### ISSUE TITLE
Media: upload files in series to provide a progress indicator

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1003]
Raised by @nylen 

Right now the media library provides no visual clues regarding progress of a batch upload, just a loading indicator.  @aduth says that we don't have a way of gauging progress of an individual file uploading.

However, we could upload files in series instead of in parallel, which would automatically provide some progress information during a batch upload.  This would be a better user experience than having the uploaded files all finish around the same time like they do currently.  Here's an example (I cut 2-3 minutes of loading time out of this video):  https://cloudup.com/iqcTBkNAeuE

**Comment by aduth** [comment]
Partially resolved by #3577, as we now upload in series, but we still do not provide a progress indicator (debatable as to whether this is desirable, however).

**Comment by nylen** [comment]
Uploading media in series does provide some progress information when uploading multiple files because they complete one at a time, which is helpful.  That was all I intended to capture in this issue; adding further progress indicators would no doubt be more involved.

Uploading one file at a time is more reliable in my testing, most likely because of Internet connections not behaving well under multiple transfers saturating upload bandwidth.  I wonder if something about uploading multiple files at once was also contributing to the previous performance issues in #1002 - from what I could see the slowdowns didn't seem to be due to excessive re-rendering.
