### ISSUE TITLE
Excerpts: Don't allow <br> to precede text

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10271]
![screen shot 2016-12-26 at 8 48 21 am](https://cloud.githubusercontent.com/assets/24388/21484472/4052e91e-cb48-11e6-91e9-0837da060e46.png)

I believe what's happening in these posts (on this stream https://wordpress.com/read/feeds/2810194) is that the first line of the excerpt is just a break tag.

We should not allow the first line to just be a break.

**Comment by samouri** [comment]
Interestingly enough, we already have [code](https://github.com/Automattic/wp-calypso/blob/master/client/lib/post-normalizer/rule-create-better-excerpt.js#L34) that does exactly this!

The reason why the starting `<br/>`s weren't being picked up was because it only looked one layer deep and so cases like this would evade the normalizer:
```html
<p>
  <br> The Occasional Hat<br>
   ....
</p>
```

I'm whipping up a PR now to fix it

**Comment by samouri** [comment]
Fixed in #10340
