### ISSUE TITLE
Publicize: Investigate disabled Jetpack

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#10332]
Per @beaulebens 

> On a Jetpack site, where Publicize is completely turned off, nothing happens when I click the Share link on the blog post listing. No errors or anything, just literally nothing happens. I’d expect to maybe have a panel slide down that tells me I need to enable Publicize to use this feature (bonus points; allow me to enable it right there).

**Comment by lancewillett** [comment]
Dropping a few more details since I didn't understand the context here when reading it at first.

#### Steps to repeat

1. Log into a Jetpack site, change Publicize setting to off in Jetpack plugin settings (under "Engagement").
2. Log in to WordPress.com, look for the site.
3. Click into Blog Posts, and click on the Share link below any post in the list.

#### Screenshots

<img width="924" alt="screen shot 2017-01-16 at 15 35 00" src="https://cloud.githubusercontent.com/assets/66797/22001314/5db842f0-dc01-11e6-95ab-8a7c9e544668.png">

<img width="966" alt="screen shot 2017-01-16 at 15 35 15" src="https://cloud.githubusercontent.com/assets/66797/22001318/69e3c5a4-dc01-11e6-8085-da606cdbd818.png">
