### ISSUE TITLE
Stats: Provide Unified View of Followers Data

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#10347]
From pKdGS-1n7-p2

Currently, follower data is displayed in 3 different places on the Insights Page:

![banners_and_alerts_and_stats_ _trout_bummin_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/21572225/bd047aa4-ce8b-11e6-8c91-556e8e10f519.png)

![banners_and_alerts_and_stats_ _trout_bummin_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/21572232/cde286c2-ce8b-11e6-8499-86365b0288bd.png)

Further complicating matters, email followers total is only shown when toggling the drop down in the followers list:

![banners_and_alerts_and_stats_ _trout_bummin_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/21572249/eaa9c69e-ce8b-11e6-8cce-1d2f4653aae5.png)

Of note, Publicize, and WordPress.com follower counts are both available in Redux. To make this task a bit cleaner, it might be nice to update Followers to use redux as well.

___Solution?__
I would love some designer feedback on this one, but I'm envisioning a new stats component on the Insights page possibly titled "Audience".  We could possibly take layout inspiration from the "Today's Stats" component:

![banners_and_alerts_and_stats_ _trout_bummin_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/21572291/3b0cc0be-ce8c-11e6-8eec-c5ef1a7657e9.png)

The boxes would be WordPress.com, Email, Publicize - and perhaps show the total number of followers in the title area of the component.  If so, we should likely update the followers number displayed in the navigation bar to include email and publicize followers too.

By chance do we also want to show Publicize "Followers" under a navigation tab in people?

![banners_and_alerts_and_people_ _trout_bummin_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/21572318/92d8c7ac-ce8c-11e6-9fc9-a0e50bd53381.png)

**Comment by folletto** [comment]
I think the main issue there is the overall page design, including the design specifically of the "Followers" block.

I'm not sure there's a simple solution to this, as I've the feeling that any additive approach would just dive us deeper in more complexity without really solving the issue at hand.

Some brainstorming:

(1) Followers: should just show all the followers in the list, regardless of source. No filter needed there, since it's just a list of the latest followers. I don't care where they come from.
(2) Followers: the counter should be counting both, and should be near the title too  

_(Note that "Comments" should have a similar treatment too, but since it can't remove the filter, that should be swapped for a pill control: `( by author | by content )`)._

Mockup:

![followers-mock-i1](https://cloud.githubusercontent.com/assets/4389/21645608/b42451d6-d28a-11e6-918a-7f8794abb61c.png)

(3) Followers: the link in the top bar imho is ok since it's fine to have multiple entry points, as well as it's a relevant indicator for the site author, and we should give to it more prominence. The panel inside stats is "just" a visualization of the latest addition, so it's fine.

(4) Followers page: it's now duplicated between `/people/followers` and `/stats/follows/`. If I haven't missed anything, the current `/people/followers` is more up-to-date and contains everything the other page contains, so I'd drop `/stats/follows` and redirect every link to `/people/followers`.

(5) `/people/followers` should have following count in the tabs menu (similar to Blog Posts).

(6) Publicize: apart from the fact that "Publicize" is a name we need to drop as it doesn't make any sense, ideally it should show the recent followers mixed i the "Followers" panel too. 

(7) Followers: the followers pane should get a deeper redesign by showing for example a graph of aggregated follows across all the sources, not just aggregated count, something like (super rough mock to get the idea, it's missing a lot of details):

![followers-mock-i2](https://cloud.githubusercontent.com/assets/4389/21646140/da56f10e-d28c-11e6-949f-529fc34d14dd.png)

Note that once we do that with followers, we can also move it to day/week/month view as it becomes actually useful to check following trends. And it would also make a good service to our users since they can finally see how much growth they had. ;)

**Comment by karmatosed** [comment]
I would agree this feels like the page itself needs to be looked at and Followers block. 

A huge +1 for followers just being any - I'm even wondering if we should include Facebook there too. Users probably don't care about splitting our the source. Perhaps a way to drill down in future would be useful but absolutely agree a summary should be all and I also feel any drilling down is a less strong user case - for those users really monitoring their following.

+1 to drop Publicize, outside our headspace it means nothing.

I like the idea of a graph or some visual source indication. That's more at a glance worthy and makes a simple latest list far more useful. Big +1 there as a starting point.

**Comment by timmyc** [comment]
I'm kind of conflicted with the inclusion of publicize "friends" as "followers" of one's site.  Granted, there are likely users who publicize all posts - and these friends on other networks might see the post, I personally do not publicize all posts.

I would have to do some digging in the old calypso repo, and possibly slack, but I think we initially launched calypso stats _without_ the Publicize module, but brought it back after feedback.

I concur that having some form of visualization around followers on the Inisghts page is likely the best path forward. The followers endpoint does return a `date_subscribed` field, along with the last 20 users that have subscribed.  With that data we could build out a viz similar to @folletto's above that is comprised of email and wpcom followers.

The x-axis date range for the follwers could be tricky.  I suppose based upon the site we could dynamically set this value between days/weeks/months etc.  Digging up an _old_ p2 thread, I dove into a chart that dealt with this quite nicely: p10gg3-2T7-p2

<img width="853" alt="dm1cy2hhaf-3000x3000" src="https://cloud.githubusercontent.com/assets/22080/21726050/e56d4bb0-d3ef-11e6-9df9-597b571ae690.png">

Note the x-axis on the chart - this chart is tracking the user's runs and since they aren't running as much as they _should_ 😆 the chart still groups the data together in one "full" chart.  Since follows might happen infrequently too, we could possibly look at a solution like that, and maybe even intersperse post data to show if/when certain posts lead to increases in followers.

**Comment by folletto** [comment]
> without the Publicize module, but brought it back after feedback.

Just to clarify since I might have been ambiguous: the _term_ "Publicize" is meaningless, not the data. The data IS truly valuable, we need to find a way to surface it.

I agree it might be better to split it out differently from direct followers... it requires some digging and design exploration. :) 

> the chart still groups the data together in one "full" chart

That chart is lying tho, it doesn't give good service imho, and would probably even create a backlash due to misleading visualization. If one doesn't get followers for a while and it is one of the goals, it is **very important to show there were no followers**. That fact is in itself a valuable data point that shouldn't be buried.

> The followers endpoint does return a date_subscribed field, along with the last 20 users that have subscribed.

Awesome!

**Comment by timmyc** [comment]
Okay I'd like to rekindle this conversation a bit, and would really love to get a solid design concept going on how to show all follower data on the Insights page.

Based upon the prior conversation, it sounds like we need to show the following:

- Total # wpcom followers
- Total # Email Followers
- Publicize Followers
- And a sum of the above 3

The sum of these values should also be the same number that is shown in the navigation bar.  Currently, this number only represents WPCOM followers ( does not include email followers).

From the current API endpoints, we have the ability to do a visualization of the change of followers over "time" based upon the last 20 subscribers.  Worth nothing this could be a very boring visualization for many users.

I feel like we should consider removing the current Followers module from the Insights page, and from this new "Followers Summary" module link to https://wordpress.com/people/followers/{site} and https://wordpress.com/people/email-followers/{site} instead.  We would need to add a link to the People email-followers page to download email followers as a CSV.

I might do a quick _try_ branch to show ^ that concept and we could iterate from there.

**Comment by beaulebens** [comment]
Worth noting that "Publicize followers" can (optionally) be broken down by connection as well. Don't know how granular you want to get, but thought it was worth mentioning. Users might have 2 Twitter accounts, or 1 Twitter and 1 Facebook, or 3 LinkedIn, etc.

Rather than referring to these as "Followers", it might make sense for the combined number to be referred to as "Reach", which is often used for talking about how many people are in your immediate audience.

**Comment by karmatosed** [comment]
I can take a run at this tomorrow. I'd like to have a think a little how we bring this in.

**Comment by karmatosed** [comment]
Looking at what you have in #10765 I'd suggest that is the best option. 

To loop back what I see is:

![2017-01-19 at 18 35](https://cloud.githubusercontent.com/assets/253067/22120118/2eee9d30-de76-11e6-8e41-67223c421d59.png)

I've got some suggestions on that but let me comment on the branch to keep the conversation there. I do agree that a chart isn't needed in this case. I think having this strip works really nicely. I also think it kind of belongs in 'Insights'. If I put my user head on I would want to know this.

**Comment by folletto** [comment]
For Insights, #10765 seems well on the way.

For Day, here's another idea from Tammie and me:

![followers-day-i1](https://cloud.githubusercontent.com/assets/4389/22159915/0ab2f4b4-df3b-11e6-9072-56721bd64770.png)

Current API limitations:

* Returns just the last 20 followers
* Returns total count

**Comment by timmyc** [comment]
#10765 has been merged but I'm going to leave this issue open for possibly implementing these other followers designs.

**Comment by folletto** [comment]
This issue is still very relevant, followers are a critical piece of stats.
It's waiting for development focus to be able to do it — it requires API and maybe even DB changes.

**Comment by folletto** [comment]
I still think that the uncertainty around follower count and who's *really* following is one of the major issues in our follow system — and on P2 it's even more problematic as people rely on notifications and it's important to know who is actually listening in the team.

However, this issue is around since 2016, and while I think this is quite a flaw, I also recognize there's nobody working on it right now. So closing with this note for the time being. Whoever is going to touch followers at some points will have to face this and make a decision.
