### ISSUE TITLE
DevDocs: /devdocs/design doesn't load on wpcalypso environment

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#10415]
#### Steps to reproduce
1. Starting at URL:  https://wpcalypso.wordpress.com/devdocs/design

#### What I expected

DevDocs components to show

#### What happened instead

Browser tab crashes

#### Browser / OS version

Chrome  55.0.2883.95 OSX 10.12.2

#### Screenshot / Video

<img width="726" alt="devdocs" src="https://cloud.githubusercontent.com/assets/128826/21664350/884107ce-d331-11e6-9b5f-537e340f6841.png">

**Comment by alisterscott** [comment]
This page works fine on master/calypso.localhost.

@gwwar has narrowed this down to https://wpcalypso.wordpress.com/devdocs/design/drop-zones

**Comment by gwwar** [comment]
Page seems fine this morning we'll need to investigate what happened

**Comment by lancewillett** [comment]
Glad it didn't persist. Let's re-open if it happens again.

Any other details you can share on how to repeat it? Any console errors?

**Comment by iandunn** [comment]
FWIW, I experience something like this regularly. I'll be making changes on a branch, then refresh, and Firefox will lock up and I'll have to force-quit, or wait ~2 minutes for it to respond to my request to close the tab.

If I switch to `master` and reopen Firefox, it still crashes. If I `clean`, rebuild, and reopen Firefox, it still crashes; same for `distclean`. Sometimes Chrome will also crash, but usually not.

It doesn't seem to be tied to a bug in the code, since is still breaks on `master`. I usually just give up working in Firefox for awhile and use Chrome, then come back to Firefox the next day, and at that point it often works again, for awhile.

It's usually happened when working in the editor or DevDocs, but that's the majority of where I spend my time too, so it might not be isolated to those locations.

If I had to guess, I'd say it's just the massive amount of code being run, combined with some bugs in Firefox.
