### ISSUE TITLE
Settings: design for `Date Format` and `Time Format` site settings

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#10441]
We can set these parameters using `/wp-admin` into the settings page - general options (/wp-admin/options-general.php)
![image](https://cloud.githubusercontent.com/assets/77539/21696620/a4a65f36-d36d-11e6-951a-bdd614bd4595.png)

So the idea is to be able to set these values from Calypso. I guess that it should be placed next to `timezone` settings:

![image](https://cloud.githubusercontent.com/assets/77539/21696711/fc52feba-d36d-11e6-8d89-b5f25553a897.png)

This is the link to get this section: `http://calypso.localhost:3000/settings/general/$site`

So the first thing that we need is a nice design :-D

cc @iamtakashi

**Comment by iamtakashi** [comment]
Here is an idea for the setting.

![1](https://cloud.githubusercontent.com/assets/908665/21832957/bd503272-d7a6-11e6-81e9-04d3e62c66c0.png)

It uses straightforward radios, but note that there are no inline input fields like wp-admin for custom format options – It’s hidden by default to avoid visual clutter for the majority of our users who likely to pick other options. The examples in the options are real time based on the site timezone like wp-admin.

When you choose “Custom”, each displays an input form with SelectDropdowns that add Tokens when you select a format. Much like SEO settings for Business plan users.

![2](https://cloud.githubusercontent.com/assets/908665/21832963/c86393a2-d7a6-11e6-96d5-bdcfc144ac7d.png)

You can create a custom format by selecting a format you want to use in the order you want to display. Once a token is in the field, you can see the preview below.

![3](https://cloud.githubusercontent.com/assets/908665/21832972/d1315032-d7a6-11e6-9923-a633b20e7b29.png)

SelectDropdowns are limited to common ones, but since it’s an input field, you can also input directly characters such as commas and colons, even the less common ones such as “T” (Timezone abbreviation) to achieve parity with wp-admin.

![4](https://cloud.githubusercontent.com/assets/908665/21832978/da267aaa-d7a6-11e6-8cc2-ba5d72adb163.png)

**Comment by retrofox** [comment]
Very nice, great job Takashi. I like it.
Some, maybe silly, questions:

1) I see that we have four options (dropdowns) for both formats (date and time). What could happen if the user wanna use only one custom value, let's say `Monday`. I guess that he/she could delete/edit them directly from the input field.
![image](https://cloud.githubusercontent.com/assets/77539/21850935/c08ab27e-d7eb-11e6-807a-00e38c747e9e.png)

2) What about if he/she wants to add more than four custom values. Make sense wondering this?

3) I see that we aren't using native select elements. I really like these customs dropdowns, but we've had to re-implement some components using the native ones thinking on mobile devices. We could switch custom-dropdown by native-select-element but the design should support this behaviour.

**Comment by Copons** [comment]
Uh! Nice ones @iamtakashi!

A week ago or so I've started working on the code-side of this: https://github.com/Automattic/wp-calypso/pull/10400
Nothing fancy, just a port of the wp-admin side, but if you want to work on this, there could be something you may want to reuse.

**Comment by iamtakashi** [comment]
@retrofox

1. Note the input field is blank to start with. So, if they want to have only one custom value, they only need to select the value to add in to the input. In your example, they would only need to select one of Day of Week. Like you guessed they can delete/edit directly if they change mind though.

2. They can have as many/few as they wish. I hope my answer to 1. clarifies this too.

3. I intended to use the native [SelectDropdown](https://wpcalypso.wordpress.com/devdocs/design/select-dropdown) but the compact one. It's true that I reduced some padding and added a plus sign at the beggining of header text. Would that cause issue? I might be misunderstanding your point here.

**Comment by retrofox** [comment]
nice @Copons.
We can join efforts here. I could continue your branch. I've seen the changes and it looks good to me. Otherwise, you could apply these changes and continue with this job?
Feel free to take whatever you want. thanks! :-D

**Comment by iamtakashi** [comment]
@Copons,
Oh, I had no idea. Thanks for letting me know!

**Comment by iamtakashi** [comment]
@retrofox,
Ah, you probably meant "browser native". Would our "Calypso native" (that's what I meant :)) SelectDropdown would cause issues on mobile?

**Comment by retrofox** [comment]
> I intended to use the native SelectDropdown but the compact one. It's true that I reduced some padding and added a plus sign at the beggining of header text. Would that cause issue? I might be misunderstanding your point here.

I guess so. I mean to native elements to those elements that are natively supported by the device. The browser in this case.
For instance, when we did the `timezone` selector the first approach was done using the select-dropdown (which isn't a native element since it's done using another html elements plus js, etc). Now the timezone looks like this:

![image](https://cloud.githubusercontent.com/assets/77539/21852524/26817008-d7f2-11e6-95c0-6e8214c14e04.png)

So what I suggest is, if it worth, switch the selectors depending on the width of the viewport or the device ... or simply implement the selectors using the native ones. Make sense?

**Comment by retrofox** [comment]
> SelectDropdown would cause issues on mobile?

Yes ...

**Comment by Copons** [comment]
@retrofox @iamtakashi No worries! I pretty much picked this from the wp-admin parity list without telling anyone. 😄 

I guess I could continue working on it, since the "tokenized" approach looks quite like the one used for the SEO title structure, and I know who to bug if I need help on them.

Either way, the main struggle is converting between PHP and Moment.js formats.
Moment uses very different tokens and doesn't even support some of the PHP ones.

**Comment by iamtakashi** [comment]
@retrofox Thanks for clarifying. I've looked #5231. Although the number of options are much less than language or timezone settings discussed there, it makes sense to go for the device native one all viewport size for this setting too. It looks like we can style it at least its face, so I'm ok with it.

**Comment by folletto** [comment]
Great discussion here. My only comment at this stage would be to avoid having all of this inside the same "General" settings page, but having a button / link / `LinkableCard`. In that way the page is shorter and clearer, and this whole UI gets the clarity of being alone in a sub-page. :)

**Comment by Copons** [comment]
@folletto That makes sense.
I've seen in Settings / Writing there's an already established pattern going on (the two taxonomy linkable cards right at the beginning).

I'd say I could group all date and time settings in a linkable card right below "Language".
Something like:
<img width="740" alt="screen shot 2017-01-13 at 16 23 30" src="https://cloud.githubusercontent.com/assets/2070010/21935158/abc8b062-d9ac-11e6-8061-970c051fd404.png">

That opens a sub-page like this:
<img width="744" alt="screen shot 2017-01-13 at 16 26 11" src="https://cloud.githubusercontent.com/assets/2070010/21935248/1f274956-d9ad-11e6-8300-d104c5076d47.png">

---

In fact, it could even be a full fledged "Locale" sub-page that includes the Language option too, but I'd argue that Language is a much more important setting that should stay in the most prominent position possible.

**Comment by folletto** [comment]
> I'd say I could group all date and time settings in a linkable card right below "Language".

I'd go with that option, yes. 👍 

Tiny detail: would be perfect if the subtitle of the linked card contained the current format, like:

![screen shot 2017-01-13 at 21 29 41](https://cloud.githubusercontent.com/assets/4389/21946244/6ab6298a-d9d7-11e6-8fcf-4a815eb867da.png)

**Comment by retrofox** [comment]
Side question: do we have a way to scroll the page to a specific card? In other words, can we position a specific section of this page when the user comes from a link? Similar way when the link has `#` in its url.

**Comment by Copons** [comment]
@retrofox I'm not exactly sure, since I guess React components aren't loaded yet when the browser tries to jump to an # anchor. We could maybe scroll to an element after its mount?

If instead you're talking specifically about settings sub-pages, such as the taxonomies ones and the proposed date/time one, there is already a system in place doing that (see: `https://wordpress.com/settings/taxonomies/category/{site}`), that I guess I could easily bring over for the date/time.

**Comment by Copons** [comment]
After some days of working on this I've noticed a couple of things that I believe should be tackled in a follow up PR to avoid over-bloating the initial one (that will then stick to a carbon-copy parity between WP Admin and Calypso):

- **Tokenized custom fields**
There are two options already available in Calypso: the `TokenField` used for tags and the `TitleFormatEditor` used for SEO title structures.
The first does not allow for free text, and the second is a Draft.js implementation deeply tied to the title structure. Ideally I would need to customize `TitleFormatEditor` to the point of making it useable for this purpose. It's not easy though, and we have the additional complexity of having to convert twice the formats: Draft.js tokens -> Moment -> PHP.

- **Date and time formats own sub-page**
Obviously enough, taxonomies are not site settings, therefore their sub-pages are stripped down of the entire logic we have in place for handling the site settings.
Moving the date/time formats into a new page means copypasting a considerable amount of stuff over from `site-settings/form-general.jsx`.

In both case, a short-ish and manageable-ish PR would instead become daunting.
I'd say: keep working on the current changes in #10400 (which also entail some backend changes), hide them behind a feature flag and later iterate and improve.

**Comment by retrofox** [comment]
@Copons I'm sorry for the delay to answer.
I do not completely understand what are you trying to say. Should we forget/get rid of some piece of the design here?

**Comment by Copons** [comment]
@retrofox Oh no, not at all!
Just, I'd rather tackle tokens and sub-pages in separate PRs as they're likely gonna be quite beefy.

**Comment by iamtakashi** [comment]
I'm also confused what's been proposed here.

Anyway, I strongly feel that we should avoid a carbon copy of the setting in wp-admin since the custom format setting  feels like only for programmer, and difficult to use for the majority of our users.

I'm not saying my idea is perfect, and there might be a better idea, but we should avoid a carbon copy parity for the setting.

**Comment by iamtakashi** [comment]
As soon as I post the previous comment I saw the clarification :/ It looks like we've misinterpreted the suggestion. Thanks for clearification @Copons.

**Comment by Copons** [comment]
I believe I'm explaining poorly.
I'm only proposing of splitting the development of this feature in several steps to avoid over-bloating single PRs.

Step 1: carbon copy (pretty much what I have already done anyway).
Step 2: move the date/time formats in their own sub-pages
Step 3: add token fields
Step 4: ship to prod

**Comment by melindahelt** [comment]
Adding a suggestion that I user submitted at 3025440-t to display UTC + City together in dropdown.

**Comment by mtias** [comment]
I stumbled on this while checking my site settings and the amount of vertical space we are taking for seldomly used settings doesn't seem great.

I don't think it warrants its own page, but what about combining all these under a segmented control navigation?

![image](https://cloud.githubusercontent.com/assets/548849/23704158/d5041e22-0403-11e7-9ce3-0bcf4428bd1b.png)

cc @iamtakashi @folletto @Copons @retrofox

**Comment by Copons** [comment]
@mtias Date/time/week sub-page is pretty much ready to go (and I'd say it could also include the Timezone setting) 🙂 
https://github.com/Automattic/wp-calypso/pull/11259

Also, it's almost essential to introduce the date/time format "tokenization", since I need to add a lot of new stuff and doing so in `form-general.jsx` would be utter madness.

**Comment by mtias** [comment]
I see, so this was being worked on separately twice?

**Comment by Copons** [comment]
@mtias What do you mean?
The decision to move in a sub-page came up when I was almost ready to ship the date-time-week in `form-general` so I chose to merge that anyway and then move it in the sub-page (without touching the Timezone part that was (is?) worked on by other people).

This said, nothing stops us to add the segmented control to the sub-page.
Just, please please please please, I need the sub-page as a sort of clean slate to work on the tokenization!

**Comment by lancewillett** [comment]
Is this related to work in https://github.com/Automattic/wp-calypso/issues/11316?

**Comment by Copons** [comment]
@lancewillet Nope, while this internally uses the locale settings for preview purposes, it only takes care of the date/time formats used in themes.
