### ISSUE TITLE
Component: scrollbar

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#1050]
@folletto: We're at a point that to implement certain UX improvements we need to have a scrollbar component. Namely:
1. Notification panel
2. Calypso sidebars
3. Editor sidebar
4. New post site selector

This is important to achieve a few things:
- Avoiding the "white band" effect for anything that isn't the right-most scrollbar on the window (or a text field).
- A consistent styling across platforms.
- Desktop "app" feel on desktop.

Which is why it's crucial in the four UIs mentioned above.

Notice that this isn't anything weird, and it's probably something that you used without even noticing in other apps, for instance:
- Slack sidebars are a custom jQuery component they developed (but not released unfortunately)
- Facebook notifications pop-up is very well done too

A couple of notes:
1. The bar should be easily skinnable, even if on Calypso we are likely going to create a canonical version to be used most of the time.
2. It should detect and support the platform user-set configuration "Jump to the next page" and "Jump to the spot that's clicked" ([screenshot](https://cloud.githubusercontent.com/assets/7233112/11481167/b9c7fda2-9769-11e5-922e-aa4187a89744.png)) if possible (not sure).
3. It should allow both "fade in on hover / scroll" and always present modes.

As a reference, I think we should take Slack's one:

![image](https://cloud.githubusercontent.com/assets/7233112/11481171/c5301f26-9769-11e5-9c0a-7680bd2236e2.png)

/cc @mtias @jasmussen 

Also it seems Slack does indeed intend to release the plugin at some point: https://twitter.com/SlackHQ/status/426471189280595968 (though the presence of "jQuery" in that sentence unnerves me).

This might be handy to look at: https://github.com/nylas/N1/blob/master/src/components/scroll-region.cjsx

Nice custom scrollbar

**Comment by folletto** [comment]
Another interesting scrollbar implementation to benchmark:
https://noraesae.github.io/perfect-scrollbar/

Interesting bits:

* Has a jQuery wrapper, but it's not jQuery
* Styleable
* AMD support

**Comment by jasmussen** [comment]
That one looks good, Davide, but the example on that page is a little bit stuttery to drag around. Especially on mobile.

**Comment by folletto** [comment]
Yeah. This sidebar thing is going to take us a while to be nailed properly :|

**Comment by shaunandrews** [comment]
During some research while working on #1442 I found this: http://stackoverflow.com/a/19694424

The relevant comment mentions the following about Facebook's custom scrollbar:

> The scrolled content is actually scrolled natively by the browser scrolling mechanisms while the native scrollbar is hidden by using overflow definitions and the custom scrollbar is kept in sync by bi-directional event listening.

Interesting. So Facebook doesn't do anything to handle the scrolling—they leave that to the browser—but they _hide_ the scrollbar with some overflow trickery and track scrolling to display/update a div.

**Comment by jasmussen** [comment]
> Interesting. So Facebook doesn't do anything to handle the scrolling—they leave that to the browser—but they hide the scrollbar with some overflow trickery and track scrolling to display/update a div.

I tried this a while back with a WordPress theme I was experimenting with. I think I got it working reasonably well. If we can combine it with some stock scrollbar styling, perhaps we can get something cool going. Codepen time?

**Comment by folletto** [comment]
Great finding! :)

**Comment by jasmussen** [comment]
Found this new react component that supplies custom scrollbars, it looks promising:

https://github.com/malte-wessel/react-custom-scrollbars

Unfortunately the component doesn't itself provide a way to prevent scroll-bleed. However since using this component would provide us with styled scrollbars with a predictable and cross-platform uniform scrollbar width, we could use this neat trick, which is fairly clean, to prevent scrollbleed: http://codepen.io/joen/pen/wGbBoe

**Comment by folletto** [comment]
Here's a related analysis on a similar problem found by @jasmussen that could be useful:
https://developers.google.com/web/updates/2017/03/custom-scrollbar

As well as the GitHub repo:
https://github.com/GoogleChrome/ui-element-samples/tree/gh-pages/custom-scrollbar

**Comment by oigewan** [comment]
@folletto I've been given this task as my trial project.  I have a couple of questions about the requirements for this component, and since you've either been mentioned or commented on this issue since the beginning, I'm hoping you can help me out.

**Supported Browsers:**
Background:  I did mobile front-end component development for the front-end framework used on the amazon.com retail website, but that was about 2.5 years ago.  The browser landscape has gotten better, but I need to know how many of my old tricks need to be dusted off for this.

I have some ideas about supported browsers from our [autoprefixer settings](https://github.com/Automattic/wp-calypso/blob/master/Makefile#L24), but Android isn't mentioned anywhere.  Is our Android support just last two versions of Chrome?

**Testing:**
I have a personal device I can use for testing (Nexus 5X), and I can download IE VMs.  However, I don't have any OSX or iOS devices to test on (I run Linux at home).  Do we have any tools to support testing on multiple browsers/mobile devices?

**Features:**
- Is preventing scroll bleed a requirement for this component?
- Default styles:  The original issue comment mentions the look of Slack's custom scrollbar.  Is that what we want for a default?
- Should this be capable of replacing the browser's scroll bar?

**Comment by folletto** [comment]
Hello there!
Sorry for the late answer.

Browser Support: yes, we tend to support only the latest two versions. Consider that on mobile we offer also the native apps, so we have two channels on these devices. Scrolling to be effective on mobile is a requirement, however, we can evaluate the approach, as natively these devices don't show scrollbars unless scrolling starts.

Testing: I'm not sure about that as I've OSX and I can run virtual machines... I'd suggest to be extensive and we can cross-check on Safari. Let's start with what we have, just be clear during your PRs that something wasn't tested on some machine/browser.

Features:

1. Ideally yes, but consider the current baseline is "no regression", so we can check case by case. I'd expect this kind of work to improve the scroll bleed tho.
2. Styling wise slack is a good choice, but you can refer to alternatives if you think it's the case. The reference to Slack is mostly because it's just two shapes (background + puck) so building something basic like that and making coloring flexible (via CSS) is a good starting point.
3. Yes, but it's a _secondary_ goal. The reason is that if we have this component, we'd like to be able to use it more extensively, if possible and if performs well enough.
4. No scroll buttons.

I hope it helps. :)

**Comment by oigewan** [comment]
@folletto 
No worries on the late answer.  My day job kept me busy during the week anyway.

For obvious reasons, I'd like to use CSS styling solutions if at all possible.  However, given the requirements, that won't be possible.  Specifically, this requirement listed in the original issue:

> It should allow both "fade in on hover / scroll" and always present modes.

I can make the scrollbar show/hide on hover, but animations refuse to play.  I tried animating the background color and opacity.  Nothing would happen.  However, toggling the visibility property on hover worked fine.  Also, since scrollbars don't count towards the width of the element, hiding the scrollbar on Window and Linux looks terrible anyway, since the scrollbar still takes up space even though it's invisible.

For reference, the Slack example uses CSS to style to scrollbar, but just leaves it as always visible.

If the aforementioned requirement is still valid, I'll need to replace the scrollbars with `<div>` elements in every single browser, even if the browser supports scrollbar customization via CSS.  That does make things a bit more difficult since a CSS solution will be far more performant on mobile browsers.  However, I'm willing to give it a go.

**Comment by folletto** [comment]
> However, given the requirements, that won't be possible.

Yep, we have already ruled out pure-CSS implementations.
It's why the issue is about creating a React Component. ;)


> For reference, the Slack example uses CSS to style to scrollbar, but just leaves it as always visible.

Se you can read from the comments above, Slack itself uses a custom jQuery library. For us, the idea is to analyze existing custom scrolling libraries, and build a reusable (not Calypso-specific ideally) React component that is able to wrap any node and make it scrollable.

Facebook seem to have another good implementation in the notifications dropdown, and I'm sure there are a number of existing React implementations around that are worth analyzing for performance and features. If there's an existing library that satisfies all our needs, and it's not huge, we can totally just use it instead of rebuilding it. We need some analysis to see if it's the case tho.

**Comment by oigewan** [comment]
> It's why the issue is about creating a React Component. ;)

Understood.  Just wanted to confirm something that was mentioned in this issue two years ago.

I've moved out of the investigation phase, and a PR is open.  Shouldn't be merged yet (need to feature flag it's integration into the sidebar), but you can have a look at where I'm headed.
