### ISSUE TITLE
Editor: "Add Media has moved to a new button" message keeps returning

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#10568]
A message saying "Add media has moved to a new button" appears in the editor more than once, even if you've already clicked "Got It" to accept the message. Can we do something to make the dismissal stick so it's only shown once?

#### Steps to reproduce
1. Start a new post from the post button or visiting wordpress.com/post directly
2. Note the "Add media has moved to a new button" message and click "Got It"
3. Return to the same page some time later and not the message has returned

#### What I expected
Clicking "Got it" to dismiss the message permanently. It seems like it's been showing for some time now, is it still needed at all.

#### What happened instead
The message returns during future visits.

#### Browser / OS version
Chrome 55, OS X 10.11.6

#### Screenshot / Video

![add media editor message](https://cloud.githubusercontent.com/assets/1900444/21864709/090ddeca-d811-11e6-8e74-6db88ac826d4.jpg)

cc @tonischneider

**Comment by aduth** [comment]
Possibly related: #202

Can you go to the My Profile section to see whether you're prompted for 2FA refresh code?

**Comment by kriskarkoski** [comment]
> Can you go to the My Profile section to see whether you're prompted for 2FA refresh code?

https://wordpress.com/me? If so, I am not prompted for a 2FA code there and just logged in fresh no more than a week ago.

**Comment by aduth** [comment]
Okay, in that case cc @Copons @mcsf (#9699, #10131)

**Comment by Copons** [comment]
We had previously noticed this issue in case of missing 2FA, but never otherwise. 
In a recent PR I had to manually wipe all the local content on every reload to force the tour to show to test my changes.
I'll test it again as soon as I can.

cc @lsinger

**Comment by Copons** [comment]
Can reproduce in **production** (wp.com unproxied) only.

**Comment by Copons** [comment]
Ok, along with @lsinger I believe we pinpointed what goes wrong:

1. Log in (unproxied) with 2FA.
2. Open the post editor (`https://wordpress.com/post/{siteId}`).
3. Wait for the GT to show (roughly 10 seconds), and click on "Got It" to dismiss it.

Now there are two alternative possibilities here:

1. Navigate away by clicking, for example, the "<- Back" button in the sidebar.
    - The GT preference gets saved correctly.
    - The GT won't show up again anymore.
2. Reload the page (`F5`, `cmd+R`, etc.).
    - The GT preference is not saved.
    - The GT will show up again.

Since in dev the preference is saved either way, this makes me wonder if, in prod, `savePreference` is somehow tied to the page routing.

**Comment by aduth** [comment]
>Since in dev the preference is saved either way, this makes me wonder if, in prod, `savePreference` is somehow tied to the page routing.

I don't think it should be. So 2FA is not related to the issue? I'd guess the cache would be different between environments, though this should clear itself up assuming we're requesting preferences at some point (we are, right?).

**Comment by Copons** [comment]
@aduth In dev and stage, an invalid 2FA definitely prevents saving the preferences. That's something that was established pretty soon and, as far as I know, is an open problem for the Guided Tours (and possibly other preferences-related parts).

So 2FA is related to prefs saving, but apparently not to this particular issue.
"Apparently" because it could part of the same problem but I don't have enough knowledge of it to be 100% sure.

**Comment by aduth** [comment]
@Copons I encountered this locally in development when I refreshed the editor after clearing all storages. Might be that we're not waiting for preferences to have been loaded before deciding to show the prompt?

Also, are we planning to remove this prompt at some point?

**Comment by mcsf** [comment]
FYI, #10616

**Comment by Copons** [comment]
@aduth I'm not involved in the GT inner workings, so I believe it's better to let others answer to that.

If we want to remove this particular tour (or hide it behind a debug flag): I'm definitely ok with it, since I'd say that at this point, after a month, it should have done its job.

**Comment by roundhill** [comment]
@copons let's go ahead and remove it for now since we haven't nailed down the root cause. This is bothering quite a few users I guess.

**Comment by Copons** [comment]
Ah! @mcsf you beat me to it! 😄
