### ISSUE TITLE
Reader: site blocking can fail on some site streams

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#10625]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/feeds/25704283
2. Click block the ellipses menu and block site

#### Video of brokenness
![broken-block](https://cloud.githubusercontent.com/assets/4656974/21941981/33e29b16-d999-11e6-8313-e14eb87b6549.gif)

#### What I expected to happen
the site should have stayed blocked for more than a split second

**Comment by fraying** [comment]
That "you have blocked..." state is also problematic. It hasn't been updated for the refresh. But more importantly, is showing that message over and over really the right thing to do? Wouldn't it be better to only show it once? Or even just bounce you out of the page and back into Reader with posts from that site omitted?

**Comment by raoulwegat** [comment]
Blocking worked fine for me on that feed.

![reader-blocking](https://cloud.githubusercontent.com/assets/2627210/21966807/de860968-dbce-11e6-9ffd-4ce0ad72786c.gif)

**Comment by bluefuton** [comment]
@fraying "you have blocked" state is updated for Refresh in https://github.com/Automattic/wp-calypso/pull/10604 :) That's the PR @samouri was testing when he found this glitch.

@samouri blocking also works fine for me on that feed. Can you check the API response from the site blocks endpoint for me? I suspect that's where the problem lies.

> Wouldn't it be better to only show it once?

Absolutely agree - the repeated blocked card feels pretty odd on a site stream. We might be able to use the same technique as with the upcoming Combined Cards to consolidate them.

> Or even just bounce you out of the page and back into Reader with posts from that site omitted?

Unfortunately we can't do this yet, because we don't have an API endpoint that lists the sites a user has blocked. It's the first thing I'd tackle if we take on the Site Blocks Improvement project at some point this year.

**Comment by fraying** [comment]
@bluefuton Hey thanks - I'd missed #10604 somehow. Feel free to cc me whenever you're refreshing.

> we don't have an API endpoint that lists the sites a user has blocked

Surprising! And good to know.

**Comment by samouri** [comment]
Update: still happening for me.  Just tried to block the site at: http://calypso.localhost:3000/read/blogs/89773126

Sample request response:

Request:
```
POST to: https://public-api.wordpress.com/rest/v1.1/me/block/sites/89773126/new?http_envelope=1
```
Response
```
{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"success":false,"modified_sub":false}}
```

**Comment by bluefuton** [comment]
@samouri are you using your Automattic account? I don't think superadmins are able to block sites.

**Comment by samouri** [comment]
@bluefuton I'm using a non Automattic account but I _am_ proxied

**Comment by bluefuton** [comment]
@samouri and you always get a 200 response with

`"success": false,
 "modified_sub": false`

?

Think we'll have to do some debugging on the endpoint. Ping me with the user details and I'll investigate!
