### ISSUE TITLE
Design Tweak to Stream Selected State

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10676]
Currently a selected post in the stream looks like this.

![before](https://cloud.githubusercontent.com/assets/24388/22001168/25e0e336-dbf8-11e6-882a-2f473367da87.png)

This design is awkward because the blue line is disconnected from the divider lines and too close to the post.

Would it be possible to update the design to something like this?

![selected](https://cloud.githubusercontent.com/assets/24388/22001193/485dddec-dbf8-11e6-9536-39a35880ebca.png)

Changes:
• Grey lines connect with blue line (this matches the way selected things look in the notification menu).
• Blue line is moved to the left so that the space below card is the same as to the left of the card.

cc @raoulwegat, @blowery, @samouri

**Comment by samouri** [comment]
@fraying I think the design here is definitely a nice improvement!

A couple questions:
1. in order to connect the grey lines with the blue one wouldn't we need to move the blue line right instead of making the grey lines longer? Otherwise the selected component would be the only one with longer grey lines (or do you mean make ALL the grey lines longer)
2. I think we will need to move the selected card's content to the right.  So then when you keyboard through cards they jump to the right into their `selected` state (to make room for the padding between the blue line and the start of the post).  Extending all the grey lines could also solve this problem?

**Comment by fraying** [comment]
@samouri 

Re: 1: I was suggesting making the grey lines of just the selected post longer. Yes, that makes it different from all the others, but that's the point. 

Re: 2: That's what I'm trying to avoid. Moving the content makes it harder to read, especially if you're keying quickly through the page. The only thing that should move is the indicator (the blue line).

**Comment by samouri** [comment]
Thanks for the clarifications  @fraying! I appreciate it

**Comment by blowery** [comment]
We might be able to pull this off by adding gray borders to the top and bottom of the selection pseudo-element... if we can get those to magically line up, we wouldn't have to mess with the content in the card at all.

**Comment by jancavan** [comment]
I think we should keep the current style mainly because it's easier to make it consistent with combined cards. If we connect the blue and gray lines, combined cards would have to be styled differently:

![screenshot 2018-03-12 10 41 01](https://user-images.githubusercontent.com/4924246/37300065-46d045c0-25e2-11e8-86d6-545722ee74a3.png)
