### ISSUE TITLE
Jetpack: can't export or import inside Calypso, sends me to wp-admin

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#10894]
#### Steps to reproduce
1. Starting at URL: /settings/general/example.mystagingwebsite.com (a Jetpack self-hosted site connected to WordPress.com)
2. Click on Export or Import in the settings section navigation.

#### What I expected
To open the import or export view in Calypso.

#### What happened instead
A new page or tab opens in the browser, with my self-hosted site's wp-admin interface. It's often jarring because I'm not logged in, and have to reauthenticate.

#### Screenshot / Video
<img width="784" alt="screen shot 2017-01-24 at 13 12 33" src="https://cloud.githubusercontent.com/assets/66797/22264860/cd51a09e-e236-11e6-9541-5b89a31c05d7.png">

#### Context / Source
How I feel: #stresscase #painpoint

How I found the issue: #dogfooding #manual-testing

**Comment by lancewillett** [comment]
Project note: this falls into JPOP's "Calypso-Jetpack" gaps list — possibly a trial project also.

**Comment by caydijay** [comment]
In order to enable exporting Jetpack enabled sites through Calypso, we should create a new Jetpack REST API that wraps the [export_wp](https://developer.wordpress.org/reference/functions/export_wp/) function.
However, WPCOM serves the export file differently than WPORG.
WPCOM saves the export file for 7 days for whenever-download.
WPORG returns the file immediately.
In order to match the UX, we should store the export file in the site's media library.
(There are also issues with file sizes, timeouts, etc. that means turning it into an asynchronous process and storing the file is ideal).
However, there are a couple issues with storing things in the media library.
Because the media library is publicly accessible, some notion of restricted access needs to be added.
Also, the export files should be cleaned up after some period of time.

Here's a list of things that need to happen to enable exports:

* create a folder for storing restricted access files, ie. a hidden folder
  * create a script for validating access to a hidden folder
  * modify the .htaccess file using [add_rewrite_rule](https://developer.wordpress.org/reference/functions/add_rewrite_rule/) to redirect requests for the hidden file to the validation script
* modify [export_wp](https://developer.wordpress.org/reference/functions/export_wp/) to take a flag
  * if the flag is present, modify the query to save the export file in the hidden folder of the media library
* create a Jetpack REST API for fetching the export file
* create a Jetpack REST API to fetch the status of the export
* create a Jetpack REST API that
  * forks a process to call [export_wp](https://developer.wordpress.org/reference/functions/export_wp/)
  * saves some information in the database regarding the status of the export
  * sets up a cron job to delete the file using [wp_schedule_single_event](https://developer.wordpress.org/reference/functions/wp_schedule_single_event/)
* modify calypso so export related functions call the corresponding Jetpack endpoints if it's for a Jetpack site

You can find all of my notes / research [here](https://jetpackp2.wordpress.com/author/caydijay/) if you're an Automattician.

**Comment by lancewillett** [comment]
Though possibly a very important feature in the future of WordPress, as core WP moves to a JS + API driven system much like Calypso, it's not urgent to fix this for the current time.

Let's re-open in the future when we get back to working on this. Closing for now due to higher priorities.
