### ISSUE TITLE
Editor: in IE11/Edge screen jumps when switching to the HTML editor 

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#10991]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post in IE11 or Edge
2. Switch to HTML editor

#### What I expected

HTML Editor shown

#### What happened instead

Screen jumps down to bottom

#### Browser / OS version

IE11 and MS Edge on Windows 7

#### Screenshot / Video

![ie11](https://cloud.githubusercontent.com/assets/128826/22357604/0a5dc26a-e485-11e6-86f5-2895a70c7a93.gif)

**Comment by Copons** [comment]
Self-reminder: it might be enough to remove [one line](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/editor-html-toolbar/index.jsx#L169).
Unfortunately, I need to wait for https://github.com/Automattic/wp-calypso/pull/11325 to merge, since I've changed the insertion logic for non-IE11 browsers.
