### ISSUE TITLE
Themes: on Jetpack sites when trying a .com theme it jumps briefly in the "Uploaded" list

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#11038]
![cap-](https://cloud.githubusercontent.com/assets/4389/22426233/7bd123ce-e6f6-11e6-812e-84857f10230d.gif)

Steps to reproduce:

* Open a Jetpack site (on Staging/Horizon)
* Open Themes
* Find a free .com theme at the top, tap ••• and select "Try & Customize"
* Notice it briefly shows up in the top list

It's expected to not show up: .com themes always stay as .com themes (i.e. they are filtered out from the top list).

/ht @lamdayap @richardmuscat

**Comment by seear** [comment]
Problem here is that the filtering is done when receiving the list of themes from the API. When we install a wpcom theme onto a jetpack site, we call `receiveTheme()` (which is not filtered) to add the theme to the query manager. This is necessary for showing the _thanks_ dialog content, but also adds the theme into the top list.

**Comment by ockham** [comment]
Good find @seear -- so that's [this line](https://github.com/Automattic/wp-calypso/blob/0e0623e0c5b808f25f2ce2aef11489d6d1a4a04e/client/state/themes/actions.js#L425).

I wonder how we handle this in a way that doesn't couple it too tightly to our UX. Wrap that line in a condition inside `installTheme` seems suboptimal, since that action is otherwise perfectly agnostic of whether it's installing a dotcom or a dotorg theme. Maybe rather move `receiveTheme` to a different action that's dotcom specific, such as around [here](https://github.com/Automattic/wp-calypso/blob/0e0623e0c5b808f25f2ce2aef11489d6d1a4a04e/client/state/themes/actions.js#L329).

It should be correctly highlighted after activation even if it is in the bottom list only, right? The activation endpoint will return the `-wpcom` suffixed theme ID, but our `isActive` selector handles that properly already.

**Comment by seear** [comment]
> Maybe rather move receiveTheme to a different action that's dotcom specific, such as around here.

I believe the thanks dialog is looking in the site specific store, but maybe we can adjust that.

@budzanowski were discussing briefly and thought that, strictly, the filtering is a visual operation and should be closer to the UI layer.

**Comment by ockham** [comment]
> @budzanowski were discussing briefly and thought that, strictly, the filtering is a visual operation and should be closer to the UI layer.

Yeah, that might make sense. That might work for the (unpaginated) top list, but I've been actively avoiding it for the bottom list where it might collide with the QueryManager's pagination...
