### ISSUE TITLE
Add "Mark As Read" option to notifications

### ISSUE THREAD

**Issue by ValeDeOro** [Automattic/wp-calypso#11053]
The reader alerts me every time there is a comment, a "like" or a mention of myself in the WP universe. Some of these notifications require me to click (to read a comment for example). Some of them require no action but a mental "OK, I have seen it". 

#### What I expected

The things I click on get marked as read. I would like to mark everything else as read as well. 

#### What happened instead

Instead, my list ends up with the unimportant stuff being highlighted, while the important stuff is not highlighted any more (because I clicked). 

![](http://cld.wthms.co/yyoh/GpU3P1zZ+)
Link to screenshot: http://cld.wthms.co/yyoh/GpU3P1zZ

#### Browser / OS version

Reader version 2.2.0 on Mac, though same happens across platforms. 

#### Screenshot / Video

The reader tells me YET AGAIN that there are 4 new items... but there is only one new alert, the other two are from earlier today... but they will end up being remarked upon until I finally click on them. Only then to they stop alerting me.

#### Context / Source

I use the reader for almost all my information management via P2s at A8C and there are a lot of likes going around that do not need me to click through again and again. 
So in my private world, without that many interactions, the notifications would be fine. But as a power user it would be nice to be able to just mark everything as read to keep track of how far I have to track back to catch up. 

@drw158

**Comment by gibrown** [comment]
Some background on where the current behavior came from: We really didn't/don't want to have yet another inbox to manage, having a mark as read button would make it more of an inbox rather than a list of notifications.

IIRC there is a high water mark (a timestamp) in the stream of notifications that could be used to indicate what is new in the stream. I think we played with adding that at one point (a line in the UI for instance above which everything was new), but decided it made the UI too complicated for more normal users.

**Comment by drw158** [comment]
I'll close since we don't have a plan on implementing this feature, even though it has been often requested.
