### ISSUE TITLE
Plugins: how do we best inform users of existing features in Jetpack?

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#11064]
Currently some top plugin features are already covered by Jetpack/WordPress.com. How do we inform users that they might not need the plugin?

I'm thinking a banner notice on the individual plugin page would work.

Example: `Your site already has the best security. Read more about your site's security before installing this plugin.`

Top categories I think this will be useful for:

- SEO (the new settings tab provides a lot of basic SEO)
- Google analytics (they will already have this feature in Jetpack as a business user)
- Security/2fa/Spam (we have all the security they need, right?)
- Sitemaps
- Cache (wp cache will be already installed?)
- e-commerce (they should use woocommerce, hopefully they will know about it)
- copy post (we have it now!)
- contact forms (we might have all that they need with the built-in builder)

Strategies on doing this:

- detect top plugins in each category
- detect plugin category from tags

For SEO, we detect a few of the top SEO plugins and turn off our SEO module in Jetpack.

cc @roundhill

**Comment by roundhill** [comment]
It looks easy enough to have a list of the top plugin slugs and assign them a category like `SEO. Then it's easy enough to show a notice when they browse to a plugin that matches the category.

Quick experiment:
<img width="737" alt="screen shot 2017-02-15 at 3 50 13 pm" src="https://cloud.githubusercontent.com/assets/789137/23000746/b27dae2c-f396-11e6-808b-7de14d6a556e.png">

**Comment by Copons** [comment]
Isn't this something that could be felt outright hostile by plugins authors?
The Yoast SEO example is quite particular too as, if I'm not mistaken, it offers many more features than our SEO tools, so we could even "damage" the end user too.

**Comment by roundhill** [comment]
> Isn't this something that could be felt outright hostile by plugins authors?

That's an excellent point!

**Comment by roundhill** [comment]
Maybe a less intrusive way (and less offensive to plugin authors) would be to add this to the Eligibility warnings?

**Comment by drw158** [comment]
Maybe, but I think our priority should be with the user. For example, if they pay for Yoast premium, and they only use the Yoast features that are already built in with Jetpack, then they are being taken advantage of. It's our job to communicate our features better. There are many sites/tutorials out there that say, WordPress doesn't have this or that, so you need to install this certain plugin. We have to actively fight against that.

I've been trying to think of a comparable situation... I know that my iPhone has a camera app on it, so I not going to buy one unless it does something better than the native one. Everyone knows they have a camera on their iPhone because Apple does a good job of lettings users know they have it – it's right on the home screen.

**Comment by drw158** [comment]
> Maybe a less intrusive way (and less offensive to plugin authors) would be to add this to the Eligibility warnings?

This wouldn't work for any future plugins they might install, but it would be less intrusive.

**Comment by drw158** [comment]
Maybe we should be thinking about it like a compatibility warning? I think some plugins warn you if you already have a similar plugin installed.  I think this happens after you active the plugin.

**Comment by roundhill** [comment]
> This wouldn't work for any future plugins they might install, but it would be less intrusive.

Oh yeah, I didn't think about installing future plugins.

**Comment by roundhill** [comment]
> Maybe we should be thinking about it like a compatibility warning?

I think you're on to something. Messaging like `This plugin may not be compatible with (Feature)` informs the user about the conflict and also raises awareness of the wp.com feature.

**Comment by Copons** [comment]
> I know that my iPhone has a camera app on it, so I not going to buy one unless it does something better than the native one. Everyone knows they have a camera on their iPhone because Apple does a good job of lettings users know they have it – it's right on the home screen.

But see, Apple doesn't stick a disclaimer on the iTunes Instagram page (sorry for the bad example, I have no idea what's going on in the world of 3rd party camera apps 😄 ) saying like "You can already shoot photos with the default Camera app and filter them in Photos".

Apple's promotion of their own features begins before - and continues outside - the app store. We could even say that people buys the iPhone because of the Camera app and the cool Photos edit options.
In the same way, we should be better at educating the users of what our own products do.

Inside Calypso we can improve NUX for new users (correct me if I'm wrong, I'm not super aware of what's going on regarding NUX) and use Guided Tours for new features.

Outside Calypso... I actually don't know what's currently going on for non-dev users.
I know sites and subreddits where I can learn about, say, new Jetpack features or where to find the core changelogs, and I guess most other WP-oriented devs do it as well (and non-WP-oriented are tech-savvy enough to find them by themselves).
But what about the normal users? Are there reputable sites for them that publish news about WP?

I mean, when Apple releases a new iOS version, I can find in-depth articles about it on any mainstream newspaper sites. And then, if an user would rather use Instagram to shoot photos instead of the default Camera app, so be it.

I'd say that this would be a good approach for us too.
We do our job of advertising our SEO Tools inside Calypso with NUX, GT, etc., and outside Calypso with mainstream articles (promoted maybe?), etc.
Then, if some users want to pay YOAST even if they only use one single free feature that we offer too, well, it's their choice.

**Comment by drw158** [comment]
I think changing the perception of what features WordPress.com has, is a big problem we've been fighting for a long time. Adding a "Plugins" page that lists all of our features has probably helped, but I don't know if we can quantify how much it has helped.

Looking at the top plugins that people install is pretty depressing considering that they don't need to install those plugins if they have Jetpack. After we launch AT, we'll need to see if those plugins  _continue_ to be the most installed. If we monitor the stats and see that the top 5 plugins aren't doing anything for our users, then something will need to change.

Unfortunately everything is bundled up into Jetpack, so it's hard to see what features Jetpack provides. I've done some [mockups](https://cloud.githubusercontent.com/assets/618551/23075198/296ae570-f501-11e6-9dd7-c6cf16610e33.png) before, that try to show what you're getting with Jetpack.

I think the best solution is to list out features separately in the plugin list, but that probably won't happen and will require a major change in how Jetpack is presented to users. Showing a banner in the single plugin page I think will be most effective for the time we have. 

Alternatively we can try and catch it before they reach the single plugin page. One idea is to show a notice if they starting searching for "SEO", informing them that they have SEO already.

@dan: I just had a though. Will we be able to know the top plugins installed that have gone through WP.com vs. just installing Jetpack self-hosted? I think it will be vital to separate those.

**Comment by apeatling** [comment]
I think this is a good idea, but it needs to be framed correctly. I'm not sure we can blindly promote our own offerings here and expect that to sit well with plugin authors. I don't think it is our place to tell a user what SEO features or plugin they should be using. If they want to use Yoast SEO because they believe it is better, that is their choice.

What I do think we can do here, is be helpful to the user and inform them of functionality conflicts that will occur if they install a plugin. This is where the example differs from the iOS examples above, there is potential for two plugins installed at the same time to badly conflict with one another. In the above example the messaging could be more like:

> Installing this plugin may conflict with the following plugins already installed on your site:
>    * SEO tools [settings]

This could apply equally for all the top plugins, so if you try and install two popular SEO plugins you see a similar warning.

**Comment by drw158** [comment]
Would this detect actual conflicts with our features, or would it just detect that the plugin they are trying to install is SEO related and we just say that it _might_ have conflicts.

At the moment, if you install Yoast it just overrides the SEO settings we have in Jetpack and the SEO module is disabled.

**Comment by apeatling** [comment]
I think just saying that it might have conflicts is enough.

**Comment by roundhill** [comment]
OK, I'm going to start working on this. @drw158 I noticed you had eCommerce on there, should we skip that for now since we don't have any offerings?

**Comment by gibrown** [comment]
A couple of thoughts:
- I think this is going to be hard to implement and maintain with any particular set of tags. Also it will make it significantly harder to handle non-English languages.
- I don't think we need to add this to the plugin's page when we could just show it as a part of the search results
- On the search results it should be pretty easy to highlight plugins that the user already has installed and recommend that they use them instead.

By applying this generically to the search page we can solve this problem for more than just Jetpack. If the user has any plugin installed and they go looking for another feature, then we can just recommend that they use whatever they have. Doesn't need to be perfect to help the user a lot. This would probably be a generally useful feature for core at some point, and implementing it in a generic way would be a good test of that (we should add some Tracks events here too).

**Comment by roundhill** [comment]
> By applying this generically to the search page

@gibrown Interesting idea. So if they search for something that may conflict like `cache`, we would show the banner at the top of the search results?

**Comment by gibrown** [comment]
@roundhill ya, that way we're steering them towards a solution sooner. Should be pretty easy to implement, and the search results page needs some work IMO.

**Comment by apeatling** [comment]
> I don't think we need to add this to the plugin's page when we could just show it as a part of the search results

The issue I have with that is that does the user care until they actually select a plugin? There is no intent in the search results, but when you click one, there is more intent to install and the information is more useful to the user.

I think to begin with to get a feel for how this will actually work, and if it makes sense we should stick to a plugin page and just our own plugins.

**Comment by gibrown** [comment]
Hmmm, I think we know a lot more about the user's intent on a search page since we know what they searched for. If the user searches for something that Jetpack doesn't match on and selects a plugin that sometimes Jetpack is an ok replacement for then we shouldn't be saying that it is already installed.

A good example would be a contact form plugin. Yes, Jetpack has basic contact forms, but there are a lot of options with different features where JP is not at all a replacement: https://wordpress.org/plugins-wp/search/popup+contact+form/ This is searched for by 1-2 people per day.

**Comment by gibrown** [comment]
I should clarify, that "conflicts" (the plugin won't work with Jetpack) are different from overlapping features. 100% agree about showing conflicts on the plugin page and that looks like what the current PR does.

**Comment by drw158** [comment]
To recap, it was determined that showing any sort of banner to communicate overlapping features is too intrusive. For it to be viable, the banner would need to warn about actual conflicts that might break the experience for the user. Closing since this was labeled as a question.
