### ISSUE TITLE
Feedbacks: suggestion to show Contact Form submissions in sidebar for WP.com sites

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11115]
Issue to track an idea — not decided yet, but open for up- or down-voting, suggestions, and comments.

"Feedbacks" — which are submissions from a contact form that are saved as a custom post type (CPT) — should show up in Calypso for WP.com sites. These are currently hidden from the sidebar menu.

They already work for Jetpack sites now (if the Jetpack site has the related module turned on):
![feebacks-jetpack](https://cloud.githubusercontent.com/assets/66797/22524658/594cf22e-e881-11e6-99a3-01b895282494.png)

Requested by @sararosso 

> we need Feedbacks in Calypso and native mobile – our users ultimately should be able to get their “DMs” / direct outreach from visitors of their sites for business or other reasons if they’ve added a contact form or forms to their site.

Noting that these feedbacks go to email as well. As a more general discussion we should consider adding new feedbacks to Notifications also.

**Comment by drw158** [comment]
Some questions before implementation:

- Is this Jetpack feature launched?
- It doesn't appear to actually be functional, meaning it doesn't display any responses to my contact form. It just lists the posts that have a contact form.
- I know technically/historically it has been a CPT but it doesn't make much sense from a user perspective. **Publish** is stuff I create. It doesn't make sense for me to "Add" a response to my own contact form.
- In that case, is it time to rename the heading to "Content"? This way it can be stuff I create or not.
- I can't think of any good reason this is a CPT, other than the way the data is stored. Maybe to preserve compatibility with wp-admin?
- "Feedback" is an obtuse name and hard to grasp. I think it's because it previously contained ratings. Can we rename it to "Responses" or something similar?

I'm not sure the status of this feature in Jetpack. It seems to be incomplete, but I am on Staging. Maybe it's cause I have Jetpack Beta?

**Comment by lancewillett** [comment]
Aside: as a feature expert I suggest also talking to @sararosso more as she has specific workflows and nitpicks.

**Comment by sararosso** [comment]
@drw158  Some thoughts: 

> It doesn't make sense for me to "Add" a response to my own contact form.
+1

> Feedback" is an obtuse name and hard to grasp. I think it's because it previously contained ratings. Can we rename it to "Responses" or something similar?

I would be careful about renaming just because a Jetpack site may be expecting to see Feedback per what they see in wp-admin. Related, do polls and ratings no longer show here? If not, where?

**Comment by drw158** [comment]
Ratings and Polls are only shown in WP Admin. Currently, we tell users to use the Ratings shortcode to add a Rating to a page/post. We don't mention the Ratings settings in WP Admin in the support doc.

https://en.support.wordpress.com/ratings/

Polls in entirely in WP Admin only, aside from just using the poll shortcode in the Calypso editor.

https://en.support.wordpress.com/forms/polls/

I'm not sure about the history of Feedbacks and Jetpack, but currently my Jetpack test site only shows Feedbacks, no Ratings or Polls like in WP Admin on wpcom.

---

My opinion is making contact forms should be fully integrated into Calypso. Receiving the responses via email or connected to a google spreadsheet seems fine to me, but I can see the need to fully integrate those form responses into Calypso, especially since we are targeting SMBs.

I also think that Polldaddy should be treated as a 3rd party service, and all poll creation, survey results, etc. should be done within Polldaddy.

**Comment by drw158** [comment]
#1791 for discussion on creating Polls in Calypso

**Comment by rachelmcr** [comment]
As long as contact forms are filtered for spam, it's also important to provide a way to check that spam filter (because spammed submissions aren't emailed to the user).

I just had a conversation with a user who thought the contact form was broken because he wasn't receiving emails. It turned out that the submissions had gone to spam and he had no way of knowing that or managing the spam.

**Comment by jeherve** [comment]
> They already work for Jetpack sites now (if the Jetpack site has the related module turned on):

fwiw I think this interface can be super confusing for someone new to WordPress and Jetpack. The "Feedback" menu appearing in that sidebar right after connecting Jetpack to WordPress.com doesn't really tell me much. At first, one could expect that this is a place to send feedback to the WordPress.com team.

Related: p8oabR-1p-p2#comment-180

**Comment by lancewillett** [comment]
Also noting that we should allow exporting a CSV of the feedbacks:

<img width="646" alt="screen shot 2017-05-16 at 16 25 02" src="https://cloud.githubusercontent.com/assets/66797/26126600/3e793762-3a54-11e7-86a9-aea6b0ce4a5f.png">

Via @ashleighaxios

**Comment by drw158** [comment]
My latest opinion on this issue: 

Currently we are developing the Comments management UI, and it would be great to use that same UI to manage "feedbacks" (aka contact form responses). We could combine Comments and Feedbacks together into a new sidebar item, called "Discussion".

**Comment by designsimply** [comment]
This came up in p4k3M4-2uX-p2. 

<blockquote>I just realized that I have a form on my site, which I even submitted some content through… and I have no way of viewing the submitted data in Calypso</blockquote>

There was also a suggestion to rename the "Feedbacks" label.

<blockquote>We call these “Feedback” in both wp-admin and Calypso. Why not just “Form Results” or “Forms” or something else that makes a bit more sense and hints that they can be used for all sorts of things? “Feedback” is a pretty specific use of this feature, even if it is the most popular/one we encourage.</blockquote>

/hat tip 🤠 @beaulebens for reporting this. #dogfooding #painpoint
