### ISSUE TITLE
Jetpack Plans: No link to contact support when setup errors out

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#11132]
### Description of the problem
I changed my wp-content/plugins directory permissions to 644 (drw-r--r--). I purchased a Premium plan and tried to go through the setup process to catch the errors and make sure there was a link to contact support. Instead of getting a link to contact support, I just see:

<img width="1433" alt="screen shot on 2017-02-02 at 10-08-26" src="https://cloud.githubusercontent.com/assets/831377/22555137/b0f24b46-e930-11e6-84b7-59eac216da21.png">

**Comment by johnHackworth** [comment]
@rickybanister  @ryelle Should we change that link to "contact support"?

**Comment by ryelle** [comment]
This looks like an actual bug, if both things fail we should be showing a red error banner, not the green one — and in that, there is a contact support button.

If only one item fails, we only show the small notice, which just links off to support docs, and the green success bar shows up because some plugins were successful — that doesn't have a contact button.

**Comment by rickybanister** [comment]
@johnHackworth you and I should go through the new purchase flow that @ebinnion is working on together. This screen is going to be fully replaced.

You can see the new flow and new error handling in #12483

**Comment by rickybanister** [comment]
This was fixed with the new thank you page.
