### ISSUE TITLE
Checkout: Have to type address again for billing after entering for domain

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#11334]
#### Steps to reproduce
1. Start signup flow and purchase a plan including a custom domain
2. Enter domain contact information
3. Continue to checkout
4. Enter billing address information

#### What I expected
After entering my domain contact information and address I expected either for it to be pre-filled in for me on checkout or offer an option to use the same address.

#### What happened instead
Had to manually type the address in both places even though the information was the same.

#### Context / Source
#flowsharing #manual-testing

**Comment by designsimply** [comment]
Closing because I tested purchasing a personal plan during sign up and was not prompted to enter my address more than once. ([3m42s](https://cloudup.com/cdhNEMrdtWJ)) 

Here are my testing steps for reference: 

1. Log out of WordPress.com (if needed)
1. Go to https://wordpress.com/ and click the "Get Started" link at top right
1. Select any type of design.
1. Select any theme.
1. Enter a custom domain and click the Upgrade link.
1. Select a personal plan and click the Upgrade button.
1. Enter an email address + password and click the Create My Account button.
1. Enter domain contact information and click the Continue to Checkout button.
1. Enter credit card information into the Secure Payment form and click the Pay button.

Please re-open if you can think of something in the steps to reproduce that may be causing a difference in my testing compared to yours!

**Comment by sandymcfadden** [comment]
It didn't ask for the full address when you made it to the billing section though you did have to duplicate your name, country and zip code which you had just inputted on domain contact information screen. Wouldn't it be better to auto fill those fields?
