### ISSUE TITLE
Fullpost: Narrow Width: Like and Following too close

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11355]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Reduce browser with to narrowest state 
3. Click on any post that has likes enabled

#### What I expected

At least 20px of blank space in between Comments, Likes, and Following.

#### What happened instead

Likes and Following too close.

<img width="501" alt="screen shot 2017-02-10 at 1 48 27 pm" src="https://cloud.githubusercontent.com/assets/24388/22848411/37ebae2c-ef98-11e6-9853-533fd9d335ff.png">

#### Browser / OS version

Safari and OSX latest

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided.

![screen shot 2017-02-22 at wed feb 22 3 43 32 pm](https://cloud.githubusercontent.com/assets/1119271/23236390/3f2fac2e-f916-11e6-871b-00514d42285b.png)
<sup>Seen at https://wordpress.com/read/feeds/8353950/posts/1349490026 using Firefox 50.0.1 on Mac OS X 10.12.3</sup>

#bug-scrub

**Comment by raoulwegat** [comment]
The problem here is the initial layout for Comments, Likes and Follow is for wide viewports and they're located to the left of the article. Note the order: Follow, Comments, Likes.

![screen shot 2017-03-02 at 4 09 30 pm](https://cloud.githubusercontent.com/assets/2627210/23493865/1d235f88-ff63-11e6-9dda-ee871369240e.png)

For narrow viewports, the elements are moved above the article and are positioned with `position: static;` taking them out of the DOM flow. Their position (and the spacing between them) has been calculated only for "Follow", not "Following" which is wider, and that is what's throwing off the spacing.

Investigating a fix.

**Comment by raoulwegat** [comment]
The fix involves a refactor of the HTML/CSS to use more flexbox and make use of the `order` property.
Prototype: http://codepen.io/raoulwegat/pen/KWzaqG

**Comment by fraying** [comment]
@raoulwegat and I chatted about a duct tape solution: just scooting Comment and Like to the left a bit. It's not the permanent solution, it just makes it better for most people for now.
