### ISSUE TITLE
Followed Stream: Recommended Posts: Spacing off

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11356]
On the main followed stream, in the Recommended Posts block, the spacing around the header is off. There should be 20px of whitespace above and below the header, but there's 25px. 

<img width="877" alt="screen shot 2017-02-10 at 2 00 03 pm" src="https://cloud.githubusercontent.com/assets/24388/22848557/7dde7904-ef99-11e6-9746-63e503672d86.png">

The spacing above and below the post title is correct.

**Comment by designsimply** [comment]
Tested and confirmed. Noticed that `.reader-stream__recommended-posts-list-item` has a height of 30px and `.reader-stream__recommended-posts-list-item` has a top padding of 10px, so it looks to me like the height of the light gray "Recommended Posts" heading might have a little squish room in it by design.

![screen shot 2017-02-22 at wed feb 22 3 56 45 pm](https://cloud.githubusercontent.com/assets/1119271/23236804/e6f96c5a-f917-11e6-8808-1f65910a9cf9.png)
<sup>Seen at https://wordpress.com/ using Firefox 50.0.1 on Mac OS X 10.12.3.</sup>

#bug-scrub

**Comment by fraying** [comment]
That highlighted area ^ should be 20px, as noted in the original issue.
