### ISSUE TITLE
Posts: viewing a private Jetpack post created via Calypso doesn't work if not logged into wp-admin

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#11379]
#### Steps to reproduce
1. Log into Calypso as a Jetpack user (don't log into wp-admin of the Jetpack site)
2. Create a new private post using Calypso 
3. If you click "View" from the sidebar the post shows fine (eg. https://manualtesting.mystagingwebsite.com/2017/02/private-post/?preview=true&frame-nonce=xxxxx
4. If you click "View Post" from the success notice it opens the new post in the new tab as a 404

#### What I expected

To be able to see the private post as I'm logged into Calypso I would expect to be able to see it

#### What happened instead

404 page as I'm not logged into my site - this will be more of an issue for AT sites since the user shouldn't have to worry about what wp-admin is on their site

#### Screenshot / Video

<img width="795" alt="screen shot 2017-02-14 at 10 35 22 am" src="https://cloud.githubusercontent.com/assets/128826/22909697/57adf678-f2a1-11e6-9688-8dcfbf473aad.png">

**Comment by lancewillett** [comment]
I tested this today with an Atomic site to see if the newer post-publishing flow worked better. It does: clicking "View" from the editor action button list (which is at the top right of the editor now instead of in the left sidebar) works as expected.

Note: the "Post updated on __site__" doesn't have a link to view the post anymore.

![screen shot 2017-09-04 at 15 57 37](https://user-images.githubusercontent.com/66797/30039749-1fc184f4-918a-11e7-87e3-41ae9d5ee4b9.png)

![screen shot 2017-09-04 at 16 01 02](https://user-images.githubusercontent.com/66797/30039764-5ada4da0-918a-11e7-906d-84f236c3a685.png)

![screen shot 2017-09-04 at 15 57 52](https://user-images.githubusercontent.com/66797/30039754-2e78b0b2-918a-11e7-9c48-00e3c3793bc8.png)
