### ISSUE TITLE
AT: Eligibility screen is scary

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#11394]
<img width="811" alt="screen shot 2017-02-14 at 12 45 17 pm" src="https://cloud.githubusercontent.com/assets/1464705/22949959/d14a042e-f2b8-11e6-8cae-a6602012b2a0.png">

I find this screen to be fairly scary, and I am an experienced user. I do not know the difference between a "red" error and an "orange" error. Must I resolve this orange error like it asks me to resolve all errors?

Why are features "conflicting" with a plugin that I want to install? I'm just installing a random plugin, why does that mean that I lose a widget? If you know the site is being transferred it makes sense, but the user does not know this. This screen assumes a lot of knowledge.

Why am I being told this stuff as a user? Can you just do it for me instead? The explanations talk about things being unsupported, but it doesn't say exactly what the result of this means.

For example in the screenshot, it says that "Contact Info" is an unsupported widget, but what happens if I proceed? It doesn't say anything like "You will no longer be able to use this widget".

Overall this screen is confusing and scary, it would be good to think through ways we can make it more approachable, limit its exposure to users as much as possible, and rethink how some of this is communicated so that it doesn't assume knowledge about the process happening behind the scenes.

**Comment by folletto** [comment]
I have to agree...

The hope when we designed this was that it was to be shown in a minimal amount of cases... unfortunately it shows up far more often than we'd like to be. Improving the compatibility is probably the most effective things we can do – blocking warnings are blocking warnings, and that's the main problem.

> This screen assumes a lot of knowledge.

It's less "assumes" and more "there's no way around it so what's the minimum amount of information we can provide"? I don't think, even here, the user should know the behind the scenes of the why they get this panel, just they have to fix this to make it work.

Given still we have to deal with this, more often, let's try brainstorm ways to make this less scary.

1. Adjust the copy to be clearer about consequences of proceeding in case of "Warnings"
2. Clear better the distinction between "Errors" and "Warnings"
3. Other?

**Comment by folletto** [comment]
Here's a mock of a potential idea:

![at-eligibility-i4](https://cloud.githubusercontent.com/assets/4389/22975009/ea4051f8-f37c-11e6-972e-6fba716f9c11.png)

**Comment by folletto** [comment]
Here's a i4b variation more positive in tone:

![at-eligibility-i4b](https://cloud.githubusercontent.com/assets/4389/22975508/eeeee19a-f37e-11e6-847b-34d0809aa6b6.png)

**Comment by apeatling** [comment]
@folletto This is already much improved!

**Comment by drw158** [comment]
New mockup looks good!

> For example in the screenshot, it says that "Contact Info" is an unsupported widget, but what happens if I proceed? It doesn't say anything like "You will no longer be able to use this widget".

Good point about the widgets not being clear on what will happen.

The intent was to make it at least a little bit serious so that the user would understand the importance of what is being removed. Users don't expect seemingly unrelated features to be removed for just installing a plugin/theme, so we need them to really stop and look at this.

I like the idea of some being positive "actions", like upgrade and add domain, although some aren't so positive. Some are more like errors.

- Site doesn’t have a business plan
- VIP site
- Site is private
- Site is flagged
- Automated transfer initiated by non-admin user
- Site is not using a custom primary domain
- User is not the owner of primary domain subscription
- Custom domain doesn’t have WordPress.com nameservers

**Comment by drw158** [comment]
Here's an idea:

Not sure if we have thought about this, but what happens if a user buys a domain but not the business plan? Will they waste that purchase, since you get a free domain with business? The following mockups help prevent that; the business plan upgrade and domain upgrade are never shown together.

![screen shot 2017-02-15 at 3 21 56 pm](https://cloud.githubusercontent.com/assets/618551/22995994/c548aeb6-f392-11e6-8164-a89c64d0a29e.png)

⬆️  The Business plan is the biggest barrier to entry, so it should be treated differently. I don't think it makes sense to treat a name server error the same as upgrading to business, which is a big commitment.

![screen shot 2017-02-15 at 3 26 56 pm](https://cloud.githubusercontent.com/assets/618551/22996145/5aff2390-f393-11e6-9861-6333e4af6343.png)

⬆️ The rest of the errors are hopefully pretty rare, but if they come up, they are described as "issues". Error is a bit harsh. If there is a way to resolve it, then there is a Resolve button.

![screen shot 2017-02-15 at 3 28 53 pm](https://cloud.githubusercontent.com/assets/618551/22996221/a4e1582a-f393-11e6-8416-ca5e78c5f283.png)


⬆️ Once they get the business plan, or they already have the business plan this is what they see. If they haven't set up the custom domain yet, it's presented as a positive action rather than an error.

**Comment by folletto** [comment]
We already did some work to have a separate banner on Themes, so that would actually be perfect as it would mean we don't have an exception but the behaviour would be identical* for Plugins and Themes. Big plus for more consistency. 

_* almost because themes will show a disabled upload form if the only missing part is the Business Plan – we could include the domain too._

---

Specifically to the latest mockups:

1. It feels a bit odd to me that "blockers" are shown with blue nice icons and "warnings" are red crosses. In terms of traffic light red is what blocks me, and yellow is what will still allow me to go with awareness of the consequences.
2. I'd remove the icon in the final card (i.e. "You must add a custom...") as it adds imho a bit of visual noise — I'm also not sure I'd say again what's is being already said above. I'd rather simplify the text there so it's standard.

**Comment by drw158** [comment]
> It feels a bit odd to me that "blockers" are shown with blue nice icons and "warnings" are red crosses. In terms of traffic light red is what blocks me, and yellow is what will still allow me to go with awareness of the consequences.

That does make sense, but in this case I think the warnings are actually more consequential and "scary". If I ignore those, I could lose a lot of content.

The errors here are actually not that bad and could be perceived as positive. Some are pretty neutral like, vip site, private site, no domain.

In an effort to make it less daunting, I chose blue, but considered green or gray. I'm not tied to blue, so open to other colors, but I think red might not correctly represent the errors.

**Comment by folletto** [comment]
My perception is less about one single color, and more how errors/warnings interplay together. If they were both blue, or both red, or one green and the other yellow as in the mockups above, I think it would work. It's just the "inversion" that doesn't feel ideal to me. 

However, I totally understand the logic you mention. Hence just a different balance can achieve both I think :)

**Comment by apeatling** [comment]
@drw158 / @roundhill Okay to assume Lannister are going to implement some of the changes talked about here before launch?

**Comment by drw158** [comment]
If you think this is good to start developing, we can see if a developer can work on it in time for launch.

**Comment by apeatling** [comment]
Okay, I think it's good to start iterating on with the above, without making it a blocker. If we can prioritize first the pieces that are low work-high impact that would be ideal.
