### ISSUE TITLE
AT: Domains: Investigate Outgoing Registrar Transfers

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#11447]
We should investigate what happens to an AT site when you transfer its domain out.

It's possible that everything works out smoothly without any interruptions :crossed_fingers: 

If things break, we should fix them and still allow people to transfer domains, we don't want to create a registrar lock in.

**Comment by klimeryk** [comment]
Transfer out itself seems to work (in the end the transfer got rejected, but that was unrelated to any AT changes).
I've simulated an AT site after a transfer out by just transferring the domain (let's call it `example.com`) to a different site on WPCOM.
Calypso for the site continued to work and I was even able to install new plugins. However, it seems that the site got stuck with the custom domain (which no longer was with that site). So, every URL used `example.com`, instead of the only valid domain for that site, which is its `.wordpress.com` subdomain. But that subdomain is also hidden in `Domains`, which leads to this weird view:
<img width="976" alt="screen shot 2017-03-20 at 15 35 40" src="https://cloud.githubusercontent.com/assets/3392497/24104598/e62a4a68-0d82-11e7-89a6-9b12757cb13b.png">

I've tried updating the primary domain for that site to the WPCOM subdomain (directly on my sandbox), but it seems it's not "sticking". I'm not even sure where Calypso is getting the `example.com` domain from since it's not linked to the site anymore 🤔
