### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by miherlosev** [Automattic/wp-calypso#11456]
Calypso is a very complex web application.
I propose to write e2e tests and add them to your CI on CircleCI.
I can do this using [TestCafe](http://github.com/devexpress/testcafe).
What do you think about this?

**Comment by hoverduck** [comment]
@miherlosev - We actually already have a suite of e2e tests for Calypso, they just live in a separate repo - https://github.com/Automattic/wp-e2e-tests

That separation is because, while they began as a completely Calypso-centric project, they've started to expand to cover other WordPress products such as Jetpack and the iOS/Android apps

That repo is open source as well, and we welcome issues and pull requests.  It's currently written in Mocha / WebDriverJS, but if you feel strongly that TestCafe offers something extra that we're missing feel free to put together a PR with a proof of concept and we'll take a look at it.

Thanks for your input!
