### ISSUE TITLE
AT: Themes shows upgrade nudge while site is loading

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#11514]
I have a business site, but if I hard-refresh the page it shows me the business upgrade nudge, presumably while the site is loading some piece of data. After a second or two it is removed. The default should be not to display the upgrade nudge unless we know it is appropriate. In this case I'm not sure what is being checked since you can see in the sidebar that calypso is already aware that I am on a business plan.

![upgrade-nudge](https://cloudup.com/coPK5qB1evL+)

@folletto @seear

**Comment by folletto** [comment]
This is currently done by blending the eligibility endpoint and some custom code for Themes, as Themes eligibility preferred to push the banner with a higher visibility.

However, now the eligibility UI is being redone, and Plugins are going to do the same thing, so it's likely to be fixed naturally once that lands. See issue #11486 :)

**Comment by Copons** [comment]
I've noticed that the upgrade banner is [rendered in `theme-upload`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/themes/theme-upload/index.jsx#L290-L294) rather than in the `EligibilityWarnings` component as I expected.

Considering both themes and plugins will be using the very same `EligibilityWarnings`, it only makes sense to me to move the banner out of the `Upload` component and into `EligibilityWarnings`.

As of now, I'm starting to tackle the styling of the warnings so there's no rush, but sooner or later I'll have to do it. Hopefully I won't screw up the rest of `Upload` though! 🙂

**Comment by folletto** [comment]
Yes, correct. The recent design change in `EligibilityWarnings` aligned it to what Theme Upload was already doing, so we can remove the custom code and have eligibility doing all the work.  :)

**Comment by Copons** [comment]
Closed after #11575 merge.
