### ISSUE TITLE
Domains: formatting is not centered if locale (es - Spanish) is set

### ISSUE THREAD

**Issue by nellofn** [Automattic/wp-calypso#11521]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/me/account
2. Switch UI to: es - Español
3. Save the changes
4. Click on Dominios -> Añadir or go to this URL: https://wordpress.com/domains/add/

#### What I expected
- The phrase _"Qué incluye WordPress.com Premium"_ at the left of _"Mejorar"_ should be centered. 

- Also, I expected "Mejorar" to say "Mejorar Plan" instead. I can try to replace the word later though it could break the formatting as it doesn't seems to fit.

#### What happened instead
The phrase _"Qué incluye WordPress.com Premium"_ at the left of _"Mejorar"_ is not centered.

#### Screenshots

![image](https://cloud.githubusercontent.com/assets/17755234/23193066/5e5959d6-f87d-11e6-956a-148bf4e9ee22.png)

#### Browser / OS version
Chrome Version 56.0.2924.87 (64-bit) / macOS Sierra 10.12.3

#### Context / Source
Test is part of a support rotation.

#i18n, #manual-testing, #support #rotation #spanish_support

**Comment by eduardozulian** [comment]
Same thing happens on https://wordpress.com/start/domains/pt-br, as you can check on the _Gratuito_ part of it (between the blue lines).

Also, the _Included in WordPress.com Premium_ / _Incluído no WordPress.com Premium_ is not aligned (pink line), but this looks like a general issue (happens also in the `en` page) rather than a locale one.

<img width="1005" alt="captura_de_tela_2017-04-07_as_18_28_10" src="https://cloud.githubusercontent.com/assets/1136160/24823113/c5dcbbe6-1bc0-11e7-96a7-bf3edd9fa937.png">

**Comment by akirk** [comment]
@taggon can this be closed?

**Comment by taggon** [comment]
@akirk I think so. :)
<img width="767" alt="screen shot 2017-12-18 at 5 55 57 pm" src="https://user-images.githubusercontent.com/212034/34099553-2a0680ea-e423-11e7-9273-c1b48e7fcf73.png">

**Comment by akirk** [comment]
Great, then let's do so :)
