### ISSUE TITLE
Free Trials: Promote "No credit card required" on /plans and signup plans page

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1155]
One of the anticipated advantages of offering free trials without a credit card upfront is an increase in sign-ups because of the lack of a barrier. We should highlight this fact in a more visible way.

Currently we only mention it in small text below the button:

![image](https://cloud.githubusercontent.com/assets/12596797/11514241/6fe19bda-9845-11e5-96ac-0cc67f2a2093.png)

**Comment by breezyskies** [comment]
A couple concepts for this:

Plans Page | NUX Plans Step
------------ | -------------
<img width="736" alt="screen shot 2015-12-02 at 7 07 25 pm" src="https://cloud.githubusercontent.com/assets/3011211/11563665/f7ff3ce4-9989-11e5-8b44-3435d3bf4858.png"> | <img width="736" alt="screen shot 2015-12-02 at 7 01 19 pm" src="https://cloud.githubusercontent.com/assets/3011211/11563664/f7ec562e-9989-11e5-817a-8ee213e94305.png">

**Comment by mikeshelton1503** [comment]
:+1: These look great @breezyskies 

Later on I think there could some interesting testing done here playing with the emphasis on the "no credit required"

**Comment by breezyskies** [comment]
> Later on I think there could some interesting testing done here playing with the emphasis on the "no credit required"

Another option would be to make the button CTA "Start 14 Day Free Trial" and focus on the "no credit card required" in the header copy.

**Comment by spncrb** [comment]
@breezyskies  I could use some guidance/styling help for the plans text...got a rough start with #1854 , but the CSS isn't quite right yet (mostly the :before :after: border crosses through the text and need to find a good way to have it stop behind the text).

**Comment by breezyskies** [comment]
@spncrb There's a good example of the CSS for this on `/discover` in the reader (not sure if we should componentize this, as I think this is the only other place we use it):

<img width="749" alt="screen shot 2015-12-21 at 4 20 05 pm" src="https://cloud.githubusercontent.com/assets/3011211/11944904/d049617e-a7fe-11e5-8779-23f8b8487942.png">

I believe it uses a bottom border on the parent div instead of `:before` / `:after` (although either would work). Let me know when and I can take a look at the updated PR.
