### ISSUE TITLE
Domain Only: no distinction for current page in the Settings menu

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#11565]
The Settings tab is highlighted in the sidebar either I'm on `/domains/manage/:name` (landing page with CTAs) or on `/domains/manage/:name/edit/:name` (advanced settings). 

In addition to that, right now, the tab takes you to `/domains/manage/:name`, which is also where users land after checkout. I was a bit confused by that, as I kept clicking Settings and nothing changed (nor the state of the menu, nor the content in the main area).

I understand the reasoning of having Settings take you to that landing page. However, it doesn't really look at all like a Settings page to me.

Here are screenshots of the menu highlighted in both pages:

![test1](https://cloud.githubusercontent.com/assets/1248436/23261876/bc8c1f28-f9d8-11e6-896c-7135b4f2d6f7.png)
![test2](https://cloud.githubusercontent.com/assets/1248436/23261875/bc8bf41c-f9d8-11e6-9297-1d55851e8215.png)

**Comment by danhauk** [comment]
I agree with you here. It doesn't make sense to have the same menu item be selected for two different views. Plus, as you mentioned, this default screen doesn't really look like a settings screen.

Here are a couple options for fixing:

1. Add a menu item for this "landing" page to make navigation more clear. Clicking "Settings" would take the user to `/domains/manage/:name/edit/:name` which is a more expected behavior. Clicking "Domain" would take the user back to the `/domains/manage/:name` with the CTAs.

![image](https://cloud.githubusercontent.com/assets/448298/23327625/1f025960-fadd-11e6-8d78-f62169ce2010.png)
(I don't particularly like the label I have in this mockup, but it's one option.)

2. Keep the single "Settings" menu item and link it to `/domains/manage/:name/edit/:name` so it would only show as selected when the user is on this page. Then change the link of the domain name itself (above the menu) to `/domains/manage/:name` (currently links to the site preview). This is probably a bit more of a technical change though, and breaks the convention and expected behavior for existing site owners.

I'm leaning toward option number 1 if we can come up with a good icon/label there.

cc @ranh @breezyskies @scruffian @josemarques

**Comment by ranh** [comment]
I don't think there's anything wrong with having the same navigation item highlighted for different screens. This is already the case in Calypso with the Domains screen and other sections. Though there's usually an explicit section navigation for that.

There was already a discussion somewhere about the use of "Domain" or "Domains" as a menu label here. It may be more consistent with how regular sites work in Calypso.

**Comment by breezyskies** [comment]
> I don't think there's anything wrong with having the same navigation item highlighted for different screens. This is already the case in Calypso with the Domains screen and other sections. Though there's usually an explicit section navigation for that.

Agree with this as far as the highlighting goes -- we already do this consistently within the same "section" within Calypso.

As for whether or not "Settings" is the right label -- I don't think it's perfect, but I also don't have a great alternative. I would suggest we see how usability testing goes with this and go from there.

**Comment by danhauk** [comment]
Closing as a non-issue, though we should revisit the label in the sidebar menu after some usability testing.
