### ISSUE TITLE
Themes: Conflicting Details Shown After Uploading Self-hosted version of a WP.COM theme. 

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/wp-calypso#11628]
Some themes have a self-hosted version and a version that was created for WordPress.com. In Calypso if a theme exists on WordPress.com we show that theme information regardless of what version was uploaded. 

This issue applies to Jetpack and AT sites. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/example.blog
2. Upload the self-hosted version of a theme that's also available on WordPress.com. (ie Elemin by Themify )
3. On the Theme information the correct information is shown "Themify Elemin" 

4. However, the popup and theme link goes to the Automattic/WordPress.com version of the theme. 

#### What I expected
To be either directed to the self-hosted version of the theme or taken to an info page on WordPress.com for the Themify version not the WordPress.com/Automattic version.

#### What happened instead

Was shown the Automattic version of the theme.

#### Screenshot / Video

![screenshot_27-02-2017-21 08 39](https://cloud.githubusercontent.com/assets/150348/23392950/fb14719c-fd33-11e6-840f-3c8dd38cbd06.png)

**WP-Admin:**
![screenshot_27-02-2017-21 10 10](https://cloud.githubusercontent.com/assets/150348/23392918/be8e2272-fd33-11e6-9c6f-e7dc434138ca.png)
![screenshot_27-02-2017-21 09 49](https://cloud.githubusercontent.com/assets/150348/23392921/c14b4422-fd33-11e6-96b4-3257d04847df.png)

**Calypso:**
![screenshot_27-02-2017-21 17 32](https://cloud.githubusercontent.com/assets/150348/23392929/d13cd72e-fd33-11e6-89da-2ec111b455c8.png)
![screenshot_27-02-2017-21 24 25](https://cloud.githubusercontent.com/assets/150348/23392931/d3fed8d6-fd33-11e6-8289-35d938e27191.png)
![screenshot_27-02-2017-21 07 51](https://cloud.githubusercontent.com/assets/150348/23392945/ed62b356-fd33-11e6-8307-d3dbe814faf9.png)

#manual-testing

Related: #11077

**Comment by folletto** [comment]
This is currently by design trying to address the issue of names clashing (the two themes are using the same themeid likely).

However, I'm not sure I understand what problem does it cause, can you clarify that? Thank you!

**Comment by BandonRandon** [comment]
> However, I'm not sure I understand what problem does it cause, can you clarify that? Thank you!

Sure, so the problem here is that I have a self-hosted Jetpack site and I've installed the Self-hosted version of the theme Elemin which I downloaded from Themify.me.  When I visit WP-Admin the correct  theme info is shown and I'm seeing the right settings. 

However, when I visit the theme details in Calypso I'm being asked to buy the version on the theme sold on WordPress.com which clearly won't work on my self-hosted Jetpack site. Instead I should see the info card for the Themify version I uploaded. 

 The self-hosted ( Themify ) and WP.COM (Automattic) versions are different so ideally I wouldn't see the WordPress.com info page when viewing details for the self-hosted version. 

In some further digging this may just be an isolated issue with the Themify themes. I tried to replicate the issue with Elegant Themes, Nexus and was unable to. The correct self-hosted version is shown on the info card. 

![screenshot_02-03-2017-16 16 27](https://cloud.githubusercontent.com/assets/150348/23533015/e0280862-ff63-11e6-9e26-1e4f4dd731f4.png)

![screenshot_02-03-2017-16 18 36](https://cloud.githubusercontent.com/assets/150348/23533021/e836707a-ff63-11e6-8d4a-f7189e78de12.png)

**Comment by folletto** [comment]
Thanks for more details about this! It's very helpful.

> The self-hosted ( Themify ) and WP.COM (Automattic) versions are different so ideally I wouldn't see the WordPress.com info page when viewing details for the self-hosted version.

The reason is that the Themify theme uses the same `Theme ID` (theme folder name) as ours, so we have no way to distinguish one from the other at the activation point.  It's unfortunately a basic issue on how themes are made, and we can't do much about it... `Theme ID`s aren't guaranteed to be unique, yet they are used as "unique" by WordPress to identify each theme in the list.

I'll keep this open to see if someone has ideas on how we could work around the issue.

**Comment by starxedsteph** [comment]
An HE reported a similar issue today in slack.  This user had uploaded a third party theme with the same name as one of our themes (Entrepreneur).
In Calypso, this displays the WP.com theme information and theme setup but in WP-Admin, it displays the correct information linking to the ThemeForest setup information for that Entrepreneur theme.
