### ISSUE TITLE
AT Plugins: Empty Eligibility Screen

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#11687]
It appears you can get the eligibility screen that has no warnings or blockers showing:

<img width="512" alt="screen_shot_2017-03-01_at_10 54 27_am_1024" src="https://cloud.githubusercontent.com/assets/789137/23480544/209c1236-fe7d-11e6-8ddc-9d44ea54d0c2.png">

If there's no warnings/blockers then the AT should just proceed.

**Comment by roundhill** [comment]
I was able to reproduce this by viewing the eligibility screen, then seeing that I needed to set the primary domain to the .blog address. I returned after doing that and saw the empty screen like in the screenshot.

I think we might not be able to avoid this from showing up like this, unless we just proceeded straight away once there were no conflicts/warnings. We could show a message like `No conflicts detected` or something?

**Comment by apeatling** [comment]
> I think we might not be able to avoid this from showing up like this

How come?

**Comment by Copons** [comment]
As asked [here](https://github.com/Automattic/wp-calypso/pull/11575#issuecomment-283482337):
> Could you also see if we can fix #11687 via this PR, if it doesn't already fix it?

The eligibility screen design wouldn't fix this, but it will simply show an empty page, with the same "If you proceed you will no longer be able to use these features." message and the Cancel/Proceed buttons.

If I got it right, this happens when you fix the conflicts, for example, in other tabs, and then come back to the eligibility tab, *reloading it* (since apparently the conflicts aren't updated live in the Redux state).

To avoid problems, we'd like to avoid automatically trigger the AT as soon as a user lands on this page with no conflicts.
This means that the best approach would be to show "No conflicts detected" (a green notice? a normal message with a green checkmark?) and no more scary "you'll lose these features" message.

I'll tentatively add it to #11575, and then iterate or change it in a follow up PR, in order to have everything already in place for the copy review.

See (internal): p1488538826310891-slack-lannister and following

**Comment by Copons** [comment]
Closed after #11575 merge.
