### ISSUE TITLE
AT: introduce stats for eligibility endpoint tracking

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#11717]
The purpose of this enhancement is to collect data and track how often eligibility errors and warnings occur. We'll want to know the percentage of users who run into these issues versus people who don't run into issues at all.

cc @rralian

**Comment by rralian** [comment]
The purpose of the stats is to help us prioritize the work needed to address the blockers and the warnings. Blocking a transfer is really bad. Warning about lost functionality is _pretty_ bad. But we don't know yet how often users will run into this because it depends on the mix of users/sites that choose to transfer and also the age of the site when they transfer (some issues for brand new sites). And we also don't know how bad showing a warning will be... we don't know if that will scare people off completely or if they'll read it and proceed anyway.

**Comment by vindl** [comment]
Closing this issue since it seems to be resolved with https://github.com/Automattic/wp-calypso/pull/12258.
