### ISSUE TITLE
Ability to change editor background color

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#11742]
In a scenario where user changes the text color to white, from the color selector, it can be an odd experience as that text won't visible in the editor, unless highlighted.

**GIF:**

![editor](https://cloud.githubusercontent.com/assets/6505293/23551585/392b5e2a-0039-11e7-9be1-e1345a358c2a.gif)

#### Context / Source
 #user-report 

It was a user suggestion in #219349-hc, and they really did want to pass this on as a feature request. If we do want to pursue this, it can be called something along the lines of 'night mode' perhaps?

**Comment by rachelmcr** [comment]
This sort of issue will most likely be addressed in the context of color schemes, i.e. the color scheme work started in https://github.com/Automattic/wp-calypso/pull/17366. I'm going to close this specific issue since it's unlikely to be addressed separately from those color schemes.

#bug-scrub #pre-gutenburg-bug-purge
