### ISSUE TITLE
Jetpack Plans: no further instructions when a user is not allowed to install plugins

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#11758]
#### Steps to reproduce
1. Starting from a sub-site, part of a multisite network, as an admin with permissions to admin that subsite and no other.
2. Connect Jetpack to WordPress.com and purchase a plan during the connection process.
3. Go back to Jetpack > Settings and click on the "Set up" button in the VaultPress card to install VaultPress.
4. You'll get the following error:

![screen shot 2017-03-03 at 19 09 38](https://cloud.githubusercontent.com/assets/426388/23566604/f51c2f88-0052-11e7-80b4-cc8ffe83f3ae.png)

It seems to be the expected result (see #6480), but Jetpack support won't be able to do much in this situation. The site owner would need to get in touch with the super admin to ask them to install the plugin. Maybe we could add such instructions instead of the "Contact Support" link?

**Comment by jeherve** [comment]
This is still an issue.

**Comment by ockham** [comment]
> as an admin with permissions to admin that subsite and no other

> The site owner would need to get in touch with the super admin to ask them to install the plugin.

AFAICS, most of Calypso currently doesn't work with multisite installs, even when connected as a user with multi-site admin privileges. Specifically, in the case of plugins, instead of seeing an 'Install' button, I'm seeing an 'Site unreachable' warning:

![image](https://user-images.githubusercontent.com/96308/37109502-14d00f32-2232-11e8-8b71-ea1dcd1ec8df.png)

(@jeherve Can you repro?)

(FWIW, other sections look even more broken -- the post editor doesn't get past a pulsating placeholder.)

This means that if we want instructions to tell users to ask their network admins to install the plugin for them, they'd need to resort to `wp-admin`. I can add instructions to that effect, but it seems to barely scratch the surface of the amount of brokenness of multisites in Calypso 🙁

**Comment by jeherve** [comment]
> Specifically, in the case of plugins, instead of seeing an 'Install' button, I'm seeing an 'Site unreachable' warning:

I personally see an "install disabled" text:

<img width="897" alt="screen shot 2018-03-08 at 12 58 45" src="https://user-images.githubusercontent.com/426388/37150032-78266f1a-22d0-11e8-9d8b-e6189a704149.png">

I do get an error message as well though as you can see.

> other sections look even more broken -- the post editor doesn't get past a pulsating placeholder.

The post editor does work for me though.

> This means that if we want instructions to tell users to ask their network admins to install the plugin for them, they'd need to resort to wp-admin

As a super admin I do get the option to install plugins, but only on the main site:

<img width="345" alt="screen shot 2018-03-08 at 13 01 36" src="https://user-images.githubusercontent.com/426388/37150160-de2f4df4-22d0-11e8-9eb7-a9b269f3498a.png">

Going through wp-admin does indeed seem like an easier path here for sure; otherwise we'd have to ask folks to ask their super admins to switch to the main site (assuming it's already connected to wpcom) in Calypso, install the plugin but not activate it, and then switch back to the subsite and then activate it there. That seems like a lot of steps.

**Comment by rachelmcr** [comment]
I retested this issue, and now on the Thank You page after the connection process we display a message about requiring manual setup:

> Your site is part of a multi-site network, but is not the main network site.
> You will have to set up your plan manually.

![screenshot 2018-08-30 16 30 07](https://user-images.githubusercontent.com/8658164/44862220-22821600-ac72-11e8-92c3-2be8d5c33c5f.png)

That includes a link to the [Installing VaultPress and Akismet](https://jetpack.com/support/installing-vaultpress-akismet/) support doc, along with a way to contact support for help.

If you later go to Jetpack > Settings and click on the "Set up" button in the Backups card, though, you will still get to the "Oh no!" message in the original report. It would be great to update this error screen to include the same information as the Thank You page.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
