### ISSUE TITLE
Perfect the design of CombinedCards

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#11913]
This PR connects the new Reader CombinedCards into streams in development mode: https://github.com/Automattic/wp-calypso/pull/11875

The goal of this issue is to collect all of the UI nits that inevitably exist.

This is how it currently appears in streams:
<img width="908" alt="combinedcard" src="https://cloud.githubusercontent.com/assets/4656974/23722588/ea186e20-0413-11e7-9d5a-40a12fa0f817.png">

**Comment by fraying** [comment]
Just a few spacing tweaks:

* More space between image and beginning of text.
* Headline should move up so that the top of the ascenders are on the same line as the top of the image.
* Excerpt line should move down 1px.
* Visit/byline should move down so that the bottom of the baseline is on the same line as the bottom of the image.

Before:
<img width="898" alt="screen shot 2017-03-08 at 1 59 34 pm" src="https://cloud.githubusercontent.com/assets/24388/23726007/8b995082-0407-11e7-8b00-d79e1e23e019.png">

After:
<img width="895" alt="screen shot 2017-03-08 at 1 59 42 pm" src="https://cloud.githubusercontent.com/assets/24388/23726015/92694ae8-0407-11e7-81c0-f008b319457f.png">

These changes make the text easier to read by increasing the space between the lines, without having to change the size of the images.

**Comment by fraying** [comment]
Text settings:

The excerpt text in the Combined Cards is thicker/darker than the excerpt text in normal cards. I looked at the CSS and noticed that the normal card's excerpt is set to "font-weight: 100;" while the Combined Card's excerpt is set to "font-weight: normal;". Could that be the difference?

cc @raoulwegat

**Comment by fraying** [comment]
A couple data bits missing from the card header:

<img width="187" alt="screen shot 2017-03-08 at 2 23 37 pm" src="https://cloud.githubusercontent.com/assets/24388/23726899/d69e940e-040a-11e7-8f06-af64e0236366.png">

1. If the site has a blavatar or site icon, it should be displayed.
2. The time spread of the posts in the CC should be listed after "X posts." As in: "X posts in X minutes" or hours or days. 

This last bit helps explain to the user why these posts have been grouped together.

**Comment by fraying** [comment]
Hey also! Combined Cards seem to break keyboard navigation. :(

cc @samouri

**Comment by fraying** [comment]
All done in #11957. Nice work, @raoulwegat!
