### ISSUE TITLE
NUX: Unable to create new site with mapped domain

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#11937]
I am trying to create a new site with a mapped domain but I end up in a loop:

![screen shot 2017-03-09 at 12 30 18](https://cloud.githubusercontent.com/assets/203408/23748545/5554e91a-04c4-11e7-83e8-fe6116ccd4eb.png)

![screen shot 2017-03-09 at 11 05 25](https://cloud.githubusercontent.com/assets/203408/23745445/78f3bc22-04b8-11e7-8be4-3a3b55f87366.png)

I enter my domain and get to the plans page.

![screen shot 2017-03-09 at 11 05 36](https://cloud.githubusercontent.com/assets/203408/23745460/95a87420-04b8-11e7-8eba-3f4de9983ee0.png)

(This shouldn't offer me free. If I pick Free I get thrown back to Step 1!)

I select "Upgrade" on the Personal plan and it takes me back to Step 3:

![screen shot 2017-03-09 at 11 05 40](https://cloud.githubusercontent.com/assets/203408/23745521/cefe4a24-04b8-11e7-925e-f7aa1b55e85e.png)

This is for a new user with no site (which I was able to create because I got caught in the signup loop in NUX: throws me back to step 3 like above after creating new user data).

Possibly related to #11900.

**Comment by KokkieH** [comment]
I've also been testing this after it was reported in the forums. The browser console showed the following errors when flipping me back to step 3:

<img width="820" alt="create_a_site_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/23751305/74e16bfe-04d9-11e7-96e5-adc002ddeaa2.png">

<img width="775" alt="create_a_site_ _wordpress_com 1" src="https://cloud.githubusercontent.com/assets/11873759/23751319/80c3fe1e-04d9-11e7-9da0-480c60d4729d.png">

I also noticed it only happens if you click the Already own a domain link, either with or without searching for the domain first. If you search for the domain, and then click the Map it link in the "domain unavailable" banner, it works as it's supposed to for me.

**Comment by akirk** [comment]
Well done @tug and @klimeryk. Thanks for fixing quickly!
