### ISSUE TITLE
Switch to grunt or gulp instead of make

### ISSUE THREAD

**Issue by alexdresko** [Automattic/wp-calypso#1193]
See https://github.com/Automattic/wp-calypso/issues/592 for the back story. 

I guess the best place to start is.. Why are you using make instead of gulp/grunt anyway? If gulp/grunt can do the same thing (which is what I'm wanting to find out), how difficult would it be to switch?

**Comment by dmsnell** [comment]
@alexdresko thanks for raising this question. We've had lots of discussion about which build system to use for the Calypso project, as you might imagine. In fact, "which build system is the best" is one of those eternal questions on the Interwebs. In our case, we made a decision to use **Make** and have benefitted from its reliability, from its flexibility, and from the widespread experience available surrounding its proper use.

As other build systems come into view, we have had to evaluate not only their inherent worth, but also the relative gain they would bring over our current and tested Makefile solution. So far, we have not seen any compelling-enough reason to make the leap and abandon Make for any other tool.

In order to change to another build system, we would not only need a working PR to make the appropriate changes, but we would need to verify that the new process preserves the integrity of all of our test suites and translations, that it would allow us to make similar changes in the future as we currently do, and that there would be significant benefits to using it over Make.

If you believe that X or Y or Z would bring a bountiful gain to Calypso, we welcome you to clone the repository and start messing around with a switchover. A PR with the changes, documentation, and enumerated benefits (and potential drawbacks) would garner quite a bit of attention.

Thanks again! I hope this is helpful.

**Comment by alexdresko** [comment]
I'm sorry, but how does "can't do development on windows" not make (pun) you question the decision to use make? 

I'm not even going to bother on the other points... A PR would certainly help... but I'm not a gulp/grunt ninja... maybe this will be my opportunity...

**Comment by dmsnell** [comment]
@alexdresko "can't do development on windows" motivates us to make our project build on Windows. That doesn't intrinsically imply that we should switch from Make. Another way to put it would be to figure out how to make our Makefile run in Windows. There are several different ways of running Make in Windows including a build system included in Visual Studio. Most of these ways require some modification to the Makefile and some environment setup, but those changes wouldn't require breaking the process for Linux or Mac.

The opposite is true as well. Merely switching from Make to [insert your build system flavor of the month here] won't immediately make Calypso build on Windows. In fact, making that transition will almost certainly require more work to get it right than figuring out how to get the Makefile to build in Windows.

It very well could be that none of us are enough of a Gulp ninja or a Grunt ninja or a Gobble ninja or a Broccoli ninja or any other kind of ninja. We're not trying to make a pointed statement about one build tool or another, just trying to answer your question as to why we went with Make.

If you would like to start investigating, it would be good pick a build tool and try to get that to work in the existing environments. This could be accomplished by installing a Linux distribution inside of Virtualbox in your existing Windows environment. Getting it to work without breaking any existing process is the first step, then comes the feature addition - getting it to work in Windows. If we are lucky, then that second addition would be free and automatic.

**Comment by alexdresko** [comment]
Great, humbling reply, @dmsnell. Thank you for taking the time to so eloquently express your team's take on the situation. I understand now and applaud your efforts! Please accept my apology if this thread was an inconvenience.

**Comment by liquidboy** [comment]
of course if you had just used Grunt/Gulp you probably wouldn't need to go through the pain of what we're going through now with trying to make it work on windows ... .. ofcourse the opensource version of msbuild is coming BUT that is too far out for now..
