### ISSUE TITLE
Reader: Inconsistent Blues

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11979]
Looks like we could use some CSS cleanup. We've got three different blues going on here.

![embarassing](https://cloud.githubusercontent.com/assets/24388/23773743/80ce8f86-04d5-11e7-9bff-e26666441704.png)

I suggest we pick the one that's closest to normal WordPress blue (the masterbar color) and make sure that all links are using that color, both in the streams and on the Fullpost page.

**Comment by blowery** [comment]
Wasn't there a whole "we need to move to a new blue because of a11y concerns" thing recently?

**Comment by fraying** [comment]
I've heard whispers of that, but nothing official as far as I know. We should get our own house in order either way.

**Comment by blowery** [comment]
Found it https://github.com/Automattic/wp-calypso/pull/11387/files#diff-bef89c08838e0a1b093c2199b15b20edR14

**Comment by fraying** [comment]
$blue-medium; it is!

**Comment by raoulwegat** [comment]
One problem with color consistency is that text color appears different to SVG colors. Take the Follow button which uses both, but the anti-aliasing on the text, makes the color _appear_ different. Here's a close up view of both retina, and non retina on desktop:

<img width="599" alt="retina" src="https://cloud.githubusercontent.com/assets/2627210/23932636/690db4d2-098d-11e7-80d5-7149ba83de91.png">

![non-retina](https://cloud.githubusercontent.com/assets/2627210/23932646/6f67fc0c-098d-11e7-9dcd-8a10b98ea9d6.png)

So seen with the eye, the text appears a different shade – even though the hex value is the same. Here's non-retina:

![screen shot 2017-03-15 at 2 42 25 pm](https://cloud.githubusercontent.com/assets/2627210/23932686/a88350d6-098d-11e7-9e17-12bc582fa84a.png)

And here's retina which appears closer to the SVG color because the anti-aliasing is more granular.

<img width="96" alt="screen shot 2017-03-15 at 2 44 22 pm" src="https://cloud.githubusercontent.com/assets/2627210/23932723/e7cc8cb2-098d-11e7-896b-3718b1e65495.png">

**Comment by fraying** [comment]
Think that's ok. So long as we're calling the same color for the links in the CSS we're good.
