### ISSUE TITLE
Reader: add stats for new Combined Card

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#12014]
We should add additional stats to the new Combined Card to track its performance.

Questions:
- do we want an additional post open event for combined cards, or just pass an extra param to the existing tracks event `calypso_reader_article_opened`?
- do we want to record a track for the _impression_ of a combined card? Perhaps with the number of sites in the card and the blog ID/feed ID?
- do we want to attribute clicks on the combined card header elements (author link, avatar, etc) to the combined card with a custom event?

<img width="845" alt="screen shot 2017-03-10 at 15 36 30" src="https://cloud.githubusercontent.com/assets/17325/23801247/5df80546-05a7-11e7-8863-24f6f3fe59a0.png">

cc @aaronyan @fraying

**Comment by fraying** [comment]
I'd like to track the normal things normally. As in, clicks on "visit", article opens, author names, site names, datestamps, etc, are all counted using the same tracks as normal cards. Make sense?

The one NEW thing I'd like to count is how often Combined Cards are shown to the user, since we have no real way of knowing that. Does that make sense?

Eventually it might be interesting to track clicks per card type, but if we were to do that, I'd want to instrument _all_ card types (Default, Photo, Gallery, Text, Video, and Combined) so we can see how they all perform in context.

**Comment by bluefuton** [comment]
> clicks on "visit", article opens, author names, site names, datestamps, etc, are all counted using the same tracks as normal cards. Make sense?

Sounds good 👍 

> The one NEW thing I'd like to count is how often Combined Cards are shown to the user, since we have no real way of knowing that.

Cool - I shall add a new Tracks event for that 👍
