### ISSUE TITLE
AT: Refreshing Eligibility screen results in blank screen

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#12086]
Refresh the page when viewing the eligibility screen. You will get a blank screen. It should reload with the latest information. This happened to me with a new AT site and seeing the "SSL" issue when trying to install a plugin.

/cc @roundhill @Copons

**Comment by Copons** [comment]
I'm not exactly sure how to reproduce this, but maybe I'm reading this wrong.

You create a new business site, add a custom domain and immediately try the AT.
The SSL certificate isn't ready yet and you get the eligibility screen with the SSL issue.
At some point the SSL is enabled (silently in background), you refresh the eligibility screen and see "ready to go" page:
<img width="650" alt="screen shot 2017-03-06 at 12 17 05" src="https://cloud.githubusercontent.com/assets/2070010/23609752/768268f6-0267-11e7-82f4-4f22683eab80.png">

Is this what happens to you?
Because as far as I understand this should be the expected behaviour (except the copy errors).

**Comment by apeatling** [comment]
The problem is before it is ready to go, I would refresh the page and get nothing, just a blank screen.
