### ISSUE TITLE
Account Settings: some users can't save settings

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#1217]
To duplicate this, start here:
https://wordpress.com/me/account

Try to select a different primary site.

The settings will say they've saved, but the form still shows the old site.   The old site also shows when refreshing.

**Comment by rachelmcr** [comment]
I can reproduce this issue, and I am unable to change my interface language there.

I am also unable to save changes to my public profile at https://wordpress.com/me.

However, this issue is account-specific. When logged in to a test account, I can save all of the above changes.

@westi — It looks like the caching issues you previously fixed in r124897-wpcom and r124894-wpcom are back. :(

**Comment by lancewillett** [comment]
Quick test with user `lancetest35` — I can save all account settings in `/me/account` as expected.

**Comment by lancewillett** [comment]
Saving settings for `testerlance` user is also working correctly.

**Comment by lancewillett** [comment]
I can't repeat this with any users — anyone else?

**Comment by lancewillett** [comment]
Please re-open if any new reports.

**Comment by gugaalves** [comment]
The same happening with me..
https://github.com/Automattic/wp-calypso/issues/1511

**Comment by jeremeylduvall** [comment]
I currently can't save my language setting either on `jeremeylduvall`. I can save them on `jeremeypt` though. Trying to figure out the common denominator...

**Comment by jeremeylduvall** [comment]
This is now working for me this morning...weird

**Comment by westi** [comment]
I'll look into this

**Comment by westi** [comment]
r128179-wpcom puts back the original "fix" for this issue, let me know if it appears broken for you again in future.
