### ISSUE TITLE
Testing: Test build environment is vastly different than dev/prod.

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#12203]
The fact that our tests build environment is different than our runtime environment is causing compatibility issues that we have to work around fairly frequently. This is especially true if we're using webpack loaders to translate parts of our code as they go into the dev/prod bundles.

Relevant links:
http://zinserjan.github.io/mocha-webpack/
https://github.com/webpack-contrib/mocha-loader
http://randycoulman.com/blog/2016/03/22/testing-with-mocha-and-webpack/
https://github.com/istarkov/babel-plugin-webpack-loaders

Related to #4915 and #6076

**Comment by nylen** [comment]
I'm running into this right now with setting up tests for https://github.com/WordPress/gutenberg.

It seems best to have the mocha tests run through webpack instead of just babel.  Potential solution:  https://www.npmjs.com/package/mocha-webpack

Though undoubtedly there would be some fun rabbit holes to go down if we wanted to use this in Calypso.
