### ISSUE TITLE
Stats / i18n: abbreviated month names aren't localized

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#1224]
Reported in 2444419-t:

> I recently noticed that the abbreviated month names in the stats screens aren't localized again. I've reported something similar in the past (https://en.forums.wordpress.com/topic/i18n-date-in-stats-screen) when the stats screen changed the last time. See my screenshot for further details:

![calypso_stats_month-abbrev](https://cloud.githubusercontent.com/assets/52152/11554405/944e9696-994c-11e5-9e2e-42efe97a7476.png)

FYI @gibrown since you fixed it last time :)

**Comment by timmyc** [comment]
moment.js gives us a utility to properly display these localized short month names via [`monthsShort`](http://momentjs.com/docs/#/i18n/listing-months-weekdays/) but it appears our translation files only have the en-us translation for this array, see [`fr.json`](http://widgets.wp.com/languages/calypso/fr.json) for an example - the `monthsShort` array is:

```
"monthsShort":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
```

Long month names _are_translated, but will not visually work in most areas ( like the month labels here ) so we can't go that route.

@rralian do you happen to know how we can update the `monthsShort` in our translation files?

**Comment by timmyc** [comment]
Plot ( or shall I say _glot_ ) thickens... it appears the base short month translations are just incorrect across the board, because short month names are also invalid in atlas stats:

![mis_estadisticas_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/14121790/b1e89b62-f5ad-11e5-94f0-bf20823ccaec.png)

**Comment by timmyc** [comment]
And incorrect abbreviated months can also be seen in the tooltips on this chart, and on the "Streak" shown in the insights page.

**Comment by rralian** [comment]
I think the back-end has changed around a fair bit since I've touched it last. The logic isn't in calypso itself, but rather the back-end used to generate those files. I believe there is some work in place to make use of moment's locale files within that back-end code to generate the final i18n files. You might have more luck pinging @akirk directly.

**Comment by akirk** [comment]
This is fixed now through an update of our WordPress month shortnames.

**Comment by timmyc** [comment]
@akirk thanks for fixing this!
