### ISSUE TITLE
Customizer > Change > Preview takes you away from Calypso

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#1227]
If you press on the customizer, then change the theme, you are shown a set of other themes (unsure why?). If you press preview on one of these themes you are then taken away from Calypso to the site in question.

This doesn't seem an optimal experience, although I'm sure there are technical reasons.

Unfortunately in the desktop app this has the effect of opening the customizer in a browser window, and leaving Calypso in a loading state.

![wp-desktop-theme-preview](https://cloud.githubusercontent.com/assets/7233112/11544773/b5c16f50-9911-11e5-9c6c-7feb5e3f6518.gif)

Although this is only a problem in the desktop app I am recording it here as its something that can only be fixed in Calypso.

Do we need to show a list of themes once you've just picked one?

Is it possible to keep the second theme selection inside Calypso?

**Comment by mattwiebe** [comment]
Just to reduce the steps to reproduce:

1. Desktop app
2. Load the Customizer
3. Try to preview a theme in Customizer
4. Customizer with theme preview pops open into the system browser

So, what's happening here is that the Customizer is served in an iframe, and when we preview a theme, the Customizer has to refresh itself entirely because its state is dependent on being loaded in a theme's context (boo).

The problem is that the [core code which does this](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/js/customize-controls.js?rev=35251#L2628) calls `window.parent.location = previewUrl`, which bubbles up into Calypso, and the Electron wrapper spots this as an external URL and opens it in the system browser.

I'm guessing core called the parent window for some good reason, but that's the cause of breaking.

Since previewing a theme breaks out of Calypso in either case, my own recommendation would be for us to disable theme previewing/browsing in the Customizer, since it duplicates (poorly) functionality already in Calypso.

**Comment by mattwiebe** [comment]
Theme browsing in the Customizer is disabled r127751-wpcom

This will not only fix the bug, but should see a 2-3x `DOMContentLoaded` speedup. :tada:
