### ISSUE TITLE
TokenField: Add placeholder text

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#12290]
Enhancement request for `TokenField` https://wpcalypso.wordpress.com/devdocs/design/token-fields.

While working on https://github.com/Automattic/wp-calypso/pull/11809, I had the need to add placeholder text to the token field, to act as a more contextual description. I want it to be super clear that you have to comma separate here.

For a visual reference, the tokenfield is the one labeled `Values`:
<img width="963" alt="screen shot 2017-03-17 at 4 19 49 pm" src="https://cloud.githubusercontent.com/assets/5835847/24066201/98beb568-0b2d-11e7-9a6d-51b78f836581.png">

Is this something we could add? Curious to hear @aduth @mtias @MichaelArestad's thoughts.

**Comment by justinshreve** [comment]
I'm happy to handle this if it's something we want.

**Comment by aduth** [comment]
I'd mentioned this being a pain, but after looking closer, there is an [input being rendered](https://github.com/Automattic/wp-calypso/blob/96dc0aa52add9827f139038e07bd90012d18c05a/client/components/token-field/token-input.jsx#L29-L37) by the component, it's just that the the selected tokens are shown outside of it. So to achieve a placeholder effect it might just be a matter of applying the placeholder prop only if there are currently no tokens assigned to the field. The condition is needed because the field is technically "empty" even if there are tokens assigned but if there is no in-progress text.

**Comment by kellychoffman** [comment]
Thanks, @aduth. 

@justinshreve: Sounds good, I would say this would be great to add, but not ASAP. It would be good to have this in place for Variations before moving onto a different section.
