### ISSUE TITLE
Reader: Fix People.com posts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12341]
People is a huge magazine publishing tons of posts (and a VIP) and their posts have problems in Reader. https://wordpress.com/read/blogs/112255790

For example:

https://wordpress.com/read/blogs/112255790/posts/5666379 - empty video embed at top of post
https://wordpress.com/read/blogs/112255790/posts/5666908 - empty video embed, broken image
https://wordpress.com/read/blogs/112255790/posts/5666566 - broken image

Etc. 

Is there an easy fix here?

cc @blowery

**Comment by blowery** [comment]
The feed mapping for people was busted, so I fixed that. Now we're pushing folks to the "feed" variant, which uses content from the RSS feed for VIPs. Here are the equivalent URLs:

https://wordpress.com/read/feeds/2067695/posts/1384882246
https://wordpress.com/read/feeds/2067695/posts/1384871573
https://wordpress.com/read/feeds/2067695/posts/1384860110

Less breakage, but the brightcove videos are entirely missing instead of broken.

**Comment by fraying** [comment]
Thanks, @blowery!
