### ISSUE TITLE
Question: Woocommerce plugin on self hosted site causing issue in Calypso

### ISSUE THREAD

**Issue by PrachiThengane** [Automattic/wp-calypso#1262]
I have installed Calypso locally and added self hosted Jetpack enabled domain in it.
Now, my aim is to get the woocommerce options in calypso navigation bar but after enabling woocommerce plugin on my wordpress site I am getting error as "Error fetching plugins on wordpress".

Could anyone help me for this?

**Comment by jeherve** [comment]
> my aim is to get the woocommerce options in calypso navigation bar

I'm afraid that won't be possible, as Calypso won't display options from other plugins yet, since these options aren't available in the REST API right now. You can follow #587 and #588 to follow our progress on porting custom data such as Custom Post Types and Custom Post Fields to Calypso.

> after enabling woocommerce plugin on my wordpress site I am getting error as "Error fetching plugins on wordpress".

That seems to be an issue with your site's connection to WordPress.com. Could you use the contact form below to send us more information about your site, so we can take a look and help you get rid of that message?
http://jetpack.me/contact-support/

Thanks!
