### ISSUE TITLE
Domains: NUX: Options for how to use domain are not visible on mobile without scrolling

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#12625]
On the site or domain NUX step, the "Just buy a domain" option is not visible without scrolling.

![image](https://cloud.githubusercontent.com/assets/12596797/24458113/f9ef7926-1465-11e7-8502-734830d40ac8.png)

In a recent usability test, users didn't always see the "Just buy a domain" option because it wasn't immediately visible.

**Comment by designsimply** [comment]
#user-testing

**Comment by danhauk** [comment]
Note that this is also an issue in regular NUX too, so we may want to look at a more holistic solution.

<img width="318" alt="screen shot 2017-04-27 at 11 43 52" src="https://cloud.githubusercontent.com/assets/448298/25491775/f05cc7d4-2b3e-11e7-9c46-93d0b33161fb.png">

With regular NUX it's not as much of an issue because the second illustration is more apparent, guiding users to scroll.

**Comment by danhauk** [comment]
Fixed in #13405 

<img src="https://cloud.githubusercontent.com/assets/275961/25530658/f6685982-2c1e-11e7-9045-1346cc77773c.png"/>
