### ISSUE TITLE
Not clear your domain is included with a plan in the /domains flow

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#12635]
In the /domains flow, we could make it clearer that the domain you just chose is included with the plan. This is a selling point that we're not capitalizing on.

From @sararosso (referring to the plans page):
>maybe we should bold / replace this text with “Your custom domain name is included!” or maybe even the name of the domain?

@danhauk worked on a design to highlight this in the results:

![image](https://cloud.githubusercontent.com/assets/12596797/24464596/571800d4-1478-11e7-9055-ed111c294f07.png)

**Comment by sararosso** [comment]
Hm. So the $30 and the "Get Domain" info are pretty far apart - I'm not really sure what the $30 buys vs. the underneath text which is offering a few more things (including repeating the domain button). 

How can we better visually associate the two price points and their buttons/CTAs - $30 / domain only and 'starting at $38..' and plan/website? 

Some thoughts - 
- Could we move that Get Domain (I think with "Only" might be too crowded, but could emphasize) closer to the price there? 

Terrible terrible mock here: 
![571800d4-1478-11e7-9055-ed111c294f07](https://cloud.githubusercontent.com/assets/4126822/24475444/b0a4a6fa-1484-11e7-87f2-918d5efed0b6.png)

- We might also consider (if there's room) "Website plans start..." in that copy to reinforce the Website + Plan pricing.

**Comment by danhauk** [comment]
@sararosso I agree with your feedback about better connecting the $30 price with the "Get domain" button. This will need some iterating and polishing. It was more of a quick concept to explain the idea and we didn't spend much time on design or copy.

**Comment by danhauk** [comment]
After some iteration and discussion/feedback within the team, we decided providing this upsell information makes more sense further in the flow. Rather than add complexity to the recommended search result, we can communicate more information on the "choose a site or just domain" step after selecting the domain.

Moving the upsell to this step keeps the results clean, removes potential confusion with the `Recommended` result having this info and not the other results, and provides more guidance to help people make a choice that works for them.

Proposed solution:

![image](https://cloud.githubusercontent.com/assets/448298/25097329/1f47a89a-2372-11e7-8a5f-1742eb343b55.png)

cc @ranh @sararosso for copy review.

**Comment by sararosso** [comment]
> Show 'coming soon' page

I think updating the button to "Just reserve a domain" and underneath: 
"A 'coming soon' page will be displayed. Add a full..."

makes it more equitable with the other choices.

**Comment by ranh** [comment]
> we could make it clearer that the domain you just chose is included with the plan. This is a selling point that we're not capitalizing on.

I'm not sure what these changes are meant to fix. We do already mention this on the plans screen and on checkout. Do we know that it's not clear enough? This may be premature optimization. 

@danhauk mentioned that one of the original concerns was the confusion around the "Custom Domain Name" item in the plan comparison. 

This is what it says now:

<img width="350" alt="ranimac3 screenshot 2017-04-19 at 17 13 46" src="https://cloud.githubusercontent.com/assets/426518/25184606/9a6c8bf0-2523-11e7-8a49-2749ccc52324.png">

> Custom Domain Name
> > Get a free custom domain name (example.com) with this plan to use for your website.

Let's change that to:

<img width="350" alt="ranimac3 screenshot 2017-04-19 at 17 17 17" src="https://cloud.githubusercontent.com/assets/426518/25184784/161f620e-2524-11e7-9001-c8e36b4ed0b5.png">

> Domain: example.com
> > Your domain (example.com) is included with this plan.

---

Re the changes in the add-site flow, the new layout looks good. I'm not sure though if these options are comparable based on price, so clearly stating a specific price next to each option may not be helpful. 

Also, actual pricing is a bit more complicated. For example, price for adding a site may vary if users do it later, so quoting the price out of context here can create false expectations. And adding to an existing site may be free if there's an available domain credit from a plan. 

What about:

* New site
    * Choose a theme, customize, and launch your site. Free domain included with all plans.
* Existing WordPress.com site
    * Use with a site you already started. Free domain included with all plans.
* "Coming Soon"
    * Show a "coming soon" notice on your domain. Add a site later. 
 
Changes:

* We should be clear that with this flow, domains can only be used with existing _WordPress.com_ sites. I changed the labels to be able to accommodate "WordPress.com" inside the button label for the second option. I'll start a separate issue since I think we should do more here.
* Shorter descriptions, and changed pricing information to be less specific (but still suggest the added cost for the plan.)
* Removed email reference from "just domain", to focus on sites. We don't mention email for any of the other options, so adding it just for this option may suggests it's the only option that offers email.

**Comment by danhauk** [comment]
@ranh Those changes look good. Thanks for putting the thought into them. What are your thoughts on @sararosso's suggestion above?

> I think updating the button to "Just reserve a domain" and underneath: "A 'coming soon' page will be displayed. Add a full..."

I like that phrasing and think it's a good suggestion. Maybe the button wording could be tweaked to "Just the domain" or "Domain only"?

**Comment by ranh** [comment]
@danhauk @sararosso In a [previous issue](https://github.com/Automattic/wp-calypso/issues/12196#issuecomment-289515842) we mentioned that the label "just buy a domain" can be confusing, because users will later find their domain under "My Sites". 

It's hard to say if that's a valid concern or not. And otherwise "just a domain" is indeed a pretty good description of that option. I think either label (just domain / coming soon) will work fine.

We probably shouldn't dwell too much on the finer details here, since this whole screen (and this whole flow) are still experimental and unproven.

**Comment by sararosso** [comment]
> And otherwise "just a domain" is indeed a pretty good description of that option. I think either label (just domain / coming soon) will work fine.

sure, just thinking 'just a domain' reinforces they're not getting anything they can customize, while offering a 'coming soon' page might imply they can customize it somehow.

**Comment by danhauk** [comment]
Ok, so just to package all of the designs into one comment to make it more clear what should be changed, here we go.

Update the screen after selecting the domain to better communicate the differences between these selections (we'll only show the "new site" and "just the domain" options until we have the [functionality for existing sites](https://github.com/Automattic/wp-calypso/issues/12196)).

![how to use domain](https://cloud.githubusercontent.com/assets/448298/25356423/1c0ae2be-2908-11e7-8565-ee702b09dc27.png)

On the plan selection screen, let's update the line items for each plan to make it more clear the domain you're purchasing is included in the plan price:

![](https://cloud.githubusercontent.com/assets/426518/25184784/161f620e-2524-11e7-9001-c8e36b4ed0b5.png)

Moving this over to development.

**Comment by scruffian** [comment]
I created #13405 to address these changes
