### ISSUE TITLE
Signup: confirmation link redirects to https version of your Jetpack site

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#12716]
#### Steps to reproduce
1. Start from a self-hosted WP site using HTTP, not HTTPS.
2. Activate the Jetpack plugin.
3. Follow the steps and get to the Jetpack signup flow for WordPress.com.
4. Create your WordPress.com account, finish connecting Jetpack on your site.
5. In my meantime, you've received an email asking you to "Activate" your WordPress.com account.
![screen shot 2017-04-03 at 11 49 56](https://cloud.githubusercontent.com/assets/426388/24604077/ad2b56c6-1863-11e7-99f0-edbc85d06124.png)
6. When clicking on that link, your account gets verified and you then get redirected to your Jetpack site.

The problem is, the Jetpack site URL is incorrect: it always uses HTTPS, even though my site does not use HTTPS.

**Comment by jeherve** [comment]
This is still an issue.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
