### ISSUE TITLE
VaultPress auto-install triggered error (after successful install)

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#12790]
I have a test site where I deleted VaultPress at some point, so the UI was telling me that I needed to SET UP (blue button) again.

I clicked through from wp-admin, and I landed on the Calypso page where it auto-installs/configured VaultPress for me. It seemed to work, and then this error also appeared (after I left the page open for a few minutes):

![screen shot 2017-04-04 at 4 35 43 pm](https://cloud.githubusercontent.com/assets/108942/24682033/f3ee7dda-1954-11e7-8570-70f9958513c7.png)

Before the auto-install, the folder definitely did not exist. When I get back to my Jetpack site, VaultPress appears to be installed and configured correctly.

It seems pretty easy to reproduce:
- get a site with a professional plan (maybe others, but that's what i have)
- deactivate and delete vaultpress from your plugins menu
- click the SET UP button from the jetpack dashboard
- watch it install things successfully, then it actually cycles through 3 different errors, and stops on the one above
- go back to your site and things seem to be configured correctly

**Comment by johnHackworth** [comment]
I think @ryelle  is more suited to this one! :)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
