### ISSUE TITLE
Settings: Traffic: update ordering of cards

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12845]
**Before:**
Stats
Related Posts
Google Analytics
SEO
Site Verification (with non-togglable sitemaps mention stuffed at the bottom)

**After:**
Stats
**Ads**
Related Posts
SEO
Google Analytics
**Sitemaps**
Site Verification

**Comment by tyxla** [comment]
I've started working on this one, but it's best if we separate concerns and address it with several PRs.

* Introducing a SItemaps card - #12898

**Comment by rickybanister** [comment]
Let's also confirm that this is the same order in Jetpack.

**Comment by tyxla** [comment]
I've opened #16244 to split away the Site Verification Services card from the SEO Settings. After we land it, we'll be able to replicate the order of these cards that's in Jetpack.

**Comment by tyxla** [comment]
#16326 is the final one, which updates the order of the cards in the Traffic section.

@rickybanister since there are several cards that are not in wp-admin, I could use your feedback about whether we're good with the suggested order (I've described the previous and the suggested order in the PR). Thanks!
