### ISSUE TITLE
Signup: Alignment of text on map domain step

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#12927]
There's a small alignment issue on the map domain step particularly for new users signing up for accounts. The text "Included in WordPress.com Premium" is slightly higher than the map domain instructions. They should be even.

#### Steps to reproduce
1. Try to start a new WordPress.com account through an incognito window.
2. On Step 3 of 5, click "Already own a domain"
3. On the next step (https://wordpress.com/start/domains/mapping/), you'll see the alignment issue.

<img width="764" alt="screen shot 2017-04-08 at 11 17 03" src="https://cloud.githubusercontent.com/assets/7240478/24830490/f28dfe84-1c4c-11e7-9701-f7cb3159e674.png">

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the steps provided.

![screen shot 2017-04-10 at mon apr 10 3 29 49 pm](https://cloud.githubusercontent.com/assets/1119271/24883547/9c7d55f0-1e02-11e7-94e7-7a4bffff51ad.png)
<sup>Seen at https://wordpress.com/start/domains/mapping using Firefox 52.0.2 on Mac OS X 10.12.4.</sup>

**Comment by VitaC123** [comment]
Hi all,

New to contributing in general, so thought I'd take a stab at this alignment fix. BTW, I retitled my branch to include the issue #, so please disregard `166c4db`.

Removing `margin-top: -5px` seems to have fixed the alignment issue. See screenshot below. If this looks good, should I submit a PR?

<img width="1440" alt="alignment of text on map domain step 4-16-2017" src="https://cloud.githubusercontent.com/assets/17498763/25073422/567f209a-229b-11e7-9d86-673043090788.png">
From http://calypso.localhost:3000/start/domains/mapping using Firefox 52.0.2 on Mac OS X 10.12.4.
---

One quick sidenote: Using the steps provided, I noticed Firefox displays this page as **Step 4 of 6**. (Instead of "3 of 5" as originally specified.)

**Comment by jeremeylduvall** [comment]
@VitaC123 thanks so much for working on this! It looks like this does fix the issue. I also checked on existing accounts with `https://wordpress.com/domains/add/mapping/` since it uses the same selector. I would encourage you to [submit a PR](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md). Let us know if you have any trouble.

**Comment by VitaC123** [comment]
@jeremeylduvall sounds good, and thanks! Just submitted the PR.

**Comment by klimeryk** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/13147 by @VitaC123 🙇
