### ISSUE TITLE
Jetpack: Don't ask secondary user to pick a plan

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#12924]
#### Steps to reproduce
Currently when you are invited to Jetpack if the site doesn't have a plan already and you login via SSO. 
You end up on the plans page. 

#### What I expected
To not but asked to pick a plan.

#### What happened instead
I was redirected to the plans page after login in via SSO

#### Browser / OS version
Latest Chrome / Mac

#### Context / Source
 #dogfooding

cc: @beaulebens

**Comment by johnHackworth** [comment]
Closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/11179

**Comment by beaulebens** [comment]
Actually I'm going to reopen this, because it's a bit different from the linked issue. This one is specifically about seeing plans during connection, as a secondary user. The other one is about where you end up at the end of the flow. Both are valid, slightly different, and should probably be fixed.

**Comment by kellychoffman** [comment]
I just had this happen to me when @allendav added me to a site he made. It felt really strange to go through the multi step process and pick a plan instead of just "Approving" the connection.

**Comment by gravityrail** [comment]
This is definitely still happening to me.

https://github.com/Automattic/jetpack/issues/7687
