### ISSUE TITLE
Manage Purchases: show a notice for disconnected sites with orphaned upgrades

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12923]
With Jetpack's connection to WordPress.com it is possible for a user to purchase an upgrade, then disconnect the site from WordPress.com. This makes that purchase somewhat 'orphaned'. @ryelle has made it possible to display the disconnected site in the purchases list with the orphan purchase, but we can do the user one better.

Let's show a notice beneath the site/purchase block like this:

![image](https://cloud.githubusercontent.com/assets/437258/24822310/20b9547e-1bc2-11e7-8cd9-a11f236778e5.png)

The reconnect link could jump them into step 2 of the Jetpack Connect flow (see if they have Jetpack installed or not and give them the appropriate instructions). 

cc @richardmuscat @beaulebens @johnHackworth 

Related to: #12746

**Comment by beaulebens** [comment]
Love it.

If they click through to the details of that upgrade, they can still cancel that upgrade from here as well, right? In the case that they've nuked that site or something, and forgot to cancel their plan/upgrade?

**Comment by rickybanister** [comment]
Yup, this will behave like any other upgrade. They'll even be able to change to a different credit card if they so choose.

**Comment by ryelle** [comment]
@johnHackworth or @roccotripaldi, is there a URL or helper I can use for the Reconnect button here that would drop into the second step of connecting? I tried looking through the connect flow but I can't see anything (aside from the authorize link generated in Jetpack, but I need something from Calypso)

**Comment by roccotripaldi** [comment]
@ryelle - try this method: https://github.com/Automattic/wp-calypso/blob/master/client/state/jetpack-connect/actions.js#L189

Before dropping into step 2 of auth, we need to do stuff on the remote site.

goToRemoteAuth will send them there. if they are already logged in to their site, they will be seamlessly be redirected to Jetpack connect step 2.  If not, they'll login, and then be sent back.

**Comment by ryelle** [comment]
It seems we don't have the full url, just the display domain (`example.com/wp`, rather than `https://example.com/wp`). `goToRemoteAuth` ends up redirecting to `http://calypso.localhost:3000/me/jetpack.redradar.net/wp-admin/admin.php…` instead of the site itself. I don't see the full URL anywhere in the data I have access to in this component (`PurchasesSite`), and it's a disconnected site, so we can't fetch more data.

So this reconnect button isn't working out. But —

- We could attempt sending the user to `https://[domain]` (or `http`), but that's certainly going to fail for some users
- We could change this NoticeAction to be "Contact Support"
- Maybe I'm missing a way of getting the full domain? I have a siteId of a site we know exists, this user just doesn't have access anymore.

**Comment by rickybanister** [comment]
I'll wait to see if @roccotripaldi can shed more light here, but it'd be great to hopefully make an educated guess about their url instead of just sending them to get support (if there's a good chance that reconnecting could _just_ work).

**Comment by beaulebens** [comment]
Could we do a quick "pre-flight" request? Make an out of band request to `https://{domain-etc}` and if it doesn't work, then use the `http://` URL.

**Comment by beaulebens** [comment]
Or actually, shouldn't the URL still be in the shadow site under site_url or home_url? The site is currently disconnected, but it was previously connected, so we should have synced it at some point.

**Comment by ryelle** [comment]
pre-flight was what I was leaning towards. We don't actually have any site info, or any way to request that info (that I know of) because the logged in user no longer has access to it. Is there a way to query (public?) info on a given site?

**Comment by rickybanister** [comment]
@roccotripaldi any ideas about the above question? @johnHackworth?

**Comment by roccotripaldi** [comment]
hmm. could we open up a new purchases endpoint? something like `getSyncedURLbyReceiptID` and we could ensure the current user has access to receipt before returning the synced value.

**Comment by roccotripaldi** [comment]
and if no synced value is found, the endpoint could handle the HTTP vs HTTPS logic, so we could pass receipt id and non-protocol URL.

**Comment by johnHackworth** [comment]
A (new?) API endpoint where you could send an URL and get some info if there's a shadow site for it would be pretty helpful. Not only here, but also in the connection process ... that will help us to know if it's a reconnection or a totally new site, so we could handle them differently (something @rickybanister have been proposing since forever)

**Comment by rickybanister** [comment]
Yes please! Being able to say 'welcome back!' would be very nice. We could reintroduce them to the plan they purchased, or even show them 'new' features since they last visited. 

Currently it feels somewhat strange to reconnect over and over.

**Comment by ryelle** [comment]
Well, looks like now that we can just pass a url to the connect screen, this is much easier 😁 The API endpoint is still a good idea, but not necessary for this issue anymore. I have to clean up my branch a little, but I'll have a PR for this this afternoon.

**Comment by rickybanister** [comment]
Awesome!
