### ISSUE TITLE
Editor: modifiers are applied to whole paragraph instead of selection

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#12945]
#### Steps to reproduce
* Go to the post editor.
* Write this in the `HTML` view:
```
Hi,
This is another line.
Another.

2 line breaks before this one.
```
* Switch to the `Visual` tab.
* Select the text `This is another line.`
* Try to apply the `Heading 2` style to it.

#### What I expected
Only the selected line should have the style applied.

#### What happened instead
The whole "block" had the style applied.

#### Browser / OS version
Chrome, Windows 10.

#### Screenshot / Video
![editor](https://cloud.githubusercontent.com/assets/1715800/24858033/5b970042-1de2-11e7-8740-f3e639cedf9e.png)

#### Notes
This is specially important because in the Android app (with the Aztec editor), when pressing the `Enter` key, only 1 line break is inserted, instead of the 2 that are inserted in the desktop UI. I'm not sure if this is a bug on the Android editor or in the desktop editor.

I wrote a blog post in my phone, and after that I opened it in the desktop webapp to style it. #dogfooding

**Comment by designsimply** [comment]
Thank you for reporting this! 

<blockquote>This is specially important because in the Android app (with the Aztec editor), when pressing the Enter key, only 1 line break is inserted, instead of the 2 that are inserted in the desktop UI. I'm not sure if this is a bug on the Android editor or in the desktop editor.</blockquote>

The issue with line breaks behaving differently is an Aztec editor issue and is being tracked at https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/258

**Comment by rachelmcr** [comment]
Closing as the Aztec issue is resolved and the block formatting behavior will be superseded by how Gutenberg handles these blocks.

#bug-scrub #pre-gutenburg-bug-purge
