### ISSUE TITLE
Pages: show comments in pages view

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#13071]
It is possible to see comments against /posts in Calypso:

<img width="1068" alt="post comments" src="https://cloud.githubusercontent.com/assets/128826/24985338/e5005b5c-2036-11e7-914e-71d8b2f36041.png">

But there doesn't appear to be any such thing for pages:

<img width="1067" alt="pages" src="https://cloud.githubusercontent.com/assets/128826/24985353/ef256438-2036-11e7-9675-425f870f6162.png">

Since pages can contain comments as well, could we add comments to the /pages view?

**Comment by rodrigoi** [comment]
We can add that, but given the UI differences between pages and posts, I think we can include them when we get the new comments section sorted out.

cc: @drw158

**Comment by designsimply** [comment]
Tested and confirmed that you cannot reach comments for pages via https://wordpress.com/pages

<img width="1280" alt="screen shot 2017-06-23 at fri jun 23 12 53 24 pm" src="https://user-images.githubusercontent.com/1119271/27496449-305af422-5813-11e7-9251-ed8bcb40f2d8.png">
<sup>Seen at https://wordpress.com/pages/design5279.wordpress.com using Firefox 54.0 on Mac OS X 10.12.5.</sup>

**Comment by designsimply** [comment]
@drw158 @rodrigoi what if we just linked out to /comments from /pages instead of building in a UI within /pages similar to /posts?

<img width="1280" alt="screen shot 2017-06-23 at fri jun 23 12 59 00 pm" src="https://user-images.githubusercontent.com/1119271/27496739-80c457b8-5814-11e7-8281-601f317748eb.png">
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com using Firefox 54.0 on Mac OS X 10.12.5.</sup>

**Comment by lancewillett** [comment]
Ran into this today during a team meetup: @mcsf was going to force us to use Calypso Reader to comment on ordering our lunch. However, we realized:

1. Can't view pages in Reader.
2. Can't comment on pages via Calypso.

**Comment by lancewillett** [comment]
Hi @apeatling — is this on the roadmap for Comments (Triton/Lannister)?
