### ISSUE TITLE
Themes: Improve error message when theme is not a single zip file. 

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#13135]
When uploading a theme from a third party where the downloaded `zip` file has  more files than just the main theme files the upload fails with:
> Problem uploading theme: no_theme_installed 

This looks to be what happens when `unknownCause` is triggered.  ( https://github.com/Automattic/wp-calypso/blob/c68aaca80491865b57ed9edfba782677d4ab1f8b/client/my-sites/themes/theme-upload/index.jsx#L147 )

This issue is to either A) improve the messaging or B) search through the zip file and find the second zip. 

#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/themes/upload/example.com
2. Upload a zip that contains more than just a single theme files. 
3. Check out the error message that says Problem uploading theme 

#### What I expected
To be given an error that tells me a bit more about what failed and what to check for. This could even be in a link to support in the theme upload area itself. The error message itself could also have the underscore of  `no_theme_installed` removed. 

#### What happened instead
I was given a confusing error message stating a problem while uploading the theme. 

One improvement would be to check for this case and change the message to:
> Problem uploading theme: Check zip file.  

#### Screenshot / Video
![screenshot_28-03-2017-19 08 27](https://cloud.githubusercontent.com/assets/150348/25059181/90774c70-2136-11e7-898f-b763a9b0e10d.png)
![screenshot_14-04-2017-15 01 50](https://cloud.githubusercontent.com/assets/150348/25059170/6d16e376-2136-11e7-8e07-3c07f4141eec.png)

Related #13133 #13128

**Comment by lamosty** [comment]
Regarding Automated Transfer: this should not be an issue for the initial transfer because if a "theme" transfer fails on the server side, the main reason for the failure is invalid theme (either because it's a zip which is containing another zip of the actual theme or any other malformed theme zip) and we now show "Upload problem: Theme may not be valid. Check that your zip file contains only the theme you are trying to upload" https://github.com/Automattic/wp-calypso/blob/ae2a3cc295690cc8e2d99e7751e3e9777481cce8/client/my-sites/themes/theme-upload/index.jsx#L143-L143. I think that message is good enough for AT.

What do you think?
