### ISSUE TITLE
Settings > Writing: Infinite Scroll settings for .com sites

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#13237]
This is pretty straight-forward, we need to make sure .com sites are getting all the appropriate Jetpack settings, including any of our theme enhancement stuff on the /writing tab. 

See #12174 for the design (for Jetpack sites)

This should replace the bulk of what's discussed in #3900 

cc @lancewillett

**Comment by tyxla** [comment]
Looking at this one in-depth, I wouldn't say this one's really straightforward.

Here's what we have for .com sites in the wp-admin right now:
![](https://cldup.com/O2AjmmcnS8.png)
![](https://cldup.com/tRViS42T9p.png)

Here's what we have in Jetpack's Settings (in Jetpack and Calypso):
![](https://cldup.com/BQkVLomGCQ.png)

From both a behavioral and UI point of view, these are very different. I think we might want to support more cases like the "footer widget" case in Calypso and Jetpack too, and that needs to happen before we adapt the infinite scroll settings in Calypso to work for .com sites.

And to add to that, currently the Infinite Scroll approach is a little hacky, because it converts the 3 UI settings we can see to the 2 settings that are in the backend (the module itself, and its single setting) - that would also require a significant refactor in both Jetpack and Calypso.

With the amount of work this should include in mind, I believe we should leave that one for v2.

**Comment by lancewillett** [comment]
Moved to wp-admin parity milestone because it's urgent for closing gaps for WP.com sites.

However — I think this is a good time for a broader discussion around Infinite Scroll settings. We intended at launch of the feature to choose smart defaults, and not allow customizing or turning it off. I think that still makes sense for WP.com sites — but maybe not for Jetpack sites.

**Comment by SiobhyB** [comment]
This came up in 540556-hc.

In that chat, the user had set 9 blog posts to display on their home page via https://wordpress.com/settings/writing. They were confused about why that setting wasn't being respected. The reason was that Infinite Scroll was enabled on their site and that overrode their manual setting.

I had to guide the user to /wp-admin in order to disable Infinite Scroll. 

It's awesome that the option to set the number of blog posts that display on the home/posts page is now in Calypso. However, Infinite Scroll will always override that setting and it's not intuitive for users to know that they need to disable that in /wp-admin first. I think it's important to add Infinite Scroll alongside the "display posts per page" toggle.

**Comment by rickybanister** [comment]
@tyxla @lancewillett 

I think the problems to solve are shared with Jetpack and .com sites.

Aren't they outlined in this issue: #13637

I thought the trouble was not having the api endpoints from Jetpack to adequately detect the widget area usage (whereas that's easier with a .com site?)

Regardless, the solution in the issue I linked should be an improvement over the current wp-admin implementation and work for jetpack if we can tell what widget areas they're using.

**Comment by tyxla** [comment]
Yup, that was the case, but we're already syncing the theme features data from Jetpack sites, so for Calypso we can build a new theme features endpoint and use it to create a better Infinite Scroll for .com and Jetpack sites. 

For Jetpack itself it shouldn't be an issue - they can always add the theme features data to the initial state, and it's easily accessible.

Also, another problem was that Infinite Scroll in Jetpack consists of one module toggle and one module setting in the backend, while in the UI it's one field with 3 values. To achieve this UI while keeping it backwards compatible we had to hack a little in both Jetpack and Calypso. This will not be necessary for .com sites.

Something else to mention: historically, it was a problem to update a module setting if the module was disabled in Jetpack. Not sure if that's still a limitation, but it wasn't a limitation for .com, which was another reason we treated the Jetpack implementation as a separate one.

The easiest and quickest solution in the short term is probably to build a .com version of Infinite Scroll. In the long term, we might want to build universal UI that would work for any types of sites.

**Comment by lancewillett** [comment]
> The easiest and quickest solution in the short term is probably to build a .com version of Infinite Scroll.

+1 to this; keeps it small and brings wp-admin parity right away.

**Comment by lancewillett** [comment]
Hi @tyxla -- checking in on this one, is it still on your radar to fix?

**Comment by tyxla** [comment]
Thanks for the pings. This one was part of Jetpack Settings v2, which we're not planning to work on at this time.

**Comment by lancewillett** [comment]
Moving this to closed because we're moving in the direction of simpler settings for WP.com Simple sites. Jetpack-enabled sites will have more fine-grained control of everything.

To finish this up, we'll need to remove WP Admin infinite scroll settings and related documentation.

**Comment by lancewillett** [comment]
Re-opening this: @Automattic/delta-samus is going to look at porting the settings to Calypso for WP.com Simple sites. CC @frontdevde @jblz
