### ISSUE TITLE
Themes: switching sites triggers 2nd page missing and blinking at the end

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#13262]
Found an issue (two?) while working on #12687.  

(1) Open the "All Sites" view of `/themes`
(2) Scroll to the very end
(3) Switch to a single .com site

Issue A → Notice that the 21st theme is actually the 41st: the "second page" of results is missing.

(4) Scroll to the very end again

Issue B → placeholders blink

![cap-](https://cloud.githubusercontent.com/assets/4389/25225656/228bb010-25ba-11e7-8dad-eca943c348b5.gif)

**Comment by budzanowski** [comment]
It happens when PaginatedQueryManager receives a page that it already has - page:1 that is. there is a call to QueryManager.receive and since it  does not understands pages it works in a different way. During some operations it reshuffles items in a way that items from page:1 are at the end. Then PaginatedQueryManager  does according to comment in code `// Replace the assumed set with the received items.` and deletes page:1 - which at this moment is page:2 - and ads received items page:1 back to their place.

**Comment by seear** [comment]
Fixed by #13549
