### ISSUE TITLE
Signup: language change fails and breaks theme slug

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#13280]
#### Steps to reproduce

1. Logged-out, using an incognito/private window, starting at URL: https://wordpress.com/themes
2. Click on a theme to show the theme page.
3. Click on "Pick this design" button.
4. End up on a URL like this `https://wordpress.com/start/with-theme/domains-theme-preselected?ref=calypshowcase&theme=twentyseventeen`
5. Not sure what triggers it to show up, but click the language change link (see screenshot below).

#### What I expected

I expected the language on the page to change.

#### What happened instead

The URL changed, adding the language string to the end of the theme slug (which will break the theme setup process as sign-up continues), and the language on the page remained in English.

#### Browser / OS version

Mac OS Chrome, latest

#### Screenshot / Video

<img width="1052" alt="screen_shot_2017-04-20_at_11_20_13_am" src="https://cloud.githubusercontent.com/assets/2036909/25238813/5bfb2e82-25bc-11e7-830f-fcc15a6aced7.png">

**Comment by sirbrillig** [comment]
I think what's happening is that the language link is assuming that there's no query string.

**Comment by sirbrillig** [comment]
Interesting addendum: unable to reproduce this using `wpcalypso`

**Comment by designsimply** [comment]
I couldn't get very far in the steps. Here's what happened when I tried testing:

1. Start at https://wordpress.com/themes (logged out)
1. Click on a theme to show the theme page.
1. Click the "Activate this design" button.

<strong>Result:</strong> I'm stuck on step 4 from the steps to reproduce, instead of seeing a link like <code>https://wordpress.com/start/with-theme/domains-theme-preselected?ref=calypshowcase&theme=twentyseventeen</code>, I see a modal window asking me to select a blog to activate the theme but I can't because I have not signed in and don't have any blogs to select:

![screen shot 2017-04-20 at thu apr 20 10 45 57 am](https://cloud.githubusercontent.com/assets/1119271/25242356/8e07db60-25b6-11e7-8f08-72d602a8b4b9.png)
<sup>Seen at https://wordpress.com/theme/independent-publisher-2 using Firefox 53.0 on Mac OS X 10.12.4 logged out unproxied.</sup>

<strong>Video:</strong> [22s](https://cloudup.com/cJCTA3qUM41)

How do I trigger the language selector?

Is it possible I'm in an A/B test? How do I check that if I'm logged out?

**Comment by folletto** [comment]
@designsimply you stumbled in a different bug: it's a bug on log-out not clearing data / Calypso trying reading it as logged in. You can see more in #11766. 

To avoid that bug, either:

1. Clear local DB caches
2. Use a new incognito session (make sure you didn't have lingering incognito windows as the session would be preserved across until the last window is closed).

**Comment by sirbrillig** [comment]
> How do I trigger the language selector?

I'm not actually sure. I think it's something that your browser sends to the site. Perhaps this: http://stackoverflow.com/questions/37221494/how-to-change-the-locale-in-chrome-browser

> Is it possible I'm in an A/B test? How do I check that if I'm logged out?

Try from an incognito window, logged-out.
