### ISSUE TITLE
Editor: Twitch.tv shortcode not working

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#13392]
#### Steps to reproduce
1. Starting at URL: WordPress.com/post
2. Add twitch.tv shortcode like `[twitchtv url="https://www.twitch.tv/videos/137551859"]`

3. Notice that https://www.twitch.tv/videos/137551859 plays fine
4. Publish the post - black video
5. Try it without the s in https and it will render the play button and say offline in the upper right corner `[twitchtv url="https://www.twitch.tv/videos/137551859"]`

#### What I expected
To see a sweet twitch embed as described here: https://en.support.wordpress.com/videos/twitch-tv-shortcode/

#### What happened instead
Blackness

#### Browser / OS version
Tested Mac Chrome/FF/Safari latest of everything

#### Screenshot / Video
Test post here: 
https://s-n-2-p.blog/2017/04/25/twitch/

Feel free to edit, tinker right there - testing only site

#### Context / Source
User reported

**Comment by kriskorn** [comment]
Another user report - 723944-zen

**Comment by kamikazeballoon** [comment]
Related: 1748342-hc (user trying to embed a Twitch Clip, url starts with clips.twitch.tv). Displays Twitch video frame but doesn't play when embedded, either in preview or published. Tested on Chrome/Win10.

**Comment by mlaetitia** [comment]
Also related: 600911-hc and 1018455-zen.
User tried to embed the following shortcode:  [twitchtv url="https://www.twitch.tv/videos/238686709"] . Black frame with the "Offline" word on it. He was able to embed a live streaming but not a regular video.

Tested with Mozilla Firefox / Win10.

**Comment by Nic-Sevic** [comment]
New case 3872607-zen where this is not working in preview but is on live posts

For simple sites and Ecom: editor preview not working but works live
For AT Business sites: editor preview works and live works

Not working view:
<img width="679" alt="Markup 2021-04-01 at 18 52 56" src="https://user-images.githubusercontent.com/47717887/113321682-82eefd80-931c-11eb-808a-0f23587d6546.png">

Working View:
<img width="655" alt="Markup 2021-04-01 at 18 59 58" src="https://user-images.githubusercontent.com/47717887/113321704-871b1b00-931c-11eb-98b2-8c5a637b139f.png">

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
