### ISSUE TITLE
Help: Ending a chat while a user is on /help/contact is a jarring experience.

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#1341]
Repro:

1. Target a group with operators available.
2. Navigate to /help/contact and initiate a chat.
3. As an operator, end the chat.

Expected: There'll be some reasonable indicator that the chat has ended.

Actual: The screen refreshes to the offline contact form and shows the `Sorry! We just missed you as our Happiness Engineers stepped away.` notification. 

To better illustrate the interaction, here's a gif of the interaction:

![chat-end](https://cloud.githubusercontent.com/assets/2738252/11637466/a4d186c6-9cef-11e5-8bc7-3359605dd377.gif)

It's a pretty jarring experience. I'm not sure what the proper experience here is. Maybe on `!end` in this scenario, we could show a notification that the chat has been ended and disable the text entry field? Cc @mattmiklic for design feedback.

**Comment by omarjackman** [comment]
@dllh I agree this is pretty jarring but I should note something thats missing from your test instructions: All operators go away after the chat has ended.

Typically the chat would just stay there so that you could resume it if you wanted to. This is tricky because a user might want to continue the chat after the op has ended it and then may choose to create a ticket if theres no one else to chat with.

**Comment by omarjackman** [comment]
@dllh What bothers me most about this is the widget flicker in the bottom right corner that occurs when the chat is unmounted and the contact form gets mounted. I'm hoping that it was inperceptible and was only caught by your animated gif maker because it caught the lucky frame that showed it.

**Comment by dllh** [comment]
Wouldn't my repro still be valid in cases in which all operators are busy when the chat ends?

I don't remember noticing the flicker you point out when I was testing, but it's something we should maybe test a bit more and see if we can fix if it is in evidence outside of screen capture software.

**Comment by mattmiklic** [comment]
Here's what I was thinking, based on our conversations about this previously. Keeps the chat visible, so the user can refer back to it, but disables the text field (using the styling from the standard disabled text input). Since we automatically send the user a transcript, we let them know that. The end of the chat is marked with a line and the W logo; the same treatment we use at the end of a list of posts, etc.

![chat-full](https://cloud.githubusercontent.com/assets/1396552/11723525/e24ce14a-9f3c-11e5-99a6-ece248d8d2b6.png)

**Comment by omarjackman** [comment]
I will add the notification here however the styling will with the WP logo will have to come later when I start restyling.
