### ISSUE TITLE
Reader: Search on Manage should not show sites you're already following in results

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13426]
In Search on Manage: The top field is labeled "Follow Something New". The purpose of this form is to find new things to follow. So the sites you're already following should not appear in results. The place to look for things you're already following is in the section below: "Followed Sites."

Also note that the design called for the placeholder text to be "Search or enter URL to follow...". Since we haven't hooked up the URL part yet, let's use "Enter text to search..." for now. Cool?

cc @samouri

**Comment by gibrown** [comment]
@fraying on the manage page, when you have quite a few things you are following remembering what you are following becomes difficult (I never do). I feel like we should somehow be showing what the user is already following that matches? I wouldn't think it would add too much noise to the results? 

I guess we have a separate search for this, but it is unfortunate to have to search someplace else to find things you are already following. Makes me want a single search box rather than having two. I feel like the UI with two different search boxes really makes me hunt for the one that is specific to sites I am already following.

On the main search on the following page (with sites added in the sidebar) I think we need to show things you are already following so we can support more navigational type searches. Type in a site so you can easily go and find it's content whether you are following it or not.

**Comment by fraying** [comment]
Let's try it as designed first.

**Comment by samouri** [comment]
> I guess we have a separate search for this, but it is unfortunate to have to search someplace else to find things you are already following. 

I agree with that and could even imagine boosting things you already follow (for blog/site title matches...not necessarily content/tag matching)

**Comment by fraying** [comment]
The point of the top box is to find something NEW to follow. That's why it says "Follow Something New". This is the same reason why the search box below (the one that says "Search Followed Sites") doesn't return things you're not following.

This will become clearer when the design is fully implemented.

**Comment by samouri** [comment]
@gibrown any updates here?   Is this doable on the backend or will we need to filter in calypso?

**Comment by gibrown** [comment]
Will do this on the backend. Very doable.

**Comment by blowery** [comment]
will we have to pass a special flag to filter followed stuff? if we want to show followed items on the sites in search project, we'll need a way to toggle back and forth...

**Comment by gibrown** [comment]
Deployed a fix to exclude everything the user is already following (so this issue should no longer be a blocker).

@blowery ya that makes sense. I guess the default should be to not filter them out, and then we add an option to filter them out?

**Comment by gibrown** [comment]
This is currently live for search on manage.

I'm not really a fan. We've already hit cases in testing where we confused ourselves because we went searching for ma.tt and it wasn't at the top because we were already following it. We shouldn't necessarily design for ourselves here, but the case where a user is trying to see where they are in the results seems like something we should support somehow.

**Comment by jancavan** [comment]
Today I searched for "time.com" and was confused why their site wasn't on the search results. I think my expectation would be that the site I'm looking for, whether or not I'm already following it, would still be in the results.

It does say right below the search bar that I am in fact following the site, but I must have missed that at first perhaps because it doesn't have the same treatment as the rest of the results.
