### ISSUE TITLE
Remove IFTTT posts from tag pages

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13424]
We should remove posts tagged "IFTTT" from tag pages. They're automated and largely valueless. And since tag pages are reverse-chronological, a single site can spam a tag, harming the user experience.

This request has come from users, too.

@blowery has some code started to do this. Just posting an issue to track it.

**Comment by blowery** [comment]
I'd started a filter to prevent IFTTT tagged posts from entering the tag graph at all. Now considering doing this as an output filter so that folks subscribed to IFTTT (there are a few, crazy folks) could still see posts there. It would also let us filter on other tags that are a bit spammy while still letting folks subscribe to those somewhat spammy tags. I think @gibrown had some other examples.

**Comment by fraying** [comment]
@blowery Sounds good. We'd talked about banishing one other tag, but I think that one should stay. This is an extreme action that I want to reserve for automated posting systems. Are there others besides IFTTT?

Either way, having a stop list for danger sign tags is a great idea. 👍

**Comment by gibrown** [comment]
https://wordpress.com/tag/reddit is worth taking a look at after we block ifttt. There seem to be a lot of folks using IFTTT to post from Reddit, but not all of them still have the "ifttt" tag getting added, but the "reddit" tag is there. You can see the ifttt.com urls in the content that they post. Eventually we could possibly filter out posts with that domain in them.
