### ISSUE TITLE
Jetpack Connection: Reconnect link below site card

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#13475]
We should extend the concept of a 'reconnect' link (#13354) to the site picker—if a site has a plan and is disconnected (improperly without going through any kind of explicit flow) should we leave it in the sites list (rather than removing it) and display a very similar notice to above underneath the site card.

Currently we let the site be removed from the sites list, but still display reference to the site and its upgrades in /me/purchases which creates a bit of a strange undiscoverable situation.

![image](https://cloud.githubusercontent.com/assets/437258/25499780/9a7915d6-2b5a-11e7-9b96-3b756e92b380.png)

cc @beaulebens @richardmuscat @keoshi @ryelle @johnHackworth

**Comment by ryelle** [comment]
What do you mean by "improperly without going through any kind of explicit flow" — like if the site goes offline? I'm having trouble thinking this through without context of when it would show up. And once here, what does the user see on Calypso itself? If we can't connect to their site, there's not really anything we can do or show.

> Currently we let the site be removed from the sites list, but still display reference to the site and its upgrades in /me/purchases which creates a bit of a strange undiscoverable situation.

This makes sense to me as we're showing the record of a purchase, even if the user's been removed from the site (this can happen on wp.com sites), or the site's been disconnected. Either way the site itself is secondary, helpful info related to the primary info of the purchase. Of course, we should have the reconnect button on purchases, because we want folks to be able to _use_ their plans 🙂

**Comment by rickybanister** [comment]
Sorry, I meant like if a user deleted the Jetpack plugin files from their site (or something similar). Clicking 'reconnect' above would lead them through reinstalling/activating/connecting Jetpack.

**Comment by johnHackworth** [comment]
Do you mean when the site is disconnected in any way that is not properly going through the disconnect flow, isn't it? I'm not sure if right now we have the ability to differentiate (I mean, I'm not sure if we are storing anything indicating that a user have done the disconnection clicking in 'disconnect', besides some tracks events). Do you know if we can extract that info from the shadow site, @lezama  or @dereksmart  ?

**Comment by lezama** [comment]
@johnHackworth normally a properly disconnected site has no tokens on the tokens table.

cc @enejb as he has been working on sticking sites that hasn't been properly disconnected.

**Comment by rickybanister** [comment]
@johnHackworth let's chat about this ticket next time we talk. 

I don't think the proposed solution is the right one, but I'd like to make sure we're doing what we can to help people with connection issues both from the remote site side and the wordpress.com side. 

Perhaps we can start with collecting data to see how often someone sees a 'couldn't reach %site%' error notice in WordPress.com.
