### ISSUE TITLE
Some Rec Posts are getting long excerpts even though they have images

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13478]
Recently @jancavan changed things so that Rec Posts without images would get longer excerpts. (Yay!)

But! Check out https://wordpress.com/read/search

Some rec posts (at least for me) are getting the longer excerpts even though they have images.

<img width="840" alt="screen shot 2017-04-27 at 12 46 34 pm" src="https://cloud.githubusercontent.com/assets/24388/25501536/efa751f2-2b47-11e7-835b-4529d0ceb389.png">
<img width="846" alt="screen shot 2017-04-27 at 12 46 28 pm" src="https://cloud.githubusercontent.com/assets/24388/25501537/efc1ab88-2b47-11e7-8f0a-0b3073fdc10f.png">

Any idea why?

**Comment by jancavan** [comment]
I came across this last night, but couldn't repro after refreshing. I'm seeing it again today though and the issue is, these posts aren't being assigned the  `is-thumbnail` class even though they do have feature images.

![screenshot 2017-04-27 13 01 36](https://cloud.githubusercontent.com/assets/4924246/25502022/c800bfd8-2b49-11e7-81cf-29e311de2a74.png)

When I click on the post though, it doesn't contain the image from the thumbnail?

Do you know why @bluefuton @samouri?

**Comment by jancavan** [comment]
Example:
https://wordpress.com/read/blogs/13137174/posts/23849

![screenshot 2017-04-27 13 05 21](https://cloud.githubusercontent.com/assets/4924246/25502119/35b535c2-2b4a-11e7-95e9-80b96b18ca52.png)

**Comment by fraying** [comment]
Oh! I know why. It's because these are thumbnails for videos, thanks to work @samouri did a while back.

**Comment by jancavan** [comment]
If `has-thumbnail` can be added to those post cards, it should automatically shorten the title/excerpt to 4 lines.

**Comment by jancavan** [comment]
Related: 
Some recs are also getting the `has-thumbail` class when they shouldn't be. 

Example:
This should be showing a longer except, but it isn't because it's getting the incorrect class.

![screenshot 2017-04-27 16 52 06](https://cloud.githubusercontent.com/assets/4924246/25508890/e17a6804-2b69-11e7-9fe3-861bd188b70c.png)

Came from this post:
https://wpcalypso.wordpress.com/read/blogs/112669439/posts/3104

Link to full-post:
https://wpcalypso.wordpress.com/read/blogs/101129525/posts/1869

**Comment by samouri** [comment]
> Oh! I know why. It's because these are thumbnails for videos, thanks to work @samouri did a while back. Jake, could you help here?

@fraying: you nailed it.  And when I added that capability I didn't update the css selector :(
