### ISSUE TITLE
Reader: Body text is bolded

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#13484]
This post's body text is bolded: https://wpcalypso.wordpress.com/read/blogs/113888668/posts/941 as well as the original post.

Any way for this to use normal weight?

**Comment by marekhrabe** [comment]
The text is bold right in the source code of the post and a lot of other posts and pages user created. Not a rendering bug - it's manually set to be bold.

You can advise the user to edit the post, select everything and press the "bold" button once or twice to disable bold text for all content.

**Comment by blowery** [comment]
This is one of those fun ones where we need to decide how much policing of user formatting choices we're willing to do. 

> Not a rendering bug - it's manually set to be bold.
I don't think Jan was stating it was a rendering bug, but wondering if there was something we could do to strip the intentional overuse of bolding. 

In this case, the author used `<strong>` tags around each block of text, not inline styles, so there's not a whole lot we can do without other intentional uses of `<strong>`.

> You can advise the user to edit the post, select everything and press the "bold" button once or twice to disable bold text for all content.

I doubt we're in touch with the user. @jancavan Did this come from a support request?

**Comment by jancavan** [comment]
> Did this come from a support request?

No, it didn't. We corrected this [post with a justified body text](https://github.com/Automattic/wp-calypso/issues/13356) that @fraying reported so I thought we wanted to do the same with this one.
