### ISSUE TITLE
Social Signup: Separate user's account being displayed

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#13555]
Reported by @hafizrahman in p6qnuF-4JF-p2:

@hafizrahman reported seeing, in the processing screen, a message about a completely unrelated account (with a similar username) when signing up. We should try to reproduce this by comparing information from both accounts with help from Hafiz. Usernames noticed were `freebb` (incorrect) and `freebble` (correct).

**Comment by fabianapsimoes** [comment]
@hafizrahman are you able to reproduce this issue with a different pair of usernames?

**Comment by fabianapsimoes** [comment]
See 5822-comment in p6qnuF-4JF-p2 for an updated video of the issue.

**Comment by stephanethomas** [comment]
We no longer display this message, although I'm not entirely sure why since the email address of new accounts created during social signup must still be verified by users. It’s probably because one of [those conditions](https://github.com/Automattic/wp-calypso/blob/2de869e7aa31262240294a337c271803bed959a6/client/signup/processing-screen/index.jsx#L21-L41) is met (probably the one that checks if the user object contains an email address).

This may just be a symptom though, and if somehow we picked up the wrong account this is something we should fix it asap. This might not be as bad as it sounds, it might just be some data from the Redux global state tree that is not updated and become stale.

**Comment by fabianapsimoes** [comment]
> although I'm not entirely sure why since the email address of new accounts created during social signup must still be verified by users. 

We shouldn't be asking users to verify the address anyway, since their social network has already request that from them. That should be addressed with T513-code.

**Comment by fabianapsimoes** [comment]
I'm not able to reproduce the original issue reported here. I'll close this, but feel free to reopen if you run into it again.
