### ISSUE TITLE
Social Signup: Use different version of Google's JS script 

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#13554]
As suggested by @drewblaisdell, there are a few different issues that we may be able to mitigate by changing the script we load from Google. @josemarques mentioned that the authentication popup is blocked by several different browsers sometimes. Also, @danhauk mentions the full list of permissions is not displayed by Google.

cc @Tug who has been looking into this too in order to 1504-tr (users stuck in the account step after authentication with Google).

**Comment by Tug** [comment]
We already tried the other version of the js client here https://github.com/Automattic/wp-calypso/compare/try/google-platform-js?expand=1 and https://github.com/Automattic/wp-calypso/compare/try/google-platform-api?expand=1 and it didn't fix anything. Closing this as the bug is tracked in https://github.com/Automattic/wp-calypso/issues/13747
