### ISSUE TITLE
Social Signup: Customize message when "signing up" using an existing email

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#13551]
Reported by @josemarques:

We should display a different message when "signing up" for an account associated with an existing email. Currently, in the processing screen, we don't indicate that the user is logging in to an existing account during signup on the success page.

cc @ranh for copy.

**Comment by kristastevens** [comment]
Standing by for copy review once @ranh's had a chance to whip up copy.

**Comment by ranh** [comment]
Currently we say:

> **Done!** Thanks for waiting, we're ready for you to get started. 
>
> [Continue]

What is the purpose of this message? Can we just go directly to the next screen, without waiting for users to hit the Continue button?

If we want to keep it, we can use this for existing users:

> **Done!** Thanks for waiting, we found your account and logged you in.
>
> [Continue]

**Comment by fabianapsimoes** [comment]
> What is the purpose of this message? Can we just go directly to the next screen, without waiting for users to hit the Continue button?

IIRC, @scruffian was looking into this recently. Did you find any reasons for that, Ben?

**Comment by scruffian** [comment]
@fabianapsimoes I was unable to discover why that change was made. IMO we should revert it.

**Comment by fabianapsimoes** [comment]
I'm in favor of removing that Continue button. It seems Triton has recently experimented removing it only for users with a plan in the cart, and it improved purchase conversion. See: p3fqKv-3xx-p2. 

I don't really see a reason why this wasn't removed for all flows / users. Maybe @bisko has some insight to offer?

**Comment by bisko** [comment]
It was kept in place to allow users to see the account activation nudge at the bottom of the screen.
This was done, because we previously didn't have any activation nudges inside the editor and users were confused why their posts weren't published ( stayed as drafts ). Now we have a popup that tells the user that they have to confirm their account:

<img width="376" alt="screen shot 2017-05-15 at 07 45 06" src="https://cloud.githubusercontent.com/assets/184938/26056241/7f6f5b56-3942-11e7-8388-95096f156eee.png">

I'd be happy to see the Continue button gone, as it is an unnecessary step in the flow of things, but I think it needs a good test, to see how it will affect non-paid account activations / conversions.

If it proves that the account activation nudge ( the whole Continue screen ) has low impact, we can safely remove it and have it auto-continue to the user's site.

**Comment by fabianapsimoes** [comment]
OK, sounds like the original issue is no longer possible to reproduce. There's still the question about the Continue button, but we should address that separately.
