### ISSUE TITLE
Pages: allow authors to set number of posts for blog page (was in Reading Settings in wp-admin)

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#13569]
This is for parity, split out from #3900 

As a WordPress.com user, I want to be able to change the "posts per page" number on my “blog posts” page on my `/pages` list so that I can avoid visiting wp-admin to make this change.

How the current Calypso `/pages` list looks — no setting here yet:

<img width="1263" alt="screen shot 2017-05-02 at 10 53 27" src="https://cloud.githubusercontent.com/assets/66797/25631796/56bb4c90-2f26-11e7-844f-b11cb3b201c2.png">

Previously in wp-admin:

<img width="796" alt="screen shot 2017-05-02 at 10 59 38" src="https://cloud.githubusercontent.com/assets/66797/25631838/73dadbba-2f26-11e7-8583-c0bc3ba2905e.png">

**Comment by lancewillett** [comment]
Let's get this one in right away to close this UX gap.

**Comment by rickybanister** [comment]
Any thoughts on the interface? 

At the minimum we could change the 'Your latest posts, shown on homepage' text to be an inline form label like this:

![image](https://cloud.githubusercontent.com/assets/437258/25633190/524739e4-2f44-11e7-9b45-7f43d0ffefe9.png)

It could say `Show [10] posts at a time on my homepage`

**Comment by kathrynwp** [comment]
> It could say Show [10] posts at a time on my homepage

Since the blog isn't always on the homepage, it should say something more like:

> Show [10] posts at a time on my blog

We should also keep in mind that Infinite Scroll loads posts in batches that aren't affected by this setting. This relates to something else I think we're currently missing in Calypso on WP.com, which is the ability to turn default IS into "click-to-scroll" (aka "load more posts) IS, a setting currently at WP Admin > Settings > Writing:

**Default IS**
![reading settings intergalactic 2 wordpress](https://cloud.githubusercontent.com/assets/7662449/25635183/36144fbc-2f4b-11e7-8035-9b40d76672fd.png)

**Click-to-Scroll IS**

![reading settings intergalactic 2 wordpress-1](https://cloud.githubusercontent.com/assets/7662449/25635266/8572ea46-2f4b-11e7-8a61-f9f4b6b3ad99.png)

**Comment by rickybanister** [comment]
cc @tyxla do we account for the 'click-to-scroll' alert if the user has footer widgets in our recent changes to the calypso infinite scroll settings (as per @kathrynwp's last comment?)

**Comment by lancewillett** [comment]
As a related note: #13568 — this relates to implementing CPT "posts per page" settings because it'll be in the same place, and use the same UI for toggle and page number.

**Comment by tyxla** [comment]
@rickybanister good call, we're not taking that into consideration right now. I've opened #13637 to track that one separately, it could use a couple of design 👀  before we develop it.

**Comment by jonathansadowski** [comment]
With #13718 we've added posts per page under general settings. This included a change in r155891-wpcom to allow the setting to be set via the API, which was also submitted as a Jetpack PR: https://github.com/Automattic/jetpack/pull/7154

**Comment by tyxla** [comment]
Nice work @jonathansadowski! Guess we can close this one @lancewillett? Or do you think this setting should be implemented elsewhere, too?

**Comment by lancewillett** [comment]
Fine to close. CC @rickybanister who is going to look at a better location for it as General isn't ideal. Writing might be OK, as the other CPT settings and page counts will be there.

**Comment by designsimply** [comment]
Following up to say the "Posts Per Page" setting location was tracked in #13868 and closed in #13916.

**Comment by tyxla** [comment]
Thanks for keeping stuff organized @designsimply 🙇
