### ISSUE TITLE
Media: Videos tab inaccessible after downgrading back to Free plan

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#13580]
#### Steps to reproduce
1. Switch to a site that has the Premium or Business upgrade, so that VideoPress is enabled.
2. Go to the Media Library at `https://wordpress.com/media/videos/example.wordpress.com`.
3. Upload a video.
4. Make sure that, anytime you load Calypso, you'll find that video in both the All and the Video tabs of the Media Library.
5. Lose the paid upgrade on that site, so that it is back on the Free plan. This can happen by failing to renew a plan, or any artificial means for debugging.
6. As a user, I understand that I can no longer upload new videos to the library, but I still have the expectation of inserting previously uploaded content. Go to the Media Library (All tab), see that there are too many images, making it hard to find videos.
7. Try switching to the Videos tab to find videos.

#### What I expected
Regardless of any possible upgrade nudges, I would be able to access my collection of videos, maybe to insert one into a post, or to copy its URL for other purposes.

#### What happened instead
The entire view is disabled, prompting me to upgrade, even though I don't want to upload a new video.

#### Screenshot / Video
<img width="1019" alt="calypso-video-downgrade" src="https://cloud.githubusercontent.com/assets/150562/25640969/ad49397e-2f89-11e7-9dc2-b64a0788be5f.png">

#### Context / Source
#dogfooding #flowsharing

**Comment by mcsf** [comment]
> If you would like it to remain open

Though a seemingly small thing, it'd be great to see this issue fixed. /cc @lancewillett

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

📌 ADDITIONAL NOTES

I gave this a quick test, and it appears this is no longer an issue. Closing as **not reproducible**.

![Markup on 2023-08-10 at 14:33:56](https://github.com/Automattic/wp-calypso/assets/27249804/90d9bea5-6cdc-421c-99e2-dc67d0c6739a)

---

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
