### ISSUE TITLE
Site Picker: ability to hide and show sites in site picker in Calypso

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#13589]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com in a multi-site account
2. Choose "SWITCH SITE"
3. Follow link at bottom to "Change" sites

<img width="258" alt="screen shot 2017-05-03 at 5 00 15 pm" src="https://cloud.githubusercontent.com/assets/128826/25650707/29fbb2f6-3022-11e7-800d-0f7b8b28ad62.png">

#### What I expected

To be able to manage these in Calypso

#### What happened instead

Sent to wp-admin (https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs&show=hidden)

#### Browser / OS version

Chrome OSX

#### Context / Source
 #reallife #dogfooding

**Comment by mtias** [comment]
See #8335.

**Comment by designsimply** [comment]
After reading through #8335 and #9587, I feel the currently accepted resolution for this is to leave the option to hide sites out of Calypso and iterate the sites list so that the last five selected sites are always available at the top of the list on any browser or device. Also see #13632.

@alisterscott would you be okay to close this issue in favor of #13632?

**Comment by alisterscott** [comment]
@designsimply sure, sounds good
