### ISSUE TITLE
Plugins: Styling problems on multi-site installs

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#13587]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plugins
2. Click through to a plugin which is installed on multiple, multi-site sites (e.g. Jetpack), which has an update available
3. Scroll down to where the sites are listed, and observe all sorts of styling problems.

#### What I expected

Professional, consistent design and layout.

#### What happened instead

Bugs :(

#### Browser / OS version

Chrome, OSX.

#### Screenshot / Video

![screen_shot_2017-05-01_at_9_51_34_pm](https://cloud.githubusercontent.com/assets/108942/25647416/044070e0-2f7f-11e7-9c85-8c38ceaec4d7.png)
Left alignment on the active/autoupdates/removal labels.

![screen_shot_2017-05-02_at_11_57_48_am](https://cloud.githubusercontent.com/assets/108942/25647422/0d72893c-2f7f-11e7-9fb6-c78a9976d9ee.png)
Vertical alignment on the Manage Connection links

![screen_shot_2017-05-02_at_11_57_56_am](https://cloud.githubusercontent.com/assets/108942/25647431/194df6ba-2f7f-11e7-81eb-0ddd24b0659b.png)
After clicking to update a plugin, the button wraps onto a second line (wasn't like that before clicking to update)

![screen_shot_2017-05-02_at_11_58_06_am](https://cloud.githubusercontent.com/assets/108942/25647443/2358371a-2f7f-11e7-9715-a1838e224d7e.png)
Left edge of the button cut off. Also the weird Management Disabled/Disconnect combo.

**Comment by beaulebens** [comment]
Note that a _lot_ of this has changed since this was originally reported, so don't trust these screenshots.

**Comment by keoshi** [comment]
After doing a bit of triaging, this is what I found:

- [x] ~Left alignment on the active/autoupdates/removal labels.~
  - No longer an issue.
- [x] ~Vertical alignment on the Manage Connection links~
  - They're left aligned now, no longer an issue as well.
- [ ] After clicking to update a plugin, the button wraps onto a second line (wasn't like that before clicking to update)
  - Still an issue; the culprit is `foldable-card__secondary`'s flex ratio once again.
- [x] ~Left edge of the button cut off. Also the weird Management Disabled/Disconnect combo.~
  - Couldn't reproduce but would imagine the button is still an issue (referenced in point above), but not the disconnected weirdness (because the alignment changed since).

**Comment by keoshi** [comment]
Remaining issue addressed here: https://github.com/Automattic/wp-calypso/pull/23136
