### ISSUE TITLE
WooCommerce: Orders list view

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#13654]
Create the orders list view for WooCommerce using data from the WooCommerce API.

**Comment by kellychoffman** [comment]
The order list view has been slightly updated since the last design, most notably the items in the filter bar and the split status in the table views: 

![orders list](https://user-images.githubusercontent.com/5835847/26851227-4755f91c-4ad8-11e7-9c54-2ab661c082dd.png)

cc @ryelle as I think you will be tackling this. Let me know if you have any questions.
