### ISSUE TITLE
Store Orders: Edit notes

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#13689]
This is the UI component work for editing and reviewing order notes.

**Comment by ryelle** [comment]
@kellychoffman @jameskoster There's no UI to edit order notes in the design posted here: https://github.com/Automattic/wp-calypso/issues/16197#issuecomment-317696662

We can't currently do this in wp-admin - there's no technical reason AFAIK, but the UI is just not there. Is this a feature we want to add, or was this issue just added because create & delete were?

If it is something we want to add, we probably only want to add it to private notes (not those emailed to the customer, since we can't update the email).

**Comment by jameskoster** [comment]
Editing (and trashing) internal notes would be useful, but it's not a priority imo. Updated the designs to add edit/trash links;

![edit-button](https://cldup.com/zefnfbYjrK-3000x3000.png)

Editing:

![editing](https://cldup.com/ECwYjMJEXO-1200x1200.png)

**Comment by kellychoffman** [comment]
>  it's not a priority imo

Agree we could hold off implementing this until next quarter.

**Comment by ryelle** [comment]
Thanks for the updated design 🙂 

> we could hold off implementing this until next quarter.

Sounds good, I'll unassign myself from it for now, then.
