### ISSUE TITLE
Store Orders: Trash notes

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#13688]
The code required to trash order notes via the API.

**Comment by timmyc** [comment]
Looks like this is already supported in the API: http://woocommerce.github.io/woocommerce-rest-api-docs/#delete-an-order-note

**Comment by ryelle** [comment]
@timmyc  Specifically this issue was about adding UI to delete order notes, which we never built - this was just one of [the many tracking issues](https://github.com/Automattic/wp-calypso/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3AStore+label%3A%22%5BType%5D+Task%22) from the store project. I agree with closing it, but wanted to clarify 🙂

**Comment by timmyc** [comment]
Ah gotcha, that makes much more sense. But we'll still keep it closed out... nobody likes stale issues.
