### ISSUE TITLE
Help: Contact form never loads on mobile

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#1371]
I can't get the contact form to load on mobile devices. The help search works as expected, but when I click "Contact us" I just get the blinking placeholder:

<img src="https://cloud.githubusercontent.com/assets/8658164/11659960/b4e5b64e-9dc2-11e5-848b-af4a1c264493.png" width="50%">

I left it for about an hour while doing other things, to see if it would ever load, and it didn't. I don't see any console errors or failed network requests to explain why the contact form doesn't appear.

Tested and reproduced on iPhone 6, Safari, iOS 9.1 and Nexus 9, Chrome, Android 6.0.

**Comment by rachelmcr** [comment]
I should also note that I tried accessing the contact form two different ways:

1. I opened https://wpcalypso.wordpress.com/help and tapped "Contact us" to open the contact form.
2. I opened https://wpcalypso.wordpress.com/help/contact directly.

In both cases, the contact form didn't load on my mobile devices (but it did load in both cases on my laptop).

**Comment by omarjackman** [comment]
@rachelmcr Thanks for finding this. So the issue here is that currently olark is disabled for mobile browsers. This is a setting in our olark master account and the work around for this will be to view the site in desktop mode. Theres usually a checkbox in the context menu that will allow you to do this.

Here's an example:
![screenshot_2015-12-09-12-59-35](https://cloud.githubusercontent.com/assets/1854440/11693891/55110ad0-9e75-11e5-8983-f213c31f05df.png)

It probably makes sense to leave this issue open as a reminder that we need to enable olark for mobile browsers once testing has concluded.

**Comment by rachelmcr** [comment]
Aha! That does the trick, and far it's working as expected.

**Comment by dllh** [comment]
We will want to toggle the global setting on for launch.

**Comment by dllh** [comment]
I've assigned this to myself. I'll toggle the option on in settings and test a few things to make sure it doesn't seem to break anything outside of Calypso.

**Comment by dllh** [comment]
I enabled the setting in our chat control panel and tested in mobile in both wp-admin and Calypso, and the feature works well and crosses boundaries (navigating from calypso to wp-admin and back) as expected. Figuring this is resolved.
