### ISSUE TITLE
Free Trials: create a signup flow for free trials

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1374]
Since we won't be offering domains in free trials (p6qnuF-129-p2), we won't be able to send users to the default signup flow. We need to create a specific trial flow that doesn't include the Domain step.

**Comment by breezyskies** [comment]
Another option would be to show the domains step, but remove references to paid domains / only show *.wordpress.com domains in the results.

**Comment by drewblaisdell** [comment]
During our meetup, we decided that the free trial test results would be more accurate here if we didn't change the flow and allowed users to checkout with both a trial plan and a domain name if they want. Which do you think is better for the v1 test, @breezyskies? Checking out with both a trial and a domain isn't currently possible, so either way, we're going to need to update signup or checkout.

**Comment by breezyskies** [comment]
> Another option would be to show the domains step, but remove references to paid domains / only show *.wordpress.com domains in the results. 

Realizing after I suggested this that the domains step comes before the plan selection, so this wouldn't work without a reorder of the steps anyways.

> Checking out with both a trial and a domain isn't currently possible, so either way, we're going to need to update signup or checkout.

I'd lean towards updating checkout over updating signup. We previously discussed a separate confirmation page for free trials in https://github.com/Automattic/wp-calypso/issues/1169 (not part of checkout), but maybe in the signup flow we just take the user to checkout with _only_ the domain in their cart. This would mean no explicit confirmation of starting a free trial during the signup flow, but I think that could work given that it implies a new site (rather than making a change to an existing site), so confirmation is less important (and less useful) in this flow. cc: @mikeshelton1503 

If the proposal above is too big of an undertaking for v1, we might want to consider a minimalist site address selection added to the user form step (removing the full domains step). Perhaps something like this:

<img width="429" alt="screen shot 2015-12-17 at 5 00 54 pm" src="https://cloud.githubusercontent.com/assets/3011211/11886528/e05bdc8a-a4df-11e5-82ba-9a98e2d9d14f.png">

(This would be my fallback choice given that it's not as clean of a test with multiple changes like this.)

**Comment by scruffian** [comment]
After chatting with @fabianapsimoes about this, I decided to create a simpler signup flow without a domain step at all, so that we can run our initial tests on this simpler flow, and not use resources to build something we might not use.
