### ISSUE TITLE
Fullpost: Broken Blavatar at Small Breakpoint

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13778]
On this page: https://wordpress.com/read/feeds/55945485/posts/1450740245

The blavatar appears as a broken image.

It's happening at all widths, but it's more obvious at narrow widths:

<img width="629" alt="screen shot 2017-05-08 at 2 00 11 pm" src="https://cloud.githubusercontent.com/assets/24388/25825208/07f0524c-33f7-11e7-8ef8-1644fe60e48c.png">

cc @jancavan @samouri

**Comment by jancavan** [comment]
I'm not seeing the blav in wider breakpoints too:

<img width="202" alt="screenshot 2017-05-17 09 41 56" src="https://cloud.githubusercontent.com/assets/4924246/26165520/1b091d2e-3ae5-11e7-8ecd-2ebb36f657b7.png">

I'm not sure why the blav is a broken link. Do you know why @samouri?

**Comment by samouri** [comment]
I think this may be more of a @blowery question.  
I looked into this for a bit last week and it seemed like the feed data may be bad

**Comment by fraying** [comment]
@blowery? (See above.)

**Comment by blowery** [comment]
His site icon (from jetpack) links to a busted image. :/

https://i0.wp.com/boo.waxy.org/wp-content/uploads/2016/10/square_logo.png?w=240

**Comment by fraying** [comment]
@blowery Weird! Can we do anything about that on our end?

**Comment by blowery** [comment]
I had a thought that we could fall back to the feed icon when the site icon fails to load, if it's present, but it turns out we didn't have it available due to a bug. Fixed that in https://github.com/Automattic/wp-calypso/pull/14830

However, falling back is pretty rough to do. The SiteIcon component doesn't really report out when a load fails.
