### ISSUE TITLE
Framework: sidebar navigation triggers "Cannot set property 'onload' of undefined"

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#13791]
![screen shot 2017-05-09 at 12 28 15](https://cloud.githubusercontent.com/assets/4389/25848610/fe296a98-34b2-11e7-830b-226e35493ad9.png)

When following a specific series of 3-4 clicks in the My Sites sidebar Calypso crashes.

How to reproduce:

* Open https://wordpress.com/stats
* Switch to any single site

Then from try the following sequences of clicks in the sidebar:

1. Stats → Plans → Testimonials → Sharing
2. Stats → Plans → Themes → Sharing
3. Stats → Themes → Plans
4. Stats → Portfolio → Plans

These work:

* Stats → Themes → Sharing
* Stats → Portfolio → Sharing
* Stats → Testimonials → Sharing

@ockham mentioned it might be something related with Single-Tree Rendering (STR).

**Comment by hoverduck** [comment]
I confirmed the bug in OSX Chrome and Firefox and Android Chrome with the above sequences.  Also more generally this fails:

* Stats -> Plans -> Themes -> _Anything_

**Comment by ockham** [comment]
Could this be due to notifications @dmsnell?

De-uglified code around the error seems to indicate so:

![image](https://cloud.githubusercontent.com/assets/96308/25853297/a2624d8c-34cc-11e7-8158-c71fe7a3c432.png)

**Comment by dmsnell** [comment]
> Could this be due to notifications @dmsnell?

yes. That code has caused so much sad in the form of browser errors. It needs to be fully audited and safe-guarded. Luckily this can be done by anyone now via Automattic/notifications-panel (and npm link or something).

If I can reproduce I can try and look at it today.

**Comment by dmsnell** [comment]
This is failing because `wpcom.js` isn't returning the XHR object it's supposed to. I confirmed in Chrome that even when manually creating the request we get back `undefined` instead of [the request](https://github.com/Automattic/wpcom.js/blob/master/lib/util/send-request.js#L81).

pinging @retrofox for help. I have confirmed that the params and callback exist.

```js
const params = {
  action: "connect",
  path: "/pinghub/wpcom/me/newest-note-data",
  method: "GET",
  apiVersion: "1.1",
  query: ""
}

const cb = function() {};

// expected XHR object
// or at _worst_ the request promise
const xhr = this.wpcom.req.get( params, cb ) // === undefined
```

@retrofox might there have been any recent changes in wpcom.js that could explain this? I didn't see anywhere that the request should return with `undefined`.

**Comment by dmsnell** [comment]
cc: @yoavf

**Comment by dmsnell** [comment]
The cause of this problem is that the `http-envelope-normalizer` is [breaking the wpcom.js API](https://github.com/Automattic/wp-calypso/blob/bc08b63dd364454b4dbdef5e44be949d8bde5eea/client/lib/wp/handlers/http-envelope-normalizer.js#L9) by not returning the request object when it intercepts requests.

I'll try to make the update and get this fixed. The sequencing is odd and I'm sure it must have to do with the injection of `http-envelope-normalizer`. _Probably_ this is affecting more than notifications as the error has been in the code for near a year; my guess is that notifications was the first thing to _expose_ it.

cc: @retrofox
