### ISSUE TITLE
Comments: Detail View

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#13894]
After we click on a comment, we're taken to the detail view.

The top row is the post (or comment) that the comment replied to. The blue text is the post title, and the gray text underneath is the post content (in the case of a reply to a comment, it would be the comment content).

![android-pending](https://cloud.githubusercontent.com/assets/1270189/25922484/375ee0e6-358e-11e7-86e1-5d793a1b4c11.png)

### Actions in each view

Pending view: Like, Approve, Reply, Edit, Spam, Trash
Approved view: Like, Approved, Reply, Edit, Spam, Trash
Spam view: Approve, Edit, Delete forever
Trash view: Approve, Spam, Delete forever

cc @drw158 I think we'll want to mark something as not spam in the spam view, if akismet categorized something incorrectly.

### Other States

Approve:
![android-approved](https://cloud.githubusercontent.com/assets/1270189/25922714/0df64c3e-358f-11e7-8c58-75a6261fa480.png)

Spammed
![android-spamed-comment](https://cloud.githubusercontent.com/assets/1270189/25922734/1fbeb262-358f-11e7-9289-f0cf4cc33fdc.png)

Trashed
![android-trashed-comment](https://cloud.githubusercontent.com/assets/1270189/25922741/25bcb61e-358f-11e7-97b7-40a1d9aac257.png)

Also see: p3fqKv-4v6-p2

**Comment by drw158** [comment]
> I think we'll want to mark something as not spam in the spam view, if akismet categorized something incorrectly.

I wrestled with that a little bit and my thought was that you wouldn't want to Not Spam a comment, you would only want to Delete Forever or Approve it (and Edit it before you Approve it). Instead of clicking on Not Spam, and then Approve, you could just click Approve. (currently it wp admin you can either hit Not Spam or Delete Permanently). 

But maybe there is a reason for the way wp admin is designed with those options. Is there a benefit of clicking on Not Spam and sending it to pending?

**Comment by gwwar** [comment]
Ah I missed that we had the approve/edit button there. Yeah I think it's fine to remove the option in that state then.
