### ISSUE TITLE
2FA: Send push verification when logged in with expired 2FA

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#13985]
Occasionally, two-factor authentication (2FA) will expire while I'm logged in to WordPress.com and working in Calypso. At that point, I'm presented with a modal to enter the verification code from my Authenticator application. It would be nice to receive the same push based verification I receive the first time I log in so I can just approve from my mobile WordPress.com app.

#### Steps to reproduce

1. Log in to WordPress.com with 2FA enabled.
1. Remove the `twostep_auth` cookie from `public-api.wordpress.com`. This simulates expired 2FA.
1. Refresh the page.
1. You will be presented with the auth screen, but not push verification.

#### What I expected

To get a push verification as well as the Authenticator code, just like at login time.

#### What happened instead

I have to enter a code, or I could log out and log back in to get a push verification.

#### Screenshot / Video

![2fa-reauth](https://cloud.githubusercontent.com/assets/841763/25992803/08c8d0a4-3708-11e7-8128-34698cf097ca.png)

**Comment by sirreal** [comment]
Still an issue as far as I know.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
