### ISSUE TITLE
Purchases: unsubscribed and expired purchases cannot be removed from a site

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#1402]
Right now it is possible to remove unsubscribed domains after expiration.

We should consider making it possible to do the same thing for post-refund but still valid domains.

There are many cases where a user no longer wants a domain to point to their site nor do they want to receive reminders to renew said domain.

Cases we should consider:
-domain mapping
-domain registrations
-domains bundled with a plan

*It is also currently impossible to separate a domain from an unsubscribed post-refund plan or an expired plan.

cc @mikeshelton1503 @fabianapsimoes since they are sitting next to me and discussing

**Comment by fabianapsimoes** [comment]
I think we should generally make it possible to remove unsubscribed purchases, not only for domains.

**Comment by fabianapsimoes** [comment]
> Right now it is possible to remove unsubscribed domains after expiration.

Actually, according to https://github.com/Automattic/wp-calypso/issues/241, we did not implement this yet. So we should make sure this issue also covers the remove option for unsubscribed purchases.

**Comment by spncrb** [comment]
We should add another scenario here:
When a user deletes a site, we should offer a simple (maybe a confirmation checkbox and a button?) way to cancel all purchases.

In the current situation, deleting a site is completely impossible for sites with any upgrades outside of the refund window.

cc @mikeshelton1503

**Comment by mikeshelton1503** [comment]
>In the current situation, deleting a site is completely impossible for sites with any upgrades outside of the refund window.

Good catch!

> When a user deletes a site, we should offer a simple (maybe a confirmation checkbox and a button?) way to cancel all purchases.

A checkbox/button seems like the easiest way for the user, however I'm not sure if we can do it that way. What about if a user has a domain associated with their account, we don't want to just cancel it without the user fully understanding what they're doing. The delete flow probably needs to be rethought however for now I'd recommend we rely on the remove purchase option that this issue is suggesting we add.

**Comment by fabianapsimoes** [comment]
> The delete flow probably needs to be rethought however for now I'd recommend we rely on the remove purchase option that this issue is suggesting we add.

For users on a subscribed state though, that's complicated. Right now, the idea is to only show Remove for unsubscribed purchases. If we did show it for subscribed purchases, users would either see two options, cancel and remove, or have to do it in two steps.

**Comment by fabianapsimoes** [comment]
@BandonRandon suggested something like a "Cancel and Remove" option, in addition to the regular "Cancel", which only disabled auto-renewal:

![screenshot_07-01-2016-15 05 59](https://cloud.githubusercontent.com/assets/150348/12185534/45df9774-b550-11e5-968b-b8efe610ad9d.png)

In https://github.com/Automattic/wp-calypso/issues/241, we implemented a Remove option for expired domains already. It's presented in the Manage Purchase screen though, instead of in Confirm Cancellation.

@mikeshelton1503 I think this is something we need to look into soon. There are two cases we need to design, especially in terms of messaging:

- Removing a domain (right now, it's only possible to do this to expired domain).
- Removing a plan or legacy upgrade.

For domains, since "Cancel" means disabling auto-renewal, I think "Remove" should be the equivalent of not only removing the subscription but also cancelling the registration. That's something we need to take into consideration when coming up with copy for this feature.

**Comment by BandonRandon** [comment]
**For regular cancellations**, if the cancel button opened up a window asking the user if they wanted to cancel or cancel and remove we could also explain the ramifications of both in that window and let the user choose. 

**For the delete flow**, I do think a checkbox would be the best thing to do. We could write text that says "cancel all upgrades, I understand this means I may not be able to use example.com again elsewhere" 

Something else that @supernovia pointed out yesterday is that if no funds were exchanged (ie the upgrade was added by an Automatticain, using credits, or payment information is not on file) the cancellation screen does not show.

**Comment by supernovia** [comment]
If the user's payment details have expired, they get an interesting issue: they aren't able to find a cancel option unless they enter new payment details.

**Comment by eurello** [comment]
I had a user on chat today with the problem @supernovia mentions. They'd received an email warning them that their domain would automatically renew in two days. They logged in to turn that off, but there was no option to do so. Their card was actually expired, so the problem here is two-fold: 

1. They got an email telling them they'd be automatically renewed when they wouldn't be; and 
2. There was nothing in the My Purchases UI to indicate that the automatic renewal was already canceled due to their expired card.

**Comment by mikeshelton1503** [comment]
Ok there are two issues here to solve (I've moved others to new issues)

1) **Users are confused about what "Cancel [Product Name]" does.** It's phrased as a definitive action therefore users could be afraid to click it. If they did click it they would find the information on the cancel page that would explain to them what "Cancel" does.

To fix that issue lets change "Cancel [Product Name]" to "Cancellation and Auto-renewal Info".

2) **Users with unsubscribed purchases have no way to remove their purchase.**

Let's add a "Remove [product name]" link to the unsubscribed state (at the bottom where the action links go). Upon clicking, we need to display a modal to confirm the action. The modal should look like this:

![image](https://cloud.githubusercontent.com/assets/12596797/12253439/a1d6b746-b8ad-11e5-8db0-d4bedda6463a.png)

> Remove [Product Name]
> Are you sure you want to remove WordPress.com Business from myawesomesite.wordpress.com? By removing, you will not be able to reuse it again without purchasing a new subscription.

cc @breezyskies 
------------------------------------------
As far as the other issues raised:

For the delete flow concerns adding the remove link will now make it possible for a user to delete their site albeit not a straightforward process. I created a separate issue for that one: #2300

> If the user's payment details have expired, they get an interesting issue: they aren't able to find a cancel option unless they enter new payment details.

@supernovia This is correct. In the case of an expired payment method, a purchase displays in the "unsubscribed active state", it's already in effect cancelled. We will now be adding a "Remove [product name]" link so the user will have two options in that case: Renew (providing new payment info in doing so) or Remove from their site.

> I had a user on chat today with the problem @supernovia mentions. They'd received an email warning them that their domain would automatically renew in two days. They logged in to turn that off, but there was no option to do so. Their card was actually expired

That sounds like something went wrong. I've created #2301 to address that issue since it's outside the scope of this issue.

**Comment by fabianapsimoes** [comment]
> 2) Users with unsubscribed purchases have no way to remove their purchase.
> Let's add a "Remove [product name]" link to the unsubscribed state (at the bottom where the action links go). Upon clicking, we need to display a modal to confirm the action. The modal should look like this:

@mikeshelton1503 We probably need a different copy for domains, making it clear that removing the domain will cancel the registration, and they might not be able to get the domain back again. That's one point where the remove / cancel terminology becomes really confusing (cc @aisajib).

For example, within the refund window, "Cancel" means we'll remove the subscription, cancel the registration, and refund the payment. Outside the refund window, "Cancel" means we'll disable automatic renewal, and then we have "Remove" which means we'll remove the subscription and cancel the registration. So, with domains, depending on the refund window, "Cancel" has different meanings and implications.

**Comment by aisajib** [comment]
Continuing on the previous discussion, is it no longer possible for the user to keep the domain but cancel the automatic renewal within the refund period? It sounds like something some users want as I've talked to a few people who were wondering how to do this.

**Comment by mikeshelton1503** [comment]
> We probably need a different copy for domains, making it clear that removing the domain will cancel the registration, and they might not be able to get the domain back again.

Good point. Here you go:

> Remove [domain name]
> Are you sure you want to remove myawesomesite.com from your account? By removing, you are canceling the domain's registration and forfeiting ownership of the domain.

cc @wensco @breezyskies for copy review

**Comment by mikeshelton1503** [comment]
> "Cancel" means we'll remove the subscription, cancel the registration, and refund the payment. Outside the refund window, "Cancel" means we'll disable automatic renewal, and then we have "Remove" which means we'll remove the subscription and cancel the registration. So, with domains, depending on the refund window, "Cancel" has different meanings and implications.

True but that's why the label change for the cancel link should help. The cancel page can explain what's going to happen much better than a 3-4 word link can.

> is it no longer possible for the user to keep the domain but cancel the automatic renewal within the refund period?

@aisajib That's correct, it's no longer possible. So far you are the first to mention this as an issue so any user feedback you can share regarding this would be very helpful!

**Comment by BandonRandon** [comment]
I would encourage us to try to simplify the message we display as much as possible. This will help with translations, as well as making things easier to understand for the users. Instead of:
> Remove [domain name]
Are you sure you want to remove myawesomesite.com from your account? By removing, you are canceling the domain's registration and forfeiting ownership of the domain.

How about:
> Remove [domain name]
This will remove myawesomesite.com from your account. By removing, you are canceling the domain registration. This may stop you from using it again, even with another service. Continue? 

cc: @breezyskies @wensco ^

@aisajib To give more details there are currently the following status' for domains:
1) Active (auto-renew on)
2) Cancelled (will not be auto-renewed but not removed from account until expiration)
3) Cancelled, within refund window (cancelled and removed)

I do think some user examples would be helpful as it will help us as we clear up the messaging around this.

**Comment by mikeshelton1503** [comment]
Thanks @BandonRandon! I'm ok with your copy revisions.

**Comment by breezyskies** [comment]
> Remove [domain name]
> This will remove myawesomesite.com from your account. By removing, you are canceling the domain registration. This may stop you from using it again, even with another service. Continue?

:+1: Copy looks good. (The "Continue?" might not even be necessary with the right button CTAs.)

**Comment by wensco** [comment]
>within the refund window, "Cancel" means we'll remove the subscription, cancel the registration, and refund the payment. Outside the refund window, "Cancel" means we'll disable automatic renewal, and then we have "Remove" which means we'll remove the subscription and cancel the registration. So, with domains, depending on the refund window, "Cancel" has different meanings and implications.

I haven't worked with this flow very much so I have somewhat fresh eyes. To me, this is confusing. We're using one word (cancel) to describe two very different sets of actions:
- cancel = disable auto-renew and let me use the domain until it expires, or until I renew it
- cancel = refund me, cancel the registration, and remove the domain from my account (possibly giving up the domain permanently)

I'm a little late to the party on this one, but it feels like we should have a standard set of clear terms that mean distinct actions/states. 

Maybe something like:
- Unsubscribe: disables automatic renewal, but leaves the upgrade subscription intact and functioning until it expires (or for domains, past expiration to cover grace period/redemption renewals). This would address the issue that @aisajib mentioned where users can't disable automatic renewal for domains within the refund window.
- Cancel: removes the subscriptions and cancels the domain registration; refunds the purchase if canceled within the refund window
- Remove: removes the subscriptions for expired domains

Sorry for the unsolicited commentary above :). If we're sticking with the current process/labels, I like @BandonRandon's copy suggestion for removals.

**Comment by drewblaisdell** [comment]
@mikeshelton1503 What is the rationale for using a modal instead of a confirmation screen (like when we cancel private registration)?

The latter makes it possible to link to the cancel page specifically (like from our emails). Also, someone please correct me if I'm wrong, but I think we've been trying to avoid using modals or `<Dialog />` in general in Calypso. @mtias should know the answer to that.

**Comment by aisajib** [comment]
@mikeshelton1503 

>That's correct, it's no longer possible. So far you are the first to mention this as an issue so any user >feedback you can share regarding this would be very helpful!

I'll keep an eye. I recently worked on quite a few tickets where users weren't comfortable leaving the auto-renewal on but didn't want to cancel the domain either. They were within the refund period. I think it'd be a neat idea to have that option.

**Comment by mikeshelton1503** [comment]
> What is the rationale for using a modal instead of a confirmation screen (like when we cancel private registration)?

@drewblaisdell The reasoning for a modal in this case is that the messaging is simply for confirmation. It is short and serves only one purpose, which is to prevent users from accidentally removing a purchase by mistakenly clicking on the link. Also, there is only one action. When the message is so short and the purpose so focused, adding a whole new page doesn't achieve any purpose, it can actually make the experience more cumbersome.

> Also, someone please correct me if I'm wrong, but I think we've been trying to avoid using modals or <Dialog /> in general in Calypso. 

My understanding is that we are not avoiding them in Calypso but we are limiting their use, primarily to confirmation messages like this. Modals can easily be abused by placing too much info and too many actions in them. Those are the cases where we are trying to avoid them. For example, one modal that we need to replace at some point is the "Why do I need Privacy Protection" in domain checkout (https://cloudup.com/cZa1NsTFcfb). There is too much going on in that modal.

> The latter makes it possible to link to the cancel page specifically (like from our emails)

This is a fair point but were talking specifically about the Remove Purchase link so I don't think we have or will have reasons to need to link directly to that from an email. It's more of a utility action.

**Comment by mikeshelton1503** [comment]
@wensco I agree the use of Cancel can cause confusion. We need to review all instances of the use of "Cancel". Since this is a separate issue of removing purchases I moved it to: #2392
