### ISSUE TITLE
Reader: clicking < SITE TITLE on mobile view shows calypso sidebar

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#14079]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage **on mobile width**
2. Choose a site
3. On the site's Reader page click **< TITLE OF YOUR SITE**

#### What I expected

Not sure what this should do and how it's different from < BACK !?!

#### What happened instead

Shows Calypso sidebar

#### Browser / OS version

Mobile width browsers

#### Screenshot / Video

![site title in reader mobile](https://cloud.githubusercontent.com/assets/128826/26089422/eeee6d88-3a40-11e7-804a-5725b2d34077.gif)

**Comment by blowery** [comment]
That's semi-standard calypso behavior on mobile I think? Agreed, it's super weird. Maybe a different heading would help? Sidebar or a hamburger or something?

cc @jancavan @fraying

**Comment by jancavan** [comment]
I've seen this around Calypso and yes, it's very weird. The Back arrow label is the very page you're on.

The sidebar heading says "Streams". We could use that as it's essentially where you're going back to:

![screenshot 2017-05-18 12 47 36](https://cloud.githubusercontent.com/assets/4924246/26220621/30a38294-3bc8-11e7-901b-a4e886470775.png)

![screenshot 2017-05-18 12 48 36](https://cloud.githubusercontent.com/assets/4924246/26220658/530e8be4-3bc8-11e7-8c49-391c1a6554ed.png)

The hamburger icon feels to me like it's the menu for the entire site. Primarily because of its location:
![screenshot 2017-05-18 12 53 53](https://cloud.githubusercontent.com/assets/4924246/26220844/2db871b0-3bc9-11e7-83af-22b22eed7ad2.png)

**Comment by fraying** [comment]
Yeah, this is standard Calypso behavior – used in a lot of places – and yeah I think it's confusing, too.

Another solution: If we centered the title, then it would stop being confusing. It looks like it's describing the back link when it is, in fact, the title of the page you're on.

**Comment by fraying** [comment]
@jancavan Could you post that hamburger idea as a separate issue? I think that's a great idea.

**Comment by jancavan** [comment]
> We could also just remove the text entirely.

I think some text is needed when you're in the site stream because there are 2 back buttons: one goes back to the main Reader menu, the other goes back to the previous page.

![screenshot 2017-06-01 10 29 20](https://cloud.githubusercontent.com/assets/4924246/26692429/80ccfadc-46b5-11e7-80ad-bfafd206b1a9.png)
