### ISSUE TITLE
Login: inconsistent use of Logging In notice

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#14155]
Steps to reproduce:

- enable 2FA via the authenticator app for your account
- log in to that same account in the WordPress mobile app
- visit `/login` and enter your username and password
- you'll receive a push notification in your phone, through the WordPress mobile app
- click Approve in that notification and keep an eye on the login page
- note that a green notice saying "Logging In" will appear on the top right

That's the only case where that green notice is displayed. It isn't used if the user logs in through any of the other methods. Do we want to keep that notice? If so, should we add it to the other login methods as well?

cc @danhauk @breezyskies

**Comment by breezyskies** [comment]
I think this notice is only shown in this case because it's an attempt to add user feedback between the two devices so the user knows that what they did worked (this isn't really useful or necessary in the other cases). Other than maybe improving the copy to make it more clear what happened, I would opt to keep it for this specific case. cc: @ranh

**Comment by ranh** [comment]
I agree that using a notice only for this particular case is a bit odd. In other cases we also had an interstitial screen for showing notices related to signup. 

We can make it more relevant if we say:

> Approved, logging in.

**Comment by fabianapsimoes** [comment]
With the changes introduced in #14659, this notice is now gone so closing this issue.
