### ISSUE TITLE
Reader Manage Following: when following 0 sites, messaging is confusing

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#14189]
When you're not following any sites, this is the message you see in Manage Following:

<img width="794" alt="screen shot 2017-05-17 at 20 48 02" src="https://cloud.githubusercontent.com/assets/17325/26170640/6b8cdbfc-3b42-11e7-9086-e4aadd93acf7.png">

**Comment by jancavan** [comment]
Is this an edge case @bluefuton when a user decides to unfollow everything (since we auto-follow them to the Big 5)?

In any case, I think we can just remove these as they aren't useful if you don't follow anything.

How about creating a better empty state, something like:

![screenshot-2017-05-17-14 20 24](https://cloud.githubusercontent.com/assets/4924246/26177375/3c24d8a8-3b0e-11e7-96cd-aa1ea4d6514c.png)

**Comment by bluefuton** [comment]
Looks good to me @jancavan!

**Comment by bluefuton** [comment]
I think it might be strange to send people off to Search when they can search right on the page, so I'll say "search above" and just include the Discover button.
