### ISSUE TITLE
Reader Following Manage: recommendation title fades late

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#14219]
This title feels a bit close to the follow button:

<img width="381" alt="screen shot 2017-05-18 at 14 29 23" src="https://cloud.githubusercontent.com/assets/17325/26202124/7e6e6120-3bd6-11e7-92ee-2249581c3299.png">

Can we have it fade a touch earlier @jancavan?

**Comment by jancavan** [comment]
I'm unable to repro this:
![screenshot 2017-05-18 13 26 10](https://cloud.githubusercontent.com/assets/4924246/26222098/97bd0aa4-3bcd-11e7-957f-8e4037fec4f4.png)

Do you know if that screenshot is from this branch https://github.com/Automattic/wp-calypso/pull/14192 @bluefuton?

That was the PR that broke the alignment, but it has been fixed in the same PR.

**Comment by bluefuton** [comment]
I think your theory is right @jancavan! Looks good to me now. I'll close this one.

<img width="361" alt="screen shot 2017-05-19 at 10 38 51" src="https://cloud.githubusercontent.com/assets/17325/26239934/6e44e19e-3c7f-11e7-8982-5d18b5c139f3.png">
