### ISSUE TITLE
Site Settings: Discussion > Avatars settings are missing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#14240]
Should Avatars settings be added to Calypso?

Steps to reproduce:

1. Go to WP Admin > Settings > Discussion.
1. Scroll until you see the Avatars section.
1. Look for those same settings in https://wordpress.com/ > My Sites > Settings.

<strong>Result:</strong> cannot find Avatars settings in Calypso.

![screen shot 2017-05-18 at thu may 18 2 36 40 pm](https://cloud.githubusercontent.com/assets/1119271/26222525/892356e2-3bd7-11e7-9070-ec320b2b0111.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/options-discussion.php using Firefox 53.0.2 on Mac OS X 10.12.4 on production.</sup>

Full page screenshot:

<img alt="screen shot 2017-05-18 at 14 36 13-fullpage" src="https://cloud.githubusercontent.com/assets/1119271/26222574/c357dfd6-3bd7-11e7-9fa2-fcb903a62e7c.png" width="200" />
<sup>Seen at https://design5279.wordpress.com/wp-admin/options-discussion.php using Firefox 53.0.2 on Mac OS X 10.12.4 on production.</sup>

/hat tip @kathrynwp for the report at p1495138967458708-slack-triage

Related support page: https://en.support.wordpress.com/settings/discussion-settings/#avatars

**Comment by lancewillett** [comment]
I'd like to remove this wp-admin setting completely, and not worry about porting to Calypso.

Let's choose the best-looking avatar design. I find this choice to be unnecessary.

**Comment by lancewillett** [comment]
We're going to remove the following settings from wp-admin and not build them into Calypso.

- Avatar settings — just use a smart default.
- Comment Form prompt — use a smart default.

**Comment by lsinger** [comment]
How shall we choose a smart default? In Link we like Identicon because they're discernible and feel inclusive.

**Comment by lancewillett** [comment]
Cancel on the Avatar settings — that comes from core WordPress and isn't easily hideable right now.

Let's just hide the Comment Form prompt for now, see D10299-code.

**Comment by lancewillett** [comment]
Re-opening: we still need to do one more step, hide the setting for the default avatars in WP Admin.

**Comment by mattsherman** [comment]
@lancewillett How shall we handle existing sites that have Default Avatar set to something different than our new default (Identicon)? I propose that, in order to avoid confusion, we also update WordPress.com to force this setting to always be Identicon for all sites. Note though, that this will introduce a change in the look of some customers' web sites.

Alternatively, we could keep the currently set value, but that would be confusing from a customer and support standpoint, as there would be no place in the UI (either wp-admin or Calypso) to ever change the setting.

**Comment by lancewillett** [comment]
Hi @mattsherman — I prefer option A, "Update WordPress.com to force this setting to always be Identicon for all sites."

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

It appears that this issue will no longer be relevant as work on the nav bar unification project progresses and so this issue is a candidate for closure with label `Closed - Won't Fix`.

If work is scoped and tabled for a milestone, please feel free to re-open this bug.
