### ISSUE TITLE
Posts: limit the draft count by user capability (wp-admin parity)

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#14243]
The post_counts API endpoint returning a count for drafts for all users even if I am logged in as an Author or Contributor role and can only see my own drafts.

Steps to reproduce:

1. Start with a WordPress.com blog with saved drafts made with an Administrator or Editor user.
1. Log out and log back in to the same blog as an Author or Contributor user.
1. Go to My Sites > Blog Posts > Drafts > Everyone.
1. Check to see if the draft count is shown for all users or the logged-in user.

<strong>Result:</strong> the draft count is shown for all users instead of what the logged-in user has rights to see as expected.

![screen shot 2017-05-18 at thu may 18 5 07 39 pm](https://cloud.githubusercontent.com/assets/1119271/26226984/c6579f5e-3bec-11e7-9689-1b2d03d0e380.png)
<sup>Seen at https://wordpress.com/posts/drafts/5276229 using Firefox 53.0.2 on Mac OS X 10.12.4 logged in as design5279c (a contributor on the blog).</sup>

/hat tip @timmyc for the original report at https://github.com/Automattic/wp-calypso/issues/1231#issuecomment-267689602

**Comment by designsimply** [comment]
Note that this is different than the wp-admin experience where a logged-in contributor can see (but cannot edit) everyone's drafts. Here is a screenshot for comparison:

![screen shot 2017-05-29 at mon may 29 5 17 56 pm](https://cloud.githubusercontent.com/assets/1119271/26563688/0244275e-4493-11e7-88f6-9a118f082ed9.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/edit.php?post_status=draft&post_type=post using Firefox 53.0.3 on Mac OS X 10.12.5 logged in as design5279c (a contributor on the blog).</sup>

**Comment by lsinger** [comment]
So the count is correct, but the fact that one can't see others' drafts is the issue with Calypso?

**Comment by bsessions85** [comment]
Yes, since we're showing a number of drafts, we should let them see the drafts, like wp-admin does.  Confirmed still happening.

**Comment by designsimply** [comment]
<blockquote>So the count is correct, but the fact that one can't see others' drafts is the issue with Calypso?</blockquote>

Well, if the intended behavior is that Contributors can only see their own drafts, then the count is wrong for them. You could either let them see but not interact with others' drafts (like wp-admin) or you could update the count for them to correctly reflect the number of drafts they can see.

**Comment by donpark** [comment]
What's filtering out posts is `user_can_view_post` but root cause is that this is another API endpoint design flaw, specifically lack of `list` context.

1. WPCOM API supports only two contexts: `display` and `edit`. Adding 'list' will touch a lot of code.
2. Calypso depends on content being included in posts listed because _posts in Redux state are shared by all components that query lists of posts of any type. For example, the SEO preview of a post uses the content to create excerpts or find the first image or other media in the post content_.

Assuming wp-admin parity is the goal, actionable options are:

1. Do nothing.
2. Add 'list' context and pull only what's only needed. Size of the task is not small to say the least.
3. Change wp-admin to behave the same as Calypso since post title can be just as sensitive as post content.

^^ @lancewillett

**Comment by lancewillett** [comment]
Thanks for investigating this, @donpark. I don't think it's worth all the effort for the `list` context unless we can imagine lots of other contexts where it'd be useful. CC @jsnajdr 

Yes, wp-admin parity is the goal. Registered users should be able to view, but not edit, other users' posts.

I suggest we do nothing for now, and re-open this issue if we receive customer complaints on it.
