### ISSUE TITLE
Reader: Re-adding a feed leaves you stuck on the loading placeholder

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14281]
### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage
2. Add a feed you're already following

### What happened
It's not able to determine whether you're already following that site (follow button is still blue):
![screenshot 2017-05-19 08 43 41](https://cloud.githubusercontent.com/assets/4924246/26255701/4c432e4e-3c6f-11e7-9c36-f4f5998dd908.png)

Once you hit follow, the loading placeholders are added to the very top of the list and it's just stuck there...
![screenshot 2017-05-19 08 44 07](https://cloud.githubusercontent.com/assets/4924246/26255733/780faf7a-3c6f-11e7-849e-eb65a26f8823.png)

... even if you clear the search:
![screenshot 2017-05-19 08 45 22](https://cloud.githubusercontent.com/assets/4924246/26255749/88e12536-3c6f-11e7-93e6-73cf128875a7.png)

If you add a new site, this site gets added after the loading placeholders:
![screenshot 2017-05-19 08 46 53](https://cloud.githubusercontent.com/assets/4924246/26255842/c6da82e2-3c6f-11e7-8714-d4fcde5f25be.png)

**Comment by samouri** [comment]
Strange. its working in some cases and broken in others:

working 
- daringfireball.net

broken
- jancavan.com

It'll probably be a fix in the reducer. I'll investigate

**Comment by bluefuton** [comment]
Looks like it's failing to pick up a feed ID or blog ID when this happens:

<img width="658" alt="screen shot 2017-05-22 at 14 37 50" src="https://cloud.githubusercontent.com/assets/17325/26309172/4afbb634-3efc-11e7-8d63-f10cf4355ecc.png">

**Comment by bluefuton** [comment]
I think this is happening when there's a discrepancy between the feed URL in Feedbag, and the one the user has entered. Jan's site has two entries:

<img width="238" alt="screen shot 2017-05-22 at 15 52 33" src="https://cloud.githubusercontent.com/assets/17325/26312108/e0fe85bc-3f06-11e7-962d-51c955672c59.png">

When we hit read/feed looking for `http://jancavan.com', we don't get anything back.

**Comment by samouri** [comment]
I'm not sure how yet, but I believe this issue may be due to a stale redux cache.  clearing IndexedDB removed this issue entirely for me.

**Comment by samouri** [comment]
Scratch what I said earlier. I can repro it even after a cache clear.

Heres what I think the issue is:
1. One requests to follow `jancavan.com`
2. api responds with:
```json
{
  "already_subscribed": true,
  "subscribed": true
}
```

What we would like the reducer to be able to do in this case is to then remove the new entry in the case of `already_subscribed`. It then also needs to realize that `jancavan.com` is an alias for a different feed_URL so that it can show the follow button status properly.  We dealt with a variant of this situation recently for when someone types in an external rss feed and the actual feed url is different than what was typed in. That means the api response feed_URL was different than the initially assumed one.  

We solved this in the follows reducer within `READER_FOLLOW` case by realizing when recognizing when actualFeedUrl is different and then changing its key + adding in a list of url aliases.

A clean way forward could be to simply add the `feed_URL` in to the response, and things should just work without any further changes.

**Comment by samouri** [comment]
@bluefuton, you were right about the feedId/blogId being missing! The data-layer gets nothing it considers to be part of the sub object from the api response except for the url in the initial request payload + the fact that its subbed.  

It then dumbly forwards that to the reducers even though its missing essential data.  https://github.com/Automattic/wp-calypso/issues/14281#issuecomment-303237738 should fix it though.

> I think this is happening when there's a discrepancy between the feed URL in Feedbag, and the one the user has entered.

nailed it!  another condition is that the user has to already be following it.  For the case where the user doesn't follow it yet we've already solved the issue :)

> Jan's site has two entries:

not sure how this relates! I don't think is mergeable either because they are both canonical right?

**Comment by bluefuton** [comment]
The API patch D5693 should help a bit. It should ensure a `subscription` object gets handed back (even when `already_subscribed`) so the data layer can compare the request and response URLs.

**Comment by samouri** [comment]
Isn't the whole problem solved @bluefuton? whats left

**Comment by bluefuton** [comment]
👍 The API patch solved the placeholder issue. There's room for some nicer feedback for the user or fuzzy URL matching like #14369, but I reckon the original problem is fixed.

**Comment by jancavan** [comment]
I'm not seeing the placeholder issue anymore, but it's displaying the "no sites" error message as well as the Follow button? @samouri @bluefuton 

![screenshot 2017-05-24 12 54 40](https://cloud.githubusercontent.com/assets/4924246/26422817/2b4aaf5e-4080-11e7-9560-89f4629ab05f.png)

**Comment by samouri** [comment]
its an edge case one layer deeper :)

It happens when a user:
- performs a site search
- there are no search results
- we've deduced it actually exists because they already follow it

what should we display?

**Comment by jancavan** [comment]
Oh I see, I know I suggested it here: https://github.com/Automattic/wp-calypso/pull/14013#issuecomment-301613399, but my expectation was that once we already know this site exists, we no longer display the error message.
