### ISSUE TITLE
Components: Header Cake: layout issues when Back is a longer string

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#143]
This is how the Back link in `HeaderCake` looks in Swedish, in smaller screens (320px wide, in the screenshot):

![image](https://cloud.githubusercontent.com/assets/7233112/11254268/b3af4ef8-8e0d-11e5-9151-242c6e4e582d.png)

**Comment by adambbecker** [comment]
Okay, so after investigating this a bit, it seems we have three choices for a potential solutions:

## Options

#### 1. Leave as is

![screen shot 2015-12-03 at 2 49 09 pm](https://cloud.githubusercontent.com/assets/1427136/11571990/0d78343e-99cd-11e5-812d-3f03f2a2e320.png)

The reason I'm including this is because currently the header cake title as well as the "back" text will always stay fully visible and the title will remain centered. We could also align the title to be in the middle of the card:

![screen shot 2015-12-03 at 2 50 29 pm](https://cloud.githubusercontent.com/assets/1427136/11572035/4303a2fa-99cd-11e5-8b95-6e4375da9551.png)

#### 2. Ellipsis "back" text

![screen shot 2015-12-03 at 2 52 51 pm](https://cloud.githubusercontent.com/assets/1427136/11572085/907b7774-99cd-11e5-9f6d-7988ec158e44.png)

This keeps the title centered, but ellipsis's the back text if it starts to overflow 1/3 width of the card.

#### 3. Ellipsis title

![screen shot 2015-12-03 at 2 42 35 pm](https://cloud.githubusercontent.com/assets/1427136/11572213/1b204986-99ce-11e5-9410-4e4812b11b1f.png)

This option makes sure all the "back" text remains visible and not wrapping, then ellipsis's the title within the available space. It keeps everything in one line.

It does, however, look a little odd depending on the strings that are used if nothing is needing an ellipsis:

![screen shot 2015-12-03 at 3 27 31 pm](https://cloud.githubusercontent.com/assets/1427136/11573104/84622f0a-99d2-11e5-86dd-2e483a4feae4.png)

#### 4. Align title right & ellipsis

![screen shot 2015-12-03 at 3 20 06 pm](https://cloud.githubusercontent.com/assets/1427136/11572921/95d78632-99d1-11e5-8310-af5575992c43.png)

This option forgoes trying to center the title and just aligns it to the right. The "back" text remains visible inline and the title also ellipsis's if it expands beyond the remaining space.

![screen shot 2015-12-03 at 3 20 55 pm](https://cloud.githubusercontent.com/assets/1427136/11572951/bd08bcb2-99d1-11e5-80ed-0945b82f7eaa.png)

---

## Recommendation

I would probably recommend **option 4** as it retains the "back" text visibility regardless of language, while still be informative as to the title. It also looks pretty decent at large sizes even if the page title is a little too verbose.

![screen shot 2015-12-03 at 3 21 35 pm](https://cloud.githubusercontent.com/assets/1427136/11573006/02c6e9d6-99d2-11e5-9f32-69bee083c030.png)

---

Curious to hear your thoughts around any of the options mentioned above.

/cc @mtias

**Comment by mtias** [comment]
@adambbecker nice breakdown. I think your last proposal makes sense. Originally there were plans to support other items at the right, but I don't think there's any section using that space? (Maybe some of the store pages with the cart, but not sure.)

**Comment by adambbecker** [comment]
@mtias: Great!

I did look through a whole variety of places where this component is being used and they all do not attempt to utilize that space. In the `HeaderCake` component itself, it doesn't actually strictly allow for that place to be used as the right corner element [doesn't have any children](https://github.com/Automattic/wp-calypso/blob/master/client/components/header-cake/index.jsx#L51), but did check that it's usage wasn't attempting to override that fact.

Here are a few examples of the right aligned method in use:

![screen shot 2015-12-10 at 1 18 44 pm](https://cloud.githubusercontent.com/assets/1427136/11724431/102e81c2-9f42-11e5-9872-a7def9a87ec8.png)

![screen shot 2015-12-10 at 1 18 51 pm](https://cloud.githubusercontent.com/assets/1427136/11724435/14511e9a-9f42-11e5-952d-541253d3ffaa.png)

![screen shot 2015-12-10 at 1 21 28 pm](https://cloud.githubusercontent.com/assets/1427136/11724440/18858406-9f42-11e5-8dc2-ea1cc3a1201c.png)

![screen shot 2015-12-10 at 1 22 29 pm](https://cloud.githubusercontent.com/assets/1427136/11724446/1dcc8c34-9f42-11e5-9396-6b36a60b5d41.png)

**Comment by fabianapsimoes** [comment]
@adambbecker looks like this is still an issue. See #3431.

**Comment by hoverduck** [comment]
26May16 Bug Scrub

Closing, looks to be fixed.  Here is the DE layout referenced in #3431 at 320px wide:

<img width="322" alt="screen shot 2016-05-26 at 1 33 58 pm" src="https://cloud.githubusercontent.com/assets/7233112/15584043/a1dd4dd2-2346-11e6-839b-f69664e69055.png">
