### ISSUE TITLE
FoldableCard: Compact version bottom margin inconsistency 

### ISSUE THREAD

**Issue by mladenplavsic** [Automattic/wp-calypso#14310]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design/foldable-card
2. Click on a "This is a compact card" expand icon

#### What I expected
It should either to stay glued to the next element, or to be split

#### What happened instead
It changes distance from next element when it's expanded or closed

#### Browser / OS version
Chrome / Ubuntu 14.04

#### Screenshot / Video
Collapsed
![screenshot from 2017-05-21 21 58 59](https://cloud.githubusercontent.com/assets/1327535/26286979/8f5b7e94-3e71-11e7-9ce3-0628b3aa594f.png)
Expanded
![screenshot from 2017-05-21 21 59 23](https://cloud.githubusercontent.com/assets/1327535/26286981/9422f3ee-3e71-11e7-8cb1-46299d8edfd6.png)

**Comment by designsimply** [comment]
Tested and confirmed using Chrome 58.0.3029.110 on Mac OS X 10.12.4.

**Comment by folletto** [comment]
That's by design: the card is made to separate itself from the others when in a list (see My Sites → Sharing). The space has been introduced to better separate an open card from the context.

I recall it also added space at the top however, that might be a regression.

**Comment by folletto** [comment]
I did a brief review with @drw158 and we came to this way forward:

1. Change the `FoldableCard` component so it adds a space at the top too (unless it's the first item of a list, or alone, should be detectable with adjacency CSS).
2. Since it's a component change, make sure before merging the change that all the existing instances for `FoldableCards` don't acquire weird behaviours.
