### ISSUE TITLE
Store: Warn the user if any required plugins are not up-to-date with the current version

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14347]
i.e. when on `/store` routes, in lieu of the store sidebar and content, we should tell them we can't reach their site and help them in some way to get things going again.

Needs design
cc @kellychoffman 

See also #14348 and #14349 

-----

Updated 4/4/18 by @ryelle – We now automatically install & activate WooCommerce and required plugins, so this issue has been changed to "warn users of outdated versions".

**Comment by jameskoster** [comment]
If there's a Jetpack / WC issue;

![wc-issue](https://cldup.com/Cs_hvdGlOi-3000x3000.png)

**Comment by kellychoffman** [comment]
I just realized that we already have an indicator when a Jetpack connection isn't working. We should probably keep this consistent. 

I tested it out by disconnecting Jetpack from one of my test sites. This is what happened in the sidebar: 

![no-jp](https://user-images.githubusercontent.com/5835847/26842367-8bcdbcba-4aba-11e7-954b-ddd0837881fe.gif)

**Comment by kellychoffman** [comment]
So, I found what actually happens when you have JP issues: 

![vgxwgk9sdh-3000x3000](https://user-images.githubusercontent.com/5835847/26842932-828f40e0-4abc-11e7-8b79-a1bc70daf319.jpeg)

It uses https://wpcalypso.wordpress.com/devdocs/design/empty-content which we should use as well. We could easily re-use this for WC issues as well.

**Comment by jameskoster** [comment]
Agreed, `empty-content` looks good. 

I'm just wondering about our sidebar. Because Store is entirely (?) dependent on both wc and jp, I'm assuming that none of the links in it will work - they'll all lead to an `empty-content` screen/error message. If that's the case I don't think we should display it at all. It would just be a distraction/frustration. 

Maybe keep our top bar so they can get back to the regular site dashboard, where some things that don't rely on wc (and jp to a lesser extent) still work.

![top-bar](https://cldup.com/JUu-D3BKrD-3000x3000.png

**Comment by kellychoffman** [comment]
Yep, that makes sense. We should not display the sidebar in this case. Just the `empty-content` and top bar.

**Comment by justinshreve** [comment]
I'm moving this to the 1.1 milestone. Jetpack should never not be there for Atomic sites so I don't think we need to worry about that just yet. Atomic users going to wp-admin or the plugin screen and removing WooCommerce and then coming back to Store and expecting it to work also feels like something we are okay with for launch. We do need better handling for cases as we expand to more users though -- so that's something we should address in the short term.

**Comment by justinshreve** [comment]
We should also do checks for versions (ala #14347).

**Comment by ryelle** [comment]
@timmyc @justinshreve I've just added #23809 which will fix deactivated/deleted WC plugins - it doesn't detect Jetpack or WC version issues, do we still think that is something we should try to catch?

**Comment by timmyc** [comment]
@ryelle I think the fix you implemented in #23809 is probably sufficient... it seems most of our critical changes for store are shipped via the companion plugins, though a few things there have been dependent upon Woo core updates too.

I suppose if we have some time while things get sorted for the dashboard project we could look into a version check, but I don't think it is critical.

**Comment by timmyc** [comment]
Since Jetpack is a managed install on AT sites - I'm going to go ahead and close this out. I believe our required WC version is quite old now, so that is a bit of a edge case too.
