### ISSUE TITLE
Devdocs: blocks page title is incorrect.

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#14430]
When navigating to https://wpcalypso.wordpress.com/devdocs/blocks

The page title is "Log In", when a user is already logged in

![screen shot 2017-05-24 at 11 40 57 am](https://cloud.githubusercontent.com/assets/1270189/26419950/22bef37c-4076-11e7-964c-3fb59eff60e1.png)

**Comment by tyxla** [comment]
Looks like this is coming from the `<DocumentHead />` in the `<Login />` block. Since blocks are expected to be reusable in different sections, it probably doesn't make much sense to have a `<DocumentHead />` here - instead, we should have it in the main component that wraps the `<Login />` block. 

cc @stephanethomas

**Comment by stephanethomas** [comment]
Good catch @tyxla. I'll fix that.

**Comment by tyxla** [comment]
Thanks!
