### ISSUE TITLE
Editor: Scheduling calendar is hidden on mobile

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#14469]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/ from a mobile device.
2. Write a post.
3. Click on the Schedule button to schedule a post.
4. Part of the calendar will be cut off. You can't scroll to get to the bottom of the calendar.

![screenshot_20170522-183940](https://cloud.githubusercontent.com/assets/426388/26450665/ef3a53be-4158-11e7-83e6-0db80aba3807.png)

**Comment by rachelmcr** [comment]
I tested with the current date picker on mobile and I'm able to scroll to view the full calendar with the current implementation:

![2017-10-04 18 02 57](https://user-images.githubusercontent.com/8658164/31188938-902781ba-a92e-11e7-88fd-2fefbea486e8.png)


However, the post settings sidebar seems to scroll in several sections (rather than scrolling all as a single element) making it hard to tap in the right place to get the scroll working. I think this could use improvement to make it easier for mobile users to scroll to view what they need here.

**Comment by rachelmcr** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/17996

**Comment by alisterscott** [comment]
I can no longer reproduce this issue, the sidebar has been updated a lot since this issue was raised:

![fullsizeoutput_10117](https://user-images.githubusercontent.com/128826/36134277-7173f240-10cf-11e8-9b4a-2a4d59507f01.jpeg)

#bug-scrub #pre-gutenburg-bug-purge
