### ISSUE TITLE
Jetpack Settings: Antispam card looks odd with a Free plan

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#14654]
I've just connected a Jetpack site on a Free plan and went to the Security settings tab, but the Antispam card looks like this:

![](https://cldup.com/YYCIrZ-57f.png)

![](https://cldup.com/-w77WLzNSl.png)

I think this could be confusing to the user. Should we add some kind of message here, or maybe a nudge to upgrade to a paid JP plan?

/cc @oskosk as he worked on the card and @rickybanister @MichaelArestad for ideas

**Comment by oskosk** [comment]
nice catch!. This is probably a bug. Free users are still shown the "your site needs an antispam key" in Jetpack Admin Page. Though I can't reproduce the fact that the input gets disabled as you're showing in the screenshot

**Comment by rickybanister** [comment]
I realize this is unrelated to this specific issue, but in trying to test this I discovered something else—with Akismet deactivated we hide the antispam card in wp-admin entirely.

![image](https://cloud.githubusercontent.com/assets/437258/26686427/d95c3ba4-46ba-11e7-9b3c-99cf79dfb707.png)

If you have the free plan we need to do a couple of things—if they do not have akismet installed it should have a `banner` to upgrade to get spam protection. It should probably show the toggle in a disabled state with the standard label as well. 

I don't think it's enough to simply offer them a place to enter an API key because even if they have a valid key they might not have Akismet installed/activated, and they won't be protected from spam. Ideally we would be able to offer them auto-config from here like the 'set up' button we offer for the backups module. They should likely also be able to manually configure Akismet if it's installed and active and they know how to enter a key. 

We'll need to test this with and without Akismet activated to make sure we catch every case.

**Comment by tyxla** [comment]
Happy to work on a solution for this one @rickybanister, let's just confirm what we should do in all of  the cases:

* Free plan, Akismet installed and activated
* Free plan, Akismet installed but not activated
* Free plan, Akismet not installed
* Free plan, Akismet installed and activated, key stored (probably quite an edge case)
* Paid plan, Akismet installed and activated
* Paid plan, Akismet installed and activated, but no key stored? (probably an edge case)
* Paid plan, Akismet installed but not activated
* Paid plan, Akismet not installed

and figure out of there are any other cases that I'm missing. 

Could you let me know what you'd expect to see in any of the above cases?

If you feel this one requires too much investigation and testing and has unclear bits, we can leave it for when we get to work on v2.

**Comment by tyxla** [comment]
I've opened #16796 to handle the Free plan case. We'll handle the rest of the cases in v2 - I've opened a separate issue for them - #16793.
