### ISSUE TITLE
Video Sharing: Starting from a specific point for Vimeo is not working

### ISSUE THREAD

**Issue by sekanderb** [Automattic/wp-calypso#14725]
#### Steps to reproduce
1. Paste this URL https://vimeo.com/73214621#t=3m13s on a page or post.
2. Publish and check if the video starts from 3 minutes 13 seconds mark.

#### What I expected
The video to start from the mentioned time

#### What happened instead
The video started from the beginning.

#### Browser / OS version
Chrome - Version 58.0.3029.110 (64-bit)
macOS Sierra 10.12.5

/hat tip @designsimply and @NujabesSoul for helping confirm the bug.

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided on Chrome 58.0.3029.110 on Mac OS X 10.12.5.

I also noticed that the Vimeo support page at https://en.support.wordpress.com/videos/vimeo/ does not mention the ability to start a video from a specific point in time and so I am not sure whether or not this is an expected behavior. Need a 2nd opinion on this one.

**Comment by sekanderb** [comment]
I guess this is a feature that we did not implement.

**Comment by designsimply** [comment]
Decided to switch this one from `[Type] Bug` to `[Type] Enhancement` since it's not clear whether time-specific start was ever supported in the past for Vimeo video embeds. That means it's lower priority and will be reviewed next time video embeds are worked on at some point in the future. I'd consider it a nice-to-have feature request. 🙂

Thank you for reporting the issue!

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Moved to https://github.com/WordPress/gutenberg/issues/5017
