### ISSUE TITLE
Impossible to navigate the login screen using Tab

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#14744]
The title says it all ;) Apparently, you can only navigate the first two input fields, but the `Keep me logged in` check and the login button itself are out of bounds, apparently. Probably needs some `tabindex` magic.
![ajdreq5wue](https://cloud.githubusercontent.com/assets/3392497/26752943/b04a0d2a-485b-11e7-900a-15185b8fd065.gif)

**Comment by danhauk** [comment]
I remember coming across this issue in [delphin](https://github.com/Automattic/delphin/) and it turns out Safari disables tab navigation by default. Chrome and Firefox don't have this problem, and you can enable tab navigation in Safari in `Preferences > Advanced`. This isn't really something we can fix.

See [this issue](https://github.com/Automattic/delphin/issues/873) for more. Props to @hafizrahman for figuring this out.

**Comment by klimeryk** [comment]
Whoa, that's a major WTF 🤔Thanks for the info, @danhauk - I'll close this issue then, since it's not something we can fix :/
