### ISSUE TITLE
Publicize: SEO Description overrides post excerpt during Publicize

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#14792]
This issue was first raised by @formosattic in Slack.

#### Steps to reproduce
1. Create a new post on a site with connected Publicize connections (Facebook, Twitter)
2. Set a post excerpt.
3. Set a SEO Description.
4. Published/publicized post will utilize the SEO description for the `og:description`.

#### What I expected
Since all plans have access to the post excerpt, it makes sense to stick with the custom excerpt as the `og:description` across the board, reserving the SEO Description for the `meta name="description"` tag only. Users who have mastered Publicize on a lower plan should not need to alter their workflow for a basic function of Calypso.

#### Examples
Oldest post: SEO Description + Post Excerpt
Middle post: SEO Description + Post Excerpt + Publicize Excerpt
Newest post: Post Excerpt only

![screen shot 2017-06-06 at 12 21 36 am](https://cloud.githubusercontent.com/assets/8002138/26818152/70ee9732-4a4e-11e7-88b9-d1ca201e42e2.png)
![screen shot 2017-06-06 at 12 21 10 am](https://cloud.githubusercontent.com/assets/8002138/26818153/70f00a40-4a4e-11e7-863f-a298a7e752a1.png)

#user-report

**Comment by AashikP** [comment]
Also reported in 2352339-zen

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
