### ISSUE TITLE
Purchases: failure to remove a domain is not applied to UI

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#14914]
#### Steps to reproduce
You'll need to simulate a failed removal by modifying the Delete Purchase endpoint reply.

1. Starting at URL: /me/purchases
2. Click on a domain registration
3. Click on "Remove xxx.yyy" 
4. The return value would be an error such as 
```{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"server_error","message":"Unable to delete the purchase because of internal error"}}```
5. The UI will show "a confirmation with The domain xxx.yyy was removed from your account."
6. The domain stays in the purchases list

#### What I expected
The error message being displayed on screen

#### What happened instead
A success message appeared

CC @drewblaisdell 

Related: #14913

**Comment by Copons** [comment]
@yoavf I've tried this by adding an early error to the endpoint (literally adding this as the first line in the endpoint callback: `return new WP_Error( 'server_error', 'Unable to delete the purchase because of internal error' );`), and it seems to work as expected:

![mar-08-2018 15-40-32](https://user-images.githubusercontent.com/2070010/37159987-16e6466e-22e7-11e8-81c1-11356e40a97a.gif)

Have I misread the reproduce steps, or can we consider this fixed?

**Comment by yoavf** [comment]
@Copons can't reproduce it either right now, thanks for looking into it!
