### ISSUE TITLE
Login: Propagate user locale to the Google OAuth flow

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#14966]
Raised by @stephanethomas in #14806:

> we should also probably pass a parameter to Google to display the OAuth flow in the language of the user.

This is something that should be fixed on the Login page. Go to http://calypso.localhost:3000/log-in and change locale using Locale Suggestions box. Make sure Google uses locale picked by WordPress.com UI.

**Comment by pento** [comment]
After researching this a bit, it turns out that the Google OAuth flow doesn't allow for setting the language - they prefer to detect it themselves.

Unfortunately, I couldn't find a documented reference for this, just a handful of comments:

https://groups.google.com/forum/#!msg/oauth2-dev/8ClMceHMzBE/sRcgDiqdU4cJ
https://stackoverflow.com/a/36582304/49473

I believe the `hl=en` parameter only works if you're manually calling the OAuth URLs, instead of using the JS library.

**Comment by pento** [comment]
Side note: the easiest way to verify Google's language detection is to add a different language to your browser, set it to your first preference, and click the Google button.
