### ISSUE TITLE
Plugins: Jetpack on WordPress.com sites shows markdown as active even if disabled

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#14995]
#### Steps to reproduce
1. Starting at URL: {site_URL)/wp-admin/options-writing.php
2. Make sure Markdown is disabled and save.
3. Go to https://wordpress.com/plugins/{site_URL}
4. Scroll to the bottom. Markdown shows a green check and says Active.

#### What I expected
That the Jetpack module status would reflect the actual setting on the site. 

Not strictly related, but an additional observation - it feels intuitive to be able to switch the setting on the Jetpack page, but it's not actually possible.

#### Screenshot / Video
![plugins_ _kokkiestrialtestsite_ _wordpress_com](https://user-images.githubusercontent.com/11873759/27029389-6d721ed4-4f68-11e7-90e7-24cdd5ebea1a.png)

#### Context / Source

#user-report in the public forums: 864059-f

Confirmed on both free and upgraded WordPress.com sites.

**Comment by designsimply** [comment]
<blockquote>Not strictly related, but an additional observation - it feels intuitive to be able to switch the setting on the Jetpack page, but it's not actually possible.</blockquote>

The setting was removed for WordPress.com in general because Markdown isn't fully supported for everyone yet there. See #11510.

**Comment by beaulebens** [comment]
This view is no longer available for WordPress.com sites in this form, so this issue is now redundant.
