### ISSUE TITLE
Security: Add Self XSS Warning to Dev Console

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#15]
Add a warning in the Javascript console similar to this example from www.facebook.com
![image](https://cloud.githubusercontent.com/assets/7233112/11216543/b98d7088-8d19-11e5-98f9-0aafc65e32ee.png)

**Comment by erickstm87** [comment]
Hey I'd like to take this one. It would be my first post. Not too familiar with xss attacks though. Is there a specific portion of the site where this warning would be needed?

**Comment by chrispwns** [comment]
Is this still open? This seems like a relatively easy fix and I'd love to have a chance at it. Assuming it's open would something like the attached image work for you? I went ahead and threw that together really quick just to see how console formatting worked in JS because it interested me.
![self-xss-warning](https://cloud.githubusercontent.com/assets/10478216/20857420/95ae2220-b8f1-11e6-9ea6-3a52b4b5af18.png)
