### ISSUE TITLE
PostShare: update publicize/published endpoint to `v2`

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#15010]
We are still using the v1 endpoint for the ~scheduled~ published actions. let's replace it by the new `v2` endpoint.

![image](https://user-images.githubusercontent.com/77539/27052923-ce9ab1c0-4f91-11e7-8928-b4e17a296600.png)

**Comment by sirbrillig** [comment]
Do you mean for published actions or scheduled actions?

Scheduled actions [should already be using the v2 endpoints](https://github.com/Automattic/wp-calypso/pull/14550/files#diff-ede235b976deba306429659b00c31780R122) but AFAIK there are no v2 endpoints for published actions because there was a technical backend issue about storing those actions.

**Comment by retrofox** [comment]
> there was a technical backend issue about storing those actions.

Let's keep this issue then. So once the backend issue is done we will be able to continue.
