### ISSUE TITLE
Domain Details: state dropdown throws TypeError on `focus`

### ISSUE THREAD

**Issue by hewsut** [Automattic/wp-calypso#15027]
#### Steps to reproduce
1. Start at URL: https://wordpress.com/plans/YOURSITE or https://wordpress.com/start, add a domain to your cart, and begin the checkout process.
2. Set the country to a value that autopopulates State (eg, United States).
3. Fill out all the form except State.
4. Click "Continue to Checkout".

#### What I expected

Autofocusing without error on the State field.

#### What happened instead

The follow error is thrown:

```
domain-details-form.jsx:584 Uncaught TypeError: this.refs[(0 , _kebabCase3.default)(...)].focus is not a function
    at DomainDetailsForm.focusFirstError (domain-details-form.jsx:584)
    at eval (domain-details-form.jsx:284)
    at Controller.eval (index.js:97)
    at Controller.eval (index.js:145)
    at eval (domain-details-form.jsx:374)
    at eval (undocumented.js:603)
    at eval (send-request.js:104)
    at XMLHttpRequest.xhrOnLoad (index.js:177)
    at resolve (index.js:552)
    at onmessage (index.js:515)
```

#### Browser / OS version

Chrome/FF, OSX

#### Screenshot / Video
![screen shot 2017-06-13 at 2 18 31 am](https://user-images.githubusercontent.com/2006764/27068551-ad16dcc0-4fde-11e7-8425-775dfe0d200a.png)

#### Context / Source

Discovered on the heels of #15009 which is admittedly suspicious. I checked out revisions before the merge and saw similar behavior so I _think_ the new code is unrelated. It's late though...so my brain is poor.

My leading theory atm is that the Reduxified nature of the `StateSelect` component is causing issues:` DomainDetailsForm` `focusFirstError`is assuming dumb components when calling `focus`, maybe, and those paradigms crossing is blowing things up. (?)

**Comment by hewsut** [comment]
@aidvu and @obenland, `git`'s telling me you touched https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/components/form/state-select.jsx#L38 and https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/components/form/state-select.jsx#L95 in ye olde past. I'm going to be back from `zzzz` in ~6 hours and plan to hop back on this. Any thoughts or insights welcome if something springs to mind.

**Comment by klimeryk** [comment]
IIRC, the problem is that that field can be two things - a regular `<input>` when the state field is not required (and we don't have a list of states for the given country) or a `<select>` if it is required (compare US vs Poland, for example). I'm guessing the code for focusing does not take that into account and tries to focus the field that is hidden.
Which is weird, because I could have sworn this was fixed already 🤔

**Comment by hewsut** [comment]
Yeah, there's an `if` in `StateSelect` that does that.

>  Which is weird, because I could have sworn this was fixed already 🤔

Possible -- it maybe freshly broken after our merge. I don't think so unless I'm screwing it up because I've checked out some git revisions preceding it.  But maybe I'm screwing that up. I'm going to try to get an independent repro as soon as I can manage.

**Comment by hewsut** [comment]
`{ withRef: true }` + `getWrappedInstance()` sounds right to me on this one. But..  the wrapped instance that is returned doesn't appear to have a `focus` method.  I'm probably overlooking something obv.

**Comment by deBhal** [comment]
> IIRC, the problem is that that field can be two things

We do need to handle both cases, but the problem is the component being wrapped by `connect()` and `localize()`, so when you get the ref, you get the higher order components, and they're both designed to just pass the props down, not pass instance functions up.

>  But.. the instance pulled out of the Redux wrapper doesn't appear to have a focus method.

Yeah, unwrapping the connect() just gets us the `localize()` wrapper, and it doesn't expose the wrapped component instance at all, only it's constructor: https://github.com/Automattic/i18n-calypso/blob/master/lib/localize/index.js#L40

We could theoretically modify `localize()` to let us drill through it, and call something like `this.refs.state.getWrappedInstance().getLocalizedInstance().focus()`, but that's pretty deeply unattractive.

As an aside, there's definitely a race condition with the state on this form too. Sometimes it loads the stored state fine, other times it's blank.

**Comment by hewsut** [comment]
> As an aside, there's definitely a race condition with the state on this form too. Sometimes it loads the stored state fine, other times it's blank.

Any more details there? Are you able to induce each side somehow for repro?  I think we should spin up another issue on that so it doesn't fall off radar and fix.

**Comment by hewsut** [comment]
> As an aside, there's definitely a race condition with the state on this form too. Sometimes it loads the stored state fine, other times it's blank.

See #15279.
