### ISSUE TITLE
Site Results showing Hidden sites

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15087]
I changed my test site to be Hidden ...

<img width="743" alt="screen shot 2017-06-13 at 4 39 14 pm" src="https://user-images.githubusercontent.com/24388/27109316-f39f777e-5056-11e7-9794-64b578f7792d.png">

... but it's still showing in site results.

<img width="948" alt="screen shot 2017-06-13 at 4 40 45 pm" src="https://user-images.githubusercontent.com/24388/27109341-13f0adf4-5057-11e7-894f-ac4e9b3edbe9.png">

cc @gibrown

**Comment by gibrown** [comment]
This was caused by the delay in indexing and the caching of search results.

I've added a check against the DB in the api to exclude sites based on this setting (and things like deleted). When setting the site from hidden to public it will still probably take 5 minutes for it to show up, but it should now disappear immediately when setting it to hidden.
