### ISSUE TITLE
Login: Fix 'empty_two_step_nonce' error when entering an incorrect verification code

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#15082]
Steps to reproduce:

1. Start with a user with 2FA by SMS enabled.
1. Go to https://wpcalypso.wordpress.com/log-in 
1. Enter a username and password.
1. Enter a wrong value in the “Verification code” field.
1. Click Continue.
1. Click Continue again.

**Video:** [36s](https://cloudup.com/cwVdRtJLAx2)

**Result:** if "Continue" is clicked twice, the error changes from "Your session has expired, please go back to the login screen" to “empty_two_step_nonce” and the following console error appears each time "Continue" is clicked:

> Failed to load resource: the server responded with a status of 400 (HTTP/2.0 400)
> https://wordpress.com/wp-login.php?action=two-step-authentication-endpoint

![screen-shot-2017-06-05-at-mon-jun-5-3-51-18-pm](https://user-images.githubusercontent.com/1119271/27107124-ad7bd042-5053-11e7-8cf3-ba98feeaf96e.png)
<sup>Seen at https://wpcalypso.wordpress.com/log-in/sms using Safari 10.1.1 on Mac OS X 10.12.5 logging in as user user907 starting from https://wpcalypso.wordpress.com/log-in</sup>

![screen-shot-2017-06-05-at-mon-jun-5-3-52-48-pm](https://user-images.githubusercontent.com/1119271/27107154-ccc9deb2-5053-11e7-8b12-33af40781ca8.png)
<sup>Seen at https://wpcalypso.wordpress.com/log-in/sms using Safari 10.1.1 on Mac OS X 10.12.5 logging in as user user907 starting from https://wpcalypso.wordpress.com/log-in and clicking “Continue” a 2nd time after seeing a “session expired” error after the first click.</sup>

#manual-testing

**Comment by danhauk** [comment]
I'm also getting an `invalid_two_step_nonce_type` error if I enter a code that's too short. Then a correct length code gives me `empty_two_step_nonce`. This also happens on the authenticator app flow.

Here's how I tested:

1. Start at `/log-in`
2. Enter username and password
3. Click to use authenticator app instead of push notification
4. Enter a code that's too short, for example `123`
5. Enter a correct code

**Result**
After entering a code that's too short, I'm presented with `invalid_two_step_nonce_type` error. Then when I enter a correct code, it changes to `empty_two_step_nonce`

<img width="426" alt="screen shot 2017-06-14 at 15 24 18" src="https://user-images.githubusercontent.com/448298/27150696-336cffb0-5116-11e7-95b2-faa913cf06cb.png">

<img width="421" alt="screen shot 2017-06-14 at 15 21 47" src="https://user-images.githubusercontent.com/448298/27150700-3898ffac-5116-11e7-8644-100d110c237c.png">

**Comment by gziolo** [comment]
Should be fixed with #15290.
