### ISSUE TITLE
ccTLDs: privacy is enabled by default for .ca and .fr individual - reflect in the UI.

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#15093]
ccTLD domains tend to include privacy by default, at no extra charge. We need to reflect appropriately in the UI as our customers tend to value/have questions about that (esp. in EU).

- .ca is private by default for every registration.
- .fr is private by default for all individual registrations, public for organization registrations.
- .de will be private by default for every registration.

**Comment by yoavf** [comment]
Related: #14764

**Comment by cecilerainon** [comment]
I'd like to suggest the following for these domains. Right now, it doesn't show anything above the form, but we could add this box (similar to the one for domains where the user can opt in/out of privacy).

The text basically say that ICANN wants contact details but they shouldn't worry because it won't be publicly available + the learn more link from the regular Privacy box:

<img width="750" alt="capture_d ecran_2017-09-04_a_19_07_45" src="https://user-images.githubusercontent.com/16645645/30034928-f1de4462-91a4-11e7-9024-718050b223e6.png">

**Comment by klimeryk** [comment]
I'm all for this, though we should wait for this test to finish first: https://github.com/Automattic/wp-calypso/pull/17559
cc @aidvu @mikeshelton1503

**Comment by deBhal** [comment]
The notice looks great, just a few extra complications for .FR (as per usual):

- The `registrant_type` field (which effectively controls privacy) is on the extra info `fr-form`, but all the fields affected by the privacy are on the other one, and we don't have any way to go back. We should add a back button, or consider adding that specific control onto the primary form.
- It'd look pretty great toggling an open/closed lock and a red/green highlight.
- We've got different registries for each of these tlds - AFNIC for dotFR and CIRA for dotCA.

**Comment by klimeryk** [comment]
Closing as this has been resolved with various UI changes in the meantime.

<img width="749" alt="Screenshot 2021-02-02 at 13 30 19" src="https://user-images.githubusercontent.com/3392497/106607242-fe217680-655a-11eb-86a2-c40ac7e8c712.png">
