### ISSUE TITLE
WooCommerce: Require WPCOM pressable for Calypso store management

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#15105]
Store setup and management features on calypso should require jetpack installed and connected + running on pressable as a wp.com site

cc @kellychoffman @toddwilkens @pmaiorana @mattyza

**Comment by DanReyLop** [comment]
So, only Business users? No regular Jetpack users? Just want to double-check here, since this was an (unresolved) topic of discussion in our last chat.

PS: I'm totally onboard with this decision. We don't want a horde of Jetpack users from a ton of different hosting providers using this from day 1 :)

**Comment by allendav** [comment]
> So, only Business users? No regular Jetpack users? Just want to double-check here, since this was an (unresolved) topic of discussion in our last chat.

Yes, that is correct. We want to limit this initial rollout and then carefully consider how to incorporate this into other plans.

**Comment by justinshreve** [comment]
Closing this. The link is currently only showing for valid AT sites.
