### ISSUE TITLE
G Suite: Incorrect price in Japanese Yen

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#15192]
As reported by @chaitanyamsv in `p2MSmN-63K-p2`, the price of G Suite in Japanese Yen is incorrect (`https://wordpress.com/domains/manage/email/:site`):
![g-suite-price-in-yen](https://user-images.githubusercontent.com/3392497/27218423-5caa07f6-527e-11e7-87e2-4fd557301a79.png)

The issue is probably in this file: https://github.com/Automattic/wp-calypso/blob/master/client/lib/google-apps/index.js
That's where we try to calculate the formatted price we get from the backend from annual to monthly format. I'm guessing, the regexp there does not handle Yens correctly, or we need a different approach altogether.

**Comment by iamgabrielma** [comment]
The regex seems that just validates that the price has a good formatting right? For reference, the price in JPY would be `5800` annually or `580` monthly, the regex here validates if the price matches:
`5800`
`5.800`
`5,800`

In any of the previous cases, what we see in the image (Y0.50 per user per month or Y5 annually) doesn't fit the price that should be displayed, are we using the wrong parameter when passing `price` maybe ?

For references, trying to change the interface, the settings, the language or the timezone to Japanese / Japan, didn't change my currency in any moment, just the language:
<img width="1121" alt="screen shot 2017-06-24 at 08 17 39" src="https://user-images.githubusercontent.com/3812076/27506539-f920dc2c-58b9-11e7-92fe-d0237b9fc81e.png">

Only the language is affected but not the currency or the USD `50` value (don't mind the $50 per month, just testing the code).

As JPY has `precision : 0`(check  https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/lib/format-currency/index.js ) , maybe the problem comes from this line? As passes the USD price with JPY precision.

`return number % 1 === 0 ? number : numberFormat( number, 2 );`

**Comment by klimeryk** [comment]
The problem is that the formatted price returned by the backend is `¥5,800`. And we treat that comma as if it was a decimal separator. The whole approach here is wrong - we were trying to take the formatted price, "extract" the digits, divide them by 10 (2 months free) to get the per month price. All this to keep the formatting we got from the server. But since we have utils for that on the frontend (the `format-currency` ones you've linked to - thanks!), we should do that properly. I'll try to fix it properly this week - thanks for the extra info, @iamgabrielma!
