### ISSUE TITLE
Free Trials: A/B test free trials

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1520]
We can test two variations in signup here:

- A flow with the site step instead of the domains step where users see free trials.
- A flow with the site step instead of the domains step where users don't see free trials.

**Comment by fabianapsimoes** [comment]
We decided on Slack to do this differently (p1450465780000178-slack-upgrades):

Instead of a 80 / 10 / 10 setup like Drew described, we'll simplify this to 90 / 10 where 90% of users see the main flow and are **not** offered a trial, and 10% see `[themes, site, plans, user]` and are offered a trial.

We believe this setup will tell us as much as the 80 / 10 / 10 would, but without costing us 10% of the domains revenue.

cc @drewblaisdell @p3ob7o @scruffian

**Comment by scruffian** [comment]
The server side component of this is in this patch: `D821-code`

**Comment by scruffian** [comment]
This is blocked by #2181
