### ISSUE TITLE
WooCommerce Products: Update sticky bar action buttons

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#15214]
When adding a new product, the sticky header bar should have the following buttons:
- Preview
- Save & Publish

Calypso doesn't use 'cancel' anywhere _and_ it doesn't fit on mobile view, so instead we'll do what the rest of wp.com does: when you navigate away without saving, you get a "You have unsaved changes. Are you sure you want to leave the page?" dialog. 

Save & Publish button opens a new tab so the user can immediately view the product on the front end without having to click an extra button. 

<img width="477" alt="screen shot 2017-06-16 at 1 34 54 pm" src="https://user-images.githubusercontent.com/5835847/27242127-f19f81aa-5298-11e7-8dba-e66e4374e674.png">

<hr>

Once you've saved and published, you're effectively editing a product. The sticky header should have the following buttons:
- Update
- View
- Delete

<img width="476" alt="screen shot 2017-06-16 at 1 35 07 pm" src="https://user-images.githubusercontent.com/5835847/27242104-d1926e0e-5298-11e7-80cd-76bef1dc3db5.png">

The mobile view should remove the labels on the `borderless-button`s: 

<img width="400" alt="screen shot 2017-06-16 at 1 35 13 pm" src="https://user-images.githubusercontent.com/5835847/27242100-cf0fc460-5298-11e7-832e-e6f0ef07f268.png">

cc @jameskoster @coderkevin

**Comment by coderkevin** [comment]
Addressed in #15598

A few things came up while adding code for this:

1. Previewing a new product as you would view an existing product isn't really possible because it hasn't yet been created on the server. Something like this would require WooCommerce to be able to do what it can't right now. For that reason, I say we axe it for v1 and discuss what to do next.

2. Since it's called "Trash" in wp-admin, and it truly is a "Trash" operation and not delete, I opted to call it "Trash" instead of "Delete" here. Let me know if you feel strongly that it should be "Delete" and we can discuss it.

3. How do you want to remove the labels on the view and trash buttons? Is there a "Calypso" way to do this? Also, I've found that `Save & Publish` is taking up a lot of space in this width as well. Should something be done about that?

4. For wide screen, it's "Delete" then "View", but for narrow screen, it's "View" then "Delete". Which one is right? (I favored "Delete" then "View")

**Comment by kellychoffman** [comment]
> Previewing a new product as you would view an existing product isn't really possible because it hasn't yet been created on the server. Something like this would require WooCommerce to be able to do what it can't right now. For that reason, I say we axe it for v1 and discuss what to do next.

Yep, that makes sense. 

> Since it's called "Trash" in wp-admin, and it truly is a "Trash" operation and not delete, I opted to call it "Trash" instead of "Delete" here. Let me know if you feel strongly that it should be "Delete" and we can discuss it.

We also use Trash in the WP.com post/page editor, so let's go with that. 

> How do you want to remove the labels on the view and trash buttons? Is there a "Calypso" way to do this? Also, I've found that Save & Publish is taking up a lot of space in this width as well. Should something be done about that?

@jameskoster took care of this with css in the PR.

> For wide screen, it's "Delete" then "View", but for narrow screen, it's "View" then "Delete". Which one is right? (I favored "Delete" then "View")

Good catch.
