### ISSUE TITLE
Me: Profile Links "Add" button icon needs more space

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#15322]
#### Steps to reproduce
1. Starting at URL: wordpress.com/me
2. Look at the section labeled "Profile Links"
3. The + icon and "Add" label are too close together

#### Screenshot / Video
<img width="765" alt="screen shot 2017-06-20 at 12 39 57" src="https://user-images.githubusercontent.com/66797/27353493-0bd3ad08-55b9-11e7-91de-6dd841b1dfdd.png">

Tested in Safari and Chrome latest on macOS.

**Comment by TrishAllin** [comment]
@lancewillett - I created a pull request for this (#15322 Fix/me button plus icon spacing #16371) - It uses consistent spacing with other site buttons that have icon and text as well as takes in consideration for that right margin to not be in the buttons that have no text. This is my first open source pull request, so let me know if I can or need to do anything else more or differently. (I tried reading the documentation thoroughly). I saw that this hadn't been dealt with since dannylafrouw's pull request and thought I would put in my own solution, with no intention of stepping on toes. Cheers!
