### ISSUE TITLE
Settings: AMP exit point from Customizer for Jetpack sites is wordpress.com (not Settings > Traffic)

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#15327]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/traffic/example.com (Jetpack site)
2. Under "Accelerated Mobile Pages (AMP)" section click on "Edit the design of your Accelerated Mobile Pages" — which opens Customizer on the Jetpack domain (not within Calypso).
3. Make edits and save (or not, both flows end the same)
4. Click the "X" is top left of Customizer sidebar

#### What I expected
To return to https://wordpress.com/settings/traffic/example.com — which is the behavior with WP.com sites in this same flow.

#### What happened instead
I was returned to https://wordpress.com/ (the Reader).

#### Screenshot / Video
Screencast (GIF, repeating) showing the issue on a test blog.

![jetpack-amp-exit](https://user-images.githubusercontent.com/66797/27357173-05cbcc9e-55c6-11e7-843b-27fa1087c3f6.gif)

#### Context / Source
Found the bug via #manual-testing.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
