### ISSUE TITLE
Reader: Related posts on full post avatars are crowded

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#15320]
https://wordpress.com/read/blogs/16956016/posts/25668

<img width="812" alt="screenshot 2017-06-20 15 04 56" src="https://user-images.githubusercontent.com/14350/27350994-fa5160c8-55c9-11e7-8a46-33b0729d16cc.png">

Avatar seems crowded and the follow button overflows a bit.

**Comment by fraying** [comment]
Oh huh. Could any of the recent Search changes result in this, @jan?

**Comment by fraying** [comment]
Took me a while to replicate, but eventually I saw one:

<img width="774" alt="screen shot 2017-06-20 at 12 42 27 pm" src="https://user-images.githubusercontent.com/24388/27352570-f5fc3d90-55b5-11e7-8465-3d57032f4137.png">

https://wpcalypso.wordpress.com/read/blogs/106585225/posts/543

It only happens when the site title is long.

**Comment by jancavan** [comment]
> Oh huh. Could any of the recent Search changes result in this

No, I don't think so because we didn't touch that part. I think it just wasn't flexible enough to contain a site title that long. Looking into it.
