### ISSUE TITLE
Reader, Editor: Pressing the daily post button Inside a post and pressing back in the editor crashes the editor.

### ISSUE THREAD

**Issue by jorgefilipecosta** [Automattic/wp-calypso#15371]
1-	Go to the reader and open daily post blog  http://worpdress.com/read/feeds/27030
2-	Open a post with daily post button
3-	Press the daily post button
4-	In the editor press back button.
Instead of going back to the reader the application throws errors in the console and the editor stays loading forever.
If we press the daily post button, in the reader outside the post, and in the editor, we press back things work fine.

![2017-06-21_21-04-41](https://user-images.githubusercontent.com/11271197/27404834-64022fcc-56c7-11e7-9875-a3a1dd255e85.gif)

**Comment by fraying** [comment]
Wow, thanks for this great bug report, @jorgefilipecosta! I can replicate this.

Note that everything works fine from the Daily Post site view (https://wordpress.com/read/feeds/27030). The bug happens when going from a Daily Post fullpost page (like https://wordpress.com/read/feeds/27030/posts/1501103061).

Pinging @blowery to see if this is something we can fix in Reader or if we need someone on the Editor team to look into it.

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided with Firefox 54.0 on Mac OS X 10.12.5.

![screen shot 2017-06-21 at wed jun 21 3 33 48 pm](https://user-images.githubusercontent.com/1119271/27407937-9db76334-5697-11e7-8b73-0ed410777ff2.png)

<blockquote>Note that everything works fine from the Daily Post site view (https://wordpress.com/read/feeds/27030). The bug happens when going from a Daily Post fullpost page (like https://wordpress.com/read/feeds/27030/posts/1501103061).</blockquote>

Also confirmed this.

**Comment by blowery** [comment]
Looking into this. From the trace, appears to be an issue in reader full post.

**Comment by fraying** [comment]
🎉

**Comment by jorgefilipecosta** [comment]
Perfect @blowery, thank you for the fix 👍
