### ISSUE TITLE
Checkout: Improve UI when user tries to buy site redirect and starts plan's free trial

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#1538]
Steps to reproduce:
1. Go to http://calypso.localhost:3000/domains/add/site-redirect.
2. Add Site Redirect to the cart.
3. Go to http://calypso.localhost:3000/plans.
4. Select Plan upgrade and start 14 days trial.
5. When you are about to start a trial you're going see this screen:

![screen shot 2015-12-14 at 12 10 05](https://cloud.githubusercontent.com/assets/699132/11779582/6751f39a-a25c-11e5-92a6-3e481aa5f8e3.png)

The same issue happens when you add more than one Domain and/or Domain Mapping to the cart.

/cc @fabianapsimoes @mikeshelton1503

**Comment by breezyskies** [comment]
Note that this could also be an issue for a user who tries to start a trial on a site with an active redirect (as opposed to it being in their cart).

**Comment by breezyskies** [comment]
@mikeshelton1503 and I chatted about this in Slack, some notes:
- We don't think the site redirect in the cart is a issue, as the free trials won't ultimately use the checkout page (see https://github.com/Automattic/wp-calypso/issues/1169). (Also this is pretty edge case that a user would add a site redirect to their cart and then try to get a trial, so low priority.)
- We do think we should warn the user when they have an site redirect already active on their site, letting them know that we're disabling the redirect for the length of their trial (rather than making them go disable it on their own as an extra step). This would show on the [free trial confirmation page](https://github.com/Automattic/wp-calypso/issues/1169): 

<img width="737" alt="c0ehjiixld-3000x3000" src="https://cloud.githubusercontent.com/assets/3011211/11815702/cdd8ccba-a301-11e5-9bb6-8d8384df616e.png">

I would also consider this relatively low priority and can probably wait for v2 of free trials.

**Comment by fabianapsimoes** [comment]
I guess the issue here isn't so much about Site Redirect upgrades, but about the general case where the user has more stuff in their cart than the trial.

For example, with two domains and a trial in the cart, you should be prompted to pay for the second domain. However, when you reach checkout, all you see is the trial confirmation page and no way to enter / select a payment method. If you click the button in the confirmation page, you see this error:

![screenshot-calypso localhost 3000 2015-12-17 13-14-31](https://cloud.githubusercontent.com/assets/1248436/11869521/cc837610-a4c0-11e5-916e-989db13da02b.png)

@gziolo is that the issue you're referring to? I have the impression you and @breezyskies are talking about different things -- and if you're not, what I mention above is another problem we need to take into consideration :)

**Comment by gziolo** [comment]
@fabianapsimoes I was rather thinking about the case you described, but both cases are valid in this context :)

**Comment by breezyskies** [comment]
> I guess the issue here isn't so much about Site Redirect upgrades, but about the general case where the user has more stuff in their cart than the trial.

This is one of the reasons @mikeshelton1503 and I were pushing for a [separate trial confirmation page](https://github.com/Automattic/wp-calypso/issues/1169) that did not include the cart -- the idea being that starting a trial would have zero to do with checkout (or interact with anything else that may or may not be in your cart).

**Comment by fabianapsimoes** [comment]
We'll no longer use the cart for Free Trials, so I'm closing this one.
