### ISSUE TITLE
Social signup: Improve feedback about passwords for social signup users

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#15392]
When users create an account with social signup, the don't create a password. However, we still show the same information about passwords, for example under `me/security`:

<img width="870" alt="ranimac3 screenshot 2017-06-22 at 17 17 26" src="https://user-images.githubusercontent.com/426518/27438738-e362969c-576e-11e7-922a-a91272b18ae6.png">

We should update this screen, as well as any other references to passwords, to avoid confusing social signup users.

**Comment by stephanethomas** [comment]
This is similar in the intent to https://github.com/Automattic/wp-calypso/issues/16690.

**Comment by simison** [comment]
Still the case in 2020. :-) 

<img width="784" alt="image" src="https://user-images.githubusercontent.com/87168/75549425-4e818180-5a38-11ea-9975-a9f658946c07.png">

**Comment by ramonjd** [comment]
Needs some input from @Automattic/dotcom-create-design 

Should we be removing the screen? Or changing it to invite the user to create a real WordPress.com account + password?

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
