### ISSUE TITLE
Reader Tags: inconsistent tag spelling or case formatting between the sidebar and main area

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#1548]
![selection_446](https://cloud.githubusercontent.com/assets/15944096/11786250/88c84a60-a2c0-11e5-8457-2adbeb881d26.png)

In the sidebar, in the Tags section, we have "WordPress", but in the main area of the Reader, it displays as "Word Press".
Another example is: "tokyo" in the sidebar, but "Tokyo" in the main area.

Same result in Firefox and Chrome.

**Comment by bluefuton** [comment]
Thanks for the report @formosattic! 

This is happening because we're using `toTitleCase()` in the tag stream header. It attempts to format camelCase strings (like WordPress) into two words:

https://github.com/ianstormtaylor/to-title-case/blob/master/test/tests.js#L14

Tempted to remove `toTitleCase` so the name is consistent between the menu and header.
