### ISSUE TITLE
Editor: Provide messaging around setting videos/audio as featured images

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#15624]
Right now, I can select a different media type (video or audio) as the featured image for a post. However, no featured image is set (assuming because the featured image has to be an image). We should either A) block users from selecting anything other than an image or B) provide an error when they do select audio/video letting them know why it won't work.

#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Click on Set Featured Image
3. Select either an audio or video
4. Notice that nothing happens when you publish. Here's how it will appear (a bit broken):

<img width="1333" alt="screen shot 2017-06-28 at 11 21 50" src="https://user-images.githubusercontent.com/7240478/27650984-07911938-5bf4-11e7-9fcb-bf918722dc3c.png">

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was not able to reproduce this issue, as only images are now able to be selected for feature image.
Uploading a video shows the following:
![Screen Shot 2021-02-11 at 1 31 20 PM](https://user-images.githubusercontent.com/6549265/107701235-7c71cd00-6c6d-11eb-8666-b6939a7b49fd.png)

As this issue is not reproducible, it is being closed with the label `Closed - Not Reproducible`.
