### ISSUE TITLE
Settings: delete-site-notices are not getting displayed

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#158]
There should be feedback that is displayed to the user when they delete a site and are redirected to the all-sites stats page. That stopped working a while ago because the component listening for these actions is no longer contained in the page due to some other changes. This should probably get reworked in general.

**Comment by drewblaisdell** [comment]
This was fixed by #1246.

**Comment by drewblaisdell** [comment]
The fix for this in #1246 was reverted with #1318, so I'm reopening this.

**Comment by rralian** [comment]
reopening issue, based on further discussion in #3076

**Comment by lancewillett** [comment]
During a bug scrub looped back to this open issue. Behavior seems the same — no improvements to the message on the final screen, `/stats`.

Testing steps:

Starting at `/settings/general`:
![screen shot 2016-05-05 at 16 16 41](https://cloud.githubusercontent.com/assets/66797/15060172/fc058fd8-12dc-11e6-9d0f-6f6c45ed6880.png)

Now at `/settings/delete-site/`:
![screen shot 2016-05-05 at 16 16 46](https://cloud.githubusercontent.com/assets/66797/15060182/07906602-12dd-11e6-960c-6a97c7c1dce5.png)

Confirm dialog appears:
![screen shot 2016-05-05 at 16 16 54](https://cloud.githubusercontent.com/assets/66797/15060186/11385af2-12dd-11e6-9956-9c6da2885adb.png)

Confirmed by typing site address:
![screen shot 2016-05-05 at 16 17 03](https://cloud.githubusercontent.com/assets/66797/15060195/1ab38200-12dd-11e6-82ee-8dc80e7b04a5.png)

Intermediate feedback appears briefly:
![screen shot 2016-05-05 at 16 17 07](https://cloud.githubusercontent.com/assets/66797/15060206/28d0efee-12dd-11e6-87c6-912a69517550.png)

Last screen has the missing & final notice (which is what this issue is about):
![screen shot 2016-05-05 at 16 17 09](https://cloud.githubusercontent.com/assets/66797/15060217/38f9bbb2-12dd-11e6-87d4-3198fa14c3e6.png)
