### ISSUE TITLE
Comments: add avatar to reply field

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#15806]
Similar to the Reader. Avatar can disappear once the field is focused, or the reply field will have to be not 100% width.

**Comment by drw158** [comment]
Just an example, not final design:

![screen shot 2017-07-06 at 12 13 05 pm](https://user-images.githubusercontent.com/618551/27929403-6d44c742-6258-11e7-8a9d-cd0900a89d9d.png)

**Comment by gwwar** [comment]
cc @megsfulton

**Comment by gwwar** [comment]
Here's an example of the current reply field:

![Uploading 29407257-bc3ec682-833b-11e7-9bb2-2a98250abbdc.png…]()

**Comment by megsfulton** [comment]
First pass at this, three options.The first two options maintain the full width reply that's currently implemented. 


 [_View in Invision to see more examples + desktop versions_](https://automattic.invisionapp.com/share/42D992S5Q#/251385273_Replies_-_Header)

**Option A**
Matches the alignment and sizing of the site avatar and name. 
![image](https://user-images.githubusercontent.com/161697/29948171-3bacabba-8e62-11e7-9829-5ca16bde95bf.png)

**Option B**
Matches the alignment and sizing of the comment avatar 
![image](https://user-images.githubusercontent.com/161697/29948174-41bbb366-8e62-11e7-9f90-c0a4b6125028.png)

**Option C**
Uses a box for the inline reply. Starts to get pretty boxy. 
![image](https://user-images.githubusercontent.com/161697/29948199-64c595fc-8e62-11e7-99d5-212c852b5221.png)

If we like this approach, would recommend considering adding a fill to the area for more contrast between the text field and the cell row. 
![image](https://user-images.githubusercontent.com/161697/29948206-6c0e99a8-8e62-11e7-8a80-e16f526a08dc.png)

**Comment by gwwar** [comment]
Thanks @megsfulton I think I prefer option A. Let's see what a few more folks think.

**Comment by Copons** [comment]
I think I could pull option A off with some smart placeholder paddings.

**Comment by Copons** [comment]
![sep-20-2017 19-25-46](https://user-images.githubusercontent.com/2070010/30660680-9185f532-9e39-11e7-92e1-97090d7e5cf2.gif)

What do you think @megsfulton?

The idea is that both elements "extraneous" to the textarea slide in and out.
The avatar slides out when the textarea gets focus, to leave as much room as possible to the actual content.
The send button slides in when the textarea gets focus, and stays in as long as the textarea contains some content.

The textarea padding slides accordingly so that there's a sort of "everything slides left on focus" / "everything slides right on blur".

(cc @folletto because there are a couple of transitions not really used anywhere else in Calypso and I'd like a second opinion)

**Comment by gwwar** [comment]
I'd personally be okay without the transition, but I'll defer to designer 👀

**Comment by folletto** [comment]
I personally like the transition, and I massively appreciate adding these details in when we can! :)

My full take is:

1. Great, I like it 👍  for me
2. Just... make sure the animation is smooth on mobile and low-performance devices (i.e. uses the GPU)
3. also cc @shaunandrews as our Grand Wizard of Animations. :)

**Comment by Copons** [comment]
Yeah, I guess my code could probably use more `translate`s 🙂

**Comment by megsfulton** [comment]
I like the transition too! 👍
