### ISSUE TITLE
We should be Sending an `X-Frame-Options` Header

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#16]
Additionally, it'd be nice if we could send a [CSP Header](http://content-security-policy.com/), though I'm not sure how valuable it'd be for us.

**Comment by rralian** [comment]
We have `x-frame-options` in the response header for pages on calypso (the homepage and other pages I've tested). ![x-frame-options](https://cloudup.com/cI-tz0yhdRF+)

I'm marking this closed, since that's the crux of the issue here. @hoverduck Feel free to create a separate issue for CSP, but it's been discussed before internally and it looks like each time it's been a purposeful decision not to add it.
