### ISSUE TITLE
Support contact form: Add site-selector for free users

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#16015]
#### Steps to reproduce
1. Log in as an account that owns an upgrade plan
2. Navigate to https://wordpress.com/help/contact
3. Note that contact form contains a site picker so user can indicate which site they need help with
4. Next log in as an account that owns no upgrades
5. Navigate to https://wordpress.com/help/contact

#### What I expected
To still see a site picker to select which site I need help with.

#### What happened instead
No site picker is visible for free account even if account owns multiple sites. Instead, the primary site is automatically indicated in the forums as the site the user needs help with, which is not always accurate and leads to delays in helping the users.

#### Screenshot / Video
Paid user:
![help_e28094_wordpress_com](https://user-images.githubusercontent.com/11873759/27994163-329536ec-64b8-11e7-8731-3d8ac2d41c8e.png)

Free user:
<img width="729" alt="help_e28094_wordpress_com1" src="https://user-images.githubusercontent.com/11873759/27994167-683613c0-64b8-11e7-8b9b-a8e55fd22ccb.png">

#### Context / Source

Change requested by forum moderators and volunteers in 852573-f and 848339-f

cc @dllh

**Comment by jsnajdr** [comment]
Howdy @KokkieH :wave: The reason why you don't see the site selector in the free account is because the site selector display depends on the support method. If you look at the screenshots carefully, you can see that the paid used is starting a Happychat session, which supports site selection.

The free user, however, doesn't have access to Happychat, and their question will be sent to forums, or maybe to Directly. Neither of these methods supports the site selection control.

In the code, this looks like a conscious decision rather than a bug. See the `showSiteField` values in this `switch` statement:

https://github.com/Automattic/wp-calypso/blob/2e51d42be2f8c4d634dcbb125e28d15636800ed3/client/me/help/help-contact/index.jsx#L292-L398

For Directly and forums, it's simply set to `false`. For Happychat and tickets, it's `true` if the user has multiple sites, no matter if free or paid.

Mentioning some folks that touched the code last: @mattwondra @southp

**Comment by KokkieH** [comment]
>  the code, this looks like a conscious decision rather than a bug.

I'm not saying it's a bug, and this issue isn't labeled as a bug report. When I created this issue I labeled it as an enhancement request to add this option to the contact form, as enabling users to indicate the correct site they need help with would enable us to provide better support to them.

The new issue in #38280 **is** a bug, or at the very least a regression, because up until Friday last week the primary site was being indicated on forum threads created using the support contact form.

**Comment by jsnajdr** [comment]
> I'm not saying it's a bug, and this issue isn't labeled as a bug report.

Sorry I misread the issue labels. If we start adding the selected site name to the forum posts, is there any risk associated with the fact that the forum posts are public? Private sites come to mind, for example.

**Comment by KokkieH** [comment]
If someone creates a new forum thread directly in the forums at https://en.forums.wordpress.com/?new=1 the site picker there lists all sites in the account, public, private, and Jetpack, and it's up to the user to choose which site to display, though the primary site is selected by default.

And up to last week (as per the new issue I created today), creating a post via https://wordpress.com/help/contact always listed the primary site, regardless of whether or not the site is private, so I wouldn't say it's a problem. We can remove the link from the post easily enough if the user requests it.

**Comment by Aurorum** [comment]
PR for this issue in #52979. :)
