### ISSUE TITLE
Domain Manager: Blank host field in MX and TXT records produces error

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#1604]
Adding MX and TXT records are most often for the naked domain, and not a subdomain.

In Calypso right now, leaving the host field blank results in an error:
<img width="468" alt="screen shot 2015-12-13 at 4 19 29 pm" src="https://cloud.githubusercontent.com/assets/8921630/11769449/56948a6a-a1b5-11e5-8941-1200d50db9ff.png">

I'd suggest making the default, blank field default to the root domain instead of forcing the user to type out the domain for a root record.  

This update should probably include also allowing ONLY subdomain entries (for example, inputting blog into the field is currently an error, as blog.domain.com is required for it to save).  Let me know if a 2nd issue should be raised for subdomain entry.

For MX and TXT records, I can see this going three ways:
1) Pre-populate the field with their root domain instead of making them type it out (makes it super clear what is being saved but may be a bit more confusing for subdomain entry, though that is rare for mx and TXT records)
2) Only provide a field for subdomains, similar to how the email forwarder looks:
<img width="453" alt="screen shot 2015-12-13 at 4 20 45 pm" src="https://cloud.githubusercontent.com/assets/8921630/11769460/8a61d384-a1b5-11e5-8b28-d866b451869b.png"> (this might be a clean visual way to display this, and is the suggestion @stephanethomas had, but I'd want to make sure the prompt text is super clear for users who want to enter root domain records)
3) Leave it how it is, but assume a blank field is the root domain and allow record to be added. This might be the simplest, as coupled with the subdomain cleanup would minimize typing needed for the user and most closely reflects how many dns managers are - but that's not exactly a good reason for us to do it the same way)

I think #3 may be the simplest to implement, but I can see advantages to all three of the options.

**Comment by umurkontaci** [comment]
We actually can add MX and SRV type records to the root domain by entering the root domain to the field. So it is not a blocker, but I totally agree that page needs some usability improvements.

I personally like 2 much better than the others, I think it is a pattern that works and we'll have a standard way of getting subdomain input. 

However, if we go through that way, we will need to find a way to enter root domain records, I don't think leaving the field blank to add a root record because people *might* forget they did not enter something and just click submit. That said I am also not a big fan of the infamous @ sign, I had to Google for a long time to understand how to add a root recording when I was changing providers.

@breezyskies might have some input.

**Comment by breezyskies** [comment]
> I personally like 2 much better than the others, I think it is a pattern that works and we'll have a standard way of getting subdomain input.

I'd also opt for the appended field design. This is consistent with how we handle this type of input in other places in Calypso. I agree with @spncrb that the placeholder text is key here -- maybe just "Optional" or "Enter a subdomain (optional)" would make it clear enough?

> That said I am also not a big fan of the infamous @ sign, I had to Google for a long time to understand how to add a root recording when I was changing providers.

Agree, let's avoid confusing symbolisms like this. I'd rather leave the field blank.

**Comment by klimeryk** [comment]
Good call on the "Enter a subdomain (optional)" - I'll incorporate this as part of #2262, as I've already added the form suffix part there.

**Comment by BandonRandon** [comment]
> That said I am also not a big fan of the infamous @ sign, I had to Google for a long time to understand how to add a root recording when I was changing providers.

I agree that this shouldn't be the default, but I do think we need to allow for some user error. For example right now the following fails:
- Blank Field 
- @ sign
- Spaces at the front or end (needs `trim()` )
- Entering single word CNAME values (for example `blog` instead of `blog.example.com`)
- Capitals in the root domain ( blog.EXAMPLE.COM )

We should address each of these on validation. For example, if someone enters just `blog` we can assume they mean `blog.example.com` or if they enter `BLOG.EXAMPLE.COM` we can save that as `BLOG.example.com` (or ask them if they want blog instead?)

In addition to this, it may be good to throw better errors. Right now the error for each of the above is "Invalid Name" this can lead to user confusion. If we said something like "please enter a complete domain" we can maybe solve some of the confusion. 

I'll be testing @klimeryk's #2262 branch shortly to see if it addresses all of these.

**Comment by BandonRandon** [comment]
@klimeryk Can you confirm this was fixed in https://github.com/Automattic/wp-calypso/pull/3235 ?

**Comment by klimeryk** [comment]
Yup, this (allowing blank host/name fields for MX/TXT) was fixed by #3235.
