### ISSUE TITLE
Editor: When editing a post from the frontend, should be returned to frontend after updating

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#16040]
#### Steps to reproduce
1. Start on the frontend of a site (with `postPublishPreview` A/B test set to `showPostPublishPreview` variation)
2. Click Edit button in action bar at bottom of page to edit a post
3. Update post

#### What I expected

To be returned to the frontend

#### What happened instead

I was shown a preview of my post in Calypso

#### Screenshot / Video

![return to page after updating](https://user-images.githubusercontent.com/2098816/28024719-8106698e-655f-11e7-8148-ef3a40c46fa6.gif)

#### Context / Source

#dogfooding

**Comment by ryanboren** [comment]
This change really harshes my chain editing flow. I edit published posts often. Usual flow:

- Use Chrome’s omnibox to search for the post I want to edit
- Proceed to the editor via the actionbar
- Edit
- Save
- Check post-post preview
- Edit some more
- Save
- Check post-post preview
- Repeat, sometimes many times

Now, instead of post-post preview, I’m taken back to the post’s permalink page. Until I realized what was happening, I was scratching my head over where my editor sessions had disappeared to.

This change makes chain editing very heavy and expensive, especially when embeds are present. The editor reloads every embed from scratch. Some posts requires over a minute to load.

I appreciate trying to avoid the Droste Effect and forking flow with new tabs/windows, but I'd prefer a solution that doesn't kill chain editing flows.

**Comment by ryanboren** [comment]
Chain editing is one of my go to testing patterns and something I do daily as part of tending a bunch of living posts. It often reveals bugs and bad flow (back button requiring one click for each save, triggering the "discard changes" AYS, this change). Keep chain editing in mind when altering editor flow.

**Comment by ryanboren** [comment]
This change still frustrates after living with it for awhile. Leaving the editor is expensive. Keep me in it until I exit with intent.

**Comment by ryanboren** [comment]
This change combined with https://github.com/Automattic/wp-calypso/issues/9833 results in this often happening when I update.

<img width="562" alt="screen shot 2017-10-23 at 11 29 56 am" src="https://user-images.githubusercontent.com/2047747/31901053-032ab07c-b7e6-11e7-8651-d7f3e4556692.png">

I'm leaving the editor without intent and getting a warning about possible lost content in the process.

**Comment by ryanboren** [comment]
On the [unsaved changes bug](https://github.com/Automattic/wp-calypso/issues/9833) that has been with us so long:

“I am seeing this more and more, including during live 1:1 sessions with Business users, and it’s awkward to explain when the user wants to know why they continue seeing it. (I can see this happening in our screenshare.) I can hear and empathize with the clear frustration in their voices when they continue to see this pop up, especially if/when they see that they are getting data loss when navigating away from the post or page in exasperation.”

This bug is triggered in post-post flow. In publishing flows, you go to the post-post preview after clicking publishing. Navigating away from the preview back to the editor to continue editing triggers this bug. When editing an already published post in a session originating on the post’s permalink page, this is triggered immediately upon clicking Update, as seen in the screenshot in the comment above.

This bug is part of our post-post flow. As long as it lingers, it should be considered while designing.

**Comment by ryanboren** [comment]
Reopening to prompt discussion and explanation.

**Comment by ryanboren** [comment]
Were there tickets about the previous flow? Who is this serving?

There are three ways back to the post from the editor. None of them are ideal in their current forms. Tweak them, and revert this.

I’ve been raising the issue of new-tab-window Drosteholes for years (see https://test.wordpress.com/tag/forked-flow/
 and https://test.wordpress.com/tag/new-tab-window/). This isn’t the way to fix them.

**Comment by ryanboren** [comment]
I have to change ingrained flows (I’m not sure how I’m going to workaround yet) for a change seemingly made in ignorance of those flows.

This goes backwards to old core behavior that I’ve wanted to go away for years.

This is a tangential bandage that impacts current flows without making a dent in the overall Droste problem. Why should it endure while we postulate the future of post-post flow?

**Comment by ryanboren** [comment]
Contemplating the workflow changes I have to make for this. Emotions are happening, tired and frustrated being foremost. I’ll state again and then rest: this change, yet to be justified, does almost nothing to better Droste, exposes our unsaved changes bug in a very annoying and confusing way, and repeatedly exposes chain editing flow to slow, full reloads of the editor after each save.

Changes like this should be held until this is fixed. https://github.com/Automattic/wp-calypso/issues/9833

**Comment by ryanboren** [comment]
We make a Droste-y mess and try to fix it by picking on a less popular flow. This tries to guess intention. I don’t think we should guess intention here.

I’ve witnessed the problems with the post-post preview Droste effect in a room with 50 educators. I appreciate it in a publicly embarrassing way. This change helps only one particular flow and makes a divisive assumption about intent. I’d reconcile the division of intention by reverting this assumption and finding another fix that respects intent.

**Comment by ryanboren** [comment]
My workaround flow:

- Bookmark the edit page in my browser, saving it to a Frequently Edited Posts folder.
- Edit the bookmark to have the post title. The page title for edit sessions is "Edit Post ‹ Ryan Boren — WordPress.com", which does not identify the post.
- Use Alfred's Chrome bookmarks integration to find the bookmarked post and launch the editor.

I have a set of living documents that I edit often. I like to repeatedly save during my sessions for a variety of reasons.

1. Due to the unsaved changes AYS bug, I don't trust the editor, so I save often.
2. I like to push changes live as I go. For a post with sections, I'll do a section, save, do a section, save.
3. The editor fails in various ways for posts with lots of embeds. I save periodically to lock down a set of changes and refresh editor state. Problems accumulate as state accumulates.

This change means I have to change my entry to the editor when editing these living posts. I usually start at permalink pages, not the editor, to begin my editing journey. I like to see the post in published context before starting my edits. I'm changing that flow to head straight to the editor.

**Comment by mattsherman** [comment]
Closing this issue as the behavior original noted in the issue was reverted in https://github.com/Automattic/wp-calypso/pull/20448.

Separate but related editing/publishing issues should be logged as separate issues.
