### ISSUE TITLE
Store Orders - marking a payment as complete

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#16060]
When there's a payment pending status for an order, how do you mark it as paid? 
<img width="276" alt="screen shot 2017-07-09 at 10 06 47 pm" src="https://user-images.githubusercontent.com/5835847/28000421-b0d9d234-64f3-11e7-9959-00e4a7e672fb.png">

The only one close, is "Completed", but when I choose that, the order is marked as fulfilled as well, which doesn't give me a chance to enter a tracking number in. 

Can we add 'Paid in full' or something similar as an option? 

Its also a bit confusing that the items in the dropdown don't necessarily match the status indicator.

**Comment by ryelle** [comment]
I think the status you're looking for is Processing, when something's paid but not shipped yet. If that sounds right I can change the label for that status to "paid in full"... Or add another item to the list "Paid in full" that changes it to processing behind the scenes?

These are the statuses that come from the API. For the status labels we do some splitting out into "human-readable labels", which is why they don't match.

**Comment by kellychoffman** [comment]
Oh! That makes way more sense now. Thanks for explaining. 

I talked to Jay a bit about this and think we should keep this for now. 'Paid in full' makes sense, but doesn't really state the status of the order.
