### ISSUE TITLE
Editor: private post reverts to public when scheduled

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1612]
Raised by @rachelmcr 

What I Did:

I created a new post, set it to private, and then scheduled it to be published in the future.

What I Expected:

I expected the private post to be scheduled for a future date.

What Actually Happened:

The post was scheduled, but the privacy changed from private to public when I hit the "Schedule" button. (Creating a password-protected post worked as expected.)

Private draft saved and future date selected for the post:

![screen shot 2015-09-09 at 6 49 49 pm](https://cloud.githubusercontent.com/assets/8658164/9769829/5e4096fe-5724-11e5-9713-82ddeaf4e328.png)

After hitting the Schedule button, with status changed to public:

![screen shot 2015-09-09 at 6 50 01 pm](https://cloud.githubusercontent.com/assets/8658164/9769847/762e9068-5724-11e5-9fa6-5ac7e8bf3c8a.png)

Note from @ryanboren 

> There's a little core background here: https://core.trac.wordpress.org/ticket/18264

**Comment by rachelmcr** [comment]
I don't think this is an issue anymore — now, when you set a post to private, it is published immediately as a private post (rather than being saved as a draft with privacy set to private).

@designsimply I'd be ok with closing this issue since it is intentional core behavior and the UI now reflects that behavior. What do you think?
