### ISSUE TITLE
Site Preview: Doesn't work on Windows in a Private site with a custom domain

### ISSUE THREAD

**Issue by Jstachurski** [Automattic/wp-calypso#16153]
This bug is very specific. Had a user report the error in live chat. They are not able to preview their site using the Site Preview button in Calypso. However, they can open the Site Preview in a separate window and it works just fine. When trying to preview the site, they see this error:

![image](https://user-images.githubusercontent.com/8549154/28134234-59cbaf02-6710-11e7-80d8-822bc5440220.png)

"This content can't be shown in a frame"

There are some JS errors shown here:
![image](https://user-images.githubusercontent.com/8549154/28134229-53daa68e-6710-11e7-8f39-d11cc55845ec.png)

When testing, I was unable to reproduce in Firefox on Mac, site loaded just fine. The user reported using IE and Edge. 

Tested on Windows in Edge and reproduced, also in Chrome. 

This only happens on PRIVATE sites, with a custom domain. 

#user-report

**Comment by Jstachurski** [comment]
user follow up 3320269-t

**Comment by senff** [comment]
I had a similar issue today with celiaspangher.com.br, which is also a Private site.

The error message is different though (so I'm not sure if it's the same issue):
**Content was blocked because it was not signed by a valid security certificate.**

![bug](https://user-images.githubusercontent.com/1710669/28193811-8eff7b06-67f4-11e7-974a-bc53ef10c561.png)

**Comment by lancewillett** [comment]
Assigning to @jblz for later triage with Samus (not urgent).
