### ISSUE TITLE
Orders: New order notification appears in notifications panel 

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#16181]
When there's a new order, it should appear as a notification in the Notification panel: 

<img width="419" alt="screen shot 2017-07-13 at 2 00 49 pm" src="https://user-images.githubusercontent.com/5835847/28167494-b2960542-67d3-11e7-8a1a-42e660184b69.png">

**Comment by ryelle** [comment]
I looked into this a bit ago and never posted my notes. This ended up falling behind other tasks, priority-wise, but I see that it's still in the Q3 bucket, so I can pick it up again this week or after the GM. @kellychoffman can you take a look at my thought process, and specifically the question about a full view?

Here's a generated notification (proof-of-concept, nothing is actually hooked up here):
![order-notif](https://user-images.githubusercontent.com/541093/30032051-cd8557ec-9161-11e7-9f62-8eead555bd88.png)

We should have the customer's email, so we can get their gravatar, but i think we're limited to a subset of noticons for the little icon overlay. The content in the notice should also all be available to us when creating it, so overall this part should be straightforward.

But when clicked, the notification should expand into a "full view", and I'm not sure what should belong there. example:
![order-notif-full](https://user-images.githubusercontent.com/541093/30032131-243b03a2-9162-11e7-8a9b-c9a38e22c13a.png)

Maybe the full view would be a list of products? We might not have that information just from the order though. It could also work like likes/follows, where the notice is just a collection of "X orders placed", and the full view is a list of orders.

**Comment by timmyc** [comment]
So I have a few ideas around the order notif. I had commented prior ( I forget where ) that we should possibly consider aggregating order notifications over time, because if a site gets a spike in orders - these notifs could become quite noisy. But, given the target user for store on wpcom, maybe we don't need to worry about that as much.

I do however think we should consider adding the ability to turn off these notifications via https://wordpress.com/me/notifications

![notifications_ _wordpress_com](https://user-images.githubusercontent.com/22080/30038055-d5fc6dc0-9175-11e7-9d80-1e9a04342d1a.png)

By providing the ability to toggle these notifs, that would accommodate sites that get massive amounts of orders, or give store owners the ability to toggle them off during big spikes too.

**Comment by kellychoffman** [comment]
> It could also work like likes/follows, where the notice is just a collection of "X orders placed", and the full view is a list of orders.

I like this idea for the first iteration. Depending on what's possible, we can consider the full view in the future if users are wanting that.

**Comment by kellychoffman** [comment]
> that we should possibly consider aggregating order notifications over time, because if a site gets a spike in orders - these notifs could become quite noisy

I think this would be a great future addition, but for now we will start with a single notif per order.

**Comment by ryelle** [comment]
@kellychoffman My suggestion _was_ to have an aggregate "X orders placed" as the notification, not a single notification per order (which admittedly might be harder). If you want a single notification per order, we'll need to figure out what goes in the full view.

**Comment by kellychoffman** [comment]
Oh! My bad. I re-read it now and see where I misunderstood. My bad, carry on with the aggregate view.

**Comment by timmyc** [comment]
In the full view perhaps we could list the products purchased, up to a certain threshold... if there were more than 3 products on an order, things could potentially get cramped. More importantly I think having some actionable links would be ideal: link to order details, maybe link to purchase postage and one to mark the order as fulfilled are a few ideas.

**Comment by justinshreve** [comment]
I wanted to follow up here since I'm starting on this. From reading about notification trapping (i.e. aggregative view of notifications) it looks like it's not much harder to do a single notification per order vs an aggregate view.

With that in mind, @kellychoffman, Is an aggregative view still what we want here for this version?

My two cents: For smaller stores, I feel the single notification is more useful. At a glance it can provide basic details and links like Timmy noted. It also seems like a more exciting notification to get.

The aggregative view (where an existing note gets updated with the new content) seems more like a a list of recent orders. That could be useful for larger stores, though I'm not sure they would be depending on notifications as much as a smaller store would.

**Comment by kellychoffman** [comment]
I agree with Timmy. We should start with one notification per order and add the ability to manage them. We can then revisit the aggregation at a later time.

**Comment by justinshreve** [comment]
Sounds good.

In terms of management links: I think these will have to be links to the order management screen that automatically open the modals -- is this what you had in mind @timmyc? 

I don't think we can do any kind of inline management easily (The comment moderation operations already have a special notification 'block' built for it).

**Comment by kellychoffman** [comment]
I'm not sure inline management is necessary - I think linking to the management section would be sufficient.

**Comment by justinshreve** [comment]
I've got the basic notification working now. It took some work to figure out how to get it working / find where we could get certain data from for the notification. The code is not quite ready for review yet. I'll put a Phabricator patch when it is. 

Left to do:
* Logic to send notification to correct users
* Notification Setting
* Action Links (I just have view order right now, if we want links to open the modals I'll need to do a PR for that).

I wanted to get some initial feedback on the contents cc @timmyc @kellychoffman. Keep in mind that we are limited with what we can put in a notification (it's not just straight up HTML). There are certain 'blocks' we can use (see `/v1-1-notifications-api/#notification-structure` on the fieldguide).

<img width="412" alt="screen shot 2017-10-17 at 1 19 18 pm" src="https://user-images.githubusercontent.com/689165/31687441-213df508-b33e-11e7-94d6-a6430fa4aa12.png">

<img width="813" alt="screen shot 2017-10-17 at 1 19 08 pm" src="https://user-images.githubusercontent.com/689165/31687448-237f8ed0-b33e-11e7-8e19-b48d0b394937.png">

**Comment by justinshreve** [comment]
> Styling-wise I like the $ icon in the OP

Unfortunately we can only use Noticons (a more limited/special set of Genericons).

<img width="1088" alt="screen shot 2017-10-17 at 2 31 33 pm" src="https://user-images.githubusercontent.com/689165/31690560-e9fe1c58-b347-11e7-80e7-fb5435da1e18.png">

I'm actually telling it to use the 'Cart' icon but it's not working correctly for some reason (I need to dig a little further). If there is another icon here though that we want to use, we can.

>  I almost think we should show the site icon instead of the user's photo.

I was wondering this too. People placing orders might not actually have a Gravatar/WordPress.com account like other contexts (comments, etc). The site icon might provide more use here.

**Comment by kellychoffman** [comment]
We discussed this IRL and said we should use the shopping cart icon.

**Comment by timmyc** [comment]
I reviewed the phabricator diff - I know it is still in progress but figured it would be good to get some feedback on it. I also tested it with the cart icon PR from the notifications panel:

<img width="842" alt="notifications" src="https://user-images.githubusercontent.com/22080/31917997-47319a32-b80f-11e7-85de-77f91486d335.png">

Hit a couple of oddities that you can see in the image above:

- Site Title... the site title for this test site is `i <3 brobee` - in case you don't know brobee, be prepared to be [amazed](https://www.google.com/search?q=brobee+yo+gabba+gabba&safe=active&source=lnms&tbm=vid). So not sure if this is just a general notif panel bug, or if we need to encode entities to take care of the missing text ourselves in this new notif
- I noted on the phabricator diff that the variable for the site slug didn't appear to be set anywhere, and when clicking on the order link, there is no site slug so order link ended up being `https://wordpress.com/store/order//70` on this test order
- Also it appears that not all of the order items are listed, I had mentioned that listing all order items might be a bit overwhelming on a larger order, but in my attempt to test this out, not all items were displayed:

<img width="732" alt="order_details_ _timmydcrawford_ _wordpress_com" src="https://user-images.githubusercontent.com/22080/31918140-fe076444-b80f-11e7-881d-b5d187933b2e.png">

Wondering if there are more than 5 items on an order, we could list the first five and then have a line that says "and x# more items" or something - but figured @kellychoffman might have some ideas on how to handle it.

Very excited to see this! Random side-note, I was curious to see if the notif would show up in the native Android app - it did not... so wondering if we need to have the new notif type whitelisted or something for use in mobile/push notifs.

**Comment by justinshreve** [comment]
> So not sure if this is just a general notif panel bug, or if we need to encode entities to take care of the missing text ourselves in this new notif

From what I can tell, it's a general bug. Reported at https://github.com/Automattic/notifications-panel/issues/190

**Comment by justinshreve** [comment]
> I was curious to see if the notif would show up in the native Android app - it did not... so wondering if we need to have the new notif type whitelisted or something for use in mobile/push notifs.

Asked in Slack p1508961983000498-slack-notificationz -- looks like we'll need to do some fun proxying to test in mobile apps.

**Comment by justinshreve** [comment]
D7802-code has been updated and contains better testing directions.

Here is a preview of the current notification:

<img width="406" alt="screen shot 2017-10-26 at 1 12 15 pm" src="https://user-images.githubusercontent.com/689165/32074807-644a0978-ba4f-11e7-8e91-a3701524c8b7.png">

<img width="386" alt="screen shot 2017-10-26 at 1 12 30 pm" src="https://user-images.githubusercontent.com/689165/32074814-687a1920-ba4f-11e7-9c18-ed70af91d229.png">

**Comment by justinshreve** [comment]
D7802-code has been updated and contains better testing directions.

I had to make some changes to the layout of the full view to try to get things a bit more consistent across platforms, because what I had previously didn't work well on mobile. 

After some back and forth with @timmyc, based on the limits we have with the notification blocks, we came up with the following (which is similar to the simple payment notification and some other notifications).

Desktop:

<img width="411" alt="screen shot 2017-10-26 at 4 02 40 pm" src="https://user-images.githubusercontent.com/689165/32080918-232ecfa6-ba67-11e7-89bd-2716a871e22b.png">

<img width="447" alt="screen shot 2017-10-26 at 4 02 33 pm" src="https://user-images.githubusercontent.com/689165/32080924-2f45e64e-ba67-11e7-80d3-d96ebe00113e.png">

iOS:

![photo_2017-10-26_15-52-32](https://user-images.githubusercontent.com/689165/32080939-46d4ed64-ba67-11e7-8578-b5ada5176705.jpg)

cc @kellychoffman

**Comment by kellychoffman** [comment]
I know we are limited to the styling and markup here, but is there any way the copy can be left aligned?

**Comment by justinshreve** [comment]
<img width="429" alt="screen shot 2017-10-27 at 9 01 36 am" src="https://user-images.githubusercontent.com/689165/32113585-943c142c-baf5-11e7-80a7-000bbd4fb472.png">

![photo_2017-10-27_09-03-13](https://user-images.githubusercontent.com/689165/32113662-c4e7d700-baf5-11e7-8fb6-01a7d65215d9.jpg)

**Comment by kellychoffman** [comment]
Ah, much better. One last request: Could the `ORDER` title up top just say `NEW ORDER`? 

And now that I'm looking at it, I think we should change the copy to match. `You have a new order!`

**Comment by justinshreve** [comment]
Done! 

<img width="423" alt="screen shot 2017-10-27 at 11 08 48 am" src="https://user-images.githubusercontent.com/689165/32118667-5eaec46e-bb07-11e7-8687-025bbd39b398.png">

<img width="433" alt="screen shot 2017-10-27 at 11 08 42 am" src="https://user-images.githubusercontent.com/689165/32118671-6315cec6-bb07-11e7-9a9f-b40b2552a5f7.png">

![photo_2017-10-27_11-09-15](https://user-images.githubusercontent.com/689165/32118674-66fe5fbc-bb07-11e7-8b35-6df6ec65fe1a.jpg)

**Comment by kellychoffman** [comment]
:shipit:

**Comment by timmyc** [comment]
Figured I should drop this here too since phabricator isn't as easy to discuss in. I placed an order with 5 variants of the same product - the notif currently appears as:

<img width="400" alt="order_details_ _timmy_s_flies_ _wordpress_com" src="https://user-images.githubusercontent.com/22080/32120608-283a843e-bb0e-11e7-95a1-046c483b47bd.png">

And the order details page:

<img width="721" alt="order_details_ _timmy_s_flies_ _wordpress_com" src="https://user-images.githubusercontent.com/22080/32120626-38dd062c-bb0e-11e7-8ad0-3a72f793997f.png">

Thinking we should have at least the correct quantity of the product name, so in this case x5, or probably best would be to list each variant individually - but wanted to see what you all thought.

Otherwise it is looking fantastic, and it is working on my sandbox now 🎉

**Comment by kellychoffman** [comment]
Strange. In this case, listing each variant might be the most clear so you could have the best picture of what they ordered just by looking at the notification.

**Comment by justinshreve** [comment]
After some discussion in p1509138046000459-slack-store-on-wpcom, we decided to go with `Parent item x 5 (Multiple variations)` based on the information we have available for us.

I need to take care of a few other things, so I'll handle this final logic Monday. Otherwise, I think this is getting close to launchable! 🎉

**Comment by justinshreve** [comment]
@timmyc I pushed a few more updates to the Phabricator patch:

* I fixed variations handling based on the above convo, which required rewriting some of the products logic
* I added a stat bump for failed note builds (to match other notifications)
* I added some additional logic to delay caching the products data right away. Sometimes the data there gets cached before all the products data has synced, which can lead to the notification product list missing items. I've added a delay of a few minutes. Open to other ideas here.

I also need some help verifying the design on Android.

Reviewing & testing this is lower priority than reviewing Stripe/Promotions PRs, but I wanted to give you a heads up it's ready for another look when you have a chance.

**Comment by timmyc** [comment]
Variation update looks good in my test just now. I've attempted to test out the new notif on my android device, done the Charles dance and verified that my traffic is going through the local proxy, but I'm not seeing the notif show on the core Android app.

I installed the Charles root certificate... any other special steps needed?

**Comment by timmyc** [comment]
Yeah clearly I have something amiss with my proxy setup, all wpcom API requests are failing from my device -> charles -> sandbox.

**Comment by timmyc** [comment]
For future me - disabling SSL proxy on `public-api.wordpress.com` in Charles fixed the issue.

On to the results... The notifs are looking good in Android - here are some screen grabs:

![screenshot_20171031-095510](https://user-images.githubusercontent.com/22080/32237930-7fa62242-be23-11e7-8e11-35af153c6274.png)

![screenshot_20171031-095528](https://user-images.githubusercontent.com/22080/32237938-860fad4c-be23-11e7-836f-e92ad9a3567c.png)

When clicking on the "View Order" action, the first screen looks broken:

![screenshot_20171031-095619](https://user-images.githubusercontent.com/22080/32237980-a39a41e2-be23-11e7-81fd-9f1489ef7121.png)

But apparently there just was no loading indicator / placeholder shown, and eventually the order details page rendered:

![screenshot_20171031-095630](https://user-images.githubusercontent.com/22080/32238012-b9145152-be23-11e7-865c-8c147bed88be.png)

**Comment by justinshreve** [comment]
Launched! 🎉
