### ISSUE TITLE
Store: Shipping Label Details and Refunds

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/wp-calypso#16197]
![screen shot 2017-07-13 at 11 06 56 am](https://user-images.githubusercontent.com/63922/28178493-ee13b62c-67bb-11e7-80e2-32a87b954e4f.png)

As a merchant, how do I refund shipping labels I've purchased? If my order required 2 packages, and I messed up one, how do I refund just the one label and try again?

![screen shot 2017-07-13 at 11 13 10 am](https://user-images.githubusercontent.com/63922/28178595-4c83b4dc-67bc-11e7-9b6f-11c6b9514c11.png)

If my order required 2 packages, and therefore 2 labels - how do I know which label to put on each package?

**Comment by jameskoster** [comment]
I think we should redesign the order activity log a bit to match Jetpack, and include refund actions in there.

> If my order required 2 packages, and therefore 2 labels - how do I know which label to put on each package?

How do you know in the current wcs? I think the simplest solution would be to have a link in the activity log which opens a modal containing this info.

Updated design to come!

**Comment by jameskoster** [comment]
Updated design, based on Jetpack activity log;

![activity-log](https://cldup.com/qth5ip8DCV.png)

> As a merchant, how do I refund shipping labels I've purchased? 

Refund button in the log. Label data (tracking number, package contents, action buttons etc) disappears from the original log item once refunded.

> If my order required 2 packages, and I messed up one, how do I refund just the one label and try again?

Click the refund button then repeat the label printing process. Hopefully we can highlight the products that still require packaging here.

> If my order required 2 packages, and therefore 2 labels - how do I know which label to put on each package?

Clicking the 'label' link in a log item will open a 'preview' of the label. Clicking the 'package' link in the same log item will reveal the package contents / dimensions.

**Comment by jeffstieler** [comment]
> Clicking the 'label' link in a log item will open a 'preview' of the label.

I think "reprint" should suffice here. Can we skip the label preview for now?

**Comment by jameskoster** [comment]
Sure.

cc @kellychoffman to check out the design

**Comment by kellychoffman** [comment]
Super cool! I think @keoshi's design is currently being implemented, so we could probably borrow the styles. Or maybe make a compact version?

**Comment by kellychoffman** [comment]
Would we cut it off at a certain point? Ie have some 'view more' link or implement infinite scroll if there's more than 20 events for a single order?

**Comment by jameskoster** [comment]
> Would we cut it off at a certain point? Ie have some 'view more' link or implement infinite scroll if there's more than 20 events for a single order?

That's a good point that I forgot to mention - to save space I think it'd best to only have the most recent activity visible and the other cards closed by default.

![closed](https://cldup.com/9L0O9AmPgG.png)

**Comment by kellychoffman** [comment]
So just open the most recent day and collapse the others? I like it.

**Comment by jeffstieler** [comment]
For posterity, here's what the reprint and refund modals look like in WCS:

![](https://cldup.com/DIhDaziqIV-3000x3000.png)

![](https://cldup.com/7uWLp0dw85-3000x3000.png)

**Comment by dechov** [comment]
Remaining items (cc @kellychoffman, @DanReyLop, @marcinbot):

## Label identification

Currently deployed in staging (no way to match labels to packages):
<img width="313" src="https://user-images.githubusercontent.com/1867547/31907575-39c37e54-b802-11e7-946c-edfca9eca38f.png">

> @jeffstieler: If my order required 2 packages, and therefore 2 labels - how do I know which label to put on each package?
>
> @jameskoster: How do you know in the current wcs? I think the simplest solution would be to have a link in the activity log which opens a modal containing this info.

`<Tooltip />` on hover in wp-admin:

<img width="349" src="https://user-images.githubusercontent.com/1867547/31906753-e8ae7dfe-b7ff-11e7-93b4-4ce404fce42d.png">

Respectively: package name, service name, package contents. (The purchased product's name is "Product" in this case.) We can display this info in a modal on click if that's preferable.

> @jameskoster:
> <img width="403" src="https://user-images.githubusercontent.com/1867547/31906080-22ae6160-b7fe-11e7-9f26-7547ec559505.png">
> Clicking the 'label' link in a log item will open a 'preview' of the label. Clicking the 'package' link in the same log item will reveal the package contents / dimensions.
>
> @jeffstieler: I think "reprint" should suffice here. Can we skip the label preview for now?
>
> @jameskoster: Sure.

Do we still want a "Label" link exposing the service name or anything else? Note that (to the best of my understanding) the package is somewhat but not entirely independent of the service — it may make more sense to keep all of that information together.

Also, the API is not currently including _package dimensions_ with the label history, but it would be little trouble to add it in an upcoming WCS release.

As for the **package name** (i.e. "package 2") — on one hand, I would expect this to match the list item text in the label purchase Packages step:

<img width="293" src="https://user-images.githubusercontent.com/1867547/31908851-2f74e4f2-b806-11e7-9a60-9aed3560fc41.png">

But the packages aren't being named or numbered as such in wp-admin — only the labels are. Since we aren't grouping labels by purchase event, a name like "package 2" isn't strictly meaningful after a 2nd purchase (and I'm not sure if we're hanging onto enough data to still compute those descriptions, without non-trivial changes on the plugin side).

In the most typical case, we expect labels from only a single purchase. Background question that might possibly inform the design here: how often would an additional label purchase be made because...
- a mistake was made the first time?
- only a portion of the order was shipped the first time? (This functionality was disabled as a side effect of another change but may return.)
- of some other reason?

Anyways — thoughts?

## Hiding data for refunded labels
> @jameskoster: Label data (tracking number, package contents, action buttons etc) disappears from the original log item once refunded.

Sounds fine to me, but package contents (etc.) and tracking number do appear in wp-admin:

<img width="345" src="https://user-images.githubusercontent.com/1867547/31906760-eb953832-b7ff-11e7-9c34-95f2915f0150.png">

Anyone know if it's kept around for a particular reason?

**Comment by DanReyLop** [comment]
> only a portion of the order was shipped the first time? (This functionality was disabled as a side effect of another change but may return.)

What change was that? I've been purchasing labels from the same order since months ago...

> Hiding data for refunded labels ...
> Anyone know if it's kept around for a particular reason?

Just because we didn't implement the "hiding when refunded" logic in `WP-Admin`, it didn't occur to us at the time. But hiding it seems the most reasonable UI.

**Comment by kellychoffman** [comment]
> Respectively: package name, service name, package contents. (The purchased product's name is "Product" in this case.) We can display this info in a modal on click if that's preferable.

Can we add a separate link that says `View details` and then display the info in a modal? 

> Do we still want a "Label" link exposing the service name or anything else? Note that (to the best of my understanding) the package is somewhat but not entirely independent of the service — it may make more sense to keep all of that information together.

I think we should just use the View details link for this. 

> As for the package name

If we can't easily grab this, lets just nix this from the UI and just say`Label printed`

**Comment by dechov** [comment]
> What change was that? I've been purchasing labels from the same order since months ago...

I meant if only item 1 was ready to ship so you bought a label for it, and later went back to buy a label for item 2. You can no longer purchase labels for a subset of items though, which (as you probably remember) you once helped me track down to https://github.com/Automattic/woocommerce-services/pull/1028/commits/c41126b46b1b28bfc723b1be11bb0bdfd519661e.

> Just because we didn't implement the "hiding when refunded" logic in WP-Admin, it didn't occur to us at the time. But hiding it seems the most reasonable UI.

👍
