### ISSUE TITLE
Sidebar header: Streams/Switch Sites too similar

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#16230]
The top of the sidebar is _very_ similar. I mentioned this, and @folletto correctly mentioned that they serve different purposes and _should_ be different. One is a title and the other is a clickable interactive element.

I can appreciate and understand this, but the difference may be _too_ subtle. I had assumed this was an oversight. Can or should we make these elements more visually different?

#### Steps to reproduce
1. Start logged in at https://wordpress.com/ (Reader)
1. Switch between "My Sites" and "Reader"
1. Observe the subtle differences between "Streams" and "← Switch Site"

#### Screenshot / Video

![mysites-stream](https://user-images.githubusercontent.com/841763/28211413-d59072b6-689c-11e7-9543-09ab3ce3bfb9.gif)

#### Context / Source

Observed when developing. Mentioned here: p1500032428933618-slack-automattic

**Comment by drw158** [comment]
To provide some history: This is a recent occurrence because of the recent change to make all compact buttons not uppercase.

Options:

- Simply change the color. The switch button is technically failing contrast test I believe, so we could use a darker color.
- Make the headers uppercase. But, we want to avoid doing that.
- I like this idea:

![screen shot 2017-07-14 at 9 45 39 am](https://user-images.githubusercontent.com/618551/28217006-3ef62c4c-6879-11e7-932e-d35e24f59a09.png)

**Comment by shaunandrews** [comment]
I think #22863 helps resolves this.
