### ISSUE TITLE
Store: Setup: WooCommerce: Notify/allow merchant to set Shop as front page of site

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16293]
Right now you have to go into wp-admin to set the WooCommerce Shop page as the site's front page.  We should change the setup steps to 1) detect that the "front" page is not the "shop" page and 2) allow them to set their "front" page to the "shop" page

I couldn't figure out how to set my "front" page from calypso at all. I had to use wp-admin to do it. I see we add an indicator on it on wordpress.com/pages/{domain} but could not find any way to set it.

<img width="82" alt="screen shot 2017-07-17 at 9 45 20 am" src="https://user-images.githubusercontent.com/1595739/28279274-d3743848-6ad4-11e7-8d84-e89f3faa0034.png">

This is needed because if the user is setting up a store, chances are they want the store (shop page) to be the first thing visitors see when they come to the site.

**Comment by justinshreve** [comment]
I think it's not in Calypso because it's in the customizer (which is technically wp-admin -- but we do redirect & open in a new window so its like they are still in Calypso) but we do link to it during the setup steps. The easiest path there could be some pointers on where to go (Static Front Page > Shop).

**Comment by kellychoffman** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/17101, which solves this problem :)
