### ISSUE TITLE
Sign up: Domain First: Formatting buttons is large and text

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#16319]
Steps to reproduce:

1. Visit https://wordpress.com/start/domain-first/site-or-domain
2. Enter a domain

Issues:

1. The EXISTING WORDPRESS.COM SITE button looks too large compared to other options
2. The phrase `Free domain included with all plans.` could sound better as `A free domain is included with all plans.`

Screenshot:

<img width="983" alt="screen shot 2017-07-18 at 12 50 33 pm" src="https://user-images.githubusercontent.com/128826/28299499-eea69fb4-6bbc-11e7-8dd2-36cfe4c81be2.png">

**Comment by fabianapsimoes** [comment]
cc @aidvu @mikeshelton1503

**Comment by aidvu** [comment]
@alisterscott mind giving me the exact browser version and OS?

**Comment by mikeshelton1503** [comment]
I've noticed this too, it's bigger because the text wraps. It will vary per OS and browser and also per different languages. The solution needs to assume that the copy will wrap but pretty low priority right now.

**Comment by alisterscott** [comment]
@aidvu: Chrome Version 59.0.3071.115 (Official Build) (64-bit) on macOS 10.12.6 (16G29)

**Comment by arunsathiya** [comment]
@aidvu What are your thoughts on having these buttons in capitalisation, instead of uppercase? From what I have noticed, most other buttons throughout Calypso are in capitalisation.

Attempting to have these button text in capitalisation by modifying [this section of the stylesheet](https://github.com/Automattic/wp-calypso/blob/3a082e55f83c618130bbb2f5f59b91328e95cddd/client/signup/steps/site-or-domain/style.scss#L41-L42) results in this format.

<img width="853" alt="screenshot 2018-11-01 at 08 43 17" src="https://user-images.githubusercontent.com/18581859/47830968-803af780-ddb4-11e8-8ec4-da467ac0c0f9.png">
<img width="1280" alt="screenshot 2018-11-01 at 08 42 21" src="https://user-images.githubusercontent.com/18581859/47830969-80d38e00-ddb4-11e8-83d3-a9f7b5fd933c.png">
<img width="398" alt="screenshot 2018-11-01 at 08 42 07" src="https://user-images.githubusercontent.com/18581859/47830970-80d38e00-ddb4-11e8-8577-49cf38187aff.png">

The buttons look even and nice at this stage.

**Comment by aidvu** [comment]
Sounds good. Will pick this up next week. :)

**Comment by arunsathiya** [comment]
@aidvu Would you mind if I submit a PR for this? 🙃I would love to hear any feedback on that PR as well!

**Comment by aidvu** [comment]
@arunsathiya I would love that! Looking forward to it!

**Comment by arunsathiya** [comment]
Closing, as this has been merged on #28210.
