### ISSUE TITLE
Analytics: Strip potential email addresses before sending to GA

### ISSUE THREAD

**Issue by pento** [Automattic/wp-calypso#16318]
Google doesn't allow email addresses to be recorded in GA, so they need to be removed from any URLs sent.

I'm inclined to remove URL parameters that may contain email address - so far I've seen `redirect_to` and `email` as parameters that we don't need to record, `url` when visiting `/post*` (used by PressThis, may contain email addresses from unknown URLs).

Here's the relevant code:

https://github.com/Automattic/wp-calypso/blob/master/client/lib/analytics/index.js#L321-L394

**Comment by Essayoh** [comment]
Just a reminder, to avoid being disconnected from our Google services (which would be, uh, suboptimal), this needs to be done by October - ideally mid-September so we can be 100% sure we've solved it to their satisfaction.

Not adding this to imply anything, but rather to keep this information out in the open rather than in my email inbox / brain.

**Comment by MicBosi** [comment]
Hi @pento, so far the approach I've followed with this PII issues is rather "brutal", we basically block all tracking/analytics if we find or think there might be PII on the URL using this function:

https://github.com/Automattic/wp-calypso/blob/master/client/lib/analytics/utils.js#L15

Looks like isPiiUrl() wasn't being triggered because so far we're looking for things like `email=` not for it's encoded counterpart `email%3D` - so the quick way to fix this would be to add those encoded patterns to the black-list used by the function, while a more elaborate way would be to strip away the PII from the URL we give to GA.

The problem with this last solution is that it does not solve the issue for all the other ad-trackers we have which likely read the value in `document.location.href` directly. In fact, even if we're unsure whether a third party JS code reads the current URL or not, we probably should not allow it to run at all, if there might be PII in the URL, in order to abide by our own TOS, let alone the third party one.

So, if you haven't objections I'll add the encoded patterns to the list as well to implement the general block and safeguard the PII from all the trackers. On top of that if you or anyone wants to treat GA specially and make URL surgery, we can do that as well, as the next step. 

In an ideal world we wouldn't have PII passed in the URL in clear but sent via POST data, or a cookie or at least safely encoded if they have to stay in the URL.

cc @Essayoh

**Comment by pento** [comment]
Oh, cool. I totally missed the existence of `isPiiUrl()`.

This sounds like a good plan - I'm fine with just not loading the external trackers on PII URLs - all the important analytics on the login and registration flows are recorded as Tracks events, we have no need for specific URLs.

**Comment by Essayoh** [comment]
Agree with @pento here, this shouldn't break any kind of internal tracking.

**Comment by MicBosi** [comment]
For reference here's the PR: #16905

**Comment by MicBosi** [comment]
PR #16905 merged and deployed. Closing the issue.
