### ISSUE TITLE
Store: WooCommerce: Order details should include order datetime

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16381]
When viewing an order (at /store/order/{domain}/{orderID} ), you cannot tell when the order was created.

**Comment by ryelle** [comment]
Re-opening this issue so that we can get a design ✅ on the placement. To me, having it between the total section and the refund/fulfill actions is interrupting the flow. The other idea in #16777 was to add it in the `SectionHeader`.

Screenshot of current placement:

<img width="744" alt="screen shot 2017-08-02 at 7 48 45 pm" src="https://user-images.githubusercontent.com/541093/28899941-ac399aae-77bb-11e7-92e1-fea08d1cedc7.png">

**Comment by folletto** [comment]
It's not bad for me, but I agree it breaks a bit the flow. 

Even without redesigning the header to include it (which I won't do as it might impact other screens and the overall logic), just moving the block up feels better, creating the top area about the details, and the bottom about the payments and actions:

![screen shot 2017-08-03 at 11 26 08](https://user-images.githubusercontent.com/4389/28917767-b411e49c-783e-11e7-80ab-798065401d10.png)

**Comment by allendav** [comment]
Hey @folletto - I agree - at the top looks better - I'll make the change
