### ISSUE TITLE
Store: WooCommerce: Tracking Number emails sometimes use the site title, but sometimes use "Site Title"

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16445]
From /store/order/{domain}/{orderID} fulfill an order, giving it a tracking number (make anything up) and checking the "send to customer" box.

The customer does receive an email, but in some places where the site title should appear the hardcoded string "Site Title" appears instead.

<img width="1005" alt="screen shot 2017-07-20 at 2 53 57 pm" src="https://user-images.githubusercontent.com/1595739/28440582-b73aec92-6d5b-11e7-9371-1ddbeed5e3f5.png">

<img width="1014" alt="screen shot 2017-07-20 at 2 54 13 pm" src="https://user-images.githubusercontent.com/1595739/28440593-c257d9aa-6d5b-11e7-9063-44200e0b4e23.png">

It is possible this is a core WooCommerce issue instead.  Not sure. cc @mikejolley

**Comment by ryelle** [comment]
This likely is a woocommerce bug, we're not doing anything in Calypso for this other than creating an order note with `customer_note=true` to send the email.

**Comment by justinshreve** [comment]
@allendav @ryelle 

So... it looks like WooCommerce has a completely [different setting for this](https://github.com/woocommerce/woocommerce/blob/891e55e1cfc08697b88e24eef38f393f88718049/includes/admin/settings/class-wc-settings-emails.php#L66). 🤦‍♂️ 

Luckily it looks like it is [filtered before sending](https://github.com/woocommerce/woocommerce/blob/cb3e1de0bec17bf340840960c0945c655aa5c9a8/includes/emails/class-wc-email.php#L497). I think a 'fix' for launch could be filtering it in a `wc-api-dev` hotfix.... otherwise we will somehow have to keep them in sync?

**Comment by justinshreve** [comment]
The footer text is a separate setting too..

**Comment by justinshreve** [comment]
Hot fix was merged for this, but I want [this fix](https://github.com/woocommerce/wc-api-dev/pull/32#issuecomment-317852090) before truly closing this.

**Comment by justinshreve** [comment]
This is fixed for Calypso sites. I've opened a core issue at #17039, so I don't think there is a need to keep this issue open.

**Comment by sirreal** [comment]
@justinshreve Did you mean https://github.com/woocommerce/woocommerce/issues/17039? 🙂

**Comment by justinshreve** [comment]
Yup, edited. Thanks for catching that!
