### ISSUE TITLE
Post URL: In the after publish preview, the mapped domain name isn't used

### ISSUE THREAD

**Issue by nickmomrik** [Automattic/wp-calypso#16470]
#### Steps to reproduce
Publish a new post. When the preview screen comes up, the URL displayed (and available for copying) at the top doesn't use the mapped domain of the site. It uses the blogname.wordpress.com domain.

#### What I expected
For the mapped domain to be used in the URL, like when copying the URL from a post edit screen as shown in this image...

![edit-post-url](https://user-images.githubusercontent.com/684691/28471939-cacd7462-6e0c-11e7-8d4b-d09c6dffd12d.png)

#### What happened instead
The blogname.wordpress.com domain is used in the URL.

![after-publish-url](https://user-images.githubusercontent.com/684691/28471928-c510b3a4-6e0c-11e7-98f4-b81aabbd38c6.png)

#### Browser / OS version
I have reproduced in Mac Chrome and in the Mac Desktop app.

**Comment by ryanboren** [comment]
I was excited when I saw this copy box in the post publish preview/confirmation. This really helps my post pub flow.

I too noticed that the mapped domain is not used. Once this is fixed, this handy little feature will be a great assist to my daily flow.

The shot below shows the copy box in full context. The link uses my unmapped domain rather than my mapped domain.

![screen shot 2017-07-23 at 9 47 23 am](https://user-images.githubusercontent.com/2047747/28501112-ae9c4b44-6f9a-11e7-9d7d-1891cec5c20e.png)

Editorial, impact: This is a recurring theme familiar to those with mapped domains. Historically, domain mapping has come with lots of little extra frustrations due to mapped/unmapped bugs. IIRC, this is the third one in the editor in recent memory.

**Comment by spen** [comment]
Thanks for the original report @nickmomrik and for the extra details @ryanboren :)
I've self-assigned on to this issue as I'm working on making some improvements in this area for Site Preview (`/view/`) at #16329. As it stands the primary domain problem is fixed there but I don't think this'll fix the other previews... I'll pop open a PR today for those all being well :)

**Comment by spen** [comment]
PR #16512 should resolve this issue :)
