### ISSUE TITLE
Image captions are not getting updated in Image editor

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#16484]
While checking an issue for a ticket, I came across an issue regarding Image caption.
2. I added a caption to an image from the Image editor. Saved the post.
3. Changed the caption using the inline editor option. Saved the post.
4. The changed caption is not displayed in the Image Editor.

I expected the image captions to be same in the editor as well in the inline editor.
Instead, the captions on the editor and in the inline editor were different.

Here is my system configuration: 
[export.pdf](https://github.com/Automattic/wp-calypso/files/1167264/export.pdf)

Screenshots:
![inline-caption](https://user-images.githubusercontent.com/7382505/28490239-a39c3a18-6ef2-11e7-8123-691898627269.png)
![editor-caption](https://user-images.githubusercontent.com/7382505/28490238-a39b275e-6ef2-11e7-8977-48b02c8298c6.png)

#manual-testing

**Comment by designsimply** [comment]
Thank you for reporting this! Great write-up!

What you've reported is expected based on how media has traditionally been designed to work using WordPress. Essentially, the meta data in the media library becomes disconnected from the edits to an image inline in the post once an image has been inserted. What this means you can do is change the size, caption, etc for an image inline in a post without affecting the meta data in the media library. When you click the pencil icon, you are viewing the meta data saved in the media library. When you edit inline or make sizing or alignment changes with the image toolbar you are editing the instance of the image in the post directly without affecting the image in the media library. This is why the captions do not match if you edit inline compared to editing the meta data for the instance of the image in the media library. I understand it can be a little confusing at first and may not be ideal with regard to the caption. I decided to close the issue but am glad it is on record and if it comes up a lot of times with users then we should re-open it and take a closer look depending on how confusing it is and how many times it is reported as a problem.

Here are my testing steps and a video explanation for this case:

1. Go to https://wordpress.com/post and select a site if prompted.
1. Insert an image.
1. Click the image.
1. Click the minus sign twice to decrease the image size to medium.
1. Click the image.
1. Click the pencil icon.
1. Make a change to the caption there and save changes.
1. Check to see if the caption in the post updates.
1. Update the caption inline in the post editor directly.
1. Click the image.
1. Click the pencil icon.
1. Not that the captions do not match.

Result: editing an image caption inline is only reflected for the instance of that image inserted into the post while editing an image caption in the media library (aka the image edit function within the post) only affects the image in the post if it is re-inserted. This is the expected behavior.

Video: [1m59s](https://cloudup.com/cJaHZA9BR8P)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11313 using Chrome 59.0.3071.115 on Mac OS X 10.12.5.</sup>
