### ISSUE TITLE
Purchases: Site order

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#165]
The order of the sites in /purchases is currently based on the purchase date of their respective purchases. It should use the same order as the site picker.

**Comment by stephanethomas** [comment]
> I agree, with a little tweak: any site with a subscription in a special state (failed auto renewal, has expired, domain in grace period or redempion) should be pushed to the top.

I'm not sure about that one because it means that the order is no more consistent with the site picker but also with what users are used to on this `Purchases` page - and when it's not predictable it forces users to think about the interface and it makes it feel less efficient. Moreover the majority of users only have one blog, only a few have twos, and as such they should be able to see that something requires their attention easily since the page wouldn't be that long.

**Comment by scruffian** [comment]
I think that moving the site to the top if it is in a special case is probably a different issue, and probably needs some design thought - we might like to change the way it looks slightly to show that it's been bumped to the top for a reason.

We can easily handle these in two different PRs.

**Comment by drewblaisdell** [comment]
I opened an issue for bumping purchases in certain states to the top of the list: https://github.com/Automattic/wp-calypso/issues/4620
