### ISSUE TITLE
Bug: Pinterest not embedding with .co.uk extension

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/wp-calypso#16504]
#### Steps to reproduce
1. Starting at URL: https://www.pinterest.co.uk/pin/31736372357550500/
2. Pasted the Pinterest URL into a blog post using the Visual editor.
3. Published the post.

#### What I expected
The Pinterest pin to be embedded.

#### What happened instead
The Pinterest URL was published, but the pin/image was not embedded. 

#### Browser / OS version
Safari
MacOS Sierra 10.12.6

#### Screenshot / Video
Published post: https://wp20170925.com/2017/07/24/testing-pinterest-embed/
Screenshot: https://cloudup.com/cuJ-p0tvLzp

#### Context / Source
Pinterest uses the .co.uk extension for UK visitors, so all URLs they see will be .co.uk instead of .com. Pasting the .com Pinterest URL results in the pin being embedded, as expected. However, the pin is not embedded when pasting in the .co.uk Pinterest URL. As a temporary workaround, users can manually change the extension in the Pinterest URL from .co.uk to .com so that the pin gets embedded.

Via #user-report in 529961-chat

**Comment by designsimply** [comment]
Thank you for reporting this @juliasydnor!

I tested and confirmed with the following steps:

1. Find the URL for a Pinterest image such as https://www.pinterest.com/pin/516436282251591544
1. Go to My Sites > Blog Posts > Add.
1. Add a title and enter sample Pinterest URLs, one per paragraph.
1. Publish the post and view it.

Result: only the .com version of Pinterest images are embedded—international TLDs such as .co.uk, .de, and .it do not work.

Sample Pinterest URLS:

* https://www.pinterest.co.uk/pin/516436282251591544
* https://www.pinterest.it/pin/516436282251591544
* https://www.pinterest.de/pin/516436282251591544
* https://www.pinterest.com/pin/516436282251591544

![screen shot 2017-07-24 at mon jul 24 3 39 57 pm](https://user-images.githubusercontent.com/1119271/28546061-96036350-7086-11e7-941e-323462756bde.png)
<sup>Seen at https://design5279.wordpress.com/2017/07/24/pinterest-embed-test-2/ using Firefox 54.0.1 on Mac OS X 10.12.5.</sup>

I researched the issue and found that the issue was already reported at 7887-wpcom and I am closing this issue as a duplicate. In general, the `wp-calypso` GitHub repository is for reporting issues which affect the Calypso part of WordPress.com directly (the new admin area) and things which affect the front end for blogs (such as embeds) are reported at wpcom.trac or core.trac. It's not expected that you would know this ahead of time, and I just wanted to let you know and also say thank you for the report and that it's no problem for me to move the issue!
