### ISSUE TITLE
Customizer: Site Identity > Select Logo > "Select" button is outside of viewport on iPad Safari 

### ISSUE THREAD

**Issue by crunnells** [Automattic/wp-calypso#16559]
When using the Customizer on an iPad, it is impossible to set a site logo because Media Modal takes up more than 100% of the screen height, so the "Select" button is outside of the viewport. I found this on a brand new iPad, and on my personal iPad (from ~4 years ago). It seems to occur regardless of tablet orientation. I should also mention that I can't reproduce the issue using Responsive Design Mode in Firefox or Safari

#### Steps to reproduce
1. Use an iPad: https://wordpress.com/customize/ 
2. Go to Site Identity > Select Logo
3. Notice the media modal is larger than the viewport, and the blue "Select" button isn't visible.

#### Browser / OS version
* New iPad (purchased in the last 30 days) iOS 10
* Also 3rd gen iPad on iOS 9.3.5

#### Screenshot / Video
https://cloudup.com/cf4K-CWLT-B

<img src="https://user-images.githubusercontent.com/1119271/36326848-cb99c168-1319-11e8-9883-ec53e8ff2e43.png" width="300">

#### Context / Source
Found while walking a friend of mine through setting up a WordPress.com site. He only has an iPad and iPhone (no laptop) so we used Safari and found this problem. We switched to the iOS app to choose the logo.

#dogfooding #user-report

**Comment by designsimply** [comment]
Tested and confirmed using Safari iOS 9.3.5 on iPad 3rd Gen (Retina). However, I did notice that it's possible to scroll to see the button.

![img_0256](https://user-images.githubusercontent.com/1119271/36327203-1a5dcd70-131b-11e8-9b45-e3dbc17c6470.PNG)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
