### ISSUE TITLE
Don't display "You need a Stripe account..." notice if Stripe is in use

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#16580]
![stripe](https://cldup.com/EiSb-VxDbv-3000x3000.png)

Do we validate their credentials? If so, we can just hide this notice once valid credentials have been supplied.

**Comment by budzanowski** [comment]
There is no verification mechanism to check if a key is a valid key or not. The only way to know is to make API call. With secret key, it should be easy to do by just asking for the balance. With publishable key it is much more problematic because it would require requesting, for example, an actual credit card token - which is not very practical. 
Maybe just test the secret key?  
Options:
1. If it works then replace the notice with something like: "Make sure that the keys here are correct". Still, a useful information and valid when the publishable key works or not.
2. Give information that there is a problem with keys when secret one does not work, and user should verify with their Stripe account.
3. Show the register account info when key fields are empty.

What I don't know is how will this be affected when we will have Stripe Connect - maybe then we could remove the banner completely and leave the keys modification to advanced users?

@allendav could you help with who to ping on question above?

**Comment by justinshreve** [comment]
I would say that we should go with #3. Part of the Q3 goals are to reduce friction with Stripe Connect as you noted and to avoid the need for users to even be pasting in these tokens. So I think a simple check would work for now.

**Comment by kellychoffman** [comment]
closing this as @allendav's work with stripe connect supersedes it.
