### ISSUE TITLE
Store: Expose direct bank transfer options and reenable

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#16630]
If you enable "Direct bank transfer" as a payment option you can configure:

![screen shot 2017-07-27 at 09 40 04](https://user-images.githubusercontent.com/551898/28679174-9630b852-72af-11e7-8064-f9bede6ac2a8.png)

In wp-admin you can configure:

![screen shot 2017-07-27 at 09 40 19](https://user-images.githubusercontent.com/551898/28679200-a4ae5682-72af-11e7-8807-9b09ab8679ea.png)

Some of these things seem pretty important if people are going to be able to pay.

**Comment by kellychoffman** [comment]
For now, bank transfers have been disabled. 

@justinshreve - We should prioritize getting this back in for next Q.

**Comment by justinshreve** [comment]
Agreed.

**Comment by timmyc** [comment]
Okay finally getting around to exploring this a little bit. Couple of challenges to note thus far:

- The API endpoint for payment gateways currently does not return any of the account details that are shown in wp-admin, just the base settings:

```
            {
                "id": "bacs",
                "title": "Direct bank transfer",
                "description": "Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.",
                "order": "",
                "enabled": false,
                "method_title": "BACS",
                "method_description": "Allows payments by BACS, more commonly known as direct bank/wire transfer.",
                "method_supports": [
                    "products"
                ],
                "settings": {
                    "title": {
                        "id": "title",
                        "label": "Title",
                        "description": "This controls the title which the user sees during checkout.",
                        "type": "text",
                        "value": "Direct bank transfer",
                        "default": "Direct bank transfer",
                        "tip": "This controls the title which the user sees during checkout.",
                        "placeholder": ""
                    },
                    "instructions": {
                        "id": "instructions",
                        "label": "Instructions",
                        "description": "Instructions that will be added to the thank you page and emails.",
                        "type": "textarea",
                        "value": "",
                        "default": "",
                        "tip": "Instructions that will be added to the thank you page and emails.",
                        "placeholder": ""
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "https://oregonpaws.blog/wp-json/wc/v3/payment_gateways/bacs"
                        }
                    ],
                    "collection": [
                        {
                            "href": "https://oregonpaws.blog/wp-json/wc/v3/payment_gateways"
                        }
                    ]
                }
            }
```
- The account details are omitted due to the fact that the field config [#](https://github.com/woocommerce/woocommerce/blob/891e55e1cfc08697b88e24eef38f393f88718049/includes/gateways/bacs/class-wc-gateway-bacs.php#L99-L101) does not have all the required attributes ( type, title )
- Returning the account details array via the current core API logic doesn't really align well with the [supported schema](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-payment-gateways-controller.php#L412-L417)
- Updating the account settings in the context of the `WC_REST_Payment_Gateways_Controller` looks _challenging_
- Account details are persisted in the `woocommerce_bacs_accounts` option [#](https://github.com/woocommerce/woocommerce/blob/891e55e1cfc08697b88e24eef38f393f88718049/includes/gateways/bacs/class-wc-gateway-bacs.php#L222)

Given those items, we have a few ways of getting the data into the API response:
- Explore building out a full CRUD set of endpoints for `/wc/v3/payment_gateways/bacs/accounts`
- [Filter the response](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-payment-gateways-controller.php#L273) from the existing endpoint logic in `wc-calypso-bridge` to include the account details

As for updating the data via the API:
- Again build out a proper set of endpoints for bacs accounts
- Hook into the API or do magic with [this filter](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-payment-gateways-controller.php#L206) to persist the data... which both feel like really bad choices

@justinshreve any thoughts on the best way to proceed here? Seems like building out some endpoints specifically for the accounts is the cleanest way to go... though a bit of work for this single payment type.

**Comment by justinshreve** [comment]
Blah - that's unfortunate and I didn't realize we were missing some key parts in the API for this. Thanks for documenting the issues here so well.

The "right" thing is proper endpoints.. but I totally agree that it is quite a bit of work, and it really doesn't seem like a good use of our time right now. 

So having said that - I think we should go ahead and take use of the filters and the fact that we have `wc-calypso-bridge` now, and do it that way. We should log a proper issue for those endpoints for the future though.
