### ISSUE TITLE
Publicize: Add master calendar view, or easier way to see upcoming shares

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#16672]
As it stands now, there's no single place where I can see all of my scheduled shares. I have to open up the Share section under each blog post to see if I have any.

We should consider adding some sort of "master" list or calendar view where I can see all my upcoming shares in one place.

Barring that, perhaps we can add a `.count` span to the post card if the post in question has shares scheduled to go out in the future? Example:

<img width="735" alt="screen shot 2017-07-28 at 06 05 25" src="https://user-images.githubusercontent.com/5512652/28712867-cce9c40a-735a-11e7-97cc-7da86f084fb7.png">

That allows me to quickly scan my posts list and see where I've scheduled future shares without having to manually open the Share section for every post.

**Comment by gziolo** [comment]
It's being worked on  in #18048.

**Comment by iamtakashi** [comment]
Thanks for bringing this up. However, I don't think adding a count number there is a good solution because it doesn't have enough context to it. 

> there's no single place where I can see all of my scheduled shares. I have to open up the Share section under each blog post to see if I have any.

Do we hear this feedback as an issue from the customers often? If yes, I wonder if it's a good time to start to think about having a large calendar in Calypso that displays all published and scheduled posts and shares. I've heard this idea more than a few times.

**Comment by aheckler** [comment]
> Do we hear this feedback as an issue from the customers often?

I haven't heard it daily or anything like that, but it does come up occasionally.

**Comment by gziolo** [comment]
@iamtakashi or @folletto, what if we would use a different icon (calendar?) with a small number on the bottom right of the icon to give it some context. Something like, but a bit nicer:

![screen shot 2017-09-29 at 08 13 03](https://user-images.githubusercontent.com/699132/31003164-656db7da-a4ee-11e7-8ff1-2e99301ac4a7.png)

**Comment by folletto** [comment]
I know it's a bit of a deviation, and I'm not sure if Takashi agrees, but I feel a good way to approach this would be to have the posts in a new tab like the "Scheduled" tab at the top, maybe even still "Scheduled" but with a different styling of the content. 

I'd also remind that it's far more important to update this page design — we need to move away from the way we are showing the posts in the list now and make it identical to the CPTs (which is the current design direction unless a new one comes up). If I had to spend time, I'd rather spend time to restyle that instead of tweaking this one that is meant to go away (soon, I hope).

**Comment by gziolo** [comment]
Fair enough @folletto. I'm closing the PR. It did a great job when I was teaching Calypso basics class. It can be now happily buried :)

**Comment by iamtakashi** [comment]
> I'd also remind that it's far more important to update this page design — we need to move away from the way we are showing the posts in the list now and make it identical to the CPTs

💯

**Comment by ockham** [comment]
I've started work toward harmonizing both views (at least from a technical POV), see e.g. #18113, #18034, and #18038.
