### ISSUE TITLE
Store: surface low inventory in dashboard

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#16732]
We should have an alert in the dashboard when a product has a low inventory.

**Comment by kellychoffman** [comment]
@jameskoster - do you want to design a card or notice for this?

**Comment by jameskoster** [comment]
Here's my proposed design;

![inventory](https://cldup.com/T9NHcm1xkx.png)

The settings probably aren't essential, but would be nice to have imo. The widget would scroll as necessary. 

In-situ:

![inventoryagain](https://cldup.com/TmBBfSvxGI.png)

**Comment by jameskoster** [comment]
Updated the design above to include an initial state which prompts users to specify their low stock threshold.

**Comment by kellychoffman** [comment]
Can you add a design for a single product being low on stock? I think the list view will be overkill for those instances.

**Comment by jameskoster** [comment]
> Can you add a design for a single product being low on stock? I think the list view will be overkill for those instances.

Couple of options:

![single](https://cldup.com/8aQ-rYmghn.png)

Show a sentence with some contextual info to create the necessary urgency to restock.

Or just keep list view but display x products approaching low stock so the store owner can pro-actively restock those as well if desired.

**Comment by kellychoffman** [comment]
> Or just keep list view but display x products approaching low stock so the store owner can pro-actively restock those as well if desired.

That's an interesting idea. I think we can go with this for now and make a single product low in stock card in the future if its needed.

**Comment by timmyc** [comment]
I'm getting started on this task, and just wanted to clarify a few things. Screen grab from wp-admin for reference:

![woocommerce_settings_ _care_for_animals_ _wordpress](https://user-images.githubusercontent.com/22080/32078229-0b13d382-ba5b-11e7-9ca9-0d34f214f2c9.png)

If "Enable Stock Management" is false/off - should this widget not display at all?

Also verifying that the Email checkboxes map to those in the screenshot above for enabling low stock / out of stock notifications.

And lastly the low stock threshold is the same setting used here correct?

**Comment by timmyc** [comment]
Hey @jameskoster / @kellychoffman - I am working on this locally now, and I think since the designs were done, things have changed a bit in dashboard-land. Specifically the Reviews widget has been added, so I'm a bit unsure of _where_ this inventory widget should live. For reference, here are the 3 states that I'm currently seeing in the dashboard:

__New Orders & New Reviews__
![orders-reviews](https://user-images.githubusercontent.com/22080/32242097-219239a0-be2f-11e7-9f32-ac12ff9f0091.png)

__No Orders & No Reviews__
![no-orders-no-reviews](https://user-images.githubusercontent.com/22080/32242135-3eea2076-be2f-11e7-8d84-077d234f85fe.png)

__No Orders & Review__
![no-orders review](https://user-images.githubusercontent.com/22080/32242149-4979cdc0-be2f-11e7-9b53-7240cabd1f3c.png)

I will just place it in it's own widget row for now, but please let me know where it should live, and which state(s) it should be shown in. Thanks!

**Comment by jameskoster** [comment]
Hmm, I've been thinking about this for a while and feel we're quickly approaching a stage where we need a dashboard widget component. Would now be a good time to work on that @timmyc?

I'm thinking of a component that is size agnostic (IE it can be full width, 1/3 width, 1/2 width, etc). It should have a title, unique content and an optional image. I'm anxious the dashboard is already starting to look a little messy. The component would provide consistency and flexibility.

If that's not something we want to work on yet I'd say;

* For "Orders + Reviews" let's make the reports widget 2/3 and put the stock notification to the right of it.
* For "No Orders" Let's replace the stats call-out. Stats aren't so useful without orders xD

**Comment by timmyc** [comment]
I think we do have a `<BasicWidget />` already [#](https://github.com/Automattic/wp-calypso/blob/master/client/extensions/woocommerce/components/basic-widget/index.js) but sounds like you are looking for something a bit more than that.

I'm fine with working on that as a stepping stone to this feature... seems like we either do it now, or come back and re-visit the inventory widget afterwards. A few other ideas on the topic:

- Do we allow users to hide/close dashboard widgets that are not of interest to them?
- Old Stats on wpcom allowed users to customize their stats page by drag/drop re-arranging stat panels... maybe that would be an interesting concept eventually for the store dashboard too.

**Comment by jameskoster** [comment]
> Do we allow users to hide/close dashboard widgets that are not of interest to them?

> Old Stats on wpcom allowed users to customize their stats page by drag/drop re-arranging stat panels... maybe that would be an interesting concept eventually for the store dashboard too.

We had an initial design that allowed this, but now I think we should wait and see how folks use the dashboard as we supply it and potentially do some user testing. My gut tells me people will want to customise, but if that turns out _not_ to be the case then we'll save a lot of headaches by not allowing any customisation.

**Comment by jameskoster** [comment]
Design ideas shared in p90Yrv-l6.

**Comment by ryelle** [comment]
This widget was added in #23347 & #23410; closing this issue
