### ISSUE TITLE
Store: Hide Store (BETA) link based on previously provided address

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#16758]
Users outside the US or CA can still see the `Store (BETA)` link. We are not currently limiting the link based on anything. Similar to #16432, we could infer based on their previous provided address (during the domain/AT setup flow) if we should show the link during this launch period or not.

This will help prevent other users from getting confused about the store link, and then realizing they can't use it.

See p90Yrv-1D-p2.

**Comment by coderkevin** [comment]
So, after doing a bit more research on the topic, I've learned a bit more. I wrote a postmortem: p4TIVU-7yw-p2

1. The original issue with this PR can be fixed with a bit more code added to it. Although it won't be ideal, it can be good enough for what we need for now.
2. WHOIS registration data is frequently deliberately falsified by people when registering their domains, so this address may be incorrect.
3. It was recommended to use billing address information instead.
4. However, billing country information is not necessarily reliable either, and will take a bit of work to get to.

So, the way I'm thinking of going on this is as follows:

1. Keep with using whois address data.
2. Add code to ensure it doesn't repeatedly send requests, even though the component may be created and mounted multiple times.
3. Inform our HEs that the "Store (BETA)" link only shows up if the WHOIS address is US or Canada, and if someone's feels they should see it and they aren't, advise them to ensure their WHOIS address is correct.

**Comment by coderkevin** [comment]
After further discussion, we'll use a GEOIP approach here: D6669-code

**Comment by coderkevin** [comment]
The GEOIP PR was merged, but @budzanowski reported that he still saw the Store link, and that his GEOIP country in redux was showing as US.

**Comment by coderkevin** [comment]
@justinshreve can you help look into why it would be reporting as US?

**Comment by justinshreve** [comment]
@coderkevin - was he proxied or had a cached value from  before? Danny said the same thing but when using the dev console unproxied he correctly got 'ES'.

**Comment by justinshreve** [comment]
Some discussion in Slack earlier: p1501843595741138-slack-woocommerce-on-wpcom.

**Comment by justinshreve** [comment]
See p4TIVU-7BK-p2

**Comment by timmyc** [comment]
Closing in favor of #20607
