### ISSUE TITLE
Can't access Store menu from homepage

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#16812]
#### Steps to reproduce
1. Starting at the homepage of your Atomic WooCommerce store
2. Select My sites to open the WP side menu
3. No store option
4. Select any option to open Calypso
5. Store (beta) side nav option appears 

#### What I expected
Store (beta) menu option to always be available 

#### What happened instead
I had to enter Calypso in order to see it. Couldn't access Store from the homepage. 

#### Browser / OS version
Chrome Version 59.0.3071.115 (Official Build) (64-bit) / MacOS 10.12.5

#### Screenshot / Video
http://cld.wthms.co/dAwWcv

#### Context / Source

#manual-testing #pain-point

**Comment by justinshreve** [comment]
From looking around a bit, it looks like these menus are controlled by Jetpack:
https://github.com/Automattic/jetpack/blob/01e305626497857bc905c577b112abd807954997/modules/masterbar/masterbar.php

@vindl (pinging since it looks like you have worked on that file) Would it be possible to get some hooks added to the menu areas so that we could hook in and add the `Store` link when appropriate from one of our Store plugins?

Right now we are showing the link to a small amount of AT users, so just adding the link to the masterbar directly isn't an option right now.

**Comment by vindl** [comment]
@justinshreve I think adding a hook to conditionally display Store item should be straightforward. I'm not sure how to determine which AT users should see it on Jetpack side - is this something you can detect in one of your Store plugins?

**Comment by timmyc** [comment]
+1 on this - I just was about to log the same issue then found this one.

**Comment by justinshreve** [comment]
A hook we can use has been merged.

**Comment by timmyc** [comment]
FYI this is now live on store sites @msdesign21
