### ISSUE TITLE
Jetpack Security: Protect/Scan/Monitor could each use 'badges'

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#169]
From @rickybanister: The Protect, Scan, and Monitor blocks at /settings/security look pretty monotonous and somewhat confusing (what's the difference between these three things?).

It would be nice if we created three badges that differentiate the three security features at a glance.

Perhaps the badges are dimmed until the feature has been enabled, then it would be fully lit up.

I'm thinking something like this, but with shield/lock/security-camera type imagery:

Here's what it looks like now on desktop:

![screen shot 2015-11-19 at 9 14 39 am](https://cloud.githubusercontent.com/assets/11487924/11272873/fabeeeda-8e9d-11e5-8dd3-2dc78bb98968.png)

And smaller screens:

![fireshot capture 11 - site settings t_ - https___wordpress com_settings_security_testingnstuff com](https://cloud.githubusercontent.com/assets/11487924/11272902/2291edf4-8e9e-11e5-8812-6bea89343854.png)

Ideas from @drw158: Here's what I have so far for Protect and Monitor. Still working on Scan and the colors. 

![](https://cloud.githubusercontent.com/assets/618551/8788568/eb857c06-2f00-11e5-832a-6a404301de0b.png)

I think making the monitor more like a square helps making it easier to use.

Mockup from @rickybanister: 

![](https://camo.githubusercontent.com/256ab2a21835521727780168a306dd050626e0a4/68747470733a2f2f636c6475702e636f6d2f565f4c677259304556692d3330303078333030302e706e67)

Note from @kellychoffman:

At first glance the scan looks like an error. Maybe another icon there? Removing the red color might help too. Also did a quick sketch for another option: 

![](https://cldup.com/pYY9KG3esa-3000x3000.jpeg)

**Comment by designsimply** [comment]
Tested and the Settings > Security > Protect/Scan/Monitor badges appear to be in place:

![screen shot 2016-04-21 at 09 24 22](https://cloud.githubusercontent.com/assets/1119271/14716721/21215e54-07a3-11e6-972e-6e0e3fa8d1d4.png)
<sup>Seen at https://wpcalypso.wordpress.com/settings/security/wildly.disambiguously.com using Firefox 45.0.1 on Mac OS X 10.11.13</sup>

Closing because the main issue is resolved but also pinging @drw158 for the nitpick about the Jetpack Scan badge looking like an error—@drw158 would you like a new issue to be opened for that?

**Comment by drw158** [comment]
@designsimply not unless we get another report about it
