### ISSUE TITLE
Login Password is Visible by Default on Mobile Site

### ISSUE THREAD

**Issue by wesdawg** [Automattic/wp-calypso#16929]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/log-in
2. Enter a password into the field.

#### What I expected
Password is hidden by default.

#### What happened instead
Password is visible as text

#### Browser / OS version
Chrome Mobile on Android

#### Screenshot / Video
<img width="1280" alt="screen shot 2017-08-04 at 2 19 18 pm" src="https://user-images.githubusercontent.com/5124946/28981545-2a769042-7920-11e7-8113-607e88486d25.png">

**Comment by designsimply** [comment]
Related: #9472

**Comment by designsimply** [comment]
Tested and confirmed using Chrome on Pixel, Android 7.1.2.

<img alt="screenshot_20170804-141647" src="https://user-images.githubusercontent.com/1119271/28985460-d847ea8c-791f-11e7-9e74-8cb4e6961069.png" width="270" />
<sup>Seen at https://wordpress.com/log-in using Chrome on Pixel, Android 7.1.2.</sup>

**Comment by designsimply** [comment]
@wesdawg, thank you for reporting the issue! 

I researched this and found that we show passwords by default on mobile for a few reasons, the main ones being that obfuscating passwords optimizes for 0.01% of use cases (someone looking over your shoulder actively trying to steal your password) and hampers usability. Also, since there is a toggle, then you do always have the option to hide the password if you want to as soon as you notice it is visible.

Related reading: 

> We decided to optimize for usability and ease of log in over questionable security increases. On a touchscreen phone, its trivial to move the device out of sight of prying eyes. Or easier still to simply hit the Hide action to obscure a password.
> 
> But not that it matters, there’s a visible touch keyboard directly below the input field that highlights each key as you press it. These bits of feedback show the characters in a password at a larger size than most input fields. So in reality, the •••• characters aren’t really hiding a password from prying eyes anyway. As a result, we opted for usability improvements instead.

— https://www.lukew.com/ff/entry.asp?1653

**Comment by wesdawg** [comment]
Thanks for the info!
