### ISSUE TITLE
Post-post: Loading message shows 'new post' after updates to existing posts.

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#17015]
I noticed that when updating existing posts, the post-post preview loads with a loading message that suggests the post is 'new'.

Note, the post was published 10 months ago:
![screen shot 2017-08-08 at 19 15 29](https://user-images.githubusercontent.com/4335450/29090277-e8a2981e-7c76-11e7-869f-edb2340f2016.png)
![screen shot 2017-08-08 at 19 16 20](https://user-images.githubusercontent.com/4335450/29090275-e870512e-7c76-11e7-9145-631a2a6b87d8.png)

A simple solution might be to do a quick check to see if the post is new or not, displaying a more relevant message if it's not.

However, @mcsf had a good point to about custom post types in the above scenario - including 'post' in the loading message may not make sense for some post-types and to include the user defined post type in a localised, interpolated string is likely to create situations where a string contains both the translated language and the language that the custom post type was defined in.

For that reason, something very general could be a better option, 'loading' for instance would be subject to much less nuance.

@mcsf, please correct me/elaborate on this if I've got details wrong or missed out something important :)

**Comment by mcsf** [comment]
I am in favor of something vague like "Loading" because of both i18n and custom post types (CPTs). Indeed, in the context of i18n we must always work with a finite set of full strings:

- _Loading your post_
- _Loading your new post_
- _Loading your page_
- _Loading your new page_
- _Loading your portfolio_
- _Loading your new portfolio_

… meaning we would require CPTs to implement (yikes) these particular strings, and subsequently translators to translate these into every locale. This is because working with string fragments is the *worst* idea — _e.g.,_ `translate( 'Loading your new' ) + post.type.label` is not acceptable, as it will break for many languages due to inflexion mechanisms _et al._.

This obviously doesn't forbid a hybrid approach (specifying the type in the string if `{ post ; page } ∋ type`), but I'd personally keep it simple.

**Comment by alisterscott** [comment]
We no longer show post previews for updating existing posts so closing this out
