### ISSUE TITLE
Store: Display message for existing WooCommerce sites if set to a country we don't support

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#17027]
We have taken a few steps to reduce confusion for stores outside of US & CA (like #16885) and a search for a solution at p4TIVU-7BK-p2.

However, p90Yrv-1D-p2 #comment-10 shows that an existing WooCommerce user that happens to be on AT could still stumble upon the interface because they wouldn't see the setup screens.

It seems like we should return a message about the interface not being available yet if we detect their `woocommerce_default_country` setting to be another country.

cc @kellychoffman

**Comment by jameskoster** [comment]
How about we disable the Store UI in Calypso in these cases and display an overlay explaining the situation. 

We could include an email signup form with country dropdown so that we can notify people when the interface is ready for them. We can also provide a link back to wp-admin.

Something like:

![denied](https://cldup.com/N5xH9joTn1.png)

**Comment by kellychoffman** [comment]
I love it!

Should we say 'return' to wp-admin if they didn't originally come from there?

**Comment by jameskoster** [comment]
Yeah I was unsure about that link. It probably shouldn't be external either. Hmm. Perhaps just "Manage store in wp-admin"?

**Comment by kellychoffman** [comment]
Hmm, this is tricky. Should we even have it? I wonder if creating a store in wp-admin would turn some non technical users off from Store completely??

**Comment by jameskoster** [comment]
I thought the only people who saw this were existing AT users who are running a store out of a non US/CA country and stumble across the "Store BETA" link (or visit a store url directly) when they're in Calypso?

**Comment by kellychoffman** [comment]
Ah, I see what you mean. Yeah, we should keep it then.

**Comment by justinshreve** [comment]
The mockup here looks good to me. We'll need to figure out what list to sign them up to. Otherwise, we could start with a simpler message minus the sign-up.

**Comment by jameskoster** [comment]
Perhaps @avivapinchas or @MarinaWoo will be able to suggest a list.

If not then;

> We could start with a simpler message minus the sign-up.

Sounds fine to me.

**Comment by kellychoffman** [comment]
It should probably be a "WP.com branded" list? (for lack of a better term) @joanrho @fditrapani do you have any suggestions here or have you done something similar in the past?

**Comment by fditrapani** [comment]
@kellychoffman I haven't done something like this in the past so I'm not sure which lists we have to start with. I would imagine we'd want to create a new list so we can target these people specifically with a WP branded email when the store is available in their country.

**Comment by avivapinchas** [comment]
@jameskoster @kellychoffman Since these folks are 'running a store' via AT, wouldn't they already be using WooCommerce, just not managing it in Calypso? 

If so, I suggest we put these in our main list on MailChimp, and have fields on that list that indicate location and their signup source. That way, we can still communicate other WooCommerce info with them, like relevant extensions and such, that might be relevant.

**Comment by justinshreve** [comment]
@kellychoffman This specific case was for people who did install WC themselves. They should be able to upload plugins/extensions via zip -- though I agree that is not the experience we want to push for AT users.

**Comment by jameskoster** [comment]
I'm not sure the main list is relevant enough in this context. The idea was to let folks know explicitly when they can start managing their store in Calypso (IE when we add support for their location).

Maybe it would be worthwhile to create a list for our biggest WC user locales outside of the US/CA? And display a signup form for that based on the store location setting. For more obscure places just leave the signup form off.

**Comment by avivapinchas** [comment]
> I'm not sure the main list is relevant enough in this context. The idea was to let folks know explicitly when they can start managing their store in Calypso (IE when we add support for their location).

I hear you - but by not adding them to a list where they'll start getting some communication, we're losing the opportunity to start a relationship with them. 

> This is definitely a nice to have though. Leaving it off entirely isn't gonna be a big deal, if it's a lot of work to orchestrate.

Including them on the main list would be a bit easier because that's the list we actively maintain, meaning all the proper settings are already defined and so on. 

> They would technically be able to upload plugins/extensions via zip -- though I agree that is not the experience we want to push for AT users. 

This is a solid point - but it feels like a shame for AT users to miss out on what WooCommerce can do via extensions and so on in the meantime. It's likely (I think, correct me if I'm off base) that for a while, we'll launch new features as extensions, and AT users should have the opportunity to use those as quickly as they would if they were on a different host. Ideally, they should have a _better_ WooCommerce experience as an AT user than somewhere else, which would mean extensions.

**Comment by justinshreve** [comment]
We currently have a version of this live minus the email:

<img width="1345" alt="screen shot 2018-03-07 at 2 38 22 pm" src="https://user-images.githubusercontent.com/689165/37122389-3eea3878-2215-11e8-9668-d1f9b6476d8b.png">

Do we want to keep this issue open to support a mailing list? Or will we notify AT WooCommerce users a different way? (Notification, banner, pull a list of emails ...)

**Comment by timmyc** [comment]
I think it is fine as-is personally. We could always potentially add a notice in wp-admin via calypso-bridge when more country support is added.

**Comment by kellychoffman** [comment]
Yeah, +1 I say fine as is.

**Comment by justinshreve** [comment]
I think we can go ahead and close this one out then.
