### ISSUE TITLE
Comments: page transition on mobile sometimes shows previous page

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#17075]
On an iPhone on any browser try navigating from the /stats page click on comments in the sidebar. We'll see a flash of the previous page during the transition. Originally reported in p58i-6u5-p2#comment-36443

**Comment by Copons** [comment]
Unrelated to the iPhone issue, but I think I introduced an issue in #16969 where we somehow redirect to `/stats` too aggressively.
Maybe it's caused by the fact that we check that capability before it's actually loaded?
Not sure, though, I believe we might want to work on both issues together, them being related to the router.

**Comment by gwwar** [comment]
The redirect bug is fixed by #17115

**Comment by gwwar** [comment]
So probably due to us removing the sidebar before redirecting.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES

_With a brief check on my mobile (iPhone XR v iOS 16.5.1), there isn't any obvious flash of a previous page, so this may have also aged out by now. 👍_
