### ISSUE TITLE
.fr: Update confirm-cancel-domain for non-ICANN domains

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#17124]
The text on the confirm cancel screen is incorrect for .fr domains. It's not clear whether .FR domains prevent transfers inside 60 days, but they are definitely not bound by ICANN.

![purchases_ _cancel_domain_ _wordpress_com](https://user-images.githubusercontent.com/5952255/29200977-56a0fa90-7e9d-11e7-9ddc-2eecd02fd216.jpg)

**Comment by hewsut** [comment]
Not only that--isn't this copy a little off the mark generally?

I mean:
1. I want to transfer.
2. I've attempted to cancel my domain instead.
3. I've selected the reason as shown above indicating that I'm actually trying to transfer.
so...
4. Shouldn't it redirect the user to the transfer UI? Instead of an ICANN lecture?

**Comment by hewsut** [comment]
Maybe something like this for all types of TLDs?

![screen shot 2017-08-14 at 3 01 32 pm](https://user-images.githubusercontent.com/2006764/29286849-7e898494-8101-11e7-89da-370938e2a1cc.png)
