### ISSUE TITLE
Store Stats: Nest Net Sales in Gross Sales

### ISSUE THREAD

**Issue by greenafrican** [Automattic/wp-calypso#17163]
Currently, Gross and Net Sales each have their own tab. The The Net Sales can be nested on the Gross Sales. This will free up the tab and I think makes sense.

**Comment by iamgabrielma** [comment]
For visual reference, going to https://wordpress.com/store/stats/orders/day , it can be seen as follows:

<img width="865" alt="screen shot 2017-08-31 at 17 55 53" src="https://user-images.githubusercontent.com/3812076/29932847-c4bd5518-8e75-11e7-8fe7-5fd8376531c8.png">

Following the same rationale, we could do the same with `orders` and `average order value` , right?

**Comment by psealock** [comment]
By looking at Site Stats, which have visitors nested in views, the views tab still exists.

Removing "Net Sales" tab can work for us, but it means introducing possibly 2 other features.

1. Tooltip - This would be a must, otherwise Net Sales aren't discoverable in precise amounts. Keep in mind the experience on mobile is less than ideal, but maybe thats ok.

![screen shot 2017-10-26 at 4 13 15 pm](https://user-images.githubusercontent.com/1922453/32033342-9fdf3d50-ba68-11e7-8d31-273620f0762c.png)

2. Toggle - This isn't too useful.

![screen shot 2017-10-26 at 4 10 47 pm](https://user-images.githubusercontent.com/1922453/32033349-a980bd52-ba68-11e7-8dbc-e1e836330a02.png)

**Comment by psealock** [comment]
@iamgabrielma

>Following the same rationale, we could do the same with `orders` and `average order value` , right?

I don't think it would work because Orders and Average Order Value different scales (integers and $ value).

**Comment by greenafrican** [comment]
> Tooltip - This would be a must

Yup. Seems like a good idea even with just the single series. Should we use the same tooltip from Site Stats? It looks pretty good.
