### ISSUE TITLE
Media: selections are not cleared

### ISSUE THREAD

**Issue by nosolosw** [Automattic/wp-calypso#17240]
Steps to reproduce:

* Go to media library.
* Select a couple of items.
* Go to settings and click "change site icon".
    * It opens a modal media library with the selection of items in the step before.
    * If I click continue and compose a gallery, upon finishing I'm redirected to the image editor for the site icon.

The same happens if I choose to change the featured image in a post immediately after selecting some items in the media library.

The expected behavior is that selections are cleared before opening the featured image and site icon modals - these modals don't accept selection of multiple items.

**Comment by sabrown84** [comment]
Hi @nosolosw I'd like to try this one. Is there anyone working on it already?

**Comment by nosolosw** [comment]
Not that I know of @sabrown84 Go for it!

**Comment by sabrown84** [comment]
@nosolosw I think I understand what the expectations are for this one. Do you have any suggestions on where to start to solve this?

**Comment by nosolosw** [comment]
That's great! I don't have any suggestions off the top of my head. Are you familiar with the Flux stores in place? If you haven't the chance yet, you may want to check [our approach to data](https://github.com/Automattic/wp-calypso/blob/9d57ad7e8379aa45831acd978ee9b8f7bd27e81f/docs/our-approach-to-data.md) and [Media specific stores](https://github.com/Automattic/wp-calypso/tree/9d57ad7e8379aa45831acd978ee9b8f7bd27e81f/client/lib/media).

**Comment by sabrown84** [comment]
@nosolosw I am having trouble trying to fix this because I'm pretty new to React. Trying to clear the selections, but should I work on this through the [Media specific stores](https://github.com/Automattic/wp-calypso/tree/9d57ad7e8379aa45831acd978ee9b8f7bd27e81f/client/lib/media) or the [Media-modal](https://github.com/Automattic/wp-calypso/tree/9d57ad7e8379aa45831acd978ee9b8f7bd27e81f/client/post-editor/media-modal) ?

**Comment by jdlrobson** [comment]
I'm pretty new to this codebase but having fun exploring :) I can submit a patch, but I don't want to step on @sabrown84 toes if she's still working on it (please feel free to do so based on my investigations if you'd like to)!

I can see 2 ways to solve this which I believe is what @sabrown84 was getting at....

1) Currently EditorMediaModal clears the selected items in componentWillMount. Seems to be a problem in that logic there (or the reducer) as the `view` becomes `null` in this workflow (as a call to [resetModalView action is made](https://github.com/Automattic/wp-calypso/blob/master/client/state/ui/media-modal/actions.js#L35) and the clear [only happens if it's ModalView.LIST](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/media-modal/index.jsx#L133). and the SiteIconSetting [doesn't specify ](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/site-icon-setting/index.jsx#L314) the view prop.

2) Alternatively, the Media component when unmounted could clear all selections - I'm not sure however if persisting selected across views is intentional however.

Solution 1 seems to make sense to me - I think this is an error in EditorMediaModal. It can be fixed either by checking if the view prop is null; checking the single prop or making it impossible for this to be null. The `single` prop seems to make the most sense to me (I'm not sure why view matters in this context... ).

**Comment by rachelmcr** [comment]
Closing as resolved in https://github.com/Automattic/wp-calypso/pull/22118.
