### ISSUE TITLE
Activity log: Monthly view not showing the right events

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#17285]
I tried the monthly view an something went wrong. 
I was seeing the placeholder and clicked on the nav bar.
See 
<img width="1103" alt="screen shot 2017-08-17 at 07 22 45" src="https://user-images.githubusercontent.com/115071/29417224-5109caba-831d-11e7-9e3f-1073193e8875.png">

**Comment by sirreal** [comment]
I've located the problem.

It has to do with parsing strings in moment. It only occurs when we pass a `startDate`.

It happens now because we parse the string _then_ apply the site offset. In the case of the size in the capture, this means subtracting seven hours. Then we try to find the start and end of that month, and we wind up in July.

Fixing is trivial when we know the site timezone. I'm having more difficulty supporting the case where we only know the offset 🤔 

```js
parseInZone( dateString ) {
	const { moment, timezone, gmtOffset } = this.props;
	if ( timezone ) {
		return moment.tz( dateString, timezone );
	}
	if ( gmtOffset ) {
		return 😱 ;
	}
	return moment.utc( dateString );
}
```
