### ISSUE TITLE
Activity Log: disable pagination beyond first event's month

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17287]
We should be getting the first event's date from the API so we can hide the left hand-side arrow for the month prior to that first event.

### Mock

![image](https://user-images.githubusercontent.com/390760/29418282-d39d2a30-8363-11e7-842a-66843b0d6d3c.png)

**Comment by sirreal** [comment]
Related to #17298 and 64-gh-action-to-activity-log

Should we show some kind of text at the bottom when we get to the end?

![oldest](https://user-images.githubusercontent.com/841763/29453996-e5436058-840b-11e7-9d54-80e232457fbb.png)

_Note:_ The actual text in the image may not be appropriate because activity does not necessarily mine backup and vice versa.

**Comment by keoshi** [comment]
Sounds like a great idea — yes, please! How will it look with the text _and_ the bottom navigation, though? We might have to increase the spacing between them to avoid clashing.

**Comment by sirreal** [comment]
> How will it look with the text and the bottom navigation

I was thinking of showing the just bottom nav _or_ just the text on the last month, but now I realize that doesn't make much sense because you still need the forward arrow to advance again 😕  🤔 

I'm not sure right now.

---

Set status to blocked waiting for resolution on 64-gh-action-to-activity-log
