### ISSUE TITLE
Reader: following a new site doesn't show site immediately in followed sites list

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#17316]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/following/manage
2. Add URL of site to follow
3. Click follow

#### What I expected

Site to appear in list of followed sites

#### What happened instead

Site shows as loading (placeholder) until page is re-loaded, or scroll down and come back up (see animation below)

#### Browser / OS version

Chrome/Safari macOS

#### Screenshot / Video

![follow new site](https://user-images.githubusercontent.com/128826/29443591-8f74428a-841c-11e7-9744-4cda7f6cfebb.gif)

#### Context / Source
#dogfooding

**Comment by fraying** [comment]
Confirmed. I tried following a URL and the placeholder never resolved.

Any ideas, @samouri?

**Comment by brbrr** [comment]
This issue is reproducible only with `Follow #{site}` button. Following via right side button works fine

![screencast 2017-10-31 14-50-50](https://user-images.githubusercontent.com/5654161/32224722-3e2fd808-be4b-11e7-8378-ef49765ac3c9.gif)

**Comment by bluefuton** [comment]
Seems to be caused by the feed URL subscribed to and the actual feed URL differing. For example, following `pinkbike.com` where the resulting feed URL received from the API is `http://www.pinkbike.com/pinkbike_xml_feed.php`.

In this case, we delete the old URL key in the reducer, and add the new one. The subscription list doesn't seem to get re-rendered in this case (the placeholder is still holding out for details on 'http://pinkbike.com', which never arrive).

**Comment by bluefuton** [comment]
Likely related to #22312.

**Comment by bluefuton** [comment]
@samouri I think this may be related to the `connectSite` higher-order component. After subscribing by URL, the subscription renders:
- once with minimal details before the API call (placeholder shown)
- once with more details from the API response (placeholder still shown because `feed` and `site` missing)

I'd expect a third re-render after the `feed` and `site` arrive, but that never happens.
