### ISSUE TITLE
Can't Change to "Public" from "Hidden" on Privacy Setting

### ISSUE THREAD

**Issue by kristenwomack** [Automattic/wp-calypso#17359]
Steps to Reproduce
1. Starting at URL: https://wordpress.com/settings/general/<clientSiteURL>
2. Scroll down to "Privacy"
3. Select "Public"
4. Save Settings

I expect the setting to be saved as public. Even though I get a "Settings saved!" message, when I try to navigate way from the page I get an error message saying the changes are unsaved.

![image](https://user-images.githubusercontent.com/5034778/29481186-f559447a-8443-11e7-9399-93b2d11f81af.png)

![image](https://user-images.githubusercontent.com/5034778/29481182-ecbf2df2-8443-11e7-8782-083527257643.png)

![image](https://user-images.githubusercontent.com/5034778/29481204-1958038e-8444-11e7-9416-c1ba6aba9239.png)

As a result the site is hidden. 
![image](https://user-images.githubusercontent.com/5034778/29481221-48cc8bee-8444-11e7-8ff5-cf093eef9c63.png)

I tried to disconnect and reconnect JetPack to fix a RPC XML file issue which I thought was the root cause of this issue. After resolving the JetPack connection, this privacy setting still won't save.

#### Browser / OS version
chrome / macOS Sierra v10.12.6

**Comment by rachelmcr** [comment]
@kristenwomack Thanks for reporting this issue! I tested on a site using Jetpack, and I was able to switch the privacy setting between "Public" and "Hidden" without any issue. I confirmed that the change was reflected on the site.

Since this seems to be an issue specific to your site, please reach out to our Jetpack support team and we can investigate your site in particular to see what's going on there:

https://jetpack.com/contact-support/
