### ISSUE TITLE
Jetpack Scan: do not show saved password in plaintext when editing settings

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#174]
After entering my SSH username and password and establishing a connection, I can click on 'Edit Settings' and see my SSH password in plaintext.

Step 1: save SSH username and password
Step 2: click on 'Edit Settings'

![jetpack-scan-edit-settings](https://cloud.githubusercontent.com/assets/11487924/8658259/bc32045a-2970-11e5-8319-655798463daa.png)

Step 3: see password

![jetpack-scan-password-in-plaintext](https://cloud.githubusercontent.com/assets/11487924/8658279/dc43d62e-2970-11e5-8913-e08da3ceeb7b.png)

**Comment by designsimply** [comment]
@v18, can you please include steps to reproduce this issue? I'm having trouble figuring out how to activate Jetpack Scan.

**Comment by designsimply** [comment]
Note: testing this requires that you have ssh access to your Jetpack site by password and no key.

I tried testing Jetpack Scan setup using a site hosted at SiteGround but was unable to get it to work because an ssh connection to shared hosting on SiteGround can only be established with a key and there is not currently an option for that in Jetpack Scan.

See #4950
