### ISSUE TITLE
Comments: Navigation bar menu doesn't automatically close anymore

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#17422]
When toggling comment status on smaller screens the dropdown menu persists after selecting particular category and switching to it.

<img src="https://user-images.githubusercontent.com/1182160/29531030-029c08d8-86a7-11e7-946a-728a3d3ac696.png" width="400px">

Props to @vindl for [catching this](https://github.com/Automattic/wp-calypso/pull/17304#issuecomment-323804787)!

**Comment by gwwar** [comment]
Is this specific to certain devices? I wasn't able to reproduce on a Nexus 5.

**Comment by vindl** [comment]
@gwwar this was somehow introduced in bulk edit PR, so you won't be able to reproduce it in production, only in `dev` or `wpcalypso`.

**Comment by kwight** [comment]
I took a look a this, but couldn't figure it out. It's definitely related to the bulk edit merge in #17304 and not present in production, but I can't tell what in that PR would cause such a problem. Seems like `toggleMobileOpenState` should be firing?

**Comment by vindl** [comment]
After enabling the bulk edit flag we introduced a new child component to SectionNav [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment-navigation/index.jsx#L200). By default it automatically closes the panel on mobile screens, but only if it contains no more than 1 control group, with the exception of `Search` which is explicitly allowed as second control group. In order to resolve this issue I added our `CommentNavigationTab` as another exception to this rule.

In order to verify this you can insert `CommentNavigationTab` bellow `SectionNav` and check that auto closing works. After that you can also replace [hasSearch](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment-navigation/index.jsx#L207) with `true` and verify that having this component nested in `SectionNav` will not break auto closing functionality.
