### ISSUE TITLE
Feedbacks: don't show Add button in sidebar or main post area

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#17437]
Raised with internal #dogfooding #real-life use by @pmaiorana 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/types/feedback/example.com
2. Look at sidebar, see "Add" next to "Feedbacks"
3. In the main post area, under "No feedback found" you'll see "Add New Post"

#### What I expected
Not to see these Add links or buttons at all.

#### Screenshot / Video
![screen_shot_2017-08-22_at_08_42_34](https://user-images.githubusercontent.com/66797/29574329-1385f2d4-8716-11e7-88ff-c0fa906d3ec3.png)

**Comment by beaulebens** [comment]
Note this is specific to the `feedback` CPT added by Jetpack/WP.com.

**Comment by iamgabrielma** [comment]
> Note this is specific to the feedback CPT added by Jetpack/WP.com.

I had problems trying to reproduce this, because the feedback module is not showing up in calypso if the site is non-Atomic, only Atomic sites display it. Is this expected? Example:

- Site: freetestsiteiamgabrielma.wordpress.com
- Theme: Twentyseventeen

The Feedback module was not showing up, but it shows up via wp-admin, I figured that maybe if there's no feedback or contact requests, the module doesn't appear, so I created a new post, added a contact form and send a test request:

Calypso view (nothing changed):
<img width="946" alt="screen shot 2017-08-29 at 19 15 18" src="https://user-images.githubusercontent.com/3812076/29834214-70510d18-8cee-11e7-990d-7e0ca496d0b3.png">

However the feedback can be seen via wp-admin under https://freetestsiteiamgabrielma.wordpress.com/wp-admin/edit.php?post_type=feedback and also received the email notification regarding this.

In an Atomic site, shows without a problem:
<img width="1042" alt="screen shot 2017-08-29 at 19 21 10" src="https://user-images.githubusercontent.com/3812076/29834486-40bb209c-8cef-11e7-938f-5fce715e870f.png">

**Comment by beaulebens** [comment]
I'm also not seeing it any more, although I'm not aware of a conscious decision to remove it for Jetpack sites.

There are a [number of checks](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/sidebar/manage-menu.jsx#L202) that could prevent it from showing up by the looks of it.

**Comment by pmaiorana** [comment]
I'm unable to reproduce it with test.paulmaiorana.com, but am still seeing it on paulmaiorana.com/notes -- both are .org sites connected to Jetpack. Not sure why I'm seeing different things :)

**Comment by pmaiorana** [comment]
It's also still an issue on Atomic sites.

**Comment by lancewillett** [comment]
Confirmed still an issue an by test Atomic site (using Safari 10.1.2 on OS X 10.12.6)

![screen shot 2017-09-08 at 09 25 34](https://user-images.githubusercontent.com/66797/30221335-b97d9822-9477-11e7-8094-6876d912f60f.png)

**Comment by KokkieH** [comment]
Just noticed this myself on a dotcom simple site. We probably also shouldn't show the Draft and Scheduled tabs for this content type, as these are contact form submissions, not content drafted by the site owner.

**Comment by KokkieH** [comment]
A Spam tab might be useful, though, as is available in WP-Admin. Contact form submissions are also filtered by Akismet, and the occasional false positive ends up in spam, but we don't indicate it anywhere here while we do for comments.

**Comment by arunsathiya** [comment]
I was able to use this option on my test sites and one of my user's sites.

#1637100-zen - In this specific case, clicking on `Add` shows a `You need a higher level of permission. Sorry, you are not allowed to create posts as this user` notice.

**Comment by torres126** [comment]
Separate issue for the Spam tab here: #30792
