### ISSUE TITLE
Stats: individual page stats view labels say "Post" instead of "Page"

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#17497]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/pages/example.com
2. Click the ... menu, it says View Page as expected.
3. Click on Stats in the ... menu, arriving at https://wpcalypso.wordpress.com/stats/post/1234/example.com
4. You'll see "Your post has not received any views yet!" and "View post" labels

#### What I expected
I expected to see "Your page has not received any views yet!" and "View page" here.

#### What happened instead

<img width="345" alt="screen shot 2017-08-24 at 07 14 04" src="https://user-images.githubusercontent.com/66797/29670645-23c813fc-889c-11e7-9ff7-ac1cc47e065a.png">

<img width="979" alt="screen_shot_2017-08-24_at_07_14_19" src="https://user-images.githubusercontent.com/66797/29670763-911c2aba-889c-11e7-8e61-5e071a2ea489.png">

#### Context / Source

Context: #flowsharing  #dogfooding

**Comment by rachelmcr** [comment]
I confirmed this behavior and found additional references to a "post" instead of a "page" when viewing the stats on a page with some views:

![screen shot 2017-08-24 at 3 53 14 pm](https://user-images.githubusercontent.com/8658164/29672605-a38c614a-88e4-11e7-9b16-60f1ddc00b87.png)

This destination (https://wpcalypso.wordpress.com/stats/post/1234/example.com) is also accessible for pages with views under My Sites > Stats by selecting a page in the "Posts & Pages" module.
