### ISSUE TITLE
Jetpack Scan: add a way to cancel editing settings

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#175]
After clicking on 'Edit Settings' it's not possible to leave the editing screen without either (1) saving the current settings again or (2) deactivating.

Here's the screen when clicking on 'Edit Settings':

![jetpack-scan-edit-settings-no-cancel](https://cloud.githubusercontent.com/assets/11487924/8658450/c901987a-2971-11e5-94ce-efab538dd464.png)

I suggest removing the 'Deactivate' link and replacing it with a 'Cancel' link (or something similar - maybe 'Cancel editing' for more clarity), like this:

![jetpack-scan-edit-settings-cancel-editing](https://cloud.githubusercontent.com/assets/11487924/8658472/f1f8ea58-2971-11e5-8907-df0e6af54c39.png)

There's a 'Deactivate' button on the main screen so it's still possible to deactivate.

![jetpack-scan-deactivate-link](https://cloud.githubusercontent.com/assets/11487924/8658487/08c08926-2972-11e5-8921-5dd61fc0156e.png)

**Comment by designsimply** [comment]
Closing because I was unable to reproduce the problem using the following testing steps:

1. Go to https://wpcalypso.wordpress.com/settings and select a Jetpack-connected site
1. Click Security in the header bar
1. Click Activate in the Jetpack Scan box
1. Look for a Deactivate button or link

Result: I only see a Cancel button at top right while editing or in first-time setup

![screen shot 2016-04-21 at 09 54 06](https://cloud.githubusercontent.com/assets/1119271/14717678/67ef6520-07a7-11e6-946e-ee528389aeba.png)
<sup>Seen at https://wpcalypso.wordpress.com/settings/security/wildly.disambiguously.com using Firefox 45.0.1 on Mac OS X 10.11.13</sup>
