### ISSUE TITLE
Jetpack Onboarding: Summary Next Step Links

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17650]
Change the summary links to point to actions outside the flow.

<img width="822" alt="screen shot 2017-08-30 at 1 56 01 pm" src="https://user-images.githubusercontent.com/22752103/29887331-12d931e0-8d8b-11e7-805c-81167215bfb7.png">

**Comment by ashleighaxios** [comment]
I believe we need to decide where we're pointing the user (Calypso, WP-admin…) before these can be added. Is that right? We want to be able to send the flow to any destination at the end, so I don't know if that leaves these links as something that are also technically adjustable based on who's sending customers through the flow. @eliorivero @rcoll @beaulebens

**Comment by beaulebens** [comment]
For _right now_ I think we can just send all links back to wp-admin so that we can get this shipped.

Ideally we'd have the ability to send in some sort of config at the very start of the flow (e.g. along with the `onboarding=1` link) that would indicate we want the final redirect to be Calypso, in which case when we get to this screen, we could just switch out all the `href`s for Calypso versions.

**Comment by tyxla** [comment]
Since users start this flow unconnected, a logical next step is to connect to Jetpack, which we added in #21332.

**Comment by tyxla** [comment]
We probably need to ditch the "Add a Store" link because we're offering to install WooCommerce in a separate step.

I'm also not sure how relevant the "Add a Site Address" link is.

Also, do we want to link to the creation of a new WP blog here?

Anyone got suggestions about what we could include there instead?

**Comment by MichaelArestad** [comment]
> We probably need to ditch the "Add a Store" link because we're offering to install WooCommerce in a separate step.

👍 

> I'm also not sure how relevant the "Add a Site Address" link is - we can't take advantage of the domain purchasing for Jetpack sites, can we?

@tyxla I don't think so. At least not yet. I think we can drop it for now.

> Also, do we want to link to the creation of a new WP blog here? It would totally take us out of the context IMHO.

Is that what start a blog does? I assumed it would walk them through making a blog post, not making a new blog.

> Anyone got suggestions about what we could include there instead?

Add additional pages
Write your first blog post
