### ISSUE TITLE
Videopress Stats Counts Plays When You View the Video in the Media Library

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#17728]
I had a user mentioning that their videos have stats while these videos are not added to any page or post. Upon taking a further look, it seems that the VideoPress stats count in when you yourself view the video in the Media Library (even though your site is not set to private).

#### Steps to reproduce
1. Upload a video to the Media Library
2. Refresh your page or log in/log out of your account
3. Go to My Sites - Media
4. Select the uploaded video, click "Edit" and play the video: https://cloudup.com/cDHJcH1BrQm
5. Refresh the page/log out and in your account
6. Go to My Sites - Stats

#### What I expected

No increase in the stats for the uploaded video

#### What happened instead

My own "play" was counted in towards the stats for the uploaded video

#### Screenshot / Video

The added video stats: https://cloudup.com/cjIVj2GMbOj

This is what I see when I click for more details on these "plays": https://cloudup.com/cJKbANtSAF0

These "plays" seem to show that they come from my Media Library: https://wordpress.com/media

#### Context / Source

This was reported by the user who had 72 "plays" in their stats without the video being published. 
For reference, #543187-hc

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I attempted to reproduce by uploading a video then selecting the video in a Video block type, then playing the video as myself. Stats page did not register my own play as a video playback count as expected.

As it does not appear the issue is reproducible, it is being closed with the label `Closed - Not Reproducible`.
