### ISSUE TITLE
WooCommerce Checkout page is not visible on site Preview

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#17790]
#### Steps to reproduce
1. Starting at any site with WooCommerce, for instance,  https://wordpress.com/stats/day/vinosaltaexpresion.com
2.Click on 'View Site' for a preview 
3. Add any product to the shopping cart
4. CLick on Checkout.

#### What I expected
You expect being able to see the checkout page

#### What happened instead
You see a blank screen. The checkout page is not shown

#### Browser / OS version
Firefox55 on MAC whatsmybrowser.org/b/EW9M38N
Chrome60 on MAC whatsmybrowser.org/b/NL4T4XZ

#### Screenshot / Video
![your site la tiendica de la nata wordpress com 2017-09-05 14-45-01](https://user-images.githubusercontent.com/6404071/30061736-dcd2620c-9248-11e7-8f2b-5285a4f91724.png)

#### Context / Source
Checked with RAchel McRoberts at #triage and "there is a CORS console error"

#user-report but the site is no longer an ATOMIC site, so reproduced the issue on several other sites

**Comment by rantoncuadrado** [comment]
Follow up ticket https://woothemes.zendesk.com/agent/tickets/668105

**Comment by rachelmcr** [comment]
The console error I observed is `Refused to display [LINK] in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

Although I wouldn't expect to be able to preview the entire checkout process in this context, it would be better to stop the user before they get to this point or otherwise fail more gracefully rather than allow a user to end up on this blank preview screen.

**Comment by gwwar** [comment]
I'd agree here with @rachelmcr to not allow us to checkout within our own preview iframe, and warn or open a new tab :)

How do you feel @apeatling ?

**Comment by kwight** [comment]
I'm not very familiar with it, but I'm thinking that we would need to use `postMessage` telling one of the iframed scripts to disable the checkout button (and maybe a label saying "disabled in preview"?). Or actually, I'll dig into how the masterbar is handled; the iframe `src` has params of `?theme_preview=true&iframe=true&frame-nonce=(nonce)&calypso_token=(token)` which seem to trigger disabling of the masterbar.

**Comment by gwwar** [comment]
@kwight what if we start with something simple like redirect or show an error if it a checkout page notices it's iframed. eg
```jsx
window.self !== window.top;
```

**Comment by apeatling** [comment]
Sorry I missed this before, I think breaking out of the frame would be okay, although it's one of those things you have to experience to see what feels expected.

**Comment by kwight** [comment]
I think the redirect will be quite jarring; I'll look at something simpler as @gwwar suggests.

**Comment by kwight** [comment]
Resigned as I don't expect to get back to this before September.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
