### ISSUE TITLE
Comments: The post view and comments view display comment content differently.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#17861]
Given a comment with HTML markup, it will be displayed in the post list view (`/posts`) as formatted:

<img width="583" alt="screen shot 2017-09-06 at 10 28 43 am" src="https://user-images.githubusercontent.com/349751/30125876-c82aa642-92ee-11e7-94b7-0c872997eccf.png">

... and unformatted in the comment list view (`/comments`):

<img width="657" alt="screen shot 2017-09-06 at 10 33 45 am" src="https://user-images.githubusercontent.com/349751/30125914-eb8926d6-92ee-11e7-8564-44d1b62322ec.png">

These should be made more consistent.

**Comment by Copons** [comment]
I'm not sure we should unify them.

On Posts, we can read the comments in their entirety, on Comment List we just show excerpt for a quick glance.

Your screenshot might be confusing because your comments are 1-liners, and so looks almost identical in both views.
Longer and formatted comments will look completely different instead, and for good reason, imho.

If anything, we might want to make the Post comments with the Comment Detail (expanded view) more consistent.
For example, at first I used the serif font for Comment Detail, copying the established Reader and Post comments design.
I can't remember the reason we decided to go with full sans-serif for Comment Management, but it was a precise design request.

(This letting alone the technical implications. If we don't strip tags in Comment List, we should take into consideration things such as images or inline styles)
