### ISSUE TITLE
Store: Order Details Table on Mobile Cramped Columns

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#17910]
![screenshot_20170906-212534_png__1080x1920_](https://user-images.githubusercontent.com/22080/30173260-f2074a0c-93ab-11e7-84ff-da3ab922403e.png)

While viewing an order detail page on my Nexus5 last night I noticed a few visual oddities that I thought should be logged as an issue:

- The details table Product column gets quite cramped on smaller viewports which results in a _very tall_ Product name cell. Not sure what we can do to remedy this, a scrolling table akin to the order list isn't the best experience either but perhaps we can get creative with limiting the size of the quantity column or something.
- Button padding. This one is odd as it only happened on the mobile chrome browser... I tried to recreate using devtools emulation on mac/chrome and it looked fine. The "Save Order" and "Submit Refund" buttons appear to have more bottom padding

**Comment by timmyc** [comment]
@kellychoffman or @jameskoster any ideas on how to make this look better on mobile? One Idea I had was to hide the quantity and price columns on mobile, and maybe have a descriptive line below the sku with something like "Quantity x at $$$ each"

**Comment by ryelle** [comment]
I'm going to drop these here too, since they're order-screen related.

The header is unusable unless you know what these buttons say:

![2018-01-10 15 33 27](https://user-images.githubusercontent.com/541093/34794258-16d465e0-f61c-11e7-8ac1-9f2141a448dd.png)

This PriceInput component needs a rethink for how we handle on mobile size, this just looks odd (having prefix/input/suffix each on their own line). It doesn't get better once you change the value & get the reset icon, either.

![shipping](https://user-images.githubusercontent.com/541093/34793983-2b7dcb2c-f61b-11e7-93c0-2171c3b6b785.png)
![screen shot 2018-01-10 at 3 41 54 pm](https://user-images.githubusercontent.com/541093/34794492-cd94b708-f61c-11e7-8297-c2535a20b03f.png)

**Comment by timmyc** [comment]
I'm thinking we could possibly take some inspiration of the work going into the Android app for this screen on the small viewports... but I agree it is getting pretty hard to read now :(

**Comment by kellychoffman** [comment]
> any ideas on how to make this look better on mobile?

What if we kept all the data and just had the product info on its own line? Was thinking it wouldn't need a label as it was obvious its a product: 

<img width="304" alt="screen shot 2018-01-10 at 6 43 58 pm" src="https://user-images.githubusercontent.com/5835847/34804509-3fb5bb7a-f636-11e7-991e-a7d4e801d35f.png">


> The header is unusable unless you know what these buttons say:

Perhaps we could turn them into a split button? https://wpcalypso.wordpress.com/devdocs/design/t or hide the "Resend Invoice" all together.

**Comment by jameskoster** [comment]
Split button is what I'd suggest as well.

For the table we could do something like we do with the cart on the frontend in core; 

![desktop](https://cldup.com/7g277HugEA-3000x3000.png)

![mobile](https://cldup.com/DTuiewJscV-3000x3000.png)
