### ISSUE TITLE
Help: Rethink the way we are populating the subject

### ISSUE THREAD

**Issue by omarjackman** [Automattic/wp-calypso#1796]
This was originally reported in #1338. We might benefit from using something other than `valueLink`.

@dmsnell and I discussed this in slack on December 16th.

**Comment by designsimply** [comment]
_Adding some notes form the other issues so this ticket can stand on it's own and read clearly._

The problem: if a person starts writing a help request and then all operators become unavailable, then a subject input field appears in the form at that point and it is autofilled with the first five words of the original message.

Steps to reproduce:

1. In Olark set yourself as "Available".
2. In another tab navigate to https://wordpress.com//help/contact
3. Enter some text in the message field.
4. In the Olark tab, set yourself as "Away".
5. In the Calypso tab, check to see what appears in the subject line when the form switches to the Kayako version.

Result: the first five words of your original message followed by an ellipses, but is this the best solution?

Other possible solutions for consideration:

1. Require the user to enter a subject anyway and use standard error form validation to make it clear what someone should do in the (rare?) case this problem happens
1. Don't require a subject line (not ideal, subject lines are nice)
1. Instead of autofilling the subject, use a generic one in a hidden form field (i.e. "WordPress.com help request for $site_name")

**Comment by designsimply** [comment]
Spoke with @omarjackman today and decided this is still a valid `Support` issue not specific to `Olark` or `Happychat`, so we'll just keep it in the `Support` label for now.

**Comment by dmsnell** [comment]
Closing because its priority hasn't percolated up in a long time.
