### ISSUE TITLE
Scheduling: timezone discrepancy between Calypso and WP Admin

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#18124]
Hello! I did some tests with trials and a12s in different timezones and @htdat and I have discovered that there is a timezone discrepancy between Calypso and WP Admin.

A post published from WP Admin will follow the site's timezone settings, and a post published from Calypso will follow the user's computer timezone settings.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general, choose a timezone that's ahead of yours.
2. Let's say it's 12PM where you are, go to Calypso (https://wordpress.com/post/) and schedule a post for 12:15PM. The post will be published in 15 minutes.
3. Let's say it's 12PM where you are, go to WP Admin (https://yoursite.wordpress.com/wp-admin/post-new.php) and schedule a post for 12:15PM. The post is published X minutes/hours ago, following the site's defined timezone.

#### What I expected

I expect the scheduling feature to schedule posts according to the timezone that is defined in the site settings when publishing posts from Calypso.

#### What happened instead

Posts scheduled in WP Admin follow the defined site settings time zone, however posts scheduled from Calypso follow the time zone of the user's computer settings.

#### Example

In this example, it's 12PM UTC+2 locally and the site timezone is set to UTC+4.
Post A was scheduled at 12:15PM on Calypso, and Post B was scheduled at 12:15PM on WP Admin:

![timezone](https://user-images.githubusercontent.com/16645645/30586681-0f3e0190-9d31-11e7-83ef-bed95f12d4b0.png)

**Comment by brbrr** [comment]
Hi @cecilerainon! That's a nice find!

May I ask you why do you think we should stick to `wp-admin` style?
(I don't actually lean to any particular answer, just want to hear what you think about this)

There is at least 1 case which might cause problems when using `wp-admin` style: when there are few editors from different time zones which want to schedule a post. They would need to calculate which time to use, so in this case, it would be easier to use editor timezone for scheduling. 

But definitely, we should put some notice about which timezone would be used (or even give user an option to select appropriate one)

**Comment by cecilerainon** [comment]
Hello! I don't think we should stick to WP Admin necessarily, especially since we're moving away from it towards Calypso. But I think we should stick to whatever timezone is entered in Calypso's settings page (https://wordpress.com/settings/general) rather than following the user's browser/computer time zone.

So if in my settings, it's set to UTC+2 and it's currently 8 AM UTC+2 and I choose to schedule a post for 11 AM, it'll get published at 11 AM UTC+2 (in 3 hours).

Finally, I agree with you about a notice. Let's say I'm traveling west to California (UTC -7) and schedule a post at a time that's already passed in UTC +2 (because that's what my site's settings are): we should show a warning message mentioning it's already passed that time in UTC +2 with, let's say, a link to the Settings page to adjust the site's time zone. Or even better, give the user the availability to update the time zone directly in the schedule module of the post editor.
