### ISSUE TITLE
Reader Manage: Don't show "error fetching feed"

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18139]
Instead of showing "error fetching feed" in the list of followed sites like this ...

![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/24388/30656494-2c14c318-9de9-11e7-8ca1-4d81096ba6b6.jpg)

... we should simply hide those items. It does the user no good to get the error (they can't do anything about it). And if the site has been deleted, we shouldn't be showing it anyway.

**Comment by samouri** [comment]
Lets take another step back here because I'm not sure just hiding this item is the best way forward. But maybe it is.  Thinking out loud:

Current Problems flow is
1. user follows site and enjoys its content
2. N years later, site gets deleted.
3. Site Stream still exists but throws errors re. fetching feed and re. getting stickers.  Site also still exists within manage but with the error shown above.  If you actually try to follow or refollow the site then we mark it as spammy behavior. Its a bad ux in multiple places.


What should we ideally do when a site is deleted?  Here are two ideas:
1.  As suggested above, hide those items. Don't make any backend changes, just hide the site stream when accessed + don't show deleted items in the subs list.  It should happen infrequently enough to not cause inefficiencies.
2. Backend cleanup: remove the site from feedbag/subscription_matrix and have the site then automatically disappear from everywhere in the ui (less work in Calypso, more work on backend).

Both the two options above have the negative that we don't let the user know they follow a site that has been removed.  This is edgecasey enough that I think thats okay.

**Comment by fraying** [comment]
Yes, we should clean up the data source, too. But I see no harm in simply hiding these errors first.

**Comment by fraying** [comment]
Where are we at in hiding the "error fetching feed" listings? cc @blowery

**Comment by rachelmcr** [comment]
We also have https://github.com/Automattic/wp-calypso/issues/5840 related to cleaning things up (to remove subscribers from deleted sites).

**Comment by blowery** [comment]
@fraying should be done now

**Comment by samouri** [comment]
@blowery: don't we need to land https://github.com/Automattic/wp-calypso/pull/18142 first?

**Comment by blowery** [comment]
@samouri nope, https://github.com/Automattic/wp-calypso/pull/18442 took care of it. if both the feed and the site are in error, we already hide it (i think).

**Comment by fraying** [comment]
@blowery Just as a paranoia check: We hide the whole row, right? Not just the title?
