### ISSUE TITLE
Images: Set a focus point or thumbnail section.

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#18206]
### The Problem
In reader, I stumbled upon the [feed of a local organisation](https://wordpress.com/read/feeds/66514499) and soon noticed that most of the preview images in the feed looked _off_.

The reason being that most of the photos are taken in portrait, something that's much much more prevalent since phones became peoples primary cameras.
The problem is that the way we crop these images for display is often much better suited to images that are already landscape and our work-around for portrait images is to set `background-position: center center` on these previews/thumbnails, which ignores the common situation where an images subject is positioned away from the center.

### Proposition
I wonder if we could give folks a tool that allows them to designate a point of focus on their images.
Perhaps they would drag and drop a target on to their photos, setting an x and y point that we would prioritise when showing thumbnails.

Here's what I mean:

Here's how an image would show right now. It isn't representative of the image that it's previewing:
<img width="852" alt="screen shot 2017-09-23 at 18 21 00" src="https://user-images.githubusercontent.com/4335450/30778714-95008948-a091-11e7-91c3-04d21d1fc351.png">

Using an added tool, I would set the focus point of the image:
<img width="1161" alt="screen shot 2017-09-23 at 18 56 14" src="https://user-images.githubusercontent.com/4335450/30778715-95160098-a091-11e7-8d4e-a18531d117e0.png">

Let's just say that that target is placed at x: 50%, y: 70%, we would set  `background-image: 50% 70%;` on the image, giving us:
<img width="863" alt="screen shot 2017-09-23 at 18 22 24" src="https://user-images.githubusercontent.com/4335450/30778713-95004eec-a091-11e7-926c-6c8dfee0bc0a.png">

My example isn't perfect, but paints the picture well I think.
Also the idea of it being a target is just an example, the main point being that we give folk _some_ way of setting this point on their images.

**Comment by fraying** [comment]
I agree that the problem is a problem. And it's a good solution. In an ideal world, we'd have enough of the user's attention that they'd want to take the time to set a focal point for their images for us. 

But, alas, I doubt very much that we live in that world. If we built this, the vast majority of users would never touch it. We just don't have that much of their attention. And for RSS feeds in Reader, those people may not use WordPress.com at all.

I think we should look into automated focal point detection instead. We've done some preliminary work there, but never prioritized finding a launchable solution.

Keep in mind the user can click on Photo cards to see them uncropped, so at least the whole photo is only ever a click/tap away.
