### ISSUE TITLE
Subscriber Role Has Jetpack Site Counted Towards Total WordPress.com Sites, Yet Site Doesn't Appear For Management

### ISSUE THREAD

**Issue by pmciano** [Automattic/wp-calypso#18230]
If a WordPress.org site user is assigned the Subscriber Role for a site, and they connect this site to their WordPress.com account through Jetpack, the site counts towards their total WordPress.com sites. Yet, the site does not appear in the site list, presumably since a Subscriber does not have site management permissions.

<img src="https://www.evernote.com/l/AthzCxGoZRdEJYkIXz3RAYRSPpIvc5_XUTYB/image.png" width="270">

I have replicated this issue with my own test account and site. Changing the WordPress.org user role changes what is seen at WordPress.com, e.g., moving a user from Subscriber to Contributor makes the site appear in the site list.

If a user is a Subscriber and doesn't have any management capability for a site, it makes sense that the site would not be listed at WordPress.com, but then it should not be counted towards the user's total WordPress.com sites.

Ticket ID: 3326451-t

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
