### ISSUE TITLE
Reader: Shortcodes unexpanded for Atomic site

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#18279]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/feeds/58300400/posts/1351764785
2. Notice unexpanded shortcodes in the content

#### What I expected
Shortcodes to be expanded

#### What happened instead
They were not

#### Browser / OS version
Any

#### Context / Source
We should be serving the expanded variant of this content, which is synced back by Jetpack. For some reason, we are not.

**Comment by blowery** [comment]
This ... may not be a bug. I see the same unexpanded shortcodes on the actual site. Checking with @dmsnell

**Comment by dmsnell** [comment]
@blowery as we discussed in Slack the shortcodes are unrendered because they are on an Atomic site.

**Comment by rachelmcr** [comment]
As this issue is being tracked for Atomic sites, and this case is noted there, I think it's safe to close this issue. Once the shortcode is working on the site itself the expected content appears in Calypso, so it seems to be a matter of handling the transfer to Atomic as expected. Please reopen if you think there's a need to handle this on the Calypso side as well.
