### ISSUE TITLE
Post sharing: Issues with timezones

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#18304]
When trying to share a post, there are some timezone inconsistencies.

On a test site in the UTC timezone, and with my browser in UTC-5, the post sharing panel opens with a share date of "Tomorrow at 2:13 am".(in this example, the local time was 9:13pm).

It looks like the panel is designed to operate mainly in the site timezone (UTC in this case), but if that's true, then perhaps I shouldn't be able to select today at all, because it's already tomorrow in UTC.

In addition, when the share panel opens, there is no date with the "selected" (light blue) style:

> <img src="https://user-images.githubusercontent.com/227022/30892914-e1d57b7c-a300-11e7-93ef-f516f7a7b63e.gif" width="375">

**Comment by nylen** [comment]
In the example above, when picking a date before "Tomorrow at 2:13 AM", this date is not saved, and the date is reset when re-opening the date picker.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
