### ISSUE TITLE
Comments: when failing to retrieve comments, auto dismiss error message,  (or not show it)

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#18322]
Users are unable to do anything meaningful in this case, so it might be better to not show an error.

**Comment by Copons** [comment]
By default, each of these error notices will "overwrite" themselves as long as the error happens on the same site. (in other words, they have a like `id: 'notice-${ siteId }'`)
This means that we'll only have a maximum of 1 of these notice visible at the same time.

I've tried adding a `duration: 5000` to the notices and I noticed that when we have multiple comments erroring out, especially on first load with clean cache, it's possible that 1+ notices are displayed _after_ the previous automatically disappears.

![oct-13-2017 15-12-19](https://user-images.githubusercontent.com/2070010/31550386-15b9e470-b029-11e7-9fc2-8e03d9755a10.gif)

What happens in this gif is that we have 3 "error" comments, and we see only 2 notices popping up one after the other, because 1 of the notices is displayed while the previous was still visible, silently replacing it.

If I try on this same site without cleaning the cache first, even in case of "Skipping initial state rehydration to recreate first-load experience.", I only ever see 1 notice.
Though, I can imagine that on sites with more than 3 "error" comments the user could see more notices anyway.

This said, I don't know if we have a reliable way to "stacking" all the errors _before_ displaying the notice.
For this reason, I guess we might want to drop the notices altogether, and rely on the placeholder to convey that something screwed up.

Alternatively, we could do some Redux magic: mark these comments in state as "error", and remove their placeholders.

**Comment by Copons** [comment]
Ok, scratch everything. We settled for not showing the error notice at all, with the reasoning that the user can't do anything about it anyway.

Though, this change will likely impact the Reader as well.
@bluefuton, @samouri: mind if I drop the notice from here?
https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/sites/comments/index.js#L114-L144

@megsfulton Do you have any opinions from a design standpoint?

**Comment by megsfulton** [comment]
Getting up to speed on this one. 

This for when only certain comments in the list view fail to load? And if so what would cause certain comments not to load? 

Is the proposed solution to keep the comment that's unable to load in the loading state? Or something else?

**Comment by Copons** [comment]
@megsfulton There can be several causes, mostly related to some miscommunication between Calypso and the back-end.
For example, in my gif over there, I forced some comments to fail by using a bug on the API endpoint.
Basically, the user or just can't fix them, or might need to try some workarounds on WP Admin (which is not something we should recommend though 😄 ).

So, the easy solution is: not showing any error notice at all, and just leave the placeholders blinking forever.

A more complicated solution could be to also remove the placeholders of failed comments.
Though, this could look odd, if for some reason those comments are failing on Calypso but are instead appearing in the Notifications panel or in WP Admin.

In the end, both solutions would look odd; it's a trade-off kind of deal.

**Comment by kwight** [comment]
Could we use an error-ish message when the comment fails to replace the pulsing placeholder
<img width="766" alt="screen shot 2017-10-18 at 2 23 16 pm" src="https://user-images.githubusercontent.com/349751/31743438-04424210-b410-11e7-8d7d-1d2ca2b091c1.png">
?

**Comment by Copons** [comment]
> Could we use an error-ish message when the comment fails to replace the pulsing placeholder?

Wondering.
If I see something like that, my first reaction would be to reload the page.
Unfortunately, though, most of the failures are caused by uncatched edge cases on the backend, and a reload wouldn't change anything, adding to the frustration.

Another option could be to remove the failed comments from the comments tree in the data layer's `onFailure` handler, so that they simply wouldn't appear anymore.
This has the pro of not touching any other Calypso section except Comment Management.
The con is that _we_ won't see errors anymore.

**Comment by samouri** [comment]
>Though, this change will likely impact the Reader as well.
@bluefuton, @samouri: mind if I drop the notice from here?
https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/sites/comments/index.js#L114-L144

makes sense to me! our users can't do anything about an individual comment fetch failure either.
We'll want to make sure we aren't re-requesting it in a loop though
