### ISSUE TITLE
Editor: Unpredictable behavior from Back button

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#18337]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/example.wordpress.com
2. Create and publish a new post
3. Click the Write button on the masterbar to start another new post, or edit an existing draft
4. (Sometimes here I saw the Are You Sure prompt, despite not making any changes, but couldn't reproduce it reliably)
5. Write your new post and save the draft
6. Click the Back arrow button

#### What I expected
To either return to my previous post, or possibly the posts list (or wherever I was before entering the Editor)

#### What happened instead
Sometimes I was given an AYS prompt despite no changes, sometimes I was sent to my earlier-published post.  Sometimes (as seen in the GIF below) the first click did something innocuous like close the sidebar, or appeared to do nothing at all, and multiple clicks were required to move anywhere.

Ref other issues with the Back arrow: #17928 #17022 #16039 #6911 #4509

#### Browser / OS version
Seen here in Linux Chrome v61, but observed in multiple environments

#### Screenshot / Video
![wp-calypso-back-arrow](https://user-images.githubusercontent.com/7233112/30933896-e43f2004-a399-11e7-8132-bbfd05735cae.gif)

#### Context / Source
#dogfooding @ryanboren

**Comment by KokkieH** [comment]
This is still happening in the new iteration without the masterbar and a "Close" button instead of the back button.

I just published a draft post I'd created a while ago, and had to click the Close button several times to get back to the main Calypso menu. It makes no difference whether I close the post-publish preview before trying to leave the editor or not. 

It always happens with posts containing an image gallery.

**Comment by rachelmcr** [comment]
I tested using the following steps:

1. Go to the Blog Posts list: https://wordpress.com/posts/my/:site
2. Create and publish a new post.
3. Select "Add another post" (in the publish success notice) to start a new post.
4. Publish the new post.
5. Select Close. This returns me to my first post.
6. Select Close again. This returns me to the Blog Posts list.

I also tested by publishing a draft post first (instead of an entirely new post) and then publishing a new post immediately after that.

In each case, I get consistent results — I am always returned to the previous post I published, and then to the place I was in Calypso before starting a new post. This matches the expected behavior, so I'll close this as resolved.
