### ISSUE TITLE
Signup: Restrict available themes that may show up during signup

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wp-calypso#18379]
Right now, only three different themes are presented to users for each 'site type' when they're creating a new site (like from https://wordpress.com/start). 

However, we currently have several different themes for each type, which are randomly used to fill those three spaces. 

It seems like a good idea to par down the available themes that are shown, so there are always only three themes available for each 'site type', and we have better control over which themes new users are steered to. So rather than having nine available themes that may be shown in one of the three spots, only have three and always show the same three.

This came up as a suggestion on this PR: https://github.com/Automattic/wp-calypso/pull/18365

Creating a separate issue for discussing aspects of this, like figuring out which themes to use, before creating a PR.

**Comment by mapk** [comment]
The themes displayed for each site-type can be [found here](https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/themes-data.js).

**Currently there are:**

- 10 themes for Blog
- 9 themes for Page
- 3 themes for Grid

**My proposal**

**Blog**

- Independent Publisher 2
- Penscratch 2
- Franklin

**Page**

- Radcliffe 2
- Gateway
- Karuna

**Grid**

- AltoFocus
- Apostrophe 2
- Dyad 2

**Comment by johnmaeda** [comment]
It's better to have more genes in the front end because they're randomizing. So more than three is fine -- as long as they have some consistency. 

I suggest that the basic consistency rules be:

— Ensuring that all themes used in these offering have their Headstart annotations set to have *no widgets*. That will increase the probability that we will have less errant Widgets that have no home upon a theme switch.
— Ensure that the amount of blog posts injected by Headstart is at a bare minimum.

Some thoughts:

— We're really good at blogging, so let's double down on blogging options because we're good at that. So use as many of them as you can.
— We're less good at page-ing. Our best offering there is currently Radcliffe 2 -- but we still have a long way to go in improving its functionality. Our next offerings should start to fill this gap.
— We're kind of good at grid-ding because that's about having a variety of ways to place items on the page as posts (e.g. my toilet paper analogy). So use as many of them as you can.

After testing each theme individually:

**Blogging**

1. **Yes to Independent Publisher 2**, but please disable the default Gravatar setting in its Headstart annotations because that is expecting a person to know how to set that up. If it's gotten easier to setup a gravatar for anyone to figure out, then by leave it that way. Last time I checked it's still not intuitive so best to leave it off by default -- otherwise it shows up as a squiggly piece of graphic that makes a person nervous. Distinctive feature: feels the most modern.

2. Yes to **Penscratch 2**. Remove all widgets and _it's EASY._

-. No to Franklin. It's dated and non single-column centric.

3. **Hemingway Rewritten**. Remove all widgets and _it's EASY._ Distinctive feature: good micro-details.

4. **Cols**. This is a brilliant blogging theme. Remove all widgets and _it's EASY._ Distinctive feature: multi-column.

5. **TwentyFifteen**. V good blogging theme. Remove all widgets and _it's EASY._ Distinctive feature: plain color nav.

6. **Bushwick**. A strange but interesting blogging theme. Remove all widgets and _it's EASY._ Distinctive feature: button-sensibility.

**Page-ing** 

I used my new ORIGINAL, CRISPY, BBQ, FRESH WAFFLES TAXONOMY, FLAME-BROILED taxonomy.

1. **Radcliffe 2**. FLAME-BROILED. Good. This is EASY.

-. Gateway is CRISPY. No good.

2. **Karuna**. FLAME-BROILED. Remove all widgets. Also it starts with two default blog posts and should start with just one. _It's still quite difficult to use so it's not EASY._

3. **Dara**. CRISPY. Remove all widgets. Also it starts with three default blog posts and should start with just two ones with the featured tag so the slider works. _It's still quite difficult to use so it's not EASY._

4. **Lodestar**. BBQ. Remove all widgets. It's as good as we can do for now. _It's still quite difficult to use so it doesn't get the EASY._

**Grid-ing**

1. **Cubic**
2. **Dyad 2**
3. **Baskerville 2**
4. **Rowling** 
5. **Boardwalk**
6. **Apostrophe 2**
7. **AltoFocus**

**Comment by mapk** [comment]
I'll create a PR with these themes as the current list in our signup flow.
