### ISSUE TITLE
Make Threat Warning Icon stand out more

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18373]
<img width="139" alt="screen shot 2017-09-28 at 8 09 38 am" src="https://user-images.githubusercontent.com/26996883/30974477-9cd444e8-a424-11e7-8f0a-cb8c365dfa15.png">

This doesn't stand out enough to me as serious. Can we make the icons for security threats more of a warning? 

According to @rickybanister 👍 

> I think you're seeing a sort of temporary state there. We definitely plan on those being colored properly, but I believe they need to map colors to a 'status' in the API.

 cc @singerb  @keoshi

**Comment by keoshi** [comment]
These were whitelisted manually in Calypso but with recent changes, it now delegates these decisions to the API. We should move this to https://github.com/Automattic/action-to-activity-log/

**Comment by rickybanister** [comment]
I don't think that's true @keoshi. I thought the API would return a 'status' and then the colors would be assigned in Calypso? 

Perhaps @sirreal can comment. 

At least I'd like to make sure @annezazu doesn't have to move this issue again and it can just get handled.

**Comment by keoshi** [comment]
> I thought the API would return a 'status' and then the colors would be assigned in Calypso?

That's true, but that only means `warning` is red or `success` is green, it doesn't mean a `synced` action will have the `success` status — that's now dealt on the API side.

**Comment by sirreal** [comment]
The API is indeed responsible for classifying Activities by status. It _may_ provide a status which closely correlates to some existing names in Calypso:

- `success`
- `error`
- `warning`
- `info`

It is up to the client to decide how to deal with the status. In Calypso at the moment, that means applying classes which change the icon color:

- `success` -> green
- `error` -> red
- `warning` -> orange
- `info` -> blue
- none -> grey

The repo being used for API changes is the [one @keoshi mentioned](https://github.com/Automattic/action-to-activity-log/).

@annezazu - A suggestion for anyone reporting things related to the logs themselves is to get a dump of the log data we have in Calypso. In this case, it's particularly helpful to know the `activityName` which I suspect is `rewind__scan_result_found`.

To do that, open the browser console and run `localStorage.debug = 'calypso:activity-log:item'`. Refresh the page and click on the log. In the console you'll see debug information related to that log which you can screenshot or copy paste into the issue:

```js
// Just an example
{
  "actorAvatarUrl": "https://www.gravatar.com/avatar/0",
  "actorName": "Jetpack",
  "actorRemoteId": 0,
  "actorRole": "",
  "actorType": "Application",
  "actorWpcomId": 0,
  "activityDate": "2017-10-02T07:58:29+00:00",
  "activityGroup": "plugin",
  "activityIcon": "plugins",
  "activityId": "AV7cGADSjEqjFGbx2Ye8",
  "activityName": "plugin__update_available",
  "activityStatus": "warning",
  "activityTitle": "Jetpack by WordPress.com plugin has an update available",
  "activityTs": 1506931109000
}
```

I've opened D7454-code which addresses this problem and is a good place to continue any discussion. Feel free to close this issue, otherwise I'll try to loop back and close it when the change is landed.

**Comment by annezazu** [comment]
Thanks so much for explaining how to find this :) DM-ed you with a follow up question. Closing for now.
