### ISSUE TITLE
Store - reviews appear in comment management

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#18437]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/reviews/approved/:sitename:
2. Make note of reviews
3. Visit http://calypso.localhost:3000/comments/all/:sitename:
4. Notice reviews can be managed there as well

#### What I expected
I didn't expect to be able to approve/manage reviews in the Comments screen

#### What happened instead
Reviews to be hidden

**Comment by justinshreve** [comment]
We'll need to think about this one. [WooCommerce isn't marking reviews with a `comment_type`](https://github.com/woocommerce/woocommerce/issues/16297#issuecomment-333612228) which makes these a bit harder to filter out. We should be able to see if it's a comment on a product `post_type`. We also need to make sure to hook into the right filter so that we can affect the output of the WordPress.com API (which is what is used for normal comments management).

**Comment by timmyc** [comment]
Moving to Q1

**Comment by timmyc** [comment]
So it turns out this is acting in the same manner as `wp-admin`/core. Verified that reviews are showing up in the Comments section there too:

![reviews-in-comments](https://user-images.githubusercontent.com/22080/37008219-f983ff7e-2095-11e8-8dec-1693b05d3e97.png)

I went back and forth a bit on this as to if I think it is "right" for the reviews to show up there, but ultimately - they *are* comments so kind of feels like it is okay. @jameskoster I'm going to close this out since it is working the same as core, but if we want to bring this up at the core level and see if there are any thoughts around removing them from the wp-admin comments listing, then I'd be fine opening this back up.

**Comment by jameskoster** [comment]
> but ultimately - they are comments

I don't think that's how users look at it ;) Offering two interfaces to manage reviews is counter intuitive.

Personally I think this is something that should be fixed, whether it's in core or Store. Ideally both. It is low priority though...

**Comment by timmyc** [comment]
I'll re-open then, shall we create an issue in core too?

**Comment by jameskoster** [comment]
We can open an issue but It's a bigger problem in core since the Comments section is the only place you can moderate reviews currently. So we can't just hide reviews there, we'd need a new review management interface before hand. I think we need to do some research before tackling core.

**Comment by timmyc** [comment]
Maybe having a dashboard interface in core could house a review management feature 🤔

**Comment by jameskoster** [comment]
If only someone was working on that 🤔

Yeah, good point. I've factored reviews in to my preliminary sketches there.

**Comment by justinshreve** [comment]
This bug is not valid anymore. Based on some API changes in WooCommerce 3.5, product reviews are no longer included in the response, however counts still are. There is an issue open for that at https://github.com/Automattic/wp-calypso/issues/28858.
