### ISSUE TITLE
Jetpack Connect: Autoconfig features list is long and confusing

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#18456]
As shown in the screenshot below, the feature list shown when we're autoconfiguring the various plugins and things for a plan purchase is pretty long and hard to read. Perhaps we could slim it down and just include the key features depending on which plan has been purchased?

<img width="562" alt="screen-shot-2017-09-28-at-10-14-18" src="https://user-images.githubusercontent.com/831377/31096069-fada3a7c-a788-11e7-8e3c-8d9098c7c430.png">

**Comment by chaselivingston** [comment]
Related: Some of these items are a bit odd with a spinner next to them, such as _Easy Site Migration_ or _Unlimited Backup Storage Space_. I think making the list more concise and highlighting only the key features will help with this as well.

**Comment by simison** [comment]
Similarly, when installation fails due missing write access, we show a long list of "unfinished" features:

![image](https://user-images.githubusercontent.com/87168/35923674-94826b9a-0c29-11e8-9b20-85e5b1472bc8.png)

As a user I'm like "I need to install and configure all this?" vs reality.

Someone could also read the above list as a "sub list":

- Real time off-site backups
  - unlimited backup archive
  - unlimited backup storage space
  - etc...

**Comment by rickybanister** [comment]
We are currently exploring a different 'thank you' experience that will remove all of the 'auto-config' stuff and be focused more on giving the customer options to manually configure anything that requires manual configuration. Everything we can do automatically will be pre-completed for them in a checklist. 

Thanks for the feedback!

I'm going to close this issue for now since the new flow will mitigate this.
