### ISSUE TITLE
Media: Edit/Delete buttons obscured / misaligned

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#18488]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Open the media modal and select an image

#### What I expected
To be able to see and use the Edit / Delete buttons

#### What happened instead
On mobile they're almost entirely obscured (which is causing the e2e tests to fail):

<img src="https://user-images.githubusercontent.com/7233112/31129371-5a7015e4-a822-11e7-9cc5-f1fd3846ace5.png" width=350>

On desktop they're just aligned all the way to the left without much spacing around them (maybe intentional?)

![image](https://user-images.githubusercontent.com/7233112/31129410-77366e8a-a822-11e7-9bf0-e78e39189761.png)

cc: @stephanethomas, likely due to #18477 since that was the most recent change 
#### Browser / OS version
Chrome on Android and Linux

#### Context / Source
 #automated-testing

**Comment by stephanethomas** [comment]
This probably happens because of the new `Card` stylesheet introduced in the `post-editor` section in https://github.com/Automattic/wp-calypso/pull/18477. If I uncheck the `display: block` rule below the buttons are correctly aligned:

<img width="282" alt="screenshot" src="https://user-images.githubusercontent.com/594356/31132476-34714a30-a85d-11e7-8d7e-897af9b5a5f9.png">
