### ISSUE TITLE
Stats: trouble with standard / daylight time on Insights page

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#18531]
#### Steps to reproduce
You would have to have done some setup before a DST/Standard Time switch, actually. This user always publishes scheduled posts at 23:45.  So let's say they posted on Sept 4 at 23:45.  Now that they've moved over to daylight time there, our Insights page says the post was published September 5.

The user who spotted this says it's fine in apps and elsewhere, just not in the browser on the Inisghts page.

#### What I expected
For a post published at 23:45 on Sept 4 to say it was published Sept 4.

#### What happened instead
The insights page says it was published Sept 5.

#### Browser / OS version
User is in Safari

#### Context / Source
Noted at https://en.forums.wordpress.com/topic/retrospective-date-change-on-posts-since-daylight-savings-change?replies=9

**Comment by supernovia** [comment]
cc @timmyc is there any other info I should gather for this?

**Comment by timmyc** [comment]
Looks good to me - not sure who can look at this in the near-term though, but plenty of data to work with when someone does. Thanks for the detailed report Velda!

**Comment by supernovia** [comment]
You bet. I told the user it likely wouldn't get fixed soon but I will thank them for the report. Cheers!

**Comment by rachelmcr** [comment]
I tried to fake a DST switch to re-test this issue but didn't manage it. :) Noting for the record, though, that "Posting Activity" is the part of the Insights page where the publish date changes:

<img width="785" alt="screen-shot-2017-10-03-at-16-30-27" src="https://user-images.githubusercontent.com/8658164/44860797-05981380-ac6f-11e8-8e79-ceacace586a1.png">

**Comment by sjaved87** [comment]
Another report for same issue in #9797255-hc

**Comment by rachelmcr** [comment]
I just ran into this on a blog I own where I post once a day, nearly daily. I noticed after the switch to daylight saving time that quite a few posts that were published between 11 PM and midnight are now showing as published on the following day.

This is especially frustrating on this particular blog, since I use the Insights tab to look back at how well I'm doing at posting once a day — now the chart is messed up and the only solution seems to be changing the post time for every post where that happened so it's before 11 PM.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES

There are also a few newer reports that may address this upstream.  Thinking specifically of: https://github.com/WordPress/gutenberg/issues/46333
