### ISSUE TITLE
Conversations: Make "Comments Closed" more subtle

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18542]
When a post closes comments, the post looks like this in Conversations:

![before](https://user-images.githubusercontent.com/24388/31192635-a60f222c-a8f6-11e7-97e3-02ab866ca171.png)

That's devoting a lot of space and visual attention to something the user can't do. I suggest changing it to this:

![after](https://user-images.githubusercontent.com/24388/31192653-b64897fe-a8f6-11e7-984c-3289f59f9c88.png)

Changes: 
- top line removed
- Text changed to "Comments closed." (Removed "are".)
- Text left aligned instead of centered. (Aligned with the left edge of the comment text above.)

I think this is better because it draws the eye less, but still informs the user as to why the comment form isn't there. It's more consistent with where the "Enter comment" text is when it's there. It also saves some vertical space.

Thoughts, @jancavan ?

**Comment by jancavan** [comment]
Good suggestion! I gave it a shot here: https://github.com/Automattic/wp-calypso/pull/18560

I like it on Conversations, but it feels buried to me in fullpost where I kinda prefer it centered because it's more obvious, although I know we want to make it consistent.

![screenshot 2017-10-04 22 25 15](https://user-images.githubusercontent.com/4924246/31212051-e9f1ca10-a952-11e7-830f-71babe5de29e.png)

**Comment by bluefuton** [comment]
I like the change in Conversations but I think I also prefer it more prominent in full post 👍

**Comment by fraying** [comment]
Agreed! I was only thinking about Conversations here. Can we leave it centered on Fullpost?

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/18560
