### ISSUE TITLE
Post Revisions: Improve Diff Styling for Accessibility

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#18551]
## Current Styling:
<img width="387" alt="screen shot 2017-10-04 at 4 54 19 pm" src="https://user-images.githubusercontent.com/1587282/31199249-c5ffbb04-a924-11e7-8659-4972858b2339.png">

## More Accessible:
<img width="328" alt="screen shot 2017-10-04 at 4 52 21 pm" src="https://user-images.githubusercontent.com/1587282/31199125-6d3bee84-a924-11e7-93fc-3b35d6dd2d5c.png">

The bottom borders are 2px & colors are “WordPress.com Blue” and “Error Red” from the [Design Handbook](https://wordpress.com/design-handbook/colors/)

Backgrounds are on the right here:

<img width="185" alt="screen-shot-2017-09-27-at-3-55-33-pm" src="https://user-images.githubusercontent.com/1587282/31198995-16551870-a924-11e7-9110-c271860f10d0.png">

**Comment by frontdevde** [comment]
Not sure if the plan is to replicate the design in `More Accessible` 1:1. Afaik it's not possible to achieve that effect without turning the individual lines into their own tags.

The background/border position is defined by the font size, so to get them to overlap we'd need to reduce the line height. While they overlap, the following line overlaps the preceding one:

<img width="181" alt="screen shot 2017-10-10 at 11 25 53" src="https://user-images.githubusercontent.com/1562646/31379390-62aa06a2-adae-11e7-92cd-652e0c520504.png">

If we reduce the line height a bit, we can make the lines stick to each other:

<img width="297" alt="screen shot 2017-10-10 at 11 25 39" src="https://user-images.githubusercontent.com/1562646/31379586-ed045320-adae-11e7-8d6f-5e8c46b8fe83.png">

The issue here is that we change the line height compared to what it used to be before. 

Imo we probably would want to leave the line height as is and just change the background/border like so: 

<img width="354" alt="screen shot 2017-10-10 at 11 21 57" src="https://user-images.githubusercontent.com/1562646/31379642-27b8e1d4-adaf-11e7-8a72-db6e38ff336f.png">

**Comment by jblz** [comment]
Thanks for the consideration and explanation about the overlap effect.

Let's just leave the line height alone and stick to the colors for now.
Make sense, @shaunandrews?

**Comment by marekhrabe** [comment]
Closing this because of #18688. Feel free to reopen for further styling update
