### ISSUE TITLE
Simple Payments: Multiple Buttons not loading in Internet Explorer

### ISSUE THREAD

**Issue by JasonSnow-Mad** [Automattic/wp-calypso#18552]
#### Steps to reproduce
1. Create multiple simple payment buttons.
2. Insert more than 3 on one page.
3. Load in Internet Explorer
4. Does not load all buttons on page

While all buttons show in Chrome and Firefox, in Internet Explorer 11, only the first three buttons are loading on my test site.

Expected: Chrome Browser:
![chrome-simple-payments-buttons](https://user-images.githubusercontent.com/8810295/31202672-802a0370-a931-11e7-8a56-35611c351c30.png)

Internet Explorer 11:
![ie-simple-payments-no-button](https://user-images.githubusercontent.com/8810295/31202685-8f668732-a931-11e7-96f4-a0f564343587.png)

 #user-report

**Comment by pauljacobson** [comment]
This is based on user feedback. I'm unable to test as I don't have a Windows machine.

## URL

962430-zen

## What the user expected

Render the menus for `Domains`, `Plans`, `Settings`, and `WP Admin` in Calypso in the browser. The user used IE 11.0.9600.18920.

## Steps to reproduce

After attempting to access these menus in IE 11, the user switched to Chrome and was able to access these menus, as would be expected.

## What happened instead

The `Domains`, `Plans`, `Settings`, and `WP Admin` menus in Calypso did not render in IE 11.

**Comment by rachelmcr** [comment]
I tested the original issue on Windows 10 / Internet Explorer 11 using Virtualbox, and the buttons worked as expected. All 5 buttons appeared in the editor and on the front of the site, and I confirmed they appeared on the front of the site while logged out of WordPress.com as well. The buttons also work as expected on the site.

I'm closing this issue as resolved, but please reopen if there are more specific conditions to reproduce it.

**Comment by senff** [comment]
Issue still occurs. User reported this in 1377611-zen.

https://recoveryonthebeach.com/2018/08/26/register-pay-may-june_september/

Also reproducable on test site:
https://senfftestwpplanspremium.wordpress.com/2018/08/30/payment-buttons-test/

Great amount of errors in console (not pasting actual errors cause I'm not sure which ones are relevant):
![paypal-ie](https://user-images.githubusercontent.com/1710669/44868244-4afd1680-ac58-11e8-93b6-6d8179a50a62.png)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
