### ISSUE TITLE
Media Editor: displaying two images, two Edit buttons, partial Done button

### ISSUE THREAD

**Issue by deancroyal** [Automattic/wp-calypso#18641]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/alwaysoverdone.com (my personal site)
2. Select an image to edit.
3. Select Edit from the top to edit the image.
4. An editor window will open.

#### I expected
- the ability to edit the image.

#### What happened
- two of the same image appear, along with two Edit Image buttons, and a partial "Done" button in the lower-right corner.

#### Browser / OS version
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Mac OS High Sierra 10.12.6 (16G29)

#### Screenshot / Video

<img width="967" alt="screen shot 2017-10-07 at 8 25 53 am" src="https://user-images.githubusercontent.com/13387217/31309415-abd3746a-ab3a-11e7-9d91-751991081e1a.png">

Sample Video: https://cloudup.com/csSA5IYb0qm

#### Context / Source
Was contacted in live chat by customer with Atomic site here: https://wordpress.com/media/bershatsky.com

**Comment by jeremeylduvall** [comment]
This is temporarily fixed with #18642 but per the comment [here](https://github.com/Automattic/wp-calypso/pull/18642#pullrequestreview-67841900) I'm going to leave it open for a better fix. Right now, we're including the `post-editor/media-modal/style` sheet in both [`_components.scss`](https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/_components.scss) and the [`post-editor.scss`](https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/sections/post-editor.scss#L59) section. We can either move this stylesheet only into `_components.scss` so we're not duplicating it or create a new section for the `/media` route.
