### ISSUE TITLE
Jetpack Connect: Plans page can have a horizontal scrollbar with Happychat opened 

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#18660]
As @sirreal noticed in https://github.com/Automattic/wp-calypso/pull/18573#pullrequestreview-67920256, on smaller displays we can observe a horizontal scrollbar when we open Happychat in the plans page.

**Comment by tyxla** [comment]
Digging further, this doesn't seem to be something that our Happychat integration is causing. If you resize your window to be narrower without Happychat opened, you'll still see a horizontal scrollbar, allowing you to scroll through all plans.

I'm not sure if that's expected though, cc @rickybanister for opinion.

**Comment by rickybanister** [comment]
The plans page (prior to adding happychat) was resonsive. It collapses into a stacked view instead of the columnar view. 

Can you investigate any larger markup changes that may have occurred here? 

cc @mattwondra (in case this has been noted on any other screens)

**Comment by mattwondra** [comment]
It sounds like @tyxla noted there's some regression in the plans page even without Happychat (there's still a horizontal scrollbar that appears).

But it's worth noting that just fixing the HC-closed use case, won't fix the HC-opened use case. The responsiveness of the page is dependent on the browser's width, so that when the browser gets narrower and the content has less rendering space, it shifts. But when Happychat is open, the page content suddenly gets less rendering space even though the browser width is the same. So you'll need to trigger the "responsive view" of this page at wider sizes when Happychat is open. I _believe_ some other pages have implemented this but I'm not certain which.

The alternative approach is to use the bottom-anchored "floating widget" version of Happychat in this page. Longer-term, this will be the standard Happychat customer experience (not the anchored sidebar view) so that may be a reason to consider using it here.

**Comment by tyxla** [comment]
AFAIK we haven't done any markup changes very recently, @rickybanister. And it doesn't seem to be related with Happychat at all - the same behavior can be observed with a more narrow width, for example the iPad in portrait orientation (768px):

![](https://cldup.com/G7gtKQqfGm.png)

The same can be observed for all mobile views, as well. The container has a scrollbar and allows the user to scroll, which I'm not sure is what we want.

Looking further, it seems this has been introduced in #15481. Maybe it was done intentionally, cc @fditrapani

**Comment by fditrapani** [comment]
> The container has a scrollbar and allows the user to scroll, which I'm not sure is what we want.

This was introduced with the plans change I made. I made the plans scroll horizontally for mobile devices. The horizontal view made it easier for people to compare the plans side by side without hiding any content. 

I admit it's not super obvious if you're looking on a desktop but it was very obvious that it was scrollable for people when I tested it out on mobile devices.

**Comment by tyxla** [comment]
Thanks @fditrapani. 

What do you think @rickybanister, should we keep it as-is?

**Comment by rickybanister** [comment]
@fditrapani can you point us to any results or data or insight about this solution, is it helping with mobile conversion? Is it worth keeping or should we explore another solution?

**Comment by fditrapani** [comment]
Although we didn't reach significance on mobile, we did see an increase in mobile conversions. I have two posts here: p5XAZ9-1v5-p2 and here: p5XAZ9-1uY-p2 with the results. 

We could look at other solutions or iterating on this one too. One suggestion would be to add [<] [>] buttons to make it more obvious that the content is interactive and to give people another way of navigating the content.
