### ISSUE TITLE
Jetpack Connect: Old help buttons and links appear on connect screen when using browser's navigation buttons

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#18663]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Log in to a WordPress.com account.
3. Go to URL: https://jetpack.com/
4. Select "Install" in the top right.
5. On the Plans screen, select a plan.
6. Confirm the "Connect a self-hosted WordPress" screen loads with the Happychat button.
7. Use the browser's back button to go back.
8. Use the browser's forward button to go forward again to the "Connect a self-hosted WordPress" screen.

#### What I expected

I expected to see the Happychat button again immediately.

#### What happened instead

I saw the “Install Jetpack manually”, “Start a new site on WordPress.com” and the old help button for a moment before the Happychat button loaded again.

![screen shot 2017-10-09 at 3 59 18 pm](https://user-images.githubusercontent.com/8658164/31345826-e09bab1a-ad0e-11e7-9b3b-0c621e01f644.png)

#### Browser / OS version

Mac OS 10.12.6, Chrome 61

#### Screenshot / Video

https://cloudup.com/cyMjT4MfFUg

#### Context / Source
#manual-testing

**Comment by tyxla** [comment]
While this is a valid point, i wouldn't consider it a bug. All of it is expected behavior.

We're displaying the old help button along with the other buttons there in case Happychat is not available for the current user. And in the meantime, while the Happychat client is connecting, it's not available; which is the reason for the other buttons to be shown. 

It's worth to mention that the same will happen if there's no operator available - the users will see the old buttons. Then, whenever an operator gets available, the new Happychat button will be shown immediately instead.

With that in mind I'd say this is better for the end users: we want to be able to present the users with alternative means to contact us even when live chat is not available for them at this time.
