### ISSUE TITLE
Edit Imaging Noop

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#18727]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/siteName
2. click on an image and then click edit
3. then click the big "Edit Image" button

#### What I expected
some sort of image editing functionality to appear

#### What happened instead
nothing

#### Browser / OS version
Mac OS X, Chrome latest

#### Screenshot / Video
Heres a picture of the button:
<img width="898" alt="screen shot 2017-10-10 at 9 50 16 pm" src="https://user-images.githubusercontent.com/4656974/31418618-10ed1046-ae05-11e7-9a4e-f6cb2f75de2e.png">

**Comment by hoverduck** [comment]
Note that the image editor works fine if opened from inside the Add Media dialog in the post/page editor

**Comment by rachelmcr** [comment]
@samouri possibly a side effect of https://github.com/Automattic/wp-calypso/pull/18678?

**Comment by samouri** [comment]
@rachelmcr I found the issue while #18678 was in staging. The first thing I did was check if the issue also existed in production, and it did.  Because of that I don't think #18678 caused it but I could have messed up my flip to production or had something funny cached

**Comment by rachelmcr** [comment]
Ah, gotcha. Ignore me. :) I was thinking it must have been a new bug from right around then because image editing was working for me just a couple hours earlier — but I was mistaken, because I was looking at image editing in the editor (which still works) rather than in the Media section.

**Comment by ockham** [comment]
I think I might've caused it with https://github.com/Automattic/wp-calypso/pull/18705. Turns out the `default` export (which I had to use, since it's `localize()`d, as opposed to the named `export`, [overrides some props](https://github.com/Automattic/wp-calypso/blob/24e64dbd513ca9b1e73a8243d23543b0531cae52/client/post-editor/media-modal/detail/index.jsx#L99-L102) in its `connect()` statement)...
