### ISSUE TITLE
Editor: Format option opens with mouseover if inserter option is open. 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#18784]
All dropdown in the editor should open with click, not mouseover. However, the format option opens with mouseover if the inserter is already open, but reverse is not true.

![untitled2](https://user-images.githubusercontent.com/908665/31496200-4fca6d60-af52-11e7-88f6-d2e3505f7a10.gif)
_The format option opens with mouseover if the inserter is already open._

---
![untitled3](https://user-images.githubusercontent.com/908665/31496209-59fbba8c-af52-11e7-9325-b30cb64adf05.gif)
_The format option stays open even I mouseover the inserter, and the format option stays open. I think this is how it's expected to behave._

Related #18719

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
