### ISSUE TITLE
Domains: consolidate whois and checkout contact forms

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#18808]
#### Background
Two domain-related forms — [domain-details-form.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/domain-details-form.jsx) and [form-card.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx) — share much of the same logic and field components.

This task is to investigate and try a possible avenue for consolidation, particularly in relation to the contact details fieldsets, which may warrant creating a common component.

#### Current domain checkout form
<img width="725" alt="checkout" src="https://user-images.githubusercontent.com/6458278/31535032-25041c68-b045-11e7-9fcf-e52c07071f02.png">

#### Current Whois contact update form
<img width="736" alt="whois" src="https://user-images.githubusercontent.com/6458278/31535021-19c07e46-b045-11e7-956a-2ef3fb908735.png">

#### Areas for consideration
* the usefulness and lifespan of `formState` Controller
* how to handle various UI states of the form itself, for example conditional rendering of field groups and different address formats.
* a common approach to prop handling
* how to balance code duplication and reuse where fields are used {n} times over several components.
* _More as they arise..._

#dogfooding

**Comment by klimeryk** [comment]
Yes, _please_ 🙇 It's been a PITA to update them both, and of course divergences cropped up in the past. No idea why it was written as two separate forms, probably one was written first (the checkout one?), then the other copied, instead of sharing some code.
Now, the checkout one is on Redux, while the WHOIS update form is using form-state. I'd use the Redux one as the base.
Love to discuss this further if you want (though, next week I'm on a meetup). One gotcha that comes to mind about the WHOIS update form is that it's slightly different for WWD domains and OpenHRS/SRS ones (the latter ones have the Designated Agent fields... unless it's a ccTLD 😀 ).

**Comment by ramonjd** [comment]
Great, I'll ping you in a week or so after you're back. I'll have more information by then too. :)

> checkout one is on Redux

The checkout form also uses `form-state`  to control the fields, but I see the user/contact details are cached in the redux store, unless I've totally missed something. 

We could store the form state in redux, and then handle form controls and validation some other way, internally or otherwise. I don't see it as much extra work to patch in some validation, but I reserve the right to pass that statement off as overly-optimistic at a later date :)

>  One gotcha that comes to mind about the WHOIS update form is that it's slightly different for WWD domains and OpenHRS/SRS ones 

*Very useful* to know. Thanks! I'll poke around and try to wrap my head around it.
