### ISSUE TITLE
Jetpack Security: Disable Two-Step Authentication Option When Two-Step Isn't Yet Enabled

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/wp-calypso#18858]
When setting up a Jetpack-connected site to use SSO with two-step authentication, if two-step isn't already enabled on the account, trying to activate that option produces an error sometimes. 

I was helping a user with this and we were continually seeing an error when trying to activate it on his account, but the first time I tried on my own account, it appeared that the settings saved. 

<img width="580" alt="screen shot on 2017-10-15 at 09 3a29 3a34" src="https://user-images.githubusercontent.com/22805865/31585179-8a99097a-b18b-11e7-9367-d59b907cdfc1.png">

Steps to reproduce:
1. Open a new WordPress.com account (without SSO set up).
2. Connect Jetpack.
3. Navigate to Settings -> Security for that site in Calypso.
4. Click "Allow sign in using WordPress.com accounts."
5. Click "Require two-step authentication" to activate it. 

It would even better if we could direct users to set it up two-step or include a tooltip about why it's disabled.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
