### ISSUE TITLE
Plan label in sidebar positioned poorly in Firefox

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#18893]
Using Firefox (latest), go to My Sites in Calypso, for any site with a paid plan. Observe poorly positioned label for your plan level in the sidebar:

<img width="306" alt="screen shot 2017-10-16 at 12 39 32 pm" src="https://user-images.githubusercontent.com/108942/31630376-a5f58264-b273-11e7-901b-7cbe25711b7e.png">

Additionally/separately, the label should probably change to white text when the Plans item is active, although that appears to be cross-browser.

**Comment by AnnaMag** [comment]
Also happens for `Free` Plans (both .com and .org)
![screen shot 2017-11-13 at 16 24 51](https://user-images.githubusercontent.com/13561163/32733272-14ccc6f8-c88f-11e7-9f79-040caf796c7a.png)

**Comment by folletto** [comment]
Note, I can reproduce it only at these conditions:

1. New fresh tab (hard reload works too)
2. No scrollbar in the sidebar

**Comment by AnnaMag** [comment]
I agree that this seems to be Firefox odd behavior-- the issue gets fixed upon manipulation of layout influencing properties. 

Just for the record here: the layout differs, because the remaining entries/sections use the same component, which sets up the icon on the left-hand side and takes care of the positioning and responsiveness of the right-most component (e.g. button). Here, it is not used because we have no JP icon at hand to pass as a prop, so current implementation attempts to mimic that component 
( not always successfully :) ).
As we spoke, let's fix it as-is to avoid that odd visual effects https://github.com/Automattic/wp-calypso/pull/19753 , and aim for a proper fix ( using svg JP icon) as a follow-up.
Thanks @folletto!

**Comment by AnnaMag** [comment]
For the sake of completeness: 
there is an svg size-ready icon we could use to provide a more solid solution https://github.com/Automattic/gridicons/issues/240#issuecomment-316532521.
An idea would be to modify the `SidebarItem` component to take as a prop an icon or svg, and use it for Plans in the same way as the remaining entries do. 
Let's wait a bit before going that path to see if the JP icon becomes part of an external repo 
 https://github.com/Automattic/gridicons/issues/261
