### ISSUE TITLE
Comments: remove fuzzy paging for fallback

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#18942]
Currently we show fuzzy paging for Jetpack sites in the /comments sections. This was a side effect of us filtering for comment type. But since we now support all types, the comment list response should include a full count.

To reproduce:

- Navigate to /comments
- Select a Jetpack site with more than 5 pages of comments
- Notice that there are 5 pages
- Click on page 5
- The pager will now show more pages

**Comment by Copons** [comment]
This requires more thought than I expected.
Even using the actual comments count returned by `/sites/$site/comments/`, we still lack the one thing that makes the tree unique: a list of all the comments IDs.

In other words, let's compare what happens when paginating, assuming for clarity that:
- We show 3 comments per page, instead of 20.
- The current implementation of List requests max 6 comments (the 3 we show + the next 3), instead of 100 (the 20 we show + the next 80).

Shown is the comments (or comments IDs) available in state (`highlighted`: the comments displayed in the page):

| Action | Tree | List (current) | List (real count) |
| --- | --- | --- | --- |
| First Load on page 1<br>(offset: 0) | `1 2 3`<br>4 5 6<br>7 8 9<br>10 11 12<br>13 14 15 | `1 2 3`<br>4 5 6 | `1 2 3` |
| Switch to page 2<br>(offset: 3) | 1 2 3<br>`4 5 6`<br>7 8 9<br>10 11 12<br>13 14 15 | 1 2 3<br>`4 5 6`<br>7 8 9 | 1 2 3<br>`4 5 6` |
| Switch to page 4<br>(offset: 9) | 1 2 3<br>4 5 6<br>7 8 9<br>`10 11 12`<br>13 14 15 | 1 2 3<br>4 5 6<br>7 8 9<br>`10 11 12`<br>13 14 15 | 1 2 3<br>4 5 6<br>10 11 12 |

What happens in the last case is that we request a **non consecutive** page (meaning: we pass an offset and a limit) from the API, which respond with only the comments contained in that page.
Then, when we try to display them, we slice the comments list on that page (again, with offset and limit), and... we go out of the array bounds.

To be honest, if we don't find a quick and painless solution, the amount of work and workarounds required to allow for this entirely new scenario is just not worth it to support outdated JP sites.

**Comment by rodrigoi** [comment]
> To be honest, if we don't find a quick and painless solution, the amount of work and workarounds required to allow for this entirely new scenario is just not worth it to support outdated JP sites.

Considering that support for Comments on Calypso is a relatively new feature, I don't think we need to jump through that many hoops to support outdated Jetpack sites. I think it's perfectly reasonable to nudge the users to upgrade their Jetpack versions.

**Comment by gwwar** [comment]
Do the page/number query arguments not work on this endpoint? I'd expect us to only need to fetch one page at a time. If it turns out we have a limitation, let's work on adding an upgrade nudge here.

**Comment by gwwar** [comment]
Closing this out since we're using client logic for the paging (we'd need another redux tree if we'd like to use the server logic).
