### ISSUE TITLE
[Store] Total Product quantity showing up empty when only variations are filled up

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#18952]
When filling quantity for products, filling up only the quantity on the variations will leave the total quantity of stock empty. This makes sense on pricing, as prices may differ depending on the variation of the product, so a global price may not make sense, but not for quantities, where I expect the sum of all variations would be equal to the total of the available stock. 

This can be seen here: p90Yrv-es-p2 on the minute 9:30-10:20

**To reproduce:**

- Go to https://WordPress.com/store/product/domain.com
- Create a new product
- Add a number under the inventory row, but just by product, not in the "All variations" row (leave that empty)

<img width="1133" alt="screen shot 2017-10-18 at 14 10 26" src="https://user-images.githubusercontent.com/3812076/31719122-acfa981a-b412-11e7-83ff-0d7f7b0824cc.png">

- Save changes
- Go to https://WordPress.com/store/products/domain.com
- See how the total quantity under Inventory shows empty ( - ) even it should be a total of 10 items in stock

<img width="1137" alt="screen shot 2017-10-18 at 14 11 32" src="https://user-images.githubusercontent.com/3812076/31719130-b79663b2-b412-11e7-92de-cd976f31e9fa.png">

**What I expected:**

- On https://WordPress.com/store/product/domain.com, to see the "All Variations" row filled automatically for the Quantity variable.
- On https://WordPress.com/store/products/domain.com, to see a total stock of 10

**What happened instead:**

- On https://WordPress.com/store/product/domain.com, is confusing to see that text field empty, not sure if adding a number there will affect the stock or the stock-per-product will be taken instead
- On https://WordPress.com/store/product/domain.com, the Inventory shows empty ( - )

**Comment by justinshreve** [comment]
@kellychoffman / @jameskoster Is this something we want to change? When we originally worked on the product list, we intentional decided to do the dash for variable products.

We could add a total count of all variations if we think it is useful, but we'll also have to load data for all the variations in the list to get each count. I'm not 100% sure how useful a total combined inventory count is though. If I have a T-Shirt product with 5 different colors and 3 different sizes, an inventory count of "200" isn't useful. How many Red smalls do I have? I'll have to open the product anyway to see.

**Comment by kellychoffman** [comment]
Good question. Other services to do something that I think might be useful. They display the inventory for a single variation, the lowest. IE `10 in stock for 1 variation`. This seems more useful that just displaying a `-`.
