### ISSUE TITLE
Signup: Activation email notice broken

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#1914]
When clicking "Resend activation email" a user will see a notice like this:

<img width="1415" alt="screen shot 2015-12-22 at 11 38 52" src="https://cloud.githubusercontent.com/assets/275961/11954543/55423bba-a8a1-11e5-8395-7868bbf55ad6.png">

The {{email /}} placeholder should be replaced with the user's email address.

**Comment by stephanethomas** [comment]
It doesn't work because the [`email` component value](https://github.com/Automattic/wp-calypso/blob/95233771c529fce20515525742ce6b43f3de214a/client/components/email-verification/email-verification-notice.jsx#L87) is not enclosed with a tag and as such is not interpreted as a React component (I guess it was enclosed by a `<strong/>` tag at some point). The root error is hidden but this will be fixed by https://github.com/Automattic/wp-calypso/pull/1915/.

**Comment by stephanethomas** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/1966.
