### ISSUE TITLE
Login: Create Drop-Down for Multiple Usernames

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/wp-calypso#19193]
Quite a few users have multiple usernames to log in. This can get messy with the log out and log in processes, as the most recent log in is the one displayed on the page by default. 

Can we add a drop-down list that contains all of the most recent log ins for a site?

Internal Ref: 751876-zen

**Comment by ngarnier** [comment]
Hello,

A dropdown would be nice, but a first step could even be easier. You could just let the user land on the login page where they have to input their login and password (modern browsers do the job of remembering credentials already well anyway, including when users have different accounts) instead of automatically logging users in.

Cheers

**Comment by stephanethomas** [comment]
@tmmbecker: I'm going to close that issue as displaying the more recent email addresses (or usernames) on the `Login` page is something that is already handled by the browser itself:

<img width="457" alt="screenshot" src="https://user-images.githubusercontent.com/594356/34440909-caf6c756-ecb8-11e7-878c-96c0cd09f88b.png">

**Comment by ngarnier** [comment]
The issue is not with remembering logins, but actually landing on the login page. 

On Gravatar, when you click on the Wordpress "Sign in" (see [screenshot](https://puu.sh/yQbaj/f2ba061da5.png)), you're automatically logged in, instead of being redirected to a login page where you can pick the email address you want to log in with. Might be an issue with how Gravatar uses the Wordpress Auth too.

You can test here: https://en.gravatar.com/
