### ISSUE TITLE
Portfolio: When adding new "Project type" in the menu, it's switched to "Tag"

### ISSUE THREAD

**Issue by blazevivan** [Automattic/wp-calypso#19214]
#### Steps to reproduce
Here is a short video: http://cld.wthms.co/NFvOYp

#### What I expected
To see the Project type in the menu

#### What happened instead
Project type is automatically switched to Tag

#### Browser / OS version
Chrome

#### Context / Source
I was not able to reproduce this case on my test site. I assume there was lack of categories and tags. 
What might be the issue here is that Tag used for a post is overriding the name of the Project type, as they have the same name in both cases. 
My workaround was to add a Custom link in the menu: https://peterburt.co.uk/project-type/drawing/

**Comment by senff** [comment]
Reproduced on test site:
https://senffbugreportsprojecttypes.wordpress.com/tag/fail/

See: http://prntscr.com/i3b6ui

Adding a tag "Fail" adds the correct link, e.g. https://senffbugreportsprojecttypes.wordpress.com/tag/fail/
Adding a Project type "Fail" adds the same link (instead of https://senffbugreportsprojecttypes.wordpress.com/project-type/fail/ )

**Comment by dphyled** [comment]
Encountered same issue in this ticket: 991809-t

Reproduced in my test site:
1. Added portfolio project with type TestProjectType. 
2. Went to Customizer and was able to add it as a Project Type menu item. 
3. Deleted menu item.
4. Added a post and created TestProjectType category.
5. Returned to Customizer and tried adding as Project Type, but it appeared as Category instead.

**Comment by lancewillett** [comment]
I don't think this is related to Calypso, right? Closing as duplicate (moved).
