### ISSUE TITLE
Themes: Try & Customize feature (Preview) not working for Atomic sites

### ISSUE THREAD

**Issue by samjhamdy** [Automattic/wp-calypso#19241]
#### Steps to reproduce
1. Open the Themes panel for any Atomic site
2. Click the three dots icon in a thumbnail from the library and click 'Try & Customize'

#### What I expected

This should open a preview of the new theme in the Customizer.

#### What happened instead

Nothing.

#### Browser / OS version

Chrome Version 61.0.3163.100 / OS X El Capitan Version 10.11.6

#### Screenshot / Video

https://cloudup.com/cJa_90gSykU

#### Context / Source

#user-report

Discovered during Business 1:1 session.

**Comment by sirbrillig** [comment]
Confirmed with Sam over Slack that the sidebar "Customize" button does work. For reference, [this](https://github.com/Automattic/wp-calypso/blob/756cfa434f79ba0c35bd8e47b1491d0c33dbf598/client/my-sites/sidebar/sidebar.jsx#L255) is where the Customize button decides what to do. Specifically it uses the [getCustomizerUrl](https://github.com/Automattic/wp-calypso/blob/756cfa434f79ba0c35bd8e47b1491d0c33dbf598/client/state/sites/selectors.js#L995) function.

The "Try & Customize" button is created [here](https://github.com/Automattic/wp-calypso/blob/b855b7a8a7e9f6a24e4fc87e8fe251cfd10603fd/client/my-sites/themes/theme-options.js#L121), which calls [tryAndCustomize](https://github.com/Automattic/wp-calypso/blob/b855b7a8a7e9f6a24e4fc87e8fe251cfd10603fd/client/state/themes/actions.js#L511). I wonder if the issue lies there.
