### ISSUE TITLE
People: Editor role on Jetpack site does not see Published blog posts

### ISSUE THREAD

**Issue by richardmtl** [Automattic/wp-calypso#19282]
In 756587-zen and 756682-zen the site owner reported that one (but only one) of their Editors on their Jetpack sites (both tickets are for a different site) is unable to actually see any posts on https://wordpress.com/posts/{site} , but they *do* see the number of published posts and drafts. I confirmed this report with the SSP. 

I was able to reproduce this by adding @NujabesSoul as an Editor to my test site as an Editor through the People -> Add New flow; he was then visible as an Editor both in my /wp-admin/ and in https://wordpress.com/people/team/reviewmysite.ca but when he went to https://wordpress.com/posts/reviewmysite.ca he only saw the following:

<img width="1349" alt="slack-imgs" src="https://user-images.githubusercontent.com/3676359/32180247-cdd0eb30-bd67-11e7-8ad0-8eb9c1a50f8e.png">

I'd expect that an Editor would be able to see all the posts and edit them. And as I mentioned, in the original report, only one user had this problem, not the others. Is it because of the way the users are being added to the site?

#user-report

**Comment by htdat** [comment]
The user is contacting again here 804850-zen

**Comment by aheckler** [comment]
This came up in 1942512-zen. Having them try a workaround: creating a new local user and a new WPcom user, connecting them, then see if it works.

**Comment by danjjohnson** [comment]
Noting for completeness that @aheckler 's workaround worked in this case.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
