### ISSUE TITLE
Simple Payments: Donate button with variable amount 

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#19303]
In [this thread](http://en.forums.wordpress.com/topic/simple-payments-three-questions), one of our users requested the option to let their site viewers choose their own donation amount.

**Comment by kristarella** [comment]
+1 #961457-hc

**Comment by chaitanyamsv** [comment]
+1 in #940419-zen

**Comment by alisterscott** [comment]
> shall we close #17367 in favor of this issue?

Sounds good, will close now

**Comment by alisterscott** [comment]
From #17639:

> Visitors to a site using the Simple Payments button are prompted to select the address where to send the item 'Delivery Address' and this could be -it is- messy in the case of donations.

**Comment by formosattic** [comment]
+1 in #4399976-hc

**Comment by formosattic** [comment]
+1 #4825773-hc

**Comment by arunsathiya** [comment]
+1 #2456138-hc

**Comment by singerb** [comment]
+1 from me setting up a site for a non-profit this weekend; will have to use the PayPal button embed instead.

**Comment by jordesign** [comment]
+1 from #8966090-hc

**Comment by arunsathiya** [comment]
9302346-hc

**Comment by scosgro** [comment]
+1 - User wanted a variable amount, so had to create/add code for their own button instead of using Simple Payments. They weren't very tech savvy, so it was fairly difficult for them to figure out.

8920073-hc

**Comment by cecoates** [comment]
The rates are different for "donations" on PayPal, so this would be fantastic.

Especially because smaller non-profits are often the ones who can't afford to upgrade to the Business plan. So having an easier setup than https://en.support.wordpress.com/paypal/ would be excellent.

**Comment by chaitanyamsv** [comment]
17137821-hc

**Comment by chaitanyamsv** [comment]
17859618-hc

**Comment by thebud15** [comment]
As it is currently, we need to refer users to the [PayPal button code](https://en.support.wordpress.com/paypal/get-paypal-button-code/) process to implement a donation button, which is a clunkier process than the Simple Payments button provides an experience for. This individual GH issue only represents a fraction of the requests for this that have come in over the 2.5 years since this has been open.

@andrewspittle considering your encouragement to surface long-requested enhancements to alleviate user pain points, do you have some insight on what this project's scope looks like, and whether we might see some movement on this issue? 
cc @lancewillett

**Comment by lancewillett** [comment]
Looping in @artpi as well.

**Comment by andrewspittle** [comment]
@thebud15, Artur was who I was thinking made sense to ping to. For now I'll wait for his review and input here as the Earn team is focused on a few related areas to this.

**Comment by supernovia** [comment]
Thanks folks :)  Hoping to see this one blossom.

**Comment by artpi** [comment]
Oh, I was not aware of this thread.
More of a "Donation" is indeed on our roadmap, linking this and please continue marking customer interest.

**Comment by artpi** [comment]
We have a donation button, we will not be implementing donations via paypal
