### ISSUE TITLE
Comments: in mobile consider using a different toggle than a dropdown for newest/oldest

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#19309]
Any quick suggestions here @megsfulton? If not @drw158 can a look. It feels like this is our default component styling.

**Comment by drw158** [comment]
It was a segmented control. Is it a dropdown now for space reasons?

**Comment by gwwar** [comment]
cc @Copons do you recall if this was intentional?

**Comment by Copons** [comment]
Actually, it's still a segmented control.
It was proposed as a dropdown in the M3-I3 design iteration (p3fqKv-5W1-p2 cc @megsfulton).

To be honest, I'd be up for a segmented control with chevron up/down icons on mobile.
Something like this but with Gridicons of course:

<img width="331" alt="screen shot 2017-11-02 at 23 08 51" src="https://user-images.githubusercontent.com/2070010/32354715-d8ff5b5a-c022-11e7-82ce-fc339cd34bfc.png">

**Comment by megsfulton** [comment]
It was something I was experimenting with a bit because I thought that on mobile it ended up breaking to a second line, but after taking a look today realized I got it mixed up with bulk edit. 

I know there was feedback from the last round that the toggle works better, I don't have a strong opinion on it and will default to @drw158. 

I worry that the up and down arrows won't be clear without labels. 

Newest / Oldest
![img_0034](https://user-images.githubusercontent.com/161697/32354938-6621d7ae-bfe9-11e7-8db5-54e625cb144d.PNG)

Bulk Edit 
![img_0035](https://user-images.githubusercontent.com/161697/32354935-647115b4-bfe9-11e7-964d-d33c647368c6.PNG)

**Comment by drw158** [comment]
Hm, that bulk edit is no good.

For the filter, let's just keep the segmented control

![screen shot 2017-11-03 at 11 23 56 am](https://user-images.githubusercontent.com/618551/32384636-89f8c994-c089-11e7-9800-3540149a6436.png)

**Comment by vindl** [comment]
Closing this since we are already using segmented control, so nothing left to do here.
