### ISSUE TITLE
Comments: should all comments only have the expanded mode?

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#19306]
We've received some feedback in p3fqKv-5W1-p2 and our interviews that it's more helpful if actions are always visible and comment content not be truncated.

**Comment by vindl** [comment]
FWIW I thought about this a couple of times - it seemed to me like the interface would look less cluttered with all of the comments expanded (and margins between them). With current layout we are likely forcing the users to scroll and click repeatedly while moderating, instead of just scrolling. 

What was the reason for adding the collapsed cards in the first place? If it was because of bulk edit, we could show them all expanded by default, and then switch to collapsed all view while in bulk edit mode.
