### ISSUE TITLE
Reader doesn't show new comments when they're made outside the Reader

### ISSUE THREAD

**Issue by pento** [Automattic/wp-calypso#1933]
The reader caches the comments too heavily, so it doesn't show new comments when they're made.

To reproduce:
- Open the Reader
- Open the post view of a post, then close it
- Open that post on its actual site in a new tab
- Comment on the post in the new tab
- Back in the Reader tab, open the post view again

Result: 

The new comment isn't shown.

**Comment by bluefuton** [comment]
Thanks for the report @pento!

I think the issue is not aggressive caching, but more that the comment fetch is currently very simple, and only grabs the first _x_ comments. There's no infinite scroll and no polling for newly added comments. Lots of room for improvement there, and it's pretty high on our hitlist for early next year.

Related: https://github.com/Automattic/wp-calypso/issues/793

**Comment by pento** [comment]
Ah, good explanation. I assumed it was cache, because I think I've seen the same behaviour with Likes.
