### ISSUE TITLE
Add color coding to the domain that needs DNS issues resolved

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#19504]
When a domain needs DNS problems resolved, it would be great to display a different color for the domain in question at https://wordpress.com/domains/manage/.

<img width="1027" alt="screen shot 2017-11-06 at 9 45 07 am" src="https://user-images.githubusercontent.com/10340370/32433058-faa7d976-c2d9-11e7-982b-28316ce2033f.png">

**Comment by klimeryk** [comment]
Thanks for the report and suggestion, @davoraltman. I think we all agree that the state domain management is in right now is far from ideal - and the whole section has a design overhaul planned for Q1 2018 to address that. I'm not sure if we should be doing such small adjustments/improvements - I'd prefer if we approach the whole thing in a holistic way, using notices and colors to indicate problems in a consistent way, for example. Otherwise we might run into a problem I've noticed recently on checkout:
<img width="535" alt="screen-shot-2017-11-01-at-23-39-17" src="https://user-images.githubusercontent.com/3392497/32439968-698e1230-c2f1-11e7-82bc-6a2d72d6f308.png">

And that's what I'm afraid will happen here if we bombard the user with colors here - it will be hard to tell what's a true warning and what to focus on.

But I'm just a developer (and part of the reason why domain management looks like it does right now...), so I'm tagging in @mikeshelton1503 to weigh in on here from design perspective. I'm sure we can at least take this idea into account when coming up with the new designs and look & feel of this section 👍

**Comment by mikeshelton1503** [comment]
Agreed @klimeryk. Thanks for the report @davoraltman. We plan to tackle domain management in Q1 likely so will keep this in mind.

**Comment by davoraltman** [comment]
Thank you, @klimeryk and @mikeshelton1503 !
