### ISSUE TITLE
Components: update pagination design to align with segmented control

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#19533]
Our current pagination component has a few problems:

- Hard to tell which page is selected.
- Easy to overlook.
- No text for the arrow buttons.
- Only works on gray background.
- Arrows are not close to the center numbers, hard to see and click.

![screen shot 2017-11-06 at 1 50 33 pm](https://user-images.githubusercontent.com/618551/32460898-d8876ae4-c2f9-11e7-9835-9f00eb211348.png)

I think we should update the design so that it looks like the segmented control, because the two UI components are similar in function.

This is a rough design for the pagination:

![screen shot 2017-11-06 at 1 49 31 pm](https://user-images.githubusercontent.com/618551/32460950-03720c96-c2fa-11e7-9d43-0866ca753105.png)

Ideally, it should look exactly like the segmented control, but still use button elements in the html, because I think that's most semantic.

![screen shot 2017-11-06 at 1 56 51 pm](https://user-images.githubusercontent.com/618551/32461095-6124ddaa-c2fa-11e7-8c23-d4beef4e822e.png)

One approach is to extend the segmented control component so that it could also be used for pagination.

cc @jameskoster

**Comment by drw158** [comment]
Currently we use pagination in Comments, Store, and Stats, but unsure of the exact locations.

**Comment by jameskoster** [comment]
> but still use button elements in the html, because I think that's most semantic.

Actually I think we could switch to anchors here. As I understand it, buttons are generally best for forms or javascript interactions where an `href` isn't required. 

I think it would look better on screen readers as well, to see a group of links rather than a mis-match of hyperlinks/buttons.

Additionally, with identical style properties `button`s and `a`nchors can display differently (looks like that might be happening in your screenshot, or it might be the icon). It's easily fixed, but consistent element usage would simplify things.

Having said all that, the `SegmentedControl` essentially performs the same task as pagination. So if that could be updated to handle pagination that would probably be preferable.

**Comment by drw158** [comment]
Sorry for the confusion, I am suggesting that _all_ of the pagination elements be buttons (no anchors). The buttons in my rough screenshot are misaligned because I didn't take the time to refine it. I believe we already have css in place that strips the default button styles so that they render the same. Regardless of the html, the pagination will look good when it ships.

I generally lean towards buttons because that is what is recommended for most actions in web apps, but I don't think we have any documentation on this, so either way is fine.

**Comment by shaunandrews** [comment]
It looks like this already happened:

<img width="448" alt="screen shot 2018-03-01 at 4 12 35 pm" src="https://user-images.githubusercontent.com/191598/36869938-66898f86-1d6b-11e8-9c3a-bac56194c211.png">

Closing. Reopen if I'm confused.
