### ISSUE TITLE
Jetpack Connect: Plans pricing page shows empty pop-up information

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#19581]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/:site, where :site is a connected Jetpack site.

#### What I expected
Pop-up windows triggered for Plan feature information to show the relevant summary.

#### What happened instead

The bottom feature in the Personal Plan, 2 last in Premium and 3 bottom ones in the Professional Plan trigger empty pop-up components  ( ->  screenshot below).

#### Browser / OS version
Firefox/Chrome, macOS Sierra

#### Screenshot / Video
Example for the Personal Plan:

![screen shot 2017-11-07 at 22 11 58](https://user-images.githubusercontent.com/13561163/32521137-4b0b04de-c40a-11e7-8e8d-cff79bad8895.png)

#### Context / Source

Follow-up to 1241-gh-jpop-issues

**Comment by nicoleckohler** [comment]
Noting my response from Slack here re: whether to respect the flag to not show the popup window or fill in text for all of these items:

> I do think all of the items should have text in the popups. I understand they’ll need to be translated but in many cases we need that extra space to properly explain what something that might be a new concept to a potential customer is.

And also noting according to @AnnaMag what is currently missing:

> We need extra pop-up info on: All Free features, All Personal features, All Premium features, 13GB Video Storage, Marketing Automation, Concierge Setup, SEO Preview Tools.

Also noting for myself/in case we can also do it with the same PR that I want to change the marketing automation description because it's not 100% accurate, [and was told to open an issue here anyway](https://github.com/Automattic/jetpack/issues/8122#issuecomment-342416963). ;)

**I'll reply again with missing content to add shortly.**

**Comment by nicoleckohler** [comment]
cc @sageBrownell

**Comment by oskosk** [comment]
This kind of looks like a regression. But I'm not super sure if the changes were intentional.

The behaviour seen here (info link for every feature instead of just those which have a description) has been introduced in #12994 with [this change](https://github.com/Automattic/wp-calypso/pull/12994/files#diff-801f5ceb927d2d46a3777a0f162507d7R340) which made `hideInfoPopover` prop be always `false`. 

The previous change to this came from #12461, introducing an A/B test.

Looks like before #12461 made [this change](https://github.com/Automattic/wp-calypso/pull/12461/files#diff-801f5ceb927d2d46a3777a0f162507d7R338), we were deciding whether to show or not popover according to what  `feature.hideInfoPopover` held.

**Comment by AnnaMag** [comment]
@nicoleckohler yes, we can do a single PR or if it takes longer for the Copy, a follow-u.

Thanks!

**Comment by nicoleckohler** [comment]
Okay -- **here are the copy additions** with a few tiny tweaks to titles while i'm at it:

**All free features:**
Also includes all features offered in the free version of Jetpack.

**All Personal features:**
Also includes all features offered in the Personal plan.

**All Premium features:**
Also includes all features offered in the Premium plan.

13GB Video Storage:
High-speed video hosting on our CDN, free of ads and watermarks, fully optimized for WordPress.

**Social Media Automation:** _(please retitle this from **Marketing Automation** -- if this doesn't fit, let me know)_
Re-share previously published content on social media, or schedule new shares in advance.

**Jetpack Concierge:** _(please retitle this from **Concierge Setup**)_
A complimentary one-on-one education session with a Jetpack expert.

**SEO Tools:** _(please retitle this from **SEO Preview Tools**)_
Edit your page titles and meta descriptions, and preview how your content will appear on social media.

Please let me know if any of these don't fit, have any other issues, etc. :) Thanks!

**Comment by AnnaMag** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/19665
