### ISSUE TITLE
Checkout: Thank You page's color for Personal Plan is easily confused with a warning notice

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#19690]
As reported in p99Zz8-7c-p2 and p99Zz8-6z-p2.

After a successful checkout, the user is shown the Thank You page - the color of the page is dependent on the plan that was purchased. However, for the Personal Plan, the chosen color is very similar to the warning notice, leading to a confusing result (seasoned Calypso users will think that something wrong went with the plan purchase, while new users could be more prone to ignoring the warning notice):
<img width="776" alt="screen-shot-2017-11-07-at-17-38-23" src="https://user-images.githubusercontent.com/3392497/32701855-3245bbfc-c7dd-11e7-8816-13ef5f0baaec.png">

For other plans, the distinction is clear. For example, the Premium plan:
<img width="776" alt="screen-shot-2017-11-07-at-17-45-15" src="https://user-images.githubusercontent.com/3392497/32701853-2a4893e8-c7dd-11e7-9c52-b98aac84b09e.png">

cc @fditrapani

**Comment by fditrapani** [comment]
Thanks for reporting this @klimeryk. I'm working on a new post signup experience that will most likely replace this screen in the next couple months. You can read about it in: p5XAZ9-1wt-p2.

Until then, we could look at changing the colour so that it isn't yellow. I'm not sure how important it is for the colours to match if the icon is there.

**Comment by klimeryk** [comment]
It seems that the changes from https://github.com/Automattic/wp-calypso/pull/17796 inadvertently fixed this issue :)
