### ISSUE TITLE
Editor: Cannot create a Sub-category with the same name as a top-level Category

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#19702]
Currently, you cannot create a Sub-category with the same name as a top-level Category, both in the Editor, and under `Settings > Writing > Categories`. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ > My Sites > Blog Posts > Add
2. Create a top-level Category such as `Reading` using the 'Categories & Tags' box in the Post Settings sidebar of the Editor
3. Now, try and create a sub-Category called `Reading` that goes another another Top-level Category.
4. Observe the error message: `Name already exists`

<img width="741" alt="tsdteg" src="https://user-images.githubusercontent.com/10125810/32726670-caf51e20-c89f-11e7-88bc-7700d6bf4b4f.png">

5. Go to https://wordpress.com/settings/taxonomies/category/ and try and create `Reading` as a Sub-Category on the site. Observe the same error message:

<img width="769" alt="xtqecl" src="https://user-images.githubusercontent.com/10125810/32726724-fe65ea50-c89f-11e7-9d29-d889195baa28.png">

6. However, the same Sub-category can be added via WP-Admin:

<img width="513" alt="zciilh" src="https://user-images.githubusercontent.com/10125810/32726742-119d21d8-c8a0-11e7-82f0-7e242e276e12.png">

<img width="926" alt="eynwu2" src="https://user-images.githubusercontent.com/10125810/32726745-139ef506-c8a0-11e7-9701-0d43294493c9.png">

Please let me know if you need any other info from my end!

**Comment by mahangu** [comment]
Reported by a user. Followed up in #789499-zen.

**Comment by tijosh** [comment]
Another report by a user in #6329789-hc

**Comment by tijosh** [comment]
User reported a similar issue in #13340236-hc

They want to add two subcategories that have the same name:

/category/maine/portland/
/category/oregon/portland/

They get "Name already exists." 

Using WP Admin is a workaround

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES

Checked for this issue in Core Trac, and found: https://core.trac.wordpress.org/ticket/6542#comment:3

> Since the move to general taxonomies it's no longer allowed to have identical slugs even though they end up in different contexts (see https://core.trac.wordpress.org/changeset/7336 )
