### ISSUE TITLE
Sidebar: Plan name initially misaligned on Firefox

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#19797]
Since switching to Firefox yesterday (57.0), I noticed that the plan name in the sidebar is initially misaligned when I load Calypso. To test, in Firefox 57.0, load https://wordpress.com/plans/my-plan/. You'll see this (notice plan level on left side).

<img width="975" alt="screen shot 2017-11-15 at 6 00 32 am" src="https://user-images.githubusercontent.com/7240478/32837319-51693db2-c9ca-11e7-8e5b-45c5e0a2b655.png">

If I resize the window very small and then large again, it gets aligned correctly. Here's a GIF of that in action (look at the plan name on the left-hand side):

![resize](https://user-images.githubusercontent.com/7240478/32837414-b94c6102-c9ca-11e7-8b50-bcdd74812087.gif)

Again, this only happens to me on Firefox. CSS for this item (`sidebar__menu-link-secondary-text`) is [here](https://github.com/Automattic/wp-calypso/blob/master/client/layout/sidebar/style.scss#L149). While inspecting the element, if you remove the `align-self: center;` declaration, it's all fixed up.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

This issue appears to be with the older user interface. Additionally, Firefox 57 was the initial release of Quantum which was a large reworking of the browser core, which likely led to the layout issue. 

As this issue is not reproducible, it is being closed with the label `Closed - Not Reproducible`.
