### ISSUE TITLE
.com Plans: unifying the look with the .org Plans

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#19861]
#### Steps to reproduce
1. Starting at URL: any with the `My Sites` sidebar visible

#### What I expected
.com Plans to have a view icon for `View Site` and no dash for `Stats`

#### What happened instead
-> screenshots below

#### Browser / OS version
Firefox, Chrome / macOS Sierra

#### Screenshot / Video
.com Plans
![screen shot 2017-11-15 at 20 01 24](https://user-images.githubusercontent.com/13561163/32862075-23e2b2f0-ca57-11e7-8e31-70fe70a3020f.png)

.org Plans
![screen shot 2017-11-15 at 20 02 11](https://user-images.githubusercontent.com/13561163/32862097-34d4122a-ca57-11e7-87e5-a02e4aaa1d11.png)

**Comment by drw158** [comment]
Just to clarify:

> and no dash for Stats

Do you mean the spark line? I did not know that Atomic sites did not have the spark line. We should keep it for .com, and there might be a plan to add it to Atomic sites.

>  a view icon for View Site

Do you mean the external arrow icon? I believe they are different because of Atomic site limitations, so the View Site link goes to a new tab. Sites on .com do not open a new tab for View Site.

**Comment by AnnaMag** [comment]
Closing for now.
