### ISSUE TITLE
Framework: Make DevDocs Faster

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19870]
At the moment, devdocs is our biggest section bundle at around 2 MB. That's because it loads all the components, blocks, and resources at once. These should all be async loaded within the devdocs section. Devdocs has to be a lean local resource to quickly prototype, reference, and improve the feature building experience of teams.

**Comment by tofumatt** [comment]
The title of the issue seems to point to a more general sense of improving devdocs' speed, but the contents point largely to the file size and the fact that nothing is async-loaded. Async loading (and reduced main bundle size) was implemented in #20690, so I think we can consider this closed unless there was something else intended in this issue–if so, please re-open. 😄

**Comment by tofumatt** [comment]
This might actually have encompassed a bit more than the file size and also referenced the lag encountered switching between Devdocs pages. I've filed #22756 to work on the actual lag/performance between loaded pages.
