### ISSUE TITLE
Editor: Copying an image with a caption leaves the caption div behind

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#1988]
Currently images with captions cannot be moved by dragging (#1989) instead they must be copied and pasted. However, when the image is copied the caption box stays behind. 
![calypso_caption](https://cloud.githubusercontent.com/assets/150348/12027876/92b905b0-ad82-11e5-8dae-53e5a6ad19ed.gif)

**Comment by lancewillett** [comment]
Seems edge-case-y to me — but I was able to repeat it in testing. Note: if you select the caption text before copying (or cutting) — it does paste, but is no longer formatted as a caption. Just plain text next to the image.

2nd opinion on leaving this open?

**Comment by designsimply** [comment]
It would be really nice if it were easier to move and cut/paste images more easily. 

Recommend closing, but recommending that because it's outside scope really (for now) and not because it's edge case. I think a lot of users run into problems managing media within their posts. Another example is being able to put two images side-by-side, something that's weirdly difficult for most people to do.

(Note to self: would be great to test image placement within posts in a usability study.)

**Comment by BandonRandon** [comment]
> Recommend closing, but recommending that because it's outside scope really (for now) and not because it's edge case.

Totally agree that media management is something that is frequently a struggle for many users. If this particular issue is not something we're going to address in V1 of the Editor let's close this. 

However, I hope that means that a V2 will be on the Horizon (pun intended).

**Comment by pento** [comment]
This is also a [bug in Core](https://core.trac.wordpress.org/ticket/35638).
