### ISSUE TITLE
When shared to Facebook Page (not personal profile), post title is replaced with website URL, if post title starts with [VOTE]. Plugin-enabled Business Plan sites.

### ISSUE THREAD

**Issue by grig-23** [Automattic/wp-calypso#19932]
#### Steps to reproduce
1. On plugin-enabled site with Business Plan, create a new blog post.
2. Start the title with [ symbol (I used [VOTE])
3. Share the link to blog post on Facebook Page (not a personal account)

#### What I expected
Expected to see the title.

#### What happened instead
Site URL appears instead of title

#### Browser / OS version
Chrome 61/Windows 10,
Chrome 62.0 on Windows 7 0.0.0 

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/13084901/32915854-f86df022-cb22-11e7-95cf-e949d4e3ef49.png)

#### Context / Source
This issue was reported in HC-1046352 and followed up 796530-zd-woothemes
When trying to enter URL in Facebook Sharing Debugger - this error comes up:
Missing Properties
The following required properties are missing: fb:app_id

**Comment by davoraltman** [comment]
I've tried different WordPress.com sites, Business plan or not, and it seems they will all return that warning when scraped:

`The following required properties are missing: fb:app_id`

<img width="1011" alt="Screen Shot 2019-11-05 at 8 00 54 AM" src="https://user-images.githubusercontent.com/10340370/68185705-72f5b180-ffa2-11e9-9484-bd07f048c1b9.png">

Reported in 59100746-zen

**Comment by designsimply** [comment]
It's been a while but I just saw this and ran through the steps again. I tested sharing a blog post to a Facebook Page from a WordPress.com Business site (with plugins installed) and the result looked the same to me regardless of whether or not the title started with a "[" character or not. ([48s](https://user-images.githubusercontent.com/1119271/109778187-c2adb280-7bc1-11eb-8455-046cebed42eb.mp4))

Here is how the shared post looked on Facebook when the title started with "["

![image](https://user-images.githubusercontent.com/1119271/109776673-161f0100-7bc0-11eb-879c-0633bac35ee8.png)

Here is how the shared post looked on Facebook when the title did not start with a square bracket character:

![image](https://user-images.githubusercontent.com/1119271/109776743-26cf7700-7bc0-11eb-9930-aa812ab7d4fb.png)

I think these shared posts are the expected result on Facebook's side, and I would like to add that it's possible that quite a lot has changed between the time this issue was first submitted and now. 

I recommend closing because it's been some time since the original report and sharing to Facebook appeared to work normally for me in a new test with Facebook showing content followed by a URL followed by a formatted card showing a place for an image, url, title, and content.
