### ISSUE TITLE
Function wrapper  "wrap-es6-functions" search not only in project folders but also in node_modules

### ISSUE THREAD

**Issue by dinarAkv** [Automattic/wp-calypso#19959]
Function in /wp-calypso/client/lib/wrap-es6-functions/index.js: 

```
[ 'codePointAt', 'normalize', 'repeat', 'startsWith', 'endsWith', 'includes' ].map(
		partial( wrapObjectFn, String.prototype, 'String#' )
	);
```

as I understand have to search usages of String functions only in project files. But it search also in node-modules. That's why [ issue #19195](https://github.com/Automattic/wp-calypso/issues/19195) appeared.

![Errors in my console about  issue #19195 ](https://user-images.githubusercontent.com/24462208/32953361-045a9324-cbc1-11e7-80ec-0f7213882e8e.png)

How I can find it. There is need to go to 
/wp-calypso/client/components/title-format-editor/index.jsx (and parse.js)
contains outer module import from node-modules:

```
import {
	CompositeDecorator,
	Editor,
	EditorState,
	Entity,
	Modifier,
	SelectionState,
} from 'draft-js';
``` 

In the same folder parser.js also contain importing draft-js module:

 
```
import {
	compact,
	flowRight as compose,
	fromPairs,
	get,
	map,
	matchesProperty,
	reduce,
} from 'lodash';
import { convertFromRaw, convertToRaw } from 'draft-js';
```

If comment those imports, errors in console in "http://calypso.localhost:3000/settings/traffic" ([issue #19195](https://github.com/Automattic/wp-calypso/issues/19195)) disappeared. 

So I concluded the reson of errors in [issue #19195](https://github.com/Automattic/wp-calypso/issues/19195) is searching **strtsWith** String functions not only in Calypso project files but also in libraries in node-modules. So there is need to fix function wrapper in /home/di/study/openS/wp-calypso/client/lib/wrap-es6-functions/index.js

particularly in 

```
[ 'codePointAt', 'normalize', 'repeat', 'startsWith', 'endsWith', 'includes' ].map(
		partial( wrapObjectFn, String.prototype, 'String#' )
	);
```

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
