### ISSUE TITLE
Comments: Authors should be able to moderate comments

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#19978]
Authors can't open the Comments Management, but they have comment moderation capabilities, at least partly.

Should they be able to use a "limited" Comments Management?

Props to @alisterscott for finding this!

**Comment by gwwar** [comment]
We should mimic what wp-admin currently does. Authors can view all pending comments, but they can only moderate comments on their own posts.

**Comment by gwwar** [comment]
See also https://github.com/Automattic/wp-calypso/issues/17687 for more behavior details.

**Comment by drw158** [comment]
Using the disabled button state sounds like a good solution.

**Comment by vindl** [comment]
From what I've seen there is no way to obtain this data from client without impacting performance further. The edit/moderate capability is not recorded in comment detail, and we would have to fetch parent post data in order to determine if current user is the author or has edit capability for it.

Seems like the best way to go would be to modify the comments endpoint in order to return this data along with other comment details.

/cc @Automattic/lannister if you have any other ideas.

**Comment by vindl** [comment]
What we can do until then is enable the sidebar link and allow authors to view comments. Every comment will have action buttons, so if they try to moderate the ones that are not authored by them they will run into error notices. Not sure if this is better then not showing them comments at all. ¯\_(ツ)_/¯

If you think this is fine for now let me know and I can spin up a quick PR for it.

**Comment by vindl** [comment]
@gwwar just occured to me that since we are forcing the comment detail request to `wpcom`, we  can update both sides right away without waiting for the next Jetpack release. 

https://github.com/Automattic/wp-calypso/pull/20636
D8703-code

**Comment by gwwar** [comment]
I do have a fallback in place to query the remote for details if the first try fails, but that seems like a good approach @vindl!
