### ISSUE TITLE
Upgrade banners: improve Copy in SEO/Ads 

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#20064]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/traffic/JP_connected_site
2. scroll down to `Search engine optimization` and `Google Analytics` sections

Let's improve the Description in the two Banners, e.g. so that the "upgrading to JP Pro"
bit is in the title OR body of the Banner (not both 😄  ).

#### Browser / OS version
Firefox, Chrome /  macOS Sierra

#### Screenshot / Video

![screen shot 2017-11-21 at 16 14 55](https://user-images.githubusercontent.com/13561163/33080052-6530f698-ced7-11e7-8072-95597f29fff6.png)

#### Context / Source

/cc @nicoleckohler for wordsmithing the Copy :)

**Comment by nicoleckohler** [comment]
Nice catch @AnnaMag -- also a good find since "plan" is capitalized in that Analytics message and it shouldn't be!

Suggestions for editing both:

> **Enable SEO Tools by upgrading to Jetpack Professional**
> Get tools to optimize your site for improved performance in search engine results

and...

> **Enable Google Analytics by upgrading to Jetpack Professional**
> Add your unique tracking ID to monitor your site's performance in Google Analytics

My question here would be if there are any other messages like this that appear for connected users in other sections. All of my sites are now on Professional so I can't check, but it might be worth looking again if you haven't already, just to be sure we're consistent with how we communicate upgrade items like this.

My preference would be to have the "upgrade to ___" bit as the heading as I have it above for all similar messages.

Thanks!
