### ISSUE TITLE
Sharing: Menu disappears when Publicize and Like buttons are disabled in Jetpack settings (AT sites)

### ISSUE THREAD

**Issue by julsyd** [Automattic/wp-calypso#20102]
#### Steps to reproduce
1. Starting at URL: testing34687.com
2. Go to WP Admin > Jetpack > Settings > Sharing.
3. Disable "Automatically share your posts to social networks" and "Allow readers to show their appreciation of your posts by adding a like button to your content".

#### What I expected
I expected "Sharing" to appear in the Calypso left menu.

#### What happened instead
"Sharing" is no longer visible in the Calypso left menu. All sharing settings can only be accessed via WP Admin > Jetpack > Settings > Sharing.

#### Browser / OS version
OS High Sierra 10.13.1
Chrome 62.0.3202.94

#### Screenshot / Video
JetPack settings: https://cloudup.com/c2JDbEn2GA2
Calypso menu: https://cloudup.com/cbniBz65nUl

#### Context / Source
Sharing buttons are still active, so users need to be able to easily access those settings from Calypso. Users should also be able to easily enable Publicize and Like buttons via Calypso, as normal, despite those settings being disabled in JetPack. It makes things confusing for users as they don't know the Sharing settings can be accessed via WP Admin, or where to even access them there.

#user-report
#manual-testing

**Comment by beaulebens** [comment]
This is effectively another case of "implicit activation" being required. We should show the UI here regardless (unless force-disabled via code, cc @ebinnion ). Then if the user decides to use any of the features, we can/should activate the appropriate modules behind the scenes.

**Comment by alaczek** [comment]
Since the recent implementation of the nav drawer sharing options now live under Tools > Marketing, and I verified it does not disappear when above options are disabled. There is a difference though.

With "Automatically share your posts to social networks" and "Add Like buttons to your posts and pages" enabled:
![image](https://user-images.githubusercontent.com/4550351/56935784-bfb18900-6b36-11e9-90cb-aa881d404a59.png)

Disabled:
![image](https://user-images.githubusercontent.com/4550351/56935761-9a247f80-6b36-11e9-989a-ff3bb77ef00c.png)

From my testing it looks like the options to enable/disable likes is available in both wp-admin and Calypso settings at all times. 

The only difference I'm seeing, is that "Connections" tab is not present in Calypso, when "Automatically share your posts to social networks" is disabled in wp-admin (and it can only be enabled via wp-admin). @juliasydnor would having the "Connections" tab be always present in Calypso be a good fix here?

**Comment by juliasydnor** [comment]
> would having the "Connections" tab be always present in Calypso be a good fix here?

@alaczek sounds good!

**Comment by jancavan** [comment]
This is very confusing. It's hard to tell if these settings are related to each other.

I'm curious why these settings need to be enabled in Jetpack before they are displayed in Calypso? Are we not able to display these settings by default in Calypso? Publicize won't be enabled anyway until the user connects each of their social media accounts. And from my understanding, none of the Sharing buttons will appear too unless they explicitly select which pages they want them to appear on?

![Screenshot 2019-07-03 09 52 20](https://user-images.githubusercontent.com/4924246/60610253-4160a580-9d78-11e9-934b-8e682d34350a.png)

In Calypso, "Connections" and "Sharing buttons" are separate tabs. Enabling the "Like" button is under "Sharing buttons". In Jetpack, enabling the Like button appears to be a separate card by itself and doesn't look to be related to the sharing buttons.

I also noticed a bug where even though I do have "Publicize" and "Sharing buttons" enabled in Jetpack, the "Connections" and "Sharing buttons" tabs are not being displayed. But once I click the "Update" button from the sidebar, then click somewhere on the screen, they randomly show up: https://cloudup.com/ci06M75tzhh

I would just display these settings in Calypso without the need for activation. However, if that isn't possible, as interim fixes to start, we could:

1. Update the Publicize card heading in Calypso to "Publicize connections" so it matches the card in wp-admin:

![Screenshot 2019-07-03 09 39 29](https://user-images.githubusercontent.com/4924246/60609432-808df700-9d76-11e9-9759-c98e8b63b5ba.png)

![Screenshot 2019-07-03 09 39 46](https://user-images.githubusercontent.com/4924246/60609436-8257ba80-9d76-11e9-8214-829354d9bf20.png)

2. Combine Sharing and Like toggles in wp-admin since "Configure your sharing buttons" link to "Sharing buttons" in Calypso which contains both settings:

![Screenshot 2019-07-03 09 46 03](https://user-images.githubusercontent.com/4924246/60609908-833d1c00-9d77-11e9-827d-7a60b989b145.png)

cc @jeffgolenski @alaczek @juliasydnor

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
