### ISSUE TITLE
Stats: quries plugins for all sites on page load

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#20129]
This make the page load really slow if the user has many plugins and many Jetpack sites.

#### Steps to reproduce
1. Starting at URL:
2. Go to https://wordpress.com/stats/activity/example.com

#### What I expected
For the page not query every sites plugins. 

#### What happened instead | Screenshot / Video
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/115071/33149622-40c64fc0-cf85-11e7-89fa-a0826828fbf0.png">

#### Context / Source
#dogfooding

cc: @psealock 
Since I think it is related to https://github.com/Automattic/wp-calypso/pull/17590

**Comment by psealock** [comment]
All the plugins are loaded so that changing sites from one store enabled site to a non-store enabled site does not break navigation.

We could hold off on querying the plugins until after the user clicks "Switch Site", but that isn't ideal because it might prevent a click if the plugins haven't returned yet.

One possible solution would be to always go to site stats when switching from one store to another.

I'll look into this one.

**Comment by enejb** [comment]
Another solution would be to query the shadow site and add the data that you need to the /me/sites api endpoint.  

We already store the list of active plugins on in the shadow DB so you wouldn't need a query an api call to get that info.

**Comment by justinshreve** [comment]
@psealock Per the comment above, there are actually two separate (new) flags you can use from /me/sites.

`options.is_wpcom_store` (AT + WC)
`options.woocommerce_is_active` (WC)
