### ISSUE TITLE
User that owns a single site cannot easily switch to/from hidden ones

### ISSUE THREAD

**Issue by dtougas** [Automattic/wp-calypso#20180]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Create a new user, and create a single WP site for them
3. Invite the user into a couple of other hidden sites (i.e. a p2 or fieldguide)
4. As that user, navigate to the admin of one of the hidden sites
5. Click on the "My Sites" link in the top left hand corner to reveal the Calypso sidebar
6. Click on "Stats" (or another link to a Calypso page) in the sidebar
7. Try to navigate back to the site the user originally created, there is no "Switch Site" link available

#### What I expected
I was expecting to see the "Switch Site" item in the sidebar all the time, instead, it just displays when I am in a WP admin.

#### What happened instead
I found myself trapped in Calypso, unable to switch sites.

Adding a second site fixed the problem. Removing the second site made the problem return.

#### Browser / OS version
Mac OS 10.12.6

#### Context / Source
I am in the process of familiarizing myself with Calypso and the WP environment as part of my trial for the Code Wrangler position. I have been given access to several internal blogs, and have a single blog of my own. So, this is a combination of #dogfooding and #user-report I guess.

**Comment by sstabrizi** [comment]
Just dropping a note as a +1 to this issue. The user was trying to access their site cscatlindotcom.wordpress.com but was only seeing cscatlin.wordpress.com. Took me some searching and asking around in Slack to find that the user had several hidden sites only accessable through wp-admin. Adjusted the stettings which gave the user access to the correct site. It would be really nice to see a calypso update that adds the ability to see hidden sites somehow.

**Comment by jamiepalatnik** [comment]
Similar issue in #6994892-hc. The user had one WordPress.com site, and one Jetpack site with a broken connection. When the Jetpack connection was broken, they could not switch sites or add a new site from the dashboard. Once the Jetpack connection was fixed, they could.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES

_I believe now if a user has multiple sites, but only 1 is accessible, the "Switch Site" option still appears and they can open that sidebar. We note the existence of hidden sites, while broken-connection-sites will just be missing._
