### ISSUE TITLE
Activity Log: RTL Display Issues

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/wp-calypso#20229]
![image](https://user-images.githubusercontent.com/574752/33247825-e6b69310-d2ee-11e7-9df1-11dfc8624bc6.png)

The arrow is pointing the wrong direction, and the ellipses is too far indented from the left.

cc: @eliorivero @MichaelArestad 

Props @rachelmcr

**Comment by MichaelArestad** [comment]
The indentation is intentional. It is the block reserved for the foldable card arrow for when we implement expanded events. The current build is using foldable cards with the exand/collapse part disabled for now.

I'm not sure how we fix the arrow, though. Definitely should be pointed the other direction. Good catch!
