### ISSUE TITLE
Activity Log: Change "Stats" to "Stats and Activity"

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/wp-calypso#20227]
@alisterscott pointed out that it may be difficult for users to find the Activity Log, and suggested this change the the navigation link in Calypso

![image](https://user-images.githubusercontent.com/574752/33246338-7b47435c-d2e1-11e7-9b63-0d13a9ad70be.png)

would become

![image](https://user-images.githubusercontent.com/574752/33246349-99b4a672-d2e1-11e7-899c-5210f9221fb2.png)

**Comment by MichaelArestad** [comment]
I think this deserves a larger discussion. Let's sit on this for the immediate future, but some alternate suggestions via brief conversation with @shaunandrews and @rickybanister are "Analytics" or perhaps another dreaded sidebar location called "History."

**Comment by MichaelArestad** [comment]
To clarify, I don't think this is urgent because folks will be led there via notifications and emails upon release and as issues occur.

**Comment by nicoleckohler** [comment]
I don't think it's _urgent_ but I would like to see this resolved prior to the full release, if possible: while users will definitely be directed there as you mentioned @MichaelArestad, I think it'd be really difficult for someone who later wants to find their log again to do so without remembering where in the (current) menu it is.

Having said all that :) I like "Analytics" as an option!

**Comment by rickybanister** [comment]
We need to test whatever we propose, and make sure it doesn't cause an adverse dip in people finding their stats page, or any other blow back or support concerns. Stats is the landing page and by far the most popular view in Calypso (and it's been called stats for a decade).

**Comment by samhotchkiss** [comment]
What is the concern about "Stats and Activity"

**Comment by nicoleckohler** [comment]
@samhotchkiss from a phrasing standpoint - I totally prefer it.

From a user standpoint - I think it'd potentially be too large on mobile/tiny screens.

**Comment by drw158** [comment]
I don't work on this feature, but here's an opinion from someone who works on Calypso:

This is a symptom of not having a great dashboard, and trying to lump unrelated things into Stats. From what I've seen, Stats and Activity don't really belong in the same category, so it's hard to find a single word that covers both. That said, I do understand why they are in the same menu item, and it's a compromise for getting the feature done sooner.

"Stats and Activity" is not a great solution, because I think of Stats and Activity as being almost the same. Seems redundant, and I think adds to the confusion that Activity actually refers to site user activity, not site visitor activity. Without knowing about the feature, I would think Activity means visitor activity on my site. 

Ideally we should think of a word that encompasses the contents inside, rather than combining words together. For example we don't say "Sharing Connections and Buttons" we just say "Sharing". Also, as Nicole pointed out, it is a very long label that is hard to digest.

Another solution might be to add an "Activity" button to the Stats menu item, similar to how "Following" has a "Manage Sites" button.

**Comment by rickybanister** [comment]
I would prefer to ship the rewind functionality today as planned and schedule some usability tests now that the functionality is complete to access user confusion. We are light on data at this point to determine if this is even a problem.

The activity log will not explicitly have any 'stats' at its launch, it is currently just a list. But it will definitely be the foundation for us to provide statistical, graphical insight to users about the activity on their site. This is mostly, but not entirely limited to admin users as well. Purchases and other types of activity will appear in the log, which for me brings it closer in line to the 'traffic' and visitor info we already display.

**Comment by MichaelArestad** [comment]
CC @shaunandrews because he's got ideas about dashboards.

**Comment by dmsnell** [comment]
Where exactly this lands doesn't seem like it would matter as much as how hard it is to get back to once someone has found it. I think it's probably far more important that we don't change it post-launch than to "get it right" before launch, and while I can understand that **Stats** isn't a perfect match, I don't see it as a _bad_ match. Right now it takes two clicks to get there: **My Sites** (defaults to **Stats**) and then **Activity**.

So to me it boils down to the question of what role we want it to play. Do we expect people to be using it all the time? I would hope not - I hope it's rarely used because that would mean that our customers aren't experiencing problems with their site. Ideally they'd only go there _in response_ to some problem.

With that I think it's _more important_ that we work towards being able to link directly to specific activities and get the notifications and emails to do that so that _when_ the unfortunate happens we can quickly direct our customers there.

Again, even if we miss the mark on the _most perfect_ home I think we'll do far more harm by moving it _after_ we introduce it to people than we could get by "fixing" it and throwing off their new habit.

**Comment by rickybanister** [comment]
I agree with everything you've said there Dennis, except for the harm it would cause to move it post launch. It didn't exist before, we'll be sending folks there for the first time, and if we receive lots of feedback, we can just move it and leave a guided tour in the old location and a guided tour in the new location informing people where it moved to—the harm will be reduced if we find a location for it that is more agreeable to a majority of users (in the event they don't like the current location). 

We will definitely be sending more traffic there from emails and notifications vs organic visits. Consider VaultPress currently—users install that plugin, and only visit it when they receive an email, or navigate to it from a link in wp-admin (we'll have that as well). 

The trick is we really don't know what the perfect location is before launch—launch is our first opportunity to gather real honest feedback because this functionality was not available to users before. I personally believe that it belongs in stats because I hope we can build some interesting visualization and insight tools for sites' activity, just as we have for their traffic. But that doesn't ensure that I'm right.

**Comment by lezama** [comment]
I think it is time to iterate on this! @rickybanister @keoshi @MichaelArestad, we need a decision so I am looking for a decider, what do you think?

**Comment by keoshi** [comment]
My 2 cents (since I missed the whole previous conversation while on sabbatical): I think it's too big of a decision to be taken this lightly, and it should be fine to leave it as is for now — people can already find it organically through Stats and Notifications.

Without proper marketing, documentation, and filtering it's not something we want to push harder on users, because it can actually be more confusing than helpful, and that could have a (relative) negative impact on how people perceive the value of this feature.

**Comment by rickybanister** [comment]
I agree. Our goal here isn't to promote the feature simply because we built it. 

If we want to test alternate language or wayfinding within the product we'll want to design a test with a clear goal and work toward it. 

I don't think the label itself will lead more folks to browse the log and I'm not even sure that should be our goal. Like @keoshi said, directing customers to the log when we have something interesting to show them seems more valuable. 

I would also like to see some iteration happen on the 'insights' view where it could become a better landing page than the traffic page (right now it is not a compelling page though). 

I'm going to close this thread for now until we have a more strategic goal in mind.
