### ISSUE TITLE
Site Preview: preview link uses siteurl instead of home

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#20240]
Start with a self-hosted site using Jetpack,  and where WordPress lives [in a subdirectory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory).

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/yoursite.com
2. Click on "View site" in the sidebar.
3. The preview will not open the site's homepage; instead it will try to open the `siteurl` value, where WordPress lives.

Reported in 807498-zen

**Comment by aheckler** [comment]
1930028-zen

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
