### ISSUE TITLE
Import: trigger a notification when an import is completed

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2030]
Raised by @rickybanister 

Pretty self-explanatory, currently we send a plaintext email, which doesn't help someone if they're looking at wp.com and not their email. 

A notification would close a loop here and be a nice upgrade to the experience.

**Comment by dmsnell** [comment]
Initial work-in-progress created in r131243-wpcom

![screen shot 2016-02-18 at 6 54 33 am](https://cloud.githubusercontent.com/assets/5431237/13145242/969c69d0-d60c-11e5-8293-ca34fc648d87.png)

This has a long way to go with styling I think, but it's easy to change and sending it on finished imports should be pretty simple.

cc: @drw158

**Comment by drw158** [comment]
I think the avatar image in the notification list should be the WordPress logo. It's possible another notification also does that, so we might already have the image. Maybe that was just a mockup I'm remembering.

We haven't switched to Gridicons for the notification list, but the `i` icon you chose is a good one for this.

I have some tweaks for the detail view:

![screen shot 2016-02-18 at 10 24 16 am](https://cloud.githubusercontent.com/assets/618551/13150243/91296200-d62a-11e5-90a3-b905d4b11166.png)

- Moved the image to the top.
- Added a period to the end of the first sentence.
- Added `has` before the word `finished`.
- Replaced `on` with `to` in the first sentence.

I'll have to make an image for this. We could either:

- Just use the WordPress logo.
- Custom graphic, probably just a cog icon or something.
- Use the service logo (Squarespace in this case).

The last one would require me to make an image for every service for the mobile apps, and we would have to update it every time we add a service to the Importer.

**Comment by dmsnell** [comment]
@drw158 I wondered if we could use the social logos here, but wasn't entirely sure the best way - maybe rasterizing them…

I'll update the code on wpcom

Thanks!

**Comment by dmsnell** [comment]
updated in r131267-wpcom except for the WordPress logo

**Comment by drw158** [comment]
Since we are on a tight deadline let's just use this image for the list and detail image:

/mu-plugins/notes/images/settings-update.svg

Should look something like this:

![screen shot 2016-02-18 at 3 48 49 pm](https://cloud.githubusercontent.com/assets/618551/13159383/2404c99e-d657-11e5-9401-fbc35745ead0.png)

**Comment by dmsnell** [comment]
<img width="793" alt="importfinishednote" src="https://cloud.githubusercontent.com/assets/5431237/13162964/09f027a6-d666-11e5-8310-6cc637511083.png">

Merged in r131299-wpcom.

I'll go ahead and stitch this into the import process and we'll be ready to close it :smile:

**Comment by rickybanister** [comment]
I sort of feel like this should be reversed. Instead of the `(i)` icon we should use a gear there since import/export are in site settings and that is the site settings sidebar icon. Regarding the avatar, this might be part of a larger conversation, but perhaps it should be a square site icon for the relevant site instead of a user or WordPress logo. That would help set the context for you. We could use that for several other types of notifications in the future (basically site-wide alerts).

**Comment by rickybanister** [comment]
They would be square instead of round (or maybe round-rect if it made sense).

**Comment by dmsnell** [comment]
Thanks @rickybanister. We used the gear because it existed and we didn't have to create a new design. We couldn't find the service-specific assets ready-to-use so we docked it for a future iteration. Right now we're under a time crunch so we unfortunately have to put out work that isn't up to par :(

**Comment by dmsnell** [comment]
deployed in r131398-wpcom

**Comment by lancewillett** [comment]
Testing notes from a quick import workflow:

Using Mac-n-Chrome, I started an import from wp-admin for my test blog. About 15 minutes later I received the notification:

<img width="817" alt="screen shot 2016-02-19 at 14 36 59" src="https://cloud.githubusercontent.com/assets/66797/13191326/1f6905d4-d720-11e5-92cf-8d7c6b09bcee.png">

**Comment by lancewillett** [comment]
I also got the email notification at about the same time.

<img width="791" alt="screen shot 2016-02-19 at 14 29 39" src="https://cloud.githubusercontent.com/assets/66797/13191342/3c049136-d720-11e5-9963-b06ee996ffa8.png">
