### ISSUE TITLE
Editor: Images are not loaded into Thumbnail Grid on linked HTTP Jetpack site 

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#20349]
This issue appears on Jetpack site without HTTPS (e. g. newly created Jurassic.ninja site)
When adding multiple images (only for Thumbnail Grid option) to the blog post - they fail to load due to <code>Mixed Content</code> issue:

```
Mixed Content: The page at 'https://wordpress.com/post/proud-plains.jurassic.ninja/7' was loaded over HTTPS, but requested an insecure image 'http://proud-plains.jurassic.ninja/wp-content/uploads/2017/11/x_22e93651-150x150.jpg'.
This request has been blocked; the content must be served over HTTPS.
```

Other options and single images work fine. When viewing published site - all images are nicely loaded, and no errors are shown.

#### Steps to reproduce
1. Starting at URL: https://jurassic.ninja/create/
2. Link your newly created site
3. Create new blog post and add multiple images (as Thumbnail Grid)
4. See JS errors and not loaded images

#### Screenshot / Video

![edit post proud plains wordpress com 2017-11-29 19-10-05](https://user-images.githubusercontent.com/5654161/33415921-6f8b815c-d5cc-11e7-8bab-d4a7cb615a5d.png)

#### Context / Source

#manual-testing on needs-testing call for new version of Jetpack

**Comment by jeherve** [comment]
This also happens in the "Media" view.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
