### ISSUE TITLE
Login: Visual feedback / tweaks & bugs

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#20364]
I have some visual feedback for the most recent login flow work.

1. For step one of the flow, the TOS jumps around after a minute or so and moves too close to the form field.

<img width="1216" alt="screen 1 tos - 1" src="https://user-images.githubusercontent.com/9257264/33442572-7432cee4-d5c3-11e7-9272-1b2778d571a6.png">

<img width="1213" alt="screen 1 tos-2" src="https://user-images.githubusercontent.com/9257264/33442577-7706ae24-d5c3-11e7-8fb5-f5cfbe323f45.png">

2. On screen two the password field is too close to the inactive email address field and the issue with the spacing for TOS also appears.

<img width="1332" alt="screen 2 - padding" src="https://user-images.githubusercontent.com/9257264/33442629-98cf5c9a-d5c3-11e7-9818-747c9466a691.png">

3. The "Email me a login link" is missing

<img width="1334" alt="new flow" src="https://user-images.githubusercontent.com/9257264/33442786-ff8e46e4-d5c3-11e7-8659-eada648f80c0.png">

<img width="1333" alt="existing flow" src="https://user-images.githubusercontent.com/9257264/33442792-021374c0-d5c4-11e7-929b-8b519f9acb7b.png">

4. Animations with the content sliding left and right will help with the user experience. It would be ideal to add this as part of the launch of this new flow. This gif isn't 100% accurate as the white module should stay in place but paired with the Google login animation it's hopefully sufficient to demonstrate the idea.

![passwordless-login](https://user-images.githubusercontent.com/9257264/33443025-883a1cfc-d5c4-11e7-9875-43cdc6bea964.gif)

![google login](https://user-images.githubusercontent.com/9257264/33443036-8d1082a2-d5c4-11e7-8008-2ecf122f5015.gif)

Let's chat more regarding this feedback!

@stephanethomas

**Comment by stephanethomas** [comment]
> 1. For step one of the flow, the TOS jumps around after a minute or so and moves too close to the form field.

I was only able to reproduce that weird jumping by doing the following:

1. Open the [`Devdocs` page](https://wpcalypso.wordpress.com/devdocs) in an incognito tab
2. Click the `Log In` link in the upper right corner

prioritizationIt's enough to investigate that issue, but do not hesitate to give us more information about how exactly you encountered it (this would also help for prioritization).

> 2. On screen two the password field is too close to the inactive email address field and the issue with the spacing for TOS also appears.

This is likely the same bug at play.

3. The "Email me a login link" is missing

This is because you were logged in when you accessed this page, and we only display that particular link when you are logged out.

4. Animations with the content sliding left and right will help with the user experience.

I agree, this would look much better. Do you have something working already that we could take inspiration from?

**Comment by stephanethomas** [comment]
> 1. For step one of the flow, the TOS jumps around after a minute or so and moves too close to the form field.

I've created https://github.com/Automattic/wp-calypso/issues/21158 to address the scenario I mentioned.

**Comment by stephanethomas** [comment]
> 1. For step one of the flow, the TOS jumps around after a minute or so and moves too close to the form field.

I think this weird jump only happens when coming from `DevDocs`. I've created https://github.com/Automattic/wp-calypso/issues/21159 to address that.

**Comment by stephanethomas** [comment]
> 4. Animations with the content sliding left and right will help with the user experience.

I'm going to close that GitHub issue, as this is low priority considering our current focus. However do not hesitate to create a new one to if that changes.
