### ISSUE TITLE
Simple Payments: Paying as Guest with Indian CC not working

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/wp-calypso#20372]
A user came to us in chat with a problem that they can't pay as a guest using their credit cards. They have explained that there is no provision to receive money in Indian rupee in Paypal, but all their credit cards can be charged in USD in India. 

When they try to pay as a guest with their credit card, the PP form opens up fine, they can enter all their billing info and then when they go to pay, the dialog box closes. No money is charged or received.

They’re claiming that it needs to ask for an “OTP” password verification step. I got the impression that credit cards in India have a password associated with them.

User tested in Chrome and IE, and the same trouble occurred.

Looked for other reports from WordPress.com users and couldn't find any. Also, with the dialog box closing unexpectedly, it might be part of PayPal's service and not ours. Thought I'd mention that as a possibility.

Chat: 1171371-hc (internal)
Follow up ticket: 822113-zen
#user-report

**Comment by MindyPostoff** [comment]
@designsimply - Is there a priority level we can give to this issue? I worry it will get lost without one.

**Comment by designsimply** [comment]
I'm sorry but there isn't! In this case, I would not consider it high priority in the current state because there has only been one user report of the problem here so far. If there are additional reports that come in, it would help to note them here.

**Comment by arunsathiya** [comment]
1467793-zen

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
