### ISSUE TITLE
Simple Payments: Total Payment buttons count has an inconsistent value

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#20411]
#### Steps to reproduce
1. Go to WordPress.com and add a Blog post.
2. In that post, create several payment buttons via **Add->Payment** button. (I've created around 20)
3. Save the post and navigate away.
4. Check the post count at the top when adding a new payment button. Initially, it will display a smaller value.
5. Access another post from the website and the count should go up to the real value.

#### What I expected
To see the right count(22) of payment button at the top.

#### What happened instead
It appears to be inconsistent. Its either 20, 21 or 22. (in total there are 22)

#### Browser / OS version
Chrome 62.0.3202.94
Windows 10

#### Screenshot / Video
822257-zen (attached it to the note)

![image](https://user-images.githubusercontent.com/6737345/33488410-2bc103be-d6b9-11e7-9ed4-ca2597bd793b.png)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
