### ISSUE TITLE
Domains: Make sure sign up flow brings in domain the user wants to register if they already tried searching

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#20436]
#### Steps to reproduce
1. Type in a random, unused *wordpress.com address
2. Land at the "XYZ domain does not exist. Do you want to register XYZ domain?"
3. Click on the option to register it
4. You will then go through the domain sign up flow but it will still lead you to the stop to pick a domain! I already picked it! At this point, it's really easy to put in the wrong domain or to forget which one you were testing.

#### What I expected
To have the domain I wanted to register to be pulled into the sign up flow since I clicked the option to register it. 

#### What happened instead
It made me re-type the domain/forgot I ever mentioned it. 

#### Screenshot / Video

Video of issue: https://cloudup.com/c1zgpNz6GlH

Apologies for the rough title of this issue :/ Had a hard time naming it.

**Comment by jsnmoon** [comment]
Hi @annezazu, it looks like this issue has been resolved:

<img width="1078" alt="wordpress_com" src="https://user-images.githubusercontent.com/4044428/40943088-34b961f6-680d-11e8-93be-f7693b39b92d.png">

<img width="1085" alt="wordpress_com" src="https://user-images.githubusercontent.com/4044428/40943102-413ca438-680d-11e8-8fe2-c48c209a913a.png">

Please reopen the issue if the bug is still reproducible, thank you! 🙇

**Comment by annezazu** [comment]
Nice!!
