### ISSUE TITLE
Activity Log: replace the ellipsis menu proposal

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#20453]
A question came up today during walk-throughs about removing the 'rewind to this day' button on the daily activity card. Since that event is fired at different times throughout the day it can create more confusion than clarity. 

Currently we show a rewind button per day, and then rewind actions somewhat hidden within the ellipsis menu per event. Like this:

![image](https://user-images.githubusercontent.com/437258/33531166-3e6bca36-d857-11e7-8fb4-51f87814afc7.png)

What if we were to emphasis the per-event rewind action (presumably the most common event) and add a dropdown menu to it that replaces the ellipsis. It would look like this:

![image](https://user-images.githubusercontent.com/437258/33531108-f7c2c40e-d856-11e7-8194-04231943b948.png)

Users would still be able to click the event card's chevron to see event actions or compact post cards etc. 

Looking for some feedback @MichaelArestad and others.

**Comment by roccotripaldi** [comment]
What would "Get Help" link to?

**Comment by rickybanister** [comment]
It would open happychat if operators were available.

**Comment by MichaelArestad** [comment]
@roccotripaldi You don't have to implement the Get help yet if it's not already implemented. That could be the next PR.

**Comment by eliorivero** [comment]
I'm working on this and create a split button to use to implement it. However, I'm wondering about the behavior when a rewind is in progress, because right now, in the ellipsis menu dropdown, we can disable the items separately.
We could also disable the main button with the **Rewind**, and leave the secondary button with the chevron enabled. Would that be ok?
Anyway, maybe this will be better answered once we see the live button.

**Comment by rickybanister** [comment]
Let's disable the entire thing, just like we did with the ellipsis. There is no need for someone to queue up a download while a rewind is taking place. Can you confirm that @MichaelArestad?

**Comment by rickybanister** [comment]
So to be clear, we would add a 'is-disabled' class and ensure both parts of the button become transparentized.

**Comment by MichaelArestad** [comment]
I can see folks wanting to do that, but they could also do it after the rewind. I suspect most folks would try the download before the rewind just in case.

**Comment by MichaelArestad** [comment]
In other words, let's disable the whole thing for now.

**Comment by rickybanister** [comment]
I saw an instance today of this button in a semi-disabled state. Rewind wasn't available so that part of the button was disabled, but the dropdown was accessible. It looked strange and confusing. @MichaelArestad can you look into an improvement of that circumstance? How can we allow someone to download a backup if we don't have a backup at that time to facilitate a rewind? Shouldn't the entire button be disabled including the dropdown? 

<img width="318" alt="screen shot 2018-01-04 at 11 19 48 am" src="https://user-images.githubusercontent.com/437258/34576773-0bdac1e4-f14d-11e7-8e8d-1ad2d4273d33.png">

**Comment by MichaelArestad** [comment]
@rickybanister They can't rewind because the site is in the process of rewinding. There is a backup associated with that item or the button/menu doesn't show at all.

Why not let them download it if they want? If we add a chat button (help button?) into the drop down they will still need access to it mid rewind. It's slightly goofy, but I think it makes sense.

**Comment by rickybanister** [comment]
I saw the above screenshot while simply browsing the AL, I was not actively rewinding.

**Comment by rickybanister** [comment]
@MichaelArestad this is implemented right? If it's done can you close?

**Comment by MichaelArestad** [comment]
It's implemented
