### ISSUE TITLE
Login: HTML visible in error message for suspended users.

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#20480]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/log-in
2. Type in a suspended user
3. Try to log in

#### What I expected
A normal error message.

#### What happened instead

I see an error message that has HTML code visible in it. 

#### Browser / OS version

Chrome 62.0.3202.94 on macOS 10.13.1

#### Screenshot / Video

<img width="444" alt="screen shot 2017-12-04 at 21 47 00" src="https://user-images.githubusercontent.com/184938/33572907-08a76b26-d93d-11e7-8e68-e1a441caf478.png">

#### Context

Tried to log in with a very old account while updating recovery codes. 

Possibly related to #246

#dogfooding #manual-testing

**Comment by bisko** [comment]
Haven't seen this happen in a while. Going to close it for now.

**Comment by KokkieH** [comment]
Reopening

I just had a report of this via Facebook DM, and am able to replicate it if I try logging in with a suspended username and the SSP. @bisko I'll DM you a username you can use to test this.

**Comment by bisko** [comment]
Confirmed that this is reproducible with the username that @KokkieH supplied.

**Comment by brbrr** [comment]
Just saw it with one of my test users

**Comment by mattgawarecki** [comment]
This appears to be driven by code in another repository. Automatticians can look at line 234 of `wp-login.php`, which takes action on the results of the `login_errors` filter.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
