### ISSUE TITLE
Editor and Preview: Editor back button loads blank screen

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#20484]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/view/sporadicthoughts.net (or, you know, for your site)
2. Click the write button in the masterbar
3. Once the editor loads, click the back arrow in the top-left
4. You'll wind up looking at a blank screen

#### What I expected
I expected to be back at the `/view/` screen.

#### What happened instead
A blank screen loaded

#### Browser / OS version
Latest Safari and latest OS X

#### Screenshot / Video
![screen shot 2017-12-04 at 5 05 36 pm](https://user-images.githubusercontent.com/191598/33578682-60248636-d915-11e7-8514-1f7c7f85dc32.png)

**Comment by jblz** [comment]
@frontdevde can you please take a look?

**Comment by frontdevde** [comment]
@jblz on it 👀

**Comment by frontdevde** [comment]
The issue is reproducible in other browsers as well, e.g. in Chrome. 

It is caused by an error being thrown in `TinyMCEDropZone`. On `componentWillUnmount` there are three `editor.dom.unbind(editor.getWin(), 'event', this.replaceEvent )` calls that try to unbind attached events. This fails as `editor.dom.win`, which the functions are trying to get via `editor.getWin()`, is `null` at the point the functions are being called.

**Comment by frontdevde** [comment]
The `componentWillUnmount` function in `TinyMCEDropZone` gets called after the editor has already been removed via the `destroyEditor()` (see `tinymce/index.js`). At that point, there is probably no need anymore to unbind any events. 

Not sure if there are other `TinyMCEDropZone` use cases where the editor doesn't get destroyed or gets removed after `TinyMCEDropZone`. Therefore going to fix this issue by wrapping the unbind functions in a check for `editor.dom.win` being present.
