### ISSUE TITLE
Store: Clicking Add Product after editing product description causes crash

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#20490]
When working in the products page, if you edit the product description, click Update, or disregard edits - the subsequently click "Add Product" errors are thrown in the console and the app crashes.

![error-add-product](https://user-images.githubusercontent.com/22080/33584885-5cd6a224-d916-11e7-9378-64e684f33f8c.gif)

The error only occurs when you interact with the TinyMCE instance on the products page. Updating other data in my testing does not trigger the issue.

Errors in console:
![product-errors](https://user-images.githubusercontent.com/22080/33584959-c683c8f0-d916-11e7-9ff6-d17bf856fe0c.png)

Via kibana it appears a few users have been hitting this problem in production. In kibana they are appearing as:

```
Minified React error #40; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=40 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
--
```

**Comment by allendav** [comment]
Sorry @timmyc - I still consistently get the "crash" when i follow the steps you gave above on this branch:

I edited just the product name, saved the change, hit the add button and then...

<img width="1366" alt="screen shot 2017-12-07 at 11 34 53 am" src="https://user-images.githubusercontent.com/1595739/33734953-b8fd11c2-db42-11e7-8edd-d03d3f49b4c1.png">

**Comment by timmyc** [comment]
Well glad you can re-create the issue at least - I will give it another try and attempt to fix again.

**Comment by designsimply** [comment]
Tested and confirmed using the following testing steps:

1. Start with a WordPress.com site setup with a store.
1. Go to My Sites > Store > Products
1. Click on any product.
1. Make a change to the description.
1. Click the "Add" button next to Products in the left sidebar.

<strong>Result:</strong> a completely blank page loads for me and I see the following errors in the console:

<blockquote>Invariant Violation: Minified React error #40; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=40 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

vendor.a88b87716aede192c3e7.min.js:37:54287


Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
build.d60dcaceaae1aa12c11f.min.js:68:1492

Error: Minified React error #40; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=40 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vendor.a88b87716aede192c3e7.min.js:37:20417</blockquote>

<img width="1280" alt="screen shot 2018-01-03 at wed jan 3 11 55 57 am" src="https://user-images.githubusercontent.com/1119271/34535640-c5b56818-f07f-11e7-928e-461abfbcd015.png">
<sup>Seen at https://wordpress.com/store/product/madefortesting347.blog/70 using Firefox 57.0.3 on macOS 10.13.2.</sup>
