### ISSUE TITLE
Store: Update Logic for Store Sidebar Link in Calypso

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#20607]
To prepare for non US/CA users of WooCommerce on AT sites, we need to update the logic that is used to display the "Store" link in the sidebar, and determine what the link target is. So there will be five different states for the sidebar store link:

__Atomic Site, Supported Country, WooCommerce Installed__
If the site is on AT, has `woocommerce` installed and activated, and is in a supported country ( currently US / CA ), the Store link will be shown, and the target will be `https://wordpress.com/store/DOMAIN`

__Atomic Site, Supported Country, WooCommerce not Installed__
The Store link should be shown in this instance, and will target the existing new store flow.

__Atomic Site, Non-Supported Country, WooCommerce Installed__
For AT sites that have `woocommerce` installed and activated, but are not in a currently supported country, show the Store link with the external gridicon, and link to the WC dashboard page `/wp-admin/edit.php?post_type=shop_order`

![external-link](https://user-images.githubusercontent.com/22080/33734527-84cfe9de-db41-11e7-892e-e6e7543a7746.png)

__Atomic Site, Non-Supported Country, WooCommerce not Installed__
For now I think the link should not be shown in this scenario. Once the Store Nux supports non-supported countries, we could expose the Store link and send these users through the standard setup flow, which will ultimately send them to the Woo setup wizard.

__All Other Sites__
In all other instances the Store link should not be shown. Eventually we could consider exposing the Store link to Pro plan users to attempt an up-sell, but for now let's just keep it hidden.

**Comment by allendav** [comment]
Let's land #21297 first and then I think this simplifies greatly:

Atomic Site:
https://wordpress.com/store/DOMAIN

except...

Atomic Site, WooCommerce Installed, Store Country not (yet) supported in Calypso:
/wp-admin/edit.php?post_type=shop_order (external link)

Right?

**Comment by allendav** [comment]
@timmyc @kellychoffman @jameskoster There is a wrinkle - if we do that ^^ then client/my-sites/sidebar/sidebar.jsx is going to need to be aware of woocommerce selectors (i.e. for location) and we were trying to avoid having “core” calypso aware of extension stuff as much as possible…

I suggest if we should just always have it point to store/{DOMAIN} instead and then on the app/dashboard code have *it* detect a nonUS nonCA store, and redirect from there

We could even (instead of an immediate redirect) show a nice message in app/dashboard to the effect that store management is available at {link} and leave it to them to click on that link - it could give us a nice place to tell them when calypso store management is ready for their location

**Comment by jameskoster** [comment]
I think that's fair. The message could probably be more literal though and say that store management can only be done in wp-admin. Something like;

> For now you can manage your store in wp-admin. We'll let you know when you can manage your store here.

> [Manage my store ->]

**Comment by allendav** [comment]
> For now you can manage your store in wp-admin.

Is wp-admin a meaningful term to our target audience though? I'd almost rather say "our legacy dashboard" instead honestly.

**Comment by kellychoffman** [comment]
I see two scenarios here that need different copy and UX: (borrowing from what Jay wrote)

1. I am going through the setup flow for the first time. Copy:

**Let's set up your store**

Howdy! It looks like your store is located in a country that we can not fully support in this interface. Instead, store setup and management will take place in wp-admin, our classic admin interface. We are actively working on adding broader support and we'll let you know when you can manage your store here!

[Set up my Store [external link icon] ]

2. I have already set up my store in wp-admin and click on Store tab.

A splash page here feels unnecessary and redundant, as Timmy mentioned. Since the user already went through the initial setup and saw the splash page previously, we shouldn't keep showing it to them.
