### ISSUE TITLE
Comments: Threaded view shows the "in reply to" label

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#20709]
The _In reply to_ label should be showed in the correct context on the threaded view.

#### Steps to reproduce
1. Start Calypso with `ENABLE_FEATURES=comments/management/threaded-view npm start`
2. Navigate to a comment post view.

#### What I expected
To have a threaded view of comments, without the _in reply to_ label.

#### What happened instead
The child messages show the _in reply to_ label, that should only show when we hit the depth limit.

#### Screenshot / Video
![screen shot 2017-12-11 at 15 52 41](https://user-images.githubusercontent.com/233601/33848322-1ce7e436-de8c-11e7-9285-60a29ad01abb.png)

#### Context / Source
From https://github.com/Automattic/wp-calypso/pull/20077#pullrequestreview-78826192

**Comment by gwwar** [comment]
Removing from the milestone since this is under a feature flag

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
