### ISSUE TITLE
Comments: Threaded View bulk edit and sorting

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#20708]
Bulk edit and sorting works only for the top level comments. What make sense for the child comments?

#### Steps to reproduce
1. Start Calypso with `ENABLE_FEATURES=comments/management/threaded-view npm start`
2. Navigate to a comment post view.
3. click on _Bulk Actions_

#### What I expected
To see a list of comments, without threading so each comment can be selected for the bulk action.

#### What happened instead
The list showed the child comments with action buttons inside a selectable comment.

#### Screenshot / Video
![screen shot 2017-12-11 at 15 48 02](https://user-images.githubusercontent.com/233601/33847885-c8675d2a-de8a-11e7-83c1-98216930852e.png)

#### Context / Source
From https://github.com/Automattic/wp-calypso/pull/20077#pullrequestreview-78826192

**Comment by gwwar** [comment]
Removing from the milestone since this is under a feature flag

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
