### ISSUE TITLE
Store: Dashboard: Empty dashboard if set_store_address_during_initial_setup false and other flags true

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#20784]
Use the console to set all the flags (POST /sites/$site/calypso-preferences/woocommerce) to true except for set_store_address_during_initial_setup, which should be set to false

Navigate to https://wordpress.com/store/{DOMAIN}

Behold the vasty nothingness.

<img width="1299" alt="vasty-nothingness" src="https://user-images.githubusercontent.com/1595739/33951934-2b9fe10e-dfe5-11e7-9cfa-214bd8a6f16d.png">

Not sure how a site could get to this state outside of using the console to reset sites (i.e. set them all to false while there is still an address on the site), but we should fix this.  The fix might include both setting the flag when an address is detected on the site AND/OR fixing the rendering code to display something :P 

Observed on today's master

**Comment by designsimply** [comment]
<blockquote>Use the console to set all the flags (POST /sites/$site/calypso-preferences/woocommerce) to true except for set_store_address_during_initial_setup, which should be set to false</blockquote>

May I please ask for a bit more detail in how to set all the flags to true using the console?

Aside: I noticed that going directly to https://wordpress.com/store and that page is even more blank (but with no console errors). Not sure if that link is expected to work or not though! Should it show the site picker? [[screenshot](https://user-images.githubusercontent.com/1119271/33971612-74a37bb2-e036-11e7-9dfe-532a5285b9e8.png)]

**Comment by timmyc** [comment]
@designsimply I don't believe `/store` was ever intended to be a true route/page, but I suppose it couldn't hurt to render a site picker if someone happens upon the page. If you'd like to open an issue around that - feel free to do so, but feeling like it would be a lower priority looking ahead at Q1.

> May I please ask for a bit more detail in how to set all the flags to true using the console?

The Store setup dashboard uses a series of flags which are persisted via the API to determine which steps have been completed in the setup process. To view or manually manipulate those settings you can use the [REST API Dev Console](https://developer.wordpress.com/docs/api/console/) and interact with the `/sites/YOURSITESLUG/calypso-preferences/woocommerce` endpoint. `GET` request will return the current values, or you can `POST` to update them. We are hoping to potentially add a tool for a12s to use in either staging or wpcalypso to make this debug process a bit easier to use.

@allendav I'd agree that getting to this state would be difficult to do, but yes we should likely handle it properly. Perhaps we can look into this while working on the non US/CA signup since we will be in the dashboard logic quite a bit then.

**Comment by allendav** [comment]
I'm fixing this now
