### ISSUE TITLE
Notifications: Filter for unreplied comments

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#2082]
Site owners can build stronger communities by responding to all (or most) comments, but as their site grows it becomes increasingly easier to lose track of which comments still need replies.

Right now, I can't tell from any comments list (in notifications or on the comments management page) what has been replied to.  But if I click on a comment from Notifications, I can see "You replied to this comment." So I know we're tracking that somewhere. That looks like this:
<img width="378" alt="Screen Shot 2021-10-28 at 7 10 54 PM" src="https://user-images.githubusercontent.com/3476361/139356916-5da42650-03bb-4838-955c-4fdb33cca836.png">

It would be helpful to be able to find all guest comments that have not had a reply. Right now the notification panel has some filters at the top, like this. It has a gear icon, too, which as far as I can tell, just closes out the notifications panel. Could we maybe allow people to select Unreplied comments there?

<img width="397" alt="Screen Shot 2021-10-28 at 7 12 59 PM" src="https://user-images.githubusercontent.com/3476361/139357055-ca646df2-a049-4ab9-bdd9-d918e9bf7b1a.png">

Or, it may make more sense to put this feature on the Comments page instead. Currently there is no info on that page about what has been replied to already. Could we add a filter here, perhaps, or a similar one in the Calypso comments page?

<img width="683" alt="Screen Shot 2021-10-28 at 7 06 29 PM" src="https://user-images.githubusercontent.com/3476361/139356839-9486b81f-f983-4d1d-b81e-f458fd04d2b1.png">

I'd love to hear any thoughts folks have on this. It's not a terribly common request, but for site owners who really want to engage with their audience, it would be a useful one.

**Comment by KokkieH** [comment]
We've had another request for this [here](https://en.forums.wordpress.com/topic/unreplied-comments/)

**Comment by supernovia** [comment]
No need to stale this. It's still a useful feature request even if no one can get to it.

**Comment by supernovia** [comment]
It's still a useful feature request even if no one can get to it. Un-staling!

**Comment by supernovia** [comment]
Let's not make this stale. It'd be a nice feature.

**Comment by supernovia** [comment]
Still hoping for this feature, either in the dashboard or in a filter for notifications. People sometimes want to find the things they haven't responded to.

**Comment by Aurorum** [comment]
Mmm - I was quite confident about this, but I've hit a brick wall. I tried adding this as a setting to the Comments page (since the Notifications API isn't open-source). 

To some extent, it works fine because we already store whether the user has replied to the individual comment. As such, we can just filter out the comments which has already replied to. 

The problem is that this breaks pagination - for example, if the user has opted to display twenty comments, and then they only display unreplied comments, this approach means that the unreplied comments would be hidden. Ideally, they would be replaced with new comments so that it always remains at twenty. 

I'd need some help updating the API endpoint for that to work properly, since I don't think it's open-source :( I doubt this will get looked at anytime soon, but hope that helps someone who tries attempting this issue in future!

**Comment by Aurorum** [comment]
Although, thinking about this more, one solution might be to allow collapsing replied comments - that would be much easier to implement (see screenshot). 

@supernovia do you think might be helpful for bloggers' flows?

<img width="1133" alt="Screenshot 2024-01-23 at 11 38 50" src="https://github.com/Automattic/wp-calypso/assets/43215253/aa64dba2-6e0f-4c78-9c56-c8c000e48888">

Would it be possible to ping some Design folks to check out that concept? 😁
