### ISSUE TITLE
Is this QueryComment instance still needed?

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#20885]
Leaving a question maybe for @Copons : is [this instance of QueryComment](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment/comment-content.jsx#L74) still needed, now with us moving away from comments-tree? It seems to add additional endpoint calls when loading `/comments` (this can be seen in #20737 ).

**Comment by Copons** [comment]
This is unfortunately still needed.

Reply comments have a "In reply to: { comment excerpt }" line, that is populated by the actual content of the parent comment.
If that's not loaded in state (e.g. because it's neither part of the current page of 20 comments, nor of the previously navigated pages), the "in reply to" line couldn't be populated and therefore we couldn't show to the user any useful information about the comment's parent comment.

I'm afraid the only solution would be to add the parent comment content (of an excerpt of it?) into the comment object returned by the list endpoint.
Though, this means adding a possibly sizeable load to the endpoint, for a non strictly necessary field.

I'm closing this issue right now, but feel free to reopen it if you have a better solution! 🙂
