### ISSUE TITLE
Editor: Hitting ctrl+z with a code block adds &amp; instead of undoing...

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#20888]
#### Steps to reproduce
1. Create a post
2. Use [code][/code] blocks
3. Start hitting ctrl+z

#### What I expected
Things to undo

#### What happened instead
&amp; added to text

#### Browser / OS version
Chrome / Windows 10

#### Screenshot / Video
![capture](https://user-images.githubusercontent.com/1883296/34066518-cecb8780-e1dd-11e7-8fbe-6af83a477aa8.PNG)

#### Context / Source
#reallife

**Comment by alisterscott** [comment]
Hi @withinboredom 

What version of Chrome are you using?

I tried latest (Version 63.0.3239.108 (Official Build) (64-bit)) on both Windows 10 and Windows 7 and I can't reproduce - nor can I reproduce on Chrome 63 on macOS.

![undo](https://user-images.githubusercontent.com/128826/34231670-a901fe22-e628-11e7-94c5-b5b509450631.gif)

Since Gutenberg is arriving soon which will replace the code editor I am changing this to a low priority as it's unlikely it will get fixed if it affects a small subset of users.

Thanks

**Comment by withinboredom** [comment]
Huh, I confirm it seems to have fixed itself...
