### ISSUE TITLE
Login: Fix user not redirected to initial page when logged out

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#20941]
We should fix the following issue - initially reported by @seear [here](https://github.com/Automattic/wp-calypso/pull/20498#issuecomment-352492739):

1. Open https://wordpress.com/jetpack/connect/plans/nasty-new-301.jurassic.ninja in an incognito tab
2. Assert that you are redirected to the [`Login` page](https://wordpress.com/log-in?redirect_to=%2Fjetpack%2Fconnect%2Fplans%2Fnasty-new-301.jurassic.ninja)
3. Enter credentials and submit the form
4. Notice that you are redirected to the [`Reader` page](https://wordpress.com) instead of the [`Jetpack Plans` page](https://wordpress.com/jetpack/connect/store)

![login_redirect](https://user-images.githubusercontent.com/7767559/34127433-0d8991e8-e435-11e7-90ba-df719a175902.gif)

**Comment by stephanethomas** [comment]
To be crystal clear, this only happens when users are logged out and try to access a page that requires them to be logged in. In that case they are redirected to the `Login` page, with the url of the previous page added to the `redirect_to` parameter.

**Comment by stephanethomas** [comment]
This issue happens because we're now relying on the initial query string, and not the current one:

<img width="394" alt="screenshot" src="https://user-images.githubusercontent.com/594356/34149051-0efda6a8-e4a4-11e7-8b1c-3d86e94b0804.png">

**Comment by seear** [comment]
Investigating a ~4% drop in successful Jetpack site connections since Monday, it is possible that this issue is the cause. It breaks an important flow, where users connect from wp-admin and need to login when arriving at Calypso. Instead of the site being connected, they get redirected to the reader:

![broken_connect_redirect](https://user-images.githubusercontent.com/7767559/34262259-c651f884-e663-11e7-810d-3d4cee62f7e7.gif)

**Comment by johnHackworth** [comment]
If this issue is the cause, a rollback while we investigate / fix it may be good, 4% is quite a big drop
