### ISSUE TITLE
Posts: Condensed posts list zero search results message not correct

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#21025]
It looks like the condensed post view search zero results message has regressed

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/my/mytestsite.com?s=dskfjidjf+d%2Cmfhjkjdshfj

#### What I expected

Relevant error message, similar to previously:

<img width="770" alt="screen shot 2017-12-21 at 2 47 31 pm" src="https://user-images.githubusercontent.com/128826/34240999-f3395b04-e65d-11e7-9fe6-64a94dcea108.png">

#### What happened instead

> You haven't created any content yet.

<img width="791" alt="screen shot 2017-12-21 at 2 48 18 pm" src="https://user-images.githubusercontent.com/128826/34241018-2b13d98c-e65e-11e7-907f-5f7aa46925ea.png">

#### Browser / OS version

Chrome macOS

**Comment by lancewillett** [comment]
Thanks for the report, CC @Automattic/tanooki

**Comment by mattsherman** [comment]
The message differs depending on whether in single site or All My Sites mode...

All My Sites mode:

![fireshot capture 16 - blog posts wordpress com - https___wordpress com_posts_my_s fewgwg](https://user-images.githubusercontent.com/2098816/34688713-05c97bce-f481-11e7-8e9c-e7aa071f0dce.png)

Single site mode:

![fireshot capture 15 - blog posts simple meeps premium _ - https___wordpress com_posts_my_tes](https://user-images.githubusercontent.com/2098816/34688714-05df2866-f481-11e7-8880-b9b60e174da4.png)

The single site mode message is not incorrect. But, it is less clear than the previous message, since it no longer references a search or the query.

It would be good to change this message to be more informative.
