### ISSUE TITLE
Activity Log/Rewind: Warn users not add credentials for root

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/wp-calypso#21026]
When users add remote access details for the root user it causes issues when they run a restore because all the files in /wp-content are restored as root while core WordPress files are owned by a different user. After the restore the user is unable to install or remove any plugins in wp-admin. 

Can we please warn users about this if we detect them adding the root user to their remote access credentials? If they go ahead and save root anyway, can we also warn the a second time just before they run the restore?

**Comment by dmsnell** [comment]
Seems like it would be good to replace the files with the same ownership as when we backed them up unless the user has disappeared. This would seem like a much better behavior anyway especially since we can have multiple sets of credentials.

**Comment by rcoll** [comment]
@dmsnell I talked with @briancolinger and that's not easily doable since we don't store the UID of the file creator. We both agree that it seems sensible to simply reject all root creds, since there is inherit danger in using them anyways.

@michaelarestad what are your thoughts here on what a warning might look like?

**Comment by MichaelArestad** [comment]
@rcoll Probably a global notice saying something like this:

> We can't accept credentials for the root user. Please acquire or create credentials for another user with access to your server. Learn more

We'll need copy review in the PR for sure. It's a tough one.

**Comment by briancolinger** [comment]
I'd go with rejecting the "root" username.

Currently, VaultPress has 7 sites with root credentials.
Historically, VaultPress has never prevented you from giving us root credentials. 
The reason for that is because we never wrote the code if ( 'root' == $user_name ) { return WP_Error( 'no_root_users_please', 'No root users please.' ); } or something similar. :)

Having said that, if I could go back and do it correctly the first time, I would out right reject root credentials. It's just too risky.

To give an example of how badly this could go wrong... 
The restore system only deletes things like helper-scripts and .sql dumps that we uploaded.
When restoring things like plugins or themes, we overwrite existing files instead of deleting the plugin or theme directory first.

In the future, the restore system may need to delete plugins and themes before restoring them from the backup.

I know that we all write very good quality code, but mistakes still happen from time to time.
A while back, I was testing some code that would do a recursive delete. I had a bug in the code that ended up deleting every single file in my server's home directory. The only reason it stopped there was that my server was properly configured and wouldn't let my SSH user delete files from the / directory.
If I had been using root credentials when that happened I could have wiped most of the files on my server.

Rejecting the root user name doesn't prevent this sort of thing from happening if the SSH user we have has root-level privileges or because of other things we haven't thought of yet. 
But, it's a start.
