### ISSUE TITLE
Bug: Faulty WordPress.com Customizer redirection for WordPress.org sites

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#21032]
**Steps to reproduce**:

Assume you are opening the WordPress.com Customizer directly, instead of opening the WordPress.com Customizer from the WordPress.com dashboard.

1. Visit https://wordpress.com/customize
2. Choose your self-hosted WordPress (WordPress.org) site from the list of sites shown.
3. The Customizer module shows up.
4. Click on the "X" button at the top left to close the Customizer.

**Expectation**: User is redirected to https://wordpress.com/customize

**Result**: User is redirected to https://wordpress.com/customize/example.com, which again loads the WordPress.com Customizer for that self-hosted WordPress (WordPress.org) site automatically.

_For WordPress.com sites, when you close the WordPress.com Customizer by clicking the "X" button, the user is redirected to https://wordpress.com/customize, which is assumed to be the right process._

**Comment by kwight** [comment]
I don't really like the behaviour of going back to `/customize`; since we would have a site context once the selection is made, I'd think we should be going back to `/stats/:site`, the same `return` value for users clicking "Customize" in the sidebar. (Well, not really; the `return` value for Customize in the sidebar is actually the same page from which Customize was clicked, which makes sense, but hovering over the Close button in the Customizer iframe will always display a `/stats` URL – not sure what's going on there.)

I think what we need is [some additional handling in](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/customize/main.jsx#L173) `buildCustomizerQuery` for `query.return`, ensuring that regardless of Jetpack vs dotcom or not, coming from `/customize` results in a `return` of `/stats/:site`.

I'm getting slightly different behaviour on local dev also. On production, selecting a dotcom site then clicking Close brings you back to `/customize` (as the OP mentions), and without any console errors. On local dev, however, doing the same will result in a failed prop warning:

![screen shot 2018-03-08 at 3 33 57 pm](https://user-images.githubusercontent.com/349751/37182446-33f357ac-22e6-11e8-92af-1a0915ea9821.png)

So maybe this is "working" by mistake? Not sure what's going on here yet either.

**Comment by lancewillett** [comment]
Closing as this is the Calypso repo and not the right place to report Customizer bugs (see `customization` repo in GitHub).
