### ISSUE TITLE
Editor: Welcome Tour partially obscures account confirmation modal

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#21122]
#### Steps to reproduce
1. Starting at URL: `/start`
2. Create a free account
3. Do _not_ confirm your email
4. Browse to the Editor
5. See the notice that publishing is blocked w/o a confirmed acct
6. Click to `Learn More`

#### What I expected

Tours to be shown behind almost all modals

#### What happened instead

The tour was show in front of the modal

#### Browser / OS version

Chrome Stable / Mac High Sierra

#### Screenshot / Video

<img width="723" alt="screen shot 2017-12-27 at 5 27 47 pm" src="https://user-images.githubusercontent.com/1587282/34395191-7149c4ac-eb2c-11e7-89cc-a84b1cf05d0c.png">

**Comment by lsinger** [comment]
I don't think it is a quick fix. We want to be above certain modals because we want to explain how they work (image editing comes to mind). But there seems to be a class of modals that isn't ... a tool we'd ever want to explain with a tour? Maybe we need to take a conceptual look at the file with the z-index definitions. 

But! One quick fix could be to give this modal specifically a higher z-index. AFK currently though with no access to a non-phone device.

**Comment by lsinger** [comment]
I looked into this in more detail now. 

I tried assigning a higher `z-index` to just this particular modal — however, its parent (the generic `ReactModal__Overlay` / dialog backdrop creates a stacking context so [changing this modal's `z-index` won't change a thing](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/) regarding its stacking order relative to Guided Tours, which creates its own stacking context (with a higher `z-index`). 😕

I still think a higher `z-index` for Guided Tours makes sense as there are modals we explain using a tour / we might want to explain using a tour in the future. 

One possible solution could be to pass through something like a `.block-guided-tours` to dialogs / modals that need it. That could then assign a higher `z-index` to the `ReactModal__Overlay` parent. 

Thoughts?
