### ISSUE TITLE
Drop Olark from Calypso

### ISSUE THREAD

**Issue by nosolosw** [Automattic/wp-calypso#21153]
I've noticed that in the HelpContact form (`client/me/help/help-contact/index.jsx` we've got tons of code related to Olark support.

I thought we were no longer using Olark, are we? cc @mattwondra 

These are some other issues that will potentially benefit from removing Olark traces from our codebase:

- https://github.com/Automattic/wp-calypso/issues/19829
- https://github.com/Automattic/wp-calypso/issues/18926
- https://github.com/Automattic/wp-calypso/issues/18556
- https://github.com/Automattic/wp-calypso/issues/14745

**Comment by mattwondra** [comment]
That's right — WordPress.com is no longer using Olark (Woo support teams are but that's outside Calypso). So any Olark-specific code should be good to tear out.

It's worth noting that there may still be actions/API calls/etc that are named "Olark" but are still actually affecting Happychat or other support features (because renaming hasn't happened yet either). So some care still needs to be taken that anything torn out is definitely dead code.

**Comment by jsnajdr** [comment]
I started to remove Olark from Calypso in a WIP PR #21488

The only bit of functionality still used is the `isUserEligible` flag returned by the `/help/olark/mine` REST endpoint. Everything else is dead code. See the PR description for more info.
