### ISSUE TITLE
Media: Search Icon Overlaps DropDown Menu in Small Screen Size

### ISSUE THREAD

**Issue by FlyteWizard** [Automattic/wp-calypso#21231]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/sitename.wordpress.com
2. View in small screen size. (485px)

#### What I expected

The layout to not overlap at certain screen size.

#### What happened instead

The layout for the search icon and the dropdown menu overlapped. 

#### Browser / OS version

Chrome (Latest) / macOS

#### Screenshot / Video

<img width="594" alt="capture d ecran 2018-01-02 a 22 11 26" src="https://user-images.githubusercontent.com/10472448/34510707-342e6e68-f00b-11e7-9a7f-3e840bff75ae.png">

<img width="397" alt="capture d ecran 2018-01-02 a 22 16 37" src="https://user-images.githubusercontent.com/10472448/34510709-368f4f74-f00b-11e7-85d5-eeb1acbfac8b.png">

#### Context / Source

We'd also love to know how you found the bug: #testingAPossibleSolutionForIssue#16921

**Comment by Vanluren** [comment]
Hey, I could take a look at this.

**Comment by andfinally** [comment]
@FlyteWizard are you still seeing this issue? I can't reproduce it.

![weird-zone](https://user-images.githubusercontent.com/1647564/36597768-1b337146-18a2-11e8-94cc-c924a81b3a9d.png)

The CSS hides the `.plan-storage` div that contains the bar on viewports smaller than 961px, and the style's been around for at least a year, since https://github.com/Automattic/wp-calypso/commit/97954ae56622d1cdcab97c719f66068d3f4c66b8. So it's strange that you're seeing it!

**Comment by FlyteWizard** [comment]
@andfinally 

Yeah, I am still experiencing this overlap. 

<img width="470" alt="capture d ecran 2018-02-23 a 08 13 04" src="https://user-images.githubusercontent.com/10472448/36604084-95f0fd1c-1871-11e8-8985-adc862e13aa9.png">
<img width="474" alt="capture d ecran 2018-02-23 a 08 13 31" src="https://user-images.githubusercontent.com/10472448/36604085-96068416-1871-11e8-8060-fe10555e93c6.png">

**Comment by andfinally** [comment]
Oh thanks, now I get why we were seeing different things. It looks like the bar's hidden on `wordpress.com`, but displayed in my local Calypso environment. Then you're squishing your browser to 485 wide to get the small layout, and your macOS is set to show scrollbars, which is reducing the available width. I have scrollbars mostly hidden, and I was viewing the page in the "Responsive" mode of devtools, and in that view the plan storage bar fits OK. I'll have another look at this.

**Comment by andfinally** [comment]
This issue happens in viewports between 480px and 490px wide when scrollbars reduce the available area. On macOS Chrome, the scrollbar uses up 15px of page width, but on the kind of touch devices these layouts are mostly aimed at, scrollbars are overlaid on the page, so the problem won't appear.

I can see two possible solutions, and both have drawbacks. One is to hide the `.plan-storage` bar above the 480px breakpoint. But in that case it would only ever appear on viewports over 960px.

Another would be to limit the dropdown list container to a max width of 150px. The change would have to be specific to this page, though, because it would break the dropdown list on a page like `/posts/my/x.wordpress.com`. And it might mean list items in some languages are truncated.

It'd be interesting to hear what other people think, considering the issue seems quite specific and both solutions have a downside.

**Comment by millerf** [comment]
Hi @andfinally @FlyteWizard,

I just started to contribute to calypso (very first post).

What about simply reducing the padding on the `.plan-storage` for breakpoints in between 480px and 660px on this specific page?

I added a fix here:
https://github.com/millerf/wp-calypso/commit/6718972f6996b8dd8a3e60a3e93438ec87b653e7

`.media-library__filter-bar` seemed to be a good selector for this specific page, but as I am new on this project, I am waiting for your feedback to start a PR

**Comment by andfinally** [comment]
Hi @millerf, welcome! 👋  I'm pretty new round here myself! I think a solution like that could work, and it would avoid the problems I mentioned. I can think of a few points though. 

It looks like your breakpoint arguments result in some CSS you probably don't want:

```
@media (min-width: 481px) {
	.media-library__filter-bar .plan-storage {
		padding-left: 22px;
		padding-right: 22px;
	}
}

@media (max-width: 660px) {
	.media-library__filter-bar .plan-storage {
		padding-left: 22px;
		padding-right: 22px;
	}
}
```
That's going to apply the padding on all viewports over 481px. I've not found any examples of a breakpoint range anywhere in the code - a simple single breakpoint argument is probably the preferred style. Fortunately you can do that in this case, because the plan bar is hidden below 480.

`.media-library__filter-bar` does look like the right selector for this situation. I'd also suggest making the padding 20px - it fixes the overlap when the viewport's between 480 and 485. I'm not exactly sure what increments are preferred for padding - someone else may recommend 18px instead of 20px. When you remove the stray blank line and use the padding shorthand you get:

```
@include breakpoint("<660px") {
	padding: 0 20px;
}
```
I'm also just earning my stripes, but I'd say go ahead and create a PR and let's see what people think. Good luck! 😃

**Comment by millerf** [comment]
Hi @andfinally , thanks for the welcome!

Yes, 20px is what it should be. Not sure why I settled with 22px. I thought I tested it...

About the breakpoints, I agree that the `">480px"` is useless when coupled with the  '"<660px"', as the .plan-storage is hidden on smaller screens. But I usually like to be very specific in bug corrections, in order to prevent headaches for eventual future modifications on the same module.

Same idea goes with the shorthand notation: using your version force the padding-top and padding-bottom to `0`, but we just want to change the padding left and right.

As you can see [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/style.scss#L83), they seem to use this kind of notation.

I am not entirealy sure which philosophy they usually use though, so I'll PR my version and see what they say :)

But thanks for the help anyway!

**Comment by andfinally** [comment]
No worries @millerf 🙂. Hm, you may have a point there - it should be fine to follow the style of that example. My issue with the breakpoints was that instead of a single media query with a range, the `>480px` creates a second media query that remains in force when your viewport is above 660px. Let's see what people think.

**Comment by millerf** [comment]
@andfinally oh, I see. I didn't notice it.

That is definitively a problem. I am on it.

**Comment by millerf** [comment]
Well spotted ;) 
It is fixed.

**Comment by andfinally** [comment]
👍 Nice, thanks!

**Comment by alisterscott** [comment]
Confirming this is no longer an issue:

<img width="486" alt="screen shot 2018-07-24 at 12 30 19 pm" src="https://user-images.githubusercontent.com/128826/43113355-671158b4-8f3d-11e8-86a0-cb2e568e6f7b.png">
