### ISSUE TITLE
Comments: Inconsistent tag-stripping

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#21246]
#### Steps to reproduce
1. Start by commenting on a test site using some HTML tags.  Use some that are traditionally [allowed](https://developer.wordpress.org/reference/functions/allowed_tags/) and some that are not.  For example:

```
<h1>A header</h1>
Some <strong>strong</strong> text
<div>A div with a <a href="#" rel="nofollow">link</a></div>

```

2. Note that, at least in Twenty Seventeen, the HTML is posted in the front end of the comment as well as the back end.

3. Go to https://wordpress.com/comments/ and try editing that comment to add another word or something.  Save the changes, and watch what happens to the tag.

#### What I expected
- I expected the disallowed tags might be removed, but they were not removed in Chrome on Mac.

- The user expected the tags would stay, but they were stripped in Chrome on Windows 10.

#### What happened instead
In Chrome (latest) on Mac, the tags are not stripped on edit.

On Windows 10 (in Firefox and in Chrome), and in Firefox on Mac, the heading and div tags _are_ stripped.

The tags are not stripped when editing the comment in wp-admin, regardless of browser.

#### Browser / OS version
(see above)

#### Screenshot / Video
https://cloudup.com/cuTat86FJiO

#### Context / Source
[User complaint in forum
](https://en.forums.wordpress.com/topic/disgusting-wordpress-new-comment-edition-mode?replies=12)

**Comment by gwwar** [comment]
Might also be a chance to use the DomParser in the editor as noted in https://github.com/Automattic/wp-calypso/pull/22331#discussion_r168575005

**Comment by synora** [comment]
I've had a user report this in chat today. The HTML markdown for their comments in Calypso aren't saving, but it works as expected within wp-admin. 

User also recorded this event: https://www.youtube.com/watch?v=MeaDUhHBSSQ&feature=youtu.be

Chat: https://mc.a8c.com/support-stats/happychat/transcript.php?id=70563
Follow Up Ticket: https://woothemes.zendesk.com/agent/tickets/1910665

**Comment by gwwar** [comment]
@synora do you mind opening a separate enhancement issue for markdown support?

**Comment by synora** [comment]
@gwwar Done!
https://github.com/Automattic/wp-calypso/issues/31779

**Comment by Lazza** [comment]
@gwwar  it's a good idea to have a separate bug report. However, the issue I have reported has the same underlying cause: **the HTML gets stripped at the end.**

So the Markdown gets converted to HTML and then it's stripped. The video I provided, in fact, shows HTML contents being inserted _via the toolbar_ and getting stripped.

I am astonished that this kind of behavior has being there on WordPress.com for so long. It's literally a user-content focused SaaS. Users leave comments using the comment form (which is based on this buggy implementation). They do not (nor cannot) use `wp-admin` to correctly format their own content.

**Comment by Lazza** [comment]
Sorry to ask, but is Automattic even considering this bug?

**Comment by Lazza** [comment]
This issue is still present and it would be great if it gets fixed.

**Comment by Lazza** [comment]
Good grief... 😞

**Comment by Lazza** [comment]
It's a bit weird to see that this bug was not considered in over 4 years.

Recently I switched from being a paying user of WP.com (for several years) to hosting WP myself. If customers do not get any kind of support, it's not worth paying for it.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES

_While reviewing for closure, I ran a quick test on a test site using Firefox 116.0.2 (64-bit) on Mac OS 13.4.1 using the sample comment above.  Tags present did not change from editing the comment via calypso. This issue may have seen improvement through other updates over time._
