### ISSUE TITLE
Store: Require complete address in initial store setup

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#21253]
To help avoid issues like [this](https://github.com/Automattic/wp-calypso/issues/21014) we should ensure that the address supplied during set up is complete and not allow the user to progress otherwise.

**Comment by allendav** [comment]
I propose either

1) the "Let's go" button is disabled unless street and city and postal code are filled in

or

2) on pressing the "Let's go" button, if street or city or postal code are not filled in, a global notice prompts them to enter required fields and the empty required fields have added to them a `This field is required.` FormInputValidation component

**Comment by timmyc** [comment]
Since the address info is pre-filled based off the customer info, it seems like there should be a somewhat low chance of this happening, i.e. a user would have to delete the form data that is pre-filled and then click "Let's Go"

I agree that since so much logic is based upon the store address we should add in validation at some point though... and in a way, now that we are having country selection be more prominent in this step for non US/CA signups we could look at adding it in then.

**Comment by jameskoster** [comment]
We need a `needs design` label xD
