### ISSUE TITLE
Loading dot in masterbar now scrolls with content and has a shadow?

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#21261]
This one is hard for me to reproduce as I am not clear on the logic of when the pulsing white dot appears, but when it does, it can scroll with the content. Trying going from Stats to blog posts on a slower connection maybe.

![image](https://user-images.githubusercontent.com/1123119/34573249-d46bcc24-f130-11e7-80c5-d8e8671f9a8b.png)

**Comment by designsimply** [comment]
The pulsing dot in the masterbar is expected to show when you navigate to an area that you don’t yet have the code for. It should show up in cases where you are delayed for more than 400ms while navigating. (p4TIVU-2uN-p2)

Related code search: https://github.com/Automattic/wp-calypso/search?utf8=✓&q=pulsing-dot

Perhaps absolute positioning without a relative parent is the culprit? See https://github.com/Automattic/wp-calypso/blob/master/client/components/pulsing-dot/style.scss#L4

**Comment by MichaelArestad** [comment]
@designsimply That might do it. Could you reproduce it?

**Comment by designsimply** [comment]
I tried but any time I triggered the pulsing dot, it disappeared too quickly for me to test scrolling even. I suspect it will become easier to debug if you can find something in Calypso which happens to be loading very slowly (or force it to as a test?).

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
