### ISSUE TITLE
Themes: allow Jetpack sites in modal site-selector

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2128]
~ This is part of a macro-feature to install .com themes to Jetpack, see #2123 ~

Raised by @seear 

Remove the filtering of Jetpack sites from the preview/activate/customize site-selector modal in multisite mode if Jetpack >= 3.7beta

Note: this should only be done once we can install wp-com themes to jp sites.

**Comment by ockham** [comment]
Let's devise a plan how to do this @seear and @budzanowski.

As discussed in our weekly team chat today, I think most of the logic we need is in `theme-options` already; we only need to add some missing pieces. I think what's key to this is the observation that some options are always mutually exclusive (such as `activate` and `activateOnJetpack`), depending on some criteria which right now are handled by `hideForSite` and `hideForTheme`. However, this still relies on us to manually either use `activate` _or_ `activateOnJetpack` in a `connectOptions()`'s `options` prop.

So maybe we can instead merge those otherwise mutually exclusive options into one. This way, the 'Activate' option would know what to do when called through a `ThemesSiteSelector` depending on what kind of site it is called for. This would obviously need to have access at state (to use selectors like like `isJetpackSite`). 

We could do this at action level (using `getState` there, sigh), but that wouldn't cover a possible future extension: `activate` and `purchase` are also mutually exclusive, but they also have different labels, so they can't be handled purely at actions level.

**Comment by ockham** [comment]
Maybe we can come up with a solution at options level. We need some way to inspect state in order to flexibly rely on arbitrary selectors Something like:

```js
const activate = {
	label: /* ... */,
	header: /* ... */,
	action: ( state ) => ( isJetpackSite( state ) ? installAndActivate : activateTheme,
	hideForTheme: /* ... */
};
```

maybe. (Only that in reality, because of our appending `-wpcom`, it'd look a bit uglier -- replace `installAndActivate` by `( themeId, siteId, ...args ) => installAndActivate( themeId + '-wpcom', siteId, ...args )`.)

`connectOptions` would then need to pass `state` to the option's `action` field in its `mapStateToProps`, before binding the result to `dispatch` in `mapDispatchToProps`.

Hmm, this could actually work...

**Comment by seear** [comment]
> because of our appending -wpcom, it'd look a bit uglier

We could append the `-wpcom` inside the `installAndActivate` action.

**Comment by ockham** [comment]
I campaigned for not doing that so we could also using the action for installing from dotorg. But we can use an intermediary variable in theme-options. I've spun up a branch that I'll push shortly.

**Comment by ockham** [comment]
After a little experiment in #10959, we've decided to tackle this at action rather than option level, since it's going to be a lot easier that way.
