### ISSUE TITLE
Reader: "Back" button is limited to other Reader pages.

### ISSUE THREAD

**Issue by jonathansadowski** [Automattic/wp-calypso#21299]
When linking to a site in Reader from outside of Reader (for example, the Likes Popover introduced in #21258), the "Back" button either does not appear (if no Reader page has yet been visited), or links to the last page in Reader, as opposed to the last page in Calypso.

To reproduce:

* Start on the "Blog Posts" page in fresh load of Calypso for a site that has posts with Likes. (Be sure to reload the page).
* Click on "[n] Like(s)" to toggle on the popover.
![image](https://user-images.githubusercontent.com/363749/34627607-dbce23f8-f226-11e7-937a-5e3923046815.png)
* Click on a name in the popover.
* You will be taken to the reader, but the "Back" button will be missing.

![image](https://user-images.githubusercontent.com/363749/34627772-84f2256a-f227-11e7-9606-5aab24eef2e9.png)

What I expected:

![image](https://user-images.githubusercontent.com/363749/34627721-5b445cf6-f227-11e7-9ec7-b2e8e56a09ea.png)

Note: it appears that Reader [attempts to track `lastPath` within its Controller](https://github.com/Automattic/wp-calypso/blob/126f3cff8f0763edec9beab8e32ec6f722d81cef/client/reader/controller.js#L91). Should we perhaps use [`hasNavigated`](https://github.com/Automattic/wp-calypso/blob/250a2a48e8a73f25c5415abe5a82fd880be72f77/client/state/selectors/has-navigated.js)?

**Comment by gibrown** [comment]
Another related bug to this came up here.

If I start reading an article in the Reader, and then click on a link in it, which takes me to a different website, then I click on the browser’s back button, I get back to the post I was reading in the Reader, which makes sense. But then if I click on the “back” link in the Reader, it takes me to my stats. I made a short screen recording of this.

Feels like this would need a similar fix so tracking in the same place for now.

**Comment by robfelty** [comment]
There is one more related issue - if I am reading an email digest and I click on a link which takes me to the Reader version of that post, and then I click the back button, I also end up at my stats page. I would expect to end up at my Reader home.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
