### ISSUE TITLE
View Site: Incorrectly adds pathname to end of site URL

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#21311]
#### Steps to reproduce
1. Connect my site to wordpress.com
2. When I click view site on wordpress.com it use wrong url! My site's url is https://violet-letter.delivery/home/, but wordpress.com use https://violet-letter.delivery/home/home/, it drive me   crazy!

#### What I expected
I expect wordpress.com use the correct url of my site.

#### Screenshot / Video
<img width="625" alt="wordpress bug2" src="https://user-images.githubusercontent.com/32959316/34640160-7d57e7b6-f328-11e7-97a1-6ede180dde54.png">
<img width="1440" alt="wordpress bug" src="https://user-images.githubusercontent.com/32959316/34640162-8697a7c6-f328-11e7-8737-26f0397a1024.png">

**Comment by EriikR** [comment]
And the WordPress version is 4.9.1

**Comment by ramonjd** [comment]
@EriikR 

Thanks for taking the time to submit an issue 👍 

From what I can see, your site's URL looks okay, however when Calypso displays it in the preview ToolBar it's [concatenating the pathname](https://github.com/Automattic/wp-calypso/blob/15bc4a2f89581124fecf47fe8a233c211fe5ad65/client/my-sites/preview/main.jsx#L102), in this case `/home`, to the end of the url.

This happens when the [preview frame updates](https://github.com/Automattic/wp-calypso/blob/15bc4a2f89581124fecf47fe8a233c211fe5ad65/client/components/web-preview/content.jsx#L111). 

There's a potential fix in broadening the following condition to check for `\` + some characters:

```
this.setState( {
    externalUrl: this.props.site.URL + ( pathname === '/' ? '' : pathname ),
} );
```

**cc**ing folks here to verify: @spen @lamosty

**Comment by EriikR** [comment]
@ramonjd Thank you for fix this problem!

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

This issue is no longer reproducible with the following steps:
1. open a page or post in editor.
2. click on `Preview`.

Here are the screenshots of the relevant location.
Post preview:
![Screen Shot 2021-02-11 at 3 02 38 PM](https://user-images.githubusercontent.com/6549265/107709654-6ae2f200-6c7a-11eb-8b3d-8814434a90a6.png)

Page preview:
![Screen Shot 2021-02-11 at 3 03 00 PM](https://user-images.githubusercontent.com/6549265/107709675-733b2d00-6c7a-11eb-8970-86d4cb03e83c.png)


As this issue does not appear to be reproducible, it is being closed with the label `Closed - Not Reproducible`.
