### ISSUE TITLE
Devices that no longer have the app installed still show up under `/me/notifications`.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#21344]
Originally reported by @wensco in https://github.com/Automattic/notifications-panel/issues/198:

I went to https://wordpress.com/me/notifications to remove email notifs from one of the p2s I follow and noticed that the mobile notifications list a specific mobile device. 

I got a new phone a couple days ago and it didn't occur to me that this would have any impact on notifications.

I noticed that all of the mobile notifications look like they are being sent to my old device (samsung s6, which was factory reset so the app should no longer be associated with that phone), yet I am receiving notifications on my new Pixel device. Below is an example of how my mobile notifications look for every blog I follow:

<img width="708" alt="notifications samsung" src="https://user-images.githubusercontent.com/7942966/33630136-48c3fe62-d9d4-11e7-8136-70093694236b.png">

I now have a dropdown where I can choose between the current Samsung and my new device, Pixel. 
http://d.pr/i/opzXGv

Based on the fact that I am getting notifications on the Pixel, I'm not sure that it's necessary to update the device listed in the drop down. If I do need to update, there is no way to globally edit all of the blogs I follow to use the new device. Perhaps we can either remove that dropdown if it's not necessary or allow users to globally update it.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
