### ISSUE TITLE
VideoPress: Captions not appearing in posts

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#21352]
#### Steps to reproduce
1. Add a video to the Media library. 
2. Edit the video in Media and add a caption.
3. Insert the video into a post

#### What I expected

The caption to be displayed as it is for images

#### What happened instead

No caption is displayed

#### Browser / OS version

Chrome Version 63.0.3239.132 (Official Build) (64-bit)
macOS High Sierra 10.13.2

(Seems to be browser/OS independent)

#### Screenshot / Video

Captions: 
<img width="1276" alt="screenshot 2018-01-08 19 40 04" src="https://user-images.githubusercontent.com/7596032/34699588-389ebd0e-f4ac-11e7-9e62-e273b2b08a5b.png">

Inserted into post here: https://tacotestpremium1.wordpress.com/2018/01/09/test-of-media-posts/

Along with an image showing the caption in the same field properly displayed.
#### Context / Source

#user-report in #1478367-hc / #888641-z

I added it to my test site and checked with a couple themes with the same result. It also displays the same way in the Calypso editor. The wp-admin editor only displays the wpvideo shortcode.

**Comment by kriskarkoski** [comment]
6004821-hc

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
