### ISSUE TITLE
Store: Smooth the transition from NUX (set location) to Woo Wizard for nonUS nonCA stores

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#21376]
In https://github.com/Automattic/wp-calypso/pull/21297#issuecomment-356127245 @kellychoffman wrote

> The transition from the address step to the WooCommerce wizard is pretty abrupt. I think we should mention WooCommerce in the address step if the user picks a non supported country to ease that transition.

**Comment by kellychoffman** [comment]
Okay, this took a bit to figure out, but I think our best best is to borrow the Powered by Jetpack footer and add in a Powered by WooCommerce footer: 

<img width="844" alt="screen shot 2018-01-09 at 3 43 16 pm" src="https://user-images.githubusercontent.com/5835847/34747105-0344268c-f554-11e7-9335-bbc1b3e07bfc.png">

This introduces the WooCommerce name and branding so that the next step isn't as jarring.

**Comment by kellychoffman** [comment]
[WooCommerce SVG file](https://cloudup.com/cj56ldONOBV)
