### ISSUE TITLE
Domains: Redirect Loop

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#2142]
If there's a user account with only one site, and the user has Editor permissions on that site;
if the user tries to go to a page that requires admin permissions (`/domains/manage` etc.), this will start a infinite redirect loop.
1. Admin page knows that the user doesn't have the permissions and redirects them to the site selection page.
2. Site selection page know that the user has only one site, and auto-selects it and redirects them to back to the admin page.

There _shouldn't_ be any links shown to the user, so I think this can only happen if the user types to URL to get to the site.

**Comment by lancewillett** [comment]
Closing #4800 as a duplicate.

**Comment by lancewillett** [comment]
> There shouldn't be any links shown to the user, so I think this can only happen if the user types to URL to get to the site.

I think this is what makes this a low priority — it'll be rare someone (not testing it specifically) types the URL directly.

**Comment by umurkontaci** [comment]
One case the user might have a specific URL is when they receive the URL from an HE while not having the necessary permissions to go to the page.

**Comment by gwwar** [comment]
Bumping the priority here since we render a domain link from the plans page. Let's do the following:

1. Mirror the capability check on /plans and check for `canCurrentUser( state, siteId, 'manage_options' )` before rendering a domain link
2. Detect this case in the router, and prevent the redirect loop. If a user doesn't have manage_options permissions and only has 1 site we should redirect to `/stats`
