### ISSUE TITLE
Comments: Race condition on subsequent do/undo/redo actions

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#21460]
This issue happens on the #21155 branch, which is close to merge so it will happen in prod as well.

#### Steps to reproduce
1. Open comments at `/comments`.
2. Find a tab with 1 comment (not mandatory, but it helps seeing what happens); usually Spam is helpful here.
3. Perform any action (except Delete) to the comment, and let it disappear from the list.
4. Undo the action.
5. Do any action again.
6. Undo again, and keep doing/undoing.

At some point (usually starting from the first "redo", but it depends on how quickly we perform the reproduction steps) there will be a race condition between the Redux state and the actual fresh comments data retrieved from the server, to decide which data has to be displayed in the page.

#### Why does this happen?

The comments page always display whatever we have in Redux state.
When we perform an action, we optimistically perform it in the Redux state as well to immediately show the results to the user. Behind the scene, though, we're firing a request to the server, that once completed will give us back the updated page of comments we're browsing (I'm simplifying here for clarity).
This fresh page of comments will get back to Calypso where it will be used to update the Redux state, which in turn updates the data rendered in the page.

Though, if we quickly do/redo, it might happen that the fresh page from the server in response to the "do" updates the Redux state after it was already optimistically updated by the "redo".

#### What can we do?

@gwwar suggested:
> We could probably improve on that by adding some detection in the data-layer to not dispatch the actual http requests if we detect nullifying actions.

**Comment by worldomonation** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. **Report anew**: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. **Reopen**: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
