### ISSUE TITLE
Editor: "Saving of draft failed" - scroll up to the header of the editor 

### ISSUE THREAD

**Issue by htdat** [Automattic/wp-calypso#21484]
#### Steps to reproduce

1. Add a wall of text to a post
2. Disconnect Internet 
3. Try to add some texts into the bottom of the editor. 
4. Wait for a bit
5. Display "Saving of draft failed" and scroll the pointer up to the top of the editor. 

#### What I expected

Keep the pointer in the same position. 

#### What happened instead

The step 5 above. 

#### Browser / OS version

Chrome - Mac OSX. 

#### Screenshot / Video

![draft](https://user-images.githubusercontent.com/10045087/34868307-e611f580-f7b5-11e7-9a8e-bd50c65eca32.gif)

#### Context / Source

252879-h
p1515745223000040-slack-helpshift

**Comment by rachelmcr** [comment]
We received another report of this bug in the desktop app (https://github.com/Automattic/wp-desktop/issues/420). The report includes an important note about the impact of this bug and suggests possible solutions:

> This means that once your post gets beyond a couple hundred words, this notification is almost constantly throwing you back to the top of the screen, losing your place. When this starts happening every five seconds, I quit.
> 
> Possible fixes:
> 
> Add preference to disable the notification entirely (my preferred solution).
> At least prevent the notification from scrolling the window up.

**Comment by billisalive** [comment]
Thanks @rachelmcr ! 

A third fix: only show the notification when the user manually clicks PUBLISH or UPDATE. This is the only time I really need to know that saving failed, and it's reasonable to see this notification then.

This is assuming that the app is saving a local copy somewhere, a copy that it can recover if the app crashes. Oops, I guess that is not here yet, it's in the offline editing enhancement: https://github.com/Automattic/wp-desktop/issues/132 I'll go comment there.

**Comment by rachelmcr** [comment]
>A third fix: only show the notification when the user manually clicks PUBLISH or UPDATE. This is the only time I really need to know that saving failed, and it's reasonable to see this notification then.

The editor autosaves as you write, so a notification is needed to alert you if you're relying on autosave and it fails.

**Comment by billisalive** [comment]
True -- this makes sense to me as a sensible default. Maybe the larger problem is the lack of being able to save locally to the disk, over in https://github.com/Automattic/wp-desktop/issues/132. Until that's an option, adding a preference to disable the notification would make this usable if the host starts glitching. But maybe the cleaner fix, rather than disabling, would be to restyle the notification so that it doesn't scroll the window up.

**Comment by spen** [comment]
Thanks for raising this issue @htdat 

I've faced this issue myself in the past few days while writing and travelling and I'm really not happy with it. I'm a proponent for making WP.com work offline so I'm going to take a look at fixing this up in the near future.

I think the fix that makes most sense as a quick solution is to just find the logic that is doing the scroll-jumping and squish that but I agree that we could improve on this too (As @billisalive suggests, a 'don't show this again' type opt-in could work).

We often, but seemingly not always, show a 'offline' pip in the centre of the header when there is no connection. I think it'd be fair to elaborate on this; show a warning somewhere to inform the writer that auto-saves are not available due to the lack of connection and avoid trying to call the autosave as we do now.

> I would love to use it, but a small problem is making it unusable.

@billisalive, thanks  for bringing this up in the desktop repo, I fully agree with your statement!

**Comment by spen** [comment]
Addressed (admittedly naively) in #22956

**Comment by lancewillett** [comment]
This came in again via a customer, this time on Twitter to start: https://twitter.com/ideafaktory/status/973467475814899712

> Autosave triggers ‘saving of draft failed’ pop-up that scrolls to top of post, loses your place in editor, over & over. Should be an easy fix.
