### ISSUE TITLE
Shortcodes appearing in New Post Notification summaries

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#21535]
1. Follow a site you own and turn on New Post notifications
2. Create a new post that starts with a `[caption]` shortcode with an image
3. Notice the notification you receive includes the `[caption]` shortcode in the summary, though the true full post looks fine

The notification summary should not include the shortcode.

**Comment by blowery** [comment]
D9324-code might fix this

**Comment by worldomonation** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. **Report anew**: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. **Reopen**: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
