### ISSUE TITLE
Store: Payment gateway fee description doesn't take in account other countries with different fees

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#21556]
At the moment when we check the Store settings, under `Method: Stripe` or `Method: PayPal`  we can see `2.9% + 30c per transaction` this seems to be a string hard coded into `payments__method-information` .

<img width="1280" alt="screen shot 2018-01-16 at 09 14 15" src="https://user-images.githubusercontent.com/3812076/34984227-c91e0c40-fae2-11e7-9593-44f7fe69c0bd.png">

However this is not true for every country, if I click on Stripe more information link I'm redirected here: https://stripe.com/pricing , and throws a different price:

<img width="1232" alt="screen shot 2018-01-16 at 09 09 17" src="https://user-images.githubusercontent.com/3812076/34984341-2b1784ee-fae3-11e7-9efc-0d9222429af3.png">

**Comment by allendav** [comment]
I think https://github.com/Automattic/wp-calypso/issues/21304 covers this as well, no?

**Comment by designsimply** [comment]
<blockquote>I think #21304 covers this as well, no?</blockquote>

It's hard to tell from the description in #21304, because that issue talks about store routes such as store/products, store/promotions, etc and #21556 mentions https://stripe.com/pricing which is not a store route. If the work there covers this, then I would defer to you to close this one as a duplicate. I really like that this issue is very clear and includes screenshots though! Having that makes it a lot easier to test and confirm a fix when needed.

**Comment by allendav** [comment]
Adding this to the list in https://github.com/Automattic/wp-calypso/issues/21574 and closing this issue. And yep - the screenshots are super helpful!
