### ISSUE TITLE
Export: _publicize_failed_xxxx log data being included in <wp:postmeta> in exports leading to failed imports

### ISSUE THREAD

**Issue by jaymendoza** [Automattic/wp-calypso#21581]
We're including `_publicize_failed_xxxxx` log data in exports, which is potentially causing issues importing into self-hosted (and potentially other types of) WordPress sites and is also making exports larger than they need to be.

xmllint shows that the issue is with the `0x0` character. See the second screenshot below.

Note that the WordPress.com importer was able to import this file just fine, but a self-hosted WordPress installation was not able to import, receiving a repeated `failed to import post tag` error.

Issue reported here: 1551355-hc

#### Steps to reproduce
1. Starting at URL: curvygirlthin.com (username: curvygirlthin)
2. Do a full export Settings > Export > Export All
3. Try to import the 2nd and 3rd of the three files into a self-hosted install

#### What I expected
1. The import would move forward successfully

#### What happened instead
1. The import times out or gives a 500 error

#### Screenshot / Video
Example export output w/ log data: 
![screen shot 2018-01-16 at 5 50 52 pm](https://user-images.githubusercontent.com/22968/35019278-a6039230-faeb-11e7-9b2b-adebf3bde6f4.png)

xmllint output:
<img width="750" alt="screen shot 2018-01-16 at 5 29 02 pm" src="https://user-images.githubusercontent.com/22968/35019279-a8a4f89e-faeb-11e7-9e71-8efecb0d49f9.png">

(For posterity) I added the example XML in a link on inside 903512-zen (internal reference) in case you are a Calypso developer working on this issue and the original export would be helpful to have.

**Comment by liviopv** [comment]
Leaving this as a workaround for future HE with the same issue:

1. Open the XML on a file editor like Atom
2. Search for "[CDATA[O:13:"Keyring_Error":2:{s:16:"
3. Manually remove the Publicize failures from `<wp:postmeta>` to `</wp:postmeta>` from the file
4. Save and import again.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
