### ISSUE TITLE
Purchases: Autorenew can't be disabled

### ISSUE THREAD

**Issue by Jstachurski** [Automattic/wp-calypso#2162]
In the /purchases page, users are unable to disable the autorenew feature. If they renew an upgrade or make a new purchase, they are automatically set up for auto renew. However, they cannot disable this feature without contacting support.

**Comment by fabianapsimoes** [comment]
@mikeshelton1503 here's another case of the feedback @aisajib gave us previously.

**Comment by mikeshelton1503** [comment]
@Jstachurski Auto-renew is no longer a setting. A user can cancel a Purchase (which will effectively turn off the auto-renew).

However, during the refund period there currently isn't a way for a user to only cancel their subscription (and not have it also removed from their site). Is this the issue you are referring to?

**Comment by davoraltman** [comment]
Hey folks :) It might be confusing for users without the actual auto-renew setting. I preferred the old way when you could turn on/off the auto-renew feature if you wanted to. Is this something that can be brought back at one point? If more people ask for it, for example :) Thanks!

**Comment by mikeshelton1503** [comment]
@davoraltman We are always are looking for feedback from our users so any feedback you find from users regarding auto-renew please do share. Right now, the only confusion we expect is potentially from long standing customers who were use to the auto-renew setting since it is a notable change. They may feel the same way you do: "I preferred the old way " simply because it's a change. However the change has positive impacts on the UI and UX so the trade of seems worth it right now.

**Comment by supernovia** [comment]
@mikeshelton1503 I realize this issue is closed, but I have someone who ran into the scenario you mentioned: they bought an upgrade and want to disable autorenew now, without having to wait for 30 days to avoid canceling their account.

I have also heard from many users who were concerned about canceling their renewal when they really just don't want to be charged automatically next year: they may want to use a different card, for example.

Is this something we would consider reopening?

**Comment by mikeshelton1503** [comment]
Thanks @supernovia for bringing this up.

>they bought an upgrade and want to disable autorenew now, without having to wait for 30 days to avoid canceling their account.

That's a separate issue from the one this was opened for, so let's create a new issue for it. Would you mind doing so, including as much information about customer interaction as possible (and even better any other similar customer interactions you know of)?
