### ISSUE TITLE
Thailand phone numbers not validating for 2FA

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#21862]
Adding a phone number with the Thailand country code returns a validation error for 2FA.

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/
2. Go to Security
3. Click Two-Step authentication > Get Started
4. Select “Thailand” in Country code
5. Enter a phone number (minus country code)
6. Click “Verify via SMS” or “Verify via App”

#### What I expected

To be prompted to complete the verification process.

#### What happened instead

I saw the error, “That phone number does not appear to be valid”.

#### Browser / OS version

Chrome
Firefox
Safari

#### Screenshot / Video

![2fa-thailand](https://user-images.githubusercontent.com/11627765/35445678-46b19a18-02aa-11e8-85e1-1f9e210a34e8.jpg)

#### Context / Source
918277-zen

#user-report
#manual-testing

**Comment by rachelmcr** [comment]
In this case, the user tried to enter a phone number beginning with `6` but we only accept numbers beginning with `8` and `9`: https://github.com/Automattic/node-phone/blob/6be6549b03137f2cca01e202250bf2590750119e/lib/index.js#L1657

According to Wikipedia `6` is used for VoIP numbers: https://en.wikipedia.org/wiki/Telephone_numbers_in_Thailand#Mobile_phone_codes_and_IP_telephony

**Comment by gemmagarner** [comment]
Thanks for this information, it's really useful! Does this mean we are unable to accept numbers starting with `6`?

**Comment by arcangelini** [comment]
I am not sure that Wiki article makes a lot of sense. The first line says that, but the table of area codes below labels only 060 and 068 as VoIP numbers. On another site I found 6,8, and 9 listed as valid cell phone prefixes. The user has responded back saying that he is on the mobile carrier AIS which does match the Wiki article table

<img width="320" alt="telephone_numbers_in_thailand_-_wikipedia" src="https://user-images.githubusercontent.com/33258733/35638419-aebed514-067c-11e8-88ce-14107e00df8e.png">

Is this something that will be possible to update? Thanks : )

**Comment by samvaidya** [comment]
Just had another reported case of this.  https://woothemes.zendesk.com/agent/tickets/952965

**Comment by CompChris** [comment]
I've also had the user that @samvaidya reported above come back and report that there is still a problem here (320399-hc). 

Is there any chance we have any new info on this? Thanks!

**Comment by gemmagarner** [comment]
Another report in 1463227-zen.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES

I quickly tested adding the phone number from the original report, 918277-zen, as a 2FA number on a test site, and the number was accepted, so this may also be resolved with more recent work. Closing as resolved.
