### ISSUE TITLE
Plans discounts differ from what is shown in jetpack.com (200 vs 299)

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#21879]
> Plans discounts differ from what is shown in jetpack.com (200 vs 299) — whenever the prices are updated, we should do the same on the jetpack.com tables, even if it means updating manually for now.

Reported by @keoshi on p9rlnk-3m

I'm wondering if this is taking into account the cost of premium (included with your site) and deducting that from the total. Thoughts?

**Comment by beaulebens** [comment]
As far as I can tell, everything is showing correctly. We don't show "discounts" available on jetpack.com because we just show the full, "shelf" price. On WP.com, we show "discount available" in the context of the current site, if you're already on a lower plan (e.g you might see $200 for a plan, where you already have a $99 plan) because we offer that discount in that context.
