### ISSUE TITLE
Jetpack Onboarding: After JPC, redirect back to the proper place

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#21916]
As reported by @gravityrail in p1HpG7-4O1-p2#comment-24206, after connecting Jetpack after the Jetpack Onboarding flow we are currently redirecting to /posts in Calypso. We probably need to redirect to wp-admin or something else that works best.

**Comment by ockham** [comment]
If connecting is successful, then redirecting to Calypso might make sense. Maybe some section that comes with a Guided Tour (or similar continued onboarding experience).

**Comment by ockham** [comment]
So apparently, in other places, we're using either Guided Tours, or Trampoline (which is similar, but uses the site's frontend -- plus sidebar -- instead of Calypso). I verified that Trampoline isn't available for JP sites. Guided Tours might work -- we'd just have to find a suitable one.

Or we just point to `/plans` because 💰.
And consistency with the "normal" JPC flow, which might be an even more relevant argument 😁

**Comment by tyxla** [comment]
With that in mind, `/plans` makes sense for when user selects the free plan, right? And for when the user selects a paid plan, we can just follow along with what JPC uses by default. PR coming for that.

In the meantime, if any of you folks have insights about where we should redirect to after connecting a site coming from the onboarding flow, please feel free to comment.

cc @Automattic/luna, @joanrho @MichaelArestad @rickybanister

**Comment by tyxla** [comment]
#22334 tackles this one.

**Comment by ockham** [comment]
For reference: https://github.com/Automattic/wp-calypso/tree/master/client/layout/guided-tours#list-of-tours

The `main` tour would be an alternative to `/plans` :slightly_smiling_face:

**Comment by tyxla** [comment]
Alternative (and a more universal) solution comes in #22341.
