### ISSUE TITLE
Domain Management: Accept transfer state for domain transfer

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#2197]
Per conversation with @umurkontaci, we do in fact need to show an "accept transfer" state for domain transfers (we previously thought this might be doable within an email). Here's the proposed design:

<img width="742" alt="screen shot 2016-01-07 at 11 11 02 am" src="https://cloud.githubusercontent.com/assets/3011211/12180073/5cf50956-b52f-11e5-8c0b-15ab9ed538c8.png">

This design assumes we know the name of the registrar the domain is being transferred to. I'm not sure if we will have this info -- if not, replace with "to another registrar" in that sentence.

**Comment by umurkontaci** [comment]
Thanks @breezyskies, we also used to show a "Deny Transfer" button along with the accept one. I think it kinda makes sense to keep that because the transfer goes through by default (even though the user doesn't click "Accept" the domain will be transferred after the specified period (around 5-7 days, I suppose). There's a chance that Accept might speed things up, but essentially denying stops the transfer and changes the flow.

**Comment by breezyskies** [comment]
Added the "deny" option:

<img width="741" alt="screen shot 2016-01-07 at 11 42 21 am" src="https://cloud.githubusercontent.com/assets/3011211/12180939/33819b7a-b534-11e5-9787-e7ee96dc79d9.png">

Note that I also moved the buttons to the right (to be more consistent with other areas of Calypso). Let's also move the "Request Transfer Code" in the initial state to the right for consistency.

(Also just a side note that [our docs](https://en.support.wordpress.com/transfer-domain-registration/#completing-the-transfer) state that accepting the transfer in this state will "initiate the transfer immediately" -- not sure if that's correct but wanted to point it out in case we need a docs update.)
