### ISSUE TITLE
Editor: Pasting a bulleted list from Google Docs, with bold items, breaks the list layout

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22021]
I know this is somewhat obscure and specific, but since it's part of a regular flow for me, I run into it at least once a week, if not more.

To reproduce:
- create a new Google Doc
- create a bulleted/numbered list with many items
- somewhere in the middle of the list, select an entire line/item and **bold** it
- copy the entire list
- paste into Calypso editor
- observe broken formatting of the list

in Google Docs;
![screen shot 2018-01-31 at 1 51 22 pm](https://user-images.githubusercontent.com/108942/35646852-d70d3f7c-068d-11e8-96d0-d7953bce5fb3.png)

pasted into Calypso;
![screen shot 2018-01-31 at 1 50 52 pm](https://user-images.githubusercontent.com/108942/35646832-c69b629a-068d-11e8-959e-31b16bd4da89.png)

It's completely possible/likely that this is actually a TinyMCE bug.

I'm observing this in Chrome/macOS in case that's relevant.

**Comment by rachelmcr** [comment]
I tested this in core and reproduced the issue in TinyMCE. I then tested in Gutenberg and the list pasted with the correct formatting, so this should be resolved once Gutenberg launches.

Since it will be resolved with Gutenberg, I'm inclined to close this issue unless you think it's high enough priority to try to fix before then.

#gutenburg-bug-purge

**Comment by beaulebens** [comment]
That's excellent news! Definitely not super high priority, even though it's annoying.

Let's switch everything to Gutenberg pronto! :)
