### ISSUE TITLE
Editor: Preview doesn't update when featured image is changed on existing post

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/wp-calypso#22083]
#### Steps to reproduce
1. Edit an already-published post. (I tried this on goblinartificer.wordpress.com with a couple of posts)
2. Change (or add) a featured image. 
3. Click Preview.

#### What I expected
A preview with the updated featured image.

#### What happened instead
A preview with the old featured image (or none if there wasn't one). 

#### Browser / OS version
Chrome on Win10. User who reported this issue used both Chrome and Edge (presumably on Win10), cleared cache/logged out and tried again.

#### Screenshot / Video
I can grab one if needed!

#### Context / Source
This was a #userreport ! See 1614519-hc and 1696798-hc :) Previous HE couldn't replicate it but I could.

**Comment by designsimply** [comment]
Tested and confirmed that previews do not include a change to a featured image made to an existing post. Nice catch @kamikazeballoon!

Video: [44s](https://cloudup.com/cg6un2B_IOQ)
<sup>Tested with Firefox 58.0.1 on macOS 10.13.3 on a WordPress.com Simple site.</sup>

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was not able to reproduce this issue with an existing post on both SImple and Atomic sites. On both, the preview after setting the Featured Image features the correct image.

As the issue is no longer reproducible this issue is being closed with the label `Closed - Not Reproducible`.
