### ISSUE TITLE
Free Trials: Loading skeletons for plans shows on free trial hub

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#2211]
I believe this was reported [earlier](https://github.com/Automattic/wp-calypso/issues/1465#issue-121507993) by @fabianapsimoes but I couldn't find a current open issue for it. 

![l9xnczy7m9](https://cloud.githubusercontent.com/assets/3011211/12183254/ae06191c-b542-11e5-8dea-648abe9301ad.gif)

**Comment by fabianapsimoes** [comment]
Yep, this is related to https://github.com/Automattic/wp-calypso/issues/1465.

Before the PR that closed that (https://github.com/Automattic/wp-calypso/pull/1987), we displayed both the skeleton and the regular content in `/plans`. The PR removed `/plans` but left the skeletons.

---

Adding this to V2 since it isn't a critical issue for the first test.

**Comment by fabianapsimoes** [comment]
Free Trials are on hold indefinitely while we iterate on our plan offerings. Closing this, since the way trials are offered will have to be reviewed thoroughly once we get back to them.
