### ISSUE TITLE
Educate after connecting to "Photos from Google"

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#22132]
After successful connection to **"Photos from Google"** feature, we leave users guessing what they should do next.

In `https://wordpress.com/sharing/:site`

![other-connections](https://user-images.githubusercontent.com/87168/35810113-4a4691a6-0a93-11e8-8003-82dea5514cf4.png)

It's hard to guess you need to go to **Media** and then press the "W" icon and only then you'll be able to access your photos:

![w](https://user-images.githubusercontent.com/87168/35810150-69c6a62e-0a93-11e8-9086-534b0ad51f56.png)

![image](https://user-images.githubusercontent.com/87168/35810173-8339bb5a-0a93-11e8-8b24-cb71952b2b8e.png)

**Comment by jancavan** [comment]
There's actually instructions written, but it's not obvious because you'd have to expand the section to be able to see it:

![screenshot 2018-06-21 15 14 44](https://user-images.githubusercontent.com/4924246/41748263-f1f9223c-7565-11e8-92ff-361f4ba4e89c.png)

Suggestion: expand the section (and all the other sections for that matter) once it's connected, but I think copy should be updated to say that it is, in fact, already connected.
