### ISSUE TITLE
My Sites: Domain expiration sidebar notification only displays only on CurrentSite

### ISSUE THREAD

**Issue by bikedorkjon** [Automattic/wp-calypso#2218]
Normally on a single blog account when a domain is in an expired state a notification is shown in the sidebar of My Sites. When a user has multiple blogs, if they have a domain that is expired on site that is not the primary, the notification is not shown until they navigate to that particular site. What this means for the user is that they will likely miss that notification.

Steps to replicate:
1. Find an account with an expired domain on a multisite where the site is not primary (ping me for example account)
2. After signing in, navigate to My Sites and confirm that there is no message in the primary site for the non-primary domain expiration
3. Switch to the site with the expiring domain to confirm the notification is showing.

The notification is mounted to the CurrentSite, and we need to change so it's visible in the site list regardless of what the CurrentSite is.

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/components/domain-warnings

props @drewblaisdell for shedding light on how this works

**Comment by alisterscott** [comment]
I confirm this is still displaying only for the expired site, not when another site is selected. I would be more inclined to say this is a usability enhancement than a bug per say, since it does display for the effected site.

Expired Site View:

![expired site](https://cloud.githubusercontent.com/assets/128826/14904398/4c8b2aea-0deb-11e6-973c-301990248071.png)

Non Expired Site View (same user)

![non-expired](https://cloud.githubusercontent.com/assets/128826/14904410/676afd18-0deb-11e6-87e2-33914f7aebbf.png)

**Comment by klimeryk** [comment]
The domain warnings shown in that space are meant to be very succinct hints related to the current site - expiring domains, unused domain credit. While I understand your intentions here, I think including a notice here from all the user's sites here would just confuse the user. We are sending email reminders, showing overlays and notices on affected sites - based on your experience do you think a lot of users miss these notices because they are not visiting the affected sites and/or missing the emails? Just wondering if the effort is worth the possible gains - implementing this in a performant way could be tricky, especially for a user who has a lot of sites 😕

**Comment by klimeryk** [comment]
Closing this - during these >7 months we've hopefully improved our domain warning notices and email reminders that this doesn't seem to be a problem anymore (seen from the lack of interest in this thread). Also, the proposed approach is conflicting with the current design and would require significant work to implement - other options seem more worth investigating.
