### ISSUE TITLE
Jetpack Settings: Stats notice should be converted to a module toggle

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#22216]
Right now, if a user has their Stats Jetpack module deactivated, we display a notice that contains a button to activate that module:

![](https://cldup.com/VoKD8WdDxd.png)

This is inconsistent with the rest of the settings for modules where we display a module toggle, for example **Ads**:

![](https://cldup.com/A4mR7tzTnn.png)

In order to make it less scary and more consistent, we should turn the notice into a card with a module activation toggle.

cc @rickybanister

**Comment by beaulebens** [comment]
This is a perfect example of what I've been calling "implicit activation". The customer shouldn't have to care about a module being active or not. They want the feature (or not). If they choose to use the feature (in this case, toggle the "Enable ads..." toggle), then under the hood we should activate the module and do whatever we need to do to make it work. The UI itself shouldn't care about the module being technically activated or not.

**Comment by sirreal** [comment]
I think we need a designer's input here. When the module is enabled, it's not clear where a toggle would go or what should be shown:

![enabled](https://user-images.githubusercontent.com/841763/37030012-a263031c-2139-11e8-8a69-4762ca40802e.png)

It seems like the button is used because it's "one-way," click to enable, then you see something else. A toggle implies something you can turn on and off, which doesn't seem to work well with the existing stats settings.

**Comment by tyxla** [comment]
I'd go for implementing the toggle directly in the foldable card section header, like it's done in "After the Deadline" and "Protect" settings:

**Settings > Writing > After the Deadline in Calypso - module enabled and section expanded**
![](https://cldup.com/WmV92Va-fW.png)

**Settings > Security > Protect in Calypso - module enabled and section expanded**
![](https://cldup.com/4dDVuI6od0.png)

**Comment by sirreal** [comment]
Thanks for that @tyxla, I went ahead and implemented the proposal in #23032 :+1:

**Comment by tyxla** [comment]
Beautiful, @sirreal, will jump in to review it soon 👍
