### ISSUE TITLE
Showcase: Change the search placeholder text

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#22251]
#### The Problem
The problem is often times users don't know what they're looking for, so they don't bother clicking into the search field. Can we update the text so that it prompts users differently?

Current placeholder text:
`What kind of theme are you looking for?`

Proposed text revision:
`Search by feature, style, designer, or industry`

#### Current 
![screen shot 2018-02-08 at 8 17 44 am](https://user-images.githubusercontent.com/617986/35984934-493f6738-0caa-11e8-8d61-8f734a42c0c6.png)

#### Proposed
![proposed-placeholder-search](https://user-images.githubusercontent.com/617986/35985033-8877fcc6-0caa-11e8-9dde-dc1b233186b8.png)

**Comment by mapk** [comment]
@davidakennedy Any thoughts around this? What do you think of the proposed text change? Should we ping anyone else? @kjellr, your thoughts?

**Comment by kjellr** [comment]
> Search by feature, style, designer, or industry. 

My first reaction is that this seems a little more "technical" than the existing prompt. "What kind of theme are you looking for?" seems to want a fairly vague answer, whereas this new one asks for more specifics. I'm not sure if that's more intimidating or if it's useful. 

I'd probably leave "designer" out, since that sounds like a probable edge case. "industry" seems like an important term, but it might need to be tweaked to be a little more colloquial. I'm not sure we use the word industry elsewhere (I'm adding the `Needs Copy Review` tag here for some expert perspective on that). 

Either way, here's another idea: 

My gut says that in general, the biggest win we'd have here would be to incorporate the suggested styles on our logged-out form (but that'd be an entirely different PR. 😄):

<img width="1018" alt="screen shot 2018-02-08 at 12 08 19 pm" src="https://user-images.githubusercontent.com/1202812/35987072-c97c32f0-0cc8-11e8-857c-cfa7c23accdc.png">

Along those lines though, I wonder if the current prompt could be enhanced by adding some suggestions after it. For instance: 

> What kind of theme are you looking for? E.g. Blog, Portfolio, Magazine. 

Back when the Longreads.com homepage was just a search bar, we used to suggest some terms inside the search bar, and those quickly became the most popular searches. If the terms are chosen with purpose, I could see a similar tactic working well for our users.

**Comment by davidakennedy** [comment]
I like that this is more specific. Designer and industry feel vague. In the past, our top search terms made up the logged-out view filters on `wordpress.com/themes/`. Those are: Portfolio, Magazine, Business, Blog, Wedding, Travel, Food, Music. So maybe it's:

_What kind of site do you want to make?_

We should also dive into some analytics to double check top searches.

**Comment by kristastevens** [comment]
I love the visual idea that @kjellr has proposed. Because that is a ball of wax of a different variety, how about combining the intel @davidakennedy shares with the prompt? 

_I'm creating a site for a: portfolio, magazine, business, wedding, or blog_

The implication here is that "travel, music, and food" are likely covered under blog.

**Comment by kjellr** [comment]
One other factor to consider here: I'm not sure container terms like "Style" or "Feature" are going to be as necessary in the search bar prompt [if we also expose the search filters by default](https://github.com/Automattic/wp-calypso/issues/22228). Once that happens, those words will already be visible on the screen. Mentioning individual styles/features in the prompt would still seem like a useful enhancement though.

**Comment by mapk** [comment]
> I'm creating a site for a: portfolio, magazine, business, wedding, or blog

My concern is that this might be too limiting. What if the user just wants a slider... nothing else matters, I just want a slider. That's why I had "feature" in there as well.

**Comment by mapk** [comment]
> I'm not sure container terms like "Style" or "Feature" are going to be as necessary in the search bar prompt if we also expose the search filters by default. 

This is a good point, but something further to consider is that we want to completely revise the taxonomy on those filters as well. Possibly even display them differently. But while both exist simultaneously, they do seem redundant.

My goal with this is to get the user to feel comfortable to search for **anything** in that field. I think that should be obvious for them.

**Comment by kristastevens** [comment]
Given that the search filters are in place by default as Kjell notes, does this help to alleviate your concern, @mapk?

**Comment by mapk** [comment]
> Given that the search filters are in place by default as Kjell notes, does this help to alleviate your concern, @mapk?

For the most part, yes. Now should we word it in a question like @davidakennedy mentioned above, or as a statement like the example from @kristastevens?

**Comment by mapk** [comment]
I'm not sure which matches our tone and voice better. @kristastevens can you help guide this decision for me?

**Comment by kjellr** [comment]
I'm not sure this should dictate our decision in this specific case, but for what it's worth: we're consistently using the following format in our search fields:

> Search [something] ...

<img width="866" alt="screen shot 2018-02-08 at 12 50 35 pm" src="https://user-images.githubusercontent.com/1202812/35989358-fa1fcfec-0cce-11e8-9be5-65bf72251f95.png">
<img width="763" alt="screen shot 2018-02-08 at 12 50 51 pm" src="https://user-images.githubusercontent.com/1202812/35989359-fa305d94-0cce-11e8-9dd3-b115b4cde392.png">
<img width="949" alt="screen shot 2018-02-08 at 12 51 05 pm" src="https://user-images.githubusercontent.com/1202812/35989360-fa413272-0cce-11e8-9887-e94820f43a7a.png">

**Comment by kristastevens** [comment]
I don't think it needs to be question, per se. As a prompt in the dialog, I think it's clear that it's helping you to guide your thinking here. I think to riff off of Kjell's prompt collection, if we added an ellipses at the end of the statement, it twigs the user to input their own category, if it's not on the list we're suppling. That would make it: 

_I'm creating a site for a: portfolio, magazine, business, wedding, blog, or..._

**Comment by mapk** [comment]
Alrighty, thanks all! I'll get a PR ready to go.

**Comment by lancewillett** [comment]
Have we considered making the "search by" menu always open?

This has come up often via HE feedback, as they work with customers in 1-1 chats. People don't know to search for the categories because it's hidden until you start searching.

**Comment by lancewillett** [comment]
Never mind! Just found https://github.com/Automattic/wp-calypso/issues/22228 🎉

**Comment by mapk** [comment]
@lancewillett I've been working on that today here: #22229
