### ISSUE TITLE
Login: Change label of Email field

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#22289]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/log-in

#### What I expected
To be able to log in using my email address, as that's how the login field is labeled.

#### What happened instead
Though the field is labelled "Email", it accepts either an email address or username. This is confusing in itself, but becomes more confusing when we force a username login due to suspicious email login.

As described by a user who reached out about this via Twitter:

> Why does the label say Email Address if you are expecting a username that is not an email address?
    this is a bit confusing to the user. Could it be shown as a mandatory second step? Now the error message gives the impression that it was expecting the username in the first place.

#### Screenshot / Video
<img width="458" alt="log-in" src="https://user-images.githubusercontent.com/11873759/36034118-afc1e74e-0dbb-11e8-8904-5620d9f145da.png">

#### Context / Source

Reported by a user via Twitter.

I originally reported it in 8003-wpcom and was advised to move it here instead.

**Comment by stephanethomas** [comment]
Something that @folletto mentioned in the past is that we want to diminish the use of usernames in favor of emails as identifiers. I see how this error message could be confusing though. One option could be to update the label to mention `Email Address or Username` whenever this error is displayed.

**Comment by folletto** [comment]
> Though the field is labelled "Email", it accepts either an email address or username. This is confusing in itself

This is done on purpose. We should really accept just emails but we keep accepting usernames due to issues... like the one mentioned above.

> when we force a username login due to suspicious email login.

The process here should be revised. In other words: we need to keep pushing for eliminating usernames across, and if anything has to be changed, should be the process that requires a username to login. There are surely good reasons for that, but that's also an example of how deeply entangled are usernames in our systems. We need to disentangle them slowly.

It's ok as a stopgap to change to "Email Address or Username", or even better say "Username" ONLY in the instance when it's a suspicious email issue. Even better would be if we can update the process to verify suspicious emails of course. :)

**Comment by westi** [comment]
> It's ok as a stopgap to change to "Email Address or Username", or even better say "Username" ONLY in the instance when it's a suspicious email issue. Even better would be if we can update the process to verify suspicious emails of course. :)

Can we do this sooner rather than later as it is causing actual user confusion for people who are used to logging in with usernames.

Also, when we push someone to log in via username instead we do this for valid reasons to help increase the security of peoples accounts so it is unlikely something that is going to go away.

**Comment by folletto** [comment]
> Also, when we push someone to log in via username instead we do this for valid reasons to help increase the security of peoples accounts so it is unlikely something that is going to go away.

This is one of the things we'll have to review in the process I mentioned above. We need to find a different way to solve the problem behind our requirement of usernames there at some point.

> Can we do this sooner rather than later as it is causing actual user confusion for people who are used to logging in with usernames.

💯
