### ISSUE TITLE
Site disconnect: modify disconnection screen for sites with backups

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#22364]
As pointed out here hp9rlnk-7E if a user with backups disconnects their site from Calypso, they will lose access to their backups. In order to prevent that, I propose modifying the disconnect dialogue to include a button directing folks to the activity log and a happy chat button to get help.

![image](https://user-images.githubusercontent.com/1123119/36126186-acb01124-1014-11e8-81cc-1d1eff7fe586.png)

![image](https://user-images.githubusercontent.com/1123119/36126192-b288620e-1014-11e8-8950-b899c0e5da0d.png)

![image](https://user-images.githubusercontent.com/1123119/36126181-a672946c-1014-11e8-8a6e-130156693ffc.png)

The only image above modified is the last. It has an added paragraph at the top and the two buttons.

* The buttons should both be tracked.
* If Happiness gets overwhelmed, we should hide the button.

**Comment by keoshi** [comment]
I like it but would suggest adding that new bit on top only if the user explicitly selected a connection issue as the reason to disconnect.

Otherwise I'd keep the focus on the disconnect implications, which already mentions the backups and scanning, like this (apologies for the bad frankenmock):

![artboard](https://user-images.githubusercontent.com/390760/36144800-35ed401e-10a7-11e8-95ba-0908702e769e.png)

**Comment by MichaelArestad** [comment]
Nice! Mine's a frankenmock, too. I like it.

**Comment by benhuberman** [comment]
@clucasrowlands Could you grab this? Let me know if it clashes with anything else, in which case I can take a look myself over the next 24 hours.

**Comment by clucasrowlands** [comment]
A few copy suggestions for the last screenshot:

Remove unnecessary commas:

> Daily automated backups (unlimited storage) 
> Daily automated malware scanning

Fix styling of "GB":

> 13GB of high-speed video hosting

Change to sentence-case style:

> Read more about Jetpack benefits

"...to before the trouble started" is awkward. A few suggestions for smoother wording:

- Troubleshoot any connection issues by rewinding your site.
- Experiencing connection issues? Try to go back and rewind your site.
- Instead of disconnecting, try again. Troubleshoot by rewinding your site.
