### ISSUE TITLE
Simple Payments: better request-handling

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#22388]
The whole process of a purchase triggers different requests among WordPress.com, PayPal, and Jetpack site. We should improve it because, under specific circumstance, it gets somewhat fragile.

For instance, it's possible to execute an order rightly on PayPal, but the same order isn't updated on the Jetpack site, showing an error to the user from the frontend.

cc @iamtakashi

**Comment by iamtakashi** [comment]
Just to add one of the examples that happened because of this. A payer saw an error message saying "payment did not execute successfully" like the screenshot below, but the transaction actually went through 😱 

We don't know this time if the payer tried to pay again assuming it didn't go through, but it could've easily been a nasty experience with refunds and surprises for both the payee and the payer. Therefore, It'd be great if we can tackle this issue sooner than later.

![screen-shot-2018-02-09-at-1 35 24-pm](https://user-images.githubusercontent.com/908665/36161795-78b934cc-10dc-11e8-87f6-bb446abf25db.png)
