### ISSUE TITLE
Editor: Contact Form: add a date field with a pop up calendar date picker

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22405]
Steps to reproduce:

1. Go to https://wordpress.com/ > My Sites > Pages > Add > Contact Form.
1. Add a date field to the contact form.

<strong>Result:</strong> there isn't an option for adding a date field.

![screen shot 2018-02-13 at tue feb 13 1 32 11 pm](https://user-images.githubusercontent.com/1119271/36172497-4df9fdca-10c3-11e8-9ce9-5c32ca4b5fed.png)
<sup>Seen at https://wordpress.com/page/design5279.wordpress.com/7618 using Firefox 58.0.2 on macOS 10.13.3.</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by arunsathiya** [comment]
Reopening because this is still not available, but on a related on, the contact form block made by @Automattic/gutenpack has this feature. I would imagine that this issue can eventually be closed because Gutenberg blocks are taking precedence over Calypso-specific features (like this contact form), but I am leaving this open for now. 

<img width="854" alt="Screenshot 2019-03-31 at 17 25 13" src="https://user-images.githubusercontent.com/18581859/55288774-2f1e4680-53da-11e9-8a6b-c418b2eb5920.png">
