### ISSUE TITLE
Markdown only support?

### ISSUE THREAD

**Issue by corysimmons** [Automattic/wp-calypso#2242]
Is it possible to disable the GUI editor completely and just support markdown? If so, could someone point me in the right direction? Right now my team has editors copy/pasting Word files into the GUI and it always produces Word garbage `Hello <span style="font-weight: 400">world</span>`, etc.

**Comment by designsimply** [comment]
The Calypso Editor does not support Markdown yet (https://github.com/Automattic/wp-calypso/issues/529), so you would need to add support for Markdown as a first step. From there, you could propose a setting to disable the TinyMCE editor on a per-profile basis. These are pretty big tasks, are you asking how to contribute to Calypso to provide those things?

Regarding the pasted Word content, a possible workaround for your editors might be to ask them to use the "Paste as Text" option when copying content from other sources such as Word before adding formatting in the WordPress.com editor:

![screen shot 2016-01-19 at tue jan 19 2 52 48 pm](https://cloud.githubusercontent.com/assets/1119271/12430259/b9e4fa0e-bebc-11e5-945b-f0017a5ae995.png)

Using the WordPress Desktop app instead of Word to create/edit content directly might also be another good option for them: https://desktop.wordpress.com/

**Comment by corysimmons** [comment]
Ah, thanks!

I'll see if my team is responsive to markdown only. If they are I might contribute.
