### ISSUE TITLE
Editor: Contact Form: fix alignment of the edit icon for long questions

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22445]
Steps to reproduce:

1. Go to https://wordpress.com/ > My Sites > Pages > Add > (+) Add > Contact Form.
1. Click the "Add New field" button.
1. Add a long question for the Field Label.
1. Click the "Insert" button.
1. Click the form.
1. Click the edit icon.
1. Find the form field with the long question and check the alignment of the icons.

<strong>Result:</strong> if the field label falls to two lines, the edit icon alignment is off.

![screen shot 2018-02-14 at wed feb 14 9 52 20 am](https://user-images.githubusercontent.com/1119271/36216788-ffe41346-116c-11e8-9b48-9b00fe82c398.png)
<sup>Seen at https://wordpress.com/page/design5279.wordpress.com/11833 using Firefox 58.0.2 on macOS 10.13.3.</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by anotheredward** [comment]
Hi! I've created a PR to fix this issue, thanks :)

**Comment by andfinally** [comment]
This does seem to do the trick, and it's more concise than the flexbox solution, which would be like

```
.editor-contact-form-modal .foldable-card__action {
	display: flex;
}

.editor-contact-form-modal-field__edit-wrapper {
	display: flex;
	flex-direction: column;
	flex: 1;
}

.editor-contact-form-modal-field__edit-wrapper-button {
	flex: 1;
}
```

I've tested on macOS Chrome and Firefox, I'll try it on some other devices. On IE11 I can't see the edit buttons at all!

![ie11-buttons](https://user-images.githubusercontent.com/1647564/36567680-237c9a54-181f-11e8-9ad5-913f09b6c41b.png)

I'll try on a VM instead of Browserstack and maybe raise a separate issue about it.

**Comment by anotheredward** [comment]
Woah @andfinally , that's not good! Did that issue exist before my change?

**Comment by andfinally** [comment]
Sorry @anotheredward, false alarm - everything's fine when I check on a VM - I've updated my response above and I'll add details to your PR.
