### ISSUE TITLE
Login: Encourage unactivated users to use email login link

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22455]
#### Steps to reproduce
1. Starting at URL (logged out of Gravatar/WordPress.com): http://gravatar.com/
2. Select "Create your own Gravatar" to create a new WPCC account.
3. Complete the WordPress.com signup.
4. Log out of WordPress.com.
5. Visit https://wordpress.com/log-in and try to log in to your new account.

#### What I expected

I expected to have a direct route to activate my account, especially in a case where I didn't receive my WPCC activation email or that activation link has expired.

For example, if I select the "Email me a login link" option on the login page I'll get a new email from WordPress.com that will activate my account and log me in, with a single step.

#### What happened instead

I get this error message:

> This account hasn't been activated yet — check your email for a message from WordPress.com and click the activation link. You'll be able to log in after that.

This doesn't help if I can't find/use the activation email from WordPress.com, and it ignores the more direct route of using the "Email me a login link" option, which would also activate my account and log me in.

#### Browser / OS version

macOS 10.13.3 / Chrome 64

#### Screenshot / Video

![screenshot 2018-02-14 18 12 33](https://user-images.githubusercontent.com/8658164/36221421-f6877114-11b5-11e8-827a-fd8a35ba159c.png)

#### Context / Source
#flow-testing

**Comment by rachelmcr** [comment]
One possible tweak to the error message, which would directly send users to have a login link emailed to them:

> This account hasn't been activated yet. [Request a login link](https://wordpress.com/log-in/link) to activate your account and log in to WordPress.com in one step.

**Comment by rachelmcr** [comment]
Also, a note on impact — this idea came out of testing the user flow for Gravatar users who (for whatever reason) are having trouble activating their accounts. There's a related issue with a number of reports from support: https://href.li/?https://github.com/Automattic/jpop-issues/issues/941

**Comment by stephanethomas** [comment]
I had a look to this issue yesterday, and since I won't be able to tackle it because of other priorities I'm going to leave a few thoughts here for whoever is going to pick that up.

@rachelmcr suggested the following change:

> This account hasn't been activated yet. [Request a login link](https://wordpress.com/log-in/link) to activate your account and log in to WordPress.com instantly.

I had a look at the current error message server-side (it has `account_unactivated` as id). For information, we overwrite the original message on the server (to remove legacy markup and link) with this one. However, I'm not sure we should make the change there mostly because the suggested message now as a link. I'm indeed worried that https://wordpress.com/log-in/link might not make sense depending on the environment (think `wpcalypso` for example), or the flow (think Jetpack).

However, we could very well display a custom message client-side by intercepting the error code in the [`ErrorNotice` component](https://github.com/Automattic/wp-calypso/blob/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/blocks/login/error-notice.jsx#L77). One benefit is that we would know the username (or email address) that was just entered by the user, and as such be able to send the magic link as soon as the user clicks the link in the message (i.e. without requiring them to enter their identifier again).

Unfortunately, the username (or email address) is not stored in Redux, but in the form component [internal state](https://github.com/Automattic/wp-calypso/blob/b46c289a366733a389ba04b4b43e7258cc944f1a/client/blocks/login/login-form.jsx#L79). Right now it's not possible to use this data from the error notice itself since the latter is too far up [in the components tree](https://github.com/Automattic/wp-calypso/blob/41f4f8b49119b9ad0c507dfcc6ffa283e9082ba3/client/blocks/login/index.jsx#L283).

So right now I see two options: either we move this field value to Redux (and we make sure we don't leave this [Personally Identifiable Information](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjGyt738t7ZAhVGECwKHUQrDEQQFggrMAA&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPersonally_identifiable_information&usg=AOvVaw1y7BckOXxHwG04Fc1S0uex) forever in the global state tree), or we're fine with just redirecting users to the [`Magic Login` page](https://wordpress.com/log-in/link) and forcing them to enter their identifier again.

**Comment by beaulebens** [comment]
@johnHackworth Assigning this to you/your team for consideration as part of iterating on the connection/NUX.

**Comment by cathymcbride** [comment]
No customer reports or activity for a while. Closing.
