### ISSUE TITLE
Activity Log: disable Happychat buttons when a chat is already active

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#22544]
Props to @rcoll for noticing this behavior: when a Happychat is open, clicking another Happychat button will do nothing, so we should disable then when there's an active chat.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
Note - Happychat has also been deprecated internally in favor of ZD.
