### ISSUE TITLE
eslint rule: no-nodejs-libs

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#22542]
Webpack allows you to use most `nodejs` libs even in client code.  That works because they maintain a [collection of polyfills](https://github.com/webpack/node-libs-browser).  Some of those polyfills are tiny and fairly acceptable to use, like `qs`, but many of them are huge and we really shouldn't be using them in the browser if we could avoid it.

For example, @jsnajdr recently removed a single usage of `stream` which then saved over 100kBgz throughout Calypso: https://github.com/Automattic/wp-calypso/pull/22539.

While it is good to remove these already in Calypso, making an eslint rule would help us make sure we don't continue to add them in the future.

**Comment by jsnajdr** [comment]
Webpack has a `node` config option that lets you specify which Node polyfills it should bundle and which are disabled. Calypso [uses this option](https://github.com/Automattic/wp-calypso/blob/master/webpack.config.js#L176-L185) and #22539 adds a `stream: false` line there, so that another attempt to import `stream` will fail.

Unfortunately, there are a few polyfills we need, and the option doesn't support a configuration to "enable a few specific polyfills and forbid everything else". Polyfills that are not explicitly set to `false` are allowed by default.

I wish we could get to a state where we can just specify `node: false` and forbid all Node.js polyfills without exception.

**Comment by samouri** [comment]
> and the option doesn't support a configuration to "enable a few specific polyfills and forbid everything else". Polyfills that are not explicitly set to false are allowed by default.

It sounds like what we should do is set `node: false` and then manually polyfill the specific libs we want using [NormalModuleReplacement](https://webpack.js.org/plugins/normal-module-replacement-plugin/). That should get us to an ideal state. For example, to polyfill `querystring` we would add something like this to the webpack config:

```
new webpack.NormalModuleReplacementPlugin( 'querystring', 'querystring-es3' );
```

**Comment by samouri** [comment]
I'm looking into it here: https://github.com/Automattic/wp-calypso/pull/22630
