### ISSUE TITLE
Customizer: add Pexels and Google Images as options to the logo selector

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22552]
Steps to reproduce:

1. Go to https://wordpress.com/ > My Sites > Customize > Site Identity.
1. Click the "Select logo" button.

<strong>Result:</strong> there are very limited option here, especially for new sites, and it's one of the first things many people would probably like to customize. Would it be possible to add Pexels and Google images as options to the logo selector?

![screen shot 2018-02-16 at fri feb 16 1 27 25 pm](https://user-images.githubusercontent.com/1119271/36327966-8d96dc8a-131d-11e8-8909-427d52f365aa.png)
<sup>Seen at https://wordpress.com/customize/whatsupbuttercup892968563.wordpress.com using Firefox 58.0.2 on macOS 10.13.3.</sup>

Dogfooding feedback:

<blockquote>First thing I wanted to do was change the image at the top, which seems to be my “logo”. I don’t have any other options though, and as a new customer wouldn’t even know where to start with finding/creating something to put there instead of what I was given. I probably wouldn’t know that I could save something from somewhere else and upload it, and wouldn’t know where to start (and we don’t give any tools) to create something of my own. Default media view is “upload”, but would probably be much friendlier if it was some sort of clipart/library/stock images view (with option to upload). Since this is the “wp-admin” Media Library, there’s no Pexels or Google Images that we’ve added to Calypso recently either. Sad Christmas.
</blockquote>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by arunsathiya** [comment]
Reopening as this is still an issue. The media modal when starting on the Customizer is that of the wp-admin.

While choosing `Site icon` on https://wordpress.com/settings/ though, it shows the Calypso media modal. 

![Screenshot 2019-03-31 at 16 22 09](https://user-images.githubusercontent.com/18581859/55288210-be732c00-53d1-11e9-8580-83a21d9a7cfe.png)

In my understanding, the simplest fix would be to show Calypso media modal when setting a logo on the Customizer, instead of showing the wp-admin media modal.
