### ISSUE TITLE
Jetpack Plans: Refine wording in the plans grid.

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22597]
For any Jetpack site, click the "Plan" menu item, then "Plans" at the top and see this:

![screen shot 2018-02-19 at 12 08 56 pm](https://user-images.githubusercontent.com/108942/36393798-5fe54788-156e-11e8-8d03-0cbb4819f1b2.png)

- [ ] Remove the "Unlimited Storage Space" entry under Personal, which is supposed to refer to our image CDN, but has carried over some details from somewhere else.
- [ ] In the tooltip for "All free features" (also under Personal), add a link to https://jetpack.com/features/comparison/ (opening in a new window)

**Comment by benhuberman** [comment]
@beaulebens since your proposed changes don't add or change existing copy (as far as I can see), could you say a bit more about what copy you'd like to see reviewed here? Thanks!

**Comment by beaulebens** [comment]
Oops, you're right @benhuberman, removing that label.

**Comment by jeffgolenski** [comment]
Just cc'ing @joanrho since you're rocking out plans stuff.

**Comment by joanrho** [comment]
Thanks for the ping, @jeffgolenski! This should be resolved if we implement the plans grid I proposed in [issue 8941](https://github.com/Automattic/jetpack/issues/8941).

**Comment by AnnaMag** [comment]
@beaulebens is the "All Premium features" feature left out on purpose in this change?

How about we make the bottom features of all plans linkable to the  `https://jetpack.com/features/comparison/ ` instead of including it in the tooltip? This will also be a step towards new design, where tooltips are replaced by links. 

What do you think?

**Comment by joanrho** [comment]
I agree with Anna's comment above. We should have "All Free features", "All Personal features", and "All Premium features" linked out to `https://jetpack.com/features/comparison` instead of nesting that single link inside the tooltip. If we had more text to include in the tooltip alongside the link, then it'd make sense to keep in in there.

**Comment by AnnaMag** [comment]
Implemented the proposed modification in https://github.com/Automattic/wp-calypso/pull/23103.

Input and reviews highly appreciated 😄
