### ISSUE TITLE
Editor: Preview is broken when editing a published custom post type

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22645]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/types/jetpack-portfolio
2. Select a site with Portfolios enabled (or enable them in the Writing settings on your site).
3. If you don't have any portfolio projects yet, create and publish one.
4. In the list of portfolio projects, select one to open it in the editor.
5. Before making any changes, select "Preview" to preview the project.
6. Make any edit to the project.
7. Select "Preview" again to try to preview your changes.

#### What I expected

I expected the preview to work, so I could preview my changes before publishing them.

#### What happened instead

I received a 404 error. The preview only worked after I selected "Update" to publish my changes, which defeats the purpose of the preview.

I observed the same issue on another custom post type (Testimonials) and confirmed that the preview works as expected for regular posts and pages, so this seems to be limited to custom post types.

#### Browser / OS version

macOS 10.13.3 / Chrome 64

#### Screenshot / Video

Preview with all changes saved/published:

![screenshot 2018-02-21 11 01 41](https://user-images.githubusercontent.com/8658164/36476792-ca3a4bcc-16f6-11e8-8e36-bb24a6d596fc.png)

Preview after making an edit to the project:

![screenshot 2018-02-21 11 02 25](https://user-images.githubusercontent.com/8658164/36476806-d4249156-16f6-11e8-8fcd-47610ea28483.png)

#### Context / Source
#manual-testing

**Comment by jblz** [comment]
I'm able to reproduce this on a *.wordpress.com site -- my Jetpack sites don't seem to do it...

If I make a change to the post before hitting preview, I'm seeing a 404 in the preview modal. I inspected the rendered iframes:

If I preview before making a change it works (no 404). The href of the iframe is something like:

https://example.wordpress.com/portfolio/a-project/?frame-nonce=1234&preview=true&iframe=true&revision=1&calypso_token=1234

Once I make a change and try to preview, the href changes to something like:

https://example.wordpress.com/2017/05/04/a-project/?preview=true&preview_id=307&preview_nonce=1234&frame-nonce=1234&iframe=true&revision=1&calypso_token=1234

## Notes and observations:

* `1234` is (obviously) not the real value anywhere it's used in the above.
* example.wordpress.com is...just an example
* The 404'ing URL includes the date in the permalink structure while the working one includes the CPT slug
* The 404'ing URL includes a `preview_id` w/ a value of the post ID of the custom post -- the working one does not include it
* The 404'ing URL includes a `preview_nonce` -- the working one does not include it

Ultimately, If I change the permalink to include the CPT slug instead of the date, it no longer 404s on my test site.

---

It's possible something unexpected is happening w/ `getPreviewUrl` in either:
* `PostEditor` [here](https://github.com/Automattic/wp-calypso/blob/e6442d76a8723ff8a1ab6b37550dbeb5ea151551/client/post-editor/post-editor.jsx#L735), or...
* [In the `PostEditStore`](https://github.com/Automattic/wp-calypso/blob/0584031e15b74eb0bb9a33a6b6a977f87365a216/client/lib/posts/post-edit-store.js)

**Comment by frontdevde** [comment]
### Observation

For standard posts the `post.URL` and the base of `post.preview_URL` always match.

With portfolios they differ, so for example the `post.URL` looks like this  
`...portfolio/portfolio-test/...` while the `post.preview_URL` looks like this 
`...2018/03/22/portfolio-test/...`.

When visiting the URL
https://example.wordpress.com/2018/03/22/portfolio-test/
in the Browser, it resolves to
https://example.wordpress.com/portfolio/portfolio-test/

Swapping the `2018/03/22/portfolio-test/` section in the `post.preview_URL` for `portfolio/portfolio-test/` results in a working preview in the iframe.

### Client-side fix

We could address the symptoms on the client side. In [wp-calypso/client/lib/posts/utils.js](https://github.com/Automattic/wp-calypso/blob/e6442d76a8723ff8a1ab6b37550dbeb5ea151551/client/lib/posts/utils.js#L35) we could swap the base part of the preview_URL with the post.URL:

```js
parsedPostUrl = url.parse( post.URL, true );
parsedPostPreview = url.parse( post.preview_URL, true );
parsedPostUrl.search = parsedPostPreview.search;
previewUrl = url.format( parsedPostUrl );
```

See the corresponding PR here https://github.com/Automattic/wp-calypso/pull/23577

### Server-side fix

While the above fix makes the preview work, it only fixes the symptoms, not the cause. 
We'd probably want to solve this on the server side.

The line in question seem to be
`$preview_url = add_query_arg( 'preview', 'true', get_permalink( $post->ID ) );`

Is there a way to return the URL in form of https://example.wordpress.com/portfolio/portfolio-test/ instead of https://example.wordpress.com/2018/03/22/portfolio-test/?

**Comment by jblz** [comment]
This should be resolved. We were not registering CPTs (& their redirects) on the "autosave" endpoint, but now are.

See D11306-code for more info.
