### ISSUE TITLE
Checkout: Improve Expiry and CVV field clarity

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#22659]
On the payment checkout form:

<img width="812" alt="screen shot 2018-02-21 at 10 22 07 am" src="https://user-images.githubusercontent.com/1464705/36497787-294c81a8-16f1-11e8-8701-996ccd627a59.png">

The only labels we have for expiry and CVV are "MM/YY", and "CVV". These may seem obvious to you, but it does make me think. Many credit cards have "Valid From" and "Valid To" dates on them. I also expect many people have no idea what CVV means.

What if we change the label for expiry to "Expiry MM/YY". Add then add a simple tooltip component to the end of the CVV field that explains that CVV is the last three digits on the back of your card?

<img width="893" alt="screen shot 2018-02-21 at 10 31 04 am" src="https://user-images.githubusercontent.com/1464705/36498169-5e1d9cc2-16f2-11e8-81d9-c0e878abc8fb.png">

**Comment by gwwar** [comment]
To summarize a Slack conversation:

It's a little tricky/hacky here to add an interactive element here to the field. The credit card field shows an icon though CSS styling, which is fine since the user doesn't directly interact with it.

A few options here:
- Create a new field component that relatively positions an icon (w/popover) 
- Style the field like the how the credit card field does (a background image), and add a popover for the field positioned to the right
- Maybe use the same background image trick, and then add a normal popover that fires at the right of the field when it has focus.

Any thoughts?

**Comment by drw158** [comment]
Maybe an easier and simpler way is to add labels for each form.

**Comment by scruffian** [comment]
Should we A/B test this kind of change?

**Comment by gwwar** [comment]
> Maybe an easier and simpler way is to add labels for each input.

@drw158 Do you mean a more traditional label above the field? I believe that would likely be more a11y friendly as well if we didn't need to merge components on top of a field.

Would you or someone else in design be able to create a mock? If folks agree on that approach I'll update the issue summary. 

@scruffian for a larger change for of what @drw158 proposed in the payments flow we'd at least need to monitor stats (and potentially revert if it has negative impact) and contact nux before merging.

**Comment by scruffian** [comment]
> we'd at least need to monitor stats (and potentially revert if it has negative impact) and contact nux before merging.

Good plan 👍 

The problem I have had with monitoring stats in the past is that they can fluctuate based on other factors, so it's always possible to say what impact your change had.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment]
This was improved by Marketing in an AB test of legacy checkout, and the changes are being carried over to the new Checkout design.
