### ISSUE TITLE
Domains: Change address terminology for other countries

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#22658]
In the NUX flow, when on the payment and domain details form where I'm asked for my address, there is a box for "State".

If I select Canada as my country, this should change to "Province". We do not have states in Canada. I think not changing this reflects poorly on us, and makes it feel like we don't care about the world outside of the USA.

I'm sure this is true for a lot of other countries, we should tackle the most highly trafficked ones first.

<img width="770" alt="screen shot 2018-02-21 at 10 17 01 am" src="https://user-images.githubusercontent.com/1464705/36497569-864fb74a-16f0-11e8-8bec-9745b3206b64.png">

**Comment by apeatling** [comment]
Ironically the reverse is true for "Postal Code". This should be "ZIP code" when United States is selected.

**Comment by codebykat** [comment]
Postal code isn't fine for the US? That doesn't read as weird to me; they feel interchangeable and plenty of signup / order forms use that terminology.

**Comment by yoavf** [comment]
cc @ramonjd who worked on this in #19088

**Comment by ramonjd** [comment]
Thanks for raising this. I think we're in a good position to cater for variations here, that is, for province/state and postcode/zip. I'll take a closer look 👍

**Comment by ramonjd** [comment]
Ah, I just saw the error messages. These are coming from the backend.

_Question_: Can we live with the label changes for now? #22839

Otherwise I'll put the PR on hold until I investigate the errors API

<img width="705" alt="screen shot 2018-02-27 at 3 16 21 pm" src="https://user-images.githubusercontent.com/6458278/36710364-8f3d2d20-1bd1-11e8-8326-c232188b3978.png">
<img width="697" alt="screen shot 2018-02-27 at 3 06 35 pm" src="https://user-images.githubusercontent.com/6458278/36710367-91f1a906-1bd1-11e8-864d-760aed48e74e.png">

**Comment by ramonjd** [comment]
Closing this as the API has been updated
