### ISSUE TITLE
Jetpack connect: Cancelling a cart purchase during onboarding autoselects free plan

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#22708]
Ok, follow me in this exhilarating trip of discovery: 

1. Let's say that you are a user who just installed Jetpack and are connecting it:

![image](https://user-images.githubusercontent.com/1554855/36545484-4243def6-17e9-11e8-92be-d4ff19c49a6b.png)

2. After connecting your site properly, you are redirected to our onboarding flow's plans page

![image](https://user-images.githubusercontent.com/1554855/36545514-5f176a3e-17e9-11e8-9c5e-e70407452a56.png)

3. Let's say that the premium plan pike your curiosity and you click on the blue button. Then you are redirected to the cart, with a premium plan ready to be paid:

![image](https://user-images.githubusercontent.com/1554855/36545572-7de020fa-17e9-11e8-9ba1-c80804dece0e.png)

But oh! it's too expensive and you don't really want to pay that much! you rather prefer to start with the free plan and then see if you use it enough for paying for an upgrade...

And here it comes the first problem: There's not an obvious way out of the checkout screen. If you go back in the browser, you are taken back to your wp-admin without any explanation:

![image](https://user-images.githubusercontent.com/1554855/36545682-b8017c7a-17e9-11e8-8c53-7443ee68f411.png)

What happened there? I know, and you know, that the user has been assigned a free plan, but does the user know what just have happened?

Let's rewind to the checkout page again. The only way out of that page without paying is emptying the cart (clicking on the red X in the top left section). What happens when you click it? this:

![image](https://user-images.githubusercontent.com/1554855/36545783-02074dea-17ea-11e8-90f4-a8a2ecf1fc06.png)

You are redirected not to the JPC/NUX plans page, but to the common plans page in /plans. A page where you don't have any option to pick a free plan, nor to return to your wp-admin (if you started the onboarding flow there).  Again, I know that is not a big deal because at that point the site already has a free plan assigned, but for the user can be very confusing (Do the site has a plan at all? has Jetpack been configured correctly? Do I need to go through all this again?)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
