### ISSUE TITLE
Plans: Incorrect tooltip copy

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22701]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/{site-url}
2. Click popover for "Unlimited storage space" under personal plan
3. Click popover for "Monetize your site" under premium plan

#### What I expected
Correct description.

#### What happened instead
1. Storage space should be talking about backups
2. Monetize should also be talking about PayPal payments

#### Screenshot / Video

<img width="642" alt="richard_s_sandbox_ _wordpress_com" src="https://user-images.githubusercontent.com/2287740/36538010-d4ba03e8-17c9-11e8-9da9-4c2ce193efea.png">

<img width="570" alt="richard_s_sandbox_ _wordpress_com" src="https://user-images.githubusercontent.com/2287740/36538021-e02fbd80-17c9-11e8-976d-1636138a6fb0.png">

**Comment by benhuberman** [comment]
@richardmuscat, @beaulebens -- How about...

**Unlimited Storage Space**
> All the space you'll ever need for your media uploads and site backups.

**Monetize Your Site**
> From ad revenue to easy-to-add PayPal payment buttons, your website is always open for business.
or:
> Put your site to work and earn through ad revenue, easy-to-add PayPal buttons, and more. 

Happy to suggest further tweaks, depending on your feedback.

**Comment by beaulebens** [comment]
For the Unlimited Storage Space, I think we need to be more explicit about it being specifically for backups, otherwise there's potential confusion that we're talking about "making their media library unlimited size". So maybe something like

**Unlimited Backup Space**
> Back up all your media uploads and site data, with no restrictions on size.

**Comment by benhuberman** [comment]
"Backup Space" sounds somewhat awkward to me. And I also wonder if it's not confusing to have two listed items naming backups (this one and "Daily Off-site Backups"). I wonder, then, if it wouldn't make more sense to highlight the unlimited-ness of backup storage space in the "Daily Off-Site Backups" item -- what's the current copy there? (Alternatively: is there a sample JP site I could be added to to see the copy in action?)

**Comment by rickybanister** [comment]
@benhuberman I've invited you to one of my test sites. You can accept that invite and visit the plans page to take a look at the other feature copy.

**Comment by benhuberman** [comment]
Perfect, thanks @rickybanister !

**Comment by benhuberman** [comment]
Having seen the other feature's copy, how about going with the following:

**Daily Off-site Backups**
> Automatic daily backups of your entire site, with unlimited, WordPress-optimized secure storage.

**Unlimited Storage Space**
> All the space you'll ever need for your media uploads, from images and audio files to documents.

I like that each one is more focused this way and doesn't try to squeeze too much into a single line of text.

**Comment by beaulebens** [comment]
I like that you've added "unlimited" to the off-site backups one, but the "Unlimited Storage Space" one is very misleading still.

This space that is unlimited is _not_ for their uploads or anything _directly_. It _only_ applies to the backup of their site.

**Comment by benhuberman** [comment]
> This space that is unlimited is not for their uploads or anything directly. It only applies to the backup of their site.

Is there anything stopping us from just nixing this item, then? If the unlimited aspect of backup storage is easily foldable into the previous item, and the media part is actually factually incorrect, it really serves no purpose here.

Since I was on the page already, I figured I might as well take a quick look at the rest of the copy, in case you were open to further tweaks. Nothing _major_ to report back, mostly just a fistful of nits to pick:

**Personal**
Comma missing after "site":
> Security essentials for your WordPress **site,** including automated backups and priority support.

Comma missing after "defense":
> State-of-the-art spam **defense,** powered by Akismet.

Hyphen missing in "high-quality":
> **High-quality** support to help you get your website up and running and working how you want it.

With this one, I also think there's an opportunity to trim/tighten a little, e.g.:
> Hands-on support to help you set up your site exactly how you want it.

**Premium**
> Automated backups and malware scanning,

I'd remove "backups and" -- this is mentioned as a Personal feature, so I found it odd to see it highlighted here.

Slight trim suggested here:
> Comprehensive, automated scanning for ~~any~~ security vulnerabilities ~~or~~ **and** threats on your site.

This stood out to me:
> Monetize Your Site

The format (second-person verb) is very different compared to the rest. It could feel a little less jarring as something like "Monetization Options" or "Site Monetization" (the rest of this feature's copy was addressed in a comment above.)

> Unlimited Video Hosting

This instance of "Unlimited" was the only one not in **bold** on this page. Also, the related copy reads somewhat long -- I think there's room to trim a bit, e.g.:
> Easy video uploads, and a fast, unbranded, customizable player, enhanced with rich stats and unlimited storage space.

I was wondering if this isn't selling the Concierge session a little short:
> A complimentary one-on-one **education** session

How about... "A complimentary, one-on-one orientation session"? Or "setup session"? Basically something that implies more of a hands-on, dialogue-based experience and less of a "somebody talking at me" experience.

**Professional**
> WordPress sites from start to finish

This read a little odd to me -- aren't all WP sites WP from start to finish? I'd go with something like "The most powerful WordPress sites: [rest of copy]" or "The full power of WordPress, unlocked: [rest of copy]"

> business class security

This needs a hyphen (business-class), but personally I'd opt for something like "business-optimized security" or "the most advanced security features," or something else along those lines that's slightly more descriptive than "business-class".

> Real-time Off-site Backups

If you wanted to, the copy here could be tweaked to match the "unlimited storage" language from Personal.

> Enhanced site-wide search

This is the only feature that's written in sentence case; for consistency, s/b "Enhanced Site-wide Search."

As for this feature's copy, a suggested tweak:
> Fast, ~~high-quality~~ relevant search results with custom filtering, powered by Elasticsearch.

**Comment by joanrho** [comment]
@beaulebens @richardmuscat If we implement this design p6TEKc-1Qa#comment-4304, which also directly relates to coming changes in [issue 8941](https://github.com/Automattic/jetpack/issues/8941), we'll only be using links to feature pages and would not need to make the above copy edits. Thoughts?

**Comment by beaulebens** [comment]
Sounds like those changes are going to come through some staged tests along the way, so I think we should just go ahead and make these changes to start with, since they're literally just text so should be quick and easy to make.

**Comment by griersongithub** [comment]
We should remove the words unlimited completely for legal reasons. I would prefer we use Unmetered or something that infers there is some sort of limit but we don't really pay attention to it unless it becomes an issue.

**Comment by ebinnion** [comment]
I've created #23087, which I believe addresses the feedback here.

**Comment by joanrho** [comment]
Sorry for not updating this thread—I already created #23059 yesterday. @ebinnion, I'll make sure our changes align before closing yours.
