### ISSUE TITLE
Jetpack auto-config of plan purchase didn't work, but said it did

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22757]
Here's a rough attempt to capture what happened:

- created a brand new wordpress site (on my own host, WP 4.9.4)
- installed and activated jetpack from the plugin directory (5.8)
- went through the connection flow
- during connection flow, went back and forth a few times selecting a plan, getting to checkout, then using browser back button to go back into the connection flow and change options (don't know if it's relevant, but i'm including just in case. this part of the process is really janky, and seems quite broken)
- eventually ended up purchasing a monthly, personal plan, using WP.com credits
- on the thank you page, everything processed and seemed to work, including ending with checkmarks against every item, indicating that everything was fine.
- when i clicked "Back to your site" on the thank you page, I landed back in my wp-admin, and saw the "welcome dialog" for the personal plan
- when i closed the welcome dialog, i noticed a VaultPress banner saying that i needed to enter a registration key.

It turns out at this point that VaultPress had been correctly installed and activated, but had **not been configured with a registration key** properly. The errors from VP are very persistent and not very helpful in this context (especially since I don't really have much/any context for VP at this point).

The site appears to have the plan "correctly" set up -- it appears in Calypso's Manage Purchases section etc, but I also **never received a receipt**. My registration keys are available via Calypso (but I'd never know that as a new user).

**Comment by beaulebens** [comment]
Here are some of the errors I saw within Jetpack after things were not configured properly:

![screen shot 2018-02-22 at 4 47 30 pm](https://user-images.githubusercontent.com/108942/36602563-91faeeda-1875-11e8-9c87-830d04a6ce91.png)
![screen shot 2018-02-22 at 4 49 06 pm](https://user-images.githubusercontent.com/108942/36602564-9215a572-1875-11e8-879c-4dfc977d99d6.png)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
