### ISSUE TITLE
Editor: Google Photos: list/show albums

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22771]
Steps to reproduce:

1. Go to My Sites > Blog Posts > Add.
1. In the Editor toolbar, click Add > Media from Google.
1. Try finding an image in an album.

<strong>Result:</strong> it's currently not possible to see albums when adding Google Photos when adding media from Google.

![screen shot 2018-02-23 at fri feb 23 12 14 47 pm](https://user-images.githubusercontent.com/1119271/36612249-4dc7bcac-1893-11e8-85b2-b3e2da50bcb1.png)
<sup>Seen at https://wordpress.com/post/cute.wordpress.com (production) Chrome 64.0.3282.167 on macOS 10.13.3.</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by jakejones1984** [comment]
@designsimply Interested to get a better understanding of your expectations here. 

Is the desired UI a list of Albums with the ability to click into a given album and then see all photos within that album?

Recommend also including the ability to toggle in/out of Album mode, because some users may just wish to show all photos and cycle through them especially if they don't have any albums.

Any other feedback here would be welcome.

**Comment by drw158** [comment]
I simple UI to improve this would be to add a select dropdown with all albums on the account. It would be basically a filter to change the photos shown in the grid. e.g.

- All Photos
- Trip to Spain
- Baby photos

**Comment by jakejones1984** [comment]
@designsimply A implementation of this is nearly complete at

https://github.com/Automattic/wp-calypso/pull/25763#issuecomment-403249565

**Comment by eduardozulian** [comment]
This was recently requested in 15522349-hc

cc @getdave, in case you're still considering it :)
