### ISSUE TITLE
Editor: when scheduling a post, the "Publish Immediately" link is confusing

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#22816]
#### Steps to reproduce
1. Starting at URL: /post/ — editor, intending to write a new post
2. In the sidebar, choose a future date. Keep an eye on the "Publish..." blue button.
3. The button changes to "Schedule..." and a new link is added to the UI with the title "Publish Immediately"
4. This new link can be confused for the primary action — and it would be nice to improve it.

Could we make it clear it's a "cancel" operation? "Change your mind? Publish immediately instead" or something, or something like that.

#### What I expected
Not to be confused by the "Publish Immediately" link which is closer in distance to my working space than the big blue "Schedule" button. (I'm testing on desktop in a wide layout.)

Either match the "Schedule post" action — or make it more visible as the option to cancel the current operation.

#### What happened instead
The link presents a confusing path.

#### Browser / OS version
Safari 11.0.3 on OS X 10.13.3.

#### Screenshot / Video

Existing:
<img width="536" alt="screen shot 2018-02-26 at 11 25 35" src="https://user-images.githubusercontent.com/66797/36687770-ca245052-1ae7-11e8-9087-c048ca9b481d.png">

One idea for improvement could be "Cancel and publish now..."

<img width="562" alt="screen shot 2018-02-26 at 11 26 52" src="https://user-images.githubusercontent.com/66797/36687877-02c39efe-1ae8-11e8-90fa-d1e8f8acb15b.png">
 
#### Context / Source
This #journey #anecdote came from @johnmaeda via #reallife #dogfooding as a #painpoint. 

> Scheduling a post is really confusing but we can make it easier. When you select a date after the current day, the upper right corner button switches from Publish to Schedule … — but the nearest text button (the only one you’ll only notice because the corner blue button switch is not obvious) doesn’t change.

> The text “Publish Immediately” should say instead “Schedule Post” like the button changes in the upper right corner. The customer is more likely to hit “Publish Immediately” thinking it will schedule the post. I get why “Publish immediately” gives optionality, but it also increases the error possibility for someone who is intending to schedule a post.

**Comment by lancewillett** [comment]
CC @shaunandrews and @Automattic/tanooki for triage.

There a few Schedule Posts issues now that we could maybe group into a tiny iteration: https://github.com/Automattic/wp-calypso/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aeditor+schedule

**Comment by shaunandrews** [comment]
I can dig it. Translation may be a little long.

**Comment by mattsherman** [comment]
My concern is that, just as the "Publish Immediately" wording can confuse customers, that "Cancel and publish now" may be equally confusing. What about something like "Cancel Schedule" or "Remove Schedule", maybe even below the calendar, so that there is less attention drawn to it? Admittedly, that still seems kind of confusing as well.

**Comment by jancavan** [comment]
I think the UI is a bit confusing in general. I submitted this bug: https://github.com/Automattic/wp-calypso/issues/19415 a while ago and I think there's been changes since, but Initially, I thought the "Publish immediately" button was the button to click to publish my post.

**Comment by mattsherman** [comment]
Maybe just a "Cancel" button below the calendar would be better.

Or, above the calendar, two radio buttons... "Publish Immediately", and "Schedule", to make it more clear that "Publish Immediately" is a setting, not an action?

**Comment by johnmaeda** [comment]
The thing to remember is that the blue button in the upper right corner -- that changes from "Publish" to "Schedule" when you pick a date after the current date -- changes undiscernably so you don't know something has happened. Your eyes are focused on the calendar days themselves. And so when you see the text sitting right above the calendar, it's logical that you will click that text in order to schedule the publishing action. 

So @mattsherman's point of making it say the text above the calendar switch to "Schedule" is a good design idea. The customer's eyes (if they can see) will quickly register that state change. And that way there's redundance that lines up with the button above the calendar and in the blue button in the corner. The redundancy enables them to do what they originally wanted to do -- which is schedule a publication.

**Comment by shaunandrews** [comment]
> two radio buttons... "Publish Immediately", and "Schedule", to make it more clear that "Publish Immediately" is a setting, not an action?

Interesting. Here's what that could look like:

<img width="650" alt="screen shot 2018-02-26 at 3 40 30 pm" src="https://user-images.githubusercontent.com/191598/36694214-aa2235ac-1b0b-11e8-80bb-f84f0dd30414.png">

**Comment by jancavan** [comment]
Just to elaborate - I think at first it wasn't obvious to me that clicking "Publish..." doesn't actually publish the post just yet; that you will be taken to the next screen for additional settings. The ellipsis is supposed to indicate this, but it isn't obvious.

@shaunandrews Should the green "Publish!" button be disabled if the "Publish later" option is active? Or change to "Schedule" like currently?

**Comment by shaunandrews** [comment]
> Should the green "Publish!" button be disabled if the "Publish later" option is active? Or change to "Schedule" like currently?

Yup, I missed that in my quick mockup. Here's an update:

<img width="1013" alt="screen shot 2018-02-26 at 3 46 32 pm" src="https://user-images.githubusercontent.com/191598/36694396-4c4b8aa4-1b0c-11e8-95f9-e658036ffb30.png">

--

Here's a quick look at what wp-admin does now:

<img width="225" alt="screen shot 2018-02-26 at 3 48 10 pm" src="https://user-images.githubusercontent.com/191598/36694485-8bf88d96-1b0c-11e8-8474-a713ad1da449.png">

Clicking the edit link opens this:

<img width="275" alt="screen shot 2018-02-26 at 3 48 14 pm" src="https://user-images.githubusercontent.com/191598/36694497-93e63242-1b0c-11e8-99aa-da1f82931ffb.png">

To "undo" the scheduling in wp-admin, you click to edit the date/time and then click cancel.

--

Gutenberg also has its own variation on this, but I can't find a way to "undo" the scheduling.

<img width="374" alt="screen shot 2018-02-26 at 3 50 56 pm" src="https://user-images.githubusercontent.com/191598/36694606-dc25ea48-1b0c-11e8-88da-2e8a50166630.png">

**Comment by nylen** [comment]
> <img width="1013" alt="screen shot 2018-02-26 at 3 46 32 pm" src="https://user-images.githubusercontent.com/191598/36694396-4c4b8aa4-1b0c-11e8-95f9-e658036ffb30.png">

The middle state in this mockup is <em>indeterminate</em> - the user has selected that they want to schedule the post for a different date, but they haven't selected the date yet.

The current UI is not ideal, but it has the advantage that there are no indeterminate states.  I don't think a pair of radio buttons is the correct solution here, because clicking the "Publish later" radio button by itself is not sufficient to put the post into a scheduled state.

Let's start with a super simple change to the "Publish Immediately" text above the calendar, along these lines:

> Could we make it clear it's a "cancel" operation? "Change your mind? Publish immediately instead" or something, or something like that.

Let's try "Clear scheduled date" -- I think this is a good blend of conciseness and clarity.  See https://github.com/Automattic/wp-calypso/pull/23943, review welcome.

**Comment by jancavan** [comment]
> The middle state in this mockup is indeterminate - the user has selected that they want to schedule the post for a different date, but they haven't selected the date yet.

What about disabling the Schedule button until they have picked a date?

**Comment by nylen** [comment]
> What about disabling the Schedule button until they have picked a date?

This would address the issue I mentioned, but I think it's better to avoid the issue entirely by not using radio buttons.  Radio buttons work best when the setting you are modifying has multiple discrete values, one value per button, which isn't really the case here.

I think #23943 gets us to a better place here, but feel free to reopen if this needs further work.
