### ISSUE TITLE
Jetpack Onboarding: Reconsider initial error states

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#22842]
We've been discussing with @ockham that the error states that we display initially when showing the business address form are a little counter-intuitive, and make the page quite tall. It would probably make sense for them to appear only when the user has tried to submit the form with 1 or more empty required fields. 

![](https://cldup.com/cGLg651c_M.png)

What do you think @rickybanister @joanrho?

**Comment by ockham** [comment]
We might just remove the visual warnings altogether -- after all, it should be up to the user to decide what data to specify. In terms of programming logic, I wouldn't even bother to show them if the user tries to submit if they're all empty (seems like overkill for little gain to me). Disabling the 'Add address' button while all fields are empty should be enough IMO.

**Comment by rickybanister** [comment]
Is any data validation required for Google Maps to work properly? If so I would mirror what they're doing. Otherwise I guess I agree with @ockham that they should be able to put just a city on a map or something.

**Comment by keoshi** [comment]
I agree, and there was a related issue in Calypso for this same thing — let me try to find it.

**Comment by keoshi** [comment]
Here: https://github.com/Automattic/wp-calypso/issues/16684

**Comment by joanrho** [comment]
The length of all visible error states doesn't bother me, since realistically, not all error states will be active at the same time. But I do agree with Bernie that we should let users decide what information they want to input/display. I also see how Rick's point about data validation may affect what users expect from this widget. So, I'd recommend editing the description to say:

"Add your business address and a map of your location with Jetpack's business address widget. A valid address is required to properly display the map. You can edit all of this information and adjust the widget's location later."

**Comment by rickybanister** [comment]
Since we've removed the validation logic at this point, I don't think there's too much value in adding that line. Do we think people would try to enter an invalid address? I imagine they'll trouble-shoot this from the customizer when they can actually see their map (that may be the best place to put extra help copy). You can't actually validate the address here since we don't return the map itself. 

So is it alright to stick with the copy as it was @joanrho?

**Comment by joanrho** [comment]
@rickybanister re: validation, sounds good to me. How about including the "You can edit all of this information and adjust the widget's location later." as the last line instead of what we have there? This helps indicate that the info is editable in addition to being moveable.

**Comment by rickybanister** [comment]
How about: `You can edit the widget's content and position later.`

**Comment by tyxla** [comment]
Will update the copy in another PR.

**Comment by tyxla** [comment]
@rickybanister @joanrho copy is being updated in #22872.
