### ISSUE TITLE
People: Can't send invitation when username field still has focus

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#22864]
<img width="769" alt="screen shot 2018-02-27 at 1 49 08 pm" src="https://user-images.githubusercontent.com/1270189/36756917-420f611e-1bc5-11e8-9d18-962301b011d5.png">

1. Navigate to https://wordpress.com/people/invites/
2. Select a site
3. Try to invite someone without unfocusing the username text field
Expected: Send Invite button is enabled
Actual: Invite button is disabled until you focus on something else

**Comment by mattsherman** [comment]
This is behavior that I admittedly just accepted since it was in place already when we started working on the invites improvements and I knew how it worked, so it "made sense" to me. But, it definitely could be confusing to customers in the following scenario:

1. Enter a single username/email
2. Inviting a Follower, so no need to change Role dropdown
3. Do not enter a Custom Message

For any scenario where the customer is changing the Role or custom message after entering in a username/email, they would not hit this. It only happens if they never change the Role/Custom Message or change those prior to entering username/email.

Perhaps we should just keep the "Send Invitation" button enabled initially, do the validation when the button is clicked, and only disable it if validation fails at that point.

**Comment by gwwar** [comment]
> Perhaps we should just keep the "Send Invitation" button enabled initially, do the validation when the button is clicked, and only disable it if validation fails at that point.

Sounds quite reasonable to me. Another more mild check would be to disable the button if the username field is completely empty. :)
