### ISSUE TITLE
Reader: Disconnected Jetpack sites should be treated like plain feeds

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#22911]
For https://wordpress.com/read/feeds/48044138 / blog id `58611663`, we show the 404 screen. However, this is a former Jetpack site that's still active. We should show posts from the site (they do appear in the following stream today).

Additionally, if I alter the code a bit to show the stream (by disabling the site.is_error check in feed stream) I can set blog id backed settings (post notifications / email notifications / etc), which should also be disabled. 

I think the solution here has a few parts:
1. We should modify the read/site/:site endpoint to return a different error for disconnected jetpack sites so we can ID them
2. Disconnected Jetpack sites should not be able to participate in reader features driven by a blog id
2a. But what about users who added things and then lost them because the site disconnected?
2b. And also how should we handle temporary disconnects vs intentional disconnects?
3. We should probably pick up intentional disconnects (if we can) and modify the feed records and sub matrix records to drop the blog id

**Comment by blowery** [comment]
There's also likely mods required to the 1.2/read/feed/.../posts endpoint, as it can end up querying the jetpack shadow if it detects a blog id associated with the feed.

**Comment by blowery** [comment]
Another one https://wordpress.com/read/feeds/26124488

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
