### ISSUE TITLE
Blog ID is reported incorrectly as null, undefined, or as incorrect site

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#23108]
When reporting tracks events we may get some non-sensical blog_id values when reporting from site specific routes. eg `/posts/:site`

We may be running into timing issues where:
- site id is not available yet
- site id is incorrect (this might be the last site we looked at)
- we shouldn't be looking at the current site id at all ( #16900 )

This line may be of some interest:
https://github.com/Automattic/wp-calypso/blob/d7b8e0a3d6e65bcd75d864f6122c9ba7ddc732cc/client/lib/analytics/super-props.js#L24

See p4qSXL-2hc-p2 (comment-5825) for additional examples.

**Comment by gwwar** [comment]
@Copons I think we can close this one out since we have a recommended path for this. If folks notice new items, we should create a new more specific issue.

**Comment by Copons** [comment]
@gwwar Ok!
I was on the fence here, but in fact we have most things tracked or even with open PRs.

---

Closing because the issue has been fixed at framework level.
Most instances of the incorrect approach (`analytics.pageView.record`) have been replaced with the correct one (`PageViewTracker`), and we have officially deprecated the former in the [analytics docs](https://github.com/Automattic/wp-calypso/blob/master/client/lib/analytics/docs/page-views.md).
