### ISSUE TITLE
Editor: Images taken on iOS not uploading from Google properly

### ISSUE THREAD

**Issue by jackiejade** [Automattic/wp-calypso#23138]
User christophorr was in chat and is trying to add photos from Google Photos into their post. Their connection settings look good, but when they try to insert photos into their posts a broken image icon appears and the image does not insert.

We’ve tried:
   
- Clearing browser cache & DNS host cache
- Disconnecting and then reconnecting google photos
- @designsimply and I tested this error on our personal sites but could not reproduce

The user confirmed that their images are all public.

@rachelmcr was able to reproduce this on her iPhone 6 stating: 

> I was able to reproduce the issue on my personal account, for photos that I had autouploaded from my iPhone 6 through the Google Photos app. Non-photos (screenshots I made on my phone) that I had backed up the same way are working just fine, but photos from my iPhone aren’t working.

>When I tested on my a8c account, linking to my a8c Google account, I tested with screenshots and photos taken on my Android tablet and everything worked as expected, so I wonder if there’s an issue with photos taken on iOS devices?

The user was asked to confirm if they could upload screenshots and they said yes they could, but that regular images are not working. 

User is on iPhone 6s, running iOS version 11.2.6

@tcn33 mentioned this may be a resolution issue with the photos from the iPhone.

**Comment by deancroyal** [comment]
Noting [another similar report](https://mc.a8c.com/support-stats/happychat/transcript.php?id=4425628): not able to add images from Google Photos that were taken with iPhone (iPhone 8, Apple iOS 11.4), but they are able to upload/insert images direct from iPhone without issue.

They also tried the disconnect/reconnect which did not appear to affect any change.

**Comment by AtrumGeost** [comment]
Got another report for this bug (5416245-hc):

iPhone 7 MNAF2LL/A (iOS 11.4.1): They can add images that were taken from their computer, but not from their iPhone. This is the error they get:

`1 file could not be uploaded because an error occurred while uploading.`

Re-connecting Google Photos didn't help

**Comment by tanjoymor** [comment]
Another report potentially for this bug (1847067-zen). I've asked the user to confirm the same information that was provided in this post to see if it's an iPhone related issue for them as well. But they are getting the error of `1 file could not be uploaded because an error occurred while uploading.` when they try to copy an image from their Google Photos within WordPress to the media library and I was able to replicate it on their site. The site is on a free plan.

**Comment by tanjoymor** [comment]
Another report that Google Photos isn't working with the Media Library 1854767-zen

**Comment by susanjanec** [comment]
> Another report potentially for this bug ([1847067-zen](https://href.li/?https://automattic.zendesk.com/agent/tickets/1847067)). I've asked the user to confirm the same information that was provided in this post to see if it's an iPhone related issue for them as well.

The user replied that the photos were originally taken on an iPhone.

Also reported that:

>The photos are on my computer in my google media library, I, however, can not upload them to my blog or add them to the other media library. Screenshots can also not be copy & pasted into my blog.
