### ISSUE TITLE
Gallery get blurred when loading on mobile view 

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#23197]
Hi there,

Square tile galleries get blurred when loading on mobile. This issue only happens on WordPress.com, tried on a WordPress.org site and wasn't able to reproduce the issue.

#### Steps to reproduce
1. Create a gallery with these settings:
![gallery-settings](https://user-images.githubusercontent.com/3696121/37231817-99cdb322-23ba-11e8-856f-77114ee28424.png)
2. View the gallery on a mobile view with the cache cleared:
![gallery-issue](https://user-images.githubusercontent.com/3696121/37231891-d9b5c830-23ba-11e8-9ce4-74f138611dde.gif)

#### What I expected
To load the gallery images without the "blur" effect, like here (WordPress.org test site):
![galllery-wporg](https://user-images.githubusercontent.com/3696121/37231974-1a285b3a-23bb-11e8-8bfe-b55fff879c05.gif)

#### What happened instead
The images got blurred.

#### Browser / OS version
Google Chrome 64.0.3282.186 / macOS High Sierra
However, we have reports that this also happens on mobile devices the first time they load the images.

#### Context / Source

#user-report (949929-zen for internal reference)

**Comment by rachelmcr** [comment]
Thanks for the report! I saw more discussion about the issue (internal ref p2EDhh-kv-p2 — that's helpful information to include in this report) and saw that this has been reproduced in multiple themes, so it isn't a theme-specific issue either.

Since it isn't theme-specific or an issue within Calypso itself (but rather front-of-site rendering), I've moved it so we can track it as a WordPress.com issue (internal ref 8021-wpcom).
