### ISSUE TITLE
Simple Payments: screen doesn't load if customer has text data in item price

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#23213]
#### Steps to reproduce

There was a customer support request `1001910-zen` where the customer had text data in some simple payment items price values, in which case the simple payments would no longer load.

Raised the potential data quality issue here: `p3fqKv-5FD-p2`

There is a JavaScript error loading the form:

```
Uncaught TypeError: Cannot read property 'integer' of null
    at ProductListItem.formatPrice (list-item.jsx:83)
    at ProductListItem.render (list-item.jsx:124)
    at finishClassComponent (react-dom.development.js:7873)
    at updateClassComponent (react-dom.development.js:7850)
    at beginWork (react-dom.development.js:8225)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
```

#### Screenshot / Video

<img width="839" alt="screen shot 2018-03-12 at 9 42 57 am" src="https://user-images.githubusercontent.com/128826/37260456-173c3268-25df-11e8-92c0-feaead2fc66b.png">

This is what the "price" showed when I removed all formatting (data now fixed)

<img width="1114" alt="form" src="https://user-images.githubusercontent.com/128826/37260471-439575c2-25df-11e8-88a8-e79e749d508e.png">

**Comment by rachelmcr** [comment]
Related issue (previous report): https://github.com/Automattic/wp-calypso/issues/17767

**Comment by alisterscott** [comment]
Another case in `1008146-zen`

**Comment by apeatling** [comment]
Thanks for the report, we'll get this looked at.

**Comment by kwight** [comment]
Simple Payments products are stored as a custom post type `jp_pay_product`, with the submitted form data (such as price) kept in meta. While I can't replicate this issue by submitting an invalid price in the form (which makes sense, considering [this check](https://github.com/Automattic/wp-calypso/blob/master/client/lib/format-currency/index.js#L27)), I was able to replicate by doing an `update_post_meta` on the product itself. 

Next, I'll see what the best way might be to catch these invalid values stored in the db, so that the data coming from the API is better typed (maybe a filter on `get_metadata`).

**Comment by designsimply** [comment]
Noting that I tried a few different ways to reproduce the problem (with language switched, using commas instead of decimals) but couldn't get the interface to break using Calypso directly (likely due to the same checks @kwight mentioned).

**Comment by kwight** [comment]
@designsimply It's still strange, after a quick look I couldn't explain why or when users would have been able to enter bad data, or what would have fixed it.

**Comment by alisterscott** [comment]
More discussion in `p3fqKv-6th-p2`
