### ISSUE TITLE
Store: Pending orders total doesn't account for individual order currency

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#23281]
Discovered while adding support for new countries, currencies and currency formats for #21574 

getNewOrdersWithoutPayPalPendingRevenue just sums all the orders without regard for cases where the order currency is not the same as the site currency

https://github.com/Automattic/wp-calypso/blob/cbe72e4d10ed6a2c885a3d9300602a1c69fdfb68/client/extensions/woocommerce/state/sites/orders/selectors.js#L253

Not sure this is affecting any/many sites - since most of the time the order currency is the same as the store currency - so this is probably just a corner case that just bears noting here until we see it in the wild.

This value is presented in the Store dashboard when pending orders are present: https://github.com/Automattic/wp-calypso/blob/58a00b326e41a35061d1ab0a5e718aeb092c16e5/client/extensions/woocommerce/app/dashboard/manage-orders-view.js#L110

**Comment by justinshreve** [comment]
Closing this since we no longer show a pending amount in the widget.

We do show a $ amount in the stats widget. There could be a case where they switched currencies, but this does feel like a corner case and not something that will happen often (and we only show a month back so it seems unlikely they will switch currencies multiple times in a month)
