### ISSUE TITLE
Unable to bulk Spam/Delete comments

### ISSUE THREAD

**Issue by munirkamal** [Automattic/wp-calypso#23295]
I tried to mark multiple/bulk comments as spam or Delete them. It gets done but within seconds I get errors as in the following screenshot.

![image 2018-03-14 at 3 35 02 pm](https://user-images.githubusercontent.com/5817882/37397488-901ad54e-279d-11e8-8cbe-51fa6f168382.png)

I've tried it many times since past few days and the issue remains same.

I am using the latest version of the app on MAC.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
A quick test of bulk editing comments on my test site indicates this is likely resolved.
