### ISSUE TITLE
Simple Payments: Incorrect price in notification stream

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#23337]
The price doesn't have the currency symbol, and it seems to be converted to US dollar. This is really confusing for non-USD sellers. The correct price and symbol are there when it's expanded..

![screen-shot-2018-03-15-at-14 29 34](https://user-images.githubusercontent.com/908665/37474309-fbbd2b88-2867-11e8-8a93-b57fb0d84b9a.jpg)

**Comment by scosgro** [comment]
Another report in 9957816-hc

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
Quite a lot of work has been done since the time of this issue on payments blocks available on WordPress.com, so this is also likely resolved.
