### ISSUE TITLE
Store: Header bar has duplicate site information

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#23343]
There were some much needed and appreciated changes to the mobile header. https://github.com/Automattic/wp-calypso/pull/22541 These also made changes to the larger screen views, which caused duplicate site info:

![screen shot 2018-03-15 at 12 49 55 pm](https://user-images.githubusercontent.com/5835847/37485026-e309bad8-284f-11e8-975b-53fb2be62429.png)

Our original header designed purposely diverged from the rest of calypso given the nature of Store. 

Options to fix:
- Only apply mobile changes to small screen (revert changes made to the large screen)
- @justinshreve suggests: Change header above nav to read "Store"
- Borrow @shaunandrews's designs
- Other ideas? cc @jameskoster

**Comment by jameskoster** [comment]
The only other option I could think of would be to combine the site link with the title/breadcrumb area;

![combined](https://cldup.com/kSdqkZqGiU-3000x3000.png)

But that doesn't disrupts the link between content / navigation so not really ideal.

> Only apply mobile changes to small screen (revert changes made to the large screen)

That seems like the cleanest solution design-wise.

**Comment by shaunandrews** [comment]
FWIW, I think what you mocked up, @jameskoster, is really nice. It reminds me of the editor's "ground control" toolbar.

The store currently has a "sticky" header for that primary action button, how would your mockup work with scrolling? Would the whole bar be sticky?

--

One note, not totally relevant: Can we switch to a chevron rather than the back arrow? That's what we're using to indicate a sidebar item has a second-level of navigation:

<img width="274" alt="screen shot 2018-03-19 at 10 33 19 am" src="https://user-images.githubusercontent.com/191598/37601661-fcf5abaa-2b60-11e8-9523-7cc3619f8afd.png">

**Comment by jameskoster** [comment]
> The store currently has a "sticky" header for that primary action button, how would your mockup work with scrolling? Would the whole bar be sticky?

The whole bar is sticky anyway, so it would work fine in that regard I think.

> One note, not totally relevant: Can we switch to a chevron rather than the back arrow? That's what we're using to indicate a sidebar item has a second-level of navigation:

Yeah we can definitely address that :)
