### ISSUE TITLE
Posts: Status filter in dropdown mode is unusable

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#23353]
For me, and at least sometimes for @rachelmcr, the status filter in the posts list becomes unusable when it shifts from a row of tabs to a dropdown.  This happens when the width of the filters exceeds a certain amount, which happens on mobile or when a site has a large number of posts in different statuses.

In this collapsed / dropdown mode, the filter is unusable for me because the dropdown won't stay expanded long enough for me to click on an option:

> ![post-status-selector](https://user-images.githubusercontent.com/227022/37499447-c0322c06-2891-11e8-9587-ef3fe739cd9b.gif)

The normal mode (a row of tabs) works fine.  If I apply a CSS rule which increases the width available for the filter, it is an effective workaround for larger screen widths because the filter goes back to the default "row of tabs" mode.  However, the filter remains broken when it collapses again at small screen widths.

The related code is the "mobile" and "dropdown" stuff in [`section-nav/index.jsx`](https://github.com/Automattic/wp-calypso/blob/51cca03c/client/components/section-nav/index.jsx) and [`section-nav/tabs.jsx`](https://github.com/Automattic/wp-calypso/blob/51cca03c/client/components/section-nav/tabs.jsx).

This issue probably only appears on certain combinations of device/OS/browser.  I'm seeing the issue on Chrome for Linux on a laptop with a touch screen, and @designsimply has been unable to see it on a variety of devices.  @rachelmcr what browser(s) do you see this issue on?

**Comment by rachelmcr** [comment]
I have seen this on macOS 10.13.3/Chrome 64-65, on my Macbook Pro. Mine might be a slightly different issue, though. It usually only happens on the first one or two tries, and after that I can open the dropdown fine. (I hadn't reported it because it felt like possible user error, e.g. a misclick, when it happened.)

I think in my case it only happens if I click on the dropdown while the post list is loading. If I wait a few seconds after opening the post list, I can click and the dropdown works as expected.
