### ISSUE TITLE
My Sites: Clicking All My Sites doesn't always work

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#2340]
See video at https://cloudup.com/caXCazwBoAF

Repro:
* Load wordpress.com
* Click on My Sites
* Pick Blog Posts from the sidebar
* Switch back and forth between All Sites and an individual blog. Usually breaks on the first switch back to All Sites.

The list gets stuck on the previous entry and doesn't switch until you pick that entry again.

**Comment by rralian** [comment]
Yeah, I'm seeing something similar... I need to pick something twice in order for the site-picker to work correctly. I see this in /posts and /pages, but I don't see this issue in stats, plugins, or themes.

The URL seems to work correctly, but the UI doesn't always update to reflect it. So it leads to an inconsistent page... here I have the all-sites URL being shown (because I just selected all-sites), but the sidebar still shows the previously selected site, and the list of posts is also from the previously selected site.

![inconsistent state](https://cloudup.com/cLN2QpsPSse+)
