### ISSUE TITLE
Jetpack Onboading: Preserve last step when redirecting to obtain credentials

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#23436]
Currently, if we're in a step different from site title, and we're redirected to obtain onboarding credentials, after obtaining we'll be redirected to the site title. 

It would be a better experience if the user is redirected to the step that they were trying to access last.

**Comment by tyxla** [comment]
This will likely require an additional parameter for the `onboard` action, just like we handle `calypso_env`; thus it would need changes in Jetpack.

**Comment by tyxla** [comment]
Another way, which avoids Jetpack changes is to store the last step in a cookie.

**Comment by ockham** [comment]
I've thought some more about this. I my preferred way would be to persist Redux state -- this would be the simplest and most elegant way of retaining credentials for when a user returns to JPO. We would likely have to add some sort of exception since right now, we don't persist Redux state for logged-out users IIRC.

**Comment by tyxla** [comment]
Sounds like a great plan! I was only wondering if we could break anything if we do that. Would be good to investigate what were the motivations to implement clearing of the state when logging in, just to make sure we're not missing something.
