### ISSUE TITLE
Jetpack Onboarding: Losing onboarding credentials when logged out and redirected to JPC flow

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#23435]
To reproduce:

1. Start the flow here: http://yourgroovydomain.com/wp-admin/admin.php?page=jetpack&action=onboard
1. Enter a site title.
1. Select "Personal" or "Business" for the site type.
1. Select "Recent news" or "Static page" for the homepage.
1. Select "Add a contact form" to be taken to the Jetpack connection flow. I was logged out, so this brought me to the account signup form.
1. Select the browser's back button.

Going back took me to this blank page with no console errors.

I used my browser's back button to go all the way back through the flow, and every page was blank. I had to re-enter the initial link to restart the flow.

---

Reported in p1HpG7-4WU-p2 #comment-25071 by @rachelmcr

**Comment by tyxla** [comment]
It appears that when logged out and being redirected to the Jetpack Connect flow, Redux state is flushed and onboarding credentials are lost.

The simplest solution will be to redirect back to wp-admin to reobtain them again in such cases. We already have a mechanism for that, we just need to expand it to cover this case. PR coming soon.

**Comment by tyxla** [comment]
I think we introduced this in #22775.

**Comment by ockham** [comment]
Testing this, I discovered the following:
* Start in a new incognito window (so you're logged out of WP.com)
* https://jurassic.ninja/create?jetpack-beta
* http://your.jurassic.ninja/wp-admin/admin.php?page=jetpack&action=onboard&calypso_env=development
* Wait for redirection to JPO.
* Site title and tagline fields aren't pre-populated!
* The reason seems to be that `hasFinishedRequestingSite` is set to `false` here: https://github.com/Automattic/wp-calypso/blob/a48f3155a367c8bdf468aa4e4bb0e3d9874e40e3/client/jetpack-onboarding/main.jsx#L77

Need to investigate what's wrong there.

**Comment by ockham** [comment]
Ah-hah! https://github.com/Automattic/wp-calypso/blob/a48f3155a367c8bdf468aa4e4bb0e3d9874e40e3/client/jetpack-onboarding/main.jsx#L191-L192 doesn't work for logged-out, since the 'all sites' concept (which is implicit in `isRequestingSites`) simply doesn't work for logged-out users (and the `isRequestingSite` doesn't really work anyway...)

**Comment by ockham** [comment]
This is both interesting and tricky. We can't just add an `isLoggedIn` criterion, since a user might be logged out of WP.com, while their site is connected. Ideally, we can modify the query component and `isRequestingSite` selector to work with site slugs...

**Comment by ockham** [comment]
This is a bit of a catch-22:

* We want to know whether we're connected or not, since that determines whether to send `jpoAuth`  credentials or not, so we wait until `hasFinishedRequestingSite` before we query JP(O) settings.
* However, if we're logged-out and unconnected, we cannot `<QuerySites />`, since we can't query for "all the user's sites", nor do we have a `siteId` to query for specifically.

**Comment by ockham** [comment]
One way out of this dilemma could be to actually do `<QuerySite siteId={ siteSlug } />` (and `isRequestingSite( state, siteSlug )`. Thanks to the underlying action, this will work...

**Comment by tyxla** [comment]
Nice sleuthing @ockham, and the solution makes sense. Will test run it in a bit.
