### ISSUE TITLE
Domain Search: use zip code lookup to populate city and state

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2345]
Raised by @breezyskies 

Something @stephanethomas and I have discussed in the past is using the zip code to pre-populate the city and state (at least for the most common countries). There are a few existing tools for this that I've come across recently: [Zippopotam](http://www.zippopotam.us/) and [Ziptastic](http://daspecster.github.io/ziptastic/index.html).

Here's a quick mockup of how we could move the zip code field up so the user would fill it out first:

<img src="https://cloud.githubusercontent.com/assets/3011211/7887621/1e686246-05f8-11e5-9c84-af27a7638ff1.png" width="400">

We could also hide the city and state fields until they zip is entered and the lookup is complete (as Zippopotam does in it's demo) so the domain registration details form doesn't look as big (hopefully leading to less user abandonment).

On a related note, is it worth pre-populating the zip code in the checkout form based on what the user enters here? Is that likely to be a good enough guess for most users?

**Comment by klimeryk** [comment]
Personally, I _hate_ it when the address form on a website tries to be too smart. Address are [_hard_](https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/) (I highly recommend to at least skim this article). While this might improve the flow for some users, it will generate an obstacle for others. See for example this point in that article:
> **An address will have a postcode**

> Richard Fletcher, Lee Hosty, Paul O'Nolan, Simon Diab, Tony Finn, Donal Maccarthy, mark lynch and Donovan all pointed out countries like the Republic of Ireland have addresses without postcodes, or only have postcodes in certain parts of the country. Danny Angus points out this is also the case in Hong Kong.
> Jessica Enders points out the [post-paid address of the AEC](http://www.aec.gov.au/enrol/send-form.htm): Australian Electoral Commission, Reply Paid 9867, your capital city

In order to do this _right_, we would have to add a lot of logic, exceptions (or rely on a third-party service, if it exists, that does it right).
Sorry if I'm sounding overly negative about this, it's just that this sort of improvements to address forms are a pet peeve of mine :laughing: If it can be done properly, I'd love to be corrected :)

**Comment by breezyskies** [comment]
> In order to do this right, we would have to add a lot of logic, exceptions (or rely on a third-party service, if it exists, that does it right).

Fair enough (and probably not worth the complexity if we can't use something more out-of-the-box). :) Also open to other improvements to this form, it's a huge obstacle right now in the checkout flow for domains, but I'll close this one for now.

**Comment by klimeryk** [comment]
Heh, I was going to suggest A/B testing this to see the actual impact :) Especially if it's such a pain point during the checkout, I think it might be interesting to see the impact of the changes @designsimply suggested.
Hooking up to a third party service to look up the city/state (for example for just the US users) shouldn't be too hard. No other changes to the form, no hiding of fields. The information deduced from the post code should be a hint, something that the user can easily change/override. Should make for a nice and quick A/B test ;)
