### ISSUE TITLE
Happychat Localized Chat Routing not showing the correct button

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#23509]
Happychat Localized Chat Routing not showing the correct button
#### Steps to reproduce
1. Set your interfaz language to SPANISH in https://wordpress.com/me/account
2. Set a site language -for this user- to SPANISH, I did with https://wordpress.com/settings/general/aprehendizajes.com
3. Set another site language to ENGLISH, I did with https://wordpress.com/settings/general/extimacies.wordpress.com
4. Try to get help from https://wordpress.com/help/contact, write something in the ¿Como podemos ayudarle? element (How could we help you?) to enable the buttons

#### What I expected

I expected to have in both cases, both buttons enabled (CHAT in ENGLISH + TICKET) or (CHAT + TICKET), depending on whether they are Spanish chat operators available

#### What happened instead
If I select the Spanish site -aprehendizajes.com- on top, I enable just the button to chat in English.
![wordpress com 2018-03-21 16-13-20](https://user-images.githubusercontent.com/6404071/37718424-eeb7b5e2-2d22-11e8-9f43-12113c65646f.png)

By the way, the support document suggestions are in English.

If I select the English site -extimacies.wordpress.com- on top, I enable no button.
![wordpress com 2018-03-21 15-57-40](https://user-images.githubusercontent.com/6404071/37718159-5f885660-2d22-11e8-83e6-a44324ef3547.png)

WHY IS THIS?

You need to fill the 'subject' field to enable the 'Email us button'.
It took me 15 minutes to realize this 'subject' field issue, and asked for help of other HE (@brezocordero ) so we can assume this is a difficult move for some of our users. 

![wordpress com 2018-03-21 16-13-42](https://user-images.githubusercontent.com/6404071/37718914-1767c990-2d24-11e8-9186-2786fbb865d7.png)

We have we noticed a drop of the Spanish support requests (We agreed on this in Spanish Guild hangout), have we any stats confirming/denying this assumption?

PS: 4th case
If I try to get support for the English site, with a Spanish user, filling the subject and question fields, I get no Chat option at all.
![wordpress com 2018-03-21 16-23-38](https://user-images.githubusercontent.com/6404071/37719014-56435d14-2d24-11e8-9812-82995a394f8d.png)

#### Browser / OS version

Chrome 64, but also in any other browser

**Comment by nellofn** [comment]
>You need to fill the 'subject' field to enable the 'Email us button'.

For this, we'll need to highlight the **Subject** field to make it easier for users to realize why the Contact option is not enabled.

>4th case
>If I try to get support for the English site, with a Spanish user, filling the subject and question fields, I get no Chat option at all.

I tried this on my sites and could replicate this case as well:

- Site language: English
- Account language: Spanish

**Result:** Email button only.

**What I expected:** Help options are based on the user's account language, not the site's language setting.

**Comment by mattwondra** [comment]
@rantoncuadrado Thanks for spotting this — we thought we'd explicitly not required the subject line in this case but it seems we were wrong. In the case where two buttons are present (one to email in Spanish and one to chat in English) we will remove the subject line and only a message will be required, the same as it is currently for live chat.

> If I try to get support for the English site, with a Spanish user, filling the subject and question fields, I get no Chat option at all.

This is because you chose a free site so live chat is not available.

**Comment by mattwondra** [comment]
@nellofn I'm assuming the same thing happened when you tested an English site — it was a free site, so chat was not given as an option.

To clarify — we do not account for the site's language preferences in any way when showing support options and routing chats/tickets.

**Comment by unDemian** [comment]
> WHY IS THIS?
> You need to fill the 'subject' field to enable the 'Email us button'.
> It took me 15 minutes to realize this 'subject' field issue, and asked for help of other HE (@brezocordero ) so we can assume this is a difficult move for some of our users.

I don't think stats would be affected by this, because that is how the form has always worked. When email option is present the subject field will be required. We are going to remove the subject field when we show both email and chat via https://github.com/Automattic/wp-calypso/pull/23529

> We have we noticed a drop of the Spanish support requests (We agreed on this in Spanish Guild hangout), have we any stats confirming/denying this assumption?

I can't see a big decrease in `es` chats in the past 2 months, I added a new chart which breaks down number of active chats per locale. You can check it out at the bottom of grafan Happychat Availability dashboard there is a section called `Active chats per locale`. Ping me in private if you need

**Comment by rantoncuadrado** [comment]
@mattwondra you are right about my English site. It was free. Sorry about that.

> I can't see a big decrease in es chats in the past 2 months, I added a new chart which breaks down number of active chats per locale. 

@unDemian. I expected something like this. The difference would be in tickets. To clarify this, as a general rule: 

- You can expect people able to speak English to choose Chat
- People with no English knowledge facing the ES-Ticket vs EN-Chat alternative could choose ES-Ticket. 
- The same people facing the EN-Chat as the only possibility could choose in some cases not to receive support at all. 

In this scenario the decrease would be in tickets.

Using this view (maybe not the best tool) https://woothemes.zendesk.com/agent/admin/views/60802506

Opened Spanish tickets last 7 days (168 hours): 292
Last 14 days (336 hours). 642 tickets.
Last 21 days (504 hours). 1030 tickets
  
So, last week: 292 tickets
Week-2: 350 tickets
Week-3: 388 tickets 32% more tickets than last week

It's maybe coincidental but could be interesting to take a deeper look at.

**Comment by mattwondra** [comment]
@rantoncuadrado There shouldn't be any impact on tickets because of this. The experience of the ticket-only form hasn't changed at all (it's always required a subject line to be submittable). And the new double-button form with the known issue was previously a chat-only form. So even though it's not ideal that the double-button form requires a subject for the ticket to be filled, that's not taking away any opportunity for tickets that was there previously.
