### ISSUE TITLE
Bug: Press This cannot be dragged to favorites bar in Microsoft Edge

### ISSUE THREAD

**Issue by caimin-j** [Automattic/wp-calypso#23505]
Using Microsoft Edge:
#### Steps to reproduce
1. Go to My Sites > Settings
2. Drag the Press This button to the favorites bar...
3. ..or right-click the Press This button

#### What I expected
To be able to save Press This to the favorites bar.

#### What happened instead
Press This can't be dropped on to the favorites bar. The right-click option does show an option to add to the favorites bar.

#### Browser / OS version
I tested this on Windows 10 desktop with Microsoft Edge 41.16299.15.0.
I've also had the same bug report from a user using a Surface Pro.

#### Screenshot / Video
Trying to drag to the favorites bar:
![2018-03-21_15h47_24](https://user-images.githubusercontent.com/37620825/37717197-5ae5b6d6-2d20-11e8-9ed1-948c61e00a1a.png)

After right-clicking:
![2018-03-21_15h48_02](https://user-images.githubusercontent.com/37620825/37717218-612e994a-2d20-11e8-939d-2146e5c50769.png)

**Comment by designsimply** [comment]
I tried adding any link by dragging it into the favorites bar in Edge 16 on Windows 10 and found that it didn't work, so I think it's a limitation of the browser. ([24s](https://cloudup.com/cA9p5gRwgW3))

After searching, I found a Stack Overflow answer that proposes a workaround: https://stackoverflow.com/a/43307055

I tried testing it but found a slightly different workaround worked for me: [35s](https://cloudup.com/cG-g2nYh19P)

**Comment by designsimply** [comment]
Would love to have a second opinion from someone working on the project about whether it might be worth updating the language. Here's what it currently says:

> Press This is a bookmarklet: a little app that runs in your browser and lets you grab bits of the web.
> 
> Use Press This to clip text, images and videos from any web page. Then edit and add more straight from Press This before you save or publish it in a post on your site.
> 
> Drag-and-drop the following link to your bookmarks bar or right click it and add it to your favorites for a posting shortcut.

<img width="1280" alt="screen shot 2018-03-21 at wed mar 21 11 22 11 am" src="https://user-images.githubusercontent.com/1119271/37726117-339557a6-2cfa-11e8-9fcf-21b1d2d59e3c.png">

**Comment by caimin-j** [comment]
Thanks for the info. I've let the user know and sent them a link to the workaround video.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
I quickly tested dragging the Press This bookmarklet into my bookmars bar in Microsoft Edge Version 114.0.1823.44, and it worked as expected. Closing as resolved.
