### ISSUE TITLE
Analytics: page views reported with non-normalized paths

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#23525]
According to internal logs, some `calypso_page_view` paths coming from Checkout are reported without replacing passed parameters with corresponding variables. For example we are reporting `example.wordpress.com` in paths instead of `:site` etc.

For more background on this please check out https://github.com/Automattic/wp-calypso/issues/16902, p7jreA-1xN-p2, and p4qSXL-2hc-p2. Ideally we should have a generic solution for this, but that would probably require replacing `page.js` and refactoring routing in Calypso.

Until then it would be great if we could figure out a way to reduce the number of new errors popping up, while we work on resolving the existing issues. Some of the ways that we could achieve this:
- adding monitoring on bad stat reporting
- introducing eslint rule if we can find a common pattern

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
