### ISSUE TITLE
Jetpack Connect: Manual instructions margins unequal at some widths

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#23544]
<img width="517" alt="screen shot 2018-03-22 at 12 39 28" src="https://user-images.githubusercontent.com/7767559/37771327-26a79650-2dcf-11e8-9926-010f8663c9df.png">

400px > Unequal margins < 480px

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
