### ISSUE TITLE
Replying to a comment doesn't respect depth limits

### ISSUE THREAD

**Issue by choubacha** [Automattic/wp-calypso#23574]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/blogs/144400841/posts/3#comments
2. Reply to comment "b" over and over. (see comments with the text `b-r-1`, every new reply has another `r` added to it)
3. Each reply is actually replied to the previous comment
4. Examine the network of comments and parents. You should see that I was able to create a deeply nested reply structure.

This is with this setting enabled:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/2043529/37806617-35be744a-2dfe-11e8-84e7-df3c326a6f1e.png">

#### What I expected
I expected the reply button to be hidden and the comment creation to fail if it were more deeply nested than my site settings allow

#### What happened instead
I was able to continue to create deeper and deeper nested comments.

#### Browser / OS version
Firefox / MacOS

#### Screenshot / Video
It's hard to demonstrate in a single image but here are the json responses and you can see how each parent points to the next comment.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/2043529/37806696-960372b0-2dfe-11e8-8fb3-e6c474c33d8b.png">

<img width="198" alt="image" src="https://user-images.githubusercontent.com/2043529/37806710-aa4d8f80-2dfe-11e8-8ab0-451bdc86d602.png">

<img width="177" alt="image" src="https://user-images.githubusercontent.com/2043529/37806717-b74787ea-2dfe-11e8-9d8f-812a33da1520.png">

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
