### ISSUE TITLE
Pages: Unable to set a page as a Home page

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#23576]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/page/[site].
2. Add a new page.
3. Try setting a page as your Home.

#### What I expected
To be able to set any page in `/pages` as my Home page. I searched for this option in the ellipsis menu, but it wasn't there.

It also doesn't help that I'm seeing `Front page is showing your latest post`. "Well, yes, that's correct, but how do I change it?"
![screenshot 2018-03-22 18 57 40](https://user-images.githubusercontent.com/4924246/37807481-e9c91f22-2e02-11e8-9cb6-801c5d210acf.png)

I ended up Googling this. Most search results are for self-hosted sites, but I eventually found this: https://learn.wordpress.com/bonus-round-get-a-home-page/

#### What happened instead
I had to set the Home page in Customizer. It feels disconnected to me.

#### Browser / OS version
Google Chrome Version 65.0.3325.162
Mac OS High Sierra 10.13.3

**Comment by mccarthinator** [comment]
This is legit! I agree this current workflow is inefficient and disconnected. Also, this is my first attempt to make a code contribution to calypso, so bear with me please as I attempt to come up with a solution :)  

Design question for you as I see you're a product designer and I'm not! What is your ideal workflow for this process of easily changing a homepage?

-One solution I see is adding another "menu item" in this popover_menu like this, that would let a user select it as the new homepage.

- Here's what the popover_menu currently looks like :
![current-menu](https://user-images.githubusercontent.com/19803726/37867740-88d1a7ac-2f6a-11e8-84d3-fccf10a76502.png)

- Here's what I think it could look like:
![new-menu](https://user-images.githubusercontent.com/19803726/37867791-23587fa8-2f6b-11e8-9d73-b9742a7344e5.png)

^ I would change the pencil icon to something else, probably.

**Comment by mccarthinator** [comment]
I've identified that this menu is a React component (PopoverMenuItem), which is found in client/my-sites/pages/page/index.js

But it's not the functionality of the component that needs changing, it's the display of this specific page that needs an additional menu-item component added to the menu. In the readme inside of the popover docs, I see that "children { node }" is where we define what exactly gets rendered inside of any given popover menu. 

Because I'm a n00b when it comes to React and how Calypso creates and displays its components, I'll attach my diff with what I think could work but I'm sure it's going to break all the things. I'm hopeful someone else with more React experience can come in and take my patch and eventually make it work!

**Comment by jancavan** [comment]
> What is your ideal workflow for this process of easily changing a homepage?

I actually assumed that an option to be able to set a page as a Home page would be in the ellipsis menu as mentioned in the original description:

> To be able to set any page in /pages as my Home page. I searched for this option in the ellipsis menu, but it wasn't there.

So I think adding it there is a good start. For the icon, the Home icon used in this image would be a better choice instead of the Pen icon:
![screenshot 2018-03-22 18 57 40](https://user-images.githubusercontent.com/4924246/37807481-e9c91f22-2e02-11e8-9cb6-801c5d210acf.png)

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/24087
