### ISSUE TITLE
Australian country code for SMS recovery missing from drop down list

### ISSUE THREAD

**Issue by fstath** [Automattic/wp-calypso#23648]
#### Steps to reproduce
1. Go to Account > Security > Account Recovery (https://wordpress.com/me/security/account-recovery)
2. Click on Add next to Recovery SMS number
3. Expand the Country Code drop down list to see that Australia isn't listed

#### What I expected
To see Australia's country code (+61)

#### What happened instead
The code isn't listed

#### Screenshot / Video
![screen shot 2018-03-26 at 19 03 31](https://user-images.githubusercontent.com/32326882/37918089-bc194f74-3128-11e8-9d68-01a922888b61.png)

#### Context / Source
A user reported it on Twitter and I have also tested in on my accounts as well.

Here’s the tweet for reference: https://twitter.com/LauraHamilton09/status/978241730876026880

**Comment by rachelmcr** [comment]
It looks like Australia (+61) is listed as "Cocos (Keeling) Islands" in the dropdown there, so the country code is available in the list but is labeled incorrectly. That list is coming from here:

https://github.com/Automattic/wp-calypso/blob/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/lib/countries-list/index.js#L153

**Comment by rachelmcr** [comment]
@southp It looks like the label may have changed due to r171277-wpcom. (Prior to that, the label for +61 was `Australia/Cocos/Christmas Island`.) Could you take a look?

**Comment by southp** [comment]
Argh! Sorry for causing this issue. With D11289, the AU is added back like this:
![image](https://user-images.githubusercontent.com/1842898/38011955-1204e9ba-3292-11e8-9ce3-dd6ab7afb7e7.png)

Since CC is still a valid country code by itself, I think it would be better to also keep it. Thus, the code is reserved and moved to the C-leading name group like this:
![image](https://user-images.githubusercontent.com/1842898/38011961-199607d6-3292-11e8-9401-8cfae7a873ff.png)

@rachelmcr Does that makes sense to you?

**Comment by rachelmcr** [comment]
That looks great to me; thanks for looking into this so quickly!

**Comment by southp** [comment]
I've deployed the fix. Please help me confirm if it's been resolved. Thanks 🙇

**Comment by rachelmcr** [comment]
I confirmed that the fix is working for both the Recovery SMS Number and the 2FA phone number country code fields. Thanks again! Closing as resolved.
