### ISSUE TITLE
Sharing: OAuth windows are not localized.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#23654]
Currently, all OAuth windows open in English, regardless of the user's locale. Some services (such as Twitter) accept a parameter to specify the OAuth window's language; this should be tied to the user's current locale and passed on.

![screen shot 2018-03-20 at 1 00 05 pm](https://user-images.githubusercontent.com/349751/37925453-75543390-30e9-11e8-9384-fed8e7256d33.png)

**Comment by kwight** [comment]
It turns out some services will use the language according to the user's settings, which explains my own results: my Twitter account was in English, so the OAuth window was displayed in English.

 - [ ] Facebook
 - [ ] Twitter
 - [ ] Google+
 - [ ] LinkedIn
 - [ ] Tumblr
 - [ ] Path
 - [ ] Eventbrite
 - [ ] Photos from Google
 - [ ] Google My Businesss

**Comment by kwight** [comment]
The service will only identify the user's language if the user is logged in to the service, so it would still be nice to provide an explicit language if we can. I've identified some params and formats that individual services use to call specific languages, but I'll also need to verify that the `service.connect_URL` (which I think comes from Keyring) can be modified to include it.

- Facebook: `locale=fr_FR`
- Twitter: `lang=fr`
- Google+: `hl=fr`

**Comment by kwight** [comment]
There's a Keyring [filter for auth token params](https://github.com/beaulebens/keyring/blob/master/includes/services/core/oauth2.php#L61); maybe this can be used to pass an additional language parameter to the service.

Hm, but after testing further, a test connection from Sharing winds up using OAuth1 (not sure why), so the language param would be inject [here](https://github.com/beaulebens/keyring/blob/master/includes/services/core/oauth1.php#L169) (but we don't have a params filter for OAuth1 like we do for OAuth2).

**Comment by beaulebens** [comment]
Note that Twitter does actually [use the OAuth1 service](https://github.com/beaulebens/keyring/blob/master/includes/services/extended/twitter.php#L7).

I think I just never added any filters there because I haven't needed them yet, but seems totally appropriate. If you do it somewhere right around where you linked (in the context of the authorize URL/redirect), then I'd suggest something like `keyring_{$service}_authorize_params` as the filter since it's slightly different from the `request_token`. I think the `request_token_params` equivalent filter for OAuth1 would actually belong [somewhere up here](https://github.com/beaulebens/keyring/blob/master/includes/services/core/oauth1.php#L81).

Feel free to just go ahead and implement what you need in the WP.com codebase as required, and I'll merge to the public copy of Keyring once you're done.

**Comment by kwight** [comment]
Started work in D12008-code.

**Comment by kwight** [comment]
Hm, digging further, I can see now that some services will use a cookie to determine the user's locale, even if the user is not logged in. I should have checked that earlier 🙃

* Facebook: `locale=fr_FR`
* Twitter: `lang=fr`
* LinkedIn: `"v=2&lang=fr-fr"`
* Tumblr: `%2Cfr_FR`

We can now assume that if a user has ever logged in to the service they're connecting to, they will see the OAuth window in whatever language to which that service is set. This means that, best case scenario, this work may help only users that have never logged into a service they're connecting (seems rather unlikely), and worst-case scenario, we'll force the user's WordPress.com locale over top of any locale the user previously selected for that service. Knowing this, it feels like I'm trying to solve a problem that isn't really there, so I'll close and move on.
