### ISSUE TITLE
Showcase: Remove "current theme" notification bar

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#23694]
With some of the recent changes to the Showcase, there are now a LOT of various notification bars on the screen. So many that they take up too much room. 

I'm proposing to eliminate the "current theme" bar and make the first theme in the grid be the active theme and keep it highlighted as it currently is.

1. HEs have mentioned that the 'current theme' bar rarely gets clicked on, and is rarely noticeable by users anyway.
2. The first theme in the grid being the active theme follows the /wp-admin which appears to work for people.

![current-theme](https://user-images.githubusercontent.com/617986/37981690-313c7586-31a3-11e8-86a0-3fd252d82ffb.png)

We should probably A/B test this solution. 

@mendezcode, any thoughts?

**Comment by kjellr** [comment]
It'd also be interesting to gather data around what people use this page for, and what they expect to use this page for. Do they primarily:

1. Use it to find information about their current theme? 
2. Use it to change their theme, and explore other themes?

If it's more the former, the Current Site bar is potentially very valuable. If that's the case, perhaps we'd want to:

- Keep the Current Site bar where it is, but adjust the treatment so that it's more noticeable.
- Hide the current theme from the grid by default, to avoid content/functionality duplication. If a user were to search or filter the grid, we could display the theme there for completeness, but otherwise it's unnecessary.

**Comment by mapk** [comment]
This is going to involve more design work and thinking. I had thought this would be a quick win worth AB testing, but there have been some great points brought up by @kjellr, @ockham and others regarding the proposed change on the PR #23879. 

I'm closing this.
