### ISSUE TITLE
Media: "Link To" Setting For Gallery Does Not Work

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#23784]
I came across user's ticket when they did not want the images in their gallery to be linking to anything. But changing from Calypso - Link To - None, does not seem to change anything.

#### Steps to reproduce
1. Starting at URL:
2. Create A New Page: https://wordpress.com/page/
3. Add a gallery to it
4. Select the option to edit gallery and then select Link to - None, Media or Attachment Page

#### What I expected
To see the difference when I select to link to different options

#### What happened instead

All of the options looked the same:
1. This is Link To - Media File: https://cloudup.com/csGxjNObxCQ
2. This is Link To - None: https://cloudup.com/cl3aW4EEfLf
3. This is Link To - Attachment Page: https://cloudup.com/cqMaOp8hxcK

All of the options look exactly the same. 

I tested with two themes - Soho and Sketch; it happened with both of them. 

#### Context / Source

The user asked to remove the link to from their pages in #1051369-zen

Somewhat similar issue #23543

**Comment by rachelmcr** [comment]
When the carousel is enabled (no setting in Calypso; can be adjusted under Settings > Media > "Display images in full-size carousel slideshow" in WP Admin) gallery images will open in that carousel slideshow. Also, the "link to: none" option has no effect when carousel is enabled — see related internal issue 6033-wpcom.

Note that the other options (attachment page and media) do have an effect on the gallery. If you click on an image it opens in a carousel, but right-clicking and opening the link in a new tab with open either the attachment page or the media file as specified in the gallery settings.

I think it's worth leaving this issue open for now, since the combination of having no carousel setting in Calypso and having the "link to: none" setting is confusing.
