### ISSUE TITLE
Analytics: allow Jetpack Premium Plan holders to use Google Analytics options

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#23936]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/traffic/ while selecting a site with a Jetpack Premium plan.
2. Scroll down to the Google Analytics section.
3. Try to activate the option.
4. You will receive the following response for the request:

```
{"code":424,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"not_supported","message":"The requested Jetpack module is not supported by your plan."}}
```

This feature should be accessible as we enabled GA for Premium plans.

cc @tyxla since you recently worked on this in #23036.

Reported in 1067400-zen

**Comment by tmmbecker** [comment]
also reported in 1067713-zen

**Comment by kraftbj** [comment]
I believe this caused by https://github.com/Automattic/jetpack/blob/5c1ee15dfe051f274ce6ca22df3a078046814427/modules/google-analytics.php#L12 .

https://github.com/Automattic/jetpack/blob/33b2f8d611fe8f7255a8df192a73f7d1c2e87c7f/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php#L70 is what is returning the error message.

**Comment by tyxla** [comment]
Thanks @kraftbj @jeherve 🙇
