### ISSUE TITLE
Creating a new site: getting stuck in the store-nux flow

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/wp-calypso#24008]
#### Steps to reproduce
1. Starting at URL: wordpress.com (logged in)
2. Switch Sites > Add a new site
3. New WordPress site
4. Fill in site details
5. Only select "Sell products or collect payments"

#### What I expected
I expected to be able to create a new site with a .wordpress.com domain and choose premium as my subscription type. 

#### What happened instead
I was forced into a business plan / and purchasing a custom domain

#### Browser / OS version
Chrome / OSX

#### Screenshot / Video

[https://cloudup.com/c_lR-YflMmE](https://cloudup.com/c_lR-YflMmE)

#### Context / Source

@crunnells and I were both running through the onboarding to partake in John's simple payments / buy me a beer challenge, and we both ran into the same problem when trying to create a new site. We both got stuck in the loop for a business plan, and couldn't create site on a premium plan with a .wordpress.com domain. CC: @fditrapani

**Comment by fditrapani** [comment]
Thanks for submitting this issue @LevinMedia. 

Just to give you a little background of what's happening here, when you only select "Sell products or collect payments" as a site goal, you are placed in the `store-nux` signup flow. This flow allows people to create a store right from signup and explains why you don't see any `.wordpress.com` subdomains along with only seeing the business plan. The reason, is because we need an Atomic site to preinstall plugins for the WP.com store that gets created after signup and being on a business plan with a custom domain is a prerequisite for that. 

When this flow was setup, the WP.com store was the only way to sell products and collect payments on WP.com so it made sense. We have since introduced the simple payments button so this might be worth revisiting. That being said, with the amount of traffic going through here it might not be the highest thing to prioritize. 

I'll cc @anneforbush and @mattwiebe as they're working in this space now.

**Comment by mattwiebe** [comment]
I was actually working on an a/b test and discovered another related bug, in that:

1. pick "sell products or collect payments" and click next
2. get "choose store theme" page
3. don't want a store
4. click back (the link on the page, not the browser button), choose anything else, click next
5. still "choose store theme"

This happens because it puts us the `store-nux` flow and clicking the back link keeps us in there, going back to the `/start/store-nux/about` route. 

I don't think this is the highest priority either, but this one is more of a straight functional problem.

**Comment by drw158** [comment]
I came across the exact bug as @mattwiebe. I just wanted to make a test site, but didn't see the free domain option.

**Comment by mattwiebe** [comment]
@drw158 oh, interesting. We fixed the stuff in my comment, but this is something else, as the flow now does get restored (you won't see the `store-nux` part in the URL), but clearly there are some other assumptions that we're stuck in a paid-only flow. Can you create a new ticket specifying the domain part?
