### ISSUE TITLE
Remove CartStore

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#24019]
This one's a biggie.

### Code
[lib/cart/store](https://github.com/Automattic/wp-calypso/tree/master/client/lib/cart/store) - actual flux stores. index and synchronizer register separately.
[lib/cart-values](https://github.com/Automattic/wp-calypso/tree/master/client/lib/cart-values) - operations / selectors on immutable cart data
[lib/products-values](https://github.com/Automattic/wp-calypso/tree/master/client/lib/products-values) - operations / selectors on product data. immutable?

Those are the big sources. Clients for each:

*cart/store:*
```
client/state/lib/middleware.js:1
client/my-sites/current-site/index.jsx:1
client/components/data/domain-management/index.jsx:1
client/components/data/domain-management/email/index.jsx:1
client/components/data/checkout/index.jsx:1
client/components/data/cart/index.jsx:1
client/lib/transaction/store.js:1
client/lib/checkout/ebanx.js:1
```

*cart-values:*
```
client/signup/steps/domains/index.jsx:1
client/signup/steps/plans/index.jsx:1
client/signup/steps/plans-atomic-store/index.jsx:1
client/signup/steps/site-or-domain/index.jsx:1
client/signup/steps/get-dot-blog-plans/index.jsx:1
client/state/selectors/is-eligible-for-checkout-to-checklist.js:1
client/my-sites/guided-transfer/host-credentials-page/index.jsx:1
client/my-sites/domains/domain-management/privacy-protection/card/add-button.jsx:1
client/my-sites/domains/domain-management/add-google-apps/add-email-addresses-card.jsx:1
client/my-sites/domains/transfer-domain/index.jsx:1
client/my-sites/domains/domain-search/site-redirect-step.jsx:1
client/my-sites/domains/map-domain/index.jsx:1
client/my-sites/checkout/gsuite-nudge/index.jsx:1
client/my-sites/checkout/checkout/secure-payment-form.jsx:1
client/my-sites/checkout/checkout/transaction-steps-mixin.jsx:1
client/my-sites/checkout/checkout/credit-card-payment-box.jsx:1
client/my-sites/checkout/checkout/subscription-text.jsx:1
client/my-sites/checkout/checkout/paypal-payment-box.jsx:1
client/my-sites/checkout/checkout/redirect-payment-box.jsx:1
client/my-sites/checkout/checkout/privacy-protection.jsx:1
client/my-sites/checkout/checkout/domain-details-form.jsx:1
client/my-sites/checkout/checkout/pay-button.jsx:1
client/my-sites/checkout/checkout/payment-box.jsx:1
client/my-sites/checkout/checkout/checkout.jsx:1
client/my-sites/checkout/cart/cart-total.jsx:1
client/my-sites/checkout/cart/cart-item.jsx:1
client/my-sites/checkout/cart/cart-plan-discount-ad.jsx:1
client/my-sites/checkout/cart/cart-messages.jsx:1
client/my-sites/checkout/cart/cart-items.jsx:1
client/my-sites/checkout/cart/cart-plan-ad.jsx:1
client/my-sites/exporter/guided-transfer-card/complete-purchase-notice.jsx:1
client/components/domains/map-domain-step/index.jsx:1
client/components/upgrades/google-apps/index.jsx:1
client/components/upgrades/google-apps/google-apps-dialog/index.jsx:1
client/me/purchases/manage-purchase/index.jsx:1
client/lib/transaction/store.js:1
client/lib/domains/utils.js:1
client/lib/signup/step-actions.js:1
client/lib/signup/cart.js:1
client/lib/checkout/test/ebanx.js:1
client/lib/checkout/index.js:1
client/lib/checkout/ebanx.js:1
client/lib/cart/store/index.js:1
client/lib/cart/store/cart-analytics.js:1
client/lib/upgrades/actions/cart.js:1
client/lib/upgrades/actions/free-trials.js:1
```

*products-values:*
```
client/signup/main.jsx:1
client/state/purchases/selectors.js:1
client/state/selectors/is-eligible-for-checkout-to-checklist.js:1
client/state/selectors/user-has-any-paid-plans.js:1
client/my-sites/sidebar/sidebar.jsx:1
client/my-sites/domain-tip/index.jsx:1
client/my-sites/ads/main.jsx:1
client/my-sites/plans/current-plan/controller.jsx:1
client/my-sites/plans/current-plan/index.jsx:1
client/my-sites/plugins/plugin-meta/index.jsx:1
client/my-sites/plugins/plugins-browser/index.jsx:1
client/my-sites/upgrade-nudge/index.jsx:1
client/my-sites/checkout/gsuite-nudge/index.jsx:1
client/my-sites/checkout/checkout/free-trial-confirmation-box.js:1
client/my-sites/checkout/cart/popover-cart.jsx:1
client/my-sites/checkout/cart/test/cart-item.js:1
client/my-sites/checkout/cart/cart-plan-discount-ad.jsx:1
client/my-sites/checkout/cart/cart-item.jsx:1
client/my-sites/checkout/cart/cart-plan-ad.jsx:1
client/my-sites/checkout/checkout-thank-you/domain-registration-details.jsx:1
client/my-sites/checkout/checkout-thank-you/header.jsx:1
client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx:1
client/my-sites/checkout/checkout-thank-you/features-header.jsx:1
client/my-sites/checkout/checkout-thank-you/personal-plan-details.jsx:1
client/my-sites/checkout/checkout-thank-you/index.jsx:1
client/my-sites/checkout/checkout-thank-you/premium-plan-details.jsx:1
client/my-sites/checkout/checkout-thank-you/domain-mapping-details.jsx:1
client/my-sites/site-settings/form-analytics.jsx:1
client/my-sites/site-settings/form-general.jsx:1
client/my-sites/site-settings/seo-settings/form.jsx:1
client/my-sites/site-settings/search.jsx:1
client/components/plans/plan-price/index.jsx:1
client/components/seo-preview-pane/index.jsx:1
client/components/marketing-survey/cancel-purchase-form/options-for-product.js:1
client/components/marketing-survey/cancel-purchase-form/steps-for-product-and-survey.js:1
client/me/purchases/remove-purchase/index.jsx:1
client/me/purchases/purchases-site/index.jsx:1
client/me/purchases/manage-purchase/purchase-meta.jsx:1
client/me/purchases/manage-purchase/notices.jsx:1
client/me/purchases/manage-purchase/index.jsx:1
client/me/purchases/manage-purchase/plan-details/index.jsx:1
client/me/purchases/cancel-purchase/test/cancellation-effect.jsx:1
client/me/purchases/cancel-purchase/refund-information.jsx:1
client/me/purchases/cancel-purchase/button.jsx:1
client/me/purchases/cancel-purchase/index.jsx:1
client/me/purchases/cancel-purchase/cancellation-effect.jsx:1
client/me/purchases/utils.js:1
client/me/purchases/product-link/index.jsx:1
client/me/purchases/purchase-item/index.jsx:1
client/me/purchases/confirm-cancel-domain/index.jsx:1
client/post-editor/editor-drawer/index.jsx:1
client/lib/ads/utils.js:1
client/lib/purchases/index.js:1
client/lib/domains/utils.js:1
client/lib/domains/email-forwarding/index.js:1
client/lib/plans/index.js:1
client/lib/signup/step-actions.js:1
client/lib/products-values/sort.js:1
client/lib/cart-values/index.js:1
client/lib/cart-values/cart-items.js:1
client/lib/analytics/ad-tracking.js:1
```

So there's a lot of code to cover.

### Prior Authors
Practically everyone. 50+ overall contribs.
Primarily @klimeryk @aidvu @stephanethomas @adamziel @delputnam @hambai @johnHackworth @spen  ...

### SSR Involved?
Doesn't appear so... Unsure.

### Any current work?
https://github.com/Automattic/wp-calypso/pull/22901
https://github.com/Automattic/wp-calypso/issues/6709 a bit

### Suggested Approach
Find out how the current store folks want to approach this. So much code.

**Comment by spen** [comment]
I just rebased #22901 so that's good for review now. Thankfully some of @aidvu's work has helped reduced the weight of that PR too so reviewing should be that little bit easier now :)

Also, I'll be very happy to pitch in here between my regular team responsibilities. Feel free to nudge me for reviews etc. and I'll do what I can! Go team!

**Comment by lsl** [comment]
Created a `<QueryCart>` component in #28375 before discovering the existing `<CartData>` way of doing things.

I wasn't going to take it anywhere anytime soon but it might serve as a good starting point for anyone wanting to move dependencies off of the synchronise code before replacing it with redux events.

**Comment by sirbrillig** [comment]
I've been working on this over the past several months, specifically by replacing `CartData` and `CartStore` with `ShoppingCartProvider` and `withShoppingCart`/`useShoppingCart`.

A few recent pieces:

- https://github.com/Automattic/wp-calypso/pull/48202
- https://github.com/Automattic/wp-calypso/pull/47970
- https://github.com/Automattic/wp-calypso/pull/47605
- https://github.com/Automattic/wp-calypso/pull/48152
- https://github.com/Automattic/wp-calypso/pull/48437

**Comment by sirbrillig** [comment]
After https://github.com/Automattic/wp-calypso/pull/48512, https://github.com/Automattic/wp-calypso/pull/48495, https://github.com/Automattic/wp-calypso/pull/48437, and https://github.com/Automattic/wp-calypso/pull/48202 are merged, the only places still using the cart modifying functions from `lib/cart/actions` that will need to be replaced with `@automattic/shopping-cart` functions are:

- `PlanBillingPeriod`
- `GSuiteAddUsers`
- `Customize` which adds a theme
- `CompletePurchaseNotice` in guided transfer 
- `HostCredentialsPage` in guided transfer
- `MapDomain` in domains
- `SiteRedirectStep` in domain search
- `domainSearch` in the domains controller which adds a personal plan if `?ref=upgrade`
- `TransferDomain` in domains
- `PaymentCountrySelect` which uses `setTaxCountryCode` (this will be removed as soon as the new payment method screens are fully launched)
- `Signup` which calls `disableCart`

Places that still use `CartData` will be:

- The `checkout` controller, which uses it to wrap `CheckoutSystemDecider`. This is used to prevent race conditions and can be removed once the above function calls are removed.
- `SiteRedirect` in domains
- `MapDomain` in domains
- `TransferDomain` in domains
- `UseYourDomainStep` in domains
- `TransferDomainStep` in domains

And finally, places that use `CartStore` directly will be:

- `isEbanxCreditCardProcessingEnabledForCountry` as a default if the cart isn't passed in which is only used in `getEbanxCreditCardRules`, which is used by `paymentFieldRules`, which is used by `validatePaymentDetails`, which is used (for credit card data) only in `CreditCardPayButton` and only when Ebanx is already enabled, so that call to `isEbanxCreditCardProcessingEnabledForCountry` can be removed.
- `ManagePurchase` under payment management, which sets the site ID. I think this may no longer be necessary.

**Comment by sirbrillig** [comment]
https://github.com/Automattic/wp-calypso/pull/48687, https://github.com/Automattic/wp-calypso/pull/48782, https://github.com/Automattic/wp-calypso/pull/48743, and https://github.com/Automattic/wp-calypso/pull/48744 take care of:

- `PlanBillingPeriod`
- `GSuiteAddUsers`
- `Customize`
- `CompletePurchaseNotice`
- `HostCredentialsPage`

This leaves basically just domains pages.

**Comment by sirbrillig** [comment]
We're nearly there, thanks to some wonderful work by the Domains folks. As of now, places still using `lib/cart/actions` are:

- `SiteRedirectStep` in domain search which adds a site redirect product when the form is submitted (fixed by https://github.com/Automattic/wp-calypso/pull/50282)
- `domainSearch` in the domains controller which adds a personal plan if `?ref=upgrade` (fixed by https://github.com/Automattic/wp-calypso/pull/50281)
- `PaymentCountrySelect` which uses `setTaxCountryCode` (fixed by https://github.com/Automattic/wp-calypso/pull/50491)
- `Signup` which calls `disableCart` (this can just be removed when the `CartStore` is removed).

Places that still use `CartData` are:

- The `checkout` controller, which uses it to wrap `CheckoutSystemDecider`. This is used to prevent race conditions and can be removed once the above function calls are removed.
- `SiteRedirect` in domains (fixed by https://github.com/Automattic/wp-calypso/pull/50282)

And finally, places that use `CartStore` directly are:

- `isEbanxCreditCardProcessingEnabledForCountry` as a default if the cart isn't passed in which is only used in `getEbanxCreditCardRules`, which is used by `paymentFieldRules`, which is used by `validatePaymentDetails`, which is used (for credit card data) only in `CreditCardPayButton` and only when Ebanx is already enabled, so that call to `isEbanxCreditCardProcessingEnabledForCountry` can be removed (fixed by https://github.com/Automattic/wp-calypso/pull/50284).
- `ManagePurchase` under payment management, which sets the site ID (fixed by https://github.com/Automattic/wp-calypso/pull/50283)

**Comment by sirbrillig** [comment]
The last thing is to remove `CartData` from `CheckoutSystemDecider`, but this is harder than I anticipated because it's been utilized for siteless and registrationless checkout. I'm working on the problem in https://github.com/Automattic/wp-calypso/pull/50681

**Comment by sirbrillig** [comment]
The current plan:

- Remove CartData from checkout: https://github.com/Automattic/wp-calypso/pull/50681
- Move getRememberedCoupon to where it is used: https://github.com/Automattic/wp-calypso/pull/50817
- Remove CartData: https://github.com/Automattic/wp-calypso/pull/50818
- Remove CartStore 🎉 : https://github.com/Automattic/wp-calypso/pull/50819
- Remove unused functions from cart-values and products-values: https://github.com/Automattic/wp-calypso/pull/51105

That should be everything!

**Comment by tyxla** [comment]
Thank you @sirbrillig and team! Absolutely outstanding work with this one 👏  ❤️
