### ISSUE TITLE
Activity: no rewind buttons after adding back credentials

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#24025]
While testing the Activity log, I removed and added back credentials.

This seems to tell the UI that this site is just now being set up and originates a couple of problems:

- No rewind buttons visible across the UI; they were there before.
- “Backup underway” banner has incorrect copy: in this case we are _not_ backing up the site for the first time, and so this is not the initial backup. We should check and have different banners for different scenarios.

![image](https://user-images.githubusercontent.com/390760/38550248-d94f1138-3cad-11e8-8a93-e4c04720705d.png)

**Comment by eliorivero** [comment]
This is because after re-entering creds, the Rewind state is `provisioning`. At this point, Rewind actions like restores and backups aren't available.

A quick fix for the notice is to update the copy so instead of "We're currently backing up your site for the first time" it says something simple like "We're creating a backup of your site".

However this should be addressed in the Rewind state machine and I wrote a post about it in p9rlnk-ei-activitylogrewind

**Comment by eliorivero** [comment]
@dmsnell fixed this in D11668
