### ISSUE TITLE
Reduxify: lib/shortcodes

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#24219]
A pretty small store with limited actions
* store is 100 LOC
* one action, `fetch`
* only used by `components/shortcode`

Might be a good candidate to leave out of redux and just use the new context API?

Either way, this should be really straightforward.

**Comment by blowery** [comment]
Previously ported to redux in https://github.com/Automattic/wp-calypso/pull/8116 and an attempt at hooking it up in https://github.com/Automattic/wp-calypso/pull/8857.

@aduth @tyxla any other movement on this one since? Looks like it was hung up on getting media reduxified?

**Comment by blowery** [comment]
Pushing this back to the backlog for a bit while we do some more discovery.

**Comment by tyxla** [comment]
No movement since, unfortunately 😕 Back then, it was considered not a good idea to use a redux bridge, even for refactoring purposes - probably because it wasn't clear when the media store will be reduxified.

The redux implementation itself could use a refresh, because it was reduxified before the data layer and the global selectors directory were created.

Thanks for working on it 👍

**Comment by blowery** [comment]
Closed by #24368
