### ISSUE TITLE
Billing History: receipts for credit card renewals show authorization date instead of transaction date

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2432]
To test:

1. Go to https://wordpress.com/me/billing
1. Switch to a site that has had a renewal authorization and purchase happen in the past
1. Check the date on the receipt for a past renewal authorization and purchase
1. Find the actual transaction date and compare it to the date shown on the receipt

<strong>Result:</strong> the receipt shows the authorization date for the charge, not the actual transaction date.

<img alt="screen shot 2016-01-14 at 13 57 50" src="https://cloud.githubusercontent.com/assets/1119271/12334243/04c1d92e-bac7-11e5-8f6d-c0ed045f39b1.png" width="500" />
<sup>Personal information has been removed from this screenshot</sup>

/hat tip @evanzi for the original report

**Comment by peterbutler** [comment]
This is actually expected behavior.  The autorenew happens very early in the morning, UTC, but the receipt is displayed on the frontend in the browser timezone (so, if you're in North America, it would display as the day before).  I'd say this is the desired behavior, as it most accurately represents when the transaction happened from the user's perspective.
