### ISSUE TITLE
Devdocs: components loading at weird scroll positions when visiting from component library

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#24337]
#### Steps to reproduce
1. Visit https://wpcalypso.wordpress.com/devdocs/design
2. Scroll down the page to the pop over component and click on the title
3. Notice where on the screen you are dropped
4. Copy and paste URL into a new tab, notice it appears at the top of the screen

#### What I expected
I expect to load the component screens at the top

#### What happened instead
When I visit a component screen from the library, in some cases it loads the screen half way down or the bottom

#### Browser / OS version
Chrome

#### Screenshot / Video
![scroll](https://user-images.githubusercontent.com/6981253/39008350-6ac14c6a-43d6-11e8-86a2-0a8d7a4b79c7.gif)

#### Context / Source
Working on a personal project I ran into a similar issue where the component would maintain the scroll position of the previous component on route change.

**Comment by Dillweed5446** [comment]
Hi, I've taken a shot at fixing this issue, but 'yarn start' isn't working in my cloned directory.  Therefore, I don't have a way to run the dev environment to see if my code works.  Should I go ahead and commit the change anyways?

**Comment by fditrapani** [comment]
Hey @Dillweed5446! Thanks for reaching out. A number of us have been running into issues with yarn. I have been using `yarn run start` to get my server running. Something that worked for me before doing that was:

- deleting `node_modules` directory
- run `yarn install`
- then run `yarn run start`. 

You can give that a try if you want or share a PR with me, I'd be happy to take a look.

**Comment by Dillweed5446** [comment]
Hi @fditrapani, thank you for the response.  I've deleted the node_modules directory and run yarn install, but still seem to be having some issues.  I'm having issues with the wpcom section:

`wpcom: Insufficient number of arguments or no entry found.
wpcom: ERROR in Entry module not found: Error: Can't resolve 'C:\Users\pdill\one
drive\documents\github\wp-calypso\packages\wpcom.js/dist/esm/index.js' in 'C:\Us
ers\pdill\onedrive\documents\github\wp-calypso\packages\wpcom.js'
wpcom: Alternatively, run 'webpack(-cli) --help' for usage info.
wpcom: error Command failed with exit code 2.
wpcom: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about th
is command.
wpcom: ERROR: "build:bundle" exited with 2.
wpcom: error Command failed with exit code 1.
wpcom: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about th
is command.
lerna ERR! yarn run prepare exited 1 in 'wpcom'
`

I would submit my solution, but I need to tinker with it to see how best to implement it.  Without an environment to run the code in, I can't see if what I'm doing is effective.  I don't want to waste your time sending you code that may not work yet.  I've found that my initial attempt was incorrect.  🤷‍♂️

**Comment by fditrapani** [comment]
Sounds good. When things act up for me like this, I usually delete the whole folder and do a clean install.

**Comment by Dillweed5446** [comment]
@fditrapani , I created a PR and tagged you in it #42195 .

I never got 'yarn run start' to work properly.  I tried deleting the node_modules folder and running 'yarn install' and even tried starting from scratch by cloning the repo again, deleting node_modules and running 'yarn install'.  The issues appear to be the wpcom dependency.  According to the package.json file, wpcom^6.0.0 is required, but the terminal says that version doesn't exist.  I tried to manually install the correct version with no success, then tried installing the version I could find available ^5.4.2, but wouldn't install because the package.json specifies the newer version.  I'm probably doing something wrong that I'm unaware of, but that's ok!  It's all part of the learning process.  Any feedback is welcome.  Thank you for your help!  I look forward to making many more contributions.
