### ISSUE TITLE
Jetpack: Feedback items open in editor window

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#24345]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/types/feedback/youratomicsite.blog for an Atomic or Jetpack site with feedback items
2. Click a feedback item

#### What I expected

To see the feedback item

#### What happened instead

The feedback opens in the post editor

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

![feedback atomic site](https://user-images.githubusercontent.com/128826/39031250-622cd090-44aa-11e8-9624-c925307593a4.gif)

#### Context / Source
#dogfooding

**Comment by designsimply** [comment]
Good find! Adding a quick screenshot/comparison for reference because I noticed that the feedback titles are not clickable at all in wp-admin:

![screen shot 2018-04-23 at mon apr 23 11 34 20 am](https://user-images.githubusercontent.com/1119271/39143318-d78479d2-46ea-11e8-8a94-554111ff2864.png)
<sup>Seen at http://alittletestblog.com/wp-admin/edit.php?post_type=feedback using Firefox 59.0.2 on macOS 10.13.4 on a site running WordPress 4.9.5 and Jetpack 6.0.</sup>
