### ISSUE TITLE
npm install: @5.6.0 - missing 'phone module'

### ISSUE THREAD

**Issue by whitefire0** [Automattic/wp-calypso#24464]
#### Steps to reproduce
1. Starting at URL: master repo
2. clone repository
3. npm start (with npm@5.6.0)
4. when navigating to http://calypso.localhost:3000/, encounter error message 'missing module', for 'phone'
5. installing phone with npm and restarting server eliminated the problem

#### What I expected
No missing modules

#### Browser / OS version
Chrome Version 66.0.3359.117 (Official Build) (64-bit)

**Comment by designsimply** [comment]
I followed your testing steps with npm 5.6.0 on macOS 10.13.4 and then visited http://calypso.localhost:3000/ using Chrome 66.0.3359.117 and I did not see an error message that said 'missing module' for 'phone'.

I also double checked the dependencies in `package.json` and `npm-shrinkwrap.json` I see that "phone" is included:
https://github.com/Automattic/wp-calypso/blob/master/package.json#L125
https://github.com/Automattic/wp-calypso/blob/master/npm-shrinkwrap.json#L12066

Please try a fresh install and check to see if the problem is still happening and re-open the issue if needed.
