### ISSUE TITLE
Jetpack Plans: monthly-billed customers shouldn't be able to attempt to downgrade their plan

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#24470]
Currently:

A customer with a plan views the plans page and sees an 'upgrade' button on plans less expensive than their current plan:

<img width="1102" alt="screen shot 2018-04-24 at 4 04 25 pm" src="https://user-images.githubusercontent.com/437258/39254067-4256e2b2-4877-11e8-816a-76f2bb638c12.png">

Clicking the 'upgrade' link displays an error:

<img width="1080" alt="screen shot 2018-04-24 at 4 06 22 pm" src="https://user-images.githubusercontent.com/437258/39254086-4caef646-4877-11e8-9f68-fd235eb6e891.png">

What should happen? We should follow .com sites' lead and not display the 'upgrade' button. 

<img width="1098" alt="screen shot 2018-04-24 at 4 05 24 pm" src="https://user-images.githubusercontent.com/437258/39254168-779021fa-4877-11e8-8b7a-de997a88b124.png">

**Bonus:** If customers want to downgrade, they will have to cancel their current plan first. We should perhaps add a 'manage plan' link below the 'upgrade to yearly' button as a plain text link.

cc @rralian @beaulebens

**Comment by rickybanister** [comment]
The circumstance I encountered only happens with sites on a monthly subscription. I tried with a yearly subscription and saw what you saw: 

![image](https://user-images.githubusercontent.com/437258/39260713-52a17018-4888-11e8-8a3b-f8ca92372a47.png)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
