### ISSUE TITLE
Reader: Discover Page "Follow blog" button broken

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#24601]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/discover
2. Try to click the "follow log X" button from within one of the post-cards.  I saw it toggle quickly between green and then back to blue.  

I would have expected it to stay green (followed). The post cards seem like they aren't paying attention to followed state.

**Comment by alexpyzhianov** [comment]
Anyone working on this? I'd like to tackle it

**Comment by alexpyzhianov** [comment]
I investigated this and the problem seems to be deeper than just a broken button

**How it looks like:**
![londr](https://user-images.githubusercontent.com/7609100/40266064-43fcae1a-5b4d-11e8-8c70-78750d2fc1c9.gif)

**Probable cause:**

The button determines own state by comparing url coming from the reader's post feed `reader/posts/items/[id]/discover_metadata/attribution/blog_url` (in Redux state tree) which for this example is **"http://www.londnr.com"** and the url from the list of sites that user follows in `reader/follows/items` which for this example is **"http://www.londnr.com/feed"**

So you may actually follow the site, but the button will be blue and not green because these are two different strings. The short period when it's green is probably due to an optimistic update.

I couldn't find a more reliable value to compare like an id. It seems like there is such an id in follows list, but not in the reader's post feed

**Solutions:**
1. A dumb one would be to use regex to match the beginning of the string or strip whatever is after the first `/`. But it's quite fragile and with my limited knowledge I'm not sure of the consequences
2. Fix this url discrepancy on the API level :thinking:

**Comment by bluefuton** [comment]
Thank you for the writeup @alexpyzhianov! It helped point me in the right direction. I have a possible solution in https://github.com/Automattic/wp-calypso/pull/25718.
