### ISSUE TITLE
Google My Business: Fix connection to Google My Business not cleared upon disconnection

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#24703]
We should fix two weird behaviors happening for a site that has already been connected to Google My Business in the past (and is now disconnected). In that case we skip authentication and granting of permissions at Google:

#### Scenario 1

1. Open the [`Login` page](https://wpcalypso.wordpress.com/log-in) in an incognito window
2. Enter credentials, and log in to WordPress.com
3. Navigate to the [`Stats` page](https://wpcalypso.wordpress.com/stats/day) of a site that is no longer connected to Google My Business
4. Click the `Start Now` button in the nudge
5. Notice that you are redirected to the [`Select Location` page](https://wpcalypso.wordpress.com/google-my-business/select-location)

#### Scenario 2

1. Open the [`Login` page](https://wpcalypso.wordpress.com/log-in) in an incognito window
2. Enter credentials, and log in to WordPress.com
3. Navigate to the [`Sharing` page](https://wpcalypso.wordpress.com/sharing) of a site that is no longer connected to Google My Business
4. Click the `Connect` button for Google My Business
6. Assert that a Google popup is displayed
7. Close that popup without doing any action
8. Notice that you are still presented with the option to connect to a former location

**Comment by stephanethomas** [comment]
My feeling is that while we reset `google_my_business_keyring_id` and `google_my_business_location_id` in site settings when disconnecting the site from Google My Business, the Keyring connection itself is not cleared. It is then returned when the `me/keyring-connections` API endpoint is called.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
