### ISSUE TITLE
Microsoft Edge: Available widget areas don't load in Calypso

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#24757]
Report from user: 1138317-zen

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize
2. User opened `Widgets` expecting to see four available widget areas.
3. The user waited several minutes for the widget area sub-menus to load

#### What I expected

Four widget areas should have loaded after a few seconds, at most. I was able to view this in both Firefox Developer Edition 61.0b2 and Chrome 66.0.3359.139 on macOS 10.13.4:

![](http://cld.wthms.co/i0bLVl+)

#### What happened instead

The user only saw a single widget area:

![](http://cld.wthms.co/QtKTWq+)

#### Browser / OS version

Microsoft Edge 41.16299.371.0
Windows 10 Pro, version 1709

**Comment by designsimply** [comment]
Thank you for the report @pauljacobson! I tested using the Sela theme on a WordPress.com Simple and I was unable to reproduce the problem you have described. When I tested, I was able to see the same number of widget areas for the home page in the customizer using Edge 16 on Win10 compared to Chrome 66 on macOS 10.13.4.

<img src="https://user-images.githubusercontent.com/1119271/39829845-f5f745e0-537c-11e8-8043-e364b87263e1.png" width="270"> <img src="https://user-images.githubusercontent.com/1119271/39829846-f60b9892-537c-11e8-8756-1f0506837a9a.png" width="270">

I noticed that in the Edge screenshot you provided, it says the following on the left:

> Your theme has 6 other widget areas, but this particular page doesn't display them.

May I ask if you were viewing the home page in each case or were you perhaps viewing the customizer for a different page in one browser compared to the other?

Because I am unable to see the problem in action, would it be possible for you to check to see if there are any JavaScript errors in the console in Edge when you see the problem happen? See https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console

Could you please confirm which theme the site in question is using (for reference)?
