### ISSUE TITLE
Purchases: Various pages still has support links that go to support.wordpress.com/contact

### ISSUE THREAD

**Issue by hafizrahman** [Automattic/wp-calypso#2513]
Various pages within the purchases flow have links for users to contact us. These links still go to https://support.wordpress.com/contact. Ideally, they will need to go to https://wordpress.com/help/contact instead, because these pages are shown to logged-in users and therefore it's better to link them to the Calypso contact page instead.

All of the links that need to be updated can be found here: 

https://github.com/Automattic/wp-calypso/search?o=desc&q=%22contact+support%22+AND+support.wordpress.com&s=indexed&type=Code&utf8=%E2%9C%93

Originally reported by @jerrysarcastic in p2MSmN-4lM-p2

**Comment by klimeryk** [comment]
It might be a good idea to extract this support link to a separate component and reuse it throughout our codebase. Maybe other support links can be added there too - that way, when we need to update them, it'd be easier and without introducing too many changes.
Something simple like:

```
/**
 * External Dependencies
 */
import React from 'react';

export const ContactSupport = () => (
	<a href="https://wordpress.com/help/contact" target="_blank" />
);
```

**Comment by stephanethomas** [comment]
Great idea. We have a few [`paths.js`](https://github.com/Automattic/wp-calypso/blob/master/client/me/purchases/paths.js) files that centralizes urls now. We would just need to find a place to store these ones.

**Comment by hafizrahman** [comment]
Does it make sense to put the link in the existing https://github.com/Automattic/wp-calypso/blob/master/client/lib/paths/index.js ?

I looked at adding it in a `paths.js` file but the link is used in various locations (`client/me` and `client/my-sites` and could be used elsewhere) so I wonder if putting it in `lib/paths` is better.

**Comment by klimeryk** [comment]
I'd put it in a new, separate file, something like `client/components/links/index.jsx` - since these will be components common across different areas of Calypso.

**Comment by stephanethomas** [comment]
I didn't know about this [`paths` module](https://github.com/Automattic/wp-calypso/blob/master/client/lib/paths/), well done @hafizrahman. It looks like a good fit to me. @klimeryk, why couldn't we access this module from anywhere in Calypso?

**Comment by klimeryk** [comment]
I don't think that's a good fit, because `paths` is for generating URLs inside Calypso. While here we want to generate _components_ with URLs.
We could make use of the `paths` module for generating the URL for the contact page (that'd be a nice touch and I'd encourage such a separation), but putting the component (`<a>` link) in there too doesn't seem like a good idea to me, it's just not the place for it. I hope I made my reasoning clear :laughing:

**Comment by stephanethomas** [comment]
Oh I missed that part, sorry.

However I'm not sure we should factorize components since it gives us less flexibility. For example, we might want to open a link in the same tab, add [an event handler](https://github.com/Automattic/wp-calypso/blob/8aa30953c0aec9647b59f05984967c5b337fad28/client/me/security-2fa-setup-backup-codes/index.jsx#L72), or use [a button](https://github.com/Automattic/wp-calypso/blob/2bc5d08ddbfbc53785eb79c21d1c7ff6f2a63271/client/my-sites/site-settings/start-over/index.jsx#L66) instead of a link.

**Comment by klimeryk** [comment]
Roger that. I noticed the event handler part earlier and thought that maybe a factory pattern, like for `debug` would address that, but if we were to add support for using a button instead of link, it'd make this whole thing more complex than it should be.
In this case, I agree with @stephanethomas that we should only extract the URLs, so as to not limit the developers to what this module offers.
So far, I see two main use cases:
 * internal URLs (`/help/contact`) - this can be handled by a `paths.js`-like module (either existing one or refactored from a controller).
 * external URLs, most likely to our support pages - can be very similar to a `paths.js`-like module, just the base URL will be different.
