### ISSUE TITLE
User mentions: close popover when caret is moved off current word using arrow keys

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#25177]
In https://github.com/Automattic/wp-calypso/pull/25148#issuecomment-392767514, @blowery noted:

> One little weird bit of behavior: if I use the left and right arrows while the popover is active, the cursor moves. That's fine, but it feels like the popover should disappear if I leave the triggering word.

![40660510-2f2c4e80-631f-11e8-8a31-25f05f28dfbf](https://user-images.githubusercontent.com/17325/40692747-b3ede212-6407-11e8-9148-41df039df399.gif)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
