### ISSUE TITLE
Signup: determine whether it's a good idea to recommend checking email from waiting screen

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25215]
From: https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=49

> Inboxes are filled with distractions and it would be really nice to keep the momentum going

<img width="873" alt="screen shot 2018-06-01 at 2 41 37 pm" src="https://user-images.githubusercontent.com/128826/40821408-14fc46c2-65aa-11e8-9545-20c8d9498353.png">

**Comment by jancavan** [comment]
I want to note that quite oddly, this only happens if you pick a Free plan - you get the email verification prompt and the "Please wait..." button which changes to Continue. For paid plans, the "Please wait..." button is also still displayed, but this doesn't change to "Continue", you're immediately just redirected to `/checkout`.

**Comment by lancewillett** [comment]
This is no longer applicable to our improved onboarding flow rolled out to users Feb to May 2019. The post-signup loading screen doesn't have any action messages, and you end up on the checklist in Calypso instead.

<img width="1552" alt="Screen Shot 2019-05-31 at 06 06 56" src="https://user-images.githubusercontent.com/66797/58707635-58bc0580-836a-11e9-8b64-366171607ce8.png">


![signup-free](https://user-images.githubusercontent.com/66797/58707629-535ebb00-836a-11e9-8336-7976cdcf9f04.gif)
