### ISSUE TITLE
Billing History: domain registration purchases should not be displayed as multiple items

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2524]
Raised by @SiobhyB with testing steps from @v18

Steps to reproduce:
1. Log in to an account where you have purchased a domain name
2. Go to Me > Manage Purchases. Note that here the domain names are correctly shown as one item
3. Go to the Billing History tab
4. See the multiple items listings

<strong>Result:</strong> domain registrations are displayed as "Multiple items" under Billing History:

![multiple-items-example](https://cloud.githubusercontent.com/assets/1119271/12394006/3e6b7fba-bdc7-11e5-85cf-e94dc57202f3.png)

Showing "Multiple items" could contribute to user confusion over mapping vs. registration.

Note: domain registrations are correctly listed as a single charge in `/me` > Manage Purchases > Purchases and `/me` > Manage Purchases > Billing History.

(originally reported at p2MSmN-3nc-p2)

**Comment by kriskarkoski** [comment]
Noting this is still an issue (originally opened as a new issue). Here's what it looks like on the receipt:

![image](https://cloud.githubusercontent.com/assets/1900444/22987510/00dad294-f37d-11e6-9d1f-c64cc55764d0.png)

**Comment by SiobhyB** [comment]
I'm changing this issue from an enhancement to a bug as "multiple items" is still visible under the Billing History tab and doesn't accurately reflect a user's purchase. 

This is low volume, especially now that we have domains with plan only, but users still sometimes get confused and ask for an explanation on what each of the three items mean.

**Comment by worldomonation** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. **Report anew**: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. **Reopen**: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
It doesn't look like domain purchases (whether as part of plan credit or individually) show as multiple items.

![Screenshot 2023-08-04 at 7 11 28 PM](https://github.com/Automattic/wp-calypso/assets/6549265/054301f6-4604-4b18-9348-f81708d42c6e)
