### ISSUE TITLE
Question: Best way for newcomer to navigate file structure?

### ISSUE THREAD

**Issue by SnGrimes** [Automattic/wp-calypso#25240]
I'm new and wanting to contribute to the project but I have run into some difficulty trying to find specific files. For example: I was looking at #25216 but I don't know what folder to look in to find the file to work on. Any help would be appreciated.

**Comment by hermawan22** [comment]
Hi @SnGrimes . :)

Greetings, i also new to start contribute for Calypso.
dev docs is helpful for me understand the structure of Calypso https://wpcalypso.wordpress.com/devdocs

Hopefully that will be helpful for you too. :)

**Comment by SnGrimes** [comment]
@hermawan22 Thank you for the link. I read through it and still unable to find specific files. I was going to read the block documentation but the site says it no longer exists. I feel like my answer would have been there.

**Comment by designsimply** [comment]
One way I can think of to find a specific file for a case like this is to search for the exact text or some surrounding text that will hopefully lead me to the right file.

For example, a search for `"Do it!"` https://github.com/Automattic/wp-calypso/search?q=%22Do+it%21%22&unscoped_q=%22Do+it%21%22 currently returns 14 code results while a search for `"Upload your profile picture"` https://github.com/Automattic/wp-calypso/search?q=%22Upload+your+profile+picture%22&unscoped_q=%22Upload+your+profile+picture%22 returns 1 result.

From there, you would need to learn to walk through and understand the code in order to make the right change. From the 2nd result above, I can see that the `checklist` folder is likely the right place and in the set of larger results I see that there is one result from the `checklist` folder:

https://github.com/Automattic/wp-calypso/blob/dbf37af87474682b11e3f73e5f9eb084630ee143/client/blocks/checklist/checklist-task.jsx#L60

I am not a developer, but it does look to me like what you would need to do in order to customize each button text would be to create the specific wording for each one in the `tasks` constant in `onboardingChecklist.js` and then also write a way for that button text to be rendered properly in the `checklist-task.jsx` file. Note that when modifying button text, care needs taken for the text not being too long because it may cause UI issues once the text is translated (such as for German which often uses more characters for phrases like these). Particularly, mobile views can be affected.

To step back and learn more about how all of these pieces fit together, you may consider starting with a strong foundation in JavaScript and React if you don't have that already.
https://www.google.com/search?q=learn+javascript
https://www.google.com/search?q=learn+react

Glad to see you here and interested in helping! I love that. I think a new codebase in an unfamiliar code can be hard to get started in so keep at it and keep experimenting with your local setup!

**Comment by SnGrimes** [comment]
Well that explains that! It was under blocks and not components as stated in the devdocs.  I've written apps with JavaScript and React but never worked in a large, unfamiliar code base before. Thank you for your help!

**Comment by hermawan22** [comment]
Awesome @designsimply . :)
Agree, i'll  search the file with the exact and text and after that i will make sure i'm on the right file.

I believe it was documented here https://wpcalypso.wordpress.com/devdocs/client/blocks/checklist/README.md?term=checklist
@SnGrimes
