### ISSUE TITLE
Community Translator: cannot re-enable translator

### ISSUE THREAD

**Issue by jsliang** [Automattic/wp-calypso#25297]
**Steps to reproduce**

1. Make sure "Enable the in-page translator where available" is checked in account settings: https://wordpress.com/me/account (The "Interface Language" must not be "English" for this check box to appear)
2. Open https://wordpress.com/themes
3. Enable Community Translator for the first time by clicking on the community translator button at the bottom right corner
4. Observe that translatable texts are highlighted
5. Disable Community Translator by clicking on the community translator button again
6. Enable Community Translator for the second time by clicking on the community translator button again
7. Observe that translatable texts are not highlighted anymore

**What I expected**

Community Translator can always be re-enabled.

**What happened instead**

Community Translator is enabled just for the first time.

**Browser / OS version**

Browser: Version 66.0.3359.181 (Official Build) (64-bit)
OS: macOS 10.12.6

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
