### ISSUE TITLE
Domain Management: phone input is not consistent with Calypso design elsewhere

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2535]
Raised by @allendav 

In the Domain Registration Details form, the phone prompt is a single field:

![screen shot 2016-01-17 at sun jan 17 10 51 51 am](https://cloud.githubusercontent.com/assets/1119271/12378365/156b95be-bd09-11e5-80d2-681055395406.png)

In the Two-Step Authentication setup at `/me/security/two-step`, the phone prompt is two separate fields:

![screen shot 2016-01-17 at sun jan 17 10 52 57 am](https://cloud.githubusercontent.com/assets/1119271/12378372/3d4dfa36-bd09-11e5-81ef-17eff229c57c.png)

Let's choose one or the other. (Note: We might need to have them separate in order to continue to be able to check for SMS support for a country. Also note: We decided in 4618-gh-calypso-pre-oss not to expect users to know their country code.)

Comment from @beaulebens 

> It might be worth looking at the overall design of the first form there as well -- while being compact looks nice visually, it's completely different to every other form in Calypso, and the change in labeling in particular concerns me when compared with other forms that we're training people to use.

Comment from @mattmiklic 

> Agreed on this. The compact layout is definitely nice-looking but I share the concerns about the label treatment that's unique (as far as I know) to this section.

Comment from @breezyskies 

> Just chatted with @stephanethomas in Slack about this, we're going to update this form to the newer Calypso field styles. 

Comment from @folletto 

> For the country code dropdown, we could actually use a mixed dropdown approach that would optimize for space AND understandability, like this quick mockup:
> 
> ![screen shot 2015-05-28 at 15 47 59](https://cloud.githubusercontent.com/assets/4389/7862925/04c5fb98-0551-11e5-8991-0ea9a473bd10.png)

Comment from @scruffian 

> We should also allow users to enter their country code manually if they know it.

Comment from @breezyskies 

> Just noticed that [Stripe's checkout widget](https://stripe.com/docs/checkout) uses a really nice combination of input masking, auto-detection, and country flag icon for handling international phone number inputs:
> 
> <img src="https://cloud.githubusercontent.com/assets/3011211/7890075/32b26bdc-0609-11e5-8a6c-e4332c6b7bf3.png" width="300">
> 
> Downside is that if the auto-detection is wrong, there's no helper like the one shown in @folletto's mockup above (although maybe that could be tied to the icon).

**Comment by drw158** [comment]
I think we should be able to build something smart like the Stripe input field. It could be flexible to allow different formats, or auto format. Also, a nice placeholder would help. Perhaps this component can help as well:

https://elements.polymer-project.org/elements/gold-phone-input?view=demo:demo/index.html&active=gold-phone-input

**Comment by klimeryk** [comment]
Just noting that since we now require the users to provide a phone number with a country code (requirement from our registrar), it might be worth revisiting this issue. At least to see if it's a pain point for users trying to finish signup.
Right now, it's a simple input field with no indication what's the format of the phone number we require:
![2016-05-24-013901_522x180_scrot](https://cloud.githubusercontent.com/assets/3392497/15488491/1d4b41aa-2157-11e6-87a1-8c1766edfefd.png)
We, of course, provide a validation error if the user gets it wrong:
![2016-05-24-013813_530x198_scrot](https://cloud.githubusercontent.com/assets/3392497/15488497/2c3994fa-2157-11e6-8b59-620a82a0bc8d.png)
but it'd be best to give them some hints before they try to input the phone number. Maybe for now, a different placeholder (with an example phone number) would be enough?

/cc @breezyskies

**Comment by breezyskies** [comment]
> but it'd be best to give them some hints before they try to input the phone number. Maybe for now, a different placeholder (with an example phone number) would be enough?

We now have a country code select component that we should probably include here (also used in the 2fa flow shown above), which would solve the validation issue.

**Comment by alexjgustafson** [comment]
I've had a couple chats where users found the current validation error confusing, not able to add the phone number such that the form would validate without assistance. 

It may be a small scale and I just happened to get those chats - but are we tracking how often that validation code fires, @klimeryk ? If it's causing some people to not continue with the domain registration it may even be impacting revenue.

**Comment by klimeryk** [comment]
@alexjgustafson maybe it was the same issue as #5531?

As for the country code select - true, I've even tried to use it in this form. However, there's a problem - we populate the phone input field with the value from the previous checkout. And there's no strict format here, it can be `+1.123.123.123` or `+1123123123` - how do we know what's the country code and what is the rest? We can't exactly put the whole phone number in the input field (and cause a validation error) because that would confuse the user even more. I think a solution that is contained to only one input field (like the Stripe on) would solve this problem without introducing a different issue. But I'm definitely open to suggestions/brainstorming.

**Comment by alexjgustafson** [comment]
Even if the formatting isn't strict (like dots or no dots in your example) , I think showing an example with a full number may be less confusing. In my chats the underlying confusion seemed to be with people that aren't used to thinking about country codes, so when they see...

> (e.g. +1)

...that message doesn't really conjure up what to change because they don't normally think about dialing +1 if they never dial international numbers.

So perhaps...

>(e.g. +1.555.867.5309)

...may help those few get over the hurdle. 

It may also be such a small issue it's not worth much change. :) I happened to have a few chats about it and thought I'd check in.

**Comment by klimeryk** [comment]
That's a very good point and suggestion, @alexjgustafson. It definitely makes the more sense than just listing the country code. If no one else has any objections, I can easily change the validation message to this. I was concerned that the format +1.123.123.123 is US-specific and in other parts of the world the phone format might be different, but that's what we have i18n and translators for :)

**Comment by mattm** [comment]
With the current validation rules, if you use the example placeholder text (+1.555.867.5309) it shows an error:

![screen shot 2016-12-06 at 1 40 06 pm](https://cloud.githubusercontent.com/assets/44436/20938557/85d7dace-bbb9-11e6-9144-004a66726eed.png)

![screen shot 2016-12-06 at 1 38 39 pm](https://cloud.githubusercontent.com/assets/44436/20938493/52b7e09e-bbb9-11e6-94db-87ec78be447e.png)

**Comment by klimeryk** [comment]
The new phone input has been A/B tested (results can be seen at `p6qnuF-44e-p2`) and deployed and is currently in use in the Domain Contact Form during checkout. It has been battle-tested and seems to be a great improvement over our previous approach.
There's an example at https://wpcalypso.wordpress.com/devdocs/design/form-fields (see `Form Media Phone Input`) and, of course, in the [Domain Contact Form](https://github.com/Automattic/wp-calypso/blob/bcfcd043f408fba817c47a7a68afca318582a48c/client/my-sites/upgrades/checkout/domain-details-form.jsx#L344).

Maybe we should switch to this field for two other usages of `form-phone-input`?
[client/me/security-account-recovery/edit-phone.jsx](https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/me/security-account-recovery/edit-phone.jsx) and [client/me/security-2fa-sms-settings/index.jsx](https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/me/security-2fa-sms-settings/index.jsx). Not sure who's responsible for those, so pinging people from the history of those components that might have a clue: @southp, @aduth :crossed_fingers:

**Comment by southp** [comment]
@klimeryk Those two are all mine. Thanks for the heads up 🙇🏻
I'm afraid I wouldn't have much bandwidth for addressing this, but will certainly keep it on my radar.

**Comment by klimeryk** [comment]
Hah, nailed it! 💪 That's cool (it did take us quite a lot of time to roll it out in Domain Management). Do you want to keep this issue open (maybe with different labels?) or will you keep track of it somewhere else?

**Comment by southp** [comment]
I've opened a new issue to track it: #15538 so we can leave this one close in peace :)

**Comment by klimeryk** [comment]
Awesome, thanks! 👍
