### ISSUE TITLE
Purchases: Expired Credit Card Warning doesn't persist to manage purchases

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#2540]
If a user has a credit card on file that expires soon, they see this warning:
![screen shot 2016-01-15 at 2 23 45 pm](https://cloud.githubusercontent.com/assets/8921630/12398989/384a7c94-bdcc-11e5-92e0-d362cba1c342.png)

If they click this item, the warning goes away:
![screen shot 2016-01-15 at 2 23 53 pm](https://cloud.githubusercontent.com/assets/8921630/12399003/4467dfee-bdcc-11e5-80d4-e0d59b516e3a.png)

The warning should probably persist and guide them to update the credit card either in addition or instead of "Renew Now"

**Comment by fabianapsimoes** [comment]
cc @mikeshelton1503 in terms of how to incorporate that warning to Manage Purchase.

**Comment by mikeshelton1503** [comment]
I feel like I remember that error messaging working (displaying on the manage purchase screen) at some point, but apparently not any more :).

The original prototype has it like this:

![image](https://cloud.githubusercontent.com/assets/12596797/14047408/12ed28ca-f27e-11e5-80e9-5847a3bf0744.png)

This notification should replace the " ...will expire and be removed ..." notification since in the case of an expiring credit card that is the most important issue to be resolved.
