### ISSUE TITLE
Customizer: Simple Payments Widget does not work on WP-Admin's Appearance > Widgets interface.

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#25576]
The Simple Payments Widget customizer form does not load correctly on _Appearance > Widgets_.

![screen shot 2018-06-18 at 22 45 08](https://user-images.githubusercontent.com/233601/41571668-9a4cecc0-734a-11e8-965a-e42410b50b34.png)

**Comment by Copons** [comment]
As far as I can see, there are two main reasons why this doesn't work:

- The `customizer.js` is only enqueued in the Customizer (easily fixable).

- The widget events (such as `widget-added`, `widget-synced`, and `widget-updated`) are not triggered in the Widgets page, or are not triggered with the same frequency as in the Customizer.

Now, this second reason is quite a problem.
Maybe it's worth refactoring `customizer.js` so that it doesn't use any custom events, but instead relies heavily on jQuery's event delegation to target dynamically added elements? 🤔

**Comment by rodrigoi** [comment]
> Maybe it's worth refactoring customizer.js so that it doesn't use any custom events, but instead relies heavily on jQuery's event delegation to target dynamically added elements?

we rely on those customizer events to handle the media library and we'll need them (in particular `widget-updated` to improve the handling of enable/disable states on form elements. Even if we remove all the event delegation for components, we'll still need them.
Do we have alternative events while on the Widgets interface?

**Comment by Copons** [comment]
> Do we have alternative events while on the Widgets interface?

So, I'm not an expert of this kind of things, but (one of) the major pain point is that `widget-sync` apparently never triggers in the Widgets page, but I have no idea if we've got alternatives there.

One passage I'm lost in the widget code, is how we fill the Edit Button form with the button data.
I thought we fed it via the `$instance` variable, but that's not the case, and I'm frankly lost at that point. 😄 
Maybe if I get unstuck there I can keep trying with workarounds. 🤔

**Comment by Copons** [comment]
@rodrigoi Considering that we're close to the JP deadline, I've opened a PR that (hopefully temporarily) hides the create/edit buttons in the Widgets page: https://github.com/Automattic/jetpack/pull/9811

I think we shouldn't pursue the usual quick and dirty workaround here just to ship on time, but instead we should try and figure out the best way to solve this issue once and for all.

**Comment by gwwar** [comment]
@Copons Maybe let's get a post up asking for opinions/options. If we feel like a proper solution won't make it in time, we can try using the temp fix for this release, and aim for a proper fix on this issue for the one after.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
