### ISSUE TITLE
Page List: Changes appearance before pages can be edited 

### ISSUE THREAD

**Issue by sashastone** [Automattic/wp-calypso#25646]
#### Steps to reproduce
1. Starting at URL: https://orangemarmaladebooks.com/
2. SU as user and click on Pages: https://wordpress.com/pages/orangemarmaladebooks.com
3. The display will initially look like this: https://d.pr/i/OGnNue
4. After a few seconds, it will switch to: https://d.pr/i/UZrqGW
5. Pages cannot be edited until it switches to the second view.
6. I created a test site: jillbookstest08687.wordpress.com by importing the user's content.

#### What I expected

I expected the pages list to load normally. 

#### What happened instead

The pages list loaded abnormally, with same issues the user is experiencing. 

When first loading: https://d.pr/i/JAL1Zm
After a few seconds: https://d.pr/i/UZrqGW

#### Browser / OS version

My browser: Chrome
My OS version: 10.13.5

#### Screenshot / Video

See above.

#### Context / Source

The user's pages have many many links to their blog posts. They don't experience this issue with their blog post list in Calypso, only with Pages.

Additional issues from the user that I was not able to reproduce on my test site: 

```
Yes, I only see the slow down when editing the pages, not just loading them. Although if I try to bring up several pages in different tabs simultaneously, it wonks out. When I try to add links, I notice it especially. If I highlight something and click on the link button, it takes a long while for the links in the pop-up box to include my most recent post, for example, or if I search in that box with a term, it takes a long time to bring up the options for linking. It does that for every single item I try to link.

I haven't noticed any slow downs happening when working on a post. Only on the pages.
```

**Comment by sashastone** [comment]
Related ticket: https://woothemes.zendesk.com/agent/tickets/1230604

**Comment by sophiegyo** [comment]
User in 1230604-zen came back with further details:
http://supportdetails.net/7OS1CWW5
Summary - Chrome 67.0.3396.87, Mac OS, 1280 x 800 resolution, JavaScript enabled.

I have also experienced this on various sites recently when helping users.  Site page list first loads in reverse-chronological order of creation, then switches to a more standard view.  This can take a longer time depending on how many pages and child pages there are.

Recent example is: thetrialsandtribulationsofparenthood.co.uk

SSP as user, visit https://wordpress.com/pages/thetrialsandtribulationsofparenthood.co.uk
The display will initially look like Sasha's screenshot: https://d.pr/i/OGnNue
After several seconds, it will switch to Sasha's second screenshot: https://d.pr/i/UZrqGW

**Comment by sophiegyo** [comment]
#1272597-zen
I have another user who is experiencing a different issue with Calypso, but I suspect it may be related.  Noting here, because when SU or SSPing into their site, I experience the page structure issue.

Site: irada.com
SU as user and click on pages: https://wordpress.com/pages/irada.com
The site will initially have a list of the pages, in reverse chronological order of publishing, before switching to the parent/child structure. It seems as if I actually need to scroll down and up the page to trigger the parent/child structure kicking in.
Screencast demonstration here: http://cld.wthms.co/0LTXgE

Of note - it IS possible to enter into any one of the pages to edit them prior to the parent-child structure kicking in.

Tested as SU in Google Chrome 67.0.3396.99 and SSP in Firefox 60.0.2 

The user originally came to us with a possibly-related issue.  When attempting to use the "switch to a better experience" Calypso link in wp-admin (the "calypso-nudge" link) the user sees that the Calyspo "background" loads, but no page content does.  They also experience this when attempting to load wordpress.com/help/contact/.  They have recorded a demonstration of this, which they linked to in their ticket.
