### ISSUE TITLE
Themes: Add page title to logged-out masterbar

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#2567]
<img width="288" alt="screen shot 2016-01-19 at 11 56 13" src="https://cloud.githubusercontent.com/assets/7767559/12417947/b3ff50c6-bea3-11e5-9267-aea03bb7ef02.png">

Show on mobile as well.

**Comment by ehg** [comment]
Noting that implementing this will cause a change in the text for non-english languages, since we don't handle i18n on the server-side yet.

**Comment by ehg** [comment]
> Noting that implementing this will cause a change in the text for non-english languages

Actually, I think it will just render as english no matter what.

**Comment by folletto** [comment]
It's ok either way, since "theme" is a sort of "sub-brand" title in that instance (i.e. like the URL).

**Comment by hugobaeta** [comment]
Just a small note on the usage of the WordPress.com logo, the screenshot above has a bad version of the logo (W icon + text). The WordPress.com logotype should always be treated as it's own element (not W + text). You can find the logos and the guidelines for use here: https://wordpress.com/design-handbook/logotype/  (we also have guidelines for how to treat the "Themes" title in there) ;)

**Comment by folletto** [comment]
You're right, thanks for pointing that out. It's currently following the latest masterbar blueprint which aren't aligned to the mark. Let's update that so we have a guideline for all our pages :)

**Comment by folletto** [comment]
Updated design: 

![screen shot 2016-03-02 at 12 52 44](https://cloud.githubusercontent.com/assets/4389/13460850/b638ed86-e075-11e5-82fc-39221e7425f7.png)

![screen shot 2016-03-02 at 12 53 37](https://cloud.githubusercontent.com/assets/4389/13460860/ce240a8e-e075-11e5-964c-5ff9a935fb6c.png)

* Desktop size: it uses the entire "(W) WordPress·com" logo, instead of composing W + text.
* Mobile size: just the (W)
* The page title is uppercase, aligned optically to the lowercase "com"

**Comment by seear** [comment]
Done in #5016
