### ISSUE TITLE
Activity: remove Jetpack Search banner on free sites

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#25705]
Currently on free sites, the Activity section already has an update nudge.

We should conditionally display the banner Jetpack Search, so that it doesn't show up at the same time as existing Activity nudges.

![screen shot 2018-06-22 at 12 10 01 pm](https://user-images.githubusercontent.com/390760/41791298-43dd86dc-764d-11e8-99a6-d61e1363bdab.png)

**Comment by roccotripaldi** [comment]
This may be resolved now. I cannot get this banner to appear, nor can i find reference to it in the code.

**Comment by roccotripaldi** [comment]
I found it - the logic is not on calypso but on wpcom, working on a fix!

**Comment by roccotripaldi** [comment]
Good points @gibrown 

We are limited on what we can do here by the fact that Activity Log is in the stats section, and this particular JITM is tied to the stats section.

A couple of ideas based on this limitation:

1) we could hide the Search banner for all free sites
2) we could move "Activity Log" to its own section

I'm not crazy about option 1, because it would stop us from showing off one of Jetpack's coolest features for free sites that could benefit from them.

Option 2 makes more sense. We've got a lot of push back to put Activity Log in its own section, and mobile is treating it as such.

With it's own section, the Activity Log could be free of stats-related banners, and have it's own JITM logic.

what do you think @keoshi

**Comment by annezazu** [comment]
@keoshi I would loop in the expert @tmmbecker who runs our documentation efforts. Happy to help in whatever way needed to!

**Comment by roccotripaldi** [comment]
PR to hide on free sites: D17220-code

And a p2 post checking with marketing: p5uIfZ-8y9-p2

**Comment by roccotripaldi** [comment]
This should be fixed as of https://github.com/Automattic/wp-calypso/pull/26941
