### ISSUE TITLE
"Open Live Demo" button on Theme Details page on mobile difficult to find/read

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25720]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/twentyfifteen/yoursite.com (for any theme) on mobile width

#### What I expected

The "Open Live Demo" text to be prominent - it blends in and is hard to read - I think this used to be centered over the image - in some cases (see below) it's not visible at all

#### Browser / OS version

Tested Chrome on MacOS

#### Screenshot / Video

<img width="416" alt="screen shot 2018-06-25 at 2 49 16 pm" src="https://user-images.githubusercontent.com/128826/41830936-55d2fcb4-7887-11e8-96a1-1653f9dbbeb1.png">

![failed-en-mobile-can-see-theme-details-page-and-open-the-live-demo-1529901148106](https://user-images.githubusercontent.com/128826/41830940-5ed6644a-7887-11e8-905a-5a96295e7a35.png)

#### Context / Source
Found by  #automated-testing failing on this screen

**Comment by keoshi** [comment]
Assigning this to you, @folletto, but let me know if you want me to tackle it.

**Comment by folletto** [comment]
> I think this used to be centered over the image

It was always meant to be below, to make use of the fade out. :)

—

Is this an issue that was raised as an actual issue, or something we noticed ourselves? I'm asking as knowing exactly what was the issue raised will help identifying the right design. I'm saying this mostly because that label was designed as "low priority" as the screenshot being tappable should be an action most users would do regardless, and the text has been added for accessibility reasons

Overall, I think one action we could take regardless is to fix the contrast of the button, as it was made when Calypso colors were still in flux, and right now we resolved with higher-contrast text colors.

**Comment by keoshi** [comment]
> the screenshot being tappable should be an action most users would do regardless

FWIW, I hadn't noticed it was clickable myself until I read your comment.

**Comment by alisterscott** [comment]
> Is this an issue that was raised as an actual issue, or something we noticed ourselves?

Our automated e2e tests used to be able to click this button until some point it became not present so it can't be clicked (our tests retry so it's not always an issue)

> screenshot being tappable should be an action most users would do regardless

I've updated our e2e tests to do this instead, however, as @keoshi points out I'm not sure myself that is obvious, that is why I thought it was an overlay to the screenshot to indicate this - maybe it was never like this and I imagined it - if so, we can either close this or keep the priority low

**Comment by folletto** [comment]
> Our automated e2e tests used to be able to click this button until some point it became not present so it can't be clicked

Yep the "not present" part seems a bug for sure, and should be fixed. I'm not sure who could look into that tho.

As for the button, we could at the very least fix the contrast to gray text min ;)
