### ISSUE TITLE
Bug: check-node-version: Permission denied (dual boot problem)

### ISSUE THREAD

**Issue by ianchanning** [Automattic/wp-calypso#2573]
**I'm not expecting a fix to this - but as I found zero google results, I'm adding one.**

I'm pretty sure this is just due to me trying to install and run calypso on my windows share when in Linux Mint that's in a dual boot setup.

The executable permissions to run `check-node-version` can't get set because the files are installed on a Windows NTFS share. i.e. `chmod +x check-node-version` has no affect.

So you can't execute the files in the bin directory.

URL: 

N/A

What I expected: 

`make run` to complete successfully

What happened instead:

```
/bin/sh: 1: [path to calypso]/bin/check-node-version: Permission denied
make: *** [node-version] Error 126
```

Steps to reproduce:

1. Dual boot Windows and Ubuntu (Linux Mint)
1. Mount the Windows share e.g. `/media/[username]/Windows8_OS/`
1. Run the following commands:
```
$ cd /media/[username]/Windows8_OS/
$ git clone git@github.com:Automattic/wp-calypso.git calypso
$ cd calypso
$ make run
```

Browser OS version:
Linux Mint 17.2 64-bit

Screenshots/Video: 
This is the bin directory where none of the files have exec permissions (the `v` directory is just a symlink to the www directory on my Windows share):

![screenshot from 2016-01-19 14 47 19](https://cloud.githubusercontent.com/assets/233318/12420258/d9d59a9a-bebb-11e5-874f-0848a0fb67cd.png)

**Comment by klimeryk** [comment]
I'd wager this more of a problem with how you mount your share. NTFS does in fact support [setting (amongst others) the executable permission](http://askubuntu.com/a/74851) - please try mounting it with the right permissions.
This probably could be fixed at Makefile level (using `node path/to/script` instead of `path/to/script`), but I'd prefer to avoid that. Right now, the `check-node-version` is a node script, but if it changes to `bash` or `sh` for some reason, the Makefile would need to be changed too. Relying on the shell and the `#!/bin/whatever` at the beginning of the script seems more robust to me.
We also have a [PR for adding "native" (using MSYS2) support for Windows](2124) - please check it out (and test it! :grin:) if that's something that interests you.

Side note: I'd recommend against using NTFS (especially on a share) for developing, for performance reasons. `ext3/4` (and basically any other *nix filesystem) is so much better at handling a large number of small files (like the numerous `*.jsx` files we have, or the `node_modules`) than NTFS.
