### ISSUE TITLE
Incorrect UI after Removing Jetpack Plan

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#25869]
To replicate:

1. Remove a Jetpack plan from https://wordpress.com/me/purchases
2. Head back to the site where you removed the plan
3. You'll get this screenshot:

<img width="1360" alt="screen shot 2018-07-04 at 10 50 08 am" src="https://user-images.githubusercontent.com/26996883/42288497-1fc412d2-7f78-11e8-9638-5b5cb418b8d9.png">

Of note, it's telling me I have a paid plan while also telling me to upgrade and notifying me my plan has been removed. 

No errors in JS console.

**Comment by annezazu** [comment]
Here's a video of the weirdness. I seem completely stuck in this state even after refreshing the page: 

https://cloudup.com/c0W86xd2kKn

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
Ran a quick test, cancelling & removing my Jetpack Premium plan via WordPress.com/me/purchases, then checking https://wordpress.com/plans/my-plan/SITE_ADDRESS for the self-hosted site that plan was on, and I see the expected Free plan:

![Markup on 2023-08-17 at 15:18:34](https://github.com/Automattic/wp-calypso/assets/27249804/a41ee19f-ae17-4c26-81d6-a3fe6f23106b)

Likely this is also resolved 👍
