### ISSUE TITLE
Signup: Unable to proceed at last step

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#25886]
This issue is not reproducible each time, here are approximate steps:
1. Sign up at wordpress.com/start
2. Go through signup (I chose porfolio, a .wp.com address, and a free plan)
3. See message that things are being set up in the background
4. See button that asks me to continue
5. See that button doesn't work, and see this error message:
```
Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://valtest20180705.wordpress.com/' cannot be created in a document with origin 'https://wordpress.com' and URL 'https://wordpress.com/start/user'.
```
Apologies, I don't have screenshots or more detailed info!

This is not reproducible every time I sign up, maybe it's an A/B test?

@gwwar is thinking maybe we're using page.js instead of a normal link.

**Comment by gwwar** [comment]
Reading the code, on the processing screen was pass through a click handler:

https://github.com/Automattic/wp-https://github.com/Automattic/wp-calypso/blob/6a31cd6eddd23f83bcf2f822397b2ce55126e507/client/signup/processing-screen/index.jsx#L271
```jsx
					{ this.props.loginHandler ? (
						<Button className="email-confirmation__button" onClick={ this.props.loginHandler }>
							{ translate( 'View My Site' ) }
						</Button>
					) : (
						<Button disabled className="email-confirmation__button">
							{ translate( 'Please wait…' ) }
						</Button>
					) }

```

Tracing this back further:
We pass through 
```jsx
<SignupProcessingScreen
						hasCartItems={ this.state.hasCartItems }
						steps={ this.state.progress }
						loginHandler={ this.state.loginHandler }
```
https://github.com/Automattic/wp-calypso/blob/6a31cd6eddd23f83bcf2f822397b2ce55126e507/client/signup/main.jsx#L490

Which if we follow that, internally calls `handleLogin`:
https://github.com/Automattic/wp-calypso/blob/6a31cd6eddd23f83bcf2f822397b2ce55126e507/client/signup/main.jsx#L322
```jsx
	handleLogin = ( dependencies, destination, event ) => {
		const userIsLoggedIn = this.props.isLoggedIn;

		if ( event && event.redirectTo ) {
			destination = event.redirectTo;
		}

		if ( userIsLoggedIn ) {
			// deferred in case the user is logged in and the redirect triggers a dispatch
			defer(
				function() {
					page( destination );
				}.bind( this )
			);
		}
//...
```

If we're attempting to navigate outside of the current origin of say WordPress.com, it's problematic to use page.js (page( destination )). The browser history API will complain because we're only allowed to push history state on the same origin for security reasons.

https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method

**Comment by meremagee** [comment]
Caught this one today as well! 
Chrome Version 67.0.3396.99 (Official Build) (64-bit). Console for your viewing pleasure:

![](https://cloudup.com/cR0ILDt8VcJ+)

**Comment by mattwiebe** [comment]
This reminds me of an old classic #908
