### ISSUE TITLE
Jetpack Checklist: Guided Tour positioned below wrong setting card

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#25933]
Reported by @joanrho (https://github.com/Automattic/wp-calypso/pull/25864#issuecomment-402917465):

> I'm seeing a bit of wonkiness with the positioning of the guided tour: I haven't set up Backups and Scanning for this particular test site yet, so the guided tour bubble landed on the Spam Filtering card. Would it be possible to change that so that it affixes to the Sign-in card instead? I believe this happened for a previous tour we worked on...did you resolve that by specifying the class name or something?

Confirmed by other testers in Slack. Seems to depend on whether backups (Activity Log/Rewind) have been set up for a site, and the corresponding 'Backups and Scanning' setting card on that page loads with a slight delay.

**Comment by simison** [comment]
I take that this is already fixed?

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
