### ISSUE TITLE
Jetpack Checklist: Center Guided Tour bubble arrow below toggle

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#25932]
From https://github.com/Automattic/wp-calypso/pull/25864#issuecomment-403010913:

> Guided Tours positioning is based on element selectors (`.sso__card .form-toggle__switch`), and some more 'qualitative' args (`arrow="top-left"`, `placement="below"`). You'd think that'd do a better job:
>
> ![position](https://user-images.githubusercontent.com/96308/42377224-bc50cedc-8122-11e8-8938-5130e71b8978.png)
>
> Maybe I can use the additional `style` arg to tweak this...

https://github.com/Automattic/wp-calypso/pull/25864#issuecomment-403491732:

> Unfortunately it doesn't seem like an easy problem to fix because as @ockham mentions, its position is calculated from the picked selector, so the `left` values you're seeing @joanrho are generated dynamically and change depending on the screen resolution you use.
>
> `transform: translateX(-16px)` would be ideal here but doesn't work because it has a `fixed` position.
>
> `margin-left: -16px` seems to do the trick, but it's not pretty at all.

**Comment by jeherve** [comment]
This also happens for plugin autoupdates:

![image](https://user-images.githubusercontent.com/426388/69658761-15bebe80-107d-11ea-8e89-8271a1aa79f6.png)

This is on Mac OS Catalina with Chrome Version 78.0.3904.108.

Reported in p8oabR-qW-p2#comment-3592

**Comment by davipontesblog** [comment]
Moved to Jetpack Improved Onboarding for triaging.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
