### ISSUE TITLE
Activity: link all activities to objects that have an interface in Calypso

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#26016]
Similarly to what we do with Posts, other objects that have an interface in Calypso should also be linked on the Activity log.

These should be linked to their editing interface (as opposed to Reader in the example of Posts).

This includes:

- Posts
- CPTs
- Comments
- Attachments/Media
- Settings
- _and more..._

As an example, see this reference for the difference in treatment to Posts and Pages:

![image 1](https://user-images.githubusercontent.com/390760/42632136-238fd25e-85d4-11e8-95d3-b0e76c13e1c6.png)

None of the CPTs appear to be linked either, looking at Testimonials:

![image](https://user-images.githubusercontent.com/390760/42633185-8e3f2192-85d7-11e8-93ee-0969a895830f.png)

**Comment by roccotripaldi** [comment]
Ultimately we wan these to link to the editor interface, right?

Right now, we are linking to the reader. While testimonials and pages are technically viewable in the reader, we don't expose them there. So we made a choice to include links for posts.

**Comment by keoshi** [comment]
> Ultimately we wan these to link to the editor interface

Exactly. Let's link all of them to their editing interface. This is an admin take on your site's pulse, so it makes sense that they link to content editing rather than consumption UIs.

**Comment by MichaelArestad** [comment]
Here an initial list of the top events from most common do least:

- [ ] `post__updated` - Link to post in Calypso editor on the <post title>
- [ ] `user__failed_login_attempt` - I am not sure we can or should link to anything here.
- [x] `rewind__backup_complete` - No link needed.
- [ ] `post__published` - Has link, but needs to point to the editor instead of the reader view.
- [ ] `plugin__update_available` - Has link in both the nudge at the top and the event. (We might want to make the text blue in the nudge [shown here](https://user-images.githubusercontent.com/1123119/43540311-9a6bc68e-9584-11e8-9077-de80dbd3e775.png) to indicate it is a link.)
- [ ] `comment__published_awaiting_approval` - Change to link to individual comment in Calypso (rather than the post).
- [ ] `monitor__site_down` - Link to the site
- [ ] `monitor__site_up` - Link to the site
- [ ] `comment__published` - Change to link to individual comment in Calypso (rather than the post).
- [ ] `term__created` (does not appear feed)
- [ ] `post__publicized` (does not appear feed)
- [ ] `user__login` I am unable to find these, but it's not that common of an event on my sites. We should link to each user in the People section of Calypso if it doesn't already do that.
- [ ] `theme__update-available` - Unclear if it shows up as an event in the timeline, but it does show up at the top of the Activity Log. We need to change the link to point to the theme view in wp-admin in both the event and bubbled up "Update Event". Example: `https://michael.blog/wp-admin/themes.php?theme=twentyfifteen`
- [ ] `post__trashed` - Link to trashed post in editor view.
- [ ] `comment__trashed` - Change to link to individual comment in Calypso (rather than the post).

We should tackle these in order. The Post updated event is by far the most popular event. You can see a chart linked to from here: p9rlnk-pA

I omitted the `attachment` (or media) events because they do not yet show and we will add links when we implement them in https://github.com/Automattic/wp-calypso/issues/26019

**Comment by enejb** [comment]
I am closing this for now. 
When we find other items that we want linked we should make more issues for them.
