### ISSUE TITLE
Domains: drop requirement for site name in URLs

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#2601]
@jerrysarcastic suggested in `p2MSmN-4mh-p2` that it'd be much easier/faster for Happiness Engineers to come up with a link for, say, email forwarding, if we did not require the site part (which has to be looked up manually).
Right now the required URL is `/domains/manage/:domain/email-forwarding/:site`. Usually, the HE has the domain part, while site has to be looked up. _Technically_, this lookup can be done in Calypso automatically (there's a 1:1 mapping between site and domain, AFAIK).

**Comment by stephanethomas** [comment]
> there's a 1:1 mapping between site and domain

I don't think so. For example a user could have two distinct WordPress.com blogs with both a site redirect for the same domain that is pointing to a site hosted somewhere else. I'm certainly talking of edge cases here but still we need to take them into account. It doesn't mean we shouldn't try to address this issue though - we might find a way to to work around these uncommon cases.

**Comment by klimeryk** [comment]
Ah, I see. Thanks for providing a use case that breaks my assumptions - very useful :+1: Still, like you said, something could be done to improve this situation. For example, we could show the site picker if the domain matches more than one site? Just throwing ideas around while I'm trying to triage these domains-related issues :)

**Comment by stephanethomas** [comment]
I know that we've been avoiding this site picker lately. I think it's time to ping @breezyskies or @mikeshelton1503 to get their feedback on this issue.

**Comment by umurkontaci** [comment]
I don't see this happening in the near future. The reason is domain data is fetched per site, after getting a list of sites of user. In order to be able to make the mapping work, we'd have to get the domain details of all sites first, which is not going to happen for performance reasons.

However, there's a neat undocumented trick which can be used for these cases. The site matcher accepts site id instead of slug as well.

So this works: /domains/manage/:domain/email-forwarding/:site_id
