### ISSUE TITLE
Checklist guided tour doesn't disable buttons on Personalize Contact page 

### ISSUE THREAD

**Issue by mel-OR** [Automattic/wp-calypso#26101]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checklist/siteurl.wordpress.com/checklist/:site:
Signed up for a free account. 
2. Click "Do It!" to Personalize your Contact page
3. Once the contact page opens, note that Update button looks enabled. Click on it.

#### What I expected
The Update either happens, or is disabled until all guided tour popups are dismissed. Maybe see this part of the tour (if image and page was done in the expected order, this is what you see):
![screen shot 2018-07-16 at 8 20 46 pm](https://user-images.githubusercontent.com/28070750/42794813-d287a73c-8935-11e8-8687-ba94796b1004.png)

#### What happened instead
Nothing. Clicking the update button didn't save the page or move me to the next guided tour modal.

#### Browser / OS version
Chrome 67.0.3396.99 
Mac OS 10.13.6

#### Context / Source
#manual-testing
#Idontfollowdirections

**Comment by lancewillett** [comment]
Thanks for the report, Melissa -- good find.

**Comment by fditrapani** [comment]
Pinging @taggon. Can you take a look when you have a chance?

**Comment by rantoncuadrado** [comment]
User in 1341800-zen reported this.

**Comment by ramonjd** [comment]
After some investigation I think it's borking [in the save post action](https://github.com/Automattic/wp-calypso/blob/master/client/state/posts/actions.js#L672). 

We don't send a request to the API and return `null` if the post is unchanged. It's still treated however as a successful save and `null` is therefore passed to the [success callback](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/post-editor.jsx#L717), the effect of which, is... well... `null`. :)

I'll look further.

**Comment by adamziel** [comment]
@ramonjd I think we should dismiss the checklist item and leave the "Update" active. If we disabled the button it may cause some confusion: "Hmm Update button is this disabled, that's weird. I probably can't edit this post for some reason, maybe something's not working properly?"

**Comment by niranjan-uma-shankar** [comment]
> 3. ??

Going back to the suggestion made by OP, I like the suggestion to show a modal that asks the user to continue with the checklist instead of just dismissing it.

![42794813-d287a73c-8935-11e8-8687-ba94796b1004](https://user-images.githubusercontent.com/1269602/47555556-bb0edc80-d929-11e8-84ef-92bcc06288b9.png)

I like this suggestion because:
(1) It gives a nudge to the user to proceed to the next items in the checklist. 
(2) It is inline with how the guided tour operates in other parts of the checklist. For example, if I add a site tagline, then I see this:

<img width="469" alt="screen shot 2018-10-26 at 2 20 38 pm" src="https://user-images.githubusercontent.com/1269602/47555803-5ef88800-d92a-11e8-9541-ed0a41c1dee7.png">

Thoughts?

**Comment by ramonjd** [comment]
> asks the user to continue with the checklist, instead of just dismissing the tour modal.

Good suggestion. I actually wanted to implement this when the update was _successful_, but in my mind the logic needed some more fundamental fine-tuning. I can't get past the idea that returning `null` and an implied success to a user update action, when no update has occurred is misleading.

It would be useful in another PR to go to automatically skip to next step after a **real**, successful update. I did play with that option using `nextGuidedTourStep( { tour, stepName } )` (the tour step names must be explicitly set), but because of the above reasons, it added too much noise to the initial task.

It would be useful however to iterate using your ideas here. 👍
