### ISSUE TITLE
Activity Log: add an unavailability notice for Jetpack sites on a free plan

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26184]
Currently, for wordpress.com sites on a free plan, we show this notice:

<img width="1063" alt="screen shot 2018-07-18 at 9 45 55 pm" src="https://user-images.githubusercontent.com/2694219/42916585-05f751b8-8ad4-11e8-843d-1b1ee35d4c7f.png">

And for for Jetpack sites where Rewind is available, we have:

<img width="1071" alt="screen shot 2018-07-19 at 10 03 11 am" src="https://user-images.githubusercontent.com/2694219/42947276-04872d6e-8b3b-11e8-858b-ab615b844daa.png">

We need a third banner for Jetpack sites where Rewind is not available:

Here is the proposed copy:

`Upgrade to get all of Jetpack's essential features including more detailed activity logs.`

For the wpcom banner, i'd propose we change:

`See 30 days of past activity`

To:

`More detailed activity logs`

**Comment by roccotripaldi** [comment]
@keoshi - i've updated this issue with some proposed copy.
What do you think?
Should we ping folks from editorial?

**Comment by gititon** [comment]
@roccotripaldi It's a good improvement on what we had, but I don't think `More detailed activity logs` sufficiently communicates that they won't just see more details in the log items they already see, but will see many more log items.

**Comment by roccotripaldi** [comment]
Agreed @gititon - we can track your 2nd point here: #23925

**Comment by roccotripaldi** [comment]
After pawing around in the code, I noticed that you can not highlight Jetpack Essential features on a Jetpack site, so I instead opted for daily off-site backups.

It's all there in #26197 !

**Comment by gititon** [comment]
> Agreed @gititon - we can track your 2nd point here: #23925

Unfortunately this might still leave people confused, @roccotripaldi , since if they change a decent amount of Jetpack settings, their very first activity (the "end" of their Activity Log), which I understand #23925 contemplates to be a message indicating they aren't seeing all of their activity, may be pushed onto the second page or further. In that case, users will not see it when they visit their Activity Log unless they advance to the second page or further to review old settings changes.

If we're going to show users only a fraction of their activity in the "Activity Log", I think it needs to remain clear why they aren't seeing their activity there, i.e. the message needs to somehow remain front and center to ensure the Activity Log provides clarity and not confusion.

**Comment by michelleweber** [comment]
Is this taken care of with the edits to the feature description in the other issue, or do y'all still need a hand here?

**Comment by roccotripaldi** [comment]
@michelleweber - we need some copy, a small line of text, that will appear at the bottom of the activity log, explaining that certain sites will only see limited activity. Something like:

`You are seeing limited activity because your site is on a free plan.`

And eventually, when we have improved our documentation:

`You are seeing limited activity because your site is on a free plan. <a>Check out our fascinating activity retention policies</a>`

**Comment by michelleweber** [comment]
Gotcha. "Since you're on a free plan, you'll see a limited number of events in your activity log."

(Super duper would be if we could be a skotch more specific, like "Since you're on a free plan, you'll only see events X and Y in your activity log.")
