### ISSUE TITLE
CSS SourceMaps busted

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#26190]
The CSS source maps for `style-debug.css` are no longer pointing back to the original sass files. Instead, they seem to be pointing to the CSS that comes out of `node-sass`.

Reported by @jancavan

**Comment by blowery** [comment]
@flootr and I have been looking at this. It appears that `postcss` isn't able to handle the sourcemap that's coming out of `node-sass`.  

If we remove `postcss` from the build chain, the sourcemap does appear to work, but we lose `autoprefixer`'s work.

**Comment by blowery** [comment]
Doesn't affect style.css and style-debug.css, but css-loader recently added some things that may help with sourcemaps there: https://github.com/webpack-contrib/css-loader/pull/901

**Comment by blowery** [comment]
Relevant PostCSS issues:
https://github.com/postcss/postcss/issues/1211
https://github.com/postcss/postcss/issues/797

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
