### ISSUE TITLE
Podcasting: Cover image doesn't render on first page load in Mobile Safari

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#26194]
For preset cover images (whether by the legacy url method, or through previous podcast testing), the cover image is blank on first load in Safari. The bug is intermittent, and goes away after resetting the cover image, but using `overflow: hidden` on the container seems to be the cause of the problem.

![9fccbcb0-d4c7-4bfa-b25e-28c7297bf3a0](https://user-images.githubusercontent.com/942359/42345728-4a1012ec-806e-11e8-82ce-5197cebcb5de.png)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
