### ISSUE TITLE
Bug: Image tags stripped from Comment edits

### ISSUE THREAD

**Issue by detlefholtz** [Automattic/wp-calypso#26315]
When editing comments via Calypso, Premium user `johnconners` found that saving an image tag within the comment will just strip it out every time. Wp-admin works fine though.

For instance, in Calypso they can’t add this tag without it getting stripped out when trying to Save:
```img alt="" src="https://johnconners.files.wordpress.com/2018/07/merdeglace1979.jpg" title=""```

That image appears here because they can still add image tags via Dashboard but try removing it and re-adding it in Calypso and it gets stripped out: 
https://johnsad.ventures/2018/07/16/visiting-the-same-glacier-22-years-apart-seeing-climate-change-in-action/#comment-79796

The problem is reproducible if you user-switch to their site. But when tested on an HE’s site — one that is using the same theme and comment settings and is on the Prem Plan — the image tag worked fine.

Ticket: 1283437-zen

While not exactly the same, this problem from back in January sounds really similar:
p1515017807000071-slack-triage

**Comment by kevmarsden** [comment]
This issue was also reported in 1370202-zen and I was able to recreate it on a test site.  

This issue only occurs when you edit a comment that was left by someone else.  If you edit your own comment, it's possible to add images.  

Also, this is an issue both when manually using`img` HTML tags and when the `img` modal is used.

**Comment by SiobhyB** [comment]
We received another report of this in 1434303-zen.
