### ISSUE TITLE
i18n: localised date formats from Moment.js have incorrect capitalization in French

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#2642]
While working on #2637, @blowery and I discovered that `this.moment` incorrectly hands back capitalized day and month names in French :fr: when using Moment.js' localised formats, `llll` and `LLLL`.

The expected output from `this.moment( date ).format( 'LLLL' )` in French is:

`jeudi 21 janvier 2016 10:35`

...and we currently get:

`Jeudi 21 janvier 2016 10:35`

The expected output from `this.moment( date ).format( 'llll' )` in French is:

`jeu. 21 janv. 2016 10:35`

...and we currently get:

`jeu 21 Jan 2016 10:35`

This suggests that the translations may be wrong for full weekdays and short month names in French.

Docs from momentjs.com:

<img width="785" alt="screen shot 2016-01-21 at 11 07 44" src="https://cloud.githubusercontent.com/assets/17325/12464726/42314660-c02f-11e5-808f-63e0127780d3.png">

cc @rralian

**Comment by lancewillett** [comment]
CC @akirk

**Comment by lancewillett** [comment]
CC @yoavf Can you take a look? Is this fixed by #2731 changes also?

**Comment by yoavf** [comment]
Not fixed by #2731, but related. Specific to this, seems like we're not loading the moment.js locale files, and instead falling back to `WP_Locale` values which are capitalized by default. Working on a fix

**Comment by blowery** [comment]
I think that fallback was on purpose, but it was so many moons ago now that I don't recall the particulars. @rralian may?

**Comment by rralian** [comment]
I don't know if this answers your question, but here are things I know. The momentjs locale object comes in as an attribute on a locale object that calypso reads from a separate url. E.g., widgets.wp.com/languages/calypso/en-gb.json. This file is generated whenever we deploy new translations for a given language.

We originally started with our own custom-built momentjs locale objects, which were pieced together from translations entered into glotpress. I made that choice because calypso and moment.js didn't have perfect overlap of supported locales and also because I (mistakenly) thought we would want direct control over the translations. @akirk had since worked on pulling in the locales from the moment.js project directly. I think he was just manually replacing the files. But I don't recall the status of that. It's possible this has just not yet been done for French.

**Comment by lancewillett** [comment]
Saw this still open during a bug scrub — OK to close now? Anything pending still? CC @hewsut

**Comment by bluefuton** [comment]
Looks like the full month names have the correct capitalisation now, but the abbreviated ones (for example, in the `lll` and `llll` formats) still have the initial capital letter:

<img width="362" alt="screen shot 2016-04-29 at 11 54 35" src="https://cloud.githubusercontent.com/assets/17325/14914395/8f941548-0e01-11e6-9b8d-e34258d2d5d1.png">

**Comment by yoavf** [comment]
Still on the radar. Our plan is to remove custom translation options and use momentjs as is (while contributing directly to it). I'll update here once we've started on this.

**Comment by kriskarkoski** [comment]
@Tug Was this resolved by #5923 (linked at bottom of #5278)?
