### ISSUE TITLE
Signup: Editor: before email activation, show accurate Publish message for new posts (draft, not publish)

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#2650]
Raised by @mjangda 

> If your account isn’t verified you can’t publish posts on WP.com. Despite this, the Calypso editor shows you a publish button and when you hit it, you get a success message saying telling you your post was published (even though it wasn’t).

UX improvement: show an accurate editor publish message when publishing to a new site, after signup, but before you've verified your email.

![screen shot 2016-01-20 at 19 54 05](https://cloud.githubusercontent.com/assets/66797/12470512/16526178-bfb2-11e5-8e3c-b6b9af447f52.png)

I tested this to confirm, with Safari 9.0.2 on OS X 10.11.2 using a a brand new user.

**Steps to repeat:**

1. Log out (or incognito) and sign up from WordPress.com
2. Without verifying your email address, go to your new site and publish a post
3. You'll see the publish message as "Post published on testeruserlance3!"
4. However, it is actually saved as a draft. You can view it, but other people without site permissions to your new blog cannot.

**Comment by folletto** [comment]
We need always to split problem and the solutions. :)

I think the problem is correct:

> Despite this, the Calypso editor shows you a publish button and when you hit it, you get a success message saying telling you your post was published (even though it wasn’t).

We wanted to avoid banners on that screen, thus not the solution above.

Instead, we should implement a message when the user clicks on Publish. 

There are multiple reasons we discussed for this:

1. The user that didn't go straight to a new post will already have seen that message elsewhere
2. If possible it's important to not split attention. We can still allow the user to write the post, complete it, draft (first focus) and then once completed and reviwed, give the message (second focus).
3. Not splitting focus also raises the motivation to complete the second action: since one has already written content and has pressed publish, which means one is ready to do that, that's the perfect moment to give a message.
4. A top banner crushes the available space, something that is already limited.

**Comment by lancewillett** [comment]
Just a note that the above screenshot isn't a proposal but the current UI flow.

**Comment by folletto** [comment]
Quick proposal for the dialog:

![screen shot 2016-01-22 at 11 57 36](https://cloud.githubusercontent.com/assets/4389/12510118/60adc4a8-c0ff-11e5-8823-d723bcfb5361.png)

Iterations on the copy are welcome.  ;)

**Comment by folletto** [comment]
Maybe it should say also something reassuring about the fact that the post is saved as draft? Or is that enough that is said in the editor and it's better to not split focus here?

**Comment by hoverduck** [comment]
21Apr16 Bug Scrub

Confirmed this is still an issue.  I was able to "Publish" a post prior to activating my account, but all that really happened was saving a draft.  Clicking "View Post" then took me to the post preview, which is further confusing because at first glance that looks like good confirmation that the post was actually published.

**Comment by folletto** [comment]
Noting that #4806 is fixing that. Testing & review needed. ;)

**Comment by lancewillett** [comment]
This is now in #5475 — follow along there. (Closing this one.)
