### ISSUE TITLE
Reader: Disable Comment Likes when they are disabled on all posts of a blog

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#26523]
Even when [comment likes](https://en.support.wordpress.com/comment-likes/) are disabled on a user's site, it's possible to like the comments in the reader.

![comment-likes-setting](https://user-images.githubusercontent.com/203408/43767299-06e059ce-9a35-11e8-8227-677fc7346635.jpg)

Another option might be to respect disabled comment likes in the API, so that spam comment likers are cut off of that route as well.

**Comment by rachelmcr** [comment]
In the past, it was decided to always have post likes enabled in the Reader, regardless of the settings on the blog/post: https://github.com/Automattic/wp-calypso/issues/770

I would expect comment likes to be treated like post likes and be always enabled in the Reader, by design. Could a designer take a look and weigh in on that?
