### ISSUE TITLE
Activity Log: phantom time zone change

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26587]
Reported in p1HpG7-5rU-p2

Time zone activity shows up in the log when it wasn't changed at all.

Likely related to general settings page stuff we've seen in the past.

**Comment by roccotripaldi** [comment]
I wasn't able to replicate, but we've solved problems like this in the past. It's likely that we can add this specific setting using the same methods we've used in past.

Possibly related to:
https://github.com/Automattic/jpop-issues/issues/2395

**Comment by roccotripaldi** [comment]
Let's investigate the specific site, as well as gauge how many sites may see this to determine priority.

**Comment by enejb** [comment]
PR in  D17219-code

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
