### ISSUE TITLE
Miscalculated Refundable Amount for Discounted Legacy Products

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#26601]
#### Steps to reproduce

1. Buy a domain from https://wordpress.com/domains. In my case, I bought the domain southptestdomain.com for JPY 3200
1. Go to https://wordpress.com and log in with the account created in the previous step. Create a site with Personal plan.
1. Since the domain has been purchased already, there should be a discount. In my case, I saw JPY 2800 instead of the original JPY 4800.
1. Once it’s done, go to https://wordpress.com/me/purchases, click on the Personal plan and then click “Cancel subscription”.
1. There will be two options: cancelling the plan and the domain or cancelling the plan only. For cancelling the plan only, I’d expect it to be JPY 2800, but it was JPY 0 since it was computed as 2800 – 3200. For cancelling the plan and the domain together, the price wasn’t correct either but I failed to note it down.

cc @Automattic/neutron

**Comment by sirbrillig** [comment]
Good find! Added to internal review list.

**Comment by southp** [comment]
I'm surprised that I've documented this issue already almost a year ago. 🙃Good job, stale bot!
If I'm not mistaken, this is still relevant. cc @Automattic/marketing-dev

**Comment by sirbrillig** [comment]
Hm... I'm not sure if this has survived in our internal bug log. cc @kanishkdudeja

**Comment by DavidRothstein** [comment]
It's at c/ICSw1gTL-tr but mostly obsolete (we don't have this discount for domains anymore).  But as noted there, it could be there's still a much-less-common version of it for sites which upgrade from a legacy product to a plan (since the discount still exists there).

**Comment by michaeldcain** [comment]
Might be related to Automattic/payments-shilling#577

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
From the comment thread, it seems like this is a pretty rare edge case at this point.
