### ISSUE TITLE
Domains: Fix incorrect privacy protection status on Contacts And Privacy page

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#2660]
We should fix the `Contacts And Privacy` page that displays a message stating that privacy protection is turned on whereas it's not the case:

![screenshot](https://cloud.githubusercontent.com/assets/594356/12483995/5885ecbc-c058-11e5-8c3b-c741ddd09346.png)

The public record preview shows the real address instead of the proxy one.

**Comment by wensco** [comment]
This seems to be triggered by having an active privacy subscription with no corresponding private registration service enabled. Users can disable privacy from /purchases but when they do this, it removes the subscription and leaves the private registration service privacy enabled.

It's possible to use internal tools to work around that process, which can cause this issue where we display a "privacy is enabled" message but the contact information is not actually private. We can test to see if we can replicate the issue using user-facing options under /purchases and /domains. We could also consider adding a check to look for enabled private registration service (instead of just the subscription), and/or a check to identify domains that have an active subscription but no active private registration service for our support staff to address.

**Comment by klimeryk** [comment]
I've stumbled upon this bug too when testing #2258 and it's been reported in #2133 :)
