### ISSUE TITLE
Site Picker: inaccurate upgrade notice

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26672]
In cases where Jetpack sites have an active VaultPress plan, it doesn't make sense to show this green upgrade banner:

<img width="1514" alt="screen shot 2018-08-13 at 3 46 50 pm" src="https://user-images.githubusercontent.com/2694219/44054360-65c0a93c-9f10-11e8-8944-0bee06eb9528.png">

To replicate:
have a site on a free Jetpack plan, and a paid Vaultpress plan.

visit calypso with that site selected

notice the banner

**Comment by rachelmcr** [comment]
I confirmed the issue with the repro steps above. We currently check if the site has a mapped domain and is on the free plan to decide [if a site is eligible for the banner](https://github.com/Automattic/wp-calypso/blob/59bdfeeb97eda4266ad39410cb0a074d2c88dbc8/client/state/selectors/is-eligible-for-domain-to-paid-plan-upsell.js). Somewhere we need to also check if the site has a standalone VaultPress plan.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
