### ISSUE TITLE
Activity Log - Fix event padding bug on tablet sizes

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#26704]
It is really only a visible issue on free sites, but we still need to fix it.

![image](https://user-images.githubusercontent.com/1123119/44151827-edee2bc6-a060-11e8-9cae-483219c75774.png)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
