### ISSUE TITLE
Editor: Select and cut text in chrome on mobile

### ISSUE THREAD

**Issue by pankmr** [Automattic/wp-calypso#26736]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Edit a post in Chrome on phone, highlight a few texts. 
3. Try to "**Cut**" the texts.

![image](https://user-images.githubusercontent.com/30791298/44220849-6585b900-a19d-11e8-99a9-6946e9983413.png)

#### What I expected
The highlighted texts should be copied to the clipboard and removed from the editor.

#### What happened instead
It doesn't remove the selected texts but copies to clipboard.

#### Browser / OS version
Chrome 68.0.3440.91/ Android 8.1 and iOS

#### Screenshot / Video
Video: https://goo.gl/VMGamD

#user-report
1349825-zen

**Comment by damiannep** [comment]
Issue replicated on Android 9.0 as well in Chrome 68.0.3440.91.

**Comment by rachelmcr** [comment]
Thank you for the report! I see that the "Cut" action cuts the last character that was selected (instead of the whole string), although it copies the entire selected string.

In my testing (Chrome on a Nexus 9/Android 7.1.1), it happened in the Calypso editor as well as the Gutenberg editor. It didn't happen in other text fields in Chrome, e.g. the title field.

Because Gutenberg is under active development, and fixes to the current Calypso editor are not being prioritized right now, I'm going to close this issue and move the report to the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/9237
