### ISSUE TITLE
Domains: Select button wonky behavior

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#26739]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/domains/add/
2. Click the button with a check icon
3. Notice how the button label changes to "Select" and the rest of the domain suggestions with prices change to "Free with your plan", even the ones that aren't supposed to be free.

#### What I expected
1. For all buttons to say "Select"
2. For labels not to change to "Free with your plan" as not all of those domains are supposed to be free

#### Browser / OS version
Chome Version 68.0.3440.75
Mac OS High Sierra 10.13.3

#### Screenshot / Video
https://cloudup.com/cRdL5u8iyRj

**Comment by klimeryk** [comment]
Not sure I understand the case fully - when you click the check button icon, you're _removing_ the domain from the cart, so the domain credit is available again. And that's why all the domain suggestions are free with the plan again.

**Comment by jancavan** [comment]
Thanks @klimeryk!

Anyway, I think I was confused because:

1) I don't actually own the domain so not sure why it's displaying a checkmark? I did check on it again though, and for some reason, the checkmark is no longer there. Hmm..

2) I didn't realize that the checkmark meant that "this is a domain I already own" partly because of (1) above, but also because button labels should contain the "action the user is about to take" - e.g. Select, Sign-up, Delete, etc.

3) In this case, the checkmark technically could also mean "Select" which is the same as the button above it, especially because both are also primary buttons:

![screenshot 2018-08-22 09 35 56](https://user-images.githubusercontent.com/4924246/44477176-c7578000-a5ee-11e8-882e-b0a6de39222a.png)

Another thing I noticed that's related to (1) - if I select a domain, I'm taken to the Checkout page, but when I go back to the `/domains/add/` page, it's displaying the checkmark even though I don't own the domain yet since I technically have not paid for it.

**Comment by klimeryk** [comment]
No idea why it was designed like this - you'd have to ask the original designers what was the intent here. The checkmark does _not_ mean you own the domain - just that the domain is already in your cart. Though, I do agree this way of visualizing this state is confusing. If you click on the checkmark, it removes the domain from the cart.

I'm guessing this whole thing goes back to a time where we were considering multidomain purchases, but that was dropped (or deeeeeply pushed back) - however this behaviour remained (since it _is_ still possible to have multiple domain names in a cart - just have to go back to domain search before finishing checkout).
