### ISSUE TITLE
Activity Log API doesn't support providing custom `locale` arguments

### ISSUE THREAD

**Issue by jklausa** [Automattic/wp-calypso#26814]
The API for Activity Log doesn't take the `locale` argument into account when returning results. 

It'd be awesome if this could be changed :)

Mobile apps use this to avoid presenting users with mixed languages in the UI — we always want to use what's local to the device, instead of their WP.com settings.

Attaching a screenshot of the dev console showing the issue.

![image](https://user-images.githubusercontent.com/1594081/44429465-d2cb8c80-a597-11e8-9792-eb6c24db4660.png)

(My WPCom preference is set to `de` and the results are returned in that locale, instead of the `en` provided in the request)

**Comment by enejb** [comment]
@jklausa A couple of problems with your query ^ 
1. Instead of just adding `?locale=en` at the end. 
Since you already have a query `?page=1` the `?locale=en` added at the end is ignored. 

The second part. The wpcom rest api requires `_locale=en` instead of `locale=en`

I think if you set your query to `/sites/klausa.blog/activity?page=1&_locale=en` your query will work as expected. 

Let us know if this is not the case and feel free to reopen this issue.

**Comment by jklausa** [comment]
@enejb argh, yes, brainfart on the second `?` there. Thanks for pointing this out :)

However, I'm not sure I follow when it comes to `locale` vs `_locale`. With something like notifications, we're for sure using `locale`. I just printed out a URL we use to fetch notifications out of debugger attached to the iOS app: 
```https://public-api.wordpress.com/rest/v1.1/notifications/?locale=en```

Does the difference apply between `rest/v1.x/` and `wpcom/v2/` endpoints, or am I completely misunderstanding what's going on here?
