### ISSUE TITLE
Activity Log: theme switches for .com sites contain incorrect URL

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26850]
To reproduce:

- switch themes on a .com site
- go to the site's activity page, and find the theme switch event
- note that the theme's link is broken

<img width="926" alt="screen shot 2018-08-22 at 3 10 12 pm" src="https://user-images.githubusercontent.com/2694219/44532623-82e8e480-a6c1-11e8-84a8-33dc3805e323.png">

**Comment by supernovia** [comment]
Just noting I see this still. Some themes seem to link to the Calypso page for that theme on my site, and others link to Github. Here's a screenshot of mousing over Boardwalk vs mousing over Twenty Nineteen.

![Screen Shot 2019-04-23 at 11 09 57 AM](https://user-images.githubusercontent.com/3476361/56601431-5a9ae800-65b8-11e9-8260-09b77e139e86.png)
![Screen Shot 2019-04-23 at 11 09 43 AM](https://user-images.githubusercontent.com/3476361/56601432-5a9ae800-65b8-11e9-8474-35ccd7071cc0.png)

**Comment by supernovia** [comment]
@roccotripaldi I'm seeing the correct theme URLs now -- are you too?  If so we can probably go ahead and close this.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
This was fixed after a later report, here: https://github.com/Automattic/wp-calypso/issues/62954
