### ISSUE TITLE
Gutenberg: Audit v2 API endpoints

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#26900]
After #26639 is completed, let's document:
- What API endpoints Gutenberg fires when we initialize the editor and perform basic actions. This is important to help scope how much work is left to get this working for Jetpack sites.
- Any endpoints that need additional work to get functionality working for simple sites.

This task is to document and create new issues, not to fix all the issues here.

**Comment by Copons** [comment]
I gave this a quick look, hope it's of some help.
(unless specified, these are all `GET` requests)

## On Load

Currently, Gutenberg preloads a lot of stuff server-side, before even starting to serve the editor.
In [`lib/client-assets.php`](https://github.com/WordPress/gutenberg/blob/82442fe03dbbf0c4f873d2caa54a44343bd280ee/lib/client-assets.php#L1255-L1263) we can see most, if not all, of the requests we were used to see client-side in the dev tools' Network tab:

- **`/`** (note: it's not `/wp/v2`, but the actual `/` root): get the theme options.
- **`/wp/v2/types`**: get the CPTs (I guess including blocks).
- **`/wp/v2/taxonomies`**: get tags, categories, maybe also custom taxonomies.
- **`/wp/v2/{ postType }/{ postId }`**: get the actual post details.
- **`/wp/v2/types/{ postType }`**: get the details of the post's CPT.
- **`/wp/v2/users/me?post_type={ postType }`**: get the current user's details (the `post_type` param is not documented, and feels more like a copypasta gone wrong 🤷‍♂️).

Because of all this behind the scenes preloads, we might not see any client-side calls at all when Gutenberg loads.
The only way we might end up requesting stuff _without first clicking anything_, is if the document sidebar is visible on load (this happens when the screen is wide enough).

On open, the sidebar would request _all_ the authors' details:

- **`/wp/v2/users/?who=authors`** (the `who` param is not documented, but it might be something like `?role=author` 🤔).

## On Click Around

Staying on the sidebar, these are the other calls that get fired:

- **`/wp/v2/categories`**: when opening the Categories section.
- **`/wp/v2/tags`**: when opening the Tags section.
- **`/wp/v2/media/{ mediaId }`**: when opening the Featured Image section (if the post has one).

At some point in my poking around (right after I added a featured image), this got requested:

- **`/wp/v2/posts/{ postId }/autosaves`**

Upon clicking any block, or the insert block button:

- **`/wp/v2/types/wp_block`**: get the `wp_block` CPT details.
- **`/wp-json/wp/v2/blocks`**: this is the [custom route for the `wp_block` CPT](https://github.com/WordPress/gutenberg/blob/82442fe03dbbf0c4f873d2caa54a44343bd280ee/lib/register.php#L471); get the reusable blocks.

Upon saving the post:

- `POST` **`/wp/v2/posts/{ postId }`**

**Comment by gwwar** [comment]
Thanks @Copons with Mike looking into remaining endpoint tasks I think we're in a good spot for this, let's file new issues if we do find specific problems.
