### ISSUE TITLE
Me: Users with English (UK) account language can't validate recovery email

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#26970]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Set Interface Language to English (UK) and save the settings.
3. Open Account Recovery settings: https://wordpress.com/me/security/account-recovery
4. Set an account recovery email.
5. Click the link in the confirmation email to validate the recovery email.

#### What I expected

The recovery email information is verified and updated on the user's account

#### What happened instead

The user is instead directed to `https://wordpress.com/me` and the information isn't updated.

#### Screenshot / Video

The screenshot contains user info. See references below for links to screenshots/videos.

#### Context / Source

Reported in 5560907-hc
Follow-up ticket currently open and user is waiting for a response: 1337885-zen
Reported internally and discussed (with screenshots and video) in p9k6jH-ij-p2

**Comment by rachelmcr** [comment]
I successfully reproduced this issue with my account language set to English (UK), and have updated the original report with steps to reproduce this with another account.

The link to validate the account recovery email includes `en-gb.wordpress.com` which I believe is causing the problem here.

As a workaround, users can switch to `English` (instead of `English (UK)`), resend the link, confirm the email address, and then switch their interface language back.

**Comment by torres126** [comment]
Is this still an issue - I can't seem to reproduce it anymore despite having my interface language set to English (UK), and the recovery email is added fine. 

![screenshot_20190102-214723](https://user-images.githubusercontent.com/43215253/50614308-39fb3500-0ed8-11e9-9d4d-ff642ae8880b.jpg)

**Comment by rachelmcr** [comment]
I can still reproduce this issue using the steps in the original report. The only difference for me is that I'm redirected to `https://wordpress.com/` instead of `https://wordpress.com/me` after using the validation link.

**Comment by GeoJunkie** [comment]
Did some more testing and this happens for any language with a "sub-locale" (e.g., `en-gb`, `pt-br`, `es-cl`).

I did a network trace and found that the `302` redirect coming from the API is incorrectly redirecting to the base wordpress.com site instead of the `wp-login`.

Examples:

English (no language in the link).

Link: `https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https%3A%2F%2Fwordpress.com%2Fwp-login.php%3Faction%3Dvalidate%26code%**REDACTED**%26login%3D**REDACTED**&sr=1&signature=**REDACTED**&user=**REDACTED**&_e=**REDACTED**&_z=z`

302 location header in response: `location: https://wordpress.com/wp-login.php?action=validate&code=**REDACTED**&login=**REDACTED**`

Spanish (`es`):

Link (note the `es.wordpress.com`): `https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https%3A%2F%2Fes.wordpress.com%2Fwp-login.php%3Faction%3Dvalidate%26code%**REDACTED**%26login%3D**REDACTED**&sr=1&signature=**REDACTED**&user=**REDACTED**&_e=**REDACTED**&_z=z`

302 location header in response: `location: https://es.wordpress.com/wp-login.php?action=validate&code=**REDACTED**&login=**REDACTED**`

Chilean (`es-cl`):

Link (note the `es-cl.wordpress.com`): `https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https%3A%2F%2Fes-cl.wordpress.com%2Fwp-login.php%3Faction%3Dvalidate%26code%3D**REDACTED**%26login%3D**REDACTED**&sr=1&signature=**REDACTED**&user=**REDACTED**&_e=**REDACTED**&_z=z`

302 location header in response: `location: https://wordpress.com/`

There's similar behavior with `pt-br` and `en-gb`.

**Comment by fstath** [comment]
I'm re-opening the issue as the same thing happened to a user that had the interface language set to Greek. When they switched it to English they were able to verify their recovery email.

Reported and troubleshot internally: pbMDNC-dH-p2

Forum thread (in Greek): https://wordpress.com/el/forums/topic/account-recovery-link-not-working/

**Comment by worldomonation** [comment]
Removed stale label as issue has been re-opened.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
