### ISSUE TITLE
Jetpack Writing settings: 1TB storage showing for videopress

### ISSUE THREAD

**Issue by dougaitken** [Automattic/wp-calypso#27043]
#### Steps to reproduce
1. WordPress site connected to Jetpack with a Premium or Professional Plan
2. Start at https://wordpress.com/settings/writing/
3. Scroll to Media
4. Toggle ```Enable fast, ad-free video hosting``` on 

#### What I expected

No mention of storage _limit_ as described in the Jetpack [Premium or Professional](https://jetpack.com/pricing/) plans.

#### What happened instead

When enabled, I see a 1TB limit on the video hosting with a sotrage size progress-type bar and an upgrade button. This upgrade button shows even on a Professional plan, this highest plan available on Jetpack.com.

#### Browser / OS version

N/A

#### Screenshot / Video

![http://cld.wthms.co/47eXzf](http://cld.wthms.co/47eXzf+)
`Image link: http://cld.wthms.co/47eXzf`

#### Context / Source

#manual-testing

I was checking another feature related to a ticket on the Writing screen in Calypso and notices the bar.

This doesn't show on the `wp-admin/admin.php?page=jetpack#/settings` for the same site so it is Calypso specific.

**Comment by sirreal** [comment]
cc: @jmdodd

**Comment by sirreal** [comment]
A starting point for folks looking at this is D5652-code and https://github.com/Automattic/wp-calypso/blob/2f2db040979e48885e342a09b68e49b5fb822b32/client/my-sites/site-settings/media-settings.jsx#L109-L120

**Comment by rfaile313** [comment]
I'd like to take a look at this. I'm pretty sure I can fix it.

**Comment by rfaile313** [comment]
Worked on this with @klimeryk today :-) we have a few ideas that we will PR soon :-D

**Comment by rfaile313** [comment]
@sirreal @dougaitken We've identified the problem and are discussing the best way to change this moving forward in p9F6qB-ww-p2 since it was a recent commit that changed this.

**Comment by rfaile313** [comment]
Outlined problem in depth in p9F6qB-ww-p2 and proposed solutions 😄

**Comment by sirreal** [comment]
Updating with investigation from @rfaile313, this is not my work:

This problem was likely introduced in D13199-code which increased the value used to represent unlimited storage plans. Existing sites do not seem to have been updated so when a comparison is made to check for unlimited storage, it now fails.

**Comment by arunsathiya** [comment]
@dougaitken I could be missing something, but the original report seems to be fixed now. I don't see 1TB limit anymore:

![Screen%20Shot%202020-02-16%20at%2011 32 47](https://user-images.githubusercontent.com/18581859/75134983-0c89d000-5706-11ea-84ae-0d030cd23536.png)

Could you confirm?

**Comment by dougaitken** [comment]
@arunsathiya my site `doug.press` is on a Professional Jetpack plan, on the same section you've screenshotted, my site shows `0% of 1 TB used`

![dougpress_calypso_performance_settings](https://user-images.githubusercontent.com/52214/75436292-392f2900-594c-11ea-8e1b-b83d6a2464af.png)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
Pricing for VideoPress notes the 1TB of storage, so it seems this issue is no longer relevant, as showing a 1TB cap on usage is accurate.
![Markup on 2023-08-17 at 15:45:27](https://github.com/Automattic/wp-calypso/assets/27249804/6a029292-febe-4bef-b564-032e16da8134)
From https://cloud.jetpack.com/pricing#jetpack_videopress
