### ISSUE TITLE
Jetpack Plans: Plan graphics are missing 

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#27152]
#### Steps to reproduce
1. Starting at URL: https://jurassic.ninja/create/?shortlived&jetpack-beta
2. Connect a site via button in wp-admin.
3. After connection, you'll be landed on Jetpack plans. Plan graphics will not be visible

#### What I expected

Plan graphics to be visible

#### What happened instead

Plan graphics was not visible. They were downloaded, but looks like they are hidden by `display: none`

#### Browser / OS version

Chrome / Mac OS

#### Screenshot / Video

<img width="1320" alt="plans wordpress com 2018-09-12 13-01-25" src="https://user-images.githubusercontent.com/5654161/45418249-a7b2f500-b68c-11e8-8c15-d40ba9394d2e.png">

**Comment by ockham** [comment]
Okay, as per discussion on Slack, I'm pretty sure it's not really the missing images that are the problem -- those were removed some [9 months ago](https://github.com/Automattic/wp-calypso/commit/ba8b8bec12704789c50b094a552473106896662e), so that should be alright.

Rather, the issue is the broken styling of prices, which used to be like this prior to 6de8093cb0f6bd05c8aff1eab36d147b8eef2cf4: 

![image](https://user-images.githubusercontent.com/96308/45422129-9e775780-b68f-11e8-97ef-82966fe6cd90.png)

/cc @adamziel

**Comment by adamziel** [comment]
@ockham I'm looking into it

**Comment by ockham** [comment]
@adamziel Thanks!

**Comment by adamziel** [comment]
@ockham I have a fix, would you mind reviewing? https://github.com/Automattic/wp-calypso/pull/27156

**Comment by adamziel** [comment]
@brbrr I just landed a fix, would you confirm it worked and close the issue?

**Comment by brbrr** [comment]
Fixed in #27156
