### ISSUE TITLE
Gutenberg: don't display Auto Draft in the title

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27162]
For new posts we use an auto draft, but default behavior will display that title in the Editor. Let's update behavior to what we see in wp-admin.

**Comment by kwight** [comment]
Here's what we have in core (including WP.com `wp-admin`):

<img width="1326" alt="screen shot 2018-09-14 at 11 13 37 am" src="https://user-images.githubusercontent.com/349751/45567662-48c9b900-b80f-11e8-92ff-eb0d99b72bd8.png">

This [welcome text](https://github.com/WordPress/gutenberg/blob/ff4bc708e4ad2a186118875e57c3eed2b80b1b5b/lib/client-assets.php#L1331) is provided by an enqueued script with [the title change triggered by a query param](https://github.com/WordPress/gutenberg/blob/ff4bc708e4ad2a186118875e57c3eed2b80b1b5b/lib/client-assets.php#L1239). This doesn't happen in Calypso since we're not adding enqueued scripts.

Our current "Auto Draft" text comes from the endpoint's core `get_default_post_to_edit()` call, which includes a convenient `default_title` filter. Since the `auto-draft` endpoint is serving this singular purpose of providing Gutenberg auto-drafts, adding a `default_title` filter to the endpoint will be most simple. Another option is to add an accepted param to the endpoint which tells it to apply the Gutenberg-specific filter; another option is mushing the transform into Calypso's `/client/gutenberg/editor/main.jsx` somehow, but that seems messiest to me.

I'll go with adding a filter to the endpoint, unless anyone has strong arguments otherwise.

**Comment by gwwar** [comment]
Sure let's add a filter to the endpoint. I can think of 2 use cases we may want to have to help populate content. One being completely blank (eg see what happens when we start a new post), and another with demo content (which we can crib off of the plugin for now).

**Comment by kwight** [comment]
Hm, this got more complicated – I misread `get_default_post_to_edit`, the filters are available for the post object it returns, but not the post it adds to the database (our endpoint just returns the ID, so those filters won't help us here).

It brings up the option of the endpoint returning the post object rather than just the ID, which would be more over the wire, but one less API call – but we'd need more refactoring in `/client/gutenberg/editor/main.jsx` (and I doubt that's terribly important right now). I'll look into other options Calypso-side next week.

**Comment by kwight** [comment]
I was getting ahead by showing the demo content, which is triggered by a query param; once using Gutenberg normally, the default title is "Add title". This is addressed in #27297 , with the option of demo content being added in a later PR.
