### ISSUE TITLE
Purchases: style issues for PayPal in Edit Payment Method

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#272]
This is how a PayPal account looks in Edit Payment Method:

![paypal](https://cloud.githubusercontent.com/assets/1248436/10970225/6f25ce46-83b4-11e5-9e2e-b6972f626ab4.png)

This is what a store credit card looks like in comparison:

![cc](https://cloud.githubusercontent.com/assets/1248436/10970229/7b02ea78-83b4-11e5-805a-dd7690dd613d.png)

We should probably add some space between the PayPal logo and the account name, and also make it bold so it matches the styles for credit cards.

@mikeshelton1503 proposed the following solution:

![image](https://cloud.githubusercontent.com/assets/12596797/11076035/8c01e688-87c6-11e5-9e7c-3a00c1296ceb.png)

**Comment by drewblaisdell** [comment]
I'm not (consciously :thought_balloon:) trying to move every issue to Purchases v2, but since this issue was created, `EditPaymentMethod` is no longer mounted on any route and no longer contains `PaymentLogo`. It will be easier to make this change/test it when payment management is in progress again.

I opened #707 to add an `isCompact` prop to `PaymentLogo`, so that we can display the 'P' in the design with `<PaymentLogo type="paypal" isCompact />`.

**Comment by fabianapsimoes** [comment]
Makes sense, Drew. Punting the rest of this to v2.

**Comment by fabianapsimoes** [comment]
Closing this since we're not mounting Edit Payment Method on any routes, as Drew mentioned.
