### ISSUE TITLE
Activity Log: Pingback deleted notification looks odd

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#27213]
On Jetpack.com I saw this. 
![screen shot 2018-09-14 at 6 20 51 am](https://user-images.githubusercontent.com/115071/45552642-7bab8700-b7e6-11e8-8acd-0303b55093c3.png)

the author name is set as `Facebook Shuts Down API for Publishing to User Timelines, Impacts Jetpack’s Publicize Feature – Central Geek`

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
