### ISSUE TITLE
Atomic: Unable to delete unassigned categories via Calypso

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-calypso#27259]
#### Steps to reproduce
1. In Calypso go to the edit category page. 
My Sites - Customize - Writing
https://wordpress.com/settings/taxonomies/category/site.com
2. Try to delete a new category that doesn't have any posts assigned to it. 
3. Doesn't work. 

Switch to Classic /wp-admin/ editor 
1. Edit categories - delete same category with success. 

Report came to us from this forum thread: 
https://en.forums.wordpress.com/topic/deleting-catagories/

Issue replicated by myself in Chrome on Mac OS. Replicated by forum volunteer on different setup.

**Comment by flootr** [comment]
I can't replicate this behaviour following the steps from above. Is this still relevant?

**Comment by rfaile313** [comment]
@flootr just got this bug in 1535629-z

Here's the bug in action: http://cld.wthms.co/aPD1Xq

**Comment by flootr** [comment]
It would be interesting if there's any errors in the console of if the network request failed (and for what reason). I still fail to replicate this bug unfortunately.

@lizkarkoski @rfaile313 can you deterministically replicate this bug with a certain blog?

**Comment by TeniCola** [comment]
Hello! It seems like this issue is still occurring because I had a user report the same thing, and then some.

> Livechat -- HC-3939939
> Site ID -- 147075553
> Slack -- p1550758140499100-slack-livechat

My user was unable to delete their categories (which were also empty), but they also couldn't edit or nest them under different parents. A hard refresh didn’t work, and I was able to replicate it myself in SU-mode. I managed to run the console while trying the actions myself and it produced these results:

![Category errors](https://cdn-std.dprcdn.net/files/acc_711857/q1W084)

For the time being, I told the user to use wp admin as a work around, but this does seem like a strange bug in Calypso, and I personally can't recreate on my own test sites.

(Also, realization that I should have expanded the console messages with the drop down, sorry I was trying to quickly capture it while in livechat and during SU mode, but I hope this helps a little)

**Comment by RealCarFax** [comment]
I was able to replicate this issue on a user's site as well: https://cloudup.com/cmQKe-yAGev

However, in this instance it was showing that 0 posts are assigned to this category, while WP Admin was showing 2 posts assigned to this category (and WP Admin was able to delete the category just fine).

User report: #2061902-zen

**Comment by tijosh** [comment]
Another report of this in #154305100-hc

**Comment by khristiansnyder** [comment]
Another report in 16724205-hc
AT site. Can replicate on my own AT site as well and have to use WP-Admin as workaround.

**Comment by annbingle** [comment]
Hi and Good day!
Here's another one 17528082-hc.
It's an AT site and the WP-Admin workaround worked.

Thank you :)
Ann

**Comment by TeniCola** [comment]
Hello! I'm back with a recent report in 19284707-hc

It's for another AT site, and I offered the WP Admin dashboard workaround for this user in the meantime.

**Comment by nerdysandy** [comment]
I can no longer replicate it on both Simple and AT sites. Closing it because of that
