### ISSUE TITLE
Gutenberg: Core Blocks Work

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27294]
Audit of blocks done by @vindl (Edited to bump info to the top summary)

## Common blocks

| Block name  | Does it work in editor? | Does it render properly on front end? | Issue/PR |
| ------------- | ------------- | ------------- | ------------- | 
| Paragraph  | **Yes** - Editing and saving works as expected for basic content. Basic block settings like alignment, bold, and italics are applied properly.  | **No** - Block sidebar settings like custom size, drop cap, background color, and text color are saved properly on the editing screen, but do not appear on front end.  |
| Heading | **Yes**  | **Yes**  |
| Image | **Yes** - In my original testing upload was failing, but now everything seems to work fine. | **No** - I'm seeing some issue with central alignment (stays left), but that might be theme dependent. |
Gallery | **Yes** | **No** - images are not rendered appropriately on the front end. The "columns" setting is not respected and they are just shown one after the other as list items. | 
List | **No** -   I was unable to ident/outdent the list item in order to produce nested lists. | **Yes**. |
Quote | **Yes**. | **No** - The editing screen should match what users see on the front end when they publish a post. That's not the case because current themes were not developed with Gutenberg editor in mind. |
Cover image | **Yes**. | **No** - It's not rendered on the front-end correctly: the image is cropped to cover text container height, or it's not shown at all if there is no cover text. |
Audio block | **No** - I tried uploading an .mp3 file but got `Sorry, this file type is not permitted for security reasons.` We might need to whitelist some extensions for this to work? | **No**. |
File block | **Yes** . | **No** - download link rendered on front end is wrong, e.g: `https://wpcalypso.wordpress.com/19115187-8f88-4fc7-a40e-6fe12c18b3fa` (results in unknown Calypso page). Also the Download button is unstyled on the front end when compared to editor. |
Video block | **No** - Similar to Audio block, I tried uploading an .mp4 file and run into `Sorry, this file type is not permitted for security reasons.` | **No**. | 

## Inline blocks 

| Block name  | Does it work in editor? | Does it render properly on front end? | Issue / PR |
| ------------- | ------------- | ------------- |------------- |
| Inline image  | **No** - Inserting this block doesn't work for me at all.  | **No**. |

## Formatting 

| Block name  | Does it work in editor? | Does it render properly on front end? | Issue / PR |
| ------------- | ------------- | ------------- |------------- |
| Code block  | **Yes**. | **Yes**. |
| Preformatted text  | **Yes**. | **Yes**. |
| Pull quote | **Yes** | **No** - there is a similar problem as with regular quote block. It looks different in editor and on front end due to different theme styling. |
| Table  | **Yes**. | **Yes**. |
| Verse  | **Yes**. | **Yes**. |

## Layout elements

| Block name  | Does it work in editor? | Does it render properly on front end? | Issue/PR |
| ------------- | ------------- | ------------- |------------- |
| Button  | **Yes**. | **No** -  background color and text color settings are not applied. |
| Columns | **Yes**. | **No** - the columns' content is just follow the default vertical flow. |
| Read more | **Yes**. | **Yes**. |
| Page break | **Yes**. | **Yes**. |
| Separator | **Yes**. | **Yes**. |
| Spacer | **No** - works as expected initially, but on editor reload it's reported with `This block has been modified externally`. _backend is stripping `aria-hidden="true"`_ | **Yes**. | #27645 |

## Widgets

| Block name  | Does it work in editor? | Does it render properly on front end? | Issue/PR |
| ------------- | ------------- | ------------- |------------- |
| Archives  | **No** - the blocks fails in editor with the following message: `Error loading block: No route was found matching the URL and request method` | **No**. |
| Latest comment  | **No** - the blocks fails in editor with the following message: `Error loading block: No route was found matching the URL and request method` | **No**. |
| Categories | **Yes** | **No** - they are loaded properly in the editor but nothing in displayed on the front end. |
| Latest posts | **Yes** | **No** - they are loaded properly in the editor but nothing in displayed on the front end. |
| Shortcodes | **Yes** | **Yes** |

## Embeds

| Block name  | Does it work in editor? | Does it render properly on front end? | Issue/PR |
| ------------- | ------------- | ------------- |------------- |
| YouTube  | **Yes**. | **Yes**. |
| Instagram | **No** - the preview is not fetched in editor. | **Yes**. |
| Flicker | **Yes**. | **Yes** (caption styling might be off). |
| Vimeo | **Yes**. | **Yes** (caption styling might be off). |
| Other services | TBD | TBD |

**Comment by vindl** [comment]
I tried to check all of the core blocks that we offer in the Gutenberg in Calypso integration now and here is the summary of results. Just a not that I've done all of the testing in wpcalypso environment.

## Common blocks

| Block name  | Does it work in editor? | Does it render properly on front end? |
| ------------- | ------------- | ------------- |
| Paragraph  | **Yes** - Editing and saving works as expected for basic content. Basic block settings like alignment, bold, and italics are applied properly.  | **No** - Block sidebar settings like custom size, drop cap, background color, and text color are saved properly on the editing screen, but do not appear on front end.  |
| Heading | **Yes**  | **Yes**  |
| Image | **Yes** - In my original testing upload was failing, but now everything seems to work fine. | **No** - I'm seeing some issue with central alignment (stays left), but that might be theme dependent. |
Gallery | **Yes** | **No** - images are not rendered appropriately on the front end. The "columns" setting is not respected and they are just shown one after the other as list items. | 
List | **No** -   I was unable to ident/outdent the list item in order to produce nested lists. | **Yes**. |
Quote | **Yes**. | **No** - The editing screen should match what users see on the front end when they publish a post. That's not the case because current themes were not developed with Gutenberg editor in mind. |
Cover image | **Yes**. | **No** - It's not rendered on the front-end correctly: the image is cropped to cover text container height, or it's not shown at all if there is no cover text. |
Audio block | **No** - I tried uploading an .mp3 file but got `Sorry, this file type is not permitted for security reasons.` We might need to whitelist some extensions for this to work? | **No**. |
File block | **Yes** . | **No** - download link rendered on front end is wrong, e.g: `https://wpcalypso.wordpress.com/19115187-8f88-4fc7-a40e-6fe12c18b3fa` (results in unknown Calypso page). Also the Download button is unstyled on the front end when compared to editor. |
Video block | **No** - Similar to Audio block, I tried uploading an .mp4 file and run into `Sorry, this file type is not permitted for security reasons.` | **No**. | 



## Inline blocks 

| Block name  | Does it work in editor? | Does it render properly on front end? |
| ------------- | ------------- | ------------- |
| Inline image  | **No** - Inserting this block doesn't work for me at all.  | **No**. |



## Formatting 

| Block name  | Does it work in editor? | Does it render properly on front end? |
| ------------- | ------------- | ------------- |
| Code block  | **Yes**. | **Yes**. |
| Preformatted text  | **Yes**. | **Yes**. |
| Pull quote | **Yes** | **No** - there is a similar problem as with regular quote block. It looks different in editor and on front end due to different theme styling. |
| Table  | **Yes**. | **Yes**. |
| Verse  | **Yes**. | **Yes**. |



## Layout elements

| Block name  | Does it work in editor? | Does it render properly on front end? |
| ------------- | ------------- | ------------- |
| Button  | **Yes**. | **No** -  background color and text color settings are not applied. |
| Columns | **Yes**. | **No** - the columns' content is just follow the default vertical flow. |
| Read more | **Yes**. | **Yes**. |
| Page break | **Yes**. | **Yes**. |
| Separator | **Yes**. | **Yes**. |
| Spacer | **No** - works as expected initially, but on editor reload it's reported with `This block has been modified externally`. I'm guessing something is pruning the empty divs on publish. | **Yes**. |



## Widgets

| Block name  | Does it work in editor? | Does it render properly on front end? |
| ------------- | ------------- | ------------- |
| Archives  | **No** - the blocks fails in editor with the following message: `Error loading block: No route was found matching the URL and request method` | **No**. |
| Latest comment  | **No** - the blocks fails in editor with the following message: `Error loading block: No route was found matching the URL and request method` | **No**. |
| Categories | **Yes** | **No** - they are loaded properly in the editor but nothing in displayed on the front end. |
| Latest posts | **Yes** | **No** - they are loaded properly in the editor but nothing in displayed on the front end. |
| Shortcodes | **Yes** | **Yes** |

## Embeds

| Block name  | Does it work in editor? | Does it render properly on front end? |
| ------------- | ------------- | ------------- |
| YouTube  | **Yes**. | **Yes**. |
| Instagram | **No** - the preview is not fetched in editor. | **Yes**. |
| Flicker | **Yes**. | **Yes** (caption styling might be off). |
| Vimeo | **Yes**. | **Yes** (caption styling might be off). |
| Other services | TBD | TBD |

cc @Automattic/lannister

**Comment by vindl** [comment]
Closing this issue since the audit in complete and we'll have separate issues to track blocks work from now on.

**Comment by vindl** [comment]
I updated the list with latest status and links to GH issues for future reference.
