### ISSUE TITLE
Gutenberg: enable oembed support

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27296]
Let's make sure that we can add oembeds to posts. (Like youtube videos.) We likely need to make sure that we have `/wp-json/oembed/1.0/` support or add a middleware handler to use our wpcom oembed endpoints.

**Comment by kwight** [comment]
Where we're at now:

<img width="1419" alt="screen shot 2018-09-20 at 3 33 18 pm" src="https://user-images.githubusercontent.com/349751/45850349-98feba80-bcea-11e8-984e-ee2cab952f0e.png">

_Core Gutenberg_

As mentioned by @gwwar , core `wp-admin` calls itself at `index.php?rest_route=/oembed/1.0/proxy&url=<source URL>` to fetch the content.

------

<img width="1271" alt="screen shot 2018-09-20 at 3 30 37 pm" src="https://user-images.githubusercontent.com/349751/45850419-eda23580-bcea-11e8-801f-716a436b3402.png">

_Calypso Gutenberg_

The embed block is fine, but its call to `https://public-api.wordpress.com/wp/v2/oembed/1.0/proxy?url=<source URL>` fails since we don't have support for it yet.

--------

<img width="1417" alt="screen shot 2018-09-20 at 3 50 16 pm" src="https://user-images.githubusercontent.com/349751/45850910-f431ac80-bcec-11e8-8e9f-840468ebaaec.png">

_Standard Calypso_

The embed works as expected in the editor, with a call to `https://public-api.wordpress.com/rest/v1.1/sites/<site ID>/embeds/render?embed_url=<source URL>&force=wpcom` responsible for fetching the content.
