### ISSUE TITLE
DevDocs: add spacing on small screens

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#27331]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/docs/sdk.md
2. View in small window or a mobile device

#### What I expected
Readable layout such as other DevDocs pages.

#### What happened instead
Squished against sides of the viewport.

#### Screenshot / Video
<img src="https://user-images.githubusercontent.com/66797/45794700-bbda9180-bc4c-11e8-84b8-1bbe55e96434.png" width="480" />

Context: seen during normal usage, clicking on a GitHub email to read the docs on my phone.

**Comment by simison** [comment]
Thanks, I'll tag this as a generic DevDocs bug since it seems to affect other pages, too:

https://wpcalypso.wordpress.com/devdocs/docs/coding-guidelines/javascript.md

<img width="393" alt="image" src="https://user-images.githubusercontent.com/87168/45794824-2f0df300-bca1-11e8-9f82-7276dd5e9fe7.png">

**Comment by lancewillett** [comment]
Thanks for that; good point. It's more than just the SDK page.

**Comment by simison** [comment]
Still an issue. :-)

https://wpcalypso.wordpress.com/devdocs/README.md

<img width="451" alt="image" src="https://user-images.githubusercontent.com/87168/59584130-ed05c680-90e5-11e9-9c55-729f92ce1613.png">
