### ISSUE TITLE
Gutenberg: Audio Block

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27639]
Let's be able to upload whitelisted audio file types as expected.

**Comment by vindl** [comment]
The apparent file type permission error has been caused by inadequate plan on the site (doesn't work with free plan for example). This has been moved to a separate issue https://github.com/Automattic/wp-calypso/issues/27772, but there is still a problem with Audio block not being rendered on the front end, and `This block has been modified externally.` error on reload which is probably related to attribute pruning issue (https://github.com/Automattic/wp-calypso/issues/27645).

**Comment by Copons** [comment]
This is caused by the `audio` tag not being whitelisted in our `wp_kses`.
Fix pending security review: D19531-code.

**Comment by Copons** [comment]
Fixed by D19531-code
