### ISSUE TITLE
Gutenberg: Spacer block (attribute pruning)

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27645]
See #27294

As the most used block ;) let's make sure that we can insert this and it's serialized appropriately in post content

**Status**

Awaiting fix in core
Awaiting fix in D19247-code

**Comment by dmsnell** [comment]
Tested in current **wpcalypso** environment and it seemed to work as expected. I addd, resized, deleted, and reloaded a page with the spacers.

![spacer-in-calypso mov](https://user-images.githubusercontent.com/5431237/46544808-88297980-c892-11e8-9ce3-e8508aea62c0.gif)

**Comment by dmsnell** [comment]
After reloading the page I discovered the problem - it appears as though Gutenberg is pruning attributes from the block on save.

**Invalid reloaded block**
Note the missing `aria` attribute
```html
<!-- wp:spacer {"height":242} -->
<div style="height:242px;" class="wp-block-spacer"></div>
<!-- /wp:spacer -->
```

**Valid new block**
```html
<!-- wp:spacer {"height":63} -->
<div style="height:63px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->
```

**Comment by mcsf** [comment]
This is likely very similar to core's issue of filtering a saving post's HTML when a user isn't admin (`unfiltered_html` capability). See:

- https://github.com/WordPress/gutenberg/issues/2539
- https://github.com/WordPress/gutenberg/pull/9875
- https://github.com/WordPress/gutenberg/pull/9954

The main reasons for some input to be filtered:

- Using `aria-*` attributes.
- Using `data-*` attributes.
- Using certain inline styles, notably `url()`, [based on this mask](https://core.trac.wordpress.org/browser/tags/4.8.1/src/wp-includes/kses.php#L1696).

The proper fix is to be done in core WP (kses). A [core ticket for CSS's `url()`](https://core.trac.wordpress.org/ticket/45067) has been opened, but further work in kses is needed in order to whitelist `aria-` and `data-` wildcards.

**Comment by vindl** [comment]
@dmsnell just a note that I'm seeing a similar issue with Audio block after uploading and saving (tested with business plan because audio uploads aren't included in free).

**Comment by dmsnell** [comment]
after the merge of D19247-code the spacer block is working
