### ISSUE TITLE
Add Jetpack branding to the Inspector

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#27773]
We need to add a Jetpack colophon of some sort to the block inspector for Jetpack blocks. Let's make it a reusable component so it will be the same across blocks.

Here is the latest design for it:

![image](https://user-images.githubusercontent.com/1123119/46757784-619b8200-cc88-11e8-8bb4-4f1ab73c5a31.png)

It's just the logo and a separator for now. It's the same SVG used in the Jetpack dashboard. I think we can further work out what we place here and, as I elaborate on here, p6TEKc-23j , we could potentially put more information on it specific to each block.

Let's get it added to these blocks:
- [ ] Markdown
- [ ] Tiled Galleries
- [ ] Related Posts

@mapk and @thomasguillot I would love some feedback and ideas from you to around this and what we could do in future iterations.

**Comment by tyxla** [comment]
And there it is: 

https://github.com/Automattic/wp-calypso/pull/27901

**Comment by MichaelArestad** [comment]
I think we might sit on this for a bit. Don't start without pinging me.

**Comment by tyxla** [comment]
> Would be neat to have the logo in the dropdown, too:

Noting that this is by design in the Gutenberg core. If we're currently looking at the plugin sidebar, a checkmark will be displayed in the dropdown, but if you select another plugin or another view (inspector controls for example), and click on the `...` button, you should see the Jetpack icon in the dropdown, to the left of the "Jetpack" item.

**Comment by scruffian** [comment]
I agree that this can be closed.
