### ISSUE TITLE
Reader: Spotify embeds leave a weird space below them

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#2777]
In the Reader, if you come across a post that contains a Spotify embed, then that gets used as the "featured media" in the list view. It displays as an actual embed, which is cool, but it leaves a big/weird gap below it:

![screen shot 2016-01-26 at 1 34 29 am](https://cloud.githubusercontent.com/assets/108942/12575861/28c5bade-c3cd-11e5-9128-e84ac20f61a4.png)

This was noted first in the desktop app, but I confirmed that I also see it on the web, using Chrome/OSX.

**Comment by blowery** [comment]
Confirmed. Can see this at https://wordpress.com/tag/spotify?at=2016-01-25T14:15:00-05:00

**Comment by samuelclemens** [comment]
The problem here imo, is that reader uses embed's aspectRatio, 
(that supplied at [post-normalizer](https://github.com/Automattic/wp-calypso/blob/0f1cf950178d2ac41a1bd6ac7e232d167b7f1e42/client/lib/post-normalizer/index.js#L667)?) to [calculate the height](https://github.com/Automattic/wp-calypso/blob/0f1cf950178d2ac41a1bd6ac7e232d167b7f1e42/client/reader/following-stream/post.jsx#L212) of the embed. BUT, spotify sizes itself according to it's own logic inside the iframe,
the size it's using is ``$(window).width()+80`` for the large embed:
```
function resizeWidget() {
    var a = $(window).width(),
        b = $(window).height(),
        d = $("body"),
        c, e;
    b - 80 > a ? (c = a + 80 + "px", e = "100%") : (e = b - 80 + "px", c = "100%");
    a >= PLAYER_MIN_WIDTH && b >= ENGAGEVIEW_MIN_HEIGHT + PLAYER_HEIGHT ? (mode = "mode-large", $("#outerWidgetContainer").css({
        width: e,
        height: c
    })) : (mode = "mode-compact", $("#outerWidgetContainer").css({
        width: "auto",
        height: "100%"
    }));
    "mode-large" === mode && (!0 !== renderListView || "track" === contextType) ? d.addClass("engage") : d.removeClass("engage");
    d.removeClass("mode-large").removeClass("mode-compact");
    d.addClass(mode)
}
```
[snippet from here](https://d2b1xqaw2ss8na.cloudfront.net/static/js/md.5ae4f9e.js)


in that case aspectRatio is [function of width](http://www.wolframalpha.com/input/?i=w%2B80%3Dx*w), not a constant.
