### ISSUE TITLE
Importers: Medium icon is out of date

### ISSUE THREAD

**Issue by andfinally** [Automattic/wp-calypso#27816]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import/[site].wordpress.com
2. View the Medium importer.

#### What I expected
The icon should be the current Medium icon.

#### What happened instead
The icon is an old version.

#### Browser / OS version
All browsers

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/1647564/46873989-f5f41900-ce2f-11e8-88e1-b8dd35fa4546.png)

![image](https://user-images.githubusercontent.com/1647564/46874142-53886580-ce30-11e8-92f7-2f9d08918b45.png)

#### Context / Source
We have an SVG for this icon from Medium's [brand guidelines page](https://medium.design/logos-and-brand-guidelines-f1a01a733592) (attached).

[Monogram.svg.zip](https://github.com/Automattic/wp-calypso/files/2473354/Monogram.svg.zip)

This icon is included from the Social Icons npm package - I've created issue https://github.com/Automattic/social-logos/issues/69 on that repo. We'll need to deploy that update before we can resolve this issue.

**Comment by dezzie** [comment]
Wanted to point out that there are a couple of issues looking at the same thing and there's a PR for this here: https://github.com/Automattic/social-logos/pull/71

**Comment by dezzie** [comment]
_(Re-posting what I put over there to solve the issue)_

The logo images are pulled from each platform's own branding guidelines, not a black and white set. 

When I inspected one of the other images, I saw that we are using a regular square image for the logo, and then setting it inside a square background of the same color. The background is the container that has the rounded corners on it. That's probably so that we don't make redundant assets and can preserve the original one to use elsewhere.

I went ahead and re-created the new Medium logo to solve any rendering issues, and because we do need to shave a bit off the sides to make the "M" look proportionately consistent with the other importer logo images. If it is easier to update the logo using a .png instead of an .svg I attached that here too.

The bg color of the updated Medium logomark should be #12100E:
[Updated Medium Logomark.zip](https://github.com/Automattic/social-logos/files/3107968/Updated.Medium.Logomark.zip)

**Comment by andfinally** [comment]
Since updating the social-logos package seems likely to take a long time, I've addressed this by using the SVG directly in https://github.com/Automattic/wp-calypso/pull/32546. The npm package still needs updating, but my PR fixes the issue immediately for Calypso.

**Comment by andfinally** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/32546.
