### ISSUE TITLE
Closing quote replaced with &#8221; when quoting "http://"

### ISSUE THREAD

**Issue by sdixon194** [Automattic/wp-calypso#27825]
This bug initially reported by a user in the Gutenberg repo. cc 1475536-zen

They discovered this seemed to happen across all of wpcom, not just GB. Let me know if there's a more appropriate place for this sort of thing: 

**Describe the bug**
If a paragraph contains "http://", the closing quote gets replaced with an HTML-encoded ” when writing in Calypso, WP-Admin, or Gutenberg 

**To Reproduce**

Create a new post. Add the following paragraph to it:
Here is how you start a URL: "http://" or "https://".

View the preview or publish it
You'll see: `Here is how you start a URL:  “http://&#8221; or “https://&#8221;.`

**Expected behavior**

No HTML encoded HTML entities should be visible.

**Screenshots**
Editor:
![screen shot on 2018-10-12 at 13 51 04](https://user-images.githubusercontent.com/33553323/46885402-e079f180-ce25-11e8-9a31-6436d1160b4a.png)

Front-end:
![screen shot 2018-10-12 at 13 50 27](https://user-images.githubusercontent.com/33553323/46885386-d22bd580-ce25-11e8-8f06-5e55d1adccdc.png)

**Desktop (please complete the following information):**

OS: Windows 7
Browser Firefox
Version 63.0b9 (64-bit)
Additional context
Active theme: Rebalance

**Comment by gwwar** [comment]
Verified still an issue for wpcom only.

**Comment by synora** [comment]
Keeping the issue open as I'm still able to reproduce it.

<img width="825" alt="Screen Shot on 2021-04-23 at 13-01-04" src="https://user-images.githubusercontent.com/10015451/115905407-0ee3d900-a434-11eb-8d28-476fbe51ab51.png">

**Comment by kwight** [comment]
Dropping this to normal priority – we've had little reports over three years. 🙃

**Comment by rosepajaroja** [comment]
Keeping this issue open as I can still reproduce it. 

![Alt text](https://d.pr/i/1DapNh/3wxyUHNAxN+)

**Comment by cometgrrl** [comment]
Lowering the priority (again) since we've had so few reports, and it seems like a pretty rare case.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
