### ISSUE TITLE
Signup: Create a landing page for the desktop signup flow

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#2785]
The desktop app currently links to the signup flow in a browser window. We'd like to have it run in the app. Unfortunately just linking directly to it from the auth screen doesn't work.

One issue is that we use a different logged out layout for the auth screen: https://github.com/Automattic/wp-calypso/blob/master/client/boot/index.js#L189

Here are some more findings:
We do the redirect to the auth screen here: https://github.com/Automattic/wp-calypso/blob/master/client/boot/index.js#L278

The login screen is rendered here: https://github.com/Automattic/wp-calypso/blob/master/client/auth/controller.js#L20

The desktop lib: https://github.com/Automattic/wp-calypso/blob/master/client/boot/index.js#L347

The desktop jade template: https://github.com/Automattic/wp-calypso/blob/master/server/pages/desktop.jade

**Comment by scruffian** [comment]
Where should a user land once they have completed the signup flow in desktop? @p3ob7o @folletto @ianstewart

**Comment by folletto** [comment]
It's a good question. Trying to list some factors that lead to the decision:

1. We can't show their front-end as we do on Calypso since it would require a jump out of the app.
2. We currently log-in to Reader.
3. The user downloading the app is likely installing it for the WordPress part, Reader being a plus — current state of our communication: "A desktop app that gives WordPress a permanent home in your dock".

So for this reason, I'd open the "My Site" `/sites` view, but not on stats since it will be empty, but on either:

* Blog Posts `/posts` — because will show the menu to manage it, and hints at creating new content
* Themes `/design` — because will show link to the customization features

I'd probably favor the Blog Posts choice.

Can we re-introduce just for this flow the top-positioned Welcome banner maybe?

**Comment by scruffian** [comment]
Pinging @mikeshelton1503 and @breezyskies for input.

**Comment by mikeshelton1503** [comment]
I've added this to Cerulean's Sprint for next week.

**Comment by folletto** [comment]
Can anyone check if this issue is still relevant or can be closed? I give it a go but it's a quite complex discussion apparently. :)
