### ISSUE TITLE
Checklist: Users with locale defaulted to zh-tw can't complete the Personalize Contact Page step.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#27868]
#### Steps to reproduce
Actually I'm not sure if this is specific to Traditional Chinese but that was how I bumped into this when looked into https://github.com/Automattic/wp-calypso/issues/26101. 

1. Log in as a user with Traditional Chinese as the interface language & the site language. Make sure you have never clicked on the "Personalize Contact Page" step.
2. Starting at URL: https://wordpress.com/checklist
3. Click on the "Do it" button next to the "Personalize Contact Page"(個人化「聯絡」頁面).

#### What I expected

1. It should lead me to edit the contact page.
1. I should be able to update it as expected.
1. Dismissing it by clicking "All done" should check the step off from the list as expected.

#### What happened instead

1. Note that you will be redirected to edit the about page(簡介), instead of the contact page
1. Clicking on "Update" won't be effective no matter what.
1. Dismissing the guided tour tip by clicking on "all done" also won't mark the step accomplished.

#### Browser / OS version
Browser: Chrome 69.0.3497.100 
OSX: OSX 10.14（18A391）

#### Screenshot / Video
![demo-bug-checklist-contact-page](https://user-images.githubusercontent.com/1842898/46998541-6e6f1880-d155-11e8-80db-e822fd2ef71e.gif)

**Comment by ramonjd** [comment]
I have been able to reproduce this.

I clicked on **Personalize your Contact** page and updated the page without dismissing the modal.

Then went back to my checklist and experienced the following:

![oct-18-2018 16-48-56](https://user-images.githubusercontent.com/6458278/47133772-ed02bc00-d2f5-11e8-8d79-83de5246ebaf.gif)

**Comment by ramonjd** [comment]
I think this is because once the contact page has been saved/updated, it loses the headstart metadata and therefore this [selector function](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checklist/wpcom-checklist/index.js#L331) can't find it.

For whatever reason we [default to a postID](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checklist/wpcom-checklist/index.js#L349) of `2` which may or may not exist :)

My suggestion is that, if we cannot find the headstart contact page, _we hide the entire **Personalize your Contact** checklist item_.

**Comment by ramonjd** [comment]
Actually, I tested in Italian (it) and got the same behaviour. Headstart complains that `pub/twentyfifteen does not have a Headstart annotation for the it locale.` Maybe it's related.

#28072 doesn't fix this, but makes it less annoying (I hope) :)
