### ISSUE TITLE
Gutenberg: make sure that we execute setup functions only once

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#27882]
Currently there are a couple of editor initialization methods that are executed whenever we navigate to the Gutenberg route:

- `registerDataPlugins` ([#](https://github.com/Automattic/wp-calypso/blob/8b9f204d8e94cdf7ba14f8b72e2cbcab4c47f8d0/client/gutenberg/editor/controller.js#L64))
- `registerCoreBlocks` ([#](https://github.com/Automattic/wp-calypso/blob/8b9f204d8e94cdf7ba14f8b72e2cbcab4c47f8d0/client/gutenberg/editor/main.jsx#L30))
- `disableTips` ([#](https://github.com/Automattic/wp-calypso/blob/8b9f204d8e94cdf7ba14f8b72e2cbcab4c47f8d0/client/gutenberg/editor/main.jsx#L32))

We should update the code to execute these only once.

**Comment by vindl** [comment]
@Automattic/team-calypso do you have any proposal for the placement of the initialization core that's better than just putting it in layout or app boot?

**Comment by jsnajdr** [comment]
> do you have any proposal for the placement of the initialization code that's better than just putting it in layout or app boot?

It needs to be place and time where the Redux store is already initialized and available, and where the initialization code is called only once.

As long as `@wordpress/core-data` does any initialization statically, triggered by merely importing the module, we also need to be very careful about the exact timing of `@wordpress` imports.

The function that's the default export of `client/gutenberg/editor/index.js` satisfies both conditions. Guaranteed to be called only once (after the Gutenberg section chunk is loaded) and only after Redux is booted. But you'll need to use `lib/redux-bridge` to access the store. Can use top-level `import`s.

The other good place is the `post` controller, in a block wrapped with `lodash/once`. Redux store is in `context`, but it will need the old-fashioned `require` calls for `@wordpress` packages, because `import`s can be only at top level and here we are inside a function scope.

```js
const init = once( () => {
  registerDataPlugins();
  require( '@wordpress/core-data' );
  return require( '@wordpress/editor' ).default;
} );

const post = ( context, next ) => {
  const GutenbergEditor = init();
  ...
};
```

The problem with imports could be also solved with dynamic `import( ... ).then` statements, which can be anywere, but the downside is that they create a new webpack chunk that's not really needed and requires one more network roundtrip to load. Maybe @b3n knows some webpack trick that avoids the need for `require`?

**Comment by blowery** [comment]
@jsnajdr I don't have any tricks up my sleeve here. It is another place where being able to do work around module init in a cross-cutting way would be really nice...
