### ISSUE TITLE
Podcasting: Widget Doesn't Show Summary and Link to iTunes on AT Sites when Cover Image is Set

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#27957]
When a cover image is set for a podcast on an AT site, the Podcast widget doesn't display anything other than the widget title and category.  The image is missing as well as the `Subscribe via iTunes` link.

#### Steps to reproduce

1. Turn on podcasting on an AT site in Calypso (Settings > Writing) or wp-admin (Settings > Media)
2. Set a summary
3. Set a cover image
4. Save settings
5. Add Podcasting widget to any widget area and fill up all fields (title, iTunes Feed ID)
6. Save

#### What I expected

I expected to see the cover image and summary to appear on the widget, together with a link to the podcast on iTunes.

#### What happened instead

The cover image and link do not appear.  Only the widget title and the podcast title may be seen.  

<img src="http://cld.wthms.co/blQXmS+" width="600" />

Another side effect is that it causes other widgets in the same widget area to not show up.  In the sample there is supposed to be a Gallery widget below the Podcast widget.

Moreover, the Widgets section in the Customizer won't load properly, making it impossible to manage widgets from there.  The message `Your theme has X widget areas, but this particular page doesn’t display it.` appears.

<img src="http://cld.wthms.co/4z30n2+" width="600" />

These issues resolve when I remove the cover image.

<img src="http://cld.wthms.co/C7CcNt+" width="600" />

<img src="http://cld.wthms.co/kASEvm+" width="600" />

Issue doesn't happen on Simple sites.

#### Browser / OS version

Tested on Chrome version 69.0.3497.100  and Firefox version 62.0.3

p9F6qB-1E6-p2

**Comment by lancewillett** [comment]
Noting for @Automattic/delta-samus

**Comment by creativecoder** [comment]
I'm pretty sure this is still an issue.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
