### ISSUE TITLE
Validate for domains like httpwwwyourgroovydomain.com

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#27953]
To prevent accidental domain registrations like:

* httpwwwyourgroovydomain.com
* httpswwwyourgroovydomain.com
* wwwyourgroovydomain.com

can we add a validation check to prevent/provide a warning for domain registrations where http, https, and www are included in the domain name itself?

#### Screenshot / Video
![Domain Search](https://cdn-std.dprcdn.net/files/acc_677550/Ukggd7)

#### Context / Source
Seen in support #7137059-hc

**Comment by thehenrybyrd** [comment]
This would be great! I've seen a number of these recently - I'll keep an eye open to add reports to this.

**Comment by thehenrybyrd** [comment]
Ran into this again today, with "4httpwww" before the desired domain. #1614063-zen

**Comment by donalirl** [comment]
I believe this is still important and hopefully easy to implement, so keeping it open unless anyone feels strongly against.

**Comment by thehenrybyrd** [comment]
Agreed. This has slipped off my radar, but I'll try to keep an eye out again as I see this fairly frequently.

**Comment by SiobhyB** [comment]
Another +1! I see this from time to time and will make more of an effort to add examples here.

**Comment by lancewillett** [comment]
@wensco @kelliepeterson Have you seen similar reports to this one? Curious if you think it is worth addressing in the Calypso domain registration UI.

Steps to repeat:

1. On an existing site, go to Plans > Domains
2. Click "Add Domain"
3. Type `httpwwwyourgroovydomain.com` into the search

<img width="983" alt="Screen Shot 2020-04-27 at 17 06 31" src="https://user-images.githubusercontent.com/66797/80432549-73179f80-88a9-11ea-9275-e27ec3d36396.png">

Improvement would be to look for common mistakes like `http` or `www` in the domain name.

**Comment by kelliepeterson** [comment]
@lancewillett thanks for surfacing this. This is the first time I've seen this report - and note that it goes back some time. 

Looking at our userbase portfolio of domain names I see that we have 14 domains across www/http for April and about 330 domains across both www and http overall that have registration dates going back to 2016 - and that includes users who have paid for renewals of these domains/plans! I'm  also seeing that this isn't just a domain name issue, it's happening at the wp.com subdomain level. 

I wouldn't want to block this outright as there are legitimate users for both, but I'm sure we can put a warning notice/modal in place. 

It's now on our radar, but it doesn't feel like a huge priority based on these numbers. Let me know if you feel otherwise though.

**Comment by lancewillett** [comment]
Thanks for the context, @kelliepeterson. I am going to close as "won't fix" for now. We can continue to gather numbers on this in the future, to see if it happens enough to add warnings in the UI.
