### ISSUE TITLE
Activity Log: Indicate when backups are via VaultPress

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#27991]
Due to the quiet way that we install VaultPress and the fact that when the plan provisions correctly, most don't know that we've set that up, it can be confusing to folks when trying to restore as they don't know to look at the VaultPress site for instructions. We explain it on the Jetpack support page only for Rewind. This can lead some folks far astray and create LOTS of confusion.

Can we add a notification in the top of the AL when a site is still using VaultPress with a link to the support docs there?

originally reported by @tmmbecker via customer report 1456531-zen.

**Comment by tmmbecker** [comment]
Go away Stale Bot

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

Is this still a relevant issue now that VaultPress has been deprecated as of October 2020?

If not, would it make sense to close this issue with label `Closed - Won't Fix`?

**Comment by tmmbecker** [comment]
Thanks for calling this one out @worldomonation. VaultPress is actually not fully deprecated - we have lots of customers who still get backups via VaultPress through our legacy plans. We're simply not offering it as part of our new plan features. 

That said, things have changed significantly since this was posted so it's clear in Calypso now when backups are provided by VaultPress. Closing.
