### ISSUE TITLE
Domains: Verifying the proxied email

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#2801]
As discussed in #2258, if you fail to verify your domain (with a privacy) the first time and ask for a new verification email, the new email verifies the proxied email address, not the original one.

Therefore if you disable Privacy Protection for transfer, you'd end up with a non-verified domain.

**Comment by wensco** [comment]
Marking this as a wontfix. Domains with privacy are not required to verify since the email address of the privacy service is already verified. To fix this, we would have to require verification for all domains on registration, including those with privacy. This would likely increase suspensions and related user support.
