### ISSUE TITLE
Gutenberg: Audio/Video blocks media modal closes itself on edit

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#28115]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/gutenberg/post/, selecting a Premium or Business site.
2. Add an `Audio` or `Video` block, and insert an audio or video file through the media library.
3. Save and reload.
4. Select the block and click on the pencil button in its toolbar.
5. Click on the media library button.

#### What I expected

The media modal opens and stay open.

#### What happened instead

The media modal closes itself immediately.
This only happens the first time I edit a block opening the media modal. All subsequent times work as expected.

**Comment by mmtr** [comment]
@Copons I found something that might be related to this issue, but maybe I'm totally wrong 🤷‍♂️ 

The first time the modal is opened, [`getSelectedItems`](https://github.com/Automattic/wp-calypso/blob/9cd0e267f01a7a24202f2b0e65cbe3cad628ec3b/client/gutenberg/editor/hooks/components/media-upload/index.js#L96) returns an empty array because `this.props.value` is `undefined`. However, all the subsequent times it returns something since `this.props.value` contains a value.

Maybe there is an asynchronous request fetching data that sets something in `this.props.value` and this change from `undefined` to something is causing to hide the modal?

**Comment by Copons** [comment]
Thanks for checking @mmtr!

I think this is caused by an excessively generous use of `MediaStore.on( 'change', this.updateMedia );`, or at least, commenting that line would fix this (and of course introduce a number of other issues).
