### ISSUE TITLE
Gutenberg: Fix scroll bleed

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#28168]
Context: https://github.com/Automattic/wp-calypso/pull/28149#issuecomment-434208968

Gutenberg uses `overscroll-behavior-y: none` to prevent the scroll bleed (when scrolling a div, reaching its scrolling edge starts scrolling the div behind) of popovers and modals on the editor content.

For some reasons, that rule prevents scrolling the editor content altogether, so it has been removed in #28149.
Though, we should find a more appropriate solution to the issue that:
- Prevents the scroll bleed.
- Removes the double scrollbars.
- And, of course, keeps the editor scrollable.

**Comment by jasmussen** [comment]
Well to clarify, Gutenberg avoids scroll bleed by scrolling the `.edit-post-layout__content` element, as opposed to the `body` element. This means they are separate containers that scroll separately. 

Gutenberg in Calypso as it is implemented currently, scrolls `body`, and then subsequently scrolls the Block Library which is, obviously, a child of `body`, and because of this hierarchy the scroll bleed issue appears.

**Comment by obenland** [comment]
This should work now with Gutenframe (p3fqKv-6Hh-p2).
