### ISSUE TITLE
Sites: error message is not centered for My Site on a username-only account

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2824]
Steps to reproduce:

1. Sign in to https://wordpress.com/ with a username-only account
1. Click My Site

<strong>Result:</strong> error message and "Create Site" prompt are not centered:

> You don't have any WordPress sites yet.
> Would you like to start one?

![screen shot 2016-01-27 at wed jan 27 8 25 47 am](https://cloud.githubusercontent.com/assets/1119271/12614745/c7667946-c4cf-11e5-9f18-3eb342f25e6c.png)

<sup>Seen at https://wordpress.com/stats/insights using Firefox 44.0 on Mac OS X 10.10.5</sup>

Similar: https://github.com/Automattic/wp-calypso/pull/1038

Found during user testing. (p4hfux-PJ-p2#comment-3819)

/ht @mjangda for the original report

**Comment by kjbenk** [comment]
This can also be replicated by going to the `/calypso` endpoint, for example `http://calypso.localhost:3000/calypso/`.

It seems that there is some disconnect with the 404 page and also having the fixed dashboard navigation sidebar on the left.  If you simply remove the class `wp-content` from the div within the 404 page, then the content will be centered since there is no sidebar.  The code can be found [here](https://github.com/Automattic/wp-calypso/blob/master/server/pages/404.jade#L19).

![Off Centered 404 page]
(https://cldup.com/_X7-35bpQa.png)

**Comment by jeremeylduvall** [comment]
Should be fixed in #2989!
