### ISSUE TITLE
Gutenberg: likes and shares are not respected

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28332]
![screen shot 2018-11-06 at 2 14 42 pm](https://user-images.githubusercontent.com/1270189/48097302-60e60500-e1ce-11e8-8c24-3264f8949506.png)

#### Steps to reproduce
1. Starting at URL: Make sure your simple site is Gutenberg enabled
2. Edit a post
3. Uncheck likes / Share
4. Publish

#### What I expected
Likes and shares to not be visible on the published post.

![screen shot 2018-11-06 at 2 16 53 pm](https://user-images.githubusercontent.com/1270189/48097460-c4703280-e1ce-11e8-800e-15fcb79a2c38.png)

#### What happened instead
Settings are not reflected in the published post, or if we edit it again.

**Comment by gwwar** [comment]
Should be okay to disable this until we fix functionality, like with the writing helper.

**Comment by kwight** [comment]
Disabled in D20459-code, ready for review.

**Comment by codebykat** [comment]
I'm going to try to work on fixing this, though we should go ahead and merge the patch to disable it in the meantime.

**Comment by alisterscott** [comment]
Related issue with support feedback: https://github.com/Automattic/wp-calypso/issues/28528

**Comment by arunsathiya** [comment]
7521188-hc - User had to switch back to classic-editor to control the sharing buttons on a per-post basis.

**Comment by arunsathiya** [comment]
@dwainm That sounds similar to https://github.com/Automattic/wp-calypso/issues/29930. Is that the same? If so, it's being tracked at https://github.com/Automattic/wp-calypso/issues/28973

**Comment by KokkieH** [comment]
Another report of the Likes and Shares module being missing from the classic editor in WP-Admin with GB activated in https://en.forums.wordpress.com/topic/social-media-buttons-not-showing-for-few-posts/

**Comment by kwight** [comment]
Note that this is being worked on, no hard ETA though: https://github.com/Automattic/wp-calypso/pull/29744

**Comment by molszewska** [comment]
Another one: 
Likes and Shares Module not available in Block editor on per-post/page basis. Available in wp-admin, though.
#1751556-zen

**Comment by sarahfg** [comment]
The Likes and Share modules are not available in Gutenberg in either wp-admin or Calypso. Sharing buttons do not show on posts even though enabled in the general site sharing settings. Disabling/enabling buttons in the Sharing settings did not touch a previously published post. #1782886-zen . To get the sharing buttons to show on a post I had to 

1. Switch to classic editor. 
2. Check Show buttons
3. Update post
4. Switch back to block editor

**Comment by KokkieH** [comment]
Another request in https://en.forums.wordpress.com/topic/sharing-tab-option-missing-in-the-new-editor/ for per-post settings to control Like and Share buttons.

**Comment by SiobhyB** [comment]
Another user who wants to control sharing buttons on a per-page in 1846163-zen.

**Comment by scosgro** [comment]
User's Sharing Buttons were not appearing on a post.

Options to turn them on were not available in Gutenframes on Simple WordPress.com site. I had to access WP-Admin Classic (since they couldn't on their end), and turn the Sharing Buttons on on the post from there. 

The option is available on Atomic (Likes and Shares), but not on Simple. 
#11057129-hc

**Comment by arunsathiya** [comment]
>(since they couldn't on their end)

The problem seems to be that,

- When users check, it takes them to `https://example.wordpress.com/wp-admin/post.php?post=1034&action=edit&classic-editor`
- When we check, it takes us to `https://example.wordpress.com/wp-admin/post.php?post=1034&action=edit` which shows the Likes and shares under Screen options.

For now, it looks like they have to give up WordPress Editor (block editor) to move to Calypso on WordPress.com/classic-editor on wp-admin to be able to see the sharing buttons section.

**Comment by formosattic** [comment]
Another request to control Like button on a specific page. 1865334-zen

**Comment by eduardozulian** [comment]
Also on 11129498-hc. Ended up disabling Likes and enabling shares in the homepage, manually, for the user.

**Comment by jonnyruzek** [comment]
Likes and sharing are being problematic in 1852384-zen.

**Comment by eduardozulian** [comment]
One more: 1875880-hc. Also disabled likes for the user from our end (non-Gutenberg wp-admin).

**Comment by AtrumGeost** [comment]
Hi folks!

This seems to also be affecting the sharing buttons display when you "copy" a page or post.

### Steps to reproduce:

1. Create a page with the sharing buttons enabled.
2. Use the Jetpack's feature to "copy" that page.

### What happened:

When you visualize the page you'll notice that it's not displaying the sharing buttons

### What happened:

To see the share buttons as on the original page.

### Screenshot:

![Screen Shot on 2019-03-17 at 09:22:26](https://user-images.githubusercontent.com/3696121/54492623-33a11600-4896-11e9-9f5f-877f26fe0ac9.png)

### Workaround

What I had to do to get the sharing buttons to show up was to switch to the "Classic" editor and click on "Update".

### More details:

This problem is specific to WordPress.com sites, I tried with a WordPress.org site with Jetpack configured and couldn't replicate the issue.

Also this doesn't happen on simple sites when using the classic editor when you copy the post.

User report: 1865324-zen

PS: _I think_ this could be caused by the main issue that's initially reported here. But if not, please let me know and I'll create a new GH issue. Cc @gwwar so you can share your insights :)

**Comment by scosgro** [comment]
Another one.

User had a post that had a Like button on it that they were unable to turn off. I manually accessed the Classic WP-Admin editor on the post for them and turned it off from there. #1885153-zd

**Comment by scosgro** [comment]
Another one. User had a few pages and one post where sharing buttons were not turned on, and they wanted them on.

Had to manually hop in to the user's WP-Admin Classic Editor for them and turn them on. #1891820-zd

**Comment by GeoJunkie** [comment]
Had this come up in 11371420-hc. User wanted to turn off sharing buttons in their featured post. Had to do it for them because they don't have access without switching editors

**Comment by kwight** [comment]
@AtrumGeost hi! Would you mind splitting the Copy one out to a new post, so we can make sure it doesn't fall through the cracks? Thanks!

**Comment by AtrumGeost** [comment]
Thank you @kwight , created the GH issue here #31575

**Comment by khristiansnyder** [comment]
Had this come up in 11592379-hc. I had to manually turn off the sharing for one of their pages for them.

**Comment by AtrumGeost** [comment]
Hi folks!

It seems this issue is getting worse. I remember that in the past we had the option to recommend the user to use the classic editor by going to WP Admin. But I got a user that is missing the sharing buttons option even when using the classic editor.

Found a similar case here: p1551728558489600-slack-livechat

Here are some screenshots of what I noticed (you can onñy reproduce that by SSP'ing into the user's site):

**Comparing the WP Admin Classic editors:** 
![Screen Shot 2019-03-27 at 11 38 36](https://user-images.githubusercontent.com/3696121/55095650-7fb63c80-5086-11e9-9da2-cc91f0ee35b1.png)

**Checking the screen options:**
![Screen Shot 2019-03-27 at 11 41 20](https://user-images.githubusercontent.com/3696121/55095662-85138700-5086-11e9-80a1-ed1986103370.png)

Once again, please let me know if I need to report it as a separate issue :)

**Comment by arunsathiya** [comment]
@AtrumGeost That sounds a lot like what I mentioned here - https://github.com/Automattic/wp-calypso/issues/28332#issuecomment-471144401

When users have WordPress Editor (Gutenberg) enabled and visit classic-editor for a post/page, the options would be missing.

They would have to give up on WordPress Editor (Gutenberg) and move back to classic-editor (which includes Calypso editor as well), and then visit wp-admin to be able to see the options.

**Comment by gwwar** [comment]
cc @codebykat for the missing options with the classic params

**Comment by JessBoctor** [comment]
I had a similar issue in chat. I had to log into the customers admin to enable the share buttons for their post #11617286-HC

**Comment by codebykat** [comment]
Happy to report this is FINALLY available in Gutenberg! See https://github.com/Automattic/jetpack/pull/12032 .
