### ISSUE TITLE
Signup: Resuming a flow

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#28401]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/developer (with an existing account)
2. Create a site
3. Go to the site
4. Go back to https://wordpress.com/start/developer

#### What I expected
I should be able to create a new site

#### What happened instead
I am stuck on the loading page

#### Browser / OS version
Chrome/OSX

#### Screenshot / Video
<img width="1256" alt="screenshot 2018-11-08 at 16 24 10" src="https://user-images.githubusercontent.com/275961/48212100-d094f500-e372-11e8-9e2b-77b1f9a60aeb.png">

**Comment by lancewillett** [comment]
Closing is duplicate of #28196

**Comment by lancewillett** [comment]
Actually, this is different — specific to the `/start/developer` flow. What is that exactly? Do we need to support it?

**Comment by scruffian** [comment]
I think it's specific to any flow that has only two steps (/start/private) does the same thing.

**Comment by p-jackson** [comment]
The `/start/developer` flow is used when deving calypso locally. When running on localhost for the first time you'll see:

![Screen Shot on 2019-07-29 at 14:27:14](https://user-images.githubusercontent.com/1500769/62018013-f87ffd80-b20c-11e9-898f-51b62d8e77cc.png)

So not a critical flow, but nice to have to smooth the onboarding process :)

**Comment by Tug** [comment]
Quick ability to resume a flow for `/start/user` was added on https://github.com/Automattic/wp-calypso/pull/36444/files#diff-46ce4cd8580489aebbb3447a87c3cb57R89

**Comment by scruffian** [comment]
This is still broken if you take these steps.
1. Open an incognito window
2. Go to wordpress.com/start/developer
3. Create a site
4. Fill in the user step
5. Get redirected to /devdocs/welcome
6. Click the back button
7. You'll see the "creating site" screen

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
