### ISSUE TITLE
Editor: YouTube embed block not displaying video in editor

### ISSUE THREAD

**Issue by blazevivan** [Automattic/wp-calypso#28424]
#### Steps to reproduce
1. Add new YouTube block
2. Paste Youtube link
3. Video is not visible in editor
4. Click on post preview
5. You can see the YouTube video

#### What I expected
To see the Youtube video in the editor. 

#### What happened instead
Text field for video caption shows up

#### Browser / OS version
Chrome v.70.0 , Win10 v.1803

#### Screenshot / Video
https://cld.wthms.co/jWmFZb

#manual-testing

**Comment by gwwar** [comment]
Verified that we're getting some inconsistent embed loading/previews on horizon /gutenberg.

@Copons I'm also seeing the following error for a plugin that was removed in #28888

<img width="465" alt="screen shot 2018-11-29 at 5 51 07 pm" src="https://user-images.githubusercontent.com/1270189/49263461-7df1aa80-f3ff-11e8-88a3-f7f1c2925812.png">

Did we need that or do we have more editor components to update?

**Comment by Copons** [comment]
I'm looking into this.

I can reproduce on horizon but not in dev and wpcalypso.
There is indeed an error in how I've modified the `ToolsMoreMenuGroup` slot logic:

```diff
- 	{ ( fills ) => ! isEmpty( fills ) && (
-		<MenuGroup label={ __( 'Tools' ) }>
-			{ fills }
-		</MenuGroup>
-	) }
+	<Slot fillProps={ fillProps }>
+		{ fills => ! isEmpty( fills ) && { fills } }
+	</Slot>
```

Basically I've left the brackets around `{ fills }`, so it incorrectly tries to destructure.

Though, I don't think this is related? 🤔 

The reason why I've unregistered the `edit-post` plugin is because it's used to [add the Tools section to the More menu](https://github.com/WordPress/gutenberg/blob/2a9d9a4a7823d5bb27e4088a539318a162b222f5/packages/edit-post/src/plugins/index.js), and I've rewritten it from scratch.

Anyway, I'll try to remove the `ToolsMoreMenuGroup` from the More menu, and leave the `edit-post` plugin registered. Let's see if it fixes the issue.

**Comment by notnownikki** [comment]
I encountered this today, editing a post with a YT video in it on production.

The API request is fine. The block creates the sandboxed iframe fine, and does the aspect ration calculation fine. The iframe is set to the correct `width`, but the `height` is `0`.

We previously had to put in a css fix to make the iframe `100%` wide for it to display, so there might be something we need to do with height as well.

It's worth noting that we have classes applied for aspect ratio preservation that prevent us setting `height` to `100%` too.

**Comment by notnownikki** [comment]
Some progress. Adding `wp-embed-responsive` to the list of classes in `<body>` makes the videos display. They don't display perfectly - the edges are cut off as the content is too big for the editor - but they're not invisible any more.

I'm not sure where to add this in the Calypso code though, I just modified the DOM to test.
