### ISSUE TITLE
Purchases: Renewals: Use a temporary cart

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#286]
Reported originally by @scruffian.

Currently when we add a renewal to your cart you lose your old cart. If we used temporary carts for renewals this wouldn't happen.

**Comment by stephanethomas** [comment]
As mentioned during our last hangout, this is something that we could use for free trials as well.

**Comment by stephanethomas** [comment]
Also looking at one of my previous note it seems we don't really have to choose between persistent and temporary shopping carts (although temporary carts seem more appropriate here). The backend indeed supports cart identifiers which means that you can manage multiple carts at the same time, whatever their type.

**Comment by drewblaisdell** [comment]
After thinking about this a little bit and talking to @scruffian, I'm not sure that adding temporary carts are the best solution to the problem here.

> Currently when we add a renewal to your cart you lose your old cart.

- If renewals are a cart item, why shouldn't they be able to live in the cart alongside other items?
- If there is a compelling reason that renewals shouldn't live alongside other items in a cart, should renewals be a cart item?

A version of checkout without a cart is something we've already talked about building for free trial checkouts. I think that extending this so that it would be a checkout component for just trials/renewals might be a better solution to this problem. It would also sidestep the issue of how we message the idea of a temporary cart to users.

**Comment by stephanethomas** [comment]
Right now shopping carts are persisted since we set `temporary` to `true` for every `POST` call to the `/sites/:site/shopping-cart` endpoint. Surprisingly the REST API defaults to using temporary carts but we never took advantage of that.

You cannot retrieve the content of a temporary cart from the API - it's not stored anywhere. So posting the content of a temporary shopping cart to this endpoint is just a way to validate it, compute discounts, and retrieves some additional data. This is great because it means we don't pollute the main shopping cart, the one that is actually persisted and available across browsers and devices as long as the user is logged in.

So I feel the only challenge is to check how the `/me/transactions` endpoint reacts when we provide it with a temporary cart. I suspect passing the temporary cart (with `temporary` set to `true`) might be just enough. If that works fine, I guess the only challenge would be to update the `CartSynchronizer` to handle temporary carts - which seems to me much less work than building a trimmed down version of the checkout without a cart.

**Comment by Tug** [comment]
Updating the `CartSynchronizer` is actually more work than it appears to be since it is really tied to the `CartStore` singleton which is used everywhere. We could set the `CartStore`'s `temporary` property to `true` but then we need some custom logic to set in back to `false` at some point. There is also the poller which we need to stop while we're using a temporary cart...

We have actually been talking extensively about this issue with @drewblaisdell and we have decided to forget about synchronizing temporary carts with the API for now and deal with the issue in another way.

We have agreed that a free trial subscription should not need to actually redirect to the checkout page since they are not actual products (they are in the case of `wpcom` but they don't *necessarily* need to be since they will always be free, coupon won't apply to it, etc.)
So we don't really need to request the `/sites/:site/shopping-cart` endpoint here because we know the total is always going to be zero. We just want to call the transaction endpoint with a default cart which contains a free trial plan.

So in order to do this without making the code in `checkout.jsx` even more complex we are going to create a new controller at `/free-trials/:site/:typeOfPlan?` which will be responsible for displaying the free trial checkout page we have at the moment (without the Cart view on the left) and making the `/me/transactions/` ajax call to the API.

@scruffian @stephanethomas @fabianapsimoes: Does that make sense to you? 
If you have any objections or see any limitations to this, please discuss it here :)

**Comment by gziolo** [comment]
I like this idea. That would also resolve other related issues like #1538. At the moment it's possible to add free plan and other products to the cart ...

**Comment by fabianapsimoes** [comment]
> If renewals are a cart item, why shouldn't they be able to live in the cart alongside other items?
> If there is a compelling reason that renewals shouldn't live alongside other items in a cart, should renewals be a cart item?

@drewblaisdell just to add some context, this is something we discussed back when we were implementing `/purchases`, see https://github.com/Automattic/calypso-pre-oss/pull/11206#issuecomment-151889265. With how renewal flows were implemented, it's confusing to users to have more than one product / renewal in the cart given the strong tie between the Renew Now button and one single product. I'm not sure if there are any technical reasons to pursue this though.

**Comment by fabianapsimoes** [comment]
@Tug, @scruffian and I chatted about this in Slack (https://a8c.slack.com/archives/upgrades/p1452680839000206). This new controller would not solve the issue for renewals, only for free trials, so I'm moving it out from the Free Trials milestone and closing the PR we started in #2157.

We can continue discussing the new controller in #2374, which is the PR @Tug started.
