### ISSUE TITLE
Gutenberg: drag selected text

### ISSUE THREAD

**Issue by arcangelini** [Automattic/wp-calypso#28618]
In the Calypso editor it is possible to highlight and drag text to new location. This is not possible in Gutenberg. The cursor moves as if its going to be the drop spot of the text, but nothing happens.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/llamaeatsagiraffe.wordpress.com/75
2. Highlight chuck of text
3. Click and drag selected text to new location
4. Release text where ever you want

#### What I expected
In the Calypso editor it is possible to highlight text and drag to new location. [Like this](https://cld.wthms.co/r7Y6yb)

#### What happened instead
In Gutenberg this is not possible. [Like this](https://cld.wthms.co/21jvuI)

#### Context / Source
#user-report

**Comment by gwwar** [comment]
Marking as low, since this should resolve itself once we move away from Calypsoify flows, and we begin using the Calypso Classic block see also https://github.com/Automattic/wp-calypso/pull/28235

As a work around folks are welcome to transform via the "convert to blocks" option, which allows dragging in units of blocks.

![43929880-9ed7f5a4-9beb-11e8-9be6-24457582da22](https://user-images.githubusercontent.com/1270189/48985303-ecaacd00-f0ba-11e8-895d-1eb22d846344.png)

**Comment by gwwar** [comment]
I can't see the original screenshots anymore, but Gutenberg does have drag support for blocks and we do have a Calypso Classic block. Closing this out for now.
