### ISSUE TITLE
PayPal form code discrepancy in Gutenberg

### ISSUE THREAD

**Issue by thebud15** [Automattic/wp-calypso#28742]
In helping a user, I noticed a difference between how a Premium site takes a <form> code from PayPal based on whether Gutenberg was active. Traditionally, this kind of code is not allowed on Premium plan sites, but only on Business sites with plugins/themes. 

The code being used in this example is as follows:
```
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="ZJV9DJVLL62QS">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
```

#### Steps to reproduce

**Test A:**
1. Start a new post (in Calypso with the **new editor**).
2. Copy and paste the sample code above into the post in an HTML block.
3. Publish the post.

**Test B:**
1. Start a new post (in Calypso with the **classic editor**).
2. Copy and paste the sample code above into the post under the HTML tab.
3. Publish the post.

#### What I expected
**Test A & B:**
I expected the code not to work, as it's a <form> code. 

#### What happened instead
**Test A:**
With the new editor, the form code was converted into a shortcode showing a PayPal payment button. Here's how it looked:
```[paypal_button cmd="_s-xclick" hosted_button_id="ZJV9DJVLL62QS" img_src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif" alt="PayPal - The safer, easier way to pay online!"]```
It looked like a button was added on the published post and then apparently the code was removed on save. When trying to click the button, it appeared active, but then showed a message like this once clicked: 
![screen shot on 2018-11-20 at 16_50_03](https://user-images.githubusercontent.com/29046778/48811858-77b74c00-ece4-11e8-9cc8-3df31d6b40c3.png)

**Test B:**
Using the old editor, the PayPal button did not display at all. 

####General Thoughts

The UI makes it seems as if the PayPal button "works" when added to an HTML black in the new editor. This could lead to a negative user experience. If we plan to keep the <form> code to only Business sites, it might make sense to strip out more of what appears to be an active button when added to the new editor. 

#### Browser / OS version
Safari, 10.13.6 High Sierra

#### Screenshot / Video

Included above

#### Context / Source

 #manual-testing, #user-report

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
We also now have the [Pay with PayPal block](https://wordpress.com/support/wordpress-editor/blocks/pay-with-paypal/) for users to use in the block editor.
