### ISSUE TITLE
Editor: Page Templates Options Are Not Appearing Under Page Attributes

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#28808]
I was working on setting up theme Corporate with the user and have noticed that page template option is not showing in the Calypso editor  when you start creating a new page (not related to Gutenberg).

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/
2. Start creating a new page with a theme that requires page templates (e.g. Corporate)
3. Go to Page Settings and check options under Page Attributes

#### What I expected

To see an option to select templates

#### What happened instead

There was no option in Calypso: 

<img width="933" alt="screen shot 2018-11-22 at 2 33 41 pm" src="https://user-images.githubusercontent.com/25575134/48919913-aad41980-ee63-11e8-9b13-40d5a8afe2aa.png">

After I have added some content on the page itself, the page attributes appeared in Calypso but they were not initially there. 

In the WP-Admin, the option to see page templates was there when I opened a screen to create a new page. 

<img width="858" alt="screen shot 2018-11-22 at 2 34 39 pm" src="https://user-images.githubusercontent.com/25575134/48919947-d9ea8b00-ee63-11e8-90d6-78643a370b08.png">

I tested with theme Corporate and Sela.

**Comment by arunsathiya** [comment]
I was able to reproduce this with Sela theme as well. 👍🏽

**Comment by kwight** [comment]
I wasn't able to repro with either theme, but I'm not surprised you've had this experience; it looks like the API request to fetch page templates isn't fired until a user actually clicks on "Page Attributes" (so if anything but an immediate valid response happens, that Page Templates component doesn't render). This is good when network performance is great because we're not requesting data before needed, but obviously poor if the network has any latency at all 🙃 

I'l look into maybe firing the request on hover (something I think we already do in other places).
