### ISSUE TITLE
Publicize Gutenberg integration: UI still available for posts that are already published

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#28810]
> Testing Publicize, I switched an old post from published to draft, then when I went to publish it again, the publicize connections were selected and I could edit the custom message, suggesting that the post would be publicized again, but on publish, as expected the post was not publicized.
> 
> Editing the same post in Classic Editor, the publicize options for old posts are disabled.
> It would be nice if on old posts, instead of just greying out the options, we show a message saying “Publicize is only available on new posts.” Or for sites with a Premium plan: “To reshare this post, go to WordPress.com”

**Comment by ockham** [comment]
> the publicize connections were selected

I cannot reproduce this part -- they are disabled for me. @danjjohnson Since you first reported this (at p1HpG7-5V3-p2 #comment-29150) -- Can you confirm that these toggles are enabled (i.e. can be toggled)?

> and I could edit the custom message, suggesting that the post would be publicized again,

This part I can reproduce.

Screenshot:

![image](https://user-images.githubusercontent.com/96308/49022793-040ab880-f196-11e8-9817-4a5c71874e2e.png)

Comparing to the Classic Editor, I think I'll start by disabling the message field so users aren't tempted to edit.

> It would be nice if on old posts, instead of just greying out the options, we show a message saying “Publicize is only available on new posts.” Or for sites with a Premium plan: “To reshare this post, go to WordPress.com”

Makes sense. I think we could use some design input here /cc @MichaelArestad @mapk

**Comment by danjjohnson** [comment]
@ockham yes, I just tried again, and the toggles are enabled, but only the first time the post is switched to draft. Once it's published again, the toggles are then disabled.

**Comment by ockham** [comment]
As clarified on p1HpG7-5V3-p2 #comment-29199:

> this was tested with the ‘Hello World’ post that every WordPress publishes upon installation — i.e. prior to any plugin (including Jetpack) being installed. The post thus was never publicized, so it makes sense that resetting its status to draft will allow to publicize it upon re-publishing. (The contract being that it’s only possible to publicize once.)
> 
> This is more of a technical limitation than anything else — Jetpack stores Publicize information that indicates whether a post has been published as part of the corresponding post object. But that means that any post that was published while Jetpack wasn’t active (and possibly connected, I’d need to check) doesn’t hold that information, and can thus be publicized when first re-published.
