### ISSUE TITLE
Gutenberg: Keyboard Shortcut Results in Backspace

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#28834]
#### Steps to reproduce
1. Starting at URL: https://horizon.wordpress.com/gutenberg/post/
2. Start a paragraph block
3. Write a word in it
4. Make it italics/bold
5. Hit your spacebar 
6. Use your keyboard shortcut to turn off italics (cmd + I on my device)
7. Type another character 
8. See issue

#### What happened

Instead of starting a new word without formatting, the text you type will just be added to your previous word, and remain in bold/italics.

#### What I expected

On previous editors, a new word will be started which has no formatting. This should happen with Gutenberg too.

#### Browser / OS version

Mac OS X 10.6.8
Chrome 49.0.2623.112

#### Context / Source

I found this whilst writing a post myself for the first time with Gutenberg. I'm used to being able to disable formatting for the next word with a keyboard shortcut, and I'm sure many others too. This bug ruins that flow with Gutenberg.

**Comment by vindl** [comment]
Thanks for the report @torres126! This issue seems to be occurring in core Gutenberg too. Could you please [report it there](https://github.com/WordPress/gutenberg/issues/new/choose) and link back here with the created issue?

We usually try to keep integration related issues in Calypso repository, and to escalate anything that also affects the core project in the Gutenberg repository. One easy way to rule out a core bug that I often use is testing with Gutenberg demo on https://wordpress.org/gutenberg/.

**Comment by torres126** [comment]
Thanks for that tip! It looks like this has been mentioned over there already, but I'll bare that tip in mind in the future. :)

**Comment by torres126** [comment]
WordPress/gutenberg#12529

**Comment by vindl** [comment]
Awesome, thanks for locating it! I forgot to mention an important step there - before reporting we should check if the issue already exist. :)

Closing since there is already a filed core issue for this: https://github.com/WordPress/gutenberg/issues/12529
