### ISSUE TITLE
Gutenberg Button Blocks with Odd Text Breaks on Mobile

### ISSUE THREAD

**Issue by thebud15** [Automattic/wp-calypso#28836]
#### Steps to reproduce
1. Open up Gutenberg page editor
2. Select a button block and create a button with text, which in this example is as follows: `Załóż konto w TransferWise i zrób przelew bez opłat`
3. Publish the block
4. Visit https://nerdontour.net/2018/11/02/finanse-w-ltd-w-uk/ on mobile (iPhone 7 on Safari and Chrome) and notice that the word zrób is split up onto two lines after the o, despite being one word. On the user's   mobile device (not confirmed which), the word `przelew` was split after the p.
5. In testing this on a test site, I was able to replicate. I tried pasting in HTML code of this button into the Button block and was presented with the option to Convert to HTML or to Blocks, in order to resolve an error that popped up, saying "This block contains unexpected or invalid content" with options to `Resolve` or `Convert to HTML`.
6. As this screenshot shows (after clicking Resolve), converting to Blocks initiates that cut off lettering, even on a desktop view (which is where this next screenshot comes from), but leaving it as HTML gives us the error mentioned in Step 5:

![screen shot on 2018-11-25 at 16 23 15](https://user-images.githubusercontent.com/29046778/48988452-7918b800-f0da-11e8-9624-dd7eebcae0cb.png)

#### What I expected
For each word to be kept together instead of getting split apart. 

#### What happened instead
The words were being split onto two lines in the mobile view. 

#### Browser / OS version
iOS 12, Safari and Chrome. 

#### Screenshot / Video

<img width="396" alt="screenshot 2018-11-26 at 11 11 05" src="https://user-images.githubusercontent.com/29046778/48988337-d6603980-f0d9-11e8-81e0-428602d7a766.png">

 #user-report

**Comment by thebud15** [comment]
Arose in 8328107-hc and moved to 1596279-zen

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
