### ISSUE TITLE
Posts tagged "Featured" appear in posts list when "...display tagged posts outside the Featured Content area" is off

### ISSUE THREAD

**Issue by caimin-j** [Automattic/wp-calypso#28957]
The "Also display tagged posts outside the Featured Content area" has no affect if the latest posts are being displayed on a separate page (rather than the homepage).

Regardless of whether the setting is on or off, posts with the "featured" tag always appear in the post list.  When the homepage is set to show "latest posts" the setting works as expected.

#### Steps to reproduce
1. Publish a post with the "featured" tag
2. Open Homepage Settings in customizer
3. Set a static homepage and a posts page
4. Open the Featured Content panel and uncheck the "Also display tagged posts outside the Featured Content area" setting.

#### What I expected
That the post tagged with "featured" would not appear in the posts list when "Also display tagged posts outside the Featured Content area" is unchecked.

#### What happened instead
The post appears regardless of the state of "Also display tagged posts outside the Featured Content area".

#### Screenshot / Video

<img width="1055" alt="screenshot 2018-11-29 at 18 38 27" src="https://user-images.githubusercontent.com/37620825/49240802-6bc73a80-f406-11e8-8c21-34cf74d567d0.png">

#### Context / Source
<!-- Optional: share your unique context to help us understand your perspective. You can add context tags such as: #journey #anecdote #narrative #context #empathy #perspective #reallife #dogfooding #livesharing #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

 #manual-testing #user-report

**Comment by lancewillett** [comment]
Hi @caimin-j -- at first glance this looks like it could be a theme display issue rather than a Calypso bug. Could you confirm which theme it happened with?

Depending on the theme, we can move it to the right bug report section of https://github.com/Automattic/themes

**Comment by caimin-j** [comment]
Hi @lancewillett Sorry for the delay in following this up.

Unless I'm missing something, this seems to be unrelated to the theme. I just tested it using a different theme (Canard) and got the same result:

<img width="1209" alt="Screenshot 2019-06-11 at 10 18 40" src="https://user-images.githubusercontent.com/37620825/59259935-91918f80-8c32-11e9-817c-f913ab33f803.png">

In the screenshot above "read more test" is the same post.

**Comment by donalirl** [comment]
Discovered this happening with the Chronicle theme in #2852615-zen and the Prosperity theme in #2837187-zen. Chronicle is retired, but Prosperity is not.

Doesn't seem to be theme-specific. Several themes share this mechanism, it seems?

**Comment by lancewillett** [comment]
I investigated this report a bit today.

Not all themes are the same, so when reporting an issue for "featured posts still show up in two places" —  look a bit at the theme itself.

Check first how it works with featured content.

1. Does the featured content show on both static home and non-home Posts page? If featured content section displays on the non-home Posts page -- this bug report would apply.
2. Does the featured content show with a special home page template? Like Prosperity. This cases wouldn't be filtered by the plugin because the home page template uses a special query (not a blog posts list as normal).

For themes like Canard and Chronicle, they fit into case 1. Plugin needs to be updated to account for the case of posts page being set to show blog list. A fix started here: D42426-code.

**Comment by lancewillett** [comment]
Prosperity theme-specific fix deployed (see ticket 3006 in premium themes Trac).

**Comment by lancewillett** [comment]
Related Jetpack bug and pull request:

- https://github.com/Automattic/jetpack/issues/3650
- https://github.com/Automattic/jetpack/pull/15562

**Comment by rinazrina** [comment]
I got a similar report with Aquene theme in #3543602-zen

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
