### ISSUE TITLE
Cover Block: Unexpected Text Alignment When Inserting Line Breaks

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#28969]
#### Steps to reproduce
1. Insert a Cover block
2. Add an image
3. Set to full-width
4. Insert many lines of text, I tested 8 lines with three additional line breaks (11 total text lines).

#### What I expected

The text should appear above the image as it does in the editor, with the line breaks intact.

#### What happened instead

The text before the line breaks is aligned left with the rest of the text aligned right in a different color.

#### Browser / OS version

Test in Chrome on macOS Mojave

#### Screenshot / Video

<img width="1093" alt="screen shot 2018-11-29 at 2 32 35 pm" src="https://user-images.githubusercontent.com/42454301/49254597-99f14e00-f3f7-11e8-9edd-7c45eddaf13b.png">
<img width="1360" alt="screen shot 2018-11-29 at 2 32 26 pm" src="https://user-images.githubusercontent.com/42454301/49254598-9a89e480-f3f7-11e8-8307-7b78b56d5a7e.png">

#### Context / Source

#user-report
1607202-zen

**Comment by lancewillett** [comment]
Hi @mdrockwell -- this looks like it could be a theme display issue rather than a Calypso bug. Is that right? (Also noting Gutenberg blocks from core would be tracked and reported in a separate place: https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+cover+block+label%3A%22%5BBlock%5D+Cover%22)

What I understand you saying is that for a given theme — the block display in the editor doesn't show up properly on the front-end of the website.

This most likely will turn out to be a theme fix rather than a Gutenberg block editor or Calypso site management issue.

**Comment by mdrockwell** [comment]
@lancewillett I'm not able to recreate the issue anymore, so this could have been fixed in subsequent changes to the theme (there were some Gutenberg-related updates [several months ago](https://wpcom-themes.trac.automattic.com/log/button-2)) or in updates elsewhere. I'll go ahead and close the issue for now.
