### ISSUE TITLE
Gutenberg: Tags not available on Pages

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#28975]
#### Steps to reproduce
1. On a Gutenberg enabled Calypso site
2. Activate [Venture theme](https://wordpress.com/theme/venture/setup) on site
3. Create a new page, and add a tag.

#### What I expected
Tags should be able to add on pages, similar as the classic editor.

#### What happened instead

Adding tags is available on the wp-admin dashboard for pages, and also on the classic editor on Calypso.. For example, this would help featured content from [Venture theme](https://wordpress.com/theme/venture/setup) to display pages on the slider. (You will need to activate this theme to see this)

#### Screenshot / Video

Here's a sample image on the tag feature on the classic editor.

![image link 2](https://cldup.com/07UMWoNWHn-300x300.png)
image link: https://cloudup.com/cU9MzMFDEEf

#### Context / Source

chat: #8450799-hc
ticket: #1608134-zen

**Comment by apeatling** [comment]
@vindl I'd love to see this one fixed, since support is there for tags on posts, we must be able to turn it on without a ton of trouble for pages.

**Comment by vindl** [comment]
> @vindl I'd love to see this one fixed and considered a blocker, since support is there for tags on posts, we must be able to turn it on without a ton of trouble for pages.

After some further investigation, there are two reasons why I believe this shouldn't be considered a blocker:

- This issue is already present in Calypsoify, so by launching it we won't be introducing a new bug to production. It's already there.
- Adding tags to pages is not enabled by default - this is something that theme/plugin has to override. So this is not a widespread issue and it affects only themes that allow this capability. In all other cases what we have in Calypsoify/Gutenlypso matches the Classic editor functionality (no Tag accordion shown).

So @rodrigoi I'd say let's prioritize a fix on this still, but if we don't get it in time for launch I'm inclined not to block it just because of this. I assume this is somewhat similar to wide image capabilities, and we are not passing through the theme capability from the API to editor settings when initializing.

I haven't checked yet, but there is a good chance this is a core bug, given that it's present in wp-admin integration too. If that turns out to be the case, let's report issue in Gutenberg core repo, close this one and move on.

**Comment by rodrigoi** [comment]
More context on p7jreA-20e-p2

**Comment by supernovia** [comment]
We had one come up here:
https://en.forums.wordpress.com/topic/page-in-featured-content/
