### ISSUE TITLE
Comments: Link to image attachment don't work

### ISSUE THREAD

**Issue by fstath** [Automattic/wp-calypso#28982]
#### Steps to reproduce
1. Starting at URL: https://fstatwp.wordpress.com/2018/11/30/image-comment-test/#jp-carousel-36
2. I left a comment

#### What I expected
To be able to see the image or the post related to that comment when moderating that comment on Calypso (https://wordpress.com/comments/approved/fstatwp.wordpress.com/36)

#### What happened instead
No image preview is shown and when I click on the "View post link" I get a message that reads "Post unavailable - Sorry, we can't display that post right now."

#### Screenshots
<img src="https://cldup.com/AIDEyF0qAr.png" alt="Comment in Calypso">
<img src="https://cldup.com/_N7bQUdY92.png" alt="Post unavailable">
<img src="https://cldup.com/vqxO3QHx10.png" alt="Comment in WP Admin">

#### Context
On WP Admin the the comment shows a preview to the image and the link to the attachment work as expected.

Reported by a WordPress.com forum user:
https://en.forums.wordpress.com/topic/cannot-see-fotos-that-were-commented/

**Comment by rachelmcr** [comment]
I just ran into this issue on a personal site:

* I received a notification about a new, pending comment on my site.
* I wasn't sure what post (or even what site) the comment was left on, so I clicked the link to the post in the comment notification.
* I was taken to the Reader with the "Post Unavailable" message there.

I was able to work around this issue in my browser by right-clicking the link to the post in the notification and opening it in a new tab, which opened it directly on my site (so I could see what post it was). It ended up being a comment made on an unattached image on my site.

However, the same issue affects comment notifications in the WordPress apps and is more of a problem there, since there isn't an equivalent workaround.

Example screenshot showing where I clicked:

![Screenshot 2019-09-30 12 51 54](https://user-images.githubusercontent.com/8658164/65876630-9ca73180-e381-11e9-9982-cf916a523dad.png)
