### ISSUE TITLE
Gutenberg: Default Categories aren't Checked

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#29272]
#### Steps to reproduce
1. Starting at URL: /wp-admin/options-writing.php
2. Select a Default Post category and save
3. Write a post using Gutenberg (https://horizon.wordpress.com/block-editor/post)
4. Navigate to the "Categories" section on the sidebar
5. There's nothing to indicate that a category has automatically been assigned

#### What I expected

Previously in the editor, it'd be made clear that category has been assigned. So, the checkbox next to the default category should be ticked in Gutenberg too, and if it becomes un-checked manually, that category should not be assigned for that post. 

#### What happened instead

There's nothing to indicate that the category has been assigned, which is confusing should you wish to not use the default category for a single post. 

#### Browser / OS version

Mac OS X 10.6.8, using Chrome - this issue probably affects all browsers & devices though

#### Screenshot / Video

![gsdfsfgdsgfdsdfg](https://user-images.githubusercontent.com/43215253/49703678-deeb6080-fbff-11e8-9eee-cb6dd252a82a.png)

#### Context / Source

Found when writing a post where I didn't want to use a default category, which caused me to be confused.

**Comment by alisterscott** [comment]
Hi @torres126 

Thanks for raising this issue. I did some further testing and saw it was assigned when the first draft of a post is saved - did you see that same behavior?

I tested this against the master branch of [Gutenberg](https://github.com/WordPress/gutenberg) and it behaves the same way. Would you like to raise this as a bug or enhancement to [Gutenberg](https://github.com/WordPress/gutenberg/issues)?

I'll close this since it's not specific to WordPress.com Calypso.

Thanks

**Comment by torres126** [comment]
I did see that behaviour, yep, and will do, thank you! :)
