### ISSUE TITLE
Gutenlypso: Classic editor's block options not showing up as expected

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#29569]
#### Steps to reproduce
1. Create a post or page and add a classic block with content
2. Try to access to the block options. (This is necesary for situations like when you want to convert the classic editor block to blocks)

#### What I expected

To see the block options in an easy way. In the same way it happens with other blocks:

![screen shot 2018-12-18 at 17 29 52](https://user-images.githubusercontent.com/3696121/50186986-a6781080-02ea-11e9-98b9-14250a07b8a7.png)

#### What happened instead

The classic editor block options were not visible until I clicked on the classic editor toolbar or until I added a block on top of it:

![screen capture on 2018-12-18 at 17-27-44](https://user-images.githubusercontent.com/3696121/50186944-73ce1800-02ea-11e9-97fb-1602822bab42.gif)

#### Browser / OS version

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
macOS Mojave Version 10.14.1

#### Context / Source

I found this due to a #user-report and was able to replicate it on a test site

Reference: 8914555-hc

PS: For some reason when I tried this for the first couple of times, the "Convert to blocks" option wasn't working. However, it is working now

**Comment by kwight** [comment]
Hm, I'm unable to reproduce neither the lack of options, nor the Convert to blocks not working. Any other ideas of how to replicate?..

**Comment by AtrumGeost** [comment]
Thanks for checking @kwight ! The first time you add the classic block it will display the options. But if you click outside and then click on it again, the options are gone until you click on the classic editor toolbar:

![screen capture on 2018-12-18 at 19-47-01](https://user-images.githubusercontent.com/3696121/50191889-e72d5500-02fd-11e9-94d3-a13e4bab0b01.gif)


As for the "Convert to blocks" option not working. That was a one-moment thing that I wasn't able to replicate again :/

**Comment by Copons** [comment]
This seems to be caused by the fact that the text editor inside the Classic block is in a separate iframe, whereas the toolbar isn't.

Events dispatched inside an iframe don't bubble up outside it.
For this reason, the Gutenberg block component can't listen to any clicks happening inside the editor, and so can't show the block toolbar.

This happens in Core as well, but they fixed this by adding the block options dropdown in the TinyMCE toolbar, and disabling the block toolbar altogether for the Classic block:

![screenshot 2018-12-20 at 17 32 34](https://user-images.githubusercontent.com/2070010/50300778-5ed5be00-047d-11e9-83e7-8127e55be73f.png)

This is a tricky one as I don't think there is a way to force an event to bubble outside an iframe, and rewriting the Classic editor toolbar to handle this case is likely a big effort. 🤔

**Comment by vindl** [comment]
Until this is fixed properly one workaround for showing the block options again would be to select the Classic block in Block Navigation:

<img width="325" alt="screenshot 2018-12-21 at 05 41 31" src="https://user-images.githubusercontent.com/1182160/50325136-6b8cfd00-04e3-11e9-869c-906412feef1b.png">

**Comment by Copons** [comment]
> Until this is fixed properly one workaround for showing the block options again would be to select the Classic block in Block Navigation:
> 
> <img alt="screenshot 2018-12-21 at 05 41 31" width="325" src="https://user-images.githubusercontent.com/1182160/50325136-6b8cfd00-04e3-11e9-869c-906412feef1b.png">

Probably easier to just click on the TinyMCE toolbar. 🤔 
Either way, it's a very bad UI.
