### ISSUE TITLE
Tiled Gallery Block: When clicking on a gallery carousel the carousel starts at the first image regardless of image clicked

### ISSUE THREAD

**Issue by jeremypaavola** [Automattic/wp-calypso#29800]
Reported in 1673669-zen

#### Steps to reproduce
1. Ensure that Jetpack's Carousel module is enabled (https://jetpack.com/support/carousel/)
2. Create a new post with the Carousel module as normal
3. Browse the carousel, noting that any image clicks results in the carousel starting from the beginning

#### What I expected

When clicking on a gallery item I expect the carousel to open at that item, rather than at the beginning.

#### What happened instead

The carousel opened at the beginning of the carousel, forcing me to scroll through to the item I wanted to view initially.

#### Screenshot / Video

https://cl.ly/4fdd1eb6638c/Screen%20Recording%202018-12-29%20at%2010.15%20am.gif

**Comment by htdat** [comment]
This issue is not related to Tiled Gallery Block as it has not been available to users yet. 
Instead, it's the issue with Jetpack Carousel and the default WordPress gallery block. 

I confirm this issue in my testing site. 

@Automattic/jetpack-crew - can you have a look? Should we keep this issue here or move it to `jetpack` repo?

**Comment by jeherve** [comment]
That's a known issue, and it was fixed in https://github.com/Automattic/jetpack/pull/11022

The fix will be included in the next Jetpack release, and is already available to WordPress.com users.
