### ISSUE TITLE
Gutenberg: images added from free photo library cause an invalid block

### ISSUE THREAD

**Issue by notnownikki** [Automattic/wp-calypso#29928]
#### Steps to reproduce
1. Add a new image block
2. Insert from media library
3. Select the "free photo library" using the top left icon
4. Insert the image
5. Save the post
6. Refresh the page to reload the post

#### What I expected

The image block should be ok.

#### What happened instead

The image block has a notice about unexpected HTML

<img width="898" alt="screen shot 2019-01-08 at 3 34 20 pm" src="https://user-images.githubusercontent.com/1270189/50865540-fcc0f800-135a-11e9-84ca-9dd408fc4fc7.png">

**Comment by gwwar** [comment]
Looks like the block doesn't like that class attribute here? 🤷‍♀️

**Comment by Copons** [comment]
> Looks like the block doesn't like that class attribute here? 🤷‍♀️

@gwwar That seems to be the case.

The block expects the class to be `wp-image-{ imageId }` (e.g. `wp-image-12345`).
Though, when inserting images from external sources, we don't have the image ID ready yet, but have to first upload it.

What happens there seems to be that when we insert an external image, we upload it in background, but never update the block.
So, the class gets the image temporary ID (e.g. `media-123`, that becomes `wp-image-media-123`) that doesn't match the expected format, breaking the block.

At the same time, other issues happen:

- We never replace the block `src` with the uploaded image path, so we end up hotlinking Pexels or Google Photos.
- We use the temporary ID (`media-123`) for the subsequent `/media` calls (e.g. `/media/media-123` instead of `/media/12345`), returning a 404.
This might be the cause of #31371.

Also interesting to notice that Gutenberg relies on the image class for the `/media` calls, because I've tried modifying it in the block HTML by using a random number, and soon after it called `/media/{ randomNumber }`.

**Comment by gwwar** [comment]
@copons we should have an id by the time of the second edit right? I'm thinking we can relax parsing and make sure it serializes to the expected format on the second save. The filter `blocks.getBlockAttributes` may help us here.

For example I used this in my personal project, to change the internal format:
https://github.com/gwwar/emoji-tasklist/blob/8a0d039ba1adbf843807bd28d08a9526e98e9e45/src/block/block.js#L114
