### ISSUE TITLE
Menus: Alignment issue with undo link in `is-info` notice after deleting menu

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#3]
The alignment of the undo link in the **is-info** notice that appears after deleting a menu is slightly off center.

Steps to reproduce:

1. Navigate to `My Site > Menus`: https://wordpress.com/menus.
1. Select **Add new menu** from the second dropdown menu.
1. Click on the trash icon next to the **Save** button in order to delete the newly added menu.

Results:

After deleting the menu, an **is-info** notice appears towards the top of the page with an option to undo the deletion. The alignment of the undo link is slightly off centre as shown in the following screenshot:

<img width="1088" alt="screen shot 2015-11-13 at 18 39 04" src="https://cloud.githubusercontent.com/assets/2998162/11154248/13138a70-8a36-11e5-92aa-a74d5447d80e.png">

**Comment by montogeek** [comment]
Hi!

This issue was fixed.
This is how it looks at this moment on Wordpress.com
![screen shot 2016-02-01 at 23 07 13](https://cloud.githubusercontent.com/assets/1002461/12739548/9cebcb90-c938-11e5-8251-8a9e2d462b7b.png)

On Calypso:
![screen shot 2016-02-01 at 23 08 47](https://cloud.githubusercontent.com/assets/1002461/12739572/cfa3835c-c938-11e5-9411-40b85151f8f7.png)

Although the close icon is misaligned.

**Comment by lancewillett** [comment]
Looks good to me, @montogeek — which browser and OS are you using?

Here's Mac-n-Chrome (El Capitan):

![screen shot 2016-02-10 at 11 30 57](https://cloud.githubusercontent.com/assets/66797/12957441/dd18588e-cfe9-11e5-8169-cbf1395523ac.png)

**Comment by montogeek** [comment]
Chrome Version 49.0.2623.39 beta (64-bit) on OSX Yosemite

**Comment by lancewillett** [comment]
Thank you for the info.
