### ISSUE TITLE
Color schemes: update stats map colors

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#30066]
Currently, the map in stats could be better visualized with a color other than blue.

![screen shot 2019-01-09 at 3 47 44 pm](https://user-images.githubusercontent.com/618551/50930602-07948f00-1426-11e9-8177-1208552da2ab.png)

I propose that we use `accent` for this instead of `primary`, mostly because this is an infographic that needs a different color.

![screen shot 2019-01-09 at 3 24 56 pm](https://user-images.githubusercontent.com/618551/50930658-272bb780-1426-11e9-9850-dbcbc1248883.png)

I tried to make this change myself by using css vars, but I got some errors

```jsx
const chartColorLight = getComputedStyle( document.documentElement ).getPropertyValue(
	'--color-accent-50'
);
const chartColorDark = getComputedStyle( document.documentElement ).getPropertyValue(
	'--color-accent'
);

		const options = {
			width: 100 + '%',
			height: width <= 480 ? '238' : '480',
			keepAspectRatio: true,
			enableRegionInteractivity: true,
			region: 'world',
			colorAxis: { colors: [ chartColorLight, chartColorDark ] },
			domain: currentUserCountryCode,
		};
```

![screen shot 2019-01-09 at 3 43 44 pm](https://user-images.githubusercontent.com/618551/50930804-8ee20280-1426-11e9-9dcf-fdc95f040fbf.png)

**Comment by flootr** [comment]
Digged into it and it seems that GeoChart parses the passed in values and adds a `#` if the first character isn't already one. Now you'd assume, that's already the case but it isn't. The first char for the string returned by `getPropertyValue` is a whitespace 🌴 

So using `.trim()` after `.getPropertyValue()` does the trick.

One last thing we have to consider as well though is that `--color-accent` on `document.documentElement` is always pink because we only change those CSS vars with inside `body`. The following worked for me:

```js
const chartColorLight = getComputedStyle( document.body )
  .getPropertyValue( '--color-accent-50' )
  .trim();

const chartColorDark = getComputedStyle( document.body )
  .getPropertyValue( '--color-accent' )
  .trim();
```
