### ISSUE TITLE
Podcasting: Podcast icon missing from podcast category in Gutenberg 

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#30195]
#### Steps to reproduce
1. Select a Podcasting category in Settings > Writing
2. Create a new post
3. Check the Categories & Tags section in the post settings

#### What I expected

I expected to see a purple podcast icon next to the Podcasting category like the one seen in the classic editor: https://cld.wthms.co/8GMWKv

#### What happened instead

There is no podcast icon next to the Podcasting category: https://cld.wthms.co/qbQPAo

#### Browser / OS version

Tested in Chrome and Safari.

#### Context / Source

Reported in 9585011-hc

**Comment by arunsathiya** [comment]
Ran into the stale status ping, tested, still an issue.

<img width="278" alt="Screenshot 2021-04-01 at 7 37 16 PM" src="https://user-images.githubusercontent.com/18581859/113306403-ac5e5800-9321-11eb-9393-657e773c6629.png">

**Comment by rosepajaroja** [comment]
Tested and still an issue. 

![Alt text](https://d.pr/i/t3tODZ/1yXeoVSwOs+)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
If someone chooses to report this again, I'd recommend reporting as a feature request, as this is likely not a bug, but just an unexpected design disparity between Classic / Block Editor.
