### ISSUE TITLE
Activity log: grey Jetpack actor

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#30265]
Jetpack actor is grey in the activity log:

<img width="735" alt="screenshot 2019-01-21 at 10 11 15" src="https://user-images.githubusercontent.com/87168/51460717-f3755980-1d64-11e9-878e-4b8c069b0bb9.png">

I expected it to be green — was this caused by the recent colour update or is it intentional?

**Comment by arunsathiya** [comment]
Just a comparison to the previous color scheme on Calypso (taken from WordPress for Mac app)

<img width="556" alt="screenshot 2019-01-21 at 14 59 22" src="https://user-images.githubusercontent.com/18581859/51465101-29c6cf00-1d8d-11e9-87da-ac8530af3797.png">

It looks like it was never green. 🤔

Considering that the current color seems to be as expected, but Design can tell. 👍🏽

**Comment by simison** [comment]
Nice idea to check from the desktop app!

Suppose it should not be green not to mix up with red/green/yellow status colours. 👍

**Comment by arunsathiya** [comment]
From what I see, the grey shades differ on the image I shared from WordPress.com Mac app as well.

On a related note, I created https://github.com/Automattic/wp-calypso/issues/30282

I can attempt to submit a PR for both. Would you mind if I take this from you, @simison? Will wait on design review first.

**Comment by arunsathiya** [comment]
<img width="640" alt="Screenshot 2021-04-01 at 7 34 11 PM" src="https://user-images.githubusercontent.com/18581859/113306012-3e199580-9321-11eb-9a51-d9de3ad67a6d.png">

Remains grey as of today, still pending design input.

**Comment by keoshi** [comment]
This was purposefully tweaked to let the icons on the left shine since they're the ones that indicate status (backup successful, plugin update available, etc.). Adding green to our logo would make it compete in lots of different scenarios; example:

![image](https://user-images.githubusercontent.com/390760/132382516-ca440a77-6852-49c8-b82b-20d6c34d1b89.png)

I do agree that we should use a single shade of grey for all secondary icons/actors: Jetpack, unregistered user, Core, etc.

**Comment by simison** [comment]
>This was purposefully tweaked to let the icons on the left shine since they're the ones that indicate status (backup successful, plugin update available, etc.). Adding green to our logo would make it compete in lots of different scenarios;

👍 Closing
