### ISSUE TITLE
Notifications: lack of contrast for unread notifications

### ISSUE THREAD

**Issue by koke** [Automattic/wp-calypso#30267]
Unread notifications show a slightly darker background than read ones, but the difference is barely visible. It was already hard to spot with the old colors, but it feels even subtler with the new color scheme.

I also think it's subtler in my Dell external display than on a MacBook Pro screen, so I'm attaching a picture instead of a screenshot:

![notifications-contrast](https://user-images.githubusercontent.com/8739/51468913-57514f80-1d70-11e9-87f2-ee63d5edda3c.jpg)

**Comment by flootr** [comment]
Just a side note that the icon color on the bottom right of the avatar also indicates un-/read status.

<img width="154" alt="screenshot 2019-01-23 at 07 18 51" src="https://user-images.githubusercontent.com/9202899/51586900-35c2a600-1edf-11e9-8bcb-81517add731c.png">

**Comment by juliasydnor** [comment]
A user contacted us about this issue in 1771633-zen:

> When I am on my WordPress dashboard and see I have a notification, I find when I click on the bell top right which brings a drop down, that it is very hard to tell what I have read or not, especially when on my phone. For the unread, it really needs to be a shade darker than what it is.

**Comment by drw158** [comment]
Using blue makes sense to me. I think we should go ahead and make this update since we have been getting reports about it.

The only text that wouldn't pass is the -color-text-subtle text on comment notifications

![screen shot 2019-02-04 at 2 16 15 pm](https://user-images.githubusercontent.com/618551/52234536-8646e580-2887-11e9-842e-e1a142d84707.png)

Not a deal breaker though, since it doesn't completely fail contrast tests (still would pass AA+ if the text was bold or > 18pt), and because the text is available to read once you click on the notification.
