### ISSUE TITLE
GIF Block: Make the caption consistent to other blocks

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/wp-calypso#30411]
When adding a caption to the GIF block and comparing it to the caption in an Image block, the 2 look very different on both front-end and back-end. I would expect the GIF caption to look like the Image caption.

Front-end:

![screenshot 2019-01-25 at 11 12 24](https://user-images.githubusercontent.com/177929/51742892-ea50f900-2092-11e9-82b8-4e4045a79cb8.png)

Back-end:

![screenshot 2019-01-25 at 11 20 03](https://user-images.githubusercontent.com/177929/51742998-43b92800-2093-11e9-88b5-ed87ba8ece30.png)

#### Suggestion

For the front-end, change the class of the caption to something more generic like `wp-caption-text` which is something most themes would style.

![screenshot 2019-01-25 at 11 14 32](https://user-images.githubusercontent.com/177929/51742943-110f2f80-2093-11e9-8b8d-dbdd380cb3cc.png)

In the editor, we could add a class like `gallery-caption` to it. The class might not be 100% accurate at least it returns the correct styling.

![screenshot 2019-01-25 at 11 23 23](https://user-images.githubusercontent.com/177929/51743231-ebcef100-2093-11e9-8f08-1c9705e4fd06.png)

**Comment by jeffersonrabb** [comment]
This is a surprisingly complex little problem. The Image block caption is a `figcaption` element. Originally we used the same in GIF, but @sirreal pointed out that it should be a child of `figure` although in the structure of this block the caption falls outside the `figure` element. Moving it inside `figure` creates problems because it breaks the `iframe` sizing tactic, which sets `padding-top` on the `figure` based on the aspect ratio of the selected GIF. So, to resolve the HTML validity questions, we opted to simply change the caption to a `p` element and move on rather than tackle some fairly baroque sizing logic. 

Here are possible resolutions to this issue:

1) Change the caption back to a `figcaption`, leaving it outside the `figure`. This would get us close, although defies ["The <figcaption> element can be placed as the first or last child of the <figure> element."](https://www.w3schools.com/tags/tag_figcaption.asp)

2) Apply styling to the `p` element that replicates the Image block's caption. 

3) Rearchitect the structure of the block and rework the sizing logic so that the caption is a `figcaption` and is the final element in the `figure`. This is potentially difficult and has the possibility of breaking things just as the block is set to release.

@thomasguillot, @sirreal what do you think?

**Comment by thomasguillot** [comment]
What if we wrap the `iframe` into a `div` and apply the `padding-top` to that `div`? Then the `figcaption` can be a direct child element.

```
<div class="wp-block-jetpack-gif">
	<figure class="wp-block-image wp-block-jetpack-gif-figure">
		<div class="wp-block-jetpack-gif-wrapper">
			Iframe here
		</div>
		<figcaption>Caption here</figcaption>
	</figure>
</div>
```

<img width="1552" alt="screenshot 2019-01-25 at 13 51 17" src="https://user-images.githubusercontent.com/177929/51749916-8fc29780-20a8-11e9-9865-f14bdda48298.png">

**Comment by sirreal** [comment]
@thomasguillot's suggestion seems like it would solve this nicely and doesn't appear overly complicated. If we want to keep the caption in this release, I think that's the way to go 👍

**Comment by jeffersonrabb** [comment]
I played with this solution and it wasn't immediately easy. I'm happy to dig in to this, but given @sirreal's time and upcoming meetup we don't have much time before code freeze. Would it be acceptable to address this issue after the JP release?

**Comment by sirreal** [comment]
If this is complicated, I would be happy to drop the caption from this release and consider it to be an enhancement to be revisited in the future.

**Comment by jeherve** [comment]
> does that sound worrying?

I think that should be fine, it should be okay to address this later.

**Comment by jeffersonrabb** [comment]
Resolved in https://github.com/Automattic/jetpack/pull/11214 and https://github.com/Automattic/wp-calypso/pull/30441
