### ISSUE TITLE
Button Group: primary busy button getting wrong color

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#30477]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design/button-group
2. notice how the border is using the accent color (in this case orange) instead of the primary color

#### Screenshot / Video
![screen shot 2019-01-29 at 12 07 24 pm](https://user-images.githubusercontent.com/618551/51933940-15578780-23c8-11e9-870f-d3b0d59bc275.png)

**Comment by torres126** [comment]
I feel like the hover styles for this also look off. They currently use accent dark, if the button was to have a primary dark border in its normal state, here's how it looks on hover.

![sfdggfdsgsdf](https://user-images.githubusercontent.com/43215253/51935458-da704680-23fd-11e9-83aa-afa0e133d1f3.png)

Not sure if that's intentional tho

**Comment by blowery** [comment]
I'll take this one

**Comment by flootr** [comment]
closing as this will be solved as part of #30394
