### ISSUE TITLE
CPTs: Nova Menu CPT goes to blank screen with Calypso and Gutenberg

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wp-calypso#30485]
On WordPress.com, when you're working with a theme that supports Jetpack's Nova Food Menu CPT and have the Gutenberg editor enabled, when you go to create or edit a menu item, you get a blank screen.

This is only happening with Calypso -- if you use the /wp-admin interface on WP.com, or on a self-hosted site, it redirects to the classic editor (not the Gutenberg editor).

#### Steps to reproduce
1. Add a theme that supports the Food Menu CPT -- examples on WP.com include Canape, Appetite, and others.
2. Click My Site > Posts, then click Food Menus > Add (Food Menus does not show up in the My Site dropdown when viewing the front-end of the site). 

#### What I expected

To be able to edit the CPT (whether through the old or new editor). 

#### What happened instead

I got a white screen screen; no JavaScript errors, but when I view source there isn't much there (screenshot below).

#### Screenshot / Video

What view source returns: 

![image](https://user-images.githubusercontent.com/177561/51947907-5016eb00-23db-11e9-95b8-d08620a43426.png)

#### Context / Source

This was originally reported as a theme issue here: 2593-wpcom-premium-themes.

**Comment by chrisfromthelc** [comment]
I had a user report multiple sites experiencing this issue in 10260285-hc

**Comment by ivan-ottinger** [comment]
Another report: 1808810-zen - Canape theme.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
