### ISSUE TITLE
Notifications: background bleed on sides of notifications in narrow views

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#3051]
There is a gap between the 480 and 660 breakpoint where you can only view the single-column detail view of a notification, but you do not get a shadow to the left of the entire notifications panel. It creates this appearance:

<img width="502" alt="screen shot 2016-02-03 at 2 11 42 pm" src="https://cloud.githubusercontent.com/assets/437258/12793818/4b8b97dc-ca80-11e5-8985-43cfeb627ce7.png">

Expected: there should always be a shadow setting notifications off the rest of the page until notifications goes fully full sreen.

cc @drw158

**Comment by designsimply** [comment]
Closing because I was unable to reproduce the problem using the following testing steps:

1. Start at https://wordpress.com
1. Click the notifications icon in the top toolbar
1. Drag the browser window so the size gets progressively smaller and check to see if the shadow setting apart the notifications panel goes away at any point

<strong>Result:</strong> the shadow didn't go away ([39s](https://cloudup.com/cTrnkpMrqrp))

I tested with Safari 9.1.1, Firefox 47.0.1, and Chrome 51.0.2704.106 on Mac OS X 10.11.5.

**Comment by rickybanister** [comment]
You're right, something has changed here and the shadow seems to stick around, but I discovered a perhaps worse responsive issue with notifications:

Before the browser reaches the smallest breakpoint, notifications never pop to be full-width, leaving no shadow on the left or right and letting the background bleed through:

<img width="457" alt="screen shot 2016-08-09 at 11 01 17 am" src="https://cloud.githubusercontent.com/assets/437258/17521310/dc99fe74-5e20-11e6-9253-85dc07ff995d.png">

**Comment by kriskarkoski** [comment]
I can still repro the second issues Rick mentioned above. I saw it happen in Chrome on Mac at a browser width of 440 and it looks like it happens at anything above 400px (the smallest I can make Chrome) and the 48-px breakpoint when the masterbar adjusts. 

I've updated the title of this issue to be for the later issue we uncovered, but I'm sure it could be tweaked further for more clarity.

**Comment by drw158** [comment]
There is now a shadow.
