### ISSUE TITLE
Editor: Add spellcheck / proofreading feature

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#306]
Implement the proofreading/spellcheck feature in the Calypso editor.

Here's what it looks like in WP Admin: 
![screen shot 2015-11-20 at 2 24 34 pm](https://cloud.githubusercontent.com/assets/1900444/11309551/82cdc84c-8f92-11e5-8ab1-17ee915eccb3.png)

**Comment by jeherve** [comment]
Also requested here:
http://halfelf.org/2015/calypso/

**Comment by aduth** [comment]
I've spent some time reviewing the technical requirements for integrating [After the Deadline](http://www.afterthedeadline.com/) (AtD). There are several hurdles to being able to support it in Calypso, which I'll summarize below:

First and foremost, the existing client-side solutions ([official TinyMCE plugin](https://github.com/Automattic/atd-tinymce#README)) assume that an endpoint will be made available in proxying requests to the AtD service. For WordPress(.com), this is implemented as an `admin-ajax.php` handler. We could potentially leverage this in Calypso (as we had done in the pre-Calypso editor), but only in production environments (WordPress.com hostname), and not with current nonce restrictions. Options for moving forward include:

- Update the AtD service to support CORS JavaScript requests to remove the proxy endpoint requirement. This will likely also require AtD to be served over HTTPS to avoid mixed content failures in making AJAX requests from WordPress.com
- Or... remove nonce checks from `admin-ajax.php` AtD handlers (seems suspect, should investigate impact)
- Or... implement a custom proxy endpoint in our Node Express server (with the side-effect of supporting development environment testing)

Further, we must consider support for ignored strings. In WordPress, this is saved as a user attribute. It may be in our interest to continue using this attribute so that ignored strings are preserved between wp-admin and Calypso editor sessions, or consider storing these settings in a local preference store. Options for moving forward:

- Add `AtD_ignored_phrases` to `/me/settings` endpoint response, including option to update setting. Configure the AtD plugin to read from / save to this endpoint using existing `wpcom.js` integration.
- Or... configure AtD plugin to use the Calypso-specific [preferences store](https://github.com/Automattic/wp-calypso/tree/master/client/lib/preferences)

Next, required dependencies will need to be ported to work in the Calypso environment. Neither the AtD TinyMCE plugin nor the core JavaScript library are designed to work in a CommonJS environment, nor are they made available on npm. If we follow preexisting patterns, we'd likely want to copy/fork these files to Calypso, rewriting specific portions to adhere to our coding standards, remove references to window globals, and export themselves as CommonJS consumable modules.

Lastly, there is likely some minimal restyling effort required to align the appearance of the AtD suggestions popover with Calypso style standards.

**Comment by aduth** [comment]
CORS support has been added to the AfterTheDeadline service, which should give us a path forward for implementing proofreading support in the Calypso editor without need for a proxy endpoint.

I expect that major revisions will be required for the TinyMCE AtD plugin, particularly around communicating directly with the AtD service (instead of through a proxy endpoint) and in retrieving/persisting user preferences for ignored suggestions.
