### ISSUE TITLE
Curação number not validating for 2FA

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#30741]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/security/two-step
2. Choose "Netherland Antilles (+599)"
3. Enter a valid number for Curação
4. Click "Verify via SMS"

#### What I expected

A verification SMS message to activate 2FA

#### What happened instead

Received `That phone number does not appear to be valid` error.

#### Browser / OS version

Chrome Version 71.0.3578.98 (Official Build) (64-bit) on MacOs Mojave

#### Screenshot / Video

<img width="758" alt="screen shot 2019-02-12 at 17 07 15" src="https://user-images.githubusercontent.com/7596032/52671334-cb52c380-2ee8-11e9-8422-17049a701d14.png">

#### Context / Source

User reported in 1784082-zen and is unable to activate 2FA on their account.

They mentioned the country code for Curação changing from +599 to +5999, but I can't find any information on that. I did verify the number they're providing is a valid Curação mobile number at https://www.searchyellowdirectory.com/reverse-phone/5999/ (along with other places via Google)

If I'm reading [this code block](https://github.com/Automattic/wp-calypso/blob/59ff2ef/client/components/phone-input/data.js) in the lookup function, the Curação numbers are interpreted this way:

`	CW: {
		isoCode: 'CW',
		dialCode: '599',
		patterns: [
			{
				match: '(\\d{3})(\\d{4})',
				replace: '$1 $2',
				leadingDigitPattern: '[13-7]',
			},
			{
				match: '(9)(\\d{3})(\\d{4})',
				replace: '$1 $2 $3',
				leadingDigitPattern: '9',
			},
		],
		priority: 10,
	},
`

Which should allow for the numbers they're entering (`9XXXXXXX`). Tried various versions of the number (listed in the ticket) and none worked.

**Comment by Robertght** [comment]
A new case in 2845285-zen

**Comment by GeoJunkie** [comment]
I did some more digging, and I think the fix is to run `bin/build-metadata.js`, but I can't find how that is triggered.

Here's what I found:

* The lookup function checks the number against `client/components/phone-input/data.js`: https://github.com/Automattic/wp-calypso/blob/e4913323624ce91d45505c4a497fc3e7bc00a3aa/client/components/phone-input/data.js#L2
* This file is generated using `bin/build-metadata.js`, which pulls data from `	'https://raw.githubusercontent.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/metadatalite.js`: https://github.com/Automattic/wp-calypso/blob/e4913323624ce91d45505c4a497fc3e7bc00a3aa/bin/build-metadata.js#L112
* [That repo](https://github.com/google/libphonenumber) has [a test site](https://libphonenumber.appspot.com/phonenumberparser) using this data. The numbers from the users work properly when submitted there

Can the updated metadata be generated?

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
`Netherland Antilles +599` is no longer included in our list of area codes. For further investigation into the area codes we support for 2FA and any issues with that, refer to https://github.com/Automattic/wp-calypso/issues/78207
