### ISSUE TITLE
Editor: Improve visibility of sticky post option

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#309]
Users are having a hard time finding the option to mark a post as stick, which is currently found by clicking the section below the blog title:

![highlight sticky open](https://cloud.githubusercontent.com/assets/1900444/11309690/45cc2b18-8f93-11e5-86d7-9501f793af84.jpg)
![screen shot 2015-11-18 at 1 11 40 pm](https://cloud.githubusercontent.com/assets/1900444/11309691/45cc2b54-8f93-11e5-96a4-2e115081a1eb.png)

We should consider a new location for this to improve discovery

**Comment by lancewillett** [comment]
Related feedback from @cecoates for this same interface, but with finding the revision options.

> I've accidentally erased the text on a post I spent a long time writing. I would like to view previous revisions of my post, but I don't realize that's an option.

![screen-shot-2017-01-29-at-01-30-13](https://cloud.githubusercontent.com/assets/66797/22664316/5428d5d4-ec6d-11e6-8017-3ad78e60e330.png)

> None of the other tabs in the post editor have a similar setup where you click on something to reveal more options, so I only realize by accident or by contacting support that I can click on "Published" to expand the tab. This information would be easier to find if these options were expanded by default.

![screen-shot-2017-01-29-at-01-30-36](https://cloud.githubusercontent.com/assets/66797/22664320/58480cac-ec6d-11e6-8769-5242e4780552.png)

**Comment by lancewillett** [comment]
This has improved a lot since this was reported, notably with a sidebar refresh: https://en.blog.wordpress.com/2017/03/13/a-distraction-free-writing-space-at-wordpress-com/

<img width="672" alt="screen shot 2017-05-02 at 08 09 05" src="https://cloud.githubusercontent.com/assets/66797/25624573/a29a333c-2f0e-11e7-87c9-f3fa6ca451e4.png">

The section with Sticky is labeled clearly "Status" and is near the top of the sidebar settings column.
