### ISSUE TITLE
Slideshow block: Broken Image reference when using' Upload an Image' button

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#30920]
#### Steps to reproduce
1. Start with a blank post or page
2. Insert a Slideshow block (any method)
3. Select 1 or more images (either upload through the media modal, or select from media library)
4. Add an additional image with 'Upload an Image' button displayed below the slideshow
![](https://cldup.com/YO_MZPObLY-3000x3000.png)
5. Publish/Update the post/page

#### What I expected

I expected the final image added would display correctly in the slideshow (as it does within the editor)

#### What happened instead

The slideshow displays correctly, but the final image has a broken source URL. It appears to use a URL like `https://wordpress.com/bedc01de-6c82-430f-86cc-0a89077b7917` rather than one like `https://lamontjordan.files.wordpress.com/2018/08/ww6.jpg?w=640`

#### Browser / OS version

Checked on Mac OSX in Chrome 71.0.3578.98 and Safari 12.0.3

#### Testing/Examples

* https://lamontjordan.blog/2019/02/20/testing-the-new-slideshow-block/
* https://lamontjordan.blog/slideshow-block-on-a-page/
* https://jordesign.wordpress.com/2019/02/20/slideshow-test/

**Comment by jeffersonrabb** [comment]
This is interesting - I believe this occurs when a post is saved while an image is still uploading - and affects other Gallery-style blocks as well. To test:

- Create Slideshow
- Add a few images from the Media Modal
- Upload a new image, the larger the filesize the better.
- Publish (or Update) the post before the image finishes uploading.

I also tried the same procedure with Core Gallery and Tiled Gallery:

In Core Gallery the problem is pretty much the same as what's being reported here. If you publish/update mid-upload you end up with a broken image. 

In Tiled Gallery the outcome is a bit worse. After publishing/updating mid-upload the block becomes invalid. Refreshing the editor page shows `This block contains unexpected or invalid content.`. In the front end the block doesn't appear at all. I'm wondering if there might be some connection to https://github.com/Automattic/wp-calypso/issues/30855? cc: @sirreal & @simison 

There's definitely one concrete TODO here for Slideshow, which is to add an upload progress indicator. The other two blocks have this and Slideshow does not, which makes it difficult to know if the image upload has completed. I'll add this UI, and continue to investigate solutions that might help all three blocks resolve the problem.

**Comment by selectedselections** [comment]
This issue was reported by another user here zd-1828336

The user had tiled galleries added to their posts with images they uploaded into the tiled gallery block itself using **Upload Media**. They noticed that clicking on items within a tiled gallery led to blank, black pages which required refreshing the browser to close. The user then removed and re-added their tiled galleries with already uploaded media and this issue was resolved.
