### ISSUE TITLE
Activity Log: Activities by CLI should not say "Jetpack" or the JP icon.

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#30966]
When actions are taken against a site from WP CLI, we should make clear that Jetpack is not the actor.

#### Steps to reproduce
1. On a Jetpack site with sufficient connection/plan to see the activity log, login via SSH.
2. Change the theme via WP CLI (e.g `wp theme activate twentyseventeen`)
3. Check the activity log on wordpress.com.
4. See the action with "Jetpack" and a Jetpack logo.

#### What I expected
It was confusing to me (and the original reporting user) that the Jetpack logo and name was there. "Why did Jetpack change my theme?" In reality, since it is WP CLI, we don't have an user, so maybe a terminal-looking icon with maybe "WP CLI" or some "The Site's Server" or something for the name?

#### What happened instead
Jetpack icon and Jetpack name.

#### Browser / OS version
n/a

#### Screenshot / Video
![wpcli](https://user-images.githubusercontent.com/88897/53255339-0b553b80-368b-11e9-8b42-d3bb6db0d293.png)

#user-report

**Comment by juliasydnor** [comment]
Another WP CLI theme change incorrectly attributed to Jetpack in 2740200-zen.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
If anyone thinks this warrants another look, I'd recommend opening a new Feature Request/Enhancement in lieu of a bug report, as it seems this is working by design.
