### ISSUE TITLE
Addition Icon is Very Similar to Deletion Icon in History with Classic Bright Scheme

### ISSUE THREAD

**Issue by theck13** [Automattic/wp-calypso#30990]
#### Steps to reproduce
0. Select **_Classic Bright_** dashboard color scheme at https://wordpress.com/me/account.
1. Open editor for post with revision history (e.g. https://wordpress.com/post/example.wordpress.com/123).
2. Click **_History_** button.
3. Notice addition icon is **_Hot Pink 500_** (`#d52c82`).
4. Notice deletion icon is **_Hot Red 500_** (`#eb0001`).

#### What I expected
The addition and deletion icons are dissimilar making it easy to differentiate between the two when viewing post history.

#### What happened instead
The addition and deletion icons are similar making it difficult to differentiate between the two when viewing post history.

#### Browser / OS version
Google Chrome v72.0.3626.109 on macOS v10.14.3.

#### Screenshot / Video
![calypso_history](https://user-images.githubusercontent.com/3827611/53355825-29b77300-38e7-11e9-8ee1-9f18d9e1e81d.png)

**Comment by drw158** [comment]
Instead of pink, it should probably use `--color-success` (green). 

I imagine that the intent was to use **blue** and **red** though, which might be better for red/green color blindness. Our `success` and `error` colors should be ok for color blindness, and if not then we should update those colors.
