### ISSUE TITLE
Repeat Visitor block: Need the ability to re-add the block 

### ISSUE THREAD

**Issue by skjaini** [Automattic/wp-calypso#31005]
#### Steps to reproduce
1. Starting at URL: WordPress.com/wp-admin/post-new.php?post_type=page
2. Select 'Repeat Visitor' block to be added to the page with default 3 visits and 'Hello' text.
3. Publish and view the page atleast 3 times and see the 'Hello' text appear.
4. Go back to editing the page and remove the 'Repeat Visitor' block.
5. Add a new 'Repeat Visitor' block with the deault 3 visits and 'World' text.
6. Hit 'Update' and visit the page atleast 3 times.

#### What I expected
Expected to see 'World' text after visiting 3 times.

#### What happened instead
Did not see the 'World' text appear after 3 visits.

#### Browser / OS version
Chrome / macOS Mojave

#### Context / Source
#dogfooding Testing the Repeat Visitor Block.

**Comment by jsnmoon** [comment]
Hi @skjaini, I just tried to reproduce this using a [Jurassic Ninja instance](https://href.li/?https://jurassic.ninja/create/?gutenpack&calypsobranch=master&branch=master) and was able to see both `Hello` and `World` after the initial 3 visits. Could you try reproducing this issue on a Jurassic Ninja instance? 

Since the Repeat Visitor block is currently marked as a beta block, it won't work properly on WPCOM.

**Comment by skjaini** [comment]
Tested again and was able to see it work after re-adding the block. Closing the issue, thanks 👍
