### ISSUE TITLE
Disable cookie warnings when viewing a site within the mobile apps

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#31158]
#### Steps to reproduce
1. Use the mobile app and navigate to "My Sites"
2. Select a site and scroll down to "View My Site"
3. It should show you your site

#### What I expected
My website without the the cookie warning at the bottom

#### What happened instead
The cookie warning is shown for a site I own

#### Browser / OS version
WordPress iOS and Android app

#### Screenshot / Video

![img_7489](https://user-images.githubusercontent.com/1158819/53675049-987a3080-3c47-11e9-88e4-94c75587040c.png)

#### Context / Source

There is no need to show a cookie warning for a site we own within the app.

#dogfooding

**Comment by mmtr** [comment]
> There is no need to show a cookie warning for a site we own within the app.

@kwonye @diegoreymendez @elibud can you clarify why the GDPR is not applicable here? To my understanding, GDPR requires websites to show these warnings and, although we're using a mobile app here, we're actually navigating through a website.

**Comment by rclations** [comment]
I believe the GDPR question was answered in p4H3ND-Ns-p2

**Comment by dmsnell** [comment]
thanks @rclations 

after looking into it more myself I'm thinking that the GDPR banner in Calypso is actually there for WordPress.com and not for the sites being previewed. That is, any GDPR banner from other sites should still appear in the preview but from the frontend and not from Calypso.

is my logic right then that we are completely safe not showing the banner from Calypso because it's only specifically for WordPress.com and _not_ for WordPress.com sites?
