### ISSUE TITLE
Gutenberg crashes on user action when offline

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#31258]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/ or https://{subdomain}.wordpress.com/wp-admin/post-new.php
2. In the inspector, find the "Network" tab and check the "Offline" mode.
3. Start writing you post, then hit "Save Draft".
4. Witness the crash notice.

#### What I expected
I expected the red error notice that appears if you follow the above steps and wait for autosave to kick in rather than you hitting "Save Draft".

![screen shot 2019-03-06 at 3 07 18 pm](https://user-images.githubusercontent.com/1398304/53920321-a3570b80-4021-11e9-85a6-ded9417c3a29.png)

#### What happened instead
I received a message about an unknown error occurring.

![image](https://user-images.githubusercontent.com/1398304/53919032-90423c80-401d-11e9-919b-7b0d2abaaf9d.png)

#### Browser / OS version
Google Chrome 72.0.3626.121, macOS 10.14.3

**Comment by tijosh** [comment]
I had a user report a possibly-related instance of this today in #13593601-hc 

They're seeing "Saving of Draft Failed" from time to time when trying to update posts.

These are the conditions they relayed to me:

* They leave their computer for a while and the screen goes off
* They return to the page/post later and make edits, then try to save
* They have their computer to set never to sleep

This happens intermittently—not predictably reproducible by them. 

I suspect it may be related to a dropped network connection or that the connection to the server gets lost.

**Comment by mkaz** [comment]
Offline support within Calypso/WordPress.com does not have the same behavior as core Block Editor.

If you start a post on WordPress.com, either through Calypso or /wp-admin/ and you lose network after starting the post, no indication is given that you have lost network. If you continue to Publish and then navigate away, you will lose any data entered since last save, but if you lost network you may not know when that was.

Test:
1. Start a post in block editor
2. Turn off your network
3. Click Publish
4. Click View Post after "Published"
5. You'll get a page not found, since you don't have network and changes are lost

In core, if you click publish in WordPress 5.3

![Screenshot from 2019-12-18 14-54-38](https://user-images.githubusercontent.com/45363/71130850-dbda6700-21a7-11ea-97dd-e1bbdd3cdb10.png)

In core, if you click publish with no network in Gutenberg v7.1 plugin

![Screenshot from 2019-12-18 14-57-38](https://user-images.githubusercontent.com/45363/71130831-d250ff00-21a7-11ea-84ff-52c610250b64.png)

**Comment by gwwar** [comment]
API middleware handling likely needs to be updated. (We modify this internally to translate relative site requests to public.api requests). Detection handling in core happens here:

https://github.com/WordPress/gutenberg/blob/9c660bf17d21e29df2e5d1d7b5ef7cc256fe04bb/packages/api-fetch/src/index.js#L98

Might be worth updating https://github.com/Automattic/wp-calypso/issues/29909 at the same time

**Comment by mmtr** [comment]
> Might be worth updating #29909 at the same time

Agree! D37093-code (currently in progress) should help with both #29909 and this one

**Comment by mmtr** [comment]
Done in D37093-code
