### ISSUE TITLE
[Shortcopy] Plans page: emphasize Security and Performance

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#31356]
Refocusing Jetpack around Security and Performance.

No major updates, number of plans, naming, and pricing all stay the same.
Design TBD

**Comment by keoshi** [comment]
## Proposed changes


### Calypso

- **Global**:
  - Ignore the lack of bold in the mocks, we should keep the existing emphasis.
- **Personal plan**:
  - Add `Expanded Site Activity` entry on Personal plan, before Priority Support.
    - Description:
    - > A comprehensive and filterable list of all the activity happening on your site takes the guesswork out of site management, debugging, and repair.
- **Premium plan**:
  - Add `Automatic Security Fixes` entry on Premium plan, before Unlimited Video Hosting.
    - Description:
    - > Automated and immediate resolution for a large percentage of known security vulnerabilities or threats.
  - `Unlimited Video Hosting` moves up before Site Monetization.
- **Professional plan**:
  - `Real-time Off-site Backups` moves to the top.
  - `Enhanced Site-wide Search` moves to second place right after Real-time Off-site Backups.

#### Before

![Screenshot 2019-03-13 at 19 09 02](https://user-images.githubusercontent.com/390760/54309593-5d251d80-45c8-11e9-93fb-1feb09fb46ad.png)

#### After

![Calypso-after](https://user-images.githubusercontent.com/390760/54309749-aecda800-45c8-11e9-9625-1f36a216e02e.png)

### Jetpack

- **Global**:
  - Replicates the changes above to make the plans table consistent across platforms.
- **Personal plan**:
  - `Daily Off-site Backups` gains a `Daily`, and moves to the top.
  - Add `Expanded Site Activity` entry on Personal plan, before Priority Support.
- **Premium plan**:
  - `Daily Malware Scanning` gains a `Daily`, and moves to the top.
  - Add `Automated Security Fixes` right below.
  - Remove `Automated Social Media Posting`.
  - `Monetize Your Site` becomes `Site Monetization`.
  - `Jetpack Concierge` becomes `Concierge Setup`.
  - `Video CDN` becomes `Unlimited Video Hosting`.
- **Professional plan**:
  - `Real-time Off-site Backups` moves to the top.
  - `Enhanced Site-wide Search` moves to second place.

#### Before

![JP-before](https://user-images.githubusercontent.com/390760/54310628-b8580f80-45ca-11e9-970c-5a0aa3d11c62.png)


#### After

![JP-after](https://user-images.githubusercontent.com/390760/54310638-c0b04a80-45ca-11e9-9a2f-a0e917f94df6.png)

Would you mind reviewing these changes, @jeffgolenski  @joanrho ? Thank you both.

**Comment by keoshi** [comment]
Pinging @Automattic/editorial for a copy review as well — thank you in advance!

**Comment by michelleweber** [comment]
Two notes --

(1)  I'd love to tighten and re-order this ever so slightly: "Take the guesswork out of site management and  debugging with a filterable record of all the activity happening on your site." (But if starting it with a verb throws it out of whack with all the other descriptions on the page, never mind and leave it as it.)

(2) "Real-time Off-site Backups" looks a little wonky because of the multiple hyphens and mix of capital and lower case lettering. Can we change "Real-time" to something like live, or instant, or simultaneous, or synchronous?

**Comment by keoshi** [comment]
1. Not at all, I think that makes perfect sense. Starting with a verb even makes it more attractive and less focused on the feature itself.
1. Great point, that one is really a mouthful. I really like the simplicity of `Live Off-site Backups` — do you have strong feelings on any of these, @beaulebens ?

**Comment by jeffgolenski** [comment]
@keoshi I love all of this, and @michelleweber 's comments. My only input for the "real-time off-site backups" hyphen shenanigans would actually be keeping "real-time" but removing "off-site"... so it'll just read "real-time backups" (we can explain in detail on landing pages that it's off-site, but I think that backup services in wordpress are really common now and off-site is generally understood. Thoughts?

Also, regarding the "unlimited premium themes" listing. According to the spreadsheet found in @jessefriedman 's post p1HpG7-6qm, we're going to be "deemphasizing" premium themes, so I think it makes sense to remove it from this list.

**Comment by keoshi** [comment]
@jeffgolenski Also a great point. I see the value in being explicit about “off-site”, but also realize many people won't even know what that means, and “Real-time backups” definitely sounds a lot cleaner. And most (all?) backup solutions are off-site anyway — otherwise what would be the point, right?

> we're going to be "deemphasizing" premium themes

Yep, I noticed that but thought the removal would be punted and handled on a later stage? I'm glad to include that on this phase, though.

Thank you, Jeff!

**Comment by keoshi** [comment]
I'm on this right now, and should have PRs soon.

**Comment by keoshi** [comment]
- **Calypso PR**: https://github.com/Automattic/wp-calypso/pull/31465
- **Jetpack diff**: D25583-code

**Comment by keoshi** [comment]
@jeffgolenski The PR and diff above have been approved (thanks @oskosk !) — since both of these live outside of the plugin code, our customers will see the updated tables in Calypso and wp-admin as soon as we merge them.

Can you think of a reason why we might want to wait until the 7.2 release? Otherwise I'll merge them tomorrow.

**Comment by keoshi** [comment]
- **Calypso** changes in https://github.com/Automattic/wp-calypso/pull/31465 have been merged and deployed.
- **Jetpack** changes in D25583-code have been deployed in r189069-wpcom.
