### ISSUE TITLE
Refactor build tool: Extract `@wordpress/` externals

### ISSUE THREAD

**Issue by gititon** [Automattic/wp-calypso#31351]
https://github.com/Automattic/wp-calypso/blob/40f010e7f0d891e69464ab849822e18b4fd707ca/webpack.config.js#L134-L158

**Comment by ockham** [comment]
Thanks for taking this on, @gititon!

Grepping `externalizeWordPressPackages`, it seems like we're only really using the `externals` for the SDK, whereas we default to `false` for Calypso itself. It might thus make sense to move this webpack config "shard" file to the `jetpack-blocks` package (that @sirreal is working on in #31199)...

**Comment by sirreal** [comment]
The Gutenberg SDK also uses this, but it's rather limited. For example, it doesn't handle externalizing `lodash` (also available as a dependency in WP Admin) or provide any sore of manifest so that scripts have the appropriate externalized dependencies when enqueued from WordPress.

With Jetpack blocks being the only real consumers, we can consider moving this into the blocks build after #31199 lands 👍

**Comment by roccotripaldi** [comment]
@sirreal et @ockham  et al. #31199 has landed!

so the plan is to remove WordPress Externals entirely from the root webpack config and into packages/jetpack-blocks/bin/build ?

Should the functionality of WordPress Externals be exportable so that Calypso can still depend on it? As it seems to be doing in these places:

- [in SDK generic](https://github.com/Automattic/wp-calypso/blob/e68f43f9b7da371dd481a6d9421103f3aca334da/bin/sdk/generic.js#L10)
- [in the Gutenberg build](https://github.com/Automattic/wp-calypso/blob/e68f43f9b7da371dd481a6d9421103f3aca334da/bin/sdk/gutenberg.js#L30)
-
