### ISSUE TITLE
Purchases: Always allow upgrade owner to renew

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#3141]
If an Upgrade owner has had their role changed to anything but "Administrator" they are not given the option to manage or renew their upgrades. 

**To Reproduce**
1) Have a non-owner purchase an upgrade
2) change their user role to something other than Admin
3) Try to renew

This can be solved one a few ways:
a) preventing non-owners from buying upgrades regardless of user role
b) allow any user who has bought an upgrade in the past to always be able to renew. 

I think we should aim for option a for new sites/upgrades and b for legacy users.

Related to #3140 on allowing the owner user role to be changed. 

Here is a video:
https://cloudup.com/cFbtNLLr-Bx

**Comment by fabianapsimoes** [comment]
cc @mikeshelton1503 

Also related to #2758.

**Comment by Tug** [comment]
Let's estimate the amount of work for this task.

I think solution a) is trivial, it should not take more than a developer day.

Solution b) on the other hand might be a lot trickier since we have to deal with permissions.
Also, it may seems that it's also the best choice in terms of UX. Indeed, it could makes sense to allow whoever user wants to pay for upgrades to do so. However, when a non-admin user wants his money back I'm not sure it's in the best interest of the site cancel the upgrade.
We can also think about a lot of other related problems. For instance when the main user of a site is not administrator and the actual administrator left the company.

So I think we should go with a) :)

**Comment by fabianapsimoes** [comment]
cc @breezyskies and @peterbutler since this would mean changes to purchase flows and renewals.

**Comment by scruffian** [comment]
What about?:

c) Allow non administrators to purchase upgrades

**Comment by fabianapsimoes** [comment]
> c) Allow non administrators to purchase upgrades

Which roles are you talking about? I'm not sure I feel comfortable with letting everyone in a site purchase upgrades that can alter the behavior of said site.

**Comment by scruffian** [comment]
I looked some more at this. I think all what we need to do is:

1. Allow users to have a cart even if they aren't an admin on the site
2. Allowing the shopping cart to accept requests from users who aren't an admin
3. Allowing the transactions endpoint to accept requests from users who aren't an admin

Part of this will be to remove this line in Calypso: https://github.com/Automattic/wp-calypso/blob/8a2656ee974afe96f25423d53ab3e113e6c046f5/client/lib/cart/store/index.js#L64

The other changes will be server side.

While these changes are small, they have large implications and so will need to be carefully considered.

**Comment by BandonRandon** [comment]
> c) Allow non administrators to purchase upgrades

I think this is something we should enable for "legacy upgrades", ie, the site already has a non-owner who has an upgrade. They should be able to continue to renew it. 

For new purchases, it may be best to only allow these to be done by the site-owner. If we wanted we could even show the plans page to non-owner, administrators with a message "to upgrade let the site owner know."
