### ISSUE TITLE
Domains: Add notice for changing contact information prevents transfers for 60 days

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#3147]
## WP-Admin example

![image](https://cloud.githubusercontent.com/assets/991022/12871218/a7baa232-cd23-11e5-824c-5df797d1e79f.png)

**Comment by klimeryk** [comment]
Closing this as resolved:
* For Tucows, we show an option (with a support link) for disabling the transfer lock.
* For WWD, the losing registrant gets an email with an explicit option to opt-out of the transfer lock (with a short explanation that it will otherwise prevent him from transferring the domain).

In the light of the above, I don't think it's needed anymore to add a separate notice to Calypso.
