### ISSUE TITLE
Simple Payments Widget: it doesn't save product image

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#31512]
When we create a new product from the widget it won't display the image, although it's possible to view it in the Customizer. I tested it with two different themes.

When we add an existent product and then we edit it to change the image, the old image doesn't change.

If we edit this same product in the original page/post it was created and change the image, then the widget image is updated with the new one.

I believe the widget isn't saving the product image, no matter if a product created from it or an existent one. Or it's a cache issue, although I have tried loading the page without cache or clearing it and it didn't make a difference.

#### Steps to reproduce
1. Add the simple payments widget via Customizer > Widgets
2. Add a new product with any image
3. View the site, the image doesn't show.
Or
1. Add a new product with image
2. Add the simple payments widget via Customizer > Widgets
3. Select the product created at step 1 and click `Edit Selected` button and change the image.
4. View the site, the image doesn't change.

#### Screenshot / Video
![simple-payments-widget-bug](https://user-images.githubusercontent.com/3521683/54463249-2d555180-4751-11e9-8f0f-3aa4105a41d5.gif)

#### Context / Source
#reallife

We'd also love to know how you found the bug: #user-report

**Comment by juliasydnor** [comment]
I had another report of this in 11854887-hc.

I wasn't able to reproduce it on a test site, but did see it on their site. Editing the product through the widget, changing the image, saving and publishing resolved it.

**Comment by DavidRothstein** [comment]
If you scroll down while editing the widget in the Customizer, you'll see there are Save/Cancel buttons inside it.  If you click Save before you publish the changes, it works correctly.

If you don't click Save or Cancel, then it doesn't work at all -- this isn't specific to images, actually (other changes don't work either).

So I think that's what's going on here?

However, these Save/Cancel buttons are very hard to find and also non-standard (other widgets don't have them at all).  So it does seem like a bug.  Ideally those buttons would be removed so that this would work as expected.

Tracking internally as a Simple Payments issue here: pNPgK-4Nu-p2
