### ISSUE TITLE
Not obvious how to edit a team member's details in People

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31634]
**Steps to reproduce**
- Go to People
- Look at the list of Team members

<img width="750" alt="Screen_Shot_2019-03-06_at_11 05 26_AM" src="https://user-images.githubusercontent.com/2124984/54762589-c9a4ab80-4bca-11e9-9e2b-29115bb0a17d.png">

*What we see*
Each member item has a chevron right/forward icon that does not really convey the available action. There's also not a label available for screen readers.

**What we suggest**
- Add a proper label and/or use an 'Edit' button instead.
- Add a proper hover state

**Comment by enriquesanchez** [comment]
Important to note: the chevron itself is not a link, the whole card is a link. There's also no hover and focus states.

**Comment by enriquesanchez** [comment]
Found here that we're explicitly removing the `outline` when element is in focus: https://github.com/Automattic/wp-calypso/blob/c0d6e152a236be520f4c6f007a3f10670de9d9a3/client/components/card/style.scss#L93

I also found that other elements that have a focus state are using this `.focusable` class: https://github.com/Automattic/wp-calypso/blob/dfffc4b999cc8929121944176c34611a25935d88/client/components/focusable/style.scss#L1

@sixhours I'd like to fix this issue and could use some advice, since I'm new to the codebase. I'm not familiar as to why we remove the `outline` when a card is focused. Do you think I can change this? Or should I use that `.focusable` class that is being used in other elements?

**Comment by sixhours** [comment]
> @sixhours I'd like to fix this issue and could use some advice, since I'm new to the codebase. I'm not familiar as to why we remove the outline when a card is focused. Do you think I can change this? Or should I use that .focusable class that is being used in other elements?

That's a really good question. I'd take a look at the last folks to edit that

**Comment by drw158** [comment]
I'd say just spin up a PR and see if your suggestions work. There's probably not a good reason why the outline is removed.

I know that we do have a special class for keyboard focus. This class is used so that we can style the keyboard focus separately from a mouse focus (usually you want to make the keyboard focus more prominent). I don't remember the name of the class.
