### ISSUE TITLE
Post Checkout: Post-purchase design improvements

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31686]
![download_(37)](https://user-images.githubusercontent.com/2124984/54836096-e8be3e80-4c99-11e9-99a7-ddb07d53c4a6.png)

<img width="1042" alt="Screen_Shot_2019-03-07_at_3 28 21_PM" src="https://user-images.githubusercontent.com/2124984/54836102-eeb41f80-4c99-11e9-891b-120368d66423.png">

* There is not always a main CTA (some purchases have them -- plans purchases, for example; some do not)
* "Back to my site" is small and confusing. Instead of this button, we should have a primary button in the center of the page, below the trophy image. The button could read "Go to My Sites". You aren't really going back; you are exiting checkout.

See also #31687

**Comment by danhauk** [comment]
Looking at this a little bit, it looks like the `Back to my site` button changes depending on some logic around what type of purchase was made. For example, if it's a domain-related purchase it takes the user back to the domains management screen, GSuite takes me to email management, etc. If it's a plan purchase it should take me to `/plans/my-plan/${ site }`. There's also a path that takes me to the domain-first flow if there's a failed purchase and no site attached (I think).

Should we make the primary button go to these places rather than the button in the header? Or should this button always just go back to My Sites?

**Comment by sixhours** [comment]
> Should we make the primary button go to these places rather than the button in the header? Or should this button always just go back to My Sites?

I think the idea is to add a primary call to action in cases where there isn't one, so I think we should remove the back button in the header entirely and use a call-to-action button for any of these actions instead. Does that make sense?

**Comment by alaczek** [comment]
> so I think we should remove the back button in the header entirely and use a call-to-action button for any of these actions instead
Yep, that makes perfect sense to me!

**Comment by sixhours** [comment]
In testing, I'm rarely able to get to this checkout screen. It looks like we've replaced it with an interstitial (possibly temporary?) advertising a concierge upgrade, and then we take the user directly to their site or to the checklist. 

I am able to see the checkout confirmation page for domain purchases.
