### ISSUE TITLE
Gutenberg: Adding <iframe> code in Custom HTML block successfully displays in block preview on plans where <iframe> is not allowed

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#31707]
As documented in https://en.support.wordpress.com/code/

The following tags are stripped from post_content on save for WordPress.com simple sites:

- embed
- frame
- iframe
- form
- input
- object
- textarea

The block editor is not aware of this limitation, and does not show any warnings. This is a confusing user experience so we should make add a nudge or provide an appropriate human readable error.

#### Steps to reproduce
1. Edit a post or page using Gutenberg on simple sites, where `<iframe>` code is not allowed
2. Add the Custom HTML block and add some `<iframe>` code, like: `<iframe src="https://staticresource.com" width="300" height="300"></iframe>`
3. Click the "preview" button on the block 

#### What I expected

For the preview to either show an error message, show the code itself, or be blank, as the code will not work on the site

#### What happened instead

The preview successfully shows the embedded content, inaccurately leading the user to believe the code will work on their site

#### Screenshot / Video

https://cld.wthms.co/cry30i

#### Context / Source

Reported in #1902396-zen

**Comment by lakellie** [comment]
Just a note, I did some further testing and the same case is happening for other types of disallowed code like `form` as well.

**Comment by gwwar** [comment]
> where <iframe> code is not allowed

Thanks for the report! @lakellie for context, what plan feature is this tied to? The custom html block is part of Gutenberg, so we'll want to make a choice here to still gate on that or not.

**Comment by lakellie** [comment]
Hi @gwwar! Happy to provide more info.

On all simple sites (including Business plan sites which are not Atomic), there are certain HTML tags that are not allowed and will not work on the site. These include `embed`, `frame`, `iframe`, `form`, `input`, `object`, `textarea`, and `script`. More info here: https://en.support.wordpress.com/code/

The only way it's possible to use these tags on your site is to go Atomic.

So the issue here is that when these particular tags are used in the Custom HTML block on a simple site, the preview on the block itself shows the code as working, when it won't actually work on the live site. So I wonder if a fix could be pushed out for simple sites only?

**Comment by gwwar** [comment]
Thanks for the additional context @lakellie !

> So I wonder if a fix could be pushed out for simple sites only?

Yes, I'll update the issue to reflect that and add it to our backlog!

**Comment by SiobhyB** [comment]
This was also the cause of confusion in 2827394-zen.

The user's attempting to embed a store from a third-party service and added the needed code to the custom HTML block. Everything looked good in the editor, which caused confusion and led them to going around in a few circles when the store didn't appear on the live site itself.

**Comment by strarsis** [comment]
A dedicated `<iframe>` or embed Gutenberg block would be nice.

**Comment by legital** [comment]
The wordpress personal plan allows lots of different embeds, but not an embed (<iframe>) from airtable.com - 👎

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
Quick tested this and I see that in the post preview, the content is stripped out as it would be on the live site; this update likely has helped alleviate some user confusion when adding advanced code on plans that don't support it. Saving the draft and refreshing also removes the code from the editor.

![Markup on 2023-08-30 at 17:23:48](https://github.com/Automattic/wp-calypso/assets/27249804/6fa68bbd-e733-46e3-adc0-d65a238d8bd3)

**Comment by robiulawal40** [comment]
<details><summary>Details</summary>
<p>

> ### **_`[](url)`_**

</p>
</details>
