### ISSUE TITLE
Signup NUX: Page title doesn't change between steps - always "Create an account"

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3173]
When going through signup steps, the page title always displays "Create an account".

**Steps to reproduce**

1. Visit https://wordpress.com/start/
2. Look at page title
3. Choose a theme
4. Look at page title

![create an account](https://cloud.githubusercontent.com/assets/128826/12905465/0c169de8-cf23-11e5-8af9-6775e55d7cca.png)

**Expected Result**

It would be nice to see titles change as per the current signup step (these should be localized)

1. Choose a theme
2. Choose a domain
3. Pick a plan 

etc

**Comment by druesome** [comment]
To add more to this, when a logged in user creates a new site via https://wordpress.com/start/, they see "Create an account", which is confusing since that is not what they're trying to do.  The title "Create a new site" is more apt, and yes, seeing the titles change for every step (as suggested by @alisterscott) would be great too.
