### ISSUE TITLE
Match font style and weight

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#31767]
RE: #31742

Once Brad adds the Material icons in, we'll probably want to match the font-size and font-weight between the Stats and Plan link text and that of the section headers (which currently are more bold: 

![](https://d1jfzjx68gj8xs.cloudfront.net/items/0p0Q0S0I3z3S3i0t3W1q/Screen%20Shot%202019-03-26%20at%206.31.20%20AM.png)

**Comment by drw158** [comment]
Since this is a redesign, I'd like us to follow our[ type scale](https://murieldesignsystem.blog/foundation/typography/type-scale/) as much as possible (even though it's not quite set in stone yet)

According to Material and our type scale the text should be 14px and either regular, medium, semibold whichever one we think is best.

We could also do 16px, but this would deviate from standard Material.

**Comment by griffbrad** [comment]
The weight is now consistent following recent commits on PR #31742.  Will make the adjustment down to 14px as suggested by @drw158.

**Comment by davipontesblog** [comment]
Closing this issue based on status update in the [Nav Drawer Redesign project](https://github.com/Automattic/wp-calypso/projects/81).
