### ISSUE TITLE
Jetpack add credit card notice shows a Renew CTA

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#31841]
#### Steps to reproduce the issue

1. Purchase a Jetpack plan
2. In your WPCOM account, go to `/me/purchases`
3. I got the following notice, even though there was a saved card on my profile (worth noting that the saved card was a Store Sandbox card):

<img width="751" alt="Screenshot 2019-03-28 at 6 00 39 PM" src="https://user-images.githubusercontent.com/1269602/55159623-85477b80-5187-11e9-8e4e-3e5bb271ca99.png">

#### What I didn't expect

1. I didn't expect an `Add a credit card` notice when I already have a card saved
2. I didn't expect the `Add a credit card ` notice to have a `Renew now` CTA, clicking which takes me to a checkout page to purchase a Jetpack plan, even though I've already purchased a plan which expiring only after a year.

**Comment by arunsathiya** [comment]
We run into this often on Happiness. 

Just so I understand this better, this happens only when the auto-renewal on that purchase is turned off. Any chance that was done from the backend? (by yourself or with a Happiness Engineer's help)

I just tested two purchases:

- One with WordPress.com credits and as expected, since no card is associated with that purchase, this notice is shown. This is correct IMO. ✅ 
- One with an actual card and on turning off auto-renewal of that purchase, this notice appears. This is normal again IMO. ✅ 

<img width="746" alt="Screenshot 2019-03-28 at 20 41 32" src="https://user-images.githubusercontent.com/18581859/55169048-0f004480-519a-11e9-9d0d-ae1934113e42.png">

(In the above image I have blurred out the card's last 4 digits, which is why it is blank) :) 

<img width="756" alt="Screenshot 2019-03-28 at 20 42 25" src="https://user-images.githubusercontent.com/18581859/55169047-0f004480-519a-11e9-8ed7-974e9493b0d7.png">

The `Renew now` text is normal as well in my opinion, because when it's used, the subscription is renewed for one more billing cycle. 

<img width="758" alt="Screenshot 2019-03-28 at 20 33 55" src="https://user-images.githubusercontent.com/18581859/55168607-1b37d200-5199-11e9-9eb9-bde90957b685.png">
<img width="1169" alt="Screenshot 2019-03-28 at 20 34 21" src="https://user-images.githubusercontent.com/18581859/55168608-1bd06880-5199-11e9-915e-aae7a1d0ab65.png">

(In both the images above, I paid using WordPress.com credits)

If we were to rename it to something like `Add a card`, a renewal flow should not be trigger and only the card should be associated with this purchase; meaning, the auto-renewal will be enabled again. 👍🏽 

All-in-all, does not feel like an issue.
