### ISSUE TITLE
Editor: WordPress.com Excerpt Link Goes to WordPress.org Support Document

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#31898]
#### Steps to reproduce
1. Starting at any WordPress.com hosted site (both Atomic and Simple).
2. Create a new Blog Post
3. Click on the Excerpt box in the editor.
4. There will be a link that says, "Learn more about manual excerpts(opens in a new tab)"
5. That link goes to https://codex.wordpress.org/Excerpt

#### What I expected
For the link to go to https://en.support.wordpress.com/excerpts/

#### What happened instead
It went to the .org support document https://codex.wordpress.org/Excerpt

#### Browser / OS version
All

#### Screenshot / Video
https://cloudup.com/cV3NLhExm_V

#### Context / Source
#perspective #reallife #dogfooding 

#dogfooding, #manual-testing,

**Comment by arunsathiya** [comment]
### Excerpts

On a related note, if we are updating this, we would need to add a link for excerpts for non-WordPress.com Business plan sites as well. Currently there is no link.

<img width="678" alt="Screenshot 2019-03-31 at 16 29 07" src="https://user-images.githubusercontent.com/18581859/55288247-3a6d7400-53d2-11e9-94c7-5dfab56c857e.png">

### SEO tools

Also, would need to do so for SEO description as well. The link can be to https://en.support.wordpress.com/seo-tools/

<img width="595" alt="Screenshot 2019-03-31 at 16 29 26" src="https://user-images.githubusercontent.com/18581859/55288248-3b060a80-53d2-11e9-81ea-caa4b527da0a.png">

Also, I added links to pingbacks and trackbacks' popup on https://github.com/Automattic/wp-calypso/pull/29657. This came from this content review originally https://github.com/Automattic/wp-calypso/issues/22679#issuecomment-367926293

Going by that logic, would need to add a support document link for all such drawers/popovers, I assume. @apeatling, could you advise on that, please? I am in favor of adding links to support documents, which would enhance users' self-service experience.

**Comment by gwwar** [comment]
To reflect a bit it sounds like we have a general question of:

For core behavior that we don't enhance, should we link to our wpcom documentation instead of dotorg?

If the answer is yes, then we'll want to open other issues:
- An audit of how many support links currently go to dotorg vs dotcom. 
- Investigation of how simple this is to override. For example, it's not worthwhile to have to swap an entire core panel, just to update a documentation link. We may need a few core contributions to add a cleaner hook.
- Checklist for the implementation task.

Overall, for folks reading, this is lower priority compared to other high priority bugs/missing features.

**Comment by scosgro** [comment]
> For core behavior that we don't enhance, should we link to our wpcom documentation instead of dotorg?

My thoughts when I noticed it were (and I don't know how difficult this is at this point, but...):

WordPress.org installations should point to the .org support docs.
WordPress.com sites should point to the .com support docs.

Or, this is the only area in the sidebar that even links to a support doc, so is there harm in removing the link altogether?

The excerpt doc on .org has a header dedicated to adjusting PHP (not relevant at all on .com), mentions screen options (rarely relevant on .com), plugins (Business Plan only), etc. Having it appear on all WordPress.com sites under excerpts just seems confusing.

**Comment by apeatling** [comment]
A good step would be making sure that core has the ability to hook in and override these documentation links, I don't think we should be starting with hacking in any overrides there. I think this is a low priority issue, mostly because they are currently getting relevant documentation, even if it's not in the place we'd want.

**Comment by gwwar** [comment]
Thanks @apeatling! I've created https://github.com/Automattic/wp-calypso/issues/31998 for the audit, and will close out this question.
