### ISSUE TITLE
MS Edge + Gutenberg | Drag and drop an image throwing  “no data supplied” error

### ISSUE THREAD

**Issue by mlaetitia** [Automattic/wp-calypso#32035]
This error occurs only on simple sites. This works on Atomic or Self-hosted sites (tested on jurassic ninja).

Notes: on the same simple site, it is possible to drag/drop via wp-admin and it is possible to upload files to the Media library. It is only not working on blocks.

#### Steps to reproduce
1. On MS Edge browser, login a simple wordpress.com site and create a new post or page
2. Add an Image or Gallery block
3. Drag&Drop an image to the post. The error  “no data supplied” appears
4. Same error occurs when clicking the "Upload" button on the bloc

#### What I expected
The image to appear/be added to the block

#### What happened instead
Error message: ![see screen shot](https://d.pr/free/i/OI5Yci+)

#### Browser / OS version
MS Edge - version 24 / Windows 10

#### Context / Source

#user-report #9386935-hc

**Comment by katiebethbrown** [comment]
Another report in 11998421-hc

User is in Edge 17.17134 on Windows 10.0.0

**Comment by gwwar** [comment]
Not having luck reproducing this one on Edge. Please re-open if folks are still having issues. I suspect one of the Gutenberg updates fixed this one.

**Comment by elibud** [comment]
I had this issue today, on Safari 14.0, macOS 10.15.7, both for a jpg and png files, adding an image via the Media Library worked, it's only inline that's failing. Worth noting that I'm on a cellular connection.

**Comment by simison** [comment]
![image](https://user-images.githubusercontent.com/87168/115507701-1dd85900-a285-11eb-9ea2-881b51d62d39.png)

@pablohoneyhoney had this happen twice (on P2 I think). Grabbed this for Create to investigate.

Can you add:
- Browser
- If you're on flaky internet
- File size & format (png, jpg...)

Error itself seems to be coming from the API: https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L965-L971

If we figure out a legit reason that we can capture in code, the error message needs to be improved for clarity.

**Comment by pablohoneyhoney** [comment]
Correct, the text didn't provide any context of what was happening.

For clarity, my issue is on Safari Version 14.0.2, iMac Big Sur 11.1

The most recent case was in pcUGD5-19-p2

The only way I was able to include images was by uploading them through the Media Library, which is tedious.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
I also ran a quick test on current versions of MS Edge (114.0.1823.44) and Safari (16.6) and did not run into this issue in the post block editor.
