### ISSUE TITLE
Activity Log: Empty "user created" action upon fresh Jetpack connection

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#32060]
To reproduce:

* Create a new JN site with the latest Jetpack.
* Connect the site and buy a plan.
* Go to the activity log.
* You'll see an empty "user created" action:

![](https://cldup.com/_K509wQfFY.png)

Here's how the action looks as returned by the activity endpoint:

![](https://cldup.com/qNGQ6xXBFs.png)

As found by @jeffgolenski and mentioned by @enejb in https://github.com/Automattic/wp-calypso/pull/31547#issuecomment-480141081

**Comment by enejb** [comment]
Thanks for the issue @tyxla!

**Comment by tyxla** [comment]
I think this hasn't been addressed yet.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
This may also be resolved - my self-hosted site shows this log when it was first connected:

![Markup on 2023-09-14 at 15:20:21](https://github.com/Automattic/wp-calypso/assets/27249804/3b6b52e7-008e-4933-aa3a-0a9b4402b127)
