### ISSUE TITLE
Private by default issue with Business sites to go Atomic

### ISSUE THREAD

**Issue by mlaetitia** [Automattic/wp-calypso#32072]
Found this while testing a bug of AT'ing a site, not related to this.

#### Steps to reproduce
1. Create a new site, without a domain, and add a Business Plan to it. It will be private by default
2. Try installing a plugin - a notice comes up saying that Private sites cannot install plugins 
3. Head to settings and click the "Launch" button
4. Even though the site has a plan and doesn't need a domain, the user is sent to a domain / plan purchase screen, as shown here: ![see screen shot](https://cld.wthms.co/QDDYwQ+)

#### What I expected
Nothing, in fact. The plan is there, the site should be made public without entering this flow. If it would, it should go to the Domain step (i saw the skip button there) and then it should recognize that a Business Plan is already in place.

#### What happened instead
The flow appeared as if the user had a Free Plan on their site.

**Comment by arunsathiya** [comment]
I tested this as well, one thing I noticed is particular is that, the `Keep this plan` string is attached to the free plan CTA irrespective of what plan the site has. In @mlaetitia's test it can seen that the flow shows `Keep this plan` on free plan, instead of WordPress.com Business plan.

Likewise on my test, happened on WordPress.com Blogger Plan.

<img width="1529" alt="Screenshot 2019-04-05 at 16 28 42" src="https://user-images.githubusercontent.com/18581859/55644611-13f57180-57f4-11e9-8ade-135358f648b2.png">
<img width="1170" alt="Screenshot 2019-04-05 at 16 28 50" src="https://user-images.githubusercontent.com/18581859/55644613-13f57180-57f4-11e9-92f4-64622b461819.png">

On that note, I am tagging this as a bug and I am attaching a high priority as well - given that this affects everyone now.

**Comment by fditrapani** [comment]
Thanks for filing this bug @mlaetitia! You're right that the plans screen should not be shown, if someone already has a plan, but it is intentional to ask people to register a domain when they launch their site if they don't already have one. I created a Trello card for the onboarding team that owns this part of the flow: https://trello.com/c/3dgT6ZyC/639-bug-plans-in-launch-flow-for-paying-customers

**Comment by suyogyashukla** [comment]
Also adding that in my testing, once I selected the Business Plan again, I was stuck at the create site screen on this URL: https://wordpress.com/start/launch-site/launch - there were no console errors either.

**Comment by lancewillett** [comment]
Moving out of high priority since Private by Default is turned off for now. We can revisit once that flow is enabled later.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
Private by default at this point is still not enabled.
