### ISSUE TITLE
Stats: Old AT redirects in stats pages

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#32081]
Links to posts on the /stats page are using an old link.

First discovered in hc-11862640. User noticed that when they clicked on "View" on some of her posts that had views in /stats, the link to view the post was using an old subdomain. For example, if their domain is abc.com then the link from stats was alt.abc.com.

#### Steps to reproduce
See specific details in hc-11862640.
1. View /stats on an AT site
2. Click View on one of the most viewed posts
3. Should show a broken page because the link uses alt.abc.com/post-id instead of abc.com/post-id

#### What I expected
Expected to see a regular redirect to abc.com/post-id

#### What happened instead
Used a broken redirect using an old AT subdomain like alt.abc.com/post-id

#### Browser / OS version
Chrome 73 on macOS (Mojave)

**Comment by samiff** [comment]
Just for a bit of clarification, it seems the links shown on `/stats` aren't being updated when the primary domain name changes. This confuses users if they click on those links because the links may not work anymore.

Updating a page/post that shows an incorrect link will correctly update that link on the `/stats` page, but that isn't ideal. I tried a search-replace but that didn't seem to matter.

![Screen Shot 2019-04-05 at 18 54 29](https://user-images.githubusercontent.com/15803018/55662851-d2090300-57d4-11e9-944d-871939552d61.png)

**Comment by jsnajdr** [comment]
Hi @aaronyan and @samiff :wave: To clarify the steps to reproduce this issue, I need to:
1. Have an AT site with two domains.
2. Change the primary from one to the other.
3. Right after the change of the primary domain, go to stats and click on a post link.

Then the link includes the old, out of date primary domain, is that right?

After reloading the Calypso page, are the links refreshed with the new primary domain?

**Comment by samiff** [comment]
@jsnajdr Yes, those are the correct steps to repdroduce.

> After reloading the Calypso page, are the links refreshed with the new primary domain?

No, they still use the previous domain name for the links. I've tried search-replace, resaving permalinks, and flushing cache, to no effect. Only updating (even making no changes) the post or page seems to cause the link on Stats to be updated.
