### ISSUE TITLE
Publicize: Remove Google+ share previews

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#32105]
#### Steps to reproduce 

- Start with a WordPress.com Premium plan or WordPress.com Business plan site
- Visit the posts list at https://wordpress.com/posts
- Click on the 3 dots menu next to a post
- Click `Share`
- Click `Preview`

#### What is expected 

Google+ preview option is not shown because Google+ references are being removed here https://github.com/Automattic/wp-calypso/issues/31299

#### What happens instead 

Google+ preview option is shown

**Comment by koralcem** [comment]
Is there any way one can reproduce this issue for themselves without a Premium or Business plan?

I'd be happy to try my hand at the issue, but don't have such plans to be able to see the Google+ preview option.

**Comment by arunsathiya** [comment]
Thanks for your interest in contributing to Calypso, @koralcem! We are happy to set you up with a test environment. I shall reach out on the email listed on your GitHub account.

**Comment by koralcem** [comment]
Thanks a lot! Will follow up by email.

**Comment by koralcem** [comment]
Followed up with @arunsathiya over email and got set up with a test plan. However, I've hit another stumbling block.

See the below gif, which is me trying to follow the steps given in the issue. After clicking `Share`, I never even see a `Preview` menu item; I'm asked to connect a social media account instead:

![Repro](https://user-images.githubusercontent.com/3772093/56481506-4cdc4a00-6474-11e9-9bfb-b22baaa5f305.gif)

I'm guessing this is because I don't actually have an account connected, and it would make sense to need one to share a post. At this point I had a few thoughts on how to proceed:

1. My next attempt was to actually connect an account via Publicize. But I don't see a Google or Google+ option in there. Were they removed in one of the changes that addressed https://github.com/Automattic/wp-calypso/issues/31299? Can one still be created by a user?

2. This next idea requires me to expand my mental model of Calypso a bit. If Calypso is indeed a JS app that talks to WordPress via a REST API, there must be a spot in the lifecycle of the app where it asks WordPress whether I have any social media accounts connected. I'm assuming in my case the answer is coming back "No", so I'm given the options to connect one. Since I'll be building and running Calypso locally to fix the issue, could I _pretend_ that I have a Google+ account by temporarily hardcoding a "Yes, he has a Google+ account" answer in some "state" or "model" object? Obviously I'll only use that show a Google+ connection so I can prove to myself that I've fixed the issue; it won't make it into the final PR. If such a thing is possible, I'd appreciate any pointers to the relevant spots in the code.

3. Another possible solution seemed a little more intrusive. The _entry spots_ to add a Google+ connection may be removed, but are such connections still represented in the database? Maybe we could give my account a temporary, fake Google+ connection, just so it shows up as a preview option for me in the UI. Out of curiosity: are social media connections associated with the user or the site?

Those were some of the ideas I had on how to proceed. Any advice on the best way forward and/or education about the relevant concepts would be greatly appreciated.

**Comment by arunsathiya** [comment]
Great ideas there, @koralcem! But, I don't think it's necessary to dwell that deep. 

You should be able to connect a different account (Twitter, Facebook, LinkedIn or Tumblr) on https://wordpress.com/sharing, and that should bring up the `Preview` section as well. This `Preview` section includes the Google+ submenu that needs to be removed.


<img width="482" alt="Screenshot 2019-04-22 at 14 51 44" src="https://user-images.githubusercontent.com/18581859/56493888-2b2fa100-650e-11e9-85f0-ab4b63f270a0.png">

<img width="745" alt="Screenshot 2019-04-22 at 14 51 35" src="https://user-images.githubusercontent.com/18581859/56493885-2b2fa100-650e-11e9-8ff0-9414bc3182bb.png">

**Comment by koralcem** [comment]
Gotcha. I've added a LinkedIn connection and now see the Google+ preview entry. Not knowing how things worked beyond the point I was stuck, I had expected the preview option to not show unless you had the corresponding account connected.

Thanks @arunsathiya. I'm on my way now.
