### ISSUE TITLE
Activity Log: Excessive usage of accent color for update notices

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#32114]
#### Steps to reproduce 

- Start with a WordPress.com Business plan site or Jetpack Professional site that likely hasn't received theme/plugin updates in a while.
- Visit https://wordpress.com/activity-log 

#### What is expected 

When the update notices pop up at the top, not all `Update` buttons are having the hot pink/accent color usage.

#### What happens instead 

There is excessive usage of hot pink/accent color usage.

<img width="1080" alt="Screenshot 2019-04-08 at 20 28 55" src="https://user-images.githubusercontent.com/18581859/55734500-4e058400-5a3d-11e9-8bd6-8cfde80ce4f5.png">

#### Notes

If I remember correct, accent color usage should be done sparingly and limited to one view. 🤔 

I believe something like only the `Update all` button having the hot pink usage should be a good idea, but I would defer to Design folks on that.

I couldn't find an existing issue for this, but if there is one, happy to be pointed at it!

#manual-testing

**Comment by cburton4** [comment]
Hi @arunsathiya,

Great catch. The Muriel guidance for button hierarchy reads as follows:

``A layout should contain a single prominent button that makes it clear that other buttons have less importance in the hierarchy. Use a high-emphasis contained button to command the most attention.``

In layman's terms this means that there should only be one contained button (also known as button primary / pink button) per screen and whichever button is contained should be the most important action we want a user to take on the screen. If all buttons have the same level of importance they should either be outlined buttons or text buttons. 

``Update all`` seems like best action for the customer to take so that button would be contained (also known as button primary / pink button) and the other update buttons would be outlined buttons.

![53780686-7694de00-3ed3-11e9-8a7c-6f10394f310d](https://user-images.githubusercontent.com/9257264/55738502-3efae380-59f5-11e9-827e-0a97cb9921c9.png)

Additional Muriel guidance on [button hierarchy and placement](https://murieldesignsystem.blog/components/buttons/#hierarchy-and-placement).

Let me know if you have any questions.

**Comment by arunsathiya** [comment]
That's very good to know, thank you @cburton4! 🙌🏽 I am not able to pick this up at the moment, but if anyone else wants to, feel free to.
