### ISSUE TITLE
Stats: Insights not matching

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#32149]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/month/jyotshnasafricandiaries.com
2. Views for February show 234
3. Click on the Insights tab
4. Views for February show 88 under "All Time Views"

#### What I expected
Insights tab showing the same amount of views from the Traffic tab.

#### What happened instead
The views for February are not matching between the Traffic and Insights tab.

#### Troubleshooting
I checked the user's site and account and wasn't able to identify why those numbers aren't matching.

#### Browser / OS version
Chrome 73.0.3683.103. OS X 10.13.6.

#### Screenshot / Video
The Traffic tab:
![Screen Shot 2019-04-09 at 11 24 39](https://user-images.githubusercontent.com/16104522/55808329-43d59b00-5aba-11e9-87da-fdc6a490fa2a.png)

The Insights tab:
![Screen Shot 2019-04-09 at 11 24 44](https://user-images.githubusercontent.com/16104522/55808355-4d5f0300-5aba-11e9-88e4-6de6af25de98.png)

#### Context / Source
From chat #11953552-hc. Follow up #1949506-zen.

#user-report

**Comment by otpidusprime** [comment]
User came back to chat at 12093686-hc asking for an update on this. I let them know that we are still looking into it and will follow up via email once we have an update on their case.

**Comment by rachelmcr** [comment]
I checked several of my sites (real and test sites) and confirmed that in each case, the very first month on the insights chart shows a lower number of views than the same months on the traffic chart. (The view on the traffic chart match the total views in the Posts & Pages section, so that seems to be the accurate count.)

All other months in the Insights chart are correct, so it looks like potentially an issue with how the first month on the insights chart is calculated.

**Comment by carinapilar** [comment]
> All other months in the Insights chart are correct, so it looks like potentially an issue with how the first month on the insights chart is calculated.

Thanks for testing @rachelmcr! Where should we report this? Can we leave it here?

**Comment by rachelmcr** [comment]
@carinapilar This is a good place for the report — thanks for opening the issue!
