### ISSUE TITLE
Editor: Media modal doesn't show newly uploaded media while the block editor is open

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#32181]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Start a new post in the block editor.
3. Add an image block to the post.
4. Upload a photo to the image block.
5. Add another image block.
6. Choose to add an image from the site's media library.

#### What I expected

I expected the media library modal to show the image I had just uploaded to the site. (This is especially helpful when using an image in two places in a post, e.g. the post content and featured image.)

#### What happened instead

The media modal doesn't show any new media uploads until the whole editor screen is refreshed.

#### Browser / OS version

Chrome 73.0.3683.86 & WPDesktop 4.1.0-beta2
macOS 10.14.4

#### Screenshot / Video

![gutenberg-media-modal](https://user-images.githubusercontent.com/8658164/55889748-78745000-5ba9-11e9-841e-ab032e384a28.gif)

#### Context / Source
#manual-testing

**Comment by AtrumGeost** [comment]
Hi folks!

Got another report for this bug here 2325436-zen. The user wanted to set as featured an image they just added.

I was able to reproduce on my end with Chrome only when using Calypso:

Version 76.0.3809.132 (Official Build) (64-bit) | macOS Mojave 10.14.6 (18G87)

The user that reported this issue is using the WordPress.com Mac App.

**Comment by AtrumGeost** [comment]
I ran a test and confirmed this is now fixed:

https://user-images.githubusercontent.com/3696121/154065579-cdea19fc-2be8-4df6-a386-073879f37df8.mp4

Closing the issue :)
