### ISSUE TITLE
Package: Calypso build- error on bad webpack filename

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#32227]
If there's a query string but the extension isn't `.js`, we return the input without the query:

```
x.ts?query
x.ts
```

That's buggy. Maybe we should throw and error if it doesn't match `/\.js$/i`

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/32194_

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
