### ISSUE TITLE
Jetpack Checklist: Tasks completion sometimes isn't up to date

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#32248]
As reported by @sirreal and @seear, and other folks before that while testing #32152 (I was also able to reproduce as well occasionally), task completion state isn't up to date sometimes.

So after a task gets completed and we quickly get back to the checklist, the task might be displayed as uncompleted. The opposite happens sometimes too.

At a first glance it seems like we're caching more than we should be. Let's investigate.

**Comment by tyxla** [comment]
#32273 addresses this for the Backups task.

**Comment by ockham** [comment]
I dug a bit deeper into this.

Checklist task completion state (both for WP.com and Jetpack) is [determined](https://github.com/Automattic/wp-calypso/blob/8c2446163d820214035bedf240242f6a55463f74/client/my-sites/plans/current-plan/jetpack-checklist/index.js#L198) by the get `getSiteChecklist()` selector, which in turn [returns](https://github.com/Automattic/wp-calypso/blob/8c2446163d820214035bedf240242f6a55463f74/client/state/selectors/get-site-checklist.js#L17) `state.checklist.items[ siteId ]`.

The latter is informed by the `/sites/${ siteId }/checklist` endpoint. This explains the delay we see after returning to the checklist some user interaction -- this issue.

However, we can obviously [update](https://github.com/Automattic/wp-calypso/blob/2546b83d7e96b269cdc1a26f37bd4709c5c5c86f/client/state/checklist/actions.js#L40-L51) `state.checklist.items[ siteId ]` [optimistically](https://github.com/Automattic/wp-calypso/blob/2546b83d7e96b269cdc1a26f37bd4709c5c5c86f/client/state/checklist/reducer.js#L32-L39). We actually do this upon [dismissal](https://github.com/Automattic/wp-calypso/blob/2546b83d7e96b269cdc1a26f37bd4709c5c5c86f/client/my-sites/checklist/wpcom-checklist/component.jsx#L140) of checklist tasks (note that task dismissal is only available for WP.com but not Jetpack sites).

So ideally, we'd also call `requestSiteChecklistTaskUpdate` upon completion of relevant checklist task, in order to update checklist state locally (and make a request to the endpoint, which in case of Jetpack sites shouldn't matter much, since unlike WP.com, we don't maintain a writeable list of bools on the server, but determine completion state by checking the relevant criteria). 

Practically speaking, this might be a bit tricky, since e.g. [Downtime Monitoring uses a `JetpackModuleToggle`](https://github.com/Automattic/wp-calypso/blob/2546b83d7e96b269cdc1a26f37bd4709c5c5c86f/client/my-sites/site-settings/form-jetpack-monitor.jsx#L145-L150), which is rather opaque and hard-wired to a different (Jetpack Module specific) Redux action to communicate the change to the server (and reflect it locally).

**Comment by jeffgolenski** [comment]
@ockham I'm just worried that normal end users won't see the task updated immediately and get confused or think the checklist is broken. 

If we're seeing a delay there and unsure how to squash it at this point, could we squeeze in the loading spinner (the one that displays during the "thank you" loading step for the tasks we auto-complete) until the task is effectively complete?

![Screen Shot 2019-04-09 at 12 19 17 PM](https://user-images.githubusercontent.com/214813/58101965-85279300-7bae-11e9-965f-f4c3e2e1ef85.png)

**Comment by ockham** [comment]
> @ockham I'm just worried that normal end users won't see the task updated immediately and get confused or think the checklist is broken.

Yep, definitely on the same page here :+1: 

> If we're seeing a delay there and unsure how to squash it at this point, could we squeeze in the loading spinner (the one that displays during the "thank you" loading step for the tasks we auto-complete) until the task is effectively complete?
> 
> ![Screen Shot 2019-04-09 at 12 19 17 PM](https://user-images.githubusercontent.com/214813/58101965-85279300-7bae-11e9-965f-f4c3e2e1ef85.png)

I'm afraid the information we'd need to ensure this behavior is pretty much the same as marking it as complete right after completion :sweat_smile:

Anyway, I think I have a fix here: #33193

**Comment by tyxla** [comment]
I think we can close this since #33193 got shipped.
