### ISSUE TITLE
Editor: Slideshow uses fullsize images in preview

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/wp-calypso#3228]
I uploaded 233 fullsize images to a site I run. I didn't resize them manually because I'm lazy and assumed that WordPress.com would take care of it for me.

Unfortunately the slideshow functionality is using the fullsize images, the 6000x4000 pixel ones. In total that's nearly a full gigabyte of images that are trying to load.

Can't we set some resize parameters since we know how big the images are going to be in the editor due to fixed width?

_**Related:** Ticket 7378 on WP.com Trac_

**Comment by DanReyLop** [comment]
I think we shouldn't resize the images in all the cases. The images in the carrousel have fixed width, but they still have a link to the original full-size image. That's a feature that some people need (photographers, for example).

I'm thinking approaching this similarly to the iOS Mail client. When you attach an image, it offers you the option to scale it (with size estimation). I don't have an iPhone at hand to take a screenshot, but it's something like this: http://www.macobserver.com/imgs/tmo_articles/20130426-05-EmailMultiImages.jpg

So what the editor should do is:
* User selects N photos from his drive.
* For each photo:
  * If the photo is "small", load it as-is.
  * If the photo is "big", show a modal with a few size options, plus having the option to upload the photo as-is. The modal should have a checkbox to apply the selected option to all the future photos.
    * If the user selected other option than the original size, resize the photo before uploading it.

It's technically feasible to re-encode a JPEG in the browser, so that's not a problem. The limit between an image being "small" and "big" will be somewhat arbitrary, and the size options given too, but apart from that, this could work. I'm thinking in doing it only for JPEG images for now, since that's the more common use case (_big_ photos).

What do you think about it? Does it seem a reasonable solution to you?

**Comment by DanReyLop** [comment]
@Viper007Bond The proposed solution assumes that the problem is that the full-resolution photos are being *uploaded*, so you don't want to transfer 1GB+ of photos to the server. Is that the real issue?

I've tried uploading some photos to a blog post, changing the gallery type, previewing it, and seeing the real post, and everywhere the images are properly resized (it only displays the huge photo when that is explicitly requested). So if that was the problem, maybe it was fixed after the issue was created?

**Comment by Viper007Bond** [comment]
No, I'm fine uploading the fullsize images, and infact I prefer it so that WP.com can properly create thumbnails in any size that's needed. However ideally thumbnails would be used when the images are not being displayed at fullsize. For example presumably most slideshows aren't viewed at 6000x4000 because themes aren't that wide.

**Comment by Viper007Bond** [comment]
By the way, you can view the issue here: https://wordpress.com/post/nwviperassociation.com/322

(Do we have super-admin working in Calypso? If not, feel free to add yourself to that site as an editor temporarily, or I can do it.)

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Tested and confirmed that the slideshow option loads images at full size.

<img width="1280" alt="screen shot 2018-01-02 at tue jan 2 9 47 28 pm" src="https://user-images.githubusercontent.com/1119271/34509486-a64c7192-f007-11e7-84bf-c08e7584ab9b.png">
<sup>Seen at https://design5279.wordpress.com/2018/01/02/slideshow-5/ using Firefox 57.0.3 on macOS 10.13.2.</sup>
