### ISSUE TITLE
Editor: Autosaves do not work for JP sites if the user is logged out on the JP side [8]

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32333]
Autosaves do not work for Jetpack sites if the user is logged out on the Jetpack side.

#### Steps to reproduce
1. Open a Jetpack site post in the Calypso editor (_not_ Gutenframe).
2. Make sure you're logged in to the Jetpack site's `wp-admin` in the same browser.
3. Make an edit (don't Update), and click Preview.
4. Verify you can see the newer content.
5. Log out off the Jetpack admin.
6. Reload the editor page.
7. Make an edit (don't Update), and click Preview.
8. Notice that the content is that which was originally loaded by the editor, without the edit.

Please timebox this issue.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
