### ISSUE TITLE
Reader: Logic for suggested blogs is unclear

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32372]
<img width="1631" alt="Screen_Shot_2019-03-06_at_10 20 46_AM" src="https://user-images.githubusercontent.com/2124984/56326206-1e443380-6143-11e9-8dc5-2a85814d059d.png">

What happened:

When I click "Find sites to follow" there doesn't seem to be rhyme or reason for what's suggested. There are suggested topics and some suggested posts. Are these trending?

What I expected:

For the function of these posts to be clearer. We can probably do this with some assistive language. Boon suggested something like:

"Because you follow..."
"Trending now..."
"New for you..."

etc.

**Comment by alaczek** [comment]
I'm guessing we'll need to connect with Reader squad to figure out this one.

**Comment by bluefuton** [comment]
# Suggested keywords

<img width="133" alt="Screen Shot 2019-04-19 at 12 14 06" src="https://user-images.githubusercontent.com/17325/56398439-aab63980-629c-11e9-9719-dfd642082257.png">

If the user is following any tags, we provide these as suggested keywords.

If the user is not following any tags, we provide 3 randomly selected suggestions from a pre-defined list for each language:

https://github.com/Automattic/wp-calypso/blob/master/client/reader/search-stream/suggestions.js

# Suggested posts

<img width="415" alt="Screen Shot 2019-04-19 at 12 14 12" src="https://user-images.githubusercontent.com/17325/56398448-b4d83800-629c-11e9-8daf-191b763a5c8e.png">

If the user hasn't searched for anything yet, we retrieve some recommended posts for them rather than show an empty page. These are based on the user's previous activity (including likes and comments). They're not trending posts.

**Comment by sixhours** [comment]
Since the suggested topics are random, I don't think we should change the language -- "Random topics" doesn't inspire confidence. :D Eventually it would be cool to have topics that are related to other things you've searched or comments/likes as well, but that's not on our radar right now.

For the posts, a brand-new user account will also get seemingly random results, because they haven't liked or commented anything, and we auto-follow several Automattic-owned blogs for them upon signup.

I'm going to call this a wontfix for now.
