### ISSUE TITLE
Add an eslint rule to forbid adding `devDependencies` in packages

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#32390]
If adding `devDependencies` to `package.json` in packages/apps can cause trouble (see e.g. https://github.com/Automattic/wp-calypso/pull/32383), we'll need an Eslint rule to stop folks doing this.

[Monorepo docs](https://github.com/Automattic/wp-calypso/blob/c3e6b4ef5120563152bdca9992537e15060d3356/docs/monorepo.md) say: 

>The only exception are devDependencies which must be declared in the wp-calypso root package.json. devDependencies of sub-packages in a monorepo are not reliably installed and cannot be relied on.

Note also conflicting `import/no-extraneous-dependencies` rule in packages (https://github.com/Automattic/wp-calypso/pull/32294#discussion_r276495780)

FYI @Automattic/team-calypso

**Comment by griffbrad** [comment]
I'll give this a shot.  Looks like the no-extraneous-dependencies rule is actually a decent model for what we need.

**Comment by blowery** [comment]
I think we're still working on this. Should be made easier / proper by https://github.com/Automattic/wp-calypso/pull/38190

**Comment by jsnajdr** [comment]
Big part of this issue was solved in #36534 by @simison himself when he added the `npm-package-json-lint` linter and enabled its `prefer-no-devDependencies` rule. But the config still allows adding dev depenencies to the `apps/*/package.json` files.

I pushed a commit to #38190 (its sha is https://github.com/Automattic/wp-calypso/pull/38190/commits/ae80bab17440c4ed83a392d9ae89c6682d5419fd as I write this, but will change after the next rebase) that modifies the linter config to allow dev dependencies only in the root `package.json`.

**Comment by scinos** [comment]
The original issue was raised when we were using `lerna` + `npm`. Since then we have moved to `yarn` and reduced our usage of `lerna`.

I do think having packages with `devDependencies` is a good thing and helps having a sane dependency tree without a bloated root package and packages relying on undeclared dependencies.

I'm closing this for now, if anybody has strong opinions about it we can revisit.
