### ISSUE TITLE
Calypsoify: The tabs for plugin search respond poorly on mobile.

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32406]
<img width="269" alt="Screen Shot 2019-04-18 at 10 55 15 AM" src="https://user-images.githubusercontent.com/2124984/56370035-7f621a80-61c8-11e9-8fa7-0aa4cc28aa6b.png">

The tabs wrap at an odd place and the spacing around the search field and Keyword dropdown is squished.

Here is a movie demonstrating the problem: https://cloudup.com/cTANlg3QOjo

**Comment by sixhours** [comment]
This means committing not to GH/Calypso but to /wp-admin, so will require a sandbox.

**Comment by crunnells** [comment]
Here is my proposed solution to this screen: 

<img width="379" alt="image" src="https://user-images.githubusercontent.com/4297811/59471794-f9350f80-8dd7-11e9-93aa-c71726a32777.png">

Changes:

* Changed the link padding from 16px to 8px
* Changed the `select` and `input` box to use flexbox to keep them inline
* Increased the height of the `input` so that it matches the height of the `select` at this screen size

**Comment by crunnells** [comment]
V2:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/4297811/59472358-d277d880-8dd9-11e9-8f21-0230d0b8c114.png">

* Changed links to stack vertically to accommodate even _smaller_ screens and languages where labels may be longer
* Slightly increased font size (from 14px to 16px)

**Comment by sixhours** [comment]
Ooh I prefer the V2, particularly because it will probably work better for multiple languages. How does the highlighted section look when it's not the top list item? Does it get a black underline?

**Comment by crunnells** [comment]
> How does the highlighted section look when it's not the top list item? Does it get a black underline?

Correct!

Something I thought of was checking out _other_ Calypsoify patterns, and looking at the previous screen which uses a similar nav bar, they center the items when the screen size gets small:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/4297811/59473844-e1fa2000-8ddf-11e9-916b-f5d0c4fa1598.png">

Since there's _somewhat_ of a precedent, I should probably follow the pattern above vs the v2 (at least making the links inline/centered with the search below). Thoughts?

**Comment by sixhours** [comment]
hmm, what does Calypso itself do? Since Calypsoify is meant to mimick Calypso, I think we should follow the patterns found there. We use tabbed headers in a lot of areas (Account Settings, Billing, etc.) so there should be precedent there as well.

**Comment by crunnells** [comment]
For the record, Calypso collapses the menu into a dropdown: 
![image](https://user-images.githubusercontent.com/4297811/64871798-b1de3b00-d5e1-11e9-8481-5ebb177f9cb8.png)

I'm not a fan on this pattern in this context, where the menu is short, and the solution would require adding JS to this page (instead of just adding CSS). I'm going to implement the v2 mockup for now as a good first iteration.
