### ISSUE TITLE
Editor: unable to update the image in Media & Text block

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#32415]
#### Steps to reproduce
1. Navigate to the block editor
2. Insert a Text & Media block
3. Choose an image for the image portion
4. Attempt to edit the image to a different one

#### What I expected

Updating the image works

#### What happened instead

Did not update

#### Browser / OS version

FF 66.0.3 / macOS 10.14.4

#### Screenshot / Video

![image-edit-fail](https://user-images.githubusercontent.com/195089/56391065-36738b80-61f3-11e9-812c-8a1c7f308b69.gif)

#### Context / Source

Discovered while testing the Page Builder MVP

**Comment by mmtr** [comment]
Here is an update after spending some time investigating this. It also happens on the WP Admin block editor, but I cannot reproduce on Core Gutenberg, so seems to be specific to WP.com.

All the attributes of the block are updated and actually, if you publish/update the post, the published view will contain the new image. The issue is only on the edit view.

Apparently, this `srcset` attribute is the one causing the problem. 

<img width="1128" alt="Screen Shot 2019-04-23 at 15 23 08" src="https://user-images.githubusercontent.com/1233880/56559258-0b66ae80-65dc-11e9-95f4-16f1ff8325b4.png">

After changing the image, the `src` attribute is updated to the new URL of the image but `srcset` keeps maintaining the previous URL.

I don't know where that `srcset` is coming from, but maybe this can help to someones else who would like to continue working on this :)

**Comment by codebykat** [comment]
So weirdly I can reproduce this on Calypso (iframed) but not on wp-admin. In wp-admin I don't have a `srcset` attribute at all:

<img width="669" alt="Screen Shot 2019-05-02 at 7 25 39 PM" src="https://user-images.githubusercontent.com/52152/57117326-1de59400-6d10-11e9-807c-a530c6911ae7.png">

**Comment by codebykat** [comment]
Okay so in both Gutenberg wp-admin and WPCOM wp-admin I do not see the `srcset` attribute added until the post is published. It's only in Calypso iframe that the `srcset` attribute is added within the editor itself.

**Comment by mmtr** [comment]
I wonder if D27606-code has some relation to this

**Comment by gwwar** [comment]
I can't reproduce this one, please reopen if folks are still having trouble.
