### ISSUE TITLE
Hover State Remaining after Click on Mobile Devices

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#32423]
#### Steps to reproduce
1. Starting pretty much anywhere on Calypso, but https://wordpress.com/plans as an example (must be on mobile) 
2. Tap "Business and Online Stores" 
3. Notice that the lighter colour indicates it's still in a hover state - you need to tap away from it to turn to its normal colour. 

![Screenshot_20190419-090131](https://user-images.githubusercontent.com/43215253/56409521-2ce53480-6282-11e9-89bd-2ce7cd0571ba.jpg)

#### What I expected

I expected, upon clicking the button, for it to longer be in a hover state. This affects a lot more outside the Plans page though, for example the slightly horrible contrast in the new sidebar layout. It's likely also causing #30257. 

Using Chrome 73 on Android

**Comment by bluefuton** [comment]
This is caused by the focus styles applied when a current `is-selected` and has focus. Tapping away from the control restores the correct colour because the element no longer has focus.

I'm not sure how to resolve this one without removing the focus colour on `is-selected`, and that doesn't feel like a good solution.

**Comment by bluefuton** [comment]
It can be reproduced on desktop too from the Devdocs page:

http://calypso.localhost:3000/devdocs/design/segmented-control

**Comment by sixhours** [comment]
I think the solution is to use separate colors for `hover` and `focus`/`is-selected` states, and the latter should use colors with higher contrast.
