### ISSUE TITLE
Domains: Entering multiple keywords is an odd way to domain search

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32514]
<img width="1280" alt="Screen Shot 2019-04-23 at 10 24 31 AM" src="https://user-images.githubusercontent.com/2124984/56588766-00972400-65b2-11e9-8612-62af25b71ef5.png">

The domain search suggests using multiple keywords to describe your business, but then the keywords are strung together to suggest a domain. So if you put in "animal care dogs cats" you could get suggestions like "animalcaredogscats.care" which is a terrible suggestion for a business' domain name. :)

I don't have a solid "What I expected" for this one, it's something that needs further thought and probably guidance on the copy. Changing the language around domain search to avoid using the word "keywords" seems like a good start, since that has SEO-ish connotations.

**Comment by alaczek** [comment]
I also found it confusing that description asks to enter the site's name, when I was just asked for it in the previous step. I was thinking it would make sense to use whatever input was already provided. Here's a screen of step 1 of site creation for reference:

![image](https://user-images.githubusercontent.com/4550351/56873577-90d3de00-6a76-11e9-8394-141420e4dc48.png)

I don't know how hard it would be change how the suggestions work, so that they actually utilise the keywords. As a stop-gap I think it would make sense to change the description to explain that this field is to search for actual domain name. Another option would be to get rid of the description above the field entirely, and update the search field placeholder.
Some examples from around the web:
* Find your perfect domain name (GoDaddy)
* Search for a domain name (Google Domains) - I think something simple like this could work for us too.

**Comment by danhauk** [comment]
> I was thinking it would make sense to use whatever input was already provided.

There was an A/B test a little over a year ago to measure what kind of affect pre-filling the domain search with the site title in the previous step. It actually showed that not pre-filling the domain converted better. You can read more about the test, results, and some hypotheses around why the pre-filled variation converted worse at p7jreA-1vS-p2

However, that was over a year ago, and it might be worth another test. We have a new (better?) domain suggestion engine. I also agree we should revisit the copy on this step. I don't think it's been looked at in quite some time.

**Comment by obi2020** [comment]
I've flagged this, too. There are probably some quick & dirty improvements we could make to the subhead and prompt copy, but I'd really like to examine the entire page - particularly the one preceding what you show here, @sixhours, which has several elements that contribute to user understanding of what's happening:

1. Header
2. Subhead
3. Search prompt
4. Gear/settings
5. Assistive text
6. Learn more link
7. Graphic example

![image](https://user-images.githubusercontent.com/3373750/56917791-67bd4880-6a8a-11e9-923b-1f775298c4da.png)

***

Some explorations: 

1. `Find a domain for your site`
2. `Your domain name is like your address on the internet. Make sure it describes your business.`
3. `marysbaskets.com, for example` Though this is repetitive of content in 7. Real estate here could be used, instead for what's buried under the gear icon.
4. Needs more than copy change, Filters + gear isn't working to describe how this is used.
5. Remove it. Not needed if other copy is effective
6. Copy is fine as is, but get's lost as there's so many other things happening.
7. Fine as is, though same could be accomplished by search prompt.

**Comment by fditrapani** [comment]
Thanks for those suggestions @obi2020. As a first quick pass, I like the suggestions you're proposing. 

> Find a domain for your site

We have had an endless debate about whether it's too early to use the word domain here. It's like a chicken and egg situation. If we avoid saying it then when is the right time to bring it up? Personally, I'm of the opinion that we educate people as early as possible and in combination with the subtitle, I think it works here. 

> Your domain name is like your address on the internet. Make sure it describes your business.

Depending on the segment the "Make sure it describes your business" might not be applicable. It wouldn't make much sense for a blog as an example. That being said, we can conditionally change the copy for blog, professional, store, or business. Going with your "shorter is better" principal, I would opt for leaving it out all together. 

> marysbaskets.com, for example

I worry that by including the tld, we might be limiting choices for folks or maybe even setting them up for disappointment if the .com is not available. I think enter a name or keyword might still work along with the graphic that shows the example in it. 

> Remove it. Not needed if other copy is effective

Due to the removal of some elements, it might be worth while revisiting the layout to accommodate.

**Comment by donpark** [comment]
I think domain name is too important to be chosen part of signup process and best set aside as an optional step with *.wordpress.com and *.wpcomstaging.com used as defaults.

I don't have any data to back up my theory but I think a lot users abandon purchase at the point domain needs to be chosen for this reason.

**Comment by obi2020** [comment]
That resonates as true, @donpark, though I don't have the data either.  I think, though, that it's still valid to introduce the concepts of the address as domain since site creation necessarily creates a new domain (right?). It's like choosing a username when you create a new account. It's an important branding moment that's a necessarily part of, but if we can communicate that there's still flexibility to improve it later that might make potential customers less intimidated.

@fditrapani thanks for that feedback. Yes, I'm pro early education, though it means we have to be sure we're actually educating properly. Domain = address = URL ... really don't know which is most used or recognizable by customers (SMBs, specifically). Ran's user testing implied that customers were familiar with `domain name` but not sure if that can be counted as statistically significant. I personally like `address` because it evokes a non-digital mean, too, but think we can refine the copy to equate the two

**Comment by klimeryk** [comment]
Closing this as it's not an actual issue - this discussion should be on a P2, including all the stakeholders. As it is now, it's based on anecdotal data and personal opinions, when there have been tests and research already done (and being done) around it.
