### ISSUE TITLE
Checkout: "Continue to Checkout" button is confusing 

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32528]
<img width="1153" alt="Screen_Shot_2019-03-07_at_11 25 12_AM" src="https://user-images.githubusercontent.com/2124984/56604244-86759800-65cf-11e9-9a18-1f5165ce4c27.png">

Button title is confusing because it appears that you are already on a checkout page. The wording for this button could be clearer; "Continue Checking Out" is a bit long, but I think closer to the sentiment we're trying to get to.

(Check with @danhauk before working on this one.)

**Comment by arunsathiya** [comment]
Alternatively, would `Proceed` or `Continue` be a good option? 

We have used `Continue` on G Suite purchase flow:

<img width="804" alt="Screenshot 2019-04-24 at 11 18 40" src="https://user-images.githubusercontent.com/18581859/56635308-c77ab480-6682-11e9-90b9-e5708a3ab050.png">

**Comment by danhauk** [comment]
`Continue` works great!

**Comment by arunsathiya** [comment]
PR in https://github.com/Automattic/wp-calypso/pull/32569. For some reasons, it looks like GitHub will not auto-close this issue when the PR is merged. Maybe because I used the text `Details in https://github.com/Automattic/wp-calypso/pull/32569` on that PR. 😕

Will keep an eye out and close this issue when the PR is merged.
