### ISSUE TITLE
Checkout: Cart icon has no label, and there's room for one

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32531]
<img width="181" alt="Screen_Shot_2019-03-07_at_10 47 02_AM" src="https://user-images.githubusercontent.com/2124984/56606150-95f6e000-65d3-11e9-8c26-065ae2018abe.png">

There should be a text label alongside the icon for clarity. I believe this is a Muriel principle?

**Comment by iamtakashi** [comment]
There are a few approaches to add a button text, and I made a mockup to gather feedback before working on a PR.

![cart-icon](https://user-images.githubusercontent.com/908665/56813781-9b536500-6835-11e9-8dcb-e886926bb338.png)

**Custom Borderless Button**
A borderless button uses `--color-text-subtle`, but with the importance of the button, it's probably better to customise it to use `--color-neutral-700`.

**Header Button**
We could use a `HeaderButton`, but the icon gets small, and it doesn't work well with the count badge.

**Custom Header Button**
We also could customise a `HeaderButton` to show the icon and text side-by-side to keep the icon the same size. If we think its `min-width` is too wide for this we could make it narrower as well.

I'm leaning towards Custom Header Button, but what do folks feel? Thanks in advance!

**Comment by shaunandrews** [comment]
I like the `headerButton` as well — the spacing feels nicer than the borderless button. [A quick search](https://github.com/Automattic/wp-calypso/search?l=JSX&q=headerButton) shows that there's only a few uses of the `headerButton` component. Perhaps we can update the component itself, rather than adding some CSS to customize this instance of it?

**Comment by drw158** [comment]
Agreed with the discussion above. Although I don't think there is any documentation on this in Material, I'd like to keep the icon to the left of the text. I've seen other design systems do the same thing — by default icon button should have the icon on the left, unless there is implied forward/backward motion, like a pagination component.

**Comment by iamtakashi** [comment]
Thanks for the feedback, folks. 

In today's show and tell I also heard `headerButton` as it currently is not working for this as well as other places (/themes and /plugins). So it makes sense to update the component.

> I'd like to keep the icon to the left of the text
That was exactly what I was going to ask you :) One of the feedback I received was to see how it'd look if the icon was on the right :) I'll just add a mockup here because I made this before I read your comment :)

![custom-reversed-headerbutton](https://user-images.githubusercontent.com/908665/56913544-d1008400-6aa9-11e9-93c1-3e81d1ead564.png)

Would it make sense to fix this first using a `headerButton`, and update the component or update the component first?

**Comment by iamtakashi** [comment]
I think I'm going to work on the `headerButton` first to make the icon and text being side-by-side first. I'm concerned about a possible negative impact with the small cart icon if I change this to `headerButton` first. I'll create a separate issue about the component.

**Comment by sixhours** [comment]
Now that we've updated HeaderButton, someone can pick this specific issue up again. Moving to To Do.

**Comment by davidakennedy** [comment]
@sixhours I'll grab this one.
