### ISSUE TITLE
Gallery block not displaying properly on mobile devices

### ISSUE THREAD

**Issue by annacmc** [Automattic/wp-calypso#32593]
It seems that the unordered list element of the gallery block is indenting & displaying the bullet points next to the images when viewed on the Android mobile version of the site, or in the reader via Android. When viewed on iOS the images are indented but not bulleted.

When switching to 'View Full Site' mode the images once again display at the full width of the device. Switching off AMP does not fix the display in the reader. 

It's also possible to view the bulleted images from a web browser when switching to AMP editing mode in the customizer. 

I've replicated this on a testing site with a few different themes.

#### Steps to reproduce
1. Add the pictures by adding block using the +, select Gallery, then select from the Media library, and add a few at a time. Switch the display from 3 images per column to 1. 
2. View the post from an Android device, either in the browser or in the reader to see the images bulleted.
3. View the post from the customizer -> AMP  to see the images bulleted
4. View the post from an iOS device browser to see the images indented, but not bulleted.

#### What I expected

Expected to see the images taking the full, normal width of the screen, without indentation or bullet points regardless of the device or browser being used. 

#### Browser / OS version

Have tested this across web browsers Chrome, Firefox & Safari, and on iOS mobile Safari, the iOS WordPress App reader and the Android WordPress App Reader.

#### Screenshot / Video

View of bulleted images via AMP editor in the customizer: https://cld.wthms.co/MQSQTd
View of indented images via iOS Safari browser: https://cld.wthms.co/3WH5lW
View of bulleted images via the Android WP App Reader: https://cld.wthms.co/OjiX5D

**Comment by designsimply** [comment]
Thanks for reporting this @annacmc! 

This was also reported at https://github.com/wordpress-mobile/WordPress-iOS/issues/10206 and https://github.com/wordpress-mobile/WordPress-Android/issues/11673. 👍

Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/10450 props @aerych and https://github.com/wordpress-mobile/WordPress-Android/pull/12213 props @malinajirka. 🎉

I tested and confirmed the update again today using Chrome and WPAndroid 15.4-rc-1 on Pixel 3 Android 10 as well as Safari and WPiOS on iPhone 11 iOS 13.6. I was unable to find the AMP settings either Calypso or WP Admin customizers.

Chrome Android|WPAndroid Reader|Safari iOS|WPiOS Reader
---|---|---|---
![Screenshot_20200805-155913](https://user-images.githubusercontent.com/1119271/89469426-9ec2e500-d736-11ea-809a-0ae20072a218.jpg)|![Screenshot_20200805-155900](https://user-images.githubusercontent.com/1119271/89469432-a08ca880-d736-11ea-881b-9df1a75d966a.jpg)|![IMG_4435](https://user-images.githubusercontent.com/1119271/89469813-7c7d9700-d737-11ea-8f9a-8288c2bb74ed.PNG)|![IMG_4433](https://user-images.githubusercontent.com/1119271/89469807-78ea1000-d737-11ea-89fa-20d913894e90.PNG)
