### ISSUE TITLE
Settings: Related Post setting "flips" for Jetpack sites

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#3262]
Steps to reproduce:
0. Visit My Sites->Settings for a Jetpack site that already has Related Posts enabled.
1. Change the Related Posts option to `Hide related content after posts` and save (this turns off RP on the Jp site)
2. Attempt to change back to `Show` option.

Expected: The setting to stick and able to click "Save"
Actual: The radio button flips back to Hide after a couple of seconds.

If you click Save fast, it'll change the setting.

**Comment by lancewillett** [comment]
I re-tested this today, and things worked as expected.

Could the original issue have been due to an API timeout by any chance? Or a connection issue on your end?

Here's a visual walkthrough for reference.

1. Started in my Jetpack site's wp-admin Jetpack plugin settings, enabled Related Posts module.
![screen shot 2016-05-09 at 3 33 10 pm](https://cloud.githubusercontent.com/assets/66797/15130572/61f2c2f6-15fe-11e6-96a7-78712e68776f.png)

2. Then turned on the setting in Settings -> Reading in the same wp-admin area, same site.
![screen shot 2016-05-09 at 3 33 38 pm](https://cloud.githubusercontent.com/assets/66797/15130584/706750a4-15fe-11e6-8413-a07d3964d034.png)

3. Then I went to wpcalypso and looked at the settings for this site.
![screen shot 2016-05-09 at 3 34 04 pm](https://cloud.githubusercontent.com/assets/66797/15130589/7b8b1696-15fe-11e6-8a02-d6aca7449581.png)

4. Then I turned it off in wpcalypso
![screen shot 2016-05-09 at 3 34 23 pm](https://cloud.githubusercontent.com/assets/66797/15130598/84a6d71a-15fe-11e6-840e-c2ccf087e145.png)

5. Checking back in wp-admin, the module is now "off" — cool. Not exactly what I expected, but OK.
<img width="852" alt="screen shot 2016-05-09 at 3 34 41 pm" src="https://cloud.githubusercontent.com/assets/66797/15130603/90aa28be-15fe-11e6-88bc-698a5ca739b7.png">

6. Back in wpcalypso UI, turn it on again.
![screen shot 2016-05-09 at 3 35 03 pm](https://cloud.githubusercontent.com/assets/66797/15130617/aec20736-15fe-11e6-9c40-f0970aad3165.png)

7. Waited, and the setting did stick.

**Comment by kraftbj** [comment]
I think something was fixed in the meantime. It was being seen on multiple sites on stable and dev versions of Jetpack. It *would* save, but only if you clicked Save faster than the browser reverted flipping the switch. 

In either case, it works for me now. ¯\_(ツ)_/¯
