### ISSUE TITLE
Inline Help: Button animation looks broken

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#32639]
**Steps to reproduce**
1. Anywhere inside Calypso hover over the help icon in the bottom right corner to see the animation.

**Result**
Quick video of the issue: https://cloudup.com/c9A87aQIhcv

**What I expected**
I think we should re-think the animation here (tagging Muriel in case there are already guidelines around this). At the very least I expected the animation to be fluid, not jerky and stuck on repeat.

**Browser / OS version**
Chrome 73.0 / macOS 10.14.4 (Mojave)

**Comment by shaunandrews** [comment]
This is actually intentional. I was hoping to help draw a little attention (and add some personality) to the button on hover — something like friendly wave hello — to help people understand there's helpful stuff hidden behind the button.

I don't have a strong attachment though, so if there's a better alternative — or someone feels strongly enough to remove the animation — don't let this comment stop you.

**Comment by danhauk** [comment]
I'd vote for removing it. I understand the idea behind it but I think it's not necessary. However, we should have some kind of hover state on it (maybe a color change).
