### ISSUE TITLE
Importer: email sent upon completion needs HTTPS for WP.com sites

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#3266]
Saw this when testing #3133 

<img width="797" alt="email-unencrypted" src="https://cloud.githubusercontent.com/assets/66797/12992804/c185e6c8-d0d3-11e5-81d7-f46e75e752a6.png">

1. Gmail flagged it as non-encrypted.
2. The *.wordpress.com URL had `http` instead of the expected `https` prefix.

Note: this is probably a WP.com back-end change and not Calypso related.

**Comment by lancewillett** [comment]
Possibly related to #2030

**Comment by lancewillett** [comment]
Looking at the email headers, the main differences are:

1. `ESMTPS` in the encrpyted; `ESMTP` in the non.
2. `TLS1_2` header line in the encrypted; missing in the non.

**Comment by dmsnell** [comment]
Thanks for the report. As we have emails with _and_ without the TSL encryption stemming from the same line of code, I'm guessing this is either related to temporary burn on the servers sending the email or maybe it was related to sending from a sandbox vs sending from production.

I'm closing for now since there is nothing to change to make this work. If we continue to find these warnings in Gmail we can start tracking down the when and why.

**Comment by lancewillett** [comment]
Sounds good, thanks for commenting and closing.
