### ISSUE TITLE
Gutenberg: Embeds: Google Forms embed doesn't work on mobile

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#32701]
#### Steps to reproduce
1. Starting at URL: https://carinatest3.wpcomstaging.com/google-form/
2. Add a Google Form embed code using an HTML or Shortcode block on a page.
3. Publish the page.
4. Check the page on mobile.

#### What I expected
To show as you see on desktop, even when resizing the browser's window to mobile screen sizes.

#### What happened instead
The form gets moved outside the layout in the right (user's form). Or it doesn't show at all (my test forms).

#### Browser / OS version
Safari on an iPhone XS, iOs 12.2. 

#### Screenshot / Video
![IMG_6629](https://user-images.githubusercontent.com/16104522/56989644-54cd7580-6b69-11e9-8a2f-9a6f26fd5a16.jpg)

#### Context / Source
#user-report 
1998847-zen

**Comment by AtrumGeost** [comment]
Found out this is only happening on iOS devices. Tried on an actual Android device and also with Browserstack and it loaded normally:

![Screen Shot 2019-04-30 at 15 43 00](https://user-images.githubusercontent.com/3696121/56992010-b63c1700-6b5e-11e9-8bc9-90b6ee51a420.png)

Also, the user came back to say they changed the size of the image on the form and that fixed it for them. But this is still worth investigating

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
