### ISSUE TITLE
Gutenberg: format "core/underline" is already registered to handle bare tag name "span"

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#32747]
When Opening block editor on a Jetpack site, I see this in console:

<img width="914" alt="Screenshot 2019-05-02 at 10 04 26" src="https://user-images.githubusercontent.com/87168/57060378-e3550a80-6cc1-11e9-9073-6009753fd461.png">

Underline doesn't seem to appear in the toolbar:

<img width="347" alt="Screenshot 2019-05-02 at 10 04 55" src="https://user-images.githubusercontent.com/87168/57060405-f36cea00-6cc1-11e9-8f62-caa7ca8cf7fc.png">

Using latest Jetpack `master` and Gutenberg 5.6.1.

cc @Automattic/lannister

**Comment by obenland** [comment]
@Copons Could you take a look at this when you get a chance?

**Comment by Copons** [comment]
This is what it seems to be happening.
When I've introduced the underline format (`wpcom/underline`), there was no `core/underline` format available in Gutenberg.
Although, this changed in, I think, Gutenberg 5.2 (which AFAIK is not yet merged into Core?), when [it was reinstated as a default format](https://github.com/WordPress/gutenberg/pull/14008).

Both ours and [Core's implementation](https://github.com/WordPress/gutenberg/blob/5c48dc17d8bc4ba94f03210d8120e73eadcc516a/packages/format-library/src/underline/index.js) rely on a `span` element with the underline applied via CSS, which is the correct way to do so, according to my own opinion and, more importantly, to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u).

Our version adds a button to the inline format toolbar, while Core's adds the CMD/CTRL+U shortcut, so they shouldn't really conflict between each other.

As it turns out, though, [it's not possible to have multiple formats on the same tag](https://github.com/WordPress/gutenberg/blob/5c48dc17d8bc4ba94f03210d8120e73eadcc516a/packages/rich-text/src/register-format-type.js#L81-L90).

Now I think this is quite unfortunate, isn't it?
Not all inline formats have their own tag, but instead they can simply be a `span` with some attributes.

I think there are a few different approaches we can take here:
- We can open a Guten PR to remove the check that triggers the "already registered to handle bare tag name" error, allowing multiple formats for the same tag (which seems a good thing to me, but I assume there are technical reasons why it's forbidden).
- We can remove the `wpcom/underline` button (but I don't think anyone wants this).
- We can unregister `core/underline` before registering `wpcom/underline` and add the former's shortcut logic into the latter.

**Comment by obenland** [comment]
Can we extend Core's underline to add the button?

**Comment by Copons** [comment]
> Can we extend Core's underline to add the button?

I don't see any extensions point in the `@wordpress/format-library` package, so I believe that if we want to have both features (and I assume we do), we'd need to do the whole unregister/register switcheroo.
