### ISSUE TITLE
Gutenframe: Admin Bar visible in Preview

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#32769]
#### Steps to reproduce
Create or edit a post on a Jetpack site from Calypso and preview the post.

#### Screenshot / Video
<img width="1406" alt="analog-retrospective-e28094-wordpress com-2019-05-02-20-11-35-1" src="https://user-images.githubusercontent.com/1398304/57096712-c113ba80-6cca-11e9-9f0f-9e183f7aef5f.png">

**Comment by kwight** [comment]
The admin bar is not present on simple sites because of the presence of a `frame-nonce` query param. Pulling the `previewUrl` from the `WebPreviewContent` component and loading it in a tab of its own, I can turn the admin bar on and off by removing or keep the `frame-nonce` param.

**Comment by obenland** [comment]
So it stays around because we switched to `jetpack_frame_nonce`?

**Comment by kwight** [comment]
The presence of a verifiable frame nonce sets a constant which, when detected by the masterbar on dotcom sites, will disable it. Since no similar mechanism exists for Jetpack (nor Atomic) sites, something could be added server-side (in Jetpack's `modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php`) or client-side in the block editor app here in Calypso (`apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js`). Although, server-side may be necessary, since we can't really verify a nonce client-side.

There's also `Jetpack_Frame_Nonce_Preview`, which could just call `show_admin_bar(false)` somewhere.

**Comment by kwight** [comment]
> So it stays around because we switched to jetpack_frame_nonce?

No, it's unrelated. Well, yes, related, in that to do the same thing that we do with dotcom, we'll have to update the `?frame-nonce` for the preview to be `frame-nonce` from the API, not `jetpack_frame_nonce` (I have a PR almost done for this part). But unrelated anyways, in that Jetpack sites don't have any system in place that removes the admin bar based on the presence of a URL's `frame-nonce`.
