### ISSUE TITLE
Full Site Editing: investigate options to clean up the MVP [8]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32824]
The original MVP inserted a global block into `post_content`. Investigate options on how to clean this up and replace it with a new representation relying on `wp_template`. For example: migrate post_content, update the block to render nothing, etc.

**Comment by mattwiebe** [comment]
I've prepared a patch at D28083-code that will migrate a given site from the MVP to whatever we have now. 

It's more than a proof of concept, since it already works and does much of what we need, but there are many things that will need to be addressed once we are actually ready to do the migration. (Everything I could think of is noted in the code.)

After the migration is complete, we will definitely be able to remove the Twenty Nineteen fork. The `site-builder` plugin, however, will need more investigation, but I believe we should be able to remove it, as well.

One other thing we may want to consider is whether to add a specific notice for these users, letting them know what has changed, how now to edit their site title and tagline.

I'll park this in "ready to review" just in case there's something I'm overlooking here but I believe this to be done for now.

**Comment by gwwar** [comment]
@mattwiebe any more work needed here?

**Comment by mattwiebe** [comment]
> any more work needed here

Nope, we can call this done.
