### ISSUE TITLE
Gutenframe: Editing with Elementor plugin triggers X-Frame-Options/sameorigin error

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#32887]
#### Steps to reproduce
1. Start with any Jetpack site in Calypso
2. Install the 'Elementor' plugin (https://wordpress.org/plugins/elementor/)
3. Edit a new page
4. Click 'Edit with Elementor' button

#### What I expected

Elementor to load the fullscreen editor (as would happen by clicking the 'Edit with Elementor' link in wp-admin/posts (eg /wp-admin/post.php?post=16&action=elementor)

#### What happened instead

Browser shows a 'Refused to connect' error and console has an error:
`Refused to display[URL] in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

#### Browser / OS version
Mac OS 10.13, Chrome Version 74.0.3729.131

#### Screenshot / Video

<img width="1340" alt="Screen Shot 2019-05-08 at 12 51 45 pm" src="https://user-images.githubusercontent.com/1842363/57345957-1c90ed00-7190-11e9-9c28-83248569d1d3.png">

<img width="1336" alt="Screen Shot 2019-05-08 at 12 51 26 pm" src="https://user-images.githubusercontent.com/1842363/57345956-1c90ed00-7190-11e9-8168-1708317e0a42.png">

#### Context / Source
#user-report in 2015542-zen

**Comment by mlaetitia** [comment]
More user reports here:
2015680-zd
2016137-zd
2016176-zd

**Comment by benchilcote** [comment]
Another report here
2016780-zd

**Comment by kwight** [comment]
Hm, this is worse for anyone installing Elementor _after_ the block editor is active; it looks like after installation, the plugin hijacks the next admin view and redirects to `http://kirkwight.ngrok.io/wp-admin/admin.php?page=elementor-getting-started` – which definitely doesn't handle the iframe verification, and fails with Mr. Sad Browser (console error: `Refused to display '/wp-admin/admin.php?page=elementor-getting-started' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by kwight** [comment]
[Elementor](https://wordpress.org/plugins/elementor/) is a page building plugin that, once installed, allows any page or post to be edited in their custom full page tool (`wp-admin/post.php?post=postId&action=elementor`). They also have another [plugin](https://wordpress.org/plugins/block-builder/) specifically for use with the block editor, but it too redirects to `wp-admin/post.php?post=postId&action=elementor` if the user wants to edit the block itself.

I was able to get Elementor loading and working properly using the same auto-nonce technique we use on WP.com, but with the Elementor sidebar having more admin and external links (view post, return to the dashboard, etc.), we could end up any number of places and stuck within the iframe.

The best solution is to do a `wp-admin` redirect instead of iframing if either of the plugins is detected.

**Comment by grvrulz** [comment]
Another report
2016211-zd

**Comment by tristanleboss** [comment]
@kwight I'm interested by having a plugin like Elementor work in Calypso (Desktop version).

1. Is it possible for you to explain the "auto-nonce technique we use on WP.com" which allowed you to use Elementor inside Calypso?

2. How a plugin like Elementor can detect in either PHP or JS if it's used in Calypso?

3. If used inside Calypso, what to do with external links (view post, return to the dashboard, etc.)? Should they be replaced by JS calls? different URLs?

**Comment by kwight** [comment]
@tristanleboss Sure – a few things to note.

We now actively block Elementor from WordPress.com integration; we rely on iframing a fullscreen block editor, and plugins that do redirects and their own integrations result in really unreliable and confusing flows for users. That said, if you want to fork your own version of Calypso to make it work, go for it!

1. The "auto-nonce technique we use on WP.com" is a combination of Jetpack and server-side code for verifying nonces – depending on what you're doing, you'll need your own mechanism to allow your client and server to agree on what is a valid nonce. [This is the WP.com implementation](https://github.com/Automattic/jetpack/blob/master/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php).

2. This could be done in many ways; a simple option is to have the parent request the iframe with a certain query param, so that when the iframe loads, it [sees the param and knows it's iframed](https://github.com/Automattic/jetpack/blob/master/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L57).

**Comment by tristanleboss** [comment]
Thanks.

Yes, I understood you ended up blacklisting Elementor through a whitelist.

TBH, I don't think Elementor will do any changes to be supported in Calypso. Indeed, unfortunately, they are really focused on mainstream users/uses: they don't really communicate and address developpers/power users need. I just hope Gutenberg features will be on par with Elementor features one day.

But, yes, I want to have a look at it because I manage 10's of self-hosted websites using Elementor, for now.

**Comment by csabarakasz** [comment]
- [ ] 37015603-hc

Same issue. I could replicate it. Workaround: use the WP-Admin, Edit with elementor link.
