### ISSUE TITLE
Cover Block attempts to remove paragraph block between div

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#32980]
#### Steps to reproduce
1. Add a cover block and image on editor
1.1 Add any modified text (font size, text color)
2. Expand "More options", select "edit as HTML"
3. From here, select anywhere else other than the current cover block.

#### What I expected
You are able to switch back to "edit visually" on cover block.

#### What happened instead
The error "This block contains unexpected or invalid content." appears on the cover block. Click on "Resolve" shows it attempts to remove paragraph block div in between

#### Screenshot / Video
![image link 1](https://cldup.com/OGF1zjWBSt-3000x3000.png)
image link: https://cloudup.com/cD2fsdLavNG

#### Context / Source
Sample test post: https://wp.me/P8Ss57-Kd
Ticket: #1986507-zen

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
A quick test indicates this appears to be resolved/not replicable: 

https://github.com/Automattic/wp-calypso/assets/27249804/4d837c93-253c-4d3a-93c5-b5088fccc925
