### ISSUE TITLE
Sometimes "Manage All Reusable Blocks" link not working

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/wp-calypso#32997]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/pages/
2. Open up a page
3. Click the plus icon to insert any block
4. Click on "Reusable Blocks"
5. Choose "Manage All Reusable Blocks"

#### What I expected
It should load this page: https://wordpress.com/types/wp_block

#### What happened instead
The page never loads

#### Browser / OS version
Safari Version 12.1 / MacOS 10.14.4

#### Screenshot / Video
Here's a GIF: https://cloudup.com/cyL8BnnXd7N

#### Context / Source
 #user-report in 12761373-hc

**Comment by gwwar** [comment]
Was this an Atomic or Jetpack site? 
I wasn't able to reproduce on simple sites

**Comment by philnick206** [comment]
I am seeing this same issue on another users site at the following location: https://wordpress.com/types/wp_block/redriverparishjournal.com

Steps are the same as above.

**Browser / OS version**

Firefox (68.0.2) / Windows 10 (1903)

Context / Source

Ticket: https://woothemes.zendesk.com/agent/tickets/2295656

#user-report

**Comment by TeniCola** [comment]
I had this exact same experience for a related issue I just posted -- #36343 

For me, trying to load the page using "Manage All Reusable Blocks" would not work for me on this user's simple site. Rather, it would not load when I was in SU or SS mode.

It _did_ finally load for me when I switched to using SSP, and it also worked for me as expected when I used my own test site. So I think that issue may be related to SS or SU mode.

p1569418633142200-slack-livechat

**Comment by gwwar** [comment]
Didn't have luck reproducing but wouldn't be surprised if this needed more env setup to trigger this.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
With the more recent updates to Patterns, this is likely no longer applicable as well.
