### ISSUE TITLE
Ecommerce Plan: Typo on My Plans page when using the ecomm plan

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33039]
<img width="774" alt="Screen Shot 2019-05-14 at 4 12 15 PM" src="https://user-images.githubusercontent.com/2124984/57729015-2c627280-7663-11e9-9ee4-5a7c875afbcf.png">

Viewing My Plans under `/plan/my-plans` shows "Your site is on a eCommerce Plan" -- "a" should be "an" here.

Originally reported by @ianstewart . The whole video of signup process can be found in this post (under eCommerce plan customers): paObgF-7Y-p2

**Comment by allancole** [comment]
So it turns out we can’t simply change the “a” to ”an” here since the plan name is dynamic meaning it could also be “Business” or “Personal” depending on the customer. To make this change, we’d need to write some kind of regex conditional string for the a/an article which would likely make translation that much more difficult. Instead, I suggest we revise the copy to be more simple and direct. 

I’m considering the following alternate copy:

1. “**My Plan: eCommerce**”
2. “**Your Plan: eCommerce**”
3. “**Your site has the eCommerce Plan**”

I’m leaning toward (1) as similar language is used in JetPack and other products.
