### ISSUE TITLE
Checklist: Redirect plan setup routes to checklist

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#33058]
Plugin setup should be handled by the checklist in a single place:

https://github.com/Automattic/wp-calypso/blob/87e60f3b9ccd22a41787006b1511aab6454de3ad/client/my-sites/checkout/checkout-thank-you/jetpack-plan-details.jsx#L78

https://github.com/Automattic/wp-calypso/blob/87e60f3b9ccd22a41787006b1511aab6454de3ad/client/my-sites/plugins/index.js#L17-L35

This is a legacy dedicated route to install and activate plugins as needed and set the plugin keys. These steps are now covered by the checklist thank you view shown after checkout.

This is the legacy set-up page:

![Screen Shot 2019-06-03 at 16 06 41](https://user-images.githubusercontent.com/841763/58808156-bcb82580-8619-11e9-8f01-95b77955d4f0.png)

**Comment by sirreal** [comment]
I'd propose a simple redirect from the plugin setup route to the checklist route. The problem is that there have been conversations about moving the Jetpack checklist to an independent page. We don't want to add a redirect to the My Plan page, then move the checklist with the install functionality to another route.

**Comment by sirreal** [comment]
Related to the checklist route/redirection question: https://github.com/Automattic/jetpack/pull/12533

**Comment by simison** [comment]
So, these are coming from here in Jetpack:

<img width="1120" alt="Screenshot 2019-06-05 at 14 27 44" src="https://user-images.githubusercontent.com/87168/58954482-fd42ab00-87a1-11e9-8c29-f623794a5d8f.png">

Basically, when you have a plan but plugins (Akismet / VaultPress) are not set up.

Those then bring to URLs like `https://wordpress.com/plugins/setup/:site?only=FEATURE` where feature can be: `vaultpress`, `backups`, `scan`, `akismet`.

So we'll for sure want to consolidate all this to the checklist, but we cannot do that yet:

- "Thank you" modal is driving installing these plugins in the checklist, and that flow would be weird so the "installer" needs to move out from the "thank you" page into the checklist itself.
- The installer needs to become smarter as in what it should install. If the customer has indicated to set up only Akismet, we shouldn't start installing VaultPress. They might've disabled it by purpose. We should still nudge them to install VaultPress, or at least skip the task (so that we get that data) — they've paid for VaultPress after all.

Once the checklist is smarter, we can redirect all these routes to the checklist.

Convo p1559732695013400-slack-luna

I checked that these "set up" buttons in Jetpack have tracking.

**Comment by simison** [comment]
:wave: FYI @joanrho — TL;DR: "set up" buttons in Jetpack dash bring customer to an old plugin setup flow in Calypso that we're aiming to consolidate to the new Jetpack checklist instead.

**Comment by joanrho** [comment]
Thanks for the heads up, @simison! My team is currently working on a project that fixes up the Jetpack Dashboard At a Glance page.

@MichaelArestad @crunnells Please see Mikael's comment above and the thread for your work on the At a Glance Tuneup.

**Comment by jeffgolenski** [comment]
I'm trying to get into the mindset of the customer who has a paid plan, but not VP or akismet set up, and see's these. It's a strange flow to fall into. Could we get some data on how many folks end up having a plan but without these plugins installed?

I'm on the border here - I don't want to drag them into the checklist since they may be expecting to end back up in wp-admin where they started. @joanrho @MichaelArestad @crunnells @fditrapani - what if, after we finish setting up those plugins we do one of two things?
1) send them back to wp-admin where they started (wp-admin will soon have the checklist CTA)
2) Literally give them a choice to return to wp-admin or proceed to the checklist so we can help them get the most out of jetpack?

**Comment by MichaelArestad** [comment]
I would go with #2, Jeff.

As for those CTA Setup links, Chris and I figured out how to modify those today. We can change them to link to an appropriate place (and maybe make them secondary buttons). We could also remove them in favor of another approach.

**Comment by joanrho** [comment]
Agree with Michael's suggestion above. Then, they can revisit the checklist CTA in wp-admin at their convenience.

**Comment by simison** [comment]
>Literally give them a choice to return to wp-admin or proceed to the checklist so we can help them get the most out of jetpack?

I agree this is the best short term change.

As for longer term solution, we can bring them to the checklist and show "set up" button in the checklist that then sets up the missing plugin for them. While at it, they get the chance to set up rest of their features too if not already done, and they'd also have easy way back to wp-admin.

We could then stop maintaining multiple flows doing the same thing and just concentrate on the checklist.

I think we need some technical changes in checklist as for how we check plugin installation status and how we even install the plugins. Now it all happens in the "thank you" step and not in the checklist itself.
