### ISSUE TITLE
Themes: Uploads page shows bogus error

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33069]
(Similar to #33063 for Plugins.) On the Upload Themes page, when you don't yet have a Business plan, the upgrade banner is shown, like this:

<img width="756" alt="Screen Shot 2019-05-15 at 2 55 28 PM" src="https://user-images.githubusercontent.com/2124984/57801417-a6593100-7721-11e9-96a9-de78267f4ff1.png">

* The copy mentions "Also get unlimited themes", when we're already on the Themes page, which is redundant.
* The overall design makes this banner look very small. It doesn't look like a clear call to action to upgrade; more like a suggestion.
* The "error" that doesn't look like an error is discouraging and doesn't provide much help. A clearer call to action should be provided. If the goal is to drive people to the Business plan from this page, we shouldn't distract them with extraneous messaging.

Found during this walkthrough by @ianstewart https://cloudup.com/iLSE_iIViNf

**Comment by ranh** [comment]
"The errors above [...]" is actually related to Atomic sites, here's an example:

![image](https://user-images.githubusercontent.com/426518/57901969-d6aee580-786f-11e9-9d00-8509d9f3fcc7.png)

Even though it badly needs a rewrite, in this case it looks like it just shouldn't be showing up at all.

**Comment by Aurorum** [comment]
Related: #32011

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
The errors shown above do not seem to be in use anymore, so this is likely resolved. Ex:

<img width="1207" alt="Screenshot 2023-09-14 at 3 33 32 PM" src="https://github.com/Automattic/wp-calypso/assets/27249804/ca10206d-12a6-4846-a23d-0aa86e31ee60">
