### ISSUE TITLE
Gutenframe: Sites with denied plugins can still load Gutenframe [5]

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#33074]
Gutenframe has a list of denied plugins; plugins which, if active on a site, should force the redirect fallback.

The list of active plugins for a site in managed by Jetpack Sync, and seems to take about ~10 seconds to happen. If the sync occurs properly, and a user somehow initiates a page load with fresh data from the `/sites` endpoint, all is well. However, activating a denied plugin with stale sites data and reloading the block editor (or reloading the block editor before sync has occurred) can bypass the forced fallback.

This could be mitigated by having Calypso (or an endpoint serving Calypso) poll the Jetpack site directly before deciding on Gutenframe eligibility.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
