### ISSUE TITLE
Themes: Upgrade banner doesn't point to the Business Plan section of the Plans page

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33071]
Similar to #33064

When you visit the Themes page and try to upload a theme without a Business plan:

<img width="756" alt="Screen Shot 2019-05-15 at 2 55 28 PM" src="https://user-images.githubusercontent.com/2124984/57802677-837c4c00-7724-11e9-92a2-ae3fc09adf27.png">

The Business Plan upgrade nudge brings you to the Blogs and Personal Sites section of the Plans page:

<img width="1030" alt="Screen Shot 2019-05-15 at 12 35 24 PM" src="https://user-images.githubusercontent.com/2124984/57792842-f75f2a00-770d-11e9-8ecb-6d308dccb98d.png">

At which point it's easy to get lost/confused and possibly purchase the wrong plan. Any nudges for the Business plan should at least point to this section of the Plans page:

<img width="1027" alt="Screen Shot 2019-05-15 at 12 36 53 PM" src="https://user-images.githubusercontent.com/2124984/57792937-2b3a4f80-770e-11e9-871f-e1fe5feb81f2.png">

That said, we know the user needs to get the Business plan if they want to upload a third-party theme, so it's distracting to be dropped into a Plans page, where you can get lost looking through the options. 

Would it be too confusing to take them directly to Checkout from the upgrade banner? Or perhaps to an interstitial that better explains the Business plan offerings only? This could use some design thinking.

**Comment by mendezcode** [comment]
I think directing to the checkout page directly may be a bit too much. My thoughts align best with redirecting to an interesticial or a marketing page page that showcases information about the business theme.

Redirecting to the plans page may confuse users a little, since they may not be 100% sure on which plan they should purchase, even highlighting the Business plan as _suggested_.

We don't currently have a page that would serve as an interstitial or a marketing page.

We do have https://wordpress.com/business/ – but that may involve getting users outside Calypso.

I think in this case a modal would work with a CTA button to go to the checkout page?

**Comment by sixhours** [comment]
I think at a bare minimum, we need to ensure they land on the Business section of the current Plans page, shown here:

https://user-images.githubusercontent.com/2124984/57792937-2b3a4f80-770e-11e9-871f-e1fe5feb81f2.png

Let's make that the goal of this ticket.
