### ISSUE TITLE
Importer Navigation and New Sidebar Usability: Remove Import and Export Sections from General

### ISSUE THREAD

**Issue by dezzie** [Automattic/wp-calypso#33104]
This is a sub-story of: https://github.com/Automattic/wp-calypso/issues/31169
A prerequisite of: https://github.com/Automattic/wp-calypso/issues/33105
There are sub-stories for each of the goals for better QA. Either me or @shaunandrews can design review and approve all of them.

@obi2020 or @ranh I'm tagging you for copy review, but no pressure.

**Context**
I ran a usability test with a participant using one of the importers, and found that the new sidebar makes that existing issue worse, especially if the user starts from signup.

**Goal**
To avoid navigation confusion for users completing an import. We are not telling these new users where in the product they are working. If they leave the import flow, the sidebar is not indicating where they are going, and they end up lost.

**Changes needed**
- [ ] **Remove Import and Export** sections out of **Manage>Settings>General** in the new sidebar. 
- [ ] **Add Export** section to **Tools>** in the new sidebar.
- [ ] **Remove the cake nav** from Import and Export sections that is no longer needed.

---
Here's what the new Settings sidebar section should be like:
<img width="1440" alt="o Import and Export" src="https://user-images.githubusercontent.com/1301932/57885841-77aa8b80-77f1-11e9-8b9d-6ee5d845a152.png">

---
Here is what the new Tools>Export sidebar section should look like after moving Export into it, and removing the cake nav now that it is no longer needed:
- [ ] the two buttons can be bumped down to an `is-secondary` class.
- [ ] Type size for section title is 24px and copy underneath is 14px
<img width="1440" alt="1440 - Tools _ Export" src="https://user-images.githubusercontent.com/1301932/57886073-04ede000-77f2-11e9-97fd-7a854e8cfad0.png">

---
Here is what the updated Import sidebar section should look like after removing the cake nav that is no longer needed:
<img width="1440" alt="Sidebar Expanded" src="https://user-images.githubusercontent.com/1301932/57886164-34045180-77f2-11e9-9b3b-f50e96e311d0.png">

**Comment by ranh** [comment]
What copy feedback are you looking for specifically?

**Comment by dezzie** [comment]
@ranh on both the new Import and Export sections, the title of the section and the line of copy beneath it.

### Export your content
With WordPress, you own your content.
(I don't think this one is good.)

### Import your content
Import your content from another site. Learn more about what we currently support in our [documentation]().
(This one is ok but it could be better.)

**Comment by obi2020** [comment]
@dezzie 

I love that you've found a place to message this value prop! And IMO the copy isn't bad. Some explorations below. Though they may violate the shorter is better rule, I'm riffing on emphasizing the ownership concept.

- You own the content you publish on WordPress.com.
- You own the content you publish with WordPress.com.
- Your content on WordPress.com is always yours.
- Your content on WordPress is your content anywhere.

Not sure if there are existing brand standards for using WordPress vs. WordPress.com in the UI. I would preference including the .com here to solidify .com as a service (in comparison to Wix et al)

***

I also have a few other questions about that screen. My understanding is that `export` will produce an xml file of some sort, right (it's been awhile since I've done this...)? Whereas for the media library, `download` seems to imply you'll download the actual files. Is that correct? If so, let's make the header and the button match. e.g. `Download media library`

**Comment by obi2020** [comment]
For the Import screen, is this the docs page you're linking to? https://en.support.wordpress.com/import/ (link above just comes back to this issue).

In any case, I would edit the subhead so that the linked text is more descriptive:

- Bring content hosted elsewhere over to WordPress.com. Learn about [importing content from another site](url).
- Create your WordPress.com site with content from another site. [Find out what we currently support](url).
- Import your content from these sites and others. [Learn more about importing content](url).

**Comment by dezzie** [comment]
Based on @obi2020's feedback I think we should go with the copy on these mockups as the finalized versions:

**Import**
<img width="1440" alt="1440 - Tools _ Export_v2" src="https://user-images.githubusercontent.com/1301932/58128445-478e2e80-7bdd-11e9-8b6c-cd15719d50f6.png">

**Export**
<img width="1440" alt="Sidebar Expanded" src="https://user-images.githubusercontent.com/1301932/58128461-4eb53c80-7bdd-11e9-9938-50f19c986e83.png">

**Comment by creativecoder** [comment]
Draft PR at https://github.com/Automattic/wp-calypso/pull/33181

**Comment by creativecoder** [comment]
Completed in #33181
