### ISSUE TITLE
Full Site Editing: Widget Support or Remove Customizer Functionality?

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33113]
Twenty Nineteen supports a footer widget area. Should we disable this in the customizer, or add a widget area in our "footer" for the Full Site Editor?

<img width="1696" alt="Screen Shot 2019-05-16 at 4 37 05 PM" src="https://user-images.githubusercontent.com/1270189/57893735-e63f1780-77f8-11e9-873d-709aa193354a.png">

cc @apeatling @alexislloyd @mtias

**Comment by apeatling** [comment]
I think since Jetpack worked to convert the most used widgets to blocks, we should not include a widget area in the theme, and remove it from the customizer for this theme only (if they switch to an older theme it should come back).

Looking at block searches will help to understand if we are missing widget coverage.

**Comment by gwwar** [comment]
> we should not include a widget area in the theme

Thanks Andy, I'll go ahead and close this question then.
