### ISSUE TITLE
User Mentions: Cannot mention viewers on a private site

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#33132]
I am actually not sure if this is expected behavior, but after hearing from a user who was confused about why they can't mention their viewers, I wanted to drop a report here just in case. 

#### Steps to reproduce
1. Test on a WP.com simple site, set to private, with at least one viewer
2. Try to mention the viewer in a comment by typing @ and their username, and nothing will pop up

#### What I expected
To be able to mention the viewer

#### Context / Source
User report in 12853752-hc

**Comment by arunsathiya** [comment]
I don't think we ever had mentions on Jetpack comments - https://jetpack.com/support/comments/ (which is in use on WordPress.com)

I tested on a WordPress.com Premium plan site, and I am not able to mention. 

I would probably ask the user where they read about mentions on WordPress (I see they have mentioned `implemented since WP Ver. 5.1.`)

**Comment by lakellie** [comment]
Hi @arunsathiya!
User Mentions are a feature on WP.com and they are described here: https://en.support.wordpress.com/user-mentions/

I have tested this on my own simple site set to private like the user's site was, and can mention users successfully, as long as they are in a role like administrator, editor, etc.

**Comment by arunsathiya** [comment]
Wow, that is a TIL for me! 😄

**Comment by arunsathiya** [comment]
Tested again, I confirm that this is still an issue.

**Comment by eduardozulian** [comment]
I just tested this on a private site and it worked for me. @arunsathiya @lakellie, can you try again and see if it's working now?

**Comment by autumnfjeld** [comment]
Blogger Pod: I tested on a private site and I could not mention the viewer (eg use @username in a post) on my private site.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
I'd recommend reporting this anew if anyone runs into it again - the history here hasn't offered enough detail to replicate consistently, so a new report with updated details and steps to reproduce would be more effective. Thanks!
