### ISSUE TITLE
Full Site Editing: deploy the plugin to WP.com [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#33163]
We need to find a way to run the plugin code on Dotcom behind something that would simulate a feature flag and enable it only on some sites for initial testing.

Previous efforts to do this ran into some issues because of the loading order and `blog_sticker` checks (see D28074-code for more info).

**Comment by Copons** [comment]
I'm wondering if a Calypsoify approach would work for us: adding a query param that saves the option into a cookie until explicitly removed.
E.g. opening the dashboard via `proxied-sandbox.wordpress.com/wp-admin/?full_site_editing=1` (or `0` to disable it).

Folks would need to clearly opt-in, so that they wouldn't be confused of what they see.
At the same time, they wouldn't need the hassle of adding their site ID into a whitelist.

**Comment by vindl** [comment]
Nice idea @copons! Yeah, I think this might work out.

**Comment by vindl** [comment]
Resolved in D28892-code.
