### ISSUE TITLE
Full Site Editing: Create multiple bundles [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33241]
As @Copons noted, it may make sense to update the webpack config to create multiple entries and bundles. For example splitting out front end styling/JS vs editor styling.

**Comment by getdave** [comment]
I had a go at adding multiple `entry` points to the webpack config today. This bit works well but (due to the way Webpack works) it spits out the build in a single `output` directory. 

It's probably possible to make the `output` based on the `entry` but this wasn't immediately obvious to me today.

Longer term it would be nice if we had a single unified build command.

**Comment by apeatling** [comment]
@gwwar Is this one still relevant?

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core FSE.
