### ISSUE TITLE
Non US / Canada based Business plan customers who set up a store are dumped in wp-admin with no explanation

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33261]
#### Steps to reproduce
1. Sign up for a Business plan
2. Upload a plugin to go Atomic
3. Click "Store" menu item to initiate Store on-boarding
4. Input a non US / Canada address in the first on-boarding step
5. Get dumped unexpectedly in wp-admin

#### What I expected
I expected to stay in Calypso. I believe what is happening here is that we're "migrating" Business plan customers over to eCommerce plan functionality based on geography, since Store only supports US / Canada stores at the moment.

#### What happened instead
I was sent to wp-admin with no explanation as to why.

I understand why we send people to wp-admin, but I think there should be an intermediary step where we inform the customer why we're doing so. It could be based on the screen you see if you try to access Store management through Calypso if the store address isn't in the US or Canada:

![1](https://cldup.com/vTFGPbdEMG-3000x3000.png)

**Comment by jwold** [comment]
Just replicated these steps and wanted to add a note. 

When I follow the final step Jay outlined, I get dumped to WP-Admin, as he said. When I press the back button on my browser I THEN see the graphic he attached above. I checked with Jay and he validated that the expectation is to show that graphic before sending me off.

**Comment by jwold** [comment]
Howdy! I'm at bottle pickup for the All Design Meetup and chose this one.

What's happening right now is if you enter a **non** USA/CA address, enter Spain for instance, you get shot over to the WP-Admin unexpectedly.

However, if you do enter a USA/CA address you get a friendly message letting you know you're about to be sent to WP-Admin.

What we'd like to do is have that friendly intermediary message show for all customers, regardless of country. 

With the help of @scruffian (thanks!) help we found the file and code, and commented it out so that it now auto shoots me over to WP-Admin, so that all customers will see the intermediary notice.

Here's the code that is commenting this out: https://d.pr/i/QQUyw2
And here's the PR where this code was originally added about a year ago added: https://github.com/Automattic/wp-calypso/pull/21409

Here's a video showing me running through this on Local, and everything is working as expected, where a Spain address sees the intermediary notice: https://v.usetapes.com/yaBg6sIQkM

**The question I have is:**
Do we need to keep this commented out code for any reason? It seems that all customers should be shown this notice (screen: https://d.pr/i/ggzkl4), and not just USA/CA customers. 

Thanks!

**Comment by timmyc** [comment]
> Do we need to keep this commented out code for any reason?

Nope, if the desired outcome is as you have outlined above, removing that code would do the trick and have no adverse affects.

**Comment by jwold** [comment]
I've created a PR for this, just not sure how to connect it to the issue yet.

**Comment by timmyc** [comment]
> I've created a PR for this, just not sure how to connect it to the issue yet.

In the PR description, just add `Fixes #33261` and when the PR is merged it will close out this issue. Looks like the PR has an approval @jwold so let me know if you need some help merging/deploying that.

**Comment by jwold** [comment]
Looks like this got resolved. Thank you for moving this forward!
