### ISSUE TITLE
There are lots of primary actions on the Store on-boarding task list

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33262]
Ideally there should only be a single primary action per page. Instead we see this, which is kind of overwhelming:

![1](https://cldup.com/kaUvyQzUVX-3000x3000.png)

Possible solutions: 

Short term: Make only the "next" task primary.

Long term: Employ a pattern like [this](https://cldup.com/uhDh7Wxz0t-3000x3000.png) which is Muriel friendly.

**Comment by MichaelArestad** [comment]
I created two pull requests to address this. Neither is the ideal solution, but are an improvement.

The first is quite nuclear: https://github.com/Automattic/wp-calypso/pull/33820

It removes all the primary buttons on any checklist. This could probably resolve this issue across the board for the Checklist pattern. I think another non-bottle issues could be created to make the checklist function in a linear fashion where only the next suggested step's button is primary.

The second is more surgical: https://github.com/Automattic/wp-calypso/pull/33825

It just changes the buttons on the Store list to be secondary instead of primary.

@jameskoster @cburton4 What do you think?
