### ISSUE TITLE
Editor: Media: gallery order is wrong in the edit details view

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#333]
When I drag several images in order into the media library modal, the numbering is correct but the image order is all jumbled:

<img width="1280" alt="e6c5d6da-862f-11e5-90b6-caae789b3499" src="https://cloud.githubusercontent.com/assets/1119271/11311464/09342d62-8f9e-11e5-954f-2bbf058122ee.png">
<sup>Tested with Chrome 46.0.2490.80 on Mac OS X 10.10.5</sup>

In the edit details view, the images are displayed in the order they appear in the media library and not in the numbered order:

<img width="1280" alt="369f66da-8630-11e5-8952-5edbf05c8350" src="https://cloud.githubusercontent.com/assets/1119271/11311479/0e6a52f2-8f9e-11e5-89a1-d6b08d769af1.png">
<sup>This image should appear 6th (see screenshot above), but appears first here. Tested with Chrome 46.0.2490.80 on Mac OS X 10.10.5</sup>

Outside of these two views (i.e. in the preview/reorder tabs and in the post after the gallery is inserted), the order goes back to the expected numbered ordering.

**Comment by aduth** [comment]
Upon further investigation, I've found that this is the expected behavior, albeit with some confusion around the shifting of the media order in the list view. The detail view order does not depend on the selected order of the items and is instead ordered by the upload date of the item. You can verify this with existing items by selecting an older item (further down the list), then a newer item, clicking Edit, and observing that the newer item is shown first despite being the second selected item. The shifting of the items in the list view during the upload occurs because the uploads may finish in an order not consistent with the temporary copy. While this may be visually disruptive, the original selected order shown should be preserved as the media items finish uploading.

**Comment by ryanboren** [comment]
I accidentally cancel the modal often. I lose selection order when this happens. Since the images are uploaded in a jumble (instead of in the order they are dropped), I can't easily resurrect selection order like I can in wp-admin, which retains drop order. I reupload entire galleries to Calypso's modal rather than scrutinize images trying to restore the selection order by hand. A very frustrating and anxiety inducing exercise that happens to me with regularity.

Since the gallery flow doesn't offer full-width images during gallery edit, I try to caption using the Edit button from the media lib view so that I can get at bigger images and wider text inputs while captioning. Since images are shown in display (random) order instead of selection/upload order, captioning this way is pain. I've given up trying to caption and order galleries in Calypso.

**Comment by ryanboren** [comment]
PoV: My photos go from iPhone to Google Photos and down to my laptop via Chrome where they are dragged to Calypso from the MacOS finder. Order is retained through that entire flow until the media modal breaks the assumption of order preservation.

**Comment by ryanboren** [comment]
https://test.wordpress.com/2016/02/10/galleries-the-impact-of-upload-ordering-and-cropped-thumbnails-on-captioned-gallery-flow/

**Comment by aduth** [comment]
Possibly related: #1003 . If we upload files in series rather than parallel, we don't run the risk of order being misplaced. This could have an impact on perceived performance (slower?), so we should do some testing to measure the impact before making such a change.

**Comment by ryanboren** [comment]
This behavior is so deeply frustrating and time wasting that I must use WP-admin to make galleries. I'll never use calypso to make galleries if it does not respect order. Respecting order is a hard requirement for me. Core manages it quickly enough.
