### ISSUE TITLE
Jetpack Checklist: Show me how to get to Settings page

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#33313]
I absolutely love that the Checklist takes me to the settings page and shows me where to configure, rather than just doing it behind the scenes. 

However, if this were my first time in Calypso, I would have no idea where to find this settings page again. 

My suggestion: A couple of extra "steps" in between the checklist and settings page where we point at the menu items to click in order to get to the settings. This would train me how to navigate Calypso and not have to rely on the Checklist flow to navigate there.

**Comment by jeffgolenski** [comment]
@dereksmart per our conversation, you make a great points. We've been looking at this UI for so long that we forget for a lot of jetpack customers this is their first foray into wordpress.com and possibly even wordpress as a whole.

What Derek is suggesting is instead of taking the customer directly to the toggle setting without explaining where the toggle setting is, we actually teach them to navigate there. It's an extra step, but I thing a necessary teachable one.

**Comment by jeffgolenski** [comment]
![new guided tour step](https://user-images.githubusercontent.com/214813/58335806-63c5e180-7e10-11e9-8271-0bd26f272d38.jpg)

@dereksmart @simison - I mocked up derek's concept above but with a twist. Instead of making them click "do it" and then show them the sidebar item, my concept will take them right to the task, but then make note of where it resides for future use. then we'll take them right back to the checklist. 

See the image above. It's just inserting one extra guided tour step for each checklist task. The mockup above outlines the downtime monitoring, and plugin auto updates, but I'd like to make this show for each checklist task.

**Comment by jeffgolenski** [comment]
@simison I added this to the backlog in luna projects. We can add it as a checklist polish item!

**Comment by simison** [comment]
We'll need to confirm that we can toggle open closed navigation accordions before showing the popup. That might complicate this otherwise rather straightforward enhancement.
