### ISSUE TITLE
Login: 2FA Authenticator login text is misplaced and is missing styles

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#33338]
#### Steps to reproduce
Not sure how to force the 2FA verification screen to show up, but notice the location of the "Verify with a code instead" link - it's on top against the blue bar, which makes it both hard to spot, and unreadable.

![image](https://user-images.githubusercontent.com/4550351/58389348-2316d400-806d-11e9-83f3-a48611a31ac2.png)

#### What I expected
For the link to be blue and to be placed within the content, below the "Or, type in the verification code..." paragraph.

#dogfooding, #manual-testing, #automated-testing

**Comment by alaczek** [comment]
Also reported in 8146-wpcom.

**Comment by davidakennedy** [comment]
I started working on this, making it match Muriel button standards. See:

![image](https://user-images.githubusercontent.com/1473618/59531266-5c877600-8e9a-11e9-9146-626b5260ec70.png)

I'm not sure that's the best approach though because it appears this is in an older part of WordPress.com, not updated with our new branding colors. If you click that button, you get another button that's the old style blue. See:

<img width="353" alt="Screen Shot 2019-06-14 at 11 50 39 AM" src="https://user-images.githubusercontent.com/1473618/59531413-b5570e80-8e9a-11e9-93c1-3482220ff1da.png">

What do you all think here? Go Muriel, or go old blue since this may require more work?

**Comment by sixhours** [comment]
I would stick with the older styles, just to fix the most glaring issue, then we can revisit matching Muriel styles in a separate PR.

**Comment by sixhours** [comment]
Tested this on my sandbox and it works! 🚢

**Comment by davidakennedy** [comment]
Thanks for the feedback, @sixhours!

I've updated the patch to use older styles. See:

![Screen Shot 2019-06-21 at 1 06 58 PM](https://user-images.githubusercontent.com/1473618/59939395-ce753780-9425-11e9-85d5-58878553185b.png)

Related diff: D29574-code
Related Trac ticket: 8146-wpcom

**Comment by davidakennedy** [comment]
Fixed in r193413-wpcom
