### ISSUE TITLE
Jetpack Checklist: Plugin autoupdate is done when autoupdates enabled for all plugins 

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#33372]
Plugin autoupdate step in Jetpack checklist states:
> Choose which WordPress plugins you want to keep automatically updated.

But to mark that step as "done" - you will need to enable autoupdates for **all** plugins.  

UPD: It seems that enabling autoupdate for Jetpack marks the step as "done". 

#### Steps to reproduce
1. Connect a Jetpack site and select a free plan
2. Check the wording in `Automatic Plugin Updates` checklist step
3. Click on "Do it" button
4. Enable autoupdates for a few plugins
5. return back to the checklist

#### What I expected

To see `Automatic Plugin Updates` step marked as done 

#### What happened instead

`Automatic Plugin Updates` step remains un-done until autoupdates for all the plugins are enabled. Once the step marked as done - disabling autoupdate for one of the plugins will mark the step as un-done once again. 

Convo p1559027828040000-slack-onboarding-exp

**Comment by simison** [comment]
With https://github.com/Automattic/wp-calypso/pull/33359 this step will look like this:

![image](https://user-images.githubusercontent.com/87168/58535689-381f6e80-81f7-11e9-98b0-61662b1b199e.png)

**Comment by simison** [comment]
Considering copy _"Choose which WordPress plugins you want to keep automatically updated."_ and that we shouldn't stop users from turning the autoupdate toggle on for all their plugins while they're at this screen, how about these changes:

- Suppress _"successfully enabled autoupdates"_ behind the tour badge, since they're basically duplicating the same info; "you succeeded!". If there's an error turning updates on, we shouldn't show "excellent, you're done" but something else instead.

- Change "no thanks." or add another button which makes it easier to jump in and update other plugins, too. Now "No thanks" feels too much like I'm dropping out the checklist work I was in the middle of.

- If customer presses "No thanks", show one more guided tour step to make sure they're not lost:

    <img width="1158" alt="Screenshot 2019-05-29 at 10 17 29" src="https://user-images.githubusercontent.com/87168/58537158-fee8fd80-81fa-11e9-8e7b-0a4ea31e84d9.png">

    We should show this also on other checklist tours when user drops out.

- Bring "update all" button somewhere. It's now hidden behind "edit all" toolbar:

    <img width="399" alt="Screenshot 2019-05-29 at 10 19 50" src="https://user-images.githubusercontent.com/87168/58537378-7880eb80-81fb-11e9-9d50-1b73e4f2145f.png">

    <img width="870" alt="Screenshot 2019-05-29 at 10 20 07" src="https://user-images.githubusercontent.com/87168/58537383-7ae34580-81fb-11e9-8bfb-01ac5df940f4.png">
