### ISSUE TITLE
Gutenberg: Make the wording on scheduled posts page clearer

### ISSUE THREAD

**Issue by suyogyashukla** [Automattic/wp-calypso#33387]
#### Steps to reproduce

1. Schedule a new post which is set to publish in a couple of months. 
2. Go to My Sites -> Site -> Posts -> Scheduled tab.

#### What happens

- It shows that the post is scheduled to publish in a month: https://cld.wthms.co/XGdUR5 even though it's actually a couple of months.

#### What can be made better

It'd be better to rather display the exact time and date the post is scheduled to be published. It's easier for users to know which post is going to be published on what date and time if they have multiple posts scheduled. 

#### Source

#9269349-hc

**Comment by synora** [comment]
I scheduled a post to publish on October 24, 2021, and that exact date is appearing. 
<img width="612" alt="Screen Shot on 2021-07-30 at 14-44-13" src="https://user-images.githubusercontent.com/10015451/127698208-24365357-9ff4-4528-bf7b-6e805f2a3086.png">

It's working for both simple and Atomic sites. I'll close this for now since it appears to be fixed.
