### ISSUE TITLE
Automate phpcs testing

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33425]
I love that we have PHP in Calypso now! :)

To maintain a high level of code quality in our Calypso apps, could you help me get phpcs testing automated? 
We have a `phpcs.xml` file in [`apps/full-site-editing`](https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing), having that run just for commits to that folder would be great (there's a build step for it that we could maybe expand on?). But if you wanted to expand that to all php files in the repo, I'd welcome that too.

I'm not at all familiar with how tooling in wp-calypso is set up and how this could be achieved, so any and all help with it I would appreciate.

/cc @Automattic/team-calypso @simison @dmsnell who seem appropriate to ping?

**Comment by simison** [comment]
I would approach @Automattic/jetpack-crew and @Automattic/poseidon team members since they've been looking into different options in Jetpack repo recently under the "Jetpack DNA" project umbarella. (see paZDrL-g-p2)

Crew has quite extensive experience from PHP linting otherwise, too.

https://github.com/Automattic/jetpack

**Comment by simison** [comment]
Do you have a need to run `phpunit` tests? How does the i18n solution for these files look like?

**Comment by jeherve** [comment]
So far we've tried to stick with what Core does as much as possible in Jetpack, for a few reasons:
- It is familiar for outside and internal contributors alike.
- Those standards are supported, maintained, and will be around as long as WP is around.
- It sets a good example for others in the community looking at building things on top of WordPress.
- We aim to support the current version of WordPress and one version prior, at all times, so sticking to Core standards make things easier.

Our set up can be found here:
https://github.com/Automattic/jetpack/blob/aff96a72f93313f2848b34992ac3d12652ca49a1/.phpcs.xml.dist
https://github.com/Automattic/jetpack/blob/aff96a72f93313f2848b34992ac3d12652ca49a1/composer.json#L15-L24

In addition to this, we run a pre-commit hook on a set of files that we know are clean today:
https://github.com/Automattic/jetpack/blob/aff96a72f93313f2848b34992ac3d12652ca49a1/bin/pre-commit-hook.js

The pre-commit hook relies on `phpcs` to check for errors, `phpcbf` to automatically fix errors when possible, and will block a commit if there are still errors left that can't be automatically fixed.

Here is the whitelist of files where the pre-commit hook is active:
https://github.com/Automattic/jetpack/blob/aff96a72f93313f2848b34992ac3d12652ca49a1/bin/phpcs-whitelist.js

As much as we'd love to just autofix most issues in all files at once and then have the pre-commit hook run on all files, it's just not an option for us right now:
- Modifying so many files at once introduces some file sync issues with WordPress.com.
- Have the pre-commit hook run on all files without fixing the issues first would add a lot of noise to PRs, as commits would start including autofixes that would be unrelated to the changes introduced by each developer.

We've toyed with the idea to have a pre-commit hook that would only run on the modified lines of a commit though. You can read more about it here:
- p1HpG7-6kp-p2
- https://github.com/Automattic/jetpack/pull/11545

In your case, however, since you have a relatively new codebase and no file sync requirements (that I know of), you may be able to fix all issues at once now and then add the pre-commit hook for all files.

Since @simison mentioned the DNA project, I should add that as part of the project, we've considered creating a Composer package that would include a set of standards that we think are valuable for every Jetpack-related project. Work on this is in progress here:
https://github.com/Automattic/jetpack/pull/12547

In an ideal world, you'd be able to benefit from that as well by pulling the standards from the Jetpack package and getting the update as we make them.

I hope this helps a bit. Don't hesitate to reach out if you want to know more!

**Comment by obenland** [comment]
@jeherve This looks really great, I'd love to just take that over wholesale. :) How can we make that happen?

> Do you have a need to run phpunit tests? 

@simison Not as of now, but that might change in the future. I'd love to have something to plug-in unit tests as we add them, at the same time I wouldn't want to delay adding automated phpcs support for it.

> How does the i18n solution for these files look like?

We're in the process of figuring that out, see pxLjZ-5nz-p2. The plugn gets deployed to both wpcom and dotorg, so that adds some complexity :)

**Comment by jeherve** [comment]
> How can we make that happen?

We're still working on that package, but I would recommend that you follow the work on this PR, as we'll make progress on this this week:
https://github.com/Automattic/jetpack/pull/12547

Once the package is available in `master` we'll publish it so anyone will be able to require it in their project via Composer.

**Comment by sirbrillig** [comment]
If it's helpful, [phpcs-changed](https://github.com/sirbrillig/phpcs-changed) allows running phpcs only on changed lines.

**Comment by kwight** [comment]
For now, this has been added to the pre-commit hook in #34286 .

**Comment by obenland** [comment]
Thank you so much @kwight!
