### ISSUE TITLE
Incorrect warning about WPLANG constant when set to empty string

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#33440]
Older WP versions defaulted WPLANG to an empty string. This can be overridden by the WPLANG option, whereas of WPLANG is populated, it overrides the DB.

In our settings page, we warn if WPLANG is set and prevent the user from setting the language, **even if it's set to an empty string.**

The bottom line: If WPLANG is set to an empty string, don't warn the user or prevent them from overriding it.

#### Steps to reproduce
0. With a site whose wp-config contains the line "define('WPLANG', '');"
1. Starting at URL: https://wordpress.com/settings/general/[my-site]
2. Observe warning "The Site Language setting is disabled because your site has the WPLANG constant set."
3. Unable to change language.

#### What I expected

No warning, able to change language.

#### What happened instead

A warning, inability to change language.

#### Screenshot / Video

<img width="855" alt="wplang-error" src="https://user-images.githubusercontent.com/51896/58593747-97de3f80-8220-11e9-8211-e2b65f0a0d8c.png">

**Comment by lancewillett** [comment]
@donpark Could you please take a look at this issue?

**Comment by donpark** [comment]
This error is displayed when `lang_id` value `error_const` is returned from [Jetpack Core API module](https://github.com/Automattic/jetpack/blob/master/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php#L425).

```
case 'lang_id':
	if ( defined( 'WPLANG' ) ) {
		// We can't affect this setting, so warn the client
		$response[ $setting ] = 'error_const';
		break;
	}
```

I'll consult with Jetpack team regarding this issue. Thx.

> Older WP versions defaulted WPLANG to an empty string.

How 'old' are we talking about?

My wpsandbox installation, < 3yrs, had `define( 'WPLANG', '');`.

**Comment by donpark** [comment]
According to response from Jetpack team, Core warns the user but still allows the user to change the language and recommends doing the same in Jetpack/Calypso.
 
Unless there are objections, I will proceed with changes that will: show a warning but still allow changing the site language via the UI in Calypso.

**Comment by donpark** [comment]
I'm reconsidering the warning part because Core displays warning **after** language setting is changed, like this:

<img width="762" alt="screenshot_814" src="https://user-images.githubusercontent.com/127594/62143810-91faee00-b2a5-11e9-8fed-9b5da4840abd.png">

Problem is that Core notice copy assumes `wp-config.php` is the place `WPLANG` is defined, most common case. I now think warning here will more likely confuse the user than help.

**Comment by donpark** [comment]
[Jetpack PR](https://github.com/Automattic/jetpack/pull/13154) addressing this issue is ready for review.

**Comment by donpark** [comment]
This issue is fixed in Jetpack master and tentatively scheduled to be ship with Jetpack 7.7 release. What it does:

1. Uses same logic as Core to determine what language setting, using WPLANG option if set, WPLANG constant if defined, then `en_US` otherwise.
2. This means Calypso language setting will now match wp-admin language setting even in rare corner cases.
3. Unlike Core, no warning message mentioning `define( 'WPLANG', '' )` in wp-config.php` file will be displayed in Calypso to a) avoid confusing users unnecessarily, b) avoid making potentially wrong assumptions since the constant could be defined anywhere, and c) avoid hassle of changing format of response passing through several layers to support warnings.
 
Thanks to everyone for making this happen.
