### ISSUE TITLE
(1P) FSE: Update size of template selector modal

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33494]
Based on the thread in p1559239403099300-slack-ajax, adjust modal size to something smaller than full screen.

**Comment by apeatling** [comment]
For me the issue is both the size and the contrast, something with more space around it, and with a darker background behind makes it clearer:

<img width="1509" alt="Screen Shot 2019-06-03 at 10 28 39 AM" src="https://user-images.githubusercontent.com/1464705/58821693-78616100-85ea-11e9-8cf2-465325e09e43.png">

I would also remove the animation that slides and fades in the modal when the page first loads. That split second of seeing the editor behind the modal makes me feel more frustrated. More like a popup getting in the way, and less like an important decision point integrated with the editor.

**Comment by getdave** [comment]
@iamtakashi Can you confirm you’re happy with the visual approach suggested here for the Modal?

**Comment by iamtakashi** [comment]
@getdave Yes, I like the darker backdrop that helps focus on the modal and smaller width like the media modal in Calypso (75%).
