### ISSUE TITLE
Hide masterbar parameter

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#3353]
Currently there is a combination of parameters we can add to hide the masterbar in certain scenarios, e.g. https://wordpress.com/themes/escutcheon?preview=true&iframe=true

This is great for the mobile app because we don't want the user to navigate within the webview. 
Can we add a `hide_masterbar=true` parameter as a catch-all?

cc @lancewillett

**Comment by lancewillett** [comment]
I'll take a look at this.

**Comment by lancewillett** [comment]
Change made on the WP.com side with r131220-wpcom

You should be able to use `hide_masterbar=true` now.

**Comment by lancewillett** [comment]
For example: https://test.wordpress.com/?hide_masterbar=true hides the toolbar.

**Comment by kwonye** [comment]
Thanks so much @lancewillett! Interestingly I am unable to get that parameter to work here:

https://wordpress.com/purchases?hide_masterbar=true

Seems to be a different masterbar (calypso). Is that possible to hide? Unfortunately my javascript is not up-to-par, but my initial guess is that we'll have to modify `logged-in.jsx` and `logged-out.jsx`s' `render()`?

**Comment by lancewillett** [comment]
Ah, yes — I didn't change anything in Calypso yet. Looking.

**Comment by lancewillett** [comment]
@kwonye I think the place to put any new logic would be in the `renderMasterbar` method here in client/layout/index.jsx: https://github.com/Automattic/wp-calypso/blob/042f6f8b376f9996291626f56d7f2013e45b22ee/client/layout/index.jsx#L96

**Comment by kwonye** [comment]
> @kwonye I think the place to put any new logic would be in the renderMasterbar method here in client/layout/index.jsx: https://github.com/Automattic/wp-calypso/blob/042f6f8b376f9996291626f56d7f2013e45b22ee/client/layout/index.jsx#L96

Totally trust your judgement. :+1: 

Also, if there is a better way to hide the masterbar than to always pass a parameter, that'd be great. Is there a way to set a state where it will always be hidden?

**Comment by lancewillett** [comment]
I'm not sure about the state question — that would make more sense that a query string if it needs to persist across a session.

Can you describe a bit more your use case for the iOS app webviews? What is the user flow and why should they not see the mastebar?

**Comment by lancewillett** [comment]
I'm going to defer to Calypso Core folks for a more framework-centric solution rather than a hack. :)

**Comment by kwonye** [comment]
> Can you describe a bit more your use case for the iOS app webviews? What is the user flow and why should they not see the masterbar?

For an upcoming feature, delete site, we direct users to a webview to cancel their purchases. When the webview opens up, we want to make sure the user doesn't have the ability to create a new post, check notifications, etc inside the webview as that is available within the app.

![screenshot_20160217-142902](https://cloud.githubusercontent.com/assets/1158819/13127265/46ae168c-d583-11e5-9f10-df34790a6590.png)
![screenshot_20160217-142911](https://cloud.githubusercontent.com/assets/1158819/13127266/46d085dc-d583-11e5-99d1-6ae5bc426742.png)

**Comment by lancewillett** [comment]
Ping @mtias for help on how to make a persistent setting in the app state for hiding the masterbar across a session.

**Comment by mtias** [comment]
I am not sure about this, there are ways (and there could be more in the future) to navigate even without the masterbar. The `← Me: Purchases` is already alien to the mobile app but core calypso navigation. (You can log out from there, for instance.) There's potentially numerous changes that could indirectly affect the mobile apps because people won't assume something is used in a windowed form when they iterate on it and it makes things more fragile.

I assume this is temporary for the mobile apps as well. Could you maybe consider building a separate route in Calypso that is specific for that purpose and just renders what you are interested in? I'd rather not add the ability to hide the masterbar for this purpose.

**Comment by folletto** [comment]
I think @mtias raises a valid point here. In themes / front-end / demo sites we can use a flag since it's literally just a matter of removing the masterbar and action bar (and even there, we should really consolidate, I recall we're using three different parameters), but in Calypso should be a specific route done for mobile. There are too many things that happen in Calypso navigation at mobile sizes. :)

**Comment by kwonye** [comment]
> but in Calypso should be a specific route done for mobile
>  Could you maybe consider building a separate route in Calypso that is specific for that purpose and just renders what you are interested in?

Could you both (@mtias and @folletto) elaborate what you mean by this please? I don't follow.

**Comment by mtias** [comment]
@kwonye I mean having a route `/purchases-mobile` that renders the components you need from `/purchases` but nothing more, so you don't get any odd interactions, it's function is explicit instead of implicit in a querystring to hide the masterbar.

**Comment by lancewillett** [comment]
I'm closing this one — feel free to create new issues if new bugs or tasks are needed to make this work better.
