### ISSUE TITLE
Toolbar Edit Page link causes User ID mismatch error

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#33574]
#### Steps to reproduce
1. Starting at URL: On a WordPress.com AT site (view p9F6qB-3jU for specific example)
2. Create a user from wp-admin
3. Log in as this user and click the Edit Page link in the top toolbar

![img](https://cld.wthms.co/fz4w9o+)

#### What I expected

Should be directed to `https://example.com/wp-admin/post.php?post=XX&action=edit`

#### What happened instead

Directed to `https://wordpress.com/page/example.com/XX`

Which results in a `User ID mismatch` error.

![img](https://cld.wthms.co/WLmq9F+)

#### Browser / OS version

Firefox/Chrome, I don't think it's OS related.

#### Context / Source

This was reported in: 

Ticket: 13024031-hc
Follow up: 2061987-zen

I was unable to replicate this on my V2 AT test site but was on the reported site, full details:

p9F6qB-3jU

**Comment by jamiepalatnik** [comment]
It looks like this issue was also reported here: 13077664-hc

**Comment by kriskarkoski** [comment]
This issue/error happens when a user is logged into a different account on the Atomic site's WP Admin that does not match their WordPress.com account. The fix is to connect Jetpack to a matching account on WP Admin if not already, have the user log out of both the Atomic site and WordPress.com (or force log them out), then login again to WP.com and it should work without error. Clearing cookies and logging in fresh to WP.com also works as this clears out the incorrect login on WP Admin.

**Comment by lancewillett** [comment]
Thanks for the notes, Kris.
