### ISSUE TITLE
Editor: TinyMCE pinned toolbar improvements

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#337]
There are some potential improvements to be made regarding the inner workings of how the tinyMCE toolbar transitions from being static to becoming pinned at the top of the page.

* [ ] Move pinned func. to a TinyMCE plugin
* [ ] Throttle `window.onscroll`
* [ ] Parameterize/calculate the top offsets (46 = master bar height, 139 = master bar height + toolbar height)

raised by aduth adambbecker

**Comment by jeremeylduvall** [comment]
When I scroll down on a long post, the tinyMCE toolbar sticks to the top of the window as it should. But, when I scroll up slowly, instead of stopping in the normal spot, it continues to stick to the top of the page when it shouldn't. Wonder if we could address that with the items above?

![scrolling](https://cloud.githubusercontent.com/assets/7240478/11426533/10d1b410-941a-11e5-967e-b7b9ed5e22df.gif)

**Comment by kriskarkoski** [comment]
There's an issue specifically for this case that hasn't been moved over yet
and I believe it's specific to having a featured image set. When it's moved
I'll try to remember to cross-link it here.
