### ISSUE TITLE
Menus: Cannot undo menu deletion

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#3379]
To reproduce
* Delete a menu
* In the notice that appears, click 'Undo'
* You'll get a JS error in your console, complaining that `close is not a function`
* The menu is _not_ undeleted!

The relevant line is https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/menus/menu-delete-button.jsx#L33. Note that this code hasn't changed in quite a while, so maybe something's funky with `notices` (not?) passing `closeFunction` as the second argument to `onClick` [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/menus/menu-delete-button.jsx#L52) as it's [supposed to](https://github.com/Automattic/wp-calypso/tree/master/client/notices#onclick)?

Pinging @artpi since #1105 looks kinda related... :-)

**Comment by ockham** [comment]
This is due to [`handleClick` having been deleted](https://github.com/Automattic/wp-calypso/commit/17f3d3be3b98643bcf30cbcdd27dd253669db7f5#diff-3dcd0c856d0202a35a21c64549d1c9b5L41).

**Comment by artpi** [comment]
> This is due to handleClick having been deleted.

Well, not exactly :) This whole component got removed as a part of an effort to move us to redux notices.
But it is perfectly true, that I forgot to pass second argument to onClick and it is my fault :/

We should continue on moving notices to redux, because the `notices/index` is ugly and we could get rid of that very soon
