### ISSUE TITLE
No clear return to data consent options

### ISSUE THREAD

**Issue by obi2020** [Automattic/wp-calypso#33828]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Create an account or log in
3. Register or transfer a domain name
4. Open email titled "Set your data use consent preferences" and click the provided link
![Image of consent email](https://cldup.com/T8Fs2OkzME-3000x3000.png)
5. Land at this URL and read that consent is optional and can be changed. https://validate.sawbuck.com/consent/74a18021-5225-477f-9ce7-e8ef99120253

#### What I expected
The copy there says you can change your settings, so I expect to be able to navigate to this page again in the future. 

#### What happened instead
There's nothing showing or instructing me on how to get back to to change these settings

#### Browser / OS version
Chrome / macOS 10.14.5 

#### Screenshot / Video
![Image of consent page1](https://cldup.com/GMyDQAJvUW-3000x3000.png)

![Image of consent page2](https://cldup.com/1BqNQOxs8n-3000x3000.png)

#### Context / Source
With the increase in interest in data privacy / ownership more user might be comforted by knowing this is option. However, if we say they have choice, we need to make sure that choice is readily actionable. 

#manual-testing

**Comment by klimeryk** [comment]
I understand your concern, but unfortunately it's not as simple as that. These consent management options are a result of a hastily implemented GDPR procedures by ICANN. And even more hastily implemented (and inconsistently) by our domain partners. As a result, they don't exactly do what you'd expect - data is not shared publicly regardless of what you choose. The link in that email hopefully explains it in more detail.

But getting back to the root issue here - you can get back to these options at any time by re-requesting this email from Calypso:
<img width="748" alt="Screenshot 2019-06-12 at 10 41 59" src="https://user-images.githubusercontent.com/3392497/59345221-337eae00-8cff-11e9-88d1-457fc446ed74.png">

And as mentioned above, we don't advertise it more, because it's a confusing requirement by ICANN that does not benefit (or improve) users' privacy.

While the domain management definitely needs a lot of love, would be great to sync up with @nodeone and his efforts (puPv3-7Qx-p2) for a more holistic approach.
