### ISSUE TITLE
Recurring payments page doesn't provide actionable help

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#33827]
Steps to reproduce:
1. From any site, go to "Earn" in navbar.
2. That's all.

The current copy on the recurring payments page possibly causes more confusion that help. It links out to a support page which provides instructions but is a heavy-handed way to understand how to use the feature.

![image](https://user-images.githubusercontent.com/12596797/59312172-f95ecf00-8c60-11e9-86f4-bc92ca3ad26d.png)

**Comment by obi2020** [comment]
@mikeshelton1503 I'd like to tackle this and noticed another mini bottle within. I believe that icon to the far right in the grey banner implies that the link should open in a new window, but it current opens in the same window.

**Comment by obi2020** [comment]
Also curious about the use of that grey banner. Why is the prompt to "learn more" implemented that why vs. and inline link, as we see in other place in the UI. Any reason per Muriel? cc @drw158

**Comment by drw158** [comment]
This seems like an inappropriate use of the Notice component (the black banner). Because the card above it ("about recurring payments") serves as more information to learn about recurring payments, any sort of link to further reading should be done in there. I would just remove the Notice, and add a read more link inline with the paragraph. As to whether or not it should open a new window, I'm not sure. I thought in the past, we'd open the support site in a separate tab.

**Comment by obi2020** [comment]
An exploration
<img width="616" alt="Screen Shot 2019-06-13 at 4 44 37 PM" src="https://user-images.githubusercontent.com/3373750/59474136-8db06980-8dfa-11e9-94cc-e9de8af7299c.png">

Copy could still be better, but tried to do a few things:

- Make the subheader more useful, instead of just repeating the feature name
- Make the card copy more direct to signal value to user
- Remove Notice component, per Dave's advice and moved link into card body. 

Other consideration "Recurring Payments" isn't the most graceful feature name. I'm not a fan of naming features in general, but if we do in this case, something related to Subscription would be preferable.

**Comment by Aurorum** [comment]
I think #34782 would fix this

**Comment by artpi** [comment]
Correct, this is much different now
