### ISSUE TITLE
Older versions of Safari can not login to WordPress.com

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#34003]
#### Steps to reproduce
1. Using an iOS device with iOS 9 or earlier
2. Visit https://wordpress.com/log-in
3. Try to login

Another scenario is for people who are already logged in to WordPress.com if they click the Write button on the admin bar at the top you will be redirected to https://wordpress.com/post and the page will be blank and not load.

#### What I expected
I would expect for the login to work as expected.

#### What happened instead
Either the login page is blank, or if the page loads if you click on the input field it doesn't allow you to input anything

#### Browser / OS version
Safari iPhone 5 iOS 9.0.2
Safari iPad iOS 9.3.5 

#### Screenshot / Video
![Image from iOS (7)](https://user-images.githubusercontent.com/1326294/59537428-f2d48f80-8ecc-11e9-97e1-66918da1ed95.jpg)

![image](https://user-images.githubusercontent.com/1326294/59537510-2b746900-8ecd-11e9-8f44-cf908cc2c1a3.png)

#### Context / Source
This started as a user report #2107185-zd but also tested in Browserstack using iOS 8 and 9 and had similar results. Customer says this just started last week.
I've run across one other similar user report but I can't find it anymore.

#user-report

**Comment by sandymcfadden** [comment]
Another report here 2108616-zd using an iPad with iOS 9.3.5

**Comment by sandymcfadden** [comment]
Have another report here and it seems it is not just Mobile devices. Older versions of Desktop Safari as well can not login. 
Using Safari 9 on Mac OS X 10.11.6 also will not load the login form. 
51689-hc

**Comment by sgomes** [comment]
@sandymcfadden #33771 should have fixed this issue. Let us know if anything's still breaking!

**Comment by sandymcfadden** [comment]
@sgomes Thank you! I've followed up with the people who reported and will let you know when I hear back.

**Comment by sandymcfadden** [comment]
Heard back from two of the three people and they are working well. I'm going to close this off.

**Comment by gracie** [comment]
It looks like someone is still being impacted by this bug in #108616-zen. Can we take a look?

**Comment by lancewillett** [comment]
Next time you run into this, could you please open the Safari developer tools and try to capture network and JavaScript errors, please? That might show the difference between a 404 (like the old /post URL) versus a page-blocking JS issue.

We might be able to fix this with a bit of digging; on the other hand, it's hard to justify too much time spent since it's an older browser/OS combination and represents a small number of customers.

**Comment by sdixon194** [comment]
The same user as above has let us know they also can't view Stats in their dashboard 2203859-zen

>Next time you run into this, could you please open the Safari developer tools and try to capture network and JavaScript errors, please? 

Is this something you need the user to do on their end @lancewillett, or are you looking for any errors that might be cropping up in Safari?

**Comment by lancewillett** [comment]
On either end! If you are chatting with a customer, you can ask them to do the Shift-Cmd-I trick (or the equivalent on Windows) to expose the developer console. However, Safari dev tools are off by default, so that could be a pain. If you are able to repeat it yourself, have the dev tools open and look for JS errors in the console.

**Comment by sdixon194** [comment]
Gotcha! Seems like the issue is on their older ipad. I could try asking them to grab that information, but not sure how easy that would be for them.

I was able to go into Browsertack and got some console errors on devices running 10+. Only the first error appears on iOS 9 when running an iphone 6 or 6plus, but I wasn't able to reproduce the stat issue.

Unfortunately Browserstack doesn't have dev info for ipad's running iOS <10.0, but I could reproduce the stat issue:

![failed to load resource](https://user-images.githubusercontent.com/33553323/61818074-005f2c80-ae1e-11e9-9a72-f59c9ccfc6af.png)

Unsure how helpful that is, but let me know if I can do anything else!

**Comment by kristarella** [comment]
One of the same customers is back saying this was fixed before, but is a problem again. I'm trying to clarify exactly what the behaviour is this time.

Testing in Browserstack:
-  iPad 4, iOS 7.0
- I try to go to the login page
- when I click in username/email field it redirects me to the start/user page and console has the error:
`Unrecognized Content-Security-Policy directive 'base-uri'.`

Before clicking on the username field there was these errors:
<img width="1189" alt="Screen Shot 2020-02-03 at 1 47 33 pm" src="https://user-images.githubusercontent.com/2031017/73621909-fac78680-468b-11ea-9057-cfe313587e32.png">

2684990-zen

**Comment by sgomes** [comment]
Thank you, @kristarella! I'm somewhat confused by your post. You mention a user having issues on an iPad 4 with iOS 7.0, but if I'm not mistaken that appears to be a Chrome DevTools screenshot. Is that related to the customer's issue, or did the screenshot come from somewhere else? And if it came from somewhere else, did login also fail there, or did it work correctly?

**Comment by kristarella** [comment]
Sorry for the confusion.

The customer has an iPad 4 with iOS 9. They said they are having the "same" issues that they had before, and this is the GH issue linked in their previous ticket. I am still clarifying the current issues with the user.

Everything else I described was my test via Browserstack. Using iPad 4 with iOS 7 in Browserstack login did not work, it redirected to the sign up page.

I was using browserstack in chrome and that was the console provided when clicking the devtools button in browserstack.

**Comment by sgomes** [comment]
That does make things clearer, thank you, @kristarella! 🙂 

I'll see if I can reproduce the issue using Browserstack as well and will keep the thread updated.

**Comment by sgomes** [comment]
@kristarella: I've been able to reproduce the error, and it looks unrelated to the previous issue, and unrelated to the error messages you're seeing.

The issue appears to be that the masterbar isn't working correctly in the browser, and it's overlaying its content on top of the login form. If you look closely, you'll see that the masterbar's content is ending up on top of the rest of the page.

The `/start` link, in particular, ends up on top of the username text field, so when the user clicks the field to type, they end up inadvertently clicking the `/start` link and get redirected to `/start`.

I'd suggest filing an issue around the layout breakage in the masterbar, but the browser in use here (Safari 7) is quite old (around 7 years old), and I'm not sure what level of support we're offering for it at this point.

**Comment by jonnyruzek** [comment]
User in 2684990-zen claims their issue is not occurring anymore, so it may have been a caching issue.

**Comment by cathymcbride** [comment]
iOS 9 represents <1% of iOS versions worldwide right now. Closing...
