### ISSUE TITLE
Domain only: can't create site after purchase

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#34001]
When purchasing a domain only at WordPress.com/domains, you won't be able to create a site once in the WordPress.com dashboard. It was reported in 2109054-zen

#### Steps to reproduce
1. Start at URL: https://wordpress.com/domains
2. Purchase a domain with the **domain only** option.
3. Go to the WordPress.com dashboard and click the _Create Site_ button.
4. Go through the steps, you'll get stuck at the _"Awesome! Give us one minute and we'll move right along"_ message.
5. There are no errors in the console unless you try to refresh the page

#### What I expected

The page to load and a site to be created and attached to the domain.

#### What happened instead

The final set up page gets stuck.

#### Browser / OS version

All.

#### Screenshot / Video

https://cld.wthms.co/XmLJSg

**Comment by allykmyta** [comment]
Request for update on issue in 2109054-zen. Reported that provided workaround did not work for them.

**Comment by retnonindya** [comment]
Reported here #2114481-zen

**Comment by retnonindya** [comment]
Reported again #2113922-zen

**Comment by retnonindya** [comment]
Report: #2116865-zen

**Comment by retnonindya** [comment]
Report: #2115611-zen

**Comment by p-jackson** [comment]
Error is happening at the end of the `site-selected` flow, in the `plans-site-selected` step.

We don't offer domain mappings on free sites (at lease we don't creating _new_ mappings on free sites) which might be the root cause of the issue.

It would be nice to display something to explain the situation to the user and give them a way out of the flow without purchasing anything.

A quick fix might be to hide the option of creating a free site.

**Comment by creativecoder** [comment]
🙈 This was caused by #33763 ... I'm sorry!

Here's a fix that's ready for review #34087

**Comment by creativecoder** [comment]
@cecilearkay I've deployed a fix for this regression, the free plan should be hidden again for domain only sites. Let me know if you see any other problems related to this issue.
