### ISSUE TITLE
Full Site Editing: remove site title when editing full page [3]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34072]
Currently, when editing the full page, site title is shown above the header which is not in line with current Figma. Investigate if it would make sense to remove it (how to handle permalinks that appear there?) and if possible do so.

Let's timebox this investigation and write up a post with options. Depending on what's available we might decide not to do this.

**Comment by mattwiebe** [comment]
Just noting that the MVP did not come up with any good solutions to this issue. We'd probably need to roll our own permalink feature support since hiding the title hides the permalink. Or, entirely possible that I missed something easier/obvious in my own frenetic process.

**Comment by rodrigoi** [comment]
I don't think this will be possible without implementing our own editor provider. I think that the question here is if this could be useful enough for other custom post types to include a hook where we can plug our own blocks (like with the media library).

**Comment by vindl** [comment]
See also the comment thread in paYE8P-3n-p2. How hard would it be to render the Header above the title?

**Comment by apeatling** [comment]
CSS might be an option, I left a comment on the P2 thread. At the very least the title could be selectively hidden, or made position: fixed to the top of the editor view.

**Comment by mmtr** [comment]
Another possibility is to hide the default post title rendered by the editor (`.editor-post-title { display: none; }`) and manually render a [`PostTitle` component](https://github.com/WordPress/gutenberg/blob/af6e5ecd8b398e08127ad1b3c784ce97899de100/packages/editor/src/components/post-title/index.js) in our `a8c/post-content` block just before the list of blocks.

Since we can insert the post content block in any post, the tricky part would be to identify if the current edited post is a full page, but it should be doable. I'll try to open a PR today or tomorrow exploring this approach.
