### ISSUE TITLE
FSE: Dynamic Blocks don't appear in published view of Template Parts 

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#34166]
If a template part includes only blocks (meaning, HTML comments such as `<!-- wp:a8c/site-logo /-->`), the parser will fatal with an error: `Fatal error: Uncaught TypeError: Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given in /var/www/html/wp-content/plugins/full-site-editing-plugin/full-site-editing/utils/replace-template-parts.php:63`.

This happens because the the dynamic block's render_callback isn't being called. When this happens  `DOMDocument::loadHTML` [here](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing/utils/replace-template-parts.php#L61) strips HTML comments, and if all it's passed is HTML comments, it'll return `false`, meaning `DOMDocument->documentElement` never gets populated, and we end up passing `null` to `DOMDocument::importNode` – which fatals.

#### Steps to reproduce
1. Create or edit a template part to add a dynamic block (such as `<!-- wp:a8c/site-logo /-->`) or recent posts.
2. Load the front-end of a page with that template part.
3. Notice the error, and the fact that the header and footer template parts haven't properly replaced the theme's header and footer.

**Comment by kwight** [comment]
I tried a couple of things to address this, none of which were clearly effective.

The most promising/least confusing semantically was to pass a `DOMComment` to `importNode`, via `DOMNode::appendChild()`. This works, but requires passing only the comment string, ie. `wp:a8c/site-logo /` in the case of `<!-- wp:a8c/site-logo /-->` – pretty awkward. And we would have to loop over each block to generate a proper HTML comment for each string.

I thought `DOMDocument::createTextNode` might work, but by generating a text node, it just means the HTML comment is output to the screen as, well, text.

An option to keep HTML comments in `loadHTML` would be ideal, but I couldn't find anything appropriate.

One option I didn't get time to play with is to create our own version of either `DOMDocument::loadHTML` (which doesn't strip comments) or `DOMDocument::createComment` (that doesn't add the comment symbols).

**Comment by gwwar** [comment]
I think our dynamic block render_callback functions aren't firing here. I can add paragraph blocks just fine, but for example a latest post block won't render in the header.

**Comment by gwwar** [comment]
Leaving a note here for related usage searches:

https://github.com/WordPress/WordPress/blob/225de4e6eb6ef4ae0de4a6945aab6556433acad9/wp-includes/class-wp-block-type.php#L109

**Comment by mmtr** [comment]
I can see the dynamic blocks markup on the published view:

<img width="588" alt="Screen Shot 2019-06-21 at 11 56 40" src="https://user-images.githubusercontent.com/1233880/59894457-a7196d00-941b-11e9-90e1-90b7d8796c49.png">

So even if we manage to don't strip the comments when doing `DOMDocument::loadHTML` to avoid the fatal error when the template part contains only dynamic blocks, the problem is that they won't be rendered on the published view.

Probably the `do_blocks` action is not rendering the dynamic blocks because of the way we're replacing the page areas with the template parts. 

We're using the output buffer (`ob_start`/`ob_end_flush`) to capture the HTML output and perform the replacement, but that's likely late too late in the chain and the `do_blocks` action was already triggered before.

https://github.com/Automattic/wp-calypso/blob/7943db1f3a8ab75b96ab6e82ca8e6e93c70d430c/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L31-L43

**Comment by mmtr** [comment]
Furthermore, by default `do_blocks` is only executed against the post content:

https://github.com/WordPress/WordPress/blob/225de4e6eb6ef4ae0de4a6945aab6556433acad9/wp-includes/default-filters.php#L172

Then, we need to manually execute `do_blocks` when replacing the HTML with the template parts that are not inside the post content.
