### ISSUE TITLE
eCommerce Plan: Selecting from pricing page leads to redundant plans step

### ISSUE THREAD

**Issue by jonathansadowski** [Automattic/wp-calypso#34253]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/pricing/
2. Select "Start with eCommerce"
![image](https://user-images.githubusercontent.com/363749/60056083-53ba4f80-96a5-11e9-8071-add53c77b346.png)

3. (If you're logged out) Complete the user step and create an account.
3. Enter your site name, topic, etc, and continue
4. Choose a domain for your site and hit continue

#### What I expected

I expected to be taken directly to the shopping cart, since I already selected the eCommerce plan.

![image](https://user-images.githubusercontent.com/363749/60055940-e1e20600-96a4-11e9-864f-43c1d07b3bfb.png)

#### What happened instead
I was again shown the plan selection screen.

![image](https://user-images.githubusercontent.com/363749/60055895-b8c17580-96a4-11e9-8c07-5877fbcf6c07.png)

**Comment by creativecoder** [comment]
As @jonathansadowski pointed out to me, it looks like automatically completing the plans step was implemented for other plan types in https://github.com/Automattic/wp-calypso/pull/30671, but not for eCommerce.

**Comment by niranjan-uma-shankar** [comment]
Thanks for pointing to this @creativecoder . I previously raised this here https://github.com/Automattic/wp-calypso/issues/34179. 

The flow linked to the `Start with eCommerce` needs to be changed since it also shows the old `About `step. Though I'd suggested to show both Business & eCommerce(since both allow setting up a store), I agree that not showing a plan step at all and having the eCommerce plan added to cart is also a valid experience.

**Comment by creativecoder** [comment]
I'm a fan of both options--either way will be a much better experience than the current one.

**Comment by timmyc** [comment]
After selecting the ecomm plan, I am now directed to the cart. Closing out.
