### ISSUE TITLE
User cannot renew when auto renew is off.

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#34338]
There is no way to manually renew when the auto renewal is turned off.

#### Steps to reproduce
1. Starting at URL: /me/purchases/
2. Open the purchase info of a WPCOM plan or a Jetpack plan
3. Toggle off the auto renewal toggle

#### What I expected

I expected the `Renew Now` button to be retained

#### What happened instead

The `Renew Now` button is removed. 

<img width="735" alt="Screenshot 2019-06-27 at 5 50 42 PM" src="https://user-images.githubusercontent.com/1269602/60265928-929a1080-9904-11e9-8b33-ae8738d7d9d9.png">

#### Browser / OS version

Chrome/MacOS

#### Screenshot / Video

![giphy (1)](https://user-images.githubusercontent.com/1269602/60265692-f1ab5580-9903-11e9-8a57-1b6472d9d66a.gif)

**Comment by DavidRothstein** [comment]
Note that the user can still renew via the "Renew Now" link at the bottom of the page... That said, this does seem like a bug.

The current code on WordPress.com production actually hides the "Renew Now" button at the top of the page on purpose, since the informational message above it contains a "Renew Now" of its own.  But if the auto-renewal toggle code is going to remove the "Renew Now" link in the informational message, it should add the button back too. 

That said, I think at least part of the problem is that the auto-renew toggle code is too aggressive in removing the "Renew Now" link from the informational message?  For example, if the subscription is expiring soon, it looks like this on WordPress.com production:

![expiring-soon-current-production-behavior](https://user-images.githubusercontent.com/235183/60483546-e178da80-9c63-11e9-80f9-a21020e1c066.png)

But it looks like this in development (with the auto-renew toggle feature in place):

![expiring-soon-with-autorenew-toggle-feature](https://user-images.githubusercontent.com/235183/60483545-e0e04400-9c63-11e9-8c4a-c4879e57f793.png)

I think that's a case where the link should remain in the informational message.
