### ISSUE TITLE
Full Site Editing: make next steps more obvious after template part changes are saved [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34346]
Currently when users edit a Header or Footer and save the changes, they can go back to the parent page by clicking the Close button. However, it has been pointed out that this might not be obvious to users by @apeatling:

> When the header or footer has been saved, it needs to be more obvious what to do next to get back to the page you were editing.

Let's work with design and improve this flow in order to make next steps more obvious, and implement that solution.

/cc @jasmussen

**Comment by jasmussen** [comment]
Thank you for the ping!

> they can go back to the parent page by clicking the Close button

Worth noting that a page will never be a "parent" to a footer or header, but rather just _one_ page that includes the template part. So clicking a close or back button will be a navigation to the _previous page_ rather than a parent page. Small semantic difference, but worth noting as it might help inform other ideas. 

Longer term, this is the mockup we have for how to navigate between pages and template parts:

![Screenshot 2019-07-01 at 09 30 22](https://user-images.githubusercontent.com/1204802/60418295-dd58a880-9be2-11e9-82d4-da2dc698f93f.png)

That is, there is a dropdown navigation menu that both shows you which page or part you're editing, and lets you navigate between them. The idea being that both the browser back button, and the toolbar back button, take you back to the page you were editing before editing a template part, but in addition to that, visually showing the title of the element you're editing, helps inform you _where you are_ and implicitly, _where you no longer are, i.e. what you can go back to_. 

Or to phrase that a little differently: if there is no visual difference in the _editor itself_ when you are editing the Header template part, vs. editing a page that includes the header, that's where the confusion comes from. Showing "Home Page" in the title, and then "Templates → Header" when you choose to edit that, it helps convey what's going on.

To my understanding, some of the challenge with the design here is that we're limited in what we can do, especially inside the editor itself. So in that vein, here are some ideas:

1. Throw up a snackbar, or even a banner notice, when you're done editing a template part, that simply informs you: "Successfully updated Header.      [link]Back to editing Home Page[/link]"
2. Show a noticable visual change when you are editing a template part. This could be a different color set, or even a big bar.

For 2, we can take inspiration from Keynote, which kind of tackles the same challenge of differentiating between content and master slides:

![keynote](https://user-images.githubusercontent.com/1204802/60418980-92d82b80-9be4-11e9-871a-cbf4e678a5c1.gif)

Note here how the editor is virtually the same, but that there is a notice before you go to edit the master slide, and there's a blue bar at the bottom. Both of these are good patterns to take inspiration for, for making it obvious. Such a notice could even be a simple JavaScript "leave page" alert between the two type of content.

Here is an older mockup where we explored such a big visual indicator (blue bar at the bottom):

![Screenshot 2019-07-01 at 09 47 01](https://user-images.githubusercontent.com/1204802/60419307-3d504e80-9be5-11e9-80ab-f6d31f8aec98.png)

Such a bar could help indicate that you're editing a template part, even if it did not include the save button.

**Comment by gwwar** [comment]
Closing this out, as we already iterated on flows here for v1
