### ISSUE TITLE
Full Site Editing: improve pre-publish notice [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34343]
When publishing or updating any Template Part, the pre-publish notice will appear, warning the users that this change will propagate across multiple pages.

<img width="299" alt="Screenshot 2019-06-27 at 21 19 19" src="https://user-images.githubusercontent.com/1182160/60294249-401b1d00-9921-11e9-9b62-53c3cec5dca5.png">

It has been pointed out that this notice might not be obvious to folks and that we should make it more... noticeable. :)

Let's work with design to figure out how it can be improved and implement that solution.

Quoting some feedback from @apeatling here:

> The notice before publish on a template part needs to stand out more so the user reads it at least for the first publish.
> The wording on the template part notice needs to be clearer to users, they won't know what a template part is.

/cc @jasmussen

**Comment by apeatling** [comment]
I suggest we use the name of the template part. So for the header it would read:

> Changes published will update all pages using this header.

**Comment by jasmussen** [comment]
Here's the design we have for this interim interaction:

![Group](https://user-images.githubusercontent.com/1204802/60417976-147a8a00-9be2-11e9-9f15-e31d190feb18.png)

I would echo what Andy suggested, that's a nice small iteration. If you'd like to give it extra emphasis, you could include [this icon](https://material.io/tools/icons/?search=warning&icon=warning&style=outline) in the prose:

![Screenshot 2019-07-01 at 09 26 01](https://user-images.githubusercontent.com/1204802/60418058-48ee4600-9be2-11e9-9653-43c1f7bb692f.png)

Finally, you can consider including a Snackbar notice that pops up informing you you're about to make global changes. It could pop up when ever you click the Publish... button, for a template part. Snackbars: https://developer.wordpress.org/block-editor/components/snackbar/

☝️ I suspect some of the above suggestions, notably the snackbar, to either be impossible without a fork, or otherwise complicated. So see the above as suggestions for improvements, not as gospel.

**Comment by glendaviesnz** [comment]
This can be closed if we go forward with #34728 as the confirmation panel will be removed in that case - if not there is a patch at https://github.com/Automattic/wp-calypso/tree/update/fse-publish-panel

**Comment by gwwar** [comment]
Thanks folks! I'm going to close in favor of https://github.com/Automattic/wp-calypso/issues/34728

We can always reopen if we still want to work on this piece.
