### ISSUE TITLE
Full Site Editing: show template parts when creating a new page [?]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34341]
Currently when you activate the plugin and attempt to create a new page, default header and footer will not be visible in the editor. They only appear once you publish and refresh. For start, these should be immediately visible when new page is created (either with blank content, or pre-populated with some Started Page Template content).

Please be aware that there might be some ongoing work regarding this already - https://github.com/Automattic/wp-calypso/pull/34214#issuecomment-505715319
/cc @mmtr

**Comment by mmtr** [comment]
After https://github.com/Automattic/wp-calypso/pull/34296, the editor should load the default template when creating a new page.

But note that the flow is not perfect yet, since selecting a Starter Page Template will result in the content being appended after the footer (https://github.com/Automattic/wp-calypso/issues/34330)

**Comment by vindl** [comment]
@mmtr Would you like to create a new one for the second part of the issue then?

**Comment by mmtr** [comment]
@vindl It's already created and you already added to the next sprint :) https://github.com/Automattic/wp-calypso/issues/34330

**Comment by vindl** [comment]
Thanks for pointing it out! It was late and there were so many issues... 😄

Closing since the relevant remaining work will be handled in https://github.com/Automattic/wp-calypso/issues/34330.
