### ISSUE TITLE
FSE: Site title and description blocks allow line breaks.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#34419]
The site title and description blocks now use `textarea`s instead of `input`s, which means users can enter entire blocks of text, including line breaks. The intention behind this is to better handle long values, but it makes previewing difficult, and introduces values into the database that are not common (nor possible through the WP Admin Settings page).

<img width="923" alt="Screen Shot 2019-07-02 at 10 30 49 AM" src="https://user-images.githubusercontent.com/349751/60535248-89b88e80-9cb8-11e9-98e5-b776d3de5d61.png">

<img width="1492" alt="Screen Shot 2019-07-02 at 10 39 00 AM" src="https://user-images.githubusercontent.com/349751/60535259-9210c980-9cb8-11e9-8890-581f1fb5a4fe.png">

**Comment by gwwar** [comment]
Some options here, for example one possibility is to keep using the PlainText component, but update <kbd>Enter</kbd> behavior to unfocus the current block, similar to how paragraph blocks create a new block on <kbd>Enter</kbd>.

We could also pick another WordPress component.

Let's check in with @shaunandrews on what matches more closely with the UX constraints here and the core project.

For context we can also update this in `/wp-admin/options-general.php` where these are both inputs, which suggests that breaks are not intended to be added.

<img width="622" alt="Screen Shot 2019-07-02 at 11 06 10 AM" src="https://user-images.githubusercontent.com/1270189/60535620-693d0400-9cb9-11e9-8ed0-1fe2ff73c667.png">

**Comment by mattwiebe** [comment]
There's prior art for this in the MVP. We [strip out newlines](https://github.com/Automattic/site-builder/blob/096a3ef7a19f0b8bc9186add9c7793adf5d06613/src/site-header/edit.js#L73) and also render inside of a [phantom element](https://github.com/Automattic/site-builder/blob/096a3ef7a19f0b8bc9186add9c7793adf5d06613/src/site-header/edit.js#L22-L38) which has `visibility: hidden` in order to flow properly in flexbox-based layouts. We could maybe abstract that behaviour into something like a `PlainTextSingleLine` component.
