### ISSUE TITLE
Signup: misalignment of translated text for requestButton and changeButton

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3444]
## Issue description

In the "Next Steps" section of the signup process, `requestButton` and `changeButton` produce incorrect alignment for some translated locales (e.g. ES, RU) where translations are significantly longer than the original EN text.
## Browser / OS version

Mobile/iOS
## Screenshots

English: correctly alignment
![en_mobile_6_next_steps_screenshot1453776829263](https://cloud.githubusercontent.com/assets/7637835/13204796/5e9a4c46-d8e1-11e5-981c-547e9e4bb288.jpg)

Spanish: misaligned
![es_mobile_6_next_steps_screenshot1453773890740](https://cloud.githubusercontent.com/assets/7637835/13204797/5eeb0884-d8e1-11e5-8d29-3c0fe6a7862f.jpg)

Russian: misaligned
![ru_mobile_6_next_steps_screenshot1453779308814](https://cloud.githubusercontent.com/assets/7637835/13204805/89c7bc28-d8e1-11e5-935a-c4679ec9c964.jpg)

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue, Spanish and Russian are still misaligned as in the examples above.  I checked a couple other languages, and German is also bad:
![screen shot 2016-05-12 at 10 58 51 am](https://cloud.githubusercontent.com/assets/7233112/15219168/b4b85512-1830-11e6-8b8a-0906719020f4.png)

**Comment by alisterscott** [comment]
This is no longer an issue since the screen has been redesigned:

Spanish:

<img width="559" alt="screen shot 2017-07-18 at 12 13 57 pm" src="https://user-images.githubusercontent.com/128826/28297763-fc5e5be2-6bb2-11e7-9495-fae0f3ad72df.png">

Russian:

<img width="557" alt="screen shot 2017-07-18 at 12 15 34 pm" src="https://user-images.githubusercontent.com/128826/28297772-0338718c-6bb3-11e7-8a38-c3da8d59c3a5.png">
