### ISSUE TITLE
Question: Design of External Dependency usage and Upgrades

### ISSUE THREAD

**Issue by afsheenirani** [Automattic/wp-calypso#3445]
## Question: Design of External Dependency usage and Upgrades
Hi @blowery , recently I saw you went through a massive uplift of the codebase owed to an update of an external dependency (lodash) in #3288 . This seems like a problem that we will face on-and-off and as the calypso codebase grows, upgrading to the external dependencies will become a much harder problem to solve.

Having said that, from a design perspective, is there a way that we can essentially draw a boundary interface where you can essentially "register" any external dependencies to be used making it a single point of entry to the calypso codebase?

I'm pretty new to ReactJS and would like to reign in your expertise on the possibilities here...

At a high level, what I'm thinking is this, have a file (say) ext-dependencies.js as a single point of entry (or maybe a few across the top-level folders) that require() any external dependencies from npm-modules and then module.export these internally. All internal calypso files should ONLY leverage the modules exposed via the ext-dependencies.js file. Now, in future, when there is an external upgrade, you just need to make the change once or to a few places and unit test the interface thoroughly as opposed to a massive uplift of the entire calypso codebase.

I think such an approach would also help to drive consistency for developers to see what common "external" modules (have been exposed internally) and are being leveraged.

Would love to get your thoughts on this and feasibility of such an approach.

CC @nb for FYI.

**Comment by blowery** [comment]
Hi @afsheenirani, 

That approach is typically called a [facade](https://en.wikipedia.org/wiki/Facade_pattern) and it would certainly reduce exposure to the external library.

The problem with that approach is that you're then limited to the interface exposed by the facade, and taken to an extreme, you end up having to write up a facade for everything you use. The hard part of the recent lodash move wasn't really the package moves, it was the semantic split in a number of iteration methods. If we had a facade in place, when we moved, we would have had to detect the style of usage of the old function and then picked the correct new version in the facade. This requires a developer using the facade to understand both the facade _and_ the underlying lib, where using the lib directly requires knowledge of only the lib. 

To make it more concrete, assume we had a lodash 3 facade like:

```
import { merge } from 'lodash/merge';

export merge;
```

Now 4 comes out and merge turns into merge and mergeWith, so what might we do?

```
import { merge, mergeBy } from 'lodash/merge';

function theseLookLikeThreeArgs( args ) {
  return isFunction( last( args ) );
}

// so ... what does this do? lodash 3's merge, or 4's?
export function merge(...args) {
  if ( theseLookLikeThreeArgsThatUseByNow( args ) { 
    yellAtDev( 'hey, update this call to use mergeBy!' );
    return mergeBy.apply( null, args );
  }

  return merge.apply( null, args );
}

export mergeBy;
```

So that gets us a warning if someone uses merge in the old style. That's very useful! But how long should we keep that code in place? Who's going to maintain it?

The other issue with the facade — and this is particular to lodash — is that it would end up pulling in nearly _all_ of lodash. We use the modular imports to help keep bundle size as small as possible; having the facade would make that much harder to wrangle.

Lodash is a bit of an odd case, as we use it more like a language extension than a library. It's all over the codebase, and for the most part, it's been quite stable. 3->4 was a big jump and not something we're expecting to have to wrangle all that often. I actually don't think we have anything else that's quite so pervasive across the codebase, other than React.

So, I think facades have merit, but they're an expensive road to travel, mostly in terms of developer productivity. Instead of adding a dep, importing the dep, and using the dep, I then also have to think about whether I need a facade for the dep. For most of our deps, I'd say the answer is "no", because they're not used widely and the surface area is pretty small. We have a _ton_ of deps and I can't imagine wanting to maintain a facade for each one.

Thanks for asking the question! Keep 'em coming. :)

**Comment by afsheenirani** [comment]
Thanks @blowery for that added context. This certainly answers my question. 

After taking a deeper look into what lodash provides, I can now see how it is used as an extension of JS rather than some external dependency and that maintaining a facade (thanks for pointing out the design pattern) would be even more work. 

Also, the fact that the lodash upgrade was a semantic one would basically mean that you would have to have an understanding of every usage in the calypso codebase to pick and choose the right api in the facade after the upgrade.

Feel free to close this issue.

**Comment by blowery** [comment]
@afsheenirani I'm glad that helped clear it up! I know it helped me to put it down in writing.
