### ISSUE TITLE
FSE: The content slot is affecting content widths

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34558]
With the Modern Business theme and the FSE plugin disabled I get this for the home page template:

<img width="1295" alt="Screen Shot 2019-07-09 at 11 17 57 AM" src="https://user-images.githubusercontent.com/1464705/60913067-761ea200-a23b-11e9-809e-fa4a6657df6f.png">

If I activate the FSE plugin, I instead get this:

<img width="1296" alt="Screen Shot 2019-07-09 at 11 18 31 AM" src="https://user-images.githubusercontent.com/1464705/60913088-7fa80a00-a23b-11e9-962b-76fecd77a1d2.png">

Notice how the content widths are broken for the page content, the hero header is offset to the left. I suspect it is something to do with the content slot that is breaking this?

This was running locally with the latest version of the FSE plugin from master, and a copy of Modern Business pulled directly from the WordPress.com codebase.

**Comment by gwwar** [comment]
We're likely not enqueuing the expected styles here, but should we need additional rules I'd recommend adding the proper editor styles as part of the theme vs the plugin. The theme content may vary with defaults. https://developer.wordpress.org/block-editor/developers/themes/theme-support/#editor-styles

**Comment by noahtallen** [comment]
I've been poking around at this to learn a bit more about how we handle styles and I think we might already be enqueuing the proper editor styles. I think the issue might be that the classes which the theme targets don't quite match the format of the post as we have it in FSE.

For example, in elegant business, the editor style which makes the page slimmer is:
```css
  body .editor-writing-flow {
    max-width: 80%;
    margin: 0 10%;
  }
```
However, `.editor-writing-flow` wraps the entire editor, so it's not getting applied to the post content inside the block. Normally, this works because the entire editor _just_ contains the post.

Additionally, the style which makes the blocks even slimmer in the middle of the page is:
```css
@media only screen and (min-width: 1168px) {
  .wp-block {
    width: calc(6 * (100vw / 12 ));
  }
}
```

It looks like this is still getting enqueued because of the screenshot below. I think it's just getting overridden by something which sets it the width to 100%. If you uncheck the top style, the width is narrower as expected. Still trying to nail down where the 100% width style is coming from! 
<img width="322" alt="Screen Shot 2019-07-12 at 1 07 38 PM" src="https://user-images.githubusercontent.com/6265975/61155556-11b34b00-a4a6-11e9-893e-df47ae79edf5.png">

For example, in the actual post editor, the style on a block is getting set to that correctly:
<img width="299" alt="Screen Shot 2019-07-12 at 1 13 17 PM" src="https://user-images.githubusercontent.com/6265975/61155885-e5e49500-a4a6-11e9-80f7-033ebb335c17.png">

**Comment by noahtallen** [comment]
I also found that if you remove the `data-align="full"` from the html around the block, it aligns much more like it should:

**With data-align set to full:**
<img width="1905" alt="Screen Shot 2019-07-12 at 1 31 55 PM" src="https://user-images.githubusercontent.com/6265975/61156967-a3708780-a4a9-11e9-9654-72e2f9b695da.png">

**With data-align removed:**
<img width="1890" alt="Screen Shot 2019-07-12 at 1 32 21 PM" src="https://user-images.githubusercontent.com/6265975/61156933-8a67d680-a4a9-11e9-9773-536565502a7f.png">

**Comment by noahtallen** [comment]
Similar to #34572 because you can also use those width buttons here on the post (which I think is what data align is doing). However, those changes don't reflect on the front end, though they probably should. (E.g. I could see a user wanting to change the width of the content on a page/post)

**Comment by noahtallen** [comment]
A quick fix could be to just remove support for changing the size of the block here: https://github.com/Automattic/wp-calypso/blob/7bb576208dc3ebfbf870e7123f830c8cdd5ad783/apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/post-content/index.js#L19-L21

**Comment by apeatling** [comment]
As an aside I don't think any of our template part blocks should have options to change the size of the block, so I'd like to see those removed.
