### ISSUE TITLE
FSE: Heading/Footer blocks allow for you to change the width

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#34572]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/191598/60935917-6fbf1300-a299-11e9-98a3-692015c00491.png">

The heading and footer blocks include buttons in their toolbar that allow you to change their width. I don't think we want to allow this change to be made outside of editing the template parts themselves.

**Comment by noahtallen** [comment]
I investigated this a bit today, and I'm struggling to get this working. It's very easy to remove support for alignment, but that means the template part gets centered and has some pretty wide margins on either side. So it wouldn't display well if we wanted to show a full width header in the editor. I think we essentially want it to stay full width, but Gutenberg doesn't appear to support forcing a block to just use one of the alternative alignments without showing the option to toggle it.

Essentially, we want `data-align="full"` to show up on the outer div around the block in the editor, but I'm also not sure if we can do that easily because that part of the dom is rendered internally.

The other solution I'm thinking about is using css to get the block to show up full width. I'm not sure how viable that is, though, because I'm guessing we want to change the style of the entire block wrapper, not just what we render which shows up inside the block wrapper.

Hopefully someone with a bit more experience can help out with some more options. I'm learning all about how this works as I go, so there are definitely some knowledge gaps!

**Comment by apeatling** [comment]
@noahtallen Your recent changes have fixed this, right?

**Comment by noahtallen** [comment]
Yep, this was resolved in #34691!
