### ISSUE TITLE
Onboarding: Total step count changes in-flow

### ISSUE THREAD

**Issue by lcollette** [Automattic/wp-calypso#34598]
#### Steps to reproduce
1. Start at https://wordpress.com/start/site-type
2. Note the step count - 1 of 6 - in the top-right corner 
3. Choose Blog
4. Step count is now 1 of 5.

#### What I expected
The total step count stays the same.

#### What happened instead
The total count changes depending on the site type the user picks without explanation.

→ blog - 2 of 5
→ business - 2 of 6
→ professional - 2 of 6
→ online store - 2 of 3 

#### Screenshot / Video

![Screen Recording 2019-07-08 at 03 47 PM](https://user-images.githubusercontent.com/181733/61069208-9fb50600-a3c0-11e9-8b0d-3fcb14e0fa01.gif)

#### Context / Source

This issue came up during usability testing. The user noticed the count had changed but they didn't know why. We should avoid making the user think outside of the focused task.

**Comment by ramonjd** [comment]
This is something we were discussing during our meetup, that is, whether the count is useful at all in this context.

The steps will sometimes change depending on how the user proceeds in the flow. This is because some site types, for example, don't require extra steps to complete the signup journey.

One suggestion was to provide a list of steps to complete. We would face a similar issue however as the list would update as the flow changed. 

My only fallback in such a scenario is to explain why something is happening. For example, telling the user that they've chosen and online store and that they have `n` steps or the "following steps" before them in order to create a site.

cc @Automattic/zelda @Automattic/start-dev

**Comment by p-jackson** [comment]
Maybe we could replace the "Step 1 of 6" text with a visual indication like a progress bar or pie graph. That way they can at least see what sort of percentage of the way through they are.

Not as good as having the actual numbers, but we can't really know how many steps they're going to need to complete, and will hopefully be less distracting.

**Comment by ramonjd** [comment]
It doesn't pertain directly to the step count, but there were some interesting suggestions over at https://github.com/Automattic/wp-calypso/issues/34299#issuecomment-507298963

I like the idea of a visual progress indicator!

**Comment by ramonjd** [comment]
Related issue: https://github.com/Automattic/wp-calypso/issues/34390
