### ISSUE TITLE
Gutenberg: Attempt a 6.2 update [5]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34660]
Let's update the Gutenberg Plugin for Simple and Atomic sites to v6.2

- [x] Test the 6.2 Gutenberg RC for both Simple and Jetpack Sites (7/22) and make it available on horizon https://github.com/WordPress/gutenberg/releases/tag/
- [x] ~Test the 6.2 Gutenberg plugin for both Simple and Jetpack Sites (7/24)~ (https://github.com/Automattic/wp-calypso/issues/34660#issuecomment-517821992)
- [x] Merge e2e test fixes (https://github.com/Automattic/wp-calypso/pull/35000)
- [x] Report and help fix related issues in the core project / Jetpack / wpcom
- [x] If no issues are found attempt to deploy the wpcom diff for Simple Sites
- [x] If simple sites are stable, file a related request to update the atomic Gutenberg plugin version.

See also steps in PCYsg-m14-p2

**Comment by kwight** [comment]
I realize now I never updated Horizon to the actual v6.2.0 release, so it's still running the RC as we look to an update on Monday, Aug 5.

I've compared the two releases (RC vs. proper), and the only difference is in `src/components/block-list/block.js`:

<img width="1209" alt="Screen Shot 2019-08-02 at 12 33 50 PM" src="https://user-images.githubusercontent.com/349751/62394652-abf53480-b522-11e9-849c-fb5a41245e16.png">

It turns out this is to fix a regression, patched in https://github.com/WordPress/gutenberg/pull/16819. This being the case, I think we're good to go straight to 6.2.0 on both horizon and production. 👍

**Comment by mmtr** [comment]
Both Simple and Atomic sites are using now 6.2.0: p7DVsv-747-p2, pMz3w-ab1-p2
