### ISSUE TITLE
Full Site Editing: close button not navigating back on Simple sites [3]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34864]
While editing header and footer on Dotcom simple sites, after click the close button the browser URL is updated correctly (to the post ID passed in `fse_parent_post` parameter), but the action for navigating to that page is no longer working.

I'm certain that this was working after I deployed the latest sync patches for FSE, Gutenframe, and Modern Business - on Monday and Tuesday (7/22 and 7/23), and I tested this flow quite a few times. However, it's no longer working for me - not sure what change might have caused this since we haven't deployed any FSE related changes since that time.

**Comment by mmtr** [comment]
Maybe this is related to the same issue I noted on https://github.com/Automattic/wp-calypso/pull/34766#issuecomment-513427091, so this might be fixed by forcing a full server navigation instead of dispatching a `navigate` action (as done [here](https://github.com/Automattic/wp-calypso/pull/34766/commits/5e25c666147fab903c6db10c25b8dd3d13dfc133)).

**Comment by noahtallen** [comment]
On this line: https://github.com/Automattic/wp-calypso/blob/7851a987998036c7e6e60c78e8a9db9b9d77e87e/apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/close-button-override/index.js#L15

closeButtonUrl is not defined when entering the template part editor. not sure if that's related, since the URL is updating. I wonder if it's failing because we reloaded the entire JS app - would it even have a context to take us back to for navigation?

**Comment by mmtr** [comment]
@noahtallen it should be unrelated, since in WP.com we have our own custom handler for the close button that ignores that override done by the plugin:

https://github.com/Automattic/wp-calypso/blob/27f71046be0f38f0861f12cade8ca49b79522ffb/apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js#L525-L534

**Comment by noahtallen** [comment]
So far, my only conclusion is that stuff related to `navigate( url )` is super wack when you're trying to navigate between different pages in the post editor. Investigating a hack for the back button to do a full reload to go back as Miguel did in his implementation for opening the TP editor.

**Comment by noahtallen** [comment]
One interesting thing is that the close URL on the element itself points to something like `"http://calypso.localhost:3000/types/wp_template_part/code4noah.wordpress.com"`. In that bit of code Miguel shared above, if you skip the post message and the prevent default, it'll go to that URL. I'm guessing that we might want to override that to be the correct URL.
