### ISSUE TITLE
FSE: Site Description block "jumps" when focused

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#34886]
![jumpy block](https://user-images.githubusercontent.com/191598/61888695-feef3c00-aed1-11e9-922e-ad1ae1a3c82e.gif)

When focusing on the Site Description block I noticed that the text and spacing changes. This makes the UI jump around and doesn't feel right. I think its making room for the inline inserter, but I don't see the behavior on other blocks.

**Comment by noahtallen** [comment]
This is fun :P I was able to stop the jumping around after you've clicked into it the first time. But there is still a jump at the beginning because somewhere, something is manually overriding the height of the element and then changes it when you click into it, but only on the first time:
![2019-08-01 11 12 26](https://user-images.githubusercontent.com/6265975/62316905-6fa3d480-b44d-11e9-9bdd-623306df15f3.gif)

Now to track down that behavior...

**Comment by noahtallen** [comment]
I think this is a bug with the underlying react library Gutenberg uses to render this component. Looking for an alternative 👀
