### ISSUE TITLE
FSE: Content Slot block UI is confusing to users

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#34889]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/191598/61892988-fe0ed800-aeda-11e9-9457-7832a0a9e1f7.png">

Our page template uses a Content Slot block to contain page-level elements. The UI this presents causes some confusion, as you can really do anything with it and it adds an extra click to edit any child block within.

Can we remove all UI relevant to the Content Slot?

**Comment by noahtallen** [comment]
I don't know much about this, other than that it's kinda tricky because from an architectural pov, the content block is "how" we get the post content into the block editor alongside the header and footer through the concept of the template. I'm not sure if gutenberg has a mechanism for a block that just transparently lets the content come through without presenting itself as a block in the editor. Maybe we could hack the style/onclick stuff to do with the content block?

Though the content slot is definitely useless right now, I could see it being potentially useful in the future, say if we are looking to add aliment options for the content on the page, or changing other settings in-editor that affect the global content slot.

**Comment by gwwar** [comment]
I think it's worth a try to not display this. We never intended customers to see the internals of how we're doing this, and we'll eventually hide template/template_parts as CPTs in wp-admin/Calypso before we relase. The Content Slot in particular is even more internal than say a group block, which a customer can insert themselves.

Do you mind changing the title @shaunandrews? Something like "Content Slot block UI is confusing to users"?
