### ISSUE TITLE
Onboarding: Button in the checklist doesn't have the correct French translation

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/wp-calypso#34938]
#### Steps to reproduce
1. Create a new site with your interface in French.
2. At the end of the onboarding process, you will have a checklist with the first item being "Update Your Homepage". You will have 2 buttons: primary: "Essaye __z__" ("Try") and "Passe __r__" ("Skip").

#### What I expected
Both verbs should have the same conjugation
* Essaye __r__
* Passe __r__

#### Screenshot

![translation](https://user-images.githubusercontent.com/177929/62004015-b628c480-b117-11e9-867a-2ece11a3dd64.png)

**Comment by sixhours** [comment]
I'm guessing we need to use a comment context to ensure the translators understand these strings are connected. Pinging i18n for a review to get their thoughts on the best approach.

**Comment by emilyaudela** [comment]
I have updated the [string](https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=254832&filters%5Btranslation_id%5D=7989824) to use the infinitive. 

The [French style guide](https://translate.wordpress.com/glossaries-and-style-guides/french-style-guide/) says to use the infinitive (ending in r) when the string does not end with a fullstop and to use the imperative (ending in z) when the sentence ends with a fullstop. Translators should be following the guidelines in the style guide, but sometimes they don't. I don't think this needs a context, since the string should always be translated as the infinitive if following the style guide.
