### ISSUE TITLE
Editor: Redirect from Gutenframe to WP Admin not working

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#35014]
The redirect to WP Admin for atomic sites that have a denied plugin installed is not working.

**Environment**
- atomic site
- user RC set to use Gutenberg
- plugin (such as Elementor) installed such that Gutenframe is set to "no"

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/pages
2. Click on a page to edit it or click Add New Page

#### What I expected
To be redirected to a URL such as /wp-admin/post.php?post=70&action=edit

#### What happened instead
Sent to Gutenframe editor e.g., https://wordpress.com/page/kristarellabiz2.wpcomstaging.com/70

Receive a popup message to switch to Block Editor

#### Browser / OS version
Mac 10.13.6 | Chrome 75.0.3770.100

#### Screenshot / Video
_Site should not use Gutenframe_
<img width="689" alt="Screen Shot 2019-07-31 at 3 14 39 pm" src="https://user-images.githubusercontent.com/2031017/62185461-f8ffcc00-b3a5-11e9-8771-da4886b3edb6.png">

_Message to switch to blocks (even though RC is already set to use Gutenberg)_
<img width="1426" alt="Screen Shot 2019-07-31 at 3 09 53 pm" src="https://user-images.githubusercontent.com/2031017/62185384-973f6200-b3a5-11e9-8eee-83751e56609d.png">

_Video of loop that happens when trying to enable blocks_
https://cld.wthms.co/EH0m1A

#### Context / Source
#user-report
13973733-hc
13581549-hc
14257773-hc
13774679-hc
14247844-hc

Maybe related to #34856

**Comment by mmtr** [comment]
Definitely this has been caused after landing my changes in D30746-code.

Those changes ensure that AT sites that are ineligible for Gutenberg in Calypso (i.e. if they have a conflicting active plugin like Calypso) won't get any Gutenberg flow from Calypso, so the Classic editor is used as fallback.

The problem is that the "Switch to the block editor" buttons will be still visible. I already reported that issue last week (https://github.com/Automattic/wp-calypso/issues/34856) and hopefully if will be solved by https://github.com/Automattic/wp-calypso/pull/34858 tomorrow.

I reverted D30746-code in the meantime, in order to avoid the confusion with the "Switch to the block editor" prompts. We'll try to land those changes again tomorrow, once https://github.com/Automattic/wp-calypso/pull/34858 is ready to land as well.
