### ISSUE TITLE
Add option to disable deep-linking

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#35129]
As someone who regularly writes and shares ideas on WordPress.com I like to use a combination of the mobile app for iOS and also the WordPress.com website (Calypso). I use the different apps for different purposes but since the introduction of the Gutenberg editor I exclusively write my content in the web app in order to gain from the fullness of what that editor offers. _Unfortunately_ a flow exists which frustrates me by taking me out of where I want to be and into the mobile app when I’m viewing WordPress.com sites.

> This may not be the best place to report this issue because it concerns links on rendered WordPress.com sites but Calypso plays a role in the UX flow that irritates me.

## What’s wrong?

Starting with the recognition that my goal is to write and publish my thoughts I prefer to write in the full Gutenberg editor available at WordPress.com. I operate within the mobile Safari browser.

 - Login to WordPress.com
 - Write some content in the editor, publish, etc…
 - View the rendered view of a post I published and notice something that I want to change.
 - Click on the edit icon

![9B05741D-35F2-41ED-839C-7BCA5D199D9A](https://user-images.githubusercontent.com/5431237/62429450-99fec780-b6c3-11e9-9ba9-d7e7cfbb81d2.jpeg)

Instead of navigating me to my WordPress.com post editor this opens the mobile app without my consent and without any way to prevent it. I expect the link to take me to the editing flow I choose but instead it closes me out of the application I was using and opens one I don’t want.

## What would be courteous?

Never for any application, let alone for WordPress.com, have I _ever_ wanted my mobile device to follow deep links. They generally seem to do what I don’t want them to do and they generally mess up the context and focus I had before they usurped my flow.

I have scoured the settings and failed to find a setting to disable them so **it would be nice to offer a toggle that would control the global rendering of deep links**. That is, I want to be able to go to **Me** > **Account Settings** > **Link into mobile apps** and disable that feature/bug. When I view a site on WordPress.com then all links should be normal HTTP URLs and not trigger unwanted external events on my device.

The only alternative I know of is to uninstall the mobile app and then I’ll miss out on what I like from it.

**Comment by rachelmcr** [comment]
@elibud @frosty I think you'll both be interested in this one.

**Comment by frosty** [comment]
@dmsnell Thanks for reporting this! There's a way built into iOS that you can disable this yourself, but Apple doesn't do a great job at making it obvious:

* In Safari, tap and hold on the Edit link. I couldn't get it to work on the icon in the bottom toolbar, but I could on the edit link in my post header. You'll see a menu like this:

![IMG_5322](https://user-images.githubusercontent.com/4780/62859766-fa11f100-bcf5-11e9-9f3a-f1eeec430c3d.PNG)

* Tap Open.
* The link should open in Safari. Now, whenever you navigate to one of these links, it should open in Safari instead of the app, effectively disabling those deep links.
* To restore the previous behaviour, tap and hold and choose **Open in "WordPress".**

**Comment by dmsnell** [comment]
@frosty you always have been and always will be my hero. This worked like a charm and now I’m going to use that trick for other apps and their deep links too.

A++
