### ISSUE TITLE
FSE: Full width images in the header do not translate to full page view

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35260]
If I add an image in the header editing view, and then set it to full width:

<img width="1301" alt="Screen Shot 2019-08-08 at 2 49 16 PM" src="https://user-images.githubusercontent.com/1464705/62740160-da27b800-b9eb-11e9-9b8e-680d1ab17017.png">

Then I go back to the page editing view, the image is not full width in the header template block:

<img width="985" alt="Screen Shot 2019-08-08 at 2 51 31 PM" src="https://user-images.githubusercontent.com/1464705/62740215-080cfc80-b9ec-11e9-81e2-0af602fb3ff0.png">

**Comment by apeatling** [comment]
It is also not full width in the front end at larger viewport widths:

<img width="1173" alt="Screen Shot 2019-08-08 at 2 53 15 PM" src="https://user-images.githubusercontent.com/1464705/62740296-4f938880-b9ec-11e9-826e-00ea2079a7d4.png">

**Comment by noahtallen** [comment]
🤔 The editor issue might be because when the theme targets full width blocks, it expects them to be in a container the same size as the normal post content area, and the header is full width already. Those are different widths so it's probably a bit borked. We fixed this for the post content area by making post content area the same width as its container without having to change any of the (very weird) margins used to make block spacing work correctly. We'll have to come up with another solution for the header since we want the block to be full width in itself. I think it's sort of about making a full width block nested in a full width block work correctly style-wise.

My guess is that the frontend is because the existing theme styles do not give the header area the right alignment classes it gives to the block-based content area.
