### ISSUE TITLE
FSE: add monitoring [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35396]
Let's add error monitoring on WordPress.com

In particular let's pay attention to:
- Template Population Failures https://github.com/Automattic/wp-calypso/issues/35077
- Unexpected thrown Errors on the Client (not necessarily a blocker but would be nice to have before the release)

(Anything else we can think of)

**Comment by vindl** [comment]
> Template Population Failures

For this I think it would be good to add action hooks in the FSE plugin, along the lines of `before_template_data_population`, `on_template_data_population_failure`, `on_template_data_population_success` or similar, and hook Dotcom specific tracking in our mu-plugin loader.

**Comment by glendaviesnz** [comment]
> * Unexpected thrown Errors on the Client (not necessarily a blocker but would be nice to have before the release)

Calypso has a module for capturing window.onerror and logging to API - https://github.com/Automattic/wp-calypso/tree/master/client/lib/catch-js-errors, and it looks like it is enabled on horizon and prod - https://github.com/Automattic/wp-calypso/blob/master/client/boot/common.js#L276 & https://github.com/Automattic/wp-calypso/blob/master/config/production.json#L22  - filtering out from the logs what might be FSE specific could be the issue

**Comment by noahtallen** [comment]
I'll take a look at making sure gutenframe errors are logged

**Comment by noahtallen** [comment]
> we can use the explicit log

This might be wacky since the logger isn't defined or set up in FSE, just in the Calypso app. So to use it, we'd probably have to create our own logger instance and initialize everything.

For now, I put up a PR which pipes uncaught errors in Gutenframe back to Calypso to use that logging mechanism, and it seems to be working fine :) btw this is just catching `window.onerror` events, which is also what Calypso is doing. Is that all we need for client logging?

**Comment by noahtallen** [comment]
- [x] Template Population Failures (done in #35077, #35961)
- [x] Unexpected thrown Errors on the Client (done in #36345)

Closing since we've covered the main blockers here :)
