### ISSUE TITLE
FSE: Removing Customize from My Sites sidebar makes the singular Themes menu item feel strange under Design.

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35418]
Via @ianstewart 

If we're removing Customizer from FSE new-user flows we should probably tackle the lone Themes menu item under Design.

Moving it up to Site makes sense but may encourage theme-switching with few themes supporting it. Perhaps we can re-purpose the "Beginner" label in the theme showcase for Themes in this test. It would be in no way ideal but perhaps limiting the Beginner label to supported themes.

**Comment by noahtallen** [comment]
> limiting the Beginner label to supported themes

I guess since we only support Modern Business at the moment, what action should we take on this?

**Comment by gwwar** [comment]
I'd recommend keeping the customize link visible with the same placement, but dropping folks into the FSE home page editor

I'm open into seeing what folks think.

**Comment by shaunandrews** [comment]
If we want to remove the customize link, I think we could move the Themes link down into Tools, rather than into Site:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/191598/63458929-ab650500-c421-11e9-81ab-08d1576b61a8.png">

**Comment by apeatling** [comment]
I think this issue should be addressed after the 10% test.

**Comment by noahtallen** [comment]
Can I get a confirmation on the approach - are we going to move themes under tools when FSE is active?

**Comment by apeatling** [comment]
/cc @shaunandrews 

Also adding a comment I made in Slack:

I’m not sure about moving themes to tools — we already get very few theme switches, this is burying it even further. I wonder if there is a grouping that makes sense for themes and plugins to be together?

**Comment by shaunandrews** [comment]
I suggested moving it to Tools specifically to _hide_ it a little more. Considering FSE as the (hopeful) default for new users, I think switching themes could be chaotic as FSE relies on Maywood.

Otherwise, I'm not sure what label we'd use for a group consisting of Themes and Plugins. We already have such generic group labels like Tools and Manage that I'd be hard pressed to come up with another one.

That said, if we key the placement of the Themes menu item based on the availability of FSE we open the likely hood of users switching their theme and having their sidebar change slightly. This could be a little confusing.

**Comment by noahtallen** [comment]
> based on the availability of FSE

Ah, this is a very good point. On other sites, the themes item would be in a different place.

> specifically to hide it a little more

This also makes very good sense since we don't support other themes yet.

Considering both approaches make sense... I'm not sure. I think _eventually_ it would make sense to put theme selection somewhere closer to Gutenberg and the FSE editor, but that's a long way down the road :)

**Comment by apeatling** [comment]
My vote is we leave this as-is for now. If we move it, it's going to change location if the user does switch themes.

**Comment by noahtallen** [comment]
feel free to re-open if we want to revisit this :)
