### ISSUE TITLE
FSE: It's difficult to understand how to edit the site tagline. 

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35421]
Via @ianstewart

I wasn't able to edit the "Site Description" text with a double-click followed by typing, unlike almost all other text on the screen.

**Comment by noahtallen** [comment]
I was unable to reproduce this bug in the current version - though sometimes the "plus" icon for adding a block overlays the bottom part of the description. We also added more actionable text and a clearer UI in https://github.com/Automattic/wp-calypso/pull/35364, which should help people understand how to edit it better!

**Comment by glendaviesnz** [comment]
probably is related to Add Block button as this is also noted here - https://dotcom.wordpress.com/2019/08/15/call-for-testing-full-site-editing/#comment-42734 - will take a look and see if we can move placement of this

**Comment by glendaviesnz** [comment]
Part of the fix at https://github.com/Automattic/themes/pull/1269 which moves the add block button to the right to stop it conflicting with trying to select the centred text (couldn't see any other way around this).

Will take a look at the double click issue separately.

**Comment by glendaviesnz** [comment]
@apeatling Have spent quite a bit of time looking at this double click to select issue. The problem is that double click to select and start typing only works if you are in the text area and have the 'text' cursor:

<img width="20" alt="Screen Shot 2019-08-16 at 4 01 35 PM" src="https://user-images.githubusercontent.com/3629020/63142802-674bbc00-c03f-11e9-85d2-ec75cd6d210e.png">

This is the same as with all the other blocks - eg. in the paragraph block if you double click at the edges of the block where you have the pointer cursor instead of text cursor it doesn't work either.

The problem we have is that in order to get the layout matching the frontend we have wound back the margins and text area widths, so in the Site Title and Site Description blocks there is very little surface area where you get the text cursor.

Not sure on the best way to solve this issue. Will ponder it over the weekend, and maybe someone else on the team may have some ideas tomorrow.

**Comment by carinapilar** [comment]
I was able to replicate this before having an image set on that next Image block. As shown on this screencast:

![SiteDescription](https://user-images.githubusercontent.com/16104522/63266075-78761200-c265-11e9-8564-0ff0b68c0e30.gif)

**Comment by noahtallen** [comment]
I wonder if some of this will be helped by https://github.com/Automattic/wp-calypso/pull/35387...

**Comment by Copons** [comment]
As already mentioned #35387 will fix this by restoring the original blocks margin, leaving enough space for the insert button (and hover area) which was covering the previous blocks.

![Aug-20-2019 12-24-50](https://user-images.githubusercontent.com/2070010/63343458-e265e880-c345-11e9-875d-52798b7d4b8e.gif)

cc @ianstewart @carinapilar
