### ISSUE TITLE
FSE: Switch Pages when selecting a page in the nav menu

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35439]
From Aadil:

On the home page, I don’t understand why I can’t click on the titles in my nav bar - e.g. click on ‘About’ and go to that page and edit it?

I just get jammed with the ‘Edit Header’ menu which is not what I am looking to do

**Comment by apeatling** [comment]
This is a partial duplicate of https://github.com/Automattic/wp-calypso/issues/35177

It seems as though we could make the links clickable quite easily? Making sure there was a warning about leaving the page if there were unsaved edits.

If this is not easy we should punt to the next version.

**Comment by noahtallen** [comment]
I think the challenge would be that our header blocks are inside a `[Disabled](https://github.com/WordPress/gutenberg/blob/5b81cbc66c5d52f9603f77a60ec7864150173dd0/packages/components/src/disabled/README.md)` component, which is what prevents us from interacting with the block UI. That block basically disables all pointer interaction. 

If we got rid of that wrapper, then we would be able to interact with and edit the blocks in the template area, but saving the changes would not do anything. (It also means you can select those blocks, which would mean you can't get into the selected state in order to see the edit header button.

We'd also have to rework the edit header UI since using a hover/select interaction would cover up the nav menu and you wouldn't be able to interact with it.

Maybe I'm wrong, but I think this would be a high effort task, but definitely a good UX improvement! :)

**Comment by gwwar** [comment]
@apeatling can maybe gather navigation feedback and work with @shaunandrews on the most important needed functionality next?

Going to remove from this sprint to let folks think this through.

**Comment by shaunandrews** [comment]
Ignoring any technical limitations behind interacting with the disabled `template_part`, I don't think this makes much sense until we can remove the need to have multiple instances of the editor. Being able to interact with a single block — in a very unique way — while having to load the `template_part` to do anything else is just asking for confused customers.

As @noahtallen mentions above, this exception to the UI interaction will conflict with the way we present the "edit header" button and associated messaging on hover and focus of the `template_part`.

**Comment by vindl** [comment]
Punted since it will be solved in Core navigation block (https://github.com/Automattic/Dotcom-roadmap/issues/51).
