### ISSUE TITLE
Page Templates: Make it easier for theme developers to publish global page template edits

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35449]
Theme developers want to be able to edit the page templates that show up in the template picker for users. These are global templates that show up regardless of theme.

Editing currently means going through a JSON file, and is laborious. There needs to be a tool, or exposure of the template so they can be edited. I think this would ideally just be in Gutenberg.

**Comment by iamtakashi** [comment]
Just to clarify, it is easy to edit or add templates on the master template site since it's Gutenberg editor. But, the steps after that — updating JSON snapshot file with wpcli and generating a linguine file for translation are a bit of a pain for designers :) 

I'm not sure if this is still the case, but I remember that I needed to remove manually some references to images in the generated JSON file for Headstart before deploying the file. And that added a further complication to the process, and it wasn't very clear to me.

I appreciate the detailed instruction in the field guide, but I thought it'd be great if it could be done in a MC with UI that's a little more designer friendly process.

This was a more of a suggestion, and we'll understand if you decide to keep the process as it is.

**Comment by apeatling** [comment]
Thanks for the clarification @iamtakashi!
