### ISSUE TITLE
FSE: CoBlocks Masonry block design broken when added to a header/footer without adding to content

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35509]
When adding the `Masonry` block from `CoBlocks` to the header or footer region, without adding a copy to the `Content` section, the design isn't as expected - the images appear in a long vertical chain instead of the actual masonry layout.

![Screenshot 2019-08-17 at 16 34 46](https://user-images.githubusercontent.com/18581859/63210540-481b6000-c10d-11e9-85a2-e62eefd134ec.png)

On the above image, 

- The first masonry is from the header region.
- The second masonry is from the footer region.
- There is no block on the content region.

When the block is added to the `Content` section, the same `Masonry` block on header and footer show the expected design again.

![Screenshot 2019-08-17 at 16 35 49](https://user-images.githubusercontent.com/18581859/63210522-1a361b80-c10d-11e9-8f71-80039d67f80b.png)

On the above image, 

- The first masonry is on the header.
- The second masonry is on the content region.
- The third masonry is on the footer region.

**Comment by apeatling** [comment]
@kwight @mmtr The CoBlocks styles should be getting picked up here, is this an issue with that, or is it the theme that is breaking the styles?

**Comment by mmtr** [comment]
I think this is caused because the frontend styles are conditionally loaded: https://github.com/godaddy/coblocks/blob/06f434a16cb8d695e2edd7ab2514b3e31160567f/includes/class-coblocks-block-assets.php#L151-L159

Likely, the `has_block` call is checking only the post content, and not the header/footer templates.

**Comment by mmtr** [comment]
The ideal solution for this would be to extend the `has_block` function, so the FSE plugin can define new conditions checking the content of the header/footer templates. Unfortunately, there are no filters at the moment allowing that.

We could implement a workaround in WP.com that loads the CoBlocks frontend styles when the blocks are found in the header or footer, but the same fix should be also implemented in `wpcomsh` in order to cover AT sites as well.

**Comment by kwight** [comment]
> We could implement a workaround in WP.com that loads the CoBlocks frontend styles when the blocks are found in the header or footer, but the same fix should be also implemented in wpcomsh in order to cover AT sites as well.

We could put our own `wp_enqueue_script` call in FSE (`./coblocks`?) that just handles `has_block` functionality for our header and footer content. The existing CoBlocks `frontend_scripts` method handles everything else fine, so no need to mess with what isn't broken.

**Comment by kwight** [comment]
We may need a more generic solution to be able to handle third-party blocks from other plugins that users may add to FSE headers and footers.

**Comment by mmtr** [comment]
I performed an audit searching for other `has_block` usages in our plugins that could to similar issues to this one. 

I found that Jetpack is using it ([#](https://github.com/Automattic/jetpack/blob/89a9af96b669e2e5a2ed47d3f3e07c804d6e0dd0/modules/carousel/jetpack-carousel.php#L221)), but in this case we are passing an explicit content to the function returned by the `the_content` filter ([#](https://github.com/Automattic/jetpack/blob/89a9af96b669e2e5a2ed47d3f3e07c804d6e0dd0/modules/carousel/jetpack-carousel.php#L80)). 

We're applying that filter to the content of the header/footer templates (https://github.com/Automattic/wp-calypso/pull/35591), so it should be safe to use the Jetpack blocks on the header/footer templates.

**Comment by mmtr** [comment]
After analyzing this a bit further to see if we can come up with a more generic solution, I realized that `has_block` actually checks the header and footer, because the FSE plugin [merges the templates with the post content](https://github.com/Automattic/wp-calypso/blob/f9fc9026f16445c152eca09b8a7629f0550949ec/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L56). The problem is that the [template content doesn't contain the markup of the inner blocks](get_page_template_content), so `has_block` cannot find them.

**Comment by mmtr** [comment]
I don't think we can build a generic solution without Core making changes to `has_block`, so a specific fix for CoBlocks like https://github.com/Automattic/wp-calypso/pull/35641 seems the only possible workaround now.
