### ISSUE TITLE
Import in Signup: Missing site title on importer screen when signing up with a non-URL based importer

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#35582]
When going through the Import in Signup flow and picking a non-URL based importer, the site title is left empty, which results in it missing from the text on the importer screen:

<img width="744" alt="ScreenCapture at Mon Aug 19 16:14:50 EDT 2019" src="https://user-images.githubusercontent.com/2098816/63296466-22bd5c00-c29d-11e9-9385-52f46f948f7d.png">

One solution would be to put the site URL there if title is unavailable. Another would be to reword the text to remove the site title from the copy.

**Comment by jonathansadowski** [comment]
Appears that `siteTitle` isn't working correct in any case. It only doesn't appear to be a problem for url-based importers because it's not shown inline, but if you look at the sidebar, it's still incorrect, despite the fact that we gathered the title in signup.

![image](https://user-images.githubusercontent.com/363749/63444835-f3bdfc00-c3fc-11e9-85c0-bc0a6c206c08.png)

For some reason, the actual API call to create the site uses [some other part of the state tree](https://github.com/Automattic/wp-calypso/blob/df29d816f4524a4dbc18b669e1d86c0c8106fdc7/client/lib/signup/step-actions.js#L144) and not the signup dependency store -- and we're not setting the title correctly in the state tree.

I'll work on a PR to set the title correctly.
