### ISSUE TITLE
Reblog button does not show unless Likes are also enabled

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#35720]
#### Steps to reproduce
1. Start at My Site → Tools → Marketing → Sharing Buttons
2. Enable Reblogs, but keep the Like button off like so: https://cld.wthms.co/8Ea635
3. Save changes
4. View your posts

#### What I expected
I expected the reblog button to show after I enabled it.

#### What happened instead
The reblog button does not show. If you enable Likes as well, then the Reblog and Like buttons show. Without Likes enabled, the Reblog button does not show at all.

#### Browser / OS version
Chrome Chrome 76.0.3809.1 / Windows 10 (64-bit)

#### Context / Source
#14750035-hc

Seen on at least two themes (Ryu and Twenty Nineteen), so does not seem theme-dependent.

**Comment by donalirl** [comment]
Follow-up required in #2294808-zen

**Comment by lancewillett** [comment]
I think I remember seeing this already reported in WP.com Trac under 7550-wpcom — at that time we decided not to fix it because we had plans to retire Reblogs due to lack of ownership with teams working on other features.

In the same spirit I'm going to close this one, but will add a link to it in the main bug report for future reference.

Thank you @donalirl for the report.
