### ISSUE TITLE
Sidebar: Home icon missing in Checklist/Home item

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#35849]
#### Steps to reproduce
1. Create a new site (can use an existing one, but it needs to be relatively new)
2. Once the calypso sidebar is visible take a look at the Home/Checklist link

#### What I expected
The Home/Checklist link has the home icon (it always displays home #35635)

#### What happened instead
**When `customerHomePage=show`**
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1500769/63895983-e16b4000-ca44-11e9-8f1e-9ae5c811231b.png">

**When `customerHomePage=hide`**
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1500769/63896001-ec25d500-ca44-11e9-978e-acd56fb39f1a.png">

#### Browser / OS version
FF

#### Context / Source
p1567029100006200-slack-CCS1W9QVA

**Comment by p-jackson** [comment]
Discovered that this was introduced in 5ca3d005c6e8fe0ac16f220122762cebdb49fa15 through testing. Don't know what part of the refactor broke it though.

**Comment by spen** [comment]
Another development - this seems to be fixed with #35586.

For posterity though, it looks like the `customerHome` method of `sidebar/siderbar.jsx` is a good place to start for similar areas.
Also, when I had `5ca3d005c6` checked out, I looked at the markup for the (missing) icon - here's what I found:
<img width="470" alt="Screenshot 2019-08-29 at 14 30 55" src="https://user-images.githubusercontent.com/4335450/63944784-1c339f00-ca6a-11e9-95aa-ba126e1db1a6.png">
I noticed that it uses a `<use>` tag... I get the feeling that the target for the `use` tag wasn't available for some reason before #35586.

**Comment by eliorivero** [comment]
Even though #35586 is merged, the icon is still missing. I'm seeing this on wpcalypso

<img width="331" alt="Screen Shot 2019-08-29 at 14 14 44" src="https://user-images.githubusercontent.com/1041600/63962667-a6c7ce80-ca69-11e9-83fb-32fd6cacb15f.png">

**Comment by pablinos** [comment]
Yes, it looks like the icon is missing from:

`packages/material-design-icons/svg-sprite/material-icons.svg`

Maybe something went wrong as that was regenerated? The `packages/material-design-icons/src/action/outline-home-24px.svg` file is still there.
