### ISSUE TITLE
FSE: use a8c_disable_full_site_editing to indicate site eligibility

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35852]
Let's make sure that usages of `a8c_disable_full_site_editing` only handle site eligibility, not if FSE flows are active.

Please also take a little bit of time to evaluate how risky it'd be to rename and have that work correctly on Simple, Atomic and Jetpack `a8c_disable_full_site_editing ` to `a8c_is_full_site_editing_eligible`.

**Comment by noahtallen** [comment]
Checking usage on wpcom yields these results:
1. _browser/trunk/wp-content/mu-plugins/full-site-editing/class-full-site-editing.php#L26-wpcom_: Here, it is used only to check the blog sticker for eligibility, as well as checking VIP. There is some extra code for handling the API requests, which looks great. ✅
2. _browser/trunk/wp-content/mu-plugins/full-site-editing/class-full-site-editing.php#L203-wpcom_: Here, it is used to force-load FSE when creating a new site. It re-calls the loader function and adds its own action which never disables the plugin (which is safe because it comes from the AB test route). I do think we could remove this call since the loader function already calls the instance above which is in the same file. Unless something wacky happens with the contexts and whatnot, I don't think we need to add a new action here. ⚠️
3. _browser/trunk/public.api/rest/sal/class.json-api-site-jetpack-shadow.php#L584-wpcom_: Here, the function tries to force-load FSE in the API context by temporarily overriding the eligibility see if it can find the "is supported theme" method. I'm not sure why we need to load all of FSE here, and I think most of this could/should be switched to [use this check](https://github.com/Automattic/wp-calypso/issues/35853). ⚠️
4. Now also in wpcomsh, we specifically use it to set the eligibility based on the site option. ✅ 

If it's plausible to remove the checks in 2 and 3, I think it would be very straightforward to switch the filter out for `a8c_is_full_site_editing_eligible` so long as we also inverse the logic where it's used.

**Comment by noahtallen** [comment]
I do think we'd have to keep the old name around if we transition to a new name. For example, if we change the name in wpcomsh, the plugin would suddenly activate for all atomic sites since the plugin hasn't been synced.

**Comment by vindl** [comment]
> I do think we'd have to keep the old name around if we transition to a new name. For example, if we change the name in wpcomsh, the plugin would suddenly activate for all atomic sites since the plugin hasn't been synced.

We can pre-emptively add the new filter to wpcomsh alongside the old one, and update the plugin after that?

**Comment by vindl** [comment]
Let's circle back to this when we start separating projects into separate plugins.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
