### ISSUE TITLE
Sidebar: Visual hierarchy of menus is unclear

### ISSUE THREAD

**Issue by lcollette** [Automattic/wp-calypso#35937]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checklist/
2. Look at the sidebar 

#### What I expected
For menu category headings to be visually discernable from their children. 

#### What happened instead
The menu headings are a lighter gray, appearing as quasi-siblings to their children. 

#### Screenshot / Video

![Screen Shot 2019-09-02 at 11 06 01 AM](https://user-images.githubusercontent.com/181733/64129849-8ce10100-cd73-11e9-8b01-004b5c5bd1c3.png)

#### Context / Source

This tiny issue came out of the amazing work done as part of the CSS Refactor in #34051.

**Comment by lcollette** [comment]
After chatting with @shaunandrews, sounds like the intent was to differentiate the expandable headings (not links) from links. 

I wonder if we might be able to do this while still maintaining visual hierarchy.

**Comment by danhauk** [comment]
One possible solution might be to employ a vertical rule and/or indentation. It adds a bit of visual clutter but makes it more clear these are children of the headings rather than siblings.

---

**Vertical rule only**

<img width="273" alt="Screen Shot 2019-10-09 at 10 56 13 AM" src="https://user-images.githubusercontent.com/448298/66493825-b5e86600-ea84-11e9-8250-9224610f9177.png">

---

**Vertical rule with indentation**

<img width="256" alt="image" src="https://user-images.githubusercontent.com/448298/66494023-fea01f00-ea84-11e9-9be0-45efc0232c05.png">

---

**Thin vertical rule with indentation**

<img width="256" alt="image" src="https://user-images.githubusercontent.com/448298/66494062-124b8580-ea85-11e9-8bc6-fc037495430f.png">

---

An alternative is also just indenting the children links without the vertical rule, but they don't feel anchored to anything:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/448298/66493710-86395e00-ea84-11e9-8abe-33b40a3d8dac.png">

**Comment by lcollette** [comment]
I like this direction, @danhauk! Did you try a version with only the thin vertical line? Which option do you think is best?

**Comment by danhauk** [comment]
I actually didn't try a version with only the thin vertical line. I'm leaning toward the thin line and indentation as the best option. It still adds that affordance without as much visual weight. And with the indentation it's easier to scan.
