### ISSUE TITLE
Full Site Editing: Infinite Loaders on Header and Footer

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35950]
Currently in prod we're seeing infinite headers/footers loading for eligible sites, on non-supported themes. Let's see what fix caused the regression.

<img width="1665" alt="Screen Shot 2019-09-03 at 6 36 48 PM" src="https://user-images.githubusercontent.com/1270189/64219324-e4699480-ce79-11e9-97cf-f8f5d536f521.png">

There may be another minor case where we currently depend on the `after_switch_theme` action to populate default data. https://github.com/Automattic/wp-calypso/blob/6c41229ff6a4953ab82441e995a3bfecc4e663c7/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L64

Please investigate if it's possible to get infinite Header/Footer loaders on FSE flows with the following steps:

- With an FSE enabled site, activate Maywood
- Then apply a code patch that whitelists support for Maywood

Or alternatively:
- With an non-fse eligible site, active a supported FSE theme
- Mark the site as FSE eligible

**Comment by mattwiebe** [comment]
`after_switch_theme` only runs on the *next request* after the switch happens, which might be a source of trouble here

**Comment by glendaviesnz** [comment]
This is a bit of a nasty chicken and egg situation. From what I can see we have never had anything that switch off FSE plugin based on a non-supported theme - I remember seeing it a couple of weeks ago, and I did add a check for this in on of my `merge_template_and_post` changes last week, but this is really to late in the piece as this method shouldn't even run if theme doesn't support FSE, which is why I think @mattwiebe took this out in his update to these changes.

So it seems like we really need some way of making the `a8c_disable_full_site_editing` return true if the current theme does not support fse. This is where the chicken and egg problem comes in as currently `is_fse_active_for_theme` calls `is_fse_disabled` but to disable the plugin at load time it needs to happen the other way around.

A very rough prototype to change to prompt discussion is up at D32454-code - this change on top of @gwwar's patch D32356-code disables the plugin when theme is not supported and stops the infinite spinners on non-supported themes.
