### ISSUE TITLE
Simple Payments: Block does not render in published view with Gutenberg 6.5

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36194]
This was found by E2E tests https://github.com/Automattic/wp-calypso/pull/36142 and confirmed by @mmtr 

The Simple Payments block is currently broken on Horizon. It can be inserted and saved, but it is not rendered on the front-end.

Let's investigate and either fix on our end, or report the related issue if we found a bug for the core project.

**Comment by glendaviesnz** [comment]
Seems to be because the block saveProduct() method is calling saveEntityRecord and this is returning null and so no productId is set and the block does not then save the required short code `[simple-payment id="{productId}"]` to the post content - with the short code missing nothing is rendered on the frontend.

**Comment by glendaviesnz** [comment]
Fix for this was merged in https://github.com/WordPress/gutenberg/pull/17492
