### ISSUE TITLE
G Suite: Error when mapped domain is not configured

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#36211]
#### Steps to reproduce
1. On a Simple Site without a custom domain (site should only have the default *.wordpress.com domain), visit `/domains/manage/{site}`
2. Add a mapped domain, but do not configure the domain's name servers to point to WordPress.com
3. Visit `/email/{site}` and select "Add G Suite"
4. Complete the GSuite setup by adding an email address and name, then click "Continue"
#### What happened

G Suite is added to my cart, but then errors because the mapped domain is not configured

<img width="1311" alt="Screen Shot 2019-09-18 at 14 25 34" src="https://user-images.githubusercontent.com/1699996/65181157-0ccdc300-da24-11e9-8e00-0960dd7cca7c.png">

#### What I expected

It's more about what I didn't expect--since I am not yet able to use G Suite email with my mapped domain (since it's not configured), I do not expect to be able to complete G Suite setup. Instead I should see a notice that I first need to configure my mapped domain. Similar to what we show users before they've added a custom domain on the `/email/{site}` page.

<img width="914" alt="Screen Shot 2019-09-20 at 10 49 19" src="https://user-images.githubusercontent.com/1699996/65340710-6f45d100-db94-11e9-952d-4d755c0b0d16.png">

#### Browser / OS version

Chrome/macOS

#### Context / Source

Seen while testing work on the Customer Home in #36030

**Comment by stephanethomas** [comment]
I believe this has been fixed now - we no longer offer G Suite if the domain does not use WordPress.com name servers. We still display the Empty page you've mentioned in your description, which is totally confusing and should instead invite users to update name servers in order to add emails:

<img width="914" alt="Screen Shot 2019-09-20 at 10 49 19" src="https://user-images.githubusercontent.com/1699996/65340710-6f45d100-db94-11e9-952d-4d755c0b0d16.png">

We're already tracking this issue in our Trello board though.
