### ISSUE TITLE
Editor: Markdown - inline code contents stripped

### ISSUE THREAD

**Issue by shawnajean** [Automattic/wp-calypso#3623]
#### Steps to reproduce
1. Starting in the editor - http://wordpress.com/post
2. Paste this markdown in the HTML editor:

```This works, as NuGet will use the more 
specific `<group targetFramework="XamariniOS1.0">` for Xamarin.iOS,
but fall back to the empty `<group>` for all other platforms.```

3. Publish the post.
4. The post does not include the parts within the backticks. And if you close & reopen the editor, the text is stripped out.

<img width="564" alt="screen shot 2016-02-26 at 6 38 33 p" src="https://cloud.githubusercontent.com/assets/775884/13369255/428fe15c-dcb8-11e5-994f-2cf3cf6a5db5.png">

<img width="776" alt="screen shot 2016-02-26 at 6 38 16 p" src="https://cloud.githubusercontent.com/assets/775884/13369256/4640788e-dcb8-11e5-9e30-6adaa6d43459.png">

I believe this is getting stripped out by our 'invalid HTML' corrections, but I'm not 100% sure.

Test post: https://testsjr1.wordpress.com/2016/02/26/1499/
Ticket: 2551051-t

**Comment by hoverduck** [comment]
21Apr16 Bug Scrub

I've confirmed this is still an issue, but I'm tempted to close it to either #1426 or #1109 which document similar issues.  But it is a different flavor of the problem, so I think it's worth leaving open for now.

**Comment by designsimply** [comment]
#bug-scrub

I re-tested but got a different result. Instead of being stripped, the code was html-encoded:

![screen shot 2016-07-20 at wed jul 20 1 26 49 pm](https://cloud.githubusercontent.com/assets/1119271/17000155/754e4be6-4e7e-11e6-885d-a5f9c46797b8.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10138 using Safari 9.1 on Mac OS X 10.11.5</sup>

![screen shot 2016-07-20 at wed jul 20 1 26 57 pm](https://cloud.githubusercontent.com/assets/1119271/17000171/83f49f6a-4e7e-11e6-9aad-4b72b350da3d.png)
<sup>Seen at https://design5279.wordpress.com/2016/07/21/testing-3623/ using Safari 9.1 on Mac OS X 10.11.5</sup>

Sample content:

```
This is some random code surrounded with backticks: `<group targetFramework="XamariniOS1.0">`

This is some valid html code surrounded with backticks: `<a href="https://wordpress.com/">WordPress.com</a>`

This works, as NuGet will use the more specific `<group targetFramework="XamariniOS1.0">` for Xamarin.iOS, but fall back to the empty `<group>` for all other platforms.
```

**Comment by lancewillett** [comment]
Testing this today, pasting the content into the Visual editor works just fine — the tags aren't stripped out and are visible in the published post.

![screen shot 2016-10-17 at 10 48 07](https://cloud.githubusercontent.com/assets/66797/19448557/33f73e2c-9457-11e6-8f0e-d4578badb005.png)

![screen shot 2016-10-17 at 10 48 04](https://cloud.githubusercontent.com/assets/66797/19448559/3728cdae-9457-11e6-9239-96fa9f0b7821.png)

However, if you paste the content — then switch to HTML editor, the content within the backticks is removed. I think that's an OK tradeoff.
