### ISSUE TITLE
(3P) SPT: Re implement template selector without a Modal

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#36232]
Includes adding a new class that positions the div absolutely in the editor.

See https://github.com/Automattic/wp-calypso/issues/35620

**Comment by getdave** [comment]
Note that I'm partially tackling this in https://github.com/Automattic/wp-calypso/issues/36323

**Comment by getdave** [comment]
I'm actually not sure this is a good idea. We are still overlaying the Editor and so we need the a11y affordances that are baked into the Modal. Otherwise we're going to end up having to re-do the a11y of the modal on our custom implementation. 

I question whether it's worth the effort given that we're going to ditch this approach anyway.

**Comment by obenland** [comment]
Yeah, that's a good point. Let's keep it as is.
