### ISSUE TITLE
Navigation: Store sidebar link redirects to stats on Simple Business site

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#36247]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/example.com (where example.com is a Simple Business plan site)
2. Click the Store sidebar link
3. Briefly see https://wordpress.com/store/example.com, which then redirects to https://wordpress.com/stats/day

#### What I expected
To see https://wordpress.com/store/example.com and be prompted to install WooCommerce on a Simple site

#### What happened instead
I was redirected to the All Sites stats page

#### Browser / OS version
Chrome 76, unproxied

#### Context / Source
#manual-testing

cc @jffng as this looks related to https://github.com/Automattic/wp-calypso/pull/33992

**Comment by lancewillett** [comment]
@jffng As a note for communication: changes to the Calypso sidebar navigation will probably impact WP.com customer support since it's a visible change. Could you please keep in mind communicating these changes in Slack/P2 with WP.com Happiness teams? (We have good info on this in Field Guide, and I'm happy to also help.)

**Comment by jffng** [comment]
Taking a look at the bug now. @lancewillett noted! Thank you for the heads up.

Given that it looks like the change isn't behaving as expected and it hasn't been messaged properly to Happiness, maybe we roll this back for now.

**Comment by jffng** [comment]
Closing this as #36249 reverted the change.
