### ISSUE TITLE
Customizer: CSS UI is different in atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36321]
Patch to review: D65448-code

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Go to Design > Customize > CSS

#### What I expected
I expected both simple and atomic sites to show the same UI in the CSS customizer.

#### What happened instead
instructional text above the CSS box appears on atomic site, not on simple site. Also, the note in the CSS editor box ("Welcome to Custom CSS!") does not show in the atomic site, only on simple

#### Screenshot / Video
Screenshot Simple 
![Design _ Customize  - Simple Site - top of CSS](https://user-images.githubusercontent.com/1398304/110372387-14f83480-8003-11eb-9d0f-5c522d048f3f.png)

Screenshot Atomic 
<img width="294" alt="Top of Additional CSS " src="https://user-images.githubusercontent.com/1398304/110372391-16c1f800-8003-11eb-8686-0830e35955e8.png">

#manual-testing

**Comment by allilevine** [comment]
I think we should align Simple sites with the Atomic UI in this case, since it's [the core UI](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-wp-customize-manager.php#L5660) and includes directions for screen reader users. We might want to keep the link to WordPress.com support, though.

@jordesign Do you happen to know of any reason to keep the Simple Site CSS UI? This is the change we would make:
Before | After
------ | -----
<img width="339" alt="Screen Shot 2021-08-03 at 4 53 04 PM" src="https://user-images.githubusercontent.com/1689238/128084677-19016477-1b80-4d67-b760-c2e5604824cd.png"> | <img width="348" alt="Screen Shot 2021-08-03 at 4 53 21 PM" src="https://user-images.githubusercontent.com/1689238/128084697-1ef15949-40f6-47ff-a786-c5f5e1c957db.png">

We'd also need to update the support doc: https://wordpress.com/support/editing-css/

**Comment by jordesign** [comment]
I think my only concern would be that the wall-of-text in the core version is potentially a little offputting. But you could maybe argue that is a good thing ;)

In either case - I think it is reasonable (and the best option) to match what core has in place. But +1 to docs needing to be updated (@donalirl) and this is something we'd want to give Happiness a quick Heads Up about when it is launching.

**Comment by allilevine** [comment]
I've opened a patch to make the UI changes for Simple sites here: D65448-code

**Comment by allilevine** [comment]
> In either case - I think it is reasonable (and the best option) to match what core has in place. But +1 to docs needing to be updated (@donalirl) and this is something we'd want to give Happiness a quick Heads Up about when it is launching.

@jordesign The patch was accepted 🎉 what timeline should we follow for giving Happiness a heads up, launching, and updating the docs?

**Comment by jordesign** [comment]
Thanks @allilevine  - I'll post a heads up to Happiness today - then we can could roll it out on Monday?

**Comment by allilevine** [comment]
I've deployed the patch: r230650-wpcom
But I missed that it required a sync with Jetpack, so I'm keeping this issue open to resolve that. See https://github.com/Automattic/jetpack/pull/20800

**Comment by allilevine** [comment]
Closing because we've aligned the Simple UI with Atomic. We've opened https://github.com/Automattic/wp-calypso/issues/56145 to track actually aligning the implementation of Custom CSS.
