### ISSUE TITLE
Settings: Performance - AMP toggle not available in AT sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36371]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/performance

#### What I expected
I expected both simple and atomic sites to show the same options for AMP.

#### What happened instead
AMP: toggle to turn off on simple site, not in atomic

#### Screenshot / Video
Screenshot Simple --  https://cld.wthms.co/nktex3
Screenshot Atomic -- https://cld.wthms.co/hadqa0

#manual-testing

**Comment by wojtekn** [comment]
We removed AMP support for Simple sites on July 11th, 2022 so this issue is not actual anymore. pdKhl6-lx-p2#comment-368

Simple sites do not include AMP toggle anymore:

![Screen Shot 2022-09-06 at 15 08 56](https://user-images.githubusercontent.com/727413/188644236-833d5221-7f0f-4dfb-ba21-99fcabf8031b.png)

Atomic sites do not include toggle, but AMP can be disabled by deactivating the plugin:

![Screen Shot 2022-09-06 at 15 12 50](https://user-images.githubusercontent.com/727413/188644396-108fd03e-47de-426a-8ee8-6fc648f5a6c9.png)
