### ISSUE TITLE
Hosting: Add Eligibility Warnings Block [5]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36485]
In Phase 2, we'd like Business customers who haven't yet transferred their site to Atomic to be able to see the Hosting Section.

In this issue let's make the Eligibility Warnings Block visible after clicking on "activate". The notice should disappear, and display the Eligibility Warnings block on what features might be lost, or what folks need to do next.

Clicking on activate should also fire a well named tracks event.

https://github.com/Automattic/wp-calypso/tree/235c755d4a5987cc354bd27f75eed1ab34c74722/client/blocks/eligibility-warnings

<img width="633" alt="Screen Shot 2019-10-02 at 4 10 22 PM" src="https://user-images.githubusercontent.com/1270189/66088649-a91dbc80-e530-11e9-9ac8-2f888e8105c9.png">

Eligibility Warnings Block
<img width="734" alt="Screen Shot 2019-10-02 at 4 20 17 PM" src="https://user-images.githubusercontent.com/1270189/66088633-9a370a00-e530-11e9-9b29-917996b3e5f6.png">

cc @apeatling if you'd prefer this to redirect to another page instead like with plugin or theme uploads

**Comment by apeatling** [comment]
If you can do it in place I think that's better. My only concern would be the jumpiness of going from a single line height notice to a multi-line variable height block in its place.

**Comment by kwight** [comment]
I like the idea of an in-place modal more too.

**Comment by gwwar** [comment]
@shaunandrews do you have any preferences here for the approach?

**Comment by shaunandrews** [comment]
The first question I have is around the use of a Banner rather than a notice for the messaging. The Banner's use of a primary Button is more noticeable as an action, but the Notice is overall more attention-grabbing:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/191598/66509411-f7870a00-eaa0-11e9-9d3e-2aacc93575eb.png">

I think a Modal overlay might be appropriate here, rather than page reloads and having to worry about back/forth navigation:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/191598/66509454-12f21500-eaa1-11e9-8279-27a1e22471c5.png">

I am slightly concerned that sometimes you can't actually "Proceed," as it seems the button is often disabled. Its not clear to me what blockers/requirements there might be with this eligibility resolution step.

**Comment by mmtr** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/37983
