### ISSUE TITLE
Domains: Consider removing duplicated "Transfer in progress" message

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36481]
<img width="1082" alt="screencapture-wordpress-domains-manage-calobeetesting06-food-blog-2019-09-11-16_25_43" src="https://user-images.githubusercontent.com/2124984/66088280-8ac3bb00-e548-11e9-8e5f-9708f3e31072.png">

(Similar to #36479)

Is it necessary to include two separate messages that say the same thing? Removing the smaller one reduces visual clutter on the page, since the larger one at the top is unable to be dismissed.

To find this screen:

1. Go to Manage -> Domains.
2. Add a domain and select Use an existing domain
3. Select Transfer a domain to WordPress.com
4. Start the domain transfer process (unlock domain, get auth code from existing registrar)
5. Checkout, if necessary.
6. Go back to Manage -> Domains. You'll see this screen with the transfer notices.

**Comment by klimeryk** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/36479#issuecomment-540527126. I agree they are duplicating each other a bit, but that's also so that it's easier to pin point which domain is in transfer. When it's one/two like this, it's not bad, but more than that (and users love to have similarly named ones...) it gets trickier when the big notice is up there and it refers to one of the domains below. How about moving the big notice inside the list item for the domain? Makes the context much clearer and it's easier to figure out which domain needs what.

**Comment by klimeryk** [comment]
This has been addressed with the domain management revamp 🎉 

<img width="1055" alt="Screenshot 2021-02-09 at 22 35 31" src="https://user-images.githubusercontent.com/3392497/107437610-28f56700-6b27-11eb-96d1-62f471496336.png">
