### ISSUE TITLE
FSE: There is no way in the mobile viewport to go back to the full page edit preview.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36610]
When editing a template part on mobile, I have no way (other that trusting the browser Back button) to get back to the main editor, which may be related to this awkwardness: https://github.com/Automattic/wp-calypso/issues/36342

<img width="390" alt="Screen Shot 2019-10-08 at 10 46 51 AM" src="https://user-images.githubusercontent.com/349751/66421916-9b978500-e9bd-11e9-9b18-d27acb7d1d4c.png">

**Comment by noahtallen** [comment]
This is also an issue on the non-FSE post/page editor (here's a non-FSE post editor screenshot):

<img width="530" alt="Screen Shot 2019-10-08 at 11 52 54 AM" src="https://user-images.githubusercontent.com/6265975/66424277-31351380-e9c2-11e9-9cbb-734f5eb727c6.png">

I think this happens because in core, one would be able to choose between an in-page or full screen layout, whereas we force a full page layout of gutenberg everywhere
