### ISSUE TITLE
Post Tags Bug: Adding an apostrophe to the end of a tag causes tag deletion to delete tags that do not have the apostrophe

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#36620]
#### Steps to reproduce
1. Starting at URL: Create a WordPress.com site
2. Publish some posts with the tag books
3. Accidentally create a second tag - books'
4. Delete books' from the WordPress.com dashboard under Manage - Settings - Writing

#### What I expected
I expected books' with the apostrophe to be deleted.

#### What happened instead
Books without the apostrophe was deleted, which also makes all of your posts tagged with books no longer have that tag. 

This was particularly painful for a user who had thousands of posts and multiple tags with apostrophes at the end. They were trying to clean up their tags list by deleting the empty tags with apostrophes. They now have to re-tag hundreds of those posts after having their tags mistakenly deleted via this bug.

The apostrophed tags can be removed in WP-Admin.

#### Browser / OS version
All of them. 

#### Screenshot / Video
![tags](https://user-images.githubusercontent.com/30731356/66440223-2fca1200-e9e7-11e9-9d8f-d9ee08e7ce35.gif)

#### Context / Source
#reallife #anxiety #anxiety-flow #stresscase #painpoint  #user-report

**Comment by gwwar** [comment]
Verified that this will delete `term` instead of `term'`

**Comment by gwwar** [comment]
Comparing wpcom v1.x and wp/v2, it looks like in this case slugs may collide, sharing the name `test` in this example, where the name may differ. Unfortunately the wpcom API uses the slug instead of the tag ID to perform actions. I'll dig a bit more to see what makes most sense.

We may want to swap this section to using the wp/v2 APIs.

<img width="1075" alt="Screen Shot 2019-10-14 at 1 26 57 PM" src="https://user-images.githubusercontent.com/1270189/66780737-7657ba80-ee86-11e9-856f-e571a25540dc.png">
