### ISSUE TITLE
[Bug] Business plan marked as "Your plan" during signup

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#36712]
## The bug or issue

During the wordpress.com onboarding, on the plan selection screen, the Business column says “Your Plan”, but I’m creating a brand new site and haven’t picked a plan yet: 

https://cloudup.com/cMb-TzSmsIo

p1570838732049500-slack-CCS1W9QVA

## Steps to reproduce

@p-jackson reproduced. Don't know if all these steps are relevant:
- Upgrade an existing site to business plan (was on free)
- Click switch site in sidebar
- Add new site
- Go through sign up, selecting blog as the site type
- Choose a free domain
- For me the plan selector shows the "Your Plan" label

FWIW my "primary" site is on a free plan.

## What I expected

To not see "Your plan" label during signup. It should still be there when looking at the `/plans` page.

## Additional context

As Veselin noted, there's a chance this happened for an existing user with another Business plan site

**Comment by jblz** [comment]
I tried & couldn't reproduce, but I'll share some code links that I inspected along the way:

The "pill" is conditionally rendered here: https://github.com/Automattic/wp-calypso/blob/a41f962165438dc9b7d8567642bf16f936aba88f/client/my-sites/plan-features/header.jsx#L101

**Comment by niranjan-uma-shankar** [comment]
I've seen this bug a few months back, but forgot to report it. This bug is seen when you're on any paid plan site, not just the Business plan. The plan selection step when going through the "Add new site" flow will highlight the site plan that you were last on before entering the flow.

Example: I have an account with sites - one on the Personal plan and the other on Premium.

When I'm on the site having Personal plan, and then go through the "Add new site" flow, the plan selection step looks like this:

<img width="962" alt="Screenshot 2019-10-21 at 2 39 28 PM" src="https://user-images.githubusercontent.com/1269602/67192187-c0a1e400-f410-11e9-83c0-4daf14b62298.png">

When I'm on the site having the Premium plan, and then go through the "Add new site" flow, the plan selection step looks like this:

<img width="1203" alt="Screenshot 2019-10-21 at 2 39 08 PM" src="https://user-images.githubusercontent.com/1269602/67192227-d7483b00-f410-11e9-9186-290000ab49cf.png">
