### ISSUE TITLE
Domains: Best Match and Best Alternative indicators aren't visibly different

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36738]
<img width="382" alt="26" src="https://user-images.githubusercontent.com/2124984/66777262-92fbee80-ee96-11e9-9229-773244eafdf9.png">

If you search for a domain (Manage -> Domains -> Add domain -> Search) on mobile web, the Best Match and Best Alternative indicators barely show a visible difference in size, rendering them ineffective as a visual indicator of the domains' relevance.

**Comment by sixhours** [comment]
In testing, this doesn't appear to be an issue all the time; only when the Best Alternative is a ~95% or higher match. Widening the overall field doesn't help, visually.

I think this begs the question whether these indicators are effective. How can we test that?

**Comment by klimeryk** [comment]
> I think this begs the question whether these indicators are effective. How can we test that?

We've done an A/B test on that in the past and they proved _extremely_ effective (see internal reference p8kIbR-21-p2).

FWIW, the mobile vs desktop styling is basically the same here. The issue is that the logic to [calculate the percentage to show](https://github.com/Automattic/wp-calypso/blob/561e197b0aae52e2eda3d78ebdc444dcba6a9169/client/components/domains/domain-registration-suggestion/index.jsx#L288) in that bar seems to have been broken at some point. It should be fairly easy to fix, though. Thanks for highlighting this, @sixhours!
