### ISSUE TITLE
Domains: Change Site Address screen needs visual tweaks for mobile web

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36737]
<img width="382" alt="23" src="https://user-images.githubusercontent.com/2124984/66777029-e15cbd80-ee95-11e9-951b-3d48311ce690.png">

* Text at the bottom should be left-aligned for better readability
* The prefix and suffix parts of the text input component always look kinda wonky on mobile due to the narrower screen width. Wrapping to a second line looks awkward. How can we style this so it works on both mobile and desktop?

To find this screen, go to:

* Go to Manage -> Domains -> Click on the WP.com site address

**Comment by danhauk** [comment]
So in addition to the screenshot above, we also have another case where you can choose the domain ending for sites that have the free .blog subdomain, e.g. `*.photo.blog`.

![calypso localhost_3000_domains_manage_dan blog(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/448298/66865029-67dfd080-ef64-11e9-966a-5eb24ac12e54.png)

I did some thinking around how we can clean this screen up.

The first thing I did was pull that very important information about your old site address not working anymore above the input. It's more visible here and provides a nice intro to what the input here will do.

As for the suffix, as you mentioned it looks wonky on mobile (and kind of wonky overall IMO). In cases where the user can't change the domain ending, I think we can remove the suffix altogether. It's added visual clutter and cognitive overhead.

![calypso localhost_3000_domains_manage_danhauktestsite wordpress com(iPhone 6_7_8 Plus) (1)](https://user-images.githubusercontent.com/448298/66865335-05d39b00-ef65-11e9-9f89-cc0b6330f793.png)

In the case where the user _can_ change the domain ending, rather than having some weird dropdown pattern inside the suffix, what if we simplify it to a regular form field. Not only is it a weird pattern, but it's kind of hidden and not clear you can change it.

Here I have radio buttons, but we could also use a regular dropdown if that might work better.

![calypso localhost_3000_domains_manage_dan photo blog_edit_dan photo blog(iPhone 6_7_8 Plus) (1)](https://user-images.githubusercontent.com/448298/66865418-2e5b9500-ef65-11e9-9f35-8748662f35e6.png)

These are just quick mockups and the copy for the form field labels needs some work. I think what I have here adds more confusion and cognitive load than necessary by adding other terms and jargon to the screen.

* Does removing the suffix completely where we can still make it clear what you're doing here?
* Can breaking the suffix selection out into a regular form field make more sense and reduce cognitive load than the current solution?

**Comment by sixhours** [comment]
> Does removing the suffix completely where we can still make it clear what you're doing here?

I'm not sure it does. :-/ I kind of wish there were a ghosted-out suffix in the text input, but I don't think we've used that pattern elsewhere, and I'm not sure that would be clearer.

> Can breaking the suffix selection out into a regular form field make more sense and reduce cognitive load than the current solution?

I think it does make more sense and is more visible this way. I prefer the radio selection over a dropdown because you can see all the options upfront without an extra click.

I'll pull these and the rest of the process into a Figma so we can see the whole flow.
