### ISSUE TITLE
Hosting Panel - Prevent flash of content for unauthorised redirect

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#36756]
#### Steps to reproduce
Go direct to http://calypso.localhost:3000/hosting/{simple-site-domain}

#### What I expected

User should be redirected to redirected to Calypso home without seeing any of the hosting panel content

#### What happened instead

The users gets a brief flash of the hosting panel content before being redirected

**Comment by jeraldjuice** [comment]
@glendaviesnz I thought this was happening because this function to redirect the page (https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/hosting/controller.js#L17) was too deep in this stack (https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/hosting/index.js#L16) for the navigation, but I'm wrong there. I think that I didn't handle blocking access correctly in the scheme of Calypso nav.

**Comment by glendaviesnz** [comment]
@jeraldjuice handling the success case first and returning before handling the redirect seems to fix it - PR for this at https://github.com/Automattic/wp-calypso/pull/36757
