### ISSUE TITLE
FSE: hero block in template parts crashes the editor

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36888]
1. Try to insert the Hero block while editing the Header.
2. Notice the following error appear:

![Screen Shot 2019-10-16 at 10 37 03](https://user-images.githubusercontent.com/1182160/67106133-5435a380-f1ca-11e9-90cd-77965b7760d9.png)

The editor crashes and is unable to recover.

**Comment by noahtallen** [comment]
<img width="1551" alt="Screen Shot 2019-10-23 at 2 11 15 PM" src="https://user-images.githubusercontent.com/6265975/67434399-fe347780-f59e-11e9-89b6-5426cfeec0dc.png">

this error displays instantly when adding the hero block

**Comment by noahtallen** [comment]
cc @glendaviesnz @kwight any thoughts? do we need to enqueue more stuff in the template part editor?

_note: this error does not appear in the page editor_

**Comment by Copons** [comment]
The error is thrown by this CoBlocks line, because `meta` is undefined.

https://github.com/godaddy/coblocks/blob/e136ef29c3e8c1f77199c207791f8692be2e405a/src/components/dimensions-control/index.js#L184

It has been fixed in https://github.com/godaddy/coblocks/pull/726 and released in version 1.16.
We are currently on 1.15 in prod and 1.16.1 in horizon.
I've tried loading the 1.16.1 on my sandbox, and it fixed the issue! 🥂 

I'll close this since we can't do anything about it except wait for the upgrade.
