### ISSUE TITLE
FSE: Site Title block improvements in Core

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36947]
Our custom FSE versions of Site Title block should be replaced with Core block.

Please note that some work is already under way in: https://github.com/WordPress/gutenberg/pull/17207.

As part of this effort we need to figure out how best to help move that work forward and getting it to merge - be it reviews, testing, or collaborating with original author and pushing commits.

Since this is one of our first Core FSE issue that we'll be contributing to, it will also be important for informing and scoping our future work. Please note any obstacles that you might encounter along the way. :)

**Update:** core PR should be merged. The rest of the task now becomes verifying if it needs further improvements and integrating in with our own FSE.

**Comment by vindl** [comment]
Just a heads up that core PR should be merged. The rest of the task now becomes verifying if it needs further improvements and integrating in with our own FSE.

**Comment by Copons** [comment]
Site Title block has been merged in Core (WordPress/gutenberg#17207), but now there's talk of making it `PlainText` instead of `RichText` (https://github.com/WordPress/gutenberg/pull/17207#pullrequestreview-305214880).

While I can see the reasons against using `RichText`, I also disagree with using `PlainText`.
`PlainText` is pretty much a simple `textarea`.
This causes the following problems, among others:

- Site Title and Description are single line (`input` fields in wp-admin), while `textarea` is natively multiline.
This means that we'll need to add a JS hack on enter keydown (or on paste multiline content, etc.).
`RichText` already has a built-in `onSplit`/`onReplace` logic that takes care of this.

- `PlainText` uses [`TextareaAutosize`](https://github.com/buildo/react-autosize-textarea) to autoresize the `textarea` height.
But it doesn't automatically resize if late-injected CSS (such as theme editor styles) changes the font size.
`RichText` simply adds `contenteditable` to any HTML element we want (e.g. `h1` for the Site Title, `p` for the Description), delegating the resize to the element itself.

- `textarea` (and other input fields) doesn't inherit the CSS from outside like any other elements.
We would end up having to style the Site Title in the front end and in the editor in two different ways (for example, we might need to explicitly providing the font family or color to the editor's Site Title, while they would be inherited from the body on the front end).
`RichText` would use the same element and CSS class as the front end, making the style consistency efforts much easier for the themes.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
