### ISSUE TITLE
Sites: add a way to update the site icon in Calypso without going to wp-admin

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#37]
The site icon is prominently featured in the Reader. We need a way to update the site icon from My Sites.

![image](https://cloud.githubusercontent.com/assets/7233112/11223369/96aac56a-8d3d-11e5-8077-3ea6c7783df1.png)

Currently, you must go to WP Admin > Settings > General to add/change/remove a site icon

Dependent on being able to upload blavatar via API. We need an endpoint in the API to handle this, as well as a cropping tool in the UI to set it.

Ideas for placement were:
- Inline within `<Site>`
- In general site settings.
# calypso-gaps

**Comment by supernovia** [comment]
For what it's worth, the upload button under Admin > Settings > General is not working on my android app. I had to click the globe/web icon to open that page on the web and update the icon there.

**Comment by lancewillett** [comment]
This is implemented now in Calypso UI, but still links to wp-admin:

![site-icon-new](https://cloud.githubusercontent.com/assets/66797/14114157/d3e49d9c-f58a-11e5-8877-fcfea2744e05.gif)

**Comment by lancewillett** [comment]
As a UX flow note: in core WordPress this is implemented in the Customizer now — so we could follow suit and match that behavior, using the same UX flow as well as the way it's stored in options. That way Jetpack, wp-admin, and Calypso all use the same image and data storage — and users don't have to learn 3 ways to edit the icon.

**Comment by lancewillett** [comment]
@aduth Can we change the My Sites link now to remove the wp-admin URL?

<img width="787" alt="screen shot 2016-11-21 at 11 07 02" src="https://cloud.githubusercontent.com/assets/66797/20494554/ae74b1ae-afda-11e6-9c67-81cc8fd5dd42.png">

Now that Site Icon can be changed in Calypso settings screen, we can point that URL to:
https://wordpress.com/settings/general/example.wordpress.com instead of https://example.wordpress.com/wp-admin/options-general.php

**Comment by aduth** [comment]
@lancewillett I think #9311 will achieve what you're looking for.

**Comment by lancewillett** [comment]
Cool! Testing it out.

Closing this one as fixed with #8456
