### ISSUE TITLE
Unexpected post-purchase screen after upgrading before Launch

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#37009]
I found an unexpected post-purchase screen after upgrading a site before launching it.

#### Steps to reproduce
I was able to see this screen in two ways.

First, by following this path …

1. Create a new WP.com site, with a new account
2. Verify email
3. Click install plugin at /plugins
4. Click Business Plan required prompt at /plugins/upload
5. Complete checkout
6. See unexpected checkout success screen (see screenshot below)

And then …

1. Create a new WP.com site, with a new account
2. Verify email
3. Click Upgrade at /plans
4. Click "Let's do it!" on Site Privacy modal
5. Complete Checkout
6. See unexpected checkout success screen (see screenshot below)

#### What I expected

I expected to see a WPcom-branded screen like the following …

![image](https://user-images.githubusercontent.com/545779/67431004-07c2dd00-f5a9-11e9-9ca1-857022eae9c2.png)

#### What happened instead

I saw this screen instead …

![image](https://user-images.githubusercontent.com/545779/67431056-1d380700-f5a9-11e9-8b49-dc35a159cce4.png)

#### Browser / OS version

MacOS, Chrome.

**Comment by sixhours** [comment]
This is the logic that's causing the thank-you card to show up instead of the usual thank-you page:

https://github.com/Automattic/wp-calypso/blob/34f6a35e6f96b8ed82ec349c15d4eee4c6263201/client/my-sites/checkout/checkout-thank-you/index.jsx#L425

`wasDotcomPlanPurchased` and `this.isNewUser()` both return `true`. `isNewUser()` is checking for user accounts younger than 2 hours:

https://github.com/Automattic/wp-calypso/blob/34f6a35e6f96b8ed82ec349c15d4eee4c6263201/client/my-sites/checkout/checkout-thank-you/index.jsx#L319-L321

Removing the check for `this.isNewUser()` fixes the problem ([it's been in production for ~2 years](https://github.com/Automattic/wp-calypso/commit/fd8135f704a8681269ee48876c185e2fbbb85ad8)). After fixing it, I'm brought to this screen instead:

<img width="1647" alt="Screen Shot 2019-10-24 at 11 43 41 AM" src="https://user-images.githubusercontent.com/2124984/67502242-92601680-f653-11e9-9db7-3c0e2a5dc1ae.png">

@aidvu I know it's been a while since this commit came through, but can you think of a reason we need to show a different thank-you page if a plan is purchased, there's no domain transfer, and the user account is less than 2 hours old?

If not, I'm going to suggest we remove the check for `isNewUser()`

**Comment by aidvu** [comment]
👋 @sixhours 

The reason is a few lines below: https://github.com/Automattic/wp-calypso/blob/34f6a35e6f96b8ed82ec349c15d4eee4c6263201/client/my-sites/checkout/checkout-thank-you/index.jsx#L427

We wanted to remind the users to start the domain transfer, as we didn't want to add more steps in the NUX flow.

cc @Automattic/cobalt

**Comment by sixhours** [comment]
Aha, so could we send domain transfers folks through the "regular" flow and change the primary action in the regular flow to "Start Domain Transfer"? Something like this (really hasty, last-minute, entirely not pretty) mockup:

<img width="1647" alt="Group 1 (1)" src="https://user-images.githubusercontent.com/2124984/67504359-38615000-f657-11e9-88be-a6419b751920.png">

(I don't understand why we'd want to check for new user accounts OR domain transfers for those users, though; wouldn't you want to check for both?)

**Comment by ianstewart** [comment]
Does that sketch make "start your domain transfer" the primary action? In the flows above, where I was upgrading to add a plugin, or just picking a plan, I wasn't doing anything that would assume a domain transfer as a primary action.

**Comment by aidvu** [comment]
I'll let @Automattic/cobalt team chime in on changes. 

The transfer is only shown when a transfer is purchased in singup. The new user thing, no idea why.

**Comment by klimeryk** [comment]
Like Andrija said - the primary action to start the domain transfer should be showed after the checkout (and only when a delayed transfer-in was bought, of course - like during signup).

Definitely please feel free to make this consistent with other flows (consistency above all!), but as mentioned above, it's very important to nudge the user to start the transfer-in as soon as they finish checkout. FWIW, we also send them an email and show a nudge in the sidebar afterwards... but this post-checkout screen seems like the best and most intuitive place for it. The user just bought a transfer-in and the assumption is that they want to start the process (which can take a bit of time) ASAP.
