### ISSUE TITLE
FSE: integrate Footer Credit block on Atomic sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#37047]
This task depends on the following issues:

- https://github.com/Automattic/wp-calypso/issues/37044
- https://github.com/Automattic/wp-calypso/issues/37045
- https://github.com/Automattic/wp-calypso/issues/37046

Once we have a working Dotcom integration, we should replicate the same block extension functionality that we covered in Dotcom specific FSE code (`mu-plugins`) to Atomic equivalent (`wpcomsh`).

**Comment by noahtallen** [comment]
I have some thoughts on this one. Primarily, all Atomic users should be allowed to remove the block because they are on our highest plan. Therefore, we do not need to override any block removal/nudge options for Atomic. (Additionally, this could prove difficult because I imagine there are few ways to provide JS extensibility via wpcomsh other than loading JS variables into the `fullSiteEditing` global object.)

All that will be left to do is:
1. Override the credit link via the PHP filter.
2. Override the options available via the PHP filter.

The above code should be identical to what will live in mu-plugins for the simple-site overrides.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
