### ISSUE TITLE
FSE: integrate Footer Credit block on Dotcom sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#37046]
This task depends on the following issues: https://github.com/Automattic/wp-calypso/issues/37045, https://github.com/Automattic/wp-calypso/issues/37044

Once we have a working .org version of this block, we should try to add extension points that allow us to implement Dotcom specific functionality and plan upgrade nudges.

Please consult this comment in the parent issue for designs: https://github.com/Automattic/Dotcom-roadmap/issues/50#issuecomment-544657971

**Comment by noahtallen** [comment]
Currently (in the PR), the following extension points exist:

- Filter `a8c_fse_default_footer_credit_option` for changing the default value if the user has not selected anything yet.
- Filter `a8c_fse_update_footer_credit_options` for changing the available options in the select.
- Filter `a8c_fse_get_footer_credit_link` for changing where the credit attribution links to (e.g. we'll use it to change from `WordPress.org` to `WordPress.com`)

The next question is figuring out how WordPress.com plans will operate in this context. Some thoughts

### Use PHP filters:
1. In PHP use a filter to retrieve whether the site has the correct plan.
2. Expose that boolean through the JS global object.
3. Display the nudge components if that boolean is true. (we would write these components in the FSE plugin, just like how Jetpack does for the Simple Payments button)
4. Disable block removal if that boolean is true.

### Use the Jetpack plans store:
1. Subscribe to `wp.data.select( 'wordpress-com/plans' ).getPlan()` ([#](https://github.com/Automattic/jetpack/blob/c817ae647ddfb68fb5fcd2680fc39d31ca12105d/extensions/shared/components/upgrade-nudge/store.js)). I verified this already exists inside the wp-admin post context on WordPress.com.
2. Use that value to figure out if we should show a plan.

### Create our own store:
1. Create a data store based off of @wordpress/data for our data needs behind the iFrame.
2. Create a way to pipe actions through the iFrame:
    - In FSE, we create a data store.
    - Start by calling a function in Calypso that looks like an action dispatcher.
    - That function triggers a message through the iFrame.
    - The iFrame bridge server gets the message, and dispatches the action to the FSE data store.
3. Subscribe to that store in FSE so that we can get plan information.

I think this is a cool solution, and it could be a way for us to get around our navigation issues. There is a fair amount of data which could go into this store and make life a bit easier than just having a global object. Not sure if it would be worth setting this up instead of just using the Jetpack store.

The main objection I see is that we'd be programming in WordPress.com specific things into FSE. For example, the nudge component would be included with FSE code. Additionally, something like "plan" in the data store would be WordPress.com specific. IMO this is not an issue. Both Calypso and Jetpack include tons of references to WordPress.com plans, and I don't think having a reference to it in FSE is an issue.

Thoughts?

**Comment by noahtallen** [comment]
To continue working on the credit block, re-add the block registration removed in this commit: 9eb8a68f9a08f74be65a1f625e06a1bad8879cc0.

Additionally, it seems that the site options may not be working on WordPress.com as they do locally, so that will need to be fixed as well.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
