### ISSUE TITLE
Editor: When picking a custom color dynamically set a text color with good contrast

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37051]
If I set the background color of a group block to predefined colors, the text color inside of the group block is set to a color with an appropriate contrast (as chosen by the theme css classes `has-secondary-background`)

However, if I set the background color of a group block to a custom color, the text color always switches to dark grey. This means I cannot set a custom dark background color as the text is unreadable with no way to change the color.

Let's see if Gutenberg core would be interested in an enhancement where when picking a custom background color we also dynamically set a text color with good contrast.

![2019-10-24 15 42 34](https://user-images.githubusercontent.com/1464705/67530772-065ee680-f675-11e9-93bd-797d6ed80e6b.gif)

**Comment by gwwar** [comment]
@apeatling I think this might be an enhancement rather than a bug. When a theme preset is picked it applies the more generic class `has-x-background-color`, which provides a background and text value. The editor is not setting dynamic values, so when a custom color is picked for background, it doesn't attempt to update the text colors.

<img width="989" alt="Screen Shot 2019-12-11 at 5 03 20 PM" src="https://user-images.githubusercontent.com/1270189/70673678-2bfd7a80-1c38-11ea-9bac-fffceea4693b.png">

**Comment by gwwar** [comment]
I think it'd still be a nice improvement, but we might want to see if a try PR is possible in Gutenberg since this is a core block.

**Comment by glendaviesnz** [comment]
I have this working on a branch, with changes to the custom background dynamically setting text color to black or white depending on which provides the best contrast, and also adds a custom text color picker so this can be modified by the user:

![text-color](https://user-images.githubusercontent.com/3629020/70892140-6d819180-204d-11ea-92cf-8bb7a166eea5.gif)

I haven't quite go the setting of the custom text color working correctly, should be able to get it sorted and a PR up tomorrow.
