### ISSUE TITLE
Store: Orders fetched by order number not post ID

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#37089]
#### Steps to reproduce
1. On a WordPress.com hosted site with WooCommerce installed, install a plugin that modifies WooCommerce order numbers such as: [WooCommerce Sequential Order Numbers Pro](https://woocommerce.com/products/sequential-order-numbers-pro/)
2. Set a starting order number that noticeably differs from the current post ID sequence.
3. Place a new WooCommerce order on the site.
4. Attempt to view the order from both WP Admin, and from Calypso in `Store > Orders`.
5. Observe for the new order that the order number and post ID differ.

#### What I expected

* To be able to view the order in Calypso irregardless if the post ID and order number differs for a particular order.

#### What happened instead

* In Calypso, the API requests use the order number when fetching, not the post ID, which leads to a response error of `woocommerce_rest_shop_order_invalid_id`.

#### Context
#user-report
p9F6qB-4gT-p2

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that

**Comment by Arxhtects** [comment]
How exactly was this fixed? I'm receiving the same error still and am running an fresh install of woocom.

wp-json/wc/v3/orders/99794?consumer_key=/&consumer_secret= 

Returns the same error as it is finding the post id rather than the order id

{"code":"woocommerce_rest_shop_order_invalid_id","message":"Invalid ID.","data":{"status":404}}
