### ISSUE TITLE
Blocks: Our Business Hours block is clunky in columns

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37085]
Our business hours block relies on UI that does not scale well when inside of a column. Our business homepage template uses the hours block in a column in the footer.

It's hard to see the AM/PM and actually really hard to adjust times with the tiny tiny arrows:

<img width="350" alt="Screen Shot 2019-10-25 at 1 51 54 PM" src="https://user-images.githubusercontent.com/1464705/67603757-a0cf3080-f72e-11e9-980b-cac4674793e1.png">

I think we can figure out a much better UI for this that uses inner blocks.

**Comment by iamtakashi** [comment]
This has been suggested the issue below, but it could be helpful to use the `<select>` element, instead of `<input type="time">`?

* `<select>` use the space a little more efficient (It doesn't add a 'cross' reset button.)
* Selecting is easier than typing/incrementing/subtracting the value inside.
* It doesn't care the browser's locale.

![with-select-2](https://user-images.githubusercontent.com/908665/67687246-f22a2a80-f98f-11e9-800d-f87b8b6eac1f.png)

Related: https://github.com/Automattic/jetpack/issues/11840

**Comment by apeatling** [comment]
This is better, but is limiting if you don't open or close on the hour. The list gets long if you start slicing by 15min intervals.

When using this block I wondered to myself why I can't just type in the times? Why am I jumping through selection hoops?

**Comment by iamtakashi** [comment]
> but is limiting if you don't open or close on the hour. The list gets long if you start slicing by 15min intervals.

Ah, that's a good point.

> When using this block I wondered to myself why I can't just type in the times? Why am I jumping through selection hoops?

By looking at the master thread pafL3P-cy-p2, the intention seemed to be to follow the pattern that Google My Business assuming it's been tested 🤷🏽‍♂️

Another possible reason was to have structural data to implement schema.org metadata, but that seemed to be blocked by wp_kses stripping. I can take a closer look at schema.org, and if we could simplify the UI. 

--

In terms of our templates, if the block doesn't provide anything meaningful than freeform, should we use paragraph in our templates?

**Comment by shaunandrews** [comment]
The UI for this block has always bothered me. Glad to see us iterate on it. Looking through google gives a few ideas, like this one from a WP plugin:

![3295C82B-77F5-4BEB-AD1E-5431AA0DAF90](https://user-images.githubusercontent.com/191598/67951894-c3e06100-fbc2-11e9-8a4f-c4b795bcf733.png)

This lets you set up hours across multiple days, and let’s you create additional hours if needed. Rather than having to enter the same times for every day. 

Another consideration is to not be so strict with the way time is entered. An `input type=“time”` and a `select` element both create some challenges and could limit the options a customer could enter. A simple text input could open up possibilities for customers to add the time how they want (9-5, 9-dark, etc). Here’s a screenshot from another WP plugin:

![EC0C2E10-1A64-4FDA-9E35-27CE30FF682F](https://user-images.githubusercontent.com/191598/67952336-8af4bc00-fbc3-11e9-9888-e9522f47d247.jpeg)

It could be interesting to explore some style variations for this block as well, allowing customers to choose of the hours are displayed in a vertical list, condensed into a single line, or some other variation. Here’s another screenshot from another WP plugin:

![1E624E5F-89BA-43FB-8E5A-8A1C0432CF2C](https://user-images.githubusercontent.com/191598/67952713-140bf300-fbc4-11e9-9a1d-a62dc94b38df.jpeg)

—

Depending on how we tackle this, it’s possible that we may want/need to use a modal to edit the time settings. Otherwise I worry that we’ll never be able to fit all the UI with it the canvas area of the block.

**Comment by iamtakashi** [comment]
> Another consideration is to not be so strict with the way time is entered. An input type=“time” and a select element both create some challenges and could limit the options a customer could enter. A simple text input could open up possibilities for customers to add the time how they want (9-5, 9-dark, etc)

Allowing freestyle would be easier and flexible, but one of the points of the block is to implement schema.org metadata for SEO, which requires certain structured data/input.

But again, we seem to have an issue to implement it, so the restrictive UI has much less point currently.

So I think the question is whether we're going to tackle the issue and implement schema.org metadata or not. If we unlikely solve the issue then we should simplify the UI to allow freestyle input. Who can answer the plan for the implementation?

**Comment by shaunandrews** [comment]
> which requires certain structured data/input.

Perhaps we can provide the structure data when rendered by recognizing common patterns in the entered data.

I wonder if we could provide guidance by using notices that suggest data be entered a better (more structured and common) way, without enforcing it — similar to how Gutenberg provides accessibility recommendations for things like colors.

**Comment by shaunandrews** [comment]
Worked up a GIF that shows a proposed update to the design of the Business Hours block:

![Business Hours i2](https://user-images.githubusercontent.com/191598/69658775-cf506c00-104a-11ea-875d-b20b3979111f.gif)

Along with that, I explore how the block would adapt based on different viewports/spacing:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/191598/69658923-26eed780-104b-11ea-9ce9-959f994f9530.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/191598/69659217-bac0a380-104b-11ea-9476-494e25a24d15.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/191598/69658936-2b1af500-104b-11ea-87d0-eaf7d28ba464.png">

Here's the Figma source file: https://www.figma.com/file/iU7UsRfSPTI7IobXP6iVdR/Business-Hours?node-id=23%3A214

**Comment by MichaelArestad** [comment]
This is a huge improvement. I love the change in direction toward `InnerBlock` conventions.

I'm hesitant about "Open now" functionality due to time zones, but I don't see that as a required feature right away so we can take the time to work that out as we iterate. It's definitely a cool idea to have some sense of if the restaurant is open or if it's closing soon.

CC @Automattic/jetpack-design

**Comment by shaunandrews** [comment]
> I'm hesitant about "Open now" functionality due to time zones, but I don't see that as a required feature right away so we can take the time to work that out as we iterate.

Agreed. The "Open now" thing is nice, but far from a requirement.

**Comment by folletto** [comment]
Nice design iteration there! 👍 

The timezone shouldn't be [too difficult in JavaScript](https://stackoverflow.com/questions/6939685/get-client-time-zone-from-browser), however, business hours are local to the place, not to the user timezone, so a basic implementation is a match of the WordPress installation set time vs the time in the block. As long as there's an option to disable it ("I can't set the time of my installation help!") it should be fine.

A note on am/pm: the number of countries using am/pm is fairly small compared to 24h clock, so let's make sure we prioritize and set defaults accordingly. I think we should however be able to again take the setting from the WordPress installation?
