### ISSUE TITLE
Icons: List view ellipsis menus are using old Gridicons.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#37116]
As noted by @shaunandrews in #36826, list view ellipsis menus are still using our old Gridicons, instead of the new Material icons present in the sidebar.

<img width="1101" alt="Screen Shot 2019-10-28 at 9 40 40 AM" src="https://user-images.githubusercontent.com/349751/67698275-4c62c580-f967-11e9-8f55-0fb0a2d7bb18.png">

**Comment by shaunandrews** [comment]
@lcollette @danhauk — I think this might still be a valid issue.

**Comment by lcollette** [comment]
Indeed it is! Added it to the Manage team's project board. Thanks, @shaunandrews!

**Comment by sixhours** [comment]
I peeked into this today and found it's more complex than I would have thought (of course).

I started a PR here to show what's involved with allowing the PopoverMenuItem component to use Material _or_ Gridicons depending on the specified prop, and updates just the Post ellipsis menu icons: #44542

There are many instances of the current pencil Gridicon across Calypso and a handful of stats instances; updating each will require different replacement methods depending on how they're used. It's a bit of a project; I would have expected to replace maybe 4-5 instances but it will be more.

If we intend to use Material instead of Gridicons across the board, the project becomes much, much larger. It's right up my alley and something I'd be thrilled to take on. :D But I'm not sure where it lands on the list of current priorities.

**Comment by sixhours** [comment]
Chatted w/ @rickybanister about this and agreed it doesn't make sense to make the jump to Material given the move toward standardizing with core/Gutenberg components. Maybe instead of bringing list items in line, we should consider changing the sidebar nav icons back to Gridicons for greater consistency in the meantime.

**Comment by danhauk** [comment]
In this interest of trying to declutter our interface, what if we simplified by just removing any icons in this list view?

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/448298/89218823-b9615680-d59c-11ea-8a6c-cee247b35777.png">

**Comment by rickybanister** [comment]
I like that proposal Dan, they don't add much that we couldn't achieve in other ways. 

We could probably explore the groupings more, add color to the trash link, etc.

**Comment by danhauk** [comment]
@rickybanister Agree we could further explore groupings, color, and labels to make it work even better.

**Comment by sixhours** [comment]
I'd suggest closing this out in favor of #45309, since the navigation will no longer be using Material icons when the combined version lands.
