### ISSUE TITLE
Gutenboarding: Can we yield an api receive action?

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#37186]
https://github.com/Automattic/wp-calypso/blob/8bcfefe6d04682b23d1f200bd4ef2b4c83dadf1c/client/gutenboarding/store/resolvers.ts#L21-L22

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/37118_

**Comment by ockham** [comment]
Yasss! Just make sure to not use integer `enum`s for action types:

```ts
// Bad!
enum ActionType {
	RECEIVE_VERTICAL, // assigned 0
	SET_SITE_TITLE, // assigned 1
	SET_SITE_TYPE, // assigned 2
}
```

Because this will happen, and Redux will get confused:

![receiveVerticals](https://user-images.githubusercontent.com/96308/67924604-4d9c2880-fbdb-11e9-8201-d63df1d3e45c.png)


Instead, make sure to set enum members to their 'string equivalents':


```ts
// Good
enum ActionType {
	RECEIVE_VERTICAL = 'RECEIVE_VERTICAL',
	SET_SITE_TITLE = 'SET_SITE_TITLE',
	SET_SITE_TYPE = 'SET_SITE_TYPE',
}
```

([See](https://github.com/Automattic/wp-calypso/pull/37118#issuecomment-548228371))

I don't think there's a more TypeScript-ey way around this; after all, we need our action's `type` fields to be some string value.

**Comment by sirreal** [comment]
> […] we need our action's `type` fields to be some string value.

Is this really a requirement?

> An *action* is a plain object that represents an intention to change the state. […]
> Actions must have a `type` field that indicates the type of action being
> performed. Types can be defined as constants and imported from another
> module. It's better to use strings for `type` than Symbols because strings
> are serializable.
> ```ts
> export interface Action<T = any> {
>   type: T
> }

[source](https://github.com/reduxjs/redux/blob/5a5ab6abf91ea6fd00579d9cceeb0d1f7693c56c/src/types/actions.ts#L1-L20https://github.com/reduxjs/redux/blob/5a5ab6abf91ea6fd00579d9cceeb0d1f7693c56c/src/types/actions.ts#L1-L20)
