### ISSUE TITLE
Gallery Block: Set a fallback width and height on uploading placeholders

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37290]
Please watch the "Editing a Page Template: Gallery Block" testing video on this post: p58i-8d4-p2

When uploading images on a slower connection it takes a long time to get width and height values and you get compressed upload spinners like this:

<img width="640" alt="Screen Shot 2019-11-05 at 7 53 11 AM" src="https://user-images.githubusercontent.com/1464705/68223271-54db8180-ffa1-11e9-9d34-f5ed286afe72.png">

**Comment by Addison-Stavlo** [comment]
Hrm, I am having issues reproducing this.

I have tried to upload single and groups of images on a custom simulated "slow" connection with high ping (2000ms) and low download/upload speed (1 kb/s) through chrome's dev tools.  As soon as there is any loading spinner, it is already wrapped in the placeholder image block with width/heigh.

I am wondering if there is something else I am missing to reproduce this?  Or perhaps if a core change has been introduced since this happened.. 🤔

**Comment by apeatling** [comment]
Fine to close if you can't reproduce now.
