### ISSUE TITLE
Editor: Inline link editing

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3736]
Original comment with concepts: https://github.com/Automattic/wp-calypso/issues/303#issuecomment-158846267
Related core ticket: https://core.trac.wordpress.org/ticket/33301

We should seek to enhance the editor by enabling users to add, edit, delete, and search for content links via an inline popover.

**Concept:**

![image](https://cloud.githubusercontent.com/assets/1779930/13476557/600d58e0-e096-11e5-8242-0cebf9f1a305.png)

/cc @folletto

**Comment by folletto** [comment]
Thanks Andrew :)

Adding two notes:

1. We might get away entirely from the "Text" field, since it's... the text right there on the page, so in the popup version we might just try to do without.
2. The "Link" section does autocomplete ([old mockup](https://cloud.githubusercontent.com/assets/4389/13493634/0cafc02e-e137-11e5-8e56-c831af6edb1e.png)).
3. The "Open link in a new window" should be default off (I know it's obvious, but since it's on in the mockup... better being clear). :D

**Comment by rachelmcr** [comment]
Closing as this will be resolved with the new link behavior in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
