### ISSUE TITLE
Customizer: Masterbar shows on Mobile Safari when coming from Calypso

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#3763]
#### Steps to reproduce
1. Load WordPress.com on Mobile Safari
2. Navigate to the Customizer

#### What I expected
Masterbar should not show in the Customizer, which is the expected behavior and how it works in wp-admin.

#### What happened instead
Masterbar appeared. Having the Masterbar there also cuts off the bottom of the page.

#### Browser / OS version
Safari, iOS 9.2.1

#### Screenshot / Video
![2016-03-03 11 53 31](https://cloud.githubusercontent.com/assets/2846578/13502472/10d6f67a-e139-11e5-8bdb-c8311fa71e99.png)
![2016-03-03 11 54 26](https://cloud.githubusercontent.com/assets/2846578/13502473/10d73d92-e139-11e5-881d-6152f79e478c.png)

**Comment by sirbrillig** [comment]
Confirmed that the masterbar is coming from Calypso rather than WordPress. The customizer section is supposed to be positioned such that it overlays the masterbar and thus hides it. At some breakpoint (looks like 660px), the masterbar jumps back into view. That's even before the customizer's mobile breakpoint, so it's not just there:

<img width="680" alt="screen shot 2016-03-03 at 1 47 10 pm" src="https://cloud.githubusercontent.com/assets/2036909/13505284/84df2224-e146-11e5-96e8-f8de6710801e.png">

**Comment by sirbrillig** [comment]
[Here's the offending code](https://github.com/Automattic/wp-calypso/blob/bdf36c9d45793157282b402f277bda6d471d2694/client/my-sites/customize/style.scss#L9-L21). Removing those breakpoints (and making the second one the default) seems to fix the issue. I'll see if I can figure out why that code was there in the first place...

**Comment by sirbrillig** [comment]
Ping @ehg because it seems like those lines were added to solve something in the showcase?

**Comment by ehg** [comment]
As discussed on Slack, I added them because the Customizer was showing as blank in mobile modes. I think it was a Safari bug, so it may no longer be needed :)
