### ISSUE TITLE
Gutenboarding: Get localized verticals

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#37630]
Get localized verticals results. We should use user's locale if they're logged in and fallback to browser locale.

**Comment by ramonjd** [comment]
For the October 2020 push (pbxlJb-ry-p2), this issue is low priority as the flag `gutenboarding/show-vertical-input` is false in all environments: https://github.com/Automattic/wp-calypso/blob/4e24c241f624db8fd089dd28c2d7e6bceaaf3f60/client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx#L104

**Comment by synora** [comment]
@sirreal Could we close out this issue? It's gone stale.

**Comment by ramonjd** [comment]
I think we can close for now. Thanks again.
