### ISSUE TITLE
Page Layout option in the sidebar should default to "open"

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#37781]
Instead of being closed by default, why not expand the "Page Layout" option by default? This way it has more visibility if users need to make changes to it.

**Comment by jasmussen** [comment]
I shared some thoughts in https://github.com/Automattic/wp-calypso/issues/37279#issuecomment-559387300 as well, the gist of it being that the sidebar was designed to hold secondary navigation exactly so that you could have an immersive block-first direct manipulation canvas. For that reason, if at all possible, I would recommend exploring a block-first UI, such as this:

<img src="https://user-images.githubusercontent.com/1204802/69788331-8de0cd80-11be-11ea-97ac-b9bc0c5cf68a.png">
