### ISSUE TITLE
Put the user in the editor when signup is complete

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37895]
When the user has completed the last step of the signup flow, drop them straight into the editor instead of customer home.

Make sure that the editor back button takes them back to customer home and the checklist when they are done.

We will also need to make sure there is a clear way to get back to customer home after updating/publishing the page.

**Code:**
- [x] Redirect user to Editor after Signup #36382 
- [x] Change Editor back button to link to Customer Home #36382
- [ ] Update post-publish message

**Comment by michaeldcain** [comment]
> When the user has completed the last step of the signup flow, drop them straight into the editor instead of customer home.

@apeatling @ianstewart: #36382 does this for the `test-fse` flow, but I'm wondering if we should also do this for `onboarding` too. What do y'all think?

**Comment by michaeldcain** [comment]
> but I'm wondering if we should also do this for onboarding too.

On second thought, I worry that we'd only increase the issue where users think their page title is their site title. Let's keep it in the `test-fse` flow.

**Comment by apeatling** [comment]
> On second thought, I worry that we'd only increase the issue where users think their page title is their site title. Let's keep it in the test-fse flow.

Yes agreed, I think users have to have FSE for this to be reasonable. That's one reason to not include non-fse blogging themes as mentioned here https://github.com/Automattic/wp-calypso/pull/36825#issuecomment-557903302

**Comment by ianstewart** [comment]
+1 on FSE-test only for now.

**Comment by andrewserong** [comment]
Closing this issue now:

* The main feature was implemented in #36382 
* It was identified in testing that without additional messaging the signup flow feels disorienting because the user lands in the editor without context of what they should do that point. This issue was raised in: https://github.com/Automattic/wp-calypso/issues/38057
* A PR to switch the `test-fse` flow's destination back to the Customer Home is open in: https://github.com/Automattic/wp-calypso/pull/38106
* The work on redirecting signups into the editor will continue in: https://github.com/Automattic/wp-calypso/issues/38058 in Milestone 3
