### ISSUE TITLE
Framework: Reduxify `lib/screen-title`

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#3796]
So we can use it on the server-side to set page title (and later, maybe also for `meta` tags for SEO purposes).

Instead of storing `formatttedTitle` (using information obtained from `sites-list`, i.e. another store!), we should probably only store the actual title, and possibly provide a `getFormattedTitle()` selector instead (that uses the sites-related stuff in our Redux tree).

(I think this could be trial material.)

**Comment by aduth** [comment]
Started some of this in #3918 . Changes there only include some basic state handlers, but does not do much to convert existing `lib/screen-title` away from using Flux.

**Comment by joseph-work** [comment]
I'll tackle this ticket, this is my approach:

I'll start by converting the base `lib/screen-title` over to Redux, by starting from scratch. By taking a TDD approach I can make sure tests are in place, as they are missing currently from the old implementation.

After I'm content with the new Redux conversion I will add a `getFormattedTitle()` selector and only store the actual title in the state instead of the `formattedTitle`, as proposed by @ockham.

**Comment by aduth** [comment]
@joseph-work , sounds like good first steps. Since we already know the requirements of the current store, it should make things a bit easier in terms of modeling new Redux state handlers.

There is pretty good test coverage in the `state/` directory, so you should be able to find some good reference material there, but feel free to ping me if you have any questions.
