### ISSUE TITLE
Different icons for editing/swapping images in different blocks

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38071]
For changing images, the Cover block uses a pencil icon with a tooltip that says "Edit Media", while the image block uses a "swap" icon with a tooltip that says "Edit Image". These both do the same thing, the only difference is that the swap icon shows a block placeholder state with some of the options from the Media Library first.

Are these different patterns? Should we standardize on one or the other?

#### Steps to reproduce
1. Add a cover block and an image block to a page.
2. Hover over the swap and pencil icons to see the tooltips.
3. Click the pencil icon to invoke the Media Library, and click the swap icon to show the block placeholder state.

#### Screenshot / Video
![Screen Shot 2019-11-29 at 11 19 40 AM](https://user-images.githubusercontent.com/1348738/69887251-e71e2f00-129a-11ea-9bcd-4d498427c484.png)
![Screen Shot 2019-11-29 at 11 19 29 AM](https://user-images.githubusercontent.com/1348738/69887252-e71e2f00-129a-11ea-9ec1-e2afb6ddd62d.png)

**Comment by Addison-Stavlo** [comment]
It looks like core updated the image block to no longer use the icon and to now say "replace" . 
![Screen Shot 2019-12-16 at 3 20 41 PM](https://user-images.githubusercontent.com/28742426/70940324-0eedf080-2018-11ea-894a-9c178369a0ff.png)

"Replace" gives 3 options for uploading, giving a URL, or selecting an image from the media library.

The "cover" block on the other hand still has the pencil icon and will open the Media Library when this is clicked.  Since this is not an image block intended uploading, opening an image from the library is the only option other than just setting a flat background color.

So at this point in time, it looks like the 2 different "icons" are for 2 different actions or group of actions.

I am not completely sure where we want to go with this?

**Comment by dwolfe** [comment]
A user can upload or insert from URL from within the Media Library, though, yes? So the difference is that the flow from the Cover block forces the user to do both of those things from the Media Library screen, rather than providing shortcuts?

It seems to me like both of these actions are just replacing an image, and standardizing the pattern would benefit users. To look at it another way: what's the value of teaching the user to think of "change image" differently when the image is part of a Cover block?

**Comment by dwolfe** [comment]
To be clear, I'd be in favor of using the "Replace" button with the menu in both places.

**Comment by alaczek** [comment]
I just stumbled upon this yesterday, and it took me a long time to figure out how to swap image in Cover block - I did not associate the pencil icon with changing the image at all. Using "Replace" instead of the pencil icon would make a big difference.

**Comment by vindl** [comment]
Closing this since both the Image and Cover block now show the "Replace" text in core.
