### ISSUE TITLE
Media: Do a better job of surfacing Pexels.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38080]
We know that it can be difficult to find images with which to build a professional-looking website. We have those images in our media library …

![image](https://user-images.githubusercontent.com/545779/69888749-1fca0280-12b3-11ea-8736-1feed1c97618.png)

Yet we hide them away …

![image](https://user-images.githubusercontent.com/545779/69888783-4be58380-12b3-11ea-85ec-3a00933396f8.png)

… where they're unlikely to be found.

cc @michaeldcain

**Comment by dwolfe** [comment]
Just wanted to +1 this issue - I jotted this down in my testing as well. The Media Library could use an overhaul of its navigation more generally, and I would suggest that better surfacing of free stock photography should be a requirement for that effort.

**Comment by iamtakashi** [comment]
This is not isolated to Pexels library but something to keep in mind for when we make this better — In my experience, the cropped square thumbnails make difficult to pick the right image to replace images on layouts/templates because it's not clear if the image that I'm interested in is portrait or landscape.

**Comment by davipontesblog** [comment]
I am closing this one since there is now a tile in "My Home" to feature the free photo library. Please reopen if you think it's still worth doing any work directly in the Media library panel in WordPress.com, or anything related to the Image block in specific as well! Thanks :)
