### ISSUE TITLE
"Update your homepage" checklist step is incomplete even though I've edited my homepage

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38097]
It looks like the "Update your homepage" checklist item doesn't evaluate the homepage status, and only completes by going through the flow initiated by the "Start" button within that checklist item. I went through the test-fse signup on Horizon and got dropped directly into the editor, then I edited several things on my homepage. After clicking "Continue Site Setup" in the help menu, I was taken to Customer Home and saw that the "Update your homepage" item was incomplete.

It led me through the layout picker, too, even though I had changed my layout using the link in the sidebar. Interestingly, "You created a tagline" was completed.

#### Steps to reproduce
1. Signup as a new user using the test-flow on Horizon
2. Click "Choose a domain later" and select a paid plan on the plans screen
3. Complete checkout
4. [Homepage loads into FSE] Make some edits - change an image and update site title
5. Click the help button and click "Continue Site Setup" to navigate to Customer Home
6. See incomplete "Update your homepage" checklist item

#### What I expected
Having edited my homepage right after checkout - including my site title, tagline, and layout - I expected the "Update your homepage" checklist item to be complete.

#### What happened instead
"Update your homepage" checklist item was incomplete.

#### Browser / OS version
(Desktop) Chrome w/dev tools open, iPhone X/XS emulator active

**Comment by ezebecke** [comment]
Same issue here: #2567707 

"Update your homepage" checklist won't go away after updating the homepage.

**Comment by GeoJunkie** [comment]
Encountered in 14308356-hc

**Comment by TeniCola** [comment]
Encountered the same issue in 14923669-hc.

Curiously, for this user the checklist was hidden in Chrome, but reappeared in Edge. For me, the checklist even appeared in Chrome.

**Comment by davipontesblog** [comment]
Moving this to the Manage board for consideration.

**Comment by gwwar** [comment]
Let's see if this is not being marked as done in different editors (native app, vs desktop vs web).

**Comment by obenland** [comment]
> Signup as a new user using the test-flow on Horizon

I'm not sure what this is referring to I'm afraid. Is this test flow active now? What's the best way to reproduce?

**Comment by p-jackson** [comment]
> > Signup as a new user using the test-flow on Horizon
>
> I'm not sure what this is referring to I'm afraid. Is this test flow active now? What's the best way to reproduce?

I suspect test-flow flow was a signup flow that no longer exists. It would be available at `/start/test-flow` if it existed, but there's nothing there now.

I've retested this issue using `/start` and `/new` onboarding and everything works as expected
- Editing the homepage after immediately after landing in the editor after `/new` updates the checklist
- Updating the homepage after manually navigating to the home page (not clicking the link in the checklist) works
- Creating a site on desktop and then updating the homepage using the mobile app works

The task gets marked as complete in the backend when either (1) the `page_on_front` is saved, or (2) the `page_on_front` option is changed. I don't know if this is different from when the bug was reported, but everything appears to be working as expected now.
