### ISSUE TITLE
Gutenberg: Add E2E test to smoke test block invalidation error on default templates

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38383]
Let's add some tests around FSE page templates loading correctly after a new site is created.

I'd recommend one canary for the homepage, and other full suites on the remaining templates.

**Comment by ianstewart** [comment]
While the following screen exists in signup …

![image](https://user-images.githubusercontent.com/545779/70736344-c233ae00-1cd5-11ea-9a4a-2ce94b892605.png)

We'll want e2e tests for at least the first three different homepages. (Blog, Business, Portfolio.)

**Comment by gwwar** [comment]
For folks who've never added E2E tests before see also PCYsg-o8X-p2

**Comment by gwwar** [comment]
We landed https://github.com/Automattic/wp-calypso/pull/38397 butI think a canary would still be worthwhile.

**Comment by mmtr** [comment]
We have now a bunch of homepage layouts:

<img width="400" alt="Screenshot 2019-12-23 at 14 14 00" src="https://user-images.githubusercontent.com/1233880/71360134-14ef4e80-258f-11ea-8b13-133bd656e00c.png">

Not sure which one we should pick for the e2e test, but maybe the [current theme template](https://github.com/Automattic/wp-calypso/blob/1d7e44068bc14ed271b51e73090b11fb88db0ff3/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js#L225) could be a good candidate in order to have the e2e more maintainable and less prone to failures when changing the SPT flow.

**Comment by mmtr** [comment]
Actually, disregard my previous comment. After reading twice the issue summary, I realized that we want to check the default homepage created after creating a new site. There is no template selector on that flow, so I guess that the test could verify the homepage can be loaded in the block editor without any block validation error.

**Comment by mmtr** [comment]
Added an extra step in https://github.com/Automattic/wp-calypso/pull/38507 to the basic sign up e2e canary test that verifies the are no errors when editing the homepage.
