### ISSUE TITLE
Gutenberg: The Classic editor admin prompt should forward to WordPress.com.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#38420]
The WP Admin Classic editor on a WP.com Simple site will display an admin notice prompting the user to try the block editor instead:

<img width="1108" alt="Screen Shot 2019-12-13 at 10 15 46 AM" src="https://user-images.githubusercontent.com/349751/70822108-983fc180-1d91-11ea-84e6-0ef15139c732.png">

Clicking "Switch to the new block editor" will set the user's editor preference to `gutenberg` for that site, but will reload the WP Admin block editor, rather than forwarding to `wordpress.com/block-editor/post/`. We should update this, so that users can enjoy integrations such as the improved media library and revisions panel, as well as immediately-available help and support.

**Comment by kwight** [comment]
I guess this also brings up an education opportunity: users of the block editor in WP Admin should probably see a prompt to try the same editor on WP.com, touting its improved UX: "Use the block editor with our improved media library, revisions, and support access!"

**Comment by davemart-in** [comment]
This is complicated by the fact that Atomic sites with the Classic Editor Plugin enabled block access to the Calypso Block Editor and force you to use the WP-Admin Block Editor. We just spent a week trying to untangle that mess and have decided to back out and leave it be for now.

So, while this issue is seemingly simple, it is unfortunately complex under the hood and likely not an easy win.

**Comment by davemart-in** [comment]
Let's spend a day or so digging into this then assign to a team to take care of.

**Comment by creativecoder** [comment]
Closing, as this was resolved by D48179-code
