### ISSUE TITLE
[Question] Atomic Vs. Simple Sites

### ISSUE THREAD

**Issue by elenamik** [Automattic/wp-calypso#38438]
In the interest of contributing to the code here, what constitutes an atomic or simple site? And how can I tell calypso to generate a simple vs atomic site? Is this a paid feature?

If this is not the right place to direct contribution-related questions, please let me know! 

Thanks,
Lena

**Comment by kriskarkoski** [comment]
Hi @elenamik! Sorry we missed your question initially, we just came across it today while doing a bug scrub.

> In the interest of contributing to the code here, what constitutes an atomic or simple site? And how can I tell calypso to generate a simple vs atomic site? Is this a paid feature?

A simple site is all WordPress.com hosted up until a couple years ago, it's our original infrastructure on multisite with more code limitations due to the shared nature and applies to sites on our Premium and lower plans. 

On our Business and eCommerce plans when a user wants to use plugins or a custom themes some changes happen behind the scenes to turn it into a more standalone site similar to what you would find on WordPress.org hosted anywhere. This is what we call Atomic. Not all Business sites are necessarily Atomic since a plugin or theme install must be requested to be converted, but all eCommerce sites are.

If you find you need an Atomic site for testing some code you are contributing please let us know and we can help you out. I am going to close this issue in the meantime but will keep an eye out for any replies :)
