### ISSUE TITLE
Theme Showcase: Twenty Twenty Homepage Layout not set as homepage on theme switch

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38450]
#### Steps to reproduce
1. Create a new site on WP.com
2. Navigate to theme showcase
3. Switch theme to a recent theme like Barnsbury, view the homepage and note that it looks like the theme demo, because it's using the homepage layout template
4. Switch theme to Twenty Twenty, view the homepage and note that it doesn't look like the theme demo

#### What I expected

Given that Twenty Twenty has a homepage layout template I expected theme switch + homepage template behaviour to match all the other recent, recommended themes.

cc @vindl @apeatling

**Comment by obenland** [comment]
It needs the `'auto-loading-homepage'` tag added to it's `style.css` file

**Comment by apeatling** [comment]
Ah, this can't happen because it's a core theme.

**Comment by Addison-Stavlo** [comment]
Hrm, do we need to remove it from Recommended Themes (or at least change how it is put on there?) ??

I goofed up, I thought this theme wrote its homepage template over what I had on Friday when I tested it out.  Because of this, I said it was ok for @allancole to add the `auto-loading-homepage` tag so it shows up in searches for this feature.  I take it we should remove this tag... but will we still want this showing up under "Recommended Themes" if it doesn't exhibit that behavior?  🤔

**Comment by allancole** [comment]
Drats, should I go ahead and remove the `auto-loading-homepage` tag from the post, and then we can wait on another solution to get it included in Recommended Themes?

**Comment by obenland** [comment]
We could also add a _sigh_ exception to the way we determine an eligible theme

**Comment by iamtakashi** [comment]
> It needs the 'auto-loading-homepage' tag added to its style.css file

> Ah, this can't happen because it's a core theme.

We have WP.com specific tags in core themes until Twenty Sixteen. It looks like we've stopped adding those from Twenty Seventeen. Was it because it makes syncing difficult? Would it be that bad to have the tag in the stylesheet?

**Comment by vindl** [comment]
> We could also add a sigh exception to the way we determine an eligible theme.

Agreed. If we can't add a tag to the theme, we could add a whitelist check in addition to `auto-loading-homepage` tag.

**Comment by obenland** [comment]
I'd prefer adding the tag fwiw. It shouldn't be a merging nuisance since these tags generally don't change for core themes.

**Comment by noahtallen** [comment]
Where could I go about adding a tag?

**Comment by noahtallen** [comment]
Is it just modifying the file in svn under `wp-content/themes/pub/twentytwenty`, or is the source somewhere else?

Another note that adding the tag wouldn't work on self-hosted (and likely Atomic).

**Comment by Addison-Stavlo** [comment]
From what I have gathered from @allancole, it sounds like in order to get (and keep) this functionality working we will need to re-add the `auto-loading-homepage` tag to the stylesheet every time WP gets an update on Dotcom.  Which could become a bit painful to maintain over time.  

My questions at this point are:
Is this something we would want to commit to doing?  
If not, would we still want this theme to appear in Recommended Themes section without that functionality?
Are there any other thoughts on where we want to go with this?

**Comment by obenland** [comment]
I'd love to learn more about how Twenty Twenty gets updated on dotcom. Based on r54887-wpcom-themes I'm not sure why we'd have to re-add it every time.

**Comment by ianstewart** [comment]
cc @allancole and @danieldudzic

**Comment by danieldudzic** [comment]
Hey @obenland,

Here's the doc outlining the dotcom update process: https://themedevp2.wordpress.com/merge-default-themes-to-wp-com/

**Comment by Addison-Stavlo** [comment]
closing this issue as the tag was added to Twenty Twenty on dotcom.
