### ISSUE TITLE
Blocks: Arrows to move blocks greyed out in some cases

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#38476]
In some cases the arrows to move a block up/down are greyed our and inaccessible, but the middle option to drag a block works and once moved the buttons generally begin working again. I have not been able to reproduce, but a user said it continues happening to them intermittently so I wanted to open an issue for tracking reports. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Add several blocks
3. Try to use the arrows to change a block location. In some instances they will be greyed out.

#### What I expected
To always be able to use the arrows to move a block

#### What happened instead
In some instances they do not work and the block has to be dragged or removed and re-added to work as expected.

#### Browser / OS version
Windows and Firefox. The user declined to share their exact versions, just the latest versions of both.

#### Screenshot / Video
![grayed-out-arrow](https://user-images.githubusercontent.com/1900444/71017546-b32d7100-20c4-11ea-8a98-5d4c70cdf478.jpg)

#### Context / Source
#user-report

**Comment by jeraldjuice** [comment]
I wasn't able to reproduce this bug. I am curious if this is because the block in question was in a group.

A post containing just a single block is not intended to show the 'Move' handlers at all for that block, and I wasn't able to find a case where that was true. However, a single block inside of a group looks exactly the way the user described. And moving the block outside of the group, presumably into a post among multiple blocks, would re-activate the move handlers.

Here's how a single block inside of a group looks:

<img width="907" alt="Screen Shot 2019-12-23 at 11 54 10 PM" src="https://user-images.githubusercontent.com/8892849/71394505-df268600-25df-11ea-8f3b-ffee2e773de0.png">

Here's the block markup that is reflected in the above screenshot:

```
<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p>et</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->
```

Based on trying to replicate this bug, this seems like the most plausible scenario.

**Comment by kriskarkoski** [comment]
The case that led to this report was multiple blocks within our Layout Grid block (https://en.support.wordpress.com/wordpress-editor/blocks/layout-grid-block/). I couldn't see the behavior, but I believe the block behaves like a group in many ways and in this case it had more than one block within it.

**Comment by kriskarkoski** [comment]
No further reports of this. I am closing for now.
