### ISSUE TITLE
Convert to Blocks Prompt Does Not Display

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38489]
WordPress.com has a custom integration that detects when:

- Displays the following modal when a post is loaded with a single classic block (HTML soup)
- Clicking on Convert to Blocks should convert the classic block to blocks. (Normally buried under more options)

<img width="694" alt="screen-shot-2019-07-08-at-11 37 12-am" src="https://user-images.githubusercontent.com/1270189/71035999-9c414b80-20d1-11ea-993e-b45f0e1eb94f.png">

https://github.com/Automattic/wp-calypso/blob/1442ba0d3c802f9f05706294d37c17295e227030/apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js#L29

This currently doesn't work since, the block editor inserts a paragraph block on edits:
<img width="1320" alt="Screen Shot 2019-12-17 at 1 30 19 PM" src="https://user-images.githubusercontent.com/1270189/71036100-cc88ea00-20d1-11ea-85f5-b7d835329e8d.png">

To reproduce this:
- ? > Switch to Classic 
- Publish a post without mixing block content
- Edit the post > ? > Switch to Block Editor
- We should see the modal display

**Comment by mmtr** [comment]
Weird. In my tests, there is only one block and it seems that the modal is not displayed because the `blocks.length === 1 && blocks[ 0 ].name === 'core/freeform'` check runs pretty early:

<img width="929" alt="Screenshot 2019-12-19 at 11 02 23" src="https://user-images.githubusercontent.com/1233880/71164316-15b27880-224f-11ea-8613-c5ba0a0173c7.png">
