### ISSUE TITLE
Hosting: Check blog stickers before displaying hosting upgrade availability.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#38484]
Certain sites can be blocked from ever be converted to Atomic sites, and these are identified with `blocked-from-atomic-transfer` stickers. Sites with these stickers should never see the Hosting Configuration sidebar item, nor be able to visit `/hosting-config` directly.

See: p9F6qB-4vk-p2

**Comment by kwight** [comment]
I started looking into adding an `is_blocked_atomic` field on the already overloaded `site` objects, but that seems heavy for what will only be a handful of sites. We can also [get blog stickers](https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/state/data-layer/wpcom/sites/blog-stickers/index.js) into Calypso, but currently it would be by another API call or the query component, neither of which is great at the routing stage, [when we need the info](https://github.com/Automattic/wp-calypso/blob/9e0d43f2727e0b4b403b75028e90f831bf57c368/client/my-sites/hosting/controller.js#L44).

This led me to thinking that it's probably just time to go ahead with [the suggestion in the comments](https://github.com/Automattic/wp-calypso/blob/cd4815b7391b9bff7b9cf2656607472affc4cb72/client/state/selectors/can-site-view-atomic-hosting.js#L13) to move the logic server-side, which would also mean easier access to the blog stickers lib. That still leaves determining the best time/place to get the data into Calypso.

**Comment by mmtr** [comment]
> This led me to thinking that it's probably just time to go ahead with [the suggestion in the comments](https://github.com/Automattic/wp-calypso/blob/cd4815b7391b9bff7b9cf2656607472affc4cb72/client/state/selectors/can-site-view-atomic-hosting.js#L13) to move the logic server-side, which would also mean easier access to the blog stickers lib. That still leaves determining the best time/place to get the data into Calypso.

I think we can move that logic to a new `manage_hosting` capability, so we don't need a new API call at all in Calypso. Started some work exploring that approach in D37177-code and https://github.com/Automattic/jetpack/pull/14288

**Comment by mmtr** [comment]
Just noted that sites with the `blocked-from-atomic-transfer` sticker cannot be transferred to Atomic from the hosting section with the current implementation:

<img width="767" alt="Screenshot 2020-01-03 at 16 21 30" src="https://user-images.githubusercontent.com/1233880/71731524-3f6dc100-2e45-11ea-860f-7b19b7496486.png">

So I'm not sure what allowed the site reported on p9F6qB-4vk-p2 to be transferred to Atomic.

> I think we can move that logic to a new `manage_hosting` capability

On a second thought, I'm not sure this is the way to go, since it will likely slow down the API request to `/me/sites` (given that `manage_hosting` would actually be a is site atomic or can be transferred to atomic check).
