### ISSUE TITLE
Landing pages: further modularize landing page HTML

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38552]
Server-side rendered page skeleton [contains masterbar HTML](https://github.com/Automattic/wp-calypso/blob/e93e018296852c93cfbd24d7d2de6b2e21ca7cb9/client/document/index.jsx#L134) which is visible while the page loads (the blue thing):

<img width="1622" alt="Screenshot 2019-12-19 at 13 48 36" src="https://user-images.githubusercontent.com/87168/71171722-20790780-2267-11ea-9071-77f4ce999e56.png">

We didn't want that on Gutenboarding entry point and thus had to hide it (https://github.com/Automattic/wp-calypso/pull/38530) with CSS.

We should restructure something so that masterbar HTML would be included optionally.

Anything else similar in the serverside rendered skeleton?

cc @Automattic/team-calypso

**Comment by jsnajdr** [comment]
I think that just displaying a gray background with the WP logo, without anything else, should be fine. And compatible with all possible layouts.

The blue masterbar looks disruptive even on classic Calypso view, if you have a theme activated:

![Screen Capture on 2019-12-20 at 14-28-10](https://user-images.githubusercontent.com/664258/71257946-48cf3780-2335-11ea-86e7-430fd672cf9c.gif)

The server-rendered placeholder also contains some legacy markup for `.editor-ground-control` that doesn't do anything useful today.

However, changing the placeholder is dangerous, as it can break SSR in the following scenario:
1. A section like `/log-in` is isomorphic and its route definitions use a special convention: instead of calling `page()` directly, they call a `router` instance passed from above: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/themes/index.web.js#L19
2. That router handler calls `ReactDOM.hydrate` instead of `ReactDOM.render`, trying to hydrate SSR-ed content.
3. That hydration happens also when SSR was not performed, e.g., when disabled by one of the preconditions (non-en locale, query args, ...) Then the SSR-ed content (mere placeholder) doesn't match with the newly rendered content (full UI). The hydration algorithm is very sensitive about that.

The React hydration algorithm walks the DOM to be rendered and tries to match it with the existing DOM. And it matches only tag names, it ignores everything else.

When the existing DOM is:
```jsx
<div class="wpcom">
  <header class="masterbar" />
</div>
```
and the new DOM is:
```jsx
<div class="jetpack">
  <header class="rocketbar" />
</div>
```
then React hydration will see a matching DOM structure (the tag names match) and will leave it as it is. Even if the class names are wrong.

Only when the tag names don't match:

_existing DOM:_
```jsx
<div class="wpcom">
  <header class="masterbar" />
</div>
```
and the new DOM is:
```jsx
<main class="jetpack">
  <header class="rocketbar" />
</main>
```
then the existing DOM will be thrown away and overwritten.

The current server-side placeholder shows the masterbar as:
```jsx
<div class="masterbar" />
```
while the real masterbar rendered with React is:
```jsx
<header id="header" class="masterbar" />
```

This tag mismatch is the main reason why Calypso works at all, I'd say 🙁 

Cc @ockham @sirreal

**Comment by simison** [comment]
The visual aspects got handled by https://github.com/Automattic/wp-calypso/pull/38530 so I don't think it makes sense to keep this open.
