### ISSUE TITLE
Gutenboarding: remove sidebar

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38686]
We can hide the sidebar for the first Gutenboarding steps; we'll need it once the customer lands in WP Admin.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/87168/71897916-a13d6c00-3160-11ea-8b0e-190c74630077.png">

This was leftover from times when we were looking into building the full editor and it was useful technical exploration at the time.

It was added in https://github.com/Automattic/wp-calypso/pull/36597

**Comment by chriskmnds** [comment]
Do we keep or hide the gear icon?

**Comment by simison** [comment]
Let's hide it. 👍

**Comment by roo2** [comment]
raised PR to remove this https://github.com/Automattic/wp-calypso/pull/38793

**Comment by chriskmnds** [comment]
@roo2 I hope you don't mind me assigning you this ticket (since you've already worked on it #38793 :ok_hand:). 

For future reference, you can double check a ticket if it contains an assignee already and whether it's in a "Now" column on the board (since we currently track these on the project board). If not, then feel free to assign it to you - else just ping the other person to check on things and/or sync work. 😸 

Good job, and thanks again!

**Comment by roo2** [comment]
thanks @chriskmnds, will do! :)
