### ISSUE TITLE
Gutenboarding: hide "next" button in intent gathering step

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38698]
In Gutenboarding (https://wpcalypso.wordpress.com/gutenboarding), during intent gathering step we have a "next" button:

<img width="1440" alt="Screenshot 2020-01-07 at 23 30 10" src="https://user-images.githubusercontent.com/87168/71931100-b7b9e680-31a5-11ea-923a-7ff702d2f9c1.png">

This is leftover from the previous iteration. The "Continue" button is the new kid in the block and the blue "next" button can be removed.

Here's @dwolfe 's earlier design for this step: 

<img width="642" alt="image" src="https://user-images.githubusercontent.com/87168/71931351-3a42a600-31a6-11ea-8bbe-e7deddc16c14.png">

The blue button should appear later on in the flow, so we might not want to remove everything related to it:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/87168/71931537-95749880-31a6-11ea-9e50-7fd7141cca6e.png">

So as long as it's hidden in the initial steps, it would be good. Then in the next steps, it can left be there.

@dwolfe @olesyabrk @joanrho can you confirm?

I'm creating this issue as practice material for our new devs.

**Comment by joanrho** [comment]
Makes sense to hide it during the initial steps when the text links "Continue" or "Don't know yet" are the primary actions we want users to take.

@simison In the prototype at https://wpcalypso.wordpress.com/gutenboarding/design, when I select a theme and then move onto pages to include on my site, the "Next" button does not become activated. Is this expected behavior given the state of the prototype? I can select page types but that's it...no next steps.

**Comment by ockham** [comment]
> Makes sense to hide it during the initial steps when the text links "Continue" or "Don't know yet" are the primary actions we want users to take.
> 
> @simison In the prototype at https://wpcalypso.wordpress.com/gutenboarding/design, when I select a theme and then move onto pages to include on my site, the "Next" button does not become activated. Is this expected behavior given the state of the prototype? I can select page types but that's it...no next steps.

We haven't implemented any yet :grimacing:
