### ISSUE TITLE
Me: 2FA: when re-enabling 2FA previous phone number is shown but buttons are not clickable

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#387]
Steps to reproduce:
1. Add 2FA to an account
2. Remove 2FA for that account
3. Try to add 2FA again. Here's what you see:

![screen shot 2015-11-21 at 10 09 42 am](https://cloud.githubusercontent.com/assets/11487924/11319101/92cad62a-9039-11e5-8f91-9126f7e8aa01.png)

The buttons are disabled:

![button-html](https://cloud.githubusercontent.com/assets/11487924/11319112/d215dbb8-9039-11e5-8eca-2434df05ce86.png)

By typing another number in the phone field, the buttons are re-enabled:

![re-enabled](https://cloud.githubusercontent.com/assets/11487924/11319121/0d7f4180-903a-11e5-93e1-721e57526942.png)

This behaviour is correct when there isn't a phone number already saved in the phone field. When there is already a number saved there, the buttons should be available right away (one exception is in the case where it's been less than 1 minute since the last SMS for the SMS button).

The buttons should not be only reenabled when more text is typed or erased from the field.

**Comment by ebinnion** [comment]
After looking into this, I think the best way to approach this would be to refactor the component. Specifically, at least factoring out [the getValue](https://github.com/Automattic/wp-calypso/blob/master/client/components/forms/form-phone-input/index.jsx#L143-L157) functionality so that we could build a `phoneNumber` object in the [getInitialState lifecycle method of Security2faSettings](https://github.com/Automattic/wp-calypso/blob/master/client/me/security-2fa-sms-settings/index.jsx#L47).

I would prefer to tackle this in a maintenance period in December so that I can focus on people management, unless this is crucial to address right now. Also ping @mjangda who might have some bandwidth to address this sooner.

cc @beaulebens @designsimply

**Comment by v18** [comment]
This is related to #26 - both buttons can become disabled when cancelling the process and starting again

**Comment by ebinnion** [comment]
This should be fixed in #584.
