### ISSUE TITLE
Publicize: Eventbrite showing as "connected" even though it was never connected due to new warning

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#38723]
#### Steps to reproduce
1. Go to Tools -> Marketing -> Connections
2. Never have Eventbrite set up

#### What I expected

See that Eventbrite is not connected. Possibly see the warning.

#### What happened instead

Eventbrite shows a "Disconnect" button. Clicking it just changes it to Connect. Reloading the page again shows "Disconnect"

#### Browser / OS version

Firefox 71.0 / macOS 10.15.2

#### Screenshot / Video

![Screenshot 2020-01-08 at 16 57 17](https://user-images.githubusercontent.com/184938/71988085-f00a0500-3237-11ea-81b8-2487555a2199.png)

#### Context / Source

I was working on my blog and looking at how to reach a certain function when I stumbled upon this. 

cc @kwight @gwwar as you worked on the backend change and might have more context here.

**Comment by gwwar** [comment]
@bisko See p58i-8p5-p2 for context

**Comment by kwight** [comment]
@bisko Assuming you're logged in as your SA account, I can see that there's an Eventbrite access token in the db from 2016, so a connection showing up makes sense. Eventbrite connections are per-user, and not per-user, per-site – so that connection will show up regardless of the site you're looking at (that's why it's in the vague bottom section, rather than with other social media above). For more technical details, check out PCYsg-4Zf-p2 or DM me directly 👍

What _is_ weird though, is that a refresh after disconnecting shows you connected again; I'll see what's up with that.

**Comment by kwight** [comment]
Ha, this has been broken since at least April 2017; [I even noticed it](https://github.com/Automattic/wp-calypso/pull/11917#issuecomment-295485564), but didn't pursue the point. 🙃 

Fix in https://github.com/Automattic/wp-calypso/pull/38730.
