### ISSUE TITLE
Gutenboarding: add selected design description

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38748]
In the designs (paObgF-RB-p2) we have a description here:

![image](https://user-images.githubusercontent.com/87168/72072152-01194b80-32f6-11ea-963c-2ab7603886db.png)

Another design has a back button, too (Although it's duplicate with header): 

![image](https://user-images.githubusercontent.com/87168/72072178-0b3b4a00-32f6-11ea-8e14-edbe60b5a32a.png)

Javi's comment via paObgF-RB-p2#comment-2109 :

> Would it be a good idea to show the site title (or something a little bit more natural, something like “Now choose which sections [site title] will have!”), and a small text explaining that you are selecting templates for internal pages that will be created within your site? Like … for me it’s pretty obvious what’s going on there, but for someone who is totally new to building a website, it may not be

Before we have the exact text, we can already add some lorem-ipsum and have it animate together with other elements.

@dwolfe @joanrho @olesyabrk :
- what should we do about that back button?
- what copy exactly we could have here?

**Comment by simison** [comment]
In a PR, we could add site's title already (in place of "Maywood" in design) to demonstrate how that would look and feel.

**Comment by ockham** [comment]
That would mean repurposing header and copy from the original design for something totally different. The original design had theme title and description, and now it's all about 'How to add Pages'. Not sure how the site title fits into that picture :thinking:

**Comment by ockham** [comment]
> * what should we do about that back button?

Weren't we considering dropping the 'Back' button from the header anyway, and replace it with in-onboarding-block navigation (also for the previous steps)?

**Comment by dwolfe** [comment]
> Weren't we considering dropping the 'Back' button from the header anyway, and replace it with in-onboarding-block navigation (also for the previous steps)?

I don't remember this one, can someone summarize?

In the original design picker/page selector concept, the back button returned to the site title step, and the "Choose a different design" link was just that iteration's idea of how to undo the first part of the two-part design+pages question.

I've always preferred more contextually-placed buttons to advance in the flow, so that users don't have to work to find how to move forward. I'm less concerned with how to go back - I think we can expect very few "back" clicks, so it's okay if it's out of the way.

I'm curious about the discussion about removing it entirely, I'll wait for an update on that before commenting further.
