### ISSUE TITLE
Classic Editor: Gallery/Carousel module closes when selected

### ISSUE THREAD

**Issue by allykmyta** [Automattic/wp-calypso#38756]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes
2. Activate retired theme [Misty Lake](https://wordpress.com/theme/misty-lake/)
3. Ensure Classic Editor is primary editor
4. Navigate to post and add a new gallery.
5. Publish and navigate to homepage (latest posts) and select gallery.

#### What I expected
The gallery carousel to appear.

#### What happened instead
Once selected, the carousel appears briefly and then closes.
No errors appear in the browser console when this occurs.

#### Browser / OS version
Current version in Firefox (issue does not occur on other browsers)

#### Screenshot / Video
Available in #2588230-zen

#### Context / Source
#user-report
Further discussion of this issue and the decision to report is available here: 
p1578523560005200-slack-C02FMH4G8

**Comment by kriskarkoski** [comment]
@allykmyta To clarify, the carousel is missing on the front-end of the site correct, not in the Editor? Assuming that's correct, I'm going close this issue here since it would ideally be opened on the theme repo instead, and since this is a retired theme and not a security issue one we're unlikely to fix. Please reopen if I've misunderstood.
