### ISSUE TITLE
Gutenboarding: inject "Launch" button to Gutenberg header

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38904]
For un-launched sites, we'll want to have "launch" button all the time visible that starts the "pre-launch flow" (plan selection, checkout, etc).

Design:

![image](https://user-images.githubusercontent.com/87168/72617212-2be05100-3941-11ea-9ee3-f6b2cdc7d350.png)

The live header looks like this when editing pages/posts (also for un-launched sites):

![image](https://user-images.githubusercontent.com/87168/72617323-6518c100-3941-11ea-8058-22d9e5759fd2.png)

(you can ignore the pink color and imagine it's blue)

It will likely look different when editing _sites_, but even then there will likely be "Save/Update"  buttons to save edited site layout/global styles whatnot.

Curious to hear from designers how launch button should integrate with other buttons in the header?

Meanwhile, we can inject this button already to get into building a functional prelaunch flow for Gutenboarding. It should stay hidden behind a flag.

cc @mtias @olesyabrk @joanrho @dwolfe for thoughts.

**Comment by simison** [comment]
I believe the actual injecting has to happen from somewhere in [`apps/wpcom-block-editor`](https://github.com/Automattic/wp-calypso/tree/c3d8e5cae9b302e058ca87cd51c31afb1771d43e/apps/wpcom-block-editor). We modify UI there in some other ways, too (e.g. add back-button).

cc @Automattic/cylon for any technical guidance.

**Comment by simison** [comment]
Should we start with a header that looks like this:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/87168/72627289-e037a280-3954-11ea-8cc7-0833d182026b.png">

**Comment by rickybanister** [comment]
In a world with full site editing I think Preview becomes slightly less valuable since you're already 'previewing' the entire site in the editor window. And prior to 'launch' all of your pages can be saved, but not published. So the Launch button can replace both preview and publish/update until the launch flag is flipped. The Jetpack or other plugin buttons aren't particularly useful prior to launch either (I may be missing something).

**Comment by simison** [comment]
>The Jetpack or other plugin buttons aren't particularly useful prior to launch either (I may be missing something).

Yep, mostly just interested about interaction and wording between _Save draft_, _Preview_, _Save/Publish_, and the new "Launch" button.

Any wording that should be modified, primary/secondary states switched around, or any buttons should be hidden?

I think what confuses me is "Save Draft" — specifically because saving posts (even for an unlaunced site) is different from "drafts". It sounds like you'd want the "Save draft" button function like "publish" button otherwise functions for a regular WP site?

Should we just have "save" instead of "save draft"?

<img width="478" alt="image" src="https://user-images.githubusercontent.com/87168/72627799-c64a8f80-3955-11ea-8e57-a2d366f93cd6.png">

**Comment by rickybanister** [comment]
"Save" feels very appropriate at the site level.

**Comment by olesyabrk** [comment]
Ditto to what Rick said about deprecating Preview and Publish/Update. 

I think it's important to keep Draft in Save Draft as it provides a secondary indicator that this is not a live site.

**Comment by noahtallen** [comment]
@simison this will become a lot easier with a custom editor instance! Yay :)

I think sticking it in that package is a fine idea so long as we intend to inject it into the iframed block editor. (I.e. it will not show up if you load the editor from wp-admin.) 

You can see prior art with the editor back button. Even without custom UI, we have to do quite a bit of work to perform navigation in the Calypso client instead of on the backend. (The moment you do a full reload, you have to re-boot calypso which takes some time.) The FSE editor also has custom UI, which lives in the FSE plugin so that it still works on wp-admin views, since the iframe bridge server only affects the iframed block editor (i.e. it does not run if you access it via wp-admin)

The flow looks like this:
1. [We get a back button URL in the Calypso app and send a message through the iFrame.
](https://github.com/Automattic/wp-calypso/blob/d5bc4c96c30dcb80c9d444c85aea04f9fa259f3c/client/gutenberg/editor/calypsoify-iframe.tsx#L274-L280)
2. [In the iframe bridge server, we listen for the back button URL. We both save it to some global state and fire a wp.hook action with the data.](https://github.com/Automattic/wp-calypso/blob/d5bc4c96c30dcb80c9d444c85aea04f9fa259f3c/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L657-L680)
3. [If it's the FSE editor, we actually listen for that wp.hook action and use that URL/label to render a different back button that makes more sense in that context](https://github.com/Automattic/wp-calypso/blob/d5bc4c96c30dcb80c9d444c85aea04f9fa259f3c/apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/close-button-override/index.js#L19-L36).
4. [In all back button flows, including FSE, we wait for the user to click on the back button then hijack the event to port a message back up through the iFrame to the calypso client.](https://github.com/Automattic/wp-calypso/blob/d5bc4c96c30dcb80c9d444c85aea04f9fa259f3c/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L559-L580)
5. [In the calypso client, we receive the close editor action and then perform client-side navigation to wherever the close URL points.](https://github.com/Automattic/wp-calypso/blob/d5bc4c96c30dcb80c9d444c85aea04f9fa259f3c/client/gutenberg/editor/calypsoify-iframe.tsx#L242-L245)

In hindsight, it would be better to use a wp data store to assist with this. I'd actually like to switch to that for a lot of our global state at some point. It just hasn't been complex enough yet to warrant it.

**Comment by simison** [comment]
> In hindsight, it would be better to use a wp data store to assist with this.

Sub-optimal solution seems fine for now, given that we'll try building custom editor at which point we don't indeed need none of this. :-)

**Comment by mtias** [comment]
Why is there both a "save draft" and "save page" action? "Launch" is meant to replace "Publish", so there should be no extra buttons compared to a regular view.

**Comment by rickybanister** [comment]
@mtias we discussed this briefly this morning, and while I'd been operating under that same assumption (that Launch would act as a publish-all button), there might be edge cases where that is undesirable. 

How would we handle a situation where someone wanted to leave a couple of pages as drafts, but launch all the pages they feel are ready? We'd need to separate out their status somehow. @olesyabrk suggested relying on page visibility settings, which could be a good solution, but requires extra thought beyond leaving things as a draft. 

We should optimize for the most common case, which I believe is launching all pages at once, but be mindful in some way of how this deviates from the standard behavior.

**Comment by sirreal** [comment]
I've assigned @Addison-Stavlo and @jeraldjuice - they and their teammates have previous expertise relevant for this type of task.
