### ISSUE TITLE
Customer Home: Quick Start Sessions

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38998]
## Start
<img width="343" alt="Screen Shot 2020-02-26 at 11 27 58 AM" src="https://user-images.githubusercontent.com/1301932/75370709-23a5fa80-588b-11ea-9e54-2e53ca297046.png">

- Copy for card is 👍 good to go 
- Imagery for the card is 👍 good to go

- CTA for the card by default is set to a secondary button. When a user selects, it can go to:
`https://wordpress.com/me/concierge/[SITE]/book`

## When a user has a session scheduled
<img width="339" alt="Screen Shot 2020-02-26 at 11 36 06 AM" src="https://user-images.githubusercontent.com/1301932/75371361-38cf5900-588c-11ea-9fb2-104ca37aebd7.png">

- The copy that changes to reflect the session details is 👍 good to go

- The `View Details` CTA takes a user to `https://wordpress.com/me/concierge/[SITE]/book`

- The `Reschedule` link takes a user to `https://wordpress.com/me/concierge/[SITE]/36109/cancel`

### More info for card styling
In `/hosting-config`, there is a card for contacting Support. The most relevant part of it is how the avatars are generated, it uses this class:
`.support-card__avatars`

### Related work
There's WIP to make the scheduling flow show up in a dialog, so that the user isn't "taken away from" this page. That work shouldn't block this work. The net value users will get from seeing this outweighs whatever interaction pattern we choose.

**Comment by dezzie** [comment]
Here's the last-known work on this one. I'll do my best to document any remaining questions or interactions that haven't been figured out.

<img width="343" alt="Screen Shot 2020-02-26 at 11 27 58 AM" src="https://user-images.githubusercontent.com/1301932/75370709-23a5fa80-588b-11ea-9e54-2e53ca297046.png">

- Copy for card is 👍 good to go

- Imagery for the card is 👍 good to go

- CTA for the card by default is set to a secondary button. When a user selects, it can go to:
`https://wordpress.com/me/concierge/[SITE]/book`

**More info for card styling**
In `/hosting-config`, there is a card for contacting Support. The most relevant part of it is how the avatars are generated, it uses this class:
`.support-card__avatars`

**For later**
There's WIP to make the scheduling flow show up in a dialog, so that the user isn't "taken away from" this page. That work shouldn't block this work. The net value users will get from seeing this outweighs whatever interaction pattern we choose.

**Comment by Aurorum** [comment]
I'm unable to get `getConciergeNextAppointment` working currently, so I can't code the session scheduled design yet. However, a first step would be introducing a Happiness Engineers Tray component so that the same code isn't repeated for a third time, and I've proposed that in #39785.

**Comment by jancavan** [comment]
It may actually be possible that a user has purchased this as an add-on in signup/onboarding, but hasn't scheduled a time yet:

https://github.com/Automattic/wp-calypso/pull/41112#issuecomment-613709957

**Comment by kwight** [comment]
As pointed out [on the PR](https://github.com/Automattic/wp-calypso/pull/41112#discussion_r410498290), we can end up in a situation where a user is looking at site A, and if they have a Quick Start session for site B, it will display the card with the date and time ofthat session. This can be confusing both ways to the user: showing it ("why is my session for another site showing here?..") and not showing it ("I already booked a session, why do I need another?..").

@sixhours suggested that if the current "has an appointment" design were to add the site, it could let us show the card regardless of site, and mitigate any confusion. @Automattic/dotcom-manage-design how does that sound?

**Comment by jancavan** [comment]
My vote is to make the concierge session card site-specific. I understand the possible confusion, but I'm a bit concerned about introducing items that cross over from one site to another.

> it could let us show the card regardless of site, and mitigate any confusion.

What happens if they booked concierge for Site A, but also want to book one for Site B? If Site B is displaying a card for Site A's booking, then they won't be able to book for Site B? Unless we offer a way for them to book for Site B while also display Site A's booking.

**Comment by kwight** [comment]
> What happens if they booked concierge for Site A, but also want to book one for Site B? If Site B is displaying a card for Site A's booking, then they won't be able to book for Site B?

Ooooh, excellent point. I'll eave it as-is then, and we'll see if it _does_ actually cause any confusion (I could be making a problem that doesn't exist anyways). Thanks @jancavan @sixhours !

**Comment by kwight** [comment]
Ah, interesting. Looking at the existing behaviour of `/me/concierge`, a user cannot book more than one session at a time; so showing the "book a session" option for site B when they already have a session for site A will not make sense either. I think we're back to where we started: even if the booking was done while on the Home of another site, we should show the upcoming booking. Not only will this align with `/me/concierge`, but it will also expose the info for users that have bought an individual standalone Quick Start session (which can be done without attaching it to a specific site/plan).

**Comment by jancavan** [comment]
@kwight @gwwar There's a WIP PR that will display an upsell to users who have lower-tier plans who have not yet purchased a session or have already used it up. The upsell banner will go on `/me/purchase`.

I _think_ this is the PR for it: https://github.com/Automattic/wp-calypso/pull/38605
