### ISSUE TITLE
UI bug - adding hyperlink then pasting giphy image URL, then undo, removes both image and hyperlink

### ISSUE THREAD

**Issue by wesinator** [Automattic/wp-calypso#39018]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com new blog post
2. Type text, add a link 
3. Paste an image via Giphy url, e.g. https://media.giphy.com/media/fYTbVFA4M7Aj6iaIHP/source.gif 
WP automatically adds the image inline to the post
4. Ctrl-Z to undo image post

#### What I expected
Ctrl-z undo removes just the most prior atomic action, in this case the image post

#### What happened instead
Both the image post and the previously added text link are removed 

#### Browser / OS version
macOS Firefox 72.0.1

**Comment by davipontesblog** [comment]
Hi @wesinator! I tested this with Firefox 73.0.1 (64-bit) on MacOS and could not replicate the issue. WordPress has also been updated in WordPress.com since your post, so that might play a role in how the links work here as well.

![Screen Shot on 2020-03-09 at 11-46-29](https://user-images.githubusercontent.com/31009008/76231487-b3d52f80-61fb-11ea-90a5-deb3b8cbca3b.png)


If you're still experiencing this issue please comment here with a screencast so we can investigate a bit more, as well as what site this is so we can check whether this is on a simple or atomic infrastructure platform in WordPress.com, whether plugins are conflicting, etc. 

Closing this for now.
