### ISSUE TITLE
Domains: show domain errors more prominently

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3903]
Currently domain settings issues are somewhat hidden and several clicks away. We should show these issues more prominently when we can tell that a domain is not set up correctly. Already started in #3889

**Comment by artpi** [comment]
Turns out @umurkontaci is working on precisely that problem in #3329 and they have a proper server endpoint for NS mismatch.
I closed #3889 because it was duplicating #3329 (in a worse way).

I will look into other domain errors and see what other teams are actually working on, so we don't conflict with their work

**Comment by artpi** [comment]
Also linking: #3152
