### ISSUE TITLE
Resolve Superagent usage on server code

### ISSUE THREAD

**Issue by ChaosExAnima** [Automattic/wp-calypso#39115]
As of #34809, we deprecated the use of Superagent in client-side code and flagged it for warnings via `.eslint`. However, the usage of superagent still happens on server-side code, which creates warnings and blocks development via the linter.

Looking at the issue, I see two potential solutions here:
1. Deprecate the usage, and load something like [`node-fetch`](https://www.npmjs.com/package/node-fetch) via Webpack for all usage of `fetch`.
2. Disable this warning for the server side code.

Thoughts?

**Comment by sgomes** [comment]
Thanks for looping me in, @ockham! 

We already have a polyfill for `fetch` on the server-side, so you should be able to migrate code to that if you wish. That said, there isn't as pressing a need for this on the server side as there was on the client side, since bundle size is not really an issue.

The deprecation warning is my fault, as I set up that rule to avoid having folks add the `superagent` dependency back to client-side code, but couldn't find a way of restricting that warning to client-side code. Which means that it unfortunately shows up in server-side code as well 😕

If it's possible to restrict the warning to client-side code, please go ahead! And thank you! 🙂

**Comment by ChaosExAnima** [comment]
@sgomes - I've opened a PR with a fix, feel free to give it a shot!

Regarding fetch, that's really interesting; definitely didn't see that when I was exploring. Regardless, perhaps we should add it as a global so ESLint doesn't throw errors when using it in the server code?

**Comment by sgomes** [comment]
> @sgomes - I've opened a PR with a fix, feel free to give it a shot!

Thank you, will do!

> Regarding fetch, that's really interesting; definitely didn't see that when I was exploring. Regardless, perhaps we should add it as a global so ESLint doesn't throw errors when using it in the server code?

On the client side, there was a conscious decision to remove just about every global, in order to avoid some hard-to-find errors with undeclared variables sharing a name with a global. I'm not sure what the situation is on the server side, perhaps @jsnajdr knows more?

The general advice from globals like `fetch` is: if you're writing client-only code, use `window.fetch`; if you're writing server-only code, use `global.fetch`; if you're writing polymorphic code, use `globalThis.fetch`.

**Comment by ChaosExAnima** [comment]
Fair enough, that makes sense :)
