### ISSUE TITLE
TFT: On sites with `Your latest posts` active, theme's Homepage is created as Draft instead of being set as new static Homepage

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#39110]
When a template-first theme (TFT) is activated on a site that has `Your latest posts` option active in _WordPress.com > My Sites > Design > Customize > Homepage Settings_, the Homepage of the chosen theme is created as a Draft instead of being set as the new static Homepage. 

Steps required to see the Homepage with demo content from the chosen theme on user's site are:
- Manually Publish the page (from Drafts)
- Set it in _WordPress.com > My Sites > Design > Customize > Homepage Settings > A static page > Homepage_ (since `Set As Home Page` option is not available for sites with `Your latest posts` active as per p7DVsv-7F2-p2#comment-24719)

**We should either warn the users about the above (as it's confusing and they cannot possibly figure it out on their own) or make sure that when a TFT is applied, the new static homepage with theme's content is set as such in _WordPress.com > My Sites > Design > Customize > Homepage Settings > A static page > Homepage_ .**

The issue is somehow related to https://github.com/Automattic/wp-calypso/issues/39073

I noticed this situation several times during Quick Start sessions.

**Context / Source**
#painpoint #user-report #quick-start-sessions

**Comment by zdenys** [comment]
Most recent case: 2667409-zen (Quick Start session)

**Comment by obenland** [comment]
@apeatling I was under the impression this was the desired behavior. Did that change?

**Comment by apeatling** [comment]
I think because it's coming up as a confusion point, and in sessions. We should revisit this, and have some designs mocked up.

**Comment by rickybanister** [comment]
@apeatling when you have a chance could you share your mockups?

CC @ianstewart

**Comment by ianstewart** [comment]
See https://github.com/Automattic/wp-calypso/issues/39073#issuecomment-580022459

**Comment by obenland** [comment]
The challenge when dealing with posts on the front page is that we have to do something with those posts, regardless of whether we pre-set the new homepage template as the front page in that page_on_front option or not. 

Either we'll have an empty page_for_posts option, or we have a blog page that is not part of any menus and can't be navigated to (and this doesn't even deal with possible slug conflicts). Not sure how to (best) get around that.

**Comment by ianstewart** [comment]
>  it's confusing and they cannot possibly figure it out on their own

>  it's coming up as a confusion point, and in sessions. We should revisit this, and have some designs mocked up

We should have design mocked up but it's not on anyone's roadmap at the moment and remains confusing. A month or so later. (I believe it may have been reported elsewhere earlier.)

@johnHackworth can we disable this feature until it's improved?

**Comment by lancewillett** [comment]
+1 to removing the confusing feature, and looping back to it later instead of leaving the gap in place for an unknown amount of time.

**Comment by obenland** [comment]
For my clarity, remove it only for sites where the front page is not static?

**Comment by simison** [comment]
The problematic flow illustrated:

<img width="506" alt="Screenshot 2020-02-25 at 10 07 21" src="https://user-images.githubusercontent.com/87168/75227497-f851db80-57b6-11ea-96d3-fcf7f782bb4e.png">

<img width="377" alt="Screenshot 2020-02-25 at 10 07 51" src="https://user-images.githubusercontent.com/87168/75227501-fb4ccc00-57b6-11ea-9736-6bd52e95430a.png">

<img width="273" alt="Screenshot 2020-02-25 at 10 08 37" src="https://user-images.githubusercontent.com/87168/75227510-00118000-57b7-11ea-884a-2317c9088047.png">

<img width="844" alt="Screenshot 2020-02-25 at 10 08 11" src="https://user-images.githubusercontent.com/87168/75227504-fdaf2600-57b6-11ea-9fdd-0d1023358811.png">

<img width="480" alt="Screenshot 2020-02-25 at 10 09 12" src="https://user-images.githubusercontent.com/87168/75227526-0273da00-57b7-11ea-9181-f7f1d64f39b1.png">

**Comment by simison** [comment]
We can grab this for the hackweek on Luna's board.

**Comment by simison** [comment]
Note that this switching applies only to newer "SPT themes" and there's a group of themes accessible via "more" button that this behaviour does not apply to:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/87168/75233398-7adf9880-57c1-11ea-8fb6-a010cc1b4e0a.png">

For sites that have "a static page" setting already chosen, we show this modal instead:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/87168/75233561-b37f7200-57c1-11ea-9845-c67b34b5b73d.png">

(implemented at https://github.com/Automattic/wp-calypso/pull/39436)

**Comment by yansern** [comment]
Here are my observations of the current behaviour on WordPress.com:

If your site currently uses **"A Static Post"** as your homepage setting, activating another theme will:
- Move your existing homepage post into **"Draft"**.
- Create a new homepage post as **"Published"**.
- This new homepage post **is used** immediately as your homepage.
- The popup button that shows after activating the theme is *"Edit Homepage"*.
- Your homepage setting remains **A Static Post**.

If your site currently uses **"Your Latest Posts"** as your homepage setting, activating another theme will :
- No existing post being moved into **"Draft"** (since there's no existing post set as homepage).
- Create a new homepage post as **"Draft"**.
- This new homepage post **is NOT used** immediately as your homepage.
- The popup button that shows after activating the theme is **"Customize Site"**.
- Your homepage setting remains **"Your Latest Post"**.

**Comment by simison** [comment]
> can we disable this feature until it's improved?

@ianstewart could you clarify what specifically you'd like to disable in this scenario?

**Comment by ianstewart** [comment]
> could you clarify what specifically you'd like to disable in this scenario?

Sorry for the delay — returning from some travel and time off. Right now we have a lot of potential variations here with theme switch and it's effect on homepage. What happens to the front page of your site can be very different depending on the state of your site _and_ the theme you're switching to.

It's been reported as confusing for users in it's current state — cc @kathrynwp since I know we've discussed it. My suggestion, or wondering, is if reverting back to how it used to work, will be better if we aren't working on it or improving it. (Although it sounds like, based on hack week discussions, that we are.)

**Comment by obenland** [comment]
Apologies, but I'm still not positive what exactly we're reverting.

Adding homepage templates as a draft when the front page is not static?
Or the entire feature, including switching the front page when it's static?

**Comment by ockham** [comment]
@obenland -- @yansern and I discussed this a bit during our team meetup in Vienna. Yan wrote a great recap (that also addresses what needs to happen when there's a non-static front page) over at #39700. Maybe you could give that a look and comment if that proposal makes sense?
