### ISSUE TITLE
Gutenframe: Block editor will not load in Calypso if Classic Editor plugin is active

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#39148]
I believe this is how things have always worked and I understand it may be due to some limitations I'm not aware of. However, I wanted to report it here, because it seems like Calypso should ideally favor the block editor if the user's preferences indicate they want to use it. If someone wants the ability to switch back and forth between Gutenberg and classic, they need to have this plugin installed, but that keeps them from being able to use Gutenberg in Calypso.

#### Steps to reproduce
1. Install Classic Editor plugin on Atomic site
2. Check User RC and make sure user preference is set for Gutenberg
3. Under wp-admin > Settings > Writing, set Gutenberg as the default editor, and choose the option to allow users to switch between editors

#### What I expected
To see Gutenberg in Calypso, since the user preference and site settings reflect this choice

#### What happened instead
The classic editor loads, and the only way to use Gutenberg is through wp-admin

**Comment by kwight** [comment]
> I believe this is how things have always worked and I understand it may be due to some limitations I'm not aware of.

Unfortunately, yes, this is the case at this time (and the foreseeable future). Gutenberg in Calypso is iframed (PCYsg-lwV-p2), so the editor you're seeing is actually the WP Admin editor of the JP/Atomic site, and must respect what a user would see if they were to use the site's WP Admin editor.

You're right, it's suboptimal – particularly since you can have the Classic editor installed, and have Gutenberg be the default editor (!). What would be best is if Calypso was aware of the Classic plugin's actual settings and, combined with the user's WP.com editor preference, could determine the appropriate editor. Or, the Classic plugin could have a setting to respect any available WP.com preferred editor for that user. While both are technically possible, they required enough UX work and code changes to both Calypso and the Classic plugin that we decided not to go ahead. Unless we have a surge of confusion or concern from users, I don't expect us to invest in the needed work any time soon. Thanks for checking, though 👍
