### ISSUE TITLE
[Question] What kind of 

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#39214]
Hi guys,

I am really trying to help, but I am struggling to find a task I can start working with. 

There used to be a tag to help for 'outsiders' like me, but it doesn't seem to exist anymore.

Can anyone guide me to a task that would suit me? I have a very good ReactJS background, but very limited knowledge about calypso...

Thanks!

**Comment by tyxla** [comment]
Hey @millerf! Thanks for your interest in contributing to Calypso! 🙌

Currently, we use the "good first issue" label for those issues, as recommended by GitHub: https://github.com/Automattic/wp-calypso/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

I would also suggest looking at the "contribute" page: https://github.com/Automattic/wp-calypso/contribute that contains issues that are considered good for starting. Another option is to take a look at all issues, and try to filter by a label that mirrors something that you find interesting to work on.

A good read before starting is the [contributing guide](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md), as it contains a lot of useful information for new contributors.

Hope that helps! I'll be closing that issue, but please don't hesitate to ping me or follow up here if you have any further questions. 

Thank you!

**Comment by millerf** [comment]
@tyxla Thanks for the information! 
I did look for this label in the label list, but couldn't find it (I didn't remember the exact name).

Maybe it could be a good idea to add this information in the contributing guide?

Thanks anyway!

**Comment by tyxla** [comment]
@millerf maybe this is a good idea, thanks for suggesting it!

Maybe the reason why it's not there is because it's a built-in functionality provided from GitHub. You can read more about it here: https://help.github.com/en/github/building-a-strong-community/encouraging-helpful-contributions-to-your-project-with-labels

And actually, when going to issues, new contributors can see that in the notice above the list of issues:

![](https://cldup.com/ktb9JKNbpP.png)

**Comment by millerf** [comment]
I did contribute a whiiiile... I guess that is why I didn't see it :)
Thanks anyway!
