### ISSUE TITLE
Browser Page/Tab Title is not set for posting using Gutenberg

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#39274]
#### Steps to reproduce
1. Starting at URL: wordpress.com - not title is "Following < Reader"
2. Click "Write"
3. Editor loads - note title is still "Following < Reader"

#### What I expected

Browser page title should update to reflect what I am doing - editing a post

#### What happened instead

 title is still "Following < Reader"

#### Browser / OS version

Chrome latest on macOS

**Comment by alisterscott** [comment]
@gwwar should this have been fixed in https://github.com/Automattic/wp-calypso/issues/27300 ?

**Comment by gwwar** [comment]
You're right @alisterscott it looks like the title is picking up whatever the last section was if we then visit /block-editor.

<img width="643" alt="Screen Shot 2020-02-05 at 10 41 07 AM" src="https://user-images.githubusercontent.com/1270189/73872164-09d14480-4804-11ea-95d2-9a1ddd538e99.png">

Maybe a quick one for @Automattic/cylon or @Automattic/luna ?

**Comment by sirreal** [comment]
`EditorDocumentHead` or something analagous isn't mounted with the block editor:

https://github.com/Automattic/wp-calypso/blob/0c2a0ea23c4c3dca9eee454dcfae1c6bdef2668f/client/post-editor/post-editor.jsx#L298

I took a quick look in https://github.com/Automattic/wp-calypso/pull/39635. It doesn't work quite right because the post seems to work a bit differently in redux state. It's a bit more involved and I don't plan to see it through in the immediate future.

**Comment by lancewillett** [comment]
Noting this one has a WIP pull request in #39635. Would be great to get it moving...

**Comment by noahtallen** [comment]
This was fixed in #39905

**Comment by alisterscott** [comment]
Thanks for fixing 💪

**Comment by noahtallen** [comment]
I can't take credit, @mmtr did the fix! ;)
