### ISSUE TITLE
Links in Homepage Templates linking to theme demo sites

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39315]
#### Steps to reproduce
1. Create a page on a site using a homepage template using the Balasana template
2. Visit the front end view of that page
3. Search for "View Teachers" and inspect the button link
4. Note that the button links to the theme demo site for Balasana

![image](https://user-images.githubusercontent.com/545779/74046036-6adb5280-4993-11ea-9a24-6d0758375284.png)

We should automatically update the links to be relative to the users site, remove the URLs entirely, just have them link to the homepage of the site, or link to the newly created page (to prevent a user getting lost before they update the button).

**Comment by getdave** [comment]
There are a number of options listed here, but it doesn't look like as a team we have agreed on the optimal solution.

In the interests of fixing quickly and effectively, I'd suggest going with a "placeholder" value. Something like `#` (as suggested in responses below) would probably fit the bill.

In the longer term, we should consider how we can highlight to users the actions they need to take in order to fully populate a template. For example, if the template implies links to other pages which don't exist then we need to make the user aware of this. However, this is a much larger body of work that we couldn't tackle here.

### Implementation

I'm working on a PR to modify Blocks before they are inserted into the Block preview. We could extend this in a followup PR, to also modify other blocks and switch out the links for `#`. However, I'm not totally clear how we'd script this as how would we detect the difference between a link to the hompage (valid as page exists) and a hardcoded link to a random url (invalid: doesn't exist).

It might be that the templates simply need to be _manually_ updated to use `#` instead of a hardcoded link. If this is the case then we need some template creation guideline documentation created so that this problem isn't perpetuated as templates are modified or new templates are created.

### Responses 

> We should automatically update the links to be relative to the users site

I'd be cautious about this at it would leave broken links on their site. Bad for SEO if they published and easy to miss for the user.

> ...remove the URLs entirely

I'm not sure an empty `href` attr is valid in HTML. But in the past @Automattic/ajax recalled using `#` to denote "empty not created".

> just have them link to the homepage of the site

Certainly an option.

> or link to the newly created page (to prevent a user getting lost before they update the button).

This adds a lot of other considerations that could delay an immediately usable "fix" getting out. If this is desirable then my instinct is we'd need to fully scope it out as a project.
