### ISSUE TITLE
Editor: AMP warning about post types appearing on pages when AMP is enabled

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39314]
#### Steps to reproduce
1. Starting from a site on a wpcomstaging domain
2. Create a new page
3. Check out the Status & visibility module in the Document inspector.

#### What I expected

To have it match the view of a typical .wordpress.com site with no warnings about AMP on pages …

![image](https://user-images.githubusercontent.com/545779/74043504-1c2bb980-498f-11ea-82c5-155ce07f0dcc.png)

#### What happened instead

![image](https://user-images.githubusercontent.com/545779/74043292-b808f580-498e-11ea-8e23-df7242681571.png)

**Comment by simison** [comment]
I can see this warning for Atomic site which is not staging, when editing a page that's private:

<img src="https://user-images.githubusercontent.com/87168/74534254-004e8780-4f3c-11ea-83c8-62172977408c.png" width="300" />

Clicking on link similarly leads to an error with this in the console:

> `Refused to display 'https://mikaelkorpela.fi/wp-admin/admin.php?page=amp-options' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

<img src="https://user-images.githubusercontent.com/87168/74534348-30962600-4f3c-11ea-9348-b7781dedd858.png" width="500" />

**Comment by separatelyunited** [comment]
I had a user with this warning on a Simple Site using the Maywood theme and their own custom domain that they registered with us. I had them disable AMP as a work around for now.

**Comment by rachelmcr** [comment]
I saw this issue today while editing a page on a simple site with AMP enabled. To help anyone searching on the message, here's the text:

> AMP cannot be enabled because this post type does not support it.

![Screenshot 2020-02-20 14 15 06](https://user-images.githubusercontent.com/8658164/74944156-7bf17e00-53ed-11ea-9365-9d9b1deb0c41.png)


I also observed that clicking on the link (`/wp-admin/admin.php?page=amp-options&frame-nonce=abc123`) takes me to a page with this error:

> The page requested does not exist

The AMP warning itself makes sense given that AMP doesn't work on pages (per the [support doc](https://en.support.wordpress.com/amp-accelerated-mobile-pages/)) but it seems out of place there and is more confusing given that the link doesn't work. I assume the placement is because on a post that's where the "Enable AMP" setting appears:

![Screenshot 2020-02-20 14 29 39](https://user-images.githubusercontent.com/8658164/74944153-798f2400-53ed-11ea-8922-79671414393d.png)

**Comment by geekinthegirl** [comment]
I came across this issue with a user in chat today - they had a Simple Site and were also using the Maywood theme, trying to create a gallery block and enable the Lightbox effect under the AMP settings to enlarge their image.

That said, they were trying to do this on a page rather than a post, but the post type warning was popping up as above regardless.

**Comment by separatelyunited** [comment]
I ran into this same issue with a user today on a Simple site using Morden. All their pages had the error.

**Comment by kspilarski** [comment]
Same case in pages at a simple site, using Hever theme. (2790737-zd)

**Comment by davipontesblog** [comment]
Just discussed this in a team meeting, this one is really confusing for users. Any way we could prioritize hiding this message?

**Comment by lancewillett** [comment]
The issue to fix Atomic site settings link not opening should be treated separately. In that case, the setting page exists at '/wp-admin/admin.php?page=amp-options` but isn't always reachable from the Gutenberg editor sidebar.

The Simple site change is to hide the admin notice entirely. Simple sites do not have the ability to turn on Pages and Media post type support (or future Stories and other types of AMP content). In the case of a Simple site — the admin notices should be always hidden. See change in https://code.a8c.com/D41407

**Comment by lancewillett** [comment]
Simple site fix deployed now.

Next steps for Atomic sites:

- Verify if there's a way to authorize the AMP setting link to open from Calypso block editor context. Showing the WP Admin settings page in the same iframe.
- If not, force the link to open in a new tab/window authenticated into WP Admin

**Comment by lancewillett** [comment]
Removing the High label as we solved the Simple sites issue, which wasn't solvable by end users.

Atomic "works" OK if you open the link in a new tab, so not as critical of a fix. Keeping this issue open until that is fixed.

**Comment by ianstewart** [comment]
> Atomic "works" OK if you open the link in a new tab, so not as critical of a fix. Keeping this issue open until that is fixed.

Are we forcing the new tab?

**Comment by lancewillett** [comment]
Not yet — needs fixing still.

**Comment by lancewillett** [comment]
Decided to not fix the Atomic case, because the effort to patch it is not a good tradeoff for the time spent.

In addition, we hope to soon remove the iframed block editor context and load posts and pages directly, which removes the need to fix this issue.

**Comment by simison** [comment]
> In addition, we hope to soon remove the iframed block editor context and load posts and pages directly, which removes the need to fix this issue.

That's a lot of work so likely not happening very soon.
