### ISSUE TITLE
Retrieving token to make an API call using wpcom

### ISSUE THREAD

**Issue by alicoding** [Automattic/wp-calypso#3934]
Hi,

I'm trying to create a proxy route on `wp-calypso` app, so that I can use it to retrieve drafts post/page for a specific user as per request, but wondering how `wp-calypso` currently get the token once the user is logged in? I've been debugging and looking through the code and it seems like it will be set to the `cookie`, but once I read from the `document.cookie` I don't see `wpcom_token` there at all.

I would really appreciated if anyone could point out how to get the token on server-side, so that I can use it to make an API call using wpcomjs.

Thanks!

**Comment by Tug** [comment]
Hi @alicoding,
It looks like you're trying to do fun stuff with `wp-calypso` :)

> I'm trying to create a proxy route on wp-calypso app, so that I can use it to retrieve drafts post/page for a specific user as per request, but wondering how wp-calypso currently get the token once the user is logged in?

If I understand this correctly, you're trying to make client requests on behalf of your users? OAuth sounds exactly what you need for this job and WordPress.com API does support [OAuth](https://developer.wordpress.com/docs/oauth2/) so it should be doable.

However, at the moment we did not enabled OAuth in `wp-calypso` because of a few minor issues (it is however enabled on `wp-desktop`). So the current authorization method simply uses a third-party cookie from `public-api.wordpress.com` for now. It is set when you login through https://wordpress.com/wp-login.php and since it's a third-party cookie, you won't have access to it.

If you're interested in testing OAuth before it is available (and maybe contributing ;)), we have a PR open for it. You can try it for yourself by following the instructions in the description and applying the patch: https://github.com/Automattic/wp-calypso/pull/3561

**Comment by alicoding** [comment]
Hi @Tug,

Thank you very much for your response. After enabling `oauth` in the config, now I'm able to read the cookies and was able to show the user their draft post as I was trying to do. 

I will play around more and hopefully we will send some PRs along the way to help make `wp-calypso` even more awesome in the near future!

Thanks!
