### ISSUE TITLE
Layouts: Contact Form Previews are very poor in Layout Selector

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39343]
Chrome and MacOS. 

![image](https://user-images.githubusercontent.com/545779/74170636-d707c180-4bf2-11ea-8e66-06ae33c5021a.png)

![image](https://user-images.githubusercontent.com/545779/74170680-ee46af00-4bf2-11ea-9f9c-5c4eacd2eb81.png)

![image](https://user-images.githubusercontent.com/545779/74170695-f56dbd00-4bf2-11ea-9c24-7c1194553f71.png)

Strange borders and Hard-to-read text that don't appear in the Editor or on published pages.

@iamtakashi @alaczek

**Comment by ianstewart** [comment]
The placeholder for the contact form here in the Maywood layout could be seen as looking like it's broken in a different way …

![image](https://user-images.githubusercontent.com/545779/74182510-d2e69e80-4c08-11ea-8e45-d11197cad3ec.png)

… in that it's not providing a preview of the final result.

**Comment by marekhrabe** [comment]
I think we've hit the problem with the intro screen of the form block before. I believe it was dismissed for the user by setting an attribute on the block. That way they immediately saw real form fields in both preview and editor. Disadvantage being they are not guided to set their email and subject and block will use some default ones

**Comment by obenland** [comment]
The borders are caused by https://github.com/Automattic/jetpack/blob/ca039e9b2a22d183c0b98c0393edda6e2b2503e7/extensions/blocks/contact-form/editor.scss#L84-L105

**Comment by iamtakashi** [comment]
> The borders are caused by...

The same CSS is used in the editor too, but the form looks fine in the editor. Why do they appear differently between the editor and the preview then? 

Some CSS from core Gutenberg that is loaded in the editor seems to be missing in the preview. `block-editor/style.css`

**Comment by getdave** [comment]
> The placeholder for the contact form here in the Maywood layout could be seen as looking like it's broken in a different way …

@ianstewart This looks to be a separate issue to the "borders". Therefore I've split out to avoid confusion:

https://github.com/Automattic/wp-calypso/issues/39663

**Comment by getdave** [comment]
> The borders are caused by https://github.com/Automattic/jetpack/blob/ca039e9b2a22d183c0b98c0393edda6e2b2503e7/extensions/blocks/contact-form/editor.scss#L84-L105

> Some CSS from core Gutenberg that is loaded in the editor seems to be missing in the preview. `block-editor/style.css`

@obenland has correctly identified that the border colors are added by Jetpack. However, the border appearing is actually caused by what @iamtakashi identified: the lack of the Core Gutenberg styles for `.block-plain-text` being applied within the preview.

Specifically it is [this missing `border: none;` rule](https://github.com/WordPress/gutenberg/blob/ef73ed07bd59bdcbbe77cc1c537299d8e39167b1/packages/block-editor/src/components/plain-text/style.scss#L7) that is _allowing_ the borders to appear on `textarea`s:

```scss
.block-editor .block-editor-plain-text {
	box-shadow: none;
	font-family: inherit;
	font-size: inherit;
	color: inherit;
	line-height: inherit;
	border: none; 
	padding: 0;
	margin: 0;
	width: 100%;
}
```

I'm not sure why the editor styles aren't being applied. However a quick fix is simply to add the necessary `border:none` in the Jetpack CSS ruleset and then re-apply it on `:focus`/`:hover`.



https://github.com/Automattic/jetpack/blob/ca039e9b2a22d183c0b98c0393edda6e2b2503e7/extensions/blocks/contact-form/editor.scss#L84-L105

**Comment by getdave** [comment]
> I'm not sure why the editor styles aren't being applied within the preview. 

I'm currently investigating this. I will update this comment with details.

#### Progress

Use the following selector to search within devtools `Elements` panel to find the necessary elements:
`block-editor-plain-text jetpack-field-label__input`

**Comment by retrofox** [comment]
> Therefore I suspect we are missing the `.block-editor` class in the DOM hierarchy within the preview.

This is a very good catch, Dave!
