### ISSUE TITLE
Gutenboarding: Make sure that support sessions don't affect persisted data

### ISSUE THREAD

**Issue by jeraldjuice** [Automattic/wp-calypso#39345]
A followup from #37849 

It looks like support sessions shouldn't be an issue during the onboarding flow, but it can't hurt to verify. If they are, then we'll need to remove the persistence plugin for that condition. (See: #39310)

**Comment by simison** [comment]
@ramonjd Are you familiar with support sessions support (ha!) in old signup flows? I'd imagine that support sessions should work at least when authenticated user is in the flow?

**Comment by ramonjd** [comment]
> Are you familiar with support sessions support (ha!) in old signup flows? I

I only have very superficial knowledge of it. Whenever we start looking at it @southp might be a good person to speak to, or at least he'll be able to provide more insight than me.

> I'd imagine that support sessions should work at least when authenticated user is in the flow?

**Comment by southp** [comment]
Ah! A good antique name from the good old days :) Nowadays it is part of the user switching functionality. Would an authenticated user go through the new onboarding flow? I imagine they would when they want to create new sites. If so, we should definitely remove the persistence plugin from there, since it's very legit that a HE would SU as a user and try the flow for troubleshooting.

**Comment by simison** [comment]
Likely safe to close :-)
