### ISSUE TITLE
Twitter sharing button shows code for apostrophe in post titles

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/wp-calypso#39353]
When sharing a post to Twitter, if the post title has an apostrophe it is shown as `&#039;` instead of the apostrophe.

I was able to replicate this on my test simple site.

Screenshot:

![Screen Shot 2020-02-07 at 11 57 03 AM (1)](https://user-images.githubusercontent.com/5779512/74185225-68802f00-4c05-11ea-8e0b-7004020154d5.png)

This was when I tried to share this post via the Twitter sharing button: https://gwentestsite733700880.wordpress.com/2020/02/07/testing-apostrophes/

#### Steps to reproduce
1. On a simple site, create a post with an apostrophe in the title. Make sure the Sharing buttons are on.
2. Publish the post and view the page.
3. Click on the Twitter sharing button and you will see any apostrophe's are converted to code.

#### What I expected
To see an apostrophe instead of code

#### What happened instead
There was `&#039;` in the apostrophe's place

#### Browser / OS version
Chrome, Mac
https://whatsmybrowser.org/b/YHKW847

#user-report

**Comment by gwensmithx** [comment]
Originally reported on 2698792-zd

**Comment by simison** [comment]
cc @chriskmnds @andrewserong

**Comment by andrewserong** [comment]
Thanks for the ping @simison and for reporting @gwensmithx!

I've tested this out on a Gutenberg Edge test site with a newly create post, and it looks like it'll be resolved after the upgrade to Gutenberg 7.4.0 or later:

![image](https://user-images.githubusercontent.com/14988353/75495153-f59ef280-5a11-11ea-9c29-2b7b0cab4f8b.png)

I've added this issue to the Ganon project board — I'll leave this open until after we've done the upgrade and updated existing titles ( pbAok1-f8-p2 ) so that we can test.

**Comment by aisajib** [comment]
A user in #19094636-hc reported the issue as well. Noting here as I promised a follow-up email once this is fixed.

**Comment by noahtallen** [comment]
@gwensmithx, I went to your test site and tried to use the twitter button. It looks like this is working now!

<img width="827" alt="Screen Shot 2020-04-06 at 2 02 11 PM" src="https://user-images.githubusercontent.com/6265975/78604827-3fe47200-780f-11ea-940f-d920fbf6ca11.png">

Please let me know if you continue seeing the issue, and we can reopen this. There was some weird stuff in Gutenberg surrounding the post titles encoding which should now be fixed.
