### ISSUE TITLE
Layouts: Dalston Preview looks Broken

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39350]
Chrome and MacOS. The Dalston preview looks broken unless it's active in Dalston.

![image](https://user-images.githubusercontent.com/545779/74182228-489e3a80-4c08-11ea-8a0e-1c07ba3ffb9e.png)

@iamtakashi @alaczek

**Comment by obenland** [comment]
Should we exclude the Dalston homepage template from the selector? Looks like it might be a bit too opinionated to work in other themes?

**Comment by alaczek** [comment]
> Should we exclude the Dalston homepage template from the selector?
The portfolio layout is quite nice, so I personally would like to see if we can find a way to keep it. It would also be good to know what makes it look so broken in the preview, so that we know what to avoid or how to get around this kind of issue.

Would it be possible to not show the overlay texts in the preview? They are created with cover block using "Hover reveal" style, and are not visible in the editor (unless you hover over an item). They behave the same way on the frontend, so showing them all in the preview feels buggy.

**Comment by alaczek** [comment]
Issue created here: https://github.com/WordPress/gutenberg/issues/20402

**Comment by marekhrabe** [comment]
Since the core inclusion for the new style, optimizing its accessibility (showing on `:focus`) and the release cycle puts this at an unknown future date, should we remove the Dalston template in the meantime as it requires theme specific features and doesn't look its best without it?

**Comment by alaczek** [comment]
What do you think @ianstewart? It looks extra bad in Maywood because of the shadow text effect, it doesn't look as bad in other themes. Here's an example from Hever:

![image](https://user-images.githubusercontent.com/4550351/75830934-404fae80-5e06-11ea-9220-01d30ccdcc69.png)

**Comment by iamtakashi** [comment]
The text-shadow has come up as a problem more than once. Since we can't get rid of the shadow abruptly, it'd be worth to try making a block style variation that is without a shadow in Maywood, and make it default.

**Comment by ianstewart** [comment]
> it'd be worth to try making a block style variation that is without a shadow in Maywood, and make it default

This seems like a good solution.

**Comment by ianstewart** [comment]
Marking this as closed with that theme issue above closed last week.
