### ISSUE TITLE
Gutenboarding: can we apply different global styles to a bigger preview easily?

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39513]
Consider a step like this in Gutenboarding:

![image](https://user-images.githubusercontent.com/87168/74739677-0e651680-5262-11ea-915b-0c52ccfb526f.png)

Can we easily apply global styles to a dynamic preview being shown with currently available tech?

wpcom global styles code [is in Calypso](https://github.com/Automattic/wp-calypso/tree/5e81be3dcc2cd70c1ed544e9f3ab18f1a0d07314/apps/full-site-editing/full-site-editing-plugin/global-styles) — can we share that code to gutenboarding?

**Comment by Addison-Stavlo** [comment]
I have been working on trying to set fonts via the global styles properties here #39526. 

We should be able to change the heading and base fonts via the properties that were added to these themes by global styles.  However, we will need to import all required styles for blocks, themes, fonts, etc. into Gutenboarding to get this to work.  I am not quite sure what all we will require, and how we may be able to go about some of that.

It turns out our previews are not just broken in style for lack of jetpack and coblocks support.  We are missing style assets.  I have added style imports for the block library styles and one of the themes stylesheets in the PR noted above.  While it does make things render better than before, it is still incomplete and I am unsure of what other assets are needed to make it complete.
