### ISSUE TITLE
Block Editor: Welcome guide cannot be dismissed with Do Not Track enabled.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#39641]
Originally reported by @scosgro in https://github.com/Automattic/wp-calypso/issues/39132#issuecomment-581074963.

The block editor's welcome guide will sometimes reappear on later views even if the user has dismissed it. This could be due to having the Do Not Track setting enabled (at least in Firefox).

![73393156-d42ad980-42a0-11ea-9082-58c7b17fe8c9](https://user-images.githubusercontent.com/349751/75178550-2965d980-56ed-11ea-941c-c5561f01a3e9.png)

https://github.com/Automattic/wp-calypso/issues/39132#issuecomment-583705628
https://github.com/Automattic/wp-calypso/issues/39132#issuecomment-587628824

**Comment by gwwar** [comment]
For folks investigating, double check to see if this is an issue with the core Gutenberg project as well off of master. We'll want to file upstream if it is an issue.

Offhand I think we store the preference in browser storage so localStorage or indexedDB, though I wouldn't be surprised if it had moved to user preferences.

**Comment by Addison-Stavlo** [comment]
> Offhand I think we store the preference in browser storage

This is how it currently works.

> We can of course fix this ahead of core if so.
> ...though I wouldn't be surprised if it had moved to user preferences.

There is an open-issue to make this an account-wide setting.  #39320 -  a PR and Diff has been merged to support the infrastructure for this #38511 with a custom dotcom Welcome Guide.  However, the functionality has not been launched as it was recommended to wait for design to come up with custom content for the dotcom version.  

One option would be to essentially copy the core welcome-guide content into our version and launch it that way in the meantime.  However, when this launches the welcome guide will pop up for every user that loads the editor (once, on their first time loading it after the launch).  This is one reason we were waiting on custom dotcom content, but if we really need to fix this sooner rather than later then launching with a copy of core's content could be an option.

**Comment by yamphoenix** [comment]
The user has requested to turn off the block editor popup in this ticket also - #2699828-zen

**Comment by noahtallen** [comment]
The welcome guide will become an account-wide option within the next day or two when the FSE plugin is synced with wpcom. This means if the user dismisses the modal once, they should not see it again for any site (unless they manually bring the welcome guide back up through the options).

<img width="389" alt="Screen Shot 2020-03-03 at 1 21 37 PM" src="https://user-images.githubusercontent.com/6265975/75828330-6fabe000-5d60-11ea-994f-32442514a22a.png">
