### ISSUE TITLE
Me: 2FA: Improve the 2FA popup dialog

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#400]
Currently when your 2FA cookie expires you see a dialog asking you to verify your login with the six digit code. The placeholder on the input displays '123456' which could confuse users. Also the submit button should be disabled until there is something in the verification field.

Before:
![screen shot 2015-06-30 at 10 42 35 am](https://cloud.githubusercontent.com/assets/437258/8433660/2076ef68-1f15-11e5-9d78-aed3e5408434.png)

Ideally:
![screen shot 2015-06-30 at 10 44 08 am](https://cloud.githubusercontent.com/assets/437258/8433663/21ed96b2-1f15-11e5-951a-c92816de2d17.png)

Suggestion:
The text could also be greyed out a bit more to indicate it's a placeholder.

**Comment by v18** [comment]
More suggestions from #49:

1. Perhaps the text should be a placeholder such as "6 digit code"
2. make the color different for the example verification code

> "but because the color was so slight it looked like it should be a proper input not a placeholder"

**Comment by ebinnion** [comment]
Personally, I think entering `••••••` in the placeholder might be just as, or even more, confusing as the `123456` that we have now.

I'd opt for either:
1. Make placeholder be a string such as "Enter your 6 digit code..." 
2. Not have a placeholder

In regards to the placeholder color, I believe that is currently handled globally. We could change it for our component, but I'd prefer to have the conversation with designers on whether that's a change we need to make globally. So, cc @MichaelArestad and @melchoyce who are contributors to the `_forms.scss` file.

**Comment by MichaelArestad** [comment]
The placeholder should be an example and not a label or tooltip. We can do something to make it clear, but it should keep similar formatting to a filled in version. `123456` > `e.g. 123456` or something like that.

The placeholder color has been brought up before. It's not likely to change because it has to keep at least that high of a contrast.

> cc @MichaelArestad and @melchoyce who are contributors to the _forms.scss file.

Wow. I guess no one touches this much. It should be totally scrapped eventually as we move toward componentizing everything in there.
