### ISSUE TITLE
Gutenboarding: add site language switcher

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40011]
Add language switcher to the header — it'll change the UI language of gutenboarding and most importantly site's language.

Imagine a situation where Spanish customer is creating an English site.

<img width="962" alt="Screenshot 2020-03-10 at 11 16 37" src="https://user-images.githubusercontent.com/87168/76297647-dd0bc380-62c0-11ea-9ff9-69acaade0377.png">
<img width="920" alt="Screenshot 2020-03-10 at 11 17 01" src="https://user-images.githubusercontent.com/87168/76297666-e4cb6800-62c0-11ea-8706-7258e8ec7fac.png">
<img width="914" alt="Screenshot 2020-03-10 at 11 17 09" src="https://user-images.githubusercontent.com/87168/76297664-e432d180-62c0-11ea-8507-73e401e69286.png">

**Questions**
- Note language picker component in Calypso: https://wpcalypso.wordpress.com/devdocs/design/language-picker — can it be re-used?
- If the user is authenticated, should we change their locale for the rest of Calypso or just site locale? 
  - Should we still update the UI locale when they're authenticated, even if we wouldn't update user's locale? After creating the site in whatever language, they'd get dropped back to Calypso in their own locale.

Context p7rd6c-2dV-p2

**Comment by yansern** [comment]
I'm exploring the possibility to reuse `LanguagePicker` component.

I think the `LanguagePicker` button component can't be reused, but the `LanguagePickerModal` component can be reused with CSS overrides from the gutenboarding end to make it look like the new design.

The only trouble is the "Select your site language" heading which may require modifying the `LanguagePickerModal` itself, otherwise, a nasty JS injection.

**Comment by yansern** [comment]
For the part that does the actual language switching, probably use the `setLocale()` method in `@wordpress/i18n`? I see `react-i18n` pulls the locale from there.

**Comment by simison** [comment]
Thoughts from @sirreal via p1584087489446600-slack-luna:

>- There’s potential to reuse some UI, but if we have different designs maybe not worthwhile.
> - There’s a component near the gutenboarding root that stores the languageData and passes it to the react-i18n Provider. My idea for implementation is that this component would add another Provider for language switching, it might provide available languages, but primarily would provide a callback to change the language. The language picker would use this context to change the language and the component would handle fetching the new language data.

**Comment by ramonjd** [comment]
Just capturing a conversation with @simison from  p1591075525152100-slack-CNMU1UHHB

> In perfect world with endless time, I’d love to;
> - Implement the language modal for us from core components :tada:
> - Replace Calypso language modal with one built from core components :tadaco:
> - Offer that to core to replace the ugly <select> we now have in settings page. :taco-rocket:
> - Once it’s in core, replace ours with core one

**Comment by sirreal** [comment]
I shared some general thoughts about i18n in Calypso that will help lay the foundations for this: https://github.com/Automattic/wp-calypso/issues/42836

https://github.com/Automattic/wp-calypso/pull/39627 has some sketching that's functional but rough. It would be straightforward to implement the language switcher on top of the work in https://github.com/Automattic/wp-calypso/pull/39627 once it's been polished.

Gutenboarding has served as a proving ground for novel i18n approaches and they seem successful so far. I hope that in the near future we're able to share the approaches back to Calypso at large. https://github.com/Automattic/wp-calypso/issues/42836 outlines an approach to make that happen.

I think it makes sense to get the language switcher implemented in Gutenboarding because I believe it's the final feature we should support before our solutions become valid for the rest of Calypso. I'm happy to collaborate and support these efforts and https://github.com/Automattic/wp-calypso/pull/39627 serves as a good base 👍
