### ISSUE TITLE
Gutenberg NUX welcome modal: hide per user, not per site-per-user 

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40040]
The welcome guide was enabled for .com in https://github.com/Automattic/wp-calypso/pull/38511

Via @lancewillett  at https://github.com/Automattic/wp-calypso/pull/38511#issuecomment-597461834:

> ith the core guide I find it very annoying to see the tutorial on every internal P2 site that I change over to the block editor (per user, per site).
> 
> How might we only show it once per user (regardless of the site where they are opting in)?
> 
> With a typical end user, this might be less of an issue, of course.

@olaolusoga @joanrho @dubielzyk thoughts on this?

**Comment by lancewillett** [comment]
Another related thought: 

If hidden after a first view (any site, same user) — is there an easy way to relaunch it? Self-help where someone wants to watch the tutorial again.

Rather than interrupting the editing flow (blocking a user) — how might we make it available but non-blocking?

**Comment by simison** [comment]
Good question! It's available on the three dots sidebar right now, tho might move to another place in future: https://github.com/WordPress/gutenberg/pull/19499

**Comment by olaolusoga** [comment]
It should only show once per user—most folks have 1 site. I think Automatticians are unique cases. 

We can set a rules:
If it's a person first site, we should show the modal
If it's a second or more site, we don't, since they are now familiar with the editor. 

Since we still have duplicate sites issue, this is something we should consider after we've fixed that bug (unless it's a minority of folks who land on the duplicate site issue)

**Comment by noahtallen** [comment]
This was solved in #39846. It should now only appear one time per user. If you dismiss it again, you will not see it any again. This change probably wasn't deployed at the time the issue was reported here! The FSE update containing the change had to be rolled back, but it should be live now. Please let us know if you continue seeing the issue.

**Comment by noahtallen** [comment]
working on the Atomic fix here: #40081
