### ISSUE TITLE
Block-Editor: Preview then Back goes to MySites Root

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#40061]
Originally reported by @carinapilar, it appears that the current preview flow may take us to MySites root instead of the originating section like Pages since we're not using the iframe preview.

### To Reproduce
1. Start from WordPress.com/pages and select a site
2. Click on Add new Page
<img width="1223" alt="Screen Shot 2020-03-11 at 9 43 57 AM" src="https://user-images.githubusercontent.com/1270189/76442192-ca0af900-637d-11ea-819c-16e165a9010f.png">
3. Select a Page Layout
<img width="1227" alt="Screen Shot 2020-03-11 at 9 44 32 AM" src="https://user-images.githubusercontent.com/1270189/76442218-d55e2480-637d-11ea-906b-3afdea8aeaa5.png">
4. Publish
<img width="1237" alt="Screen Shot 2020-03-11 at 9 46 46 AM" src="https://user-images.githubusercontent.com/1270189/76442243-df802300-637d-11ea-9135-a36d1c3151db.png">
5. In the Post Publish Pane, click on Preview. This goes directly to the site in the current tab, and not in an iframe.
<img width="300" alt="Screen Shot 2020-03-11 at 9 41 37 AM" src="https://user-images.githubusercontent.com/1270189/76442297-f7f03d80-637d-11ea-9274-111d66ed278a.png">
6. From the published page, click the back button which takes us to the block editor.
<img width="575" alt="Screen Shot 2020-03-11 at 9 41 53 AM" src="https://user-images.githubusercontent.com/1270189/76442323-04749600-637e-11ea-80b0-1f196f4842ee.png">
7. Click the back chevron in the block-editor
<img width="668" alt="Screen Shot 2020-03-11 at 9 47 55 AM" src="https://user-images.githubusercontent.com/1270189/76442359-122a1b80-637e-11ea-8765-0e046e1578a8.png">

Expected: We navigate back to the Pages section
Actual: We navigate to customer home (MySite root section).

Not sure if we meant to use this type of preview for the post-publish step, but let's see if it's possible to preserve back functionality.

**Comment by noahtallen** [comment]
So the way the back button currently works is that when the iFrame is loaded, the Calypso JS context sends it the correct URL to go back to (for example, `/home`). However, when Calypso JS context is destroyed by navigating to a new page in the same tab, it does not know the last URL you were on any more, since the redux state from your previous visit to Calypso is gone. so when the calypso context loads again when you re-enter the editor, it is just using a default value or location. I assume that's what is causing the bug, anyways 😁  

I think the easiest way to fix this issue is to open "view page" in a new tab. (which makes more sense to me personally anyways) I'm not sure if it's worth the time trying to implement a different approach. Plus, the new g2 preview gives you an option to "preview externally", which opens the page in a new tab (so, similar behavior).

**Comment by noahtallen** [comment]
also, i want to note that we'll have to contribute this in Gutenberg since that is where the panel lives.

**Comment by ockham** [comment]
Update, the button in Step 7. is now actually labeled 'My Home', which might at least set expectations more properly (even though it's still debatable if that's the right target for that button to point to):

![image](https://user-images.githubusercontent.com/96308/89641676-7e1f9a00-d8b2-11ea-816a-e395989538d5.png)

**Comment by noahtallen** [comment]
> Update, the button in Step 7. is now actually labeled 'My Home', 

IIRC, this is only the case on a dotcom-FSE site :/
