### ISSUE TITLE
(8P) Masterbar: Unequal spacing between masterbar icons on first mobile page load

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#40060]
#### Steps to reproduce
1. Starting on a mobile device, open WordPress.com while logged in: https://wordpress.com/
2. Notice that the space between the Me and Notifications icon is greater than between other icons.
3. Navigate around Calypso and notice that eventually (e.g. after opening the Reader) the icon spacing fixes itself.

#### What I expected

I expect the icons to always be equally spaced.

#### What happened instead

On first page load on a mobile device, the icons have unequal spacing.

#### Browser / OS version

Safari / iPhone XS, iOS 13.3.1

#### Screenshot / Video

<img src="https://user-images.githubusercontent.com/8658164/76441258-0870da00-63b7-11ea-97b4-10fbdbf47f51.png" width="50%">

#### Context / Source
#dogfooding

**Comment by lancewillett** [comment]
Good eye, thanks for reporting. 

I'm seeing a weird spacing issue in desktop web with the notifications toolbar icon — it seems too wide now (Safari on macOS):

<img width="324" alt="Screen Shot 2020-03-11 at 21 00 21" src="https://user-images.githubusercontent.com/66797/76485997-53044d80-63db-11ea-85e6-e6888e1aa3fe.png">

**Comment by lancewillett** [comment]
I can repeat the mobile web issue on first load, iPhone XS with mobile Safari.

1. First load, weird spacing

<img src="https://user-images.githubusercontent.com/66797/76486239-ff463400-63db-11ea-8e3d-b4923291ccfa.PNG" width="480" />

2. Click on Reader icon in toolbar, it fixes itself

<img src="https://user-images.githubusercontent.com/66797/76486241-00776100-63dc-11ea-9e03-d8ba5dcc5a99.PNG" width="480" />

**Comment by rachelmcr** [comment]
I can also see the issue you saw in Safari desktop web, although it seems to correct itself once the page finishes loading. (I see the issue at first, but I see additional network requests e.g. for more CSS files after which the spacing is fixed.)

I took a closer look at the mobile web issue with Safari's responsive design mode, and as far as I can tell it's an issue with flexbox and the `auto` margin calculations on the masterbar icons. On first page load, the right/left margins for all icons except notifications are 0px:

![Screenshot 2020-03-12 13 27 24](https://user-images.githubusercontent.com/8658164/76526665-cc488280-6465-11ea-89c7-dbf9f7b4f59d.png)

After navigating e.g. to the Reader, the right/left margins are recalculated and are equal for all the icons (including notifications):

![Screenshot 2020-03-12 13 33 11](https://user-images.githubusercontent.com/8658164/76527044-70cac480-6466-11ea-9193-dbb4e12a5493.png)

I can also force the issue to reappear on a mobile screen size by disabling this CSS:

```
@media (max-width: 480px)
.masterbar__item {
flex: 1 1 auto;
}
```

**Comment by lancewillett** [comment]
Adding to Manage team board for consideration — cc @sixhours as this feels like a Caro sweet spot. ⭐️

**Comment by gwwar** [comment]
We may need to investigate on a native device I couldn't reproduce in Chrome browser emulator.

**Comment by lancewillett** [comment]
I'm still seeing this happen each day in desktop Safari (v 13.0.5 on macOS Catalina 10.15.3).

It only appears from a cold start, such as first time in the day I load https://wpcalypso.wordpress.com/ — the notifications "bell" section is wider than it should be.

Before | After
|------------ | -------------|
|<img width="343" alt="Screen Shot 2020-03-23 at 15 48 03" src="https://user-images.githubusercontent.com/66797/77370254-bec0b180-6d1d-11ea-905e-4e7901a50503.png"> | <img width="343" alt="Screen Shot 2020-03-23 at 15 48 07" src="https://user-images.githubusercontent.com/66797/77370258-c1230b80-6d1d-11ea-968a-29f357a92b3d.png">|

**Comment by sixhours** [comment]
So far, I'm not able to reproduce either of these in the following environments:

* Chrome, iPhone 11 Pro Max, iOS 13.3.1
* Safari, iPhone 11 Pro Max, iOS 13.3.1

* Chrome 80, Mac OS 10.15.3
* Safari 13.0.5, Mac OS 10.15.3
* Firefox 74, Mac OS 10.15.3

@lancewillett when this happens on desktop, does the Network tab of the inspector show anything stalled, any 404's? Does the console show any errors?

@rachelmcr Are you still seeing the alignment issue on mobile devices? I did find some interesting anecdotal evidence to suggest that child items with `auto` margins and a flexbox parent could behave oddly in Safari, but it was from 2 years ago and seems to have been fixed since then.

**Comment by lancewillett** [comment]
No errors in console or 404s. It looks more like a calculation error in the width of the element.

Note in the first screenshot the Safari inspector gives the width value an estimate with `~126.77` (broken). I've never seen that before...

<img width="350" alt="Screen Shot 2020-03-24 at 14 01 10" src="https://user-images.githubusercontent.com/66797/77476839-977aea80-6dd8-11ea-9fe1-94eb47c5d1a0.png">

In the correct version, second screenshot — the width is `66`.

<img width="341" alt="Screen Shot 2020-03-24 at 14 01 18" src="https://user-images.githubusercontent.com/66797/77476842-99dd4480-6dd8-11ea-84e8-6a6ce2d50cb3.png">

I'm able to trigger most successfully using `wpcalypso` instead of production.

**Comment by sixhours** [comment]
Aha! I was able to reproduce this on `wpcalypso` when I switched my primary site to a site that has My Home (my normal primary site is a Jetpack site, so My Home isn't available, and I land on the Stats page). This points to something about My Home, specifically.

**Comment by gwwar** [comment]
TIL about cmd+option+R for the mobile previews on Safari!

Overall, I think it's the flex rule on `.masterbar__item` The media query might need to be updated. It's only applied to screens 480px and smaller.

| Flex: 0 1 auto | Flex: 1 1 auto |
| ------------- | ------------- |
| <img width="1288" alt="Screen Shot 2020-04-08 at 4 40 32 PM" src="https://user-images.githubusercontent.com/1270189/78843714-7c070680-79b8-11ea-8ba8-84970028c1ef.png"> | <img width="1238" alt="Screen Shot 2020-04-08 at 4 40 40 PM" src="https://user-images.githubusercontent.com/1270189/78843768-ace73b80-79b8-11ea-9f62-616d8ca570d5.png"> |

@sixhours do you want to give this a try? I don't have an iPhone :D

**Comment by lancewillett** [comment]
> I don't have an iPhone :D

One technique I use to test iOS devices "natively" is the Xcode Simulator.app — you can test on any Apple device.

<img width="708" alt="Screen Shot 2020-04-08 at 17 03 19" src="https://user-images.githubusercontent.com/66797/78844529-dacd7f80-79ba-11ea-81b5-5156ec810741.png">

**Comment by gwwar** [comment]
Some bugs can only be reproduced on a native device, and xcode wasn't cooperating today

**Comment by obenland** [comment]
@davemart-in In backlog grooming the question came up if this one would be a good fit for the Manage Janitorial Board?

**Comment by davemart-in** [comment]
I don't think so. I suspect that due largely to the testing that is going to be required that this is going to turn into more than just a tiny little fix.

**Comment by cpapazoglou** [comment]
I am trying to reproduce this bug without success. I have tried (Catalina 10.15.5):

Safari (13.1.1): both on desktop and responsive view
Simulator: iPhone SE 2 & iPhone 11 Pro

I also made sure to land on Home page of my site as @sixhours suggests. Apart from that, I cannot spot the code that could potentially cause these issues (in the current codebase).

I assumed that a network delay could potentially cause this issue but the css in question `client/layout/masterbar/style.scss` is among the first assets loaded. Also, it would not explain the reload needed so that it is fixed. That said, I also don't believe that moving 

 ```
@include breakpoint-deprecated( '<480px' ) {
		flex: 1 1 auto;
}
```

before 

```
.masterbar__item {
	flex: 0 1 auto;
```

is the solution.

So, to move on:
1) @lancewillett  Does this still reproduce?
2) is anyone (affected) willing to have a zoom session anytime in the 06:00 - 14:00 UTC window?

**Comment by rachelmcr** [comment]
I can no longer reproduce this behavior on my phone (Safari on iPhone XS, iOS 13.5.1) or on my laptop (Safari 13.1.1 on macOS 10.15.5, desktop and responsive view).

I see some unequal spacing as the page loads, but unlike the original report the spacing ends up equal once the page finishes loading.

From my end it looks like this is resolved but I'll wait for @lancewillett to confirm on his end.

**Comment by obenland** [comment]
I can't reproduce it either. Tried loading the stats page of a jetpack site (no My Home), loading My Home on a simple site, loading the reader, on wpcalypso, horizon, and production wp.com.

**Comment by rachelmcr** [comment]
Thanks for the confirmation. Let's go ahead and close this issue, and @lancewillett can reopen if it's persisting for him.
