### ISSUE TITLE
Jetpack purchases: Poor color contrast on hovering over checkout buttons

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#40128]
#### Steps to reproduce 

- Start with a Jetpack site
- Add a plan to cart
- Continue through the checkout process
- Hover over the payment confirmation button

#### What is expected 

The color contrast is fine.

#### What happens instead 

The color contrast is poor. 

Below images are with and without hover, respectively.

<img width="1019" alt="Screenshot 2019-03-28 at 20 38 26" src="https://user-images.githubusercontent.com/18581859/55169919-a1edae80-519b-11e9-947f-3c60b22495bf.png">
<img width="1104" alt="Screenshot 2019-03-28 at 20 38 30" src="https://user-images.githubusercontent.com/18581859/55169920-a1edae80-519b-11e9-9fa0-bf2d4721ffe1.png">

#### Other product purchases

For other product purchases, say a WordPress.com purchase, the hover contrast appears to be fine. Below images (without and with hover)

<img width="1321" alt="Screenshot 2019-03-28 at 20 50 27" src="https://user-images.githubusercontent.com/18581859/55169879-913d3880-519b-11e9-8fb7-b9a97ba749e3.png">
<img width="1323" alt="Screenshot 2019-03-28 at 20 50 32" src="https://user-images.githubusercontent.com/18581859/55169881-913d3880-519b-11e9-9c83-3418cc894a1a.png">

Tested with `Classic bright` color scheme, but I think Jetpack purchases are independent of the chosen scheme. (Edit to clarify: The first two images may be from Powder Snow and not Classic Bright)

cc @Automattic/jetpack-design for thoughts.

**Comment by keoshi** [comment]
I'll be looking at this in the upcoming HACK week.

**Comment by keoshi** [comment]
The button has since suffered some changes and the color on `:hover`/`:focus` is now much darker at `rgb(0, 113, 23)`. This gets a contrast ratio of 6.22, almost AAA level and comfortably above AA level.

![image](https://user-images.githubusercontent.com/390760/110344941-f35c7480-8025-11eb-86f4-3cedafe1c4a5.png)

![image](https://user-images.githubusercontent.com/390760/110344989-ff483680-8025-11eb-807c-724061600e4e.png)

Closing this one.
