### ISSUE TITLE
Broken domains-landing page in Edge 44

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#40328]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/domain-services/registrant-verification

#### What I expected
To get _any_ screen, probably this error one (because of missing parameters):
<img width="750" alt="Screenshot 2020-03-20 at 14 49 48" src="https://user-images.githubusercontent.com/3392497/77175188-16f77980-6aba-11ea-8566-fb6ce2de6b10.png">

#### What happened instead
Blank screen, nothing gets loaded.
There's a `'globalThis' is not defined` error in the console. The code is minified, but it pretty clearly points to this line:

https://github.com/Automattic/wp-calypso/blob/e15c64ac27e9a85f1b76f59800cfb275461b6697/client/my-sites/media-library/proxied-image.tsx#L13

Looks like it was introduced in https://github.com/Automattic/wp-calypso/pull/38313 cc @sgomes 

As @jsnajdr noticed in https://github.com/Automattic/wp-calypso/pull/38313#issuecomment-564073429, `domains-landing` (and gutenboarding) entrypoint was not loading the polyfills. There was a [follow-up issue created for Gutenboarding](https://github.com/Automattic/wp-calypso/issues/38336), but unless I'm mistaken, not one for domains-landing and no one from Cobalt was notified that this change could potentially break our landing pages. And it seems it exactly did that - we have a very long list of reports from users/HEs in p2MSmN-7Mj-p2. Looks like Edge and old Safari versions are impacted.

#### Browser / OS version
Windows 10, Edge 44.18632.449.0

#### Screenshot / Video
![Image from iOS](https://user-images.githubusercontent.com/3392497/77175443-92f1c180-6aba-11ea-8f0e-a63f962db71c.jpg)

#### Context / Source

#dogfooding, #manual-testing

**Comment by klimeryk** [comment]
Potential fix in https://github.com/Automattic/wp-calypso/pull/40331

**Comment by sgomes** [comment]
> Looks like it was introduced in #38313 cc @sgomes

To clarify, the issue was not introduced in #38313, as that only enabled support for `globalThis` in the common polyfills, without requiring anything to use it. The issue was introduced in later code that modified `proxied-image.tsx` to use `globalThis` once support was in place.

**Comment by klimeryk** [comment]
Right - but https://github.com/Automattic/wp-calypso/pull/39616 doesn't seem to touch domains-landing (probably indirectly by pulling in some tangled dependency that's not really used). What I meant was that since #38313 this exact situation was a possibility. There was a talk of following up with gutenboarding and domains-landing entrypoints, but seems it happened for gutenboarding, but not domains-landing. And I'd love to avoid such regressions in the future.

**Comment by sgomes** [comment]
> Right - but #39616 doesn't seem to touch domains-landing (probably indirectly by pulling in some tangled dependency that's not really used). What I meant was that since #38313 this exact situation was a possibility. There was a talk of following up with gutenboarding and domains-landing entrypoints, but seems it happened for gutenboarding, but not domains-landing. And I'd love to avoid such regressions in the future.

That's partly why the `calypso-polyfills` package was created later in #38660, to ensure a consistent set of polyfills across the board, that everyone can rely on, whether part of Calypso client or not.

However, since `domains-landing` never made use of any of Calypso's polyfills, it wasn't updated to use the new package. I should have been more proactive there in ensuring that this was intentional and not an oversight, absolutely, but I just want to clarify that this is entirely unrelated to adding `globalThis` support; there was already a strong possibility for failures in `domains-landing` for a lack of other polyfills.

As for avoiding the issue going forward, I believe the solution is twofold:
- Have the addition of new entry points be reviewed by team Calypso, to identify issues such as the non-use of common polyfills. I believe there was discussion of documentation on "Creating a new entry point" as well.
- Add support for the common polyfills in `domains-landing` as you've done in #40331. This makes sure that `domains-landing` is always up-to-date, and able to rely on the same set of polyfills.

In the meantime, I'll check if there are any other entry points missing polyfills.

**Comment by daledupreez** [comment]
For completeness, we also saw failures in a range of other browsers, so we'll be checking to see if we have continued issues.

The browsers we saw likely fall off our evergreen list, though. We saw what look like failures in the following browsers and versions based on an initial redirect and then no actual REST API call to the server:
- Edge: 44 (multiple patch versions), 42, 12.246
- IE: 11
- Chrome: 67, 49, 34
- Safari: 11.1, 10.1
- Firefox: 54, 52
- Opera: 35
- Samsung Browser: 7.2
