### ISSUE TITLE
Add more color options to Paragraph Block

### ISSUE THREAD

**Issue by bsanevans** [Automattic/wp-calypso#40348]
A user would like to see the following features added to the background color settings of the Paragraph block.

- Ability to change opacity
- Ability to soften the corners

19560174-hc 2805590-zen

**Comment by kriskarkoski** [comment]
There's a core issue opened for opacity/transparency for all blocks with background color here: https://github.com/WordPress/gutenberg/issues/18095

**Comment by lancewillett** [comment]
@kriskarkoski I have two suggestions for how to handle issues that rely on a core fix "upstream":

1. Close it with a note, and you'd personally track it later to reply to the customer.
2. Keep it open, so that we remember to check and reply to the customer once the issue is fixed and merged back to WordPress.com.

**Comment by annacmc** [comment]
Closing this up in favor of core issue opened upstream at https://github.com/WordPress/gutenberg/issues/18095 @bsanevans if you're wanting to follow up with the user, there is progress being made on this request over in that thread you can follow.
