### ISSUE TITLE
Question: Why is jetpack needed to allow calypso connect to a local site

### ISSUE THREAD

**Issue by mwoodpatrick** [Automattic/wp-calypso#40358]
I am doing local testing of WordPress under an Ubuntu container running under WSL-2. Why is jetpack needed to allow calypso to connect to a local site it seems that REST should work without the need for a remote server to be able to access my site. What am I missing?

The error I'm getting is:

	The Jetpack server was unable to communicate with your site https://my-wp.loc [IXR -32300: transport error: http_request_failed cURL error 6: Could not resolve host: my-wp.loc]

**Comment by lancewillett** [comment]
This depends on the type of WordPress site you're managing with Calypso. For most WordPress.com sites, Jetpack isn't required as an active plugin because we don't run it the same way as a self-hosted WordPress site would (WordPress.com is a multi-site instance, and syncs code with Jetpack).

For self-hosted sites, or sites on the WordPress.com Business or eCommerce plan — an active Jetpack connection is required.

==

Also, note an important feature of Calypso is it must run on the domain specified:

> Please remember to access Calypso via http://calypso.localhost:3000

From the Troubleshooting docs: https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md

**Comment by mwoodpatrick** [comment]
Why is it needed for a self hosted site? It would seem like REST should work without jetpack, what am I missing?

**Comment by lancewillett** [comment]
Which type of WordPress site are you connecting to? Where is it hosted?

**Comment by lancewillett** [comment]
For Calypso to work with a self-hosted site requires an active Jetpack connection.

**Comment by mwoodpatrick** [comment]
This is a development site running  in a docker container on Ubuntu via WSL 2 on my desktop PC. I dont understand why authentication requires jetpack or wordpress to be in the loop when making  REST requests from calypso to my wordpress installation could you elaborate why this is needed

**Comment by lancewillett** [comment]
Yes, because Calypso is a WordPress.com project, and for any WordPress to connect to it — we built Jetpack as the bridge.

**Comment by lancewillett** [comment]
I'm going to close the question. Please refer to the docs for more troubleshooting notes: https://github.com/Automattic/wp-calypso/issues/40358#issuecomment-602881143

And, of course, for bugs and suggestions please get back in touch! Thank you, @mwoodpatrick

**Comment by mwoodpatrick** [comment]
This sounds more like a marketing reason rather than a technical one but maybe I'm missing something?
