### ISSUE TITLE
Themes: fix "business" search to show Business keyed suggestions first before "Blog" suggestions

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#40398]
Reported by @markx2 — an Automattic / WordPress.com Happiness Engineer; internal P2: p58i-8Mu-p2.

#### Steps to reproduce

1. Starting at URL: `/themes`
2. Wait a while for it to load, scroll down and click "Show All Themes"
3. Search for `business`
4. Hit "Enter" with keyboard

#### What I expected

A search box should respect what I enter.

#### What happened instead

Theme search is broken. You will be shown these results: https://wordpress.com/themes/filter/blog

The search box sees the ‘b’ but nothing after that.

#### Screenshot / Video

<img width="1120" alt="screen-shot-2020-03-24-at-08 03 24" src="https://user-images.githubusercontent.com/66797/77441412-a5b01300-6da6-11ea-82d7-72014c354326.png">

#### Context 

The cause is the "keyed search suggestions" pull up Blog filter first because the description mentions the word `business` — and `Blog` comes before `Business` alphabetically.

<blockquote>Choose from a wide variety of styles and layouts for your personal blog, professional blog, or <strong>business</strong> blog.</blockquote>

Emphasis mine.

The simplest fix will be to remove the word `business` from the blog filter description.

**Comment by lancewillett** [comment]
This should be a quick fix if anyone wants a `good first issue` to work on.

**Comment by chip** [comment]
Hi - I'm looking to contribute to my first issue, but running into a snag.

When I visit http://calypso.localhost:3000/themes, I briefly see a search page, but then it displays, "You don't have any WordPress sites yet."

I've read the Troubleshooting doc, which was helpful with other issues, but not this one. Do you have any suggestions?

Thank you.

**Comment by lancewillett** [comment]
Hi @chip Are you logged in to WordPress.com in the same browser and session? Does your WordPress.com account have 1 or more sites?

**Comment by chip** [comment]
Hi @lancewillett - Oops! I'm logged in, but didn't realize I needed to register a site to contribute.

**Comment by lancewillett** [comment]
Hehe, that's a key part of what Calypso is built for! We do have a few logged-out views like `/themes` but 99% of the app is intended for WordPress site management where site owners change their settings, check stats, and such.

**Comment by lancewillett** [comment]
It might be a fun stress test, though — to navigate logged-in Calypso with no website, and see what breaks. 😄

**Comment by chip** [comment]
Yeah, I'm a bit of a noob here and it's showing through. 😄

I've [pushed a commit to my fork](https://github.com/chip/wp-calypso/commit/89986f63d2074ad71fdbddee98d349e74eb07bbd), but it is only for a few test files.

I still haven't found where the data for the tests is coming from, but I'll dig a little deeper. Still getting familiar with the docs. Thanks for your guidance.

**Comment by lancewillett** [comment]
@chip Welcome!

Please keep asking questions as you go. Happy to also test your fork and give feedback.

One helpful thing for asking for review, is include a screenshot of the fix you're making. Or a short GIF or movie.

_Before_: current behavior
_After_: with my fix, here's how it behaves better

**Comment by chip** [comment]
@lancewillett - Thanks! Will do.

So, on my commit, I essentially removed the "business" wording from the tests and then updated the fixture data so that those 3 tests would pass. In fact, the entire test suite passed, which doesn't give me much confidence given that the bug still exists on my local machine.

Where is the seed data coming from for the theme search results?

Thanks.

**Comment by lancewillett** [comment]
I believe it comes in via a REST API request. If you inspect the Network tab of your browser, you can capture the URL used for the XHR. Then, logged in to WordPress.com, go to the REST API console here: https://developer.wordpress.com/docs/api/console/ and you can replicate the theme results in the API by inputting the same arguments.

**Comment by lancewillett** [comment]
If this change requires backend (REST API) changes — I'll remove the `good first bug` from the issue, because that is advanced and requires inside technical access.

And apologies if that's the case — I thought it was a simple text change only in Calypso.

**Comment by chip** [comment]
![Screen Shot 2020-03-26 at 5 17 50 PM](https://user-images.githubusercontent.com/31725/77702147-dac68c00-6f85-11ea-9f56-efd1a8cb775b.png)

When the page is initially loaded, it makes a number of API calls.

One goes to https://public-api.wordpress.com/rest/v1.2/theme-filters?http_envelope=1, with a response containing the data shown on the **Advanced Themes** results *(I've truncated the data because it was too verbose)*:

```
{"name":"Blog","description":"Choose from a wide variety of styles and layouts for your personal blog, professional blog, or business blog."},
```

I didn't see any relevant XHR calls to the API when typing in the word "business". It appears to me that Calypso responds too quickly for it to call the API. To be fair, I was unable to confirm the state data using React DevTools, which might be due to my lack of familiarity with the app.

I also tried using the API console, but I am getting a 404. I think this might be due to the fact that the URL call is for **v1.2**, but the API console only goes up to **v1.1**.

Please let me know if I should dig any further. Thanks.

**Comment by lancewillett** [comment]
Oh, man — I apologize. This turned out to be a simple fix on the backend, in our Theme Showcase data.

Old: `Choose from a wide variety of styles and layouts for your personal blog, professional blog, or business blog.`
New: `Choose from a wide variety of styles and layouts for your personal or professional blog.`

<img width="1262" alt="Screen Shot 2020-03-26 at 16 04 40" src="https://user-images.githubusercontent.com/66797/77704968-9fbf5b00-6f7b-11ea-9ed5-b5dca53c9471.png">

Fixed. ✅ 

Sorry @chip for the wild goose chase. Hope you'll find a different bug report to jump in on next.

**Comment by chip** [comment]
@lancewillett - No worries. Glad it got resolved. 👍
