### ISSUE TITLE
Payments Block: block does not appear on front end when nested in a Columns Block

### ISSUE THREAD

**Issue by kcswong** [Automattic/wp-calypso#40493]
#### Steps to reproduce

1. Create a Recurring Payment plan or use an existing one you already have 
2. Create a new page or post
3. Add a Columns block
4. Add Recurring Payment block in the Columns block
5. Publish the page/post

#### What I expected

For the Recurring Payment button to appear in the column on the published page

#### What happened instead

It didn't appear. Adding a Recurring Payment outside of the Column still works. 

![recurring blocks on published page](https://d.pr/i/g6PoNz+)

_Image link: https://d.pr/i/g6PoNz_

It also added a new box in the editor, like this: 

![recurring payment block in column](https://d.pr/i/odWvUe+)

_Image link: https://d.pr/i/odWvUe_

Tested across a few different themes, but the result was the same. The user's site who reported was a Simple site, and I tested on Simple as well. This appears to be working correctly on my Atomic test site, so only seems to be affecting Simple sites.

#### Context / Source
#user-report

Follow-up ticket: #2821585-zen

**Comment by thabotswana** [comment]
Another report here: #3155893-zen

**Comment by kcswong** [comment]
Another report in 23006911-hc, helped them move Payments out of the Columns block

**Comment by sirbrillig** [comment]
I think this is probably something for the Earn folks or whoever handles Recurring Payments, so I'm removing it from the Shilling team board (the log doesn't say how it got on our board, but feel free to disagree if you are the person who added it and we can discuss the issue!).

**Comment by davipontesblog** [comment]
OK, so this one took a bit of brainstorming to really dive into what's happening here. I recorded a video to show:

Droplr link: https://d.pr/v/oz6HHO/GZxfmk1yaf

Video:

https://user-images.githubusercontent.com/31009008/114721645-21109980-9d07-11eb-94f1-0c1bb0e1fc42.mov

The issue seems to happen because when adding a Payments block into a Column, the modal that appears is this:

<img width="341" alt="Screen Shot 2021-04-14 at 09 53 19" src="https://user-images.githubusercontent.com/31009008/114722099-84023080-9d07-11eb-8a92-31b0f384ddaf.png">

as opposed to this:

<img width="654" alt="Screen Shot on 2021-04-14 at 09-53-38" src="https://user-images.githubusercontent.com/31009008/114722131-895f7b00-9d07-11eb-88a6-10b08a84b518.png">

**So it's as though the modal is hidden / not triggered correctly when the block is placed in a Column, and it seems like the block needs the user to pick a plan inside that modal, before it can show the button on a preview/ front end.** As you see on the video recording, as soon as I pick a plan in the block settings sidebar for the blocks inside the columns, they immediately show on the preview/front end.

@apeatling pinging you here as you may have some thoughts on this bug. Thanks!

**Comment by Nic-Sevic** [comment]
Also happening here 29303995-hc;

Since when the payments block is in a columns block with more than 2 columns; advised user to set block settings outside columns and then move into columns

With the columns block set to 2 columns you can access the payment block settings already
