### ISSUE TITLE
Site Editor: blank screen on newly created sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#40497]
1. Create a new WP.com test site.
2. Add `gutenberg-edge` (we need v7.8.0) and `core-site-editor-enabled` stickers to it.
3. Sync latest FSE plugin master from Calypso to your sandbox.
4. Navigate to test site's wp-admin or Calypso.
5. Site Editor menu should be visible in both cases.
6. Clicking on them should load the editor but instead it's crashing with the following error:

<img width="648" alt="Screenshot 2020-03-26 at 21 55 57" src="https://user-images.githubusercontent.com/1182160/77695781-98647580-6fac-11ea-9026-43c4671be20b.png">

Interestingly enough the same code works for my existing test site, which makes me think it's related to experimental option filtering (in case it's already stored for my existing site).

**Comment by Addison-Stavlo** [comment]
> which makes me think it's related to experimental option filtering

It definitely seems to be related to this.  New sites don't have the option initialized and return `FALSE` instead of the option.  The experiment filtering method won't work on the un-initialized option like this.  Good news, is if we initialize the option to something falsy like `''` it starts to work so this will hopefully be a fairly simple fix.
