### ISSUE TITLE
Jetpack Search Plan: update design of the upsell card

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#40551]
Go to http://calypso.localhost:3000/plans/ for a free jp site

We need to update this design and the copy:

<img width="626" alt="Screen Shot 2020-03-29 at 12 37 25 PM" src="https://user-images.githubusercontent.com/820871/77857370-2b262f80-71ba-11ea-81f1-c723698bd79c.png">

**Comment by keoshi** [comment]
- **Copy**: being handled on https://github.com/Automattic/jetpack/issues/15183
- **Introductory prices**: my assumption is that we shouldn't include this element since we don't have discounts for launch.
- **Tier information/selection**: chatted with Enej last week about the design proposal on p6TEKc-3wi-p2. @enejb, do you think you'll tackle that this week? Would Search benefit from that change on both Calypso and wp-admin?

cc @robertbpugh to see if you agree with all of the above.

**Comment by enejb** [comment]
@rcanepa already stated a PR https://github.com/Automattic/wp-calypso/pull/40583 to make things look like.
https://jpopdesignp2.wordpress.com/2020/03/26/revisiting-single-product-ui-on-plans/
