### ISSUE TITLE
Customer Home: sidebar inconsistencies

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#40573]
I noticed a few small inconsistencies on the customer home sidebar. I don't have specific solutions in mind, but we should try to sync up the details across all the cards:

![image](https://user-images.githubusercontent.com/437258/77928006-e5c73800-7275-11ea-81c8-590ed9399323.png)

Things like 
* bottom margin of links
* width of buttons
* placement of text titles

**Comment by rickybanister** [comment]
The stats card also is inconsistent with the other boxes, it has a left aligned text link to see all stats instead of a non-primary button like the other cards:

![image](https://user-images.githubusercontent.com/437258/78057928-86405980-7355-11ea-9927-3d783cbee106.png)

**Comment by rickybanister** [comment]
I also noticed that the stats card differs from the commensurate card on the stats insights page:

![image](https://user-images.githubusercontent.com/437258/78058953-1501a600-7357-11ea-9771-c9d3298da217.png)

The language feels reversed on customer home—Tuesday most popular day. On the insights page 'most popular day' feels more like a label and Tuesday a value. 

We should sync up both cards since they're sharing the same info.

**Comment by gwwar** [comment]
@danhauk does https://github.com/Automattic/wp-calypso/pull/40997 fix this one?

**Comment by rickybanister** [comment]
It addresses one of the inconsistencies. The action treatment and placement is still an issue.

**Comment by gwwar** [comment]
@rickybanister can we try splitting that out to their own issues or adding a checklist? Makes it a bit easier to track what we need to do.

**Comment by rickybanister** [comment]
Feel free to track however is best for you all; as a design task I think tackling all of these together and developing a 'skeleton' or architectural model for how we treat sidebar (or any customer home) content is the first deliverable here.

**Comment by danhauk** [comment]
I think a lot of these inconsistencies are/will be addressed in the new layout currently being worked on under the `home/experimental-layout` feature flag.

**Comment by lcollette** [comment]
@danhauk Can you confirm these inconsistencies have been addressed in the new layout? If so, please close this out. :)

**Comment by danhauk** [comment]
The new layout and some followup PRs do address these inconsistencies.

* Titles are at the top of all cards.
* Images for learn and grow cards have a consistent placement to the right of the text.
* Actions and links are aligned left at the bottom of the card.
* The new stats card intentionally breaks out of these rules but still aligns with title and action placement.
* #41875 cleans up the margin/padding inconsistencies with the support card links.
* #41879 updates the mobile card to use the same link pattern instead of a full width button.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/448298/81209324-63314700-8f9e-11ea-8d75-490438deac15.png">

<img width="282" alt="image" src="https://user-images.githubusercontent.com/448298/81209488-9a075d00-8f9e-11ea-832c-641e629b53e3.png">

<img src="https://user-images.githubusercontent.com/448298/81206767-92de5000-8f9a-11ea-9bd7-e4664da2be3e.png" alt="image">

**Comment by rickybanister** [comment]
Thanks @danhauk !
