### ISSUE TITLE
New drafts don’t automatically save slug

### ISSUE THREAD

**Issue by alicoding** [Automattic/wp-calypso#4059]
I'm not sure if this is the right place to file a bug for this nor this is an actual bug...

When we create a new page on wordpress.com using Calypso, it doesn't automatically save the slug for unpublished page (draft was saved) when you try to read it from the API call

STR:

1. Create a new page
2. Add a title
3. Save a draft (Or it will automatically saves it for you)

Expected result:

The object that returned from the API call should have slug name in the `slug` property.

Actual result:

```
{
  "ID": 2,
  "author": {
    ...
  },
  "content": "<p>first post test here</p>\n<p>&nbsp;</p>\n<p>now we have draft right?</p>\n",
  "excerpt": "<p>first post test here &nbsp; now we have draft right?</p>\n",
  "slug": "", // This is empty
  "status": "draft",
  "other_URLs": {
    "suggested_slug": "test" // This is actually here
  }
}
```
The `slug` property doesn't have `slug` name in it, but you can see it in `suggested_slug`

**Comment by aduth** [comment]
Hi @alicoding , this is in-fact the expected behavior. When drafting a post in WordPress, it's quite possible that you'll change the title of your post several times before you decide to publish, thus a slug is typically not assigned until the time of publish, or if you explicitly set your own slug.

Here's the relevant bit of code from WordPress's `wp_insert_post` function:
- https://github.com/WordPress/WordPress/blob/4045562/wp-includes/post.php#L3135-L3153

Within our own codebase, we have a few functions that allow us to derive the intended slug for a given post:
- https://github.com/Automattic/wp-calypso/blob/04f7a94/client/lib/posts/utils.js#L191-L197
- https://github.com/Automattic/wp-calypso/blob/04f7a94/client/lib/posts/post-edit-store.js#L59-L84

You'll see that as soon as you publish your post, the response payload will include an assigned slug value. If you don't provide your own slug, the slug will reflect a sanitized and deduplicated version of the post title.

If you _do_ assign a slug, from either "More options" accordion or the link icon adjacent the title, this will also be returned in the response payload, even for draft status posts.
