### ISSUE TITLE
Gutenboarding: Better system for loading fonts

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#40613]
Fonts are loaded in Gutenboarding in a couple places:

https://github.com/Automattic/wp-calypso/blob/78adaf01ec3f4e7617047f34aefe070431b04da4/client/landing/gutenboarding/gutenboard.tsx#L40-L63

https://github.com/Automattic/wp-calypso/blob/78adaf01ec3f4e7617047f34aefe070431b04da4/client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx#L94-L128

Improve this system.

**Comment by simison** [comment]
The partial text font loader shouldn't load partial font for fonts listed as system fonts, basically "Roboto".  Otherwise it'll override those system fonts and text show up funky:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/87168/78356875-1a5e2b00-75b9-11ea-88b0-e6b863a9de39.png">


Convo p1585846493390000-slack-gutenboarding

**Comment by simison** [comment]
Since the font isn't loaded to memory, there's a short time when changing fonts shows system font until fonts gets loaded and show correctly.

In practise it shows as "flicker" when switching between fonts, until all fonts are in browser memory: https://cloudup.com/cC4QqrNKbGh

The slower the connection, more flicker.

We should either:
- load all fonts up-front :-( heavy on the browser, esp. on slow connections
- start loading earlier, which can still flicker sometimes but much less. maybe when button fonts are loaded, we can start loading the rest?
- load on button hover so that it gets head-start?

**Comment by sirreal** [comment]
We can inject all the styles early, that's a good idea.

Font resources aren't requested until they're needed, that's where the flicker comes from. I'm not sure if we can prefetch or trick the browser into requesting them on hover, also a good idea.

There's also the font-display property we can play with:

https://www.w3.org/TR/css-fonts-4/#font-display-desc

Currently we're using `swap` I believe.

---

I'd note that the two issues are independent (flicker/partial text rendered as fallthrough with "Roboto"). The flicker is in the iframe and the roboto is in the top window. Different assets in each context.

**Comment by worldomonation** [comment]
Is this still relevant, given that we're deprecating Gutenboading?

**Comment by simison** [comment]
Not relevant
