### ISSUE TITLE
Coutoire Home Template: Page editor overlaps to the left

### ISSUE THREAD

**Issue by geekinthegirl** [Automattic/wp-calypso#40719]
## Steps to replicate

When trying to edit/add blocks to a page using the Coutoire theme, the editor loads content overlapped to the left, making it difficult to edit:

<img width="1680" alt="Screenshot 2020-04-01 at 16 43 27" src="https://user-images.githubusercontent.com/22247240/78167138-ddbdf280-7445-11ea-9e73-e73231b597a5.png">

This was replicated by adding Coutoire to a test site, and the same occurs with demo content:

<img width="340" alt="Screenshot 2020-04-01 at 18 21 11" src="https://user-images.githubusercontent.com/22247240/78167158-e8788780-7445-11ea-9ed4-711ed4e0f6bb.png">

This behaviour was the same in both Chrome and Firefox.

## Expected

Calypso editor should allow users to edit content for the Coutoire theme within the screen, and not overlap or cut off.

Also to note: when published, the content looks fine. This issue only occurs in the editor.

* User report: #3880801-hc

**Comment by tijosh** [comment]
Looks similar to /Automattic/themes/issues/1816

**Comment by kjellr** [comment]
I think this issue is specific to Coutoire, and has to do with the fact that the Media & Text block on the left there is a full-width block inside of a column block. Changing it to a standard width eliminates the issue, and keeps the appearance the same on the front end: 

**Before**

<img width="1080" alt="Screen Shot 2020-04-06 at 1 31 07 PM" src="https://user-images.githubusercontent.com/1202812/78587420-eaa66180-780a-11ea-9952-27127f3103dc.png">

**After**

<img width="1079" alt="Screen Shot 2020-04-06 at 1 31 19 PM" src="https://user-images.githubusercontent.com/1202812/78587429-ec702500-780a-11ea-8f50-fb3e1d20691e.png">

---

This may be something that can be fixed in the theme, but a quicker fix would be to just adjust that template to not use a full-width block there.

**Comment by simison** [comment]
>  a quicker fix for now would be to just adjust that template to not use a full-width block there

@ianstewart

**Comment by ianstewart** [comment]
This _should_ be corrected now. I updated this homepage annotation just yesterday but … @obenland it looks like theme switching is still using the old annotation for the homepage layout? Anything we can do to update that?

**Comment by obenland** [comment]
Homepage templates are cached for 24 hours. So either regenerate or wait

**Comment by kjellr** [comment]
Also just to follow up: https://github.com/Automattic/themes/pull/1902 should prevent this from happening in the future.

**Comment by obenland** [comment]
This has been fixed.
