### ISSUE TITLE
Jetpack Connect: Thank you modal after purchasing Search refers to the Free plan.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#40753]
#### Steps to reproduce

1. Starting at URL: jetpack.com/upgrade/search (logged in)
2. Pass the JPC flow with a site with no Jetpack Search 
3. Verify the Thank You modal pointing to a Free plan (Search product should be added correctly)

#### What I expected
See a Thank You note corresponding to JPS
#### What happened instead
We see the Free plan modal

**Comment by gibrown** [comment]
had to get reverted...

**Comment by gibrown** [comment]
so what i was seeing is this flow:
- jetpack.com/upgrade/search
- https://wordpress.com/jetpack/connect/jetpack_search?cta_id=landing-page-search-primary-cta&cta_from=upgrade_search
- https://wordpress.com/jetpack/connect/plans/gibrown.wpsandbox.me::demo (shows all plans rather than just going directly to checkout of search plan)

that last step is what was not working for me on staging. all the plan buttons seemed to be disabled, not sure why.

**Comment by gibrown** [comment]
This has been fixed somewhere along the way.
