### ISSUE TITLE
Help should be part of the /me navigation

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#40869]
I knew that /help lived within /me, but I navigated directly to /me and couldn't find how to get there. I then went to a customer home page and clicked the help dot in the corner, then clicked 'more help' to land at /help. I noticed that there is no sidebar item in the /me menu for Help, creating a pretty counter-intuitive navigation experience.

![image](https://user-images.githubusercontent.com/437258/78714683-485dab00-78ea-11ea-94b1-9c7b22982a6e.png)

I expected to see a help link on the left highlighted.

cc @fditrapani who has done some mockups recently that play with an improved organization of the /me sidbar links—maybe we can incorporate that new layout while adding a /help link?

Edit by @gwwar: As a first iteration let's put this new item under "Account".

**Comment by fditrapani** [comment]
Good idea Rick! I can see the link fitting well i the new update I was working on. I unfortunately didn't get to finish my explorations due to my new COVID life but would be happy to continue working on it or pass it along should we consider to implement it. This is where I left off: 

![image](https://user-images.githubusercontent.com/6981253/78744622-0f482980-7930-11ea-9aa5-75bb9bf6fcc5.png)

**Comment by rickybanister** [comment]
I knew if I sent up the bat signal you'd drop an image in here, thank you!

**Comment by fditrapani** [comment]
ahah. While I had it open, I quickly mocked up where I thought it should be heading after a couple conversations:

![image](https://user-images.githubusercontent.com/6981253/78839738-0d7d7500-79c7-11ea-8b39-1a3b10c6f792.png)

In this view:
- the account settings can be merged into the profile section (either as another tab or as sections on the profile page). 
- Blocked sites would fit under security and privacy somewhere. 
- Billing history becomes purchases.
- Sites is an updated view of our current Purchases screen with all your sites listed out. 
- Security and Privacy are merged. 
- And I added "Help" under profile

**Comment by davemart-in** [comment]
This is the first time that I'm seeing this issue. From my perspective, having help in /me doesn't really make a lot of sense. It seems like most apps have help as its own link in the top right corner of the screen. I'm not sure I would ever think to look in my profile for help. Do you think there is some more exploration we could do on this @rickybanister?

**Comment by fditrapani** [comment]
It's been a while since I've seen this and the changes we're making with payments management don't align with the screenshots I shared. I'm with you on this Dave that having a link in `/me` isn't very intuitive. I think keeping the help at the site level makes most sense but with our floating help icon, I'm not 100% if it should be duplicated in the nav (mostly because our nav is so full already!).

**Comment by jordesign** [comment]
Closing this as Help will be a top-level admin item as part of the Help Center.
