### ISSUE TITLE
Gutenframe: Canceling inline image addition re-opens modal

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#40934]
### Steps to reproduce

1. In the current block editor on wpcom, select text in a paragraph, and then choose "inline image" from the block dropdown menu:
<img width="670" alt="Screen Shot 2020-04-08 at 1 39 25 PM" src="https://user-images.githubusercontent.com/6265975/78831383-65ec4c80-799e-11ea-9181-f6b9f8aa82fe.png">

2. Then, "cancel" out of the modal by clicking outside of it.
3. After a second or two, click in the block editor somewhere
4. Notice the modal appear again. Now, whenever you try to "cancel", it immediately re-opens the menu.

![2020-04-08 13 08 35](https://user-images.githubusercontent.com/6265975/78831499-96cc8180-799e-11ea-89ff-994f36b53bc3.gif)

Note that when you "insert an image" instead of cancelling, the re-opening of the modal stops.

**Comment by yansern** [comment]
This is happening because when the replacement modal is closed, it does not trigger the `closeModal()` function in https://github.com/WordPress/gutenberg/blob/master/packages/format-library/src/image/index.js#L95-L97.

Triggering this function would require opening another message channel and to send a message back from parent calypso back to the iframe editor notifying that the modal is being closed.

**Comment by p-jackson** [comment]
The modal loop only happens on FF. Still an issue either way!

**Comment by yansern** [comment]
> The modal loop only happens on FF. Still an issue either way!

FF is no longer an issue: https://github.com/Automattic/wp-calypso/pull/43113#pullrequestreview-427786865
