### ISSUE TITLE
Gutenboarding: use `getSuggestionsVendor()` for domains

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40968]
Convo from https://github.com/Automattic/wp-calypso/issues/40164#issuecomment-609785023

> I don't see getSuggestionsVendor in packages/data-stores/src/domain-suggestions currently used. Is that an issue?

> Unfortunately, yes, it is a possible issue - in the past, we've had to switch providers for many reasons (a/b testing being the usual one, but also during outages or other problems with providers). In order to provide consistent user experience, we need to ensure we use the same provider across the board. It will probably seriously screw the results of an A/B test as well ;) We don't have short-term plans of testing any new providers, but nevertheless we should make sure the same provider is used consistently.

API/data layer:

https://github.com/Automattic/wp-calypso/blob/58442f38b9682f90c2822458b213e552155a42d3/packages/data-stores/src/domain-suggestions/selectors.ts#L75-L86

API used in Gutenboarding:

https://github.com/Automattic/wp-calypso/blob/53152de21e71deb004831778243cc855b1e9c372/client/landing/gutenboarding/hooks/use-domain-suggestions.ts#L29-L34

The utility we need to call:

https://github.com/Automattic/wp-calypso/blob/e1face4840c4d7710a66d76d90bf1ff810dede8b/client/lib/domains/suggestions/index.js#L5-L10

In our case, we likely need to add this to `gutenboarding/hooks/use-domain-suggestions.ts` @Automattic/luna ?

@klimeryk hi! :-) We should use`isSignup: true` for something like Gutenboarding, correct?

**Comment by klimeryk** [comment]
> @klimeryk hi! :-) We should useisSignup: true for something like Gutenboarding, correct?

Yup, that's my understanding - Gutenboarding cannot be "re-run" for exisiting sites, right? It's basically onboarding/signup only?

**Comment by simison** [comment]
@klimeryk the idea is to keep showing the same drop-down functionality to users after initial onboarding if they choose not to get domain in onboarding phase. That way we can show same feature for all existing free domain users going forward.

So maybe true/false depending on state we're at? :-) It's true that now the component is visible only during first steps of onboarding/sign-up, so for now we can keep it `true`.

**Comment by ockham** [comment]
Some guiding principles:

- Let's not directly import a file from `client/`. We've managed to steer away from the "Calypso soup" so far (and for good reason), let's not start now.
- That said, we might have to duplicate `getSuggestionsVendor()`; maybe inside a new domain util package in `packages/`.
- If we need to allow or domain suggestions store vendor agnostic, and pass in the vendor as an argument, we should make the suggestions store _entirely_ vendor agnostic (i.e. it shouldn't hold any list of potential vendors, or a default vendor). It also shouldn't be coupled to a helper like `getSuggestionsVendor`, but just accept a `vendor` argument. (Separation of concerns -- the data store should really just be in charge of fetching domain suggestions, but it should be ignorant of what vendors exist.) And of course, there should never be any A/B tests implemented inside of the data store, should we decide to A/B test vendors again.
- My preferred way would be to keep all the vendor business in the backend. As I said [elsewhere](https://github.com/Automattic/wp-calypso/issues/40164#issuecomment-611728353): 

> It makes sense for a domain suggestions endpoint to expect arguments like a query, vertical, and maybe some flags about which TLDs (and/or subdomains) to include or exclude, but the vendor should IMO be considered an implementation detail. In other words, I can expect the user calling the endpoint to know what information to provide about the desired domain in order to provide meaningful search results, as all that's domain-specific. But the results provider/vendor? That should be treated as an implementation detail IMO -- how is a user calling the endpoint even supposed to know which vendors are available?

**Comment by sirreal** [comment]
I tend to agree with the points @ockham raises here. Specifically, I don't understand why the client decides, or is even _aware of_ the vendor.

**Comment by klimeryk** [comment]
I really don't understand your fixation on `vendor` 😅 

My suggestion seems the easiest and most consistent method right now. I assumed you already share some code with Calypso - and this is a very small function that should be easy to isolate (no dependencies) and include here without pulling in anything unrelated.

Seems there are plans to re-test some of our suggestion partners and their different configurations. It seemed like preserving the current behaviour would be much easier than trying to refactor it - which I don't think anyone is eager to do :)

> I tend to agree with the points @ockham raises here. Specifically, I don't understand why the client decides, or is even aware of the vendor.

And my answer is still the same: [if you can pass the A/B test information from backend to frontend, we can do that](https://github.com/Automattic/wp-calypso/issues/40164#issuecomment-611746926).
Longer version: we heavily track how suggestions are performing, including using TrainTracks (check FieldGuide for more info) to pass along the railcarId to precisely track the suggestion and how it converts (in relation to the vendor as well). This is a strictly front-end thing, it seems. If we can do this in the same way while somehow informing TrainTracks on the frontend which vendor was used in a consistent way, cool. But that seems like an exercise not worth the effort. You could return the vendor in the suggestions' endpoint response, but then you have to take into account error paths (some errors are generated by vendors, some could be generic, how do you accurately report which are which?) and so on.

Could we just share 5 lines of code? If you're not using already code from Calypso, I'd suggest start doing so anyway, otherwise you'll run into issues with data validation and sanitization. See https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/index.js#L144 and related functions there.

**Comment by daledupreez** [comment]
This may well be piggybacking, but the signup flow is one of the areas where there is often a lot of testing and modification, so keeping all of the A/B testing management in the client code (aka Calypso) has meant that we have much less coordination between the front and back end to support various experiments. We _could_ move _pieces_ of that to the back end, but that would result in a lot of ongoing complexity and coordination to ensure we can track the events for those experiments.

That said, I do agree with @ockham's notes RE separation of concerns. I think it would be cleaner if the suggestions store could be vendor-agnostic, but that mostly shifts the code location where the vendor-awareness needs to be located.

I also think it's not the end of the world if we duplicate or approximate the `getSuggestionsVendor()` logic to some non-Calypso location, as I think it would be _extremely_ unlikely for us to run A/B tests across the standard Calypso UIs and Gutenboarding. The goal of that function was to centralize the logic for vendor selection to ensure we were consistent in support of various experiments and A/B tests.

**Comment by sirreal** [comment]
I've prepared #41177 to resolve this.
