### ISSUE TITLE
Plugins: Upgrade nudge missing to install plugins

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-calypso#41046]
#### Steps to reproduce

1. Head to https://wordpress.com/plugins/ on a site with a paid plan lower than Business (not free plan)
2. Select a plugin to install
3. Install is greyed out and there is no information

#### What I expected
I expected an upgrade nudge

#### What happened instead
No information is provided on what I need to do

#### Browser / OS version
Chrome 80
Mac OS 10.14.6

#### Screenshot / Video

Video: https://d.pr/v/Yu7nwy

#### Context / Source

#dogfooding, #manual-testing

H/T: @mrfoxtalbot

**Comment by arunsathiya** [comment]
I had a look and from what I see, the notice appears as expected.

It appears on these paths (WooCommerce is an example here):

- https://wordpress.com/plugins/woocommerce/free.wpcom.arun.be
- https://wordpress.com/plugins/free.wpcom.arun.be

<img width="1427" alt="Screenshot 2020-04-14 at 00 16 14" src="https://user-images.githubusercontent.com/18581859/79149880-7577f500-7de5-11ea-90c6-18db39982cc7.png">
<img width="868" alt="Screenshot 2020-04-14 at 00 16 00" src="https://user-images.githubusercontent.com/18581859/79149890-7a3ca900-7de5-11ea-9bd4-e76271b0b804.png">



It does not appear on https://wordpress.com/plugins/ itself. 

<img width="1680" alt="Screenshot 2020-04-14 at 00 15 12" src="https://user-images.githubusercontent.com/18581859/79149867-6e50e700-7de5-11ea-94d2-9597c19b9582.png">


I don't think we used to show a notice here, because on this page, there is no site selected. It's only on clicking a plugin name, or on visiting the site's plugins list, we know that the site's not eligible for plugins.

**Comment by damiannep** [comment]
@arunsathiya I edited the report. The plan needs to be a paid plan. The upgrade nudge shows for the free plan but not for Premium or Personal.

**Comment by Aurorum** [comment]
Hi, I'd like to open a PR for this but I don't have a site with an adequate plan to do so. Would it please be possible to invite me to a site with a Personal or Premium plan? :)

**Comment by damiannep** [comment]
I'd be happy to @Aurorum but I'm not sure of you WordPress.com username.

**Comment by Aurorum** [comment]
Ah oops, thanks @damiannep! It's `torres126`.

**Comment by damiannep** [comment]
Invite sent :)

**Comment by Aurorum** [comment]
Thank you! PR in #41076 to make it appear for Personal and Premium sites again. :)
