### ISSUE TITLE
Customer Home: Show editor deprecation notice

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#41085]
Related to #41084

> As a user who uses the WordPress.com editor (aka Calypso editor) for a site,
> I need to know that the WordPress.com editor is being deprecated,
> So that I can prepare for the change.

## Requirements

1. Users who currently edit a site with the WordPress.com editor see a dismissible notice at the top of Customer Home indicating that the editor is being deprecated
1. Notice is translated before it's deployed to production
1. Notice is displayed starting ~2 weeks before the WordPress.com editor is deprecated

## Notes

Site wide notices project, (possibly relevant to how we display the notice): pbAPfg-bT-p2

**Comment by glendaviesnz** [comment]
@Automattic/serenity given your recent work on the Home screen, do you have any suggestions about the best way to add a dismissible notice to a users site home screen to notify them about the upcoming editor deprecation? It looks like the Site wide notice project is not close to being available yet. 

I have had a quick look, and it seems like we could reasonably easily add another notice type into `client/my-sites/customer-home/cards/notices` to handle this, as it is only going to be temporary, and this gives us a site dismissible notice at top of home screen with a minimal amount of work (maybe instead of a new type we could call it 'celebrate-editor-deprecation' 😄). Before I explore this further can you see any gotchas?

**Comment by mmtr** [comment]
Hey @glendaviesnz! The first thing to have in mind is that My Home is now powered by an API endpoint. You can read more about that in PCYsg-pPq-p2. 

So, in order to display a new notice in My Home, you'll need a few things:
- [Server-side] Decide which views will get the notice (unlaunched sites, sites with the onboarding checklist uncompleted, established sites, etc).
- [Server-side] Add the notice identifier to the selected view(s).
- [Server-side] Add logic to filter out the notice visibility if needed (i.e. you might want to hide the notice for users currently using Gutenberg).
- [Client-side] Add notice component to `client/my-sites/customer-home/cards/notices`.
- [Client-side] Connect server-side notice identifier with client-site component in `client/my-sites/customer-home/locations/notices`.

**Comment by gwwar** [comment]
cc @danhauk @lcollette for guidance on where to put this type of notice.

**Comment by glendaviesnz** [comment]
> The first thing to have in mind is that My Home is now powered by an API endpoint.

Thanks, @mmtr, I am glad I asked, I wouldn't have figured all that out by myself 😄

**Comment by jancavan** [comment]
> @Automattic/serenity given your recent work on the Home screen, do you have any suggestions about the best way to add a dismissible notice to a users site home screen to notify them about the upcoming editor deprecation

Designs for this can be found here: https://github.com/Automattic/Dotcom-roadmap/issues/124#issuecomment-618708518

Please note that the primary button in the Site Setup list will have to change to secondary when this notice is present. I outlined it in the comment above ^
