### ISSUE TITLE
Editor: Toggle between Block editor and Classic editor

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#41087]
> As a user who previously used the WordPress.com editor (aka Calypso editor) for a site,
> I need to quickly switch between the Block editor and the Classic editor for a post or page,
> So that I have easy access to both interfaces while I adjust to the change

## Requirements

1. After [the WordPress.com editor is deprecated](https://github.com/Automattic/wp-calypso/issues/41086), users who had not previously made an explicit editor choice and were still editing a site with the WordPress.com classic editor (this will be users prior to Dec 2018) see a dismissible notice in both the Block editor and the Classic editor that let's them easily switch back and forth between the editors for the current page/post they are editing.
1. For this group the notice shows by default in the block editor for ~2 weeks after the WordPress.com classic editor is deprecated, and after that 2 weeks will only show if a query param is present indicating a users has just redirected from the classic editor. The notice will display permanently in the wpadmin classic editor.
1. Last used editor becomes the site wide setting for that user--when the user comes back to edit a post/page on the site, they should be directed to the editor they last used

## Notes

1. Information about the Gutenberg Opt-In API: PCYsg-hNB-p2
1. In the Block editor, If the notice points to the ["Switch to Classic Editor" link](https://github.com/Automattic/wp-calypso/issues/41108) that's already there, then users will learn where that is and how to access it, when needed.
1. If a user makes an explicit editor choice after deprecation, ie. switches to classic, we are not concerned that they previously fell into the above mentioned group. From that point they will be treated the same as a user that made an explicit editor choice prior to deprecation in terms of which notices are displayed.

**Comment by dwolfe** [comment]
Adding design assets...

## Gutenberg sidebar prompt

![Gutenberg sidebar prompt](https://user-images.githubusercontent.com/1348738/80751935-8ca22c80-8adf-11ea-9c6c-a39f002fcd8e.png)

Note: This should be a dismissible panel locked to the bottom of the sidebar, elevated above the rest of the sidebar content so that the accordions scroll beneath it (we'll need to add padding to the bottom of the sidebar, equivalent to the height of the prompt, so that all settings can still be accessed). In situ comp:

![In Situ Gutenberg sidebar prompt](https://user-images.githubusercontent.com/1348738/80752113-d4c14f00-8adf-11ea-905c-02bb2d65c8e2.png)

## Classic editor prompt

![Classic Editor sidebar prompt](https://user-images.githubusercontent.com/1348738/80752192-f0c4f080-8adf-11ea-8e33-e365c028654f.png)

Note: This is a dismissible panel at the bottom of the right column after the last settings group, in the normal document flow. In situ comp:

![In Situ Classic Editor prompt](https://user-images.githubusercontent.com/1348738/80752268-1225dc80-8ae0-11ea-9b5c-6ea03b74e874.png)

## Post-sunset Classic Editor prompt

I don't know if this is the right issue for this, but just in case: after the sunset period, there needs to be a way for the user to switch to the block editor. This should be the top (default) tab in the help panel at the top of the editor.

![Classic Editor Help Panel prompt](https://user-images.githubusercontent.com/1348738/80752578-8bbdca80-8ae0-11ea-9b30-09d3f790fa69.png)

In situ comp:

![In Situ Classic Editor Help Panel prompt](https://user-images.githubusercontent.com/1348738/80752590-94160580-8ae0-11ea-8230-79de46f5f08e.png)

**Comment by glendaviesnz** [comment]
@dwolfe there is a slight issue with the block editor notice placement, and with having the other options scroll behind it, and that is it potentially hides a lot of the options from new users if on  smaller browser window, and doesn't necessarily look like a scrollable are ... and also hides toggled options behind it:

![notice](https://user-images.githubusercontent.com/3629020/82397457-9ac2e780-9aa4-11ea-8194-c6175435536a.gif)

In providing a quick link back to classic we are potentially introducing a usability issue to block editor that may just encourage them to switch back - what do you think?

**Comment by glendaviesnz** [comment]
@dwolfe I would like to suggest that we instead inject an additional settings panel. This is a standard gutenberg approach to adding extra options to the document settings panel, it is just as visible to users, but doesn't introduce any new/strange usability issues:

![alt-classic](https://user-images.githubusercontent.com/3629020/82401701-a1eef300-9aae-11ea-9ffa-c7563225f5fb.gif)

**Comment by dwolfe** [comment]
Thanks for pointing this out, @glendaviesnz. Would something like this be possible?

![Gutenberg-sidebar-switch-notice](https://user-images.githubusercontent.com/1348738/82505314-39097a00-9ab2-11ea-84ce-2167ae252050.png)

This notice is only going to exist for two weeks, but I was hoping that users would be able to dismiss it. If there's an issue with this execution that I'm not aware of, let me know, but otherwise I think we can use our standard notice and call it done.

**Comment by creativecoder** [comment]
@dwolfe @glendaviesnz 

Based on the discussion in pb5gDS-yZ-p2#comment-1457, the trigger for this notice in the block editor will be coming directly from the Classic Editor in wp-admin (by clicking on the notice we're adding there), or one time if it's the user's first time seeing the block editor.

Given that it's going to be such a temporary notice, what about using a dismissable "tooltip" that's right up next to the three dots menu? Would would let users know how to get back to the classic editor in wp-admin by clicking into that menu, and it would go away after they decide to close it.

**Comment by glendaviesnz** [comment]
@dwolfe @creativecoder I got the notice working in https://github.com/Automattic/wp-calypso/pull/42390#issue-420492144. The only issues I have are:

- It isn't possible to wrap the text under the close button as in your design without resorting to fixed positioning in css or creating a custom notice component for this - not sure if it is critical enough to warrant this extra work  - you can see how it currently looks in screenshot on PR
- I am having trouble getting the onRemove callback to fire when the notice is dismissed in order to track somehow that user has previously dismissed this, so currently the notice comes back on reload - will keep working on this.

**Comment by glendaviesnz** [comment]
@dwolfe Am I correct in assuming that the reason you want to explain where the existing switch to classic is to teach the user for when this notice disappears? Just asking because we could just put a "switch to classic" link in the notice, but that defeats the purpose if the main aim is to alert the user to where the menu option is.

**Comment by glendaviesnz** [comment]
@dwolfe I managed to get the notice placed in the sidebar and dismissible. The only issue is that with placing it under the document status, it shifts position to the top of the panel if the user clicks on the block panel:

![broken-placement](https://user-images.githubusercontent.com/3629020/82854043-698e5f80-9f5b-11ea-99b1-de138874edd7.gif)

Unfortunately because we are injecting this from outside gutenberg we can't easily hook into when the tabs are changed, so the notice has to exist in both tabs as the both share the same content panel. A way to fix the placement issue is to always insert it at the top of the panel:

![notice2](https://user-images.githubusercontent.com/3629020/82854144-abb7a100-9f5b-11ea-9b42-0258b4de3789.gif)

Are you happy with that approach? Apologies that we can't get this exactly as you have designed, it is just tricky than would normally be the case as we have to push this notice in from outside of gutenberg.

**Comment by aaronrobertshaw** [comment]
@dwolfe I ran into a couple of limitations with the metabox API needed to achieve placement of this prompt at the bottom of the right-hand column. It forces the wrapping of the metabox content with hard-coded HTML, including the collapsible header. For accessibility purposes, I'd like to suggest we leave the header visible and remove the dismiss button from within the prompt itself.

My understanding is that this prompt will be short lived. Not having the prompt be dismissible may help make the most out of driving adoption of the block editor.  

The end result can be seen in the screenshot below:

<img width="1194" alt="use-block-editor-prompt" src="https://user-images.githubusercontent.com/60436221/83366781-86f87900-a3f4-11ea-830e-cf92e8b5f387.png">

**Comment by glendaviesnz** [comment]
We are exploring a different approach to editor deprecation so closing this issue for now.
