### ISSUE TITLE
Editor: Email users regarding editor deprecation

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#41086]
Follow up to #41084

> As a user who uses the WordPress.com editor (aka Calypso editor) for a site,
> I need to be notified when the WordPress.com editor is deprecated and no longer available to use,
> So that I can know how to continue editing my site content.

## Requirements

1. Roll out deprecation to users gradually, starting with 5% of total users still using the Calypso editor
1. Add each group of users to the deprecation group and send deprecation email

## Notes

1. We'll roll this out gradually, starting with 5% of affected users
1. Additional information on sending the emails through WordPress.com p428ex-AU-p2 and PCYsg-beU-p2 (specifically the "Mass Email (from WP.com only)" section)
1. Preparation work in D43115-code, D42798-code, and D45864-code
1. Instructions for sending emails: pb5gDS-Hk-p2

**Comment by scruffian** [comment]
Just noting that we need to make sure we don't break PressThis...

**Comment by scruffian** [comment]
I think the requirements need updating, but I spent some time looking into this. For users without an assigned editor this is simple. We can just do something like: D43850-code. We'll need to make sure that we also filter the emails by the same users.

However, I'm not sure how we will handle the case of users who have the classic editor already assigned. In this case we still want to direct these people to Gutenberg, but then we want to give them the option to switch. Right now switching is based on the editors user attribute, but since we'll be ignoring that and sending everyone to Gutenberg initially, we'll need a new way to determine who has opted out - maybe a new value in the editors user attribute?

It's possible I've misunderstood the requirements, but it would be good to make sure they were up to date above.

**Comment by creativecoder** [comment]
Looks like it was me misunderstanding the requirements. I've updated the description

> 2. Users with the editor preference for the block editor continue to be directed there
> 3. Users with the editor preference for the classic editor have their preference updated to the block editor before the email is sent

By changing the editor preference one time, users will go to the block editor after the deprecation, but they can switch their preference back to classic after that, if they prefer.

**Comment by creativecoder** [comment]
Note, I've updated the requirements based on what's already been completed (email, translations, etc). This issue now covers only sending the emails in batches, not any of the preparation work.

**Comment by scruffian** [comment]
Made a start here: https://code.a8c.com/D45864

**Comment by creativecoder** [comment]
D45864-code is now working and ready for review.

**Comment by scruffian** [comment]
I also added D45991-code.

**Comment by creativecoder** [comment]
Note, added @scruffian 's instructions for sending emails to the issue description: pb5gDS-Hk-p2

**Comment by creativecoder** [comment]
All emails have now been sent.
