### ISSUE TITLE
Editor: Deprecation notice for WordPress.com editor

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#41084]
> As a user who uses the WordPress.com editor (aka Calypso editor) for a site,
> I need to know that the WordPress.com editor is being deprecated,
> So that I can know how to edit my site content after the deprecation.

## Requirements

1. Users who currently edit a site with the WordPress.com editor see a notice that gives a notification that they will be defaulted to the Block Editor (in Calypso) when the WordPress.com editor is deprecated.
2. Clicking “Try it out” will simply take you to the Gutenberg editor to take it for a spin. No default editor preferences will change.
3. Clicking “Not now” will simply dismiss the modal.
4. Notice is displayed starting ~2 weeks before the WordPress.com editor is deprecated
5. Notice is translated before it's deployed to production

## Notes

[Example notice from core](https://a.cl.ly/d5u0dnDD)

[Example placement for the notice](https://a.cl.ly/DOu85GL0)

**Comment by scruffian** [comment]
### Updated Requirements based on [this comment](pb5gDS-uw-p2/#comment-1269)

1. Users who currently edit a site with the WordPress.com editor see a notice that gives a notification that they will be defaulted to the Block Editor (in Calypso) when the WordPress.com editor is deprecated.
2. Clicking “Try it out” will simply take you to the Gutenberg editor to take it for a spin. No default editor preferences will change.
3. Clicking “Not now” will simply dismiss the modal.
4. Notice is displayed starting ~2 weeks before the WordPress.com editor is deprecated
5. Notice is translated before it's deployed to production

**Comment by dwolfe** [comment]
Adding design assets - this takes into @glendaviesnz's [point that we can't really do "Try it out"](https://github.com/Automattic/wp-calypso/pull/41570#issuecomment-621523371):

![Pre-sunset Calypso Editor sidebar prompt (1)](https://user-images.githubusercontent.com/1348738/80762967-60dc7200-8af2-11ea-84a2-c7dc3cb9581e.png)

Note: This is a dismissible panel locked to the bottom of the sidebar and elevated over the rest of the sidebar content, so that it scrolls beneath the notice. We'll need to add padding to the bottom of the sidebar equal to the height of the panel so that all sidebar content can be accessed. In situ prompt:

![In Situ Pre-sunset Calypso Editor sidebar prompt](https://user-images.githubusercontent.com/1348738/80763104-a436e080-8af2-11ea-9995-18b3c04aefb8.png)
