### ISSUE TITLE
Gutenboarding: Vertical suggestions don't show a single exact match

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#41121]
#### Steps to reproduce

1. Starting at URL: [wpcalypso.wordpress.com/new](http://wpcalypso.wordpress.com/new)
2. After typing _baker_ you see this 
![image](https://user-images.githubusercontent.com/14192054/79306000-14dbdb80-7efd-11ea-8ab7-b8f05cad25f3.png)
3. When pressing the final letter _y_ the suggestions dropdown disappears.

#### Context / Source
We decided to hide the Suggestions dropdown when there is a single match displayed and it is identical with the user input (non-case sensitive match). This was a bit annoying when the user selected a suggestion and then came back to edit but I see it’s even more annoying to see your option gone from the dropdown as the first experience.

Initially mentioned in p58i-8UC-p2#comment-46014
Reverts: https://github.com/Automattic/wp-calypso/pull/40110

**Comment by razvanpapadopol** [comment]
@dubielzyk should we show the single exact suggestion all the time or just after the user modified the input value?

**Comment by dubielzyk** [comment]
Good shout. It feels a bit odd that it disappears when the string matches exactly. If we match a suggestion we should show it. The suggestions list shouldn't show _only_ when there's no suggestion. Let's optimize for the first run, rather than the coming back scenario. 

We could also hide the suggestion list when they come back until they focus on the input field.
