### ISSUE TITLE
Documentation: Ensure node_modules is installed on the first run

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#41241]
The instructions to get up and running say to clone the repository, and from the project directory, run `yarn start`, but on a fresh installation, this results in an error about the command `check-npm-client` not being found.

#### Steps to reproduce

1. Follow the instructions to create a fresh install of of the project
2. Ensure that `check-npm-client` is not installed as a global module
3. Run `yarn start`

#### What I expected

The project to build and run

#### What happened instead

A shell error saying that `check-npm-client` was not found.

#### Solutions

We could remove the check from certain tasks, or add some script that checks for the presence of `node_modules`. I was going to do this using bash but realised that wouldn't be cross-platform.

**Comment by scinos** [comment]
In order to simplify the setup, we decided that manually installing dependencies when you clone a NPM project is a widely adopted convention, and trying to add any kind of logic to automatically install dependencies when required is going to be complex, error prone (it is not trivial to detect if the existing `node_modules` is enough to start Calypso) and may introduce startup delays.

The `Getting started` section in `README.md` already states:
> 4. Execute `yarn` and then `yarn start` from the root directory of the repository.

**Comment by pablinos** [comment]
Ah yes, I see @shaunandrews updated it. That's a much simpler solution! Thanks all.
