### ISSUE TITLE
Gutenboarding: Private site messaging

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41302]
Right now we don't communicate at all that the site is in a 'coming soon' mode and what that it means, or how to change it when the user first lands in the editor.

We need to find a way to deliver this information: They need to understand their site is already created, but it won't be visible to anyone until they launch it.

**Comment by ramonjd** [comment]
Welcome modal?

I know we were debating whether to send the user to their Customer Home as a fallback. That would be another spot for this communication. 🤷

**Comment by dubielzyk** [comment]
FYI @joanrho @olaolusoga

**Comment by joanrho** [comment]
I'd hesitate to rely on a welcome modal or anything that can be quickly dismissable to communicate that. IIRC, we used to have some sort of persistent/sticky bottom or top bar in WPcom that communicated this in the past. Do you recall that @johnHackworth @rickybanister?

**Comment by olaolusoga** [comment]
This is part of pre-launch, and launch flow. Reassigned to @joanrho

**Comment by joanrho** [comment]
The sidebar is collapsible, so the prompt could just be hidden and forgotten. The topbar solution worked well, even if "ugly", because it persisted and was quite distracting to entice users to act on it. If anything, we should keep it stick across the bottom bar until users have launched.

**Comment by rickybanister** [comment]
I don't think you understand what I meant by ugly. 

Here is the ticket I opened:

https://github.com/Automattic/wp-calypso/issues/40618

This banner is still in production, but it now only displays when you visit the front-end of your site in coming soon mode. We only hid it when inside the preview to avoid the double bar, double pink button situation.

**Comment by joanrho** [comment]
@rickybanister Thanks for sharing more context. That double bar/double pink button situation is definitely more than we need. I'll explore some simpler directions in either the sidebar or bottom of the page.

**Comment by joanrho** [comment]
After doing a few explorations, the sidebar direction proved to surface more issues than clear solutions, like: Where will it live amidst the other topbar icons and side panels? When other panels, like Block Patterns, are active what will happen to this element? Will it collapse or get dismissed? If anything, placing it in the topbar alongside the Launch button up would make the most sense, but we're already accumulating quite a lot of things to interact with and process up there. 

Instead, I explored what a page-bottom placement could look like:

**Editor:**
<img width="1201" alt="Screen Shot 2020-04-22 at 5 08 21 PM" src="https://user-images.githubusercontent.com/204742/80042403-1e94ae80-84bc-11ea-8703-db6c16804768.png">

**Site Preview:**
<img width="1159" alt="Screen Shot 2020-04-22 at 5 31 55 PM" src="https://user-images.githubusercontent.com/204742/80043569-54876200-84bf-11ea-9d84-339adcc59e34.png">

I think this simple, clean sticky banner on the bottom of the Editor page below the breadcrumb communicates well. For the Site Preview, we could even clip it to fit the bounds of the previewed page to emphasize that the site being viewed isn't launched yet.

Since Customer Home already presents users with a Site Setup list item and Customer Home Card addressing Site Launch (and private until launch), we wouldn't need to display this banner in Calypso.

<img width="1416" alt="Screen Shot 2020-04-22 at 5 26 17 PM" src="https://user-images.githubusercontent.com/204742/80043251-6a485780-84be-11ea-943f-c11e8a0579d5.png">

What do you both think @johnHackworth @rickybanister ?

**Comment by rickybanister** [comment]
I'm a bit concerned about adding more elements to the editor, especially ephemeral ones, and non-dismissable ones. 

@johnHackworth already suggested a wp notice in the editor to point out the preview link in pbAok1-Aa :

![image](https://user-images.githubusercontent.com/437258/80045806-8fe15b00-84d6-11ea-9f15-96e0b1c177f3.png)

And your proposal for the help dot or sidebar checklist would contribute another (also ephemeral ) element. 

I wonder how we can better leverage the elements we already have. A couple of examples—if the launch button is going to be persistent and we've heard people are scared to click it, could a tooltip or hover treatment of it help assuage that fear and explain that only they can see their site right now? 

Or the welcome modal. I feel like we've made a very generic statement like 'no one reads these things, they simply close them'. Perhaps we need to work on making the content more compelling, or less nitty gritty. We could then consider not providing a skip button and forcing people to see three quick screens. I could picture the content being something like:

* Welcome to your site, let's help you make it yours
* Edit all the starter content and add your own
* Don't worry, your site is hidden until you're ready to launch
* Here's how you access help if you need it

**Comment by simison** [comment]
This info is now in "welcome modal". I'll close this and we can have another todo for future improvements.
