### ISSUE TITLE
Gutenboarding: always show welcome modal to users

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41375]
We show welcome modal once a customer lands for the first time in the editor:

![image](https://user-images.githubusercontent.com/87168/80010453-1c8a1a00-84d3-11ea-8dcc-2b417818d401.png)

Once dismissed, we _never_ show it again, even when they created a new site.

Should we add an exception to rule and _always_ show when they land for the first time in the editor for a new site?

@dubielzyk thoughts?

**Comment by joanrho** [comment]
>always show when they land for the first time in the editor for a new site?
Makes sense to me.

**Comment by shaunandrews** [comment]
> add an exception to rule and always show when they land for the first time in the editor for a new site

Can you explain the rationale a little? As a customer, I wouldn't expect to see this modal more than once unless I explicitly triggered it.

**Comment by joanrho** [comment]
@shaunandrews We currently show the modal when users create a new site, but if they click out of it to dismiss, we never show it again even for future new sites they create. This change happened because I believe in the past, all Editor visits triggered the modal, which was quite annoying.

Here, we're now proposing showing the modal for all new sites upon first visit to the Editor. It's still dismissable and won't appear in subsequent visits to the Editor for the same site.

**Comment by shaunandrews** [comment]
> Here, we're now proposing showing the modal for all new sites upon first visit to the Editor. It's still dismissable and won't appear in subsequent visits to the Editor for the same site.

Understood. But I don't know _why_ we think it would be beneficial for customers to see the modal again after they create another site? I would assume people who intentionally create a new site have already seen the modal once, and are more likely to have used the editor.

**Comment by simison** [comment]
@shaunandrews consider that there can be significant time between customer creating new site again, so refresher guide would be more helpful than harmful.

Existing mechanism storing the dismissal at backend (it's still per-user dismissal, not per-site-per-user) would still be in effect ensuring this wouldn't get too repetitive or annoying. In the past, modal was always shown when you cleared your browser cookies, changed browser, got invited to edit an existing site, etc.

**Comment by simison** [comment]
I'm not entirely sure about this, but I've had in mind something along lines of us providing concrete next onboarding-steps in the modal in which case not having it show up might "break the flow" little bit. Just not sure how to elaborate on that exactly. :-)

(...modal could get replaced by some kind of tour in future without changing the dismissal mechanisms, but anyway.)

**Comment by joanrho** [comment]
Assigning to myself since I'll be working on improving the pre-launch experience, which covers this modal (or whatever will replace it). We can revisit alternative solutions in separate issues.

Given that the majority of our customers only have 1 site, I'd recommend we move this issue forward with the proposed direction of showing the modal for all new sites upon first visit to the Editor.

**Comment by dubielzyk** [comment]
I'm inclined to agree with @shaunandrews here. I also don't think the modal contains information that valuable once it's been read or dismissed once. If you read it, it's quite generic and only really seems applicable for users who's never seen the editor. I would prefer to show it once and not again, but I don't feel super strongly (other that we should definitely not show it on every visit).

**Comment by simison** [comment]
Let's close this now and we'll think the topic more with custom tips-guide.
