### ISSUE TITLE
FSE: call-to-action-02 pattern broken on Atomic

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#41380]
The Call To Action pattern has a broken button block on Atomic, seemingly both in Gutenberg 7.8.1 and 7.9.1. It worked on dotcom. To avoid shipping a broken pattern, I removed that one from the dotorg version of v1.1.

#### Steps to reproduce

1. On your Atomic test site, deactivate your FSE plugin.
2. Upload and activate FSE v1.1 as it exists on dotcom: [fse-build-archive.zip](https://github.com/Automattic/wp-calypso/files/4518800/fse-build-archive.zip)
3. Go to the editor and try to insert the Call To Action pattern
4. Note the broken button block

#### Screenshot / Video
![image (3)](https://user-images.githubusercontent.com/1398304/80029756-1593e500-849c-11ea-91aa-fa7bfc62dd74.png)

See #41152.

**Comment by andrewserong** [comment]
Looks like on simple sites, we end up getting different markup to what's in `call-to-action-02.php`, possibly due to the [code to fix invalid blocks](https://github.com/automattic/wp-calypso/blob/master/apps/wpcom-block-editor/src/wpcom/features/fix-block-invalidation-errors.js#L47), that's running on simple sites. If I copy and paste the markup that gets added in a simple site to an Atomic site, it works for me. The solution is likely to update the markup to something like below: 

```html
<!-- wp:cover {"url":"https://dotcompatterns.files.wordpress.com/2020/04/louis-hansel-shotsoflouis-d0ueoxdvj5i-unsplash.jpg","id":181,"dimRatio":20,"customOverlayColor":"#000000","focalPoint":{"x":0.5,"y":"0.70"},"minHeight":620,"align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim-20 has-background-dim" style="background-image:url(https://dotcompatterns.files.wordpress.com/2020/04/louis-hansel-shotsoflouis-d0ueoxdvj5i-unsplash.jpg);background-color:#000000;background-position:50% 70%;min-height:620px"><div class="wp-block-cover__inner-container"><!-- wp:jetpack/layout-grid {"addGutterEnds":false,"column1DesktopSpan":10,"column1DesktopOffset":1,"column1TabletSpan":8,"column1MobileSpan":4,"column2DesktopOffset":1,"className":"column1-desktop-grid__span-10 column1-desktop-grid__start-2 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-10 column1-desktop-grid__start-2 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1 wp-block-jetpack-layout-gutter__nowrap"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:paragraph {"align":"center","className":"margin-bottom-none","style":{"color":{"text":"#ffffff"},"typography":{"fontSize":80}}} -->
<p class="has-text-align-center margin-bottom-none has-text-color" style="font-size:80px;color:#ffffff"><strong>Get it delivered</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","className":"margin-top-none","style":{"color":{"text":"#ffffff"}}} -->
<p class="has-text-align-center margin-top-none has-text-color" style="color:#ffffff">If you can’t come to us, we’ll go to you.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button {"style":{"color":{"text":"#ffffff","background":"#a5150f"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="background-color:#a5150f;color:#ffffff">Order now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid --></div></div>
<!-- /wp:cover -->
```

So my hunch is that the markup already might have had validation errors, but we're only see it on Atomic sites, because that invalidation is being dealt with "automatically" on simple sites.

**Comment by andrewserong** [comment]
@obenland I think I was totally off on my hunch the other day — I got a little bit further today investigating this. If I disable CoBlocks on the Atomic site, then the `call-to-action-02` pattern renders correctly. However, if I enabled CoBlocks, then the error displays. So I'm now wondering if something in the CoBlocks Buttons block deprecations could be causing a conflict somewhere? https://github.com/godaddy-wordpress/coblocks/tree/master/src/blocks/buttons

I imagine we'd be seeing the error on Atomic sites and not simple sites due to the simplified build we use in simple sites, so that might be why we're not getting a conflict there.

**Comment by obenland** [comment]
From what I gathered so far, I think it's related to the button's custom text color. Coblocks seems to expect that style attribute to be present on the button's surrounding div element, while Core adds it to the button itself. There seems to be a conflict of some sort
