### ISSUE TITLE
Earn: Revisit call to actions after someone upgrades the plan

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41590]
The call to action buttons on /earn are not very clear, or helpful, after you upgrade. Let's see if we can find better copy and destinations.

**Comment by danhauk** [comment]
Here's a first stab at improving the call to actions here. I'm still learning about all things Earn so please correct me if I've misunderstood the way anything here works.

I'm also not sure of the technical lift required to check state and customize the CTA a bit, but it would be really helpful for our users.

#### Default state
I've also made a few tweaks to the feature copy.
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/448298/82248228-c5cb0100-9915-11ea-9ce6-6014caa2ef18.png">

1. One-time payments - `Learn how` would open the [Simple Payments Block](https://wordpress.com/support/wordpress-editor/blocks/simple-payments-block/) support doc in a modal using the [`<InlineSupportLink>`](https://wpcalypso.wordpress.com/devdocs/design/inline-support-link) component to keep users in the context of this page.

#### Set up states
When recurring payments and WordAds are set up, the CTAs change to provide a more clear expectation of where the user is going.

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/448298/82248252-ce233c00-9915-11ea-8232-a60a1c2826fe.png">

@davemart-in @fditrapani @artpi Do you any have insight into what people expect when they click the current CTAs? I agree they're not clear as-is, since they just repeat the heading. Any additional info would also be helpful.

**Comment by davemart-in** [comment]
@danhauk I don't. Your guess is as good as mine.

**Comment by danhauk** [comment]
@lauac and @donlair are working on new copy for these cards and CTAs in #42541 and pbMlHh-dE-p2

**Comment by gwwar** [comment]
@danhauk is there any work left on this issue?

**Comment by danhauk** [comment]
Closing since we've got some great folks helping out with CTAs and copy on the marketing side. We can tweak as needed going forward.
