### ISSUE TITLE
Broken Layout Selector: Missing Fonts, Off-canvas Preview in Layout Selector/Editor

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#41719]
To reproduce …

1. Create a new WP.com site as a new user
2. Click Add New Page at /pages to bring up the layout selector
3. Examine the layout selector 
4. Notice the missing theme fonts in the layout selector
5. Examine the two layouts in the screenshot below and notice that the blocks in the layout extend beyond the canvas
6. Select one of the layouts and notice the same issue as item 5 in the editor
7. Compare with the front-end view where the theme fonts and horizontal display appears to be working correctly.

![image](https://user-images.githubusercontent.com/545779/80833424-1f140000-8bb4-11ea-8a55-f02ec0a796fc.png)

![image](https://user-images.githubusercontent.com/545779/80833448-2804d180-8bb4-11ea-9f8c-d394c0c7f102.png)

cc @kjellr I believe the editor views are a theme issue.

**Comment by kjellr** [comment]
> Examine the two layouts in the screenshot below and notice that the blocks in the layout extend beyond the canvas

This appears to be a problem with all Varia themes. I think it's just the Jetpack Layout Grid block. cc @allancole

**Comment by kjellr** [comment]
^ I opened a PR that will fix the theme portion of this, but I'm still a little unsure why this is occurring — I can't reproduce this locally using these themes + layouts, and the rule I'm overriding there come straight from Gutenberg, not from the theme. So I'd suggest we investigate a little more. 

If we want to clean this up quickly, we can try removing those Layout Grid Blocks from inside of group blocks in the layouts we offer.

**Comment by andrewserong** [comment]
Just tested this issue against a Gutenberg Edge site running v8.0.0 and it looks like upgrading Gutenberg resolves some of this (though for some reason the page title isn't centred correctly):

| Services | Contact |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/14988353/80932854-a48def00-8e04-11ea-9108-5cb0d284147a.png) | ![image](https://user-images.githubusercontent.com/14988353/80932862-a9eb3980-8e04-11ea-8a60-b8c1be0f8b65.png) |

I know Gutenberg has recently changed a number of classnames in the editor, so that affect things in the page layout previews, too.
