### ISSUE TITLE
Audio Block: The block does not play .mp3 files on Safari, but they do play on Chrome and Firefox

### ISSUE THREAD

**Issue by zyousafi** [Automattic/wp-calypso#41760]
#### Steps to reproduce

1. Start at https://wordpress.com/posts/
2. Click **Add new post**
3. Give the post a title.  Click on the `+` sign and add an **Audio Block**
4. Save the post
5. View the post in Safari
6. The **Audio Block** with the `.mp3` file will show an error message like in the image below.
7. Now view the post in Chrome or Firefox.  The exact same **Audio Block** doesn't show any error and it plays without issues

![image](https://user-images.githubusercontent.com/18581859/169451873-13d25fcf-781e-411f-9f7e-065a98c557b5.png)

#### What I expected

That the **Audio Block** would play `.mp3` files on Safari, just as it does on Chrome and Firefox

#### What happened instead

The **Audio Block** shows an error message on Safari and doesn't play the `.mp3`

#### Browser / OS version

I'm using Safari 13.0.5 on a MacBook Pro running macOS Catalina 10.15.3

#### Screenshot / Video

The error message on Safari looks like this: 

![image](https://user-images.githubusercontent.com/18581859/169451873-13d25fcf-781e-411f-9f7e-065a98c557b5.png)

#### Context / Source

Spoke to a user who reported this issue here: #20796585-hc
The follow-up e-mail can be found here: #2941007-zen

#user-report

**Comment by davipontesblog** [comment]
I was not able to replicate this following the same steps, on my test site on Business plan, simple.
Gutenberg: 8.2.1
CoBlocks: 1.23.0
wpcom-FSE: 131824367

Closing this for now since it seems to have been fixed. If more issues occur please reopen.

**Comment by hacchism** [comment]
Reopening the issue as I got another report: #26994237-hc

I could replicate the issue following the steps Zohair mentioned, on my test site on eCommerce plan(Atomic).

Gutenberg: 9.6.2
Safari's version: Version 13.0.4

**Comment by xpurichan** [comment]
I just replicated this issue on an Atomic site in Safari version 14.0.3.

I also noticed that the old Droplr image links in the original post were broken. I've taken new screenshots and replaced them.

Adding the "Type: Bug" to this report.

**Comment by cathymcbride** [comment]
I'm not reproing on safari or atomic on Gutenberg 9.9.3. @xpurichan can you still repro?

**Comment by xpurichan** [comment]
@cathymcbride I just re-tested on a simple site and an AT site and both are working well for me!

MacOS: 10.15.7
Safari: Version 14.0.3 (15610.4.3.1.6, 15610)
Gutenberg: 10.0.0
Jetpack: 9.4.1

**Comment by edwinho89** [comment]
Hello. I'm reopening this issue as it is now reproducible and reported here: 3906809-zen

MacOS: 11.2.3 (20D91)
Safari: Version 14.0.3 (16610.4.3.1.7)
Gutenberg: 10.3.2
Jetpack: 9.6.1

You'll see similar results when visiting audio blocks on iOS devices (Chrome and Safari)

**Comment by kwight** [comment]
I'm dropping this to normal priority, due to limited people experiencing it.

**Comment by retnonindya** [comment]
I received user report here:
4397342-zd-woothemes

This is the user's device:
Safari: 15.0
MacOS Big Sur 11.6

As for me, I can see the Error when I accessed their site on Safari -- and the specification is the same as the user's. The user's website is in Personal plan (SIMPLE site)

I checked Google, and I found a discussion from 2017, and it seems like the cause is a corrupted file? 🤔 

--- 

UPDATE: Yep, it seems like the cause is some kind of funky MP3 files. I did a test on my test site. I'm using Audio block, and I uploaded two files (both are MP3s) -- so, two Audio blocks.

One block is using the user's MP3 file.

Another one is my MP3 file.

I can confirm only the user's MP3 file giving out error, while the other MP3 file plays just fine on Safari.

**Comment by liviopv** [comment]
I had a chat 33477270-hc with the issue above and it turned out that it was a problem with the file.

In my case, the user was "changing" .m4a files into .mp3 by editing the file name from Finder, which created a .m4a file labeled as .mp3. Switching it back to .m4a by renaming the file fixed the issue.

**Comment by youbrokesomething** [comment]
No reports of this issue since 2021. I'm going to close this. Please reopen if any new user reports come in.
