### ISSUE TITLE
Gutenboarding: Modal-first mobile-first domain picker stylesheets.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#41806]
The stylesheets are now a bit of a mess and a refactoring is needed. The stylesheet in the current domain picker was initially designed with this frame of mind:
- popover-first over modal-first
- desktop-first over mobile-first

And I would like to turn it into:
- modal-first
- mobile-first

The reason for this is that the modal version of the domain picker is more widely used than the popover version, and soon enough it's going to be turned into a step and also used in wp-admin.

If the stylesheet is popover-based, it will cause a lot of overrides once domain picker gets reused in other places.

We have 4 views:
- popover view (desktop & mobile)
- modal view (desktop & mobile)
- more views to come (wp-admin, step...)

with varying heading sizes, margins and sticky footer.

We have 3 stylesheets:
- base stylesheet
- popover stylesheet
- modal stylesheet
- more stylesheet to come (wp-admin, step..)

The base stylesheet should be mobile-first + modal-first. Any overrides should be done respectively in popover & modal stylesheets.

The reason why stylesheets should be modal first is because all of the views are mostly modal-first, the only deviation is the popover desktop.

Popover mobile should be modal-first, this is because the current transition from Popover Mobile to Modal Mobile is really weird, as the margins and font-size deviate even though the content looks similar. Popover Mobile should inherit margins and font-size from Modal Mobile. 

@dubielzyk When popover mobile view becomes modal-first, it will no longer look the same as in Figma, but it will ensure the transition from popover mobile to modal mobile looks more seamless (consistent heading size, consistent margins, etc.).

**Comment by dubielzyk** [comment]
>When popover mobile view becomes modal-first, it will no longer look the same as in Figma

How come? What will be different?

**Comment by simison** [comment]
Thanks for logging the issue. 👍

We coild work on this while moving the modal to wp-admin in coming weeks.

**Comment by yansern** [comment]
> How come? What will be different?

@dubielzyk The font size & margins on popover-mobile does not look the same as the font size & margins on desktop-mobile. So when a mobile user hit "More Options", suddenly the heading expands and the margin reduces, even though content wise they look almost the same.

**Comment by razvanpapadopol** [comment]
Instead of having all these stylesheets we're using specifically for Domain Picker, why not start looking at some _component-first_ architecture? 

By carefully checking the designs, the Domain Picker modal, as a container, shares a lot of similarities with the new [Plans Grid](https://github.com/Automattic/wp-calypso/issues/41787) container and all the steps in Gutenboarding (except acquire intent):
- same heading styles (mobile and desktop) - we already have them as [components](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/components/titles.tsx)
- same action buttons group style and positioning (sticky on mobile) - we could introduce a container `<ActionButtons />` that receives buttons directly as children or as props `primary` and `secondary`.
- same spacing (top/bottom) - we already have a [mixin](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/mixins.scss#L54-L60) and we could use it to create a component `<HeaderContainer />`

I'm thinking of a header structure like this (example for Domain Picker):
```
<HeaderContainer>
  <Title>{ __( 'Choose a domain' ) }</Title>
  <Subtitle>
    { showDomainConnectButton ? 
     __( 'Free for the first year with any paid plan.' ) : (
     __( 'Free for the first year with any paid plan.' ) }
  </Subtitle>
  <ActionButtons
     primary={<ConfirmButton />}
     secondary={
	<CloseButton
		className="domain-picker__close-button" // only if we need some specific styling
		onClick={ onClose }
	/>
     }
  </ActionButtons>
</HeaderContainer>
```

And we could then rewrite the following bits so we get rid of the duplicated CSS and also align design of these common parts of Gutenboarding. 
- [domain picker](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/components/domain-picker/index.tsx#L151-L166) 
- [design selector](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/onboarding-block/design-selector/index.tsx#L57-L71)
- [style preview](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/onboarding-block/style-preview/index.tsx#L67-L92)

Then I don't really agree having the popover overriding modal styles. Domain picker popover should be a separate container in which we could render the same elements as above but they will get positioned separately. We'll probably re-use it as well in wp-admin in some future iteration.
> So when a mobile user hit "More Options", suddenly the heading expands and the margin reduces, even though content wise they look almost the same.
This can probably be solved with some subtle fade transition.

**Comment by yansern** [comment]
@razvanpapadopol Seems like a pattern is emerging indeed, I'm all towards a standardized structure!

**Comment by razvanpapadopol** [comment]
I think we can close this now. We can follow the [new introduced pattern](https://github.com/Automattic/wp-calypso/pull/44077) and add to `@automattic/onboarding` package any reusable components from Gutenboarding.
