### ISSUE TITLE
Gutenboarding: Theme demo homepage images added to Media Library

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#41831]
#### Steps to reproduce

1. Use Gutenboarding to pick a starter design and create a new site
2. Visit the editor and add an image block
3. Use the image block to visit your Media Library
4. See a set of images related not to your starter design but, if you know what's happening, a theme demo site. 

If you do not know why this is happening the results are confusing.

Some screenshots to demonstrate.

When I select the Vesta design in Gutenboarding I see the following in my media library.

![image](https://user-images.githubusercontent.com/545779/81115616-9fef3680-8ee9-11ea-9e61-0ecb5a06c90f.png)

These are images from [the Mayland theme](https://maylanddemo.wordpress.com/).

When I select the Bowen design in Gutenboarding I see the following in my media library.

![image](https://user-images.githubusercontent.com/545779/81115685-ba291480-8ee9-11ea-998e-afaf01dd4252.png)

These are images from [the Coutoire theme](https://coutoiredemo.wordpress.com/).

**Comment by ramonjd** [comment]
This is Headstart pulling in the theme's images. It's not ideal behaviour but it's expected behaviour.

Vesta is [based on Mayland](https://github.com/Automattic/wp-calypso/blob/b632332e6cbb848ea1f8f069e87aa359dfe34bf9/client/landing/gutenboarding/available-designs.ts#L7)

It will require, what your mechanic might call, a major overhaul. 

My uneducated guess is that we can tell Headstart not to upload any theme images in the case of Brice, Vesta and so on.

**Comment by ianstewart** [comment]
Could we also potentially tell it to use a different annotation? As in generate an annotation for each starter design. That part is easy. :D We have the sites ready and the script exists. Just needs to be stored somewhere and then Gutenboarding uses those particular annotations?

**Comment by ramonjd** [comment]
>  As in generate an annotation for each starter design ... Just needs to be stored somewhere and then Gutenboarding uses those particular annotations?

It's a good idea. Hire this man!

I'm not sure, however, if it will be more or less work to create, store, and update annotation paths in headstart since we're populating the template content on the fly in the `sites/new` endpoint callback **_after_** headstart has done its thing.

Still, it might allow us to clean up a couple of areas. 

For example, for sites created via Gutenboarding, we're deleting _post hoc_ all non-home pages and posts (where there is no latest posts block on the homepage). D42257-code

Any annotations for such sites, therefore, would be very sparse (no images, no extra pages or posts), and I believe we wouldn't need to worry about localization since the homepage content, as mentioned, is added after site creation

So I'm wondering if we couldn't just pass some flag to headstart to tell it to ignore the image array in the theme annotation for now.

**Comment by andrewserong** [comment]
This was fixed a fair while ago when we moved to using Gutenboarding specific Headstart annotations. (Just double-checked it on a freshly created to site to be sure). The Headstart annotations are in `nux-helpers/gutenboarding-content` and more info in: PCYsg-r7w-p2)
