### ISSUE TITLE
Gutenboarding: Visual fixes for domain page

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#41851]
- [ ] Clicking the back button on the domain page doesn't do anything.
- [ ] When entering the domain page, the scroll should reset to the top. Reproduce by going to the Design screen, scroll down, then click Domain picker and More Options. You'll see the [top headline chopped off a bit](https://d.pr/i/sqJGmf)
- [ ] Header spacing is off. [See mock](https://d.pr/i/rY6lGo) (left is mock, right is dev). Make sure get the right measurements from Figma.
- [ ] The action buttons in the top right are not consistent with the rest of Gutenboarding flow (Design and Style/Fonts page). The _Cancel_ button is off center as well. [See mock](https://d.pr/i/BPAEdM)
- [ ] Input field font-size should be `14px`

**Comment by razvanpapadopol** [comment]
> Clicking the back button on the domain page doesn't do anything.

This is a good one, it's applicable also for plans grid and it's a [usual source of frustration](https://www.nngroup.com/articles/overuse-of-overlays/) for web users. We've implemented them as modals but they are uncommon since:
- they don't have (x) button to close
- they don't look like modals (no opacity effect behind, they cover the full-width of the screen, etc)
- ESC button doesn't work

But still we are displaying them without changing the route. I believe this has to change. I'll work on it in #41857 

Then use could still include them in some overlay when really needed (eg: wp-admin) with all the points mentioned above fixed, including the override of the browser back button.

> When entering the domain page, the scroll should reset to the top. Reproduce by going to the Design screen, scroll down, then click Domain picker and More Options. You'll see the top headline chopped off a bit

This will be fixed when we change the route when opening domain page.

>   Header spacing is off. See mock (left is mock, right is dev). Make sure get the right measurements from Figma.
 The action buttons in the top right are not consistent with the rest of Gutenboarding flow (Design and Style/Fonts page). The Cancel button is off center as well. See mock

After merging #41857 we can reuse generic parts from there to provide consistency. Details in https://github.com/Automattic/wp-calypso/issues/41806#issuecomment-624495834

**Comment by yansern** [comment]
Fast forward. Styling issues have been rectified. And we now have reusable Title/Subtitle/ActionButtons.
