### ISSUE TITLE
Gutenberg: When copy-pasting post/page contents into Custom HTML block, the code will be removed when the post/page is saved/updated

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#41860]
Uhhhh, the title is really confusing. So sorry! So, the issue (?) is when we copy-pasted page/post content in HTML format into a Custom HTML block, saved it, navigate away, then rechecked it, the code we pasted into the Custom HTML block disappears.

#### Steps to reproduce

1. Open a page or post with Block Editor/Gutenberg.
2. View the page/post using Code Editor view (click the three dots on the top right corner > Code Editor).
3. Copy the contents.
4. Create new page/post in Block Editor.
5. Add new block: **Custom HTML block**.
6. Paste the contents we just copied into the Custom HTML block.
7. Click 'Preview' on the block toolbar, see the contents are all there.
8. Click 'Update' to save the changes.
9. Navigate out from the editor.
10. Return to the page/post with the Custom HTML block.
11. Interestingly, the contents are visible on the live site.

#### What I expected... Sort of?
The code I just pasted into the Custom HTML block stays.

#### What happened instead
Empty Custom HTML block with placeholder text "Write HTML..."

#### Browser / OS version
Chrome. macOS Catalina.

#### Screenshot / Video

This is the code I pasted into the Custom HTML block (I'm copy-pasting the code from Form block):

![block](https://cldup.com/cwDO4sm82l.png)
*Direct link: https://cldup.com/cwDO4sm82l.png*

#### Context / Source
I wanted to check with you folks if this is an expected behavior from Custom HTML block (to have the code stripped out/removed from Custom HTML block if the code is blocks-related.) I able to test this on my test sites (non-plugin WordPress.com sites and sites with customized plugin.)

I feel that this is expected (?) because if one wants to copy-paste a content from one page/post in code/HTML format, they need to paste it by using Code Editor view, I guess? 🤔 

So, not super urgent, but I just wanted to ask you folks for some clarifications here on what I can expect from Custom HTML block behavior. Thank you!

**Comment by annacmc** [comment]
Reproduced in both wpcom, wporg/local environments on Chrome Version 88.0.4324.96 (Official Build) (x86_64) and Safari Version 14.0.2 (16610.3.7.1.9)

**Interesting additional notes:**

- The same issue does not occur with regular HTML tests. Only when copying block code out of 'code view' such as `<!-- wp:paragraph {"align":"left"} -->`

- If you follow on from the provided steps to replicate with the following:

1. Return to the page/post with the Custom HTML block, and see that the block shows empty (despite content previewing correctly)
2. Add new code into the same empty looking HTML block
3. View the preview: See it overwrites the displayed content, rather than adds to it.

**Comment by annacmc** [comment]
Closing this up as a new issue has been opened in the Gutenberg repo at https://github.com/WordPress/gutenberg/issues/28537 for this.
