### ISSUE TITLE
Button Block: Built-in color palettes inoperable on non-Varia themes

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#41873]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/themes/
2. Select "Show All Themes" and activate any non Varia-child theme (Original report was on Twenty Twenty)
3. Create a new post or page and insert a button block. Give the button some text
4. Using the provided Color settings, select any of the preset color bubbles for Text or Background color
5. Note the color does not change or it reverts to theme default
6. Click on "Custom Color"
7. Set any color that _isn't_ one of the provided presets
8. Observe color updates
9. Use color picker to manually select one of the preset options (enter the hex code by hand)
10. Again, colors do not change or it reverts to theme default

I've reproduced this on Twenty Twenty, Canard, and Rowling, but not on themes like Barnsbury or Mayland.

#### What I expected
The selected color should appear in the editor and on the preview/published page

#### What happened instead
Any custom color will work fine, but attempting to use any of the provided color options for the button will revert to the theme's default button color

#### Browser / OS version
Chrome Version 81.0.4044.138
macOS 10.15.4

#### Screenshot / Video
![Screen Capture on 2020-05-06 at 11-02-26](https://user-images.githubusercontent.com/13856531/81197517-61f81e00-8f8e-11ea-984e-e1114a3cfbbc.gif)

#### Context / Source
#user-report
20883734-hc

**Comment by marcuswisecaesar** [comment]
Another Report here: 20887556-hc

**Comment by designsimply** [comment]
Tested and confirmed as part of WPAndroid 15.1 beta testing (see test case "Colors" [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2241#issue-414981743)).

![theme-button-colors-are-not-working-in-the-wpcom-editor](https://user-images.githubusercontent.com/1119271/84945802-f0d77a80-b0a4-11ea-8238-33f575ea9bb4.png)

<img width="1280" alt="Screen Shot 2020-06-17 at Jun 17 2 10 40 PM" src="https://user-images.githubusercontent.com/1119271/84945812-f46b0180-b0a4-11ea-99f1-191fb1edb91c.png">

<sup>Firefox 77.0.1 on macOS 10.15.4.</sup>

Changes to theme colors for buttons in the block settings aren't reflected in the editor but do show up correctly in previews and on the front-end after a post is published. Custom colors work as expected in the editor. ([1m36s](https://cloudup.com/cTCXBOFc3Sh))

Tested and confirmed this problem is not happening in Gutenberg on core with a WP 5.4.2 site with no active plugins. ([25s](https://cloudup.com/cAgDzKgLLoH))

**Comment by KokkieH** [comment]
Not sure if it's the same issue, as details seem to differ a bit, but seeing something similar in Escutcheon:

In the editor itself the colors show correctly as selected:

![Edit_Post_‹_Shift_to_the_left_—_WordPress_com](https://user-images.githubusercontent.com/11873759/85990546-7d156600-b9f2-11ea-93e8-3bf4fa9e6689.png)

But on the published post the theme default overrides the text color (not the background).

![Testing_buttons_–_Shift_to_the_left](https://user-images.githubusercontent.com/11873759/85990618-96b6ad80-b9f2-11ea-9d69-773f9cb74ce6.png)

**Comment by ezebecke** [comment]
Another Report here: 22945259-hc. Hever theme

**Comment by yansern** [comment]
This will be fixed in Gutenberg 8.7. https://github.com/WordPress/gutenberg/pull/24153
