### ISSUE TITLE
Gutenboarding: Site topic input can sometimes jump around

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#41874]
At certain browser widths (or when I zoom way in so I can read things) the madlibs-style inputs on the first step of the new signup flow can sometimes jump around. 

![intent responsiveness](https://user-images.githubusercontent.com/191598/81202392-8b1bad00-8f94-11ea-9f3c-5af75acbd305.gif)

In the above GIF you can see that the input first appears on it's own line, but then jumps up to the first line when I start typing. As I continue to type, the input jumps down to it's own line again. At this point, the list of suggestions renders on top of the skip link.

Once you proceed to the next step, where you enter your site's name, its easy to get the suggestions to render on top of the text below.

![image](https://user-images.githubusercontent.com/191598/81202688-f49bbb80-8f94-11ea-8eb8-bfc4768071e3.png)

**Comment by razvanpapadopol** [comment]
> At certain browser widths (or when I zoom way in so I can read things) the madlibs-style inputs on the first step of the new signup flow can sometimes jump around.

It jumps when the user starts typing (placeholder gets hidden) because the placeholder has some reserved width in order to prevent continuous jumping while animating. This is a demo of how it would look like without that reserved width: https://cloudup.com/cor-ETe66A4. If it's acceptable, it shouldn't be a big change to implement.

Also when thinking of potential solutions for this, please keep in mind i18n. There are locales where the phrase doesn't end with the vertical input. Example for [Japanese](https://wpcalypso.wordpress.com/new/ja): https://cloudup.com/cVorrkWRW-5

> the list of suggestions renders on top of the skip link.

This is clearly a bug. The suggestions dropdown shouldn't be transparent. 

> Once you proceed to the next step, where you enter your site's name, its easy to get the suggestions to render on top of the text below.

I don't think this is a bug from technical point of view. Maybe we need some further design guidance. cc: @dubielzyk

**Comment by dubielzyk** [comment]
> Once you proceed to the next step, where you enter your site's name, its easy to get the suggestions to render on top of the text below.

Good call. I'll have a look.

> It jumps when the user starts typing

It feels like at least the typing animation shouldn't make things jump around. Can we set a min-width of the input field to be the same length as the longest suggestion? That should alleviate that issue. As for normal jumping, this will naturally happen if the string you enter is too long. I'm gonna look into reducing the edge-padding so it's less likely for it to wrap on two lines.

**Comment by shaunandrews** [comment]
It looks like some things have changed since I first posted this issue. The bugs are still there, but they're slightly different now. Check out this GIF to see what happens with the suggestions as the lines wrap:

![onboarding word wrapping](https://user-images.githubusercontent.com/191598/82058344-9ce70980-9692-11ea-9971-824754744a88.gif)

I'm not sure why the "Its called ________" bit showed up here; I never actually finished typing or selected anything from the suggestions.

**Comment by razvanpapadopol** [comment]
Maybe you pressed this skip button?
<img width="925" alt="Screenshot 2020-05-19 at 17 30 19" src="https://user-images.githubusercontent.com/14192054/82339293-8aecca00-99f6-11ea-9d82-ab4a1f4cfa2e.png">

We'll probably introduce fixed width for empty/filled in state with this change: https://github.com/Automattic/wp-calypso/issues/42363
So the current jumping issue should be fixed.

**Comment by razvanpapadopol** [comment]
Fixed in current version where placeholder lives inside the `<input/>`.
