### ISSUE TITLE
Show clarification prompt when trying to add a new domain or site

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#41943]
## Description

To this day, we have numerous people confused around the concept of adding a new domain and adding a new site. Happiness engineers deal with this confusion daily. The problem is, once someone creates a new domain or site unintentionally, it doubles or triples the amount of work that it takes to then fix the problem.

What I'd like to propose is to introduce an interstitial modal that shows any time someone goes to add a new domain or add a new site which looks something like this:

![duplicate-prevention](https://user-images.githubusercontent.com/5634774/81309356-dabfae80-9050-11ea-9896-608e4f2e4959.png)

Note: This design still needs some polish.

Anywhere customers can add a domain or add a new site, we should show this dialog.

Props for this design go to @shaunandrews who originally [designed this](https://a.cl.ly/P8uEQod5).

**Comment by klimeryk** [comment]
It's a great idea, but, IIRC, @fditrapani was also working on this? Could you add a P2 reference to the discussion - I remember seeing a few, but not sure which one is the newest :)

**Comment by fditrapani** [comment]
I was looking at this from a slightly different perspective and that is setting a domain as a primary domain before/after the domain is purchased but this might be something we think about at the same time though. 

> What I'd like to propose is to introduce an interstitial modal that shows any time someone goes to add a new domain or add a new site which looks something like this:

I think the interstitial could work well when creating a new site but I'm not sure it makes as much sense with the domain. Just noting that we might want to incorporate these options into this existing screen:

![image](https://user-images.githubusercontent.com/6981253/81321162-3d6c7680-9060-11ea-8e6a-786fbc5c364a.png)

**Comment by davemart-in** [comment]
Cool. Thanks for the feedback @fditrapani! I'll let @olesyabrk pick this design up from here.

**Comment by olesyabrk** [comment]
I transferred my existing site from HostGator to DotCom, and remapped my domain name at GoDaddy to the DotCom nameservers, so I'm very familiar with the modal @fditrapani mentioned. I documented my experience [here](https://www.figma.com/file/cClTgQI6zAcJc6OXWdayQF/Existing-Site-Migration-to-DotCom?node-id=0%3A1) as part of my research.

**Comment by olesyabrk** [comment]
I've created a number of iterations based on the original mock by @davemart-in, you can take a look at my thought process [here](https://www.figma.com/file/i5O4Mqmda7lfhkNb9bm5hf/Add-New-Site%2FDomain-Prompt?node-id=614%3A1964).

Some considerations and ideas:

- Based on the dev input and a convo with Rick, I'm moving towards adopting the Gutenberg style modal going forward with Calypso
- We're tackling two workflows as MVP: Add a Domain and Add a New Site

**Add a domain workflow**
![image](https://user-images.githubusercontent.com/51215741/82270596-26fccf80-992a-11ea-8379-0005540aa120.png)
![image](https://user-images.githubusercontent.com/51215741/82270612-3419be80-992a-11ea-91f1-a7c8a08677b1.png)
![image](https://user-images.githubusercontent.com/51215741/82270629-409e1700-992a-11ea-8eee-de0eafde76bb.png)
**Modal up close**
![image](https://user-images.githubusercontent.com/51215741/82270671-64615d00-992a-11ea-832e-e10621009dcf.png)

**Add a new site workflow**
![image](https://user-images.githubusercontent.com/51215741/82270722-94106500-992a-11ea-9216-133805e442ba.png)
![image](https://user-images.githubusercontent.com/51215741/82270742-a094bd80-992a-11ea-8fff-5f840e4e39e8.png)
![image](https://user-images.githubusercontent.com/51215741/82270763-adb1ac80-992a-11ea-9239-119051685781.png)
![image](https://user-images.githubusercontent.com/51215741/82270778-b609e780-992a-11ea-861d-ae8be7e54293.png)
**Full page modal up close**
![image](https://user-images.githubusercontent.com/51215741/82270840-f1a4b180-992a-11ea-80d7-ac0bfecbd5fe.png)

I'm suggesting two designs to match the visual progression of two separate workflows. If we need to scale back, I'm suggesting using the modal as MVP for both workflows. 

cc: @davemart-in @lcollette

**Comment by lcollette** [comment]
Recapping the feedback I left you earlier:

My gut reaction is for either Option E or Gutenberg C, as such, I’ve zoomed into feedback on them.

**Option E**

<img width="906" alt="Screen Shot 2020-05-18 at 8 19 18 PM" src="https://user-images.githubusercontent.com/181733/82280926-e494bc00-9944-11ea-9090-95db4b32aecd.png">

- I like the visual nature of this. Removing the Calypso chrome creates more focus for the user. It’s also just more visually interesting than the modal option.
- This is probably a non-issue but will the transition from the Intent step to Add a New Site step be noticeable enough?
- [Unrelated] Should these headers be sentence case?
- At the surface layer, as we roll out Gutenboarding to customers, will the visual language presented here map to there?

**Gutenberg C**

<img width="388" alt="Screen Shot 2020-05-18 at 8 17 40 PM" src="https://user-images.githubusercontent.com/181733/82280869-c202a300-9944-11ea-8666-fb48c6fa1e1c.png">

- This might be a stupid idea but have you tried a modal with the content of option E or something similar?
- C works best given the progression of content. It makes the most sense, to me, to have the domain beneath “Add another domain to use with your existing site” because it’s directly related. 
- [Nit] Both options end with “your existing site”, which makes them feel a bit repetitive.

**Generally**
- While I see why you're suggesting separate designs for each workflow, I'm on the fence about creating two different experiences for the same functionality. This may be an exception to that principle though. 
- Did you intentionally stick with existing components? If so, why?
- In the modal options, on the surface, the spacing throughout the card needs adjustment. The whitespace feels unintentional.
- In Option E, Add new site is presented as the first option, while Gutenberg C has Add another domain as the first option. Do we have data to inform which option we should present first? (I see now that this may be intentional)

**Comment by davemart-in** [comment]
Let's go ahead and pause this issue for now. We have some additional data that suggests that the vast majority of duplicate sites are actually coming from the signup flow and they take place within minutes of someone signing up.

**Comment by olesyabrk** [comment]
@davemart-in there is also data that the new onboarding is not mitigating this issue.

**Comment by davemart-in** [comment]
My understanding of the data is that the vast majority of duplicate sites occur within the first few minutes of a site being created. As a result, I'm not sure the proposal that we've made in this issue will make much of a dent.

**Comment by davemart-in** [comment]
I'm going to close this issue for now. Happy to resurrect it if we end up discovering that a good portion of duplicate sites are coming from outside the onboarding flow.
