### ISSUE TITLE
Update the NUX modal

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#41960]
Let's update the text and images for the Gutenboarding NUX modal! 🙌

The changes require work in the [FSE plugin directory](https://github.com/Automattic/wp-calypso/blob/ccf9cf2f21b9038274d1278e99129980fb5568e0/apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/wpcom-nux.js), and are meant for Gutenboarding sites only. 

The "Private until you're ready to launch" slide is [commented](https://github.com/Automattic/wp-calypso/blob/ccf9cf2f21b9038274d1278e99129980fb5568e0/apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/wpcom-nux.js#L102-L111) out at present for all sites, but we can turn it back on for Gutenboarding sites.

### The copy

> **Welcome to your website**
> Edit your homepage, add the pages you need, and change your site’s look and feel.
> 
> **Add or edit your content**
> Edit the placeholder content we’ve started you off with, or click the plus sign to add more content.
> 
> **Preview your site as you go**
> As you edit your site content, click “Preview” to see your site the way your visitors will.
> 
> **Private until you’re ready**
> Your site will remain private as you make changes until you’re ready to launch and share with the world.

![image](https://user-images.githubusercontent.com/6458278/81354447-f8ebe400-910e-11ea-937d-57276d22af8f.png)
![image](https://user-images.githubusercontent.com/6458278/81354454-fe492e80-910e-11ea-8d5f-dcdc92b1277e.png)
![image](https://user-images.githubusercontent.com/6458278/81354456-01441f00-910f-11ea-8e90-602fe43b58c1.png)
![image](https://user-images.githubusercontent.com/6458278/81354468-043f0f80-910f-11ea-9a5a-08114d6e8d37.png)

Context and links to Figma files
p1588879262397200-slack-CPFFQTG69

**Comment by ramonjd** [comment]
Hi @joanrho !

I just have a few questions:

Do the copy changes + images apply only for Gutenboarding or everywhere?

Only asking because the background colors of the images in the Figma file differ slightly to the existing SVGs

**Current**
#1381D8
<img width="594" alt="Screen Shot 2020-05-08 at 8 41 29 am" src="https://user-images.githubusercontent.com/6458278/81352119-16b64a80-9109-11ea-867a-f09977b416e6.png">

**New**
#3981D2
<img width="376" alt="Screen Shot 2020-05-08 at 8 40 10 am" src="https://user-images.githubusercontent.com/6458278/81351585-0baeea80-9108-11ea-891e-cbcb807d4911.png">

Also double checking that we're going to skip over the [step in the current flow](https://github.com/Automattic/wp-calypso/blob/5b1532662fa3eb2985e76a3c94df129c42e1481d/apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/wpcom-nux.js#L78) that doesn't exist in the Figma file. The "Customize your content" step with this image: 
<img width="544" alt="Screen Shot 2020-05-08 at 8 50 33 am" src="https://user-images.githubusercontent.com/6458278/81352081-03a37a80-9109-11ea-9f9d-74dddee11eb4.png">

**Comment by joanrho** [comment]
@ramonjd Sorry, that blue change in the "add block" illustration was an exploration on my part that I forgot to "undo" (I had wanted to see what unifying the blues between the background and the plus icon and search field border would look like). Please ignore that and let's just keep all the same colors as in the existing flow.

The only change is the text in each screen, the additional step, and the addition of the new illustration. I've just updated that new illustration in the Figma file to replace the W icon with a circle:

<img width="710" alt="Screen Shot 2020-05-07 at 5 26 45 PM" src="https://user-images.githubusercontent.com/204742/81354101-05792980-9088-11ea-9ed3-90ddae321253.png">

>Do the copy changes + images apply only for Gutenboarding or everywhere?

IMO this should be launched to all users, not just the Gutenboarding cohort because they will all be served the same Editor experience. Users who are not in the Gutenboarding cohort will still have private sites until they hit Launch in Customer Home or their site Preview, so the modal we show regarding "private until launch" (screenshot below) is still relevant and it's not specific to an Editor-launch. What do you think, @johnHackworth @olaolusoga?

<img width="699" alt="Screen Shot 2020-05-07 at 5 28 23 PM" src="https://user-images.githubusercontent.com/204742/81354241-5721b400-9088-11ea-9ada-6aa527da2a20.png">

**Comment by ramonjd** [comment]
Thanks for the update @joanrho !

I don't think translations for the new strings will be ready in time for soft launch, so we might have to do some `if/else` on the copy in the interim. That is, if "Gutenboarding" show the new copy, otherwise should the existing copy for which we have translations.

Gutenboarding will be released to `en` for the soft launch.
