### ISSUE TITLE
Cart awaiting payment notice has weird shadow

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#42003]
@rickybanister noticed a weird shadow under the global notice in the latest Chrome. I couldn't reproduce it with the Settings global notice and had trouble getting the cart awaiting payment notice to show up.

Also from Rick:

> I refreshed the page 10 or so times and each time the artifact got more faint and less tall until it was gone.

![image](https://user-images.githubusercontent.com/448298/81436459-8ba07900-9137-11ea-82f3-e28751043393.png)

#### Browser / OS version

Latest Chrome; Mac OS

**Comment by sixhours** [comment]
I started looking into this, but I can't reproduce it -- even though I've seen it for myself on @lcollette's screen, using the same exact site and setup.

**Comment by rickybanister** [comment]
I see it in the latest version of chrome on my laptop screen, no external monitor. In case any of those variables contribute to it.

**Comment by sixhours** [comment]
@lcollette found that tinkering with the `box-shadow` on the global notice produced different results, so I did some research around box shadows and Chrome. Here's an issue on StackOverflow with the exact same problem: https://stackoverflow.com/questions/61937184/strange-css-drop-shadow-bug-in-chrome-only

That thread suggests it could be related to `border-radius` and `box-shadow` on the same element, and using `filter` rather than `box-shadow` might be a workaround. Something like `filter: drop-shadow(0 2px 5px rgba(0,0,0,.2)) drop-shadow(0 0 56px rgba(0,0,0,0.15))` could replace the existing styles. It looks very similar if not exactly the same:

<img width="1680" alt="Screen Shot 2020-06-24 at 2 26 17 PM" src="https://user-images.githubusercontent.com/2124984/85612264-b6328c80-b626-11ea-9d39-4094c2f905d3.png">

My guess is this is related to different graphics cards and how they interact with Chrome for rendering, which may explain why I can't see it but Rick and Lynn can.

**Comment by sixhours** [comment]
`filter` has good support for modern browsers, but we'd be leaving IE 11 behind if we switched:

<img width="1334" alt="Screen Shot 2020-06-24 at 2 37 24 PM" src="https://user-images.githubusercontent.com/2124984/85613823-458c6f80-b628-11ea-8b34-ac0bb619e1a3.png">

**Comment by sixhours** [comment]
> My guess is this is related to different graphics cards and how they interact with Chrome for rendering, which may explain why I can't see it but Rick and Lynn can.

Confirmed, we do have different graphics cards, which probably explains my inability to see this. Good to know!

`filter` takes advantage of graphics hardware acceleration, `box-shadow` does not. I suspect that is why `filter` renders properly. Which also makes me wonder if enabling/disabling hardware acceleration for computers that use that particular Radeon card would have the same effect.
