### ISSUE TITLE
[Themes page]Theme menu has a blank menu item

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#42052]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/themes/
2. Click on the three dotted button and check underneath the menu items
3. You'll be able to hover over an empty one which, on some themes, acts like an activation button.

#### Browser / OS version
Chrome 81

#### Screenshot / Video
https://monosnap.com/file/QvNH8eJjH5Ru9Mq4ezs5XyLsqRDQ70

#### Context / Source
#manual-testing
Confirmed by @kjellr here: p1589197758250600-slack

**Comment by Robertght** [comment]
Still a problem:

![image](https://user-images.githubusercontent.com/6737345/109352557-b2c16600-7883-11eb-82e8-37c01ddc1e06.png)

**Comment by mreishus** [comment]
This is caused by something called [showAutoLoadingHomepageWarning](https://github.com/Automattic/wp-calypso/blob/87083962f859b79de269733f89ed1f0eb4e576cf/client/my-sites/themes/theme-options.js#L148-L150), which is turned into a menu item by [this code](https://github.com/Automattic/wp-calypso/blob/87083962f859b79de269733f89ed1f0eb4e576cf/client/components/theme/more-button.jsx#L93-L102).

I'm unsure of the purpose of `showAutoLoadingHomepageWarning` and if it is working.

**Comment by DanielSmithMichigan** [comment]
**High level thoughts so far:**

The blank menu option might have been created by mistake. When you click it, a modal is created which [prompts the user for additional input](https://user-images.githubusercontent.com/10274366/118731181-d521aa80-b806-11eb-9d14-ca5e976b1705.png).

Removing [the property Matthew discussed](https://github.com/Automattic/wp-calypso/blob/87083962f859b79de269733f89ed1f0eb4e576cf/client/my-sites/themes/theme-options.js#L200) will get rid of the blank menu option. ~~`The outstanding question to me is: Should the "activate" button be displaying that modal instead?~~

**Other details:**

The showAutoLoadingHomepageWarning originally came from [this commit](https://github.com/Automattic/wp-calypso/commit/4e5cfa45d471cdace6295bbd001da2cf9626a3d9).

The blank menu option existed at that time as well, and [this is how it used to function](https://user-images.githubusercontent.com/10274366/118731802-2af65280-b807-11eb-8ef6-04e7f4ed3a4d.png). The blank menu option was created at the same time the modal was created(NOTE 1). The "activate" button used to also create the modal at that time, but it no longer creates that modal. ~~As far as I can tell, right now **the blank menu option is the only way to get that modal**.~~

~~**Where I'm at now:**~~

~~Doing a git bisect to find when the 'activate' button stopped prompting with the modal.~~

NOTE 1: I know this, since I checked out 4e5cfa45d471cdace6295bbd001da2cf9626a3d9~1. Neither the blank menu option nor the modal existed in that commit.

**Comment by DanielSmithMichigan** [comment]
These are the conditions under which the modal is shown when using the "activate" button:
themeHasAutoLoadingHomepage && ! isJetpackSite && ! isSiteAtomic
