### ISSUE TITLE
Testing: Find solution for double callback warning

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#4206]
Part of #4915.

When you use dot reporter:` npm run test-client -- --reporter=dot` you can see this message 3 times:

> double callback!

Some comments about this issue can be found in #4121.

@umurkontaci:
> this is caused by superagent and when the request callback is called more than once. I do not know why it is happening but one instance I've found this happening is before hook on posts/actions.

@gwwar:
> I need to narrow this down further, but the `double callback` warnings are coming from `lib/posts/test/actions`, `lib/posts/test/post-list-store` and `post-editor/test/post-editor`

> Most of these come from the test setup. Not sure of the reason, but `SitesList = require( 'lib/sites-list/list' );` triggers this in `post-editor/test/post-editor`, while `PostEditStore = require( '../post-edit-store' );` triggers this in `lib/posts/test/actions`

**Comment by blowery** [comment]
a stab in the dark: superagent is loaded twice because mockery is being used in those tests that emit "double callback".

**Comment by samouri** [comment]
I commented out various require lines until I was able to isolate exactly which line was causing this (was there a better way of figuring this out?).

This LOCs responsible for the double callback: https://github.com/Automattic/wp-calypso/blob/master/client/lib/user/user.js#L27-L31

Something wacky is happening inside of the initialize / fetch.
I'll update when I've figured out exactly what was happening and the best way of fixing it.

**Comment by samouri** [comment]
Update: this issue is the same one as described here: https://github.com/node-nock/nock/issues/211
It only occurs when we pass in query params the request.  In this case its with me.get( { meta: 'flags'}, ...)
You can view the error by logging the output like: console.log( me.get(...) )

Error pasted below:

<pre>
Promise {
  <rejected> { TypeError: Cannot read property 'indexOf' of undefined
    at Request.end (/programming/automattic/wp-calypso/node_modules/superagent/lib/node/index.js:826:19)
    at request (/programming/automattic/wp-calypso/node_modules/wpcom-xhr-request/index.js:107:7)
    at WPCOMUndocumented.<anonymous> (index.js:47:10)
    at WPCOMUndocumented.request (support.js:73:11)
    at WPCOMUndocumented.request (index.js:74:11)
    at /programming/automattic/wp-calypso/node_modules/wpcom/dist/lib/util/send-request.js:91:9
    at Promise.exp (/programming/automattic/wp-calypso/node_modules/wpcom/node_modules/core-js/library/modules/$.def.js:38:36)
    at WPCOMUndocumented.module.exports (/programming/automattic/wp-calypso/node_modules/wpcom/dist/lib/util/send-request.js:90:9)
    at Req.get (/programming/automattic/wp-calypso/node_modules/wpcom/dist/lib/util/request.js:29:22)
    at Me.get (/programming/automattic/wp-calypso/node_modules/wpcom/dist/lib/me.js:49:25) response: undefined } }
</pre>

I'll investigate more tomorrow a good fix

**Comment by samouri** [comment]
Turns out there are multiple problems going on in multiple places. As things are right now:
1. Superagent is being too forgiving of bad clients/tamperers by [catching extra errors](https://github.com/visionmedia/superagent/pull/1005#issuecomment-227056391).  This isn't great and hopefully someone will solve it because it is what allowed nock (and potentially other libraries) to get away with other problems.
2. Nock is [breaking Node.js http expectations](https://github.com/node-nock/nock/issues/211#issuecomment-227352613).   This is relatively more egregious and significantly easier to fix.  I've submitted a PR to them and hopefully what I said there made sense / the PR can get through

**Comment by gziolo** [comment]
It looks like the issue is caused by two internal libraries that trigger network requests. Those two usually help:

```js
mockery.registerMock( 'lib/abtest', noop );
mockery.registerMock( 'lib/analytics', {} );
```

**Comment by blowery** [comment]
@gziolo I think some new `use-xxx` mock helpers might be in order for those two. We run into them causing problems quite a bit.

**Comment by gziolo** [comment]
@blowery Good idea, I need to check more tests and confirm that it's the root cause of double callback warning :)

**Comment by gziolo** [comment]
Folders to fix:
* [x] `client/auth/`
* [x] `client/components/`
* [ ] `client/lib/`
* [ ] `client/my-sites/`
* [ ] `client/post-editor/`
* [ ] `client/reader/`
* [x] `client/signup/`
* [ ] `client/state/`

**Comment by gziolo** [comment]
This task was divided into 3 PRs. They are waiting to be reviewed:
* #7366
* #8100 
* #8168

It turned out that user object creates most of the warnings. `Analytics` and `abtest` are other libraries that cause troubles.

**Comment by aduth** [comment]
@gziolo Not sure if you had meant for #8168 to close this, as the autoclose was triggered by the text "Partially fixes".

Another question though: How can we document this issue so that developers don't fall into the same traps? I'm still not entirely clear from the issues and PRs what causes the problem. Would it help to mock some of these methods from the base test runner?

**Comment by gziolo** [comment]
Yes, GH autoclosed it. I need to mention reference more wisely next time :) 

I think we shouldn't change that much in the way we write tests. However I can enumerate action items which should help us avoid this kind of warning:
1. Reduxify everything, in first place `Sites` and `User` objects.
2. Always use analytics middleware to trigger events.
3. Make sure `abtest` library doesn't trigger network request - it might be directly related to the item (1).

There is also a growing number of React warnings that started to pollute console output after we upgraded React to 15.3, which we should fix.
