### ISSUE TITLE
Editor: Mobile styles broken

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#4211]
#### Steps to reproduce
1. Visit https://wpcalypso.wordpress.com/post on small screens
2. Pick a blog
3. Small screen styles appear broken

#### Browser / OS version
OSX Yosemite (10.10.5) Chrome, iOS 9.2 Chrome

#### Screenshot / Video

![img_4134](https://cloud.githubusercontent.com/assets/2846578/13956250/5c91dc44-f01e-11e5-9c42-3e66a55fca75.PNG)

The blog title is far away and below the lock icon instead of right next to it, and the dark background beneath "Actions" and "X" hits against the left edge of Actions, instead of having a margin between the button and the edge. 

The title also takes up a tremendous amount of vertical space, which contributes to it feeling broken.

**Comment by codebykat** [comment]
That weird border is showing up on the medium-sized styles too:

![screen shot 2016-03-22 at 12 19 24 pm](https://cloud.githubusercontent.com/assets/52152/13964946/7b3c6d8e-f029-11e5-8c5d-3db8e43b157e.png)

**Comment by folletto** [comment]
Noting that that part has already a redesign pending, which would be better instead of fixing it if possible. :) 

Reposting here the relevant bit from the Calypso Editor v1.1 mock:

![screen shot 2016-03-22 at 20 14 02](https://cloud.githubusercontent.com/assets/4389/13966506/a5606868-f06a-11e5-8b0c-3c859d4d936a.png)

**Comment by folletto** [comment]
Trying to disassemble the issue:

1. The fade is the CSS to allow for the label to fade when it's too long. However requires uniform color, and by default in the Editor that's white, hence the white fade. Needs probably a rule that changes the fade color at the mobile breakpoint. Should be straightforward.
2. The misalignment of text might be due to a change in how we handled the lock icon.
3. The title space on top should be there due to the space needed for author switcher on the left (on multi-user sites) and the icons to the right.

**Comment by melchoyce** [comment]
Pending redesign would definitely be better than fixing :+1: Is that on anyone's plate?

**Comment by folletto** [comment]
Not sure... maybe @aduth knows and can suggest an approach here. :)

**Comment by aduth** [comment]
I imagine the fade should be a quick fix, and will look to resolve it in the next day or so.

The redesign is certainly overdue. While it's not a main focus for our team at the moment, I'll try to make a more conscious effort in dedicating some downtime (if any exists) in the coming weeks. It may coincide well with ongoing editor component refactoring in adopting Redux state (for custom post types).

A more incremental approach might be to move the author picker and action buttons to the "Metadata tab" within the current design, which would resolve the title height issue.

**Comment by aduth** [comment]
Marking this as closed by #4253, as I'd assumed there to be an existing issue for the mobile redesign. I'm having trouble finding one, though - @folletto , do you know if we've tracked this somewhere?

**Comment by folletto** [comment]
No I don't think it was tracked on GitHub.

**Comment by aduth** [comment]
Tracking redesign at #4266
