### ISSUE TITLE
Gutenboarding: ensure loading screen looks good on iOS

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#42149]
On iOS browser, loading screen looks like this:

<img src="https://user-images.githubusercontent.com/87168/81800181-15c35580-951b-11ea-8f85-7b39d47a6bc2.jpeg" alt="" width="320"/>

The spacing should be equal on both sides.

On my Iphone 11 Pro, running chrome in incognito mode.

**Comment by yansern** [comment]
In the previous sign-up stage, when entering email/password in the signup form, it zoomed the browser viewport. This zoom was carried over to this screen, hence the screenshot since above.

Since the sign-up zoom is fixed here https://github.com/Automattic/wp-calypso/pull/42138, this issue might be fixed as well. Unless we want to programmatically reset zoom on this page or prevent user from zooming this page.
