### ISSUE TITLE
Gutenboarding: do not show plans grid if a plan was manually selected

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42218]
To reproduce:
1. Enter the flow (incognito, no account)
2. Click 'free plan' in the header
3. Pick a paid plan
4. After picking a design see the plans grid again

Expected:
Since I picked a plan I should advance straight to account creation, not see the plans grid again.

cc @johnHackworth

**Comment by simison** [comment]
And the same for paid domain flow:

 1. Enter flow
 2. Pick paid domain; plan gets selected to "premium"
 3. Open plans grid from the header
 4. Either choose to keep the plan or choose another plan
 5. After picking a design see the plans grid again

They shouldn't see the plans grid since they've already opened the grid and compared plans, even if they didn't change the default.

**Comment by razvanpapadopol** [comment]
Update: show the plans step to all users if they didn't picked a plan, not only with paid domain selected
CNMU1UHHB/p1589487235117500-slack-gutenboarding

**Comment by ramonjd** [comment]
Also relevant p1589495542131700-slack-CNMU1UHHB

> Show the plans grid to ALL users (including users who did not interact with domains or choose a plan) BEFORE account creation

> For users who have chosen a plan before account creation, send them directly to the checkout flow, don’t make them pick a plan again

**Comment by ramonjd** [comment]
I'm going to try to look at this today and palm it off when I run out of time :)

**Comment by ramonjd** [comment]
> For users who have chosen a plan before account creation, send them directly to the checkout flow, don’t make them pick a plan again

Just elaborating here. I'm assuming we want to show the plans step to everyone unless they have deliberately selected a plan in the plans modal.

If they selected a paid domain, but have not explicitly selected a plan, then we show them the plans modal.

I also think we should keep showing the plans step if we show it once. Otherwise back and forward navigation would be confusing, especially if the user expects to be able to change their selection.
