### ISSUE TITLE
Plans: in-context promo of "unlimited premium themes" in themes pages

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4229]
Here are the notes from the team hangout.

> - We don’t promote “unlimited premium themes” for the business plan when people are purchasing themes or looking at themes - we’re not promoting premium themes at all!
> - I would display huge promo of premium themes and custom css at the top of the themes page
> - I was thinking about Cover-Flow like promo of most purchased premium themes

We also talked about only showing a plans upgrade banner on a site-specific themes page, since plans are site-specific themselves. And we talked about more aggressive targeting of users who had already purchased a premium theme and were looking at a different premium theme (most likely to benefit from unlimited premium themes).

I'll leave this somewhat generic, as I suspect we can suss out specifics in this issue thread. @folletto would welcome your thoughts/learnings in this area as well.

**Comment by folletto** [comment]
Themes are a bit in a troublesome position until we reach _The One_ milestone (one showcase, retiring all the old codebases – 4.0, 2.0). We can't really change gear to growth there until then.

But, as we discussed briefly, there can be approaches that while limited might be able to give us the data we need here. My advice – until we release The One – would be along these principles:

* Limit any effort to Calypso, knowing that is however a subset of all our usage   
  _(both in quantity and type)_
* Go for modular approaches that don't change the existing structure   
  _(because we are still heavily in flux)_

Brainstorming, in term of modular approaches I can imagine these:

1. Add an extra "fake" theme thumbnail block within the first few items, that is instead a call to action to promote premium
2. Add a call to action on the actual purchase store page, so after the user asked for a Premium theme, to nudge the upgrade
3. Add a call to action every X themes (like a horizontal band). This design wise is cool and seems the best approach to me, but might be tricky given the matrix array done in `flex` (and the fact the row extends from 1 column to N columns). If we manage to do it however would be amazing also for other things (support, jump to different filters, etc).
4. Add a call to action on the toolbar showing up in the theme preview (i.e. see https://marqueedemo.wordpress.com/ – not Calypso, but might be easy enough).

**Comment by drw158** [comment]
@folletto, Aside from codebase difficulties, wouldn't we have to also address the logistics for doing this with Premium users?

Sellers, price normalization, contracts, transition for users who recently bought, etc.

**Comment by folletto** [comment]
Uhm maybe I misunderstood the question. _Unlimited Premium Themes_ is a package we offer(ed?)... and the question seemed related only to _Business Plans_, which already includes it. So... yes? :D

**Comment by drw158** [comment]
Yes, that clears it up. We can target non-Business users and prompt them to upgrade to Business.

**Comment by drw158** [comment]
Two different takes on the "fake" theme thumbnail concept.

I chose to promote the Business plan in these mockups because that feature already exists. The same UI could be used for Premium too. It would be good to test this and see how it performs.

Ignore the illustration for now. That is still in flux.

![group 2](https://cloud.githubusercontent.com/assets/618551/14030011/643b4bfe-f1d3-11e5-975a-3e87b1722d33.png)

**Comment by folletto** [comment]
Both look good. And good thinking on the ability to close them. :)

I'd probably avoid if possible to put them on the first spot, but for the test I'd test it in that position — **but with the firmness to not deploy it there in the end. Just to collect good data.**

**Comment by drw158** [comment]
We have a banner with the promo that seems to be successful, so I'm closing.

![screen shot 2018-01-17 at 12 09 01 pm](https://user-images.githubusercontent.com/618551/35058994-5c83e44a-fb7f-11e7-9c69-a44cd357d2c3.png)
