### ISSUE TITLE
Sign in with Apple (SIWA): Can't connect Apple account to existing WP.com account when 2FA is enabled

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#42359]
Connecting an Apple account to an existing account that already has 2FA enabled currently fails when a user attempts to do this via `/log-in`. The Apple account can be added successfully if you go to `/me/security/social-login` after logging in.

Connecting an Apple account to an existing account that _doesn't_ have 2FA enabled, appears to work correctly.

#### Steps to reproduce

1. With an account that doesn't have an Apple account connected, enable 2FA (the email should match the Apple account you're going to use).
2. Go to `/log-in`
3. Select `Continue with Apple`
4. You should see a notice that an account already exists and to log in to connect your Apple account with the WordPress.com account
5. After entering your password and 2FA, you'll be redirected to `/log-in/social-connect`, however there'll be additional errors in the console, and the [social connect prompt](https://github.com/automattic/wp-calypso/blob/d8abda88ad56af035ed0c6f49da22650ba73635f/client/blocks/login/index.jsx#L401) does not get rendered.

#### What I expected

To be able to add an Apple account to an existing WordPress.com account via `/log-in`.

#### What happened instead

An empty page.

#### Browser / OS version

Chrome 81, MacOS 10.14.6

#### Screenshot / Video

The page looks like this:

![image](https://user-images.githubusercontent.com/14988353/82303181-f38b7500-99fd-11ea-86a9-a886b4acd7b1.png)

It should look like this:

![image](https://user-images.githubusercontent.com/14988353/82303512-63016480-99fe-11ea-9806-45b014fe110c.png)

**Comment by alshakero** [comment]
I did some investigation and it seems this error only occurs when you use Authenticator. If you use WordPress.com app login verification it doesn't happen.

I'll investigate further.

**Comment by alshakero** [comment]
This has been a long journey. I couldn't pin it down but mostly due to development challenges. I realized that I need to point wordpress.com to 127.0.0.1 and add the generated certificate as a trusted one, so I could run the login code locally and to fool Apple login into accepting the redirect (it won't redirect to localhost). Then it turns out I still needed `wordpress.com/wp-login.php` to be served from wpcom API. 

I tried to use Fiddler rules but without much luck. Any ideas how do we debug authentication stories this like this one?
