### ISSUE TITLE
Plans: show storage upgrade promo in storage-heavy themes

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4237]
This is a little different from #4229. The idea is that if there are certain themes that lend themselves to lots of storage, like a photo portfolio, or a theme meant to display videos, we should show a targeted upgrade about the premium plan regarding the expanded storage space. Again, would welcome feedback from @folletto and anyone else on the hyperion team.

**Comment by folletto** [comment]
I'd suggest this in the store purchase screen. 

In the showcase listing doesn't feel to me there's any space to fit that since it's per-theme, until at least we complete the theme sheets, but that's the milestone currently being built. :) 

A better location looks to me also the media gallery, post editor or similar location when the user is _actually_ using that space.
