### ISSUE TITLE
Editor: Saving draft of post with same title as lots of other posts in same site takes long time

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4247]
#### Background

I have a test site where there are about 250 posts with the same title ('Author Post'). When adding a new post in Calypso editor with this same title, each auto-save of a draft takes about 45 seconds.

Adding a new post with a different title (not 'Author Post') takes 2-3 seconds to save each draft.

Whilst this is an unusual situation, this could potentially happen for P2 blogs where the title may be blank, or aside posts etc.

Creating the same post with the same title in the wp-admin editor is much quicker.

#### Steps to reproduce
1. You will need a test site with multiple posts with the same title (eg. e2eflowtesting.wordpress.com)
2. Create a new post with the same title as your multiple posts (eg. Author Post)
3. Wait for autosave

#### What I expected

Autosave takes 2-3 seconds - typical time

#### What happened instead

Autosave takes ~45 seconds

#### Browser / OS version

Chrome OSX 10.11.2

##### Autosave of post with same title

![post with same title](https://cloud.githubusercontent.com/assets/128826/13975595/d4c49302-f102-11e5-8142-40ded2a5dad0.gif)

##### Autosave of post with different title

![post with different title](https://cloud.githubusercontent.com/assets/128826/13975591/cc56be20-f102-11e5-99af-3ac5c407b007.gif)

**Comment by lancewillett** [comment]
Nice find. That delay is kinda crazy... I wonder if it's something tied to trying to create a slug for posts with the exact same title. Which could realistically happen for a P2-themed site where you don't post with titles from the front-end.

**Comment by alisterscott** [comment]
> I wonder if it's something tied to trying to create a slug for posts with the exact same title.

I don't believe so. I tested this as such: initial draft save before slug is shown (~45 seconds), subsequent draft save on edit with slug already shown (another ~45 seconds), changing title of existing draft to something else (~3 seconds).

**Comment by dmsnell** [comment]
This is more of a hunch than an investigation, but I suspect [this check](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L3795) in core code, which is looping on on an SQL request fetching a single row. Fetching a single row is probably good for a lot of small cases, but I think when we have a bunch of posts with the same title, the slugs are similar, and thus we spool up this loop. The bad thing about limiting our SQL results at 1 row is that we don't get any caching benefit.

If this _does_ turn out to be the problem, I bet we could make a significant improvement by prefetching a reasonable number of posts. Since the [SQL query](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L3757) is only requesting the post name, we could pull in a bunch of posts on a single request and be sane. I propose something like 100 posts at a time and then looping over those results from within PHP, continuing to fetch in batches until all have been searched.

Sorry I don't have more time to test this theory out. Hope it helps!

**Comment by designsimply** [comment]
> I have a test site where there are about 250 posts with the same title ('Author Post').

The 250 posts with the same title are published posts and not drafts themselves, correct?

**Comment by designsimply** [comment]
I tested with 25 (a relatively small number of, probably too small number of) posts with the same title, and saving worked at a consistent speed throughout, and the longest save time was ~9.2s and the average was ~4.25s. See [1m45s](https://cloudup.com/cUTMxWvqApZ)

**Comment by designsimply** [comment]
> this could potentially happen for P2 blogs where the title may be blank, or aside posts etc
I believe P2 creates a unique title based on content, including asides posts, so I don't think P2 would be affected by this issue.

Because 250+ posts with the same exact title is likely extremely rare, I would recommend closing this for now and reopening if the issue comes up in another use case or help request from a user.

**Comment by lancewillett** [comment]
Agreed on closing for now — we have a nice record here of what could happen in this scenario.
