### ISSUE TITLE
Button (singular) block can't be centered

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#42499]
Unlike the button**s** (plural) block, the button block can't be centered. It can be aligned to the right, but will remain on the left if you choose to center it. It only happens on WordPress.com, whether the site is Simple or Atomic. It doesn't happen on .org as far as I could see.

#### Steps to reproduce

Although it can't be added by looking it up in the list of available blocks, the button block can be added manually with the code editor or by choosing a layout,
1. Create a new page and choose a layout, like one of the _About_ layouts, which comes with the single button block,
2. Center the button using the alignment option,
3. Preview/publish and notice it's still aligned to the left.

#### What I expected

The button to be centered.

#### What happened instead

The button remains on the left.

#### Screenshot / Video

![Screen Capture on 2020-05-20 at 21-39-04](https://user-images.githubusercontent.com/16645645/82489775-784fbf00-9ae2-11ea-9792-36bf91d456f1.gif)

#### Workaround

Add the following CSS to My Site > Design > Customize > Additional CSS:

```
.wp-block-button.btn-centered {
	display: block;
	text-align: center;
}
```

Add the following class to the Advanced module of the button: `btn-centered`

**Comment by xpurichan** [comment]
Getting lots of reports about this in HC and ZD which we can see in Slack. I got another report in 21276293-hc.

Another solution is to convert the "button" block to the new "buttons" block, center-align works there.

**Comment by khristiansnyder** [comment]
Had this in 12287038-hc

Used this CSS to center user's blocks as they wanted all blocks on their site centered: 
.wp-block-button {
    text-align: center;
}

**Comment by davoraltman** [comment]
Another case in 21821402-hc

**Comment by davipontesblog** [comment]
This block (Button) has been deprecated in favor of the new block "Buttons", for a few months now, but some sites still have the old block and it's causing this issue. @lsl mentioned this is being tracked here in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/21509

Solution: Convert the block to "Buttons", and alignment works.

**Comment by zdenys** [comment]
Just wanted to link the conversation where I first reported the above issue too p1591724116387100-slack-CRNF6A9DX

**Comment by LauraSWP** [comment]
I am having the same issue with 2 users. 
![image](https://user-images.githubusercontent.com/63611065/85278334-1d184000-b485-11ea-9f40-f60ab4ba79f2.png)

And this one is using the Buttons block, which should work but it doesn't:
![button](https://user-images.githubusercontent.com/63611065/85278532-5fda1800-b485-11ea-9ec7-19cfdf0536b6.gif)

**Comment by zdenys** [comment]
@LauraSWP, for the second case:
>And this one is using the Buttons block, which should work but it doesn't:

Make sure to do this:

>To change a button’s alignment, select the entire Buttons block first and then align left, center, or right from the toolbar.

as mentioned and illustrated in https://wordpress.com/support/wordpress-editor/blocks/buttons-block/#aligning-buttons

**Comment by lsl** [comment]
> And this one is using the Buttons block, which should work but it doesn't:

This looks like it has nested buttons blocks, iirc the inner buttons should not have an alignment option.

Are you able to get a hold of the raw gutenberg html/markup from the code editor?

**Comment by TeniCola** [comment]
Hi all! My team encountered this same issue with centering the Button block during our team's virtual meetup, where we were using Gutenberg for our DIFM project. Context in team master thread: p6knfs-29V-p2

The CSS solution is good to know in the future, as well as converting the Button block to Button**s** instead, so we'll be mindful of this moving forward. Just adding a note here that the issue came up for some new sites we had created during our team project.

**Comment by lsl** [comment]
> Just adding a note here that the issue came up for some new sites we had created during our team project.

@ramonjd maybe headstart content needs updating?

**Comment by ramonjd** [comment]
> Just adding a note here that the issue came up for some new sites we had created during our team project.

Thanks for the ping. 

@TeniCola Were those sites created via wordpress.com/start or wordpress.com/new?

If wordpress.com/new, which "design" did you select? 

If it's something to do with the initial code we use to create pages in onboarding it's definitely something we can look into further. 👍

**Comment by liviopv** [comment]
@ramonjd I made some testings and found out that the old version of the Button Block is present on some themes starter content, like Exford. While it still keeps the alignment while Exform is active, the alignment breaks as soon as the user switches themes.

Reported the issue in Exford here: https://github.com/Automattic/themes/issues/2888

**Comment by arunsathiya** [comment]
I see that there are two things here.

## Old Button block

One way to find this block is by activating Exford and editing the demo homepage that it generates. It shows the old Button block throughout that page. It's not clear if we have plans to change that to the newer Buttons block, and if we would do that for all affected sites. [I asked about it here](https://github.com/Automattic/themes/issues/2888#issuecomment-1132309495).

In the meantime, I see that the old Button block's alignment works fine now. This is how things look when left-aligned:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/18581859/169382597-853fbc4f-1ec7-4320-b4b8-55160cac7c62.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18581859/169382635-f4657e60-961c-4e26-89c4-109e2f251b7c.png">

And when centered:

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/18581859/169382688-96fa3669-a24b-4f92-9067-9cc50dd75c49.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18581859/169382721-d071910c-8169-4997-802e-75040a56fd0a.png">

## Newer Buttons block

I can see that the center alignment option is available only on the inner Button block. The parent block does not. The inner block's setting works fine:

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/18581859/169382247-7a8e1c75-1367-4851-a2e5-2cef493529e5.png">

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/18581859/169382312-07d725a5-3dd1-417a-a89e-2b6c51879466.png">

## Conclusion

I'll close this report for now, as it has been nearly two years and the Gutenberg and themes experience has evolved a lot since. The newer Buttons block should be the only available option these days.

If affected customers reach out, we should help them move to the newer Buttons block.
