### ISSUE TITLE
Gutenboarding: Checkout in Launch Flow Launches site — even when not completed

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42545]
We found this in two usability tests today. It's possible to enter the launch flow from the Editor in Gutenboarding, go to checkout, change your mind, go back to the Editor and have your site launched — without intending to do that.

Here's a gif that reproduces that as a new user.

![2020-05-21 16 47 10](https://user-images.githubusercontent.com/545779/82609925-198e5200-9b83-11ea-8342-22fd661ee1fc.gif)

**Comment by ianstewart** [comment]
The flow has changed significantly but the same issue remains. If backout of the checkout screen in the launch flow I will not have the opportunity to go through the flow again.

**Comment by razvanpapadopol** [comment]
This should be fixed in D57607-code by rolling out Focused Launch (pbAok1-1IU-p2) for Gutenboarding sites. 

A dismissable checkout modal should be displayed when trying to launch from editor with paid plan or custom domain. There are just 2 unavoidable exceptions: having an eCommerce plan selected and launching from wp-admin. 

Check Focused Launch instructions on [how to test the main user flows](https://github.com/Automattic/wp-calypso/issues/46943#issuecomment-779895421) for more details.

**Comment by razvanpapadopol** [comment]
Fixed in D57607-code. The remaining exceptions (eCommerce and wp-admin) would be fixed by implementing #50122
