### ISSUE TITLE
Checkbox style is not working on List block for atomic sites

### ISSUE THREAD

**Issue by tarunvijwani** [Automattic/wp-calypso#42565]
Checkbox style is not working on List block for atomic sites

#### Steps to reproduce

1. Go to the post/page editor of any atomic site
2. Add a new list block and select the checkbox style
3. Add the list content and publish the page/post.

#### What I expected
The list should be displayed in the checkbox style

#### What happened instead

The list is getting displayed in the bullet style

#### Screenshot / Video
Screen recording: https://d.pr/v/eRpRTW

I tried switching the themes. However, it was displaying the bullets for every theme.

zen-2987909

**Comment by xpurichan** [comment]
It appears this issue has been resolved. I tested this on an Atomic website and it properly displayed the checkbox list style with these themes:

* Eris
* Twenty Twenty
* Karuna
* Illustratr

If you do experience this issue please note the theme and consider reporting to the [Themes repository](https://github.com/Automattic/themes) if the issue seems isolated then.
