### ISSUE TITLE
Duplicate inserter on dotcom-fse 8.2.0-alpha.1

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#42611]
Affects fullstite editing sites with the gutenberg edge sticker applied

![Screen Shot 2020-05-22 at 6 49 39 PM](https://user-images.githubusercontent.com/22446385/82778723-895b5000-9e95-11ea-8f9f-a3227ec9711f.png)

### To reprouce
* Open or create a full site editing site
* Apply the gutenberg edge sticker to enable GB8.2.0-alpha.1
* Open the editor for a page or post.
* You will see two Add buttons instead of one

### context 
p1590190488050600-slack-create-gardeners

**Comment by ockham** [comment]
As @sirreal stated in that Slack convo, this is probably due to a CSS class that changed.

FSE inserter source, for reference: https://github.com/Automattic/wp-calypso/blob/b6944b9c4f84459bc56463e0f8ebb01b2f9727e1/apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/block-inserter/index.js
