### ISSUE TITLE
Editor: Mobile refactor / redesign

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#4266]
We should seek to implement a refactor of the mobile editor layout, as reflected by the concept shown below:

![Mobile refactor](https://cloud.githubusercontent.com/assets/1779930/13996428/15935b56-f104-11e5-94c3-c936393a1dd8.png)

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Closing because the mobile editor was redesigned in #5987 and shipped on on Dec 21, 2016, and there have been additional changes since then beyond that.

Recent screenshots from iPhone 6S on iOS 11.2.1 for reference: 

<img alt="img_1758" src="https://user-images.githubusercontent.com/1119271/34506332-0debb93a-efe9-11e7-9f26-2d184d58f51a.PNG" width="200" /> <img alt="img_1759" src="https://user-images.githubusercontent.com/1119271/34506333-0e0b99bc-efe9-11e7-97cd-74d0fa4f8f65.PNG" width="200" /> <img alt="img_1760" src="https://user-images.githubusercontent.com/1119271/34506334-0e232640-efe9-11e7-9605-81766f4c8d08.PNG" width="200" />
