### ISSUE TITLE
Gutenboarding: use of theme demo site annotations creates "random" post in design selection screen

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42672]
At some point we may no longer use theme demo site annotations for Gutenboarding but in the meantime, while we do …

1. Fire up Gutenboarding at wp.com/new
2. Select the Cassel design and proceed to font pairing screen
3. Review the posts in the preview of the Cassel design on the font pairing screen

Here's a screenshot of what you'll see …

![image](https://user-images.githubusercontent.com/545779/82948323-3225b000-9f67-11ea-9e8a-ab89579e8dd3.png)

The top half of the design is from the template. The bottom, the blog posts, are blog posts from the Mayland theme demo site.

https://maylanddemo.wordpress.com/

This can be seen with the Edison design as well.

![image](https://user-images.githubusercontent.com/545779/82948449-6ac58980-9f67-11ea-8f84-5f597f935169.png)

**Comment by ianstewart** [comment]
Related issue: #42671

**Comment by ramonjd** [comment]
Yeah, this is because [Cassel uses the Mayland theme](https://github.com/Automattic/wp-calypso/blob/b6944b9/client/landing/gutenboarding/available-designs.ts#L31) and is therefore headstarted with it.

I suppose we need to brainstorm how we're going to create/customize posts independently of headstart, or modify/add headstart annotations to do this.

We can extend headstart to cater for Gutenboarding. I don't think headstart is a lost cause yet. Just keeping an open mind and trying to stop my 🧠 from falling out.

**Comment by andrewserong** [comment]
Resolved in D45183-code.
