### ISSUE TITLE
Gutenboarding: use of theme demo site annotations creates "random" images in media library

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42671]
At some point we may no longer use theme demo site annotations for Gutenboarding but in the meantime, while we do …

1. Create a new site with the Edison design in Gutenboarding.
2. Visit the media library on your new site.
3. See a collection of images and icons that are not found in any of the blocks for your new site.

This is what you'll see.

![image](https://user-images.githubusercontent.com/545779/82948042-aad83c80-9f66-11ea-9e2f-4781bbd0fad3.png)

These are images from the Stratford theme demo site. 

https://stratforddemo.wordpress.com/

## What I expected

One of two states …

- An empty media library
- A media library with images from the design selected in Gutenboarding

**Comment by ianstewart** [comment]
Related issue: #42672

**Comment by ramonjd** [comment]
I guess we could do a post-site creation wipe of the media library. Particularly since most images, at least on the homepage templates we're injecting have absolute image URLs.

The posts we create, if they have images, will come from the demo however. 

When (and if) we clear the media library, we might like to only delete attachments whose parent post ids do not match the homepage post id. If that's at all possible. Sounds legit.

**Comment by ianstewart** [comment]
This is popping up regularly in **every** Usability Testing session of Gutenboarding. The first or second action for every participant in the Editor has been to replace images. Each user sees a set of random images when they (seemingly, from what they seem to say) expect to find samples images that should work well with their design they've selected.

**Comment by ramonjd** [comment]
>  The first or second action for every participant in the Editor has been to replace images. 

Thanks @ianstewart 

I'll see if @Automattic/ganon can come up with a provisional solution.

This, as folks know, is just headstart doing its job: adding the required images for the theme's annotation. 

I wonder if this could be solved by creating headstart annotation from the starter sites themselves instead of using the themes' existing config. It might solve a few problems at once. See: https://github.com/Automattic/wp-calypso/issues/43363

**Comment by ianstewart** [comment]
Ah — this is what I was suggesting the other day. With Headstart we _can_ create an annotation of any arbitrary site. And we can also use Headstart to push all that content and those settings to any other WP.com site.

**Comment by ramonjd** [comment]
Been testing over here: https://github.com/Automattic/wp-calypso/issues/43363#issuecomment-646443895

Result of D45183-code

<img width="1006" alt="Screen Shot 2020-06-19 at 3 32 57 pm" src="https://user-images.githubusercontent.com/6458278/85099948-2f566c00-b242-11ea-93f5-a0dcd29d9e46.png">

**Comment by ianstewart** [comment]
That's much more inline with what I think would be expected! Looks like we have at least one stray image in the source site but that's easily fixed.

**Comment by ramonjd** [comment]
Will mostly be addressed by Automattic/view-design#54 and regeneration of annotations over at D45183-code

**Comment by ramonjd** [comment]
Ready for testing D45183-code

**Comment by ramonjd** [comment]
Deployed in D45183-code
