### ISSUE TITLE
Earn: adding a recurring payment plan sometimes fails

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42818]
We've gotten a report that some folks are having trouble adding a new payment plan at https://wordpress.com/earn/payments-plans/siteSlug, with the following JS error thrown "Cannot read property 'id' of undefined". 

![Screen Shot 2020-05-29 at 23 04 45](https://user-images.githubusercontent.com/1270189/83301448-85d60a80-a1ae-11ea-81ef-92c163564364.png)

This is likely specific to certain accounts so please debug and see additional details in:
p1590773186070600-slack-earn

Please close out this issue once this specific occurrence has been investigated.

**Comment by kwight** [comment]
@vajrasar This error is consistent with no working Stripe connection:

<img width="816" alt="Screen Shot 2020-05-29 at 2 31 56 PM" src="https://user-images.githubusercontent.com/349751/83307354-61cbf680-a1b9-11ea-88d8-d2b52694b2e2.png">

You mentioned the user tried to re-connect to Stripe many times; so do we know they don't have a proper working Stripe connection?

**Comment by vajrasar** [comment]
@kwight The connection seems to be established, at least from the Calypso interface.

![Screenshot](https://razzmtazz.blog/wp-content/uploads/2020/05/Screen-Shot-2020-05-30-at-13.08.42.png)

The multiple tries to re-connect with Stripe was more about checking if it is a connection issue. When the Stripe support was asked about this issue, they pointed to seek support from our side on the matter.

**Comment by gwwar** [comment]
@artpi do you have any experience with this type of error?

**Comment by artpi** [comment]
This is consistent with behavior when the user that has set up Stripe account is not the one setting up the product.
Solving this problem is  on our roadmap: https://github.com/Automattic/wp-calypso/issues/43065

We theoretically could manually reassign the Stripe connection of that user OR make that reconnecting Stripe reassigns user id (it does not - it attempts to find previous data and use previous entry )

I reassigned the connection to the user that has contacted us, because he is the plan owner. Please confirm.
more detail in:
p1591626184382300-slack-CDA5HLRD2?thread_ts=1590773186.070600&cid=CDA5HLRD2
