### ISSUE TITLE
Patterns: Add keywords to improve search

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42906]
It would be great if we could add keywords to Patterns to improve search. Here's an example.

A search for "food" will reveal a food menu …

![image](https://user-images.githubusercontent.com/545779/83570025-fc467580-a4ea-11ea-8064-a08b130b8c95.png)

but not other patterns that might be helpful for someone looking for things related to food …

![image](https://user-images.githubusercontent.com/545779/83570216-47608880-a4eb-11ea-8e8b-ffb20c70b6f4.png)

Neither of the above patterns would be revealed for someone looking for restaurant-related patterns.

![image](https://user-images.githubusercontent.com/545779/83570304-68c17480-a4eb-11ea-87c5-01b6684698e9.png)

**Comment by ramonjd** [comment]
We haven't lifted a proverbial finger in terms of development, but this idea ties in nicely with discussions we're having about adding metadata to pattern definition files. Don't ask me what those are yet. :)

This also serves to remind us that any metadata, such as search term keywords, must be translatable.

**Comment by ramonjd** [comment]
I know you've told us before @ianstewart , but just confirming that the patterns source site is https://dotcompatterns.wordpress.com/ ?

🙇‍♂️

**Comment by ianstewart** [comment]
Totes McGoats. All the categories/tags should be up to date there (and easily changed if we've made a mistake). It's a known that some are empty. Some of the empty tags may or may not be filled. Figurin' it out. :)

**Comment by ramonjd** [comment]
Update: The patterns lib stores the categories of the posts whose content it parses.

We might look at ways to exploit this feature for block patterns integration, building on top of D48036-code

**Comment by ramonjd** [comment]
I think we almost have everything we need to enable this. See: D49335-code

**Comment by ramonjd** [comment]
@andrewserong 

Can I close D49335-code (a8c-only registration of patterns)? 

Has this approach been superseded by your API endpoint in D49914-code?

If so, let me know and we can delete the file entirely that D49335-code modifies.

Also I think we can close this issue since we're adding category and tag filters in D49914-code.

**Comment by andrewserong** [comment]
Thanks for the ping @ramonjd! Yes, we can close D49335 now since the work to consume the new endpoint is covered in: https://github.com/Automattic/wp-calypso/pull/45926, and that will supersede it.

I think it’d be worth keeping this issue (and that backend file) around until #45926 is ready to land so that we make sure this behaviour is covered. I’m happy to update / close this issue when it comes time!

**Comment by ramonjd** [comment]
> I think it’d be worth keeping this issue (and that backend file) around until #45926 is ready to land so that we make sure this behaviour is covered. I’m happy to update / close this issue when it comes time!

Thanks!! 🙇
