### ISSUE TITLE
Donation Plans: Calypso Management Exploration

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#43033]
Let's explore how we'll manage donation plans. While the backing subscriptions will be the same as customizable payments, we may want a different grouping and UI to help manage 
options.

We do this so that the 12 auto-added donation subscriptions don’t show up as options in the recurring payments and premium content blocks. This helps us avoid a couple of edge case scenarios.

cc @danhauk feel free to modify this

<img width="1526" alt="Screen Shot 2020-06-05 at 11 22 09 AM" src="https://user-images.githubusercontent.com/1270189/83910222-05b82380-a71f-11ea-859c-e0d2a5f2042b.png">

**Comment by danhauk** [comment]
In order to reduce the scope I didn't spend a lot of time trying to redesign the main payments screen. We can work on that iteratively to make this page more engaging and useful overall.  worked within the constraints we already have here with layout.

**Main Payments screen**
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/448298/84199001-6ffbfb80-aa72-11ea-923a-87ac512855ca.png">

* Individual payment plans and donation tiers are separate management settings to set and reinforce the mental model that these are different things.
* Each type of plan has a short explanation of what these are and how they're different. Again, helping to set expectations of usage for customers.
* Icons added to provide some affordance and quick scanability. These options are aligned with the newish domain management settings in production.

**Donation tiers screen**
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/448298/84199862-dafa0200-aa73-11ea-83a6-d652a5cf5632.png">

* A header card sets the context for this page. This is helpful for people coming directly here from the editor after inserting the block. Illustration freshens up the aesthetic (I might tweak a bit here, it feels very Valentine's Day).
* The list is aligned with content lists everywhere else (posts, pages, etc.)
* Each list item has the amount and tier name, aligning with the current payment plans list.
* Tabs help separate out the donation tier renewal periods to 1) avoid a lot of repetition in the default tier names and 2) avoid a long list of 12 tier amounts that could be overwhelming at first glance.

**Individual payments screen**
I also updated the current recurring payments screen to bring it in alignment with the donation tiers screen above.

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/448298/84200089-28766f00-aa74-11ea-8c12-1cf99be684f4.png">

* Header card again being used to set context of what these payment plans should be used for.
* Added the renewal period to the list item to provide more value to the user when looking at this list.

---

Open to any feedback or questions you might have. Does the flow here make sense to separate the types of plans? Does the header card provide enough value to be necessary? Thoughts on the tabbed organization of the donation tiers? cc @Automattic/dotcom-manage-design

**Comment by lcollette** [comment]
Thanks, @danhauk! Left feedback in your figma but I'll summarize here as well. 

- Plan management and Stripe settings feel like different categories of functionality. Can they be grouped separately? 
- The Donation and Payment plan pages are visually and functionally different. One uses tabs while the other uses pills to communicate the renewal period. One allows adding a plan while the other doesn't. Is that intended? For consistency, can we align and standardize on one direction?
- What is the purpose of the header card? I count 3 types of headers on the Donation and Payment plan pages which seems like overkill. :)

**Comment by danhauk** [comment]
Updates! I think we can settle on this direction for v1 unless there is any major blocking feedback.

**Full flow blueprint**
<img width="7134" alt="donations calypso management" src="https://user-images.githubusercontent.com/448298/84527251-fa7b6f80-acab-11ea-9b0e-5134fb75671d.png">

**Payments screen**
<img width="1440" alt="Payments" src="https://user-images.githubusercontent.com/448298/84526669-c902a400-acab-11ea-9ab8-54662d144b91.png">
* Plan management and Stripe are grouped separately to address the feedback that they feel like different categories of functionality.

**Donation tiers**
<img width="1440" alt="Donation tiers" src="https://user-images.githubusercontent.com/448298/84527657-45958280-acac-11ea-9e6b-18fffb0930d5.png">
* The headers are consolidated a bit until we can think more on updating how headers work holistically across Calypso. I like the card with illustration, but we can still set context with the subheader while reducing the number of stacked cards. There's still some duplication between the header and the section header/back button.
* Donation tiers are grouped by type to reveal all the tiers and amounts without an overwhelming giant list.
* While this differs slightly from the individual Payment Plans where each plan is a separate list item, this still aligns functionality and visuals.

**Editing donation tiers**
<img width="1440" alt="edit Donation tiers" src="https://user-images.githubusercontent.com/448298/84527996-d704f480-acac-11ea-89be-25a5ad1f39a8.png">
* Because the tiers are grouped by type, they are edited by type as well.
* Anything not relevant to donations has been removed from the edit modal.
* Plan names that show up in emails, notices, etc. (e.g. "One-time $30 Donation") are automatically created and updated. Plan names aren't helpful in the way they are for individual plans and there's not as much of a use case to customize them.

**Empty states - Connect Stripe**
<img width="1440" alt="Connect stripe" src="https://user-images.githubusercontent.com/448298/84528297-67dbd000-acad-11ea-9546-a037b536c6a9.png">
* If Stripe is not yet connected, we prompt the user to connect Stripe to get started.
* This style can be applied to the Payment Plans screen as well (vs. the current text on gray)

**After Stripe connected**
<img width="1440" alt="Donation tiers - connected" src="https://user-images.githubusercontent.com/448298/84528395-9eb1e600-acad-11ea-8031-e6849f719670.png">
* After Stripe is authorized and connected, the donation tiers are automatically generated with a success message.

**Empty State - Stripe already connected**
<img width="1440" alt="generate donation tiers" src="https://user-images.githubusercontent.com/448298/84528453-b5f0d380-acad-11ea-9dbc-0fedc71523b9.png">
* If Stripe is already connected but the user hasn't inserted the Donations Block yet, we provide a way to generate the default tiers from Calypso rather than only from the block.

**Comment by gwwar** [comment]
I think this is a great starting point @danhauk! I'll close out this issue and will create separate tasks. We can continue chatting through design options on the smaller issues.
