### ISSUE TITLE
Premium Content Block: Investigate subscribe/log in buttons on mobile

### ISSUE THREAD

**Issue by n3f** [Automattic/wp-calypso#43041]
Reported here: p1591393352358100-slack-CDA5HLRD2 (with screenshots).  It appears that the buttons in the Premium Content Block might get into a state where they aren't being properly responsive.  Need to investigate and verify.  Could be solved by #42715.

![image](https://user-images.githubusercontent.com/6354169/83926368-83d7f280-a73e-11ea-890a-0ee0aece9285.png)

I was able to replicate similar behavior in chrome by enabling devices and then switching back and forth from the Pixel2 several times.

**Comment by gwwar** [comment]
This one is easily reproducible. Using the device toolbar in Chrome @n3f a hard refresh of the page is required (otherwise you may see rendering glitches).

<img width="954" alt="Screen Shot 2020-06-05 at 3 12 51 PM" src="https://user-images.githubusercontent.com/1270189/83926576-17a9be80-a73f-11ea-9c53-d7b61d2bb918.png">

**Comment by gwwar** [comment]
There's a min-width of 200px. 
<img width="280" alt="Screen Shot 2020-06-05 at 3 14 51 PM" src="https://user-images.githubusercontent.com/1270189/83926650-53448880-a73f-11ea-96c4-acc015c691b2.png">
