### ISSUE TITLE
Domains: use site title, not autogenerated subdomain for suggestions

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#43118]
I just created a test site (via gutenboarding in case relevant), launched it, landed on My Home, then clicked the domain nudge in the sidebar. 

I saw this:

![image](https://user-images.githubusercontent.com/437258/84189526-6323db80-aa63-11ea-8b6d-b8aa59a59320.png)

What I expected: to see a relevant domain name based on my site title (dog dog goose). My site title was the input that generated the subdomain, so I expected that to again be the input recommending a better domain. In gutenboarding and I believe in the launch flow I saw better domain suggestions than this one. 
What I saw instead: my autogenerated subdomain was submitted to the domain search.

**Comment by klimeryk** [comment]
Makes sense - though, I'd add a condition to check if the site title is not empty, which is a valid state. I'd also add that in most cases, the WPCOM subdomain will be much closer to the site title, but in this case that subdomain was already taken, so a random number was added.

There's one more consideration here - in Gutenboarding, the user might end up skipping the domains step (because they did not see it, etc.), so they might end up with a WPCOM subdomain they don't recognize or would not have chosen otherwise. As a result, we can see more people with these subdomains with random numbers at the end. We could try to improve the UX here (if the site title is empty) by stripping any long (I'd have to check if the length of the number is always the same) numbers at the end of the site slug. Then the query would become `dogdoggoose`, something very close to what you'd expect - and the results would definitely be much more attractive.

**Comment by klimeryk** [comment]
No, AFAIK the site slug has always been used to fetch default search suggestions in Domain Management -> Add. The only relevant recent change was to make that fact more explicit by populating the search field with the site slug: https://github.com/Automattic/wp-calypso/pull/39664

**Comment by rickybanister** [comment]
I think this could be a high-impact and cheap fix. Seeing a domain that matches my input is much more compelling than something with random numbers.

**Comment by klimeryk** [comment]
Yup, agreed. I've created https://github.com/Automattic/wp-calypso/pull/43449 to address it 👍
