### ISSUE TITLE
Editor: Saved Changes in Alignment for Video Blocks are Reverted

### ISSUE THREAD

**Issue by robertocyrino** [Automattic/wp-calypso#43252]
#### Steps to reproduce

1. Start with a site with PRE sub or superior
2. Create a new post or page
3. Add a title
4. Add a **Video block**, upload or add a video
5. Add a fair amount of text (tested with **around 500 characters**)
6. Change the Video block alignment to left or right
7. Click Save Draft
8. Click Preview
9. Confirm the changes
10. Leave the Editor
11. Open the page created
12. Verify that the alignment changes were reverted 

#### What I expected
Alignment changes should be kept after leaving the Editor.

#### What happened instead
The changes made to the alignment were lost after leaving the Editor.

#### Browser / OS version
Firefox 77.0 (64-bit)

#### Screenshot / Video
https://cloudup.com/cpATs3NNQPg

#### Context / Source
HappyChat: 21854479-hc
Triage at #gutenberg-on-dotcom: p1591984473027900-slack-CBTN58FTJ
Follow-up ticket: 3057943-zen

#user-report

**Comment by yansern** [comment]
Looking at the console, there is a block validation error once the page is loaded up again for editing. The difference is the missing `alignleft` classname.

![image](https://user-images.githubusercontent.com/1287077/84561795-b3df5100-ad4f-11ea-9ea0-8f3127ca8f40.png)

Looking at `serializeBlock()`, when the block is serialized, the `align: left` block attribute was missing.

![image](https://user-images.githubusercontent.com/1287077/84561815-dec9a500-ad4f-11ea-83e3-29bcf883db38.png)

Strange, in the `core/video` block's metadata in [packages/block-library/src/video/block.json](https://github.com/wordpress/gutenberg/blob/v8.2.1/packages/block-library/src/video/block.json#L64-L67), align support is set to true.

![image](https://user-images.githubusercontent.com/1287077/84561847-0fa9da00-ad50-11ea-9909-49edb2b619b7.png)

Looking inside `addAttribute()` inside the align hook [packages/block-editor/src/hooks/align.js](https://github.com/wordpress/gutenberg/blob/v8.2.1/packages/block-editor/src/hooks/align.js#L91-L99) shows that the `align: { type: string }` is added to the `core/video` attribute schema.

![image](https://user-images.githubusercontent.com/1287077/84561894-61eafb00-ad50-11ea-9476-3fe735f58571.png)

However, when the block is parsed, the attribute schema that is used against parsing the attributes did not include the `align` attribute, which could cause the `align` attribute to be discarded.

![image](https://user-images.githubusercontent.com/1287077/84561979-14bb5900-ad51-11ea-9dc3-cb055a200538.png)

So let's take a look at this from another angle by seeing what happens when the blockType is being registered inside `registerBlockType()` in [packages/blocks/src/api/registration.js](https://github.com/wordpress/gutenberg/blob/v8.2.1/packages/blocks/src/api/registration.js#L168-L191)

It seems that while the align hook adds the `align: { type: string }` property to the attribute schema, there is another hook in the process of deprecating old block settings that is yanking out the align property.

![image](https://user-images.githubusercontent.com/1287077/84561991-33215480-ad51-11ea-9a6d-b1164fe67873.png)

So let's see what are the hooks that are registered to `blocks.registerBlockType`, setting a conditional breakpoint on [packages/hooks/src/createRunHook.js](https://github.com/wordpress/gutenberg/blob/v8.2.1/packages/hooks/src/createRunHook.js#L31) where `hookName=='blocks.registerBlockType'` shows us there are 16 hooks, but which one could it be?

![image](https://user-images.githubusercontent.com/1287077/84562149-88aa3100-ad52-11ea-8053-294dcee53347.png)

Investigating what each handler does to the attribute schema one-by-one shows that after the `jetpack/videopress` hook was run, the `align: left` attribute was removed, and the `deprecated` object was added.

![image](https://user-images.githubusercontent.com/1287077/84562267-7e3c6700-ad53-11ea-903e-b15c246ac5fd.png)

![image](https://user-images.githubusercontent.com/1287077/84562270-82688480-ad53-11ea-8be0-e20b48dbe4b6.png)

Inside [jetpack/extensions/blocks/videopress/editor.js](https://github.com/automattic/jetpack/blob/master/extensions/blocks/videopress/editor.js#L199), this hook is registered to the function `addVideoPressSupport()`.

Inside `addVideoPressSupport()`, it appears to return a completely new set of attribute schema, discarding the `align` schema that was previously added by the align hook.

![image](https://user-images.githubusercontent.com/1287077/84562366-4e419380-ad54-11ea-9dd1-83b48c525716.png)

So the file https://github.com/automattic/jetpack/blob/master/extensions/blocks/videopress/editor.js needs to be fixed by inheriting attribute schema that was decorated by other hooks instead of recreating a new set of attribute schema.

**Comment by yansern** [comment]
PR for this issue here: https://github.com/Automattic/jetpack/pull/16627

**Comment by ockham** [comment]
Should be fixed by https://github.com/Automattic/jetpack/pull/16651 and D47361-code.
