### ISSUE TITLE
Earn: Donations emails exploration

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#43254]
With the new donation block, what email copy changes/brand new emails will we need to make?

**Comment by mmtr** [comment]
As a recap, these are the three emails we currently send when someone subscribes to a plan. In all of them, "_Earn_" is the name of my test site and "_Red Cross donation campaign_" the name of the subscription I used in my tests.

**New subscription (sent to subscriber)**
<img width="500" alt="Screen Shot 2020-06-25 at 14 27 35" src="https://user-images.githubusercontent.com/1233880/85720557-d62e8280-b6f0-11ea-8f13-25c74c412af7.png">

**New subscription (sent to site owner)**
<img width="500" alt="Screen Shot 2020-06-25 at 14 28 25" src="https://user-images.githubusercontent.com/1233880/85720596-df1f5400-b6f0-11ea-866c-dae2f610e886.png">

**Receipt (sent to subscriber)**
<img width="500" alt="Screen Shot 2020-06-25 at 14 29 32" src="https://user-images.githubusercontent.com/1233880/85720673-f2322400-b6f0-11ea-89a0-eec211a80ecd.png">

We can reuse them and slightly change the copy when a user subscribes to a donation-type plan or we can even send a completely different email template with a more tailored design.

Tagging @sixhours @danhauk @anneforbush @donalirl @lauac for ideas.

Let's remember that for v1, the name of a donation-type plan won't be visible for both site owners and subscribers (they are created with a internal default name that cannot be changed) so it might be good to completely hide the plan name from the email content and replace it with a more generic term (e.g. "_Thank you for your donation!_").

**Comment by danhauk** [comment]
The new subscription email is in progress for a redesign. Here's what @sixhours started implementing to bring it in alignment with the new design for the subscriber-facing email:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/448298/85788640-4c37e700-b6fb-11ea-83db-06e09c41a3c4.png">

Given that, I think we could reuse these templates and slightly change copy and illustrations for the v1. I did some quick mockups to see how these could scale to donations with minimal changes.

**Subscriber-facing email (recurring donation)**

This one would need a different illustration to represent "donation" rather than "subscription".

<img width="623" alt="image" src="https://user-images.githubusercontent.com/448298/85789574-dcc2f700-b6fc-11ea-9cb5-e05d6cf8c9e1.png">

**Subscriber-facing email (one-time donation)**
If it's a one-time donation we can remove all the stuff relevant only to recurring donations. Alternatively, we don't send this email in favor of only sending the receipt.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/448298/85789509-b7ce8400-b6fc-11ea-8ef7-f2777bead39c.png">

**Merchant-facing email**

<img width="623" alt="image" src="https://user-images.githubusercontent.com/448298/85789626-f6643e80-b6fc-11ea-973a-d6892a11394e.png">

**Comment by mmtr** [comment]
Thanks @danhauk! I started adapting the current "first purchase/new account" email template to donation-type plans in D45640-code based on your mockup above. 

Feel free to update the diff if you come up with an illustration to better represent donations.

**Comment by anneforbush** [comment]
These are looking great everyone! Super small suggestion that y'all can feel free to take or leave:

> Subscriber-facing email (recurring donation)
For this one, would it make sense to have the email say "Next Donation Date" vs. "Renewal Date"? I was thinking the term "renewal" could get confusing in this context for folks making a donation (as everything else in the email focuses on a donation vs. a payment, plan, subscription, etc.

cc @danhauk @mmtr

**Comment by mmtr** [comment]
I think that makes sense @anneforbush! I've updated D45640-code with that. Since donations are not enabled yet in production, we can always change it to anything else without affecting users in case there is additional feedback.

**Comment by danhauk** [comment]
Agreed "Next Donation Date" makes a lot more sense than "Renewal Date"! Thanks @anneforbush!

**Comment by mmtr** [comment]
We're tracking the remaining emails in separate issues: merchant-facing emails (https://github.com/Automattic/wp-calypso/issues/44110) and receipt emails (https://github.com/Automattic/wp-calypso/issues/44111).
