### ISSUE TITLE
Single Page Editing: new onboarding route in Horizon

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43284]
We need to provide a different version of Gutenboarding flow that's tailored for FSE. To start that we need either a separate onboarding route in Calypso, or we can use the existing one with the special parameter that will help us differentiate this flow from the default one. This will come in handy in places were we need to conditionally change something in the flow, like navigating to site editor instead of post editor, or displaying a different selection of themes/page layouts.

**Comment by ockham** [comment]
#43246 is currently doing this via a feature flag (that can be set by appending a `?flags=` query arg). We can go with this option for as long as it makes sense, and expand to a separate route if needed. (I'd rather avoid introducing the route right away, since it might lead to some -- currently unnecessary -- duplication of logic between the two flows.)

**Comment by vindl** [comment]
I think the query arg is completely fine and that we can close this issue.
