### ISSUE TITLE
Single Page Editing: front page loading

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43289]
In order to display the correct page when we load users in the site editor we'll need to accomplish the following tasks:

- [x] Ensure that Site Editor loads the selected static front page by default. It needs to load the correct template associated with that page. (@noahtallen)
- [x] That template should contain a post content block and it should be prefilled with front page’s content.

For the second part it would be good to verify if Seedlet blocks theme contains the appropriate page template in the first place and add it if that's not the case.

**Comment by ockham** [comment]
> Ensure that Site Editor loads the selected static front page by default. It needs to load the correct template associated with that page.

I _think_ that this should Gutenberg's responsibility (and thus, implemented there) -- it makes sense for Gutenberg to always show whatever template is responsible for rendering the site's home page upon first loading the Site Editor (which in our case happens to be a static front page). By and large, I think's this is how it works already (possibly pending https://github.com/WordPress/gutenberg/pull/23186).

**Comment by vindl** [comment]
> I think that this should Gutenberg's responsibility (and thus, implemented there)

 I think so too. I believe it will work out of the box but we agreed to split it out as a separate thing just in case.

**Comment by noahtallen** [comment]
I'm closing this because all the changes should be working in core:

- If your site is set to display latest posts, seedlet-blocks uses the `home` template which includes the posts block. This is the template which displays when you first enter the editor as well.
- If your site is set to display a static front page, seedlet-blocks uses the `singular` template, which includes post title and post content. When loading the editor, it correct loads the set homepage title and content.

Some fixes were made in core to accomplish this:
- https://github.com/WordPress/gutenberg/pull/23186 Made sure that the correct template was loaded for the homepage
- https://github.com/WordPress/gutenberg/pull/23180 Fixed a bug which prevented the post content and post title blocks from rendering on the front end.

**Comment by noahtallen** [comment]
I should also note that in the site editor, we already deliberately set the initial view to the homepage, whether it's a page or post.
