### ISSUE TITLE
More Detailed Plugin Pages in Calypso Plugin Browser

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#43332]
#### Description

When a plugin is clicked on in the Calypso Plugin Browser, a user is led to a page containing a header image and description of the plugin.

<img src="https://d.pr/i/Gesyr1+" width="600" />

#### Expected

To improve on this, the user may find it helpful to see another tab for Support, similar to the Calypso Theme pages:

<img src="https://d.pr/i/jHZJmh+" width="600" />

The tab would contain:

1. Information on whether it's third-party or a product of Automattic and whether we officially support it
2. A link to the .org support forum
3. A link to documentation that we create (if available)
4. A link to the plugin's official website and documentation

Widening the space containing the plugin info would be nice as well.

<img src="https://d.pr/i/F6b54m+" width="600" />

#### Actual

Currently, there is one tab containing only a description of the plugin.  It lacks support information and the description is confined within a 720 pixel frame that could make it difficult to read.

Related: #43230

**Comment by jordesign** [comment]
Would the info from 'Installation' tabs on the .org plugin repo be helpful here as well? Not all authors use it well - but many include installation and usage instructions there.

**Comment by cpapazoglou** [comment]
From my explorations:
the plugin page receives all data from `https://api.wordpress.org/plugins/info/1.0/woocommerce.json` (woocommerce example). So, in fact we already have all the wordpress.org data available. It is just our option, what to show.

WordPress.com Sites | Self Hosted
-------|------
![](https://cln.sh/Bh10zg+) | ![](https://cln.sh/6fSxas+)

The code https://github.com/Automattic/wp-calypso/blob/4537033c6794449ce0a10b69d72daf5fa658d553/client/my-sites/plugins/plugin-sections/index.jsx#L58-L60 decides to show less or more sections which seems like a product decision. The content of these tabs need some moderation whether they should be displayed in a WordPress.com site. I believe that Changelog and FAQ are regarded as safe, it seems we have to work out the Installation tab. Maybe always showing the Installation tab and adding a short note - warning on WordPress.com sites?

Instead of `Support` we should use the `FAQs` tab

![](https://cln.sh/A47Qx7+)

we can inject on top of that tab `Supported by Automattic | Not Supported by Automattic`. In the case that it is supported we may also add the `Contact Us` button. We can decide if it supported by Automattic or not by filtering on the `slug` of `https://api.wordpress.org/plugins/info/1.0/woocommerce.json` (by using a predefined list of supported plugins). 

What do you think?

**Comment by davipontesblog** [comment]
@olaolusoga is this something that is being explored by the Dotcom Design team? I think it's still very relevant. It may be related to the new marketplace approach as well.

**Comment by olaolusoga** [comment]
>is this something that is being explored by the Dotcom Design team? I think it's still very relevant. It may be related to the new marketplace approach as well.

Yes. Exploration around this will be baked into the overall UX. More to come.

**Comment by gcsecsey** [comment]
Designs are linked here: pdh6GB-sk-p2

**Comment by gcsecsey** [comment]
Backlog grooming:
Let's split this up by first updating the layout then updating the different components. We should create/point these stories on our next backlog grooming session:

- [ ] https://github.com/Automattic/wp-calypso/issues/63683
- [ ] https://github.com/Automattic/wp-calypso/issues/63684
- [x] https://github.com/Automattic/wp-calypso/issues/63711
- [x] https://github.com/Automattic/wp-calypso/issues/63713
- [ ] https://github.com/Automattic/wp-calypso/issues/63714
- [ ] https://github.com/Automattic/wp-calypso/issues/60769
- [ ] https://github.com/Automattic/wp-calypso/issues/63715
- [ ] https://github.com/Automattic/wp-calypso/issues/63716
- [ ] https://github.com/Automattic/wp-calypso/issues/63717
- [ ] https://github.com/Automattic/wp-calypso/issues/63887
- [ ] https://github.com/Automattic/wp-calypso/issues/63888

**Comment by cpapazoglou** [comment]
Let's open all the related subtasks.

**Comment by cpapazoglou** [comment]
I have created all issues under the Marketplace Plugin Details Page milestone https://github.com/Automattic/wp-calypso/milestone/395

Closing this.
