### ISSUE TITLE
Typography: Improve Reader sidebar Following list

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#43396]
#### Steps to reproduce

Starting at URL: https://wordpress.com/read

The list of sites you're following aren't indented right under their heading. Hierarchy is lost here especially since they share the same font size.

See: https://github.com/Automattic/wp-calypso/pull/43295#issuecomment-644955101

cc @sixhours

**Comment by jancavan** [comment]
I also noticed there's a large space between some nav items. Not sure if that was intentional.

![Screen Shot 2020-06-30 at 9 20 54 AM](https://user-images.githubusercontent.com/4924246/86151082-1a37d380-bab3-11ea-9121-8484c8284b4f.png)

**Comment by bluefuton** [comment]
Hi @sixhours 👋 I will have to defer to @Automattic/lighthouse here as they made the referenced changes to the sidebar.

**Comment by unDemian** [comment]
@bluefuton thanks for the ping, @evilluendas designed the extra spacing and new indenting, he will be back from AFK on Thursday

**Comment by evilluendas** [comment]
Hello! The space is intentional, but it was added to somewhat help with the lack of hierarchy. I'm not very familiarized with Calypso design patterns and I wasn't able to find any existing pattern that indented items with icon, but if hierarchy can be achieved in a better way I'm totally in favor of removing those spaces. 👍
