### ISSUE TITLE
Premium Content: Switching from NZD plan throws a JS error

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#43450]
The Premium Content Block may throw an error when attempting to switch from a NZD plan in block settings

### To reproduce 
1. With a site with the premium plan or above
2. Create a number of payment plans in `https://wordpress.com/earn/payments/siteSlug`, with one plan being NZD
3. Go into the post or page editor and add a premium content block
4. Set the backing plan to NZD
5. Attempt to switch away from NZD

Expected: we can switch plans
Actual: A JS error is thrown

![Jun-18-2020 10-05-18](https://user-images.githubusercontent.com/1270189/85053871-035abe00-b150-11ea-9690-3c8f64d75259.gif)

<img width="705" alt="Screen Shot 2020-06-18 at 10 45 38 AM" src="https://user-images.githubusercontent.com/1270189/85054423-deb31600-b150-11ea-9979-07be6ddbd0db.png">
<img width="924" alt="Screen Shot 2020-06-18 at 10 45 32 AM" src="https://user-images.githubusercontent.com/1270189/85054430-dfe44300-b150-11ea-90fb-01c7677d7998.png">

**Comment by mmtr** [comment]
Investigated this for a bit today and noted a few things:
- The JS error is no longer thrown. Likely solved by other PR.
- However, plans cannot be switched. The issue only happens when trying to change the plan from the Recurring Payments inner block. Changing the plan from the Premium Content block works fine:
![Jun-25-2020 15-08-19](https://user-images.githubusercontent.com/1233880/85725815-c49ba980-b6f5-11ea-9b94-5d9c5fb38916.gif)
- This is caused because the Premium Content block enforces [any nested Recurring Payments block to use the same plan](https://github.com/Automattic/wp-calypso/blob/ea4003723293ba41b1d367891cf9de7102c1beb9/apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/buttons/edit.js#L40-L45).
- The issue is more notorious because the nested Recurring Payments block is auto-focused when the Premium Content block is inserted, making easier to assume the block controls displayed in the sidebar belongs to the Premium Content block.

A better approach would be:
- Hide the plan selector in any nested Recurring Payments block so users are forced to use the plan selector of the Premium Content block.
- Auto-select the Premium Content block on insertion.

**Comment by mmtr** [comment]
> Auto-select the Premium Content block on insertion

This PR should handle this: https://github.com/Automattic/wp-calypso/pull/43684

> Hide the plan selector in any nested Recurring Payments block so users are forced to use the plan selector of the Premium Content block.

Turns out this is not trivial because we cannot change the Recurring Payments block controls from other blocks. If we want to implement this we'll need to do it in Recurring Payments block itself. Alternatively, rather than hiding the selector, we could listen for plan changes in a nested Recurring Payments block and update the plan of the parent Premium Content block.

**Comment by mmtr** [comment]
> Turns out this is not trivial because we cannot change the Recurring Payments block controls from other blocks. If we want to implement this we'll need to do it in Recurring Payments block itself. 

Added support for this in https://github.com/Automattic/jetpack/pull/16313 and updated https://github.com/Automattic/wp-calypso/pull/43684 to use the new filter.
