### ISSUE TITLE
Checkbox Group: It is not possible to edit the block title

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#43612]
#### Steps to reproduce

1. Add the Checkbox Group block to the Form block
2. Add the title
3. Add several checkboxes below
4. Try to change the block title and observe

#### What I expected

It is possible to edit the block title.

#### What happened instead

Cursor jumps back to the last edited checkbox as soon as I try to edit the block title. I managed to edit the title only after I hit `CMD + X` and removed the current title.

#### Browser / OS version

Doesn't seem to be related.

#### Screenshot / Video

![Screen Capture on 2020-06-24 at 11-54-05](https://user-images.githubusercontent.com/25105483/85534352-92188080-b611-11ea-92ac-b3300ccc5ddb.gif)

#### Context / Source

#manual-testing

**Comment by KokkieH** [comment]
The same thing happens when editing individual checkbox items:

![checkbox](https://user-images.githubusercontent.com/11873759/89375962-1d942f80-d6ef-11ea-89d4-5d3b2ea1dea7.gif)

Suspect it might be related to https://github.com/Automattic/jetpack/issues/15479, though I can only replicate it on a WordPress.com simple site, not a Jetpack-connected site.

User report in https://wordpress.com/forums/topic/block-editor-contact-form-possible-bugs/#post-3538748

**Comment by ivan-ottinger** [comment]
I tried to reproduce the issue (on both - individual checkbox items and Checkbox Group) and it seems to be fixed already.
