### ISSUE TITLE
Question: Why should i communicate through Wordpress.com?

### ISSUE THREAD

**Issue by mehhrad** [Automattic/wp-calypso#43724]
i have a self hosted wordpress instance, why i should install jetpack and communicate through wordpress.com with my wp instapnce? 

why not communicate with my wp instance directly?

**Comment by nagpai** [comment]
The Repository here is meant for development of the Calypso interface, and to report bugs and feature requests for Calypso.

For the question you have asked regarding Jetpack, a better forum to ask would be https://wordpress.org/support/plugin/jetpack/

It is not compulsory to use the Jetpack plugin if you do not wish to. However it's features such as stats, CDN and more, require WordPress.com infrastructure and hence requires a connection. If you do not wish to use Jetpack, you can certainly uninstall the plugin.

I am closing the issue here since it is not a report about Calypso.

**Comment by mehhrad** [comment]
with calypso you want to replace the old wp-admin page with a fast reactive dashboard,

why should we use wordpress.com infrastructures? my wp instance has all the rest api you need, it's not a complicated question.

i'm not talking about jetpack, but what if i want to be independent of wordpress.com infrastructures?

**Comment by nagpai** [comment]
As mentioned on the project home page here :
https://developer.wordpress.com/calypso/

```
A single interface to manage all your WordPress.com or Jetpack-enabled sites
```

If you scroll down in the Q and A section

```
**Will you be using the WordPress core REST API in the future?**
We're excited about the REST scaffolding going in WordPress 4.4, but the endpoints in the latest version don't cover a huge part of what we're doing. Automattic contributors to core have been heavily involved in the core API work so far, and we expect that to continue and increase in 2016, hopefully completely harmonizing the different APIs in one of the core releases next year.
```
This was probably written quite a while ago indicating that Calypso runs on WordPress.com API. and hence currently supports WordPress.com and Jetpack connected sites only. 

For Calypso to run without WordPress.com API and with Core WP.org API, will require lot of changes in the core code. Maybe an opportunity to create a separate project.
