### ISSUE TITLE
Site Editor: Vesta layout not matching the front end on Seedlet blocks theme

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43882]
There is a slight discrepancy between what's rendered in editor and front end for Vesta layout in Seedlet blocks theme.

This is likely a theme issue that needs to be resolved, similar to https://github.com/Automattic/themes/pull/2204.

### Testing instructions

1. Apply D45778 and D45780 to your sandbox.
2. Create a new test FSE site and select the Vesta layout.
3. Sandbox the newly created site.
4. Reload the site editor.
5. Notice the misaligned images.

<img width="1680" alt="Screenshot 2020-07-03 at 01 12 23" src="https://user-images.githubusercontent.com/1182160/86416473-45484000-bcca-11ea-874c-07f36af6df59.png">

**Comment by vindl** [comment]
@kjellr pointed us to this issue which might be related https://github.com/Automattic/themes/issues/2191.

**Comment by alaczek** [comment]
Yep, I bet this is it from reading the CSS:

![image](https://user-images.githubusercontent.com/4550351/86713384-5e9e1300-c061-11ea-9724-e4cc28a0b8b7.png)

**Comment by Copons** [comment]
This seems to happen because Seedlet removes the top margin on first-child blocks:

https://github.com/Automattic/themes/blob/55051ac7b0904213034713c8d8c56ba20a5766ec/seedlet/assets/sass/blocks/utilities/_editor.scss#L166-L168

It's generally not an issue, as blocks are displayed vertically, but it obviously gets in the way with columns.
Core Gutenberg explicitly removes the top margin to all columns:

https://github.com/WordPress/gutenberg/blob/e2da15e22364f8f75e7dae9476bde687f34fc553/packages/block-library/src/columns/editor.scss#L22-L28

I think this should probably be fixed in the `jetpack/layout-grid-column` editor style, rather than in the theme.

**Comment by Copons** [comment]
Note that this has been fixed in the [Layout Grid Block plugin](https://en-gb.wordpress.org/plugins/layout-grid/), so it won't be visible immediately.
