### ISSUE TITLE
Global Styles: Heading and base fonts switched

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#43904]
#### Steps to reproduce

1. Enable a Varia child theme, e.g. Redhill or Brompton.
2. Create a new post, add a title and some paragraphs
3. Click the global styles icon and change the heading and base font

#### What I expected

For the selected fonts to be applied to the title and content respectively.

#### What happened instead

The base font gets applied to the post title, and the heading font gets applied to the paragraphs.

#### Screenshot / Video

<img width="781" alt="Edit_Post_‹_kokkiestrialtestsite_—_WordPress_com" src="https://user-images.githubusercontent.com/11873759/86558192-fbc15480-bf58-11ea-91d5-25c9654356d5.png">

#### Context / Source

Discovered while checking something unrelated in helping the user in https://wordpress.com/forums/topic/varia-theme/

**Comment by FireQueen-3010** [comment]
I want to work on this!

**Comment by pauljacobson** [comment]
I picked up on this in 3117893-zen while on a Quick Start Support session with a user. The user was using the Redhill theme at the time, and you can [see the issue in action here](https://d.pr/v/mf0SKq/LeYUlI3RVJ).

**Comment by kcswong** [comment]
Just got another report of this from a user in 26017946-hc where they reported this behavior, but I observed that changing the Heading font changed the font for the whole site

**Comment by simison** [comment]
> observed that changing the Heading font changed the font for the whole site

That's intentional 👍 

> The user was using the Redhill theme at the time, and you can see the issue in action here.

@scruffian hi! is this a theme bug?

**Comment by scruffian** [comment]
I'll add it to the list...

**Comment by pbking** [comment]
From what I can tell this is a theme issue and seems to be specific to Redhill.  (Contrary to the notes in the description testing with Brompton show that the header/base fonts follow the settings in the Style Editor.) So far Redhill is the only theme that I have noticed this issue in, however I have thus far only evaluated some of the Varia child themes.  (Varia itself is also not experiencing the issue.)

This is not recent breakage, the Redhill theme appears to have inverted the header/base fonts since the [initial commit of the theme](https://github.com/Automattic/themes/commit/9d9e5bc1d4276f7d4d5cabd9064cce1841914a9c#diff-78fa1b477ee966c2b5634645425dfe51ed26913da87690d2787b8fd809c64ce4R197) which is the inverse of [other child themes](https://github.com/Automattic/themes/commit/0066ccdaab4f0a010f73159c5eda7611f6ec4cf0#diff-04023cf71018868b888ce717d915df1ac46614f2d7d014bbfffdac82eb4d83f6R201).  (That heading style is referenced as an example; There are many other spots where the primary/secondary variable usage was swip-swapped).

There are a couple of ways this might be addressed, but all of them would invert [all,most] of the element's current font selections (things using a header font would switch to a base, things using the base font would switch to header).  Which would address the ask of the issue.  However it would also suddenly invert the font selections of all sites using the Redhill theme that are leveraging that Global Style editor.

**Comment by pbking** [comment]
One potential option for a fix might be: https://github.com/Automattic/themes/pull/3123

**Comment by scruffian** [comment]
@simison what are your thoughts on this fix? The concern is that this will switch things for existing users...

**Comment by simison** [comment]
Oh, that's a bummer! We shouldn't do that, at least without communicating with customers first.

Are there any technical solutions to fix this and avoid changing it to existing customers who applied fonts on that theme?

cc @ianstewart

**Comment by scruffian** [comment]
I guess we could run a script to update all of the fonts for users of this theme manually... 😭

**Comment by simison** [comment]
Yeah, we have some scripts to do that already. It's less scary than it sounds. :-)

I agree that's probably the best, considering that adding any conditionals in code would need to be maintained ad-infinitum anyway, so it's better to do more work to get it sorted all at once.

**Comment by scruffian** [comment]
Ok, can I let y'all handle this? You have the PR for when you need it..

**Comment by simison** [comment]
@scruffian Hi! I didn't notice your question earlier, thanks for patience.

Did you mean that .com teams would do the migration? I think it goes a bit more into theme-integration aspects of work so I'd expect it from you all.

**Comment by pbking** [comment]
The portion of the theme that needs to change is (I believe) covered by the PR noted above.  It and the inversion of existing header/body selections for Redhill should be brought in together, but I'm afraid I have no idea how the inversion portion would be done.  @simison you mentioned above that you have some scripts to do that part already.  Will you be able to help us out with that?

**Comment by simison** [comment]
Gotcha! Yeah so I just meant that there are heaps of scripts for this kind of tasks on wpcom at `bin/one-time/*`.

**Comment by scruffian** [comment]
Ok I've added it to the board. @jeffikus I'll let you prioritize this one :)

**Comment by youbrokesomething** [comment]
The Redhill theme was retired in June 2021 and there haven't been user complaints since (on this issue at least) so I'm going to close this.
