### ISSUE TITLE
(5P) Social Previews: Prevent rendering HTML tags visually

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#43948]
#### Steps to reproduce

The preview currently shows things like this:

<img width="138" alt="Screenshot 2020-07-07 at 17 58 08" src="https://user-images.githubusercontent.com/156676/86809415-25bf6780-c07c-11ea-8774-ca37143f1ec9.png">

We should strip tags or find different sources for data that are already cleared.

**Comment by getdave** [comment]
I took a brief look at this. I wonder whether some of the markup isn't being stripped from the string because the `post.content` includes Gutenberg grammar comments. I think the parser might be missing them. Something to consider anyway when looking into this issue.

Note how the `ReaderPreview` component handles this perfectly, so there must be something working better in that component than the others...
