### ISSUE TITLE
Cover Block: Dimensions - Minimum Height - First number gets remembered and can't be changed

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#43961]
#### Steps to reproduce

1. Create a new page
2. Add a Cover Block, 
3. On the right hand side under Dimensions, give a custom "Minimum height of cover" - Any number can work here. 500, for example. 
4. Change your mind. Delete your number, and add a new number. If you chose 500 above, now try to make it 250.
5. The first number (5) will appear first, whether you type a 1, 2, 3, 4, 6, 7, 8, or 9, so once you've chosen that first number, it can't be immediately changed.

#### What I expected
The number to be able to be updated to whatever you want that number to be.

#### What happened instead
The first number you choose gets stuck. 

#### Browser / OS version
All
#### Screenshot / Video
In this example, every number typed when trying to change it is not a "1"

![coverblock](https://user-images.githubusercontent.com/30731356/86846841-44176a00-c060-11ea-8a26-732bf3375522.gif)

#### Context / Source

#manual-testing, or #user-report if applicable.

**Comment by yansern** [comment]
The reason this is happening is because the `onChange` input fires the last known valid value when the input field is empty. The `onChange` event by `UnitControl` is actually a modified version of the `onChange` event which has a different behaviour than the native `onChange` event.

The solution is to use `onInput` which ensures the event handler always executes when input value has changed.

PR: https://github.com/WordPress/gutenberg/pull/24392

**Comment by ockham** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/24490.
