### ISSUE TITLE
Editor: icons are HUGE in Windows IE Edge

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#4399]
#### Steps to reproduce
Open Windows (I used Windows 10) and launch wpcalypso in Edge browser. Add a new post.

<img width="1270" alt="screen shot 2016-03-29 at 12 18 12" src="https://cloud.githubusercontent.com/assets/66797/14120733/07a5a720-f5a9-11e5-9fa2-d37528df96cc.png">

#### What I expected
The icons to work like OS X and Chrome on Windows.

<img width="1270" alt="screen shot 2016-03-29 at 12 24 51" src="https://cloud.githubusercontent.com/assets/66797/14120781/493c81f4-f5a9-11e5-9302-3606de8bea08.png">

#### What happened instead
The icons are HUGE!

<img width="1270" alt="screen shot 2016-03-29 at 12 19 18" src="https://cloud.githubusercontent.com/assets/66797/14120749/22923094-f5a9-11e5-932d-e0c76e3625c1.png">

**Comment by aduth** [comment]
Hmm, looks like we missed a few icons in #4280 (cc @gwwar)

**Comment by aduth** [comment]
As @gwwar mentioned at https://github.com/Automattic/wp-calypso/pull/4280#issuecomment-200604313, I think there might be a possible solution to explore from the Gridicon base component. I'm a bit wary of applying an inline style attribute, as that has a much higher specificity than any styles which would be applied via a CSS selector. The problem seems to be with how IE is handling `width: auto;` on the SVG elements (applied via [borderless button styling](https://github.com/Automattic/wp-calypso/blob/6607d0910a2d579ad4b30db60e3de92b48ada418/client/components/button/style.scss#L175-L176)).

Since there's an immediate fix available, I'll opt to take a similar approach to that in #4280 until we can spend more time investigating a more permanent solution.

**Comment by gwwar** [comment]
> I'm a bit wary of applying an inline style attribute, as that has a much higher specificity than any styles which would be applied via a CSS selector.

We pass in a size prop, so I think it's fine in this case. We can remove this when we drop IE 11 support in the future.

**Comment by aduth** [comment]
>We pass in a size prop, so I think it's fine in this case.

The problem is there are cases where styles are applied and presumed to take precedence over the default size ([example](https://github.com/Automattic/wp-calypso/blob/6607d0910a2d579ad4b30db60e3de92b48ada418/client/components/button/style.scss#L99-L100)), which would not be true if a `style` attribute were present.
