### ISSUE TITLE
Customer Home: Move Checklist items from left to right

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#44112]
#### Steps to reproduce

On a new site. This is what the Checklist should look like:

![Screen Shot 2020-07-13 at 10 01 34 AM](https://user-images.githubusercontent.com/4924246/87332053-d780ed00-c4ef-11ea-9e95-8efacd67d2c9.png)

Let's move the Checklist items from the left to the right like so:

![Screen Shot 2020-07-13 at 10 02 27 AM](https://user-images.githubusercontent.com/4924246/87332117-f7181580-c4ef-11ea-9608-61e331d2a1b2.png)

This gives more focus on the main cards and tasks vs the list of items in the Checklist.

Related discussion: CS0C44U07-p1594415624033500-slack

cc @rickybanister @danhauk @lcollette

**Comment by sfougnier** [comment]
**Desktop**
Shifted checklist to the right of the highlighted task card on desktop. See the full flow [here](https://www.figma.com/file/2v3gyTfWHBDS9iT7aoVCB4/Customer-Home-Checklist?node-id=7%3A4540).

<img width="1440" alt="01B Desktop" src="https://user-images.githubusercontent.com/67021691/87571599-4b5df980-c698-11ea-8b93-5216e072583e.png">

**Mobile**
The current experience highlights the list menu first, requiring users to tap into the task. I think this is still viable but took the opportunity to explore integrating the list with the tasks. Perhaps there is a possibility to keep the list and task separated, but highlight the specific task on landing rather than the full list?

<img width="1488" alt="Screen Shot 2020-07-15 at 12 50 49 PM" src="https://user-images.githubusercontent.com/67021691/87572664-e4414480-c699-11ea-85e6-046321210eb0.png">

An alternative approach that highlights each step in order to align mobile with the intent of desktop. If we want to place emphasis on the task rather than the list, automatically expanding each task in an accordion style list may help achieve that.

<img width="1329" alt="Screen Shot 2020-07-15 at 12 38 54 PM" src="https://user-images.githubusercontent.com/67021691/87571638-59137f00-c698-11ea-864d-033725c2cf29.png">

[Full flows here](https://www.figma.com/file/2v3gyTfWHBDS9iT7aoVCB4/Customer-Home-Checklist?node-id=7%3A4467)

**Comment by rickybanister** [comment]
Looks lovely. 

Are there any suggestions you have for giving more life to the actionable side of the checklist at larger widths?

Some of them feel a bit anemic with all that unused white space.

**Comment by davemart-in** [comment]
I removed this from the Manage Group backlog. My assumption is that this is something that can be achieved without the need for engineers. If you need a hand with anything, please let me know. Thanks!

**Comment by jancavan** [comment]
There's an existing PR related to this issue: https://github.com/Automattic/wp-calypso/pull/44124. Can someone please review if any more changes need to be made? @sfougnier @sixhours @lcollette

**Comment by sfougnier** [comment]
The changes in the existing PR look fine, but I think it would be good to consider how this update can impact mobile. @sixhours and I chatted through the feasibility of this update to the mobile checklist at the end of last week. If we feel this is a good update I think it's worth taking advantage of this to improve the mobile experience as well.

<img width="877" alt="Screen Shot 2020-07-20 at 2 46 40 PM" src="https://user-images.githubusercontent.com/67021691/87974321-e7707200-ca97-11ea-874a-5996dc232edb.png">
