### ISSUE TITLE
Error when run webpack

### ISSUE THREAD

**Issue by minhchu** [Automattic/wp-calypso#4417]
This is not an issue. Sorry for asking here.

I use windows and dont have `make` command. 
I read the Makefile and figure how `make` run so I can install Calypso without `make`
As I see on line 141:
```
build-server: install
	@mkdir -p build
	@CALYPSO_ENV=$(CALYPSO_ENV) $(NODE_BIN)/webpack --display-error-details --config webpack.config.node.js
```
I try running:
``
node_modules\.bin\webpack --display-error-details --config webpack.config.node.js
``
it shows an error:
```
Hash: 0f7db56f0b7502023736  
Version: webpack 1.12.6  
Time: 8257ms  
                    Asset     Size  Chunks             Chunk Names
    bundle-development.js  1.14 MB       0  [emitted]  main
bundle-development.js.map  1.46 MB       0  [emitted]  main
    + 508 hidden modules    
ERROR in ./client/sections.js  
Module build failed: Error: Cannot find module 'config'  
    at Function.Module._resolveFilename (module.js:325:15)  
    at Function.Module._load (module.js:276:25)  
    at Module.require (module.js:353:17)  
    at require (internal/module.js:12:17)  
    at Object.<anonymous> (D:\calypso\client\sections.js:1:76)  
    at Module._compile (module.js:409:26)  
    at Object.Module._extensions..js (module.js:416:10)  
    at Module.load (module.js:343:32)  
    at Function.Module._load (module.js:300:12)  
    at Module.require (module.js:353:17)  
    at require (internal/module.js:12:17)  
    at Object.module.exports (D:\calypso\server\isomorphic-routing\loader.js:30:13)  
 @ ./server/pages/index.js 15:15-47  
```
While on Ubuntu, I run ``make build-server`` without any errors.
Could anyone explain what the difference between run `make` and run directly ?
I really appreciate any help.
Thanks.

**Comment by klimeryk** [comment]
Well, this is certainly an interesting approach :grin: The `Makefile` does mainly two things - invoke a series of commands and export some environment variables. While in most cases there are some sane defaults (no `CALYPSO_DEV`? We'll assume you want `development` then), an [important variable is `NODE_PATH`](https://github.com/Automattic/wp-calypso/blob/master/Makefile#L62) which is [directly used by `node`](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders). Try exporting it like this from the root of Calypso:
```
export NODE_PATH = server;client;.
```
You _are_ using at least a bash shell, _right_? :smile:

Even if you manage to start Calypso this way, it is a very fragile setup and is not supported by us. If you are willing to go to all this trouble, [why not set up MSYS2](https://github.com/Automattic/wp-calypso/blob/master/docs/windows.md)? It's quite light-weight, especially compared to Cygwin... And it's a one-time effort, instead of worrying that the next `git pull` might break your build.

I'm closing this because this is a setup we are definitely not supporting - unless you have a very good reason for not wanting to install `make`? I'd be willing to help more if, for example, you wanted to get to know how the build process exactly works (hence "bypassing" `make`), but this doesn't seem to be the case :)

**Comment by minhchu** [comment]
Thank you for the answer. 
I actually installed calypso with MSYS2. It's just for my curiousity to understand how `make` work in this case. 
It would be great that you explain the build process in details.
Thanks.

**Comment by klimeryk** [comment]
The easiest way to see how something is built using make is to use the `--dry-run` option that will print the commands that would be executed (without executing them):
```
$ make run --dry-run
printf "\033[36m             _                           \n"
printf "\033[36m    ___ __ _| |_   _ _ __  ___  ___      \n"
printf "\033[36m   / __/ _\` | | | | | '_ \/ __|/ _ \\   \n"
printf "\033[36m  | (_| (_| | | |_| | |_) \__ \ (_) |    \n"
printf "\033[36m   \___\__,_|_|\__, | .__/|___/\___/     \n"
printf "\033[36m               |___/|_|                  \n"
printf "\033[m\n"
```
Fancy ASCI art :wink:
```
if [ ! -e .git/hooks/pre-commit ]; then ln -s ../../bin/pre-commit .git/hooks/pre-commit; fi
if [ ! -e .git/hooks/pre-push ]; then ln -s ../../bin/pre-push .git/hooks/pre-push; fi
```
These hooks run `eslint` and some other safeguards before commiting/pushing.
```
'/mnt/work/a8c/workspace/calypso'/bin/check-node-version
```
We check if you have an up to date version of node.
```
mkdir -p build
CALYPSO_ENV=development '/mnt/work/a8c/workspace/calypso'/node_modules/.bin/webpack --display-error-details --config webpack.config.node.js
```
Run webpack using the config in `webpack.config.node.js`.
```
'/mnt/work/a8c/workspace/calypso'/bin/record-env .env
```
This records the `CALYPSO_ENV`'s value in the `.env` file. Why? So that `make` can track it (`make` is great at tracking changes in files) and regenerate the following file:
```
node server/config/regenerate-client.js > client/config/index.js
```
This generates `client/config/index.js` based on your current config (which is based on your `CALYPSO_ENV` variable). So, for `development`, `config/development.json` will be used.
```
'/mnt/work/a8c/workspace/calypso'/node_modules/.bin/node-sass --include-path 'client' assets/stylesheets/style.scss public/style.css
'/mnt/work/a8c/workspace/calypso'/node_modules/.bin/postcss -r --use autoprefixer --autoprefixer.browsers "last 2 versions, > 1%, Safari >= 8, iOS >= 8, Firefox ESR, Opera 12.1" public/style.css
'/mnt/work/a8c/workspace/calypso'/node_modules/.bin/rtlcss '/mnt/work/a8c/workspace/calypso'/public/style.css public/style-rtl.css
'/mnt/work/a8c/workspace/calypso'/node_modules/.bin/node-sass --include-path 'client' --source-map "public/style-debug.css.map" assets/stylesheets/style.scss public/style-debug.css
'/mnt/work/a8c/workspace/calypso'/node_modules/.bin/postcss -r --use autoprefixer --autoprefixer.browsers "last 2 versions, > 1%, Safari >= 8, iOS >= 8, Firefox ESR, Opera 12.1" public/style-debug.css
'/mnt/work/a8c/workspace/calypso'/node_modules/.bin/node-sass --include-path 'client' assets/stylesheets/editor.scss public/editor.css
'/mnt/work/a8c/workspace/calypso'/node_modules/.bin/postcss -r --use autoprefixer --autoprefixer.browsers "last 2 versions, > 1%, Safari >= 8, iOS >= 8, Firefox ESR, Opera 12.1" public/editor.css
```
Process our CSS files with SASS and autoprefixer.
```
node build/bundle-development.js
```
Run Calypso!

Well, that's it in a nutshell. Dig into the Makefile to see more details, which commands depends on what, etc. Happy hacking! :wink:
