### ISSUE TITLE
Premium Content: Double "connect to Stripe" message

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#44332]
When adding Premium Content block for the first time (before the Stripe connection is established), a "Connect to Stripe" banner is displayed twice.

#### Steps to reproduce

1. On a site with a Premium plan and where none of the Earn blocks were set up before, add a Premium Content block to a post or a page.
2. You should see two "Connect to Stripe" banners, with different designs.
3. Switch between Subscriber and non-subscriber view. The non-subscriber view is the one with two banners.
4. Once you connect to Stripe both banners go away.

#### What I expected
To see only one Stripe banner.

Non-subscriber view:

![image](https://user-images.githubusercontent.com/4550351/88131266-e407f280-cc1f-11ea-9bd4-74c94cc82ba1.png)

Subscriber view:

![image](https://user-images.githubusercontent.com/4550351/88131289-f2560e80-cc1f-11ea-9e43-ab8b38eaaf61.png)

**Comment by blackjackkent** [comment]
Did some digging on this today. The culprit seems to be repeated code between Calypso and Jetpack.

In Calypso's https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/logged-out-view/edit.js, the view first loads a `StripeNudge` component from `../../container/stripe-nudge.js`. It then loads the buttons from `../../buttons/edit.js`, which further calls a template called `recurring-payments` from Jetpack (https://github.com/Automattic/jetpack/blob/master/extensions/blocks/recurring-payments/edit.jsx), which has its own `StripeNudge` component from the Jetpack repo at `../../shared/components/stripe-nudge/index.js`. They both have the same text but slightly different stylings, so the user ends up seeing two similar but not identical bits of messaging.

I'm not sure of the ideal solution here. 🤔 I'm assuming the functionality is in both places since the user isn't guaranteed to both have Calypso and Jetpack; off the top of my head it seems like the correct choice would be to have Jetpack check whether it's on a wpcom site in some way before displaying its nudge. But I need to delve further. Suggestions appreciated!

**Comment by mmtr** [comment]
Nice sleuthing @blackjackkent! So the issue is that the Premium Content reuses the Payments block (formerly known as Recurring Payments block) for rendering a subscribe button in the non-subscriber view.

Since the Payments block has its own nudge when there is no connection to Stripe, we end up with 2 nudges:
- The one implemented in the Premium Content block which is displayed below the subscriber/non-subscriber tabs menu.
- The one implemented in the Payments block which is displayed above the subscribe button.

I'd say we should keep the first one, which is the only one that stays visible when editing both views and it's displayed in a better location at the top of the block (as oppose to the nudge of the subscribe button, which is only visible in the non-subscriber view and displayed at the bottom of the block). Furthermore, a user could remove the subscribe button from the block if they wish, so we need to have a nudge that is controlled entirely in the Premium Content block.

Unfortunately, we cannot disable the Payments block nudge from a parent block right now, but one quick fix might be to hide it with CSS if we add a rule to https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/premium-content/style.css

**Comment by blackjackkent** [comment]
@mmtr Thanks, Miguel! I've pushed a CSS change per your suggestion to my PR for this issue.

**Comment by kwight** [comment]
@blackjackkent While testing https://github.com/Automattic/wp-calypso/pull/45204, it looks like I found a regression – the double Connect is back:

<img width="1034" alt="Screen Shot 2020-08-25 at 3 59 14 PM" src="https://user-images.githubusercontent.com/349751/91236160-1196fe80-e6ec-11ea-8b95-f74a9b0f6dee.png">

On a quick look, I didn't see the `premium-content/style.css` file that handles this:

<img width="523" alt="Screen Shot 2020-08-25 at 4 02 39 PM" src="https://user-images.githubusercontent.com/349751/91236302-6dfa1e00-e6ec-11ea-9f5d-96364a337a85.png">

**Comment by blackjackkent** [comment]
@kwight It looks like this regression was a consequence of the change at https://github.com/Automattic/wp-calypso/pull/44825, which split the initialization of the block out into multiple lifecycle hooks. The style which hides the extra Stripe notification needs to be in `editor.css` now, which is initialized for the edit view, rather than `style.css`, which is now only initialized for the front-end view.
