### ISSUE TITLE
Reader: Unfollowing a site does not remove it from the sidebar

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#44350]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/feeds/94581160
2. Follow the site
3. Refresh the reader. Notice the site appears in the Following sidebar and is selected.
4. Unfollow the site from the site view
5. Notice the site still appears in the sidebar. Maybe it stays until we pick a new site?
6. Click on another site under Following. The first site still remains in the sidebar.

#### What I expected

The site to be removed from the sidebar once I navigated away from it

#### What happened instead

The site remained

#### Browser / OS version

Chrome 83 / macOS

**Comment by nerdysandy** [comment]
I can't replicate it anymore. It stays there until I refresh the page after unfollowing it. I believe this is expected behavior? I tested it using the Desktop app too. It went away after I quit the app and relaunched it. I understand that there is no way to refresh the app but I believe that sounds more like a feature request for the app, in general, to be able to refresh it?
