### ISSUE TITLE
Seeing 3 duplicate intro posts upon new site creation

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#44430]
### What
There are 3 copies of the same post coming with the default signup theme. Let's get that number down to 1

### Why
Seeing a duplicate post may not be an ideal UX

### A/C
- [ ] delete the two additional example posts from the source site of the default theme
- [ ] recreate annotations

#### Steps to reproduce

1. Sign up for a new WP.com account
2. Select free URL
3. Visit posts page

#### What I expected

For there to be one example post.

#### What happened instead 

There were 3 copies of the same post.

#### Browser / OS version

Mac OsX, Chrome Version 83.0.4103.116 (Official Build) (64-bit)

#### Screenshot / Video

<img width="1093" alt="Image 2020-07-24 at 10 47 14 AM" src="https://user-images.githubusercontent.com/5634774/88403908-243fb000-cd9b-11ea-90aa-d8e2b37c4c44.png">

**Comment by andrewserong** [comment]
Just adding some further context for anyone else looking at this issue: the default Headstart annotation for a newly created site from `/start` features a Blog Posts block with three posts in it on the Home page. In order to show a layout with three blog posts, there needs to be three example posts in the site:

![image](https://user-images.githubusercontent.com/14988353/99220334-93518080-2832-11eb-8345-36f1c9dfb59a.png)

So, a solution to this might be non-trivial to implement as it'd probably involve customising the Blog Posts block in some way. I've labelled this as low priority because fixing it would probably need to be a project prioritised outside the scope of gardening.

**Comment by simison** [comment]
Since we're moving to a design picker in signup (pbAok1-26U-p2) and sites won't have default headstart content, this problem will go away on its own.

Related https://github.com/Automattic/wp-calypso/issues/44151

**Comment by ianstewart** [comment]
@simison I saw you re-opened https://github.com/Automattic/wp-calypso/issues/44151 — want to re-open this one as well?

I have a simple fix if we proceed with 44151 that would close this one again. We can just delete the two additional example posts from the source site. :)

**Comment by razvanpapadopol** [comment]
Patch in D61839-code accepted and ready to 🚢

**Comment by alshakero** [comment]
Here is how it looks right now.

![water861730831 wordpress com_ (1)](https://user-images.githubusercontent.com/17054134/119982030-9f2ab600-bfbe-11eb-9514-a21453bda29c.png)
You can also see the actual site here: Pd6a5N-5-p2.

**Comment by simison** [comment]
It's not amazing looking, but that's expected. Fine to ship, and it sounded like Ian is ok with it too.

- Overall not needing to delete a bunch of posts is better as an experience
- We know we'll work on placeholders (https://github.com/Automattic/view-design/issues/274)
- We know we'll replace this default layout with something else (https://github.com/Automattic/wp-calypso/issues/52580)
- We know customers will see default layout way less often after design picker is shipped (pbAok1-26U-p2)
