### ISSUE TITLE
Earn: Non-USD Total Earnings reported in USD

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#44433]
There is a UI bug in the `/earn/payments/siteSlug` on Calypso.

<img width="156" alt="Screenshot 2020-07-24 at 23 02 38" src="https://user-images.githubusercontent.com/5560595/88439008-e4f87a00-ce01-11ea-9d69-94c79186e76a.png">

Background: pbMlHh-sZ-p2

The total earnings amount is actually the total USD amount. 

In this case, the user's currency is GBP. The user has collected `£90` to date.

The total amount is calculated in [Connected_Accounts\get_memberships_earnings_totals()](https://opengrok.a8c.com/source/xref/trunk/wp-content/lib/billingdaddy/src/api/connected-accounts-namespace.php#610).

This lookup returns the USD amount, rather than the local gross amount.

As such, the total USD amount is `$114.92` but is getting reported as `£114.92` in Calypso.

The fix here would be to update the `get_earnings` endpoint to return the total local gross and display this total if the user has a non-USD currency.

**Comment by susanjanec** [comment]
I had a user in chat 23321761-hc where the user has 4 subscribers at £15.00/year, but it is showing their total earnings as £98.10. From what I understand it appears to be a conversion issue here. However, in this case it also appears that the amount also includes a cancelled subscription in the total which wasn't refunded.

Can someone clarify the expected behavior in this case?

**Comment by n3f** [comment]
@blackjackkent - Still an issue, there's a report: p1598456360069400-slack-CDA5HLRD2/p1598456360069400

**Comment by mmtr** [comment]
Hopefully D48683-code will fix this.
