### ISSUE TITLE
Redirect to concierge upsell after new card purchase requiring 3DS is busted

### ISSUE THREAD

**Issue by nbloomf** [Automattic/wp-calypso#44541]
The 3DS post-success redirect to the concierge upsell page is not working correctly. This does not prevent the purchase, but is confusing UX. First noticed this bug in #44119 and related patches.

#### Steps to reproduce

1. Manually put yourself in the `offer` group of the `conciergeUpsellDial` A/B test
1. Add a Personal plan to your cart.
1. Enter composite checkout (currently enabled for all US/USD purchases)
2. Pay using a good new 3DS-enabled credit card. Test credentials are at stripe.com/docs/testing, e.g. `4000000000003220`
3. Authenticate the payment (if using a test card, simply accept when the modal pops up)

#### What I expected

To redirect to the quickstart upsell page.

#### What happened instead

I remained on the checkout page, which is stuck in a mostly-disabled state and develops a new white div on the left side.

![Screen Shot 2020-07-29 at 3 02 20 PM](https://user-images.githubusercontent.com/9310939/88850612-40838880-d1b1-11ea-8b37-8a2dbbda8109.png)

#manual-testing

**Comment by sirbrillig** [comment]
🤔  I wasn't able to reproduce this. I tried `4000000000003220` (3DS 2) and `4000002760003184` (3DS) and either way, I'm redirected to the correct thank-you page. I did once see the page you captured in the screenshot above, but I think it was just waiting for the response from Stripe because before I could take a look it transitioned to the thank-you page. Maybe there's some additional combination of factors that triggers this.

**Comment by nbloomf** [comment]
I did notice that both times I saw this behavior, the URL indicated I was being redirected to the quickstart upsell. Did you see the thank you page specifically? If so, maybe it's an issue with just the quickstart redirect.

**Comment by nbloomf** [comment]
Yep- I just verified that this happens if I'm in the `offer` variant of the `conciergeUpsellDial` A/B test, but not in the `noOffer` variant. I've updated the test instructions - good catch.

**Comment by sirbrillig** [comment]
To add some details: the redirect happens, and the URL becomes something like http://calypso.localhost:3000/checkout/offer-quickstart-session/pending/471525/example.com. If I visit that URL manually, I get a blank page with the Calypso checkout masterbar.

![Screen Shot 2020-08-03 at 12 41 48 PM](https://user-images.githubusercontent.com/2036909/89206072-b8bdc580-d586-11ea-8aa7-2007462d23cc.png)

**Comment by sirbrillig** [comment]
I confirmed that the broken URL comes directly from `getThankYouPageUrl()`, and the reason is that `pendingOrReceiptId` is `pending/471545`. This happens because `getPendingOrReceiptId()` will return `pending/${ orderId }` if the order ID is set. So, what are we actually looking at here?

There are two flows which are colliding. The normal thank-you flow (without the concierge upsell) is trying to redirect to a pending page URL like http://calypso.localhost:3000/checkout/thank-you/example.com/pending/471525. This URL ends in `pending/` followed by the _order_ id, which it will poll until it gets a receipt, after which it replaces both `pending/` and the order id with the receipt so you end up with a URL like http://calypso.localhost:3000/checkout/thank-you/example.com/19787592

Meanwhile, the concierge flow is trying to redirect to a URL like http://calypso.localhost:3000/checkout/offer-quickstart-session/19787592/example.com instead. Note that this URL requires already knowing the receipt id.

Because we try to apply both of these URLs together (a pending page with a concierge flow), we end up with an invalid URL.

**Comment by sirbrillig** [comment]
In old checkout, this bug does not occur. When checkout completes, we are redirect to the URL http://calypso.localhost:3000/checkout/thank-you/example.com/pending/471553 which shows the pending page and then replaces it with http://calypso.localhost:3000/checkout/thank-you/example.com/19787673. That is, we ignore the quickstart upsell entirely, even if we are in the abtest group.
