### ISSUE TITLE
Payments: Stop charging application fees for certain countries.

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#44553]
We recently learned, that there are countries that won't work with Payments blocks:

@kosiew has discovered that:

> Stripe doesn’t currently support application fees for platforms in US with connected accounts in MY
Platforms outside of Malaysia with connected accounts in Malaysia, collecting of cross-border application fees is not supported.

This means, that a **user from Malaysia can't sell on Payments.**

More so, the WCPay also won't work in Malaysia

1. We have to review the supported country list and warn users from Malaysia, that setting up payments won't work for them. Are there other countries that won't work? We don't know.
2. We have to contact the users from these countries and deliver sad news

**Comment by artpi** [comment]
Maybe we can make test accounts in each of the countries and test it?

**Comment by artpi** [comment]
We can also contact Stripe to get a list of countries that would give us trouble.
We do:
- a direct charge on a connected account
- using a platform account in the US
- charge a platform fee
- We store the customer on the platform account
- We share that customer to get a token before each reneawl

**Comment by artpi** [comment]
Wee seem to have the same problem in Mexico:
`Stripe doesn't currently support application fees for platforms in US with connected accounts in MX.`
Context: p1596601891435600-slack-C03TY6J1A

**Comment by artpi** [comment]
This is very relevant:

> Stripe supports separate charges and transfers in the following regions: Australia, Europe, Japan, New Zealand, and the U.S. Separate charges and transfers are supported only if both your platform and the connected account are in the same region (for example, both in Australia).

https://stripe.com/docs/connect/charges-transfers

**Comment by artpi** [comment]
More context:
pbMlHh-w5-p2

**Comment by kwight** [comment]
To get around issues regarding application fees with certain countries, we will stop charging application fees for Brazil, India, Mexico and Malaysia. See pbMlHh-w5-p2#comment-807 for a possible approach.

**Comment by mmtr** [comment]
@artpi or @kwight is there any way of faking the country of our users so we can replicate the issue? I tried purchasing a plan for a new site and entered Mexico as country in the billing address, but has been able to set up a Payments block and complete a purchase without problems.

**Comment by kwight** [comment]
> is there any way of faking the country of our users so we can replicate the issue?

My first thought would be a VPN (I think we'd have to disable proxying during setup too?).

**Comment by mmtr** [comment]
Reading through all P2s and Slack messages, the issue seems to be on **connected Stripe accounts** that are located in Brazil, India, Mexico or Malaysia. 

I guess that in order to replicate the issue, we actually need to create a Stripe account for one of those countries, rather than using a dev account (which I guess will bypass the application fee limitation?).
<img width="1411" alt="Screen Shot 2020-08-28 at 12 09 52" src="https://user-images.githubusercontent.com/1233880/91549591-768a6880-e927-11ea-9404-e4e9b7216d3c.png">

**Comment by mmtr** [comment]
> we actually need to create a Stripe account for one of those countries

Well, that's going to be hard given we need the actual details of bank account hosted in one of those countries.

**Comment by mmtr** [comment]
> My first thought would be a VPN

This actually works great, thanks for the suggestion @kwight! I had to try a few times, but found out some reliable steps to reproduce the issue:
- Set up a VPN connection to Mexico (I used [TunnelBear](https://www.tunnelbear.com/) which is easy and free to use.
- Open an incognito window (Stripe seems to remember your actual country otherwise, if you already visited the Stripe connect page).
- Sandbox the API and the store.
- Go to https://wordpress.com/earn/payments.
- Select a site which is under a paid plan.
- Disconnect Stripe if currently connected.
- Connect to Stripe and click on the "Skip this account form" link.
- Back in Earn, go to Manage payments > Collect payments.
- Create a new payment plan.
- Go to Site > Posts > Add new.
- Insert a Payments block and select the plan you created above (plans created with the previous Stripe account won't work).
- Publish the post and visit it.
- Try subscribing to the plan.
- Note the failure:
<img width="434" alt="Screen Shot 2020-08-28 at 14 04 20" src="https://user-images.githubusercontent.com/1233880/91559910-30d69b80-e939-11ea-9b55-ab79f8926a26.png">

**Comment by mmtr** [comment]
Alright, changes in D48778-code should ensure that we no longer charge fees on unsupported countries. 👀 are appreciated!
