### ISSUE TITLE
Reblog button missing unless Like button is displayed too

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#44658]
Reblog button doesn’t appear anymore unless `Show like button` is checked too in _WordPress.com > My Sites > Marketing > Sharing Buttons_. Previously it used to work.

I tested it on several simple sites and several themes and can reproduce consistently. So possibly it’s due to a recent change? Maybe https://github.com/Automattic/dotcom-manage/issues/116 one that introduced Customize buttons link below sharing buttons?

#### Steps to reproduce

1. On Simple Site go to _WordPress.com > My Sites > Marketing > Sharing Buttons_ and check `Show reblog button` and uncheck `Show like button`
2. Visit any Post/Page

#### What I expected

See `Reblog` button

#### What happened instead

No `Reblog` button shown (unless you also check `Show like button` in _WordPress.com > My Sites > Marketing > Sharing Buttons_)

#### Video

https://d.pr/v/z2yIj3

#### Context / Source

#manual-testing #user-report in 18245480-hc

**Comment by thebud15** [comment]
+1 from a recent user report

**Comment by kwight** [comment]
It's not related to the Customize link I don't think – it's in a separate container above the Likes container. This is likely the section toggle being based on that one checkbox, rather than on both.

**Comment by AtrumGeost** [comment]
Got another report here: 15448029-hc

**Comment by roo2** [comment]
I've done some investigation on this: 

Currently the reblog button is implemented as part of the jetpack Likes plugin [source]
The Likes plugin is only loaded if [`is_likes_visible`](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/likes/jetpack-likes-settings.php#L273) returns true. is_likes_visible is complex but the setting must be enabled to return true. When the plugin's javascript is loaded, the `/sites/$site_id/posts/$post_id/reblogs/mine` endpoint is called, which returns values for `can_user_reblog` ( if this is true, reblogging button is enabled and the current user can reblog the page).

So that's why this bug is occurring, the plugin isn't even loaded if the like button is disabled. 

I tried to enable the plugin if either like button is enabled OR the reblog button is enabled. Unfortunately, once enabled, the plugin does not have any way of hiding the like button. The decision for whether the like button should be hidden is in [`is_likes_visible`](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/likes/jetpack-likes-settings.php#L273). This isn't currently exposed by the API like `can_user_reblog` is.

I see a few ways forward:

1. Expose `is_likes_visible` via the API, then update the plugin to disable likes if this is the case. 
    * Difficulty: medium
    * Conceptual consistency: good, same pattern as `can_user_reblog`.
2. Use a global js variable to pass the value of `is_likes_visible` to the front end.
   * Difficulty: easy
   * Conceptual consistency: Not so good
3. Pull the code for the reblogging button outside of the likes plugin, it doesn't actually make sense to me that it should live with the like button code.
   * Difficulty: hard
   * Conceptual consistency: best

I'm leaning towards option **2.** which would be to pass the value of `is_likes_visible` to the front end via a javascript global, probably using `wp_localize_script` [as we do in the ETK](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/index.php#L66). This would fix the bug and keep this task a "Small" but isn't the nicest implementation

@p-jackson do you have any thoughts on this approach?

**Comment by arthur791004** [comment]
I agreed the 3rd one is best but not easy to do. So, I prefer the first one except exposing via the API is really too difficult to do!

**Comment by p-jackson** [comment]
I think breaking the "reblogging" feature out of the "likes" module (option 3) is a big undertaking, and would probably have product implications too i.e. the user can switch the likes module on/off in Jetpack so we'd need to migrate things if we broke it into a seperate module.

If you think of Likes (with a capital L) as the name of the module that's an umbrella module for liking and reblogging, I think option (1) makes the most sense.
Then the function would be `is_LIKES_visible()` which determines whether the features in this module should be visible. In which case we'd want to share all that logic for both liking and reblogging. We could remove the liking specific settings checks from the shared `is_LIKES_visible()` function and have it always rely on the API.

With option (2), where would the JavaScript be? Would it be somewhere on wpcom? Does that mean this bug would still exist for non-wpcom Jetpack sites?

We should probably bring in the Jetpack crew to see whether we're thinking about this the right way. @kraftbj does this assessment of the situation seem accurate? https://github.com/Automattic/wp-calypso/issues/44658#issuecomment-896516941 How would you advise tackling this?

**Comment by roo2** [comment]
@kraftbj I've got a draft fix for this up, it's basically 
* Enable the likes module if like button is displayed OR reblog button is displayed
* pass a `?hide_like_button=true` flag to the front end via the query string.

If the reblog button is disabled, and like button is enabled, `hide_like_button` would be true.

It's implemented in D65521-code and https://github.com/Automattic/jetpack/pull/20722 I've been able to test it in wpcom but haven't been able to test it on the jetpack side yet.

What do you think?

**Comment by roo2** [comment]
@p-jackson 
>With option (2), where would the JavaScript be? Would it be somewhere on wpcom? Does that mean this bug would still exist for non-wpcom Jetpack sites?

There is javascript loaded (it appears for both wpcom and non wpcom sites) from widgets.wp.com so I've updated that in  D65521-code which should also affect non-wpcom sites. I've been trying to work out how non-wpcom sites are effected and implemented a PR in jetpack, but I haven't been able to test it yet https://github.com/Automattic/jetpack/pull/20722

I found that we're currently using the query string to pass the `lang` to the front end, so it looked like using the query string here might make sense here too.

**Comment by arthur791004** [comment]
If we can ensure that this HTML would only be loaded in iframe, then I'm okay with using query string for that. Because query string might be omitted and if we don't have `hide_like_button=true` in the query string, like button will show and looks strange. Also, there is inconsistent because we have some likes data coming from `/likes` API but `hide_like_button` comes from the query string. It might be confused.

BTW, is there any concern about not to keep using `is_likes_visible` and change to `hide_like_button`?

**Comment by roo2** [comment]
> BTW, is there any concern about not to keep using is_likes_visible and change to hide_like_button?

I first thought to use `hide_like_button` because it would default to false. When it comes to deployment, `widgets.wordpress.com` will be deployed first as part of D65521-code, when this is deployed but https://github.com/Automattic/jetpack/pull/20722 has not yet been deployed, no value will be passed to the front end. Therefore `hide_like_button` will be `false` which is the same as current behavior.

**Comment by roo2** [comment]
I created an alternate approach in D66115-code by sepperating out the module level checks and the like buton checks and updating the API to return a canLike flag.

**Comment by adelineyaw** [comment]
Adding user report 4277562-zen 
I've suggested they also select 'Show like button' as a temporary solution.

**Comment by roo2** [comment]
fixed by D66115-code
