### ISSUE TITLE
Sharing Connections: Adding accounts to Twitter modal needs visual design love

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#44742]
#### Steps to reproduce

1. Starting at URL: `/marketing/sharing-buttons/[site]`
2. Add a Twitter connection
3. The modal that appears after you connect your account has some odd spacing if there is no icon associated with that account (Guessing that looks for the Gravatar associated with the email address you use for that Twitter account?) and connected accounts have an unnecessary left margin where a radio button might go if you were selecting the account for something.

<img width="1680" alt="Screen Shot 2020-08-06 at 10 26 57 AM" src="https://user-images.githubusercontent.com/2124984/89546253-61ac3080-d7d2-11ea-9339-55dc7ae9c212.png">

**Comment by twhite96** [comment]
Maybe I can work on this. Is that okay?

**Comment by twhite96** [comment]
I've started working on this. Just found where the modal is, and am poking around. Hopefully will have a fix tomorrow.

**Comment by sixhours** [comment]
Welcome @twhite96! Have at it, and don't hesitate to start a PR even if you're not sure/have questions. :)

**Comment by Christopher-Stevers** [comment]
@sixhours  looks like there hasn't been any work on this issue for awhile, can I pick it up?

**Comment by sixhours** [comment]
@Christopher-Stevers Go for it! :)

**Comment by Christopher-Stevers** [comment]
@sixhours  I was looking for new issues and I realized this issue was never closed. My pull request [Sharing: Improve Twitter modal visual design. #54537](https://github.com/Automattic/wp-calypso/pull/54537) should close it . If not, what else needs to be addressed? If it does close it, do you have any other issues I could work on? I can work on CSS and React related issues. I don't have any subscriptions to WordPress though, so I'm not able to work on anything that requires testing with a paid account.

**Comment by sixhours** [comment]
You're right, looks like this can be closed; thanks @Christopher-Stevers !

Your best bet for finding new issues to work on is probably under the Bug label: https://github.com/Automattic/wp-calypso/issues?q=is%3Aissue+is%3Aopen+label%3A%22%5BType%5D+Bug%22 

There's plenty to choose from and many won't need a premium/paid account to test (but we can always test for you if it does!)
