### ISSUE TITLE
Domains: Clicking Payment Settings throws an error

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#4491]
Props to @stephanethomas for noticing this.

When you click `Payment Settings` button on `Domain Edit` page, you get an error:

![image](https://cloud.githubusercontent.com/assets/991022/14222620/77bb8d1a-f827-11e5-9f9c-034eb587fdcd.png)

After serious bisecting, I've found this to be introduced in #3890, with cbc9e9a.

It seems the error is caused when we click the link on Purchases, it clears the `selectedSite` prop, hence setting `domains` prop to `null`. What I don't understand is once we change the link, that component doesn't need to render at all, but I'm not sure why that happens. The changes were not directly related to this, but I'm guessing it could be something related to `connect`?

/cc: @drewblaisdell @Tug @stephanethomas

**Comment by drewblaisdell** [comment]
When switching from `/domains/manage/:domain/edit/:site` to `/purchases`, the selected site is set to `false` for before `DomainManagement.Edit` is replaced with `PurchasesList`. `sites-list` is an event emitter that we use with `data-observe`, so as soon as it updates, we force a render on the components that observe it. This means that, for a single render, `sites-list` will be `false`.

I'm not entirely sure why this wouldn't have been an issue before using `connect` though, because it has come up in domain management (and other sections of Calypso) before.

`DomainManagementData`, which provides` domains` to `DomainManagement.Edit`, is [explicit about passing a null `domains` prop](https://github.com/Automattic/wp-calypso/blob/master/client/components/data/domain-management/index.jsx#L28) if the selected site isn't present. Because of this, `DomainManagement.Edit` should probably work without that prop. A simple solution we've used before is to bail at the top of its render() if that prop isn't available.

**Comment by umurkontaci** [comment]
Yeah, that's pretty much parallel with my initial thoughts. I thought about fixing it with letting it work without a prop, but I wanted to know the root cause and if possible fix it there.

Quick question: Do you know what do we pass for `domains` prop when the data isn't ready? Because we do have a placeholder that's working properly.

**Comment by drewblaisdell** [comment]
<img width="687" alt="screen shot 2016-04-01 at 5 06 57 pm" src="https://cloud.githubusercontent.com/assets/1130674/14222952/9f2b4a0c-f82c-11e5-8a12-d565c0b511c0.png">

`DomainManagement.Edit` will only mount when the sites have been fetched or are in local storage, so the domains are fetched as soon as `DomainManagementData` is mounted. The screenshot is a log from the top of the `DomainManagement.Edit` render().
