### ISSUE TITLE
Earn: Confusing copy after Stripe is connected

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#45018]
Reported by @lauac in p58i-9k2-p2 #comment-47323.

The message displayed after the Stripe connection is set up contains a confusing "Close this window" term that can lead users to close the browser window, and then open a new tab, reload WordPress.com and go back into posts.

![image](https://user-images.githubusercontent.com/1233880/90608292-adaf9a00-e202-11ea-992e-0cb0d55bec2b.png)

I think we can simplify the message to just "Congrats! Your site is now connected to Stripe. You can add now your first payment plan".

**Comment by sixhours** [comment]
It looks like this was fixed when we started sending folks back to the editor after Stripe connection, rather than to the `/earn` screen:

<img width="1400" alt="Screen Shot 2020-10-06 at 3 11 52 PM" src="https://user-images.githubusercontent.com/2124984/95249872-57fd7400-07e7-11eb-81c4-d22012f639e1.png">

I think we can remove the code for that notice now, since we get a Gutenberg notice instead. Will open a PR to do that.

**Comment by mmtr** [comment]
> It looks like this was fixed when we started sending folks back to the editor after Stripe connection

You can also setup the Stripe connection from "Tools > Earn > Collect payments" (`wordpress.com/earn/payments/:site`) and in that case we redirect back to Earn.
