### ISSUE TITLE
Embeds: Spotify song and Apple music not working

### ISSUE THREAD

**Issue by LauraSWP** [Automattic/wp-calypso#45057]
### Steps to reproduce

1. Try to embed a Spotify song using the sharing url
2. Get the error:
![image](https://user-images.githubusercontent.com/63611065/90767972-54249980-e2ee-11ea-859f-6a4fe78cc247.png)

 Same with Apple music.

AT Site

#### What I expected

1. Add the Spotify song URL using the Spotify block.
2. It embeds the song.

It works if you use the shortcode [spotify url]

Reported here: 23447109-hc

**Comment by serabi** [comment]
Also reported on 21647038-hc - provided shortcode as a workaround.

**Comment by carladoria** [comment]
Also reported on 23499554-hc with Spotify, provided shortcode workaround too

**Comment by jjchrisdiehl** [comment]
Here too

hc - 23499816
hc - 23026158

**Comment by RealCarFax** [comment]
I encountered this issue here as well: #4588674-hc

**Comment by khristiansnyder** [comment]
Encountered in 23503891-hc

**Comment by retnonindya** [comment]
User report here: 23513861-hc

**Comment by chaitanyamsv** [comment]
23568288-hc

**Comment by formosattic** [comment]
20589304-hc

**Comment by KokkieH** [comment]
This is an issue on Spotify's end. It's happening in Core as well, and someone on that end has reached out to Spotify: https://github.com/WordPress/gutenberg/issues/24737#issuecomment-678705117

**Comment by KokkieH** [comment]
This is working again on Core, and it's also working for me on WordPress.com, but with a caveat: I still see the error in the block in the editor, but when I preview/publish the post, the embed is working fine.

**Comment by philnick206** [comment]
Reported here: 3247832-zen

Asking for confirmation that it's working again now.

**Comment by serabi** [comment]
Reported here: 3247787-zen 

I'll let them know it should be working once they publish, and ask for confirmation.

**Comment by edequalsawesome** [comment]
Reported here: #3249125-zen

Let them know it should work when published, asked for confirmation.

**Comment by tjcafferkey** [comment]
Having looked into this issue, here is what we know so far:

- This error only occurs if the website has no posts.
- This only happens on DOTCOM, and not DOTORG.

The reason behind this is because, when we use oEmbed to fetch the data for the URL inputted we need to use a post ID to cache this response against. It’s probably worth mentioning it doesn’t look like it cares if the post we’re editing and the post ID we are using to cache it against match, it just picks the first post from the result of `get_posts()` and uses that (although I could be wrong here) in order to generate a `$cachekey`. In the scenario where we currently have no posts (thus no post ID) on DOTCOM, and we click “Add new post” for the first time it and it has not autosaved we don’t have a database entry for this newly created post yet (thus still no post ID).

[One approach we looked at](https://code.a8c.com/D49028) was to fabricate a post with an ID of 1 when we find ourselves without any posts. When reviewed by people with more experience in this codebase it wasn’t looked upon as a favourable approach and was seen as ‘dirty’. This is something we agree with, it’s not an elegant solution and definitely feels like a hack. We did try a few things here such as passing a `post_status => 'any'` argument to `get_posts()` just in case it was defaulting to published/public posts only, but to no avail.

Another approach we investigated was in Gutenberg. In here we looked into the possibility that when the user clicks “Embed”, we check if there are any posts, if there are none then we trigger an autosave which then creates an entry with a status of “draft” and in turn giving us a post ID to cache against. Again, this did not feel like the right place to implement any changes on the basis that it is not Gutenbergs responsibility to make sure there are the appropriate database records available (as this only happens in DOTCOM).

It looks like we have found ourselves using a posts ID in a scenario where no post ID exists yet as far as I can tell. Ideally, it would be nice to either:

1. Ensure the post is created as a draft, thus giving us a post ID.
2. Being able to generate an ID ourselves for the purpose of caching against. Baring in mind this only occurs when a user has zero posts available.
3. We ditch caching in this scenario.

**Comment by ockham** [comment]
Thanks @tjcafferkey for this thorough analysis!

Having read the above, I agree that we should not try to hack our way around this issue. I have one question that I couldn't find an obvious answer for in your comment: What does dotcom do differently from dotorg, if the embeds _are_ working on the latter? It seems like the 'right' solution needs to somehow address that difference.

Furthermore, since the caching mechanism is the same for all oEmbeds (AFAIK) -- is this issue also present for the other ones?

**Comment by nerdysandy** [comment]
I can't replicate it anymore. I embedded a spotify URL using Spotify block. It didn't throw any error and embedded the song as expected. I tested this on AT site as mentioned in the original report too.
