### ISSUE TITLE
Notifications: Column Blocks aren't properly processed

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/wp-calypso#45116]
#### Notes:
**This affects Post and Comment notifications.** Detailing steps below

**PLUS** Email Notifications are also affected, for both scenarios.

#### Scenario: Post Notification
1. Add a new Post
2. Insert a columns block
3. Add content to each row
4. Mention a 2nd user

#### Scenario: Comment Notification
1. Add a new Comment
2. Insert a columns block
3. Add content to each row
4. Mention a 2nd user

#### What I expected
The Post Notification received by the second user should  properly display its contents in columns

#### What happened instead
Content isn't laid out in columns

#### Browser / OS version
Chrome 84.0.4147.135, macOS Catalina 15.6

#### Screenshot / Video
<img width="300" alt="Screen Shot 2020-08-21 at 15 13 30" src="https://user-images.githubusercontent.com/1195260/90921588-e72e0400-e3c0-11ea-897e-fd65509daec7.png">

#### Context / Source
Sample content below!

```
<!-- wp:heading -->
<h2>Layout: 50/50</h2>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>50/50 Left | BLA BLA BLA BLA</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>50/50 Right| BLA BLA BLA BLA</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by kwight** [comment]
For reference, this is the editor view:

<img width="770" alt="Screen Shot 2020-09-28 at 10 40 28 AM" src="https://user-images.githubusercontent.com/349751/94467749-3ad9fd00-0178-11eb-8326-f58d61e00a4a.png">

I guess there could be an argument for maintaining two columns in the notification, but not anything above that – @sixhours what do you think of showing two columns? Is everything better left as a single column? The current fixed width for a notif allows 400px of content; would ~180px for a column be enough?

**Comment by blackjackkent** [comment]
I actually just came here to leave the exact same comment @kwight . I've been looking into this and #45135, and for both of them, it seems like the content is all being returned from the server in full, so this is purely a styling issue and strikes me a little bit like how we would discuss rendering a multi-column layout in a mobile view (even more so since 400px is probably less than is available in most mobile layouts). 

I'm inclined to say that single column would give a better user experience but definitely we need @sixhours input.

**Comment by sixhours** [comment]
Agreed, we should do what we'd usually do with content displayed on a 400px screen, since columns can be 2+ (and it would be a tight fit with even 2). I seem to remember Kirk suggesting using a mobile-friendly layout for notifications in one of the summary posts for working with block styles. I'm all for single-column displays here.
