### ISSUE TITLE
Hide Homepage Title in Customizer Makes Homepage Title Uneditable

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#45127]
#### Steps to reproduce

1. Activate a new theme (Redhill to Twenty Twenty)
2. Set a static homepage. Name it whatever you'd like.
3. Under Design - Customize - Homepage Settings, check the Hide Homepage Title box. Save Changes.
4. Under Site - Pages, visit your homepage, and try to change the title.
5. It's not possible. 

To change the page title, you'd need to go back to the customizer, show the page title, save, go back to the editor, refresh, change the page title, save, go back to the Customizer, hide it again, save. 

Discovered this because a user was sharing the page on Twitter, and the Twitter card would only show "Home" as the site's title. To edit this, they needed to change the page title, which seemed much more involved than it should have been. 

#### What I expected
The page title to be able to be edited, regardless of the Customizer setting that hides it on the front end. 

#### What happened instead
There are multiple additional steps, and an unnecessary trip to the Customizer to edit a page title.

#### Browser / OS version
All.

#### Screenshot / Video
Editor with hidden page title in Customizer
![image](https://user-images.githubusercontent.com/30731356/90929148-0753c800-e3ad-11ea-8bf6-ad7d5f308ce5.png)

Editor without hidden page title in Customizer
![image](https://user-images.githubusercontent.com/30731356/90929278-46821900-e3ad-11ea-9cea-f3b2c84b8f66.png)

#### Context / Source

#user-report

**Comment by yansern** [comment]
**Showing the post title again**

When homepage title is hidden, the `hide-homepage-title` css classname is added to the admin body class. The post title input field is still rendered, just hidden with `display: none`.

The function `admin_body_classes()` inside `apps/editing-toolkit/editing-toolkit-plugin/common/index.php` adds this classname after looking up the config key `hide_front_page_title`. 

Quick fix will be just as simple as removing the css styles `apps/editing-toolkit/editing-toolkit-plugin/common/index.scss`.

**Adding a small note to avoid confusion?**

While this fixes the pain point of not being able to edit page title of homepage, it introduces another issue where user may click on Preview but then asks why is it that the site homepage title is missing (because user may not know or have forgotten that they have set to hide the homepage title).

One solution I can I think of is when the post title input field is in focus, show a small note under it that informs the user that the post title will not be shown because user has set to hide the homepage title.

However, as the post title input field comes from gutenberg core, we would need to do some kind of DOM injection just to insert the that small note from Editing Toolkit plugin. And this feels really hacky, especially that small note might be removed upon any potential react re-rerendering (not sure about that).

Another way is to inject using the `:after { content: '' }` CSS pseudo-selector, but translation strings can exists in CSS, unless it is a CSS rule that's injected via JS.

**What to avoid looking into:**

Inside `apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php`, the config key `hide_front_page_title` is retrieved on the server-side and passed back as `hideFrontPageTitle` on the client side. Any scripts on client side that uses `hideFrontPageTitle` is irrelevant to the post title input field, it is just to determine how to generate page previews.

**Comment by annbingle** [comment]
HI there! 

I have kind of the same issue for the user's site but since they are using the old them Edin, it doesn't have the box for  "Hide Homepage Title" on their Customizer. So far, what happens is when their page is set as the Homepage, the page title on the Editor in Calypso is not showing up. No issue when the page is opened in WP Admin.

[3660471-zd](https://woothemes.zendesk.com/agent/tickets/3660471)

**Comment by ianstewart** [comment]
cc @scruffian

**Comment by p-jackson** [comment]
This has moved to the theme dev board, so moving off the maintenance board

**Comment by scosgro** [comment]
Popped up again in 24867064-hc

**Comment by tbradsha** [comment]
27487083-hc
