### ISSUE TITLE
Notifications: Layout-grid block is missing in post notification 

### ISSUE THREAD

**Issue by yaelirub** [Automattic/wp-calypso#45135]
#### Steps to reproduce

1. Follow a site.
2. Publish a post with a code block to the site in Step 0.
3. Open the Notifications panel.
4. Click the notification for the post in Step 1.
5. Notice the layout grid block is missing 

#### What I expected

I expected to see the block

#### What happened instead
I can't see the Layout-grid block 

#### Browser / OS version

Chrome / Safari (latest)

### How it appears in my post

<img width="1426" alt="Screen Shot 2020-08-21 at 4 35 24 PM" src="https://user-images.githubusercontent.com/1335657/90943193-a7b9e480-e3cd-11ea-8c18-57d428d1ad89.png">''

### How it appears in notification 
<img width="417" alt="Screen Shot 2020-08-21 at 4 35 16 PM" src="https://user-images.githubusercontent.com/1335657/90943218-d89a1980-e3cd-11ea-9cba-e0df175dcd39.png">

**Comment by kwight** [comment]
@yaelirub Looking at the images, it seems like the layout block markup didn't make it into your notif at all – was that what you meant by "missing" (as opposed to the layout being removed, but the content being there)?

I'm seeing Layout Grid content myself in notifs; it's stacked as a single column, but this is considered desirable because of the notifications' fixed width of only 400px.

Front-End | Notification
--- | ---
<img width="479" alt="Screen Shot 2020-09-28 at 12 54 29 PM" src="https://user-images.githubusercontent.com/349751/94479558-d3c54400-0189-11eb-88cb-035ab529a49e.png"> | <img width="479" alt="Screen Shot 2020-09-28 at 12 50 49 PM" src="https://user-images.githubusercontent.com/349751/94479567-d9bb2500-0189-11eb-9bf7-f9ebd750cfe3.png">

**Comment by yaelirub** [comment]
Hey @kwight , thanks for looking into this! 
>it seems like the layout block markup didn't make it into your notif at all – was that what you meant by "missing" 

Yes, it didn't make it at all

**Comment by kwight** [comment]
> Yes, it didn't make it at all

Ah OK, good, a few of us have confirmed it's working fine now, so I'll close. Just reopen if it comes up again, thanks! 👍
