### ISSUE TITLE
Image Block Does Not Appear Under Search Term "Image" When Adding a New Block

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#45136]
#### Steps to reproduce

1. Create a new page
2. Click the + to add a block
3. Search for Image
4. The Image Block does not appear. Instead, it gives options for Gif, Image Compare, Latest Instagram Posts, Slideshow, Tiled Gallery, Story.
5. Search for Media 
6. Image is the 5th option, Gallery the 6th. 

#### What I expected
The Image Block to show up when you search for Image.

#### What happened instead
The Image Block doesn't appear when you search for "Image."
#### Browser / OS version
All

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/30731356/90944094-bf936780-e3d1-11ea-9b6e-333e4072f0ea.png)

#### Context / Source
#flowsharing #painpoint

**Comment by sirreal** [comment]
This is the expected behavior for Gutenberg at this time. Any proposals and changes should happen in the Gutenberg project.

Searches are sorted based on [_frecency_](https://en.wikipedia.org/wiki/Frecency). Depending on usage, you may get different results. I tested this and get these results:

**Image**

![Screen Shot 2020-08-24 at 11 23 08](https://user-images.githubusercontent.com/841763/91028545-ea620380-e5fd-11ea-8ad0-fc20f6cbbb76.png)

**Video**

![Screen Shot 2020-08-24 at 11 23 19](https://user-images.githubusercontent.com/841763/91028566-f352d500-e5fd-11ea-8891-750258aa56be.png)

These are exactly the results I'd expect.

This is very much dependent on a user's behavior and the inserter is behaving as expected. I do agree that the results could be better when the search term is very close to the name of a specific block. For example, blocks could be weighted by [edit distance](https://en.wikipedia.org/wiki/Edit_distance#Types_of_edit_distance). It's a conversation that needs to happen in the core Gutenberg project.

*Note: In your screenshot there's an additional block _Story (beta)_ that's not available in production.


> […] I find it frustrating when I type `/image` and press enter only to create a GIF block :)

@rfaile313 That's another issue, the [Slash Inserter](https://github.com/WordPress/gutenberg/blob/0679889fab45ef834a4bef82a20c0f0a4192b7ac/packages/block-editor/src/autocompleters/block.js#L47) is different from the [Quick Inserter](https://github.com/WordPress/gutenberg/blob/0679889fab45ef834a4bef82a20c0f0a4192b7ac/packages/block-editor/src/components/inserter/quick-inserter.js#L54-L61) mentioned in the description. Again, this is a conversation that needs to happen in the Gutenberg project. I find it odd that it doesn't use the same sorting as the quick inserter. The slash inserter would likely benefit from the same sort of weighting I mentioned above.

I folks would like to [raise these feature requests in Gutenberg](https://github.com/WordPress/gutenberg/issues/new?template=Feature_request.md), they're welcome to, please link here. If not, @Automattic/good-mountain will create issues for the quick inserter and slash inserter in the next couple of days.

**Comment by sirreal** [comment]
This should be addressed in Gutenberg 9 by https://github.com/WordPress/gutenberg/pull/25105

**Comment by fullofcaffeine** [comment]
The problem does seem to be fixed. I cleared the localstorage data for my simple test site (unsandboxed, running GB 9), and both "Image" and "Video" appears as the first item in the first row in the quick inserter (main editor or layout column).
