### ISSUE TITLE
Block editor: Accessibility issues with wpcom page/post navigation sidebar

### ISSUE THREAD

**Issue by olaolusoga** [Automattic/wp-calypso#45239]
## Description

Customer raised issue with current sidebars accessibility.

Feedback from customer:
When I am on the editing page for a blog post I don't see any links or way to get back to the dashboard like I use to... So what I have to do is go back to the dashboard the long way and select preview from there. It a lot of extra steps and time. Please let someone know to fix this because it use to work with my screen readr.

## Expected

We need to adjust a few things to make the sidebar more accessible. Below are a list of adjustments:

1. For the W button: add an aria-label that describes what the button is for. Button when closed should read "Open sidebar", when W button is open it should read "You are viewing sidebar. To close select "esc".
2. When a person open the sidebar, move :focus to the "View all pages" item. Aria-label should read: "View all pages in Dashboard" 
4. Look at https://www.w3.org/TR/wai-aria-practices/#dialog_modal for the correct implementation of role="dialog"
5. Use an h2 instead of a div for the “Posts” heading

cc: @enriquesanchez for guidance

**Comment by autumnfjeld** [comment]
Thanks for this @olaolusoga! I will start working on these accessibility fixes.

**Comment by enriquesanchez** [comment]
Happy to help test when these updates are ready 👍

**Comment by p-jackson** [comment]
> When a person open the sidebar, move :focus to the "View all pages" item

I don't fully agree with this. I'm worried that trying to be too clever with where to auto focus will further disorient the user. The ARIA guidance says this about setting the initial focus:

> Unless a condition where doing otherwise is advisable, focus is initially set on the first focusable element.

It does list exceptions to this rule, but they don't apply here imo.

So if "the top of the dialog" is where users would expect the focus to be, then I think that's where we should put it. In our case that means it'd be on the "close dialog" button (which is the (W) button). The first time the user opens the dialog they'd also have the advantage of seeing the content from the top, including any descriptions of the modal we put in for screen readers.

@enriquesanchez @olaolusoga

**Comment by autumnfjeld** [comment]
I'll wait for further input on Philip's comments above before pursuing further work on 
> move :focus to the "View all pages" item.
(Had quite a learning curve in trying to put the focus on the "View all pages" link, which at this moment I still have not figured out).

**Comment by enriquesanchez** [comment]
Because the W button acts as a toggle, I think focus can stay in the W button. This should also happen when you close the dialog:

>When a dialog closes, focus returns to the element that invoked the dialog

--- 

We should also add the appropriate ARIA state for the toggle button. From https://www.w3.org/TR/wai-aria-practices/#button:

>Toggle button: A two-state button that can be either off (not pressed) or on (pressed). To tell assistive technologies that a button is a toggle button, specify a value for the attribute [aria-pressed](https://www.w3.org/TR/wai-aria-1.1/#aria-pressed).

>The first time the user opens the dialog they'd also have the advantage of seeing the content from the top, including any descriptions of the modal we put in for screen readers.

A little clarification here: keyboard navigation and screen-reader navigation are not the same thing. While there may be times where there is some overlap, usually screen-readers users have a set of commands and shortcuts they use to navigate a page. So even if the first focusable item were not to be the upmost element in the dialog, a screen-reader user will still be able to consume the full content of the dialog.

**Comment by p-jackson** [comment]
> Because the W button acts as a toggle, I think focus can stay in the W button

> We should also add the appropriate ARIA state for the toggle button.

The thing is that in the markup it's not a toggle button, the close button is a second button that's inside the sidebar, and the sidebar is on top of the header and everything else. The reason it has to be a seperate button (and so can't be a toggle) is because focus has to be constrained to the sidebar, so the close button has to be _inside_ the sidebar. But the button to open the sidebar has to be in the header so _can't_ be inside the sidebar.

In the markup it's actually a pretty vanilla modal dialog, it's just styled to appear on the left instead of the centre of the page.

---

> A little clarification here: keyboard navigation and screen-reader navigation are not the same thing. While there may be times where there is some overlap, usually screen-readers users have a set of commands and shortcuts they use to navigate a page. So even if the first focusable item were not to be the upmost element in the dialog, a screen-reader user will still be able to consume the full content of the dialog.

Ah yes. I was thinking that maybe we should follow the example of the [Verify Address example modal on this page](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html). It's also a large modal that potentially scrolls. But now that I think of it, our case is different. In the Verify Address example the first focusable element in the dialog might be scrolled out of view. But in the sidebar the first focusable element would be near the top.

**Comment by enriquesanchez** [comment]
>The thing is that in the markup it's not a toggle button, the close button is a second button that's inside the sidebar, and the sidebar is on top of the header and everything else. 

@p-jackson Ah, thanks for clarifying that. I think what we should do then for the W button that expands the dialog is to follow a similar pattern to what we are already using for the editor Settings sidebar:

<img width="346" alt="Screen Shot 2020-09-01 at 11 31 34" src="https://user-images.githubusercontent.com/3276087/91881170-b3679f80-ec46-11ea-8dea-9e0f07d882f5.png">

We use `aria-expanded="true"` [to communicate that the dialog has expanded](https://www.w3.org/WAI/GL/wiki/Using_aria-expanded_to_indicate_the_state_of_a_collapsible_element). 

What we're not doing in the editor's sidebar and I think we should test here is adding `aria-haspopup="dialog"` [to communicate that a dialog will open](https://www.w3.org/TR/wai-aria/#aria-haspopup). The spec also suggests using `aria-controls` [to establish the relationship between the button and the dialog](https://www.w3.org/TR/wai-aria-1.1/#aria-controls).

**Comment by p-jackson** [comment]
Sounds good! I'll makes those changes in another PR. We're also not correctly returning the focus to the original control after closing the sidebar either, so I'll fix that up too.

`aria-controls` sounds cool. I don't think it'll work in our situation because the dialog's not present in the DOM until it's open so can't be referred to with an ID. But I'll read up and see if it's possible.

**Comment by ramonjd** [comment]
This is a bit stale. Let's open a new issue if further work needs to be done to improve accessibility for the sidebar.
