### ISSUE TITLE
Block editor: Updated design for wpcom page/post navigation sidebar

### ISSUE THREAD

**Issue by olaolusoga** [Automattic/wp-calypso#45240]
## Description

With the MVP out the door, we need to do a second pass on the design of the sidebar. Some reasons we need an update:

- The MVP design was created as a baseline in order to get something out the door. The pln was to circle back, and update as more design refinements are made.
- Since the MVP, we've cleaned up the sidebar design, removing unnecessary components, and improving the information information architecture

Note: the sidebar design conversation is still going on in core. To navigate past the conversation, we're pulling pieces that have value for the patch we have in place at the moment on dotcom (this should deprecate once FSE lands). Also, this issue dovetails with the [accessibility updates](https://github.com/Automattic/wp-calypso/issues/45239) a customer reported—we should try and update both around the same time.

## Expected

**Before**
<img width="1792" alt="Screen Shot 2020-08-26 at 10 45 19 PM" src="https://user-images.githubusercontent.com/1382943/91378238-f3b1c280-e7ed-11ea-8a3d-498d6124e3ca.png">

**After**
<img width="1440" alt="dotcom-sidebar-adjustments2" src="https://user-images.githubusercontent.com/1382943/91378164-c49b5100-e7ed-11ea-85be-55d3b03b521f.png">

Adjustments:
- Move site title next to W
- Get rid of "view site"
- Change arrow next to "View page/post" to "<" icon (it should be post or page depending on editor context)
- Fix bottom and relabel "add new page/post" to  "Create new page/post" (it should be post or page depending on editor context)
- break links into three groups: currently editing, recently opened, drafts
- with "draft" grouping, we should get rid of "draft" tag visual

**Comment by autumnfjeld** [comment]
@ramonjd If "view site" is being removed, then my concerns about the difficulty of turning `<ExternalLink />` into a `<Button />` are irrelevant. https://github.com/Automattic/wp-calypso/blob/66698207f61ab27c60a941ffd38d3760bc2639cd/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx#L210

In the bigger picture of attempting/thinking about turning all `<a />` into `<button>` in the sidenav: at the moment I'm still leaning toward educating the user on how to turn on tab navigation in Safari & Firefox, rather than changing our markup to get around a setting the user simply needs to set.

**Comment by ramonjd** [comment]
> If "view site" is being removed, then my concerns about the difficulty of turning <ExternalLink /> into a <Button /> are irrelevant.

👍 

> at the moment I'm still leaning toward educating the user on how to turn on tab navigation in Safari & Firefox, rather than changing our markup to get around a setting the user simply needs to set.

No problems. I see where you're coming from. Posted a reply over at the issue: https://github.com/Automattic/wp-calypso/issues/43972

**Comment by ramonjd** [comment]
Some questions:

1. We might get some long site titles. E.g.,

<img width="304" alt="Screen Shot 2020-08-27 at 7 36 24 pm" src="https://user-images.githubusercontent.com/6458278/91424050-ab051280-e89c-11ea-8a95-27165c60337c.png">

Any ideas on how to deal with these given the header's light background colour?

2. I'd propose changing "Recently opened" to "Recently edited" for a true description of the list since the query to get the posts looks at the last modified date.

3. I see we're removing the status labels. Should we keep one for scheduled posts? E.g.,

<img width="299" alt="Screen Shot 2020-08-27 at 7 39 32 pm" src="https://user-images.githubusercontent.com/6458278/91424386-10f19a00-e89d-11ea-8257-caad76057527.png">

**Comment by p-jackson** [comment]
@olaolusoga I really like using the headings instead of the labels to indicate whether something's a draft. Especially how it more clearly shows which is currently being edited.

The contrast of the list items is pretty low. I was surprised to see that it actually does conform to the WCAG AA guidelines, but personally I find it a little hard to read.

**Comment by ramonjd** [comment]
>  really like using the headings instead of the labels to indicate whether something's a draft

I kept them in for now for the same reason... until further notice :)
