### ISSUE TITLE
Premium Content: iPhone subscribers cannot log in to see content.

### ISSUE THREAD

**Issue by robfelty** [Automattic/wp-calypso#45470]
Some Premium Content subscribers are reporting problems logging in on iPhones to be able to see their premium content.

See: 3295186-zd-woothemes

**Comment by robfelty** [comment]
cc @kwight

**Comment by kwight** [comment]
@robfelty Looking at the chats again, it seems like the remaining issue the OP has is iPhone users, so I've updated the description again.

**Comment by gwensmithx** [comment]
Hi all! Just wondering if I can get a status update on this?

**Comment by kwight** [comment]
@gwensmithx It's still on the board, but having a hard time getting to it with resources right now. No ETA, I'm afraid.

**Comment by pauljacobson** [comment]
For the sake of keeping track of incidents of this issue, we also have a report in 3370120-zen

**Comment by nerdysandy** [comment]
#24706659-hc reported that their users can't access Premium content on Chrome/Edge. I wonder if we should change the title for this issue?

**Comment by wprhunt** [comment]
#24706659-hc An update on nerdysandy's customer that came back in to report that their customer only had issues with Edge and that the browser was reporting security errors when trying to access that premium content. They tested resigning up and found only Edge was preventing access to their customer. Followup on #3370120-zd

**Comment by kwight** [comment]
This is still valid as far as I know – perhaps it's related to Safari third-party cookies.

**Comment by aneeshd16** [comment]
I tried to reproduce this issue on a test site, and as per my findings, the Premium Content block does not require third-party cookies to show subscriber-only content. The above reports seem to be for the same site. Are there any other reports of this bug? Having more examples will make this easier to debug.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on iPhone 14 iOS 16.5.1 Safari browser with the Paid Content blocks on a simple site. 
     - Browser has `Prevent Cross-Site Tracking` enabled
     - Browser has `Block All Cookies` disabled
- No issues logging in or subscribing. 

📌 ACTIONS
- It's been a long time since this had reports or activity, and the Premium Content blocks have recently undergone quite a bit of work.
- Closing as no longer relevant/not reproducible
