### ISSUE TITLE
Hosting: support card missing HE avatars

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#45507]
![image](https://user-images.githubusercontent.com/437258/92616821-ad983c80-f28c-11ea-909f-725d14281ffe.png)

I just noticed that the HE avatars aren't loading there, I'm not sure why or what changed.

**Comment by sixhours** [comment]
This appears to be a server-side issue because it's happening in /devdocs and anywhere else we'd display the array of HE Gravatars; the API returns an empty array.

Pinging @westi since it looks like he last edited the server-side file; I don't think his changes are responsible, but I'm not sure who else to ping. :)

**Comment by sixhours** [comment]
This was fixed in D50767-code
