### ISSUE TITLE
Purchases: Update success notice for renewals paid with credits

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#4554]
This is what I see when I renew my premium plan on WordPress.com

<img width="712" alt="screen shot 2016-04-06 at 10 38 14 am" src="https://cloud.githubusercontent.com/assets/1464705/14326749/3f888f72-fbe4-11e5-991c-64cfc9b399fd.png">

Two issues I see with this that make it confusing.
1. The success message says that the plan will "auto renew", but the message in blue says that "it will expire and be removed from my site in a year". These messages conflict.
2. Do I need the information message and renew link when the expiry is 12 months away? I think inside of three months would make more sense. Otherwise I don't think there's a need to show this.

/cc @fabianapsimoes

**Comment by fabianapsimoes** [comment]
> The success message says that the plan will "auto renew", but the message in blue says that "it will expire and be removed from my site in a year". These messages conflict.

Hm, I'm unable to reproduce this. This is what I see when I renew an unsubscribed purchase:

![screenshot-wordpress com 2016-04-07 12-36-07](https://cloud.githubusercontent.com/assets/1248436/14348526/6085d9da-fcbd-11e5-84f7-2cac45e423cc.png)

Did you renew with credits by any chance? If that's the case, because of the lack of payment method, we're not able to switch the purchase to subscribed (which is what we do when we renew unsubscribed purchases). That blue notice is only displayed for unsubscribed purchases.

If that's what happened, what we can do is update the notice to not refer to auto renewal when there's no payment method attached to the purchase.

> Do I need the information message and renew link when the expiry is 12 months away? I think inside of three months would make more sense. Otherwise I don't think there's a need to show this.

There's an open issue for this: https://github.com/Automattic/wp-calypso/issues/732

**Comment by apeatling** [comment]
Yes -- renewed with credits.

**Comment by fabianapsimoes** [comment]
OK, so we should update the green notice and make sure it doesn't mention auto-renewal if we were unable to switch the purchase to subscribed.

cc @mikeshelton1503 for copy.
