### ISSUE TITLE
PDF file upload failure error message in Block Editor

### ISSUE THREAD

**Issue by nancyhuihuiyu** [Automattic/wp-calypso#45600]
#### Steps to reproduce

1. Starting at URL: +hrp2

#### What I expected

To upload the PDF file successfully. PDF size: 3.8M

#### What happened instead

Got the following error message in the Block Editor, and the file didn't show up in the dashboard.

<img width="746" alt="Screen Shot 2020-09-11 at 4 15 52 PM" src="https://user-images.githubusercontent.com/36929963/92980247-40320a80-f44a-11ea-8264-f147289e64dd.png">

However, in the wp-admin editor, I can see it's uploaded already:

<img width="740" alt="Screen Shot 2020-09-11 at 10 08 53 AM" src="https://user-images.githubusercontent.com/36929963/92980294-68ba0480-f44a-11ea-80e4-26a24717b02c.png">

#### Browser / OS version

Chrome / macOS Catalina Version 10.15.6

#### Screenshot / Video

See above

**Comment by yansern** [comment]
This issue is no longer replicable. Tested with various PDF file sizes on both +h2p2 and other simple WP sites.

I looked up commit history of relevant files on both Calypso and WPCOM to see if there were any fixes done related to this but to no avail.

If network response error was captured at the time this issue it would help to give a better picture what went wrong at that time.

For now I will close this issue.
