### ISSUE TITLE
Localize Support URL for HSTS Tooltip in Domain Picker

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#45610]
#### Background

When users are presented with domain suggestions for domains that require HSTS (.dev TLDs for example) they are presented with tooltip which reveals information about this including a link to a support URL for more information on the topic.

![Screenshot on 2020-09-14 at 08-55-55](https://user-images.githubusercontent.com/8639742/93059099-2837d200-f668-11ea-9a69-042af0ff7719.png)

#### What needs to be done

The `/support/https-ssl` in the component below needs to be localized.

https://github.com/Automattic/wp-calypso/blob/4c56241965ca1e996c6ac8375566142b4709519d/packages/domain-picker/src/domain-picker/suggestion-item.tsx#L101-L107

**Comment by Aurorum** [comment]
From https://github.com/Automattic/wp-calypso/pull/40080#issuecomment-599105095:

> The principle to keep in mind for WordPress.com hosted help articles — meaning written by Automattic on our support sites — is to keep the entire experience within the Calypso app context. Please use the mechanism that already exists to show the article in an overlay first. That overlay could then link to open the full help article in a new tab/window.

@lancewillett out of curiosity, would the same principle apply to links within a pop-up, such as the one in this issue? I believe that the link could be swapped for the Support Article Dialog along with being localised.

**Comment by lancewillett** [comment]
Handing the baton to @rickybanister to help answer your question, @Aurorum (I miss you all wonderful people, I'm working on Tumblr product experience these days!)

**Comment by rickybanister** [comment]
@Aurorum that's a good point and I think it would be an appropriate UX to avoid popping folks over to a new browser tab etc.

I'm not sure, however, whether we have access to the support article dialog component within this onboarding context. I'll have to leave that up to @tjcafferkey or @simison to answer.

**Comment by Aurorum** [comment]
@lancewillett ah, okay, best of luck with the Tumblr work! :) 

@rickybanister thank you - that's a good point about access to the component too.

**Comment by tjcafferkey** [comment]
@rickybanister we currently don't have access to the support article dialog component within this context unfortunately. 

I know we usually move common Calypso components from `client/components` to packages so we can use them, although the support dialog box currently lives in `client/blocks` and at the moment I'm not sure whether we can do the same with them.

**Comment by autumnfjeld** [comment]
Summarizing the complications that prevent the above suggestions from being implemented:

The packages noramlly used in Calypso to [url localization](https://github.com/Automattic/wp-calypso/blob/0c1acd1afc6e2fa8fcebae13f3ce355fd5a15e6f/client/lib/i18n-utils/utils.js#L242) such as `https://wordpress.com/support/https-ssl` and packages that handle the ideal help/support UX are not currently NOT “out of the box” useable here because they are Calypso components or utils (they are not standalone NPM packages) and thus not usable because we are in a Gutenboarding context (Gutenboarding is its own React app).

A quick implentation/workaround for this localization can be done by getting the locale and manually creating the localized support url. For example:
```
`https://wordpress.com/${ i18nLocale }/support/https-ssl`
``` 

Worthwhile to note this [@automattic/langauge-picker issue](https://github.com/Automattic/wp-calypso/pull/46020/) for future use.
