### ISSUE TITLE
Nav Unification: Responsive

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#45674]
Let's implement structural and styling changes so that we achieve a unified mobile experience between calypso and wp-admin when user is using the left nav.

Probably we will remove this
![](https://cln.sh/gnJEl5+)

and make it like this, where the WP logo acts as the hamburger memu
![image](https://user-images.githubusercontent.com/12430020/93234483-05e7a680-f785-11ea-9bb0-cbe64c122599.png)

Beware, that currently, WP logo in calypso doesn't close the menu. We need to fix that too.

#### Design
<img width="203" alt="mobile-13" src="https://user-images.githubusercontent.com/1398304/93808952-854ffc80-fc01-11ea-9a8c-91a542dc0dd1.png">

- [x] in calypso remove the white stripe containing the hamburger menu and site name
- [x] in calypso adjust the WP logo so that it toggles the menu without redirecting to home
- [x] check that spacing, padding, margin, font-size are in par with the designs
- [x] check that menus have the correct width
- [x] In wp-admin remove the hamburger menu, move the functionality to WP logo
- [ ] expand - collapse button?
- [ ] `wp-admin` sidebar state showing only icons?

**Comment by cpapazoglou** [comment]
@sfougnier Can you please link the final designs?

**Comment by obenland** [comment]
We have a decision on going with the full-width mobile styles (and removing the little ‘beak’ cutout):
pbAPfg-RE-p2#comment-1709

**Comment by cpapazoglou** [comment]
@sfougnier in `wp-admin` for  782px > breakpoint > 960px the sidebar shows only the icons

![](https://cln.sh/qqarrC+)

also this makes more evident that there is an expand - collapse button 

![](https://cln.sh/PWWpw8+)

Shall we inherit this UI - UX in calypso?

**Comment by sfougnier** [comment]
> Shall we inherit this UI - UX in calypso?

I would say it would be best to inherit this and not deviate from wp-admin. My only question is whether it would be weird to then click Reader and have the full menu appear.

> Moreover, as wp-admin makes the menu mobile in < 782px whereas calypso < 660px which one do you suggest following? I would be in favor of following wp-admin so that we don't have not expected surprises in the future.

Yeah, I agree it makes sense to follow wp-admin for this.

**Comment by cpapazoglou** [comment]
> My only question is whether it would be weird to then click Reader and have the full menu appear.
I guess we can keep a global state of the sidebar being collapsed, would that work for you?
What I have just thought, is that we can't keep a global state between jumps from calypso and wp-admin. So if a user has collapsed the sidebar in only one of these interfaces, they will see it expanded when clicking a link leading to the other. We could avoid this by hiding the expand / collapse 😄! Your call!

**Comment by cpapazoglou** [comment]
Thanks @sfougnier !

> My only question is whether it would be weird to then click Reader and have the full menu appear.

I guess we can keep a global state of the sidebar being collapsed, would that work for you?
What I have just thought, is that we can't keep a global state between jumps from calypso and wp-admin. So if a user has collapsed the sidebar in only one of these interfaces, they will see it expanded when clicking a link leading to the other. We could avoid this by hiding the expand / collapse 😄! Your call!

**Comment by sfougnier** [comment]
> is that we can't keep a global state between jumps from calypso and wp-admin. So if a user has collapsed the sidebar in only one of these interfaces, they will see it expanded when clicking a link leading to the other.

Yeah, I agree this isn't great but I'm not so sure removing the ability to expand/collapse is an option at this point, since we're trying to stick to Core as much as possible.

> what are we going to do with site switcher, site card and nudges when collapsed?

Something like this I think makes sense for the collapsed state.
<img width="1351" alt="desktop - collapsed" src="https://user-images.githubusercontent.com/67021691/94273554-930fc580-ff12-11ea-97ce-c8d05585b642.png">

I'm just not so sure about the nudges. The contextual nudge scales well, but the upgrade nudge doesn't really translate to a collapsed version since it has no icon. Do we hide it or add an icon in for the collapsed view? Not sure if that is possible or even makes sense, but I can try to think about this a little more.
<img width="1351" alt="desktop - collapsed nudge" src="https://user-images.githubusercontent.com/67021691/94273910-06193c00-ff13-11ea-92f5-99f39dc61319.png">
<img width="1351" alt="desktop - collapsed nudge 2" src="https://user-images.githubusercontent.com/67021691/94273878-fd286a80-ff12-11ea-8a9f-668abbca28e0.png">

**Comment by cpapazoglou** [comment]
Great @sfougnier, please share here any mockups as soon as you have something! The hover state of the site-switcher, site-card and notices would be useful too!
