### ISSUE TITLE
Plans: Launch plugins page

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4572]
@dmsnell and @drw158

**Comment by retrofox** [comment]
PR: #4438

**Comment by drw158** [comment]
TODO

- [ ] tweak banner text
- [ ] change icon for each plugin
- [ ] hook up purchase buttons (goes to plans for right now)
- [ ] launch to wpcalypso
- [ ] hook up metrics (includes clicks on individual plugin items)

**Comment by lancewillett** [comment]
Minor nitpick: post title is `standard Plugin` for a URL like https://wpcalypso.wordpress.com/plugins/standard/example.wordpress.com

Shouldn't it be `Standard Plugins`?

<img width="1199" alt="standard-plugins" src="https://cloud.githubusercontent.com/assets/66797/14359550/d77d7762-fca6-11e5-9b5a-5cff437e7156.png">

**Comment by apeatling** [comment]
This is coming together well. Here's some feedback, taking into account your TODO above:

1. Looking at this page as a new user, it would not be clear to me that the plugins in premium and business are not active. There's no difference between the visual representation of active and not active plugins. Maybe a "[x] disabled" under each inactive plugin, or a "[tick] Active" under each active one, or, have the inactive plugins faded out slightly?

2. Visually the different plans with plugins sections don't stand out all that clearly. I think it's because the "View Standard Plugins" section and link is so big compared to the "Premium Upgrades" title below it, it gets lost.

3. Could we make sure we call the upgrades "plans" in the headings, to be clearer that you can't buy them individually? So instead of "Premium Upgrades", "Premium Plan Upgrades".

**Comment by rralian** [comment]
Before we launch this to production, let's get it in staging for a day or two and make sure happiness is aware of the page, maybe with a post on wehavetheanswers.

**Comment by lancewillett** [comment]
Reminder to reference the Automattic commit checklist (which is in the FG), and has links for how to ask for testing, etc.

**Comment by rralian** [comment]
@drw158 I added a couple todo items to your comment above, feel free to edit.

**Comment by alisterscott** [comment]
This is looking good. Should the 'learn more' link open in a new tab since it's leaving Calypso?

**Comment by roundhill** [comment]
> hook up purchase buttons (goes to plans for right now)

I'll tackle this.

**Comment by drw158** [comment]
Now on Horizon for testing https://horizonfeedback.wordpress.com/2016/04/21/call-for-testing-plugins-page/

**Comment by drw158** [comment]
launched to a % of users https://github.com/Automattic/wp-calypso/pull/5022
