### ISSUE TITLE
Can Sybil be used for the FAB shown in Calypso.

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#45769]
Currently, Sybil (which is an automated system for suggesting Support Docs to users) is only used on https://wordpress.com/help/contact. Elsewhere the FAB is used - which (AFAIK) is hard coded and therefore more time consuming to update to provide relevant answers as our product changes.

### Why
* Consolidating 2 different systems for managing support doc suggestions reduces the ongoing maintenance workload
* Sybil is managed and updated by HEs - so this is something that can be done without the need for Dev work or commits to Calypso.

**Comment by davemart-in** [comment]
I'd love to understand some numbers behind this proposal. Like:

How many searches result in a customer contacting Happiness with Sybil on https://wordpress.com/help/contact compared to the number of searches within the FAB search popup which result in a customer contacting Happiness. 

We're talking about a serious investment of time and I just want to make sure that before we go down that road that the proposed solution is measurably better than what we have now.

**Comment by kristenzuck** [comment]
Thanks for the ping @davemart-in! I'll take a closer look at this later on this week and share my findings here :)

**Comment by gracie** [comment]
> How many searches result in a customer contacting Happiness with Sybil on https://wordpress.com/help/contact compared to the number of searches within the FAB search popup which result in a customer contacting Happiness.

I'm not exactly sure what you're asking (and I don't know what FAB is either!), but for Sibyl:

Users click on 6000+ sibyl suggestions each month for WPCOM, and that's from it living in the contact form alone. It could certainly use some love (hasn't been updated or audited in years), but even so, it's working well - that's an impressive stat for something that only appears in one place.

How many of those end up contacting support anyway? There's no direct way to tell. We think it prevents about 5000 queries total each month. Some of those people certainly contact support later for other questions, but Sibyl helps reduce how many questions they have or clears out the easier steps in a customer question.

Where do we find FAB stats?

**Comment by gracie** [comment]
@jordesign question for you - you mentioned this

> Elsewhere the FAB is used - which (AFAIK) is hard coded and therefore more time consuming to update to provide relevant answers as our product changes.

What's an instance of when that was problematic? I'm wondering if it would be wise to test FAB next to Sibyl and see if they're both serving relevant and time-sensitive suggestions. Right now, I can see it's serving up the editor deprecation doc when I write, "How can I write a post" into the question mark search field. Did we have to manually request that be added, or is it working intuitively? Granted, since these results show a support doc's title instead of "Are you looking for how to publish a post in the new editor?" we lose that translation into the customer's perspective and language in FAB, and I see that as a poignant downside to it. I'd love to see its stats.

If we want to expand Sibyl and see its stats are performing better than what's in FAB now, I'd like to request that PS make it a Q4 or Q1 goal to give WPCOM Sibyl a good scrub + seek out some dev help in polishing it, then pursue expanding it.

**Comment by davemart-in** [comment]
> I don't know what FAB is either

Sorry for using an acronym here! FAB stands for Floating Action Button and in this case we're talking about the blue help button in the bottom right corner of most screens:

![Image 2020-09-21 at 11 00 55 AM](https://user-images.githubusercontent.com/5634774/93783557-d0fea800-fbf9-11ea-94b3-76c57ed98960.png)

> I'm not exactly sure what you're asking

@gracie I guess what I'm asking is that before we start looking to incorporate Sibyl into the blue help button popup, I'd love to better understand how the Sibyl user flow compares to the blue help button popup user flow in terms of providing self-help (thus preventing the need to contact support). My guess is that this project would end up be a large or even XL project, so I'd love to just gather some data around it to help us make a more informed decision.

**Comment by gracie** [comment]
> @gracie I guess what I'm asking is that before we start looking to incorporate Sibyl into the blue help button popup, I'd love to better understand how the Sibyl user flow compares to the blue help button popup user flow in terms of providing self-help (thus preventing the need to contact support).

Super. I agree with you.

**Comment by sarahcada** [comment]
I'd like to make a small note that in the past, the FAB seemed to use Sibyl, or at least questions/answers similar to the ones used by Sibyl. We can [see that in action in the screencast in this post](https://wpcomhappy.wordpress.com/2020/04/27/wordpress-com-queue-diagnostics/) that @gracie made in 2019. Perhaps it was the length of the questions that forced the team to change it, I'm unsure. I'm not able to dig up the history at the moment, but I can spend time on that if it's needed.

**User Flow Comparison**
>I'd love to better understand how the Sibyl user flow compares to the blue help button popup user flow in terms of providing self-help (thus preventing the need to contact support).

I'm not as well-versed in Tracks as the HappOps folks, so I don't yet know how to get stats for the FAB, but from some of the conversation in Dave's [post on the Increase in Support Volume](https://happops.wordpress.com/2020/09/01/increase-in-support-volume/#comment-2234) it seems like there's a way to generate it.

As for Sibyl, I can support what Gracie said earlier using graphs that she herself helped us generate. From [here](https://mc.a8c.com/tracks/funnel/view.php?22539/2020-08-01/to/2020-08-31), we can see that in August, out of 6144 people who clicked a Sibyl suggestion, only 3020 (49%) returned within a week for a question (either the same one they asked initially or another question entirely), which means that the other 51% probably got their answer. 

![sibyl in august](https://d.pr/i/8wEAHT+) 

To balance that, here's a graph [of the past few months](https://mc.a8c.com/tracks/trends/?eventname=calypso_sibyl_question_click%2C%20calypso_sibyl_support_after_question_click&interval=week&startdate=20200327&stat=counts), where users come in, types a question and clicks a Sibyl-suggested doc, then comes back to ask the question waiting in the contact form. This doesn't count someone opening a new tab and asking the question, so the number of "answered"/"deflected" answers here is much higher: 5000 to 7000 a month.

![sibyl in august 2](https://d.pr/i/ZqLLsl+) 

>...test FAB next to Sibyl and see if they're both serving relevant and time-sensitive suggestions
>...since these results show a support doc's title instead of "Are you looking for how to publish a post in the new editor?" we lose that translation into the customer's perspective and language in FAB, and I see that as a poignant downside to it.

For comparison of what the customers experience, I'm happy to provide screenshots with some commentary. Contact Form with Sibyl on the left, FAB on the right.

Like what Gracie said, while both do a great job pulling up docs that may be helpful, the questions/entries crafted for Sibyl anticipate the possible ways a user will ask their question. Sibyl presents several versions of a question, lets the user pick which one they actually mean, and gives links to the most specific area we can think of so that they can get their answer quickly.

*Example 1*: Refund.
Sibyl suggestions lead to different sections of the "Manage Purchases..." doc. Titles in the FAB suggestions don't include "refund" so the user may think they're inaccurate.

![Refund question](https://d.pr/i/qZEXWF+) 

*Example 2*: Old editor.
Sibyl's suggestions point to the ["how can I use the classic editor" section ](https://wordpress.com/support/wordpress-com-classic-editor-deprecation-faqs/#how-can-i-use-the-classic-editor) of the FAQ, the [Classic Block doc](https://wordpress.com/support/wordpress-editor/blocks/classic-block/), and the ["why have you changed the editor" section](https://wordpress.com/support/wordpress-com-classic-editor-deprecation-faqs/#why-have-you-changed-the-editor) of the FAQ. The FAB's suggestions gives links to the pages that have these answers as well, but our users might click and not have the patience to read, or, they might think that those aren't the answers they're looking for and click through to the chat anyway.

![editor question](https://d.pr/i/5rJ9ub+) 

*Example 3*: Alignment.
Not all users use or know the term image wrapping, some might not think of the word "alignment". They just want the image and text next to each other. The answer is not in one of the suggestions by the FAB.

![image alignment](https://d.pr/i/A8BtnZ+)  

**Maintenance**
>Did we have to manually request that be added, or is it working intuitively? 

For FAB, as far as I know, requests are added manually by Manage folks. I believe the most recent post that HEs are aware of is [this one](https://wpcomhappy.wordpress.com/2020/06/19/surfacing-admin-sections-in-help/). Maybe @davemart-in can give an accurate answer. 

For Sibyl, any HE can add, edit, and delete/unapprove entries anytime here: https://mc.a8c.com/qanda/

In 2019, it took ~3 hours for 14 folks of Team Leviosa to update all the questions in a sprint during their meetup. In 2020, Patronus didn't dedicate one solid block of time; we'll approximate the total time spent but I'm guessing it'll be around the same.

It would be wonderful if the FAB or the My Home support UI can have a similar maintenance area that HEs can directly use without needing to ask devs!

**Comment by apeatling** [comment]
Note: I removed @sarahcada's comment because it contained sensitive data and links, and messaged in Slack to move to a P2

**Comment by sarahcada** [comment]
Thank you, @andypeatling. I appreciate it!

Reposting answers to specific questions:

>I guess what I'm asking is that before we start looking to incorporate Sibyl into the blue help button popup

I'll expound on what Gracie said earlier in this thread. "Users click on 6000+ sibyl suggestions each month for WPCOM", and *don't* return to the contact form where their question is still in the contact form. Another stat to look at is that in August, out of 6000+ people who clicked a Sibyl suggestion, only 3000+ returned within a week for a question (either the same one they asked initially or another question entirely), which means that the other 50% probably got their answer.

For comparison of what the users experience, while both do a great job pulling up docs that may be helpful, the questions/entries crafted for Sibyl anticipate the possible ways a user will ask their question. Sibyl presents several versions of a question, lets the user pick which one they actually mean, and gives links to the most specific area we can think of so that they can get their answer quickly. For the FAB and My Home support UI, if the understandably short titles of the support docs don't make the user feel like the specific answer they're looking for isn't there, then they won't feel helped. I can share comparison screenshots and further commentary on this in a P2.

By the way, there seem to be history of the FAB using Sibyl suggestions. It's possible that the length of the questions that forced the team to change it, I’m unsure and currently unable to dig up the history in dev convos. Perhaps Dave might be more aware,

As for maintenance, there's a control area where any HE can add, edit, and delete/unapprove entries anytime without dev intervention. It would be wonderful if the FAB or the My Home support UI can have a similar area.

**Comment by davemart-in** [comment]
Thanks for sharing @sarahcada!

> there seem to be history of the FAB using Sibyl suggestions
This is news to me. Does anyone know who could be pinged for more info on this? @kristenzuck, @gracie any thoughts?

> As for maintenance, there's a control area where any HE can add, edit, and delete/unapprove entries anytime without dev intervention. It would be wonderful if the FAB or the My Home support UI can have a similar area.
Yep. Understood. This makes sense! 

I'd still be interested to look at funnel data between the two options. @kurt213 is this something that you'd be able to add to your list? Basically, I'm interested in knowing:

A) Of the people who view the [FAB UI](https://a.cl.ly/ApuL6RWQ) and perform a search, how many go on to click "Contact us" and submit a contact form or chat with us?
B) Of all the people who view https://wordpress.com/help/contact how many go on to submit the contact form?

**Comment by kurt213** [comment]
@davemart-in got this added to my list. Part A funnel is [complete](https://mc.a8c.com/tracks/funnel/view.php?25834/2020-08-30/to/2020-09-28) if you want a sneak preview and have any questions. Currently looking into calculating part B.

> how many go on to click "Contact us" and submit a contact form **or chat with us**?
I can see the contact form submission but can't see an option to chat? Not sure if it's a plan limitation/there is an alternative way for a user to reach chat?

**Comment by davemart-in** [comment]
@kurt213 There are plan limitations on chat (@jordesign do you know what plan is required?). There are also availability limitations. I believe this is what you should see if chat is available:

![Screen Recording 2020-09-29 at 09 47 AM](https://user-images.githubusercontent.com/5634774/94566806-c915b800-0238-11eb-85f1-45df2164ca6f.gif)

**Comment by jordesign** [comment]
@davemart-in @kurt213 Currently an active paid plan is required (and relies on chat availability). This is changing shortly (to Premium or higher) but you should end up with access with any existing paid plan

**Comment by kristenzuck** [comment]
> There are plan limitations on chat (@jordesign do you know what plan is required?). There are also availability limitations. I believe this is what you should see if chat is available:

> Currently an active paid plan is required (and relies on chat availability). This is changing shortly (to Premium or higher) but you should end up with access with any existing paid plan

Additionally if you are an admin on someone else's site with a paid plan, you can get chat access, there are also presales and precancellations.

**Comment by kurt213** [comment]
I've completed an initial funnel analysis of these two journeys pcr1an-9-p2
> A) Of the people who view the FAB UI and perform a search, how many go on to click "Contact us" and submit a contact form or chat with us?
> B) Of all the people who view https://wordpress.com/help/contact how many go on to submit the contact form?

**Comment by donalirl** [comment]
Am I right in saying Sybil has been integrated into the FAB now? I'm not sure what was the case a year ago, but here's what is happening today:

In the FAB, I type "cancel plan":

<img width="263" alt="111" src="https://user-images.githubusercontent.com/30727666/137082334-5c021cdc-9d3b-4841-bfb7-a7dac255dd09.PNG">

The suggestions under 'support articles' are not Sybil, but then I click Contact Us:

<img width="276" alt="2222" src="https://user-images.githubusercontent.com/30727666/137090391-a756bf3b-c3ec-4002-9675-45db2e89c915.png">

Then, I click Continue and am presented with Sybil questions before initiating a contact request:

<img width="276" alt="333" src="https://user-images.githubusercontent.com/30727666/137082325-9c3dbe21-c494-42e1-bd0f-3c33f8265527.PNG">

**Comment by jordesign** [comment]
Closing this as FAB is being discontinued in the new "Help Center' work
