### ISSUE TITLE
Checkout: G Suite extra licenses should not ask for contact information

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#45786]
We only ever need customer information when creating a brand new G Suite account, not when adding extra licenses.

<img src="https://user-images.githubusercontent.com/594356/93774973-264eaf80-fc22-11ea-8f9d-c81f0160b480.png" />

Reported by @stephanethomas in https://github.com/Automattic/wp-calypso/pull/45737

**Comment by michaeldcain** [comment]
@stephanethomas: can you explain what information we _should not_ be asking for? The postal code and country from this screenshot are required billing fields for taxes.

**Comment by stephanethomas** [comment]
Ha, I didn't realize that the postal code and country were required for billing purposes. However, when you click on the `Edit` link we also ask for the alternate email address as well as the first and last names:

![screenshot](https://user-images.githubusercontent.com/594356/93990833-e572aa00-fd8b-11ea-945a-441a46349f83.png)

Again we don't need any information from this form in order to provision an extra license, so unless it's required for taxes or anything related to billing I would suggest removing it.

**Comment by nbloomf** [comment]
Here's a wild idea - the logic for determining what contact form to show in checkout is not trivial, a little scattered, and depends (mostly? entirely?) on business logic involving the cart contents. Can this decision be made on the backend and passed to calypso as a property on the shopping cart endpoint response?
