### ISSUE TITLE
Premium Blocks: Consider not hiding the upgrade prompt when the block loses focus.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45852]
We currently hide the plan upgrade prompt in premium blocks when the user clicks out of the block: 

![2020-09-22 13 48 08](https://user-images.githubusercontent.com/349751/93936182-9b7dbb80-fcda-11ea-9a29-ba7cce0915b8.gif)

We should consider leaving it displayed, to avoid the jumping visuals and potential user confusion.

See: pbBQWj-lH-p2

**Comment by davemart-in** [comment]
I'm going to ping @sfougnier on this as I think this was done intentionally.

**Comment by sfougnier** [comment]
Showing the upgrade prompt only in the active/edit state of the block was done intentionally to draw a user's attention to the messaging when they've placed the block and are working on editing it, in order to provide them with the ability to freely explore and view how these blocks would look in their page after they've clicked outside the block.

We chose not to keep it persistent for a few reasons:
- Keeping the upgrade messaging visible all the time gets in the way of a user editing and viewing their page content, making it another "thing" to work around and ignore.
- If a user had placed multiple premium blocks on the page there would be multiple premium block banners repeating down the page.
- Due to the varying designs of block styles and states, keeping the banner persistent in an inactive state didn't scale across every block and in some cases felt difficult to visually associate which block it was connected with. 
- On blocks that surface the Stripe banner, the vertical stacking of both banners made it difficult to focus the eye and further convoluted the ability to connect the block with the banner.
- If a user is editing another block within the page, the action on this banner competes with other actions.

With that said, I agree there are some conflicts with the toolbar overlapping this in some blocks. I wonder though if keeping the banner persistent is the best solution or if there could be a more seamless way to ensure this messaging doesn't get lost.

**Comment by davemart-in** [comment]
I'm going to close this one out. Let's move this convo to P2 if we want to keep the discussion going, then move the solution to a Github issue once we've decided what we want to do..
