### ISSUE TITLE
Provide Option to Move Domain Mapping Between Sites

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#45860]
For domains registered with Automattic, there is a self-serve option to transfer a domain to another site in the user's account:
![image](https://user-images.githubusercontent.com/30727666/93962880-245e2b00-fd9f-11ea-80d2-19d64681b80f.png)

This option does not exist for mapped domains. It's common to encounter cases of a customer who has mapped a domain to the wrong site in their account. They cannot move it. In addition, if they remove the mapping with the intention of mapping it back to the correct site, they are prevented from doing so with the "domain has been recently mapped" error. The only way to move the domain mapping is through HE intervention.

A self-serve option to move domain mapping would be beneficial to customers and reduce support requests.

#### Context / Source

Example case in #3340662-zen

**Comment by davemart-in** [comment]
@daledupreez is this something that the Cobalt team could consider?

**Comment by daledupreez** [comment]
Thanks for the ping, @davemart-in. I think we definitely should take a look, especially because we've also been looking at some closely related work this week.

@klimeryk, could you explore what would be involved here at a technical level? I know you've been way down into the weeds on site transfers, so think it would be good to consider this while that's still fresh in your mind.

**Comment by klimeryk** [comment]
Thanks for reporting, @donalirl! Always appreciate nudges from Happiness Engineers on frequent pain points 🙇 

> In addition, if they remove the mapping with the intention of mapping it back to the correct site, they are prevented from doing so with the "domain has been recently mapped" error.

FWIW, this should not be the case anymore - we removed that limitation a few months ago, since it was causing more trouble than it was worth.

We initially focused on domain registrations because we _had_ to provide that option to be fully compliant with ICANN rules. But I completely agree that it's high time we had a self-serve option for domain mappings, same as we already do for registrations.

And I think that will be the best starting point - like you mentioned, we already have the flows for registrations, so we should be able to adapt them to mappings as well (minus the option to transfer out to a different registrar, of course).
On the backend, the same endpoints can be used and depending on the type of domain, appropriate actions taken.

Overall, I don't think this will be a hard task - I'll add it to our Asana board and I hope to start working on it next week 🙇

**Comment by klimeryk** [comment]
Working on implementing transfer between sites here: https://github.com/Automattic/wp-calypso/pull/46418 🎉

**Comment by klimeryk** [comment]
To close the loop here: transfer mappings across sites has been implemented in https://github.com/Automattic/wp-calypso/pull/46418 and transfer to other users in https://github.com/Automattic/wp-calypso/pull/47060 🎉 

Thanks again for the nudge! ❤️
