### ISSUE TITLE
Make Specific Errors Retry-able In the Domain Suggestions API

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#45871]
#### Steps to reproduce

1. Starting at URL: /new
2. Enter site name
3. Change your domain search query to include non-alphanumeric characters (e.g.: العربية)
4. The returning error has a "Retry" button, which is will just return the same error.

#### What I expected

I expected no "Retry" button to exist, encouraging the user to correct their query.

#### What happened instead

I was presented with a "Retry" button, clicking this will return the same error

#### Screenshot / Video

<img width="1791" alt="Screenshot 2020-09-23 at 10 35 04" src="https://user-images.githubusercontent.com/8639742/93995095-7c3d6780-fd88-11ea-9d84-b332af41f417.png">

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I tried the same steps today and found a newer UX has been quietly implemented for this use case.

1. launch Gutenboarding as logged in user.
2. name the site some name.
3. remove all alphanumeric text from the search box.
4. enter non-alphanumeric text.

With Japanese-Kanji script and Arabic script, I was able to produce a banner that is shown in red and informs user to try something else with alphanumeric text only.

As the core of this issue is resolved, I am closing this issue as Closed - Fixed.

![Screen Shot 2021-03-22 at 3 52 08 PM](https://user-images.githubusercontent.com/6549265/112068304-e318bf00-8b26-11eb-9da6-0d5fa97514f4.png)
![Screen Shot 2021-03-22 at 3 52 33 PM](https://user-images.githubusercontent.com/6549265/112068306-e3b15580-8b26-11eb-9582-6642ec51bbd8.png)
