### ISSUE TITLE
CoBlocks Masonry gallery gets replaced when adding a new image using Calypso

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#45935]
#### Steps to reproduce

1. Open the Block Editor using Calypso (My Sites > Site > Pages > Add)
2. Add a Masonry block and some images to it. 
3. Save as a draft or publish the post.
4. Reload the editor and try adding a new image by clicking on "Media Library"

#### What I expected

For the new image to be added at the end of the rest of the images. The same way it happens when using WP Admin

#### What happened instead

The new image replaced all the previous images

#### Browser / OS version

Chrome: Version 85.0.4183.121 (Official Build) (64-bit)

macOS Catalina: 10.15.6 (19G2021)

#### Screenshot / Video

![Screen Capture on 2020-09-25 at 11-03-54](https://user-images.githubusercontent.com/3696121/94289810-e6881080-ff1e-11ea-98ec-8299828f5901.gif)

#### Context / Source

23933816-hc

#user-report

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was unable to reproduce this issue with the following versions:
Gutenberg: v10.1.1
CoBlocks: 2.5.3
Editing Toolkit: 3.2409


https://user-images.githubusercontent.com/6549265/111550463-61e2b600-873b-11eb-9df0-a271eb8c031a.mov


As such this issue is being closed with `Closed - Not Reproducible`.
If this issue should remain open, please feel free to re-open this bug.
