### ISSUE TITLE
Calypso styles not loading

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#45968]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/ (while logged in)

#### Summary

* Styles appear to be missing.
* Not sure if the `?retry=1` is normal in the URL.
* Refreshing seemed to help, but HEs still seeing periodic issues.
* There are JS console errors:

![Screen Shot 2020-09-28 at 12 35 39 PM](https://user-images.githubusercontent.com/15803018/94471884-218c7d00-0187-11eb-92c7-c54649d8158f.png)

#### Context / Source

p1601317466033300-slack-C02DQP0FP

**Comment by griffbrad** [comment]
If you're running Calypso in the staging environment and then a new build is pushed, that will often invalidate/remove some of the old JS chunks being referenced by the build you're running in your browser at that time, resulting in errors similar to those you shared here. This issue is avoided in production by the CDN, which will continue to serve the JS files from previous builds for a period of time after a new build is deployed.
