### ISSUE TITLE
Block Editor: Block Toolbar hidden for first block on home page

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#45967]
It's currently possible to create a site on WP.com, delete all the default blocks on the home page, created for you, add a new block and then — this is the bug — be unable to edit the first block on the homepage. 

Here's a screenshot.

![image](https://user-images.githubusercontent.com/545779/94469960-8eeedc80-018c-11eb-829d-2d99e3b361a5.png)

To reproduce …

1. Make a site on WP.com
2. Delete all the blocks on your home page
3. Add a new block
4. Click on the block and try and use the block toolbar — you should see something like the above

Tested with …
- The existing user flow
- Seedlet and Balasana (a Varia theme)

It may be a theme issue but it may also be a Calypso issue with some custom setting just for those themes causing this.

**Comment by ciampo** [comment]
I had a look into the problem, here are some initial findings.

This issue seems to manifest when the "post title" block is not displayed in the block editor. This explains why this issue happens on the home page, where [the title block is not shown to the user](https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/common/index.scss).

This title block would normally add enough vertical space on top of the first block for the toolbar to show. But when the block is hidden, the toolbar is positioned incorrectly and ends up being hidden under the post header toolbar

<img width="1604" alt="Markup 2020-09-29 at 11 58 11" src="https://user-images.githubusercontent.com/1083581/94544112-2155b580-024b-11eb-9dd2-7b75c77669d6.png">

Another thing that I noticed is that the positioning of the toolbar is calculated differently depending on the "height" of the content. With enough content, the toolbar is actually partially shown to the user:

<img width="1792" alt="Markup 2020-09-29 at 12 04 35" src="https://user-images.githubusercontent.com/1083581/94544963-3252f680-024c-11eb-983a-4670b3c9ff4c.png">
