### ISSUE TITLE
DevDocs: Add filter to gridicons section 

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#460]
Originally raised by @kellychoffman:

It would be nice if we could add a way to search/filter the gridicons list in the Dev Docs

**Comment by afsheenirani** [comment]
@alisterscott / @kellychoffman - That is a great point. Currently the UI components page seems to apply filtering to only the titles/headings for the various components and further granularity is not available. Let me take a stab at this enhancement.

What i'm thinking at a high-level is that the filtering should apply to even the text that helps define the UI component. 

So for an example Gridicon: `<Gridicon icon="link" />` we should be able to filter on `link`.

Thoughts?

cc @nb for fyi.

**Comment by kellychoffman** [comment]
It would be cool if you could search using the search bar at the top of https://wpcalypso.wordpress.com/devdocs/design/, but that isn't available on the gridicon page itself, if you have it bookmarked: https://wpcalypso.wordpress.com/devdocs/design/gridicons.

**Comment by afsheenirani** [comment]
@kellychoffman - Hahaha...there's no way you can get to that gridicons link from the main Sidebar or through links on the ui-components page...so I guess you can only play with the url paths or would have to know the folder structure in order to get to it.

I see your point though, let me think of this some more to see if this can be "generalized" some way. So that even "Social Logos" can have a search (or for that matter any "groupings" of components):
https://wpcalypso.wordpress.com/devdocs/design/sociallogos

**Comment by kellychoffman** [comment]
> there's no way you can get to that gridicons link from the main Sidebar or through links on the ui-components page

You can get to it by clicking on the Gridicons heading from the main page. All the headers are links. I constantly referred to the /gridicons page when working on new features.

**Comment by afsheenirani** [comment]
Ah! my bad...

**Comment by kellychoffman** [comment]
No worries - I should have specified in my previous comment.
