### ISSUE TITLE
Premium Content: Stripe connection banner needs visual fixes

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#46010]
When connecting a premium block to Stripe, there's some funky stuff going on with the banner; note the vertical alignment of the button and the button's border:

<img width="654" alt="Screen Shot 2020-09-29 at 12 57 01 PM" src="https://user-images.githubusercontent.com/2124984/94591290-e311c380-0255-11eb-95d8-2fff0d3e3b96.png">

The copy is also redundant and could be massaged a bit.
 
Originally noted by @pablohoneyhoney in Slack, ref: p1601399186066200-slack-dotcom-design

**Comment by sixhours** [comment]
It looks like the Premium Content block callout uses a different style from the Donations/Payments blocks, too, and there are spacing issues:

**Premium Content**

<img width="804" alt="Screen Shot 2020-10-06 at 11 55 09 AM" src="https://user-images.githubusercontent.com/2124984/95229205-49569300-07ce-11eb-9ecb-9a388dbfc11b.png">

**Donations/Payments**

<img width="823" alt="Screen Shot 2020-10-06 at 12 19 21 PM" src="https://user-images.githubusercontent.com/2124984/95229273-5e332680-07ce-11eb-83bd-3d489949d854.png">

**Comment by sixhours** [comment]
I haven't been able to reproduce the bottom border issue or the star icon being off-centered in the circle as is shown above. My hunch is a theme's styles might be bleeding into the banner, but I can't find a theme that displays this way.

**Comment by kwight** [comment]
> It looks like the Premium Content block callout uses a different style from the Donations/Payments blocks

Because Premium Content is still in FSE while Donations et al. are in Jetpack, it's different code rendering that same prompt for each. This sort of inconsistency will thankfully go away once PC is in JP.

Since that filled-in star is particular to Jetpack (from what I can tell), I'm assuming the OP was referring to a block like Payments, and not the Premium Content block (which is not available in JP at all). Here's what I'm seeing.

Simple PC | Atomic PC | Payments JP
--- | --- | ---
<img width="905" alt="Screen Shot 2020-10-09 at 12 44 54 PM" src="https://user-images.githubusercontent.com/349751/95625808-f844da00-0a2d-11eb-87ec-01b36bbeeeff.png"> | <img width="906" alt="Screen Shot 2020-10-09 at 12 45 46 PM" src="https://user-images.githubusercontent.com/349751/95625816-fbd86100-0a2d-11eb-892e-2d4bfc741ddf.png"> | <img width="720" alt="Screen Shot 2020-10-09 at 12 47 46 PM" src="https://user-images.githubusercontent.com/349751/95625822-ff6be800-0a2d-11eb-8095-757d146ff088.png">
