### ISSUE TITLE
PHP: Prepare dotcom projects for PHP 8 compatibility

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#46015]
This is a tracking issue for PHP 8 compatibility

- [x] Editing Toolkit
- [ ] Editor iframe integration
- [ ] CoBlocks
- [ ] AMP plugin

Please add other PHP-based projects to the list as you become aware of them

**Comment by simison** [comment]
cc @sirreal anything to worry about CoBlocks?

**Comment by simison** [comment]
([PHP 8 is out](https://www.php.net/releases/8.0/en.php))

**Comment by sirreal** [comment]
> anything to worry about CoBlocks?

Good question… I think it's unlikely to have issues but we can do some testing. I've created [an issue](https://github.com/godaddy-wordpress/coblocks/issues/1767) so CoBlocks is aware and can prepare automated testing.

I'll add this to @Automattic/good-mountain board to do some CoBlocks testing.

**Comment by simison** [comment]
@noahtallen do you happen to know how ready ETK is for PHP8, and if so, is it possible to keep it that way in current/future CI setup?

7.3 and 7.4 are other two versions we need to support on Atomic (https://wordpress.com/hosting-config):

<img src="https://user-images.githubusercontent.com/87168/108097638-0fa26c80-708b-11eb-9ebb-25442fbf0fc3.png" width="300"/>

**Comment by noahtallen** [comment]
I don't know if ETK is ready for PHP 8, but I can look into that this week. (CI sounds like a good way to track that)

**Comment by simison** [comment]
Thanks! Lemme know if you spot any changes needed and maintainers can help out. 👍

**Comment by noahtallen** [comment]
I've been able to successfully run the plugin with `phpVersion: 8.0` in wp-env. (Verified the php version, and it is working well as far as I can tell.)

I need to do some more research on CI stuff. The underlying PHPCompatibility checker hasn't yet been updated with full PHP 8 support yet, so it's not that simple.

Some other suggestions were running phpunit tests in a PHP 8 environment, but we don't have a very extensive test suite, so that may not catch everything.

If anyone has more ideas, I'm all ears! I'll keep looking for some more suggestions around the web

**Comment by simison** [comment]
@Automattic/team-calypso-platform howdy! I'll close this up as it sounds like things are either tracked elsewhere (for CoBlocks) or already working (ETK). Feel free to re-open if you'd like to keep this for your work, tho!

**Comment by noahtallen** [comment]
Cool! I do want to note that we don't have any CI running it on PHP 8 yet, but I think ETK is low risk in general just because the amount of PHP code is fairly low
