### ISSUE TITLE
Global Styles: Show Font Choices in the Actual Font

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#46027]
When browsing the list of available fonts in Global Styles, the list of fonts does not give any visual indication of what the font looks like:

![Annotation on 2020-09-30 at 11-57-11](https://user-images.githubusercontent.com/30727666/94634784-52e68380-0314-11eb-9862-acfef53a06d3.png)

This is a poor user experience because the user needs to manually click on each font to select it, to see what the font looks like. The average user does not know what Montserrat looks like or even what 'Sans' means in fonts. They need a visual indicator.

The experience can be vastly improved by displaying the font names in the actual font, like how it's done in Customize:

<img width="285" alt="font customizer" src="https://user-images.githubusercontent.com/30727666/94634866-950fc500-0314-11eb-9b92-e11808def25a.PNG">

#### Context / Source

#empathy #dogfooding #painpoint

**Comment by mattwiebe** [comment]
This is unfortunately complicated for a simple reason: `<option>` elements in a dropdown are not able to be styled, at least not in the way that we would like here. 

I wrote much of the old Customizer implementation, which meant that we had to create our own (Backbone!) component in order to render the dropdown in the font itself. This also meant that we had to solve the (many!) UX issues that dropdowns like this produce, never mind small screen and other accessibility issues.

We could use the `<Dropdown>` component instead of `<SelectControl>`, since it allows us to render HTML in a way that will allow us to style it with the `font-family`.

Also note that there will be some performance hits when loading a lot of fonts into the browser. It would be best not to load them until required so as to not to make the editor load more slowly. Also look into a subset of just the text of the font when loading.

**Comment by noahtallen** [comment]
Thanks for the context matt! I think we can remove this from the create focus maintenance board, since this is more of a feature which should probably be handled by an individual team. I also imagine that we may not want to work on this in favor of waiting for core's global styles solution to be in place.

**Comment by noahtallen** [comment]
Though this is a good request, I don't think this will be prioritized because of the work on Global Styles in core. That's a much more advanced system, and I imagine this global styles implementation will be deprecated at some point in the future.
