### ISSUE TITLE
Changes to homepage appear to get reverted if the change is made immediately after page load

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#46114]
![homepage](https://user-images.githubusercontent.com/22446385/94874672-e1364300-0495-11eb-84b5-f47f36119c0d.gif)
A similar bug was fixed in #45532 but this does not appear to have the same cause.

### To reproduce:

Go to the "Pages" page
* reload the page
* within the first ~5 seconds of the page loading, change the homepage
* the homepage will be updated
* wait ~5 more seconds
* the homepage will change back to the old homepage.

if you reload the page again, the homepage will appear set to the old homepage but will then jump to the new homepage 🤔 
the new homepage will remain selected.

**Comment by obenland** [comment]
@roo2 @ramonjd  Is this something you'd want to take another look at?

**Comment by ramonjd** [comment]
Thanks for the ping @obenland 

I think it's better suited to the Create Gardeners board for triage. I'll add it :)

**Comment by Copons** [comment]
I've tried this and apparently the setting never really saved, even waiting a while after the page load. 🤔 
As it seems, it never fires any request to save the `page_on_front` option (and `page_for_posts` too!).

The options are persisted in the Redux state and in the local storage, so that when I reload the pages list, I see the "updated" options for a brief moment, and then they "revert" to the previous state once the actual site is returned by the API.

I'll look more into this.
