### ISSUE TITLE
Editor Checkout - E2E Tests

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#46365]
Part of p7rd6c-2xm-p2

Implement e2e tests for in editor checkout

**Comment by tjcafferkey** [comment]
@razvanpapadopol from the linked draft PR you can see what scenarios I have covered but essentially the only one missing is actually taking the payment from the user. Is this something we can/want to cover in these tests?

I have looked at [other specs](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-plan-purchase-spec.js) and they don't seem to be covering this? I am wondering if this is because either:

1. It's not possible? E.g. can we run E2E tests if we're taken to PayPal?
2. These are already covered in another suite and doing so would be duplication?

**Comment by razvanpapadopol** [comment]
A good example of an e2e test suite that covers also user payment is the signup spec.
https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-signup-spec.js#L433-L475

I don't think it would be duplication since in our case, there are at least two differences:
- entry point is inside the editor
- checkout is displayed as a modal 

Of course, if you see an opportunity for code reusability (eg: `test/e2e/lib/shared-steps`) feel free to open a separate PR for that 👍
