### ISSUE TITLE
Account: remove upcoming charges tab

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#46415]
Let's remove the "upcoming charges" tab by merging its information with the subscription listing.

- Add renewal amount to subscription listing (Renews at $20 on 22 December) - maybe merge this independently
- Remove "upcoming charges" tab and components
- Add route forwarding to subscription tab
- Update support docs to old route
- Check for links to old route in emails

**Comment by DavidRothstein** [comment]
There are some possible edge cases here regarding what happens when a subscription is past its first auto-renewal attempt (especially for Jetpack, G Suite, and some others, where the first auto-renewal attempt is on the day of expiration, so there can be subscriptions that already expired but that still will have a renewal attempt on a future date).  Need to figure out what to display in that case and how to display it.

**Comment by michaeldcain** [comment]
Let's split this into two tasks:
- [ ] adding the renewal to the subscription listing and removing the tab
- [ ] forwarding the route and removing the unused components
