### ISSUE TITLE
Audit experimental features in Editing Toolkit

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#46489]
**Master tracking issue**: https://github.com/Automattic/wp-calypso/issues/44251

Editing Toolkit is dependant on [experimental](https://github.com/WordPress/gutenberg/blob/1d0eecb53fc3b91b1ad7bd51a368e088243fa8eb/docs/contributors/coding-guidelines.md#experimental-and-unstable-apis) features without a fallback for a scenario where such a feature is not supported anymore. Below is a list of usages that we need to update in this matter:

- [ ] `dotcom-fse`: https://github.com/Automattic/wp-calypso/issues/46520
- [ ] `event-countdown-block`: https://github.com/Automattic/wp-calypso/issues/46519
- [ ] `global-styles`: https://github.com/Automattic/wp-calypso/issues/46522
- [ ] `premium-content`: https://github.com/Automattic/wp-calypso/issues/46523
- [ ] `wpcom-block-editor-nav-sidebar`: https://github.com/Automattic/wp-calypso/issues/46524

**Comment by WunderBart** [comment]
@Automattic/cylon is this something that you could look into?

**Comment by noahtallen** [comment]
@WunderBart I think we might need to split this across the teams who worked on each area of the codebase since we are really only familiar with `dotcom-fse`.

> /event-countdown-block

cc @mkaz 

> /global-styles

cc @nosolosw 

> /premium-content

cc @Automattic/serenity 

> /wpcom-block-editor-nav-sidebar

cc @p-jackson

**Comment by WunderBart** [comment]
Thanks for mentioning the right folks, @noahtallen! 🙌 

I've split this one into separate issues (see updated description) and created a [milestone for the ET](https://github.com/Automattic/wp-calypso/milestone/323). I hope this will help organize this task better.

**Comment by nosolosw** [comment]
:wave: I've received the pings and would like to understand how can I help here: is it your goal to audit if an unstable/experimental usage is ok or does it need updating based on [WordPress 5.6 stabilization task](https://github.com/WordPress/gutenberg/issues/25786)?

This is what I can say about the [code for Global Styles](https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/global-styles/src/dom-updater.js#L33): apparently, `__unstableIsEditorReady` was introduced as a patch specific for WordPress.com/iframed editor at https://github.com/Automattic/wp-calypso/pull/40690 It is an API that will remain as it is for the time being, so it's safe to keep using it.

---

In case the goal was to remove any unstable/experimental API. From what I gathered reading that issue, it looks like the problem was that the stylesheet generated in the client by the Global Styles plugin upon user changes needs to be appended after Gutenberg's own editor styles (which is somehow messed up by the iframed editor). This is what's happening:

1. GS (server) sends to the block editor some [pre-calculated styles](https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/global-styles/class-global-styles.php#L309) via the block_editor_settings, so they are wrapped by the `.editor-style-wrapper`.
2. GS (client) adds a new styleshet with new styles if the user made any changes. This needs to be loaded after 1.

A few alternatives that come to mind to get rid of the `__unstableIsEditorReady` would be:

- given that user changes can only happen when the sidebar is mounted, etc, is there any other editor event this can be hooked to?
- change how the styles work for the editor: do not send the existing pre-calculated styles and instead generate them all in the client.

**Comment by WunderBart** [comment]
> 👋 I've received the pings and would like to understand how can I help here: is it your goal to audit if an unstable/experimental usage is ok or does it need updating based on WordPress 5.6 stabilization task?

👋 @nosolosw, thanks for your reply. Our goal is to make sure experimental features don't accidentally break the code that depends on them. This means either providing a fallback mechanism (i.e. like [this one](https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/block-inserter-modifications/contextual-tips.js#L41-L49)) or an alternative implementation as you mentioned. I didn't notice the `__unstableIsEditorReady` to be mentioned in the [5.6 stabilization task](https://github.com/WordPress/gutenberg/issues/25786) so [I asked about adding it](https://github.com/WordPress/gutenberg/issues/25786#issuecomment-712165216). Do you think you could own the https://github.com/Automattic/wp-calypso/issues/46522?

**Comment by WunderBart** [comment]
> 👋 I've received the pings and would like to understand how can I help here: is it your goal to audit if an unstable/experimental usage is ok or does it need updating based on [WordPress 5.6 stabilization task](https://github.com/WordPress/gutenberg/issues/25786)?
> 
> This is what I can say about the [code for Global Styles](https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/global-styles/src/dom-updater.js#L33): apparently, `__unstableIsEditorReady` was introduced as a patch specific for WordPress.com/iframed editor at #40690 It is an API that will remain as it is for the time being, so it's safe to keep using it.
> 
> In case the goal was to remove any unstable/experimental API. From what I gathered reading that issue, it looks like the problem was that the stylesheet generated in the client by the Global Styles plugin upon user changes needs to be appended after Gutenberg's own editor styles (which is somehow messed up by the iframed editor). This is what's happening:
> 
> 1. GS (server) sends to the block editor some [pre-calculated styles](https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/global-styles/class-global-styles.php#L309) via the block_editor_settings, so they are wrapped by the `.editor-style-wrapper`.
> 2. GS (client) adds a new styleshet with new styles if the user made any changes. This needs to be loaded after 1.
> 
> A few alternatives that come to mind to get rid of the `__unstableIsEditorReady` would be:
> 
> * given that user changes can only happen when the sidebar is mounted, etc, is there any other editor event this can be hooked to?
> * change how the styles work for the editor: do not send the existing pre-calculated styles and instead generate them all in the client.

**Comment by nosolosw** [comment]
I don't think I can own that refactor but can provide support, pointers to where to start, or reviews if that's helpful to folks.

**Comment by sirreal** [comment]
Closing this as of https://github.com/Automattic/wp-calypso/pull/47712 / p4TIVU-9xW-p2
