### ISSUE TITLE
Editor: Media: gallery images are in the wrong order in the "Edit" step

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#4652]
Steps to reproduce:

1. Start at https://wordpress.com/post (select a blog if prompted)
1. Tap Add Media icon
1. Select a few images in a specific order
1. Tap the Edit link (in the ellipsis menu)

<strong>Result:</strong> I expected to see the images in the order I selected in the "Edit" step, but they are out of order.

<strong>Video:</strong> [35s](https://cloudup.com/cY8icK9fdSU)

I selected a pie image as the first image in my gallery, but after clicking "Edit" I saw the butterfly image first instead of the pie image that I wanted to be shown first:

<img src="https://cloud.githubusercontent.com/assets/1119271/14436739/4be198cc-ffdb-11e5-9ea5-9d508290af98.png" width="400" alt="screen shot 2016-04-11 at mon apr 11 11 47 26 am" />

**Comment by aduth** [comment]
I'm having trouble finding the previous discussion or rationale, but worth pointing out that this behavior is [explicit and intentional](https://github.com/Automattic/wp-calypso/blob/e9f4e500dcc46ba2a64826d1c086b8a2cfc12873/client/post-editor/media-modal/detail/index.jsx#L63). If I had to guess, it may have been that we wanted the editing flow to be distinct from the insertion workflow; an idea I'm not sure I would agree with any longer (especially given primary action on that screen which... IIRC wasn't originally there?).

/cc @kellychoffman

**Comment by kellychoffman** [comment]
> an idea I'm not sure I would agree with any longer

Same here. I think the ordering should remain the same whether you are inserting or editing.
