### ISSUE TITLE
Background Color Picker For Gutenberg Block Malfunctioning

### ISSUE THREAD

**Issue by stumax** [Automattic/wp-calypso#46527]
See #3406855-zd for full details,

#### Steps to reproduce
Create new page in calypso or wp-amin
Add a cover block
Try to add background color with color picker

#### What I expected
Colors to be visible and selectable 

#### What happened instead
All color options are black and have no affect.
errors in console related to 'Block Validation' observed

#### Browser / OS version
replicated on chrome, although probably non specific
Seems to be site specifc , could not replicate on another instance with same theme and custom css 
Theme = Redhill

#### Screenshot / Video
https://d.pr/free/v/wmnL7B

**Comment by edequalsawesome** [comment]
In checking on this, the issue was that the settings for the Colors & Backgrounds area of the Customizer weren't saving correctly, so no color options were being provided -- I reset that and saved the default colors again (since that's what the customer was using anyway), and now the Cover block is showing the correct color options!

**Comment by noahtallen** [comment]
What theme was used?

**Comment by edequalsawesome** [comment]
@noahtallen It's using Redhill, which they started using about a year ago.

Let me know if there's any other information I can get for you!

**Comment by noahtallen** [comment]
Thanks! I'll try to replicate the issue :)

**Comment by noahtallen** [comment]
I'm going to close this for now. I think it must have been an issue where activating the theme a year ago didn't correctly change or set the color palette. At least, that's my guess! I think a lot of work has been done on varia child theme colors since then. It definitely seems to be working properly now 👍
