### ISSUE TITLE
Payments - Feature Request: Show currently connected Stripe account in dashboard

### ISSUE THREAD

**Issue by ersatzpenguin** [Automattic/wp-calypso#46551]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/earn/payments/mygroovydomain.com
2. Connect to Stripe.
3. Forget which Stripe account you've connected to your site, because you have multiple.
4. Go back to https://wordpress.com/earn/payments/oohaahdspa.com and try to find out which account you connected.
5. Stare at the screen a bit until you give up and disconnect, then reconnect the account so you can be sure which one is connected.

#### What I expected
To see the current connected Stripe account listed *somewhere* on the page—at the very least on the disconnect button.

#### What happened instead
No indication is made whatsoever about which Stripe account is connected to the site—forcing a disconnect and reconnect to verify.

#### Browser / OS version
N/A. Issue is present in all browsers.

#### Screenshot / Video

![earn page after connecting stripe](https://d.pr/i/jAKk8m+)

#### Context / Source
This came up in 24892024-hc, where a user reached out via chat looking to determine which Stripe account their site was connected to—but unable to do so. I struggled as well, and in looking through our documentation and reaching out via Slack, it became clear that this isn't something that's possible currently.

I am unsure what sorts of technical challenges it would impose to add it, but the fact that it's not possible to see which Stripe account is connected impacts a user's ability to verify where they should be receiving payments etc., and the work-around (disconnecting and then re-connecting) is a bit clumsy.

#user-report

**Comment by eduardozulian** [comment]
+1

Another issue in 25452637-hc. The user tried to connect Stripe to determine what is the Stripe account we created for them.

**Comment by pottedmeat** [comment]
Patch submitted to add this information to the API in D80696-code

**Comment by pottedmeat** [comment]
Would appreciate feedback on the following UI changes to show the user whatever information we have—either business name + email or the account name—whether or not the account is currently connected:

![image](https://user-images.githubusercontent.com/38750/169356058-3019d02c-482c-45fc-ba0d-8dcf93cfb758.png)

![image](https://user-images.githubusercontent.com/38750/169356081-e1091ac1-e557-4e30-b254-e68904009eca.png)

For additional context, especially in the case of the "Disconnect Stripe Account", the user may discover they do not recognize the connected account.

This can potentially be fixed by contacting an HE, which we would inform the user of when they begin the disconnection workflow. It can also be fixed by adding the option to reconnect a Stripe account, which can also be initiated through the disconnection workflow but possibly limited to only situations where the [account mismatch bug](935-gh-Automattic/payments-shilling) was present.

**Comment by chrisfromthelc** [comment]
That makes sense to me. We should give the user some kind of clue as to what it was/is connected to in order to avoid confusion.
