### ISSUE TITLE
Checkout bar still shown after completing a new purchase

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#46684]
#### Steps to reproduce

1. Buy something new (e.g. a WordPress.com plan).
2. Notice that after you complete the purchase, you're still inside checkout (via the top bar on the page) rather than having the normal navigation.
3. You can get out by clicking some of the links inside the page, but clicking the "X" in the bar tends to lead to broken behavior.

#### What I expected

To no longer have the "Secure checkout" bar displayed once my purchase is complete -- it should just show the normal Calypso navigation instead.  That is how it used to work until recently.

#### Screenshot

![stuck-in-checkout](https://user-images.githubusercontent.com/235183/96893940-3e039880-1459-11eb-8f57-e194cd7fef8a.png)

**Comment by sirbrillig** [comment]
🤔  Interesting... the checkout masterbar is shown on the thank-you page because it's the masterbar for the whole checkout section of calypso, as rendered by [MasterbarLoggedIn](https://github.com/Automattic/wp-calypso/blob/b1ece95a798617eb068ec47bc6c10adcf359ab19/client/layout/masterbar/logged-in.jsx#L201). That was [modified recently](https://github.com/Automattic/wp-calypso/pull/45040/files#diff-27374a70c13059756839dabb3fedf4c59c75444f93497261a45b2804e989cc89R173), but the actual behavior has existed since [the close button was added to checkout](https://github.com/Automattic/wp-calypso/commit/3beeeb6554a7105511b0f7e7c6a7ee7cad009117). (The checkout masterbar has been shown on the thank-you page for [much longer](https://github.com/Automattic/wp-calypso/pull/36529).)

**Comment by sirbrillig** [comment]
The behavior for the button is: if there's a `previousPath` (I think that's saved in Redux), go there; otherwise go to the plans page. So if you click on the close button when you're on the post-purchase upsell page, it throws you back to checkout. If you click on the close button on the thank-you page, you go back to the upsell page or to checkout (depending on where you came from). I think that's the issue, as going back to checkout is not where I'd expect the close button to go.

Maybe we should just hide the close button except on the actual checkout page.

**Comment by sirbrillig** [comment]
I was looking too hard, apparently. @DavidRothstein  and @michaeldcain tracked the bug down to this PR: https://github.com/Automattic/wp-calypso/pull/46086 which changed where the `sectionName` is stored.

It looks like a result of that is that [this call to setSection](https://github.com/Automattic/wp-calypso/blob/b8d5d2b355072390301b26c8c04d8529c3c2378f/client/my-sites/checkout/controller.jsx#L140) no longer works, or possibly works too slowly for the masterbar decision making.

**Comment by sirbrillig** [comment]
Before #46086 , if you examine the props of the `Layout` component on the thank-you page (eg: http://calypso.localhost:3000/checkout/thank-you/example.com/111111111):

<img width="288" alt="before-change" src="https://user-images.githubusercontent.com/2036909/96906281-95106a00-1467-11eb-88f7-215deb565762.png">

And after:

<img width="283" alt="after-change" src="https://user-images.githubusercontent.com/2036909/96906294-993c8780-1467-11eb-8797-050def85cb0d.png">
