### ISSUE TITLE
Onboarding: No indication of URL in the console until you first try loading Calypso in the browser

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#467]
Once I have built Calypso, until I try loading it in the browser the only indication I get in the console is:

`wp-calypso booted in 680ms - port: 3000`'

It doesn't tell me what URL to go to. Unless I know that, I wouldn't have any idea unless I read the readme, and we know a lot of people won't be doing that.

Of course once I load it, because I know the URL it shows it in the console:

`Compiling assets... Wait until you see READY! and then try http://calypso.localhost:3000/ again.`

this information needs to be shown sooner, without the need to try it in the browser first. /cc @nb

**Comment by folletto** [comment]
> You don't get that message until after you have hit the browser.

Initially I was confused too, but you get the ready message regardless of the browser. The compiling is happening, and if you don't do anything, the URL will appear.

The message:

```Compiling assets... Wait until you see READY! and then try http://calypso.localhost:3000/ again.```

Appears only in the case you hit the browser **before** it's "Ready!"... which shouldn't happen, since we don't show the message until that moment... and that's why the message is shown. ;)

So... I actually would _not_ show the URL before, since before it's shown, it's _not_ ready yet!
We might even want to remove it from that "Compiling assets..." message, since at that stage it's, again, not ready, so no reason to open it and well... if the message is appearing, it's likely already open.

See #1039 that already fixed the flow adding the wait message. :)

**Comment by sirbrillig** [comment]
@folletto Maybe what is needed is an opening message explaining what is going to happen before compilation begins? Something like

``
Calypso is getting ready. Please wait a few moments while we build everything. When we're done, we'll let you know right here.
```

**Comment by folletto** [comment]
The message is already there (#1039 merged it):

![screen shot 2015-12-11 at 22 39 32](https://cloud.githubusercontent.com/assets/4389/11757296/152734dc-a058-11e5-8f85-43561be472dd.png)
