### ISSUE TITLE
Nav Unification: Check domain notices

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#46732]
#### Steps to reproduce

* Starting at URL: `/home/[your-site]/?flag=nav-unification`
* On a site with an expired domain, you'll see something like this:

<img width="277" alt="Screen Shot 2020-10-23 at 10 52 27 AM" src="https://user-images.githubusercontent.com/2124984/97028189-c7829b80-1529-11eb-92f2-baa80710ce31.png">

There are other non-JITM notices that [pop up here](https://github.com/Automattic/wp-calypso/blob/b8d5d2b355072390301b26c8c04d8529c3c2378f/client/my-sites/current-site/notice.jsx) that probably need testing. I usually trigger them by overriding the logic in that file manually; not sure if there's a better way.

**Comment by cpapazoglou** [comment]
@sixhours interesting enough, the text is overflowing in production already! It is just the fact that the overflowing content is hidden 
![](https://cln.sh/bZfYrC+)
and it is more prominent now due to the narrower sidebar.

Addressed here https://github.com/Automattic/wp-calypso/pull/46819. I would appreciate it if you could take a look!
