### ISSUE TITLE
E2E: Audit the `getElementByText()` helper

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#46775]
Recently, in https://github.com/Automattic/wp-calypso/commit/71371187208152c1a69645fd3fd0a15bd99b8ebb we fixed a flaky spec. Let's answer a few questions to get some perspective.

**How was that spec flaky?**
The test itself was frequently taking too long, throwing a timeout error.

**Why was it taking so long?**
Because the [`getElementByText()`](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/lib/driver-helper.js#L544-L549) helper was called with a very generic element selector - a `span`. At that point, there were around 1.5k `span`s in the DOM which made the iterator lag heavily.

**Should we be using `xpath` instead of that helper?**
I'm not sure :) - I went for the `xpath` because I had a hunch that the helper is overkill. It helped in that situation, but generally, `xpath` doesn't seem to be faster in cases where a more specific selector is provided. It definitely is less friendly to use because of the cumbersome syntax, though.

**What should we do then??**
I would say that we should:
- Audit other usages of that helper and see if they're not making any other specs flaky,
- See if we can optimize the helper for generic selectors,
- If we can't, let's think of a way to provide protection against using generic selectors, like add a linter rule,  throw an error, etc,
- Consider using `xpath` instead (write a helper that uses `xpath`?).

cc @bsessions85

**Comment by bsessions85** [comment]
Generally we prefer to avoid xpath because it is much more likely to change and break the tests. That being said, sometimes it is necessary. In this case the options would be to either use xpath, or see if it is possible to add some sort of data attribute to the code. Seeing as how this is Gutenberg and the code isn't in the Calypso repo, that leaves xpath.  I think you did the right thing and I don't think an xpath helper is needed. `By.xpath` should work just fine with things we already have in place.

**Comment by WunderBart** [comment]
Thanks for the reply, @bsessions85!

> Generally we prefer to avoid xpath because it is much more likely to change and break the tests.

I'm pretty new to `xpath` - could you elaborate on what you mean by that it's more likely to change, please?

**Comment by bsessions85** [comment]
@WunderBart Yes, with xpath often times people will use an absolute path that will break any time a div is added or removed. I see you used a relative path, so that is much more reliable. 

Honestly, I've been avoiding xpath for so long I wasn't aware how much better they've made things to avoid those types of breakages, so I feel much better using it after looking up some more info about it.

**Comment by WunderBart** [comment]
I've checked all the current usages of the `getElementByText()` helper and none of them seems to be causing any additional delays. The original flaky spec was an exception. Let's close this one.
