### ISSUE TITLE
Horizon Site Editor: Can't exit the Site Editor

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#46822]
I expect this one may turn out to be just a small one to fix as things may have just got a bit out of sync. To reproduce …

- [Create a site on Horizon with the site editor flag](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor).
- Attempt to exit the site editor and go back to Calypso.

Here's what I see when I attempt to exit the Site Editor right now. My browser tab appears to be crashing here in Chrome MacOS.

![image](https://user-images.githubusercontent.com/545779/97234753-7be12380-17af-11eb-8fc2-79202f46c061.png)

**Comment by ianstewart** [comment]
Here's a gif …

![2020-11-04 15 40 49](https://user-images.githubusercontent.com/545779/98171026-ad937200-1eb4-11eb-9de9-c59c28ae21db.gif)

**Comment by vindl** [comment]
The problem here is that we don't have similar Dotcom specific overrides for this button like we had for W icon. As a result it's attempting to navigate to wp-admin page within the iframe and that request is blocked.

The proper solution here should be:
- create a slot/fill in core that allows us to replace the default button
- use that slot to provide a Dotcom specific version of it that navigates back to Calypso dashboard instead of wp-admin

**Comment by david-szabo97** [comment]
> create a slot/fill in core that allows us to replace the default button

Taking this one 🙂

**Comment by vindl** [comment]
The core PR for this has been merged. Once 9.4 lands on edge sites we can proceed with a Dotcom specific override. One note - since both site editor and post editor use the same slot/fill, we should make sure to limit the fill application to just the site editor context.

**Comment by vindl** [comment]
> One note - since both site editor and post editor use the same slot/fill, we should make sure to limit the fill application to just the site editor context.

Update: after https://github.com/WordPress/gutenberg/pull/27213 this is no longer true.
