### ISSUE TITLE
Focused Launch: Refine overall layout styles

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46844]
- Modal should have correct padding / white space around the content
- Content should scroll inside the modal if the viewport's height is too short
- Quotes on mobile should be in between each step title and its interactive content. On mobile, they should sit to the site of each step (maybe consider using CSS grid layout)

![Screenshot 2020-10-28 at 11 09 04](https://user-images.githubusercontent.com/1083581/97422523-338c4780-190e-11eb-8ce4-adea77faee10.png)

![Screenshot 2020-10-28 at 11 08 25](https://user-images.githubusercontent.com/1083581/97422532-371fce80-190e-11eb-9291-63ca38d194f1.png)

**Comment by alshakero** [comment]
These are all fixed in https://github.com/Automattic/wp-calypso/pull/46784
![testingfocusedflow wordpress com_wp-admin_post php_post=2 action=edit post_type=page calypsoify=1 block-editor=1 frame-nonce=a93d648c14 origin=http%3A%2F%2Fcalypso localhost%3A3000 environment-id=development support_user _support_token(iPho](https://user-images.githubusercontent.com/17054134/97600309-35870100-1a09-11eb-953e-15678e9b28d5.png)

**Comment by alshakero** [comment]
Closing as done.
