### ISSUE TITLE
Focused Launch: register Launch data-store and any other necessary data-stores

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46853]
registration example: https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/stores/domain-suggestions/index.ts

**Comment by yansern** [comment]
About registering stores in Launch package, I did this here https://github.com/Automattic/wp-calypso/pull/46834/files#diff-8b474e5056b6f588d348eb6c5a092485e17c85af90bc8910532f2d705812ea45 but I have a feeling that things might go wrong when FocusedLaunch loads under FSE (double data store registration?) because FSE's store registration is done through the alias `a8c-fse-common-data-stores` which is loaded by the *existing* Launch modal. I should double check the PR to see if it runs under FSE.

**Comment by ciampo** [comment]
@yansern I'm going to assume that #46834 fixes this issue, but feel free to add more details in case it doesn't
