### ISSUE TITLE
Video Block: Default Poster Image

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#46891]
When you don't set a poster image for a video, how is the default image determined? I expect it to be the same as the one I see on a self-hosted site that matches with the preview in Finder.

WP.com | Self Hosted
------------ | ------------
![screencapture-iamtakashi-wordpress-2020-10-28-headings-on-cover-2020-10-28-20_54_32 1](https://user-images.githubusercontent.com/908665/97498554-534e5a80-1964-11eb-83ba-77184f48413a.jpg) | ![screencapture-iamtakashi-eu-ngrok-io-2020-10-28-20_50_12 1](https://user-images.githubusercontent.com/908665/97498565-5b0dff00-1964-11eb-87bb-eaceef0ffe76.jpg)

![Screenshot 2020-10-28 at 21 26 53](https://user-images.githubusercontent.com/908665/97498611-6cefa200-1964-11eb-8cc8-d54e53d62270.jpg)

cc @ianstewart @apeatling

**Comment by glendaviesnz** [comment]
@mmtr from memory I think you have done a bit of work on videopress - do you have any thoughts on why WPcom always defaults to 4:3 aspect ratio but jetpack sites running video press default to 16:9?

I have tried setting `Display higher quality video by default.` in WPadmin for the sandboxed site, but that didn't make any difference, and havn't had much joy trying to the trace the code that is setting the aspect ratio for the player - can see where it happens in the jetpack block, but it is just getting the height and width from the underlying iframe size which is set somewhere on the backend.

**Comment by mmtr** [comment]
@glendaviesnz I don't know what causes the different behavior but likely is determined in the [videopress lib](https://github.com/Automattic/videopress):

https://github.com/Automattic/videopress/blob/master/lib/auto-resize.js
https://github.com/Automattic/videopress/blob/45c72f78ba088c47b89fcd2a0954b40a62dea6c8/lib/index.js#L27-L28

**Comment by glendaviesnz** [comment]
This is VideoPress related. On WPcom and Jetpack sites with videopress enabled the selected image is the same .. it is only different when using the raw gutenberg video block. Will look further into how videopress determines which frame to show

**Comment by apeatling** [comment]
As a note, if you upload a video via the wp-admin media library there is a UI to select the desired frame.

**Comment by glendaviesnz** [comment]
The default video block makes no effort to generate a suitable poster image it just shows the first frame of the video, which is why it is the same as the preview image in finder ... Videopress however generates a poster image from a certain number of seconds into the video and applies various filters or checks to ensure that thumbnail is valid ... my view is that the Videopress approach is more likely to produce a default poster image that is useful than just showing the first frame, so unless customers are complaining about the result I don't think we should be changing this videopress setup.
