### ISSUE TITLE
Checkout: Display tier of plan in the cart for Search

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#46934]
#### Steps to reproduce

1. Starting at URL: https://jetpack.com/upgrade/search/
2. Click on either the main CTA (https://wordpress.com/purchase-product/jetpack_search/monthly) or the annual link (https://wordpress.com/purchase-product/jetpack_search) 
3. Select a site to add the upgrade to (can be a Jetpack site or a WP.com site)
4. You end up at the cart

#### What I expected

I should see the tier of the subscription (e.g. up to 1000 records) and see whether it is monthly or annual.

~~I should also be able to switch between monthly and annual.~~ (Tracked separately)

#### What happened instead

I just see "Jetpack Search" with a price and no context.

#### Screenshot / Video

<img width="1020" alt="screen-shot-on-2020-10-29-at-15-15-41" src="https://user-images.githubusercontent.com/820871/97651011-a685e300-1a20-11eb-8dd7-3a0e90f74ed0.png">

<img width="636" alt="95409762-df312000-097e-11eb-94e3-fdda67303be0" src="https://user-images.githubusercontent.com/820871/97651020-aab20080-1a20-11eb-8100-dd8942d37403.png">

**Comment by gibrown** [comment]
Supposedly the cart is supposed to let you change the billing frequency, but that doesn't seem to work.

<img width="799" alt="Screen Shot 2020-10-30 at 8 25 49 AM" src="https://user-images.githubusercontent.com/820871/97716873-c4d3f900-1a89-11eb-95f6-8f3d1efb6b82.png">

**Comment by michaeldcain** [comment]
> Supposedly the cart is supposed to let you change the billing frequency, but that doesn't seem to work.

This is a separate issue (that probably applies to all Jetpack products), since it looks like [we only show term variations for plans](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/composite-checkout/hooks/product-variants.js#L176). 

It'll involve quite a bit of work, and currently we see minimum user interaction with term picking in Checkout, so let's track it in #47009

**Comment by sirbrillig** [comment]
After some recent changes, calypso should have enough data now to be able to do this. Specifically:

- Shopping cart products already contain a `months_per_bill_period` which can be used to determine if a product renews monthly, yearly, or biannually.
- Since D59709-code, the site-specific products endpoint now returns `price_tier_list` and `price_tier_usage_quantity` which can be used to determine the current price tier (see https://github.com/Automattic/wp-calypso/pull/51661 for a related example).
- Since D60448-code, the shopping-cart endpoint now returns `current_quantity` for each product which should be the number of units for the Jetpack Search product. (This is probably the same as `price_tier_usage_quantity`, but could be helpful too.)

We can probably work on this soon if no one else gets to it first.

**Comment by sirbrillig** [comment]
https://github.com/Automattic/wp-calypso/pull/52308 should fix this.
