### ISSUE TITLE
Translated patterns UI vs content

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#46952]
A couple confusing points around translated patterns and translated patterns UI:

### Account English, site Spanish 

1. Have your UI language in English
2. Have your site's locale in Spanish
3. Open block editor and patterns inserter
4. Note:
    <img width="383" alt="Screenshot 2020-10-30 at 15 33 15" src="https://user-images.githubusercontent.com/87168/97711274-907e2e00-1ac5-11eb-9bf6-4106816945f2.png">
  - Categories list in site's locale: expected in UI locale 🚫 
  - Pattern content in site's locale: as expected 👍 
  - Pattern names in UI locale: as expected 👍 
  - Note how "contacto" is in lowercase, is that correct?

### Account Spanish, site English

The same is visible if I set my account in Spanish, but site is in English:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/87168/97714980-827edc00-1aca-11eb-8769-b1fdd6803df9.png">

### Account Spanish, site Spanish

Furthermore, when I change both UI and site's locale to Spanish, I still see pattern names in English:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/87168/97711836-43e72280-1ac6-11eb-9717-aa93281fc1bc.png">

I couldn't find the pattern name from [Translator](https://translate.wordpress.com/).

Actually looks like some of them are translated, but I couldn't find those from translate tool either:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/87168/97712544-40a06680-1ac7-11eb-92bf-2f95fa268864.png">

**Comment by ramonjd** [comment]
> Categories list in site's locale: expected in UI locale 

The [category labels](https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/block-patterns/class-block-patterns-from-api.php#L99) come from the patterns API. Just confirming that @lsl resent dotcompatterns.wordpress.com off for retranslation this week. 

That might resolve many of the issues we're seeing here I hope!

**Comment by ianstewart** [comment]
@simison it took me a while here to realize the issue until I tried it out in French and the rest of the Editor UI. :)

### Category Labels in select menu translated when they shouldn't be

Current Status: Translated when site language is non-EN but UI is EN.

Expected Status: Category labels should remain in English when only the site language settings have changed but not the UI language settings.

Meaning these labels here, because they're UI, should be in English.

![image](https://user-images.githubusercontent.com/545779/97895242-25b53880-1cf9-11eb-91f5-4985ab969f64.png)

To reproduce:

1. Visit settings and change your language to a non-EN language while keeping your /me UI settings in EN.
2. Compare the select menu for category labels with other parts of the Gutenberg UI.

@apeatling we'll need to either update the Patterns Toolkit API here or how it integrates with the Editor.

### Pattern names never translated.

With both the site and UI language settings set to non_EN it looks like these are incompletely translated in multiple languages.

@ramonjd @lsl or @andrewserong these should be corrected over time as translations come in, correct?

**Comment by ramonjd** [comment]
> @ramonjd @lsl or @andrewserong these should be corrected over time as translations come in, correct?

I'm _fairly_ confident this is correct. Just looking at strand 68958 (sv) as an example in Linguine, the Pattern title string `Layered Images and Call to Action` is being translated.

**Comment by ianstewart** [comment]
Great. I believe we're also tracking in another repo a task to send these out for translation automatically. That'll help prevent the mixed or late translations.

That leaves just the UI update to be taken care of by View Engineering.

**Comment by apeatling** [comment]
Grabbing this one 👍

**Comment by apeatling** [comment]
I've updated the patterns in editor code to always use the user language setting in https://github.com/Automattic/wp-calypso/pull/47297, although I'm not sure my conclusion was correct from the above. Does it make sense to use the user's language setting here?

**Comment by ianstewart** [comment]
Left a comment on the PR!

**Comment by andrewserong** [comment]
Just updating this issue: #47297 was closed with the conclusion that:

> the UI elements should be in the user's language but any content that actually gets inserted into the site should be in the site's language.

I've added this issue to Ganon's patterns backlog, and that the goal would be for the API (or somehow the consumer) to support displaying pattern categories in the user's locale, but the pattern content in the _site's_ locale. I believe this would be non-trivial to implement in a single API call due to locale switching being an expensive operation. So, perhaps another way to do it would be:

* [ ] Add an additional endpoint that gets a list of _just_ the pattern categories in one locale, ensure the category _slugs_ are not translated
* [ ] In the existing API endpoint for getting patterns, ensure that the category slugs are not translated
* [ ] In the consuming code, get the list of pattern categories using the user's locale and store them in a variable
* [ ] In the consuming code, get the list of patterns in the site's locale, and look up each category based on its untranslated slug to get the translated category name, when registering the patterns

I _think_ something like that should work, and would result in the fewest locale switches.

I also assume that most of the time, for most of our users, the user's locale and the site's locale will be the same? So I'll add a low priority label to this one, but let us know if you think it's a higher priority to fix this @apeatling!

**Comment by simison** [comment]
@ramonjd @autumnfjeld @andrewserong would anything here be relevant for page template picker i18n?

**Comment by andrewserong** [comment]
@simison I think a possible path forward to addressing this in the page layout picker (but possibly for the pattern inserter, too) would be to create a separate pattern categories endpoint (raised here: https://github.com/Automattic/wp-calypso/issues/49851) so that the pattern categories could be requested in one locale, but then the patterns themselves would be requested in another. From the sounds of it, the additional endpoint isn't part of the MVP (?), so an alternative could be to hard-code the pattern categories into the page layout picker if you wanted to preserve a different locale for the categories to that of the patterns.

**Comment by andrewserong** [comment]
I believe this one was resolved by @ramonjd's PR: https://github.com/Automattic/wp-calypso/pull/54636 which switched the dotcom patterns to be fetched using the user locale, for consistency with patterns sourced from the .org patterns directory. I'll close this issue out now, but feel free to re-open if it's still an issue / anyone wants to pick it up and investigate further.
