### ISSUE TITLE
Notifications: Some text nodes do not display properly.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46961]
Core File blocks do not display properly in notifications.

Front-End | Email | Notifs
--- | --- | ---
<img width="730" alt="Screen Shot 2020-10-30 at 9 44 01 AM" src="https://user-images.githubusercontent.com/349751/97733095-9f002180-1a94-11eb-9629-a48e02367b80.png"> | <img width="746" alt="Screen Shot 2020-10-30 at 9 44 11 AM" src="https://user-images.githubusercontent.com/349751/97733110-a45d6c00-1a94-11eb-850e-2c238a6ad955.png"> | <img width="470" alt="Screen Shot 2020-10-30 at 9 45 06 AM" src="https://user-images.githubusercontent.com/349751/97733120-a7585c80-1a94-11eb-9479-6ae128c956cc.png">

**Comment by krymson24** [comment]
I tried to continue where you left off. In general, I'd recommend whoever looks at this, to step through using a `debugger`. `console.log` does not show you the details of the `sub_range` that the `build_chunks` function relies on.

Furthermore, I tried reverting some of the code we introduced to this file, and it looks like this problem existed before, so it wasn't a new regression we caused.

If you want to focus on one notification so that there's less noise, you can hardcode something like this:

```
		const noteGroups = groupBy( this.props.notes, ( { timestamp } ) => {
			const time = new Date( timestamp );
			return findIndex( timeGroups, ( [ after, before ] ) => before < time && time <= after );
		} );

		// console.log('noteGroups', noteGroups);

		const effectiveNoteGroups = {
			[0]:[],
			[1]: noteGroups[1] ? [noteGroups[1][0]] : []
		}

		// console.log('effectiveNoteGroups', effectiveNoteGroups)
```

Note that as time goes by, the notification you want to evaluate will appear in a different group. [0] represents "Today", [1] represents "Yesterday"... etc.

in `apps/notifications/src/panel/templates/note-list.jsx`

**Comment by kwight** [comment]
By doing a rough bisect, I found that these issues were introduced with https://github.com/Automattic/wp-calypso/pull/45710. @blackjackkent can you take a look please?

**Comment by krymson24** [comment]
I manually applied these files locally:

https://raw.githubusercontent.com/Automattic/wp-calypso/b24c6ceffc236ca57f7eb54b459a5f421c7d94ba/apps/notifications/src/panel/templates/functions.jsx
https://raw.githubusercontent.com/Automattic/wp-calypso/fe44257b9e3bbf6aff1692ef5601eda1d7588d4d/apps/notifications/src/panel/indices-to-html/index.js

The commits are shown in the URL.

When applying those, you can already see some unexpected behavior rendering certain elements.

<img width="517" alt="Screen Shot 2020-11-02 at 6 06 24 PM" src="https://user-images.githubusercontent.com/66652282/97929022-3fc13c00-1d36-11eb-8662-9d17dd700fa2.png">
<img width="450" alt="Screen Shot 2020-11-02 at 6 06 48 PM" src="https://user-images.githubusercontent.com/66652282/97929024-4059d280-1d36-11eb-8b75-e53fb1580092.png">

Currently, you can see the following issues:

<img width="395" alt="Screen Shot 2020-11-02 at 6 09 47 PM" src="https://user-images.githubusercontent.com/66652282/97929854-1bfef580-1d38-11eb-8b95-0b847c67db6d.png">
<img width="396" alt="Screen Shot 2020-11-02 at 6 20 14 PM" src="https://user-images.githubusercontent.com/66652282/97929856-1d302280-1d38-11eb-8cef-9a1c8da3d630.png">
<img width="405" alt="Screen Shot 2020-11-02 at 6 19 50 PM" src="https://user-images.githubusercontent.com/66652282/97929857-1dc8b900-1d38-11eb-9c79-d46e5ad25cc2.png">

With the fixes, there are still some changes that render incorrectly
<img width="365" alt="Screen Shot 2020-11-02 at 6 21 24 PM" src="https://user-images.githubusercontent.com/66652282/97929996-82841380-1d38-11eb-908c-d34821253f3e.png">
<img width="358" alt="Screen Shot 2020-11-02 at 6 22 43 PM" src="https://user-images.githubusercontent.com/66652282/97930002-844dd700-1d38-11eb-88a1-c0be04405b9e.png">
<img width="373" alt="Screen Shot 2020-11-02 at 6 23 39 PM" src="https://user-images.githubusercontent.com/66652282/97930025-90399900-1d38-11eb-814d-67ed4acfd4a6.png">

**Comment by krymson24** [comment]
Despite this problem being introduced in that specific commit, the root problem is what Miguel described, in that elements with the same starting and ending position are not handled correctly.

The quick, but incomplete fix would be to remove specific tags where this problem is occurring (I imagine it could any element), but the ones that are apparent so far are `p` and `figure` tags. If we remove these from being allowed (backend and frontend), you'll see that this specific content renders correctly.

<img width="355" alt="Screen Shot 2020-11-03 at 1 11 34 AM" src="https://user-images.githubusercontent.com/66652282/97954543-ce06e380-1d71-11eb-9981-fe50a903f354.png">
<img width="345" alt="Screen Shot 2020-11-03 at 1 13 07 AM" src="https://user-images.githubusercontent.com/66652282/97954545-ce9f7a00-1d71-11eb-80ba-507324e4606f.png">

Going to need more time to figure out the "right" way of solving this.

**Comment by kwight** [comment]
@krymson24 Ah, complicated. 🙃 Great, use your best judgement – it's a very obvious visual regression being seen by everyone, so do what you can to minimize that and then keep digging. 🤔

**Comment by krymson24** [comment]
I'm leveraging Miguel's work here and I'm noticing a few things -- the API has elements with the same starting and ending indices, but those are never returned on the frontend. The frontend has a concept of `empty_ranges`, but I'm finding that ranges on the frontend are never empty, and the frontend never receives those elements with the same starting and ending indices. The final content that is being send could be using those indices in their calculation, but I'm not sure yet if that's the root cause of the problem

The frontend algorithm is also quite complicated, so I haven't found what I need to fix yet, but I'm going to need to step through it a few more times to understand it better.

**Comment by krymson24** [comment]
Another finding --

This happens for elements with the same starting and ending indices. If the element is an `hr` (and maybe others I haven't found) this gets returned to the frontend, however, if they're other elements (like `p` or `figure` elements) they do not get returned with the same starting and ending indices. I'm thinking that this has to do with certain fallbacks that we have, which makes it so that we don't render content within the element (like an `iframe` in a `figure`), and so whatever content we end up rendering, perhaps isn't being calculated correctly...? Going to do some pairing tomorrow to try and get to the bottom of this.

**Comment by sixhours** [comment]
If you need more test data, this post breaks up pretty badly: pbAPfg-13V-p2

**Comment by krymson24** [comment]
I haven't found the solution to this yet, but I'm on a roll.

Here's the work I've done so far --

I've visualized what exactly the algorithm is doing with the indices. Each index is associated with a meta data and a tag name.
![IMG_0011](https://user-images.githubusercontent.com/66652282/98333440-c2fcbf00-1fce-11eb-909b-61bcac6d5a78.jpg)

I've also visualized and compared what the frontend notification renders, what a post actually contains, and what the backend actually parses. (hint, they're all different)
![IMG_0012](https://user-images.githubusercontent.com/66652282/98333452-c7c17300-1fce-11eb-936c-c4dc02b054b1.jpg)

One of the changes that's needed is related to our fix for `figure` elements not rendering. This was a change made here: D51894-code

Specifically this:

```
		if ( substr( trim( $html ), 0, 7 ) === '<figure' ) {
			$html = '<div>' . $html . '</div>';
		}
```

Adds an extra element that the backend algorithm needs to parse that doesn't match up with the text and indices returned to the frontend.

I've added some changes to reverse remove this extra `div` on the backend as it gets returned to the client. My codebase is riddled with code so I can't put a diff up a this moment.

This is not all that needs to be fixed. The backend currently uses HTML where some elements are separated by newline elements, and some are not. I'm still investigating into why that is the case, but it's definitely throwing off the indices.
<img width="888" alt="Screen Shot 2020-11-06 at 1 32 00 AM" src="https://user-images.githubusercontent.com/66652282/98333988-e2481c00-1fcf-11eb-8533-2afd859095ce.png">

I somehow lost one on the frontend here.
<img width="644" alt="Screen Shot 2020-11-06 at 1 35 57 AM" src="https://user-images.githubusercontent.com/66652282/98334322-9d70b500-1fd0-11eb-957d-dc11e2a6946a.png">

I'm really close!

**Comment by kwight** [comment]
Fantastic digging @krymson24 , keep at it! 🚀

**Comment by krymson24** [comment]
Hopefully this fix most of the rendering issues we're seeing! D52422-code

**Comment by mmtr** [comment]
Awesome work so far @krymson24! I updated https://github.com/Automattic/wp-calypso/pull/46965 with a hopefully more stable and robust approach that (it also depends on some backend changes but they are minimal: D52453-code).

If that works, we may not need D52422-code.

**Comment by krymson24** [comment]
@mmtr for more context the reason for my logic in https://href.li/?D52422-code is because Emogrifier returns `figure` elements without any HTML spacing. From the example below you can tell that the other elements are spaced out appropriately, but `figures` are not

It seems that the backend algorithm requires that to identify "text" nodes that will return the accurate start and end indices. So, in order to fabricate these required "text" nodes, I'm adding the `&nbsp;`

```
<div class="wp-block-jetpack-slideshow aligncenter" style="margin-bottom:1.5em;position:relative;">
<div class="wp-block-jetpack-slideshow_container swiper-container" style="width:100%;overflow:hidden;opacity:0;">
<ul class="wp-block-jetpack-slideshow_swiper-wrapper swiper-wrapper" style="padding:0;margin:0;line-height:normal;display:flex;">
<li class="wp-block-jetpack-slideshow_slide swiper-slide" style="display:flex;height:100%;width:100%;padding:0;margin:0;line-height:normal;">
<figure style="align-items:center;display:flex;height:100%;justify-content:center;margin:0;position:relative;width:100%;"><img alt="" class="wp-block-jetpack-slideshow_image wp-image-31" src="example.com/2020/09/rachel-pfuetzner-0fn7fxv1ewa-unsplash.jpg?w=750"></figure>&nbsp;
</li>
<li class="wp-block-jetpack-slideshow_slide swiper-slide" style="display:flex;height:100%;width:100%;padding:0;margin:0;line-height:normal;">
<figure style="align-items:center;display:flex;height:100%;justify-content:center;margin:0;position:relative;width:100%;"><img alt="" class="wp-block-jetpack-slideshow_image wp-image-28" src="example.com/2020/09/qi-bin-w4hbafegiac-unsplash.jpg?w=750"></figure>&nbsp;
</li>
<li class="wp-block-jetpack-slideshow_slide swiper-slide" style="display:flex;height:100%;width:100%;padding:0;margin:0;line-height:normal;">
<figure style="align-items:center;display:flex;height:100%;justify-content:center;margin:0;position:relative;width:100%;"><img alt="" class="wp-block-jetpack-slideshow_image wp-image-85" src="example.com/2020/10/x8vqgd8kuypu8kqbrsz4bk-1200-80.jpg?w=1024"></figure>&nbsp;
</li>
</ul>
```
