### ISSUE TITLE
My Home: New card for "What's New" feature/product announcements

### ISSUE THREAD

**Issue by lauac** [Automattic/wp-calypso#47013]
What's New feature to notify users of latest features and product updates

Scoping for WP.com kicked off: pbAPfg-Yo-p2

**Comment by davemart-in** [comment]
Rick mentioned that it would be great to collaborate with @dubielzyk on the Gutenberg welcome tour stuff he's been designing.

**Comment by dubielzyk** [comment]
Would love to collaborate :) I've got a section in the new Help sidebar reserved for new announcement:
![image](https://user-images.githubusercontent.com/2896062/98178442-fe2ebd80-1efc-11eb-882b-bddd730bacb3.png)

The idea was that some of the bigger features would have modals as you enter the Editor:
![image](https://user-images.githubusercontent.com/2896062/98179690-9cbc1e00-1eff-11eb-92ac-13440a9cd685.png)

**Comment by lauac** [comment]
Thanks for connecting the dots, Dave. The new Help sidebar design looks great, @dubielzyk!

@lcollette and @sfougnier are helping out with this and [MarTech will be doing the dev work after the holidays, kicking that part off in Jan 2021](https://martechp2.wordpress.com/2020/11/02/whats-new-notifications-developer-support/#comment-8484).

**Comment by sixhours** [comment]
👋 Hey folks, this repo is public so I've removed the links to private sites and deleted the revisions. Check the FG for more info about using shorthand in public Github threads. :)

**Comment by davemart-in** [comment]
Thanks @sixhours!

**Comment by davipontesblog** [comment]
Adding this to "My Home" pod for consideration. Feel free to close it if we don't intend on adding this :)

**Comment by jordesign** [comment]
Perhaps something for @jeffgolenski to consider in his design work for the Primary/Secondary/Tertiary areas?

We do already highlight WPCOM features in the tertiary area - so this could be a part of that?

**Comment by autumnfjeld** [comment]
@lauac I'm going to close this issue, since we are in active rework of my home and the idea has been flagged with The My Home Pod.  I think this is also a bit bigger issue than a github task, for instance we might need education and process set up to let teams know they can publicize a new feature in a dedicated area of My Home.  I'd suggest starting a conversation in a P2 to get a feel for how a "What's new" section on My Home might work.   Feel free to start that in the My Home Pod p2 d2qGl-p2.

![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)

**Comment by jeffgolenski** [comment]
Thanks @autumnfjeld !
