### ISSUE TITLE
Nav unification: Port over WP Admin color schemes as new options in Calypso /me section.

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#47036]
This issue is part of the effort of combining color schemes in the Nav unification project. 
For the approved direction please see https://github.com/Automattic/wp-calypso/issues/45675#issuecomment-714664414.

### Reference Issues

* Main Issue #45435
  * Color Schemes Issue + Direction  #45675

**Comment by frontdevde** [comment]
@sfougnier @lcollette Design request: for this one we'll need thumbnails for the wp-admin color schemes similar to the ones that already exist in the Calypso Color Scheme picker. Could you please provide us with these? Thank you!

For reference see SVGs for existing color schemes here:
https://github.com/Automattic/wp-calypso/tree/master/client/assets/images/color-schemes

**Comment by mreishus** [comment]
We may be able to do this ourselves by editing the existing svgs and changing the color codes in them.
![2020-11-03_13-18](https://user-images.githubusercontent.com/937354/98030732-12789a80-1dd7-11eb-8cd1-cd8d2aa62e9e.png)

**Comment by mreishus** [comment]
Most wp-admin colors seem to be auto generated from 4 main variables:

```
$base-color: #523f6d;
$icon-color: #ece6f6;
$highlight-color: #a3b745;
$notification-color: #d46f15;
```

**Comment by mreishus** [comment]
- Calypso color scheme definitions in CSS look like this: [link](https://github.com/Automattic/wp-calypso/blob/6ad54be27eab120d41286c3ea90aa1c7071b147d/packages/calypso-color-schemes/src/shared/color-schemes/_sakura.scss#L3)
- Definitions of the variables used in the above link come from: `packages/calypso-color-schemes/src/__color-studio/color-properties.css`  `packages/calypso-color-schemes/src/__color-studio/color-properties-rgb.css`, but these files aren't tracked in git.
- A build process copies these files from `@automattic/color-studio`: [link](https://github.com/Automattic/wp-calypso/blob/6ad54be27eab120d41286c3ea90aa1c7071b147d/packages/calypso-color-schemes/bin/prepare-sass-assets.js#L5-L6)
- https://color-studio.blog/ shows all of the color-studio colors available.
- color-studio is a project made by design systems: pbjpUB-aH-p2

So we may not be able to match the wp-admin colors 1:1, but rather use approximate matches that come from our internal color pallette.  (Although, maybe the wp-admin colors were chosen from the pallette as well, haven't checked)

**Comment by mreishus** [comment]
I created a PR for adding ectoplasm here.  This could serve as a basis for making other color schemes: https://github.com/Automattic/wp-calypso/pull/47075

* Used https://color-studio.blog/ as a reference
* In the [SCSS file](https://github.com/Automattic/wp-calypso/pull/47075/files#diff-3be7607d1278482183f0c3421d924779cf27ade277bb45125f7c631065328a3a), I manually picked sidebar and masterbar colors from the https://color-studio.blog/ pallette, looking to match the wp-admin color scheme as close as possible.
* Modified the masterbar to be darker than the sidebar to fit with other calypso schemes
* For color-primary and color-accent styles, you basically only get to pick the hue from https://color-studio.blog/, as calypso "wants" --color-primary and --color-accent to be -50 lightness.
* For the SVG, I manually edited it, setting the same colors I picked in sidebar and masterbar, changing only color codes.  If your editor can display the color of hex color codes it's not too bad:
![2020-11-03_16-38](https://user-images.githubusercontent.com/937354/98048297-039fe100-1df3-11eb-92c7-f15bde38f5c6.png)

This was a decent amount of work so, maybe one PR per color scheme is the way to go?  Any thoughts here?

**Comment by frontdevde** [comment]
> We may be able to do this ourselves by editing the existing svgs and changing the color codes in them.

Yes, we can easily change them. I was more thinking for design to provide us with guidance on how the thumbnails should look. That said, it's probably pretty easy for us to deduce the right look given that they simply reflect the implemented color scheme.

> So we may not be able to match the wp-admin colors 1:1, but rather use approximate matches that come from our internal color pallette. (Although, maybe the wp-admin colors were chosen from the pallette as well, haven't checked)

I'd argue it's imperative that we do match the wp-admin colors 1:1 (either by matching in Calyso or adjusting in wp-admin). The goal of nav unification is to make the two interfaces identical. If colors don't match up exactly, colors will change when switching between menu items.

**Comment by mreishus** [comment]
> I'd argue it's imperative that we do match the wp-admin colors 1:1 (either by matching in Calyso or adjusting in wp-admin). The goal of nav unification is to make the two interfaces identical. If colors don't match up exactly, colors will change when switching between menu items.

We do plan to remove the color scheme setting from wp-admin and have it read from calypso, so after all steps are completed, it would match wp-admin 1:1.  The issue is that calypso (and other products) have standardized on a standard color pallette, https://color-studio.blog/  or npm package `@automattic/color-studio`, and the current wp-admin themes don't fit within that pallette.

**Comment by mreishus** [comment]
Continued discussion here: https://github.com/Automattic/wp-calypso/issues/47103

**Comment by mreishus** [comment]
## Link to PRs dealing with individual schemes

* Ectoplasm - #47122 
* Sunrise - #47171 
* Ocean - Awaiting Calypso ocean to be renamed
* Midnight - Awaiting Calypso midnight to be renamed
* Coffee - None yet
* Blue - None yet
* Modern - None yet
* Light - None yet
* Default - None yet, unsure if we need to port this one

**Comment by frontdevde** [comment]
> Default - None yet, unsure if we need to port this one

I don't think we need to, right? Thinking out loud here: Initially, if we launch all of color schemes early, the default color scheme on the wp-admin side would be replaced by Classic Bright i.e. current Calypso colors. Then once we launch nav unification the default will be replaced by the new dark colors. With than in mind it seems like we wouldn't need to port the wp-admin default color scheme over to Calypso (but we'd definitely need to port over default Calypso Classic Bright to wp-admin). If folks want the old colours back, they can select the new Classic Dark theme we're creating that's very close to the wp-admin color scheme.

**Comment by frontdevde** [comment]
Closing as last remaining task is logged as a new issue here https://github.com/Automattic/wp-calypso/issues/47597
