### ISSUE TITLE
Me: Support: two help links next to each other in sidebar

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#4704]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/me (get there by clicking "Me" avatar link in toolbar)
2. Look at sidebar.

#### What I expected
Only one Help link at the bottom.

#### What happened instead
Two help links.

<img width="331" alt="screen shot 2016-04-13 at 09 08 18" src="https://cloud.githubusercontent.com/assets/66797/14500643/b71bfa24-0157-11e6-8aa8-0aaf7383f129.png">

**Comment by folletto** [comment]
Related to: #4254

**Comment by jasmussen** [comment]
Thanks for opening this issue. 

My immediate reaction was to hide the sidebar footer when on the Me section — because duplicate/redundant navigation is not often a good thing. 

Thinking more about it though, I'd rather we have the footer built in such a way that we can hide the *item* instead, because we might still put in a language switcher in the footer. (In fact we might point the help link onto something else entirely, but that's a different story for a different time).

But let's say we had "Help" and a language switcher here, would it actually make sense to hide the help link here? It'd be the only page it was hidden on. I'm frankly not sure what's best.

**Comment by folletto** [comment]
> I'm frankly not sure what's best.

...also, what happens when you get a new message, given we want that to indicate it in the future (no?)?

**Comment by lancewillett** [comment]
#4715

**Comment by jasmussen** [comment]
>  ...also, what happens when you get a new message, given we want that to indicate it in the future (no?)?

I think #4715 is a fine solution for now. If/when we introduce new features to the footer area, we can revisit this.

**Comment by lancewillett** [comment]
Is this bug related to Help text changes? Small screens, current section title is overlapping: https://github.com/Automattic/wp-calypso/issues/4717
