### ISSUE TITLE
Nav Unification: Show a modal to customers the first time they log in 

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#47049]
**What**

If a user is logging in for the first time since the nav unification project is enabled, show them a modal explaining the recent changes.

**Why**

We need to help customers orient themselves to the change by explaining what has changed, the reasons behind it and how it will benefit them.

**Acceptance criteria**
* Should a user login for the first time since the nav unification change. They will see a [modal](https://github.com/WordPress/gutenberg/tree/d9e7541fe29c0022f2f5de2570ec60bee670aede/packages/components/src/guide#readme) which explains the recent changes to them.
* Should a user close the modal, they will not be presented with this again upon future logins.

**Resources**

For any design improvements, adding some animated GIFs would be preferred see https://github.com/Automattic/wp-calypso/issues/47049#issuecomment-737627688

Design i1 JPGs:
* [Desktop.zip](https://github.com/Automattic/wp-calypso/files/5689823/Desktop.zip)
* [Mobile.zip](https://github.com/Automattic/wp-calypso/files/5689825/Mobile.zip)

Design i2 GIFs, JPGs + mp4 walkthrough videos:
* [Desktop.zip](https://github.com/Automattic/wp-calypso/files/5633314/Desktop.zip)
* [Mobile.zip](https://github.com/Automattic/wp-calypso/files/5633317/Mobile.zip)

Design files:
* [Figma designs](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=1166%3A75340)

Related to https://github.com/Automattic/wp-calypso/issues/47047

**Comment by cpapazoglou** [comment]
@davemart-in could you please elaborate more on this? Do we have any designs, user journey?

**Comment by davemart-in** [comment]
I'll cc @sfougnier on this one.

**Comment by ghost** [comment]
I have been exploring using a stepped approach that allows us to showcase the updated features. The intention of this is to introduce the unified nav and tell a brief story of how it works in an attempt to cut down on any confusion. 

A few things:
- The copy is not final but I wanted to get the design out in the world.
- Is there potential to use animated gifs in lieu of static imagery? It could help tell the story and show off specific interactions.

**Desktop**

<img width="1440" alt="Desktop - Modal 1" src="https://user-images.githubusercontent.com/67021691/100025573-10db3a80-2db7-11eb-8b4b-ab7eb29ce3e9.png">
<img width="1440" alt="Desktop - Modal 2" src="https://user-images.githubusercontent.com/67021691/100025576-1173d100-2db7-11eb-99e3-f5fad8aa2b3d.png">
<img width="1440" alt="Desktop - Modal 3" src="https://user-images.githubusercontent.com/67021691/100025577-1173d100-2db7-11eb-8ab2-7602c55d0ce4.png">

**Mobile**

<img width="1360" alt="Screen Shot 2020-11-23 at 6 02 59 PM" src="https://user-images.githubusercontent.com/67021691/100025621-25b7ce00-2db7-11eb-96c4-af9793383523.png">

[Figma link](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=1120%3A2503)

**Comment by cpapazoglou** [comment]
Thanks @sfougnier for working on this! This stepped approach seems very good and makes sense! 

> The copy is not final but I wanted to get the design out in the world.

I understand that the copy is not final, but is the `wp-admin` wording something that may confuse most of the simple users? Many of them may not even know its existence. A usp for all the users would be "Faster navigation" cause we have surfaced the most used links (Posts, Pages) and we have also used the flyouts.

> Is there potential to use animated gifs in lieu of static imagery? It could help tell the story and show off specific interactions.

I don't see a blocker here, go for it! We just need to make sure that we create images / gifs for the variation that we will launch (currently we have developed only i1).

**Comment by ghost** [comment]
> is the wp-admin wording something that may confuse most of the simple users?

Agreed, I definitely don't think we would want to include that jargon here. I imagine that can be cut, but I am not the best wordsmith and wanted to express intent here.

> I don't see a blocker here, go for it! We just need to make sure that we create images / gifs for the variation that we will launch (currently we have developed only i1).

Awesome! I can work on creating those.

**Comment by ghost** [comment]
For pairing this modal with the sidebar design that's currently being tested, let's use static designs:
<img width="1440" alt="Desktop - Modal 4" src="https://user-images.githubusercontent.com/67021691/102101942-4218ba80-3df9-11eb-818f-6cfe71dbc99e.png">
<img width="1440" alt="Desktop - Modal 5" src="https://user-images.githubusercontent.com/67021691/102101948-4349e780-3df9-11eb-8aaf-b88efe2dcd6e.png">
<img width="1440" alt="Desktop - Modal 6" src="https://user-images.githubusercontent.com/67021691/102101952-43e27e00-3df9-11eb-9977-c9ba679fb229.png">

<img width="1274" alt="Screen Shot 2020-12-14 at 10 43 35 AM" src="https://user-images.githubusercontent.com/67021691/102101915-39c07f80-3df9-11eb-9588-e78659d363ab.png">


For any design improvements, adding some animated GIFs would be preferred:
 ![Desktop](https://user-images.githubusercontent.com/67021691/100957048-c9a42680-34e7-11eb-8f12-cce3361b2b5f.gif)
![Mobile](https://user-images.githubusercontent.com/67021691/100956745-27843e80-34e7-11eb-9580-71c5b3c58a4b.gif)

**Design i1 JPGs**
[Desktop.zip](https://github.com/Automattic/wp-calypso/files/5689823/Desktop.zip)
[Mobile.zip](https://github.com/Automattic/wp-calypso/files/5689825/Mobile.zip)


**Design i2 GIFs, JPGs + mp4 walkthrough videos**
[Desktop.zip](https://github.com/Automattic/wp-calypso/files/5633314/Desktop.zip)
[Mobile.zip](https://github.com/Automattic/wp-calypso/files/5633317/Mobile.zip)

**Design files**
[Figma designs
](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=1166%3A75340)

**Comment by obenland** [comment]
@davemart-in Priority-wise, should this still go into next iteration or should we focus on alpha feedback first?

**Comment by cpapazoglou** [comment]
@sfougnier I am afraid you have created visuals with the new designs (i2) that are not developed. Should we create the visuals with i1? Or is it something I am missing?

**Comment by cpapazoglou** [comment]
@davemart-in , sorry for the double ping ❤️ ! In which environments / cases should this modal be shown:

- Calypso Screens
- Calypso block editor
- wp-admin

Also, are we showing it only once?

**Comment by davemart-in** [comment]
> should this still go into next iteration or should we focus on alpha feedback first?

@obenland Up to you. We'll need both before launch.

> In which environments / cases should this modal be shown:

@cpapazoglou I'd say we could keep it to `Calypso Screens` to reduce scope.

> Also, are we showing it only once?

Yes, users should only ever see this modal once.

**Comment by ghost** [comment]
> Should we create the visuals with i1? Or is it something I am missing?

@cpapazoglou I added i1 visuals to my comment above. Let's keep anything i1 static for now and reserve the fancy GIFs for any design improvements.

**Comment by getdave** [comment]
Scope and designs look to have been confirmed.

This now requires investigation and quick research into how much effort is required so we have a handle on scope.

**Comment by frontdevde** [comment]
Note: there's a WP.com What’s New Product Announcements feature (pbBQWj-AH-p2) that will do something similar in Calypso. They are using the core [Guide](https://github.com/WordPress/gutenberg/tree/d9e7541fe29c0022f2f5de2570ec60bee670aede/packages/components/src/guide#readme) component and it was suggested we consider this as well.

**Comment by tjcafferkey** [comment]
**Couple of questions:**
* Should we only be showing this to existing users, or new users as well?
* To avoid any dependency on Calypso should we create this in `/packages/[announcements / nav-unification]` in case scope increases in future and this does end up getting rolled out to other environments? (E.g. WPCOM Block Editor, WP Admin)

**Comment by cpapazoglou** [comment]
> Should we only be showing this to existing users, or new users as well?

That's a good question. Current plans, include enabling nav-unification for specific segments ( eg all users with User IDs ending in `3` ) and then ramping up. With that in mind, new users should also be shown that modal _when_ their User ID is included to the launched segment. On the other hand, since we are not a/b testing at all it could make sense enabling `nav-unification` for **all** new users and thus not needing to show that modal. But again, showing that modal doesn't do any harm in any case. So, for the sake of this issue, I lean to yes.

**Comment by tjcafferkey** [comment]
Thanks @cpapazoglou, I guess it will be based on the following criteria then:

* User is an existing user, or a new user.
* User falls into the segment which nav unification is enabled for.
* User has not seen this modal before.

On this last point. How do we want to track this state? The obvious answer would be localStorage however we know that if the user:

* Clears browser data
* Uses a different browser
* Uses a different device

Then they will be shown the modal repeatedly which could become annoying/frustrating over time. For the Block Editor NUX modal this value is [sent to a specific endpoint](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/store.js#L54-L66) when dismissed. For comparison the [Whats New](https://github.com/Automattic/wp-calypso/pull/48722) modal isn't tracked at all, since it's accessible via the menu in the editor.

Any ideas/preference around this aspect of the functionality?

**Comment by cpapazoglou** [comment]
> I guess it will be based on the following criteria then: ... 

Hmm, now that I read my comment, my answer "yes" doesn't make sense. What I meant is, show the modal regardless of whether the user is new or existing. Just use `config.isEnabled( 'nav-unification' )` and whether the modal hasn't been shown before.

> How do we want to track this state

Not sure how this pbBQWj-AH-p2 will work, I suppose it should already have a tracking mechanism. FWIW though, `Banner` already has a tracking mechanism 
https://github.com/Automattic/wp-calypso/blob/ba85297f6f21d08cd2c693040b8c2c3b2ac03185/client/components/banner/README.md#L33

**Comment by tjcafferkey** [comment]
Sorry, I think I miscommunicated what I meant by tracking the state. The tracking you mention above is tracking events, whereas I meant how we want to keep track of the state of the modal so that we know it has been shown (e.g. persistent storage).

I'll move towards a localStorage solution for now and we can update that if required.

**Comment by cpapazoglou** [comment]
> I think I miscommunicated what I meant by tracking the state ...

Nope, you did pretty well! I have probably guided you to the wrong line. Here you are https://github.com/Automattic/wp-calypso/blob/ed3e91545e431da92beeffcbe80289eadde067c0/client/components/banner/index.jsx#L49-L50

with `dismissTemporary = false`

You can better understand how it works here https://github.com/Automattic/wp-calypso/blob/2b8a9b4f46663d567724d5c1a99ec20d637eddd8/client/blocks/dismissible-card/index.jsx#L82-L88

**Comment by tjcafferkey** [comment]
By the look of things the [`<Guide />`](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/guide) component does not achieve 100% design parity by default unless some we start overriding the component markup & styles. The guide component renders the image and text on top of each other rather than side-by-side as per the [designs](9cy0DIowQkPAu0rodb9jsL-fi-1166%3A75342).

**(Ignore the placeholder image)**

![Screenshot 2021-02-01 at 16 22 11](https://user-images.githubusercontent.com/8639742/106486525-a5de6c00-64a9-11eb-950a-34e165279912.png)

The way around this would be to use a `<GuidePage />` component but as you can see [here](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/guide/page.js) this isn't recommended as it's deprecated. (Note: This is what was done for the [Whats New modal](https://github.com/Automattic/wp-calypso/pull/48722/files#diff-fa67e080df3b2f314ea8ec9574b3aecd1a20e7318921b3853dde7ecef9ab6472R206-R239)).

It seems like there are two obvious options here:

1. Use the `<Guide />` component how it's recommended, which will render the image and text on top of each other rather than side-by-side.
2. Use the (deprecated) `<GuidePage />` component with `<Guide />` and using additional markup and styles (overriding the core components styles) achieve design parity.

cc: @sfougnier @getdave

**Comment by getdave** [comment]
Thanks for checking in @tjcafferkey and for the nice research into this.

Using the deprecated component would seem like it could cause maintenance issues down the line. As you say it looks like the `pages` prop of `<Guide />` is the right direction.

The Issue appears to be that by default there is no built in mechanism for a "side-by-side" layout.

How about we [spin up Storybook locally](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md#storybook) and test to see if it's possible to provide markup + style overides to achieve a side-by-side layout using the `<Guide>`?

Failing that, we should check whether @sfougnier is ok to adjust the design for the sake of expediency. If (as I suspect) it turns out that the side-by-side layout is a critical piece of the design, then we should get some context from the team that implemented the welcome modal as to why they decided it was ok to use the `GuidePage` and what their upgrade/maintenance plans are for the future.

I'd like to avoid Ajax getting sidetracked with developing an entirely new component if possible.

**Comment by ghost** [comment]
What's the reason we can't follow the same side-by-side layout that's in the What's new modal? 
This design was meant to reuse that component. It seems like the stacked approach deviates from that.

**Comment by tjcafferkey** [comment]
>This design was meant to reuse that component

@sfougnier sorry for not updating this issue yesterday. The good news is we are able to make it look like the What's New modal by overriding the `<Guide />` core CSS (which is what was done in the case of What's New).

However, we may need to deviate from the mobile designs (which look different to the What's New modal) because the markup doesn't allow for certain aspects of it, mainly around the pagination and its position.

This PR should be ready for review today so it would be great if you could also cast your eye over it if you have time 😄

**Comment by mmtr** [comment]
I think there are a couple of things to follow up:
- Images contain English texts. Should we display them to users with a different language set?
- We need to make sure that new users don't get this modal, only existing users.

**Comment by tjcafferkey** [comment]
@mmtr yes you're right. I'll be creating separate issues for these to follow up.

**Comment by cpapazoglou** [comment]
> I think there are a couple of things to follow up:
> 
> * Images contain English texts. Should we display them to users with a different language set?
> * We need to make sure that new users don't get this modal, only existing users.

We would need to iterate on the "new users" condition **the day** we actually launch to customers.

**Comment by davemart-in** [comment]
> Images contain English texts. Should we display them to users with a different language set?

I don't think this is necessary. The text in the screenshot is UI based, not informational. User's don't need to be able to read the text within the image to understand what is going on.

**Comment by mmtr** [comment]
> We would need to iterate on the "new users" condition the day we actually launch to customers.

Right, the rollout will be gradual, so we have to handle that. The modal should show up if the nav unification has been enabled for the current logged user after they signed up.

- For the beta launch that is: is_a11n && registered_date <= January 21, 2021.
- For the first rollout (5% of single site users) that is: site_count == 1 && user_id % 100 < 5 && registered_date <= <first_rollout_date>
- Etc.


EDIT: I guess this can be simplified to: 

```
function shouldDisplayNavUnificationModal() {
  if ( hasDismissedModal() ) {
    return false;
  }

  if ( isNavUnificationDisabled() ) {
    return false;
  }

  return getCurrentUserRegisteredDate() <= <LAST_ROLLOUT_DATE>;
}
```

And then update `<LAST_ROLLOUT_DATE>` every time we do a partial rollout.

**Comment by ghost** [comment]
Looks like the modal that accidentally debuted earlier was using the wrong image asset. We should be using these since there's no current plan to implement the visual changes:
[IMG.zip](https://github.com/Automattic/wp-calypso/files/5932960/IMG.zip)

**Comment by Aurorum** [comment]
> Looks like the modal that accidentally debuted earlier was using the wrong image asset. We should be using these since there's no current plan to implement the visual changes:
> [IMG.zip](https://github.com/Automattic/wp-calypso/files/5932960/IMG.zip)

PR in #49827 to update those image assets. :)
