### ISSUE TITLE
Login: improve autofill detection on iOS & Safari

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#47089]
Our login forms are on multiple pages and we can help autofill detect correct inputs with `autocomplete="current-password"` and `autocomplete="username"`.

> Explicitly defining an input element’s autocomplete value lets you support login workflows that couldn’t otherwise be detected by Password AutoFill’s heuristics. For example, the heuristics assume the user name and password inputs are on the same page. If you have a multipage login form, explicitly setting the username and current-password types lets the user tap and fill those inputs, even if they are on separate pages.

via https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

**Comment by vivianxu1230** [comment]
Hi I would love to take on this issue :)

**Comment by vivianxu1230** [comment]
@simison Is this issue is pointing to the client/auth/login.jsx file path? I see some inputs (FormTextInput) fields that could benefit from having the password/username autofill for iOS/Safari. 

Also– is the enhancement only needed for usernames and passwords, or for one-time verification codes as well? I see that in the Apple docs they provide an option for it, but on line 161 of the login.jsx file I see that autocomplete is explicitly set to "off".

**Comment by lsl** [comment]
I believe these changes will need to be made on the [`LoginForm` block](https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/blocks/login/login-form.jsx#L533). ([Used here](https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/blocks/login/index.jsx#L466))

Good catch about [client/auth/login.jsx](https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/auth/login.jsx#L136). I haven't looked too deeply at this but I suspect LoginForm block is used by the wordpress.com/login form and the other being used for something else - oauth prompts perhaps? -- this might also be useful to change but I would start with focusing on one login form for now.

> Also– is the enhancement only needed for usernames and passwords, or for one-time verification codes as well? 

Lets start with only username/passwords for now. 

I don't know about one-time passwords, would browsers try to save these if we change the autocomplete setting? (that could be annoying as they're one time use passwords)

**Comment by p-jackson** [comment]
After deploying I noticed that the password still had `autocomplete="off"` because the `<FormPasswordInput>` component actually [forces the value to be off](https://github.com/Automattic/wp-calypso/blob/b7858d3a2bc03525eae496eb41ab1b49221942db/client/components/forms/form-password-input/index.jsx#L56).

It was still saving my username and password on Safari though ... I'll do a bit more testing now that it's easier to test on mobile too. It could be that the `autoComplete="username"` on the username field is enough to get the heuristic to work and that's why it was testing fine.

**Comment by p-jackson** [comment]
@simison ok so this is sort of fixed. The password hinting is working, however [on mobile the password visibility toggle defaults to "visible"](https://github.com/Automattic/wp-calypso/blob/2b955fe7a8021f6ea9cd118cbadaa1ff9d1c1ee5/client/components/forms/form-password-input/index.jsx#L27). 

This thing:
![Image from iOS-2](https://user-images.githubusercontent.com/1500769/106227918-16d61780-624f-11eb-8833-5ff535389c52.jpg)

Mobile Safari doesn't offer to auto complete the password when the toggle is set to visible. So if the user first makes the password field hidden, _then_ Safari will over to auto complete the password.

This is even though [the docs](https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element) seem to imply that using the `autocomplete` hint allows it to work on plain text fields 🤷 

I've marked as closed because I think addressing this might be a brand new task for designers to think about: should we still default password fields to hidden on mobile? It's been that way since the original `wp-calypso` commit, but maybe password managers on mobile have improved enough since then that it's now better to encourage their use?
Maybe we can take our cue from the mobile app designers. @mattmiklic is it good practice to show the password field by default to make it easier to type on small on-screen keyboards?

**Comment by simison** [comment]
Seems really odd to me to leave it visible by default, especially if it stops autofilling from working. Not an expert on this area though. :-)

**Comment by mattmiklic** [comment]
My 2¢ would be that autofill is more valuable than visible-by-default. I don't know if the same autofill limitation is true for native apps but FWIW we default to not-visible.

**Comment by p-jackson** [comment]
> My 2¢ would be that autofill is more valuable than visible-by-default

I agree. I'll create a PR and @ some folks so we can duke it out there.

Update: PR created #49441
