### ISSUE TITLE
Edge Browser: WP.com login with query string doesn't work

### ISSUE THREAD

**Issue by hitolonen** [Automattic/wp-calypso#47094]
This was first reported by a VIP user using legacy Edge browser, version 44.18362.449.0. I've been able to replicate with Browserstack Windows 10, Edge 18:

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/log-in/
2. The page only loads the W logo, nothing else.
3. Console errors with:

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
SCRIPT438: SCRIPT438: Object doesn't support property or method 'AppBoot'

```
#### What I expected

The default log in screen:

<img width="505" alt="expected result" src="https://user-images.githubusercontent.com/20572314/98104208-cdb83680-1e9e-11eb-84b5-f821afd2c408.png">

#### What happened instead

Only the W logo loads, console errors.

<img width="1860" alt="legacy edge browser" src="https://user-images.githubusercontent.com/20572314/98104303-ed4f5f00-1e9e-11eb-870e-c28a936277ce.png">

#### Browser / OS version

Browserstack Windows 10, Edge 18. User reported OS version unclear, Edge version 44.18362.449.0.

#### Other notes

Similar error https://github.com/Automattic/wp-calypso/pull/40861 https://github.com/Automattic/wp-calypso/pull/39487#discussion_r380585769

**Comment by hitolonen** [comment]
Closing - won't be fixed due to very old browser version.

**Comment by designsimply** [comment]
Re-opening because I encountered the same issue when trying to log in using Edge 44 on Windows 10.

I found that I could reliably reproduce the problem by going to WordPress.com first and then clicking "Log In" which adds a query string to end of the login URL.

Steps to reproduce:

1. Go to https://wordpress.com/
1. Click "Log In".

**Result:** I see a blank screen with a gray WordPress logo and no option to log in. There are errors in the console matching @hitolonen's report.

![image (1)](https://user-images.githubusercontent.com/1119271/99133700-32c70700-25d8-11eb-9304-2f8289c7ee15.png)

![image (2)](https://user-images.githubusercontent.com/1119271/99133703-3a86ab80-25d8-11eb-958a-7a6fec1b47c2.png)

**Note:** I tested from a Win10 VM running on VirtualBox.

![image (3)](https://user-images.githubusercontent.com/1119271/99133707-41152300-25d8-11eb-893f-313e73de487b.png)

**Comment by designsimply** [comment]
Adding on, if I go to https://wordpress.com/log-in I can see the login form but all the options are grayed out and I am unable to enter my username or log in.

![image (4)](https://user-images.githubusercontent.com/1119271/99133871-ec25dc80-25d8-11eb-9ef8-c204b56a19c8.png)

**Comment by designsimply** [comment]
Welp. Somehow I managed to miss the comment about Edge 44 being a legacy version and the note that we don't plan to fix the issue because of that. Sorry for the noise!

**Comment by KokkieH** [comment]
Noting we've had another report of the issue in https://wordpress.com/forums/topic/login-broken-when-using-edge-not-the-chromium-edge-regular-egde/

**Comment by KokkieH** [comment]
For other users running into this, the legacy login page at https://wordpress.com/wp-login.php?no-calypso works for me in Browserstack, so we can suggest that to users who don't have access to the Chromium version of Edge yet.
