### ISSUE TITLE
Focused Launch: show Site Name step only when needed

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47243]
- [ ] Show site title step only if the user hasn't changed the site title yet (e.g. `title === __("Site Title")`). Hide it otherwise
- [ ] If the site title step was ever shown to the user, keep showing it in the flow (requires storing this information in the `@automattic/launch` data store)

**Comment by razvanpapadopol** [comment]
@ollierozdarz what do you think about the following scenario?

1. The user is landing in the editor after creating a site without a custom site title.  They click _Launch_ and the steps look like this:
<img width="472" alt="Screenshot 2020-11-10 at 21 47 52" src="https://user-images.githubusercontent.com/14192054/98726797-a500d700-239f-11eb-94e1-b5ec74911a10.png">

2. The user is customizing the site title and exits the flow without launching.
3. Next time they click _Launch_, steps look like this:
<img width="466" alt="Screenshot 2020-11-10 at 21 48 00" src="https://user-images.githubusercontent.com/14192054/98726821-aaf6b800-239f-11eb-8b70-8730795b58c6.png">

Shouldn't we remember that we displayed the _Name your site_  step and always (as long as they visit using the same browser without clearing local storage) display it even if they changed it?

**Comment by ollierozdarz** [comment]
Hey @razvanpapadopol, thanks for the mention! If I'm reading correctly, it's about 'what happens if a user hasen't yet edited their site title > they via the launch flow > but don't end up launching'?

In my mind there are two options:

**1.** We either treat the Launch button (in the mock) as a submit action, where editing the site title then launching would save the site title. 
**2.** Otherwise, if a user edits the site title here, and doesn't launch, we could simply ask them again next time they open the launch flow. 

It probably boils down to what is possible (and easier) technically.

I do strongly think we should _only_ be displaying (and asking) the user to edit the site title if they have never edited it before, purely as a way to heighten the chances of them purchasing a domain in this flow 🙂

**Comment by razvanpapadopol** [comment]
> 2. Otherwise, if a user edits the site title here, and doesn't launch, we could simply ask them again next time they open the launch flow.

Yes, this is exactly what I was thinking. For consistency, if we're asking them once to edit the site title as part of this flow (and updating the domain suggestions in real-time) we should keep doing that until they launch. 

> we should only be displaying (and asking) the user to edit the site title if they have never edited it before

👌 We'll be checking this condition the first time focused launch flow is started.

**Comment by ciampo** [comment]
Thank you @razvanpapadopol and @ollierozdarz , I've updated this issue's description to reflect the new requirements
