### ISSUE TITLE
Nav Unification: Rename the Ocean color scheme to Aquatic; update user preferences accordingly

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#47256]
## Task

* Rename the Ocean color scheme to Aquatic.
* Develop a one-time script to move user preferences from ocean -> aquatic.
* Right after this is pushed, run the one-time script.

**Context:**  We want to introduce the wp-admin color scheme named ocean, and keep its same name in calypso.  To do that, we'll have to move the existing ocean 'out of the way'.  For more context, see the issues below.

### Reference Issues

* Main Issue #45435
  * Color Schemes Issue + Direction  #45675
    * Port over wp-admin schemes to calypso #47036

**Comment by marekhrabe** [comment]
My launch plan for this migration explained below. It has a few differences from the original description so each of those steps works on their own and removes any time pressure of aligning the databse migration and scheme renaming in Calypso.

### Phase One

Make the current calypso ocean colors respond to both names "ocean" and "aquatic" but hide the "ocean" from the list of available ones in the color scheme picker.

Deploy the above. Since both names have the same colors, there will be no visual regression. Hiding "ocean" means it won't get any new users and everyone picking that scheme will already use the new name "aquatic".

### Phase Two

Write and execute one-off script that processes user options and migrates "ocean" users to "aquatic". Again, no visual regression but we no longer have anyone using "ocean" in the database. Everybody has "aquatic" set.

### Phase Three

After migration done, "ocean" scheme in calypso isn't used by anybody and we can safely:
- update its SCSS file with colors from wp-admin ocean
- update the SVG preview image with new colors
- resurface the scheme in the picker UI
- deploy

Phase three will happen as part of #47036.

### Final result

All users who were using "Ocean" will see they have "Aquatic" selected. There will be a new color scheme called Ocean with completely new colors, aligned to the wp-admin counterpart.

**Comment by mreishus** [comment]
Finished all steps
