### ISSUE TITLE
Nav Unification: Site Switcher Loading Indicators are incorrect color

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#47303]
### Steps to Reproduce

* Using the default color scheme, or a ported wp-admin color scheme, visit calypso with nav unification turned on
* Go to the site switcher and observe the loading placeholders while your list of blogs is loading

### Actual Results

![2020-11-10_17-09](https://user-images.githubusercontent.com/937354/98744835-0319c400-2378-11eb-8210-813d446617fa.png)
![2020-11-10_17-07_1](https://user-images.githubusercontent.com/937354/98744845-08770e80-2378-11eb-9045-58a269298fbb.png)

The placeholders are white, which looks out of place on a darker background.  Usually you'd expect to see something with just a little bit of contrast from the background.

### Expect to see

Blocks of color closer to the background color.

### Reference Issues

* Main Issue #45435
  * Color Schemes Issue + Direction  #45675
    * Port over WP Admin color schemes as new options in Calypso /me section. #47036

**Comment by frontdevde** [comment]
The issue is caused by the loading state using the neutral color.

```
.site.is-loading {
	.site-icon,
	.site__title,
	.site__domain {
		background-color: var( --color-neutral-0 );
	}
}
```

We'll need to look at the different places the site switcher is used in. In the full page site switcher on /home it should probably remain a neutral color. In the sidebar we'd probably want to tweak it to be a shade different from the sidebar background color.
