### ISSUE TITLE
Gutenberg: Converting deprecated reusable blocks fails on wpcom

### ISSUE THREAD

**Issue by gamebits** [Automattic/wp-calypso#47336]
#### Steps to reproduce

1. Create a reusable block on WordPress.com using a custom block type, such as "Task List".
2. Remove whatever functionality made that custom block type available, such as a plugin. (In this case, "Task List" was unique to wpcom and has been deprecated.)
3. Insert the reusable block into a post.
4. Click the "Convert to regular blocks" button. Nothing will happen, because there is no regular block to convert the reusable custom block to.

#### What I expected

On a self-hosted site, the response to clicking the button and failing to convert would be this warning:

> Your site doesn’t include support for the “[block name]” block. You can leave this block intact, convert its contents to a Custom HTML block, or remove it entirely.

#### What happened instead

Nothing. The reusable block did not convert, and no warning was presented.

#### Browser / OS version

Safari 14 & Firefox 82 in macOS 10.14.6.

#### Screenshot / Video

![reusable-block](https://user-images.githubusercontent.com/12199101/98850532-c5657b80-2409-11eb-94fc-8af2c22ed679.jpg)

#### Context / Source

#dogfooding
#manual-testing

**Comment by sirreal** [comment]
Can be easily reproduced with this test post: p3hyOA-3eT-p2

**Comment by david-szabo97** [comment]
Convert reusable to regular block happens here: [code](https://github.com/WordPress/gutenberg/blob/e83ef614543184f347c4ad26d668b21ec7f3f21a/packages/reusable-blocks/src/store/controls.js#L58-L76)

Which calls into `replaceBlocks`: [code](https://github.com/WordPress/gutenberg/blob/e83ef614543184f347c4ad26d668b21ec7f3f21a/packages/block-editor/src/store/actions.js#L351-L391)

The convert is canceled by this line in the `replaceBlocks function:
```
if ( ! canInsertBlock ) {
```

`canInsertBlocks` calls `canInsertBlockType` which returns false: [code](https://github.com/WordPress/gutenberg/blob/e83ef614543184f347c4ad26d668b21ec7f3f21a/packages/block-editor/src/store/selectors.js#L1239-L1311)

It returns false because of the block missing from the allowed list: [code](https://github.com/WordPress/gutenberg/blob/e83ef614543184f347c4ad26d668b21ec7f3f21a/packages/block-editor/src/store/selectors.js#L1265-L1274)

By default the allowed list contains all the blocks except the hidden ones. [code](https://github.com/WordPress/gutenberg/blob/e83ef614543184f347c4ad26d668b21ec7f3f21a/packages/edit-post/src/editor.js#L123-L137)

`a8c/todo` block is a hidden block in P2 so it's removed from the allowed list.

**Comment by david-szabo97** [comment]
@sirreal Got any idea how to fix/get around this? 🤔

**Comment by sirreal** [comment]
Not really, everything makes sense in some way. The issue is really that we've disabled the blocks but they aren't migrated in any way. Maybe we can provide an upgrade path for a8c blocks that have been disabled somehow?

It may be best to consider this a one off loss and switch to the preferred block, I believe there's an alternative. I think @mirka was working with these blocks and may have insight.

**Comment by mirka** [comment]
Yes, we only hid the deprecated blocks `a8c/task` and `a8c/todo` from the inserter (instead of unregistering) so existing instances would continue working.

From reading this thread, it seems like the unresponsiveness is a Gutenberg problem. It’s expected for the conversion to fail, but it should display an error message. Correct?

---

Aside from that, is there also a specific and practical problem here of needing to convert a bunch of old reusable `a8c/todo`s? If so, that’s neither a Calypso or Gutenberg problem, but we’d be happy to help in `#p2` on Slack. I didn’t write a transform function for `a8c/todo` → `p2/task` migration because honestly I didn’t think anyone would need it, but if it’s worth the effort we can definitely look into that. I guess we can also do things like keep the deprecated blocks available just for a specific P2.

**Comment by sirreal** [comment]
I think this can be closed. We know and understand the underlying issue (one of the block used in the reusable block is disabled) but there are no plans to fix it. That seems acceptable as it's an internal block with minimal usage.

@gamebits Did you get your case sorted out? Replacing the old blocks for the newer ones should make sure you can keep this flow.

**Comment by gamebits** [comment]
I suppose, though I would check if the lack of failing gracefully is also occurring in the other issue I just linked to.
