### ISSUE TITLE
Business Hours Block: Breaks on List View

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#47439]
#### Steps to reproduce

1. Create a new page
2. Add the Business Hours block
3. Deselect the block, and then select it again using the List View option

#### What I expected
For the Business Hours block be selected.

#### What happened instead
It shows the error `This block has encountered an error and cannot be previewed.`

#### Screenshot / Video
![BusinessHoursBlockIssue](https://user-images.githubusercontent.com/16104522/99191736-611a2300-274d-11eb-9b6b-1cabf3055a0c.gif)

#### Browser / OS version
OS X 10.15.7
Chrome 86.0.4240.193

#### Context / Source
#dogfooding

**Comment by jeyip** [comment]
I can reproduce this issue on simple sites and in a local dev environment. The issue manifests differently on atomic sites for me -- rather than an error, the site freezes and eventually displays a white screen of death. 

Not certain if that's a separate problem, but I'll leave it as a comment here for now.

**Comment by jeyip** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/27125

**Comment by apeatling** [comment]
Fixed
