### ISSUE TITLE
Purchases: Cannot add a new credit card in Brazil

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#47436]
#### Steps to reproduce

1. Make sure your currency is set to BRL.
1. Starting at URL: `https://wordpress.com/purchases/add-credit-card/:domain`
1. Select "Brazil" as the country in the drop-down menu.
1. Fill in the credit card form and press submit.

#### What I expected

The card to be added.

#### What happened instead

Received `Missing required param: payment_method_data[card].`

#### Screenshot / Video

![brazil](https://user-images.githubusercontent.com/2036909/99158833-33799f00-26a5-11eb-93db-ba2c948efc9f.png)

#### Context / Source

It's possible that this has been broken for at least a year and possibly longer (maybe since we implemented the SCA project?). It's also possible this was a regression that somehow happened when we made the changes to enable site-level billing, in which case this was much more recent.

**Comment by fditrapani** [comment]
I noticed this issue of the blank screen while working on the credit card form as well. I traced it back to this function and no cart loading: https://github.com/Automattic/wp-calypso/blob/master/client/lib/checkout/processor-specific.js#L24.

I'm not entirely sure how to fix it though.

**Comment by nbloomf** [comment]
Putting some notes here. The CreditCardForm component appears to assume it will only ever display the extra (non-stripe) fields in signup: https://github.com/Automattic/wp-calypso/blob/trunk/client/components/credit-card-form-fields/index.jsx#L282

#47261 changed the logic that is used to detect whether to show those fields: https://github.com/Automattic/wp-calypso/blame/trunk/client/lib/checkout/processor-specific.js#L46, albeit in a way that I don't _think_ would affect this.

That said, as far as I can tell, this component is not currently used in any context where the currently expected behavior is to _not_ use the stripe processor. If that is true, the best solution might be to just make CreditCardForm always use stripe.

**Comment by sirbrillig** [comment]
Worth noting that when we were discussing this, we discovered what I think is the proximate cause for these errors: the line https://github.com/Automattic/wp-calypso/blob/79192ec9258152a671fbdb0085a628f561c282f5/client/lib/checkout/processor-specific.js#L32 (added in https://github.com/Automattic/wp-calypso/pull/47261) assumes that `cart.allowed_payment_methods` will always exist; this is true for `ShoppingCartProvider`, but not for `CartStore`, which returns an empty object when not initialized.

**Comment by sirbrillig** [comment]
Just to record some additional thoughts from a Slack thread:

Excluding the `cart.allowed_payment_methods` issue, if you selected Brazil and had BRL currency, wouldn't the form have always shown the old credit card fields (previously paygate but now ebanx)?

And if that's the case, and the form submission was triggered by the existence of `stripe`, then wouldn't the form have always failed for Brazil since the stripe fields were empty?

If that's true, then this form has been broken for a very long time (at least since we introduced Stripe elements). Since I don't know of a reason why Stripe would not work for Brazil, making the add card form use Stripe seems like a good fix. We can then investigate what we would need to do to add Ebanx cards.
