### ISSUE TITLE
Site Privacy: Users on Private Sites end up in a login loop unable to view site

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#47659]
#### Steps to reproduce

1. As User A, set a site to be private
2. Invite User B to be a viewer of the site
3. Attempt to visit site when logged in as User B
4. Follow prompts to log in for access to Private site

#### What I expected

After confirming to log in as User B I should see the site content of the Private Site.

#### What happened instead

I am sent back to the 'Private Site' screen prompting me to login.

#### Screenshot / Video

Screencast from an actual user:
https://imgur.com/a/keDyjjZ?fbclid=IwAR2lnGBC61oMD3uYjD2ej1WIdJ5NpHZcI-llzXkTMiTpZ4QyFLhPutOMLrA

-----
Shifting this over from this open P2: p2EDhh-1bk-p2

We're seeing an increasing number of reports of this (I'll list them below) and are seeking to get browser information from users who have the problem. I've been able to recreate in Chrome will in a Support Session as a user affected.

Currently, it seems that the problem is caused by a custom domain - switching to using the *.wordpress.com address resolves the issue. It seems that browser cache/cookies clearing has no impact.

**Comment by jordesign** [comment]
Cases so far:

* #5915641-ch 
* #25114152-hc
* #3408415-zen
* #3418338-zen
* #20100819-hc
* #3479418-zen
* #3479418-zen
* #3512691-zen

**Comment by cathymcbride** [comment]
Moving to janitorial pri backlog, since we are hitting multiple reports of this happening pretty quickly.

**Comment by simison** [comment]
Heads up that @Automattic/ganon has been working on related things but they had a look on Monday and concluded that it's not related.

> [...] it seems that the problem is caused by a custom domain - switching to using the *.wordpress.com address resolves the issue. It seems that browser cache/cookies clearing has no impact.

cc @daledupreez any changes recently that could impact this?

**Comment by daledupreez** [comment]
Apologies for the delay. AFAIK, we haven't made any direct changes that would affect this.

However, this feels a _lot_ like it could be driven by third party cookie restrictions. cc @josephscott for input on whether that's a likely root cause here.

**Comment by joaodante** [comment]
I got another case: HC-23086790 and they also had a ticket about the same issue ZD-3520755.

**Comment by cathymcbride** [comment]
Removing from the Manage board, and leaving on the create board so we don't duplicate effort on this one.

**Comment by josephscott** [comment]
@daledupreez I believe you are correct.  I watched the video very closely and it looks like it is Chrome in an Incognito window.  If that is the case, then they could have the Incognito "Block third-party cookies" toggle enabled, in which case third-party cookies won't work.  That means remote login on WordPress.com won't work.

**Comment by roo2** [comment]
@josephscott I was also able to reproduce this issue in chrome in an incognito window with "Block third-party cookies" enabled. (the setting is enabled by default in incognito). When I changed the chrome setting, I was able to log in successfully

**Comment by cathymcbride** [comment]
@roo2 Are you saying this isn't a bug per se, or a bug with blocking 3rd party cookies?

**Comment by ramonjd** [comment]
> Are you saying this isn't a bug per se, or a bug with blocking 3rd party cookies?

@roo2 can confirm but I think it's a browser "feature", and not a specific bug on WordPress.com. I could reproduce it too.

As mentioned better [above](https://github.com/Automattic/wp-calypso/issues/47659#issuecomment-739016227), the Viewer is logged into WordPress.com fine, but when they try to visit `customdomain.com` the browser views the WordPress.com login cookie as third-party. At least that's how I understand this particular browser restriction.

I'm not 100% sure if this will work, but what if we tacked `?preview=true` at the end of the site's free domain (when they're viewed by site members?) 

For example `user_domain[.]wordpress.com?preview=true` instead of `user_domain.com`

It seems to prevent the redirect to the custom domain, but I could be swimming up the wrong creek.

**Comment by roo2** [comment]
hmmm @ramonjd I tried the ?preview=true, it worked perfectly when accessing a page within the site e.g. `/about?preview=true`, I was able to log in and view the private site.

However, if I tried to access the root of the site `/?preview=true`, I was redirected to the custom domain.

Maybe this fix could work if we enabled `preview=true` on the root of the site. hmmm but could we actually deploy this? I think we would either need to:
* Update links to use `domain.wordpress.com/?preview=true` for all users
* Or we would need some logic that determines if the user has viewer access to the site and redirects them to the wordpress.com domain... but actually we can't determine if the user should have viewer access because their login cookie has already been blocked

Hmm otherwise we would have to figure out a way to make custom domains use first party cookies to log in, which should be possible, but could be a significant piece of work.

Also, I confirmed that this issue also affects the blog owner themselves if accessing the private site from an incognito window.

**Comment by ramonjd** [comment]
> However, if I tried to access the root of the site /?preview=true, I was redirected to the custom domain.

Dang. Yeah I wasn't sure. Seemed too good to be true

**Comment by yashitamittal11** [comment]
Another one- #3648338-zen

**Comment by iandunn** [comment]
I think @dd32 tracked it down to a bug w/ remote login, so it's not just a cookie issue? It happens to me constantly in regular (non-Incognito) windows.

It sounds like a lot of a12s are experiencing it too, xref `slack/archives/C025Q5RK2/p1611879396118300`.

**Comment by ramonjd** [comment]
I think D56176-code resolved the private login issue. However, as far as I know, there's an outstanding problem related to 3rd party cookies/ITP.

See discussion in:

p1611897603232600-slack-C02AVAR9B

Perhaps we could politely add it to the 3rd Party Cookie team's roadmap p1HpG7-b9q-p2

**Comment by iandunn** [comment]
🤔 , I logged out and then back in, since IIRC the last time I logged in was before that was deployed. I can access the FG  front-end again, but it's hard to say if it's actually fixed, since IIRC the problem wouldn't be triggered right away.

Even right after logging in, though, I'm still getting `403` errors with embeds and thumbnails on `a8ctv`. I'm using a regular window, and have Chrome configured to only block 3rd party cookies in private windows. The `Address Bar > Padlock > Cookies` doesn't show any blocked cookies. If I open the thumbnail URLs directly, they load, it's only when they're embedded that they're blocked.

**Comment by ramonjd** [comment]
> Even right after logging in, though, I'm still getting 403 errors with embeds and thumbnails on a8ctv. I'm using a regular window, and have Chrome configured to only block 3rd party cookies in private windows. The Address Bar > Padlock > Cookies doesn't show any blocked cookies. If I open the thumbnail URLs directly, they load, it's only when they're embedded that they're blocked.

Hmm, that is interesting. Thanks for the report, it'll be helpful for future debugging.  

I just tried in FF and Chrome, and can login from the private page to a8ctv and other private sites without any issue.  
I have experienced issues in the past when trying to login to private sites with custom domains.

**Comment by iandunn** [comment]
A few days later and I'm experiencing this w/ the FG and A8CTV again :(

**Comment by jsnajdr** [comment]
If the site is showing the "Private site -- login here" banner even after redirecting to wordpress.com/log-in and back, it means that the site was unable to perform remote login.

One cause was apparently fixed by @dd32 in D56176. There was a bug that prevented inserting the remote login code into the page markup.

If remote login still doesn't work, especially on a mapped custom domain, it means that the site (e.g. example.blog) cannot access the third-party cookies for wordpress.com. The remote login embeds an iframe from wordpress.com, but none of the HTTP requests, neither the HTML document for the iframe nor the XHR requests that its scripts are sending, includes the wordpress.com auth cookies. Because the top-level site is example.blog. That's what "block third-party cookies" means.

> Even right after logging in, though, I'm still getting 403 errors with embeds and thumbnails on a8ctv.

@iandunn All the evidence suggests that you, and everyone else who experiences this issue in Chrome, has 3rd party cookies disabled 🙂  Not only in Incognito, but everywhere:

<img width="685" alt="Screenshot 2021-02-19 at 12 56 02" src="https://user-images.githubusercontent.com/664258/108502837-b5d0bb00-72b3-11eb-9501-264baa9903b7.png">

Video thumbnail images and the videos themselves are downloaded from videos.files.wordpress.com. Because a8ctv is a private site, these requests need to be authenticated with a `wordpress_logged_in` auth cookie for wordpress.com. But when issuing HTTP requests from a mapped domain, the cookies are not attached. Again, 3rd party cookie blocking in action.

Chrome devtools can show why a cookie wasn't attached to a request and explain why. Find the failing thumbnail request in the Network panel and look at the Cookies tab: (with "Show filtered out request cookies" checkbox enabled)

<img width="683" alt="Screenshot 2021-02-19 at 13 15 51" src="https://user-images.githubusercontent.com/664258/108503583-e8c77e80-72b4-11eb-9d0a-f978834d2af0.png">

Here it tells me that I have a `wordpress_logged_in` cookie, but it wasn't sent due to my preferences, i.e. 3rd party blocking enabled. What do you see there? Is the `wordpress_logged_in` cookie present? Is it present and blocked? And why?

**Comment by iandunn** [comment]
Hi @jsnajdr 👋🏻 , thanks for looking into it!

I do get a different reason for the block:

> This cookie didn't specify a "SameSite" attribute when it was stored and was defaulted to "SameSite=Lax," and was blocked because the request was made from a different site and was not initiated by a top-level navigation. The cookie had to have been set with  "SameSite=None" to enable cross-site usage.

<img width="932" alt="Screen Shot 2021-02-19 at 12 14 37 PM" src="https://user-images.githubusercontent.com/484068/108556826-794d9100-72ac-11eb-8a1b-e8e4e95a96a2.png">

My settings only block 3rd party cookies in private windows:

![Screen Shot 2021-02-19 at 11 57 42 AM](https://user-images.githubusercontent.com/484068/108556789-6e92fc00-72ac-11eb-84ea-13a3f8585cd6.png)

It may not be relevant, but the message I see is slightly different than the one you described:

![Screen Shot 2021-02-19 at 11 58 58 AM](https://user-images.githubusercontent.com/484068/108556822-78b4fa80-72ac-11eb-8d95-5998dd9b48b8.png)

**Comment by iandunn** [comment]
Hmm, it seems like [HTTPS Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en) is the problem.

If I logout, disable it, and then log back in, the cookie isn't blocked. If I logout, enable it, and log back in, then the cookie _is_ blocked. 

It seems like it prevents the cookies from getting the correct `SameSite` setting when they're set, so logging out and then in again is required.

**Comment by jsnajdr** [comment]
> Hmm, it seems like HTTPS Everywhere is the problem.

I can reproduce the issue with the HTTPS Everywhere extension installed.

The trouble is that a successful `wp-login.php` is setting the `wordpress_logged_in` cookie twice, with different `secure` and `SameSite` attributes:
```
Set-Cookie: wordpress_logged_in=secret
Set-Cookie: wordpress_logged_in=secret; secure=true; SameSite=None
```

The `secure` attribute apparently makes a cookie unique and the browser's cookie storage stores them as two different cookies instead of overwriting them.

Now HTTPS Everywhere registers a "cookie on change" hook that converts cookies to secure. That enforces `secure=true` on the first cookie and stores a secure cookie without `SameSite`.

The second `Set-Cookie` header, the one with `SameSite=None` is then apparently ignored.

We're setting two `wordpress_logged_in` cookies in order to:
- make even unencrypted `http://*` loads authenticated with a `wordpress_logged_in` cookie
- make the unencrypted cookie less powerful by omitting the `SameSite` attribute

Note that setting two cookies with the same name is a grey area of the [HTTP cookie standard](https://tools.ietf.org/html/rfc6265#section-4.1.1) which says:

> Servers SHOULD NOT include more than one Set-Cookie header field in the same response with the same cookie-name.

And then the [Storage Model section](https://tools.ietf.org/html/rfc6265#section-5.3) says:

> If the cookie store contains a cookie with the same name, domain, and path as the newly created cookie:
> [ ... ]
> Remove the old-cookie from the cookie store.

So the above two `Set-Cookie` headers shouldn't have been sent in the first place. And if they were, the `secure` attribute should not make the two cookies different from each other. Only the name, domain, and path attributes can do that.

@josephscott do you have any ideas about possible solutions?

**Comment by josephscott** [comment]
> make the unencrypted cookie less powerful by omitting the SameSite attribute

Not exactly.  The [SameSite attribute is only allowed on secure cookies](https://web.dev/samesite-cookies-explained/), so there is no option to set it on insecure cookies.

---

I agree that we shouldn't have two cookies like this with the same name.  It will take someone going through all the references to `wordpress_logged_in` and figuring out which one it is trying to use.  The other option is to rename the insecure one ( `wordpress_logged_in_notsafe` ? ) and see what breaks :)

**Comment by jsnajdr** [comment]
> Not exactly. The SameSite attribute is only allowed on secure cookies, so there is no option to set it on insecure cookies.

I see! It's not that just the `SameSite=None` attribute on a non-secure cookie is ignored. The entire cookie would be rejected.

I filed a HTTPS Everywhere bug: https://github.com/EFForg/https-everywhere/issues/19954 Let's see if we get a response and if anything can be done about that.

> The other option is to rename the insecure one

That looks like an interesting approach. Is there still any unencrypted HTTP traffic to WordPress.com these days? I'd expect that after 4+ years of LetsEncrypt it's extinct. Maybe some Jetpack sites, but these should have their own site-specific `wordpress_logged_in` cookie.

**Comment by josephscott** [comment]
I'd like to say no, everything on WPCOM should be HTTPS at this point.  If I say that out loud though I fear some edge will show up.

**Comment by jsnajdr** [comment]
HTTPS Everywhere released an updated ruleset few hours ago and I can confirm that the issue is solved for my local testing Chrome + HTTPS Everywhere.

The only other scenario where this private site login loop can happen now is when the browser genuinely blocks all 3rd party cookies. Safari does that by default. Chrome and Firefox do that only when you manually enable stricter-than-default privacy settings.

**Comment by simison** [comment]
Thanks everyone for working on this!

> The only other scenario where this private site login loop can happen now is when the browser genuinely blocks all 3rd party cookies. Safari does that by default. Chrome and Firefox do that only when you manually enable stricter-than-default privacy settings.

@jsnajdr Since that's more generic issue that is also being worked on, I believe we can now close this issue?

**Comment by jsnajdr** [comment]
> Since that's more generic issue that is also being worked on, I believe we can now close this issue?

Yes, let's close this.

**Comment by Gustavo-Hilario** [comment]
Hey, y'all 👋

I have another report here: #4678364-zen

I tested this issue with some colleagues, and we could reproduce it on several test sites. We were using Google Chrome and Firefox. Third-party cookies were enabled. Can you please check and advise?

**Comment by mmtr** [comment]
Looks like right now Atomic sites don't support viewers on private sites according to https://wordpress.com/support/user-roles/#viewer:

> Viewers cannot view sites that are plugin-enabled. If you want someone to view your plugin-enabled site while it is private, invite them as a Subscriber

See also https://github.com/Automattic/wp-calypso/issues/43919

So the ~~workaround~~ solution for now would be to prevent users of Atomic sites from inviting viewers. That doesn't solve the underlying issue but at least ensures that the created users can access the site.
