### ISSUE TITLE
[Table block] Edit table actions are unclickable after performing a delete action

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#47696]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/pages/
2. Add new post.
3. Add Table block.
4. Specify more than 1 rows and columns.
5. On toolbar, click on Edit table
6. Click `Delete Row` or `Delete Column`
7. Click on Edit table again

#### What I expected
User is able to perform additional actions under Edit table menu.

#### What happened instead
Edit table actions are greyed out.
User must refocus on a cell to execute another action.

#### Browser / OS version
Browser: Firefox 85.0a1 (2020-11-23) (64-bit), Safari Version 14.0.1 (15610.2.11.51.10, 15610)
OS: macOS 10.15.7 19H2

#### Screenshot / Video
![Screen Shot 2020-11-23 at 22 05 33](https://user-images.githubusercontent.com/6549265/100055349-8b688200-2dd8-11eb-8616-5fadf28d5d5f.png)

#### Context / Source
Context: exploratory testing of Media & Text block. Issue found via #manual-testing.

**Comment by worldomonation** [comment]
Attached reproduce video:


https://user-images.githubusercontent.com/6549265/106533086-52b6ea00-64a6-11eb-8b1a-b32752fbfc35.mov

**Comment by inaikem** [comment]
Triage: I was able to reproduce on WPcom and self-hosted sites.

The issue only appears _immediately_ after the table is inserted and the edit button is clicked _before_ selecting a table cell.

If I create a table block and move focus to something else in the editor then click back, a table cell is selected on click/keyboard navigation and the issue is negated.

**Comment by inaikem** [comment]
Closed and moved to `WordPress/Gutenberg`: https://github.com/WordPress/gutenberg/issues/28714
