### ISSUE TITLE
Desktop app: "Launch" flows are not up-to-date with WordPress.com

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#47759]
Trying to launch a site using the app is not up to par with our current offering efforts in WordPress.com. See below:

- "My Home": No setup checklist, no option to Launch the site: 
<img width="1228" alt="Screen Shot 2020-11-24 at 14 48 03" src="https://user-images.githubusercontent.com/31009008/100268613-47ce5f00-2f23-11eb-9a04-ca3a275603a7.png">

- The "Launch" option is only available in Manage > Settings and in the editor:
<img width="1356" alt="Screen Shot on 2020-11-24 at 14-48-42" src="https://user-images.githubusercontent.com/31009008/100268619-4866f580-2f23-11eb-93f1-f6cff4b4bb5a.png">

- Clicking "Launch" in the page editor takes me to our legacy launch flow:
<img width="1029" alt="Screen Shot on 2020-11-25 at 13-35-24" src="https://user-images.githubusercontent.com/31009008/100268623-48ff8c00-2f23-11eb-9fbc-694183c4e7f6.png">

#### What I expected
I expected to see the setup checklist and Launch option in My Home, and to see the current launch flow when deciding to launch my site.

#### Browser / OS version
Desktop app version 6.4, macOS.

#### Context / Source
#dogfooding

**Comment by andrewserong** [comment]
Looks like the Primary layout isn't rendering in Customer Home for that site for some reason. I'm not too sure what sets `layout.primary` (relevant line here: https://github.com/automattic/wp-calypso/blob/trunk/client%2Fmy-sites%2Fcustomer-home%2Fmain.jsx#L85) so this is where I'd suggest the next person looking at this start from.

**Comment by ramonjd** [comment]
Just to confirm, are we expecting things to look as they do when you create a new site on WordPress.com? 

<img width="1089" alt="Screen Shot 2021-02-18 at 1 53 06 pm" src="https://user-images.githubusercontent.com/6458278/108298195-a89ec800-71f0-11eb-8251-4af582c0987b.png">

There are a couple of things going on. I'll provide some context for folks who eventually pick up this after we've cleared things up.

The layout of the home page is driven by the `wpcom/v2/sites/{$SITE_ID}/home/layout` endpoint, which returns the content that should appear in the primary, secondary and tertiary layout areas.

This is what I see when I create a new site on WordPress.com (not the desktop app).

<img width="838" alt="Screen Shot 2021-02-18 at 1 55 19 pm" src="https://user-images.githubusercontent.com/6458278/108298592-57430880-71f1-11eb-9e45-f73044d9ebbc.png">

The "primary" layout in the above response is `home-task-site-setup-checklist`. So Calypso shows me the checklist with the launch task! 🎉 

On the backend, we have a series of PHP definition files for various "views" ( e.g., desktop app, podcasting, wp for teams). 

These files contain instructions on which primary, secondary and tertiary layouts the frontend should display.

Here's the primary view that new sites on WordPress.com will see:

```
'primary' => [
    TASK_SITE_SETUP_CHECKLIST,
], 
```

That's why I can see the checklist.

And here's the one for the desktop app:

```
'primary' => [],
```

That's why the primary layout is empty on desktop. Or at least I'm pretty sure that's why 😇 

There is a comment in the PHP file that more or less says that we deliver a simplified view to desktop, with _no_ primary layout, because the build is often behind the latest Calypso build and rarely updated.

Does that sound right @kwight? (Plucked your name from the annotations) Is there any specific reason why we don't show the checklist on the desktop app?

**Comment by kwight** [comment]
> Does that sound right @kwight? (Plucked your name from the annotations) Is there any specific reason why we don't show the checklist on the desktop app?

Yep, that sounds right. I'm not sure the desktop app had anyone maintaining it at all at the time, so we left it as a layout that didn't need regular attention.

**Comment by simison** [comment]
I believe the desktop app now has a maintainer, @nsakaimbo :wave: Nicholas, would you recommend us making sure the Customer home matches web version?

My assumption is that we would have test coverage for customer home ensuring nothing breaks across web/desktop?

**Comment by kwight** [comment]
> My assumption is that we would have test coverage for customer home

The server-side library itself that determines the cards and layout have unit test coverage, yes.

**Comment by nsakaimbo** [comment]
👋 Thanks for the ping, @simison! Just catching up on this thread. Yes, the setup checklist was intentionally excluded from the Desktop app, and turns out I created [this issue](https://github.com/Automattic/wp-calypso/issues/47965) to track re-instating it at some point. The primary reasons for exclusion boil down to:

> The biggest roadblock to implementing this feature is ensuring that older Desktop clients aren’t broken by potential updates to the backend APIs that support this feature.
> 
> You’d need to perform versions checks in the API to determine if it’s safe to return the site setup view for My Home.

And more specifically:

> The first step would be to add VIEW_SITE_SETUP to the list of views compatible with the desktop app.
> 
> Then you’d need to determine if it’s safe to return that view. For that, you can add checks to the is_view_applicable function:
> ...
> (more details in Github issue #47965)

While fixing this feature and bringing it up-to-par with the web app is ideal, I should state that we're a few months away from completely re-writing the Desktop application. The plan is for the re-written app to be nothing more than a thin browser client that loads WordPress.com/Calypso webapp directly, instead of hosting a local Calypso instance (see pbwngY-9Y-p2).

While the WP-Desktop rewrite is pending, we won’t be dedicating much time to fixing bugs and features in the current application as we expect that the new architecture should solve this and host of other bugs and broken features.

All that being said, if you’re curious to tinker with the Electron code, I’d be happy to point you in the right direction and/or do some pairing. However if this proves to be a significant amount of work, we may be better off punting on this issue until the rewrite is complete.

cc: @kwight

**Comment by p-jackson** [comment]
So it looks like this difference between wep and desktop is by design. [The rationale was described above](https://github.com/Automattic/wp-calypso/issues/47759#issuecomment-785274464).

I think it makes sense to track this work in #47965 which already on the desktop app team's board and is labeled as a Feature Request, which I think is more appropriate.
