### ISSUE TITLE
Focused Launch: site title causing domain error 

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47813]
#### Steps to reproduce

1. Create a site using `/start/domains` flow.
2. Go to Manage > Settings > Site profile and update site title to a non-alphanumeric value (eg: `"`).
3. Go to editor and start Focused launch flow

#### What I expected
Domain suggestions to be displayed at _Confirm your domain_ step

#### What happened instead
An error was caused because of the invalid search query

#### Screenshot / Video
<img width="663" alt="Screenshot 2020-11-26 at 22 46 00" src="https://user-images.githubusercontent.com/14192054/100390691-f5cc2d00-3039-11eb-9c44-31cca092a2a5.png">

#### Context
Also mentioned in p58i-9Mt-p2#comment-48530

**Comment by yansern** [comment]
I can see the disallowed pattern from the backend is `$disallowed_pattern = '/[^\w\s\.-]/';`. On top of this, is a list of disallowed keywords.

Initially I was thinking of stripping out the invalid characters but actually from the client side we don't have the jurisdiction over what is considered valid or invalid domain keyword.

Instead, I think what needs to be done is:
1. When there is an error in domain suggestions.
2. Display the error (to inform/educate users).
3. Requery the domain suggestions with the subdomain as keyword (to allow user to continue picking a domain instead of blocking user out).

**Comment by razvanpapadopol** [comment]
I think we're already doing the first 2 points. Re-querying with subdomain as keyword seems like a good fix. Should we do this when pressing _Retry_ button or automatically after getting suggestions fails?

Also, I believe this is a blocker for the public release in all languages. Quoting from where the issue has been first mentioned (p58i-9Mt-p2#comment-48530):
> Because the default site title is the localized version of “site title” = サイトのタイトル, a domain cannot be recommended, so I get a warning. The warning sign shows a “Retry” = 再試行 button but pressing it doesn’t do anything.

**Comment by yansern** [comment]
>  or automatically after getting suggestions fails

Yup automatically after suggestion fails.

**Comment by razvanpapadopol** [comment]
Fixed in #48399
