### ISSUE TITLE
Ensure wp-gutenberg-experimental-features-spec.js spec runs

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#47839]
Context: https://github.com/Automattic/wp-calypso/pull/47712#discussion_r531109276

Ensure wp-gutenberg-experimental-features-spec.js are running on full suite and gutenberg edge suite.

May need the `@parallel` tag added.

**Comment by sirreal** [comment]
@fullofcaffeine Have you had a chance to investigate this?

**Comment by fullofcaffeine** [comment]
I just found out that @deBhal is already taking care of this issue as part of https://github.com/Automattic/wp-calypso/pull/48164. It wouldn't make much sense to just add the `@parallel` tag in a separate PR given the spec is currently failing. @deBhal is also working on fixing the tests, so it makes sense to just wait for https://github.com/Automattic/wp-calypso/pull/48164 in order to close this issue.

**Comment by deBhal** [comment]
I've merged #48164 now, but I'm not sure what's going on with one of the failing checks I removed to get it green. I've written up my investigation in https://github.com/Automattic/wp-calypso/issues/48585 - do either of y'all know what's going on with `editSite.__experimentalMainDashboardButton` ?
