### ISSUE TITLE
Focus Launch: Should we launch with the free plan if user closes checkout modal?

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#47897]
This question relates to the following scenario:

1. User selects paid domain
2. User selects paid plan
3. User clicks "Launch" to launch their site.
4. User is presented with the Checkout Modal overlaying their Success view. But they close the modal because they either did not want to pay, don't have their card details on them or [insert another reason here]

In this scenario we continue to launch their site with the free domain and plan instead of the paid options they had selected.

Is this the right approach? Or should we leave their site as unlaunched until the user re-selects the free options to relaunch, or pays for their selected paid domain and plan?

**Comment by tjcafferkey** [comment]
cc @ollierozdarz

**Comment by ollierozdarz** [comment]
Hey @tjcafferkey, thanks for checking!

> Or should we leave their site as unlaunched until the user re-selects the free options to relaunch, or pays for their selected paid domain and plan?

^ This is the _right_ solution in my eyes. I don't think it would be a great experience to launch a users site with options they didn't select just because they cancelled/closed a flow.

**Comment by tjcafferkey** [comment]
Thanks @ollierozdarz  :) I will convert this into an actionable issue.

**Comment by razvanpapadopol** [comment]
@tjcafferkey Now I see we already have a similar issue to fix the UX for the paid flow: https://github.com/Automattic/wp-calypso/issues/47831
Feel free to close that one or update it with the insights from here and from [Ollie's answer](https://github.com/Automattic/wp-calypso/issues/47831#issuecomment-736231749).

See also: p1606904152263600-slack-C0KDTA48Y
Highlights from that thread:
> the moment of congrats post-purchase is the moment the site launches. If someone makes selections and then abandons, let’s leave their site unlaunched

> Launch your site button at the bottom of the Focused Launch modal which gets enabled as soon as all the selections are made. If I click that I expect the site to be launched.
If we want to make the checkout step mandatory for launch with paid selection, maybe that button should say “Complete Purchase and Launch” ?

> Let’s just make sure all the buttons and labels make sense:
> - The button before user enters checkout needs to make sense like Razvan pointed out
> - Close/skip/back buttons in checkout need to behave expectedly and have appropriate labels for clarity.

Another point to consider is that we might want to remove the thank-you page redirect in case of Launch since we're using the success view to replace that https://github.com/Automattic/wp-calypso/pull/47808#issuecomment-738056195

**Comment by razvanpapadopol** [comment]
Thanks for figuring out this important piece of the puzzle. We'll continue with the implementation in https://github.com/Automattic/wp-calypso/issues/48081
