### ISSUE TITLE
Editor: Update button is active even though there is nothing to update

### ISSUE THREAD

**Issue by davewhitley** [Automattic/wp-calypso#4794]
#### Steps to reproduce
1. Schedule a post with some content
2. Leave editor
3. Come back and edit the post
4. The update button is active, even though there is nothing to update. I just got to the editor. Clicking on the button does nothing in the UI.
#### What I expected

I expected it to work similarly to the Save text button on a draft. The Save button does not show up until I make edits. Clicking on Save changes the UI to reflect that it is saving the post.
#### What happened instead

The update button is active, and that makes me think that edits are not saved. But, clicking on the button does nothing, so I don't know what to think.
#### Browser / OS version

Safari 9.0.2
#### Screenshot / Video

![screen shot 2016-04-15 at 4 50 32 pm](https://cloud.githubusercontent.com/assets/618551/14575933/cb64a24a-032a-11e6-8948-dd7451fd83b9.png)
#### Possible solution

Display a message saying "Updated!" or something even if it does nothing. Or, disable the Update button until there are changes.

**Comment by aduth** [comment]
If I recall correctly, it was an intentional choice to always leave "Update" enabled, even when the post is not dirty (except when a publish request is in-flight). The reasoning may have been to provide encouragement to users in knowing that they could publish or update a post at any point in time, whereas an autosave is intended to occur in the background without the user's explicit interaction.

/cc @mtias @folletto to weigh in if I'm wrong or we no longer agree with this assessment.

**Comment by folletto** [comment]
I think we can review that decision. I had the same sensation expressed by Dave before, and this feedback corroborates it wasn't just my impression. :)

**Comment by rachelmcr** [comment]
Confirmed that the Update button still works as described in this issue. I'll leave the issue open for future review of this behavior.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated](https://github.com/Automattic/wp-calypso/milestone/309?closed=1), I don't think this issue is relevant any longer. But please feel free to re-open it if that's incorrect.
