### ISSUE TITLE
Me: Sign Out button moving with browser window size change in Safari

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#4796]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me in Safari
2. Flex bottom of browser window up and down to see items on the left moving too.

#### What I expected
The left sidebar should have scrolling capabilities.

#### What happened instead
Everything from the Sign Out button and below move with the browser window changes.

Temporary workaround is to zoom out enough until everything in the sidebar is visible again.

#### Browser / OS version
Safari version 9.1 / OS Version 10.11.4

#### Screenshot / Video
<img width="276" alt="before me" src="https://cloud.githubusercontent.com/assets/11635760/14576454/04e68536-031e-11e6-9a1f-16bbe60f3915.png">
<img width="269" alt="after me" src="https://cloud.githubusercontent.com/assets/11635760/14576456/08d9b852-031e-11e6-8621-4221c290bb9f.png">

353508-chat

**Comment by lancewillett** [comment]
Thanks for the report — probably related to recent changes in #4712 CC @jasmussen

**Comment by jasmussen** [comment]
Oh I think this may be related to a refactor very recently done by @mtias. The sign out button is wrapped in a non-descript `div`, because the `button` element can't flex in Safari.

The solution to fix this is to add a CSS class to this non-descript div, and add `flex-shrink: 0;` to that. Let me see if I can put together a quick PR.

**Comment by jasmussen** [comment]
There ^^, that PR fixes it. 

I will be on and off today, so if anyone feels like verifying, merging, deploying, please go for it.
