### ISSUE TITLE
Followers: Unable to remove email followers

### ISSUE THREAD

**Issue by rezzap** [Automattic/wp-calypso#48045]
#### Steps to reproduce

1. Starting at URL: WordPress.com go to My Site > Manage > People and select the email followers list
2. Click the 'Remove X' button to try and remove an email follower.
3. The pop up button shows up and requires confirmation. Click to confirm. 
4. The email subscriber is still listed and the list does not refresh.

#### What I expected

That by clicking on the confirmation, the email follower would be removed. 

#### What happened instead

The email follower remained listed, making it impossible to remove these. 

#### Browser / OS version

Replicated in Firefox 83.0 (64-bit) macOS Cataline 10.15.7

#### Screenshot / Video

![Screen Recording 2020-12-04 at 10 13 53 am](https://user-images.githubusercontent.com/10325627/101151665-e6d91200-3619-11eb-85b5-7160851a9797.gif)

#### Context / Source

Reported by a user in 3544126-zen and 3535528-zen (same user)
#user-report

**Comment by JoshuaGoode** [comment]
We received an internal Atomic Request for this one as well at p9F6qB-6eO-p2

It appears the API call is incorrect.

When the  `Remove` button is clicked, it generates a POST like the following example but nothing happens.

`https://public-api.wordpress.com/rest/v1.1/sites/$site/followers/$user/delete?http_envelope=1`

Doing this in the API console returns the following 404:

> Full error message: That user is not found to be following this blog.

Looks like this should be using `email-followers` instead of `followers` which works.

So, it should look like the following instead:

`https://public-api.wordpress.com/rest/v1.1/sites/$site/email-followers/followers/$user/delete?http_envelope=1`

----

User report:
24158727-hc with a follow-up on 3544483-zen

**Comment by JoshuaGoode** [comment]
Related to https://github.com/Automattic/wp-calypso/pull/47451 ?

cc: @flootr @tyxla

**Comment by nerdysandy** [comment]
Reported on #26118884-hc Josh fixed it manually for now.

**Comment by JoshuaGoode** [comment]
I used the API to remove some followers when the user really wanted it done.  I forgot about our internal subscriptions admin tool, though, which would be far faster and easier. 

Dropped an internal note on p1607122767268000-slack-C029GN3KD

**Comment by formosattic** [comment]
+1 3546774-zen, thanks for the tip @JoshuaGoode! 
+1 3546808-zen

**Comment by jenlynnemc** [comment]
Related #26140684-hc
I removed the 1 follower the user wanted removed manually.
