### ISSUE TITLE
Focused Launch: Highlighting logic when user has items in cart

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48047]
To avoid confusion when I mention the term highlighting below I mean the step has had its opacity removed and it's "enabled". Not to be confused with highlighting (applying a border) a selected / focused option within the step.

**What**
If the user enters the Focused Launch flow with an item in their cart which will be used to preselect an item in the Focused Launch summary view then we will remove all highlighting logic and 'enable' every step.

**Why**
When a user enters the Focused Launch flow with an item in their cart it can result in the last step being highlighted (if they've got a plan in their cart) and the middle step (domains) appearing 'disabled'. 

This is confusing for the user as this flow was designed to guide them in a linear fashion from step 1 through to step 3.

**Acceptance criteria**
* Should the user open the Focused Launch modal with no items in their cart. The first step should be highlighted, and the subsequent steps should appear 'disabled'. (Current logic)
* Should the user open the Focused Launch modal with a plan or a domain in their cart which will be used to pre-select an option in the Summary view. All steps should be highlighted.

**Comment by ollierozdarz** [comment]
@tjcafferkey we use highlighting (i.e. in this case I'm referring to removing the opacity) on an option to then make it appear ready to select. We do this to keep the user focused on the linear flow and to not provide too much information at once (this is basically the crux of the 'focused' flow experiment). 

By default, only the first the options is available to select:
<img width="1437" alt="Screen Shot 2020-12-08 at 2 17 22 pm" src="https://user-images.githubusercontent.com/67085494/101439402-25473780-3960-11eb-87f9-51b55aa029de.png">

After the user selects an option (i.e. the blue 'selected' treatment on the panel), we highlight (remove the opacity) on the second available option:
<img width="1435" alt="Screen Shot 2020-12-08 at 2 18 38 pm" src="https://user-images.githubusercontent.com/67085494/101439456-47d95080-3960-11eb-9f01-ddb86902e152.png">

I'm keen to know more about the cart logic to help provide a solution as soon as I can.

If this is breaking down, I can imagine a few possible fixes for users coming from the cart specifically:

1. We could this 'highlighting' logic for this specific use case only.
2. If it doesn't break anything, we could pre-select (blue treatment) their cart options in this flow.

If it breaks down because they've selected say, a plan, but haven't yet selected a domain, this is where (1.) could help (removing the highlighting logic for this use case).

**Comment by tjcafferkey** [comment]
>If the user has a Premium Plan in their cart then we would pre-select this in the Focused Launch, meaning the last step is highlighted and completed, but the domains step isn't. So the flow isn't exactly linear in all situations.

As per mine and @ollierozdarz conversations there are two options here

1. When a user comes from the cart with an item (such as a plan) then we remove highlighting logic for all steps so that every step is highlighted.
2. When a user comes from the cart with a plan, which will cause the last step to be highlighted but the one before it (domains) to look 'disabled' then we reverse the order of these steps on the UI so it maintains a linear flow.

Option 1 would likely prevent any further edge cases from happening regarding cart data, option 2 would be most ideal although we should proceed with the path of least resistance as both are suitable solutions.

Going to update this Issue description to reflect decision for option 2. Previous description can be going in the history.
