### ISSUE TITLE
Page layout selector: Spacing missing between rows

### ISSUE THREAD

**Issue by david-szabo97** [Automattic/wp-calypso#48127]
#### Steps to reproduce

1. Starting at URL: wordpress.com
2. Open one of your sites
3. Create a new page
4. Check layout of the templates

#### What I expected
Spacing between rows

#### What happened instead
Rows are on top of each other

#### Browser / OS version
Safari Version 14.0.1 (16610.2.11.51.8)

#### Screenshot / Video
In this image, you can see the border/focus ring of the selected template. Looks like the image is overflowing. These previews are supposed to be a square image.
![image](https://user-images.githubusercontent.com/2256104/101513178-2be3a800-397c-11eb-9eb6-d7f83a6dd172.png)

![image](https://user-images.githubusercontent.com/2256104/101512384-3cdfe980-397b-11eb-9e31-b0baf8bacead.png)

#### Context / Source
https://wordpress.com/read/blogs/171213001/posts/6780#comment-3516

**Comment by ramonjd** [comment]
I can't seem to reproduce.

Checked in Safari

<img width="833" alt="Screen Shot 2021-02-18 at 2 49 10 pm" src="https://user-images.githubusercontent.com/6458278/108302844-e7d11700-71f8-11eb-901a-555186666d0d.png">

Also looked at FF, Chrome and Edge and it looks okay.

The commit history doesn't reveal where it might have been fixed in the meantime, at least deliberately :trollface: 

The last change was https://github.com/Automattic/wp-calypso/pull/49661, which is a precursor to a complete redesign/refactor.

 @Automattic/ganon is working on it at the moment, and it will be released in a few weeks. 

cc @p-jackson @roo2 for visibility, but I think we could close this issue in light of the upcoming redesign?

**Comment by davipontesblog** [comment]
@ramonjd I think this can be closed with the new layout picker merged now. Could you confirm?

**Comment by ramonjd** [comment]
> I think this can be closed with the new layout picker merged now. Could you confirm?

Thanks @davipontesblog 

Yep the redesign was shipped very recently pbAok1-1Rg-p2#comment-4175 😄 

Closing.
