### ISSUE TITLE
Switching Dashboard/admin color scheme leaves flash of old color scheme on reload

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#48220]
This relates specifically to the admin colors unification project. 

### Expected behavior
Once a new scheme is selected I shouldn't see any UI in the old color scheme.

### Actual behavior
I saw a flash of the old color schemes on reload before the new one kicked in.

### To Reproduce
* Select a color scheme.
* Hit Save
* Fully reload the page.
* Choose new color scheme.
* Save.
* Reload.
* See flash of _old_ color scheme before new one kicks in.

See also p1607595811242200-slack-ajax

**Comment by obenland** [comment]
> We might have to digg into `client/state/preferences/README.md` and see how it's updating the setting and if that can be improved
—@getdave

**Comment by getdave** [comment]
@mmtr Did you have a PR in progress here? If so would it be ok to link it up? 🙇

**Comment by mmtr** [comment]
@getdave I don't have any PR yet. Only had time to identify that the flash occurs because we have 2 different data sources:

- The `Layout` component gets the color scheme from the `preferences` Redux state: https://github.com/Automattic/wp-calypso/blob/0b3580e9a1ee14c72fc40477afbcf33433d8e72b/client/layout/index.jsx#L325
- The Account Settings page uses the `userSettings` library which implements its own state: https://github.com/Automattic/wp-calypso/blob/2f6c3df8d5033a90ed6a25f5bdc4fa546bb20d91/client/me/account/main.jsx#L86

Both end up being synced with the API response eventually, but since the `userSettings` library does not update the `preferences` local state, the `Layout` component will use an incorrect color until the `preferences` local state is updated with the API response.

**Comment by retrofox** [comment]
I've created a PR that tries to tackle this issue, in case you get the chance to take a 👀. 🙇‍♂️
