### ISSUE TITLE
Nav Unification: cloud.jetpack.com

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#48315]
Jetpack cloud (cloud.jetpack.com) and calypso are the same interface thus Jetpack cloud will be affected by nav unification when it goes live. Below I will try to illustrate the problematic areas with the current implementation. 

Before | After
-------|------
![](https://cln.sh/PJOVF4+) | ![](https://cln.sh/FjthD2+)

As jetpack already uses different components for sidebar and masterbar, most problems originate from the way we have overridden the styles so we can have both the feature enabled and disabled till we rollout to 100%.

Problems :
1) The most significant problems are in the masterbar

![](https://cln.sh/kGJ6HG+)

all of them are resolved by adding the correct styles in 
`client/components/jetpack/masterbar/style.scss` for 
```
--masterbar-height: 32px;
```

the following will eventually be auto resolved when we push it live for everyone as the offending code `client/my-sites/sidebar-unified/style.scss` will be moved into the correct theme and jetpack cloud theme will override properly.
```
--color-masterbar-background: #101517;
--color-masterbar-border: #333;
--color-masterbar-item-hover-background: #333;
--color-masterbar-item-active-background: #23282d;
```
Till then, we will need to alter `client/my-sites/sidebar-unified/style.scss` so that they are triggered only for the default theme only. 

This can be resolved now (no need to wait for nav-unification to go live)

2) Dashicon from "Switch Site" is missing. This can be resolved by correctly importing 
`@import url( '//s1.wp.com/wp-includes/css/dashicons.css?v=20150727' );`
in `https://github.com/Automattic/wp-calypso/blob/8445b88ee26c58e3e4465e36e2ffa75d82c96296/client%2Fcomponents%2Fjetpack%2Fsidebar%2Fstyle.scss#L22`

This can also be resolved now (no need to wait for nav-unification to go live)

3) On mobile we need to make the Jetpack Logo to open the sidebar or reinstate the SidebarNavigation (https://github.com/Automattic/wp-calypso/blob/43d3beb3962b37f72ea2f2f0f78c6e480c0b758e/client%2Fcomponents%2Fsidebar-navigation%2Findex.jsx#L22) only for jetpack (we can check `jetpack-cloud` flag). Currently there is no way to open the sidebar.

![](https://cln.sh/ph8hZp+)

This can also be resolved now (no need to wait for nav-unification to go live)

### **We should make a decision whether:**
1) we make jetpack cloud look like as the original one. By resolving the problems above. Seems really simple and straightforward.
2) or we make jetpack cloud look alike calypso. Needs a lot of effort. Are we going to also adapt the color-scheme (dark) or just geometries (masterbar height, menu items padding etc)?

**Comment by folletto** [comment]
To add details here:

1. When Nav Unification kicked off we asked to keep Calypso Green within scope of the work.
2. At this stage Nav Unification is focused on shipping on .com first.
3. Ideally, I'm imagining we should be using the same UI component, driven by a different data set (the Jetpack specific navigation). It's important we avoid forking Calypso Green and Calypso Blue structure as much as sensible (what's sensible is part of the discussion).
4. We might consider some more changes to align better the Nav Unification work to Calypso Green.

Thus, unless there's a change of plan for Nav Unification, and until they ship on .com and are then able to work on Calypso Green, we should just make sure there's no breakage happening.

**Comment by cpapazoglou** [comment]
> Thus, unless there's a change of plan for Nav Unification, and until they ship on .com and are then able to work on Calypso Green, we should just make sure there's no breakage happening.

This sound like "make jetpack cloud look like as the original one.". The problems I described are all breaking.

> Ideally, I'm imagining we should be using the same UI component, driven by a different data set (the Jetpack specific navigation). It's important we avoid forking Calypso Green and Calypso Blue structure as much as sensible (what's sensible is part of the discussion).

Just to clarify, calypso already uses different components for jetpack cloud rather than same components with different data set.

**Comment by folletto** [comment]
> This sound like "make jetpack cloud look like as the original one.". The problems I described are all breaking.

Yes, at this stage this seems the right approach. My note was more to highlight to "let's not forget" alignment tho. 

> Just to clarify, calypso already uses different components for jetpack cloud rather than same components with different data set.

You mean for the sidebar? I thought it was using the same components, while the only bit was the bar at the top. I'll cross check then.

In general, my concern to be clear is to avoid forking of experiences and thus components, because we know that in the long term that leads to maintenance problems and misalignment of the experience overall. Unless a better proposal comes forward, aligning Calypso Green to the new Nav is part of ensuring this.

**Comment by rcanepa** [comment]
Hey @cpapazoglou! Is there a branch we can use to test the changes introduced by the Nav Unification project?

**Comment by obenland** [comment]
@rcanepa paYJgx-1cy-p2 contains testing instructions for nav unification.

**Comment by obenland** [comment]
+1 on going the route of least resistance, which seems to be @cpapazoglou's first suggestion.

/cc @davemart-in

**Comment by davemart-in** [comment]
> As jetpack already uses different components for sidebar and masterbar

Can we double check and verify this please @cpapazoglou and @folletto? 

At a bare minimum, let's ensure that nothing is leaking through.

**Comment by folletto** [comment]
Yes, that's what I meant when I said "I'll cross check" above: I pinged our Voyager team for review, @rcanepa already replied above and is looking into it.

**Comment by rcanepa** [comment]
> As jetpack already uses different components for sidebar and masterbar

This is correct. We had to create different components since both the sidebar and the masterbar work and look different in cloud.jetpack.com than in WordPress.com. However, both apps rely on the same layout components under the hood. Basically, what we created are wrapper components.

**Sidebar**

Each app uses a different component that wraps the `Sidebar` layout component located at [`client/layout/sidebar/index.jsx`](https://github.com/Automattic/wp-calypso/blob/ea53396172e91112a35d1a90255adb58be4c432b/client%2Flayout%2Fsidebar%2Findex.jsx). On cloud.jetpack.com, the wrapper component is called `JetpackCloudSidebar` and it's located at [`client/components/jetpack/sidebar/index.jsx`](https://github.com/Automattic/wp-calypso/blob/f72caa54aad2abc9c77c15e3fbb3e5be98739e75/client%2Fcomponents%2Fjetpack%2Fsidebar%2Findex.jsx), and on WordPress.com the wrapper component is called `MySitesSidebar` and it's located at [`client/my-sites/sidebar/index.jsx`](https://github.com/Automattic/wp-calypso/blob/80f83f1f644748540ea07644f95dc583de38e19b/client%2Fmy-sites%2Fsidebar%2Findex.jsx).

**Masterbar**

The situation is basically the same. Each app has a different wrapper component that wraps the `Masterbar` layout component. In the case of cloud.jetpack.com, we have a component called `JetpackCloudMasterBar` located at [`client/components/jetpack/masterbar/index.jsx`](https://github.com/Automattic/wp-calypso/blob/43d3beb3962b37f72ea2f2f0f78c6e480c0b758e/client%2Fcomponents%2Fjetpack%2Fmasterbar%2Findex.jsx). On the other hand, WordPress.com uses a component called `MasterbarLoggedIn` located at [`client/layout/masterbar/logged-in.jsx`](https://github.com/Automattic/wp-calypso/blob/80f83f1f644748540ea07644f95dc583de38e19b/client%2Flayout%2Fmasterbar%2Flogged-in.jsx).

**Comment by davemart-in** [comment]
Thanks for clarifying @rcanepa!

@obenland and I discussed this during our 1:1 yesterday. We'll:

A) Ensure that there are no visual regressions as a result of the nav unification work
B) Dig in to see what it will take to ensure that Calypso Green doesn't fall behind
