### ISSUE TITLE
Color schemes: button component hover styles

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#48368]
The hover state of buttons using the 'modern' color scheme appears to be different than the hover color in core:

Calypso:
<img width="1569" alt="Screen Shot 2020-12-15 at 12 16 46 PM" src="https://user-images.githubusercontent.com/437258/102250039-0d783200-3ed1-11eb-81cc-90f4fdf9945e.png">
`--color-accent-60`

Core:
![image](https://user-images.githubusercontent.com/437258/102250196-40222a80-3ed1-11eb-9a72-1aac26609f8c.png)

`--wp-admin-theme-color-darker-10`

**Comment by sixhours** [comment]
Looks like core uses two different hover colors on primary buttons; wp-admin (top screenshot) differs from Gutenberg, too:

<img width="626" alt="Screen Shot 2021-04-27 at 9 37 02 AM" src="https://user-images.githubusercontent.com/2124984/116250927-2ffe3f80-a73c-11eb-8b83-d45c4ded289c.png">
<img width="254" alt="Screen Shot 2021-04-27 at 9 37 17 AM" src="https://user-images.githubusercontent.com/2124984/116250930-3096d600-a73c-11eb-84c4-af6e5959ee49.png">

I'm assuming we want to use the Gutenberg hover color rather than the /wp-admin one for Calypso.
