### ISSUE TITLE
Store|Woo: automatically redirect new users to the Core UI

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wp-calypso#48423]
**User story:**
As a new Store user
I want to be automatically redirected to the new UI 
So I don't need to spend time learning to work with a UI that's going to be removed

**Description:** new US/CA business customers that click on the Store/WOO menu item for the first time should be automatically redirected to the Core UI setup journey, once we start sunsetting the store experience. 

**Acceptance criteria:**
- [ ] Automatically redirect users that click on the Store/WOO menu item for the first time to the Core UI setup journey
- [ ] Display a loading screen while everything is being installed. I think that we can reuse the existing screen. See the demo and support doc:
p6q6po-9eH-p2
https://wordpress.com/support/store/

**Event tracking:**
I think that we should keep the event tracking the currently exists to track if they click on the menu item and move past the loading screen, but I'd love to hear your feedback about this:

`calypso_woocommerce_store_nav_item_click`: Number of clicks on ‘Store’ nav item
`calypso_woocommerce_store_create`: Number of users who get past the plugin step

**Comment by pmcpinto** [comment]
cc @elizaan36 @becdetat

**Comment by mattsherman** [comment]
Thanks for this story... I was going to the PT right now to ask about how this should be handled! 🙌 

> **Description:** new US/CA business customers that click on the Store/WOO menu item for the first time should be automatically redirected to the Core UI setup journey, once we start sunsetting the store experience.

What should happen with non-US/CA business customers?

**Comment by pmcpinto** [comment]
The Store UI is only available to US/CA customers. The non-US/CA users need to go to plugins, install WooCommerce, etc

It's tempting to use this opportunity to simplify the flow and increase the Woo distribution across non-US/CA users 😄 But in Jan we're going to review the Woo hosting strategy so at this point I think that we should keep it simple and just focus on users that can get the Store UI. Makes sense?

**Comment by mattsherman** [comment]
@ilyasfoo When new users click on the WooCommerce menu item and we kick off the Core UI setup journey, we should also set a site option such as `calypso_hide_deprecated_store` (just a thought on the name) to `true`. This way, I can use that site option in #48424 to hide the deprecated Store menu item for new users.

_Edit: Nevermind... I don't think this will be good enough... it doesn't handle time before the user clicks on WooCommerce menu item. I'll think about this more and post some thought on #48424... I don't think we'll need to do anything in the PR for this issue._

**Comment by ilyasfoo** [comment]
Thanks for chiming in @mattsherman! I do think its tricky to detect new users, and I agree that the most reliable way is to set an option on site creation after deprecation config flag is enabled.

In the meantime, I think it's best for me to do a temporary stub implementation for detecting new users while waiting for your solution in #48424. In order to avoid stepping toes, I'll work on other things that are more specific to this issue instead:
- Detection for woocommerce plugin installation (If not yet installed, Store dashboard will still be accessible just to install)
- Redirection to Core UI setup journey after installation
- New tracks

**Comment by ilyasfoo** [comment]
@pmcpinto Can you help to confirm my assumptions on what is supposed to happen in this scenario:
1. User with Business plan atomic site clicks on Store menu item without WC plugin installed
2. User sees Store dashboard with the button "Set up my store!" https://d.pr/i/CtGP4m
3. When clicking "Set up my store!", loading screen is shown
4. After finishing installation, instead of going to page to set up store details, user will be automatically redirected to Core UI setup journey in wp-admin (without any confirmation)
5. From that point onwards, if the user clicks on Calypso store menu item it will automatically redirect to Core UI

cc @elizaan36

**Comment by pmcpinto** [comment]
@ilyasfoo 

> After finishing installation, instead of going to page to set up store details, user will be automatically redirected to Core UI setup journey in wp-admin (without any confirmation)

After finishing installation they should be redirected to the first step of the store profiler: https://d.pr/i/bw0Qbz

Lmk if you have more questions. Thanks

**Comment by mattsherman** [comment]
> Thanks for chiming in @mattsherman! I do think its tricky to detect new users, and I agree that the most reliable way is to set an option on site creation after deprecation config flag is enabled.
> 
> In the meantime, I think it's best for me to do a temporary stub implementation for detecting new users while waiting for your solution in #48424. In order to avoid stepping toes, I'll work on other things that are more specific to this issue instead:

I don't think you need the solution from #48424.

In this case, the "WooCommerce" menu item is new -- it always shows when "Store" is deprecated. Anytime that "WooCommerce" menu item is clicked and the WC plugin isn't installed, the user should be presented with the "Setup up my store!" button.

**Comment by ilyasfoo** [comment]
>In this case, the "WooCommerce" menu item is new -- it always shows when "Store" is deprecated. Anytime that "WooCommerce" menu item is clicked and the WC plugin isn't installed, the user should be presented with the "Setup up my store!" button.

That makes sense, I get it now thanks!

**Comment by ilyasfoo** [comment]
This is trickier than I thought, it seems that the flag to determine whether WC plugin is installed `finished_initial_install_of_required_plugins` is fetched **after** Store UI dashboard is loaded via `WOOCOMMERCE_SETUP_CHOICES_REQUEST` action. This means that during rendering our sidebar, we don't know the installation status.

I don't think it's appropriate to add a site-specific request before selecting a site. Dynamically setting URL for WooCommerce menu item does not sound right either since we cannot guarantee the consistency (user might click before installation status is determined).

At the moment I leaning towards making the redirect **after** store UI is loaded, but the UX won't be great. If anyone has any suggestion I would extremely appreciate it!

**Comment by mattsherman** [comment]
> This is trickier than I thought, it seems that the flag to determine whether WC plugin is installed `finished_initial_install_of_required_plugins` is fetched **after** Store UI dashboard is loaded via `WOOCOMMERCE_SETUP_CHOICES_REQUEST` action. This means that during rendering our sidebar, we don't know the installation status.

@ilyasfoo What particular scenario are you talking about here? There's a number of different paths -- I feel like we need a flowchart to keep all of them straight!

I assume that the action and flag mentioned are part of the WooCommerce Calypso extension that doesn't get loaded until Store section is navigated to? Could we pull that check out of the extension (which we won't need once Store is totally removed) and just put it in 'core' Calypso?

In other words (from a very quick look at the code!)...

Could we pull out `fetchSetupChoices()` and call that outside of the WooCommerce extension? Or, even just load the WooCommerce extension whenever a Business site is selected? Maybe in conjunction with making use of some of the other global state available in Calypso? (see below)

> I don't think it's appropriate to add a site-specific request before selecting a site.

The WooCommerce menu item won't be available in the My Sites sidebar unless a user has selected a site. So, that doesn't seem to be an issue, unless I'm missing a detail (which is likely! 😀).

> Dynamically setting URL for WooCommerce menu item does not sound right either since we cannot guarantee the consistency (user might click before installation status is determined).

I think dynamically setting the WooCommerce menu item URL should be reasonable. The issue of determining the installation status is one that we need to address regardless of where we are doing the branching.

The global state tree in Calypso has some information that could be useful for determining things...

```
getSiteOption( state, siteId, 'is_wpcom_store' ) // 'is_automated_transfer' && 'woocommerce_is_active'
getSiteOption( state, sideId, 'woocommerce_is_active' )
```

It looks like we could get the plugins for a site with some actions and selectors...

```
fetchSitePlugins( siteId )
getPlugins( state, [siteId] )
```

Of course, we'd need to make sure that we did this in a way that performed well, since we don't want to slow down the My Sites sidebar.

> At the moment I leaning towards making the redirect **after** store UI is loaded, but the UX won't be great. If anyone has any suggestion I would extremely appreciate it!

Yeah, that doesn't seem like good UX -- let's try to avoid that!

**Comment by mattsherman** [comment]
@ilyasfoo I'm likely going to be doing some state checks (though I expect much less involved) in #48424 to determine when to hide the Store menu item... I'll be working on that more this afternoon. I'll ping you in that PR when I have something working, in case it helps spark any ideas on how to handle the WooCommerce menu item in this PR.

**Comment by elizaan36** [comment]
how long does it take to bring up the Store UI and then redirect? I wonder if you could hide the Store UI while it's loading?

**Comment by ilyasfoo** [comment]
@pmcpinto For tracks:

`calypso_woocommerce_store_nav_item_click` is already being tracked on clicking the Store menu item. WooCommerce menu item is tracked using `calypso_woocommerce_store_woo_core_item_click`.

Can you elaborate on "Number of users who get past the plugin step"? Does this mean that we track the users finishing loading screen?

**Comment by ilyasfoo** [comment]
@mattsherman Thank you so much for your insight, I have tested `is_wpcom_store` option and found it to accurately identify a site with AT, installed & activated WooCommerce plugin!

**Comment by pmcpinto** [comment]
> Can you elaborate on "Number of users who get past the plugin step"? Does this mean that we track the users finishing loading screen?

Yes. AFAIK the `calypso_woocommerce_store_create` event is triggered when they move past the install screen. I just want to confirm if we'll continue triggering this event.

**Comment by ilyasfoo** [comment]
@pmcpinto It seems that `calypso_woocommerce_store_create` is not tracked by calypso, looking at tracks it may have been triggered from WPCOM API. I've checked in tracks history, the sites created under my PR is still being recorded.

**Comment by pmcpinto** [comment]
Gotcha. Thanks for the clarification
