### ISSUE TITLE
Payment Methods: Add notice about the current payment method when it's not available to select on the Update Payment Method page

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#48433]
And highlight the method if special (expired or Paypal)

**Comment by fditrapani** [comment]
I think this will look redundant since we select the current credit card on file — we should likely only show it if it's an expired card. I know we have it lined up for expired cards but based on how we handle credits, I believe this will go to the Add payment method screen if there isn't a valid credit card. 

This might be something we want to circle back to after we get PayPal integrated.

**Comment by DavidRothstein** [comment]
Following https://github.com/Automattic/wp-calypso/pull/48466, changing the payment method for an expired card now goes to the same screen as anything else.  The result is no payment method selected by default on that page, so we decided to try to do something here to help explain why.

We should still only show that extra info in the case where the current payment method isn't one of the ones that's available to be selected, though (e.g., if it's an expired card).

**Comment by DavidRothstein** [comment]
Since we decided to only show this information conditionally, I wonder if the Purchase Details section in the sidebar is really the best place for it after all.  (That area seems better suited for data that is always displayed.)

The purpose of this information is basically to explain to the user why no radio button is pre-selected, and they'll typically get here by coming from a page where the expired credit card is already mentioned in a notice, so I wonder if a notice right above the radio buttons might be a better way to communicate this?

For example, the user will usually be coming to the update payment method page from the manage purchase page, which typically will look like this:

![manage-purchase](https://user-images.githubusercontent.com/235183/102578264-c6a05d00-40c7-11eb-9dcc-16897b79acf4.png)

So maybe something like this would work on the update payment method page (exact text to be determined):

![change-payment-method](https://user-images.githubusercontent.com/235183/102578415-1d0d9b80-40c8-11eb-874a-d81b1469de8b.png)

cc @fditrapani for any input.

**Comment by fditrapani** [comment]
> So maybe something like this would work on the update payment method page (exact text to be determined):

Yeah, that looks great! thanks for putting it together.

**Comment by DavidRothstein** [comment]
The fix is now up for review in https://github.com/Automattic/wp-calypso/pull/48583.

I added messages for both expired cards and PayPal, and since an earlier pull request already made it so that the first payment method is selected on this page in the case where the existing payment method is PayPal (rather than selecting nothing) I did the same thing for expired cards too, for consistency -- that seemed to make the most sense, since the user came here to select a new payment method and the notice should alert the user to why their current payment method isn't there.

The screenshots in the above pull request show the final state.
