### ISSUE TITLE
Gutenboarding: Site creation fails when site title is invalid

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#48547]
#### Steps to reproduce

1. Starting at URL: http://calypso.localhost:3000/new
2. Choose an invalid title like "WordPress WordPress"
3. Complete the Gutenboarding flow to create site

#### What I expected
Either the site to be successfully created (possibly with a randomly generated subdomain) or a relevant error message.

#### What happened instead
I saw a "Something went wrong..." error and the response to the site creation request was "Please enter a site name."
<img width="568" alt="Screen Shot 2020-12-22 at 4 15 11 PM" src="https://user-images.githubusercontent.com/1689238/102933907-2bb1d500-4471-11eb-9221-03c2f8b99fbe.png">
<img width="557" alt="Screen Shot 2020-12-22 at 4 17 48 PM" src="https://user-images.githubusercontent.com/1689238/102933971-408e6880-4471-11eb-9378-989deceaef3f.png">

#### Browser / OS version
Firefox Developer 85 / MacOS Catalina

#### Screenshot / Video
https://www.loom.com/share/40c2dd70e73c44e58c539d09b5e4abb4

#### Context / Source

I ran into this issue while testing: #48430 and D54613-code
From debugging it seems like this issue occurs when there are *only* invalid words in the selected Site Title that are then sent to the endpoint as the `blog_name`.

**Comment by ramonjd** [comment]
Some tracing and discussion over at p1608714446221300-slack-C013QHLF2

**Comment by ramonjd** [comment]
When we go to create a site we use the [site title as the blog name](https://github.com/Automattic/wp-calypso/blob/d35f1eca00123e489c9ca53af32b15ae3ea74efe/client/landing/gutenboarding/stores/onboard/actions.ts#L68) if the domain is empty. 

```
const siteUrl = domain?.domain_name || siteTitle || username;
```

The issue is that, even though the site title triggers an error in the domains suggestions store when a user first lands on the domains page, we don't know about it at the time of site creation.

I had some spare time today and was thinking that it might be better for the frontend to handle the error, and then fill `blog_name` with an alternative or just empty it.

At the very least, it might be good for the onboarding app to know about such errors [before it tries to create a site](https://github.com/Automattic/wp-calypso/blob/d35f1eca00123e489c9ca53af32b15ae3ea74efe/client/landing/gutenboarding/stores/onboard/actions.ts#L68). 

In other words, the [domain picker](https://github.com/Automattic/wp-calypso/blob/f50ea71fc09bf1e8bd2772830f03729055fae679/packages/domain-picker/src/domain-picker/index.tsx#L227) and [domain suggestions store](https://github.com/Automattic/wp-calypso/blob/7a27876c58ef4bc1d5e06709eb6b552156fe82b5/packages/data-stores/src/domain-suggestions/resolvers.ts#L71) packages could inform the consuming app about errors. 

That way, we would know that the site title is invalid as a blog name **_before_** we create the site, so we can act accordingly.

The domains/suggestions API response is a 400 with the following data:

```
error: "invalid_query"
message: "Please change your search as it includes words that we don't allow"
```

I was thinking we could add a prop to `<DomainPicker />` for example `onDomainSearchError()` that would fire and return some data when the domain suggestions API response with an error.

If we want to be specific we could also send the error key (`e.error`) to the `receiveDomainSuggestionsError` [action in the domain-suggestions store](https://github.com/Automattic/wp-calypso/blob/7a27876c58ef4bc1d5e06709eb6b552156fe82b5/packages/data-stores/src/domain-suggestions/resolvers.ts#L71), then do something with that.

It might not be as quick as throwing a workaround on the backend I believe, but way we validate domains on the backend, especially in the case of blacklisted words, is fairly verbose and recursive and could do with some refactoring.

There's probably an easier way to do all this. Folks with more experience working with Gutenboarding will know better than I do.

**Comment by ramonjd** [comment]
Actually, I didn't take into account the scenario where the user:

1. types a blacklisted domain keyword into the site title field, e.g., `WordPress`
2. searches for a blacklisted domain keyword on the domains page, e.g., `bankofamerica`, and then clicks "Skip"

In that case we'll send the blacklisted site title as a fallback.

I think that means we should always do a check on whatever value we try to set for `blog_name` 🤷

**Comment by yansern** [comment]
**Quick fix:**

I suggest that for quick fix, when the `site_creation_flow` is `gutenboarding`, when the site title cannot be validated on the server side, we'll fallback to the site title `Site` (that's what currently being used when user skips entering site title).

Here's a phab patch for that: D56420-code

**Long term fix:**

> I think that means we should always do a check on whatever value we try to set for blog_name 🤷

It appears that the create new site API endpoint at `/sites/new` has a `validate` param that just validates the blog name. When `validate=1`, it will return the WP_Error object with the relevant error message.

So on the client-side during the Name step, we could make a request to validate the site title in the background and show that error message. Design needed.

**Comment by yansern** [comment]
The quick fix is actually the better fix than the long term fix as it doesn't hinder the user from entering any site title they wish, while allowing users to continue create site.

**Comment by yansern** [comment]
Deployed.
