### ISSUE TITLE
Focused Launch: Replace "Back" buttons with ButtonArrow onboarding component

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48568]
The `<GoBackButton/>` should be replaced by the `<ArrowButton />` from `@automattic/onboarding` which is styled exactly how is presented in the Focused Launch Figma designs.

#### Acceptance criteria
* [ ] The `<GoBackButton/>` is replaced by the `<ArrowButton />` in the DomainDetails View.
* [ ] The `<GoBackButton/>` is replaced by the `<ArrowButton />` in the PlanDetails View.
* [ ] The `<GoBackButton/>` component is removed.
* [ ] Refactor the component's styles (including [this](https://github.com/Automattic/wp-calypso/pull/49249/files#r564420245))

#### Additional info
> Blocked until https://github.com/Automattic/wp-calypso/pull/48119 is merged as this PR contains the necessary component

**Comment by StefanNieuwenhuis** [comment]
@tjcafferkey, due to the `min-width` and `padding` properties of the `<ArrowButton/>`, the component isn't aligned properly (see screenshots). In order to make it more agnostic (i.e. reusable in different use-cases), I suggest to remove the properties from the component and add them to its parent containers. Since the component is only used in `packages/domain-picker/src/domain-picker/use-your-domain-item.tsx`, it's a small effort to refactor. What do you think?

#### What I got
<img width="322" alt="Screenshot 2021-01-18 at 11 42 58" src="https://user-images.githubusercontent.com/12104589/104905401-924be500-5982-11eb-87e3-9a95214a8e71.png">

#### Expected
<img width="398" alt="Screenshot 2021-01-18 at 11 45 29" src="https://user-images.githubusercontent.com/12104589/104905485-b4ddfe00-5982-11eb-8505-c75d9011b3ea.png">

**Comment by tjcafferkey** [comment]
@StefanNieuwenhuis I don't think that button is currently used anywhere as far as I know (worth checking) so removing these properties to make it more reusable if needed in theory shouldn't be an issue.

**Comment by jordesign** [comment]
@razvanpapadopol Is 'Focused Launch' an ongoing concern - so this is still relevant?

With the 'Launch' button no longer in the editor - I wasn't sure if it is still in use.

**Comment by Robertght** [comment]
I removed the stale label for now from all the issues related to the `Focused Launch` so we can track the issues better on our end. Previous issue: https://github.com/Automattic/wp-calypso/issues/47112

@razvanpapadopol if I should revert the change, please let me know.

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
