### ISSUE TITLE
Expired credit cards don't appear on the Payment Methods page and can't be deleted, even when they are still attached to a subscription

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#48703]
### Use case
A user wishes to retain an active subscription on WordPress.com but does _not_ wish for their payment details to be saved. Instead, they would prefer to manually log in and enter their payment details after receiving an expiry notice/warning from us as their subscription(s) near expiry.

### What I expected
After deleting all payment methods via `Manage Purchases`, I expect there to be no means of payment connected to any active subscriptions. This is not the case.

### What happened instead
Even after removing payment methods from Calypso, via `Manage Purchases > Payment Methods`, details are still stored at a subscription-level and will be used if auto-renew is enabled.

It is possible for users to update payment methods on active subscriptions but not delete them. 

### Screenshots

The screenshots below show subscription-level payment methods are still set, even though they have been removed from `Manage Purchases > Payment Methods`.

**Fig 1: Manage Purchases**

![01 Manage Purchases ](https://user-images.githubusercontent.com/66711744/103849797-9b19fc80-50e0-11eb-8c25-0b12a9595eac.png)

**Fig 2: Manage Purchases > Purchase Settings**

![02 Manage Purchases - Purchase Settings](https://user-images.githubusercontent.com/66711744/103849811-a2d9a100-50e0-11eb-8d4d-5846d97e8ea8.png)

**Fig 3: Manage Purchases > Purchase Settings > Change Payment Method**

![03 Manage Purchases - Change Payment Method](https://user-images.githubusercontent.com/66711744/103849804-9f461a00-50e0-11eb-848e-d64a7c647b7c.png)

### Context / Source
I appreciate this is an edge case but feel it important that if a user requests that payment method is removed via a self-serve option, that it is completely removed by us. 

I also appreciate this might cause issues further down the line at renewal if payment methods were unintentionally removed by users. However, I believe this can be addressed by using the existing error/information notification settings to communicate missing payment information.

Requests like this stem from a desire for privacy and reducing exposure to financial damage in the event of hacked/compromised service providers. I believe we should respect them.

#empathy #perspective #anxiety #user-report 

- 3626233-zen
- pNPgK-5iB-p2

**Comment by DavidRothstein** [comment]
This is an issue for expired cards specifically, since they aren't shown at https://wordpress.com/me/purchases/payment-methods so there's no way to delete them.

We're discussing the overall behavior of expired cards internally at 93-gh-Automattic/payments-shilling and that would handle this issue, but I'll keep it open separately for now since perhaps it's possible we could handle just showing the cards and allowing them to be deleted separately.  But I'll move this issue to the same backlog for discussion.

**Comment by inaikem** [comment]
Thanks for the context. I've not been able to test it myself yet but I'd like to know if the behaviour described here also applies to valid cards:.

_Payment method added, used to purchase and removed but still billed on renewal if auto-renew was enabled._

It seems to me that removing the card should take precedence over the renewal regardless of the payment method's validity (there's clearer intent there).

Just a thought.

**Comment by DavidRothstein** [comment]
Deleting a credit card also removes it from all subscriptions, so no, it shouldn't be an issue for any valid card that is deleted.   The only issue is that expired credit cards can't actually be deleted from within Calypso.

**Comment by michaeldcain** [comment]
From Shilling's planning call:

Let's try to add a parameter (`include_expired`) to the `me/stored-cards/` endpoint to return expired cards, and then set that parameter to true for Payments Management screens. Stored cards are stored in state, so we'll want to make sure that the expired ones aren't returned anywhere unexpectedly.

**Comment by sirbrillig** [comment]
It turns out there's already an endpoint called `/me/payment-methods` which is newer than `/me/stored-cards` and already includes an `expired` parameter. We're already using that endpoint in calypso for the `QueryStoredCards` query component, so if we pass the `expired` parameter there, we should get expired cards saved in the Redux store automatically, to be used everywhere that uses the Redux store for saved cards. The challenge, I imagine, is to make sure we don't display expired cards in places where we want to avoid them.

To help with that, here's a list of places that I know use stored cards:

- Checkout. (This does not use the cards from Redux and has its own fetcher.)
- The post-checkout one-click upsell modal. (This does use `getStoredCards` so it will be affected.)
- The account-level and site-level payment method lists. (This is the form we care about here and does use `getStoredCards`.)
- The account-level and site-level "change payment method" forms. (This does use `getStoredCards` so it will be affected.)
