### ISSUE TITLE
Settings > Ratings is a Broken Link 

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/wp-calypso#48724]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/home/
2. Click Settings
3. Click Ratings

#### What I expected
To see the Ratings Page

#### What happened instead
An empty Settings page was displayed: 
![screenshot](https://d.pr/i/QGlFdd+)
[Direct Link](https://d.pr/i/QGlFdd)

#### Browser / OS version
Chrome: Version 87.0.4280.141 (Official Build) (x86_64)
macOS Big Sur - Version 11.1

#### Screenshot / Video
[](https://d.pr/i/QGlFdd)

#### Context / Source
#dogfooding
#manual-testing

**Comment by cathymcbride** [comment]
Hi @marcuswisecaesar! Can you add more information to this? What sort of site are you on? I'm having trouble reproing this.

**Comment by marcuswisecaesar** [comment]
Hello @cathymcbride ! 

Apologies for not providing more information!  

Simple Site > Premium Plan 

Here are 2 .gif's to illustrate: 

![screenshot](https://d.pr/i/znwni5+)
[Direct Link](https://d.pr/i/znwni5)

![screenshot](https://d.pr/i/I4EbVl+)
[Direct Link](https://d.pr/i/I4EbVl)

This is on a Simple Personal Plan site: 

![screenshot](https://d.pr/i/D6gWMS+)
[Direct Link](https://d.pr/i/D6gWMS)

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was not able to reproduce this issue, mostly because the Settings > Ratings menu no longer exists for the various sites I have tried with the following plans:

- WordPress.com Premium
- WordPress.com Business
- WordPRess.com no plan

Please see attached screenshot from a WordPress.com Premium site.
![Screen Shot 2021-07-19 at 1 23 09 PM](https://user-images.githubusercontent.com/6549265/126222424-bf3e9b13-fac6-4d49-8f54-5845f7e3e259.png)

If this issue should remain open, please feel free to re-open this bug.
