### ISSUE TITLE
Editor: Localization bug

### ISSUE THREAD

**Issue by EmreYigitAlparslan** [Automattic/wp-calypso#48770]
I have clicked on the "Add a menu" button in my new site's home. It directed me to Editor, and a tip popup has shown up. Although the rest of the page was Turkish, the tip description was English. 

#bug #editor

<img width="1435" alt="Screen Shot 2021-01-09 at 4 43 06 PM" src="https://user-images.githubusercontent.com/9999399/104205569-9be3c300-543f-11eb-97c5-efe5681051a2.png">

**Comment by emilyaudela** [comment]
The [string](https://translate.wordpress.com/projects/wpcom/tr/default?filters%5Bterm%5D=here+you+can+control) hasn’t been translated yet. I have added it to our watched paths and it will be sent to translation next week. I have also created a [deliverable](https://translate.wordpress.com/deliverables/overview/5428162/) so that our internal team can take of it faster for some languages.

**Comment by cathymcbride** [comment]
@EmreYigitAlparslan This looks fixed on this end. Do you still repro?

**Comment by EmreYigitAlparslan** [comment]
@cathymcbride Since the pop-up didn't show up, I couldn't test if it is fixed. Let me know if there is a way the see that manually.
