### ISSUE TITLE
Add New Page Screen: Jetpack subscriptions block not rendering in preview.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48888]
#### Steps to reproduce the behavior

1. Go to add new page screen
2. Click on first blog layout (noted below)
3. Scroll down subscriptions block in preview (see below)
4. Notice that the email input is just a white box (see below)

#### Result

![image](https://user-images.githubusercontent.com/545779/104503652-f8adbd80-55a6-11eb-9637-7c8791b92313.png)

Strangely, this seems to render more or less correctly once you proceed to the actual editor itself.

![image](https://user-images.githubusercontent.com/545779/104503730-0cf1ba80-55a7-11eb-9114-cee48fe29859.png)

### Browser / OS version

Chrome, MacOS

**Comment by andrewserong** [comment]
While looking into this, I noticed that the subscription forms for the Bowen, Edison, and Cassel layouts were throwing block validation errors in the preview and when inserted in the page:

E.g.

![image](https://user-images.githubusercontent.com/14988353/104997273-6eb99500-5a7d-11eb-8152-0dc3be21e16f.png)

From comparing the markup before and after clicking Attempt Block Recovery, I can see that in the before markup, the shortcode includes a custom placeholder and submit button text, but those strings do not appear in the block metadata JSON literal, which appears to be what caused the validation error. Because these strings match the new(er) placeholders introduced in Jetpack 9.3 (https://github.com/Automattic/jetpack/pull/18073), we can remove them. I've gone in and updated these three layouts in dotcompatterns to remove the custom placeholder and subscribe text, so the validation issues should be resolved once the cache clears (but the strings will be the same for a user).

We'll then be able to look at the styling issue reported here :)

**Comment by andrewserong** [comment]
@ianstewart it turns out that the white box where the input field is meant to be is actually a block error notice! The block is currently failing when rendered within a preview (a Disabled context) when there is no color set for both the background and text for the button. It looks like this is set for the other layouts (either a custom color or a named color). To fix in the short term we can update the block within the Bowen layout, but I've put together a fix in Jetpack for this in https://github.com/Automattic/jetpack/pull/18446

I didn't update the layout in dotcompatterns, just because it's easier to test the fix if we leave it broken, but if you'd prefer to have the workaround in place immediately, do feel free to update it! (Or I can tomorrow)

**Comment by andrewserong** [comment]
Closing now as the fix (https://github.com/Automattic/jetpack/pull/18446) has been rolled out to production.
