### ISSUE TITLE
Add New Page Screen: Contact Form not rendering correctly in preview

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48889]
#### Steps to reproduce the behavior

1. Go to Add New Page Screen
2. Click on the contact pattern indicated below
3. See error in preview noted below

#### Result

![image](https://user-images.githubusercontent.com/545779/104504359-f1d37a80-55a7-11eb-9a8e-3ac2a0e222bb.png)

#### Expected

Contrast with the result of the page layout when it's inserted into post content after clicking the accept button on the add new page screen.

![image](https://user-images.githubusercontent.com/545779/104504443-10397600-55a8-11eb-80fa-5bbb1daf32da.png)

**Comment by andrewserong** [comment]
It looks like the missing styles are from the [BaseControl component](https://github.com/WordPress/gutenberg/blob/4885681f05a6eb0b80764d8710839a158475afd5/packages/components/src/base-control/index.js#L37) which is used by the `jetpack/field-textarea` component. BaseControl uses Emotion for its CSS-in-JS in the editor, and it appears it's these styles that aren't being picked up by the iframe. I suspect due to the styles being dynamically injected when the preview is updated, where the preview's iframe is only loading the styles once, before those styles are injected. I'm curious if we could get this working by borrowing the iframe component from Gutenberg, which already handles much of the copying of styles, and see if that helps: https://github.com/WordPress/gutenberg/blob/541141d49bd48da25b22f568506cca1f24ab5b5b/packages/block-editor/src/components/iframe/index.js#L30

**Comment by andrewserong** [comment]
Since the page layout picker is going to be rebuilt and will likely use mShots screenshots, I think the higher priority issue to fix with this block, is the behaviour when rendered in the template/demo endpoint preview, tracked in 216-gh-Automattic/view-design

**Comment by andrewserong** [comment]
@ianstewart I've fixed the Contact Form preview when it's rendered by the `template/demo` endpoint (216-gh-Automattic/view-design), which will fix its rendering in the new page layout picker (and should fix it in the thumbnails in the existing layout picker).

The outstanding issue is in the large preview where the textarea isn't inheriting the `width: 100%` style which is set by Emotion. Rather than try to dig into the large iframe and figure out how to transfer styles generated on the fly by Emotion, I thought we could close this issue now, as the solution for fixing up the iframe is non-obvious. Does that sound okay to you?

**Comment by andrewserong** [comment]
Closing for now.
