### ISSUE TITLE
Add New Page Screen: Image Thumbnails not loading when using `blank-canvas` theme

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48932]
1. Activate blank canvas theme using instructions at pNEWy-du1-p2
2. Click on Add New Page
3. Observe thumbnail error shown below

![image](https://user-images.githubusercontent.com/545779/104645268-75f33400-5674-11eb-9adc-3f7cfa83c0cc.png)

This seems to **only** happen with the Blank Canvas theme, which is not yet network-activated.

cc @kjellr

**Comment by andrewserong** [comment]
@ianstewart I believe this one should be fixed by D56048-code which updated the template/demo endpoint preview to support specifying the theme and rendering the preview in that theme's context. This has just been deployed, but it might take up to a day for the mShots cache to be refreshed, I believe, but that particular image that was 404ing is now working correctly for me:

![image](https://user-images.githubusercontent.com/14988353/106098285-dd3cd800-618c-11eb-9836-67ad1b0e4a2a.png)

That diff (D56048-code) attempts to use the site's currently selected theme, if available, and falls back to Hever if for some reason it isn't available. So, once the cache has cleared, the screenshots should start looking _closer_ to how they'd look on the user's site.

**Comment by andrewserong** [comment]
The caches are updated and all the screenshots appear to be rendering now using `blank-canvas` when the site is set to that theme:

![image](https://user-images.githubusercontent.com/14988353/106210757-8a5e3180-621b-11eb-868d-e94f7891f227.png)

I'll close this issue out now, but let us know if you encounter any other peculiarities with `blank-canvas`!
