### ISSUE TITLE
Interface Language change in Calypso not synced to WP Admin dashboard for Atomic site

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#48980]
#### Steps to reproduce the behavior

1. Go to https://wordpress.com/me/account
2. Change "Interface Language" from English to a different language for example
3. Go to WP Admin dashboard for one of your Atomic sites
4. Check if the interface language in WP Admin was switched to the language you chose in Step 2

#### What I expected to happen

I expected the interface language in WP Admin to be changed automatically.

#### What actually happened

The interface language in WP Admin remained English. And we need to change WP Admin's interface language manually by going to https://EXAMPLE.COM/wp-admin/profile.php/.

<img width="1872" alt="Screen Shot 2021-01-18 at 08 12 15" src="https://user-images.githubusercontent.com/32432463/104858791-0a0b1700-5965-11eb-9fd6-5cc8296d5b34.png">

**Comment by JoshuaGoode** [comment]
Reproduced.

On the two Atomic test sites I used, the default user profile Language setting is set to `Site Default` instead of `English`.  

This will be problematic with Nav Unification as accessing the profile settings page will be a bit more difficult unless the user has enabled the option to use WP Admin equivalents when possible or we share the direct link to the page. 

Outside of this setting not syncing, other `/me` and `/me/account` settings including username, email, name, about, and web address are not syncing between the WPCOM profile and the connected user on Atomic sites. 

These additional items not syncing have been reported on https://github.com/Automattic/wp-calypso/issues/46077

**Comment by obenland** [comment]
This should be fairly straight forward to do by extending the way color schemes are currently synced.

**Comment by cpapazoglou** [comment]
@allilevine with https://github.com/Automattic/jetpack/pull/19525 being merged, I think we can close this too?

**Comment by allilevine** [comment]
Yes thanks! Closed by https://github.com/Automattic/jetpack/pull/19525 🎉

**Comment by hacchism** [comment]
Awesome! Thank you✨
