### ISSUE TITLE
Mappings: Confusing Message When Removing It

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#49043]
#### Steps to reproduce the behavior
1. Go to Manage > Domains on a site where you have a mapping upgrade
2. Click on 'Delete domain mapping'

#### What I expected to happen
To maybe show a message to confirm the mapping removal, with a warning that the site will stop loading with it - something like that.

#### What actually happened
It asks for a reason to be removed, and warns that you won't be able to use it again without getting a plan - although the site is already on a plan and mappings are free and unlimited.

#### Screenshot / Video
From a site with a Personal plan:

![RemovingMapping](https://user-images.githubusercontent.com/16104522/105067837-e926ec80-5a5e-11eb-9926-b670b669e507.jpg)

#### Context
Confusion reported by user on 3644230-zd-woothemes

**Comment by DavidRothstein** [comment]
I think "purchasing a new subscription" refers to a domain mapping subscription in this case (not a plan subscription) -- it's just generic text that is used for any product.  But this is definitely confusing, especially with domain mappings being free.

And (from p2MSmN-8vd-p2) it sounds like it can be confusing wording even when removing non-mapping products too, like plans, I guess because it's not clear what the "it" in "reuse it again" refers to.

We could probably just replace all this text with text that's more similar to what is used in the case where a refundable subscription is being removed (minus the parts of the text that refer to refunds, of course), and make up some new default text to use for products that aren't already specifically listed there: https://github.com/Automattic/wp-calypso/blob/3ad54614a4022826034ef4312e82b1df2d014c06/client/me/purchases/cancel-purchase/cancellation-effect.jsx

**Comment by ChrissiePollock** [comment]
This was also brought up in 23548141-hc.

**Comment by chrisfromthelc** [comment]
> But this is definitely confusing, especially with domain mappings being free.

@DavidRothstein There is an exception to this; on a free site, the domain mapping is still $13.

We could change it to something like:

<img width="546" alt="Screen Shot 2021-08-11 at 3 38 15 PM" src="https://user-images.githubusercontent.com/8002138/129112870-007c2417-c07e-4893-a055-295a79208b63.png">

I whipped up a draft PR in #55399 if it looks like this is a good direction to go in.

**Comment by DavidRothstein** [comment]
>There is an exception to this; on a free site, the domain mapping is still $13.

Yes, that's true (although it's a lot less common) -- but even then, I'm not sure it's that important to talk about "starting a new subscription"?

Let me elaborate on my comment above a bit more:

>We could probably just replace all this text with text that's more similar to what is used in the case where a refundable subscription is being removed (minus the parts of the text that refer to refunds, of course)

This is the text we currently use when removing and refunding a plan within the refund window:

![cancel-refund-personal](https://user-images.githubusercontent.com/235183/129275305-013d7d0b-f28f-4d6e-9a59-82773498f40a.png)

The "All plan features and custom changes will be removed from your site" pattern seems pretty useful to me (more useful than just telling people that they'd need to purchase a new subscription to get it back).  So that's why I was wondering if we could just use similar wording here (when removing a non-refundable subscription).  What do you think?

For domain mappings, we don't seem to have equivalent wording to the "All plan features and custom changes will be removed from your site" right now, but we could add something.  It does seem useful to me to tell people exactly what will happen to their site when the domain mapping is removed...

**Comment by DavidRothstein** [comment]
We should probably look a bit into the origin of the current "without purchasing a new subscription" wording though.  It may have been added as an attempt to make people understand that even though they were removing their subscription early (before the expiration date) they still wouldn't be able to just get it back for free.  But if that's the goal, I think there is probably still a better way to communicate that.
