### ISSUE TITLE
Onboarding: "Site Language" in Japanese doesn't fit the UI on design selector screen

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#49061]
The translation for "Site Language" in the language picker for Japanese sometimes breaks out of the header bar on small screens.

The `/new/design/ja` page seems to be the only place this occurs - with the domain picker and jetpack icon squashing the available space in between.

Other locales seem to be fine but I suspect this is because they all use two words. The fix is probably to just apply a word break rule. Or potentially just not show this label on mobile - it looks pretty cramped in most languages including english.

#### Steps to reproduce the behavior

1. http://calypso.localhost:3000/new/design/ja

#### What I expected to happen

"Site language" in Japanese to fit

#### What actually happened

It didn't

#### Browser / OS version
Mobile screen size (iphone 6/7/...)

#### Level of impact
Minimal, I don't think the language picker is live? And other pages during sign up manage to fit the full text in the header bar.

#### Screenshot / Video:
![Screenshot(14)](https://user-images.githubusercontent.com/811776/105122985-5e5ff380-5b2b-11eb-8587-ca9d605be5a6.png)

**Comment by Copons** [comment]
As @lsl guessed, that language picker only shows up in dev and Horizon, so it doesn't directly affect users.
The site language label already uses correctly the word break, but whereas most languages use spaces between words, Japanese doesn't, and so we end up with 1 character per line instead of 1 word per line.

There are many possible solutions for this, including hiding the language picker on small screens, or showing only the language badge.
I'd defer to @Automattic/ganon for a design decision. 🙂

**Comment by ramonjd** [comment]
> showing only the language badge.

Thanks @Copons 

What about a combination of your suggestions: showing only the language badge on smaller screens? 😄

**Comment by Copons** [comment]
> > showing only the language badge.
> 
> Thanks @Copons
> 
> What about a combination of your suggestions: showing only the language badge on smaller screens? 😄

Ahah yes, I fumbled the sentence above, I meant all the above to be for small screens only. 😄 

Either way, I'll open a quick one ASAP!
