### ISSUE TITLE
Link to initiate Support Chat is overlapped by upsell box in checkout

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49150]
### Steps to reproduce the behavior

Prereq: Use a free site with no purchases.
1. Go to My Site.
2. Add domain to site.
3. Choose a custom domain.
4. Add to cart and check out.
5. Skip G Suite integration.
6. At secure checkout, inspect the right pane.

#### What I expected to happen
Link to initiate Support Chat should be clearly visible.

#### What actually happened
`Upgrade and Save` upsell box overlaps half of the link.

### Context
Manual user testing.

#### Browser / OS version
Browser: Firefox Nightly 86.0a1
OS: macOS Catalina 10.15.7

#### Is this specific to the applied theme? Which one?
N/A.

#### Does this happen on simple or atomic sites or both?
N/A.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - user is still able to initiate chats through the `?` icon on the bottom right if needed.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-01-21 at 12 03 20](https://user-images.githubusercontent.com/6549265/105406865-dc7ed180-5be1-11eb-9e40-2f758ed8e68d.png)

**Comment by sirbrillig** [comment]
For some additional info, the component that displays the support link is [`CheckoutSummaryHelp`](https://github.com/Automattic/wp-calypso/blob/a7ee7a2af4b1bc56efebdb82212ba61dd44e15f7/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js#L317) and the component that renders the upsell is [`CartFreeUserPlanUpsell`](https://github.com/Automattic/wp-calypso/blob/a7ee7a2af4b1bc56efebdb82212ba61dd44e15f7/client/my-sites/checkout/cart/cart-free-user-plan-upsell.jsx#L36). The cause of the issue seems to be that [CheckoutSummaryHelpWrapper uses absolute positioning](https://github.com/Automattic/wp-calypso/blob/a7ee7a2af4b1bc56efebdb82212ba61dd44e15f7/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js#L447) to put itself outside of its container, which was added in https://github.com/Automattic/wp-calypso/pull/48345.
