### ISSUE TITLE
Nav Unification: Unable to update passwords and email addresses in Users > All Users 

### ISSUE THREAD

**Issue by nixiack** [Automattic/wp-calypso#49211]
### Steps to reproduce the behavior

1. Go to 'Users > All Users'
2. Click on any user
3. Scroll down to the bottom of the User
4. It only allows for role change, display name and name change, and deletion of user.  

#### What I expected to happen

When going to the Users and selecting a User, there should be the option to change the password, change email, etc.  as the standard WordPress Core user interface screen allows.

#### What actually happened

Can only change Role, Name, Display Name.  Can also delete user, but that is it.  No address change options, no email update or password update option allowed.

#### Browser / OS version: 
Chrome Version 87.0.4280.141 (Official Build) (x86_64)

#### Is this specific to the applied theme?

No, this is in the back end WP-Admin area.

#### Does this happen on simple or atomic sites or both?

Atomic for now, requires Business/EComm plan for WooCommerce capability.

#### Is there any console output or error text?

No, none in Console:

![screenshot](https://d.pr/i/TvbXij+) **Image Link:** https://d.pr/i/TvbXij

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It blocks us from being able to alter users when needed to test for various issues, and it will block any Admin level user on any site to be able to effortlessly change a lower level user for updated email and / or password.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

GIF:

![screenshot](http://recordit.co/Uab4FE4SMa+) **Image Link:** http://recordit.co/Uab4FE4SMa

**Comment by cpapazoglou** [comment]
👋 @nixiack, thanks for reporting this! We are planning to address this issue as part of https://github.com/Automattic/wp-calypso/issues/47043. https://github.com/Automattic/wp-calypso/issues/47043#issuecomment-765579539 shows a suggested solution. 

Till then, would using `[DOMAIN]/wp-admin/users.php` suffice?

**Comment by cpapazoglou** [comment]
This issue will be resolved by https://github.com/Automattic/wp-calypso/issues/49262

**Comment by cpapazoglou** [comment]
We will need to add a link `People -> Advanced Users List [/wp-admin/users.php]` only for WoA.

**Comment by mmtr** [comment]
> It blocks us from being able to alter users when needed to test for various issues, and it will block any Admin level user on any site to be able to effortlessly change a lower level user for updated email and / or password.

I need some clarification about that.

I did some tests on my Atomic and eCommerce test sites, and changing the email or password from the WP Admin screen didn’t cause any effect, because SSO is enabled and users are still required to log in through wordpress.com/log-in using the previous email/password.

AFAIK, if SSO is enabled, changing the email/password in WP Admin don’t sync the changes back to the WP.com account.

On the other hand, when SSO is disabled, then the WP Admin screen for managing users is relevant, since it's the only way of fully managing users.

According to this quick research, I think we should:
- If SSO is enabled: always link to Calypso since the WP Admin screens won't work for updating the email/password of a user.
- If SSO is disabled: always link to WP Admin since the Calypso screens don't offer support for updating the email/password of a users.

@nixiack, did I miss any other scenario?

**Comment by mmtr** [comment]
I discussed the above with @nixiack on Slack and apparently the ability to change email/passwords is used on eCommerce sites even when SSO is enabled:

> When an admin user gets a notification that they need to change a password or a user email address, they cannot.
>
> in standard WP-Admin screens, I can change them: https://d.pr/i/K4ZPXt
>
> This is required if an Admin gets a customer email that was created from placing an order, or a Vendor who is selling items on the site, etc. they cannot change it - I doubt it would be good to tell the user they have to reset the pass with a reset pass link and cannot change email ever.  (I have Product Vendors installed on my AT site, and that user in the screenshot above is a Vendor).  Directing it to just be the `/wp-admin/users.php` area should just stick; it was that way prior to the nav change
>
> I believe it is just best practice to allow users to be able to change passwords for those registered on their sites (if also email addresses).

I still have not replicated that flow, since I'm not very familiar with WooCommerce, but will try to investigate a bit further in order to see the content of those emails. cc @cpapazoglou in case you are aware of anything else.

**Comment by mmtr** [comment]
Alright, it seems that many plugins (e.g. WooCommerce Product Vendors PbTz5e-tD-p2) may need to edit users through WP Admin screens, regardless the SSO status, so we should always link to both Calypso and WP Admin to cover all possible usages.

**Comment by mmtr** [comment]
On a second thought, and after reviewing once again the whole discussion at paYJgx-1lp-p2, I think the current proposed solution at https://github.com/Automattic/jetpack/pull/18805 should work:
- If the "Replace all dashboard pages with WP Admin equivalents when possible" setting is disabled, we add a link to `/wp-admin/users.php`.
- If the "Replace all dashboard pages with WP Admin equivalents when possible" setting is enabled, we don't change the menu.

That will mean that users with the setting enabled will miss the menu that links to the invite user page, but as noted in the mentioned post by @obenland, the setting is the appropriate tool for that. If a user has enabled the setting, it will likely mean they are only interested in the features offered by WP Admin.

**Comment by getdave** [comment]
Removing the `Blocker` label as this is tracked elsewhere on our roadmap under https://github.com/Automattic/wp-calypso/issues/49262.
