### ISSUE TITLE
Testing: run a subset of the tests from the command line and watch for changes

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#4922]
Part of https://github.com/Automattic/wp-calypso/issues/4915

- Would be nice to be able to run a subset of the tests. I tried the `-g LoginTest` and it did work if I call the runner directly (`NODE_ENV=test NODE_PATH=test:client TEST_ROOT=client test/runner.js -g LoginTest`) but not from `npm test`.
- Would be cool to watch a directory also so we could please our TDD fans ;)

**Comment by gziolo** [comment]
It's partially done thanks to @aduth work done in #5465 :)
You can execute all tests in a given subfolder now!

**Comment by samouri** [comment]
File Watching with Mocha
--
Given that mocha allows for watching for files, my initial thought was to just pass through the watch flag to mocha like we do for a few of the other flags.

It turns out that Mocha does not support file-watching when used programmatically (as opposed to through their cli executable).  This is a bad thing in that we don't get file-watching for free but at the same time a good thing because they've set an example to follow for implementation.

- [watch utility function](https://github.com/mochajs/mocha/blob/8a37e016e5629b46709891740c74d5f0b69929e0/lib/utils.js#L168)
- [bussiness logic to rerun-mocha](https://github.com/mochajs/mocha/blob/b76989ceb8ca38b4ad9a2df4892581d96e8c4ba8/bin/_mocha#L343)

My current plan is to implement watching similarly to how mocha did (While keeping @aduth's logic for deciding which files to include).

**Comment by samouri** [comment]
PR for file watching: #6000

**Comment by samouri** [comment]
Now that #6321 has been merged, this can be closed
