### ISSUE TITLE
calypso.localhost:3000 refuses to authenticate in Safari

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#49237]
### Steps to reproduce the behavior

1. In Safari 14, go to calypso.localhost:3000
2. Try to log in

#### What I expected to happen

Logged in

#### What actually happened

Redirected to devdocs with no explanation

#### Browser / OS version

Safari 14, macOS 11.1 (Big Sur)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Total inability to log in

**Comment by jsnajdr** [comment]
The REST proxy iframe relies on sending cookie-authenticated requests to _public-api.wordpress.com_. And because the top-level domain for local Calypso is _calypso.localhost_, the _public-api.wordpress.com_ domain is third-party. And Safari blocks third party cookies. Therefore _public-api.wordpress.com_ requests are not authenticated. This approach is broken forever and will never work again.

The solution is to use OAuth authentication for local Calypso. Here are steps to make it work:
1. Go to [developer.wordpress.com/apps](https://developer.wordpress.com/apps/) and register a new OAuth app there. Specify `http://calypso.localhost:3000` as one of the Redirect URLs.
2. Create a local `config/development.local.json` file in your `wp-calypso` repo and put your OAuth client ID there:
```
{
  "oauth_client_id": "NNNNN"
}
```
Note you don't even need the client secret! The auth loop doesn't need it and merely checks that you're coming from the correct registered URL.

3. Start local Calypso with `ENABLE_FEATURES=oauth yarn start`
4. Load `http://calypso.localhost:3000` in Safari.

You'll be taken through the OAuth authorization loop:

<img width="477" alt="Screenshot 2021-02-22 at 14 26 00" src="https://user-images.githubusercontent.com/664258/108714615-0c3f3300-751a-11eb-9bf1-68fadee2bd0e.png">

And then redirected back to a logged-in Calypso. Without cookies, with all REST authentication done with `Authorization: Bearer <oauth-token>` headers.

There's still plenty of little things that don't work, but most of the time this OAuth Calypso in Safari is OK. This is the future! I'm working on fixing all the little things one patch at a time.

**Comment by jsnajdr** [comment]
This was fixed by adding an OAuth/Cookies toggle to dev mode to switch between authentication methods in #53402.
