### ISSUE TITLE
Reader: Back button in full post view conflicts with Cloudup embeds

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#4924]
#### Steps to reproduce
1. On a blog you follow in the reader, publish a post that contains a Cloudup embed with multiple items
2. Visit https://wordpress.com/ and notice the post
3. Click on the post title to reach the full post view
4. Click to advance through the Cloudup Embed
5. Click the back button to leave the full post view
#### What I expected

Return to the Reader view
#### What happened instead

The Cloudup Embed retracts to previous item
#### Browser / OS version

Chrome 49 , WordPress.com for Mac 1.3.1, Safari 9
#### Screenshot / Video

https://cloudup.com/cMIaGSEN2ot

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue, OSX Chrome v51

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed with Safari 9.1 on Mac OS X 10.11.5 using the steps provided ([5s](https://cloudup.com/cqwx0_aeWlG))

<strong>Result:</strong> clicking the right arrow in the Cloudup embed to advance to the next image and then clicking the back button in the Reader full post view triggers the cloudup embed to go back one image instead of going back to the post stream in the Reader as expected

**Comment by blowery** [comment]
I don't think there's anything we can do here. This is a standard browser feature.

**Comment by alexjgustafson** [comment]
> This is a standard browser feature.
Could you clarify this a bit? The issue is when using the back button provided within the Reader full post view, not the browser's back button. 

Is our back button meant to be always be tied to the behavior of the browser's button?
