### ISSUE TITLE
Launch flow: 2nd domain sales step broken on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49311]
- Create a free site
- Launch it
- Continue on free option across regular domains step & plans step
- 2nd domain sales step doesn't look great on mobile:

Regular mobile devices:

<img width="453" alt="Screenshot 2021-01-26 at 17 45 39" src="https://user-images.githubusercontent.com/87168/105868149-886b5700-5ffe-11eb-8bc8-036d6fa45f5e.png">

Bigger screen mobile devices:

<img width="457" alt="Screenshot 2021-01-26 at 17 45 45" src="https://user-images.githubusercontent.com/87168/105868160-8a351a80-5ffe-11eb-8444-752bcd548a35.png">

Possibility to continue for free is under the fold even on bigger screens. Note also help FAB disappearing outside the viewport:

<img width="467" alt="Screenshot 2021-01-26 at 17 45 56" src="https://user-images.githubusercontent.com/87168/105868165-8bfede00-5ffe-11eb-94d8-7c0376eb3c9d.png">

**Comment by aneeshd16** [comment]
FYI https://github.com/Automattic/wp-calypso/issues/49285 is another bug related to the same screen and also needs some design guidance. 🙂

**Comment by ollierozdarz** [comment]
@simison @olaolusoga.

For a quicker win for mobile, I've tried to break this down to three actions.

1. The quick win here is fix the button, since the long text is what's breaking the UI. If we add `max-width: 100%;` to the primary Pink `button`, this will automatically add truncation (ellipsis) after two lines, which I think it the right approach. This also fixes the FAB being pushed outside of the viewport.

2. The 'No thanks, I'll stick with X site..' option could be moved up into the White table as the last option. Agree with @simison that it's probably going to be under the fold most of the time, and while we'd rather push users to purchase a domain, I'd be worried this being hidden could lead to frustration/churn.

3. If we act on the first two options, we could make the primary Pink button area `position: fixed;` to the bottom, and have it stick to the bottom of the page. This way it's always in view and the other options are still scrollable.

As the size of the viewport gets smaller, the entire page seems to fall apart, which feels like a bigger scope to fix.

**Comment by simison** [comment]
https://github.com/Automattic/wp-calypso/pull/50234 removed the step, closing.
