### ISSUE TITLE
Plans Grid: persist value of the billing period in store

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#49339]
## What

Persist in the launch store the `billingPeriod` (at the moment it always "resets" to annual)

## Why

This would improve the UX around plans selection, and avoid confusion in the user

## A/C

- [x] When showing the plans grid, the initial value of the annual-vs-monthly toggle should be:
   - [x] The same as the billing period of the currently selected plan (if there is one in the launch store)
   - [x] Otherwise, fallback to annual

**Comment by razvanpapadopol** [comment]
@ollierozdarz WDYT about this one?

Since we have the select plan already persisted, an interesting alternative would be to have the Plans Grid automatically show as default the correct billing period depending on the selected plan product. 

Then if the user just toggles between annually and monthly and doesn't make a selection we continue to show annual next time as default.

**Comment by ollierozdarz** [comment]
@ciampo @razvanpapadopol yeah, this makes a lot of sense to me. I think it makes a users experience more personalized (remembering their plan and billing period), makes us look like we remembered (like all of these pages are connected), and feels like the right decision to make!

**Comment by razvanpapadopol** [comment]
Thanks for your confirmation, @ollierozdarz! 🙌🏼
Here are 3 short demos with how this feature work across the flows: https://github.com/Automattic/wp-calypso/pull/49518#pullrequestreview-580120046

**Comment by razvanpapadopol** [comment]
Fixed in #49518
