### ISSUE TITLE
Email receipt : Showing domain which is no longer mapped

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#49477]
### Steps to reproduce the behavior

User received an email receipt of a recent purchase which also showed a domain name which had not been mapped on their site for 5 years:

From the users WordPress.com dashboard the old mapped domain name is not visible, nor does it appear on the receipt in under purchases from their dashboard, it only appeared in the email that was sent out.

Email Logstash: 

#### What I expected to happen

- Expected to only see Personal plan and current mapped domain name on email receipt

#### What actually happened

- Domain mapping for a domain that had been mapped to the site 5 years ago showed, as well as, current Personal plan and correct domain mapping 

#### Screenshot

- Screenshot:

Related ticket: #3689562-zen

**Comment by michaeldcain** [comment]
@rachelwinspear: I've updated this issue to remove internal links and/or images. See: PCYsg-68j-p2

**Comment by michaeldcain** [comment]
Added this to the Payments backlog in: c/v5SbyTBS-tr

If it turns our to be a backend issue (I think it is), we'll close this.

**Comment by DavidRothstein** [comment]
Closing this, since it's being tracked internally per above.

It seems to be a rare issue related to some incorrect billing records, but since the billing records in question aren't actually used directly for anything billing-related, we might not fix this anytime soon (unless it starts affecting a lot more people) since it's just a small mistake on the receipt.
