### ISSUE TITLE
Domains: Transferred-in domains show no indication of name server changes required

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#49548]
Domains: Transferred-in domains show no indication of name server changes required

When a user transfers in a domain, it will keep the name server settings it had prior to starting the transfer.

This is good in many cases.  However, users can set the domain as primary and there is no notice that they need to toggle on our name servers if they want to use it with their WPCOM site.  

The user then has a site with a broken domain until they finally notice and find how to fix it. A specific user went 22 days with a broken primary domain and was mostly waiting on it to fix itself.

For transferred-in domains, users may intentionally leave a domain's name servers pointed elsewhere.

Additionally, the user may point the domain to a service like CloudFlare and then back to WPCOM via A records. 

However, we still need a notice letting them know a name server, or DNS, adjustment is necessary if they want the domain to point to their WPCOM site

For mapped domains, we display a notice.

![Screen Shot on 2021-02-01 at 10:13:54](https://user-images.githubusercontent.com/4887830/106477595-50d53280-6476-11eb-9cec-318f95106f69.png)

### Steps to reproduce the behavior

1. Transfer in a domain name without first updating name servers to WPCOM's (or set a normally registered domain's name servers elsewhere)
2. Set domain as primary.
3. Review that there is no notice regarding name servers or that the domain is pointed elsewhere.

#### What I expected to happen

For a notice to appear letting the user know that there's still some configuration necessary before the domain is pointed to the WPCOM site.

An extra notice alerting the user prior to setting a misconfigured domain as primary. 

#### What actually happened

No notice.  Primary domain not pointed to WPCOM site.

![Screen Shot on 2021-02-01 at 10:19:07](https://user-images.githubusercontent.com/4887830/106478222-fbe5ec00-6476-11eb-83e5-ca5d8fc781c3.png)

### Context

Encountered multiple times in chat. 

#### Does this happen on simple or atomic sites or both?
Both.  Also occurred in new nav unification interface and past iterations of Calypso.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Impacts any site that transfers-in domain that isn't pointed to our name servers.

**Comment by cathymcbride** [comment]
Fyi: @daledupreez

**Comment by JoshuaGoode** [comment]
New encounter on 24929238-hc

**Comment by JoshuaGoode** [comment]
Encountered on 27267306-hc

**Comment by klimeryk** [comment]
This is a good point, but this applies to all domains in general. For transfers-in we:

 - Send an email reminder that they could/should update the nameservers if they want use the domain with a WPCOM site.
 - We _do_ show a reminder to the user to update the nameservers for three days since the transfer-in has completed: https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/my-sites/domains/components/domain-warnings/index.jsx#L445 Like you mentioned, some users have valid cases not to use our nameservers.

I'll close this issue, but there's an ongoing internal discussion on how to handle setting primary domains that we know will not work as expected here: p2MSmN-8g3-p2 🙇‍♂️ I'll be sure to reference this issue there - thanks for reporting the cases!
