### ISSUE TITLE
Can't change global style fonts on unlaunched site

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#49578]
### Steps to reproduce the behavior

1. Create a new site
2. Do not launch the site
3. Try changing fonts of site from Global Styles menu in page editor
4. Changes aren't saved, and revert whenever you view a preview of the page

#### What I expected to happen

Fonts on site will change

#### What actually happened

Fonts do not change.

### Context

27437705-hc

#### Does this happen on simple or atomic sites or both?

Confirmed on Simple so far

#### Workaround

Launching the site then makes the changes saveable.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I attempted to reproduce this issue but was unsuccessful. Please see the video below.


https://user-images.githubusercontent.com/6549265/135937061-8c61e673-e644-48ab-a9d2-ef45ea1ed48d.mov

OS: macOS Big Sur 11.6
Browser: Firefox Nightly 94.0a1.

As I was not able to reproduce this issue, this issue is being closed with the label `Closed - Not Reproducible`.
If this issue should remain open, please feel free to re-open this bug.
