### ISSUE TITLE
New Onboarding Launch: missing translations

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49589]
### Steps to reproduce the behavior

1. Create a site starting from `/new`
2. Click on Launch button on editor top bar while having a non-EN language set in your account
3. Advance through the flow

#### What I expected to happen
All strings to be translated

#### What actually happened
Multiple strings on _Select a plan_ step are in English

### Context
This issue might be related to #49169

#### Screenshot
<img width="1550" alt="Screenshot 2021-02-02 at 10 22 29" src="https://user-images.githubusercontent.com/14192054/106573575-7cbdea00-6542-11eb-9cd5-37a26fd06e09.png">

**Comment by lsl** [comment]
I think this is because we're loading translations from wordpress.org for ETK plugin (even on simple sites?)

wporg translations missing https://translate.wordpress.org/projects/wp-plugins/full-site-editing/stable/ko/default/

wpcom translations available https://translate.wordpress.com/deliverables/ko/5048137/

I'm not across the process that transfers these but maybe we need to speed that up? @Automattic/i18n

**Comment by razvanpapadopol** [comment]
Probably fixed in https://github.com/Automattic/wp-calypso/pull/49812
