### ISSUE TITLE
Signup: add Fredricson starter design

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#49617]
We've created a new Starter Design site that can be added to the Design Screen in signup.

https://fredricksonstarter.wordpress.com/

![image](https://user-images.githubusercontent.com/545779/106639151-497f5900-654a-11eb-95a2-05e86c246ff3.png)

**Note:** we'll also be adding the default content on this home-page to our Patterns Library on WP.com.

cc @Automattic/dotcom-view-design @simison 

### Recipe

The starter design "recipe" for this site looks like the following.

- [Blank Canvas theme](https://wordpress.com/theme/blank-canvas). cc @kjellr 
- Static homepage with default content.
- A default font pairing of Cabin / Cabin.
- A custom colour scheme set in the customizer.

If the output of the created site does not match the screenshot above it will be related to one of those parts of the "recipe".

**Comment by kjellr** [comment]
@ianstewart just a heads up that a bunch of additional "Link in Bio" patterns are landing soon in Blank Canvas that might be useful here: 

Issue: https://github.com/Automattic/themes/issues/3161
PR: https://github.com/Automattic/themes/pull/3151

**Comment by p-jackson** [comment]
Was just testing this and I found it a bit jarring that after I'd entered my own site title during onboarding, but when my site was created and I landed in the editor the big heading at the top of the page is still "Alex Fredrickson". Feels like why ask me the name of my site if you aren't going to make it the site "title" (the `<title>` has been set of course, I just imagine a user will think of the "Alex Fredrickson" heading as the site's title).

I see why it's doing this of course, and it's not technically any different from what we're doing with Balasana or Vesta
![Screen Shot on 2021-02-11 at 20:28:32](https://user-images.githubusercontent.com/1500769/107610991-d2fbfd00-6ca7-11eb-9bd1-f775b6bc20b1.png)
![Screen Shot on 2021-02-11 at 20:29:01](https://user-images.githubusercontent.com/1500769/107611033-ed35db00-6ca7-11eb-9129-451d7be07190.png)

But I think they get away with it a bit more because the title's in the middle of some copy that's clearly placeholder.

Not a blocker, but what do you think about doing something more like Balan or Pollard that seem to get away without actually using the person's name.

---

Also a wee a11y thing, the "Alex Fredrickson" at the top is a `<p>` not an `<h1>`

**Comment by simison** [comment]
I'm not entirely sure we should replace these in content via API — the best would be using Site title block instead, and I'm assuming at least when we have FSE, all templates will use that. @ianstewart would it be possible already now?

**Comment by simison** [comment]
> would it be possible already now?

To answer myself: no, the title block isn't available in block editor.

That said... it could be pretty useful for single site templates so perhaps it _should_ be available?

**Comment by ramonjd** [comment]
> Not a blocker, but what do you think about doing something more like Balan or Pollard that seem to get away without actually using the person's name.

We're ready to ship the new design to Gutenboarding unless @ianstewart or anyone else has any strong feelings about the use of the first name Alex. It's something we can remove at any time. Or change it to Reginald or something

**Comment by p-jackson** [comment]
Personally I think it's fine to ship it and potentially change it later

**Comment by p-jackson** [comment]
#49970 has deployed
