### ISSUE TITLE
[Domains] Unable to navigate to DNS page for a parked domain

### ISSUE THREAD

**Issue by nbloomf** [Automattic/wp-calypso#49613]
### Steps to reproduce the behavior

I ran into this today on one of my own domains. I'm not sure if this is expected or not, but I was only able to self-serve because I know calypso's URL structure.

0. My goal: add a custom DNS TXT record to a parked domain with nameservers pointing to another service.
1. Go to `\view\$domain` and click "Manage Domain"
2. Click on "Change your nameservers and DNS records"

#### What I expected to happen

To be able to add a custom DNS record, or at least see a link directing me to the place to do so.

#### What actually happened

My only options on this page are to add or delete custom nameservers or turn off custom nameservers; nothing about DNS records.

I was eventually able to self-serve by manually navigating to `https://wordpress.com/domains/manage/$domain/dns/$domain`, but I don't see links to this page in calypso in any obvious place.

### Context

This was in response to a time sensitive request from facebook to add a custom TXT record verifying that I own the domain. If I didn't know how to work around calypso's navigation issues I would be looking for another domain host. :(

**Comment by klimeryk** [comment]
Thanks for reporting, @nbloomf 🙇 This is "expected" - if the nameservers are not pointing to us, allowing the users to change DNS records could make them think that this will actually change the active DNS records. But since the domain is pointing to different nameservers, those changes will not matter.

> This was in response to a time sensitive request from facebook to add a custom TXT record verifying that I own the domain. If I didn't know how to work around calypso's navigation issues I would be looking for another domain host. :(

Not sure I understand the case here - if the nameservers were not pointing to us, why would you need to add this record on WordPress.com?

Technically, there is a use case where you'd want to do that - prepare a domain before switching nameservers (like, when using external hosting or email provider). But in most cases, if the user switches to our nameservers, they want to use our IP records (which are set up automatically).

We'd have to redesign that whole section (which is definitely a good idea) to ensure this change would not cause more trouble than benefit - unfortunately, that's not on our roadmap :( So I'll close this as wontfix.
