### ISSUE TITLE
New onboarding: pad size doesn't differ from desktop size

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49665]
At `/new` flow, when looking at preview, size between desktop/pad doesn't have any difference. This is especially the case on Macbook 13" screen, but difference isn't big in bigger screens either

<img width="1434" alt="Screenshot 2021-02-03 at 17 52 06" src="https://user-images.githubusercontent.com/87168/106772488-baa53600-6648-11eb-88f6-c4871aebf9d3.png">
<img width="1434" alt="Screenshot 2021-02-03 at 17 52 00" src="https://user-images.githubusercontent.com/87168/106772505-bf69ea00-6648-11eb-9ffb-50742902b0ae.png">

Solution could be to scale it little bit smaller (e.g. 768px).

On smaller screensize, the pad size wouldn't be useful even if we would scale it smaller:

![image](https://user-images.githubusercontent.com/87168/106772729-f9d38700-6648-11eb-9378-58408d8cf453.png)

@ollierozdarz thoughts on this?
- We could remove the whole pad breakpoint
- We could make it smaller
- We could hide it when screen is small enough

**Comment by ollierozdarz** [comment]
@simison great pickup! I think it'd be a shame to hide it since it may be valuable for some users. 

> We could make it smaller

This sounds like the most practical to me. I just had a look at Squarespace for an example, and the difference between their Desktop and Tablet views are quite noticeable. Even at our biggest viewport size if we can adjust Desktop and Tablet to have a 10%-20% size difference, then continue it as the viewport scales down, that'll be a win! 🙂
