### ISSUE TITLE
My home: swap "create a site menu" and "update your home page" order

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49706]
When creating a  new site, we show a checklist of next tasks at customer home:

<img width="1072" alt="Screenshot 2021-02-04 at 11 13 21" src="https://user-images.githubusercontent.com/87168/106870702-153aa280-66da-11eb-9b8a-4d0b63dc12ab.png">

See https://github.com/Automattic/wp-calypso/issues/47334 for context, but in gist is that editing menus is currently hard in Customizer, and should be introduced later on in the site building process.

Customers should feel more success and be more attached to process if they edit their homepage first instead.

While removing the menu task item needs a bit more design thought (https://github.com/Automattic/wp-calypso/issues/47334), just swapping the menu item order is less risky and trivial:

Before
- Name your site
- **Create a site menu**
- **Update your homepage**
- Launch your site

After:
- Name your site
- **Update your homepage**
- **Create a site menu**
- Launch your site

Thoughts @olaolusoga @ianstewart @ollierozdarz ?

**Comment by ollierozdarz** [comment]
@simison +1 from me. Let's get some quicker psychological wins on the board with a user before introducing harder tasks which could result in churn.

**Comment by olaolusoga** [comment]
What Ollie said. I'd also plus one[ Rick's comment](https://github.com/Automattic/wp-calypso/issues/47334) on removing the edit menu task all together. Editing menus is not great at the moment—we're making it better with Gutenberg—if we have to continue with customizer I wonder if there is a better moment in the user journey to expose menu management. 

Also the [quick links has "edit menu"](https://d.pr/i/90VkOX), which I think is a better placement, since the person is intentionally selecting to edit menus, and is ready for menu management—this is different from the customer home tasks since those are meant to be "quick wins" and a way to onboard folks.

**Comment by joanrho** [comment]
+1 swapping the order and also removing it as a task from the Customer Home checklist, unless users have more than one page (they wouldn't need a menu for a single page site, but they might need one if they have at least two published pages).

**Comment by simison** [comment]
@autumnfjeld since this is closely related to editor guidance, I added this to Ganon UX issues backlog.

**Comment by roo2** [comment]
created a diff to change it on the api side D58253-code

**Comment by roo2** [comment]
order is now changed 👍
