### ISSUE TITLE
New Page Layout Picker: reorder the list of page layout categories

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#49863]
The page layout picker is being re-designed: p9Jlb4-27F-p2
The order in which the categories appear is being changed in accordance with layout usage data.

The new order will eventually be:
- Blank
- Featured
- About
- Blog
- Home (renamed from Home Page #49861)
- Gallery
- Services (includes the four layouts from deleted "Restaurant" category #49862)
- Contact

For this issue, just reorder the categories that currently exist in production; the new/changed categories will all slot into place as those things are implemented.

**Comment by autumnfjeld** [comment]
FYI: 120-gh-Automattic/view-design#issuecomment-775764995 in case that impacts work being done with this category re-order (or any other part of Page Layout Picker project)

**Comment by roo2** [comment]
There are two parts to this, the first is the PR https://github.com/Automattic/wp-calypso/pull/50110 to apply the order to categories. The second is to combine restaurants category into services.

When we do this we will need to update the support document here docs https://wordpress.com/support/build-a-website-for-your-restaurant/#page-layouts

think we should only combine the restaurant category into services towards the end of the project just so that we don't have toupdate the docs twice

**Comment by p-jackson** [comment]
Hmmm, that page has a reference to the "Change Layout" button too. I bet we're going to need to make a bunch of updates to a number of pages actually.

**Comment by p-jackson** [comment]
> There are two parts to this, the first is the PR #50110 to apply the order to categories. The second is to combine restaurants category into services.

@roo2 I think we can close this issue once #50110 merges because the task to combine restaurants and services is tracked by #49862
