### ISSUE TITLE
Nav Unification: Announcement Modal has untranslated next/previous/finish buttons

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#49981]
In the tour the content is translated but not the buttons [although the translation exists](https://translate.wordpress.com/projects/wpcom/-all-translated/3943/):

<img width="696" alt="Screenshot 2021-02-11 at 09 14 19" src="https://user-images.githubusercontent.com/203408/107614079-e6787b00-6c49-11eb-854d-23d341bcf767.png">

<img width="690" alt="Screenshot 2021-02-11 at 09 14 15" src="https://user-images.githubusercontent.com/203408/107614083-e8423e80-6c49-11eb-9663-378d3b1089ab.png">

**Comment by tjcafferkey** [comment]
@akirk thanks for raising this issue, much appreciated.

I think this is down to us using a Gutenberg component within Calypso where the Gutenberg translations are not loaded.

I may have got this wrong, but did you solve a similar issue in WP Admin recently? If so any advice/help tackling this would be appreciated.

Thank you! 😄

**Comment by akirk** [comment]
The reason used to be that the component needs to be wrapped with `localize()` but I am not sure if this is still true. Maybe @yuliyan can chime in? Thanks!

**Comment by yuliyan** [comment]
The root of the problem comes from our string extraction process. For various reasons, we don't extract strings from external packages, and in this case the navigation buttons' strings are coming from [`@wordpress/components` package](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/guide/index.js).

I've created a PR #50184 with a quick workaround. Once we get it deployed and trigger i18n deploy, translations appear would normally.

**Comment by tjcafferkey** [comment]
Thanks so much for the explanation and the PR. This makes much more sense as to why it wasn't working. It's massively appreciated.

I'm going to review the PR and hopefully get that merged in.

**Comment by yuliyan** [comment]
Control buttons are now being translated -
![CleanShot 2021-02-18 at 16 06 52](https://user-images.githubusercontent.com/2722412/108368770-7fd3fe00-7203-11eb-9817-735d12b01a78.gif)
