### ISSUE TITLE
Horizon Site Editor: Enable theme switching for sites created in this flow.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#50053]
As part of testing the site editor on Horizon we will (at some point) want to enable theme switching …

- between Block themes
- and from Block theme to Classic theme (and back again).

In order to do this we'll want to enable these themes for sites created in this flow. And sites created in this flow only. These themes are not yet ready to appear on simple sites for all users. :)

Here's what I think that looks like:

- We need a mechanism for conditionally displaying a subset of themes from /pub and /premium for sites created in this flow and only in this flow.
- But this mechanism should not be horizon-specific because at some point we may want to enable this flow for a slice of traffic for regular wpcom — including atomic.
- And once we have the mechanism, then we make those themes show up on Horizon for testing.
- And make switching themes a task in testing with HEs. (And later real users.)

**Comment by ianstewart** [comment]
> We need a mechanism for conditionally displaying a subset of themes from /pub and /premium for sites created in this flow and only in this flow.

In developing this mechanism it may be worth exploring how we'd roll this out to signup variations as well.

**Comment by vindl** [comment]
> - We need a mechanism for conditionally displaying a subset of themes from /pub and /premium for sites created in this flow and only in this flow.
> - But this mechanism should not be horizon-specific because at some point we may want to enable this flow for a slice of traffic for regular wpcom — including atomic.

I think we can base this on existing `core-site-editor-enabled` sticker that still applied to all of the sites created to FSE test flow. Previously this was controlling FSE experiment activation, but now that's not needed since it's automatically done when supporting theme is detected. We still left it around to cover purposes like this one. 

@ianstewart any opinions on the following:

- How should these themes be differentiated in the showcase? (do we surface them as first suggestions, add some visual clues like ribbons, hide legacy themes behind show more button etc.)
- How should switching from FSE to legacy theme (and vice versa) ideally look like? Should we display some prompt informing the user about the change in the experience, and linking to TBD support docs?

**Comment by simison** [comment]
Would it be useful to just list _only_ FSE themes there for starters in the experiment, and the rest maybe behind some toggle? I don't mind if this is pretty ugly for starters just to get testing it, but this flow also really needs design effort to figure out.

**Comment by vindl** [comment]
> Would it be useful to just list only FSE themes there for starters in the experiment, and the rest maybe behind some toggle?

I think that would work just fine to get the testing rolling.

**Comment by ianstewart** [comment]
> How should these themes be differentiated in the showcase? (do we surface them as first suggestions, add some visual clues like ribbons, hide legacy themes behind show more button etc.)

**Pre-Launch MVP:** Merely listing them in the list of themes behind the appropriate flag/sticker/mechanism would be a big win as they don't show up yet at all on Horizon. :)

**Internal and External Testing:** My expectation is that at the very least Block Themes would replace our recommended themes when Block Themes are available. I don't think it's a blocker for internal testing. It may be a blocker for initial usability testing. We may want to add some sort of explanation about _why_ one would want to use a recommended theme.

**Comment by ianstewart** [comment]
> How should switching from FSE to legacy theme (and vice versa) ideally look like? Should we display some prompt informing the user about the change in the experience, and linking to TBD support docs?

Less sure about this one. I think it's a core Gutenberg issue that we should likely contribute to or follow. I think it's a separate issue. 

That said, I don't think we should _warn_ people about switching.

- Nothing should break and no content should be lost.
- Many themes already have idiosyncratic functionality that is turned off and on during theme switch and in general pattern this would be no different.

Future things to look at pursuing in separate issue …

- We could perhaps use a notification to let people know that the Customizer / Site Editor has been turned off / on for both directions.
-  We could keep the Site Editor on independent of Block Theme activation and use it as an opportunity to promote or note the Block Theme requirement.

**Comment by vindl** [comment]
> Less sure about this one. I think it's a core Gutenberg issue that we should likely contribute to or follow. I think it's a separate issue.

Yeah that's a good point, it should be dealt with and discussed separately, preferably in core.

So the main thing from a technical side here is to figure out if it's possible to conditionally (per user or site basis) show themes in the showcase that are network disabled.

**Comment by ianstewart** [comment]
@kathrynwp would you be able to take a look at some of the notes and UX issues above from a Design Selection Pod point of view?

**Comment by kathrynwp** [comment]
@ianstewart Would it be possible to look at some of the feedback received from the earlier test where we put some users into a FSE flow? Looking at things that went well and not as well from that test could help inform how we go about things this time around.

**Comment by ianstewart** [comment]
This one’s a bit different as the previous thing didn’t turn off the customizer and turn on new sidebar menu items. @vindl do you recall us throwing any warnings when people switched away from themes? I don't recall it being tested in any of the usability testing.

**Comment by kathrynwp** [comment]
> would you be able to take a look at some of the notes and UX issues above from a Design Selection Pod point of view?

> How should these themes be differentiated in the showcase? (do we surface them as first suggestions, add some visual clues like ribbons, hide legacy themes behind show more button etc.)

Until we have a decent number of themes fully supporting FSE, I would lean toward adding a ribbon or other type of highlight – rather than hiding other themes behind some type of toggle. This would shine a positive spotlight on themes that let folks take full advantage of the FSE functionality ("bonus!"), rather than reflecting a lack (i.e. a dearth of themes missing the feature).

> How should switching from FSE to legacy theme (and vice versa) ideally look like? Should we display some prompt informing the user about the change in the experience, and linking to TBD support docs?

I think we would need some kind of alert letting users know that their experience is going to change, otherwise they may have no idea where to find and edit their site logo, site title, menus, and other elements. One approach could link to support docs; another idea might be to have a little modal window showing people a visual of where to find these items in the alternate editing experience, along with a link to further guidance.
