### ISSUE TITLE
Plans: update prices to add USD identifier to non-US geos

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#50064]
We already include non-USD identifiers for supported currencies that use the $ as a currency symbol (i.e. "C$" for Canadian dollars), but we don't include a USD identifier when a user is in a location that uses the $ and we don't currently support their currency (i.e. Argentinian Pesos). When a user is outside of the US, we should add an indicator to the amount (i.e. "US$"). 

In #46205 and D52530-code, we added this logic to pricing display values returned from different endpoints and fixed this issue where those values are used (i.e. Checkout, parts of the subscription settings, billing history, receipts, etc. - see: #44673, #49005), but some places in Calypso (i.e. Plans, subscriptions settings) build their own display prices and don't use the value from the endpoint. This has the added side effect bug of not using properly localized currency formats (i.e. amount on left, currency symbol on right) that are also returned with the display value.

The best fix is summarized in the second half of [this comment](79-gh-Automattic/payments-shilling#issuecomment-752669323): 

> Then, to address the incorrect formatting elsewhere on this page (in the large price) and in Calypso:
> 
> - Add a value to the /purchases/ endpoint that returns the localized store price without the <abbr /> HTML stripped (display_store_price())
> - Switch out the instances where we create a symbol/amount pair on the front-end with this value and style appropriately

**Comment by jjchrisdiehl** [comment]
This is still a work in progress, so far the API has been updated to pass along the display price. Next step: update frontend to use new API values.

**Comment by jjchrisdiehl** [comment]
Circling back to this, this issue is a bit sticky.

I've identified three areas that handle the price creation separately, all three pass in the price and currency and then construct the layout within React.

[Purchases section](https://github.com/Automattic/wp-calypso/blob/f94ff293bdff7327ca791e20f276828fb8756899/client/my-sites/plan-price/index.jsx#L98-L99) `<PlanPrice>`

![image](https://user-images.githubusercontent.com/16580129/165648722-de5a8c86-643d-4587-8c54-b992cb724553.png)

[Email Upgrades](https://github.com/Automattic/wp-calypso/blob/f94ff293bdff7327ca791e20f276828fb8756899/client/my-sites/email/email-providers-comparison/price-with-interval/index.tsx#L90) `<PriceWithInterval>`

**Professional Email**
<img width="746" alt="image" src="https://user-images.githubusercontent.com/16580129/165648813-83ab0dc2-ce28-44a6-b911-46bd4052e655.png">

**Google Workspace**
![image](https://user-images.githubusercontent.com/16580129/165648880-028cc7c5-4c96-4ce3-896e-2cfb08abe029.png)



[Plans page pro-rating discount](https://github.com/Automattic/wp-calypso/blob/f94ff293bdff7327ca791e20f276828fb8756899/client/my-sites/plan-features/index.jsx#L248) `<Notice>`

![image](https://user-images.githubusercontent.com/16580129/165648564-40485ddd-0175-4f60-9809-3aa882d92f96.png)

The strategy to replace these values with the formatted values provided from the backend seems to be the best way to go forward, as the server geo-ids the customer and left/right aligns the currency and pricing. 

The issue here is that depending on the location of the price in Calypso, the wrapper HTML provides different classes for the currency symbols and the price itself. It may make sense to just standardize the output.

In some cases, such as is the case with the `purchase management` screen, we [provide price ranges](https://github.com/Automattic/wp-calypso/pull/36651) for Jetpack plans, so we would need to keep that in mind when implementing the new pricing.

The original idea as mentioned by @michaeldcain above, 

> Add a value to the /purchases/ endpoint that returns the localized store price without the HTML stripped (display_store_price())
Switch out the instances where we create a symbol/amount pair on the front-end with this value and style appropriately

Has the caveat that if we passed an HTML string to React then we would need to [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) which may be suboptimal. 

As per @sirbrillig recommendation, we could perhaps pass the currency, pricing, and format to the front end and construct the HTML in React, though I suppose that duplicates the work done on the backend.

Another option is we always default to the store price format and style it the same way across Calypso, though this is less flexible depending on a component's needs.

Any thoughts?

**Comment by michaeldcain** [comment]
> Another option is we always default to the store price format and style it the same way across Calypso, though this is less flexible depending on a component's needs.

@jjchrisdiehl @sirbrillig I think we should start with this, given that it will consolidate logic and address a confusing situation for some users, at the somewhat minor expense of removing the currency symbol and cents styling on the purchase management and legacy plans pages - both of which are older designs. It would also be great to audit the uses of the old endpoint return values to make sure we have them all covered, and possibly mark them as deprecated so that this bug doesn't get reintroduced.

If we deem that we need that additional styling in the future, then we can create a component that handles it on the front-end, or we can revisit my suggestion to return the HTML from the backend.

**Comment by sirbrillig** [comment]
I apologize for adding more confusion to this plan. I don't love using `dangerouslySetInnerHTML`, but in this case it's probably pretty safe and I think it will unblock this project. We can always change it later. 

In addition, I think it's best to limit the scope of this to just the plans page pricing to start with. The plans page is not an easy thing to modify and it's arguably one of the most important pages in calypso. If we can do that in such a way that the price is embedded in a component that's easy to share to the other locations which display prices, even better, but I don't think that should be made a requirement. A specialized component could be made later to deduplicate the code once we have it working.

**Comment by jjchrisdiehl** [comment]
@sirbrillig I've opened a PR for the beginning of a fix to the pricing found on My Plans > Manage Plans. Should we include this in the scope of this fix? Perhaps we look at the following:

- Plans section (legacy and new plans?)
- Manage Plans

**Comment by sirbrillig** [comment]
That sounds fine to me. Whatever feels good to you as you are working on it. If it feels like something is taking too much work, maybe reconsider it.

**Comment by jjchrisdiehl** [comment]
### Updated roadmap

After some experimentation, the current idea to resolve this issue will require updating the `<PlanPrice />` component to take a `productDisplayPrice` prop returned from the backend as described by Cain in the original post. Once this is done, we can then update `<PlanPrice />` components across Calypso to take in this new value and conditionally display it.

Update the endpoints and PlanPrice component:
- [x] Update endpoints, add `productDisplayPrice` value that returns a geo-IDed formatted price (purchases, plans) D80584-code 🚢 
- [x] Update `<PlanPrice />` component to accept the `productDisplayPrice` prop and conditionally render it https://github.com/Automattic/wp-calypso/pull/63524

Update instances of PlanPrice to accept the new backend values:
- [x] Manage Plans https://github.com/Automattic/wp-calypso/pull/63254
- [x] Plans (Legacy) https://github.com/Automattic/wp-calypso/pull/63783
- ~~[ ] Plans (New)~~
- ~~[ ] Pro-rated credit notification~~
- ~~[ ] Get started flow~~

If time permits:
- [x] Update store price formats D81534-code

**Comment by jjchrisdiehl** [comment]
Update: The base component and endpoint updates are finished and pending a review. As for the four sections I intend to update, Manage Plans is finished and I am working on Plans (Legacy) now. Likely have this all done by the end of the week.

**Comment by jjchrisdiehl** [comment]
Update: So far, the two 'base' changes have been deployed: i.e values have been added to the /purchases and /plans endpoints and the PlanPrice component has been updated to account for a productDisplayPrice prop. 

Additionally, 

- the [Manage Plans pricing](https://github.com/Automattic/wp-calypso/pull/63254) has been updated
- the [Plans page pricing](https://github.com/Automattic/wp-calypso/issues/50064#:~:text=conditionally%20render%20it-,Update%20PlanPrice%20to%20use%20productDisplayPrice%20prop%C2%A0%2363524,-Update%20instances%20of) was updated, but [due to a bug](p1654278982740649-slack-C02FMH4G8), this change has been [reverted](https://github.com/Automattic/wp-calypso/pull/64341).

It seems the bug here involves the Plans page's `term` prop being discarded/not utilized. Since the /plans endpoint only returns an annual value, it is used instead of the monthly format for the plan (granted, 12 months at the monthly rate is more expensive then the returned annual plan value, so this is wrong doubly so).

Possible solution, return monthly pricing values via the plans endpoint and use these values when a monthly format is requested.

**Comment by michaeldcain** [comment]
> Possibly solution, return monthly pricing values via the plans endpoint and use these values when a monthly format is requested.

I think that's a good solution.

**Comment by jjchrisdiehl** [comment]
Update:

I wanted to answer the question "have we resolved the original issue". Let's take a look.

_**The issue**_

> some places in Calypso (i.e. Plans, subscriptions settings) build their own display prices and don't use the value from the endpoint

So far, we have identified five areas that do not use the endpoint outlined by @michaeldcain in the original statement at the top of this page. They are:
- Plans (legacy)
- Plans (new)
- Subscription settings (Manage Plans section)
- Notifications (pro-rated credits etc)
- Get started flow

In order to resolve this, we have updated the PlanPrice component and the plans/purchases APIs to provide a productDisplayPrice prop which utilizes the backend geo-ID functions. We have also passed this new prop value on the Manage Plans section.

At this point, we've implemented these changes once as a proof of concept, but more work would need to be done to implement them elsewhere. We also learned that there are billing term requirements that we'll need to also pass along as a separate prop to account for monthly/annual/biennial pricing, so this would delay the implementation on some pages.

That being said, I think we're at a good stopping point for now and can lower the priority on this task. It could be useful to surface these new props to teams who are working on adding new pricing interfaces in the future.

**Comment by sirbrillig** [comment]
This should be fixed by relying on locale-aware client-side price formatting (https://github.com/Automattic/wp-calypso/pull/71387). https://github.com/Automattic/wp-calypso/pull/71722 changes checkout to do this, and the plans page already does this. An example of using Canadian French with USD:

<img width="276" alt="Screenshot 2023-01-13 at 2 34 10 PM" src="https://user-images.githubusercontent.com/2036909/212403817-ee5ac317-c867-415f-ac46-83139c60a49b.png">

That primarily leaves the purchases pages which should be fixed by https://github.com/Automattic/wp-calypso/pull/71952.

<img width="539" alt="Screenshot 2023-01-13 at 2 35 33 PM" src="https://user-images.githubusercontent.com/2036909/212404561-570e035f-f77a-4839-a29d-555a85334db2.png">
