### ISSUE TITLE
Social Icons Block: Incorrect rendering of icon color and icon background color

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#50171]
The social icon's color that is set in the editor is not rendering on the live page as expected in Simple sites. It also shows an incorrect warning that color combination is hard to read.

### Steps to reproduce the behavior

1. On a simple site, create a new page and add social icons block.
2. Add a few social icons.
3. Change their icon color and icon background color
4. Preview it or check the live page. You will notice that the color settings are not reflected.

#### What I expected to happen

The colors that are set for the social icons in the editor should appear on the live page.

#### What actually happened

Instead, it shows a black icon with no background color. 

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
Happens only on the Simple site. Was not able to reproduce the issue on Atomic.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Yes

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![](https://cdn-std.droplr.net/files/acc_1121510/L7Yx0d)

How it is rendered:

![](https://cdn-std.droplr.net/files/acc_1121510/i4Qsns)

* User report: #27800807-hc

**Comment by alaczek** [comment]
I encountered the same issue, but _I think_ this might be theme-specific, so reported here: https://github.com/Automattic/themes/issues/3263

**Comment by vajrasar** [comment]
Hi @devNigel and @alaczek thanks for the reports.

I checked this on my simple site and I was not able to replicate the issue on either draft/preview or published post on the following themes (based on this and [#3263](https://github.com/Automattic/themes/issues/3263) report):

- Blank Canvas
- Seedlet
- Mayland
- Maywood
- Radcliffe 2
- and some others

I'm closing this issue since this cannot be replicated right now. However, please feel free to open this is you can replicate it on your end.
