### ISSUE TITLE
Nav Unification: WooCommerce submenu items are incorrect (in different ways) in both wp-admin and Calypso when the new WooCommerce Navigation experience is enabled

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#50249]
### Steps to reproduce the behavior

1. Go to an eCommerce site with WooCommerce 5.1 Beta 1 installed (see pbIJXs-Fz-p2 for detailed instructions)
2. Verify wp-admin menu
3. Verify Calypso menu

#### What I expected to happen

I expected the WooCommerce submenu items to be correct and the same in both wp-admin and Calypso.

#### wp-admin

<img width="550" alt="eCommerce Plan with WooCommerce 5 1 and New WooCommerce Navigation Enabled wp-admin" src="https://user-images.githubusercontent.com/2098816/108430312-2eca0700-720f-11eb-9f3e-d211d4cf844f.png">

- Note: the Mailchimp item at the top of the submenu

#### Calypso

<img width="439" alt="eCommerce Plan with WooCommerce 5 1 and New WooCommerce Navigation Enabled Calypso" src="https://user-images.githubusercontent.com/2098816/108430331-3689ab80-720f-11eb-96c7-f230849598a5.png">

- Note: It appears that the new WooCommerce Navigation experience submenu items are being appended to the existing WooCommerce submenu items.
- Note: The Products and Archives top level menus are also still present. Those should be gone when the new WooCommerce Navigation experience is enabled.

/cc @psealock @getdave

**Comment by psealock** [comment]
Thanks for writing this up @mattsherman. There are two issues at play here.

First: The wp-admin MailChimp problem noted. Automatically migrated items like MailChimp are moved over but not appropriately hidden from the flyout menu. That is a concern of wc-admin and I created an issue to track that in https://github.com/woocommerce/woocommerce-admin/issues/6377

Secondly: Extra items visible. WooCommerce make use of WP CSS class `hide-if-js` to avoid showing items that shouldn't be there, but not remove them completely so their routes remain available.

The `admin-menu` route does not return added CSS classes. We have been getting around this by adding classes in `admin_menu` hook instead of waiting for `admin_menu_classes` and that makes sense they aren't included in the response. One solution would be to also query `admin_menu_classes` hook as part of the the `admin-menu` route. Or maybe call it independently. The other part of the solution would be to include a similar CSS rule in Calypso.

**Comment by mmtr** [comment]
> Secondly: Extra items visible. WooCommerce make use of WP CSS class hide-if-js to avoid showing items that shouldn't be there, but not remove them completely so their routes remain available.

I wonder if we should update the `admin-menu` endpoint to exclude menu items with these classes, since the `hide-if-class` definitely shows a clear intent of hiding the menu item.

Alternatively, there are ways of registering a route without a menu, but they all feel _hacky_, since there isn't any simple WordPress function we can use just for that. We recently had to to something similar in Jetpack in order to have the `/wp-admin/options-general.php?page=sharing` route registered but without any menu registered: https://github.com/Automattic/jetpack/blob/d3e9d424c88050eb6471b1a30e3b5cdadd742a78/projects/plugins/jetpack/_inc/lib/class.jetpack-keyring-service-helper.php#L75-L77

**Comment by mmtr** [comment]
I opened https://github.com/Automattic/jetpack/pull/18898 for excluding the hidden items from the API response.

**Comment by psealock** [comment]
Nice solution @mmtr ! Thanks for the fix
