### ISSUE TITLE
TypeScript errors are not caught when building Editing Toolkit

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50334]
### Steps to reproduce the behavior

1. On your local machine, introduce a TypeScript error in the `apps/editing-toolkit` folder (for example: #50335)
2. Notice how the error is flagged in a IDE that supports TypeScript
3. Build the project (`yarn && yarn build` in one terminal tab) and ETK (`cd apps/editing-toolkit && yarn build` in another tab)
4. Notice how the build completes, and no TypeScript errors were logged
5. Commit the code and push to a new PR
6. Notice how the CI check pass successfully, and no TypeScript errors were logged

#### What I expected to happen

- The site build should not complete if there are TypeScript errors
- In the same way, CI tasks in a PR should fail if there are TypeScript errors

#### What actually happened

- The site build completed successfully
- CI tasks in a PR passed successfully

### Context

This scenario already happened a handful of times in the past weeks and caused a few bugs (since the team trusted TSC to flag errors in the code).

I opened a few PRs to exemplify this issue:
- #50335 introduced an error in `apps/editing-toolkit`. Both local build and CI check passed, despite the TypeScript errors.
- #50339 introduced an error in `packages/launch`.  Some of the CI checks failed because of the TypeScript errors
- #50340 introduced an error in `client/landing/gutenboarding`.  Some of the CI checks failed because of the TypeScript errors

Could be related to #49984

**Comment by ciampo** [comment]
cc'ing @Automattic/team-calypso-platform

**Comment by scinos** [comment]
I don't see any CI build or script to validate types in ETK (or in other /apps).

- In Calypso, we have the step "Run type checks" as part of the unit tests, but it only type-checks `packages/*` and `client/landing/gutenboarding` in Calypso.

- The build process of ETK uses webpack+babel to transpile TypeScript files. AFAIK it doesn't do any type checking.


Either we add another build step to the build `WPCom Plugins / Editor ToolKit` to check types, or we change Calypso's main "Run type checks" to also include ETK. I think I prefer the latter, because we could argue that TypeScript support (including type checking) is something provided by the platform, not something that every app/package has to worry about individually.

What do you think @noahtallen ?

**Comment by noahtallen** [comment]
That makes sense to me. Do you think it's at all possible that there could be tsconfig conflicts? (I see there is an ETK-specific one here: https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/tsconfig.json)

Or would that type check use the correct one automatically? 

I do think it makes sense to move them under the main check for types though.

**Comment by sarayourfriend** [comment]
Was this caused by when we stopped using TSC to compile typescript, instead opting to just run everything through babel with typescript support?

**Comment by ciampo** [comment]
> Was this caused by when we stopped using TSC to compile typescript, instead opting to just run everything through babel with typescript support?

Yes, I think it's potentially related to #49984

**Comment by scinos** [comment]
> Was this caused by when we stopped using TSC to compile typescript

I don't think so. What we did in #49984 is skip TSC compilation for _packages_, not for _apps_. AFAIK we never run TSC for apps.
