### ISSUE TITLE
Async Jobs: Purging Publicize connections fails with OOM error

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#50347]
It looks like grabbing blog_ids that have a certain blog sticker leads to an out-of-memory error in this job.
Let's see if we can come up with a way to identify these sites in a more granular way.

See paYE8P-KY-p2

WIP Fix: D60193-code

**Comment by obenland** [comment]
D15431-code contains some discussion around batching for get_blog_ids_with_sticker which was removed after some review feedback. Not sure if it’s related but might be worthwhile to check out.

**Comment by pablinos** [comment]
In reviewing what to work on next, I did a quick test of `get_blog_ids_with_sticker` using the `publicize-connections-to-purge` sticker from the job. It returned fine, but suspiciously with exactly 1000 IDs.

It might well be that the object cache is causing the problem here and that we should call `stop_the_insanity` and use the other recovery techniques to re-queue the job as we start hitting the top limit for memory usage.

I've also implemented something for refreshing the Instagram tokens where one job spawns worker jobs for batches. We could investigate doing something similar here if needs be.

**Comment by pablinos** [comment]
D60193-code has a fix for this, but as the problem comes from the job trying to process the best part of a million sites, I think we need to investigate if something else has gone wrong and connections have been incorrectly flagged for purge.

**Comment by pablinos** [comment]
r227501-wpcom
