### ISSUE TITLE
Nav Unification: plugins item does not link to plugins page

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50371]
### Steps to reproduce the behavior

Reproduces while on Spanish locale, but it may apply to all locales (needs triaging)

1. Go to customer home (`/home`)
2. Click on the "Plugins" nav item
3. Notice how the browser doesn't navigate to the plugins page

#### What I expected to happen

The browser should navigate to the plugins page

#### Environment

Business plan (Atomic) on Calypso

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/1083581/108842318-60f5b300-75d9-11eb-81af-47e428f9fc4d.mp4

**Comment by cpapazoglou** [comment]
It seems that navigation to any external url is impossible through Calypso in your site cause https://github.com/Automattic/wp-calypso/blob/2de5e432fc90d3793d8bac4f8aa3e7a7dfb5432c/client/state/sites/selectors/get-site-admin-url.js#L17 returned an `http` version for your site url. I am not sure how this is possible, it seems like `admin_url` option in your site doesn't have `https`.

I will fix our Regex here https://github.com/Automattic/wp-calypso/blob/3a1d304bd61e8ce1e3d181b0df77da62e108b94e/client/state/data-layer/wpcom/sites/admin-menu/index.js#L23 so that it doesn't depend on the protocol. 

Note to future self: The problem is locale irrelevant.

**Comment by cpapazoglou** [comment]
@ciampo It would be interesting to know whether your problem has anything to do with yoast p58i-a6S-p2.

**Comment by ciampo** [comment]
> @ciampo It would be interesting to know whether your problem has anything to do with yoast p58i-a6S-p2.

Seems like a similar problem, although the site where this issue was reported did not have Yoast installed?
