### ISSUE TITLE
Launch button not displayed in editor for unlaunched Atomic sites

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#50394]
### Steps to reproduce the behavior
1. Go to `/start` and create a business site
2. Install a plugin to make the site atomic
3. Go to editor

#### What I expected to happen
Launch button in editor top bar

#### Context
Mentioned as point 2 in p1614084077052300-slack-CBTN58FTJ

**Comment by ramonjd** [comment]
For consistent behaviour, I think we might need to ensure that the option is migrated over during AT. See comment: https://github.com/Automattic/wp-calypso/issues/46559#issuecomment-784946571

We could test this by deploying D57559-code

Not only that, it's likely we'll have to port the `a8c_enable_editor_site_launch` filter to wpcomsh so that we can still get the options when the editor isn't in the Calypso iframe.

See also the discussion over at p1614084077052300-slack-CBTN58FTJ

**Comment by ramonjd** [comment]
Now that we've [deployed D57559-code](https://github.com/Automattic/wp-calypso/issues/46559#issuecomment-785555754) we can look at how and if the `a8c_enable_editor_site_launch` filter is returning the correct launch values.

**Comment by yansern** [comment]
My understanding is that:

For **Simple sites**, the filter `a8c_enable_editor_site_launch` exists. It is located at `wp-content/mu-plugins/full-site-editing.php`.

For **Atomic sites**, the filter `a8c_enable_editor_site_launch` is missing. It should be placed in `wpcomsh/feature-plugins/full-site-editing.php`.

However, since both files run in different environments, as stated by @ramonjd in  p1614136102075500/1614084077.052300-slack-CBTN58FTJ, there are two challenges:
1. The library `WPCOM_Store_API` does not exist.
2. The library `ExPlat` does not exist.

**Tackling Issue 1: Missing `WPCOM_Store_API`**

Since Atomic (symlinked) can only be Business or eCommerce plan, it is safe to say that we won't be needing `WPCOM_Store_API` to verify what plan the user is on.

This library won't be needed.

**Tackling Issue 2: Missing `ExPlat`**

Here are two options we can pursue:
- The easy way: Ignore A/B test for Business & eCommerce, use Focused Launch for all Atomic sites.
- The harder way: Keep A/B test, create an endpoint on WPCOM to retrieve variation.

Explanation for the harder way: We can't use ExPlat's PHP lib because it doesn't exist on Atomic. We can't use ExPlat's JS lib because it is only for Calypso. So the only option I can think of is to create an API endpoint and have the launch button make an API request to WPCOM to retrieve the variation, then decide whether to redirect or show Focused Launch modal.

For now, I will create a PR for the easy way, which is to add the `a8c_enable_editor_site_launch` filter on `wpcomsh` that enables Focused Launch without A/B test for Business & eCommerce sites, then we can discuss whether to do to the extra API work for ExPlat.

**Comment by yansern** [comment]
Accidentally hit on the close button. ;)

**Comment by yansern** [comment]
An update. The decision is to use Redirect Launch on Atomic sites for now.
Context: 617-gh-Automattic/wpcomsh p1614264009076200/1614225156.060700-slack-C0KDTA48Y

**Comment by yansern** [comment]
I'm reopening this issue as `\Private_Site\is_launched()` seems to still return true when an Atomic site is launched.
The Launch button is now disabled again on Atomic sites.

**Comment by simison** [comment]
I'll close this due to launch button not being in editor at the time being.
