### ISSUE TITLE
Launch: skipping or selecting a domain is first reloading the page

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#50400]
### Steps to reproduce the behavior

Try launching a site which has already a purchased paid plan but no custom domain.

#### What I expected to happen
My site to launch or to get some upsell

#### What actually happened
During demo at p58i-a5v-p2 the user was redirected briefly to `/start/launch-site/domain-upsell` and then back so it seemed like a page reload.

### Context
`domain-upsell` seems to be part of the `launch-site` flow: https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/config/flows-pure.js#L318

#### Video
* I've managed to reproduce the exact issue after purchasing a monthly plan and then launching from Settings:
See demo: https://cloudup.com/cc9fjYZG5GG

* Then, the following is not an actual demo of the reloading bug but you can see better the brief redirect to `/domain-upsell` before launch.

https://user-images.githubusercontent.com/14192054/108903598-25cda100-7626-11eb-9b0c-d85b18227fb1.mov

**Comment by ramonjd** [comment]
I came across this today as well:

![Feb-24-2021 12-19-22](https://user-images.githubusercontent.com/6458278/108931997-b941b900-769c-11eb-92f9-89606e3196e6.gif)


Can confirm it happens on both the `start/launch-site` and `start/new-launch` (Gutenboarding-styled) flows and refreshes also when I select a paid domain upgrade option.

**Comment by aneeshd16** [comment]
Hi, thanks for reporting! I can reproduce this issue reliably too, I'll be debugging and fixing this.

Steps:
1. Create a new account with a free domain and a paid monthly plan.
2. Go to http://calypso.localhost:3000/start/launch-site?siteSlug={slug}
3. Click on Skip Purchase, the page should "refresh".

I cannot reproduce the issue after removing `domain-upsell` from the flow, so it is definitely caused by this step.
https://github.com/Automattic/wp-calypso/blob/d7d5076729e25ea21f11ecde2562b05f8ef6b060/client/signup/config/flows-pure.js#L319

I'll post an update here soon, sorry for the late response on this!
