### ISSUE TITLE
Signup: selected paid item is not added to cart during site creation if launch flow is open

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#50430]
### Steps to reproduce the behavior
1. Select an un-launched site start the launch flow from My home; it doesn't matter if you land on `/start/launch-site` or `/start/new-launch`.
2. Open a new tab and go to `/start` directly (or try creating a new site from [wordpress.com/pricing](https://wordpress.com/pricing))
3. Select a free domain.
4. Select a paid plan.

#### What I expected to happen
Selected plan to show up at Checkout for the newly created site so I can purchase it.

#### What actually happened
Checkout was displayed briefly in a loading state and then empty state of the checkout was displayed. The selected plan was not added to cart.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Demo with a monthly plan: https://cloudup.com/cHMd7LKm1IF
Demo with an annual plan: https://cloudup.com/cJvRU5BlNai
Demo with a non-EN locale: https://cloudup.com/c4NlmY19rtE

**Note**: the issue is not reproduced when trying to create a new site from Calypso but only when landing on `/start` directly or from an external page such as `/pricing`.

**Comment by ciampo** [comment]
Tested on production, it seems to be working fine for me


https://user-images.githubusercontent.com/1083581/109007047-fd888580-76ab-11eb-90c0-ae340baeaaa4.mp4

**Comment by simison** [comment]
@razvanpapadopol since no other reports, this might've been some data inconsistency locally causing it?

**Comment by razvanpapadopol** [comment]
It seems like I was reproducing this consistently when I was trying to test the launch flow for this other issue: https://github.com/Automattic/wp-calypso/issues/50273

I'm not sure if they are related or not but the only way to reproduce this so far is by having the launch flow opened in a separate tab while creating a new site.

cc: @ciampo to re-test using the updated description 🙏🏼 

**LE:** the error reported in #50431 is actually thrown only when `/start` site creation flow is working correctly (you don't have Launch flow opened in another tab). So the current issue is reproduced when there is no JS TypeError error logged in the console, pointing to #49680 (changes that introduced the JS TypeError) as a good place to start troubleshooting.

**Comment by ciampo** [comment]
> cc: @ciampo to re-test using the updated description

I was able to reproduce by following the updated instructions:


https://user-images.githubusercontent.com/1083581/109791959-4d6acd80-7c13-11eb-9746-b431818a5405.mp4

**Comment by jeyip** [comment]
Not the most familiar with calypso signup, but I'm going to start investigating this. 👍

**Comment by jeyip** [comment]
- After some spelunking, the "empty cart" page is rendered under a variety of circumstances (see [here](https://github.com/Automattic/wp-calypso/blob/776d0bc5c75f94192d6b67eeee06e51dbcfccbbf/client/my-sites/checkout/composite-checkout/composite-checkout.tsx#L596-L632)). 
- In our case, it turns out that the `@automattic/shopping-cart` library isn't loading the response cart with the selected plan properly (see [here](https://github.com/Automattic/wp-calypso/blob/776d0bc5c75f94192d6b67eeee06e51dbcfccbbf/client/my-sites/checkout/composite-checkout/composite-checkout.tsx#L736-L738)).
- I'm currently digging into the library source code ([here](https://github.com/Automattic/wp-calypso/blob/776d0bc5c75f94192d6b67eeee06e51dbcfccbbf/packages/shopping-cart/src/cart-functions.ts#L225-L238)) to figure out how the response cart is manipulated when we're visiting the checkout from an external source, like `/pricing`, vs from Calypso, like in `/site-launch`

**Comment by simison** [comment]
> [...] the only way to reproduce this so far is by having the launch flow opened in a separate tab while creating a new site.

This sounds like the impact is very limited and we can lower the priority. Lemme know if anyone objects though!

**Comment by jeyip** [comment]
This turned out to be trickier than I thought, and I ended up learning a ton about the calypso signup flows. After lots of digging, here's what I found:

- At first, shopping cart logic or localStorage seemed like the probable cause of our problems. That turned out not to be the case.
- The issue seems to be that the `dependencyStore` slice of state accessed through[ client/state/signup/dependency-store/selectors.js:13](https://github.com/Automattic/wp-calypso/blob/1718f43e78277d06f16df1bc550917dfb7d0c9c9/client/state/signup/dependency-store/selectors.js#L13) has an outdated site slug. This happens because the launch flow persists its site slug in stored dependencies through indexedDB.  The same launch flow site slug is subsequently loaded from indexedDB and referenced in the onboarding site flow. As a result, any paid items selected in onboarding will be added to the launch site's cart.

https://github.com/Automattic/wp-calypso/blob/1718f43e78277d06f16df1bc550917dfb7d0c9c9/client/state/signup/dependency-store/selectors.js#L12-L14

- There's a lot of abstracted logic to wade through, but basically, when we access a plan from an external page such as `/pricing`, the outdated site slug is inadvertently uses an async request to add a paid plan to the cart of the site. However, since we're using an outdated site slug, we add to the site's cart that was in the middle of the launch flow, and _not_ the site we're currently onboarding (that we accessed from `/pricing`).

https://github.com/Automattic/wp-calypso/blob/1718f43e78277d06f16df1bc550917dfb7d0c9c9/client/lib/signup/flow-controller.ts#L306-L309

https://github.com/Automattic/wp-calypso/blob/1718f43e78277d06f16df1bc550917dfb7d0c9c9/client/lib/signup/flow-controller.ts#L321-L338

https://github.com/Automattic/wp-calypso/blob/1718f43e78277d06f16df1bc550917dfb7d0c9c9/client/lib/signup/step-actions/index.js#L347-L361

I'm going to mull over possible solutions, but I'll do my best to have a fix set up by sometime tomorrow.

**Comment by simison** [comment]
@razvanpapadopol this can now be closed I assume? And other similar bugs in that flow that's no longer live for anyone?

**Comment by razvanpapadopol** [comment]
This bug is happening in live flows (`/start/launch-site` and `/start`) and will be probably fixed by https://github.com/Automattic/wp-calypso/pull/51021.

**Comment by yansern** [comment]
This PR https://github.com/Automattic/wp-calypso/pull/52434 provides the fix and the full analysis of the problem. :)

**Comment by razvanpapadopol** [comment]
Added this to the Signup pod's board just to keep track of it. 
@yansern @taggon, feel free to continue working on https://github.com/Automattic/wp-calypso/pull/52434 and ping us for reviews if needed 👷🏼

**Comment by razvanpapadopol** [comment]
> Added this to the Signup pod's board just to keep track of it.
> @yansern @taggon, feel free to continue working on #52434 and ping us for reviews if needed 👷🏼

Please ignore this ☝🏼 
@StefanNieuwenhuis from Pod Signup will take over as agreed in p1621348224006900-slack-C020SHYRB24

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/52434
