### ISSUE TITLE
The label "Dashboard" (not "Home") will be surfaced in the Editor when using nav hovers to open the Editor and in the Site Editor

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#50445]
### Steps to reproduce the behavior

From the Home screen in Calypso add a post (or page) by clicking Add New in nav sidebar hover.

![image](https://user-images.githubusercontent.com/545779/109039843-dc676b00-7692-11eb-8a85-d5c1bf2f5aad.png)

Click the W button in the Editor.

![image](https://user-images.githubusercontent.com/545779/109039953-00c34780-7693-11eb-97c6-ca6afa4a6362.png)

#### What I expected to happen

The label "Dashboard" would read "Home" as Calypso uses the term "Home" instead of "Dashboard" to refer to that location. cc @lcollette 

### Context

This is also an issue with the Site Editor.

![image](https://user-images.githubusercontent.com/545779/109040143-39632100-7693-11eb-97e2-0076e6d43510.png)

**Comment by obenland** [comment]
Should be overridable in [`MainDashboardButton`](https://github.com/WordPress/gutenberg/blob/e8c58e18b396f5d66c7419f4089370f1583b138a/docs/designers-developers/developers/slotfills/main-dashboard-button.md).

**Comment by Addison-Stavlo** [comment]
Being that "Home" is a very common name for a Page that exists on most users sites, and that one can navigate through pages in this nav panel, wouldn't renaming 'Dashboard' to 'Home' in this panel potentially create confusion between calypso Home and the users Home page in the editor?  'Dashboard' may be more representative and less potentially confusing.

**Comment by ianstewart** [comment]
> wouldn't renaming 'Dashboard' to 'Home' in this panel potentially create confusion between calypso Home and the users Home page in the editor? 'Dashboard' may be more representative and less potentially confusing.

It may though that would invert the issue and we'd want to update Home to Dashboard everywhere else. :D

cc @olaolusoga @lcollette

**Comment by Addison-Stavlo** [comment]
Its probably less of an issue being where it is located in the nav menu itself, but thoughts on surfacing it as "My Home" instead of just "Home" ? 🤔

**Comment by simison** [comment]
We just renamed it to “Dashboard” recently, since “My home” is pretty vague if you’ve never seen Calypso before (imagine you’re landing in the editor from signup and are editing “my home page”).

It also matches with terminology used in core (in the site editor sidebar).

https://github.com/Automattic/wp-calypso/issues/47054

This UI has heaps of other issues in that it's not easy to find way to dashboard, but terminology helps a bit here even if it isn't consistent with calypso term. Think it more like "I get back to that other dashboard experience, where my home page is".

I'd be open to call "my home" dashboard too though but that's another convo. Cc @jeffgolenski 

@ianstewart I'll close this for now but lemme know if you feel strongly about the terminology here and we can ponder some more. :-) Lets observe what comes up in potential future editor user testing.

**Comment by ianstewart** [comment]
> if you feel strongly about the terminology here and we can ponder some more. :-)

I think it should match-up with the Calypso screen term as it does elsewhere or perhaps be a generic "back". If the "my home" terminology is not working that should change. 

It's OK if we tackle that in a separate issue though.
