### ISSUE TITLE
Nav Unification: Jetpack sites getting WP Admin menus (not Calypso)

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/wp-calypso#50451]
### Steps to reproduce the behavior

1. Go to any Jetpack-connected site.
2. Note that the sidebar is displaying WP Admin menu options. 

#### What I expected to happen

I'd see Calypso-specific options. 

#### What actually happened

I see WP Admin options.

#### Browser / OS version

Chrome Version 88.0.4324.182

#### Does this happen on simple or atomic sites or both?

Jetpack

#### Is there any console output or error text?

No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

This came in a team call about somethingn else. Four people on the team checked various sites with the same result.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot on 2021-02-24 at 14-49-45](https://user-images.githubusercontent.com/22805865/109057422-b4d2cb80-76af-11eb-8d2b-1a5e6366acc5.png)

**Comment by tmmbecker** [comment]
I created a new JN site and connected with no plan. I saw the correct Calypso menu appear briefly and then it switched to the same WP Admin menu. NOTE that this WP Admin menu that I'm seeing in Calypso is MISSING the Jetpack menu that appears in the actual WP Admin menu.

**Comment by mmtr** [comment]
Thanks for your report, @tmmbecker. This should be solved as of https://github.com/Automattic/jetpack/pull/18921 and https://github.com/Automattic/wp-calypso/pull/50444. If you try Jetpack 9.5 RC you should get a menu that is pretty much the same as the existing Calypso menu in the old navigation:

![](https://cln.sh/0LcXv4+)

Can you confirm? Feel free to reopen if you still reproduce any issue.

**Comment by getdave** [comment]
@tmmbecker I've also tested this as per your instructions using a fresh JN site. 

Steps:

1. Create JN site.
2. Install JP Beta.
3. Activate Release Candidate (this pulls in latest changes - note there is nothing we can do to avoid you having to take this step - it's the only way we can have you test the latest features before they land on WoA)
4. Connect JP.

Doing this you should see something akin to the following when viewing the site _via Calypso_ (depending on your Account color scheme setting on WordPress.com).

<img width="677" alt="Screen Shot 2021-02-26 at 09 42 58" src="https://user-images.githubusercontent.com/444434/109284414-bc14e900-7817-11eb-9b28-7b4e7b179c7f.png">

Switch back to WPAdmin and you'll see the menu remains unaffected.

Note also the JP menu is displayed:

<img width="527" alt="Screen Shot 2021-02-26 at 09 49 04" src="https://user-images.githubusercontent.com/444434/109284592-eff00e80-7817-11eb-8404-3e144e688b29.png">

I am intending to post to p2 today to request another round of feedback from your teams. We've had to keep this separate from Beta 2 because there's no guarantee that Nav Unification will ship to Jetpack connected sites unless all the JP teams are happy with it.
