### ISSUE TITLE
Nav unification: site image broken in navigation when using MailPoet plugin

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#50490]
The site image breaks visually when using MailPoet plugin:

![Screenshot 2021-02-25 at 19 56 05](https://user-images.githubusercontent.com/87168/109195803-a36aeb80-77a3-11eb-9ada-bfd64c1785ed.png)

![Screenshot 2021-02-25 at 19 56 35](https://user-images.githubusercontent.com/87168/109195796-a1089180-77a3-11eb-9969-ae7e29a0247d.png)

Chrome browser, Atomic site. 

On other admin pages image behaves just fine:

![Screenshot 2021-02-25 at 19 58 57](https://user-images.githubusercontent.com/87168/109196065-eaf17780-77a3-11eb-8223-f61dfbcbbc2e.png)

cc @getdave

**Comment by tjcafferkey** [comment]
The issue here is that MailPoet is [filtering out all stylesheets](https://plugins.trac.wordpress.org/browser/mailpoet/trunk/lib/Util/ConflictResolver.php#L81) unless they're their own, coming from WP core or various other [_allowed_ sources](https://plugins.trac.wordpress.org/browser/mailpoet/trunk/lib/Util/ConflictResolver.php#L11).

In this case we're loading in the nav unification styles through Jetpack which isn't on MailPoets allowed list so the styles aren't getting applied on the admins plugin page.

We need to reach out to the MailPoet team (which I will do) and notify them of this issue as we feel it's better fixed on their end rather than in Jetpack.

**Comment by obenland** [comment]
> We need to reach out to the MailPoet team (which I will do)

Any response from their end yet?

**Comment by tjcafferkey** [comment]
>Any response from their end yet?

I tested a build late last week which fixed the issue. This is due to get released this week AFAIK. Have set a reminder to check again in a few days time.

**Comment by tjcafferkey** [comment]
This has been fixed in the latest MailPoet release
