### ISSUE TITLE
Monthly pricing: Negative percentages in checkout

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#50525]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/start and purchase a Premium monthly plan.
2. Next go to Calypso's /plans page and click on Upgrade on the Business plan
3. In the checkout page, click on "Edit".

#### What I expected to happen

To see positive values for the discount percentages

#### What actually happened

Negative percentage values displayed

#### Browser / OS version

Chrome / MacOS

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="547" alt="Screenshot 2021-02-26 at 4 15 19 PM" src="https://user-images.githubusercontent.com/1269602/109295146-424f2080-7854-11eb-9cf4-e6bb89aba0af.png">

**Comment by DavidRothstein** [comment]
Hm, it seems to be using the discounted monthly price for comparison rather than the actual price -- i.e. for "One year" it's using 440 * 12 = 5280 as the price to compare, but it should actually be using 1050 * 12 = 12600.

This might be fixed as a side effect of https://github.com/Automattic/wp-calypso/pull/50383 (I'll leave a note there) but otherwise it's probably not too hard to fix separately.

**Comment by michaeldcain** [comment]
It looks like this was fixed in #50383.

<img width="601" alt="Screen Shot 2021-03-08 at 12 09 11 PM" src="https://user-images.githubusercontent.com/942359/110355412-32c79880-8007-11eb-820f-1099b36ff64e.png">
