### ISSUE TITLE
Nav Unification: Blank menu item under WooCommerce menu item in admin menu

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#50550]
### Steps to reproduce the behavior

With a JP site with WooCommerce 5.1 Beta 1 activated, and the new Woo Navigation enabled as well (see pbIJXs-Fz-p2 for instructions on how to set up a test site)...

1. Go to wordpress.com
4. See a blank menu item under the "WooCommerce" menu item in the admin menu

#### What I expected to happen

Only the "WooCommerce" menu item to be visible in the admin menu in Calypso.

#### What actually happened

There is a "blank" menu item under the "WooCommerce" menu item. This appears to be the menu item for the "Products" custom post type.

<img width="440" alt="Screen Shot 2021-02-26 at 11 57 51" src="https://user-images.githubusercontent.com/2098816/109360472-4c255380-7855-11eb-8591-2d7e501aeae6.png">

/cc @psealock @mmtr

**Comment by getdave** [comment]
I replicated this. Doesn't happen in WPAdmin, only Calypso. Where does Woo register menus like this for the "new menu" experience?

**Comment by mmtr** [comment]
I think this caused by the lack of `hide-if-js` classes in some submenus. When I check the DOM in WP Admin, I can see the menu is there but hidden. Note how the submenus that are appearing in Calypso are those without the `hide-if-js` class:

<img width="890" alt="Screen Shot 2021-03-01 at 17 32 27" src="https://user-images.githubusercontent.com/1233880/109527674-36619980-7ab4-11eb-91d2-7dc2f41286df.png">

This could be solved by 2 ways:
- Add the `hide-if-js` class to the hidden submenus in WooCommerce.
- Update the `admin-menu` API endpoint to ensure that hidden menu items don't return any submenu.

**Comment by mmtr** [comment]
> Update the admin-menu API endpoint to ensure that hidden menu items don't return any submenu.

Unfortunately JP 9.5 is released is tomorrow, so there is not enough time for fixing this in the API before the nav unification launch. If this a blocker, we should prepare a fix in WooCommerce. cc @mattsherman @psealock

**Comment by getdave** [comment]
Is there a fundamental reason these menu items shouldn't appear if JS is enabled? What's the underlying reason here for Woo?

Adding an exception for something like this to the API endpoint feels like it could go on growing forever. Can we provide a hook to allow folks to add their own exceptions as required? That way Nav Unification can delegate the reasonability for patching these things to the relevant "3rd parties".

Just suggesting a 3rd option of adding a custom CSS rule to Calypso to specifically target these Woo classes.

**Comment by mattsherman** [comment]
> Is there a fundamental reason these menu items shouldn't appear if JS is enabled? What's the underlying reason here for Woo?

@psealock can provide more detail, but my understanding is that the `hide-if-js` class is being used as a "workaround" to hide menu items when the new WooCommerce Navigation is enabled. This is probably because WooCommerce Navigation is in `woocommerce-admin` and not `woocommerce` core. 

> Adding an exception for something like this to the API endpoint feels like it could go on growing forever. Can we provide a hook to allow folks to add their own exceptions as required? That way Nav Unification can delegate the reasonability for patching these things to the relevant "3rd parties".

That would be nice. It also adds additional burden on third party plugin developers. But, those third parties will know exactly how things should be handled.

> Just suggesting a 3rd option of adding a custom CSS rule to Calypso to specifically target these Woo classes.

I think that in this specific case, this might be the best short-term solution, as I don't know if we'd be able to get a proper fix in WooCommerce either in time, since it is in RC and due to be released next week.

**Comment by psealock** [comment]
>This could be solved by 2 ways:

> * Add the hide-if-js class to the hidden submenus in WooCommerce.
> * Update the admin-menu API endpoint to ensure that hidden menu items don't return any submenu.

A fix to the Jetpack API so that it replicates wp-admin behaviour seems ideal because other plugins may encounter the same scenario. If that is the consensus, I can create an issue in Jetpack.

>I don't know if we'd be able to get a proper fix in WooCommerce either in time, since it is in RC and due to be released next week.

Unfortunately, this is the case and leaves us with adding a temporary custom CSS rule in Calypso as the only decent solution. 

>Is there a fundamental reason these menu items shouldn't appear if JS is enabled? What's the underlying reason here for Woo?

As @mattsherman mentioned, WooCommerce Admin and Navigation is all Javascript, so the class is a handy way to exclude elements from the DOM with certainty.

**Comment by mmtr** [comment]
In Automattic/jetpack#18969 we added a fix to the API endpoint in order to replicate the Core behavior and @jeherve has been able to include on Jetpack 9.5 ❤️ , so we should be all set for the nav unification launch.

**Comment by mattsherman** [comment]
> In [Automattic/jetpack#18969](https://github.com/Automattic/jetpack/pull/18969) we added a fix to the API endpoint in order to replicate the Core behavior and @jeherve has been able to include on Jetpack 9.5 ❤️ , so we should be all set for the nav unification launch.

Awesome news. Huge thanks! 🙌

**Comment by psealock** [comment]
Wow 😮 amazing, thank you @mmtr!
