### ISSUE TITLE
Add Custom CSS submenu item to Appearance nav

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#50569]
**What**
It'd be great to have a direct link to Custom CSS in the navigation.

**Why**
This is a popular feature and would require one less click via the Customizer. It also would raise awareness to the fact we do have Custom CSS features at WordPress.com, and is quick-win upsell opportunity (the upsell notice already exists in the Customizer).

**Comment by getdave** [comment]
This fix would only be possible on Simple at this point @tjcafferkey due to Jetpack release schedules.

**Comment by tjcafferkey** [comment]
@getdave that's fine. There wouldn't be an issue releasing this to Simple Sites whilst at the same preparing the work in Jetpack for the next release, will there?

**Comment by tjcafferkey** [comment]
>This fix would only be possible on Simple at this point

This menu item already exists on Atomic sites.

I've worked on a diff for this on Simple sites here D58341-code which is in review.

**Comment by tjcafferkey** [comment]
@cpapazoglou if the Edit CSS menu item gets added to Atomic [here](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/custom-css/custom-css-4.7.php#L136) where is the best place to move the code in the above diff to so that it only gets applied to Simple Sites or reliably gets added to both Atomic and Simple (ie. we don't end up with duplicate menu items)

Adding it [here](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L406) will result it 2 admin menu items in Atomic wont it?

**Comment by cpapazoglou** [comment]
Here https://github.com/Automattic/jetpack/blob/3eaa2c3b05aed96556bf24d80326f9c334ac8c8d/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L17 

would be a good place for adding Simple sites specifics. 

If we were to add it in the generic class

https://github.com/Automattic/jetpack/blob/d5faf7b8b509e3fb9db892c63785aa039dbe65fb/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L406

we will probably first need to unregister it and reregister it once so it applies both for Simple & Atomic.
