### ISSUE TITLE
Remove redundant/duplicate Categories link in nav

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#50568]
### Steps to reproduce the behavior

* Posts → Categories goes to the WP Admin version, and *Settings → Writing → Categories* goes to the Calypso version

#### What I expected to happen
Either the Calypso version OR the WP Admin version of a page should show, and only one route should be visible (decided by the Account Settings toggle).

#### What actually happened
There are several place where there are both WP Admin and Calypso links.

**Comment by mmtr** [comment]
I also noted we have the same problem with Posts > Tags (WP Admin) and Settings > Writing > Tags (Calypso).

As suggested, we should have in consideration the "show advanced pages" setting:

- If toggle is disabled -> keep Calypso links in menu.
- If enabled -> keep WP Admin links in menu.
- In any case, both screens should be accessible via direct link.

**Comment by obenland** [comment]
Alternatively we could also hide the Category/Tags UI in Settings > Writing.

@sfougnier Do you have a preference either way?

**Comment by sixhours** [comment]
I'm seeing two issues here:

- [x] The sidebar navigation links to Categories and Tags management in `/wp-admin`, regardless of the Dashboard appearance settings. When the toggle is **off**, these should go to `/settings/taxonomies/categories/[site]` and `/settings/taxonomies/post_tag/[site]` respectively. When the toggle is **on** these should go to their respective screens in `/wp-admin` - Done in Automattic/jetpack#19569 and r224677-wpcom

- [x] When the toggle is **on**, the links under Settings -> Writing still go to their respective Calypso screens rather than `/wp-admin`, which is inconsistent with expectations. I think hiding the flow to these settings when the toggle is on makes more sense, as Konstantin suggests. - Being worked on in #52112

**Comment by sixhours** [comment]
Closed by the above issues
