### ISSUE TITLE
Missing dependencies: ./packages/composite-checkout/package.json

### ISSUE THREAD

**Issue by scinos** [Automattic/wp-calypso#50647]
### Undeclared dependencies:
```
  ./packages/composite-checkout/src/components/order-review-line-items.tsx:11:1: Undeclared dependency on src
  ./packages/composite-checkout/src/components/radio-button.tsx:10:1: Undeclared dependency on src
```

### Missing peer dependencies
```
  ./packages/composite-checkout/package.json:53:32: Unmet transitive peer dependency on enzyme@^3.11.0, via @automattic/calypso-build@^7.0.0
  ./packages/composite-checkout/package.json:53:32: Unmet transitive peer dependency on jest@>=26.4.0, via @automattic/calypso-build@^7.0.0
  ./packages/composite-checkout/package.json:53:32: Unmet transitive peer dependency on postcss@^8.2.6, via @automattic/calypso-build@^7.0.0
```

**Comment by sirbrillig** [comment]
The weird imports should be fixed by https://github.com/Automattic/wp-calypso/pull/51321 and https://github.com/Automattic/wp-calypso/pull/51320 which also adds `jest` to the `devDependencies`, but I don't understand the mentions of enzyme and postcss. `composite-checkout` does not use those packages. 

How do I get these warning messages to display? Running `yarn` at the root of the monorepo mentions a bunch of other packages, but not `composite-checkout`.

**Comment by scinos** [comment]
`npx @yarnpkg/doctor packages/composite-checkout` should show the errors.

> I don't understand the mentions of enzyme and postcss. composite-checkout does not use those packages.

They are "errors" because a dependency of `composite-checkout` (`calypso-build` in this case) is saying "whoever imports me needs to import these packages as well". Most likely nothing will break if `composite-checkout` don't specify those dependencies, but it is theoretically possible that a future version of `calypso-build` starts assuming those packages are indeed present.
