### ISSUE TITLE
Replace "Add new site" with "Add New Site"

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#50698]
Code is here 

https://github.com/Automattic/jetpack/blob/3eaa2c3b05aed96556bf24d80326f9c334ac8c8d/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L104

![](https://cln.sh/02ZzMk+)

**Comment by mmtr** [comment]
@cpapazoglou why is this needed? I think we're trying to adapt a "Sentence case" format instead of a "Title Case" format (e.g. https://github.com/Automattic/wp-calypso/issues/40120, https://github.com/Automattic/wp-calypso/issues/40027, https://github.com/Automattic/wp-calypso/issues/42586).

Actually, we're currently using `Add new site` in Calypso: 

https://github.com/Automattic/wp-calypso/blob/afbb92042b7b7abbed2cc76d365a493399467bd7/client/components/site-selector/add-site.jsx#L34

https://github.com/Automattic/wp-calypso/blob/afbb92042b7b7abbed2cc76d365a493399467bd7/client/my-sites/sidebar/index.jsx#L1000

https://github.com/Automattic/wp-calypso/blob/afbb92042b7b7abbed2cc76d365a493399467bd7/client/my-sites/sidebar-unified/index.jsx#L147

**Comment by cpapazoglou** [comment]
@mmtr While "Sentence case" is our preference in Calypso, WP Admin has a "Title Case" preference visible in submenus
![](https://cln.sh/kChD2E+). As we try to align with WP Admin at least in the sidebar, it would be better going for "Title Case" in these cases.
