### ISSUE TITLE
Nav Unification: Add a way to access Inactive Widgets from the Customizer

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#50868]
**What**
The Widgets section in the Customizer doesn't offer a way to access the Inactive widgets so once Nav Unification is implemented, it will be more difficult for users to access that feature.

**Why**
Sometimes users want access to widgets they added in the past but no longer appear for one reason or another (ie., sometimes when changing themes users will lose widgets if the widget area doesn't exist) so we refer them to the WP Admin dashboard to easily add them back. Users will now need to know how to access the WP Admin Widget area by the direct link in order to get there.

**How**
A simple solution would be to add a link to the WP Admin Widgets page from the Widgets section in the Customizer.

**Comment by kdevnel** [comment]
I also just came across a new occurrence of this. Since we redirected all Widget editing links to the Customizer it is no longer possible to reach the /widgets.php page where you can manage inactive widgets unless you enter that domain name directly.

This is the interface you get at that URL on a self-hosted site:

![Markup on 2021-08-14 at 17:06:37](https://user-images.githubusercontent.com/22053773/129450678-bb04caec-519c-44fd-bd39-286f49ec2023.png)

This came up on 4219136-zd-woothemes

**Comment by mmtr** [comment]
> Since we redirected all Widget editing links to the Customizer it is no longer possible to reach the /widgets.php page where you can manage inactive widgets unless you enter that domain name directly.

We recently shipped a fix so "Appearance > Widgets" now points to `widgets.php`. I guess we can close this issue then?
