### ISSUE TITLE
Media Uploads: Uploading .zip files in Calypso fails with "error occurred while uploading"

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#50928]
### Steps to reproduce the behavior

Trying to upload a .zip file from Calypso fails

1. Visit https://wordpress.com/media/ (requires a website with a Personal or higher level plan [per our support guide](https://wordpress.com/support/accepted-filetypes/#documents))
2. Upload a .zip file
3. The error "1 file could not be uploaded because an error occurred while uploading." will display on the page and the file will not be uploaded

You can upload the file successfully and without error in WP Admin:

1. If the website has nav unification setup then visit https://wordpress.com/me/account to turn on the "Show advanced dashboard pages." setting and save. If you aren't using unified nav then you can skip this step.
2. Visit DOMAINCOM/wp-admin/upload.php (again, requires a website with a Personal or higher level plan [per our support guide](https://wordpress.com/support/accepted-filetypes/#documents))
3. Upload a .zip file
4. Note that the file is uploaded without error

#### What I expected to happen
All websites using our paid plans should be able to upload .zip files to the Calypso media library page.

#### What actually happened
Uploading a zipped file via Calypso leads to failure and an error message.

### Context
User report (don't have the case# and personal testing).

#### Browser / OS version
N/A

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
Yes:
![Screen Shot 2021-03-09 at 8 36 35 PM](https://user-images.githubusercontent.com/33190975/110562266-cb950b80-810e-11eb-9155-6c42640af5e9.jpg)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium currently, though the impact will be heightened once nav unification launched because we'll be taking away easy access to WP Admin (requiring customers to enable the setting before WP Admin can be fully accessed).

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See above for the console error screenshot.

**Comment by cpapazoglou** [comment]
I am removing Nav Unification label, as it is unrelated to the bug itself.

**Comment by synora** [comment]
Tested this and uploading .zip files for simple sites worked fine with or without "Show advanced dashboard pages"  selected. I did have to turn on that option on my Atomic site, otherwise, the error message would appear and the .zip file would fail to upload.

**Comment by goblinartificer** [comment]
This is true of a lot of other file formats, including .ics!

**Comment by lakellie** [comment]
Another report in 3863712-zen (Atomic site)

**Comment by metabreakr** [comment]
8083194-hc (Atomic)

**Comment by devNigel** [comment]
Another report: 3877713-zen ( Atomic )

**Comment by xpurichan** [comment]
Reported in 3929382-zd.

**Comment by metabreakr** [comment]
Reported in 23234992-hc (simple).

Browser: https://www.whatsmybrowser.org/b/IAPSQ

**Comment by devNigel** [comment]
Another report: 29557116-HC ( AT )

I'd also like to note that uploading works fine via FIle block.

**Comment by pauloeaquino** [comment]
29644139-hc (AT)

**Comment by pauloeaquino** [comment]
3990452-zen (AT)

**Comment by jackiejade** [comment]
4038229-zen (AT)

**Comment by poojashetty18** [comment]
25524338-hc (AT)

**Comment by metabreakr** [comment]
26718976-hc with a `.ppsx` file.

**Comment by isocialtish** [comment]
Another report 4120847-zen (AT) they've had it consistently happen with several zip files and have come to chat several times.

**Comment by dsas** [comment]
I'm struggling to reproduce this in firefox 89 and chrome 91 so far. 

1. I've created [this zip](https://github.com/Automattic/wp-calypso/files/6776748/test.zip)
2. Go to https://wordpress.com/media/
3. Select my site (it's a simple site, unlaunched, on the premium plan)
4. I press 'Add new' and select the zip attached above ^^, then press open
5. It uploads the zip.

**Comment by xpurichan** [comment]
@dsas I'll admit that I am a little puzzled by my own report. I thought this issue was only present on Atomic, though I did clearly indicate "both" in my original post. I thought this could have just been a mistake but @jonnyruzek mentioned this affecting a customer's simple site in an earlier comment, so now I'm a bit unsure (perhaps there was an unrelated issue there?)

You should be able to consistently reproduce the issue on an Atomic site.

**Comment by dsas** [comment]
thanks @xpurichan 🙌 I can reproduce on atomic immediately, using my steps above but selecting an atomic site.

I get this response
```
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"unsupported_mime_type","message":"File type unknown"}}
```

when POSTing to https://public-api.wordpress.com/rest/v1.1/sites/SITEID/media/new?http_envelope=1

**Comment by xpurichan** [comment]
Reported in 30394506-hc

**Comment by dsas** [comment]
The user-facing docs explains what kind of files are allowed: [zip files are allowed as long as the .zip file contains accepted file types](https://wordpress.com/support/accepted-filetypes/)

Uploading files uses the [new media API endpoint](P2gHKz-g-p2.1/post/sites/%24site/media/new/)

For atomic sites this is using a hardcoded allowed mimetypes list which doesn't include zips, for simple sites it's varying the allowed mimetypes depending upon the site's options.

For atomic sites the relevant parts of the flow are:
  - `Public_API_WPCOM_JSON_API->process_request`
    - Identifies the request as a jetpack request due to `STATS_SITE == $target_blog_details->site_id`
  - `Public_API_WPCOM_JSON_API->process_jetpack_request`
    - Picks up that it's a /media/new request and routes accordingly
  - `Public_API_WPCOM_JSON_API->process_jetpack_media_upload_request`
  - `Public_API_WPCOM_JSON_API->upload_jetpack_files`
    - `Jetpack_Client->upload_files` is called with no parameters, so `$delete_in_two_hours = false`
        - This method has an allow list of mimetypes, which doesn't include zips (and never has) unless `$delete_in_two_hours` is true (for themes and plugins).
        - The allow list is eventually given to `wp_check_filetype`
        - As the mimetype (application/zip) is not in the allow list. it's not allowed.

Simple sites don't hardcode an allow list, so when they get to `wp_check_filetype`, they use `get_allowed_mime_types` and run it's 'upload_mimes' hook. In ms-default-filters this hook is registered to run `check_upload_mimes` which checks the blog/site options via `use_upgraded_upload_filetypes`

Next steps:
 * See what the differences are between the `Jetpack_Client` allow list and the default allow list, to see if the differences are intentional.
 * Find out why the `Jetpack_Client` needs it's own allow list
 * If it's not needed then remove the allow list
 * If it is needed, then some refactoring will be needed to ensure that it consults the blog/site options to have an accurate allow list.

**Comment by dsas** [comment]
Reviewing the various tickets and happy chats referenced so far, they're mostly atomic sites, the simple sites reports are not necessarily related to this ticket after all.

**Comment by dsas** [comment]
> See what the differences are between the Jetpack_Client allow list and the default allow list, to see if the differences are intentional.

Allowing for differences in formatting, the difference between simple premium site and an atomic business site are:

Simple has these extra

- [asc] => application/pgp-keys
- [docm] => application/vnd.ms-word.document.macroEnabled.12
- [gz|gzip] => application/x-gzip
- [key] => application/vnd.apple.keynote
- [pot] => application/vnd.ms-powerpoint
- [ppsm] => application/vnd.ms-powerpoint.slideshow.macroEnabled.12
- [pptm] => application/vnd.ms-powerpoint.presentation.macroEnabled.12
- [xla|xlt|xlw] => application/vnd.ms-excel
- [xlsb] => application/vnd.ms-excel.sheet.binary.macroEnabled.12
- [xlsm] => application/vnd.ms-excel.sheet.macroEnabled.12
- [zip] => application/zip

Atomic (aka the Jetpack_Client) has these extra:

- [bmp] => image/bmp
- [tif|tiff] => image/tiff
- [txt] => text/plain

In addition there are slightly different treatments of docx (and similar for xlsx ppsx)
Simple:    [docx] => application/vnd.openxmlformats-officedocument.wordprocessingml.document
Atomic:    [docx] => application/vnd.openxmlformats-officedocument.wordprocessingml

**Comment by dsas** [comment]
#18601 is probably a duplicate.

I can't find any documentation explaining why the Jetpack_Client has it's own allowed list of mimetypes and it's been like that basically forever (images in r59694-wpcom, documents in r63209-wpcom and more additions in r106880-wpcom). It looks as though wp-admin and the API are supposed to be in sync according to the media endpoints 1.1 launch announcement (p3hLNG-kl-p2)  Given that the mime types above can be uploaded via wp-admin I can't think that there's a security issue. 

I think the next steps are to 
1. Remove the `Jetpack_Client::upload_files` allowed mime type list
2. Add back support for bmp, tif and txt
  * The user-facing documentation doesn't mention that we support these, so it might be worth updating that
  * We should probably add them to simple sites too so that they're the same. 
  * Might be done by a `upload_mimes` hook, or by looking at `upgraded_upload_filetypes` (see `check_upload_mimes` - works by a pre_site_option_video_upload_filetypes filter which gets the list from a constant)

**Comment by cpapazoglou** [comment]
> * We should probably add them to simple sites too so that they're the same.

Thanks @dsas for the thorough details! Can you please create an Atomic P2 explaining why we will remove the `$allowed_mimes` list? Or at least add the missing formats in that list? Keeping in the loop Atomic folks may unveil the "Why".

**Comment by joweber123** [comment]
Another report here 30665805-hc (AT) They said that they have not had issues until recently with uploading zip files and I can confirm that uploading from Calypso gives this error while uploading from wp-admin does not.

**Comment by dsas** [comment]
I'm working on the necessary server-side changes for this under D64132-code

**Comment by dsas** [comment]
Deployed r229078-wpcom with thanks @mmtr
