### ISSUE TITLE
Social Menu: Add icon for TikTok

### ISSUE THREAD

**Issue by isocialtish** [Automattic/wp-calypso#50927]
In the social menu, when you add a link to a TikTok profile an icon for TikTok should display

![Screen Shot on 2021-03-09 at 14:03:28](https://user-images.githubusercontent.com/6664819/110555201-4135b300-80e0-11eb-8b27-344452d2a8ac.png)

**Comment by wynwin** [comment]
+1 Just had a user request this in a Quick Start session.

**Comment by joweber123** [comment]
+1 Just had a user request this in a Quick Start session.  It looks like we **do** support this in the [social icons block ](https://wordpress.com/support/wordpress-editor/blocks/social-links-block/#list-of-supported-icons)but not yet in the social menu.

**Comment by syds87** [comment]
+1 Requested in another Quick Start session for the social menu.

**Comment by xpurichan** [comment]
Requested in 29847928-hc.

**Comment by KokkieH** [comment]
Another request in https://wordpress.com/forums/topic/page-headers-tiktok-link-logo/

Noting support for this was added to Jetpack social menus in https://github.com/Automattic/jetpack/pull/18563. @jeherve, are you able to help getting this added on wpcom as well?

**Comment by formosattic** [comment]
+1 4178728-zd-woothemes

**Comment by jeherve** [comment]
> Noting support for this was added to Jetpack social menus in Automattic/jetpack#18563. @jeherve, are you able to help getting this added on wpcom as well?

We have added support on WordPress.com simple already.

The theme in use on this site, however, relies on its own custom social menu implementation:
https://github.com/Automattic/themes/blob/3efbab4eb950d0a86432064a0d1b2c581f8d6a12/varia/classes/class-varia-svg-icons.php

I would recommend opening a new issue in the Themes repo, for each theme where you experience the issue, so the theme can be updated to use Jetpack's Social Icons instead of a custom implementation. 

Here is an example of an existing issue for the Luxury theme:
https://github.com/Automattic/themes/issues/3860

**Comment by jeherve** [comment]
Closing this issue as per the comment above. I would recommend opening new issues for each theme that needs to be updated instead.

**Comment by KokkieH** [comment]
Thanks for the details, @jeherve 

I've opened an issue for Varia, Seedlet and their childen, cc @xpurichan 

I've added an issue for Obsidian, cc @formosattic 

The other reports here don't have any info on the theme or users, so I'm not able to check if there might be other themes affected.
