### ISSUE TITLE
Media: Unable to edit video thumbnail

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#50959]
### Steps to reproduce the behavior

1. Go to Media
2. Click on a video, then click Edit
3. Click Edit Thumbnail
4. Select Frame is greyed out

#### What I expected to happen

I would expect to be able to select a frame of the video to use as the video thumbnail.

#### What actually happened

Select frame is greyed out throughout the video runtime. Screenshot: 
<img width="1082" alt="Select frame grey" src="https://user-images.githubusercontent.com/30788962/110678905-0f7e2400-8194-11eb-8fe0-cc20de8aa6f8.png">

### Context

There was a previous issue here: https://github.com/Automattic/wp-calypso/issues/38892

#### Browser / OS version

Multiple browsers

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

I can recreate this on AT and simple sites. 

#### Is there any console output or error text?

I see some console errors. Screenshot:
<img width="1432" alt="Console errors" src="https://user-images.githubusercontent.com/30788962/110678935-186ef580-8194-11eb-8d9b-db254abe52d7.png">

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Seems to affect all sites.

**Comment by i11za** [comment]
Another report here: 4856796-zen

I was able to replicate it on my Atomic site. 
The behaviour is slightly different - the **Select Frame** option is active, however nothing happens when it's selected, and after loading for a shot while the page reloads in *Media* overview (screencast):

https://user-images.githubusercontent.com/84193945/158063581-93f32695-4305-42b5-afc5-09e8b412e710.mp4

I'm also seeing the following console errors (screenshot):

<img width="1241" alt="Screenshot 2022-03-13 at 15 06 39" src="https://user-images.githubusercontent.com/84193945/158063611-4cdfe604-4c3b-4e5f-a7c2-5a11bafed114.png">

Frame selector works as expected on a simple test site with a Business plan.

Let the user know they can use the **Upload Image** as a workaround for now (tested and confirmed it works).

**Comment by Greatdane** [comment]
The interface behaves the same on Simple and Atomic (so it looks like it has been saved), however, if I go back to the video on an Atomic site, the new thumbnail has not been saved.

**Comment by simison** [comment]
@roundhill would this bug be good for the VideoPress team?

**Comment by katinthehatsite** [comment]
I spent some time testing this bug and these were the outcomes of my tests:

* I was able to **both select frame and upload an image** to a video thumbnail;
* however, as the frame or image was set, I was brought back to the Media Library to the video that _seemed to have no thumbnail_;
* along with that, there was a 403 error in the console for the image:

<img width="1100" alt="Screenshot 2023-09-15 at 9 40 08 AM" src="https://github.com/Automattic/wp-calypso/assets/25575134/d5609548-4190-4659-8d56-74ea5e6aa2a7">

* when I refreshed the page, I could see that my thumbnail **was actually saved** and I could open the video editor and edit it:

<img width="1111" alt="Screenshot 2023-09-15 at 9 43 50 AM" src="https://github.com/Automattic/wp-calypso/assets/25575134/cf4ef549-b28d-40a8-a87f-d03d5a976f58">

* it seems that the issue is that **when the image upload or frame selection is finished**, you are brought back to the media library with the video that looks like it has no thumbnail (while it does have a thumbnail) which creates a confusing UX since you need to refresh the page or to click on the video again to confirm that the thumbnail was uploaded and added to your video
* Tested on `Firefox 115.0.3 (64-bit)` and `Chrome Version 117.0.5938.62 (Official Build)`
* This behaviour happens when you either both **Select frame** or **Upload image** 
* I was not able to replicated the issue specifically with not being able to select a frame on either Atomic or Simple on either of the browsers that I tested with

**Comment by katinthehatsite** [comment]
I see two possible ways to proceed with this:

* one option is to fix the issue is that when the progress bar for uploading is completed and the user is redirected back to `https://wordpress.com/media/` on upload, they could see the thumbnail being displayed here (so keeping current behaviour and fixing thumbnail preview):

<img width="841" alt="Screenshot 2023-09-15 at 11 59 27 AM" src="https://github.com/Automattic/wp-calypso/assets/25575134/348457d4-f700-45b1-87db-2671ab3c515d">

This will probably fix some of the confusion around the image seeming like it was not added or edited.

* the second option could be to modify the behaviour to be similar with how it works with `Cancel` button (so when doing `Edit Thumbnail -> Cancel`. It opens the video editor **specifically for thumbnail** but when the action is canceled, instead of jumping back to the Media Library, it goes back to the general video editor which you can close and get back to the Media Library. So the process would be something like:

* Navigate to `Edit Thumbnail`
* Click on either `Upload image` or `Select frame`
* Wait for the progress bar to finish loading and for the process to complete
* See uploaded thumbnail in the thumbnail editor
* Click on `Cancel` to get back to the general video editor
* Close the video editor once done with your editing
* You are brought back  to the Media Library

This approach seems to be more organic and smoother in terms of user experience but I am not a UX designer. 

@javierarce What would be your recommendation in terms of user experience? Thanks!

I added a video below to compare how two behaviour work:

https://github.com/Automattic/wp-calypso/assets/25575134/e3c1fa23-6e20-4c3f-b336-24f840d685bb

**Comment by javierarce** [comment]
@katinthehatsite: I haven't been able to reproduce the original problem, but your second proposal (bringing the user back to the video editor instead of directly displaying the Media Library) is the best approach because it brings the user back to where they were previously.

**Comment by katinthehatsite** [comment]
@javierarce - yeah makes sense, I will look into implementing that approach on Monday. I could not reproduce the original issue either but I think the **actual issue** is that the UX around closing the video editor is so confusing (when it self-closes after the thumbnail is set) that it looks like the thumbnail was not uploaded at all (which it was!). 

Thanks for your feedback!

**Comment by katinthehatsite** [comment]
I spent some more time on this and I could not replicate anymore either the original issue or the issue with the thumbnail preview once the thumbnail finished uploading. Here are the results of my testing:

**Safari**: Version 16.3 (18614.4.6.1.6)

https://github.com/Automattic/wp-calypso/assets/25575134/a6f34c9f-4672-4c4a-bb8f-4d5e0ac3c917

Both the image upload option and selecting a frame option are working as expected adding the preview for the thumbnail. 

**Firefox**: 117.0.1 (64-bit)

https://github.com/Automattic/wp-calypso/assets/25575134/43578d66-fd0f-4539-885c-9df5e9ab9a8e

**Chrome**: Version 117.0.5938.62 

https://github.com/Automattic/wp-calypso/assets/25575134/22ec73f9-1aea-42d9-a96a-c9d01cf166b7

Since I can't reproduce this anymore and the UX is made less confusing by the thumbnail preview actually appearing once the thumbnail is uploaded, I think we can close this as not reproducible. 

@jamiepalatnik @Greatdane - could you please test again and let me know if you still can see this issue? If yes, could you please add the exact steps that you are following?

**Comment by katinthehatsite** [comment]
For the general UX flow and improving that, I took a look at the code and most of it is about 7 years old and will likely take some work to refactor. I think we can possibly treat this as a separate issue to improve the UX and refactor the code and start a discussion outside of this issue.

**Comment by katinthehatsite** [comment]
Since I can't reproduce the issue anymore and we have no further reports since 2021, I am going to close this as not reproducible. If you can see it again, feel free to open a new issue.
