### ISSUE TITLE
Nav unification "advanced toggle" orphan symbol in Spanish

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#51027]
Open https://wordpress.com/me/account in Spanish and observe wp-admin advanced setting:

<img width="1104" alt="Screenshot 2021-03-12 at 15 00 04" src="https://user-images.githubusercontent.com/87168/110943368-cd93e000-8343-11eb-8d8f-bed7ae9aa37e.png">

See how the ?-symbol gets orphaned on its own line.

This function might help:

https://github.com/Automattic/wp-calypso/blob/9a3fc0feba3b8ddef3c40a04085883aa32dfc2bd/client/lib/formatting/index.js#L5

**Comment by mreishus** [comment]
I'm not sure if preventWidows() can help here, since it seems to be about [changing spaces in text strings](https://github.com/Automattic/wp-calypso/blob/6cf0e7e28f2761fa6c9fb578e18daae021bda33a/client/lib/formatting/prevent-widows.js#L6-L18), but this is happening at the boundary between element text and an `<svg>`.
![2021-04-21_16-39](https://user-images.githubusercontent.com/937354/115624583-79740800-a2c0-11eb-9169-9722c3ebb551.png)
