### ISSUE TITLE
Checkout: Upgrading to Monthly Business doesn't offer "discount"

### ISSUE THREAD

**Issue by jackiejade** [Automattic/wp-calypso#51037]
### Steps to reproduce the behavior

1. Go to Plans and purchase an annual Personal plan
2. Decide you need the Business plan but the annual is a bit much, so choose monthly instead
3. Click on plans and upgrade to Monthly Business
4. I've now been charged for 2 plans, one annual and one monthly.

#### What I expected to happen

When a user upgrades to a different annual plan, their already paid amount is applied as a "discount" but really, it's just taking into account what they've already paid. This doesn't happen when choosing a monthly option, which is fine, but the initial purchase should be acknowledged in some way either a credit toward their purchase or a refund. 

#### What actually happened

Charge for two plans and one of them isn't even on the account anymore. 

Purchase history page/payment history showing both purchases
![showing payment history](https://d.pr/i/XpHExx+)

Here is the Active Upgrades page for the user showing only the Business plan:
![active upgrades](https://d.pr/i/nhDyYi+)

### Context

This would be fine if the user is upgrading at the end of their existing plan. However, the user in my example upgraded the same day as they realized they needed a higher plan - which is the case for many users.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

This happens to anyone who upgrades to a monthly plan from an annual plan.

**Comment by cathymcbride** [comment]
@michaeldcain does this need to go on the shilling backlog?

**Comment by michaeldcain** [comment]
@jackiejade: I don't see a monthly option on the /plans/ page after buying an annual Personal plan. Can you let me know where that was offered? It _is_ possible to add an annual upgrade to your cart and then switch to monthly in Checkout, but as a policy, we allow term picking for upgrades so it's not specifically a Checkout issue.

<img width="1552" alt="Screen Shot 2021-03-16 at 11 14 32 AM" src="https://user-images.githubusercontent.com/942359/111333403-0a641d80-8649-11eb-8de4-ab53efee2999.png">

@cathymcbride: the underlying issue here is related to our Payments infrastructure, and is tracked in c/W7hLWnbg-tr. It seems like the offering of monthly plans has increased the severity of this issue and @DavidRothstein has increased its priority. I'll add the issue to our GH backlog to track its fix.

**Comment by metabreakr** [comment]
4034873-zen

**Comment by DavidRothstein** [comment]
I think this is now fixed via https://github.com/Automattic/wp-calypso/issues/52473.
