### ISSUE TITLE
Reader: site display in edit following page

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#5118]
The site display in `/following/edit` should be the same as `<Site>` components.

![image](https://cloud.githubusercontent.com/assets/548849/14916277/ed7e3fa0-0e18-11e6-877a-91d2b2156541.png)

![image](https://cloud.githubusercontent.com/assets/548849/14916313/33c95b2a-0e19-11e6-96c5-aad95bc1aa83.png)

cc @jancavan

**Comment by bluefuton** [comment]
I quite like the external site indicator. How do you feel abut have that in the `<Site>` components @mtias?

<img width="18" alt="screen shot 2016-04-29 at 14 16 51" src="https://cloud.githubusercontent.com/assets/17325/14917062/11b8f742-0e15-11e6-809f-80eacceba32e.png">

**Comment by mtias** [comment]
I think we should use an external-link Card:

**Comment by mtias** [comment]
Or a "view site" button like in other places.

**Comment by folletto** [comment]
Updating screenshot reference since it got updated from the one above:

![screen shot 2016-05-20 at 13 04 42](https://cloud.githubusercontent.com/assets/4389/15427228/7ab3af86-1e8b-11e6-9bec-2f3d1450f569.png)

+1 to update the badge to the standard `Site` component. I don't think it needs a view site there more explicit, it's not a primary action, but still it's clickable as everywhere else.

I also noticed that the overall typeface there is a bit bigger than everywhere else in the UI and the button is not vertically centered. See current / with tweaks:

![screen shot 2016-05-20 at 13 07 08](https://cloud.githubusercontent.com/assets/4389/15427272/cd91029e-1e8b-11e6-95b2-c8752a914a9e.png)
