### ISSUE TITLE
Site Editor: Query Block link to open Post Editor not working on Horizon

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51206]
### Steps to reproduce the behavior

1. Open Site Editor in WP.com.
2. Add a Query Block.
3. Open block inspector sidebar.
4. Click "Create a new post." (Screenshot below.)
5. See bug. (Screenshot below.)

**Click "Create a new post."**

![image](https://user-images.githubusercontent.com/545779/111700877-05999800-8808-11eb-94d3-efaec33ed839.png)

**See bug.**

![image](https://user-images.githubusercontent.com/545779/111700923-134f1d80-8808-11eb-888f-a45e78d2f2da.png)

**Comment by david-szabo97** [comment]
The error is: 

```
Refused to display '_YOUR_SITE_URL_' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

The link works fine if you access your site using `subdomain . wordpress.com`. It breaks if you access it through `wordpress.com/site-editor/_YOUR_SITE_`. Which makes sense since we are using `sameorigin`.

"Manage reusable blocks" breaks for the same reason.

Accessing the site editor through `wordpress.com`, the editor is iframed so the link is trying to navigate the iframe. Which isn't ideal in this case. Somehow we should tell the hyperlink to use `target="_parent"`. And we should change the `href` as well to point to WPcom rather than WPadmin
