### ISSUE TITLE
WP.com Plugins: add missing functionality

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#5125]
There are some nice features that we support that we should communicate in this page:

- [ ] Publicize (separate from social media icons)
- [ ] Polls
- [ ] Ratings
- [ ] Post by Email

**Comment by rralian** [comment]
I think we also add:
### Business
- [ ] live chat support

**Comment by mtias** [comment]
Agreed.

**Comment by drw158** [comment]
> Publicize
Seems okay to me. It wasn't included because it wasn't in our original list of wp.com plugins.

> Polls
Can users add Polls in Calypso?

> Ratings
I thought this was retired in Calypso?

> Post by email
Maybe? 

> Live Chat
As discussed before, I don't think of this as a plugin and it doesn't fit in the scope of this page. It makes me think that I can add Live Chat support to _my_ site.

**Comment by mtias** [comment]
> Can users add Polls in Calypso?

Yes via shortcodes, eventually as embeds in the editor.

**Comment by drw158** [comment]
That would fall under the "Extended Shortcodes" where we link to a whole list of shortcodes. We could add "Polls" in the description, or make it its own "plugin" on the page.

**Comment by mtias** [comment]
Yeah, I think making it its own item would be good.
