### ISSUE TITLE
Nav Unification: Offer access to Share Stats

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#51252]
With the new dashboard that prevents access to WP Admin, users can no longer access the Share Stats as described here:

https://wordpress.com/support/sharing/#share-stats

Can these be added to the Stats Insights?

**Comment by Aurorum** [comment]
Hi! Out of interest, is there no way to access the previous Share Stats at all, even through some obscure URL? I can try adding them to Calypso, but I just need to verify that the correct number will be displayed first.

**Comment by Aurorum** [comment]
Ah, I managed to access it. It seems like just the total number of Shares was displayed there. That should be pretty easy to add to the Insights section.

<img width="850" alt="Screenshot 2021-03-21 at 15 50 29" src="https://user-images.githubusercontent.com/43215253/111911359-31fa2200-8a5d-11eb-91e3-f6d975d53a11.png">

But there's also a deeper breakdown of how those stats are distributed regarding individual services. Although I usually prefer collected data like this being published because it can be interesting for site owners, I'm not sure if that should be shown to them too. It'd be a little more complicated, but I imagine it could just be a box similar to the "Publicize" one. 

<img width="244" alt="Screenshot 2021-03-21 at 16 08 25" src="https://user-images.githubusercontent.com/43215253/111912022-af269680-8a5f-11eb-84ee-6e00ba5d7b45.png">

**Comment by ccwalburn** [comment]
Hi @Aurorum ! This particular request was based on a user I worked with who wanted to see which post was shared the most. Our documentation made it sound like that was possible by clicking on the total number of shares:

![screenshot](https://d.pr/i/D5zegV+)
Image URL: https://d.pr/i/D5zegV

Do you see that information anywhere?

**Comment by Aurorum** [comment]
Oh, yep. Looking into it, I don't think that information is passed to Calypso though (at least I can't find it) so that might require adding to the API first. 

Just for context, here's that screen: 

<img width="1683" alt="Screenshot 2021-03-21 at 21 10 08" src="https://user-images.githubusercontent.com/43215253/111921195-1e65b000-8a8b-11eb-977d-535dd80f8f01.png">

**Comment by syds87** [comment]
Hi!

I had a similar report on #3838128-ZD.

**Comment by thesacredpath** [comment]
Report here as well: #3851156-zen

Told user we would update them via ticket once this is fixed.

**Comment by Aurorum** [comment]
Been thinking about this one again, and I think that displaying the "Top Posts & Pages" information will be a little tricky because it doesn't seem like that information is provided by the API, nor is it something that seems to be included within Jetpack, so I think that's something I'm not able to add. 

The "Top Sharing Services" is significantly easier to add though - I wonder if there'd be benefit in making that available, even without the rest of the data? I recognise that information is probably less important to the average user compared to the details of the content being shared. 

However, while providing this information in Calypso will still have benefits, it seems that the Stats page not being accessible at all is a wider issue being tracked in #51381. Once that is resolved, people should hopefully be able to access this information again.

**Comment by darnelldibbles-zz** [comment]
We have another user bring this up in https://wordpress.com/forums/topic/unified-navigation/page/2/#post-3653791

**Comment by rachelwinspear** [comment]
Another case #3859675-zen
`I’m talking about the old ‘classic’ dashboard stats, where you could see what posts had been shared and how many shares.`

**Comment by mmtr** [comment]
Thanks for reporting this, @ccwalburn! We're already tracking this in https://github.com/Automattic/wp-calypso/issues/51095, so I'm going to close this out as duplicate.
