### ISSUE TITLE
Customizer: Can't add custom links to menus

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/wp-calypso#5132]
When trying to add a custom link to a menu, the input fields aren't accessible—they don't gain focus when you click on them, so you can't type anything into them.

![custom-link](https://cloud.githubusercontent.com/assets/376315/14928978/038a15fa-0e53-11e6-9eda-daf339ca91fd.gif)

You can't see it, but that's me furiously trying to click on those input fields.

`.accordion-section-content` is overlapping this area, making it impossible to select the text fields in the "custom links" panel. Setting the element to display: none, or setting its z-index to -1 resolved the issue.

#### Steps to reproduce
1. Make a site on WordPress.com.
2. Open the Customizer.
3. Menus > Select a menu > Add item > Custom link.
4. Try to input text in the input fields.

#### Browser / OS version
Firefox 47.0a2 / OS X El Capitan

**Comment by lancewillett** [comment]
Hi @sarahmonster — thanks for this report; I don't think it's specific to Calypso, though. Customizer still runs from wp-admin (core files) rather than Calypso's JS-based framework.

If you raise it with Gravity team they can probably say where they want bugs logged (I think in a GitHub repo maybe, or WP.com Trac).

**Comment by lancewillett** [comment]
Moved to 100-gh-customizer for now.
