### ISSUE TITLE
Editor: show site logo in place of W icon

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#51396]
### What
For sites with site icon set, let's show the site icon in place of W icon in the header.

### Why
- This will align us with core which already shows site icon.
- Site icon will make it clearer which site you're editing in case you have multiple sites.

### How

[`__experimentalFullscreenModeClose`](https://github.com/WordPress/gutenberg/search?q=__experimentalFullscreenModeClose) button can be imported from core, and it accepts an option `icon` prop. Since this is `__experimental` API, it would be important to cover this with a function-availability check and a test so that folks doing Gutenberg upgrades catch when it might stop working.

We override the button in post editor [with code that's in editing toolkit](https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar).

It's enough to do this for post/page editor for now — site editor can be handled separately.

**Before**

<img width="364" src="https://user-images.githubusercontent.com/87168/112461056-3c236580-8d68-11eb-8df4-81b9768297f2.png">

<img width="364" src="https://user-images.githubusercontent.com/87168/112460677-d46d1a80-8d67-11eb-9173-4b925f612bf3.png">

**After**

<img width="364" src="https://user-images.githubusercontent.com/87168/112461066-3fb6ec80-8d68-11eb-8137-307d73bd1ec7.png">

<img width="364" src="https://user-images.githubusercontent.com/87168/112460856-04b4b900-8d68-11eb-8f5a-8638902da56e.png">

FYI @ianstewart @olaolusoga

**Comment by vindl** [comment]
> Code for this is already in Gutenberg, but we need to adapt it to our own custom sidebar. We override the button in post editor with code that's in editing toolkit.

The linked code is in `edit-site`, it might be better to use the one provided in `edit-post`. It exports `__experimentalFullscreenModeClose` button which accepts optional `icon` prop, and we should be able to reuse it here and feed it to `<MainDashboardButton.Slot>` in ETK plugin override (that was the intended usage when the slot was made at least).

**Comment by mtias** [comment]
This is tiny effort for a relatively bit impact, let's prioritize updating it :)

**Comment by creativecoder** [comment]
Draft PR for this started at https://github.com/Automattic/wp-calypso/pull/51477

The `__experimentalFullscreenModeClose` component isn't all that helpful, as it outputs a fully formed button with a link that exits the editor (rather than open the sidebar menu). But it's not difficult to use the same general approach to fetch the site icon and using it for toggling the menu.

Note that the way the icon is [shimmed into the root api endpoint](https://github.com/WordPress/gutenberg/blob/08616cb3829531523331bb42476850f934b20708/lib/init.php#L160) seems to be in flux, and it doesn't work as is for Simple Sites, so I think relying on a wpcom endpoint for fetching the site icon (at least until it stabilizes in Core) is going to be the way to go, for now.

**Comment by david-szabo97** [comment]
> Note that the way the icon is shimmed into the root api endpoint seems to be in flux, and it doesn't work as is for Simple Sites, so I think relying on a wpcom endpoint for fetching the site icon (at least until it stabilizes in Core) is going to be the way to go, for now.

My approach that I explore in https://github.com/Automattic/wp-calypso/issues/51482#issuecomment-811920019 is quite hacky but I think we need to solve the endpoint issue somehow. Since there are other data that we use from that endpoint, for example the site's title.

**Comment by creativecoder** [comment]
https://github.com/Automattic/wp-calypso/pull/51477 is working as is for Jetpack/Atomic sites, but not for Simple sites because root endpoint with the site icon isn't preloaded correctly. A couple possible solutions:

- Adding middleware for wpcom to transform the API request (a bit hacky, but it works): D59634-code
- Updating how Gutenberg gets the icon to only add the `context=edit` parameter when needed: https://github.com/WordPress/gutenberg/pull/30482

I'll see if we can land the Gutenberg change, and if not, we can fall back to the wpcom hack.

**Comment by creativecoder** [comment]
Correction, #51477 will work with Simple sites, but needs some wpcom changes first: D59822-code

**Comment by ciampo** [comment]
With #51477 merged:

- the bug should be fixed for Atomic sites that update to latest ETK version
- the bug will be fixed for Simple sites once D59822-code gets approved and deployed

**Comment by davipontesblog** [comment]
@creativecoder how can one track whether these have been deployed to both simple and atomic sites in WP.com so the issue can be closed?

> the bug should be fixed for Atomic sites that update to latest ETK version
the bug will be fixed for Simple sites once D59822-code gets approved and deployed

We can then also close https://github.com/Automattic/wp-calypso/issues/51482

Thanks!

**Comment by ciampo** [comment]
> how can one track whether these have been deployed to both simple and atomic sites in WP.com so the issue can be closed?

As explained above, Atomic sites should already be fixed as soon as they update their ETK plugin. For the fix to land on Simple sites, instead, D59822-code needs to be approved and deployed (pending @Automattic/cylon review) — so, basically, tracking the progress on D59822-code should be enough

I believe that @creativecoder and the whole of @Automattic/cylon are off until next week.

> We can then also close #51482

Yes, that was the plan! In fact I already posted the [same comment](https://github.com/Automattic/wp-calypso/issues/51482#issuecomment-814880507) and added the same `[Status] Fix Inbound` label

**Comment by davipontesblog** [comment]
Thanks so much for clarifying! And yes I actually just checked an atomic site of mine and I see the site icon there now already :)

**Comment by davipontesblog** [comment]
This is now working on simple sites and atomic sites.
