### ISSUE TITLE
AMP 2.0 - validation fails with error

### ISSUE THREAD

**Issue by kavyagokul** [Automattic/wp-calypso#51539]
### Steps to reproduce the behavior

1. Go to 'https://validator.amp.dev/
2. Enter a URL that has AMP 2.0 (one with ?amp-next=1 appended)
3. Validation fails with this warning

> Tag 'html' marked with attribute 'data-ampdevmode'. Validator will suppress errors regarding any other tag with this attribute.

#### What I expected to happen
Validation passes

#### What actually happened
Validation failed

#### Browser / OS version
Firefox developer edition 88.0b2 / Archlinux

#### Does this happen on simple or atomic sites or both?
Simple

#### Screenshot / Video: 
![Screenshot_2021-03-30 The AMP Validator](https://user-images.githubusercontent.com/1659416/112946196-dc0b3580-9152-11eb-9c3e-71f8d384ba95.png)

**Comment by erricgunawan** [comment]
I can confirm this happens to me too. 
On Simple site. 

#### Browser / OS Version:
Chrome Version 89.0.4389.90 (Official Build) (x86_64)
macOS Catalina 10.15.7

**Comment by claudiucelfilip** [comment]
Thank you for testing and raising this.

The error is caused by the fact that AMP Dev Mode is enabled. This is an expected behaviour in this version of the plugin. However, this should only be enabled if the user is logged in. However, an  additional, custom, sanitizer is overwriting this and forcing this mode all the time.
Opened D59726-code to prevent the Dev Mode from being overwritten.

**Comment by claudiucelfilip** [comment]
D59726-code Has been deployed. The issue should be fixed now.

**Comment by wojtekn** [comment]
We removed AMP support for Simple sites on July 11th, 2022 so this issue is not actual anymore. pdKhl6-lx-p2#comment-368 (However, it looks like it was fixed before 🙂)
