### ISSUE TITLE
Checkout: give user option to empty cart when exiting Checkout

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#51556]
We're seeing increased reports of users misunderstanding the abandoned cart notifications and emails throughout the product - sometimes leading to duplicate purchases. This might be related to thinking that leaving Checkout equates to "emptying my cart" or not understanding that clicking a CTA in our product adds an item to the user's cart.

#48335 deals with making it easier to edit the cart from within Checkout, but we might also want to add an option when a user clicks the "X" to close Checkout (and possibly the browser's back button), to empty their cart or leave it alone. We could use a similar modal to that of the one that's shown when removing an item from their cart:

<img width="1329" alt="Screen Shot 2021-03-30 at 12 28 21 PM" src="https://user-images.githubusercontent.com/942359/113024666-03fb9880-9155-11eb-82ee-6bf7b14af234.png">

@olaolusoga, I believe this would need some basic design input.

**Comment by zdenys** [comment]
I've been seeing several reports from users confused about how to empty the cart. 4219885-zd-woothemes

**Comment by michaeldcain** [comment]
@zdenys: we made it easier to empty the cart in #52850 (as the video in the ticket shows). This issue is related to exiting the cart. Can you give more context as to why the users are having an issue emptying their carts? The trash icon is now always shown and quite evident. We could make it a text link, but I'm inclined to think that it'd be more likely to be missed.

**Comment by zdenys** [comment]
>Can you give more context as to why the users are having an issue emptying their carts? The trash icon is now always shown and quite evident.

I cannot tell for sure. Could it be that the message banner about the presence of purchases in the cart is not actionable enough to them? It is clear enough to me though since it has the link `View your cart`.

![image](https://user-images.githubusercontent.com/39308239/130210858-b987ac1e-bc3e-4c3d-83a4-1925a44d3f2f.png)

Could it be that that banner is not displayed on all screens in Calypso and not consistently, so they don't know how to bring it up and visit the cart directly? 

It does display in My Home the first time I log in, but then if I visit another section and go back to My Home, no banner is displayed. 

https://user-images.githubusercontent.com/39308239/130211816-a52ec5bc-8d44-4272-9fd2-a56b9468fe3a.mov

Only if I go to WordPress.com > My Sites > Upgrades section, I can see the flashing Cart icon. But as an HE I know I can find the cart there, but users may not know it.

![image](https://user-images.githubusercontent.com/39308239/130211598-dcf04f55-ef6c-49cd-9751-5b45c9b0073f.png)

I don't have an accurate answer, but those are my observations. 

Possibly this deserves a separate issue to be opened since it's not specifically about the Checkout but about how to actually get to it?

**Comment by donalirl** [comment]
To date, we have had over 3,000 customers contact us in chat with confusion over the abandoned cart notification. Here is a recent example: #14081679-hc

I think that emptying the cart upon exiting checkout is a helpful solution that would prevent customers from needing to contact us about this. Is there scope to bump up the priority on this one @michaeldcain?

**Comment by zdenys** [comment]
Here is another case 4272626-zd-woothemes of a confused user:

>Once logged in to my website. Found that there is an invoice payable. Is this
correct?
Also, I usually pay in November every year.
Please, advise.

And I can see that they have something in their checkout cart:

![image](https://user-images.githubusercontent.com/39308239/132093812-93c6df09-2a5a-499a-b6d0-db25d6e42398.png)

**Comment by michaeldcain** [comment]
> Could it be that that banner is not displayed on all screens in Calypso and not consistently, so they don't know how to bring it up and visit the cart directly?

I'm not inclined to add the abandoned cart notice to more screens, since it and the related emails are often cited as the primary source of confusion for our users. Instead, we'll be adding a persistent cart to the app in #52890 (issue #48334), and possibly removing the notices around the same time.

In the meantime, is there better wording for the message? We last updated it in #35753 (from "complete your purchase" to "view your cart").

**Comment by zdenys** [comment]
>I'm not inclined to add the abandoned cart notice to more screens, since it and the related emails are often cited as the primary source of confusion for our users.

I would not suggest that either.

>Instead, we'll be adding a persistent cart to the app in #52890 (issue #48334), and possibly removing the notices around the same time.

This sounds like a better direction indeed.

>In the meantime, is there better wording for the message? We last updated it in #35753 (from "complete your purchase" to "view your cart").

I don't have data to support the idea that changing the wording would lead to less confusion. So I'm not sure it's worth the time/effort which instead could be used for higher priority / more impactful tasks (e.g. the persistent cart icon solution you mentioned).

**Comment by michaeldcain** [comment]
To get back to the original suggestion for this issue, let's show a modal when the user clicks the "X" to leave Checkout and still has items in their cart. It would read something like:

> **You are about to leave Checkout with items in your cart**
> You can leave the items in the cart or clear your cart.
> [Clear cart (secondary)] [Leave items (primary)]
