### ISSUE TITLE
Jetpack Connect: Reduce requests to check if site can be connected

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#5156]
I'm not sure if this was by design or not, but as is, the connection process makes up to 6 API requests to test if a site can be connected.

![screen shot 2016-05-02 at 9 35 24 am](https://cloud.githubusercontent.com/assets/1126811/14957203/a465ff50-1049-11e6-9e4f-92f14f834154.png)

Since each request is to the same endpoint, I would think that we'd make one request and then handle the responses client side. It doesn't look like this would be too hard since the API already returns the information for each filter in an object with the filter's name.

ex. –

```
{
  exists: ,
  isWordPRess: ,
  etc
  ...
}
```

cc @johnHackworth

**Comment by johnHackworth** [comment]
It's very much by design :)

Browsers can make 6 simultaneous http calls of the same type (here, XHR). Since we are hitting our own API here, where we use PHP, and each check usually requires non-async operations (db checks or other URL hookups), dividing it in 6 different requests help us reducing the total time. Something like this:

![image](https://cloud.githubusercontent.com/assets/1554855/14957456/bd808b86-1085-11e6-8374-05f4fb057d99.png)
(Behold my inkscape amazing skills!)

**Comment by johnHackworth** [comment]
(well, TBH, in practice it's more like this:
![image](https://cloud.githubusercontent.com/assets/1554855/14957515/0a6c597a-1086-11e6-8b5c-19bfe456a931.png)

Some of the requests take much longer than the others, so the difference is not as spectacular... but for edge cases, it helps to have them separated)
