### ISSUE TITLE
Free Atomic: Do not allow Additional CSS

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51589]
### What plan tier is the site on?
Free

### Where are you seeing the issue?
This feature is in the customizer found at Appearance > Edit CSS

#### What I expected on the Atomic site
To show some sort of upgrade notice, such as the one currently shown: 
![image](https://user-images.githubusercontent.com/7129409/113171599-9fecd900-9215-11eb-8e1a-809b15032e26.png)

#### What actually happened
Additional CSS is enabled.

**Comment by BogdanUngureanu** [comment]
Since users right now cannot upgrade to Premium on Free Atomic sites, should we replace the `Premium` with `Business`? Maybe something like would be more helpful:
> Purchase a Business Plan to activate CSS customization.

cc @olaolusoga

**Comment by tjcafferkey** [comment]
Patch WIP: D61776-code

**Comment by tjcafferkey** [comment]
In Simple sites the Additional CSS feature checks that the users site has the `custom-design-upgrade` option enabled. Our thinking was that we just need to sync this option with the users Atomic site whenever it changes but unfortunately when the Atomic transfer happens this option does not transferred. Meaning if we took this approach it would only work for sites transferred **after** this fix.

As an alternative approach we are going to have to check the sites plan level and if it's above Free then allow then access otherwise show them a similar nudge to what Simple sites get.

**Comment by pablinos** [comment]
Could you trigger a sync if the option wasn't there? It would be another API request, which would slow things up the first time, but it would also safeguard against the option being deleted/corrupted in some way.
