### ISSUE TITLE
Free Atomic: Premium Themes

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51590]
### What plan tier is the site on?
Free

### Where are you seeing the issue?
/themes/site

#### What I expected on the Atomic site
Only themes available to Free users are available. 

#### What actually happened
Not seeing upgrade banners? 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/7129409/113172229-39b48600-9216-11eb-9ba0-c390b70cc214.png)

**Comment by ianstewart** [comment]
@dereksmart do you have a screenshot of what you expected to see vs what you saw? And/or steps to reproduce the issue?

It sounds the issue is that you expected to see a Premium Themes banner on a Free Plan but didn't?

**Comment by kwight** [comment]
We likely have logic somewhere saying "if on Atomic, you get all Premium themes!" – which is no longer the case with free plans on Atomic. 🙃

**Comment by kwight** [comment]
@dereksmart Hey! Was this something you're trackign for yourselves, or something you need help with from our pod?

**Comment by mmtr** [comment]
I think things have been improved in last weeks, since I do see the upgrade banners now on my Free Atomic site. However, there are still some differences on how individual themes are presented:

Simple (Free) | Atomic (Free)
--- | ---
<img width="1264" alt="Screen Shot 2021-05-27 at 12 10 35" src="https://user-images.githubusercontent.com/1233880/119808952-e8a6d280-bee4-11eb-9470-a8e0c12ea145.png"> | <img width="1281" alt="Screen Shot 2021-05-27 at 12 10 43" src="https://user-images.githubusercontent.com/1233880/119808964-eba1c300-bee4-11eb-9cf1-c36722e231da.png">

**Comment by mmtr** [comment]
@DustyReagan not sure if you're actively working on this (the issue is still in the backlog status column rather than in progress), but thought it might be helpful to share some notes:

- After reinstating the Premium Themes into WordPress.com, https://github.com/Automattic/wp-calypso/pull/58818 added back the `Unlock ALL premium themes with our Premium and Business plans!` upsell nudges, but only for Simple sites.
- Free Atomic sites don't display any Premium Themes upsell banner at all. Instead we show a "Upload your own themes with our Business and eCommerce plans!" message: <img width="600" alt="Screen Shot 2022-02-08 at 15 49 29" src="https://user-images.githubusercontent.com/1233880/153011513-744921c2-d6f3-446c-9850-e5fd0410db0a.png">

- Since Premium plans are still unsupported by Atomic, I think we could adapt the [wording of the current upsell for Atomic](https://github.com/Automattic/wp-calypso/blob/58e493d98906691fddbf28a04878c8a2bb3ab8d7/client/my-sites/themes/single-site-jetpack.jsx#L58) to clarify that Premium Themes are included on Business plans as well. Something like `Unlock ALL premium themes and upload your own themes with our Business and eCommerce plans!` could work.

**Comment by DustyReagan** [comment]
I'm still researching what's going on with the [individual themes](https://github.com/Automattic/wp-calypso/issues/51590#issuecomment-849512348). Meanwhile I went ahead and created a [PR for the upsell nudge copy change](https://github.com/Automattic/wp-calypso/pull/60939).

**Comment by DustyReagan** [comment]
I [created a PR](https://github.com/Automattic/wp-calypso/pull/60980) to address the [missing individual themes price and upsell nudge](https://github.com/Automattic/wp-calypso/issues/51590#issuecomment-849512348) on Atomic issue. Definitely needs some 👀 as it was quite a bit more complex than I expected.

I also noticed that themes are not installing on sub Business Atomic sites. I'm thinking that should be a [new issue.](https://github.com/Automattic/wp-calypso/issues/60981)

**Comment by mmtr** [comment]
Noted one more difference: the upsell nudge on individual pages of themes is missing on Free Atomic sites:

Simple (Free) | Atomic (Free)
--- | ---
<img width="789" alt="Screen Shot 2022-02-10 at 11 23 19" src="https://user-images.githubusercontent.com/1233880/153388203-e5a39bb4-1137-48db-a8a0-9ee83f1b57aa.png"> | <img width="822" alt="Screen Shot 2022-02-10 at 11 23 25" src="https://user-images.githubusercontent.com/1233880/153388217-73d9e739-2906-4a8e-9019-a0ab5aa4e33b.png">
