### ISSUE TITLE
Free Atomic: File storage - Adhere to limits

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51594]
Free : 3GB
Personal : 6GB
Premium : 13GB
Business/ e-Commerce : 200 GB

These limits need to be enforced and taken into consideration before a site moves to a Free tier of Atomic.

### What plan tier is the site on?
Free

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/7129409/113174298-3c17df80-9218-11eb-9be1-fdaea68dd876.png)

**Comment by ddc22** [comment]
@dereksmart I installed yoast on a free site, however the capacity remains as 3 GB. Does this mean that this issue does not exist?
![image](https://user-images.githubusercontent.com/3422709/113666864-8e9c4480-96cd-11eb-932b-111363475f44.png)

**Comment by dereksmart** [comment]
@jdc91 Great question. We'll need to make sure it's not just the client-side (Calypso) that shows 3GB, and that those limits are enforced server-side. 

More info p58i-aeR-p2#comment-50015

**Comment by allilevine** [comment]
> We'll need to make sure it's not just the client-side (Calypso) that shows 3GB, and that those limits are enforced server-side.

The sites/site/media-storage API endpoint is returning the correct limit (3GB) but the limit does not seem to be enforced, at least on a free Atomic developer blog. I was able to upload 3.5GB and check the disk usage via SSH.

**Comment by allilevine** [comment]
I've opened a patch to show a more accurate quota / limit on the Media page: D62589-code

Next step is to figure out how we change that quota when upgrading / downgrading plans.

**Comment by jmdodd** [comment]
Atomic infrastructure will be able to support changing the space quota from the default on both provision and update. This work is in progress, but requires some careful planning to avoid unnecessary over quota systems alerts.

**Comment by allilevine** [comment]
I'm suspending work on this one for the time being since we've changed focuses.

**Comment by obenland** [comment]
Todo from #59742 

Update the transfer manager and any eligibility checks to account for different plan level values, at the moment only business level restrictions are checked.

- [ ] `Transfer manager::can_be_transfered()`
- [ ] ` woa_transfer_validate()`
- [ ] Confirm eligibility is checked during /initiate-transfer api call

**Comment by jmdodd** [comment]
What is the expected behavior for a site with a Free plan but 6 GB of media uploaded while it had a Personal plan (example)? Should this site be eligible to upgrade/transfer?

**Comment by obenland** [comment]
Discussed this in the Limited Atomic planning and agreed to
* put in the effort to get this right, rather than to continue papering over storage limits
* tell customers the actual space they use to limit surprises
* do more research on how we communicate the need for plan upgrades for sites that exceeded storage

**Comment by mreishus** [comment]
I've been researching this and it's definitely not as simple as setting the `blog_upload_space` option, like we do on simple.

## I believe our next steps are:

* Change the Atomic `create-site` API to accept a variable representing the amount of space to be set as disk-quota when making the new site.
  * This is being tracked here: p9o2xV-1ht-p2
* Change the Atomic transfer code to examine a site's plan, determine the amount of space to be provisioned based on the plan, and to pass that argument to the `create-site` call.
  * We may want to add some sort of buffer or allowance beyond what's provided by the plan. For example, a personal plan may give you 6GB. That represents 6GB of media on simple, but on Atomic, the WP code, all themes and plugins also count against that 6GB. 
* We will have to address the problem of a user having storage over their limit when making an atomic transfer: It literally wouldn't fit and the transfer would fail.
* Plan changes while already on atomic (upgrade and downgrade) will need to call the Atomic API to adjust their available disk space.
* We need to make sure the user has a good idea of how much space they're using, what their limit is, and how close they are to going over. Maybe some sort of alert email if this doesn't already exist?
* If possible, address the systems team needing to take manual intervention when a site goes over the limit. Is this possible?
  * Things like the media endpoint could stop accepting uploads when the user is at 95% of their limit, for example. But I don't think we can stop plugins from writing to disk.
 

## Various scattered notes

### Approach

* WP.com uses the blog option `blog_upload_space` to control how much media is able to be uploaded.
  * This doesn't have any bearing on Atomic sites disk usage, it only exists in their Jetpack cache tables. It only controls videopress uploads.
* Atomic platform sites have a disk quota: All sites are provisioned with 200GB.
  * We may use the Atomic API to adjust this ( 2b8ea-pb ).
  * We could modify `create-site` to take a parameter that specifies the disk space available when creating an atomic site. This way, we could create new sites with a disk limit less than 200GB.
  * Note that simple sites, "6GB" of space only relates to the media the user has uploaded. They get the WP codebase, plus plugins and themes "for free". On the atomic platform, WP code, plugins and themes count against their disk space quota. We may need to add some sort of extra allowance or buffer here.
  * The Atomic disk limit is a hard limit. Once a site goes over the limit, it is no longer allowed to write to disk. The systems team must intervene and take action, as this prevents automatic updates to plugins, themes, and wp, as well as disrupting other processes.
    * We may have to come up with a solution for this. With lower limits like 3gb or 6gb, users will run into them much more often than 200gb, and we probably don't want to be disrupting the systems team by having them intervene whenever this happens.
  * It's unknown if calypso or WP-Admin UIs report on space used on atomic sites to the user, or what their current disk quota limit is.
  * While the media upload endpoint can check for limits, plugins are incredibly powerful and can do things like `file_put_contents()`, which write files directly to disk. This can't really be stopped by anything other than a hard limit.

*I wrote a lot of the stuff below when I still thought `blog_upload_space` and `max_storage_bytes` were important to limiting atomic usage.*

### Variables of note

* Option `blog_upload_space` or "Blog Upload Space"
  * I seem to remember this "not mattering" on Atomic.
* Option `max_storage_bytes` or "Site Upload Space Quota"
  * "mostly visual" on WPCOM atomic p9F6qB-7Ob-p2#comment-441
* Function call `get_space_allowed()`
  * Core function in wp-includes/ms-functions.php, Filterable, unsure if overridden in atomic (or even called - Atomic isn't multisite is it?)
* Linux disk quota assigned to an atomic site, on the platform level  
  * API Description here 2b8ea-pb : site-meta has a key 'space_quota' that can be get/set
  * The source of truth for “how much space is an Atomic site allowed to use” is the platform setting the zfs space_quota site meta that is done via the Atomic API.
  * The source of truth for “how much space an Atomic site is using on an Atomic pool server” is approximately the space_used site meta that is updated every 12 hours.

### Endpoints to check

* GET https://public-api.wordpress.com/rest/v1.1/sites/<SITE>/media-storage?http_envelope=1
* ` switch_to_blog( <SITE> ); print_r( get_option( 'blog_upload_space' ) ); `
* ` gpr SELECT * FROM wp_<SITE>_options WHERE option_name = 'blog_upload_space'; `
* ` switch_to_blog( <SITE> ); print_r( get_space_allowed() );`
* ` require_lib( 'wpcom-sites-on-atomic' ); print_r( get_atomic_site_by_blog_id( <SITE> ) );`
* ` print_r( WPCOM_Sites_on_Atomic::get_site_meta( <SITE>, 'space_used' ) ); `
  

### Space Adjustments on Atomic Transfer

* Back in 2020 I changed all atomic transfers to update blog_upload_space to 2TB on xfer to allow for unlimited videopress uploads in D50029-code . I believe this adjustment was only made in the Jetpack cache tables.
  * This was moved into a post-transfer job in Dec 2021 D71080-code  | p9o2xV-1D4-p2#comment-5322 | p9F6qB-7iw-p2
  
### Current Behavior

I used diffs in 2b8da-pb to allow a newly created personal plan simple site to be xferred to atomic. Before the transfer, its blog_upload_space was 6,144 MB.
After the transfer:
  * I do not see a blog_upload_space option when visiting `/wp-admin/options.php` on the site. (In contrast, I do see it on one of my simple sites).
  * The MC report card page has an html comment telling me that the Jetpack cache table value for blog_upload_space is 6,144 MB.
    * I actually expected to see 2TB here. Maybe the post-transfer code checks for the videopress product?
    * The job uses videopress_post_transfer_set_blog_upload_space(), which checks woa_has_atomic_subscription(). If that passes, the blog_upload_space is set to 2TB. (Here, we'd need to change this, since some atomic plans will have videopress, and others won't: https://github.com/Automattic/wp-calypso/issues/60727 )
  * /rest/v1.1/sites/<SITE>/media-storage reports max_storage_bytes:6442450944 , or 49,152 MiB or 48 GiB
  * switch_to_blog( <SITE> ); print_r( get_option( 'blog_upload_space' ) ); = 6144
  * switch_to_blog( <SITE> ); print_r( get_space_allowed() ); = 6144


### Debugging space allowances on atomic sites

Great comment here p9F6qB-7Ob-p2#comment-44149

**Comment by obenland** [comment]
Thank you for this detailed update @mreishus! 

In Planning we said we should start with improving the experience on Atomic before turning to plan up/downgrades and transfers. Looking through the list of next steps you outlined, I'm thinking it would make sense to not limit us in that way for the upload space work, but rather fix it in all stages.

> Change the Atomic transfer code to examine a site's plan, determine the amount of space to be provisioned based on the plan, and to pass that argument to the create-site call.

Rather than checking the plan, I wonder if we could check for an upload space feature/upgrade to decouple this from plans?

> the media endpoint could stop accepting uploads when the user is at 95% of their limit

Putting on my product hat, I like your suggestion of a buffer or allowance beyond what's provided by the plan better. I could see customers becoming frustrated if they can't use all the space they purchased.

@jmdodd How does that list of next steps look like for you? Should we postpone the "Plan changes while already on atomic" bullet point?

**Comment by mreishus** [comment]
> Rather than checking the plan, I wonder if we could check for an upload space feature/upgrade to decouple this from plans?

Yes, this should work. Plans are bundles of products, and I believe the current plan definitions match what we want. Personal comes with WPCOM_SPACE_3GB, which represents 6 gb of space, and Business+Ecommerce come with WPCOM_SPACE_100GB, which represents 200gb of space.

**Comment by mreishus** [comment]
In my testing, simple sites are accurately reporting storage used: :heavy_check_mark: 
*  through the storage-media endpoint, 
* in the UI displayed to the user in the calypso media gallery 
* in the UI displayed to the user in  wp-admin upload.php

They are also preventing uploads that would go beyond their allotted space. :heavy_check_mark: 

The functions being used are `get_space_allowed()` and `get_space_used()`. What's checked is in what's in the directory returned `wp_upload_dir()`.

**wp-admin warning - not much space left**
![2022-02-02_12-37](https://user-images.githubusercontent.com/937354/152219738-3f3cb6e6-e706-4449-b772-528ced2275fb.png)
**calypso warning - not much space left**
![2022-02-02_12-37_1](https://user-images.githubusercontent.com/937354/152219779-38cd4233-9a85-41b9-9962-4d7438968e6f.png)
**wp-admin upload failure - not enough space left**
![2022-02-02_12-46](https://user-images.githubusercontent.com/937354/152219865-0fada874-e7c0-482d-819e-c752b10db182.png)
**calypso upload failure - not enough space left**
![2022-02-02_12-55](https://user-images.githubusercontent.com/937354/152220046-681edb8b-1476-432f-92b2-9d1a7aaffec2.png)
![2022-02-02_13-01](https://user-images.githubusercontent.com/937354/152220205-ff0eaa04-4a0a-4f56-9f52-3a01ac1a73d5.png)

So far, all looks good on simple. 
On Atomic, I'm unsure of the situation; it might be that the storage space used by themes and plugins is not accurately reported to the user, or perhaps other data written outside of the upload directory (for example, caching plugins writing files).

**Comment by mreishus** [comment]
## Investigating Atomic storage reporting

### Media Endpoint Storage Reporting (Atomic)

The media endpoint is used by calypso to display the space used and available in the calypso media page:
<img width="230" alt="Screen_Shot_2021-06-09_at_1 42 21_PM" src="https://user-images.githubusercontent.com/937354/152244671-44e8450d-a318-41d3-bd84-51d429193b01.png">

I had a personal **simple** site with a ~400MB file uploaded. The `/media/<site>` endpoint returned:
```
max_storage_bytes:6442450944 = 6144mb
storage_used_bytes:432002925 =  411mb
```
After transferring to atomic, the same `/media/<site>` endpoint returned:
```
max_storage_bytes:214748364800 = 200gb (want to eventually see: 6GB + allowance)
storage_used_bytes:0                   (want to see: 411mb)
```
After waiting 12 hours, but uploading no additional files, the same `/media/<site>` endpoint returned:
```
    max_storage_bytes:214748364800 = 200gb
    storage_used_bytes:550802432  = 525mib. The extra ~100mb must come from the wp install, plugins and themes.
```

#### Media Endpoint `storage_used_bytes`

 The media endpoint is driven by `class.wpcom-json-api-media-storage-endpoint.php`, which already has a special case for atomic storage_used_bytes, and checks `WPCOM_Sites_on_Atomic::get_site_meta( $atomic_site_id, 'space_used' );`
The `space_used` is a value updated every 12 hours, and is the closest we have to a source of truth for “how much space an Atomic site is using on an Atomic pool server”.

I did find it odd that directly after my site was transferred, it reads as 0, even though a 400MB file did land in my wp-content/uploads directory. I am assuming this will correctly be updated the next time the 12 hour update runs. If this is why it's 0 right now, **I wonder if it's feasible to have the job run once right after the transfer process to populate this with a value right away?**

#### Media Endpoint `max_storage_bytes`

We're still working on provisioning atomic sites with the correct amount of storage, so not a lot to say here.

The media endpoint is checking `get_space_available()`. I don't know if this is accurate on the atomic platform. Allison's patch D62589-code changes this to look at the `WPCOM_Sites_on_Atomic::get_site_meta( $atomic_site_id, 'space_quota' );` value. This looks promising.

### WP-Admin Upload

wpcomsh adds a message that displays on the `pre-upload-ui` action. The message gets values from `wpcomsh_get_at_site_info()`, which read `space_used` and `space_quota` from a special file on disk. My site didn't have this yet; maybe it's set by the 12 hour process, I will have to see if it shows up on my site.

One potential pitfall is that the values read only update every 12 hours. I might see the message "You are currently using 4GB out of 6B upload limit.", then upload 1.5GB worth of stuff, and still see the message say 4GB/6GB instead of 5.5GB/6GB.

### Site Health

Atomic users can visit `/wp-admin/site-health.php`, which does include a detailed breakdown of directory size for WP, uploads, plugins, and themes. I believe it also tries to grab info from `wpcomsh_get_at_site_info()`, which contains the important `space_used` and `space_quota` values, but my site doesn't have them yet. Will have to check later.

Edit: Checking >12 hours later, my site health page now shows "Disk space used" and "Disk space quota", and stopped displaying "Total installation Size". Interestingly, my "Total Installation Size" was ~610MB, but the "Disk space used" is only 525MB. Perhaps this means that the 12 hour updating `space_used` variable can account for deduplication through symlinks of themes, but the "Total Installation Size" cannot.

### Conclusion

* After we have <200GB Atomic sites available to test with, we will have to **adjust the media storage endpoint**'s reporting of `max_storage_bytes` to check the `space_quota` value.
  * It's possible this is already working? That's why I would like a smaller provisioned atomic site to check.
* After we have<200GB Atomic sites: **Check enforcement and develop a user friendly solution**. 
  * If my site has a 6GB disk quota, I could theoretically upload data until the site hits the quota and linux is no longer able to write to disk, but that would be really messy, since it would prevent various essential processes from working (like automatic updates to themes, plugins and wp) and require manual intervention from systems.
  * We want a way to prevent the user from filling up their entire disk quota with uploads, and even if the user is doing uploads one after another without waiting 12 hours between each one. So we need some sort of "soft" limit, and it can't be too dependent upon the `space_used` value, because that only updates once every 12 hours.
    * If we had a timestamp for the last `space_used` update, maybe we could keep a running estimate of all of the data uploaded since the last update somewhere else? Like an `estimated_space_used_delta`, and our best guess would be `space_used` + `estimated_space_used_delta`.
    * Or, maybe we could check the file sizes directly, through a different mechanism. `site-health.php` was able to find a "Total installation size" of 610MB on my site, which is correct (200MB for WP+Themes+Plugins and 400MB for my uploads directory), even though `wpcomsh_get_at_site_info()` is not returning any information and `space_used` and `space_quota` are not available for my site yet. Could we use whatever `site-health.php` is doing?
* After 12 hours have passed, I should check my site to see if the `storage_used_bytes` is correctly reflecting the 400mb file I have uploaded. Additionally, verify that the `space_used` and `space_quota` values are appearing in the site health section.
  * Edit: Updated previous parts of this note with the values 12 hours later. `space_used` and `space_quota` are indeed now populated.

**Comment by mreishus** [comment]
## Accurate reporting of space quota: Done

* Merged: 829-gh-Automattic/wpcomsh [Remove hardcoded space quota of 200GB]
* Deployed: D62589-code [Media Storage Endpoint: Check space_quota for Atomic sites]

**Calypso shows 3 gig available**
![2022-03-01_10-39](https://user-images.githubusercontent.com/937354/156218852-3ee96cd7-6cb2-42c0-9ff3-31c24247ef9f.png)


**WP-Admin shows 3 gig available**
![2022-03-01_10-58](https://user-images.githubusercontent.com/937354/156218811-5873bd53-17ed-4e5f-a39c-b15831af1a29.png)


## Space used on 12 hour lag

The calypso upload, wp-admin upload, and site health pages are accurately reporting space quota below 200GB now.
The biggest issue looks to be that the "space used" numbers update once every 12 hours.  Here's an example of the upload pages before and after I upload a 400MB file:

**Before upload: Accurate report of 760/3000**
![2022-03-01_10-58_1-before-upload](https://user-images.githubusercontent.com/937354/156218525-5dd80419-3491-4bfe-9424-3c539905a87e.png)

**After upload: Inaccurate report of 760/3000 (wp-admin)**
![2022-03-01_11-22-after-upload](https://user-images.githubusercontent.com/937354/156218620-4124bbd6-f4ee-44db-b4bf-b153bc290d1e.png)

**After upload: Inaccurate report of 760/3000 (calypso)**
![2022-03-01_11-23-after-upload-media](https://user-images.githubusercontent.com/937354/156218664-25d1ca4b-9fbd-463c-8108-faf3e118a84a.png)

**Comment by obenland** [comment]
> The biggest issue looks to be that the "space used" numbers update once every 12 hours.

My understanding is that that's just the way it is? Or do you think there's something that can be improved here?

**Comment by mreishus** [comment]
> My understanding is that that's just the way it is? Or do you think there's something that can be improved here?

We can't track all changes written to disk, but we can track file uploads (a main source of storage used). In my testing, these filters accurately captures the number of bytes written to disk on file uploads:
```
my_add_attachment( $attachment_id ) {
        $file = get_attached_file( $attachment_id );
        if ( $file ) {
                $bytes = filesize( $file );
                error_log( "my_add_attachment: Uploaded file size of " . $bytes );
        }
}
add_action( "add_attachment", 'my_add_attachment', 10, 1 );

function my_generate_attachment_metadata( $metadata, $attachment_id ) {
        $file = get_attached_file( $attachment_id );
        if ( $file ) {
                $bytes = filesize( $file );
                error_log( "my_generate_attachment_metadata: Uploaded file size of " . $bytes );
        }
}
add_action( 'wp_generate_attachment_metadata', 'my_generate_attachment_metadata', 10, 2 );
```

I think we could track a "estimated space used since last 12-hour update" variable, using these rules:
* On file upload, set `$estimated_space_used += $file_bytes`
* On file delete, set `$estimated_space_used -= $file_bytes`
* When the 12 hour update happens, set `$estimated_space_used = 0`
* When wpcomsh and media endpoint report space used, use `$site_info['space_used'] + $estimated_space_used`

The benefit would be stopping users from running into the hard limit of the linux disk quota. Currently, if I continue to upload files to my site, nothing in the application layer will stop me until I fill up the site's disk quota. When that happens, additional bytes will not be able to be written to disk, causing normal maintenance processes to fail, and manual intervention from the atomic team will be required to fix the site.

On the downside, it's additional code, additional complexity, I'm not sure if we have a way to hook a change on the 12 hour update, and the estimated space used would probably have to be stored in a blog option. Should we have a discussion with @jmdodd about pursuing this path?

**Comment by obenland** [comment]
@jmdodd Would you anticipate the scenario of a customer filling their upload quota within the 12 h window to be so likely that we should find ways to prevent it?

(This may read like a loaded question but it's not. I'm genuinely curious and happy to fix 🙂)

**Comment by jmdodd** [comment]
I think there are higher priorities at this time. Doesn't mean we can't pursue this part of the UX later, but there are more critical path issues that are a lower lift.

In general, if a customer fills their quota in under 12 hours, there are probably other factors at play.

**Comment by mreishus** [comment]
I think we're basically done then. I just need to bring my site within close distance of the limit, wait until the next day, and verify that I'm no longer allowed to upload large files after the space used has caught up.

**Comment by obenland** [comment]
Thank you so much for driving this forward and getting it to this point @mreishus!

**Comment by mreishus** [comment]
Yesterday, I left my site with 200MB left. Today, I tried to upload a 400MB file through wp-admin and calypso:

**wp-admin blocked the upload and did not write to disk.**
![2022-03-03_09-53](https://user-images.githubusercontent.com/937354/156650026-851682aa-1f51-4990-b89b-e3057a716a5c.png)

**calypso let the upload go through, wrote the file to disk, and let the disk space used hit the quota**
Alerts etc were fired.
![2022-03-03_14-46](https://user-images.githubusercontent.com/937354/156650228-c7a7ac92-e5db-420d-bcbc-bf32efd02090.png)

Calypso on simple blocks uploads when it detects there is not enough space allowed, but Calypso on atomic uses a different path which doesn't do any space checks, anywhere. I'm figuring out how the path works and looking for a simple place for wpcomsh to add a hook.

**Comment by mreishus** [comment]
When using calypso to upload a file to an atomic site, I couldn't find anywhere in the code path that checked for file sizes. Simple has this check, but WoA does not.
I was able to block uploads that would bring me over the quota by adding a filter in jetpack, and implementing that filter in wpcomsh. Example: https://github.com/Automattic/jetpack/pull/23229 + 832-gh-Automattic/wpcomsh

**Comment by mreishus** [comment]
https://github.com/Automattic/jetpack/pull/23229 + 832-gh-Automattic/wpcomsh
Have both been merged, allowing uploads through Calypso to be blocked when the site is close to the quota limit.
This should be addressed now, with the note that we have to wait 12 hours for all space_used updates.
