### ISSUE TITLE
Nav Unification: Simple sites are seeing the core Themes page instead of the Calypso themes showcase.

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#51663]
### What plan tier is the site on?
Business
### Where are you seeing the issue?

1. Toggle on `Advanced Dashboard Pages` in https://wordpress.com/me/account 
2. Navigate Appearance > Themes
3. See no `Add new`, `Add new theme`, or `Upload` button

### What I expected on the WordPress.com site
See `Add new`, `Add new theme`, or `Upload` button to add a third-party theme
#### What I expected on the Atomic site
I can see `Add new`, `Add new theme`, and `Upload` buttons
#### What actually happened
No no `Add new`, `Add new theme`, or `Upload` buttons are displayed
#### Is this specific to the applied theme? Which one?
No
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
**Simple Site**
![](https://d.pr/i/FFn2pI+)
_Link: https://d.pr/i/FFn2pI_

**Atomic site**
![](https://d.pr/i/G9gzra+)
_Link: https://d.pr/i/G9gzra_

**Comment by zdenys** [comment]
Encountered in 3837900-zd-woothemes

**Comment by BogdanUngureanu** [comment]
Since the site is still a simple site, these pages are not available. In my opinion, `Add new`, `Add new theme`, or `Upload` could be linked instead to `https://wordpress.com/themes/upload/:site-name` where the user will be prompted with this confirmation message:

> By installing a theme the following change will be made to the site:
WordPress.com Subdomains: Your subdomain will change from demo-site.wordpress.com to demo-site.wpcomstaging.com.
Questions?: Contact support for help.

After that, the user will have access to the theme upload menus they will be migrated to AT.

**Comment by cpapazoglou** [comment]
This is a regression. We should always show the Calypso Themes screen for Simple sites.

**Comment by sixhours** [comment]
Started a diff for this in D59926-code

**Comment by kwight** [comment]
https://github.com/Automattic/jetpack/pull/19509
