### ISSUE TITLE
PDF Embeds: file loads incorrectly on iOS

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#51664]
### Steps to reproduce the behavior

1. Embed a PDF file on a post or page https://wordpress.com/support/embedding-a-pdf-file/
2. Open the page/post on an iOS device

#### What I expected to happen

The PDF should load as an embed  as it does on desktop, or it should load as a downloadable link like on Android

#### What actually happened

The file displays only the first page of the PDF, with no option to scroll on multi-page files. The content of the PDF is displayed against the site's background, ignoring the PDF's background.

![Screenshot](https://d.pr/i/N8UjSV+)
Screenshot: https://d.pr/i/N8UjSV

Pages:
- Simple: P6VVUQ-Ba-p2
- Atomic: https://atlivio.wpcomstaging.com/pdf/

#### Browser / OS version

Tested on an iPad Air 4 running iOS 14.4. Chrome and Safari apps in their latest versions.

#### Is this specific to the applied theme? Which one?

All themes

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact

Medium. It handles PDF embeds (not common) unusable on an entire operating system (very common).

#### Reproducibility

Consistent

**Comment by rw-ye** [comment]
Customer report of this issue here: 4451703-zd-woothemes

**Comment by Robertght** [comment]
Still an issue. 
I tested with on a iPad Pro with iOS 15, Chrome and Safari.

**Comment by brookewp** [comment]
Another report here: hc-32877576

**Comment by thekingsprojects** [comment]
Another here: 4555202-zen

**Comment by sejas** [comment]
I've been testing the issue. Here are my findings.
The issue comes from WPcore/Gutenberg and the current limitations to rendering PDF previews on mobile devices.

There is a reported issue on Apple's Developer Forum about this limitation on iOS.
https://developer.apple.com/forums/thread/649982
I've tried using only the slashes without `https:`, and the problem persists.

Testing on Android, I can see an empty space instead of the PDF preview or the first-page image.

I've also found this interesting conversation in the original PR:
- https://github.com/WordPress/gutenberg/pull/24233#issuecomment-665493901 wich suggests a workaround hiding the preview for specific user agents https://github.com/WordPress/gutenberg/commit/1c40e28cfb31116b2c795dab7914012b1b69b1b9

## Screenshots
| **iOS** | **Android** |
|---|---|
|![ios](https://user-images.githubusercontent.com/779993/206226850-cbe64c35-0551-44a9-99a5-fb857c55aae3.PNG)|![android](https://user-images.githubusercontent.com/779993/206227515-a6cd7cad-c76a-4ad5-8150-e91eca89c5ef.png)

The Preview can be disabled, showing only the "download" buttons.
<img width="280" alt="Screenshot 2022-12-07 at 15 45 26" src="https://user-images.githubusercontent.com/779993/206270177-93964044-516e-47a7-bbe7-c5a23aad8556.png">

I've created this issue on Gutenberg's repo: https://github.com/WordPress/gutenberg/issues/46382

@liviopv, is it ok to close this issue in favor of the new one on Gutenberg?

**Comment by liviopv** [comment]
@sejas yes, sounds like a good option! Closing for now.
