### ISSUE TITLE
Nav Unification: Edit Page Leads to WP Admin POSTS dashboard When Under "Show Advanced Dashboard Pages"

### ISSUE THREAD

**Issue by darnelldibbles-zz** [Automattic/wp-calypso#51683]
### Steps to reproduce the behavior

1. Enable _Show advanced dashboard pages_ under **Dashboard appearance**
2. Go Directly to wordpress.com/pages
3. Click _edit_ under the ellipsis dropdown of one of the pages
4. Instead of taking me to the edit page, it takes me to WP Admin POSTS dashboard _wp-admin/edit.php_

#### What I expected to happen
I expect to land on my edit page:
![Expected Behavior](https://cdn-std.droplr.net/files/acc_894591/skRQPt)

#### What actually happened
Instead of taking me to the edit page, it takes me to _wp-admin/edit.php_
![screen capture](https://cdn-std.droplr.net/files/acc_894591/VO4fMf)

### Context
Reported by our moderator in the WordPress.com forums: 
https://wordpress.com/forums/topic/new-navigation-oddity/
#### Browser / OS version
N/A. This appears to impact all browsers.

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
This affects both simple and atomic sites.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It happens on all sites. Anyone who either clicks on a hyperlink to http://wordpress.com/pages or types and goes directly to http://wordpress.com/pages while _Show advanced dashboard pages_ is enabled will encounter this

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See above.

**Comment by obenland** [comment]
How odd. It has the right link on the posts list, but for pages it's an Edit button, not a link.

**Comment by cpapazoglou** [comment]
Since these changes https://github.com/Automattic/wp-calypso/pull/51108, we redirect users to WP Admin for new or existing posts / pages when the toggle is enabled.

**Comment by obenland** [comment]
Sure. The issue is not that it redirects to wp-admin, it's that it redirects to the pages list instead of the editor.

**Comment by sixhours** [comment]
I need to do more testing to be sure, but it looks like the selector we're using to determine the edit URL is `isEligibleForGutenframe`:

https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/my-sites/pages/page/index.js#L209-L216

But I think we need to use `shouldLoadGutenframe` introduced in https://github.com/Automattic/wp-calypso/pull/51108/files#diff-7cc551cd7e2d1dcfcebb6a03fc289568d0b69dddff3653dd1640edf90424412a, which is the new selector that takes nav unification and advanced dashboard settings into account.

Otherwise the resulting edit URL gets passed through `pageRouter`:

https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/my-sites/pages/page/index.js#L396-L399

Which does not work with non-Calypso-style URLs.

The reason Posts work as expected is because the edit link is a direct `href` prop and does not get passed through `pageRouter`.
