### ISSUE TITLE
Media search results only return some results

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#51699]
### Steps to reproduce the behavior

1. Go to Media Library on a site with many files
2. Search for files
3. The Calypso Media Library will only show some results - probably only results from those that were loaded before the search. If searched from https://domain.com/wp-admin/upload.php , search offers many more results.

### Context

3877867-zd-woothemes (site has 2,778 media items)

#### Does this happen on simple or atomic sites or both?

User site is a Atomic site. I don't have a test site with enough media files to test.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Doesn't affect purchases. So far, only reproducible on this user's site. We need a site with many media files in order to test.

**Comment by Robertght** [comment]
Another case in 4862523-zen (site has 5,170 items)

Simple site.

The images show up if you load the editor through the Classic/WP-Admin view.

**Comment by formosattic** [comment]
I was able to reproduce this on a test site with 48 media items, so the issue doesn't seem related to the number of media files.

Calypso just seems to return a smaller set of results.

| Calypso -22 items  | WP Admin - 44 items|
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/160590548-98962f2b-3bc6-405f-a8a6-77f4fe02a732.png)  | ![image2](https://user-images.githubusercontent.com/15944096/160590506-31b22c6c-3371-4c0e-abff-c7f7e64f2ca7.png)  |

This issue was previously reported at https://github.com/Automattic/wp-calypso/issues/15233, so I'll close this one and report the user cases there.
