### ISSUE TITLE
Media Library/Modal: include Pexels and Google Photos as image sources in WP Admin/Classic Editor screens

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#51716]
With Nav Unification, users now have the possibility of completely missing out on our integration with Pexels/ Google Photos if they turn on WP Admin in the dashboard appearance settings and set the Classic Editor as the default editor.

When both of those things are turned on, there's no area that loads the Calypso media modal, so it would make sense for us to try to port those options into the WP Admin modal.

**Additional context**
User case: 28852816-hc

**Comment by obenland** [comment]
> if they turn on WP Admin in the dashboard appearance settings and set the Classic Editor as the default editor.

When customers opt out of two experiences that we're working towards, I think it's reasonable to expect that the result doesn't include every feature that was previously available. We should spend more time on giving customers more reasons to switch back to the better experience than on back-porting features that are otherwise available.

**Comment by obenland** [comment]
I see there's already a docs issue open to update the support page. Let's close this one in favor of setting clearer expectations.
