### ISSUE TITLE
Reblog: A blank post is created if `Show advanced dashboard pages` is active

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#51746]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/me/account and toggle on `Show advanced dashboard pages`
2. Go to Reader and find a post to reblog
3. Click the share icon, and select one of your sites to share to
4. Notice that this triggers the creation of a new, blank post with nothing from the previous post carried through to be shared.

#### What I expected to happen
See the content of the post in the Editor
#### What actually happened
Empty post is created
#### Browser / OS version
Chrome
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Simple
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/39308239/113845351-15205700-979e-11eb-98b8-54c2f76a883b.mov

**Comment by zdenys** [comment]
3886937-zd-woothemes

**Comment by obenland** [comment]
@mreishus Any chance this could be related to recent work on Reblog?

**Comment by cpapazoglou** [comment]
Since these changes https://github.com/Automattic/wp-calypso/pull/51108, we redirect users to WP Admin for new or existing posts / pages when the toggle is enabled. Clicking the Reblog button generates a URL 

`/post/[SITE_ID]?embed=https%3A%2F%2Fwww.youtube.com%2Fembed%2FfZtovVxp67M%3Fversion%3D3%26rel%3D1%26showsearch%3D0%26showinfo%3D1%26iv_load_policy%3D1%26fs%3D1%26hl%3Den-US%26autohide%3D2%26wmode%3Dtransparent&image=https%3A%2F%2Fi0.wp.com%2Fma.tt%2Ffiles%2F2021%2F04%2FIMG_4301-1-1024x723.jpg%3Fquality%3D80%26ssl%3D1%26strip%3Dinfo%26w%3D1600&title=Wix+and+Their+Dirty+Tricks+%E2%80%94+Matt+Mullenweg&text=Wix%2C+the+website+builder+company+you+may+remember+from+stealing+WordPress+code+and+lying+about+it%2C+has+now+decided+the+best+way+to+gain+relevance+is+attacking+the+open+source+WordPress+community+in+a+bizarre+set+of+ads.+They+can%E2%80%99t+even+come+up+with+original+concepts+for+attack+ads%2C+and+have+tried+to+rip-off%C2%A0of%E2%80%A6&url=https%3A%2F%2Fma.tt%2F2021%2F04%2Fwix-dirty-tricks%2F&is_post_share=true`

which redirects to WP Admin
`/wp-admin/post-new.php?post_type=post&calypsoify=1&embed=https%3A%2F%2Fwww.youtube.com%2Fembed%2FfZtovVxp67M%3Fversion%3D3%26rel%3D1%26showsearch%3D0%26showinfo%3D1%26iv_load_policy%3D1%26fs%3D1%26hl%3Den-US%26autohide%3D2%26wmode%3Dtransparent&image=https%3A%2F%2Fi0.wp.com%2Fma.tt%2Ffiles%2F2021%2F04%2FIMG_4301-1-1024x723.jpg%3Fquality%3D80%26ssl%3D1%26strip%3Dinfo%26w%3D1600&title=Wix+and+Their+Dirty+Tricks+—+Matt+Mullenweg&text=Wix%2C+the+website+builder+company+you+may+remember+from+stealing+WordPress+code+and+lying+about+it%2C+has+now+decided+the+best+way+to+gain+relevance+is+attacking+the+open+source+WordPress+community+in+a+bizarre+set+of+ads.+They+can’t+even+come+up+with+original+concepts+for+attack+ads%2C+and+have+tried+to+rip-off%C2%A0of…&url=https%3A%2F%2Fma.tt%2F2021%2F04%2Fwix-dirty-tricks%2F&is_post_share=true`

which makes me wonder if that ever worked in WP Admin. Should we maybe disable this redirect for reblogs?

**Comment by obenland** [comment]
Serenity recently made it work in wp-admin for WoA sites. Maybe we could port that solution back to wpcom for simple sites?
636-gh-Automattic/wpcomsh

**Comment by mreishus** [comment]
I'm also seeing this issue with an ephemeral site, but unlike Harris, when I'm redirected with calypsoify turned on I lost the share parameters.

Clicking share brought me to
`https://wordpress.com/post/<blog_id>?embed=https%3A%2F%2Fwww.youtube.com%2Fembed%2FDWVfaxqTyl4%3Fversion%3D3%26rel%3D1%26showsearch%3D0%26showinfo%3D1%26iv_load_policy%3D1%26fs%3D1%26hl%3Den%26autohide%3D2%26wmode%3Dtransparent&image=https%3A%2F%2Fi1.wp.com%2Fhackaday.com%2Fwp-content%2Fuploads%2F2021%2F02%2Fac.png%3Fquality%3D80%26ssl%3D1%26strip%3Dinfo%26w%3D800&title=PC+Overclocking+with+an+Air+Conditioner+%E2%80%94+Hackaday&text=We+never+insist+that+a+hack+be+practical.+%5BTech+Ingredients%5D+is+living+proof+as+they+modded+a+computer+case+to+use+a+window+air+conditioner+for+overclocking+a+computer.+They+think+they+haven%E2%80%99t+hit+the+ceiling+yet%2C+and+got+their+AMD+Ryzen+8-core+processor+up+to+4.58+GHz.+An+advantage+of+forcing+air+from+an%C2%A0%5B%E2%80%A6%5D&url=https%3A%2F%2Fhackaday.com%2F2021%2F02%2F11%2Fpc-overclocking-with-an-air-conditioner%2F&is_post_share=true`
Which redirected me to
`https://abc.xyz.blog/wp-admin/post-new.php?calypsoify=1&block-editor=1&frame-nonce=redacted&origin=https%3A%2F%2Fwordpress.com&environment-id=stage&support_user&_support_token`
Which drew an empty editor.

I am unsure of the cause.

**Comment by Robertght** [comment]
another case in 3888614-zen

**Comment by retnonindya** [comment]
Another report:
3892491-zd-woothemes

**Comment by cpapazoglou** [comment]
> Serenity recently made it work in wp-admin for WoA sites. Maybe we could port that solution back to wpcom for simple sites?
> 636-gh-Automattic/wpcomsh

I have posted p9dueE-2LC-p2 for discussion since it feels we should move code to a more generic codebase.

**Comment by cpapazoglou** [comment]
It seems that folks are leaning to move the code to Jetpack and consolidate this feature with the Reblog feature in the frontend p9dueE-2LC-p2#comment-4887. Since this maybe a long quests, I created a PR which will temporarily resolve the problem for Simple sites.
