### ISSUE TITLE
W logo visually broken in the editor

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#51740]
In the editor, the W logo is visually broken:

I don't remember seeing this border on hover before — I think the whole area just used to have brighter color on hover:

<img width="392" alt="Screenshot 2021-04-07 at 11 36 32" src="https://user-images.githubusercontent.com/87168/113836872-f1f1a980-9795-11eb-994c-c33f48f5b485.png">

And when I open the drawer, site title/logo breaks up, and border around logo remains visible:

<img width="760" alt="Screenshot 2021-04-07 at 11 36 04" src="https://user-images.githubusercontent.com/87168/113836945-06ce3d00-9796-11eb-8188-3556e141f4cb.png">

I believe the code for side nav is here: https://github.com/Automattic/wp-calypso/tree/714324a537c380b2d6135c95af9838b25247229b/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar

Themes I tested:
- Independent Publisher 2
- Alves
- Atomic Blocks

Plugins:
Gutenberg: v10.3.1-with-autocomplete-fix
CoBlocks: 2.5.3
Editing Toolkit: 3.3976
WP AMP: 1.4.2

**Comment by ciampo** [comment]
> I don't remember seeing this border on hover before

Looking at https://github.com/WordPress/gutenberg/pull/29888, it seems like these border hover styles are working as expected

> And when I open the drawer, site title/logo breaks up, and border around logo remains visible:

This definitely seems buggy, I'm going to take some time to reproduce and potentially fix

**Comment by simison** [comment]
Aight! Thanks for digging up the PR for hover styles. :-)

**Comment by ciampo** [comment]
> And when I open the drawer, site title/logo breaks up, and border around logo remains visible:
> ...
> I believe the code for side nav is here: https://github.com/Automattic/wp-calypso/tree/714324a537c380b2d6135c95af9838b25247229b/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar

I can reproduce this consistently. The issue is indeed related to ETK code, in particular to [some higher-specificity rules](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/header/fullscreen-mode-close/style.scss#L19) that override some of the styles set in ETK for that button:

https://user-images.githubusercontent.com/1083581/113860012-d5f60400-97a5-11eb-8273-ffd81ccc8619.mp4


The good news is that https://github.com/Automattic/wp-calypso/pull/51477 already fixes this issue, by making the container `div` to use flexbox instead of fixed positioning (in order to test the fix, run `install-plugin.sh etk add/site-icon-to-nav-sidebar` on your sandbox and enable it for you test site)

@simison, since @creativecoder is AFK for the next days, I am happy to merge #51477 on his behalf. What do you think?

**Comment by simison** [comment]
Yep, sounds good. Grant is also off from gardening so someone should take the work over anyway. Thanks again!
