### ISSUE TITLE
Jetpack Connect: Terms of service

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#5174]
From @beaulebens:

```There’s no acceptance of terms of service, or indication of what they’re really approving. I’m a little concerned about that, and we might need something like “by approving, you’re agreeing to our {terms of service}” on there.```

^ @rickybanister

**Comment by rickybanister** [comment]
Hey @johnHackworth we definitely will add a link, I just want to confirm whether it should happen before we send users to wp-admin for the first time, or after they come back. Since we're currently auto-connecting when they come back we may want to have this language happen before they go to wp-admin. 

One additional thought, if they just signed up for an account they've very recently agreed to the TOS, but of course we want to make sure they have every opportunity to understand the connection process.

cc @jennyzhu for some peace of mind please
