### ISSUE TITLE
Nav Unification: Sidebar - Border on Hover State

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#51835]
This is a very minor detail, but something which I noticed so felt was worth raising. The hover state of the site card in the Sidebar appears to have a left border in WP-Admin, but not in Calypso.

| Calypso  | WP-Admin 
| ------------- | ------------- 
|  <img width="260" alt="Screenshot 2021-04-10 at 13 56 15" src="https://user-images.githubusercontent.com/43215253/114270598-346ced80-9a05-11eb-83ca-b6abccd4c4e1.png"> | <img width="249" alt="Screenshot 2021-04-10 at 13 56 03" src="https://user-images.githubusercontent.com/43215253/114270603-3767de00-9a05-11eb-9f4c-c56f58d44f78.png">|

Is this intentional, or should there be a border added to it in Calypso too in order to ensure that they're consistent?

cc @cpapazoglou

**Comment by cpapazoglou** [comment]
Hey @Aurorum! It's not intentional, they should be consistent. I have even mentioned it here https://github.com/Automattic/wp-calypso/pull/50427#pullrequestreview-597417356 😁! I am actually proposing to remove the hover effect from the site card in WP Admin (code lives: [here](https://github.com/Automattic/jetpack/blob/16fd659047e04f94b8f3fb768dd15f665eee1291/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.css)). This would align with "Collapse menu" which is also not a menu and doesn't have that hover effect.

But let's hear what @sfougnier has to say!

**Comment by ghost** [comment]
Yes, agreed that it's strange. I don't think it's necessary on the site card.

**Comment by cpapazoglou** [comment]
Let me note that we should also remove it from the "Browse Sites" button.

**Comment by Aurorum** [comment]
Thanks! I opened a PR to remove it in Automattic/jetpack#19510. :)
