### ISSUE TITLE
E2E: Flaky "Can see correct post title" in wp-calypso-gutenberg-post-editor-spec.js

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#51947]
This spec seems to be flaky so let's try to fix it.

#### Failing spec details

From https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/65435/workflows/9b1b45e9-dc71-47ce-946c-c122ed0f3f7f/jobs/156505:

```
[WPCOM] Calypso Gutenberg Editor: Posts (mobile) Private Posts: @parallel Publish a Private Post As a logged in user - Can see correct post title - As a logged in user - Can see correct post title
/home/circleci/wp-calypso/wp-calypso/test/e2e/specs-gutenberg/wp-calypso-gutenberg-post-editor-spec.js
TimeoutError: Waiting for the element to become located and visible By(css selector, .type-post)
Wait timed out after 22085ms
    at /home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by noahtallen** [comment]
Looking at the video from the URL, the problem is that it didn't wait long enough for the editor to load after creating a site. It took a bit too long on the "step 2" part of the create site flow. (inside this function call: https://github.com/Automattic/wp-calypso/blob/8f2f25edfd8a7ad0fab997a741a1000dba2b781e/test/e2e/specs-gutenberg/wp-calypso-gutenberg-post-editor-spec.js#L440)

So I think we need to increase a timeout somewhere -- gonna try to find where that is.

**Comment by noahtallen** [comment]
From what I can tell from the video, when the "published post" snackbar shows up, the driver does click it -- but the published post doesn't load. :thinking:

**Comment by WunderBart** [comment]
> From what I can tell from the video, when the "published post" snackbar shows up, the driver does click it -- but the published post doesn't load. 🤔

Seems like this could be fixed by https://github.com/Automattic/wp-calypso/pull/52089/commits/abd6dd52c4e89068ffaf5861da2a9b0577cb6ca9 then! 🤞

**Comment by noahtallen** [comment]
Lovely!
