### ISSUE TITLE
Free Atomic: Site Health Accessible

### ISSUE THREAD

**Issue by sbathompson-he** [Automattic/wp-calypso#51999]
### What plan tier is the site on?
Free

### Where are you seeing the issue?
Tools > Site Health

#### What I expected on the Atomic site
Not to see Site Health as that is usually only on a Business or eCommerce Plan

#### What actually happened
Ability to see Site Health which includes all the information shown on the Info Tab.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![](https://d.pr/i/hAiv1L+)

**Comment by cpapazoglou** [comment]
AFAIK, Site Health isn't a paid feature. On Business or eCommerce Plan it makes sense to have it available since 3d party plugins may brake things. Besides that, I don't see any point of removing this page for Free Atomic. Does the existence of this page on Free Atomic create any problems?

**Comment by DustyReagan** [comment]
I'm leaning we leave "Site Health" in for all Atomic sites. Seems like it's useful for debugging and a feature of having an Atomic site, rather than a specific plan. Only downside of leaving it in is maybe it could confuse users? But it seems tucked away and easy enough for the user to ignore.

**Comment by mmtr** [comment]
AFAIK the only reason why "Site Health" is not available on Simple sites is due to security constraints, so I agree with @DustyReagan above.

As long as the screen doesn't contribute to issues for users, let's keep it around since it can be useful in many instances. We can revisit the approach if we start receiving reports of users being confused by this, or if we finally decide to sell it as a paid feature.
