### ISSUE TITLE
Purchases: Auto-renew is shown as off for unbillable or missing payment methods even when it is on

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#51996]
### Steps to reproduce the behavior

1. Buy a subscription with a credit card. Go to the Manage Purchase page and verify that it has auto-renew turned on:
    ![auto-renew-on-payment-method](https://user-images.githubusercontent.com/235183/114943280-c153e480-9e13-11eb-9520-9e22c6d30b29.png)
2. Go to https://wordpress.com/me/purchases/payment-methods and remove the credit card.
3. Go back to the Manage Purchase page and notice that auto-renew is now off:
   ![auto-renew-off-no-payment-method](https://user-images.githubusercontent.com/235183/114943312-cb75e300-9e13-11eb-9503-b77f95bd66ed.png)

That wouldn't be so bad on its own, but the problem is that auto-renew actually **is** on -- which will be reflected in the billing emails the user gets, etc.  (Of course, without a payment method attached, auto-renewal will never succeed.)

In addition, since you can essentially reproduce the above by simply buying a subscription with credits or a non-rechargeable payment method also (auto-renew will be on, but Calypso will show it as off), and in that case we have no reason to think the user intended for auto-renew to be off at all, the issue here is mainly that Calypso is showing misleading information.

### What I expected to happen

I think the best course of action is to show auto-renew on whenever it's on, but with some kind of warning icon and note underneath, something like:

>:warning: No payment method

The user would still be able to toggle auto-renew off if they want, at which point it will "really" be off.  And if you then try to turn it back on, it should take you into the dialog to add a payment method first (just like it does now).

### Context

I think this issue may have originally been fixed in https://github.com/Automattic/wp-calypso/pull/35723 and then came back in https://github.com/Automattic/wp-calypso/pull/40660, although I'm not sure.

See also (internal link): p1618461009271000-slack-C02BEP610

**Comment by DavidRothstein** [comment]
Somewhat related to this also (internal link): c/kAk1PjtN-tr

**Comment by DavidRothstein** [comment]
Came up here also (internal link): pNPgK-5u1-p2

**Comment by mpkelly** [comment]
Hi @DavidRothstein! I am taking a look at this one now. 

Regarding your remark, "but the problem is that auto-renew actually is on" above, which system are you referring to, and is the status reflected somewhere in the data available in Calypso?

I checked through the code and can see this toggle still using the negated value of `isExpiring`, which you last changed in 2019, to decide if it is enabled:
![image](https://user-images.githubusercontent.com/6851384/177181994-54141301-c325-49c0-ae1d-1df886e15609.png)

(the change more recent than yours is just removing Lodash)

So my guess is that when a card is removed, the `expiryStatus` is changed to **manualRenew**.  Your comment above suggests another source of truth, and I'd like to use that - can you give me some pointers here?

**Comment by mpkelly** [comment]
I tested this with a Pro Plan purchase today. This diff shows how the JSON data - which comes from `rest/v1.1/sites/{site}/purchases` - changes when manually disabled vs when a payment method has been removed:

![image](https://user-images.githubusercontent.com/6851384/177533419-6af59da0-cd33-41c8-97e2-dc9e7d1a3b9d.png)

I think the issue is that this is still **"1"** on the right side
```JSON
"auto_renew": "1",
```
This value should be reflected in the UI, but currently it isn't. 

I think it is worth asking what a user is trying to do when they remove a payment method, as we can maybe improve the UX. For example, we could offer to cancel linked subscriptions when deleting the payment method. Something like this:

![image](https://user-images.githubusercontent.com/6851384/177535752-2e8c5095-5921-41e5-8f58-ef7cd04b850d.png)

The minimum change should be to have [auto-renew-toggle](https://github.com/Automattic/wp-calypso/blob/3cc332640fbbf4682f4d7aa1b70fba33c1fbd626/client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx#L244) use the `"auto_renew"` field shown above and also show a warning if there is no payment method: 

```typescript
export default connect(
	( state, { purchase, siteSlug } ) => {
		return ( {
			fetchingUserPurchases: isFetchingUserPurchases( state ),
			isEnabled: purchase.isAutoRenewEnabled, // modified
			showMissingPaymentMethodWarning: purchase.isAutoRenewEnabled && !purchase.isRechargeable, // added
			currentUserId: getCurrentUserId( state ),
			isAtomicSite: isSiteAtomic( state, purchase.siteId ),
			siteSlug: siteSlug || getSelectedSiteSlug( state ),
		} )
	},
	{
		fetchUserPurchases,
		recordTracksEvent,
		createNotice,
	}
)( localize( AutoRenewToggle ) );

```
The above change would also require a change to [client/lib/purchases/assembler.js](https://github.com/Automattic/wp-calypso/blob/3cc332640fbbf4682f4d7aa1b70fba33c1fbd626/client/lib/purchases/assembler.js#L97) as shown

```typescript
                ...
		userId: Number( purchase.user_id ),
		isAutoRenewEnabled: purchase.auto_renew === "1", // added 
```
(there are a few other places that need updating but these are the key parts)

@daledupreez what do you think of this proposal? What do you think about the suggestion above, to offer to cancel subscriptions when the payment method is removed?

**Comment by DavidRothstein** [comment]
Thanks @mpkelly -- I don't remember exactly, but I think you're probably right that the `auto_renew` field you identified is the correct one to look at!

>What do you think about the suggestion above, to offer to cancel subscriptions when the payment method is removed?

The word "cancel" is very ambiguous sometimes, so it depends what you mean :smile: If you mean actually removing the subscription, then definitely not.  If you mean turning off auto-renew, then maybe -- see 265-gh-Automattic/payments-shilling.  But it's also an extra thing for the user to think about, so even though I filed that issue, I'm not sure... Just showing them the list of affected subscriptions as in https://github.com/Automattic/wp-calypso/issues/60629 might be better.  Ultimately, if they are deleting a payment method and not adding one to replace it, they're probably not going to care much about the difference between auto-renew on and auto-renew off anyway.

**Comment by mpkelly** [comment]
Thanks @DavidRothstein

>If you mean turning off auto-renew, then maybe

Yes, I meant this. 

Reading through the linked issues, I think option 2 in 265-gh-Automattic/payments-shilling is probably a good solution unless there is a backup payment method present. At a minimum, I think we should show a warning on the `PaymentMethodDeleteDialog` if a card is linked to purchases that have auto-renew enabled. 

I will make the change related to the `auto_renew` flag not being properly reflected in the UI. Let me know if you have a preference for the other change when a card is removed, and, if so, I can take care of that too.

**Comment by daledupreez** [comment]
~@mpkelly and @DavidRothstein, I think we can close this issue with PR #65365 getting merged to production. Can you confirm?~
Scratch that -- I am going to close the issue as resolved. Feel free to re-open if you think we still have work to do.

**Comment by DavidRothstein** [comment]
It looks great for missing payment methods, but there are still some issues for unbillable payment methods.  Since this is already closed I decided to just file that separately: 1058-gh-Automattic/payments-shilling
