### ISSUE TITLE
Design Picker: ensure design thumbnails correct size

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#52017]
## What

The Design Picker component at the moment doesn't take its own width into account when laying out the grid containing the design thumbnails. In particular, when embedded in the `/start` signup flow, the size of the design thumbnails can get particularly small at higher screen sizes:

<img src="https://user-images.githubusercontent.com/1083581/115263289-96300480-a135-11eb-85a6-53be87b2d39c.png" width=400 />

<details>
<summary>Here's a detailed recap of the Design Picker layout configurations (click to expand):</summary>

### Design Picker in `/new` flow

| Breakpoints | Container layout | Grid layout | Design item width |
|---|---|---|---|
| [320, 480) | 100% width (with 24px L/R margins) | 1 col, 48px row gap | 270px - 429px |
| [480, 600) | same as above | 2 col, 48px row gap, 24px row gap | 202px - 262px |
| [600, 782) | 100% width (with 48px L/R margins) | same as above  | 328px - 329px |
| [782, 1080) | 100% width (with 96px L/R margins) | same as above  | 281px - 430px |
| [1080, 1632) | same as above  | 3 col, 48px row gap, 32px row gap | 272px - 456px |
| [1632, 1920) | maxed at 1440px width | same as above | 456px |
| [1920+ | same as above | 4 col, 48px row gap, 32px row gap | 334px |

https://user-images.githubusercontent.com/1083581/115269286-70a5f980-a13b-11eb-8330-a060c3d9eb10.mp4

### Design Picker in `/start` flow

| Breakpoints | Container layout | Grid layout | Design item width |
|---|---|---|---|
| [320, 480) | 100% width (with 24px L/R margins) | 1 col, 48px row gap | 272px - 431px |
| [480, 1008) | same as above | 2 col, 48px row gap, 24px row gap | 204px - 468px |
| [1008, 1080) | maxed at 960px | same as above  | 468px |
| [1080, 1920) | same as above | 3 col, 48px row gap, 32px row gap  | 299px |
| [1920+ | same as above | 4 col, 48px row gap, 32px row gap | 216px |

https://user-images.githubusercontent.com/1083581/115269307-769bda80-a13b-11eb-88d0-d26e79bfdcd8.mp4

</details>

## Why

We should ensure that the design thumbnails never get too small, regardless of the viewport width and of the design picker's container width.

We should make this feature contained inside the Design Picker component — i.e. the design picker component should be aware of its own width, and arrange the design items accordingly.

## A/C

- [ ] The design picker thumbnails should never be narrower than [TBC]px
- [ ] The design picker thumbnails should never be laid out on more than 4 columns
- [ ] The maximum width of the `design` step in the `/start` signup flow should be increased to `1280px` (or `1440px` alternatively)
- [ ] The thumbnails' size should be determined from the design picker's container size (and not from the viewport size). The code for setting the thumbnail size should be within the design picker component
- [ ] The column gap is `24px` when there are less than 3 columns, and `32px` for 3 columns or more
- [ ] This piece of functionality should not interfere with the [long previews feature](https://github.com/Automattic/wp-calypso/issues/51925)

## Additional context

There are 2 approaches that seem suitable for the task:

- using CSS grid ([see example](https://gridbyexample.com/examples/example28/)) — Proof of concept: #52068
- using the `ResizeObserver` APIs (see [docs](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver))

See p1618566052238000-slack-C0KDTA48Y

**Comment by roo2** [comment]
We've optomized the size of preview images on the new page template selector dialog in #51854.

We could apply a similar treatment to the `/start` flow, just optimizing the available space on different breakpoints.

A separate work in progress is enabling previews with longer aspect ratios and a scroll preview on hover in production  https://github.com/Automattic/wp-calypso/issues/51925

**Comment by ollierozdarz** [comment]
Nice, @ciampo ! 

Actually, after seeing your videos (the nitty gritty 😉), I wonder if the last step of showing 4 designs is actually necessary. Seeing 3 designs feels bigger and better in those scenarios, then once we hit the final breakpoint you lose a bit of value since the grid container is the same size but the designs get smaller.

Unless there's push back on this, I'd be up for making [1632, 1920, + sizes] 3 col, 48px row gap, 32px col gap.

For the /start design, I think there's an opportunity to make the design names White, since Grey is very hard to see on the dark Blue background.

**Comment by razvanpapadopol** [comment]
> I wonder if the last step of showing 4 designs is actually necessary. Seeing 3 designs feels bigger and better in those scenarios.

Yes, this is exactly what happens in the proof of concept PR (#52068) by setting the minimum width of 295px per item. Just to confirm, the 3 columns as a maximum will apply in `/start` which has the max-width of the container 960px. On the other hand, in `/new`, where we have 1440px as max-width, having 4 columns makes sense.

Test link for `/start`: https://calypso.live/start/with-design-picker?branch=try/design-picker-dynamic-layout
Test link for `/new`: https://calypso.live/new?branch=try/design-picker-dynamic-layout

> For the /start design, I think there's an opportunity to make the design names White, since Grey is very hard to see on the dark Blue background.

We're working on it. `<DesignPicker />` will have an option to be used on dark backgrounds such as the /start blue: https://github.com/Automattic/wp-calypso/issues/51401

**Comment by ollierozdarz** [comment]
Thanks @razvanpapadopol!

Would it make anything easier (more parity) for both flows to use 1440px max-width? I know some of the control flow pages are 960px, but the current domain variant page I see right now in /start is much wider anyway, and since the page title and subtitle are centre aligned, I feel like there's not a big issue with the inconsistency.

**Comment by razvanpapadopol** [comment]
> Would it make anything easier (more parity) for both flows to use 1440px max-width? I know some of the control flow pages are 960px, but the current domain variant page I see right now in /start is much wider anyway, and since the page title and subtitle are centre aligned, I feel like there's not a big issue with the inconsistency.

@ollierozdarz, I guess you're talking about the version you get when being assigned to the Treatment variation of `refined_reskin_v1` experiment, right?

#### We have `/start/domains` screen:
* title and subtitle aligned to the left
* max-width: 1200px
<img width="961" alt="Screenshot 2021-04-21 at 15 37 45" src="https://user-images.githubusercontent.com/14192054/115554829-8fc99600-a2b7-11eb-8b20-9182ecba9a4f.png">

#### And `/start/plans` screen
* title and subtitle aligned to center
* max-width: ~100px more than 1200px as you can see below (screenshot made on a 1920px wide screen)
<img width="961" alt="Screenshot 2021-04-21 at 15 37 23" src="https://user-images.githubusercontent.com/14192054/115554840-922bf000-a2b7-11eb-90bd-9c222fb52e9b.png">

If we're fine with having these inconsistencies, I guess adding the `/start/design` step with title & subtitle center-aligned (as in `/start/plans`) and max-width 1440 (as in `/new`) should be fine on the reskinned onboarding 👌🏼 

Would you consider also doing the same on the blue onboarding which has a somewhat conservative layout (960 for domains step)?

**Comment by ollierozdarz** [comment]
> @ollierozdarz, I guess you're talking about the version you get when being assigned to the Treatment variation of refined_reskin_v1 experiment, right?

@razvanpapadopol, sorry, I should have articulated my question better.

I was actually meaning the **/start** domains variation that I currently see:

<img width="1789" alt="Screen Shot 2021-04-22 at 3 17 30 pm" src="https://user-images.githubusercontent.com/67085494/115659514-029d4480-a37e-11eb-91d5-a009af3b8c5f.png">

This looks like it's 1280px max-width, so we have the jump from 960px to 1280px in that flow (granted that this is probably an experiment).

So my question was, could the picker page below (**/start** picker) follow suit and become wider, because the designs feel really small when contained in the 960px panel. If we made it 1440px, we'd reach parity with the **/new** picker.

From Luna's perspective, would that be more ideal to handle?

I'd probably leave the other start pages as they are (960px) since this page is visually showcasing a benefit and could justify the change.

<img width="1788" alt="Screen Shot 2021-04-22 at 3 23 51 pm" src="https://user-images.githubusercontent.com/67085494/115660093-dafaac00-a37e-11eb-93bf-e68cb5651ca2.png">

(you can see here how the grey design names also become unreadable)

**Comment by ciampo** [comment]
> So my question was, could the picker page below (**/start** picker) follow suit and become wider, because the designs feel really small when contained in the 960px panel. If we made it 1440px, we'd reach parity with the **/new** picker.
> 
> From Luna's perspective, would that be more ideal to handle?

I believe that changing the width to `1280px` or to `1440px` won't make much of a difference to Luna, especially since with #52068 we would be computing the size of thumbnails based on the size of the design picker grid container (and _not_ of the page)

> (you can see here how the grey design names also become unreadable)

This is tracked separately in #51401 (and we already a PR opened: #52162)
