### ISSUE TITLE
Nav Unification - No option for users to enable "Send an email when a post or page changes"

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#52051]
Previously in the wp-admin settings for a site, a user could enable the  "Send an email when a post or page changes".  This option does not appear to be available any longer without accessing that URL directly ( domain/wp-admin/options-writing.php) or enabling the "Show advanced dashboard pages" option.  

### Steps to reproduce the behavior

1. Go to Settings > Writing
2. I would have assumed that the option for "Send an email when a post or page changes" would appear here as it does in the wp-admin for a site.  It does not.

#### What I expected to happen
In order to access this option, a user must know the exact URL of the wp-admin page to enable this or enable the "Show advanced dashboard pages" option.  

### Context
3919039-zen

#### Does this happen on simple or atomic sites or both?
Simple (this does not appear an an option in the wp-admin for Atomic sites)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Does not block purchases

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Markup on 2021-04-19 at 14:18:03](https://user-images.githubusercontent.com/24914028/115185069-13e61700-a11a-11eb-8368-51bdd0c28dfe.png)

**Comment by obenland** [comment]
@mmtr Did something revert or break [your commit from last week](https://github.com/Automattic/wp-calypso/issues/50217#issuecomment-818605628)? I also can't find that setting

**Comment by mmtr** [comment]
@obenland the commit is still there, but as noted in D58852-code, we moved the "Email Post Changes" settings to the WP Admin writing settings (`/wp-admin/options-writing.php`), which can be accessed from the menu only when the "show advance pages" toggle is enabled. They are not available in the Calypso writing settings (`https://wordpress.com/settings/writing`).

That means that in order to manage these settings, users need to either enable the toggle and select "Settings > Writing" in the menu, or type the WP Admin writing settings URL directly in the browser.

**Comment by joweber123** [comment]
We can go ahead and close this issue then if this setting was intentionally moved to the wp-admin section. Thank you for the clarification.
