### ISSUE TITLE
Site Editor: redirect loop during signup 

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#52216]
A couple of folks ran into redirect loop after creating their site and landing into site editor.

> This happened on macOS 10.x, 11.x, and in all major browsers – Chrome, Safari, and Firefox.

I didn't run into it so far, and it seems like intermittently happens only for some folks.

https://user-images.githubusercontent.com/1182160/115799309-7bc98580-a3d8-11eb-84df-f37abfe0783d.mp4

**Comment by david-szabo97** [comment]
Tried to reproduce it but no luck 😞

**Comment by mattwiebe** [comment]
I tried, too, also no luck. One hunch was maybe that sandboxing the REST API was the problem, so I tried with and without the sandbox, but both worked.

**Comment by simison** [comment]
Non sandboxed, happens in both proxied and non-proxied, Chrome and Firefox.

Looks like it's jumping between `https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0` and `https://horizon.wordpress.com/site-editor/[MY SITE]`

**Comment by mattwiebe** [comment]
Just reporting in here that @Addison-Stavlo found a probable cause: it happens to accounts with "show wp-admin pages if available" setting enabled in `/account/me`. 

I won't be able to dig in more today but if that bears out in testing, this becomes a much lower priority since the number of people registering an additional site on an account with that setting enabled will be pretty low.

**Comment by Copons** [comment]
> Just reporting in here that @Addison-Stavlo found a probable cause: it happens to accounts with "show wp-admin pages if available" setting enabled in /account/me.

It happened to me as well with the wp-admin option turned on, and was also confirmed by one of the people testing the 4th CfT.
This is excellent news!
