### ISSUE TITLE
Offer the ability to create and manage staging sites on WoA sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#52241]
Initially posted in the Ideas P2 here: pKdGS-1OT-p2

### What
Offer users on WoA the ability to create and manage staging sites so they can try out other themes, plugins, etc, without having to make changes on their live site, or to create another site on WordPress.com and require another Business plan to do that.

**Additional context**
This has been mentioned in **54 comments** from July 2019 to March 2021.

**Comment by davipontesblog** [comment]
This can be tracked by reviewing the volume of incidence of this chat tag in WP.com: `atomic_staging_local`

Current stats: 37 requests in the last 30 days.

**Comment by formosattic** [comment]
Also tracked at 384-gh-Automattic/atomic

**Comment by happychait** [comment]
30342938-hc

**Comment by JoshuaGoode** [comment]
Copying over some of my comments from an internal discussion. See it for some additional links: p7DVsv-ccs-p2#comment-36767

Overall, it’s been a product decision not to offer staging. I personally would like to see some kind of paid add-on in the future that allows for easy site cloning.

The Atomic platform has cloning built-in with endpoints ready if WordPress.com wants to add it at some point. It's already in use outside of WPCOM.

For WordPress.com, this could potentially be provided as an “advanced” monthly paid add-on to a current plan — designed to be temporary but the user can continue to renew it for as long as they need it. If user cancels it, we can make it clear that it and its content will be gone. If it expires, after a grace period with plenty of notices, we could then automatically revert it so WoA doesn’t have countless sites without a plan.

The gap would still likely be pushing/syncing/migrating the content if they make changes to the staging version that they want to move to their live site. There are many ways to tackle that from my point of view though — filled with potential Jetpack connection, ownership, stats..etc issues.

**Comment by zachspears** [comment]
I have had numerous chats with users asking about staging sites, I will start adding those conversations here. I think it would provide a lot of use as an advanced add-on, and give people more flexibility to build their projects and test their sites.
31599148-hc

**Comment by JoshuaGoode** [comment]
Copying over requests from the older legacy Atomic repo (384-gh-Automattic/atomic).



* Jan 18, 2018: 1572955-hc
* Jul 15, 2018: `This would be particularly helpful with eCommerce/WooCommerce sites who still need their online shop running while the site is being troubleshot.` 5034686-hc
* Sep 17, 2018: 2152115-hc
* Jan 31, 2019: `This is requested fairly often. As an enhancement it could have a high impact, specially for WooCommerce sites.
I am not changing the priority as I understand there are no resources for it but it might be worth revisiting it in the future.`
* Feb 2, 2019: `would this be an interesting addition / selling point for the eCommerce plan maybe? While not all Business sites would need a staging site, I personally wouldn't want to run an online store without staging.`
* Feb 2, 2019:  `I see it requested and actually needed fairly often (for example, when a business site wants to switch themes). Also, we have a significant number of Business sites with Woo installed, since the eCommerce plan is new. Perhaps as an add-on for any AT sites would be good.`
* Feb 11, 2019 5891835-hc, 2895357-zen, `is there a way I can start a new site from scratch with keeping up our current one until our new site is ready and then swapping them? The idea is so customers can't see all the changes and we can have a workplace away from the public eye.`
* Mar 24, 2019: 11529107-hc
* Nov 5, 2019: `A customer asked for staging site` 16002914-hc
* Nov 8, 2019: `Another customer requesting this` 16275914-hc
* Nov 12, 2019: `Another customer who needed this` 16586636-hc
* Jun 26, 2021: 30342938-hc
* Jul 10, 2021:  30560919-hc


* Aug 15, 2021:

>  30855304-hc

> The customer would have liked to use a staging site to test major theme changes before applying those to the live site.

> I also would like to highlight the difference in difficulty (and compatibility caveats) in setting up a local staging environment between WordPress.com and something like Local. It seems like this type of integration could be something we could build.


I'm not copying them over but also please see the ideas post previously mentioned, pKdGS-1OT-p2

**Comment by arunsathiya** [comment]
Also requested on 31431395-hc.

**Comment by arunsathiya** [comment]
Two more requests: 32440474-hc and 32441092-hc.

**Comment by kuropixel** [comment]
User requesting: 32723456-hc

**Comment by arunsathiya** [comment]
Requested in 32838788-hc.

**Comment by arunsathiya** [comment]
Requested in 32813550-hc.

**Comment by davipontesblog** [comment]
Requested in 20087312-hc

**Comment by dragstor** [comment]
Requested in 32890176-hc.

**Comment by arunsathiya** [comment]
33019126-hc.

**Comment by arunsathiya** [comment]
32740445-hc.

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/planning-a-full-rebrand-and-relaunch-need-help-with-logistics/?view=all

**Comment by arunsathiya** [comment]
Requested on 33681364-hc.

**Comment by dragstor** [comment]
Requested on:
-  19175884-hc
- 33720770-hc

**Comment by happychait** [comment]
33961463-hc which was followed up in 4737092-zen

**Comment by happychait** [comment]
In 34329929-hc customer asked for duplicating their live site.

**Comment by syhussaini** [comment]
In 4807826-zen the user would like to have a pre-production environment so that they can work on the changes without disrupting the existing site.

**Comment by happychait** [comment]
Another one in 35049390-hc

Suggested Local by Flywheel for now.

**Comment by dragstor** [comment]
Requested in 35077926-hc Suggested https://localwp.com/

**Comment by dragstor** [comment]
Requested in 34658053-hc

**Comment by arunsathiya** [comment]
Requested in 34887095-hc.

**Comment by arunsathiya** [comment]
Also requested in 35528948-hc.

**Comment by rw-ye** [comment]
Another request here: 5226914-zd-woothemes

**Comment by formosattic** [comment]
- [ ]  35640394-hc
- [ ]  35720566-hc

**Comment by arunsathiya** [comment]
- [ ] Also requested in 35870833-hc

**Comment by kuropixel** [comment]
- [ ] Also requested in 35880860-hc

**Comment by arunsathiya** [comment]
Requested in 36072446-hc. Given the nature of this issue, it wouldn't be implemented right now. So, I haven't promised a followup.

**Comment by arinoch** [comment]
One more. 36125479-hc

Given how far this is down the priority list, gave the local alternative and did not offer a followup.

**Comment by arunsathiya** [comment]
11434269-hc.

**Comment by dragstor** [comment]
28750711-hc

**Comment by dragstor** [comment]
35788589-hc

**Comment by kuropixel** [comment]
5707046-zen

**Comment by happychait** [comment]
38449575-hc

**Comment by dragstor** [comment]
38754078-hc

**Comment by dragstor** [comment]
40276444-hc

**Comment by happychait** [comment]
40854517-hc

**Comment by tvolpert** [comment]
- [ ] 41261522-hc

**Comment by happychait** [comment]
42156434-hc

**Comment by dragstor** [comment]
42315424-hc

**Comment by vindl** [comment]
Closing this since we released staging sites in the meantime: https://wordpress.com/blog/2023/05/02/announcing-staging-sites/.
