### ISSUE TITLE
Nav Unification: Collapse State Not Preserved After Switching Site

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#52261]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/home and pick any site you have
2. Click on `Collapse menu ` at the bottom of the left sidebar
3. Click `Switch Site` and pick another site
4. Click `Switch Site`again and select the previous site again
5. See the sidebar uncollapsed

#### What I expected to happen

See the sidebar collapsed

#### What actually happened

Sidebar uncollapsed

### Context

Manual testing after user's report in 3934837-zd-woothemes who wanted to have the sidebar consistently collapsed but could not.
#### Browser / OS version
Chrome 89 on macOS
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Both
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/39308239/115953258-069ea300-a4f3-11eb-8f37-81d40e3bc09c.mov

https://user-images.githubusercontent.com/39308239/115953290-3baaf580-a4f3-11eb-9deb-42eb827f2926.mov

**Comment by cpapazoglou** [comment]
The moment you click "Switch Site" the sidebar is **expanded** since the site-switcher belongs to the Sidebar. While I found this behavior logical, I get the User frustration. It seems I haven't meticulously taken into consideration Users with multiple sites. 

Currently the `Sidebar Collapsed State` is like an account wide preference, meaning it applies to all sites and all environments Calypso, Simple, Atomic (Atomic will be fully synchronized on next Jetpack release  May 4, 2021). 

- Would keeping the same state after User selects a site in the site-switcher alleviate the problem? Be ware that clicking a notice / nudge or the site card will also expand the sidebar.
- Do we need to keep the sidebar state per site?

**Comment by inaikem** [comment]
> * Would keeping the same state after User selects a site in the site-switcher alleviate the problem? Be ware that clicking a notice / nudge or the site card will also expand the sidebar.
> * Do we need to keep the sidebar state per site?

It's a yes on both counts from me.

I would work on the principle that this user preference this should be the same across multiple sites once set. The only (big) reason I can think of altering an editorial flow/process from site to site is if different platforms are being used.

...with the proviso that in a purely WP environment, users might want to retain different block editor preferences based on the format and type of content being produced. Hope that makes sense!
