### ISSUE TITLE
Settings: Can't navigate Site Timezone dropdown with keyboard

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5231]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/
2. Pick one of your sites.
3. Click on the dropdown appearing below Site Timezone.
4. Start typing "b", "u", "d".

I would expect the dropdown to lead me to "Budapest", as it currently happens in wp-admin. Instead, the dropdown doesn't move at all, I can't navigate it with a keyboard.

**Comment by lancewillett** [comment]
Closed #5243 as a duplicate.

**Comment by lancewillett** [comment]
See also https://test.wordpress.com/2016/04/13/settings-timezone-picker-usability/ and #3902

**Comment by rralian** [comment]
I don't think I had ever noticed before that we're using two different components for the same purpose on the same page, one on top of another. They're both dropdown selectors with option groups. The language selector uses a native selector element, albeit with a custom-looking face when it's inactive. But the timezone-selector uses a custom react-implemented dropdown.

![two dropdowns](https://cloudup.com/chxyWxKcwyL+)

---------

![native select](https://cloudup.com/c7id7LvHYIf+)

---------

![react-implemented dropdown](https://cloudup.com/cLOPvwgMR6X+)

----------

While the react-implemented component looks a little nicer in a screenshot, the native select element is much easier to use because it conforms to my expectations and has built-in support for accessibility and touch device implementation (native beats the react-custom-component hands down in mobile), and also because it's implemented by the operating system, so it gets special access to do things like show a long list that expands _beyond_ the browser.

![img_0094](https://cloud.githubusercontent.com/assets/134044/15135650/5c2e990e-163e-11e6-8be4-1d8cd8999fb0.PNG)

------------

![img_0095](https://cloud.githubusercontent.com/assets/134044/15135643/50ed448c-163e-11e6-99ab-624babfaabf2.PNG)

-----------

![list beyond browser](https://cloudup.com/cWtEXhgNC5m+)

------------

Given this, I'm of the opinion that we should swap out the custom component for a select element. @retrofox what do you think?

**Comment by retrofox** [comment]
@rralian yup, you're right. I'm down specially how the dropdown is shown in different devices.

**Comment by retrofox** [comment]
let me create a PR for this btw

**Comment by rralian** [comment]
@retrofox have you had a chance to look at this yet?

**Comment by retrofox** [comment]
no yet. I'll do to night.
