### ISSUE TITLE
Site Editor: Arrows sometimes appear underneath select boxes in block inspector sidebar

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52345]
Stubbing out an issue reported by @alaczek. Arrows (as shown below) will sometimes appear in the Site Editor  with the Query Block.

![image](https://user-images.githubusercontent.com/545779/116300888-073e7000-a765-11eb-813f-c00206829f70.png)

I've been able to reproduce this myself but they will sometimes appear or disappear intermittently.

**Comment by andrewserong** [comment]
Similar issue to #52343 

This appears to be working correctly now:

![image](https://user-images.githubusercontent.com/14988353/116948284-5551f700-acc2-11eb-8e5e-539002f510f4.png)

I believe this was a regression in Gutenberg v10.5.0 RC 1 reported in https://github.com/WordPress/gutenberg/issues/31070 and resolved in https://github.com/WordPress/gutenberg/pull/31073. I double checked on my test site, and this issue is no longer present as of Gutenberg v10.5.2 running on edge stickered sites (and also isn't present in v10.4.1 on a site without the sticker present). Let us know if you see the issue again, and we can re-open the issue.
