### ISSUE TITLE
Site Editor: unexpected group block UI in block inspector

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52346]
### Steps to reproduce the behavior

1. Create a new site with the Site Editor on WP.com
2. Click on a group block
3. Open the block inspector

#### What I expected to happen

Group Block UI in Core

![image](https://user-images.githubusercontent.com/545779/116301281-7f0c9a80-a765-11eb-90cb-b548a04e20bf.png)

#### What actually happened

Too-wide UI in block inspector.

![image](https://user-images.githubusercontent.com/545779/116301436-a2374a00-a765-11eb-9dc1-ec2f827cd94d.png)

**Comment by andrewserong** [comment]
I _think_ this one might be resolved by https://github.com/WordPress/gutenberg/pull/31073 in Gutenberg 10.5, but I'll double check.

**Comment by andrewserong** [comment]
Similar issue to #52345

This appears to be working correctly now:

![image](https://user-images.githubusercontent.com/14988353/116952158-4c1a5780-accd-11eb-915d-9c16b1f0531c.png)

I believe this was a regression in Gutenberg v10.5.0 RC 1 reported in https://github.com/WordPress/gutenberg/issues/31070 and resolved in https://github.com/WordPress/gutenberg/pull/31073. I double checked on my test site, and this issue is no longer present as of Gutenberg v10.5.2 running on edge stickered sites (and also isn't present in v10.4.1 on a site without the sticker present). Let us know if you see the issue again, and we can re-open the issue.
