### ISSUE TITLE
Site Editor: Custom Link Text Field Misaligned

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52343]
### Steps to reproduce the behavior

1. Create a site on WP.com with the site Editor
2. Add a custom link item block to your navigation block in the site editor
3. Open the block inspector

#### What I expected to happen

What I see in core.

![image](https://user-images.githubusercontent.com/545779/116299947-e9bcd680-a763-11eb-947a-806cf6f1cbc0.png)

#### What actually happened

What I see on WP.com.

![image](https://user-images.githubusercontent.com/545779/116299995-f93c1f80-a763-11eb-93b3-97ad89c93f91.png)

**Comment by andrewserong** [comment]
I believe this was a regression in Gutenberg v10.5.0 RC 1 reported in https://github.com/WordPress/gutenberg/issues/31070 and resolved in https://github.com/WordPress/gutenberg/pull/31073. I double checked on my test site, and this issue is no longer present as of Gutenberg v10.5.2 running on edge stickered sites (and also isn't present on v10.4.1 without the sticker present). Let us know if you see the issue again, and we can re-open the issue.
