### ISSUE TITLE
E2E: Flaky "Can Correctly Apply Coupon" in test/e2e/specs/wp-plan-purchase-spec.js (failure rate 30%)

### ISSUE THREAD

**Issue by scinos** [Automattic/wp-calypso#52442]
Full Spec path: "[WPCOM] Plans: (desktop): Viewing a specific plan with coupon: @parallel @jetpack > Can Correctly Apply Coupon"
[Test history](https://teamcity.a8c.com/test/7199180902701457093?currentProjectId=calypso_WebApp&branch=%3Cdefault%3E)
Failure rate: 30% (61 failed, 147 successful)

#### Failing spec details

From https://teamcity.a8c.com/buildConfiguration/calypso_RunCalypsoE2eDesktopTests/6150646?buildTab=tests&status=muted&pager.currentPage=1&expandedTest=7199180902701457093:

```
Waiting for element to be clickable By(css selector, .notice.is-dismissable .notice__dismiss)
Wait timed out after 20152ms
TimeoutError: Waiting for element to be clickable By(css selector, .notice.is-dismissable .notice__dismiss)
Wait timed out after 20152ms
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:842:17
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by WunderBart** [comment]
It looks like the success notice doesn't always pop up after applying the coupon:

![image](https://user-images.githubusercontent.com/1451471/117027208-c7473200-acfc-11eb-9ec5-efba8c29e859.png)


The test is trying to dismiss it (IMO unnecessarily) and it fails since it's not there. The question is whether we want to handle/ignore it in the test or if we should actually fix the notice to appear 100% of the time. Or maybe both? :)
@Automattic/team-calypso-components any idea why it might be happening?
