### ISSUE TITLE
Unmanaged Gutenberg install has upgrades but it isn't visible

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#52511]
Was reported that:

> there is some weirdness in updates on the site, first it’s clear that auto-updates aren’t running for this site
but also that Gutenberg is in a weird state, where it has an update available but isn’t showing in all places `nourishedunion.com`
>
> also some weirdness on the “drop-ins” page of plugins.php

When looking at the wp-admin plugin updates page.

Few guesses:

- We have Gutenberg as a managed plugin, and it has an upstream update
- We haven't updated to that version .com-wide yet?
- WP detects the update and shows indicators for it in few places, but we hide the upgrade action on the update page somehow?

All that leads to some confusion.

@obenland could you help pull in someone from Atomic related teams that could triage this one? Thx!

**Comment by obenland** [comment]
> @obenland  could you help pull in someone from Atomic related teams that could triage this one? Thx!

Sounds to me like this would be a wpcomsh candidate?

**Comment by simison** [comment]
@obenland could be! I think this might need a designer to go through a bit of the experience to find out the confusing parts. Ghost updates must be stressful to customers. 😓 

Related: p9o2xV-1pr-p2

**Comment by JoshuaGoode** [comment]
The WordPress.com on Atomic platform was experiencing some updater issues around this time which is why unmanaged plugins were not updating automatically as expected. That specifically is now resolved. p7DVsv-cgt-p2 .  Along with things being fixed, sites can now control which unmanaged plugins auto-update.

As for Gutenberg on that specific site, it is not the managed/symlinked  version at the time of this comment. It is also actively updating automatically and is the latest repo version available.

While it's difficult to know what was seen on that site at that time, **_I can confirm that we are unintentionally hiding update notices for unmanaged version of Gutenberg._** 

### Managed Gutenberg and WordPress.com on Atomic

Some sites might have our symlinked/managed version of Gutenberg -- which will now display `Managed by host` in the WP-Admin plugin list.  We push out updates for that to the entire platform and the plugin can sometimes be intentionally behind the latest updates available or just pending a deploy.  

![Screen Shot on 2021-08-06 at 17:49:54](https://user-images.githubusercontent.com/4887830/128574424-d0609d14-bc57-4932-a665-ed484aa95c5a.png)*This screenshot shows a managed version of Gutenberg 11.2.0 which is behind the latest repo version available.*


At times, WordPress core might detect that our managed version doesn't match the repo version and note that an update is available.

![Screen Shot on 2021-08-06 at 17:48:15](https://user-images.githubusercontent.com/4887830/128574316-50cd51ed-d9ab-4170-844d-062d4e2a6fcf.png)*While the plugins page did not display an update is available, WP-CLI does.  Attempting to update this managed version here will fail.*


We've been hiding update notices for the managed version of Gutenberg for a while.  Some plugins might detect this and recommend an update. This was previously something Yoast would do.  We will also see an update is available if we check `plugin list` via CLI.

### Unmanaged Gutenberg and Update Notification Issues

Some sites will be using an unmanaged version and can disable auto-updates for it.  

It appears that through our attempts to hide update notifications for our managed version, we are also hiding them for the unmanaged version. 

![Screen Shot on 2021-08-06 at 17:56:41](https://user-images.githubusercontent.com/4887830/128574885-94ce8449-df2f-49a5-8e26-648ae2a31826.png)*In this screenshot, we have an unmanaged version of Gutenberg with auto-updates off.  It is behind on updates but no notification is visible in the plugin list.*


However, we can find an update notification for this unmanaged version by going to `/wp-admin/update-core.php`.

We can also see update indicators for it in the sidebar next to Updates and Plugins.

![Screen Shot on 2021-08-06 at 17:59:43](https://user-images.githubusercontent.com/4887830/128575112-2257dcd3-5bea-4152-bc6e-27d9f9ac067a.png)

@simison

**Comment by simison** [comment]
cc @tjcafferkey @obenland FYI above, might be some good simple/Atomic work to sort out?

**Comment by obenland** [comment]
@Copons I'm not sure this affects a ton of sites, but might be a small fix that could be a good wpcomsh onboarding task

**Comment by Copons** [comment]
I've pulled this into our board, we'll see to triage it.

> We've been hiding update notices for the managed version of Gutenberg for a while.

@JoshuaGoode could you please share where we do this? It would be extremely helpful! 🙇‍♂️

**Comment by JoshuaGoode** [comment]
@Copons I'd suspect it's `wpcomsh`.

We pull an array of managed/symlinked plugin names and then hide update notices for them.

I guess that might be what is hiding notices for non-managed versions that aren't symlinked. 

wpcomsh.php#L483

I can test and confirm this is still an issue later.
