### ISSUE TITLE
Stats: Insights missing days of views, or taking a long time to update

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#52556]
### Steps to reproduce the behavior

1. Go to Stats > Insights
2. Scroll to Views
3. Compare to Monthly views for previous month
4. We have many reports of these not adding up (see screenshots below)

### Context

p56BUd-nh-p2 has multiple reports
3953662-zen
3924210-zen
3918071-zen
3902502-zen
3901537-zen
3894897-zen
3894972-zen

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It impacts multiple sites, but the monthly stats are still correct.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Intermittent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image (9)](https://user-images.githubusercontent.com/31680407/117011445-d8bc1a00-acbb-11eb-8b11-9eb5c78eabed.png)

![image (10)](https://user-images.githubusercontent.com/31680407/117011503-e6719f80-acbb-11eb-8a34-06d944d310e1.png)

**Comment by supernovia** [comment]
We have some cases here:
https://wordpress.com/forums/topic/insights-is-undercounting-views/

@kosiew thought it might be a lag. I'm also suspecting a lag since my users said their previous month's stats seem more accurate now.

**Comment by jinnypark** [comment]
Another case from Jetpack user (self-hosted) in 3955402-zen. 
Jetpack debug shows site sync is up-to-date.

**Comment by scosgro** [comment]
Another report on 3961054-zd

**Comment by kuropixel** [comment]
4017013-zd
I've got a user experiencing this issue again it seems. 
The user was reporting 4.4K views for the month of May via the insights tab. 
On my side, I saw 4.6K. We both exchanged screenshots and the user tried from various browsers and machines but was unable to see the latest stats/insights.

**Comment by mikeicode** [comment]
29720458-hc Customer returned saying this has happened the last 3 months, the insights total are incorrect for the monthly views.

**Comment by kristarella** [comment]
Related to @kuropixel post above for ticket 4017013-zd

I am seeing something different to what the user sees - they sent a screenshot less than an hour ago.

**User screenshot**
![Monthly Insights (0601210](https://user-images.githubusercontent.com/2031017/120427791-eb5a6980-c3b5-11eb-8a2b-24ea993f3ccb.JPG)

**My screenshot**
![image](https://user-images.githubusercontent.com/2031017/120427814-f614fe80-c3b5-11eb-9954-072cd30668de.png)

Notice that not only are the last two numbers different (and closer match the Stats view), but we have other months that are different (Apr 2021, Feb 2021, Oct 2020, Sep 2020, Mar 2020, maybe some further back).

I'm wondering if local browser/computer time is having some impact on Insights, but not on Stats. In addition, or instead of a delay in the display?

**Comment by susanjanec** [comment]
4130736-zen - user reports that average daily views are inaccurate - they report from July 1-9 they have 6331 views and the average daily views should be 703 but showing 575 for the month of July so far.

I checked for June which their views were 24,039 and if my math is correct the average daily views should be 801 since there are 30 days in June. The average daily views for June shows at 793. Is there an explanation on the discrepancy?

**Comment by marianearchimbaud** [comment]
Similar report here: 
4322182-zd
31842086-hc
different number on stats view and insights view:
https://d.pr/i/sUJO4Z
https://d.pr/i/jCU8NH

**Comment by jackiejade** [comment]
29956898-hc User came back to check on this open issue for a few months now this has been effecting their site.

**Comment by jorpdesigns** [comment]
Similar report here: 8091525-hc

User screenshot:
![user](https://user-images.githubusercontent.com/40006288/152167243-8713815b-2b85-44a7-9381-f2b1fbd42175.png)

My screenshot:
<img width="1265" alt="mine" src="https://user-images.githubusercontent.com/40006288/152167266-bccd27c7-1a25-4dc7-8923-e78d4d62cdeb.png">

**Comment by poeticabdul** [comment]
Similar report here 35507580-hc

**Comment by aidvu** [comment]
The Traffic/Insights discrepancies should be fixed with D82402-code.

As for the "miscounts" or different results seen by HEs and customers, the stats queries are cached. They are not real-time, but should be close enough.

Closing this one. Feel free to reopen if any more reports come in.
