### ISSUE TITLE
When "WordPress.com Editing Toolkit" plugin is deactivated, site becomes public but settings page still shows launch button

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#52596]
Originally reported in https://github.com/Automattic/wp-calypso/issues/48316

Coming soon is dependent on the full site editing plugin to work, but in atomic sites it is possible to deactivate the ETK plugin. In this scenario, the site will be public but the settings page UI indicates that the site is still "unlaunched"

We did discus this side effect of using the ETK to implement coming soon v2 previously, and I don't think we should re-architect it. But we should fix the settings page so that if the ETK is deactivated, it shows the site as launched with the normal privacy options.
<img width="756" alt="Screen Shot 2021-05-05 at 11 15 26 AM" src="https://user-images.githubusercontent.com/22446385/117087613-61f25000-ad93-11eb-9169-80f4cf106e04.png">

**Comment by inaikem** [comment]
> But we should fix the settings page so that if the ETK is deactivated...

If we're unable to stop this from occurring, I'd also like to ensure there's some obvious messaging in place to users. this could either be as part of a 2-step plugin deactivation or something similar to the notice that appears when block themes are enabled on Atomic sites:

> You're using an experimental Full Site Editing theme. Full Site Editing is an experimental feature and potential API changes are to be expected!

To make things simpler still, would it be possible to throw a window alert to say "_Disabling this plugin will make your site public_", or something equally quick and easy to understand?

**Comment by kaitohm** [comment]
Just noting a user who was confused by this: 30858570-hc

**Comment by Nic-Sevic** [comment]
p1638882010280300-slack-C03TY6J1A - similar case here where `full-site-editing` was deactivated after site launched but coming soon persisted in calypso. Site was set to public and displayed public.
To resolve had to activate fse plugin > set to private > save > set to public > save > deactivate fse plugin (because user didn't want, not because flag persisted)

**Comment by zachspears** [comment]
I tested this and was able to replicate it. I would also note that the site shows "Coming Soon" in the dashboard menu: 
<img width="417" alt="Screen Shot 2022-05-19 at 9 07 13 PM" src="https://user-images.githubusercontent.com/10124024/169442610-16041b08-1835-4694-ae8e-2fa8c4268528.png">

I am thinking this may have to due to the fact that "Coming Soon" is a feature of this plugin, which is also why you will not see this feature on the Settings > General page: 
<img width="733" alt="Screen Shot 2022-05-19 at 9 09 29 PM" src="https://user-images.githubusercontent.com/10124024/169442937-2a411a5e-161e-4702-8b99-016fd1ec4013.png">

Workaround: Either set page to Private, or Activate plugin again to enable Coming Soon functionality.

**Comment by arthur791004** [comment]
> the site will be public but the settings page UI indicates that the site is still "unlaunched"

I'm curious about why the site will become public when the ETK plugin is deactivated. It's weird that activating/deactivating a plugin will affect the privacy settings 🤔

**Comment by arthur791004** [comment]
Oh, I got the reason. The coming soon feature is based on the `blog_public: 0` and it's [the default value for the newly created site](https://github.com/Automattic/wp-calypso/blob/51d5a41b87e863b458f81ef3dde2325bfe9fe5bb/packages/data-stores/src/onboard/actions.ts#L48). IMHO, this is weird and the public status of the site before launch should be private. If not, why do we need “Launch site” feature 😂

Note the value of the `blog_public`
* 1: public
* 0: public but search engine hidden
* -1: private
