### ISSUE TITLE
Quick start purchase shows two success notices

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#52611]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/start and signup as a new user.
2. Purchase a Personal plan in the signup flow, and after successful completion of the purchase, you should then be shown the Quick Start upsell.
3. Purchase a Quick Start session from the upsell page.
4. After successful completion of the purchase, you will be taken to Customer Home

#### What I expected to happen

To see a purchase success floating notification

#### What actually happened

I saw two floating notifications with the same message

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![qssn](https://user-images.githubusercontent.com/1269602/117125004-a4795400-adb6-11eb-8e1e-5f4b1f63535c.gif)

**Comment by simison** [comment]
@michaeldcain would this be good for your team?

**Comment by michaeldcain** [comment]
@simison: we can talk about it in our next call. I haven't looked into it, but it's similar to the bug in #50432 that was fixed in #50540.

**Comment by sirbrillig** [comment]
I haven't looked into this yet but just from looking at the video my guess would be that the first notice is from the upsell nudge:

https://github.com/Automattic/wp-calypso/blob/f9def4bfd3958309062af5d9aa136242205a8616/client/my-sites/checkout/upsell-nudge/purchase-modal/index.tsx#L59

and the second notice is from customer home:

https://github.com/Automattic/wp-calypso/blob/f9def4bfd3958309062af5d9aa136242205a8616/client/my-sites/customer-home/main.jsx#L62

I bet what happened is that the upsell didn't use customer home as a thank-you page and then changed so that it uses it now.

If I'm right, that's tricky to resolve because the customer home page notice has no real knowledge of checkout; it just reacts to the presence of a query string in the url which is added by this code:

https://github.com/Automattic/wp-calypso/blob/f9def4bfd3958309062af5d9aa136242205a8616/client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts#L435

I think there's a way to change [the logic that generates that URL](https://github.com/Automattic/wp-calypso/blob/f9def4bfd3958309062af5d9aa136242205a8616/client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts#L220) in `getThankYouPageUrl()` so that it only adds the notice query string in cases where it's required. The hard part will be to determine when it's required. It was added in https://github.com/Automattic/wp-calypso/pull/49612 by @niranjan-uma-shankar so he may be able to help us figure that out.

**Comment by michaeldcain** [comment]
From our planning call:

The right solution might be to just remove the notice from the up-sell. If that doesn't break anything, then we celebrate.
