### ISSUE TITLE
Signup: make Skip more visible

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#52633]
### What
Add a more clear Skip button to steps that can be skipped.

- Example of a step where the skip button is not in the first screen:
<img width="800" alt="Screenshot 2021-05-06 at 09 47 45" src="https://user-images.githubusercontent.com/14192054/117257201-4e5aee00-ae54-11eb-85a5-4d60ccc5b219.png">

- The button is currently at the very button of the screen where usually a "show more results" button is expected:
<img width="800" alt="Screenshot 2021-05-06 at 09 46 55" src="https://user-images.githubusercontent.com/14192054/117257214-531fa200-ae54-11eb-8fb5-fbb203c56177.png">

The example above may be fixed with the introduction of Blank Canvas but we'll have more steps in the same situation (eg: Font Selection, Feature Selection, Goals, etc)

### Why
Some users may not be ready immediately after signup to make decisions on all the optional steps in the onboarding. Having a clear, visible, _Skip_ button may help them to complete the signup flow and make those decisions later.

### A/C
- [ ] Skip button should be displayed above the design options on the Design step of `/start/with-design-picker` onboarding flow

**Comment by ollierozdarz** [comment]
Good thinking @razvanpapadopol!

There's no **pretty** way to do this, since the start framework doesn't already have a pattern for skipping, so let's just move the Skip link under the heading and above the designs. I don't think this page will be in existence for too much longer (because of the Reskin), so it's not worth us making more complex changes 🙂

<img width="1435" alt="Screen Shot 2021-05-07 at 1 39 02 pm" src="https://user-images.githubusercontent.com/67085494/117394811-32317c80-af3a-11eb-9e3e-30392b82050a.png">

**Comment by razvanpapadopol** [comment]
Thanks for your input, @ollierozdarz!

The suggested change is ready to be tested in https://github.com/Automattic/wp-calypso/pull/52666

**Comment by razvanpapadopol** [comment]
Not applicable anymore
