### ISSUE TITLE
Themes: Spike on surfacing patterns as themes in the Showcase.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52724]
We'll first need to do a spike on what's involved for surfacing patterns as themes. We'd like to let users see that there are more options when a single theme has multiple associated patterns; see pd2qbF-l-p2 for more context and details.

**Comment by kwight** [comment]
@blackjackkent Can you give an update here please?

**Comment by blackjackkent** [comment]
My productivity on this has been less marked than I would have liked due to this week being hectic and broken up, but there's been a considerable amount of discussion going on on P2 (pd2qbF-l-p2) which I will attempt to summarize here:

- The primary concern here is a disconnect in user experience between the signup process and the theme showcase. A user who selected the Baker pattern on signup sees their theme represented in the theme showcase as just "Blank Canvas", and they also won't be able to find the patterns from the signup process in the showcase if they want to go back and try one of them later.
- The two major approaches under discussion are:
    - Create multiple theme packages, each combining different default content with the base blank canvas theme, in order to display them all as separate options in the theme showcase to parallel their appearance as patterns in the customizer. This would be a more backend strategy involving customizing build scripts.
    - Update the way the theme API works to include alternative sources for displaying items in the theme showcase, customized for this purpose. This would be a more front-end approach and would require more logic to make sure the theme showcase understands the distinction between the user having a theme enabled and the user having Blank Canvas enabled with a pattern attached.

It also seems to me that to a certain extent this may be something that could be addressed by updated wording during pattern selection that emphasizes the distinction from themes so the user isn't surprised by the behavior later on, and I have noted this in the discussion as well.

To be honest, I'm still feeling a little out of my depth as far as understanding how the systems behind theme packaging and then serving from the API works, so I'm going to spend some of my 20% time trying to delve further into that.

**Comment by kwight** [comment]
Thanks – we're likely lean towards option 1 (we'll get proper Theme Showcase and Atomic behaviour for free, since we're generating legit themes, rather than injecting fakes). cc/ @ianstewart

**Comment by ianstewart** [comment]
Some notes on how we might approach this from a "use a script to create themes based on target sites" standpoint, for discussion and potential mile-stoning. (Note: this is mostly based on me thinking about how I might approach this if I were creating a theme manually so please feel free to dismiss all of these ideas.)

This assumes we have a target site on Dotcom that we can pass to the script as an arg like mycoolnewthemename dot WordPress dot com.

- Script forks target site theme (we'll start with just Blank Canvas to keep it simple), merely by changing directory. (Could be an arg for a new theme slug.)
- Script forks target site theme in sandbox to /pub (or maybe /pub/generated if we wanted to cordon it off).
- Script changes all theme-slug-based strings in target site theme fork to create a "proper" named fork.
- Script generates Headstart Annotation. (I assume it would just run the existing command or this all would just be new Headstart script functionality.)
- Script generates theme screenshot with Mshots.
- Script will also over-write all generated files just in case we have an update from the original theme. Otherwise, maintenance could potentially get out of hand. (This would be a reason to cordon off themes in /generated so that we remind ourselves not to make direct edits.)

For testing I believe it's possible to change the theme of a site to any not-yet-Network-activated site via Network Admin?

At this stage we could potentially launch a generated theme. We'd need to create a showcase page as well. That's a manual process but I just wanted to note it.

Some potential next steps.

- Launch a theme. :)
- We figure out how to use the fonts and colours on the target site and apply them to the generated theme. (I'm pretty sure we could potentially script colour changes in a v1 but want to be mindful of scope.)

**Comment by ianstewart** [comment]
I'll create a simple target site for us to use to make this less abstract. :)

**Comment by ianstewart** [comment]
I set up this site: (cc @alaczek)

https://bakerstarterdesign.wordpress.com/

![image](https://user-images.githubusercontent.com/545779/118309691-3c5ff780-b4b3-11eb-924d-4e22c13a5ffb.png)

When we turn on FSE Blocks like "Site Title" I'll be updating the site content to use those. Shouldn't affect anything but just wanted to note it.

If anyone needs to be added as an admin there, just let me know!

**Note:** I may change the domain later to bakerdemo or bakerthemedemo. Shouldn't affect anything except it might break a link while we're testing.

**Comment by youbrokesomething** [comment]
@ianstewart I'm cleaning up old GitHub issues with the bug label. I'm going to close this as it seems like the spike was completed. Please reopen it if it's still needed!
