### ISSUE TITLE
Themes: Script a method for generating themes based on patterns.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52848]
We'd like to develop a script that will allow us to quickly launch new parent themes (forked from a base theme) with homepages based on block patterns. Are rough sequence of operations would be:

* Script forks theme in sandbox to `/pub` (or maybe `/pub/generated` or something) and just changes slug based on title of target site.
* Script changes all strings in the Blank Canvas fork (or whatever the parent theme is).
* Script generates Headstart annotation.
* Script generates theme screenshot.
* Script will over-write all generated files just in case we have an update from the original theme.

See: pd2qbF-l-p2

**Comment by kwight** [comment]
I've assigned @mreishus to lead this task. 🎉

**Comment by ianstewart** [comment]
I left a some notes on https://github.com/Automattic/wp-calypso/issues/52724#issuecomment-841357855 related to this.

**Comment by ianstewart** [comment]
Moving my notes over to this issue.

Some notes on how we might approach this from a "use a script to create themes based on target sites" standpoint, for discussion and potential mile-stoning. (Note: this is mostly based on me thinking about how I might approach this if I were creating a theme manually so please feel free to dismiss all of these ideas.)

This assumes we have a target site on Dotcom that we can pass to the script as an arg like mycoolnewthemename dot WordPress dot com.

- Script forks target site theme (we'll start with just Blank Canvas to keep it simple), merely by changing directory. (Could be an arg for a new theme slug.)
- Script forks target site theme in sandbox to /pub (or maybe /pub/generated if we wanted to cordon it off).
- Script changes all theme-slug-based strings in target site theme fork to create a "proper" named fork.
- Script generates Headstart Annotation. (I assume it would just run the existing command or this all would just be new Headstart script functionality.)
- Script generates theme screenshot with Mshots.
- Script will also over-write all generated files just in case we have an update from the original theme. Otherwise, maintenance could potentially get out of hand. (This would be a reason to cordon off themes in /generated so that we remind ourselves not to make direct edits.)

For testing I believe it's possible to change the theme of a site to any not-yet-Network-activated site via Network Admin?

At this stage we could potentially launch a generated theme. We'd need to create a showcase page as well. That's a manual process but I just wanted to note it.

Some potential next steps.

- Launch a theme. :)
- We figure out how to use the fonts and colours on the target site and apply them to the generated theme. (I'm pretty sure we could potentially script colour changes in a v1 but want to be mindful of scope.)

**Comment by ianstewart** [comment]
I set up a site for us to target. cc @alaczek

https://bakerstarterdesign.wordpress.com/

![image](https://user-images.githubusercontent.com/545779/118309691-3c5ff780-b4b3-11eb-924d-4e22c13a5ffb.png)

When we turn on FSE Blocks like "Site Title" I'll be updating the site content to use those. Shouldn't affect anything but just wanted to note it.

If anyone needs to be added as an admin there, just let me know!

**Note:** I may change the domain later to bakerdemo or bakerthemedemo. Shouldn't affect anything except it might break a link while we're testing.

**Comment by kwight** [comment]
@mreishus We're going to take more time to prepare this mini-project – let's leave it for later.

**Comment by kwight** [comment]
A high-level overview of the process:

* Begin with a starter demo site (eg. rileystarter.wordpress.com).
* Do a fork of Blank Canvas.
* Replace necessary strings (`blank_canvas_`, `blank-canvas`, etc)
* Update color annotations values.
* Update color globals for the block editor (`variables.css`).
* Update fonts.
* Ads need to be taken into consideration for colors (TBD).
* Pull in homepage content from the demo site (using Headstart).

Some things to keep in mind:
* Can we do a PHP library (functions, simple ins and outs, similar to Anchor) that can be used by other mediums (API endpoint, MC, WP-CLI on sandboxes)?
* How do we identify these generated themes? We can use taxonomies in the Theme Showcase.
* What does maintenance look like? Updating themes by script should be repeatable, and devs should somehow be discouraged from making direct code updates to the theme itself (top-of-file comments (à la Fusion), commit blacklist?).

**Comment by ianstewart** [comment]
> Replace necessary strings (blank_canvas_, blank-canvas, etc)

I mentioned this on our call but I think there is prior art in this repo for doing some of this with PHP. I don't know how valuable it is. It's pretty old, and based on a particular theme, [_s](https://github.com/Automattic/_s).

It's the code that handles all this. 

![image](https://user-images.githubusercontent.com/545779/120555927-68d7a700-c3c1-11eb-9d88-73f3d621d238.png)

**Comment by mreishus** [comment]
D62155-code

**Comment by kwight** [comment]
Our first version of this script and library have been merged via D62155-code.
