### ISSUE TITLE
Editor: Tags with diacritics considered the same as without and vice versa

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#5286]
#### Steps to reproduce
1. Add new post;
2. Add tag `haló`;
3. Publish post;
4. Add tag `halo` and update post;
5. Tag `halo` removed, tag `haló` staying.
6. If you started with `halo` (can try different tag), it would behave the same but this time `haló` would be removed and `halo` would stay.
#### What I expected

Post with tags `haló` and `halo`.
#### What happened instead

Post with tags `haló`.
#### Browser / OS version

Newest Chrome, Ubuntu.
#### Notes

This bug was reported by a user through 1154090-t.

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the steps provided. ([40s](https://cloudup.com/cMh7732Ebou))

![screen shot 2016-08-30 at tue aug 30 3 44 08 pm](https://cloud.githubusercontent.com/assets/1119271/18108268/cf66ff0a-6ec8-11e6-868a-f2c3f9a7f0c4.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10294 using Firefox 48.0.1 on Mac OS X 10.11.6</sup>

**Comment by designsimply** [comment]
I re-tested adding tags with and without diacritics to a post, and confirmed the problem is still happening. Tested with Safari 10.0 on Mac OS X 10.11.6. ([43s](https://cloudup.com/cOzMNW5H6qa))

Recommend closing this issue at the next #bug-scrub if there has been no action by then since it has been over 5 moths since the issue was opened and it appears to be a low priority issue in the sense that it is probably uncommon to want to add both versions of a word with and without diacritics as tags.

**Comment by folletto** [comment]
>  it is probably uncommon to want to add both versions of a word with and without diacritics as tags.

Yep. I agree with this. This seems more a decision on "how tags are done". The current assumption is that tags get normalized. 

The issue here is that the Editor isn't aware of that normalization, so I'd probably treat this similarly to my suggestion in #12792.
