### ISSUE TITLE
Editor: Add Markdown support

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#529]
The Calypso Editor supports formatting shortcuts from [WordPress.com 4.3](https://wordpress.org/news/2015/08/billie/), but does not currently support the Markdown format that is [available from the WP Admin editor](https://en.support.wordpress.com/markdown/) on WordPress.com.

**Comment by lamosty** [comment]
Agree. This was the first bigger issue I noticed with Calypso.

**Comment by sirbrillig** [comment]
You can actually use Markdown in Calypso if you enable it in wp-admin first. The editor would just need to incorporate a "enable Markdown" option. (Of course, that may be misleading since the Markdown option (currently) applies site-wide and not just for the current page.)

**Comment by notesbytom** [comment]
Hello @sirbrillig - when testing Calypso a month ago, the markdown support seemed to convert everything to shortcodes and html when saving a new edit. Returning to edit a blog post in the future would then be missing all of the original markdown used to create the post. Has this changed to keep the markdown with the blog-post text for future edits? I had "enable Markdown" selected in wp-admin during that test. I've been using only wp-admin since Calypso released so that my markdown is preserved.

**Comment by sirbrillig** [comment]
@notesbytom hey, you're right! I hadn't tried going back in and editing the posts again. That's another thing that needs to be fixed.

**Comment by electronicsguy** [comment]
@sirbrillig Any update on this? I tried turning ON markdown within wp-admin today. I went to one of my existing posts and tried to use markdown instead of <code> </code> tags, but it doesn't work.

**Comment by sirbrillig** [comment]
@codebykat, do you know if anything like this is in the works?

**Comment by codebykat** [comment]
I'd like to get it done but other things are more on fire at the moment... if someone can submit a PR I would be happy to review. Otherwise we'll try to get to it but can't promise when. Please do log votes here as that helps us prioritize new features. :)

**Comment by lancewillett** [comment]
I think we should remove support for Markdown in Calypso — it's a power-user feature, and not something the majority of bloggers or site owners would ever know or care about. Let's focus instead of a delightful and engaging experience in the visual editor.

There are many recent improvements (from core WP wp-admin editor as well) that allow for using typical Markdown syntax in the visual editor. Try typing ` and then again after a word. Boom. Code formatting. Same with asterisk for bold.

Let's work on the editing experience for *everyone* and to me that doesn't include Markdown.

**Comment by lancewillett** [comment]
Moving discussion to https://github.com/Automattic/wp-calypso/issues/5110

**Comment by wilx** [comment]
[**@lancewillett**](https://github.com/lancewillett) commented on [21. 2. 2017 16:27 SEČ](https://github.com/Automattic/wp-calypso/issues/529#issuecomment-281376463 "2017-02-21T15:27:20Z - Replied by Github Reply Comments"):
> I think we should remove support for Markdown in Calypso — it's a power-user feature, and not something the majority of bloggers or site owners would ever know or care about. Let's focus instead of a delightful and engaging experience in the visual editor.
> 
> There are many recent improvements (from core WP wp-admin editor as well) that allow for using typical Markdown syntax in the visual editor. Try typing ` and then again after a word. Boom. Code formatting. Same with asterisk for bold.
> 
> Let's work on the editing experience for _everyone_ and to me that doesn't include Markdown.

Are you really giving :thumbsup: to your own post for real?

**Comment by lancewillett** [comment]
Hahaha. Yes. Good eye. :)
