### ISSUE TITLE
Checkout: when purchasing a Jetpack Search addon for a free plan, the message "Sorry, but we were not able to find that coupon" is shown

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#52904]
### Steps to reproduce the behavior

1. Sign up for a brand new WordPress.com free account
2. Go to Jetpack > Search and click subscribe to the Jetpack Search monthly plan

#### What I expected to happen
I am shown the monthly Jetpack Search plan in the checkout and I can buy it without issues.

#### What actually happened
I am shown the monthly Jetpack Search plan in the checkout but with a persistent notice about not being able to find a coupon. I had not applied a coupon.

### Context

Found while looking for Search signup bugs on wpcom.

#### Does this happen on simple or atomic sites or both?

Only tested with a simple site.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

The checkout process still works, but it's confusing and may put off a new user from going through the checkout.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1762" alt="Screen Shot 2021-05-17 at 16 53 39" src="https://user-images.githubusercontent.com/17325/118434033-72f67600-b730-11eb-8c93-e0a37baf1fc6.png">

cc @Automattic/shilling

**Comment by sirbrillig** [comment]
This is probably because of the FRESHPACK coupon (https://github.com/Automattic/wp-calypso/pull/50138). The coupon still seems to be active, so if it's not working then I assume it's because some condition of the coupon is not being met (eg: it was already used by the user). I think that an auto-applied coupon is probably not the right way to offer this discount. Pending approval, I've created https://github.com/Automattic/wp-calypso/pull/52922 to remove that feature.

**Comment by bluefuton** [comment]
@sirbrillig I _think_ I've seen the FRESHPACK coupon code successfully apply for Jetpack plans (like Jetpack Professional) but not for the Jetpack Search add on - would that make sense?

**Comment by sirbrillig** [comment]
That's a good theory, @bluefuton. I checked and the server says FRESHPACK should work for Jetpack Search as well, and the authors of the front-end code made it so that it applies to all Jetpack plans and products, so unless something is malfunctioning there, I don't think that's the issue.

We've decided to postpone removing the coupon auto-application for the time being, but I've created D61506-code which will make it so that you get a more specific error message when a coupon fails to be applied and hopefully that will let us track down this specific issue. If my guess is right and it is indeed the restriction that prevents using a code more than once for a user and/or a site, then D61507-code should fix that by allowing FRESHPACK to be applied multiple times.

**Comment by michaeldcain** [comment]
> I checked and the server says FRESHPACK should work for Jetpack Search as well

I think this is because the `FRESHPACK` coupon isn't available for "Jetpack Search for WordPress.com", and IIRC, we do some strange mapping in the codebase to make the two products look like one in Calypso. We can probably enable it for WPcom sites just to "fix" this issue until a better fix is in place.

<img width="255" alt="Screen Shot 2021-05-18 at 4 34 30 AM" src="https://user-images.githubusercontent.com/942359/118619227-6276e780-b792-11eb-9fee-50ad5f16e372.png">

**Comment by michaeldcain** [comment]
"Fixed".

<img width="1154" alt="Screen Shot 2021-05-18 at 4 37 25 AM" src="https://user-images.githubusercontent.com/942359/118619650-cac5c900-b792-11eb-81a9-1ec07bdd99fb.png">

**Comment by sirbrillig** [comment]
Wow, nice find! It's a little weird to me that Jetpack Search for WordPress.com [shows up as a "jetpack" product as defined by this line](https://github.com/Automattic/wp-calypso/blob/2b3fbddb6da1d2e43bb4d6ac611eb6958dd4f030/client/my-sites/checkout/composite-checkout/hooks/use-maybe-jetpack-intro-coupon-code.ts#L30). I wonder if that's a bug. 

This is why:

https://github.com/Automattic/wp-calypso/blob/2b3fbddb6da1d2e43bb4d6ac611eb6958dd4f030/packages/calypso-products/src/constants/jetpack.ts#L56-L60

**Comment by michaeldcain** [comment]
> I wonder if that's a bug.

Just to close the loop, we discussed this on our call today and it was an intentional decisions. Jetpack Search and Jetpack Search for WPcom are essentially the same product, and should appear the same to the user with the exception that one can be purchased on simple sites.

**Comment by bluefuton** [comment]
Thanks for tracking this down @michaeldcain and @sirbrillig! Much appreciated.
