### ISSUE TITLE
My Home: Update copy in setup checklist so it changes depending on whether the the task is complete

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#52936]
The tense of the copy in the setup checklist doesn't change when the task gets completed. E.g. "launch site" doesn't change to "site launched", we just put a tick beside the item and hope that'll be clear enough.

In 490-gh-dotcom-manage @mreishus reported it felt strange.

![2021-02-22_14-25](https://user-images.githubusercontent.com/937354/108765731-c7b39780-7519-11eb-8b7b-5514b1b3d7f2.png)

At pd2qGl-7s-p2 we're coming up with new copy each task in the checklist, which could be different depending on whether the task is complete or not. The task here is to implement these changes once the copy changes have been settled.

**Comment by p-jackson** [comment]
So turns out this issue isn't unique to the "launch your site" task. The task descriptions don't change after the task has been complete.

The email verification task is still telling the user to verify, although it is clear from the disabled button that it doesn't need to be done again.
![Screen Shot on 2021-06-02 at 11:55:22](https://user-images.githubusercontent.com/1500769/120403966-6f522880-c399-11eb-8c79-45c25e6acdeb.png)

The site naming task text hasn't changed, but that's sort of fine because changing the site name is always an option, and the text is generic enough.
<img width="940" alt="Screenshot 2021-06-02 at 11 54 42 AM" src="https://user-images.githubusercontent.com/1500769/120403992-7c6f1780-c399-11eb-9ba6-f693e6376f59.png">


---

For the launch card I think the options are:

1. We do nothing; all the cards work this way and the `[Complete]` badge and disabled `[Launch site]` button are clues enough
2. Change the copy to make it work for both the launched and unlaunched states e.g. "A private site is is only visible to you. Launching your site will make it public for everyone!"
3. Do something custom for this card so the text changes based on whether the task is complete (or perhaps update all tasks to work this way)

Do any of these ideas fit with your thoughts for the future of the checklist @jeffgolenski?

**Comment by jeffgolenski** [comment]
Great thoughts here @p-jackson @roo2! For the short-term, I think each individual action needs to be broken down into past-tense, but also provide different direction.

Since the checklist effectively disappears after launch, I don't want people getting comfortable using the checklist as a place to keep coming back to perform edits. Example: After they name their site, I don't want them to keep coming back to that card to change their site name over and over—that forms a temporarily mental model that will be broken the minute they launch. I want them to learn where in wordpress.com to do that (settings). 

Here's what I'm thinking for a few of the cards at first glance:

**Name your site**
<img width="1072" alt="Screen Shot 2021-06-02 at 12 19 18 PM" src="https://user-images.githubusercontent.com/214813/120515965-de7d4c00-c39c-11eb-9235-7896f08823dc.png">

* Complete label is still there
* Title remains the same (or maybe it changes as well)
* Descriptive text indicates where they can go to change this in the future and helps them explore wordpress.com more
* CTA becomes a secondary CTA and directs them to where they can change the subject of the card (site name in this case)

Very similar to the email confirmation card after confirmation, but we've tightening up the UI a bit and removed a link in the pattern.

**Launch card**

@p-jackson I think for the launch card, a mix of items 2 & 3 in your comment above is probably the best way to go. First of all, do we have metrics on how many people revisit the checklist after launch? cc @autumnfjeld 

1) Pre-launch: First and foremost, I'd love for us to add "You can launch your site at any time" to the launch card, so it clarifies that people do not need to accomplish each task in the list if they don't want to.
2) Post-launch: If the task is complete, let's use the formula I mention above.

<img width="725" alt="Screen Shot 2021-06-02 at 12 32 30 PM" src="https://user-images.githubusercontent.com/214813/120517606-9f4ffa80-c39e-11eb-86cd-896bf4c7a84b.png">

I'll continue to think about these patterns as I progress. But how do we feel about this for the short-term?

**Comment by jeffgolenski** [comment]
@michaelpick @sethmclellana8c — would love your thoughts on the above convo. Mainly differentiating between current and past-tense states of the checklist. Keeping in mind that customers can visit the checklist post launch as well.

**Comment by p-jackson** [comment]
Makes sense @jeffgolenski, adding incomplete/complete variations for each card fits in well with the current code structure so no problems there. When the time comes I think I'll do a p2 with every task listed so we can see every change.

**Comment by michaelpick** [comment]
> would love your thoughts on the above convo. Mainly differentiating between current and past-tense states of the checklist. Keeping in mind that customers can visit the checklist post launch as well.

I like the solution you've outlined, Jeff, and how it teaches the user to fish rather than increases dependency on the checklist or My Home outside of its intended purpose.

For the checklist itself, I'd say that consistency in the experience trumps a switch in the tense here. Most of us are familiar with checklist to-do items, and the idea of completing them without the task description itself changing. It feels like a well-established mental model. With that in mind, I'd skip changing the copy here.

One caveat on relying on primarily visual cues, though, is accessibility. Presumably, the checkmarks indicating completion have semantically sound alt-text that would ensure that screenreader users can differentiate between complete and incomplete list items?

---

Aside: I'm not a designer, so take this with a huge pinch of salt, but I wonder if the visual shorthand of the grey circles for unchecked items entirely communicates tasks that haven't been completed 🤔  

An _empty_ circle, square checkbox, or other more familiar visual cue as to their incomplete task status might disambiguate here, possibly.  As is, the combination of lighter weight text and grey circles vs heavier weight text and checkboxes for complete items visually deprioritizes them, which may be the opposite of what we're hoping to achieve. I appreciate that this might be part of a design system or that there are other factors in play -- just floating that.

**Comment by p-jackson** [comment]
> One caveat on relying on primarily visual cues, though, is accessibility. Presumably, the checkmarks indicating completion have semantically sound alt-text that would ensure that screenreader users can differentiate between complete and incomplete list items?

On this a11y point, unfortunately not. My Home is really lacking a number of basic a11y features e.g.  tab navigation, visible focus, semantics for checklist etc.
It's one of the things I've got in my head that I'd like to improve while we're working in this area.

**Comment by michaelpick** [comment]
>> One caveat on relying on primarily visual cues, though, is accessibility. Presumably, the checkmarks indicating completion have semantically sound alt-text that would ensure that screenreader users can differentiate between complete and incomplete list items?

> On this a11y point, unfortunately not. My Home is really lacking a number of basic a11y features e.g. tab navigation, visible focus, semantics for checklist etc.

Ah! If there isn't a better solution that lets us keep consistency, that could make the case for switching tense after all.

A few ideas:

### Consistency focused

One way to handle it would be to keep things as consistent with the original wording as possible:

- Name your site > Named your site
- Update your homepage > Updated your homepage
- Edit the site menu > Edited the site menu
- Launch your site >  Launched your site
- Confirm your email address > Confirmed your email address
- Get the WordPress app > Got the WordPress app

Note on the above: 'Edit the site menu' could be changed to 'Edit your site menu' if that isn't too clunky. The other items (except the app download) use 'your'. 'Update your site menu' perhaps sounds more natural? In which case:

- Update your site menu > Updated your site menu

This approach could help to avoid confusion when the checklist items change, as it's basically a tense switch. It's functional and simple.

### Clarity focused

A variation of the above that slightly breaks consistency, but increases readability for being more direct (at the cost of the 'personal touch')

- Name your site > Site named
- Update your homepage > Homepage updated
- Edit the site menu > Site menu edited
- Launch your site >  Site launched
- Confirm your email address > Email address confirmed
- Get the WordPress app > WordPress app installed

You could quite possibly add a little more personality to either, but for a checklist I'm usually thinking about using as few words as necessary to focus on the action. 

### Personality flavoured

Here's what a very slightly more personality-augmented take might look like:

- Give your site a name > Your site has a name
- Update your homepage > Your homepage is good to go
- Customize your site menu > You've set up your menu
- Take your site live / Launch your site to the world >  Your site is live / You've launched your site!
- Confirm your email address > Your email address has been verified
- Try the WordPress app > You've installed the WordPress app

We could certainly turn this very subtle personal touch approach up to eleven (happy to give that a shot if that's the direction you'd like to go).

To my mind, the '[clarity focused](#clarity-focused)' take gets this done most effectively.

**Comment by jeffgolenski** [comment]
@michaelpick Thanks for the great breakdown there. I think you list of personality flavored reads very nicely. Feels natural and    concise!

**Comment by sethmclellana8c** [comment]
- Agree with @michaelpick 's comment above that checklists and "Complete" tags are pretty universally understood. So we shouldn't fuss too too much.
- I agree the email card reads much more naturally, as you pointed out @jeffgolenski  .
- I hadn't thought about the subtle effect of "being trained to go to the checklist to do things", though I agree this could be an issue for some users and we definitely don't want to reinforce that.

Cognitively, I was a little confused looking at a completed card with the tag "Complete".

- It's round, which suggests a "tag" or "status" to me [great]
- but it's black which indicates that it might be indicating "what I need to do" - versus it being green for example [not what we want]
- but there's a checkmark next to the item in the checklist [ok, so it's done?]
- and then I wonder whether the status should read "Completed"
- Plus the Launch card is all in the tense of the task needing to be done

Returning to the overall experience from the start, now I'm actually really confused. Even by spending minutes interpreting what I'm seeing.

I had similar thoughts to Michael in terms of titles. I strongly feel that Michael's "Consistency" wording is awkward and shouldn't be implemented. And I gravitate strongly to the "Personality flavoured" tone above.

However, I would argue that the checklist language could stay the same. Resulting changes would feel like this:

Side: [Checkmark] Name your site -->
Card: [Completed] Your site has been named (change description beneath as you suggested, Jeff)

Sort of a "This was your original To do list" --> "Here are the notes of how it went". Might cut down a little bit on the cognitive load of interpreting a "new checklist"

SIDE NOTE: In @roo2 's original post, the "Name your site" item is complete in the list, list as "Complete" in the card, but the button isn't greyed out as it should be. Confusing. I realize you can rename it at any point, but there shouldn't be a perpetual "You can always change this" in a To Do list. Cross it off.

**Comment by p-jackson** [comment]
I've created a spreadsheet where we can come up with the new copy. Going to subtly try and nudge the conversation to p2 since that's where the spreadsheet is linked from pd2qGl-7s-p2 :nudge:

**Comment by p-jackson** [comment]
We made small improvements to the copy here: #54749, but decided against changing copy based on whether the task was complete or not.
