### ISSUE TITLE
Video block doesn't work in site editor

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#52949]
### Steps to reproduce the behavior

1. Go to site editor ([create a new site](https://horizon.wordpress.com/new?fresh&flags=gutenboarding/site-editor))
2. Add Video block and upload video
3. Video doesn't show up
4. Look at the block list view, see the video there

https://user-images.githubusercontent.com/87168/118613214-36298e00-b7c7-11eb-8db6-76462ef7313d.mov

Site: simisontestingfse805282478
Theme: Blank Canvas Blocks

Could be affected by editor content being iframed in Gutenberg these days?

**Comment by ianstewart** [comment]
Haven't tested yet but would be worth testing to see if we have the same issues in the blank template editor as well.

**Comment by roundhill** [comment]
The video is there but I spy an iframe with "0" height...

<img width="228" alt="Screen Shot 2021-05-18 at 10 16 00 AM" src="https://user-images.githubusercontent.com/789137/118687484-48ed9400-b7c2-11eb-86b7-fa92fbc5bfcb.png">

Not sure what's setting that but it appears to be the culprit.

**Comment by roundhill** [comment]
The height is set properly in the post editor:

<img width="239" alt="Screen Shot 2021-05-18 at 10 24 02 AM" src="https://user-images.githubusercontent.com/789137/118688350-39bb1600-b7c3-11eb-856d-f0ff87cd41d4.png">

**Comment by simison** [comment]
There's been a number of styling/height fixes for other blocks for FSE, could be similar? (I'm not familiar with details there)

https://github.com/Automattic/jetpack/pulls?q=is%3Apr+is%3Aclosed+fse

**Comment by roundhill** [comment]
Ok some more info, I think it is because the CSS for `.wp-embed-responsive .wp-has-aspect-ratio iframe` isn't present in the site editor, it's present in the post editor:

<img width="1018" alt="Screen Shot 2021-05-18 at 11 05 17 AM" src="https://user-images.githubusercontent.com/789137/118694471-55291f80-b7c9-11eb-952e-173a58ae3f84.png">

If that `height: 100%` is added the js that listens for the resize event kicks in and the video appears. If we can add that CSS or ensure that the same CSS from the post editor is copied over we should be good. Hopefully someone more familiar with the site editor will know what to do?

**Comment by roundhill** [comment]
Even after manually adding that fix though, I can't seem to click on the video block to select it... could be another bug.

**Comment by jeherve** [comment]
fwiw, the Video block isn't fully compatible with WP 5.8, because of this issue:
https://github.com/Automattic/jetpack/issues/18864

**Comment by roundhill** [comment]
This will be fixed once https://github.com/WordPress/gutenberg/pull/32057 is merged.

**Comment by roundhill** [comment]
It's merged! Closing.
