### ISSUE TITLE
Testimonials: Two Testimonials tabs when Stay theme is active

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#5296]
The Stay theme adds Rooms and Testimonials to the dashboard by default.  If Testimonials are not enabled, any Testimonials added will not show up.  If Testimonials are enabled, another Testimonials tab will show up in the dashboard.

#### Steps to reproduce
1. Starting at URL: wordpress.com/design
2. Activate the Stay theme.
3. Go back to the site dashboard, where Rooms and Testimonials now appear.
4. Activate Testimonials by going to the WP Admin dashboard, then Settings > Writing.
5. Go back to the WordPress.com dashboard, where two Testimonials tabs now appear.

<img width="268" alt="testimonials stay" src="https://cloud.githubusercontent.com/assets/11635760/15124851/d0f25b3c-15de-11e6-9d38-eb496b2239b2.png">

<img width="269" alt="testimonials twice" src="https://cloud.githubusercontent.com/assets/11635760/15124765/5ecbab4e-15de-11e6-8c97-a0a640e23896.png">

**Comment by lancewillett** [comment]
Thanks for the report.

Also: this could be changing soon due to experimental CPT behavior that's in development: see https://github.com/Automattic/wp-calypso/labels/Custom%20Post%20Types%20%28CPT%29.

**Comment by ockham** [comment]
Yep, this must be due to Calypso's CPT handling. Changing issue labels accordingly.

**Comment by aduth** [comment]
I'm going to close this as working-as-intended, specifically because these are technically two separate post types, `hotels_testimonials` (as registered by the Stay theme) and `jetpack-testimonails` (as enabled under Settings > Writing).

FWIW, the wp-admin navigation is also affected by this oddity:

![image](https://cloud.githubusercontent.com/assets/1779930/15560799/1fc3db9c-22bd-11e6-9854-b2711536bc4c.png)

If encountered, we can suggest that the users disable testimonials from Settings > Writing and leverage the theme-registered testimonails, which may be better displayed on the front-end.
