### ISSUE TITLE
Themes: Prepare blog themes for Headstart-on-theme-switch.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52988]
When https://github.com/Automattic/wp-calypso/issues/52799 is fixed, we'll be able to expand Headstart on theme switch to another set of blog-focused themes.

**Comment by kwight** [comment]
@ianstewart will fill in the themes.

**Comment by ianstewart** [comment]
Let's take a look at adding the following …

- Independent Publisher 2
- Twenty Sixteen
- Ryu
- Twenty Fifteen

Open to starting with others but those are known popular, and aesthetically pleasing, designs. (But maybe capping at a number of 5–7 to start with.)

**Comment by ianstewart** [comment]
@sixhours I think you have a list where you've double-checked some of our blog themes for inclusion here? IP2, Dyad-2, and one other?

**Comment by michaeldcain** [comment]
> IP2, Dyad-2, and one other?

I believe it was Hemingway Rewritten

**Comment by michaeldcain** [comment]
Diffs to add tags:

- Ryu: D62491-code
- Twenty Fifteen: D62492-code
- Twenty Sixteen: D62493-code

Independent Publisher and Hemingway Rewritten have already been tagged.

**Comment by ianstewart** [comment]
@michaeldcain I gave you an LGTM on those phab diffs.

**Comment by fushar** [comment]
This is not necessary anymore as we will reset the "Your homepage displays" setting to Default regardless of the presence of the `blog-homepage` tag. This behavior now correctly covers all newer themes, regardless of whether or not they are "blog" themes, because the homepage is now built in templates. See:

- #79167

I'm closing this issue 😄 cc: @Automattic/lego
