### ISSUE TITLE
Plans SEO: Move Related Posts Settings to Writing Tab

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5311]
To match up with the mobile apps and to make more contextual sense, let's move the 'Related Posts' settings out of the 'General' tab and into 'Reading'.

<img width="740" alt="screen shot 2016-05-09 at 5 06 48 pm" src="https://cloud.githubusercontent.com/assets/789137/15131849/72dc434e-1608-11e6-924f-66963a92ef04.png">

**Comment by rralian** [comment]
@roundhill part of the reason we did not put related posts into a reading section is because related posts is not a universally-supported option. There are some conditions we check before we display this setting. So if that's the _only_ setting we put into a `Reading` settings section, then we either need to check those conditions before we even paint the settings navigation bar (to determine whether or not to show a `Reading` tab), or we would show an empty page to people (or possibly a disabled setting).

**Comment by rralian** [comment]
Actually, did you mean you wanted to move it to `Writing` or `Reading`? Because the `Related Posts` settings are currently in the `Writing` settings area in the app (at least the iOS app). Though I would have understood a request to move it to `Reading`, since that's where it lives in `wp-admin` (and frankly, that would make more contextual sense than `Writing`).

**Comment by roundhill** [comment]
Thanks for the context Bob! @drw158 what do you think of moving it to `Reading`?

**Comment by drw158** [comment]
The idea was to match the apps, so Writing. I dont want to create another tab unless there is some bigger need or another plan to do so.

**Comment by mtias** [comment]
I think there are a few items we were considering adding to "Reading", including nudges like no-ads and a couple missing features that have been requested. I think it could make sense to bring "Reading" back.

**Comment by drw158** [comment]
We could:

- Leave Related Posts where it is.
- Put it in Writing, like in the apps.
- Create a new Reading tab and add another settings in there.

I prefer number 2, unless we feel confident about dedicating time to adding a Reading tab in the short term.

**Comment by rralian** [comment]
My vote is #1. The apps might have put that in Writing, but it makes little contextual sense there (to me at least), since it doesn't have to do with writing. I also think it would be ideal to focus on the new SEO stuff, so keep the other changes to a minimum.

**Comment by mtias** [comment]
Agreed. I say let's make an issue to bring back "Reading" and separate the task from the SEO stuff.
