### ISSUE TITLE
Theme Showcase: Errors occur when activating a theme from directly accessing the showcase URL.

### ISSUE THREAD

**Issue by MaksimUrasov** [Automattic/wp-calypso#53110]
Hi there, 

(Amended the issue body for clarity)

Recently the behavior of "All my sites" menu in Calypso multisite ( example here https://snipboard.io/whcAf7.jpg ) has changed-  Pressing Themes requires to choose a site first. 
To check that: in My Sites press Statistics > Swith Site >  All My Sites. That "All My Sites" menu can be entered not only from Statistics, but also from Domains, Posts, Pages, Plugins menus, but not Themes (I have to choose a site first to continue). 

That is not a big issue itself, but there is one error that is related to that changed behavior:

### Steps to reproduce the error

1. Go to https://wordpress.com/blog/category/themes/
2. Click on the first theme there – “New Theme: Twenty Twenty One”, it opens https://wordpress.com/blog/2021/01/14/twenty-twenty-one/
3. Near the bottom of the post, click on “Learn more about TwentyTwentyOne”, it opens the theme’s landing page: https://wordpress.com/theme/twentytwentyone
4. Click on the button near the top, “Activate this design FREE”
5. I’m presented a pop-over asking me, “How would you like to use Twenty Twenty-One on your site?” – example: https://d.pr/i/pKfQwi
6. Click on “Activate Twenty Twenty-One” button to activate the theme.
**7. Immediately get an error message in the top-right that says, “Unable to activate theme. Contact support.” – example: https://d.pr/i/bQ8MNh**

### Solution
**Possible solution: after step 4 to show the site selection window like this https://snipboard.io/WlU4tc.jpg**

On WordPress.com desktop app same issue is already solved:  You can go to My Sites > Switch Site > All my sites > Themes> Twenty Twenty One > Activate this design FREE > **a popup appears to choose a site** > Activate > Activate Twenty Twenty-One >Edit homepage. 

Also, "Themes" menu item can be removed from "All My Sites" menu (https://snipboard.io/whcAf7.jpg), because it does not make any sense to show a menu item that does not work as expected: does not show Themes available for all websites.

#### Level of impact 
Potentially can block paid theme purchases for multisite users.

#### DETAILS
That behavior started 21/05/21, a day before it worked fine.
This is similar to [#52789](https://github.com/Automattic/wp-calypso/issues/52789).

**Comment by michaeldcain** [comment]
@ianstewart @kwight: I believe your pod made the change here.

**Comment by kwight** [comment]
This isn't particular to the flow given by the original poster, but will happen when activating a theme from any directly-accessed URL in the showcase, eg. https://wordpress.com/theme/twentytwentyone. Theme switch fails because there's no given site to which to apply it – normally found as a slug at the end of a theme showcase URL when coming in from `/themes` for logged-in users.

This will also result in a "sad browser" for any theme switch preview at desktop widths, as the root domain for the iframe URL is `null`.

<img width="948" alt="Screen Shot 2021-06-28 at 10 55 43 AM" src="https://user-images.githubusercontent.com/349751/123683337-f1026e00-d800-11eb-8416-63db914d43d7.png">
<img width="449" alt="Screen Shot 2021-06-28 at 10 56 39 AM" src="https://user-images.githubusercontent.com/349751/123683362-f790e580-d800-11eb-9429-910c783566dd.png">


The fix is likely adding the same routing treatment for `/themes` to `/theme/*`. @mreishus could you look into this whenever you get a chance?
