### ISSUE TITLE
My Home: Investigate WooCommerce site setup checklist

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#53202]
From [Atomic site checklist original issue](https://github.com/Automattic/wp-calypso/issues/50523#issuecomment-836595977)

> There seems to be special logic to serve WooComerce sites a different checklist, we'll have to check that this checklist is working too.

This task is simply verifying if the Woo Commerce checklist works as expected.

If the checklist is not working, then let's make a new ticket with the details of what needs to be done.

**Comment by roo2** [comment]
hmm it seems that the checklist is just not available for woocommerce users becasue they have a very different woocommerce store setup process. Instead of a checklist, they see a "finish store setup" CTA
<img width="1062" alt="Screen Shot 2021-06-15 at 1 18 13 PM" src="https://user-images.githubusercontent.com/22446385/121979466-5bb5b180-cdde-11eb-9596-478576074320.png">

If the user completes the first part of the woocommerce onboarding, and then exits out of the flow, they will no longer be prompted to return and finish their onboarding. Note that the site is still not launched:

<img width="1595" alt="Screen Shot 2021-06-15 at 1 46 01 PM" src="https://user-images.githubusercontent.com/22446385/121980701-899bf580-cde0-11eb-9368-0d469e74f718.png">

So this could be improved with a CTA to finish their store setup and launch their site

**Comment by roo2** [comment]
I think that a solution to this would be to tweak the conditions for the "Finish store setup" CTA so that it stays around until the entire setup is finished.

**Comment by roo2** [comment]
closing in favor of https://github.com/Automattic/wp-calypso/issues/53686
