### ISSUE TITLE
My Home (pre-launch): visual refresh & style update

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#53212]
### Overview
This is part of [My Home Pod short-term design improvements](pd2qGl-2P-p2#short-term-goals)
Styling updates to My Home **(pre-launch view)** to create a more light, airy and modern UI.

![image](https://user-images.githubusercontent.com/5665959/119781985-fc672e80-bf0e-11eb-9cd4-338e00393928.png)

### User facing acceptance criteria
Given that the user has gone through site onboarding
When they land in My Home and have not launched their site
Then they see My Home with updated styling per [Figma designs](https://href.li/?https://www.figma.com/file/fLQcNzdadWzo87n89Imecj/?node-id=1763%3A0)
And they will see the proper update on desktop, tablet, and mobile viewports

### Figma Designs
https://href.li/?https://www.figma.com/file/fLQcNzdadWzo87n89Imecj/?node-id=1763%3A0
including  for desktop, tablet, and mobile viewports

### Related links
[My Home Project thread]( pd2qGl-17-p2)
[My Home: Short-term design improvements](pd2qGl-4i-p2)

### Dev Notes

**Comment by roo2** [comment]
Changes I can see: (other changes were made already in https://github.com/Automattic/wp-calypso/pull/53619)

#### Checklist:
~~"Update your site"~~ "Launch your site" moved to the last item in the checklist
"Learn how to use the editor" added
"Confirm your email address" removed

#### Style
Make page background white
More border radius on cards
Remove chevrons from quick links 
Remove borders from quick links

#### Other
Two _Learn Grow_ content items shown instead of one
"Make updates on the go" App subtitle removed

#### Not doing
"Visit site" button removed (discussed here pd2qGl-4i-p2#comment-140 and we actually did this and reverted https://github.com/Automattic/wp-calypso/pull/52830  metrics showed that people are still using it)

**Comment by roo2** [comment]
I'll work on doing the style changes 
I can also make two _Learn Grow_ content items appear
I think we can take out the "Make updates on the go" after reading pd2qGl-4i-p2#comment-154 even though it wasn't 100% resolved.

I think we should discuss checklist changes more and make another card for them

**Comment by autumnfjeld** [comment]
> "Update your site" moved to the last item in the checklist

Did you mean "Update your Home page"?  (Or maybe you're testing on a FSE site?).  Why is that last item in the Site checklist list? I don't see that in Jeff's designs...

**Comment by roo2** [comment]
Sorry I meant "Launch your site", it's moved to be the last item in the checklist, after "Get the Wordpress app"

**Comment by autumnfjeld** [comment]
OK, that makes a lot more sense: "Launch your site" at the end of the checklist. 👍

**Comment by roo2** [comment]
I pulled the changes to the checklist into https://github.com/Automattic/wp-calypso/issues/53976
And have a PR up to implement the design changes https://github.com/Automattic/wp-calypso/pull/53972
