### ISSUE TITLE
cloud.jetpack.com prompts to install as WordPress PWA on mobile

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#53313]
Any site with a manifest.json can provide icons and naming for when a user chooses to install it as a Progressive Web App. cloud.jetpack.com uses the Calypso manifest.json unmodified which results in confusing behaviour.

### Steps to reproduce the behavior

1. Go to cloud.jetpack.com on Android+Chrome
2. Browse around until you get the install prompt for "WordPress.com"
3. Click to install

#### What I expected to happen

No prompt, or prompt to install Jetpack Cloud with appropriate icon

#### What actually happened

Installed PWA as an icon named "WordPress" with WP logo
Clicking PWA opened as a deep link to the backups page on a particular site (rather than any kind of dashboard)

### Context

This is all because of how Calypso's manifest.json file is set up. We need to make it not run on cloud.jetpack.com for now.

#### Browser / OS version

Android 11 / Chrome 90

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screenshot_20210525-164809](https://user-images.githubusercontent.com/51896/120367456-bd95f780-c2c5-11eb-8731-b0776680c394.png)

**Comment by cbauerman** [comment]
We had[ previously added Jetpack Cloud specific manifest values](https://github.com/Automattic/wp-calypso/pull/42509). However, due to a routing overlap ( pMz3w-ddz-p2 ) the WordPress.com/Blue Calypso app was the only app handling `calypso/manifest.json`. In other words, it has never worked 🤦

Now that I have requested help with the routing, the Jetpack Cloud PWA has the following:
* Correct title `Jetpack.com`
* Correct Icons
* Correct Theme color

The one issue that was not addressed was the routing to `/backups` on the PWA open. Jetpack Cloud deliberately does not have a "dashboard" like WordPress.com, so the solution is to route to Backups or Scan ( depending on which products are active ) on the primary site or first Jetpack site if the primary site is not.

**Comment by gravityrail** [comment]
Gotcha, thanks @cbauerman
