### ISSUE TITLE
Add graceful failures for remote login

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#53536]
There are a few cases when remote login could fail:

* The back URL points to a disallowed host
* Token expired

... and so on.

Currently, we exit the code and the user sees a blank white screen. It could be useful to show some helpful messages here - like "Contact support", or redirect them to a fallback URL.

**Comment by lsl** [comment]
@aneeshd16 I have a feeling this is what people are somehow hitting in https://github.com/Automattic/wp-calypso/issues/53100#issuecomment-876132001

How they hit it I'm not sure. In the past when I hit RLT white screens it was usually due to sandboxing something incorrectly. I think I also hit this with a missed cache bust (rWP224225) once.

It would also be good to add logging to this error case since we do know where this occurs.

**Comment by lsl** [comment]
D63848-code is *not* likely to be merged but I suspect HTTP sites fail with a whitescreen on RLT. 

Possibly worth confirming / adding a check for this here.

**Comment by niranjan-uma-shankar** [comment]
> but I suspect HTTP sites fail with a whitescreen on RLT.

That's right, mentioned it here too - D63668?id=252339#1306675-code

**Comment by aneeshd16** [comment]
I have been trying to work out scenarios where the white screen might be shown in "natural" flows (no manual URL tampering is involved)
1. The domain is no longer set as primary. This can happen if you open a site on a custom domain, in a new tab change the primary redirect, and then click on the Log In CTA in the first tab. For this situation, we can detect this early and redirect to `https://<primary redirect>?logmein=1`
2. Token verification fails if the token is too old. This can happen due to network failures. For this, we can retry the login attempt by redirecting to 

I could not find any other use cases for which remote login could fail. What if we add stats to these failures, similar to this: 29bc0-pb

**Comment by niranjan-uma-shankar** [comment]
> What if we add stats to these failures, similar to this: 29bc0-pb

Adding Stats seems a good idea. @lsl is this the logging you had in mind?

**Comment by lsl** [comment]
LGTM

**Comment by lsl** [comment]
I've been concerned about ?logmein=direct from a logged out state but checking today it is handled gracefully maybe it always was?

I think for the other cases mentioned above, adding stats with D64547-code diff should be enough to gauge whether this is a real problem.

I'm also pretty convinced this code isn't the problem for the WSOD's we're seeing in the editor either so we won't be gaining much by diving too deeply into this (even if its probably worth it at some point).

@aneeshd16 you can probably close this out after merging your statsd additions in D64547-code

**Comment by aneeshd16** [comment]
Closed via D64547-code.
