### ISSUE TITLE
Themes: Generate dynamic preview of both options in theme switch modal.

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#53674]
This covers the back-end work necessary for https://github.com/Automattic/wp-calypso/issues/52792.

We need to be able to embed dynamic previews of both options used in the theme switch modal: keeping the user's existing homepage content with the new theme, or switching to the theme's default homepage content.

@simison notes in [this comment](https://github.com/Automattic/wp-calypso/issues/52792#issuecomment-858433302) that Ganon and/or Luna team should have some existing API systems that we can plug into for this purpose. 

Ideally, we will end up with an endpoint that can be plugged into front-end functionality being developed in https://github.com/Automattic/wp-calypso/issues/53675.

**Comment by mreishus** [comment]
* Currently, the API behind URLs [/v1/template/demo/barnsbury/barnsbury](https://public-api.wordpress.com/rest/v1/template/demo/barnsbury/barnsbury?font_headings=Open%20Sans&font_base=Chivo&site_title=Barnsbury&viewport_height=700&language=en&use_screenshot_overrides=true) doesn't look that promising. It has some restrictions about what themes can be used that I go into detail [in this comment](https://github.com/Automattic/wp-calypso/issues/52792#issuecomment-861024571).
* MShots takes a screenshot of a url. If that URL has been requested previously, a cached version can be returned instead.
* I'm worried about any MShots based solution for this:
  * Where MShots is used on `/new/designs`, there are a fixed number of sites it might screenshot: One for each theme or pattern. This is well below 1,000 and probably below 100.  So after all of the themes are screenshotted, the rest of the loads will be from cache.
  * For this issue, we would need to take a screenshot of (That user's homepage * The theme they selected). Since most everyone has a different homepage, and a user would select different themes, our cached hit rate would be very low. It would be taking and scoring screenshots all the time, and the tracks view `calypso_theme_autoloading_homepage_modal_view` shows that we display this modal 6,000-9,000 times a day.
* Probably the most promising mechanism is whatever mechanism the customizer live preview uses.

**Comment by mreishus** [comment]
Some of the homepages that we will need to render in this dialog:
* Are on private sites
* Are on jetpack or atomic sites

Because of this, I believe any mshot or photon proxy based solution cannot work (because we would need to be able to access content on a private+atomic site, and mshots runs in a public, unauthenticated context to my understanding).

**Comment by mreishus** [comment]
## List of Approaches

## Approach 1: Embed the customizer in an `<iframe>`
* Proof of concept: https://github.com/Automattic/wp-calypso/pull/53719
* Pros
  * The customizer already knows how to display the site using a different theme.
  * It's battle tested and already in production.
  * It works fine across atomic, private, jetpack sites.
  * Since the code generating the view of that site's homepage lives on that site, it has access to all of that site's plugins and settings, meaning it will be accurate.
* Cons
  * Editing icons appear in the profile and can be clicked on
  * `<iframe>`s are slow
  * Will not be able to convert to an autoscrolling image

## Approach 2: Modify the API used to generate screenshots on `/new/design`: [/v1/template/demo/barnsbury/barnsbury](https://public-api.wordpress.com/rest/v1/template/demo/barnsbury/barnsbury?font_headings=Open%20Sans&font_base=Chivo&site_title=Barnsbury&viewport_height=700&language=en&use_screenshot_overrides=true)
* Proof of Concept:
  * Backend: D62921-code
  * Frontend: #53759
* Pros
  * Without mshots, the results of the API call can be embedded inside a `<div>`.
  * With mshots, the results of the API call can be embedded in an `<img>`.
* Cons
  * This code only knows how to render homepages belonging to specific sites created with block patterns. They must be starter sites that belong to a hardcoded list or that have a special tag on the theme gallery. It cannot render any homepage given the site_id.
  * This code assumes that the homepage is comprised of patterns. For example, it uses `\A8C\Lib\Patterns\PatternStores::get_store()->get_homepage()` to find a site's homepage. It's not clear that this would work on arbitrary user sites that might not have pattern based homepages.
  * All of the starter sites used have these attributes: public, simple. A user's site does not, it could be private, atomic or jetpack. Can the methods in here be adapted for these types of sites? For example, `\A8C\Lib\Patterns\PatternStores::get_store()->get_homepage()` uses `temporary_switch_to_blog()` and then `\WP_Query()->query()` to get info. Does that work on jetpack and atomic sites when running on the public-api?
  * Using Mshots would create a resource burden. When the # of possible screenshots is = (number of themes), it's quite low and many requests to the service can be served by cached responses. When the # of possible screenshots is = (number of users's custom homepages * number of themes), most requests to the service cannot be served by cached responses, since most users have different homepage content. Additionally, the dialog is shown up to 9,000 times per day.
  * Mshots most likely cannot access private atomic sites (and possibly private simple sites).
  * How does the public-api get the homepage for any specific site?
    * Remote "curl" Requests: Would there be authentication issues for private simple and private atomic sites?
    * Maybe something with jetpack bridge?
    * If the backend is rendering the homepage by some method other than making a web request to the frontend, are there any issues with custom plugins on jetpack and atomic sites not rendering properly?

## Approach 3: Add a query parameter that allows a site to temporarily display in another theme, then embed in an iframe
* Pros
  * Would be able to get the functionality of the customizer previewing themes without invoking the rest of it
* Cons
  * Requires an `<iframe>`, which is slow
  * I feel like I could create this in an mu-plugin for simple, but I'm not sure about handling atomic and jetpack sites. I guess it would have to go into Editing Toolkit?
  * Private, atomic, jetpack sites would be fine, since the user is viewing the site in an iframe, not the public-api backend making requests to it

**Comment by mreishus** [comment]
Tried some more stuff out and I'm feeling a little more positive about approach 2. If I bypass all of the pattern stores stuff, then I am able to load homepage content from other sites and apply new themes to it, even private atomic sites, or jetpack sites.
So my questions re: approach 2 are:
* Can we load the desired sites?
  * Seems to work, even for private atomic sites, or jetpack sites.  
* Can we load the desired themes and apply them?
  * I believe there may be some restrictions here about which themes can and can't be applied. Need to keep investigating.
* How to organize code: Where should the endpoint be, and what should it be called, etc. First instinct is to extend or tweak the `WPCOM_JSON_API_Template_Demo_Endpoint` however, none of the patterns stuff is needed and it's actually getting in the way.

**Comment by simison** [comment]
cc @ramonjd @andrewserong who are kinda experts of these APIs, you might have some thoughts/feedback/ideas to share. :-)

**Comment by simison** [comment]
> Add a query parameter that allows a site to temporarily display in another theme, then embed in an iframe

BTW I have something like this implemented in https://github.com/simison/back-to-the-theme :-)

It's generally useful to be able to render in context of the actual site, just with a different theme, so that all the plugins and such get included.

**Comment by mreishus** [comment]
RE: Showing the user's current homepage with a theme chosen at run-time.
I'm seeing this breaks down into two levels. A solution should pick one approach for each level and combine them.
* Where the information is sourced
* How the information is displayed

Current options:
* **Where the information is sourced**
  * A variation of the backend endpoint used to generate previews  on `/new/design`
    * Change to allow loading homepage content from any arbitrary site
      * Will need to verify the requesting user and limit access, to prevent information leakage from private sites
        * And possibly also "coming soon" sites
    * Rough Sketch: D62921-code 
      * (+ frontend iframe display #53759)
  * Use the currently available customizer to preview a theme
    * Example: `https://wordpress.com/customize/<sitename>?theme=pub/twentytwentyone`
    * Rough sketch with iframe: https://github.com/Automattic/wp-calypso/pull/53719
  * Use the front end with "theme butler"
    * Example: `https://<sitename>/?theme=pub%2Ftwentytwentyone`
    * Theme butler is currently not available to everyone. p5cPuC-1f7-p2
  * Other options?
* **How the information is displayed**
  * Through the MShots service and `<MShotsImage>` react component
    * Concerned about:
      * Authorization; how can we securely access information on private sites while not opening it to the public?
      * Caching Misses leading to high resource usage
   * Through an IFrame
     * Iframe with src set to the customizer or the public api backend (sourcing options)
     * Concerned about authorization; loading public-api through an iframe src causes `get_current_user_id();` to return 0
     * Should investigate `https://wordpress.com/view/<sitename>` to see how it works, looks mature
  * Other options?

**Comment by ramonjd** [comment]
> Approach 2: Modify the API used to generate screenshots on /new/design: /v1/template/demo/barnsbury/barnsbury

It seems like you've gone pretty deep already on this, and you've highlighted more cons to adapting the demo endpoint than pros.

The demo endpoint is fairly cobbled together. Its was conceived for one purpose: to demo WPCOM designs on onboarding with varying text content (i18n, vertical content).

I like the idea of extending `WPCOM_JSON_API_Template_Demo_Endpoint`. Do you see any potential to create a base class that we could extend with the patterns stuff, which you mentioned were causing you problems?

By the way, @deBhal is pretty familiar with mShots and might be able to better confirm the limitations of the tool/address your concerns above. 

> I feel like I could create this in an mu-plugin for simple, but I'm not sure about handling atomic and jetpack sites. I guess it would have to go into Editing Toolkit?

The Editing Toolkit seems like a good fit, though it can be deactivated in Atomic sites.

A combination of `mu-plugin` on WPCOM and a duplicate in `wpcomsh` for Atomic might also do the trick.

**Comment by andrewserong** [comment]
Nice work exploring the options here! Just echoing Ramon's comments that the `template/demo` endpoint was fairly cobbled together. It has quite a different use case where the markup of the page is being manipulated directly to insert pattern content, update post title, augment the rendering of particular blocks, etc, and the endpoint is unauthenticated. For these reasons, I think it's important that we don't allow arbitrary post content from users' sites for that particular endpoint; the way it's currently written is with the assumption that we're dealing with trusted content. That said, I also like the idea if there are things that are worth grabbing from it, in creating a shared parent class for a separate endpoint if that looks like the way you want to deal with it?

For displaying a dynamic preview of a user's site in another theme, I imagine if it's delivered via an API endpoint, that it'd need to be authenticated (as a user I don't want other people to be able to preview my site in another theme), and as mentioned, we'd need to be able to support private sites. It sounds like that alone might rule out mShots as an option for rendering screenshots (I don't think it supports query params for a nonce-based approach or passing through authentication)?

> Approach 3: Add a query parameter that allows a site to temporarily display in another theme, then embed in an iframe

This one sounds like the most viable option to me! There were also challenges in delivering HTML directly via the public-api endpoint (I think it had to be a v1 API endpoint because the v2 / core REST API didn't really supported returning HTML?), so requesting the site itself might wind up being more straightforward to implement.

All that said, it sounds like you've done a lot of work looking into this already, and since it's been a little while since I've worked on the demo endpoint, you probably have a better idea of some of these trade-offs at this stage 🙂

Thanks for laying out your thoughts / ideas so clearly!

**Comment by mreishus** [comment]
* Information Source Layer
  * **`template/demo` endpoint**
  I have made a copy of this, and named it `theme/preview` endpoint in D62921-code. It mostly reuses the already existing `$template_helpers->get_demo_content()` to get the theme homepage and `$template_helpers->customize_page()` to mix the theme homepage and the user's homepage. There is some glue code around it, that could possibly use inheritance to reduce duplication with the other glue code, but they're different enough that I'm not sure if it's worth it. It currently doesn't do authentication, which could be added.
If `$template_helpers->customize_page()` is insecure when fed untrusted content from the third argument (`$template - The Gutenberg HTML of a page template.`), then I think this approach should be abandoned (unless there's an easy fix like wrapping the argument in one function).
I also don't know how to request the backend with authentication and load its response into an iframe. If I have the iframe src set directly to public-api, then the backend doesn't know who I am.  If I use wpcom.req in calypso to make the request, then I can't seem to access the HTML data that's sent in the response (it expects json on the frontend).
  * **Approach 3: Add a query parameter that allows a site to temporarily display their site in another theme**
I discovered someone has already made this: "Theme Butler" p5cPuC-1f7-p2 . However, it's not enabled for everyone, you have to go through some hoops and special flags to use it. Regular users can't. I guess if we went this way, I'd need to open it up so users with certain capabilities are able to use theme butler on their own sites.

* Display Layer
  * MShots
  I believe MShots is not viable due to the issues with authentication and private sites.
  * IFrames
    * Concerns about scaling and making a clean display that works across desktop and mobile.

**Comment by simison** [comment]
> Caching Misses leading to high resource usage

Best confirm this with devops before ruling it out — I got impression that it likely isn't an issue when we were discussing rendering design previews with custom site names (and onboarding has way more traffic than theme switcher)

**Comment by simison** [comment]
Above said, biggest reason to use mShots has been performance. If you have just two screens, that might not be an issue even with mobile internet.

**Comment by mreishus** [comment]
Good news: It looks like there's already a built in version of theme butler, or theme preview, that does not have a UI and does not require any special A8C settings or flags. Simply add `?theme=pub%2Ftwentytwentyone&hide_banners=true` to the end of the frontend url of a blog that you have the capability of switching themes on. It worked for a non-a8c account in my testing.

**Comment by mreishus** [comment]
I will look to develop some prototypes based off this pr: https://github.com/Automattic/wp-calypso/pull/53796
Edit: Child PR here #53823

**Comment by andrewserong** [comment]
> Good news: It looks like there's already a built in version of theme butler, or theme preview, that does not have a UI and does not require and special A8C settings or flags

Nice, this sounds promising! 👍

**Comment by mreishus** [comment]
This was solved here: #53823 -> #53796 -> #53959
