### ISSUE TITLE
Settings > Privacy: ""Copy suggested policy text to clipboard" not working

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#53805]
### Steps to reproduce the behavior

1. Go to https://tamsinstestsite.wpcomstaging.com/wp-admin/options-privacy.php
2. Click on Policy Guide.
3. Scroll down to one of the sample policies (WordPress, WooCommerce, Akismet) and expand it.
4. Scroll to the bottom.
5. Click "Copy suggested policy text to clipboard."

#### What I expected to happen
The policy guide text copies to the clipboard, and can then be pasted to another document.

#### What actually happened
Nothing.

### Context
User reported this for https://vtwinspecialties.net/wp-admin/options-privacy.php?tab=policyguide, which I was unable to access, but I duplicated the error on my test site (linked above).

#### Browser / OS version
Windows 10 and macOS Big Sur 11.4

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
Atomic.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Multiple sites, no purchase block.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Mostly consistent. It worked once, with the green "Copied!" notice next to the button, but I couldn't reproduce the success.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://d.pr/i/RbUTBs

**Comment by synora** [comment]
Triaged. Can replicate. As a workaround for now, highlighting the text with your mouse, right-click the mouse to copy the text, then pasting it to a page works.

**Comment by mpkelly** [comment]
Hi @the-misha! I have tried to reproduce this issue just now without success. I was using macOS Monterey and tried Chrome and Firefox. Can you retest it and let me know if there is a problem? Given the timeframe, I think it might have been fixed already. 

Apart from the bug, I noticed a couple of other issues:

1. When there is a lot of content in the Calypso Sidebar, after you scroll down to **Settings** and choose **Privacy**, the content is also scrolled. Once you click **Privacy**, the content updates but keeps the same scroll position. As there isn't much content on the default privacy page, you end up on a mostly blank page and think that the privacy page hasn't loaded unless you scroll back up. I think this is confusing and should be changed so that when you navigate via the Sidebar, the content's scroll position is reset. Here's how it looks:

![image](https://user-images.githubusercontent.com/6851384/177150933-ae933515-de97-4316-aac2-715cdd1f989b.png)

2. When you click copy twice quickly, the subsequent copies include the text "Copied!" at the bottom.

**Comment by youbrokesomething** [comment]
I'm going to close this as not reproducible. Please reopen if there are any new user reports of this issue.
