### ISSUE TITLE
Billing: Price shows up with a dot when it's larger than one thousand(with some specific interface languages)

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#53840]
### Steps to reproduce the behavior

1. Make sure that your account's interface language is set to any of these: ES, PT BR, DE or IT
2. Go to https://wordpress.com/plans/EXAMPLE.COM and add any plan to your cart(make sure to pick a plan that its total price goes over one thousand)
3. Check the checkout page at https://wordpress.com/checkout/EXAMPLE.COM

#### What I expected to happen
The price shown on the checkout page should be something like "2,500" with a comma.

#### What actually happened
Instead, it shows up with a dot.

![Screen Shot on 2021-06-19 at 10:47:52](https://user-images.githubusercontent.com/32432463/122627721-485f5a80-d0ec-11eb-9b0d-1573faa97edf.png)

This is extremely confusing as it makes the price look cheaper than real. 

### Additional Info

I tested with ES, PT BR, DE and IT so far and could reproduce the issue. The issue didn't happen with EN and JA. 

I didn't test all languages. So there might be more languages with which the issue can be reproduced.

**Comment by DavidRothstein** [comment]
I think that's expected behavior -- different countries use the comma and period in different ways (https://en.wikipedia.org/wiki/Decimal_separator#Usage_worldwide).

It's possible other areas of Calypso display prices inconsistent with the way checkout is displaying it, but it looks to me like checkout is actually doing it correctly.

Based on the screenshot, I'm guessing the user who ran into this is in Mexico?  If so, they can go to https://wordpress.com/me/account and change their interface language from _Español_ to _Español de México_ and it will probably work the way they expect (see also pNPgK-5bR-p2).

**Comment by hacchism** [comment]
@DavidRothstein Forgive my ignorance. I didn't know that🤦‍♂️

Closing it as it indeed looks like expected behavior.
