### ISSUE TITLE
Editor: page templates stuck from previous theme

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#5387]
I was doing some theme testing and switching between themes, as a result I noticed the templates got stuck. Initially I thought there was something wrong with the theme I was testing, however it wasn't the case. On switching to another theme, the same issue. 

Here is the video of what happened:
https://cldup.com/vdKVeKaqPF.mp4

Note, those templates don't exist in the theme, so actually clicking meant it didn't change. This only vanished when I did a hard refresh. This was despite coming in and out, saving and previewing. I even went into different sections, to change the theme, then came back. Only on refreshing did this clear up.

I have tried this with a few different themes and it happens every time - I need to refresh to get it to stick. The test site I am using is using Incognito Chrome (potentially the issue maybe?) and also a new user to test theme UX with. The site has only had 2 blog posts made and is verified: tuxthemereview.wordpress.com

**Comment by lancewillett** [comment]
Thanks for the report, Tammie.

**Comment by jeremeylduvall** [comment]
I dug into this a bit, but it has ended up being trickier than expected. We do have a function in place to take care of this ([`this._fetchTemplatesIfThemeChanges`](https://github.com/Automattic/wp-calypso/blob/95356cf9072bef0d3960f90518b26557ad6c3efd/client/components/data/page-templates-data/index.jsx#L38)) that listens to `site` and fires on `change`. It does work, but it just takes awhile in my testing.

The main issue is that when the component mounts it doesn't recognize that the theme has changed. You can see this by throwing `console.log( this.activeTheme )` into [`componentWillMount`](https://github.com/Automattic/wp-calypso/blob/95356cf9072bef0d3960f90518b26557ad6c3efd/client/components/data/page-templates-data/index.jsx#L34). If you change the theme and then go immediately to add a new page, it will still show you the old theme presumably because it hasn't fetched the new theme just yet. When we run the comparison in `_fetchTemplatesIfThemeChanges`, it returns without fetching anything since the themes are still equal.

Here's a video of me opening the page editor, going back to change the theme, and reopening the page editor. In the demo, I'm starting on Hemingway Rewritten (does have page templates) and going to Scratchpad (doesn't have page templates).

https://cloudup.com/cnD25gRUGI6

The first `console.log` you see is from logging out `this.activeTheme` in `componentWillMount`. You'll notice that although I switched themes, it still thinks I'm in Hemingway Rewritten when I re-enter the editor. The second `console.log` is from `_fetchTemplatesIfThemeChanges`. That takes about 25 seconds to fire.

Two potential solutions:
1. Always fire `PageTemplatesActions.fetchPageTemplates( this.props.siteId )` when the component is mounting. As a result, we'll be firing this quite a few times when we don't need to (anytime the theme hasn't changed).
2. We store a value for `isInitialized` in the [`PageTemplatesStore`](https://github.com/Automattic/wp-calypso/blob/95356cf9072bef0d3960f90518b26557ad6c3efd/client/lib/page-templates/store.js#L24) to determine if we've already fetched the page templates for a specific site. Perhaps we could set that to `false` when a theme is activated. (I thought about storing the `themeSlug` in that store as well and then comparing to the active theme when the page loads, but that still has the same lag time so doesn't end up working.)

**Comment by nylen** [comment]
Discussed this a bit, and I can think of two potential solutions:

- Ensure that the current site and/or the sites store fire a `change` event when the current theme is changed.  This seems like it should be happening anyway and I'm a bit surprised that the site object isn't being updated.
- Connect this component to the Redux `currentThemes` state [here](https://github.com/Automattic/wp-calypso/tree/3ede1a2/client/state/themes/current-theme).

@aduth - what do you think?  would it be appropriate to connect this data component to the Redux state for the current theme, or can you think of a better approach?

**Comment by aduth** [comment]
Yeah, it's a bit more difficult now because themes is Redux-based, while the page templates store is still based in Flux. I think the ideal solution would be to fully port the page templates data to Redux, and connect the `post-editor/editor-page-templates` directly to Redux state. In implementing page templates, I think we should also reconsider how we're storing the templates. Currently, we're storing on the basis of site ID, which is obviously a concern when the theme for the site changes. We could blow away data for the site when a new theme is activated, but I wonder if instead we should simply track page templates by the theme slug. That way, there's more of a chance that switching between sites or themes will reuse existing data. There's a bit of a worry here about conflicts for themes with the same slug (especially for a Jetpack site), but that's probably more of an edge case.

Few other notes:
- @jeremeylduvall : I suspect the delay you're noting is the polling of sites data [[1]](https://github.com/Automattic/wp-calypso/blob/5db5b934a149731f10ea7bb7ad5956852cf9681f/client/lib/sites-list/index.js#L15) [[2]](https://github.com/Automattic/wp-calypso/blob/5db5b934a149731f10ea7bb7ad5956852cf9681f/client/lib/data-poller/poller.js#L3)
- @nylen : It might be more difficult than you'd think to fire `change` on the site when the theme is activated

I do think your second suggestion on connecting `<PostTemplatesData />` to `currentThemes` state would be a viable near-term solution. We could monitor changes to the the currently activated theme from `componentWillReceiveProps` and trigger `PageTemplatesActions.fetchPageTemplates`.

**Comment by jeremeylduvall** [comment]
I took a shot at the near-term solution in #5785 connecting to the currentThemes state. Have a few notes in that PR.
