### ISSUE TITLE
Publicize: LinkedIn posts are shared without the featured image

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#53978]
We have had several reports on LinkedIn posts sharing without the featured image - despite _LinkedIn Post Inspector_ is displaying each post correctly (with the featured image).

### Steps to reproduce the behavior

1. Make sure LinkedIn is connected to the site
2. Publish a new post with Featured image
3. Check the LinkedIn page if the image was publicized
4. Compare with the result in the _LinkedIn Post Inspector_: [](https://www.linkedin.com/post-inspector/)

#### What I expected to happen

Posts publicized to LinkedIn should include the image:

![Markup on 2021-06-24 at 10:25:25](https://user-images.githubusercontent.com/25105483/123229437-956d7300-d4d6-11eb-9c42-ac09036f4ace.png)

#### What actually happened

Posts publicized to LinkedIn were shared without the image:

![Markup on 2021-06-24 at 10:25:11](https://user-images.githubusercontent.com/25105483/123229486-a1593500-d4d6-11eb-87a9-c7cf158aaecd.png)

### Context

Reports we have so far:

* 4089495-zd-woothemes (Simple site)
* 4088037-zd-woothemes (Atomic)
* https://wordpress.org/support/topic/publicize-to-linkedin-not-sharing-feature-image/ (self-hosted)
* https://wordpress.org/support/topic/publicize-to-linkedin-not-sharing-featured-image/ (self-hosted)

#### Browser / OS version

N/A

#### Is this specific to the applied theme? Which one?

N/A

#### Does this happen on simple or atomic sites or both?

Both Simple and Atomic; self-hosted as well.

#### Is there any console output or error text?

-

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Issue doesn't block purchases; it affects more than one site.

**Comment by bobmatyas** [comment]
Another example on a self-hosted site:

https://wordpress.org/support/topic/plublicize-no-image-shared-on-linkedin/

**Comment by E-VANCE** [comment]
Using another service (automate.io) in order to auto-share to LinkedIn yielded the same, image-less result... Luckily I could get some debug-info regarding the connected fields and it seems that the relative thumbnail URL is the culprit here.

![CleanShot 2021-06-25 at 09 54 13](https://user-images.githubusercontent.com/4123541/123391291-24908e80-d59c-11eb-9efa-2f9a89f8fb8d.png)

So maybe investigate in this direction, seems promising.

**Comment by danmaze** [comment]
Another example: 4099732-zen

There appears to be a trend here as we're seeing more users experience this.

**Comment by SteffanCline** [comment]
I too am having this issue and have not heard of anyone being successful in nearly a week now. Any progress?

**Comment by sanjeev00733** [comment]
Another report in 4099941-zen

**Comment by ctdealba** [comment]
Another example: 4105885-zen

**Comment by davipontesblog** [comment]
Adding "Priority: Normal" to this one as it's definitely an issue to be resolved and seems widespread, but it's not stopping the posts from getting published.

**Comment by jeherve** [comment]
Also reported in 4115528-zen

**Comment by jeherve** [comment]
We haven't done any changes on our end in the past few months, so I wonder if this may be a change on LinkedIn's end, in the type of data they expect / accept when doing API calls to publish new posts.

@E-VANCE Could you tell us more about your setup for this tests, so we can try it on our end as well?

Thank you.

**Comment by jeherve** [comment]
Update. I reached out to the LinkedIn team about this in 4117016-zen.

Internal reference: p7fD6U-4Ad-p2

**Comment by E-VANCE** [comment]
@jeherve Feel free to use automate.io and set up a connection between WP (new post as trigger) and LinkedIn, the setup is rather trivial and should be easily reproducible.

**Comment by SteffanCline** [comment]
RE: "Adding 'Priority: Normal' to this one as it's definitely an issue to be resolved and seems widespread, but it's not stopping the posts from getting published." - The whole purpose of the plugin is text AND picture. This needs to remain a high priority until resolved.

**Comment by EranBoudjnah** [comment]
This is still ongoing. Not a single post of mine has been posted with a picture for quite some time. I can never recover the lost traffic. Without the picture posts are getting no traction.

**Comment by SteffanCline** [comment]
Can we get an update? It seems like surely in 20 days we'd have some kind of progress.

**Comment by jeherve** [comment]
I'm afraid we have no news yet. As mentioned above, the issue happens [with other services as well](https://github.com/Automattic/wp-calypso/issues/53978#issuecomment-868303633), so it would seem that the problem stems from updates to the LinkedIn API. We'll update this issue as soon as we receive an update from the LinkedIn team on the problem.

**Comment by EranBoudjnah** [comment]
Apologies for the naive question, but why is this stuck with LinkedIn? It seems like they're pulling metadata correctly from other sites without fail. Have the web logs been analyzed? Can other websites read the metadata? Can you share some technical data? I'm using wordpress.com. So not self-hosting.

**Comment by jeherve** [comment]
>  It seems like they're pulling metadata correctly from other sites without fail. 

Sharing a post manually does work indeed, regardless of where your site is hosted. Here is an example:

![image](https://user-images.githubusercontent.com/426388/125430738-d3aa8c82-c12a-47ec-904f-e70f0fba2846.png)

The problem seems to be related to automated posting, just like the one that happens when you use [our Publicize feature](https://wordpress.com/support/publicize/) to automatically publish your new posts to your LinkedIn profile. When you use that feature, WordPress.com relies on an API endpoint provided by LinkedIn. WordPress.com pushes data (a post URL, a title, a description, and an image URL if one can be found in the post) to that endpoint, and LinkedIn uses that data to build an update on your LinkedIn profile.

I hope this clarifies things a bit.

**Comment by ctdealba** [comment]
Another report 4139807-zen

**Comment by donalirl** [comment]
Encountered in #30718718-hc and shared this reply from LinkedIn support:

>If the URL is shared directly on Linkedin, the image will appear as expected. 
It wont if pushing to LinkedIn via Share API because the API is not properly passing the image. Per the above, you can specify the image, title, url, ... information in the API call to create the post.  It does not automatically pull from the OG tags.
This means that there is an issue with the Wordpress API and how it handling images. You would need to pass this information to Wordpress.

More details: p7fD6U-4Ad-p2#comment-16955

Follow-up: #4160795-zen

**Comment by Robertght** [comment]
Another case in 30250985-hc

**Comment by jaz-on** [comment]
I would like to add a few examples that go along with what Jeremy says:

- I published my first post with Jetpack Publicize today and the featured image doens't show up on LinkedIn: https://www.linkedin.com/posts/jasonrouet_je-vous-en-dis-un-peu-plus-sur-la-mise-%C3%A0-activity-6827818401939955712-pxVH
- Then I shared the same post manually and it works: https://www.linkedin.com/posts/jasonrouet_mise-%C3%A0-jour-du-blog-de-mi-2021-jasonnade-activity-6827849830652547072-M5SY

For comparison purposes, I shared this post on Twitter with Publicize and it works very well: https://twitter.com/JasonRouet/status/1422052704616992772

**Comment by Nic-Sevic** [comment]
I reached out to LinkedIn again since we didn't receive a response last time: 4227338-zen

**Comment by gaurav1984** [comment]
I have closed 4105885-zen. Please reply to the customer once the issue is resolved.

**Comment by bobmatyas** [comment]
Reached back out to LinkedIn on 4283661-zen

**Comment by benchilcote** [comment]
Adding another case 4298237-zen

**Comment by yansern** [comment]
**Investigation note:**

It is likely that the `thumbnails` property should be used as seen in https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api?tabs=http#sharemedia.

The relevant file to modify is `wp-content/admin-plugins/publicize/services/linkedin.php`.

**Comment by yansern** [comment]
~It also seems that the job that publicize post is running too quickly before featured_image is set on the post meta as well.~ Update: This is only the case when `publicize_force_synchronous` is turned on. When job runs async, the featured image is added to the post meta first, then only the job runs.

**Comment by yansern** [comment]
**The phab patch for the fix is ready for review!**
D67270-code

**Final investigation note:**

The **UGCPosts** API endpoint has a `thumbnails` property but that one did not work. The documentation says:

> UGC Post is a content API best suited for creating and retrieving posts for organic video posts and video ads. **For other media types, it is advised to use the Shares API.**

Therefore, the fix implemented was to move over to Shares API. https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/share-api?tabs=http

![image](https://user-images.githubusercontent.com/1287077/134431395-4247662b-88cc-4d44-89a0-b189bb93b02e.png)

**Comment by yansern** [comment]
Phab patch D67270-code deployed. This issue is now resolved.

**Comment by bobmatyas** [comment]
I updated Jetpack Forum users who created threads about this issue.

**Comment by bobmatyas** [comment]
@yansern We got a report of a possible regression on the forums:

https://wordpress.org/support/topic/publicize-to-linkedin-not-sharing-featured-image/?view=all#post-14920649

According to the user:

> it seems now that it has caused all LinkedIn posts to have VISIBILITY set to CONNECTIONS instead of PUBLIC.

I did not have a chance to independently verify this.

**Comment by yansern** [comment]
@bobmatyas Thanks for reporting this! I indeed, wasn't aware of the visibility aspect of posts when I migrated over to Shares API.

So here it is, another phab patch - D67701-code.

![2021-10-01_06-46-00](https://user-images.githubusercontent.com/1287077/135562397-fbb044c1-fa78-4a43-b77d-611df3495160.png)

**Comment by yansern** [comment]
Deployed!

**Comment by bobmatyas** [comment]
@yansern - We have another report on the forums the custom message for LinkedIn is not working and that instead the first ~395 characters of articles are being shown instead.

https://wordpress.org/support/topic/publicize-to-linkedin-not-sharing-custom-message/?view=all

**Comment by yansern** [comment]
> @yansern - We have another report on the forums the custom message for LinkedIn is not working and that instead the first ~395 characters of articles are being shown instead.

Noted! Will pick this up again.

**Comment by alshakero** [comment]
Continuing in https://github.com/Automattic/wp-calypso/issues/57144
