### ISSUE TITLE
Signup: inconsistent width for Domains step

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#54022]
### Steps to reproduce the behavior
Force an invalid state of the `/start/domains` step in the Signup flow.

#### What I expected to happen
In all states, width to be as in the default view (960px for the blue signup)

<img width="800" alt="Screenshot 2021-06-25 at 15 56 14" src="https://user-images.githubusercontent.com/14192054/123430197-908cea00-d5d0-11eb-9b68-035e549181ab.png">

#### What actually happened
When the step is displayed in an invalid state, [720px width is applied to the step wrapper](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/domains/style.scss#L6)

<img width="800" alt="Screenshot 2021-06-25 at 15 55 31" src="https://user-images.githubusercontent.com/14192054/123430167-866aeb80-d5d0-11eb-82e9-d90d6a2340fe.png">

### Context

Fixing this won't be straightforward since `domains__step-section-wrapper` class is used in multiple cases, not only for the [invalid state](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/domains/index.jsx#L731). Also, the reskin version should be taken into consideration.

**Comment by andrewserong** [comment]
I'm not sure if this issue is related, but in the reskinned version of the same step, I noticed that there's a breakpoint where the padding on the step wrapper doesn't appear to be present, so the heading and container goes right up against the left side of the screen (I didn't have time to look closely, apologise for the drive-by report if it's unrelated!):

![image](https://user-images.githubusercontent.com/14988353/123566280-a681f100-d802-11eb-9d0e-572b44634ab1.png)

**Comment by lsl** [comment]
Stale
