### ISSUE TITLE
Theme Showcase: Remove Layout and Style filter features, and hide the bar behind an Advanced toggle

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#54078]
We're going to reduce these to just Feature, Layout, and Subject, and hide them behind an Advanced toggle.

<img width="1368" alt="Screen Shot 2021-06-28 at 9 54 31 AM" src="https://user-images.githubusercontent.com/2124984/123648444-f35fca80-d7f6-11eb-885c-1270436cdb03.png">

Related to #53960

**Comment by mreishus** [comment]
If we keep these, they are essentially impossible to use with the auto-complete dropdown removed here (#54077). You need to search for `feature:<feature-name>`, but the feature name must be exact. Without the dropdown, there's no way to know what the feature names are. Clicking the "Feature" on the "Magic Welcome Bar" prefills your search with "feature:", but you still need to know what to type.
![2021-06-28_13-31](https://user-images.githubusercontent.com/937354/123686304-49436b00-d815-11eb-8e3d-4d3d31b45934.png)
^ With dropdown
![2021-06-28_13-31_1](https://user-images.githubusercontent.com/937354/123686313-4b0d2e80-d815-11eb-928e-d622d4c43fa8.png)
^ With dropdown removed

**Comment by kathrynwp** [comment]
I’ve compiled some feedback and recommendations from several HEs about this potential change:

- HEs still often use _some_ of these filters to find themes to fit users’ specific requests, particularly the **Feature** filter. Several mentioned being able to find a theme with a sidebar, since most of a the current Recommended Themes do not have a sidebar, and without the filter it would otherwise be difficult to find them. 
- One HE pointed out that the search would generally be for advanced users only – but even those folks are likely going to want a third-party theme.
- If we remove the filters, we should still have a way for HEs to access the Feature filter **at minimum.**
- Almost no one mentioned the **Layout** or **Column** filters as being particularly useful. With the block editor, they’re on their way to being obsolete, so we can probably safely remove those. Several HEs do use the **Style** filter, although even that one is questionable, since colour and other design options are available in many blocks, so the style of the site can now be controlled that way. 
- There are significant issues with the current **Subject** filter, since the thumbnails we present don’t always match the selected term. The Blog subject presents some thumbnails that don’t look at all like blogs, and the same goes for Wedding, to give just two examples.

### Top row of search results for `subject:blog`:

![Blog_WordPress_Themes_‹_Global_Styles_Demo_—_WordPress_com](https://user-images.githubusercontent.com/7662449/123803886-b0672b00-d8ba-11eb-8658-86304e9f24da.jpg)

### Top two rows of search results for `subject:wedding` – none of these themes is particular wedding-like:

![Wedding_WordPress_Themes_‹_Global_Styles_Demo_—_WordPress_com](https://user-images.githubusercontent.com/7662449/123804147-f8864d80-d8ba-11eb-99a7-57299ef9a8a0.jpg)

- One person pointed out that the language used in some of the Feature filters doesn’t match the language HEs use with customers, reducing their clarity and usefulness. For example, we never say “auto-loading homepage.” And “Block Editor Styles” is vague and implies that other themes _don’t_ work with the block editor. 

That said, **users do need some way of finding themes that meet their needs,** aside from scrolling past thumbnails whose components consist mostly of blocks that could be created in any newer theme.

Several HEs mentioned that the search box should be kept and ideally the search improved. For example, can we make sure themes with sidebars come up if you type in “sidebar.” There was also a suggestion to update the placeholder text to make it clear _how_ you can search. 

#### Before

![WordPress_Themes_‹_Global_Styles_Demo_—_WordPress_com](https://user-images.githubusercontent.com/7662449/123805474-199b6e00-d8bc-11eb-8076-1a32bf27e90d.jpg)

#### After

<img width="647" alt="theme-search-idea" src="https://user-images.githubusercontent.com/7662449/123805662-43ed2b80-d8bc-11eb-9fc7-54333e0e17e5.png">

### An Idea

What if we hid the feature filters under an "Advanced search" toggle, near the search bar? This would avoid having to come up with a separate way for HEs to access the filters. It would also give us time to see how the change affects users.

**Comment by sixhours** [comment]
> If we keep these, they are essentially impossible to use with the auto-complete dropdown removed here (#54077). You need to search for feature:<feature-name>, but the feature name must be exact. Without the dropdown, there's no way to know what the feature names are. Clicking the "Feature" on the "Magic Welcome Bar" prefills your search with "feature:", but you still need to know what to type.

Ahh, that's a good point. :-/ Could we only show the search dropdown piece when using the "advanced search" as Kathryn suggests below?

> What if we hid the feature filters under an "Advanced search" toggle, near the search bar? This would avoid having to come up with a separate way for HEs to access the filters. It would also give us time to see how the change affects users.

@ianstewart What do you think about this as an interim solution for this sprint? It sounds like total removal would be disruptive to HE workflows.

**Comment by mreishus** [comment]
>     * HEs still often use _some_ of these filters to find themes to fit users’ specific requests, particularly the **Feature** filter. Several mentioned being able to find a theme with a sidebar

Do you know how they search for sidebars? I wasn't able to find anything matching under the feature section (unless it's fixed menu?):
![2021-06-29_10-11](https://user-images.githubusercontent.com/937354/123823158-8c0f4c80-d8c2-11eb-804f-195fe32f6249.png)

**Comment by kathrynwp** [comment]
@mreishus Actually it's under Columns, so though no one mentioned Columns specifically, it's the sidebar options there that _are_ well used. (and sorry for my misleading comment about it above!)

![WordPress_Themes_‹_Global_Styles_Demo_—_WordPress_com](https://user-images.githubusercontent.com/7662449/123823639-60449480-d8cb-11eb-935e-349ddfb77759.jpg)

**Comment by sixhours** [comment]
#54141 covers the removal of Layout and Style feature filters

**Comment by sixhours** [comment]
These changes were shipped under a feature flag in #54218 and #54215 -- calling this done! 🥳 I'll open a separate ticket to track the front-end work.
