### ISSUE TITLE
Theme Showcase: Remove dropdown for search results

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#54077]
The current showcase has this dropdown when you search by specific terms:

<img width="1360" alt="Screen Shot 2021-06-28 at 9 48 12 AM" src="https://user-images.githubusercontent.com/2124984/123647984-906e3380-d7f6-11eb-993f-fe8d81010151.png">

Let's remove the dropdown and update the search results automatically.

Related to #53960

**Comment by mreishus** [comment]
I believe the results already update automatically; clicking on the dropdown or pressing enter changes your search input, but a search is still happening even when the dropdown is being displayed.

**Comment by mreishus** [comment]
* Removes Component Entirely: https://github.com/Automattic/wp-calypso/pull/54092
  * There seems to be some issues with this, the specific 'feature' search will essentially be impossible to use in this state.
* Alternative Approach: Make it appear less often: https://github.com/Automattic/wp-calypso/pull/54097
* Alternative Approach: Make the matches more strict: https://github.com/Automattic/wp-calypso/pull/54125

**Comment by kwight** [comment]
> Make it appear less often

Wonderful option.

**Comment by kathrynwp** [comment]
> update the search results automatically

I'd love to see how this would work in practice – let me know if there's a way I can test it! (Edit: I also commented on the PR itself)

**Comment by mreishus** [comment]
Wrote a comment about disadvantages of the "less often" Alternative Approach in that PR: [Link to comment](https://github.com/Automattic/wp-calypso/pull/54097#issuecomment-870701939) (tldr; makes it harder for users to find the features they do want like sidebars)

I started to wonder just why so many KeyedSuggestions are appearing and looked into a strange one to find the mechanism. 
![2021-06-29_10-50](https://user-images.githubusercontent.com/937354/123829446-160de400-d8c8-11eb-9640-415f55308812.png)
^ When you search for `twen`, "Multiple Menus: Supports two or more menus, not including social-links menus." appears as a match. Why is this?

It turns out the "twen" search is expanded to the regex `"twen|twen.*|twe.*n|tw.*en.*"`, which matches the description because it contains "tw" followed by "en" somewhere, namely: 

`twen` matches -> "Supports **tw**o or more m**en**us"

As a third approach, I'll quickly try taming the regex to make KeyedSuggestions return fewer matches to see how it feels.  Done here: https://github.com/Automattic/wp-calypso/pull/54125

**Comment by kwight** [comment]
> When you search for twen, "Multiple Menus: Supports two or more menus, not including social-links menus." appears as a match. Why is this?

My first thought is that `twen` matches the Twenty-something themes, which likely support many menus? For example, Twenty Twenty shows as supporting multiple menus ([source](https://theme.wordpress.com/wp-admin/post.php?post=36834&action=edit)):

<img width="325" alt="Screen Shot 2021-06-29 at 11 30 57 AM" src="https://user-images.githubusercontent.com/349751/123849529-c03c3a80-d8cd-11eb-96e4-97ba0795c3e6.png">

**Comment by mreishus** [comment]
Created: Theme Showcase: Make the keyed suggestions matches even more strict #54145

**Comment by sixhours** [comment]
Following up on this, we're *not* removing the search dropdown after all. Closing this one out.
