### ISSUE TITLE
My Home: Support Docs to link directly to Document instead of using inline display.

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#54150]
In My Home the Support search results currently use an inline display of the document which is quite plain.

<img width="1024" alt="screen-shot-2021-06-16-at-11 39 52-am" src="https://user-images.githubusercontent.com/1842363/123908961-ad079880-d9bb-11eb-9d8b-57ed21d455ae.png">

As per the discussion in pd2qGl-8f-p2 I'd propose that we change this behavior so links go directly to the support document.

**Comment by Aurorum** [comment]
> As per the discussion in pd2qGl-8f-p2e I'd propose that we change this behavior so links go directly to the support document.

Just out of curiosity, did this P2 conclude that this should no longer be the default behaviour everywhere throughout Calypso? 

For context, https://github.com/Automattic/wp-calypso/pull/40080#issuecomment-599105095 advocated that all support links should display a dialog rather than link to the page directly citing p4TIVU-94p-p2 titled "Inline Support Articles Everywhere" - it'd probably be good to know if that's changed just for future cases where a support document link is inserted! :)

**Comment by jordesign** [comment]
Hey @Aurorum - it turns out there's still some discussion to go - but it would only be in My Home we'd want to remove these inline docs.

**Comment by p-jackson** [comment]
I'll copy the relevant discussion onto GitHub so you can see @aurorum.

The content of p4TIVU-94p-p2, titled "Inline Support Articles Everywhere", is advertising the fact that "inline support articles can now be used everywhere". It's not really a directive to "please use inline support articles everywhere". I hadn't read this post or https://github.com/Automattic/wp-calypso/pull/40080#issuecomment-599105095 before, so you've actually provided me with some extra context, thank you for that!

> Just out of curiosity, did this P2 conclude that this should no longer be the default behaviour everywhere throughout Calypso?

We're only changing the behaviour of the support links that appear in the "Get help" card on My Home. 
<img width="629" alt="searchlinks" src="https://user-images.githubusercontent.com/1500769/124067249-31c2e700-da8e-11eb-988d-11590c2850e1.png">

If there are other help links that appear in My Home (e.g. the "add menu" site setup task has a help link) those will continue to open the help inline.

We like the idea of inline help! When the user is trying to achieve some goal, showing the help inline means we don't derail them from that goal. A good example is setting up podcasting:
![podcasting settings interface with inline help link highlighted](https://user-images.githubusercontent.com/1500769/124066836-79953e80-da8d-11eb-8a7c-77a5d6589a09.png)

Just because a user wants a little more explanation before clicking "Set up", that doesn't mean they want to be navigated away.

We feel the "Get help" search results on My Home are a different case. Here the goal _is_ to find and read the support material<sup>1</sup>, so opening the content in a full tab will be a better reading experience. The "Get help" card sort of serves the same purpose as the search box on https://wordpress.com/support/

---
<sup>1</sup> Of course their overarching goal will be more than just reading support material, but the immediate task at hand is to find support material

**Comment by Aurorum** [comment]
Thanks for sharing! I've opened a PR to make that change in #54202. :)

**Comment by p-jackson** [comment]
#54202 deployed which implements this change, thanks @Aurorum!
