### ISSUE TITLE
Jetpack Form Block - Date Picker - day suffix showing as "S" on simple sites

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#54200]
### Steps to reproduce the behavior

1. On a simple site add a form block to a page
2. Add a Date Picker field
3. View the published page and select a date

#### What I expected to happen
I expected the date to show as "16th" but is showed as "16S" instead. This only happens on Simple sites I tested which show the date in the format day month year. On atomic and self-hosted I see the date without a suffix in the format July 12, 2021.

### Context
#30417306-hc and follow-up: 4106376-zd-woothemes

#### Is this specific to the applied theme? Which one?
No, tested on multiple themes with same result

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
No blockers but seems to impact all siimple sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Markup on 2021-07-01 at 09:21:23](https://user-images.githubusercontent.com/22053773/124083055-b9d4cc80-da4d-11eb-9a17-b14c3a91ccd9.png)

**Comment by synora** [comment]
Triaged. I cannot replicate this by following the above steps but I've done some digging.

In Settings > General (https://siteurl.wordpress.com/wp-admin/options-general.php), there's a custom date format in place for the above report in particular.

![Annotation on 2021-07-02 at 17-11-47 (1)](https://user-images.githubusercontent.com/10015451/124329822-2806b580-db5a-11eb-8c3c-9b213c8bb350.png)
 

Just after the 'j' character is an 'S' character. 

I went back to my test site and created a custom date with the same format as the screenshot above. When the 'S' is removed and inserted, you can see in the date preview to the right that the 'S' character is supposed to create the date suffix but it's not. This is causing the actual 'S' character to appear on the date instead of the date suffix. 

It appears to be a long-standing core bug: 
https://core.trac.wordpress.org/ticket/39991
https://core.trac.wordpress.org/ticket/22225

I'm unable to find a workaround for this at the moment.

**Comment by zdenys** [comment]
There has been this much older bug https://github.com/Automattic/jetpack/issues/11251 still open. I think we should close this one in favor of the older one.

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/jetpack/issues/11251
