### ISSUE TITLE
Reader Search: Allow refining results by relevance or recency

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5428]
With the Reader Search results are we showing more recent or more relevant results first?
Can we provide switch between relevant/recent?

**Comment by gibrown** [comment]
Results are sorted by combining both search term relevancy and recency (and a number of other features) because recency is often a proxy for relevancy. I don't think we should add another option. If someone wants a complete stream they should look at a topic, though this is tied into how we redefine topics.

**Comment by gibrown** [comment]
This was shipped a while ago.
