### ISSUE TITLE
Reader: can't follow specific blogs

### ISSUE THREAD

**Issue by priethor** [Automattic/wp-calypso#54280]
If I try to subscribe to make.wordpress.blogs, either by clicking the follow button or by using their feed URL (which works fine in other RSS readers), I get an undisclosed error.

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/search
2. Search for "Make WordPress" blogs
3. Try to follow any "make.wordpress.org" blog.

It can also be reproduced by typing directly the blog feed, as in "make.wordpress.org/design/feed"

#### What I expected
To have those blogs added to my followed list.

#### What happened instead
A generic error message appears

#### Browser / OS version
MacOs 11.4 with Chrome 91 and Firefox 89.

#### Screenshot / Video
https://user-images.githubusercontent.com/27339341/124453025-3e458900-dd87-11eb-947d-0adfcca9fe87.mov

**Comment by arcangelini** [comment]
Just posting some notes here on what I have found.

It looks like the WPCOM API call for these as well as a few other domains such as jurassic.ninja ( [see issue here](https://github.com/Automattic/wp-calypso/issues/47289) ) is using the FEED URL rather than the SITE URL as most of the other API requests show.

#### Working request
<img width="1551" alt="Markup 2021-08-04 at 16 45 06" src="https://user-images.githubusercontent.com/33258733/128260920-de276de1-e88e-4784-847e-3e47ffaf3cf3.png">

#### Not working request
<img width="1505" alt="Markup 2021-08-04 at 16 47 51" src="https://user-images.githubusercontent.com/33258733/128260837-e41bc12b-9021-4025-94cb-a52c3470f2ae.png">

Inside most of the FollowButton components, the `siteUrl` is being set to the `feedUrl`. I have been looking specifically at the [reader-subscription-list-item](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/reader-subscription-list-item/index.jsx#L147). As for the `feedUrl`, it looks like it gets set to the value of `url` or uses the `getFeedUrl` method [which seems to return either the siteUrl, postUrl, or feedUrl](https://github.com/Automattic/wp-calypso/blob/trunk/client/reader/get-helpers.js#L35).

I tested setting the `siteUrl={ siteUrl }` and it seemed to solve the issue but may need some more testing. I have not been able to make sense of why the feedUrl would be used here and why some sites have it and others don't. Maybe someone else has some more insight on why this seems to be using the `feedUrl` and `siteUrl` interchangeably?

Not sure if it would be better to update the HTTP request to handle the URL properly regardless of the feed or site URL, or work to only use the site URL when building these.

**Comment by yansern** [comment]
> I tested setting the siteUrl={ siteUrl } and it seemed to solve the issue but may need some more testing. I have not been able to make sense of why the feedUrl would be used here and why some sites have it and others don't. Maybe someone else has some more insight on why this seems to be using the feedUrl and siteUrl interchangeably?

This got me wondering where this component is used because obviously it is being used in more than one place.

Did some digging and stumbled upon https://github.com/Automattic/wp-calypso/pull/13166.

In that PR description, it says: "ensure that the siteUrls and siteTitles in **full-post, combined-cards, manage/following, reader-post-cards, and feed-streams** all look good."

To switch it over to `siteUrl={ siteUrl }` would require testing all these places. As the PR is 4 years old, I wonder if they are still relevant, e.g. I wouldn't know what combined cards are.

**Comment by priethor** [comment]
As a side note, I managed to follow the sites that were giving me issues by importing a manually edited `reader-export.opml` export fil, adding the blogs' main site URL to the `htmlUrl` attribute and the feed URL to the `feedUrl`attribute. These URLs seem interchangeable in some sites like P2s but are not in the sites that were not working properly, which would contain a trailing `/feed/` in their `feedUrl`.

**Comment by roo2** [comment]
This was fixed a while ago, from memory it was a pretty complicated issue in the subsribe backend logic related to resolving the url for sites on subdomains.
