### ISSUE TITLE
Theme Showcase: Maybe allow filter lists to scroll

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#54358]
<img width="1371" alt="Screen Shot 2021-07-07 at 3 36 34 PM" src="https://user-images.githubusercontent.com/2124984/124818766-6c6aca80-df39-11eb-8aed-e521151cd2d4.png">

Some filter areas have a lot of subjects! To show them all, we have to click this oddly placed "Show all" link (underlined in the screenshot above). It might be easier/better UX if the list could scroll.

**Comment by onuro** [comment]
The original idea I had for search input is anything called "keyed suggestion" is to be converted into an autocomplete suggestions, separated from the input(meaning that dropdown won't push anything below down but work as a popover/overlay).

Within that context, we can maybe allow scrolling of results for more than a list of **viewport allowance**. But I wouldn't recommend it. Because especially with desktop resolutions with 16:9 arrangement you get really small vertical real estate and scroll within the results dropdown might cause a janky scroll.


![image](https://user-images.githubusercontent.com/645713/124844777-d917b080-df9d-11eb-9639-68c5e829816d.png)

**Comment by sixhours** [comment]
This was introduced in #54514
