### ISSUE TITLE
Welcome tour: action buttons are misaligned

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#54445]
### Steps to reproduce the behavior

1. Go to page/post editor
2. Click on Welcome Guide

#### What I expected to happen
Welcome tour UI to be as designed

#### What actually happened
Welcome tour action buttons are a bit off

Mentioned in Slack p1625861214195300-slack-C01VA100LEA

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1208" alt="Screenshot 2021-07-12 at 11 27 38" src="https://user-images.githubusercontent.com/14192054/125268448-634e7480-e310-11eb-9dd6-d384ea656333.png">

**Comment by ciampo** [comment]
The PR https://github.com/WordPress/gutenberg/pull/33511 containing a fix has been merged in Gutenberg. 

When this fix will be released in the next version of Gutenberg and adopted in Calypso, it would be great if we could revert the hotfix from this PR — @razvanpapadopol and @alshakero , is this something that you'd be able to track on your side?

**Comment by ciampo** [comment]
~FYI, Gutenberg 11.1.0 was [released last week](https://github.com/WordPress/gutenberg/releases/tag/v11.1.0). It is already in use on simple sites and should soon be on Atomic sites.~

Let me know if you have capacity for reverting the hotfix, otherwise I'm happy to have a go at it myself!

Edit: the fix will be actually released in Gutenberg 11.2.0 [later this week](https://github.com/WordPress/gutenberg/milestones?direction=asc&sort=due_date)
