### ISSUE TITLE
Themes: Launch Baker to the public.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#54817]
Let's launch the new Baker theme to the public. We won't do any sort of en.blog post, but the launch should include a heads-up to support.

@ianstewart has begun the process, so he'll know what tasks remain.

![baker](https://user-images.githubusercontent.com/349751/126708913-aa6a5d93-d21b-4bf5-bc3d-16dcca9dae05.png)

**Comment by kwight** [comment]
@ianstewart internal notes:

> Launch generated themes:
> * got stuck when he got to the translation thing
> * script needs to be rerun to get the screenshots in?
> * and then we need to recommit the theme.

**Comment by sixhours** [comment]
Baker's POT file diff is here: D64618-code

**Comment by sixhours** [comment]
Sent Headstart annotation for translation via Linguine, Strand ID: 89188

**Comment by sixhours** [comment]
![baker-blocks](https://user-images.githubusercontent.com/2124984/127017686-88d70c6b-8de8-4c75-a55a-c8be65bdddb3.png)

Block highlights screenshot for the Showcase /cc @ianstewart

**Comment by sixhours** [comment]
Screenshot diff: D64633-code

**Comment by sixhours** [comment]
I can't find the source/copyright info for the avatar photo for this theme; IIRC we need to be able to point to the image's source if we want to submit this theme to WP.org in the future (since it's included in the theme's screenshot.png). What do you think @ianstewart? Should we swap the image out for something we can credit or not worry about it?

**Comment by sixhours** [comment]
Theme has been Network Activated and Showcase pages published. I'll notify Happiness shortly!
