### ISSUE TITLE
Varia based themes: When gutenberg plugin deactivated unable to save changes

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#54922]
### Steps to reproduce the behavior

1. Activate a varia based theme 
2. deactivate the gutenberg plugin
3. check customizer for save option

#### What I expected to happen
you should be able to save changes as normal

#### What actually happened
the save button is replaced with a cannot activate button with no further context

### Context
two AT pings, latest p2  for one here: p9F6qB-7f6-p2

#### Browser / OS version
not specific

#### Is this specific to the applied theme? Which one?
Varia based; and likely any other theme that relies on FSE?

#### Does this happen on simple or atomic sites or both?
AT; can't deactivate Gutenberg on simple

#### Is there any console output or error text?
nope

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
all sites with gutenberg deactivated and varia theme

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/47717887/127139144-ce6faa07-9cef-4eed-b6c6-2ddd14268da9.png)
![image](https://user-images.githubusercontent.com/47717887/127139159-66e7845f-8ea5-4df0-b1fc-b56c6a5d40c3.png)

**Comment by inaikem** [comment]
I was able to replicate on my Atomic test site.

<img width="356" alt="Screen Shot 2021-07-27 at 6 12 17 PM" src="https://user-images.githubusercontent.com/66711744/127139700-3c5cd285-6ba0-4cd5-8270-48e5d9c0ad30.png">

**Comment by Copons** [comment]
I think the issue here is that Varia shouldn't have access to the Customizer, exactly like its children. 🤔 

But let me backtrack briefly.

The Varia family of themes was used in 2019 for the Legacy Dotcom FSE experiment, which has been discontinued.
In that experiment, the Customizer was removed, and the site design was being done straight into the Page Editor.

Those themes are tagged as `full-site-editing` in their [stylesheet](https://github.com/Automattic/themes/blob/7e8706ed7f703aacbbe00b9a1b182b2f2cede76e/varia/style.css#L13
).

```
Tags: one-column, flexible-header, accessibility-ready, custom-colors, custom-menu, custom-logo, editor-style, featured-images, footer-widgets, rtl-language-support, sticky-post, threaded-comments, translation-ready, auto-loading-homepage, full-site-editing, jetpack-global-styles
```

In Core 5.8 (which was released a few days ago), themes with that tag strictly [require Gutenberg to be activated](https://github.com/WordPress/WordPress/blob/0f9e2d2c6605190299c984ed9e6ab9951c53c262/wp-includes/theme.php#L914-L923
):

```php
if ( ! empty( $theme_tags ) && in_array( 'full-site-editing', $theme_tags, true ) && ! function_exists( 'gutenberg_is_fse_theme' ) ) {
	return new WP_Error(
		'theme_requires_gutenberg_plugin',
		sprintf(
				/* translators: %s: Theme name. */
			_x( '<strong>Error:</strong> This theme (%s) uses Full Site Editing, which requires the Gutenberg plugin to be activated.', 'theme' ),
			$theme->display( 'Name' )
		)
	);
}

```

The `full-site-editing` tag check also happens in the [Customizer](https://github.com/WordPress/WordPress/blob/0f9e2d2c6605190299c984ed9e6ab9951c53c262/wp-admin/customize.php#L192-L194
):

```php
if ( ! empty( $theme_tags ) && in_array( 'full-site-editing', $theme_tags, true ) && ! function_exists( 'gutenberg_is_fse_theme' ) ) {
	$fse_safe = false;
}
```

Which leads to the ["Cannot Activate" button](https://github.com/WordPress/WordPress/blob/0f9e2d2c6605190299c984ed9e6ab9951c53c262/wp-admin/customize.php#L202-L206):

```php
<?php if ( $compatible_wp && $compatible_php && $fse_safe ) : ?>

...

<?php else : ?>
	<?php $save_text = _x( 'Cannot Activate', 'theme' ); ?>
	<div id="customize-save-button-wrapper" class="customize-save-button-wrapper disabled" >
		<button class="button button-primary disabled" aria-label="<?php esc_attr_e( 'Publish Settings' ); ?>" aria-expanded="false" disabled><?php echo $save_text; ?></button>
	</div>
<?php endif; ?>
```

---

Wrapping up, I think that we have a few things to check:

- Should we remove the `full-site-editing` tag from the Varia family themes, since they are not (Core) FSE themes?
  - Double check if Legacy Dotcom FSE relies on the theme stylesheet tag, or just on the Dotcom internal `full-site-editing` taxonomy.
    - If it needs the stylesheet tag, we would also update Dotcom/ETK with another way for Legacy Dotcom FSE to determine if the theme is valid.
- Why does Varia show the Customizer menu item, while its children don't?
  - Should we hide the Customizer from Varia as well?

CC @Automattic/cylon @Automattic/theam

**Comment by MaggieCabrera** [comment]
From the theme's perspective I think removing the fse tag is ok, in fact it's preferred since it conflicts with the dotorg tag and it's confusing.

**Comment by Addison-Stavlo** [comment]
> Why does Varia show the Customizer menu item, while its children don't?
Should we hide the Customizer from Varia as well?

Im actually a bit confused on what is supposed to happen here with these themes.  Looking at one of them (Morden) on simple sites I have access to the customizer, but as soon as I transfer it to Atomic the customizer option is no longer available.

> Double check if Legacy Dotcom FSE relies on the theme stylesheet tag, or just on the Dotcom internal full-site-editing taxonomy.

If we only need the taxonomy, removing the theme tag seems like the best way to go about it.

> If it needs the stylesheet tag, we would also update Dotcom/ETK with another way for Legacy Dotcom FSE to determine if the theme is valid.

I don't think this changes any of the results for the core conditions though. 🤔   But yeah, `is_full_site_editing_active` (from ETK) checks for both the sticker and the FSE tag, meaning there could be the conflict of having the LFSE sticker and a core FSE theme activated triggering the LFSE experience if it really is reading the stylesheet tag and not the internal taxonomy.

**Comment by Copons** [comment]
I think we should try to make it all more consistent:

- `full-site-editing` stylesheet tag
  - Used by Core FSE (as of 5.8).
  - Maybe used by Legacy FSE (ETK).
- `full-site-editing` internal taxonomy
  - Used by the theme showcase to show A8C's Legacy FSE themes (Varia family).
  - Maybe used by Legacy FSE (ETK).
- `block-templates` internal taxonomy
  - Used by the theme showcase to show A8C's Core FSE themes.

This makes me 🤯 big time!

**Comment by Addison-Stavlo** [comment]
> This makes me 🤯 big time!

Are we able to change the tag/tax for LFSE and its themes to something like `dotcom-legacy-fse`, and roll it out in a way that will won't break any LFSE sites?  That way we can avoid the confusion with having a `full-site-editing` taxonomy that doesn't correspond to core FSE (and avoid having to use the less obvious `block-templates` tax there instead)?

**Comment by MaggieCabrera** [comment]
The PR that removes the fse tag from the css of the themes that are not actually using the site editor: https://github.com/Automattic/themes/pull/4335

**Comment by mattwiebe** [comment]
While we work on a better fix, this can temporarily be resolved by activating the Gutenberg plugin

**Comment by mattwiebe** [comment]
We've shipped a fix for this now. Feel free to re-open this issue and ping me if it persists.
