### ISSUE TITLE
Switching currency does not reflect the new price on plan switcher view of checkout without reloading

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#55019]
### Steps to reproduce the behavior

- Add a plan to a free site and reach the checkout stage of the purchase flow.
- Have a staff update your WordPress.com account's currency
- See that the currency is updated for the items in the cart, but not on the plan length switcher section

#### What I expected to happen

The currency on the plan length switcher is updated too.

#### What actually happened

The currency isn't updated on the plan length switcher view.

### Context

Internal testing: p9anKZ-1VR-p2#comment-3858

#### Browser / OS version

Firefox 90.0.2 (64-bit).

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

In the image below, INR is correct, SGD is not. I haven't tried refreshing the checkout page to see if the currency updates, but I imagine that must not be necessary.

![image](https://user-images.githubusercontent.com/18581859/127472635-6dba158b-9789-4a3d-b987-bfd30a0b2dcb.png)

**Comment by inaikem** [comment]
Thanks for reporting this. I was able to replicate the issue above. 

Regarding the below, reloading the page manually does refresh the term variation currency and values to reflect the correct information.

>  I haven't tried refreshing the checkout page to see if the currency updates, but I imagine that must not be necessary.

**Comment by sirbrillig** [comment]
The reason for this is that the plan variant picker uses prices from the products endpoint, which is fetched by a query component and managed by redux; most of the rest of checkout uses data from the shopping-cart endpoint, which is fetched by the `@automattic/shopping-cart` package and refetches if the page is refocused.

If you see the cart automatically update when your currency changes (a relatively rare occurrence), it is only because you unfocused the page for about a minute and then refocused it. This is sort of a bonus feature and not implemented in most of calypso's state management system (at least until we start using react-query for everything). It's still expected that with any change, you must reload the page manually.

That said, it is inconsistent. It might be nice to refactor the plan variant picker to use react-query so that it would also benefit from the fetch-on-focus feature, but given the complexity of that component's data needs, I don't see that happening anytime soon.

**Comment by sirbrillig** [comment]
This should be fixed by https://github.com/Automattic/wp-calypso/pull/70452
