### ISSUE TITLE
Featured Image section not showing

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#55081]
Steps to reproduce

    Starting at URL: wordpress.com
    Start a new post on a Gutenberg-enabled site using a certain theme (confirmed with Linen)
    Note the Featured Image option is not shown

What I expected

To be able to set a Featured Image regardless of theme support as it's used by things like Publicized
What happened instead

No Featured Image option was shown

This happened again with the Plane theme not showing a section for Featured Images 29763905-hc. It's the same as https://github.com/Automattic/wp-calypso/pull/29868 

and 

https://github.com/Automattic/wp-calypso/issues/28938

**Comment by synora** [comment]
Triaged. Can replicate.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by alshakero** [comment]
I managed to reproduce.

Atomic site, business plan, theme Plane.

Can confirm it's only reproducible on Atomic sites, tested with Plane on a simple site and it works.

**Comment by alshakero** [comment]
Hi @Copons and @david-binda! I have been fighting with this issue by trying to create a replica of this fix (D22775-code) for atomic sites, but to no avail. 

Would really appreciate any guidance or direction on this. Since the business logic was already discussed [here](https://github.com/Automattic/wp-calypso/issues/28938), it seems reasonable to also always allow featured images in atomic sites too.

**Comment by Copons** [comment]
> Hi @Copons and @david-binda! I have been fighting with this issue by trying to create a replica of this fix (D22775-code) for atomic sites, but to no avail.
> 
> Would really appreciate any guidance or direction on this. Since the business logic was already discussed [here](https://github.com/Automattic/wp-calypso/issues/28938), it seems reasonable to also always allow featured images in atomic sites too.

Hi @alshakero, sorry for the delay, the notification fell through the cracks. 🙇‍♂️ 

I'm not quite sure how to solve this on Atomic, to be honest. Partly because I don't know almost anything about Publicize, and partly because I'm really bad at Atomic. 😬
 
The original fix was very straightforward though.
In REST context, just force support of the featured image (through the Core's [`rest_prepare_theme` filter](https://developer.wordpress.org/reference/hooks/rest_prepare_theme/)) on sites with
- Publicize enabled.
- A theme that doesn't support featured images.

I kinda guess it should be possible to do something similar in JP which has a Publicize module already. 🤔

**Comment by Gustavo-Hilario** [comment]
This same user contacted us again today with this same issue 31163161-hc. We have made some tests and it seems that the `Quick Featured Image` plugin workaround is still working, but they are looking for a permanent fix so they can insert a featured image while editing their posts.

**Comment by jordesign** [comment]
Plane has ~100k active installs and Linen (retired) has about 3300 active installs.

It sounds as though the issue here is limited to themes that don't support Featured Images - something I suspect is likely to happen less and less often. Interested on other thoughts on prioritising this @simison @ianstewart

**Comment by manuelrebollo-a11y** [comment]
> This same user contacted us again today with this same issue 31163161-hc

The customer contacted us again, in 32939252-hc
Following up via 4771268-zd-woothemes

**Comment by p-jackson** [comment]
I've got a fix for atomic: 884-gh-Automattic/wpcomsh
But I've also started a conversation about whether the fix should actually be for Jetpack sites more broadly p1HpG7-frH-p2

**Comment by p-jackson** [comment]
Temporary fix for Atomic coming in 884-gh-Automattic/wpcomsh. Better fix for the underlying issue coming in https://github.com/Automattic/jetpack/pull/23871
