### ISSUE TITLE
HEIC Image Uploads

### ISSUE THREAD

**Issue by rezzap** [Automattic/wp-calypso#55102]
### Steps to reproduce the behavior

1. From a Mac computer, go to your iCloud Photo library in a browser
2. Click on some images and use the download icon to download images.
3. Open the folder, images are saved into HEIC format. 
4. Open WordPress.com in a browser to create a new post and add an image block. 
5. Select the option to upload media and use the downloaded HEIC images
6. You'll see an error message in the editor `This image has an empty alt attribute; its file name is IMG_0574.heic`
7. Navigate to the Media Library and the image displays there but in HEIC format

#### What I expected to happen

If the image can't be uploaded, it shouldn't be in the media library. It's also very confusing for users who then end up with multiple images in their media library in HEIC format that cannot be inserted into their posts. 

Using the mobile app, the HEIC files are automatically converted to JPEG making image uploads from iOS devices easy. 

#### What actually happened

The images show in the media library, fail to upload and the process to convert them is quite confusing. It's very time consuming to have to convert manually each image to a different format. 

I have had a number of chats where this comes up and guiding the user on steps to convert image formats is not ideal and something we should either do automatically or block the uploads with a clearer error message. 

### Context

Chat: 30911034-hc

#### Browser / OS version

Any Mac/browser combo will give you the same effect. 

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both (HEIC image file type is not supported)

#### Is there any console output or error text?

This image has an empty alt attribute; its file name is IMG_0574.heic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Makes image uploads very inconvenient for Mac users with HEIC image formats.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Image 2021-08-02 at 4 38 42 pm](https://user-images.githubusercontent.com/10325627/127887659-675dba32-2538-4e23-98be-40f891d15c77.jpg)
![Image 2021-08-02 at 4 39 04 pm](https://user-images.githubusercontent.com/10325627/127887666-afdad939-28fa-4e46-ad12-c8b8931dd1d0.jpg)

**Comment by synora** [comment]
When I get to step 5, my HEIC image is grayed out in my folder-it's unclickable.  I cannot upload a HEIC image to my Media Library.

I attempted to drag and drop the image in the Media Library and that's when I got the "1 file could not be uploaded because the file type is not supported." Tested on a simple site.

**Comment by rezzap** [comment]
Yes, sorry, this is only happening on drag and drop at that point. :)

**Comment by sixhours** [comment]
Good to note this is only happening for Atomic sites. On a Simple site, I'm not able to upload a HEIC file regardless of how I go about doing so; I tried a few ways in the editor with the Image block, both selecting a file and dragging and dropping:

https://user-images.githubusercontent.com/2124984/129971862-60716c20-163c-41d5-a394-323fa47c9db9.mov

**Comment by sixhours** [comment]
Confirmed I'm only able to upload an HEIC by dragging and dropping into Image blocks (Image, Image Compare, Media & Text, Gallery, etc.) on an Atomic site, not via the Media Library. That seems to indicate this is a core issue with the editor not performing checks on the file type before uploading via drag-and-drop into blocks.

Confirmed this is happening on a non-Atomic WP install with my personal site:

<img width="839" alt="Screen Shot 2021-08-19 at 11 35 52 AM" src="https://user-images.githubusercontent.com/2124984/130099553-1a39b0d5-9637-45d4-9d2e-90168125b459.png">

Simple sites have additional security measures, apparently. We might be able to transfer those over to Atomic sites using the ETK or wpsh while we're waiting on HEIC support.

**Comment by sixhours** [comment]
It looks like we add HEIC file types to the restricted list for simple sites, which is what prompts this error no matter how you try to upload them:

<img width="795" alt="Screen Shot 2021-08-19 at 11 53 57 AM" src="https://user-images.githubusercontent.com/2124984/130101414-b23998dd-be97-4f32-a305-ca53ddfbb301.png">

I confirmed this by adding this restriction to one of my Atomic sites with the MIME types plugin.

**Comment by sixhours** [comment]
Reported the editor issue here: https://github.com/WordPress/gutenberg/issues/34181

**Comment by sixhours** [comment]
We might be able to extend the media uploader on Atomic sites with a small plugin using the `editor.MediaUploader` hook and checking the MIME type before uploading with `onFilesPreUpload`; this silently filters out anything with a `image/heic` file type, for example:

```
const CheckHEIC = wp.compose.createHigherOrderComponent( ( MediaPlaceholder ) => {
	return ( props ) => {
		props.onFilesPreUpload = ( files ) => {
			if ( files ) {
				const filteredFiles = Object.values( files ).filter( file => {
					if ( "image/heic" !== file.type ) {
						return file;
					}
				});
				return filteredFiles;
			}
		};

		return wp.element.createElement(
			MediaPlaceholder,
			props,
		);
	};
}, 'CheckHEIC' );

wp.hooks.addFilter(
	'editor.MediaPlaceholder',
	'wpcom/CheckHEIC',
	CheckHEIC
);
```

**Comment by sixhours** [comment]
Core's media library treats HEIC uploads like this:
<img width="659" alt="Screen Shot 2021-08-19 at 12 46 49 PM" src="https://user-images.githubusercontent.com/2124984/130247273-7ad16c45-6187-4bae-9956-a001dc14ed88.png">

You can still upload them, but a warning is shown noting that they're not viewable in the browser.

**Comment by simison** [comment]
@sixhours @flaviozavan let's please coordinate when the HEIC support can be added to .com. I'd love to have a timeline. Latest convo in p3topS-Tn-p2#comment-3725

**Comment by mriyazuddin** [comment]
Hey @sixhours ! Looks like this issue is back again. I have a user facing issues uploading HEIC images to posts or WooCommerce products. I'm able to replicate this as well. Here's the error message:

<img width="1440" alt="Screenshot on 2022-06-06 at 12-26-24" src="https://user-images.githubusercontent.com/49064126/172111326-373a2feb-291a-44c6-9eb4-5e374006318a.png">

**Comment by mriyazuddin** [comment]
- [ ] Reported in #5272044-zd

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- **I can confirm that HEIC images are not supported by WordPress.com, or on a Self-hosted site.**
- That seems to be the conclusion of the conversation above, and by design.
- I believe the issue that needs to happen here is that our docs need to be updated to remove `heic` from the list of supported image types. Requested that update here: 1609-gh-Automattic/en.support-docs-content

📌 ACTIONS
- Closing again given the discussion above - See https://github.com/Automattic/wp-calypso/pull/55637 for further details on this restriction.

📌 Message to Author
 - @mriyazuddin just a heads up on this!

**Comment by simison** [comment]
> That seems to be the conclusion of the conversation above, and by design.


Support for HEIC on .com was added just in April 2022 so something has broken since: pLZE4-l55-p2 and pMz3w-dYl-p2#comment-98009

I.e. this _should_ work. There likely is bug happening that it doesn't work always. In the comments above you can see stats link which definitely shows HEIC images being actively uploaded and working.

cc @Automattic/team-calypso-platform anything with recent Gutenberg upgrades that might've broken HEIC upload support in the last two weeks?

**Comment by sajmes** [comment]
User report: 35917397-hc

**Comment by kristinaquinones** [comment]
35916724-hc
5330304-zen

**Comment by simison** [comment]
@flaviozavan :wave: know if something has changed for HEIC images to stop working? See https://github.com/Automattic/wp-calypso/issues/55102#issuecomment-1147114636

**Comment by flaviozavan** [comment]
> @flaviozavan wave know if something has changed for HEIC images to stop working? See [#55102 (comment)](https://github.com/Automattic/wp-calypso/issues/55102#issuecomment-1147114636)

@simison There have been no changes by or others related to this. Our stats still indicate over 1k daily uploads in the format. I ran some tests and I can upload them via the media manager, but when editing a post/page, the frontend stops me before the upload and conversion can happen

**Comment by cuemarie** [comment]
Thanks for the clarification @simison ! Since this was scrubbed and replicated above: https://github.com/Automattic/wp-calypso/issues/55102#issuecomment-1155514082 , just marking as `Triaged` and moving forward in the PQA boards

**Comment by kelasante** [comment]
User report in  35949977-hc. I am also not able to upload .heic images on my personal atomic site.

**Comment by cometgrrl** [comment]
I tested on Atomic, summarizing here since there's a lot of various things described in the comments that appear outdated.

- I can upload an HEIC image to the media library
- When I choose from the media library, I get this error `This image has an empty alt attribute; its file name is IMG_0574.heic`
- If I try to upload into an image block, HEIC images are greyed out and not selectable
- If I drag an HEIC into an image block, I get this error `HEIC images are not viewable in the editor. Please convert to a JPG, PNG, or GIF and try again.`

Per @simison, HEIC images should be supported.

**Comment by sudeepbaral** [comment]
- [ ] 5442466-zen

Suggested user to convert the HEIC images to JPEG and re-upload them. The images are loading as a thumbnail in their site (they were using Elementor) but do not load when expanded.

**Comment by tanjoymor** [comment]
Another case here: 5458059-ZD (suggested converting to JPG and re-upload)

**Comment by ai2n** [comment]
Ditto on 37042040-hc

**Comment by connorhipps** [comment]
The same issue appears again here 5711438-zd-woothemes

**Comment by freelylovinglife** [comment]
Another report 5714674-ZD

**Comment by gwensmithx** [comment]
Another report here: #5774031-zd - I'm able to repro on my AT site. I can only drag and drop the images into the media library. I was also a bit confused because our support docs say we do support .heic: https://wordpress.com/support/accepted-filetypes/#images I just want to confirm that this is not the case?

**Comment by danielbachhuber** [comment]
In debugging this a little bit, it's possible to upload `.heic` into the Media Library:

<img width="1813" alt="image" src="https://user-images.githubusercontent.com/36432/234702679-3425abc6-10fa-46c1-97f5-f073b30741fe.png">

However, I can't upload `.heic` into an Image Block:

<img width="1813" alt="image" src="https://user-images.githubusercontent.com/36432/234702830-edc7c7d6-226d-449b-b1fe-c82b8c0c06dc.png">

My guess is that it's because the Image Block `<input>` has a `accept="image/*"` restriction, and the browser doesn't recognize `.heic` as a supported image type.

If I upload a `.heic` file into the Media Library, it seems kinda broken:

<img width="1813" alt="image" src="https://user-images.githubusercontent.com/36432/234704395-7d345208-cf37-40e1-88dc-e0e2a58ea2b0.png">

Here's a related core ticket: https://core.trac.wordpress.org/ticket/53645

I also glanced through p3topS-Tn-p2 and pMz3w-dYl-p2 

Given browsers don't support `.heic` in the first place, I'd suggest we:
1. Remove support for uploading `.heic` files.
2. Update our documentation to explain that `.heic` isn't a browser-supported format, and that users should convert the image to JPG before uploading.

**Comment by simison** [comment]
@danielbachhuber tested Simple / Atomic / both?

I dug and found this script disabling HEICs in the editor — explains a lot! :-D

https://github.com/Automattic/wp-calypso/blob/fd176117327073d6fb9322d9961823a0550cf366/apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js

Added in 2021 at https://github.com/Automattic/wp-calypso/pull/55637

Wanna re-test without the script?

**Comment by danielbachhuber** [comment]
> tested Simple / Atomic / both?

@simison Sorry, my tests are from Atomic (see URL in screenshots).

It looks like it gets magically converted to a JPEG on Simple sites:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/36432/234840875-cc49211f-2a48-4b1a-8b8c-672907d10afd.png">

Here's the corresponding code: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Survs%2Qfhccbeg.cuc%3Se%3Qn982017s-og

I guess that code was never applied to Atomic sites? The `Photon_OpenCV` class doesn't appear to exist:

```
$ wp shell
wp> class_exists( 'Photon_OpenCV' );
=> bool(false)
```

However, it's not possible to upload `.heic` or `.heif` into the Image Block on a Simple Site:

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/36432/234841883-b96175e9-8fab-4a6b-84ee-ccd1836672bc.png">

> I dug and found this script disabling HEICs in the editor — explains a lot! :-D

Er, not really. That script is specific to drag and drop upload to the Image Block. Without it, the user experiences this error: https://github.com/WordPress/gutenberg/issues/34181

**Comment by simison** [comment]
>I guess that code was never applied to Atomic sites? The Photon_OpenCV class doesn't appear to exist:

@flaviozavan can you comment to that?

**Comment by danielbachhuber** [comment]
Some discussion in Slack p1684237227631749-slack-C7YPW6K40

**Comment by danielbachhuber** [comment]
P2 request p9o2xV-35e-p2

**Comment by danielbachhuber** [comment]
`Photon_OpenCV` is now available in Atomic environments, so I spun up a PR to bring the WPCOM functionality to WoA sites: https://github.com/Automattic/jetpack/pull/31719

Once that's live, I'll remove the existing WPCOM code (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Survs%2Qfhccbeg.cuc%3Se%3Qn982017s-og) and submit a request to update the documentation.

Because the Image Block `<input>` has a `accept="image/*"` restriction, we won't be able to add HEIC/HEIF image upload support to the Image Block / Block Editor generally.

**Comment by simison** [comment]
Nice job!

> Because the Image Block <input> has a accept="image/*" restriction, we won't be able to add HEIC/HEIF image upload support to the Image Block / Block Editor generally.

Worth proposing adding a filter in Gutenberg for the `accepts`? It's not just image block but gallery blocks, slideshow blocks in Jetpack, cover block, etc.

**Comment by danielbachhuber** [comment]
> Worth proposing adding a filter in Gutenberg for the `accepts`? It's not just image block but gallery blocks, slideshow blocks in Jetpack, cover block, etc.

@simison I thought about something like that. However, I think it would need to be more than a filter: if you upload a video to the Image Block, it should auto-transform to a Video Block, etc. Probably not worth solving at this time.

**Comment by danielbachhuber** [comment]
HEIC/HEIF image upload support is now live for WoA sites.

Shared with WPCOM Happy p1694177549057259-slack-CB0B2G43X
