### ISSUE TITLE
SEO Settings Enhancement: Show Save Settings button on Site Verification Services section

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5515]
#### Steps to reproduce
1. Starting at URL: For a WordPress.com public site, visit https://wpcalypso.wordpress.com/settings/seo/
2. Scroll to Site Verification Services
3. Enter a code
#### What I expected

To see a Save Settings option
#### What happened instead

The Save Settings option is at the top of the screen. Could we show a Save Settings button for the Site Verification Services section as well similar to General Settings.
#### Browser / OS version

Chrome OSX
##### Current Implementation

![current](https://cloud.githubusercontent.com/assets/128826/15459399/3cd8d2f4-20e8-11e6-8d73-959f92e528fc.png)
##### General Settings - Multiple Save Setttings

![general settings](https://cloud.githubusercontent.com/assets/128826/15459411/57374dce-20e8-11e6-82fb-780d45cc933f.png)

**Comment by drw158** [comment]
@roundhill Options:

- Don't fix this, because it is sort of out of scope, and other pages like Discussion suffer the same issue. I agree that it's not the best UX though. It should be fixed throughout all of settings.
- Break up this page into 2 sections: first section would include the Intro, XML Sitemap, and Meta Description in that order. The second section would have just the verification stuff. Each section would have a save button. We would probably need to tweak the notices to not be global.

**Comment by drw158** [comment]
The Save button now appears on Site Verification Services.
