### ISSUE TITLE
Display Name Not Updating Across Atomic Site

### ISSUE THREAD

**Issue by nicolynramos** [Automattic/wp-calypso#55175]
### Steps to Reproduce

1. On Atomic site, follow wordpress.com/me to update Display Name
2. View posts by user and see the Display Name has not been updated.

### What I expected to happen

Posts should show the updated Display Name

### What actually happened

Old display name shown

### Context

Since the site is Atomic, I also tried updating through WP-Admin
1. Click on Users
2. Switch to Classic View in Screen Options (wp-admin)
3. Edit user
4. Field to update Display Name is missing
5. Banner appears "WordPress.com users can change their profile’s basic details ( i.e., First Name, Last Name, Display Name, About ) in WordPress.com Profile settings."

It appears that the option to change the display name in WP-Admin has been removed and updating display name in .com profile settings does not update across the site.

### Operating System

macOS

### Browser

Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Other information

Able to reproduce across all Atomic sites.

**Comment by wpshellbelle** [comment]
Report here: 30920688-hc

I did find that the display name is not updating on the site. Instead, the display name is displaying as the username. As a workaround, you can update the display name via CLI. 

Issue is only present on Atomic sites.

**Comment by kosiew** [comment]
Hi @nicolynramos ,

Thanks for reporting this and the detailed steps.


I tested and could not replicate this:

![Screen Capture on 2021-08-09 at 18-48-57](https://user-images.githubusercontent.com/29057562/128695652-8405b8ca-ae43-42b4-bb3e-8ae1d0eb8657.gif)

Theme: Storefront child theme: Bistro.

Closing this. Please reopen if you have additional context to add.

**Comment by katiebethbrown** [comment]
I'm re-opening this issue, as I've run into it and can replicate.

If Jetpack is disconnected, Public Display Name changes in Calypso will not be reflected in wp-admin.

GIF showing changes not reflected on atomic site if Jetpack is disconnected:
![UsernameUpdateGIF](https://user-images.githubusercontent.com/42279181/137964855-43c457e4-b320-431d-aa66-d2972fa9a081.gif)

But I would expect them to update once we reconnect to ensure consistency since users can't edit directly in wp-admin. But reconnecting Jetpack and running a sync does not appear to update them either. 

After a reconnect:
<img width="2067" alt="Aferreconnect" src="https://user-images.githubusercontent.com/42279181/137965031-fade752e-b6e1-4a4d-a645-6cc75cc2327a.png">

This is an issue because users have no way to check whether wp-admin was correctly updated because we're just linking them right back to Calypso (where the incorrect display name shows).

The only way to update the display name in wp-admin is by ensuring Jetpack is connected, and then making a change in Calypso and saving it or updating it via CLI.

**Comment by sixhours** [comment]
I'm able to reproduce this on my test site using @katiebethbrown's excellent instructions.

After looking at Jetpack Sync's documentation and some of the code, I suspect we're comparing user IDs only -- the existing ID vs. the to-be-synced ID -- and see they are the same; the only thing that's changed is the username meta, which we never check for changes.

This is where we pull the user information to be synced:

https://github.com/Automattic/jetpack/blob/3830aa48a592878a5470e7673c813d094b07c25f/projects/packages/sync/src/modules/class-users.php#L707

And this is where we check to see how much data will be synced if we update the data:

https://github.com/Automattic/jetpack/blob/3830aa48a592878a5470e7673c813d094b07c25f/projects/packages/sync/src/modules/class-users.php#L646

In the latter case, we only check user meta (capabilities) and the user IDs.

I need to confirm this with logging out the data in those areas and checking the user meta via API. Will keep working at it.

**Comment by sixhours** [comment]
Checking the user received data from the API, we may be able to "fix" this on the front end by displaying the `name` from `linked_user_info` rather than the name assigned to the blog ID:
<img width="750" alt="Screen Shot 2021-11-16 at 12 58 41 PM" src="https://user-images.githubusercontent.com/2124984/142040289-d95d3a9d-b617-4397-babb-5eb5b9281072.png">

This gets set in `class.wpcom-json-api-endpoints.php#54` and is specifically for dotcom users with Jetpack connected sites.

Then we wouldn't need to sync additional user meta via Jetpack since we'd be reading the information from the source. I'd need to confirm that data is still available when a site is disconnected from Jetpack, though.

**Comment by sixhours** [comment]
> Then we wouldn't need to sync additional user meta via Jetpack since we'd be reading the information from the source. I'd need to confirm that data is still available when a site is disconnected from Jetpack, though.

Tested this, and when a site is disconnected from Jetpack, you can't access the Calypso UI for the Atomic site, though you can access the  UI for the shadow site, and it still contains the linked user info. Since Simple sites won't have `linked_user_info`, we can check to see if there is `linked_user_info` and favor that `name` over the site's `name` since it's the most up to date.

I'm leaning toward this as a solution rather than updating the sync scripts to check specific user meta because it seems like checking *all* meta for changes during sync would be consume more resources, take more time...and because honestly backend stuff is not my forte. ;) 

This does mean Jetpack sites (not necessarily Atomic ones) will change to show the `linked_user_info` name rather than their native WP.org name value in the `/people` screens. I feel like this makes sense, though? If they're using the WP.com interface I would expect it to show WP.com's version of the data.

**Comment by sixhours** [comment]
Scrapped a front-end approach for now, since the People screen is not the only place you'll find the display name in Calypso. :-/ 

~~I think this might have been caused by the fix in Automattic/jetpack#20479, which prevents syncing of stale user data from WP.com to `/wp-admin`. It's possible the updated WP.com data is seen as "stale" after a disconnection.~~ Not true, this PR applied to data being saved to the database, not Jetpack Sync failing to update data between the site and WP.com. Will keep digging!

**Comment by sixhours** [comment]
I made marginal progress here, but I've spent enough time with it that I think we need to consult Jetpack folks who better understand Jetpack Sync. I'm going to ping in #jetpack-crew, but here's where I'm at:

* I think I found where we compare different values for user meta and opened a PR to add the `$user->name` to that checksum here: Automattic/jetpack#21784
* I've also figured out how to sandbox the checksums and run them manually, so I've tried updating my sandbox with the above changes, running `composer update`, and manually running a sandboxed checksum.
* ...but that's not fixing the username discrepancy on my WoA site. :) I suspect I'm not doing something right with the Composer process for the package on my sandbox, or my hunch about where/how to fix it is incorrect.

**Comment by sixhours** [comment]
Pinged in #jetpack-crew and they explained something that changes my tack:

* "Sync is predicated on the idea that the local site has the most accurate information for the site in question." -- Jetpack Sync only operates one-way from Jetpack connected site -> WP.com cache site.
* But for this fix, we need to figure out where we pass info from WP.com -> the Jetpack connected site.
* So, it's not a Jetpack Sync issue. :)

**Comment by sixhours** [comment]
OK, so after chatting with @kraftbj I think I have a better handle on the expected behavior here.

> But I would expect them to update once we reconnect to ensure consistency since users can't edit directly in wp-admin. But reconnecting Jetpack and running a sync does not appear to update them either.

Jetpack Sync presumes the most accurate data is located on the local Jetpack site, so reconnecting to Jetpack doesn't fix the issue because that doesn't trigger a WP.com -> Jetpack site sync, only a Jetpack site -> WP.com sync.

The updates for WP.com -> Atomic sites are run on our side and hooked into `updated_user_meta` and `profile_update` in `wp-content/mu-plugins/masterbar.php` -- effectively, updating the profile in Calypso triggers the WP.com -> Jetpack site sync.

It's possible there's a hook (like `jetpack_connected`) where we could also run those checks, so the data gets updated on reconnection. I'll look into that, but IMO, going to `/me` and updating the profile information is a solid workaround unless this issue is widespread.

**Comment by sixhours** [comment]
> It's possible there's a hook (like jetpack_connected) where we could also run those checks, so the data gets updated on reconnection. I'll look into that, but IMO, going to /me and updating the profile information is a solid workaround unless this issue is widespread.

I dug into this, and we do have several Jetpack hooks at our disposal, but the more I think about it, the more I think this is a wontfix.

* If we operate under the assumption that the Jetpack site is the source of truth, we shouldn't try to push the WP.com site's data back to the Jetpack site and overwrite it.
* But perhaps we *should* see the WP.com side of an Atomic site as the source of truth in this case?
* I'm not clear on the level of impact this bug has. It seems like it should be relatively rare with a straightforward workaround. Is this something that comes up frequently @katiebethbrown? @Robertght you may have thoughts, too.

I'd like to get a second opinion from @mreishus or @nelsonec87 before we close it out, though. Maybe they'll see something I'm missing.

**Comment by katiebethbrown** [comment]
> Is this something that comes up frequently @katiebethbrown?

Anecdotally, I'd say it isn't too common, at least in my experience. 

It seems likely that it happens more than we hear about, but just isn't caught because if Jetpack is disconnected there are other issues that are more visible so those become the priority for the site owner.

**Comment by mreishus** [comment]
After reading through the ticket and researching, here is my current understanding:
* Jetpack Sync is a process designed to send data in one direction only: from the Atomic site to WPCOM.
* `display_name` is a field that can only be changed on the WPCOM side. When it is changed, it uses `update_user_data_in_all_atomic_sites() -> atomic_update_user_data()` to push the change to all currently connected Atomic sites.
  * This was created in D61740-code and #46077.
  * (Another PR on the jetpack side rejects stale data: https://github.com/Automattic/jetpack/pull/20479 )
  * If there is a currently disconnected Atomic site, that change is not applied to the disconnected site and is 'lost'.

One idea I have for a solution is:
* When `atomic_update_user_data()` is given an update, but finds a disconnected jetpack site, it stores that update in a queue somewhere: "Pending Update: When site `#1234` is connected, update user `#4567's` display name to xyz. This update was queued at 2000-01-01 01:01:01Z".
* When an atomic site is reconnected, look through that log of pending updates, apply them to the atomic site, then delete the pending update entries.

A second, simpler idea:
* Whenever an atomic site is reconnected to WPCOM, copy the WP.com display name over to the atomic site.

However, I'm not really certain about these being good solutions. Probably @cpapazoglou or @mmtr would have more insight into this since they're more familiar with the issue. Any ideas?

**Comment by cpapazoglou** [comment]
Good recap @mreishus!

Generally the problem behind finding the best solution is "Does the user want this change to happen?". Updating the info on the background may not be in benefit of the user. What if we added a section in `wordpress.com/me` showing:

- disconnected sites and link to reconnect them
- out of sync info and a way to update them in the stale site

![SS 2021-11-22 at 14 43 25](https://user-images.githubusercontent.com/12430020/142863987-b7c5cecf-6374-4fe9-a928-91de3e1b7214.png)

This would be like a self-service experience.

**Comment by sguzovskaia** [comment]
Another case reported here: 33015696-HC
On Atomic site, updating Display Name in wordpress.com/me is not changing the admin name in Users and View posts by user.

**Comment by kuropixel** [comment]
Another case reported: 33962863-hc

CLI showing a different display name than what we're seeing on WPcom profile. There's also no way to change it from Users page in Classic view.

**Comment by arinoch** [comment]
Another case in 4744578-zd-woothemes. I changed the display name in CLI.

**Comment by i11za** [comment]
Another report here 34110908-hc and follow up via 4765222-zen
Changed the display name in CLI.

**Comment by ktyfuller604** [comment]
Had a report similar to this (bio was not updating). Same fix in CLI resolved the issue. 

4789640-zen

**Comment by wpshellbelle** [comment]
Another report at 35224064-hc

**Comment by kuropixel** [comment]
Another report at 35515594-hc (Bio and not display name) Changed bio via CLI

**Comment by Nic-Sevic** [comment]
Another related issue here: https://github.com/Automattic/wp-calypso/issues/56574
And another case here: p9F6qB-9SM-p2

**Comment by sejas** [comment]
Hi, I'm working on this issue.

My current plan consists in adding an async job in the WPcom API when jetpack `authorize` successfully an atomic site. `class.wpcom-json-api-jetpack-blog-endpoint.php:360`

DIFF in progress: D89202-code

**Comment by sejas** [comment]
The diff is ready for review D89202-code I would appreciate any feedback on it.

**Comment by sejas** [comment]
I've deployed the change r254523-wpcom . 
The diff updates the user_meta when an atomic site connects to WPcom.
The user_meta could change while the site was disconnected.
I assumed it was safe to update the user_meta because that behavior would also happen if the user updated his user_meta from calypso and the site was connected.
