### ISSUE TITLE
Facebook Embed for Facebook post links with vertical videos are not responsive in mobile

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#55187]
### Steps to Reproduce

1. Go to a Facebook page and find the post URL and video URL for a vertical / portrait video. 
For example, FB Post URL: https://www.facebook.com/bbcnews/posts/10158942255397217 
FB Video URL: https://www.facebook.com/bbcnews/videos/1728479674027688
2. Add a new page / post in an Atomic or Simple site with any theme and embed the above links.
3. You will observe that the Facebook embed with posts link is not responsive.

Screen recording: 

https://user-images.githubusercontent.com/33957570/128316876-872c0fe0-bd20-4960-9592-cb29a7966ac2.mov

### What I expected to happen

The Facebook embed using posts link should be responsive.

### What actually happened

The Facebook embed using posts link was not responsive.

### Context

User interaction: 4199625-zen

### Operating System

Windows, macOS, Linux

### Browser

Chrome/Chromium

### Browser Version

Chrome Beta 93.0.4577.15

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple, Atomic or both?

Simple, Atomic

### Console and/or error logs

NA

### Level of impact

High

### Reproducibility

Consistent

### Other information

As a workaround, I suggested the following solutions:

* Use the Facebook videos link if the post contains vertical video.
* Use the following CSS fix:

```
/* Facebook embed overflow fix mobile | 4199625-HC NJ */

@media only screen and (max-width: 768px){
.fb_iframe_widget iframe, .fb_iframe_widget_fluid span {
max-width: 350px !important;
    margin: 0;
    max-height: 623px !important;
}
}
```

**Comment by kosiew** [comment]
Hi @devNigel ,

Thanks for reporting this and the detailed steps.


I managed to reproduce this and your CSS fix works too.

Triaging for developers' further action.

**Comment by kosiew** [comment]
similar to previous stale issue https://github.com/Automattic/wp-calypso/issues/37469

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
There's a hardcoded width of `$width = 552;` under `jetpack_facebook_embed_handler` (it was decided back in 2017) which caused FB post embed to have a fixed width of 552.

Needs to be reviewed whether this can be safely removed.

**Comment by arcangelini** [comment]
I have attempted removing the hardcoded `$width = 552;` for posts but this did not help the issue. Based on [Facebooks developer guide](https://developers.facebook.com/docs/plugins/embedded-posts/) the lack of a `data-width` element should cause it to be fluid however, that is not the case.

If you add `!important` to the CSS this fixes the issue. SInce the SPAN that is setting the width is something returned by the Facebook plugin we may need to dig a little deeper to see how we can overwrite this.

I will keep digging.

**Comment by arcangelini** [comment]
### Explanation
We use the [Facebook plugin](https://developers.facebook.com/docs/plugins/embedded-posts/) to embed posts, pages, and videos. This involves creating a `div` element with the criteria ie. URL, attributes, and styling then running the Facebook plugin that replaces it with an `iframe` within a `span`.

### The dilemma
When someone adds the URL of what they want to embed we examine the URL and determine what type of content it is, either a post, page, comment, etc. and format our `div` accordingly. This determines how Facebook embeds the content. In the event that someone gives us a URL for a **POST** like this ⇢ `https://www.facebook.com/bbcnews/posts/1728479674027688` that includes a **VIDEO** Facebook returns the coding for a **POST** rather than a video. This means that the fluid width is not taken into account and is hardcoded to be 552px wide.

### The solution
Me and @yansern sifted through the differences between a post, video, and video within a post embed and there is no way to determine if the content being returned is a video within a post. This means there is no way to recognize that it has gone wrong and make changes to fix it. Because this is a very specific situation (video within a post) and there is not a feasible solution, this is not something we are going to fix.

The best way to fix this is to ask the user to get the **VIDEO** URL rather than the **POST** URL and replace the URL in the embed block.

*Video*
`https://www.facebook.com/watch/?v=1728479674027688`

*Post*
`https://www.facebook.com/bbcnews/posts/1728479674027688`

A bandaid CSS could also be:

```
/* Facebook Embed Width */
.fb_iframe_widget_fluid span {
    width: 100% !important;
}
```

But given the nature of `!important` it should probably be avoided and instead you should use the correct URL based on the content you are displaying.

**Comment by yansern** [comment]
@arcangelini Well explained!
