### ISSUE TITLE
NUX: Back button is inconsistent

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#5532]
#### Steps to reproduce
1. Starting at URL: wordpress.com/start
2. Select and add a custom domain
3. On the google apps step, hit the bottom back link
4. I see the plans selection page

#### What I expected

To go back to the previous step, which in this case was the domain selection page.

#### What happened instead

I saw the plans selection page, which I had not seen before.

#### Browser / OS version

Chrome latest OS X

/cc @fabianapsimoes @meremagee

**Comment by fabianapsimoes** [comment]
@scruffian I remember we discussed Back button behavior a lot when we were working on signup. Do you remember what were the constraints we faced? I believe the issue was broader than a single step.

Also cc @wensco as this related to the Domains step.

**Comment by scruffian** [comment]
I can't replicate this.

A "Back" button can mean different things in different contexts and they quickly become very complex in signup. We have:

1. Back to the previous section of the current step (so back from GAPPS to domain selection, or back from /plans/compare to /plans for example).
2. Back to the previous step (so if you're on GAPPS, back would mean go to the theme step)
3. Back to where I was before. (This can mean any number of different things, given that users can be redirected to steps in the flow when there are errors).

IMO the behaviour should always be number 3 - back buttons should be the same as the browser back button. However this change would not be restricted to signup - it would also have an impact all over Calypso, where we use the "Back" button in the `HeaderCake` component to do different things in different contexts. If we want to make a change like this we'll need to consider the impact across the board...

**Comment by alisterscott** [comment]
> I can't replicate this.

@scruffian: the behaviour is a little confusing at present since there's two back buttons on this page, and this bug only relates to the **bottom** back button.

At present, the top back button does the same as the browser back button, that is your number 3.

The bottom back button does what your number 2 suggests, and my understanding of this bug is to make is behave the same as the other back button (and the browser back button).

I recorded a screen video of the behaviour of the two back buttons and browser back button on this step:

![nux back](https://cloud.githubusercontent.com/assets/128826/16031383/d1cb0e84-323d-11e6-9a2f-9403a4f6ff47.gif)

**Comment by klimeryk** [comment]
I've stumbled upon this bug in https://github.com/Automattic/wp-calypso/pull/6075#issuecomment-227920709 and can verify it's still there (as well as some wonkiness when it comes to redirects - please see the comment and @umurkontaci's findings in https://github.com/Automattic/wp-calypso/pull/6075#issuecomment-228938081).
