### ISSUE TITLE
[Simple Site Block Widgets] Edit buttons on live site editor in customizer do not take you to the widget/widget menu

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#55365]
### Steps to Reproduce

1. Create/access a simple site. 
2. Open up My Sites → Appearance → Customize
3. On the live site editor, click on the round blue edit button for any existing widget.
4. The edit icon will not take you anywhere.

All other edit buttons work, so this looks to be due to the recent Simple Site Block Widget update. 

See GIF for example:
https://d.pr/i/DLiqZG

### What I expected to happen

Clicking on the blue edit button on the live site editor while in the customizer should take you to the specific widget edit options in the left-hand menu, like all other edit buttons do. 

### What actually happened

The edit button does not take you anywhere. 

### Context

User Report: WP1 user only accessed widgets via the blue edit icon (did not know how to via menu). Could replicate the bug.

zen-4213591
hc-31070230

Other HE could replicate the bug. Slack-p1628664261059200

### Operating System

Windows, macOS, Linux

### OS Version

11.5.1

### Browser

Chrome/Chromium

### Is this specific to applied theme? If so, what is the theme name?

Multiple themes seem to be affected 

### Simple, Atomic or both?

Simple

### Console and/or error logs

None

### Number of Users Impacted

All users

### Available Workarounds

Use the left-hand menu to access the widgets.

### Reproducibility

Consistent

**Comment by yansern** [comment]
After some digging, it appears that the old [customize-direct-manipulation](https://github.com/Automattic/customize-direct-manipulation) plugin is interfering with the customizer on Gutenberg core.

I have tested preventing the old customize-direct-manipulation scripts from loading on my sandbox and the customizer on WPCOM still continue to work just fine. And on top of that, it resolves the problem reported in this issue.

I do not know if this is the right move but, unless there is something that still relies on this 4-5 year plugin that I don't know about, I think it is very likely that the customize-direct-manipulation plugin can be safely removed on WPCOM [since this functionality is now provided by core](https://github.com/Automattic/customize-direct-manipulation/issues/52).

Phab patch to remove the plugin here. D65402-code

cc @draganescu @noisysocks pinging you both as I see that you both participated in https://github.com/WordPress/gutenberg/issues/24687 and https://github.com/WordPress/gutenberg/issues/33242.

**Comment by ccwalburn** [comment]
Another report here: 4212068-zen

**Comment by pauljacobson** [comment]
Another report here: 1459030-hc (follow-up in 4216613-zen). 

- The site uses Twenty Sixteen. 
- I was able to reproduce this issue using Firefox Developer Edition v92.0b2 on macOS 11.5.1
- Console logs: 29f98-pb/

**Comment by yansern** [comment]
D65402-code deployed.

**Comment by roo2** [comment]
One thing that customizer-direct-manipulation was responsible for, was applying the `customizer_direct_manipulation_steps` filter that `wpcom's customizer-extra-guides.php` (2a061-pb) uses to add custom help guides to the customizer. ( currently we have custom code for connecting social media and adding menus ).

I think that probably it's ok if those custom guides aren't shown for a while but we should make an effort to get the `customizer_direct_manipulation_steps` filter added into core so that we can get our custom tours working again

cc @yansern

**Comment by roo2** [comment]
Actually it looks like the default customizer guide is broken too.

**Comment by autumnfjeld** [comment]
@yansern  What about exploring WHY that plugin was causing the problem?  The removal of the plugin means the customizer guides are gone.

**Comment by Greatdane** [comment]
By customizer guide, do we mean the little blue edit pencils? Because they are now missing for the widgets. 

This is causing some confusion for users, especially non-advanced. I believe many users accessed the widgets by clicking the blue edit pencils, and some do not know how to edit widgets otherwise. 
see: 4238136-zd-woothemes.

**Comment by chriskmnds** [comment]
Reopened as reintroduced by reverting D65402-code in D65686-code. Discussion in Slack thread p1629346556037700-slack-C0KDTA48Y

**Comment by draganescu** [comment]
> Actually it looks like the default customizer guide is broken too.

Testing this with core WordPress and the pencil icons work, taking the user to the widget area > block selected UI state.

**Comment by jordesign** [comment]
Thanks @draganescu. Confirming in HE Triage that I can recreate this. Confirming it is only on Simple Sites (not Atomic).

Ideal solution would be to *keep* the blue pencil/edit icons but have them once again behave as expected.

**Comment by mikeicode** [comment]
Simple site Photography theme 4254576-zd-woothemes

**Comment by DavidSaladu** [comment]
Reproduced as well in 4255598-zd-woothemes
I reproduced the bug as well on this conditions:
- The site uses Twenty-Twelve
- Google Chrome Version 92.0.4515.159 (Official Build) (x86_64) on macOS 11.3.1

**Comment by KirkwallDay** [comment]
Another instance here: 6475965-Hc

**Comment by hacchism** [comment]
Another report: 31387545-hc
Simple site with Sela theme.

**Comment by cuemarie** [comment]
Another report here: 4261519-zd-woothemes
Simple Site; Retired Theme - Bueno

**Comment by tellisbethel** [comment]
Another instance here: 4277633-zd-woothemes
Simple site, Gateway theme

**Comment by masperber** [comment]
Another instance here: 4283073-zen
Simple site, Sela theme

**Comment by yansern** [comment]
Delegated to @Automattic/pod-happiness-gardeners. p1629346556037700-slack-C0KDTA48Y

**Comment by chriskmnds** [comment]
> Delegated to @Automattic/pod-happiness-gardeners. p1629346556037700-slack-C0KDTA48Y

I am not sure that was the conclusion from the discussion there @yansern . From my understanding, this is back in flow patrol's area of responsibility. We took the necessary intervention to revert a deployment that broke functionality (user guides) critical and relevant to what the pod is working on (helping/guiding users), along with header/nav edit buttons in a number of themes (potentially as critical as this issue refers to). 

As you have already done a fair bit of exploration on this, I feel it's only reasonable that you continue on that path and persevere with this a little further. Just please make sure to not deploy or introduce plugins that have not been thoroughly tested (especially in this case, deprecating a plugin 5-6 years in use - a CFT should have preceded the changes IMO). Would you be willing to write up a post mortem to put some context on what broke, what the action was to resolve, what the path looks forward (things discussed in the thread you linked to)? The division can then decide what pod is best suited to address holistically IMO.

**Comment by simison** [comment]
Let's have this on Flow patrol's todo @yansern @alshakero @chriskmnds . 👍

**Comment by yansern** [comment]
Thanks @chriskmnds! Sorry to have tagged you guys earlier (as I was reorganizing our project boards and just wanted to make sure there was a follow-up).

> As you have already done a fair bit of exploration on this, I feel it's only reasonable that you continue on that path and persevere with this a little further. 

Fixing this will require time & effort which at this point I don't have the luxury of at the moment. But I agree that since I've investigated this quite deeply, I should move this forward when I'm able to. Need more devs.

> Would you be willing to write up a post mortem to put some context on what broke, what the action was to resolve, what the path looks forward (things discussed in the thread you linked to)?

Post-mortem, not really, as the situation was either this broke, or that broke. Currently, we're still in the broken stage. But, drafting up a plan on how to move forward, yes.

**Comment by yansern** [comment]
Moved this issue to "Can't Fix Quickly" column.

**Comment by chriskmnds** [comment]
> Post-mortem, not really, as the situation was either this broke, or that broke. Currently, we're still in the broken stage. But, drafting up a plan on how to move forward, yes.

Yes, that's what I meant. Put everything in context so whoever owns this has a point of reference. what happened, what we tried, what to watch out for/ lessons learned, what's the way forward. I believe you did a great job/investigation, so it makes sense to compile everything in a nice P2 post at least for a start (doesn't mean you will end up fixing this).

> Fixing this will require time & effort which at this point I don't have the luxury of at the moment. But I agree that since I've investigated this quite deeply, I should move this forward when I'm able to. Need more devs.

I hear you. You have a wide area of responsibility. At the same time, we've been narrowing the scope of gardeners and already looking at things to wrap up and hand over to the next rotation. None of that is bugs in the editor right now - they are help center explorations, welcome tour, user guidance, help links/popovers, etc. Razvan is part-time lead, I am part-time hiring too. Who doesn't need more devs? However, if it means pulling someone from anywhere to work on this as a supercritical bug (and it does seem critical), then obviously things can be re-prioritized. I believe this needs to be decided with efficiency & relevance in mind, and you are definitely the most efficient/relevant person/pod here (other priorities/focuses aside) 🤷‍♂️

**Comment by rw-ye** [comment]
4289251-zd-woothemes
Simple Site
Theme: Karuna

They can't do it through Safari(14.1 with macOS Catalina installed) but it works on Edge.

**Comment by chriskmnds** [comment]
Looking into this. 

Apologies that this was left unattended for what looks like 3 weeks now. Hopefully there's an easy fix somewhere that won't introduce breakage elsewhere. 🙏

**Comment by chriskmnds** [comment]
Looks like we haven't had any more reports here, so we can close as fixed in https://github.com/Automattic/customize-direct-manipulation/pull/53. 🙏  A follow-up outlined in https://github.com/Automattic/customize-direct-manipulation/issues/54
