### ISSUE TITLE
Theme Showcase: Live demo opens externally on Atomic sites

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55497]
### Steps to Reproduce

1. Go to WordPress.com > My Sites > Appearance
2. Click `...` on one of the themes and then on `Live demo`

### What I expected to happen

The Live demo should open in a modal and stay that way.

### What actually happened

The Live demo opens briefly in a modal, but then redirects and opens in a new tab.

### Context

Observed during a Quick Start session 4218872-zd-woothemes

### Operating System

macOS

### OS Version

BigSur 11.4

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

Any theme except for the currently active one on the site. So far tested with Storefront, Blank Canvas, Twenty Twenty-One.

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Reproducibility

Consistent

### Other information

https://user-images.githubusercontent.com/39308239/129333437-2f68b763-49d1-436c-b0a4-86d4871d4609.mov

**Comment by synora** [comment]
There must have been a glitch in the matrix (j/k). I tried this out with a few themes and I'm unable to replicate this issue. 


https://user-images.githubusercontent.com/10015451/129749576-82337f08-6cd6-40ce-ad07-86547ed8689a.mp4

I'm closing the issue for now but it can be reopened if there are further reports.

**Comment by zdenys** [comment]
I actually reproduced it today once again during a Quick Start session with a customer. I can see you are trying under `All Themes` section, not the `Recommended` one.

I can reproduce 100% of the time.

- I use Chrome 92
- On AT site I navigate to Appearance > Themes (and by default, I am in the `Recommended` tab)
- I have Storefront theme active
- I click three-dots on theme Twenty Twenty and can see how the Live demo shortly opens in the modal but then quickly redirects to `https://wp-themes.com/twentytwenty/?demo=true&iframe=true&theme_preview=true`


https://user-images.githubusercontent.com/39308239/129751592-fe53d9e5-f8b7-45d6-a4c2-46cd0e880f08.mov

I can even reproduce the same in macOS WordPress Desktop App 7.1. See this video:

https://user-images.githubusercontent.com/39308239/129752226-c5d2b007-ad8c-4c65-aebc-80254406a66c.mov

Can you try the same steps and let me know what you find, @synora?

**Comment by synora** [comment]
Wow! Thanks for the updated steps. I can replicate this exactly when Storefront is active on my AT site. I can't replicate this with Perennial or Twenty-Twenty as active themes though. Keeping the issue open.

**Comment by sixhours** [comment]
I have a hunch this has to do with not being able to display external domain names (like wp-themes.com) within an iframe from a custom domain.

That seems to be the case on my *.blog site, but not on *.wpcomstaging.com. It also happens for themes that we technically host (like Illustratr -- illustratrdemo.wordpress.com) because the Showcase is looking at the WP.org showcase for a demo site first.

But there's also some weirdness with broken demo links that never work at all, the API is throwing 404s:

<img width="1539" alt="Screen Shot 2021-08-31 at 12 02 16 PM" src="https://user-images.githubusercontent.com/2124984/131536986-3fd11e52-3be3-4ad0-bd65-3c15ee2e4bcd.png">

I'll keep digging.

**Comment by sixhours** [comment]
Yeah, there's likely something about some demo links that can't be previewed in the iFrame due to limitations of `WebPreview`:
https://github.com/Automattic/wp-calypso/blob/trunk/client/components/web-preview/README.md

But we should look at two things:

* Why is the API throwing 404s for some themes?
* Why are we looking to WP.org for demo sites when we have demo sites for many of these themes already?

**Comment by sixhours** [comment]
Here's where I'm at so far:

* At the time the Theme Showcase first loads, `getCanonicalTheme` returns an `undefined` source for those themes with broken demo site links, which causes `getTheme` to return `null`, and therefore breaks selectors like `getThemeDemoUrl`: https://github.com/Automattic/wp-calypso/blob/trunk/client/state/themes/selectors/get-canonical-theme.js
* This happens with themes that are only available on WordPress.com and have not been added to the WordPress.org repository. I've been testing against Rivington as an example of one such theme.
* When you visit a context that does load the theme's data into state, functions for that theme start working again. For example, if you click on Rivington's screenshot to go to the single theme view, the data is loaded, and returning to the Showcase allows you to open the correct demo site.
* I suspect this was broken during our work on the Theme Showcase during the Design Selection pod and we just never realized it, because there are many different variables to test against. It seems like something we should be able to add tests for, though. 🤔 

I'm going back through commits to see if one of them broke the behavior for Atomic sites. Failing finding the culprit, we need to find a way to properly load theme data into state regardless of the environment (Simple vs. Atomic).

This smells a little bit like this issue I found when we were working on the Showcase, with non-paginated queries not loading theme data into state past a certain number: https://github.com/Automattic/wp-calypso/pull/54648

**Comment by sixhours** [comment]
I did find a revision of Calypso that did *not* have this behavior going back a few months 05c2d14 so I'm running a git bisect to see if I can track down the culprit.

**Comment by sixhours** [comment]
The breaking commit happened in this PR, when Design Selection made a big update to the Showcase: #54361

**Comment by sixhours** [comment]
This has been fixed in #55910!
