### ISSUE TITLE
Welcome tour: top buttons are not always visible on mobile

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#55587]
### Steps to reproduce the behavior

1. Open the website on a mobile browser. I've checked this with Chrome browser.
2. Open WordPress.com > My Sites > Pages > Add New Page (and select blank layout) or a Post.
3. Click on the three dots on top-right corner and open **Welcome guide**.
4. You'll see the welcome guide is shown with the following behavior:
  * the top buttons are showing up briefly on a new slide and then they disappear
  * once you press somewhere on the slide, the buttons appear again and continue to be visible

#### What I expected to happen
Top buttons to be always visible on mobile, similar to how they are on desktop

### Context
The [close button not showing on mobile](https://github.com/Automattic/wp-calypso/issues/54426) was recently fixed in https://github.com/Automattic/wp-calypso/pull/55131

#### Browser / OS version
Tested in Chrome

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://user-images.githubusercontent.com/14192054/129916048-ce1688e5-039a-4371-b2bd-e9e8ee88e4ee.mov

**Comment by amustaque97** [comment]
Hi, I will be working on it. Perhaps by tomorrow, I will raise a PR addressing this issue fix.

Thank You

**Comment by chriskmnds** [comment]
I do notice a bug of sorts with what we have right now, and fixing it would address the behavior we are seeing with the buttons disappearing when changing views. The problem is, we don't yet know what the mobile version will look like exactly, so focusing on these overlay buttons right now as part of the mobile view feels disconnected. I'll prep a PR irrespective, but going to close this issue in favor of #52280. 

Relevant discussion in Slack thread p1629899413074600-slack-C029WSAQMT9.
