### ISSUE TITLE
Audio player in Marquee not appearing on Simple Sites with static home page

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#55708]
### Steps to Reproduce

1. Change theme to Marquee in simple site (tested in Premium)
2. Add audio to theme options "Player Attachment IDs"
3. Set homepage to static
4. Open site and you'll see that the audio player is not functional - track list icon shows but does not function, cannot play music
5. Switch back to "latest posts" and audio appears

### What I expected to happen

Audio should show on home page regardless of if page is set to latest posts or static.

### What actually happened

When set to static, audio does not function properly.

### Context

First reported here: 4238829-zd-woothemes
Tested on my own site and got the same results: d8ZOo-p2

### Operating System

macOS

### Browser

Chrome/Chromium, Firefox, Microsoft Edge, Safari

### Is this specific to applied theme? If so, what is the theme name?

Marquee

### Simple/Atomic

Simple

### Available Workarounds

No known workarounds aside from setting home page to latest posts which is not really an option for a lot of users.

### Reproducibility

Consistent

**Comment by jordesign** [comment]
Triaging this issue - I was able to get the audio player working in both Atomic and Simple sites, on both Static Front Page and also Latest Posts on front page.

@ClassicRKR27 Are you able to let me know the URL of your test site so I can test and observe the issue in place?

**Comment by Greatdane** [comment]
I actually think this is related to `MediaElement.js` not always working properly on the front page. 

See: p2EDhh-1ki-p2 / 4250668-zd-woothemes for the same issue. 

Both sites have the same error message in console;
<img width="1067" alt="Markup 2021-08-27 at 16 15 33" src="https://user-images.githubusercontent.com/5075840/131095850-ce3a6b37-ca07-4728-884b-f3aa320c1b8a.png">

This is a video file rather than a music file. 

I am unable to replicate the issue (both sites using old editor?)

**Comment by inaikem** [comment]
Appears dependent on the linked issue above. Marking as triaged for the moment.

**Comment by sixhours** [comment]
This may be related to #55696 as Robert mentions in that thread.

**Comment by mreishus** [comment]
In #55696, a fix was applied (https://github.com/Automattic/jetpack/pull/21004) for `Uncaught TypeError: Cannot set property 'mejs' of undefined` errors, which may also apply here. The fix is already on simple sites, and should be moving to Atomic shortly.

I'm having difficulty testing to see if the issue is resolved. Recently, we removed premium themes, so I'm not able to change my site to Marquee. I tried looking at the site mentioned in 4238829-zd-woothemes, but I don't see any audio players on the front page. For the site mentioned in 4250668-zd-woothemes, the author moved to youtube blocks as a workaround. I do not have access to d8ZOo-p2. @ClassicRKR27, can you let me know if this is still an issue on the site you recreated it on?

**Comment by sixhours** [comment]
This appears to be working for me on a test site now that the fix in https://github.com/Automattic/jetpack/pull/21004 has been deployed. It should also be fixed on Atomic per @jeherve's comment 6947-gh-Automattic/jpop-issues#issuecomment-922817812

I'm closing this out!
