### ISSUE TITLE
Like Button: Clicking Like button and then the Follow button resets the state of the Like button until refresh

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55745]
### Steps to Reproduce

1. Click Like button on a post or page
2. Click Follow button

https://user-images.githubusercontent.com/39308239/130925938-70354365-5336-47cd-84fd-49cdb0a4c0eb.mov

### What I expected to happen

See the Like button preserve its state

### What actually happened

The Like button changes its apparent state to unclicked, until you refresh the page.

### Context

This reports comes as the result of manual testing on Simple Sites and P2s

### Operating System

macOS

### OS Version

BigSur 11.5.2

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Simple

### Number of Users Impacted

Most users (>50%)

### Available Workarounds

Refresh the page to see the actual state of the Like button

### Reproducibility

Consistent

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
The follow button seems to be only testable on sites running P2 theme.
When the follow button is clicked, it triggers a change event, causing the post content to rerender.

In order to debug this, set a breakpoint on `renderPost: function () {`. (Source file: `wp-content/plugins/p2tenberg/p2/js/post.js`) so you can see the entire trace of how clicking on follow button causes the post to rerender.

The way I see this can be fixed is to prevent the `change` event from being triggered (but I see the `silent: true` option is already set, so why is the `change` event still being triggered?). (Source file: `wp-content/plugins/o2/modules/follow/js/views/post.js`).

![image](https://user-images.githubusercontent.com/1287077/132499973-05c4a610-9154-4af4-8f83-4583ebdd691e.png)

**Comment by alshakero** [comment]
Fix is ready in D66665-code

**Comment by alshakero** [comment]
Closing as fix is in production now. Many thanks to @naxoc for deploying the P2 part.
