### ISSUE TITLE
Categories widget sorts Swedish characters in an incorrect alphabetical order

### ISSUE THREAD

**Issue by LauraSWP** [Automattic/wp-calypso#55755]
### Steps to Reproduce

1.In My site → Settings set the site´s interface to Swedish.
2.Create post Categories or Tags with Swedish special characters ( Å, Ä, O ) My Site → Posts → Categories/Tags.
3.The titles are placed next to other titles that start with A or O normal characters instead of being at the end.
4.Navigate to Customizer and add Categories widget. Tick the box to Show as a dropdown.
5. Special characters are also sorted next to A and O letters. 

### What I expected to happen

From the request: _I would expect the Categories widget dropdown menu and Post titles in United Navigation/Classic view to be sorted in correct alphabetical order. Link to check Swedish alphabet: https://en.wikipedia.org/wiki/Swedish_alphabet_

### What actually happened

From the request: _Words that start with Swedish special characters are placed next to words that start with A and O characters._

Blog posts are not ordered in the correct alphabetical order.

### Context

HC Request: short-link /pd4QKa-eq
Related interaction 4249728-zen

![image](https://user-images.githubusercontent.com/63611065/130967591-03147d90-1786-40a9-805f-118ea966301a.png)
Categories widget
![image](https://user-images.githubusercontent.com/63611065/130967647-7a1a7952-7339-4706-8427-3171b9454f99.png)
Post sorted by title in Classic view displays post in correct alphabetical order

### Operating System

Windows, macOS

### OS Version

10 64bit

### Browser

Chrome/Chromium, Firefox

### Browser Version(s)

Firefox 91.0.2 (64-bit) Google Chrome: Version 92.0.4515.159

### Simple/Atomic

Simple

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

From the request: _To display post categories in correct alphabetical order on a page/post one can build a Custom Menu then add a Navigation Block._

I didn't find any workaround for post titles on the blog.

**Comment by formosattic** [comment]
This is due to the WordPress.com databases using Latin1 ([see ref.](https://wordpress.com/support/incompatible-plugins/#my-plugin-says-the-database-doesnt-support-a-character-set-what-do-i-do)) character set, so that default setting can't be changed.

That said, it's possible to convert character set it if the site is on a Business plan.
The fix would require the character encoding of the database to be converted to one that'll work for Swedish, such as `utf8mb4_swedish_ci` ([see ref.](https://wordpress.org/support/topic/wrong-order-with-utf-8-swedish-characters/#post-10348656)), `utf8_swedish_ci` ([see ref.](pNHAH-3x-p2_title-for-international-characters/)), possibly `latin1_swedish_ci`.

More details about **Converting Database Character Sets** at https://codex.wordpress.org/Converting_Database_Character_Sets.

Thanks for the report @LauraSWP. Will close.
