### ISSUE TITLE
Reader: Gallery code showing in Reader preview when thumbnail grid gallery is used.

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#5576]
#### Steps to reproduce
1. Create a new post at https://wordpress.com/post
2. Add an image gallery with two or more images.
3. Select the Thumbnail Grid layout and insert the gallery into the post (other settings don't appear to matter)
4. Make sure you are following the site and view the post in the Reader

#### What I expected
If no featured image or other images are present in the post, the preview should show the first gallery image, with small gallery thumbnails below the post title.

#### What happened instead
The first gallery image is shown in the preview, but some CSS code for the gallery is shown after the post title and before the small thumbnails.

#### Screenshot / Video
![kokkiestrialtestsite_ _reader_ _wordpress_com](https://cloud.githubusercontent.com/assets/11873759/15544301/73b2d0de-2298-11e6-9974-0215db687e53.png)

Reported in 734647-f

**Comment by stephdau** [comment]
+1

<img width="746" alt="screen shot 2016-05-31 at 9 35 22 am" src="https://cloud.githubusercontent.com/assets/1891/15676159/2e5c5cd8-2713-11e6-815d-e1128f780aa8.png">

**Comment by pellyma** [comment]
Hi kokkieh,
I really need your attention to the bug problem because it's getting worse and is affecting the way my blog appears in the Reader now in total. Please look at the forum thread I had opened so you could understand what's wrong: https://en.forums.wordpress.com/topic/hidden-text-appears-in-my-post-reader?replies=18#post-2650934
This is what I see now in my Reader when I click on pelly*made:
https://pellymade.files.wordpress.com/2016/06/messed_up2016-06-01.jpg
I really need a solution asap, as I cannot post anything new...
Thanks

**Comment by blowery** [comment]
Thanks for the report @KokkieH and @stephdau. Fixed in prod now.
