### ISSUE TITLE
Tabs to Spaces

### ISSUE THREAD

**Issue by damassi** [Automattic/wp-calypso#558]
Browsing the code, i'm noticing that you're using tabs instead of spaces, which blows out code viewing unnecessarily into *8 spaces* for every tab:

<img width="941" alt="screen shot 2015-11-23 at 11 53 30 am" src="https://cloud.githubusercontent.com/assets/236943/11348049/15826ad8-91d9-11e5-84b9-8ad74c627ee6.png">

Idiomatic JS is typically 2 soft spaces, which significantly cuts down on read time across a codebase, while also making contributions easier since people can read the code at a glance.

**Comment by aduth** [comment]
You can add a `?ts=4` parameter to reduce the spacing while previewing on GitHub. GitHub has [begun to incorporate some `.editorconfig` features](https://twitter.com/editorconfig/status/610836234676535296), so we could choose to assign a [`tab_width` parameter](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#tab_width) in our configuration, though this would likely take precedence over a developer's editor settings if an EditorConfig plugin is in use.

**Comment by rralian** [comment]
It's a bit of a WordPress legacy to prefer tabs over spaces. https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#spacing

And that's been picked up in this project (everyone came from WordPress after all). https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#spacing

I agree though, seems like the consensus in the javascript community is to prefer two-spaces for indentation instead of tabs. I think it would be a good idea for us to align with that (even if I always did prefer tabs).

**Comment by damassi** [comment]
As a previous 4-spacer, 2 really grows you after a bit of time. But yeah, since you're moving over to JS on such a large scale using React and so on, it would be best to align sooner rather than later : ) Aside from that, great work.

**Comment by nb** [comment]
Thanks, @damassi!
