### ISSUE TITLE
Domain Picker: broken UI for HSTS notice popover

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#55860]
### Steps to reproduce the behavior

1. Go to [wordpress.com/new](https://wordpress.com/new)
2. Click on _Choose a domain_ button in the header
3. Search for "mysite.page"
4. Click on the Info icon next to the domain suggestion

#### What I expected to happen
To be able to read the HSTS notice when clicking the Info icon

#### What actually happened
The popover is rendered with a very small width so the content is unreadable

### Context
This info tooltip has been added in https://github.com/Automattic/wp-calypso/pull/45490

#### Browser / OS version
Chrome / MacOS

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
<img width="1080" alt="Screenshot 2021-08-31 at 12 14 16" src="https://user-images.githubusercontent.com/14192054/131477744-9ba6135a-79b8-4991-8c5c-3d50da1c819b.png">

**Comment by c3ho** [comment]
Hi @razvanpapadopol I'm kind of new to UI/UX and was wondering if this is alright?

Desktop:
![image](https://user-images.githubusercontent.com/18711727/137057671-5125e5be-c75a-41ef-a0fe-535e7f6a3580.png)

Mobile:
![image](https://user-images.githubusercontent.com/18711727/137057619-d100cccd-1cd4-4eb0-bd29-ce3a407c39b5.png)

I added a property `word-break: keep-all` otherwise some words were breaking at awkward places with a set width of `232px`
