### ISSUE TITLE
Marketplace: Update plugins upsell nudges to better reflect when / if users need to upgrade to a paid plan

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#55917]
The plugins page has upsell to business banners when viewing the page from a non business plan.

These need updating to suggest upgrading to any paid plan.

Before
![Screenshot 2021-09-02 at 12-15-11 WooCommerce Plugin ‹ Woop Test 1 — WordPress com](https://user-images.githubusercontent.com/811776/131770513-9ad8428f-29f1-4830-95db-a8f13c2afb1e.png)

**Comment by lsl** [comment]
@cpapazoglou This is likely a marketplace pod task, was thinking the banner might trigger a transfer and ended up getting into the code before realising it wasn't what I was looking for.

Anyone can take this over if it helps https://github.com/Automattic/wp-calypso/pull/55918

**Comment by cpapazoglou** [comment]
> @cpapazoglou This is likely a marketplace pod task, was thinking the banner might trigger a transfer and ended up getting into the code before realising it wasn't what I was looking for.
> 
> Anyone can take this over if it helps #55918

Yeah, the banner say explicit what it does. It is just a CTA to buy the Business plan. You will need to visit this page again and install a plugin so that the AT transfer kicks off.

Rewording it is a little bit tricky:

**Marketplace V1**
- All plugins (extensions) we will offer require the woo plugin, so a Business or higher plan is required (at least until woo works on all plans)
- Installing any other plugin, will still require a Business plan

**Marketplace V2**
- All plugins (extensions) we will offer require the woo plugin, so a Business or higher plan is required (at least until woo works on all plans)
- We will offer the Yoast premium, which will be available for any plan (even the free plan).
- Installing any other plugin, will still require a Business plan

**Marketplace VX**
- All third party paid plugins we offer will be available on all plans.
- Installing a third party plugin we don't offer or a wp.org plugin, will still require a Business plan

**Comment by cpapazoglou** [comment]
**The task here is:**
When we offer paid plugins in all plans we will need to add a check and hide this nudge only for paid plugins.
