### ISSUE TITLE
Services block - Adding heading to second service item creates a new service item 

### ISSUE THREAD

**Issue by yashitamittal11** [Automattic/wp-calypso#56021]
### Steps to Reproduce

1. Add a Services block
2. Next, add the heading to both the service items
3. As soon as we start typing in the heading field of the second service item, it creates a new service item.

### What I expected to happen

Adding the heading for the second service item should not create a new service item.

### What actually happened

Adding the heading to the second service item creates a third service item placeholder block within that Services block.

### Context

I tested this issue on Redhill, Varia, and Twenty Twenty One. I see the same issue on all the themes.

https://user-images.githubusercontent.com/21078987/132185857-3b0fb975-6903-458d-8804-33dadedc699a.mov

### Operating System

macOS

### Browser

Chrome/Chromium

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Atomic

### Reproducibility

Consistent

**Comment by synora** [comment]
Triaged. Can replicate.

**Comment by jordesign** [comment]
Just double checking on this one - as I don't see an open issue from CoBlocks that this is being tracked in?

I also notice that 'Services' isn't one of the blocks we include on WPCOM on Simple Sites - so this issue is just with the plugin version of CoBlocks which *can* be installed on Atomic sites. I'm inclined to say we don't really need to track this?

But happy for a second opinion: @synora @inaikem

**Comment by Greatdane** [comment]
Going to close this.
