### ISSUE TITLE
Grey line in Gallery block

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#56064]
### Steps to Reproduce

1. The site has a gallery block with a large number of images - https://wordpress.com/page/twols.club/124
2. Within the editor but not in the public view there is a grey bar showing next to an image
![image](https://user-images.githubusercontent.com/6737345/133394235-82b550ed-9918-409e-be76-f4ad31201b12.png)

3. When I copied it to a test site, the bar still appears. The original theme is Stow. The effect appears again on Alves.
4. Change the column numbers or changing the image near the bar on any side doesn't remove it.
5. There doesn't appear to be anything in the page code to draw the bar either.

### What I expected to happen

No bar to appear

### What actually happened

A bar that you can't click appears in the interface

### Context

#4268858-zd

### Operating System

macOS

### Browser

Chrome/Chromium

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Reproducibility

Consistent

**Comment by Robertght** [comment]
I can confirm I've seen this with the current gallery, but not with the refactored one.  Is it safe to close this one cc @glendaviesnz ?

**Comment by glendaviesnz** [comment]
This is not a gallery issue. I am pretty sure this is related to the Jetpack publicize module and this is a separator related to the Twitter thread option. On trying to replicate in the Jetpack repo it seems to disappear after this move of the publicize module - https://github.com/Automattic/jetpack/pull/21016 - @retrofox may now if this was a known issue that was fixed by this move, or an unintentional side effect. 

In theory this issue should disappear when the next release of Jetpack is on WPcom, if not you should add an issue to the Jetpack repo for this and note that the Jetpack publicize module appears to be adding a tweet divider to the core gallery block even if the option to use publicize to publish a tweet thread has not been selected.

**Comment by retrofox** [comment]
> I am pretty sure this is related to the Jetpack publicize module and this is a separator related to the Twitter thread option. On trying to replicate in the Jetpack repo it seems to disappear after this move of the publicize module - [Automattic/jetpack#21016](https://github.com/Automattic/jetpack/pull/21016) -

First of all, why we are defining these [gallery styles in the publicize plugin](https://github.com/Automattic/jetpack/blob/c7adc871c064744a56a57583a5f210f46e60a5dc/projects/plugins/jetpack/extensions/plugins/publicize/components/twitter/editor.scss#L137-L141
)?

```scss
.annotation-text-jetpack-tweetstorm,
.jetpack-publicize-twitter__tweet-divider,
.block-editor-block-list__block li::after,
.blocks-gallery-grid .blocks-gallery-item:nth-child(5) figure::before {
	transition: opacity 0.5s;
	opacity: 1;
}
```

https://github.com/Automattic/jetpack/pull/21016 simply moved the location where the Publicize block-editor plugin was defined and registered, but we didn't change how and when it runs. Do you think this issue was really introduced in this PR, or there is a chance it was there before these changes?

> In theory this issue should disappear when the next release of Jetpack is on WPcom, if not you should add an issue to the Jetpack repo for this and note that the Jetpack publicize module appears to be adding a tweet divider to the core gallery block even if the option to use publicize to publish a tweet thread has not been selected.

Creating an issue would be nice. It seems to need some exploration and definitely some changes to fix the issue.

Thanks, @glendaviesnz for your ping 👍

**Comment by glendaviesnz** [comment]
> Do you think this issue was really introduced in this PR?

No, the issue was there before your PR - and I just checked again and it actually still occurs in trunk - not sure why it wasn't showing in trunk for me yesterday - so I don't think your PR has actually impacted it at all @retrofox. I have added an issue in jetpack repo for it https://github.com/Automattic/jetpack/issues/21121

**Comment by jeherve** [comment]
👍 Closing this issue in favor of the one in the Jetpack repo.
