### ISSUE TITLE
Block Editor Widgets: Red X on top of show/hide visibility setting

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#56184]
### Quick summary

On the new block editor widgets, the Red X sits on top of show/hide visibility settings.

### Steps to reproduce

1. Open Widgets section in the Customizer for a Personal plan site
2. Add a widget (I tried the Google Translate and Text widgets)
3. Click the Visibility button

### What you expected to happen

I expected to see the Show or Hide selection without a red X on top.
On my AT site it looks like this: 

![screenshot](https://d.pr/i/Nq1n35+)
Image URL: https://d.pr/i/Nq1n35

### What actually happened

The red X was on top of the Show / Hide selection like this:

![screenshot](https://d.pr/i/azYmFX+)
Image URL: https://d.pr/i/azYmFX

### Context

Customer report
4290805-zen

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
**Investigation Note:**

CSS fixes needs to be done for both `wp-admin/widgets.php` view and `wp-admin/customize.php` view.

The file to work with is `jetpack/modules/widget-visibility/widget-conditions/widget-conditions.css`.

**How it looks like on Standalone widgets editor:**
![image](https://user-images.githubusercontent.com/1287077/136242670-c19ac737-4de3-466c-a9ac-5a0e17d248b4.png)

**How it looks like on Customizer widgets editor:**
![image](https://user-images.githubusercontent.com/1287077/136242852-895452f9-c233-4b0c-9db6-3d06882af528.png)

I would slightly rework the UI to make it easier/usable.

When running under customizer, one can use the parent classname `.wp-customizer` to add CSS overrides for narrow viewport.

**Comment by yansern** [comment]
It appears that Block Settings have a nicer CSS layout. I think we just need to bring this over.

![image](https://user-images.githubusercontent.com/1287077/137718263-4594409b-a6d1-46d1-b3be-7bc83f13f4b4.png)

**Comment by ivan-ottinger** [comment]
Turns out that WPCOM overrides the Customizer styles in `customizer-fixes.css`. Since there are no styling issues on Jetpack sites, neither Atomic, we could override the styles solely on WPCOM - with a quick fix that would align the ❌ button to the right like this:

![Markup on 2021-10-21 at 17:54:34](https://user-images.githubusercontent.com/25105483/138313754-ac46f59d-2b52-43f9-b448-82a0086a46b3.png)

I think it looks nicer - as the ❌ button aligns with the ➕ sign horizontally.

Here is the patch we can use for that: D68839-code.

Then later we can consider how to better format the whole Visibility section - as Yan suggested in the [previous comment](https://github.com/Automattic/wp-calypso/issues/56184#issuecomment-945648098).

What do you think?

---

> How it looks like on Standalone widgets editor:
> ![](https://user-images.githubusercontent.com/1287077/136242670-c19ac737-4de3-466c-a9ac-5a0e17d248b4.png)

Hey @yansern, could you please share with me which browser (or maybe theme) you used when you saw that broken drop-down icon? I couldn't reproduce it. 🤔

**Comment by yansern** [comment]
> Hey @yansern, could you please share with me which browser (or maybe theme) you used when you saw that broken drop-down icon? I couldn't reproduce it. 🤔

I can no longer replicate this as well.

Seems like the `no-repeat` CSS is now added.

![image](https://user-images.githubusercontent.com/1287077/138667358-d4229a69-3dd0-4178-8b39-bee1cc1f3ddf.png)

**Comment by ivan-ottinger** [comment]
> I can no longer replicate this as well.
> Seems like the `no-repeat` CSS is now added.

Perfect!

**Comment by yansern** [comment]
> Here is the patch we can use for that: D68839-code.

Patch approved.

> Then later we can consider how to better format the whole Visibility section - as Yan suggested in the previous comment.
> What do you think?

Yeah, quick fix, then iterate. Would be nice if legacy and new block visibility settings look the same.

**Comment by ivan-ottinger** [comment]
Fix successfully deployed to WPCOM production. 🎉 

Users will now see the ❌ on the side:

![Markup on 2021-10-21 at 17:54:34](https://user-images.githubusercontent.com/25105483/138313754-ac46f59d-2b52-43f9-b448-82a0086a46b3.png)
