### ISSUE TITLE
Customizer: legacy widget previews are broken until focused on

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#56468]
Originally reported in p1632316642084400-slack-CBTN58FTJ

### Steps to reproduce the behavior

1. Go to Appearance > Customize
2. Click on the + to add a new block widget.
3.  Select Legacy Widget, and choose an available option
4. Configure any options your selected widget requires in order to render. Otherwise you'll get a "No preview available"
5. Once your widget is properly configured, click outside of it. Anywhere on the screen will do.
6. Once focus is lost, the widget become invisible apart from a small whitespace
7. Hovering will reveal a small outline of the widget (but not its full size)
8. Click on the outline and you widget will appear again
9. Publish changes, close and reopen Customizer
10. Preview is still broken for existing widgets (issue isn't just with newly added blocks)

#### What I expected to happen
Legacy widget previews should be visible when the Customize opens and the widget isn't currently selected for editing

#### What actually happened
You can only see legacy widgets when they're in focus

#### Browser / OS version
Chrome Version 93.0.4577.82
MacOS 11.5.2

#### Does this happen on simple or atomic sites or both?
WPCOM Simple Sites only

#### Is there any console output or error text?
Yes, see below.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Appears to impact all Simple sites, but doesn't block purchases or functionality apart from previewing the widgets in the Customizer

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
<img width="1246" alt="Screen Shot 2021-09-22 at 11 17 47" src="https://user-images.githubusercontent.com/13856531/134371979-fdc3736a-ee4b-40a4-8c09-1cba02b3abe5.png">

**Comment by chad1008** [comment]
Update to add:

I forgot to mention that I bisected this issue, and it appears to have been triggered by #34384, specifically https://github.com/WordPress/gutenberg/commit/521dbbb35e51914e0bea3fcd705f3345a8b9341e

**Comment by jp-imagines** [comment]
Just had a report of this in 4317138-zen. Showed the user how to find/edit their widgets while this is being worked on.

**Comment by radtechgh** [comment]
Another report in 4306852-zen

**Comment by dcoleonline** [comment]
another report in #4315712-zen

I'm asking the customer to use wp-admin/widgets.php and to use the list view to select the widgets.

**Comment by tellisbethel** [comment]
Encountered this as well here: 4318353-zd-woothemes 
(This user would love to be notified of any updates.)

I pointed the user to their wp-admin screen, but it wasn't a suitable workaround for them given their long list of legacy widgets. Here's a screenshot showing just a few of them:

<img width="1389" alt="Screen Shot 2021-09-22 at 15 31 42" src="https://user-images.githubusercontent.com/1767799/134401654-493a782a-ef8c-46c0-a24e-2a5b206a345f.png">

**Comment by jp-imagines** [comment]
Another report: 31821186-hc
Previous HE on the chat temporarily deactivated block widgets for one of the user's site as a workaround before discovering this report.

**Comment by fullofcaffeine** [comment]
Fix has been deployed in D67244-code. Let us know if you still experience any issues!

**Comment by jsnajdr** [comment]
To send authenticated REST requests to `public-api.wordpress.com`, the `gutenberg-wpcom-apifetch` module uses the WordPress.com REST proxy. That's an iframe loaded from `public-api.wordpress.com`, it's same-origin with the actual REST endpoints URL, and can add the headers and cookies that are needed to authenticate the REST requests -- an `Authorization: X-WPCOOKIE` header and a `wp_api_sec` cookie.

The editor that's running on a third-party mapped domain like `example.blog` sends cross-origin requests not with the native Fetch or XHR APIs, but by sending messages (`postMessage`, `onmessage`) to the iframe and back. The iframe then sends the actual requests and it's capable of sending them because it knows the authentication credential that the parent `example.blog` frame doesn't know.

The message that the parent frame sends to the proxy iframe looks like this:

<img width="387" alt="Screenshot 2021-09-23 at 9 43 32" src="https://user-images.githubusercontent.com/664258/134471315-44947888-5947-4b3f-8385-16c5b64b5384.png">

The iframe uses that message to construct a Fetch/XHR request and then sends back the response in this format:

<img width="423" alt="Screenshot 2021-09-23 at 9 44 23" src="https://user-images.githubusercontent.com/664258/134471458-bb78be54-1f67-46c7-b0a4-b58af2c2b135.png">

The `61c79f3a-97f9-4e26-8661-611dfc4c300c` is an unique ID that's used to match requests with responses and you can see them in both the request and the response. It's in `params.callback` and in `e.data[ 3 ]`, respectively.

The response is an array with a `[ body, status, headers, callback ]` structure.

You can play with this yourself by running Calypso locally in dev mode and then place breakpoints in the `wpcom-proxy-request/src/index.js` module. One on the `iframe.contentWindow.postMessage` call, one on the `onmessage` callback that's registered with `window.addEventListener( 'message', onmessage )`.

Now, what went wrong with the Gutenberg `api-fetch` `AbortController` is that the `AbortSignal` object ended up as a `params.signal` field and `postMessage` wanted to send it along to the proxy iframe. But you can send only data as a message, not an `AbortSignal` object that has methods and events etc. That fails to be serialized with the browser's [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm).

What we need to do in order to make the proxy requests abortable is to add that support to the proxy client. I.e., to the `wpcom-proxy-request` package and to the `gutenberg-wpcom-apifetch` module that uses a jQuery-based version of the proxy client.

It would do something like:
```js
if ( request.signal ) {
  request.signal.addEventListener( 'abort', () => {
    // reject the promise returned to the caller
    requestPromise.reject( new AbortError( 'aborted' ) );
    // tell the proxy iframe to abort the request and not send response back
    iframe.contentWindow.postMessage( {
      abort: true,
      callback: '61c79f3a-97f9-4e26-8661-611dfc4c300c',
    } );
  } );
  // remove the `signal` field so that it's not sent to the proxy iframe
  delete request.signal;
}
```

As an aside, the fact that `gutenberg-wpcom-apifetch` is implemented using `jQuery.wpcom_proxy_request` and `jQuery.ajax` is quite unfortunate. We could do much better than that, with no jQuery at all. Instead of `jQuery.ajax` we can use `window.fetch` directly, and as the proxy client we could use the `wpcom-proxy-request` NPM package which implements the client in vanilla JS with zero dependencies.

**Comment by jp-imagines** [comment]
@fullofcaffeine I just had another report of this in 2422993-hc (social media icons legacy widget). Confirmed it on my end as well.

**Comment by AtrumGeost** [comment]
Hi @fullofcaffeine 
We have another report here:

4385556-zd-woothemes

I was able to see the issue on my end both on the Customizer and WP Admin:

![Screen Shot on 2021-10-23 at 08:55:43](https://user-images.githubusercontent.com/3696121/138559435-4db00aaf-cb4f-40cc-aaf4-6eb0ad6ba769.png)

I'm also getting many console errors as the widgets admin page is loaded:

![Screen Shot 2021-10-23 at 08 57 27](https://user-images.githubusercontent.com/3696121/138559510-30166a56-e416-401f-a805-4f19a2d05cfa.png)

**Comment by kuropixel** [comment]
I had a user with this issue. 32521196-hc

I was able to replicate it in the customizer on my end as well
<img width="830" alt="Screen Shot 2021-11-02 at 14 01 10" src="https://user-images.githubusercontent.com/83020905/139789322-f6bbd0a2-aecb-4785-82cf-adb9c94e18d1.png">

**Comment by chad1008** [comment]
@kuropixel Your screenshot looks like it's from widgets.php in wp-admin, and not the Customizer, is that correct?

I'm able to reproduce it if I check widgets.php for the specific site referenced in the chat you've included, but not in the Customizer.

I also cannot reproduce on my own site, even if I activate the same theme (Edin) so there may be something very specific about that site we need to dig into.

First though, can you confirm if you are seeing this in the Customizer as well as widgets.php? And if it's happening on your test site or just on the customer's site?

**Comment by kuropixel** [comment]
@chad1008 

Thank you for replying.

Yes, my screenshot is from widgets.php, but the same issue happens in Customizer. My apologies for not being detailed on how to see this through customizer!

The only way I'm able to see the issue is:

1. Go to Customizer
2. Go to Widgets
3. You can only see Footer widgets by default, so you have to navigate on the site preview to "Music and Movement~" or "Orff-Afrique Master class" from the site menu to bring up the sidebar widgets.
4. Many of the widgets are invisible until clicked.

I'm not able to replicate on a test site because I'm not sure how to reproduce the exact legacy widget from the user's site on my test site. Adding a legacy widget on a test site wants me to specify which one, and I'm not seeing the type of legacy widget specified on user's site
![customizer](https://user-images.githubusercontent.com/83020905/139964027-e09accd2-1d22-4cd2-95a6-e8ec100b11ec.png)
.

**Comment by chad1008** [comment]
Sorry for the delayed response @kuropixel, and thank you for the additional info. I am able to reproduce it on the customer's site in both widgets.php AND the customizer, but _only_ on that site.

As @kuropixel notes, Text Widgets are no longer an option under Legacy Widgets when adding a new one, so I can't fully test on a site that doesn't _already_ have text widgets in place.

Looking at the site, all of the affected widgets are Text widgets, however, not _all_ text widgets are losing their previews. There are several Text widgets on the site in different widget areas that render previews as expected.

cc @fullofcaffeine , I know we had a fix for this previously, but it looks like there are still some edge cases that are triggering the lack of previews.

**Comment by TeniCola** [comment]
Hi team, another user report in 30284626-hc, I was able to replicate on their account for legacy widgets, in both the Widgets page and the Customizer.

This user hadn't contacted us in 5 months, so they were finding this on _all_ of their websites as were understandable concerned. I advised them about the error and how to click to access their widgets in the editor, but worth noting that this may confuse users who return to adjust their widgets for the first time in a while.

**Comment by ccwalburn** [comment]
Another user report here: 
26227933-hc
4465958-zen

**Comment by rachelwinspear** [comment]
Another report:
32511675-hc
4547317-zen

Screenshot of how the widgets show up blurry, until they are clicked on: 
![Annotation on 2021-11-26 at 12-05-05](https://user-images.githubusercontent.com/44442769/143586685-36a9411a-2819-48df-9eee-57c3f79819db.png)

**Comment by thekingsprojects** [comment]
Another report here: 4555389-zen

**Comment by devNigel** [comment]
Another report: 32963141-hc

Follow up: 4575333-zen

**Comment by jp-imagines** [comment]
Another report in 33113726-hc. User couldn't find a Mailchimp widget to remove it because of this.

**Comment by thekingsprojects** [comment]
Another report here: 22827547-hc

User was okay with just having me remove the widget for now, since it was hard for them to actually find in widgets.php.

**Comment by edwinho89** [comment]
Another report on 4691463-zd-woothemes

User is using the retired "Hearts and Style" premium theme, if it relates to that.

It is also weird that legacy widgets aren't being shown on the theme sidebar, until you convert into a block widget - https://d.pr/v/0payUu

**Comment by vajrasar** [comment]
Another user report here: 4749075-zen

Theme: TwentyFourteen

All the widgets show with the "Legacy Widget" title, and preview shows only Widget Headings (not what the widget actually are).

**Comment by inaikem** [comment]
@chad1008 👋 Just a quick ping to see if it's possible to taker another look at this, thanks!

Cc: @Automattic/dotcom-triage-pa-group + @cometgrrl

**Comment by chad1008** [comment]
Hi @inaikem ! I know @fullofcaffeine has been investigating a solution, though it sounds like some additional testing/investigation is needed... but it hasn't been forgotten!

ref: p1643133714043300-slack-C7YPUHBB2

**Comment by tellisbethel** [comment]
Another case here: 31924804-hc
User was unable to see Cookies and Consent widget without focusing on it.
Third party theme: Soho

**Comment by thekingsprojects** [comment]
Similar case here: 31420254-hc

User was not able to see their legacy widgets in Customizer without clicking, but can see them and edit them in widgets.php.

**Comment by jamiepalatnik** [comment]
Another report: 34350562-hc
Some legacy widgets (not all) are invisible in Customizer and Widgets preview unless clicked. Hovering will reveal a small outline of the widget (but not its full size). When clicked, it is possible to edit as usual.

Noting that this is happening on an AT site, not a simple site.

**Comment by kathrynwp** [comment]
Ran into this in 22745418-hc 

In addition, editing the legacy widget **caused it to duplicate.**

**Comment by jp-imagines** [comment]
Another report in 35793057-hc. User couldn't find widgets to delete them because of this. Simple site, affected `/widgets.php` and the Customizer.

**Comment by fullofcaffeine** [comment]
We shipped a fix for this today in D73778-code. I'll close this now, but feel free to re-open it if you get a similar report again and we'll investigate. Thanks!
