### ISSUE TITLE
Problem retrieving blog stickers

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#56483]
### Quick summary

Some customers are seeing
`Problem retrieving blog stickers. Please try again later`

[Here is an instance on a Simple site](p1632357338149200-slack-C03TY6J1A).

[Here is another on an AT site](4315172-zd-woothemes)

![image](https://user-images.githubusercontent.com/29057562/134441691-663322bd-b6d3-4698-ad98-e91534204ecc.png)

### Steps to reproduce

In 4315172-zd-woothemes, the Customer sees it at 
WordPress.com > My Sites > Upgrades > Plans
but I could not reproduce it.

### What you expected to happen

No "Problem retrieving blog stickers"

### What actually happened

`Problem retrieving blog stickers. Please try again later`

### Reproducibility

Intermittent

**Comment by kosiew** [comment]
hi @Robertght ,

Flagging for flow attention

**Comment by kuropixel** [comment]
I'm also seeing this issue on simple sites.
I'm able to trigger the message when I go to Purchases, choose an entry, and wait for about 30 seconds to a minute.
4312381-zd
4318807-zd
![blog sticker](https://user-images.githubusercontent.com/83020905/134442313-0ec302f0-2bd0-4383-92f7-36d24b79774a.png)
![blog sticker 2](https://user-images.githubusercontent.com/83020905/134442388-8196523b-7025-4005-a2d4-63c9553cef9b.png)

**Comment by Robertght** [comment]
I've asked in Slack now: C029WGXE5T4/p1632373949016800

**Comment by Greatdane** [comment]
We had another report of this issue (which I can reproduce as the user) today;
5225778-zd-woothemes

This happens when the user visits certain blog posts in the reader (exact details in the ticket). Note, the user used to have an Atomic site but no longer. 

<img width="561" alt="Screenshot 2022-05-19 at 14 11 27" src="https://user-images.githubusercontent.com/5075840/169213094-f01364ca-2a11-45fe-83bb-1456a770a838.png">

@dsas is it possible you can have a look at this again please?

**Comment by dsas** [comment]
Hi @Greatdane, this will be someone else making the same kind of mistake as I addressed originally, rather than the same issue. I'll take a look and try to get it to the right teams attention.
