### ISSUE TITLE
Playwright: add e2e tests for P2

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#56664]
### Details

Investigate feasibility of adding automated e2e tests for P2s as part of the Gutenberg update process.

Context: p1632936169323300-slack-C7YPUHBB2

### Checklist

- [ ] Set up TeamCity task for P2 tests.
- [ ] Set up a testing P2 blog and user account.
- [ ] Set up a cron job to clear the test P2.
- [ ] Write test cases for the front-end editor.

**Comment by mirka** [comment]
Thanks for considering this @worldomonation !

I wanted to note that we'll be adding a gutenberg-edge P2 to the vizreg tests on our end, too. These monitoring tests run hourly for normal P2s on production, and daily for gutenberg-edge P2s. It should at least catch the immediate editor crashes.

What kind of e2e tests do you usually run for non-P2 simple sites? Just making sure we don't waste your time in case it takes a lot of effort, or the type of coverage is redundant 😄

**Comment by worldomonation** [comment]
@mirka 👋 

> What kind of e2e tests do you usually run for non-P2 simple sites?

[This](https://github.com/Automattic/wp-calypso/tree/trunk/test/e2e/specs/specs-playwright) is the list of e2e specs that are currently run against Calypso on Simple and Atomic sites.

Every test file runs against (at a minimum) Simple sites. Atomic coverage is less than Simple, but the situation now is better than 2 months ago where no coverage existed 😅 

Context: my team (Quality-Squad) is in the final phases of transitioning our testing framework from Selenium to Playwright. We rewrote a whole bunch of test specs as part of this process and added new tests where appropriate.

There currently exists decent coverage for the Gutenberg editor in Calypso. 
[This spec](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-playwright/wp-editor__post-basic-flow-spec.ts) covers the basic editing, preview, publish and tagging workflow for the editor.
[This spec](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-playwright/wp-likes__post-spec.js) indirectly covers the editor in the process of publishing a test post.

---

I haven't had a chance to take a deeper look at what's required to set up some sort of e2e coverage for P2s yet; some of the challenges I anticipate are:

- should this run as part of the [Calypso](https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop?branch=%3Cdefault%3E&buildTypeTab=overview) life cycle or under [Gutenberg](https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_desktop?branch=%3Cdefault%3E&buildTypeTab=overview) life cycle, or in a standalone task?
- standing up the testing infrastructure (P2 under test, testing user account, emptying the P2 regularly, etc.)
- if something breaks, what happens then?

Most of these are not serious blockers; it has more to do with me being relatively new here and not knowing some of the processes, etc.

**Comment by mirka** [comment]
I see, that was very informative, thanks.

> * should this run as part of the [Calypso](https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop?branch=%3Cdefault%3E&buildTypeTab=overview) life cycle or under [Gutenberg](https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_desktop?branch=%3Cdefault%3E&buildTypeTab=overview) life cycle, or in a standalone task?

The P2-specific coverage we need is on the frontend P2 editor, since the wp-admin/calypso editor is basically the same as on other Simple sites. Historically, the failures we've seen have largely been integration problems with a new Gutenberg plugin version & [Isolated Block Editor](https://github.com/Automattic/isolated-block-editor/).

> * standing up the testing infrastructure (P2 under test, testing user account, emptying the P2 regularly, etc.)

Because we've never really had failures with publishing itself, we don't need any setup/teardown as all the worthwhile testing can be done in the editor without persisting data.

> * if something breaks, what happens then?

@Automattic/lighthouse or @johngodley has to fix, or pin the older Gutenberg version for P2s. I guess all this points to the conclusion that the current e2e monitoring setup that Lighthouse has is probably sufficient for the time being, although we might add a few more tests around specific editor interactions. I'm also looking into adding React unit tests to Isolated Block Editor, which should help too.

**Comment by worldomonation** [comment]
@mirka Thanks for some answers! My bullet lists were more questions I had posed for myself, but I appreciate the clarifying information you've provided in your answers.

There are some other items that my team needs to get done, but we'll discuss this topic in the next sprint meeting :)

**Comment by worldomonation** [comment]
Consider using these test P2s when the test is written:
- 3hyOA-p2
- 9WIwn-p2
- cl4cA-p2

**Comment by worldomonation** [comment]
@mirka I saw there were issues with Gutenberg 11.9 and P2 this morning (PST). Sorry I was not able to implement the front-end sanity tests before this happened again.

I noticed in p1637254351381800/1637115269.354600-slack-C7YPUHBB2 that you mention there are basic sanity checks. There are also tests you mention in p1637254604382800/1637115269.354600-slack-C7YPUHBB2 which I assume are visual tests.

Here's my thought: how and what should be tested on our end here so that issues like what we saw today is caught?

Currently, the [proposed PR](https://github.com/Automattic/wp-calypso/pull/58217) sets up a build inside TeamCity, under Calypso > WPCOM Tests. The schedule is for it to run every 3 hours, every day of the week. 

Since Gutenberg deploys are done as part of `wp-calypso`, would it make sense to trigger P2 tests for every merge to `trunk` as well?

----

In terms of the content being tested, at this exact moment it's a super basic test consisting of:
1. log in and navigate to a P2 (set up for this purpose).
2. enter some text in the frontend editor.
3. post.

How would you like to see this expanded? It seems the issue from today was related to saving the post as draft with a Button block in the editor. 

Note, while I won't be able to write all the tests due to myself being the only dev on the team for the next 6 weeks, I'd be happy to lay some additional groundwork so it's easier for someone else to write tests.

----

Action items for me:
- [x] apply the `gutenberg-edge` sticker to the test P2.
- [x] merge the changes to add `P2E2E` to TeamCity.

**Comment by mirka** [comment]
> how and what should be tested on our end here so that issues like what we saw today is caught?

The failure caught today was rare in the sense that it was a purely backend problem (a fatal thrown in an API endpoint). In the past 18 months or so that we've been doing this, the vast majority of integration failures have been on the frontend (JS or CSS). In fact I don't remember there ever being a purely backend one (@johngodley @annemirasol do you remember anything?). This is why we currently only have integration tests for frontend issues.

Now, it is entirely possible that the failure today was a harbinger of things to come, perhaps attributable to the active backend changes happening in Gutenberg for [Global Styles](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/). But given that this is still a very rare type of issue, and that we were _still_ able to catch it in time through non-automated measures (increased dev interaction with gutenberg-edge), I wouldn't necessarily flag this as a priority yet. Even as I debugged the issue, it did not strike me as a type of failure that could've easily been caught by an E2E test. It was a general "cache invalidation is hard" issue, and a non-obvious P2 code path just happened to be one of the triggers.

It would be easier to design a useful test once we see a pattern of failure modes.

> How would you like to see this expanded?

I think that's fine for the time being. The "3. post" step is a nice added layer of confidence since we don't currently test any DB writes.

Even for the wp-admin editor which we don't test yet, most if not all of the regressions have been visual in nature. So it would probably make more sense for Team Lighthouse to just expand our vizreg tests to cover that.

**Comment by johngodley** [comment]
> In fact I don't remember there ever being a purely backend one

No, I don't think there's been a pure back end one. Mostly it's front end only, or something missing on the back end that crashes the front end (i.e a setting).

**Comment by worldomonation** [comment]
> I think that's fine for the time being. The "3. post" step is a nice added layer of confidence since we don't currently test any DB writes.

I plan to add a few more steps to the test, which may consist of the following steps:
- add different blocks
- add a reply
- save draft then transition to the iframed editor
- delete post

No timeline for implementing these yet, but hopefully adding some of these additional steps would help catch breakages quicker.

**Comment by worldomonation** [comment]
FYI, when the linked PR #58217 merges, a P2 E2E build configuration will be added to Calypso > WPCOM Tests category. It will be located [here](https://teamcity.a8c.com/project/calypso_WPComTests?branch=%3Cdefault%3E&buildTypeTab=overview&mode=builds#all-projects).

**Comment by worldomonation** [comment]
Changes merged in and a build configuration for P2 E2E tests has been created under [Calypso > WPCOM Tests > P2 E2E Tests](https://teamcity.a8c.com/buildConfiguration/calypso_P2E2ETests?branch=%3Cdefault%3E&buildTypeTab=overview&mode=builds).

I'll be paying some attention to this going forward. Plan is to also add some more test cases for the front-end editor.

@mirka Are you happy with the outcome of this so far? If you have suggestions for additional test cases, or comments on how this is set up, feel free to let me know 😀 

Currently a test run is triggered every 3 hours. Should it be more or less frequent?

**Comment by mirka** [comment]
Awesome, thanks so much for adding these! We'll be in touch if we need any modifications. The tests look straightforward to add, so maybe Lighthouse can just ping you for review if we write more test cases.

> Currently a test run is triggered every 3 hours. Should it be more or less frequent?

Sounds reasonable 👍

Some final questions:

1. Do the tests run on a gutenberg-edge site, a normal production site, or both?
2. What happens when a test fails? (Who gets the alert, and how? Can we easily set up some kind of alerting system, for example that outputs to a Slack channel?)

**Comment by worldomonation** [comment]
> Awesome, thanks so much for adding these! We'll be in touch if we need any modifications. The tests look straightforward to add, so maybe Lighthouse can just ping you for review if we write more test cases.

No worries - happy to help!

>     1. Do the tests run on a gutenberg-edge site, a normal production site, or both?

I've tagged the P2 used in this test with `gutenberg-edge`. Is that sufficient to ensure it's running the latest Gutenberg?

>     2. What happens when a test fails? (Who gets the alert, and how? Can we easily set up some kind of alerting system, for example that outputs to a Slack channel?)

Right, that's probably something that should be set up. 
For Calypso end-to-end tests, we have a slack channel at #e2eflowtesting-notif.

Here are some options:
- send notifications directly to your team channel (if you have one)
- send notifications to a new channel (eg. #e2eflowtesting-p2)
- send notifications to same channel as Calypso tests.

There's further options to tweak the kinds of messages:
- notify only on failure
- notify on failure _and_ success
- notify on start, success and failure

Sorry for wall of text 😛

**Comment by lezama** [comment]
hey @worldomonation could we do these?

* notify on start, success and failure to a new channel  #e2eflowtesting-p2
and 
* notify only on failure to ##happytools-alerts


if it's not easy just the second one :)

Thanks for all your help here!

**Comment by worldomonation** [comment]
@lezama I've posted a PR here: https://github.com/Automattic/wp-calypso/pull/58463

It's pending review by the folks at Team Calypso and it should start working once it's approved and merged.

**Comment by mirka** [comment]
> I've tagged the P2 used in this test with `gutenberg-edge`. Is that sufficient to ensure it's running the latest Gutenberg?

Yes, that is sufficient 👍 Thanks.
