### ISSUE TITLE
Add Query Pagination block by default into Query Loop block

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#56819]
### What

Allow Query Pagination block added inside Query loop block by default

### Why

It would be easier to remove existing blocks, rather than finding and adding the Query Pagination block instead.

**Comment by inaikem** [comment]
Thanks for the request, Edwin 👍  I'm closing this as a duplicate. 

For context, this was recently requested in #56501 by @carinapilar, and was subsequently added by me as a Gutenberg core enhancement request here: https://github.com/WordPress/gutenberg/issues/35134.

The issue was [mentioned in this pull request](https://github.com/WordPress/gutenberg/pull/35347) and has since been added to the [Gutenberg 11.7 milestone](https://github.com/WordPress/gutenberg/milestone/161)! 

Gutenberg 11.7 is currently in [Release Candidate](https://github.com/WordPress/gutenberg/releases/tag/v11.7.0-rc.1) stage and is expected to ship on/around October 13th 🚀

**Comment by formosattic** [comment]
FYI: be aware that finding the Query Selection block is still tricky, and being addressed
https://github.com/WordPress/gutenberg/issues/35788

To find the Query Pagination block, you must add the block inside the Query Loop, then  select **Browse all** or **Search** for it:

![image2](https://user-images.githubusercontent.com/15944096/138675600-ffee3311-e9f0-4f4f-8ecd-78bba0737737.png)


![image](https://user-images.githubusercontent.com/15944096/138670199-e51d7862-b30a-4914-bda7-1b4788c4076c.png)
