### ISSUE TITLE
Seedlet: green background stripe visible in demo isn't visible on the site 

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#56822]
### Quick summary

Seedlet theme: green background stripe visible in demo in homepage isn't visible on the site, even when the same blocks used. 

### Steps to reproduce

1. Instal Seedlet
2. Add blocks: Group > Columns > Images (like in the theme setup)
3. Check preview - there is no green stripe like in theme's demo: https://wordpress.com/theme/seedlet, my test: 
4. This works in Atomic, not on simple site: Add new page and select predefined layout: https://d.pr/v/GsOwIM

### What you expected to happen

There is green stripe in the background

### What actually happened

All background is white

### Context

4352577-zd-woothemes

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

yes

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by jordesign** [comment]
Hey @daria2303  - thanks for checking on this.

The background which shows in this particular pattern is set by a Background gradient which is *part* of the pattern (not automatically added to Group > Columns > Images

<img width="1359" alt="Screen Shot 2021-10-13 at 11 06 14 am" src="https://user-images.githubusercontent.com/1842363/137045372-7a2a3471-1c64-450b-ad0c-d56547551b80.png">

In order to add this layout to the editor - the user could go to the Block/Pattern inserter and select the correct pattern. It will be inserted with the background in place.

<img width="1403" alt="Screen Shot 2021-10-13 at 11 06 41 am" src="https://user-images.githubusercontent.com/1842363/137045405-8c322be6-7513-4305-9c1a-1d5e9d6d94dc.png">

It would be worth following up with this user to explain how they can insert that pattern.

**Comment by jordesign** [comment]
@daria2303  That's definitely very strange - are you able to share your test site with me so I can take a look?

**Comment by daria2303** [comment]
@jordesign sure: https://darusjapers.blog/ it is in home

**Comment by jordesign** [comment]
Hmmm - I can see it in that instance as well - but not in any other testing of Seedlet on Simple SItes. I'll pop this over to the Themes repo to see if they can diagnose anything in these specific instances:

* https://darusjapers.blog/
* http://flauwekult.nl/
