### ISSUE TITLE
Design Picker: Twenty Twenty One content needs updating

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#56835]
We're adding a lot of pages, posts, and media to user sites through the design picker with no control. I believe most of this content is here to support a "Works" page/template that the user does not get to preview before design selection. (They only see the homepage.) And a blog template that only requires one post to capture the layout.

We should clean up the demo site or the headstart annotation for Twenty Twenty One to simplify it.

![image](https://user-images.githubusercontent.com/545779/136230519-849e7db8-979a-4fd2-8131-aae1d7397eb9.png)

![image](https://user-images.githubusercontent.com/545779/136230745-3e5c75d6-87ae-4c77-b6ab-4dd21a6605d5.png)

cc @kjellr @alaczek

**Comment by p-jackson** [comment]
I wrote a diff that filtered out the unreferenced pages during headstart (D68194-code).

But we went through all 28 annotations, and TT1 is the only theme where this filtering code would be used; no other theme has this issue with unused pages. p1634024867145600/1633932553.086100-slack-C029SB8JT8S

Rather than add the extra complexity, I think we should just fix TT1 manually (either by updating the demo site and regenerating annotations, or just manually editing the annotations). Maybe this was your intention all along @ianstewart 

Moved to "Ready for Dev" for someone to do that, but doesn't need to be a dev.

**Comment by p-jackson** [comment]
Oh, and we're already automatically limiting the number of posts to 3, so that part of the demo site doesn't necessarily have to change.

**Comment by alaczek** [comment]
I can go in and manually clean up the headstart annotation in this case. Personally, I'd leave the demo as is, since we want to showcase the theme.

While I update the annotation, I assume I should remove all pages besides Home and Blog?

**Comment by p-jackson** [comment]
The problem with not updating the demo site we discussed with @jordesign was that it breaks HE expectations that running HS from blog RC will make the site match the demo site.
I had thought we'd just remove pages that aren't referenced in menus. I wasn't sure why "Block Patterns" or "Starter Patterns" would be needed if they're not accessible via menu links. Are they linked to directly from within page/post content?

**Comment by p-jackson** [comment]
Oh I see! Pages like "The Garden at Bougival" are linked to directly from "Work". That's tricky...

Maybe that means we _should_ be removing them automatically as part of the onboarding process 🤔

**Comment by alaczek** [comment]
> Oh I see! Pages like "The Garden at Bougival" are linked to directly from "Work". That's tricky...

Yes, exactly - these are needed to set up the Work page!

> Maybe that means we should be removing them automatically as part of the onboarding process 🤔

I don't know about that, my plan was to go in and manually edit the annotation to leave only the Home and Blog pages?
Shall I go ahead?

**Comment by p-jackson** [comment]
> Shall I go ahead?

My gut reaction is no, because it breaks HE expectations about running HS from blog RC. But @ianstewart might want to make the call there.

**Comment by p-jackson** [comment]
As discussed in the pod sync today, let's just the "Work" page from the annotations and leave the demo site as it is.

**Comment by alaczek** [comment]
Done! There were also two extra pages not linked in the demo at all - “Block Patterns” and “Starter content”. I removed them as well. So now there are only four pages in the annotation: Home, About, Blog, Contact, and six posts (which I'm leaving because we'll automatically be limiting to three as per pdgK6S-cW-p2).
