### ISSUE TITLE
Account Close: Domain-only account closure flow is not redirecting to account closed page if user never logged out.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#56841]
### Quick summary

Issue identified from automated e2e testing script: `test/e2e/specs/specs-playwright/wp-signup__domain.ts`.

This issue only affects accounts created through the `/start/domain` flow and the user has **never** logged out before closing the account.

Issue is introduced with https://github.com/Automattic/wp-calypso/pull/56803, which was a fix for an earlier issue https://github.com/Automattic/wp-calypso/issues/56548.

### Steps to reproduce

1. start at `/start/domain`
2. search for and select a domain.
3. select `Just buy a domain`.
4. create an account.
5. check out (using sandbox is fine).
6. after checkout, cancel the domain.
7. close account.

### What you expected to happen

Upon confirming account closure, the `Closing account` spinner is shown.
After that point, the user should be redirected to `wp-calypso/client/me/account-close/main.jsx`.

### What actually happened

`Closing account` spinner is not shown to user.
User is not redirected to `wp-calypso/client/me/account-close/main.jsx`, but instead redirected to `https://wordpress.com`.

https://user-images.githubusercontent.com/6549265/136294313-0f3087c3-4044-4438-9b79-3980c0ef6229.mov

### Context

Playwright automated tests

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Log out then re-log in.

**Comment by worldomonation** [comment]
Quoting from @sirbrillig in https://github.com/Automattic/wp-calypso/pull/56803#issuecomment-936800075:

> Oh, I see it now. Sorry I didn't understand that before!
> 
> I wonder where that redirect to the home page is coming from... the only call to `page()` in `AccountCloseConfirmDialog` is to the expected page.
> 
> One thing that looks possibly suspicious is this code which redirects to a [logout page](https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/state/current-user/actions.js#L66).
> 
> https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/main.jsx#L38-L43
> 
> I wonder if maybe that redirect is triggering before the confirmation dialog's redirect (it's possible since the confirmation redirect uses `page` which may have a delay and the above redirect uses `window` which should be faster), and perhaps [the calculation it uses](https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/lib/user/shared-utils/get-logout-url.js#L3-L27) to determine the logout url is affected by logging-in for the first time.
> 
> I'd be curious to see what happens if we reproduce the problem and disable [the redirect in `AccountSettingsClose`](https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/main.jsx#L38-L43).

**Comment by sirbrillig** [comment]
I've done a little research on this and the issue appears to be mainly that the call to `page()` that's supposed to redirect to the "deleting" page silently does nothing at all if you haven't refreshed calypso (a logout is not required, just a page reload).

https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/confirm-dialog.jsx#L53

The result is that the user stays on the account page and the [log out redirect](https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/main.jsx#L41) fires eventually when the close action completes, which redirects the user to the log-out page (`https://wordpress.com/wp-login.php?action=logout&_wpnonce=xxxxx&redirect_to=https%3A%2F%2Fwordpress.com%2F`) which sends the user onto the homepage via a 302 redirect.

I've never seen a case where `page()` did not work, but it must have something to do with having created a new account in the same browser session. I'm trying to figure that out. Unfortunately the most common solution to `page` problems, using `window.location.href = ...` instead, probably won't work here because we want to wait for the pending async account close request to finish.

**Comment by sirbrillig** [comment]
I figured it out. The `page()` [redirect](https://github.com/Automattic/wp-calypso/blob/f243ee759ce1add7d8b07bf5d0f35e83b0d3b559/client/me/account-close/confirm-dialog.jsx#L53) after final confirmation _was_ working, but then was being redirected _back_ to the first page by [another](https://github.com/Automattic/wp-calypso/blob/f243ee759ce1add7d8b07bf5d0f35e83b0d3b559/client/me/account-close/closed.jsx#L20-L22) `page()` redirect. Since they were both SPA redirects, it appeared to do nothing at all.

The guard that caused this bug has actually existed for 2 years but probably was hidden because all the flows had a page refresh. It's likely that https://github.com/Automattic/wp-calypso/pull/56803 somehow removed the need for one of those refreshes, exposing the issue. It's also possible that something changed about how the Redux `getPreviousRoute` selector worked for new signups and maybe it used to work when the original guard was added.

It should be fixed by https://github.com/Automattic/wp-calypso/pull/56849

**Comment by sirbrillig** [comment]
One of the more obvious clues that I should have noticed earlier was that the confirmation dialog closed after the final confirmation, but there's no flow inside the components where that's even possible. The only flow that closes the dialog is pressing "Cancel". 

The reason that the dialog was appearing to close was that _the whole page_ was being unmounted and remounted when we were being briefly (and invisibly) redirected to the spinner page and then immediately back again. This caused the parent page to re-render from scratch where no dialog was visible, making it appear that the dialog somehow got closed.

**Comment by worldomonation** [comment]
> One of the more obvious clues that I should have noticed earlier was that the confirmation dialog closed after the final confirmation, but there's no flow inside the components where that's even possible. The only flow that closes the dialog is pressing "Cancel".
> 
> The reason that the dialog was appearing to close was that _the whole page_ was being unmounted and remounted when we were being briefly (and invisibly) redirected to the spinner page and then immediately back again. This caused the parent page to re-render from scratch where no dialog was visible, making it appear that the dialog somehow got closed.

I appreciate that you have taken so much time to dig into this issue. Thank you!

I've already deployed a workaround that involves logging off then back in, but I'll try doing a `reload` instead on the workaround. It will save us quite bit of execution time not having to log back in.
