### ISSUE TITLE
Notifications: inconsistent scrolling behavior across browsers

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#5697]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Open notifications
3. Scroll all the way down the notification list
4. The page (Reader) scrolls once you reach the bottom of the notes list
#### What I expected

The background page should not scroll while I'm scrolling in the notifications panel.
#### Browser / OS version

Mac OS X 
Chrome and FF

Safari is the only browser that works as expected.

cc @jasmussen @rodrigoi

**Comment by lancewillett** [comment]
Confirmed in testing in Safari vs Chrome (both on OS X) — Chrome is super odd in that it scrolls notifications pane once down, then Reader page once down, then alternates between them.

**Comment by jasmussen** [comment]
I think we decided to call this "scroll bleed", and the desktop app has a fix for this, which @beaucollins and I worked on a while back. It's enabled only via a feature flag for the desktop app because it's sort of icky and hacky. 

There are some circumstances surrounding this that I don't fully recall, but I believe the desktop app uses a notifications client that is not in an `iframe`, or did at some point. And because it didn't, the hack that would prevent scroll bleed in Calypso didn't work. 

However I see now that Calypso still uses an `iframe` for the notifications client — and therefore there seems to have been a regression. 

The old hack, which I think @rodrigoi worked on, but I may be mistaken, involved *disabling* scrolling on the main Calypso window when the mouse is over the notifications client, and *enabling* it again when it's outside. This works because the iframe is a separate `window`, so scrolling isn't disabled everywhere.

**Comment by beaucollins** [comment]
It's actually a mixin inside the happychat component now. It prevents the mousewheel event from bubbling out of a particular node when the mouse is over it.

**Comment by beaucollins** [comment]
I believe the "hacky" bits have to do with attempting to simulate intertial scroll via he mousewheel in the node that has captured the mousewheel events.

**Comment by jasmussen** [comment]
For whatever reason I can't invoke the dev tools in the latest WordPress app, so I can't verify that the notifications client inside the app is in an iframe or not. But I believe it isn't, and like I said that's why we implemented the hacky scrollbleed trick that Beau is referring to.

However so long as the web client uses an iframe, and unless it's switching away from that, the better hack is to use the old iframe hack that must've regressed at some point. 

I made this collection of Codepen scrollbleed hacks: http://codepen.io/collection/DZOGmL/ — though none of those use the iframe hack.

**Comment by drw158** [comment]
There is a long term goal of removing the notifications iframe in Calypso, that is slowly being worked on (https://github.com/dmsnell/wrnc). Maybe we could implement the hack until the new version is ready. I think we'd still need the iframe for the front-end and Jetpack right? It would be nice to figure out a consistent solution for those cases.

**Comment by jasmussen** [comment]
If the iframe is being phased out, we might as well use the hack that Beau and I built for the desktop app. Right now it's flagged as desktop only — so in theory we should be able to just upgrade from that.

**Comment by ryanboren** [comment]
This post has a visual:

https://test.wordpress.com/2016/11/02/session-notes-scroll-bleed-ios-web-alt-text-flow-captioned-gallery-flow-unpermalinks-editor-ays/

#scroll-bleed is pervasive, especially on iOS.

https://test.wordpress.com/tag/scroll-bleed/

**Comment by drw158** [comment]
Still an issue.

**Comment by drw158** [comment]
Moved: https://github.com/Automattic/notifications-panel/issues/216
