### ISSUE TITLE
Legacy Dotcom FSE cleanup

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#56975]
Task: deprecate and remove legacy Dotcom FSE code.

After the plan to migrate legacy FSE sites to Core FSE is executed (see pbAok1-27H-p2), there is a lot of code that we can remove as it will no longer be used by any sites on WP.com. It's important to do this, as leaving this code in place creates confusion because it refers to "FSE" but not the features and functionality that most people now think of when seeing FSE.

This list likely incomplete, but here's a start to what we should remove/change

- [x] Remove dotcom-fse code from the ETK plugin and wpcom (https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse)
- [ ] Update FSE and Site editor related functions and classes, removing "core", this is redundant once dotcom FSE is gone (e.g. `is_core_fse_active` and related functions in https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php)
- [x] Remove `\A8C\MU\Full_Site_Editing\Full_Site_Editing` file and class from wpcom
- [ ] Remove namespace `A8C\MU\Full_Site_Editing` from helper functions (`enroll_in_fse` and `is_fse_eligible`)
- [ ] Ideally it would be good to get rid of the singleton classes in mu-plugins/full-site-editing, as these are mainly being used to namespace functions that already have PHP namespaces 🙃

Please comment with any additional tasks for this issue!

**Comment by mattwiebe** [comment]
> Remove dotcom-fse code from the ETK plugin and wpcom

We are not going to remove all of it, but rather we are going to remove all of the editor and REST API integration. The frontend will continue rendering the header and footer template parts that the user is accustomed to, while no longer being able to edit them. Users who need to edit their header or footer can be helped to switch to a Core FSE theme. See #61453 for current work

Otherwise, here's a few more things:

- [x] remove REST API hooks/overrides
- [x] remove all references to `isSiteUsingLegacyFSE` and `isSiteEligibleForLegacyFSE` from Calypso

**Comment by mattwiebe** [comment]
All Legacy FSE stuff has been scoured from our systems, save for frontend rendering of template parts, where they existed. All of the cleanup stuff where we needed to qualify Core FSE as opposed to Legacy Dotcom FSE can now be refactored for greater clarity.

**Comment by Addison-Stavlo** [comment]
Closing as we can track this in the other issue - https://github.com/Automattic/wp-calypso/issues/61107
