### ISSUE TITLE
Missing author field in post-activation card when switching themes

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#5699]
#### Steps to reproduce
1. Visit /design
2. Click thumbnail to open preview
3. Click Try and Customize
4. Click Save and Publish
5. Note missing author https://cloudup.com/cw5UGlCeugh

**Comment by ockham** [comment]
This is due to the thanks modal obtaining its `theme` prop from the `ActivatingTheme` data component, which in turn uses the `getCurrentTheme` selector. While the `THEME_ACTIVATED` action correctly sets the `currentTheme` value, there's unfortunately a `THEMES_RECEIVE_CURRENT` event fired afterwards that obtains its data from the `/v1.1/sites/example.wordpress.com/themes/mine` endpoint (which only has `id`, `name`, and `cost`), and overrides the `currentTheme` value.

I think the solution will be to avoid `THEMES_RECEIVE_CURRENT` being triggered right after theme activation.

**Comment by ockham** [comment]
Another possible fix would be to have the `currentTheme` reducer only update if the new theme `id` is different from the previous one...
