### ISSUE TITLE
Paragraph Block: Text Color option missing from block's toolbar list of more options

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#57054]
### Quick summary

The Text Color option is missing from block's toolbarthe 

![image](https://user-images.githubusercontent.com/39308239/137446195-59bf96ea-5e79-44cd-9970-7bd91b8512ba.png)

### Steps to reproduce

1. Add [Paragraph Block](https://wordpress.com/support/wordpress-editor/blocks/paragraph-block/)
2. Type some text and select it
3. Click the downward arrow in the block toolbar to see more hidden options

### What you expected to happen

See the option called Text Color described [here](https://wordpress.com/support/wordpress-editor/blocks/paragraph-block/#text-color)

### What actually happened

There is no such option anymore

![image](https://user-images.githubusercontent.com/39308239/137446195-59bf96ea-5e79-44cd-9970-7bd91b8512ba.png)

### Context

Reported by customer in 4377247-zd-woothemes

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Other notes

Editor information:

Gutenberg: v11.7.0
CoBlocks: 2.10.1
Editing Toolkit: 3.16867
WP AMP: 2.0.5

### Reproducibility

Consistent

**Comment by jordesign** [comment]
Thanks for reporting @zdenys - This is by design - introduced in the most recent version of Gutenber.
Text Color is no replaced by 'Highlight' which allows you to change both the text color and the background color:
https://github.com/WordPress/gutenberg/pull/34680

I've opened an issue to get the doc updated:
1287-gh-Automattic/en.support-docs-content
