### ISSUE TITLE
Block widgets: Social icons block broken if added as widget in Customizer

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#57083]
### Quick summary

It appears the Social Icons block doesn't work as expected when adding via the Customizer on a simple site - icons don't display correctly, and the text box to add a URL doesn't appear. It works as expected in WP-Admin, and also on an Atomic site.

### Steps to reproduce

1. Open the Customizer >Widgets
2. Add a new widget, and select the Social Icons block
3. Add a new icon, selecting any available option

### What you expected to happen

For the icon to appear in the widget panel and in the site preview, as the default round icon. Clicking on it I expected the text box to appear to add a URL.

### What actually happened

The icon appears elongated, stretched the full width of the Customizer sidebar. It doesn't appear on the site preview at all.

Clicking on the icon does not offer any way to add a link.

![Screen Capture on 2021-10-16 at 19-33-19](https://user-images.githubusercontent.com/11873759/137596924-f8e47977-bf64-4085-9de4-4c419f846117.gif)

### Context

Reported in the forums at https://wordpress.com/forums/topic/social-media-icons-no-displaying/?view=all

### Operating System

Windows, macOS

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Does not appear to be. Reproduced in Seedlet, Plane, and Hemingway Rewritten

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The widget works if added via WP-Admin at `/wp-admin/widgets.php`

**Comment by Robertght** [comment]
Thank you for reporting this @KokkieH !

I believe this may share a common cause with this one: https://github.com/Automattic/wp-calypso/issues/56688

Flagging this for @Automattic/flow-patrol-create for a second look.

**Comment by darnelldibbles** [comment]
Update from user:

> The problem seems to be that external links generally don’t work.
> 
> Last Edit: It seems the problem only occurs when I view the page in the design-interface. When I go to the webpage the links work. Only the social media icons are displayed in an odd egg shape (and they are not evenly sized), as I mentioned before.

**Comment by arcangelini** [comment]
OK, I have been digging into this and it seems that the issue is currently appearing on Atomic and Simple site for me. The problem appears to be with the way that the CSS is being loaded into the Widget Editor. The functionality of the buttons appears to work but you need to be sure to click the icon and not the button. This is what I am seeing on Simple and Atomic site:

![Screen Capture on 2021-11-17 at 11-20-57](https://user-images.githubusercontent.com/33258733/142183005-6416bdc2-9cda-431e-8a2d-47583cb68e31.gif)

I am going to work on trying to get the CSS to load properly and this will hopefully resolve the issue throughout WPcom

**Comment by arcangelini** [comment]
Further findings...

It appears the overall issue is due to the fact that the widget box in the customizer (and anywhere else this is being called ie Patterns) is not getting the `editor-styles-wrapper` parent tag. This causes the CSS that is injected to not apply. Here is the difference between the Widget editor of WP-ADMIN and the Widget section of the customizer:

![Markup 2021-11-17 at 13 13 27](https://user-images.githubusercontent.com/33258733/142199095-3e767bb0-533b-4da8-9554-f367c6d407a0.png)

I am not 100% sure where this is added or if it would be better to get the `editor-styles-wrapper` added or remove it from the styling that is injected. Stay tuned.

**Comment by yansern** [comment]
> I am not 100% sure where this is added or if it would be better to get the editor-styles-wrapper added or remove it from the styling that is injected. Stay tuned.

Some other blocks that have broken CSS styling under Block Widgets Editor could benefit from having the `.editor-styles-wrapper` classname restored. They may not look as broken at first (minor things like not displaying the right font/color/size/padding/margins/etc.) but they are, the brokenness is just not as glaring as Social Icons.

If there's a way to restore `.editor-styles-wrapper` classname then, it could be one stone multiple birds kind of fix. But IIRC this has to be done in either Gutenberg or WP Core.

What I've done for the Feedback block is just to add the `.wp-customizer` class as a secondary parent classname to `.editor-styles-wrapper.` https://github.com/Automattic/crowdsignal-forms/pull/173/files#diff-07eaa1090eee00bb0abbfe80f0274bed8a3856807b1ac451b41b330dcd86c4a0R54-R55

It's a bit of a code bloat of course, that was just a quick fix.

**Comment by arcangelini** [comment]
[It looks like this fix is being addressed in Gutenberg 11.9](https://github.com/WordPress/gutenberg/pull/35865). I tested the changes proposed on WordPress.com and it should resolve the issue. Currently, Simple sites are on 11.8.3

When 11.9 is deployed I will double-check and make sure all is good.

**Comment by yansern** [comment]
Thanks for discovering the PR! https://github.com/WordPress/gutenberg/pull/35865

**Comment by arcangelini** [comment]
No longer able to replicate. Latest version of Gutenberg has resolved this issue.

Please re-open if you are seeing otherwise.
