### ISSUE TITLE
Marketplace: Monthly / Annually component

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57102]
### What

A switcher component for selecting monthly / annually pricing

### Why

The Marketplace will introduce paid plugins. Since we offer plans on monthly and annual basis we should also offer the plugins in the same basis.

### How

- Let's create a new component that interacts with the state so that it can be reused in multiple cases.
- let’s make sure that selecting “Monthly” or “Annually” persists while navigating to plugins screens

Plugins Browser
<img width="789" alt="SS 2021-11-25 at 15 02 05" src="https://user-images.githubusercontent.com/12430020/143446428-c6319b34-cc70-4652-8523-cec1835e60a5.png">

Plugin Details
<img width="993" alt="SS 2021-11-25 at 15 02 30" src="https://user-images.githubusercontent.com/12430020/143446470-f34d5807-c843-45f3-b9fd-cdb6887f1a82.png">

Designs: oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A49583

**Comment by cpapazoglou** [comment]
Let's see if we can reuse the component which already exists in plans page https://wordpress.com/plans and in new signups https://wordpress.com/new/plans-modal

**Comment by sarahcada** [comment]
>let’s make sure that selecting “Monthly” or “Annually” persists while navigating to plugins screens

I'm reopening this since the selection doesn't seem to persist.

**Steps to replicate**: From Plugins > Add New, select Annual in the switcher component.
**Expected**: The price shown will be Annual.
**Actual**: The price shown is Monthly; switcher is back to monthly.

(That said, the selection from the plugin's screen *will* persist after clicking Purchase and activate.)

![Screen Capture on 2022-01-04 at 14-02-27](https://user-images.githubusercontent.com/26526521/148016205-52e71c57-5652-4f39-baf3-a3d2abc58b37.gif)
