### ISSUE TITLE
Homepage switching not working for Blockbase themes

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#57133]
### Quick summary

When switching to a Blockbase child theme (Quadrat, Zoologist, Geologist) and choosing to use the Homepage content *from the new theme* - no change to the home page is made. The previous theme homepage remains in place.

### Steps to reproduce

1. Go to 'Themes' on any existing site
2. Switch to Quadrat, Geologist, or Zoologist and choose the option to use the new theme's Homepage content
3. Check your site once the theme is active

### What you expected to happen

The homepage content to reflect the *new* theme

### What actually happened

The site retained the old content from before the theme switch

### Context

Team testing

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Quadrat, Zoologist, Geologist

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by creativecoder** [comment]
Noting that this seems to be happening because the these themes are missing the `auto-loading-homepage` tag in the style.css header. This tag is necessary for the theme's homepage content to load when switching themes.

Similar, previous fix, for example: https://github.com/Automattic/themes/pull/3275

**Comment by creativecoder** [comment]
[Themes have been updated](https://github.com/Automattic/themes/pull/4874) with the `auto-loading-homepage` tag, and Quadrat seems to now be working as expected.

Blockbase and Geologist still don't work as expected... the sample content seems to be posts, but selecting "Replace my homepage content" when switching to those themes doesn't change the homepage setting to show posts.

Zoologist does change the homepage setting to show latest posts for me, but of course shows my posts, not the sample ones, so the preview is deceiving. As a separate issue, I think the preview should be updated to use the site's posts rather than the sample content, so it accurately shows what the homepage will look like after switching themes.

**Comment by creativecoder** [comment]
> I think the preview should be updated to use the site's posts rather than the sample content, so it accurately shows what the homepage will look like after switching themes.

I spun that out into another issue: #57670

---

That leaves the issue with Blockbase and Geologist not setting the homepage to show posts when switching to those themes:

> Blockbase and Geologist still don't work as expected... the sample content seems to be posts, but selecting "Replace my homepage content" when switching to those themes doesn't change the homepage setting to show posts.

Who is best to address that? cc @Automattic/theam @Automattic/flowpatrol @Automattic/flow-patrol-create

**Comment by youbrokesomething** [comment]
I can't reproduce this issue with Geologist at this time. My homepage content was replaced with my most recent posts as expected so, I'm going to close this for now. However, I will say that the other open tickets still linked to this one are valid. While the feature is doing what we expect, it might not be what the customer expects if they want all the nice example images etc.

**Comment by fushar** [comment]
Even though this issue is closed, for future reference, we have fixed all such cases permanently via:

- #79167
