### ISSUE TITLE
Account Secondary Email

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#57142]
### What

A user has requested the possibility of adding a second email to their account.

### Why

This would enable users to receive notifications, contact us, on/from several different email accounts and avoid much of the  "Contact us from the email associated with your account" issue.

I do apologize if this is a repeated request, but I couldn't find it anywhere.

The ticket where the user requested the feature was: 4383826-zd-woothemes.

### How

I would add it to the account settings, under the Account email: 

![image](https://user-images.githubusercontent.com/15944096/137888713-b00da348-9878-4625-a9b9-79aa2aa09427.png)

Something like "Secondary Contact Email".

Thanks!

**Comment by formosattic** [comment]
I'm afraid that can't be an option because of this:

> Each WordPress.com account must have a unique email address — email addresses cannot be shared among accounts.

Support link: https://wordpress.com/support/account-settings/#email-address)

The option `Email address to send to` in the Form block is meant for this type of request,
https://wordpress.com/support/wordpress-editor/blocks/form-block/#change-the-email-address-messages-are-sent-to

If they want to be notified at other addresses, they can also configure their inbox to forward messages based on specific rules. Each email service will be different but here's the guide for Google https://support.google.com/mail/answer/10957?hl=en
