### ISSUE TITLE
FSE beta: Templates sidebar is accessible from header dropdown

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#57214]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/site-editor
2. Click the header dropdown button
3. Click the "browse all templates button"
4. Select a template in the sidebar
5. Try to re-access the templates sidebar via the W button

#### What I expected
I originally expected to see the templates sidebar when clicking the W button again, but @jeyip mentioned that the templates sidebar is not supposed to be accessible in the FSE beta. So I'm guessing the templates sidebar is not meant to be accessible from the header dropdown.

#### Browser / OS version
Firefox/macOS

#### Screenshot / Video

https://user-images.githubusercontent.com/6265975/138188137-41f5fc25-b45c-4961-ae80-bcb832f2ee72.mov

**Comment by vindl** [comment]
Hi @noahtallen, thanks for the feedback! We discussed this a bit prior to the release and decided not to deal with it with CSS hacks. The main problem with the default core sidebar now is that it opens the view focused on the current template, which is in a deep level of nesting. As a result, the users in all of our tests had trouble finding a way to go back to the dashboard.

On the other hand, Universal themes declare more than one template, so making the browsing sidebar completely hidden/inaccessible in Beta would be a much more severe regression than having this slight inconsistency for the time being. So it was an intentional tradeoff until we can find a better way to deal with this.

I think the proper way to handle it is to revert back to showing the top level of the sidebar in the core upon opening. The existing users on WP.com are used to `W` leading to posts/pages sidebar already. If that fails, we can try dispatching navigation events to navigate to the top manually (on the W button click) through our editor integration.

**Comment by noahtallen** [comment]
> I think the proper way to handle it is to revert back to showing the top level of the sidebar in the core upon opening. The existing users on WP.com are used to W leading to posts/pages sidebar already

This makes a lot of sense to me. I definitely expected the W icon to open the sidebar after seeing it associated with the W icon after I opened it from the dropdown menu. I wonder if other users feel the same way after seeing the nav sidebar attached to the W icon for the first time

**Comment by Addison-Stavlo** [comment]
Note that the Nav sidebar is being removed from Gutenberg for 5.9.  As a result the "Browse all templates" button on Gutenberg's `trunk` branch currently leads to the wp-admin templates post management screen.

**Comment by noahtallen** [comment]
> Note that the Nav sidebar is being removed from Gutenberg for 5.9. As a result the "Browse all templates" button on Gutenberg's trunk branch currently leads to the wp-admin templates post management screen.

That sucks, the nav sidebar is such a better experience imo. Now we have to eat the loading cost of the editor so much more frequently :/

**Comment by Addison-Stavlo** [comment]
> That sucks, the nav sidebar is such a better experience imo. Now we have to eat the loading cost of the editor so much more frequently :/

I agree, but hopefully we wont have to eat too much editor loading in the end.  Other navigation patterns are being explored, such as this WIP PR for a mosaic view selection interface for templates: https://github.com/WordPress/gutenberg/pull/33770

**Comment by vindl** [comment]
This is no longer an issue since Core introduced a new Browsing Sidebar and full-screen template selector. We are exposing it as-is on WP.com now, meaning that Browsing Sidebar is again accessible via the W button.
