### ISSUE TITLE
Jetpack linked sites are not showing up in some views on Calypso dashboard

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#57295]
### Quick summary

Jetpack linked sites are not showing up in the list of sites at https://wordpress.com/home

But it is showing up on other views like this: 
* https://wordpress.com/media
* https://wordpress.com/settings/general

### Steps to reproduce

1. Create a WPORG site. You can use https://jurassic.ninja/
2. Connect it to your WordPress.com account.
3. You can see the site is showing in the list under My Sites and views mentioned about, but not in https://wordpress.com/home

### What you expected to happen

I expected sites list to be consistent across all views

### What actually happened

The Jetpack sites are missing from https://wordpress.com/home

### Context

Chat interaction: 32244628-hc

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Users will have to check under My Sites or other views.

**Comment by dpasque** [comment]
Switching over to @Automattic/flow-patrol-create for the time being because it seems to be affecting the My Home page.

**Comment by ivan-ottinger** [comment]
The issue is caused by the following filter condition:

https://github.com/Automattic/wp-calypso/blob/b019e5848b267df5de134270fe1175a59b8292bc/client/my-sites/sites/index.jsx#L59-L62

introduced in https://github.com/Automattic/wp-calypso/pull/39090.

What happens here is that the whole pool of sites is filtered and as the condition `! site.is_vip && ! ( site.jetpack && ! site.options.is_automated_transfer )` returns `false` on every Jetpack site, it is being filtered out from the display.

I will take a closer look to see how this can be fixed.

Update: I have a working solution and will publish PR tomorrow.

**Comment by ivan-ottinger** [comment]
Just noting here for clarity that the issue has been fixed in https://github.com/Automattic/wp-calypso/pull/57952.
