### ISSUE TITLE
Unable To Insert Videos Into Cover Blocks on Atomic Sites

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#57299]
### Quick summary

The cover block does not display videos added to it. Images work but videos do not.  

### Steps to reproduce

1. On an atomic site, add a cover block.
2. Click Add Media.
3. Upload a video or select a video from your media library.
4. The video is not added. You get a blank dark box where the video is supposed to be. 

### What you expected to happen

To see the video inserted in the cover block as you do on simple sites.

### What actually happened

I got this black/grey-ish box
<img width="1018" alt="Markup 2021-10-23 at 18 53 59" src="https://user-images.githubusercontent.com/74204272/138575777-27f85719-54e9-492b-8e8f-f9f76a087d0f.png">

### Context

User in 31346211-hc complained that the cover block was not displaying videos.

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

A workaround is using the video block to insert the video but it is not the best workaround for users who want videos inserted in the cover block.

**Comment by kuropixel** [comment]
Additional user report: 4405030-zd
I was also able to reproduce this on a test Atomic site.

Videos don't display at all.

https://user-images.githubusercontent.com/83020905/138821910-43957c46-e7fe-404a-b95a-f902379ff411.mov

 
Initial upload shows them briefly in cover block for a second, then back to black.
Attached a screen recording.

**Comment by Robertght** [comment]
Thank you for reporting this!

I cannot replicate this one on my end yet. 

@kelasante @kuropixel Are you using it with a specific theme?

**Comment by kuropixel** [comment]
@Robertght In my test, I was using the theme "Toujours".

**Comment by dpasque** [comment]
Because it's also media, also adding the Manage label in case they have an idea what might be causing this.

**Comment by JoshuaGoode** [comment]
This is due to recent VideoPress changes.

For WordPress.com on Atomic sites, the site must be public or coming soon with VideoPress enabled. The video must be uploaded to and transcoded by VideoPress recently. The output file should be a .m3u8 playlist file instead of .mp4.

#### Workarounds

Workarounds include setting the `videopress-legacy-transcode` sticker on a site and reupload the video. Or, bypass VideoPress and use the site's storage by uploading to `/wp-admin/media-new.php`

Issue where this is being discussed and tracked: 994-gh-Automattic/greenhouse

**Comment by cometgrrl** [comment]
Closing as linked issue 994-gh-Automattic/greenhouse is closed.
