### ISSUE TITLE
Login page: Blank screen on mobile screens for older iOS devices

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#57379]
### Quick summary

This seems to be similar to https://github.com/Automattic/wp-calypso/issues/34003 but this case had way older iOS versions mentioned.

### Steps to reproduce

This was reported here: p1635250937073200-slack-C01UW7SB411 ( iPhone 6, iOS 12.5.5)

It was replicated with Browserstack as well

![image](https://user-images.githubusercontent.com/6737345/139024886-1e945896-79f7-48ae-a2e2-7255ab43fc58.png)

### What you expected to happen

To have it showing up the login fields

### What actually happened

Only the WordPress logo showed up

### Context

4402192-zen

### Operating System

iOS

### Browser

Google Chrome/Chromium, Apple Safari

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

no

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by simison** [comment]
@Automattic/team-calypso by chance this is old browser support issue similar to IE11?

**Comment by WunderBart** [comment]
I was able to reproduce with Borwserstack up to Safari v12 (iOS v12.3). It's OK for Safari v13 and higher. Here are the errors I'm seeing:

<img width="1034" alt="Screenshot 2021-10-27 at 11 26 11" src="https://user-images.githubusercontent.com/1451471/139040247-fe334796-c801-4030-9ad9-142ac6a9c1eb.png">

According to our `evergreen` setup, we're supporting only the [last two versions of iOS Safari](https://github.com/Automattic/wp-calypso/blob/d055311bf64b6bcc118570e60988526bebda592e/package.json#L33). Latest version is v15, so it would correctly mean the v13 and below might not work correctly. Having said that, maybe we should be showing the `browserhappy` page for iOS Safari v12 and below now that we know it has issues? cc @noahtallen

**Comment by jsnajdr** [comment]
Accidentally, we are being even stricter with supported Safari versions. "two versions" doesn't mean major versions, but just ... versions.
```
$ npx browserslist "last 2 Safari versions"
safari 14.1
safari 14
$ npx browserslist "last 2 iOS versions"
ios_saf 14.5-14.7
ios_saf 14.0-14.4
```
Safari 15 is not listed at all because in Calypso the `caniuse-lite` package with the database it not yet updated to the latest version.

We should decide which versions of Safari do we really want to support and then patch the `browserslist` specs accordingly.

**Comment by jamiepalatnik** [comment]
User report: 4402192-zd-woothemes

I can recreate this on my own device (iPhone 6, iOS 12.5.5) on Safari and Chrome.

**Comment by noahtallen** [comment]
The reason it isn't getting the "unsupported browser page" is because we are allowing public pages, like `log-in`, to be accessed by anyone regardless of browser support. The WSOD is because the bundle _actually_ doesn't work in the browser, since it doesn't support modern ES syntax.

Since we (including the WordPress org in general) have decided to stop supporting browsers which don't support modern ES (specifically IE 11), I don't think we intend to support the Safari version from iOS 12. Unless we reverse that decision! But that would also mean supporting older ES in our bundle, and probably re-introducing multiple bundles...

I think the action here is to make sure that we show the "unsupported browser" message on these devices, and we are currently exploring that here: p9oQ9f-MJ-p2

**Comment by noahtallen** [comment]
> On Wednesday, October 27, 2021, 11:01 PM Noah Allen <
***@***.***> wrote: 

@JACKsparo0 I think you may have forgotten your message :)

**Comment by karenroldan** [comment]
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Low` to better reflect its status in the larger context of open bugs in this repo.

**Comment by inaikem** [comment]
Closing as expected - we officially support the last two versions of Safari. Please repoen if needed.
