### ISSUE TITLE
Playwright: Fix mismatched screenshot names

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57436]
### Details

The pre-release tests have been recently using screenshot names that don't match the names of the test failures, which can make it confusing to associate screenshots/videos with test failures.

It might be a good idea to rework the artifacts directory so that it is also more obvious which tests belong to to which files.

See TeamCity builds 655 and 648.

**Comment by worldomonation** [comment]
This is going to be bit more of a complicated task, as we will need to look at [hooks.ts](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/hooks.ts#L66-L74) and determine why Jest is setting `__CURRENT_TEST_NAME__` to the last `it` step in the file instead of the actual failed test.

[environment.js](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/lib/jest/environment.js#L63-L66) that sets the variables.

Related: https://github.com/Automattic/wp-calypso/issues/56449.
