### ISSUE TITLE
FSE beta: add clarification to proxied only FSE beta toggle

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#57441]
Internal users often don't realize that `Appearance -> FSE beta` screen and toggle is not visible to normal users. To clarify this, we should add an `A8C only` tag to it and perhaps an explanation on the screen.

**Comment by Addison-Stavlo** [comment]
> To clarify this, we should add an A8C only tag to it 

Im wondering the best way to clarify this screen, keeping in mind the toggle is also visible to atomic and self hosted users running the ETK plugin.

If we aren't too worried about atomic/SH users reading this verbage: "Note: this toggle is not visible to simple site users on dotcom" or something similar.  Otherwise, maybe something a bit more clever? 🤔

**Comment by Addison-Stavlo** [comment]
Closing as this toggle DNE anymore
