### ISSUE TITLE
[Bug]: broken Crowdsignal nudge at sidebar

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#57498]
### Quick summary

On my fresh Atomic sites on a business plan, I saw a nudge at sidebar:

![image](https://user-images.githubusercontent.com/87168/139661328-112052ce-e365-438f-963f-c585be53aa5a.png)

It leads to a broken page:

`https://wordpress.comhttps/mikaeltestingmailpoet.wpcomstaging.com/wp-admin/admin.php?page=crowdsignal-forms-settings`

### Steps to reproduce

1. Create business site, turn it Atomic by installing a plugin (not sure if AT site is required for bug)
2. Click on Crowdsignal banner

### What you expected to happen

Link to work

### What actually happened

:sad

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

cc @Automattic/crowdsignal hi, could you folks have a look at this? Thanks!

**Comment by digitalwaveride** [comment]
Thanks so much for the ping @simison ! 🙏 

I reached out to the Dinobots team, they manage this campaign.
cc @withinboredom

**Comment by withinboredom** [comment]
Ah, that's a very interesting bug. It appears it works if you click the banner from calypso, but is broken if you click the link in wp-admin.

**Comment by withinboredom** [comment]
This is likely related to the differences in how the JITM is parsed in javascript vs. php. I'll see if I can figure something out.

**Comment by withinboredom** [comment]
I'm going to disable the jitm for now until we reach a better solution for handling this: pd0D4C-bj-p2#comment-637

**Comment by Copons** [comment]
I'm reopening this issue since it's indeed related to Nav Unification.

I'm still learning how to properly test stuff across WoA/JP/JITM and the likes, but I managed to backtrack the issue and found out how the situation diverges between Calypso and wp-admin.

### Why does it work in Calypso?

In a nutshell, the WPCOM sidebar consists of two main parts: the admin menu and the current site section.
The Nav Unification unifies **both** across Calypso and wp-admin, by (basically) recreating the wp-admin admin menu in Calypso, and the Calypso current site in wp-admin.

<img width="500" alt="Screenshot 2021-11-03 at 18 12 16" src="https://user-images.githubusercontent.com/2070010/140168374-ef8466b1-74da-43da-84d0-e1df1f9362c5.png">

_Artist's rendition of the Nav Unification process._

In Calypso this happens by requesting via API the site's wp-admin admin menu, and rendering it below the current site section.
In other words, in Calypso, the current site section is not part of the Nav Unification but [of Calypso itself](https://github.com/Automattic/wp-calypso/blob/ebc6af0283fdfaee1533d4b42bd15ebfd223b519/client/my-sites/current-site/notice.jsx#L265-L272) and... there's just not much else to say about it. 😄 

### What Happens in wp-admin?

In wp-admin, the Nav Unification basically rebuilds its own original admin menu sprinkling all the WPCOM logic on top of it (no need for API calls in this case, it all happens server-side).
It also [recreates the Calypso current site section](https://github.com/Automattic/jetpack/blob/4fe0df95dd0af0b1d61ac6f184f0ca12fd71cd9f/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L70-L80) (link to the Atomic version for convenience), and puts it on top of the rebuilt admin menu.

This practically means that the way JITM nudges are rendered in wp-admin is completely different than Calypso.

In the wp-admin version of Nav Unification, [if the site has JITM nudges](https://github.com/Automattic/jetpack/blob/4fe0df95dd0af0b1d61ac6f184f0ca12fd71cd9f/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L74-L77) it will call [`add_upsell_nudge()`](https://github.com/Automattic/jetpack/blob/4fe0df95dd0af0b1d61ac6f184f0ca12fd71cd9f/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L110-L134).

And, finally, `add_upsell_nudge()` **[hardcodes `https://wordpress.com` to the nudge link](https://github.com/Automattic/jetpack/blob/4fe0df95dd0af0b1d61ac6f184f0ca12fd71cd9f/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L132)**, causing the issue we have here.

**Comment by Copons** [comment]
I've moved this to our team's current iteration (which is partly busy on a different project) and set it to high priority because this is currently blocking another team's JITM campaign for Crowdsignal.

**Comment by mmtr** [comment]
I opened https://github.com/Automattic/jetpack/pull/21821 to solve the issue with the hardcoded `wordpress.com` in the JITM URL. Once that's shipped, we should be able to enable the Crowdsignal JITM again.

**Comment by dsas** [comment]
Just to note that this JITM will not be dismissible at present, because the sidebar implementation doesn't currently render a dismiss button. Once that's added, which I intend to work on next week, it will be. 

If this shouldn't be dismissible we'll need to add `is_dismissible( false );` to the message, if it should be dismissible (which I assume is the case), we don't need to do anything.

**Comment by mmtr** [comment]
Just merged the fix to avoid this issue in future JITMs. Not sure if we want to keep this issue open though, in case we want to track that the Crowdsignal JITM needs to be enabled again.

**Comment by Copons** [comment]
I'll close this issue as the bug has been long since fixed, and the current Crowdsignal JITM work is being tracked in pd0D4C-ju-p2.
