### ISSUE TITLE
Flaky E2E: Close account

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57513]
### Spec file

wp-signup__domain.ts

### Suite or step

Close account

### Framework

Playwright

### Logs

Logs:
```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "text=These items will be deleted" to be visible
============================================================
at AccountSettingsPage.closeAccount (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/me/account-settings-page.ts:45:19)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at CloseAccountFlow.closeAccount (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/close-account-flow.ts:33:3)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-signup__domain.ts:136:4)
```

Run: 6916825

![wp-signup__domain-close-account](https://user-images.githubusercontent.com/6549265/139732252-d94506ca-fcde-4822-88e7-531632fab78a.png)

**Comment by worldomonation** [comment]
Context: Only on Signup: Domain flow.

Suspect it has to do with domains taking some time to 'provision' even if it's a fake purchase in the sandbox system, so by cancelling the domain purchase almost immediately after it is made the system still thinks the user has the domain active.

Reason for the hypothesis: if I log in to the test account after some time using a real browser, the domain no longer shows up on the account and user is able to close the account.

**Comment by worldomonation** [comment]
@dpasque I feel like this is a case where we should try the use of an arbitrary `waitForTimeout` despite all its drawbacks. I think waiting 10 seconds after cancellation of the domain purchase could be useful here.

Alternatively, we quarantine this spec and discontinue running it as part of the PR build.

**Comment by dpasque** [comment]
> cancelling the domain purchase almost immediately after it is made the system still thinks the user has the domain active

Yeah - this has always been my experience when I was working with this spec - it just needs more time!

> I feel like this is a case where we should try the use of an arbitrary waitForTimeout despite all its drawbacks.

I think this could work!

Alternatively though, what do you think of perhaps a looping mechanism that refreshes the page after a second, looks for an element, then refreshes again, all with a timeout? I've thought it might be worth having a modularized library function for doing something like this - basically our own `waitForSelector` implementation that uses page refreshes to look for something.

It would be a bit more work, but I think it would make our test more stable and reliable in the long run. I always prefer to wait for _something_ rather than just time.

But, if that's too clunky, I think having a brief delay could get the job done! Honestly, I think even 5 seconds would be enough!
