### ISSUE TITLE
Jotform link does not show in stats when clicked

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#57552]
### Quick summary

A user reported that when visitors click on a button on their site leading to a Jotform (form is not embedded), those clicks are no longer counted. They report that they were previously counted. 

I tested this on my own site. I created two buttons on a single post. One linked to YouTube and one to Jotform. Clicks on the YouTube button were counted in my stats. Clicks on the Jotform button were not counted. 

Report: 4420003-zd-woothemes

### Steps to reproduce

1. On a simple site, add links to a Jotform using a button.
2. Click that button from a non-logged in browser window.

### What you expected to happen

Clicks for the Jotform link should show in the clicks section of stats. 

### What actually happened

Clicks for other buttons on the same page show in stats. The Jotform clicks do not show in stats. 

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

N/A

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by ivan-ottinger** [comment]
Initial investigation:

- There was a similar case discussed in p56BUd-k3-p2 where the issue was likely caused by the tracked URL being blocked by Akismet. I have checked whether `form.jotform.com` (used in JotForm forms) is blocked and it doesn't seem to be the case here. Double-checking with Akismet: p1636449777156600-slack-C029E4HPT
- Clicks to the root `jotform.com` are tracked properly.
- Track is being triggered correctly, `pixel.wp.com/c.gif` is firing every time we click on the JotForm link
- The stats data fed to Calypso are already missing the URL.

It is not yet clear where the issue is coming from.

**Comment by ivan-ottinger** [comment]
At the end no code change was necessary. The links at `form.jotform.com` were incorrectly blocked by Akismet. Everything is working as expected now. We can let the user know @sajmes. :)

Screenshot from the Stats on my test site:
![Markup on 2021-11-10 at 14:56:40](https://user-images.githubusercontent.com/25105483/141126114-dc99ec68-b603-4e7a-ae77-245c9682ffb9.png)
