### ISSUE TITLE
Can't Add New Pexel Images When Updating Gallery

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#57611]
### Quick summary

When I try to add Pexel images in the old Gallery block (and the new), I only get to choose one search result for images. For example, I wanted to add some snow pictures then some summer images. After I added the snow, I was not given an option to add images from another search. There was no longer a Pexels option.

### Steps to reproduce

Add a Gallery block.
Choose "Select Images."
Select Pexels Free Photos. 
Search a topic and add images.
Notice there is no longer an option to "Select Images." The only options are Upload and Media Library.
Click Media Library and notice there is still no Pexels option.

My gif is too big to upload, but it's set to public and to last forever on https://d.pr/i/9aL7wW

### What you expected to happen

Pexels would be an option when adding more images.

### What actually happened

It wasn't.

### Context

My own testing while updating support pages.

### Operating System

macOS

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Not theme specific

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Add the Pexels to your media library then add them to the gallery.

**Comment by nelsonec87** [comment]
The fact that is not possible to add new pictures to existing galleries is due to a limitation in the way this feature was implemented: the MediaPlaceholder o[nly passes the images' IDs](https://github.com/WordPress/gutenberg/blob/c711a16dbfd3858fecb1bbb306ad0962bb26d19a/packages/block-editor/src/components/media-placeholder/index.js#L356), but [the Gallery passes the whole objects](https://github.com/WordPress/gutenberg/blob/c711a16dbfd3858fecb1bbb306ad0962bb26d19a/packages/block-library/src/gallery/edit.js#L369).

The original issue and PR with further details can be found [here](https://github.com/Automattic/jetpack/pull/16176) and [here](https://github.com/Automattic/jetpack/pull/16176).

It also has an easy workaround, so I'm closing the issue.
