### ISSUE TITLE
Add SVG support in Calypso

### ISSUE THREAD

**Issue by mrsjaved** [Automattic/wp-calypso#57634]
### What

Ability to add SVG support in Calypso from My Sites -> Media library.

### Why

A user was using the SVG support plugin but they were unable to upload the SVG file from My Sites -> Media -> Add New. 

It works from WP - Admin -> Media but a bit confusing because users does not know the difference and expect it to work the same. When it does not, it creates confusion and frustration.  

### How

Related ticket: 4422551-zd-woothemes

**Comment by kosiew** [comment]
Hi @mrsjaved ,

Thanks for reporting this.

We do not allow SVG upload due to security risks.

Here are some related references:

https://blog.online-convert.com/svg-file-and-its-danger/

p9zhOE-Ka-p2#comment-5775

If Customer makes a similar request, please advise of the risk and dissuade them or inform them of the necessary safety precautions to sanitize SVGs.

Closing.
