### ISSUE TITLE
Themes: Details page fails to load on IE11

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#5766]
#### Steps to reproduce
1. Using IE11
2. Starting at URL: https://wpcalypso.wordpress.com/design/
3. Choose a theme and click the ellipsis, then Details

#### What I expected
The details page to load

#### What happened instead
The URL https://themes/ is opened, which fails to load

#### Browser / OS version
IE 11.0.9600.18163 on Windows 7

#### Screenshot / Video
![themes-ie11](https://cloud.githubusercontent.com/assets/7233112/15758289/df01cc24-28d7-11e6-943a-c990295a0574.gif)

**Comment by seear** [comment]
Investigating. Very odd so far. For links in the ... button, there seems to be an extra slash char prepended to the href target, which is causing a 'security error' in IE11 when page.js calls `pushState()`:

<img width="239" alt="screen shot 2016-06-06 at 14 25 26" src="https://cloud.githubusercontent.com/assets/7767559/15823432/90bdbde8-2bf2-11e6-9676-de06c333e2d0.png">

<img width="321" alt="screen shot 2016-06-06 at 14 25 05" src="https://cloud.githubusercontent.com/assets/7767559/15823436/94ad90c2-2bf2-11e6-81d9-f133007f7bbe.png">

**Comment by seear** [comment]
In IE11 (only), for a js `onclick` event on an `<a>` tag in a modal window, the event param passed to the handler has an extra slash prepended to `target.pathname`.

So, for example '/themes/mood' becomes '//themes/mood'

The page.js router accesses `pathname` and attempts to route to that incorrect address:
https://github.com/visionmedia/page.js/blob/aa605501e240727a0afaef7ec1641f60c8d7e8a5/index.js#L581

This is possibly related to a fix in IE for a *missing* slash in modal links:
https://connect.microsoft.com/IE/Feedback/Details/1002846

Seems unlikely this will ever be fixed in IE.

We could submit a patch to page.js that works around, or wait it out until we drop support for IE11 (this is not a problem in Edge)

**Note**: this affects all Calypso links in the [`<PopoverMenu/>`](https://github.com/Automattic/wp-calypso/tree/master/client/components/popover) component, which is used by the editor and the reader.

PR #5855 is a workaround _only_ for the theme '...' menu, to limit the scope of the testing.

**Comment by ockham** [comment]
> In IE11 (only), for a js `onclick` event on an `<a>` tag in a modal window, the event param passed to the handler has an extra slash prepended to `target.pathname`.

> So, for example '/themes/mood' becomes '//themes/mood'

Not sure I'm reading you correctly, but the 'Details' item only has an `href`, no `onClick` handler?

**Comment by seear** [comment]
> Not sure I'm reading you correctly, but the 'Details' item only has an href, no onClick handler?

Yeah, sorry, (I'm assuming that) page.js hooks into every click to do the routing. Problem is in page.js `onClick` handler here:
https://github.com/visionmedia/page.js/blob/aa605501e240727a0afaef7ec1641f60c8d7e8a5/index.js#L541

**Comment by ockham** [comment]
This seems to have been fixed by the React 15 upgrade (#5116) 🎉 so I'm closing this issue. To verify, just test with `wpcalypso`, staging, or in development on the `master` branch. If -- contrarily to what I'm seeing -- the issue persists, please re-open :-)
