### ISSUE TITLE
Plugin Details: Update plugin author link to redirect to a WP.com page showing all plugins of the selected author

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#57749]
Update plugin author link to redirect to a WP.com page showing all plugins of the selected author

We should parse the author from the `author_profile: https://profiles.wordpress.org/takayukister` field eg `takayukister` and use it in the `https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request[author]=takayukister` endpoint which will return all plugins that this author is a contributor.

We will need to optionally add the `author` parameter (like `search` parameter) here 
https://github.com/Automattic/wp-calypso/blob/b019e5848b267df5de134270fe1175a59b8292bc/client/lib/wporg/index.js#L55-L60

![SS 2021-11-08 at 16 45 58](https://user-images.githubusercontent.com/12430020/140762773-29cba0ec-7a5f-457d-b7e8-0cc96e09d38d.png)

- [ ] Implement author search
<img width="1009" alt="SS 2021-11-25 at 14 56 55" src="https://user-images.githubusercontent.com/12430020/143445781-669243e4-2705-4de0-8612-d7d4759689c8.png">
- [ ] Redirect to that URL from plugin details page.

**Comment by gcsecsey** [comment]
As this issue currently has low priority, it's not certain that we will pick this up in the following sprint. In the previous sprint, I've been working on getting the author name from the search string reliably. 

I've created a regex pattern that returns any string that's between quotes and after the author: prefix. Eg.: for `author:"Automattic"` it will produce `Automattic` as the author name. The quotes here are needed because – looking at the WPOrg plugins – the author name often contains two or more words, and it would be hard to separate the author name from the search string otherwise.

I've also added the `author` field to the WPOrg request, and it's being sent correctly.
```
https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request[page]=1&request[per_page]=24&request[fields]=icons,last_updated,rating,active_installs,tested,-downloaded,-ratings,-requires,-requires_php,-tags,-contributors,-added,-donate_link,-homepage&request[locale]=en_US&request[browse]=all&request[author]=Automattic
```
![image](https://user-images.githubusercontent.com/11555574/151842607-77cf225d-ca7b-4019-991b-8756b863d1c6.png)

However, the search string is still passed to the WPCom Marketplace API without modification, and it causes that request to fail:
```
https://public-api.wordpress.com/wpcom/v2/marketplace/products?_envelope=1&q=author:"Automattic"&type=all
```
![image](https://user-images.githubusercontent.com/11555574/151842911-98babf11-1885-431f-b066-46367b644854.png)

These changes are in the draft PR that I've linked to the issue.

The outstanding tasks on this ticket are:
- [ ] Pass the author field's value to the WPCom API request and remove it from the search query, similarly to the WPOrg request
- [ ] Update the author link on the plugin details page to redirect to the search page with the author's plugins

We've agreed on today's planning meeting to reduce the estimate to 2 points.

**Comment by WBerredo** [comment]
WPCom - Search by author: D74695-code
Calypso - Search by author: https://github.com/Automattic/wp-calypso/pull/60679
Calypso - Redirect author link to a page inside calypso with plugins of a given author:  https://github.com/Automattic/wp-calypso/pull/60977

**Comment by WBerredo** [comment]
Changeset deployed at WP.com: r240456-wpcom
