### ISSUE TITLE
Marketplace: Extensions icons

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57751]
While trying to implement the figma designs (oU6nEIeiKSg8CayhEtgR6b-fi-6693%3A53273) we have stumbled into an inconsistency. 

![SS 2021-11-08 at 16 48 18](https://user-images.githubusercontent.com/12430020/140763243-c9788aa3-926a-4072-88fd-85a66258099b.png)

The WOO extensions icons are not square eg [https://woocommerce.com/wp-content/uploads/2020/06/Logo-Woo-Subscriptions-Dark.png?fit=300,200](https://woocommerce.com/wp-content/uploads/2020/06/Logo-Woo-Subscriptions-Dark.png?fit=300,200) while WP.org plugins have square icons eg [https://ps.w.org/contact-form-7/assets/icon-256x256.png?rev=2279696](https://ps.w.org/contact-form-7/assets/icon-256x256.png?rev=2279696).

It seems as we have add a grey bg to WOO extensions only. It would be great if we could find a common rule for both icons. Does it worth creating new square icons for the WOO extensions? Another note is that icons look the same in the plugin browser list

![SS 2021-11-08 at 16 53 10](https://user-images.githubusercontent.com/12430020/140764141-cab77189-5a2c-472c-968d-66ce041706c4.png)

**Comment by SaxonF** [comment]
Hi @cpapazoglou! Saxon from the design team here. Just so that we aren't blocked I think standardising on square icons (without dictating background) makes sense for now. I'll reach out to the Woo design team to see if there are other icons we should be using for their sub products that work at smaller sizes. In the meantime, I've created a set of square icons with a solid grey background for you.
<img width="187" alt="addons" src="https://user-images.githubusercontent.com/1072756/142138559-e9d63bfa-422f-4595-b35d-6a4f042ae0da.png">
<img width="187" alt="automate" src="https://user-images.githubusercontent.com/1072756/142138563-79119400-5cb9-45ef-8f5f-fd703e8039c2.png">
<img width="187" alt="bookings" src="https://user-images.githubusercontent.com/1072756/142138565-b52e4e2e-6f98-4597-9e68-d3e475e221f8.png">
<img width="187" alt="boxoffice" src="https://user-images.githubusercontent.com/1072756/142138570-2204d504-e847-4959-a804-e7880c578960.png">
<img width="187" alt="shipping" src="https://user-images.githubusercontent.com/1072756/142138574-7d66eaa4-b12e-4ce2-9472-838e80d56e3d.png">
<img width="187" alt="subscriptions" src="https://user-images.githubusercontent.com/1072756/142138577-74582835-8f7f-4938-9203-da5028d66a4e.png">
<img width="187" alt="tablerate" src="https://user-images.githubusercontent.com/1072756/142138579-996e85bd-8c9b-4961-a97c-e7349ffa6aa3.png">
<img width="187" alt="tax" src="https://user-images.githubusercontent.com/1072756/142138581-6c2d2bf8-78c1-4dc4-b565-10364d021eb2.png">
<img width="187" alt="tracking" src="https://user-images.githubusercontent.com/1072756/142138585-059ee78a-8d54-46b9-8b32-129a666d7487.png">

**Comment by cpapazoglou** [comment]
That's great @SaxonF, thanks!

@gavande1, can we pick up this issue in our next sprint and use the provided icons in the API response?

**Comment by cpapazoglou** [comment]
@gavande1 saving the images to `wp-content/lib/*any_folder*` should be enough. You will need to sandbox `wordpress.com` to test it.

![SS 2021-11-23 at 15 21 02](https://user-images.githubusercontent.com/12430020/143031509-ed3457e1-83a8-4161-a704-f5140dae6fa1.png)

**Comment by cpapazoglou** [comment]
Related diff D70833-code

**Comment by cpapazoglou** [comment]
Deployed r235874-wpcom
