### ISSUE TITLE
Marketplace: Subscription removal / expiration

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57755]
Make sure that plugin is removed when subscription is removed / has expired and users can't re-activate it.

**Comment by cpapazoglou** [comment]
@gavande1 had you made any progress in researching this?

**Comment by gavande1** [comment]
### How the deactivation will work?

1. Handle expiry using event life cycle method `deactivation` of `Store_Product_Marketplace_Plugins`

2. Use method `manage_software` API of `WPCOM_Atomic_Service` class to remove the plugin. 
we need to format params as follows: 
```php
$software = [
    'plugins/{SLUG}'  => 'remove',
];
```

### Questions

1. Let’s say the subscription expired and we removed the plugin. The user comes back and says, here is the money! please restore my plugins and data (Assuming removing the plugin will remove the DB table & data).  How do we do it? Do we want to even do that? Any alternative way to approach?
2. Let say we install WooCommerce along with WooCommerce Subscriptions. The user also installed a free plugin (https://wordpress.org/plugins/facebook-for-woocommerce/) which is also dependent on WooCommerce. So when the subscription expires, It doesn’t make sense to remove the dependent plugin WooCommerce. Should we attempt to remove WooCommerce in this case? Or keep it as it is? The problem is how do we detect if there is any such plugin installed?

**Comment by cpapazoglou** [comment]
> Use method manage_software API of WPCOM_Atomic_Service class to remove the plugin.
we need to format params as follows:

Should we first `deactivate` the plugin so that any deactivation hooks run? 

> 1. Let’s say the subscription expired and we removed the plugin. The user comes back and says, here is the money! please restore my plugins and data (Assuming removing the plugin will remove the DB table & data).  How do we do it? Do we want to even do that? Any alternative way to approach?

Can you confirm that plugin removal does indeed remove DB tables & data? If it doesn't remove data, then the only problem would be in cases that we would want to downgrade the site to Simple and in those cases the data are indeed lost.

> 2. Let say we install WooCommerce along with WooCommerce Subscriptions. The user also installed a free plugin (https://wordpress.org/plugins/facebook-for-woocommerce/) which is also dependent on WooCommerce. So when the subscription expires, It doesn’t make sense to remove the dependent plugin WooCommerce. Should we attempt to remove WooCommerce in this case? Or keep it as it is? The problem is how do we detect if there is any such plugin installed?

I don't feel there is a need in removing plugin dependencies, except if they are also paid expired plugins.

**Comment by gavande1** [comment]
The diff created at: D70920-code

**Comment by gavande1** [comment]
🚀 deployed r236373-wpcom
