### ISSUE TITLE
Preview of Draft posts returns 404 error 

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#57812]
### Quick summary

Similar to these previous cases:

https://github.com/Automattic/wp-calypso/issues/54107

https://github.com/Automattic/wp-calypso/issues/57011

### Steps to reproduce

In theory, we should be able to replicate by following these steps:

1. Create a draft post.
2.  Try to preview it in a separate window

This doesn't happen on my test site, but I found a few that were affected last week.

### What you expected to happen

To see the preview without an issue

### What actually happened

I got a 404 page instead

### Context

4432206-zen
4430152-zen
4418811-zd-woothemes
4429496-zen

### Operating System

Windows, macOS

### Simple, Atomic or both?

Simple

### Theme-specific issue?

no

### Other notes

I can only replicate on their site while SSP'ing.

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

I suggested the users to use the Preview option from the Pages section instead and that worked.

![image](https://user-images.githubusercontent.com/6737345/140874953-8da12557-b94f-4bcb-8901-ef4f376aad40.png)

**Comment by edwinho89** [comment]
I'm seeing a pattern.. I had a few chats having similar issue when they're on `Safari 15.0, Mac OS X 10.15.7` (or older)

32601554-hc
32539363-hc

Switching to another web browser like Chrome, or updating to the latest OSX appeared to have fixed it.

**Comment by kerrynicl** [comment]
Here's another report - ZD- 4439905

Additional info- 
User confirmed workaround worked 
User Shared info - I’m on OS 11.5.1 on Safari 14.1.2. - Advised user to update browser and OS

**Comment by jp-imagines** [comment]
Another report in 4438942-zd.

**Comment by kerrynicl** [comment]
Another report - ZD 4444438. - 

Additional info 
Uer confirmed workaround stated above worked
The device I’m using is an Ipad, 8th generation, version 14.0, model nb MYLD2NF/A, and I use Safari as browser but I just tried to use Chrome and the issue is the same on that browser too. I’ve also noticed some changes when using certain features. Sometimes, I have to re-do what I was trying to create like for example when using the button call to action. The display wasn’t good so I had to re-do the same steps three times to get the desired outcome. I don’t know what’s happening because the Ipad I use is quite recent. It was released last year in October so the device cannot be outdated. Plus, the updates are made automatically.

**Comment by msilbers** [comment]
reported in 32669140-hc

Recommended the same workaround to preview from the pages or post list

**Comment by kerrynicl** [comment]
Also another report here : 
4445021 - ZD 
4444797 - ZD

**Comment by nickpagz** [comment]
Noting this happened in this interaction as well:
27140549-hc

In this case the user is on Chrome 96:
https://www.whatsmybrowser.org/b/XRX1U

Full user agent is `Mozilla/5.0 (X11; CrOS x86_64 14268.25.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.33 Safari/537.36`

I'm asking the user to test on another browser.

**Comment by arinoch** [comment]
4445021-zd-woothemesprovided more info. They're on Windows 10 with Chrome 95, they've also tested in Edge. Same issue. Issue also appears to happen on pages. Suggesting they try with Firefox, but I'm leaning towards the workaround isn't in this case.

**Comment by AtrumGeost** [comment]
The user here: 4441486-zd-woothemes

Pointed out they ran some tests and the issue only happens when trying to preview with the custom domain (ex. `custon-domain.com/?p=3964&preview=true`), but if they use the free WP.com address it works (ex. `custom-domaim.wordpress.com/?p=3964&preview=true`)

**Comment by rw-ye** [comment]
4453017-zd-woothemes

The user tried using Safari 15 and Firefox 94:
https://www.whatsmybrowser.org/b/1B77J
https://www.whatsmybrowser.org/b/QXFC4

Suggested the workaround for now.

**Comment by jp-imagines** [comment]
Another report: 31344553-hc. Chrome 95.0 on Windows 10. Suggested the workaround.

**Comment by ccwalburn** [comment]
Another report here: 32763305-hc
Only happens with Scheduled posts.
Firefox 94 on Windows 10 - preview doesn't work from the editor (they get an "Oops! That page can’t be found." error), but the workaround works
Chrome - preview works in the editor and with the workaround

**Comment by jp-imagines** [comment]
Another report in 12785399-hc, Safari 15.0 on Mac OS X 10.15.7.

**Comment by annbingle** [comment]
Another one reported in this ticket - 4461543-zd

**Comment by retnonindya** [comment]
4461543-zd-woothemes. Chrome 96 on Windows 10

**Comment by galakhyati** [comment]
Two instances of the issue where preview isn't working consistently:

#32792353-hc / Follow up: #4464377-zd-woothemes. Safari 14.1 on Mac OS X 10.15.7 
#32792307-hc / Follow up: #4464442-zd-woothemes. Firefox 94.0 on Windows 7.0.0

**Comment by jp-imagines** [comment]
Another in 32800528-hc, Safari 14.1 on Mac OS X 10.15.7. Showed them the workaround. Also suggested trying another browser or enabling third-party cookies, as they have them disabled. 

**User requested an email follow-up when this is fixed.**

**Comment by kerrynicl** [comment]
Another report - ZD- 4530198

**Comment by sharonlaker19** [comment]
+1 at 4551202-zen
User Agent: Mozilla/5.0 (iPad; CPU OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/96.0.4664.53 Mobile/15E148 Safari/604.1
Suggested workaround for now.

**Comment by manuelrebollo-a11y** [comment]
+1 at 4554141-zen
Suggesting workaround found above.

**Comment by metabreakr** [comment]
25548990-hc
Safari 14.1 on Mac OS X 10.15.7

**Comment by dolgelukkig** [comment]
One more: 32870674-hc

Safari version 14.1.2 (15611.3.10.1.5, 15611), Mac OS Catalina version 10.15.7

**Comment by metabreakr** [comment]
4560496-zen might be another instance, though am asking user for additional details such as browser information.

**Comment by aetta** [comment]
4564283-zen

Safari version 14.1.2, Firefox version 94.0.2, Mac OS Big Sur 11.6

**Comment by arinoch** [comment]
+1: 4563212-zd-woothemes

both Safari and Firefox. Having them try the workarounds listed above.

**Comment by arinoch** [comment]
... Aaaaand the workarounds for 4563212-zd-woothemes worked intermittently. If I'm reading the translation correctly, it only works if they edit a page. But if they edit the same page again, it doesn't work. Leaving this here for further investigation.

**Comment by as-esu** [comment]
4604166-zen
4575740-zen
Windows 10, Firefox 94
- They mention that when they update already published pages. Changes are not reflected when previewing published pages.
Suggested to preview option from the Pages section.

**Comment by ChrissiePollock** [comment]
Also happened in 4604011-zen.

**Comment by Robertght** [comment]
4571601-zen: 

>I emptied the cache and cookies and just now was able to "preview" my posts once again. I accessed it through Safari

**Comment by rw-ye** [comment]
Another report: 33214138-hc

Suggested workaround.

**Comment by gabriel-fuentes** [comment]
4614268 - zen

**Comment by gabriel-fuentes** [comment]
4610943 - zen

**Comment by arinoch** [comment]
33247207-hc - The issue was secondary to the reason this user came into chat, it was something they mentioned after I fixed their actual issue. Using Opera 82 on Windows 10.

**Comment by edwinho89** [comment]
24550100-hc - User is on Safari 15.1 on Mac OS X 10.15.7

**Comment by khristiansnyder** [comment]
Another report in #3078066-hc, but I have seen this a couple of times a week over the last several weeks as well. Preview works fine from the Posts section of the dashboard, but not in-editor.

**Comment by hacchism** [comment]
4671397-zen

Suggested workaround. Still trying to get the user's machine and browser info.

**Comment by msilbers** [comment]
reported in 27486484-hc and I could reproduce it using Mac OSX 11.4 and Chrome Version 96.0.4664.110

**Comment by mdtanjid0** [comment]
4681337-zen, I was not able to replicate the issue, but I have a couple of users today facing this issue.

**Comment by nagpai** [comment]
29915099-hc   
Safari browser with the usual allergy for cookies. 
https://www.whatismybrowser.com/w/SEA6TDZ

Worked after disabling the option `block all cookies` and ` prevent cross site tracking`

**Comment by mdtanjid0** [comment]
4681620-zen. 

Suggested workaround. Still trying to get the user's machine and browser info.

**Comment by IoanaAMuresan** [comment]
Another instance: 33778550-HC

**Comment by Greatdane** [comment]
Another; 33802091-hc

**Comment by rw-ye** [comment]
Another report: 4741959-zd-woothemes

**Comment by manuelrebollo-a11y** [comment]
New occurrence reported in Safari: 4756869-zd-woothemes

**Comment by rw-ye** [comment]
4760520-zd-woothemes

Suggested workaround

**Comment by ktyfuller604** [comment]
A report here 15847656-hc

Interesting note: When I gave them the direct link to the Preview option they were able to see the Preview, and when they went back to try to reproduce the issue (they thought they'd seen a different link in Preview), the preview worked for them.

**Comment by aetta** [comment]
4802697-zd-woothemes
Suggested above workarounds!

**Comment by Robertght** [comment]
#4798826-zen

**Comment by dev-sabbir** [comment]
Another one here: 4811187-zd-woothemes

**Comment by tellisbethel** [comment]
Another case here: 28554212-hc
Suggested user update their Safari browsers (on Macbook and iPhone 11) or try a different browser. 
(I couldn't reproduce the issue at all from Firefox.)

**Comment by ccwalburn** [comment]
Another case here: 34493754-hc
Browser: Safari
The workaround allowed them to see the preview, but they also discovered that unchecking the **Hide IP address from trackers** checkbox in the Privacy settings allowed them to view the preview from the editor as well. (note that we had already unchecked cross-tracking but unchecking that alone did not solve it)

**Comment by manuelrebollo-a11y** [comment]
Hello! I have a new report in 4838971-zd-woothemes
The suggested workaround is not helping this customer.

**Comment by philnick206** [comment]
New report: #34560418-hc
Gave them the workaround and that worked for them

**Comment by rickmgithub** [comment]
#4838971-zd 
Suggested workaround

**Comment by devNigel** [comment]
Another case: [34560418](34560418-hc)
Followup: 4843248-zen

Please follow up with the user on a new ticket once it is fixed.

**Comment by galakhyati** [comment]
Another case: 4862344-zen

Suggested workaround.

**Comment by manuelrebollo-a11y** [comment]
New occurrence in 4866570-zd-woothemes
I could not reproduce using a Support Session.
The customer decided to use the workaround on their own.

**Comment by edwinho89** [comment]
4902339-zd-woothemes

**Comment by edwinho89** [comment]
4911600-zd-woothemes

**Comment by ariel-maidana** [comment]
4913509-zd-woothemes
Provided the workaround.

**Comment by syds87** [comment]
4915932-zd-woothemes
Provided the workaround.

**Comment by rw-ye** [comment]
4935966-zd-woothemes
Workaround provided

**Comment by arinoch** [comment]
4936623-zd-woothemes

**Comment by dolgelukkig** [comment]
24842553-hc
Provided workaround

**Comment by sajmes** [comment]
35149867-hc 

Workaround provided.

**Comment by cintacks** [comment]
4944479-zd-woothemes

Same user as earlier in the issue thread is pinging again about a fix: https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-965134686

**Comment by wpshellbelle** [comment]
reported in 34342004-hc

Recommended the same workaround to preview from the pages or post list

**Comment by as-esu** [comment]
zen-4966789
provided the workaround

**Comment by dolgelukkig** [comment]
hc-32366897

provided workaround

**Comment by arinoch** [comment]
5181915-zd-woothemes

Provided workaround.

**Comment by philnick206** [comment]
5214612-zd-woothemes

Provided workaround.

**Comment by tavilla61** [comment]
5216414-zen
provided the workaround

**Comment by kimerlin81** [comment]
Another case: 5219096-zd-woothemes

Workaround did not work for this user on any browser (404), but providing them with the direct link for them to open in a new tab did.

Please notify them once this has been fixed. Thanks!

**Comment by wpshellbelle** [comment]
5218609-zen
Provided workaround

**Comment by tvolpert** [comment]
Another report here: 5223996-zen

Workaround was provided.

**Comment by jeyip** [comment]
Hi team -- @Addison-Stavlo and I started triaging this issue and had difficulty reproducing this problem. Like others have mentioned, we couldn't reproduce the problem with a support session ( we tried to on a site that had brought up this complaint https://andherestorethmysoulproject.org/ )

We also attempted to replicate things on one of our test sites under a variety of conditions ( with different permissions, with scheduled posts, with draft posts ) PdEeOA-t-p2

Wondering if anyone can provide concrete steps to reproduce so that we can continue our investigation.

**Comment by Robertght** [comment]
Another case in 5228330-zen.

It seems like this is happening on the upgraded site(klassiekvannu.com), but not on the free site(theaderks.wordpress.com).

**Comment by kuropixel** [comment]
5273262-zen

User was using Safari with 3rd party cookies blocked. I had them try enabling them but that also didn't work.
Suggested they try Chrome/Edge and also provided workaround.

**Comment by sajmes** [comment]
35811290-hc

Chrome. I could not replicate when SU so cannot provide steps to help replicate.

**Comment by jp-imagines** [comment]
- [ ] 5309681-zd-woothemes

Chrome/Safari on a Mac. Not able to replicate on my end.

**Comment by nicolynramos** [comment]
5333377-zd

Checked Firefox, Chrome and Safari on multiple devices and networks and all were affected. Gave workaround, would like update when fixed, if possible

**Comment by abcrsol** [comment]
Another case here: 5311940-zd. Firefox 101.0.1 (x64) is affected, but not Microsoft Edge, nor Chrome.

**Comment by abcrsol** [comment]
Another case here: 5339369-zd. No browser specified.

**Comment by villanovachile** [comment]
Another case here: 35949409-hc

**Comment by sajmes** [comment]
35490544-hc Safari.

**Comment by ktyfuller604** [comment]
30711073-hc

Using preview from the Posts list page worked. 

Firefox: 102.0
Opera: 88.0.4412.53 

OS: Windows 10

**Comment by metabreakr** [comment]
34332568-hc
Firefox 101.0 on Windows 10.0.0

**Comment by Robertght** [comment]
5350470-zen Windows 10 and Firefox 102. Clearing the cache didn't help.

**Comment by filipanoscampos** [comment]
Another one here 5351540-zd-woothemes.

If possible, please notify user once this is solved:

- [x] 5351540-zd-woothemes

**Comment by aetta** [comment]
+1 5355923-zd (Firefox)

Shared the workaround!

**Comment by jeyip** [comment]
I started taking a closer look at this again since we've free up some bandwidth. I'm consolidating potential causes of the issue below:

- Browser Problems noted [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-963872826) and [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-964428601). It should be noted that others could _not_ solve the problem by using different browsers like [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-965656202) and [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-965945442).
- Custom domain issues described [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-966614192)
- A scheduled posts problem written about [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-970305342)
- A Third party cookie noted [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-972915963), although another comment suggests that it might not be the case [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-1146934683)

Current Workarounds:
- Direct the user to the posts list page and preview posts from there
- Provide a direct link to the preview page

There's quite a bit to sort through 🤔 . [This comment](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-1047801860) stands out to me though.

> Interesting note: When I gave them the direct link to the Preview option they were able to see the Preview, and when they went back to try to reproduce the issue (they thought they'd seen a different link in Preview), the preview worked for them.

Would folks be able to slack me the url of the preview that's throwing the 404 for the user, as well as the url for the same user's site?

Before I dive into the weeds on this, I'm going to be reaching out to fellow devs to see whether or not someone has any hunches as to what the cause might be. To set expectations, this is going to be a particularly difficult issue to resolve without a reliable way to reproduce the problem, but we'll try our best to solve this asap!

**Comment by TPilgs** [comment]
Another instance here: 5355710-zd

User mentioned they were able to access the preview on their mobile and iPad but still nothing on desktop.

**Comment by ktyfuller604** [comment]
Another report: 5363611-zd

I asked them to share their browser/OS when I provided the workaround.

**Comment by wpshellbelle** [comment]
Another report at 8961853-hc
Provided workaround and this worked for them.

**Comment by ktyfuller604** [comment]
35919850-hc
Firefox 102.0 on Mac OS X 10.15.0

**Comment by Babylon1999** [comment]
One more here zd-5367245

Provided the workaround.

**Comment by synora** [comment]
Another one 34877036-hc
The workaround is also possible via wp-admin. 

The user also stated that the preview function within a post worked fine up until recently.

**Comment by wpshellbelle** [comment]
Another report at 35991878-hc
I was able to duplicate issue. Provided workaround and this worked for this customer.

**Comment by dhackneya8c** [comment]
Another report in 36061760-hc. Shared WP-Admin workaround

**Comment by fetenlakhal** [comment]
5376069-zd

**Comment by ktyfuller604** [comment]
26441629-zd

Firefox 83.0 on Windows 10.0.0

**Comment by Jaykame** [comment]
36080329-hc

Chrome Version 103.0.5060.114 (Official Build) (arm64). User is using Mac OS 12.4

I asked user to view their posts on the Classic view and that seem to did the trick for them.

**Comment by thekingsprojects** [comment]
Another case: 

- [ ] 5385041-zen / 360805570-hc

User went quiet before I could get browser details, but they mentioned using Safari.

**Comment by Babylon1999** [comment]
One more here: 5400889-zen

**Comment by pauljacobson** [comment]
We seem to have another report of this here:

- [ ] 5374786-zen

The user tried in Edge and Chrome on Windows. They shared details about their Edge browser here: https://www.whatsmybrowser.org/b/MF2TS

This use reported that this only seems to affect draft posts. They also mentioned something about Norton software, so I've asked for more information about this.

Is it possible that something like Norton could interfere with draft post previews only?

**Comment by Babylon1999** [comment]
Another case here: 5386158-zd

**Comment by KirkwallDay** [comment]
- [ ] 5402057-zen
What is my browser link:  https://whatismybrowser.com/w/H72QLGR  (Firefox 102, Max OS X 10.15)

**Comment by ktyfuller604** [comment]
- [ ] 5404339-zen

No additional details to provide

**Comment by Robertght** [comment]
5383032-zen

**Comment by jorpdesigns** [comment]
Reported in 36109966-hc. They are using Firefox and are unable to preview published posts too. I could reproduce.

Browser details: https://www.whatismybrowser.com/w/QZ3ATGL

Asked user to switch to Classic View and they could preview from there.

- [ ] Follow up created in 5407454-zen

**Comment by kelasante** [comment]
Another report in 18356650-hc. Shared previewing in Pages list instead.

**Comment by carinapilar** [comment]
Another one on 5413341-zd-woothemes - I'm able to replicate when accessing the account, on Chrome. Within the editor, it opens the preview with the custom domain, that's when we get the 404 error - the preview only opens when loading with the site's free address.

**Comment by ktyfuller604** [comment]
- [ ] 5418764-zd

* Provided Post List preview workaround.

**Comment by ktyfuller604** [comment]
- [ ] 5419140-zd

* Provided Post List preview workaround.

**Comment by JoshuaGoode** [comment]
Adding some of my notes from p9o2xV-2hz-p2#comment-6180

---

Seems similar to this 2019 report: https://github.com/Automattic/wp-calypso/issues/30145 and p58i-89x-p2

There was an attempt to fix it via https://github.com/Automattic/wp-calypso/pull/39859 

And a recent Firefox-specific report: https://github.com/Automattic/wp-calypso/issues/65755

I imagine it's easier to reproduce with Firefox, and Safari, due to their default security/cookie settings. 

Overall, seems like we're not proactively setting necessary cookies.

**Comment by JoshuaGoode** [comment]
Copying over info from #65755

---

From @edequalsawesome :


### Quick summary

Previewing a post on a Premium site with Firefox isn't working as expected -- I'm seeing a page not found error

### Steps to reproduce

1.  Create a site with the WordPress.com Premium plan on Firefox with a custom domain
2.  Create a new post, save as a draft
3.  Attempt to preview the post

### What you expected to happen

That I would be able to see the post preview

### What actually happened

I was taken to a 404 page

### Context

5377841-zen

I was originally able to duplicate this on my test site, but for some reason haven't been able to since my initial test -- I've been able to do this reliably when SSP'd in as the customer in the ticket with a draft post there, though. I must have gotten a cookie somewhere along the line for my test site, but I'm able to duplicate it with a new site:

**Comment by JoshuaGoode** [comment]
Was able to easily reproduce via the following

1. In Safari with default security and privacy settings, third-party cookies prevented
2. Cleared cache and cookies
3. Logged in to WordPress.com, accessed a Simple site with a custom mapped/connected/registered domain already set as primary
4. Did not access any other site settings or features, went to My Site > Posts and edited a draft post, ID 149.  Attempted to preview.
5. Was taken to `https://custom-domain/?p=149&preview=true` in a new tab
6. 404'd

**Comment by JoshuaGoode** [comment]
### Examining the issue

Following up on my [reproduction steps](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-1194128807):

If I manually visit the preview using the Simple site's free WPCOM address, instead of the custom domain, it loads without 404'ing. 

E.g. 

- Doesn't work:  `https://custom-domain/?p=149&preview=true` -- preview link used by the editor
- Works:  `https://free-wpcom-address/?p=149&preview=true` -- URL used for the preview link from Calypso

Which does seem related to the [older 2019 report and cookie issues](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-1194050488) I mentioned

### No cookie

When I examine the posts via both URLs, I see I don't have any cookies for `custom-domain` but lots of cookies for the free WPCOM site address.

I'm in a logged-out state when viewing the site via its custom domain. 

If I force enough login flows, I eventually get `wordpress_logged_in_xxxxx` and `wpc_wpc` cookies for my custom domain -- which then allows me to see the draft via `https://custom-domain/?p=149&preview=true`

For example, remaining on the 404 page and using the action bar to Log in, I'm asked to continue without needing to renter credentials and am taken back to the preview.  This time I can see the preview. I have a cookie and am in a logged-in state.

Perhaps the previous work to ensure logins automatically set cookies for custom domains, in the first-party context, wasn't enough or something is broken.

Re cookies work

* pd8D2H-23-p2
* p58i-aLK-p2

### New workaround

This brings a new workaround.  If a user encounters this, have them remain on the 404 page and then utilize the action bar to log in.  

This will take them to a log-in page, ask them to continue/confirm without needing to enter credentials, and then take them back to the draft preview with a cookie in a logged-in state.  No 404.

`... > Log in`

![Screen Shot on 2022-07-25 at 13:50:07](https://user-images.githubusercontent.com/4887830/180842185-a69490d6-7009-4f3d-8ff9-fc7e5a9345af.png)

**Comment by jeyip** [comment]
Thank for sharing the knowledge @JoshuaGoode. Spent today narrowing things down.

- It seems like the most likely culprit for this issue is [this PR](https://github.com/Automattic/wp-calypso/pull/56899), which removed Calypso's implementation of the preview modal in favor of the core Gutenberg preview feature.
- We're seeing issues because the core Gutenberg preview feature opens in a new window pointed at the simple site's mapped domain 
- The url pointing towards the preview, as far as I can tell, _has not_ implemented any of the solutions discussed in p58i-2DN-p2 to circumvent third party cookie problems
- I'm in the process of drafting a PR. Hopefully I'll have something for review by tomorrow or the day after.

**Comment by Babylon1999** [comment]
5428038-zd

**Comment by Babylon1999** [comment]
5431712-zd

**Comment by syedshaon** [comment]
5436021-zd

**Comment by liviopv** [comment]
- [ ] 36185739-hc
- [ ] 5401434-zd-woothemes

**Comment by aetta** [comment]
5438243-zd

**Comment by rinazrina** [comment]
#5439830-zen

#5439525-zen

**Comment by syedshaon** [comment]
5439179-zd

**Comment by filipanoscampos** [comment]
Another case, here: 36311000-hc

Please follow up, here:

- [ ] 5448353-zd-woothemes

**Comment by jp-imagines** [comment]
Another in 36314195-hc

- [ ] follow-up: `5449183-zd-woothemes`

**Comment by Babylon1999** [comment]
5445983-zd

**Comment by tanjoymor** [comment]
27167061-hc (happens in Firefox but not Chrome with a draft post)

**Comment by csabarakasz** [comment]
- [ ] 5441292-zd-woothemes

Similar case. Requesting OS and browser version.

**Comment by jeyip** [comment]
Hey team -- we just released a bug fix for this issue in https://github.com/Automattic/wp-calypso/pull/66046. I tested the draft preview 404 third party cookie issue in production and it should be solved for simple sites.

One thing to note is that in testing, #cylon noticed that browser caches and cookies could be finicky, even with the fix. This means that existing users with the problem might not see things resolved until they either:

1. ~Follow the workaround instructions that @JoshuaGoode suggested [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-1194382590)~ ( This workaround is no longer behaving as expected )
2. Clear browser cache and cookies and log back into WordPress

~I'd suggest option number 1.~ That being said, once fixed, our users should no longer need to do any other finagling and should not see this problem on simple sites moving forward.

**Comment by jeyip** [comment]
Closing this for now as the problem appears to have been solved

**Comment by syedshaon** [comment]
5472157-zd

**Comment by cometgrrl** [comment]
@jeyip Can you follow up with @syedshaon on 5472157-zen and see if this needs to be re-opened or if we need to file a new bug?

**Comment by jeyip** [comment]
@cometgrrl Sure 👍 I'll reach out to @syedshaon

**Comment by jeyip** [comment]
Talked to @syedshaon and I pointed him to workarounds for potential problems with browser caches and cookies [here](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-1205827077). Also noted that, once handled, the problem _should not_ reoccur. It seems like this issue doesn't need to be reopened, but I'll keep an eye on things.

**Comment by rickmgithub** [comment]
5473741-zd User reported the workaround [here ](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-1194382590)doesn't work for them.

**Comment by jeyip** [comment]
@rickmgithub Is the user led to a blank screen? @syedshaon had a similar problem, and we're waiting to see what happens when the user clears their cookies.

I'll open up a new Github issue if this is the case.

**Comment by jorpdesigns** [comment]
@jeyip The user in the case reported by @rickmgithub (5473741-zen) confirmed they see a blank screen.

We have also asked them to clear their browser cache and they confirmed this did not work either.

I have now asked them to clear their browser cookies and let us know if that works.

**Comment by jeyip** [comment]
> @jeyip The user in the case reported by @rickmgithub (5473741-zen) confirmed they see a blank screen.

I'll see if I can reproduce this in a bit. If so, I'll create a second issue that can be prioritized and handled by a separate team, because the blank screen seems unrelated to the cookie problems we addressed here.

**Comment by jeyip** [comment]
@syedshaon @jorpdesigns @rickmgithub @cometgrrl @JoshuaGoode I can consistently reproduce the login problem described by others. I'm [creating a separate issue](https://github.com/Automattic/wp-calypso/issues/66608) now. I've also amended [my suggested browser cache invalidation techniques](https://github.com/Automattic/wp-calypso/issues/57812#issuecomment-1205827077) to no longer include Joshua's suggested workaround.

**Comment by metabreakr** [comment]
36508625-hc
Firefox 103.0 on Windows 10.0.0

**Comment by wiesenhauss** [comment]
Another one - using Baskerville 2
- [ ] 5527101-zen

**Comment by druesome** [comment]
36585851-hc

Firefox user is unable to view scheduled post while logged in.

**Comment by brinbliss** [comment]
Another with Firefox 104 and the Maxwell theme. Copying the draft into a new draft fixed it, for this user.

- [ ] 32647624-hc

**Comment by csabarakasz** [comment]
- [ ] 36356258-hc
Another one. suggested the Preview option from the Pages section instead.

I couldn't replicate it btw.

**Comment by cuemarie** [comment]
_Decision was made here: p1683245378229639-slack-C0160HSMDQV that batch replies for users impacted by this issue will not be sent out._
