### ISSUE TITLE
Videos UI: Test with non-English locales and RTL.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57852]
While launching EN-only, we'll need to verify videos UI behaviour and content with other locales (and RTL) for when translations are complete.

**Comment by kwight** [comment]
EN-only behaviour is currently gated client-side.

**Comment by blackjackkent** [comment]
I tested all Mag16 languages and all of the modal text and video API content is currently translated for all of them except for two (Hebrew and Japanese) - these latter two never got translated because we kicked the priority down [over on GlotPress](https://translate.wordpress.com/deliverables/overview/6915723/) because this wasn't going out to anyone but English-speaking users. Since we are now planning on a wider release, I've kicked the priority back up to high.

I've also opened https://github.com/Automattic/wp-calypso/pull/58963 which adds internationalization to the card itself. We can track translation of those strings on the GlotPress link in the PR.

(As a side note, I also removed the client-side gating of EN-only behavior, because it was redundant - the card is hidden based on locale on the server-side in `wp-content/lib/home/cards.php`.)

**Comment by kwight** [comment]
Wow, that looks amazing:

| Arabic | Korean | German |
| --- | --- | --- |
| <img width="1631" alt="Screen Shot 2021-12-08 at 1 21 07 PM" src="https://user-images.githubusercontent.com/349751/145286729-ad9438e7-d631-4fd1-9642-aed1fface3e6.png"> | <img width="1631" alt="Screen Shot 2021-12-08 at 1 22 30 PM" src="https://user-images.githubusercontent.com/349751/145286752-e9aa5c0b-c874-4143-a9ed-4315c84a50ab.png"> | <img width="1636" alt="Screen Shot 2021-12-08 at 1 24 06 PM" src="https://user-images.githubusercontent.com/349751/145286777-361d07f7-ab01-474c-beb5-616901f31b24.png"> |

> Since we are now planning on a wider release, I've kicked the priority back up to high.

Awesome, great.

> I've also opened #58963 which adds internationalization to the card itself.

So it sounds like when the card is translated, as well as the content in Hebrew and Japanese, we'll be ready to go. 👍
