### ISSUE TITLE
Veni: disappearing Menu 

### ISSUE THREAD

**Issue by cat-og** [Automattic/wp-calypso#57927]
### Quick summary

With the theme Veni, the top menu has a strange reactive breaking point. The menu only shows up when I am in fullscreen or if I have expanded my window to at least 2/3 of my screen. [Repeated this on their demo](https://themeskingdom.com/demo/veni/) although the demo has the menu in another place. 

### Steps to reproduce

1. Visit https://andrewberkin.com/ or https://themeskingdom.com/demo/veni/ on the homepage.
2. Expand and shrink window, menu items disappear. 

### What you expected to happen

I can see the menu options while in Desktop mode

### What actually happened

The menu disappears and is not visible until the screen reaches the responsive breaking point. 

### Context

This is a recent change, user was always able to see and access the menu beneath their logo in desktop mode until yesterday. Verified with site activity, no changes were made. 

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
Thank you for the report @cat-og ! Although they are the same theme in essence, some things might not behave the same.

I'm not quite sure of the expected behavior here, but I'm pinging @jordesign for a second look.

**Comment by jordesign** [comment]
OK - so there's a few things going on here....

https://themeskingdom.com/demo/veni/ and 8Dqch-p2r (our demo site) both use the 'Compact menu' option for the theme- which is different to what the user has in place. In either case - the change from full-menu to hamburger-menu appears to happen at the same kind of point.

There is a *slight* difference between the public theme and our version - but only 2px worth. So that's not really it.

The most recent build of Veni that we are using is from 2018-09-26 - and that hasn't changed recently. So none of this explains why it would be different for the user.

**Comment by jordesign** [comment]
It seems possible we need to go back to them to see if anything else may have changed. Things I can think of that might make it *seem* like the theme changed...

* They're looking on a device with a different screen resolution
* The page-zoom in their browser has changed.

**Comment by Robertght** [comment]
@cat-og is there any news from the user?

**Comment by Robertght** [comment]
I'm going to close this for now due to inactivity, but please reopen if necessary.
