### ISSUE TITLE
Signup Plan Selection: Handle Stripe rate limits more gracefully.

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57960]
### Quick summary

One of our end-to-end tests has exposed a case where you can hit a Stripe rate limit when selecting a plan during signup. When this happens, the user is left with an empty cart. 
In light of that...
1. We should potentially investigate the number of Stripe calls - the network trace showed 21 web requests all firing in the same second to Stripe, which seems like a pretty high volume to me (but I don't know a lot about billing!)
2. We should handle hitting the rate limit more gracefully. We should pause and retry rather than showing an empty cart.

### Steps to reproduce

1. Go to `/start`
2. Pick a domain
3. Pick a paid plan
4. Land in cart

### What you expected to happen

See items in cart.

### What actually happened

Showed an empty cart with error message to re-add items. See screenshot!

### Context

Failures in E2E tests - see #57958

### Other notes

Screenshot of cart:  
![wp-signup__paid-see-secure-payment](https://user-images.githubusercontent.com/26772342/141337002-7794883c-b3b4-4089-84f1-00e2e3bc7654.png)

Error message in console: 
`We were rate-limited from checking if your requested Payment Request options are allowed. Please test again before going live.`

Tracing the console, I saw 21 POST requests to `https://r/stripe/com/0` that all happened in the same second.

### Reproducibility

Intermittent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

You can just go backwards in the flow and try to re-add your plan, and if you don't hit the rate limit again, you should be good!

**Comment by Robertght** [comment]
@Automattic/shilling I'm adding this to your board.

**Comment by sirbrillig** [comment]
Thanks for bringing this up!

That's odd... the shopping cart is mostly unrelated to Stripe, so I'm not sure why this would occur.

I wonder if the Stripe notice is a red herring and the actual problem is something else, like maybe a race condition with account creation (which could be related to the cart ownership errors we see constantly but haven't been able to track down: 410-gh-Automattic/payments-shilling).

**Comment by sirbrillig** [comment]
For now, let's put down what I do know:

- If you see the "empty cart" page, it's because the shopping-cart endpoint has been queried and returned a cart with no products.
- If you don't see any error notices displayed on the "empty cart" page, it means that the shopping-cart endpoint has not returned any errors.
- If there are no error notices in the shopping-cart endpoint and there are no products, either no products have been added to the given cart key, or there were errors when products were added outside of checkout.
- Shopping carts are stored in user attributes, so if an account hasn't been created yet, no request to the shopping-cart endpoint will succeed.
- Signup must create an account before adding a product to the cart, **although I'm not sure where that occurs.**
- Signup adds products to the cart outside of checkout here, using the site slug as the cart key:

https://github.com/Automattic/wp-calypso/blob/ad310497522376dd048a2b7c565f3d63e69a5ebd/client/lib/signup/step-actions/index.js#L452-L456

- If signup has an error adding products, it calls the callback function passed to `processItemCart()`, which is originally passed to `addDomainToCart()`/`addPlanToCart()`. **I can't tell where that callback is implemented, though.**

So my best guess at the moment is that there's one of two things happening (maybe both):

1. The signup framework is not waiting for the account creation to complete before adding products to the cart (or not waiting long enough; it may be a race condition since we don't see this all the time).
2. An error is happening when trying to add the products to the cart but the signup framework is not correctly handling the error, which presumably would involve pausing signup to display the error rather than continuing to checkout.

I may need help from someone who groks the signup framework to dig deeper. 

It would also be helpful to be able to reproduce this locally. Is there a way to run the failing test manually on the cli? If we can examine the network requests to `/me/shopping-cart` in the browser when the test fails, we should be able to find out what's happening.

**Comment by sirbrillig** [comment]
Oh, one thing I just realized is that if the call to `addProductsToCart()` fails to add a product, it **may not reject its promise**, since the cart endpoint will still return valid cart data (with errors included). So this line will never be called:

https://github.com/Automattic/wp-calypso/blob/ad310497522376dd048a2b7c565f3d63e69a5ebd/client/lib/signup/step-actions/index.js#L456

I'm experimenting with a way to resolve this in https://github.com/Automattic/wp-calypso/pull/58428
