### ISSUE TITLE
Theme Showcase: Disable logged-out follow buttons on demo sites?

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#5801]
Not a bug exactly, but I noticed when live previewing a theme in incognito mode, the logged out follow button was really apparent: 

<img width="467" alt="screen shot 2016-06-03 at 3 07 20 pm" src="https://cloud.githubusercontent.com/assets/8698879/15792846/1bad5ed4-299d-11e6-812d-dc9e3ff2bd79.png">

<img width="1192" alt="screen shot 2016-06-03 at 3 10 02 pm" src="https://cloud.githubusercontent.com/assets/8698879/15792871/491b282e-299d-11e6-9bbf-57d5a63b3b1c.png">

Since no one really needs to be accidentally following a theme demo, should we just start turning those off on the demo sites? 

This might not matter, I particularly noticed it because I previewed one in the mobile view (see first screenshot) and so it took up like half the screen.

**Comment by folletto** [comment]
@kathrynwp is that something that we forgot to turn off on the demo sites? I think it's a setting per-site, or am I missing something?

**Comment by kathrynwp** [comment]
I will ask the wrangler if that's something on their list as I'm not involved in demo setup. Will get back to you!

**Comment by kathrynwp** [comment]
@allancole is going to look into this.

**Comment by allancole** [comment]
Turns out we didn’t uncheck the “Show follow button to logged out users” setting for both of those demos and a few others. I went through all the demos of themes released in 2016 and needed to fix this setting for the following themes: 

* Escutcheon
* Luxury
* Rebalance
* Revelar
* Rowling
* Scratchpad

@kathrynwp: This specific settings change seems to be missing from our Theme Launch docs which explains the inconsistency here. Unless it’s mentioned somewhere else, I’ll go ahead update the Theme Launch docs ;-)

**Comment by kathrynwp** [comment]
Thanks @allancole -- I'd say go ahead, even if it's in multiple places that's fine!

**Comment by folletto** [comment]
Cool! That's a quick turnaround! 
Thank you!

Should we keep this thread open until you're done, or can we close this? :)

**Comment by allancole** [comment]
Will do, KP!

@folletto Yup, updating the docs now so I’ll go ahead and close.
