### ISSUE TITLE
[Bug]: Import onboarding flow: Attempting a WPcom simple site import doesn't move beyond the template selection screen

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#58163]
### Quick summary

On the new `Import onboarding flow` (https://wpcalypso.wordpress.com/start/importer/capture?siteSlug=slug.wordpress.com), entering a WPcom simple site as the site to import moves to the next screen, which is selecting a template. But, none of the templates respond. Clicking on them has no effect.

### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/start/importer/capture?siteSlug=slug.wordpress.com (replace slug.wordpress.com) with your WPcom site address
2. Enter a WPcom simple site address to import.
3. Click on `Start building`
4. Move forward to the template selection screen.

### What you expected to happen

Clicking on one of the templates actually responds.

### What actually happened

None of the templates respond when I click on it.

https://user-images.githubusercontent.com/18581859/142170980-1fd8fe44-f76a-4ca4-a3cd-cba10f38da85.mov

### Context

Manual testing: pcmemI-dX-p2

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

NA

### Reproducibility

Consistent

### Severity

All

**Comment by arunsathiya** [comment]
Similarly: if you try to import a simple site (haven't tested Atomic site) on an Atomic site (https://wpcalypso.wordpress.com/start/importer/capture?siteSlug=atomicarunsathiya.wpcomstaging.com; I created this link manually), it results in a loop, redirecting back to the import screen after choosing the template:

https://user-images.githubusercontent.com/18581859/142171319-45f674fb-8173-4f12-9fd2-b345ebe6122b.mov

**Comment by bogiii** [comment]
I've investigated and found out that the Design picker screen doesn't trigger [goToNextStep method](https://github.com/Automattic/wp-calypso/blob/460eb38b4724bd4052fe1c7fa1cc28a31a35f278/client/signup/steps/design-picker/index.jsx#L160).
Actually, it triggers, but it doesn't redirect to the proper destination defined [here](https://github.com/Automattic/wp-calypso/blob/460eb38b4724bd4052fe1c7fa1cc28a31a35f278/client/signup/config/flows.js#L103).

It must be caused by the nature of how the flow is working by design. Everything is fine when you come from the Intent screen, but when the Importer module redirects to the design-picker step by calling the [goToStep method](https://github.com/Automattic/wp-calypso/blob/460eb38b4724bd4052fe1c7fa1cc28a31a35f278/client/signup/steps/import/ready/index.tsx#L193) it doesn't.

@arthur791004, do you maybe have some idea how to resolve this issue?

cc @vishnugopal

**Comment by arthur791004** [comment]
@Robertght @bogiii I'm sorry for the late response. The reason is that you don't submit the site intent, so that step is still “in-progress”. After the user is redirected to the “design-setup-site” step and wants to go to the next step, it would try to go to find the first invalid step or complete the flow if all of the steps are submitted as it's the last step of the setup-site flow. However, there is no invalid step and there is still one step never being submitted. So the page won't do anything 😅

Let me think about how to redirect to the build flow 🤔

Besides, I have some questions as followed:
* When the user clicks the “Back” button after redirecting to the build flow, what's the correct previous step? “Your site is ready on WordPress.com” or “Intent screen”?
* How do you track the events? I found that you use `goToImporterPage` to go to importer page on WP.com rather than the `destination` function to redirect to that page. This would make the `calypso_signup_complete` event not being fired.

IMO, making the rest of the build flow be part of the importer flow might be easier to solve the problem now and make the tracks event work correctly. In long term, we can have a better solution after we finish pbAok1-2iM-p2.

**Comment by bogiii** [comment]
@arthur791004 Thank you for the response!

> When the user clicks the “Back” button after redirecting to the build flow, what's the correct previous step? “Your site is ready on WordPress.com” or “Intent screen”?

The right answer should be to go back to the `importer` flow, and it will be the Capture screen instead of the `Your site is already on WordPress.com` screen (because of the Flow framework nature).

> How do you track the events?

We still don't trigger any additional events except the events that come from the "Flow framework". We have a plan for the current sprint to track more events in the importer flow.

> I found that you use goToImporterPage to go to importer page on WP.com rather than the destination function to redirect to that page. This would make the calypso_signup_complete event not being fired.

Actually, I didn't know what is the difference between the `goToImporterPage` and `destination` functions. I've consumed the `goToImporterPage` function since it comes with step component dependencies.

cc @vishnugopal

**Comment by vishnugopal** [comment]
> When the user clicks the “Back” button after redirecting to the build flow, what's the correct previous step? “Your site is ready on WordPress.com” or “Intent screen”?

I kinda feel for a user, a Back here at this point, it might be better to go to the Intent screen.  

Another option for us is to redirect the "Start Building" button to the Intent screen in case that helps make things simpler. cc @ollierozdarz

**Comment by vishnugopal** [comment]
^ @ollierozdarz concurs that we can just take them to the Intent screen if that makes for a simpler solution!
