### ISSUE TITLE
Plugin Installation: Better guard the installation flow 

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58297]
During our demo it was suggested that we should better guard our plugin installation direct url so that we avoid malicious users getting WordPress.com users to visit it and thus install a malicious wporg plugin in their site.

**Comment by cpapazoglou** [comment]
Suggestion, saving in the state that User has indeed initiated the plugin installation.

**Comment by WBerredo** [comment]
Considering we'll be able to identify that a plugin installation was not initiated by the customer(#58493), I think we can give the customer the chance to proceed with the installation, giving the idea of successful operation instead of an error. 

This way the installation link could be used directly but in a safe manner.

Ex:
![Screen Shot 2021-11-26 at 10 38 57](https://user-images.githubusercontent.com/5039531/143597817-f6883c10-6da3-40c2-a9ab-bf5ab740ba5e.png)

**Comment by cpapazoglou** [comment]
> Considering we'll be able to identify that a plugin installation was not initiated by the customer(#58493), I think we can give the customer the chance to proceed with the installation, giving the idea of successful operation instead of an error.
> 
> This way the installation link could be used directly but in a safe manner.
> 
> Ex: ![Screen Shot 2021-11-26 at 10 38 57](https://user-images.githubusercontent.com/5039531/143597817-f6883c10-6da3-40c2-a9ab-bf5ab740ba5e.png)

I like this idea @WBerredo, cc @gcsecsey

**Comment by gcsecsey** [comment]
I think this is a brilliant idea @WBerredo! 🎉 

To make the implementation more straightforward, I think we should add this as a follow-up PR, after we've handled plugin icons in https://github.com/Automattic/wp-calypso/issues/58281#issuecomment-975573046
