### ISSUE TITLE
Plugin Details: Header revisit

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58296]
### Details

Was kinda missing the icon here, it’s so text heavy. 🙂
We should definitely add some star/recommended/something next to Automattic plugins. 😀

|Desktop | Mobile|
|-------|------|
|<img width="1473" alt="SS 2022-01-28 at 10 37 08" src="https://user-images.githubusercontent.com/12430020/151514242-fecc05a8-447b-4630-b1a1-388e3d3ca718.png">|![image](https://user-images.githubusercontent.com/12430020/151514135-26c6b17d-49a8-4142-89d0-e00811ba6b32.png)|

### Related

> I think there’s still potential for improvement with the top section. More economical use of the space available. But that’s a nice start for a single column for the content. -- Ian

pdh6GB-6h-p2#comment-315

**Comment by cpapazoglou** [comment]
Could we potentially add:

- a verified by checkmark would probably work will all Marketplace products
- or "Editors Choice" would probably work with a limited selection of Marketplace products

Regarding the icon, may we can sneak peek how other marketplaces present their plugins.

**Comment by SaxonF** [comment]
Also related https://github.com/Automattic/wp-calypso/issues/43230

**Comment by SaxonF** [comment]
Let's add the plugin icon to the plugin details page

![image](https://user-images.githubusercontent.com/1072756/153978926-b8d4326c-899b-4ef6-be22-08805c08d8a4.png)
![image](https://user-images.githubusercontent.com/1072756/153978965-3c6ff258-ba9e-414e-ac3c-970956eaa186.png)


Acceptance criteria:
- Plugin icon shows to the left of the plugin title and description but below the plugin tags
- Plugin icon is 88px by 88px
- Plugin icon has a 4px border radius but does not set a background so that circular images like the Contact 7 example above still work

**Comment by lsl** [comment]
Likely a separate issue but Is there a reason we display the Developer as "Automattic" and not "WordPress.com", or in the case of WooCommerce "WooCommerce"?

**Comment by cpapazoglou** [comment]
> Likely a separate issue but Is there a reason we display the Developer as "Automattic" and not "WordPress.com", or in the case of WooCommerce "WooCommerce"?

We are following the WordPress.org pattern here https://wordpress.org/plugins/woocommerce/

**Comment by lsl** [comment]
Yes there too. Do our users know they have their website hosted with Automattic?

**Comment by cpapazoglou** [comment]
> Yes there too. Do our users know they have their website hosted with Automattic?

I see your point. There is an issue to address this https://github.com/Automattic/wp-calypso/issues/43230
