### ISSUE TITLE
Dyad 2, Android, open submenu items

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#58323]
### What

Opening submenu items

### Why

Clicking on Main menus will take user to a page and not allowing to click on submenus. Works ok on Iphone. 

https://user-images.githubusercontent.com/11535091/142732634-0a49012e-69ea-471c-b17a-4bc789ce2bc5.mp4

**Comment by kosiew** [comment]
Hi @daria2303 ,

Thanks for reporting this.

Can I confirm the theme is Dyad 2, instead of Dyad?

Here is how it looked when I tested on Dyad 2.
In other words, the sub menu is visible to be clicked.
![image](https://user-images.githubusercontent.com/29057562/143364570-9b623407-a4dc-4fcc-82e8-38b707c458f3.png)

**Comment by daria2303** [comment]
Hi @Greatdane, sorry, your are right it is Dyad 2, hacemoslasmaletas.com

**Comment by Greatdane** [comment]
cc: @kosiew, see above!

**Comment by iamgabrielma** [comment]
Adding here the case 4459815-zen so we can follow up when there's an update.

**Comment by Robertght** [comment]
I'm closing this in favor of this one: 

https://github.com/Automattic/themes/issues/1417

Another similar case: https://github.com/Automattic/themes/issues/810
