### ISSUE TITLE
Woo Installer: Add error handling to transfer step

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#58331]
The atomic transfer step in the woocommerce installer [needs error handling](https://github.com/Automattic/wp-calypso/blob/ec91807b772975d793f1243e89b6bccecdc4e111/client/signup/steps/woocommerce-install/transfer/index.tsx#L135).

- [x] On error, redirect back to the confirm step and display the error.
- [x] Investigate: There may now be a stuck transfer in place, confirm what these look like on the confirm screen it may be we need to add disabling to buttons on the confirm screen.

One semi-consistent way to trigger a transfer failure error in prod: 

- Initiate transfer using installer
- Revert site without issuing early cleanup
- Immediately attempt a re-transfer

If the clean up runs mid transfer (it should) you'll get a transfer error

**Comment by lsl** [comment]
Updated design for the confirm screen to work from, cc @SaxonF 

pdhcfv-5D-p2#comment-120
r6eTqDpL2GGk96hcPLhsBb-fi-431%3A2447
https://github.com/Automattic/wp-calypso/pull/58024#issuecomment-977556114

I'm not sure how we want to split this between the [mobile ux ticket](https://github.com/Automattic/wp-calypso/issues/58387 ) maybe we just close one and tackle it all out of here? 

cc @allilevine / @Rolilink / @retrofox

**Comment by allilevine** [comment]
> I'm not sure how we want to split this between the [mobile ux ticket](https://github.com/Automattic/wp-calypso/issues/58387) maybe we just close one and tackle it all out of here?
> 
> cc @allilevine / @Rolilink / @retrofox

I think we should work on updating the design (and mobile view) separately. I updated https://github.com/Automattic/wp-calypso/issues/58387 to include both.

**Comment by Rolilink** [comment]
> I think we should work on updating the design (and mobile view) separately. I updated #58387 to include both.

This sounds like a good approach, I wonder if the design and mobile implementations will block each other but I don't think it is a big deal!.

**Comment by lsl** [comment]
Sounds good to me.

**Comment by retrofox** [comment]
> > I'm not sure how we want to split this between the [mobile ux ticket](https://github.com/Automattic/wp-calypso/issues/58387) maybe we just close one and tackle it all out of here?
> > cc @allilevine / @Rolilink / @retrofox
> 
> I think we should work on updating the design (and mobile view) separately. I updated #58387 to include both.

Also, I think we could split up in landing page and transferring step?

Landing page | Transferring step
-----|-----
![image](https://user-images.githubusercontent.com/77539/143387670-07aa82ea-d9e1-44f7-aebe-8791526554e0.png) | ![image](https://user-images.githubusercontent.com/77539/143387826-b2323b00-1e5a-4754-a89f-4d230a0b10e6.png)

**Comment by retrofox** [comment]
- [ ] Transferring step: https://github.com/Automattic/wp-calypso/pull/58527

**Comment by lsl** [comment]
^ https://github.com/Automattic/wp-calypso/pull/58719

**Comment by lsl** [comment]
Some context around what remains for this in here: https://github.com/Automattic/wp-calypso/pull/58848#issuecomment-992148918

**Comment by pablinos** [comment]
It's not clear to me what we need to do to complete this. To begin with, I think all errors on the transfer step should lead to the progress bar being replaced with an error, which includes a way to contact support and a way to get back to the app - exit the flow.

As an HTTP error, an error response, or a timeout can all be treated as unrecoverable, the process should be aborted. People could probably come through the landing page to try again, but we'll not to make sure that the state is reset correctly.

This part of [the above referenced comment](https://github.com/Automattic/wp-calypso/pull/58848#issuecomment-992148918), I'm not sure I fully understand:

> I think we should just rely on errorNotice for request failures (e.g. this, not this), that pops up a notice bar in the top right of the page. For transfer failures we should set an error state and show it in place of the progress bar.

Once on the transfer step, I think all failures, request or otherwise, would need to be treated the same, because we're showing the progress bar at this point. Whatever has happened we would need to rely on the error state to abort the process. I think this comment is saying the same thing, but also that we can use the error notice when requests fail while we are not on the transfer step.

For the transfer step there's maybe a few initial things to look at:

- [x] Create an error page/state that can be shown in place of the progress bar
- [ ] Have a way to display that error page if any failure occurs during HTTP requests.
- [ ] Checking the transfer state and [error property](https://github.com/Automattic/wp-calypso/blob/6dd5aad11ebdb7af312d854dc7a7c71d0456304e/client/state/atomic/transfers/actions.ts#L18), and show the error page if it is stuck, or some other error has occurred
- [ ] Checking the [error property](https://github.com/Automattic/wp-calypso/blob/6dd5aad11ebdb7af312d854dc7a7c71d0456304e/client/state/atomic/software/actions.ts#L13) in the software install status, and showing the error page if it gets set
- [ ] Implement a timeout for the software install step. This should be a really quick part of the process, so the timeout could be 15 seconds or so. As a first version, we could again show the error page rather than implementing a retry. A retry could be handled manually by restarting the flow.

**Comment by retrofox** [comment]
> Create an error page/state that can be shown in place of the progress bar

![image](https://user-images.githubusercontent.com/77539/146248568-65ffa15c-c6ae-4add-a03d-060e6b6d49cd.png)

This is what we got now. It's almost the same Error component defined in the transfer step. Do you think it's good enough at least for now?

**Comment by retrofox** [comment]
> - [ ] Have a way to display that error page if any failure occurs during HTTP requests.
> - [ ] Checking the transfer state and error property, and show the error page if it is stuck, or some other error has occurred

Those seem pretty similar to me. I'm testing with a broken WoA site (status is `active`). The transfer object defines its status with `500`. I think we can check this property to catch it.

**Comment by retrofox** [comment]
> Checking the transfer state and error property, and show the error page if it is stuck, or some other error has occurred

Is this property defined? I'm testing with broken sites, and it doesn't seem to be.

**Comment by retrofox** [comment]
First attempt for transfer: https://github.com/Automattic/wp-calypso/pull/59267
