### ISSUE TITLE
Advanced SEO: Allow Editing of Meta for Posts and Pages

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5834]
In SEO v1 we added a great way to edit a site's meta description (see `settings/seo`) to update how it appears in search results.

Let's expand on that for advanced SEO by allowing a user to edit the `title` and `description` meta and open graph tags for individual posts and pages. This would be added to the post editor.

Design to be posted here by @drw158

**Comment by drw158** [comment]
Some thoughts: I don't think we should allow custom meta for each social service, but just should show a preview of what their post/page will look like in context.

Regarding images, it might be tricky to communicate why a certain image was chosen for the preview, and how they can change it.

Here is a very simple mockup:

![artboard](https://cloud.githubusercontent.com/assets/618551/15872541/9c141d90-2cbf-11e6-853b-d47dc69e460b.png)

Because the previews aren't really SEO related, we could include it in the post preview:

![artboard](https://cloud.githubusercontent.com/assets/618551/15872680/3de011a6-2cc0-11e6-8433-63051be2710c.png)

**Comment by drw158** [comment]
Idea for adding these 2 fields. First field is disabled, similar to Yoast SEO. The format can be changed using the planned addition to the SEO settings tab.

![artboard](https://cloud.githubusercontent.com/assets/618551/16052377/9bfebf94-3229-11e6-93b3-c87bbb0ce7df.png)

**Comment by roundhill** [comment]
> First field is disabled, similar to Yoast SEO. The format can be changed using the planned addition to the SEO settings tab.

I like that, and maybe we could have an `Edit` link or something that would take you to the settings?

**Comment by roundhill** [comment]
This is pretty much done, but we need to add the custom title format component to mark this as closed.

**Comment by roundhill** [comment]
This is finished 🚀
