### ISSUE TITLE
[Bug]: wordpress.com see "Unsupported browser on Safari"

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58352]
### Quick summary

![image](https://user-images.githubusercontent.com/5665959/142888022-2ef1a0ff-06d3-4133-933e-04257f29c0e4.png)

![image](https://user-images.githubusercontent.com/5665959/142888061-077d4caf-3402-4f91-b91e-0aff8dc1c077.png)
Version 14.0.2 (16610.3.7.1.9)

### Steps to reproduce

1. In Safari goto wordpress.com
2. See redirect to https://wordpress.com/browsehappy?from=%2F and see the Unsupported Browser page

### What you expected to happen

I expect to see the wordpress.com landing page

### What actually happened

redirect to https://wordpress.com/browsehappy?from=%2F and see the Unsupported Browser page

### Browser

Apple Safari

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

No workaround- the landing page should work in Safari

**Comment by AliSoftware** [comment]
FWIW I tested in Safari `Version 15.0 (16612.1.29.41.4, 16612)` and couldn't reproduce.
I don't have a Safari 14.x around to test with the version mentioned in this issue.

**Comment by scinos** [comment]
Related to #58218

**Comment by noahtallen** [comment]
> FWIW I tested in Safari Version 15.0 (16612.1.29.41.4, 16612) and couldn't reproduce.

This makes sense -- v14 does not fall inside the version range we list for Safari, so Calypso doesn't think it's supported. Newer versions do fall inside that version range. 

It's a bit of an oversight because we expected v14 to be supported when we say "support the last two safari versions," but I think the tool we are using is using the point releases instead.
