### ISSUE TITLE
Magic Links: intermittent Login link is expired or invalid

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#58382]
### Quick summary

Intermittently the magic link feature fails to allow the user to log in with a message:
`Login links is expired or invalid`
`Maybe try resetting your password instead`

While most observations of this has been in end to end testing, anecdotally a friend of mine has also run into this issue when attempting to log into WordPress.com.

### Steps to reproduce

1. navigate to `/log-in`.
2. click on 'email me a link'
3. enter details as requested.
4. after email is received, click on the link.

### What you expected to happen

User is prompted to log in.

### What actually happened

Calypso error page is shown:
`Login links is expired or invalid`
`Maybe try resetting your password instead`

![image](https://user-images.githubusercontent.com/6549265/142958300-9f81ef28-09b9-4bff-9d28-b5c7fd2952c3.png)

https://user-images.githubusercontent.com/6549265/142958516-c77afb35-ffa8-4305-9f9b-2e2fac6bb93d.mp4

### Context

Playwright automated tests

### Other notes

Console logs:
```
wp-login.php?action=magic-login:0
Failed to load resource: the server responded with a status of 403 ()
```

TeamCity ID: 7020084

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

User is required to enter username/password if the magic link fails to operate.

**Comment by worldomonation** [comment]
I've assigned the priority of Normal, but in some instances this should really be a High priority.

**Comment by worldomonation** [comment]
Observed in https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/7122316?buildTab=artifacts#%2Fscreenshots.

**Comment by ClassicRKR27** [comment]
- [ ] I have another report here: 5307463-zd-woothemes

On top of that, I am able to replicate this consistently with one of my test accounts (`blakebays30`) - I just created it for the purposes of testing and I haven't once been able to get the link to work (including opening Incognito windows repeatedly in order to try and make sure it wasn't a browser cache issue).

**Comment by vinnykaur** [comment]
📌 SCRUBBING: RESULT

- Tested on WordPress.com account: Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

- Tried from a non-a8c account. I could not replicate the issue and be able to log in successfully. 

📌 ACTIONS

- Await author feedback
- Marked as Triaged for Quality Squad review


📌 Message to Author
- @worldomonation , @ClassicRKR27 Since it's been a while and we haven't had any more reports, I wanted to check if you are still able to replicate this issue.

**Comment by vajrasar** [comment]
Closing this since there has been no further reports, but pls feel free to re-open and share findings.

**Comment by jugalbandi** [comment]
Same occurring for me, Magic Link is immediately expired, as depicted in the video clip above, except for me it’s my first Magic Link to create the Wordpress account, so there’s no login workaroud. Password reset is not viable either, as my username/email isn’t yet found as a live account. (However, I think it’s registered someplace, stuck in a half-way state perhaps, because I get an error if I try create an account again with the same email.) 

Occurs whether requesting the link from the WP app or the WP website (Safari), on iOS 17.1.1 (latest official). 

I haven’t tried to reproduce this with a different email address. I’m not a programmer, but let me know if you would like any additional info. 

Could a new registration automatically create a default, self-expiring password so that at least the Reset Password workaround would be an option?
