### ISSUE TITLE
Plugins Navigation: add a way to go back to search results

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58501]
Scenario:
- User searches woocommerce
- Clicks on WooCommerce subscriptions
- They should be able to go back to the search results from the Header Navigation

figma designs: oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A49583

<img width="949" alt="SS 2021-11-25 at 14 14 49" src="https://user-images.githubusercontent.com/12430020/143439964-7c9c51d1-ffc2-4050-bc82-c17ec3d73c01.png">

**Comment by WBerredo** [comment]
When the user clicks on a plugin card, there is a redirect to the Plugin Details page, which lead us to two ways of sending info:
* via URL
* via global state (redux) *


In order to not pollute the URL with internal state, I would propose to save the breadcrumbs into the global state, which would allow us to solve the breadcrumbs problem in a more generic way.

https://github.com/Automattic/wp-calypso/blob/174eb8ebbe2a8e004962c2b7008db6d923674da2/client/my-sites/plugins/plugin-details.jsx#L182-L184
