### ISSUE TITLE
Videos UI: Back button is broken on mobile

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#58511]
After the refactor of the header bar the back button stopped working on mobile.

**Comment by enejb** [comment]
I reopened this issue since it is still broken for me. 

See
https://user-images.githubusercontent.com/115071/149019129-4742936e-6df3-4d5f-ac37-ef0a7c117ca9.mp4

In this demo, I used the browser back button which takes me to `google.com` since that was the previous page that I was on before I opened up wordpress.com. 

The same can be replicated if you use the back button on the desktop. 
The fix here should really use the browser history to push a new state once we open up the video modal. 
Maybe the modal should be present on a different URL completely?

**Comment by kwight** [comment]
@enejb Hm, I can't replicate this on dev tools nor on an actual device (iPhone with Brave) – any other tips to replicate?

**Comment by enejb** [comment]
Try using the browser back button instead of the one provided by the UI. 

See

https://user-images.githubusercontent.com/115071/149400960-82366191-8b0b-4d0d-892a-d361ce29fe3c.mov

 When I used the browser  back button I expect to be taken back to the /home dashboard

**Comment by kwight** [comment]
Oh! The _browser_ Back button, I see what you mean. Yeah, being a modal for the current page, it doesn't make sense for the URL to change (so it can change back) – but being fullscreen, which it's always intended to be... makes it appear like a different view. Hm, I dunno – I'd prefer to keep it as is, since users can always use the UI Back button (they're not ever really stuck), but I get the concern.

@ollierozdarz any preferences to address this?

**Comment by ollierozdarz** [comment]
Hmm yeah, I see what you mean. I agree with you @kwight, let's keep it how it is unless there are more issues/concerns down the road.

**Comment by enejb** [comment]
On desktop devices, this is not so much an issue but on mobile, the swipe to go back is very common user behaviour and it is currently broken. 

I really think we should fix this. What is the concern about adding a URL parameter when a user navigates away? 
This would also make the course linkable which is something that would make sense for educational content. 

This way a HE could send the user links to these videos for example. Currently, this is not the case. 

To be fair, the browser back button is currently broken for all the modals in calypso. 🙀 Such as the help ones that are present all over the place.

**Comment by kwight** [comment]
> the swipe to go back is very common user behaviour and it is currently broken

I think the issue is that we're not going back – we're closing a modal (but you're right, kinda confusing for users since our modal is fullscreen, which looks an awful lot like you loaded a new screen). 🙃 

> What is the concern about adding a URL parameter when a user navigates away?
This would also make the course linkable which is something that would make sense for educational content.

Again, it's that the modal is presented in the context of the page it's on – the courses are helpful to the specific view you're on, as opposed to standing on their own anywhere in Calypso (which, you're right, they could do). I wonder if instead of a route change in the URL, we could do a query param (eg. `https: wordpress.com/home/mysite.wordpress.com?course=blogging-quick-start`). That would keep the mental model of not going elsewhere when opening a course, but also allow the deep linking, which would be great (and the deep linking could be anywhere eg. `https: wordpress.com/marketing/mysite.wordpress.com?course=blogging-quick-start`).

> To be fair, the browser back button is currently broken for all the modals in calypso. 🙀

Right, which makes it feel more like a Calypso-wide project (at least, if we do something for it, it should be a solution that can be applied to all modals, which I think would apply to the query param + `pushState()` approach above).

**Comment by kwight** [comment]
@enejb We discussed this issue in our sprint planning meeting (paYKcK-1c8-p2), and decided to not take it on for the foreseeable future; if you choose to try it yourself, please do ping @Automattic/serenity for any help and reviews. 👍

**Comment by enejb** [comment]
@kwight Thanks for clarifying this. :) 

I have added it to my to-do list, will ping your team when I have something to review. :)

**Comment by lynnbgriffith** [comment]
@enejb Feel free to reach out to @Automattic/team-calypso-frameworks for review as well. Sounds like an interesting issue. I’m not totally sure that _all_ modals should use browser history in this way. Looking at Gutenberg, for example, rendering the modal component also typically doesn’t push a change to the URL.

**Comment by enejb** [comment]
Thanks for the offer to help @griffbrad. Will pong team calypso for a review as well. 
I agree that it might not apply to all modals but we can implement it as a prop and then easily added to the modals that should have it.

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/61110
