### ISSUE TITLE
[Bug]: blank canvas doesn't show up page template picker anymore

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#58544]
### Quick summary

The blank canvas used to show the page template picker by default when opening the editor the first time. This has stopped working at some point — I've tested both `/new` and `/start` flows:

https://user-images.githubusercontent.com/87168/143578838-bfcd8cdf-94ca-42d7-8d07-585fd7fb20f1.mov

I would expect identical experience to adding a new page:

https://user-images.githubusercontent.com/87168/143578604-15eefcb9-2ec9-4393-a158-d301076e0dfb.mov

### Steps to reproduce

- /new or /start
- Pick blank canvas
- At my home "edit homepage"
- Empty editor

### What you expected to happen

Page template picker

### What actually happened

Nada

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by p-jackson** [comment]
I can't reproduce this issue using the `/new` flow. [The code for showing the "Add a page" modal instead of the welcome guide is here](https://github.com/Automattic/wp-calypso/blob/84c520f6447ad9cc6c81df70f5a78f55fb1a6d91/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-nux-status-controller.php#L79), and when I test it it's working as expected.

The `/start` flow is different. This behaviour hasn't been implemented. @ollierozdarz My guess is we only want the "Add a page" modal to appear for the `build` flow? Not `write`?

Since the Hero Flow creates the site before showing the design picker, we'd need another way to set the `was_created_with_blank_canvas_design` option. Probably in the post-hero-flow API call.

**Comment by simison** [comment]
Old one. :-)
