### ISSUE TITLE
Theme Showcase: Re-add premium references

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#58616]
All of these can be done behind the `themes/premium` feature flag to avoid showing before they're ready:

* Re-enable the All | Free | Premium toggle
* Re-add the Premium Themes / premium plan upsell nudge for Free and Personal plan sites that was removed in https://github.com/Automattic/wp-calypso/pull/55942/files#diff-e1414f0851e1ef5a3807284b9645fa8c8ddf7abefdf68353fca4e8b6b210fc1eL30 and https://github.com/Automattic/wp-calypso/pull/55942/commits/45c80fab75eb07df154e059565cf776dd42c2c21#diff-e1414f0851e1ef5a3807284b9645fa8c8ddf7abefdf68353fca4e8b6b210fc1eL30

**Comment by sixhours** [comment]
Toggle PR re-added behind the feature flag in #58605

**Comment by mreishus** [comment]
Once we get the API to return some themes as premium, I'm wondering what we will see in calypso. That's an intermediate step.

**Comment by nelsonec87** [comment]
Regarding [these UpsellNudges](https://github.com/Automattic/wp-calypso/pull/55942/files?authenticity_token=LPz9k8fPcJm2RgWxlwpW%2B01R7LU98Ry7I%2F4Lc8wgmyx0m0CEMOKaFaoN6xpyz8iQu7iISdjRA8Hl6dWHZBmjkA%3D%3D&file-filters%5B%5D=.jsx&file-filters%5B%5D=.ts&hide-deleted-files=true#diff-a4c745026acf197c564244c92aebb153704da206bd091979e30479babe8cf5e4) , It seems there were changes to the component itself. Now there are other attributes/props and it is explicitly tied to `FEATURE_UPLOAD_THEMES`. 

Current structure:

```
<UpsellNudge
	className="themes__showcase-banner"
	event="calypso_themes_list_install_themes"
	feature={ FEATURE_UPLOAD_THEMES }
	plan={ PLAN_BUSINESS }
	title={ translate( 'Upload your own themes with our Business and eCommerce plans!' ) }
	forceHref={ true }
	showIcon={ true }
/>
```

I don't know if I should change it back or not.

**Comment by nelsonec87** [comment]
On [this file](https://github.com/Automattic/wp-calypso/pull/55942/files?authenticity_token=44HViLH4OsSKdJ3K%2BIO268mLhszK5RokMZQAGGELgbG75mifRtXQSJY%2Fc2EdRiiAP2LiMC%2FFBV73g97syTK5DQ%3D%3D&file-filters%5B%5D=.jsx&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&hide-deleted-files=true#diff-3d150099a2de6cc5246c60373128d17d35ac1dda06163d9456b35b05a6db9146) , there is this text:

`"You've now got access to every premium theme, at no extra cost - that's hundreds of new options. "`

Since there will be only a few themes (for now), I'm just leaving this last part out.

**Comment by sixhours** [comment]
All of this has been done in the above PRs, it just needs testing. Closing this!
