### ISSUE TITLE
Guided Tours: tours persist over Customizer

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#5861]
![](https://cloudup.com/iSR9AYqXzPP+)

I would prefer to update z-index to allow tours to persist under customizer than to dismiss the tour entirely so that context isn't lost. If that proves to be challenging, dismissing and restarting may work. Worst case, dismiss tour entirely if the user opens customizer.

**Comment by lancewillett** [comment]
Work is in-progress in #7908

**Comment by lsinger** [comment]
There are many other things between the Customizer `z-index` and the ones for Guides Tours. For example: preview. We want GuidedTours to be on top of preview, so we can't move them below it. We'd have to move Customizer up, which in this case would mean elevating it to almost the top-most element (only Olark would be further up). I'm not familiar enough with the situations in which Customizer can turn up and needs to work, so I'd rather not change it that drastically. 

Since #7908 got merged into `master` now though, tours will quit when we open the Customizer and the tour isn't waiting for that. 

Taking the above two data points, I'm closing this issue for now.
