### ISSUE TITLE
Blogger flow tracks event missing prop info on calypso_signup_actions_submit_step

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58620]
### Item 1
On the Blog Name (site-options) screen, it looks like calypso_signup_actions_submit_step
 is not recording step=site-options.

![image](https://user-images.githubusercontent.com/5665959/143976320-9068c903-e3f4-435c-8f43-86fc734f5200.png)

Look for the following in the calypso_signup_actions_submit_step tracks event page and see that step=site-options is missing
![image](https://user-images.githubusercontent.com/5665959/143976340-5d72afb3-c1d7-40dc-ab9e-ad1a79043c0f.png)

**Expected**
calypso_signup_step_start
[flow=setup-site, intent=write, step=starting-point]

**Observing**
calypso_signup_step_start
[flow=setup-site, intent=write]

### Item 2 
On the Starting Point screen, it looks like step=starting-point is missing from calypso_signup_step_start
[flow=setup-site, intent=write, step=starting-point]
![image](https://user-images.githubusercontent.com/5665959/143976773-b7eb9f7f-d139-475e-90e3-aa336a65375d.png)
See that step=starting-point is missing
![image](https://user-images.githubusercontent.com/5665959/143976906-d69dbbe0-7b00-436f-9ed1-6a7c63bc00ef.png)
Expected

**Expected**
calypso_signup_step_start
[flow=setup-site, intent=write, step=starting-point]

**Observing**
calypso_signup_step_start
[flow=setup-site, intent=write, ]

**Comment by autumnfjeld** [comment]
@arthur791004 If you get a chance today or tomorrow could you have a look to see if the step prop is missing from the events I listed in the description?  Thank you!!!

**Comment by arthur791004** [comment]
I think we cannot see all of the values on that page because it only shows the top 10 values as my observation. We can see all of the values from https://mc.a8c.com/tracks/trends/

## Site Options

https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=calypso_signup_actions_submit_step&interval=day&prop=step&startdate=20211031&stat=uniques

<img width="300" src="https://user-images.githubusercontent.com/13596067/144015688-043f5a72-ce2b-4109-bf5d-838b60c36ea1.png" />

<img width="300" src="https://user-images.githubusercontent.com/13596067/144013190-710ef206-b3e1-4ffd-a4fb-3e805312a0b3.png" />

## Starting Point

https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=calypso_signup_step_start&interval=day&prop=step&startdate=20211031&stat=uniques

<img width="300" src="https://user-images.githubusercontent.com/13596067/144015795-21779ec5-51d7-4880-965d-15f410f0ea7d.png" />

<img width="300" src="https://user-images.githubusercontent.com/13596067/144013635-3142db7d-7852-4050-b68d-b7368f5353c2.png" />

**Comment by arthur791004** [comment]
I think we cannot see all of the values on that page because it only shows the top 10 values as my observation. We can see all of the values from tracks > trends

## Site Options

<img width="300" src="https://user-images.githubusercontent.com/13596067/144015688-043f5a72-ce2b-4109-bf5d-838b60c36ea1.png" />

<img width="300" src="https://user-images.githubusercontent.com/13596067/144013190-710ef206-b3e1-4ffd-a4fb-3e805312a0b3.png" />

## Starting Point

<img width="300" src="https://user-images.githubusercontent.com/13596067/144015795-21779ec5-51d7-4880-965d-15f410f0ea7d.png" />

<img width="300" src="https://user-images.githubusercontent.com/13596067/144013635-3142db7d-7852-4050-b68d-b7368f5353c2.png" />

**Comment by autumnfjeld** [comment]
Ah yes, I see.  Thank you @arthur791004 !!!  Going above and beyond. :) 
![image](https://user-images.githubusercontent.com/5665959/144135203-cec3c5ba-794a-43c7-82cf-cd92b4e89d7f.png)

![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)
