### ISSUE TITLE
Videos UI: We have no fallback value for videos with no `completed_seconds` value.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58775]
In cases where users of our upcoming management system for courses don't enter a "course completed" time, we'll need a fallback value in the courses library. It could be, say, 90%, or maybe ten seconds lass than the length of the video.

**Comment by andres-blanco** [comment]
I was thinking that we might want to store the `duration` attribute of the videos in seconds, just as the `completed_seconds` in order to:
 * Avoid conversions to make calculations like "90%"
 * Avoid ambiguity of the duration key format in the API
 * Duration localization might not be needed https://github.com/Automattic/wp-calypso/issues/57571

**Comment by andres-blanco** [comment]
This diff and PR implements this change: D71068-code, https://github.com/Automattic/wp-calypso/pull/58863

**Comment by kwight** [comment]
> This diff and PR implements this change

@andres-blanco I don't see how they solve this issue? I'd expect #58863 to have a check and a fallback value.

**Comment by andres-blanco** [comment]
I was talking about the change from `duration` to `duration_seconds`. I will add a new PR to implement de fallback

**Comment by sixhours** [comment]
Started working on this here D78218-code

**Comment by sixhours** [comment]
Fixed in r243193-wpcom
