### ISSUE TITLE
[Bug]: Google login — 3rd party cookie popover doesn't work on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#59022]
### Quick summary

On desktop, we show a "3rd party cookies need to be enabled" popover for the Google Login button when hovering the button.

On a mobile browsers hovering isn't possible.  Pressing the disabled button just shows the popover for a split-second, and then it's gone.

Mobile users have no idea why the button stays disabled. 

![image](https://user-images.githubusercontent.com/87168/145476792-a51b03f4-5cef-4445-9cd6-b702c6d5791e.png)

<img src="https://user-images.githubusercontent.com/87168/145476929-e66ba15d-6f30-4a09-825e-27a3667a7c72.png" width="350"/>

### Steps to reproduce

- Open a new tab on browsers (desktop & mobile) in incognito mode
- Go to https://wordpress.com/start
- Observe the Google login button

### What you expected to happen

Understand on mobile why the button is disabled.

Once we have e.g. inline text on mobile version, we should check if the [docs](https://wordpress.com/support/third-party-cookies/) we link to make sense on mobile as well.

### What actually happened

Nada.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by annchichi** [comment]
Heya @simison, I want to double-check if the issue is solved. :) 

-  @enejb and I were not able to replicate it. It seems okay with browsers like Chrome, Safari, Firefox, and Brave. 
- Also, regarding the copy, I wonder if 'Please enable "third-party cookies"...' makes it a bit hard to grasp for general users. 
Do we want to encourage them to switch to using the 'normal' one instead of the incognito one as the next step ? Just being curious here. Thanks! 🤓
