### ISSUE TITLE
is_admin() function not working

### ISSUE THREAD

**Issue by mukundthanki** [Automattic/wp-calypso#59097]
### Quick summary

Hi,

I am trying to hide some posts from a category on the front, but eventually, it hides from the admin view as well.

so I applied is_admin() conditional check, which works well for classic admin but not on calypso.
I am using the below code to hide posts:
```
add_action('pre_get_posts', 'mt_exclude_alerts');
function mt_exclude_alerts($query)
{
	if(!is_admin() && !$query->is_feed()){
		$alertsCategory = get_term_by('slug', 'alerts', 'category');
		if(!is_wp_error($alertsCategory) && $alertsCategory instanceof WP_Term){
			$query->set('category__not_in', [$alertsCategory->term_id]);
		}
	}
}
```

Thanks

### Steps to reproduce

1. Create category "alerts" and assign a post to it.
2. Check if the post hides on the front.
3. Check if the post hides on the admin view. Classic (https://domain.com/wp-admin/edit.php?post_type=post&all_posts=1) and Calypso (https://wordpress.com/posts/domain.com)

### What you expected to happen

Post which excluded conditionally using is_admin() function should be visible on admin view, both Classic and Calypso.

### What actually happened

Posts excluded conditionally using is_admin() function should be visible on both classic and Calypso admin view.

### Reproducibility

Consistent

**Comment by arunsathiya** [comment]
Thanks for submitting this issue upon on request! 

We spoke about it internally. For sites being extended in this fashion, we recommend using the wp-admin dashboard view (classic WordPress view) instead of the Calypso view. Here's how you can switch to that view: 

https://wordpress.com/support/dashboard/#access-wp-admin

For some additional context, some kind of way to avoid post showing up in the API might help too. 

I have also sent you an email with this update. Please followup on that email for any other questions, thanks @mukundthanki!
