### ISSUE TITLE
Design Picker layout improvements

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#59124]
This issue is to caputre Design Picker UI bugs reported by Mikeal p58i-bpK-p2#comment-52565.   Please refer to that comment for the visuals included that go along with the items below:

Issues to consider in improving the DP layout:
- [ ] Improve columnar layout for mid size and table size screens: Grid looks too small at around 800px width, I would’ve expected 1 column:
- [ ]  Improve layout of Landscape mobile category picker 
- [ ] Landscape version of preview is broken:
- [ ] Design picker categories selection on mobile looks unstyled with Firefox
- [ ] Desktop preview doesn’t use the full page size well I think, and in smaller screens (e.g. 13″ macbook pro) it feels too tight. I’m basically previewing just my header (and I know I can scroll but the page is very long). I can’t get good “at glance” view of my site. 
- [ ] 
* check in with @ollierozdarz  if he has specific input.

**Comment by ollierozdarz** [comment]
> Improve columnar layout for mid size and table size screens: Grid looks too small at around 800px width, I would’ve expected 1 column

Agree. Let's make the designs turn from 2 col to 1 col at approx 116px (or closest breakpoint upwards if one is set).

> Improve layout of Landscape mobile category picker.

This looked fine in my mobile test. Do we have any more info? If so, it's probably something @annchichi can add to her list.

> Landscape version of preview is broken.
> Design picker categories selection on mobile looks unstyled with Firefox.

Defer back to Dev to investigate/fix 🙂

> Desktop preview doesn’t use the full page size well I think, and in smaller screens (e.g. 13″ macbook pro) it feels too tight. I’m basically previewing just my header (and I know I can scroll but the page is very long). I can’t get good “at glance” view of my site.

This needs some more thought. I checked it out on various sizes and it doesn't appear too bad to me - but the suggestion might mean using some kind of aspect ratio for the site image instead of a 1:1 view. Let's return to this.

**Comment by arthur791004** [comment]
I think part of the issues mentioned above has already been fixed in https://github.com/Automattic/wp-calypso/pull/58444

> Improve columnar layout for mid size and table size screens: Grid looks too small at around 800px width, I would’ve expected 1 column:

Now, there is only 1 column if the screen width is smaller than 960px

> Improve layout of Landscape mobile category picker

I'm not sure about this one 🤔

> Design picker categories selection on mobile looks unstyled with Firefox

This has already been fixed and looks as follow with Firefox

![image](https://user-images.githubusercontent.com/13596067/146334481-dab22768-62f6-4483-8b40-cfe52bc4c9ff.png)

> Landscape version of preview is broken:

> Desktop preview doesn’t use the full page size well I think, and in smaller screens (e.g. 13″ macbook pro) it feels too tight. I’m basically previewing just my header (and I know I can scroll but the page is very long). I can’t get good “at glance” view of my site.

I've adjusted the height of the preview and here is the screenshot. If the preview looks weird under certain screen, feel free to let me know 🙂

Landscape
![image](https://user-images.githubusercontent.com/13596067/146335138-3b6831d8-a79a-41e7-b52f-2c75e26f1db1.png)

13" MacBook pro
![image](https://user-images.githubusercontent.com/13596067/146334999-d8a8b236-1fb8-4379-be13-a52e46c4c36c.png)

**Comment by autumnfjeld** [comment]
Thanks for following up with these @arthur791004 .   

> I've adjusted the height of the preview and here is the screenshot. If the preview looks weird under certain screen, feel free to let me know 🙂

Looks better to me.

**Comment by ollierozdarz** [comment]
Yes! These are looking good @autumnfjeld @arthur791004!
