### ISSUE TITLE
Error when installing on Windows

### ISSUE THREAD

**Issue by localpcguy** [Automattic/wp-calypso#592]
I run Windows 10, and I've tried to install both with the standard CMD prompt and with Cmder. I have Clink and GNU for Windows installed, so make tries to run the makefile but it fails. The error message is as follows:

    > make run
        File not found - *.scss
        FIND: Parameter format not correct
       
        module.js:340
            throw err;
            ^
    
        Error: Cannot find module 'C:\Program'
            at Function.Module._resolveFilename (module.js:338:15)
            at Function.Module._load (module.js:289:25)
            at Function.Module.runMain (module.js:457:10)
            at startup (node.js:138:18)
            at node.js:974:3
        make: *** [node_modules] Error 1

I can (it seems) get a little farther by adding `SHELL=C:/Windows/System32/cmd.exe` to the beginning of the Makefile, but then the error is:

    The system cannot find the path specified.
    File not found - *.scss
    FIND: Parameter format not correct
    ! was unexpected at this time.
    make: *** [githooks-commit] Error 255

Before I started debugging further into the Makefile, I wanted to find out if it has ever been tested on Windows or if Windows is not a supported system at this time? Or am I just missing something?

**Comment by Viper007Bond** [comment]
>  Error: Cannot find module 'C:\Program'

Completely blind guess but that looks like an error that stems from not wrapping paths in quotes. The space in `Program Files` is likely at fault.

**Comment by Tug** [comment]
My guess is that `shell find` at [Makefile#L29](https://github.com/Automattic/wp-calypso/blob/master/Makefile#L29) won't work on windows because the find command on this platform is not the same.
@localpcguy I don't think it has ever been tested on windows yet! The Makefiles use unix commands mostly so the windows port probably won't be a breeze.

**Comment by stephanethomas** [comment]
For your information @localpcguy, we have a development environment for Calypso running on [Vagrant](https://www.vagrantup.com/) that will be released soon. That way you won't have to deal with configuration issues such as this one.

**Comment by localpcguy** [comment]
Yup, I was diving deeper and every time I fixed one line (i.e. adding quotes, fixing other Windows shell related issues), another one would error, so I figured it hadn't been tested on Windows. 

I'm assuming Vagrant will spin up a Linux VM for development?

**Comment by nb** [comment]
@localpcguy exactly.

**Comment by alexdresko** [comment]
Is there a plan for getting it to work in Windows? Please?

**Comment by Viper007Bond** [comment]
@alexdresko: The [Vagrant](https://www.vagrantup.com/) setup that @stephanethomas mentioned is so much easier than trying to deal with getting it running natively on Windows, even if there weren't any bugs in our configuration files. You just `vagrant up` and that's it -- it automatically downloads and installs all of the required dependencies, even checking out Calypso itself. Even if I used Mac OS or Linux instead of Windows on my machines, I'd still go that route personally. It's nice having it self-contained and not worrying about having the right versions of things installed.

The alternative is requiring the installation of Cygwin or whatnot in order to be able to run `make` and other unix commands. It's a serious pain in the ass. Trust me, I tried before @stephanethomas told me about the Vagrant setup he made. I've been using it for a few months and it works like a dream.

We're working on releasing it soon.

**Comment by localpcguy** [comment]
While that is your opinion @Viper007Bond, I believe that if there is a desire to get Calypso widely adopted for open source WordPress, it must work on Windows (and not through a Cygwyn-style workaround). One of the best things about WordPress is that it runs on a variety of OSes, and the core technology (Node) also runs well on Windows as well, so that isn't a barrier. As far as I can tell, the only serious barrier (I haven't done a deep dive) is the installation/build being driven by Make instead of something cross-OS like Gulp or something similar.

**Comment by kingofhawks** [comment]
Second what @localpcguy need:)

**Comment by Viper007Bond** [comment]
#100 is related to this -- spaces in the path, i.e. `Program Files`, breaks the build script.

**Comment by alexdresko** [comment]
Why are you using make instead of gulp/grunt anyway? If gulp/grunt can do the same thing (which is what I'm wanting to find out), how difficult would it be to switch?

**Comment by zhouyongh** [comment]
+1 support to use gulp/grunt instead of make.

**Comment by Viper007Bond** [comment]
It's probably worth opening a new, separate issue stating a case for switching away from make instead of having it being buried in an issue specifically about Windows.

**Comment by alexdresko** [comment]
@Viper007Bond Done: https://github.com/Automattic/wp-calypso/issues/1193

**Comment by stephanethomas** [comment]
I just wanted to let you know that we have released this [portable development environment](https://github.com/Automattic/wp-calypso-bootstrap) based on Vagrant that simplifies the task of running Calypso on Windows.
