### ISSUE TITLE
Theme Showcase: Screenshots may appear too short for their given space at some screen widths

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#59254]
### Details 

On skivers's page (`/theme/skivers/<site>`), there is an extra space below the left screenshot:

![image](https://user-images.githubusercontent.com/3801502/146253802-f0816c18-efc8-4493-93be-12b5eac2867a.png)

The image seems to be shorter than the div's `min-height`.

**Comment by alaczek** [comment]
Thanks for the ping! The height of the screenshot container is based on browser window width (36.15vw). Because these homepages aren't very tall, I'm finding it tricky to create a screenshot that would scale up nicely - at 2560px browser width, the screenshot would need to be 735px wide by 925px high, and it just doesn't match the design proportions. It works well only with sufficiently tall home page designs really. 

So far for those single-page designs like Skivers I've been uploading a theme screenshot (1200x900). This image will look ok in a browser up to ~1530px wide. Maybe we can agree on a max browser width we're going to target and optimize the images for? I was thinking 1600 - that would require the images to be 735px x 551px.

**Comment by sixhours** [comment]
I wonder if we could just edit the showcase CSS to not expect a specific height/ratio there and have it grow/shrink on resize. (I feel like that came up when they were building out the showcase pages before, and is probably not as easy as I'm making it sound, too. 😅)

Let's set this aside for now, we have more pressing issues with theme activation on Jetpack and Atomic sites to work through.

**Comment by nelsonec87** [comment]
> I wonder if we could just edit the showcase CSS to not expect a specific height/ratio there and have it grow/shrink on resize.

+1 
In the long run it'd be better not to worry about every new theme screenshot ratio.

**Comment by fushar** [comment]
We have fixed this via:

- #79277 (cc: @taipeicoder)

Specifically for Skivers theme, we now show an iframe to the demo site instead. See:

- #79896

We're closing this issue 😄
