### ISSUE TITLE
Videos UI: Investigate the "set in Media Library" link for videos.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59337]
In the videos UI course management system, we need to add posters (a representative static image) for each video, and we've done this so far with the featured image. There's another related-sounding link on the video edit view called "set in Media Library" that should be investigated as another possible better way to handle posters.

<img width="832" alt="Screen Shot 2021-12-16 at 4 34 27 PM" src="https://user-images.githubusercontent.com/349751/146469272-06582daf-d9eb-4fec-a936-915981b88698.png">

**Comment by andres-blanco** [comment]
Actually this is really useful since it provides a way to set the poster from the web ui instead of loading a new image.

### Instructions
1. Go to a video and click in `Set in Media Library`.
2. Select the video you want to edit ![image](https://user-images.githubusercontent.com/375980/147776546-ab0a80b6-fca2-4b40-bb6b-ebf8aeaa772f.png)
3. Press the `Edit` button on the top bar: ![image](https://user-images.githubusercontent.com/375980/147776567-0c38de2d-76b8-4176-893d-8790d49cc3b4.png)
4. Click on the `Edit Thumbnail` button on the top right of the video: ![image](https://user-images.githubusercontent.com/375980/147776611-7285ac7a-c891-4035-99fc-6eb4eb1f5a03.png)
5. Press play and pause when you see what you want to use as a poster.
6. Click the `Select Frame` button ![image](https://user-images.githubusercontent.com/375980/147776711-99dd03a4-421b-4813-a8d8-dd5086b7e01d.png)

**Comment by andres-blanco** [comment]
Read from thumbnail implementation D72351-code

**Comment by kwight** [comment]
Amazing, so much better than the manual screenshot process. ❤️ Diff approved, merge away.
