### ISSUE TITLE
FSE Beta: periodically autosave entities in the Site Editor

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#59371]
Core currently doesn't have drafts and autosaving in the Site Editor. Adding that will probably take a while, so we should look into some temporary measures that could make things better for WP.com.

@mtias proposed the following:

> I’d say that the role of the site editor in signup for WP.com is a bit different, though, and you could consider forcing saves as auto-saves on regular intervals without much problem since you are not concerned with draft states on already published entities because the site is presumably not live yet.

We should investigate ways to implement this and assess the UX consequences of this change.

**Comment by vindl** [comment]
Comment thread discussion p58i-bAv-p2#comment-52747

**Comment by zaguiini** [comment]
Discussion: paYE8P-1np-p2

**Comment by zaguiini** [comment]
One way of doing that would be to implement changesets.

The idea is to initially implement a single draft state so one could have an immediate backup point. From there, we could extend this functionality by implementing multiple draft versions and, most importantly, finally allowing previews directly in the browser instead of inside the editor.

The draft state would contain several bits of changed information including, but not limited to:

- current template;
- contents of the template;
- global styles;
- block global styles;
- option changes.

I think the most practical solution, for starters, would be to store a JSON in the database as a custom post, just like we do in the Customizer.

In fact, there are already [some thoughts on using the Customize API](https://github.com/WordPress/gutenberg/issues/29398#issuecomment-826356763) and a plugin called [wp-customize-posts](https://github.com/xwp/wp-customize-posts), so it looks like this is the right direction. Thoughts?

**Comment by vindl** [comment]
We decided to punt this work for now based on the discussion in paYE8P-1np-p2.
