### ISSUE TITLE
Marketplace: advertise the discount on annual plans

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59397]
Users selecting an annual paid plugin subscription will also benefit from a discounted price. How can we advertise that discount?

|Monthly | Annually|
|-------|------|
|<img width="1199" alt="SS 2021-12-20 at 11 20 47" src="https://user-images.githubusercontent.com/12430020/146743462-0fbfa413-f49b-4d85-aa93-2e50b2cc1a55.png">|<img width="1191" alt="SS 2021-12-20 at 11 21 07" src="https://user-images.githubusercontent.com/12430020/146743485-8859e1ab-6463-49f2-86bb-a8d10b9d18a9.png">|

**Comment by cpapazoglou** [comment]
Here is how it displays in the start new site
<img width="1573" alt="SS 2022-01-06 at 14 44 24" src="https://user-images.githubusercontent.com/12430020/148385005-e79b534f-1cac-4aa6-ad0f-c36b8b04804e.png">

we are using a select dropdown in mobile breakpoints so replicating above is not straightforward.
<img width="606" alt="SS 2022-01-06 at 14 49 18" src="https://user-images.githubusercontent.com/12430020/148385484-d9edb8a0-4f75-45e2-949f-0102edd0b5a6.png">

Also, when upgrading from a personal or premium the price stated should factor in the pro-rated credits of the current plan.

**Comment by SaxonF** [comment]
@cpapazoglou while looking at this I also started exploring what it would look like with monthly/yearly more closely mapped to the price itself.

Using a toggle
![image](https://user-images.githubusercontent.com/1072756/148890985-4758e78d-33cb-4299-a4a5-28e2b85f2fe1.png)

Using a switch
![image](https://user-images.githubusercontent.com/1072756/148890782-2954fb6e-5f34-43d6-a915-22c21db50f26.png)

Keeping switch in header but just highlighting savings. This might be an easy first step.
![image](https://user-images.githubusercontent.com/1072756/148890810-dfbff97d-41f5-4672-bfb6-bdd3c31388e3.png)

Long term leaning towards option 2 but unsure whether it provides enough clarity as to whether it will be billed monthly/yearly. Could change it so that it would be "$197 per [month/year]".

**Comment by SaxonF** [comment]
One more and I think this is the direction we'll go in after chatting with the design team
![image](https://user-images.githubusercontent.com/1072756/149040561-98c3f05a-512d-419d-98b7-ef6949b632ec.png)

**Comment by allilevine** [comment]
Pattern used in the pricing pages.

**Comment by SaxonF** [comment]
I'm going to make this a little easier so we don't have to touch the structure of the page. I think that the price section of the plugin header probably needs a revisit at some point and at that time we can move the price toggle.

For the time being however, let's just add the savings to the existing monthly/yearly toggle.

![image](https://user-images.githubusercontent.com/1072756/153982435-f963f1f7-177f-4365-a17f-5d1d07ad8b14.png)
![image](https://user-images.githubusercontent.com/1072756/153982446-77ffa74e-d234-4ff5-b5fe-7d4484284e36.png)
![image](https://user-images.githubusercontent.com/1072756/153982462-80c78909-f341-48f4-b4e9-82c7ae85213c.png)

Acceptance criteria:
- On the plugin detail page, we show the yearly savings in dollars on the annual plan within the toggle
- The savings are using the green.60 color value (007017)
- On mobile, we show an abbreviate version of this on the dropdown option (Annual price -$51)
- On mobile, when the annual plan is selected, the colour of the saving should be in white

**Comment by allilevine** [comment]
@cpapazoglou Can you confirm the annual discount for this one? It looked like 10% to me but I see 15% mentioned here: pdh6GB-66-p2

**Comment by cpapazoglou** [comment]
> @cpapazoglou Can you confirm the annual discount for this one? It looked like 10% to me but I see 15% mentioned here: pdh6GB-66-p2

I think we should be calculating the discount and price difference dynamically for each product.
