### ISSUE TITLE
Atomic sites: Global Styles missing with some themes

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#59396]
## Summary

Twenty Twenty-One has no option to change Global Styles. If we have changed the custom font while using a different block based theme, and now we want to change the font to the default theme font we need to change the theme, reset the font to default, and change our theme back to Twenty Twenty-One.

UPDATE: This issue is limited to Atomic Sites.

## Steps to replicate

1- Go to any page editor while using Twenty Twenty-One

## Result

Global styles option won't appear. 

## Expected

To see the Global Styles option like any other block based theme. 

![Markup 2021-02-06 at 12 47 38](https://user-images.githubusercontent.com/24919469/107127117-954b3e80-6879-11eb-9ae9-378dced68871.png)

* User report: #3712817-zd

**Comment by scruffian** [comment]
This has been fixed in r59062-wpcom

**Comment by filipanoscampos** [comment]
@scruffian 
Hi! I stumbled on this issue again on ticket 4370483-zd-woothemes.
I also made some experiments with my test sites and was able to replicate the issue on my Atomic Busines sites.

@kriskorn also helped me confirm this. 
Do you know who I should ping about this issue?
Thanks!

**Comment by scruffian** [comment]
@jeffikus should we add this to our backlog?

**Comment by scruffian** [comment]
This looks like an issue with the Editing Toolkit and corresponding features, not a themes issue, so I've moved it to wp-calypso.

**Comment by formosattic** [comment]
+1 33429033-hc

Theme: Exford

Global Styles showed up after activating plugin WordPress.com Editing Toolkit.

**Comment by Sandkorner** [comment]
Another issue it seems. 

4712079-ZEN

Theme: Twenty Twenty One

User has active Editing Toolkit plugin:

<img width="791" alt="Screenshot 2022-01-23 at 17 17 09" src="https://user-images.githubusercontent.com/71094068/150685437-8ac6e28a-ac7d-4070-a877-e14a8f9d3062.png">

Still no option for Global Styles in the editor.

**Comment by JoshuaGoode** [comment]
@Sandkorner For your user's case with `twentytwentyone`, this is because the site had the incorrect version symlinked.

The Atomic platform serves two versions of the theme, the upstream version from WordPress.org and a special WPCOM version.

In some cases a WPCOM site might end up with the WPORG version symlinked.

To resolve, we can break the symlink and then install the theme from Calypso -- the proper WPCOM version is installed.

I fixed it for that specific site and discussed with the HE working on the issue at the time @ahmadbaig1 
p1643046046173000-slack-C3GP81E05 

#### Workaround

1. Remove the folder for twentytwentyone to break the symlink.
2. Reinstall twentytwentyone via Calypso, WP-Admin, or `wp theme install twentytwenty.` 

This will get the proper WPCOM-specific version symlinked on your WoA sites.

#### Internal discussion

More on this internally here: p9o2xV-1LC-p2#comment-5395

cc @jeffikus @scruffian it can be a theme issue, I suspect it is in most cases. But, more of a platform symlinking issue.

**Comment by jordesign** [comment]
@kriskorn pinging you to see if you get the impression this is a platform level issue which still needs addressing? I'm only seeing one additional report in the past year...

**Comment by kriskorn** [comment]
@jordesign I can see that with a properly symlinked Twenty Twenty-One theme, the Global Styles option is there, so it seems the issue might mostly happen only when there is a .org version of the theme active on a site, [as Joshua has described here](https://github.com/Automattic/wp-calypso/issues/59396#issuecomment-1020380212). 

With that said, I think we can go ahead and close this one and help customers out with properly activating a symlinked theme to see Global Styles.

**Comment by jordesign** [comment]
Awesome - i'd agree with that too. Thanks for the gut check - consider it closed!
