### ISSUE TITLE
[Bug]: Fix checkout which freezes when G Suite is removed from shopping cart

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#59414]
### Quick summary

The following error is triggered in the checkout when G Suite is removed from the shopping cart by the backend - when the corresponding domain registration is removed by the user:

![image](https://user-images.githubusercontent.com/594356/146788136-2996edf5-e49f-49f5-80dd-3d90aacb592b.png)

> G Suite has been removed from your cart because it is no longer valid (you may have removed the associated domain).

### Steps to reproduce

1. Open the [`Domain Search` page](https://wordpress.com/domains/add/)
2. Click any `Select` button to access the upsell page
3. Fill in the Google Workspace form
4. Click the `Add` button to access the checkout
5. Assert that there is a domain registration and Google Workspace account in your shopping cart
6. Click the `Remove from cart` link for the domain registration
7. Click the `Continue` button to confirm the removal
8. Assert that the error mentioned above is displayed

### What you expected to happen

Be redirected to the `Plans` page (or another page)

### What actually happened

The placeholder for the checkout page is shown, and I'm not redirected to another page

### Reproducibility

Consistent

/cc @sirbrillig

**Comment by stephanethomas** [comment]
Well, actually it also happens for Professional Email:

![image](https://user-images.githubusercontent.com/594356/146789969-131858f5-d506-47ec-9125-393a453790fb.png)

**Comment by sirbrillig** [comment]
I'm going to research this today but I wonder if it was related to https://github.com/Automattic/wp-calypso/pull/58834...

**Comment by sirbrillig** [comment]
It was indeed caused by that change, because now the code that would redirect you back to the plans page when you have an empty cart will not trigger since there is an error in the `removeProductsFromCart` action:

https://github.com/Automattic/wp-calypso/blob/77238537a28244bfcf4bdd3c2be1380b11892ce4/client/my-sites/checkout/composite-checkout/hooks/use-remove-from-cart-and-redirect.ts#L53-L61

And because we do not show the empty cart page if we are in the process of deleting to avoid a flash of the empty cart page before the expected redirect:

https://github.com/Automattic/wp-calypso/blob/77238537a28244bfcf4bdd3c2be1380b11892ce4/client/my-sites/checkout/composite-checkout/composite-checkout.tsx#L879-L881

However, this is not necessarily incorrect behavior. If there was a real error in performing an action, we might want that error to be displayed to the user which a redirect could hide. The real issue is that the notice about removing an extra product from the cart isn't actually an "error"; the operation did complete successfully.

I might try to solve this from several angles, but the first and simplest may be to change these error messages (and many others, it turns out) into info messages instead on the server.

At the same time, it's not great UX to just show a loading page forever here. I'll see if I can, for example, show the empty cart page instead if there are errors.

**Comment by sirbrillig** [comment]
Changing the errors to info messages is a little more complex so for now I'm just going to solve this by showing the empty cart page in case of an error.

**Comment by sirbrillig** [comment]
To be clear, the problem with making the notice not an error has to do with how the shopping-cart endpoint works:

When you click to remove the domain, what actually happens is that the cart without the domain is submitted as a new cart to be updated; then when trying to add the G Suite product, it fails with the above mentioned error because the domain has been removed.

So the action of updating the cart fails, but the action of removing the product works just fine. 🤔  I wonder if maybe `removeProductFromCart` should be hard-coded to never fail?
