### ISSUE TITLE
Cover block: Nested block font colour is always set to white in the editor but not accurately displayed on the frontend.

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#59434]
### Quick summary

When a Heading or Paragraph Block is nested inside a Cover Block, the font is shown as white in the editor. The same content shows as black when the post/page is viewed/previewed.

### Steps to reproduce

1. Add a Cover Block and add some media to it or set a background colour.
2. Add 2x Heading or Paragraph Blocks.
3. Set one to use the text colour of your choice and leave the other one as it is.
4. Both blocks will show their content as white in the editor.
5. Preview the page to see that the text with the default colour will now show as black in the preview.
6. Change the Cover Block's background colour or image and note that the block with the default colour will not change as it does in Core.

### What you expected to happen

I expected:

1. The editor's default font colour for theses nested blocks to be accurately represented on the frontend.
2. The default font colour for theses nested blocks to change as the background image/colour does.

### What actually happened

Unlike Core, where the font colour changes depending on the background colour or image, WordPress.com sites do not/no longer change the text colour dynamically.
&nbsp;

**Editor view:**

<img width="887" alt="Editor colour" src="https://user-images.githubusercontent.com/66711744/146883059-6abf7e54-38c7-44d0-a591-56fb565079be.png">

&nbsp;

**Preview view:**

<img width="831" alt="Preview Color" src="https://user-images.githubusercontent.com/66711744/146883067-c80a2e01-cb7c-4330-8d65-61bf1fb6537e.png">

### Context

The change appears to be a regression. As a customer reported they noticed the switch from white to black font colours on a page with multiple Heading and P Blocks nested  in Cover Blocks appx 2 days ago.

29468458-hc

The site had a mixture of text already set to white manually in the editor and text with a default font colour which presents as white in the editor. It was this "default" text that reverted to Black appx 2 days ago at the time of this report.

I helped the affected customer manually set their nested Headings and Text to white, which resolved the issue.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No. Tested on Exford and Blockbase

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Set the desired colour in the editor directly.

**Comment by aleone89** [comment]
Just to add, I am also experiencing this issue and can replicate consistently as well.

**Comment by formosattic** [comment]
> Unlike Core, where the font colour changes depending on the background colour or image, WordPress.com sites do not/no longer change the text colour dynamically.

The dynamic colour change is also controlled by the Opacity set in the Cover block.
![troubleshooting](https://user-images.githubusercontent.com/15944096/147544521-58fbf07a-9382-46f8-ab16-b611b85d797e.gif)

From my testing the default color set renders is consistent:

| Editor  | Preview |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/147545051-33403e29-0a63-4d66-8eed-63a7298e1c18.png) | ![image2](https://user-images.githubusercontent.com/15944096/147545161-c81db4b6-5bf8-4633-94a7-8a3d90b0b56b.png)  |

@inaikem @aleone89 , can you see if the issue still happens on your end?

**Comment by freelylovinglife** [comment]
Here is another report: 4732174 - ZD

**Comment by as-esu** [comment]
zen-4763815
zen-4776594
I could reproduce the issue on my test site when activating the Rockfield/Exford themes with its homepage demo content. The last section on the Rockfield theme using the cover block shows the text in the front end as expected ( white colour ).
**Editor view:**
![Rockfield-1](https://user-images.githubusercontent.com/64140926/153368589-2a63872e-0139-4b4b-9baf-5d7623c58f4f.jpg)
**Preview:**
![Rockfield-2](https://user-images.githubusercontent.com/64140926/153368612-3d8e0315-2140-4fa3-94e1-5283d5ef9d1a.jpg)

I could also reproduce the issue when nesting heading and paragraph blocks inside the cover block that had a media background. The issue was not apparent if I was using a cover block with a background colour. 
Changing colours in Customizer did not impact block colours nested in cove block.

**Comment by jartes** [comment]
7207370-hc

**Comment by janmckell** [comment]
This user looks to be affected by same:
4870396-zen
32701618-hc

**Comment by cintacks** [comment]
Another one: 34950507-hc

This was due to auto-translation on the site. When viewing English, color settings would apply, but when viewing the site in French, they remained black. 

I fixed this with CSS (overriding the `mark` element that was keeping the text black, even though it's class said otherwise):

```
mark.has-inline-color.has-white-color {
  color:white;
}
```

**Comment by as-esu** [comment]
4776594-zen
The black colour appeared on the front end even though white was specified in the editor for the **Paragraph** block nested within the **Cover** block. Grouping the **Paragraph** block and setting the white text colour for the Group solved the issue.
Theme: Twenty-Twenty.

**Comment by aleone89** [comment]
Another report here: hc-35007280

I had to write this CSS

`
.wp-block-cover__inner-container p {
    color: white;
}`

**Comment by inaikem** [comment]
Just a quick note to say both @vajrasar and I were _**not**_ able to replicate this on fresh Jurassic Ninja sites.

**Comment by cuemarie** [comment]
It's been a while since this has had attention, so I re-tested today.

📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Inconsistent - theme dependent
- Tested on Atomic – Inconsistent - theme dependent

📌 FINDINGS/SCREENSHOTS/VIDEO
- On Gutenberg 16.2.1 (on AT) and Gutenberg 16.3.0 (on Simple), both using Theme TT3, I could not replicate this issue.  The live site matched the theme-chosen font color for nested content inside the cover block.
- Also tested in theme Twenty Twenty, and so no discrepancy between editor & live site.

#### Screenshots/Recordings

_AT, Theme: TT3_

https://github.com/Automattic/wp-calypso/assets/27249804/bcc4fb61-ef6a-4993-9281-6208bea57e9b

_Simple, Theme: TT3_

https://github.com/Automattic/wp-calypso/assets/27249804/d55eb6cf-6909-4693-bfca-f65643a0265d

---

- On both Simple and AT using theme **Exford**, I was able to see more specific problems.  The theme's homepage demo Cover block shows some inconsistencies between the editor and the live site - seems like messing with they overlay slider is how to trigger the issue:

_Brand new AT site, Theme: Exford_


📌 ACTIONS
- Closed as no longer relevant / could not replicate
- Creating a new report specific to Exford: https://github.com/Automattic/themes/issues/7280

📌 Message to Author
- If this pops up again, please open a new report specific to the theme for now. Feel free to reference this issue in the report.
