### ISSUE TITLE
FSE beta: Exporting templates doesn't work

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#59527]
### Quick summary

Within Site Editor, the Export feature doesn't work and result in "Zip Export not supported" message.

### Steps to reproduce

1. Open Site Editor
2. Click three dots menu at top right
3. Click `Export`

### What you expected to happen

Be able to download the templates and their parts. 

### What actually happened

"Zip Export not supported" message is displayed in lower left corner.

![image](https://user-images.githubusercontent.com/39308239/147235702-fa4380e3-55a3-4676-af92-e8f05fe5e46f.png)

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

Note from @cometgrrl : Edited to include the correct text of error message as shown in screenshot "Zip Export not supported" not "Zip File not supported".

**Comment by formosattic** [comment]
Also able to reproduce this issue.

**Comment by KokkieH** [comment]
Another report in https://wordpress.com/forums/topic/fse-site-export-customized-templates/?view=all

**Comment by creativecoder** [comment]
This issue appears to only affect Simple sites. The error returned is

```json
{ "code": "missing_zip_package", "message": "Zip Export not supported." }
```

which indicates the `ZipArchive` php class is not available during the API request to `wp-block-editor/v1/sites/{site}/export`. This seems to be intentional: pMz3w-91R-p2. Other import/export features that rely on ZipArchive use async jobs, where this class is available.

I think to fix this we'd need to override the the API endpoint to create an async job that builds the archive and emails the user a link to download it when it's done. And add some kind of indication in the UI that's what's happening.

As a work-around, you can use the regular export feature, just be sure to "Export all" so that the custom templates get included in the export.

<img width="745" alt="Screen Shot 2022-03-01 at 15 49 03 1" src="https://user-images.githubusercontent.com/1699996/156254807-b7f956bf-a44b-45e5-bb15-fe14876a9620.png">

cc @Automattic/team-calypso-platform @vishnugopal

**Comment by desnum** [comment]
Another case in 34130736-hc

**Comment by Addison-Stavlo** [comment]
Given that fixing this in the editor[ may take some time](https://github.com/Automattic/wp-calypso/issues/59527#issuecomment-1055896206) and that we can "Export All", would a temporary measure to hide this "Export" button in the Site Editor be useful to help customers avoid confusion?

edit - @creativecoder also suggested temporarily linking it to the export tool in calypso, which may also be a good way to handle this gracefully until it is fixed.

**Comment by katiebethbrown** [comment]
Adding a +1 as I ran into this working with a Team51 site.

**Comment by zdenys** [comment]
Related:
- https://github.com/Automattic/wp-calypso/issues/51442
- https://github.com/Automattic/wp-calypso/issues/61496

**Comment by zaerl** [comment]
> I think to fix this we'd need to override the API endpoint to create an async job that builds the archive and emails the user a link to download it when it's done. And add some kind of indication in the UI that's what's happening.

I'm on it. Of course, we can generate a new async job around `gutenberg_generate_block_templates_export_file` and send an email as it happens in other export calls.

If this is the way we want to take then some small changes will be necessary on FE. Let me know.

**Comment by vishnugopal** [comment]
@zaerl Can you estimate the difficulty of the async job solution? If it's likely to take a while, let's move ahead with the temporary renaming.

**Comment by creativecoder** [comment]
Noting that the Site editor export now gives additional files that are not included in the regular WordPress export, including theme.json, php templates, and theme css. (https://make.wordpress.org/core/2022/03/16/whats-new-in-gutenberg-12-8-16-march/#highlight-3)

I'm not sure how important these are, given you can always grab these files from the theme, separately, but wanted to note the change, as the regular WordPress export is no longer equivalent.

**Comment by zaerl** [comment]
> @zaerl Can you estimate the difficulty of the async job solution? If it's likely to take a while, let's move ahead with the temporary renaming.

I think this will be a couple of days of work on the WPCOM side.

**Comment by vishnugopal** [comment]
@zaerl As discussed, let's do this then! :-)

**Comment by creativecoder** [comment]
> I think this will be a couple of days of work on the WPCOM side.

That would be amazing! I'd be very surprised if it was only a couple days, but please keep us updated. Also, if hooks or otherwise are needed to make it easier/possible to override the Gutenberg export process, let us know.

**Comment by zaerl** [comment]
@creativecoder after a study of the problem, these are my considerations:

The code can work using an async job and I've tested it in my diff. It is straightforward; it has the same interface as the main `export` endpoint; it sends a similar email with a link to an auto-expiring zip file. I only need an `action` on `gutenberg_generate_block_templates_export_file` in order to hook the process and run it.

Async jobs are a peculiarity of WPCOM and can't be used on a standalone installation of WordPress, which should rely on an inline creation and stream of a zip file which is exactly what is happening right now. Keep in mind that the zip library is enabled by default on standard installations of PHP but not on WPCOM.

So what can we do? We can handle both situations and override the result on the frontend.

1. Actual situation: a zip file streaming directly to the browser
2. New situation: a job is started and it sends an email when the zip has been created

Or simply generate a custom behavior only for WPCOM. Feel free to contact me so we can find together the best solution to this problem.

cc @vishnugopal

**Comment by Addison-Stavlo** [comment]
>  a job is started and it sends an email when the zip has been created

Are there any updates on where we are at resolving this or any blockers?

**Comment by zaerl** [comment]
I've concluded that patching the frontend like what happens on `gutenberg-wpcom-a8c.js` isn't the best. I've seen that the DOM is changing from version to version like as is normal, and maybe we handle a specific structure that then perhaps be changed and the patch breaks.

What we can make (see here D78100-code) is to use a backup method that is used elsewhere in WP. If `ZipArchive` is not active, we use `PclZip` instead, guaranteed to be there. This diff is used to test these changes; it only modifies Gutenberg code to see the results.

So there are two ways that we can follow:

1. We create a new PR, and we modify https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/block-template-utils.php#L39 to add the `PclZip` backup method when the [native zip library](https://www.php.net/manual/en/zip.installation.php) is disabled. It is disabled in hosting services like WP, Bluehost, etc., cause it can be used for resource-heavy operations. Our operation here is very lightweight. In this way, Gutenberg will be more usable in those hosting that have restricted environments
2. We create an action on `gutenberg_generate_block_templates_export_file` that can be intercepted so the user can create a method to generate the export file before generating that error

Now I need to investigate a new error ("An error occurred while creating the site export.") which occurs even in a clean codebase that generates a valid .zip like what happened before in staging. An exception rises, maybe something has changed.

cc. @creativecoder @Addison-Stavlo @vishnugopal

**Comment by vishnugopal** [comment]
@creativecoder Any suggestions on which one of the 2 approaches we should choose above? And is using PclZip as a fallack option okay in this case?

**Comment by creativecoder** [comment]
> add the PclZip backup method when the [native zip library](https://www.php.net/manual/en/zip.installation.php) is disabled

- In general, this sounds it could be a nice enhancement to Gutenberg to be more resilient in varied hosting environments
- For WP.com, I would ask systems (recommend submitting a systems request). My understanding from pMz3w-91R-p2 is that offloading any potentially long running tasks to async jobs is preferable. I'm not sure if using PclZip changes any of the reasoning there, or not.

> We create an action on gutenberg_generate_block_templates_export_file that can be intercepted...

This sounds like it would be the best for performance, and most in line with existing WP.com import/export, as long as we can create an acceptable user experience in the UI. I'd imagine Gutenberg would be open to adding hooks (server side) and/or slots (client side) here to make this feature more flexible, as long as we can clearly articulate the need and benefits.

**Comment by zaerl** [comment]
The zip library has now been enabled on WPCOM because is already in the WP [recommended list of extensions](https://href.li/?https://make.wordpress.org/hosting/handbook/server-environment/) so no changes must be made to the code. The export is a very lightweight operation. You can find my request on pMz3w-fex-p2. Refactoring can be performed but I think this is outside the scope of this particular bug.
@vishnugopal

**Comment by zaerl** [comment]
On production now the `Accept` header must be changed and specify `application/zip` because the base header is `*/*`. I will create a small PR to fix this. See https://core.trac.wordpress.org/ticket/44534.

**Comment by creativecoder** [comment]
> The zip library has now been enabled on WPCOM

Nice and a good reminder that sometimes we just need to ask!

**Comment by rakshitwesley** [comment]
Another report in 5249703-zd-woothemes

**Comment by vishnugopal** [comment]
We've pushed a merge to Gutenberg that fixes the remaining issue here, and we're waiting for a Gutenberg release to confirm this is fixed on WPCOM.

**Comment by zaerl** [comment]
A fix for simple sites can be found here: D84503-code and then we have covered 100% of the cases.

**Comment by vishnugopal** [comment]
This is tested and fixed on Simple and Atomic sites. Please reopen if there's any issue! Thanks for patience 🙏🏽
