### ISSUE TITLE
Incorrect number of mailboxes in Billing History for Google Workspace Starter purchase

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#59652]
### Quick summary

User had purchased the first license of Google Workspace Starter on 2021-12-15 by paying the promotional price $36.

Then on 2021-12-16, user purchased the second license by paying the actual price $72.

In total, the user had purchased only 2 licenses. However, the Billing History indicates that the user purchased 2 mailboxes in the second purchase.

Store Admin is showing the correct information. i.e: "1 new license".

But Billing History shows "Purchase of 2 mailboxes".

Due to this incorrect data, user thought they were charged for 3 licenses in total.

### Steps to reproduce

Not sure how to reproduce this. You can find details for the user with ID 172475058

### What you expected to happen

The number of mailboxes in Billing History Store Admin should match the number of license in Store Admin

### What actually happened

The number of mailboxes in Billing History Store Admin did not match the number of license in Store Admin

### Context

User report: 4652166-zen

**Comment by Greatdane** [comment]
Not sure if this is like an API issue with Google or just a Calypso Billing error. 

CC: @arunsathiya (email lead)

**Comment by arunsathiya** [comment]
Everything looks okay to me too. I am not sure why Calypso billing history would show 2 additional licenses were purchased. I'll tag @Automattic/letero for help here.

**Comment by daledupreez** [comment]
I did some additional investigation, and I believe that this issue was caused due to a bug that specifically meant we didn't track quantity upgrades like this correctly when an asynchronous payment method like PayPal was used. We corrected that issue for new purchases in D71445-code, which was deployed to production on 2022-01-13.

We do have some missing data for existing transactions like this one, but we don't believe we'll be able to fully recreate the data, so it's unlikely that we'll be able to do that cleanup in the near future. I am going to close this issue, but if we see enough users getting tripped up or confused by this issue, it would be good to make sure we note that in the issue so we can revisit performing cleanup on the existing data.
