### ISSUE TITLE
Marketplace: Add a home banner advertising the paid plugins

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59657]
Let's add the content of our announcement modal
<img width="902" alt="SS 2022-01-03 at 10 52 50" src="https://user-images.githubusercontent.com/12430020/147913097-f4926264-baa5-4156-a693-c4eb672d1f71.png">

to the home announcements banners section
![SS 2022-01-03 at 10 55 07](https://user-images.githubusercontent.com/12430020/147913270-bbb08ed8-4c73-4aec-9b36-42d260217936.png)

**Comment by cpapazoglou** [comment]
@emmnyc85 any clues on which of the two home sections to use?

**Comment by emmnyc85** [comment]
It might look redundant / like too much from one cross-sell to have it in those two sections, especially since they can seem to be right on top of each other. 
- I agree with including this in the Banner section, primarily as the first item shown.
- What about adding a Quick Link too? 'Explore plugins' and then that drives to the modal on the plugin page
