### ISSUE TITLE
Videos UI: Opening the video UI invalidates the wordpress.com HTTPS certificate.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59681]
I'm not sure how or why, but opening the video UI invalidates the wordpress.com HTTPS certificate (at least in Chrome).

![2022-01-03 12 08 18](https://user-images.githubusercontent.com/349751/147975365-d45599a7-c157-452a-a00a-e10d3fabecd2.gif)

**Comment by andres-blanco** [comment]
The warning is due to the wpcommedia videos urls are being generated(/wp-content/lib/courses/courses.php?r=237551#164) with `http` instead of `https`. There are two ways to go around this warning:
1. replace the http by https. (https://wpcommedia.files.wordpress.com/2021/11/video-1.mp4)
1. use the `video_highest_resolution_mp4` function to generate the video url from the CDN. This is the one that looks like the way to go but the CDN actually host low quality videos, eg: https://videos.files.wordpress.com/VfUmUJMC/video-1_mp4_std.mp4. 

@kwight do you now how can we host higher quality videos on the CDN? or it's not necessary and we can get away with replacing the http by https?

**Comment by kwight** [comment]
Ah – then maybe we can just add a `preg_replace` around L139 in `fetch_videos()` to swap the protocol to HTTPS (because it looks like that change alone still produces valid URLs). Nice find. 👍

**Comment by andres-blanco** [comment]
D72526-code
