### ISSUE TITLE
Marketplace : Option to switch to Annual billing for Plugin 

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#59694]
### What

While upgrading from simple site on a monthly plan, the checkout page gives an option to switch the Business plan to Annual.

There is no such option for the plugin, it remains stuck on Monthly, even If I change the Plan to annual. 

### Why

User should have a choice to set the tenure of the plugin purchase too.  Else it is confusing to the user at checkout. 

### How

![image](https://user-images.githubusercontent.com/4162931/148018875-40c63cdc-3f59-45d2-a4e3-d21797adc6d3.png)

Steps to replicate:

* On a simple site, add any paid marketplace plugin to cart on monthly plan (default) 
* On checkout page you will find the option to change tenure only for the plan, and not for the extension / plugin purchased. This is confusing to the user, and will cause greater confusion later when their plan is charged yearly and plugins are charged monthly.

**Comment by lsl** [comment]
This has changed a bit since the issue was created. Added needs design label because I'm not sure what we need to do here. Do we want to create a complete new [checkout summary card](https://github.com/Automattic/wp-calypso/blob/f4948a9859c50e2a538069b5a54b67d2baa81b15/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx#L66) or just change the copy around and add a new [annual plan upsell](https://github.com/Automattic/wp-calypso/blob/f4948a9859c50e2a538069b5a54b67d2baa81b15/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx#L291) section?

Similar question about the edit cart toggles, do we want to allow monthly, 1-year and 2-year plan options for plugins? Should we just match the plan term or should we allow mixed plugin term lengths?

![Screenshot 2022-02-14 at 18-14-50 Checkout — WordPress com](https://user-images.githubusercontent.com/811776/153817081-56f95405-7f7c-4216-bae0-7c261efbe7a5.png)

https://user-images.githubusercontent.com/811776/153817102-e4557200-d77c-471b-9a35-3b9aa7c779d1.mp4

**Comment by lsl** [comment]
On the implementation side of things:

The feature summary list ("included with your purchase") are [coupled to plans](https://github.com/Automattic/wp-calypso/blob/f4948a9859c50e2a538069b5a54b67d2baa81b15/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx#L79) I'm not sure how well this component will like plugin plans (are they set up the same?)

Changing plans is [external to this component](https://github.com/Automattic/wp-calypso/blob/f4948a9859c50e2a538069b5a54b67d2baa81b15/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx#L45) so I'm not sure what else in the composite checkout will need updating to handle plugin term switching. (I suspect it will respect that product slug and play nicely but its hard to say without looking into this further).

**Comment by allilevine** [comment]
> This has changed a bit since the issue was created. Added needs design label because I'm not sure what we need to do here. Do we want to create a complete new [checkout summary card](https://github.com/Automattic/wp-calypso/blob/f4948a9859c50e2a538069b5a54b67d2baa81b15/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx#L66) or just change the copy around and add a new [annual plan upsell](https://github.com/Automattic/wp-calypso/blob/f4948a9859c50e2a538069b5a54b67d2baa81b15/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx#L291) section?
> 
> Similar question about the edit cart toggles, do we want to allow monthly, 1-year and 2-year plan options for plugins? Should we just match the plan term or should we allow mixed plugin term lengths?

Great questions. It definitely seems like this needs a design decision. Although maybe the checkout page needs clarification in general if users expect an annual plan to include an annual plugin subscription.

> On the implementation side of things:

We need more information about what plugin subscriptions are, vs. plans. Are they also products?

**Comment by cpapazoglou** [comment]
This is already resolved.
