### ISSUE TITLE
Advanced SEO: Add Social and Search Previews in Editor

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5974]
Let's add a new feature to the editor that will allow a user to preview how their posts will look once shared across search platforms and social media.

![just_preview-guide_hidden](https://cloud.githubusercontent.com/assets/789137/15980393/08949b7c-2f20-11e6-8d2e-b210d49f629b.png)

Requires the search/ social network preview components to be completed first. See  #5839, #5971, #5972 and #5973

**Comment by drw158** [comment]
Idea: could be helpful, on mobile, or perhaps to eliminate the need for a sidebar nav as shown in Adam's mockups:

![artboard](https://cloud.githubusercontent.com/assets/618551/16051824/046d89a0-3227-11e6-8ec8-ec7383f1bddd.png)

**Comment by drw158** [comment]
I'm still not 100% sure on what to do here. I do like the idea of editing the meta fields right in the preview and seeing the result, but I also think a setting that like might be too buried in the preview button. Having the social previews in the preview component makes a lot of sense though.

3 ideas: 
- Put an edit button in the social preview so that they can easily access the SEO settings accordion.
- Add an Preview button in the SEO accordion that would activate the preview component.
- Just add helper text in the preview component that says something like "To edit this, view the [SEO settings](#) of your post"

I like number 3
