### ISSUE TITLE
Checkout: Error When Applying Coupon on Expired Domain

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#59945]
### Quick summary

The checkout shows a 500 error if you click to apply a coupon when trying to renew an expired domain.

### Steps to reproduce

1. Add to the checkout an expired domain
2. Add to the account's SA some paid credits
3. Add a discount coupon to the checkout

### What you expected to happen

To either apply the coupon, or show that it's not valid.

### What actually happened

It shows a 500 error and stops loading the page.

### Context

I'm not sure what exactly is causing the error, and if the account credit is relevant, but it was the scenario when testing on 4654223-zd-woothemes. Errors:

![CheckoutDomainError_2](https://user-images.githubusercontent.com/16104522/148947995-4436325a-c505-4ff5-9a1c-101af0239f49.jpg)

![CheckoutDomainError_1](https://user-images.githubusercontent.com/16104522/148947987-4af5ce42-b7ab-455d-a7d9-f26f0a438be9.jpg)

**Comment by sirbrillig** [comment]
Reproduced. The error is on the server, `Failed to read coupon in the data store.` and is thrown supposedly when a coupon does not exist. I double checked that the coupons I was trying did exist, so it is mistaken and also a weird fatal error since normally when a coupon does not exist you get this nice error message:

<img width="646" alt="Screen Shot 2022-01-14 at 11 09 29 PM" src="https://user-images.githubusercontent.com/2036909/149608313-a73d2ba3-9e43-49e3-8247-54c38c2c8dd5.png">

The fatal error appears to occur because of special logic for `WPCOM_DOMAIN_REDEMPTION_PRODUCT` when validating the coupon. It tries to fetch any coupons that match the coupon code but which are targeted for that specific product. Since the coupons we've tried are universal and not specific, the search throws the above-mentioned error. This is... confusing, though, because there's a `try`/`catch` around the code that throws the error, and yet somehow it's not being caught.

Ah, I see: the `catch` is catching `Exception` rather than `\Exception` and since the coupon code is in a namespace, it's not working correctly. This is a very subtle bug that's easy to miss. In this case it will only happen when a coupon that does not apply to a domain redemption is used on a domain redemption.

The code that triggers the error was added in D61906-code (cc @dzver, @southp, and @delputnam). I created a fix in D73121-code.
