### ISSUE TITLE
Theme Showcase: Homepage activation options unavailable after purchasing premium theme

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59996]
When activating a new block-based theme on the WP.com simple site, you have the option to choose how you want your homepage to work:
<img width="784" alt="Screen Shot 2022-01-12 at 11 24 59 AM" src="https://user-images.githubusercontent.com/2124984/149180404-dbf5bae7-2203-4ed6-9f88-a755901fabb2.png">

However, when you purchase an individual premium theme, the theme is activated on your site automatically after purchase, with no option to choose how the homepage should be set up. 

The flow looks like this:

1. On a WP.com site with a free plan, go to the `/themes/[site]` and click the three-dots menu for a premium theme like Byrne.
2. Click "Purchase". You'll be taken through the checkout flow.
3. After checkout, you'll be brought back to the Theme Showcase where the theme will automatically be activated on your site:
<img width="920" alt="Screen Shot 2022-01-12 at 11 26 41 AM" src="https://user-images.githubusercontent.com/2124984/149180889-3a3a60fb-932a-4a9a-9c50-c86f785ed5c9.png">
<img width="303" alt="Screen Shot 2022-01-12 at 11 26 48 AM" src="https://user-images.githubusercontent.com/2124984/149180901-4cacc56d-f038-4177-835e-f5c1121902da.png">

Ideally, at step 3 a user should be able to choose between using the themes' starter content or using their existing content.

**Comment by supernovia** [comment]
This is the first thing I noticed, too. I tried adding a new page thinking I could find the home page layout there for Byrne, but no luck.

**Comment by mreishus** [comment]
The root cause is different method of theme activations. 

**When activating a theme without purchase**, calypso displays the modal, collects the input from the user, and POSTs to `/rest/v1.1/sites/<siteid>/themes/mine` to start the theme switch, including if the homepage should be switched or not.

**When buying an individual premium theme**, calypso POSTs to `/rest/v1.1/me/transactions` to process the payment. When that is processed, the backend automatically changes the site's theme. I used to think the modal you see after a theme purchase was activating the theme, but no, it is already activated by the time the credit card transaction has gone through.

```
#0 wp-content/mu-plugins/premium-themes.php:23 - switch_theme(?, ?)  
#1 wp-includes/class-wp-hook.php:309 - activate_premium_theme_product(?, ?, ?, ?, ?, ?)  
#2 wp-includes/class-wp-hook.php:331 - apply_filters(?, ?)  
#3 wp-includes/plugin.php:474 - do_action(?)  
#4 wp-content/admin-plugins/wpcom-billing/class.wpcom-store.php:2376 - do_action(?, ?, ?, ?, ?, ?, ?, ?, ?)  
#5 wp-content/lib/store/checkout/steps.php:54 - add_upgrade(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  
```

To fix, we'd need to either decouple the purchase and activation, and let calypso activate after the purchase is made through its regular process, or to change the checkout process to collect the homepage switch/preserve information.

**Comment by mreishus** [comment]
Are there any ways to purchase premium themes that aren't through calypso? If we decouple the purchase and activation, those would be affected. WP-Admin, maybe?

Edit: You can purchase premium themes from wp-admin, but you're brought to wp.com/checkout, which is calypso, and you land in the calypso theme showcase when done.

**Comment by mreishus** [comment]
Created https://github.com/Automattic/wp-calypso/pull/60263 + D73399-code

**Comment by sixhours** [comment]
This is fixed by D73399-code and https://github.com/Automattic/wp-calypso/pull/60263
