### ISSUE TITLE
Signup: DSS: Add notice when a search returns no results

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#60]
We should notify the user if a search fails or returns 0 results. Right now, the previews just don't change, but that's a confusing UX.

**Comment by sirbrillig** [comment]
We've tried several mockups for how these failures would appear, and all of them are still a confusing UX. The main issue, I think, is that it's unclear to users what the DSS search field is there for above the theme list. If the field pops up an error, the user is likely to be even more confused. 

I think a better UX would be to separate the search field from the theme list by a step, so that if there are no direct results from the user's search, the default theme screenshots will be shown as-is. Effectively this will be the same result the user would get now, with no search results, except that since the interactions (search field > picking a theme) would not be on the page at the same time, the user is not forced to make the mental leap about how they are connected.

Closing this for now until the next iteration of DSS is created.
