### ISSUE TITLE
[Core] Avoid empty translation to overwrite the domain configuration

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#60111]
Tracking Gutenberg issue:  Avoid empty translation to overwrite the domain configuration

### Waiting for reply 

https://core.trac.wordpress.org/ticket/54858#ticket

### Waiting for this issue and PR

* https://github.com/WordPress/gutenberg/issues/34101
* https://github.com/WordPress/gutenberg/pull/37686
* https://github.com/WordPress/gutenberg/pull/37704

### Related issue

D65529-code
D73128-code

**Comment by autumnfjeld** [comment]
@arthur791004   We can close this, correct?
Since https://github.com/WordPress/gutenberg/pull/37704 is merged.  

And I think then that this trac issue, https://core.trac.wordpress.org/ticket/54858,  could be closed too ya ?  Could you follow up with that, add a comment that https://github.com/WordPress/gutenberg/pull/37704 is merged.

And then close this issue.

Thank you!! :)

**Comment by arthur791004** [comment]
As we need to consider backward compatibility, https://github.com/WordPress/gutenberg/pull/37704 just created a new function to avoid the domain configuration being overridden. Hence, we still to make changes to WP Core so that we can benefit from the new function. That's why I create this ticket - https://core.trac.wordpress.org/ticket/54858. But they still have concerns about backward compatibility..., so we're waiting for other core devs to chime in.

On the other hand, I think I have to spend some time verifying whether this issue exists or not and make an easy example to describe it well so that dev cores can easily understand what's the problem now.

**Comment by arthur791004** [comment]
@autumnfjeld I change my mind that we might be able to close this one as we never receive any reports about this one. We could re-open this once we get any related reports 🙂
