### ISSUE TITLE
Phone number field in Checkout adds 0s and 1s randomly for Mexico

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#60118]
### Quick summary

On WordPress.com checkout page, the phone number field is inserting 0s and 1s when Mexico is selected.

![Screen Capture on 2022-01-17 at 16-45-04](https://user-images.githubusercontent.com/33957570/149760062-06225535-4143-4ff6-8f66-0fc82716f23c.gif)

### Steps to reproduce

1. Add a domain registration purchase to your WordPress.com account.
2. Go to the checkout page.
3. Select Mexico.
4. Type digits of phone number
5. You will notice 0s and 1s being inserted into the field.the 

### What you expected to happen

Only the entered number should be added in the phone number field

### What actually happened

0s and 1s were added automatically.

### Context

User report: 33607890-hc

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Users will have to copy-paste the number.

**Comment by cometgrrl** [comment]
@Automattic/shilling  Can you take a look at this one?

**Comment by sirbrillig** [comment]
While this bug is being investigated, a workaround is to have any affected customer input the country code manually. So in this case, start entering the phone number as `+52` (which I believe is Mexico) and then the rest of the number. Starting with `+` should disable the country code guessing system which seems to be misbehaving.
