### ISSUE TITLE
wc-admin task card: Refer to the word "theme" in setup task that only includes the theme name.

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60144]
wc-admin task card: Refer to the word "theme" in setup task that only includes the theme name.

**Comment by obenland** [comment]
@lsl Could you add a bit more context here? Maybe a screenshot?

**Comment by lsl** [comment]
This was a drive by from @ianstewart, there was a setup card on the wc admin homepage that referred to setting up your theme but instead of saying "setup your theme" it said "setup hemingway" which didn't really explain what was happening unless you knew your theme name.

I believe this has been changed on the woo side:

![Screenshot 2022-01-18 at 13-20-32 Home ‹ WooCommerce ‹ wooptestupgrade — WooCommerce](https://user-images.githubusercontent.com/811776/149859605-d763ef1a-c47b-4197-815c-780aabe570da.png)

Couldn't find removal PR of the old card but there has been some [significant changes](https://github.com/woocommerce/woocommerce-admin/pull/7838/) to these since this issue was created.

Closing for now, reopen if you find it's still around.
