### ISSUE TITLE
Seller Experience: Add an e-commerce category to the onboarding theme selection.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60152]
We'll need a new category of e-commerce themes in signup. @SaxonF will work with @alaczek to come up with the new patterns.

<img width="2109" alt="Screen Shot 2022-01-17 at 11 54 58 AM" src="https://user-images.githubusercontent.com/349751/149830707-27306dcf-d90f-4ac2-b44c-570aac7e2307.png">

**Comment by blackjackkent** [comment]
@kwight I did some digging on how this list is displayed and it seems like this might not require developer work?

The categories list is generated dynamically from the list of themes -- see [client/signup/steps/design-picker/index.jsx:99](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/design-picker/index.jsx#L99) and [packages/design-picker/src/hooks/use-categorization.ts](https://github.com/Automattic/wp-calypso/blob/trunk/packages/design-picker/src/hooks/use-categorization.ts). These themes are fetched from the API at `wpcom-json-endpoints/class.wpcom-json-api-themes-v1-2-endpoint.php`.

I'm not quite clear on where the data being fetched actually lives, except that it involves ElasticSearch. But as near as I can tell, as long as we add that data with a fresh category type, it should automatically be incorporated into this screen.

**Comment by kwight** [comment]
> I'm not quite clear on where the data being fetched actually lives, except that it involves ElasticSearch.

Sounds like the next step to figure out – maybe they're categories or tags in the theme showcase? I don't remember how that works. See what it takes to get the top item to be Commerce with the recommended pill beside it.

**Comment by blackjackkent** [comment]
Did some research on this and found the documentation for the design picker at PCYsg-D3C-p2 - further discussion at p1642707515042000-slack-C0Q664T29 regarding the specific blog where these themes are stored. Basically, each theme is a post on an internal Wordpress.com site; themes with the `auto-loading-homepage` feature term are included in the design picker and the categories are automatically sorted out based on the `theme_subject` taxonomy.

Since these themes are used for both development and production, I'm not sure if I should actually fiddle with any of them to test, but it seems like adding a "Commerce" theme subject taxonomy and applying it to all relevant themes (along with the auto loading homepage feature) should automatically make that category appear in the the picker.

**Comment by blackjackkent** [comment]
The majority of the work for this issue was completed in #60415, which implemented the "recommended" theme and put the logic in place to sort a separate theme category to the top when the user is in the 'sell' intent. Currently it is using the "Business" category for this purpose since it's all still behind a feature flag anyway, but can be updated in future when the designers have put together the designs and they're ready to go.

**Comment by blackjackkent** [comment]
Superseded by #61921
