### ISSUE TITLE
Address / Business info steps aren't setting profile data on atomic sites

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60172]
Noticed we can't test the new [bussiness info step](https://github.com/Automattic/wp-calypso/pull/59837) against existing atomic sites as it only updates site options on non atomic sites.

I think we're waiting on a Jetpack release of https://github.com/Automattic/jetpack/pull/22248 for this to be resolved. cc @DustyReagan 

- [ ] Wait for Jetpack release to hit atomic.

**Comment by DustyReagan** [comment]
> I think we're waiting on a Jetpack release of Automattic/jetpack#22248 for this to be resolved. cc @DustyReagan

That sounds correct. I'll watch for the release today.

**Comment by DustyReagan** [comment]
So it looks like the data is saving on Atomic fine after the Jetpack update, but I'm seeing the "snag" error and a blank screen on wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard

<img src="https://user-images.githubusercontent.com/140841/150024750-8f44402f-004a-47c8-ad85-78fc448dbe1e.png" width="300" />

I wonder if it's because we're missing the `completed` marker, or maybe `product_types` needs to be an array? 🤔 Testing video below.

https://user-images.githubusercontent.com/140841/150025591-67a4c216-d683-4b52-b5d0-0d7f121d4a8b.mp4

**Comment by DustyReagan** [comment]
> maybe `product_types` needs to be an array?

Yeah, I think this is why we're seeing a blank page when returned to wc-admin. If I manually update `product_types` to be an array instead of a string, the page renders correctly. Still not sure about the "We hit a snag" error though.

```
{
	"woocommerce_onboarding_profile": {
		"store_email": "test@test3.com",
		"product_types": [
			"downloads"
		],
		"product_count": "11-100",
		"selling_venues": "brick-mortar",
		"completed": true
	}
}
```

![wc-admin](https://user-images.githubusercontent.com/140841/150030375-36ed3cdb-e40d-45c2-b06f-c52b3ad94221.png)

**Comment by DustyReagan** [comment]
Just another note. I didn't see the `completed` boolean in the profile array after installation. I added it manually and it seems to skip the wizard like anticipated.

**Comment by lsl** [comment]
> Still not sure about the "We hit a snag" error though.

Going by the video timestamp (28s end - 13s start = 15s you're hitting the [timeout](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/woocommerce-install/transfer/install-plugins.tsx#L18).)

The install only process should only take 1-2 seconds of polling, the install part of the process is near instant.

I'd guess the software endpoint is either not responding as applied or the trigger wasn't fired off right.

> Just another note. I didn't see the completed boolean in the profile array after installation. 

I'll try figure out why this is happening today.

**Comment by DustyReagan** [comment]
> I'd guess the software endpoint is either not responding as applied or the trigger wasn't fired off right.

For what it's worth, I was testing a reverted site. Maybe some old stale data was the issue? 🤔 Probably needs more testing. However, I think this particular issue of data transferring on Atomic could possibly be closed, and new issues opened.

**Comment by lsl** [comment]
>  I think this particular issue of data transferring on Atomic could possibly be closed, and new issues opened.

+1

**Comment by lsl** [comment]
> Still not sure about the "We hit a snag" error though.

@DustyReagan I couldn't repro in prod or dev, maybe something on your end?

**Comment by lsl** [comment]
Follow up for complete happening here https://github.com/Automattic/wp-calypso/pull/60231
