### ISSUE TITLE
Add intent prop to calypso_signup_previous_step_button_click

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#60216]
Add the  intent prop for the Design Picker(DP)  back button, e.g `calypso_signup_previous_step_button_click` such that the intent gets recorded when user clicks the back button on the DP screen.  We need to be able to know “user clicks back on the DP in the build flow, or in the write flow, or in any other flow”, otherwise we can’t do correct analysis.

See my analysis here on how I found this issue: https://docs.google.com/document/d/1kISyqspwN_hWBLBDsA6sk2ub2KjVZHWcck5SJnfDBcM/edit#

See that intent prop is missing:

![image](https://user-images.githubusercontent.com/5665959/150014907-22419de7-397a-48f7-b91b-e4ab27dd6730.png)

**Comment by p-jackson** [comment]
I don't see any harm in adding the `intent` prop to this event, so worth adding I think.

> We need to be able to know “user clicks back on the DP in the build flow, or in the write flow, or in any other flow”

I don't think adding this prop will make it specific enough. When you're in the full screen preview of the design picker and click back, you get a `calypso_signup_previous_step_button_click` event with `step=design-setup-site`.
<img width="1580" alt="Screenshot 2022-01-20 at 9 16 06 AM" src="https://user-images.githubusercontent.com/1500769/150207354-c5c73a12-c5b4-42ec-aa5d-456e9ff149e9.png">

That's because the full-screen preview is sort of a sub-step, the user is technically still in the `design-setup-site` step. This makes it indistinguishable from clicking the back button to go back to the intent screen.

**Comment by p-jackson** [comment]
Is it possible to add the same event twice in the same funnel? I'm thinking of a two-step funnel:

1. `calypso_signup_intent_select` where `intent=build`
2. `calypso_signup_intent_select` where `intent=write`

This two-step funnel would show which percentage of users changed their minds from "build" to "write".
Pro: only two steps, I think we can be more confident it's working correctly
Con: it can only measure going one direction, we'd need a second funnel for users who change from "write" to "build"

Even _more_ bulletproof idea: a back-end track event that records what the intent was when we actually the setup/headstart process. A user could change their mind multiple times but the above funnel idea would only capture their first change-of-mind. A back-end track event would allow us to compare their very first choice to their ultimate choice.

**Comment by autumnfjeld** [comment]
> Is it possible to add the same event twice in the same funnel? I'm thinking of a two-step funnel:

I do think this would work! And I think your suggestion is a better approach, because that is the core of what I wanted to check, did user switch intent (doesn't matter if they went forward/back three screens or one).  I will give it a try.   Thank you!

> A user could change their mind multiple times but the above funnel idea would only capture their first change-of-mind. A back-end track event would allow us to compare their very first choice to their ultimate choice.
Great idea, I had similar thoughts (pdgK6S-ox-p2#comment-719), if we decide this is really importatnt to track this would be the way to go.  

For now I'm just trying to get a sense check.

**Comment by autumnfjeld** [comment]
> I don't think adding this prop will make it specific enough. When you're in the full screen preview of the design picker and click back, you get a calypso_signup_previous_step_button_click event with step=design-setup-site.

Ah, hmhh. Good point!  I wonder if the DP preview should have a different step name. ` step=design-setup-site-preview`.  Are there any downsides to doing this?   (I don't think it is too big of a deal, I'm trying to think of any critical analytics that would hinge on this. But it would indeed throw off stats if someone was purely looking to see how often a user clicks back from within the DP, but again, this doesn't seem a critical analytic )

And in a funnel, I don't know if it would matter because a funnel looks at a series of actions:  action1 > action2 > action3 (even if someone did action2 10x really fast, the funnel would still expose the series of actions. (I think)

**Comment by p-jackson** [comment]
> Are there any downsides to doing this

- We're pushing the branching in the signup flow to the limits. From memory making it a sub-step simplified the branching (one less step to existing on a weird branch). But I could be overstating this issue.
- I think of the big preview as just another feature of the design picker component, not that it advances to a whole new screen. This means we could easily add this big preview to `/new` since it's not changing the flow (although it's not worth it given we're deprecating `/new`). Using the flow-level "back" button for this design picker feature does make it a bit confusing though.

Maybe the back button shouldn't be sending the `calypso_signup_previous_step_button_click` at all, since it's not really going back a step. It's more like `calypso_signup_previous_section_button_click` (these sub-steps are called "sections" in the signup framework).

**Comment by arthur791004** [comment]
I think adding something like `stepSectionName` to the event might be better to distinguish the design picker and its preview as we also have `stepSectionName` in another flow.

Oh but the `stepSectionName` of the preview is the title of theme 😅

**Comment by p-jackson** [comment]
> Oh but the `stepSectionName` of the preview is the title of theme 😅

Oh no! lol. I was going to say it seems like a safe thing to just add, it'd be recorded for the other "sections" that are used, like in the domain step. Having it vary for each theme won't work for us though 🥲

**Comment by autumnfjeld** [comment]
Let's just remove that tracking from the back button on the preview, since as you said it's a subsection and not a step in itself.    I'm not too fussed that we need to track it.  I don't think it is going to tell us anything dramatic and exciting about our users or the Hero Flow UX.

**Comment by p-jackson** [comment]
> Let's just remove that tracking from the back button on the preview

👍

Probably worth noting that this will also remove the same back button events from the domain step subsections. Which look like this:

https://user-images.githubusercontent.com/1500769/150628550-14014927-bfbc-44a8-948f-1a5521c3e6ea.mov

I don't think anyone's running analysis on these back steps right now though. Pretty sure we'd know about any project around this area.

**Comment by arthur791004** [comment]
I think it's okay. As you said, “it's not really going back a step.”, going back from the domain step subsections is not really going back a step either.

Or maybe we should have the rule to define semantic `stepSectionName` and replace the current one with `/design-picker/preview?theme=...`. Then, we can add `stepSectionName` to the prop of the event.

**Comment by p-jackson** [comment]
🤷 I kinda like the url the way it is right now

**Comment by arthur791004** [comment]
Close it as https://github.com/Automattic/wp-calypso/pull/60230 is shipped!
