### ISSUE TITLE
File Block: download option not downloading directly the file on simple sites

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#60232]
### Quick summary

When adding for example an image or a PDF file on the File block on a simple site, the download button is not downloading the file directly to the device. Instead, the file is opened/displayed on the browser, and the user needs to save it using the options from their computer.

### Steps to reproduce

1. On a Simple Site, create a post or a page. 
2. Add a File Block, and upload an image or PDF file. 
3. Visit the page/post, and click on the `Download` button.

### What you expected to happen

To have the file downloaded on the computer, like on Atomic sites.

### What actually happened

The file is opened in the browser, having the user download it manually.

### Context

This was reported on 4697853-zd-woothemes

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment]
Confirmed with txt/jpg/pdf files.

Atomic download the file directly, while Simple load the file within the browser.

**Comment by daledupreez** [comment]
I've investigated this further and the main cause of the issue is that we host uploaded files on a subdomain of `files.wordpress.com` instead of directly on the site. This means the `download` attribute of the `a` tag is not honoured by the browser, because the file is on a different origin. This restriction is called out in [this MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download).

Browsers will honour a `Content-Disposition: attachment` header if it is present, but it's not clear if we can safely request or inject that header.

As a further side note, this issue seems to apply for Simple sites with and without a custom domain as the primary domain, as the domain for files doesn't match for both cases.

**Comment by daledupreez** [comment]
I've started an internal discussion to see if we can come up with a way to request that the `Content-Disposition` header gets added for special cases like this one. pMz3w-fJo-p2

**Comment by daledupreez** [comment]
Earlier today, we added a back end change to make it possible for the `Content-Disposition` header to be requested by the client. That was deployed in D86776-code.

I am now working on ensuring that the links are added correctly for the download button.

**Comment by daledupreez** [comment]
I've just deployed D87065-code to production, and we should be correctly enforcing downloads for WordPress.com Simple sites.
