### ISSUE TITLE
Bugs in domains-only signup flow

### ISSUE THREAD

**Issue by emilyaudela** [Automattic/wp-calypso#60277]
### Quick summary

From the [domains landing page](https://wordpress.com/domains/), users can search for a domain and start the signup flow. The design and flow is inconsistent with the regular signup flow. 

### Steps to reproduce

1. Start at https://wordpress.com/domains/
2. Enter a domain name in the domain name field and click Search
3. Select a domain from the proposed domain options
4. Click the first option in the list: New Site.

### What you expected to happen

I expected to see the design picker that is used in the normal signup flow from wordpress.com/start. At the very least, I would expect the title to be centered and the button at the end of the text to be aligned with the text. 

### What actually happened

I was presented with this theme selection screen. The title is not centered and there is a strange floating Jetpack button. The themes are not current themes.

<img width="500" alt="Screen Shot 2022-01-19 at 6 37 22 PM" src="https://user-images.githubusercontent.com/36699353/150246636-971effea-1dd7-4ecb-aec3-26649a859aa8.png">

On the next page, the plans page, there is a color contrast issue in the text making it hard to read. 

![Markup on 2022-01-19 at 18:40:58](https://user-images.githubusercontent.com/36699353/150247101-607aee43-b4d0-464a-8439-2094a71ac89b.png)

### Browser, operating system and other notes

Chrome and Firefox

**Comment by Greatdane** [comment]
@emilyaudela I cannot reproduce or see the screens you get when starting from https://wordpress.com/domains/

This is what I see;

<img width="1251" alt="Markup 2022-02-03 at 14 49 45" src="https://user-images.githubusercontent.com/5075840/152288619-586efe19-b479-4688-aac1-a973ad80a2eb.png">

<img width="1171" alt="Markup 2022-02-03 at 14 50 08" src="https://user-images.githubusercontent.com/5075840/152288647-6e445295-5491-48ff-a36c-3126c2ebde88.png">

(I see 'Choose a Theme' is not centered due to the Jetpack option)

Are you still able to reproduce the issue?
