### ISSUE TITLE
Calypso: by default, Child pages aren't nested under the correct Parent page

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#60280]
### Quick summary

User report: 4699873-zd-woothemes

When there are a lot of child pages, they re-arrange to the correct position, only after scrolling down the page. 

https://user-images.githubusercontent.com/21261509/150281025-1a1ce23c-e7b8-4640-b86a-697259837a44.mov

### Steps to reproduce

1. Open a simple/AT site.
2. Go to **Pages**.
3. Create a lot of pages (~20+) with a majority of them being **child pages** (Select a **Parent Page** via **Page Attributes** in **Page settings** for the individual pages). 
4. Go back to the **Pages** list in **Calypso**.
5. The pages re-arrange to the correct position, after scrolling down the page.

### What you expected to happen

I expected all child pages to be in the correct position on page load. 

### What actually happened

The child pages show in the correct position only after scrolling down the page. The page jumps back to the top, and I need to scroll down the page again. 

### Context

The user is experiencing this issue here: 4699873-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is zooming out to 90-80% in your browser, or view in Classic View

**Comment by mxhassani** [comment]
### Another workaround:
Using the classic view.
![image](https://user-images.githubusercontent.com/81776920/150512279-15acccf6-c3f4-477e-aa2f-b6923738cf66.png)

Support guide: https://wordpress.com/support/dashboard/

**Comment by formosattic** [comment]
I wasn't able to reproduce on my test site, but can still see the issue on the user's site, so whoever will take a closer a look, I'd suggest checking the user's site in this ticket 4699873-zd-woothemes

As I understand, by "correct position", it's meant that the child pages aren't nested under the correct parent page. This was clearer when I checked on the user's site. 

The visual styling of the nesting/indent also looks different.

| Incorrect Parent  | Correct Parent |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/154043469-3ce14827-9b8b-45c9-bad9-9ade46352f21.png) | ![image2](https://user-images.githubusercontent.com/15944096/154043414-b6086100-796b-4dad-9ea7-fe19caac7432.png)  |

**Comment by wojtekn** [comment]
### Reproducibility 

I reviewed this issue and found a straightforward way to reproduce it:
1. Create the first page
2. Add >20 pages and assign the first page as a parent for all of them
3. Load Pages in a browser window that is not big enough to trigger loading more than 20 pages

It should load 20 pages in “chronological” mode. Then scroll to the bottom to trigger loading more records. Page list gets rendered in “hierarchical” mode now.

The same issue was also reported under https://github.com/Automattic/wp-calypso/issues/51610, https://github.com/Automattic/wp-calypso/issues/40333, and https://github.com/Automattic/wp-calypso/pull/55711 (p9F6qB-7iD-p2).

###  Background

The “hierarchical” mode is used to render pages only if specific conditions are met: the number of pages is not greater than 100, there is no query search, and all pages are loaded using the infinite scroll. When we load the page initially, it loads 20 records, and five are remaining. All records are not loaded yet, so the “chronological” mode is used.

When the last page of the infinite scroll is reached, Calypso has all pages in place. It can use child/parent relations from all records to calculate hierarchy: the indent level and sort order. It calculates them and displays pages in “hierarchical” mode.

Initially, when the “hierarchical” mode was implemented, there was no infinite scroll. Calypso was loading pages in the “hierarchical” mode if the number of pages was lower than 100. It worked as expected (p8F9tW-18-p2). The current behavior was introduced after introducing the infinite scroll.

###  Possible Solutions

The most comprehensive fix would be moving hierarchy/indent calculation from Node code to the API endpoint. The endpoint would need to be modified to return hierarchical data - pages would be already sorted in the desired order and would have indent level filled accordingly. This approach was summarized by @yansern under https://github.com/Automattic/wp-calypso/issues/51610#issuecomment-916046218. The fix requires significant effort.

###  Request for feedback

I would appreciate feedback from @Automattic/build and @Automattic/cylon.

**Comment by danielbachhuber** [comment]
> ### Possible Solutions

Another option to consider: display a takeover loading indicator in “hierarchical” mode until all of the data is loaded.

While it isn't desirable to introduce a more significant delay in the user experience, a loading indicator would solve the problem of the user temporarily seeing an incorrect state. This might be the right balance between effort and return.

**Comment by wojtekn** [comment]
@danielbachhuber, thanks for the feedback. I am concerned about using the loading indicator for the "infinite scroll" feature to help with the issue we are having. The loading indicator wouldn't be displayed until the user scrolls down to the bottom of the page. And then, when the user scrolled down, it would immediately load new records.

Another point is that Calypso guidelines recommend [avoiding using loading indicators](https://github.com/Automattic/wp-calypso/blob/trunk/docs/reactivity.md).

Adding @mattsherman, who was announcing the hierarchical view feature launch (p8F9tW-18-p2).

**Comment by p-jackson** [comment]
I'm not sure this helps us, but do we know how useful infinite scroll actually is? If a site has many 100s of posts then is it useful to be able to scroll through all of them in one big list? It sounds unwieldy and the user is likely to use the search feature to find posts anyway. I assume the view used to have pagination.
Anyway, just throwing the cat amongst the pigeons thinking about reverting the infinite scroll behaviour :)

**Comment by p-jackson** [comment]
It's also not necessarily out of the question that we spend the time to implement chronological-hierarchical fetching correctly. Previous efforts at fixing this have been about trying to squish bugs, whereas you could say the Build Team has the mandate to push post navigation forward. Especially at this phase of our roadmap 🤷‍♂️

**Comment by creativecoder** [comment]
I don't remember how I became subscribed to this issue, but since I am, here is an unsolicited opinion 😄

Infinite scroll in the Calypso post/pages list has always seemed to cause more problems than it's solved. I think it's hard to do in a browser/user friendly and robust way-- for example, do you end up in the same place on the list after navigating away and using the back/forward buttons in the browser? Can the list handle hundreds or thousands of elements and without a constant increase to browser memory/resources? These things are hard to get right.

My vote would be to put time and energy into enhancing wp-admin with features from Calypso, rather than redoing the page/posts list in Calypso. That's more inclusive of Atomic sites, which may be using plugins to add functionality in wp-admin that will always be missing from Calypso. And wp-admin already has number of features that Calypso is missing, like quick editing mode.

**Comment by wojtekn** [comment]
> My vote would be to put time and energy into enhancing wp-admin with features from Calypso, rather than redoing the page/posts list in Calypso. That's more inclusive of Atomic sites, which may be using plugins to add functionality in wp-admin that will always be missing from Calypso. And wp-admin already has number of features that Calypso is missing, like quick editing mode.

@creativecoder, thanks for the feedback. This seems to be a more strategic change. If there is a desire to go that route, I think it makes sense to discuss it separately. Thus here, I would try to fix the current UX issue using a solution that doesn’t require us to invest too much time and energy.

Summing up the findings and the feedback:
* building the tree on the client-side using the partial results received from the server won’t work
* infinite scroll seems to cause problems
* replacing infinite scroll with pagination won’t fix the issue users are having
* adding a loading indicator might help a little but is not recommended by Calypso guidelines
* moving generating the hierarchy/indent to the server-side may require significant effort. Still, the paginated tree doesn't seem as great UX.

Having all those, I tried to check if we could display pages in the hierarchical mode for most of the users on the initial load. I’ve checked the data, and I found that less than 0,1% of sites have more than 100 pages. I came up with the change that increases the number of pages loaded on a single site to 100, which is the value that was chosen initially as a limit for the hierarchical view and which is a maximum supported value by the API endpoint:

https://github.com/Automattic/wp-calypso/pull/64286

If we do it that way, 99,9% of users will always see pages in the hierarchical mode. 

If we think that changing the limit from 20 to 100 is too aggressive, we could try with a lower value, e.g., 50. The fundamental change is not choosing a particular number but aligning the number of records per page with the hierarchical mode top limit.

I will appreciate giving it a test and review.

**Comment by mattsherman** [comment]
> Infinite scroll in the Calypso post/pages list has always seemed to cause more problems than it's solved. I think it's hard to do in a browser/user friendly and robust way-- for example, do you end up in the same place on the list after navigating away and using the back/forward buttons in the browser? Can the list handle hundreds or thousands of elements and without a constant increase to browser memory/resources? These things are hard to get right.

Infinite scroll nearly always is implemented poorly. As such, it nearly always ends up being a frustrating experience for users.

> My vote would be to put time and energy into enhancing wp-admin with features from Calypso, rather than redoing the page/posts list in Calypso. That's more inclusive of Atomic sites, which may be using plugins to add functionality in wp-admin that will always be missing from Calypso. And wp-admin already has number of features that Calypso is missing, like quick editing mode.

💯 

That said, I do agree that loading 100 of pages on the initial load, to allow for hierarchical mode without confusing reordering as scrolling/pagination occurs, sounds like a reasonable fix.

**Comment by p-jackson** [comment]
> If we think that changing the limit from 20 to 100 is too aggressive, we could try with a lower value, e.g., 50. The fundamental change is not choosing a particular number but aligning the number of records per page with the hierarchical mode top limit.

I think 100 might be too aggressive. I'm sure the servers could deal with the extra load, what I'm more worried about is fetches on slower internet connections. When I simulate a 3G connection in Chrome for instance, the `/posts` request for 20 items takes ~10s. I worry about what that will mean when we fetch 5x more posts! Perhaps I misunderstand how 3G works, it could be that most of that time is in latency and so requesting 100 posts isn't going to take ~50s. But I think it'd be worth being conservative and increasing to only 50ish.

**Comment by wojtekn** [comment]
@p-jackson I reduced it, made some tests, and now for 50 items it takes less than one second to get `/sites/$site/posts?number=50&type=page`:

* 20 items: 485ms
* 50 items: 934ms

I played with throttling as well:

* no throttling: 610ms
* fast 3g: 755ms
* slow 3g: 2.5s

**Comment by danielbachhuber** [comment]
What about a combo approach?
1. Increase the number of requested items to 50.
2. Display a loading indicator.

One downside of only increasing the number of requested items is that we haven't truly "fixed" the problem. We've only solved it for another subset of users. By including a loading indicator too, we've solved the user experience gap for everyone.

I don't strongly feel this is a good idea, though.

I haven't tested but I think the most technically correct solution is:
1. Add support for `orderby=menu,title` in the WP REST API: https://core.trac.wordpress.org/ticket/39037
2. Update Calypso to use those query params.

Landing a core patch would obviously be a substantial effort, however.

**Comment by wojtekn** [comment]
> One downside of only increasing the number of requested items is that we haven't truly "fixed" the problem. We've only solved it for another subset of users.

The fix is not only about increasing items per page. I think the more critical part of the fix is aligning the number of items per page with a top limit of items that make a list eligible for a hierarchical view. That way, we are fixing the confusing behavior from the initial report:

> When there are a lot of child pages, they re-arrange to the correct position only after scrolling down the page.

To give more background on the confusing behavior - if those are not aligned, the user sees the chronological list until infinite scroll loads all items, and then the view quickly changes to hierarchical when all items are loaded. The hierarchical view is sorted differently than the chronological, which is responsible for a part of that confusion.

With the fix, there is no such behavior - if the user has less than 50 pages, it always loads a hierarchical view. It always loads a chronological view if it has more than 50 pages. Choosing between 50, 100, or any other value between 20 and 100 depends on the loading speed we can afford there.

> Add support for orderby=menu,title in the WP REST API: https://core.trac.wordpress.org/ticket/39037

By default, the chronological view sorts posts by date, descending. Then the hierarchical view sorts by menu, but it puts pages into the parent/child hierarchy. How could we utilize sort by `menu,title` there? Would this change replace the date sort order for a chronological view?

**Comment by danielbachhuber** [comment]
> Then the hierarchical view sorts by menu, but it puts pages into the parent/child hierarchy. How could we utilize sort by `menu,title` there? Would this change replace the date sort order for a chronological view?

Correct — it would mean the REST API request would map 1-to-1 to core's query for a hierarchical Posts List: https://github.com/WordPress/wordpress-develop/blob/96d6eae6013121394ed0a166459f5376567ffd36/src/wp-admin/includes/class-wp-posts-list-table.php#L170

**Comment by wojtekn** [comment]
@danielbachhuber, I'm trying to understand it better - in that approach, would you remove the complete recalculation of hierarchy on the client-side (https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/pages/helpers.js) and remove the chronological sort, so the page list in Calypso would mimic the one from /wp-admin/ ("Classic view")?

**Comment by danielbachhuber** [comment]
> would you remove the complete recalculation of hierarchy on the client-side (https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/pages/helpers.js)

@wojtekn I think some of that code would need to remain in place. The client would _receive_ the pages in the correct order, but would still need to build the hierarchical display.

> remove the chronological sort, so the page list in Calypso would mimic the one from /wp-admin/ ("Classic view")?

Oh! I didn't realize Calypso's behavior departed from core.

If we changed the chronological sort to hierarchical, I suppose we'd need to:

1. Track down the original decision for chronological (and whether it was intentional or not).
2. Review the proposed change with a broader group of people.

---

Sorry to have derailed your progress on this issue, @wojtekn. It seems to be a rabbit hole without a clear solution 😕

**Comment by wojtekn** [comment]
@danielbachhuber, I feel this has become too complex for the initial issue. What if we take a step back and fix an original problem for now? A combination of two things causes the main issue:

* displaying 20 items per page,
* displaying hierarchical view only if all eligible items (up to 100) are loaded.

This behavior causes a chain of events in which the user first sees the chronological view. Then when all items are loaded, it switches to the hierarchical view.

I think the more critical part of the fix is aligning the number of items per page with a top limit of items that make a list eligible for a hierarchical view. While doing this, we also reduce the limit from 100 to 50. That way, we are fixing the confusing behavior from the initial report. The user will always see the same view:

- the user who has less than 50 pages will always see a hierarchical view
- the user who has more than 50 pages will always see a chronological view

I want to avoid reimplementing the whole Calypso pages list here, as it looks like it deserves to be a project.

@Automattic/build

**Comment by danielbachhuber** [comment]
@wojtekn I'm amenable to your proposed solution. I agree a "proper fix" would require a full re-implementation, which is a path we don't want to go down right now.

**Comment by wojtekn** [comment]
Thank you! I'm closing it as it is fixed by https://github.com/Automattic/wp-calypso/pull/64286 now.
