### ISSUE TITLE
Domain Cancellation Survey

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#60359]
### What

Add to the domain cancellation survey the reason _"won't be using the domain anymore"_ or _"don't need the domain"_.

### Why

Although there's an option for _"something not listed here"_, we're losing the opportunity to get stats for one of what seems to be the most common reason to cancel a domain.

### How

Here's how the survey looks like now:

![DomainCancellationSurvey](https://user-images.githubusercontent.com/16104522/150638348-36ce58bf-e262-4d5f-ac5c-c3b57492f55a.jpg)

**Comment by delputnam** [comment]
We're not capturing the selected reason from this form at all. The purpose of this form is to guide the user to the correct action if they don't understand that there might be a better option than canceling to accomplish their goal since we had a number of users mistakenly canceling their domains when they really just wanted to transfer  it or they didn't understand the implications of the canceling the domain.

I'll add a task for Nomado to think about how to use this data if we did capture it and to consider this for a future sprint.
