### ISSUE TITLE
Drafts: run a usertest to determine which 'add post' buttons get clicked

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6035]
As of #4936 we will have a drafts column in the posts view. It introduces a third 'add' button in a unique style. This, along with the masterbar compose button and the sidebar's add button makes for three ways to add a new post/draft. I'm curious if three are necessary and if one is superior to the rest. 

Let's see if there's a prevailing trend here by testing on some real users. It'd also be interesting to see if we can get good analytic data on which is the most popular option. 

cc @mtias

**Comment by mtias** [comment]
Some reference on why we switched away from `+` buttons in the sidebar — at the time of the very first launches of Calypso sections, we only had sites, so the + was cryptic since there was nothing else on the page (we didn't have posts nor pages) using the same pattern. I think we can give that a go now again since we have many more elements that support "adding" an item.

**Comment by folletto** [comment]
I confirm. In the tests we did "Add" was way clearer than "+". Given we provide multiple access ways tho, we might be totally fine in having that specific instance to be less clear, and move to a `+` icon. :)

**Comment by alisterscott** [comment]
Closing this as we no longer display drafts as a sidebar item in /posts
