### ISSUE TITLE
Atomic: Bad Experience on Non-wordpress.com Domain Change

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#60364]
### What

When a site is ATed, the domain change from a non-wordpress.com address is quite disruptive.

### Why

When the site has a .wordpress.com domain, that part only changes to _".wpcomstaging.com"_, but if the site had one of the other extensions we offer, such as ".food.blog" for example, the address is changed to "dotfooddotblog.wpcomstaging.com", which is very different from the original.

I'm not sure about a better way to change this to, but it feels to me that at least changing to "foodblog.wpcomstaging.com" - without the "dots" - would be a bit less disruptive. Or just use the actual site name part in the URL, if it was "amazingsite.food.blog", it would be "amazingsite.wpcomstaging.com" - it might not be possible though because it might exist already, but this seems to be the ideal situation, maybe we could give options to the user.

### How

User got upset with this on 4710961-zd-woothemes

**Comment by arinoch** [comment]
This is an address generation issue, and affects atomic and simple sites. What happens is if a user creates a site and goes straight to a custom domain, we try to base the WordPress.com address off that domain--assuming, for whatever reason, that that address will never be seen.

If a user on the Personal plan creates a site and goes directly to also registering mygruvysite.com, we give them mygruvysitecom.wordpress.com by default. We could possibly shorten that to mygruvysite.wordpress.com, but as pointed out in the initial request, this may generate its own problems if mygruvysite.wordpress.com is already taken--either by the same user or another.

**Comment by kerrynicl** [comment]
Perhaps even a warning to atleast notify what the user's domain might be changing to would be ideal here

**Comment by delputnam** [comment]
I understand the frustration here and I agree that switching from the nice clean free URL to the wpcomstaging.com URL is frustrating. Finding a nice clean _and unique_ subdomain quickly gets complicated. For example, if the user selected `amazing.food.blog` as their free URL, we are much more likely to have an unused subdomain like `amazingdotfooddotblog` (since the FQDN is guaranteed to be globally unique) than `amazingfoodblog`. In which case, we'd end up having to append random numbers to the string to make it unique. So the user might end up with something like `amazingfoodblog7456283` which I can imagine would be equally frustrating.

It turns out that with a very crowded wordpress.com subdomain space it's very challenging to quickly find a subdomain that is both unique and easy to read.  We did quite a bit of work on the wpcom subdomain generation function a few years ago since it was becoming very slow as the space becomes increasingly crowded.

We could probably show a message to users who don't already have a custom domain and remind them that they can chose a free domain name for their site. Since I only count a total of 13 sites that have a free .blog subdomain and no custom domain, I'll add this to Nomado's backlog and close this issue.
