### ISSUE TITLE
Signup: Theme selection in signup should not rely on dependency props.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#6038]
@nylen has brought up that [props shouldn't be used to set the initial state](https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html) of the `theme-selection` [step in signup](https://github.com/Automattic/wp-calypso/blob/master/client/signup/steps/theme-selection/index.jsx#L32).

Is there a better way to handle getting themes into this step:
* taking into account the selections of the `survey` and `design-type` steps, and
* not relying on signup flow dependencies, as that would require `survey` and `design-type` steps for every flow that uses the `theme-selection` step?

**Comment by kwight** [comment]
cc/ @sirbrillig

**Comment by bisko** [comment]
We are currently working on something similar in #5673 which would help with something like that. There are some things that we have to work out in the back end of things, but in the end it could be applied to the case you described above.

**Comment by sirbrillig** [comment]
After reading the Slack thread, I think that there are several things going on here.

The themes step uses the props to determine what themes to display. That's a pretty straightforward 1-1 props-to-themes computation, which could happen directly during render. However, the lib that does that computation returns its data shuffled, which means that every call to that function, even with the same parameters, will return different data.

React components are usually based on the idea that for the same props (input), the rendered markup should be the same (output). Because of the shuffling, we're breaking that experience.

In order to maintain the order, I suggested that we add a layer of caching inside the component. When it is first rendered, and whenever the props change in a way that would change the list of themes, we use the props to compute the list of themes and save it in the state.

There may be a better method to avoid the non-idempotent nature of computing the list of themes. One possibility would be to avoid shuffling the result of the computation. Maybe a more React-style way would be to use `shouldComponentRender` to prevent re-computing the themes list unless the props change in a way that would change the computation. Essentially React would provide the caching in that case.

The other thing that's going on is that the props that are used in the computation come from the previous steps in the signup flow, which means that they are not direct children of `props`, but rather `props.signupDependencies`. That extra level of object creates some confusion, because it makes it hard to show the component's requirements via `propTypes`. Changing how the signup flow passes dependencies might make that easier. We could also use a wrapper component that translates the `signupDependencies` into actual `props` for our themes list component.

I'll make some PRs to try out both of those ideas and see how they perform.
