### ISSUE TITLE
Seller Experience: Show a celebratory modal on product publish.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60413]
Let's show a celebratory modal on product publish from the editor.

![image](https://user-images.githubusercontent.com/13437011/155621428-c7e945f5-34ba-4eb1-87e8-23605f217e09.png)

After hitting save for the first time on an editor where the user has the "sell" intent and a Payments block in the editor body, the user should be greeted with a modal. The modal guides them towards previewing their product via a “View your product” button. They can close the modal and return to the editor via the “Return to editor” button; clicking outside the modal also closes it and returns to the editor.

See: paYKcK-1cv-p2 and paYKcK-1k7-p2

**Comment by blackjackkent** [comment]
I did a good amount of work on this the last two days and will be continuing it into next sprint. After some discussion with Kirk, we decided this will make use of a new `useSiteIntent` React hook in the editing toolkit to allow us to determine whether the user created their site in the 'sell' flow or not. We already have existing logic to display a "congrats on your first post" modal, so per discussion with Saxon (p1643229757064900-slack-C0Q664T29) we will be retaining that design and updating it for the "Sell" context:

![image](https://user-images.githubusercontent.com/13437011/151398482-b53cce2e-6b58-485c-8e7b-9b799a8618fd.png)

I got all the logic for this working, but at the end of the day yesterday abruptly started running into issues getting the modal to display consistently at all in either flow. So I need to figure out what's going on there and get this refined and ready to go.

**Comment by kwight** [comment]
Also see: https://github.com/Automattic/wp-calypso/pull/60772#issuecomment-1028341100

**Comment by blackjackkent** [comment]
This has turned out to be a bit more of a complex issue (and more of a learning experience) than I expected. With the decision made to navigate the Sell flow user to the site editor, I'm working on how to implement a conditional modal when that editor specifically has been submitted (for the first time, with a user who arrived via the sell intent and has a product block on the page, as noted in the comment Kirk linked above).

Made good progress on this today with some help from the folks in the #dotcom-fse channel. I've currently got a simple POC set up loading a new plugin in the Editing Toolkit which conditionally initializes a React component (with access to the `core/data` store and its info) on the site editor only. Monday's tasks will be getting it to render the modal, and then getting it to show only when the entity record is submitting (I was pointed towards [this selector](https://github.com/WordPress/gutenberg/blob/339ffc2711846910dd9f06e61bb1f7f2931608bd/packages/core-data/src/selectors.js#L550) as a possible starting point). After that, I should be able to add in further conditions regarding the user's account and the content being submitted.

( @kwight and/or @sixhours if you have time on Monday and would be up for a pair programming/rubber-ducking session I would certainly appreciate bouncing some ideas around. 😄 )

**Comment by kwight** [comment]
Could you give us an update here @blackjackkent ?
