### ISSUE TITLE
Woo Installer: Use siteSlug instead of site

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60568]
It looks like other onboarding flows are using a `siteSlug` parameter to pass on the site context from step to step, including the new seller experience onboarding flow that is being worked on by @Automattic/serenity. 

@lsl said [switching should be easy enough](https://github.com/Automattic/wp-calypso/pull/60383#discussion_r793194786), so let's try doing that in the interest of more conformity.

**Comment by lsl** [comment]
This switch involves reversing parts of https://github.com/Automattic/wp-calypso/pull/58561 to move the woo installer back to `siteSlug` from `site`. Since then there are likely many more references to `site` so we will need to find those too.

Around the same time this took place there was a fix from @roo2 to make it so the siteSlug is passed along to every step in the URL instead of using the one out of context https://github.com/Automattic/wp-calypso/pull/58498 - we should get this for free and fixes one of the original problems we had with using `siteSlug` (https://github.com/Automattic/wp-calypso/pull/60383 should have fixed the other)

Potential problem: We use getSelectedSiteId instead of the siteSlug that comes through props, this was to create a consistent approach and single source of truth. I'm pretty confident this should remain the same but it's potentially something to check still works as expected along each step in the chain (especially around anything dealing with [flow resume](https://github.com/Automattic/wp-calypso/blob/98691b2a629096284030a4c2888eefad95a8755e/client/signup/utils.js#L206) e.g. checkout and return to transfer.)

**Comment by Rolilink** [comment]
PR here #60866, it seems introducing back `siteSlug` triggers back the #60383 issue. Actually it seems to only happen on the first step the siteId is not being updated when entering the flow and is returning the id of the previous slug 👀 .

**Comment by lsl** [comment]
> let's try doing that in the interest of more conformity.

@obenland / @kwight heads up - [We might](https://github.com/Automattic/wp-calypso/pull/60866#issuecomment-1032222359) need to let go of ^this plan, siteSlug or site will need to be sent in regardless so I don't know if it matters too much whether it's site or siteSlug.

> Actually it seems to only happen on the first step the siteId is not being updated when entering the flow and is returning the id of the previous slug

See link above, I suspect that's probably related?

Regardless of this situation there is a bug we need to fix, probably by passing `site` all the way through so browser back buttons work properly from the checkout. (https://github.com/Automattic/wp-calypso/issues/60907)

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/pull/60866
