### ISSUE TITLE
Woo Installer: Make back button work landing page agnostic

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60569]
The seller experience onboarding flow will likely link into the woop flow to get customers set up with their store.

Currently the back link in the address step is hard-coded to point to the `woocommerce-install` landing page, so customers coming in from the seller experience flow won't be able to step back into that.

Let's update that backUrl parameter to point to wherever customers arrived from.

**Comment by allilevine** [comment]
History API, pass params from URL.

**Comment by lsl** [comment]
Going to need something we ingest at the start of the flow - need to be able to access it in other places like the contact support url 

e.g. note what I've done [here](https://github.com/Automattic/wp-calypso/pull/60798/files#diff-27479408af4e300120c9425fc05d5585a74c602ff3c1f0992681591f92624700R27) will have a similar issue. 

We might want to set up three different urls, start url, error url (otherwise we use start url), success url (if not wc-admin).

**Comment by obenland** [comment]
Discussed in State of the Board (p1643922774499119-slack-C029UPVMGTW)

Instead of three different URLs, maybe try history api and see how it works out? Or maybe store the URL the flow was entered from and carry that along? It would be good to keep the API for the first step as simple as possible

**Comment by allilevine** [comment]
Closed via https://github.com/Automattic/wp-calypso/pull/60892 cc @kwight
