### ISSUE TITLE
Calypso / Themes: Cannot navigate away from theme page, My Sites button broken on theme pages

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#60577]
### Quick summary

It seems users can get stuck in navigation loop when directly visiting theme pages.

https://user-images.githubusercontent.com/4887830/151420827-0393f818-883d-4ffb-a19f-3f4e8251c7b7.mp4

### Steps to reproduce

1. In a new tab visit a theme page directly. E.g. https://wordpress.com/theme/stewart/
2. Select the site you're working on (Why does it do this? It would be nice to just navigate directly to the theme page.)
3. End up on the theme page for a specific site (https://wordpress.com/theme/stewart/DOMAIN)
4. Attempt to click My Sites (Nothing happens)
5. Click Back and be prompted to select a site again. a 

### What you expected to happen

Be able to return to My Sites > My Home or just WordPress.com.

### What actually happened

Cannot easily navigate away from the theme page.

### Context

Found while inspecting the newly launched Stewart theme.

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Tested on Chrome, macOS

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Open a new tab and go to WordPress.com.

Or, click the Reader or /me buttons and then My Sites.

**Comment by Robertght** [comment]
Thank you for reporting this @JoshuaGoode ! I have asked [here](p1643277764247600-slack-C02DQP0FP) as well but I got no thoughts yet.

**Comment by kimerlin81** [comment]
@JoshuaGoode - Thanks for reporting this issue. Being prompted to choose a theme when multiple sites are listed on an account appears to be expected behavior. When only one site is listed in My Sites, the user is sent directly to the theme page. I believe this prompt helps to prevent users from activating a theme on the wrong site.

As for the My Sites link being unresponsive, [this issue](https://github.com/Automattic/wp-calypso/issues/49847) has been triaged to address that.

**Comment by kimerlin81** [comment]
Reopening per this slack [thread](p1645096030633169/1643277764.247600-slack-C02DQP0FP)

**Comment by mmtr** [comment]
I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/49847, so closing this one out and leaving the other one open since it was reported before.
