### ISSUE TITLE
FSE: Contact Forms Added To Templates Via the Site Editor Don't Show Submission Responses

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#60774]
### Quick summary

Jetpack contact forms added directly to templates in the site editor do not show the response when submitted.

The contact form submissions do go through, but the confirmation does not display.

### Steps to reproduce

1. Activate a FSE theme.
2. Open the Site Editor.
3. Add a Contact Form to a Template.
4. View the post or page on the live site, and submit a form response.

### What you expected to happen

For the selected confirmation (text message, list of responses, etc) to display.

### What actually happened

The page reloads, scrolls to the bottom of the form, and appends the param to the end of the URL:
`/?contact-form-hash=f8039090395f711d58a1cfe1abd61b6951a509f3&contact-form-id=486&contact-form-sent=489&_wpnonce=af2e0fb74a#contact-form-486`

After the reload the fields are empty and the submission has gone through, but there is no visual confirmation. The response I selected in the editor (to show a message) does not display.

GIF:
![CleanShot 2022-02-02 at 10 11 04](https://user-images.githubusercontent.com/42279181/152203093-58c24989-7aa3-45f6-85aa-861a33ad6137.gif)

### Context

We've encountered this issue working on a Team51 partner site, and I've replicated on my test site here:

https://kbb-premium.blog/2022/02/02/form-test/

- Forms in the post (or page) content work without issue. 
- Forms added to the template (here it's the single post template and the footer template, as indicated in the header over each one) do not work as expected.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by ivan-ottinger** [comment]
I was able to reproduce the issue on a local Jetpack install.

---

**Initial investigation:**

It looks like the issue is coming from the [`if` condition](https://github.com/Automattic/jetpack/blob/a511be40d3468e2a3412b0c5a09a84b2bb51cd4d/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L2153-L2158) in `projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php` (in the Jetpack repo):

```php
if ( isset( $_GET['contact-form-id'] )
			&& (int) $_GET['contact-form-id'] === (int) self::$last->get_attribute( 'id' )
			&& isset( $_GET['contact-form-sent'], $_GET['contact-form-hash'] )
			&& is_string( $_GET['contact-form-hash'] )
			&& hash_equals( $form->hash, $_GET['contact-form-hash'] ) )
```

When the Contact Form block is located outside of the post/page content, the condition evaluates as `false` and therefore no message is outputted to the page (as the [code responsible for the confirmation message](https://github.com/Automattic/jetpack/blob/a511be40d3468e2a3412b0c5a09a84b2bb51cd4d/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L2163-L2182) is skipped and the `else` portion is executed instead).

**Update**: It appears that whole condition fails because of `$form->hash` and  `$_GET['contact-form-hash']` are not equal:

```php
hash_equals( $form->hash, $_GET['contact-form-hash'] )
```

**Update 2:** The correct hash is the one stored in `$form->hash`. The value stored in `$_GET['contact-form-hash']` should be the same, but isn't for some reason.

---

For completeness, the Contact Form block code lives in `projects/plugins/jetpack/extensions/blocks/contact-form/index.js`.

Our team will look into the issue further.

**Comment by ivan-ottinger** [comment]
Another observation (may or may not be related): When there's a Contact Form block in the FSE template only (if we don't add it to the post/page content as well), the related CSS stylesheet is not enqueued:

```html
<link rel="stylesheet" id="grunion.css-css" href="http://localhost/wp-content/plugins/jetpack/modules/contact-form/css/grunion.css?ver=10.9-a.0" media="all">
```
and as a result, the form is missing its formatting:
![Markup on 2022-04-04 at 17:24:09](https://user-images.githubusercontent.com/25105483/161577577-7f01bc1c-643f-4bac-be7d-a5ed8288925f.png)

**Update**: The styling issue is present only when the Form block is in the header template.

**Comment by danielk-am** [comment]
A user was not able to get the Form's on submissions to work when the Form block is added in the Site Editor - 5215601-zen.

I have tested and it seems that the "on submission" is triggered only when the Form block is added in the Post Content block in the Site Editor.

**Comment by cuemarie** [comment]
Ran into this issue here as well: 35693941-hc

Moved the content back onto the page (as they wanted it only on their homepage anyway) to resolve. 

*No need to update the user if this ever ends up with bulk replies.*

**Comment by ckmccoy2** [comment]
Issue occurred again on 35784164-hc

Advising user to place form on the page itself.

**Comment by danielbachhuber** [comment]
Some additional debugging at https://github.com/Automattic/wp-calypso/issues/62431#issuecomment-1154111872

Pull request started with https://github.com/Automattic/jetpack/pull/24727

**Comment by helenaartmann** [comment]
Got a user reporting the form does not confirm it was sent when added to their widgets: #5306610 - zen.

**Comment by sejas** [comment]
Fixed on https://github.com/Automattic/jetpack/pull/24727 and D82492-code
