### ISSUE TITLE
[Bug] TT2 themes are not shuffling properly in the Gutenboarding (/new) Design Picker

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#60840]
## Description
In the Gutenboarding Design Picker, the designs are meant to shuffle so that they appear in a random order on page load.  There seems to be a bug such that the Twenty Twenty 2 (TT2) themes are not shuffling properly--instead they always show in the top of the grid. 

Even though the /new flow will be replaced by /start in the coming weeks/months, it is important that we have TT2 themes properly shuffling so that FSE stats are comparable to pre-FSE scenarios (e.g. shuffling works properly before & after FSE launch).

![image](https://user-images.githubusercontent.com/5665959/152479910-c48d4b0d-4c49-4fbe-804e-699a9e26fbcc.png)

## Reproduce
* go to https://wordpress.com/new/design
* see all the TT2 themes at the top

## Prior work in this area
Design picker: re-write and re-enable randomized designs unit tests #52794
Design Picker: Cleanup after extraction to package #51633

**Comment by autumnfjeld** [comment]
@Automattic/ganon  We've been asked to help out with this FSE bug.  I think this could be a good task for Griffith or Ashar, get some experience in the Gutenberg tech and the [Design Picker package](https://github.com/Automattic/wp-calypso/tree/trunk/packages/design-picker).

**Comment by taipeicoder** [comment]
Looking at the code, [shuffling](https://github.com/Automattic/wp-calypso/blob/trunk/packages/design-picker/src/utils/available-designs.ts#L95) works as intended. That being said, after shuffling there is [sorting](https://github.com/Automattic/wp-calypso/blob/trunk/packages/design-picker/src/utils/available-designs.ts#L100) step where designs with the property `is_featured_picks`  are prioritized.

The list of designs with the property `is_featured_picks` are:
* Blank Canvas
* Twenty Twenty-Two
* Twenty Twenty-Two Swiss
* Twenty Twenty-Two Pink
* Twenty Twenty-Two Mint
* Twenty Twenty-Two Red
* Twenty Twenty-Two Blue

As result, the first seven items of the final list will always be a shuffled version of the designs listed above, giving the impression that the design picker is not properly shuffling designs. Since this is the expected behavior, would be good to discuss next steps, to either:

1. Leave the behavior as is but make it clearer in the UI that these designed are featured.
2. Remove the sort step and output the shuffled list. 
3. No change for now.

**Comment by autumnfjeld** [comment]
Awesome sluething @taipeicoder !  @vindl if we don't want TT2 to be featured, should the `is_featured_picks` be removed? Or is that used in the Theme Showcase to feature there?  If we are worried about metrics representing similar behavior to "before FSE" then I'd think we don't want these to be featured.

And if we are going to feature things differently between Theme Showcase & /new Design Pickers maybe the tag needs to represent that. e.g. `is_feature_picks_showcase`.  I'm only guessing at what might be the motivation here. 

Also @taipeicoder note if we need to do some temporary hack here to only feature Blank Canvas at the top, that might be ok, because the /new flow is being deprecated.

Let us know what you think is best Marko. 

cc: @simison

**Comment by arthur791004** [comment]
I think we can just remove `is_featured_picks` for those themes from [available-designs-config.json](https://github.com/Automattic/wp-calypso/blob/67e2c946767a595c90f86777364d87cbb9d55bf4/packages/design-picker/src/available-designs-config.json#L42) as Twenty Twenty related themes should not enable this feature. See PCYsg-D3C-p2 for more details about `is_featured_picks`

**Comment by simison** [comment]
Yep, what Arthur said. Just leave blank canvas on top and the rest can be random. 👍

**Comment by vindl** [comment]
>  @vindl if we don't want TT2 to be featured, should the is_featured_picks be removed?

I agree with the previous comments, and I'm fine with removing them. 👍
