### ISSUE TITLE
Premium Content Block not showing subscriber content in editor

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#60871]
### Quick summary

The editor doesn't show the content which has been published for subscribers

To illustrate
* Go to this page - https://wordpress.com/post/arizkattsherbs.com/1588
* Select subscriber view. Nothing shows but the words 

Subscriber Content
Add content here that will only be visible to your subscribers.

* Go to the public page https://arizkattsherbs.com/2022/02/05/bts-bee-garden/
* There is plenty of subscriber content.

### Steps to reproduce

Pls see note above

### What you expected to happen

The subscriber content to appear in the editor

### What actually happened

Pls see note above

### Context

2 current cases
4751339-zd
4751395-zd

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Remake the page.

**Comment by renata-franco** [comment]
This is my third one today: 4709244-zd-woothemes

**Comment by hanananah** [comment]
Another case here: #34078427-hc

Wants to be notified when resolved

**Comment by rw-ye** [comment]
Another report of it here: 4760520-zd-woothemes

**Comment by connorhipps** [comment]
Another report here as well: 4772028-zd-woothemes

**Comment by JoshuaGoode** [comment]
We're seeing a similar issue, no subscriber content in the editor, on an Atomic site.

See p9F6qB-8uA-p2#comment-45599

Reached out to Ajax via a crosspost and in Slack. p1644610878445909-slack-CJS75TX3R

**Comment by jp-imagines** [comment]
Another in 4769302-zd / p9F6qB-8vb-p2

**Comment by JoshuaGoode** [comment]
Once the bugfix reaches Atomic, via a Jetpack update, we'll want to test and then update this user: 4766556-zd-woothemes

> Another in 4769302-zd / p9F6qB-8vb-p2

Looks like that is an Atomic user as well: 4769302-zd-woothemes

**Comment by kraftbj** [comment]
@Copons is deploying this to the Simple platform now. For the Atomic platform, it will go out as part of next week's weekly release (Wednesday) at the latest, if not before. Content is not lost.

**Comment by Copons** [comment]
I've just deployed the fix on Simple, and confirmed it's working on the site reported by @rickmgithub too.

The issue was caused by a regression introduced in #22626, where we inverted the order of the tabs of the Premium Content block.

When users edited a post containing a PC block created before the change, the block editor parser would notice the different format, and figure the block must contain some incorrect content. It then discarded it, restoring the initial placeholder content.

The fix involved reverting to the old tab order (to fix the issue for old PC blocks), and adding a migration step from the new order to the old one (to prevent the issue from happening for PC blocks inserted after the regression).

### The Bad News

Atomic sites won't be fixed until February 16 (at the latest), so we'll keep getting reports for a while. 😞 

### The Good News

The content is not lost.

The issue only affects the moment when Gutenberg loads the post into the editor canvas.
Any customizations on the PC block are safely stored in the post content in the database — reason why the block was working fine on the front end.

If a user has saved the post after Gutenberg replaced the custom content with the placeholder, they will still find it in a post revision.

### How can we support users?

Simple sites users have already got a fix, so I guess we could just ask them to reload the editor? 😅 

If they overwrote the custom content, we could guide them towards restoring the appropriate revision.

Atomic users will still need to wait a little bit.
We could reassure them that the fix is ready and will land next week.
Meanwhile, we could suggest not touching affected posts until the fix: the premium content is still available to their subscribers, and they won't risk accidentally overwriting it, potentially making a restore trickier.

**Comment by JoshuaGoode** [comment]
Thanks for the quick fix and detailed overview @Copons.

Reopening until the fix lands on Atomic. For tracking and visibility purposes.

**Comment by arunsathiya** [comment]
4774892-zen; offered to followup once the bug is fixed.

**Comment by dolgelukkig** [comment]
33886268-hc

advised the user to not change the post and wait for a few days.

**Comment by fashuvo** [comment]
Another report on 28311099-hc.

User already tried restoring from auto-save and updating the post. I suggested them to not make any more changes.

**Comment by aleone89** [comment]
Another possible related case here: 

4781956-zen

With the above, the following happened: 
1. Site went from Simple to AT
2. This disconnected Stripe 
3. The premium content in the subscriber view was deleted

I had to AT Revert the site, re-create the plan > re-assign the plan to content.

**Comment by ariel-maidana** [comment]
Another possible related case (AT site):

4707915-zen

- They say subscribers have to wait one or two hours to access the content after it's posted.
- They say the issue is worse in the WP mobile app.

**Comment by thekingsprojects** [comment]
Another case here (AT): 4782833-zen

Let user know that a fix for AT sites should be available tomorrow; they'd probably appreciate another follow-up once the fix is live, however.

(It looks like they may have overwritten some of their content trying to restore revisions, so they may have to restore those few posts manually after the fix is live.)

**Comment by JoshuaGoode** [comment]
This should be fixed on WPCOM Atomic shortly with the deployment of Jetpack 10.7-a.5

https://github.com/Automattic/jetpack/blob/8cd1d7faad7df76904963b2caed2d10bdef88eac/projects/plugins/jetpack/CHANGELOG.md

p9o2xV-1So-p2

**Comment by ccwalburn** [comment]
Adding this ticket for a user who wants to be notified: 4775976-zen. 
This is a follow up from the chat above: 33886268-hc

**Comment by Copons** [comment]
I've just double-checked the sites linked by @ccwalburn and @thekingsprojects, and the Premium Content issue reported for both seems to be solved.
Thanks for bearing the brunt of the regression we've introduced.
I'm finally closing this issue!

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
