### ISSUE TITLE
Jetpack Connect: wrong redirection URL when site admin in subdirectory

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#6088]
#### Steps to reproduce
1. Set up a self-hosted WordPress site with the root install in its own directory. You should have these values for the site URLs:

**WordPress Address (URL)**: http://example.com/wp
**Site Address (URL)**: http://example.com/
1. Install & activate Jetpack on your site, but do not connect it
2. Log in to your site and to WordPress.com
3. Go to WordPress.com/jetpack/connect, your site URL `http://example.com/`, and click the connect button
4. See that the process does not recognize the location of Jetpack & shows the installation screen:
   <img width="1287" alt="screen shot 2016-06-16 at 9 38 58 am" src="https://cloud.githubusercontent.com/assets/11487924/16118674/2ca5c592-33a6-11e6-8571-ecc50fc6716f.png">
5. If you click on 'Install Jetpack' you'll get a 404 error at this page:
   `http://example.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=jetpack`
   This is the wrong URL - it's missing the /wp required to see my dashboard
#### What I expected

I expected the process to correctly detect where my root install folder is when Jetpack is already activated.

**Comment by designsimply** [comment]
I was unable to get past step 3 because I ran into issue https://github.com/Automattic/wp-calypso/issues/6085 as a blocker even after [updating to a subdirectory install](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory#Using_a_pre-existing_subdirectory_install).

![screen shot 2016-11-30 at wed nov 30 12 06 01 pm](https://cloud.githubusercontent.com/assets/1119271/20766917/6df07c68-b6f5-11e6-8f58-fb95f8653cef.png)
<sup>Seen at https://wordpress.com/jetpack/connect using Safari 10.0 on Mac OS X 10.12 with a fresh WordPress 4.6.1 install on Bluehost.</sup>

**Comment by BandonRandon** [comment]
I'm closing this one in favor of #10980 as the redirect link does work when a site URL is added. 

If you're still having trouble feel free to re-open this one.
