### ISSUE TITLE
Latest Posts homepage scrolls down to first slideshare

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/wp-calypso#60906]
### Quick summary

Customer's homepage automatically scrolls down to whatever the first slideshare is.  If I remove the slideshare from one post it automatically scrolls to the next post that contains a slideshare.

### Steps to reproduce

1. Open Site which has slideshare block in one of the posts and is set to Latest Posts for Homepage.

### What you expected to happen

Page to load and focus to remain at top of page until scroll.

### What actually happened

Page scrolls down to whatever the first slideshare is.

### Context

See: hc34078843 for details.

Slideshare is shortcode in a classic block.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No, affects all themes.

### Browser, operating system and other notes

All

### Reproducibility

Consistent

### Severity

One

### Workaround details

Workaround of converting to slideshow blocks or shortcode blocks in the block editor instead of classic block wasn't able to be tried.

**Comment by kimerlin81** [comment]
@paxblueribbon Thanks for submitting this bug report. It has now been triaged.

I was able to reproduce as shown below:

https://user-images.githubusercontent.com/83732167/156365172-fab334c4-7a7d-4bc5-9d14-d515d5b443f3.mp4

The scrolling behavior only seems to happen when the Slideshare shortcode is used. The page did not scroll when I used the Slideshare URL.

**Comment by yansern** [comment]
This is happening because in Slideshare's `scrollToSlide()` function, they call `element.scrollIntoView()`.

Unfortunately, there is a bug exploit where calling `scrollIntoView()` in child iframe can cause parent window to scroll to the element within iframe.

This scrolling into view happens when:
- when the page loads initially
- when the window is resized and their resize event listener calls `scrollToSlide()`.

![image](https://user-images.githubusercontent.com/1287077/162225640-c606c635-27be-4252-a764-9081c6d02c3a.png)

![image](https://user-images.githubusercontent.com/1287077/162225660-21214bbd-76d7-42d9-8c5b-96f249178fc7.png)

More information about the `scrollIntoView()` bug exploit here:
- https://stackoverflow.com/questions/70940758/how-do-i-forbid-an-iframe-from-scrolling-its-parent-window
- https://github.com/w3c/webappsec-permissions-policy/issues/171
- https://github.com/w3c/webappsec-permissions-policy/blob/main/policies/vertical_scroll.md

We can only wait until this feature policy is implemented `<iframe src="..." allow="vertical-scroll 'none'"></iframe>` before we can _really_ fix it on our end.

> The scrolling behavior only seems to happen when the Slideshare shortcode is used. The page did not scroll when I used the Slideshare URL.

For shortcode, this happens on initial page load & when resizing or zooming the browser window.
For block, this happens when resizing or zooming the browser window.

**Comment by yansern** [comment]
~One fix we can do, based on this PR https://github.com/Automattic/jetpack/pull/23853#issuecomment-1091858496, is to set `frameborder=0` in the shortcode iframe. This fixes scrolling on page load at least.~

UPDATE: The behaviour is inconsistent across themes. There is nothing we can do to fix this on our end. I sent a message to Slideshare (through their online contact form) to see if they can avoid doing `scrollIntoView`. Just use the classic window scroll or jQuery's scrollTo (since that library is loaded on slideshare).
