### ISSUE TITLE
Marketplace: promote Yoast Premium

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#60923]
As we are planning to launch Yoast, it would be great if we have some visuals (banner?) to promote it in the plugins screen or even (additionally) an announcement modal.

**Comment by obenland** [comment]
We'll create a Spotlight component that can be re-used for various plugins to be highlighted at the top of the plugin screen. An example for WooCommerce looks like this:

![image-2](https://user-images.githubusercontent.com/1398304/153093664-b76ad2c4-23ae-4f69-8f99-a25b7393bac2.png)

For this iteration, let's have props for a plugin object, an illustration, a background color, and maybe a promo text?

See pdh6GB-gN-p2

**Comment by SaxonF** [comment]
@obenland updated the design to simplify this a little bit initially. We wont need a background colour.

![image](https://user-images.githubusercontent.com/1072756/153506692-2bc71405-a6d7-4a17-9785-e315f8abd88e.png)
![image](https://user-images.githubusercontent.com/1072756/153506810-861a3bd0-dc65-4fb3-88b2-982223c794ff.png)
![image](https://user-images.githubusercontent.com/1072756/154466977-4875302c-9d92-4e7b-b8e7-4084480bb183.png)

Note that for this issue we're focused on the spotlight component that will be added at the top of the featured section. It should have a logo and a tagline and link off to the plugin detail page. The whole component should be clickable. 

Edit: updated again to remove illustration for now and keep it simple until we have time to create a set for each major category of plugin.

Note: This issue is only for the spotlight component and not the surrounding areas (search etc).

**Comment by cpapazoglou** [comment]
The URL for the CTA should be `https://wordpress.com/plugins/wordpress-seo-premium/:site?`. 

In the future we can add an endpoint for "editing" this section from the backend (without needing to deploy Calypso).

**Comment by allilevine** [comment]
Needs to be behind a flag for now (Yoast feature flag?).

**Comment by cpapazoglou** [comment]
> Needs to be behind a flag for now (Yoast feature flag?).

Yes, please! `marketplace-spotlight` in my opinion. It targets the feature rather that the content.

**Comment by lsl** [comment]
We're still waiting on a decision on how / when / what conditions this is shown to users.

For this sprint we're scoping this issue to building the promotion component.

Stand alone `marketplace-spotlight` makes sense for this sprint. Next sprint we can replace that with conditional logic once we know what it is. Turning on the flag with `?flags=marketplace-spotlight` will just show the promo on every screen for debugging/demo purposes.

**Comment by cpapazoglou** [comment]
> Stand alone `marketplace-spotlight` makes sense for this sprint. Next sprint we can replace that with conditional logic once we know what it is. Turning on the flag with `?flags=marketplace-spotlight` will just show the promo on every screen for debugging/demo purposes.

Initially I thought that we will just show the spotlight to everyone. After thinking it a little bit more, I think we should be showing the spotlight plugin only for users who don't have it installed. Perhaps, we can have a list of spotlight plugins that will pop up a promoted plugin that is not installed. How does this sound @SaxonF ?
