### ISSUE TITLE
Atomic: Sync feature list to wpcomsh

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60966]
### Details

Let's see if we can find a way to bring the feature list from dotcom to wpcomsh. This will enable us to check if sites have access to certain features based on their purchases and allows for features to work separately from the plans that bundle them.

See pdG1ka-17-p2

### Checklist

- [ ] Prep feature list in wpcom to be portable
- [ ] Create a file with a function in it that is the same in WPCOM and wpcomsh, with comments that both exist and need updating

### Related

#60965

**Comment by obenland** [comment]
Let's make sure what ever mapping we come up with can be reused on wpcom

**Comment by mreishus** [comment]
Explored one "baby step" idea here: D74966-code + pdG1ka-2M-p2.
It's mostly taking what we already have and splitting it into separate files with minimal dependencies, in order to set up those files being copy and pasted later.
Definitely not committed to the idea and looking for feedback. Is it too confusing? Does it make sense? etc.

**Comment by DustyReagan** [comment]
I took at a stab at this by beginning/approaching from the WPCOMSH side here: 814-gh-Automattic/wpcomsh. Next step would be to create a WPCOM patch implementing class-purchases-features-map.php.

**Comment by DustyReagan** [comment]
I think is issue is addressed with D75219-code and 814-gh-Automattic/wpcomsh.

**Comment by obenland** [comment]
Fixed in D75219-code, D75572-code, 820-gh-Automattic/wpcomsh, and 814-gh-Automattic/wpcomsh.
