### ISSUE TITLE
FSE: Create a "Post Read More Button" block for use with Query Loops / Post Templates

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#60972]
### What

Create a "Post Read More Button" type block that can be used with the Query Loop Block / Post Template.

The ability to use a button that links to the link within a Query Loop Block > Post Template would be awesome! 

### Why

Right now, the Post Excerpt block adds a "read more" link via text, but that doesn't offer much customization.

You can add a Buttons Block within the same group, but that requires manually linking it to the right post. That means if you're using the Query Loop Block for a single highlighted post, the button must be manually updated.

<img width="1398" alt="Markup 2022-02-09 at 09 58 09" src="https://user-images.githubusercontent.com/27249804/153276092-cbe9437b-2f48-47e7-9666-90b724f58abd.png">

<img width="1408" alt="Markup 2022-02-09 at 09 59 11" src="https://user-images.githubusercontent.com/27249804/153276165-3bbcf5f4-1983-4c5f-bf65-8afcbbd4ca44.png">

**Comment by dcoleonline** [comment]
+1 to this, as manually adding the Read More link can be difficult to discover

34480947-hc

**Comment by jp-imagines** [comment]
Looks like this has been implemented: https://github.com/WordPress/gutenberg/pull/37649

It's a link instead of a button, but it has background color, padding, and border controls, so you can style it as if it's a button. I'm seeing it available on simple and WoA sites.
![Markup on 2022-05-13 at 12:07:10](https://user-images.githubusercontent.com/5630717/168323521-2c7ce7df-18cd-4bbe-807e-6cb9cae70d2e.png)
