### ISSUE TITLE
Seller Experience: The blog name and tagline data is not passed on to the Woo onboarding flow.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60978]
We have a step in the seller experience flow that allows the user to enter their site title and tagline. This works for the simple flow, but the data does not get passed to the Woo onboarding for the "more" flow.

<img width="874" alt="Screen Shot 2022-02-09 at 2 51 26 PM" src="https://user-images.githubusercontent.com/349751/153303979-ad9b5c39-9628-400b-9f6a-86909ffb2ee1.png">

**Comment by kwight** [comment]
We should be able to save this straight to the database on Continue – that way it's already set before we get into the Woo flow (which itself has no similar step).

**Comment by kwight** [comment]
How does this work already in the blogger flow? At some point, it's being set before showing the editor to the user. There's a "defer until of flow" setting of `true` for this step – we'd need to find out if that's done for any particular reason (we could also just handle differently depending on intent, but that adds more complexity).

**Comment by sixhours** [comment]
Similar to how we handled the simple flow, I think what we need to do is leverage `getDestinationFromIntent` to handle the redirection to the Woo flow; that allows us to submit the signup step with its dependencies intact and carry them through the rest of the process.

**Comment by kwight** [comment]
@sixhours I thought we were going to just save the title and tagline right from the step, so that it's already done by the time the user starts the Woo flow?..

**Comment by sixhours** [comment]
> I thought we were going to just save the title and tagline right from the step, so that it's already done by the time the user starts the Woo flow?..

We could do that, but I thought it made more sense to work with the signup infrastructure by formally "closing" the flow using `goToNextStep` rather than bailing out with a `page` redirect. Let's chat about it at some point, because I think we're talking about the same thing. :D

**Comment by sixhours** [comment]
Aha, wait, I get what you're suggesting now! So yes, we can make a one-line change to make sure the site title and tagline are submitted at the time of entry rather than at the end of the flow, by removing this line:

https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/config/steps-pure.js#L190

That does fix the bug. But the blogger flow also uses `goToNextStep` and takes advantage of the signup infrastructure, similar to what I've done in #61093:

https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/starting-point/index.tsx#L41

This has the benefit of consolidating the redirect logic into one place and is consistent with other signup steps, so I think it makes sense to do this as well.
