### ISSUE TITLE
Installing themes on Atomic Free sites does not work.

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#60981]
### What plan tier(s) are affected?

Free, Personal, Premium

### Steps to Reproduce

Go to [themes showcase](https://wordpress.com/themes/) on a free Atomic site. Try installing a free theme from the showcase.

### Expected (Simple)

The free theme installs fine on a simple site.

### Expected (Atomic)

The free theme should install on an Atomic site.

### Actual

Trying to install a theme produces the error "Theme not yet available for this site"

![theme-not-yet](https://user-images.githubusercontent.com/140841/153310811-90798662-89bf-413d-8e53-0f4f743a15df.png)

**Comment by obenland** [comment]
I'm not sure why but I'm currently having trouble sandboxing the API to debug this :(
Will loop back later.

**Comment by obenland** [comment]
This is caused by the `install_themes` capability being disabled on sites with these plans.

Calypso sends two requests when switching themes on a WOA site, one to install the chosen theme and a second one to switch to that new theme.
On lower-tier plans it can't install the theme because that capability is unavailable and then the subsequent theme switch call returns an error ("Theme not yet available for this site")
