### ISSUE TITLE
Domain: Expiring notice overflow

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#6098]
The expiring notice on the sidebar is overflowed when the domain name is a bit long.

![image](https://cloud.githubusercontent.com/assets/991022/16128825/0f5ec55e-33b7-11e6-8855-81dd2132602c.png)

@breezyskies is there a way to force linebreak here?

**Comment by breezyskies** [comment]
`word-wrap: break-word;` should work.

**Comment by klimeryk** [comment]
Worth revisiting this issue after #3329 is merged and this notice is displayed as the compact version.

**Comment by klimeryk** [comment]
Unfortunately, `word-wrap` alone doesn't seem to do the trick :/
<img width="297" alt="screen shot 2016-08-15 at 13 24 48" src="https://cloud.githubusercontent.com/assets/3392497/17663600/f4752d94-62ed-11e6-916f-1b62794c932c.png">

The problem seems to be that behind the scenes, the notice is expanded (flex grow probably) as needed:
<img width="377" alt="screen shot 2016-08-15 at 13 43 53" src="https://cloud.githubusercontent.com/assets/3392497/17663656/675ddfae-62ee-11e6-84ed-b92be650cfaf.png">

Probably best if a designer looked at this and found a proper fix (since we don't want to break compact notices in other parts of the application).

**Comment by breezyskies** [comment]
Adding this to our backlog but probably won't get to it soon.

**Comment by umurkontaci** [comment]
95% of .com domains are less than 28 characters. It'll fit :) This might only be a problem with subdomain mappings.
