### ISSUE TITLE
FSE: Emptying a Site Does Not Empty Template Parts

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#61090]
### Quick summary

Emptying a site that has template parts edited via the site editor does not clear out the modified template parts.

### Steps to reproduce

1. Edit a site's templates through the Site Editor.
2. Search for the site in Network Admin.
3. Use the `empty` option to reset it and remove all content.
4. Once confirmation is received that the process is complete, open the site.

### What you expected to happen

All pages to be gone and the site returned to a default empty state.

### What actually happened

The posts/pages were removed, but the edits to template parts - blocks, their settings and text, and global styles - remained. 

### Context

Ran into this when emptying a simple site we were using as a staging site for a Team51 partner. I emptied the site to prepare for a clean import but was surprised to see our template changes still intact when the process was complete.

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Workaround details

The edited template parts have to be manually cleared out by editing them in the Site Editor.

**Comment by edequalsawesome** [comment]
I was able to duplicate -- since this would prevent complete site resets for FSE sites, I marked this as a high priority

**Comment by arunsathiya** [comment]
As part of my triage work here pc4f5j-1Tr-p2, I am moving this to Normal priority because it's not often that customers reach out for a site empty, and even we process an empty, the templates are cleared (as verified in my tests now)

It's just template parts that need to be reset/fixed manually.

Before:

<img width="894" alt="image" src="https://user-images.githubusercontent.com/18581859/169665732-6e108c9f-bb69-4619-b90f-ca47ea25f6fc.png">

After:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/18581859/169665743-b13091c1-01ea-42cd-98d3-b9b95df7027b.png">

I was expecting that the template part for the Site Title be reset back to H1 instead of the manually set H6.

**Comment by arunsathiya** [comment]
I cannot reproduce this on a WordPress.org site with a reset database plugin. I changed H1 to H6 on a Site Title block, reset the site and then visited the same template. 

![image](https://user-images.githubusercontent.com/18581859/169665974-d8df43b1-0aad-4b45-ab33-a1ed67bb846d.png)

![image](https://user-images.githubusercontent.com/18581859/169665978-8beac13f-651c-4771-9aa4-94b706d82350.png)

I see the Site Title template part to be H1 now, as expected:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/18581859/169665970-d085567f-c012-4bf2-980d-828e143fa087.png">

But, it gets interesting with an Atomic site.

With the same `reset-database` plugin, I can reproduce the original report's behavior. 

So, it's something about the Gutenberg implementation in Dotcom that causes this behavior.

**Comment by masperber** [comment]
Affected user: 35620396-hc asked for their site to be reset, and asked why the menu wasn't reset too after I did a headstart.

I reproduced the issue on a test site.

**Comment by Addison-Stavlo** [comment]
D90791-code aims to resolve this.

**Comment by agrullon95** [comment]
Fix to empty template/template_parts have been deployed: D90791-code.
