### ISSUE TITLE
Seller experience: The "Buy now" button is not translated.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61178]
The "Buy now" button appears to be the only untranslated part of the commerce pattern. It should also be sentence-case ("Buy now").

<img width="1263" alt="Screen Shot 2022-02-16 at 12 23 29 PM" src="https://user-images.githubusercontent.com/349751/154351161-58801f17-4b85-45b9-b7c4-4024fc4a7395.png">

**Comment by sixhours** [comment]
I've updated the pattern to use sentence case:
<img width="517" alt="Screen Shot 2022-02-16 at 3 41 32 PM" src="https://user-images.githubusercontent.com/2124984/154353560-6e0d907d-086a-4bd0-9c72-f2d76f3f7de3.png">

The button text differs from the other headings/paragraphs in that the default text comes from the block properties, so I suspect that's why it's not localized:

<img width="944" alt="Screen Shot 2022-02-16 at 3 44 42 PM" src="https://user-images.githubusercontent.com/2124984/154353933-96e6012d-c01b-48f5-90b6-cdc2bc7beb7b.png">

I ran into similar issues trying to use translated strings within the hard-coded block markup in #61137.

**Comment by sixhours** [comment]
Reading up on translations for the block patterns, it looks like strings from post content get automatically imported to GlotPress: PCYsg-t0E-p2

So the next step is to figure out if the "Buy now" string is new and just hasn't been pulled into GlotPress yet, or if the automated process does not "see" strings that are block properties rather than block contents.

**Comment by sixhours** [comment]
OK, checked out the Glotpress importer on my sandbox and looked at all strings from the patterns site. The "Buy now" string does not show up in the output, which tells me it's probably not seen by the importer.

I also checked GlotPress itself, and the "Buy Now" string does not exist there yet.

There may be another way to add text to the button without using a block property, going to test that now.

**Comment by sixhours** [comment]
I tried adding the button text string as a child element of the block rather than a property, like so:

```
<div class="wp-block-jetpack-recurring-payments">
<!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-id","text":"Buy now"} -->
This text should be translated!
<!-- /wp:jetpack/recurring-payments -->
</div>
```

But it just breaks the block.

Other button-based blocks (like the subscriptions block, which has a "Subscribe" string for the button) include the same strings in the block's properties AND its content/children, which is why their strings are available to the GlotPress importer. Example source for a subscriptions block:

```
<!-- wp:jetpack/subscriptions {"submitButtonText":"\u003cstrong\u003eSUBSCRIBE\u003c/strong\u003e" }-->
<div class="wp-block-jetpack-subscriptions">
[jetpack_subscription_form submit_button_text="<strong>SUBSCRIBE</strong>"...]
</div>
<!-- /wp:jetpack/subscriptions -->
```

Note the `SUBSCRIBE` string is available as `submitButtonText` but also in the block contents' shortcode; the string in the shortcode is able to be parsed by the GlotPress importer for patterns, so it gets translated.

So I think to get the "Buy Now" string translated we need to either:

* Update the Recurring Payments block to allow for strings to be inserted as children/contents of a block or...
* Update the parser to import strings from other parts of the block; maybe we could make it look at the `placeholder` and `text` properties, for starters.

I need to investigate how the importer itself works, though; is it parsing the block content before or after rendering?

**Comment by kwight** [comment]
Good investigation @sixhours , so it sounds like GlotPress just doesn't support strings in block properties. 🤔  @dlind1 any ideas how we might best approach this?..

**Comment by sixhours** [comment]
In looking at the block parser for buttons, we do account for placeholders. Inserting a button into a pattern reveals a translated placeholder:

<img width="497" alt="Screen Shot 2022-02-17 at 11 11 31 AM" src="https://user-images.githubusercontent.com/2124984/154522534-d44d3c96-cb1a-4d8d-bc54-9d24d7e4eb1a.png">

But the Recurring Payments button does not seem to behave like a regular button, so that's probably why the parser doesn't see it/account for it. The source for a regular button:

```
<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">I'm a button!</a></div>
<!-- /wp:button -->
```

The source for the Recurring Payments button:

```
<!-- wp:jetpack/recurring-payments -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-id","text":"Buy now","customTextColor":"#ffffff","backgroundColor":"black","borderRadius":0,"width":"100%"} /--></div>
<!-- /wp:jetpack/recurring-payments -->
```

So I suspect this is an issue with the Recurring Payments button using a Jetpack version of a button block, specifically.

**Comment by sixhours** [comment]
Yes, looking at the parser at `wp-content/lib/patterns/parser.php`, we've accounted for other Jetpack blocks (contact form, subscriptions) but not Recurring Payments. We probably need to add a for Recurring Payments, otherwise it falls back to the basic text parser, which won't find a block's properties. Will see if I can write one.

**Comment by kwight** [comment]
Great @sixhours , sounds like a plan – go for it. 👍

**Comment by sixhours** [comment]
Started working on this in D75214-code

**Comment by sixhours** [comment]
Fixed in D75214-code
