### ISSUE TITLE
[Bug]: The (?) That shows up in the bottom right corner of select media page overlaps the over buttons on mobile.

### ISSUE THREAD

**Issue by spraveenitpro** [Automattic/wp-calypso#61221]
### Quick summary

The `?` that shows on the mobile when selecting image from pexels, overlaps like this over other buttons:

![](https://d.pr/i/2Oqnpc+)
[Direct Link](https://d.pr/i/2Oqnpc+)

### Steps to reproduce

1. Open WordPress.com on mobile phone and login
2. Now, create a new page by clicking the compose button on top
3. Now, try to add an image block and select free image from pexels like this:  ![](https://d.pr/i/wF4QIC+)
[Direct Link](https://d.pr/i/wF4QIC+)
4. As you can see the `?` overlaps the button on that page

### What you expected to happen

The `?` should not show up on that page

### What actually happened

The `?` shows up on the select media page and overlaps the button

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Other notes

@enejb @tyxla 

### Reproducibility

Consistent

### Severity

One

@enejb @tyxla

**Comment by tyxla** [comment]
Nice find @spraveenitpro 👍 

IMHO the inline help button shouldn't overlap the button, but should still be on the page. This could be achieved with some additional padding at the bottom for mobile perhaps?

I'd also ask for @enejb's opinion on what's best to be done here.

**Comment by brookewp** [comment]
@tyxla I took a peek at this and compared it to our media library and it covers up the help button completely. So maybe it would make sense that the Pexels library would do the same? 🤔 Unless we'd want all of the library options to include the inline-help button. 

I'd love to help work on a fix for this, either way!

**Comment by spraveenitpro** [comment]
Hey @brookewp @tyxla  I am currently working on this. 👍

**Comment by tyxla** [comment]
Sounds good, thank you both! Feel free to ping me in a PR or if you need anything in the meantime @spraveenitpro @brookewp

**Comment by enejb** [comment]
> I'd also ask for @enejb's opinion on what's best to be done here.

I think if it would be possible we should trigger the hiding of the (?) every time we show a modal on mobile. 
The problem with modals on mobile is that we lose the ability to scroll and the (?) becomes fixed and then ends up overlapping UI elements. So fixing it for all modals will help this issue not appear in the future. Instead of just fixing this one modal. 

I haven't investigated this solution yet but that is what I would try to do first.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic (Mobile Safari) - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- With the more recent work on Jetpack/WordPress apps and the updated Help Center, this issue seems to no longer be a problem.

![IMG_F004A8D33A02-1](https://github.com/Automattic/wp-calypso/assets/27249804/4cd70722-17ac-49a5-bf17-2812de8fb3a9)

📌 ACTIONS
- Closing as not reproducible
