### ISSUE TITLE
View Page Links Stopped Opening on New Tab

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#61237]
### Quick summary

When you publish a new post or page, the View Page link doesn't open the content on a new tab.

### Steps to reproduce

1. Start a new page or post
2. Publish the content
3. Click on the View Page link while holding Cmd/Ctrl

### What you expected to happen

To open the new page/content on a new tab. This was recently working, and it stopped for some reason.

### What actually happened

Nothing happens when you click on View Page while holding Cmd/Ctrl. It only works when clicking the link, which exits the editor opening the content on the same tab.

### Context

Here's the link I'm referring to:

![ViewPage_1](https://user-images.githubusercontent.com/16104522/154666895-308c0824-1a4e-4424-b436-e647b1ef3332.jpg)

![ViewPage_2](https://user-images.githubusercontent.com/16104522/154666902-e16d129e-b9a6-4ec5-8b51-6e4421a6ac31.jpg)

### Browser, operating system and other notes

Replicated this on Chrome and Firefox.

### Available workarounds?

Yes, easy to implement

### Workaround details

If you don't want to open on the same tab, you can go to the page's settings, and click on the page's URL from the Permalink section, Cmd + Click works in there.

**Comment by Robertght** [comment]
I can replicate this and I've pinged here: p1646405319013729-slack-C02DQP0FP

**Comment by cometgrrl** [comment]
@autumnfjeld It looks like y'all fixed this a few months ago, but it's back. Does it make sense for Ganon to take a look at it?

**Comment by arthur791004** [comment]
Seems like the root cause is we [remove jquery from wpcom block editor](https://github.com/Automattic/wp-calypso/pull/60225). The `triggerOverrideHandler` disables the default behavior for Cmd + Click. If we remove the following click event handler, it would work correctly.

![image](https://user-images.githubusercontent.com/13596067/160823723-79c91e91-0285-4ed9-892d-83effccaadbc.png)

See https://github.com/Automattic/wp-calypso/blob/25f75cb74b372a82f09f3bb81d4fe2ae4cb7fb59/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L67

cc @noahtallen

**Comment by noahtallen** [comment]
Thanks for finding the problem, definitely an oversight when changing the event handlers there. A fix: https://github.com/Automattic/wp-calypso/pull/62504
