### ISSUE TITLE
[Bug]: Pay with Paypal block: Block not saved in Widgets in Customizer

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#61319]
### Quick summary

When adding a new Pay with Paypal block in the Site Editor and in Widgets page, the block does not appear after the user updates the page.

### Steps to reproduce

1. Go to Appearance > Customizer > Widgets
2. Add a new Pay with Paypal block and press Save
3. Go to the front-end and notice that the block is not displayed
4. Go to the editor and refresh the page. The block appears in the editor.
5. Go back to the front-end and notice that block is being displayed on the front-end (after the refresh).

### What you expected to happen

The block to be displayed when the user clicks on the save/update button.

### What actually happened

The block is not visible on the front-end even though it's displayed in the editor.

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

### Workaround details

The user will need to refresh the editor page in order for the block to be displayed on the front-end.

**Comment by dsas** [comment]
It's not appearing because the product isn't being saved properly - it needs to POST to `/wp/v2/jp_pay_product/` to save the product as a CPT rather than just as block attribs.

If you reload the editor *after* saving the template with the change, then it will make that POST and save the product

----

It looks like there's logic in `componentDidMount` to do with saving using the `isPostEditor` prop that isn't in `componentDidUpdate` which was first introduced in [Jetpack#19571](https://github.com/Automattic/jetpack/pull/19571/)

https://github.com/Automattic/jetpack/blob/f57435be62e89c0767bae5c66a2d455f4299b455/projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js#L62-L66

There's also an `isSaving` prop which is defined by checking to see if a post is being saved, this is always false on a widget/fse screen.

Both of these props are always false outside of a post context during  [`componentDidUpdate`](https://github.com/Automattic/jetpack/blob/f57435be62e89c0767bae5c66a2d455f4299b455/projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js#L81), which is the root of where the POST request is made.

----

The solution is probably to change the `isSaving` prop to be true if saving an FSE template or widget area as well as a post.

If that doesn't work then the condition in `componentDidUpdate` which checks whether to save, will probably need to do something akin to the `isPostEditor` check in `componentDidMount` - though need to be careful not to get stuck in an infinite loop :-/ as validateAttributes will update the state.

**Comment by dsas** [comment]
> The solution is probably to change the isSaving prop to be true if saving an FSE template, customizer or widget area as well as a post.

The widgets store is edit-widgets and it does have `isSavingWidgetAreas` which looks to be an `isSavingPost` equivalent. I've pushed a [jetpack draft pr](https://github.com/Automattic/jetpack/pull/23216) which does this.

The FSE store is edit-site, and it doesn't have an isSavingPost equivalent, also I can't see an equivalent for the Customizer (this block is barely usable there at all)

----

It feels like "I need to save some information via a rest api" is a problem umpteen blocks must have sold by now. Why is this one so different?

It feels like the problem is that it's not clear when the user has finished editing the product, giving rise to these options:
 * Save on change/blur of each field, maybe noisy
 * Save when deselecting the block, user has to realise they need to deselect.
 * Save when the context the block is in is being saved - current solution, doesn't work for all contexts
 * Have an explicit save button

recurring-payments lets you choose from an existing saved "product" (plan) or add a new one - which has a "save" (well Add this payment plan) button.

Having an explicit save button would be much easier and more reliable but would probably not be obvious with the current block design...

**Comment by Robertght** [comment]
4828843-zen

**Comment by dsas** [comment]
The [aforementioned PR](https://github.com/Automattic/jetpack/pull/23216) fixes this for the widget editor and for FSE but not for widgets inside the customizer (not a regression from the PR).

I think this would require hooking a save event from the customizer. I think it might be [changeset-saved](https://core.trac.wordpress.org/browser/trunk/src/js/_enqueues/wp/customize/controls.js#L640) but I haven't yet looked how to get access to do this from within the pay with paypal widget.
