### ISSUE TITLE
[Bug]: Non-latin characters in Design Picker thumbnails appear as squares

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#61351]
### Quick summary

Some thumbnails appear to be translated, but the text rendering is broken in non-latin scripts. E.g. Quadrat Red in Japanese

<img width="615" alt="Screenshot 2022-02-22 at 5 58 05 PM" src="https://user-images.githubusercontent.com/1500769/155065936-94626552-40dd-4a79-981c-1de7bba3acc1.png">

Interestingly, not every Quadrat variant is broken 🤔 

### Steps to reproduce

1. Switch user language to Japanese
2. Head to `/start` to create a new site
3. Proceed through site creation until you get to the design picker

### What you expected to happen

Thumbnails will be partially translated (depends on how far through the translation process is). But the thumbnails that have been translated to Japanese should render those Japanese characters correctly.

### What actually happened

See the screenshot above.

### Other notes

I've tracked it down to being an issue with mShots (which is what takes jpeg screenshots of the theme previews). I can tell that this is the case because when I access the `template/demo` API endpoint directly the Japanese characters render correctly. It's only once I send that API endpoint through mShots that I see the broken text. It could be that the mShots docker container needs some extra fonts installed? Or maybe there's a setting that needs to be adjusted in the headless browser that takes the screenshots?

We may also need to do a little dev work to get the mShots dev environment up to date. When I tried it, it didn't appear to be working in a M1 Apple Silicon environment.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by taipeicoder** [comment]
Regarding not able to run the dev environment on a M1 Apple Silicon environment, the following dependencies were problematic:

* [sharp](https://github.com/lovell/sharp). As discussed in this [ticket](https://github.com/lovell/sharp/issues/2460#issuecomment-811046375), the solution is to upgrade the package from `0.25.2` to `0.28.0`.
* The `Dockerfile` tries to install `google-chrome-unstable` which doesn't exist for the `arm64` arch. Changing it to install `chromium` works, and that allowed me to run `mShot` locally, but this feels like a significant change. Perhaps we can add a conditional so that it install `chromium` in the M1 Apple Silicon environment.

**Comment by p-jackson** [comment]
I also had success adding
```
FROM --platform=linux/amd64 php:7.4-apache-buster
```

to the top of the `Dockerfile`. I think it's instructing Docker not to take any hints from the host environment and to force `amd64`. And on `amd64`, `google-chrome-unstable` is available.

I think 😅  🤷

**Comment by taipeicoder** [comment]
Specifying the platform in the `Dockerfile` as mentioned above also works (and I think the better approach), the dev environment is now able to start but not working. I'm seeing the following error from `mshots.log`:

> Failed to launch the browser: Error: Protocol error (Target.setDiscoverTargets): Target closed.

Still seems related to the M1 Silicon environment, as also reported in this [ticket](https://github.com/puppeteer/puppeteer/issues/7916).

Update: Adding the flag `--single-process` to Puppeteer solves the problem.

**Comment by taipeicoder** [comment]
Here are the issues I've encountered while setting `mShot` on my local M1 Apple Silicon machine (`arm64`) via Docker:

1. The `sharp` library dependency in its current version attempts to build the library while installing it. The build fails due the missing dependency of the library `libvips`. The solution would be to upgrade the `sharp` library to a version that provides a prebuilt binary for `arm64`.
2. Docker attempts to install `google-chrome-unstable` which is as of now not available for `arm64`. Specifying the platform in `Dockerfile` would install the `amd64` version.
3. Running `mShot` results in the error `Failed to launch the browser: Error: Protocol error (Target.setDiscoverTargets): Target closed.` This is an issue from Puppeteer, and I haven't found a good solution. For the moment, running Puppeteer with the flag `--single-process` (that is passed to the browser) works. 
4. Related to (3), since the browser now runs as a single-process, Puppeteer now has issues taking screenshots of pages that have large viewports (e.g.: 1200x3200). Same, no good solution for this but to take screenshots of pages with smaller viewports (e.g.: 600x800).

Next steps: 
Try to reproduce the original bug using local environment, and once resolved come back to the issue described above and see what improvements can be done.

**Comment by taipeicoder** [comment]
On the issue regarding non-Latin characters rendering incorrectly (rectangle boxes) - unfortunately, I was not able to reproduce the issue on my local environment. That being said, I do have some findings that came up while testing `mShots` on production.

To start, it's unlikely that the cause is missing installed fonts. This is supported not only by the fact that other themes' thumbnails render non-Latin characters fine, but also the odd behavior that problematic themes not always result in problematic thumbnails.

For instance, see the two thumbnails below:
![Screen Shot 2022-02-25 at 4 32 23 PM](https://user-images.githubusercontent.com/797888/155682236-4c51c306-d460-46d3-8528-504955d1c785.png)
![Screen Shot 2022-02-25 at 4 34 11 PM](https://user-images.githubusercontent.com/797888/155682348-d2385bfa-525a-4202-b31b-dc910aaed52f.png)

These two thumbnails were generated in the production environment seconds from each other, with exact parameters except for `site_title` which is used for the site title used in the page. See the top-left corner of the thumbnails, one is titled `Quadrat Red A` and the other `Quadrat Red B`. After testing with different site titles, sometimes it results in a problematic thumbnail, sometimes it doesn't.

So what's happening?

Well, it's hard to pinpoint the problem without being able to reproduce it directly on the local environment. The issue is that the expected font is not being loaded properly sometimes. That could be caused by a headless Chrome not properly loading fonts in one of the `mShots` workers, or network connectivity latency that makes Puppeteer to make screenshots of pages before the fonts are finished loading.

The latter theory is easier to test out. While `mShots` already uses several mechanisms to ensure the page is fully loaded before taking screenshots (i.e.: [waiting until there are no more than 2 network connections for at least 500ms](https://pptr.dev/#?product=Puppeteer&version=v13.4.0&show=api-pagegotourl-options), and on top of that wait another 2 seconds before taking the screenshot), we can also add the following code:

`await page.evaluateHandle('document.fonts.ready');` 

This blocks the code until the [browser deems fonts as fully loaded](https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts).

**Comment by taipeicoder** [comment]
After checking with the systems team, we found the problem to be caused by an experimental server in the `mShots` instance pool. The issue has since been fixed and verified by re-queuing the problematic thumbnails.

As this was a server configuration issue, no code change were needed on our end.
