### ISSUE TITLE
Adding stylelint check for css linting

### ISSUE THREAD

**Issue by sendilkumarn** [Automattic/wp-calypso#6142]
Can we add stylelint check for css styling? [Stylelint](http://stylelint.io/)

I will submit a PR if yes

**Comment by designsimply** [comment]
Related: #5999 via @belcherj

**Comment by belcherj** [comment]
@sendilkumarn That is something that would be great for the project.  A PR would be great.  Make sure to tag me so that I can review.

A couple of notes:

This would probably be a good start:  https://github.com/ntwb/stylelint-config-wordpress

Since the sass has never been linted there are probably issues.  This should not be mandatory in the build until those issues can be resolved. Making changes to sass files that offend the linter should be done in separate commits.

I will close my commit in preference to the upcoming PR.

**Comment by sendilkumarn** [comment]
Hi @belcherj sure. I will submit a PR and tag you.
