### ISSUE TITLE
Replace existing checks based on `get_site_specific_features_data()` with `has_feature()` checks once available

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#61499]
With `wpcom_site_has_feature()` in place now, we can start replacing calls to `get_site_specific_features_data()` with it. They are mostly used to gate Videopress and Gutenberg blocks, it looks like.

- [ ] Replace feature check in `class.videopress-gutenberg.php`
- [ ] Replace feature check in `class.jetpack-gutenberg.php`

There seem to be two cases where it's being used to offer the list of supported features:
1. to populate the `features` array in jetpacks option during atomic transfer
2. to create the response for the `https://public-api.wordpress.com/rest/v1/sites/example.wordpress.com/features/` endpoint.

We might have to split those two out into separate issues.

Depends on #61425.

**Comment by mmtr** [comment]
> Replace feature check in `class.videopress-gutenberg.php`

This should be covered by https://github.com/Automattic/jetpack/pull/23189.

> Replace feature check in `class.jetpack-gutenberg.php`

In https://github.com/Automattic/jetpack/pull/23189 we no longer use `get_site_specific_features_data` for the feature check, but we still need the call to `get_site_specific_features_data` since it's also used to determine in which plans are available the given feature and display an upsell nudge with the name of the lowest plan that includes such feature:

https://github.com/Automattic/jetpack/blob/b29bc08144e31119207065c15b313ad3d19e839a/projects/plugins/jetpack/class.jetpack-gutenberg.php#L1128-L1130
