### ISSUE TITLE
Theme Showcase: Entering a search word with hyphen activates the feature filter

### ISSUE THREAD

**Issue by lizswafford** [Automattic/wp-calypso#61544]
### Quick summary

In the Theme Showcase, searching for a theme whose name includes a hyphen triggers a feature filter. 

For example, typing "Twenty Twenty-Two" in the search bar results in the text being changed to "Twenty column:two-columns". 

Also, typing (no hyphen) "Twenty Twenty One" triggers the column filter. The text is changed to "Twenty Twenty feature:one-column". 

 Theme search results include no themes at all, or unrelated themes.

<img width="413" alt="SearchTheme_TwentyTwentyTwo" src="https://user-images.githubusercontent.com/33204818/156024761-4ad99a49-4dd4-482b-8f35-85bbb2445c6f.png">

https://user-images.githubusercontent.com/33204818/156024809-6df75870-c6d2-4ed4-8edc-bdb80255753e.mp4

### Steps to reproduce

1. Go to https://wordpress.com/themes
2. Enter the search term  "Twenty Twenty-Two" in the theme search field.
3. Press enter to run a search for the theme. 
4. Notice that the theme search results are missing, there is a "Sorry, no themes found" message. 
5. Or, notice that the option to choose the feature filter for Two-Columns is offered. 

### What you expected to happen

After searching with the proper theme name, I expect to see the Twenty Twenty-Two theme, and its additional variations, listed in the search results. 

### What actually happened

Searching with the hyphen in the theme name gives no results. 
Searching with the partial name "Twenty Twenty-" does show theme results. 
It's not possible to find the theme with the full name. 

### Context

Found this error when setting up a test site. I started with the theme called Geologist, then tried to switch to Twenty Twenty-Two, but I couldn't find the theme easily in the Theme Showcase by using the search field. 

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Tested searching for the themes: 

Twenty Twenty-One
Twenty Twenty-Two

### Browser, operating system and other notes

Tested on MacOS, desktop. 
FireFox 97.0.1
Chrome  98.0.4758.109

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

The main workaround is to search only using the word "Twenty".

**Comment by jordesign** [comment]
Confirming this behaviour in testing.

**Comment by blackjackkent** [comment]
@mreishus Can you take a look into this, since you took the lead on the search algorithms in the theme showcase previously?

**Comment by mreishus** [comment]
Sure, I've worked in this area and I'm familiar with the search. I definitely agree it is confusing.  There's a couple of things going on:

1. `-` not working in search. Searching for `twenty` brings up results, but `twenty-t` doesn't.

I believe this is due to [the mechanism that strips out special regex characters](https://github.com/Automattic/wp-calypso/blob/0d7d82872a7c37bf07387d2ffa27c9cf53b580ba/client/components/keyed-suggestions/index.jsx#L109) from the search term. It's probably better to escape them instead.

2. Typing `one` (or `abc xyz one` or `twenty twenty one`) then pressing enter changes to `feature:one-column `

This is by design; `one` triggers the spellcorrect/autocomplete for `feature:one-column`. The system doesn't expect people to know to type `feature:one-column` and gives them help along the way. Note that pressing enter accepts the auto-complete, but the search works without pressing enter. (Searching `twenty twenty one` without pressing enter brings the theme up as the first result).

3. Typing `twenty-two` (or `twentytwo`) brings up the autocomplete suggestion for `feature:two-column`.

This one is a bit of a strange coincidence. This is the fuzzy match kicking in because the string `twentytwo` has 2 clues matching the word `two`: It contains the trigram `t` `w` `o` as well as the trigram `<start>` `t` `w`.  Note that `zwentytwo` doesn't match, it's matching because `twentytwo` 1.) contains `two` and 2.) starts with `tw`. These are two strong clues, so it triggers the match. 

I'm not sure what to do here. We could add a special case to the match checking code that stops `twenty-two` or `twentytwo` from matching against `two`. [Link](https://github.com/Automattic/wp-calypso/blob/0d7d82872a7c37bf07387d2ffa27c9cf53b580ba/client/components/keyed-suggestions/index.jsx#L259)

**Comment by blackjackkent** [comment]
@mreishus Thanks for this analysis! Do you have bandwidth to pick up this issue and make the necessary changes?

**Comment by blackjackkent** [comment]
(Talked to Matthew today and he doesn't have much bandwidth alongside limited Atomic stuff, so I will grab this myself.)

**Comment by markbiek** [comment]
I think there are _two_ separate issues happening here.

The first is that typing `two` triggers the `two:column` suggestion. The second is that theme API calls to search for `twentytwo` (or `twenty-two`) aren't returning any results.

**Comment by markbiek** [comment]
Public API issue noted here: #62016

**Comment by markbiek** [comment]
@blackjackkent I feel like Matthew's idea of adding an exception to prevent `twentytwo` from triggering the `two:column` suggestion is the best way to go.

_However_, I wonder if the `two:column` suggestion would seem less weird if we actually got theme results when searching for `twentytwo`/`twenty-two`?

**Comment by blackjackkent** [comment]
@markbiek In other words, you're wondering if fixing the first issue makes the other ones less significant?

I'd say def go ahead and get a PR in for the main hyphen issue and we can get further opinions once that is merged.

**Comment by markbiek** [comment]
@blackjackkent Sorry I wasn't more clear.

There isn't really a hyphen issue, per-se. Typing `two` in any context triggers that `two:column` suggestion.

To me, the larger issue is that you should be getting search results back and you don't (which is the API issue).

That said, I have an idea for preventing the `two:column` suggestion that I'm trying out now.
