### ISSUE TITLE
Reader: new cards start appearing only as you scroll

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#6163]
In Cold Start, one feedback we received was that there was no obvious way to tell if new cards have been appended to the bottom.

When you're at the top of the list, I don't think that providing an indication that new cards are being added to the bottom is necessary. We are aware that these are related recs, but this is transparent to users, especially since the new recs are outside of their current view. This is also more of a discovery phase for them, they don't really know what they're looking for. Our job is to just keep recommending stuff, but it needs to be done subtly. There is no need for some sort of announcement that we are actually doing that.

However:
1. as you scroll, it could take longer for these new recs to show up and there's no clear indication that "we're working on adding new stuff for you". If they don't show up in time, you might think that you've reached the end.
2. if you click on one of the cards at the bottom of the list, then you hit back from full-post view, new cards randomly are just there all of a sudden, which could be disorienting.

To address these, we should make use of the infinite scroll/skeleton placeholder style similar to the mockup below and new cards should start appearing only on scroll. 

This sets an expectation to users that we are adding new stuff for them.

![skeleton](https://cloud.githubusercontent.com/assets/4924246/16210384/82857d84-36f0-11e6-94dd-4cd7e71b3b3e.jpg)

/cc @bluefuton

**Comment by bluefuton** [comment]
Doesn't look like our existing infinite scroll component will help here. @blowery suggests `react-virtualized` instead.

Might be worth thinking of other ways to communicate that new cards have loaded. Various suggestions in Slack have included:
- little header with text “because you followed FooBar"
- highlight the new cards in some way

**Comment by blowery** [comment]
Part of the problem here is that we _may not_ get new recs for a given interaction, so if we naively show the skeletons when we're looking for new recs, there's a decent chance they'll be replaced with nothing. Maybe that's fine, but it feels broken to me.

We could fake it though. When we get new recs to show, show the skeletons for a short bit (maybe 5s?) and then show the posts. We would do this even though we have the posts already available to show, it's just theater to help the user understand that new recs are coming into the UI.

**Comment by jancavan** [comment]
The main purpose here isn't really to communicate that new cards _have_ loaded. It's more of setting an expectation that new cards are _about to be_ loaded in an event where it'll take a while to load them.

@blowery But now I remember you mentioned we won't actually know if we have recs or not until we have them.

> Maybe that's fine, but it feels broken to me.

Right, it's not great. In some cases where there's only a single preloader and the page ends up displaying nothing, it isn't great, but it isn't too bad either. But when there are multiple preloaders and it ends up displaying nothing (e.g. Manage Following), that's when it feels wonky.

> When we get new recs to show, show the skeletons for a short bit (maybe 5s?) and then show the posts.

I think this might defeat the purpose of a preloader since it's supposed to replace the possible lag that might ccur as we're requesting new recs? 

I think if we show just one preloader (then end up displaying either one, multiple, or no cards), it isn't too bad vs showing multiple preloaders.

Thoughts?

**Comment by samouri** [comment]
Is this still relevant?

**Comment by bluefuton** [comment]
We can close this one out now Cold Start has been removed 👍
