### ISSUE TITLE
Marketplace: Add search header

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#61863]
We need to add a search header to the /plugins page. Figma: f84fqtCG4pCnCh2Hq0But5-fi-1164%3A15551

<img width="777" alt="Screen Shot 2022-03-11 at 5 20 02 PM" src="https://user-images.githubusercontent.com/1689238/157980302-4ca35e04-849a-4a45-9477-18ceab6a0348.png">

- [x] Re-use header and search components to add the search.
- [ ] Implement scroll experience. @vinimotaa to confirm if search will stay in fixed breadcrumb header.
- [x] Add "most popular searches". @cpapazoglou Do we have data to use here?

**Comment by cpapazoglou** [comment]
`calypso_plugins_search_results_show` is a track event that has the `search_term` as a prop. This shows the most popular searches. As expected, users are searching for specific plugins rather than categories. Let's collect the data and do a quick analysis of what makes more sense to show there.

**Comment by cpapazoglou** [comment]
>  Implement scroll experience. @vinimotaa to confirm if search will stay in fixed breadcrumb header.

If you mean:
- users scrolls past the BIG search component
- SMALL search component appears in the fixed header 

then I all in and excited 😄. But @vinimotaa is making the call here.

**Comment by vinimotaa** [comment]
Well, I remember in the call we discussed the search bar behavior.  I understood that for the next iteration we wouldn't be able to achieve the search bar transition from top header to being fixed?

Ideally, that is how that should be built; the reason is that we'll have infinite scroll, and because of that, in the future, if you have scrolled deeper enough, and decide to search for something, you would need to scroll all the way up. To avoid that, a sticky search would be needed.

Something like this:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/97929097/158203269-99980157-6c14-452e-83e6-f587d5421c53.png">


If we're capable of bringing that in, that would be my recommendation - so then we enable and encourage users to keep hunting to whatever they are looking for from the search bar.

ps: I just realized that although Google has the pagination approach (which I'm not a big fan of) they also have the fixed search bar.

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/97929097/158202008-dad227e4-032f-4923-8518-b59d846ed978.png">

**Comment by Rolilink** [comment]
@vinimotaa on smaller devices like phone should we also follow the sticky search bar pattern or should we do something different?

**Comment by vinimotaa** [comment]
Hey @Rolilink great question! As a best practice, what I have in mind is to hide the search bar once the user is scrolling the page down, and display it when the user scrolls up.

I suggest we follow this across the marketplace and if possible, ideally across DotCom in the future.

I’m attaching a video with an example.


https://user-images.githubusercontent.com/97929097/159376176-c5687dc7-905d-4bcd-96f0-1197e3ff6d20.MP4

**Comment by Rolilink** [comment]
This one is almost ready just need to add some css for the sticky header to look fine and some mobile styles to be able to create a PR.

While testing the implementation of the sticky search bar found out what seems to be an issue related to this one: https://github.com/Automattic/wp-calypso/issues/62119.

Since I am rendering two search bars (the sticky one and the content one) the value is not matching between them, when I take a look at the component view both are receiving the same props but rendering a different result.

**Comment by cpapazoglou** [comment]
@Rolilink can you link the PR to this issue please?

**Comment by cpapazoglou** [comment]
> Hey @Rolilink great question! As a best practice, what I have in mind is to hide the search bar once the user is scrolling the page down, and display it when the user scrolls up.
> 
> I suggest we follow this across the marketplace and if possible, ideally across DotCom in the future.
> 
> I’m attaching a video with an example.
> 
>  IMG_8914.MP4

@vinimotaa thanks for providing an example. Can we please add all these states in figma? Are there mobile designs? Also, can we gather all Marketplace designs / flows in one place that gets updated? eg oU6nEIeiKSg8CayhEtgR6b-fi-6450%3A38266

**Comment by Rolilink** [comment]
current PR: #62080

**Comment by vinimotaa** [comment]
Hey both @Rolilink @cpapazoglou!

I have just designed the states for the mobile version as well - you can find it on the same Figma file: https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=1164%3A15550

**Comment by cpapazoglou** [comment]
> Hey both @Rolilink @cpapazoglou!
> 
> I have just designed the states for the mobile version as well - you can find it on the same Figma file: f84fqtCG4pCnCh2Hq0But5-fi-1164%3A15550

Thanks @vinimotaa. What about the desktop scroll down state?
