### ISSUE TITLE
Editor: please bring back minimal distraction-free mode?

### ISSUE THREAD

**Issue by tieguy** [Automattic/wp-calypso#6196]
#### Context / Source
Compare the extremely minimal [Wordpress 3.2 distraction-free mode](http://mattrefghi.com/blog/2011/07/distraction-free-writing-in-wordpress-3-2/) to the much-praised [Medium default editing experience](https://camo.githubusercontent.com/278bdd0cc5e1d9cbe156376ca46cd9913f1ab5b6/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3534353433302f313637393739372f37376366396361302d356435632d313165332d383062322d6337373433633739383334382e706e67). Both similar, both with essentially zero buttons visible by default.

Then compare the, um, [less minimal Calypso editing experience](https://en-blog.files.wordpress.com/2015/12/01-writing-with-dock.png). 

I don't know exactly why the minimal mode got so much less minimal in WP 4.x, but it'd be nice to have an actually minimal distraction-free mode in Calypso, comparable to Medium and WP 3.1's.

#simplicity #minimalism

**Comment by designsimply** [comment]
@tieguy, thank you for the suggestion. 

> I don't know exactly why the minimal mode got so much less minimal in WP 4.x

You can find some of the reasons behind those design decisions made in WordPress 4.0 explained in the post and demo video at https://make.wordpress.org/core/2014/11/11/focus-v2-demo-video/ if you're interested.

Regarding the `wp-calypso` editing interface on WordPress.com, it was approached more as a single interface and designed to be as distraction free as possible without adding an additional, separate function for that at the start. It's something that could possibly be added in the future but isn't currently being actively worked on by our team.

Since this is a feature request and not an issue or PR, I am going to close this for now while also noting that it's a good suggestion and the issue can be re-opened, or a PR can be submitted, if someone would like to work on it in the future.

**Comment by aduth** [comment]
It's also worth pointing out that the screenshot you referenced for the WordPress.com editor is outdated. Here's how it appears currently:

![Editor](https://cloud.githubusercontent.com/assets/1779930/16265961/4cdc7be0-3850-11e6-89e8-db61cf2d219f.png)

This redesign was introduced in #2131, increased the editor width from 579px to 700px, and added the effect that the editor is seamless with the background of the page.
