### ISSUE TITLE
Domain is "Domain canceled at registry" but can't be re-registered through "Add new site" flow

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#61970]
### Quick summary

When a recently canceled domain is available to purchase, it is showing up as "unavailable". However, it is available to purchase when you go through other flows such as adding a domain manually, checking via GoDaddy, etc.

https://user-images.githubusercontent.com/83020905/158506113-809d2298-a981-439a-ba63-aca9a5d07ff5.mp4

### Steps to reproduce

1. Need a recently canceled domain (status `Domain canceled at registry`) that is available to purchase
2. Go to "Add site' in dashboard and try to purchase or choose the domain that was recently canceled.
3. It will be unavailable.

### What you expected to happen

The domain should be available through this flow as it is through the other ways to add a domain.

### What actually happened

Domain is unavailable to purchase through the "Add new site" flow.

### Context

4858239-zen

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

None

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Had the user go directly to https://wordpress.com/domains where they can input the domain with an option to create a site from it.

**Comment by formosattic** [comment]
Doesn't look like it'll be an easy one to reproduce, as it'd require a domain that switched to status `Domain canceled at registry` (as in the user's case, 4858239-zd-woothemes). I've updated the title to clarify that.

Will tag this for Domains to check.

**Comment by delputnam** [comment]
I don't think there is really anything we could do about this.

When a domain is canceled at the registry it's not always immediately available and when it starts to become available, there is propagation lag, caching, etc. that determine when it appears to be available for re-registration at various places around the web. In addition to this, we also cache the results of a search query for a short period of time to improve performance of the domain search page.  From what I can tell, the timing of this search was just exactly right so that for a period of time the domain was showing as unavailable.

Please let me know if there's something else I'm missing, but from what I can tell, this is one of those edge cases that we can't really improve, so I'll mark this one as closed.
