### ISSUE TITLE
Marketplace: i18n on plugins search

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#61993]
When searching plugins (free or paid) only the actual name is considered for the search. This name is usually in English.
It would be nice if a user could find the best plugins even searching in their native language.

**Comment by cpapazoglou** [comment]
@gibrown does Jetpack search allow searching in all translated fields?

**Comment by gibrown** [comment]
It depends on how we are storing the translated data. For .org plugins it is stored in post meta and then we index it into separate fields. Jetpack Search doesn't currently pay attention to any translations in post meta, but it fairly easily could since we are doing it elsewhere.

I guess my specific questions would be:
- How are we currently storing translations?
- How are we handling plugins that are not translated?
- Is this about plugins from the .org repo, or about the ones that we are selling in the marketplace?
- Should we store translations in post meta the way that .org is doing (this is ok, but not quite how Jetpack Search currently works), or could we just store the translations as separate posts and then add some filtering by language? The second option has some downsides too.

In general, I'd say that if we can, then we should get it to work for English on the existing Jetpack Search API and then probably plan to fork the api to allow correctly handling translations. 

cc @robfelty @mdbitz

**Comment by gcsecsey** [comment]
Backlog Grooming: Let's discuss this further on our upcoming meetup.

**Comment by gcsecsey** [comment]
Backlog Grooming:
This may be a duplicate issue of this one: https://github.com/Automattic/wp-calypso/issues/63168

We're still working on getting the existing Jetpack Search API to work in English, but we'll definitely look for adding translations later. @gibrown @robfelty @mdbitz based on the above questions, do you think it'd be feasible with the jetpack search index?

**Comment by gibrown** [comment]
FYI, discussing this on p2 a bit. Seems like we're probably at the point of building a separate index.

**Comment by gcsecsey** [comment]
Closing this as redundant with #64571, and that one is more up-to-date.
