### ISSUE TITLE
Pullquote theme default text colors not displaying on live page

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#62078]
### Quick summary

I have a user who has multiple Pullquote Blocks added to a page. The blocks seem to have all the same text color settings but they do not all show a dark color on the live page. Some text is white when it should be black. The text color shows correctly in the editor.
4873464-zen

### Steps to reproduce

1. Select a default text color for the Pullquote Block.
2. In this instance, some Pullquote Blocks on the same page show a white color and others show a black color, despite the same settings.
3. If you try to adjust the color of the dark text that is showing correctly, such as resetting it to the same color it already is (in this case #000), it will then show as white. So, the issue can be created by setting the text to #000 in the color picker or choosing a theme default color for the Pullquote text.

### What you expected to happen

The text color for the Pullquote Block should display the same on the live page as it does in the editor. 

### What actually happened

The color only shows correctly in the editor unless you manually set it to a color slightly different than #000 in the color picker.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

The theme in this instance is Hever and the site is Atomic. I tried to reproduce on an atomic test site using the Hever theme but was unable to replicate the issue.

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Manually select the text color in the color picker by slightly altering it to not match the default theme colors or #000. Such as hex code 030303.

**Comment by rinazrina** [comment]
I got another report here: #4874848-zen

Theme: Alves

The theme color is displaying correctly on the top and bottom borders, but not on the right and left borders. The color was correct on the editor, but not on the live page. 

Slightly altering the color code did the trick.

**Comment by vajrasar** [comment]
Hey @CodeAllNightNDay 👋 Thanks for the bug report. And, thanks @rinazrina for the additional issue on the same block.

While I was not able to replicate the issue shared by @CodeAllNightNDay, and what's specifically shared by @rinazrina - I was able to find another issue related to Pullquotes Block. 

When you select Style and Color attributes for the Border of the block, but do not put any value (keep blank) in Width -- no borders on the Pullquote Block is shown on the editor, but on the site it shows borders on top and bottom (where left + right borders are thinner than the top + bottom borders). But, as soon as you set any Width, the borders behave as expected on editor and the site.

Issue recording: https://d.pr/v/f2H7XD

I checked this on the following themes: Archeo, Skatepark, Hever, and all themes show the issue. This issue could be the indicator that the issue shared by both @CodeAllNightNDay and @rinazrina might also be something happening on edge cases (but not easily replicated). 

Also, @CodeAllNightNDay for better confirmation, you can also check if the issue was still showing with all plugins deactivated.

**Comment by danielbachhuber** [comment]
@vajrasar @rinazrina @CodeAllNightNDay Does this problem still exist? If so, can you share specific steps to reproduce? Screenshots would be very helpful.

I created a test post with a few pullquote blocks. Each had the text and background present:

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/36432/179834879-87150b6f-fb68-4a2c-956f-4bc35a835d5e.png">

However, the pullquote blocks appeared as expected on the frontend:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/36432/179834987-1c2e15fb-6364-4fd8-b692-cb666bc86797.png">

Is there some aspect I'm missing?

Thanks!

**Comment by vykes-mac** [comment]
I'm also unable to reproduce this issue, Everything renders on the site as it is in the editor

**Comment by vykes-mac** [comment]
@CodeAllNightNDay Can you confirm if this issue still exists?

**Comment by danielbachhuber** [comment]
Closing because we can't reproduce. Feel free to re-open with specific reproduction steps + screenshots if it comes up again.
