### ISSUE TITLE
[Bug]: Videomaker screenshot at onboarding theme picker broken

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#62176]
### Quick summary

A small screenshot in theme grid has issues with videos:
- Videos don't show up
- Smaller thumbs even have errors about videos

<img width="639" alt="Screenshot 2022-03-23 at 16 13 20" src="https://user-images.githubusercontent.com/87168/159719739-5267fbd4-b6f7-407c-9e76-6d0a89b830cd.png">
 
If it's not possible to get videos load on mShots easily, perhaps video block should just render as an image when theme is previewed for mshots?

When clicking "preview" it works again:

<img width="1831" alt="image" src="https://user-images.githubusercontent.com/87168/159720150-c881166d-068e-4458-b793-cd15dc0abfc0.png">

Note the difference between header video which has autoplay and other videos which have play icon over them.

@autumnfjeld could Ganon team have this on your maintenance backlog?

### Steps to reproduce

- create new site at /start
- pick "Build" when asked
- at theme picker, find videomaker

### What you expected to happen

Videos show up visually.

### What actually happened

Black boxes and errors.

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by arthur791004** [comment]
Close it as it's fixed by D83169-code and https://github.com/Automattic/wp-calypso/pull/65021 🎉

Here is the current screenshot
<img src="https://s0.wp.com/mshots/v1/https%3A%2F%2Fpublic-api.wordpress.com%2Fwpcom%2Fv2%2Fblock-previews%2Fsite%3Fstylesheet%3Dpremium%252Fvideomaker%26language%3Den%26viewport_height%3D1040%26source_site%3Dpatternboilerplates.wordpress.com%26use_screenshot_overrides%3Dtrue%26site_title%3DVideomaker?vpw=1600&vph=1600&w=1199&screen_height=3600&count=0" />
