### ISSUE TITLE
Navigation Block - Holds focus / selection in empty state

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#62181]
#### Steps to reproduce

1. Add a navigation block in the site editor
2. Select 'start empty'
3. Press the '+' icon
4. Notice the block is stuck in selection and that we cannot select other blocks.

Unable to repro in core.

![Screen Shot 2022-03-23 at 12 36 37 PM](https://user-images.githubusercontent.com/28742426/159750307-0d4b4bd0-e34e-4521-80a8-8fe8e55abdcc.png)

#### What I expected
To be able to select other blocks.

#### What happened instead
Cannot select other blocks.

**Comment by vykes-mac** [comment]
Looking at this a little it seems the issue doesn't happen in core. What I've discovered so far is that

- The method `useEffect` anonymous function is being called multiple times when a navigation block is added.
- This method in turn calls `selectBlock` which highlights the selected navigation block.
- Because this method is called multiple times even when you select another block it's executed again, the selection remain stuck on the navigation block.
- It seems once the navigation block is added any block that is selected the `useEffect` function is still executed, even when the user scroll it's still executed.

This behaviour does not happen in core. The screens below prints to console to illustrate when the `useEffect` method is called.

#### Calypso
![2022-04-25_11-45-37 (1)](https://user-images.githubusercontent.com/47489215/165139446-1db26f97-8050-4c54-b8bd-73e5e7a2494a.gif)

#### Core
![2022-04-25_11-57-04 (1)](https://user-images.githubusercontent.com/47489215/165139564-85960ba6-908f-4628-a6c2-81cce43125f0.gif)

gutenberg filepath: `packages/block-library/src/navigation/edit/index.js:187`

**Comment by Addison-Stavlo** [comment]
This process has been updated and I can no longer trigger this focus trap.
