### ISSUE TITLE
Marketplace: Find a way to make Plugins landing page look like having fresh content

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#62205]
Related to https://github.com/Automattic/wp-calypso/issues/62202

> @vinimotaa, @SaxonF I can understand that these results might have added something fresh to our landing page. I would like us to try something different for showing that this page is constantly updated. Some ideas are the following:

> - Spotlight -> rotating top X uninstalled plugins (probably premium)
> - Plugin Lists (premium, featured, popular) -> Show only uninstalled plugins. In the Browse All page we can show both installed and uninstalled

**Comment by gcsecsey** [comment]
@SaxonF what do you think about only showing uninstalled plugins in the spotlight/search results?

**Comment by SaxonF** [comment]
I think it makes sense to show only uninstalled when on the home page but show all when searching/browsing.

**Comment by cpapazoglou** [comment]
Thanks @SaxonF , we will start by filtering out installed plugins from the Top Paid Plugins homepage section.

**Comment by WBerredo** [comment]
On #63689 the filtering out was made only on the landing page, so it wouldn't be reflected when clicking on **Browse all**.

| Landing page  | Top Paid plugins (after click on Browse all) |
| ------------- | ------------- |
|<img width="985" alt="Screen Shot 2022-05-16 at 16 37 39" src="https://user-images.githubusercontent.com/5039531/168680517-aa7434af-93ca-41ef-8a50-94c20e34093a.png">|<img width="985" alt="Screen Shot 2022-05-16 at 16 37 55" src="https://user-images.githubusercontent.com/5039531/168680624-f4070376-e5d7-4252-87fa-2af4f7a8b158.png">|



I would like to discuss whether or not this is the expected behavior.

**Comment by cpapazoglou** [comment]
Yes indeed. The landing page should have fresh content, it's meant for users to discover new plugins. Installed plugins are not new per se. On the other hand the **Browse All** sections should include all plugins, this is the source of truth.
