### ISSUE TITLE
Marketplace: Add a11n check to spotlight rules

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#62231]
To be able to launch plugin spotlight rules separately, we need to add checks to the Yoast and Sensei Pro spotlight rules, we decided to go ahead and add a11n checks to both rules which will be removed separately when each plugin is launched

- [ ] Add a11n check to Yoast Premium rules.
- [ ] Add a11n check to Sensei Pro rules.

**Comment by lsl** [comment]
Doing this in D77801-code but take note of my comment: D77801-code#1616810 as is_a11n checks don't work for atomic.

Not a real blocker imo, the goal here seems to be to remove front end feature flags and "deploy" the feature even though nothing is showing, I think that's a good idea, they'll still show in testing for simple sites so that's good enough imo.
