### ISSUE TITLE
Full site editing: Unable to view a page template if the page is marked as a blog archive

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#62288]
### Quick summary

When a page is marked as blog archive, there's no way to open that page's editor view to view the applied template. It's possible only after un-setting the page as blog archive on the Customizer.

### Steps to reproduce

- Create a page and publish it. **Don't close the editor view of this page**
- Mark that page as the blog archive on the Customizer.
- Refresh the editor view of the page, see that the template changed from "Page" to "Home" (related report: https://github.com/Automattic/wp-calypso/issues/62287)
- Try to open the page editor from the pages list now, on a new tab. 

### What you expected to happen

There's an option to open the editor view of a page once it's marked as a blog archive.

### What actually happened

- The only option on the pages list is to view the blog archive on the live site. There's no editor view. 
- This makes it impossible to identify what template is applied to the blog archive page. It's necessary to un-set the page from being the blog archive first, in order to open the editor view.

### Context

Customer report on 4885219-zen.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No, I believe it applies to all but I have tested only with core theme Twenty Twenty-Two.

### Browser, operating system and other notes

Not applicable.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

**Comment by arunsathiya** [comment]
Interestingly, this does not happen on WordPress.org: I can access the editor view of a blog archive page fine.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/18581859/160286833-268d0d07-a739-42a6-9df6-cd1a32e43914.png">


It's only on WordPress.com where I cannot open the editor view:

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/18581859/160286861-753a4c64-d629-496b-b543-0021cb4c6a6f.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/18581859/160286869-84e9efd1-4d80-4cfb-bdaa-e11e3ce98a53.png">

**Comment by arunsathiya** [comment]
- Found when reporting this issue: https://github.com/Automattic/wp-calypso/issues/62287

**Comment by arunsathiya** [comment]
Interestingly, this does not happen on WordPress.org: I can access the editor view of a blog archive page fine.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/18581859/160286833-268d0d07-a739-42a6-9df6-cd1a32e43914.png">


It's only on WordPress.com where I cannot open the editor view:

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/18581859/160286861-753a4c64-d629-496b-b543-0021cb4c6a6f.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/18581859/160286869-84e9efd1-4d80-4cfb-bdaa-e11e3ce98a53.png">

**Comment by vajrasar** [comment]
Hi @arunsathiya 👋 Thanks for the detailed report. 

I checked and I can confirm the issue on .com (Simple + AT sites) where you do not get the option to edit the "Blog" page (set as the Posts Page) on the Page Editor, and also you do not have any way to edit the Blog page template via Site Editor.

While on non .com sites you get the option to edit the "Blog" page, the changes you make are not visible. Hence, it does not make any difference if the editing is available. But, same like .com you do not have any way to make changes to the Blog page template using Site Editor even on non .com site.

Both of the above cases are true when the "Blog" page is set as the Posts Page of the site.

The workaround is to unset the "Blog" page from the Posts Page, select Static Posts page, move to Site Edito, make changes on the Home template, and then go ahead and set "Blog" page as the Posts page again. The changes you made o the Home template will reflect on the Blog page now.

**Comment by vajrasar** [comment]
cc: @Automattic/cylon

**Comment by Addison-Stavlo** [comment]
> moved this from Inbox to Cylon - FSE in [Dotcom Bug Prioritization](https://github.com/orgs/Automattic/projects/343#card-80963823) [13 days ago](https://github.com/Automattic/wp-calypso/issues/62288#event-6474265120)

Agreed this is problematic. However we probably wont be able to get to this soon due to the prioritization of other FSE issues and the impact this causes as we focus users towards FSE.

**Comment by creativecoder** [comment]
This one is very hard to fix... even if we added links to "Edit" the Home and/or Posts page from the page list, typically you would see empty post_content in the editor, because the content for those pages primarily comes from templates. Opening an empty homepage in the editor is quite confusing!

Ultimately, we're dependent on Gutenberg/Core to improve the in editor content preview for these special pages. For now I think the best workaround is to select and edit the template from the site editor:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1699996/166733583-21e9ec57-01d2-429a-9527-1c26e8c464f8.png">

**Comment by cuemarie** [comment]
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Normal` to better reflect its status in the larger context of open bugs in this repo.
- I also quickly retested on a new free site (Themes `Fewer` and `TT3`), and I'm not sure this issue is still occurring:

https://github.com/Automattic/wp-calypso/assets/27249804/d5a53360-bca7-41f0-92d3-aec9c1e00ce3

@creativecoder do you agree?

**Comment by gikaragia** [comment]
Did some testing and investigation around this and it seems that this is expected behavior.

The posts page is supposed to be defined by the theme itself so users do not make sense to edit this page. If we allow editing in such a page, there is a warning that says 'You are currently editing the page that shows your latest posts.' on top and any changes will not appear anywhere. There is more information about [this here](https://wordpress.com/support/posts-page/) and [this is the issue ](https://github.com/Automattic/wp-calypso/pull/8863) that removed these links in the first place.
