### ISSUE TITLE
Hide "Blank Canvas" from site creation design picker.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#62384]
What:

* Hide 'Blank Canvas' from the design picker in onboarding.

This should NOT change:

* The "start from scratch" flow that triggers blank canvas should be left in place.
* 'Bank Canvas' should remain in the theme showcase.

Why:
pdqkMK-d7-p2#comment-214 for history.

**Comment by jeyip** [comment]
> The "start from scratch" flow that triggers blank canvas should be left in place.

It appears that the "start from scratch" flow scaffolds a website with `zoologist` as the default theme instead of `blank-canvas`. Here's what I did:

**Logged in user**
- Clicked on the "ADD NEW SITE" button from the calypso admin menu sidebar
- Stepped through onboarding
- Clicked on the "Start from scratch" hyperlink

**Logged out user**
- Logged out of wordpress.com
- Navigated back to wordpress.com as a logged out user
- Clicked on the "Start your website" button
- Created a new user
- Stepped through onboarding
- Clicked on the "Start from scratch" hyperlink

I'll create a separate issue that we can address if you're seeing the same thing @Addison-Stavlo.

cc @vykes-mac

**Comment by jeyip** [comment]
@vykes-mac It looks like the blank-canvas theme is only applied when clicking on the "Use a blank theme" button in the design picker screen.

<img width="1270" alt="Screen Shot 2022-03-30 at 11 51 17 AM" src="https://user-images.githubusercontent.com/5414230/160909386-9d99f8d1-0a41-4b30-9032-475fdde4133a.png">

We can remove references to this component from the design picker view `packages/design-picker/src/components/featured-picks-buttons/index.tsx`

You can test the onboarding flow in your local env by:
- Navigating to calypso in a terminal
- Running `yarn` to install npm packages
- Running `yarn start` to spin up the calypso local dev environment
- Following instructions left in this comment to test changes ( [link](https://github.com/Automattic/wp-calypso/issues/62384#issuecomment-1083445262) )

**Comment by Addison-Stavlo** [comment]
> It appears that the "start from scratch" flow scaffolds a website with zoologist

Oh wow, good find!

> I'll create a separate issue that we can address if you're seeing the same thing

I see the same thing happen. We may actually want to leave it that way for the time being 🤔  cc @simison

**Comment by simison** [comment]
> It appears that the "start from scratch" flow scaffolds a website with zoologist

Oh, Zoologist! Why? :-D It looked sooo much like blank when in editor.

@ianstewart  do you know if Zoologist was a choice or an oversight? Any concerns switching it to Blank?

**Comment by Addison-Stavlo** [comment]
pdqkMK-d7-p2#comment-220 cc @simison  it sounds like the switch to Zoologist for that flow was known and possibly forgotten about?

**Comment by Addison-Stavlo** [comment]
closing with https://github.com/Automattic/wp-calypso/pull/62427 - will open a [separate issue to follow up regarding these featured buttons.](https://github.com/Automattic/wp-calypso/issues/62566)
