### ISSUE TITLE
Pro: Upgrade nudge on the media library of a free plan site says "Premium plan"

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#62430]
### Quick summary

On a free plan (doesn't matter if it's created before the Pro plan launch today, or the newer version) site, the media library has an upgrade nudge that says "Premium plan" instead of the "Pro plan"

### Steps to reproduce

- Start with a free plan site.
- Click on its media library and view the wp-admin version.

### What you expected to happen

Upgrade nudge says "Pro plan"

### What actually happened

Upgrade nudge says "Premium plan"

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/18581859/161107460-452735f1-4702-4e40-99b5-28a4bee958c3.png">

### Reproducibility

Consistent

**Comment by sixhours** [comment]
Fix in D78222-code

**Comment by sixhours** [comment]
Fixed in r243190-wpcom

**Comment by southp** [comment]
Reopen since there was some unfixed cased identified. It is now working in code-D78635

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on P2 - No 
- Tested on Simple-  ✅  Yes
- Tested on AT ✅- No
- Tested on Self-hosted - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context - Issue appears fixed on my Free test site. Not able to replicate 
- Uploaded file (if needed)
<img width="857" alt="Markup 2022-05-10 at 08 23 35" src="https://user-images.githubusercontent.com/83325600/167638819-cec4f969-2e5a-4367-93dd-15fafe71bc36.png">


📌 ACTIONS

- Marked as Triaged for Quality Squad review as this was reopened due to unfixed cases - Serenity Expand Group seems to be working on this at the moment 
https://github.com/Automattic/wp-calypso/issues/62430#issuecomment-1114468587

**Comment by DavidRothstein** [comment]
@nbloomf was working on the remaining followup for this and was assigned on the old Trello board -- I'm adding this to the Shilling GitHub board now too (since the Trello board isn't being used anymore) and assigning him here.

As noted above, the remaining work is at D78635-code and is almost ready to go but not quite.

**Comment by DavidRothstein** [comment]
Also, to clarify (since it was only mentioned in Trello), the remaining work here is the following, copying over from my comment there:

>It looks like it's actually half-fixed -- there are other upgrade messages that kick in when you're closer to your upload limit, and those still upsell the legacy plans.
>
>For example:

![Screenshot_from_2022-04-11_21-44-38](https://user-images.githubusercontent.com/235183/167666816-9bcbe931-45c0-4ce9-a276-f1663f264e15.png)

**Comment by southp** [comment]
I'm deprioritizing from the Plan Overhaul board so our Current Phase view can focus on the high priority issue of the phase 2 launch.

**Comment by DavidRothstein** [comment]
It's possible the remaining issues here were fixed as a side effect of https://github.com/Automattic/wp-calypso/issues/60433, but it needs some testing.

**Comment by valterlorran** [comment]
I tested it, and it's working correctly. I'll close this issue.
