### ISSUE TITLE
Push Notifications: Chrome v49 doesn't display notifications

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#6243]
#### Steps to reproduce
1. Running Chrome v49 for either Linux/OSX/Windows (obtained [here](http://www.slimjet.com/chrome/google-chrome-old-version.php))
2. Enable desktop notifications at https://wordpress.com/me/notifications
3. Spawn a new notification

#### What I expected
To receive a desktop popup

#### What happened instead
Nothing but the badge on the notification icon

#### Browser / OS version
Linux / OSX / Windows Chrome v49

#### Context / Source
#manual-testing

**Comment by mjuhasz** [comment]
Chrome versions 40-49 support web push notifications, but with a reduced feature set (in particular, these versions do not support encryption).

Our feature detection shows the browser as supporting web push but because of the missing encryption functionality, sending notifications fails.

Chrome 49 is not supported by the vendor anymore, and it is not covered by the Calypso support policy either: at the moment, the latest two versions of Chrome are v51 and v50, they both work with our implementation.

Nevertheless we are planning to improve the experience for those on obsolete Chrome versions.
