### ISSUE TITLE
Anchor.fm - Implement onboarding state management logic in Stepper framework

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#62668]
As part of migrating Anchor.fm onboarding to the stepper framework, following on from https://github.com/Automattic/wp-calypso/issues/62666, implement any needed state management logic to carry all necessary site/user info from end to end in the flow.

**Comment by sixhours** [comment]
Data to carry through the flow ([gleaned from existing Gutenboarding hook](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/gutenboarding/hooks/use-on-signup.ts)):

* Site title (may be pre-populated by the Anchor.fm podcast title, fetched from API when the `anchor_podcast` query is used with a valid podcast ID)
* Anchor.fm podcast ID (required, passed via query param `anchor_podcast`)
* Anchor.fm episode ID (optional, specify an episode to fetch data to populate a post corresponding to the episode)
* Spotify URL (optional)

We also need a method of checking for an existing podcast ID and adding a new episode to that site based on the `anchor_episode_id`: https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/gutenboarding/hooks/use-detect-matching-anchor-site.ts

**Comment by sixhours** [comment]
Hrm, something that just occurred to me as I was looking at this. Unlike the onboarding flow, this flow needs to handle site creation, too; we won't have a ready-made site when someone lands on the first step of the flow. right now we're passing in a `siteSlug` parameter but that won't exist when someone clicks on the link from Anchor.

When would be the better place to handle site creation? Upon submission of the title step, or at the end of the flow after the design step? 🤔 

I feel like since the design step acts on the expectation of a site having been created, we should probably create one at the title step, or as soon as possible in the flow.

**Comment by blackjackkent** [comment]
> When would be the better place to handle site creation? Upon submission of the title step, or at the end of the flow after the design step? 🤔

Good question. 🤔 How are we addressing this in the existing Gutenboarding code?

**Comment by sixhours** [comment]
This has been implemented for all the Anchor-related params in #63211
