### ISSUE TITLE
potential bug with byrne theme

### ISSUE THREAD

**Issue by ckmccoy2** [Automattic/wp-calypso#62673]
### Quick summary

With all plugins disabled, seeing the fatal error `Uncaught Error: Class 'WP_Theme_JSON_Resolver_Gutenberg' not found in /wordpress/themes/premium/blockbase-premium/inc/social-navigation.php:47` when Byrne theme is activated, but not when another default theme (like twenty twenty)

### Steps to reproduce

1. On the site [nigellaeatseverything.com](https://nigellaeatseverything.com/), the above error occurs when byrne theme is active with all plugins disabled, but not if twenty twenty is

### What you expected to happen

For no fatal error to occur

### What actually happened

above fatal error occurs

### Context

34999864-hc

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Byrne

### Browser, operating system and other notes

CLI error message: PHP Fatal error:  Uncaught Error: Class 'WP_Theme_JSON_Resolver_Gutenberg' not found in /wordpress/themes/premium/blockbase-premium/inc/social-navigation.php:47

I tried reproducing this on my test site, but wasn't able to do

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Use a different theme

**Comment by vajrasar** [comment]
Hi @ckmccoy2 thanks for the report. 

I tried to follow the steps shared on my test AT site with only Akismet and JP active with the Byrne theme and I do not see any error.

Since the error is related to Social Navigation, I also added a Social Icons menu to the site, and still, I do not see any error message.

If you can replicate the issue again please feel free to reopen this.
