### ISSUE TITLE
Purchases: Use the correct site address in the URL 

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#627]
The manage purchase view always uses the *.wordpress.com site name in the url. It should be the primary domain as elsewhere in Calypso.

This was initially done in the REST API, but it caused issues with domain renewals in Jetpack sites. See r127299-wpcom.

**Comment by umurkontaci** [comment]
This will be fixed with #536.

**Comment by drewblaisdell** [comment]
This will be fixed soon in #536, but just so this information is stored on the issue instead of a PR: we should mirror the rest of Calypso by using the site slug as determined by `SitesList` instead of the primary domain, to handle [this case](https://github.com/Automattic/wp-calypso/pull/536#issuecomment-159700772).

**Comment by drewblaisdell** [comment]
This was fixed by #536 and #1147.
