### ISSUE TITLE
Feature Request: improved social media preview for unlaunched site

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#62773]
### What

When a new site is created, isn't launched, and is coming soon, the social preview is blank:

[FB linter example](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fcardiiiiiiiiiioe11.wordpress.com%2F):

<img width="791" alt="image" src="https://user-images.githubusercontent.com/87168/163396462-ccfa3d9e-8802-4d21-8110-8817e0cda28d.png">

When it's an existing site with social preview details, but has coming soon landing page up, it shows the sites social preview details.

It'd be great to improve this where:
- If person has a coming soon site that doesn't have social preview details set up, we should have a default preview for all coming soon sites.
- If a site has social preview details set up, and still has coming soon up, their social preview details should override our defaults.

Bonus: how can we ensure FB/Twitter etc cache clears out as soon as site becomes public?

We need a default OG image, could be something newly designed or the WP.com default one:

<img width="572" alt="Screenshot 2022-04-14 at 16 06 02" src="https://user-images.githubusercontent.com/87168/163397041-dcebe7f9-7369-4285-8c2f-beda4ebc65cb.png">

### Why

Even the default state of the site should always be exciting and impressive, and stand out when shared to social media.

**Comment by TimBroddin** [comment]
Changes would need to be made here: https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/coming-soon/fallback-coming-soon-page.php

### Quick spiking of this issue

Facebook shows the first `og:image` tag it encounters as the default, for `og:title` & `og:description` tags this is the other way around (the last encountered tag is shown)<sup>1</sup>. Because of this behavior, we cannot simply insert our default tags before/after the call to `wp_head` but we'll have to output buffer wp_head, see if the relevant tags (`og:title`, `og:description`, `og:image`) are already present, and add the default ones for those tags missing. 

Since OpenGraph tags can be added through a variety of ways (Jetpack, SEO plugins, ...) there's no one place where this data is stored, so this seems like the best approach to me. 

An alternative would be to hook into the `jetpack_open_graph_tags` filter, but I did a quick check and Jetpack's OpenGraph output is disabled by Yoast (and probably all other SEO plugins).

<sup>1</sup> Based on this testing: [JSBin](https://jsbin.com/ravofufohi/1/edit?html,output) / [OpenGraph debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Foutput.jsbin.com%2Fravofufohi)

### Next steps
@simison what copy and image should be used for sites that don't already have OpenGraph tags?

**Comment by simison** [comment]
I think you should implement this in Jetpack, and it's fine if those get overridden by dedicated SEO plugins like Yoast. It'll just provide decent out-of-the-box experience for .com customers across simple and Atomic.

`og:description` Copy I believe is fine already?

But the `og:image` is missing. You can either copy the one from WordPress.com or check with designers if they'd wanna come up with a new generic one.

**Comment by TimBroddin** [comment]
Thanks for the feedback. I'll implement it in Jetpack!

**Comment by TimBroddin** [comment]
Created a PR: https://github.com/Automattic/wp-calypso/pull/70474
