### ISSUE TITLE
Themes: Update notification is not actionable unless in WP Admin view

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#62822]
### Quick summary

If there is a theme update, Theme menu item on the left sidebar will show a related notification like ⓵

<img width="272" alt="Screenshot 2022-04-15 at 16 14 10" src="https://user-images.githubusercontent.com/39308239/163574954-bbbb9480-468b-4fb5-acb6-77563189b4e0.png">

It's not clear how to clear that notification from Themes section unless you switch to the Classic (WP Admin) view

https://user-images.githubusercontent.com/39308239/163576242-86e6d7c3-bfa9-488d-bb47-355efe72c1b9.mov

 

### Steps to reproduce

1. On AT site install an outdated theme (for example Storefront https://downloads.wordpress.org/theme/storefront.4.0.0.zip)
2. Visit https://wordpress.com/themes and see the update notification like ⓵ on the left

### What you expected to happen

See which theme needs to be updated

### What actually happened

I don't see which theme needs to be updated

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.3 with Google Chrome Version 100.0.4896.127 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

- Switch to [WP Admin Dashboard](https://wordpress.com/en/support/dashboard/) view
- Visit My Home > Updates at `SITE_URL/wp-admin/update-core.php`

**Comment by Robertght** [comment]
Thank you for reporting this @zdenys! @Automattic/serenity is this something that could be done from your side of things?

**Comment by blackjackkent** [comment]
Yep! Will pull this into our board for next sprint.

**Comment by valterlorran** [comment]
I noticed that the menu is being generated inside the site's VM. Which uses `get_site_transient( 'update_themes' )` to get the information on how many themes need to be updated. However, the information used to render the list of themes on the themes pages is fetched from the `Public API`, and we can't use `get_site_transient( 'update_themes' )`in the multi-site infrastructure.

The information used to set the transient site data is fetched from the `wp_update_themes` function. We could create a new function based on it that would cache the information for the multi-site infrastructure. On my tests, it worked. My only concern is that it would make the themes' endpoint heavier since this function needs to make an external HTTP call.

**Comment by andres-blanco** [comment]
I think that we should try first to find out how the current notification is making its way from the Atomic site to the Calypso UI and see if we can add the theme-to-update-id there.
