### ISSUE TITLE
Marketplace: Categories page with no selected site feel slow / unresponsive.

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#62912]
When navigating to a [category page with no selected site](https://wordpress.com/plugins/popular ) on a user with many sites, the UI freezes / feels slow and CPU is at 100%. Let's research why this is happening and fix this. I found this one on an account with 40+ sites.

p1650466334044759-slack-CKZHG0QCR

## Acceptance Criteria
- [x] Visiting `/plugins` or `plugins/:plugin` should open the site selector.
- [ ] Maybe inform Happiness to be able to track user complaining for the feature.

**Comment by allilevine** [comment]
I'm seeing this on /plugins as well.

**Comment by allilevine** [comment]
So far it seems like some API requests get held up or fail, like `/rest/v1.1/sites/{id}/plugins/jetpack-dev%2Fjetpack/update`

**Comment by lsl** [comment]
Not able to repro on chrome or firefox. Any other hints? My test user has >200 sites for ref though most are not atomic.

**Comment by allilevine** [comment]
> Not able to repro on chrome or firefox. Any other hints? My test user has >200 sites for ref though most are not atomic.

I've been seeing it in Firefox, just by going to /plugins. 🤔

**Comment by allilevine** [comment]
Timebox investigation - 1 hour, check if it's caused by having too many Atomic sites.

**Comment by lsl** [comment]
I'm guessing it is just the number of atomic sites, we probably make Jetpack requests to each site to check current active plugins. That would be slow in a loop.

For scope, the /plugins (no site) route sees basically no traffic, probably only us testing:

![Screenshot 2022-04-26 at 09-06-41 Funnel Browse All Page Views](https://user-images.githubusercontent.com/811776/165188878-c9629b95-701d-4d6d-9540-6a8defa45e47.png)

Maybe, as part of https://github.com/Automattic/wp-calypso/issues/62935 we should just disable the /plugins (no-site) route and display a site selector instead? (This is a common wpcom pattern, we have a thing we can plug in to the page router to intercept and load this)

We could also strip out all the "plugin is active with 3 sites" state checking from the browser in this view requiring a site selection to show this information.

Since it is actually kind of confusing to land on /plugins because you don't really realise you need to select a site to get the proper view, can I suggest for now we just remove the /plugins (no-site) route as part of https://github.com/Automattic/wp-calypso/issues/62935 and display a site selector? 

I think later we want to show a logged out view of /plugins (no site) but I think we can add that in again later quite easy as we won't need to be concerned about active plugins etc and it will just be a matter of disabling logged in features like plugin install/active state.

This will also reduce the number of contexts we need to test for changes to the PluginsBrowser:
- ~/plugins~
- /plugins/:site (simple, atomic, jetpack)
- ~/plugins/:category~
- /plugins/:category/:site (simple, atomic, jetpack)
- ~/plugins/:plugin~
- /plugins/:plugin/:site (simple, atomic, jetpack)


@cpapazoglou / @SaxonF

**Comment by cpapazoglou** [comment]
I don't have strong feelings for the logged-in `/plugins` page. The added benefit it has is that site administrators can manage (install, activate, deactivate) a single plugin in all their connected sites. And the "install" part only works for free plugins, since premium plugins will require a distinct purchase flow for each of their sites.

I would agree, adding the site selector step to the `/plugins` path.

**Comment by lsl** [comment]
> The added benefit it has is that site administrators can manage (install, activate, deactivate) a single plugin in all their connected sites. And the "install" part only works for free plugins, since premium plugins will require a distinct purchase flow for each of their sites.

Is there a way to find out how many people leverage this? I would rather not take something useful away from people if we can help it, even if this code is very hard to maintain going forward.

I was wondering if we could, as an alternative, split the code base a bit and run with a bunch of duplication. That approach would lock in `/plugins (nosite)` pretty much as is but let us iterate on a new plugins browser in isolation. (as part of https://github.com/Automattic/wp-calypso/issues/62935) - not an idea solution with a lot of caveats and I think I still prefer a site selector for the vast majority of users that might hit this page logged in from e.g. a support page linking to /plugins without the site selected.

... Another idea, move ahead to remove, if there is considerable user need we can bring the functionality back under `/plugins/all-sites` or something like that after we've cleaned up the current plugins browser code.

**Comment by lsl** [comment]
I think I saw this today, wild speculation, don't quote me:

Looked like a problem with infinite scroll (or at least the code that loads search results) or the wordpress.org api responses themselves.

Search requests were spamming the network log in one instance and in another the page just locked up (probably making requests).

Could it be something like the request is slow so calypso re-tries before .org has a chance to cache the result? (I think there is some caching that goes on for search queries).

I was using a french locale test user and I'm wondering if using obscure search requests might be enough to trigger it more consistently?

**Comment by Rolilink** [comment]
> Is there a way to find out how many people leverage this? I would rather not take something useful away from people if we can help it, even if this code is very hard to maintain going forward.

Doing some queries against the tracks database maybe! Querying users that have triggered the `calypso_plugin_install_click_from_sites_list ` and doing a unique count through users ids? we will have to check if they are non a11n.

**Comment by Rolilink** [comment]
> I don't have strong feelings for the logged-in /plugins page. The added benefit it has is that site administrators can manage (install, activate, deactivate) a single plugin in all their connected sites. And the "install" part only works for free plugins, since premium plugins will require a distinct purchase flow for each of their sites.

There is some usage in production:

![Screen Shot 2022-04-27 at 1 00 45 PM](https://user-images.githubusercontent.com/1035546/165590435-494a1cf8-58c9-45a1-bd9b-4dc420afc674.png).

I also don't have any strong feeling agains't  removing it and adding it! still gonna time-box some research to check out why this is happening

**Comment by lsl** [comment]
I'm going to guess this can be a proxy for how few people use the multi-site capability to deactivate/activate plugins across sites. Lets drop the route for now and bring it back as required once the implementation is in better shape.

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/pull/63161

**Comment by lsl** [comment]
5203059-zd-woothemes p1652188664973559-slack-C029JEQRVRT

User report of not being able to update multiple plugins at once via Jetpack.
