### ISSUE TITLE
[Bug]: Purchase detail page not loading when accessed directly under certain conditions

### ISSUE THREAD

**Issue by danielmx-dev** [Automattic/wp-calypso#62959]
### Quick summary

If you have purchases on multiple sites, there may be times when the purchase detail page for certain sites won't load when accessed directly through the direct URL (which is usually provided in email receipts and pre-renewal reminders). Instead of loading the detail page, the browser will redirect you to the list of all purchases page.

This only happens when using a direct URL, if you click on the purchase from the list it will load properly no matter which site it belongs to.

### Steps to reproduce

Pre-requisite. Have a site A with purchase X, and site B with purchase Y in the same account.
1.  Visit site A
2. Go to https://wordpress.com/me/purchases
3. Open the detail page of purchase Y and copy the URL.
4. Open the copied URL in a different tab.

You can also reproduce the issue the other way around:
1.  Visit site B
2. Go to https://wordpress.com/me/purchases
3. Open the detail page of purchase X and copy the URL.
4. Open the copied URL in a different tab.

### What you expected to happen

The purchase detail page for purchase Y should be displayed.

### What actually happened

The browser redirects you to the list of all purchases page.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by sirbrillig** [comment]
I bet this is where the redirect happens: 

https://github.com/Automattic/wp-calypso/blob/7c3e055e3fe7920543d18f4e0e0fe51f0f978774/client/me/purchases/manage-purchase/index.jsx#L158

That occurs if the purchase is invalid, and you mentioned in Slack that you saw an API request to the wrong site for the purchase, so that would make sense. I do see that the `ManagePurchase` component uses `getSelectedSiteId` before defaulting to the purchase's site ID:

https://github.com/Automattic/wp-calypso/blob/7c3e055e3fe7920543d18f4e0e0fe51f0f978774/client/me/purchases/manage-purchase/index.jsx#L947

I'm not sure if that's what triggers the API request to the wrong site, but it could be. Maybe something changed where the account-level pages used to not have a selected site ID but now it persists from site-level pages. If we're lucky we may just need to alter that one line but we may need to look for other places that might use the selected site on that page.

**Comment by sirbrillig** [comment]
https://github.com/Automattic/wp-calypso/pull/62963 seems to fix it but I want to experiment more because I'm not sure why it was that way in the first place.

**Comment by sirbrillig** [comment]
> This only happens when using a direct URL, if you click on the purchase from the list it will load properly no matter which site it belongs to.

True, but it turns out that some of its information may still be incorrect because much of it is based on the `siteId` prop so this is even more important to fix.

**Comment by sirbrillig** [comment]
I think I grok it now. https://github.com/Automattic/wp-calypso/pull/62963 should resolve the issue.

Basically, when we reach the purchase page we only have a purchase ID, so we need to load a list of purchases to get the rest of the purchase data to display. There's no single purchase API endpoint so originally the page did this by loading all the user's purchases, but this could be very slow for users with many sites. https://github.com/Automattic/wp-calypso/pull/47427 improved the situation by allowing us to query just the site-level purchases if we're loading in a site-level context.

The problem is that this was done implicitly rather than explicitly. The above PR (and I suspect a lot of other code) assumes that outside of a site-level context, there is no currently selected site saved in the redux store. This is incorrect. As a result, there are two problems. 

First, the page bases all its operations on the selected site ID, which can cause numerous bugs like the one reported here in an account-level context. 

Second, even if the above issue is fixed, when the purchase page first loads, it does not have a site ID (it gets that from the purchase which requires querying the purchases endpoint, or from the selected site if we are in a site-level context) and so what it should do is load purchases and _then wait_ before doing any other operations that rely on the site ID until we have it. Otherwise we risk making more incorrect assumptions about what site we should be using (as we do in `ProductPlanOverlapNotices` which assumes that if the site ID isn't provided, we should default to the selected site).

The solution, I think, is to explicitly state when we are in a site-level or account-level context, and to wait for the site ID to be available from the appropriate source before doing anything with it.
