### ISSUE TITLE
[E-mails] Empty list items for "Great content you might have missed" when post/page with no title included

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#62995]
### Quick summary

When subscribing to a new blog, the confirmation email does not show `Great content you might have missed` area.

![CleanShot 2022-04-24 at 15 04 13](https://user-images.githubusercontent.com/84539773/164978519-e9d37e97-cc2f-45e0-b97d-e9671fcb3afa.jpeg)

### Steps to reproduce

1. subscribe to a new blog that has posts already
2. email shows incorrectly

### What you expected to happen

for the links to show up

### What actually happened

links didn't show up.

### Simple, Atomic or both?

Atomic

**Comment by yansern** [comment]
From the screenshot, the list of post is missing but the section exists or?

**Comment by csabarakasz** [comment]
Thank you for the clarification question, @yansern ! Yes, the list of posts is missing even though there are other posts on the site: https://csabarakasz.wpcomstaging.com/blog

(This is a test site only.)

**Comment by formosattic** [comment]
Strange, I tested by subscribing to a Simple, Atomic site, but the list of posts shows ok.

| Simple  | Atomic |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/165266398-40699f35-bb19-4b12-86f2-9846283282d9.png)  | ![image2](https://user-images.githubusercontent.com/15944096/165266414-e9de4bb7-2189-4d8a-a19f-5ccced3a38f6.png)  |


Yet, when I subscribed to https://csabarakasz.wpcomstaging.com/blog , it shows missing posts, but it appears that it's because those post are untitled, so a case to be handled more gracefully.
Can you confirm those posts are untitled @csabarakasz? 

![image1](https://user-images.githubusercontent.com/15944096/165265896-218afefa-dda9-4c01-8749-d27ae16cb1b4.png)

Related: https://github.com/Automattic/jetpack/issues/24036

**Comment by csabarakasz** [comment]
@formosattic Thank you for your reply and research. I can confirm that 372-2 was untitled. This might be the reason. 

I am not sure what happened with the other Title because it seems to be pointing to root, so maybe the Home page, which did have a title. 

I have a title to all my posts/ pages, test subscribed again and the issue still persisted, but that might be because of site cache. 

Also, I noticed that all of those contents are pointing to pages. Is that on purpose? I would have thought those were for other posts.

**Comment by mashikag** [comment]
Good points @csabarakasz! 

To be investigated:
1. `Great content you might have missed` should contain list of posts, not pages.
2. Handle posts with no post title. Either do not display such posts in the list, or provide some fallback content for the post's list item.

**Comment by mashikag** [comment]
**Re:** 
> 1. `Great content you might have missed` should contain list of posts, not pages.

@csabarakasz I have investigated the above point which was created because of the following statement.

> Also, I noticed that all of those contents are pointing to pages. Is that on purpose? I would have thought those were for other posts.

I took my test page which has more than 5 pages and more than 5 posts. I used my sandbox environment for testing and I reverted the code base to use the old email templates. Here is the screenshot of the email I have received:
![Screenshot 2022-04-29 at 14 31 46](https://user-images.githubusercontent.com/2019970/165945650-9fc27c58-f553-4bc7-98d3-b3fe6aca92bb.png)

Then I cancelled the subscription and did the same but with the new email templates applied.
![Screenshot 2022-04-29 at 14 31 32](https://user-images.githubusercontent.com/2019970/165945774-f1f24095-cf4f-48e4-9757-e3c5d8a3b3ac.png)

Both emails produce exactly the same list. The list is a mixture of pages and posts. The [Subscribe to my site](http://simplesitetest456643757.wordpress.com/subscribe-to-my-site/) is a page where as the other two, [Posting a post](http://simplesitetest456643757.wordpress.com/2022/04/12/posting-a-post/) and [Long, long ago: Dragons](http://simplesitetest456643757.wordpress.com/2022/04/12/long-long-ago-dragons/), are posts. 

Hence the following point is not an issue.
> 1. `Great content you might have missed` should contain list of posts, not pages.

The list is a mixture of pages and posts. The logic used for picking the posts and pages that make the list is in fact a duplicate code of what it used to be in the old email templates.

**Comment by mashikag** [comment]
**Re:**
> 2. Handle posts with no post title. Either do not display such posts in the list, or provide some fallback content for the post's list item.

I just confirmed that this is long existing issue. It is not specific to the new e-mail templates. Using my sandboxed environment I tested how the old email templates handled such situation where one of the posts has no title. Firstly I removed the title from [Posting a post](http://simplesitetest456643757.wordpress.com/2022/04/12/posting-a-post/) post. From doing the tests in the above https://github.com/Automattic/wp-calypso/issues/62995#issuecomment-1113270003 I was confident that the post will be included in the `Great content you may have missed` list, and so it was.
![Screenshot 2022-04-29 at 15 36 08](https://user-images.githubusercontent.com/2019970/165956308-280b1b1d-ee99-40b8-9967-1fe0ca1fd881.png)

**Therefore the issue is not a regression introduced by the new email templates implementation.**

For now my proposal would be simply to skip any posts/pages which have an empty title.

**Comment by mashikag** [comment]
I created a patch for this: D79838-code

**Comment by csabarakasz** [comment]
Thank you so much for the update and the patch! :)

**Comment by ivan-ottinger** [comment]
We have deployed the fix (D79838-code) to production. → Closing this issue.
