### ISSUE TITLE
Marketplace: Rework or replace UrlSearch wrapper

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#63013]
Currently `PluginsBrowser` is wrapped in the UrlSearch HOC:

https://github.com/Automattic/wp-calypso/blob/bf1b6bfda7dcf18b282a77b446a531632eddf47a/client/my-sites/plugins/plugins-browser/index.jsx#L742

The way this HOC is constructed is a blocker to scaling search. We should replace it or refactor it as a hook.

Acceptance criteria:
- [ ] Remove or replace this wrapper for the Marketplace search.

**Comment by allilevine** [comment]
UrlSearch is using Lifecycle methods; add to hook instead. Might need wide testing; could create new one just for Marketplace.

Adds ?s= to search URL.

**Comment by lsl** [comment]
Some extra context from slack p1651657558749909/1651058992.576089-slack-C03DY3RJ5, we can try tick off a box in https://github.com/Automattic/wp-calypso/issues/58453 with this if we want too.

**Comment by paulopmt1** [comment]
The next step here will be adding support to `queryParams` instead of just a query search string [in the previous refactor](https://github.com/Automattic/wp-calypso/pull/63352).

With this queryParams, we expect to get and update more than one parameter on the URL.
For instance, if we have the following URL: `/plugins?search=s&category=c` and we call the hook, it should return `{ search: 's', category: 'c' }`

We also need to be able to do the other way around, writing new queryParams and the hook should replace them in the URL.
