### ISSUE TITLE
[Storefront] Edit button on Storefront theme lands on broken page

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#63011]
### Quick summary

When I click on the Edit button on the theme from the My Site → Appearance → Themes page, it takes me to a broken Full Site Editing page, even though the theme isn't supported by FSE.

### Steps to reproduce

1. Click on the Edit button on the Storefront theme.
2. It takes me to https://wordpress.com/site-editor/galakhyatiatomicsite1.wpcomstaging.com URL.

### What you expected to happen

Since the theme isn't supported by FSE, it should show the Customize button instead of the Edit button.

### What actually happened

It shows the Edit button and takes you to Site Editor link which shows an error.

Screenshot:
<img width="1219" alt="Markup 2022-04-25 at 17 49 35" src="https://user-images.githubusercontent.com/7382505/165093994-ecfeb208-3f4d-483d-97ed-0c39cdbec0fd.png">

Screencast video of the issue: 

https://user-images.githubusercontent.com/7382505/165094290-502700d5-6901-4294-ae53-8f609655fa6a.mp4

### Context

Customer report

5165529-zd-woothemes

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Storefront

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
Thank you for reporting this @galakhyati! I believe this could be related to this one: https://github.com/Automattic/wp-calypso/issues/62755

@Addison-Stavlo I can see the error message is slightly different therefore I'm not if we should close this one in favor of the above.

Also, I noticed Nic opened a new report about this inconsistency regarding FSE for some non-FSE themes: https://github.com/Automattic/support-tools-maintenance/issues/78

**Comment by Greatdane** [comment]
Reported here for Astra theme as well; 23437437-hc

**Comment by cuemarie** [comment]
Ran into this with a user on Dara theme: 35514472-hc

- `Edit` site on dashboard's My Home https://wordpress.com/home/
- `Edit` button on Themes page https://wordpress.com/themes/, and
- `Customize site` button on the theme's info page https://wordpress.com/theme/dara/

all try to open https://wordpress.com/site-editor/ instead of the Customizer, resulting in:

```
Sorry, you are not allowed to access this page.
```

I also mentioned this over on https://github.com/Automattic/wp-calypso/issues/62755#issuecomment-1128168176  - I wonder if the slightly different error message might have to do with the user's location (GB vs US, for instance?)

**Comment by arunsathiya** [comment]
I am closing this in favor of the other issue:

- https://github.com/Automattic/wp-calypso/issues/62755

If there's something about the current issue, feel free to tell me and reopen this issue.
