### ISSUE TITLE
Need to upload the plugin again in WP-Admin interface when attempting to replace an existing plugin

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#63010]
### Quick summary

After the user uploads the plugin on the Calypso interface, they're then taken to the WP Admin interface and need to upload the plugin file again. This is a repeat of the action we're expecting the users to perform, which can be frustrating if this needs to be done for multiple plugins.

### Steps to reproduce

1. Install a plugin on your atomic site.
2. Try to upload another version of the same plugin from Calypso.
3. You'll land on a page where it'll say the plugin already exists on the site. With Continue and Back buttons.
4. Clicking on the Continue button takes me to the WP-Admin interface where I need to upload the plugin again in order to replace/update the plugin.

### What you expected to happen

Ideally, when I upload the plugin again on the Calypso interface, I'd expect to allow me to replace/update the plugin there itself.

Since this is currently being handled in WP-Admin, when the system detects the plugin's copy is existing on the site, it should redirect to the WP-Admin interface and detect the uploaded plugin and allow to replace/update the plugin copy.

### What actually happened

After uploading the plugin copy, I was redirected to the WP-Admin interface and then upload the plugin again. 
Slack: p1650625052885289-slack-C029JEQRVRT

### Context

dog-fooding

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Share the /wp-admin/plugin-install.php?tab=upload link with the user to directly replace/update the plugin.

**Comment by Greatdane** [comment]
I assume this is expected behavior, the states that if you want to update the plugin, you would have to do so via wp-admin. Clicking continue takes you to wp-admin where you can then overwrite the plugin. 

<img width="693" alt="Markup 2022-04-28 at 14 26 07" src="https://user-images.githubusercontent.com/5075840/165682534-e3018d9b-7290-4e4f-a01c-ee8452d484ed.png">

and then replace via wp-admin;

<img width="734" alt="Markup 2022-04-28 at 14 28 06" src="https://user-images.githubusercontent.com/5075840/165682600-46ac2b2d-fee2-4d09-a0ec-99b4eee8a24d.png">
