### ISSUE TITLE
[Bug]: Coupon for yearly product isn't discarded in checkout page when switching to monthly term

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/wp-calypso#63020]
### Quick summary

Let’s assume there’s a yearly term product in the cart, and that a coupon for this specific product has been applied (coupon’s available for the yearly term only). When switching the term from _One year_ to _One month_ in the term dropdown, the coupon is still applied, while it shouldn’t for the monthly term.

This seems to only happen when the term selection is made through a dropdown, and not when terms are displayed in a list.

### Steps to reproduce

1. Create a test coupon, and make sure not to select a monthly term when choosing a product to which it applies. Select a Jetpack product so that a term dropdown is displayed in the checkout page.
2. In Calypso (with a Jetpack site selected) or Cloud, visit the pricing page.
3. Add the product you've created a coupon for to the cart (make sure it's the yearly term).
4. Visit the checkout page if you're not there already.
5. Apply the coupon via the text input, or via the `coupon` query parameter.
6. Coupon should be applied successfully.
7. In the term dropdown, select _One month_ instead of _One year_.
8. Notice that the coupon still applies.

### What you expected to happen

Coupon should be automatically removed, since it doesn't apply to the monthly term. It should be applied again if the user switches back to _One year_, though.

### What actually happened

Coupon is still applied.

### Browser

Google Chrome/Chromium

### Other notes

Tested with a Jetpack product and no site selected from the [Jetpack Cloud pricing page](https://cloud.jetpack.com/pricing), and with a Jetpack site selected in Wordpress.com.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by DavidRothstein** [comment]
Some discussion on this here: p1650914923579369-slack-C0117V2PCAE

**Comment by sirbrillig** [comment]
Mentioned by @DavidRothstein in Slack (p1650914923579369-slack-C0117V2PCAE), it looks like this was intentional behavior added to the coupon system so that the same coupons could be used for monthly plans: D49095-code

Later, the coupon system was modified to allow for coupons per term length (pau2Xa-2lC-p2) but possibly only for wpcom plans and not for Jetpack plans. However, if that's accurate, it should be impossible to create a coupon that applies only to a Jetpack plan with a specific term length, and yet it seems that we can. So something is wrong somewhere.

**Comment by sirbrillig** [comment]
cc @Automattic/martech since they generally manage the coupon tool and organized all the above-mentioned changes.

**Comment by sirbrillig** [comment]
Discussion: this needs to be fixed at the very least inside the coupon admin tool. Either we need to disallow Jetpack products from creating term-specific coupons there, or we need to make it so that Jetpack term-specific coupons actually are restricted by term. EDIT: **this latter option would be preferable!**

Generally @Automattic/martech deals with this tool, so we'll see if they can fit this in to their schedule.

**Comment by monsieur-z** [comment]
Thanks for the details @sirbrillig.

> Discussion: this needs to be fixed at the very least inside the coupon admin tool.

In pbNhbs-1xX-p2, we've implemented a feature that generates coupons for the yearly term of some products. If the fix is in the admin tool only, we'll need to find a way to disable term switching in the checkout page.

**Comment by sirbrillig** [comment]
In that case hopefully the solution is this:

> we need to make it so that Jetpack term-specific coupons actually are restricted by term.

**Comment by aneeshd16** [comment]
Hi @monsieur-z, @sirbrillig! I have started work on this in D79775-code by adding a failing test. Please let me know on the diff if this is what you're expecting!
cc: @southp

**Comment by monsieur-z** [comment]
Thanks @aneeshd16! Yep, that looks good to me.

**Comment by aneeshd16** [comment]
Hi! This was fixed via D79775-code. Closing this :shipit: !
