### ISSUE TITLE
Slideshow Block incorrectly calculating height

### ISSUE THREAD

**Issue by cintacks** [Automattic/wp-calypso#63082]
### Quick summary

The Slideshow Block height is too high on specific pages (could be site-specific). Could be an issue with the number of gallery images - seems to be affects by positioning of pagination controls. 

### Steps to reproduce

1. Go to https://uknorthwalesholidayrentals.co.uk/abi-horizon/
2. Remove `display:none` for .wp-block-jetpack-slideshow .wp-block-jetpack-slideshow_pagination.swiper-pagination-bullets in devtools (this was a CSS hotfix implemented to mitigate this issue)
3. View vertical height.

Alternatively, edit above page - vertical height evident within editor. 

### What you expected to happen

Slideshow Block height should be normal, based on internal contents.

### What actually happened

Slideshow Block height is too tall, creating space underneath

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Morden

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

CSS hotfix implemented:

```
.wp-block-jetpack-slideshow .wp-block-jetpack-slideshow_pagination.swiper-pagination-bullets {
	display:none;
}
```

**Comment by zachspears** [comment]
Unable to replicate, need another triagers input. 

Clarification of issue: If the provided CSS is removed from Additional CSS there is a large space added below the Slideshow block. This space appears to come from the "dot" navigation of the slideshow as it does not appear on the page, and removing it with CSS fixes the issue. 

Tested:
- Tried adding block with same number or images, while using the same theme. 
- Tried checking for plugin conflicts.
- Inspected CSS code. 
- Checked Block settings.

**Comment by kathrynwp** [comment]
Ran into this in 35348273-hc as well 

Provided the CSS workaround mentioned in the OP.

**Comment by jorpdesigns** [comment]
Reported in 35376910-hc. Shared CSS workaround.

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate the issue on AT test site only, not simple or self-hosted
- Themes Tested: Blockbase, Morden

### Test
https://user-images.githubusercontent.com/27249804/166732202-6390cb91-4c04-430b-a545-a02617c82694.mp4

### Result 
<img width="1127" alt="Markup 2022-05-04 at 09 46 03" src="https://user-images.githubusercontent.com/27249804/166732398-c2f9a91d-b002-409d-a733-2c0c3ecb60c9.png">

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Notes from Test:**

- I was only able to recreate this by adding a high number of images. Not all of my images are optimized, but I checked the original report's slideshow, and it looks like all their images are well under 1MB in file-size.
- AMP is deactivated on my test site and OP, but is enabled on the site kathrynwp assisted with.
- Copying the OP's slideshow to my test site resulted in the same spacing issue (on Blockbase theme), so I don't believe the user's site or theme are the cause. 
- Rebuilding the slideshow on the OP's page with a new block did not help either - the same spacing issue occurred.

**Comment by NoHopeRadio** [comment]
I think I understand what's going on here, but I don't know the exact cause. It seems that somewhere there's a display property being set for the `swiper-container` class from a source other than the standard swiper.css stylesheet, and in the swiper.css stylesheet, there's no display property defined for the `swiper-container` class (it seems to inherit the `display: block;` property from its parent div). Since something else is defining it though, an errant `display: flex` property is loading with nothing to counteract it, and I think the main problem with this property is that the pagination links don't load correctly in a flex container. Thus, when there are a lot of pagination links, they create that extra space.

I think simply adding some variation of

```
.swiper-container {
display: block;
}
```
to the swiper.css file will fix the issue, though I still don't understand where these other rules are coming from. On a site I was looking at with this problem, the extra rules were from a stylesheet with a randomly generated string of numbers as a name:

![Notice that the correct swiper.css stylesheet is still present](https://user-images.githubusercontent.com/71042895/166998480-cb0ea57f-1c97-4e2d-b642-c2c44acb8847.png)

I could not figure out the source of these files. It seems to be an aggregate of some Jetpack rules and the theme rules.

we were discussing this in slack-C03TY6J1A/p1651768807029699

**Comment by vajrasar** [comment]
Reported in chat, followed up with a CSS workaround.

- [ ] 5249055-zd-woothemes

**Comment by edequalsawesome** [comment]
Provided CSS to resolve this in 29575302-hc

**Comment by ccwalburn** [comment]
- [ ] Instance reported here: 5287074-zen

Provided CSS workaround.

**Comment by kelasante** [comment]
Another report here - 35813792-hc

Shared CSS workaround.

**Comment by vykes-mac** [comment]
@cuemarie are you still able to reproduce this issue? I can't seem to repro it. I've tried AT, Simple and Jetpack Site and can't get to break.

**Comment by vykes-mac** [comment]
We've discovered here that the issue happens whenever the [coblock](https://github.com/godaddy-wordpress/coblocks/blob/99a53c304c2c3bdd2b3cb867c1d55adcefef3c51/src/components/swiper/style.scss) plugin is installed, it adds the following css 
```
.swiper-wrapper {
    display: flex;
    height: 100%;
    margin: 0;
    padding: 0;
    width: 100%;
}
```

which overrides our swiper-container css. That's why the issue is reproducible mostly on AT sites
