### ISSUE TITLE
Jetpack Connect: redirect occurs when connecting an already owned site

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#6310]
#### To reproduce:
- On wordpress.com, clear your Redux state using Chrome's Resources tab
- Go to wordpress.com/jetpack/connect and try to connect a site that is already connected for you
- You'll get redirected
  - Older versions of jetpack will see this: ![screen shot 2016-06-24 at 3 47 25 pm](https://cloud.githubusercontent.com/assets/2694219/16348869/1f1b59ea-3a23-11e6-8021-cba8557df4a2.png)
  - The latest Jetpacks will see this: ![screen shot 2016-06-24 at 3 47 48 pm](https://cloud.githubusercontent.com/assets/2694219/16348881/2c31b174-3a23-11e6-9c3e-6709ae8b6be9.png)
#### What I expected:

Since I've already connected the site, I expected to see this:
![screen shot 2016-06-24 at 3 50 56 pm](https://cloud.githubusercontent.com/assets/2694219/16348922/76885836-3a23-11e6-8c4f-0cc30f2c32d7.png)
#### Some Notes

While searching for a solution, I noticed a these two things that might offer some clues:
- If you wait a minute or so for the Site's list to load while on wordpress.com/jetpack/connect, everything works as expected
- If you use the site picker to select the site in question, and then come back to wordpress.com/jetpack/connect, everything works as expected.

**Comment by tyxla** [comment]
For some unknown reason, I'm unable to reproduce this. Probably because of the number of sites I have?

**Comment by johnHackworth** [comment]
yeah, this is a race condition. You probably couldn't reproduce it because your sites-list is being retrieved quicker than rocco's, @tyxla .  

Anyway, this is probably not something users are going to get into unless they manually clear their browser indexedDB, because if you already connected the site before, you already will have your sites list cached there ...  but yeah, we probably should add some checks to wait until there's info in sites-list before proceed to check a url and/or send them to authorize it in wp-admin

**Comment by tyxla** [comment]
This has been updated a while ago and currently redirects to the "My plan" page.
