### ISSUE TITLE
Karuna: Incorrect "More posts" button visible on the homepage

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#63141]
### Quick summary

On the Karuna theme, there's a setting within `Theme options` area of the Customizer that allows one to show four posts on the homepage: `Display up to four Recent Posts on the static front page.`. Enabling this setting shows four posts, and a `More posts` button below it which doesn't respond. Since only upto four posts are shown, the button shouldn't exist.

### Steps to reproduce

- Activate Karuna on a WordPress.com site: https://wordpress.com/theme/karuna
- Publish four blog posts.
- Set a static homepage.
- Enable `Display up to four Recent Posts on the static front page.` on `Theme options` area of the Customizer.

### What you expected to happen

There's no `More posts` button.

### What actually happened

There's a `More posts` button which does not respond.

<img width="1701" alt="image" src="https://user-images.githubusercontent.com/18581859/165780334-8911c60e-f21e-4b93-8ffc-7e780a4acd9b.png">

### Context

User report.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Karuna.

### Browser, operating system and other notes

All.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Have to turn off the setting and then add "Blog posts" block to the homepage.

**Comment by arunsathiya** [comment]
5173795-zen.

**Comment by arunsathiya** [comment]
To clarify, the button responds, but it just refreshes the page with no visible change.

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Theme Tested: Karuna

📌 FINDINGS/SCREENSHOTS/VIDEO

- I was able to replicate the issue. However, I saw that I did not have a posts page set. When I selected an option for the Posts page, the "More Posts" button redirected to the selected Posts page - so it seems it may rely on there being a Posts Page set up.  With that in mind, this looks to be intended behavior. 
- I checked the site of the user who reported the issue, and they don't have a Posts page set. 

<img width="397" alt="Markup 2022-05-04 at 11 08 44" src="https://user-images.githubusercontent.com/27249804/166797755-a5a9613d-2c2d-43cb-b2d4-d7810c932828.png">

<img width="952" alt="Markup 2022-05-04 at 11 14 17" src="https://user-images.githubusercontent.com/27249804/166799254-2a821a61-e596-4018-a1b4-12616d1ac48e.png">

📌 ACTIONS
- Await author feedback
- Closed as this appears to be expected behavior, please reopen this issue if you believe there is a bug that needs addressing here

 @arunsathiya Can you see if the user is open to setting a Posts Page from within `Appearance > Customize > Homepage Settings`? This might alleviate the difficult workaround with a simpler option.

**Comment by arunsathiya** [comment]
@cuemarie Great find, thank you! I followed up with the customer to share that info.

**Comment by arunsathiya** [comment]
@Automattic/dotcom-pqa-group Should we move this issue to https://github.com/Automattic/themes?
