### ISSUE TITLE
[Bug]: Link to help page for WordPress.com Plans not working

### ISSUE THREAD

**Issue by guarani** [Automattic/wp-calypso#63185]
### Quick summary

When buying a plan, WP.com sometimes offers the user a button to read more about plans, but that button doesn't appear to work.

https://user-images.githubusercontent.com/1898325/166067210-ea10b9d0-b5da-4aef-9b6e-38e97ce06c73.mov

### Steps to reproduce

1. On https://wordpress.com, select a site in the site picker
2. Click Upgrades
3. Click "Start with Pro"
4. Notice a button that says "Questions? Ask a Happiness Engineer" (⚠️ some accounts show a different button that has different functionality, so you may have to try multiple sites or accounts until a button with this text appears)
5. Click that button and a "Search for help" popup will appear
6. Click "WordPress.com Plans"
7. Notice the subsequent popup doesn't show much useful information (I'm not sure if this is a bug)
8. Click the "Read more" button and notice that nothing happens (this is the bug)

### What you expected to happen

The "Read More" button should open a page explaining plans.

### What actually happened

The "Read More" button does nothing visibly.

### Context

I noticed it while testing something else.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Users can search for plans on the help page (https://wordpress.com/support/plan-features/).

**Comment by sirbrillig** [comment]
This is happening because the checkout page has a hash in the URL, `/checkout/sitename#step2`, and the help modal tries to add a query string to the page, but does so poorly without considering the URL structure and ends up just appending it to the hash like `/checkout/sitename#step2?support-article=XXXXX`. Since that's not a real query string, it does nothing.

Fortunately, URL parsing is pretty easy in modern JS so I looked to see where the URL is being modified to add a fix, but it turns out to be a bug in the `addQueryArgs()` function of the `@wordpress/url` package:

https://github.com/WordPress/gutenberg/blob/6fab3c45c6f357dee0ee920221698322ddd1857c/packages/url/src/add-query-args.js#L41

I'll submit a PR to fix it there but in the meantime we can probably modify `useRouteModal()` in calypso to do the right thing.

https://github.com/Automattic/wp-calypso/blob/3569fd4aad505429d374808c5e3600a44188fa3b/client/lib/route-modal/use-route-modal.tsx#L35

**Comment by sirbrillig** [comment]
It looks like this bug in `@wordpress/url` was already reported in https://github.com/WordPress/gutenberg/issues/16655 (props to @guarani for finding it!)
