### ISSUE TITLE
Navigation Block not populating page links

### ISSUE THREAD

**Issue by cintacks** [Automattic/wp-calypso#63209]
### Quick summary

Navigation Block isn't populating page links (but other link types are ok), effectively making menu invisible on frontend.

### Steps to reproduce

1. Add Navigation Block
2. Add page link
3. View frontend, page link not visible, even in HTML

### What you expected to happen

Page links should be visible

### What actually happened

Page links not included in code. 

### Context

Noticed on `jaimeconejos.com` (2020 theme installed) - 5184079-zd-woothemes

I don't know if other users have been impacted but this is such a common theme, that it should be flagged.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Twenty-Two

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Add custom links instead for now: https://d.pr/v/0bfJox

**Comment by zachspears** [comment]
Unable to reproduce the issue, installed 2020 theme and tried adding a Navigation Block and page link:
<img width="1096" alt="Screen Shot 2022-05-11 at 6 21 34 PM" src="https://user-images.githubusercontent.com/10124024/167968306-a39628c9-5007-49c6-aa99-213971af5c30.png">
<img width="1096" alt="Screen Shot 2022-05-11 at 6 22 10 PM" src="https://user-images.githubusercontent.com/10124024/167968320-01ce1d74-3d6e-4c81-b233-2176d1312e07.png">

Droplr video appears to be faulty, I downloaded it, but it acts as a screenshot, unfortunately: https://d.pr/v/0bfJox
Marking closed unless this issue is replicated.
