### ISSUE TITLE
Premium Content as a Reusable Block: White Dot on Publish Button appears when Reusable block has not been modified

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#63200]
### Quick summary

If you modify a Reusable block while editing a post, a white dot appears on the Publish button, but there are some situations where the white dot is displaying even when no changes are being made to the reusable block on the page. 

<img width="1261" alt="Screenshot 2022-04-28 at 20 32 42" src="https://user-images.githubusercontent.com/15944096/166420677-1c0465b3-eadf-48c0-824e-0bf79259572a.png">

Here are two examples:

1. Adding a Reusable Block with a Payment Button or Premium Content block causes the white dot to appear as soon as the block is added to the page and no modifications have been made.
2. Adding a Reusable Block to a post and making a change to it, but then changing it to a regular block without publishing

### Steps to reproduce

Example A:
1. Add a Premium block to a post and convert it to a Reusable block
2. Create a new post
3. Add the Reusable Premium block to the post

Example B:
1. Add a paragraph block to a post and convert it to a Reusable block
2. Create a new post
3. Add the Reusable Paragraph block to the post
4. Add text to the paragraph
5. Convert the Reusable block to a Regular block

### What you expected to happen

Example A:
I didn't expect the white dot to appear on the Publish button

Example B:
I expected the white dot to disappear from the Publish button

### What actually happened

Example A:
The white dot appeared next to the Publish button as soon as the block was added.

Example B: 
The white dot remained on the Publish button after I converted it to a regular block.

### Context

5176139-zen

**Comment by pauljacobson** [comment]
The user has followed up with us, and has described this issue as a blocker for them. In the meantime, here is what happens when you add a regular (non-Premium Content) reusable block to a post:

https://user-images.githubusercontent.com/2912202/166197858-a4ed330b-68c3-47ed-bfec-966bc87d150a.mp4

Here is a demonstration of what happens when adding a reusable Premium Content block. Note the white dot on the _Publish_ button, and the message indicating that changes to the block will be made when publishing the post:

https://user-images.githubusercontent.com/2912202/166198094-6e3bc89b-8245-4ac1-9949-9594c269f338.mp4

I wasn't able to determine whether clicking the _Publish_ button, and accepting the proposed changes to the reusable block _actually changed the block_. Just based on my limited test, this doesn't seem to have happened.

**Comment by formosattic** [comment]
In Visual view, nothing changes, but when checking the revisions of the Premium Content Reusable block, we notice that the URL of the buttons get updated with the ID of the post, so that explains why the editor is detecting a modification (and the white dot appears)

Example from test site (Premium Content block not connected to Stripe):

![image1](https://user-images.githubusercontent.com/15944096/166443989-3fac3b08-e236-40e6-88a9-1cfc5d5cf3d1.png)

![image2](https://user-images.githubusercontent.com/15944096/166443984-2dcb9ddc-77a5-4f75-b1df-9241c4b17cac.png)

**But is it the expected behavior of a Premium Content block that is reusable, that the button URLs auto-update with the new post ID?**

Is this a recent change? Something happened around April 29, 2022, that disturbed the user's workflow (still gathering more info on that).

**Comment by formosattic** [comment]
Got some clarifications internally: p1651579207312679-slack-CJS75TX3R:

> we've been working on the premium content block. Now the postId gets added so that it can be correctly opened when clicking on the subscribe button through the reader, email or notifications.
>
> The white dot appears since the user needs to update the post in order for the changes to take effect.
>
> You can also expect this exact same behavior in posts that have a recurring payments button.

The white dot on the Publish button indicating the change is the expected behavior, so will close this report.

We'll want to explain this to users, and guide their workflow based on this expected behavior.
