### ISSUE TITLE
Help Center: Fix design problems

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#63275]
Design Improvements.

## Article Page 
- External link icon should be 20px (I had issues seeing it on the live site so still need to look again)
- All titles should be var( --color-neutral-100);
- h1 should be: font-size 20px, font-weight: 600;
- h4 should be: font-size 16px, font-weight: 600;
- h5 should be 14px, font-weight: 600;
- p should be: 14px, var( --color-neutral-80 );
- remove `.support-article-dialog__story` 20px padding.
- all links should be var( --studio-blue-50 ); with no underline.
- ul should be:
    - 14px, var( --color-neutral-80 );
    - Add bullets to the ul.
- `.wp-block-quote `should be:
    - background var( --color-neutral-0 );
    - No border left.
    - Padding 16px.
    - Text var( --color-neutral-80 );
    - `.noticon noticon-star` var( --studio-yellow-20 );
- `.wp-block-separator` should be 1px, var( --color-neutral-10 );
- `.wp-block-group__inner-container` should have a bg of var( --color-neutral-0 );
- `.wp-block-group__inner-container` should have extra top & bottom padding of 16px.
- Can `.wp-block-button` be styled the same as `.button-primary`?

## Table of contents:

- “Table of contents” title should be: var( --color-neutral-80 ); font-size 16px.
- section (without title) should have a fill of var( --studio-blue-0 );
- section padding should be 16px.
- remove numbers for item list.

**Comment by poligilad-auto** [comment]
Hey @arcangelini,
Didn't have a chance to see all the design styles live, so I'll have more comments later, but I did manage to go over the "article" page. We can make these style changes to make it fit in better.

Article page:
- External link icon should be 20px (I had issues seeing it on the live site so still need to look again)
- All titles should be var( --color-neutral-100);
- h1 should be: font-size 20px, font-weight: 600;
- h4 should be: font-size 16px, font-weight: 600;
- h5 should be 14px, font-weight: 600;
- p should be: 14px, var( --color-neutral-80 );
- remove `.support-article-dialog__story` 20px padding.
- all links should be var( --studio-blue-50 ); with no underline.
- ul should be:
    - 14px, var( --color-neutral-80 );
    - Add bullets to the ul.
- `.wp-block-quote `should be:
    - background var( --color-neutral-0 );
    - No border left.
    - Padding 16px.
    - Text var( --color-neutral-80 );
    - `.noticon noticon-star` var( --studio-yellow-20 );
- `.wp-block-separator` should be 1px, var( --color-neutral-10 );
- `.wp-block-group__inner-container` should have a bg of var( --color-neutral-0 );
- `.wp-block-group__inner-container` should have extra top & bottom padding of 16px.
- Can `.wp-block-button` be styled the same as `.button-primary`?

Table of contents:

- “Table of contents” title should be: var( --color-neutral-80 ); font-size 16px.
- section (without title) should have a fill of var( --studio-blue-0 );
- section padding should be 16px.
- remove numbers for item list.

This is what I managed to see from looking at one article, but I'm sure I missed something so will look again on Friday.
I guess I should be changing h2 & h3 as well? Didn't see if they are used somewhere.

**Comment by poligilad-auto** [comment]
**Resources:**

All resources should appear like they do on the "contact us" page (icon color, size etc.).
<img width="461" alt="image" src="https://user-images.githubusercontent.com/83961704/167138119-331f0d9b-a8ab-4fbd-ae18-956601b2e4ab.png">

For some reason they appear differently on the main "help center" page.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/83961704/167138189-d0c490fd-1015-4dff-b44c-65348c6b5876.png">

**Comment by poligilad-auto** [comment]
- **Help center height**: originally I though “800px” was good, but testing it on desktop “cuts off” the edge of it. Can we have the height dependant on the viewport height? Something like 80%?
<img width="484" alt="image" src="https://user-images.githubusercontent.com/83961704/167826887-1ee30798-2b68-4d49-983f-eea531c6aa62.png">

- **Button focus state**: Let’s remove the “focus” state from all these buttons after clicking (all resources, all the links under “more resources”, all “show me where to” resources, back buttons, “Still need help” button, “open in a new tab” button in the article page).
https://user-images.githubusercontent.com/83961704/167826920-9daae498-3042-4b87-ab1b-a372065d39cb.mov

- **Colors**: I prefer us not to hard code any colors, they should all come from these [vars](https://github.com/Automattic/wp-calypso/blob/HEAD/packages/calypso-color-schemes/src/shared/color-schemes/_default.scss), not sure how to do that. I’m happy to have a zoom call and maybe just go over them one by one? Or over slack.
- **Back button**: All “Back” buttons should be styles the same. Just like on the “contact us” page.
- **Header**: The “minimize” button isn’t centered, you can see it when it’s “focused”.
- **Article page**: the h1 title is still appearing huge, it should be h1 should be "$font-title-medium" (24px).
- **Article page**: when there is an internal extra ol or li within the main li it shoud still have some indenation, just like in the resources website.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/83961704/167827432-6fe14b99-a64a-4484-a32f-0f7882bd0603.png">

- **Article page**: The seperation lines are still appearing black, I think there are multiple CSS overrides going on there. It should be “var( --studio-gray-10 );”
- **Article page**: remove the bottom margin from “.support-article-dialog__header”.
- **Article page**: sorry if I wasn't clear, the buttons should all look like the theme [buttons](https://wpcalypso.wordpress.com/devdocs/design/button). Now they don't.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/83961704/167828622-5dfc00cb-2b38-401e-82ba-62cb40a4aba2.png">

- **Contact us page**: make the spacing between the email + chat title and the sub-title 2px instead of 5px.
- **Contact us page**: can we style the input fields the same as the search bar? With no “focus” state.
- **Contact us page**: the button should be a [calypso button](https://wpcalypso.wordpress.com/devdocs/design/button), using the same disabled state + correct theme color, now it’s not.
- **Contact us page**: “.site-picker__site-item-site-logo svg” fill should be “var( --studio-gray-30 );”.
- **Contact us page**: let’s use the typography vars for the font sizes.
- **Contact us page**: the text next to the HE photos should be `$font-body-extra-small`.
- **Contact us page**: HE photo sizes should be 32px.
- **Contact form page:** let’s make “.site-picker__site-item” padding: 12px 8px;
- **Chat** - the “unread” messages bubble: was appearing without the BK color. After a while I wasn’t seeing new “unread messages”. Font size of the “unread messages” should be `$font-body-extra-small` padding should be 2px 6px. Color should be the main theme CTA color.
- **Minimized view with long article name**: we should truncate the name when it's long with "...", it's breaking the UI now.
<img width="437" alt="long-article-name" src="https://user-images.githubusercontent.com/83961704/167826742-275a035f-31b5-44c6-9e05-0fe651fc3554.png">
<img width="394" alt="image" src="https://user-images.githubusercontent.com/83961704/167826701-76f79e47-568a-4987-bc62-3609d36ea01d.png">

**Comment by poligilad-auto** [comment]
Nice work @arcangelini!

Most comments are taken care of, some have some issues and I noticed a few other small bits and pieces.

- **“Still need help” button**: the hover color for the button is too dark. Let’s make it like the standard Calypso buttons: [https://wpcalypso.wordpress.com/devdocs/design/button](https://wpcalypso.wordpress.com/devdocs/design/button)
- **All buttons**: I see we have a styling for “.wp-core-ui .button, .wp-core-ui .button-primary, .wp-core-ui .button-secondary” of font-size: 13px. Let’s remove this.
- **Header**: The “minimize” button isn’t centered - still an issue.
<img width="428" alt="image" src="https://user-images.githubusercontent.com/83961704/169490603-bedcb04c-80b8-489d-ba10-6a446d78539b.png">

- **Article page**: table of contents: remove the margin-bottom of 6px from “li” elements.
- **Article page**: The seperation lines are still appearing black, add `border-top: 0; `to `.wp-block-separator` and it should solve it.
- **Article page**: remove the bottom margin from `.support-article-dialog__header`.  Still seeing this.
- **Article page**: h1: change line-height to 32px (maybe just chaing this to $font-title-medium will work?)
- **Article page**: change the `.button-primary` top & bottom padding to 4px (the buttons are too high now).
- **Contact form page - email**: remove “focus state” styling from “subject”.
-  **Contact form page**: have the first field in “focus” by default (either “Subject” or “How can we help you today”).
- **Contact form page**: remove the “other site” option from all forms except the “Public forms” contact form.
- **Contact us page**: the title “Contact our WordPress.com experts” should be the same as the title on the contact forms “Start live chat” etc. They should all be $font-body, font-weight: 500.
- **Contact us page**: “.site-picker__site-item-site-logo svg” fill should be “var( --studio-gray-30 );”. It has an override, so it’s not working.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/83961704/169491624-45a5876b-6a76-46b6-a21d-1f80859c2bd1.png">

- **Chat**: There is some misalignment with the title of the minimized view.
<img width="429" alt="Live chat" src="https://user-images.githubusercontent.com/83961704/169491625-fef2c9b2-fe60-49b3-badb-9b7566ec3382.png">
<img width="437" alt="Live chat2" src="https://user-images.githubusercontent.com/83961704/169491640-f3dab7a4-7245-4201-b1c4-7b12a2adb39d.png">

- **Chat**: It seems that for the “message count” we are also including messages that the user sent. I saw a “1” even when the HE didn’t respond yet. This doesn’t make sense, we should only count HE messages.
- **Contact form page:** let’s make “.site-picker__site-item” padding: 12px 8px;
- **Minimized view with long article name**: we are cutting the article name now, but let’s add "..." to the end of the name, that way it’s clear that it’s truncated.
- **Contact form page**: The site "selector" should be the site image, but I don't think it's picking that up.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/83961704/169492558-ada9c843-6897-4eff-b1e4-fd094e588519.png">
- **Entry point**: Didn't notice this till now, but the "?" should always be next to the "3 dots" icon. In every editor. That way it has a permanent location.
Also just noticed that the "?" isn't centered within the button.
<img width="382" alt="image" src="https://user-images.githubusercontent.com/83961704/169492792-510e294d-09ce-4cc0-a402-696457f73fa9.png">.
