### ISSUE TITLE
Woo on Stepper: remove the hasAvailableSiteFeature from site data store

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#63296]
As @obenland [noticed here](https://github.com/Automattic/wp-calypso/pull/62919#issuecomment-1115401427) the `hasAvailableSiteFeature` selector shouldn't be here. We should re-check that this selector is not being used and remove it if it isn't.

We can also use this opportunity to rename the `hasActiveSiteFeature` to `siteHasFeature` as suggested in this p2: p4TIVU-a66-p2

**Comment by valterlorran** [comment]
I'm taking a look on this issue and It seems to be used here:
https://github.com/Automattic/wp-calypso/blob/d224e8dde4e005c710e42bbba3e035523cb565da/client/landing/stepper/declarative-flow/internals/steps-repository/woo-confirm/index.tsx#L93

Because it uses the `hasAvailableSiteFeature` selector here:
https://github.com/Automattic/wp-calypso/blob/d224e8dde4e005c710e42bbba3e035523cb565da/packages/data-stores/src/site/selectors.ts#L130-L139

**Comment by obenland** [comment]
Yes, you should be able to replace it with just `! select( STORE_KEY ).hasActiveSiteFeature( siteId, 'woop' )`. `hasAvailableSiteFeature` is redundant in this instance (it's always available through an upgrade).
