### ISSUE TITLE
[Bug]: Add block button, block inserter, not showing to the side of a block

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/wp-calypso#63301]
### Quick summary

The add block button, **Block Inserter**, that shows to the side of an empty block is *not* showing up as explained at https://wordpress.com/support/wordpress-editor/add-content-blocks/#how-to-add-a-block 

Creating new line doesn't automatically display + button, or Block Inserter,  to the side of the empty block. To get it to display to the side of the empty block, I have to click out and make sure no block is selected.

Video of issue: 

https://user-images.githubusercontent.com/77413972/166747646-632cbc7b-e620-45d4-b7df-51553160d67a.mp4

### Steps to reproduce

1. Edit any page or post
2. Press the Enter/Return key on your keyboard to create a new line below it
3. Find that + button, block inserter, does not display to the right side of the empty block 

### What you expected to happen

I expected that the block inserter would display to the side of the empty block, as explained here: https://wordpress.com/support/wordpress-editor/add-content-blocks/#how-to-add-a-block

I expected that if I press the Return key on my keyboard to create a new line below it, the + Block Inserter button would display. 

### What actually happened

The + Block Inserter button is not displayed after adding a new, empty block. To get the + Block Inserter button to display to the side of the block, you must make sure you do not have a block selected (as seen in my video above).

### Context

Customer reported in 35380407-hc

### Browser

All browsers, I used Firefox and Chrome to test

### Simple/Atomic

Both Simple and Atomic sites

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Use another way to add a block: 

- Click the + Block Inserter at the top left corner of the editor
- Click on exisiting block → three dots → Insert before/after

**Comment by ClassicRKR27** [comment]
Another report here: 35323401-hc

**Comment by thekingsprojects** [comment]
Another here: 35405612-hc

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on P2 ✅ **Replicated**
- Tested on Simple ✅ **Replicated**
- Tested on AT ✅ **Replicated**
- Tested on Self-hosted ✅ **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this issue on both Simple and AT sites, as well as on P2. Self-hosted environment showed the `+` button as expected to the right of an empty block.

**Simple**
https://user-images.githubusercontent.com/27249804/167518171-b57b0434-0a23-4955-bb3e-73716dca8e76.mp4

**AT**
https://user-images.githubusercontent.com/27249804/167518196-59fa9a00-64c8-411d-9c0c-126c2b017e8f.mp4

**P2**
https://user-images.githubusercontent.com/27249804/167518203-c04430fe-d316-4c57-be5b-e6470b695930.mp4

**Self-hosted for comparison**
https://user-images.githubusercontent.com/27249804/167518429-a009c15d-cbb7-4d9a-a190-5cea15df1d96.mp4

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by thekingsprojects** [comment]
Another case: 35250290-hc

**Comment by jp-imagines** [comment]
Another report in 35638195-hc.

**Comment by jp-imagines** [comment]
> Another report here: 35323401-hc

- [ ] This user came back in 5318285-zd-woothemes asking for an update on this. They've already identified the existing workarounds (and searching for blocks by typing `/`). I'm sure they'd appreciate a follow-up when this is fixed.

**Comment by vykes-mac** [comment]
I'm not sure this is a bug as seen in the video. The user selects an empty paragraph block which now has the focus, the only time the paragraph block lost focus was when another paragraph block captures the focus. As far as i can tell the + button shows up when you click any where in the editor that's not a block so that no block has the focus. It would be good to get other persons input to verify if that's the expected behavior.

**Comment by mpkelly** [comment]
For me, this does feel a little inconsistent. If I focus the Post Title block on a new post, then the button appears after the empty paragraph, yet when I focus a paragraph block it disappears. I think it's probably designed this way though to try and get the user to use `/` to change the current block, and stop them from adding a new block. So I would say this is expected behaviour. Either way, it doesn't sound like a big issue and users should be able to fix it with `Enter` then `/ <block they want>`. 


https://user-images.githubusercontent.com/6851384/197471674-e6ca24fa-447e-4f38-8b6c-f780c6d23a15.mp4

**Comment by p-jackson** [comment]
I believe this issue has been fixed, probably by some WordPress/Gutenberg update since the bug was first reported.

The + button now appears at the right of empty blocks, the same way it's described in the support docs.

> I expected that if I press the Return key on my keyboard to create a new line below it, the + Block Inserter button would display.

It doesn't _quite_ work this way. When you press Return the + button doesn't appear until you move the mouse. I believe this is intentional to make the paragraph typing experience more pleasant. When you're in the flow, writing lots of text, you'll press Return and immediately keep typing. We wouldn't want the + button appearing and then immediately disappearing. I think it's similar to how we hide the text formatting toolbar while the user is typing. Hide the unnecessary UI elements so they can get in the flow of writing.

This is how it's working in Core too, so we're now matching the vanilla Gutenberg behaviour, which is good.

I've tested the post, page, and site editors, both with a classic and block theme just to make sure they all work the same way.

https://user-images.githubusercontent.com/1500769/236369979-53f7f369-13ee-49a7-ae9d-ae2a374a5f6e.mov

I was going to close this bug, but perhaps we should edit https://wordpress.com/support/wordpress-editor/add-content-blocks/#how-to-add-a-block to avoid any confusion in the future. We could either
- Remove option 3 (`Press the Enter/Return key on your keyboard to create a new line below it, and click the + Block Inserter`)
- Reword it, to make it clear you need to move your mouse.

**Comment by autumnfjeld** [comment]
> I believe this issue has been fixed, probably by some WordPress/Gutenberg update since the bug was first reported.

Should we close this @p-jackson ?

**Comment by p-jackson** [comment]
I re-read the support page and compared it to how the editor was working. I didn't find it confusing, it appears to match the editor behaviour perfectly.
