### ISSUE TITLE
[Bug]: WP.com Atomic site Google Analytics feature docs pointing to Jetpack docs

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#63324]
### Quick summary

Google Analytics feature's docs point to Jetpack docs. cc @donalirl in case there was issue open that I just didn't see.

@alshakero could you add this to Vertex' maintenance backlog? thx!

### Steps to reproduce

- Go to `https://wordpress.com/marketing/traffic` for your Atomic site
- Enable feature and click docs links
- You'll end up at https://jetpack.com/support/google-analytics/

<img width="1081" alt="Screenshot 2022-05-05 at 12 07 09" src="https://user-images.githubusercontent.com/87168/166894347-5bac00b0-593b-4064-8fe3-fbab2a062af1.png">

### What you expected to happen

Docs should point to https://wordpress.com/support/google-analytics/ for WP.com sites.

### What actually happened

Jetpack docs. For Jetpack sites these make sense of course.

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic - **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- That link does still direct to a Jetpack support doc, rather than WordPress.com.  
     - Simple Site > Tools > Marketing > Traffic > Google Analytics: `Learn More` links to https://wordpress.com/support/google-analytics/
     - Atomic Site > Tools > Marketing > Traffic > Google Analytics: both `Learn More` and `Google Analytics with WordPress.com` link to https://jetpack.com/support/google-analytics/

![Markup on 2023-05-17 at 15:22:22](https://github.com/Automattic/wp-calypso/assets/27249804/e1f600a5-4d4b-4e46-9a96-643277a06c95)

📌 ACTIONS
- Assigned to @Automattic/vertex

**Comment by escapemanuele** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/77101
