### ISSUE TITLE
Embed Block Displays the Actual Link Instead of Showing the Preview of the Linked Site

### ISSUE THREAD

**Issue by allanftd** [Automattic/wp-calypso#63380]
### Quick summary

When copy-pasting the direct link of the page to be embedded, the URL itself displays instead of a preview of the page content

### Steps to reproduce

1. Edit a post or page
2. Add an Embed block by typing /Embed
3. Copy-paste the full URL of the page you want to embed, for example: https://www.theguardian.com/environment/2022/may/06/country-diary-the-sheer-joy-of-watching-sparrows-move-in-with-us
4. Click Embed
5. The editor displays the URL itself and not the preview of the embedded page.
User mentioned they were previously able to make the block to work properly on another (older) post. They started having issues only recently.

### What you expected to happen

The preview of the embedded page should show up on the post

### What actually happened

The copy-pasted hyperlink of the page to be embedded shows up instead.

### Context

35402059-hc / 5195086-zen

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Available workarounds?

No but the platform is still usable

### Workaround details

None. tried converting the working Embed block on the old post into a Reusable block but it is not working on the new post. Also tried duplicating the post with the working Embed block but the same issue persists.

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Updated main description of report - No

📌 SCRUBBING
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
Hi there @allanftd 
It seems the link you shared is not able to be embedded because it does not have a previewable card
I've tested the same link on a self hosted site with the same results 
<img width="636" alt="Markup 2022-05-18 at 16 42 46" src="https://user-images.githubusercontent.com/83325600/169160791-6dbc489b-de22-4327-9fc2-899d59e505c1.png">

The feature will work with an embeddable link so I'll go ahead and close this for now 
📌 ACTIONS
- Closed as no longer relevant, feature by design
