### ISSUE TITLE
Make it possible to differentiate which Donations block was used on a site to donate.

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#63398]
### What

Context: 35017139-hc and 4915147-zd-woothemes

User has multiple donations block across multiple pages. They would like to have a feature to be able to tell which page people donated from.

There is no current way to tell that. We can only see details about the donations.

Feature request. Create a tab under Tools > Earn > Collect Payments that would show statistics on which page was used to donate. It would also work to add some identifiers to the donation blocks and those identifiers would show up in the statistics.

![donation blocks](https://user-images.githubusercontent.com/84539773/167285365-a2e4a6c0-cd3b-4493-8840-02e118e64bcc.png)

### Why

Feature requested by a user.

**Comment by Copons** [comment]
@csabarakasz we don't track the origin of payments so it's currently not possible to determine where they come from.
It would also be a particularly complicated task, as blocks can be rendered in posts and pages as well as in any other layout element (FSE templates, widget areas, etc.).

Generally speaking, the user could create distinct products for each area they want to track.
This is possible with the Payment Button block, but **not** with the Donations Form block, which is a special case where the donation products are automatically created behind the scenes, and are the same on every Donations Form block.

This said, currently the Payment Button block supports donation products, so for simple use-cases, the user could use that instead of the Donations Form block.

For example, they could add to the "About Us" page a Payment Button block using a product of type donation called "Donation: About Us".

In the near-ish future, we will create patterns using Payment Button blocks that will completely replace the Donations Form block. At the moment there is no ETA, though.
