### ISSUE TITLE
Subscription Block appears / renders oddly / broken in the post notification emails

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#63628]
### Quick summary

The [Subscribe Block](https://wordpress.com/en/support/wordpress-editor/blocks/subscribe-block/) renders improperly in the notification emails.

Email | Frontend
--- | --- 
![image](https://user-images.githubusercontent.com/39308239/168417359-d76bd029-b45a-41e3-939c-2892a77e5556.png) | ![image](https://user-images.githubusercontent.com/39308239/168417378-af7d9546-0572-448a-a4e4-9e444f5abf3d.png)  

### Steps to reproduce

1. Publish a post including [Subscribe Block](https://wordpress.com/en/support/wordpress-editor/blocks/subscribe-block/) on a site to which you are subscribed to receive new posts via email.

### What you expected to happen

See the [Subscribe Block](https://wordpress.com/en/support/wordpress-editor/blocks/subscribe-block/) rendered as on the frontend or similar

### What actually happened

The [Subscribe Block](https://wordpress.com/en/support/wordpress-editor/blocks/subscribe-block/) appears kind of broken, split into two lines with a big white gap in the middle.

Email | Frontend
--- | --- 
![image](https://user-images.githubusercontent.com/39308239/168417359-d76bd029-b45a-41e3-939c-2892a77e5556.png) | ![image](https://user-images.githubusercontent.com/39308239/168417378-af7d9546-0572-448a-a4e4-9e444f5abf3d.png)  

### Context

User report: 5196787-zd-woothemes

I think this possibly belongs to https://github.com/orgs/Automattic/projects/361/views/2 or at the very least to the Jetpack repo.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.3.1 with Google Chrome Version 100.0.4896.127 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- On a Simple site, I am able to recreate the issue where the Subscribe block renders poorly in the new post email, as shown below: 

<img width="550" alt="simple screenshot" src="https://user-images.githubusercontent.com/27249804/170583274-c1f12598-5366-4789-8a0d-e622a4dd8567.png">

- For AT and Self-Hosted sites, the Subscribe block does not appear at all in the email - the content is removed/hidden. I'm not sure if this is what it should do by design, or if this is a related/separate issue.
- 
<img width="550" alt="atomic screenshot" src="https://user-images.githubusercontent.com/27249804/170583438-d42b5a48-5f9f-4415-a9d8-440eb459b9da.png">

<img width="550" alt="selfhosted screenshot" src="https://user-images.githubusercontent.com/27249804/170583372-dc57c0d2-a04f-4ee7-b8f2-50e291314f60.png">

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by danielbachhuber** [comment]
Spent some time debugging this mis-styled/missing Subscribe Block today.

First of all, email client support for `<form>` is [pretty dismal](https://www.caniemail.com/features/html-form/), so we could:
1. Display a fallback element instead.
2. Remove any reference to the Subscribe Block. It appears the Contact Form Block is removed entirely.

Personally, I'd opt for the latter: removing the Subscribe Block entirely. If someone is already receiving an email notification, I'm not sure why they need to see the Subscribe Block.

In either case, all of the logic to generate the email content lives in `Subscription_Mailer->get_posts()`. It looks like there's a lot of existing logic to handle shortcodes. 

Lastly, there's a really helpful script to send an email from your sandbox: `php ~/public_html/bin/subscriptions/send.php <blog-id> post <post-id> <email-address>`

**Comment by danielbachhuber** [comment]
> Personally, I'd opt for the latter: removing the Subscribe Block entirely. If someone is already receiving an email notification, I'm not sure why they need to see the Subscribe Block.

Upon further reflection, this is the obvious fix to me 😁 

Created a patch with D83354-code

**Comment by danielbachhuber** [comment]
Subscribe Block is removed from notification emails with r248207-wpcom
