### ISSUE TITLE
Error when removing Timeline Block Background color

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#63626]
### Quick summary

When removing the background color from the Timeline block, an error is showing in the console and the block only shows the "Attempt Block Recovery" message. 

### Steps to reproduce

1. Add in a Timeline block
2. Go into a Timeline Entry child block settings and press "clear" to remove the background color from the block.

![Markup on 2022-05-14 at 15:57:57](https://user-images.githubusercontent.com/24914028/168414735-a0541f2b-0ef5-4673-bdc0-3c5e1604a74b.png)

3. Save draft.
4. Reload page.

### What you expected to happen

I don't think this block should have a background color by default and I would expect that we can remove the background color if needed.

### What actually happened

When saving the change, an error is shown in the console.

![Markup on 2022-05-14 at 15:52:51](https://user-images.githubusercontent.com/24914028/168414566-56ce8d63-8694-4a62-ada8-fdd4cf67b5e2.png)

```
Block validation: Expected attributes  
0: Array(3) [ "style", "background-color:#eeeeee", true ]
1: Array(3) [ "class", "wp-block-jetpack-timeline-item", true ]
length: 2

​instead saw  
0: Array(3) [ "class", "wp-block-jetpack-timeline-item", true ]
length: 1
```

### Context

5212968-zen

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround that I found was to add in a background color to match the site editor, but I think a better solution would be, to be able to clear the background color if desired.

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ - _no timeline block in self-hosted_

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated issue on **Simple**, **AT**, and **P2** following the exact same steps outlined above. Timeline block looks fine after removing the bg color from the "Timeline Entry" child block, but if you save as draft and refresh the page, the block shows `This block contains unexpected or invalid content`.
- Recovering the block restores the default background color.
- No **Timeline** block on my self-hosted site.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by danielbachhuber** [comment]
## Reproduction steps

I was able to reproduce this issue in my local WordPress environment with the Editing Toolkit plugin installed:

1. Add a Timeline Block to my post:

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/36432/176558602-8e407c3f-8d67-461c-b9a4-c1362f9e68ca.png">

2. Clear the default Background Color (`#eeeeee`) on the Timeline Entry Block:

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/36432/176558699-bf07b8b2-b65d-4e24-9615-23f4eafc5fb5.png">

3. The Timeline Entry Block background is initially transparent as expected:

<img width="1518" alt="image" src="https://user-images.githubusercontent.com/36432/176558746-7f6549a6-3972-4dff-977f-b3d371d4c276.png">

4. However, when you save the post and refresh the page (or switch to Code mode and switch back), the Timeline Entry Block ends up as crashed:

<img width="1910" alt="image" src="https://user-images.githubusercontent.com/36432/176558962-9129c652-4e76-4a14-9233-fa11698c5e76.png">

## Technical analysis

The problem stems from an unfortunate anachronism of how Gutenberg's `default` value works for attributes:

1. If the `background` attribute _is not_ present for the block, Gutenberg use the `default` value. This default value is then injected on the `style=""` attribute of the `<li>` element, but **is not** added to the serialized JSON:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/36432/176559667-2845ac16-9673-4e63-838b-dfc5fdd3c451.png">

2. Clicking 'Clear' removes the `style=""` attribute, and the block's runtime memory of `background`, but doesn't include any attribute in the serialized JSON:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/36432/176559876-6b3f6d6c-edf1-4ebb-897c-c374bf3f3c9b.png">

3. **Thus**, when the Block Editor is loaded again:
 * Gutenberg _expects_ to see `<!-- wp:jetpack/timeline-item -->` and `<li style="background-color:#eeeeee" class="wp-block-jetpack-timeline-item">`.
 * Gutenberg _actually_ sees `<!-- wp:jetpack/timeline-item -->` and `<li class="wp-block-jetpack-timeline-item">`
 * Gutenberg crash.

We can't simply remove the `default` value for `background`. Because the `default` value isn't stored in the JSON-serialized data:
* The background color would revert to transparent the next time the block is loaded in the block editor.
* Any existing Timeline Entry Blocks without a `background` JSON attribute would be crashed the next time they're loaded in the Block Editor (because of the inverse of the problem above — the block editor would expect to see `<li class="wp-block-jetpack-timeline-item">` and actually see `<li style="background-color:#eeeeee" class="wp-block-jetpack-timeline-item">`).

Funny enough, I've actually run into this problem before! My issue search foo is failing me, so I can't figure out whether there's an existing issue on the topic in the Gutenberg repo.

**Comment by danielbachhuber** [comment]
The best possible "fix" I can think of is to store 'transparent' as the `background` when the color is removed: https://github.com/Automattic/wp-calypso/pull/65104

Very open to other ideas!

**Comment by danielbachhuber** [comment]
Based on @p-jackson's [extensive research](https://github.com/Automattic/wp-calypso/pull/65104#issuecomment-1170735113), solving this with two changes:

- [x] Resetting to the default color when the user clicks "Clear" https://github.com/Automattic/wp-calypso/pull/65107
- [x] Adding 'Transparent' as an option to the color palette.

I haven't found a formal API for the latter, so started a Slack thread: p1657053522061869-slack-C45SNKV4Z

**Comment by danielbachhuber** [comment]
For lack of a formal API, I've created https://github.com/Automattic/wp-calypso/pull/65266 (and https://github.com/WordPress/gutenberg/issues/42170 for discussion)

**Comment by danielbachhuber** [comment]
The UX is a little convoluted, but the user will shortly be able to apply transparency with this approach:

![image](https://user-images.githubusercontent.com/36432/179061780-5f9171f5-5324-4405-bad5-a5e5bcf75782.png)

The UX will hopefully be improved with https://github.com/WordPress/gutenberg/issues/42170
