### ISSUE TITLE
Stepper: verify siteSlug belongs to logged in user

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#63687]
We should verify that the user has the capability to manage the site in siteSlug. 

If the user cannot edit redirect them to `/start`.

**Comment by sixhours** [comment]
We need to do the same for the Anchor flow. Maybe worth creating a shared hook?

**Comment by andres-blanco** [comment]
Sure! It could then be used from the [`userAssertConditions`](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/site-setup-flow.ts#L347)  callback on both flows 👍

**Comment by andres-blanco** [comment]
@sixhours I've added the hook. I am not so sure how to add tests to it, do you have any suggestions?

**Comment by sixhours** [comment]
> I've added the hook. I am not so sure how to add tests to it, do you have any suggestions?

Hurrah, I'll add that to the Anchor flow today!

I think to test we'd need to set up a mock state with a user object that has permissions for a mocked site ID, then pass it to the hook. Might need to set a false for `isRequestingSites` in the mock, too...

**Comment by sixhours** [comment]
I realized as I was testing #63976 that Anchor needs something slightly different; we don't have a site object at any point in the flow, so there's no point in checking if the user is authenticated to the site. 

But Anchor probably should have a mechanism for re-routing users who are not logged in to the `login` step. I can't seem to use `useAssertConditions` for this case because it's not a straightforward redirect and I *don't* want to run that logic on the `login` step itself or we'll get an infinite loop. Bailing out if we're already on the login step breaks the rules of hooks.

Since it's a tiny flow, I think I'll just add this logic to the steps individually for now.

**Comment by andres-blanco** [comment]
> I realized as I was testing #63976 that Anchor needs something slightly different; we don't have a site object at any point in the flow, so there's no point in checking if the user is authenticated to the site.
> 
I didn't realize that this would not be usable in the Anchor flow, but now that you mention it, it makes sense. 

> But Anchor probably should have a mechanism for re-routing users who are not logged in to the `login` step. I can't seem to use `useAssertConditions` for this case because it's not a straightforward redirect and I _don't_ want to run that logic on the `login` step itself or we'll get an infinite loop. Bailing out if we're already on the login step breaks the rules of hooks.
> 
> Since it's a tiny flow, I think I'll just add this logic to the steps individually for now.

Yep, definitively you don't want to add this to the login screen.
