### ISSUE TITLE
Blog Posts Block: posts don't respect the grid

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#63699]
### Quick summary

Blog Posts Block displays the posts after 14th out of the grid. 

### Steps to reproduce

1. Add Blog Posts Block
2. Set it to display in grid and at least 15 posts

### What you expected to happen

All posts show in grid.

### What actually happened

Posts are in grid in the editor but in the preview and published page only 14 displays in the grid, the rest is in one column list. 

### Context

35517890-hc /  5220599-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Checked three themes, it was present in all. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by zdenys** [comment]
One workaround is to use [Latest Posts Block](https://wordpress.com/en/support/wordpress-editor/blocks/latest-posts-block/) or [Query Loop Block](https://wordpress.com/en/support/full-site-editing/theme-blocks/query-loop-block/). 

I mentioned that to the user in 5220599-zd-woothemes

**Comment by poeticabdul** [comment]
>One workaround is to use [Latest Posts Block](https://wordpress.com/en/support/wordpress-editor/blocks/latest-posts-block/) or [Query Loop Block](https://wordpress.com/en/support/full-site-editing/theme-blocks/query-loop-block/).

User says the workaround didn't work. The same issue happens for these blocks too.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested the Blog Posts block on simple and AT and was not able to recreate this issue. All posts load in the grid as expected.
- Tested this with @cuemarie, testing notes here: p1654116132153659/1654113263.092899-slack-C01UW7SB411 

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - Since we were not able to replicate this issue with the Blog Posts block, I would recommend following up with the user to troubleshoot this further, such as testing for a theme or plugin conflict or testing with different infinite scroll settings.
