### ISSUE TITLE
Chrome: Not able to hide welcome popup / tour

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#63765]
### Quick summary

Each time user opens a post editor they get this welcome popup. We tried to skip, turn off, minimize.

### Steps to reproduce

1. Visit editor
2. close / skip / minimize welcome popup
3. refresh

### What you expected to happen

Popup is still there. 

### What actually happened

Popup doesn't appear after closing.

### Context

5223791-zd-woothemes

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

Chrome, another HE didn't see it in Firefox

### Reproducibility

Consistent

### Severity

One

**Comment by nicolynramos** [comment]
Another report: 5228082-zen

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to replicate issue.
- Also SSP'd into OP user's site in Chrome, and could not replicate there either following the steps above

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - So far I'm unable to replicate this issue. If you'd like to reopen the bug, let us know the steps we can take to replicate the issue.
 - From these tests, the issue seems specific to these users (perhaps devices, or chrome versions/cookies settings?) rather than a bug.

**Comment by daria2303** [comment]
Hi there, while in 5223791-zd-woothemes it is gone, in 5228082-zd-woothemes I am still seeing it. Maybe we could check it again?

https://user-images.githubusercontent.com/11535091/171617700-4046e7d0-f769-4cf6-b238-277c2183d753.mp4

**Comment by ClassicRKR27** [comment]
I've got another report here:

- [ ] 17541658-hc

**Comment by danielk-am** [comment]
Encountered here 35740447-hc. I have tested this on Chrome which is still showing the modal after clicking on close and refreshing the page.

**Comment by daria2303** [comment]
I am reopening it as there are more cases.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on Self-hosted - N/A

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested with the site from 5228082-zd-woothemes and I could recreate on the most recent post in a support session, but the welcome popup did not appear on all posts. 
- I tested on the same site with SSP. I clicked Skip to dismiss the welcome, exited the editor, and when I returned to the post it no longer appeared. However, if I waited a few minutes or refreshed the dashboard before returning to the post, the welcome popup appeared again.
- I created a new WordPress.com account and clicked Skip to dismiss the welcome in the editor. I exited the editor, and when I returned to the post it no longer appeared. Refreshed the dashboard before returning to the post, and the welcome popup did not reappear. Could not replicate the issue.

📌 ACTIONS
- Await author feedback

📌 Message to Author
 - Can you please share steps to replicate this on a test site? So far the comments only show individual user reports and I could not replicate with a different account.
 - I edited the original report to remove the video, since it showed internal tools and a username. 
 - Also noting that I tried to edit [this comment](https://github.com/Automattic/wp-calypso/issues/63765#issuecomment-1144744666) to update ticket format to link to ticket instead of an unrelated GitHub issue, but it didn't work.

**Comment by jamiepalatnik** [comment]
Noting that this issue might be related: https://github.com/Automattic/wp-calypso/issues/64324
Asked about this here: p1655391908616619-slack-C01UW7SB411

**Comment by jamiepalatnik** [comment]
Closing in favor of this issue: https://github.com/Automattic/wp-calypso/issues/57660
See Slack discussion for reference: p1655391908616619-slack-C01UW7SB411
