### ISSUE TITLE
Ads Block: WordAds not resizing on mobile device. 

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#63798]
### Quick summary

Horizontal banner ads are breaking mobile view of website in Geologist theme. I also see open issues related to Dara and other themes about this. The user here seems to have added the ads via Ads block. 

### Steps to reproduce

Seen on user website 

### What you expected to happen

Horizontal ads should not appear on mobile, or at least they should not break the layout

### What actually happened

Check the screenshot 

### Context

35527803-hc

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

The theme here is Geologist, I see open issues related to Dara and one more.

**Comment by nagpai** [comment]
The workaround seems to be using this option to disable ads in mobile 
![image](https://user-images.githubusercontent.com/4162931/169205342-f034e35f-6e7d-472a-bd24-d020f7dd40b6.png)

I wonder why the description of the block shows as [object Object] .. something is off.

**Comment by nagpai** [comment]
maybe related 
https://github.com/Automattic/themes/issues/5619

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- So far I'm unable to test this thoroughly as I don't have a test site with active WordAds. Working on it :) 
- I do see the `[object Object]` language on the Ad block on a test site though: 

<img width="550" alt="screenshot" src="https://user-images.githubusercontent.com/27249804/171508577-eff4add3-40bf-4dd8-bbff-488d3305d48c.png">

📌 ACTIONS
- Await author feedback

📌 Message to Author
 - @nagpai - your screenshot of the steps to replicate did not attach. Can you clarify the steps to replicate the issue?
 


---

@Robertght This appears to me to be the same issue as https://github.com/Automattic/themes/issues/5619, would you agree? I wonder if this is issue is a themes issue, or perhaps related to WordAds in general.

Also seeing similar reports here: 
- https://github.com/Automattic/wp-calypso/issues/57585
- https://github.com/Automattic/themes/issues/4006

**Comment by nagpai** [comment]
Sorry about the late reply here. It is difficult for me to reproduce the issue now. To describe how it looked. - A horizontal banner ad stretched the width of the website on responsive mobile view and pushed the actual website outside the viewable screen. 

In other words, the block should not show rectangular wide ads on mobile device, else it will cause the layout to break.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Not tested yet

📌 SCRUBBING
- Tested on P2 - No 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - No, I don't have a self-hosted site with WordAds yet

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate this issue. Steps to replicate:

1. Enable WordAds
2. Add Ad block to editor with the Leaderboard ad format selected
3. View site

**Results on a simple site:**
The ad with the Leaderboard format breaks the layout on mobile. Screenshot: 

![6EFA15CA-59BC-4F43-9256-01D13AE4B09A_1_105_c](https://user-images.githubusercontent.com/30788962/176700494-9fb6bfa1-0654-4760-8ba2-3c44457e0e41.jpeg)

**Results on an Atomic site:**
The ad with the Leaderboard format does not break the layout on mobile, but the ad is cut off. Screenshot:

![D28B9F0C-4AE1-48A0-B6EE-1984ECE8DFFC_1_105_c](https://user-images.githubusercontent.com/30788962/176702435-bfdb52cb-716c-4b06-b1c3-ce067117920e.jpeg)

Tested on multiple themes and was able to recreate on all themes tested, so I don't think this is a theme-related issue. I am wondering if the Leaderboard ad format is known to not work well on mobile, since in the Ad block toolbar there is also an option to select Mobile Leaderboard, which did not have any display issues on mobile.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 Message to Author
 - I removed the broken screenshot link from the original report.

**Comment by youbrokesomething** [comment]
Based on the conversation here: p1659046452765739-slack-C029FQX6U
This behavior is a known WordAds experience that Ads do not resize for mobile. It is recommended to use a smaller sized ad for a better mobile experience. It may be a good idea to open a feature request with WordAds if this is something many customers want.

Closing this ticket for now.
