### ISSUE TITLE
Multiple enclosure tags in RSS feed

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#63801]
### Quick summary

The user can't submit their RSS feed to iHeart Radio as the RSS feed has multiple enclosure tags for the same file.

This is causing the feed to not validate - https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frodgermarion.com%2Fcategory%2Fmodern-radio-adventures%2Ffeed%2F#l72

The feed is here - https://rodgermarion.com/category/modern-radio-adventures/feed/

In the feed we can see 

<img width="1446" alt="Markup 2022-05-19 at 08 38 01" src="https://user-images.githubusercontent.com/13706336/169239101-c4dd91fa-186b-43c1-91a4-6769cb10af0a.png">
 

### Steps to reproduce

I can't reproduce it on a test site but the site is a premium plan site, so there is no additional code or plugins. 
The only thing out of order is the theme which is retired. Everything else looks good.

### What you expected to happen

The RSS feed to validate

### What actually happened

The feed doesn't validate.

### Context

- Premium Plan
- Retired theme - Connections by Patricia M&#252;ller
- They have set up the podcast settings correctly on their site via Writing-Podcasting
- The feed is using our generated feed
- Premium

### Simple, Atomic or both?

Simple

### Severity

One

### Workaround details

On AT sites there used to be this option to manually edit the tags as a workaround. However, this site is a Premium plan site.

**Comment by danielbachhuber** [comment]
> The user can't submit their RSS feed to iHeart Radio as the RSS feed has multiple enclosure tags for the same file.

To provide a little clarity, there are five separate validation issues:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/36432/169301202-32a3539a-d2c1-4385-818c-21bb2691c978.png">

"multiple enclosure tags" _may_ be the validation issue blocking submission, but the other validation issues may be problematic too.

"multiple enclosure tags" seems like it has some longstanding history: https://core.trac.wordpress.org/ticket/1197#comment:4

Notably, for the blog in question, I'm not sure why multiple `<enclosure>` elements are added when there's only one audio player in the post.

It seems like potential actions could be:
1. Debug why multiple `<enclosure>` elements are added when there's only one audio player in the post. If we can fix it, do so, report back to the user, and have them try to submit again.
2. If resolving multiple `<enclosure>` elements doesn't allow submission, strip the unsupported `<amp-fit-text>` and `<audio controls>` from the feed, report back to the user, and have them try to submit again.

**Comment by metabreakr** [comment]
According to the user, removing `<amp-fit-text>` removed one validation error, however they still cannot submit to iHeart. 

Using a different validator: https://www.castfeedvalidator.com/?url=https://rodgermarion.com/category/modern-radio-adventures/feed/

<img width="1096" alt="Screen Shot 2022-05-19 at 2 52 49 PM" src="https://user-images.githubusercontent.com/39252765/169402697-a0221ea2-4c4b-453f-8569-466259f757e2.png">

```
WARNING: Found 9 items with multiple enclosures. Only one is allowed per item.
```

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
Not able to replicate on another testing site but observable on reported site

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by danielbachhuber** [comment]
I debugged the multiple enclosure tags in RSS issue a bit today.

On the user's site, multiple `<enclosure>` tags are added to the feed `<item>` because the post in question (https://rodgermarion.com/2022/05/12/the-case-of-the-silver-screen-horses/) has multiple `enclosure` post meta entries. This core code behaves as expected: https://github.com/WordPress/wordpress-develop/blob/2648a5f984b8abf06872151898e3a61d3458a628/src/wp-includes/feed.php#L459-L498

The unexpected behavior is that there are multiple `enclosure` post meta entries. I'm not sure how this is happening, and haven't found a way to reproduce it yet.

**Comment by danielbachhuber** [comment]
To move this forward, I:
1. Created a WP-CLI command for removing the duplicate `enclosure` post meta entries: D82453-code
2. Ran the WP-CLI command on the user's site for the posts in their podcast feed.
3. Reported back to the user on a new ticket: 5293351-zd-woothemes

Closing the issue until we have steps to reproduce the root cause of multiple `enclosure` post meta values being added.
