### ISSUE TITLE
Read More block not displaying.

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#63843]
I'm reporting this issue here since I was not able to replicate it on a local WP install (WP 5.9.3, Gutenberg plugin 13.2.2)

#### Steps to reproduce

1. On a site running TwentyTwentyTwo theme create a page and add a Query block.
2. Add a Post title, Post Content, and a Read More block. Save and preview.
3. Note the "Read more" link is not displaying on the front end.
4. Replace the Post Content block with the Post Excerpt block and configure the built-in "Read more" link. Save and preview.
5. Note the "Read more" link included in the Post Excerpt block is being displayed as expected.

Here's the Query block code I used:
```
<!-- wp:query {"queryId":0,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:post-title /-->

<!-- wp:post-excerpt /-->

<!-- wp:read-more {"content":"Keep reading!","linkTarget":"_blank"} /-->
<!-- /wp:post-template -->

<!-- wp:query-no-results /--></div>
<!-- /wp:query -->
```

#### What I expected
I expected the "Read more" block to display on the front end, as it does in the editor.

#### What happened instead
The "Read More" button is not displayed on the front end.

#### Screenshot / Video
Here's a quick video of the issue:

https://user-images.githubusercontent.com/18581859/169452778-dde3dc50-5527-4807-bd6a-4c0989551d10.mp4

**Comment by arunsathiya** [comment]
Quick note that I see the same behavior on a simple site with Gutenberg 13.2.2:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/18581859/169455818-fd69aaa5-b38a-4cd8-b4df-2a308c3d5729.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/18581859/169455843-a9913e04-842a-46f5-9f89-428e682b8e3d.png">

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
I'm not able to replicate this anymore so it might have been fixed in a recent release 
Using the TwentyTwentyTwo theme, in the Editor and on the live preview :

<img width="1551" alt="Markup 2022-06-03 at 08 47 44" src="https://user-images.githubusercontent.com/83325600/171867395-185a46b1-0db4-43ac-846e-fd25c7a2cacd.png">
<img width="1068" alt="Markup 2022-06-03 at 08 48 15" src="https://user-images.githubusercontent.com/83325600/171867404-46f961f9-a6c0-4ebe-b756-cd354f2196e8.png">

📌 ACTIONS
- Marked as Triaged 
- Closed as no longer relevant, please reopen if issue persists
