### ISSUE TITLE
"Classic" dashboard view is not persistent

### ISSUE THREAD

**Issue by hlashbrooke** [Automattic/wp-calypso#63841]
### What

Dashboard pages in Calypso have an option to switch between the "Default" and "Classic" views. The "classic" view shows you the admin page as it displays in WordPress core, without Calypso. This is a great feature, but the you have to do it on every page where you want that "classic" view. This would be greatly improved if there was a persistent setting you could enable that would force the "classic" view throughout the dashboard until you opted to switch back to "default".

As a side note, I'm uncomfortable with calling the native view “classic” and it makes me sad to see that we do - it carries the implication that the view is old and dated, even though it's still very current in WordPress. 

### Why

This would make a much smoother UX for people who prefer the native WordPress dashboard ("classic") over the Calypso version - instead of having to switch on many pages they could set it as one persistent, global option for themselves.

### How

When someone select the "classic" view perhaps have an alert box pop up that asks if they would like to keep that setting across page navigation. The same question can pop up if/when they select "default" again.

**Comment by BogdanUngureanu** [comment]
Hi there, the first iterations of the Viewer (or Quick switcher) acted on a global level. However, this was considered a limitation and we opted for a more flexible approach where users can configure the option for each section. 

This was needed because there's a disparity between Calypso and WP-Admin screens(some features were in Calypso and some in WP-Admin), forcing the users to switch between versions a lot of times.

I guess that we could in theory have some kind of checkbox that says something in the lines of "Choose this screen for all sections of this site".

As for the UI naming, I know we had a discussion about it (we had different naming options before choosing this one) but I can't seem to find it anymore. :(

cc @mmtr (Miguel is currently AFK).

**Comment by zachspears** [comment]
Since the Quick Switcher was organized this way initially and caused additional issues and usability problems for users, I am going to go ahead and close this Feature Request. Thank you for submitting. :)
