### ISSUE TITLE
Domain registration activation causes admin to break during DNS propagation

### ISSUE THREAD

**Issue by becdetat** [Automattic/wp-calypso#63845]
### Quick summary

I created a new site last week (via WooCommerce.com, but I believe this would apply to any WordPress.com site). As part of the creation process I registered a new domain. After getting through onboarding I ended up at ___.wordpress.com/wp-admin/... and was able to start configuring the new site.

Part-way through this I started getting redirected to the new domain - ___.store/wp-admin/... I figured that the domain had been registered, however it wasn't available to me yet, I'm assuming because DNS hadn't propagated. The end result was that I was unable to use the site for about 30 minutes as there was no way to get back to ___.wordpress.com - it would continue to redirect to the new domain.

This was frustrating to me and I can only imagine how frustrating it would be to a user that doesn't know about DNS.

### Steps to reproduce

1. Go to WooCommerce.com
2. Create a new site
3. Register a new domain
4. Continue to site admin
5. Hang around in admin for a while, configuring the site

### What you expected to happen

I explored that a bit in my post on the experience - pbIJXs-1MS-p2. 

- At the very least the site should be able to detect that delegation hasn’t happened yet on the user’s machine and keep from redirecting

- Domain registration processes shouldn’t break admin while you’re using it
- There is no indication of what is happening with your domain registration after paying for it
- There should be a message during setup, after payment, clearly setting expectations for what will happen “in the next 30 minutes” for example
- After getting in to admin, there should be an extremely visible notice indicating that the domain isn’t available yet, that it’s still processing, and that the site is temporarily available at ___.wordpress.com. The very first thing most people are going to do after buying a $800 web site is to try and access it to see what it looks like. Make sure they know where to go and why.
- Push notifications should be displayed as the domain is registered and configured
- The admin site should never just stop working – there needs to be a better way of transferring from ___.wordpress.com to the custom domain during delegation. These aren’t web designers building a site and registering a domain, these are small business owners building their own store, should never need to ever know about DNS or how delegation works.

### What actually happened

The site stopped working for around 30 minutes, I assume while DNS was propagating

### Context

P2 post here - pbIJXs-1MS-p2

### Simple, Atomic or both?

Atomic

### Browser, operating system and other notes

Chrome, MacOS

**Comment by zachspears** [comment]
Unable to reproduce the issue directly, but I did have some interesting findings. 

- First, after activating the site I went to make it atomic using Hosting Configuration. I wanted to see if it would use the domain prior to installing WooCommerce. I was stuck waiting for the Atomic switch for several minutes. This could be a related/separate bug but I will wait and see if anyone else sees the same issue. 
<img width="1032" alt="Screenshot on 2022-06-03 at 00-51-15" src="https://user-images.githubusercontent.com/10124024/171804133-a338c608-4428-4de2-b7b5-c1fa9d92f1f6.png"> 
While stuck here I was unable to click on anything and had to close the tab out and access my site again directly. 


- Once I was able to activate WooCommerce the site switched from using the .wpstaging.com address to my purchased one. Previously it had only used the .wpstaging.com address since my domain was not ready. After the switch, I was still able to edit my site just fine, but I cannot say with confidence that this is because WP knew the domain was ready to go, and not that I was simply DNS lucky.

**Comment by inaikem** [comment]
Marking as triaged and bumping along to get Atomic eyes-on.

**Comment by cometgrrl** [comment]
@Automattic/reactor Pinging y'all to make sure this is on your radar.

**Comment by JoshuaGoode** [comment]
Overall, this issue has been off/on for WPCOM for some time.  For both Simple and Atomic. It just impacts Atomic a bit more since a broken domain will break a site's Jetpack connection and, in turn, site management.  

Jetpack connections power everything from the ability to edit a site down to domains and billing management.

* https://github.com/Automattic/wp-calypso/issues/49898
* https://github.com/Automattic/wp-calypso/issues/63210
* https://github.com/Automattic/wp-calypso/issues/49899
* https://github.com/Automattic/wp-calypso/issues/48746


The issue here is that the custom domain is being made primary before it has had a chance to propagate down to the end-user and the Jetpack connection is left temporarily broken. 

An extended grace period leaving the .wpcomstaging.com as primary -- accommodating if WPCOM can tell the domain is propagated + some extra padding to accommodate end-user networks -- would help.  I think this has had some past iterations where we gave things more time to propagate and perhaps that changed.

Unless/until we provide a way to facilitate site management without a working Jetpack connection, I'd classify this as a domains issue rather than Atomic.  The Atomic site and Jetpack are largely working as expected, it's making the registered domain primary too early that is breaking things. @cometgrrl @inaikem

**Comment by JoshuaGoode** [comment]
cc @delputnam

**Comment by delputnam** [comment]
@JoshuaGoode We already have a check to determine if the domain resolves to WPCOM infrastructure in the job that sets the primary domain.  But obviously we can only check if the domain is resolving from the jobs servers.

Do you happen to have any additional data about this we could use to dial in on a "delay" once the domain starts to resolve for us?  For example, how long is the jetpack connection seem broken for these cases? Does this tend to happen in a certain part of the world? Does it tend to happen on certain networks? For certain TLDS?

Also, do you know how frequently this happens?

And do you know if there are logs we can look at to determine when this type of issue occurs?  (So we could try to see if a fix is actually helping.)

**Comment by delputnam** [comment]
I've created a task for Nomado to address this. We'll update this issue once we've deployed a fix.

**Comment by JoshuaGoode** [comment]
@delputnam  Unfortunately, I don't have data at the moment.  It happens from time-to-time in terms of escalations Reactor receives but is largely dependent on network conditions at the time of propagation.  

I don't believe it occurs all that often, though.

Jetpack seems to be a bit more finicky when it comes to propagation.  

We've seen many cases where WPCOM seems to recognize the domain as being accessible but Jetpack doesn't. Upon further inspection, there are often a few random name servers still propagating.   

Until Jetpack can connect, the site will remain in a broken state. 

So, I imagine it's a mix of TLD, network conditions..etc


> And do you know if there are logs we can look at to determine when this type of issue occurs? (So we could try to see if a fix is actually helping.)

I'll have to dig into that. The first thing that comes to mind would be Jetpack connection error logs but we'd need it in the context of newly registered domains.  Perhaps our Jetpack friends have more on what we can look for.

**Comment by kriskorn** [comment]
I have just tried to reproduce this issue, but was unable to.

**The Setup**

Registered a totally new site with a `.blog` domain and a Commerce plan. This means that the site will be Atomic from the start and the `.blog` TLD is something that will take time to start working. Once the site was created, it started loading on the wpcomstaging.com default domain. 

After around ~25 minutes, the `.blog` domain was finally activated and the system was smart enough to set it as the primary domain. Considering all of the above, I am going to close this issue for now, as it cannot be easily reproduced. 

Context: pdtR3Z-1Cq-p2#comment-1504 & p1679414671950499-dotcom-reactor
