### ISSUE TITLE
[Emails] [New Post] Adjust post date format based on the site language / date settings

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#63852]
This is a feature request on having the post date formatted depending on the site language / date settings.

Currently, the date is formatted regardless of the site settings as can be seen in the following screenshot:

![Image](https://user-images.githubusercontent.com/25105483/169492754-d08f75ce-a0b7-4832-9695-7ff55386525c.png)

[Suggested in a comment](https://wordpress.com/blog/2022/05/19/your-website-looks-great-so-should-your-emails/#comment-423345)

**Comment by yansern** [comment]
The only possible route is using the site's date time format, with the user's language settings applied, which can be weird, but at least the option is offered.

This is because there is no date time settings on the user level, only on the site level.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/1287077/196729863-9e2e05a2-0298-487d-9cd7-9cd389634744.png">

**Comment by TimBroddin** [comment]
Fixed in D135727-code

**Comment by ivan-ottinger** [comment]
D135727-code is now in production.
