### ISSUE TITLE
Stats: Maldives do not appear in the right location on map

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#63899]
### Impacted plugin

Jetpack

### What

Maldives show in the wrong location.

### How

Suggested in #5233963-zen where it's stated: In the Jetpack status page (County maps), the Country (Maldives) is shown in a terrible way.

![SAVE_20220522_061953](https://user-images.githubusercontent.com/2545184/169695934-c55269d6-c325-451a-9c80-9c30f9088885.jpg)

**Comment by jeherve** [comment]
Transferring this to the Calypso repo, where the map lives.

**Comment by cuemarie** [comment]
Checked this out on the site of the user who reported it, and it looks like we've removed the incorrect location for the Maldives since this report:


https://github.com/Automattic/wp-calypso/assets/27249804/cc39bebe-2eed-4c42-8aca-7a94a997623e

The Maldives don't appear when hovering over the map at all now (t_hese islands very small and would be difficult to achieve in the UI_), so that seems more appropriate than having them appear in the wrong place. 

Closing this out!
