### ISSUE TITLE
Post Streak Miscalcuation

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/wp-calypso#63967]
### Quick summary

A user is getting two conflicting "post streak" notifications in the WP.com reader: 700 days without missing a day, and then 480 days. They're confused by that and believe they've been publishing for 700d non-stop.  Does deleting posts from the past year affect the streak calculation?

### Steps to reproduce

1. Start a posting streak. 
2. Be notified of a posting streak 
3. Delete a post after publishing it. 
4. Observe the streak number, does it include the post that was published but later deleted?

### What you expected to happen

The latest notification should read "You’re on a 700-day streak...."

### What actually happened

The latest notification lists "You're on a 480-day streak...." 

### Context

Customer Report: 5240301-zd-woothemes

### Simple, Atomic or both?

Simple

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I followed the testing instructions and tested on a test site that had a 5-day streak. I deleted the last post from the streak, then checked the notification. There was no change to the notification. It still reads "You're on a 5-day streak".

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - Since I'm not able to replicate this, I would recommend following up with the user to troubleshoot this further. If you can recreate this issue on a test site or if there are other user reports, please feel free to reopen with more details.

**Comment by scruffian** [comment]
I'm seeing this on haiku.blog. I was on a 2600 day streak and its suddenly gone down to 8! I have checked all the posts and I can't find a gap. Feel free to look at my site for an example. Maybe I set a post date wrong?!

**Comment by cuemarie** [comment]
📌 ACTIONS
- Await author feedback

📌 Message to Author

Hey @scruffian , thanks for re-opening this. Are you still seeing the low-count streak on your site?

According to internal tools ( more here: p7DVsv-bN3-p2 ), your `haiku.blog`, is currently on day **2803** of it's streak, stretching all the way back to `2015-03-04` (wow!). I'm curious if you're still seeing a low number, or if your streak has returned. Can you let us know?

**Comment by scruffian** [comment]
I fixed it. The problem was that somehow the mobile app created a post without an author.

**Comment by cuemarie** [comment]
@scruffian Great to hear! And thanks for sharing what the issue was - that will be a great thing to check if we encounter future reports like this 👍
