### ISSUE TITLE
 Reviewing New Post E-mail Template 

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/wp-calypso#63982]
A few details reviewing a real case of an email notification from this post: https://wordpress.org/news/2022/05/arturo/

- [ ] We may need to check the text widths on various devices. For me on large iphone (12 max) it’s too narrow, barely fit ~5 words per line.

![image](https://user-images.githubusercontent.com/25516611/170132553-d9dbf51d-e9d0-46ab-8419-7224f02e2bd8.png)

- [ ] There’s a small hiccup in how a button renders so close to the previous quote block. Not sure if it’s on us. It also renders a raw style (color, radius). 

![image](https://user-images.githubusercontent.com/25516611/170132650-515b6f3a-9995-4654-9f78-b8789021d2d5.png)

- [ ] We probably need to revise the footer, it blends too much, and the apps don’t have context of what you get/download.

![image](https://user-images.githubusercontent.com/25516611/170132610-edb3bef5-3b07-48e5-b443-c372f1d5afc1.png)

**Comment by mashikag** [comment]
1. Text widths should now be fixed with the following issue https://github.com/Automattic/wp-calypso/issues/63819
2. The following issue was created to track the button block top margin problem: https://github.com/Automattic/wp-calypso/issues/68587
3. The footer is being revised by `wordpress-mobile-team-leads-group` team.
