### ISSUE TITLE
Unable to delete tags from contributor posts in editor

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#64044]
### Quick summary

Site owner is unable to edit contributor posts in editor to remove unwanted tags.

### Steps to reproduce

1. Start on Posts page in Calypso.
2. Open post in block editor.
3. Click on X to remove unwanted tag in right sidebar.
4. Click **Update** to save changes.

### What you expected to happen

Tag should be removed from post.

### What actually happened

Tag is still on post.

### Context

Customer report

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

Chrome 101.0 on Windows 10.0.0

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Edit tags with Quick Edit in Classic View of Posts page.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on simple site, AT, and self-hosted. Created post as contributor, then followed steps to remove tag as site owner. Tested removing tags while post was saved as draft, and after the post was published. In all tests, removing tags worked as expected.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - Since I'm not able to replicate this, I would recommend following up with the user to troubleshoot this further. If you can recreate this issue again on a test site or if there are other user reports, please feel free to reopen with more details.
