### ISSUE TITLE
Marketplace: Category descriptions

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#64055]
See this comment for design: https://github.com/Automattic/wp-calypso/issues/63893#issuecomment-1136664229

Category When selecting a category we show more opinionated formatted results header including title, optional description, and number of plugins . I'll need to work on these with marketing but would be nice to set it up now.

- [ ] Add prelim descriptions to each category (then get copy sign off)
- [x] Display them below the category bar on category pages (this bar will be present once https://github.com/Automattic/wp-calypso/issues/63893 is completed)

@SaxonF can add a design with the clear button present, should this be shown on category pages (currently is)

**Comment by allilevine** [comment]
@SaxonF What's the next step to add category descriptions re: [your comment here](https://github.com/Automattic/wp-calypso/issues/63893#issuecomment-1136664229)?

**Comment by SaxonF** [comment]
Some suggestions for prelim content for the most visible categories. For the remaining categories we can hide the description. Let's remove the "clear" button for now when on category pages. We can monitor via Full Story to make sure people are finding their way back to "discover" via categories sidebar or back button

```
Analytics - Tools to help you better understand your site’s visitors and performance.
Booking & Scheduling - Add a fully functionality booking system to your site
Customer Service - Build stronger relationships with your customers by improving how your provide support via your site.
Design - A collection of tools that will give you more control over the design of your site
Donations - Accept and keep track of donations directly on your site
Ecommerce & Business - Everything you need to turn your WordPress site into a powerful online store
Education - Add free or paid educational content to your site in a more engaging way
Top paid plugins - A collection of the most popular premium plugins on offer
Top free plugins - The most popular free plugins to extend your WordPress site
```

**Comment by lsl** [comment]
Need some new ones for:

- SEO
- CRM & Livechat (Replaced customer service)
- Events Calendar
- Social
- Email (newsletter marketing)

But lets start with what we have.

**Comment by candy02058912** [comment]
@SaxonF

> Top paid plugins - A collection of the most popular premium plugins on offer
> Top free plugins - The most popular free plugins to extend your WordPress site

"Top paid plugins" (now "Top premium plugins") and "Top free plugins" [according to the design mentioned here](https://github.com/Automattic/wp-calypso/issues/63893#issuecomment-1136664229):

> Default home/discover page remains the same

~Since there's no design change so I don't think we need to add the descriptions for these two.~

Update: I was able to locate the dedicated "Top free plugins" and "Top premium plugins" page!


We still need descriptions for the following categories:

**Must have (visible categories)**
- SEO
- Events Calendar
- Social
- Email (newsletter marketing)
![image](https://user-images.githubusercontent.com/6586048/185077201-6c890d07-1cb1-449a-a857-c6ac3c31f6bf.png)


Low priority (in the "More" dropdown)
- Security
- Finance & Payments
- Shipping & Delivery
- Marketing
- Photo & Video
- Crowdfunding (Replaced Donations)
- Learning Management Systems (Replaced Education)
- Widgets
- Posts & Posting
- CRM & Livechat (Replaced Customer Service)

It would be nice to have descriptions for the "Low priority" ones since the visible categories seem to be changing quite often. Judging from that it already looks different than when [the above comment](https://github.com/Automattic/wp-calypso/issues/64055#issuecomment-1208943268) was made, but I may be wrong. It's also okay to just hide the description [per the comment above](https://github.com/Automattic/wp-calypso/issues/64055#issuecomment-1140626607).

I will need the "Must have" ones to finalize the PR. Thanks 🙏

**Comment by lsl** [comment]
Going by slack I think we can ship this with what we have and ignore the rest for now. (There is a follow up design change that can catch the missing ones at that stage.)

**Comment by michaelpick** [comment]
Hi again @vinimotaa 👋 

Connected to the category description labels in #67171 and the [style consistency notes](https://github.com/Automattic/wp-calypso/issues/67171#issuecomment-1237449674) I left there, here's some fresh copy for the above:

## Page headline variations
I've kept this without a subheading, as with the current selection. Let me know if you'd me to riff on some subheadings, too. I think the headline you've picked works as is, but here are some others for coverage (my personal favorite in bold):

- **Flex your site's features with plugins**
- Power-up and flex your site with plugins
- Flex your site faster with plugins
- Reimagine what's possible with plugins
- Go further, faster with plugins
- Plugins take your site further, faster
- Take your site further with plugins
- Meet plugins: a fast, flexible way to take your site further
- Plugins: a fast, flexible way to take your site further

## Must-have premium plugins
{{Note the sentence casing, although an exception could be made for 'Premium Plugins' if we choose to title-case features}}

Subheadings for coverage (personal preferences in bold):

- Jump straight into the most popular plugins on WordPress.com
- Jumpstart your site with the most popular plugins on WordPress.com
- **Get a jumpstart with our most popular plugins**
- Add the plugins our customers use most
- **Add our the best-loved plugins on WordPress.com**
- Check out the plugins WordPress.com users install first
- Jump straight into the plugins our users install first
- Start out with these popular plugins
- Hit the ground running with these plugin essentials
- Start growing your site faster with these popular picks
- Get a head start with these essential plugins
- Grab the most popular plugins on WordPress.com
- Add the most popular plugins on WordPress.com
- Get a head start with the most popular plugins
- Start faster with the most popular plugins
- Dive right in with the most popular plugins
- Start fast with the most popular plugins on WordPress.com
- Snag the most popular plugins on WordPress.com
- **Meet the most popular plugins on WordPress.com**
- Add the most popular plugins with WordPress.com users

## Our developers’ favorites
- Grab the plugins most loved by the WordPress.com team.
- **Get the WordPress.com team's most-recommended plugins.**
- Get on the inside track with WordPress.com developer's favorite plugins
- Add the plugins our developers wouldn't live without
- **Grab the plugins our developers install first**
- Get the inside scoop with these WordPress.com team picks
- Install the plugins the WordPress.com team swears by
- Get a head start with these WordPress.com team picks
- Add these WordPress.com recommended plugins
- **Start fast with these WordPress.com team picks**

## The free essentials

- Start free-as-in-beer with these plugin essentials
- Give your site a boost with these zero-cost essentials
- Add these free plugin essentials to your site
- **Install the very best zero-cost plugins**
- Add the very best free plugins to your site
- **Start out free with these zero-cost plugins**
- **Start out free with these zero-cost essentials**

Breaking out of the verb-led pattern:

- Plugin essentials that won't cost you a penny
- **Essential plugins that won't cost you a penny**
- Powerful plugins at everyone's favorite price (free)
- **Essential plugins. Entirely free.**

## Get started with plugins

- Learn everything you'll ever need to know about plugins, fast.
- Handpicked articles to get you up and running with plugins
- Learn anything and everything about plugins with these quick reads
- Get up to speed on plugins, fast. No experience necessary.
- Learn the ins and outs of plugins, fast.
- Helpful how-to, deep-dive, and quickstart guides to plugins
- **Go further, faster with plugins. With a little help from these guides.**
- Take plugins further, faster. With these how-to articles.
- Learn all about plugins with these guides. In minutes, not hours.
- **Everything you ever wanted to know about plugins. In minutes, not hours.**
- **Our favorite how-to guides to get you started with plugins.**

## You pick the plugin. We’ll take care of the rest.

### Fully managed
Premium plugins are fully managed by the team at WordPress.com. No security patches. No update nags. It just works.

### Thousands of plugins
- From our hand-curated collection of premium plugins to thousands of community plugins. If you can think of it, there's a plugin for it.
- **From WordPress.com premium plugins to thousands more community-authored plugins, we've got you covered.**
- Whatever job you need to get done, there's a plugin that'll make it happen. Draw on our curated collection of premium plugins or thousands of community plugins besides.
- **Whatever you need to get done, there's a plugin that'll make it happen. Pick from WordPress.com premium plugins or your choice of thousands of community plugins.**
- Whatever you need to get done, there's a plugin that'll make it happen, fast.

### Flexible pricing
- **Pay yearly and save. Or keep it flexible with monthly premium plugin pricing. It's entirely up to you.**
- Pay, your way. Save with annual payments or keep it flexible with monthly premium plugins.

---

As always, let me know if I can iterate, further narrow down selections above, or otherwise lend a hand!
