### ISSUE TITLE
Theme Archeo: Site Navigation Block Text Color Doesn't work in Mobile

### ISSUE THREAD

**Issue by annbingle** [Automattic/wp-calypso#64076]
### Quick summary

The user's theme is Archeo. Their Site Navigation is set with Font set to White and Background to Purple. It works great in desktop but not in mobile.

Also, to add to it, they have set the Links color in the Styles section to green. However, in mobile, the  Site Navigation text color is showing in Grey.

I gave them the CSS Code below as a workaround since the preset color isn't working in mobile.

```
.wp-block-navigation:where(.has-background) .wp-block-navigation-item__content {
color:#fff;
}
```

### Steps to reproduce

1. Open the Site Editor.
2. Click on the Site Navigation then click on the Color option under the Block Settings.
3. Set the color for Text and Background and Submenu.
4.
<img width="1312" alt="Screen Shot on 2022-05-25 at 04-32-49" src="https://user-images.githubusercontent.com/40605613/170491889-d8a73211-8175-4d51-897d-9a32d06b3e44.png">

### What you expected to happen

The Menu Text on Mobile should display as white.

### What actually happened

It displays as grey for some reason.
<img width="302" alt="Screen Shot on 2022-05-25 at 04-31-41" src="https://user-images.githubusercontent.com/40605613/170492050-abf61e66-f86b-4c32-98f4-4a1ef36074ae.png">

### Context

35606646-hc

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

The thing is that I tested it on my test site with Archeo and Quadrat and I cannot replicate it. It only happens on the user's site. I didn't ask them to change their theme though as they already have setup the site and the only issue is the menu.

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

I gave them the CSS code for a fix. 

```
.wp-block-navigation:where(.has-background) .wp-block-navigation-item__content {
color:#fff;
}
```

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context: I remember testing this previously in this ticket #5237792-zen. The user confirmed they have some CSS changes and other plugins there that need to be excluded in order to fully replicate the issue. They refused to do so and I don't see any other similar cases.




📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs


📌 Message to Author
 - I'm going to close this, however, if you want more troubleshooting on this, please P2 this on happinessfeedback.
