### ISSUE TITLE
PHP fatal error in Byrne theme on category pages

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#64088]
### Steps to reproduce

In 5247455-zd-woothemes, the user's site, running byrne, has a fatal error on `/category/movies/`:

```
PHP Fatal error:  Uncaught Error: Object of class WP_Error could not be converted to string in /wordpress/core/6.0/wp-includes/class-wp-block.php:255
Stack trace:
#0 /wordpress/core/6.0/wp-includes/class-wp-block.php(241): WP_Block->render()
#1 /wordpress/core/6.0/wp-includes/class-wp-block.php(241): WP_Block->render()
#2 /wordpress/core/6.0/wp-includes/blocks.php(901): WP_Block->render()
#3 /wordpress/core/6.0/wp-includes/blocks.php(939): render_block(Array)
#4 /wordpress/plugins/gutenberg/13.2.2/build/block-library/blocks/template-part.php(132): do_blocks('<!-- wp:group {...')
#5 /wordpress/core/6.0/wp-includes/class-wp-block.php(255): gutenberg_render_block_core_template_part(Array, '', Object(WP_Block))
```

### What you expected to happen

The category page to load without errors.

### What actually happened

The category page was unable to load.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

byrne

### Reproducibility

Once

### Severity

One

### Available workarounds?

No and the platform is unusable

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context. I couldn't replicate this issue on my end or on their site. Also the user hasn't replied since(May 30). 
- I was able to find a previous case with a similar error, but unrelated to this theme: https://github.com/Automattic/themes/issues/5641
- Please reopen if we see other cases.



📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
