### ISSUE TITLE
[Bug]: Installing plugin process allowing to install plugins even after showing prompt to upgrade

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#64116]
### Quick summary

 The plugins Add new page shows to upgrade to Pro plan to install plugins. When I try to install the plugin, it still prompts to upgrade, and when I click on Upgrade to Pro, instead of taking me to the checkout page, it takes me to Manage plugins page and it actually installs the plugin on the site.

### Steps to reproduce

1. Go to My Site → Plugins → Add New page.
2. Try uploading a plugin.
3. It prompts to upgrade to the Pro plan
4. When I click on Upgrade to Pro, instead of taking me to the Checkout process, it takes me to Manage Plugin page.
5. Checking the My Site → Plugins → Installed Plugins page, the plugin was actually installed and activated.

### What you expected to happen

Since the site is atomic already, it shouldn't prompt me to upgrade to the Pro plan. 

### What actually happened

It prompted me to upgrade but still allowed me to install the plugin.

### Reproducibility

Consistent

### Severity

All

**Comment by obenland** [comment]
Did you access that page directly? On my site on a Personal plan there is no "Add new" menu item, only "Plugins" which leads to https://wordpress.com/plugins/[site]

**Comment by obenland** [comment]
@galakhyati Have you had a chance to review this yet?

**Comment by edequalsawesome** [comment]
@obenland I was able to duplicate it -- here's a GIF showing my flow with a Premium plan site:

![2022-06-14 16 04 10](https://user-images.githubusercontent.com/4000628/173678817-2f1b2a00-9924-4901-8ec0-bc46211ead84.gif)

I also didn't need to click on the Upgrade Plan button -- just waiting a few seconds got me past that.

**Comment by marianearchimbaud** [comment]
I was not able to reproduce this. I see a white screen on the Installed plugins section, though. For the record,  the site is indeed atomic:

<img width="1214" alt="Screenshot on 2022-06-14 at 19-33-18" src="https://user-images.githubusercontent.com/72237737/173711826-598cfc52-de2d-48be-a41c-5db685386bcf.png">


<img width="909" alt="Screenshot on 2022-06-14 at 19-26-37" src="https://user-images.githubusercontent.com/72237737/173711668-774e01bc-bc30-4e81-969b-b4e33310326a.png">

**Comment by DustyReagan** [comment]
I'm having trouble reproducing this. @edequalsawesome How did you take your Premium site Atomic? Maybe that's the key to reproducing this issue.

**Comment by supernovia** [comment]
I was also unable to reproduce this. Here's how I tested:
- I used an existing free test site.
- I clicked on Plugins
- Clicked Upload
- Was prompted to upgrade to Pro
- I upgraded to pro
- Went back to Plugins
- Clicked Upload, and while I was warned about the site url changing, it didn't prompt an upgrade.

**Comment by obenland** [comment]
I can't reproduce it either, instead of redirecting after the error message it now shows an error banner at the top right.

However I think we can be a bit smarter about showing the "Installed Plugins" and "Upload Plugins" buttons. They should not be visible if the site doesn't have the MANAGE_PLUGINS and UPLOAD_PLUGINS feature.

**Comment by DustyReagan** [comment]
> However I think we can be a bit smarter about showing the "Installed Plugins" and "Upload Plugins" buttons. They should not be visible if the site doesn't have the MANAGE_PLUGINS and UPLOAD_PLUGINS feature.

That's certainly doable. Perhaps we should redirect traffic to /plugins/upload/ too.

**Comment by DustyReagan** [comment]
This bug is caused by Atomic WPCOM_PURCHASES data being out of sync with WPCOM purchase data. Essentially the Atomic site is seeing an eCommerce and Premium subscription (for example), but WPCOM (the source of truth) is only seeing the Premium subscription.

It’s hard to say what caused the data to become out of sync, but we believe it's due to a race condition where we are updating Atomic WPCOM_PURCHASES before the database has finished updating the purchase record. D82940-code addresses that possible scenario, and hopefully fixes this issue going forward.

Should an Atomic site be found to have out-of-sync purchase data, there is a button in Store Admin to trigger a data sync D83120-code.

**Comment by DustyReagan** [comment]
I did a bit research looking for a fallback syncing hook and came up short. I'm going to go ahead and close this issue believing D82940-code and D83120-code addresses this. Please feel free to re-open if you're able to get a new site into this scenario.
