### ISSUE TITLE
Themes: Some themes missing localized Headstart annotations

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#64194]
Every non-retired theme on WP.com should have an `inc/headstart` folder with a bunch of localized annotations for each of the mag16 languages, but it appears many themes have only `en.json` or English annotations. There should also be `fr.json`, `es.json`, etc. for each theme. This potentially breaks Headstart for the affected themes for all but English sites. 

Example `pub` themes that have localized annotations are Dalston and Bradford.

Example `pub` themes that are missing annotations are Dara and Altofocus.

**To-do's**

- [ ] Use the themes' commit history to find out when/why some localized annotations were removed and document your findings here.
- [ ] If this was a mistake, we need to find a way to restore the missing localized annotations.

As an aside, @themeshaper removed Headstart annotations from the Github themes repo here: https://github.com/Automattic/themes/pull/1908. Maybe a sync script removed them from WP.com when syncing from the Github repo?

**Comment by nelsonec87** [comment]
Some findings:
- The current process for sending the annotations for translation (p6nuNy-IQ-p2) is not being followed correctly (or at all for several themes). 
- The process is pretty "manual", so it's easy to forget or get lost (p1642437768052000-slack-C02AED43D)
- Also, sending the file to linguine is not enough, since they are not sent to translation regularly (p1634719053153500-slack-C02AED43D)
- The email saying the translations are done is not working (334-gh-Automattic/i18n-issues), which is the trigger for the developer to commit the translated files.
- **This project (pxLjZ-6Er-p2) is already working on automating headstart translation (and deployment) process, making it more similar to the theme translation.**

**Comment by blackjackkent** [comment]
@nelsonec87 will follow up with i18n team to see current status of ongoing project related to this; if things are well in hand, we can close this issue.

**Comment by nelsonec87** [comment]
Closing this issue since the headstart translation automation project (pxLjZ-6Er-p2) is about to go live 🥳
