### ISSUE TITLE
Anchor: Add cache-busting to the onboard store when the podcast ID changes

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#64298]
When visiting `/setup?anchor_podcast=[your podcast ID]`, the onboarding store will remember the last input value for the podcast title in favor of the one associated with the `anchor_podcast` ID in the query param.

This means if the podcast ID value changes in the query param, the new podcast title does not get fetched from the API; it reuses whatever is in local storage/the onboard store.

We should probably confirm the podcast title being fetched from the API matches the podcast ID given, and update it when they don't match.

This is an edge-case issue users are unlikely to encounter unless they're creating multiple sites with multiple podcast IDs.

**Comment by nelsonec87** [comment]
I couldn't come up with an optimal solution for this one yet...

We can always use the title from Anchor, but it would generate strange behavior:
- Calypso fetches the title
- I want a different one and change it
- Click continue - the changed title is stored
- Clicking Back would fetch the title again and replace the user input.

The problem is to differentiate the the original title from a different podcast and a custom podcast title the user typed.

One possible solution would be to clear the podcast title in the end of the flow, so it would work correctly for the next site. The problem is that it would _only_ be cleared if the user goes until the end of the flow.

One thought that occurred to me is to move `ONBOARD_STORE` to `sessionStorage` (instead of `localStorage`). This way old data would not be used. But it could have unwanted consequences as well.

**Comment by nelsonec87** [comment]
@sixhours thoughts? :)

**Comment by nelsonec87** [comment]
Closing as it's really unlikely it's gonna affect real users.
