### ISSUE TITLE
Task: Replace videopress_has_required_purchase_for_jetpack_site with feature check

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#64311]
### Details

We should be able to replace that with a feature check for `VIDEOPRESS_UNLIMITED_STORAGE`.

### Related

https://github.com/Automattic/wp-calypso/issues/64309, https://github.com/Automattic/wp-calypso/issues/64310

**Comment by DustyReagan** [comment]
We weren't able to remove `videopress_has_required_purchase_for_jetpack_site` because it contains logic to check previous "upsold" subscriptions for a valid legacy VideoPress plan. However, we were able to refactor it to remove the `videopress_jetpack_has_active_product` function call, the hardcoded date checks, and simplify it a bit for clarity. D82361-code
