### ISSUE TITLE
Convert to blocks converts <div> tags to Custom HTML Blocks

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#64332]
### Quick summary

When using the Convert to blocks feature on the Classic Block, any elements inside of a <div> will be converted to Custom HTML instead of the corresponding block element. This can complicate converting some Classic editor pages into Blocks.

### Steps to reproduce

1. Create a page
2. Insert a Classic Block and add a <div> element somewhere inside of the Classic Block
3. Use Convert to blocks

All elements inside of a <div> will be converted into a Custom HTML block instead of the correct type of block.

### What you expected to happen

A <p> inside of a <div> should be converted to a Paragraph Block instead of HTML code inside of a Custom HTML Block.

### What actually happened

All elements inside of a <div> were converted to a Custom HTML Block.

### Context

Customer report 35701815-hc . Customer noted that after using Convert to blocks, half of the page was in a Custom HTML Block. I noticed that the bottom half of the page was inside of <div>. Using Edit as HTML allowed me to delete the <div> tags. Deleting the <div> tags allowed Convert to blocks to work as expected.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Use Edit as HTML to remove all <div> tags from the Classic Block element. After the <div> tags are removed, Convert to blocks works as expected.

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- **Could not replicate.** Created a Classic Block that contained a heading, text, an image, and text with a link in all test sites, and each one Converted to Block with no issue. Example on AT site: 

https://user-images.githubusercontent.com/27249804/173628335-cc50ac14-c1c4-4b97-b2fb-d2ae416e912f.mov

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - @masperber were you able to replicate the issue in a test environment, or was this unique to the user's site?  There may be something else going on particular to this user's site, rather than a bug. Closing for now, but feel free to reopen if you can replicate the issue - please let us know any further details if so. Thanks!
