### ISSUE TITLE
Site Editor: Block inserter (+) hovering on content

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#64351]
### Quick summary

While using the site editor, the block inserter (+) line appears on top of the content, which makes it difficult to add a new block between other blocks. 

Similar to the issue here: https://github.com/Automattic/wp-calypso/issues/63279 however now it is impacting the site editor. 

https://user-images.githubusercontent.com/21261509/172034606-4819845b-c24b-4ddd-9190-d7b14bda4463.mov

### Steps to reproduce

1. Enable an FSE-compatible theme.
2. Go to the site editor (Appearance > Editor).
3. Add new content with any block.
4. Hover the cursor at the bottom of the block.

### What you expected to happen

 The + icon to be displayed at the bottom of the block.

### What actually happened

The + icon overlaps the block.

### Context

User report: 5271155-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

FSE Themes

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Jaykame** [comment]
Another report here with the same issue happening in Editor: 5278312-zd-woothemes

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- **Could not replicate.** Hey folks! On Simple, AT, and Self-hosted test sites, I was not able to replicate the behavior reported above, where the `+` block inserter appeared hovering over other blocks, rather than between them.  Tested on Twenty Twenty Two, Zoologist, and Appleton.
- Also tried opening the sites mentioned above, and could not replicate the issue there either.
- Example recording from AT test site's Site Editor:

https://user-images.githubusercontent.com/27249804/173636163-037a6e71-b618-4a10-856d-41348f262cc7.mp4

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - @rw-ye and @Jaykame - I was also not able to see this behavior any longer in the user's sites. Both sites have Gutenberg active, which is now on v 13.4, released on June 8 - it's possible that release caught this issue and resolved it already!
