### ISSUE TITLE
Sharing buttons do not work inside Calypso anymore

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#64435]
### Quick summary

The user reached out to us and mentioned that when accessing the site from the dashboard, under https://wordpress.com/view/DOMAINNAME, the sharing buttons do not work anymore.

### Steps to reproduce

1. Access the dashboard of the site.
2. Make sure the sharing buttons are turned on 
3. Access https://wordpress.com/view/DOMAINNAME

### What you expected to happen

To be able to share a post/page.

### What actually happened

I got this:

![image](https://user-images.githubusercontent.com/6737345/172530602-32080216-3b21-4f6e-9d78-f35a0da85566.png)

### Context

5277549-zen

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Use the sharing option outside the dashboard.

**Comment by jamiepalatnik** [comment]
- [ ] User in 5277549-zd-woothemes requested a follow-up when this is fixed.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes, with Jetpack active

📌 SCRUBBING
- Tested on P2 - N/A
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate the issue by following the steps, with the clarification that the Print and Email sharing buttons still work in https://wordpress.com/view/DOMAINNAME. Social media sharing buttons do not. 
- I get the same "refused to connect" error screen on Chrome. 
- On Safari nothing happens when I click the Twitter sharing button.
- On Sarari I get a Go to Facebook link that takes me to a login screen.

📌 ACTIONS
- Marked as Triaged for Quality Squad review.

**Comment by mpkelly** [comment]
Hi @Robertght, I've taken a look at this, and I don't think there is anything we can do about it. There are certain security restrictions in place when you embed another website within a second site, as we do when you go to `/view/DOMAINNAME`, and these are controlled by the site that gets embedded. All social media sites have blocked users from clicking these share buttons when in embed mode. One security issue is clickjacking, which can happen when a malicious actor embeds a webpage into their site and tricks the user into clicking on an invisible button placed above actual content like a share button. This is one reason why the restriction is in place. 

You can read more about that here:

https://owasp.org/www-community/attacks/Clickjacking 

To work around this issue, the user can right-click and open the link in a new tab or use their site directly. 

If you have any questions let me know. If not, I'd be grateful if you would close this issue after communicating with the user. Thanks!

**Comment by lsl** [comment]
Won't fix. We no longer link to this page.
