### ISSUE TITLE
Video not working on Iphone

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#64444]
### Quick summary

The video on the homepage is not displaying on Iphones. 

### Steps to reproduce

Open the site on an Iphone
The site opens fine but is displaying a white area where the video is supposed to be.
An HE with an Iphone was able to replicate this issue, the video works fine on my Android phone

### What you expected to happen

When opening the site I would expect the video to start playing

### What actually happened

When I first enter the main page, the video start icon appears and immediately disappears. The part of the video is white. Then when I press that part, the video opens. In that part, the video should play or appear automatically.
- quote from user

### Context

User is on a Premium plan, and used the video block to add the video. They tested different settings but that didn't change the outcome. We also tried clearing the browser cache and turning off AMP, but neither changed the outcome. 
5280098-zd

### Simple, Atomic or both?

Simple

### Browser, operating system and other notes

The user is using an Iphone 11, they tested in Safari, Brave and Chrome browser. 

### Reproducibility

Intermittent

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority - No
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested visiting the user's site from report on an iPhone. There is a white space where video should be in the AMP version, but when you click to view the full site, the video loads as expected.
- Video loads as expected when testing with other sites.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - Since I'm not able to replicate this, I would recommend following up with the user to troubleshoot this further. If you can recreate this issue again on a test site or if there are other user reports, please feel free to reopen with more details.
