### ISSUE TITLE
[Spike] Generated design picker: Improve iframe preview CSS overrides

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64518]
## Description
Currently, the generated design picker displays previews in an iframe that is auto-resized based on its embedded page's height. Note that this is only for the desktop view. This creates a tricky situation where if the embedded page's layout style uses `vh` as unit, the reference will be to the iframe and not the user's browser viewport. To get around this issue, we currently override some CSS styles by replacing `vh` with `px`.

From the conversation thread: https://wp.me/pdtkmj-ba#comment-307, there's room for improvement to this approach.

## Acceptance Criteria
Ideally, we want the design preview to stay faithful as much as possible to the original layout. This spike is to explore ways that we can improve the `vh` → `px`conversion. At the moment, we are replacing it with a fixed value of `height: 700px`.

**Comment by iamtakashi** [comment]
Thanks for looking into this issue. Much appreciated!

> This spike is to explore ways that we can improve the vh → px conversion.

I don't know how this has been done under the hood, but I just wanted to note that the issue seems to be happening in all the cover block instances, not only the ones with`vh` unit.

In case it's helpful, these are the cover block patterns used in the recipes for the MVP.
* https://patternboilerplates.wordpress.com/2022/04/11/headline-with-title-and-cover/
* https://patternboilerplates.wordpress.com/2022/04/11/text-list-and-media/
* https://patternboilerplates.wordpress.com/2022/05/03/text-26/
* https://patternboilerplates.wordpress.com/2022/04/08/newsletter-10/
* https://patternboilerplates.wordpress.com/2022/03/22/headlines-22/
* https://patternboilerplates.wordpress.com/2022/05/03/blog-1/
* https://patternboilerplates.wordpress.com/2022/04/14/headlines-24/

**Comment by taipeicoder** [comment]
Shipped and closing!
