### ISSUE TITLE
Remove wpcom overrides for forcing post thumbnail support with Publicize feature

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64515]
**This task is blocked on Jetpack 11.1 being released.**
Scheduled for July 5

Now that [Jetpack is ensuring that the "featured image" UI appears in the editor whenever the Publicize module is enabled](https://github.com/Automattic/jetpack/pull/23871), we can now remove our wpcom specific hacks.

#### Tasks

- [x] Rollback the WoA fix 884-gh-Automattic/wpcomsh
- [ ] Rollback the Simple sites fix D22775-code

#### Context

p1HpG7-frH-p2

**Comment by danielbachhuber** [comment]
@p-jackson As far as I can tell, D22775-code needs to remain on WPCOM because https://github.com/Automattic/jetpack/pull/23871 didn't get synced to WPCOM.

I tried removing D22775-code while leaving the test in place, and the test didn't pass.

Is this correct? If so, it seems the only necessary change is 1031-gh-Automattic/wpcomsh

**Comment by wojtekn** [comment]
@danielbachhuber I've double-checked it, and I see that https://github.com/Automattic/jetpack/pull/23871 is not a part of the code synchronized to WPCOM. It looks like we need to leave the WPCOM-specific fix in place.

**Comment by danielbachhuber** [comment]
Shipped 1031-gh-Automattic/wpcomsh, so I think we're all set here.

**Comment by p-jackson** [comment]
> I've double-checked it, and I see that https://github.com/Automattic/jetpack/pull/23871 is not a part of the code synchronized to WPCOM.

Darn, didn't notice that at the time. That was my motivation for moving the feature to Jetpack in the first place 😮‍💨
