### ISSUE TITLE
Multiple Blocks: Typography appearance settings is overridden by Styles Typography Links settings

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#64596]
### Quick summary

The Styles Typography setting is overriding the Typography settings in Site Title Block.

The Block level settings should have higher priority. 

### Steps to reproduce

1. On a simple or AT site with FSE theme, go to Appearance > Editor.
2. On the Site Title block settings > Typography > Appearance, set it to something like Bold. You can see it works.
3. Next, go to Styles tab > Typography > Links > Appearance and change it to anything other than Default such as Thin.
4. You will notice that it affected the Site Title Block display.
5. The only way to preserve Site Title Block settings is to use Default in Styles tab > Typography > Links > Appearance.

![image](https://user-images.githubusercontent.com/33957570/173485522-83c89c52-c6f4-4b61-b6bb-b52b6eb6248a.png)

![image](https://user-images.githubusercontent.com/33957570/173485537-802b61a6-5a53-4f2f-8383-ba5e698fd97a.png)

### What you expected to happen

The block level settings should have priority over global settings such as the ones in Stlyes.

### What actually happened

Appearance settings in Styles > Typography > Links also affected Site Title block display. 

### Context

User report: 5295002-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No.

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

The only way to preserve Site Title Block display settings is to use Default in Styles tab > Typography > Links > Appearance.

**Comment by Joshgrygiel** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS
- Confirmed the steps outlined result in the styles tab settings overwriting the appearance settings of the Title Block through the FSE editor

📌 ACTIONS

- Marked as Triaged for Quality Squad review
- Transferred to WordPress/Gutenberg external repo: [here](https://github.com/WordPress/gutenberg/issues/41725)

📌 Message to Author - @devNigel I can confirm the individual Title Block typography styles are overwritten by the Styles tab settings. I opened this issue on [Wordpress / Gutenberg](https://github.com/WordPress/gutenberg/issues/41725) as the issue is appearing on self-hosted

**Comment by rw-ye** [comment]
Another report here: 5443273-zd-woothemes

The font size in Styles is also overriding the size set in block settings.

**Comment by Robertght** [comment]
Another case with Byrne in 5765619-zen

**Comment by cuemarie** [comment]
User reports from #73012 : 

- [ ] 5932564-zd-woothemes

**Comment by cuemarie** [comment]
I think this may be related: https://github.com/WordPress/gutenberg/issues/44931  **Global Styles: Styles specificity and users expectations** 

If so, the TLDR here is that GB is working as intended, but has a confusing UX due to the hierarchy of elements vs blocks.

@dsas Do you agree this is part of that larger conversation?

**Comment by dsas** [comment]
It's part of that conversation. Maybe this could be addressed differently, ([similarly to navigation](https://github.com/WordPress/gutenberg/pull/44578/files)) but maybe that just causes a different set of UX problems.

In either case it's definitely a problem that needs thinking about and addressing in Core Gutenberg and I see a [GB bug](https://github.com/WordPress/gutenberg/issues/41725) has been created

**Comment by the-misha** [comment]
Another user report: 42096785-hc

**Comment by tvolpert** [comment]
another one here:

- [ ] 36766118-hc

**Comment by jartes** [comment]
Another report when using the Site Title block and trying to change the styles: 

6300599-zd-woothemes

**Comment by khristiansnyder** [comment]
Ran into this issue today as well in #6330054-zd. Had to remove the link styling so the font size of the site title block could be used properly.

**Comment by cuemarie** [comment]
Encountered this again here: #6370750-zen

User was super frustrated and confused as to why their Site Title block's changes wouldn't update - and indeed the UI is hard to understand here.  I walked them through resetting Styles > Typography > Link > Font Size so that they can control the Site Title block from the block settings again.

**Comment by cuemarie** [comment]
It's been identified above that this issue is primarily an issue of confusing UI, which is being discussed in core here: https://github.com/WordPress/gutenberg/issues/44931

📌 ACTIONS
- With that in mind, I've downgraded the priority from `High` to `Normal` to better reflect its status in the larger context of open bugs in this repo.

**Comment by annezazu** [comment]
Noting that there's a PR underway to address this: https://github.com/WordPress/gutenberg/pull/64911 and that I can still replicate the original report. I've added the PR as needs review to the connecting the dots board for now.

**Comment by davemart-in** [comment]
Closing this out as it seems to be fixed by https://github.com/WordPress/gutenberg/pull/64911
