### ISSUE TITLE
One-time donations is shown as a subscription in the Earn section

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/wp-calypso#64600]
One-time donations also show as a subscription, which is confusing;

<img width="763" alt="Markup 2022-05-13 at 13 46 56" src="https://user-images.githubusercontent.com/5075840/168213062-7885b6d0-5f94-45ee-8197-17964ac44cf5.png">

_Originally posted by @Greatdane in https://github.com/Automattic/wp-calypso/issues/63267#issuecomment-1125653525_

**Comment by dsas** [comment]
Similarly a one-time payment also shows as a subscription:
![image](https://user-images.githubusercontent.com/93301/184848927-9c98107b-af22-4c9b-8b8e-ff295eaae46d.png)

**Comment by dsas** [comment]
For the subscriber we display the awkward phrase 'Remove one-off product':
![image](https://user-images.githubusercontent.com/93301/184865450-0b1a1233-66c9-4339-86fd-59476cdfabf6.png)

I think we should retain the cancellation functionality - you might want to stop someone from accessing your premium-content that you sold for a donation or subscription for example (need to confirm this is how it works). 

This then becomes a case of rewording 'Cancel Subscription' for one-off payers / donors. Maybe it should be 'Remove customer' / 'Remove donor', depending upon whether it's a donation being "cancelled" or not.

**Comment by dsas** [comment]
If you use the button, the confirmation dialog afterwards is chock-full of subscription wording too:

![image](https://user-images.githubusercontent.com/93301/184917831-85f8592c-ebfa-42b6-88ab-8bb2c97ab7b5.png)

**Comment by dsas** [comment]
> One-time donations also show as a subscription, which is confusing;

I think the premise here is that by donating / purchasing / etc, you get a "subscription" to the site. I think the confusion might be indicative of the payment blocks being built for one use-case and having had other things bolted on.

Cancel Subscription is kind of technically correct - the subscriber no longer has access to their subscribed content (that may not exist), Cancel donation isn't technically correct for a one-off donation - that sounds like the donation will be refunded which isn't the case and similarly Cancel purchase isn't correct if you're selling physical goods.

I think it's hard to get 100% accurate wording unless you know what the money transfer is for - a paywall, an ongoing donation, a one-off donation, a fur coat, a nail tech appointment...

With all of that in mind:
 * The button text ought to be 'Remove' for all one-time payments and 'Cancel Subscription' for all others
 * The confirmation dialog should always be displayed:
   * The sub-heading ought to be omitted for one-time payments (open to wording but I can't think of anything), and remain as is for all others.
   * The info box should not be displayed for one-offs whether donations or otherwise 
   * The button should echo the earlier button

This means that the final one-time payment confirmation dialog would look like this:
![image](https://user-images.githubusercontent.com/93301/184929749-4831462d-95e1-48ba-a471-708d9804f2a9.png).

**Comment by mmtr** [comment]
> I think we should retain the cancellation functionality - you might want to stop someone from accessing your premium-content that you sold for a donation or subscription for example (need to confirm this is how it works).

IIRC, users can only select non-donation plans in a premium content block, so I think we can remove the ability to cancel one-off donations since that doesn't produce any effect in practice.

> - The sub-heading ought to be omitted for one-time payments (open to wording but I can't think of anything), and remain as is for all others.
> - The info box should not be displayed for one-offs whether donations or otherwise

Assuming that the dialog won't be displayed for one-off donations, I think we can use the following generic wording when removing a one-off payment:

- Sub-heading: "Do you want to remove this purchase?"
- Info box: "Removing the purchase means that the user email@example.com will no longer have access to any service granted by this product, such as restricted premium content or a digital subscription. The cost of the purchase will not be refunded."

**Comment by dsas** [comment]
> IIRC, users can only select non-donation plans in a premium content block

Unfortunately that's not right. 

I think we can still use your proposed wording though, it just makes it more fiddly. We'll  have to s/purchase/donation
