### ISSUE TITLE
Domain Manager: Explicit Errors for duplicate DNS records

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#6462]
#### Steps to reproduce
1. Starting at URL: WordPress.com/domains
2. Click a site with a custom domain
3. Click the custom domain
4. Click Name Servers and DNS
5. Add a record that already exists, if no custom records exist, create a CNAME record that is valid and add it
6. Create the same record again, you'll see the following error:
![screen shot 2016-06-30 at 1 51 01 pm](https://cloud.githubusercontent.com/assets/8921630/16503860/de527ed8-3ec9-11e6-9578-c3a039c64d1c.png)

####Solution
The error should say something like "This DNS record already exists" to clarify why they're receiving the error.

This is probably not super high priority, I've only seen it come up once, but definitely a nice to have.

**Comment by klimeryk** [comment]
Thanks for reporting - I completely agree that this needs fixing... that's why I submitted [basically the same issue some time ago](https://github.com/Automattic/wp-calypso/issues/2920) 😀 I'd prefer to keep this one (it looks so much better ;)), but the old one is from January and I want to feel its puppy eyes on my back asking me "Why haven't you fixed me yet? 😢".
