### ISSUE TITLE
Yoast SEO Premium does not auto update if user purchased it directly from Yoast

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#64697]
### Quick summary

The user had Yoast SEO free plugin whose updates were managed by WPcom. They purchased Yoast SEO Premium directly from Yoast.

The Yoast SEO Premium plugin was outdated ( 18.5 )and there was no way to update it to the latest version ( 18.7 ) . The auto-update settings said: 

> Auto-updates are disabled based on this setting for Yoast SEO

I had to run `plugin symlink wordpress-seo-premium` in CLI to get the Premium plugin updated.

Creating bug report as suggested here: p1655364184377149/1655348649.822299-slack-C03TY6J1A

### Steps to reproduce

Not sure how to reproduce. 

### What you expected to happen

It should be possible to update Yoast SEO Premium.

### What actually happened

The Yoast SEO Premium was stuck in old version.

### Context

User report: 35815537-hc

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Run `plugin symlink wordpress-seo-premium`

**Comment by arunsathiya** [comment]
Note for the next triager: p1655348649822299-slack-C03TY6J1A

**Comment by cpapazoglou** [comment]
We shouldn’t symlink a plugin that is not purchased through [WordPress.com](http://wordpress.com/) and therefore shouldn’t be managed from [WordPress.com](http://wordpress.com/)

Here is why their Yoast SEO Premium doesn’t auto-update:
https://yoast.com/help/how-can-i-update-my-premium-plugin/#h-auto-updates-in-wordpress-5-5

**Yoast SEO** (free) is registered as managed in our Atomic infrastructure and this seems rendering it as "auto updates disabled" and as a result also stopping the auto updates for **Yoast SEO Premium** when it is bought from external sources.

It seems like we need to push a fix for making Yoast SEO (free) look like it has auto-updates enabled. We could alter the `get_site_option( 'auto_update_plugins' );` so that `wordpress-seo` is pushed there if it's installed. I wonder if we should do this for all managed plugins and whether it will have any consequences. @jmdodd any feedback?

**Comment by cpapazoglou** [comment]
Haven't done enough progress here... The idea here was to update the `auto_update_plugins` option in `wpcomsh_auto_update_new_plugins_by_default` (or a new function) so that it includes `wordpress-seo/wp-seo.php` when `wordpress-seo-premium` is installed / active AND purchased out of WordPress.com. 

After discussing with @jmdodd though, this might create issues with users who don't want `wordpress-seo` to auto update (for any reason). So the new plan is to unlink the `wordpress-seo` plugin manually. @jmdodd is there a way for HEs to unlink (remove the symlink) for a given plugin? Otherwise, the workaround is removing the plugin and uploading it.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - N/A

📌 SCRUBBING
- Did not test since this requires Yoast Premium purchase to replicate and it looks like @cpapazoglou is already investigating a solution.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cometgrrl** [comment]
FYI, while this is important, @jordesign and I agreed it's not a `blocker`, so we're lowering it to `high`.

**Comment by cpapazoglou** [comment]
After some thought and discussions https://github.com/Automattic/wp-calypso/issues/64697#issuecomment-1171184129, it's better to handle this per case. The workaround is removing `wordpress-seo` and uploading it rather than installing it.

**Comment by mattf10** [comment]
I just tried the work-around and it didn't work.    I removed Yoast SEO, then uploaded the latest version (19.11).   Yoast SEO is set to automatic updates enabled, yet for premium, I still have the error "Auto-updates are disabled based on this setting for Yoast SEO."

Please re-open this and provide a fix.

**Comment by cpapazoglou** [comment]
> I just tried the work-around and it didn't work. I removed Yoast SEO, then uploaded the latest version (19.11). Yoast SEO is set to automatic updates enabled, yet for premium, I still have the error "Auto-updates are disabled based on this setting for Yoast SEO."
> 
> Please re-open this and provide a fix.

Have you tried also removing and uploading the premium version?

**Comment by mattf10** [comment]
Yes, just tried that and still the same issue.

**Comment by cpapazoglou** [comment]
> Yes, just tried that and still the same issue.

Interesting, I can't reproduce it. FWIW:

- I have deleted Yoast SEO & Yoast SEO Premium
- I have upload Yoast SEO 
- I have enabled auto-update for Yoast SEO
- I have uploaded Yoast SEO Premium

![CleanShot 2022-12-01 at 12 50 07@2x](https://user-images.githubusercontent.com/12430020/205034286-ba281f04-f0d7-41cb-82ea-38d53e265714.png)

Also, please make sure that your Yoast SEO Premium license is active. 

If nothing above works, please reach us through our Support System https://wordpress.com/help/contact so that we can look further in your site.

**Comment by mattf10** [comment]
Ok - it's working now.   I was using a filter to force plugin updates to true.  After removing that, I clicked 'Enable auto-updates' on Yoast SEO, which then set Premium to 'enabled'.    I still think it would be better not to have to remove and add plugins to get this to work.

**Comment by jorpdesigns** [comment]
Just noting that I was able to avoid manually deleting / uploading plugins via CLI:

`wpcomsh plugin use-unmanaged wordpress-seo --remove-existing`
