### ISSUE TITLE
Calypso: Some Third Party Plugin (Elementor) Navigation Links lead nowhere in Calypso, work in WP-Admin

### ISSUE THREAD

**Issue by aisajib** [Automattic/wp-calypso#64691]
### Quick summary

On WordPress.com sites with Elementor installed, some links under My Site → Templates do not work when on Calypso. For example, Templates → Theme Builder doesn't work. It links to whatever page you're on Calypso. But if you navigate to /wp-admin, the links work correctly. 

In this screenshot, check out the link at the bottom. This is on Calypso. 
<img width="450" alt="Screen Shot 2022-06-16 at 9 26 02 AM" src="https://user-images.githubusercontent.com/2541844/173984520-7e1d7b98-e6cc-41ae-980e-960b3813a747.png">

The same link works fine when I'm on /wp-admin: 

<img width="674" alt="Screen Shot 2022-06-16 at 9 32 34 AM" src="https://user-images.githubusercontent.com/2541844/173985190-71dcf246-08f8-4da2-9353-7a6c62c65921.png">

### Steps to reproduce

1. Install Elementor on a WordPress.com site. 
2. Navigate to My Sites → Templates → Theme Builder

### What you expected to happen

Theme Builder page should open. Link: /wp-admin/admin.php?page=elementor-app&ver=3.6.6#/site-editor/templates (this requires Elementor Pro), but the "Theme Builder" should load something even without Elementor Pro installed. 

### What actually happened

Nothing happens. 

### Context

This was reported on a live chat, which I've since pushed to a ticket here: 5301448-zd-woothemes
I could replicate it on my test site. 

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Likely not. 

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is to simply visit the wp-admin dashboard (like by clicking My Site → Plugins → Installed Plugins) and then click Templates → Theme Builder.

**Comment by druesome** [comment]
Just to add more info from my findings here, other links under the Elementor Templates menu such as Kit Library and Add New also don't work as expected.  They link to the last page you're on in Calypso.

<img src="https://d.pr/i/yly07m+" width="500" />

While looking into this, the bug also affects another plugin called [Fonts Plugin | Google Fonts Typography](https://wordpress.org/plugins/olympus-google-fonts/), and my guess is there might be more plugins affected by this.

<img src="https://d.pr/i/JvdLPR+" width="500" />

Thanks for looking!

**Comment by galakhyati** [comment]
Another report for the issue to access Kit Library: 5322256-zd-woothemes

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Can replicate the issue:

### AT Site:

- Install Elementor Plugin
- Return to Calypso dashboard
- Hover over (Elementor) > `Templates > Theme Builder`, `Templates > Kit Library`, or `Templates > Add New`

Item links to the current page of the dashboard.

<img width="519" alt="Markup 2022-06-28 at 10 35 38" src="https://user-images.githubusercontent.com/27249804/176246966-79d5f068-7364-4ea1-8780-503da5b93503.png">

Also confirmed this happens with `Fonts Plugin > Customize Fonts` and `Fonts Plugin > Documentation` on my test site as well.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 Message to Author/Quality Squad
- Not sure if this is something that needs fixing on our side, or an update these plugin devs need to make within their products.

**Comment by i11za** [comment]
I'm closing the original ticket 5301448-zd-woothemes, please update the user once/if there's a fix. Thanks!

**Comment by Greatdane** [comment]
Another Elementor (Templates) → Theme Builder here;
- [ ] 36003887-hc

**Comment by csabarakasz** [comment]
Same issue: 36003887-hc

**Comment by Greatdane** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 


📌 FINDINGS/SCREENSHOTS/VIDEO
- Calypso bug. Moved to high priority, as although there is a simple work-around, it is not obvious to the user and is causing longer chats and frustrated users!

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by mmtr** [comment]
I took a quick look at this and I don't think this can be solved by us, since apparently the Elementor plugin is using a non-standard hack to register their menus:

- The "Theme Builder" menu item is first registered using the standard `admin_menu` action: https://plugins.trac.wordpress.org/browser/elementor/trunk/core/app/app.php?rev=2692417#L260
- It uses an invalid (*) `elementor-app` as menu slug: https://plugins.trac.wordpress.org/browser/elementor/trunk/core/app/app.php?rev=2692417#L37
  - (*) Invalid because there is no plugin file matching that slug and because there is no callback associated to that slug: https://developer.wordpress.org/reference/functions/add_submenu_page/
- That menu item initially links to `/wp-admin/elementor-app`
- It's later changed to `/wp-admin/admin.php?page=elementor-app&ver=<VERSION>#site-editor/promotion` using the `add_menu_classes` action: https://plugins.trac.wordpress.org/browser/elementor/trunk/core/app/app.php?rev=2692417#L263
- However, the `add_menu_classes` action is not meant to alter the URLs of the menu items. It should be used only to add CSS classes: https://developer.wordpress.org/reference/functions/add_menu_classes/
- Since the URL of the menu item has been manipulated outside of the `admin_menu` action, our Nav Unification logic thinks that the menu item links to `/wp-admin/elementor-app` which is not a valid URL, so we return an empty URL: https://github.com/Automattic/jetpack/blob/f51ea0c879352de9a84d64898b71acfe2725185f/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php#L371
- Calypso interprets that empty URL as the current URL

I'd advise to contact the Elementor dev team so they avoid using the `add_menu_classes` action to change the URL.

**Comment by mmtr** [comment]
Related to the above: PCYsg-vFf-p2#i-dont-see-a-menu-registered-by-a-plugin-how-can-i-access-it

> In this logic, we are only capturing menus that have been registered using the standard WP utils for manipulating the admin menu (the `admin_menu` hook, the regular `add_menu_page`/`add_submenu_page` functions, the `$menu`/`$submenu` globals).
>
> Certain plugins may get more creative and use alternative ways for changing the menu: via CSS styles, with JS overrides, using other WP/PHP functions, etc. The `admin-menu` endpoint is not able to capture all these exceptions, and thus all plugins using them will have missing menus in Calypso.

This is the same issue with the difference that the menu is not missing but has a wrong URL.

**Comment by csabarakasz** [comment]
Another Elementor > Kit Library opening issue:

- [ ] 5362513-zd-woothemes

**Comment by dsas** [comment]
This is a bit of a restatement of @mmtr's [earlier comment](https://github.com/Automattic/wp-calypso/issues/64691#issuecomment-1177673838) as Elementor have substantially refactored since:

 1. The "Theme Builder" menu item is first registered as a link to /wp-admin/elementor-app ([src](https://plugins.trac.wordpress.org/browser/elementor/trunk/app/app.php?rev=2840521#L40))
 2. The URL is then altered via the `add_menu_classes` filter ([src](https://plugins.trac.wordpress.org/browser/elementor/trunk/app/app.php?rev=2840521#L260)) which executes `fix_submenu` ([src](https://plugins.trac.wordpress.org/browser/elementor/trunk/app/app.php?rev=2840521#L44)) ultimately changing it to the url above using the `menu_url` setting ([src](https://plugins.trac.wordpress.org/browser/elementor/trunk/app/app.php?rev=2840521#L91)).

As the URL registered in 1. isn't valid - there's no plugin file or callback matching `elementor-app`, then we don't use a link at all.

**Comment by dsas** [comment]
I think the problem is that the menu item includes the domain,  and [we only allow jetpack.com and wordpress.com domains in menus](https://github.com/Automattic/jetpack/blob/f51ea0c879352de9a84d64898b71acfe2725185f/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php#L373). I see no reason why we shouldn't allow links to the site being administered 🤔 

You can see the menu items by sshing to the atomic site and running `wp --user=<yourwpcomuserid> shell` and then:

```
wp> require_once JETPACK__PLUGIN_DIR . '/modules/masterbar/admin-menu/load.php';
wp> global $admin_page_hooks, $menu, $menu_order, $submenu, $_wp_menu_nopriv, $_wp_submenu_nopriv;
wp> require_once ABSPATH . 'wp-admin/includes/admin.php';
wp> require_once ABSPATH . 'wp-admin/menu.php';
wp> print_r($submenu['edit.php?post_type=elementor_library'], true);
```

This gives:
 * **Theme Builder:** https://deanatomictestnodevstuff.wpcomstaging.com/wp-admin/admin.php?page=elementor-app&ver=3.10.0#site-editor/promotion
 * **Kit Library**: https://deanatomictestnodevstuff.wpcomstaging.com/wp-admin/admin.php?page=elementor-app&ver=3.10.0#/kit-library
 * **Add New**: post-new.php?post_type=elementor_library

I'm still not sure why Add New isn't working - it should be ok because it's [using an existing wp-admin file](https://github.com/Automattic/jetpack/blob/f51ea0c879352de9a84d64898b71acfe2725185f/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php#L419)
