### ISSUE TITLE
Themes: Something is wrong with replace homepage functionallity

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#64705]
The **Replace my homepage content with the [THEME] homepage.** does not work with some themes, I've reproduced the issue with Archeo, Remote and Skatepark.
@sixhours noted that this might be related to themes that don't include a static home page, If we choose to replace homepage in one of the mentioned themes above and go to the customizer and selecting "Your latest posts", they work as expected.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/375980/174110813-7d6f9fe0-51a4-4d37-addb-dfec764c862a.png">

This is the current behaviour, notice that after selecting the Archeo theme we don't see the expected big head on our site.

![2022-06-16 12 45 09](https://user-images.githubusercontent.com/375980/174112058-067ad3d3-8f7a-4fac-ae36-c1a48d7867d4.gif)

**Comment by creativecoder** [comment]
All of these themes use the setting `"show_on_front": "posts"` in their headstart annotations (which are used for replacing the home page content, iirc). We don't really have a good mechanism for making an existing site "look like the demo" in this case, since it would require inserting dummy posts onto the site to show up on the front page.

See this issue, which is basically the same underlying problem: https://github.com/Automattic/wp-calypso/issues/57670

Maybe as a stopgap, we should disable this choice on themes designed to use the posts list as the front page.

**Comment by andres-blanco** [comment]
We where thinking around this issue with @sixhours and found that the setting `show_on_front: posts` is not being set for this themes because the `blog-homepage` tag on the `style.css` is missing, if you add it the homepage you end up is closer to what you would expect. Since theme files are heavily cached you can test this behaviour following this instructions:
1. Set up a new site.
2. Sandbox public-api.
3. On your sandbox replace line 99 of this file `wp-content/mu-plugins/full-site-editing/class-template-first-themes.php` with: `if ( true || $this->has_blog_homepage( $stylesheet ) ) {`, bypassing the check for the `blog-homepage` tag.
4. Go to `https://wordpress.com/themes/[YOUR_SITE]`.
5. Replace you theme homepage with one of themes mentioned above (eg: Archeo).
6. Go to `[YOUR_SITE]` and see if you feel it's more like you would have expected.

If you think this is a good approach let me know so I set up a couple of diffs.

**Comment by andres-blanco** [comment]
Started working on this here: D83131-code

**Comment by sixhours** [comment]
Fixed by D83131-code.
