### ISSUE TITLE
Import: improve the import flow when you export as ZIP yet require an unzipped XML file to import

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#6470]
#### Steps to reproduce
1. Go to `/settings/export`, export and download the resulting zip archive.
2. Go to `/settings/import`, import the zip.
3. You should now see this error message:
   ![2016-07-01 10 55 53](https://cloud.githubusercontent.com/assets/1842898/16510738/4bbbd760-3f7b-11e6-8e74-3d149047099a.png)

While our importer only takes WXR file, a user could legitimately assume she can import whatever exported directly. 

It would be less confusing to show clearer instructions to inform the user to extract and to upload WXR files individually.

**Comment by designsimply** [comment]
Agreed. It would be nice to detect an uploaded zip file and let someone know that they should unzip first and upload the xml file instead.

I saw a different error when I tested this. I'm including it here for reference:

> Unexpected error during the upload

![screen shot 2016-08-19 at fri aug 19 1 20 26 pm](https://cloud.githubusercontent.com/assets/1119271/17821607/b9b95340-660f-11e6-9513-dbcad542e3a6.png)
<sup>Seen at https://wordpress.com/settings/import/foodescapades.wordpress.com using Chrome 52.0.2743.116 on Mac OS X 10.11.6</sup>

**Comment by lancewillett** [comment]
Wanted to say +1 to fixing this UX issue.

@m mentioned this one again recently — adding more notes here.

UX issue: When you download an export from WP.com, you end up with a ZIP file. But if you try to upload that ZIP file to import somewhere else on WP.com, it errors because the import needs an unzipped .xml file and not the ZIP format.

**Comment by jblz** [comment]
@Automattic/delta-samus, this should be pretty straightforward. Let's fix it.

**Comment by pablinos** [comment]
What's preventing us from allowing the zip to be uploaded and extracting the XML on the server? It seems like that would be a better experience than asking the user to unzip it themselves.

We could do some checks to ensure that the zip only contains an appropriate import file as a security measure.

**Comment by southp** [comment]
@pablinos Actually I had proposed it in https://github.com/Automattic/hg/issues/147#issuecomment-229545699 . The only reason we didn't aim for that was because we simply didn't have the bandwidth. Sarcastically, we still don't have the bandwidth even after we scoped it down 🙃

 If we implement zip uploading, I think we should still support WXR uploading and provide clear instructions that both uploading a zipped WXRs archive and a WXR will work.

**Comment by jblz** [comment]
If we can patch the client to get the zip file to PHP, we can extract only appropriate files by passing them to the 2nd param of [ZipArchive::extractTo](https://secure.php.net/manual/en/ziparchive.extractto.php).

**Comment by lancewillett** [comment]
Tagging @Automattic/delta-samus on this one as it came up again yesterday in an empathy challenge posted by @m.

**Comment by jblz** [comment]
@bisko is working some magic in D16447-code

**Comment by thehenrybyrd** [comment]
Ran into this today in #8049949-hc. 
The user was attempting to upload the enclosing file folder, rather than the zip or the .xml. This is because when a site is exported, a zip is downloaded and some OS open these automatically. 
Then you have the zip archive, the enclosing folder, and the .xml file within.

Uploading the enclosing folder results in this error:
<img width="733" alt="importerror" src="https://user-images.githubusercontent.com/15107387/50077390-efe23600-01ec-11e9-8923-21a3ef8c8029.png">

Whatever error we display here should specify the acceptable filetype(s) the importer will accept.
It would also be helpful to specify this below the importer in the first place. "Upload a WordPress export file" doesn't help someone who doesn't know what a WordPress export file means.

**Comment by bisko** [comment]
@thehenrybyrd Seems like an XML file in the Zip archive was having broken encoding. We have a fix in place for testing, but it's not fully released to the public. 

You can enable the feature for the customer's site and let them try the import again. 

More information here: p7DVsv-5Hb-p2

**Comment by dezzie** [comment]
Hey I know this issue has been stale for a while, but thought I could help out:

ZIP and WXR are both supported now, and the UI copy had been updated a while back to indicate that:
<img width="735" alt="Screen Shot 2019-06-12 at 2 50 12 PM" src="https://user-images.githubusercontent.com/1301932/59390284-ae5abf80-8d25-11e9-9376-5d85ec6bda07.png">

Next, to add specificity to the upload error message, I re-iterate what a valid export file is:
<img width="1239" alt="Screen Shot 2019-06-12 at 3 14 10 PM" src="https://user-images.githubusercontent.com/1301932/59390331-caf6f780-8d25-11e9-85df-0d2a294ff770.png">

Lastly, when a user contacts support, I propose to make that link more specific and skip the self-serve articles and go straight to /help/contact:
<img width="743" alt="Screen Shot 2019-06-12 at 3 23 05 PM" src="https://user-images.githubusercontent.com/1301932/59390414-01cd0d80-8d26-11e9-8627-c59b828e0ad3.png">

**Comment by dezzie** [comment]
PR: https://github.com/Automattic/wp-calypso/pull/33904

**Comment by dezzie** [comment]
I got feedback on the proposed solution, to not link the message directly to support, but to keep the link as-is, pointing to the Help section. In that case, I changed the original error message for accuracy, since that wasn't contacting support either:

<img width="740" alt="Screen Shot 2019-06-13 at 3 25 01 PM" src="https://user-images.githubusercontent.com/1301932/59471383-c3038a00-8def-11e9-9b3a-782b19a4b137.png">

**Comment by southp** [comment]
Thanks for tackling this, @dezzie 🙇
