### ISSUE TITLE
Nav Unification / Sidebar: Mailpoet icon does not show when on WordPress.com

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#64751]
### Quick summary

When in wp-admin for my Atomic or Jetpack site, I see the MailPoet icon in the sidebar. When on WPCOM, I see a settings cog icon.

We should probably show the MailPoet icon here since this is one of our plugins.

<img width="576" alt="Screen Shot 2022-06-17 at 12 50 33 PM" src="https://user-images.githubusercontent.com/1126811/174398472-44dbacf3-4a5e-4e78-8277-0aa226c2de28.png">
<img width="498" alt="Screen Shot 2022-06-17 at 12 50 18 PM" src="https://user-images.githubusercontent.com/1126811/174398478-a4398b7b-265d-4d16-88a4-9cf3ccf855ed.png">

### Steps to reproduce

1. On Atomic or Jetpack site, ensure that MailPoet is installed
2. Go to `wordpress.com/home/$site_slug` and verify that settings cog shows beside menu item for MailPoet
3. Go to `$site.com/wp-admin` and very that the MailPoet icon shows in the sidebar

### What you expected to happen

The MailPoet icon to show in the sidebar on WPCOM

### What actually happened

The settings cog showed beside MailPoet in the sidebar on WPCOM

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

**Comment by galakhyati** [comment]
📌 HOUSEKEEPING
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on Atomic site, on Calypso UI the MailPoet shows a cogwheel icon, whereas on WP-Admin view, it shows the plugin's icon.
- On a self-hosted site, I tested on Jurassic.ninja site, I'm not seeing the plugin option on Calypso UI, whereas on WP-Admin view, I'm seeing the plugin's icon.
- 
![Markup on 2022-06-30 at 17:30:54](https://user-images.githubusercontent.com/7382505/176672215-6e0a9967-3397-4e28-b3a9-9dc26df5b81e.png)
![Markup on 2022-06-30 at 17:32:00](https://user-images.githubusercontent.com/7382505/176672397-76f8a240-b502-423b-9406-1791d10d3ab0.png)
![Markup on 2022-06-30 at 17:34:00](https://user-images.githubusercontent.com/7382505/176672755-d4912c44-bf8a-426b-8b5c-881884cbfd70.png)
![Markup on 2022-06-30 at 17:34:51](https://user-images.githubusercontent.com/7382505/176672892-e63f7486-c2e5-4a9b-af45-61f60f11c57f.png)

**Comment by danielbachhuber** [comment]
It looks like the Mailpoet icon is missing from Calypso because it's added to the WordPress admin with an icon font https://github.com/mailpoet/mailpoet/blob/450210a269f505569fd12605f0fcad1bcb41b45d/mailpoet/assets/css/src/components-admin/_menu.scss#L1-L6

This icon font was originally added in https://github.com/mailpoet/mailpoet/commit/2dbd6315002717ba29afe6251e8cd691e209a658

The AMP Icon appears as expected, so it may be as simple as swapping in a base64-encoded SVG: https://github.com/ampproject/amp-wp/blob/6113006e39bc688ad8d34ebc892c4c83d52b416a/src/Admin/OptionsMenu.php#L158-L169

Asked in Slack about the implementation p1657644096510499-slack-C01GH764202

**Comment by danielbachhuber** [comment]
Mailpoet switched to a SVG menu icon for Calypso compatibility with https://github.com/mailpoet/mailpoet/pull/4268
