### ISSUE TITLE
Lint: consider disable or removal of the `jest/no-disabled-tests` rule.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#64870]
### Details

In PR https://github.com/Automattic/wp-calypso/pull/64743, specifically in https://github.com/Automattic/wp-calypso/pull/64743#discussion_r903364716 the merits of the `jest/no-disabled-tests` rule was discussed.

It seems the rule hasn't had the intended results (encouraging developers to re-enable and fix their tests), instead resulting in the tests being disabled for weeks/months on end or the rule itself disabled to mask the problem.

### Checklist

Investigate which is more feasible:
- [ ] Disable the rule for the `test/e2e/` folder.
- [ ] Identify and remove all instances where the rule is suppressed via `eslint-disable` annotations.

**Comment by worldomonation** [comment]
@john-legg I've assigned you this task, which should be a fairly good introduction to working within the `wp-calyspo` codebase.

Recall that we talked about linting that happens in two places:
- when the file is saved, typically through a code editor (eg. VSCode)
- when the file is staged for commit, using git pre-commit hooks.

We currently have the `jest/no-disabled-tests` rule enabled as either a warning or error for the `test/e2e` directory. As described in the original comment, this hasn't really had the effect we were hoping for.

I've updated the checklist in the original comment and it should be enough to get you started.

**Comment by john-legg** [comment]
Hi @worldomonation! I've made these changes locally, but I just want to confirm one thing before pushing. I noticed that there was one test left with the `jest/no-disabled-tests` rule being used: 

- [checkout-contact-step.js](https://github.com/Automattic/wp-calypso/blob/e1dfd101d09bc9e691ec93fa1b0532a8ee7385f6/client/my-sites/checkout/composite-checkout/test/checkout-contact-step.js#L261)

Since it falls under `client/my-sites/checkout-checkout/test/` (i.e. not under `test/e2e/`) should I just leave it alone? Thanks!

**Comment by worldomonation** [comment]
> Since it falls under client/my-sites/checkout-checkout/test/ (i.e. not under test/e2e/) should I just leave it alone? 

@john-legg Yes, let's focus only on E2E specs under `tests/e2e` for now. The changes to disable the rule should also be limited to the `test/e2e` folder.

**Comment by worldomonation** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/68056.
