### ISSUE TITLE
Purchases: monthly billing period shows as annual

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#64923]
### Steps to reproduce

1. Buy https://wordpress.com/plugins/wordpress-seo-premium/
2. Go to https://wordpress.com/me/purchases
3. Find the Yoast SEO Premium subscription and click it

![CleanShot 2022-06-24 at 08 20 50@2x](https://user-images.githubusercontent.com/12430020/175472258-9b57cd70-026e-4603-9a9c-949e8a18caff.png)

### What you expected to happen

Billing period to be monthly " / month"

### What actually happened

Billing period is annual " / year"

### Reproducibility

Consistent

**Comment by WBerredo** [comment]
The issue is related to this check on the product plan, as the plan at this point is a string with the slug, it won't enter this condition, and still as default (`year`):
https://github.com/Automattic/wp-calypso/blob/3799492a9e2992f76e21e6fe54535cd019a57322/client/me/purchases/manage-purchase/purchase-meta.jsx#L248-L258

The definition of the plan happens on this method which verifies if the product slug is on this hard-coded list (`PRODUCTS_LIST`), if not, just returns the slug (this is the case):

```typescript
export function getProductFromSlug( productSlug: string ): Product | string {
	if ( PRODUCTS_LIST[ productSlug as ProductSlug ] ) {
		return PRODUCTS_LIST[ productSlug as ProductSlug ];
	}
	return productSlug; // Consistent behavior with `getPlan`.
}
```

https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-products/src/get-product-from-slug.ts#L4-L9

**Comment by cpapazoglou** [comment]
I can see that the `purchase` object includes a `bill_period_label`. Can we refactor the Calypso implementation by removing all the hard coded references and use the dynamic `bill_period_label`?

![CleanShot 2022-06-27 at 12 04 31@2x](https://user-images.githubusercontent.com/12430020/175903666-b4b426df-80ec-4fcb-b985-2272cf119837.png)

Checking the backend it can be any of the following `for life`, `per day`,`per week`,`per month`,`per year`

**Comment by WBerredo** [comment]
> Can we refactor the Calypso implementation by removing all the hard coded references and use the dynamic bill_period_label?

I'm not sure about remove *all the hard coded references* and I would go for adding them as a fallback as in #64949.
Mainly because this method has a lot of different ways to check and I don't have the context to determinate if we can make this switch.

**Comment by WBerredo** [comment]
I would also like to know where did you print this `purchase` object. 

When I try to print it inside the `PurchaseMetaPrice` component, I don't get the `bill_period_label` filled, I actually get all properties in camel case but only `billPeriodDays` is filed.

**Comment by WBerredo** [comment]
I created the PR #65006 where we use the `bill_period_label` to define the period if it exists.
Otherwise, the other checks will be used.
