### ISSUE TITLE
[Bug]: Custom Post Types not displayed in Calypso UI

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#64935]
### Quick summary

One should have access to their allowlisted Custom Post Types when managing their site from the WordPress.com dashboard. This used to be possible, but the CPT do not appear in the sidebar menu anymore.

### Steps to reproduce

1. Start with a Jetpack site that's connected to WordPress.com.
2. Register a new CPT, and allowlist it.
```php
// Register Custom Post Type
function jeherve_rowan_custom_post_type() {

	$labels = array(
		'name'                  => _x( 'Example Post Types', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'An example Post Type', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Example Post Types', 'text_domain' ),
		'name_admin_bar'        => __( 'Post Type', 'text_domain' ),
		'archives'              => __( 'Item Archives', 'text_domain' ),
		'attributes'            => __( 'Item Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Item:', 'text_domain' ),
		'all_items'             => __( 'All Items', 'text_domain' ),
		'add_new_item'          => __( 'Add New Item', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Item', 'text_domain' ),
		'edit_item'             => __( 'Edit Item', 'text_domain' ),
		'update_item'           => __( 'Update Item', 'text_domain' ),
		'view_item'             => __( 'View Item', 'text_domain' ),
		'view_items'            => __( 'View Items', 'text_domain' ),
		'search_items'          => __( 'Search Item', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
		'items_list'            => __( 'Items list', 'text_domain' ),
		'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'An example Post Type', 'text_domain' ),
		'description'           => __( 'An exmaple post type description', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'show_in_rest'          => true,
	);
	register_post_type( 'jeherve_rowan', $args );

}
add_action( 'init', 'jeherve_rowan_custom_post_type', 0 );

function jeherve_allow_my_post_types( $allowed_post_types ) {
	$allowed_post_types[] = 'jeherve_rowan';
	return $allowed_post_types;
}
add_filter( 'rest_api_allowed_post_types', 'jeherve_allow_my_post_types' );
```
3. You will see the new post type menu when managing your site in wp-admin.
4. You will not see the menu when in WordPress.com.

**wp-admin**
<img width="227" alt="image" src="https://user-images.githubusercontent.com/426388/175513139-e3ca0be0-7247-45df-abc8-80383d807994.png">

**Calypso**
<img width="296" alt="image" src="https://user-images.githubusercontent.com/426388/175513229-5551697c-1b07-403d-b97c-978da33494e9.png">

### What you expected to happen

The "Example Post Types" menu item should appear, just like the other Post Types on those screenshots.

### What actually happened

It does not appear.

### Context

5303505-zen

### Browser

Google Chrome/Chromium

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The only way to access the Post Type management screen is by navigating to wp-admin first.

**Comment by jeherve** [comment]
I think it may be related to the fallback menu we added to Jetpack sites when we worked on nav-unification: #49352

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I followed the testing steps (used the Code Snippets plugin to add the code) and was able to recreate this with a Jetpack site connected to WordPress.com. 
- It seems that this is not limited to custom post types—other menu items, like menu items from installed plugins, don't appear in Calypso for my Jetpack test site. These menu items do appear for AT sites.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by sejas** [comment]
@jeherve @mmtr,

I've created a PR that includes the CPT menu items in Calypso for Jetpack sites https://github.com/Automattic/jetpack/pull/25670, but I would like to confirm with you if this is still needed and is the right direction.

My concerns are:

1. On nav unification, the Jetpack sites have a different menu on purpose. From my understanding, the CPTs were not included on Jetpack sites. On atomic sites, we do include them.
   - On Jetpack sites, we reset the admin menus to exclude any menu item from plugins. Creating the admin menu from scratch. [projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php#L32-L34](https://github.com/Automattic/jetpack/blob/c1e82ce99a0d4c93949407bc32a409bf3010bb79/projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php#L32-L34) 
   - On atomic sites we keep the original menu and we add new items and replace some links. [projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L62-L69](https://github.com/Automattic/jetpack/blob/c1e82ce99a0d4c93949407bc32a409bf3010bb79/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L62-L69)
2. We decided to keep the menu as it is in https://github.com/Automattic/wp-calypso/issues/66068.
3. On the user-facing site has a different menu from WPCom and different from wp-admin

I can see three possible actions:
1. Move forward and include only the CPT menu items on calypso UI.
2. Plan a bigger refactor to change the current behavior for jetpack sites.
3. Consider the Jetpack sites have different calypso admin menu and close this issue.

## Screenshots of the 3 current admin menus

**Calypso**

<img width="271" alt="Screenshot 2022-08-17 at 12 17 58" src="https://user-images.githubusercontent.com/779993/185105814-0be944d0-6e63-4d23-8256-832788c6587c.png">

**WP Admin**

<img width="163" alt="Screenshot 2022-08-17 at 12 53 13" src="https://user-images.githubusercontent.com/779993/185112030-3e990cf5-123f-47ad-848a-dec67434f58d.png">


**Frontend**

<img width="336" alt="Screenshot 2022-08-17 at 12 52 27" src="https://user-images.githubusercontent.com/779993/185111939-48a9d717-8c47-45cd-9de8-8852b3ca7b31.png">

**Comment by jeherve** [comment]
I'll let @mmtr weigh in on this, as I'm not completely familiar with what the original goals were with the Calypso menu for Jetpack sites in the nav-unification project.

**Comment by mmtr** [comment]
The overall strategy for Jetpack sites is to avoid jumps between Calypso and WP-Admin. See p1HpG7-bcl-p2#comment-44627:

> In short: **any flow that starts in WP Admin should end in WP Admin, any flow that starts in Calypso should end in Calypso**. If no other way it’s possible, the switch should be explicit.

So we launched a _limited_ menu for Jetpack sites that replicated the same menu items we had in the old sidebar, but using the same new UI component introduced for the unified menu on WP.com sites. See https://github.com/Automattic/jetpack/pull/18921.

That means that the only menu items that point to a WP Admin screen are the ones who were already in the old sidebar. Those are the only exceptions. 

Now, it seems we missed adding some exceptions to the new menu, like the menus items for all CPTs, since they were rendered in the old sidebar: 

https://github.com/Automattic/wp-calypso/blob/3c8c6d27ef3957a03beea37633a33e0fbeac7c09/client/my-sites/sidebar/index.jsx#L1069

https://github.com/Automattic/wp-calypso/blob/3c8c6d27ef3957a03beea37633a33e0fbeac7c09/client/my-sites/sidebar/index.jsx#L140-L149

https://github.com/Automattic/wp-calypso/blob/3c8c6d27ef3957a03beea37633a33e0fbeac7c09/client/my-sites/sidebar/site-menu.jsx#L195

And in the new sidebar we only render the menu items for the Testimonials and Portfolio CPTs:

https://github.com/Automattic/jetpack/blob/c1e82ce99a0d4c93949407bc32a409bf3010bb79/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L31-L32

So @sejas, for this particular case, it's fine to go ahead with your first suggested action "Move forward and include only the CPT menu items on calypso UI", since it's an allowed exception that was already happening in the old sidebar. Let's just make sure they are marked as external and opened on new tabs (this should happen automatically as of https://github.com/Automattic/wp-calypso/pull/50444).

**Comment by mmtr** [comment]
On a second thought, it looks like that the CPT menu items in the old sidebar were pointing to Calypso: https://github.com/Automattic/wp-calypso/blob/3c8c6d27ef3957a03beea37633a33e0fbeac7c09/client/my-sites/sidebar/site-menu.jsx#L254

So we need to change https://github.com/Automattic/jetpack/pull/25670 so they are registered as menu items that point to Calypso.

**Comment by sejas** [comment]
I've updated the PR https://github.com/Automattic/jetpack/pull/25670 to open the CPT menu items using the Calypso UI.

I've also found that Jetpack sites need to have WPcom SSO enabled in order to use the "calypso editor". The pain point is that jetpack has this feature disabled by default on Jetpack sites. The result of trying to add/edit a post, page or custom post without SSO is that the user will be asked to log-in again and redirected to wp-admin.

This behavior is different from this issue but something to take into consideration.

This can be seen at Minute 7:00

p1HpG7-bcl-p2 

And I've recorded a screencast explaining it:

https://user-images.githubusercontent.com/779993/185683004-cd4b9b57-b75e-46f0-9592-5787053a6300.mp4

**Comment by mmtr** [comment]
> I've also found that Jetpack sites need to have WPcom SSO enabled in order to use the "calypso editor".

Correct. That's a known issue tracked here: https://github.com/Automattic/wp-calypso/issues/48477. It's unrelated to your changes though, since it happens across all post types, not only CPTs. Said that, I think we can mitigate that by checking if the SSO module is enabled and use the WP Admin link when disabled.
