### ISSUE TITLE
Classic Editor defaults to Text mode instead of Visual mode

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#64967]
### Quick summary

We’ve got a really odd case here where the Text tab would be the default option for this user when using the Classic editor. Even if you switch to Visual, and update, the next time that page is edited in the Classic Editor it defaults back to the Text tab.

We could replicate this behavior. We tried:

* logged the user out from all sessions
* clearing all the local storage artifacts

Not able to reproduce on other sites, but only on this specific site: `terry-marsh.com` of the user.

### Steps to reproduce

1. SU to the user's site. 
2. Go to Posts / Pages > Add New > Classic Editor.
3. You will notice that editor defaults to Text mode.

### What you expected to happen

The editor should default to Visual mode.

### What actually happened

The editor defaulted to Text mode.

### Context

User report: 5319043-zd-woothemes

### Simple, Atomic or both?

Simple

### Reproducibility

Once

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment]
@devNige I can replicate this behavior on my Premium plan website? Are you able to try a Premium site and replicate it?

**Comment by filipanoscampos** [comment]
@Greatdane 
I have tried to replicate this but couldn't.

I did notice that, in my test site, with the same theme activated, the Classic Editor mode defaults to my last-used option.
If I left the previously edited page in Text mode, it will open in text view. But I can't replicate this behaviour on the user's site.

**Comment by devNigel** [comment]
@Greatdane I checked with Lodestar and Twenty Twenty-One on my premium site. I agree with Filipa's findings. The Classic Editor opens in the last used option on my test site.

**Comment by cuemarie** [comment]
I just took the following steps:

- SU to the user's site.
- Go to Posts / Pages > Classic Editor.
- Selected "Add New"

The editor opened with the **Visual Editor**, not the Text Editor.

<img width="1227" alt="Markup 2022-07-04 at 14 54 09" src="https://user-images.githubusercontent.com/27249804/177219622-0c28542f-72a2-45e6-8c5d-d75afde22fb9.png">

However, when I select `Classic Editor` underneath an existing post or page, that opens in the Text Editor.

---

It looks like none of their Published pages/posts have been modified since 2018. 

- I wonder if the user/HEs could try switching to Visual, making any change on the page with the content, and then Updating, if that would help at all?

**Comment by Greatdane** [comment]
Moving it back to the triage queue to see if someone else can replicate on their own site.

**Comment by jamiepalatnik** [comment]
Noting that we told the user we would follow up when we have an update on this. Closed the ticket for now.

- [ ] 5319043-zd-woothemes

**Comment by cuemarie** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- **Could not replicate**. Steps taken:

1. Open Premium Site
2. Switch to Lodestar (user's theme)
3. Posts > Add New > Classic Editor

**Result**: New classic editor post opens in `Visual` mode, not `Text` mode.

Editor saves preference: 
- `Save Draft` while in `Visual` mode has the Classic editor re-open in `Visual` mode. 
- `Save Draft` while in `Text` mode has the Classic editor re-open in `Text` mode. 

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @devNigel I recommend posting this instead on **Happiness Feedback** for further testing, since the issue cannot be replicated.
