### ISSUE TITLE
Plans Redesign: add abtest

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6502]
This task should be done after all other plan redesign issues have been completed. Remove the `manage/plan-features` feature flag and add a 50/50 abtest in its place.

**Comment by lamosty** [comment]
Should we keep plan features on separate URL, e.g.: `/plans/features` and have the old/current plans on `/plans`? Or if plan features is enabled, show it on both `/plans` and `/plans/features`? <- that's how it's done at the moment because we only check for feature flag in `plans/main`, not whether you are on `/plans/features` or only `/plans`.

Will do this after we merge all the smaller plans PRs and the tabular PlanFeatures PR. Okay?

**Comment by gwwar** [comment]
@lamosty Did we ever link to `/plans/features`? If possible lets stick to displaying on `/plans` and `/plans/compare` when the abtest is set to show the new redesign.

> Will do this after we merge all the smaller plans PRs and the tabular PlanFeatures PR.

Sounds like a good plan.

**Comment by lamosty** [comment]
>  Remove the manage/plan-features feature flag

Why? Shouldn't I keep the `manage/plan-features` feature flag and add the abtest as an addition? And then enable plan-features for all environments? I think that's how we have done it so far with other things?

**Comment by gwwar** [comment]
It can be done either way, we tend to keep feature flags around for riskier features. We can leave it in if we think we may need to quickly turn it off for everyone.
