### ISSUE TITLE
Calypso: No Warning of Loss of Custom Free Subdomain (Dotblog subdomain) When Going Atomic

### ISSUE THREAD

**Issue by i11za** [Automattic/wp-calypso#65081]
### Quick summary

There's no warning that a the free `*.tech.blog` subdomain will be lost when going Atomic either via plugin installation, hosting config, or theme upload pages' on Pro plan. 

Tested with `*.tech.blog` and `*.food.blog` [free .blog subdomain](https://wordpress.com/blog/2018/11/28/announcing-free-dotblog-subdomains/). 

Haven't tested this on Legacy plugin-enabled plans. 

### Steps to reproduce

1. Create a new site on Pro and select a free .blog subdomain as the site address. 
2. Go Atomic by installing a plugin or uploading a theme, or activating hosting config. 
3. Site goes Atomic and address changes to `*.wpcomstaging.com` without warning. 

### What you expected to happen

To receive a warning:

> **Warning**
> By installing a plugin the following change will be made to the site:
Your subdomain will change from *.*.blog to *.wpcomstaging.com.

Here's an example of the warning when switching to AT on a site with a legacy Business plan: 

> **Warning**
> By installing a plugin the following change will be made to the site:
Your subdomain will change from *.wordpress.com to *.wpcomstaging.com.

![image](https://user-images.githubusercontent.com/84193945/176406538-f9fa3911-dfa3-4aab-9c2d-42cc3e4b1c88.png)

### What actually happened

The site is made Atomic, and the URL is changed for example from `*.tech.blog` to`*techblog.wpcomstaging.com` without any warning. 

### Context

Customer report: 35932814-hc / 5327907-zd-woothemes

Internal discussion/initial testing: p1656491813170169-slack-C03TY6J1A

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by arunsathiya** [comment]
This is not an official triage (that'll come from @Automattic/dotcom-pqa-group later) but noting some screenshots of what I noticed too. None of the current upgrade flows show the warning:

- Plugin installation from https://wordpress.com/plugins/ (which may fall under marketplace team, cc @cpapazoglou, I think)
- Pro plan upgrade nudge from https://wordpress.com/themes (cc @paulbonahora or @DavidRothstein)
- Pro plan upgrade nudge from hosting activation screen https://wordpress.com/hosting-config/

Or all three cases may fall under @Automattic/nomado because the popup explaining the address changes is mostly domain-specific.

<img width="1440" alt="image(3)" src="https://user-images.githubusercontent.com/18581859/176410307-90085684-1139-4eaf-9f8a-4742b23ea723.png">
<img width="1440" alt="image(4)" src="https://user-images.githubusercontent.com/18581859/176410342-54f147a8-33f2-4a31-9d73-cb8e54a7a1e8.png">
<img width="1440" alt="image(5)" src="https://user-images.githubusercontent.com/18581859/176410346-a9438b64-6ac0-4c4d-99f3-7ccf8e275417.png">
<img width="1440" alt="image(6)" src="https://user-images.githubusercontent.com/18581859/176410350-0b5d3d60-c3dd-49c3-8289-d0127814ae0d.png">

We should show a consistent popup in all transfers to Atomic that explain the loss of dotblog subdomain address.

**Comment by cpapazoglou** [comment]
Thanks for flagging this. In my opinion, *.*.blog subdomain should be available to Atomic and not lost. @Automattic/nomado  is there something blocking us from transferring these subdomains to Atomic?

**Comment by Greatdane** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I am sure we had a previous issue/discussion regarding this but I cannot find it on GitHub 🤷 . Regardless, confirmed! 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by delputnam** [comment]
> is there something blocking us from transferring these subdomains to Atomic?

This is something that someone on the Atomic team will have to answer.

**Comment by cpapazoglou** [comment]
> Thanks for flagging this. In my opinion, _._.blog subdomain should be available to Atomic and not lost. @Automattic/nomado is there something blocking us from transferring these subdomains to Atomic?

These domains cannot be transferred (p9o2xV-1jE-p2#comment-4279). We need to find out why the warning doesn't popup and fix it.

**Comment by epeicher** [comment]
This is happening because the `domain_mapping` has a value for the `.blog` subdomain, so the following condition
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sryvtvovyvgl.cuc%3Se%3Q89948n49%23348-og
does not meet and the warning is not returned.

If we need to still display the warning we should update that condition. @cpapazoglou , @jmdodd, What additional criteria could we use to identify that a domain will change from `*.blog` to `*.wpcomstaging.com`?

**Comment by epeicher** [comment]
Started a thread asking about this issue here p1667496657336169-slack-C029JEQRVRT

**Comment by cpapazoglou** [comment]
> This is happening because the `domain_mapping` has a value for the `.blog` subdomain, so the following condition [fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sryvtvovyvgl.cuc%3Se%3Q89948n49%23348-og](uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sryvtvovyvgl.cuc%3Se%3Q89948n49%23348-og) does not meet and the warning is not returned.
> 
> If we need to still display the warning we should update that condition. @cpapazoglou , @jmdodd, What additional criteria could we use to identify that a domain will change from `*.blog` to `*.wpcomstaging.com`?

I assume that all [free blog subdomains](https://wordpress.com/blog/2018/11/28/announcing-free-dotblog-subdomains/) are pointing to the Simple sites infrastructure and thus need to change to `*.wpcomstaging.com` when they move to Atomic. This condition should be enough.

**Comment by epeicher** [comment]
Diff created D92473-code

**Comment by delputnam** [comment]
This looks like a good temporary fix, but I think we can actually make these subdomains available on Atomic sites with some help from systems.

**Comment by delputnam** [comment]
FYI, I also submitted a suggested change to the back-end diff to make sure we capture w.link and any other managed subdomains as well.

**Comment by epeicher** [comment]
> FYI, I also submitted a suggested change to the back-end diff to make sure we capture w.link and any other managed subdomains as well.

Thanks for that! I have updated the diff with the suggested changes

**Comment by epeicher** [comment]
Diff deployed r256391-wpcom

**Comment by epeicher** [comment]
Closing this as completed
