### ISSUE TITLE
Themes: Support tab link to wp.com/help/contact over theme forum for users on a plan 

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#6514]
Users on a plan will get faster help at https://wordpress.com/help/contact than the theme-specific forum.

**Comment by folletto** [comment]
![support-help](https://cloud.githubusercontent.com/assets/4389/16764208/c19ca03e-4824-11e6-9078-d6cc4e4b8262.png)

Good idea! :)

Above the design with the copy change for that:

* "Contact us"
* "Get in touch with our support team"
* Icon changed to `gridicons-help`

**Comment by seear** [comment]
Not sure yet how to best determine a _paid user_. Determining if a site is on a plan is straightforward but doesn't seem like the best solution.

**Comment by folletto** [comment]
Can we start with "site on a plan" and then review later?

**Comment by seear** [comment]
> Can we start with "site on a plan" and then review later?

Yes, I think this makes more sense than creating a brand-new API endpoint just for this feature.

**Comment by seear** [comment]
Suggested solution if we want to improve: Add all purchases from /me/purchases endpoint to the store. If there are any purchases, user is entitled to support.

**Comment by andrewspittle** [comment]
> Users on a plan will get faster help at https://wordpress.com/help/contact than the theme-specific forum.

Just to confirm something: Is the plan to make this change for all themes? Or just free themes? Premium themes have theme-specific forums on WordPress.com so I want to be sure we're adjusting what we intend to.

**Comment by folletto** [comment]
That made me thing about another option:

1. Adding the `Card` above with "Contact Us" instead of replacing the existing one.
2. If the "Contact Us" card is present, then it has a blue primary button, and all the others get a white one.

How does it sound?

**Comment by andrewspittle** [comment]
That sounds okay to me. I think what's key is distinguishing _who_ will likely reply to the customer.

- Contact form: Staff (for paying customers).
- Premium Theme forum: Theme shop.
- Free Themes forum: Volunteers.

**Comment by folletto** [comment]
Do you have maybe any copy change suggestion on the three blocks? :)

**Comment by andrewspittle** [comment]
Sure; half-baked idea:

*Staff support for paid customers*
> Need extra help?
> Get in touch with our support team.
> Contact us

*Premium Themes*
> Have a question about this theme?
> Get in touch with the designer of this theme.
> Visit forum

*Free Themes*
> Prefer to use our forums?
> Get help from volunteers in our Themes forum.
> Visit forum

**Comment by folletto** [comment]
They look good. And definitely an improvement. I just changed "designer" to "author" and kept the CSS title on the third one, since it's a specific CSS forum, but the sub-message is good. 

Here's in context:

![screen shot 2016-07-15 at 13 46 40](https://cloud.githubusercontent.com/assets/4389/16874685/94606202-4a92-11e6-8ef2-372ebbc86140.png)

**Comment by kathrynwp** [comment]
Couple of small suggestions based on your screenshot @folletto:

In the second item, to avoid ending two consecutive sentences with "this theme" how about "Get in touch with the theme author" or "Get in touch with the theme developer"

In the third item, there's a typo in "volunteers"  (volounteers)

In third item, suggested rewording a bit since (a) staff does make sure all CSS questions are properly answered, and (b) the CSS forum and Themes forum are two different forums. Suggestion: "Get help from the experts in our CSS forum"

For **free** themes, the second item will be different, since each theme doesn't have its own forum. Suggest a slight variation of what Andrew suggested above, since staff does make sure all Themes questions get a good reply. Could be:

"Get help from volunteers and staff in our Themes forum."

**Comment by folletto** [comment]
Ok, so, here's an updated mock with the two variations:

![support-variations](https://cloud.githubusercontent.com/assets/4389/16916591/744b23de-4cf5-11e6-8dc6-e40654ebc72e.png)

1. The first block is conditional to the availability for that site of the Support (paying customers), and overrides the `is-primary` state of the button too.
2. The second block is a variation depending if it's a Free or Premium theme.

**Comment by andrewspittle** [comment]
Looks good to me overall. To clarify a bit on the logic: we should show the "Contact us" prompt for any paying customer (even those on a free theme). So the "Free state" mockup there would be for those customers currently 1) using a free theme and 2) without any paid upgrade on their site.

**Comment by folletto** [comment]
Thanks for the clarification! 👍

**Comment by kathrynwp** [comment]
Looks good to me too.

**Comment by ockham** [comment]
Possibly relevant selectors: https://github.com/Automattic/wp-calypso/blob/master/client/state/purchases/selectors.js
