### ISSUE TITLE
Site Switcher: Improve the presentation of All My Sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65162]
We want to improve the look and positioning of the `All My Sites` item in the Site Switcher.

<img width="267" alt="Screenshot 2022-07-01 at 22 01 57" src="https://user-images.githubusercontent.com/1182160/176961621-72cdc342-a31e-4901-848b-304fbbe128bb.png">

We want to:

1. Move it to the top above the search bar.
2. Improve the design to make it more prominent, with the goal of driving more traffic to the new Sites Management Dashboard.
3. Add the `New`, `Beta`, or `New Feature` label next to it.

Open questions:

- This link is also used in Jetpack Cloud (Calypso Green) and we need to decide how to handle the changes there.
- Should we also surface the link outside of the Site Switcher at the top level (above My Home for example)?

cc @SaxonF

**Comment by SaxonF** [comment]
@vindl after playing with this for a bit (one iteration below), I actually think we should leave any changes here until we are ready to refresh the global nav bar, especially given its also in use in Jetpack Cloud. 

From a marketing standpoint, that would be the time where we can really promote Dotcom as a platform for managing multiple sites.

What do you think? Either way, not a blocker for launching V1.

![image](https://user-images.githubusercontent.com/1072756/177066482-cd3edef0-2060-485f-bd3d-9a2b602d59d1.png)

**Comment by pablohoneyhoney** [comment]
Do you think `Sites` is too redundant reading it three times? 

A related note on language: https://buildp2.wordpress.com/2022/06/24/multi-site-management-i1-2/#comment-315

**Comment by SaxonF** [comment]
@pablohoneyhoney good point, could probably simplify to "manage" and "Search..."

**Comment by vindl** [comment]
> @vindl after playing with this for a bit (one iteration below), I actually think we should leave any changes here until we are ready to refresh the global nav bar, especially given its also in use in Jetpack Cloud.

If Jetpack Cloud is the only concern, we could gate our changes so they are not shown there. But this looks like something Jetpack Cloud could benefit from too? Looping in @jeffgolenski for thoughts.

**Comment by SaxonF** [comment]
An extension of the previous concept including moving the add site button to a more prominent position. Still faces the challenge of the conflicting "my sites" tab vs "sites/my sites" heading for sidebar. The sidebar could open up over the top of the global bar which may improve things but still not perfect.

![image](https://user-images.githubusercontent.com/1072756/177709135-41988d6f-1a03-48b5-a4e3-ec37e71df045.png)

![image](https://user-images.githubusercontent.com/1072756/177709160-1d81bcc2-c3ec-42cf-9a20-677e54b2bee5.png)

I'm wary of spending too much time on the existing sidebar as I'd like to look at the global bar more holistically. The current "my sites" link (tab?) has always felt confusing to me from a hierarchy perspective as it just takes you to the existing site until you open up the switcher, which behaves separately to the tab. As explored in some of the earlier concepts I think we can emphasise the link back to the sites management page, and the site switcher becomes more of a quick switcher.

![image](https://user-images.githubusercontent.com/1072756/177709080-1c33f82f-9aa8-4302-9a9b-3fab6e63dd3e.png)

**Comment by pablohoneyhoney** [comment]
> I'm wary of spending too much time on the existing sidebar as I'd like to look at the global bar more holistically. 

I'm not sure I agree with this. It could sound too incremental but we don't doo enough incremental work and expect the larger speculation will fix our problems later. Let's tackle now with the best UX now. afaik, the implementation of a better UX on this is fairly trivial. In other words, the current state of the sidebar can use help, and this work can significantly improve what's there, both in the UI and the UX behavior itself, even before added paths and functionalities (dashboard).  

I'd love if we do way more permutations on the below, as it isn't working yet, especially how we associate the affordances.  

<img width="478" alt="Screen Shot 2022-07-08 at 11 00 36 AM" src="https://user-images.githubusercontent.com/25516611/178018539-8c284717-6e6a-4b16-82e7-217f386d31df.png">

For example:

- Perhaps you don't need to repeat `Sites` with the number, and number and Manage all are more integrated. `Manage all 156 sites`, for example. 
- The + seems obscure and less clear of what to expect. It also relates too much with a searching behavior.
- The search should be more related to the list below, not with adding new.
- It could perhaps use some spacing or separator between manage/add, and search/list. 
- It'd be also cool to see a low-fi prototype to understand the behaviors and in/outs of the different affordances. _I search a site, I create a new one, I pick a site and dive in, I go back to the sidebar list, I want to see them all._

**Comment by SaxonF** [comment]
@pablohoneyhoney I don't think these are perfect either but here's a few more concepts to look at:

Reverting back to using bottom space
![image](https://user-images.githubusercontent.com/1072756/178207475-7bcacd16-baea-411d-a27b-2f9e6da6d812.png)

Top actions bar
![image](https://user-images.githubusercontent.com/1072756/178207507-f573d593-c6ce-4386-85c9-129b894f90c4.png)

Removing sidebar title
![image](https://user-images.githubusercontent.com/1072756/178207689-4b9e10ef-4bf9-4883-8fd7-8fe387f262c2.png)

Floating sidebar over top bar 
![image](https://user-images.githubusercontent.com/1072756/178207741-8e189a79-87d8-44b7-8bfa-a71f15c14a90.png)

In terms of behaviour, it wouldn't change from what exists currently. If we did want to make a change, the "My sites" link could open up the sidebar rather than "switch site", but this would be a risky change to make right now and I don't think we are ready for it.

> It could sound too incremental but we don't doo enough incremental work and expect the larger speculation will fix our problems later.

My concern here is one of impact. In my opinion most of the UX issues stem from the global bar and work their way down to the switcher. Iterations to the global bar would have a much bigger impact by generating awareness of the greater site management experience, clarifying the IA, and making site switching more accessible.

**Comment by vindl** [comment]
I wanted to add another point that we should consider. When the user has only one site, the state that all new users end up with, the Site Switcher is not visible, and `Add New Site` is presented differently.

No site switcher at the top:
<img width="271" alt="Screenshot 2022-07-11 at 14 47 33" src="https://user-images.githubusercontent.com/1182160/178277175-7aa7cf0e-40c6-4177-bf85-32d7fb308259.png">

`Add New Site` appears as a regular menu item at the bottom:
<img width="271" alt="Screenshot 2022-07-11 at 14 47 14" src="https://user-images.githubusercontent.com/1182160/178277173-31bb5951-77a3-443a-b65b-6fb4b83bd5fe.png">

Should we align this with the new changes for consistency? I want to make this dashboard accessible to users with only one site, but with current designs, that won't be the case since the link is gated behind the Site Switcher.

**Comment by SaxonF** [comment]
@vindl Good pickup. Yes the behaviour should be the same whether you have one site or many. In the short term we can add the site switcher back to accounts with a single site. This does emphasise the point above about a broken top bar UX though.

**Comment by vindl** [comment]
And here is another inconsistency 😅: when viewing the sidebar from wp-admin `Switch Site` is replaced with `Browse Sites`. Clicking on it navigates to `/home` (the view that the new dashboard will replace):

<img width="270" alt="Screenshot 2022-07-12 at 02 44 41" src="https://user-images.githubusercontent.com/1182160/178384184-bdf42d1c-5e23-4431-9fd9-70e9f17e92d7.png">

This was likely a compromise solution because it was hard to isolate the Site Switcher component coming from Calypso and re-use it in wp-admin for nav unification.

**Comment by jeffgolenski** [comment]
Hey folks — apologies I missed the ping for this earlier @SaxonF @vindl. We're also exploring this from a different angle. It may be best if we sit down to discuss the issues we've heard from customers, the IA, and how we can build something scalable for both our products. 

I do love these explorations, but also agree with @pablohoneyhoney's feedback above. For Jetpack, "Add new site" is not functionality we will have. Sites are added automatically the moment they're connected to a wordpress.com account. It would be ideal to implement a pattern that's modular for that! 

Our big challenge currently is the customers understanding that "Switch site" leads them to the all my sites view, where the dashboard lives and future multi-site management tools will live. @grbicsanja and myself are looking at different levels of the hierarchy to make this more clear.

**Comment by SaxonF** [comment]
Just following up here, @jeffgolenski  and I quickly caught up and have started a cross team discussion around how to best move forward and collaborate on this.

**Comment by keoshi** [comment]
Hey, all! Quick drive-by feedback on these latter options:

![image](https://user-images.githubusercontent.com/390760/178687524-7e8d4d61-9319-45c9-9a5f-74d0399792e7.png)

Specifically on the favicon vs text ratio, I'd point out that while the site image can be distinctive, the site URL is the unique identifier. From that perspective, it seems important to give the text column a bit more room so longer site names and URLs are not cut off.

This is probably not that important for dotcom Simple Sites, but becomes critical when you consider multiple environments of the same self-hosted site like production, staging, development, and more; e.g.:

- outdoor-adventures.com
- outdoor-adventures.com/staging
- outdoor-adventures.com/test

**Comment by grbicsanja** [comment]
Looking at the proposals, I have a few thoughts:

- The goal here is to have users access the Sites management tool. 
- Along the way, we want to make Add new site equally important (correct me if I'm wrong)
- We do not want to disrupt the way users switch between the sites but complement it

Thoughts on the iterations:

![Slice 3](https://user-images.githubusercontent.com/90194580/178725791-6f8c8cfc-9507-4003-8f04-e1145c196c08.png)


- Changing the 'All my sites' menu item to just a link that says Manage sites makes it look less prominent and less important than the single-site view - this is contrary to this project's goals and to the hierarchy it represents. 
- Same if we move it to the bottom when it actually should represent some kind of higher-level view. And it just gets lost down there.
- Making it a button is also a bit weird because it's not about taking action, but changing the view (ie it works for Add new site)
- In any of these cases, on a single site view, there is still nothing to indicate a dashboard exists and can be accessed behind the '< Switch site' nav item.
- As for the Add new site button, have you thought about adding it to the global navigation? I feel like it would fit well at the same level with My Sites and Reader.


Our main goal on Jetpack is to make sure agency users can easily access the tools for managing all sites. In a recent usability test users had trouble finding the dashboard.
We haven't posted this exploration yet, but here's what we're exploring currently on Jetpack 
- I made some edits this morning too, inspired by your explorations, ie aligning on the language used. I tried out moving search below too, but in this exploration, I don't think it works, as it splits the list of clickable items into two parts
- You can see we are also exploring adding a direct link to the dashboard from a single site view, and potentially we might want to add a Licensing shortcut as well.

<img width="1440" alt="Screenshot 2022-07-13 at 13 39 57" src="https://user-images.githubusercontent.com/90194580/178725852-bd633f6f-428a-4bfd-8b53-37892b030315.png">
<img width="1513" alt="Screenshot 2022-07-13 at 13 40 03" src="https://user-images.githubusercontent.com/90194580/178725865-b1a215f1-bdc9-4785-a25f-eeb636804abc.png">
<img width="743" alt="Screenshot 2022-07-13 at 13 40 08" src="https://user-images.githubusercontent.com/90194580/178725872-28f89822-bee1-4cdc-afe4-e6031b5caca8.png">

**Comment by grbicsanja** [comment]
Also, did you plan to do any usability testing for these changes? We use Maze for this and so far it's been pretty easy and straightforward.

**Comment by SaxonF** [comment]
@grbicsanja @jeffgolenski @keoshi Thanks for the input here. 

TBH I think we're going to struggle to find a perfect short term solution. I would currently vote for just moving the "all my sites" link up above search and rethinking the copy as @grbicsanja suggested. We can also just make the add site button more prominent.

![image](https://user-images.githubusercontent.com/1072756/178893989-f712dbc8-f4bc-422e-ba3e-e2d174110d65.png)

While these iterations are underway we can carry on our conversation about higher/global level changes that will help to clarify the `account level -> site level` IA which should also resolve other issues like awareness of site management etc.

> You can see we are also exploring adding a direct link to the dashboard from a single site view, and potentially we might want to add a Licensing shortcut as well.

Definitely understand the goals but it feels confusing from a hierarchy standpoint.

> As for the Add new site button, have you thought about adding it to the global navigation? I feel like it would fit well at the same level with My Sites and Reader.

Since site creation isn't an action that happens _that_ regularly I don't see a huge benefit other than visibility purposes. However, we could explore a generic "create" action lets you create a site, page, post, product etc, though you'd have to deal with site selection for site related actions. Asana do something similar:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/1072756/178896052-d9ca5d87-d1e3-4ba2-8dbf-cb10cbf0ecb0.png">

**Comment by SaxonF** [comment]
pdKhl6-vB-p2 also highlights a few edge cases we need to be wary of. For example, the existing "all my sites" link sometimes takes you to global level pages e.g. if you are on statistics and click that link you are taken to an overview of all sites. The behaviour is not consistent.

**Comment by pablohoneyhoney** [comment]
@SaxonF that link above doesn't get to the desired destination, I think. 

Looking at this, I have a few notes and questions.

![](https://user-images.githubusercontent.com/1072756/178893989-f712dbc8-f4bc-422e-ba3e-e2d174110d65.png)

Copy should likely say: `Manage all sites` 
The whole deal is that you could have multiple sites, mostly not _yours_.

We also don't need the redundancy on `Visit the dashboard`, unless I'm missing something. It's also unclear how we utilize the concept dashboard across the board. Even in Dotcom, is it the My Home or is it a higher level of abstraction?

`Add new site` makes sense, but you wouldn't want to attach it conditionally to the list, because it could hide if the list grows. It's also relevant to see it in context of My Home and other pages, because a blue button could be too prominent in the overall Calypso interface. 

I like the simplicity of what was showed above, but could be challenged by the following questions below in terms of the UX flows (in and outs). And the edge cases @vindl has indicated above. 

![](https://user-images.githubusercontent.com/390760/178687524-7e8d4d61-9319-45c9-9a5f-74d0399792e7.png)


For better understanding the flows:

- What's the behavior of `Manage all sites`? 
- And what's the behavior of `Add new site`. Does it open a dropdown with the options? 
- It's also worth to visualize where you come from. To connect those instances more systematically. 
- How does the sidebar behave with Calypso theming user options? h/t Saxon 
- And also consider the edge cases @vindl has indicated above.

**Comment by vindl** [comment]
Some additional considerations regarding the `All My Sites` link are outlined in pdKhl6-vB-p2. It doesn't always lead to the page with the Site Switcher. Sometimes, it will link to multi-site views depending on the current context (e.g., plugins, domains, posts, etc.), so we need to decide how to handle those cases.

**Comment by SaxonF** [comment]
Based on the feedback above here's where we are at.

https://user-images.githubusercontent.com/1072756/179915612-2ca33b9b-2e17-48aa-9232-4b448279e0c1.mp4

**Overview**
- The sidebar needs to work regardless of what colour scheme is selected. The secondary "manage sites" button uses the secondary text colour with a 25% opacity for its stroke. 
- The behaviour of the bottom section remains the same as it is now, which means it sticks to the bottom of the sidebar when there is a scroll overflow. 
- The add new site dropdown should be adaptive in that it should reposition to the top it ventures outside the bounds of the screen, this is built into the [WordPress Dropdown component.](https://wordpress.github.io/gutenberg/?path=/story/components-dropdown--default)

![image](https://user-images.githubusercontent.com/1072756/179919776-5b1921a0-43a4-4e38-800f-73ad8e602e5d.png)

- When on a page that has a global level equivalent (e.g. pages, posts, statistics) we include an item at the top of the site list that takes people to this global page

![image](https://user-images.githubusercontent.com/1072756/179918293-94a953b2-ffd3-4ffd-abb4-632c8c5b7b73.png)

**Jetpack**
I realise this is a riskier change for Jetpack because they are further along in the cross site management experience and have additional functionality living there. As @vindl mentions above, its worthwhile gating these changes so that Jetpack can decide to opt-in if suitable. We can continue our longer term discussions in the meantime as I'm fairly confident we can find a higher level solution that works for everyone.

![image](https://user-images.githubusercontent.com/1072756/179929634-1bf71306-eed6-49bf-829f-f97ef5693b66.png)

**Comment by jeffgolenski** [comment]
@SaxonF 

> As @vindl mentions above, its worthwhile gating these changes so that Jetpack can decide to opt-in if suitable. We can continue our longer term discussions in the meantime as I'm fairly confident we can find a higher level solution that works for everyone.

Thanks for continuing to push on this! Can you send me the figma file where you're working so we can jam together? We've got a few issues to fix for Jetpack, but it would be nice to see them side-by-side. I'll work on some prototypes as well. Thanks, friends!

**Comment by SaxonF** [comment]
I wanted to re-surface an earlier proposal which is to just separate "my sites" from the WordPress logo and use that to link up the main sites view. WordPress logo would still link to current site's admin home. The site switcher would remain the same for the time being, however we could update the "add new site" button to be more prominent as shown in this thread.

![image](https://user-images.githubusercontent.com/1072756/180150771-5e5ac593-8955-4a68-a7ee-9206b8396786.png)

![image](https://user-images.githubusercontent.com/1072756/180150794-55c59e19-3833-45ab-9b03-a240d59a35c6.png)

Jetpack could use the same pattern

![image](https://user-images.githubusercontent.com/1072756/180154128-d454566d-f972-4c4c-ba1b-4ac0fdd01cc9.png)

The downside to this is that the "my sites" link currently takes you back to the active site's home screen, which is quite strange but also fairly well engrained by now. Changing it might upset a few people.

Given how deep this site switcher discussion has gone though this might actually be as simpler and more visible starting point.

**Comment by pablohoneyhoney** [comment]
[This work above](https://github.com/Automattic/wp-calypso/issues/65162#issuecomment-1189914507) is taking much better shape with greater context on how the flows and cases work. 

A few notes:

- This should likely say the number of sites (otherwise there isn't any reference to the quantity). Manage all xx sites
- Is there another way to represent these buttons more discreetly? I personally like them but in the context of the whole Calypso might gain too much prominence. So it's worth seeing them (or other options) in context. notice that above in the video you dim down the content (which is new behavior), is that the intent or was that just part of the prototype?

<img width="336" alt="Screen Shot 2022-07-21 at 4 42 27 PM" src="https://user-images.githubusercontent.com/25516611/180311575-ec848864-06af-490e-8f73-717a1cdda38b.png">

- Does the button open up a dropdown or is it a modal? What happens exactly after clicking on each option? 
- What does boost your self-hosted site mean? It doesn't seem a clear CTA. 
- The dropdown list now is prioritizing the Boost... which is perhaps not the desire. Could we find a way they are more equal? 
- Shall the resting button say `Add site` or is there another way to make a clearer taxonomy difference between `Add new site` / `Create a new site`. Or is it clear?

<img width="336" alt="Screen Shot 2022-07-21 at 4 42 38 PM" src="https://user-images.githubusercontent.com/25516611/180311555-19f28595-143b-41a8-b369-706cbf64fa26.png">

When in a global feature/view (Stats, Plugins, Themes), the top back button should probably say `Back` instead of `Switch site`. 

<img width="818" alt="Screen Shot 2022-07-21 at 4 50 15 PM" src="https://user-images.githubusercontent.com/25516611/180312795-591d006e-e4ec-48c6-bc57-c4d35650a49c.png">

If you go back and still in a global view, we need to add an access back in, but perhaps the copy can be simplified as `View Stats for all` / `View Themes for all` / `View Plugins for all`
If the number of sites is represented in Manage all xx sites (which is more permanent), perhaps we don't need to say again the number. And rather style this as another button-like to access back in the _global view_ that is visually differentiated from the singular site items.

<img width="415" alt="Screen Shot 2022-07-21 at 4 55 40 PM" src="https://user-images.githubusercontent.com/25516611/180313674-3d1fcd0c-9883-497f-b4e4-c206009d8f37.png">

It'd be neat to see how this logic adapts also to Jetpack @jeffgolenski and Woo.

**Comment by SaxonF** [comment]
After further discussion this is what we've decided to move forward with for the first iteration.

Single sites 

- Move add new site button to bottom of sidebar, under collapse. We can keep the existing, low prominence button style for now.
- Site switcher remains hidden

Multi sites
![image](https://user-images.githubusercontent.com/1072756/181681761-0bb99e8d-0636-4347-b6d1-fffa2827ba5f.png)
![image](https://user-images.githubusercontent.com/1072756/181685883-c158e999-238b-453f-b551-34eb63198582.png)

- Move the add button to bottom of the sidebar and increase its prominence
- The add button will not trigger a dropdown as part of this first release and will behave as it does currently
- Add a "manage xx sites" button to the bottom above add new
- Keep the “all my sites” link when on a page that has a global equivalent, but change copy to "View stats for all sites"
- Hide the “View All Sites” button when on a page that doesn't have a global equivalent as this is covered by the manage sites button below

@jeffgolenski has shown what this may look like for Jetpack where the primary CTA is management. We can still put these changes behind a feature flag to give the Jetpack team time to discuss.
![image](https://user-images.githubusercontent.com/1072756/181684055-deaeabd0-6d80-4bc5-8d98-17a1afc36c96.png)

For the second iteration, when site management is in a better place, we'll be updating the "my sites" link in the toolbar to take users to site management. The WordPress logo will keep the existing behaviour. At this point we will also remove the manage sites link in the site switcher. Icon's are TBD. 

![image](https://user-images.githubusercontent.com/1072756/181683667-e292e708-bba8-4dd4-a541-fce09fe2f7a6.png)

We'll also be looking at adding the Jetpack and import connection "add site" options as discussed elsewhere.
![image](https://user-images.githubusercontent.com/1072756/181685626-6c4726c4-f0dc-4f78-9240-e5c399d608f9.png)

Further iterations we'll be looking at the global nav in general, including how someone might access the site switcher.

**Comment by danielbachhuber** [comment]
Thanks for all of the effort towards producing a solution!

The Site Switcher changes are now being shipped as a part of a project thread: pdKhl6-Fj-p2
