### ISSUE TITLE
Sites Management Dashboard: add site actions to the ellipsis menu

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65174]
_Updated summary after comments:_

Based on the feedback, I compiled a list of items to add for i1. We'll iterate on this further, once we elevate some options to primary actions in list view columns (e.g., launch/checklist) and start showing contextual actions based on the site's type.

- **Launch Site** - show only if the site is not launched yet
- **Settings** - link to `/settings/general`
- **Manage Plugins** - link to `/plugins/manage/{site}`
- **Hosting Configuration** - link to `hosting-config/{site}`
- **Visit WP admin** - link to `/wp-admin/`, open in a new tab
- ~**Hide from list** - https://github.com/Automattic/wp-calypso/issues/66597~

Done is:
- The above links are available in the ellipsis menu and lead to appropriate URLs (test with various site types).
  - [x] Launch site #66642
  - [x] Settings #66641
  - [x] Manage plugins #66641
  - [x] Hosting configuration #66641
  - [x] Visit WP admin #66641
  - [x] ~Hide from list~
- Tracks events are added to record clicks on individual menu items.

**Comment by SaxonF** [comment]
Let's discuss this week but we can also launch without it.

Other options
- Edit site (FSE)
- Launch site
- Unlaunch site
- Manage plugins

**Comment by p-jackson** [comment]
I'm in favour of actions like "launch" because that's info that we are surfacing in the dashboard. Or if we end up with labels for "plan expiring soon", then an action to "renew plan" would be a good one. Maybe "Visit site", which opens the front end in a new tab? (since presumably the primary action for the row will open the back end).

I'm not sure about adding actions that quick-jump to other Calypso areas (i.e. edit site, manage plugins), unless they're something the user can customise. Once a link is added to the list it'll be hard to remove because it'll break people's flows. So we might just add a nav link to the list because we don't have good actions to put there yet and we don't want it to feel empty, but then I worry we'll end up with a very long list of actions as we continue to add things and can't remove any.

**Comment by p-jackson** [comment]
> Delete your site

This isn't a quick action for Atomic sites (which will be many of our users) because it requires talking to Happiness. So I'm not sure we want to add it, and then only have it inconsistently available i.e. it'll be in the simple site menus but not the atomic sites, which seems strangely arbitrary to a user.

**Comment by vindl** [comment]
Based on the feedback, I compiled a list of items to add for i1. We'll iterate on this further in the future, once we elevate some options to primary actions in view columns (e.g., launch/checklist), and start showing contextual actions based on the type of site.

- **Launch Site** -  show only if the site is not launched yet
- **Settings** - link to `/settings/general`
- **Manage Plugins** - link to `/plugins/manage/{site}` 
- **Hosting Configuration** - link to `hosting-config/{site}`
- **Visit WP admin** - link to `/wp-admin/`
- **Hide from list** - #66597

**Comment by p-jackson** [comment]
`/wp-admin/` opens a new tab maybe? I think our wp-admin links usually do this, but I can't find any links anymore. I guess we'd only just removed them all 😅 
(FWIW I'm in favour of having a wp-admin link)

**Comment by vindl** [comment]
> /wp-admin/ opens a new tab maybe? I think our wp-admin links usually do this, but I can't find any links anymore. I guess we'd only just removed them all 😅

Yes, that was my intention and I added it to the top-level summary. 😄 It's still available at the bottom of the sidebar for Jetpack sites, but not shown otherwise.

**Comment by vindl** [comment]
I removed the `Hide from list` from the scope of this task since we decided to punt further work on it. Since the others are already merged, we can close this issue.
