### ISSUE TITLE
Add-ons bug in signup flow if user goes to cart, and then back to add-ons route.

### ISSUE THREAD

**Issue by gmovr** [Automattic/wp-calypso#65341]
Just noticed a bit of a bug/issue: 

If you select an add-on and go to checkout, then going back to the flow will not let you add other add-ons to your cart, until the previous one is "removed" from cart on the checkout page. The previously selected add-on that lingers in the cart is not shown as selected on the add-ons page either. This happened to me with any add-on combination.

![Kapture 2022-07-05 at 15 10 15](https://user-images.githubusercontent.com/1705499/177326526-7d633e14-967f-4a09-966b-879687faa044.gif)

Reproduce:

1. go to `start/add-ons`
2. select "Premium Themes" add-on and go to checkout. do not complete the purchase
3. go back to `start/add-ons` (any way)
4. select "Custom CSS" add-on and go to checkout.
5. "Premium Themes" should still show for checkout (and no "Custom CSS").

@gmovr can you confirm if this is reproducible on your end pls?

_Originally posted by @chriskmnds in https://github.com/Automattic/wp-calypso/issues/64451#issuecomment-1174999502_

**Comment by DavidRothstein** [comment]
I did a little debugging and I think the culprit is this code: https://github.com/Automattic/wp-calypso/blob/6f9e2334a78baf2a34c39a8d9441907d9adaa4e3/client/signup/navigation-link/index.jsx#L110-L112

When the user clicks "Go to checkout" on the add-on page, it hits that code and submits the step with the _default_ dependencies (i.e. not including whatever add-ons the user just selected), thereby leading to the bug.

This is not an issue during the initial path through the signup flow because the user doesn't have a site yet, and thus the above submission actually fails to proceed, since the `siteSlug` dependency of the add-on signup step isn't met (which ultimately prevents the submission from going through): https://github.com/Automattic/wp-calypso/blob/6f9e2334a78baf2a34c39a8d9441907d9adaa4e3/client/signup/config/steps-pure.js#L712

But when you go back into the flow after the site is created, then the dependencies are met, so the submission succeeds.

I'm not sure the right way to fix this (not familiar with how the `NavigationLink` component is supposed to operate) but using something other than `NavigationLink` might be one way to fix it.

**Comment by chriskmnds** [comment]
Nice sleuthing @DavidRothstein ! You have a real knack for problem-solving :D 

I think you narrowed in on the culprit - however, I'm not sure if `NavigationLink` should behave differently there. It does execute the `goToNextStep` callback after submitting the default dependencies it seems (from what I understand, the part you link to). and that's where we supposedly submit the `cartItem`, [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/add-ons/index.tsx#L142). 🤔 

Not sure what happens when these steps get "submitted" and where the navigation to checkout happens. It could be some race condition not submitting the provided/cartItem dependencies before navigating away i.e. if submitting the default dependencies causes completion of flow or something?

**Comment by gmovr** [comment]
Addressed in this PR: https://github.com/Automattic/wp-calypso/pull/65406
