### ISSUE TITLE
Site Switcher: add tracking for clicks

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65353]
It seems like we have no track events tracking for the following two items that will be useful for gauging the impact of changes shipped with Sites Management Dashboard:

- Switch Site clicks,
- All My Sites clicks.

Let's verify if that's actually the case, and if true, add the missing event tracking to Calypso.

One way to observe the events being fired in real-time as you use the app is to set `localStorage.setItem( 'debug', 'calypso:analytics*' );` in the console.

**Comment by zaguiini** [comment]
I was looking at what events we currently dispatch and although they're not track events, apparently we already have the means to understand the impact:

![image](https://user-images.githubusercontent.com/26530524/177833550-5d5dd494-f110-4790-838e-6b9925221904.png)

We're dispatching a GA event on the `Clicked Switch Site` action, and a pageview for `/home`. Isn't that enough? Do we want to use specific tracks features that are not possible with the current implementation (i.e. funnels)?

**Comment by vindl** [comment]
@zaguiini Ideally we'd like to set up funnels for some of these events to compare. If that can be done with the current setup - great! But I'm not sure that that's the case.

**Comment by zaguiini** [comment]
Not possible -- those are different tools. Thanks for the reasoning. Will start adding the tracks events!

**Comment by vindl** [comment]
Let me know if you find the dashboards where we can look at previous trends for these ga events.

**Comment by zaguiini** [comment]
Asked a question in #data about how the tools communicate and if there are processes to normalize the data between them: p1657215624610539-slack-C029ENR23.

**Comment by zaguiini** [comment]
I tried creating a funnel in Tracks: 2cd97-pb.

The problem with that funnel is that there's no guarantee that the user clicked on the `Switch Site` button, then clicked on the `All My Sites` button -- and I doubt that's good enough. However, the GA implementation might be:

![image](https://user-images.githubusercontent.com/26530524/177838953-439e612b-fc28-4905-8b58-238562536db7.png)

That's still not perfect, but at least we're sure that the user first opened the site switcher before browsing to `/home` (effectively what happens when you click on `All My Sites`). That could also have some deviation because you can achieve the same result by removing the site from the URL and pressing `Enter`, but good enough without any modifications.

I asked the Marketing team for GA access so we could browse the project and play with it.

If we want something that's flawless (and I will at least have a PR ready), we'll need to create new tracks events. The only problem is that we won't have historical data (and backfilling is problematic -- p1657216773924619/1657215624.610539-slack-C029ENR23), but that might not be important depending on how much data we need and the sample size. Last case scenario, we export the data and import it  @vindl let me know exactly your thoughts.

**Comment by zaguiini** [comment]
Created the PR with new track events: https://github.com/Automattic/wp-calypso/pull/65388

**Comment by vindl** [comment]
> Last case scenario, we export the data and import it @vindl let me know exactly your thoughts.

Let's just go with the tracks events, no need to export/import the GA historical data.
