### ISSUE TITLE
Task: Review usage of wpcom_product_has_feature()

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#65395]
### Details

Let's review our usage of `wpcom_product_has_feature()` within `wpcom`. The function evolved quite a bit since we first started using it, accepting `Store_Subscription` objects now and also receiving a sister function in `wpcom_purchase_has_feature()` that might be more appropriate in some places.

### Checklist

- [ ] Update usages of `wpcom_product_has_feature()` where we use product slug or product ID instead of the product directly.
- [ ] Replace usages of `wpcom_product_has_feature()` where we're checking `Store_Subscription` objects.

**Comment by mmtr** [comment]
> Update usages of wpcom_product_has_feature() where we use product slug or product ID instead of the product directly.

Is it the goal to only accept `Store_Product` objects? If so, I don't think that's doable without adding extra complexity to the codebase since there are some instances where we only have the product slug / ID available (e.g. all `activate_product`/`deactivate_product` callbacks), so we should add a `get_store_product` call to use the product directly.

IMO it's better if `wpcom_product_has_feature` keeps accepting product slugs and product IDs to abstract that extra complexity.

**Comment by mmtr** [comment]
Said that, I think it's fine to use the product directly whenever is available, so I opened D84148-code to update those usages and to replace the instances where we were passing a `Store_Subscription` object.

**Comment by obenland** [comment]
> IMO it's better if wpcom_product_has_feature keeps accepting product slugs and product IDs to abstract that extra complexity.

Yes, that's what I meant, apologies for the ambiguity.
Thank you for that updating those!
