### ISSUE TITLE
Calypso: Pages not listed

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#65400]
### Quick summary

The pages were not loading for the user in Calypso dashboard. Cleared cache, tried from multiple browsers, but the issue was still there. I was not able to reproduce the issue on my end.

When the user checked on Google Chrome console, it showed this error:

> DOMException: play() failed because the user didn't interact with the document first.

for a code from WordPress.com.

![image](https://user-images.githubusercontent.com/33957570/177950201-ea62a687-cab6-4db9-a429-4c2614479071.png)

They saw the same loading issue on Firefox and Safari as well.

I have seen a similar issue happening to other users as well. 

### Steps to reproduce

I am not able to reproduce, but this is what affected users observed.

1. Go to Pages
2. It showed that the site doesn't have published pages even though the page count showed number.

### What you expected to happen

The Calypso should list the pages on the site for the user,

### What actually happened

The Calypso was not listing pages for the user.

### Context

Chat: 35953388-hc
Followup: 5358630-zd-woothemes

### Simple, Atomic or both?

Atomic

### Browser, operating system and other notes

Google Chrome, Firefox, Safari

### Reproducibility

Intermittent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Asked them to switch to Classic view.

**Comment by halleshubham** [comment]
Shall I give a try ? @devNigel

**Comment by devNigel** [comment]
@halleshubham I was not able to reproduce the issue on the user's account or on my account.

I should have clarified that I am not sure how to reproduce this bug, but it is real and happened to the user.

**Comment by nagpai** [comment]
Another issue here 35976851-hc

Unable to replicate in Support sessions login / proxied browser. 

Browsers: Brave / Chrome on Linux 

I suspect hyperallergic privacy settings of local browser blocking scripts. 

a. Console Error on Brave 

![image](https://user-images.githubusercontent.com/4162931/178667366-5806b202-d8f2-45a0-a7a0-2e4d331a5d7b.png)

b. Chrome privacy settings 

![image](https://user-images.githubusercontent.com/4162931/178667503-317a430b-3777-4a37-bbb9-dac390f46e0b.png)

c. Chrome Console errors 
![image](https://user-images.githubusercontent.com/4162931/178667592-a455948e-dd5e-44c5-b9d4-c0667606ed6d.png)


Workaround - Use Classic view. ( WP admin )

**Comment by nagpai** [comment]
Update : User did a plugin dance and found Elementor core was the culprit. I am not sure if it was Elementor or Its combination with Page optimize.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was not able to reproduce the issue on the user's account from the initial report or on my account. 
- From [this comment](https://github.com/Automattic/wp-calypso/issues/65400#issuecomment-1179507363) it sounds like the author is also unable to reproduce.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - @devNigel Since we are not able to reproduce this issue, I would recommend following up with the user to troubleshoot this further. If you can recreate this issue on a test site, please feel free to reopen with more details.
