### ISSUE TITLE
Launching free site flow: very hard to find the free plan

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#65455]
### Quick summary

If a user wants to launch a free site they are able to go to step 2 by selecting "Choose my domain later" but then they are not able to select a free plan. They have to try to find a domain, scroll down to find "skip purchase" > click "start a free site". It's very hard to find. 

https://user-images.githubusercontent.com/11535091/178300437-e7a1bf61-d8c9-4b74-81ee-3475aad7b0c4.mp4

### Steps to reproduce

1. Get a free site 
2. Try to launch it without a plan and domain

### What you expected to happen

There isn't an option in the launching flow to select a free plan and free domain or at least skip. 

### What actually happened

Step 1: Search for a domain
Step 2: No Free plan option to select

### Context

5364942-zd-woothemes

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Step 1: click "Choose my domain later" > Scroll down to click "Skip purchase"
Step 2: click "Start a free site"

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING

- Labels ✅
- Priority ✅
- Replicable on Core - Not applicable

📌 SCRUBBING

- Tested on P2 - no
- Tested on Simple - not applicable
- Tested on AT - not applicable
- Tested on Self-hosted - not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

- I see the same behavior.

📌 ACTIONS

- Closing this because it's not exactly a bug. It's the intended behavior: p1656516851396149/1656503682.346249-slack-C025Q5RK2

**Comment by wiesenhauss** [comment]
18041484-hc
Another user with the same issue - when trying to launch a free site, the link to 'skip purchase' only appears when the user searches for a domain first (not intuitive). I could reproduce this on a test site.
