### ISSUE TITLE
Marketplace: Missing paragraph break or break element in WooCommerce Subscriptions

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#65461]
![image](https://user-images.githubusercontent.com/545779/178310975-c655d250-7423-463c-9b76-0704b08c6096.png)

There should be a linebreak before the heading.

**Comment by cpapazoglou** [comment]
This should be apparent in all WC.com extensions. It seems that the previous element is a `div` rather than a `p`. That `div` has a class in WC.com that gets stripped in WP.com

|WC.com | WP.com|
|-------|------|
|![CleanShot 2022-07-12 at 11 20 16@2x](https://user-images.githubusercontent.com/12430020/178444311-fb687af3-2e9f-4120-9a62-877fb9621be4.png)|![CleanShot 2022-07-12 at 11 21 05@2x](https://user-images.githubusercontent.com/12430020/178444486-da49c966-5b85-4f89-9165-faf74fe67b37.png)|

One quick solution is adding a `margin-bottom` to all `div` inside the `plugin-sections__content`.
