### ISSUE TITLE
Marketplace: Active plugin with Autoupdates not appearing as such in "Installed on" card.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#65463]
I expected to see an Active and Autoupdates indicator here immediately after an upgrade.

![image](https://user-images.githubusercontent.com/545779/178312652-245bf8e5-219b-4275-9b38-8d571b83b950.png)

**Comment by cpapazoglou** [comment]
We should fix this for the new Plugin details page iteration


![Image](https://user-images.githubusercontent.com/12430020/187210511-4dbfa5e2-0da5-48a3-b189-f12d984035f9.png)

**Comment by WBerredo** [comment]
On Calypso, we should be able to activate/deactivate the plugin but not change the auto update policy, as per WP core:

<img width="1203" alt="Screen Shot 2022-09-02 at 16 56 05" src="https://user-images.githubusercontent.com/5039531/188234065-1ea5082d-e22d-4cf5-8b52-94ef186ca3da.png">

**Comment by WBerredo** [comment]
On Plugin Details iteration we already have the business logic to disable the auto-update management **for Marketplace products**.

<img width="1203" alt="Screen Shot 2022-09-02 at 16 58 37" src="https://user-images.githubusercontent.com/5039531/188234364-2d754706-7230-49ac-838c-54b51d3295bd.png">

https://github.com/Automattic/wp-calypso/blob/259cbafefc7060ea189d65e6a8f964024839b8a3/client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx#L65-L70

Woocommerce doesn't fall on this condition as a free plugin.

----

There is also a static list in some places marking plugins as automanaged. Woocommerce is also not on that list.

https://github.com/Automattic/wp-calypso/blob/259cbafefc7060ea189d65e6a8f964024839b8a3/client/my-sites/plugins/plugins-list/index.jsx#L609-L610

**Comment by WBerredo** [comment]
Given the current ways to tell if a plugin is automanaged, we can come up with two possible solutions:
- Add Woocommerce (and others that might come) to this static list
- Make jetpack provide a way to differentiate an automanaged plugin from the others.

The answer will depend on how many plugins we expect to be automanaged but that is not a paid plugin. Do we have this data or estimation?

cc: @cpapazoglou

**Comment by cpapazoglou** [comment]
> Add Woocommerce (and others that might come) to this static list

The thing is that some plugins like the ones defined in code are managed - installed by wpcom in all plans whereas woo is 
managed only in ecom plans. In biz plan you can install it manually, this happens with all bundled plugins in the ecom plan - woo and some extensions.

Can you try installing woo in a biz plan and check if there is anything else in the response that we can use to identify if it's managed? Otherwise, we will need to alter the jetpack response to include this info OR hard code an `autoManagedPluginsEcom` which will contain the ecom bundled plugins.

**Comment by WBerredo** [comment]
I installed the Woocommerce plugin on a biz plan (not bundled), and it is coming as automanaged. I wonder if Woocommerce is coming as automanaged when installed bundled or standalone and if that is the expected behavior.

<img width="1203" alt="Screen Shot 2022-09-06 at 08 50 34" src="https://user-images.githubusercontent.com/5039531/188639683-9422f527-c84c-4bc0-9c01-0bb1f5cbb0fb.png">

**Comment by cpapazoglou** [comment]
You are right, either something has changed or I was completely wrong! 

In that case, we can add to the static list the products bundled in ecom

https://github.com/Automattic/woocommerce.com/blob/95985d9b256e056dd43dae6470e0fb27b4ee0143/plugins/wccom-plugins/host-plan/includes/packages/class-wpcom-ecommerce.php#L24-L39

and these ones (installed in biz and ecom)?
<img width="1303" alt="CleanShot 2022-09-06 at 16 29 43@2x" src="https://user-images.githubusercontent.com/12430020/188647881-1f2435b4-3596-457f-99ad-6906c2979e07.png">

**Comment by WBerredo** [comment]
We also have this list of pre-installed plugins, which will present the plugin page in the following way.

https://github.com/Automattic/wp-calypso/blob/d748783cb09b7961ee7ff276fd5eb7bc10eb2ebd/client/my-sites/plugins/constants.js#L7-L15

<img width="1103" alt="Screen Shot 2022-09-06 at 09 40 53" src="https://user-images.githubusercontent.com/5039531/188650264-a5bdaeac-3388-424e-927d-549c3c5bdd61.png">


---

For Woocommerce I think the first version is better: you should be able to activate/deactivate and would see a tooltip warning about the autoupdate being disabled due to the automanaged part.

**Comment by WBerredo** [comment]
I checked the current behavior with @jmdodd and the current behavior is the expected one. Its preferred for Woocommerce to be automanaged.

---

>[Wesley Berrêdo]
[...]if I install the woocommerce plugin (standalone, not bundled with other plugins), it is coming as automanaged as well, do you know if this is the expected outcome?


>[Jennifer Dodd]
Yes, it is an expected outcome.
If available in a chroot, the managed version of a plugin is used if it is being installed via the Atomic API.
[...]
It is generally preferable for a plugin (if available like WooCommerce) to be managed because then the platform
1\. doesn’t have thousands of copies of the same files taking up space for each site, 2. can roll back those copies if a release has problems, 3. means that those files can’t be edited (e.g. “hacked”) if a site is compromised.

**Comment by cpapazoglou** [comment]
> We also have this list of pre-installed plugins, which will present the plugin page in the following way.
> 
> https://github.com/Automattic/wp-calypso/blob/d748783cb09b7961ee7ff276fd5eb7bc10eb2ebd/client/my-sites/plugins/constants.js#L7-L15
> 
> <img alt="Screen Shot 2022-09-06 at 09 40 53" width="1103" src="https://user-images.githubusercontent.com/5039531/188650264-a5bdaeac-3388-424e-927d-549c3c5bdd61.png">
> 
> For Woocommerce I think the first version is better: you should be able to activate/deactivate and would see a tooltip warning about the autoupdate being disabled due to the automanaged part.

that's accurate! The first version looks better to me too.
