### ISSUE TITLE
WooCommerce Subscriptions installed without access to WooCommerce Payments also

### ISSUE THREAD

**Issue by janmckell** [Automattic/wp-calypso#65525]
### Quick summary

You can go through a limited installation of WooCommerce Subscriptions with the Starter plan (and it correctly installed WooCommerce as well), but then needed to activate to Pro to install something like WooCommerce Payments — installing our own extensions should be limited, or we should automatically install WooCommerce Payments.

### Steps to reproduce

1. Started at Plugins
2. Installed WooCommerce Subscriptions
3. WooCommerce automatically installed
4. WooCommerce Payments did *not* automatically install
5. When attempting to install WooCommerce Payments, I was asked to upgrade to Pro

### What you expected to happen

I'd be able to install WooCommerce Payments, since it's needed for WooCommerce Subscriptions, to work.

### What actually happened

I was asked to upgrade to Pro, in order to install WooCommerce Payments.

![Markup on 2022-07-12 at 11:35:24](https://user-images.githubusercontent.com/84089207/178696786-0ccc2cc8-7308-466d-bc06-fd73aa436a24.png)
![Markup on 2022-07-12 at 11:35:37](https://user-images.githubusercontent.com/84089207/178696848-bf77071a-3755-40eb-bc1f-4b01951ca1d9.png)

### Browser

Mozilla Firefox

### Reproducibility

Once

**Comment by dsas** [comment]
The dependency on a payment gateway is documented [here](https://woocommerce.com/document/subscriptions/payment-gateways/). It seems reasonable to just install the [free WooCommerce Payments extension](https://woocommerce.com/products/woocommerce-payments/), it could be added as a dependency.

**Comment by cpapazoglou** [comment]
We can do one of the following:

1. Add it as a requirement for each WC.com extension
2. Automatically install whenever `woocommerce` gets installed

**Comment by obenland** [comment]
Do we have the concept of plugin dependencies outside of Marketplace plugins? It might be easiest to go with 1.

**Comment by obenland** [comment]
Just checked on how this is handled for the eCommerce plan to see if we can learn from that, but it just has WooCommerce Payments as part of its software set (2cef6-pb/#plain).

**Comment by cpapazoglou** [comment]
Here is the related diff D84517-code that adds WooCommerce Payments as a requirement for every woo extension. I have found this method more explicit and straight forward than bundling it with `woocommerce`.

> Do we have the concept of plugin dependencies outside of Marketplace plugins? It might be easiest to go with 1.

AFAIK that any WP plugin that needs other plugin as requirements follows on of the following:
- Autoloads them through their code - this is what wordpress-seo-premium currently does with wordpress-seo, though they are deprecating this method.
- Pops up messages in WP Admin that requirements are missing with a CTA to install them - this wouldn't work in our case since users don't have the `manage_plugins` permission. It feels hacky overriding it only for one plugin.

**Comment by cpapazoglou** [comment]
D84517-code is ready for review.

**Comment by cpapazoglou** [comment]
Deployed r249736-wpcom
