### ISSUE TITLE
Theme/Plugin Bundling: Update the processing step to install other plugins

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#65558]
Related to #65100

NOTE: We may not implement this for the first pass since we're initially only bundling WooCommerce.

We need to update the processing step so it can install any plugin that's bundled with a theme.

**Comment by markbiek** [comment]
We should be able to modify `/atomic/transfers` to handle this. The advantage of that approach is we don't have to worry about plugin order since the Atomic API would handle that for us.

See comments from @obenland on paYKcK-1R4-p2 for more details.

**Comment by mreishus** [comment]
There are several ways to atomic transfer, but I see three main ones:
* **v1 endpoint**: `/automated-transfers/initiate`
  * `public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-sites-automated-transfers-initiate-endpoints.php`
  * This is used when I click the button in Settings -> Hosting
  * Caly has some action creators for this [1](https://github.com/Automattic/wp-calypso/blob/383101aa5d44f48d74a64445754b7a03f301cc35/client/state/data-layer/wpcom/sites/automated-transfer/initiate/index.js#L20), [2](https://github.com/Automattic/wp-calypso/blob/383101aa5d44f48d74a64445754b7a03f301cc35/client/state/themes/actions/theme-transfer.js#L45)
* **v2 endpoint**: `/wpcom/v2/sites/$blog_id/atomic/transfers`
  * `wp-content/rest-api-plugins/endpoints/sites-atomic-transfer.php`
  * Caly has an [action creator](https://github.com/Automattic/wp-calypso/blob/383101aa5d44f48d74a64445754b7a03f301cc35/packages/data-stores/src/site/actions.ts#L327) to call this
    * This takes a `software_set` argument which is a predefined set of plugins to install. Used by marketplace. 
      * A hook is added that adds information to the transfer meta before the transfer is initiated.
    * @obenland suggests adding a `software` argument that also works by setting a transfer meta. We can make this one more flexible than the predefined sets used by `software_set`.
* **Backend** 
  * automatically starts transfer on ecommerce purchase
    * `activate_product()` checks for ecommerce plan and automatically runs `->initiate_transfer();`

What I'm wondering now is when exactly will the atomic transfer happen during the flow, and which side will start the transfer (calypso or backend).  For example, if I buy an ecommerce plan and a theme with plugin at the same time, when I submit the checkout page, the transfer will already be started by the backend and it will be too late for calypso to request a transfer, and too late to add the software meta.

On the other hand, if I buy a business plan and a theme with plugin at the same time, no transfer will be initiated, and we will need calypso to request it.

So maybe we need both the v2 api and the backend to be able to support setting the software meta?  
Or maybe we can change the backend to automatically initiate transfers when buying premium themes with plugins bundled, and that will set the software meta?

**Comment by mreishus** [comment]
There will also be the case of users who already have an atomic site buying a bundled (theme+plugins). In this case, we'll need to install the plugins without using an atomic transfer.

**Comment by mreishus** [comment]
If the source of truth for plugins bundled with themes is the new taxonomy added on theme.wp.com, I don’t think the wpcom backend has access to that information.

(This is related to the problems we’ve seen when the auto-loading-homepage tag is desynced and exists on theme.wp.com but not in style.css. Calypso reads from the data on theme.wp.com, the wpcom backend reads from style.css).

Therefore, we must have calypso initiate all commands to initiate atomic transfers and/or install plugins for purchases of premium themes with plugins bundled.

**Comment by mreishus** [comment]
I traced through the process of creating a new site, buying a business plan, choosing sell intent, choosing simple, and picking a premium theme. I went through these urls:

```
http://calypso.localhost:3000/start/domains
http://calypso.localhost:3000/start/plans
Choose Business
http://calypso.localhost:3000/checkout/MYSITE?signup=1
Pay
http://calypso.localhost:3000/setup/goals?siteSlug=MYSITE&notice=purchase-success
(I choose sell as a goal)
http://calypso.localhost:3000/setup/vertical?siteSlug=MYSITE&notice=purchase-success
http://calypso.localhost:3000/setup/options?siteSlug=MYSITE&notice=purchase-success
http://calypso.localhost:3000/setup/storeFeatures?siteSlug=MYSITE&notice=purchase-success
(Given simple or power choice, I choose simple)
http://calypso.localhost:3000/setup/designSetup?siteSlug=MYSITE&notice=purchase-success
Choose a premium theme with the plugin bundled -> click "Start with Baxter"
http://calypso.localhost:3000/setup/processing?siteSlug=MYSITE&notice=purchase-success
Sends me to /home
```

A good place to start is to have `/setup/processing` send you to the new flow, and have the new flow kick off the atomic transfer with the instruction to install the plugin.

---

Another possible location is the 'pickDesign' function that runs when you click the `[Start with THEME]` button in the top right of the design picker.

https://github.com/Automattic/wp-calypso/blob/f665a893d8ef278be47c8042837b78cf718cb8f0/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx#L160

This ends up calling `setDesignOnSite`. https://github.com/Automattic/wp-calypso/blob/f665a893d8ef278be47c8042837b78cf718cb8f0/packages/data-stores/src/site/actions.ts#L284

Maybe this is less fragile than hoping the second flow to issue the correct commands?

Thinking about it again, I'm more inclined to use the new flow to issue the command. An action creator sending off atomic transfers in some situations feels like it could be unexpected.

---

The processing step is designed to run a pending action before you proceed.
https://github.com/Automattic/wp-calypso/blob/0fd298418d5901953c7ea4c6e4d19fdcf9ed4a96/client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx#L31

**Comment by mreishus** [comment]
I have a better understanding of this now that I've been working in this area.

### Clearing up some of my ideas from the previous note:

* In #66832 we got the handoff between the site-setup flow and the plugin-bundle flow working.
* `setDesignOnSite()` does not seem an appropriate place to issue plugin install or atomic transfer commands.
  * In #66832 I added a `.then( () => ...` that runs after  `setDesignOnSite()` and dispatches `requestActiveTheme()`. The data retrieved includes the plugin taxonomy information.
  * The `submit()` function of the site-setup flow checks the plugin in the taxonomy and uses `setBundledPluginSlug()` to store the plugins to be installed in the site store.
* Already existing steps will be useful: `wooConfirm` does an atomic transfer, and `wooInstallPlugins` installs (hardcoded) plugins.
  * `wooInstallPlugins` calls `initiateSoftwareInstall( site.ID, 'woo-on-plans' )`, which does a request to `/sites/SLUG/atomic/software/woo-on-plans`.
  * `wooConfirm` + `wooTransfer` seems close to being a generic atomic transfer step. However, [it does check the 'woop' feature ](https://github.com/Automattic/wp-calypso/blob/059e81c1acfa12d76ab5e0aa9c28ec113ed35fdc/packages/data-stores/src/site/selectors.ts#L125-L127), it doesn't look like it checks the atomic feature?, and it has some woocommerce specific text.
* The `processing` step is a generic step to run anything that other steps queue up with `setPendingAction()`.

### Current Behavior: Installing Additional Software

We use a POST `/sites/SLUG/atomic/transfers` with `software_set=woo-on-plans` in the post body for newly transferred atomic sites. [Link](https://github.com/Automattic/wp-calypso/blob/843615650d4da0b29f0544a18ea9213e51096196/packages/data-stores/src/site/actions.ts#L359-L361)  [Link2](https://github.com/Automattic/wp-calypso/blob/843615650d4da0b29f0544a18ea9213e51096196/client/landing/stepper/declarative-flow/internals/steps-repository/woo-transfer/index.tsx#L87)

We use a POST `/sites/SLUG/atomic/software/woo-on-plans` to install it on already atomic sites.  [Link
](https://github.com/Automattic/wp-calypso/blob/843615650d4da0b29f0544a18ea9213e51096196/packages/data-stores/src/site/actions.ts#L477-L479) called by the [woo-install-plugins step.](https://github.com/Automattic/wp-calypso/blob/843615650d4da0b29f0544a18ea9213e51096196/client/landing/stepper/declarative-flow/internals/steps-repository/woo-install-plugins/index.tsx#L60)

### Plugin-Bundle Flow: Woocommerce only support PR

In #66880, I set the woocommerce plugin taxonomy to be use the `wooTransfer` and `wooInstallPlugins` steps to AT transfer and install woocommerce.

### Next steps: More flexibility

The next steps for this issue would be to make it more generic with regard to which plugins are installed. 

We could either embrace the "softwareSets" notion, or go more flexible by supporting individual plugins passed as a param called "software".

#### If using softwareSets

* The theme meta information would represent softwareSets, not individual plugins.
  * Possibly rename the theme taxonomy to reflect it stores softwareSets. :heavy_check_mark: 
    * We have completed this.
  * Software sets are defined in `wp-content/lib/atomic-v2.php` (example: `woo-on-plans`) and are collections of plugins.
  * We would modify or copy the `wooInstallPlugins` and `wooTransfer` steps to use specified softwareSets instead of `woo-on-plans`.

#### If using plugins

* The theme meta information might need to include actual plugin names, like `woocommerce/woocommerce.php`. Is that settable in a slug, or are some characters not allowed?
  * If it isn't allowed, we might need some sort of translation layer between 'short plugin slugs' and 'real plugin names'. But this does sound suspiciously close to a softwareSet. 
* We would probably have to modify `setBundledPluginSlug` to accept multiple plugins rather than just one.
* The `/wpcom/v2/sites/$blog_id/atomic/transfers` endpoint would need to support `software` in addition to `software_set`.
  * Because users can have sites that are already atomic, we need a way to install plugins without doing a new transfer.
    * We would need to modify the `/sites/SLUG/atomic/software/` endpoint to take individual plugins instead of softwareSets, or to make a new endpoint to support this.

### My Preference

If we aren't going to add too many different plugins that are bundled with themes, I lean toward embracing the softwareSets: We can have one abstraction that's used to install software at the same time as transfer instead of two different ones.  Additionally, having plugin names come from a predefined list in the backend seems safer to me than accepting POST input with plugin names.

**Comment by markbiek** [comment]
My understanding at this point is that we'll mostly be bundling woocommerce and then maybe some woocommerce add-ons on top of that. Bundling other non-woo plugins is a long way off.

To that end, I agree that softwareSets coming from a predefined list makes the most sense.

**Comment by markbiek** [comment]
@mreishus Is there anything left to related to this issue? I kind of feel like it's all been addressed at this point.

**Comment by mreishus** [comment]
I think we're good. The only limitation I know of right now is that we're locked to the `woo-on-plans` software set.
