### ISSUE TITLE
Improving Titles and Labels in Plugins Page

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/wp-calypso#65574]
Besides obvious design improvements to the https://wordpress.com/plugins/ page (for which we can open a different issue), it's worth adding slightly better labelling and titles for more context, storytelling, and precision to categories, actions, and the whole marketplace/plugins page. These below are only suggestions @michaelpick, hopefully the intent comes across. 

- [ ] `Plugins you need to get your projects done` to something like `All the plugins to power and flex your site`

- [ ] `Top` is redundant, we use it everywhere so it becomes irrelevant. Add more storytelling, elevate each category. 
Not `Top paid plugins` but `Featured Paid Plugins`.
Not `Editor’s pick`, but `Our Developers Favorites` 
Not `Top free plugins`, but `The Free Essentials`
Other examples:
`Everyone's favorites`, `Must-Haves`, `Try Something New`, The etc. 

- [ ] `Browse all` links need to say (because they don't live immediately close to the title) what you actually are going to browse. Like `Browse all paid plugins`, reinforcing where you go. 

- [ ] `Learn more` isn't enough. Something like `Learn more about plugins in WordPress.com`

- [ ] `Add additional features to your WordPress site. Risk free.` should say `WordPress.com`, right?

And a more higher level of question: why aren’t we promoting more clearly our Jetpack standalone plugins offering (or the ones we can provide explicitly) as a case study of how plugins provide a better, more flexible version of your site? It’s almost a subtle educational/promotional opportunity of the value of plugins. It can also reinforce the association JP/Dotcom.

**Comment by SaxonF** [comment]
All looks good! 

How about "Give your site super powers" as a title?

The only one I'd push back on is `Learn more` for each category. I don't feel like the additional context is needed and it could get lengthy when we have longer category/collection titles.

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/1072756/180145890-aaef96a6-5618-4b62-823c-f002b65632ce.png">

**Comment by michaelpick** [comment]
Hey. Sorry that I'm just getting to this. I'd be happy to put a top-to-bottom copy spring clean for this page on my to-do list if that helps? I could mock something up fair swiftly for the main pieces.

In the meantime, a few more ideas to riff on your suggestions @pablohoneyhoney, injecting a little more voice into things (as Matt suggested would be good to see) without sacrificing clarity:

### Headlines
> 'Plugins you need to get your projects done' to something like 'All the plugins to power and flex your site'

First up, taking a page from the Apple playbook – a punchy, playful, staccato headline, supported by a more informational subhead:

# Plugin. Turn On. Max Out.
### Go further, faster with plugins: one-click feature power-ups for your WordPress.com site.

**Variant headlines:**
- Plugin. Turn On. Span Out. <-- As in [spanning out](https://www.urbandictionary.com/define.php?term=Spanning+Out).
- Plugin. Turn On. Add Clout. <-- Leans a little harder on the power boost.
- Plugin. Turn On. Geek Out. <-- Leans into geeking up our voice, literally.
- Plugin. Turn On. Far Out. <-- A little twist of Jobsian post-hippy awe.

H/T to Timothy Leary 😉 

**Variant subheads:**
- Plugins are one-click power-ups for your WordPress.com website. 
- Plugins are one-click, do-anything power-ups that take your WordPress.com site further.
- Browse, buy, and add plugins: one-click power-ups for your WordPress.com site.

--
A few different approaches, dispensing with the subheading:

# 50,000 Ways to Take Your Site So. Much. Further.
(Additional emphatic periods optional 😉 <-- puts focus on the wider ecosystem of plugins which may not be appropriate here?)

# Buckle Up and Give Your Site a Power Boost With Plugins
(Slightly playful, focus on unlocking the power/forward momentum following the addition of plugins)

# Give Your Site a Shot in the Arm With Plugins
(Plugins as vitamins)

# Go Further, Faster. Flex Your Site's Features with Plugins.
(Alliteration FTW. Starts with the why, follows with the how)

# An Infinite Library of Plugins to Power-up and Expand Your Site.
(A Borgesian spin on things for a good measure, with a little factual qualification as chaser)

---

### Curation-focused subheads

> Top is redundant, we use it everywhere so it becomes irrelevant. Add more storytelling, elevate each category.
Not Top paid plugins but Featured Paid Plugins.
Not Editor’s pick, but Our Developers Favorites
Not Top free plugins, but The Free Essentials
Other examples:
Everyone's favorites, Must-Haves, Try Something New, The etc.

I love these suggestions. What if you collided a couple together for the first one, to give you:

- Must-Have Premium Plugins
- Our Developers' Favorites
- The Free Essentials

### CTAs/navigational microcopy

> Browse all links need to say (because they don't live immediately close to the title) what you actually are going to browse. Like Browse all paid plugins, reinforcing where you go.

I think 'Browse all' works in the context of this layout, as with @SaxonF's Apple example. 'Browse {Premium/Paid}' (I saw we were going with Premium vs. Paid?) and 'Browse Free' might help reduce line length while adding a pinch more wayfinding clarity.

## Learn more section

> Learn more isn't enough. Something like Learn more about plugins in WordPress.com

This looks to be a section header on the page, pointing to different tutorials. I wonder if it would be more effective at the bottom of this screen. If folks are confused, they'll scroll past calls to action to find more information, and would then find it. This would then allow the secondary value prop section below a little more breathing room.

A few variations for the 'Learn More' section header:

## Learn more about plugins

## Get to grips with plugins

## Get up to speed on plugins

## Plugin How-Tos

## Level up your plugin game

## Get started with plugins


### Secondary value proposition
> _Add additional features to your WordPress site. Risk free._ should say WordPress.com, right?

I'm not entirely convinced the current copy pulls its weight here. Let's assume I don't anticipate there being any risk in the first place. Or might interpret risk another way – most commonly this pattern is used to indicate a warranty/money-back guarantee/no commitment free trial.  

The first column unit of supporting copy emphasizes dotcom plugins being fully managed, which is really the key benefit we're selling, right? I think we could do a little more with these final three columns – I'd be happy to circle back to that if that sounds good?
 
For now, some alternative ideas for this section headline:

## Magically updated. Massively secure.
(Two key features of managed plugins, with a bold, alliterative twist)

## You pick the plugin. We'll take care of the rest.
(Lean into low-hassle and instant gratification)

## Always up to date. Never under threat.
(Variant of two of three key benefits, with always/never ping-ponging)

## Forget updates and security. We've got you.
(Variant; conversational, benefits driven, and reassuring)

## Fast. Secure. And hassle-free.
(Call out key benefits in a scannable format)

## Fast. Flexible. And fully secure.
(Variation of above, with alliteration)

## One click. And you're done.
(Call out the key benefit / lack of need to do anything yourself)

## Plugins. Minus the headaches.
(Painklllers sell more than vitamins)

Let me know if it would be useful to draft up a top-to-bottom take on this, or if there's anything else I can help with here. I can keep iterating if none of these land or we'd like to explore a little further!

**Comment by cpapazoglou** [comment]
I have added this to the Dotcom Marketplace board, but it's unclear to me what changes should be done. Can we gather all changes in one comment?

**Comment by vinimotaa** [comment]
Hi folks!

Thanks for all the inputs - I put together a mockup for us to make some decisions here.

- I have replaced the main header with @pablohoneyhoney initial suggestion. I think that is clear enough and doesn't require further subheadings. Perhaps this is something we can revisit in case we go ahead with a "unified Marketplace" which will require us to rethink the entire header.
- In this mockup, I'm redesigning the existing section title, adding a subheader to each title. This will give us more room to provide even more context to the sections. This same pattern will be applied to categories - for every plugin category you visit, we'll have the category name and a supporting subheader providing more context to that specific category.
- I came up with a draft for all the section's suheader, but happy to refine it further based on feedback.

![marketplace](https://user-images.githubusercontent.com/97929097/187081512-6d31c812-0bdf-41a2-8a15-90e812a941df.jpg)

@michaelpick @cpapazoglou @SaxonF

**Comment by cpapazoglou** [comment]
Thanks @vinimotaa, we will pick this up as soon as it has been finally approved.

**Comment by vinimotaa** [comment]
@michaelpick, whenever you have some time, could you please double-check these titles/labels so we can work towards implementing them? This is pretty much related to the categories descriptions in terms of consistency. This Title+Description will be a standard in the Marketplace.

![marketplace_labels](https://user-images.githubusercontent.com/97929097/188124255-11a075f4-e71c-4134-8d14-a9263224bead.jpg)

Thanks a lot Michael!

**Comment by michaelpick** [comment]
Hi @vinimotaa – sure, happy to circle back to this! 

I'll apply the heading/subheading pattern you mentioned.

Just to clarify, it sounds like you:
- ❌  Aren't looking for additional suggestions for the page headline and other elements covered in my [earlier reply](https://github.com/Automattic/wp-calypso/issues/65574#issuecomment-1192738976)
- ✅  Would like a review of section headings and subhead pairings for the main sections of the page (like 'Our developers favorites' etc.)

Let me know if I've misread that!

As there's some nice crossover, I'll work on this in parallel with #67171 and aim to get you both on Monday if that works?

**Comment by vinimotaa** [comment]
Hi @michaelpick, thanks for getting back!

> Aren't looking for additional suggestions for the page headline and other elements covered in my https://github.com/Automattic/wp-calypso/issues/65574#issuecomment-1192738976

We're still open to better options. We selected those from your previous suggestions, but please let us know if you have better recommendations!

> Would like a review of section headings and subhead pairings for the main sections of the page (like 'Our developers favorites' etc.)

Yes! Those subheads were written by me as a first draft. The idea of having those is to add more context to each section. Again, if you have better alternatives, feel free to suggest them so I can put a mock-up together!

**Comment by michaelpick** [comment]
Cool, thanks @vinimotaa! I'm on the case with this today 👍

**Comment by michaelpick** [comment]
Hi again @vinimotaa 👋 

Connected to the category description labels in #67171 and the [style consistency notes](https://github.com/Automattic/wp-calypso/issues/67171#issuecomment-1237449674) I left there, here's some fresh copy for the above:

## Page headline variations
I've kept this without a subheading, as with the current selection. Let me know if you'd me to riff on some subheadings, too. I think the headline you've picked works as is, but here are some others for coverage (my personal favorite in bold):

- **Flex your site's features with plugins**
- Power-up and flex your site with plugins
- Flex your site faster with plugins
- Reimagine what's possible with plugins
- Go further, faster with plugins
- Plugins take your site further, faster
- Take your site further with plugins
- Meet plugins: a fast, flexible way to take your site further
- Plugins: a fast, flexible way to take your site further

## Must-have premium plugins
{{Note the sentence casing, although an exception could be made for 'Premium Plugins' if we choose to title-case features}}

Subheadings for coverage (personal preferences in bold):

- Jump straight into the most popular plugins on WordPress.com
- Jumpstart your site with the most popular plugins on WordPress.com
- **Get a jumpstart with our most popular plugins**
- Add the plugins our customers use most
- **Add the best-loved plugins on WordPress.com**
- Check out the plugins WordPress.com users install first
- Jump straight into the plugins our users install first
- Start out with these popular plugins
- Hit the ground running with these plugin essentials
- Start growing your site faster with these popular picks
- Get a head start with these essential plugins
- Grab the most popular plugins on WordPress.com
- Add the most popular plugins on WordPress.com
- Get a head start with the most popular plugins
- Start faster with the most popular plugins
- Dive right in with the most popular plugins
- Start fast with the most popular plugins on WordPress.com
- Snag the most popular plugins on WordPress.com
- **Meet the most popular plugins on WordPress.com**
- Add the most popular plugins with WordPress.com users

## Our developers’ favorites
- Grab the plugins most loved by the WordPress.com team.
- **Get the WordPress.com team's most-recommended plugins.**
- Get on the inside track with WordPress.com developer's favorite plugins
- Add the plugins our developers wouldn't live without
- **Grab the plugins our developers install first**
- Get the inside scoop with these WordPress.com team picks
- Install the plugins the WordPress.com team swears by
- Get a head start with these WordPress.com team picks
- Add these WordPress.com recommended plugins
- **Start fast with these WordPress.com team picks**

## The free essentials

- Start free-as-in-beer with these plugin essentials
- Give your site a boost with these zero-cost essentials
- Add these free plugin essentials to your site
- **Add and install the very best free plugins**
- Add these popular free plugins to your site
- **Start out free with these zero-cost plugins**
- **Start out free with these zero-cost essentials**

Breaking out of the verb-led pattern:

- Plugin essentials that won't cost you a penny
- **Essential plugins that won't cost you a penny**
- Powerful plugins at everyone's favorite price (free)
- **Essential plugins. Entirely free.**

## Get started with plugins

- Learn everything you'll ever need to know about plugins, fast.
- Handpicked articles to get you up and running with plugins
- Learn anything and everything about plugins with these quick reads
- Get up to speed on plugins, fast. No experience necessary.
- Learn the ins and outs of plugins, fast.
- Helpful how-to, deep-dive, and quickstart guides to plugins
- **Go further, faster with plugins. With a little help from these guides.**
- Take plugins further, faster. With these how-to articles.
- Learn all about plugins with these guides. In minutes, not hours.
- **Everything you ever wanted to know about plugins. In minutes, not hours.**
- **Our favorite how-to guides to get you started with plugins.**

## You pick the plugin. We’ll take care of the rest.

### Fully managed
Premium plugins are fully managed by the team at WordPress.com. No security patches. No update nags. It just works.

### Thousands of plugins
- From our hand-curated collection of premium plugins to thousands of community plugins. If you can think of it, there's a plugin for it.
- **From WordPress.com premium plugins to thousands more community-authored plugins, we've got you covered.**
- Whatever job you need to get done, there's a plugin that'll make it happen. Draw on our curated collection of premium plugins or thousands of community plugins besides.
- **Whatever you need to get done, there's a plugin that'll make it happen. Pick from WordPress.com premium plugins or your choice of thousands of community plugins.**
- Whatever you need to get done, there's a plugin that'll make it happen, fast.

### Flexible pricing
- **Pay yearly and save. Or keep it flexible with monthly premium plugin pricing. It's entirely up to you.**
- Pay, your way. Save with annual payments or keep it flexible with monthly premium plugins.

---

As always, let me know if I can iterate, further narrow down the selections above, or otherwise lend a hand!

**Comment by vinimotaa** [comment]
Hi @michaelpick, thank you for this!

I have updated the mock-up - let us know if there is anything else we should change!

![marketplace_labels](https://user-images.githubusercontent.com/97929097/188646281-16605b48-284a-47d2-b868-622192ed93aa.jpg)

@cpapazoglou I think we're good to go with these labels. 

[Figma file here](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=3760%3A33005)

p.s: this implementation relates [to this](https://github.com/Automattic/wp-calypso/issues/67239) as we now have to add the subheadings.

**Comment by vinimotaa** [comment]
Specs here:

![marketplace_labels_specs](https://user-images.githubusercontent.com/97929097/188648043-4ccf71cd-361a-4ae2-b651-0675f7634eea.jpg)

**Comment by michaelpick** [comment]
Thanks @vinimotaa! Looking good 😎

**Comment by lsl** [comment]
@vinimotaa were you going to update the how to guide links? I see the text is bolded but design hasn't changed and we'll need the links too.

**Comment by lsl** [comment]
Screenshots / calypso live of these updates here https://github.com/Automattic/wp-calypso/pull/67636 @vinimotaa there is quite a lot of changes, could you review?

I'm also not updating the category page headers themselves - there is a bit of a discrepancy between title sizing, guessing that will be resolved as part of https://github.com/Automattic/wp-calypso/issues/67239 ?

**Comment by vinimotaa** [comment]
Hi @lsl !

For specs, you can find the [Figma here](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=4273%3A39668). There is a full gridsystem and padding specifications for the entire page.

**Comment by lsl** [comment]
Thanks, the first PR should get most of this, remainder fixes tracking in https://github.com/Automattic/wp-calypso/pull/67781#issuecomment-1250436102.

**Comment by lsl** [comment]
Auto closed, there is still some more to do in https://github.com/Automattic/wp-calypso/pull/67781#issuecomment-1250436102

**Comment by lsl** [comment]
This should be resolved now. There is some remaining refactoring to do in order to fix up some margins in the education footer and below but we're tracking that in https://github.com/Automattic/wp-calypso/issues/68622
