### ISSUE TITLE
Videomaker: Group Block Not Showing Correct Color in Editor When Set to Use Custom Primary Color

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#65609]
### Quick summary

Editor is not reflecting the proper color set as the background color for a group block when the color is set to use the "Primary" color. The editor shows the group block with a black background color. Live version of page shows correct color.

 

### Steps to reproduce

1. Activate `Videomaker White` theme.
2. On a page, add some paragraph blocks and group them.
3. Set the group block background to use the "Primary" color.
4. Observer the editor versus what is shown on the live site.

### What you expected to happen

The editor to show the group block reflecting the "Primary" background color that was set.

### What actually happened

The group block looks like this:

![Markup on 2022-07-06 at 12:45:29](https://user-images.githubusercontent.com/93800099/177602311-4a691381-9441-4af2-b697-252fb21a8db7.png)

### Context

Customer report: 35875720-HC

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Videomaker White

I tested a few other themes and was not able to reproduce the issue with them.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Set the group block background to use a gradient color. Set the gradient color to use the same color values for both ends of the gradient.

![Markup on 2022-07-06 at 12:47:28](https://user-images.githubusercontent.com/93800099/177602645-f4624660-e39f-48da-8e9d-aa7a64f6ed53.png)

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to recreate this on simple and AT sites with Videomaker and Videomaker White, and self-hosted with Videomaker (Videomaker White is not an option). I set a custom Primary color in the site editor Styles, but this color was not shown in the editor.
- Updated title to Videomaker since this behavior is present on the Videomaker theme as well, not just Videomaker White.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Robertght** [comment]
Thank you @jamiepalatnik ! I'm moving this here and flagging it to Serenity as it's a Premium theme.
