### ISSUE TITLE
Post Featured Image block not aligned according to the settings in the Editor

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#65629]
### Quick summary

On FSE  themes, the Post Featured Image block alignment setting is not working as shown in the editor. I was able to reproduce the issue on Appleton, Antonia and Twenty Twenty-Two on Atomic and Simple sites.

### Steps to reproduce

1. Activate an FSE theme.
2. Add Query Loop block with Post Featured Image and other blocks,
3. Change the alignment of Post Featured Image block. For example, set it right aligned. You will notice it changes in the editor. Save the page.
4. Check the live page, you will notice there is no difference.

Screenshot: 

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/33957570/179175665-0e5a1cdc-727e-4722-b1d7-ceeafb304fdc.png">

Live page:

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/33957570/179176130-701f69f8-8ad9-46b3-86a6-4d94714122cf.png">

### What you expected to happen

The alignment settings on editor should work on live page.

### What actually happened

The alignment settings on editor did not work on live page.

### Context

User report: [36069534](36069534-hc)
Follow up: 5380271-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

FSE themes. It worked as expected in Classic themes like Twenty Nineteen.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - No 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested on simple, Atomic, and self-hosted with the themes Appleton, Twenty Twenty-Two, and Attar. 
- I tested aligning the Post Featured Image to the right in a Query Loop block.
- In all tests the aligment on the live site matched the alignment shown in the Site Editor. 

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - @devNigel I closed the issue since I was not able to replicate and there is only one user report, but please feel free to reopen if there are other reports or if you can share more details about how you were able to replicate this. Thanks!
