### ISSUE TITLE
[Bug]: Cannot create or modify any post from the desktop app

### ISSUE THREAD

**Issue by theRAGEhero** [Automattic/wp-calypso#65638]
### Quick summary

Hello,
since one year, every time I use the desktop Wordpress app (on both Linux and Windows), I can't open or modify any post.

I allows me to login and to see the list of published posts and drafts, but when I click on Create o Modify it redirect me to the browser version.

From the Android app everything works fine.

Thank you

### Steps to reproduce

1. Open the desktop Wordpress app
2. Click modify post
3. My main browser open to the link of the post I want to modify.

### What you expected to happen

I would like to modify the post from the desktop app

### What actually happened

If I click on _new post_ Firefox opens a new tab to https://www.domain.it/wp-admin/post-new.php?post_type=post instead of remaining in the desktop app

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No and the platform is unusable

**Comment by simison** [comment]
Thank you for the report!

> since one year, every time I use the desktop Wordpress app (on both Linux and Windows), I can't open or modify any post.

I didn't have Windows/Linux for testing right now but tested MacOS version in case (Monterey 12.5.1), and it worked ok. 

The problem might be limited to Linux/Windows, and in theory could be due to 3rd party cookies not enabled. The editor opens from a different domain (`*.wordpress.com` subdomain or `example.com`) than WP.com dashboard itself (which is just `wordpress.com`).

Needs further testing.

https://user-images.githubusercontent.com/87168/188455129-4f1bfad6-9628-4743-ba16-0e5974020588.mov


https://user-images.githubusercontent.com/87168/188455139-8510f6f9-8170-49c6-80bf-81609990cb7e.mov

**Comment by simison** [comment]
We've tested  v7.2.0 on Windows 10, so far couldn't replicate.

Tested:

- On a Jetpack-connected site, with and without the Classic Editor plugin active
- Tested also wpcom "simple" site
- Switching Posts screen view options between classic and default views make no difference

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple WordPress.com Site: **Could Not Replicate**
- Tested on Plugin-Enabled WordPress.com Site: **Could Not Replicate**
- Tested on Self-hosted: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm only able to test on a **Mac OS** at this time, and I am unable to replicate this as well.

📌 ACTIONS
- Await author feedback

📌 Message to Author
- @theRAGEhero , thanks for the report! Can you please check to see if you're using version 7.2 of the desktop app as well? Should see something like this: 
<img width="304" alt="Screen Shot 2022-09-07 at 10 36 49 AM" src="https://user-images.githubusercontent.com/27249804/188943145-eaedf689-1247-47e7-86c7-689be0914b62.png">

**Comment by Joshgrygiel** [comment]
📌 Message to Author
@theRAGEhero I'm closing this report out for now, however please feel free to reopen at any time!
