### ISSUE TITLE
[New Liked Comment] Define and add link descriptors to links/buttons

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65709]
### Details
It's necessary to introduce link descriptors on all links in the template to collect additional metrics on New Liked Comment emails. 

### Checklist
- [x] Define link descriptors for all links in the template
- [x] Verify possible naming collisions
- [x] Include `data-tracks-link-desc` on all links
- [x] Verify if the descriptor is available in the URL event data

**Comment by ivan-ottinger** [comment]
> [ ] Define link descriptions for all links in the template
> [ ] Verify possible naming collisions

I have reviewed the links that are present in the current template and here are a couple of suggestions.

Each link in the screenshot below has its number - so it is easier to discuss the proposed changes:

![Markup on 2022-07-19 at 13:17:34](https://user-images.githubusercontent.com/25105483/179737815-6208630d-6722-43b2-a372-9737d2672e27.png)

Links:
1. We can keep the current `header-comment-like` description
2. We could use `post-url` - the same as we have on the current _New Post_ template
3. We could use `comment-post` - the same as we have on the current _New Post_ template; alternative could be `view-comment`
4. We could use `post-url` (the same as in 2.); alternative could be `view-post`
5. We could use `manage-comment-notifications`. Other emails use `manage-subscriptions`, but the link in the _New Comment Liked_ template is pointing to a different settings page at `/me/notifications/comments` - dedicated for comment notifications:
![Markup on 2022-07-19 at 13:24:04](https://user-images.githubusercontent.com/25105483/179738971-774c0164-9c23-4917-8f4b-8d97414a2da2.png)

That is why I think we should reflect that in the link description.

6. We can keep the current `footer-wordpress` description
7. We can keep the current `footer-app-ios` description
8. We can keep the current `footer-app-android` description

What do you folks think @Automattic/apex? Do you have any objections / different perspective? Cheers. :)

---

One thing to note is that the [i2 template design](c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A24407) doesn't include any of the two CTA buttons ("View comment" & "View Post").

Previous discussions on link descriptions:
- p1653604248892519-slack-C03G5MLTRHQ
- p1653570357170509-slack-C03G5MLTRHQ

**Comment by phcp** [comment]
Thank you for mapping these Ivan! They all look good to me. In the latest version on Figma we only have the View Comment button, so no need to include on on View Post as it'll be deleted.

We may also need to define a link-desc for the "their blog" link below. In this case, the description would be added in the #65538 task as the link isn't there yet.
![Image](https://user-images.githubusercontent.com/3113712/180102647-13318fa1-3ea6-4acb-8c1f-491f5cce33ab.png)

**Updated Figma:** c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A21504

**Comment by ivan-ottinger** [comment]
> Thank you for mapping these Ivan! They all look good to me. In the latest version on Figma we only have the View Comment button, so no need to include on on View Post as it'll be deleted.

Thank you for your feedback Paulo! Taking into account your suggestions, here are the updated labels. Of course, we can still adjust them later if necessary:

- [x] 1. `header-comment-like description` - since we are keeping it and it is implemented in the header template, no change is necessary
- [x] 2. `post-url` (the same as we have on the current New Post template)
- [x] 3. `view-comment`
- [x] ~~4. `view-post`~~ - won't need to be implemented as the new template doesn't have this CTA
- [x] 5. `manage-comment-notifications`
- [x] 6. `footer-wordpress` - since we are keeping it and it is implemented in the footer template, no change is necessary
- [x] 7. `footer-app-ios` - since we are keeping it and it is implemented in the footer template, no change is necessary
- [x] 8. `footer-app-android` - since we are keeping it and it is implemented in the footer template, no change is necessary
- [ ] 9. `liker-blog-url`- will be implemented as a part of the task https://github.com/Automattic/wp-calypso/issues/65538

I will add the labels 2, 3 and 5 in D84449-code.

**Comment by phcp** [comment]
Moved the 9. `liker-blog-url`  to be implemented on #65937

**Comment by ivan-ottinger** [comment]
D84449-code is now ready for review.
