### ISSUE TITLE
[Bug]: Creating a page with a pre-defined layout or start with a blank page does not work

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#65775]
### Quick summary

When creating a new page with a pre-defined layout or start with a blank page, it does not work. Nothing happens when you click on the blank page button or select a pre-defined layout. The modal cannot be closed as well.

### Steps to reproduce

1. On a simple site, go to Pages
2. Click on add a new page button
3. Notice that clicking on the blank page button or any layout doesn't work.

### What you expected to happen

Clicking on the blank page button should create a blank page or selecting a layout should create a page with the layout.

### What actually happened

Clicking on the blank page button or any layout doesn't work.

### Browser

Google Chrome/Chromium

### Context

36049347-hc
- [ ] Follow up 5410104-zen

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Tested on simple sites with different themes and could reproduce this.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

As shared by Cecile: As a workaround, you can suggest users to copy an existing page which will bypass the layout window, and then empty the page to start from scratch.

**Comment by cecilearkay** [comment]
Another report in 36119339-hc. Was able to reproduce on my own site.

**Comment by cecilearkay** [comment]
As a workaround, you can suggest users to copy an existing page which will bypass the layout window, and then empty the page to start from scratch.

**Comment by cecilearkay** [comment]
Another report in 4372125-hc

**Comment by silvio-meter** [comment]
Another report in 35039563-hc
Follow up: 5410292-zen

**Comment by ghost** [comment]
Another report here -  12972280-hc
Follow up ticket - 5410584-zd

**Comment by jorpdesigns** [comment]
Reported in 14086776-hc

- [x] Follow up: 5410310-zen

**Comment by ianstewart** [comment]
I just tested this with my a11n account and my test account and it appears to be working correctly. I can't reproduce the issue. Are other still experiencing this issue?

**Comment by gmovr** [comment]
Same issue as this p1658319124555789-slack-C010KDAPG49

Should be resolved.

**Comment by ghost** [comment]
Another report here -  32563887-hc
Follow up ticket - 5410503-zd

**Comment by mreishus** [comment]
### Current Status = Reverted

* The latest ETK seems to have an error in it.
* As of `[2022-07-20 14:36 +0000]`, We have currently reverted the ETK version ( D84545-code ) to working version `3.37278` based off 6264558dc, which does not have the error, preventing the error in production.

### How to check

The error is recreatable on sandbox by visiting a sandboxed p2 post url and appending `?concat_js=yes` ( example: 2cf1e-pb ). Check the JS console for this:
![2022-07-20_14-17](https://user-images.githubusercontent.com/937354/180064869-d5d5e65d-bab4-4605-9c9e-c4b8eb20ef42.png)
(Note, the p2's domain must be in your hosts file and pointing to your sandbox).
More generally, any non-calypso url with `?concat_js=yes` should exhibit the ETK plugin not working.

### P2, issue with typing `@`: Has workaround but the underlying ETK issue persists

D84544-code is deployed which fixes the error of typing `@...` in a p2 comment box while the ETK is crashing. However, it doesn't fix the underlying issue.

### Newly generated ETKs still have the issue, even after reverting known ETK changes

We have applied these reverts:
* #65787
* #65789
 
Rolling back the changes to the ETK since the last known good version. However, even if we generate a new ETK with these reverts deployed, the ETK still has issues. Could there be some sort of build configuration issue or infrastructure change causing this?

### Clue about when issue exists

**Checking the file `common/dist/data-stores.min.js` in the built ETK**
![2022-07-20_11-37](https://user-images.githubusercontent.com/937354/180065819-1b0d4489-6cf4-4740-89e7-2e70e76fb051.png)

In the versions of the ETK with the bug, the `common/dist/data-stores.min.js` contains a new block of code. It looks to be from calypso-config in calypso: [Link](https://github.com/Automattic/wp-calypso/blob/cde5ea7fb6b2bc3268ba4fc3996152a8824616c0/packages/calypso-config/src/index.ts#L20).

### When did this extra block of code start getting added?

I can check the ETK built for each PR to see if the `data-stores.min.js` file has that block of code in it. Some of the oldest ones I've seen that contain it are #65591 and #65672, but I don't think either of those caused it, because there's no notification that the ETK changed, and the changes don't look ETK related. I'm trying to do a 'manual bisect' of sorts, by looking at ETK builds on PRs, but it's difficult because each PR has a different starting point that isn't necessarily correlated with when it was merged in. I think I need to figure out how to check the built ETK files for each commit on trunk, rather than each branch.

**Comment by mreishus** [comment]
I figured how to bisect locally (run `yarn build` in the ETK directory and either copy or examine the built files)

I'm seeing #65531 as the first commit causing the crash. It seems plausible:
* Modifies the ETK
* Adds @automattic/calypso-config as a dependency (the error we're seeing is related to calypso-config)

 I tested 58dc89437a and the version just before it 78dd64028f, by yarn building the ETK for each, sending it to my sandbox to overwrite the prod directory, and checking 2cf1e-pb while sandboxed. I'm seeing the crash on 58dc89437a but not on 78dd64028f. I think we should revert #65531 to get a stable ETK build again.

@arthur791004, are you ok with that?

**Comment by dhackneya8c** [comment]
Another report in 36124171-hc

**Comment by tanjoymor** [comment]
Additional reports: 36085205-hc
It also happened while I was in a Quick Start session (before I knew this was a known issue)
And I can't add pages to any of my own simple sites.

**Comment by supernovia** [comment]
https://wordpress.com/forums/topic/unable-to-add-pages-2/ (we let the user know it's fixed)

**Comment by supernovia** [comment]
Another: https://wordpress.com/forums/topic/unable-to-create-new-page/ (updated with the fix)

**Comment by mreishus** [comment]
## Problem reappearing

Our mitigation (reverting the ETK version) stopped being effective when a new ETK was deployed: ( D84579-code ). Something to consider for the future: How can we better share the status of 'ETK Blocked'?

## Fix deployed

Since there was active breakage, we decided to revert (#65531 and #65725) immediately to bring the ETK back to a stable state: ( #65803 + D84592-code ).
This should be fixed now, let us know if it isn't.

**Comment by noahtallen** [comment]
Closing as fixed 👍

**Comment by cuemarie** [comment]
_Decision was made here: p1683245378229639-slack-C0160HSMDQV that batch replies for users impacted by this issue will not be sent out._
