### ISSUE TITLE
Domain tip in wp-admin - link rephrasing request

### ISSUE THREAD

**Issue by syds87** [Automattic/wp-calypso#65782]
### Quick summary

There's a tip showing up in wp-admin for websites that are still using the WordPress.com free address, even though they have a connected custom domain. 
The message reads: `Tip: You’re one step away from using usersdomainname.blog as your blog address. Click here to activate usersdomainname.blog`

This might sound confusing, as the domain is already active. It could be a good idea to change the link to something like: `Click here to set userdomainname.blog as your site's primary address.`

### Steps to reproduce

1. Access the dashboard of a site with at least one domain connected but still using the free site address.
2. You will notice this message:
<img width="851" alt="Screen Shot 2022-07-20 at 13 58 00" src="https://user-images.githubusercontent.com/70008187/180000846-ba9f86da-3bbe-48a9-8645-583a2fb6a498.png">

### What you expected to happen

It could be good to have a message like: `Tip: You’re one step away from using usersdomainname.blog as your blog address. Click here to set usersdomainname.blog as the primary address`.

That would be more consistent with the language we use in the dashboard’s domain management page and our official guides (e.g. https://wordpress.com/support/domains/set-a-primary-address/ and https://wordpress.com/support/domains/#set-a-primary-address). 

### What actually happened

The message reads: `Tip: You’re one step away from using usersdomainname.blog as your blog address. Click here to activate usersdomainname.blog`

### Context

User report #5378907-zen

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I wasn't able to replicate this issue. Tested on:

1. Simple site with a registered domain,
2. AT site with a connected (mapped) domain. 
 
In both scenarios, the free default address was set as primary, but there was no message regarding the domain in `siteaddress.com/wp-admin` (or any other wp-admin page).

📌 ACTIONS
- Await author feedback
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @syds87 , were you able to replicate this on a test site as well, or only on the user's site? Can you think of any other steps that are needed to replicate this issue? 
- Closing for now, but if you're able to replicate this on a test site please reopen the issue; thanks!
- Otherwise, this might be a good request for StoreP2 so that the domains team can weigh in on where that tip might be coming from.

**Comment by syds87** [comment]
Thanks, @cumarie for checking this! I have tried a test site, Simple site with a Domain Connection and Registration subscription, using the free `.wordpress.com` address as the primary one. 

I get this message as soon as I try accessing the wp-admin for that website.

Of course, just let me know if I can provide further details or steps!

Thanks!

**Comment by mzitinfo** [comment]
Hi! I just wanted to clarify that this message appears in our dashboard at https://wordpress.com/domains/manage/siteaddress.wordpress.com, not in /wp-admin :)

**Comment by mzitinfo** [comment]
Hi, I wanted to confirm I can replicate the issue on a test site of mine as well:

![Bildschirmfoto von 2022-08-03 08-50-40](https://user-images.githubusercontent.com/9356132/182543576-38ac8389-5b45-4620-bd4f-a2a2b98f771b.png)


Side issue, but the link "Click here..." actually leads me to the domain registration page, rather than the domain management page: 

![Bildschirmfoto von 2022-08-03 08-50-51](https://user-images.githubusercontent.com/9356132/182543880-d3faac05-dfaf-4520-a85d-dde678f78204.png)

Even thought I already own the domain that was mentioned in the initial message:

![Bildschirmfoto von 2022-08-03 08-50-55](https://user-images.githubusercontent.com/9356132/182544120-cc736c9c-78d6-48a8-95a5-861fb621ab74.png)

**Comment by obenland** [comment]
Fixed in r254658-wpcom. Translated versions of the string will show up as those translations become available.

@mzitinfo I was not able to reproduce the unexpected redirect. Please feel free to open a new bug with steps to reproduce if that continues to happen.
