### ISSUE TITLE
[Bug]: Featured Image setting is not available on Pages

### ISSUE THREAD

**Issue by jffng** [Automattic/wp-calypso#65895]
### Quick summary

On pages, the option to set a featured image is not available for simple sites:

<img width="1510" alt="Screen Shot 2022-07-22 at 9 03 36 AM" src="https://user-images.githubusercontent.com/5375500/180479276-83dcb35c-1342-4b7d-9105-5b600b570a7a.png">

The option is however available on self-hosted and Atomic sites, e.g: https://atomicpagefeatured.wpcomstaging.com/featured-image-page-on-atomic/

### Steps to reproduce

1. Activate TT2 or another block theme (Skatepark, Pendant, Archeo)
2. Go to edit a page
3. Verify the Featured Image tab is not available via the page settings.

### What you expected to happen

Featured image setting to be available in the editor

### What actually happened

No dice! 

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

You can add a post featured image block inside the content, set it, and then delete it. The featured image will persist.

**Comment by iamtakashi** [comment]
Can someone look into this? This is a kind of blocker for a theme that's about to launch.

**Comment by simison** [comment]
Few reports starting in July here https://github.com/Automattic/themes/issues/6194 and some technical investigation as well.

**Comment by Addison-Stavlo** [comment]
Adding to our board so it stays in sight, but wondering if @Automattic/team-calypso or other folks have any ideas as to why this is being limited to posts only on dotcom.  Some good info on the other issue noted - https://github.com/Automattic/themes/issues/6194#issuecomment-1184590446

**Comment by noahtallen** [comment]
I did a little digging, and here's part of the problem:

https://github.com/WordPress/gutenberg/blob/ebb5d8231195ff8dd48f7502faa71d0b5c76cc27/packages/editor/src/components/theme-support-check/index.js#L24-L32

Skatepark seems to have `post-thumbnails: [ 'post' ]` in the theme support object at this point in the execution, which means that it only shows the featured image panel for posts, and not for pages.

As for why that's the case on dotcom and not atomic, I'm not sure. 🤔

**Comment by noahtallen** [comment]
It looks like this was mentioned in the other thread as well: https://github.com/Automattic/themes/issues/6194#issuecomment-1184590446

**Comment by noahtallen** [comment]
It's a deeper problem as well:

```php
$blog_id = get_blog_id_from_url( 'example.wordpress.com' ); // site with skatepark theme
switch_to_blog( $blog_id );
get_theme_support( 'post-thumbnails');
// => array(1) {
//  [0]=>
//  array(1) {
//    [0]=>
//    string(4) "post"
//  }
// }

**Comment by noahtallen** [comment]
This support option is supposed to be added by default for all block themes:

https://github.com/WordPress/WordPress/blob/105a3d97825a38d0e80c7b2c9a1aa2379ceb944f/wp-includes/theme.php#L4214-L4231

**Comment by noahtallen** [comment]
At the end of the `setup_theme` action, skatepark should support the feature. so something after that must be turning it off.

**Comment by noahtallen** [comment]
_edit: I ended up compiling all my individual comments into one big one_

I did a little digging and found the problem.

https://github.com/WordPress/gutenberg/blob/ebb5d8231195ff8dd48f7502faa71d0b5c76cc27/packages/editor/src/components/theme-support-check/index.js#L24-L32

Skatepark seems to have post-thumbnails: [ 'post' ] in the theme support object at this point in the execution, which means that it only shows the featured image panel for posts, and not for pages. (It looks like that was [mentioned in the other thread](https://github.com/Automattic/themes/issues/6194#issuecomment-1184590446) as well.)

Interestingly, this support option is supposed to be added by default for all block themes:

https://github.com/WordPress/WordPress/blob/105a3d97825a38d0e80c7b2c9a1aa2379ceb944f/wp-includes/theme.php#L4214-L4231

This function adding support for all block based themes is run on the `setup_theme` action.

And if I log around the end of the `setup_theme` action, skatepark supports the feature. In fact, if I do logging around most normal actions, it seems like the option is turned on for the entire boot-up cycle. So nothing appears to be turning it off.

### Problem:
In a public-api request, `_add_default_theme_supports` does get called, but the current theme (from `get_current_theme`) is _not_ set to the actual site theme. It's only set to the theme of the public-api "site."

So support is never added in the first place if you access block-based theme data over the public-api.

Since the public-api is not used in self-hosted and Atomic sites, there's no problem. There, the active theme when `_add_default_theme_supports` is executed is likely the current block based theme, so support is correctly added.

### Fix: 
Still looking into this, but I'm curious if there is a core bug. I'm not sure this approach for setting up the theme would work in general for API requests. I think core gets lucky because the current active theme in an API is block-based, so support is added. If one was requesting a different, non-active theme over the API, I'm wondering if this would incorrectly add theme support to that other theme.

Further conversation: p1661385700115819-slack-CBTN58FTJ

**Comment by noahtallen** [comment]
Fix: D86721-code

**Comment by noahtallen** [comment]
This issue should be resolved in production 👍
