### ISSUE TITLE
Checkout: clarify pricing and discounts in variant picker

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#65968]
In #65374, we merged the logic for subscription variant pickers between Jetpack and WPcom, always showing the dropdown variant picker when term variants are available.

Since the annual discount UI could be confusing, and this could affect conversion rates, we should run an AB test to measure the impact of the change.

See: https://github.com/Automattic/wp-calypso/pull/65374#issuecomment-1179388553
See: p1658837514683709-slack-C031TFM2NKC

**Comment by michaeldcain** [comment]
From planning:

Using the dropdown feels like both a usability and code complexity improvement. It seems from the slack discussion that the biggest issue is the confusion around what the discount is relative to in the selected state:

<img width="584" alt="Screen Shot 2022-07-26 at 1 19 16 PM" src="https://user-images.githubusercontent.com/942359/181070403-9b2e3e82-7a51-4161-8fba-bc933d2836c2.png">

@lucasmendes-design do you have any suggestions for how we could improve that discount message?

**Comment by lucasmendes-design** [comment]
I'm looking on that 👍🏼

**Comment by lucasmendes-design** [comment]
I wouldn't suggest using the dropdown variant. We can use the radio as the default variant. 

<img width="504" alt="image" src="https://user-images.githubusercontent.com/98343583/181135580-1ee88655-5bd3-47ec-b5a7-1495568923b2.png">

IMO, the copy is confusing because we're showing different prices range (month, year and two years). Normally, what we do is standardize showing by the default per month. Some examples: 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/98343583/181136295-8b59a77d-ded5-4801-adab-656a833e7681.png">

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/98343583/181136319-7ff885b5-13f2-4d02-96e1-90461bab263b.png">

<img width="622" alt="image" src="https://user-images.githubusercontent.com/98343583/181137712-b6e1ccd7-9fd7-4ec7-aa82-92674756b52a.png">

 
So, my suggestion is to use the radio button and change the copy: 
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/98343583/181140756-6f5d1889-7bfd-4c75-9f60-c5914d711e6a.png">

**Comment by lucasmendes-design** [comment]
Adding the copy "First year discount"

<img width="577" alt="image" src="https://user-images.githubusercontent.com/98343583/181145757-02ac4689-d70d-44a9-aa26-d262f806fcd8.png">

cc: @DavidRothstein

**Comment by michaeldcain** [comment]
@lucasmendes-design: Consolidating behind a lowest common denominator term (monthly) really helps clarify the discounts in the variant picker. The total being paid is conveyed at the line item level (and again in the cart total). Regardless of using the radio buttons or the dropdown, I think the variant price changes should be integrated into both.

**Comment by sirbrillig** [comment]
Some PRs up for review:

https://github.com/Automattic/wp-calypso/pull/66066 will change the variant picker to show monthly prices as suggested above. 

https://github.com/Automattic/wp-calypso/pull/66027 will switch wpcom back to using radio buttons for the variant picker (not clear if they should just be always visible or hidden behind some version of an edit button) and generating the "Save X%" text by comparing each variant to the lowest available variant rather than the selected one.

https://github.com/Automattic/wp-calypso/pull/66031 will add the text "Annual discount: X%" or "Biennial discount: X%" to each line item. Note that these are not really "discounts" in the sense that they are not modifications to the product price.

https://github.com/Automattic/wp-calypso/pull/66029 will add text to each line item that explains the discounts applied to that line item. This is different from the discounts mentioned above because these are actual modifications to the product price like domain bundle discounts or proration discounts.

**Comment by DavidRothstein** [comment]
I left some thoughts at https://github.com/Automattic/wp-calypso/pull/66066#issuecomment-1199374216 about how (and how not) to handle the `$4/month` display.  I get why we want to do it, but we need to be more careful.  Some of that comment is specific to how things look with that specific pull request, but I think some of it is relevant more generally.

**Comment by sirbrillig** [comment]
Here's some designs utilizing radio buttons for the variant picker by @JanaMW27 ([originally mentioned here](https://github.com/Automattic/wp-calypso/pull/69494#issuecomment-1295315829)) which I wanted to explore. The basic idea is to remove the price display for the line item if variants are available and instead display the price and discounts inside the variant itself. This would greatly decrease the risk of clutter and price confusion stemming from the radio button UI.

For annual plans:

<img width="645" alt="Screen Shot 2022-11-09 at 1 01 45 PM" src="https://user-images.githubusercontent.com/2036909/200906299-3e998e26-a348-4bc7-9b67-eca4615032dc.png">

For monthly plans:

<img width="514" alt="Screen Shot 2022-11-09 at 1 02 28 PM" src="https://user-images.githubusercontent.com/2036909/200906331-530d979f-a354-4b7e-9040-51d9d33314c2.png">

The biggest challenge is how to display discounts. Currently the line item price shows text like "Discount for first year". In this model, that text is moved inside the selected variant. However, if the selected variant also needs to include a percentage of savings (compared to the smallest term variant) then we need a way to display both or otherwise disambiguate the prices.

**Comment by sirbrillig** [comment]
The above approach met with some challenges due to the variety of data included in a line item. A new design is here:

![radiofull](https://user-images.githubusercontent.com/2036909/203445234-a66f4817-0775-4c64-be53-386d0e6e29a8.png)

**Comment by sirbrillig** [comment]
I've created https://github.com/Automattic/wp-calypso/pull/70315 to work on the updated design.

**Comment by sirbrillig** [comment]
The PR is merged and we're AB Testing it here: pbxNRc-2ce-p2

**Comment by sirbrillig** [comment]
Closing this issue as I believe the new radio buttons are going to work well. We can reopen it if we need additional work.
