### ISSUE TITLE
Theme homepage replacement not working on all themes

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#66045]
### Quick summary

The homepage replacement doesn't consistently but not clear what difference between themes is

### Steps to reproduce

1. On AT site apply flag on themes page (?flags=themes/atomic-homepage-replace)
2. Change to a variety of different themes (ex. Archeo and Calvin)
3. See how styles change for all but content only replaced for some

### What you expected to happen

content of home should be replaced for all

### What actually happened

Not all themes replace content
ex Archeo/Stewart/Vivre change styles but not content while Calvin/Alonso/Pendant do

Archeo should look like:
![2022-07-28 at 13 26](https://user-images.githubusercontent.com/47717887/181484067-fd1a470a-8625-4fdd-ba82-fe68db6e5488.jpg)

On My site looks like:
![2022-07-28 at 13 27](https://user-images.githubusercontent.com/47717887/181484137-88075273-ea63-4ce0-9273-826fbf0d2488.jpg)

pendant should look like:
![2022-07-28 at 13 28](https://user-images.githubusercontent.com/47717887/181484244-45795d4c-ef2a-4be1-b6ae-a31612e923cc.jpg)

on my site looks like:
![2022-07-28 at 13 28](https://user-images.githubusercontent.com/47717887/181484362-8507eccc-75f6-436b-802f-566c42b9823f.jpg)

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

**Comment by andres-blanco** [comment]
This is most likely related to flags missing in `style.css` file on themes and not directly related to Atomic. 

Related issues and diffs:
* https://github.com/Automattic/wp-calypso/issues/65900
* D83131-code

**Comment by deancroyal** [comment]
Customer reported in 36319723-hc when trying to switch to Byrne

**Comment by tanjoymor** [comment]
What seems to be happening is that some themes are not properly updating the option under Settings > Reading for how the theme is built. This results in a theme like Archeo and Pendant loading the last set "Homepage" set as the Static page, instead of switching to "Latest Posts" (which is how these themes are built). 

The "Homepage content" for these themes is actually built in a "Template" not a page and that's where the "Auto Loading Homeloading" feature is putting the Homepage content for those themes (not on a page). Change the site setting to "Latest Posts" for the Homepage and you'll see the correct Homepage content on the site and in the Site Editor. 

BUT it doesn't happen consistently. (Though so far it happens every time with Varese.)

It happens on Simple sites as well as Atomic too.

Not sure why Byrne would have had an issue, unless maybe they didn't actually select the Load Homepage option? It is switching and adding the Homepage as a Page as expected, and updating the option under Settings > Reading appropriately.

**Comment by fushar** [comment]
Fixed via:

- #79167

cc @Automattic/lego ❤️
