### ISSUE TITLE
Marketplace: July search data snapshot report

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#66065]
Repeat pdh6GB-1yg-p2 for July by following this guide: PCYsg-ID9-p2

Acceptance criteria:
- [x] p2 report posted
- [x] Category changes proposed
- [x] Investigation on how to track if searches convert to purchases

**Comment by Rolilink** [comment]
I am still doing my research on this one but it seem we will need to implement the events described here: pdh6GB-1au-p2 to be able to track the searches that don't convert to purchases.

Tried with the following suggestion pdh6GB-1bw-p2#comment-2252 but didn't got any results, it seems like they are saving two different session ids or just not saving the searches because there is no interaction event being sent.

**Comment by Rolilink** [comment]
After some more research it seems this two events exist but are hidden behind a feature flag, they are part of the Marketplace Elastic Search implementation pdh6GB-1bw-p2#comment-2582.

But they are used for click conversion (clicking the plugin from the list) and not purchase conversion (going through the whole process and clicking the purchase/install button).

For the last one I think we will need to send a second interaction event with a different action which I [created an issue for](https://github.com/Automattic/wp-calypso/issues/66367).
