### ISSUE TITLE
gutenberg_configure_persisted_preferences: Does unused work on some pages

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#66063]
### Overview

* Apply this patch to a sandbox.
```diff
diff --git a/wp-content/plugins/gutenberg-core/v13.6.0/lib/compat/wordpress-6.1/persisted-preferences.php b/wp-content/plugins/gutenberg-core/v13.6.0/lib/compat/wordpress-6.1/persisted-preferences.php
index 2a5211e12..8386f4081 100644
--- a/wp-content/plugins/gutenberg-core/v13.6.0/lib/compat/wordpress-6.1/persisted-preferences.php
+++ b/wp-content/plugins/gutenberg-core/v13.6.0/lib/compat/wordpress-6.1/persisted-preferences.php
@@ -55,7 +55,14 @@ function gutenberg_configure_persisted_preferences() {
        global $wpdb;
        $meta_key = $wpdb->get_blog_prefix() . 'persisted_preferences';
 
+       $start = microtime(true);
        $preload_data = get_user_meta( $user_id, $meta_key, true );
+       $end = microtime(true);
+       $elap = ($end - $start) * 1000;
+
+       $actual_link = 'http://'.$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'];
+       error_log("adding inline script. URL: $actual_link. Took: $elap ms");
+       error_log(print_r( compact('preload_data'), true ) );
 
        wp_add_inline_script(
                'wp-preferences',
```

* watch `tail -f /tmp/php-errors`
* Visit `/wp-admin` on a sandboxed simple site
* Observe: This code is running on index.php (also on adam-ajax.php), and sometimes takes 12ms or 22ms (other times, it takes less than 1ms)
  * You may also check the debug bar's list of SQL queries, to find a query related against `wp_usermeta` that takes 5-10ms. It loads all usermeta entries for my user; not just the requested {$blogid}persisted_preferences key. This might be an optimization "the first time we visit the usermeta table, pick up everything", but this unneeded request could be the first and only usermeta request, leading to a lot of wasted data being fetched.
* The purpose of the code is to add an inline script block that includes `var serverData =`.
* However, if you check the source code for the `wp-admin/index.php` page, there is no `var serverData =`.
  * The function  `gutenberg_configure_persisted_preferences()` ran `wp_add_inline_script( 'wp-preferences'`, however, `wp-preferences` was not enqueued, so it did costly work that ended up having no effect.
* Contrast to  `/wp-admin/post-new.php`, where you do see the `var serverData =` in the source generated.

Only some pages are using the `serverData` computed by this function, but other pages are calculating it but not using it. Can we make `gutenberg_configure_persisted_preferences()` run only on the requests where it will be used?

**Comment by mreishus** [comment]
Gutenberg hangs this on `admin_init`: https://github.com/WordPress/gutenberg/blob/e3136a4cae7bc27c3d842b73bafd6afa546cc497/lib/compat/wordpress-6.1/persisted-preferences.php#L78

**Comment by mreishus** [comment]
@david-binda : Would you have any ideas on an approach I could take?

**Comment by david-binda** [comment]
> It loads all usermeta entries for my user; not just the requested {$blogid}persisted_preferences key. This might be an optimization "the first time we visit the usermeta table, pick up everything", but this unneeded request could be the first and only usermeta request, leading to a lot of wasted data being fetched.

Right, this is native WordPress behaviour. When requesting some meta data for an object, it attempts to get this from cache, and if it's not found in there, it pre-populates the cache. The cache is, further, being used not only during the same page load, but also in between the requests as WPCOM simple sites are using memcache as peristent cache storage. No more trips to database should happen as long as the cache exists.

What's going on here, at least based on my investigation, is that the cache key holding all the user meta keys and values is being deleted on all wp-admin requests, and thus is being recreated over and over, resulting in the SQL queries we are seeing here.

The offending code responsible for constant cache purging is here: https://github.com/Automattic/jetpack/blob/b82dce6b08932eae8b31eede5aa8b77b22edc36b/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L435,L440 , more specifically inside the `set_user_setting` function called from there.

The thing with `set_user_setting` is that it always updates also the timestamp of the last update ( see https://github.com/WordPress/WordPress/blob/82ee734e8bd72ba3dc85660aeadabe144ace3768/wp-includes/option.php#L1272 ), which is, naturally, different every time the function is called ( as it's obtaining the value via `time()` function ), so the cache gets invalidated only in order to contain a different timestamp, even if the rest of the settings are staying the same.

IMHO, we should add some logic to the `sync_sidebar_collapsed_state` function to check whether the setting obtained form calypso is different from the one stored in the user setting (which is using the user meta storage), before attempting to update it.

Eg.: something like this should do the trick.

```
public function sync_sidebar_collapsed_state() {
    $calypso_preferences = get_user_attribute( get_current_user_id(), 'calypso_preferences' );

    $sidebar_collapsed = isset( $calypso_preferences['sidebarCollapsed'] ) ? $calypso_preferences['sidebarCollapsed'] : false;

    // Read the current stored setting and convert it to boolean in order to be able to compare the values later.
    $current_sidebar_collapsed_setting = get_user_setting( 'mfold' );
    if ( 'f' === $current_sidebar_collapsed_setting ) {
        $current_sidebar_collapsed_setting = true;
    } else {
        $current_sidebar_collapsed_setting = false;
    }

    // Only set the setting if the value differs, as `set_user_setting` always updates at least the timestamp
    // which leads to unnecessary user meta cache purging on all wp-admin screen requests.
    if ( $current_sidebar_collapsed_setting !== $sidebar_collapsed ) {
        set_user_setting( 'mfold', $sidebar_collapsed ? 'f' : 'o' );
    }
}
```

**Comment by david-binda** [comment]
Besides an issue in the Jetpack repository ^ , I have also prepared a PR with a fix: https://github.com/Automattic/jetpack/pull/25333

**Comment by mreishus** [comment]
Very interesting, thank you. I also noticed this constant timestamp behavior but didn't realize it was related!

One other interesting thing I found was `wp_set_all_user_settings()` -> `update_user_option()` -> `update_user_meta()` -> `update_metadata()` has a mechanism to not do writes if we request to write a value that is not a change:

https://github.com/WordPress/wordpress-develop/blob/9f5935c2e8161cc0e887e2ee4ad50cefd1cf07de/src/wp-includes/meta.php#L238-L246

However, the timestamp is written even if this optimization kicks in, because this is way up the callstack:

https://github.com/WordPress/wordpress-develop/blob/9f5935c2e8161cc0e887e2ee4ad50cefd1cf07de/src/wp-includes/option.php#L1271-L1272

I had an idea to do something like:
```php
	$updated = update_user_option( $user_id, 'user-settings', $settings, false );
        if ( $updated !== false ) {
	    update_user_option( $user_id, 'user-settings-time', time(), false );
        }
```
Checking the chain of return functions, it looks like they provide the value that we need to do this.

https://github.com/WordPress/wordpress-develop/blob/9f5935c2e8161cc0e887e2ee4ad50cefd1cf07de/src/wp-includes/user.php#L708-L709

I was kinda scared to submit this, since I've never done an update to core before. Any feedback on this?

**Comment by david-binda** [comment]
I would say that there is no need to be scared of opening a core ticket with any proposal :)

I'm not sure if always updating at least the timestamp is intentional or not. The `set` in the function name could be a hint on the behaviour (vs. `update` which could be read as update if needed). So another approach would be to have a `update_user_setting` function, which would bail if the value would not get updated.

Anyway, the best path forward would be to fill in a core ticket, and possibly submit a patch along with it. Again, no need to be scared at all :)

**Comment by david-binda** [comment]
@mreishus with the above PR merged, and D85079-code being merged to WPCOM simple sites, this should be fixed.

I'm closing this issue, but feel free to reopen if you feel otherwise.

**Comment by mreishus** [comment]
Great, thanks for your work on this! I no longer see the ~10ms queries on every page load.
