### ISSUE TITLE
LaunchPad Container - Create full-screen container

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66119]
The Launchpad will need a full-screen container that hides the rest of calypso interfaces in this mode. More context and designs - paYE8P-1Ot-p2

* Create or re-use a full-screen container for the LaunchPad. (Perhaps there is something we can reuse from the stepper flow here?)
* The full-screen container should be active when some variable check is `true`.  We can start this as a foo-bar placeholder set to `false` for now, but will need to coordinate how to check this data for real at a later point in time (related p2 - pdDR7T-bx-p2).
* When visiting calypso and the aforementioned check is `true`, this screen is all that we see and we can not interact with other calypso interfaces (sidebar / topbar / etc.).
* Investigation aspect - maybe we add a full-screen modal to calypso, maybe we implement a redirect into a stepper flow LaunchPad screen with appropriate query params, maybe other.

**Comment by jeyip** [comment]
I created a draft PR that creates a new full screen launchpad container in Stepper. I started there instead of with the Calypso modal for a few reasons:

1. We have access to navigation helpers only available to components rendered within the scope of stepper. They allow us to easily move back and forth to different steps within onboarding.
2. The page layout, top progress bar, escape hatch button, etc. already come for free if rendered within stepper

@agrullon95 and I hopped on a call to pair and discuss things further. From what we can tell, we'll be able to accomplish all requirements outlined by the Launchpad project  if we use stepper. We'll be able to:

- Render a checklist and site preview
- Access the calypso UI's redux state and Onboarding redux state to verify checklist item progress and determine which checklist to render
- Use calypso config to hide and display our step while it's under development
- Redirect back to the launchpad stepper page from the editor and frontend using  a url that looks like `.wordpress.com/setup/launchpad?flow=newsletter`
- Reuse the same components rendered in the launchpad step for the mini my home feature

We thought about why a full screen calypso modal might be better suited for launchpad, but couldn't come up with much. Maybe other folks can chime in with opinions? Stepper seems like the way to go.

**Comment by Addison-Stavlo** [comment]
Very nice finds!

> using a url that looks like .wordpress.com/setup/launchpad?flow=newsletter

I imagine that url might need some sort of site specific ID or url?

**Comment by jeyip** [comment]
> I imagine that url might need some sort of site specific ID or url?

That's a good question. We'd need it to pull up the correct checklist and progress against items on the checklist. @agrullon95 and I explored a bit to see if there was some "selected site" state that we could reference in the calypso redux store that would provide the site slug in onboarding, but didn't see anything obvious.

It also looks like the defacto way of referencing site slug in stepper is to use the query param, so you're probably right...we'll want something for the future
