### ISSUE TITLE
Marketplace search: results show a 5-star rating if there are no ratings

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#66158]
#### Steps to reproduce

> **Note**
> The `marketplace-jetpack-plugin-search` feature flag is enabled by default on the **wpcalypso** environment.

1. Starting at URL: https://wpcalypso.wordpress.com/plugins
2. Search for a plugin with no ratings, eg.: `unicard`

#### What I expected
The search result should show 0 ratings.

#### What happened instead
The search result shows 1 rating of 5.

#### Screenshot / Video
![CleanShot 2022-08-02 at 12 02 07@2x](https://user-images.githubusercontent.com/11555574/182348514-cf29de04-78d5-4b0b-a7d9-658419ebe782.png)

**Comment by WBerredo** [comment]
There are two issues on this search:
- [ ] ES is returning as 1 rating with value 1 (it should returns 0 ratings)
- [x] The rating 1 is being shown as 5 - #66831

**Comment by BogdanUngureanu** [comment]
>  ES is returning as 1 rating with value 1 (it should returns 0 ratings)

I believe the problem comes from the fact that we build the ES for rating counting from 1 for both the rating and rating nums fields: class.wpes-wpcom-plugin-post-field-builder.php#103 From what I understood, this is needed for ranking purposes.

We need to format the response from ES in the search API by checking these two fields and, if they are both 1, we can assume that the plugin doesn't have any reviews.

I'll open a diff with a fix for this on Monday. :)

**Comment by BogdanUngureanu** [comment]
>  ES is returning as 1 rating with value 1 (it should returns 0 ratings)

~~Opened D86744-code (Ready for review) that fixes this issue.~~

**Comment by BogdanUngureanu** [comment]
Alternative approach RfR: D86823-code

**Comment by BogdanUngureanu** [comment]
The patch was deployed in rWPGITe10866df6fd7e9b6a2e03483bc7ad3398c4ab836

For now the search results are still showing the 1 star rating for products without ratings. I suppose this is caused because the cache wasn't rebuilt?

**Comment by BogdanUngureanu** [comment]
Looks like that the cache was refreshed and now the rating is no longer displayed for plugins that don't have any rating 🎉
