### ISSUE TITLE
Sites Management Page: Update style of empty states

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66211]
We show a helpful message when the user has no sites at all. We just need to update its style so they match the mockup (which will bring them in line with the standard `<EmptyContent>` style we use elsewhere in Calypso)

Mockup looks like this:
![Image](https://user-images.githubusercontent.com/1500769/182568874-b1f05409-92b2-411b-8031-22a4a7964058.png)

Current implementation looks like this:
![Image](https://user-images.githubusercontent.com/1500769/182569320-46dd5a6f-dbcc-46ac-a7ad-564a5685ed36.png)

You can see other examples of how it should be styled at
- `https://wordpress.com/domains/manage/{{ site slug }}` (when the site has no domains)
- `https://wordpress.com/woocommerce-installation/{{ site slug }}` (when the site has a business plan but isn't a store)

Done is:
- [ ] Font sizes match what you see in the empty Domains and WooCommerce pages listed above
- [ ] Heading should use recoletta font
- [ ] Update the icon to match the Figma mockup (I've attempted to export it myself and made it available here: pdKhl6-Au-p2#comment-487)
- [ ] The status specific empty states don't use recoletta or have a graphic, but confirm that their vertical alignment is consistent
- [ ] Confirm final wording with @SaxonF

**Comment by halleshubham** [comment]
how to access the Figma mockup:  184522-pb ?

can I pick this up ?

**Comment by p-jackson** [comment]
Hi @halleshubham, thanks for your interest in the new sites management page!

This task in particular will be a bit tricky without access to Figma, which isn't accessible outside of Automattic. So I'd leave this one for someone else. If you are interested in helping out #66210 might be a good one, although no pressure of course.

**Comment by halleshubham** [comment]
sure! @p-jackson

**Comment by danielbachhuber** [comment]
@p-jackson Is this issue complete as of #66492?

**Comment by sejas** [comment]
@danielbachhuber Yes, I think you are right. This issue is already done.

- I'm closing this issue since it was done in https://github.com/Automattic/wp-calypso/pull/66492

Here I attach the screenshots of the current status of the combination between empty states and the dropdown filter:

# No sites at all

<img width="1337" alt="no-sites" src="https://user-images.githubusercontent.com/779993/184891839-391eac20-233f-40b4-ab75-ff1e723d8604.png">


# Public
<img width="1322" alt="public" src="https://user-images.githubusercontent.com/779993/184891853-29dcfbdd-919b-437d-888e-6c0790a90fad.png">


# Private

<img width="1326" alt="private" src="https://user-images.githubusercontent.com/779993/184891876-3e3e24c6-7486-4d1f-bd9f-444da1e88f07.png">


# No Coming soon

<img width="1316" alt="coming-soon" src="https://user-images.githubusercontent.com/779993/184891895-3caed124-d23e-43ed-a086-b1fa98e6e85f.png">
