### ISSUE TITLE
Sites Management Page: Table doesn't update when user adds a new site (or changes anything else)

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66340]
#### Steps to reproduce

1. Create a new site at `/start`
2. Visit the main Calypso dashboard at `wpcalypso.wordpress.com` 
   - the new site is available in the site switcher, as it should be 👍
3. Visit `wpcalypso.wordpress.com/sites-dashboard`
   - the new site isn't in the site table, it should be there 👎
   - if you forcefully empty Calypso's application cache using the dev tools then the new site will appear
4. Hang around on the sites management page for [5 minutes](https://github.com/Automattic/wp-calypso/blob/edbd5a4297ffc599d8e88365c622055e0269ff3f/client/data/sites/use-site-excerpts-query.ts#L31)
5. The new site will magically appear in the list

Whatever mechanism the Calypso Redux store is using to invalidate the sites list doesn't seem to be working for us. I know that Calypso updates the site list as one of the very last steps in the site creation flow and I thought that would be picked up by our `useSiteExcerptsQuery` hook, but that doesn't appear to be the case.

If you change step 1 to "change the title of one of your sites" then the same issue of stale data happens. So it's a general caching issue.

**Comment by sejas** [comment]
`useQuery` provides a way to invalidate the queries (clear the cache) and fetch the data again. https://tanstack.com/query/v4/docs/guides/query-invalidation

I usually create a hook that returns a function, and I call it when some action occurs, i.e. a user clicks on add site.

```js
export const useInvalidateSiteExcerptsQuery = () => {
	const queryClient = useQueryClient();
	return () => queryClient.invalidateQueries( [ SITE_EXCERPT_QUERY_KEY ] );
};

```

I love `useQuery` in general, but I feel we would be reinventing the wheel because we need to invalidate the query in multiple cases, when a site upgrades, a site is added/deleted ...

Moving the logic inside the redux store seems the only way to do it, but it feels a bit odd. We should skip a few react patterns to access `queryClient` directly, outside of a hook and outside of a component. It's possible but odd.

I think the best solution here is to use the redux store as we do in multiple places.

@danielbachhuber what do you think?

**Comment by danielbachhuber** [comment]
@sejas I originally used Redux and was directed to use React Query instead: https://github.com/Automattic/wp-calypso/pull/65593#pullrequestreview-1040027902

We'll need to have Redux properly clear the React Query cache.

**Comment by sejas** [comment]
Some workarounds 
1. Reduce the stale time to ""30 seconds""
3. Invalidate the query when the component is mounted / the tab get the focus

**Comment by sejas** [comment]
I think the second workaround will work well.

**Comment by danielbachhuber** [comment]
@sejas Ideally, wouldn't Redux prime the React Query cache when it's updated?

**Comment by sejas** [comment]
That is the path I think is contrary to the react patterns.

Anyway, I've found that my second workaround is a good solution. It's simple, clean, and effective. I'm preparing the PR 😎 .

**Comment by sejas** [comment]
- @danielbachhuber  PR: https://github.com/Automattic/wp-calypso/pull/66361 Ready to review.
