### ISSUE TITLE
Product categories not showing up in the menu

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#66463]
### Quick summary

The product categories are not showing up as options to add to the menu. 

### Steps to reproduce

Open the menu page https://digiug.wpcomstaging.com/wp-admin/nav-menus.php 
Try adding product categories to the menu, they should be there but they are not
![Markup on 2022-08-10 at 11:45:24](https://user-images.githubusercontent.com/5507879/183944334-5474dff8-61f7-4588-96f5-3c6e575a6905.png)

It is possible to add them using the Site Editor but only if your search for them. 

There are categories created and they have products in them. 

### What you expected to happen

I expected the product categories to be an option to add to the menu in the menu page. 

### What actually happened

Product categories are not available in to add to the menu

### Context

ticket: 5467851-zd

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Not sure. I am not able to replicate this issue on my test site using the theme Arbutus or other themes. 

### Reproducibility

Once

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

The user is adding the categories manually to the menu via the Site Editor.

**Comment by cuemarie** [comment]
Hi @dolgelukkig ! Since you were not able to replicate this issue, and it instead relies on user-specific site information, a better place to report this would be through internal channels, so that other HE's can help troubleshoot and determine if a reproduceable bug is present. For more context, check out this P2: p7DVsv-eW4-p2

- [ ] Could you please remove the specific link to the user's site from this report? Once that's removed, please also [delete the previous revision from history](https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) to protect their privacy.

In the meantime, it looks like the user's issue was addressed on the ticket by the next HE, so that's great! With that in mind, this issue is closed.
