### ISSUE TITLE
Sites Management Page: Site thumbnail should reflect changes made to the site

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66524]
We currently rely on mshots default caching. That means if mshots hasn't taken a screenshot in a while then it'll retake it, otherwise it gets the image from the cache. The problem with this is that if a user drastically changes the front end of their site, the thumbnail in SMP won't update until the mshots cache time expires.

We can get mshots to take a another screenshot by adding a cache-busting query param. So one quickish improvement would be to use date from the "last updated" column as the query param e.g. `?v=20220812T224900`

To stop us from refreshing the cache too frequently we could truncate the minutes and seconds of the timestamp.

There are other fancier ways we could come up with the cache-busting string that would only invalidate the cache when the edit to the site actually impacted the front page. But this might be a good start.

Done is:
- [x] When users make edits that impact the front-end, those edits are reflected next time the user loads the SMP
- [x] It is acceptable for the thumbnail to regenerate more frequently than necessary (i.e. a time based solution is acceptable)

**Comment by danielbachhuber** [comment]
@p-jackson @Automattic/build Nothing is as easy as it looks, of course!

As far as I can tell, mShots caches `https://s0.wp.com/mshots/v1/*` pretty aggressively. Including an additional `&v=<rounded-updated-at>` query param in the mShots request doesn't generate a new screenshot — rather, it serves the existing screenshot. As such, our "simple" fix to include a query busting param doesn't give us a new screenshot.

One "hacky" workaround is to include `?v=<rounded-updated-at>` on the _screenshot URL itself_ (#66534). I think it's a little hacky because I'm not sure it's a "blessed" use of mShots. Additionally, if the site's full page cache doesn't discard the `v` query param, this approach will likely bypass the site's full page cache and take a longer time to generate a mShot.

A few other options I can think of:
1. Refactor `useMshotsImg` to use `fetch()` instead of `imgRef.current.onload`. With `fetch()`, we'd be able to inspect `Last-Modified` (or some other filter header), and re-request the mShot with `&requeue=true` if needed.
2. Update mShots production infrastructure to support a `&v=<rounded-updated-at>` query parameter with the behavior we want.
3. (Probably a bad idea but) always include `&requeue=true` in our mShots requests to make sure we get the freshest images.
4. Punt on busting cache, because mShots expire after 12 hours anyway (pMz3w-fyd-p2#comment-100304)

My hunch is that the first option (`&requeue=true`) is the "blessed" one. However, it seems overly complex and I'm not sure which header would be most reliable to inspect.

My preference would be the second option. It would obviously require getting approval 😄 

Thoughts?

**Comment by vykes-mac** [comment]
At the moment what do we use to determine last-modified of a site, and what kinda modification was done? If we identify the type of modifications that qualify for a new thumbnail then we might check for those on each page load and `requeue` when necessary. Is it possible to get info from `activity log` and if that activity was modify `theme/post` and it matches` last modified` then we requeue? 🤷

**Comment by p-jackson** [comment]
> One "hacky" workaround is to include `?v=<rounded-updated-at>` on the screenshot _URL itself_

That's exactly how I was expecting it would work 😄 
In terms of being "blessed", Systems didn't seem to balk at the suggestion and seemed to think it was an elegant way to "invalidate" both server and client caches pMz3w-fyd-p2#comment-100304

>  if the site's full page cache doesn't discard the `v` query param, this approach will likely bypass the site's full page cache and take a longer time to generate a mShot.

That's a fair point, but the amount of time the PHP takes to run seems pretty negligible in relation to the total user-perceived time it takes for the screenshot to load right?

**Comment by zaguiini** [comment]
So far, the proposed solutions depend on implementation details, which might break in the future without any warning.

For me, the ideal solution would be to invalidate the screenshot whenever the front-end changes or hook into `Last Published` to invalidate the screenshot cache for that particular page, in the back-end. This would be an "active" solution to this problem.

The ones that are suggested here (as far as I understand, let me know if I'm wrong) are "passive" in the sense that they try to invalidate the cache passively as the consumer. Looking forward to hearing more about it!

**Comment by danielbachhuber** [comment]
Asked for some systems input with pMz3w-fyd-p2#comment-100975

**Comment by danielbachhuber** [comment]
`?v=<rounded-timestamp` is the blessed approach: pMz3w-fyd-p2#comment-100976

**Comment by p-jackson** [comment]
🙏

**Comment by danielbachhuber** [comment]
Shipped with #66534
