### ISSUE TITLE
Marketplace: Add test to check plugin author page is correctly linked

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#66532]
To prevent #66520 from recurring, we would like an ~~e2e~~ component test to check this flow:

- ~~Visit https://wordpress.com/plugins/wordpress-seo-premium~~
- ~~Click on the plugin developer~~
- ~~You should be redirected to /plugins/?s=developer:"toast"~~
- Render `PluginDetailsHeader`
- Check for the correct author URL in href attribute

**Comment by cpapazoglou** [comment]
> You should be redirected to /plugins/?s=developer:"toast"

Since we want to test it end to end, would it be preferable testing the resulting interface rather than the resulting link?

For example, the resulting interface should contain a textbox with the relevant search term

![CleanShot 2022-08-12 at 17 06 56@2x](https://user-images.githubusercontent.com/12430020/184372974-a3eb34f4-68b5-4c09-8270-e5453b7125f2.png)

**Comment by candy02058912** [comment]
Decided to move it to component test as suggested by @worldomonation [here](https://github.com/Automattic/wp-calypso/pull/66562#discussion_r945886729).

Turning it into a component test still serves the purpose of preventing [the issue mentioned](https://github.com/Automattic/wp-calypso/pull/66520).

**Comment by worldomonation** [comment]
> Decided to move it to component test as suggested by @worldomonation [here](https://github.com/Automattic/wp-calypso/pull/66562#discussion_r945886729).
> 
> 
> 
> Turning it into a component test still serves the purpose of preventing [the issue mentioned](https://github.com/Automattic/wp-calypso/pull/66520).

I think you did a really good job here! Well done👏
