### ISSUE TITLE
WordPress.com login SSO creates an account with "Anyone can register" on private Atomic site

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#66548]
### Quick summary

With SSO and "Anyone can register" option enabled under wp-admin/options-general.php , anyone can bypass and access the private privacy setting.

Bump across this bug while trying to reproduce https://github.com/Automattic/wp-calypso/issues/66547

### Steps to reproduce

1. Setup WordPress.com site as Atomic, and site privacy as private.
2. Enable "Anyone can register" in wp-admin/options-general.php

### What you expected to happen

Users should not be able to access private AT site

### What actually happened

User account created as a subscriber directly after logging in to JP SSO. (even if no invite was made to user)

![Screen Capture on 2022-08-13 at 18-00-53](https://user-images.githubusercontent.com/34882260/184479052-49b131dd-b85e-4e47-a261-39576e924d3e.gif)

gif link: https://d.pr/i/q195Az

### Platform (Simple, Atomic, or both?)

Atomic

### Available workarounds?

Yes, easy to implement

### Workaround details

Turn off "Anyone can register"

**Comment by Greatdane** [comment]
I am not sure if this is a bug? If 'Anyone can register' is enabled, the viewer is able to freely register and become a subscriber, at which point they have access to the site because they are now a user (regardless of the privacy settings)

Basically, the Jetpack SSO 'logging in' screen is creating a user on that site because 'Anyone can register' is enabled? 

Maybe @Automattic/jetpack can confirm if this is intentional.

**Comment by jeherve** [comment]
> If 'Anyone can register' is enabled, the viewer is able to freely register and become a subscriber, at which point they have access to the site because they are now a user (regardless of the privacy settings)

Exactly. I would not see this as a bug. This is how the "Anyone can register" option is meant to be used; it allows anyone to create an account on your site, thus gaining access to all content that is only be accessible to folks with an account.
