### ISSUE TITLE
Stepper: Mobile 'Back' and 'Skip' buttons disappear after interacting with certain forms

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#66611]
#### Steps to reproduce

Seems to be specific to Firefox for Android. I didn't see the behavior in mobile Chrome and I couldn't test mobile Safari.

1. On a real mobile device, https://wordpress.com/start
2. Create a new site with the Sell intent and the "More Power" upgrade
3. When you get to the `businessInfo` step, you should have both the "Back" link and the "Skip for now" link in the footer.
4. Check the "Physical Products" or "Downloads" boxes.
5. When you uncheck the box, the footer links will disappear.
6. Scrolling the page will bring the footer links back.

https://user-images.githubusercontent.com/917632/184951341-8cafa1eb-7e3f-41bd-b6ee-ba2e0e981e18.mp4

**Comment by nelsonec87** [comment]
I couldn't reproduce the issue on my device, but a different one, that might be related:
This is the screen:


![image](https://user-images.githubusercontent.com/3801502/195999073-e0ecca90-6153-4bdd-b922-07f206055c59.png)

If I scroll to the bottom, the address bar is hidden by the browser, but the action bar gets taller instead of bottom to the [new] bottom:


![image](https://user-images.githubusercontent.com/3801502/195999110-8e48eaa4-0817-48d2-8b4f-b12232d6427e.png)

**Comment by andres-blanco** [comment]
this doesn't apply anymore since the steps involved in reproducing this bug have changed or don't exist anymore.
