### ISSUE TITLE
Latest Instagram Posts block: images display in different sizes

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#66653]
### Quick summary

Instagram Posts block images display in different sizes and there isn't control over that. Usually the third row is different. Even our support doc example has this problem: https://wordpress.com/support/instagram/#latest-instagram-posts-block
Also, saw slack discussions about it.
![Markup 2022-08-17 at 19 03 46](https://user-images.githubusercontent.com/11535091/185199878-90f5d2a6-52e5-483c-82b7-84301ec0a393.png)

### Steps to reproduce

1. Add Instagram Posts block
2. Connect with IG account with more than 6 images

### What you expected to happen

Images display in the same size - squares.

### What actually happened

Last row images are different, height is bigger. 

### Context

5485594-zd-woothemes, tested on my site too

### Theme-specific issue?

no

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

.wp-block-jetpack-instagram-gallery .wp-block-jetpack-instagram-gallery__grid-post img {
  height: 100px !important;
}

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Uncertain
- Tested on Self-hosted - Could Not Replicate
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I could not replicate this issue on Simple or Self-hosted (block is from Jetpack). All posts display the same size.
- Screenshot: 

<img width="1047" alt="Latest Instagram Posts" src="https://user-images.githubusercontent.com/30788962/186745829-d32e8e20-e6fe-48e0-9f0e-d5f5f86f1e47.png">

- I could not test on AT because Instagram would not connect.
- I am not sure that the support doc shows an example of this—it looks like the screenshot does not include the full third row.

📌 ACTIONS
- Await author feedback

📌 Message to Author
- Is this an intermittent issue or do you have more details on how to replicate this? I have not been able to replicate this in my tests so far but I had some trouble testing on AT, so I will leave this open for now in case anyone else is able to test.

**Comment by daria2303** [comment]
@jamiepalatnik thank you for checking, I am able to replicate on atomic ![jy0Yyz.png](https://user-images.githubusercontent.com/11535091/187060892-05215a59-ce88-4332-91ac-a318911b87bc.png)

In our doc we can see that the first row is higher than the second one ![iewG8A.png](https://user-images.githubusercontent.com/11535091/187060965-ab9db59a-e221-4d3d-8751-91cf140a8805.png)

**Comment by jamiepalatnik** [comment]
@daria2303 Thanks for testing again! Moving this back to Needs Triage to see if anyone else is able to replicate.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- it took a while to get this to show up - but finally was able to replicate. It seems the height changes depending on the contents of the row - rows with videos or reels show up taller, while rows with only photos in them (or possibly with videos but not reels) are shorter. 
- In replicating, it helps to have a mix of photos/videos/reels in the feed you're sharing, and to keep the columns low, so you can catch a row with only one kind of content in it. See below: 

*Example*
![Markup on 2022-09-13 at 10:32:30](https://user-images.githubusercontent.com/27249804/189971020-41a10836-173b-4e60-bdc8-d5b1f05017aa.png)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by daria2303** [comment]
Thank you @cuemarie for checking that! I should mention that my test IG account has just several images and still it displayed weirdly. However, at the moment I am not able to connect with IG at all.

**Comment by aleone89** [comment]
Another report here: https://wordpress.com/forums/topic/latest-instagram-post-block-display-issue/?view=all#post-3891733 

Plan: Personal 
Theme: Gateway 

I've deployed the workaround as seen above.

**Comment by karenroldan** [comment]
Hi @jeherve, should we move this to Jetpack?

**Comment by karenroldan** [comment]
Hi @jeherve, should we move this to Jetpack?

**Comment by jeherve** [comment]
I believe that's already tracked in https://github.com/Automattic/jetpack/issues/22241 . I'll add a link and some more details (like how videos / reels can make this easier to spot) to the issue, and I believe we can close this one.
