### ISSUE TITLE
Theme/Plugin Bundling: Flow eligibility check

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#66689]
# New functionality needed

We need some kind of check as part of the new `plugin-bundle-flow` to make sure that a user is actually eligible to proceed with the flow. This will prevent people from accessing the flow directly or any other weird edge cases.

@mreishus had some possible ideas in a comment on paYKcK-20n-p2.

Possible approaches include:

- An invisible first step which checks eligibility and sends the user to the next step or sends them back.
- Doing the eligibility check as part of the loop over `availableFlows`.
- Adding an ad-hoc check to `FlowSwitch` similar to what we're doing for Anchor.

# Defining eligibility

A user is eligible to proceed with the plugin-bundle flow if:

1. They have a Business (or higher) plan.
2. They've selected a theme that supports plugin bundling.
3. _Is there anything else?_

**Comment by mreishus** [comment]
Instead of checking for a business plan directly, we should check for a feature ( see: PCYsg-IbE-p2 ). Some candidates are ATOMIC or WOOP features.
There is some code in stepper already for checking this, but I think it's currently only used on the removed 'simple/power' step:
https://github.com/Automattic/wp-calypso/blob/9e4c5b39e4217532c084fce88c354f26f083afe8/client/landing/stepper/declarative-flow/internals/steps-repository/store-features/index.tsx#L32-L34
