### ISSUE TITLE
Feature Request: Generate headstart annotation from an Atomic site.

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#66738]
### What

Part of the theme launch process is generating headstart annotations (see the FG page on Headstart), but we've never done this with Atomic site as the source. The purpose of this issue is to explore if it's possible to do that.

Since premium themes are available to customers on the Premium plan, it would also be good to investigate what would happen if the annotation generated from the Atomic site was applied to a simple site and make sure everything is working properly. 

We currently have one premium theme in the works - [Thriving Artist](https://thrivingartistdemo.wpcomstaging.com/) - that could serve as a test subject.

Some discussion and ideas around this: p1660841410506979-slack-C02M88KJ684

### Why

We're working on themes featuring the WooCommerce store. In order to showcase the store on the theme demo site, we need to upgrade to Business and activate WooCommerce, which will make the site Atomic.

**Comment by simison** [comment]
Since Atomic sites have also simple site counterparts (or at least used to have), produced by Jetpack syncing, you might be able to sync juts that.

If it's just blocks, note that premium/woo blocks can be present on simple site's page and post content. They just won't render properly without the plugin, but it might be enough for headstart purposes. Ideally the demo would be the same as the headstart source tho, so pulling from Atomic sites would be great.

Something that concerns me with Atomic sites would be speed, which might be quite a bit slower than dealing with Simple sites.

**Comment by alaczek** [comment]
Here are some earlier explorations from @roo2 on supporting Atomic sites with Headstart: pbxlJb-WW-p2

**Comment by valterlorran** [comment]
Hey @alaczek, we had a discussion here p1661797380066559-slack-C0Q664T29 about this topic, and we reached a consensus that the headstart should not be the place to ensure that the applied site matches the demo site, regarding the plugins required.
I'm still working and waiting for approval on the fix(D86789-code) to be able to generate the headstart annotation from an atomic demo site.

**Comment by mreishus** [comment]
Building on the idea in D86789-code, I made D87766-code which only modifies behavior if a new flag is passed, in attempt to minimize the risk associated with the change. However, it's still a high risk change and we would still need the blessings of the systems team to go ahead with this approach.

**Comment by mreishus** [comment]
Discussion of some options here: p1663253248210669-slack-C0Q664T29 .
Even though we're only using it for a manual process that occurs rarely, D87766-code is still high risk since it modifies critical files.
Bringing in all of the files needed for wpcom's headstart generation file ends up adding 90 files to wpcomsh or a custom plugin.
Inspired by Andy's changes in wpcomsh re: class-template-first-themes.php, I will spend some time trying to make a scaled down annotation generation with little or no dependencies for wpcomsh. If we can drop support for some things, like widgets, then we don't need to pull in so much code.

**Comment by mreishus** [comment]
Atomic Headstart Generation: Is now a part of the theme-demo-bar-plugin. https://github.com/Automattic/theme-demo-bar-plugin
