### ISSUE TITLE
[All] Review CTA buttons' sizes - make sure they match the intended design

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66747]
It looks like there's a slight difference between the sizes currently used in the new templates when compared to designs in Figma (c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A23435).

We can compare the differences and fix if necessary.

**Comment by TimBroddin** [comment]
I did an investigation into this ticket. 

It seems that in the Figma design, there is a line-height of `24px` set on the button. In the CSS, this gets set to `1 `(which resolved to the font size `16px`). Changing this to `24px` gives a taller button.

Furthermore, there's a `1px transparent solid` border around/inside the button. This adds to the width/height of the button, as it will take on the background color of the button, since it's transparent. Even though `box-sizing` is set to `border-box`, this doesn't affect the calculation of width/height, since this only applies when width/height properties are set on the element. [MDN link on box-sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing)

After setting the line-height to `24px` and removing the transparent border, we have almost the same button as in the Figma design. The only real difference seems to be the font used, `-apple-system` seems to prefer SF Text, while in Figma, it's SF Pro Display.

I made [a small CodePen](https://codepen.io/timbroddin/full/PoeQjgL) to play with the options mentioned above.

This image summarizes all the variations mentioned above:

![image](https://user-images.githubusercontent.com/528287/192815618-c7145c3f-0fd0-4c4b-9ff2-cf41faeab236.png)

My recommendation:
- Set line-height to 24px
- Either remove the transparent border, or adjust the padding accordingly

**Comment by ivan-ottinger** [comment]
Perfect! Thanks, Tim! Your recommendation sounds good to me. 👍🏼

**Comment by TimBroddin** [comment]
These are the affected templates:
- comment-aproval 
- comment-like 
- comment 
- invitation-confirmed-invitee 
- invite-contributor 
- invite-follower 
- new-follower 
- new-post
- site-confirmed 

I'm going through all of them to see if removing the border & changing the line-height doesn't break anything.

**Comment by ivan-ottinger** [comment]
D88806-code is now merged and deployed.
