### ISSUE TITLE
[Bug]: Search icon covers the plugins page heading

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#66743]
### Quick summary

Screenshot here: ![https://d.pr/i/w6eBG8](https://d.pr/i/w6eBG8+)

### Steps to reproduce

1. Go to /plugins/active/:atomicSiteId
2. Scroll down

### What you expected to happen

The search icon should go under the plugins page heading

### What actually happened

The search icon should went over the plugins page heading

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Atomic, Self-hosted

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic –Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- No longer appears to be an issue; this may have been addressed in a page redesign since this report was filed.

#### Screenshots/Recordings

![wYFjwg.gif](https://user-images.githubusercontent.com/27249804/236020360-d5d0532a-2e15-4176-b0d1-bc62e8352233.gif)

📌 ACTIONS
- Closed as no longer relevant
