### ISSUE TITLE
Pattern Assembler: Show the pattern selector on "build-your-own-layout" step

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#66788]
# Description

We want to show the pattern selector on "build-your-own"  step (the Pattern Assembler flow). It will contains title, ~search bar~, patterns and the "Continue" button. It might have the back button in the future (See [this](https://www.figma.com/file/7l53h5fxAUNjVRBQ82YFwn?node-id=249:41386#249318120)).

Here are related endpoints to fetch the patterns
* Gutenberg uses [getBlockPatterns](https://github.com/WordPress/gutenberg/blob/cb84d6e225e5e245d3fe5caed6425c3fe41635b2/packages/core-data/src/resolvers.js#L480) to query patterns from the `/wp/v2/sites/:site_id/block-patterns/patterns` endpoint. And this endpoint will return **ALL** registered patterns
* ETK plugin hooks to [rest_dispatch_request](https://github.com/Automattic/wp-calypso/blob/897ccdf8027bf0b84308821a139f82760348bef0/apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php#L266) to register the patterns from the `/rest/v1/ptk/patterns/:locale` endpoint before the previous API called. ~**We need to check how many patterns are registered here, and how could we register these patterns in the current step**~

I thought we might need to query these two endpoints and combine the patterns 🙂

We can refer to [__experimentalGetAllowedPatterns selector](https://github.com/WordPress/gutenberg/blob/4f0f70da41191b110cd82dd91d40da46110e4658/packages/block-editor/src/store/selectors.js#L2291) and [patternsTab](https://github.com/WordPress/gutenberg/blob/4f0f70da41191b110cd82dd91d40da46110e4658/packages/block-editor/src/components/inserter/menu.js#L136) from Gutenberg to see how does it work 🙂

![image](https://user-images.githubusercontent.com/13596067/185580208-8f9702b7-2191-428c-8876-9d946de575c1.png)

7l53h5fxAUNjVRBQ82YFwn-fi-238%3A41198

# Acceptance Criteria

- [x] Show the whitelisted patterns
- [x] When you click on a pattern, it will be selected and you will go back to the main screen.
- [ ] ~When you type something in the search bar, we have to filter the patterns by its title (?)~. NO SEARCH FOR THIS MVP

# Dev Tasks

- [x]  https://github.com/Automattic/wp-calypso/pull/66954

# Related

* https://github.com/Automattic/wp-calypso/issues/66589

**Comment by miksansegundo** [comment]
@arthur791004 I've read your [comment](https://github.com/Automattic/wp-calypso/issues/66589#issuecomment-1219341048) about the previews performance. 

The pattern selector in Gutenberg renders the preview of patterns in [iframes](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-preview/auto.js#L79) by creating a portal in the `documentElement` and then rendering the HTML directly, without using any server API.

I think that solution will perform better than using the API `/wpcom/v2/block-previews/pattern`, and I like the fact that is controlled in the front-end. However, I'm going to try first to preview using the API as it could be a simpler implementation, and we should test its performance before making a decision.  

Maybe we could use the same iframe technique for the site preview, instead of using the server API `/wpcom/v2/block-previews/site`.

**Comment by arthur791004** [comment]
> The pattern selector in Gutenberg renders the preview of patterns in [iframes](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-preview/auto.js#L79) by creating a portal in the documentElement and then rendering the HTML directly, without using any server API.

Yes, it would be better if we could render the preview in iframes on the frontend side but it's a big effort. We could try the preview API first as you said to see whether the performance is acceptable on production or not 🙂

**Comment by autumnfjeld** [comment]
cc: @mtias on the above discussions

**Comment by miksansegundo** [comment]
I've tested the loading times using the production preview API. The times are not bad. Here is a recording showing the loading times for:

- 7 Headers
- 15 Sections
- 2 Footers

https://user-images.githubusercontent.com/1881481/187354295-ca7610ac-e48b-4966-856b-23f3acd86c34.mov

I'm working on a preloading system that could reduce the initial loading time. I'll share a recording in an hour.

**Comment by miksansegundo** [comment]
Here is the recording using the preloading system. Thanks @taipeicoder for the idea! 

https://user-images.githubusercontent.com/1881481/187363993-aa7e7911-29b6-4156-9417-9d0a89241835.mov

If the user takes 2~3 seconds to open the pattern selector, the previews will be pre-loaded. In following attempts they will be preloaded, and the scroll preserved because the HTML (iframes) are never removed, only hidden. 

@autumnfjeld this solution could be good enough if we keep the lists short.

**Comment by autumnfjeld** [comment]
Fantastic @miksansegundo !

I think this will be quite suitable for an MVP! 

> If the user takes 2~3 seconds to open the pattern selector

Perhaps there is even something deliberate that can be done to "slow" the user, like have a bit of educational copy that takes a few seconds to read or something clever like that.    But even without that, I think the demo you showed above is good!!

**Comment by autumnfjeld** [comment]
![image](https://user-images.githubusercontent.com/5665959/187372848-ded501da-f317-4bf4-95e5-05fcb8e92652.png)

I think we might want clearer langauge here @SaxonF  (not sure on the state of copy), but user might need more literal language.  "Create your page layout by selecting a header, a footer, and section patterns below."   (That's just an idea, can be better 😃)

Also see comment above.

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/66954. As we show the whitelisted patterns on the current iteration, there is no need to fetch the endpoint.
