### ISSUE TITLE
Sites Management Page: Fix issue where empty page and "show hidden" message appear during loading

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66898]
Occasionally seeing an empty list where only the "Show hidden sites" message displays while SMP loads.
Seems to happen during force refreshes.

See video here: pdtkmj-nh-p2#comment-613

It'd be good to get to the bottom of what causes this. It might be more likely to happen during local development when force refreshes of the store can be required. In which case it's not as big a deal.

**What I Expected**
If for whatever reason page isn't ready to show the sites then it should be showing the loading state.

**Comment by danielbachhuber** [comment]
@p-jackson This bug kinda sucks. 

`useSitesDisplayMode` can return `'none'` when the remote preferences aren't loaded yet:

https://github.com/Automattic/wp-calypso/blob/294575e86ca18c4449412bd203b099ba46721641/client/sites-dashboard/components/sites-display-mode-switcher.tsx#L20-L31

#66942 "fixes" the issue by ensuring the hidden sites message and button doesn't appear when `displayMode='none'`.

I put "fixes" in quotes because I feel like it's only a partial fix. We _might_ want a loading state for `displayMode` because the current implementation of a partly empty page feels a little broken. However, we might not want a loading state for `displayMode` because it might be too many partial flashes of UI.

Thoughts?

**Comment by p-jackson** [comment]
Ugh 😭 
Good debugging @vykes-mac and @danielbachhuber 

I think the simple fix of hiding the hidden sites message is acceptable for i1. The user preferences will usually already be loaded, and they will load a lot faster than the site list anyway.

After i1 ... I've been thinking about adding another loading indicator somewhere in the UI. Like tucked away in a corner or something. It might be good to show a spinner while the sites query is in the `isFetching` state. That way it might be less jarring when the sites rearrange themselves, because the user could see an update was going on in the background.

Anyway, maybe we could use that same spinner when loading the user preferences too.

![CleanShot 2022-08-25 at 11 01 31@2x](https://user-images.githubusercontent.com/1500769/186538678-953bfa29-8a5a-45b6-9695-0df7aaaba9cd.png)
