### ISSUE TITLE
Jetpack NUX: store a property on users that have previously connected Jetpack

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6689]
Currently, if you disconnect and reconnect Jetpack we treat users as if they are brand new. This poses several possible problems:
- When a user connects for the first time we would like to take them through the full NUX, but on subsequent connections we may want to tailor the experience as a 'welcome back' or perhaps provide support opportunities. (Related to #5716)
- When we attempt a 1-click auth test we need to know if the user has previously connected or not (to perform the appropriate redirection and to not attempt to create a new wp.com account for them)

To alleviate these problems we need to store some sort of property when users have connected a specific site. We can then use that to tailor the experience if they try re-connecting.

cc @johnHackworth @roccotripaldi

**Comment by roccotripaldi** [comment]
Good call!

**Comment by rickybanister** [comment]
This is also very relevant to a conversation raised by @rralian in which a site lost it's connection without a proper disconnect flow. You can then view sections in Calypso with lots of errors and no data for a period before we simply remove that site from the site's list. Instead we should offer them a very easy Jetpack 'Re'Connect flow in which they click one button, authenticate on the remote site side, and the site is reconnected, data restored.

**Comment by alisterscott** [comment]
Is this still an issue with recent work done on Jetpack NUX?

**Comment by rickybanister** [comment]
This is still an issue, yes, we continue to present the same experience, regardless if that site has been previously registered.

**Comment by worldomonation** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. **Report anew**: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. **Reopen**: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
