### ISSUE TITLE
Sites Management Page: Add dropdown for changing Sort Order, and apply Sort Order to Sites List

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#67043]
We'd like to add a dropdown to the Sites Managment Page for changing the Sort Order. It should live with some lower profile UI next to the display mode icons:

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/36432/189230679-48772246-01ab-4afd-a055-1c80c1b8a3a8.png">

When the user changes their Sort Order, it should save to their persistent user preferences and also be applied to the Site Selector.

Originally proposed with pdKhl6-I6-p2

**Done is:**
* [x] There's a new Sort Order dropdown on the Sites Management Page. It should have a more subtle, secondary UI to the launch status dropdown.
* [x] The Sort Order dropdown offers these options: Alphabetically (A-Z), Automagically, Last Updated. The dropdown defaults to “Automagically”.
* [x] Our “Automagically” option orders sites based on frequency of interaction (underlying data coming with 805-gh-Automattic/dotcom-forge) and puts the primary site on top. "Frequency of interaction" algorithm is at the engineer's discretion.
* [x] The selected Sort Order is applied to the Site Switcher. However, there won't be any Sort Order UI in the Site Switcher.

**Comment by zaguiini** [comment]
Action plan for this issue:

1. add a preference that saves and syncs the current sorting order in the back-end, just like we have for the display mode (PR no. 1);
2. pass the value of the preference to `useSitesTableSorting` (PR no. 1);
3. add alphabetical A-Z and Z-A sorting algorithm to `useSitesTableSorting` (PR no. 1);
4. add a text-only dropdown link to SMD that opens a native select, allowing the user to pick one of the options and set the preference accordingly (PR no. 1);
5. add automagically sorting algorithm to `useSitesTableSorting` (PR no. 2);
6. retrieve last interaction data if the selected sorting order is automagical (PR no. 2);
7. pass `automagical` as a value to `useSitesTableSorting`, along with the interaction data (PR no. 2);
8. add the "Automagically" option to the sorting dropdown (PR no. 2);
9. use `useSitesTableSorting` in the site switcher (PR no. 3).

Step no. 9 will remove the recent site's section in the site selector since the automagical sorting takes the last interactions (recent) into account.

**Comment by zaguiini** [comment]
Also question @danielbachhuber, why didn't we use the `recentSites` preference instead of creating a whole new mechanism to expose the sites that the user last interacted with?

The main reason I can think of is that it saves a site as "recent" based on visiting only, which is kind of shallow and doesn't do much in the context of updating it. So, thinking about it, does it make sense to include sites table sorting in the site switcher, since they serve different purposes?

**Comment by danielbachhuber** [comment]
> why didn't we use the `recentSites` preference instead of creating a whole new mechanism to expose the sites that the user last interacted with?

@zaguiini Great question! A couple of answers:

1. The primary reason is that our new abstraction will support both recency _and_ frequency. The theory is that combining both of these will allow us to produce a better relevancy algorithm.
2. The secondary reason is that server-side events are a better source of truth for interactions. Plus, we have some opportunity to re-evaluate which events are considered an interaction (instead of shallowly looking at Calypso visits).

> The main reason I can think of is that it saves a site as "recent" based on visiting only, which is kind of shallow and doesn't do much in the context of updating it. So, thinking about it, does it make sense to include sites table sorting in the site switcher, since they serve different purposes?

I'm not sure I follow "does it make sense to include sites table sorting in the site switcher"... can you clarify further?

The key idea is to have a consistent sort order between the Sites page and Site Switcher.

> retrieve last interaction data if the selected sorting order is automagical (PR no. 4);

The interaction data is returned on each `site` object, similar to the `visible` property. Having the interaction data available is simply a matter of updating `useSiteExcerptsQuery` and the Redux action to request the `user_interactions` site field too.

**Comment by SaxonF** [comment]
We can use same dropdown as status filter and label could be "Sort by: Name" instead of "alphabetically"

**Comment by danielbachhuber** [comment]
Saxon and I chatted briefly about the dropdown design in Slack: p1663015307662189-slack-C041RHH38NQ

Eventually, we decided to keep the current implementation as-is, but may update the design in a future GitHub issue.

**Comment by zaguiini** [comment]
>can you clarify further?

You gave the explanation in the very next sentence:
>The key idea is to have a consistent sort order between the Sites page and Site Switcher.

😄

**Comment by danielbachhuber** [comment]
@zaguiini One thing I just thought of (while looking at #890): we're not yet tracking interactions for non-Automatticians, so "automagical" sorting doesn't actually do much 🙃

We should probably only make the option available to Automatticians until we track interactions for all users (#909).
