### ISSUE TITLE
Global Styles: Layout Dimensions can't be changed

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#67059]
### Quick summary

On at least two themes, the Global Styles layout setting does not actually save changes to the dimensions. You can input a new number, but when you hit Save they are set back to default.

<img width="592" alt="Screen Shot 2022-08-26 at 4 41 26 PM" src="https://user-images.githubusercontent.com/31680407/186989305-8a7f992e-c1ee-47d6-967e-49b8468f9f38.png">

### Steps to reproduce

1. Activate an FSE theme, tested on Blank Canvas and Quadrat
2. Go to Appearance > Editor
3. On the top right, select Global Styles
4. Select Layout
5. Change the Content or Wide dimensions to anything else, click Save

### What you expected to happen

To save new dimensions for the site's content area

### What actually happened

The values reverted to what they originally showed

### Context

Reported by a customer, reproduced by HE

reported in 

- [ ] 5510316-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Applies at least to:

Blank Canvas
Quadrat

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by rw-ye** [comment]
Another report here: 5493921-zd-woothemes

Theme: Blank Canvas

**Comment by kerrynicl** [comment]
USer report - 36522030 - hc
User unable to remove block spacing, defaults to 1.5 rem

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: Could Not Replicate
- Tested on Self-hosted: Could Not Replicate
- Replicable on Core? Not so far

📌 FINDINGS/SCREENSHOTS/VIDEO
- Based on my findings below, this issue seems to be site-specific, not theme specific. Take a look:

Testing Round One:
- AT Site on Quadrat White: Could Not Replicate
- **Simple Site on Blockbase: **Replicated****
- Self-Hosted Site on Blank Canvas: Could Not Replicate

Theme Swap:

- AT Site on Blockbase: Could Not Replicate
**- Simple Site on Quadrat White: **Replicated****
- Self-Hosted on Blockbase: Could Not Replicate

➡️ The issue was reproducible, but in my tests, it followed the site, not the theme.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by dcoleonline** [comment]
Another in 5532506-zen

**Comment by hanananah** [comment]
Another in 36989848-hc

Meraki theme, but they've tried other themes as well with the same issue

**Comment by ghost** [comment]
Another in 5588431-zd-woothemes Zoologist theme

**Comment by Copons** [comment]
@mmtr this looks similar to https://github.com/Automattic/wp-calypso/issues/67344
Would you mind checking this within the same context?

Note that the initial report mentioned Atomic, but a [following comment](https://github.com/Automattic/wp-calypso/issues/67059#issuecomment-1233682252) can't repro anymore.

**Comment by mmtr** [comment]
@Copons Yes, this is the same issue as https://github.com/Automattic/wp-calypso/issues/67344 which is caused by this Gutenberg bug: https://github.com/WordPress/gutenberg/issues/45520

**Comment by msilbers** [comment]
This was reported  in 37532163-hc on Appleton theme

**Comment by dolgelukkig** [comment]
Another report 38364437-hc theme Payton

**Comment by mmtr** [comment]
This is being fixed upstream in Gutenberg: https://github.com/WordPress/gutenberg/pull/46388

**Comment by mmtr** [comment]
Turns out that https://github.com/WordPress/gutenberg/pull/46388 has fixed https://github.com/Automattic/wp-calypso/issues/67344 (block gap), but not this issue (dimensions). 

@andrewserong I think Gutenberg needs to add more properties to `INDIRECT_PROPERTIES_METADATA` in order to properly handle the the layout dimensions.

If no one beats me to it, I'll try to look into it tomorrow.

**Comment by mmtr** [comment]
I opened https://github.com/WordPress/gutenberg/pull/46712 as a fix for this.

**Comment by louinel** [comment]
New case in 5847270-zd-woothemes Twenty Twenty-Three theme

**Comment by Copons** [comment]
Note that we have provided [a fix in Core Gutenberg](https://github.com/WordPress/gutenberg/pull/46712), which is included in Gutenberg 14.9, which should be released on Dotcom this week.

**Comment by mmtr** [comment]
Gutenberg [v14.9.1](https://github.com/WordPress/gutenberg/releases/tag/v14.9.1) is now running on all WP.com sites, so this issue should be solved.
