### ISSUE TITLE
Subscribe Block: Clicking Subscribe button snaps page scroll below the success message

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#67070]
### Quick summary

After clicking the submit button on a Subscribe Block, the page is abruptly scrolled down. This has something to do with the success message being displayed, but the page is scrolled below the success message, so it isn't visible. From a user's perspective, it's jarring and confusing.

### Steps to reproduce

1. Add a Subscribe Block to a page.
2. Add enough content below the Subscribe Block so that the page can scroll vertically.
3. Publish the page.
4. Visit the page and attempt to subscribe.

### What you expected to happen

On WoA, the page is instantly scrolled down below the success message. On simple sites, the page is instantly scrolled down to the success message.

### What actually happened

The page should not scroll at all when the success message is displayed.

### Video of the issue

https://user-images.githubusercontent.com/1519466/187096429-c8cd4639-b027-452a-b89b-451b25aec171.mp4

### Context

Customer report: 5509623-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Calypso only block. N/A

📌 FINDINGS/SCREENSHOTS/VIDEO
- Am able to replicate the issue on Simple and Atomic
- I suspect this is due to the way the anchor works `?subscribe=success#subscribe-blog-1` 

https://user-images.githubusercontent.com/5075840/187834991-0797af5e-e3dd-4748-8fb6-48b457badb92.mp4

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by katinthehatsite** [comment]
Hi @masperber - thanks for your report!

I just started working on this and while testing the issue, it seems that Subscribe Block has changed its behavior which eliminated the issue that you are reporting. At the moment, once you submit your email, you are getting a modal /popover that informs you about the email being sent to you. Once you close it, the page refreshes with the success message and the page gets back to the place where it was previously with no scrolling effect.

This is what I am seeing on an Atomic site for success and incomplete token:

https://github.com/Automattic/wp-calypso/assets/25575134/bbb8747e-bb1f-4cfe-b0b6-2c3e24cff1f7

This is what I am seeing on a Simple site for success and incomplete token (there is no success message available f[or Simple sites as per support page](https://wordpress.com/support/wordpress-editor/blocks/subscribe-block/#success-message):

https://github.com/Automattic/wp-calypso/assets/25575134/137e346e-7d99-4fe7-a8a8-31c3be42c68f

@masperber Could you please confirm that the issue no longer exists so that I can close it on our end? Thanks!

**Comment by katinthehatsite** [comment]
Since I could not replicate this, I am going to close this for now! If the issue persists, feel free to reopen.
