### ISSUE TITLE
Purchases Page: Refactor existing code for function PurchaseMetaPrice with suggestions

### ISSUE THREAD

**Issue by spraveenitpro** [Automattic/wp-calypso#67133]
### Quick summary

1. Use only early returns rather than reassigning period so that it's clear what each block's priority is.
2. Don't assume that the default term is "yearly"; if we cannot figure out the term in any other way, maybe display nothing at all and/or throw an error.
3. Only use bill_period_label if none of the other conditions is found (ie: only if plan.term does not exist, etc.).
4. Add unit tests to cover different products (marketplace, plans with different terms, one time purchases, transfers, included purchases, etc.) and verify their term is what is expected.

### Steps to reproduce

Nothing to reproduce, this is related to refactor to avoid future bugs

### What you expected to happen

Nothing but code refactor

### What actually happened

This is the result of outcomes from the below Issues:
1. #64923
2. #66025

**Comment by sirbrillig** [comment]
I'm moving https://github.com/Automattic/wp-calypso/pull/69904 to the review column since (I believe) it fixes this issue and moving this issue to in-progress to avoid cluttering the column (since there's nothing to review here).

I've also updated the description of that PR to read "Fixes 67133" so it will automatically close this issue when it is merged. If I'm wrong and this issue should remain open, please undo that change.
