### ISSUE TITLE
Orvis theme link color in editor not showing on Atomic sites

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#67134]
### Quick summary

Unless links are given a highlight color in the editor, they do not show on Atomic sites using the Orvis theme as soon as the default link color is changed in the customizer.

5516610-zen

### Steps to reproduce

1. Add the Orvis theme to a site.
2. Make sure the site is Atomic.
3. Change the link color under Appearance > Customize > Colors & Background to anything other than the default.
4. Add a link to any post or page without giving it color using the highlight option.

### What you expected to happen

Expected links to show as blue in the editor unless a highlight color is added.

![Screen Shot 2022-08-29 at 6 11 13 PM](https://user-images.githubusercontent.com/34966264/187308656-a2c57051-0729-4014-9ac4-2745eec7edfe.png)

### What actually happened

If the site is Atomic and the link color has been changed in the customizer, the link cannot be seen in the editor, even though it still shows on the live page or post.
![Screen Shot 2022-08-29 at 6 18 22 PM](https://user-images.githubusercontent.com/34966264/187308827-e93e283c-b07d-4ffc-87fb-93cae588e890.png)

### Context

The links still show on the live page, but not in the editor. I've only found it happening on Atomic sites.

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Have only had it happen on the Orvis theme so far.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

It is easy to implement in the sense you can change the highlight color of each link in the editor, but could be time-consuming, depending on how many links the user has.

![Screen Shot 2022-08-29 at 6 20 54 PM](https://user-images.githubusercontent.com/34966264/187309117-83baaede-07fc-4ed3-bbd8-422d5d98dbf8.png)

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on AT - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was not able to replicate this issue. Links showed blue for me in the editor and the custom color on my live site as expected.
- I tested with a link in the Classic block and Paragraph block.
- I did notice some strange behavior that made the link hard to edit when a custom color was selected because the background and text color is the same as the custom color, but that seems to be a different issue. Screenshot:

<img width="691" alt="Orvis colors" src="https://user-images.githubusercontent.com/30788962/187984439-78595853-7617-43b2-b418-2b627cc7b1f8.png">

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- Since I'm not able to replicate this, I would recommend following up with the user to troubleshoot this further or suggest they use the workaround. If you can find how to replicate this issue on another test site or if there are other user reports, please feel free to reopen with more details. Thanks!
