### ISSUE TITLE
Marketplace: Browser back button double click

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#67143]
Browser back button requires two clicks when I expect one.

Repro: /plugins > click a category > click a search > click a result > click back > search results loads > click back again > **nothing** > click back second time > now we go back to category browser.

Acceptance:
- [ ] Back button doesn't need to be clicked twice to load back to the category browser

**Comment by WBerredo** [comment]
This is not the expected behavior anymore.

After https://github.com/Automattic/wp-calypso/pull/79483, plugin search and category selection are considered to be on the same "level", which means the breadcrumb will be replaced and not stacked after those two actions (click a category > click a search, and vice versa).

For category selection, the `back` option on breadcrumb is being tested with this e2e test:

https://github.com/Automattic/wp-calypso/blob/3be02186b67c624aeee5badbcfcf21d460f0ad88/test/e2e/specs/plugins/plugins__browse.ts#L62-L70
