### ISSUE TITLE
Marketplace: Category Description Design Adjustments

### ISSUE THREAD

**Issue by vinimotaa** [Automattic/wp-calypso#67239]
Recently we have implemented the category title + description on Marketplace.

As we iterate on a few things, I'd like us to make some minor adjustments to the overall page title/header.

- Title size to be 26px instead of 36px (across all the pages)
- Description/subtitle using our "Base/Regular" 14px
- Place the plugin number on the other side of the page also using our "Base/Regular" 14px
- Follow the padding indicated on the image bellow

![marketplace](https://user-images.githubusercontent.com/97929097/187783329-a3f6828e-72bd-4a23-ac9f-f623f5d96a39.jpg)

We thought this structure to be consistent across the Marketplace. Soon, we will have the same style/component structure not only on the categories but also on the main page and the search results page.

![title1](https://user-images.githubusercontent.com/97929097/187784577-10c55ad7-7468-434a-a976-d433f85119f2.jpg)
![title2](https://user-images.githubusercontent.com/97929097/187784589-363db2b3-e348-4c94-9ee9-68d38ebd12b9.jpg)
![title3](https://user-images.githubusercontent.com/97929097/187787907-1c2c6b34-cec0-4fc8-bab6-c507e1a65253.jpg)
![title4](https://user-images.githubusercontent.com/97929097/187787916-9ce2f455-8d41-414d-9106-a779bb238b07.jpg)

**Comment by vinimotaa** [comment]
A complete grid system and padding specifications for the entire landing page on this [Figma file](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=4273%3A39668).

**Comment by lsl** [comment]
This should be fixed by https://github.com/Automattic/wp-calypso/pull/67636 please let me know if production doesn't match anything required for this issue. 

- [x] Title size to be 26px instead of 36px (across all the pages)
- [x] Description/subtitle using our "Base/Regular" 14px
- [x] Place the plugin number on the other side of the page also using our "Base/Regular" 14px (if this isn't done for search count it will be done in the [follow up](https://github.com/Automattic/wp-calypso/pull/67781#issuecomment-1250436102))
- [x] Follow the padding indicated on the image bellow

Re font size 26, I used 24 per our [typography variables](https://github.com/Automattic/wp-calypso/blob/b7a4a072ae2a13785fb6ccbf9c34ed8e65739705/packages/typography/styles/variables.scss#L42). Please create a separate issue for changing that as I think there is issues with changing these on certain displays / browsers.
