### ISSUE TITLE
FSE on Simple Sites: Global Styles "Block Spacing" not accepting changes

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#67344]
### Quick summary

I had a user trying to figure out how to adjust the spacing between their header and the rest of their content within FSE, but every time they changed the measurement and saved the change would revert back to the default state. I tested this with an Atomic site which would accept the changes, but every theme I tried on a Simple site resulted in the same issue. I tested `Disco`, `Appleton`, `Archeo` and `Meraki` and they all could reproduce the error.

### Steps to reproduce

1. Set up an FSE theme on a Simple site
2. Navigate to `Global Styles > Layout`
3. Change the `BLOCK SPACING` amount and save the changes

### What you expected to happen

The changes would be retained upon saving.

### What actually happened

The settings revert back to default instantly.

### Context

36731616-hc

https://user-images.githubusercontent.com/51870544/188231646-7fcb9a9d-42d3-40b7-a8db-bf0a4f02f234.mp4

### Platform (Simple, Atomic, or both?)

Simple

### Browser, operating system and other notes

Replicated across `Chrome`, `Firefox`, and `Safari`.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Depending on how much they are wanting to change the only thing I've found to work is `CSS` - this user was fine with just `CSS` to address the issue with their `header` block but if they're expecting it to work on all of their blocks that would get complicated quickly.

**Comment by zachspears** [comment]
Able to reproduce. Keeping Normal priority due to high impact.

**Comment by dpasque** [comment]
I was doing some dogfooding on a site and ran into this, and wanted to add a little more information.

This actually seems to affect every setting under the Global Style Layout panel, not just block spacing. For example, you can't change the content width.

I also would recommend considering this for a higher priority, as the workaround for some of those settings can get a little tricky. For example, if you want to change the content width style, you have to do some pretty-involved CSS to override the values (because of how the base CSS rules are applied).

**Comment by ClassicRKR27** [comment]
- [ ] We've got another report here: 14591634-hc

**Comment by Joshgrygiel** [comment]
Another here: 37265127-hc

**Comment by janmckell** [comment]
- [ ] Another report here:  5594665-zd-woothemes

I also tested this, and I could replicate it on a simple site, on more than one theme, 'TwentyTwentyTwo' and 'Thriving Artist' (a paid theme).

**Comment by devNigel** [comment]
- [ ] Another report: 5619686-zd-woothemes

**Comment by sudeepbaral** [comment]
Another report where the layout dimensions change did not work.

- [ ] 5620083-zen

**Comment by Copons** [comment]
@Addison-Stavlo I think it makes sense if Ajax grabs this issue. Feel free to remove it from your backlog, if you agree! 🙂 
Also, on the off-chance someone has already started working on this, please reach out to us for pointers, suggestions, and whatnot!

**Comment by Addison-Stavlo** [comment]
> I think it makes sense if Ajax grabs this issue. Feel free to remove it from your backlog, if you agree! 🙂

Sounds great. Thanks @Copons !

**Comment by mmtr** [comment]
I think this happens because Simple sites are still not fully updated to WordPress 6.1 and they are lacking [this changeset](https://core.trac.wordpress.org/changeset/54162) which allows the `blockGap` property to be at any level. I cannot reproduce this on Atomic sites running WordPress 6.0 or self-hosted Jetpack sites running WordPress 6.1 and the lastest version of Gutenberg.

@david-binda do you have any idea about how long would it take to have that changeset in wpcom?

EDIT: Also asked in p94tqY-sD-p2#comment-1385

EDIT2: After discussing it privately with David, he told me that the changeset should land in WPCOM anytime this week.

**Comment by mmtr** [comment]
I took a deeper look at this since WP.com Simple sites are already running WP 6.1 and the issue is still present. Turns out that it's a Core bug that happens only when the KSES filters are active (which is the case of WP.com Simple sites), so I reported it in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/45520

**Comment by connorhipps** [comment]
Found another case with `Appleton` here: 5726870-zd-woothemes

**Comment by Copons** [comment]
I will close this issue for now because it's a Core bug tracked by a [Core Gutenberg issue](https://github.com/WordPress/gutenberg/issues/45520) (also assigned to the Ajax board).
