### ISSUE TITLE
Site Switcher: Clicking "Add new site" unexpectedly closes Site Switcher before navigating

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#67497]
Reported in Slack: p1662532879047989-slack-C0347E545HR

https://user-images.githubusercontent.com/36432/188870380-ddc81330-e6fe-42ed-8aaf-1ee190c13f63.mp4

The expected behavior is for the navigation to occur immediately, without the Site Switcher closing.

**Comment by danielbachhuber** [comment]
Debugging this a little further...

"Manage sites" includes the full URL in the button and doesn't exhibit this behavior. However, "Add new site" is only a path:

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/36432/188871588-f05242b4-b5e9-419f-ba99-7d8c520409b0.png">

It looks like the `SitePicker` component has some `clickOutside` behavior:

https://github.com/Automattic/wp-calypso/blob/750219f84230fb2fb1c60dbf876ca56ed0cf91b1/client/my-sites/picker/picker.jsx#L127-L129

However, if I disable `wrapWithClickOutside`, the behavior still occurs.

Importantly, the Site Switcher close transition occurs when clicking "View stats for all sites", which I think is expected behavior:

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/36432/188874063-5a18a97b-0dac-470c-b744-f659bdecf9d3.png">

My guess is that a link with a host is passed to the browser, while a link without a host is simply re-rendered by React. For the latter, some intermediate re-render state is taking place to close the Site Switcher.

**Comment by vindl** [comment]
> Importantly, the Site Switcher close transition occurs when clicking "View stats for all sites", which I think is expected behavior:

Site Switcher close might be fine (although it looks a bit janky), but the opening of the multisite sidebar is very unexpected. For more context, here is the screen that I got briefly during the transition:

<img width="1334" alt="Screenshot 2022-09-07 at 14 45 51" src="https://user-images.githubusercontent.com/1182160/188881970-a28c0ba3-2414-4d71-bbb0-d0210abf9d75.png">

**Comment by danielbachhuber** [comment]
> Site Switcher close might be fine (although it looks a bit janky), but the opening of the multisite sidebar is very unexpected. For more context, here is the screen that I got briefly during the transition:

@vindl To clarify, what is your expected behavior?

**Comment by vindl** [comment]
> @vindl To clarify, what is your expected behavior?

Same as when clicking on `Manage Sites`. The destination should obviously be different. 😄

**Comment by vykes-mac** [comment]
After some debugging I realise clicking the add new site button causes the Site Switcher to re-render before the navigation takes place, the `/start/domains` url is registered before navigation and results in error `This page is not available`. It would seem because `/start/domains` is not registered as a section it's simple rendered as a component where as manage sites is a registered section it is handled different (seems sections are preloaded?).

I've created a Draft PR that simply prevents the site switcher from re-rendering by stopping the add new site click event from propagating up to it's parent.  Thoughts?

**Comment by danielbachhuber** [comment]
> After some debugging I realise clicking the add new site button causes the Site Switcher to re-render before the navigation takes place, the `/start/domains` url is registered before navigation and results in error `This page is not available`. It would seem because `/start/domains` is not registered as a section it's simple rendered as a component where as manage sites is a registered section it is handled different (seems sections are preloaded?).

@vykes-mac Interesting!

> I've created a Draft PR that simply prevents the site switcher from re-rendering by stopping the add new site click event from propagating up to it's parent. Thoughts?

Seems a bit hacky 😁 I'm a little afraid of unexpected negative side effects of this approach.

It'd be great to clearly identify the root cause of the difference between "Manage sites" and "Add new site", and then solve the problem within those confines too.

No rush to solving the issue, so feel free to explore further as you have time.

**Comment by vykes-mac** [comment]
@danielbachhuber I agree it looks hacky. On further investigation It seems the issue lies in the `client/signup/controller.js: L288` `context.store.dispatch( setSelectedSiteId( null ) );`, This clears the siteId and cause the page to re-render with an empty page component since site info was cleared. 

Because onboarding flow consist of a series of steps the component for each step is loaded async `const stepComponent = await getStepComponent( stepName );` in our case the domains step, this results in the component taking longer to show as it's not pre-loaded like `/sites `component. The longer load time + the clearing of the siteId is what's causing the current behavior. 

We might have to create a function that loads the necessary component upfront without async import or try and force the necessary query dependencies to avoid the siteId being set to null.
```
	if (
			! providesDependenciesInQuery?.includes( 'siteId' ) &&
			! providesDependenciesInQuery?.includes( 'siteSlug' ) &&
			! isManageSiteFlow
		) {
			context.store.dispatch( setSelectedSiteId( null ) );
		} 
```

**Comment by danielbachhuber** [comment]
Taking our debugging to some discussion: p4TIVU-aiA-p2

**Comment by danielbachhuber** [comment]
@Automattic/build Moving this to `Hold` in our backlog. It seems like it's a `Low Value, High Effort` problem to fix, and may eventually be resolved by signup flow changes anyway.

**Comment by vindl** [comment]
Since we will be moving to surface the Sites page more prominently in the top nav, there will be less need to show `Manage sites` and `Add new site` in the switcher, and we can remove them. Closing since this will become a non-issue soon.
