### ISSUE TITLE
Signup: DSS: DSS flows should use the `ThemesList` shared component.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#675]
See #256 .

**Comment by sirbrillig** [comment]
After reviewing the `ThemesList` and `Theme` components, I don't think this issue is valid as-written. 

DSS uses a special `DssScreenshot` component in place of an image in order to render the markup of a theme as a "screenshot" with a custom image provided, so in order to replace it with a `Theme` component, we'd need to add some custom code to `Theme` to support a special screenshot as a child component. This is possible, but since DSS is still in the testing stage, I don't think it's necessarily wise to modify the `Theme` component in this way.

That said, the framework surrounding the theme list used by DSS was based on (and in some cases, copied from) the existing theme list components. It would be possible to refactor the DSS versions of those containers to more closely match the `ThemesList` and `Theme` component tree. Since the design of DSS is still in flux, however, I think this may want to wait until the next iteration of the DSS test.

I'm going to close this issue for now.
