### ISSUE TITLE
Plans Redesign: Update "My Plan" page to show 

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6760]
Let's update the http://calypso.localhost:3000/plans/my-plan to show a disabled button when features are enabled and no actions are required, for example: 

![5c09000a-48ec-11e6-9c5d-267ca9bc5208](https://cloud.githubusercontent.com/assets/1270189/16817648/916068ae-48f8-11e6-83cd-888b92625395.png)

**Comment by lamosty** [comment]
Do we want the disabled button look exactly like on the screenshot above? Because if yes, I would have to fiddle with some custom button in `PurchaseDetail` component as we don't have such one yet.

This is how it looks with the button which is currently used in `PurchaseDetail` but disabled:

![selection_055](https://cloud.githubusercontent.com/assets/4988512/16836829/f8427734-49bf-11e6-92b8-4e1ea3a4b623.jpg)

**Comment by gwwar** [comment]
I think @apeatling was thinking of styling similar to how your current plan button looks like on the /plans page.

**Comment by rickybanister** [comment]
The example showed by @gwwar is much clearer. With the disabled blue buttons it looks like the feature is broken rather than requiring no user input.

Can the akismet section of the Jetpack My Plan page get the same enabled treatment?

**Comment by rralian** [comment]
My two cents; I don't like showing a button at all. I think it's just sort of confusing. I look at this and wonder why the button is disabled and what it would do if I clicked it... and what do I need to do to enable it.

**Comment by rralian** [comment]
The screenshot example is particularly confusing to me. "No Ads Enabled"... what... I don't have any ads enabled? Is that a warning? Is something wrong? How do I enable ads? Do I click this to enable ads?

**Comment by apeatling** [comment]
Definitely the disabled button is confusing, it doesn't indicate that the feature is enabled and you do not need to do anything.

IMO this is the best way to communicate that you need to take no further action because:

1. It keeps the button consistency, all other cards I have to click a button to activate or set up a feature, that sets the expectation that I need to do the same thing for No Ads. Having a confirmation of this in the same style removes any doubt.
2. It brings over consistency with the Plans page, where we use this button in exactly the same fashion.

An alternative would be to update the wording to be more clear, but we know that people generally don't read paragraphs of text, so are more likely to miss it there.

**Comment by apeatling** [comment]
Alternatives for wording:

* No Ads active
* No Ads is active
* Feature Enabled
* Enabled
* Advertising Removed

**Comment by rickybanister** [comment]
I prefer options like 'Advertising Removed' and 'WordPress.com Advertising Removed' because they don't treat 'No Ads' like a proper noun. It's only a proper noun to us. 

We could also say something more plain like 'Your site is now ad-free'

**Comment by rralian** [comment]
Yes, 👍  for "Advertising Removed"... that's much more clear.

**Comment by lamosty** [comment]
So, should I just update the feature title wording from No Ads to Advertising Removed?

**Comment by rralian** [comment]
> It keeps the button consistency, all other cards I have to click a button to activate or set up a feature, this sets the expectation that I need to do the same thing for No Ads. Having a confirmation of this in the same style removes any doubt.

I don't think maintaining button consistency or displaying a button of any style communicates the message that you don't need further action to enable the feature. I think it does the opposite, even with different styling. Maybe some other non-interactive element like a badge or a star with "Automattically Enabled!" or something for automatically enabled features would help balance out the cards without raising the questions (to me at least) "why do I have a disabled button here? what does it do? how do I enable it?"

> So, should I just update the feature title wording from No Ads to Advertising Removed?

That'd be my vote... but I don't think it's Andy's vote. Maybe @rickybanister has an opinion. Or if Andy feels strongly or if you agree with him, feel free to overrule me. Just adding my two cents.

**Comment by rickybanister** [comment]
I don't have too much skin in this game. I just felt that 'no ads' is sort of jargony. 

`Advertising Removed` sounds fine

or `Ad-free` or `Advertising-free`

There's probably something to be said for making each feature have the same kind of 'part of speech'. 

As per the disabled button, I agree with the consensus that it might be confusing. It works without it.

**Comment by apeatling** [comment]
Okay, I am outvoted, so I am happy to concede. Let's change the wording though to include "Advertising removed".

> With your plan, all WordPress.com advertising has been removed from your site.

**Comment by lamosty** [comment]
Will do

**Comment by lamosty** [comment]
I also don't like the copy "Your plan removes advertising from your site so your visitors can enjoy your content without distractions!" Four "your".

It also doesn't match with Personal plan No Ads: "Personal plan automatically removes all Ads from your site. Now your visitors can enjoy your great content without distractions!".

**Comment by apeatling** [comment]
@lamosty I meant above that we should completely replace the wording.
