### ISSUE TITLE
Post Featured Image Block: some alignment options don't work properly

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#67623]
### Quick summary

On some FSE themes, some particular alignment options(`Wide width` and `None`) don't work for Post Featured Image Block. 

The themes with which I could replicate the issue:

- Russell
- Marl
- Appleton

### Steps to reproduce

1. Activate one of the themes I mentioned above in the Quick Summary.
2. Go to https://XXXXXX.wordpress.com/wp-admin/site-editor.php?postType=wp_template and open the Single template.
3. Click on the Post Featured Image Block and change its alignment to `Wide width` or `None` and save the change.
4. Preview a single post page.

### What you expected to happen

Post's featured image shows up with the max width for the alignment option selected.

![Screen Shot on 2022-09-11 at 15:31:55](https://user-images.githubusercontent.com/32432463/189515438-e9134fa2-f4d9-4953-95a2-08cb0710c922.png)

### What actually happened

Post's featured image shows up way wider and doesn't respect the alignment option set in Editor.

![Screen Shot on 2022-09-11 at 15:32:56](https://user-images.githubusercontent.com/32432463/189515477-89c5ef0e-8742-485a-82f8-5e22cef29eed.png)

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

I could reproduce the issue with Russell, Marl, and Appleton so far. It appears it's specific to some themes as I couldn't reproduce the issue on Twenty Twenty-two for example. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

We can use the following CSS code for users on Premium or higher but no workaround for Free/Personal plan users.

```
.wp-block-post-featured-image {
    max-width: XXXpx;
    margin: 0 auto;
}
```

**Comment by Joshgrygiel** [comment]
📌 SCRUBBING
- Tested on P2  ❌
- Tested on Simple ✅  
- Tested on AT ✅ 
- Tested on Self-hosted ✅  
- Replicable on Core - ❌

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to confirm on Russel, Marl and Appleton on only AT and Simple sites (Not replicable on Self Hosted) The "None" and "Wide Width" options do not affect the featured image at all, and the "Full Width" options removes the side margins of it to actually make the image full width:

https://user-images.githubusercontent.com/88345647/189968033-54044f52-8168-488e-9d20-e0d045b4cb8b.mp4

With that being said, it seems the "None" and "Wide Width" options have no affect on the featured image on those themes

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
Encountered this issue here: 36983948-hc

**Workaround**
I had the user try placing the "Post Featured Image" block inside of it's own Group Block, and that helped get the image down to a size that matched the content closely, while staying responsive.

They decided to remove the block altogether for their own design goals, so no follow up needed.

**Comment by annezazu** [comment]
Trying to replicate this a few years on so I activated the russell theme and opened the Single Post template. I found the post featured image block, by default, doesn't display certain alignment options unless or until you group it (this is intentional):

https://github.com/user-attachments/assets/93d60db2-630a-4dd2-91fd-d88633ad3fe6

This then worked correctly on the front end. As a result, I'm going to close this out as I both can't replicate and don't see additional reports.
