### ISSUE TITLE
Themes: Remove 'More' button from search bar

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#6773]
**Old**
![screen shot 2016-07-14 at 12 50 39](https://cloud.githubusercontent.com/assets/7767559/16838607/ecb2ee06-49c1-11e6-8ef7-1abcb4723b43.png)

**New**
![screen shot 2016-07-14 at 12 52 27](https://cloud.githubusercontent.com/assets/7767559/16838625/02ad548a-49c2-11e6-9df8-6657429a6b35.png)

**Comment by seear** [comment]
Not necessary, since we are going to build a new search bar from scratch in #7073

**Comment by lancewillett** [comment]
Can we do this now? Would be good to stop sending folks to older /themes view since it isn't as great of an experience.

This came up in a recent #dogfooding review from @beaulebens 

> "More" link within themes opened a new window, took forever to load, old Masterbar, all sorts of gross

Here's what it looked like for me going from https://wordpress.com/design/lancetest611.wordpress.com

<img width="1280" alt="screen shot 2016-10-05 at 13 21 32" src="https://cloud.githubusercontent.com/assets/66797/19130096/b3c39d4c-8afe-11e6-9167-2a3a9de1145b.png">

to 

https://wordpress.com/themes/filter/staff-picks/type/free/

<img width="1282" alt="screen shot 2016-10-05 at 13 21 40" src="https://cloud.githubusercontent.com/assets/66797/19130104/bc48bf7e-8afe-11e6-973c-6dfa207936ad.png">

**Comment by folletto** [comment]
> Can we do this now? Would be good to stop sending folks to older /themes view since it isn't as great of an experience.

Yes would be good! No we can't do this now.

We are very aware of it, but we can't remove it until we reach feature parity. We have a roadmap we are following, and it's going to happen in the [current milestone](https://github.com/Automattic/wp-calypso/milestone/103). Filtering is a highly requested feature, and very widely used by HEs.

**Comment by lancewillett** [comment]
It seems the roadmap is taking years. :/

Can't HEs bookmark the older URL and let end users see the streamlined, modern experience?

**Comment by folletto** [comment]
Yes, it's a huge piece of Calypso, so it's taking time unfortunately. And we had to work on other pieces and framework as well in the meantime, which made the roadmap even longer. I'm very aware it's uncommon for us to stick on long term visions and what that means. ;) 

We already let the users see the modern experience. It's right there. "More" is the only thing that leads to the old one, and we do that in a new tab too to avoid being blocked inside there. From the data we have, users filter away, it's not just HEs. It's a primary showcase feature, and the last one we have missing now before reaching feature parity. :)
