### ISSUE TITLE
[Bug]: Help Center: Sorry We Couldn't Connect You Error

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#67933]
### Quick summary

When starting a new chat I initially see a "Sorry we couldn't connect you with a Happiness Engineer. Please check back later." message. 

![chat message](https://user-images.githubusercontent.com/1900444/190711300-932c450d-8642-4fe9-950d-e605c57e381e.gif)

@arcangelini 

### Steps to reproduce

1. Open Help Center from a chat eligible account
2. Select Still Need Help
3. Select Live chat
4. Start a chat
5. See the we couldn't connect you message

### What you expected to happen

To be connected to a Happiness Engineer without an error message

### What actually happened

A connection error message is shown for a few seconds

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by alshakero** [comment]
This happens due to a discrepancy in the environment between the availability check and the actual chat. The availability check happens in either Calypso or the Editing Toolkit and finds available slots against Happychat staging. Then the chat lives in a separate app under apps/happychat and connects to prod where there are no slots. 

This becomes even more tricky in the editor because has no environment concept, so we ended up using the webpack build environment variable (prod or dev) of ETK to determine which env to use. But this proved bad, since even a12ns get ETK prod version.

The solution we're working on is to use `proxied` value to choose the env, proxied => dev, not => prod. This check is available in Calypso and the Editor and will align everything together, and this issue won't happen. 

It's worth noting that this issue only affects a12ns.
