### ISSUE TITLE
Marketplace: Implement compact card design

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#67979]
For design specs see https://github.com/Automattic/wp-calypso/issues/67987

We need to implement a compact version of the plugin cards, to reduce the screen real estate plugin cards take up, and differentiate Collections.

Acceptance criteria:
- [ ] The card fits the specs outlined in https://github.com/Automattic/wp-calypso/issues/67987

**Comment by lsl** [comment]
Few ways to do this, suspect we should implement a `compact` prop that sets an `is-compact` css class on the `PluginsBrowserList` component.

We can use that prop in a follow up issue to create a new version of SingleListView for collections. I say new because SingleListView is coupled to categories and it's not clear if collections are categories. (I'm leaning towards "not categories" so far - and we can always refactor them back together later if it makes sense)

**Comment by lsl** [comment]
Follow up issue here https://github.com/Automattic/wp-calypso/issues/68800

Thinking more, we could possibly just hack all this on top of categories themselves as there is a lot of cross over. e.g. we could add a "plugins" property to the response from `useCategories` where we hardcode a list of products to swap out.

I'm thinking while that might work, it will probably create some extra branching around the category plugin fetching logic. Since it's pretty trivial to zip these two concepts up and remove the extra components later, I think it makes sense to explore this collections concept in isolation first.

**Comment by allilevine** [comment]
> I'm thinking while that might work, it will probably create some extra branching around the category plugin fetching logic. Since it's pretty trivial to zip these two concepts up and remove the extra components later, I think it makes sense to explore this collections concept in isolation first.

+1. We haven't proved the concept yet, so ideally we would keep this first pass as simple as possible.

**Comment by lsl** [comment]
The plugins browser list already implements a compact view but it will need updating to list 3 across in wide enough breakpoints.

@vinimotaa do you want to provide breakpoints or should we just figure something out?

Existing compact view looks like this:

![Screenshot 2022-10-11 at 16-45-39 Plugins ‹ Bussiness Simple — WordPress com](https://user-images.githubusercontent.com/811776/195006725-8cfb03e1-d174-4810-b40c-9c5eea4cc410.png)

Triggered by passing the prop: `extended={ false }`

**Comment by lsl** [comment]
This will get closed by https://github.com/Automattic/wp-calypso/pull/68884 (noticed the smaller font and used a 33% - 10px width, seems to be ok most breakpoints)

![Screenshot 2022-10-11 at 17-29-04 Plugins ‹ Bussiness Simple — WordPress com](https://user-images.githubusercontent.com/811776/195012954-85863965-25e5-4f56-8c8e-f60d1440fe05.png)

![Screenshot 2022-10-11 at 17-28-19 Plugins ‹ Bussiness Simple — WordPress com](https://user-images.githubusercontent.com/811776/195012832-cc47d802-3168-40f4-89ee-e356d162ca40.png)

**Comment by vinimotaa** [comment]
Hi @lsl, thanks for this, is this ready for a design review? Product cards seem a bit off from the design specs provided. If the team is still working on it, it's ok, otherwise, we could double-check check paddings, font sizes, thumbnail sizes, etc. Happy to help

**Comment by lsl** [comment]
Design review early and often is always welcome!

> Product cards seem a bit off from the design specs provided.

Sorry, missed these, I was focusing on getting something to unblock these other todo's https://github.com/Automattic/wp-calypso/issues/67987#issuecomment-1274141653 and re-using the existing compact view to get something in front of users right away felt like a good call.

We could put it all behind a feature flag and leave this issue open to iterate behind the scenes but I think Dusty already fixed these issues in the PR.

I'll add a note in the list of todo's to recheck the spec's before we close out the main issue https://github.com/Automattic/wp-calypso/issues/67987 too just to be sure.
