### ISSUE TITLE
Task: Move Help Center close to the top bar

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#68016]
### Details

Change the default Help Center position as close as possible to the top bar, with a margin of 10px tops.

**Comment by renancarvalho** [comment]
I investigated this one a bit and noticed that it is not aligned because the top is calculated using the header height style variable from `@wordpress/base-styles `which is 60px (Gutenberg height) but calypso has 30px height.

A simple fix would be like add the correct top based on where the Help Center is ( Calypso or Gutenberg ).  With that I have two questions.
1 - Is there any other place where HC lives that is not calypso or Gutenberg? Maybe another header with different size ?
2 - What is the best way to know if the context is Gutenberg ? I noticed a window object window.wpcomGutenberg but sounds 'hacky' to me.


Have pushed some basic experiment [here](https://github.com/Automattic/wp-calypso/tree/update/help-center-position)
