### ISSUE TITLE
Site Selector: Apply sort order before searching the list

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#68043]
From https://github.com/Automattic/wp-calypso/pull/68042

In order to ensure the search relevancy algorithm is applied to the list of results, we should make sure the sort order is applied _before_ searching the list.

**Done is:**
* Sort order is applied before searching the list.

**Comment by zaguiini** [comment]
### Problem description

The big requirement here is that we want to make the logic as generic as possible (by putting code in `packages/components/src/sites-table`) and as straightforward to use as possible by calling a single hook in different places, an abstraction. This would allow us to apply the same instructions to the sites list, wherever it's called, be it the sites page, the site switcher (in Calypso or Jetpack Cloud) or really anywhere you'd like to have the same sites list.

The main problem with that is as the logic grows in size, we're introducing more and more hooks that serve as pipes for data processing. And to replicate the same behavior in all places, one would need to copy and paste the hook calls in the exact same order, making code redundant and possibly not 1:1 as the developer might forget to include all hooks.

This is cool and all, but the coupling of functionality isn't that flexible -- the site switcher doesn't group by status, and there's no way to opt out right now.

### Possible solution

We might expose all "pipes", such as:

- `useSitesListGrouping`;
- `useSitesListSorting`;
- `useSitesListFiltering`.

As individual hooks, just as it is right now, allowing the pipes to be used as needed in certain scenarios. Then, expose a component called `<SitesList>` that would accept a `sites` prop, which is essentially the raw, original list of sites, retrieved from the back-end.

The reason for a component aggregator instead of a hook is that it's easier to disable or enable functionalities as needed. You can't conditionally call hooks, but you can render or don't render certain components. The idea is to expose a component for each hook (sort of like a higher-order component), then create the `SitesList` component which would act as an aggregator for those data pipes. We would accept props that would serve as options for the pipes, along with allowing us to disable the pipes by passing `false` as the prop value.

So, one example of usage would be:

```ts
const SiteSwitcher = ( { sites } ) => {
	return (
		<SitesList
			sites={ sites }
			status="all"
			filter={ false } // useSitesListFiltering won't run for the sites list
			sorting={ { sortKey: 'alphabetically', sortOrder: 'asc' } } // but we do want to apply sorting
		>
			{ ( { processedSites, statuses } ) => {
				return processedSites.map( ( site ) => <Site site={ site } /> );
			} }
		</SitesList>
	);
};
```

Thoughts?

**Comment by danielbachhuber** [comment]
@zaguiini Dig it! Seems like a worthwhile abstraction to me.

**Comment by danielbachhuber** [comment]
Still need to work through this question: https://github.com/Automattic/wp-calypso/pull/68175#discussion_r978981749

**Comment by danielbachhuber** [comment]
@zaguiini There's a little bit of scope creep going on, but we'll also want to remove the concept of hidden sites from this abstraction once #67581 and #68173 are shipped.

**Comment by zaguiini** [comment]
@danielbachhuber but isn't the sliced sites list optional? Are we sure we want to remove hidden sites even from pages like http://wordpress.com/marketing/tools?

**Comment by danielbachhuber** [comment]
@zaguiini Good point. I don't have a strong opinion.

In the interest of limiting scope, let's keep hidden sites applied to `/marketing/tools` and other site lists outside of the Site Switcher. As such, we can keep the abstraction in place.

**Comment by zaguiini** [comment]
Yeah, and the only thing we need to do in the site switcher is to specify `showHidden` as `true`, this way the hidden sites will show up. I'll come up with a PR soon.
