### ISSUE TITLE
Audio block: download button not available on iOS devices

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#68098]
### Steps to reproduce

1. Start at https://wordpress.com/support/wordpress-editor/blocks/audio-block/
2. Try to download the audio file using the three dotted button on the player

### What you expected to happen

To see the **download** option 

### What actually happened

I only got the playback speed options.

### Context

5572341-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

iOS, Chrome and Safari

Android works ok

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Replicated
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate this behavior, but from what I understand the Audio block uses the HTML <audio> tag and implementation may vary depending on the browser. 
- Since this happens in the Audio block on self-hosted sites too, I think the Gutenberg repo would be the best place for this issue, but I didn't copy the issue there because after searching in that repo I suspect this may be specific to iOS restrictions and not an issue with the Audio block itself. Other related issues in the Gutenberg repo were closed for this reason: https://github.com/WordPress/gutenberg/issues/25121#issuecomment-689530784

📌 ACTIONS
- Closed since this seems to be expected behavior.

📌 Message to Author
- @Robertght Since this was a user report it might be helpful to follow up with them to set expectations that this seems to be determined by the way iOS works. Or feel free to open this issue in the Guteberg repo if you think it might be helpful to report there. Thanks!
