### ISSUE TITLE
Domain Search: TLD error messages

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#6810]
#### Steps to reproduce
1. Starting at URL: WordPress.com/domains
2. Search for a domain that is not registered and ends in a TLD we don't offer
3. Error reads as follows:
<img width="746" alt="screen shot 2016-07-14 at 4 17 59 pm" src="https://cloud.githubusercontent.com/assets/8921630/16858823/9e8d5442-49de-11e6-94a5-c946ec4f7719.png">
4. While this is true, we should specify that this isn't a TLD we offer.

A message like 

> We currently don't offer domains ending in .nl, but you can register it elsewhere and map it here

With a link to buy mapping, plus the list of alternatives below.

I know this might be a pain to maintain, but just saying you can't register it here is pretty general and not too helpful.

**Comment by klimeryk** [comment]
Just to clarify - that's the message shown when the domain is _not registered_.
When it's registered, we show the usual "X is taken. You can map it bla bla bla" message - so in that case, the user is not bothered with what TLDs we support or not.

As for the error message: while it's clear _to me_, I certainly see your point, it could use some improvements. Starting with the severity of the notice - error is too much. The message you propose, `We currently don't offer domains ending in .nl, but you can register it elsewhere and map it here` sounds good to me, but maybe it's good to run it by @ranh 🙇

**Comment by ranh** [comment]
How about something like:

> To use a domain ending with .nl to your site, you can register it elsewhere and then add it here. Learn more.

This should not be considered an error, we should never use those red notices inside the domain search like this. It would be better to use the warning or info styles.

I'm a big fan of having support pages that are tailor-fit for a specific notice. That's also a pain to maintain, but it makes for a much better experience when the context-switch involved with going from Calypso to the support site is minimized. I don't have time to create a dedicated fan page for this right now, but wanted to throw this out there in the hope someone else will be inspired to do it. 

If I did have time, I would use a title like "add a domain with a local or custom extension", include a list of the extensions we do support, and follow with some general pointers about registering a domain outside of WordPress.com and adding it here.

Otherwise, a link to the current mapping page might be good enough.
