### ISSUE TITLE
Marketplace: Find a way to create Upgrade Path for the SaaS product subscription

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#68149]
## Details 

As part of SaaS product licensing, we need to allow vendors to create an Upgrade/Downgrade path for the users who already have active subscriptions. We also need to look into adjusting prices according to current usage and credit or charge upon downgrade or upgrade.

**Comment by epeicher** [comment]
**Backlog grooming:**: As this is a research task, it will be timeboxed to 2

**Comment by JulianBustamante** [comment]
PoC Diff created D91555-code

**Comment by cpapazoglou** [comment]
The upgrade path can be triggered in two ways:
- from the UI, the customer selects an upgraded plan
  - the flow is more or less the same
- from the vendor, the vendor wants the customer to buy an upgraded plan due to reaching their limits
  - when the vendor creates a billing intent on their own, we should send an email to the customer and probably a web notification. We might need to think more about it, in case it's better for the vendor to send the email themselves. 

Discussed email notifications with Mailpoet in p1676409006741099-slack-C04PDM42HE0, and they will be sending the notification. So, at least for the time being there isn't anything for us to do here.

**Comment by cpapazoglou** [comment]
Related to cancellations or downgrades:

We need to hook into the marketplace subscription cancellation, check if the site is eligible for a lower plan ( it could be free for all sites and premium for ecommerce sites ). If there is eligibility, keep the product installed, downgrade the subscription, send an event webhook to the vendor.

Scenario 1:
- A business site buys Mailpoet premium
- They cancel the premium plan
- They should still have the free plan and the plugin installed

Scenario 2:
- A user buys ecommerce plan where Mailpoet premium is bundled with
- Site reaches the subscribers limits and upgrades to Mailpoet ultra plan
- They cancel the ultra plan
- They should still have the premium plan and the plugin installed

Scenario 3:
- A user buys ecommerce plan where Mailpoet premium is bundled with
- User cancels the ecommerce plan
- The Mailpoet premium plan should get cancelled, the plugin should be removed.

**Comment by cpapazoglou** [comment]
We also need to create ( or update ) the webhooks related to an upgrade / downgrade.

**Comment by JulianBustamante** [comment]
A new approach was implemented. This approach overrides the `Store_Products` method `apply_discounts` instead of creating an Upsell class initialized in the `Shopping_Cart ` apply_discounts on SaaS products to allow applying discounts when upgrading SaaS subscriptions at D105222-code

**Comment by gavande1** [comment]
deployed r263799-wpcom
