### ISSUE TITLE
Task: NL - Jetpack logo should be stuck to the bottom (not floating)

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#68213]
### Details

pbAok1-3fI-p2

**Comment by autumnfjeld** [comment]
@alshakero  @renancarvalho @escapemanuele  It would be nice if you all could include screenshots in your issues/PR. SO that is is super easy to identify what is being worked on.    I mention this because I'm tracking down this break change that affected all users going through onboarding.  I want to see what you were fixing..... what UI you were fixing related to the Jetpack logo.

One problem seems to be a bigger check wasn't done with this PR #68290   to see if your changes affected other onboarding screens. 

![image](https://user-images.githubusercontent.com/5665959/192942649-325a0fe5-0654-4108-ba24-75fce023d638.png)


p1664411235927349-slack-CRWCHQGUB

Thank you. 😃
