### ISSUE TITLE
Theme Bundling: User should be redirected into Woo onboarding from selecting a Woo theme

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#68306]
Per comments at pdtkmj-xt-p2#comment-960 and pdtkmj-xt-p2#comment-987 - if a user has selected a Woo-supporting theme during onboarding, we should expect to redirect them into the `storeAddress` onboarding step for Woo onboarding.

**Comment by markbiek** [comment]
Documenting the two main scenarios people seem to be running into:

## Test Scenario 1 - Upgrade from theme showcase

- New site, new domain, free site
- Skip to dashboard
- Go to TA theme page and click "Upgrade to activate"
- Checkout Business plan (I selected monthly)
- Ended up on "Thank you page" instead of `storeAddress`

## Test Scenario 2 - Unlock theme from `designSetup`

- New site, new domain, free site
- Go through sell intent
- Pick TA from `designSetup` and click "Unlock theme"
- End up with Premium plan in the cart

**Comment by mreishus** [comment]
Scenario 1: Fixed in #68538
Scenario 2: Possibly fixed in #68361 and/or #67992

**Comment by markbiek** [comment]
I think this can be closed. It seems pretty out of date for the current landscape of plans and stepper flows.
