### ISSUE TITLE
Import subscribers: Email notification improvement

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#68390]
CFT Feedback:

"Our test CSV file contains a duplicate address, and the notification email we get says it imported 10 out of 11 subscribers. We expect to be told that, but it does not specify why."

"My .csv file contained one duplicate contact, the notification email (“ Subscriber import completed”) tells me 10 out of 11 were imported, but doesn’t explain why a contact wasn’t added successfully. There is also no notice of this in the interface. It would be good to be told why an address isn’t imported, even with generic/boilerplate language."

cc @vishnugopal @jeroenpf

**Comment by vishnugopal** [comment]
Should we populate an errors output as well along with the API response? How should we communicate this?

Let this be a known issue for now, we can discuss this with @saygunnyc and improve later.

**Comment by jeroenpf** [comment]
The only place we can communicate this is in the email because we run the import async. 

There can be other reasons that an email address was skipped and we should think about how we communicate this. Keep in mind that for large email lists there  could potentially be many skipped emails. 

Perhaps we could also let the user know in the UI that an email will be sent when the import has completed?

**Comment by jeroenpf** [comment]
Also see: https://github.com/Automattic/dotcom-forge/issues/1011

**Comment by simison** [comment]
Improved copies in D118229-code but there's still space for more improvements. The more help we can give them, the better.

**Comment by bogiii** [comment]
Closing ticket in favor of https://github.com/Automattic/wp-calypso/issues/88855

cc @zaerl
