### ISSUE TITLE
Media: Updating gallery caption doesn't set post as dirty

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#6850]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/post
2. Select a site
3. Insert an image gallery
4. Save the post
5. Click the image gallery in post content to select it
6. Switch to Edit tab in gallery options
7. Add or update a caption
8. Click Update to save revisions

#### What I expected

Post should become "dirty". In other words, the "Save" button should be shown to reflect that there are unsaved changes.

#### What happened instead

The post is not marked as unsaved.

**Comment by lancewillett** [comment]
I disagree with this one, in general — image captions in galleries aren't really post content, they are tied to the image itself in the site's Media Library.

For a smoother UX, though, it does seem like you're editing the post and would need to save the changes. The same thing happens in wp-admin when you edit the Featured Image: it saves automatically, and you don't need to hit "Update" for the entire post — but it feels like you are missing a step.

One suggestion to improve the UX could be to pop up a notification when the gallery is saved saying "Gallery changes saved. Post content not changed." or something so that authors know they don't need to see their post as having unsaved changes.

I'm going to close but dropping these thoughts in case this comes up in the future.
