### ISSUE TITLE
Alert me when I paste HTML markup into the Visual Editor

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/wp-calypso#6864]
All too often I will copy simple markup or content from an old post with the intention of reusing it. Most times I write in the Visual editor and when I paste the markup everything "feels" right. It's not until I publish the post that I remember that the Visual editor is displaying the HTML but has in fact escaped it all. 

It'd be nice if I got a warning reminding me that I'm in fact pasting the HTML into the Visual side of the editor.  To take it a step further it might be nice if when I paste it I just get an option to "convert" it back or something like that.

**Comment by folletto** [comment]
I'd try to avoid "warning" approaches, and instead turn this in providing a choice along the potential user intent.

When a user paste code, I can imagine three intents:

1. Code pasted as `pre`
2. Code pasted inside the HTML tab, so proper content
3. Code pasted by error, meant pasting the clean text

This means that if we detect markup/code (pending the detector for this) we could show a dialog with some options to advance:

> **It seems you're pasting some code. Would you like to...**
> [ Paste as is ] [ Paste as code ] [ Paste as formatted text ]

* "Paste as is" simply converts the code to entities `<` to `&lt;` so the result is just text
* "Paste as code" paste the code in without changes, wrapping it in `pre`
* "Paste as formatted text" is identical to paste to HTML tab and switching back to the visual editor, thus creating a nice experience without the switch back / forth.

This could also be done inline (like our [links proposal](https://github.com/Automattic/wp-calypso/issues/3736)) instead of a dialog.

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Closing because this will be addressed in the [Gutenberg editor](https://github.com/WordPress/gutenberg). I just tested pasting HTML content into a block using Gutenberg 1.9.1, and the content appears normally in visual mode and I can switch to HTML mode after that to see the code.
