### ISSUE TITLE
Empty columns block on a page render 32018 pages when printing

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#68794]
### Quick summary

If you have an empty Columns block on page and try to print it, you won't be able to and you'll see 32018 for printing which is incorrect.

### Steps to reproduce

1. Add an empty Columns block on a page
2. Publish the page
3. Check the frontend and try to print it

### What you expected to happen

To see the correct number of pages.

### What actually happened

![lufkun.png](https://user-images.githubusercontent.com/6737345/194692932-e9727087-34bd-43e1-9411-61dab4bbba0c.png)

### Context

5612379-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Theme-specific issue?

No

### Browser, operating system and other notes

Chrome

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Remove the empty columns block.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Could Not Replicate**
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Test environments: 
     - Simple Site, Themes: Twenty Nineteen, Twenty Sixteen (theme active in user case)
     - AT Site, Theme: Russel (FSE)
     - Tried printing in FireFox 105 and Chrome 106 on MacOS 12.5.1

*Example: Simple Site*
![Markup on 2022-10-11 at 10:48:51](https://user-images.githubusercontent.com/27249804/195164110-dda02344-82ee-47f6-a76d-05a313c1726b.png)

![Markup on 2022-10-11 at 10:46:13](https://user-images.githubusercontent.com/27249804/195164128-2ac8ebc6-b46f-4b98-86a4-0b321951ec50.png)

*Example: AT Site*
![Markup on 2022-10-11 at 10:50:34](https://user-images.githubusercontent.com/27249804/195164182-170de5c2-df07-4c13-9c64-3c2db1a4a447.png)

📌 ACTIONS
- Await author feedback

📌 Message to Author
- Hey @Robertght ! Thanks for the report. Were you able to replicate this outside the user's environment? I wasn't able to replicate this in Simple or AT with a few different themes, including the original user's theme. Can you check if there are any other steps needed in order to reproduce this issue?

**Comment by vajrasar** [comment]
@Robertght can you please re-check if there are any additional steps to replicate the issue?

**Comment by vajrasar** [comment]
Closing this, if the issue shows up again please feel free to reopen it.

**Comment by Robertght** [comment]
Hey! Sorry for missing this. I can't replicate the issue anymore.
