### ISSUE TITLE
Alignment issue for form inside cover block

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#68796]
### Quick summary

Place a form inside a cover block on them 2020 and it is skewed to the right of the screen like this 
![Uploading Markup on 2022-10-09 at 13:01:37.png…]()

### Steps to reproduce

1. Test site : Personal plan. Theme 2020.
1. Add a cover block. 
2. Add a form inside.
3. The form is over to the right
4. Change theme to 2022 and the form moves to the left of the block where you would expect it. 
5. This also occurs when moving form outside of the cover block

### What you expected to happen

The editor to be reflected on the public page.
On the 2022 theme it looks like this - 
![Markup on 2022-10-09 at 13:04:11](https://user-images.githubusercontent.com/13706336/194734173-5c0c5ccf-2a8c-4d08-a75a-8fd02d702dab.png)

### What actually happened

Please see earlier screenshot.

### Context

5615577-zd

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

2020

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Not able to replicate the issue following the steps provided.
- Simple Site, using Twenty Twenty Theme, placing a form block inside a cover block
- Form block rendered consistently between editor and live site, and aligned as expected.

*Example - Editor View*

![Markup on 2022-10-11 at 11:20:15](https://user-images.githubusercontent.com/27249804/195169649-2208d1cb-f0e2-42f9-be93-10869d272ef4.png)

*Example - Live Site*
![Markup on 2022-10-11 at 11:20:33](https://user-images.githubusercontent.com/27249804/195169678-495ba255-1560-4072-a473-dd8ed55c99c9.png)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @rickmgithub could you review your steps to replicate to see if anything is missing in order to reproduce this issue?
- Also, please note your attached screenshot/recording wasn't able to upload, so that is not visible.
- Finally, make sure not to include any user-specific information in your screenshots or details. Please edit the report above to use screenshots from a test site or with redacted information instead. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.
