### ISSUE TITLE
Headstart on Atomic: Implement product data and taxonomy in application script

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#68847]
When a user initiates headstart using an atomic theme, we need to be able to apply product data and taxonomy information after WooCommerce is installed.

Current planned strategy is to store this information as site options and use a hook to trigger creation of this taxonomy info after WooCommerce is installed.

**Comment by mreishus** [comment]
### Documentation and References

* [WC_Product API Reference](https://woocommerce.github.io/code-reference/classes/WC-Product.html)

### Generate Annotation 

For each post that is a type=product, find the associated WC product object, then call special functions like `->get_price()` and `->get_sku()` on it:

```diff
diff --git a/wpcom-headstart/class-wpcomsh-headstart-generate-annotation.php b/wpcom-headstart/class-wpcomsh-headstart-generate-annotation.php
index af3cc48..14e2f40 100644
--- a/wpcom-headstart/class-wpcomsh-headstart-generate-annotation.php
+++ b/wpcom-headstart/class-wpcomsh-headstart-generate-annotation.php
@@ -10,9 +10,37 @@ class WPCOMSH_Headstart_Annotation_Generator {
                $excluded_post_types = [];
 
                $anno = Headstart_Annotation_Generator_Simple::generate_theme_annotation( $type, $options, $widgets, $template_for_post_id, $posts_required, $excluded_post_types );
+
+               $anno['woocommerce_product_data'] = self::build_woocommerce_product_data();
+
                return $anno;
        }
 
+       private static function build_woocommerce_product_data() {
+               $args = array(
+                       'nopaging'    => true,
+                       'post_status' => 'publish',
+                       'post_type'   => array( 'product' ),
+               );
+               $posts = get_posts( $args );
+
+               $return_data = array( );
+
+               foreach ( $posts as $post ) {
+                       $product = wc_get_product( $post );
+                       if ( empty( $product ) || is_wp_error( $product ) ) {
+                               continue;
+                       }
+                       $this_product_data = array(
+                               'price' => $product->get_price(),
+                               'sku' => $product->get_sku(),
+                       );
+                       $return_data[ $post->ID ] = $this_product_data;
+               }
+
+               return $return_data;
+       }
+
        private static function get_site_options() {
                $site_options = array();
                $site_options['show_on_front'] = get_option( 'show_on_front' );
```

This is data that we can only generate on Atomic sites, since Simple sites don't run Woo.

As far as I can tell, we can't do generalized product data getting and setting, like `$product_data = $product->get_data()`, then later `$product->set_data( $product_data )`. We have to rely on specialized function pairs like `->get_price()` and `->set_price()`, or `->get_sku()` and `->set_sku()`. Meaning that we'll have to explicitly build support for each product data field we want on both sides of this operation.  This also means we'll probably want to only support a minimal set of fields appropriate for our demos.

Edit: Dale pointed out a way to get generalized data, install code snippets plugin, and use this:

```php
add_filter( 'admin_footer_text', function ( $text ) {
	echo "<div><pre>";
	
	$headstart_product_meta = array();

	$woo_product_data_store = new WC_Product_Data_Store_CPT();
	$woo_product_meta_keys  = $woo_product_data_store->get_internal_meta_keys();

	$published_product_filter = array(
		'nopaging'    => true,
		'post_status' => 'publish',
		'post_type'   => array( 'product' ),
	);
	$product_posts            = get_posts( $published_product_filter );

	foreach ( $product_posts as $product_post ) {
		$post_meta = get_post_meta( $product_post->ID );
		if ( ! empty( $post_meta ) && is_array( $post_meta ) ) {
			// Extract all specified Woo meta keys
			// We may want to avoid any empty keys, in which case we could use ARRAY_FILTER_USE_BOTH
			$headstart_product_meta[ $product_post->ID ] = array_filter(
				$post_meta,
				function ( $meta_key ) use ( $woo_product_meta_keys ) {
					return in_array( $meta_key, $woo_product_meta_keys, true );
				},
				ARRAY_FILTER_USE_KEY
			);
		}
	}

	$data = $headstart_product_meta;
	echo wp_json_encode( $data );
	echo "</pre></div>";
	return $text;
});
```

### Example Field added to Annotation

#### Generic Example
```
    "woocommerce_product_data": {
        "119": {
            "price": "9.99",
            "sku": "ABC1234"
        },
        "120": {
            "price": "",
            "sku": ""
        },
    }
```
119 and 120 are WordPress post_ids, not WooCommerce product ids. Above is an example of one product with data and one without.

#### Alt Method Example
```
  "148": {
    "total_sales": [
      "0"
    ],
    "_tax_status": [
      "taxable"
    ],
    "_tax_class": [
      ""
    ],
    "_manage_stock": [
      "no"
    ],
    "_backorders": [
      "no"
    ],
    "_sold_individually": [
      "no"
    ],
    "_virtual": [
      "no"
    ],
    "_downloadable": [
      "no"
    ],
    "_download_limit": [
      "0"
    ],
    "_download_expiry": [
      "0"
    ],
    "_stock": [
      null
    ],
    "_stock_status": [
      "instock"
    ],
    "_wc_average_rating": [
      "0"
    ],
    "_wc_review_count": [
      "0"
    ],
    "_product_version": [
      "6.8.2"
    ],
    "_wp_old_slug": [
      "import-placeholder-for-127"
    ],
    "_regular_price": [
      "20"
    ],
    "_thumbnail_id": [
      "154"
    ],
    "_price": [
      "20"
    ],
    "_edit_lock": [
      "1662942625:67978261"
    ],
    "_edit_last": [
      "67978261"
    ]
  },

```

#### Modified Thriving Artist / Tsubaki Annotations

* D89577-code (Price and SKU only)
* D89687-code (Trying to get all woocommerce data)

### Post IDs as Key

Q: Is keying off WP POST ID appropriate? Can Headstart guarantee that these will be set the same or are they ignored?

A: Headstart does not guarantee that the new posts will have the same IDs as before, but mapping data is available at headstart application runtime inside the `$new_post_ids` variable inside `lib/headstart/class-headstart-setters.php` : `copy_all_things()`.

### Applying Annotation to Simple site (Storing data in simple site option at headstart application time)

D89578-code

Looks to be working. Data is stored in the `headstart_woocommerce_product_data` option.

### Does the site option get transferred successfully to Atomic? :x: 

~~Dumb question I guess~~, but I was just assuming this would happen. Would be good to test.

#### :( ===> I am not seeing the option set after transferring to atomic. <===

I'm seeing a few options here:
* Modify `get_wordpress_option_overrides()` on the wpcom backend such that the data is sent over.
  * It's so rare that options are moved on atomic transfer it makes me think this is something we don't want to do.
* Change wpcomsh to read the data from, say, `~/htdocs/wp-content/themes/thriving-artist/inc/headstart/en.json` instead of the option in the post-install hook. See 1106-gh-Automattic/wpcomsh 
* After woocommerce is installed, make an API request which returns woocommerce data for the current theme.

Barry recommends against using options here: pMz3w-ahn-p2#comment-72940 

### WooCommerce install hook (Moving data from site option to wc products)

TBD

**Comment by daledupreez** [comment]
Might it make sense to do this in a more brute force way that tries to copy any relevant Woo post meta values?

The specific meta keys should be available using code like the following:
```php
$headstart_product_meta = array();

$woo_product_data_store = new WC_Product_Data_Store_CPT();
$woo_product_meta_keys = $product_data_store->get_internal_meta_keys();

$published_product_filter = array(
  'nopaging'    => true,
  'post_status' => 'publish',
  'post_type'   => array( 'product' ),
);
$product_posts = get_posts( $published_product_filter );

foreach ( $product_posts as $product_post ) {
  $post_meta = get_post_meta( $product_post->ID );
  if ( ! empty( $post_meta ) && is_array( $post_meta ) ) {
    // Extract all specified Woo meta keys
    // We may want to avoid any empty keys, in which case we could use ARRAY_FILTER_USE_BOTH
    $headstart_product_meta[ $product_post->ID ] = array_filter(
      $post_meta,
      function ( $meta_key ) use ( $woo_product_meta_keys ) {
        return in_array( $meta_key, $woo_product_meta_keys, true ); 
      },
      ARRAY_FILTER_USE_KEY
    );
  }
}
```

The application side could then just run `add_post_meta()` or `update_post_meta()` for each of the specified meta values.

**Comment by mreishus** [comment]
Interesting. I was looking for a generalized way to do this, but couldn't find one. This looks like it might work. One thing I'm seeing is that I have to remove one level of arrays from the values on application time, that is: 
```php
		foreach ( $woo_data as $k => $v ) {
			update_post_meta( $product_post->ID, $k, $v[0] );
		}

```

**Comment by mreishus** [comment]
I'm starting to think the option plan will not work. When you create a new atomic site, options are not copied from the simple site. Anything I write to options before the transfer is just lost.

There's a way to override this and specify that an option should be copied, but the last time we added to this list, there was pushback from Barry. I don't think this is really a supported avenue. I'm looking at making wpcomsh look through the annotation locally here: 1106-gh-Automattic/wpcomsh

I'm also editing the large comment above and keeping it up to date

**Comment by daledupreez** [comment]
I am thinking we can keep things even simpler, at least for the "simple" data stored in `product_meta`.

Why don't we simply add a deeper set of key-value pairs below `hs_post_meta` that we apply for _any_ Headstart use case? This should occur well before we turn Atomic, and those values should be handled correctly during the transfer to Atomic. The only work is to then add the correct fields during generation of the annotation.

I've started exploring this in D89726-code (which I haven't had a chance to test _at all_ yet!), but I think that would be a clean solution for the product data. ( + D89755-code )

That doesn't solve for taxonomy data, but I think having a simple, generic solution for `post_meta` in the main Headstart code will be more robust.

**Comment by mreishus** [comment]
I tried the above patches out and they look to be a great solution for product data :+1:

**Comment by mreishus** [comment]
Product data is now working with D89726-code + D89755-code.

**Comment by daledupreez** [comment]
As a quick follow-up note, I added the `product_meta` fields for WooCommerce to the Tsubaki annotations in D89811-code.

**Comment by mreishus** [comment]
I have Terms ~~partially~~ working with this:

### Generator
```php
<?php
// mreishus 2022-10-19
// see: https://github.com/Automattic/wp-calypso/issues/68847
// The generated annotations contain default woo terms like "grouped",
// and dynamic meta values like "product_count_product_tag".
// Haven't yet decided how to handle these.

function build_custom_terms() {
	$taxons = get_taxonomies();
	$taxons = array_diff( $taxons, get_default_taxonomies() );

	$custom_terms = array();
	foreach ( $taxons as $taxon ) {
		$terms = get_terms( $taxon, array( 'hide_empty' => false ) );
		if ( ! empty( $terms ) ) {
			$custom_terms[$taxon] = $terms;
		}
	}
	return $custom_terms;
}

function get_default_taxonomies() {
	return array(
		'category',
		'post_tag',
		'nav_menu',
		'link_category',
		'post_format',
		'wp_theme',
		'wp_template_part_area',
		'mentions',
	);
}

function get_custom_term_ids( $custom_terms_by_taxonomy ) {
	$all_ids = array();
	foreach ( $custom_terms_by_taxonomy as $taxon => $terms ) {
		$these_ids = array_map( function( $v ) {
			return $v->term_id;
		}, $terms );
		$all_ids = array_merge( $all_ids, $these_ids );
	}
	return $all_ids;
}

function build_custom_term_meta( $custom_term_ids ) {
	$result = array();
	foreach ( $custom_term_ids as $id ) {
		$meta = get_term_meta( $id );
		if ( ! empty( $meta ) ) {
			$result[ $id ] = $meta;
		}
	}
	return $result;
}

function build_product_term_assignments( ) {
	$assignments = array();

	$published_product_filter = array(
	  'nopaging'    => true,
	  'post_status' => 'publish',
	  'post_type'   => array( 'product' ),
	);
	$product_posts = get_posts( $published_product_filter );
	foreach ( $product_posts as $post ) {
		$assignments[ $post->ID ] = array();

		$taxes = get_object_taxonomies( $post->post_type );
		foreach ( $taxes as $tax ) {
			$names = wp_get_object_terms( $post->ID, $tax, array( 'fields' => 'names' ) );
			if ( ! empty( $names ) ) {
				$assignments[$post->ID][$tax] = $names;
			}
		}

		if ( empty( $assignments[ $post->ID ] ) ) {
			unset( $assignments[ $post->ID ] );
		}
	}
	return $assignments;
}


add_filter( 'admin_footer_text', function ( $text ) {
	echo "<div><pre>";

	$data = array();
	$data['custom_terms_by_taxonomy'] = build_custom_terms();
	$custom_term_ids = get_custom_term_ids( $data['custom_terms_by_taxonomy'] );
	$data['custom_term_meta'] = build_custom_term_meta( $custom_term_ids );
	$data['custom_term_assignments'] = build_product_term_assignments();
	
	echo wp_json_encode( $data );
	echo "</pre></div>";
	return $text;
});
```

### Tsubaki update

D89989-code - Committed.

### Applier

1110-gh-Automattic/wpcomsh

### Status

Inserting the terms works.

Assigning the terms works!

However, it doesn't automatically trigger when woocommerce is installed. It only runs via CLI command.

**Comment by mreishus** [comment]
### Full workflow testing not currently possible

The current dev/test path requires logging into your atomic site and running manual commands. We need wpcomsh code to be on the site at the time woocommerce is installed, which as far as I know, there's no way to do.

I think we will have to ship the code to wpcomsh prod in order to try out the entire workflow.

### Commited/Deployed Tsubaki Annotation update

D89989-code Is now committed; it has no affect on simple sites. The extra data will just be ignored.

### Dynamic values in Annotation

Like `product_count_product_cat` and `product_count_product_tag`. These concern me. It seems good to put them on new sites since our insertions probably bypass woocommerce hooks. But it seems bad to put them on existing sites because we could be overwriting existing values.

I can see arguments for:
  * (1) Filtering them out via a hardcoded list in the term annotation generator
  * (2) Keeping as-is
  * (3) Changing the term_meta applier to only ADD meta values if they don't exist, but to NOT UPDATE meta values that are already on the site. :heavy_check_mark: 

Update: We went with (3).

**Comment by daledupreez** [comment]
For the dynamic annotation values, I mentioned in a Slack thread with @mreishus that I think approach (3) is the right way to move forward so we can keep this relatively safe. p1666275343861819-slack-C0Q664T29

**Comment by mreishus** [comment]
See paYKcK-2f3-p2 for a summary of work remaining

**Comment by mreishus** [comment]
Atomic Headstart Generation: Is now a part of the theme-demo-bar-plugin. https://github.com/Automattic/theme-demo-bar-plugin
Atomic Headstart Application: The taxonomy portion is now triggered by a wpcomsh "headstart-terms" command, which is queued up to run in a post-transfer job.
