### ISSUE TITLE
Visual inconsistencies with the CTA styles on the plan management page

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#68921]
### Quick summary

This is a followup to https://github.com/Automattic/wp-calypso/pull/67423 for some small inconsistencies.

First, as already noted at https://github.com/Automattic/wp-calypso/pull/67423#issuecomment-1249671790, the visual style for the CTAs on Earn purchases (made via the Payment Blocks) is now quite different from everything else (icons used, icon placement, etc) -- compare this to other screenshots below:

![payments-blocks](https://user-images.githubusercontent.com/235183/195146269-42189c2f-f67c-4b19-b916-e91008edcb08.png)

Second, when a WordPress.com plan is close to expiration, the "Renew Annually" and "Renew Monthly" links have wrong capitalization compared to everything else (also, two links with the same icon looks kind of strange, but I'm not sure I have a better suggestion):

![renew-annually-and-monthly](https://user-images.githubusercontent.com/235183/195146513-4cdf63a5-32ed-420b-b03a-61bf3495bb02.png)

Finally, and this is fairly minor, for a upgradeable Jetpack **product** (like Backup) which is not a plan, the upgrade link says "Upgrade plan" (previously it just said "Upgrade").  This isn't really so bad, except that it's inconsistent with the terminology we show when the product is already expired -- for that we are using "product", not "plan".

Non-expired Backup product:

![jetpack-backup-not-expired](https://user-images.githubusercontent.com/235183/195147125-bf07b36c-aaac-4b26-b36f-8ab55e556fce.png)

Expired Backup product:

![jetpack-backup-expired](https://user-images.githubusercontent.com/235183/195147141-af92362b-47c9-432d-a02d-fb14652bd06a.png)

### Steps to reproduce

Follow the instructions above to generate subscriptions in different states, then go to `/me/purchases` and click through to view the subscription.  You may need to edit the expiration date on the server (requires WordPress.com admin access) to get a subscription that expires soon or is already expired.

For the Earn/Payments Block purchases, testing instructions can be found at PCYsg-lW4-p2.

### What you expected to happen

See above

### What actually happened

See above

### Reproducibility

Consistent

**Comment by jjchrisdiehl** [comment]
@DavidRothstein For the payment block 'subscription' products, we appear to use a separate frontend component in the manage purchase section than our typical 'plan' products:

Subscription management 
https://github.com/Automattic/wp-calypso/blob/trunk/client/me/memberships/subscription.jsx#L136-L145

Plan Management
https://github.com/Automattic/wp-calypso/blob/trunk/client/me/purchases/manage-purchase/index.jsx#L449-L462

I'm not particularly sure why we have two sets of code here, but perhaps there was a good reason to do so.

We have two options, as far as I can tell:

A) Simple styling fix. Just duplicate the styles across these sections so that they match
B) Refactor the payment block subscription section so that it uses the same patterns as the regular plan purchase management components.

I suspect A is probably a better option at this time. Thoughts?

**Comment by DavidRothstein** [comment]
@jjchrisdiehl That sounds right to me too.  Definitely can't refactor the whole thing to use the same code (since the `RemovePurchase` component is basically tied to WPCOM purchases) but I wonder if you could get pretty far just by swapping out the `CompactCard` component that the payment block subscriptions currently use with the `Wrapper` component that is ultimately used inside `RemovePurchase`?:

https://github.com/Automattic/wp-calypso/blob/85a7711207bd72f41aed4547a4195f1e22a4179c/client/me/purchases/remove-purchase/index.jsx#L359-L362

Or in the worst case, yes, just directly styling them to match.

**Comment by jjchrisdiehl** [comment]
PR can be found here https://github.com/Automattic/wp-calypso/pull/69271

**Comment by jjchrisdiehl** [comment]
Just waiting on translations to finish here https://translate.wordpress.com/deliverables/7619216

Once that is done, [this](https://github.com/Automattic/wp-calypso/pull/69271) should be good to merge.

**Comment by jjchrisdiehl** [comment]
Issue has been resolved by https://github.com/Automattic/wp-calypso/pull/69271
