### ISSUE TITLE
Comments notification emails

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#68949]
### Quick summary

We have someone who is getting email notifications on comments, but they have not subscribed to the site.

We need more help, based on this as it appears to be a .com specific thing:

https://github.com/Automattic/jpop-issues/issues/7805#issuecomment-1272756255

### Steps to reproduce

Unable to replicate.

### What you expected to happen

For the email notification to not show up if they aren't subscribed.

### What actually happened

The user received a notification.

### Context

5522885-zen

### Theme-specific issue?

no

### Browser, operating system and other notes

no

### Workaround details

They could turn off all notifications from: https://wordpress.com/me/notifications/comments

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Was not able to test, issue does not include steps to replicate.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @Robertght Please feel free to reopen with steps to replicate if possible. If this issue is only affecting one specific user, I'd recommend reporting through internal channels. Thanks!
