### ISSUE TITLE
Unsubscribe email link doesn't work

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#68950]
### Quick summary

This is a second issue related to the same case.

#1 https://github.com/Automattic/wp-calypso/issues/68949

### Steps to reproduce

We cannot replicate

### What you expected to happen

For the unsubscribe link to disable notifications on new comments

### What actually happened

It did nothing

### Context

5522885-zen

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

No

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Was not able to test, issue does not include steps to replicate.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @Robertght Please feel free to reopen with steps to replicate if possible. If this issue is only affecting one specific user, I'd recommend reporting through internal channels. Thanks!
