### ISSUE TITLE
[Bug]: Post-checkout thank you page says "You don't have any WordPress sites yet" for users without sites

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#68988]
### Quick summary

As a user without any sites yet, making a Jetpack purchase (via siteless checkout) leads me to this post-purchase "thank you page":

![siteless-checkout-thank-you-page](https://user-images.githubusercontent.com/235183/195377047-d41c8374-d58d-4e0d-a1eb-82c5617a93c6.png)

As can be seen from the URL, it was probably trying to redirect me into the expected thank you flow but got interrupted by the "no sites" message instead.

My guess would be that this is a side effect of https://github.com/Automattic/wp-calypso/issues/53356 but I haven't looked.

### Steps to reproduce

The easiest way to reproduce this is to start at https://cloud.jetpack.com/pricing as a logged-out user and make a purchase of any product.  After checkout, you get redirected to the screen shown above.

### What you expected to happen

To see the expected post-checkout thank you page.

### What actually happened

Saw the "You don't have any WordPress sites yet" page instead.

### Reproducibility

Consistent

**Comment by sirbrillig** [comment]
I agree that the bug seems likely to be related to that PR. What I don't understand yet is why it's happening. My first guess was that the [pending page redirect function](https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/my-sites/checkout/checkout-thank-you/pending/index.tsx#L76-L81) is misbehaving somehow.

The way it's supposed to work is that if there is a `receiptId` and a `redirectTo` in the query string, the page should redirect to the `redirectTo`:

https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/my-sites/checkout/composite-checkout/lib/pending-page.ts#L317-L330

If there's any problem with the redirect, we are instead [sent to a generic thank-you page](https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/my-sites/checkout/composite-checkout/lib/pending-page.ts#L276-L281).

However, in your screenshot, it looks like we are _still on the pending page_. This is very strange because the pending page [now displays a loading indicator](https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/my-sites/checkout/checkout-thank-you/pending/index.tsx#L100-L110) and instead we are seeing the "You don't have any WordPress sites" message.

Therefore two supposedly impossible things are happening:

1. The pending page is not redirecting anywhere even though the conditions for the redirect seem correct.
2. The pending page is displaying "You don't have any WordPress sites" instead of the loading indicator.

This makes me wonder if **maybe the page we're seeing isn't actually the pending page component at all**, and instead is coming from somewhere else either in the [controller](https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/my-sites/checkout/controller.jsx#L202-L233) or [the middleware](https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/my-sites/checkout/index.js#L96-L103). I don't know what they do right now but perhaps `redirectLoggedOut` or `siteSelection` is hijacking the route.

**Comment by sirbrillig** [comment]
To the above, maybe `siteSelection` is doing this:

https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/my-sites/controller.js#L442-L447

I don't know if that call is necessary for the `no-site` route and maybe we can just remove it by removing this line:

https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/my-sites/checkout/index.js#L99

**Comment by sirbrillig** [comment]
https://github.com/Automattic/wp-calypso/pull/69002 Should fix it.

**Comment by manzoorwanijk** [comment]
Related p1HpG7-ir3-p2
