### ISSUE TITLE
Cannot disable auto-renew for purchases made without a site

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#68998]
### Quick summary

If you use Jetpack siteless checkout to purchase a subscription that isn't yet connected to a site, and then go to manage the purchase, you don't have the option to toggle auto-renew on or off ("ON" in the screenshot below would normally be a link):

![jetpack-siteless-checkout-no-autorenew-toggle](https://user-images.githubusercontent.com/235183/195405243-20f7c060-df27-45ac-8e19-946b8050c9a0.png)

I thought this might be a recent regression, but based on the code it seems like it's actually old behavior.  I think it's basically because of this:

https://github.com/Automattic/wp-calypso/blob/2dbbd0a9b64eb73d3c08da63d8972d7770af7f8b/client/me/purchases/manage-purchase/purchase-meta.jsx#L507

And more broadly the fact that the `AutoRenewToggle` component expects a site slug.

### Steps to reproduce

1. Start at https://cloud.jetpack.com/pricing
2. Buy something (or at least anything except Jetpack Search, since that one requires you to choose a site for the purchase)
3. Go to https://wordpress.com/me/purchases and click on your purchase

### What you expected to happen

To be able to toggle auto-renew on and off.

### What actually happened

There was no option to do that.

### Reproducibility

Consistent

### Available workarounds?

Yes, difficult to implement

### Workaround details

Once you connect your Jetpack subscription to a site, presumably the issue goes away then (I haven't tested).  However, some users likely struggle with that and may want to toggle auto-renew off earlier in the process.

**Comment by JessBoctor** [comment]
@jboland88 I noticed that the blocker for the auto-renewal toggle being shown is [isJetpackPurchaseUsingPrimaryCancellationFlow](https://github.com/Automattic/wp-calypso/blob/trunk/client/me/purchases/manage-purchase/purchase-meta.jsx#L409). 

Does the new cancellation flow expect that siteless purchases don't have an option to deactivate/reactive auto-renew?

Any insight you have would be greatly appreciated. Thanks!

**Comment by jboland88** [comment]
Hi @JessBoctor 

> Does the new cancellation flow expect that siteless purchases don't have an option to deactivate/reactive auto-renew?

Hmm, so the main cancellation flow is clicking on the "Cancel Purchase" button below the purchase details from the purchase page. Cancelling this way should work for siteless purchases and will disable auto-renew.

In #70493 we made the change so that all Jetpack purchases use this main cancellation flow instead of the auto-renew toggle to disable auto-renewal. As an addition, we did add a link to "Re-enable" auto-renew from the purchase page when it is off. Check out the test plan on that PR for what the  re-enable link looks like. 

However, I think the re-enable link will not show for siteless purchases when auto-renew is off due to the same root issue mentioned in this bug. The re-enable link uses the same `<AutoRenewToggle />` component, which is conditionally rendered based on the above mentioned variable `shouldRenderToggle`, which looks for the presence of a site.

Reference: https://github.com/Automattic/wp-calypso/blob/trunk/client/me/purchases/manage-purchase/purchase-meta.jsx#L345-L358

Not sure if that helps answer your question?

**Comment by JessBoctor** [comment]
Checking the current code, it looks like the change in the cancellation flow has been reverted. Still need to test, but I think this can be closed.

**Comment by JessBoctor** [comment]
I retested this today. The auto-renewal button is still removed for siteless Jetpack sites. This kinda makes sense given the cancellation flow for checkout in general, and the changes to the autorenewal meta on WordPress.com that uses links rather than the toggle buttons. 

<img width="1445" alt="GH68998-AutoRenewOn-Screenshot 2023-04-18 at 2 15 45 PM" src="https://user-images.githubusercontent.com/12505355/232915342-5f2c6ecc-5d20-4fee-b67f-7b0cdcf0f920.png">

The one area of improvement would be for when auto-renew is turned off. It might be good to add a note that to re-enable auto-renew they should connect a site. 

<img width="1067" alt="GH68998-AutoRenewOff-Screenshot 2023-04-18 at 3 02 17 PM" src="https://user-images.githubusercontent.com/12505355/232915590-b18b64b3-c697-4cc0-b1d3-498bc175cdd6.png">

Putting back into the inbox to discuss if this is worth picking up again.

**Comment by michaeldcain** [comment]
From planning:

If this is the intended behavior for Jetpack Siteless subscriptions (only being able to cancel, create a site and assign, or auto-renew -- no manual renewal), then let's close this issue.

**Comment by DavidRothstein** [comment]
^^ Or to put it another way, this probably **should** get a "Re-enable auto-renew" option (similar to everything else in Jetpack) but it's less important and not the original purpose of the issue and we probably won't be adding that ourselves, especially since the use case for renewing these subscriptions is relatively low anyway.
