### ISSUE TITLE
Posts / CPTs: Preview icon & behavior inconsistencies

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#6902]
For the CPT post listing, we're using an in-page preview modal, whereas on the post and page listings it opens a new window. This is especially confusing because we're using the same icon for both (the "pop out" icon), which usually indicates that a link will open in a new page.

@mtias <a href="https://github.com/Automattic/wp-calypso/pull/6534#issuecomment-233591038">said</a> "If something opens within Calypso we should use no icon", but I'm not sure how that will affect the layout.

cc @hugobaeta

**Comment by codebykat** [comment]
CPT listing (opens in modal):
![screen shot 2016-07-19 at 12 13 13 pm](https://cloud.githubusercontent.com/assets/52152/16963392/1cd309c6-4dab-11e6-84bb-a93c8b263bea.png)

Pages (opens new window):
![screen shot 2016-07-19 at 12 13 31 pm](https://cloud.githubusercontent.com/assets/52152/16963393/207795d8-4dab-11e6-98b9-c1b405fce662.png)

Posts (opens new window):
![screen shot 2016-07-19 at 12 20 46 pm](https://cloud.githubusercontent.com/assets/52152/16963438/43441b40-4dab-11e6-836a-277dff25d9b6.png)

**Comment by hugobaeta** [comment]
I just told this to @codebykat: When I designed the new compact card list view for CPT's, I followed the principles in the "Blog Posts" list view - that includes the order of the elements (first item should always be the primary action of the card, "Edit"), and their behaviour (on Blog Posts, "View Page" opens a new tab). Whatever we chose, it should be first and foremost consistent. If we go for the modal view in both places, maybe the eye icon could be used to represent that action, maybe?

**Comment by hugobaeta** [comment]
Also, Pages List shouldn't even be considered as an example, as I'd love for that view to be switched to this new compact card view eventually.

**Comment by mtias** [comment]
Agreed on being consistent with the order.

> If we go for the modal view in both places, maybe the eye icon could be used to represent that action, maybe?

Yes, the idea is to gradually replace all "Preview" actions to happen within the app, so we should be reducing the amount of external link indicators.

**Comment by folletto** [comment]
> If we go for the modal view in both places, maybe the eye icon could be used to represent that action, maybe?

Agreed as well. The "pop out" icon should be used for new windows/tabs. Otherwise we should use a more semantic icon (eye, or one made ad-hoc). :)

**Comment by designsimply** [comment]
Closing because Preview/View links appear to have been updated from pop-out to eye icons:

![screen shot 2016-07-28 at thu jul 28 11 28 42 am](https://cloud.githubusercontent.com/assets/1119271/17222709/f2bc03b4-54b6-11e6-9648-fd2eded331c9.png)
<sup>Seen at https://wordpress.com/types/jetpack-portfolio/drafts/design5279.wordpress.com on staging using Firefox 47.0.1 on Mac OS X 10.11.5</sup>

![screen shot 2016-07-28 at thu jul 28 11 28 55 am](https://cloud.githubusercontent.com/assets/1119271/17222718/f89da77e-54b6-11e6-9b79-2cd4ebb58d7d.png)
<sup>Seen at https://wordpress.com/types/jetpack-testimonial/design5279.wordpress.com on staging using Firefox 47.0.1 on Mac OS X 10.11.5</sup>
