### ISSUE TITLE
Editor: cannot get back to a post preview without an entire page refresh after clicking an internal link in a preview

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#6911]
Steps to reproduce:
1. Create a new post including a link to another post on the same blog
2. Make sure the post is saved
3. Click the Preview button
4. Click on the link from inside the preview

<strong>Result:</strong> once a link is clicked, there's no way to get back to the original post preview without an entire page refresh

<img width="1280" alt="screen shot 2016-07-19 at tue jul 19 4 32 35 pm" src="https://cloud.githubusercontent.com/assets/1119271/16971265/8694dc8e-4ddf-11e6-870d-e8d8c3eb2c52.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10114 using Firefox 47.0.1 on Mac OS X 10.11.5</sup>

Found during a #bug-scrub

/ht @hoverduck  for the original report

**Comment by rachelmcr** [comment]
Confirmed this is still an issue.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

I tested the steps as follows:

1. Create a post.
2. Type text using Paragraph block.
3. Insert link to post on same blog.
4. Save post.
5. Preview.
6. Click on the link in preview.

While back/forward navigation does not appear to function in the preview window, it is possible to close the preview and re-open the preview.

Does the above sound like expected behavior?

If not, I am proposing to close this issue with an appropriate label denoting reason for closure.

https://user-images.githubusercontent.com/6549265/106336081-fdc76980-6242-11eb-87d2-2d0b52454d30.mov
