### ISSUE TITLE
Sites Management Page: Add <SitesTableRow /> to DevDocs

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#69130]
Our `<SitesTableRow />` has a fair number of UI variations now. It would be great to set this up in DevDocs, so we can more easily inspect changes (p1665762615564289-slack-C0347E545HR).

**Done is:**
* [ ] `<SitesTableRow />` is set up in DevDocs.
* [ ] We have a good number of stories written for the UI variations.

**Comment by zaguiini** [comment]
Hmm. `client/components` do not have a Storybook setup. Do you mean `packages/components`? If yes, I'd be reluctant in adding the `SitesTableRow` or `SitesGridTile` there since they're very specific to the Sites page. Maybe it'd be worth it to set Storybook for the `client` folder as well?

**Comment by danielbachhuber** [comment]
> Maybe it'd be worth it to set Storybook for the `client` folder as well?

@zaguiini Yeah, likely:
1. I originally went down the path of setting up Storybook for `client`.
2. After I was unsuccessful, I created this issue.
3. After I created this issue, I chatted with @p-jackson and we agreed it probably makes sense to set up Storybook for `client` (vs. abstracting `<SitesTableRow />` out). It seems like it would be generally useful to have Storybook available for `client`.

**Comment by zaguiini** [comment]
We have [Devdocs](http://calypso.localhost:3000/devdocs/design), which maybe does what we want. How about we try that before adding Storybook?

**Comment by danielbachhuber** [comment]
> We have [Devdocs](http://calypso.localhost:3000/devdocs/design), which maybe does what we want. How about we try that before adding Storybook?

@zaguiini Could, although would that require abstracting the code to `client/components/` ?

@p-jackson Is Devdocs or Storybook the more "modern" approach?

**Comment by p-jackson** [comment]
> Is Devdocs or Storybook the more "modern" approach?

I would say that Storybook is the more "modern". It's being used by both Gutenberg and `@automattic/components`, and I think over time Calypso should move towards that set of technologies.

However devdocs probably does have everything we need. The main problem we want to solve here is to make it easier to test all of the variations and permutations of the table and grid components, and we wanted to be able to do that without the need to tease apart all the Calypso dependencies first. So devdocs would allow us to achieve that.

> I'd be reluctant in adding the `SitesTableRow` or `SitesGridTile` there since they're very specific to the Sites page

@zaguiini I don't think these components are so Sites page specific, and my original intention was for them to be distributable via `@automattic/components` (or any `@automattic/*` package). The components allow you to browse your sites, and that seems like a generally useful concept across wpcom. Maybe you're adding a site to your P2 network, we could open an easily scannable list of your existing sites to add to the network. Or in the block editor we want to add some controls that add a hyperlink to one of your other websites (like a blogroll maybe?)

I've found that over time, UI which we never thought will get used outside of its original context, gets re-used. Usually in the editor 😄; if it exists we always seem to want to show it in the editor. That's why I think putting things in `@automattic/*` whenever possible is important. Gutenberg is our lowest common denominator, and if it's compatible with GB then it can be used in all contexts: Calypso, GB, ETK, some other plugin etc.

**Comment by zaguiini** [comment]
I see what you're saying, @p-jackson and it makes sense too. Maybe it'd be worthwhile to move it to a standalone package once we confirm that we're reusing that logic, but as it stands, we'd even lose some benefits since the packages do not have emotion or other tools we're currently using, so a bigger refactor would be needed.
