### ISSUE TITLE
Writing Prompts - Add writing prompt notification setting

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#69160]
## Description

We plan on adding writing prompts to the Gutenberg block editor. One place we will surface writing prompts is via notifications. Adding the notification is handled in https://github.com/Automattic/wp-calypso/issues/69159, this card is for managing the notification settings.

#### Notification settings
We had some lively debate on the team sync about where notifications should be handled in summary:
* It makes sense for notifications to be tied to a site since they must take the user to the editor for a specific site. But,
* If a user has multiple sites, they may not be able to easily discover which of their sites has writing prompt notifications active, or where to go to deactivate them.
* If multiple sites have daily notifications active, they may receive too many notifications

We'll need to decide on whether to have notifications be global (and if so, which site to use in the link) or to be site specific (and if so how to manage multiple sites having notifications active).

@ollierozdarz was going to put some more thought into this.

#### Notification frequency
Another consideration is how often to send notifications, different prompts are released daily, but if we send a notification every day, that could be a lot of spam. I don't think we've worked out the exact mechanics of this yet

## Screenshot
![CleanShot 2022-10-17 at 10 34 54](https://user-images.githubusercontent.com/22446385/196323406-5a78afe3-0453-40fe-84ab-801e579cadd1.jpeg)

![image](https://user-images.githubusercontent.com/5634774/196437174-17a007df-5fec-4a8f-819d-858d847d5239.png)

**Comment by ollierozdarz** [comment]
@roo2 I've provided some more details in Slack. Here's a link to a [GIF](https://d.pr/i/WoCCbA) which will show the flow better too.

Essentially, we'll introduce a disabled Bell icon on the active instance of the notification in the side panel (the popout panel once you click a notification). That Bell will deep link the user to their Site Notification settings belonging to notification (since notifications are global, but these will be on a site level). Users can then choose to disable the Daily Prompt notification. By doing it this way, they don't lose the ability to turn it back on later on.

<img width="1479" alt="Screen Shot 2022-10-19 at 8 17 10 am" src="https://user-images.githubusercontent.com/67085494/196555532-81cc8ab4-44d3-4977-96ec-e96c75afe155.png">
<img width="1474" alt="Screen Shot 2022-10-19 at 8 17 15 am" src="https://user-images.githubusercontent.com/67085494/196555551-2f13cfa7-fc2d-4d74-8bae-bd0d2cde4d91.png">

**Comment by roo2** [comment]
We were discussing in slack p1666123444322499-slack-C03NLNTPZ2T how to limit spam if the user has multiple blogs.

The current idea is to show notifications by default _only_ for the _first created_ blog with `site_intent === 'write'`. Of course this could later be changed by the user.

**Comment by creativecoder** [comment]
A setting for Writing prompt notifications is now available at `/me/notifications` for each site.
