### ISSUE TITLE
Update theme switch modal for case of switching to Blank Canvas in the Theme Showcase

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69168]
# Description
See Reviewing the theme switch modal messaging pbxlJb-2Gx-p2
See related issue for possible better ideas: https://github.com/Automattic/wp-calypso/issues/68953

When the PA flow ships, the blank-canvas-3 (PR https://github.com/Automattic/themes/pull/6665) will be available in the Theme Showcase. It will be called Blank Canvas publicly.

When users pick this theme in the showcase they will of course be undergoing a theme switch, from some ThemeX to BC they need to understand the special context of this theme.  Thus the Theme switch modal needs to be customized for this special case.  This will be an interim situation, as once we add in the PA flow into the theme showcase, the user will have a guided flow for setting up their BC.

For MVP we aren't going to implement preserving existing content for ThemeX-->BC (however we will preserve copy from BC-->ThemeX see [[Spike] Persist the BCPA home.html template through a theme switch](https://github.com/Automattic/wp-calypso/issues/68427))

**Current modal:**
<img width="521" alt="image" src="https://user-images.githubusercontent.com/5665959/196595502-0e185698-47fd-44cb-98e0-f99402b48036.png">

** Updated modal:**
@SaxonF  Do we need design?  Or do we simply have a modal with copy?  Or maybe it should include this imagery:
![image](https://user-images.githubusercontent.com/5665959/196350312-52b2ac09-39c6-4ebf-9d6e-e9b475a92743.png)

### Specs
* BC does not have a homepage or a home.html so copy needs to reflect this reality
* Copy should explain what Blank Canvas is, perhaps "Blank Canvas is a bare bones theme, ready for you to create your theme templates and build the site you want.  Are you sure you want to switch to this theme and start site building from scratch?"
* Should we include a link out to template docs? https://wordpress.com/support/templates/

Note: we will need to update this again when we introduce the PA flow into the Theme showcase.

**Comment by autumnfjeld** [comment]
While doing this work, double check that the second modal makes sense.  I think the current one will be fine, but just wanted to share my thoughts.

Here's the current BC modal #2:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/5665959/196595333-363ae53b-351f-4b18-9368-5d59243298e3.png">

**Comment by autumnfjeld** [comment]
@SaxonF  Can you help us with design here?   Thank you! :)

**Comment by tanjoymor** [comment]
> For MVP we aren't going to implement preserving existing content for ThemeX-->BC

So if someone tries to switch an existing site from their current theme to BC will they lose “content” as in pages and posts? Or are you just referring to pre-existing templates? That distinction needs to be clear.

**Comment by SaxonF** [comment]
I'm assuming pages and posts will remain, you'll just lose any content contained in templates. 

I'm not sure we should do something that's specific to BC here and instead work on changes that can benefit all theme switches. e.g. If I manually created a front-page template and switch theme I'll have a very similar experience. The Blank Canvas theme could also be used by people without needing to go through the PA.

- If your homepage settings are set to show latest posts I don't believe there is currently a way to preserve content so that shouldn't even be an option. ( I could be wrong). We should instead show what their homepage will look like and warn that their existing homepage will be replaced.
- If static page is set to home, and they select preserve content on theme switch, they will still lose any content that's within the template rather than page.

The best way to warn a user of the consequences of a theme switch is to _show_ them. We have these tiny thumbnails that are also in a broken state when switching themes when homepage is set to show latest posts.

All that to say I don't think this should be a blocker for the PA onboarding flow and we should instead treat this as a separate issue. 

**Issues**
- Remove the option to preserve content when homepage is set to show latest posts
- Provide a better view into what the resulting site will look like post switch. This is marked as Milestone 4 [here](p9Jlb4-5vv-p2#milestone-4-theme-switching)
- Preserve templates when switching themes which as you mentioned is already in motion in core

**Comment by arthur791004** [comment]
> For MVP we aren't going to implement preserving existing content for ThemeX-->BC (however we will preserve copy from BC-->ThemeX

Why do we only preserve content from BC-->ThemeX for MVP? I don't think we need extra effort to keep the content bidirectionally (BC <--> ThemeX). In my opinion, we just need to preserve the content when people don't want to change their home page and the homepage displays setting is configured to "latest posts". Additionally, we need to take care of both old and new themes supporting FSE

**Comment by autumnfjeld** [comment]
> Why do we only preserve content from BC-->ThemeX for MVP?

@arthur791004 The reason was to avoid scope creep. To be laser focused on one experience.    If you think it is straightforward to implement it bidirectionally, then that is great news. Do it.  😃

**Comment by autumnfjeld** [comment]
> So if someone tries to switch an existing site from their current theme to BC will they lose “content” as in pages and posts? Or are you just referring to pre-existing templates? That distinction needs to be clear.

Ah, sorry about that Of course all Pages & Posts persist thru theme change. No change there from existing behavior.

**Comment by miksansegundo** [comment]
> For MVP we aren't going to implement preserving existing content for ThemeX-->BC

Are we going to redirect users to the PA when they switch from some ThemeX to BC? I think we will, and the PA won't show the previous home. The user will create a new home from scratch, the previous home won't be deleted because it seems that we can keep it but it won't be used.

> The Blank Canvas theme could also be used by people without needing to go through the PA.

So depending on if we redirect them to the PA or not, the meaning of "Switch theme preserving my homepage content" can be different, right?

**Comment by autumnfjeld** [comment]
>  The Blank Canvas theme could also be used by people without needing to go through the PA.

It is very likely we will add the PA flow to the BC theme showcase, p1665735522252499/1665730226.315779-slack-CRWCHQGUB,  I'm not sure the if we will give users an option to skip the PA flow. There hasn't been any mention of something like that.  🤔 

For the interim period, because the new BC theme won't have any concept of "homepage" or "Home Page" or "home.html" , I do believe we have a special case here that needs to be considered when users switch to this theme without the PA flow.

**Comment by autumnfjeld** [comment]
AH! Decision has been made to hide the new BC: p1666253424596039/1665543032.718109-slack-CRNF6A9DX

This makes me happy.

**Comment by miksansegundo** [comment]
If in the future, we decide to show the new BC and redirect to the PA, the template creation won't work because of this [reason](https://github.com/Automattic/wp-calypso/pull/69241#pullrequestreview-1148665502).
