### ISSUE TITLE
[Bug]: "We could not validate your contact information" error on checkout load when buying a domain for a user who previously bought a non-domain

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#69211]
### Quick summary

If a user who already paid for a non-domain goes to buy a domain later, they get an error message like this immediately when the checkout screen loads (before they have typed anything in):

![validation-error-on-checkout-load](https://user-images.githubusercontent.com/235183/196496153-3255a0af-f6a4-43af-aa56-5361a4ec1ec6.png)

### Steps to reproduce

The easiest way to reproduce this is to sign up with a new user account and buy a monthly plan (since that does not come with a free domain), then later go to Upgrades -> Domains and add a domain to your shopping cart.

### What you expected to happen

No error message immediately when the checkout page loads.

### What actually happened

I saw an error message immediately after the checkout page loaded.

### Reproducibility

Consistent

**Comment by DavidRothstein** [comment]
>The easiest way to reproduce this is to sign up with a new user account and buy a monthly plan (since that does not come with a free domain), then later go to Upgrades -> Domains and add a domain to your shopping cart.

Actually it turns out this can be reproduced with an annual plan also (in the case where you buy the plan first and add the free domain later) because it appears the bug occurs in the shopping cart even when a free purchase is being made.

**Comment by sirbrillig** [comment]
This is a side effect of https://github.com/Automattic/wp-calypso/pull/64344 which simplified how contact validation works. Since the contact step attempts to auto-complete as soon as checkout loads, it will display validation errors if the information is incomplete. Prior to that PR we had a special form of validation that would silently ignore validation errors on load; however, that meant that we had to maintain two separate validation functions. 

We may be able to implement that feature again within the simpler setup. The hard part is how to determine if the step completion is being triggered by code (we don't want to see validation errors) or by a user (we do want to see validation errors).

Alternatively, maybe there's a way to avoid attempting the validation in the first place if the form is missing required fields. This is hard, though, because which fields are required is entirely controlled by the validation endpoint.

**Comment by sirbrillig** [comment]
The fix was reverted, so this is again an issue.
