### ISSUE TITLE
Task: Clean up the FSE E2E smoke test.

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#69258]
### Details

The current FSE smoke test `specs/fse/fse__temp-smoke-test.ts` has a couple issues...

1. It doesn't pass on Atomic sites. See the related tracking issue #65906.
2. It doesn't use the Full Site Editor POM classes that were added in the editor tracking migration.

We should update both of those!

**Comment by dpasque** [comment]
Hi @karenroldan! 👋 

For your first fix, I'm assigning you this piece that was broken off of the bigger tracking issue: #65906.

That tracking issue tracks all of our E2E tests that don't pass on atomic. This individual script needs updating to pass on atomic. Using the [new library classes added for FSE in the calypso-e2e package](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts) should probably get you pretty far!

Also, as a helpful reference, you can force E2E tests to run on an atomic user/site with an env variable:
`TEST_ON_ATOMIC=true yarn jest specs/fse/fse__temp-smoke-test.ts`

**Comment by WunderBart** [comment]
It's worth adding that currently, to get correct results in the CI (TeamCity) for the Atomic suites, the tests need to be run concurrently (see the explanation [here](https://github.com/Automattic/wp-calypso/issues/65906#issue-1315490128)). To run the tests concurrently, the Magellan workers must be limited to 1 instead of 16 in the job options. This takes more time to complete, but otherwise, many of the tests will fail at the user authentication step.

**Comment by karenroldan** [comment]
> It's worth adding that currently, to get correct results in the CI (TeamCity) for the Atomic suites, the tests need to be run concurrently (see the explanation [here](https://github.com/Automattic/wp-calypso/issues/65906#issue-1315490128)). To run the tests concurrently, the Magellan workers must be limited to 1 instead of 16 in the job options. This takes more time to complete, but otherwise, many of the tests will fail at the user authentication step.

Thanks, @WunderBart! I got a walkthrough on TeamCity and how I can set the Magellan workers from 16 to 1.
