### ISSUE TITLE
Blockbase: cover block in content body overlaps mobile menu

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#69355]
### Quick summary

When a navigation block is added within a cover block in the header template part, and then a cover block (using background image and also contains a post title block) in the content body is rendered on mobile, the second cover block overlaps the mobile menu overlay, as if the z-index is greater than the menu. 

https://user-images.githubusercontent.com/39252765/197308628-7268571e-6dab-4aed-8e49-1aa1cc0f5fcc.mp4

### Steps to reproduce

1. Activate Blockbase
2. In the site editor, create a header template part that is comprised of a cover block that contains a navigation block
3. Also in the site editor, outside the header template part, create another cover block with a background image and post title block
4. Save changes, then preview the site in responsive view, particularly the mobile menu

The structure in the site editor should look like this: 

<img width="783" alt="Screen Shot 2022-10-21 at 2 39 41 PM" src="https://user-images.githubusercontent.com/39252765/197308709-b0cabfa5-d62a-45b1-820b-86bcab6b4419.png">

### What you expected to happen

I expected the navigation block on mobile to overlay all other blocks within the content body.

### What actually happened

The second cover block on the page overlaid the navigation block.

### Context

Here's an example site: https://phonerepair2.wordpress.com/

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Blockbase

### Browser, operating system and other notes

macOS, Chrome/Safari/Firefox

### Reproducibility

Consistent

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on Self-hosted - Replicated
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Was able to replicate this on simple and self-hosted test sites
- Since I was able to replicate this on self-hosted with Twenty Twenty-Two as well, it seems like it might be a core issue, not a theme issue. Closing this & opened an issue in the Gutenberg repo.

📌 ACTIONS
- Transferred to Gutenberg external repo: https://github.com/WordPress/gutenberg/issues/45353
