### ISSUE TITLE
Marketplace: Category localization

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#69360]
`/plugins` with a locale and the logged out version `/ko/plugins` is missing translations for category text.

Not sure why this is, could be we're using the wrong translation function at the wrong time, ~could be SSR?~ (don't think ssr)

~Need to double check we have translations in the first place on translate.wordpress.com.~ [Translations exist](https://translate.wordpress.com/projects/wpcom/ko/default?filters%5Bterm%5D=Add+the+best-loved+plugins+on+WordPress.com) so something must be wrong with how we load them.

Acceptance
- [ ] Category titles / descriptions should have translations

![Screenshot(51)](https://user-images.githubusercontent.com/811776/197424238-1e5fbac8-a16c-4a51-bac9-56b6e3fe7488.png)

**Comment by lsl** [comment]
@cpapazoglou would bespin be able to pick this up? A chunk of explorers are on support rotation this week.

**Comment by claudiucelfilip** [comment]
The issue seems to be caused by the fact that the translation function are run only once, very early in the app cycle. At that moment, either the locale or translations are not correct.
I [opened a PR](https://github.com/Automattic/wp-calypso/pull/69365) to move the categories to a get function, which allows the translations function to rerun later. It also ensures the translation will work once SSR is enabled.
