### ISSUE TITLE
Pattern Assembler - UI improvements

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#69362]
Addressing here the feedback in the P2 **Patterns for the Pattern Assembler MVP**

**Issues**
- Remove scrolling in pattern previews
- Pattern preview randomly uses a wrong width (Missing styles?)
- Add to the list the pattern Header pattern with button
- Swap the content patterns for the content wireframe patterns in dotcompatterns
- Retest the header selection to confirm that is added in the editor
- Order content patterns by function
- Use the “reblog” icon in the Gridicons component as the replace icon

**Features**
- Add a Cancel button in the pattern selector instead of using the Back button
- Use the site title or vertical name instead of the theme name
- Add some labels for the groups of content patterns
- See the active pattern in the list even during a replacement
- Highlight patterns in the preview when hovering them in the list of chosen patterns

**Post MVP**
- Ask for site colors to create a color scheme for the patterns

**Comment by miksansegundo** [comment]
Convo about the new features p1666574635983329-slack-CRWCHQGUB

**Comment by miksansegundo** [comment]
✅ Remove scrolling in pattern previews
✅ Add to the list the pattern Header pattern with button
✅ Swap the content patterns for the content wireframe patterns in dotcompatterns
✅ Order content patterns by function
✅ Retest the header selection to confirm that is added in the editor. There is a known issue that happens when you use an existing site with a home using a template.

❎ Use the “reblog” icon in the Gridicons component as the replace icon. We had an icon like that before, but we decided to use the pencil to be consistent with the icon used in the editor.

⚙️ Pattern preview randomly uses a wrong width
The scrollbars appear when the pattern doesn't load with the correct height and width because of a 429 error. We are working to find the root cause to fix it.

**Comment by autumnfjeld** [comment]
@miksansegundo 
Let's prioritize fixing these by MVP
* Close button https://github.com/Automattic/wp-calypso/issues/69406
* Remove scrolling in pattern previews
* See the active pattern in the list even during a replacement
* Use vertical name instead of theme name
* Patterns
  * Add to the list the pattern Header pattern with button
  * Swap the content patterns for the content wireframe patterns in dotcompatterns
  * In general we need to keep iterating, lots of room for improvement and asking designers to keep helping us iterate on pattern quality



And if you feel any others should be prioritized please do so. :)

**Comment by autumnfjeld** [comment]
I went ahead and put all the pattern items in this issue:

[Pattern improvements for MVP 🤞](https://github.com/Automattic/wp-calypso/issues/69408)
 
Since they are separate from UI issues and we'll need theme peeps to help us tackle these.
