### ISSUE TITLE
Actually unlock the content based on token

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69518]
D89966-code started passing a token to unlock content in the Jetpack posts.
It now will have a new parameter, `blog_sub` that we can use to unlock posts that are reserved for blog subscribers only. 

The case for paid subscribers is already handled:
https://github.com/Automattic/jetpack/pull/26417/files#diff-6c4e5f6a52aca3eb00a4cc6c302da733d70d8d26b61d4ba9e4ec2a8141add6e3R453

We also want to write a test for that.

I think we want to encapsulate the logic in `\Automattic\Jetpack\Extensions\Premium_Content\subscription_service`

For reference, here is how it should behave: pbOQVh-2wm-p2

**Comment by romarioraffington** [comment]
### Todos
- [ ] Write logic to unlock content based on JWT and add that logic in `\Automattic\Jetpack\Extensions\Premium_Content\subscription_service`
- [ ] Write a test for the [gating posts for paid subscribers](https://github.com/Automattic/jetpack/pull/26417/files#diff-6c4e5f6a52aca3eb00a4cc6c302da733d70d8d26b61d4ba9e4ec2a8141add6e3R453)

**Comment by artpi** [comment]
This task is ONLY about handling `blog_sub ` parameter

**Comment by artpi** [comment]
> Write a test for the [gating posts for paid subscribers](https://github.com/Automattic/jetpack/pull/26417/files#diff-6c4e5f6a52aca3eb00a4cc6c302da733d70d8d26b61d4ba9e4ec2a8141add6e3R453)

You want to write a test for gating post for **blog subscribers**.  I think a one for paid should already be there

**Comment by romarioraffington** [comment]
After discussions with Artur, we felt it was important to share additional context. I find it easier to understand the solutions in terms of user flows.

### Flow A: User subscribes for the first time as a paid subscriber

1. User enters their email, then clicks the subscribe button
2. A checkout modal is displayed in an iFrame
3. User enters their card details and pays
5. A JWT token is returned from the server to the iFrame
6. The iFrame uses [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to post the JWT to the parent window
7. From the parent window, the JWT is stored as a cookie and appended to the current URL, and the page is refreshed ( [code](https://github.com/Automattic/jetpack/blob/b313bd253afdf919adf7a71a866d0ab85b3a7bda/projects/plugins/jetpack/extensions/blocks/premium-content/view.js#L21) )
8. User now has access to the content.

### Flow B: User attempts to re-subscribe as a paid subscriber

This could happen due to the user being unauthenticated in some way.

1. User enters their email, then clicks the subscribe button
2. A JWT is returned from the server.
3. The JWT is stored as a cookie and appended to the current URL, and the page is refreshed ( [code]
8. User now has access to the content.


There are other flows, such as authenticating with a code that is then emailed; however, the important concept to remember here is that a JWT or cookie is used to authenticate subscribers, and this authentication check is done after clicking the subscribe button.

**Bug:  Currently, the JWT is not returned when a user subscribes as a "free" subscriber.** 

This thread is also useful: p1667238412018459-slack-C01B6KEJ5GE

**Comment by n3f** [comment]
Feel free to edit this diagram if it helps...

```mermaid
flowchart TD
start[User enters their email then clicks the subscribe button]
isauth{User is authenticated}
fin[User now has access to the content]
start --> isauth

%% flow A
modal[A checkout modal is displayed in an iframe]
cc[User enters their card details and pays]
jwtiframe[iframe -- subscribe.wordpress.com]
parent[parent-- original client site]

isauth -- Yes --> modal
modal --> cc
cc -- JWT --> jwtiframe
jwtiframe -- iFrame uses window.postMessage to post the JWT --> parent
parent -- stores JWT in cookie and appends to URL --> parent
parent --> fin

%% flow B
isauth -- No --> server
server -- JWT --> parent
```
