### ISSUE TITLE
Fix blurry mShots images in Design Picker

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69610]
# Description

See Matias's comment: p1666274280616169-slack-C03E1LGV796.
>  "Theme screenshots are looking blurry to me (not hi-dpi) (?)"

Currently the thumbnails in the Design Picker look blurry. Investigate if sharper images can be produced for the Design Picker. Is it a mShots issue? Or image sizing issue?

![Image](https://user-images.githubusercontent.com/5665959/198934633-70a494a0-30f3-4841-8410-f1238e8ae10b.png)

Compare the Design Picker thumbnails to the resolution in these other areas (the screenshots below aren't very good for highlighting the resolution, but in my opinion, when I looked at the three UI locations below, the resolution was better than DP images) :

###  1 Generated designs (which are of course iFramed html, so naturally are sharp):

![Image](https://user-images.githubusercontent.com/5665959/198935225-1b12288f-6f8c-47d6-9734-13df9cb77331.png)

### 2  Theme Showcase

![Image](https://user-images.githubusercontent.com/5665959/198935428-361bcba2-1cf2-485a-a488-76614ba82064.png)

### 3  Add a page

![Image](https://user-images.githubusercontent.com/5665959/198935575-dd9e85e6-eac6-4952-80e3-b0c2d2adfef3.png)

## Ideas
Looking at

https://s0.wp.com/mshots/v1/https%3A%2F%2Fpublic-api.wordpress.com%2Fwpcom%2Fv2%2Fblock-previews%2Fsite%3Fstylesheet%3Dpub%252Fquadrat%26language%3Den%26viewport_height%3D1040%26source_site%3Dpatternboilerplates.wordpress.com%26use_screenshot_overrides%3Dtrue%26site_title%3DQuadrat?vpw=599&vph=1600&w=600&screen_height=3600&count=0

`vpw=599&vph=1600&w=600&screen_height=3600&count=0`
Should we double with width?

**Comment by gmovr** [comment]
I wonder if this is related to retina (and other 2x screens). It can be solved using `srcset="pic.jpg?w=600 1x, pic.jpg?w=1200 2x"` I believe (or something along those lines). 

At least worth a test to prevent loading images larger than the container.

@dkd903 who's been working on something similar for images on blog posts/landing pages.

**Comment by dkd903** [comment]
srcet (responsive images) supports both width as well as device pixel ratio calculations, which means it is perfectly okay to combine width declarations as well as device pixel ratio. The Picture and source atgs seem to be particularly usefule here as well.

**Comment by miksansegundo** [comment]
I think we could simply double the width of the `mShots` images if that doesn't impact the loading time on a slow network because the design picker already loads slower than other steps.

Because we load the `mShots` image from an inlined `background-image` added with JS, it can be solved by loading a 2x image when we detect that screen supports a higher pixel ratio with [window.devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio).

As mentioned in the comments above, we could try to change the implementation to `<img>` tags wit the attribute [srcset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset) to load the `mShot` images responsively.

Just for reference, when images are loaded using CSS selectors, we can use media queries [-webkit-device-pixel-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-device-pixel-ratio) and [resolution](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution) to load a 2x image only on screens that support a higher pixel ratio:

```css
@media print,
  (-webkit-min-device-pixel-ratio: 1.25),
  (min-resolution: 120dpi) {
    div {
        background-image: url("mShots &w=1200");
    }
}
```

cc: @Automattic/ganon

**Comment by simison** [comment]
Size should help; we're loading 600px image in 400px container now, depending a bit on browser width, which isn't enough for retina screens.

Another thing you can try is png format that [mShots now supports](https://github.com/Automattic/mShots/pull/74) — this was added specifically for Link in Bio design picker (pbAok1-3fx-p2#comment-5394).

KBs are something to watch out for though — it's a bummer we don't have Webp support in mShots.

Here's a quick comparison between png and jpg — open bigger to see properly. There's an improvement but image size should help, too. Something else I'd try is loading way bigger than 2x image (try 3-4x) but with quite a bit lower jpg quality. Then scale that down. That trick works well with photos, and usually not so well with text, which themes have quite a lot.

<img width="1326" alt="Screenshot 2022-12-14 at 10 39 59" src="https://user-images.githubusercontent.com/87168/207547862-afb34821-f096-4fc7-a7b4-da89ca7988e0.png">
<img width="1324" alt="Screenshot 2022-12-14 at 10 39 44" src="https://user-images.githubusercontent.com/87168/207547873-830afa67-b884-4e15-897e-e6350fdd7303.png">

**Comment by fushar** [comment]
I put on my detective hat 🕵️ today to investigate this issue and I think I got to the bottom of it.

I believe, this was a regression when we replace the original (Site-Setup) Design Picker with the Unified Design Picker (PR: https://github.com/Automattic/wp-calypso/pull/65534). We used to render hi-res design thumbnails. See the following difference:

|Site-Setup Design Picker|Unified Design Picker|
|-|-|
|packages/design-picker/src/components/index.tsx:<br><br><img width="654" alt="image" src="https://user-images.githubusercontent.com/1525580/211553545-5fc33785-8465-4eab-a0fd-7b3480f1ccca.png"><br><br>client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx:<br><br><img width="623" alt="image" src="https://user-images.githubusercontent.com/1525580/211554281-def8a5a2-81e3-453f-9f2b-c143cb3e9738.png">|packages/design-picker/src/components/unified-design-picker.tsx:<br><br><img width="658" alt="image" src="https://user-images.githubusercontent.com/1525580/211554087-953f3bf4-3a91-4022-8e34-4bdaed12f6ce.png">|

This is the commit in the PR that hard-coded `highRes` to `false`: https://github.com/Automattic/wp-calypso/pull/65534/commits/2e81297c8edf1844bf20574503e7a7c35d5ad835

<img width="925" alt="image" src="https://user-images.githubusercontent.com/1525580/211556277-4bf63def-740c-47c5-a6d1-8d56650a09a1.png">

Adding @roo2: was this simply an oversight?

---

To see the original Design Picker, I've put together a PR which disables Unified Design Picker: https://github.com/Automattic/wp-calypso/pull/71848. You can click on the Calypso Live link on that PR and go to the design picker step. Verify that the mShots images are hi-res (`w=1199`).

---

So I guess the proper "fix" for this issue is to just simple pass `true` to the `highRes` prop correctly as per the original behavior. Any objections? If not I'll implement this :)

**Comment by fushar** [comment]
This is shipped.
