### ISSUE TITLE
2FA: Retry failed scenarios on authentication

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#69718]
### Details

On https://github.com/Automattic/wp-calypso/pull/69460, we implemented a mechanism to prevent the loading of a query that depends on 2FA if the user is not yet authorized. We would like to check the existing 2FA-required scenarios and adapt the logic to automatically retry or not render components that depend on 2FA depending on the current user status.

### Checklist

- [x] Analyze all scenarios where we're using the `<ReauthRequired />` component for retries
- [ ] Wrap 2FA-protected components/routes so they're not rendered if 2FA is pending
- [ ] Retry 2FA-protected queries once the user is authorized

**Comment by vykes-mac** [comment]
@zaguiini after analysing where `<ReauthRequired />` is used in the codebase, I don't see much benefit to refactoring those components:

**1**. As the images show, I think having the UI loaded with the placeholders behind the reauth dialog is a better experience. 

![image](https://user-images.githubusercontent.com/47489215/207116319-ae311af9-ca2f-4f19-8357-37496dec1893.png)

![image](https://user-images.githubusercontent.com/47489215/207116485-2364fdab-f1e2-4184-8b1d-6981334d4eb4.png)

**2.** I didn't see any benefit in terms of network calls since most of the calls happen on global state and results pass down as props so the network call happens even before the UI is shown. If it was a case where the network call is coupled with the component then it would save us making unnecessary network calls.

I think for future components that encapsulate network calls, wrapping those components with 2FA make sense, but refactoring the current ones I don''t see much benefit because of how the make the network calls.


Areas where `<ReauthRequired />` is used:
```
client/blocks/get-apps/mobile-download-card.jsx
client/my-sites/hosting/sftp-card/index.js
client/me/social-login/index.jsx
client/me/notification-settings/comment-settings/index.jsx
client/me/notification-settings/reader-subscriptions/index.jsx
client/me/notification-settings/main.jsx
client/me/notification-settings/wpcom-settings/index.jsx
client/me/security-account-email/index.tsx
client/me/privacy/main.jsx
client/me/security-checkup/index.jsx
client/me/security/main.jsx
client/me/concierge/main.js
client/me/security-account-recovery/index.jsx
client/me/connected-applications/index.jsx
client/me/two-step/index.jsx
client/me/security-ssh-key/security-ssh-key.tsx
client/me/profile/index.jsx
client/me/account/main.jsx
```

**Comment by zaguiini** [comment]
After some research made by Kenroy above, we decided not to pursue this.
