### ISSUE TITLE
Remove "Add User" button on the Followers tab of Simple sites

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#69768]
### What

Remove the `Add User` button on the Users page → Followers tab of Simple sites.

### Why

`Add User` button is only relevant on the Team tab for inviting people to the site with the other regular roles (Administrator, Editor, Author, Contributor, and Viewer (on private sites)).

On the Followers tab, we don't allow inviting Followers. Now we can only "invite" Followers from the Email Subscribers tab, on which if the customer adds an email subscriber, or uploads an email list that contains WordPress.com email addresses, respective users with a matching WordPress.com account email address will automatically become Followers.

So the `Add User` button on the Followers tab can be confusing as it gives the impression that we can add a Follower, which is not the case anymore.

Removing the `Add User` button on the Followers tab for Simple sites also brings the UI and functional parity with Atomic sites that don’t already show the `Add User` button on the Followers tab.

This is a follow-up to https://github.com/Automattic/wp-calypso/issues/69650. 

Reference: p1667474029045749/1666865636.011679-slack-C02FMH4G8

**Comment by ouikhuan** [comment]
Hi @happychait , instead of removing the "Add User" button on the Followers tab for simple sites, we decide to keep it and redirect it the Email Subscribers tab, so the proposed change here will be:
1. You'll still see the `Add User` button on the Followers tab on Simple sites.
2. Once you click the button it will brings you to the Emails Subscribers tab.

Could you prepare the doc for this updated behavior if needed? Please let me know if you have any other questions, thank you!

**Comment by ouikhuan** [comment]
I'm closing this issue because it's being addressed in #70083
