### ISSUE TITLE
Post Featured Image block has no options to change sizes

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#69811]
### Quick summary

I am not sure if this is intended, but on the FSE Russell theme, the default Single template includes a Post Featured Image block to show the image but it has no adjustment settings to change the image height. The default look crops most of the image and since there is no way to change it, it is limiting. 

![vYEqwcaWJjHowQc05DdwcQVhKeNGyuYFx5xjwLqO.jpg](https://user-images.githubusercontent.com/84539773/200189743-5571b5a5-e009-49c0-a9b4-e1783a23a57e.jpg)

The workaround is to use Cover Block instead.

### Steps to reproduce

1. Russell theme
2. Site editor > Single Template
3. Post Featured Image block

### What you expected to happen

It would be possible to adjust the image with settings similar to the Cover block.

### What actually happened

There are no settings to change it.

### Context

Ticket: 5688663-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

I think this is an FSE thing, but I only tested Russell

### Workaround details

Use a Cover block instead in the Single Template.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Replicated**
- Replicable on Core? **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated in several themes and across AT, Simple, and Self-Hosted. 
- **Post Featured Image** block, at least in the `Single` Template, comes with little to no good resizing options. 

**Examples**

**Simple Site, Russell Theme**
<img width="1312" alt="Markup 2022-11-15 at 18 58 05" src="https://user-images.githubusercontent.com/27249804/202065336-bdc2c4a4-65ed-45a6-8db7-20cfb60e750d.png">

**AT Site, Masu Theme**
![Markup on 2022-11-15 at 19:03:40](https://user-images.githubusercontent.com/27249804/202065608-8a0309e4-4e20-4a5a-82d7-4d81da99d0cd.png)

**Self-Hosted Site, Twenty Twenty Two Theme**
<img width="1431" alt="Markup 2022-11-15 at 18 59 36" src="https://user-images.githubusercontent.com/27249804/202065378-fa05b76a-30c6-4334-bf64-23a81ffe7d67.png">


📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Added to HE Cross-repo Watchlist

📌 Message to Quality Squad
**Added Context:** Resizing the Post Featured Image on the Single template is a very common request I see come in from users, and frequently, I find myself helping them 'constrain' the block by nesting inside of columns, or swapping it out for the Cover block so they can control the height. 

Also, this seems more like a feature request rather than a bug, but for now I'll leave it labeled as both so y'all can decide. I can't quite make sense of the /gutenberg issues that are addressing this, but it's definitely being discussed! Any insight y'all can offer for future HE's who come across this would be great. Here's what I dug up:

- https://github.com/WordPress/gutenberg/issues/38990
- https://github.com/WordPress/gutenberg/issues/33789
- https://github.com/WordPress/gutenberg/pull/38044
     - This pull request indicates there should/will be Height and Width settings added to the Dimensions, but those are not currently available on WordPress.com yet, at least not in any of the themes tested above.

**Comment by csabarakasz** [comment]
another case: 37726151-hc

In the meantime, I created this issue as well which is somewhat related to this. https://github.com/Automattic/wp-calypso/issues/70458 Since user's are not able to edit the Post Featured image block, they are using cover block, but when the cover block is using the featured image as media, the Fixed background settings is not shown.

**Comment by drsdre** [comment]
This issue seems to be related if the Post Featured Image is used within a query loop (shows Image Size) or outside as is on a 'single' template.

It's important to have the image size controls for Post Featured Image available in both contexts.

**Comment by karenroldan** [comment]
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Low` to better reflect its status in the larger context of open bugs in this repo.
- Looks like the linked core issues are already closed, so this `Needs retest` to confirm.

**Comment by annezazu** [comment]
https://github.com/user-attachments/assets/51c4c29c-df6e-4b35-817a-78d6b7a76f8a

Closing this out as I can't replicate using WordPress 6.6.1! Of note, it was originally added thanks to this PR: https://github.com/WordPress/gutenberg/pull/38044
