### ISSUE TITLE
Marketplace: Yoast SEO Premium shows as inactive if purchased directly from Yoast

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#69973]
### Quick summary

If Yoast SEO Premium is purchased from Yoast directly, then it will show as **Inactive** on the Plugin Marketplace. 

<img width="595" alt="Screenshot 2022-11-13 at 1 06 51 pm" src="https://user-images.githubusercontent.com/21261509/201503807-26687477-ac92-4ac6-a29e-31a8a4869fd1.png">

### Steps to reproduce

1. Download Yoast SEO Premium directly from their site: https://yoast.com/wordpress/plugins/seo/
2. Install it on AT WordPress.com site.
3. Search for `yoast` in Marketplace.
4. It will display as **Installed** but **Inactive**.

### What you expected to happen

Expected **Yoast SEO Premium** to show as **Active**.

### What actually happened

**Yoast SEO Premium** shows as **Inactive**.

### Context

5706530-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Skipped testing on a test site since this would require a purchase from Yoast, but I can confirm this is the case on the site from the user report.

📌 FINDINGS/SCREENSHOTS/VIDEO
- I checked the site from the user report and I see that Yoast SEO Premium has an Inactive label in Calypso, even through the plugin is active. 
- I also noticed that if you click the plugin, there is still an option to purchase Yoast SEO Premium in the WordPress.com Marketplace. It would be great if there were some kind of check so that instead of an option to purchase, it showed that the plugin is already installed and active.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cpapazoglou** [comment]
Backlog grooming:
- we will revert using the `Inactive` status for plugin that don't have an active subscription
- active / inactive should only depend to the actual plugin status reported from the API
- in plugin details page, if there isn't an active subscription we will put a notice `Plugin subscription not found or you have purchased the plugin outside of [WordPress.com](http://wordpress.com/). Buy a WordPress.com subscription if you want to receive updates and support.`
