### ISSUE TITLE
CPT / Editor: Add New Project Type Module disappears when project auto-saves 

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#7023]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/edit/jetpack-portfolio/$site
2. Add a project title
3. (Quickly) open up the Add New Project Type module
4. With module open, watch the project automatically save and the module disappears

#### What I expected

I expected the module to remain in view and allow edit, the way it does with regular Posts

#### What happened instead

The module disappears without saving changes

#### Screenshot / Video

https://cloudup.com/cGV_7XI8rAI

**Comment by timmyc** [comment]
Just adding in some notes as I'm testing this out.  It appears when the auto save happens, or save is clicked manually there are five render calls made to `<EditorDrawerTaxonomies />` where a `postId` is present, but the value of `getEditedPostValue( state, siteId, postId, 'type' )` is `undefined` and `getPostTypeTaxonomies( state, siteId, postType )` is also `undefined` which is resulting in the flicker, and the issue reported here since there are renders where there are no `taxonomies` to render.

**Comment by aduth** [comment]
@timmyc Might be a result of this sequence of dispatch calls after a save which would cause the edited type to be temporarily removed?

https://github.com/Automattic/wp-calypso/blob/a09c8b1/client/post-editor/post-editor.jsx#L685-L688

**Comment by timmyc** [comment]
Ha was just looking at those lines of code, that kind of jives - will know more soon :)
