### ISSUE TITLE
Subscriptions: Unable to use saved card as the payment method

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#70264]
### Quick summary

The user on 3813665-hc wasn't able to use one of their saved credit cards as the payment method for their subscriptions. I was able to reproduce this issue from their account but not from my account, where I have a Brazilian cc. This seems to be localized and related to Ebanx as I noticed the error message: `existing-card-ebanx`

### Steps to reproduce

1. Go to Purchases and click on any subscription that doesn't have a payment method.
2. Try to set the existing card and the new payment method. You might see the `Use this card` button.
3. On their account, the button did nothing, and I saw the error message below from the console.

![add_payment_method](https://user-images.githubusercontent.com/50875131/203177958-468fe257-aa55-4729-b6d0-80521629843a.png)

The user tried from a different browser, but the issue persisted.

### What you expected to happen

Expect the user to be able to use their credit card.

I also can't find any details about this issue on Payment Admin.

### What actually happened

Nothing. Browser freezes. No error message is shown to the user.

### Context

Same brazilian user on 5731481-zen and 38136655-hc.

### Reproducibility

Consistent

### Available workarounds?

No but the platform is still usable

**Comment by sirbrillig** [comment]
For reference, the error message is `No payment processor found with key: existing-card-ebanx` and it's triggered by an onClick handler, so it's probably from here:

https://github.com/Automattic/wp-calypso/blob/8b455ceaf7b462e1a0e2a25216361f45abe97cbf/packages/composite-checkout/src/components/use-process-payment.ts#L28-L30

There is a payment processor function defined with that key in checkout:

https://github.com/Automattic/wp-calypso/blob/8b455ceaf7b462e1a0e2a25216361f45abe97cbf/client/my-sites/checkout/composite-checkout/components/checkout-main.tsx#L483-L484

However, this bug is appearing in the add payment method form, not in checkout, and that form indeed is missing that processor:

https://github.com/Automattic/wp-calypso/blob/8b455ceaf7b462e1a0e2a25216361f45abe97cbf/client/me/purchases/manage-purchase/payment-method-selector/index.tsx#L164-L182

**Comment by cuemarie** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
- Given @sirbrillig 's notes above and the new https://github.com/Automattic/wp-calypso/pull/70265 request, it looks like this is already on it's way toward a resolution!

📌 ACTIONS
- Marked as Triaged for Quality Squad review
