### ISSUE TITLE
[Bug]: Two-year plan upsell in checkout gets cut off if the browser window is too short

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#70298]
### Quick summary

As reported at p1668537497002199-slack-CT1FP5D62, the upsell nudge for two-year plans in checkout can get cut off vertically, if your browser window is too short.

This is most likely to happen with a monthly plan and domain in the cart (since the content above the nudge is taller then) but in theory could happen for anything.

Example (in this screenshot you can see via the left column that I've scrolled all the way down, but since the right column isn't scrollable, it's still not fully visible):

![two-years-upsell](https://user-images.githubusercontent.com/235183/203377928-15c73799-23de-4c17-ad49-8379d531bff7.png)

@michaeldcain suggested solving this for the monthly case by just removing the two-year upsell (since it duplicates the probably more-relevant annual upsell a bit further up in the sidebar).  This is probably a good idea, although it wouldn't necessarily solve the more general bug in the case of an even-shorter browser window.

### Steps to reproduce

1. Put a non-two-year plan in your shopping cart.
2. Adjust the height of your browser window until you see the bug.

### What you expected to happen

Either the right sidebar content is short enough to fit on my screen, or it is able to scroll.

### What actually happened

The content was cut off.

### Reproducibility

Consistent

**Comment by sirbrillig** [comment]
Two ideas from the hangout:

1. Add `overflow-y: auto` to the sidebar area so that it can scroll if needed.
2. Add a CSS breakpoint to the upsell that says to hide it (or shrink it in some way?) if the viewport is desktop width (so the sidebar is visible) and has a vertical height that's smaller than roughly 800px (we don't know exactly the size because the higher-placed boxes in the sidebar are variable-sized). Or even compare the viewport height to the sidebar height somehow.

However, this is probably an edge case and therefore low priority right now.

The only part that may be a higher priority is the monthly view since that's somewhat more common. Hiding the upsell in this case could solve that issue, although for the majority of users that probably don't have this bug that will hide a 2-year upsell which could have a revenue impact.

**Comment by sirbrillig** [comment]
~This will probably be fixed by https://github.com/Automattic/wp-calypso/pull/70315 which removes the upsell.~ Nevermind, we've decided not to remove the upsell just yet to reduce the variables for an AB test.
