### ISSUE TITLE
Support disconnect and cleanup 

### ISSUE THREAD

**Issue by mpkelly** [Automattic/wp-calypso#70382]
### Details

Create the "Disconnect" UI and do the necessary cleanup via the API. The GitHub connection belongs to the user and might be used across many sites. So this clean-up should only stop `push` event updating the Atomic site. 

![connected_branch](https://user-images.githubusercontent.com/6851384/205395112-8e884b79-9678-4ac2-9c52-2c80d9be47de.png)

### Checklist

- [x] ~UI looks like mockup~ Slightly different UI p1675811699694899/1675811625.450599-slack-C04H4NY6STW
- [x] Works for RTl
- [x] ~Removes webhook for push notifications~ Uninstalls GitHub app (which will remove any webhooks)
- [x] Updates the server-side state to reflect the disconnected state. 
- [x] Removes `access_token` from the server, so that the Authorize flow must be completed again to connect
- [x] Once disconnected, the page should show the Connect UI added in https://github.com/Automattic/wp-calypso/issues/70378
- [x] Remove any webhooks we create in the repo.

**Comment by p-jackson** [comment]
App can now be cleaned up, and when it is deleted from Calypso it will uninstall the app in GH.

todo:
- When app is uninstalled in GitHub we should respond to the appropriate webhook and delete on our site

will not do:
- we don't unauthorise the oauth portion of our permissions. This is something that the P2 app hasn't figured out how to do either. It might be an exercise for a future iteration, or perhaps we shouldn't ever clean it up. If user A installs the app then they also authorise it for oauth APIs too. If user B uninstalls the app, is it really appropriate for them to be revoking another users oauth tokens?

**Comment by zaguiini** [comment]
We should also remove the webhook that we created in the repo.

**Comment by p-jackson** [comment]
I've updated the acceptance criteria to include cleaning up the hook.

Technically if we were using the GitHub app to it's fullest then we wouldn't need to install a hook per repo and we wouldn't be polluting the user's webhook list at all. Apps can have their own webhook that isn't visible to the user, that's why GitHub advertise one of the advantage of the app is approach is that you don't need to worry about leaving webhooks behind. https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/differences-between-github-apps-and-oauth-apps#webhooks

But this will involve re-jigging how our whole webhook system works and doesn't need to be done to show a proof-of-concept i1 working. We should be able to clean up the webhook we create.

**Comment by p-jackson** [comment]
The webhook now gets removed D102269-code
