### ISSUE TITLE
Reading Settings: Add “Related posts” site setting

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#70412]
![Image](https://user-images.githubusercontent.com/2019970/203962754-953b36ac-f06f-4a95-8fca-1b7246093694.png)

#### Acceptance criteria:
- To be placed following "Blogs post" setting under "Site settings" section
- To apply site settings as expected
- To mirror the behavior of the setting that is currently out in production

##### Getting settings
Endpoint: `GET /site/%s/settings`
Relevant settings from response body:
- `jetpack_relatedposts_allowed`
- `jetpack_relatedposts_enabled`
- `jetpack_relatedposts_show_headline`
- `jetpack_relatedposts_show_thumbnails`

##### Saving settings
Endpoint: `POST /site/%s/settings`
Relevant settings to be included in the payload:
- `jetpack_relatedposts_enabled`
- `jetpack_relatedposts_show_headline`
- `jetpack_relatedposts_show_thumbnails`

Relevant conversation: pdDOJh-15W-p2#comment-806, pdDOJh-15W-p2#comment-845

**Comment by mashikag** [comment]
@saygunnyc can you review the Acceptance criteria I wrote up for the task please. 🙏  Perhaps you may want to get familiar with the conversation related to the setting that took place in one of mine p2: pdDOJh-15W-p2#comment-806 . 

If you agree with all points can you help to come up with the copy to be displayed as a disclaimer why the setting is disabled for users with block based theme applied? Also would you be able to tell to which support resource we should point to?

**Comment by mashikag** [comment]
Mind that this task has a potential to be further broken down into 3 tasks:
1. The classic themes version of the settings
2. Disable the setting for block based themes
3. Add a disclaimer for when the setting is disabled

**Comment by saygunnyc** [comment]
I had a back-and-forth with this one: 

Is there a case where the user might have previous posts created via the classic editor, then switched to a block-based theme, so this setting as is (if we were not to modify) can actually affect the previous posts? Or is this setting completely useless once after the user switches to a block-based theme? 

Because if that's possible (I wasn't able to test), then I'd suggest keeping the setting as is and perhaps adding the [Related Posts Block](https://wordpress.com/support/wordpress-editor/blocks/related-posts-block/) information and support link to the existing disclaimer.

**"These settings will impact all related posts on your site, except for those you created via the block editor. If you'd like to add related posts to your posts or pages on a block-based theme, you can add a Related Posts Block by clicking on the Add Block button.** **[Learn more.](https://wordpress.com/support/wordpress-editor/blocks/related-posts-block/)"**


Part of my confusion/hesitation also comes from those settings that will still be accessible on the classic settings. _–wp-admin_

Let me know your thoughts!

**Comment by mashikag** [comment]
Finding out these questions will help us decide how we can improve the Related Posts settings.
1. How do you determine if a user is on block-based theme?
2. How do you determine if the related posts module is enabled or disabled on Atomic & Jetpack?

Scenarios include:
- User on block-based themes so the settings are irrelevant, what to show?
- User on Atomic/Self-Hosted with related posts disabled, what to show?
  - Maybe this is equivalent to the Show/Hide toggle.

**Comment by mashikag** [comment]
I have double checked that the jetpack's settings API already exposes all the required settings (this is not 100% true, I will explain later), and allows for updating them. Therefore no changes to the API are needed. 

#### Settings API
##### Getting settings
Endpoint: `GET /site/%s/settings`
Relevant settings from response body:
- `jetpack_relatedposts_allowed`
- `jetpack_relatedposts_enabled`
- `jetpack_relatedposts_show_headline`
- `jetpack_relatedposts_show_thumbnails`

##### Saving settings
Endpoint: `POST /site/%s/settings`
Relevant settings to be included in the payload:
- `jetpack_relatedposts_enabled`
- `jetpack_relatedposts_show_headline`
- `jetpack_relatedposts_show_thumbnails`

___ 
There is actually one option missing, i.e. `show_date`. However as the MVP version, or at least for early CfT time, I believe we should release by re-using the setting component implemented in **Tools > Marketing > Traffic**. The component is missing the setting.
![Screen Shot 2022-12-23 at 13 27 41](https://user-images.githubusercontent.com/2019970/209336673-9ac44c4b-3641-4489-8cac-8ad5bd614c72.png)

I will create follow up tasks to expose the `jetpack_relatedposts_show_date` option and to add the toggle to the setting.

cc @yansern

**Comment by mashikag** [comment]
The code for the **Related posts** react setting component, from **Tools > Marketing > Traffic**, can be found in: 
`client/my-sites/site-settings/related-posts/index.jsx` ([go to the file](https://github.com/Automattic/wp-calypso/blob/6d0de5ad965a673a444afcd026f19e2b01e3023d/client/my-sites/site-settings/related-posts/index.jsx)).

It looks like it should be an easy job to implement it in the new Reading Settings page.

**Comment by mashikag** [comment]
I created the following two tasks as a follow up to this:
1. https://github.com/Automattic/wp-calypso/issues/71593
2. https://github.com/Automattic/wp-calypso/issues/71594
