### ISSUE TITLE
PurchaseMetaPrice assumes english language terms

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#70549]
`PurchaseMetaPrice` contains a switch statement that looks at the contents of the `billPeriodLabel` on the purchase to decide what term to show.

https://github.com/Automattic/wp-calypso/blob/7f68bb845d543a8f1ac8ea8602300a7d8be63c1a/client/me/purchases/manage-purchase/purchase-meta.jsx#L300-L311

However, `billPeriodLabel` is localized for the user's language, so the switch statement will fail for non-EN languages. It must be replaced. 

In theory we could change it to compare the strings against translated versions of the cases, but that might not be reliable since the translations are coming from two different places (`billPeriodLabel` comes from the backend). 

Better would be to use some other property, either a number or a code, to determine the term length. 

This code was added by https://github.com/Automattic/wp-calypso/pull/65006 for Marketplace products specifically although it is used for all kinds of products.

**Comment by JessBoctor** [comment]
From planning: 

This was a temporary solution that was not updated. It needs to be replaced, but we need to do some research into why it was added originally. 

@WBerredo Can you please provide insight into what we might break when we edit this or if there's a better way to handle it?

**Comment by WBerredo** [comment]
This switch is only removing the `"per"` part (on the English version) because there is already a `/` doing the same job. One option would be to remove the `/` and use the actual value of this variable as it is already localized. But there is a potential localization issue with this if there is a language which wouldn't work with the construction `"${price} per year"`.

Another option I see is to use the of `purchase.bill_period_days` and create a `switch` based on the period of days of each plan. I would say this is a safer solution.

**Comment by michaeldcain** [comment]
From planning:

> Another option I see is to use the of purchase.bill_period_days and create a switch based on the period of days of each plan. I would say this is a safer solution.

Let's do this.
