### ISSUE TITLE
Podcast episodes not appearing in the feed

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#70621]
### Quick summary

* The last two podcast episodes are not appearing on apple in this podcast feed generated by WordPress - <<ULR REMOVED>>
* While the episode details are there, they are missing the enclosure tag ie the media file itself

### Steps to reproduce

1. Look at the RSS feed - https://SITEURL/category/podcast/feed/
3. Look for the latest episode <<PODCAST TITLE>>
4. There is no enclosure tag.
5. This is what it should look like (previous episode) <<IMAGE URL REMOVED>>
6. So there is no file for Apple to read
7. the problem occurs on the last 2 episodes

### What you expected to happen

The enclosure tags to be there

### What actually happened

The enclosure tags are not there

### Context

5728798-zd

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

**Comment by jenlynnemc** [comment]
Noting that the user had reached out to Apple and received this reply:
Hello Joshua, Thank you for contacting us. We appreciate your patience while we work to answer emails as quickly as we can!

We have taken a look at your podcast and it appears it is not getting through the validator for the storefront. The image in your RSS feed is listed as a .png, however, when the image is read/downloaded, it does so as a .webp which is a format our validator cannot read. As a result, the podcast doesn’t get updated on Apple Podcasts.

To fix this, please ensure the image in the RSS feed downloads as a .png or .jpg. Once it does so, you should see your episodes start appearing within 24 hours!

If you have additional questions related to this request, please reference case number 101872681197.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Await author feedback

📌 Message to Author
- @rickmgithub based on your report, can you recommend any steps to replicate this?
- If not, this may be better suited for an internal report on 2EDhh-p2 rather than in this public Github repo, given the user data. 
- With that in mind, please also take a moment to edit the report/comment above to remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

**Comment by vajrasar** [comment]
I went ahead and drafted this issue report (in original form) on 2EDhh-p2 as pointed by Marie. And, I pinged Rick on Slack to check the issue and publish the report on 2EDhh-p2 if required. I'm closing this.

And, I removed the user-specific information from the issue here.

@rickmgithub if required please feel free to reopen the issue.
