### ISSUE TITLE
Slideshow play/pause button rendering outside frame

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#70734]
### Quick summary

User in ticket has multiple Slideshow blocks on homepage where the Play/Pause button consistently renders outside the slideshow image frame, then relocates inside the frame as expected when the page is refreshed.

### Steps to reproduce

1. Load homepage in browser.
2. Scroll down to slideshow blocks.
3. Note pause button location.
4. Reload page.
5. Note pause button's new location.

### What you expected to happen

The play/pause button should render within the slideshow image frame.

### What actually happened

Button appears above the slideshow, then corrects its position when page is reloaded.

### Context

Customer report: 5759701-zd-woothemes

Bad image: ![image](https://user-images.githubusercontent.com/79414372/205452870-57e23fcc-3470-4359-aad2-6a84b2a92258.png)
Good image: 
![image](https://user-images.githubusercontent.com/79414372/205452894-3687fec9-2f8d-437d-8d2e-e4909e237c72.png)

### Platform (Simple, Atomic, or both?)

Atomic

### Browser, operating system and other notes

Reproduces consistently in current versions of Chrome, Safari, and Firefox.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Button appears in correct location after reloading page.

**Comment by ghost** [comment]
Not sure if this is the same issue, but slideshow is not rendering the pause button or right arrow button on live view. Workaround doesn't solve the issue here. No plugins on site, not atomic.
5770120-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- No steps to replicate provided. I created 3 auto-playing slideshow blocks on an AT site using an FSE theme, inside of a 3-column columns block, as the user in the original report has done.
- The slideshow block in my test site rendered the play/pause button at the top corner of the slideshow block, with no change after refreshing.

The only way I was able to see the button appear above the image was if the slideshow also contained a portrait style image with greater height than the other images, as shown below:

**AT Example**

https://user-images.githubusercontent.com/27249804/208790705-d206044f-cf99-4190-8c1b-8eac24ee8764.mp4


📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @the-misha , were you able to replicate this issue outside of the user's site? If there's no way we can reproduce the issue, this may need specific plugin/site troubleshooting for further investigation. 
- @lunasera41 Thanks for highlighting that! The issue you've brought up appears to be a separate issue than the one reported above. Can you file that through butomattic please?
- For HE's playing into the ticket 5759701-zd-woothemes, please replicate the issue to reopen this report, or report internally for further investigation. If we can replicate it and reopen, then please work to close the ticket with the customer instead of keeping it on hold. 

Thanks all!
