### ISSUE TITLE
Data Layer: Allow `null` responses from the API

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#70790]
In https://github.com/Automattic/wp-calypso/pull/70480#issuecomment-1329980914, we discovered that the data layer borks on `null` responses from the API.

As it turns out, this is probably a bug! p1670277810543499/1669734008.636179-slack-C7YPUHBB2

We should fix it up 💪

**Done is:**
* The data layer properly handles `null` responses from the API.
* We have tests so we don't run into this issue again (you're welcome to steal https://github.com/Automattic/wp-calypso/pull/70531)

**Comment by dmsnell** [comment]
## Notes from the investigation

When #18733 was [rebased](https://github.com/Automattic/wp-calypso/pull/18733#event-1304062099) and 5df42036292d4c93002472cb76dda087555cfc9d turned into 73ac6cb185b54615b2d1e3d480d827d054223374, that rebase incorporated #18543, which fixed this very issue.

Unfortunately, because #18733 presented a semantic conflict but not a textual conflict, it wasn't observed that the behavior on the underlying `dispatchRequest` function had been updated, and those updates didn't make it into the new `dispatchRequestEx` function.

Because #18733 was adding a new function, even though it traced its code back to the original `dispatchRequest` function, the `diff` _only_ showed adding new lines. There was nothing it was actually removing and so it wasn't obvious _from the diff alone_ that we were removing the handling for empty responses.

New code started operating without the fix and then, in #29355, the original `dispatchRequest` function was removed and the new one took its place. This removed the fix from the unused code path and left the bug in Calypso ever since.

*Proposed solution*: bring back the fix that @withinboredom originally introduced in #18543.

cc: @jsnajdr (guess we all missed that at the time we merged #18733)

**Comment by wojtekn** [comment]
I opened an initial PR https://github.com/Automattic/wp-calypso/pull/70821.

@dmsnell, thanks for providing more details on the issue history. I implemented a fix as proposed and added tests for new cases.

@danielbachhuber I've tried to build upon the draft PR you created, but it seems that those tests from `index.js` do not call the `createRequestAction` action.

**Comment by danielbachhuber** [comment]
> I've tried to build upon the draft PR you created, but it seems that those tests from `index.js` do not call the `createRequestAction` action.

Sounds good! We can punt on my PR
