### ISSUE TITLE
Marketplace: Vendor access token not found when sending webhook

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#70855]
The vendor access token cannot be found when trying to send a webhook due to most of the access tokens don't have a user_id attached to them.

**Comment by JulianBustamante** [comment]
Diff created D94524-code

**Comment by gavande1** [comment]
Deployed r257456-wpcom to prevent errors. We still need to find a solution for this.

**Comment by cpapazoglou** [comment]
Let's try to see if we can backfill the User Ids related to the access token

**Comment by gavande1** [comment]
This is happening because jobs run in an async environment. Due to that, the job loses access to `get_current_user_id()`. We probably need to pass the user id received in the request object to the job at the time of queueing it. 

I think, we should also backfill user ids for the already issues marketplace access tokens.

**Comment by gavande1** [comment]
The issue has already been resolved in diff D101277-code
