### ISSUE TITLE
Domains: Transfers: Copy update for wait period and name server change

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#7090]
Per conversation in p7DVsv-9B-p2, I'm proposing we add some copy to the domain transfer screen. Here's an example of what I have in mind:

> Please note that transfers can take up to x days. You may want to [update your name servers](link) before initiating the transfer. 

<img width="744" alt="screen shot 2016-07-27 at 2 19 23 pm" src="https://cloud.githubusercontent.com/assets/3011211/17189209/209e57a2-5406-11e6-9782-3907a0cc0b38.png">

cc: @ranh for copy feedback.

**Comment by ranh** [comment]
I'd change even more:

> Transferring your domain means it will be removed from your WordPress.com site and moved to your new provider. The transfer can take up to two weeks to complete.
>
> To begin, we have to unlock your domain and remove Privacy Protection. If you proceed, your contact information will become available in the domain’s public records.

Any more details about changing the name servers before the transfer?

**Comment by wensco** [comment]
> Transferring your domain means it will be removed from your WordPress.com site 
This may cause confusion since we retain the domain mapping once a registration is transferred out so in effect, the domain still resolves to their WordPress.com site.

FYI, we're working on a related adjustment to prevent registrants from trying to make name server and contact info changes while a domain is pending transfer since they fail.

Maybe something like this for that second paragraph? (noting that 2 weeks for a gTLD transfer is a mighty long time; ccTLDs are another matter)
"Please note that transfers can take up to two weeks. While your transfer is in progress, you will not be able to change your registrant contact information or the domain's name servers. If you need to make changes, please do so before starting the transfer."

**Comment by ranh** [comment]
@wensco How about: 

> Transferring your domain can take up to two weeks. During this time, your domain will be unlocked and your contact information will become available in the domain's public records. 
>
> Domain settings such as name servers and contact information cannot be changed during the transfer. If you need to make changes, please do so before starting. 

This removes the part you said was confusing and still hopefully covers all the details to consider before starting the transfer.

> (noting that 2 weeks for a gTLD transfer is a mighty long time; ccTLDs are another matter)

Not following you here. Can you expand on that? Do you think we should be showing different times? I don't actually remember ATM what I basing the "two weeks" on, so do correct me if I'm using bad data.

**Comment by wensco** [comment]
@ranh your edits look good to me. :)

Regarding the comment on the 2 weeks time period, most gTLDs transfer pretty seamlessly and within a week - sometimes less. I would rather overestimate the time period and have someone pleasantly surprised when it's faster than the inverse of that and have someone frustrated.

It's a completely different story for ccTLDs. Transfers for those can take longer and can require a lot of manual intervention and special processes. The requirements vary by TLD. I just mentioned it so that we're aware that one time frame fits _most_ of the TLDs currently registered through WordPress.com accounts but not all. If memory serves, we had a different flow for those since quite a few of them don't use EPP codes and have other special processes.

**Comment by ranh** [comment]
Would it make sense to adapt this based on the domain in question? "Transferring your domain will take about a week" for gtlds, and whatever the relevant time period is for each cctld.
