### ISSUE TITLE
Stats: Remove "Unknown Search Terms" from the Search Terms stats module

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#70963]
![Image](https://user-images.githubusercontent.com/4044428/206553929-2b92a5b7-9c10-428b-81a7-1d35f65306c7.png)

Reported [here](https://github.com/Automattic/wp-calypso/pull/70857#issuecomment-1341716249). It may be simpler to remove this from the API endpoint instead of the interface.

**Comment by annacmc** [comment]
> It may be simpler to remove this from the API endpoint instead of the interface

I've been looking into the API endpoint to see about removing this from there instead of the interface. I've had a play round with a lot of different approaches to see what might work best. Currently, the endpoint is returning:

```
'search_terms'           => $terms,
'encrypted_search_terms' => $encrypted,
'other_search_terms'     => $other,
'total_search_terms'     => $total,
```

In this case, what we are considering as "unknown search terms" is the `encrypted_search_terms` data. It is then being normalized over in a Calypso `utils` file into the `Unknown Search Terms` 

If we stop this from returning the encrypted search terms, the `total_search_terms` result will also need to be updated

I want to double-check check, though... do we have a use for that encrypted search term data elsewhere or in the future that I'm missing? I haven't found anywhere else that's using it currently. But just erring on the side of caution here as the world of stats is still very new to me! 

AFAIK the next best alternative would be to stop using the `encrypted_search_terms` (and potentially the `other_search_terms`) when we gather that data from the endpoint. But keep it there in the endpoint as it is, in case we want to use it for something else instead. 

So just checking in with @jsnmoon and @Automattic/red for what everyone thinks about this encrypted search term count data.

**Comment by jsnmoon** [comment]
@annacmc: Let's try removing `encrypted_search_terms` handling within Calypso's `utils` as our first stab at tackling this issue. Could we also get a better understanding of how `other_search_terms` is being used?

We may have use for `other_search_tearms` and `encrypted_search_terms` in the future. I can't say when, though 😉

**Comment by annacmc** [comment]
Ok perfect! Thanks @jsnmoon I'll give that direction a stab and look into the 'other_search_terms' more closely as well. Really appreciate the guidance!

**Comment by annacmc** [comment]
> Let's try removing encrypted_search_terms handling within Calypso's utils as our first stab at tackling this issue. Could we also get a better understanding of how other_search_terms is being used?

It looks like `other_search_terms` is not currently being used anywhere. In the endpoint it's calculated using

```
$other = $total - $shown;
```

so it looks like perhaps it's a fallback/catchall for any remaining terms which are not being shown for whichever reason. However I've spent a while looking through both the endpoint/wpcom and calypso repos and there's no sign of this being used or output currently (that I can see) 

cc @jsnmoon

**Comment by jsnmoon** [comment]
@danjjohnson: We intend to remove the "Unknown search terms" item from the "Search terms" section [as recommended by our designers](https://github.com/Automattic/wp-calypso/pull/70857#issuecomment-1341716249):

> I think your approach makes more sense visually, but from a functionality standpoint, there's nothing customers can do with this information at this point. It really only serves to confuse people.
> 
> I think I'd opt for removing it completely [...]

This change will look like the following:

|Before|After|
|-|-|
|<img width="411" alt="image" src="https://user-images.githubusercontent.com/4044428/210017971-ac6a8ac4-cd1a-43e9-9244-7c78d3fe57f4.png">|<img width="408" alt="image" src="https://user-images.githubusercontent.com/4044428/210017954-dfccb2fd-4fd5-4712-9605-d34e9e222672.png">|

**Comment by danjjohnson** [comment]
@jsnmoon thanks for the ping. My only concern is that customers may find it useful to know that 353 visitors came via search, even if they don't know the search terms. In the after view it looks like they only got 8 visitors via search.

**Comment by jsnmoon** [comment]
> @jsnmoon thanks for the ping. My only concern is that customers may find it useful to know that 353 visitors came via search, even if they don't know the search terms. In the after view it looks like they only got 8 visitors via search.

That's also my concern, but this will reduce customer queries on what "Unknown search queries" are while making the stats dashboard more actionable.
