### ISSUE TITLE
Posts: Ellipsis menu in Posts list is missing padding

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#71007]
We discovered (https://github.com/Automattic/wp-calypso/pull/70928#pullrequestreview-1209972363) the ellipsis menu in the posts list sometimes is all of the way to the right:

![image](https://user-images.githubusercontent.com/36432/206731434-2d48d423-c916-47bb-9d06-db632973d17a.png)

[However](https://github.com/Automattic/wp-calypso/pull/70928#issuecomment-1344172769):
> This doesn't look related to browsers. I reproduce the issue in all browsers but only on environments other than production and staging. It seems that additional CSS code is loaded for `.button.is-borderless` on those environments, and it resets padding to 0.

**Done is:**
* The padding appears as expected in all environments.

**Comment by wojtekn** [comment]
Thanks for adding this @danielbachhuber . 

More details from my quick debugging - that additional CSS is loaded using the URL:
https://wpcalypso.wordpress.com/calypso/evergreen/async-load-calypso-lib-account-settings-helper.7ab0d3ed7ced20534e45.min.css

The file responsible for that CSS block is:
https://github.com/Automattic/wp-calypso/blob/trunk/client/jetpack-cloud/style.scss#L148

The issue is gone when I remove those two padding calls, but I'm not sure if it's a proper fix - we may need to check it on the Jetpack Cloud side and ensure we don't break anything there.

I'm still curious why this is loaded on dev environments and not on staging and production.

**Comment by wojtekn** [comment]
> I'm still curious why this is loaded on dev environments and not on staging and production.

It's loaded as a part of Dev Tools on local and wpcalypso environments:

https://github.com/Automattic/wp-calypso/blob/6822bcdaae9dd4a96a5fc52a6fd86a8779684d25/client/lib/load-dev-helpers/index.js#L5

Still not sure why this CSS includes `client/jetpack-cloud/style.scss`.
