### ISSUE TITLE
Stats: Detail Page(s) - Summary Pages

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#71018]
# Development

- [x] Apply horizontal bars to the stats list.
- [x] Restyle the period type selector.
- [x] Ensure that all detail pages have been updated.
- [x] Verify that all additional items are present on the page, for example, CSV export option
- [ ] Align `Videos` to the other pages and apply horizontal bars

Additional tasks:
- #72131
- #72132

# Design

Each summary page we have needs a slight redesign. These pages will mostly utilize components we've already built elsewhere in stats, so we shouldn't need dev specs... but if we do, let me know!

These pages are accessed when a user clicks "View all" or "View details" at the bottom of cards on the Traffic and Insights pages.

_Note: There are many summary pages, so we may have to adjust designs if we find any special use-cases_

### Two before / after examples

**Country summary**

![Image](https://user-images.githubusercontent.com/214813/206773895-0a51a63a-2efe-46cb-817c-7dbceb4ce491.png)

**Posts & Pages summary**

![Image](https://user-images.githubusercontent.com/214813/206774216-2a412de1-b0f0-4fa1-b41a-9c8602f24f11.png)

**Comment by grzegorz-cp** [comment]
As part of modernising the Insights page, we'd like to create a summary detail page for `Tags & categories`.

**Comment by grzegorz-cp** [comment]
While working on #71638, I discovered three special cases for the summary page - [details](https://github.com/Automattic/wp-calypso/issues/71638#issuecomment-1381180070).

`Authors` and `File downloads` need investigation of the API to check if we can update it to apply the standard header available on other summary pages.

`Videos` need more guidance or a new design because the table exposes multiple values, not only views.
An alternative approach could drop all of the additional values. While this could be useful for the `watch time`, which is often `>1h`, it would be a shame to remove `impressions`.
If we keep all the values, we may improve `watch time` by providing an exact time.

It's also a shame that the users can't sort the table by `impressions`. This sorting should be easy to implement on the client side, but it would beat the purpose of the horizontal bars, which are affected by views. A toggle option could help here (similar to some of the components on the new Insights page designs), but this has to be discussed further.

**Comment by jsnmoon** [comment]
> - Create a summary page for Tags & categories
> - Extend API for Authors and File downloads to accept different periods and restore the header visible on other summary pages (propose an alternative if the task is too time-consuming)

@grzegorz-cp: I propose we queue up these two tasks as follow-up tasks in separate issue(s) since they are much larger in scope than the other tasks specified here. What do you think?

**Comment by grzegorz-cp** [comment]
Good idea to split it up.

**Comment by grzegorz-cp** [comment]
I created a PR to update the last remaining summary page, but it turns out that `Videos` needs the same API extension as #72131 because it doesn't have the period navigation.

**Comment by jsnmoon** [comment]
@grzegorz-cp: What are your thoughts on marking this issue as complete and tracking the Videos summary page updates in a separate task?

**Comment by grzegorz-cp** [comment]
@jsnmoon, that is a good idea. 
I'll create a separate issue for updating the API endpoint to enable to unified header with period selection buttons.
