### ISSUE TITLE
Theme Showcase: Inform users about placement change of Current Theme

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#71040]
## Description

Ready for dev to pick up and start conversation about how to improve this. 

As brought up in p7DVsv-fVu-p2#comment-43213, with the new Theme Showcase i4 work there is a disconnect between the new user experience, and our educational material. One of the biggest changes in our latest Theme Showcase iteration is that we have changed the placement of where users can see their current theme. See #70326 for more context.

| Before | After |
| --- | --- |
| ![Screen Shot 2022-11-23 at 6 47 43 PM](https://user-images.githubusercontent.com/797888/203527933-c8462701-9040-4e6d-8dc3-24a8d484113b.png) | ![Screen Shot 2022-11-23 at 6 48 15 PM](https://user-images.githubusercontent.com/797888/203528047-f450d3b0-7a5f-48f2-aaf9-fc3c745fcf69.png)

As a result, it's important that we inform users about this UI change.

## Acceptance Criteria
- [ ] Work with @SaxonF towards an approach to inform users about this UI change.
- [ ] Ask @ianstewart and @tanjoymor to review the proposed approach.
- [ ] Implement the approach.

**Comment by arthur791004** [comment]
I think maybe we can add a new entry point called `My Theme` under the `Appearance`. When people click on it, you can just show them a theme detail page. What do you think?

**Comment by autumnfjeld** [comment]
I think your idea is worth pursuing @arthur791004 , I'd suggest a slack conversation in #dotcom-marvel or a P2 to see if there is any reason not to do this.  Since it is a change to the sidenav I'd want to make sure we have agreement form a wider audience than just Lego. ;) 

When we talked about this in 1:1 you called out some specific use cases of why having "My Theme" under Appearance is needed:
* users who come thru an onboarding flow that has a theme chosen for them, like LIB, Newsletter
* users who go thru Write flow 
* users who skip the DP and get default theme

These cases are important to call out in your support for this new menu item. :)

**Comment by autumnfjeld** [comment]
I think this work is now old enough we can close this issue.  Do you agree @taipeicoder ?

Perhaps @arthur791004 's https://github.com/Automattic/wp-calypso/issues/71040#issuecomment-1512496347 is worth moving to own issue.

**Comment by taipeicoder** [comment]
We can close this one since we have a new direction as discussed in pekYwv-2VT-p2#comment-2317
