### ISSUE TITLE
Bundled Plugins: Atomic sites activating bundled themes produce unexpected results

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71215]
**Steps to reproduce**

1. Visit `/themes` on an Atomic site (*.wpcomstaging or custom domain) that already has WooCommerce activated
2. Activate a theme that bundles WooCommerce (like Tsubaki or Tazza) - click the three-dots menu and Activate, or visit the theme's page and click Activate 
3. You'll be prompted to choose whether to replace your home page content -- doesn't matter which you choose, pick one and click Activate
4. You'll be redirected to `/setup/plugin-bundle/getCurrentThemeSoftwareSets?siteSlug=[siteSlug]`, then to `/home/[siteSlug]`

**What I expected to happen**

To have the theme activate, stay on the Theme Showcase (or at least direct me back to it), and display a notice similar to this:

<img width="411" alt="Screen Shot 2022-12-14 at 3 21 03 PM" src="https://user-images.githubusercontent.com/2124984/207705846-3a7adda4-735c-444d-9fa4-a4283188e749.png">

**What happens instead**

https://user-images.githubusercontent.com/2124984/207705466-542629f8-4d1e-4ad5-bee8-62f3388bf295.mov

**Comment by daledupreez** [comment]
I am seeing differently bad behaviour, at least for sites on the eCommerce trial -- I get stuck on the processing step where we're trying to install WooCommerce, but it's already installed.

I think we need to verify this is actually working for sites that are already on an eCommerce plan or have WooCommerce installed already.

**Comment by daledupreez** [comment]
I think we hit this issue in testing here: pdtkmj-182-p2#comment-2021
I've bumped priority on Serenity's sprint board, as this may be impacting users who already have WooCommerce installed.

**Comment by markbiek** [comment]
I did a bunch of testing and it's definitely failing in the plugin-bundle flow on the API call to install WooCommerce (`/wpcom/v2/sites/:siteSlug/atomic/software/woo-on-plans`). 

That API call always returns `applied: false` (presumably because WooCommerce is already installed) and the flow eventually times out and fails.

The obvious fix to me is updating the plugin-bundle flow to check if WooCommerce is already installed and skipping that step.

**Comment by markbiek** [comment]
I have no idea what's changed. I've been working on this all day and, at some point in the last couple of hours, I've stopped having to go through the plugin-bundle flow for Tsubaki or Tazza.

It seems like maybe something changed elsewhere but the initial `GetCurrentThemeSoftwareSets` step redirects to `/home` with a `Redirected because theme has no bundled software` message.

Assuming this is real and not some weird fluke, it's a good thing. Then we just need to fix the `ThankYouModal` to show the activated theme messsage (we're currently still redirected to the `wc-admin` launch checklist).

At the moment, I'm _not_ seeing the same behavior on `wordpress.com` so I'm leaning towards something weird on my local dev.

**Comment by daledupreez** [comment]
When I switch to a WooCommerce-enabled theme, I am seeing the following:
 * When starting the flow, I am being prompted to fill in my store address despite it already being filled in.
 * When I complete that step, I am shown the businessInfo step, which is almost certainly unnecessary for eCommerce stores.
   - Trying to skip the businessInfo step brings me back to the storeAddress step. 🙃 
 * Then we get to the processing step where we try to call the `atomic/software/woo-on-plans` endpoint.

I am wondering if we simply want the logic for the flow to simply check if WooCommerce is already installed as a first step, and skip all the other steps if it is.

**Comment by markbiek** [comment]
> I am wondering if we simply want the logic for the flow to simply check if WooCommerce is already installed as a first step, and skip all the other steps if it is.

Agreed! That's the approach I've been taking.

I've done more testing and I think my local just went haywire yesterday. The last 2h of the day, it was skipping the plugin-bundle flow entirely without any code changes.

This morning, I'm back to seeing the behavior you described above.

**One small tricky thing**
Even after we skip the plugin-bundle flow, I'm assuming we want to show the normal "Thanks for activating :themeSlug" modal after activation (otherwise it'll go to the WooCommerce launch checklist).

That means we need to be able to tell the `ThanksModal` that the site already has WooCommerce installed so it doesn't do the redirect to `/home`.

This is tricky because the Stepper and the theme showcase are using two different methods for handling state (`packages/data-stores` vs `client/state`) and there isn't a great way for us to set state in Stepper that's then accessible to the theme showcase.

My two ideas currently are:

1. A query string argument that we set when we exit the plugin-bundle flow.
2. Checking for WooCommerce from inside the `ThanksModal` (_I don't really like this idea_).
