### ISSUE TITLE
Site Editor: Add Location-Aware Snackbar on Load

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#71274]
When navigating into the Site Editor, the user might not be aware of what kind of document is being edited — especially if unfamiliar with the Site Editor UI.

We should display a snackbar providing information about the current document when entering the Site Editor.

For example:
- "Editing the Index template"
- "Editing the Footer template part"

_Originally requested in https://github.com/Automattic/wp-calypso/issues/68953_

**Comment by mmtr** [comment]
I think this needs a broader discussion across different teams. Gutenberg did some changes to improve the Site Editor UI such as the new navigation mode (which is active by default upon loading the site editor) that helps users to acknowledge what they are editing:

![image](https://user-images.githubusercontent.com/1233880/217004219-d4d84f52-fa32-4cfb-8f7a-0ca58bbc84e4.png)

However, that navigation mode is completely skipped / hidden in dotcom, apparently because of conflicts with the Link in Bio flow: p9Jlb4-6ad-p2 / https://github.com/Automattic/wp-calypso/pull/72339.

I agree that, for certain flows, users should enter the site editor completely focused on what they expect to edit (i.e. it's ok to bypass the navigation mode if the've clicked on an "Add links" button), but, for other flows, that might make the experience more confusing (e.g. users landing in the Site Editor after clicking in the Appearance > Editor menu).

**Comment by Copons** [comment]
IMHO, the navigation mode would have been enough to resolve this issue.
Even without snackbar notifications, the navigation mode requires intentionality from the user, reducing the chance of getting lost.

With Dotcom skipping the navigation mode, this is not exactly the case anymore.

I wonder how hard it would be to display the snackbar as suggested in a demo PR (or behind feature flag), and showcase it to the interested parties. 🤔
