### ISSUE TITLE
Anchor.fm integration: Selected theme from Design Picker is different from the actual theme

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#71334]
### Steps to reproduce

1. Connect WordPress.com from Anchor.fm 
2. In the onboarding flow, select a theme. Only **Gilbert**, **Hannah**, and **Riley** are available.
3. Go to `Appearance > Theme`
4. Observe the current theme set (in the video, the theme set was Mayland)
5. Click on the `Customize` button
6. Theme set from that page is now Spearhead 

See the attached video below for reference.

### What you expected to happen

The selected and actual theme should be the same.

### What actually happened

From `Appearance > Theme`, the theme that was set (Mayland) was different from what I selected (Hannah). 
From `Appearance > Customize`, the theme displayed was also different (Spearhead). 

https://user-images.githubusercontent.com/67279475/208456676-c3d93a7f-3508-410e-8c77-a2dbd3bc7552.mov

### Context

Found the issue when doing an empathy challenge where I connected WordPress.com from Anchor.fm 

Context: pciE2j-1Cl-p2

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

The issue happens when selecting from one of the 3 available themes when integrating from Anchor.fm:

1. Gilbert
2. Hannah
3. Riley

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by zachspears** [comment]
Unable to test due to issues with Anchor. I accidentally created an account on the wrong page, so I can't connect WordPress with the existing account and now I get the following error when trying to create another account:

> Unable to create account
> Sorry, but we were unable to create your account. Please refresh the page and try again, or visit [https://help.anchor.fm/hc/en-us](https://anchor.fm/https://help.anchor.fm/hc/en-us) so we can help you troubleshoot.

Leaving for another triager, but as a side note the Anchor integration process is a nightmare.

**Comment by cuemarie** [comment]
Replicating this issue is quite troublesome. Step 1 of the steps to replicate: `Connect WordPress.com from Anchor.fm` involves the following: 

1. Create a new Anchor.fm account
2. Publish a podcast episode
3. Accumulate **25 plays of the episode**
4. At this point, a banner will appear on the Anchor.fm dashboard prompting you to create a WordPress.com site, and the rest of the steps above can be followed. ( [WordPress.com guide here](https://wordpress.com/support/audio/podcasting/#create-a-site-from-your-anchor-podcast) ). 

I've taken steps 1 & 2, but it'll be a bit before we can get back to replicate this. In case folks on @Automattic/serenity already have test sites standing by, I believe they are the right folks to look into this next.

**Comment by cuemarie** [comment]
I've asked for a possible hand in getting this repro tested faster here: p1674076514699179-slack-C0Q664T29

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- In terms of triaging steps, these steps can be followed to get into the Anchor.fm -> WordPress.com flow: p1674076673851059/1674076514.699179-slack-C0Q664T29
- In the Design Picker, I chose theme **Hannah**, but my site has **Mayland** activated. 
- When I head to customize, the homepage doesn't look recognizably like **Mayland**
- Also, if I go to switch back to one of the recommended themes, none of them appear. My only options under the `Podcast` filter are **Quadrat** and **Spearhead.**

**Recordings**

https://user-images.githubusercontent.com/27249804/213299627-e6853685-c402-44d5-bf37-c6745937136d.mp4

https://user-images.githubusercontent.com/27249804/213299459-9da3a04a-37d3-4ce1-b77a-cc0df38e18d5.mov

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by valterlorran** [comment]
Closing this as we won't be able to work on it. - For more details, please see p7fD6U-9EZ-p2.
