### ISSUE TITLE
Lettre design looks off in the Design Picker

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#71439]
# Description
 See p1671645376874249-slack-C048CUFRGFQ

Screenshot from the Design Picker (looks odd)
![Image](https://user-images.githubusercontent.com/5665959/209030711-af7c9f81-542e-40bf-ad63-9262afc9d260.png)

![Image](https://user-images.githubusercontent.com/5665959/209030950-7007fba9-07c5-4157-a577-0ffc6cee0393.png)

Screenshot from the Showcase (looks better)

![Image](https://user-images.githubusercontent.com/5665959/209030884-1d91b6d7-7ba6-4195-9b8d-c64f13d8ea7b.png)

# Dev Tasks
- [x] investigate if the is an mShots issue or something else

**Comment by candy02058912** [comment]
I was playing around and changed these numbers randomly:
* `vph`: 1600 -> 800
* `w`: 600 -> 800

| Original  | Adjusted |
| :-------------: | :-------------: |
| <img src="https://user-images.githubusercontent.com/6586048/209955439-121ca1e7-91a5-4c72-9dfe-d451b62e43a9.png">  | <img src="https://user-images.githubusercontent.com/6586048/209955451-bcd7f4ca-bc24-4a5a-9d8f-1edd57c49170.png">|

Inside the Design Picker

| Before  | After |
| :-------------: | :-------------: |
| <img src="https://user-images.githubusercontent.com/5665959/209030711-af7c9f81-542e-40bf-ad63-9262afc9d260.png">  | <img src="https://user-images.githubusercontent.com/6586048/209954835-e8869472-b047-482c-84e0-18801b1ffd04.png">|

The settings are passed in [here](https://github.com/Automattic/wp-calypso/blob/trunk/packages/design-picker/src/utils/available-designs.ts#L52-L65).
The tricky thing is that I don't know if we tweak the settings, what will happen to the other designs and the layout.

Any suggestions on how we should approach this?

**Comment by simison** [comment]
I don't think this is a design or pattern problem — the problem is within mShots browser settings.

[Lettre](https://lettredemo.wordpress.com/) has a cover area which is set to `min-height: 90vh` i.e. the cover basically fills the browser viewport — that works perfectly well and as-designed in the regular browser, but with mShots Puppeteer browser you need to tell specifically screen dimensions you want because the "screen" and thus "viewport" would otherwise be full page height.

Currently we render with max 3600px height _page_, with [emulated _viewport_ height of 1600px](https://github.com/Automattic/wp-calypso/blob/d51680ca420d4027b39aa9ce5d0a606c46711f44/packages/design-picker/src/utils/available-designs.ts#L59-L60). Width is also set to 1600px, so we render as if browser window would be square:

<img src="https://user-images.githubusercontent.com/87168/209963300-5f7435fc-edd7-45f7-b2cd-5ead1d263335.png" width="400"/>


https://s0.wp.com/mshots/v1/https%3A%2F%2Flettredemo.wordpress.com?vpw=1600&vph=1600&w=600&screen_height=3600

If we reduce the vph to 900px in design picker, giving us a more common 1600x900px browser size, you get:

<img src="https://user-images.githubusercontent.com/87168/209963368-58e255c9-8bfd-46a3-b407-edb88f868fae.png" width="400"/>

https://s0.wp.com/mshots/v1/https%3A%2F%2Flettredemo.wordpress.com?vpw=1600&vph=900&w=600&screen_height=3600

In design picker this would render like so:

<img width="1508" alt="Screenshot 2022-12-29 at 15 42 45" src="https://user-images.githubusercontent.com/87168/209962832-f64a3efb-0c10-4617-8ed8-8992b6b4ae51.png">

Design picker originally [has perfectly fine viewport height 1040px](https://github.com/Automattic/wp-calypso/blob/dbc36b0b43c786bf509c3286b241a6f8a21b5b92/packages/design-picker/src/constants.ts#L59-L60) but later the height is [changed to higher 1600px](https://github.com/Automattic/wp-calypso/blob/d51680ca420d4027b39aa9ce5d0a606c46711f44/packages/design-picker/src/utils/available-designs.ts#L59-L60) to create a scrolling effect, while originally we should've probably increased the total page height instead to ensure percentage vph values continue rendering as intended. 

The fix in design picker should improve the situation for any other themes using % viewport heights as well.

**Comment by candy02058912** [comment]
After testing, `vph` 900 will have a line on the right like this:
![image](https://user-images.githubusercontent.com/6586048/210354130-17c7c01b-7837-40c9-836f-dfb95dc637ea.png)

Changing `vph` to 901 fixes the problem and won't produce that line on all of the current designs to this date.
