### ISSUE TITLE
Design Previews: The styles of the theme make preview weird

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#71513]
Referring to https://github.com/Automattic/wp-calypso/pull/71455#pullrequestreview-1229824064 and https://github.com/Automattic/wp-calypso/pull/71455#issuecomment-1364858277, the styles of the theme with variation might make the preview look weird.

For example,

1. TT3 with the "Whisper" style variation, the body of the theme has `8px` border width and it makes its content doesn't overlap with the outer element.

<img src="https://user-images.githubusercontent.com/797888/209494948-7ca851b7-6abd-4db6-9b16-b21546f6b506.png" />

2. Muscat with the "midnight" style variation. the computed font size of the heading text "Is this nice" depends on the viewport width, and it makes the value become `204px` and leads to the overflow.

<img src="https://user-images.githubusercontent.com/797888/209495013-f69e80ea-72eb-4d18-a1eb-8b49e5d4109b.png" />

**Comment by fushar** [comment]
I don't think this is caused by our design preview component. When I view my site using the mentioned themes on my real Android phone, they indeed look broken:

|TT3 Whisper|Muscat Midnight|
|-|-|
|![image](https://user-images.githubusercontent.com/1525580/210725043-f675b371-f51f-4899-8f5a-5f55f21f710d.png)|![image](https://user-images.githubusercontent.com/1525580/210725854-9f825f58-1a5d-4659-b1c9-26b07cd1a659.png)|

(Note that for TT3, I had to extend `Mindblown` to `Mindblownnnn` because my phone is not narrow enough to show the "bug")

Should we close this issue? Or is there really anything that we should fix?

**Comment by arthur791004** [comment]
I think we might need to ask designers to update those themes. Maybe we can transfer this issue to themes repo.

**Comment by fushar** [comment]
Created a new issue for Muscat: https://github.com/Automattic/themes/issues/6813.

**Comment by fushar** [comment]
For TT3, I'm not entirely sure myself. What is the intended behavior here?

**Comment by arthur791004** [comment]
I think we have nothing to do if the "Whisper" style variation wants to keep the `8px` border width
