### ISSUE TITLE
[UI] Changing site produces strange behavior

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#71523]
When you're inside the email open stats, and you use the menu on the left the bahavior is strange

Before: http://calypso.localhost:3000/stats/email/open/broddin.be/day/313?tab=unique_opens

Change site to Apex P2: http://calypso.localhost:3000/stats/email/open/broddin.be/day/newsite.domain.tld

(Post id changes to site name)

**Comment by JuanLucha** [comment]
This is a general problem in Calypso. The typical way to create the routes is to put the site slug at the end of everything, so the site switcher takes that into consideration. Our route has the site slug in the middle of the url, not at the end, and that's why it fails. 

I say it's a general problem in Calypso as we can see that behavior in other parts of the software. For example, if you go to `Comments` and then clicks on one comment, the url is `/comments/approved/[site-slug]/[comment-id]`. If you then switch the site, the same error happens, as the switcher expects the last url parameter to be the site-slug, not the comment-id. 

To me this is a problem of the account switcher functionality and not a problem of the email stats per se. We could change the url structure to have the site-slug at the end, of course. That's another option.

Any thoughts on this?

**Comment by yansern** [comment]
Seems like an easy fix to just shift the site slug to the end of the url.

**Comment by TimBroddin** [comment]
Agree with @yansern . If the site switcher is not flexible, we should change our routes to match what it expects. I can refactor this tomorrow morning.

**Comment by TimBroddin** [comment]
I have a PR ready, but there's another issue.

When you're at `http://calypso.localhost:3000/stats/email/opens/day/3625/<siteid>` and you change sites to another site, the URL changes to `http://calypso.localhost:3000/stats/email/opens/day/3625/<newsiteid>`.

However, the `postId` stays the same. Chances are slim that you want to view the stats of the post with the same id. I think we need to change this behavior to go to the main Jetpack Stats view when changing sites. 

I'm currently looking into a way to achieve this (probably using `componentWillReceiveProps` and comparing the old site slug and the incoming one).
