### ISSUE TITLE
Hosting Configuration: Remove overlay and make cards readonly instead

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#71599]
### Details

Part of pdKhl6-1th-p2.

On the Hosting Configuration page, if I'm not on Business plan or higher, I do not see any of the features I'm supposed to get once I upgrade:

![image](https://user-images.githubusercontent.com/26530524/210105371-547ec45f-888f-49bb-8a05-621bf4aa97b0.png)

A better approach would be to make the cards read-only with some copy indicating that it's available on the Business plan instead of hiding it behind this gradient. Please verify if we really want to do this before working on it.

### Done is

- [ ] I see what features I'll get before upgrading to the Business plan
- [ ] The cards are not actionable, but visible
- [ ] There's text indicating that I should upgrade to enjoy the feature

**Comment by p-jackson** [comment]
> Please verify if we really want to do this before working on it.

@zaguiini the design we've gone with from pdKhl6-1th-p2#comment-1811 includes the fade-out overlay. I'm going to close this issue but please re-open if you don't think this is verified enough yet.

I think the gradient is a pattern users will probably be familiar with. It reminds me of paywalls on newspapers. Iirc one reason we were considering removing the overlay was because it was preventing users from seeing all the features they'd get by upgrading. But the new upsell lists these features so that reason isn't relevant anymore.
