### ISSUE TITLE
Hosting Configuration: Describe premium features in the upsell nudge

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#71598]
### Details

Part of pdKhl6-1th-p2.

The current upsell nudge on the Hosting Configuration page is not attractive at all:

![image](https://user-images.githubusercontent.com/26530524/210105371-547ec45f-888f-49bb-8a05-621bf4aa97b0.png)

It tells me to upgrade but doesn't say what I'll get if I do 🤔 😅 

### Done is

- [x] I see what features I'll get before upgrading to the Business plan
- [x] There's detailed information for every feature so I'm sure of what I'm getting

**Comment by p-jackson** [comment]
Planning on using this design from pdKhl6-1th-p2#comment-1811, but without the price info.

![image](https://user-images.githubusercontent.com/1500769/210931599-16a6d20a-3ae1-43b6-a942-ddbdf18c03cb.png)

Explains the value proposition well.

**Comment by p-jackson** [comment]
I'm unsure about including the pricing info (see pdKhl6-1th-p2#comment-1836), so I'm going to submit my current WIP for review without adding it. Because it's gated behind an experiment no one will see the updated banner yet and I can add the price info in a follow up PR.

- [x] Add new banner variation behind A/B test #71750
- [ ] ~Add price information~ https://github.com/Automattic/wp-calypso/issues/71833
- [ ] ~Finalise copy~ https://github.com/Automattic/wp-calypso/issues/71832
