### ISSUE TITLE
Gutenberg Plugin prompts to Upgrade Plan rather than Install and Activate on Simple Business plan sites

### ISSUE THREAD

**Issue by mrmurphy** [Automattic/wp-calypso#71614]
### Quick summary

I purchased a business upgrade earlier today to support custom CSS on https://mrmurphy.blog. Aside from popping up a toast twice that upgrading from my plan wasn't supported, things seemed to work.

I purchased the upgrade using credits.

Now, visiting the gutenberg plugin page, I'm told that I have a "free" account, and prompted to upgrade.
I repeat the upgrade, using $300 in credits.
I navigate back to that same gutenberg page, it says I'm still free. I click the upgrade button and am offered an upgrade again. I see that my balance of credits has been reduced from the last purchase.

### Steps to reproduce

1. Visit https://wordpress.com/plugins/gutenberg/mrmurphy.blog
2. See that it tells me I'm "free"
3. Upgrade, using credits
4. Visit that page again, see it still says "free"
5. Try to make the purchase again

### What you expected to happen

That plugin page would recognize that I'm already a business user. But even if it didn't, the platform wouldn't let me repeat an upgrade to business when I'm already on business tier.

### What actually happened

See all above.

### Context

See above.

### Platform (Simple, Atomic, or both?)

Simple

### Browser, operating system and other notes

Safari 16.1, Mac OS

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- To replicate, I took the following steps: 

1. Open a Simple test site on the WordPress.com Business plan
2. Navigate to https://wordpress.com/plugins/gutenberg/ on this site
3. See that I'm prompted to "Upgrade", rather than install and activate the plugin

<img width="1352" alt="Markup 2023-01-13 at 14 19 16" src="https://user-images.githubusercontent.com/27249804/212412003-cefd7447-3889-42af-8822-5e515ff32361.png">

By comparison, when I open another free plugin, like Health Check & Troubleshooting, I'm prompted to Install: 

<img width="1352" alt="Markup 2023-01-13 at 14 21 21" src="https://user-images.githubusercontent.com/27249804/212412163-6659a974-3df6-461e-a4fd-b8288664d042.png">

To make matters more confusing, on the Plugins Search page in Calypso on this same site, Gutenberg is listed as **Installed** and **Active**!

<img width="1278" alt="Markup 2023-01-13 at 14 22 27" src="https://user-images.githubusercontent.com/27249804/212412366-44662bcd-5c98-46a3-8bb8-51e5b49b2427.png">

(the same happens on simple sites with lower plans, as well): 

![Markup on 2023-01-13 at 14:23:57](https://user-images.githubusercontent.com/27249804/212412561-1d1f03fd-1c91-4ce3-b4ba-0a6536c0256b.png)

Best summary for this issue from my tests is that the Gutenberg Plugin is displaying confusing messaging on WordPress.com sites. Will highlight this internally as well.

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Escalated here for visibility: p1673641781742569-slack-CBTN58FTJ
