### ISSUE TITLE
Pattern Assembler: Add a site option to ID assembler sites in a8c tools

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#71988]
# Description

As a first iteration, let' only add a site option to identify the sites that click on the Blank canvas CTA and complete the Assembler step to create their site.

* site option: `wpcom_site_setup = assembler`

This will be used in filtering in Site Snapshots, site quality analysis, data analysis, and possibly downstream in calypso UI.

The query for the options of all sites in `wpcom` must be done in the table `wpcom/blog_properties` in Hue. Something like:
```
select distinct blog_id from wpcom.blog_properties
where wpcom_site_setup = assembler;
```

# Acceptance Criteria
- [X] Be able to filter sites by the option  to know the count, URL, etc...
- [X] Be able to know when a site is created with the Site Assembler flow in Calypso, in MC tools like the Blog Report Card.

# Dev Tasks
- [X] Set the site option `wpcom_site_setup=assembler` for newly created sites, expect for virtual themes
- [x] Document the option `wpcom_site_setup` somewhere

# Testing 
* Create a new site and access the PA flow
* Click "Continue" to complete the PA flow
* Go to `/wp-admin/options.php` in your site to confirm that option `design_type: assembler` is there

## Related
p1673503178795799/1673498055.131429-slack-C048CUFRGFQ
https://github.com/Automattic/dotcom-forge/issues/1430

**Comment by autumnfjeld** [comment]
Maybe we should discuss this more widely.   I'm not sure `design_type` is good.   For example we might want to use language that encompasses a broader idea.  That could be used for LIB, Newsletter, Build, Write, Assembler.     I'm not yet sure.

**Comment by miksansegundo** [comment]
I like `wpcom_signup_flow`.

**Comment by autumnfjeld** [comment]
See p1675390590190449-slack-C014TPFLP4Z

I don't think it should include the word `signup`.   Should be broader, like it could include a site going through a theme switch.

Seems like your idea `design_type is popular in that slack thread.  Maybe `wpcom_design_type` ? 

cc: @Automattic/lego

**Comment by autumnfjeld** [comment]
Related comment left here https://github.com/Automattic/wp-calypso/pull/72989#issuecomment-1423742277

**Comment by autumnfjeld** [comment]
Let's check in with Nuria if this would be valuable for the launchpad. cc: @miksansegundo

**Comment by miksansegundo** [comment]
Moving this to the backlog until we find a reason to justify adding a site option to sites created through the assembler flow.

**Comment by autumnfjeld** [comment]
I think we are now at the point to execute on this site option.   Because of Virtual Designs using Blank Canvas and Virtual Designs will lead to the Assembler.  paYJgx-3ga-p2#comment-3417

And I believe we'll be following through with attaching an Assembler flow to all themes in the next couple months. It is on the roadmap (and @arthur791004  is working on a POC.

These new developments show the importance of the Assembler and the value of creating a site setting to mark sites that start with the Assembler.

If we go with `design_type` , what are the possible options it would have?

`design_type = assembler | standard | premium | third_party`

If that is what we'll want, we also will need to update the site option on theme switch.

@Automattic/lego  @Automattic/t-rex

**Comment by autumnfjeld** [comment]
See discussion thread here p1682479070766589-slack-C048CUFRGFQ

**Comment by mmtr** [comment]
> attaching an Assembler flow to all themes in the next couple months.

Does that this mean that in the future all sites will have a `design_type: assembler` option? If that's the case, will we still need a `design_type` option? I guess there might some flows that won't go through the assembler (e.g. mobile viewports, tailored flows), but maybe it is not worth to track/identify these?

**Comment by autumnfjeld** [comment]
> I guess there might some flows that won't go through the assembler (e.g. mobile viewports, tailored flows), but maybe it is not worth to track/identify these?

 I don't have strong opinions on that right now.  And I think the site option `intent` is already used to track LIB & Newsletter.   See p1675390590190449-slack-C014TPFLP4Z

> Does that this mean that in the future all sites will have a design_type: assembler option? 
 I don't see a scenario where all sites would be made from the assembler.  Some people will still pick pre-built themes or start with a default theme or go through LIB or Newsletter or some other yet to be created onboarding flow. 


Mostly I want to ensure that we tag sites that start out via the Assembler step.  We might also want to have some specificity to indicate they actually selected something in the Assembler step, they didn't just skip it or click Continue with nothing selected.   But I also don't want to overcomplicate this.

I am conflicted on if virtual sites should get the `design_type: assembler ` because they already have patterns/content.   

Perhaps what we should do is only tag sites with `design_type: assembler`  if user takes an action in the Assembler (any action, choosing a pattern, a color a font and that action is passed on the starter site). 

For example:
* User chooses Blank Canvas CTA (pure blank canvas)
* User does not do anything in the Assembler step (when they click Continue there is nothing to save)
* User gets a starting site that has no content, it is pure BC
* We would NOT record this site as `design_type=assembler` (maybe it is design_type=standard or no designation at all)


Similarly if a user chose a virtual theme, went to the assembler and then upon clicking "Continue" there are no changes, the site is NOT recorded as `design_type = assembler`. 

But I'm not sure that is a good idea.  It might be a bad idea.  🤔   Perhaps the best idea is to keep it simple? 


@miksansegundo  @arthur791004  @taipeicoder would love your input here.

**Comment by autumnfjeld** [comment]
Perhaps we classify VT on their own?

`design_type = virtual_theme | assembler | standard | premium | third_party`

**Comment by dsas** [comment]
> Perhaps what we should do is only tag sites with design_type: assembler if user takes an action in the Assembler (any action, choosing a pattern, a color a font and that action is passed on the starter site).

I think you're definitely onto something here 👍 

`design_type = virtual_theme | assembler | standard | premium | third_party`

I'd be interested to see VT there but I don't have a use case in mind, so it's not a strong need. In theory they are the same as any other theme.

**Comment by mmtr** [comment]
It looks that at some point all themes will be able to trigger the assembler flow (or at least standard, premium, and virtual – not sure about third party), so I wonder if'd be more flexible to have a separate `has_used_assembler` option and keep the `design_type` for the actual theme type (standard, premium, third party, maybe virtual theme), so we have a better picture about the theme type and whether it's been customized in the assembler.

> Perhaps what we should do is only tag sites with `design_type: assembler` if user takes an action in the Assembler (any action, choosing a pattern, a color a font and that action is passed on the starter site).

Is there any reason why we need to store this action in a blog option rather than using a Tracks event?

**Comment by miksansegundo** [comment]
For me the goal of this issue is identify sites that are set up with the assembler so we can:

1. know how many sites
2. know site details like their URL, etc...
3. customize the LaunchPad checklist and any other screen/section that we want on Calypso
4. show a section in the Blog Report Card to help HEs (let's get feedback from them on this to know what kind of info and tools would help them) 

As a first iteration, I'd only add a site option to identify the sites that click on the Blank canvas CTA and complete the Assembler step to create their site.

I'd call it something like `wpcom_site_setup_assembler` if it's a tag or `wpcom_site_setup: assembler` if it's an option.

@arthur791004 you mentioned in slack that you'd prefer using a internal site tag rather than a site option. What kind of tag do you mean? Can we query that kind if tag with Hue or how?

In next iterations, we can add this or other options to sites that complete their setup with Assembler step, such as:

- virtual themes: We can use the same tag because we always can filter by theme if we need to differentiate them.
- theme switches (not required for now but same idea as above)

**Comment by arthur791004** [comment]
Maybe something like `BLOG STICKERS`? I assume we can introduce a new kind of sticker to store this information for a site 🤔

**Comment by autumnfjeld** [comment]
>  Is there any reason why we need to store this action in a blog option rather than using a Tracks event?

Yes, that is why the issue is being actively discussed again.   
*  I'd like to have it for Site Snapshots filtering.   
* We want to be able to use a8c tools to ID these sites, so maybe also Blog RC as Miguel mentioned.
* We may want to use it the Launchpad to surface particular items, but that is a big unknown, and since it is an unknown it isn't a driver of this issue. We don't have any solid use cases or design plans that are about customizing calypso pages (LP or MyHome) but that is done with site option `intent=write`.
* It doesn't matter to me if it is a blog sticker or a site option as long as it can be used properly in site snapshots and the other possible use cases. 


We don't have any use cases for  `design_type = virtual_theme | assembler | standard | premium | third_party` outside of the assembler, so there is no point is creating it unless it is for the assembler use cases.   However I think these are interesting categories for analysis.

**Comment by autumnfjeld** [comment]
Site options can be surfaced in RC, but looks like it needs the page markup to be updated, as opposed to Blog Sticker surfacing automatically.

p1683161902068459/1683151859.189389-slack-C048CUFRGFQ
![image](https://user-images.githubusercontent.com/5665959/236086448-03f8b3e2-bf89-4167-b6b2-8f0307c229aa.png)

**Comment by autumnfjeld** [comment]
Let's keep it simple and  go with your proposal @miksansegundo 

> As a first iteration, I'd only add a site option to identify the sites that click on the Blank canvas CTA and complete the Assembler step to create their site.

* site option:  `wpcom_site_setup: assembler` 
* blog sticker: `wpcom_site_setup_assembler`   (if we want to also do a blog sticker)


I've updated the issue description and then get started on this in the next day or two?   Thank you!!! 😄

**Comment by miksansegundo** [comment]
We have deployed the [PR](https://github.com/Automattic/wp-calypso/pull/77426) that adds the site option `wpcom_site_setup` with the value `assembler` for newly created sites that complete the assembler flow, except for those using virtual themes.

For simplicity, we are doing it using the new assembler endpoint `/site-assembler` that removes headstart, which is still under a feature flag during testing. See https://github.com/Automattic/wp-calypso/pull/77152

Meaning that we'll have to wait until the new assembler endpoint is stable and shipped to users before we can use `wpcom_site_setup` for Hue queries or other purposes. cc: @autumnfjeld @taipeicoder

**Comment by autumnfjeld** [comment]
To repeat that back in my own words :) 
* soon all Assembler flows (LITS, DP, LOTS, implying usage for both simple & atomic site) will use endpoint /site-assembler for site creation
* the site option `wpcom_site_setup` is part of the [endpoint](fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfvgr%2Qnffrzoyre%2Sfvgr%2Qnffrzoyre.cuc%3Se%3Q7782n700%2384-og) 

👍

**Comment by autumnfjeld** [comment]
@miksansegundo We should update https://fieldguide.automattic.com/site-onboarding-flows/blank-canvas-pattern-assembler-onboarding-flow/  with this new information.  Both the new endpoint and the site option?

And when this goes live share a message in Marvel and ping Nuria because she had proposed ideas about conditional LP content based on PA, so this site option is of interest.  Maybe there are others to ping, we can discuss when it is live. :)

**Comment by miksansegundo** [comment]
Sure, let's update the FG pages to mention the new endpoint, the site option and add links for more info.

I'll also ping Nuria about using the option  in Launchpad.
