### ISSUE TITLE
[Bug]: TT3's design preview's style variations look cut in certain resolution

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#72055]
### Steps to reproduce

1. Open Calypso locally, or use staging/production with this flag: `?flags=themes/showcase-i4/details-and-preview`
1. Open `/theme/twentytwentythree` (or `/theme/twentytwentythree/{siteSlug}` if logged in)
1. Click "Open live demo"
1. Resize the browser width slowly until you see the style variations move to the top of the screen

@Automattic/lego 

### What you expected to happen

The first style (Aubergine) is not cut

### What actually happened

Only small part of the first style (Aubergine) is visible. There is no way to scroll to the left

<img width="840" alt="Screen Shot 2023-01-13 at 17 12 53" src="https://user-images.githubusercontent.com/1525580/212296107-4649b578-56ff-4d07-9ad9-e13b80867e48.png">

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 ACTIONS
- Added to Dotcom Bug Prioritization Board > Lego during some bug sweeps

📌 Message to Author
- Went to scrub, but at the moment I don't see a way to view the styles in the Live Demo. Not sure if I'm misunderstanding the steps to replicate, or if this isn't available right now and that's why this is backlogged. 
- If you'd like me to triage at any point, feel free to ping me!

**Comment by taipeicoder** [comment]
Fixed via #77333
