### ISSUE TITLE
Checkout: discounts not visible in dropdown when two/three years are selected

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#72057]
When trying to purchase a product for a Dotcom simple site, I'm seeing a weird behavior where the discount notice is not displayed.

This happens when two or three years are selected or, in other words, when I pick something else other than the default selection.

I _think_ I get the logic behind this: if I'm picking an increasingly more expensive plan, it doesn't make much sense to compare it to cheaper ones. However, wouldn't it still be valuable to highlight the savings for each billing period regardless?

#### One year

<img width="501" alt="image" src="https://user-images.githubusercontent.com/390760/212036197-22c91977-570d-4a80-bb91-5d08e11ddc2e.png">

#### Two years

<img width="497" alt="image" src="https://user-images.githubusercontent.com/390760/212036451-b9175c52-8d54-4ead-8159-0aa62873aebb.png">

#### Three years

<img width="498" alt="image" src="https://user-images.githubusercontent.com/390760/212036603-e843c272-a79a-4669-88ab-fe620551e92a.png">

**Comment by sirbrillig** [comment]
This behavior was intentionally added in https://github.com/Automattic/wp-calypso/pull/65998. The idea was that users were confused when seeing the savings in each variant if they were being compared to the lower priced variant instead of the currently selected one, especially when the dropdown was collapsed. You can see more discussion about this in pbOQVh-24K-p2

If we ever want to go back to the previous method of comparing the variant to the lowest priced variant, we created https://github.com/Automattic/wp-calypso/pull/66099 to do that.

We do have a newly designed radio button replacement for the dropdown variant picker currently being AB tested in https://github.com/Automattic/wp-calypso/pull/70315 which does compare the price of each variant to the lowest-priced variant since that comparison is more obvious in the radio button view when all the options are always visible. That experiment (pbxNRc-2ce-p2) is performing poorly, but we're planning to run another experiment soon with some variations.

**Comment by keoshi** [comment]
Thanks for the context and links, @sirbrillig !
