### ISSUE TITLE
LaunchPad - adapt and enable the back-to-launchpad modal in the post/page editor.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72093]
p2 CFT context - pdtkmj-WY-p2#comment-1549

Since work on the conflicting modal has not yet been started, lets enable our back-to-launchpad modal in the post editor as well.

Related to and may make sense to resolve with this existing issue in progress - https://github.com/Automattic/wp-calypso/issues/71717

**Comment by nuriapenya** [comment]
As the current modal has a very personalised copy for Link in Bio, I would propose changing the copy of this modal to make it more generic so that it can work with all the other flows/scenarios. How about:


`Great progress!`
`You are one step away from bringing your site to life. Check out the next steps that will help you to launch your site.`



![Launchpad - Modal Post Page](https://user-images.githubusercontent.com/7931304/212888287-b64611cd-fccd-4337-96ea-2754b853011f.jpg)

[Design in Figma](YTe1seBsKUaFPqjwiuqc7U-fi-1803%3A10967&t=kNFc2BC5iXd0mC6S-4)
