### ISSUE TITLE
Themes | Bug | Farrow | Changes in Editor not reflecting in live view

### ISSUE THREAD

**Issue by alevarsir** [Automattic/wp-calypso#72128]
### Quick summary

The user’s changes to the Footer template do not reflect in the live view but show correctly in the Editor view.

I tried using the same theme on my test site, and all changes to the templates/template parts (footer/header/page, etc.) do not reflect in the live view, although the changes were saved.

### Steps to reproduce

1.     Switch to the Farrow theme
2.     Go to Appearance > Editor (beta)
3.     Select a Template/Template part to edit and save the changes
4.     Check the page that’s using the template

### What you expected to happen

All the changes made in the Editor should be reflected in the live view.

### What actually happened

The changes did not reflect in the live view but showed in the Editor view

### Context

Footer template part changes: https://screencast-o-matic.com/watch/c0V22DVwzU2

Header/Page template changes:
– https://screencast-o-matic.com/watch/c0V22rVwzUU
– https://screencast-o-matic.com/watch/c0V22yVwzUN/c0V22yVwzUN

Console errors:
– https://prnt.sc/eEh9K2IqgcPe
– https://prnt.sc/PaVHTKKHjmbh

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Farrow

### Browser, operating system and other notes

Chrome and Firefox (latest versions)

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by filipanoscampos** [comment]
This looks like another case of this issue:
pd4QKa-It-p2
5871794-zd-woothemes

**Comment by aetta** [comment]
Possibly one more here: 5884480-zen - theme: Hari

**Comment by worldomonation** [comment]
Interesting. @cometgrrl suspected that this and https://github.com/Automattic/wp-calypso/issues/72118 were related, but I was able to reproduce this issue here while I was unable to do so for the other issue.

1. chose to replace the contents of my home page with contents of the Farrow theme.
2. edited the footer and added some text.

Observations:
- changes are not reflected in page preview from Calypso.
- changes are also not reflected when visiting the page.

Possible variables:
- the site is not launched.

Screenshots:

![Screen Shot 2023-01-23 at 1 33 42 PM](https://user-images.githubusercontent.com/6549265/214155119-bd3c4f22-b988-4594-85b7-759b885ebe94.png)
![Screen Shot 2023-01-23 at 1 33 18 PM](https://user-images.githubusercontent.com/6549265/214155132-920120c2-e297-413b-b715-b48dd520b381.png)

Response:
2edcf-pb/

**Comment by iamjohnrex** [comment]
same concern but with a different theme (Russell)
5866181-zen HC

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: Could not replicate
- Tested on Self-hosted: Could not replicate
- Replicable on Core? No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated this issue on **Simple** site only with Theme: **Farrow** and **Russell**

However, in both cases, reloading the page shows the edit to the template is removed. This matches what's been reported over here: #72684 

**Simple Example**

https://user-images.githubusercontent.com/27249804/216404082-76511e90-6976-40aa-96ae-8c8187001b36.mov

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/72684

📌 Message to Author
- Thanks for these reports! I'll share the specific cases on issue https://github.com/Automattic/wp-calypso/issues/72684
