### ISSUE TITLE
Convert tabs to a select on summary page for a small screen

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#72175]
After applying the new header style to summary detail pages, the period navigation buttons are too wide for screens between 320px and around 500px. The previous header was collapsing the controls to a select (below 480px).

We can improve the experience by restoring the select.

# Reference images
- broken controls on a small screen

![Image](https://user-images.githubusercontent.com/112354940/212763720-6c79a215-3a6c-4cf7-94b4-47a0780817e0.png)

**Comment by grzegorz-cp** [comment]
@jeffgolenski @keoshi Do you think collapsing to a select or a dropdown would be the best solution for this case?

**Comment by keoshi** [comment]
@grzegorz-cp Apologies for the delay here.

Jeff and I were discussing this very thing last week, although in a different context.

IMO it's totally fine to collapse the navigation buttons into a single dropdown in smaller screens.

**Comment by jeffgolenski** [comment]
@grzegorz-cp Absolutely. @keoshi actually mocked this up a couple months ago, but there's been a lot happening. Apologies if we didn't communicate this properly! Here's the mock. The drop down should sit above the timeframe headline, since that'll change depending on what period a user selects! 

![Detailed view - mobile](https://user-images.githubusercontent.com/214813/213021080-20b42dae-5833-4eb4-9795-24c43a881f57.png)
