### ISSUE TITLE
Mailpoet plugin page in wp-admin on an Atomic site has two help center icons but neither work.

### ISSUE THREAD

**Issue by cometgrrl** [Automattic/wp-calypso#72390]
On the Mailpoet plugin page in wp-admin on an Atomic site:

Two major issues:

- There’s a Zendesk widget in the bottom right that almost covers up our support widget… which should not be there at all, because the Help Center has taken its place.
- Help Center is indeed in the top/admin bar… but there’s two ? icons. And clicking on them actually does nothing.

Additional details at Audit of WordPress.com’s support flows -> pbvpgB-2BZ-p2 in the "obviously broken" section.

**Comment by renancarvalho** [comment]
> On the Mailpoet plugin page in wp-admin on an Atomic site
Hi @cometgrrl 👋 I am trying to reproduce this issue but I am not sure which page you meant, 
I have tried this one but it looks ok. Could you share more details about the issue ? I am happy to fix it :)

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/2653810/214262034-d8fe2b39-74d7-4850-92ab-04396a5bde60.png">

**Comment by renancarvalho** [comment]
Hi 👋 quick Update on this issue.
I have split this issue into two parts. First part is regarding the FAB button ( blue question mark ) and the second is the help center icons duplicated on header.

**Fab Button issue**
Here is a [PR to fix it](https://github.com/Automattic/jetpack/pull/28584). The issue was inside jetpack

**Duplicated icons on header/masterbar**

It happens because [help center scripts](https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit/editing-toolkit-plugin/help-center) are not being loaded at all, although I can see the [calls to load them](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php).I believe there is something overriding it, so far I did not find where.

**Comment by cometgrrl** [comment]
I updated the title to reflect the second issue, since the FAB button issue was fixed already.

**Comment by cometgrrl** [comment]
@renancarvalho / @alshakero Can Vertex follow-up on this?

**Comment by heavyweight** [comment]
This is no longer reproducible
