### ISSUE TITLE
Signup: Make domain search input use the same focus/active styles as other Calypso inputs

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#7249]
The domain search input in signup doesn't have an active/focus style:

![screen shot 2016-08-03 at 10 42 35 am](https://cloud.githubusercontent.com/assets/191598/17369627/0e014e4a-5967-11e6-8aed-cfee248975a3.png)

Its not at all obvious that the field is active, and that you (the user) should start typing to search.

**Comment by shaunandrews** [comment]
Its possible this is related to the search component in general, as no search inputs in Calypso have an active/focus state.

**Comment by klimeryk** [comment]
This is a great suggestion - as you've discovered, it's a deficiency in the `Search` component used throughout Calypso, not only in this case. It'd be great if we could implement it for `Search`, so that the whole app would benefit from it.
Looking through `wp-calypso`, there's one place where it has been done recently, the Themes Showcase. See [themes-magic-search-card](https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/my-sites/themes/themes-magic-search-card/index.jsx#L272) for the code and visit https://wordpress.com/themes/ to see it in action. Unfortunately, due to how `Search` is built, it's not as simple as adding a `border`, so this would require some designer input on how to integrate that approach with `Search`.
/cc @folletto @seear @budzanowski @ockham, the authors of the Showcase, in case there was a reason `Search` was not extended to have this advanced (😉) feature in the first place.

**Comment by mtias** [comment]
`Search` does have built in styles, they are triggered when using the keyboard: https://github.com/Automattic/wp-calypso/blob/master/client/components/search/style.scss#L48-L50

**Comment by folletto** [comment]
I'd note also that the "Magic Search" in theory was designed to replace the old one — we just didn't have time to do it properly and replace it everywhere in Calypso.

**Comment by klimeryk** [comment]
@mtias, thanks for pointing that out, I missed that. But I'm still confused why there's no border when focusing the field via a mouse click (or a tap)? Was that a design decision? It just seems inconsistent with how we treat other [input fields](https://wpcalypso.wordpress.com/devdocs/design/form-fields), hence my confusion :)
