### ISSUE TITLE
Site Assembler - Pattern fast preview component optimizations

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#72548]
## Description
The rendering is pretty snappy, but we wonder if this could be snappier.

## Are there any possible optimizations?

We could try some of the following:

 - use a virtual list (virtual scroll) to keep a low number of DOM elements
 - use infinite scroll to avoid rendering all the patterns in a category at the same time 
 - render the first patterns of each category in the background
 - render all patterns in the background
 - move some JS tasks to a web worker
 - load the pattern CSS in the iframe first and then the HTML
 - load the patterns in a category in small batches (3 at a time)
 - add an animation to show patterns with some delay, so they have time to load their CSS and images
 - cache the server requests 

##  How it works?

The fast preview component fetches the patterns HTML already rendered from the server and applies their CSS in an iframe in the browser.

https://user-images.githubusercontent.com/1881481/216924374-5dfec33d-a235-4a84-b10d-1d1adaa9887a.mov

https://user-images.githubusercontent.com/1881481/214501461-26cbc35e-43ab-4bbd-88d6-1c94a2fe83a1.mov

## Considerations

We should be aware of client-side performance issues caused by the following:

- blocking the UI because of too many synchronous JS tasks - tasks should be queued 
- lagging the UI because of having a large amount of DOM elements in the document  
- unnecessary renders
- memory leaks

## Questions

> Can we have these loading in the background somewhere continually while someone is browsing so that rendering just gets snappier and snappier in a session?

The loading time is now not caused by the server requests but by how the patterns are rendered in the browser. The pattern HTML and CSS are downloaded in the background, but they are rendered together at the same time that a pattern is displayed. 

> Can we cache all these so they render instantly?

We had a client-side cache for the server requests, it was removed because it caused an annoying issue only for developers. 

We could try to add a new cache system. Maybe using a browser service worker or a server-side cache using the site as a cache key. This won't make the patterns render instantly but will reduce the download time of the HTML & CSS. 

## Related

https://github.com/Automattic/wp-calypso/pull/71311

**Comment by arthur791004** [comment]
> use a virtual list (virtual scroll) to keep a low number of DOM elements
> use infinite scroll to avoid rendering all the patterns in a category at the same time

It would be great but I think we can hold it on. I assume the performance would be better after adding categories since there are not so many patterns in each category. But if we still feel a bit slow at that time, we can start to work on this one.

> render the first patterns of each category in the background

The downside is the rendering of the patterns in the last few categories might be blocked if there are too many categories. For example, if we have 10 categories and we want to preload 5 patterns from each category, the patterns in the last category need to wait for 45 patterns to be loaded. But it might be the edge case that the user scrolls down to pick the category at the bottom. The possible way might be preloading a few patterns when the user hovers over a category.

> render all patterns in the background

I don't think it's possible to load all patterns in the background if we have lots of patterns. Also, it takes up too much memory to load all patterns and it might lead the user's browser to crash 😅

> move some JS tasks to a web worker

In my opinion, the bottleneck is too many requests to load all patterns simultaneously. Some external styles are queued and need to wait for other requests. So, we have to reduce the number of unnecessary external styles or even transfer them into inline styles. I know it might increase the payload of the network request but it's good to have a try.

For JS tasks, the heavy ones might be generating styles based on the global styles of fonts & colors. But those functionalities are from Gutenberg and react hook, I'm not sure whether it is possible to deal with it by workers.

> load the pattern CSS in the iframe first and then the HTML

Yes, this can avoid showing unstyled content and I did it [here](https://github.com/Automattic/wp-calypso/pull/73077/commits/77e3a588f5fbe1bd97343a0c2e7c1dadc71cd9fe)

> load the patterns in a category in small batches (3 at a time)

If I understand correctly, you mean we can load patterns page by page. I think it's a great idea and it should be done by `useAsyncList`. But I feel like the `useAsyncList` doesn't behave as I imagine because it doesn't wait for the previous to be loaded 😅

> add an animation to show patterns with some delay, so they have time to load their CSS and images

Yes, we can use animations to make users not be aware of the loading time of patterns. We can do it when we cannot come up with any idea for optimizations.

> cache the server requests

The browser has already cached the external CSS. But the requests are still queued as there are too many requests. Thus, it might be better to load patterns one and one to avoid the requests being queued.

**Comment by miksansegundo** [comment]
Thanks @arthur791004 for reviewing all the points! You got everything right and I agree with all your comments. 

I also thought `useAsyncList` was going to do something more. Let's follow this Gutenberg [PR](https://github.com/WordPress/gutenberg/pull/48085/files) that proposes changes to `Prevent pattern previews from rendering in parallel due to React's concurrent mode`

Here is another related Calypso PR [Replace LazyRender with intersection observer library](https://github.com/Automattic/wp-calypso/pull/56154).

**Comment by arthur791004** [comment]
> Let's follow this Gutenberg [PR](https://github.com/WordPress/gutenberg/pull/48085/files) that proposes changes to Prevent pattern previews from rendering in parallel due to React's concurrent mode

Unfortunately, our `@wordpress/*` packages is out-of-date for a long time, so we cannot benefit from that PR immediately when it gets merged 😔

> Here is another related Calypso PR https://github.com/Automattic/wp-calypso/pull/56154.

Yes, this is a quick improvement to wrap each pattern inside the `InView` so we won't load all patterns at the same time when people open the pattern list

**Comment by miksansegundo** [comment]
I'm closing this issue because we have done great optimizations. The current rendering performance is good. We can loop back later if we can find more potential optimizations.
