### ISSUE TITLE
Jetpack/Woo: first approach

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#7273]
We are starting to talk about how Woo Commerce and Jetpack can live together. Even if we don't have a clear picture of what's going to happen, whatever we attempt will depend on first being able to install and config Woo Commerce from jetpack / calypso. 

So we need to start exploring this option. Some questions that need to be asked:
- Will a non-key dependent plugin like Woo Commerce fit ok in our plans autoconfig flow? 
- What do we need to do to add this install to the free plan too?
- Woo Commerce have its own wp-based onboarding flow once installed, which in this case would clash with Jetpack's landing page. We would need to decide how to handle this.
- Would it be possible to integrate this Woo onboarding into our own flow in calypso? Does it have an API we can use to write the values it sets from WordPress.com? Would we need to add some on our own via Jetpack?
- If nothing of this is possible, would it be possible to skip WooCommerce onboarding so the user can land back in Jetpack once back to their wp-admin, and add a new jetpack section that allows you to launch manually that onboarding flow  ?

Please, add any question that crosses your mind about this.

**Comment by allendav** [comment]
> If nothing of this is possible, would it be possible to skip WooCommerce onboarding so the user can land back in Jetpack once back to their wp-admin, and add a new jetpack section that allows you to launch manually that onboarding flow ?

We are planning on a new Jetpack tab already for eCommerce, which will 1) promote the features of WooCommerce and Connect and 2) allow the merchant to install and activate WooCommerce and Connect

> What do we need to do to add this install to the free plan too?

The eCommerce features we will be promoting on new tab we're adding should probably be "rows" mentioned on the free plan of course.

cc @avivapinchas

**Comment by ryelle** [comment]
> Will a non-key dependent plugin like Woo Commerce fit ok in our plans autoconfig flow?

Yep! The plugins we install are generated by the API & based on which plan the site has. We just need to know that for a site with whatever plan, we want to install woocommerce too. So we might need to create ecommerce versions of the JP plans? So that people can opt-in.

Alternately we could make it another step where we ask if they want woocommerce and just re-use the plugin install code to add it (without worrying about autoconfig, since it doesn't need any options set).

I think that becomes a user-flow question rather than a technical one. 

> Would it be possible to integrate this Woo onboarding into our own flow in calypso? Does it have an API we can use to write the values it sets from WordPress.com? Would we need to add some on our own via Jetpack?

Technically I think we could put something together that would do all the same things as the onboarding, but it would be much easier to create some step-based API endpoints, which we can use like the save handlers are [currently used](https://plugins.trac.wordpress.org/browser/woocommerce/trunk/includes/admin/class-wc-admin-setup-wizard.php#L57).

> If nothing of this is possible, would it be possible to skip WooCommerce onboarding so the user can land back in Jetpack once back to their wp-admin, and add a new jetpack section that allows you to launch manually that onboarding flow ?

You can already jump into the woo onboarding at any time, so this would probably be a simple solution. It might require a little tweak to WC to let us skip the automatic redirect though.

**Comment by ryelle** [comment]
We have a store flow that installs woocommerce now, this issue is no longer relevant.
