### ISSUE TITLE
Task: Explore options for reducing prominence of payment blocks on eCommerce plans

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#72767]
### Details

We need to work out whether it makes sense to deprioritise our promotions of payment blocks to users on our eCommerce plans. This task is to investigate how we promote them at the moment, and then to see if we have a relatively easy mechanism for deprioritising them. We could technically disable them altogether, but that may not be a great UX, especially if users have previously set these blocks up for specific purposes.

**Comment by sixhours** [comment]
I've done a quick audit of the places where we emphasize the Payments blocks, and the two biggest promoters are located under Tools -> Marketing -> Marketing Tools (`/tools/marketing`) (which is confusing, since Woo Express users have a separate top-level menu, Marketing, that links to similar-but-different content) and Tools -> Earn:

<img width="570" alt="Screen Shot 2023-04-18 at 12 47 21 PM" src="https://user-images.githubusercontent.com/2124984/232848304-6bd395f2-9076-4959-8b18-906ec7c30a39.png">

Within this screen we could hide the Monetize your site card as a quick fix, or replace it with a card pointing to WooCommerce features:

<img width="1092" alt="Screen Shot 2023-04-18 at 12 51 52 PM" src="https://user-images.githubusercontent.com/2124984/232848741-f7b35581-7b37-47e6-a475-214927c2405e.png">

<img width="538" alt="Screen Shot 2023-04-18 at 12 48 01 PM" src="https://user-images.githubusercontent.com/2124984/232848788-30e2e607-88ce-426d-9721-22cfd53bd5cf.png">

The Monetize your site card links to the Earn screen at `/earn`; maybe we redirect this screen to the WooCommerce dashboard for Woo Express users. The functionality under `/earn` is required for the Payments block(s) to work (relying on a connection to Stripe) so if we hide or disable this screen, we should probably disable the Payments blocks, too.

<img width="1134" alt="Screen Shot 2023-04-18 at 12 47 50 PM" src="https://user-images.githubusercontent.com/2124984/232849480-fd382ad7-4a73-4b90-8e01-e117681a6457.png">

**Comment by sixhours** [comment]
We'll likely address this as part of the upcoming Bazaar initiative; closing this issue for now.
