### ISSUE TITLE
Premium Content Block: Subscriber able to access subscriber-only content not included in their subscription

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#72821]
### Quick summary

This is a peculiar issue. A customer reported that one of their subscribers (actually a test account) is able to access content outside their paid subscriptions. This only seems to affect this particular user, and we are able to reproduce this issue through the subscriber's account.

### Steps to reproduce

1. Subscriber browses to a page with a Premium Content Block at [REDACTED]
2. Subscriber clicks the _Login_ button despite not being a subscriber to this particular content
3. Subscriber is able to access subscriber-only content reserved for subscribers who specifically subscribe to this content.

### What you expected to happen

This subscriber has not subscribed to the subscription plan that grants access to this particular paid content. They should not be able to access the content, and should instead be prompted to subscribe to access the content ~~like this demonstration:~~

[REDACTED]

### What actually happened

Instead, the subscriber is able to click on the _Login_ button to access the content, as you can see here:

[REDACTED]

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The site uses the Maywood theme although this doesn't seem to be a factor as this issue seems to affect a specific user.

Reported in 5910364-zen

**Comment by cuemarie** [comment]
Hi @pauljacobson ! I've reported this issue here for you instead, since it's so specific to just one user: p2EDhh-1RL-p2

Always make sure to exclude any user-specific information in your screenshots or details.

Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.
