### ISSUE TITLE
SEO: Settings design updates

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7285]
Updates to the UX of the SEO settings page. Specifically around the title structure override section, which in general is a really tough interface to make understandable. I think this is an improvement, although there is still a fair amount of mystery meat due to not being able to fetch and populate the default title structure from the active theme.

Before:

![screencapture-calypso-localhost-3000-settings-seo-apeatlingtest54-wordpress-com-1470341455029](https://cloud.githubusercontent.com/assets/1464705/17416833/f01b1918-5a44-11e6-80fe-a412e93ab1f3.png)

After:

![seo-settings](https://cloud.githubusercontent.com/assets/1464705/17416835/f24504b0-5a44-11e6-8534-616034e1ece1.png)

**Comment by adambbecker** [comment]
I really, really like this. Separating the page out into sections is a good call, especially since it makes the "Save Settings" buttons feel specific to a related group of settings.

Also not using tabs for the pages is great as well as I think there's a lot of value in seeing them all at once.

The only thing I would consider adding would be the relevant chips or tokens for the default state. The preview text underneath is quite useful, but it did take me a second to understand that a blank input could still have a preview (hence realizing the `(default)` in the preview text. I think actually having those pre-filled even for the defaults might make a nice connection between the input tokens & preview text.

**Comment by folletto** [comment]
Nice change. It's a bit verbose first impact, but I think it's worth it as this is a rather advanced configuration screen. :)

> The only thing I would consider adding would be the relevant chips or tokens for the default state. 

+1 to this. :)

**Comment by apeatling** [comment]
Totally agreed on default state, unfortunately though, according to @dmsnell it's not possible to do this because it is set by the theme. All we can do is render the preview underneath. Is that correct @dmsnell? I think if we can find a way, it's going to dramatically improve this UI, so at some point (perhaps as a loopback) we can put our heads together to try and make it happen, it would be beneficial.

**Comment by dmsnell** [comment]
> All we can do is render the preview underneath

true @apeatling, but I think we misunderstood each other. I was suggesting some grayed-out text inside the format editing box to indicate that with no custom text or chips, it would show _as generated by the theme_. This default could also render below in the search preview.

**Comment by dmsnell** [comment]
After some discussion yesterday with other Calypsites, I believe that we are going to try and incorporate the `draft.js` editor here as the new input field and rebuild it all. This might now work out in the end but it probably stands the most reasonable chance of fixing the UX issues.

**Comment by roundhill** [comment]
Reopening, #7473 took care of half of the design update.
