### ISSUE TITLE
Extraneous inner border inside input fields

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#72966]
### Quick summary

I noticed that the input fields inside the Hosting Configuration section now have an extra inner border:

![calypso localhost_3000_hosting-config_javierarce blog](https://user-images.githubusercontent.com/4933/216674841-67a6e8c5-5e39-4fb5-a8db-9786a4be89e2.png)

Here's the previous (correct) version:

<img width="742" alt="Screenshot 2023-02-03 at 18 50 54" src="https://user-images.githubusercontent.com/4933/216675007-ef18ab19-b134-4a99-96e5-9f634c2865e5.png">

### Steps to reproduce

1. Visit the Hosting Configuration page

### What you expected to happen

No border inside the input fields

### What actually happened

There's an extra border inside the input fields

### Impact

All

**Comment by danielbachhuber** [comment]
It looks like there's some generic `input` styling applied:

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/36432/216718355-65159dbf-0cec-46b5-8835-46c8d7b8a48b.png">

https://github.com/Automattic/wp-calypso/issues/45259 seems like a related project

@Automattic/team-calypso-frameworks How would you recommend fixing this?

This CSS does the trick, but it feels like playing whack-a-mole:

```diff
diff --git a/client/my-sites/hosting/sftp-card/style.scss b/client/my-sites/hosting/sftp-card/style.scss
index 64e385399a..172e8a07a9 100644
--- a/client/my-sites/hosting/sftp-card/style.scss
+++ b/client/my-sites/hosting/sftp-card/style.scss
@@ -12,6 +12,18 @@
 	padding: 0;
 	margin-bottom: 16px;
 
+	input[type="text"].sftp-card__copy-input {
+		font-family: $monospace;
+		flex: 1 1 0;
+		border: none;
+		min-width: 0;
+	}
+
+	input[type="text"].sftp-card__copy-input:focus {
+		border: none;
+		box-shadow: none;
+	}
+
 	&.is-focused {
 		border-color: var(--color-primary);
 		outline: none;
@@ -81,18 +93,6 @@
 	}
 }
 
-input[type="text"].sftp-card__copy-input {
-	font-family: $monospace;
-	flex: 1 1 0;
-	border: none;
-	min-width: 0;
-}
-
-input[type="text"].sftp-card__copy-input:focus {
-	border: none;
-	box-shadow: none;
-}
-
 .sftp-card__password-explainer {
 	margin-bottom: 8px;
 }
```

**Comment by tyxla** [comment]
I wonder if we can adjust our design to stay as close as possible to the existing generic styles? Is that an option we could consider? I'd say this is the ideal path forward since it would keep us aligned with the core component design as much as possible. This parity between Calypso and WordPress components is something that tends to be difficult over time, but definitely worth it.

Otherwise, if we really need to erase the generic styles in favor of our own design, we can add some custom styling similar to what @danielbachhuber demonstrated, and I'd be fine with that, given that we've weighed the trade-offs. We understand that it's not always possible to stay flexible and make good use of design and creativity while maintaining compatibility with WordPress components.

**Comment by danielbachhuber** [comment]
> I wonder if we can adjust our design to stay as close as possible to the existing generic styles? Is that an option we could consider?

I'd be fine with this.

@javierarce What do you think? If you're in favor, want to mock something up?

**Comment by javierarce** [comment]
Yes, I'll work on an alternative for that type of button.

**Comment by javierarce** [comment]
What about something like this? 

https://user-images.githubusercontent.com/4933/217885575-78532293-d543-455c-8277-4b558609b4cc.mov

I'm trying to have a look at other pages where we use the `ClipboardButton` component to make sure that the design makes sense, but I was only able to access the refer-a-friend page.

**Comment by danielbachhuber** [comment]
@javierarce As it turns out, there's a `<ClipboardButtonInput />` component that seems to work well:
* https://github.com/Automattic/wp-calypso/pull/73195
* https://wpcalypso.wordpress.com/devdocs/client/components/clipboard-button-input/README.md

I think I prefer the "overlaid button" style vs. what you've mocked up. The button in your mockup doesn't really appear like a button...

**Comment by javierarce** [comment]
> The button in your mockup doesn't really appear like a button...

Yes, that was one of the issues I was having with my proposal: that it could be confused with the inputs with suffixes, for example.
