### ISSUE TITLE
Calypso crashes when trying to add a new site on the `/plans` page

### ISSUE THREAD

**Issue by ddc22** [Automattic/wp-calypso#72990]
### Quick summary

A white screen appears in the `https://wordpress.com/plans` due to a JS error. The same error doesn't appear on any other page.
![image](https://user-images.githubusercontent.com/3422709/216890571-52639c31-a694-40a3-95d9-dd56971d66d1.png)

Issue raised by @dzver: Automattic/martech#1473
Diagnosis by @claudiucelfilip: https://github.com/Automattic/wp-calypso/pull/72402/files#r1096004215

### Steps to reproduce

1. Go to /plans or /domains
2. Select Switch site
3. Add a new site

### What you expected to happen

The page should not break

### What actually happened

A white screen appeared with a JS error.
![image](https://user-images.githubusercontent.com/3422709/216890699-24c618a9-72d7-446e-b495-0376961dac88.png)

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

![image](https://user-images.githubusercontent.com/3422709/216890771-b560dd09-fced-4d61-a437-69b605e812d5.png)

**Comment by daledupreez** [comment]
@jdc91, @dzver, and/or @claudiucelfilip, have any of you been able to reproduce this in wpcalypso or local dev environments? I _think_ I have a fix in #72992, but I can't verify that because the `/plans` and `/domains` paths redirect to the logged out versions of those pages in wpcalypso and the calypso.localhost. I am also not sure from the instructions whether I need to switch to another site to trigger the error.
