### ISSUE TITLE
Dyad 2 theme :: Post page :: Double scrolling post pages with tags. 

### ISSUE THREAD

**Issue by mdtanjid0** [Automattic/wp-calypso#73042]
### Quick summary

**_The issue couldn't be replicated on either my or my colleague's @desnum site._** 

So the issue could be replicable only on the customer site with the theme ( Personal plan, so no custom code or plugins ). 

It's hard to scroll on the single post page with the tags with the [Dyad 2](https://wordpress.com/theme/dyad-2/) theme. 

The issue is caused by this CSS: 

<img width="1385" alt="Screen Shot 2023-02-06 at 13 49 04" src="https://user-images.githubusercontent.com/54123436/217234976-ee8a8195-804f-43c4-a7c8-b3a6504cee1e.png">

### Steps to reproduce

1. Go to this URL: [deleted]
2. And scroll the post up and down and see the lag there. 
3. To compare it, you can check this post: [deleted] which hasn't any tags.  

### What you expected to happen

The post should be scrollable without any lag like that. 

For example, please add this CSS code via the browser inspector tool: 

```
/* Fix the scrolling issue for the single page | ( 5899645-zen ) MT */

.single main article.hentry {
    overflow-x: initial;
}
```

And see the difference. 

### What actually happened

It's lagging while scrolling. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The issue is theme specific: [Dyad 2](https://wordpress.com/theme/dyad-2/)

And I have chosen Available workarounds as "difficult" to implement because it's impossible to execute the CSS with the Personal plan's user, and if the user wants to stick with the theme, then they can't get rid of the issue. 

Context: 5899645-zd

**Comment by mdtanjid0** [comment]
5899645-zen ( needs to follow up ).

**Comment by cuemarie** [comment]
Hi @mdtanjid0 ! I see there's some discussion happening about this issue here as well: p2EDhh-1Qb-p2 and @vajrasar has mentioned the preferred workflow for issues that cannot be replicated in test environments.

I also checked the links provided, but do not see any double scroll issues - it's possible the user has removed tags that seem to have triggered the issue.

With all that in mind, I'll close this report in favor of the internal investigation.

When you have a moment, please edit the report above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

**Comment by mdtanjid0** [comment]
Thanks, @cuemarie!

Edited and removed that as well from the revision.

**Comment by galakhyati** [comment]
Similar scrolling issue with Dyad 2 theme here: 8346877-zd-a8c
