### ISSUE TITLE
Missing Fonts in Styles on eCommerce Sites

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#73133]
### Quick summary

For some FSE themes on eCommerce plan sites, the Styles > Typography option only shows a limited number of fonts. The specific fonts shown seem to vary by theme. The same themes on a Business plan site show a much larger selection of font options.

This was reported in Twenty Twenty-Three, but I also see it happening in Twenty Twenty-Two, Tsubaki, Tazza, and Zaino so far. On the other hand, Heiwa and Zoologist show the same number of fonts on both Biz and eCom, so those seem unaffected. (I do notice that the font list available to Heiwa is smaller than the font list available to 2023 on Business, but that may just mean those are the default styles available to Heiwa rather than a bug/related to this issue.)

It's very similar to the Simple site issue seen here: https://github.com/Automattic/wp-calypso/issues/71360 Though I'm not sure if the cause is related in any way.

### Steps to reproduce

1. On an eCommerce site, activate the managed/wpcom Twenty Twenty-Three theme (or one of the other affected themes, such as Tsubaki).
2. Go to Appearance > Editor and edit a template.
3. Open the Styles panel and choose Typography, then Text.
4. Check the available font selection.

### What you expected to happen

There should be a full list of font options, as shown in this Business plan screenshot from Twenty Twenty-Three:

<img width="309" alt="2023-fonts-business" src="https://user-images.githubusercontent.com/82622339/217701561-18df9aff-1280-414c-b37a-30127d18d32f.png">

### What actually happened

Only a small selection of font options is available, as shown in this eCommerce screenshot from Twenty Twenty-Three:

<img width="293" alt="2023-fonts-ecom" src="https://user-images.githubusercontent.com/82622339/217701904-7299db87-cd24-415e-b278-25777a6767b3.png">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

User report: 5941280-zen

Seems to be eCommerce only rather than all AT sites

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Wasn't able to replicate this on a test eComm site. Tested **Twenty Twenty Three** and **Tsubaki** on the eCommerce plan.

https://user-images.githubusercontent.com/27249804/221074867-ebba5529-ba14-4147-94b0-e87346578c5c.mp4

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @thekingsprojects are you still able to replicate the missing fonts on a test site? Or is this only happening in a user's site?
- It's possible this has been resolved since it was reported, or that it may be a similar issue to https://github.com/Automattic/wp-calypso/issues/65115
- If this is still happening for the user, and you can find a way to replicate this on a test site, feel free to reopen! Otherwise this might need some help from Reactor instead. Thanks!

**Comment by thekingsprojects** [comment]
The screenshots above were from my own sites, but I just tested my eCom site again with Twenty Twenty-Three and Tazza and the issue isn't happening any more. Looks like it got resolved by something else—thanks for checking!

I've updated the user to check with them just in case (though they're currently not using an FSE theme at all, so it may be a moot point).
