### ISSUE TITLE
Writing prompts: Move BloggingPromptCard component

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#73158]
### Details

The home card blogging prompt components are used in my sites and in reader. We should move them to `client/components` to reflect the fact they are used in multiple places.

### Checklist

- [ ] Move `BloggingPromptCard` to `client/components` directory

**Comment by creativecoder** [comment]
The changes needed in https://github.com/Automattic/wp-calypso/pull/72923/files#diff-f89c58910f936f82c9062e6c0d675980c1704c55439efb3a19c7e8c2c833139a tell me that the blogging prompt card would be better if it was mainly a presentational component and minimally tied to global state.

For example, passing in siteId as a prop rather than from a hook would allow us to assign whatever id is best for the context, be it selected site, primary site, etc.

I think moving the component would be a good opportunity to refactor.

**Comment by eoigal** [comment]
I've refactored how we handle selected site id in https://github.com/Automattic/wp-calypso/pull/73284
