### ISSUE TITLE
Purchases: Adapt renewal warning messages to remaining time

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#732]
When an upgrade is expiring in a long time we probably should change this message:

<img width="743" alt="screen shot 2015-11-25 at 14 00 48" src="https://cloud.githubusercontent.com/assets/275961/11397892/c45db534-9374-11e5-855e-9b8e83c5c37a.png">

cc @mikeshelton1503 for ideas

@p3ob7o:

> we ned to set a limit beyond which we don’t say “will expire and be removed"

**Comment by mikeshelton1503** [comment]
Agreed that's odd, however >1 year would be an edge case AFAIK. We don't allow users to renew for more than one year at a time. I know there are a few situations where it's possible but not sure exactly which situations those are and how common they are. Also going forward, auto renew is always on (unless credits were used) so seeing this message should be an edge case in itself.

With that said, really the issue here is more than awkward copy. It's odd to have a "Renew Now" link >90 days from expiration. This is something that happened in the hustle to get things done for v1 and it's fine for now but I really think we should address the larger issue here for v2 if we think it's still an issue that will persist for more than just a handful of users (perhaps in a few months we can run a query to see how many users have auto-renew off and how many months away they are from expiration).

The reason this exists as it is now is because we wanted to have an "unsubscribed active state" for all purchases with auto renew off. So when we denote that something is going to "expire" it seemed wrong to not then also provide an option to remedy the issue. I think "Renew now" is the wrong action. It's really "turn auto-renew on" though that could be problematic given that we don't want to ever indicate that auto-renew is optional since it's not.

Yes, I realize that I just provided a suggestion to a problem that I had just mentioned is not common enough to fix. Just wanted to cover both bases prior to having any data in hand to back up my assumtions :smile:

**Comment by mikeshelton1503** [comment]
cc @breezyskies

**Comment by breezyskies** [comment]
>  We don't allow users to renew for more than one year at a time.

This is true at the moment, but @umurkontaci was working on adding the option to register a domain for multiple years.

> It's odd to have a "Renew Now" link >90 days from expiration.

Agreed. Maybe we don't need any notice over 90 days?

**Comment by mikeshelton1503** [comment]
>Agreed. Maybe we don't need any notice over 90 days?

That was how it was originally until the point was raised that we change "Auto-renews on" to "Expires on" for the unsubscribed active state immediately but weren't providing a method to allow users to renew.

**Comment by scruffian** [comment]
> Maybe we don't need any notice over 90 days?

We need to show something to allow users to switch on auto renew when its disabled

**Comment by breezyskies** [comment]
> That was how it was originally until the point was raised that we change "Auto-renews on" to "Expires on" for the unsubscribed active state immediately but weren't providing a method to allow users to renew.

I guess I'm wondering if this is a major concern if we don't show a notice? I guess there is the potential for a user to accidentally cancel and want to renew again quickly after, but that seems pretty edge case given the cancelation flow. 

(Another option would be to revisit the "renew now" link / button concept.)

**Comment by spncrb** [comment]
> Agreed that's odd, however >1 year would be an edge case AFAIK.

This isn't really true with Purchases v1, since clicking the Renew now button is the only way to subscribe to an unsubscribed purchase.  We are now actively promoting renewals for all unsubscribed purchases, meaning purchases with over 1 year on them may become more common.

I think the simplest solution is adding a variation of our current "Edit Payment Information" option for all unsubscribed purchases.  We could re-use this functionality, but label it "Add Payment Information" and on the back end, it would change a purchase from unsubscribed back to subscribed without adding an additional year.

**Comment by mikeshelton1503** [comment]
> I think the simplest solution is adding a variation of our current "Edit Payment Method" option for all unsubscribed purchases. We could re-use this functionality, but label it "Add Payment Method" and on the back end, it would change a purchase from unsubscribed back to subscribed without adding an additional year.

In v2 we are adding an "Add a new card" feature within the "Edit payment method screen" https://cloudup.com/cdQkb-uAAKl 

I do agree that we should change the behavior where a unsubscribed purchase can only be made active again by making a payment immediately. Instead we could just restore the purchase to an active state when a valid payment method is added again, and charge the user on the same date as if the purchase were active all along.

**Comment by BandonRandon** [comment]
I also just wanted to mention that if the subscription will expire in 1 year or greater you'll get an error message when trying to renew. I think maybe either hiding the message when you can't renew anyway or change the text to something make "Manage Now" since you'll be allowed to change the status of the renewal.

**Comment by fabianapsimoes** [comment]
This came up again in #3809. @mikeshelton1503, what do you think we should do about this notivce, especially considering what Brooke mentions in https://github.com/Automattic/wp-calypso/issues/732#issuecomment-169834277?

There are two things to consider:

- adjusting the copy when the purchase won't expire any time soon
- not displaying the notice at all when it's not possible to renew.
