### ISSUE TITLE
Conversion: Offer a discount to new free users if they upgrade to a paid plan

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7326]
Let's test offering new users who are on a free plan a discount for upgrading to a paid plan inside of a specific window. 

Since the first week of engagement is key, I think we should look at the offer being available between 1 and 7 days after signup and notifying the user of this. The discount should not be present on day 0, since they will have just seen full prices in the signup flow.

I think the discount should be in the 5-10% range. Although this is open for consideration and analysis.

**Comment by artpi** [comment]
I would love for us to play with discount codes.
Also I thing that it would be much more useful in linking 'offline' campaigns to stats etc. I proposet specific approach here: p5uIfZ-1FJ-p2/#comment-2329 - it kicked up some discussion / considerations.
Overall I think that while offering discounts to people from specific campaign lets us easily mitigate price erosion, offering discounts to people that just came sets a very dangerous precedent.
Price erosion is a difficult topic and it would be good to discuss it on some p2 :)

**Comment by retrofox** [comment]
- [ ] _... the offer being available between 1 and 7 days after signup_
- [ ] _...notifying the user of this.
- [ ] _I think the discount should be in the 5-10% range._

**Comment by rralian** [comment]
I've added the `[NUX]` label, as we're talking about tying this to the signup timeline, so we should really make sure we're in sync with Delta's plans.

@meremagee and @shaunandrews we were thinking this could be a good case for an email drip campaign, post-registration for free users. But I wouldn't want to propose that without knowing how that fits in with signup plans in general (particularly emails). What do you think?

**Comment by retrofox** [comment]
***First question***
Are we agreed we would notify to the user in two possible ways: email campaign and through of the UX (dialog opens automatically, nudge, etc.)? In both cases let's keep the same period .

**Comment by rralian** [comment]
I think for now you can proceed by adding a feature gate, combined with registration timeline (i.e., 1--7 days) as discussed, and use that to determine whether to show the discount on the plans page. Then we can determine as a separate task exactly how we will promote and link to it.

**Comment by apeatling** [comment]
Discount codes seems like a good approach here. I also like the idea of emails and in UX notices too. It's possible that seeing both could be a bit much though?

**Comment by rralian** [comment]
Discount codes is pretty different from how I imagined this would work. So now I'm a little confused about how we would approach this.

I like the idea of a DRIP email because it helps both our goals of improving revenue and engagement. If we just link people to the plans page, we can automatically show the discount. I don't think there's a need for discount codes. But that begs the question of what happens if they click the email link past 7 days. Do we still give them a discount? Or do we say it's too late? I think deadlines motivate people, but it seems wrong to set them up for a disappointment at the point of checkout.

If we instead gave people discount codes, would they be personalized hashes? Or would they be something general like "NEWUSER" that they enter as part of the cart? So if a user navigated to the plans page on their own without the discount code, would we not offer the discount?

Another consideration is whether we can offer this consistently for everyone going forward. Wouldn't people eventually learn about this and just always start with a free plan to get the discount? So would we need to turn the campaign on and off periodically?

**Comment by retrofox** [comment]
> Discount codes is pretty different from how I imagined this would work. So now I'm a little confused about how we would approach this.

Me too. 

> But that begs the question of what happens if they click the email link past 7 days. Do we still give them a discount? Or do we say it's too late? I think deadlines motivate people, but it seems wrong to set them up for a disappointment at the point of checkout.

I think the message that we send to users should be as clear as possible: "It's a cool offer but you have a short deadline to get it.". For this reason we should keep them aware of this, either sending an email or showing a message in the app.
In other hand could we increase the deadline? I guess 6 days in too short.

>Another consideration is whether we can offer this consistently for everyone going forward. Wouldn't people eventually learn about this and just always start with a free plan to get the discount? So would we need to turn the campaign on and off periodically?

It's very easy create a new user to get this discount. For instance I use `myemailroot+username@gmail.com`. :-o

**Comment by rralian** [comment]
This is tabled for now, at least as originally specked.
