### ISSUE TITLE
Color Scheme Conflicting in Editor

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#73287]
When writing/editing a post on my site (sporadicthoughts.net) I see pink buttons and some weird hover states:

<img width="456" alt="CleanShot 2023-02-13 at 11 12 27@2x" src="https://user-images.githubusercontent.com/191598/218515375-0641c93b-138d-479e-8661-1c2b3073b046.png">

https://user-images.githubusercontent.com/191598/218515396-182cfe30-ef77-4a6e-9081-1bb97f93eb81.mov

I think there's some conflicting CSS or something, as I have selected the "Modern" color scheme; I shouldn't be seeing the pink buttons.

**Comment by vajrasar** [comment]
I can replicate the issue on WordPress.com account when selecting any color scheme (not just Modern), and this appears only while creating a new post (not pages).

**Comment by kozer** [comment]
I couldn't replicate the issue. Steps I followed:
- Created a business simple site.
- Navigated to `me/account`
- Change the `Dashboard color scheme`
- Create a new post
- Create a new page
- Both have the correct colors.

Can you still replicate @vajrasar ?

**Comment by sejas** [comment]
I'm investigating this issue.
I'm able to reproduce only on atomic sites using calypso.
The plus button has the wrong color.


https://github.com/Automattic/wp-calypso/assets/779993/7217b825-41c9-42b4-8192-d79835dbd065

**Comment by jeroenpf** [comment]
From what I can tell, this is caused by the [Jetpack Calypsoify module](https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/jetpack/modules/calypsoify). For the post/page editor iframe we pass `calypsoify=1` as a parameter in the iframe UR. This causes the module to load and place additional stylesheets and scripts. There are some hardcoded colors that correspond to the Calypso default theme and they overwrite the Gutenberg style (which respects theme colors). 

For non-atomic sites, we don't load the Jetpack module but we have a a plugin ( fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Spnylcfbvsl.cuc%3Se%3Qr4npr5q7-og ) that also overwrites a couple of styles, just not as many as the module does. It seems that both the JP module and the plugin for simple sites share a common ancestry but have diverged over the years.

My hunch is that we should remove the conflicting styles from the module.  I'll need to figure out if this is not going to break things in other places first.

**Comment by jeherve** [comment]
This is currently tracked here as well:
https://github.com/Automattic/jetpack/issues/11478

**Comment by jeroenpf** [comment]
See: https://github.com/Automattic/jetpack/pull/32919

**Comment by jeroenpf** [comment]
Fixes have been implemented. Once the latest Jetpack version is available on wpcom, this issue will be resolved.
