### ISSUE TITLE
Conversion: Build one click upgrade flow for domains-only users

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7329]
Build a specific nudge and upgrade flow to present a domain only user with the option to easily switch to a plan with one click (use all payment details on file). This should be seamless and informative for the user (they should understand why they should change to a plan, and possible also be offered a discount for the first year).

**Comment by artpi** [comment]
Nice!
This makes a lot of sense.

> possible also be offered a discount for the first year

First we need to come to terms with our price-erosion-discount-tactic, but inserting nudges is a no-brainer :)

**Comment by rralian** [comment]
IMHO the best approach would be to promote the personal plan in particular. This would also simplify the widget so we wouldn't need a plan-selection interface.

I think the general implementation would be a promo card that has some marketing message with a call to action "upgrade to get blah blah". The user clicks the upgrade button and a small interface slides out that shows the proposed charge, shows the discount because of their domain purchase, the last four digits of the credit card on file, and a button to confirm the purchase. There would also be an optional link to change payment details which would link to the current checkout page with the personal plan in the cart. If the user confirms the purchase, once it is successful, we would redirect the to the "thank-you" page.

First I think we need to figure out where we'd put this. Based on pageviews, time-on-page, and relevance, three options stand out to me:
- `/stats/day/:site`
- `/post`
- `/help`

I would propose we build just one of these at first, and I think an upgrade card in the sidebar on the `/post` (editor) page would be a good option. It could say:
> ### Personal Plan [NEW!]
> ~~$71.88~~ $53.88 today
- No Advertising
- Priority Support

> [ upgrade now ]

@apeatling how does all that sound? If this sounds like a good first step, I think we need at least a wireframe to start this. Are you able to put something together, or is there a designer we can ping?

**Comment by apeatling** [comment]
I'll get a wireframe together.

**Comment by apeatling** [comment]
<img width="788" alt="screen shot 2016-08-17 at 11 27 46" src="https://cloud.githubusercontent.com/assets/1464705/17748323/a9ff015a-646d-11e6-9914-2a1960d640fd.png">

https://cloudup.com/cWPAdNty6T0

If a designer would like to put some design to this, that would be awesome. Anything with color would be great, I really like the new reader notices.

**Comment by apeatling** [comment]
This wireframe I was thinking would be positioned at the top of a page, probably stats to start with since it's high impact.

**Comment by gwwar** [comment]
This looks like a pretty large notice. Are we OK with our nudge being so prominent? At the very least I think I'll add a preference to not show this notice again. We may need a checkbox to differentiate between hiding this forever vs just this session.

Also, what does the flow look like after we click on Subscribe now?

**Comment by rralian** [comment]
If we put this in stats, and we want good exposure, we should put it in `/stats/day/:site`. Based on time-on-page from GA, that's where people spend quality time in `/stats`. `/stats/insights/:site` seems to be just a transition page.

It would also be helpful to put this in context of the page. Like, does it go above or below the navigation?

**Comment by gwwar** [comment]
@apeatling could you let us know where this might fit on the page in context? Are you thinking top of content like the banners in p5PDj3-1ls-p2 ?

**Comment by apeatling** [comment]
Yes, up top, above nav.

**Comment by rralian** [comment]
We include 3GB of storage in our free plan. I don't think we should list that as a benefit of the personal plan. Also, shouldn't we have some interaction that shows the user the last four digits of a credit card we are charging, and offers them the ability to edit payment details? That's what I was proposing as a "slide out" panel in my comment above. https://github.com/Automattic/wp-calypso/issues/7329#issuecomment-240238536

**Comment by apeatling** [comment]
@rralian I was following the email promos we sent out with that one. It's still something you get in the plan, even if it's not an upgrade.

I agree on the credit card part, how about:

<img width="769" alt="screen shot 2016-08-22 at 09 12 35" src="https://cloud.githubusercontent.com/assets/1464705/17862079/97b9dae0-6848-11e6-9421-0c6004b75bf6.png">

**Comment by folletto** [comment]
> This wireframe I was thinking would be positioned at the top of a page, probably stats to start with since it's high impact.
  
> Yes, up top, above nav.

Can you mock that up inside the page (wireframed with less details), so there's full context for the wireframe?

**Comment by melchoyce** [comment]
Took a stab at designing this:

![personal upgrade nudge](https://cloud.githubusercontent.com/assets/2846578/17940508/7c54fd28-69fd-11e6-915c-13df31370969.png)

(<a href="https://cloudup.com/cuEmoIU7Eb8">Sketch file</a>)

I tried a few different color options, but they mostly ended up looking garish — there are too many text elements going on here with potentially different colors to work super harmoniously, based on my experimentation, and still provide enough contrast and hierarchy.

**Comment by rickybanister** [comment]
@melchoyce that looks great ;)

I figured it's worth explicitly mentioning that we should use the same bottom border color (or other accent color) for each respective plan in upgrade nudges as we do on the plans page:

<img width="1113" alt="screen shot 2016-08-24 at 12 59 15 pm" src="https://cloud.githubusercontent.com/assets/437258/17940870/00283cae-69ff-11e6-9e7a-862f53d213e0.png">

I think that should be true for these as well:

<img width="777" alt="screen shot 2016-08-24 at 12 58 32 pm" src="https://cloud.githubusercontent.com/assets/437258/17940879/0965a806-69ff-11e6-90ab-a709aa002841.png">

So in the case of the footer credit upgrade nudge ^ shouldn't it be purple? (happy to open another issue for that, just wanted to debate it first).

Also, regarding the copy of this nudge—why is the discount being offered? We never say. Does the 25% expire if you don't act soon? Is it because they already have a domain? Is it just to make the plan seem cheaper? 

Should the call-to-action be "Subscribe" or "Upgrade"? Everywhere else we say "Upgrade".

**Comment by gwwar** [comment]
> Also, regarding the copy of this nudge—why is the discount being offered?

Looking at the store code, if folks have purchased a domain we give them a $20 discount if they've done so recently or a $10 discount if it's been a while.

We give some discount reasons in our current checkout, but this seems hard to explain succinctly.

![screen shot 2016-08-24 at 10 08 35 am](https://cloud.githubusercontent.com/assets/1270189/17941049/78b24872-69e6-11e6-94e3-731d8d11058f.png)

**Comment by rickybanister** [comment]
Can/should we put that reason on the upgrade nudge? Only folks that take the leap to upgrade will know why they received the discount otherwise.

**Comment by gwwar** [comment]
> Can/should we put that reason on the upgrade nudge?

Ideally, yes. If we don't run into any technical hurdles, the call to action is a one-click purchase, so they won't be able to see the image above. (It skips the checkout page)

**Comment by apeatling** [comment]
I'm not sure the reason is all that important, my assumption would be that this will convert better if we just stick to saying there's a discount.

Another option would be to have a bullet point that makes it clear you keep your existing domain name and it becomes part of the plan.

**Comment by melchoyce** [comment]
Just want to clarify... are people actually saving anything? Or are they making up the difference between buying a domain and the rest of the cost of the plan?

**Comment by apeatling** [comment]
You are saving $20 dollars over the price of buying a personal plan, but in reality you've already paid for a domain, so it's just a deduction.

**Comment by gwwar** [comment]
> Just want to clarify... are people actually saving anything?

Kind of? We give them a fixed discount rather than subtract the actual cost of what the domain was. In most cases they should mostly come out even if they purchased a domain firs then a plan, rather than just the plan initially.

**Comment by melchoyce** [comment]
If people realize they, might they feel cheated? What if we tried to focus on the value of bundling these great features with your domain, rather than focusing on saving money?

**Comment by apeatling** [comment]
It's possible, but let's test how this converts first, and get feedback from people who go through and purchase. It is still a discount at the end of the day, and we are presenting the extra features you get with a plan.

I would not be opposed to adding the line above, being clear that you retain your existing domain with the new plan.

**Comment by melchoyce** [comment]
Made some updates:

![personal upgrade nudge 6](https://cloud.githubusercontent.com/assets/2846578/17946192/48fe89d6-6a15-11e6-98b2-495559ca01d0.png)

**Comment by melchoyce** [comment]
[Updated Sketch file](https://cloudup.com/ig-Ebm4EgOu)

**Comment by ehti** [comment]
@gwwar @apeatling Personal plan doesn't include VideoPress, so you can't upload videos. Do you want to restrict it to photos? They'd might already be aware of this restriction.

**Comment by dmsnell** [comment]
> If people realize that, might they feel cheated?

a valid concern @melchoyce - thanks for bringing it up

**Comment by gwwar** [comment]
Thanks @ehti we have an issue open for this on the plans page #7744, and we'll make sure not to add the incorrect copy to this nudge

**Comment by apeatling** [comment]
Good point @ehti let's remove the reference to videos. I think we need to reword it.

**Comment by apeatling** [comment]
@dmsnell: For a few reasons I don't think it's like that. Ping me on Slack and we can chat about it.

**Comment by designsimply** [comment]
Closing as fixed because I tested My Sites > Domains and was able to see an upgrade nudge:

![screen shot 2017-05-09 at tue may 9 5 12 47 pm](https://cloud.githubusercontent.com/assets/1119271/25876536/17788dd0-34db-11e7-89e7-11790d2ee972.png)
<sup>Seen at https://wordpress.com/domains/manage/thegamewereplaying.com (currently setup with a domain and no plan) using Firefox 53.0 on Mac OS X 10.12.4.</sup>

Aside: note that `/domains` was recently taken over by the domain-first signup flow in https://github.com/Automattic/wp-calypso/pull/11884 ([screenshot](https://cloud.githubusercontent.com/assets/1119271/25876622/a8d3c92a-34db-11e7-82f9-a518f768511f.png) for reference).
