### ISSUE TITLE
Conversion: Build informative placeholders for paid plan features

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7330]
Users that are on a free plan should see many of the paid features in their interface. When they select this, they should be presented with an informative upsell that encourages them to purchase a plan to activate the feature.

Some good examples of where we can do this:

* Google Analytics
* Advanced SEO
* Video uploads (videopress promo)
* On the frontend where we show ads (no ads)
* On the frontend in the footer (for the site owner show a message about removing branding)
* On our support section in Calypso, talk about more advanced support options
* On the themes section, promo for unlimited premium themes.

**Comment by apeatling** [comment]
For full settings pages, or where possible, we should treat these sections like places where we can really showcase what the feature offers. An example from @adambbecker:

![feature-callout_preview](https://cloud.githubusercontent.com/assets/1464705/17490025/cd4a04e4-5d55-11e6-97ad-a6c18dd8b1c1.png)

**Comment by artpi** [comment]
Do we intend to revive the direction we were taking in April?
From what I remember, we determined in test that these pages did not help us lift conversion.

If we intend to revive them, I have closed PRs in which I was developing this:

### Custom design

https://github.com/Automattic/wp-calypso/pull/4709

### Space

https://github.com/Automattic/wp-calypso/pull/4658

### Google analytics

Merged, but I believe it was since turned off

https://github.com/Automattic/wp-calypso/pull/4593

**Comment by rralian** [comment]
I'm having a hard time figuring out what concrete steps to take for this issue. As @artpi points out we tested a similar concept earlier this year and found that in-context nudges for paid features do work, but we were better off (gauging by overall conversion) taking people directly to the plans page rather than a feature-specific info page. So if we _don't_ build feature-promo pages, I think this issue just means we want an in-context nudge for each item.

Regarding nudges for each section:
### Google Analytics

We have an in-context nudge for GA already. 
![screen shot 2016-08-22 at 12 38 39 pm](https://cloud.githubusercontent.com/assets/134044/17864872/7148926c-6865-11e6-8910-28cbce6d1398.png)

### Advanced SEO

This is being worked on in https://github.com/Automattic/wp-calypso/pull/7563.
### Wordads (monetization)

WordAds lives in its own configuration section, and in order to keep the navigation clear and uncluttered, we determined not to add this sidebar item unless someone had activated the feature. We could revisit that, but right now someone needs to active WordAds from their "my plan" page to see the sidebar item.

![screen shot 2016-08-22 at 12 42 06 pm](https://cloud.githubusercontent.com/assets/134044/17865046/44cc17b2-6866-11e6-9f8d-e1f53ae6496c.png)
### Video uploads (videopress promo)

Until we have a dedicated "media" area in calypso (this is a big omission I would love to address), I don't think there's a very prominent place to promote video uploads. We can show them something if they add media and click the video link, and in fact we already do this. We could iterate on that copy.

![screen shot 2016-08-22 at 12 47 39 pm](https://cloud.githubusercontent.com/assets/134044/17865174/d7c73592-6866-11e6-912e-a6e96b95f0fe.png)
### On the frontend where we show ads (no ads)

We already do something like this. This is what an author sees when viewing their own free site. 
![screen shot 2016-08-22 at 1 23 58 pm](https://cloud.githubusercontent.com/assets/134044/17866370/e571fb0a-686b-11e6-8436-47d1f108bf4e.png)

### On the frontend in the footer (for the site owner show a message about removing branding)

We could add this. I'm a little leary about adding content here, since I'm not sure how it's treated across different themes.
### On our support section in Calypso, talk about more advanced support options

This makes sense, we could add it to the main support page (wordpress.com/help) and the contact page (wordpress.com/help/contact). The main help page is the same for everyone. It's the contact page that is different depending on whether you are a paid customer or not, and it's not a site-specific page, so you only have to have purchased _something_ for a site in order to get priority support.

### On the themes section, promo for unlimited premium themes.

We started talking about this in #4229 when we were originally working on nudges, but we wound up moving on from nudges at a certain point without building this one out.

**Comment by apeatling** [comment]
Talking to bob, we need content and separate issues for:

* GA
* Video Uploads
* Frontend ad promo for plans
* Content for priority support

And we should use the screengrab in #4229 for themes.

**Comment by apeatling** [comment]
Closing this in favour of the above broken down issues.
