### ISSUE TITLE
Metrics for the BCPA CTA in the logged-out Theme Showcase

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#73304]
#### Description

The BCPA CTA (Blank Canvas Pattern Assembler Call to Action) in the logged-out Theme showcase was launched on Feb 14, 2023. The tracks events related to this feature can be found in pbxlJb-3tq-p2

In the upcoming weeks, we are interested in analyzing the following metrics:

- [ ] Trends: How many users select the BCPA CTA in the logged-out Theme Showcase
- [ ] Trends: Comparison of the number of selected BCPA CTA between the logged-out Theme Showcase and the Design Picker
- [ ] Trends: Comparison between the number of selected BCPA CTA in the logged-out Theme Showcase and the number of selected Blank Canvas theme in the logged-in Theme Showcase
- [ ] Funnel: Users selected BCPA, created a new site, build their homepage via assembler, and launch the site

**Comment by autumnfjeld** [comment]
@taipeicoder  I'll go ahead and move this into "In Progress" as you and I are slowly starting on it.     And I can take it over as needed during your AFK.

One thought I had today is that it would be interesting to do completion rate comparisons for the following signup flows. The completion flow being Entry point to Editor/Launchpad (whatever the end-of-signup screen is)

* Free flow -> Launchpad
* LoTS with Assembler -> Editor
* LoTS with standard theme -> Launchpad (? does that end in LP?)
* wordpress.com/start -> Assembler > Editor
* wordpress.com/start -> standard theme > Launchpad 



In theory the Free flow is a  low friction flow and should have less dropoff because there are less screens in the Signup part of the flow.

Then we are comparing apples to apples as best we can: starting from a logged-out state in each case.    We could divide and conquer this.  Or its also ok if I end up doing this.  Brainstorming over slack a bit was helpful already.

**Comment by taipeicoder** [comment]
> @taipeicoder I'll go ahead and move this into "In Progress" as you and I are slowly starting on it. And I can take it over as needed during your AFK.
> 
> One thought I had today is that it would be interesting to do completion rate comparisons for the following signup flows. The completion flow being Entry point to Editor/Launchpad (whatever the end-of-signup screen is)
> 
> * Free flow -> Launchpad
> * LoTS with Assembler -> Editor
> * LoTS with standard theme -> Launchpad (? does that end in LP?)
> * wordpress.com/start -> Assembler > Editor
> * wordpress.com/start -> standard theme > Launchpad
> 
> In theory the Free flow is a low friction flow and should have less dropoff because there are less screens in the Signup part of the flow.
> 
> Then we are comparing apples to apples as best we can: starting from a logged-out state in each case. We could divide and conquer this. Or its also ok if I end up doing this. Brainstorming over slack a bit was helpful already.

Great idea, I'll check out the completion rates today 🙂

**Comment by autumnfjeld** [comment]
Since Ola's Themeboard weekly covers this I'm closing this issue pNEWy-hnU-p2
