### ISSUE TITLE
Conversion: Logged-out bar for free sites

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7331]
Look at a branded logged out bar for all free user sites that is an incentive to upgrade (to remove it), and also acts as a way to expore more WordPress.com content for users.

**Comment by artpi** [comment]
Since it is completely frontend-related, it requires non-calypso changes.
It is also very volotile topic. Should we start master thread for all related discussions? ( I assume there will be opinions. String. )
Also - honestly: Could we round up such volotile topics to experiment with them during GM? That sounds like a good opportunity to quickly decide on direction.

**Comment by apeatling** [comment]
@artpi Yes, I agree this is a good one to discuss at the GM. 

I would say to everyone: hold off on this issue for now.

**Comment by lancewillett** [comment]
Closing as this is outdated now. Let's reopen in the future if this comes up again.
