### ISSUE TITLE
LaunchPad preview - Add domain banner above

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#73324]
To combat the fall in upsells/purchases due to the launchpad in general onboarding flows, we want to add more upsell opportunity.

Here, we want to add a banner attached to/above the site preview when the site is on a free plan:

![image](https://user-images.githubusercontent.com/28742426/218739141-932439e1-d479-4599-a740-54ab0d0c4be7.png)

### Related items already in place.
This will be similar to the recently added upsell in the post editor for free sites as seen below:

![Screen Shot 2023-02-14 at 7 32 10 AM](https://user-images.githubusercontent.com/28742426/218739608-f7f5410c-8077-4589-909b-d326afc3bfc8.png)

**Comment by nuriapenya** [comment]
📍 Figma File: 9wpoYJrMlYKAKUYvVBMN74-fi-2427%3A9711

**Design notes:**

- Currently, this domain upsell component offers the possibility to close with the "X". I suggest removing that for the Launchpad; otherwise, there will be a gap in the frame.
- There's no mobile version of this banner. Do we want it for the Launchpad? It might break...
- Styling is the same; both backgrounds should share the same value #F8F8F8
