### ISSUE TITLE
Newsletter accent colors do not reset "choose a plan" conditional task in launchpad

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#73339]
Switching back to the default accent color does not get rid of the "choose a plan" requirement. (or more simply, it doesn't seem possible to actually switch back to the default color)

To Repro:
* Create a site in the newsletter flow - wordpress.com/setup/newsletter
* Select a different "favorite color" (like vivid red) in the first setup step.
![Screen Shot 2023-02-14 at 1 18 34 PM](https://user-images.githubusercontent.com/28742426/218823494-d7f39351-2747-4a23-a968-6e00f47d9e9a.png)
* continue through onboarding to the launchpad and notice the "choose a plan" task showed up due to our selection
![Screen Shot 2023-02-14 at 1 23 26 PM](https://user-images.githubusercontent.com/28742426/218824512-e6418723-c87f-4d0e-84c0-2a186299cf24.png)

* click on "Personalize Newsletter" to revisit the setup step.

### Problem 1 - the selection now loads with the original color, and not the color that is currently selected.

![Screen Shot 2023-02-14 at 1 24 41 PM](https://user-images.githubusercontent.com/28742426/218824744-a25f5ae1-808c-43a4-810e-c68b7addb6ac.png)

### Problem 2 - Continuing from here doesn't change the color.

It seems possible to change to other custom colors, but the default (free) option does not seem to work:
![newsletter-color-flow](https://user-images.githubusercontent.com/28742426/218825281-fa8204c5-bd8e-415c-bc45-a728a7a551ba.gif)

**Comment by dsas** [comment]
You need a blog that limits global styles to reproduce this.

I had assumed that this was due to https://github.com/Automattic/wp-calypso/pull/70958 but actually, even after reverting the changes in that PR and in the phab diff, this is still reproducible. 

It looks like the problem is that the newsletter setup screen thinks the color is already blue and so doesn't make the XHR request to save it as blue. 

It think this because it hits the `/wpcom/v2/sites/215718860/global-styles-variation/site-accent-color` endpoint. This endpoint uses the `wpcom_get_site_accent_color` function, which eventually hits `WP_Theme_JSON_Resolver::get_user_data` which runs the `wp_theme_json_data_user` filter that we hook to implement global styles with `wpcom_block_global_styles_frontend`.

**Comment by dsas** [comment]
Possible solutions:
 * Implement an exemption to using global styles
 * Drop the has the colour changed check in https://github.com/Automattic/wp-calypso/blob/33f1e2061bd17111464e5f19c047dee634105cba/client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-post-setup/index.tsx#L77
 * Pass the `preview-global-styles` GET var when GETing the site-accent-color endpoint

**Comment by dsas** [comment]
#73509 passes the `preview-global-styles` GET var. This means that the UI now knows the actual colour saved rather than using the gated (default) value, and so saving the default colour now works.

This by itself is not sufficient - it will save the default colour to the global styles CPT but this means that the GS CPT exists and has non-empty style values, and so is still eligible for gating.

A follow-up change is required where if the default colour is set, the back-end will realise this and remove the colour setting from the GS CPT.

**Comment by mmtr** [comment]
> A follow-up change is required where if the default colour is set, the back-end will realise this and remove the colour setting from the GS CPT.

D103333-code
