### ISSUE TITLE
Block: Full Width and Wide Width alignments are missing from image-related blocks

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#73417]
### Quick summary

It seems like Full-Width alignment and Wide-Width alignment are missing with websites using FSE themes. This issue happens on websites with the following conditions:

- Simple site (WPCOM)
- FSE theme is active

For now, all image-related blocks (Cover Block, Image Block, Tiled Gallery Block, Gallery Block) has no either Full Width or Wide Width.

### Steps to reproduce

1. Activate Block Theme: Twenty Twenty Three, for example
2. Open page/post editor
3. Create a Cover Block
4. Click block toolbar to set the Cover Block to Full Width or Wide Width

### What you expected to happen

To see an option to set the Cover Block/Image Block to full width or wide width

### What actually happened

No such option on the block toolbar.

<img width="774" alt="Screenshot 2023-02-16 at 4 21 20 PM" src="https://user-images.githubusercontent.com/44726232/219307937-bcccfe5d-5520-45f0-a164-11a7f0ecabd8.png">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The first report is on Slack: 
p1676532945430879-slack-C03TY6J1A

I can replicate the issue on my personal blog (Simple site) and two of my test sites (Simple sites)

**Comment by vinnykaur** [comment]
📌 SCRUBBING : RESULT

- Tested on Simple - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- The issue is replicable on themes like `Blank Canvas` and `Bitácora` as well. Below is a screen record from a simple site using the `Blank Canvas` theme.


https://user-images.githubusercontent.com/49183855/219331895-26481f17-5119-40cf-951a-bf9e535f7f6c.mov


📌 ACTIONS

- Marked as Triaged for Quality Squad review

**Comment by vinnykaur** [comment]
User report: 5962836-zen

**Comment by rw-ye** [comment]
I tried to reproduce this issue on the `Twenty Twenty-Three` and `Blank Canvas` themes, however, I wasn't able to. The wide-width and full-width options are visible to me. 


<img width="958" alt="Screenshot 2023-02-16 at 6 48 12 pm" src="https://user-images.githubusercontent.com/21261509/219332961-634d0830-ae54-4c4d-81eb-f52749002086.png">

Tested on three of my simple sites and the templates were using default settings.

**Comment by NoHopeRadio** [comment]
In 39807213-hc we are seeing this issue when the template for the page is set as one of the theme defaults, but not when using a user created template.

Varese theme.

**Comment by zdenys** [comment]
5966832-zen theme Zoologist

**Comment by masperber** [comment]
40733443-hc theme Byrne. Taking the site Atomic fixed the bug.

Can reproduce on my test site with several other FSE themes. Taking the test site Atomic fixed the bug there as well.

**Comment by metabreakr** [comment]
I was able to reproduce this using TT3 for pdEkSe-2hI-p2

A workaround that works for me:

* Group blocks together
* Check "Inner blocks use content width" (this part might be optional)
* Set block width
* Ungroup blocks, and width value will be retained

**Comment by metabreakr** [comment]
Also encountered this issue in Zoologist for pdEkSe-2eg-p2

**Comment by rw-ye** [comment]
Another report - 5962672-zd-woothemes

**Comment by poeticabdul** [comment]
Another report 5966861-zen

**Comment by cintacks** [comment]
Another report: 5969077-zd-woothemes

Workaround worked for me: https://github.com/Automattic/wp-calypso/issues/73417#issuecomment-1435251999

**Comment by ccwalburn** [comment]
Another report: 39135993-hc
Workaround did not work.

**Comment by hngdny** [comment]
Another report: 40741619-hc

**Comment by NoHopeRadio** [comment]
40573516-hc , only "Blank" template seems to work

**Comment by tanjoymor** [comment]
Speculation question here... is it possible that this bug is related to the "age" of the site? I can reproduce the bug on my older simple sites, but on any newer sites the bug doesn't surface (this with setting up old and new sites with all the exact same setup). If someone wants to ping me, I'm happy to share details of the sites I've been comparing (not sure if I should include relevant links for that here or not).

Edit: also to add that the Group block option doesn’t work either as on these sites the Group block doesn’t give any alignment options, regardless of the sidebar settings.

**Comment by retnonindya** [comment]
On the Slack thread -- p1676535319834749-slack-CBTN58FTJ -- @tanjoymor wondered if the issue happens on old websites.

My personal blog was created on 2016, so perhaps it was related. 

However, I then checked one of the websites reported here (this one: https://github.com/Automattic/wp-calypso/issues/73417#issuecomment-1434561206 ) and I noticed the website was created relatively recently (3 months ago) 🤔  Sooooo... Yeah, not sure what're the similarities between the sites reported here and why it is quite tricky to replicate 🥲

**Comment by danielk-am** [comment]
38342184-hc → 5981194-zd

Shared a workaround by adding a Group block, then select the align option. Ungroup after selecting the align option.

40897689-hc

Shared the workaround using the Group and Ungroup approach.

**Comment by metabreakr** [comment]
Unable to set width for columns block in Russell theme for pdEkSe-2iV-p2 and my workaround doesn't work in this case.

**Comment by jp-imagines** [comment]
Another report in 5971260-zd-woothemes on Quadrat White.

**Comment by jordesign** [comment]
Just noting that a fix for this should be coming with Gutenberg 15.2 in the next few days

**Comment by tellthemachines** [comment]
@jordesign afaik a similar issue was fixed for hybrid themes, but this is happening on block themes so is unlikely to be fixed by the same change. 

I can reproduce this issue on a dotcom test site with Zoologist theme enabled, but not on a self-hosted site with the same theme.

The differences I spotted between the dotcom and self-hosted instances are the following:

* on dotcom, the root content wrapper for the post editor has an `is-layout-flow` classname, whereas on self-hosted the same content wrapper has `is-layout-constrained`. `is-layout-constrained` is the correct classname when the Post Content block has "Inner blocks use content width" enabled in the site editor. Why might this be happening? It could be that when the post editor loads it doesn't have access to the Post Content block layout attributes.
* on dotcom, the template selector in the post editor sidebar displays the template name as "default template" and doesn't allow editing it, whereas on self-hosted the template name is displayed as "single" and it is editable. I suspect this may be because [getEditedPostTemplate](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/store/selectors.js#L510) is returning null for the dotcom site, which means the template isn't being found in the database. I'm not sure why this might happen.

dotcom template selector:

<img width="307" alt="Screenshot 2023-02-23 at 11 53 24 am" src="https://user-images.githubusercontent.com/8096000/220799838-48d717ae-164f-45ce-89c1-182584cd5f30.png">

self-hosted template selector:

<img width="304" alt="Screenshot 2023-02-23 at 12 00 20 pm" src="https://user-images.githubusercontent.com/8096000/220799849-c7cff83f-73f6-4df3-8c73-d667a87ee308.png">

**Comment by vinnykaur** [comment]
hc-33350889 using theme Twenty Twenty-Two (Swiss)

**Comment by vajrasar** [comment]
- [ ] 5985415-zen 

Issue can be seen on site with TT3 theme, but not on my own test site with the same theme.

**Comment by kylemcph** [comment]
Another report in 5981916-zen. Workaround from [#73417 (comment)](https://github.com/Automattic/wp-calypso/issues/73417#issuecomment-1435251999) worked for their site.

**Comment by zdenys** [comment]
5979360-zd-woothemes Theme: Blank Canvas 3

**Comment by poeticabdul** [comment]
Another report 5985924-zen Cultivate theme

**Comment by sharonlaker19** [comment]
- [ ] 5984979-zen

Attar theme. They'd like to be updated once the bug is resolved.

**Comment by carinapilar** [comment]
Got another report on 40929819-hc

**Comment by tellthemachines** [comment]
Update: this might be fixed in https://github.com/WordPress/gutenberg/pull/48386, which is targeted for 15.3 but might conceivably be included in a minor release beforehand if needed.

**Comment by thekingsprojects** [comment]
Another case here: 5982351-zen

**Comment by kavyagokul** [comment]
Ran into this in 34155464-hc

**Comment by sophiegyo** [comment]
Report on Premium site: https://wordpress.com/forums/topic/image-not-showing-full-width

Could not use the [workaround](https://github.com/Automattic/wp-calypso/issues/73417#issuecomment-1435251999) since the group block does not offer a width option in the post editor at this time, and also appears to be missing the alignment option.

**Comment by mdtanjid0** [comment]
- [ ] 5982351-zen ( needs to follow up ).

**Comment by kylemcph** [comment]
Another report on 41065556-hc

**Comment by priethor** [comment]
The potential fix in https://github.com/WordPress/gutenberg/pull/48386 has been backported to the 15.2 branch and is available in the just-published Gutenberg 15.2.2. Could anybody confirm whether this is fixed after Dotcom is updated to 15.2.2?

**Comment by metabreakr** [comment]
@priethor I cannot set a media & text block's with in TT3 when site building for pdEkSe-2kH-p2 on simple.

Edit: same goes for columns blocks. We've had to group and manually add `alignfull` and `alignwide` classes to these.

**Comment by Robertght** [comment]
It looks like 15.2.1 is delayed until this week based on this p4TIVU-arQ-p2

@fullofcaffeine could we get a heads up when the above is implemented?

**Comment by sharonlaker19** [comment]
- [ ] 40508318-hc

They'd like an update when the bug is resolved.

**Comment by marianearchimbaud** [comment]
40757654-hc

Reported here as well. We used a Group block to try to reach the full-width option for an Image block

**Comment by mxhassani** [comment]
41069209-hc similar with Columns block

**Comment by sanjeev00733** [comment]
Another case here: 6004008-zen

**Comment by ariel-maidana** [comment]
5999141-zd-woothemes
Please let the user know once this issue is fixed.

**Comment by jordesign** [comment]
Noting that the fix in Gutenberg 15.2.x is now deployed on Simple Sites. We'll need to wait for Atomic sites as well - but this is close to being resolved.

**Comment by vajrasar** [comment]
Gutenberg v15.2.4 is now deployed to WoA sites. I checked and I can no longer replicate the issue. We are now in process to inform the affected users. More update soon.

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by zdenys** [comment]
Oddly in 41345321-hc user was still missing full width controls for Cover Block with Gutenberg 15.2.4 active on WoA. Turning it off fixed the issue.

**Comment by tellthemachines** [comment]
@zdenys if it's a block theme and the Post Content block _doesn't_ have content width enabled, the controls are expected to not show for root blocks in the post editor. Might that be the case?

**Comment by tanjoymor** [comment]
I confirmed what @tellthemachines has explained, on a test site using the same TT3 theme as the user @zdenys was referring to. On an Atomic site, in the Site Editor, if the Layout setting on the Post Content block for "Inner blocks use content width" is off:
<img width="1636" alt="Markup 2023-03-07 at 20 26 10" src="https://user-images.githubusercontent.com/42655541/223612374-a304503e-b05e-4c1e-87b8-28951257a905.png">

The Cover block does not have the wide and full width options in the Page editor:
<img width="814" alt="Markup 2023-03-07 at 20 25 53" src="https://user-images.githubusercontent.com/42655541/223612405-4c8e58d7-b6c2-4b1f-9bbe-969736c596a4.png">

If this option is on:
<img width="1638" alt="Markup 2023-03-07 at 20 27 06" src="https://user-images.githubusercontent.com/42655541/223612421-aa11f983-8c20-443e-9a9a-d5ef6672d6cc.png">

The wide and full width options are available:
<img width="773" alt="Markup 2023-03-07 at 20 26 48" src="https://user-images.githubusercontent.com/42655541/223612461-dca56de6-98ca-4ace-8da5-9aa017e5d839.png">

The user still has the Gutenberg plugin deactivated, so I didn't change that in order to test specifically on their site.

**Comment by zdenys** [comment]
Thank you @tanjoymor! That checks out and is a TIL for me. Yet, as a user, go figure out all of that 😶‍🌫️

**Comment by tanjoymor** [comment]
Yup @zdenys I totally hear you!
