### ISSUE TITLE
Bug: Hide "Install new theme" in theme showcase when uploads aren't enabled

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73489]
### Details

When the site is not permitted to upload themes, we should not show the _Install new theme_ button on the theme showcase. You can see it in the top right of the screenshot below:

<img width="1440" alt="Screenshot 2023-02-17 at 15 15 07" src="https://user-images.githubusercontent.com/3376401/219662693-5cc47826-424c-4584-a380-82b46c5bf0d4.png">

### Checklist

- [ ] Free eCommerce trial sites should not see the _Install new theme_ button

**Comment by sixhours** [comment]
I noticed while I was working on this that the current behavior is not to hide the button for sites that could qualify to upload themes, but to show them the theme upload screen with an upsell:

<img width="1085" alt="Screen Shot 2023-02-28 at 1 17 19 PM" src="https://user-images.githubusercontent.com/2124984/221943842-d1aababb-9fc9-4dca-9739-f5de66d127af.png">

Would it make more sense to keep the button but change the upsell messaging (as an encouragement to upgrade) rather than hiding functionality?

**Comment by daledupreez** [comment]
> I noticed while I was working on this that the current behavior is not to hide the button for sites that could qualify to upload themes, but to show them the theme upload screen with an upsell

Excellent catch, @sixhours! I think your proposed approach is likely the best one -- I missed that there was an upsell on that page.

**Comment by sixhours** [comment]
I updated my approach in #73901 !
