### ISSUE TITLE
Task: Investigate default store details on free trial

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73539]
### Details

We have now had multiple reports of users getting unexpected store and currency details when creating a new eCommerce trial site:
 * pdtkmj-182-p2#comment-2064
 * pdtkmj-182-p2#comment-2086

We need to investigate how we're doing the defaulting, and whether that makes sense.

### Checklist

- [x] Work out how we're defaulting the store location and currency for free eCommerce trials

**Comment by that-mike-bal** [comment]
If there is no address, it is defaulting to the first country on the list in alphabetical order. Don't fallback and leave the task incomplete if possible.

**Comment by sixhours** [comment]
Digging into this, when we set up WooCommerce on an Atomic site, we grab the user's address information from their billing details and populate the `woocommerce_*` options with that:

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Spynff%2Qjbbpbzzrepr%2Qznantre.cuc%3Se%3Qo36s1n46%23210-og

**Comment by sixhours** [comment]
It doesn't look like we do anything to change the `woocommerce_currency` option upon setting up the site; it's set to USD by default.

Should we update it to match the user's currency in the billing store if possible? Or leave as-is for now?

**Comment by sixhours** [comment]
> Digging into this, when we set up WooCommerce on an Atomic site, we grab the user's address information from their billing details and populate the woocommerce_* options with that:

I've confirmed that if the country code for billing address is empty, or does not match the available country codes in WooCommerce*, it will fall back to the first item in the menu (Afghanistan). That menu doesn't allow for an empty value, so it's likely this is happening when a user hasn't provided their billing address/country code yet.

I see a couple potential avenues for fixing this, although all of them require the user add their billing information manually:

* Don't update the user's billing data when we transfer to Atomic. This means the user will be prompted by the checklist to fill out their billing information manually.
* Allow the country code field to be empty. This requires an update to WooCommerce, and if it's left empty, the user would also be prompted to fill out their billing information manually via the checklist.
* When setting up the site, we could re-use the `storeAddress` step after WooCommerce is activated and prompt them to add their billing information.

I lean toward option 1 since we ultimately have to ask the user to update their billing info no matter what, and it's the simplest solution to implement given the time frame.

_* It's also possible the codes we have in our billing data don't line up with the expected codes in WooCommerce, but I haven't confirmed this yet. For example, I can use a valid country code, `ZA`, but WC requires it be formatted like `ZA:SN` where SN is a valid state code as well. If I don't provide a country/state combo to WC for those countries that have states, it will once again fall back to the first item in the list (Afghanistan)._

**Comment by daledupreez** [comment]
@sixhours, I think we should go with option 1, where we don't set any values for the store specifically for sites on the eCommerce trial. I think that's a reasonable first pass. We do want to pull these values in from the WooCommerce.com onboarding flow, but we have separate tasks for managing that.

_Sidebar_

The existing logic here is specifically pulling up information that we've previously stored for user purchases, especially domain registrations (where we collect a lot of address details), so I don't know that it's going to be super reliable, especially if WooCommerce requires the state/province. (I know that some countries don't have any sub-divisions like that, so I am hoping the requirement varies from country to country.)

It may be worth looking at whether we can easily validate or limit the values we can/should inject to avoid unexpected values.

**Comment by sixhours** [comment]
Started working on this in D103363-code

**Comment by sixhours** [comment]
I merged and deployed D103363-code but I'm seeing the previous behavior at `/setup/wooexpress` (sites are created with pre-populated contact info from billing); I'm not sure if there's some kind of Atomic cache or if we don't have access to the blog sticker at that point in the setup. We should test this again tomorrow to make sure it's actually working as expected.

**Comment by daledupreez** [comment]
I confirmed that the code that kicks off the transfer to Atomic is hooked in to the product activation hook before the function that sets the blog sticker we are checking for. 

That should be addressed in D103466-code.

**Comment by daledupreez** [comment]
I've just deployed D103466-code, and the store details are no longer being defaulted in for eCommerce trials.
