### ISSUE TITLE
Fix the hyphen bread word issue on Safari

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#73580]
Original discussion: pdtkmj-1ay-p2#comment-2134

Sidebar menu text shows slightly different on Safari. Desktop Safari wraps the phrase Move to WordPress.com in the sidebar differently than Chrome or Firefox, which almost makes it look like it’s saying Word-Press.com

![Image](https://user-images.githubusercontent.com/4074459/220309770-56cf6385-7246-43ba-8cf9-ef50576759dd.png)

**Comment by bogiii** [comment]
The Sidebar CSS file contains the `-webkit-hyphens` property with an `auto` value which has been properly read by Safari but not with Chrome (probably doesn't support it).


![Image](https://user-images.githubusercontent.com/1241413/220474099-896251c7-8364-4846-9f86-d75759c1d76c.png)



This is out of scope since it's a generic style for the sidebar.

cc @ouikhuan

**Comment by ouikhuan** [comment]
Thanks for looking into it @bogiii ! This makes sense, I'll close the issue for now.
