### ISSUE TITLE
Upsells: Hide second upsell in /themes if fewer than 6 rows

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#73672]
Following up from https://github.com/Automattic/wp-calypso/issues/73110

We need to hide the 2nd upsell in /themes if there are fewer than 6 rows of results. Slack conversation for reference: p1677082943014849-slack-CKZHG0QCR

Screen shot of too many upsells given the amount of results.
![1-results-2-upsells](https://user-images.githubusercontent.com/140841/220703697-dcdcb5e6-c5f2-4b9e-ac5a-c92a80b2d4ba.png)

**Comment by candy02058912** [comment]
Since we did this with CSS grids, there doesn't seem to be an easy way to hide it with pure CSS.
I'm planning to
1. calculate how many items are in a row with JavaScript
2. Get the minimum amount of themes needed: items per row * 6 rows
3. Decide whether to show the second upsell by checking if the number of themes are greater than the number we get in `2.`

**Comment by lupus2k** [comment]
I tried playing with all the grid properties but couldn't make it.

The best option for me is to choose the minimum number of items to show the upsell. We can use different numbers for mobile or desktop.
