### ISSUE TITLE
Review Email Login Section design.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73728]
The Email Login Section can now be seen on `wordpress.com/email-subscriptions` as a logged-out user (incognito).

Let us know if you have any feedback on the implementation of the design.

**Comment by yansern** [comment]
One thing I'd like to add is when a logged-out user enters the page, it redirects to the portal immediately, which begs the question of whether it should detect whether a user is logged-in, then instead of show the email form, show some text saying "You are logged in as X, you can manage your subscriptions through the portal. [Blue Button Here]"

**Comment by saygunnyc** [comment]
Fantastic to see this!
IMO, no matter the user's status, this UI should stick to its purpose, sending a link to their email address and not managing subscriptions. I don't know if there are technical difficulties in doing so or if there's a case I'm missing. Please elaborate if so. Leaving a few notes below as well.

- **1.Footer:** One thing that stood out to me is the difference in the footer. Not sure if that's because of Landpack, but ours look and function a bit differently than the WordPress.com logged-out homepage (grid, underlines, hover states).–We should align.

**Desktop**
**WordPress.com Landing Page**
<img width="1835" alt="D-Footer_LOHP" src="https://user-images.githubusercontent.com/78876323/221694959-868973e6-7303-4bb4-b6aa-8ef7febf862d.png">

**Subscriptions LP**
<img width="1836" alt="D-Footer_Subscriptions" src="https://user-images.githubusercontent.com/78876323/221695117-768f7f84-4cb1-4949-8944-bbd49eb0863a.png">


**Mobile**
**WordPress.com Landing Page**
<img width="499" alt="M-Footer_LOHP" src="https://user-images.githubusercontent.com/78876323/221695244-01cf5c35-3af2-4683-bebd-0e5af1bdf761.png">

**Subscriptions LP**
<img width="500" alt="M-Footer_Subscriptions" src="https://user-images.githubusercontent.com/78876323/221695293-cc4114e4-e64d-4e8a-930b-7e8f47f95c8e.png">



- **2.Focus State of Primary CTA:** We've designed focus states for the tailored use case flows as we worked on them. It would be good to align the Primary CTA's focus state with it. Pinged on where relevant over the Figma. 

**Current Focus State**
<img width="265" alt="Focus State - Update w Launched Flows" src="https://user-images.githubusercontent.com/78876323/221695740-7e1c7e24-2478-42ea-bc24-0e72fe0dfa99.png">

**New**
<img width="1353" alt="Screenshot 2023-02-27 at 5 04 10 PM" src="https://user-images.githubusercontent.com/78876323/221696311-38419a3c-4724-47e1-aab0-8210902e9417.png">



- **3.Login Link:** The login link ("Already have an account? Login here.) didn't work for me, and I got stuck here.
<img width="1198" alt="Screenshot 2023-02-27 at 5 06 49 PM" src="https://user-images.githubusercontent.com/78876323/221696796-73e2cfeb-0eb8-473e-b7ab-e9048ff0f48c.png">

- **4.Reader Experience CTA**: It would be good to open this up in a new window rather than the same as it links to a support doc.



Hope this is helpful!

**Comment by yansern** [comment]
> 1. Footer: One thing that stood out to me is the difference in the footer. Not sure if that's because of Landpack, but ours look and function a bit differently than the WordPress.com logged-out homepage (grid, underlines, hover states).–We should align.

For the alignment of footer styles, we'll work with @alshakero on that. Context: p1677186834327989/1677185561.338199-slack-C02TCEHP3HA

> 2. Focus State of Primary CTA: We've designed focus states for the tailored use case flows as we worked on them. It would be good to align the Primary CTA's focus state with it. Pinged on where relevant over the Figma.

Is there already a component built for this style of focus/hover button? Landpack buttons (`.lp-button .wp-block-button`) and regular landing page buttons (`.lpc lpc-button`) have different button focus & hover states too. Pulling in Claudiu for advice. @claudiucelfilip is there a plan to standardize the buttons across pages too?

> 3. Login Link: The login link ("Already have an account? Login here.) didn't work for me, and I got stuck here.

Looks like there's a `%3` typo in the URL, the correct URL is:
`https://wordpress.com/wp-login.php?redirect_to=https%3A%2F%2Fsubscribe.wordpress.com%2F`. cc @ivan-ottinger 

> 4. Reader Experience CTA: It would be good to open this up in a new window rather than the same as it links to a support doc.

Got it. But in the updated copy, the link to the reader experience is removed, the reasoning was around how linking to a support doc doesn't quite help sell the Reader product.

**Comment by ivan-ottinger** [comment]
> Looks like there's a %3 typo in the URL, the correct URL is:
https://wordpress.com/wp-login.php?redirect_to=https%3A%2F%2Fsubscribe.wordpress.com%2F. cc @ivan-ottinger

Thanks for the ping, Yan. I have added the fix to the following PR (currently un review): https://github.com/Automattic/landpack/pull/1238.

**Comment by claudiucelfilip** [comment]
> is there a plan to standardize the buttons across pages too?

@yansern I don't think there is.
The non-Landpack pages haven't been updated lately and their styling hasn't changed much since they were implemented in https://github.com/Automattic/landpack/pull/1224 . Changes in Landpack don't reflect on non-Landpack pages so we'd need to sync them up. Also, we can expect a few non-Landpack pages (or event components) to implement their own button styling. 
Therefore, trying to match button UI on all the LPs might become non-trivial.
We should probably try to match the UI styling at least for the most relevant pages, such as:
* Landpack pages - they all share the same CSS
* LOHP
* /pricing
* /create

This is similar to the Footer; I believe that the Landpack Footer styling has been recently updated and we'd need to sync the changes with the non-Landpack pages. This effort will need to be replicated to a couple of Calypso Logged-Out sections (/plugins and /themes) which also show the Footer and IIRC there are a few themes that use the same Footer.
We've opened a task for it https://github.com/Automattic/martech/issues/1328 to update the Header and Footer sections with the new design but haven't gotten around to doing it yet.

**Comment by yansern** [comment]
> This is similar to the Footer; I believe that the Landpack Footer styling has been recently updated and we'd need to sync the changes with the non-Landpack pages.

So Landpack Footer is the source of truth in the latest design @claudiucelfilip?

--- 

Also, closing this issue as the task of reviewing the design is done. Next steps:

- Footer design discrepancy will depend on the Universal Footer unification -or-when Martech/Landpack folks sync the changes with non-Landpack pages.
- CTA button states we'll follow Landpack's. Created issue here: https://github.com/Automattic/wp-calypso/issues/74035
- Login link is fixed through this PR https://github.com/Automattic/landpack/pull/1238
- Reader Experience link was removed after a copy change.
