### ISSUE TITLE
Add Template Name for 'Default template' in Template selection dropdown

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#73793]
### What

I would like to add a **Template Name** for **'Default template'** in the Template selection dropdown. 

### Why

Currently, the default template is listed as **Default template**, which makes it tricky to understand whether it is a **Single** or a **Blank** template. The Template name appears after you select it from the list and not in the dropdown.

![Screen Capture on 2023-02-26 at 10-37-28](https://user-images.githubusercontent.com/8070771/221393445-4f904ffa-9716-4683-81c0-090c0d0d472d.gif)

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

📌 Message to Author
- Thanks @syhussaini ! Are you suggesting that you'd prefer to see "Single" listed in the dropdown menu, instead of "Default Template"?

I've also run into many situations where I see "Default Template" listed in the page/post sidebar, and not "Page" or "Single" - which is also leaving things less clear for the user.

What do you think about having both the sidebar and the dropdown say something like "**Default Template: Single**" - that way we take the opportunity to communicate right there what's going on?

**Comment by annezazu** [comment]
Closing this out as the experience has evolved to be both more visual and to include the name of the default template upon switching to it:

https://github.com/user-attachments/assets/a5b7d5eb-ef6d-400b-9b02-fead4d952e09
