### ISSUE TITLE
pls improve the performance

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#73794]
### Quick summary

Dear WordPress.com Support team:

By writing this email, I use the tools in case to test the performance of the site, cf. https://pagespeed.web.dev/report?url=https%3A%2F%2Fttcath.org%2F&hl=zh-CN

According to the reports, that the Time to Interactive and Total Blocking Time is very slow, also, some plugin provided by WordPerss.com cause the problem. Please help to fix these problems at once. 

Again, I don’t want to receive any incidents reports from any other monitor service provider, because in some countries outside of China, the homepage of the website load very slow. So, please check and report to your developer team, inquiry them fix the problem. Before they do the fix, please ask my permission, without my permission, you cannot do any change on the site.

### Steps to reproduce

1. open  https://pagespeed.web.dev/
2. key in the domain www.ttcath.org
3. get the results

### What you expected to happen

Time to Interactive and Total Blocking Time is very slow, also, some plugin provided by WordPerss.com cause the problem. 
please help to fix.

### What actually happened

see the report 
https://pagespeed.web.dev/report?url=https%3A%2F%2Fttcath.org%2F&hl=en

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

see the report 
https://pagespeed.web.dev/report?url=https%3A%2F%2Fttcath.org%2F&hl=en

**Comment by ttcath** [comment]
@tyxla please help to fix the problems.

**Comment by tyxla** [comment]
Hey @ttcath,

Thanks for getting in touch! 

We don't normally provide high-level support via GitHub. We usually use GitHub for development, collaboration, and working on concrete and specific issues and bugs. 

I'd recommend heading to wordpress.com and once logged in, clicking on the question mark in the top right of your screen, which will take you to our support section. Alternatively, you could head to https://wordpress.com/support/ where there are multiple ways to get help.

**Comment by ttcath** [comment]
@tyxla thx. I allready wrote a email letter to WordPress.com Support Team, but they can not solve the problem. Please look at the tickets open to WordPress.com Support Team first.

**Comment by tyxla** [comment]
Thanks for confirming @ttcath, that was helpful. 

I wonder if this has something to do with the recent Gutenberg performance issues you've been mentioning recently @sgomes?

**Comment by sgomes** [comment]
@tyxla : No, this appears to be unrelated to the Gutenberg performance issue (which is now fixed).

I ran [a quick performance analysis](https://www.webpagetest.org/result/230228_AiDcC2_798/1/details/#waterfall_view_step1). Since the complain is related to users outside of China, I used a USA testing location.

The performance is honestly, quite reasonable. LCP is at 3.7s, which is above the target, but taking into account the network throttling and the geographic conditions, is acceptable. If I could offer some advice here, it would be to switch to a theme that does not make use of `jQuery` (to have less JS in the critical path), and doesn't enqueue quite as much CSS (to have less CSS in the critical path). Ensuring all images have width and height set could also help for other metrics, like CLS.

Google's automated tooling, being automated, isn't perfect, and seems to be making several key errors here:
- It treats all JS equally, both JS that's in the critical path (such as `jQuery`), and JS that's loaded after first render, such as Facebook and Twitter JS.
- It incorrectly reports a Time to Interactive of 9.3s, which is grossly overestimated. The above WPT test, performed using the same emulated hardware (Moto G4), reports just 1.2s, which isn't ideal, but is a long way from 9.3s.
- It incorrectly reports a Cumulative Layout Shift of 0.43, when the above test reports just 0.23. Also, I don't see from their filmstrip how it could possibly be 0.43; there don't seem to be any large shifts happening, only a bottom bar being overlaid on top of existing content.

As such, it seems to me that the problem here isn't the user's site, but instead Google's tool grossly misrepresenting the site's performance.

**Comment by ttcath** [comment]
@sgomes thx for reply.

I run[a quick performance analysis](https://www.uptimia.com/website-availability-test/99ee5dac) it seems that in some countries, the performance is not acceptable.

Also, as I send a root cause report to WordPress.com Support Team by email, that the average of load speed for last three days is 5.91 sec. and Average response of SSLfor last three days is 34ms, average load speed of Transaction for last three days is 13.41 sec. 

[a quick performance test] (https://tool.chinaz.com/speedtest/ttcath.org), it shows the performance in mainland China, pls also help to investigate, try to find the way to troubleshoot the problems.

Both of those test is from IPs outside of mainland China. 

@tyxla pls help to push to fix or optimize the problems.

**Comment by sgomes** [comment]
Thank you for the links, @ttcath!

I'm not sure I understand why you think the performance is not acceptable. I'm not familiar with the tool you used (`www.uptimia.com`), which seems to be more focused on availability than performance, but the tool itself claims a 93/100 performance score, which sounds pretty good.

More objectively, I also don't know what metric they're referring to by "loading speed". Is this the `load` event? If so, that's not particularly relevant for user-facing performance; you usually want to look at metrics like Largest Contentful Paint (LCP) instead, which take into account user perception and actual page content. As long as the page renders and becomes interactive quickly, it is perceived as fast by users, regardless of whether it's still making requests in the background.

That said, if you really want to bring down `load` time, then your best bet is probably to disable the various third-party scripts that are present on the page: I see Google Tag Manager, Google Analytics, Facebook, and Twitter scripts being loaded, at least. They all add extra resources to fetch, and they do so from third-party origins, which take extra time to establish connections to. One of them (Google Tag Manager) is even being loaded ahead of more important resources in your page, like images, therefore delaying them.

**Comment by ttcath** [comment]
@sgomes received, but according to the plan which I used, there is no any other plugins on the site. So I feel confused that there are too many bad reports which the uptimia.com reports. 

Also, please help to improve the accessiblity of the site, I saw the site load in mainland China very slow. Please do the investigation, thx.

**Comment by tyxla** [comment]
I've done some testing and I confirm what @sgomes said earlier that the site's performance is acceptable and not indicating any issues. In any case, if you notice a more specific issue that concerns you, don't hesitate to report it.

The same applies to accessibility. Generally, most of the themes tend to be fairly accessible, but if you have any specific accessibility concerns, feel free to report them. 

To conclude, we aren't able to reproduce any of the reported behavior, so unfortunately, there's not much we can do from here.

**Comment by ttcath** [comment]
@tyxla but I found that some of "Happiness Engineer“ allways make fake news about our site. They allways says "your website was block in mainland China", but in fact, the website can be visit in mainland China, but last time, it appear 429 error due to the security reason that WordPress.com Support Team limit the legal traffic from mainland China on mobile devices visit our website, now there is no more 429 error.

@sgomes Thank you so much for the test, but I think WordPress.com Developer must urge the Email Support Team be honest, and do not make any fake news, or create a link here, assign the take to revelent developer, so we could take directly.

Once again, thx @tyxla and @sgomes

**Comment by ttcath** [comment]
@sgomes @tyxla according to the report given by Uptima, it says:

Mar 11 2023, 01:08:49 SSL monitor invalid at the check point IP: 149.248.7.54 and 31.13.213.16 and 45.32.139.74 and 51.75.170.220, looks like the visitor from those IP can not pass the SSL verification. So, please check this as possible.

**Comment by jeherve** [comment]
This is currently tracked in #74358. I'll close this issue as duplicate.
