### ISSUE TITLE
[Block] Search: Button and Label options can't be changed when part of Navigation Block

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#73860]
### Quick summary

If we have a Search block in a Navigation block, we cannot completely hide the button of the search from the template. It does hide on the frontend though.

### Steps to reproduce

1. From Appearance > Site Editor, choose a template with a header and a navigation block and make sure it has the Search block
2. Select the search block and choose to not show any buttons.
3. Save the changes

### What you expected to happen

For the buttons to be hidden on the Site editor and frontend.

### What actually happened

The buttons were removed from the editor temporarily(until it got refreshed) and permanently from the frontend.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

I tested this on a self-hosted website as well as on a WordPress.com website with two different themes(Rusell and Quadrat) and the results are the same.

Video: https://www.youtube.com/watch?v=30bkreFWOFI

Screenshot

![8jobPv.png](https://user-images.githubusercontent.com/6737345/221770698-2b79a07b-435f-421d-82b4-074bc0d88840.png)

Ticket: 5989070-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Replicated
- Tested on AT: Replicated
- Tested on Self-hosted: Replicated
- Replicable on Core? **Yes**
- Looks to match this report: https://github.com/WordPress/gutenberg/issues/48410

📌 FINDINGS/SCREENSHOTS/VIDEO
- From my tests, it seems the issue here only is with the Search Block **inside a Navigation block**. There, giving the search block a label, or trying to change the button placement, is immediately reset in the editor.
- By contrast, a search block placed directly onto the template in the same editor can have all settings saved as expected.

**Self-Hosted Example**

https://user-images.githubusercontent.com/27249804/224522138-cd0e377d-d58d-4911-9ca8-d89e14ff7654.mov

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Updated title

📌 Message to Author
- @Robertght I'm not sure what you meant by _we cannot completely hide the button of the search from the template. It does hide on the frontend though._  Does this mean you were able to hide the button with CSS?

**Comment by annezazu** [comment]
I can't replicate this on WordPress.com:


https://github.com/user-attachments/assets/22df8802-a678-4676-ac78-87b3b824050e

Nor could I with a self hosted site so I closed out the original report too and will be closing this out as well :)
