### ISSUE TITLE
Site Assembler: The content of Home template might be incorrect

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#73978]
Referring to pdtkmj-1eO-p2#comment-2252, when you finish the Pattern Assembler step with **_the existing site_** and land on the site editor, the content is not the same as the patterns you selected.

**Reason**

The reason is we will replace the content of the homepage based on the `show_on_front` option. However, when we're customizing the content of the homepage, the `show_on_front` option is not configured to `posts` and it leads that headstart customizes the wrong homepage template.

**Reproduce Step**

1. Go to your site
2. Active the theme and its homepage is a `page`. Or go to `Settings > Readings`, and change the "Your homepage displays" to a page.
3. Go to `/setup?siteSlug=<your_site>`
4. Continue until you land on the Design Picker screen
5. On the Design Picker screen
   * Scroll down to the bottom, and select "Start designing"
7. On the Pattern Assembler screen
   * Select a header, section, and footer
   * Continue
8. When you land on the site editor, the content is not expected

**Comment by miksansegundo** [comment]
I believe this issue happens because [_resolve_home_block_template()](https://developer.wordpress.org/reference/functions/_resolve_home_block_template/) returns the homepage template using the site settings, but the template we want is the homepage template that the theme will use after headstart runs.  

A potential solution to this issue is to stop using the verticalization API and headstart to set the template's content in the assembler flow. 

We already create the Home template with the patterns from the browser at the end of the Assembler flow. I think we only have to confirm/set the site reading settings to default ("posts") for WP to use the Home template (assuming that the theme doesn't have a [front-page template](https://developer.wordpress.org/themes/basics/template-hierarchy/#home-page-display))

**Comment by arthur791004** [comment]
The reason is the `headstart_source_information` action run before we apply the settings to the target site. Hence, when we want to customize the home template, we get the incorrect template id. However, after applying settings to the site, the "homepage displays" setting is changed so that the customized home template is missing.

A solution is to separate `wpcom_verticalize_starter_content` into 2 parts and move customizing the home template to the `headstart_complete` action so that we're able to get the correct settings.

The other is as you mentioned. But we have to return the raw content of each pattern and we can do it after we fetch all patterns into Pattern Assembler.

**Comment by autumnfjeld** [comment]
This issue only applies for an existing site, doesn't apply to onboarding. But will be a relevant issue in a theme switch situation.

**Comment by autumnfjeld** [comment]
Can we close this issue @arthur791004 ?

**Comment by arthur791004** [comment]
D116100-code resolved this issue on the simple sites, and we can close it after deploying https://github.com/Automattic/wpcomsh/pull/1452 on the atomic sites 🙂

**Comment by arthur791004** [comment]
Closing it since https://github.com/Automattic/wpcomsh/pull/1452 is deployed.
