### ISSUE TITLE
Cover Blocks Break Some Jetpack Form Background Settings

### ISSUE THREAD

**Issue by ersatzpenguin** [Automattic/wp-calypso#74001]
### Quick summary

The "Single Choice" and "Multiple Choice" blocks in Jetpack Form blocks, when added to a form inside a Cover block, do not obey the background setting set in the editor and display with a white background instead.

A workaround is to not place the Form block in a Cover block—using a Group block or similar instead.

### Steps to reproduce

1. Add a cover block to a page, and a form inside it.
2. Add a "Single Choice" or "Multiple Choice" block to the form.
3. Observe issue in editor.
4. Save changes.
5. Observe issue on front-end as well.

### What you expected to happen

For form blocks to always respect the background setting set in the block's settings, regardless of where they are placed.

### What actually happened

Some blocks inside form blocks do not respect the background setting set in the block's settings when placed in Cover blocks.

### Example in editor:
![Markup on 2023-03-02 at 09:43:37](https://user-images.githubusercontent.com/10101587/222477184-d0170ce1-0e58-4bf3-aefb-77e59edac60b.png)

### Example on site:
![Screenshot 2023-03-02 at 9 40 44 AM](https://user-images.githubusercontent.com/10101587/222477256-415ca9e0-d19e-4be8-a48c-83dd477040bb.png)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Reported in 5953824-zd-woothemes

**Comment by ersatzpenguin** [comment]
Update: having a form block inside a cover block anywhere on the page will cause the issue to impact all other forms on the page—regardless of whether they are inside a form block.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could Not Replicate
- Tested on AT: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- From my tests, the "Single Choice" and "Multiple Choice" form blocks behave the same way as all other form blocks, whether they're in a cover block, a group block, or directly on the post. 

**AT Example**

https://user-images.githubusercontent.com/27249804/227379035-58061997-c017-4711-9172-b8afb651f34a.mp4

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @ersatzpenguin  are you still seeing the same inconsistencies from this original report?  If so, could you let me know if I should update any steps to replicate?  Otherwise, it seems like this might be seeing improvements/updates already! Thanks!

**Comment by ersatzpenguin** [comment]
Hey @cuemarie, I've tested again, and I'm still seeing the issue on both Simple and Atomic:

### Simple:

https://user-images.githubusercontent.com/10101587/227968787-c535fa1c-4d4f-4920-bb84-e74846e5a14d.mp4

### Atomic:

https://user-images.githubusercontent.com/10101587/227968930-414f97ed-2c1e-43b0-833b-a85793860d51.mp4


I also saw it while testing just the form block in a group (without a cover) on a simple site. What was interesting about this is that changing the field color did update the field color, whereas that same thing with a group block didn't work:

https://user-images.githubusercontent.com/10101587/227970166-ba5d4961-ea72-4b8c-93b6-10cbda0abc48.mp4

**Comment by jcheringer** [comment]
I was able to reproduce the issue too.
We'll try to come up with a fix in the next few days.

**Comment by cuemarie** [comment]
Thanks so much @ersatzpenguin ! Appreciate the recordings to show me what I was missing!  Confirming I can repro as well 😊

**AT Example**

![Screenshot](https://user-images.githubusercontent.com/27249804/228413040-ebe10231-a4f1-45e3-a14c-ce3dc78158e9.png)

📌 ACTIONS
-
- Looks like Jetpack is on this one already 🎉
- Moving to `Other`
