### ISSUE TITLE
Welcome Tour: update copy for pattern assembler experience

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#74089]
# Description

Currently the Welcome Tour uses language about "blocks".   We should make some small adjustments to the copy for the tour that shows for users that come through the Assembler experience.   The tour should provide continuity between what the user went through in onboarding and what they are about to (or might do) in the Site Editor.

You can access the tour yourself by going to an existing site and selecting "Welcome Guide" 
<img width="152" alt="image" src="https://user-images.githubusercontent.com/5665959/223053986-b33b642e-326d-447c-8fdc-b8af583d7516.png">

CURRENT
These are the initial  slides of the tour:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/5665959/223054874-9be97032-d06f-4546-ac42-bd21f1273bdd.png">

<img width="398" alt="image" src="https://user-images.githubusercontent.com/5665959/223054280-7f845e19-87f0-4720-a13e-9d5474527115.png">

<img width="395" alt="image" src="https://user-images.githubusercontent.com/5665959/223054197-d033f427-dd9b-427f-8e99-fc3d80184011.png">

**Some ideas I have:**

* For the PA flow, the second slide should mention patterns (not that the first slide is the intro slide) and how patterns are the easiest way to create a site from scratch. 
  * We might need a new image
* Then the following slide could mention blocks, and something about them being more simple or basic than patterns
* Somewhere it should be made clear that a site can be composed of both patterns and blocks, so as not confuse the user  

**Example:**
Slide 1 : stays as is
Slide 2: is about patterns
Slide 3: is about blocks
Slide 4: adapted to include both terminology abut inserting blocks or patterns

# Related
[Welcome Tour: update when/how it appears in the site editor and/or browse mode](https://github.com/Automattic/wp-calypso/issues/72533)

**Comment by davewhitley** [comment]
The tour is already 9 steps, so I think we should also take some away if we add more.

Proposal

1. [Keep the same] Welcome to WordPress! Take this short, interactive tour to learn the fundamentals of the WordPress editor.
2. [**New**] Using patterns: Use pre-designed website elements to make beautiful layouts.  
3. [**New**] Adding a new pattern: Click + to open the inserter. Then click the Pattern tab to explore patterns.
4. [Keep the same] Everything is a block: In the WordPress Editor, paragraphs, images, and videos are all blocks.
5. [Keep the same] Click a block to change it: Use the toolbar to change the appearance of a selected block. Try making it bold.

In this case we'd be adding 2 slides and removing 1 slide for a total increase of 1 slide. I didn't include the "adding a new block" slide because of redundancy.

I'd be open to making this change for all users, but we can also just keep alter it for SA users.

**Comment by autumnfjeld** [comment]
Autumn to check in with Lucas on this. Maybe get more input from designers.

**Comment by taipeicoder** [comment]
Closing since it's not planned.
