### ISSUE TITLE
Feature Request: Add login logs on admin panel

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#74080]
### What

I would like to see the login logs at Jeypack.

### Why

It can improve the security for the site.

**Comment by ttcath** [comment]
@trey pls

**Comment by ttcath** [comment]
@tyxla pls

**Comment by tyxla** [comment]
cc @Automattic/yamato-backup as AFAIK they're working on that product. There's a chance this is reported somewhere else. In fact, https://github.com/automattic/jetpack might be a better place to post a feature request for Jetpack Backup.

**Comment by ttcath** [comment]
@tyxla  got it. pls move this post to the proper place, in case to improve the products and user exprience. thx

**Comment by tyxla** [comment]
> @tyxla got it. pls move this post to the proper place, in case to improve the products and user exprience. thx

Sure, I've already pinged the team who knows better where to report it.

**Comment by ttcath** [comment]
> > @tyxla got it. pls move this post to the proper place, in case to improve the products and user exprience. thx
> 
> Sure, I've already pinged the team who knows better where to report it.

Okay, pls let me know at once.

**Comment by jeherve** [comment]
> There's a chance this is reported somewhere else. 

Logs are indeed already reported and available in [the Activity Log](https://wordpress.com/activity-log/), when using WordPress.com and its Business plan. @ttcath I see you do not use that plan on your site, so you will not have access to that data.

However, since your site is hosted on WordPress.com you do not really have to worry about malicious login attempts. This is something WordPress.com monitors for you. I would, however, recommend that you [enable two-factor authentication](https://wordpress.com/support/security/two-step-authentication/) and set a strong unique random password stored in a password manager. If you've already done that, you've already done a lot of keep your WordPress.com site secure.
