### ISSUE TITLE
Reskinned Portal: Disable batcache on wordpress.com/email-subscriptions.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#74095]
Batcache should be disabled under the following conditions:
- the host is `wordpress.com`
- AND the request_uri starts with `/email-subscriptions`
- AND the `subkey` cookie exists.

The file is `batcache-config.php`, see D103574#2103026-code for more context.

**Comment by phcp** [comment]
@yansern instead of editing `batcache-config.php` we could call `batcache_cancel()` as suggested by the the FieldGuide (cache/#page-cache). It could be placed on the Landpack block implementation or on the V2 class, I'll test these possibilities.

> You can bypass or turn off the batcache for the current page load by calling batcache_cancel() some time during page execution.

There is also a similar implementation on `subscribe-to-blogs.php` to disable the cache on the old page.
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sfhofpevor%2Qgb%2Qoybtf.cuc%3Se%3Q2oo19p09%23109-og

**Comment by yansern** [comment]
>@yansern instead of editing batcache-config.php we could call batcache_cancel() as suggested by the the FieldGuide (cache/#page-cache). 

Thanks for the findings! TIL!

**Comment by yansern** [comment]
Relevant patch. D103795-code
