### ISSUE TITLE
Mobile (Munchies theme): Cover Block doesn't displays incorrect image width

### ISSUE THREAD

**Issue by cintacks** [Automattic/wp-calypso#74111]
### Quick summary

Munchies theme specific:

When setting a min height on a Cover Block that uses a Post Featured Image within the `Single` Template, image width is not calculated correctly, resulting in images being horizontally cut off: https://shottr.cc/s/74FO/SCR-20230306-ftt.png

This may be affecting other themes as well but couldn't replicate on Zoologist

### Steps to reproduce

Example specific to: 6017188-zd-woothemes

1. Login as user
2. Remove custom CSS from theme 
3. See example of issue: https://shottr.cc/s/74FO/SCR-20230306-ftt.png

Could not replicate on test site - this might be user-specific.

### What you expected to happen

Image should be resized correctly on mobile

### What actually happened

Image did not resize correctly

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Workaround CSS:

```
@media screen and (max-width: 800px) {
	.wp-block-cover {
		min-height: auto !important;
		padding: 0;
	}
	
	img.wp-block-cover__image-background.wp-post-image {
		width: 100%;
		position: relative;
	}
}
```

**Comment by cuemarie** [comment]
📌 ACTIONS
- Requested author feedback

📌 Message to Author
- Hi @cintacks ! My understanding of this issue is that this is how the Cover block is designed to work.  From the [WordPress.com Public guide on the Cover block](https://wordpress.com/support/wordpress-editor/blocks/cover-block/#tips-for-choosing-an-image): 

> The Cover block uses the image as a background image, and will not resize to show the entire image width on different size devices. If you have content in the image that needs to be displayed for all device sizes, you would want to use an [Image block](https://wordpress.com/support/wordpress-editor/blocks/image-block/) instead.

This seems to apply to the user's case above. Can you let me know if there's something more here that I'm misunderstanding about the reported issue?  Thank you!

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Closing report for now. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
