### ISSUE TITLE
Global Styles -> Typography -> Links overriding block-specific settings

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#74234]
### What

Right now, it seems that global styles settings for Links override the Navigation block settings. For example, if there is a custom font size set for Links, selecting any font size in the Navigation block settings will not apply any changes.

I would expect to be able to customize the menu font size using the Navigation block settings, even if there are custom global styles settings.

### Why

It can cause confusion when a user tries to change the font size of the menu in the Navigation block settings and nothing happens.

This was the case when trying to guide a user to change the font size in this follow-up ticket: 6027253-zd-woothemes

Discussed on Slack: p1678306490128969-slack-C03TY6J1A

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

📌 Note
- There are a few reports about the Global Styles overriding block-specific settings that I wanted to note here: 
     - https://github.com/Automattic/wp-calypso/issues/72743
     - https://github.com/Automattic/wp-calypso/issues/74280

This was reported as a feature request because in the slack thread linked above, it was noted that: 

> the font size for the Navigation block applies it to the `li` element, and the setting in Global Styles applies it to the `a` inside that `li`, so the `a` sizing wins

**Comment by cuemarie** [comment]
- I've seen a few reports of Global Styles overriding block-specific settings, both here and in `/gutenberg`; wondering if this larger discussion is relevant: https://github.com/WordPress/gutenberg/issues/45086

**Comment by liviopv** [comment]
- [ ] 7465210-zd-a8c Custom font set for Links overrides Site Title Block

**Comment by Copons** [comment]
I'm closing this because it's a Core Gutenberg issue originating from the lack of Link style controls on blocks containing links. From a CSS cascading perspective, the problematic behavior is correct; however, in a real web design scenario, link styles are almost always overridden when used on primary layout elements (such as the site title or the navigation).

Here is a couple of directly related issues that are actively in progress:

- https://github.com/WordPress/gutenberg/issues/62987
- https://github.com/WordPress/gutenberg/issues/64670
