### ISSUE TITLE
Site Assembler: Review copy

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#74243]
We have a discussion on the copies below
* pbxlJb-3d0-p2#comment-2412
* pbxlJb-3d0-p2#comment-2417

Here are copies that need to change

| Screenshots | Before | Possible Candidates |
| - | - | - |
| <img width="310" alt="Screenshot 2023-03-09 at 3 59 51 PM" src="https://user-images.githubusercontent.com/13596067/223958605-a35c36de-9f37-4bc8-b078-626ed0e6f7f7.png"> | Create your homepage | Choose homepage patterns<br />Arrange your homepage<br />Layout your homepage<br />Homepage (*) |
| <img width="310" alt="Screenshot 2023-03-09 at 3 59 51 PM copy 2" src="https://user-images.githubusercontent.com/13596067/223958629-f776b109-85c8-40c2-aba2-1b3fef803fcf.png"> | Continue | Continue (*)<br />Go to the Editor<br />Edit your content<br />Open the editor<br />Customize your site |
| <img width="310" alt="Screenshot 2023-03-09 at 3 59 51 PM copy" src="https://user-images.githubusercontent.com/13596067/223958622-002b40e1-325c-4174-a566-8dc3739deafb.png"> | N/A | Click Continue to further customize your site.<br />Ready? Go to the Site Editor to edit your content. (*)<br />When you’re done selecting your options above, click the Continue button below. |
| <img width="305" alt="Screenshot 2023-03-09 at 4 01 47 PM" src="https://user-images.githubusercontent.com/13596067/223958634-e287213f-3faf-4922-86c4-e45d3878a60f.png"> | Done | Save (*)<br />Save Draft |
| <img width="306" alt="Screenshot 2023-03-09 at 4 11 21 PM" src="https://user-images.githubusercontent.com/13596067/223960429-4e4225f8-df67-4ccb-97c2-0af243e5a690.png"> | Add new patterns or re-arrange existing ones to create the structure of your page. | Add patterns and then re-arrange them to create the structure of your homepage.<br /><br />Create your homepage by adding and rearranging patterns. (*) |

**Comment by tanjoymor** [comment]
> Hmmm...the "Choose homepage patterns" is a bit longer 😂

😂 indeed! At least it’s in the middle? 🤔

Initial thoughts on the screenshots above:

“Add content patterns” is 4 characters less and uses less “wide” characters (such as: m p g). Not sure if that helps enough. Though personally, I’d lean more into the clarity and continuity of “Choose homepage patterns” than the space it takes. I am on the fence between “homepage” and “content”. 

For the Main panel button “Edit your content” is it possible to delay that from displaying until after patterns have actually been selected? If it’s there right at the start users might think that’s the starting point. (“Continue” could have the same effect too.)

(I’ll fully test again when I’m back at my computer.)

(I had this comment on the PR then thought maybe it should be here for discussion, now I’m not sure lol. I can move it back to the PR if you want lol.)

**Comment by tanjoymor** [comment]
Of the options above, my votes are:
1. Choose content patterns (new suggestion lol)
2. Edit your content
3. Click the button below to open the Site Editor (new suggestion lol)
4. Save
5. I like the new suggested wording

On the panel for “Create your Home” if the full wording feels too long, it could say “Choose patterns” there because there’s the paragraph below that explains it. 

Are we planning to add anything at the top of the panel that displays the patterns?

**Comment by davewhitley** [comment]
I think all menu items should follow suggestions from here pbxlJb-3d0#comment-2379

- Header
- Footer
- Homepage
- Styles
- Colors
- Fonts

2. Keep "Continue" but...
3. Add "Ready? Go to the Site Editor to edit your content." above the button. I like it! I came up with "Click Continue to further customize your site." because I wanted to keep it generic. I don't think we can always assume that clicking the button will open the Site Editor. I wanted to write something that conveyed, "This part is done and now you are going to the next step of launching your site." I think "Ready? Go to the Site Editor to edit your content." is fine to use for now though.
4. Save — I like it!
5. I don't have much of an opinion here, but I'd tweak it to be a bit less robotic. Something like, "Create your homepage by adding and rearranging patterns."

**Comment by autumnfjeld** [comment]
> 1.  I think all menu items should follow suggestions from here pbxlJb-3d0#comment-2379

@davewhitley  Something is wrong with that link....I can't click it.   But I get the jist and definitely agree! The simple labels work nicely.

> 5. I don't have much of an opinion here, but I'd tweak it to be a bit less robotic. Something like, "Create your homepage by adding and rearranging patterns."
Agree that we coudl be less robotic.  Le't avoid terms like "structure of your page".     Dave's suggestion works for me. 😄 

@arthur791004  I agree with everything Dave said.

**Comment by arthur791004** [comment]
@autumnfjeld The link should be pbxlJb-3d0-p2#comment-2379 and I totally missed "Change list names" 😂

**Comment by tanjoymor** [comment]
Oh! Haha me too @arthur791004 on the list names. That does simplify things 😂 Would it make sense to tweak the paragraph above the list to give explicit instructions? Maybe adding at the beginning: Click a section below to use…

I’m still hung up on using Homepage in the list (because the whole thing is the Homepage). But just “Content” or “Patterns” doesn’t sit well either, and “Content patterns” breaks the single word simplified list (though it’s more accurate). Am I overthinking it?

I also agree with Dave and Autumn on the adjustment to point 5. Dave’s suggestion reads better and smoother. And points 2 and 3 work too. “Continue” is fine if there’s instructions above it saying what’s going to happen when the button is clicked.

**Comment by arthur791004** [comment]
Here are the new screenshots

| Main | Header | Footer | Homepage | Colors | Fonts |
| - | - | - | - | - | - |
| ![image](https://user-images.githubusercontent.com/13596067/224273762-10d27bb7-3ee4-4bf8-a1c5-cb12fef11489.png) | ![image](https://user-images.githubusercontent.com/13596067/224273930-84219dcd-969e-4a4a-88a4-c9a3f3c5a86c.png) | ![image](https://user-images.githubusercontent.com/13596067/224273967-a968113e-d4fe-4647-b8c8-3bca21290f9b.png) | ![image](https://user-images.githubusercontent.com/13596067/224274013-48d62143-ded2-4531-9de5-6930ee462dae.png) | ![image](https://user-images.githubusercontent.com/13596067/224274091-bb91353f-bccf-43df-8fa1-0b86b01ad797.png) | ![image](https://user-images.githubusercontent.com/13596067/224274164-ef631aad-f81c-4c90-aebf-822048dbaa2b.png) |

**Comment by miksansegundo** [comment]
Is there anything left in this issue? We shipped https://github.com/Automattic/wp-calypso/pull/74245 with these copy updates.
