### ISSUE TITLE
Stats: Find and analyse potential chart libraries

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#74318]
This issue is an extension of #74316, the difference is that this task focuses on finding new libraries not mentioned in the other ticket and evaluating them the same way.

We'll need a line chart for our next feature and we want to analyse our options.
This issue focuses on finding tradeoffs of using an external library.

Things to pay attention to:
- package size
- is it language agnostic (e.g. React.js vs vanilla JS or pure CSS)
- how popular is it (e.g. GitHub stars and followers), and is it still maintained
- if possible, find out if we could extend it (e.g. is it easy to apply custom CSS, write a plugin)
- is it open source
- does it match features of our existing bar chart (e.g. have tooltips, multiple data sets on one graph)
- extras (e.g. sharp and smooth edges for a data point)
- other

**Comment by a8ck3n** [comment]
Noting the existence of the `LineChart` component from Calypso's library of UI components.

https://wpcalypso.wordpress.com/devdocs/design/line-chart

**Comment by a8ck3n** [comment]
Libraries being researched in #74316:
- https://chartscss.org/
- https://www.npmjs.com/package/react-chartjs-2
- https://github.com/soorena110/ReactLightChart

See #74317 for notes on creating our own charting library/component.

**Comment by a8ck3n** [comment]
The high-level summary of my research so far:

- Chart.js and D3 are the major players.
- Many of the open source libraries I found were actually wrappers to D3.
- There aren’t many wrappers for Chart.js though, so it looks like `react-chartjs-2` is sufficient for most who are looking to use Chart.js with React.
- ApexCharts is another option with good adoption. Instead of wrapping one of the above, it’s a different thing with a React interface as part of the project.
- Two popular options for wrapping D3 are Billboard.js and Recharts.

Based on that, I'm planning to dig in a bit more with Billboard.js, Recharts, and ApexCharts.

**Comment by a8ck3n** [comment]
Summary of library testing:

1. Recharts has the smallest footprint and looks the nicest. Unfortunately, I wasn't able to get it added as a dependency to Calypso so instead tested with an empty `create-react-app` project.
2. Both ApexCharts & Billboard were easy enough to integrate but their footprint is close to 500kb each which isn't ideal.

Based on my testing so far, I'd lean towards the existing LineChart in the component library OR possibly Recharts if we can sort out the dependency issues.
