### ISSUE TITLE
Commerce Plan Onboarding: Create Your Store Button Opens to "Page Requested Does Not Exist" Page

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#74345]
### Quick summary

After completing checkout for a new Commerce plan site purchase, the `Create your store` button loads a `Page Requested Does Not Exist` page.

### Steps to reproduce

1. Created a new site using the "Add a site" option in Calypso.
2. Chose and pay for the Commerce plan.
3. After payment completes the "Thank you" page has a `Create your store` button. Click that button.

<img width="200px" src="https://user-images.githubusercontent.com/42279181/224414004-ecd2c7ba-e3d0-492c-abe8-790de480bc11.png">

For a short time after page load, the button points to the simple site URL:

`https://sitename.wordpress.com/wp-admin/admin.php?page=wc-admin&from-calypso`

The site seems to be going atomic in the background, and the URL updates to:

`https://sitename.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&from-calypso`

The window seems to be small, but if the user clicks the button before the site goes atomic in the background they are take to the error page.

### What you expected to happen

To be taken to the next steps for setting up my store.

### What actually happened

I was taken to a page with the message `The page requested does not exist.`

![image](https://user-images.githubusercontent.com/42279181/224410685-8457ad88-18af-421e-9b43-48d64d913038.png)

Apologies for the _tall_ video, but you can see at about 0:08 when I hover over the button the URL points to the simple site address and then updates to the atomic URL:

https://user-images.githubusercontent.com/42279181/224412543-78a21b9b-4784-4cc7-8a1d-540beaca7c31.mp4

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

- Ran into this creating a new T51 partner site.
- The length of time the button points to the incorrect URL is variable. I tested multiple times and often it updated within a second or two of load, but other times it took several seconds more (maybe related to server load during the transfer process?), but even if it's 1 in 20 times, having a customer see an error screen as the first thing that loads right after they pay for a new site feels like something worth avoiding, especially because there's no direction on where to go from there; doubly so if it happens to a new user setting up their first site.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Started from `Add new site`
- Completed checkout with the Commerce plan
- The loading page shows the `wpcomstaging` domain, but as described in the report, the "Create your store!" button directs to the simple version of the site address, which then leads to an error.
- Returning to the dashboard takes you to the wp-admin dashboard, where I can then click `Start Selling`, which leads to

`https://sitename.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&task=products`

**AT Example**

https://user-images.githubusercontent.com/27249804/228378226-4ea475d8-c524-42d6-9081-901258068748.mov

📌 ACTIONS
- Since this doesn't stop the creation of the store (though I agree it does introduce an unwelcome step in the onboarding), changing the priority to `High`
- Assigned to MarTech

**Comment by gmovr** [comment]
Opened a PR here as part of our "Bottle pickup" meetup project :) https://github.com/Automattic/wp-calypso/pull/81207

**Comment by gmovr** [comment]
Deployed the above PR (had to wait for translations) cc: @katiebethbrown @cuemarie

**Comment by cuemarie** [comment]
Thank you @gmovr ! Retested today and the "Create your store" page now directs to the site's My Home:

https://github.com/Automattic/wp-calypso/assets/27249804/2f5f29ee-8ad6-42df-a469-7a2727b86be7

📌 ACTIONS
- Closing as fixed by https://github.com/Automattic/wp-calypso/pull/81207
