### ISSUE TITLE
Incorrect Downgrade Prompt on Plans page

### ISSUE THREAD

**Issue by kerrynicl** [Automattic/wp-calypso#74498]
### Quick summary

When SU'd to the user anjaassista, there is a prompt to "downgrade" to the commerce plan.
This gives the illusion that the commerce plan is cheaper than the site's current business plan 
<img width="1824" alt="Markup 2023-03-15 at 20 15 06" src="https://user-images.githubusercontent.com/83325600/225484464-78dec4cf-5636-4f7e-b206-2376e0abec0e.png">

### Steps to reproduce

1. Go to the My Site > Upgrade > Plans
2. Commerce plan shows "Downgrade Button"

### What you expected to happen

The Commerce plan show "Upgrade" as it does from the site owner's profile
<img width="1287" alt="Markup 2023-03-15 at 20 18 19" src="https://user-images.githubusercontent.com/83325600/225484860-7bae2e63-7a8e-4e10-9b4d-61bdd639bcee.png">

### What actually happened

It shows Downgrade

<img width="1824" alt="Markup 2023-03-15 at 20 15 06" src="https://user-images.githubusercontent.com/83325600/225484890-4b537973-b288-42d1-af12-8bcc806e6529.png">

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

The affected user is using the Croatian language. I was not able to reproduce on a test site but it is reproducible from the account  anjaassista

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested with both the site and the account switched to Croatian - no issue either way.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- Hey @kerrynicl ! I recommend that this issue be P2'd internally, since it cannot be replicated on a test site.
- As a reminder, always make sure to exclude any user-specific information in your screenshots or details, as well as any internal tools ( see pbawwo-18-p2 )
     - [ ] Please edit the report/comment above to use remove user-specific information and internal-only tools. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.
