### ISSUE TITLE
Livro | Unable to resize the image, and posts are not displayed chronologically

### ISSUE THREAD

**Issue by connorhipps** [Automattic/wp-calypso#74615]
### Quick summary

On the Livro theme, resizing image function isn’t working. Also, posts are not getting displayed chronologically.

In the editor, posts are displayed correctly however on the front end it isn’t. The same goes for image resizing as well.

### Steps to reproduce the image resizing issue

1. Go to page/post editor
2. Add an image and try resizing

### Steps to reproduce Post order issue

1. Go to Appearance → Editor → Home → Query loop
2. Under the Block settings → Disable the “Inherit query from template” option
3. Click on the drop-down button under ORDER BY and select the options there.

### What you expected to happen

The image should be resized and posts should be ordered as per the option we selected.

### What actually happened

1. The image will not be resized.
2. Posts order will not be the same as the option we selected.

![image](https://user-images.githubusercontent.com/5952196/226143144-0a717540-c3cb-426f-99b3-ea83cca1ef48.png)

Selected the image size as Medium

![image](https://user-images.githubusercontent.com/5952196/226143147-75cc7677-38ff-4e10-853f-85726240578e.png)

The displayed image on the front end isn’t medium-sized.

![image](https://user-images.githubusercontent.com/5952196/226143150-233831ae-7287-47e2-806e-654b96e958ea.png)

Selected the order as “Newest to oldest”

![image](https://user-images.githubusercontent.com/5952196/226143152-d6bc2163-cc4d-4f32-bb94-8ad0ccec9c2d.png)

The oldest post is showing first

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by connorhipps** [comment]
Related ticket link: 6045743-zd-woothemes

**Comment by worldomonation** [comment]
Tested on macOS Ventura 13.2.1, Firefox Nightly 113.0a1 (2023-03-19).

Unable to reproduce the image resizing issue. Please see video below.

https://user-images.githubusercontent.com/6549265/226443789-22de00c0-7e62-43f3-92f5-32e07f96fe64.mov

-----

Also unable to reproduce the Post Order issue - this is likely because the default posts all have the same date, which is the date at which the site was created. See screenshot below:
![image](https://user-images.githubusercontent.com/6549265/226444236-631919b6-b67a-421f-92d5-112ead7a4612.png)

After creating three posts with different dates and changing the Query Loop block:
![image](https://user-images.githubusercontent.com/6549265/226445014-8938ee6c-afbd-46b3-8b1a-e8963c8746da.png)

**Comment by worldomonation** [comment]
I'm inclined to close as non-reproducible. @connorhipps, what do you think?

**Comment by worldomonation** [comment]
Addendum, could you please log two issues instead of one in the future? It helps keep the problems at hand separate.

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate 
- Tested on AT - Could Not Replicate
- Tested on Self-hosted - Could Not Replicate 
- Replicable on Core - No


📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @connorhipps I've been unable to reproduce. If you're able to, please share more detailed steps, information about the environment, and please split this into two bugs
