### ISSUE TITLE
Feature Request: block someone and add someone into blacklist

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#74664]
### What

I would like to block one of my follower, remove the one, and add the one into black list

### Why

According to Code of Canon Law, our website cannot contain any political reletated comments, discussions. But WordPress.com only provide remove the one who post political reletated comments, discussions, mark the comments and discuession as spam, but cannot add the one and his/her devices into our blacklist, in case to prevent the one leave any message, and pingpack our links to his/her website.

**Comment by ttcath** [comment]
@jeherve if could, please help to push this feature request to relevant engineers.

**Comment by ttcath** [comment]
@tyxla pls pingpack @Automattic/yamato-backup, and relevant developer. Thx

**Comment by jeherve** [comment]
> I would like to block one of my follower, remove the one, and add the one into black list

You can remove existing followers from this screen:

https://wordpress.com/people/subscribers

However, since your site is public, you cannot stop them from subscribing to your site again if they would like to. If your site is public, your content is publicly accessible and folks can access it, either via email subscriptions or via other means (visiting the website, subscribing via RSS, ...).

>  our website cannot contain any political reletated comments, discussions. But WordPress.com only provide remove the one who post political reletated comments, discussions, mark the comments and discuession as spam, but cannot add the one and his/her devices into our blacklist, in case to prevent the one leave any message, and pingpack our links to his/her website.

If you'd like to block someone from commenting on your site, you can go to Settings > Discussion and add that person's information to the "Disallowed Comment Keys" section.
Once you have done that, when a comment contains any of these words in its content, author name, URL, email, IP address, or browser’s user agent string, it will be put in the Trash and will not appear on your site.
