### ISSUE TITLE
Woo Express Performance: Restoring plugins adds unexpected plugins

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#74776]
After restoring plugins from `/hosting-config/:siteSlug`, the following additional plugins are added:

* google-listings-and-ads
* pinterest-for-woocommerce
* tiktok-for-woocommerce

**Comment by daledupreez** [comment]
@markbiek, I believe these plugins should be included for the Performance plan. They should only be excluded for free trials.

**Comment by markbiek** [comment]
> @markbiek, I believe these plugins should be included for the Performance plan. They should only be excluded for free trials.

@daledupreez Do you mean they should be included when a site is first upgraded to the Performance plan? Or do you mean that this issue can be closed because it's not really an issue?

**Comment by daledupreez** [comment]
@markbiek, I believe we can close the issue because these plugins should always be installed on the Performance plan. Without context, I am not sure if there was a problem where these plugins were _not_ installed after the upgrade, so I can't categorically say that we don't have a bug. But I would lean towards closing this issue, at least as it is currently written.
