### ISSUE TITLE
My Profile: Hide my photo and Gravatar toggle is overlapping with text

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#74787]
### Quick summary

The "hide my photo" toggle is overlapping with the text on /me:
<img width="714" alt="Screen Shot 2023-03-22 at 10 45 09 AM" src="https://user-images.githubusercontent.com/1689238/226953597-179c0063-e192-40e8-adfe-62c3a89f5d89.png">
I tested in web Firefox, Chrome, and Safari.

### Steps to reproduce

1. Go to /me
2. Scroll down to the "Hide my photo" toggle.

### What you expected to happen

The toggle shouldn't overlap with the text.

### What actually happened

The toggle does overlap with the text (see screenshot).

### Impact

All

### Available workarounds?

There is no user impact

**Comment by allilevine** [comment]
From some quick tests it looks like this is happening because of the length of the label text in the `flex` layout.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on DotCom - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Could not replicate in FireFox, Chrome, or Safari.

**Screenshots/Recordings**

Firefox 112.0: 

https://user-images.githubusercontent.com/27249804/231552557-606afa58-ca9b-4e14-864d-3305a2443a69.mp4

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- Thanks for the report, @allilevine ! Are you still seeing this issue?  If so, could you lend any more details about your browser versions?
- Otherwise, looks like this issue may already be taken care of 😊👍

**Comment by allilevine** [comment]
> Thanks for the report, @allilevine ! Are you still seeing this issue? If so, could you lend any more details about your browser versions?

Looks like it was fixed, thanks!
