### ISSUE TITLE
Colors & Fonts Walkthrough follow up tasks & bug fixes (design not needed)

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#74816]
# Description
These are small items that do not need design, but should be flagged with  @davewhitley  when ready in case he has input.

I purposely did not include the work for the "Unlock styles modal" because it is more complicated.  I'll make a separate issue for that.

## Must do before CfT
- [x] Check that all fonts are working properly -- make sure to check on a variety of patterns
  - [x] pekYwv-Vw-p2#comment-776
- [x] Add Guidance message to the canvas area if user clicks on colors or fonts before they add a pattern: 
   - [x]  New copy: "You can view your color and font selections after you select a pattern, get started by adding a header pattern[link to header patterns]."
   - [x] New copy replaces the old string 
   - [ ] Later.....@davewhitley  & Pablo can approve or update copy. See 7l53h5fxAUNjVRBQ82YFwn-fi-2424%3A60507 
   - [ ] Go ahead with the translation on this.
  - [x] https://github.com/Automattic/wp-calypso/pull/75110
- [x] Change "Homepage" to "Sections" and move it between header and footer.
  - [x] https://github.com/Automattic/wp-calypso/pull/74840
- [x] In the action bar: use the text "Remove" instead of X
  - [x] https://github.com/Automattic/wp-calypso/pull/74872
- [x] In the list controls: update the copy from "Delete" to "Remove"
  - [x] https://github.com/Automattic/wp-calypso/pull/74872

## Can do during/after CfT
- [x] After exiting the Assembler flow the user should land in open editor , NOT browse mode.  (We can use the URL param `?canvas=edit` to achieve this)
  - [x] https://github.com/Automattic/wp-calypso/pull/74873
- [x] Ensure the Welcome Tour doesn't show in browse mode (this is general...not just for PA flow). See https://github.com/Automattic/wp-calypso/pull/74242
- [ ] Replace the textual list of patterns with thumbnails.  https://github.com/Automattic/wp-calypso/issues/74869

**Comment by autumnfjeld** [comment]
@davewhitley  Did you have ideas for this copy:
 “Select a pattern[link to header patterns] to apply colors and fonts to your website.” 

It will appear in the blank canvas when user hasn't selected a pattern.

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/5665959/227128920-88b97c28-b437-4181-9c41-c83a3d8695a7.png">

**Comment by autumnfjeld** [comment]
@davewhitley  Do you have any better ideas for this:
- [ ] Change "Homepage" to "Sections" and move it between header and footer.

It's a hard one....Sections is ok I guess.

**Comment by miksansegundo** [comment]
>  Change "Homepage" to "Sections" and move it between header and footer.

I think "Sections" is fine because it makes a difference between Header and Footer. I think it might not be ideal if we consider that the term "Section" doesn't exist in the context of the editor.

How about using "Home patterns" or "Home template"? The "Homepage" screen contains the patterns added to the Home template. 

Matias mentioned that "Homepage" sounds a bit confusing because the header and footer patterns are also included in the Homepage. To be precise, the Home template has "template parts" for the header and footer, which is the feature that adds the header and footer to all pages. 

Adding some screenshots and explanations as reference:
 
**What areas are in a template?** 
The concept "template part" goes with the concept of "areas". Users can see their areas in the Template settings on the sidebar. 

![Image](https://user-images.githubusercontent.com/1881481/227134760-e183ce64-9024-40ad-a718-8838500b6514.png)

When users click on `Edit` on a header/footer template part

![Image](https://user-images.githubusercontent.com/1881481/227136673-0fd0b7af-ca3e-4dc2-8d1c-86475263d950.png)

They will see this screen introducing the concept "template part"

![Image](https://user-images.githubusercontent.com/1881481/227137245-f580c3df-3ee8-47b8-80a8-ef3705b96887.png)


**What is a template part?**

![Image](https://user-images.githubusercontent.com/1881481/227138014-7d6d97a4-2d70-4ba4-a755-35d76fc34e59.png)

**Comment by autumnfjeld** [comment]
The concept of template parts is good for us to understand, but I think too advanced to be expressed to the user.   So I think the user doesn't need to know about template parts so early in the WP experience. 

I like the sound of "Home patterns".   But the same problem arises, when we say home we mean Homepage and Header and Footer are also Homepage patterns -- when I see this through a new user's eyes.

> I think "Sections" is fine because it makes a difference between Header and Footer. I think it might not be ideal if we consider that the term "Section" doesn't exist in the context of the editor.

This is a good point....but the editor doesn't really have a simple word for "patterns that go in the middle of the homepage".  ;)

I think "Sections" is the best option we have right now. (Which is sad how we can't find a good name for this! 😃😢🥺)

**Comment by arthur791004** [comment]
> In the list controls: update the copy from "Delete" to "Remove"

@autumnfjeld This means to update the copy of the tooltip, and keep using the remove icon in the list view, right?

**Comment by autumnfjeld** [comment]
Yes, update the copy in the tooltip.  🤓

**Comment by autumnfjeld** [comment]
@arthur791004  We can go forward with the CfT without copy approval.   Because there are many other important things that are worthy of user testing, copy fixes can come later.

So for this item, go ahead and implement it for the CfT:
- [x] Add Guidance message to the canvas area if user clicks on colors or fonts before they add a pattern: “Select a pattern[link to header patterns] to apply colors and fonts to your website.”  

That same message can show in both situations (e.g. same message in the canvas if users clicks colors or if user clicks fonts).

**Comment by arthur791004** [comment]
I'm going to close this issue since the tasks are almost done and we have a separate issue for https://github.com/Automattic/wp-calypso/issues/74869
