### ISSUE TITLE
 Select all 'WooCommerce Endpoints' on 'Appearance → Menus' not working

### ISSUE THREAD

**Issue by samueljseay** [Automattic/wp-calypso#74936]
### Quick summary

Could someone help me confirm if this belongs in Calypso?

Here's the original issue raised in WooCommerce: https://github.com/woocommerce/woocommerce/issues/37090

It looks like a menu I don't recognize being in core WooCommerce so I wondered if this is Wordpress.com specific.

Thanks.

### Steps to reproduce

See the original issue: https://github.com/woocommerce/woocommerce/issues/37090

### What you expected to happen

All checkbox items should be selected

### What actually happened

Nothing happens

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Replicated in WooCommerce | Version 7.5.1

📌 FINDINGS/SCREENSHOTS/VIDEO
- Following the steps from the original issue, https://github.com/woocommerce/woocommerce/issues/37090 , I am able to replicate on my AT site.

**Steps to Replicate**
1. Go to Appearance → Menus
2. Expand the “WooCommerce Endpoints” section under Add menu items
3. Click the Select All link

The page refreshes to `/wp-admin/nav-menus.php?page-tab=all&selectall=1#posttype-woocommerce-endpoints`, but nothing is selected.  When trying again, nothing happens at all.

**Screenshots/Recordings**

https://user-images.githubusercontent.com/27249804/231606202-6c2f558b-6e5e-4cec-8082-c220c646b67e.mp4

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- Hey @samueljseay ! I see that the original issue has had some recent activity since you opened this issue in Calypso - can you let us know if you still think this needs to exist here in `wp-calypso`, or if the findings on the original thread (or my triaging above) mean this can be closed? Thank you!
