### ISSUE TITLE
Checkout: allow user to enter in details while site is being set up

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#7497]
When creating a site, after selecting a plan we get suck on this screen, while we wait for a site to be set up.
<img width="607" alt="screen shot 2016-08-16 at 9 18 55 am" src="https://cloud.githubusercontent.com/assets/1270189/17706844/8a34c192-6392-11e6-9004-46df8c6bef53.png">
When it's done, the user is forced to click on this button:
<img width="481" alt="screen shot 2016-08-16 at 9 19 05 am" src="https://cloud.githubusercontent.com/assets/1270189/17706869/a13e6f5a-6392-11e6-98ef-68798d38f55d.png">

Instead of this waiting screen, let's instead take them to the checkout page to let them enter in CC details. If necessary, we can disable the submit button until the site is setup and ready.

**Comment by gwwar** [comment]
Be aware that a user can empty cart items on this page. The current behavior redirects to their site, so we might need to leave them on the checkout, or show that placeholder.

**Comment by meremagee** [comment]
Love this. Reiterating a few "next steps" for purchasing users that I outlined elsewhere, here, for posterity. As discussed with @apeatling, if y'all are heading in this direction, take it away. If not, we'll get to it ASAP.

**desired flow for new, purchasing users:**

1. do not show post-processing screen (the one noted here) in signup if user has plan in cart – take users who have something in cart from user step directly to checkout.
2. after check-out, replace current thank-you page with something that looks like the post-processing screen, to the tune of “thank you for your purchase. we’re getting your site ready. continue.”
3. take paying users to trampoline/front-end and guide them through site creation process as we do for non-paying users.
4. users get a lovely email receipt based on their purchase which shows them all the great things they just bought (already in production thanks to store team!)

**This helps mitigate 3 issues:**

1. Even though checkout isn’t formally part of signup code, for users it is. The post-processing screen should be the completion of signup for _users_, not us.
2. For users with something in their cart, if we encourage them to confirm their account in the signup flow, and they do, they will return to Calypso and skip checkout entirely – meaning they won’t actually get to purchase the plan or domain they had just selected in signup (https://github.com/Automattic/wp-calypso/issues/7440).
3. NUX for purchasing users is not optimum at the moment since the thank-you page takes them out of the normal new user flow (front-end of site with onboarding tips).

**Comment by rralian** [comment]
Our research into this small step in streamlining the checkout flow in signup basically shows that it isn't the gimme/small-task that we were hoping. We would need a considerable refactor to pull this off, which means we should probably do this as part of an overall signup/checkout overhaul and not for this small change on its own. I'm un-assigning @artpi from this task for now. @meremagee, do you think we should keep this open here, or should this get closed and folded into something in Delta?

**Comment by meremagee** [comment]
Let's close. We had a similar discussion on Delta and came to the same conclusion. @artpi has coordinated a bit with @lsinger to get some incremental, lightweight changes out the door that should improve the flow before we could circle back to a bigger checkout step refactor.
