### ISSUE TITLE
Theme Showcase: style variation not showing for 3rd party themes with style variations

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#75258]
# Description
Originally reported by @ianstewart  p1680545433925719/1680545224.994839-slack-C048CUFRGFQ
p1680585205247879/1680545224.994839-slack-C048CUFRGFQ

 Understanding how 3-party themes should display style variations
At least one (presumably more) of our third-party premium themes display style variations. But we’re not currently displaying those in the same we do with our first-party themes. 

See comments below

# Acceptance Criteria / Dev Tasks
- [ ] Third party themes with style variations should surface these just as our own dotcom themes surface style variations (thought I am not sure how premium and upgrades are handled here)

cc: @Automattic/lego  @cpapazoglou  @davewhitley

**Comment by cpapazoglou** [comment]
Getting the style variations (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sjcpbz%2Qgurzrf.cuc%232101-og) requires a `stylesheet` and a demo site we own which has the theme activated (it uses `switch_to_blog`). It uses gutenberg `get_style_variations` function which again needs access to the theme files and `/styles` folder.

I assume that if we create a8c owned demo sites for all 3pd themes, we will get the variations on theme details page. I don't know though how the rest of the flow will work.

`Vetro` is not a 3-party theme. It's an a8c theme and that's why `get_style_variations( $stylesheet )` works.

**Comment by autumnfjeld** [comment]
This issue should be split into two.  Could the dev that picks this up do that?   Thank you.

EDIT: DONE.
Other issue is https://github.com/Automattic/wp-calypso/issues/75946
