### ISSUE TITLE
Matching unique Country Tax Name to profile address or currency 

### ISSUE THREAD

**Issue by janmckell** [Automattic/wp-calypso#75445]
### What

Can the location or currency that a user is using in their profile be linked to the name of the tax id in the region, country or countries which use that currency?

### Why

It’s a small thing, but it could be a good win for making a user feel personally spoken to.

6175013-zen is an example of a user saying that they were confused by the VAT/GST reference. They are in Australia and it is called the ABN for Australian customers - they higlighted this when asking what the GST tax was.

### How

This can be automatically matched to location/currency and updated to the users Billing History, or wherever the country tax name is shown. 

For instance, the ID number that we'll ask the user for in their VAT details may not always be called **VAT** ID, so for example, when they change their country ID, can the related VAT name change?

See annotated screenshot below:
![Markup on 2023-04-07 at 18:04:54](https://user-images.githubusercontent.com/84089207/230684663-7cc552b4-2b13-4460-9370-968f450944c3.png)

I considered that this might be too small or unnecessary to be worked on, but in case it is a small change, I decided to surface it.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

📌 Message to Author
- Thanks for sharing this suggestion!
- CCing @Automattic/shilling

**Comment by sirbrillig** [comment]
This should be mostly fixed by https://github.com/Automattic/wp-calypso/pull/75044 although there's still some things that could be improved (eg: the page title since that is controlled by the _saved_ country and will not change just because a different country is selected in the dropdown).

<img width="1060" alt="Screenshot 2023-04-24 at 8 27 56 PM" src="https://user-images.githubusercontent.com/2036909/234145041-5abe13e6-5a32-4451-ba0a-e182c209487e.png">

<img width="1060" alt="Screenshot 2023-04-24 at 8 30 00 PM" src="https://user-images.githubusercontent.com/2036909/234145492-3bb5b013-d200-4979-8513-eaee6542f2ad.png">

**Comment by sirbrillig** [comment]
The other place that will still be inaccurate is the button that leads to the VAT form at the bottom of the Billing History page, since it has no idea what country you're in if VAT details have not been set already:

<img width="984" alt="Screenshot 2023-05-02 at 1 36 34 PM" src="https://user-images.githubusercontent.com/2036909/235742172-f765434d-f776-4810-9362-48902d794edf.png">

**Comment by michaeldcain** [comment]
From planning:

Let's update the headercake title and the compactcard title on the previous page to read "Add tax (VAT/GST/CT) details" or "Add tax details (VAT/GST/CT)".

**Comment by sirbrillig** [comment]
I forgot, this is less of an issue because in https://github.com/Automattic/wp-calypso/pull/75044 I used geolocation as a fallback country for these titles, so the generic text will only be seen by users geolocated in countries without a tax name (eg: the US). In any case, I implemented the more generic text in https://github.com/Automattic/wp-calypso/pull/76609
