### ISSUE TITLE
Linux Desktop App: Update dependencies to remove gconf2

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#75452]
### Quick summary

A user pointed out that when they tried to install the Linux Desktop app, they were prompted about dependencies for gconf2, which has been deprecated and replaced with dconf. They're asking if we can update dependencies accordingly.

### Steps to reproduce

1. Install Linux Desktop 
2. Note the dependencies
3. Note gconf2 has been replaced and should be dconf instead if the app still needs that

### What you expected to happen

Any dependencies should be current

### What actually happened

The app wants to install gconf2, and shouldn't because that's been replaced by dconf.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

Bug scrubbers: I'm not actually sure whether this makes the app unusable, but the user [in this thread](https://wordpress.com/forums/topic/linux-desktop-dependency-gconf-moved-renamed-at-gnome-org/) said they couldn't install the app.

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Present in Linux Desktop App.

@mreishus  pointed out it was probably just added for Electron's sake and needs to be updated. @sandymcfadden  asked me to ping him and @nsakaimbo too  👋 

Apologies if this is in the wrong repo, entering it here anyway using our tooling, as it seemed like it might be related to [this Calypso code](fbhepr%2Suvfgbel%2Spnylcfb%2Sqrfxgbc%2Sryrpgeba%2Qohvyqre.wfba-og). Likely similar to [this issue](https://github.com/Automattic/simplenote-electron/issues/3048).

**Comment by mreishus** [comment]
Ubuntu does have a [gconf2 package](https://packages.ubuntu.com/jammy/gconf2), so my hunch is that our .deb is still usable, but it does require you to install obsolete software (which is a valid concern - especially for some users who wouldn't feel comfortable removing it after the package is updated).

**Comment by cuemarie** [comment]
This issue was raised here to try to find a suitable assignee: p1681160713839369-slack-C02FMH4G8

Some relevant feedback in the thread there from @/nsakaimbo : 

> `gconf` is not a direct dependency of the app, so is likely buried somewhere within electron itself, which means the fix will likely involve upgrading electron to the latest version: https://github.com/Automattic/wp-calypso/blob/trunk/desktop/package.json

> Once electron is upgraded, we can ping the platform team to help deploy it.

However they would not be able to look further into this for several weeks, so this could still use a volunteer

**Comment by danielbachhuber** [comment]
@kozer Can you see if you can figure this out sometime in the next month or so? Thanks!

**Comment by vindl** [comment]
Some ongoing work in https://github.com/Automattic/wp-calypso/pull/75516, so might be good to sync up.

p1681404395393659/1681160713.839369-slack-C02FMH4G8

**Comment by kozer** [comment]
I don't have a Debian-based distro, however, I did some investigation.

- I downloaded the `deb` file and extracted it. Inside that, there is a `tar.gz` file that called `control.tar.gz`. Inside that there is a `control` file that has the following line:
```
Depends: gconf2, gconf-service, libnotify4, libxtst6, libnss3
```
- The above seems that is related to a line that exists in `desktop/electron-builder.json`, specifically:
```
		"depends": [ "gconf2", "gconf-service", "libnotify4", "libxtst6", "libnss3" ],
```
and was first introduced in https://github.com/Automattic/wp-calypso/commit/367b1fae0f02afb54ecad0143d780db531e416a that seems to be there from when the `desktop` app was moved in calypso

- As I am an Arch distro user, I installed it through this [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wp-desktop). This ends up building the app from it's `tar.gz` file.
Running it locally, I get:
```
[79880:0522/122743.816109:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  /opt/WordPress.com/wpcom
```
This issue is open [here](https://github.com/Automattic/simplenote-electron/issues/3044) and seems to be related to `simplenote-electron` package. I don't know if it's related. Probably not.

The pr mentioned above is trying to update the electron, so I guess this will resolve the `gconf2` issue. I 'll keep watching this pr for updates, and test it when is ready.

cc: @nsakaimbo

**Comment by bruvellu** [comment]
Hey, I just want to report that I couldn't install WP Desktop v8.0.3-1130432 DEB on Ubuntu 23.10 (Mantic) due to the `gconf2` dependency error:

![image](https://github.com/Automattic/wp-calypso/assets/361179/2d7cf1fe-3515-4c8b-bc75-cc61c8ccbbf9)

And the package is no longer available in this Ubuntu version:

![image](https://github.com/Automattic/wp-calypso/assets/361179/24da6469-6aa5-4ef2-8f86-464d961e24f4)

Any workaround?

Best,
Bruno
