### ISSUE TITLE
Newsletter sign-up form submission redirects don't work when the form is in the footer

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#75450]
### Quick summary

When a user fills out a newsletter signup form that has been added to the site's footer template part, the user is not redirected to the page that has been set in the Block Settings. 

### Steps to reproduce

1. Edit the site footer in the Site Editor and add a Newsletter signup form.
2. Choose the option to redirect to another page on submission.
3. Open the live site, fill out the form, and click on the submit button.

### What you expected to happen

To be redirected to the page I selected in the block settings.

### What actually happened

I was not redirected. 
The entry was correctly recorded.

### Impact

One

### Available workarounds?

Yes, easy to implement: move the form out of the site's footer.

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Theme: Twenty Twenty-Three.

**Comment by ariel-maidana** [comment]
6173994-zd-woothemes
Please let the user know once the issue is solved.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- In testing, I added the Contact Form > "Newsletter Sign-Up" to my site's footer, and set it to redirect to the "About" page of my test site.  With both a static homepage and a default theme home template, the form redirected on submission to `https://SITE_ADDRESS/about/#contact-form-block-template-part-twentytwentythree//footer`

**Screenshots/Recordings**

**Setup**

![BKomSD.png](https://user-images.githubusercontent.com/27249804/231235867-5ae56be9-284c-493e-a2ab-643b34f2f3c0.png)

**Result**

https://user-images.githubusercontent.com/27249804/231236595-63967555-0cdf-4e8d-9d49-5efa31b9c83a.mp4

**Simple Site Test (Regular Contact Form)**

https://user-images.githubusercontent.com/27249804/231236344-b612181a-66d0-4994-8dcd-c95103b11071.mp4

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- Hey @ariel-maidana ! I was not able to replicate this in a test site, suggesting this issue is specific to the user's set up.  If you are able to replicate this with additional details, please feel free to update the report- otherwise I recommend further testing at the user's site level.  Thanks!

**Comment by tellisbethel** [comment]
Hi @cuemarie! I added the form to the user's Page template as a Template Part rather than Reusable block. I then also set an anchor link so the submission redirection jumps to the top of the confirmation page rather than back to the form at the bottom of the page, and everything appears to work now. But I'm not sure why this worked this way or if it's expected!
