### ISSUE TITLE
Woo Express Essential: Issues with expired plan

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#75485]
CfT: pdtkmj-1mM-p2#comment-2527

There's some strange behavior with expired plans. It seems that users may not being sent to the plan expired page. The reporting user was still able to see the plan at `Upgrades -> PLans` but buttons were disabled and changed to "Downgrade".

![image](https://user-images.githubusercontent.com/917632/230933229-135cf751-409f-4f7a-ac32-d2b29d52c2f3.png)

The user was also able to interact with all WooCommerce menu items. and eventually ended up on the "Your free trial has ended" page which showed a broken plans page similar to the one pictured above.

**Comment by sixhours** [comment]
This sounds like it could be an issue with the downgrade logic that was recently updated to avoid overloading Atomic infra by staggering the downgrades over a 12-hour period: D107068-code

So the Woo software would still be active for a bit even if the plan didn't allow it.

Though that diff specifies the trial, so I don't know if the same logic applies to downgrades from Essential or Performance.

**Comment by sixhours** [comment]
I'm not able to reproduce this issue, either. I'm redirected to the page at `/plans/my-plan/trial-expired/siteSlug` which I think is the expected behavior, although I can see why the "Your trial has expired" language is confusing (since the user would have been on a paid plan, not a free trial).

Aha, I see that's also reported as an issue here: https://github.com/Automattic/wp-calypso/issues/75492

**Comment by markbiek** [comment]
Closing as unreproducible. Please reopen if more information becomes available.
