### ISSUE TITLE
Newsletter: when picking paid plan from launchpad, plans page lacks direction

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#75728]
### Quick summary

The link from the global styles "you need an upgrade" step in the launchpad goes to the plans page where it's not clear which plan you need and why.

This worked when first launched - the step passes `plan=value_bundle&feature=advanced-design-customization` to the /plans page but has stopped working (along with all other uses of these GET vars) due to changes on the plans page.

### Steps to reproduce

1. Create a newsletter https://wordpress.com/setup/newsletter
2. Pick a custom color
3. In the launchpad note "need a plan" thingy

   <img width="471" alt="image" src="https://user-images.githubusercontent.com/87168/231875339-6b3a4c95-12f8-416d-915d-7892572e3635.png">

4. After choosing the task, you see only 3 plans:

    <img width="1505" alt="image" src="https://user-images.githubusercontent.com/87168/231875438-672f94f9-6541-43e8-ad93-36eb0d82d93e.png">
URL is `https://wordpress.com/plans/SITE_SLUG?plan=value_bundle&feature=advanced-design-customization`

5. Click "pay monthly" button and more plans appear
    
    <img width="1506" alt="Screenshot 2023-04-13 at 23 28 26" src="https://user-images.githubusercontent.com/87168/231875606-67228314-1194-4efe-8c39-ff419f60496d.png">

### What you expected to happen

Clearer next steps from picking the task. 

### What actually happened

I didn't see all plans, I didn't see which plan I needed for me. No features or anything was highlighted or explained.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

@Addison-Stavlo is this behaviour from the Launchpad, or something specific to the plans grid? Do you know whom to ping about the plans grid?

Some discussion: p1681461948232039-slack-C048CUFRGFQ

----

### Next steps
 - [ ] Talk to Marketing (or whoever owns the /plans page) to align on what needs to happen with the get vars and highlighting
 - [ ] Consider the language used in the /plans page and with global styles nudges and whether they could align better

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate, so long as I chose to start with the free plan after choosing my domain.  Agreed, it was a bit confusing to land on the Plans page without further guidance!

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/231897746-3b38d084-cd2e-4194-9348-715348ba18f7.mov

📌 ACTIONS
- Assigned to Lego

📌 Message to Author
- I'm thinking Lego might be able to help as they look at new user and onboarding experiences, but feel free to update as needed based on the feedback you receive from Addison!

**Comment by simison** [comment]
I get now what's going on. It's a global styles upsell, and global styles require Premium plan at a minimum. Hence we don't show other plans.

<img width="772" alt="Screenshot 2023-04-14 at 11 39 54" src="https://user-images.githubusercontent.com/87168/231992566-802fbd8a-b0ae-4688-aeaa-adcf9062f7cb.png">


**Problems:**

- Only place where we mention Premium plan is required is the lengthy upsell text, but we don't carry that info to plans grid itself.
    <img width="390" alt="image" src="https://user-images.githubusercontent.com/87168/231992521-46299043-e8d1-4ca8-8b67-387a05cc229b.png">

- Other plans appear when clicking around. **(bug)**
- I might be aware of other plans as  customer, so it's confusing not to see them. I didn't test if I see them if I had bought Personal during onboarding.
- Terminology isn't aligned; in the nudge we say "custom colors" and in the plans grid "style customizations".
- In the launchpad it's just one-way upsell; I can't remove custom colours and get rid of it

@ianstewart hello! I think improving the global styles upsell could be owned by your teams?

**Comment by simison** [comment]
Maybe something like this? (Just a rough mockup.)

- Show current plan + personal plan, but non-primary CTAs
- Add "style customization" as striked out to personal (and free?). Doesn't have to be there normally but just in this case.
- No need to show "enterprise" column
- Above plans highlight better which is the plan they need
- Simplify upsell and use the same words as in plans grid

<img width="1501" alt="Screenshot 2023-04-14 at 11 54 29" src="https://user-images.githubusercontent.com/87168/231996189-f1a942f1-103c-49b9-addb-3f3974f51bc6.png">

Or maybe moving the highlighted feature up, and adding different visual treatment:

<img width="1434" alt="Screenshot 2023-04-14 at 12 22 30" src="https://user-images.githubusercontent.com/87168/232004030-c90b15bb-0dda-448b-942e-a92c656154fd.png">

**Comment by mmtr** [comment]
Seems that the new layout for the Plans page no longer supports highlighting a feature. [It was possible in the previous layout](https://github.com/Automattic/wp-calypso/pull/70933), and the wording was also clear about why you're only seeing a limited number of plans:

![image](https://user-images.githubusercontent.com/1233880/232012012-0f6ea0e6-d785-4b9e-900a-a22e6867875b.png)

cc @Automattic/martech

**Comment by autumnfjeld** [comment]
Here's the upsell in the onboarding DP, as an example.
<img width="789" alt="image" src="https://user-images.githubusercontent.com/5665959/232428628-55bd7d68-1b65-48ed-99c0-63cd34d6f277.png">

Also I think using anything that says "custom colors" or "premium colors" as in trying to tell the user they have to pay for pink or purple is not a great sales pitch.   Selling "professional design" sounds worthy of $$, but selling a color doesn't make sense.  I'd be a frustrated customer and I'd want to know how to ditch my "custom color" that I'm not willing to pay $8/month for.  Just my two cents. 😄

**Comment by simison** [comment]
@autumnfjeld but the ability to change any colours is exactly what we're selling. :-) That point aside, for now the wording should just stay consistent from upsell to another upsell to plans grid.

**Comment by autumnfjeld** [comment]
I disagree to some extent.   We trying to sell the premium plan.  If we are selling colors or a special color design it has to be much much cheaper than the cost of a premium plan.  Who is going to pay that kind of money for a color?

**Comment by lucasmendes-design** [comment]
I've made a similar comment about this modal. I think we can give users more context about their plans and prices.

**Comment by dsas** [comment]
I think most of the issues raised here will be resolved by bringing back the features in the plans page as @mmtr [highlighted](https://github.com/Automattic/wp-calypso/issues/75728#issuecomment-1508257318).


There are separate issues for these problems:
> Terminology isn't aligned; in the nudge we say "custom colors" and in the plans grid "style customizations".

https://github.com/Automattic/dotcom-forge/issues/2262 but then launchpad+plans becomes misaligned with rest of newsletter flow..

> In the launchpad it's just one-way upsell; I can't remove custom colours and get rid of it

See https://github.com/Automattic/dotcom-forge/issues/2263

**Comment by autumnfjeld** [comment]
For this issue the context is Newsletter flow.  Adding some visuals to help the discussion.
The LaunchPad upsell task is the second time the user has seen a mention of Premium Plan. (So they have already rejected the PP in the signup flow plans screen by the time they see the upsell in the LP.)
 
**The flow:**
* Start Newsletter flow
* Fill out items on the "It begins with a name" screen
* Domain
* Plan
* Add subscribers screen
* LaunchPad

<img width="609" alt="image" src="https://user-images.githubusercontent.com/5665959/235380393-29f282a2-6223-4054-92d6-adad1917399a.png">

<img width="838" alt="image" src="https://user-images.githubusercontent.com/5665959/235380444-0de58240-d8a6-4426-9950-25ac31325281.png">

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/5665959/235380466-75195935-42b3-46b6-8025-4b8c320f5c2a.png">

User sees this upsell because they chose a color on the "It begins with a name" screen.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/5665959/235379539-f3fcc3a8-7a93-4abf-8cc8-c8e8c082d81c.png">


I would feel so confused as a user that one tiny action of choosing a single color in an onboarding step led to me having to take action to figure out how to get this "custom color" out of my setup, because that one choice of color is a very minor action on the user's part and very expensive in the Upsell.  Newsletter is a simple flow. It is targeting a simple use case, and the upsell isn't even about the core of the flow e.g. Newsletters. 

As @dsas said this is being examined in https://github.com/Automattic/dotcom-forge/issues/2263

cc: @nuriapenya

**Comment by mmtr** [comment]
> because that one choice of color is a very minor action on the user's part and very expensive in the Upsell

+1. This was discussed in p9Jlb4-76h-p2 too:

> > have we considered not having the “Favorite color” picker?
>
> We could also move the dropdown to launchpad and that could be clearer because you see directly both preview and dropdown
> [...]
> I think we should add Styles to Lettre, and make sure those styles work with the newsletter emails too. UI can then be more along the other flows using Styles. So I’m leaning to removing this specific dropdown at setup step
>
> p9Jlb4-76h-p2#comment-7688

> I’d simplify this (remove the locks) and just have folks pick the color of the button or emphasize style variations folks can pick from at a high level with the usual global styles gating nudge in place after they are set up. If we’re trying to get people to upgrade, showing them very basic colors that look like they need to be paid for when you can only see that color applied to the button feels extremely underwhelming. It’s not clear this is some sort of global color and even then changing a global color feels pretty basic to offer these days.
>
> p9Jlb4-76h-p2#comment-7684

**Comment by Addison-Stavlo** [comment]
Separate to some of the other concerns above, another improvement here could be to use an encapsulated plans page within stepper for this task instead of sending the user into calypso with all the admin area distractions.  Initially these flows linked into calypso for things like plans for simplicity and iteration speed, but ideally should be updated to avoid that.

An example of this currently would be in our "Free" flow (`*/setup/free`) for the later "choose a domain" step. Components for things like domains, plans, etc. can be brought into their own stepper mini-flows to do things like go from LaunchPad -> Plans -> Checkout -> Launchpad in a streamlined way without getting into more complicated interfaces (or calypso proper at all).

![free-flow-plans-step](https://user-images.githubusercontent.com/28742426/235460010-47c16baf-3e35-454c-a382-7144a90d9bcb.gif)

Context for the Gif: the free flow skips domains and plans steps initially, and gives the user an auto-generated domain name at first. The gif starts at the Launchpad, then clicking the "choose a domain" task from the launchpad brings the use into a separately defined stepper flow to guide the user through domains/plans selection.

**Comment by lucasmendes-design** [comment]
> Separate to some of the other concerns above, another improvement here could be to use an encapsulated plans page within stepper for this task instead of sending the user into calypso with all the admin area distractions. Initially these flows linked into calypso for things like plans for simplicity and iteration speed, but ideally should be updated to avoid that.

Yes, this is something that we discussed in our design reviews. Redirecting users to Calypso is very strange in many ways (distraction, different interfaces, etc).
