### ISSUE TITLE
Our wpcom_block_editor_global_styles_menu_selected tracks event handler is broken

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#75798]
### Quick summary

We add a handler to the Site Editor to track menu clicks within global styles. This records the `wpcom_block_editor_global_styles_menu_selected` event.

Right now, this seems to be broken. Clicking on any menu in Global Styles logs a console error because there's a [crash on this line](https://github.com/Automattic/wp-calypso/blob/trunk/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-global-styles-menu-selected.js#L14). The console error reads `Uncaught TypeError: Cannot read properties of undefined (reading 'find')`.

Practically, **this has no user impact**, but it does seem to be affecting that event from being logged correctly. That lines up with a decrease in this event sometime in January:
![Screen Shot 2023-04-14 at 1 52 43 PM](https://user-images.githubusercontent.com/26772342/232132616-5595fbdc-059f-4a3f-a43b-619f8aa95669.png)

### Steps to reproduce

1. Open the site editor
2. Open global styles
3. Click any submenu
4. Open console and see error

### What you expected to happen

No error

### What actually happened

Console error

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested in Firefox 112.0.1 , so I see the following FF version of the error in the Console for both Simple and AT sites:

`Uncaught TypeError: r is undefined`

📌 ACTIONS
- Assigned to T-Rex

**Comment by mmtr** [comment]
Turns out that we were using a deprecated and non-standard [`event.path` property](https://github.com/Automattic/wp-calypso/blob/79c1b10c2fca1e6d29b0a625729b286e07d158cd/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-global-styles-menu-selected.js#L4) to track this event, and such property was [fully removed in January 2023](https://bugs.chromium.org/p/chromium/issues/detail?id=1277431).

I opened https://github.com/Automattic/wp-calypso/pull/76292 as a fix so we no longer rely on `event.path`.
