### ISSUE TITLE
Premium Content Block: Shows up on site's Pages even though the block isn't added

### ISSUE THREAD

**Issue by dromero20** [Automattic/wp-calypso#75804]
### Quick summary

On this site's #6206486-zd pages listed in the ticket notes:

There's a prompt to "Connect to Stripe" at the top, looks like it's triggered by the Premium Content Block.

<img width="520" alt="Captura de pantalla 2023-04-16 a las 13 24 21" src="https://user-images.githubusercontent.com/23258551/232306549-7042f2ac-840e-495f-89ed-33cc3fbf439c.png">

However, on those pages there's no Premium Content Block added. Clearing the site's cache didn't help. All new Pages you create have the "Connect with Stripe" message, no matter what content you're adding. 

### Steps to reproduce

1. Create a new page.
2. Add any content (a paragraph and title, for instance).
3. Save it as draft.
4. View the page.

### What you expected to happen

The content you added should be there and that's it.

### What actually happened

The content you added is there AND also a prompt to connect Stripe to the Premium Content Block.

### Impact

One

#6206486-zd

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple.

**Comment by cuemarie** [comment]
📌 SCRUBBING NOTES
I took a quick look at the user's site, and it looks like they have the Premium Content block added to their templates, which is why that stripe message is appearing on certain parts of their site, but no blocks can be found on the pages themselves.  Here's an example screenshot from their Page Template:

![Markup on 2023-04-18 at 16:14:32](https://user-images.githubusercontent.com/27249804/232924902-aadf3009-344b-4df0-9943-71f4bd056be0.png)

📌 ACTIONS
- Closed as not a bug

📌 Message to Author
Hi @dromero20 !  

It's important to always exclude any user-specific information in your screenshots or details, since this is a public repo. 

I've gone ahead and removed all user-specific information from your report, and [deleted the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

In the future, issues like this woul be better addressed internally, such as through a post on 2EDhh-p2 , where the user's details can be safely shared in an internal-only environment.
