### ISSUE TITLE
Barnsbury: Background color cannot be changed

### ISSUE THREAD

**Issue by brittanygray902** [Automattic/wp-calypso#75808]
### Quick summary

Cannot change background color in customizer as intended

### Steps to reproduce

1. Go to Customizer > Background & Colors
2. Change background color (any color)

### What you expected to happen

I expected the entire background to display white, instead of off white color it was. 

On my test site I was able to change the background colors as intended:

<img width="889" alt="Screenshot 2023-04-16 at 9 22 53 PM" src="https://user-images.githubusercontent.com/80774825/232363064-e2f51d4d-d0f4-4291-abc7-bcf6b1145d5d.png">

### What actually happened

The background color behind the menu changed colors but the rest of the site remained the same. 
<img width="1378" alt="Screenshot 2023-04-16 at 9 20 16 PM" src="https://user-images.githubusercontent.com/80774825/232362829-73dad121-99ba-4640-ac7e-659fad4eb5f0.png">

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Was able to work around this by giving the user CSS to change the background color to white, as intended.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Following the steps above, Barnsbury's background color responded as expected.

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/233226343-9c3409fb-27e8-485b-a9e3-6ae6ea17d252.mp4

📌 ACTIONS
- Closed as could not replicate (please reopen with more details if able to replicate in a test environment)

📌 Message to Author
- Hey @brittanygray902 ! I also could not replicate this in a test environment, suggesting this user's site has more specifics that were impacting the behavior of the bg color, rather than a theme bug.
- If this needs further troubleshooting, I suggest an internal post on 2EDhh-p2 where you can share more details about the user's specific site!
