### ISSUE TITLE
Site Assembler - Featured patterns review and update

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#75864]
# What

Review the reasons to feature patterns in the assembler and the editor and decide if they should be updated programmatically or manually once every week.

# Why

Users will probably explore this category first because appears on the first position in the list of categories. 

![Image](https://user-images.githubusercontent.com/1881481/232690381-dfbdfac3-37de-4e70-a041-3bba2f6bb4e6.png)

They list of patterns in the featured category are static. Why are [these patterns](https://dotcompatterns.wordpress.com/category/featured/) featured? 

# How

Make dynamic the featured patterns by updating them programmatically or manually.

- Manually once every week 
  - Will Ola decide which patterns should be added/removed from the featured category?
  - After clearing the patterns cache, the changes will appear in the editor and the assembler.  
- Programmatically 
  - Decide the strategy - Which strategy do we want?
    - Maybe randomly pick one or two patterns from each category?
  - If we only want to update the featured patterns on the assembler, it could be easily done from the front-end because we have the whole list of patterns indexed and we can control which patterns are shown in the featured category.
  - If we want to update them in the editor too, we could create a script to recategorize them and run it periodically using a cron every week.

**Comment by autumnfjeld** [comment]
As a precursor to this, let's hide/remove the featured category because it is currently stale and not really serving the purpose of "Featured" or "Best of".   See slack discussion: p1681802119464299/1681325885.219489-slack-C048CUFRGFQ

**Comment by richtabor** [comment]
A bit of context on the theme front. It's not abnormal for folks to place a theme's more interesting patterns into the "Featured" category. In the context of the Assembler I probably wouldn't have any classified as featured. 

For dotOrg context, the Pattern Directory marks [some patterns as featured](https://wordpress.org/patterns/author/wordpressdotorg/categories/featured/), which are then available within the Pattern Inserter's Featured category. Though I'm thinking the featured category should probably be more local (either theme, or plugin, etc) — instead of a holistic "I see this same pattern front-and-center on every WP install" approach.

**Comment by miksansegundo** [comment]
Thanks for sharing that context. Here is the current status of the featured category:

- in the editor:
  - we don't feature patterns from the Dotcom library.
  - we still feature patterns coming from themes and plugins, as it worked before.
- in the assembler:
  - we don't feature any patterns

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
