### ISSUE TITLE
Stats: Subscribers - update chart CSS and add a gradient

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#75932]
Update CSS for subscribers chart to match the designs.

# Designs
- Widescreen
![Image](https://user-images.githubusercontent.com/112354940/232933558-716a889b-905d-42ab-9939-d5be971deca0.png)

- Mobile
![Image](https://user-images.githubusercontent.com/112354940/232933736-ecd0595d-36c8-47f2-a841-4ae4dac4ca04.png)

# Development
- [x] add a gradient
- [x] check mobile view and update if needed
- [x] verify the colour for the x and y-axis labels and the lines going through the chart area
- [x] y-axis might not start with 0 - check with the designers if the chart looks fine without a line for the x-axis
- ~~check if we can influence the step for the y-axis and if we have to reduce it for a better look~~ (skipped because this detail is too small at this stage)

**Comment by jsnmoon** [comment]
@annacmc: Adding a gradient to uPlot seemed nontrivial the last time I looked at it, so feel free to punt on this task if it seems too challenging. (I wasn't able to figure out a clean way to do it, for example.)

**Comment by annacmc** [comment]
Thanks @jsnmoon you're right - it's not possible to do this with CSS. It needs to have a custom hook or plugin written for uPlot in order to create the gradient. I thought I had it sorted out but for whatever reason it's still not actually working. I might move on to something else right now. If someone else picks this up, I suspect the solution is along these lines:

1. Create a plugin function that returns a hook, similar to this (but not this - it doesn't work) 

```tsx
function bgGradientPlugin() {
	function drawChartAreaGradient( u: uPlot, seriesIdx: number ) {
		if ( seriesIdx === 1 ) {
			const ctx = u.ctx;
			const series = u.series[ seriesIdx ];
			const yScale = u.scales[ series.scale! ];
			const offsetY = ( yScale.range as number[] )[ 1 ] - ( yScale.range as number[] )[ 0 ];

			ctx.save();

			// Set the gradient fill
			const gradient = ctx.createLinearGradient( 0, 0, 0, offsetY );
			gradient.addColorStop( 0, 'blue' );
			gradient.addColorStop( 1, 'red' );
			ctx.fillStyle = gradient;

			const path2D = series.paths;
			if ( path2D && u.series[ 0 ].idxs ) {
				const idx0 = u.series[ 0 ].idxs[ 0 ];
				const idx1 = u.series[ 0 ].idxs[ 1 ];
				if ( typeof idx0 !== 'undefined' && typeof idx1 !== 'undefined' ) {
					const path = path2D( u, 0, idx0, idx1 );
					if ( path instanceof Path2D ) {
						// Draw the fill using the existing path
						ctx.fill( path );
					}
				}
			}

			ctx.restore();
		}
	}

	return {
		hooks: {
			drawSeries: drawChartAreaGradient,
		},
	};
}
```

2. Call the plugin from the chart config
```jsx
plugins: [ bgGradientPlugin() ],
```

**Comment by grzegorz-cp** [comment]
This is indeed tricky. uPlot is using HTML canvas to draw the chart so we can't just use CSS to add the gradient.
I found those examples in uPlot repo -  [code](https://github.com/leeoniya/uPlot/blob/master/demos/gradients.html), [page](https://leeoniya.github.io/uPlot/demos/gradients.html).

There is some issue with the chart not populating min and max values for the datasets and axis' when generating the chart for the first time. This makes the code in the examples not applicable to our scenario, but the mechanism could be used by our chart.

Mode documentation about canvas gradient and methods we could use - [here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors) and [here](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createLinearGradient).

**Comment by grzegorz-cp** [comment]
After solving the problem with uninitialised values, the above examples are fine for our use case.

**Comment by jsnmoon** [comment]
~~Let's shelve adding the gradient for now since the implementation requires far more effort than the utility it brings.~~

~~In fact,~~ we'll likely want to forgo area charts altogether once we start plotting multiple data series on the same chart (e.g., Total Subscribers vs. Free Subscribers vs. Paid Subscribers).

EDIT: Please disregard the first part of my message; Grzegorz already has a working gradient implementation in #76258.

**Comment by leeoniya** [comment]
yes, you need to create a canvas gradient, but you should do this inside a `series.fill` callback that returns the created gradient.

**Comment by keoshi** [comment]
@grzegorz-cp Leaving my comment in this issue but a lot of this is also related to https://github.com/Automattic/wp-calypso/pull/76258

First off, the chart in that PR is looking absolutely fantastic!! I'd be very happy with that already, but suggesting three small changes:

- [x] Changing the top range of the gradient opacity from `0.7` to `0.4`.

This should make the gradient more subtle, letting the main stroke stand out on its own a bit more. Here's the code I used a small preview of what it looks like:

```
[min + range * 0.0, 'rgba(48, 87, 220, 0)'],
[min + range * 1.0, 'rgba(48, 87, 220, 0.4)'],
```
<img width="809" alt="image" src="https://user-images.githubusercontent.com/390760/235889474-f26d3d85-7e4a-4394-b3cd-74c7f6cdb2da.png">

- [ ] More of a question, but would it be possible at all to respect the user's color scheme selection as we currently do with the bar charts instead of hardcoding the blue above?

- [x] Stretch goal, but it would be great if we could have smooth curves in the chart, using uPlot's `spline` line interpolation.

Here's an example of what it would look like:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/390760/235897698-751b3a79-1fff-455f-bade-7bef298ab2fb.png">

>  y-axis might not start with 0 - check with the designers if the chart looks fine without a line for the x-axis

It looks a bit odd without that reference point, but if it's impossible to have or really hard to accomplish I think it's fine to do without it.

---

Last but not least, I'm very excited for this change as it's a faaaantastic primer for updating our current bar charts into more modern and elegant line charts. Great work, y'all!

![image](https://user-images.githubusercontent.com/390760/235899116-ea115e82-c43e-4ab3-94e4-c53e70197d5e.png)

**Comment by jsnmoon** [comment]
>would it be possible at all to respect the user's color scheme selection as we currently do with the bar charts instead of hardcoding the blue above? (@keoshi)

We could, but we'd need to implement a library to hardcode a mapping between the user's current theme and the desired chart color palette. We'll strive to offer it after our MVP.

**Comment by keoshi** [comment]
That’s more than reasonable, @jsnmoon. Wanted to mention it so it’s logged somewhere, but didn’t want to distract you from shipping this.

**Comment by jsnmoon** [comment]
I might be mistaken: it looks like @grzegorz-cp might have [theming support in mind for the MVP](https://github.com/Automattic/wp-calypso/issues/76328) 🙂

**Comment by grzegorz-cp** [comment]
Thanks for the feedback. I applied `spline, the smaller alpha for the blue area and an rgba colour for the y-axis grid lines.
 
We are thinking about setting up the beginning of theming or at least allowing for a set of nice colours (if we use more than one area on one graph). In the end, it boils down to having some way of mapping a theme, but we'll explore it a bit further down the road, as @jsnmoon mentioned.
