### ISSUE TITLE
Show warning in editor when autosave fails or gets stuck

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#75976]
### What

Display a warning notice to the user that it's time they save manually and refresh, as their autosaves may have encountered an issue on their device.

### Why

Occasionally, the Autosave feature gets stuck and fails to preserve content while a user is working, even locally.  It seems this can happen for a few reasons, such as:

- The user loses internet connection without noticing and continues working on their content
- The user works on a page/post for a significantly long time
- The user has the same page/post open in the editor across multiple tabs of their browser
- Their browser cache is impacting things

This can result in the user losing work, assuming it was saved properly.

Autosaves getting 'stuck' has been reported periodically over the years:

- https://github.com/Automattic/wp-calypso/issues/36191
- https://github.com/Automattic/calypso-pre-oss/issues/11765
- https://github.com/Automattic/wp-calypso/issues/315

Since there are a number of contributing local factors that can cause this, it doesn't seem like we can fully prevent it from happening - but providing a heads up to the user could help avoid loss of content, and clue users in to a potential problem early.

### How

According to the [WordPress.com Support Doc on Revisions](https://wordpress.com/support/editors/page-post-revisions/#saving-and-autosave), content changes are

> automatically saved to your local device every 15 seconds and to WordPress.com about once per minute. 

Perhaps we can track how long it's been since WordPress.com received an autosave, and at a certain interval, such as 5 minutes, we can provide a notice to the user?

**Comment by jerrysarcastic** [comment]
We've been seeing this issue pretty steadily in the forums, so I suspect this is affecting many more folks (who are not contacting us) and is worthy of dev attention.  Here is a recent sampling to add some sense of scope:

https://wordpress.com/forums/topic/lost-draft-70/
https://wordpress.com/forums/topic/autosaving-6/
https://wordpress.com/forums/topic/why-is-it-still-autosaving/
https://wordpress.com/forums/topic/lost-revisions-2/
https://wordpress.com/forums/topic/how-to-cancel-autosave/
https://wordpress.com/forums/topic/autosaving-doesnt-work/
https://wordpress.com/forums/topic/autosave-issue/
https://wordpress.com/forums/topic/autosave-and-sudden-refresh/
https://wordpress.com/forums/topic/lost-hours-of-work-because-autosave-did-not-work/
https://wordpress.com/forums/topic/autosave-bug/
https://wordpress.com/forums/topic/lost-work-29/
https://wordpress.com/forums/topic/autosave-not-working-4/

**Comment by davemart-in** [comment]
Seems like there were a bunch of related forum posts all around the same time. I went to the forums and searched for autosave and there don't appear to be any recent reports. Closing this out.
