### ISSUE TITLE
On discussion settings, the info tooltip icons are misaligned with the text

### ISSUE THREAD

**Issue by emilyaudela** [Automattic/wp-calypso#76155]
### Quick summary

On https://wordpress.com/settings/discussion/, in the Comments section the tool tip icons are not aligned with the text. This happens in English and non-English. 

![Markup on 2023-04-24 at 21:39:11](https://user-images.githubusercontent.com/36699353/234099528-5bbb77c8-d961-4ef8-b976-e0cba93d427d.png)

![Markup on 2023-04-24 at 21:45:50](https://user-images.githubusercontent.com/36699353/234100145-1f332372-d7bd-4dee-b384-710d93e7135a.png)

### Steps to reproduce

1. Start on wordpress.com
2. Go to https://wordpress.com/settings/discussion/

In the comments section, the tooltip icons don't align with the text.

### What you expected to happen

The tooltip icon would be horizontally aligned with the text.

### What actually happened

The tooltip icon is too high.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by CodingKite** [comment]
The same issue is at multiple locations in the codebase wherever we have used <SupportInfo/> (used to show the info icon) with <ToggleControl /> 

Why the problem exists:
- Because <ToggleControl />  is an self-enclosing tag.

There are a few possible solutions to it : 
- We can wrap <ToggleControl /> and <SupportInfo/> with an enclosing tag like <div> 
- We can make another container <ToggleControlWithContent> which is not an self-enclosing tag, rather it wraps <ToggleControl /> and <SupportInfo/> into a single <div>. **[RECOMMENDED]**

**Comment by emilyaudela** [comment]
Sorry for the late reply! I am not a developer so I can't really provide any advice as to which is the best solution.
