### ISSUE TITLE
Purchase management: Deleted payment methods can flash back on the screen after being deleted

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#76238]
### Quick summary

After deleting a payment method, I've seen the deleted payment pop back onto the screen (typically after a page reload) for a short while. This seems to be a new behavior.

The payment method is actually deleted (I checked this on the server) so it appears to be some kind of minor caching issue in Calypso.

### Steps to reproduce

1. Go to https://wordpress.com/me/purchases/payment-methods
2. Delete a payment method
3. Reload the page. (Maybe there are other ways to reproduce it too -- I think when I first saw it I may have reproduced it differently. But this seems to be the simplest one.)

Video:

https://user-images.githubusercontent.com/235183/234345980-b2272fef-7c4c-43cd-955d-d163138770ff.mp4

### What you expected to happen

The payment method would not appear on the page, since it was deleted.

### What actually happened

The payment method temporarily flashed onto the page before disappearing again.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Account – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described - though after refreshing my screen, the deleted payment method only appeared for 1-2 seconds, before clearing out again.
- When I refresh the screen a second time, the payment method does not appear again.
- Firefox 112.0.1 (64-bit)

📌 ACTIONS
- Assigned to Other

**Comment by michaeldcain** [comment]
From planning:

This could possibly be solved by adjusting the react-query options on the hook used for deleting payment methods. Slightly lower priority, but possibly a quick fix.

**Comment by sirbrillig** [comment]
I was able to reproduce this fairly easily. The payment method is deleted, disappears from the list, and then when you reload the page, it reappears briefly.

This is strange because [the hook invalidates the cache](https://github.com/Automattic/wp-calypso/blob/7dfd2014f7cd11551ebf88d32a2ddbed1f234b6d/client/my-sites/checkout/composite-checkout/hooks/use-stored-payment-methods.tsx#L104) and you can see that a new query is run which causes the deleted item to disappear. It then only reappears when the page gets reloaded and I checked: there's no API call being run when that happens, so this is definitely coming from some sort of local cache. However, to my knowledge, react-query doesn't use any persistent cache.

It might have to do with calypso's [implementation of the query client](https://github.com/Automattic/wp-calypso/blob/7dfd2014f7cd11551ebf88d32a2ddbed1f234b6d/client/state/query-client.ts#L21-L47) (added in https://github.com/Automattic/wp-calypso/pull/56828) which seems to do some persistent caching but maybe its data doesn't get updated on every fetch?

**Comment by sirbrillig** [comment]
Ah hah. This sounds like a similar issue: https://github.com/Automattic/wp-calypso/pull/69257

> Our current configuration of React Query Client is saving the "latest" state of the queries in IndexDB. This was showing an incorrect state when you added or removed an SSH key and refreshed the page immediately.

It looks like there's a `persist: false` option we can set to prevent the caching from happening. Still, it makes me wonder why this is happening in the first place.

**Comment by sirbrillig** [comment]
Some discussion on Slack that may be worth following: p1683655760754029-slack-C02DQP0FP

**Comment by sirbrillig** [comment]
> Data are persisted to IndexedDB every 5 seconds, it’s this throttled call: https://github.com/Automattic/wp-calypso/blob/trunk/client/state/query-client.ts#L28-L32

> So, if you modify the data and then reload within 5 seconds before the next save can occur, you’ll load stale data

**Comment by sirbrillig** [comment]
I'm going to say that the benefit of persistent caching of payment methods probably outweighs the likelihood of someone reloading their page within 5 seconds of deleting a payment method. If we can prove a more common case where this bug manifests, we can reconsider disabling it (which should be trivial based on https://github.com/Automattic/wp-calypso/pull/69257).
