### ISSUE TITLE
People: Unable to invite users to site from iOS Safari

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7623]
#### Steps to reproduce
1. From iOS Safari: https://wordpress.com/people/new
2. Attempt to tap focus into the Usernames or Email field
#### What I expected

To be able to type in usernames and e-mails
#### What happened instead

I'm unable to focus the keyboard in that input field.  @designsimply reports that with an external bluetooth keyboard she's able to shift-tab into it from the Custom Message field, though.
#### Browser / OS version

iOS 9.3.1
#### Context / Source
# manual-testing

**Comment by hoverduck** [comment]
I can reproduce the problem at https://wpcalypso.wordpress.com/devdocs/design/token-fields, so I'm assuming it's a problem directly with that component.

Since there are already items pre-populated in that list, I can successfully put keyboard focus into the field by tapping the X to delete an existing entry.

**Comment by kriskarkoski** [comment]
Confirmed this issue is still present in Safari on my iPad mini running iOS 9.3.5 and on my iPhone 6 on iOS 9.3.5 in Chrome 53.

Reported by a user in #2857805-t

**Comment by KokkieH** [comment]
Another report via [the public forums](https://en.forums.wordpress.com/topic/some-links-are-not-working/page/2?replies=50#post-2803044).

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed that this is still a problem.  @mcsf - it looks like you were the last one to touch the token-field component, can you take a look at this at some point?

**Comment by mcsf** [comment]
@hoverduck: my intervention in TokenField was pretty minor, and I am temporarily without a machine capable of debugging Safari (iOS or macOS). Gently looping @nylen in, in case he'd take a look.

**Comment by mcsf** [comment]
Further exploration with a proper Safari inspector reveal the following:
- The `input` element itself only takes a small width towards the left edge of the apparent input.
- Tapping that real element is possible in order to focus the input field.
- The `input` element isn't only narrow on Safari/iOS — it's seemingly part of the component's design.
- Instead, the culprit seems to be the logic that triggers a `focus` on the `input`.
- This fixes the issue for me:

```diff
diff --git a/client/components/token-field/index.jsx b/client/components/token-field/index.jsx
index f2b2640..f46f6d4 100644
--- a/client/components/token-field/index.jsx
+++ b/client/components/token-field/index.jsx
@@ -113,7 +113,8 @@ var TokenField = React.createClass( {
 			tokenFieldProps = Object.assign( {}, tokenFieldProps, {
 				onKeyDown: this._onKeyDown,
 				onKeyPress: this._onKeyPress,
-				onFocus: this._onFocus
+				onFocus: this._onFocus,
+				onClick: this._onFocus,
 			} );
 		}
 
```

**Comment by mcsf** [comment]
A Web search reveals that there have historically been some oddities with iOS Safari and `focus` events, but most would've been tackled by now. A more [recent thread](https://www.reddit.com/r/reactjs/comments/428m5l/onfocus_and_onblur_only_works_for_input_elements/) concerning React suggests that guaranteeing `tabIndex="-1"` on a `div` is enough to allow to bind to `focus` events, but we already to that in `TokenField`.

🤔

**Comment by mcsf** [comment]
(Per Slack, ping @nylen.)

**Comment by nylen** [comment]
Hi @mcsf, sorry for the delay in responding to this ( :scream: )

I no longer have easy access to an iOS device (or emulator, for that matter) so it's pretty difficult for me to test this on that platform.

At first glance your patch feels like it might be a bit too invasive as a fix for this specific issue.  You mentioned:  "the culprit seems to be the logic that triggers a focus on the input."  So, why not something more specific to that issue, like:  "if the div is clicked in an empty content area, then focus the input?"

Still, it's hard to imagine a situation where you've clicked the component and it shouldn't be active, so maybe it's ok.

Another issue with the proposed patch is that you're calling a method named `_onFocus` during the `onClick` event.  I'd prefer this naming issue to be resolved, as this usually indicates to me that things aren't quite structured as they should be.

Looking a bit closer, here is the contents of the `_onFocus` method:

```js
this.setState( { isActive: true } );
if ( 'function' === typeof this.props.onFocus ) { 
    this.props.onFocus( event );
}
```

I suspect what you really want to call during `onClick` is the `setState ... isActive` line, and *not* the `this.props.onFocus` handler.  So I would suggest the following code changes to your patch:

- Split this line into a new method: `setActive`
- Call `setActive` from the `_onFocus` method
- Also call `setActive` from the `onClick` event.

Finally I would say that this needs testing on as wide a variety of platforms (mobile and desktop, different browsers) as possible.  This component still scares me a bit :scream:

**Comment by mcsf** [comment]
Manual testing suggests this may have been fixed collaterally in the meantime. @hoverduck, can you confirm?
