### ISSUE TITLE
Patterns: Hide featured category

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#76263]
# Description
See #75864 and the comment https://github.com/Automattic/wp-calypso/issues/75864#issuecomment-1512569468 for context.

This is for both the Editor and the Assembler.

Currently the Featured category is not updated frequently enough, making it stale, not useful.  And as the first category, it is likely distorting pattern data in [wpcom_pattern_inserted] 

When decisions are made in #75864, to keep the Featured category fresh , we can re-introduce the feature.

Same applies to Page categories in the Assembler and WP UI. If the featured list is stale, let's hide it for now.

**Comment by miksansegundo** [comment]
In order to hide the `Featured` category, I unassigned patterns and pages from it. I still have to review the code to confirm that it's safe to unregister the category and remove it completely from `dotcompatterns`.

## Testing
To test it we have to visit the assembler, the editor and the add page modal to verify that the `Featured` category is hidden.

## Assembler
![Image](https://user-images.githubusercontent.com/1881481/235447932-40561537-f294-4862-ae6b-cddf87ae114e.png)

## Editor
![Image](https://user-images.githubusercontent.com/1881481/235448082-25c6530e-1e26-4667-8c5e-d6c58cf0ed19.png)

## Add Page Modal
Now the category `About` is open because it's the first available category.

![Image](https://user-images.githubusercontent.com/1881481/235448100-eb25fdf8-bd2f-448e-932b-acd409a08de8.png)

**Comment by miksansegundo** [comment]
This taskl is completed. I forgot to close it. The other related [issue](https://github.com/Automattic/wp-calypso/issues/75864) is still open.
