### ISSUE TITLE
Signup: Google Apps: display fields for first user right away

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#764]
We do not allow users to sign up for Google Apps without setting up at least one user account. We currently display this screen for Google Apps signup, once users chose a domain:

![gapps1](https://cloud.githubusercontent.com/assets/1248436/9875709/b894fe2a-5bb0-11e5-9a1b-2df78d0a8a62.png)

If you click the Add Email button, the screen renders again and displays some input fields for the user account. Since there's no way to proceed without creating at least one user, we should probably skip the Add Email button, and show the fields right away. Like this:

![gapps2](https://cloud.githubusercontent.com/assets/1248436/9875762/161beaf4-5bb1-11e5-8def-83f5fb0339c1.png)

@breezyskies suggested we use the new Google Apps form there to simplify it:

<img width="684" alt="screen shot 2015-09-15 at 7 38 29 am" src="https://cloud.githubusercontent.com/assets/3011211/9879567/d3cfacaa-5b7c-11e5-9bf9-28b677be24e3.png">

@gziolo pointed that, at the moment, we add missing first and last name at the same time we add the Google Apps item to the cart on the server side. We would need to make sure it works properly when users buy domain with Google Apps but they haven't provided address details yet.

**Comment by Lochlaer** [comment]
My understanding from all the Google Apps provisioning logs is that our systems are currently pulling the address, FirstName, LastName, and other details from the domain reg form. It causes occasional problems when for some reason the WWD table has a different country input (e.g., *United States* instead of *US*) and Google's API rejects it for not using the required format (Google requires two-letter country codes).
