### ISSUE TITLE
Signup: only display locale suggestions in the first section of a step

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#765]
Right now, if the first step in the flow has several sections (like the Domain step), the locale suggestions is displayed in all of them. We should only display them in the main section of the step.

Steps to reproduce:

- Visit `/start/domain`. You'll land in the main section of the Domains step (`/domain/domains`)Notice the locale suggestions, if you have more than one language added in your browser settings.
- Click Map It. You'll land in another section of the Domains step (`/domain/domains/mapping`) Notice that the locale suggestions are still displayed.

**Comment by bisko** [comment]
This issue is no longer valid, because we currently don't have any flows that start with the `domain` step, which is possibly the only case that observes this behaviour. More information on why is below. 

The locale choice is only shown on the first step of the signup flow.

The domains "step" is a bit special in that matter. When `Map` is chosen, the step is not changed, but just a different screen still inside the `domain` step is shown.
