### ISSUE TITLE
Site editor: misaligned icon in styles onboarding popup

### ISSUE THREAD

**Issue by davewhitley** [Automattic/wp-calypso#76603]
### Quick summary

You can see the issue in these screenshots. The close icon is too low.

Before

<img width="817" alt="Screen Shot 2023-05-04 at 2 16 12 PM" src="https://user-images.githubusercontent.com/618551/236306302-c462e60e-4990-4bda-8a7b-897c51a569f9.png">

Current

<img width="859" alt="Screen Shot 2023-05-04 at 11 58 36 AM" src="https://user-images.githubusercontent.com/618551/236306346-7283ed3a-e9ac-4842-b2af-5bfb8fb799f1.png">

### Steps to reproduce

1. create new site
2. Go to Appearance > Editor
3. Click on Styles
4. Modal should appear

### What you expected to happen

The icon should be aligned correctly

### What actually happened

The icon is not aligned correctly

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Replicable outside of Dotcom – **No**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described. Seems related to this CSS:

```
.wpcom-global-styles-modal .components-modal__header .components-button {
  top: 16px;
}
```

#### Screenshots/Recordings

![Screen Capture on 2023-05-09 at 15-45-54](https://github.com/Automattic/wp-calypso/assets/27249804/426ed195-e638-4f77-ad8c-b8db2b489a88)

📌 ACTIONS
- Assigned to @Automattic/lego since this modal is part of a new user/site's experience - but feel free to let me know if this would be better addressed elsewhere!

**Comment by taipeicoder** [comment]
Fixed via https://github.com/Automattic/wp-calypso/pull/80130
