### ISSUE TITLE
Theme Details: refreshing the page while logged-out results to CTAs not working

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#76663]
### Quick summary
In Theme Details logged out page, refreshing the page results to CTAs being disabeld.

### Steps to reproduce

1. Log out or use incognito
2. Load `https://wordpress.com/theme/miniature`
3. Refresh the page

### What you expected to happen

CTA buttons "Pick this Design" and "Subscribe banner" to be available

### What actually happened

CTA buttons "Pick this Design" and "Subscribe banner" were disabled

![CleanShot 2023-05-08 at 14 04 15@2x](https://user-images.githubusercontent.com/12430020/236808531-74cb02be-8ba5-4716-8cb7-42f56e9c527a.jpg)

**Comment by cpapazoglou** [comment]
I have tracked down the bug to this change https://github.com/Automattic/wp-calypso/pull/74883/files#diff-37e3b422dd740fc07578772e39876041fe377de10c1cbfbbdfcf9bb4931ae8d8R19-R39

@epeicher any ideas why this change might make the SSR fail?

Paging also @claudiucelfilip who has worked on the Plugin details SSR in case he can share any insights.

**Comment by epeicher** [comment]
> I have tracked down the bug to this change https://github.com/Automattic/wp-calypso/pull/74883/files#diff-37e3b422dd740fc07578772e39876041fe377de10c1cbfbbdfcf9bb4931ae8d8R19-R39
>
> @epeicher any ideas why this change might make the SSR fail?

As commented, it does not seem to be related to that commit, as I have been able to reproduce the issue with the previous commit. 
I have been investigating a bit, and the error seems to be that the Server Rendered version returns the class `theme__page-upsell-disabled` **but** the Client does not delete that class from the dom. The classes added by the Client do not contain `theme__page-upsell-disabled` but the DOM contains it. You can see the CSS class added by the Client adding a `console.log` of `elementClass` [here](https://github.com/Automattic/wp-calypso/blob/1b22ee1a52781595ed58191724505b50c6ba8516/packages/components/src/card/index.tsx#L55-L56) and the HTML Dom element contains that 
![CleanShot 2023-05-11 at 12 59 52@2x](https://github.com/Automattic/wp-calypso/assets/3519124/3428be6a-62bc-428a-acf5-cc925957a5ad)
Compared to the scenario where it works (deleting the browser cache), the only difference I can see is that it forces the DOM to re-render. So the problem seems that the cached version does not identify changes and it does not re-render the DOM of that specific component.

**Comment by WBerredo** [comment]
Apparently, we need to guarantee the [initial state to be the same](
https://github.com/facebook/react/issues/20152#issuecomment-721066999) for React SSR. This is currently not the case as the `isLoading` starts with `true` on the non-cached case, but after having it cached it will always return as `false`, causing the the disabled state to remain unchanged.

https://github.com/facebook/react/issues/20152#issuecomment-721066999
