### ISSUE TITLE
Reading Settings: Logic for setting blog page incorrect

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#76681]
### Quick summary

While redoing my site this past weekend, I got into a situation where I lost my blog page after creating a front page template. Being a long-time WordPress-er, I knew that I could just create a new page named "Blog" and then set that as my posts page. But, when I went to the UI in WordPress.com, I saw this:

<img width="792" alt="Screenshot 2023-05-08 at 2 19 17 PM" src="https://user-images.githubusercontent.com/1126811/236914539-e7a87fa6-b850-45a0-ba4c-547895fc6eb3.png">

To specify, the posts page setting was grayed out. To work around this, I selected the "view" option at the top right of the screen and went to classic view. Upon digging in a bit today, what I noticed is that when the "default" option is selected for the homepage select, that the posts page select is disabled.

To the best of my knowledge, this behavior is incorrect and each setting should be able to be selected independently. Why? Because the template hierarchy allows generating pages outside of this setting.

For example, using a template like `front-page.php` or the front page template in site editor will take precedence.

<img width="775" alt="Screenshot 2023-05-08 at 2 19 23 PM" src="https://user-images.githubusercontent.com/1126811/236914549-96e29b1b-8fc3-4232-935d-5751d31dd091.png">

### Steps to reproduce

1. Go to site editor
2. Create front page
3. Add some content there, like "Hello World"
4. Go to Settings > Reading in Calypso
5. Ensure that homepage select is set to default
6. Ensure that you can't set blog posts page
7. Set a page for the home page with some content that is not your "Hello World"
8. Load the frontend of the site
9. Verify that "Hello World" is shown anyways

### What you expected to happen

To be able to set blog posts page and not home.

### What actually happened

Blog posts page setting was disabled.

Workaround is to set a home page or fallback to classic view.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by autumnfjeld** [comment]
cc: @Automattic/lego

**Comment by mashikag** [comment]
This limitation was introduced intentionally when we implemented the Calypso reading settings page.
There were many discussions about the setting at the time when we were introducing the new design. The final call to introduce the limitation was made here: pdtkmj-Vc-p2#comment-1796

cc @tanjoymor

**Comment by tanjoymor** [comment]
@ebinnion The `front-page.php` is the exception from pretty much every angle. But if we set that aside, the majority of themes are built using either `home.php` or `index.php` and when either of these templates are in use you cannot set both a Default Homepage and a Default Posts page because they would be the exact same page and not necessarily a “blog”. 

This is most relevant for Block themes, but isn’t harmful on Classic themes, the functionality is the same users just can’t edit the templates. 

In the event that `front-page.php` is being used, the solution is to assign a Custom Homepage, which will then allow the Default Posts page to be assigned. 

Please don’t change this behavior, it will cause problems and confusion. 

Classic and Block themes all work as expected, without confusion when following these parameters:

Default Homepage / Custom Posts Page
Custom Homepage / Custom Posts Page
Custom Homepage / Default Posts Page

[https://wordpress.com/support/pages/front-page/](https://wordpress.com/support/pages/front-page/) 

[https://wordpress.com/support/create-a-custom-homepage/](https://wordpress.com/support/create-a-custom-homepage/) 

p7DVsv-gzS-p2

**Comment by tanjoymor** [comment]
To experience a live example of why this is so important:

1. Create a new site
2. Select the Pendant theme
3. View the Homepage to see what it looks like
4. Under Settings > Reading assign both a Homepage and a Posts page
5. View the Homepage and the Posts page
6. You will now have a Posts page that looks like the theme’s demo Homepage

If you could use the Default for both Home and Posts, Pendant would be giving you 2 Homepages and no Posts page. Many themes are now doing this.

**Comment by ebinnion** [comment]
I disagree that the disabling of the posts page select is the way to go. If we want to find some other way to minimize confusion, such as improving the description of what the setting is or providing some recommendations, this seems reasonable to me.

But, as is, it seems like another case where Dotcom is doing something different from core and breaking expectations.

**Comment by ebinnion** [comment]
> In the event that front-page.php is being used, the solution is to assign a Custom Homepage, which will then allow the Default Posts page to be assigned.

Sure. Though, why would I set a home page when I'm using the front page template?

**Comment by cuemarie** [comment]
Tried walking through this with some empathy testing:

On a test site using Blank Canvas, my site editor only shows 3 templates, but if I click `+` I'm prompted to create lots of new templates, starting with the **Front Page**. Sounds great to me - let's build a homepage:

<img width="550" alt="screenshot" src="">

I went through the process of [setting up my front page template](https://github.com/Automattic/wp-calypso/assets/27249804/6dd76d0c-9dac-42a7-b178-6ea2d2960415) with a header pattern, content pattern, and footer pattern, then saved that.

Next, I'd like to set a page as my default posts page: return to my Settings > Reading page, and I cannot.  It's not super clear why - if I select the Homepage dropdown, my only options are to change my front page to a static page, which I don't need since I just built a Front Page template.

To resolve, I must assign one of my static pages as the Home page, even though I created my whole front page on the template itself.  This was the same in either the Classic or Default View.

I agree that it felt un-intuitive to lock down the Default Posts page after I set up a custom template for my front page, and it wasn't clear from my experience in the editor why that was.

**Comment by ebinnion** [comment]
> Please don’t change this behavior, it will cause problems and confusion.

After reading through @tanjoymor's post that she linked above and thinking about it, I still think that the current behavior is broken and needs to be fixed.

That said, perhaps we don't have to allow the settings to be managed independently as I originally suggested. Perhaps, we can leave the logic as is _unless_ a front page template is saved for the current site... when a front page template is saved, then perhaps we could:

1. Disable the "Your homepage displays" select with some explanation, as it's now useless.
2. Enable the "Default posts page" select.

**Comment by tanjoymor** [comment]
I completely agree that when the `front-page` template is in play, the process is extremely unintuitive. There were many conversations around the situation with templates last year when most of the confusion was surfaced. At the time, Dotcom didn't have any themes that were using the `front-page` template (we now do, and users are also now activating it themselves). 

If @ebinnion's suggestion above is possible to do when `front-page` is active on the site, that would be terrific. I was led to believe that it wasn't possible. It had to be one way or the other for all scenarios.

Since having the `front-page` template was a much lower instance, and the scenarios of users ending up with a Home and Blog page that were identical, or a Blog page that looked like the theme's Home page, were much higher, the current set up was decided upon.

In October 2022, when all of the conversations around templates and theme changes were at their peak, I had proposed the idea of Dotcom themes fully leaning into using the `front-page` template in this post pbxlJb-2Wa-p2 but it was decided against going that route for various reasons that I don't have all the details on.

There are dozens of P2 posts/comments and Slack conversations around all of this, it was an extremely messy, complicated, and confusing situation to work through. I'm not sure if I can track them all down but I can try if you'd like.

@ianstewart and @jffng do you have any thoughts to add to this?

**Comment by tanjoymor** [comment]
> But, as is, it seems like another case where Dotcom is doing something different from core and breaking expectations.

It's actually not. In the core software if you have `front-page` active and the Reading Settings are set to "Latest Posts" you can't select a Posts Page:

<img width="922" alt="Screenshot on 2023-05-09 at 22-22-18" src="https://github.com/Automattic/wp-calypso/assets/42655541/82cf713f-b24f-4140-a832-9a03358422c0">

In order to set a Posts Page you have to select a static Homepage:

<img width="859" alt="Screenshot on 2023-05-09 at 22-23-11" src="https://github.com/Automattic/wp-calypso/assets/42655541/4d13bdfb-0235-4d4b-98d2-a647668c2a48">

As is the current case in Dotcom, when `front-page` is active it hijacks any Homepage related settings. You have a static Homepage assigned, but it is ignored completely.

**Comment by tanjoymor** [comment]
At the end of the day, I'm still of the opinion that the ideal set up for any theme is to force the situation of `front-page` always being the Homepage and `Index` always being the Posts page and eliminate the range of unnecessary choices and scenarios. But I believe there are backward compatibility issues to Classic themes (and now existing Block themes) if we were to do that, and that's not how core behaves.

**Comment by ianstewart** [comment]
> @ianstewart and @jffng do you have any thoughts to add to this?

The Calypso reading settings for static front page and blog posts pages should work exactly 100% equivalent to the core /wp-admin page and the Customizer. We shouldn't introduce extra functionality or take any away.

It should be fixed ASAP if there's a divergence. As @ebinnion noted it's, "another case where Dotcom is doing something different from core and breaking expectations.

> If we want to find some other way to minimize confusion, such as improving the description of what the setting is or providing some recommendations, this seems reasonable to me.

This is a great idea and should be added in another issue. But correcting the behaviour should take precedent.

**Comment by tanjoymor** [comment]
@ianstewart  While it "presents" differently in appearance, it does actually function the same way as core. There's no divergence happening.

**Comment by ebinnion** [comment]
> In order to set a Posts Page you have to select a static Homepage:

This isn't correct. The static homepage does not need to be set.

<img width="615" alt="Screenshot 2023-05-10 at 2 26 55 PM" src="https://github.com/Automattic/wp-calypso/assets/1126811/4f241986-b420-48ec-bf28-9c5cc60d97fb">

**Comment by ebinnion** [comment]
I've deployed the PR as-is for now. But, will create a follow-up issue to see about changing the behavior for when front-page is in use.

**Comment by tanjoymor** [comment]
> This isn't correct. The static homepage does not need to be set.

To clarify, I meant that you had to choose the Static Homepage option, but you're right, in core it does allow you to select the Posts page with no Home page selected. 

With the PR you've deployed it now reintroduces the situation that if no Homepage is selected in that setting, and a Posts page is assigned, both the Homepage and the Posts page are using the same template. This does also happen in core, so I guess if we do want Dotcom to create that same problem and confusion in order to keep it consistent with core then this is technically correct.

https://github.com/Automattic/wp-calypso/assets/42655541/ba7299dd-4c5c-4f8e-b661-4401837f96dc

@ebinnion  Should we be updating our documentation to explain that if a user doesn't assign a specific Homepage and they do assign a Posts page, then both Home and Posts will be identical?

**Comment by ebinnion** [comment]
> Should we be updating our documentation to explain that if a user doesn't assign a specific Homepage and they do assign a Posts page, then both Home and Posts will be identical?

I think that it depends on the timing here. If this is going to cause increased support, then that makes sense.

That said, we may be able to fix this short-term. The behavior of requiring the home page to be selected to then be able to set the posts page _mostly_ makes sense to me. But, we need to figure out this front page case. Once we address that, I have no concerns with going back to the home page select required to edit the post page select.

**Comment by tanjoymor** [comment]
Fair enough and I would love a fix that works for `front-page` but anyone with the Pendant theme (or similar) right now that selects a posts page without a homepage is going to end up with this: 

https://github.com/Automattic/wp-calypso/assets/42655541/02a17f9f-9a4a-4ab2-9d13-91b8970bb66b

**Comment by tanjoymor** [comment]
Since the `front-page` template is less common in Dotcom, my preference would be to leave it as it was and then find a solution for `front-page` rather than reintroducing this problem. But it's not my call to make.

Other than with the `front-page` template I can't think of a single use case where someone would need or want to set a posts page without setting a homepage.
