### ISSUE TITLE
[Help Center] 'Still need help?' option does not load on wp-admin pages

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#76804]
### Quick summary

When accessing **Help Center** and then selecting **Still need help?** while on a `wp-admin` page, it will show a loading symbol and will not load. 

https://github.com/Automattic/wp-calypso/assets/21261509/17d50a78-ccc8-4b6b-beff-e9895f0b4d4a

### Steps to reproduce

1. Open an AT site
2. Go to a `wp-admin` page
3. Select the **Help Center** (? icon)
4. Click on **Still need help?**

### What you expected to happen

For the WordPress.com support contact options to display

### What actually happened

An infinite loading screen

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

The support contact in the Help Center still works on Calyso pages on AT and on Simple sites.

**Comment by rw-ye** [comment]
User report: 6269953-zd-woothemes

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS

- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

- Issue is reproducible with/without proxy. 

**Simple**

![Screenshot 2023-05-11 at 14 44 05](https://github.com/Automattic/wp-calypso/assets/67279475/9f368ed3-4b13-4e7a-8170-11ca7027c44d)

**Atomic**

![atomic-help-center](https://github.com/Automattic/wp-calypso/assets/67279475/ade056b2-06cc-4114-bbf1-733363b8913b)


📌 ACTIONS

- Assigned to @Automattic/vertex 

📌 Message to Author

- Thanks for the report! Changed the priority to `Normal` since users can still access the help center on the default view.

**Comment by alshakero** [comment]
Fix is here https://github.com/Automattic/wp-calypso/pull/76817

**Comment by alshakero** [comment]
Fix is live.
