### ISSUE TITLE
Balasana Theme - WooCommerce View Cart Link in Add to Cart Success Banner is Erroneously Highlighted

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#76907]
### Quick summary

In the Balasana theme, the View Cart link that appears in the WooCommerce add to cart success banner is highlighted with the same color as the link itself.

### Steps to reproduce

1. Activate the Balasana theme.
2. Set up a WooCommerce store with at least one active product.
3. Open the product page and add the product to the cart.
4. Observe that the View cart link is highlighted, as in this screenshot

<img width="1058" alt="Screenshot 2023-05-14 at 4 16 12 PM" src="https://github.com/Automattic/wp-calypso/assets/12906034/0ffcc81d-694f-44e1-a11c-32b4d8c6b09e">

### What you expected to happen

The View Cart link should not be highlighted. For example, the Strorefront theme has the correct behavior.

### What actually happened

The View Cart link is highlighted.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

**Comment by masperber** [comment]
Initial report: 39879581-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- On an existing WooCommerce site, I activated the Balasana theme and tested adding content to my cart, but the `View Cart` button appeared as expected.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/8899bb25-08ac-400a-a6c4-1526cf54ba79

Comparing my test site with the user's, it seems the user's `View Cart` button is missing padding, but I can't tell why:

**Site where View Cart looks broken**
![Markup on 2023-05-16 at 10:27:24](https://github.com/Automattic/wp-calypso/assets/27249804/a8a9a529-1b08-44d9-bae5-3765778491dc)

**My Test Site**
<img width="1339" alt="Markup 2023-05-16 at 10 34 43" src="https://github.com/Automattic/wp-calypso/assets/27249804/bf5e84ea-7001-4f48-aa53-3f35ae6b4929">


📌 ACTIONS
- Requested author feedback

📌 Message to Author
- Hey @masperber ! Can you see if there are any other details required in order to replicate this issue? It seems that just the Balasana theme active on a WooCommerce site doesn't reproduce the problem on it's own.  I took a look at my test site compared with the user's, and they do have fewer Jetpack Modules active - can you check if that is true of your test environment as well?  Or perhaps there's something specific to the products in question that we can pinpoint as part of the issue. Thanks for taking another look!

**Comment by masperber** [comment]
Hi @cuemarie 

The bug is no longer reproducible on my test sites, and also on the reporting customer's site. Perhaps there was an update to WooCommerce or Gutenberg since my initial report that has resolved this bug.

Thank you for checking! :)
