### ISSUE TITLE
Likes: Clicking Like in Firefox triggers a pop-up

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#77177]
### Quick summary

On the front-end of a blog, clicking "Like" on a post, while logged in, triggers a pop-up in Firefox.

### Steps to reproduce

1. Log into WordPress.com in Firefox.
2. Start on a blog post like https://evesouthworth.com/2023/04/17/etsy-shop-is-live/
3. Click "Like" to like the post. 

### What you expected to happen

The post should be liked.

### What actually happened

A pop-up is triggered:
<img width="460" alt="Screen Shot 2023-05-19 at 11 13 42 AM" src="https://github.com/Automattic/wp-calypso/assets/1689238/bf60adec-16ee-448e-85fe-e791c872e669">
When allowed, the pop-up is blank and disappears, then the post is liked.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by worldomonation** [comment]
This behavior is typically seen when the user attempts to like a post while being logged out.

To demonstrate, I have recorded the following two videos showing the two scenarios - clicking the Like button while logged in, and again while logged out. Note the pop-up alert while logged out, as WordPress.com pops up a window to initiate the login process. Since Firefox blocks pop-ups by default, this is likely what you noticed @allilevine.

**Logged in**

https://github.com/Automattic/wp-calypso/assets/6549265/6d35bdea-00f6-4d4f-b494-f4e075c85b74


**Logged out**

https://github.com/Automattic/wp-calypso/assets/6549265/12fffd14-1d6b-4bd2-b5b1-e8a416def551

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closing as by design

**Comment by allilevine** [comment]
> This behavior is typically seen when the user attempts to like a post while being logged out.

@worldomonation I'm seeing it logged in, but if you can't replicate it then closing sounds good. I'll keep troubleshooting on my end.
