### ISSUE TITLE
Site Editor: Replace Template Part option missing from List View Options if block not selected

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#77280]
### Quick summary

When I want to replace a Header Template Part in the Site Editor, the replace header option only shows up in the floating menu, not in the List View.

### Steps to reproduce

1. Click List View > three dots next to Header:

![dgw2X8UnU3buRZtK7Zw8emcxewpY09CiJWtpPY0X.jpg](https://github.com/Automattic/wp-calypso/assets/84539773/abfc7ded-f8e2-4952-a1ef-0fe58ce38d3f)

2. Click List View > Select the Header > click the three dots from the **floating menu** > Replace Header options is there:

![M6vdHm30kgHT6iIEUa4RV8SKpPMzFTincSXLmi72.jpg](https://github.com/Automattic/wp-calypso/assets/84539773/ddda65bd-e081-4676-9802-53058e605db5)

If I remember correctly, it used to be there at both places.

### What you expected to happen

The option would show up at both block setting menu.

### What actually happened

Only show up on the floating menu.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

In Gutenberg 15.8 the [Block Settings menu was rearranged](https://github.com/WordPress/gutenberg/pull/50453). I wonder if it is connected

**Comment by csabarakasz** [comment]
Sharing again to link the two GitHub links. I wonder if this is related: https://github.com/WordPress/gutenberg/pull/50453

**Comment by csabarakasz** [comment]
Ps.: there are also two Edit buttons in the floating menu 🤷‍♂️ 😆

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- My tests show that `Replace Header` appears in the List View menu as well, but _only if you've selected the Header template part_. If you have something else selected, then click the `...` button next to the Header Template Part in List View, `Create Reusable Block` appears instead of "Replace Header".

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/3c39d8db-df82-41ca-9954-28819781bff9

Test Sites:

**Atomic Site**
- WordPress 6.2.2
- Gutenberg v15.8.1
- Theme Twenty Twenty-Three 1.1

**Simple (Edge) Site**
- WordPress 6.2+ (not able to see exact version as this is a simple site)
- Gutenberg: v15.8.1
- Theme Twenty Twenty Three

**Outside of DotCom**
- WordPress 6.2.2 
- Gutenberg v15.8.1
- Theme: Twenty Twenty-Three


📌 ACTIONS
- Assigned to Non-Urgent
- Added to ‘HE Cross-repo Watchlist’ project board
- Reported in /gutenberg repo: https://github.com/WordPress/gutenberg/issues/50928

**Comment by cuemarie** [comment]
> Ps.: there are also two Edit buttons in the floating menu 🤷‍♂️ 😆

@csabarakasz as this is a different issue, it should be reported separately rather than in the comments here.  I've created this report: 

- https://github.com/Automattic/wp-calypso/issues/77344

**Comment by cuemarie** [comment]
[This comment](https://github.com/WordPress/gutenberg/issues/50928#issuecomment-1571426963) provides some good insight into the underlying issue here.  This issue may remain for the time being, as it's a bit more complicated and less impactful than other issues in the works at the moment.

**Comment by annezazu** [comment]
I can't replicate this using WP 6.6.1 and GB 19.0:

https://github.com/user-attachments/assets/e882da78-0bd0-47dd-b5ee-31e7d3bfab60

I'm also not seeing any recent reports here. Happy to reopen and have folks investigate if we can get more up to date steps.
