### ISSUE TITLE
WPcom Editing Toolkit blocking taxonomies panels from loading in the Calypso editor

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#77355]
### Quick summary

On AT sites, when the editing a post in Firefox while the WordPress.com Editing Toolkit plugin is active, there are 429 errors appearing in the console for the `/wp-json/wp/v2/taxonomies?context=edit&per_page=100&_locale=user` file, which is causing the taxonomy panels like Tags, Categories, and Features Image not to appear in the editor.

I have noticed that this is intermittent, but I've been able to duplicate it on a few sites, including a new test site I created. This was also reported as an issue in Safari, but I was unable to duplicate that.

Reported in #6325560-zen, #6324906-zen, and #6325169-zen

### Steps to reproduce

1. Ensure the WordPress.com Editing Toolkit plugin is active
2. Open a post from the Calypso view of the `Posts > All Posts` area of WordPress.com: https://wordpress.com/posts/

### What you expected to happen

The Categories, Tags, and Featured Image panels would be loaded as expected

### What actually happened

The panels don't load at all, and the console shows a 429 error for the `/wp-json/wp/v2/taxonomies?context=edit&per_page=100&_locale=user` file that (I think!) should load those panels.

As a work-around, opening the post from the WP Admin view of the `Posts > All Posts` _does_ work.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Firefox 113.0.2 and 114.0b8

![429 Error (Test Site)](https://github.com/Automattic/wp-calypso/assets/4000628/7f21a496-f699-4247-87de-5fb6178f912e)

**Comment by khristiansnyder** [comment]
Reported in Firefox:

#6329522-zen

**Comment by john-legg** [comment]
📌 REPRODUCTION RESULTS

Tested on Simple – Could Not Replicate (not applicable)
Tested on Atomic – Replicated 
Replicable outside of Dotcom – No (fatal error activating the editing toolkit plugin)

📌 FINDINGS/SCREENSHOTS/VIDEO

Tested using: Firefox 113.0.2, Safari 16.4, and Chrome 112.0.5615.137. 

This one was a bit tricky to replicate. The panels mentioned (Categories, Tags, and Featured Image) load 90% of the time for me, but every once in a while, one will disappear (usually the Featured Image panel):

https://github.com/Automattic/wp-calypso/assets/96805492/89f6bde0-6bc8-4cb7-ae00-1999c6c99d6d

In fact, after recording this video, I went back to `Posts > All Posts`, opened it again, and the Featured Image panel showed up:

<img width="1281" alt="Featured Image Panel" src="https://github.com/Automattic/wp-calypso/assets/96805492/b6d64bbf-e6e6-4a0e-b752-7913f80e9e68">


As shown in the video and screenshot, there are a handful of `428` errors and I even see the one mentioned in the issue description once in a while: `/wp-json/wp/v2/taxonomies?context=edit&per_page=100&_locale=user`. However, I never got the `429 Too Many Requests page`.

I was also able to replicate this on Safari, where only the Featured Image was visible, but wouldn't display any content when expanded:

<img width="1281" alt="Feature Panel Safari" src="https://github.com/Automattic/wp-calypso/assets/96805492/c0eff3f7-f2e0-4cd9-a447-7fe703edd5cd">

Unfortunately, I was not able to test on self-hosted because I kept getting a sitewide fatal error when trying to activate the WordPress.com Editing Toolkit Plugin. I'll have to investigate this later in a separate bug.


📌 ACTIONS

Assigned to column `Non-Urgent`

**Comment by edequalsawesome** [comment]
Reported in 6330711-zen on Safari 16.1, requested a follow-up 6330815-zen

**Comment by edequalsawesome** [comment]
Reported in Safari 16.4 in 6334820-zen, follow-up requested through 6334853-zen

**Comment by zdenys** [comment]
6329097-zd-woothemes

**Comment by galakhyati** [comment]
Reported in 6336244-zd-woothemes

**Comment by sguzovskaia** [comment]
Reported in Firefox 6322312-zen

**Comment by inaikem** [comment]
Reported in Safari: 6338146-ZEN

**Comment by worldomonation** [comment]
This has been noted in E2E tests in the CI, where it is run on a Playwright-controlled Chromium with strict settings (ie. third-party cookies completely disabled). 

Slack: p1684982386797169/1684346413.217409-slack-CDRRDATPS

**Comment by worldomonation** [comment]
Additionally, I was able to reproduce the missing Categories/Tags/Featured Image on the first attempt at loading the AT editor.

Left window is the first attempt. The right window is the second attempt.

<img width="1530" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/dc2cc050-3e72-4f10-b759-93e41533eeb6">

**Comment by ktyfuller604** [comment]
6341954-zd-woothemes 
Safari: Version 16.4 (18615.1.26.110.1)

**Comment by khristiansnyder** [comment]
#6342578-zd

Tags missing in Safari.

**Comment by pauloeaquino** [comment]
6337925-zd

Browser: safari

**Comment by kcswong** [comment]
Reported in Firefox 6345609-zd-woothemes

**Comment by cuemarie** [comment]
~I'm fairly confident my user was encountering this yesterday (though I wasn't aware of the bug yet)~ This user confirmed deactivating WPcom Editing Toolkit resolved the missing sidebar sections on their iPad > Safari: 

- Chat: 6343221-zd-woothemes
- Follow up: 6347827-zd-woothemes

**Comment by cuemarie** [comment]
I was also able to replicate after a few tries, using these steps:

1. Opened a test AT site
2. Opened WordPress.com/posts/
3. Opened an existing post
4. Refreshed it.

The problem appeared on probably the 3rd or 4th refresh - no categories, tags, or featured image modules in the Post Settings sidebar. 

The `428` errors noted above are present in the console logs, along with lots of other activity.

https://github.com/Automattic/wp-calypso/assets/27249804/6b8d845c-727e-4f91-8b61-732dbdf4ef14

- **WordPress.com Editing Toolkit Version 3.67126** active
- Firefox 113.0.2 (64-bit)

📌 ACTIONS
- Escalated for input here: p1685485284796319-slack-C02DQP0FP

**Comment by cuemarie** [comment]
> Unfortunately, I was not able to test on self-hosted because I kept getting a sitewide fatal error when trying to activate the WordPress.com Editing Toolkit Plugin.

I was able to replicate this as well, and I've reported this issue here: 

- https://github.com/Automattic/wp-calypso/issues/77573

**Comment by pauloeaquino** [comment]
Another report in 6345085-zd

**Comment by masperber** [comment]
Another report: 6355864-zen

**Comment by masperber** [comment]
Customer requested followup when resolved: 6355945-zen

**Comment by cuemarie** [comment]
There's some larger conversation happening regarding the WPcom Editing Toolkit here, that seems related: p1685550995632009-slack-C03N25JPCE4

That conversation has resulted in this PR which 🤞 may resolve the issue:  https://github.com/Automattic/wp-calypso/pull/77629

**Comment by cuemarie** [comment]
So far, I'm not longer able to replicate this issue, across multiple sites! 

📌 ACTIONS
- Closed as resolved (please reopen if you find this still happening on test or user sites.
