### ISSUE TITLE
Gutenberg conflict with Yoast SEO and Yoast SEO Premium with a notice "Updating Failed" after previewing any post

### ISSUE THREAD

**Issue by renata-franco** [Automattic/wp-calypso#77469]
### Quick summary

I got a ticket from a user with Business plan that reported that after visiting any of their published or scheduled posts, and previewing them, opening a new tab for this, which is automatic, and closing this tab, they got an error at the top of the editor saying "Updating Failed". 

Looks like this: 

![CleanShot 2023-05-28 at 18 06 24](https://github.com/Automattic/wp-calypso/assets/81378719/4f4a8a95-fccb-40ac-8228-cd1800d6729a)

After some troubleshooting from my end, I see that the problem is actually Gutenberg Plugin active and Yoast SEO and Yoast SEO Premium active as well. 

I was able to replicate the issue on a test site with Business plan. 

### Steps to reproduce

1. Install Yoast SEO and Yoast SEO Premium. 
2. Have Gutenberg plugin active on the site. 
3. Go to a published or schedule post. 
4. Click "Preview" on the top right of the editor. 
5. Check the new tab open with the Preview of the post. 
6. Close the preview tab and come back to the editor. 
7. The error will appear now. 

### What you expected to happen

No error should appear. 

### What actually happened

The error appears like this: 

![CleanShot 2023-05-28 at 18 06 24](https://github.com/Automattic/wp-calypso/assets/81378719/0d0ec890-fa98-4d56-937b-6db0b4e0e83e)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

- Seems like other plugins do not cause any difference. 
- Gutenberg plugin is 15.8.1. 
- Deactivating Gutenberg plugin fixes it. 
- Looks like the theme does not affect this issue.
- The problem is mostly an annoyance, and there doesn't seem to be any other issue with anything.

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS

   Tested on Simple – Not applicable
   Tested on Atomic – Reproduced
   Replicable outside of Dotcom – Not Applicable (Yoast SEO Premium plugin not available)

📌 FINDINGS/SCREENSHOTS/VIDEO

**AT**
<img width="1271" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/f92ed70e-d25a-4194-b423-32c142798c2a">

What looks to be happening is that, because "Preview post in new tab" saves the draft automatically, the Yoast SEO and Yoast SEO Premium plugins are preventing the autosave in some way or another, which triggers the banner.

This can be demonstrated by the following:
1. after opening the scheduled post, make an edit somewhere.
2. follow the preview instructions in the original post.
3. reload the editor.

The changes made in 2 will be gone.

Additionally, getting into this state may prevent the Preview in new tab functionality from displaying the preview until the draft is manually saved again (by clicking on the  `Save draft` button on the toolbar). 

Video demonstrating the above:

https://github.com/Automattic/wp-calypso/assets/6549265/81db11ed-3a52-485d-8f9c-a9d586f93278

<img width="1271" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/1edda769-5f9a-46ff-bf57-e5fd58c86301">

📌 WORKAROUND

After encountering the banner, ensure:

1. save the draft manually.
2. refresh the editor.
3. trigger preview.

It should allow the user to preview while also saving the content of the changes.

📌 ACTIONS
    Moved to Normal priority as a workaround is available.

**Comment by renata-franco** [comment]
Hi @worldomonation. Thanks! Did you also try with published posts? The issue also happens there. Saving as a draft is a possibility?

**Comment by worldomonation** [comment]
> Hi @worldomonation. Thanks! Did you also try with published posts? The issue also happens there. Saving as a draft is a possibility?

Hi, I only tried it with scheduled but unpublished posts. It sounds like this also happens with published posts, is that correct?

**Comment by renata-franco** [comment]
> Hi, I only tried it with scheduled but unpublished posts. It sounds like this also happens with published posts, is that correct?

Yes, it also happens with published posts!

**Comment by cuemarie** [comment]
📌 ACTIONS
- Pinging @Automattic/bespin for your awareness on this one.

**Comment by jeroenrotty** [comment]
Will be fixed by https://core.trac.wordpress.org/ticket/58739 - see previous discussion https://github.com/WordPress/gutenberg/issues/51088

**Comment by cpapazoglou** [comment]
This should be fixed by now
