### ISSUE TITLE
Flaky E2E: Start a WordPress import

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#77642]
### Spec file

specs/onboarding/setup__importer.ts

### Logs

```
page.waitForSelector: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('.content-chooser .import-layout__column:nth-child(2) > div > div:last-child button:text("Continue")') to be visible
============================================================
at StartImportFlow.validateWordPressPage (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/start-import-flow.ts:114:19)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/setup__importer.ts:44:26)
```

![image](https://github.com/Automattic/wp-calypso/assets/6549265/d3aa35d9-ebe7-4245-ab11-fca919bf4cbf)

**Comment by worldomonation** [comment]
Caused by https://github.com/Automattic/wp-calypso/pull/77478.

Revert proposed in https://github.com/Automattic/wp-calypso/pull/77641.

**Comment by ouikhuan** [comment]
Hi @worldomonation , this looks like it's still picking up the old `validateWordPressPage` function during the test. Do you have any ideas about which environment those errors were triggered from? If we have the feature flag turned on this function should never gets called.

**Comment by ouikhuan** [comment]
After some investigation looks like the branches that triggered the errors didn't have the latest feature flag in their branch `"onboarding/import-redesign": true`. For example:
This is a failed build here:
https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Calypso_E2E_Playwright_desktop/10115889?buildTab=tests
When I looked into the code, the new feature flag updated from my previous PR isn't there:
https://github.com/Automattic/wp-calypso/blob/7d4d8576afa56f1c89d745808a8538651d6a3845/config/wpcalypso.json#L113

Here's another example:
https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Calypso_E2E_Playwright_desktop/10123538?expandChain=10123538&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true

Code here also didn't have the latest feature flag:
https://github.com/Automattic/wp-calypso/blob/2648506e9c74569d93c2880c027982458e6dd4bb/config/wpcalypso.json#L113

On wpcalypso, it should show the new flow we introduced because we pushed up the changes, but since these tests didn't have the feature flag, so it's checking the old flow, that's the reason it triggered fail. 

If the above makes sense to you, I've created a new PR to introduce the feature flag in again, it's basically the same as the previous one. Could you have another look? Thank you!
https://github.com/Automattic/wp-calypso/pull/77664

**Comment by worldomonation** [comment]
Hopefully fixed by https://github.com/Automattic/wp-calypso/pull/77664, monitoring.
