### ISSUE TITLE
Export: Prevent exports on unsupported devices

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#78]
We may be able to allow exports on mobile devices since we're using the async exporter—emailing a link to download the file.

We just need to be careful about providing the link on the export status screen to an xml file. On desktop this initiates a download, but on some mobile devices (e.g. iOS) it simply loads the xml file as text in the browser—not helpful.

We could perhaps just conditionalize the message on the status screen indicating that the import has finished and to check your email for the link to the file. They will likely have to sit down at a computer to import that file into another system.

Some options:
- We can use a media query in the css to hide the export download link
- We can look into the way other sections are detecting mobile:
  - /posts does some mobile checks for the component
  - and the sidebar also for showing/not-showing customizer

Note that some mobile devices do support downloading the export file from the browser (tested on Nexus 9, Android 6.0, Chrome and the download worked) so it would be great if we could detect the mobile devices that don't support it and show a different message only for those devices.

**Comment by folletto** [comment]
Yes, sorry, I gave that implied in "download". 

From iOS 9 you can download, store it (Cloud, Dropbox, Drive,... all depends in they have an app installed with the right extension) and then re-upload. It needs to be tested, but from WP Admin you should be already able to do it (using the "Export" icon when the weird page opens):

<img src="https://cloud.githubusercontent.com/assets/4389/11407233/6590e37a-93a9-11e5-9403-2fb81851a9c9.jpg" width="300" />

And then when you tap upload:

<img src="https://cloud.githubusercontent.com/assets/4389/11407240/70fe2452-93a9-11e5-8399-02d4cb0b29d7.jpg" width="300" />

The only difficult thing right now is that the "download" is using the "Export" icon, thus makes it a bit troublesome (doesn't seem to trigger the right apps and even dropbox has problems, no proper file type name or detection). One we turn that in a properly triggered download, should work.

Android should be the same, since they had Upload / Download implemented a few version ago, but I haven't tested. :)

So this means that a user with Import / Export would be able on mobile to download, save, and then re-upload on a different side, making the process of making the data free available even if one has only a smartphone.

Plus the email, which will still be there. :)

**Comment by jordwest** [comment]
Here's how iOS 9 currently handles the Calypso Exporter (in PR #1359):
![export_mobile_flow](https://cloud.githubusercontent.com/assets/416133/12251422/986b560e-b91a-11e5-906b-142ddf8ed29e.gif)

I don't have the Dropbox app installed, but presumably it would also appear as well as iCloud drive.

**Comment by folletto** [comment]
Looks good! :+1:
