### ISSUE TITLE
Back button doesn't work properly after accessing the Blog page

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#78045]
### Quick summary

When the "back" button is being clicked on the browser(after accessing the blog page from the dashboard) the notification sidebar shows up instead of going back to the dashboard.

### Steps to reproduce

1. Activate a theme like Pendant or Bibimbap
2. Make sure there's a Blog page assigned under Settings > Reading
3. Go to Pages and click on the Blog page
4. It should show the blog page directly
5. Click on the "Back" button on the browser
6. The notification sidebar will open up as many times you click on it

### What you expected to happen

To be directed the dashboard

### What actually happened

![JVoOgH.png](https://github.com/Automattic/wp-calypso/assets/6737345/2fe14b13-c10f-4993-973f-8ae72adddeaa)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The theme seems to play a role, but I'm not 100% sure. The Seedlet theme did not appear to have this issue.
Tested on Simple sites.
Tested while using Chrome 114.

Note: after running more tests, the "back" button moves me to the dashboard again, but it's inconsistent.

Video demo: 
https://github.com/Automattic/wp-calypso/assets/6737345/a0584d2f-59a5-4fc2-9baf-5cbdeaf1969e

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – not reproduced
Tested on Atomic – not reproduced
Replicable outside of Dotcom – not applicable

Tried to reproduce with both Bibimbap and Pendant themes, but was unable to do so.

📌 FINDINGS/SCREENSHOTS/VIDEO
**Simple**

https://github.com/Automattic/wp-calypso/assets/6549265/be04dd9a-ed89-460e-8267-203116685561


📌 ACTIONS
- keep Low priority.
- <strike>move to Non-urgent column.</strike> request HE response as I was unable to reproduce.

**Comment by Robertght** [comment]
Thank you @worldomonation !

I tested this again and I'm not yet finding the pattern that's triggering this, but after setting up a new website with 2023 and adding a FrontPage template, then going back to the Pages where the Blog page is and clicking on it, redirects me to the /blog/ page and then the behavior started to happen. 

Not sure what else I can try in the meantime.

**Comment by kspilarski** [comment]
I tested this in Simple and AT sites using Firefox, Chrome and Safari, and I was not able to reproduce the issue. From Pages, going to the Blog opens the blog page. Then the return / back button in the browser took me back to Pages.

**Comment by worldomonation** [comment]
> I tested this again and I'm not yet finding the pattern that's triggering this, but after setting up a new website with 2023 and adding a FrontPage template, then going back to the Pages where the Blog page is and clicking on it, redirects me to the /blog/ page and then the behavior started to happen.

Was it just this one time that it happened, or has it occurred more than once?
Could you elaborate on what a FrontPage template is? I'm not familiar with it. Is it a FSE template?

**Comment by Robertght** [comment]
It happens randomly but most of the times. Sometimes it just works correctly and I cleared the browser cache and cookies.

Also, sometimes it lets me access the Blog page within the editor instead of redirecting me to /blog/

The two sites I'm working with are https://testingnew20220126xbetaefs.wordpress.com/ and https://rdg20172110.com/

The second one has gutenberg-edge enabled, but the first one doesn't.

The FrontPage template can be added through the Templates section like so:

![image](https://github.com/Automattic/wp-calypso/assets/6737345/ec418ac9-f812-44a2-99ba-da80f4a51414)

I'm not yet sure this is the trigger as removing it didn't change a lot of the inconsistencies I'm seeing here.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Attempts to replicate here have failed too. Here's what I've tried:

### Test One

- Brand new free site (TT3)
- Created Blog page and set that as posts page
- Launched site
- Created Front Page template
- Pages > Blog > /blog/ > `Back` always works

```
Gutenberg: v15.9.1
Editing Toolkit: 3.68337
WP AMP: 2.0.5
```

### Test Two

- Existing Free **Edge** site
- TT3 Active
- Home page: `Default` and Posts page: `Blog` - this arrangement allows me to edit the blog page
- Home page: `Home` and Posts page: `Blog` - this arrangement sets the Blog page to open `/blog` instead - still able to go back in the browser, though. 

```
Gutenberg: v16.0.0-rc.5
Editing Toolkit: 3.68337
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.4
```

### Test Three

- Existing Edge Simple site (Starter Plan) using a custom domain as primary
- Activated Bibimbap
- Home was set to `Home` and Posts was set to `Blog` after the switch, but this was still letting me edit the blog page. (I think this is a separate bug perhaps)
- Saving the Homepage as `Default` then `Home` again cleared that up, but from here going to Pages > Blog > /blog > Back still works without issue.

```
Gutenberg: v16.0.0-rc.5
Editing Toolkit: 3.68337
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.4
```
📌 ACTION
- Closed as unable to reproduce (please reopen if pattern to repro is found)

📌 MESSAGE TO AUTHOR
- @Robertght going to close this for now, since a few of us have tried to repro with no luck; please reopen if you can spot a pattern!

**Comment by Robertght** [comment]
Thank you for trying to replicate this!

It looks like this is something super-specific to my setup and I'm not sure why. The Tampermonkey extension is causing this and the only thing that made it work is to limit the access to specific websites only, yet this renders me unable to use it on WordPress.com at the moment. I'll keep an eye to see if I can get a full workaround in place.
