### ISSUE TITLE
Stats: Allow for collapsing and rearranging of stats meta boxes

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#7821]
It's currently not possible to collapse or rearrange the various boxes at wordpress.com/stats/day. It would be nice to be able to do that on a per site or even just a per user basis so users can customize their stats view.
![screen shot 2016-09-01 at 2 37 51 pm](https://cloud.githubusercontent.com/assets/831377/18179688/b2cb7918-7051-11e6-9942-5f333f50cdc4.png)

**Comment by chaselivingston** [comment]
2813764-t

**Comment by lschuyler** [comment]
Also in 2820808-t -> "Two things that I would like on the new stats, if possible, is the ability to customize the default page (I like going right to the Day view with referrers and traffic-per-page for a quick “how am I doing” check) and the ability to customize the view on the new stats page so that I can quickly see the sections I’m watching for."
