### ISSUE TITLE
Theme Showcase: Show different header and description text when logged out

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#78225]
## Description

From https://github.com/Automattic/dotcom-forge/issues/2410:

> On the logged out /themes page, we would like to provide better SEO content and additional content for category page views. And explore design ideas for making the category area on the /themes page more attractive. We can break this into two parts.

This issue will focus on updating header and description texts for different categories, plus a title tag fix:
![Image](https://github.com/Automattic/wp-calypso/assets/797888/051dac80-fff8-40fc-ac5c-6fc721e6ff50)

### Specs

Navigate to the logged-out Theme Showcase (`https://wordpress.com/themes/`) and update the page's copy as specified by the [spreadsheet](https://docs.google.com/spreadsheets/d/10uoJqOZLTne3565nbbR6ggR09vrPhUpK_ztwbuvau14/edit#gid=0).

<img width="1441" alt="Screenshot 2023-06-27 at 15 17 54" src="https://github.com/Automattic/wp-calypso/assets/2070010/755431dd-3991-4d13-95e6-816f7f2149c6">

#### Changes

- `<title>` tag
- `<meta name="description">` tag
- Header
- Description

Remember to consider the translations before deploying (see the team's handbook: PaYJgx-3sX-p2).

## Dev Tasks
- [ ] Update the copy as specified in the [spreadsheet](https://docs.google.com/spreadsheets/d/10uoJqOZLTne3565nbbR6ggR09vrPhUpK_ztwbuvau14/edit#gid=0)
- [ ] Update the title on https://wordpress.com/themes/marketplace to be `WordPress Marketplace Themes` as discussed [here](pdyEEc-st-p2#comment-792) and [here](https://docs.google.com/spreadsheets/d/10uoJqOZLTne3565nbbR6ggR09vrPhUpK_ztwbuvau14/edit#gid=0&range=F13) 
- [ ] Ask @sailerbe  to review when ready

**Comment by taipeicoder** [comment]
T-Rex will be handling this one 🙂

**Comment by Copons** [comment]
@taipeicoder @autumnfjeld @sailerbe I'm reviewing this issue, and I've noticed that the we have more potential duplicate `<title>` tags across multiple different paths, all caused by the tier toggle (All/Free/Premium/Paid).

The issue already mentions `/themes/marketplace` (filters: Recommended / Paid), which is the same as `/themes` (Recommended / All).

But once we filter by subject, the title remains the same for all tiers.

For example, all these paths have the same title ("Blog WordPress Themes - WordPress.com"):

- `/themes/filter/blog` (Blog / All)
- `/themes/free/filter/blog` (Blog / Free)
- `/themes/premium/filter/blog` (Blog / Premium)
- `/themes/paid/filter/blog` (Blog / Paid)

We can proceed with the original proposed changes, but IMHO, we should review how the `<title>` tag should change based on combinations of subjects and tiers.

**Comment by sailerbe** [comment]
@Copons This is a good catch. We could update each duplicative title tag to follow a [TYPE] + [CATEGORY] syntax. Ex:

Blog WordPress Themes - WordPress.com
Free Blog WordPress Themes - WordPress.com
Premium Blog WordPress Themes - WordPress.com
Paid Blog WordPress Themes - WordPress.com

This format could then repeat for each theme category.

In order to keep the copy on each page unique, this would also necessitate slight variations in the header and sub-header copy as well. I can write these variations and add them to the spreadsheet.

**Comment by Copons** [comment]
@sailerbe that would be great, thanks! 🙇‍♂️

**Comment by sailerbe** [comment]
You're welcome @Copons! I've updated the spreadsheet with title tags, header, and subheader copy: 

https://docs.google.com/spreadsheets/d/10uoJqOZLTne3565nbbR6ggR09vrPhUpK_ztwbuvau14/edit#gid=0

A couple additional changes:

- I've also added a column for meta descriptions (we can repurpose the subhead copy for meta descriptions). Most of these pages currently have meta descriptions that are too short, and so Google is overwriting them in search results in a way that doesn't read well by pulling in a random series of theme names ([example](https://www.google.com/search?q=free+wordpress+themes&sxsrf=APwXEdcyyAHEffJgxBW1j0yp5qw7DI371A%3A1687900901620&ei=5VKbZKm-Jevf0PEP0IakuA8&oq=free&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAxgAMgcIIxCKBRAnMgcIIxCKBRAnMgcIIxCKBRAnMgcIABCKBRBDMgcIABCKBRBDMg0ILhCKBRDHARDRAxBDMgcIABCKBRBDMgcIABCKBRBDMgcIABCKBRBDMhMILhCKBRCxAxCDARDHARDRAxBDOgoIABBHENYEELADOggIABCKBRCRAjoRCC4QgAQQsQMQgwEQxwEQ0QM6CwgAEIAEELEDEIMBOgsILhCABBDHARDRAzoECCMQJzoRCC4QgwEQxwEQsQMQ0QMQgARKBAhBGABQygNYkQdg6g5oA3ABeACAAY4BiAGlBJIBAzAuNJgBAKABAbgBA8ABAcgBCA&sclient=gws-wiz-serp)).
- I've rewritten all title tags and header copy so they follow a somewhat more standardized format (though they should still be unique enough to drive SEO benefits).

Let me know if there's anything else I can do to help move this forward.

**Comment by Copons** [comment]
Thanks @sailerbe!

I've mentioned the meta tag in the issue description. AFAICS they are all identical to the descriptions, which means the translations will be reused, which is brilliant. 👍 

I have one last question about the "All / Paid" title (cell D14): `Paid WordPress Themes - WordPress.com Marketplace`.
It's the only one that mentions "Marketplace" and I wonder if it's intentional.

**Comment by sailerbe** [comment]
You're welcome @Copons! I noticed that selecting Paid adds a folder labeled Marketplace to the URL structure, and so my initial thought was that we could append the title tag with "Marketplace" to match, but in retrospect this doesn't seem necessary so I've removed the word "Marketplace" from the sheet.

**Comment by sailerbe** [comment]
@Copons Just want to follow up on this. Is there an ETA on when these updates might ship?

**Comment by Copons** [comment]
@sailerbe apologies for the delay. We had technical difficulties launching an A/B test and had to delay all our non-urgent tasks. We'll work on this during this sprint. 👍

**Comment by sailerbe** [comment]
@Copons Totally understand, thank you!

**Comment by Copons** [comment]
Yesterday I gave this a quick try, but realized that there are a few unexpected complications that I'd like to share with the team @Automattic/t-rex, in case I've overlooked something obvious.

- Is a massive multi-dimensional array hardcoded somewhere in the Theme Showcase the only solution here?
- The sheer amount of new strings might be intense from an i18n standpoint.
  - It's annoying because most strings are similar to each other.
  - I don't think there's any way around this, though, as we should avoid variables in translatable strings.
  - Although the developer in me can't help trying to do a clever mix-and-match to avoid creating the multi-dimensional array.
- Subjects are supposed to provide their own descriptions from the server: they are defined in the `theme_subject` taxonomy.
  - Should we add the descriptions to the server?
    - What about their translations?
  - But then again, maybe not, since we have to combine subjects and pricing tiers.
  - So far, only 3 subjects have a description, so I guess it's not such a big deal if we ignore it?
- Is the SSR'd Theme Showcase cached to death? I couldn't get the meta description to change, no matter what.
- The current spreadsheet might become obsolete soon, as we are working to refactor both the categories (https://github.com/Automattic/dotcom-forge/issues/3057) and the pricing tiers (paYJgx-3AU-p2).

**Comment by sailerbe** [comment]
@Copons 

> The current spreadsheet might become obsolete soon, as we are working to refactor both the categories (https://github.com/Automattic/dotcom-forge/issues/3057) and the pricing tiers (paYJgx-3AU-p2).

Due to the potential for categories to change soon, I wonder if it'd be best to hold off on copy/meta data updates until those have been finalized.

**Comment by Copons** [comment]
> Due to the potential for categories to change soon, I wonder if it'd be best to hold off on copy/meta data updates until those have been finalized.

@sailerbe Yep, that's my same reasoning — although, the technical challenges will remain the same.

Talking with @autumnfjeld, we were considering addressing this issue gradually.
Instead of adding all strings at once, we could start with those that we are certain will remain after the refactor (e.g. it's unlikely we'll drop the Blog category 🙂).

I think this should improve the SEO situation a little bit, and at the same time, it would give us the opportunity to experiment with the technical part.
