### ISSUE TITLE
Stats :: Insights - EN-GB Language in WPcom Account breaks dates in the Posting Activity section

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#78235]
### Quick summary

In the Stats → Insights → Posting Activity section, the date format is incorrect.

### Steps to reproduce

1. In the General settings, set the timezone to London.
2. Go to Stats → Insights → Post Activity section.
3. Move the mouse onto the calendar icon

### What you expected to happen

The date format should be shown correctly.

### What actually happened

The date is shown in the incorrect format as in this screenshot:  

![Markup on 2023-06-15 at 16:18:34](https://github.com/Automattic/wp-calypso/assets/27249804/213b0c72-6377-4f8d-a708-5830d3c3098d)
_screenshot updated to hide user info_

And this video:

https://github.com/Automattic/wp-calypso/assets/1519466/b0dcefda-33d4-4961-887b-39c27f97addc

Site's timezone is London:

![CleanShot 2023-06-15 at 11 06 25@2x](https://github.com/Automattic/wp-calypso/assets/1519466/d611e4a9-ced9-445b-ac1b-c3bbc37f6e50)

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by happychait** [comment]
6398386-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – No - _Not without Jetpack and Claypso_

📌 FINDINGS/SCREENSHOTS/VIDEO
- The issue here seems to stem from the Claypso language being set to `EN GB` or English (UK), not `EN` English.  When that switch is made, the default time on `/wp-admin/options-general.php` changes, and the Stats > Insights > Post Activity section shows incorrect dates, formatted to the new default, as well as a lot of `Invalid Date (Invalid Date)` responses.

| | EN English | EN GB English |
| ------------- | ------------- | ------------- |
| Default Date Format: | June 16, 2023  | 16 June 2023  |
| Insights Posting Activity (Hovering over December 4, 2022) | ![Markup on 2023-06-15 at 16:31:02](https://github.com/Automattic/wp-calypso/assets/27249804/337c212a-bb0f-4cde-b0d0-fe0ec7f1867b) | ![hPTC9O.png](https://github.com/Automattic/wp-calypso/assets/27249804/bcb8081d-c52a-4dd7-96b6-52f3bf2e0390) |


#### Screenshots/Recordings

**Setting Calypso Language to English (EN) **

https://github.com/Automattic/wp-calypso/assets/27249804/131cedf5-2fe9-4ae6-a805-aeeebc174851

**Setting Calypso Language to English UK (EN GB)**

https://github.com/Automattic/wp-calypso/assets/27249804/c34d6bac-1c2c-4309-9672-731e4f40f48b

Notice that when I switch from `EN` to `EN GB`, my selected Date format moves to **Custom:** `F j, Y` to match what was previously selected. However, whether I choose this or the default option, the result is the same in the Insights page.

![k81Jbq.png](https://github.com/Automattic/wp-calypso/assets/27249804/4271c103-9da6-486a-b70f-a64c09099177)

📌 ACTIONS
- Assigned to Other
- CC: @jeherve for Jetpack Stats / Calypso issue

**Comment by kangzj** [comment]
It feels like an issue of date format between PHP and moment.js. It's likely not only affects the posting activity view, but a lot other places too. We'll take a look. Thanks all!

**Comment by kangzj** [comment]
This is already fixed by https://github.com/Automattic/wp-calypso/pull/81588
