### ISSUE TITLE
Request: Allow paid content blocks to use newsletter payment plans

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#78285]
### Quick summary

A payment plan with the option _"Email newly published posts to your customers."_ enabled stopped showing as an option on the Paid Content block.

### Steps to reproduce

1. Create 2 Payment Plans, on Tools > Earn.
2. In one, select the option _"Email newly published posts to your customers."_.
3. On the second, make sure to not select that email option.
4. Create a new page and add the _"Paid Content"_ block, check the available payment plans on the block.

### What you expected to happen

To be able to select both payment plans in the block.

### What actually happened

It shows only the payment plan that doesn't have that email option selected, **it used to show both options**.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Reported on 6414179-zd-woothemes, user was able to select the _"newsletter"_ payment option before, but it stopped showing up, had to ask them to disable that email option, but then the plan subscribers won't receive email updates.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- As described, the `Paid Content` block (formerly Premium Content) only allows me to select a plan that is not for a newsletter.

#### Screenshots/Recordings


https://github.com/Automattic/wp-calypso/assets/27249804/172e72bd-3fb2-4b6d-bb5b-ff6db856f7f7

**Plans on this site**

<img width="1454" alt="Screenshot 2023-06-15 at 4 10 04 PM" src="https://github.com/Automattic/wp-calypso/assets/27249804/5898f317-c0f2-487a-8f93-fc5d3f165c2b">


📌 ACTIONS
- Assigned to @Automattic/apex 

📌 Message to Apex
- Hey folks! I can see how this _could_ be by design, perhaps related to the work happening here: pdDOJh-1Y1-p2 but I can't quite tell what the relationship should be between Newsletter plans and Paid Content plans. Am I correct that this separation is intentional, or did something unexpected happen here?

**Comment by nicolynramos** [comment]
This same behavior happens on regular Payment Buttons blocks as well. I was able to replicate the issue. Payment plans identified as "Newsletter" (having the _Email newly published posts to your customers_ option enabled) do not show in lists of plans able to be set with a payment button. 
6415572-zd

**Comment by inaikem** [comment]
New report in 6462145-zd-woothemes.

I suggested they try duplicating a known working block and/or create new (temporary) plans, which I was able to confirm work.

**Comment by cuemarie** [comment]
CC: @Automattic/gold & @Automattic/zap 

Should we be able to add Newsletter subscriptions to the Paid Content blocks?

**Comment by inaikem** [comment]
> Should we be able to add Newsletter subscriptions to the Paid Content blocks?

I'd love to see a toggle that enables users to selectively "link" payment plans across these two products -> "Make this subscription available to both Paid Content and Paid Newsletter subscribers" ...or something less clumsy. 😉

**Comment by millerf** [comment]
@cuemarie @inaikem 

It was a deliberate choice (see https://github.com/Automattic/jetpack/issues/31199) to not display newsletter plans in the Premium Content block, as it was more confusing than anything.
They are two different subscriptions for different areas  


> I'd love to see a toggle that enables users to selectively "link" payment plans across these two products -> "Make this subscription available to both Paid Content and Paid Newsletter subscribers" ...or something less clumsy

:) I do agree. IMHO it should be more "user" facing, like an option in the Earn admin saying "Premium content users and Paid newsletter users have the same rights"... or something less clumsy.

CCing @crisbusquets for ideas, as Earn is being re-thought...

**Comment by crisbusquets** [comment]
> @cuemarie @inaikem
> 
> It was a deliberate choice (see [Automattic/jetpack#31199](https://github.com/Automattic/jetpack/issues/31199)) to not display newsletter plans in the Premium Content block, as it was more confusing than anything. They are two different subscriptions for different areas
> 
> > I'd love to see a toggle that enables users to selectively "link" payment plans across these two products -> "Make this subscription available to both Paid Content and Paid Newsletter subscribers" ...or something less clumsy
> 
> :) I do agree. IMHO it should be more "user" facing, like an option in the Earn admin saying "Premium content users and Paid newsletter users have the same rights"... or something less clumsy.
> 
> CCing @crisbusquets for ideas, as Earn is being re-thought...

Thanks for the ping @millerf !

@inaikem:
> I'd love to see a toggle that enables users to selectively "link" payment plans across these two products -> "Make this subscription available to both Paid Content and Paid Newsletter subscribers" ...or something less clumsy. 😉

Right now we have this restriction so that the users can create plans that will only show up here: 

<img width="957" alt="Screenshot 2023-06-28 at 15 50 03" src="https://github.com/Automattic/wp-calypso/assets/25607244/bb752b5e-227f-43df-9fce-140a0e9ed39e">

Does it make sense to allow them to use that same plan, which is intended to be used for a paid newsletter, in other blocks? I feel it can be confusing to allow them to mix and match all of them. Would you to hear your thoughts on this :)

**Comment by romarioraffington** [comment]
> CC: @Automattic/gold & @Automattic/zap
> 
> Should we be able to add Newsletter subscriptions to the Paid Content blocks?

Great question. I can share how the current logic works:

1. When users purchase a newsletter plan, we only give them access to newsletter content ( i.e. newsletter gated posts )
2. When users purchase a plan from a premium content block, we only give them access to the premium content if the plan ID matches what was purchased.

When we allowed newsletter plans to be purchased from the premium content block, this also gave customers access to newsletter content. Should we allow customers to purchase newsletter plans from other blocks, we would have to change how we're gating newsletter posts.

**Comment by carinapilar** [comment]
> It was a deliberate choice to not display newsletter plans in the Premium Content block, as it was more confusing than anything.

IMHO it feels more confusing when we completely remove a feature that customers were used to have, without a way for them to know what happened - that was the case with the user I had. Neither the Paid Content block, nor the payment plans screen, leave that logic clear. 😕

**Comment by cuemarie** [comment]
> When users purchase a newsletter plan, we only give them access to newsletter content ( i.e. newsletter gated posts )
> When users purchase a plan from a premium content block, we only give them access to the premium content if the plan ID matches what was purchased.

I imagine part of the confusion/disconnect with customers might be that some want to use newsletters & premium content more like Levels of Membership (a la patreon), where:

1. "Tier 1" is a $5 / month plan that gets you access to certain premium content, but not all posts
2. "Tier 2" is a $50 / annual plan that gets you access to All posts (newsletters), as well as premium content. 

We haven't really differentiated the Newsletter & Premium Content that much in how we explain them (see https://wordpress.com/support/monetize-your-site/#paid-newsletters ), and since both options are ultimately about granting/gating access to Post content, I can see how the distinction between these 2 different content subscriptions wouldn't feel very obvious or important for a site owner.

**Comment by cuemarie** [comment]
> When we allowed newsletter plans to be purchased from the premium content block, this also gave customers access to newsletter content. Should we allow customers to purchase newsletter plans from other blocks, we would have to change how we're gating newsletter posts.

Thanks for sharing this too! I hadn't thought about the purchase flow and it's implications - imagining being a site owner, I'm thinking about what my users can access, not necessarily where they make the original purchase. It makes sense though that at that block level, users can only set up 1 plan for access, and that's what they purchase right there at the content level (wheras the Newsletter purchase is not block-specific). 🤔 

---

I think if we don't change anything to the current set up, I think we'll need to look over our guide docs and try to help clarify the distinction between Newsletters and Paid Content.  A guide with examples of how to use both separately and together would be awesome, so HEs can point users to something that helps them envision how to use them. 

- _Example: I was thinking of this guide as a possible example: https://wordpress.com/support/tutorials/decision-guide-to-build-a-membership-website/#different-membership-solutions and then I noticed that in this, we actually muddy this very distinction we're discussing 😅:_

> The Premium Content block is ideal for sharing informational content (including text, video, and audio) and can also be configured to be a [members-only newsletter](https://wordpress.com/support/paid-newsletters/). It can be set to receive one-time payments or be subscription-based with recurring monthly or yearly payments.

**Comment by millerf** [comment]
> And can also be configured to be a [members-only newsletter](https://wordpress.com/support/paid-newsletters/). 

Oh. That part was making sense before we started working on Newsletter. This document needs to be updated!

**Comment by millerf** [comment]
CC @donalirl here

**Comment by cuemarie** [comment]
>This document needs to be updated!

Sure! Whipped up a request for that specific part of the docs. ⬆️ 

---

@millerf Given the larger feedback around the separation between paid content & newsletters, do you think that we should try to address the confusion shared with further docs updates, or should we wait for additional discussion/decisions around how the Newsletter and Paid Content plans are allowed to relate before doing anything else?

**Comment by lezama** [comment]
@crisbusquets is thinking and redesigning the Earn pages and flows around plans, I would wait for this before updating or adding more docs.

**Comment by millerf** [comment]
> @millerf Given the larger feedback around the separation between paid content & newsletters, do you think that we should try to address the confusion shared with further docs updates, or should we wait for additional discussion/decisions around how the Newsletter and Paid Content plans are allowed to relate before doing anything else?

Very good question...

> try to address the confusion shared with further docs updates
I thing addressing the issue in the documentation would already be a first step. I don't think discussions would undo that part...

**Comment by cuemarie** [comment]
📌 ACTIONS
- I've updated the title and labeling of this issue to better reflect the discussion we're having, since this it not a bug

**Comment by kuropixel** [comment]
Ran into this on 6504047-zd. Advised to turn off the email option in the subscription plan then they were able to select that subscription from the paid content block.

**Comment by cuemarie** [comment]
It looks like Newsletter Plans can now be selected in Paid Content Blocks, however there's still some sorting out with regard to how that subscription grants access to content; see:

- https://github.com/Automattic/wp-calypso/issues/82433

![Markup on 2023-10-02 at 16:57:32](https://github.com/Automattic/wp-calypso/assets/27249804/b8f71e1b-fffb-4eb0-bdff-fa82361b4bb8)

**Comment by millerf** [comment]
@cuemarie 

> It looks like Newsletter Plans can now be selected in Paid Content Blocks, however there's still some sorting out with regard to how that subscription grants access to content

Yes, this is intentional, and I understand it can be misleading.
"Newsletter" plans merely adds you as an email subscriber, while "regular" plans don't.

So using those "newsletter" plans on a premium content block or pay block grants you access to that premium-content, but also subscribes you to the site newsletters (and also gives you access to paywalled content accordingly.

This gives the creator a lot of flexibility on how to set up their site.

**Comment by cuemarie** [comment]
Thanks @millerf !  I'll close this request as resolved, then!

📌 ACTIONS
- Closed as resolved
