### ISSUE TITLE
Plans 2023: Comparison Grid Alignment Issues

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#78298]
### Quick summary

When the comparison grid pricing header is too long, comparison grid alignment breaks.

<img width="1086" alt="Screenshot 2023-06-15 at 5 45 42 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/0d5c28ba-7394-4fa5-9db2-15819e73b519">

### Steps to reproduce

1. Create a site with a personal _monthly_ plan
2. Visit the /plans page https://wordpress.com/plans/{SITE_SLUG}
3. Scroll down to the plans comparison grid
4. Note the misalignment of grid columns

### What you expected to happen

Comparison grid columns are formatted correctly

### What actually happened

Comparison grid columns are offset

**Comment by jeyip** [comment]
@lucasmendes-design  [The 156px width for comparison grid plan columns](https://github.com/Automattic/martech/issues/1530#issuecomment-1435049868) doesn't accommodate longer header prices. 

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/98343583/219690724-5238f0f0-923b-4836-bfd3-1a22946663dc.png">

In the image below, the width of content for the business plan column `$24.25` pricing header is 165px. To accommodate this, we could decrease font sizing, render the crossed out `$25` pricing on a new line, or something else entirely

<img width="1086" alt="Screenshot 2023-06-15 at 5 45 42 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/0d5c28ba-7394-4fa5-9db2-15819e73b519">

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – not reproduced
Tested on Atomic – reproduced
Replicable outside of Dotcom – not applicable

It appears the issue is not persistently reproducible. My original hypothesis is that this is only reproducible on sites with Business plans, but I was able to make this happen on a Personal site as well.

Tested on both Microsoft Edge and Mozilla Firefox Nightly.

📌 FINDINGS/SCREENSHOTS/VIDEO
All are for user ID 214627768 with Canadian dollar currency.

**Free** 
<img width="1425" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/75f9f519-2550-485a-a015-9470cf8f13b9">

**Personal** 
<img width="1179" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/be13bd3c-a4c9-44e5-973f-20275617695b">

**Premium** 
<img width="1257" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/d1b95275-0764-4e0a-b2d4-1ffdee228537">

**Business** 
<img width="1238" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/5e7d683a-9ec3-4619-a96d-84f189b83676">

**eCommerce** 
<img width="1099" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/2033db96-f223-4b25-88d8-bac170ff7e1f">

📌 ACTIONS
- assign normal priority as @jeyip appears to be working on it.
- remove Needs Triage label.
- add to the dotcom prioritization board.
- add to the MarTech column.

**Comment by lucasmendes-design** [comment]
Thanks for pinging me :) as @worldomonation mentioned let's make sure why this problem happen. However, if we couldn't find an easy way to fix let's remove the crossed-out price. It's already in the notice and in the plans grid above. So, it's clear. Plus, we say that again in the checkout page. 

-------

Unrelated to this PR. 

I don't know where this copy came from `Upgrade to yearly`. It's confusing to have this here. Let's use `upgrade` for all, so the buttons are aligned. 
<img width="552" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/5dcd7884-22e3-4324-82f5-1a244eb87288">


Let's not use `contact support` and change all buttons to the same hierarchy and copy. I don't know why "Contact support" and "Downgrade" have different style (dark gray vs light gray and Bold vs Regular fonts). These buttons should be with the same copy and style. 
<img width="470" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/7caf96d5-5076-4ff3-aa48-f49c71280cdb">

Example
<img width="820" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/6199a977-28b7-4bea-a2bb-aa6bb6a526b0">

Can you open a GH issue for that @jeyip?

**Comment by jeyip** [comment]
> Can you open a GH issue for that @jeyip?

I was on vacation, but got back earlier this week. I'll be sure to write on by EOD today or tomorrow :D

**Comment by jeyip** [comment]
Apologies for the slowness on creating the issue! I've been caught up in high pri work, and this slipped my mind. I'm drafting an issue now

_Edit:_
Drafted the issue https://github.com/Automattic/wp-calypso/issues/79085

**Comment by southp** [comment]
Most of the issues described here are fixed at some points, so I'm closing this in favor of others.
