### ISSUE TITLE
Purchasing domain on Woo Express, ends up on white screen of death on thank you page

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wp-calypso#78378]
### Quick summary

At the final step, (thank you - https://wordpress.com/checkout/thank-you/woo-xxxxxxxxxxxxx.wpcomstaging.com/81332962) the order completes successfully, then there is a flash of content, an error appears, in the console and the page turns white.

The file that is causing the issue is https://wordpress.com/calypso/evergreen/87013.fd58d19601e1b073201b.min.js - I deactivated page optimize, the issue persists

### Steps to reproduce

1. Create a WooCommerce Free trial site
2. Purchase a domain
3. On the thank-you page, there is a flash of content, white page and an error in console
4. The domain purchase finishes successfully, no problem there

### What you expected to happen

On the thank-you page, there shouldn't be any errors

### What actually happened

On the thank-you page, there is a flash of content, white page and an error in console 

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

https://github.com/Automattic/wp-calypso/assets/2484390/4dbadae4-c605-4be6-a73e-a36b1f069b25

**Comment by sirbrillig** [comment]
Thanks to @michaeldcain for helping to reproduce this. The error happens because [this function call](https://github.com/Automattic/wp-calypso/blob/9afe7548373a63ea879fdf9222555d03680666f0/client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx#L38) is inside a `useMemo` which gets its data [from this line](https://github.com/Automattic/wp-calypso/blob/9afe7548373a63ea879fdf9222555d03680666f0/client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx#L22) (why are all those capitalized? They're just regular functions. That's misleading.) which then calls `useSiteOption`. You can't call a React hook inside the callback of `useMemo`.

The bug is happening because [this function](https://github.com/Automattic/wp-calypso/blob/9afe7548373a63ea879fdf9222555d03680666f0/client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx#L16) has been written as a React component (it is capitalized), but it is not actually a component at all, just a function that processes and returns data. Because it was written as a component, our linters allowed it to [call useSiteOption](https://github.com/Automattic/wp-calypso/blob/9afe7548373a63ea879fdf9222555d03680666f0/client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx#L35), but that will not work in a non-component function.

This cause was introduced in https://github.com/Automattic/wp-calypso/pull/56949 which added the poor naming, and then the hooks that broke this page were added in https://github.com/Automattic/wp-calypso/pull/73904.
