### ISSUE TITLE
Patterns: Calypso 'Patterns' page is surfaced in Gutenberg 16.1 and may be confusing.

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#78883]
### Quick summary

With the new Un/Synced Pattern functionality introduced in Gutenberg 16.1 - it is possible to view a list view of a user's custom patterns. In both the page editor and site editor there are links to https://wordpress.com/types/wp_block/ which displays using the default Calypso page list.

<img width="1005" alt="Screenshot 2023-07-03 at 3 33 09 pm" src="https://github.com/Automattic/wp-calypso/assets/1842363/f8907e21-680a-4396-9600-67958a4fa19e">

Two points to note:

* this page doesn't appear to be surfaced within the Admin navigation.
* this list is potentially confusing as it doesn't distinguish between Synced Patterns and UnSynced Patterns.

### Steps to reproduce

1. Test on a site running `gutenberg_edge` or Gutenberg 16.1
2. Open the Site Editor and go to Library
3. Click 'Manage all Custom Patterns' 
4. Confirm the list of patterns in Calypso loads

### What you expected to happen

For more clarity about the list of patterns

### What actually happened

A view that _looks_ like pages or posts - but isn't actually either of those.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by jordesign** [comment]
It looks like there is GB issue to change where those links point:
https://github.com/WordPress/gutenberg/issues/51944

but in the meantime - I don't know if we should worry about the list view.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- On both Simple and AT sites, navigating from `Editor > Library > Manage all Patterns` delivers me to `/wp-admin/edit.php?post_type=wp_block`, not the Calypso version of the page. 
- I am able to load the Calypso version using the URLs in the report above, but so far I can't find a way to arrive there through navigation steps on my sites.

#### Screenshots/Recordings

Simple Edge Site, Theme TT3:

https://github.com/Automattic/wp-calypso/assets/27249804/bdf82185-a23c-4f14-975f-a547c7825fd3

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @jordesign is your concern with either the wp-admin or Calypso post list of `wp_block` posts?  Or specifically the Calypso version?  Are you still delivered to a Calypso list when you take the steps to replicate?
- The issue you mentioned https://github.com/WordPress/gutenberg/issues/51944 does seem to be working on improving the `wp-admin` experience, so that's great.

**Comment by jordesign** [comment]
> On both Simple and AT sites, navigating from Editor > Library > Manage all Patterns delivers me to /wp-admin/edit.php?post_type=wp_block, not the Calypso version of the page.

That's really interesting - I wonder if it is down to the Classic/Calypso view preference set for the test sites? I was able to toggle between the 2 views using the normal 'View' menu.

> @jordesign is your concern with either the wp-admin or Calypso post list of wp_block posts? Or specifically the Calypso version?

Predominantly the Calypso version _if_ users will be able to get to it. But with the incoming changes - if they can only see WP-Admin then I guess it doesn't matter :)

**Comment by cuemarie** [comment]
> I wonder if it is down to the Classic/Calypso view preference set for the test sites? I was able to toggle between the 2 views using the normal 'View' menu.

Surprised I can't replicate this! If I go to `https://wordpress.com/types/wp_block/` by URL, I have the View option, but once I switch to wp-admin, I can't switch back!

https://github.com/Automattic/wp-calypso/assets/27249804/f14b9dfc-6ae2-42fb-a622-2869beb1311c

**Comment by jordesign** [comment]
@cuemarie  ooh - that's a good point - I can't navigate back to the Calypso view either once I've made it there. It was just that _very_ first time.

Given that the plan is for the 'Manage all my patterns' link to go direct to WP-Admin soon - I think this issue can be closed. Thanks for all the additional scrubbing.
