### ISSUE TITLE
Assembler: Discuss defaulting to a header and footer

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#78881]
## Description

Currently, when users land on the Assembler, the large preview shows placeholder content:
![Image](https://user-images.githubusercontent.com/797888/250422884-5fdc1f97-2313-4c65-997a-fbc987c19871.png)

When users select on the header/footer section, the large preview is still empty, and the first non-empty header/footer is focused for the user to select:
![Image](https://user-images.githubusercontent.com/797888/250423097-8c33ad42-27b5-48ee-8945-0ef979b5ceee.png)

This implementation has two issues:

1. A significant portion of the initial user journey is empty content/blank space. When users navigating to any item, they still see empty content.
2. Which leads to users are able to select colors and fonts, even though the large preview is still empty.

Let's discuss improving these two areas. One proposed solution is to select a header/footer to users by default, whether on the initial screen or when they navigate to the header/footer section. Also consider guiding users by telling them how to change the pre-selected header/footer.

See: pbxlJb-45X-p2

## Acceptance Criteria

- [ ] Minimize empty states/blank spaces.
- [x] Users should not be able to select colors and fonts without having patterns selected in the large preview.

**Comment by lucasmendes-design** [comment]
In my prototype, I block users from proceeding to the next step without adding a pattern. So, users must add at least one pattern to proceed. We can also add a tooltip explaining this. 

I think letting users select a completely blank website is not useful. It's challenging to create a site using SA. Just imagine creating from scratch. 

<img width="574" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/06bcf4d8-f859-4d53-85f9-901b4a011356">

> When users select on the header/footer section

We can populate with a header/footer when users select this section. 

> Users should not be able to select colors and fonts without having patterns selected in the large preview.

I also iterated on this a while ago. Here is the latest exploration of this. 

<img width="1122" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/deb8168f-c722-44a1-8576-38fe7ea770e6">

cc: @autumnfjeld

**Comment by autumnfjeld** [comment]
I still don't understand the reasoning of ever blocking color selection.   What does it hurt if a user selects a color without selection a pattern? It might be valuable because it will show up when they view the pattern list.  What is your reasoning that it should be blocked? Just to keep users in a more linear flow?  "Stop and go and do the first thing first!" 😆 

>  It's challenging to create a site using SA. Just imagine creating from scratch.
I agree with the challenging part, but I don't think pre-populating with a header changes anything about the challenge.   It is clear one must populate their blank homepage.    That does't mean I'm against the idea, I just don't think that is the most import thing we need to fix right now.   

It could be that pre-populating with a header a user didn't select is actually more confusing.  

--------------
![image](https://github.com/Automattic/wp-calypso/assets/5665959/f2ead977-0cd6-4d2a-9bcb-e99bce77e3ed)

@lucasmendes-design  This could still be worked on to be clearer, more instructional.

And this new copy will also help:
![image](https://github.com/Automattic/wp-calypso/assets/5665959/014c9560-cc71-4c6a-bd91-acacd83501af)

-------
<img width="1238" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/a83095e9-ec98-4d64-b4ef-bc1973aa38d2">

Should we be  making the copy here more instructional about adding a header "Select from the list below to add a header to your homepage."

We can keep improving here too: 
![image](https://github.com/Automattic/wp-calypso/assets/5665959/a82f9017-8bd4-4f84-8a11-a20d9961ceda)

That needs some English grammer improvement. Sorry @miksansegundo I missed that in our [recent copy review.](https://github.com/Automattic/wp-calypso/pull/78581#top)  @lucasmendes-design and I will get together soon to do another copy review.   Copy never sleeps! 😆

**Comment by taipeicoder** [comment]
> I still don't understand the reasoning of ever blocking color selection. What does it hurt if a user selects a color without selection a pattern? 

To me, the issue is that when users select color/font without having patterns, they go with the intention of experimenting cool and fun styles. When they see that they have to go and select patterns, the momentum is gone.

What if instead of pre-populating a header/footer when users go to header/footer, we pre-select a header, a footer, and some patterns for the user when they go to color/font without having any patterns? We would have a copy saying that we've picked those for them so that they can visualize the changes.

Something like:
![Screenshot 2023-07-06 at 6 15 28 PM](https://github.com/Automattic/wp-calypso/assets/797888/6da6e081-2210-4c79-84a9-61094b777dd8)

**Comment by lucasmendes-design** [comment]
> It could be that pre-populating with a header a user didn't select is actually more confusing.

The idea was we'll pre-populating only if users click on the header. So, when the panel opens, we pre-select with the first header. 

> To me, the issue is that when users select color/font without having patterns, they go with the intention of experimenting cool and fun styles. When they see that they have to go and select patterns, the momentum is gone.

Yes, this is the idea. 

> What does it hurt if a user selects a color without selection a pattern? It might be valuable because it will show up when they view the pattern list.

Users who select colors or fonts don't know that the pattern list will change, they need to go back and open the patterns to see the change. It seems broken to me. They are playing with colors, and nothing happens right away. 

> What if instead of pre-populating a header/footer when users go to header/footer, we pre-select a header, a footer, and some patterns for the user when they go to color/font without having any patterns? We would have a copy saying that we've picked those for them so that they can visualize the changes.

I think having this copy here and pre-populate color + patterns are confusing. It's two actions in one. I think it's not a trivial message to convey.

**Comment by taipeicoder** [comment]
Closing this since:

> 1. A significant portion of the initial user journey is empty content/blank space. When users navigating to any item, they still see empty content.
> 2. Which leads to users are able to select colors and fonts, even though the large preview is still empty.

The second point is already addressed with the new Assembler flow. Let's open a new issue for the first point later, if needed.
