### ISSUE TITLE
Help button overlaps submit button in checkout at small widths

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#79018]
At small widths (eg: on mobile), the floating help button overlaps with the submit button which is not ideal. Here's a screenshot of 320px:

![Image](https://github.com/Automattic/wp-calypso/assets/2036909/1ff5275e-950d-46a6-8a94-67f6ded55a89)

Here's one possible design suggested by @JanaMW27 to resolve this (putting it in the top bar):

![Image](https://github.com/Automattic/wp-calypso/assets/2036909/c66967bc-b145-441f-9e2e-51dce83dbad1)

This is being discussed in Slack here: p1687895996371809-slack-C029S5LLB7D

**Comment by jjchrisdiehl** [comment]
I did a bit of digging and we could pretty easily make the existing _Help_ icon in the masterbar visible on mobile, but, we may need to lose the "Secure Checkout" text since it led to some [overscroll issues](https://github.com/Automattic/wp-calypso/pull/78544) on mobile with so many items crammed into the masterbar. I am not sure how valuable this tagline is for such a small section of horizontal screen real estate.

We may want to consider dropping the tagline down the page, perhaps by Checkout, and take advantage of the vertical screen real estate instead.

Example without the "secure checkout" language:

**Help closed**
![image](https://github.com/Automattic/wp-calypso/assets/16580129/91875f7d-ecaf-4fdd-ae7d-436b0553edc5)


**Help open**
![image](https://github.com/Automattic/wp-calypso/assets/16580129/16f96703-cc4a-4b5d-9127-8e1ce6473032)


@JanaMW27 Thoughts here?

**Comment by JanaMW27** [comment]
I am ok losing the Secure Checkout label, also, I am ok to remove the label Help from the icon as we have it on the desktop.

**Comment by klimeryk** [comment]
When considering the designs for this, let's keep in mind the primary reason why that Zendesk launcher is visible in the first place - to facilitate pre-sales conversations. Users are used to chat buttons being in that area. The default launcher also has the option (that we use, AFAIK) for pro-active nudges, to grab users attention, especially when they are on the fence for some reason.
cc @correliebre as the sales lead on WPCOM for extra input 🙇‍♂️

**Comment by jjchrisdiehl** [comment]
> The default launcher also has the option (that we use, AFAIK) for pro-active nudges, to grab users attention, especially when they are on the fence for some reason.

@klimeryk Can you clarify this part for me a bit more? 

The problem seems to be that we have two call to action buttons competing over the bottom portion of the screen. While the current 'square green' version of the button provides better contrast, the overlap still doesn't feel right.

I suppose we could also hide the launcher button while scrolling down, then have it slide in when scrolling up, this could essentially give the screen real estate to the purchase button when you're scrolling down the checkout page to the checkout button, but then prompt the user to use the help button when scrolling back up to the content of the checkout page.

While hiding a help button doesn't feel great, I think it is preferable to obscuring a checkout button. Thoughts?

**Comment by jjchrisdiehl** [comment]
As an alternative, we could change the bottom padding on the upper content and adjust the position of the launcher FAB, but I am not sure if from an accessibility/UX stand point if moving its position is frowned upon.

 ![image](https://github.com/Automattic/wp-calypso/assets/16580129/b158190e-f4c6-4932-ab00-48dd94b23f48)  ![image](https://github.com/Automattic/wp-calypso/assets/16580129/5902bb92-a969-41f8-8af8-ef5229dda0a1) 

I suppose as long as the FAB is in one place on mobile, and in another on wider viewports, and doesn't change position from within those two contexts then it shouldn't present much of a problem.

**Comment by correliebre** [comment]
Thanks for the ping @klimeryk! 

We definitely need to have the Zendesk presales chat launcher in checkout since the goal is to help anybody who is having doubts about the purchase. If it's the Help Center, then they will need to go through a lot more steps to get support, since the Help Center is built to help people find solutions on their own, and only start chats when it's absolutely necessary. If somebody while on the checkout page has any questions, we do want to be there as quickly as possible to smoothen things out. 

I was talking to @jjchrisdiehl about how this could look like, and I think his alternatives above could solve the issue of having something covering the pay button (which we should never have), and still offering the chat alternative for anybody who may require assistance before finishing up a purchase.

**Comment by JanaMW27** [comment]
Could we bring the chat button on the top nav? Besides the help center?

As you can see in the following mockup both entry points could coexist in the top nav. We could hide the top nav when the user scrolls down and have it visible when the user scrolls up.

<img width="716" alt="Screenshot 2023-07-10 at 08 57 17" src="https://github.com/Automattic/wp-calypso/assets/71137829/dee75feb-ce1a-4487-91cf-fda19d620e53">

With this option, we make sure that the chat has an entry point without covering the Pay CTA or taking up an important real state on the screen.

I could consider changing the format of the icon, and color or background, to make it more prominent.

**Comment by jjchrisdiehl** [comment]
> Could we bring the chat button on the top nav? Besides the help center?

This looks like a fair place to have it, as the bottom FAB placement feels a bit odd on mobile in general.

> I could consider changing the format of the icon, and color or background, to make it more prominent.

~I think this is a good idea as currently the icons seem backwards. I would expect a chat bubble icon to bring up a conversation with support and a '?' icon to open a help center/knowledgebase.~ My mistake, The current help center icon is the "?" so your design looks good! I'll start working on a PR.

**Comment by klimeryk** [comment]
@jjchrisdiehl, do you still any clarification from my side?

**Comment by jjchrisdiehl** [comment]
@klimeryk Do you have any guidance around conditionally showing/hiding the bottom right zendesk launcher? 

~I think your PR [here](https://github.com/Automattic/wp-calypso/pull/77443/files) shows the general idea for showing/hiding, but in this case I'll need to query the viewport size and conditionally show the launcher once the viewport is <480px. I would also need to restrict this to just the checkout screen. It looks like I can use `import { isMobile } from '@automattic/viewport'` to handle this.~

_Should be all set with this  ^._

Are there any specific parameters required for properly routing the chat in Zendesk other than passing in the chatIntent as `Presales`? I can also add on a tracks event for the new button in the mobile view of the checkout masterbar to ensure we're tracking that customers are finding the icon and using it.

**Comment by klimeryk** [comment]
The routing is done based on which Zendesk config was used: https://github.com/Automattic/wp-calypso/blob/747ed70592d867f555341d83ab6a6abad512330b/packages/help-center/src/hooks/use-zendesk-messaging.ts#L12. Which is done automatically by the `chatIntent="PRESALES"` property on `ChatButton` (I forgot I did that myself 😅).

The downside of that is that once you load the widget, it's loaded with that config. So if you start in Checkout, you load presales. But then the user is no longer in Checkout, they open Help Center, start chatting and their chat gets routed like presales. It should be solvable, but we're adjusting our Zendesk Messaging configuration now (pbvpgB-3if-p2), so that's somewhere in the future.

So I would not be too worried about additional Tracks data here. What Happiness Operations is looking at is where the chat is coming from (support or presales), and that's in Zendesk already.

**Comment by klimeryk** [comment]
Make a note here of https://github.com/Automattic/wp-calypso/pull/81784 that hides the pre-sales widget in mobile app.

**Comment by jjchrisdiehl** [comment]
This is now resolved by https://github.com/Automattic/wp-calypso/pull/80724 - closing for now.

**Comment by jjchrisdiehl** [comment]
Reverted in https://github.com/Automattic/wp-calypso/pull/82622

Reopening this issue to track future fixes to avoid the above bug in the ChatButton component going forward.

**Comment by jjchrisdiehl** [comment]
For now this is taking a back-seat to the checkout redesign project. Will revisit shortly.

**Comment by jjchrisdiehl** [comment]
Closing this as we are sticking with a separate strategy to accommodate the bottom aligned support "fab" rather than a masterbar icon - https://github.com/Automattic/wp-calypso/pull/88819
