### ISSUE TITLE
PayPal method doesn't show at checkout if there are credits 

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/wp-calypso#79273]
### Quick summary

In the checkout flow, I noticed that the PayPal option did not appear if I had credits in my account. I was only offered my existing card, add a new card, or add a payment method later. 

This seems to be a consistent issue across all products, including Akismet, Jetpack, WordPress.com 

### Steps to reproduce

1. Add credits to your SA. 
2. Choose any product from a pricing page and go to checkout page. 
3. Check which payment options are offered. 
4. Go back to SA and remove store credits. 
5. Refresh checkout page. 
<img width="1086" alt="Screenshot 2023-07-12 at 11 15 09" src="https://github.com/Automattic/wp-calypso/assets/26651984/85fdf016-f32b-4884-ad65-75f3cc5a5154">

### What you expected to happen

See all payment options offered (including PayPal), whether credits are present or not. 
<img width="1086" alt="Screenshot 2023-07-12 at 11 14 41" src="https://github.com/Automattic/wp-calypso/assets/26651984/a77f8d1b-b12e-4ed2-992b-6b3f08c9bb88">

### What actually happened

With credits, the PayPal option doesn't appear. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Simple and AT. The PayPal payment method was missing when I had free credits on my SA, or when I had a free domain credit to use toward a new domain registration.

#### Screenshots/Recordings

_Example: Simple Site_

With Credits:
![Markup on 2023-07-12 at 15:35:22](https://github.com/Automattic/wp-calypso/assets/27249804/cd89ad05-7e8a-4179-9f9b-e462d1ffdb48)

Without Credits: 
![Markup on 2023-07-12 at 15:34:47](https://github.com/Automattic/wp-calypso/assets/27249804/26b12d8e-2768-4a4d-a183-60ce73f907e1)

📌 ACTIONS
- Assigned to Other
- CC: @Automattic/shilling

**Comment by sirbrillig** [comment]
Having partial credits in your account will not prevent PayPal from being displayed as a payment method option. However, if a purchase is free, we do not currently support PayPal. 

We only recently added support for [using saved cards for free purchases](https://github.com/Automattic/wp-calypso/pull/79029) and [new cards for free purchases](https://github.com/Automattic/wp-calypso/pull/79083). Prior to those changes, the only option for a free purchase was "Free Purchase" (which would read "WordPress.com Credits" if the purchase was free due to credits). That button has been renamed "Assign a Payment Method Later" when other payment methods are available.

**Comment by sirbrillig** [comment]
To be clear, we may add this feature in the future, but right now it's quite difficult for the same reason that we don't support PayPal in the "Add new payment method" page: the way we use a new card for a free purchase right now is by adding a new card not attached to a purchase and then "paying" for it with that "existing" card; we can't do that with a PayPal Express payment agreement.
