### ISSUE TITLE
Plans grid: Unclear 'Contact Support' button under free plan column

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#79285]
### Quick summary

@Automattic/martech-decepticons @lucasm would you be able to take a look?

<img width="1587" alt="Screenshot 2023-07-12 at 12 12 38" src="https://github.com/Automattic/wp-calypso/assets/87168/895e9395-2ef1-4913-ac68-3611b3eeff9d">

### Steps to reproduce

1. Have a site with plan (business in my case)
2. Check plans page
3. See disabled contact button

### What you expected to happen

I don't understand why contact button is here, or why it's disabled.

### What actually happened

I should be able to contact support since I'm on business plan, although I don't know why I'd do so from this Free column.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated! Sites with paid plans all show `Contact Support` under the Free plan column. 

#### Screenshots/Recordings

![Markup on 2023-07-12 at 16:40:32](https://github.com/Automattic/wp-calypso/assets/27249804/4172159f-7641-4d58-890b-c05595667620)

By comparison, lower paid plans show a greyed out `Downgrade` button, which when you hover over it says to Contact support:

![Markup on 2023-07-12 at 16:42:33](https://github.com/Automattic/wp-calypso/assets/27249804/aa3ab466-c962-407a-9c0f-2c66fe5534c7)

📌 ACTIONS
- Assigned to @Automattic/martech

**Comment by southp** [comment]
@simison We have tracked the same issue here: Automattic/martech#1458 and I've bumpted its priority due to an influx of mentions about it recently. Could you help me see if [the proposed solution](https://github.com/Automattic/martech/issues/1458#issuecomment-1598268994) works for you? I'd be grateful :)

**Comment by southp** [comment]
With @ddc22 & @aneeshd16 's collaboration of https://github.com/Automattic/wp-calypso/pull/91925, the CTA now becomes "Downgrade"; clicking on it will lead to the cancellation form. I'm closing this issue since the proposed solution in https://github.com/Automattic/martech/issues/1458 has been completed. If we want to further iterate on the solution, a new issue will be better.

**Comment by niranjan-uma-shankar** [comment]
> On a paid plan site, I am still seeing the "Contact support" button in a disabled state.

The PR [was reverted](https://github.com/Automattic/wp-calypso/pull/92674)
