### ISSUE TITLE
Advanced SEO: Can default state show current theme's title display?

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7930]
If you haven't set a custom title format for a site, the fields are blank. Would we be able to show the format as it is set for the current theme? I'm guessing that might be hard to do but it would be nice.

**Comment by dmsnell** [comment]
@roundhill the site title is easy to pre-fill, but what do you propose we do for post titles and the other categories?

**Comment by drw158** [comment]
I'll copy what @dmsnell in Slack :)

> the only way I can think of to get this information is to make an API call that generates `the_title` or returns `post_title` or what not for the different types of pages

**Comment by drw158** [comment]
Related, I think this could be considered a bug:

![screen shot 2016-09-30 at 10 17 04 am](https://cloud.githubusercontent.com/assets/618551/18996755/2205052c-86f7-11e6-958d-48ac168e1660.png)

It's misleading, because my front page title is not currently `Things I Find Interesting`, but the preview text suggests that it is. We should probably get rid of Preview unless the user has typed something in the field. If we solved the original issue here, then we could show a preview before the user changes anything in the fields.

**Comment by dmsnell** [comment]
No preview is being shown, no deception. Right now it seems to work fine. Closing.
