### ISSUE TITLE
Footnotes Block malfunctions on nested content

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#79384]
### Quick summary

When using the new footnotes block, it does not actually create footnotes consistently (I think this may be when the original block for the footnote is nested).

### Steps to reproduce

_steps updated 2023-07-17 - cuemarie_

1. Create a new post
2. Add nested text content (such as inside a group or column block)
3. Add a footnote to the nested text

### What you expected to happen

Footnote should open as shown in the announcement post: p7DVsv-hNL-p2

### What actually happened

Impossible to add footnote: 

https://github.com/Automattic/wp-calypso/assets/10124024/3ec1626f-aaa1-46ac-9a22-297d2dba0090

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Workaround using page jumps and manually making footnotes as was done prior to this.

**Comment by zachspears** [comment]
Note to add that I tried other pre-defined layouts so it is unlikely this is limited to the Heiwa theme, but I did not have time to test that.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated consistently - the issue here is that footnotes on content nested inside of groups, columns, etc. are not working properly.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/9338003a-356c-47c6-b7dd-8cd4e6f02f89

**Outside of Dotcom**

![Markup on 2023-07-17 at 11:19:44](https://github.com/Automattic/wp-calypso/assets/27249804/76e77c5b-5e39-4a29-8f5b-9ed43dc90839)

📌 ACTIONS
- Assigned to Other
- Added to ‘HE Cross-repo Watchlist’ project board
- Reported here: https://github.com/WordPress/gutenberg/issues/52703

**Comment by cuemarie** [comment]
This will be fixed in WP 6.3 with https://github.com/WordPress/gutenberg/pull/52682

**Comment by cuemarie** [comment]
Tested on an AT site with WP 6.3 and GB 16.4.0, and footnotes work on nested content now. Closing as resolved.

![Markup on 2023-08-22 at 10:54:41](https://github.com/Automattic/wp-calypso/assets/27249804/42f3e0e9-d115-4f8b-886f-30ed222fc3f9)

**Comment by gambuzino-wonder** [comment]
My Current version: 6.7.1 (the latest) and footnotes keep disappearing, randomly. Sometimes they save sometimes they vanish. 😮‍💨

**Comment by gambuzino-wonder** [comment]
### Workaround
It isn't pretty but it works.

1. Make sure you have the settings to see WP custom fields.
2. Scroll down and search the "footnotes" custom field. If you inserted at the post it should be already visible and in use.
3. Insert a footnote into your text, right click at the footnote link ↵ and copy it.
4. Extract the footnote ID from the url: https://yourwebsite.org/wp-admin/post.php?post=21849&action=edit#**009557fc-eef8-4116-bfb7-ccaf257c5b1e**-link. In this e.g. the id will be 009557fc-eef8-4116-bfb7-ccaf257c5b1e.
 ![Image](https://github.com/user-attachments/assets/1b8b8790-28c8-4c31-9f9e-e828b14ad39b)
5. Use this model to inject your footnote content and link:
[{"content":"ContentGoesHere","id":"idGoesHere"}]
E.g.:  [{"content":"Roses are red but also of many colors.","id":"009557fc-eef8-4116-bfb7-ccaf257c5b1e"}]
6. Inject the code at the value of the footnotes custom field (see image).
7. For more that one footnote per post then use this model: [{"content":"1ContentGoesHere","id":"1idGoesHere"},{"content":"2ContentGoesHere","id":"2idGoesHere"}]
8. Save and refresh.

Until WP solves it in a stable way 🤷‍♂️ Tell me if it worked for you,
