### ISSUE TITLE
JITM 'dismiss' cross icon not showing up.

### ISSUE THREAD

**Issue by PZ01** [Automattic/wp-calypso#79602]
I implemented a dismissable JITM in the `jitm-engine` class. Upon viewing it, I did not see any 'X' mark. I inspected the element and did see a cross-hair icon label in the HTML. I suspect something is wrong with the resource URL path.

![image](https://github.com/Automattic/jetpack/assets/6424653/da627858-26a2-450d-8ea3-9d24597fbec1)

I was on a private browsing session.
<img width="842" alt="image" src="https://github.com/Automattic/jetpack/assets/6424653/93c87980-5c56-48bb-9fd6-a872bee4e578">

**Comment by jeherve** [comment]
I'll move this issue to the Calypso repo, since this specific JITM was built in Calypso:
https://github.com/Automattic/wp-calypso/tree/233ac1ad7ed0a8638b095a5aaa9f61f11227ebf7/client/blocks/jitm

**Comment by dpasque** [comment]
Reproduced:
Something is off with the styling for these JITM sidebar banners in Calypso.
This only affects dismissable ones (like certain upsells and domain sale notifications). 
This also is unique to Calypso styles -- if you view in `wp-admin` the styling is just fine!

![Screenshot 2023-07-19 at 9 38 08 AM](https://github.com/Automattic/wp-calypso/assets/26772342/2ee348aa-a23e-4932-8c0b-896057c8799f)

Also worth noting: it's still a button and you can click on it to dismiss it!

I'm going to start this at High priority... This affects basically everyone, and I could see some people getting mad that they can't dismiss these.

**Comment by dpasque** [comment]
Sending to MarTech as this is upsell/JITM related.

**Comment by PZ01** [comment]
> Reproduced: Something is off with the styling for these JITM sidebar banners in Calypso. This only affects dismissable ones (like certain upsells and domain sale notifications). This also is unique to Calypso styles -- if you view in `wp-admin` the styling is just fine!
> 
> ![Screenshot 2023-07-19 at 9 38 08 AM](https://user-images.githubusercontent.com/26772342/254608643-2ee348aa-a23e-4932-8c0b-896057c8799f.png)
> 
> Also worth noting: it's still a button and you can click on it to dismiss it!
> 
> I'm going to start this at High priority... This affects basically everyone, and I could see some people getting mad that they can't dismiss these.

Thanks Dan, and yes indeed someone did get mad before I made it dismissable, which remains case in point that when these are hitting paying customers and they can't remove them, it causes friction.
p1689120996954219/1689120912.481419-slack-C029GN3KD

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closed as resolved thanks to https://github.com/Automattic/growth-foundations/issues/126
- FYI @PZ01 in case I'm wrong about that, please feel free to reopen 👍

**Comment by PZ01** [comment]
👋 That issue had to do with email campaign promotion fixes that were solely on the back-end. 

I just pulled the latest calypso and the icon remains problematic:
<img width="802" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6424653/bc3009aa-a6f1-4023-9c7f-c24929998375">

**Comment by cuemarie** [comment]
@PZ01 Got it - thank you for clearing up my understanding!

**Comment by cuemarie** [comment]
📌 ACTIONS
- After reviewing the timeline on this issue, I've downgraded the priority from `High` to `Normal` to better reflect its status in the larger context of open bugs in this repo.

**Comment by katinthehatsite** [comment]
It seems that the issue is resolved for now  - testing on my end now, I can see the `X` visible on the notices where it is added:

<img width="367" alt="Screenshot 2024-09-05 at 10 39 04 AM" src="https://github.com/user-attachments/assets/ce9019e7-621f-4062-8aa9-828a3b6e3d47">

On some notices, the button is not present at all but it looks like this is done by design:

<img width="1236" alt="Screenshot 2024-09-05 at 10 42 04 AM" src="https://github.com/user-attachments/assets/fbcc9d83-e385-4dba-8dcf-8586636d6f08">

I see that some notices do not have `is-dismissable` prop so they don't have the cross to remove them. The ones that have the prop, display the cross correctly:

<img width="2469" alt="Screenshot 2024-09-05 at 10 53 08 AM" src="https://github.com/user-attachments/assets/8c8e7fc2-81b5-423a-a16c-1389b1771a6c">

Since it can't be reproduced anymore, I will close this issue. Feel free to re-open if the issue happens again!
