### ISSUE TITLE
Domain transfer manage purchase page does not have info on pending status

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#79751]
The Manage Purchase page for a pending domain transfer (before it turns into a Domain Registration) is very bare. It could benefit from some information about the pending transfer and what to do about it (ie: wait).

See https://github.com/Automattic/dotcom-forge/issues/2941#issuecomment-1644666902 for more details.

**Comment by sirbrillig** [comment]
From planning: we could certainly get some design feedback on this screen but in the meantime I think it's valuable to just update the page to read something like "The domain transfer is in progress. Please visit this page again in 5-7 business days to see its status."

@JessBoctor  is going to figure out some good text to display and @spraveenitpro  will try to put together a PR to show it on the page. We can then run it by the Google Domains migration team to see how they feel about it.

**Comment by JessBoctor** [comment]
I was looking at our domain transfer documentation. It looks like the `Upgrades > Domains ` or the [All my domains](https://wordpress.com/domains/manage) pages have some custom messaging based on the status of the transfer. 

From our support documentation:

![waiting](https://en-support.files.wordpress.com/2022/12/domain-transfer-waiting.png)

![in-progress](https://en-support.files.wordpress.com/2022/12/domain-transfer-in-progress.png)

![failed](https://en-support.files.wordpress.com/2022/12/domain-transfer-failed.png)

From my test account: 

![screencapture-wordpress-domains-manage-2023-07-28-10_10_37](https://github.com/Automattic/wp-calypso/assets/12505355/511339a7-5585-4c2c-976f-71149c700897)

I think it would be best to re-iterate that here. Since we have more room, we can include some [additional information](https://wordpress.com/support/domains/incoming-domain-transfer/#step-4-check-your-transfer-status) for each status from the support documentation.

No matter what, I think the most important things to highlight would be:
- Transfer's current status
- How to cancel if they want to bail
- How long it should take (generally 5 -7 business days)
- Where to get help if 

@spraveenitpro Let me know if you need something more specific.

**Comment by spraveenitpro** [comment]
@sirbrillig  Here is the update:

1.  I have tracked down the dynamic messaging logic to [here](https://github.com/Automattic/wp-calypso/blob/bbe439b7a0a5453d973d948e354b938708e9a156/client/lib/domains/resolve-domain-status.tsx#L585). `import { resolveDomainStatus } from 'calypso/lib/domains';`
2. The above logic needs to be imported and called from the `manage purchases` section [here](https://github.com/Automattic/wp-calypso/blob/bbe439b7a0a5453d973d948e354b938708e9a156/client/me/purchases/manage-purchase/index.tsx#L973)
3. I am currently bring in the logic and testing various methods, I will update here as soon as it is completed.
