### ISSUE TITLE
Jetpack: Unable to enable automatic plugin update

### ISSUE THREAD

**Issue by hajekj** [Automattic/wp-calypso#7976]
#### Steps to reproduce
1. Create a self-hosted WordPress powered-blog with default configuration
2. Install Jetpack and connect it to WordPress.com and enable default settings
3. Go to https://wordpress.com/plugins/site-name and try to enable automatic updates of plugins

#### What I expected
The automatic update button to show.

#### What happened instead
Was presented with following error:
*Autoupdates are not available for Site Name. The file permissions on this host prevent editing files.*

#### Browser / OS version
Independent of browser and OS, Windows 10 Anniversary Update, Microsoft Edge

#### Screenshot / Video
N/A

#### Context / Source
With the default installation of WordPress, `WP_AUTO_UPDATE_CORE` is set to `false` which results in the site settings contain:
```
“file_mod_disabled”: [
    “wp_auto_update_core_disabled”
]
```
which results to having automatic plugin updates disabled even if there is no actual blocker for that. Adding `define( 'WP_AUTO_UPDATE_CORE', true );` into `wp-config.php` resolves the issue.

This is generally caused by poor attribute checking at [client/my-sites/plugins/plugin-install-button/index.jsx#L69](https://github.com/Automattic/wp-calypso/blob/3712e77187e7b5796e54d01673917baf672f2658/client/my-sites/plugins/plugin-install-button/index.jsx#L69) and [client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx#L77](https://github.com/Automattic/wp-calypso/blob/3712e77187e7b5796e54d01673917baf672f2658/client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx#L77). It could also be solved within Jetpack itself or both ways, depending how the teams can agree.

#manual-testing #user-report

Related Jetpack e-mail support ticket: #2820869

**Comment by johnHackworth** [comment]
Thank you a lot for reporting this and taking all this time to investigate the issue! This is a wonderfully documented issue, I must say.

I have been taking a look and it's not so easy to reproduce. If I follow the steps (install a new WordPress from scratch, add jetpack, try to enable autoupdate plugins from WordPress.com) everything seems to work ok. 

I took a look at the code to see if I was missing something, and as you say, both checks seem to be too weak, especially when the default wp-config of a jetpack site would make them go to the error condition within the `if`. But taking a closer look, that error condition depend first on `this.props.selectedSite.canUpdateFiles` being false.  

If you take a look at the method that calculate that property (https://github.com/Automattic/wp-calypso/blob/3712e77187e7b5796e54d01673917baf672f2658/client/lib/site/utils.js#L95 ), it only returns 'false' if certain conditions are met ( old jetpack version, is a subsite in a multisite network , etc). The only check that deals with `file_mod_disabled` just fails if `disallow_file_mods` or `has_no_file_system_write_access` are present. So in a regular site with a modern jetpack version, `canUpdateFiles` will only be false in case one of those errors are present within  `file_mod_disabled`.

Without any of those errors there, it shouldn't matter that there are any other contents in `file_mod_disabled`, because that checks in those ifs can't be true and that code won't be executed. Would it be possible that your site is also under one of those conditions ( `disallow_file_mods` or `has_no_file_system_write_access` ), so that's why autoupdates are shown disabled?

Probably this part of the code could be written in a more clear way, to be honest.

**Comment by hajekj** [comment]
I checked and my site didn't report any of `file_mod_disabled` or `has_no_file_system_write_access`. After couple of e-mails with Jetpack's support on ticket #2820869, they said that the engineer did something to prevent this from happening, so they could've modified the Jetpack plugin itself or something on the backend. If possible, it would be better to reach out to them and see what exactly they did to fix the issue (because it seems to work correctly now).

**Comment by johnHackworth** [comment]
Oh, I see! I'll talk with the jetpack team to see what was going on.

Anyway, thank you a lot for taking so much time with this! :)
