### ISSUE TITLE
Link in Bio flow: Progress bar is overlapping into content area

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#79824]
### Quick summary

In link-in-bio signup flow, the progress bar is misaligned. 

### Steps to reproduce

1. Visit w.link while logged out.
2. Click on the main CTA to enter [this signup flow](https://wordpress.com/setup/link-in-bio-tld/domains?new=).
3. Notice the misaligned progress bar on the registration step.
4. Complete registration and notice the progress bar again on the next step.

### What you expected to happen

The progress bar to be aligned correctly

### What actually happened

<img width="1335" alt="Screenshot 2023-07-25 at 1 29 25 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/368bfb4f-4a8d-4bc2-ab97-79aedd275660">
<img width="1248" alt="Screenshot 2023-07-25 at 1 31 22 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/1fb760e4-53a8-47ab-880f-f4250503ac40">

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described - the most noticeable page with the issue is `/setup/link-in-bio-tld/linkInBioSetup`

#### Screenshots/Recordings

![Markup on 2023-07-25 at 09:01:42](https://github.com/Automattic/wp-calypso/assets/27249804/0454bbd7-a5bc-4acc-a395-d2b2ecdfad12)

📌 ACTIONS
- Assigned to @Automattic/lego

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/80177
