### ISSUE TITLE
Image Editor: 'Save' instead of 'Done'?

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7984]
Just a thought about the `Done` button that you click when you have finished editing an image. I wonder if `Save` might be more appropriate since you are changing/modifying an image?

Referring to the lower-right button here:

<img width="1058" alt="screen shot 2016-09-08 at 3 54 18 pm" src="https://cloud.githubusercontent.com/assets/789137/18369803/cb5be3b0-75dc-11e6-8241-1fe879778cbe.png">

**Comment by retrofox** [comment]
In fact I'd like suggest `Create` as another option because that's what the user is doing: creating a new image.

cc @adambbecker @folletto

**Comment by folletto** [comment]
I agree. "Done" is too neutral. Given the fact it's actually creating a new one, a better wording is necessary.

Both `Save` and `Create` work, but I'd suggest one that is also an accepted standard, at least on OSX and some cross-platform softwares: `Save copy`.

**Comment by drw158** [comment]
I think there was a reason for this, but it's been a few months... these suggestion don't work currently, because the user can click Reset (resets changes and doesn't close window). Once the user clicks Reset, "Save" wouldn't make sense because there were no changes. Done is nice because it means both "close without changes" and  "save changes".

Option:

- Remove the Cancel button altogether and make the Done button dynamic. If there are no changes, the blue button is "Cancel". If there are changes, then it becomes Save or Save Copy. I don't like this option because "Cancel" makes it seem like there were changes and now you are discarding them.

Also, this was design before file management was considered. I hoped that it wouldn't save a copy and it would just be one image like in Google Photos and iOS.

**Comment by folletto** [comment]
> this was design before file management was considered

Yeah, this is understandable. I think a Photos/iOS management style would require (as I think both do) an undo system built-in somewhere: the image is still there, just doesn't show up, and you can "undo" the changes.

> Done is nice because it means both "close without changes" and "save changes".

This seems the issue then.

> Remove the Cancel button altogether and make the Done button dynamic. If there are no changes, the blue button is "Cancel". If there are changes, then it becomes Save or Save Copy. I don't like this option because "Cancel" makes it seem like there were changes and now you are discarding them.

I'm not sure I understand why. To me it's just a matter of having both "Reset" and "Save copy" to be disabled if there are no changes, while "Cancel" is always active. No?

**Comment by drw158** [comment]
> To me it's just a matter of having both "Reset" and "Save copy" to be disabled if there are no changes, while "Cancel" is always active.

That'd work, but I liked having the clear blue primary action there not disabled at all times.

After discussing image versioning (not really possible) on Slack, I think this will be fine for now:

- If edits are not present: `Cancel` `Reset`(disabled) `Save Copy`(disabled)
- If edits are present: `Cancel` `Reset` `Save Copy`

Because Cancel is now being moved to the right, i think it will need to become red if changes are made.

Thanks for the help, @folletto

**Comment by gwwar** [comment]
@iamtakashi what do you think about this one? Note that we have 3 usages of the image editor so far:
- Cropping images for Site Avatars (creates a new copy if it has changes)
- Cropping images for Gravatar ( not saved to media, but uploaded to gravatar )
- Editing (not copying) images in the media modal

We may want to have a neutral default here with the option of overriding the primary action text.

**Comment by drw158** [comment]
"Done" could be a nice default. 

I don't think it's necessary to know that it's saving a new copy if changing the Site Avatar. "Save" might be just fine.

**Comment by iamtakashi** [comment]
> I don't think it's necessary to know that it's saving a new copy if changing the Site Avatar. "Save" might be just fine.

I like "Save" because it's simple, but "Save Copy" is reassuring that the original stays safe in the library after cropping.

**Comment by v18** [comment]
> We may want to have a neutral default here with the option of overriding the primary action text.

FWIW, there is now a way to alter the text as needed for different uses of the `ImageEditor` component, by using the `doneButtonText` prop.
