### ISSUE TITLE
Atomic: Incorrect hour picker on Site Logs 

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#79923]
### Quick summary

The hour picker on Tools > Site Logs does not reflect the selected hour. It appears the picker shows time in the site's timezone but adds to the field in UTC which is confusing.

### Steps to reproduce

1. Make sure the test site setting is not in UTC 0:00 timezone
2. On the AT site, go to Tools > Site Logs.
3. Click on the calendar icon and select the hour.
4. You will notice that the hour entered in the field is not what you selected.

### What you expected to happen

The hour selected in the picker should be added to the input.

### What actually happened

Screen recording: 

https://github.com/Automattic/wp-calypso/assets/33957570/c12bb57e-5567-49d5-9745-508eb08a0e39

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

User interaction: 6584158-zd-woothemes

**Comment by hideandgeek404** [comment]
Having tested this earlier, I just wanted to pass comment and clarify that it's actually the reverse of the above. The hour in the drop down is shown in my own time but once selected the hour is that of the same time but according to the site location.

i.e. I am in UTC+1 (British Summer Time) currently. The site we tested on was set to UTC-4. When I open the dropdown I am presented with all the hours. If I click 10, the hour selected in the field is then converted to 5 hours ago (05). This is because the datepicker is using my local time (presumably that of the browser) and the time is then converted to that of the site. This is actually really only an issue for those users who are accessing their site from a timezone different to that of the site.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- In my test, I don't have a time selector as shown in the recording above - only a date picker pops up when I click the calendar icon. That said, keying in a time also shows the issue - what I type in is converted immediately in the search field.
- Recorded with an onscreen keyboard to help visualize:

#### Screenshots/Recordings

![Markup on 2023-07-27 at 10:44:12](https://github.com/Automattic/wp-calypso/assets/27249804/f112aa5e-ec33-4fb0-a260-7b4ed50e8485)

https://github.com/Automattic/wp-calypso/assets/27249804/2023aa20-18f1-4d25-a247-756e1d6fb4eb

📌 ACTIONS
- Assigned to @Automattic/quake
