### ISSUE TITLE
Reader: Posts are not displayed after subscribing to a feed

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#79925]
### Quick summary

I subscribed to Forte Labs RSS feed through WordPress.com Reader, but I can't see any posts. The list even shows the wrong site.

**NOTE:** I was only able to replicate it for that specific feed. 

### Steps to reproduce

1. Start `https://wordpress.com/read/search`
2. Search `Forte Labs` or type `https://fortelabs.com/feed/` (I also tried `fortelabs.com/feed`)
3. Click the "Follow fortelabs.com/feed/" link to subscribe.
4. From the list of subscribed sites, click on Forte Labs. 

### What you expected to happen

I expect a list of posts will be displayed. 

### What actually happened

Clicking on the site shows "No recent posts". 

![ndfLVA.png](https://github.com/Automattic/wp-calypso/assets/67279475/73335eae-70a5-4374-a6ef-27b92ee22b90)

Looking at the list of my subscribed sites, I also see that the attached domain is incorrect. 

![qa8BO7.png](https://github.com/Automattic/wp-calypso/assets/67279475/a12468bd-0d98-4445-b43c-78f038ba3ae0)

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

I tried the same RSS URL in another app, and it showed the latest posts.

![eFUhx2.gif](https://github.com/Automattic/wp-calypso/assets/67279475/72899b01-2a76-4ba2-ba86-ede20b1bcbe4)

cc: @Automattic/loop

**Comment by davemart-in** [comment]
Thanks for the report! I've added it to our bugs board. Just noting that this looks similar in nature to https://github.com/Automattic/wp-calypso/issues/78757 cc @roo2

**Comment by roo2** [comment]
hmm this case is similar to https://github.com/Automattic/wp-calypso/issues/78757 but not exactly the same
In https://github.com/Automattic/wp-calypso/issues/78757, there were two different blogs that had used the same domain.
They each had a feedbag entry, and the old entry was returned by default.
The fix was to use our migration tool

Here, we have feedbag entries for two different domains pointing to the same blog (141161858).
 There is an old domain (no longer functioning) `http://praxisblog.co` which is also attached to the same blog (141161858).

I see that we have a php script that can merge the too feeds, so I might just run that for this blog.

But I suspect that if this happened with this one blog, maybe this will happen every time a user transfers to a new domain for the same blog.

I'll keep investigating.

**Comment by roo2** [comment]
Sorry, I finally got back to this, I was able to fix this iste with a CLI tool. PCYsg-1C4-p2, there were duplicate feeds as explained in previous comment, but I didn't work out how that happened. After merging the feeds, I was able to subscribe and see the posts as expected.
