### ISSUE TITLE
Desktop App: 32bit Windows app crashes with "keytar.node is not a valid Win32 application".

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#80092]
### Quick summary

User reports the app crashes and they get an error.

Ticket: 6516883-zd-woothemes
Slack: p1690626327588859-slack-C08GLCXMZ

### Steps to reproduce

1. On a Windows device (user's appear to be 32bit) open the WordPress.com app version 8.0.0 or 8.0.1
2. Notice an error appears and the app crashes
 
![image](https://github.com/Automattic/wp-calypso/assets/2540430/72771ee5-fb02-420e-99ac-cd36afed77db)

### What you expected to happen

The app to open and work as usual. 

### What actually happened

It crashed.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

The user has been using version 7.2.0.

**Comment by worldomonation** [comment]
Summarizing the results of what I've found out so far, after about 6 hours.

## Issue
When Windows binaries are built, only the 64-bit binary for `[keytar](https://github.com/atom/node-keytar)` module is packaged into the resulting Electron app.

This is evident from the error message:

```
keytar.node is not a valid Win32 application.
```
![image](https://github.com/Automattic/wp-calypso/assets/6549265/6197415a-495e-4271-9e07-1a308b7c92f3)

## Investigation & Attempts at fixing
I've investigated the following avenues.

**Replace the Keytar module**
This is easy in theory, and also good practice - `keytar` has been end-of-lifed as of December 2022.
There is a newer, built-in tool called Electron SafeStorage which comes pre-packaged with Electron itself.
However, because 1) I have not worked with this level of system integration in the past, and 2) There is no guarantee that this change will fix the issue, and 3) This solution may be quite convoluted and require a lot of time to implement. 

As a result, I do not plan to pursue this route. 

**Install 32-bit dependencies for electron-builder**
See: https://stackoverflow.com/a/68553001

This seems to be the easiest way forward, and the first avenue I explored.

However, the process begins and then hangs immediately after:

```
circleci@packer-64b08804-da81-0464-407f-40ab47a7a8fb  /c/Users/circleci/wp-calypso (desktop/windows-8.0.0-keytar)
$ npx electron-builder install-app-deps --platform=win32 --arch=ia32
  • electron-builder  version=23.0.3
  • rebuilding native dependencies  dependencies=dtrace-provider@0.8.8 platform=win32 arch=ia32
```

**Setting NPM to prefer 32-bit binaries**
See: https://stackoverflow.com/a/62022819

This instructs NPM to use 32-bit binaries for dependencies.
This seems to not present any issues, at least for this step.

## Current status
As of August 2, 2023 the issue has been: How to get CircleCI to output a 32-bit binary to test this out?

I'm also coming up on at least a half working day's worth of effort. At the prevailing cost of software engineering, the time I've spent so far already outstrips any benefit we will see from getting 32-bit Windows build working. I will consult with my lead for further instructions but further work is not guaranteed.

Part of the calculus here is that 32-bit OS has not been the mainstream for about a decade now. Take a look at the [PassMark](https://www.pcbenchmarks.net/os-marketshare.html) hardware survey, which does not even list _any_ Windows 32-bit OS as having even a single percentage of market share:

![image](https://github.com/Automattic/wp-calypso/assets/6549265/1d1d7b86-a2b3-49a7-b9b9-483b10c0387d)

[Steam Hardware Survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) also, predictably, shows almost entirely 64-bit with the sole exception of Windows 7 32-bit at 0.1%.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/a20c7016-bbaa-4819-bf02-6d2af19fbdf8)

**Comment by worldomonation** [comment]
**Update 2023/08/04**

A few things were discovered:
- Windows does not have a built-in way to check or the bit-ness of a binary in question. That said, it is possible to run the software and check Task Manager. 64-bit software will only show the name of the process, but 32-bit software will show `(32)` beside the process name.
- one of the avenues explored, **Setting NPM to prefer 32-bit binaries** was not successful.

**Setting NPM to prefer 32-bit binaries**

After making changes to the configuration, then building it on the CircleCI machine and then exfiltrating the binary to my local machine via SCP __and then__ transferring it to my Windows machine, I was met with the exact same error upon launching the app.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/6257144b-003b-438f-ba75-c246040f749c)

This proves that installing 32-bit dependency using NPM isn't workable.

**Update Keytar to the newest available version before it was deprecated**

Keytar is currently at v7.9.0, but we are on v7.7.0. 

Binaries produced with this was unusable, with the same issue as above.

**Possible solution - Replace the Keytar module**

I went down this path after exhausting other options. 

[Someone else had replaced keytar with an alternative in the past](https://freek.dev/2103-replacing-keytar-with-electrons-safestorage-in-ray), and I referenced this work heavily. The new solution uses `electron`'s built-in `safeStorage` method and a new dependency called `electron-store`.

The work is done in https://github.com/Automattic/wp-calypso/pull/80077 and the resulting binary runs as expected on macOS x64/arm64, Windows 64/32-bit. Linux is not tested due to not having a Linux machine.
