### ISSUE TITLE
Update endpoint: make a limit on Trial plan creation to only one website per user

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#80173]

**Comment by jeroenpf** [comment]
Question: is this one _active_ trial plan at any given time or one trial plan in the history of the user account?

**Comment by vishnugopal** [comment]
One trial plan in the history of the user account seems good. Let's make sure to ignore a8c users when making this change.

Let's also make a MC sticker so that HEs can at their discretion enable multiple trials.

What error do we communicate in the UI? Something like `You had subscribed to a trial plan in the past, and cannot activate a new trial.` seems good.

**Comment by ouikhuan** [comment]
Implemented checking the migration trial in history and block it if a user has ever had a business trial plan. More details see: D118285-code

**Comment by ouikhuan** [comment]
Feature config and check implemented here: D118335-code
