### ISSUE TITLE
Calypso banner targeting specifically Google domains owners

### ISSUE THREAD

**Issue by JanaMW27** [Automattic/wp-calypso#80255]
p1690988318599129/1690940012.537719-slack-C05CT832K2T

**Comment by JanaMW27** [comment]
p1690988318599129/1690940012.537719-slack-C05CT832K2T

**Comment by ebinnion** [comment]
Design is here and I believe Explorers is picking this up. Assigning to @DustyReagan for now.

**Comment by ebinnion** [comment]
There is some data that may be interesting for this promotion in this post:

p58i-f9r-p2

**Comment by lsl** [comment]
A simple query would be the best way to do that if possible, otherwise there is also this function we use for determining which domain transfers get the $0 transfer or not:

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sqbznvaf%2Sjcpbz%2Qqbznva.cuc%3Se%3Q3034prns%231451%2Q1503-og

It's a little slow so the banner would need to be async, I guess if we do this with a JITM it already deals with the async loading for us.

**Comment by lsl** [comment]
> There is some data that may be interesting for this promotion in this post: p58i-f9r-p2

Just noting the tumblr list excludes users we can't email via `is_marketable = 1` p1691134510567989/1691095145.948899-slack-CR1U5CLD9, we might want to get a fresh list for banner ads, though I'm not sure there is going to be enough overlap with dotcom that it matters unless we're also showing a banner on tumblr, should we be trying to find out how to do that as well?

**Comment by ebinnion** [comment]
I'm not sure that we'd include the Tumblr users for this promotion, since it's on Dotcom. But, we could probably minimize the promotion to only show to users with email addresses that have domains that have Google MX records or that have domains that are registered at Google.

**Comment by DustyReagan** [comment]
We could accomplish this similarly to how we did the churn retention project.

1. Create an async-job that updates a custom `user_attribute`. Could be called `google_domain_owner`. Maybe we just run it once or as needed, rather than scheduled recurring. (example D94175-code)
2. In the JITM use `->with_user_attribute( 'google_domain_owner', '1' )` (example D97010-code)
3. Profit

**Comment by candy02058912** [comment]
Updated `is_google_domain_owner` attribute to 280,065 users, script used is here: D119530-code

**Comment by lsl** [comment]
Closing, we've got other issues for the remaining banners.
