### ISSUE TITLE
Classic block: Image resize not showing changes in editor, but works on live site

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#80347]
### Quick summary

On simple sites, the option to resize an image in a Classic block by dragging it does not work. This seems to happen when using a Classic theme. 

### Steps to reproduce

1. On a simple site with a Classic theme, add a Classic block to a post. 
2. Add an image within the block
3. Drag to resize 

### What you expected to happen

The image to resize 

### What actually happened

The image goes back to its original shape. The user in 6637554-zen says this started happening about two days ago. 

https://github.com/Automattic/wp-calypso/assets/74204272/c848ec56-41a0-4328-92db-1e409d9a095d

There are a few workarounds, including:

1. Convert Classic block to Blocks and then resize the image.
2. Issue does not seem to happen on FSE themes

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I could not replicate it on an Atomic site.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm able to replicate this on my simple site.  Notable - the image does resize on the live site - so the issue here is that the editor doesn't show the resized image. 
     - I also saw this issue on this post using theme TT3 - the pop-up classic block editor showed the resized image, then the block editor did not, but the live site did. 
- Atomic site did not replicate the issue, as OP mentioned.

Simple Site Test Environment:

- WP 6.3
- Gutenberg: v16.3.0
- Editing Toolkit: 3.74607
- WP AMP: 2.0.5
- CoBlocks: 2.18.1-simple-rev.4

Atomic Site Test Environment

- WP 6.3
- Gutenberg: v16.3.0
- Editing Toolkit: 3.74607

#### Screenshots/Recordings

**Simple Site, Twenty Twenty-One (Classic)**

https://github.com/Automattic/wp-calypso/assets/27249804/723b4e0e-8c27-4b56-8215-579690ce896c

**Simple Site, Twenty Twenty-Three (FSE)**

https://github.com/Automattic/wp-calypso/assets/27249804/d11641d2-1f3e-4160-a30e-dab7ebee2361

📌 ACTIONS
- Assigned to Non-Urgent

**Comment by msilbers** [comment]
reported in #6647183-zen
the site is using Quadra, but having the same issue on the gallery page, with the Classic Block

**Comment by supernovia** [comment]
We have a bunch of users running into this problem. I'll note each one, but for now, here's what I'm seeing in Exmoor, which is not a classic theme.

Also, is this modal just a thing now? It's not happening on my .org instance. It makes it hard to see what I'm working with because the window is so small.

https://github.com/Automattic/wp-calypso/assets/3476361/8678d53e-d2ca-4430-bc9d-20f4d4011e68

**Comment by supernovia** [comment]
We have a report in the forums, and several "me toos" on the thread. Here's the OP:
https://wordpress.com/forums/topic/now-unable-to-resize-images-in-the-classic-editor/

**Comment by supernovia** [comment]
Another user complaint:
https://wordpress.com/forums/topic/now-unable-to-resize-images-in-the-classic-editor/?view=all#post-3978177

**Comment by supernovia** [comment]
Another complaint:
https://wordpress.com/forums/topic/now-unable-to-resize-images-in-the-classic-editor/?view=all#post-3978322

**Comment by supernovia** [comment]
Another user complaining:
https://wordpress.com/forums/topic/now-unable-to-resize-images-in-the-classic-editor/?view=all#post-3978800

**Comment by supernovia** [comment]
Another user with the same issue:
https://wordpress.com/forums/topic/now-unable-to-resize-images-in-the-classic-editor/?view=all#post-3979118

**Comment by supernovia** [comment]
Another user here:
https://wordpress.com/forums/topic/now-unable-to-resize-images-in-the-classic-editor/page/2/?view=all#post-3979648

**Comment by essleeung** [comment]
Another case here: 6650955-zd-a8c

**Comment by aleone89** [comment]
Another report of this here in social: https://twitter.com/TheUntranslated/status/1689939378066345984

**Comment by aleone89** [comment]
Another report here: https://wordpress.com/forums/topic/displayed-page-is-different-than-edit-page/?view=all

**Comment by cuemarie** [comment]
Upgraded priority to `Normal` and escalated here: p1692038059050479-slack-C01LXBU1N21 , given this is impacting more users.

**Comment by cuemarie** [comment]
📌 UPDATES
- Tested on Atomic – **Replicated** - _this is new from last week, when I could not replicate on Atomic_
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO

**ATOMIC**
- I'm now able to replicate this on an Atomic site with TT3 installed. Behavior matches the behavior noted above - the classic block pop-up modal shows the resized images, as does the live site, but the block editor does not show any changes to the image size. 

https://github.com/Automattic/wp-calypso/assets/27249804/64160190-d64b-479e-aaaa-b79fac68e267

- WP 6.3
- Gutenberg Version 16.3.0
- Deactivated all non-must-use plugins other than Gutenberg, and issue still presented

**OUTSIDE OF DOTCOM**
- **Could not reproduce** on a JN site (outside of Dotcom). 
- No matter the theme or GB version (tested 16.4, 16.3, and inactive), the classic block pop-up modal showed image resizes correctly in the editor and on the live site.

https://github.com/Automattic/wp-calypso/assets/27249804/e201e3c2-e33b-4260-b6ec-1345a56d8452

- WP 6.3
- Gutenberg Versions: 16.4.0, 16.3.0, and inactive

**Comment by supernovia** [comment]
> I am still having issues with this, is everyone else as well?

- [in the forums](https://wordpress.com/forums/topic/now-unable-to-resize-images-in-the-classic-editor/page/2/?view=all#post-3981353)
