### ISSUE TITLE
Theme Curation: LOTS & LITS Categories Design follow up

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/wp-calypso#80360]
There is room for some visual improvements:
- Ideally, the pricing dropdown and the collapsible categories dropdown should be visually consistent. There are some differences right now (color, border radius)
- The text weight of the pricing dropdown is also much wider than the text weight of the search input. They should be the same.
- In the LOTS, it's weird that the dropdown uses a pink color scheme since everything else (except the Site Assembler CTA) is blue. It should probably use a blue color scheme (and the SA CTA too).
- In the LOTS, I think there is too much separation between the search input and the pricing dropdown:

<img width="870" alt="Screenshot 2023-08-09 at 11 20 42" src="https://github.com/Automattic/wp-calypso/assets/1233880/8d878410-7bb2-4522-82b7-715371955083">

Originally posted by @mmtr in https://github.com/Automattic/wp-calypso/pull/80313#pullrequestreview-1567381099

**Comment by Copons** [comment]
Some suggestions:

### LOTS

The gap between search input and pricing dropdown is caused by a `max-width: 450px` on
`.is-logged-out .search-themes-card`. Just removing that should fix the issue without regressions.

There's a bit of a jump between `break-large` (960px) and `break-small` (600px).
Wonder if we could add a `break-medium` (782px) with an intermediate `.theme__search` width (e.g. 65%). 🤔 

### LITS and LOTS

I'm not sure the dropdown needs to be so large. 🤔
I think it would look better (especially on LOTS where the searchbar doesn't take the whole horizontal space) if the dropdown were only as wide as needed.

Example:

```diff
 .theme__search-input {
-  flex: 1;
   width: 100%;
   padding: 0 0 10px 0;
   @include break-mobile {
-     flex: 2;
      padding: 0 10px 0 0;
   }
 }
 
 .section-nav-tabs__dropdown {
-  flex: 1;
+  flex-shrink: 0;
   width: 100%;
+  @include break-mobile {
+     width: auto;
+  }
 }
```

### LITS

The dropdown should go on a newline on mobile screens, like in the LOTS.

### Needs Fixing

With D118131-code applied, I see all the `&` encoded as `&amp;`.

**Comment by rcrdortiz** [comment]
> LITS
> The dropdown should go on a newline on mobile screens, like in the LOTS.

The dropdown does go on a newline on moblie screen just like in the LOTS, I think I'm not understanding what you mean.
![Captura de Pantalla 2023-08-09 a las 13 16 40](https://github.com/Automattic/wp-calypso/assets/1989914/e5d3c616-f9d4-4a99-9477-2978d1097754)


> Needs Fixing
> With D118131-code applied, I see all the & encoded as &amp;.

It needs a merge with trunk since the code that decodes the entities isn't in that branch. You can manually change the categories in trunk and you'll see the categories displayed correctly.

**Comment by rcrdortiz** [comment]
Changes have been deployed.
