### ISSUE TITLE
Comment Notifications: Inconsistent or broken firing of email notifications

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#80407]
### Quick summary

@bryanvillarin reported in p1691260635356439-slack-C025Q5RK2 that he was not receiving email notifications when getting comments even though his subscription settings indicate that he should. He did receive notifications via the bell.

### Steps to reproduce

See Slack thread.

### What you expected to happen

To receive notifications via email and bell.

### What actually happened

Only received notifications via bell.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by ebinnion** [comment]
@yansern - Can someone from Apex dig into this?

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on P2 – Inconsistent

📌 FINDINGS/SCREENSHOTS/VIDEO
I had inconsistent test results while trying to replicate this. 


<details>
  <summary>Test Site notes:</summary>

**TEST ONE** - A8C P2 Comment Thread: pciE2j-1TW-p2#comment-1638
- This is a P2 I follow, but I have emails notifcations for new comments disabled.  I do have Replies to my comments on other blogs enabled, under `/me/account/notifications/`
    - Dan replied to my first comment at `2023-08-10 17:05 UTC`
    - I replied to that, then Dan replied to this threaded comment at `2023-08-10 17:22 UTC`

I received these email notifications, and they appear in my Email delivery logs accurately, as follows:

```
[New comment] Welcome, Marie [...]
    timestamp: Thu, 10 Aug 2023 17:05:13 +0000
    caller: wp_notify_parent_comment_author

[New comment] Welcome, Marie, [...]
    timestamp: Thu, 10 Aug 2023 17:22:13 +0000
    caller: wp_notify_parent_comment_author
```

**TEST TWO** - Free P2 Comment Thread: https://ariteststhingsp2general.wordpress.com/2023/08/10/welcome-to-your-p2/
- This is a P2 I created for testing under a non-staff WordPress.com account.
     - The P2 Owner left a series of comments on the post, of which they are the author.
     - A second account (added as an admin) left replies to these comments.

P2 Owner has EMAIL notifications enabled for comments on this site (https://wordpress.com/me/notifications), and received new comment updates like this:

```
[New comment] Welcome to your P2!
    timestamp: Thu, 10 Aug 2023 19:03:42 +0000
    caller: send_comment_to_subscriber_batch
```

Other commenter, non site owner or post author, also subscribed to notifications for comments on my site and comment replies on other blogs, received notification emails like this:

```
[New comment] Welcome to your P2!
    timestamp: Thu, 10 Aug 2023 18:55:24 +0000
    caller: wp_notify_parent_comment_author
```

These all seemed to track relatively well, but the emails were sometimes delayed, or arrived in my inbox with a delay in logstash, so that may reflect an intermittent issue I can't really see.

</details>

---

### Notes on Email delivery logs for the person who raised the report internally

They shared links to several comments that they received a bell notification for, but no email.  I checked out their email delivery logs, and couldn't find any direct matches for those notifications.

<details>
  <summary>Detailed findings for the comments they reported</summary>

1. p1691260635356439-slack-C025Q5RK2 at `2023-08-05 18:11 UTC` is not found in the reporter's Email delivery logs, when searching for all emails delivered between 2023-08-04 - 2023-08-06.
2. p1691260876994039/1691260635.356439-slack-C025Q5RK2 this refers to 4 different comments left by the same author on `2023-08-04` at `21:01 UTC`, `21:46 UTC`, `22:11 UTC`, & `22:14 UTC`.  Again, none of these have corresponding logstash records, 
     - Rhere are Email delivery records for this post corresponding to other comments that day:
     - p6mraL-kl-p2#comment-1135 and p6mraL-kl-p2#comment-1138, both in reply to someone else's comments
     
     ```
    [New comment] Digital Services [...]
    timestamp: Fri, 04 Aug 2023 20:43:49 +0000
    caller: send_comment_to_subscriber_batch

    [New comment] Digital Services [...]
    timestamp: Fri, 04 Aug 2023 22:08:29 +0000
    caller: send_comment_to_subscriber_batch
    ```

3. pdn9vV-cx-p2#comment-205 last flagged comment at `2023-07-27 22:09 UTC`
     - **Unclear** - there are 2 email delivery records for comments at 22:10 and 22:11, and the post has 2 comments published at 22:09 and 22:11 - it's plausible the first comment's delivery was delayed in the logstash.
     
     ````
    [New comment] Tumblr Domains
    timestamp: Thu, 27 Jul 2023 22:10:00 +0000
    caller: send_comment_to_subscriber_batch
     ```

</details>

- Note: I could find no email delivery records in the reporter's logs with the `caller: wp_notify_parent_comment_author` log.

📌 ACTIONS
- Assigned to @Automattic/apex

**Comment by ebinnion** [comment]
@Automattic/apex - Can someone investigate this please?

**Comment by TimBroddin** [comment]
Hey,

We did some sleuthing today, and found what causes this. 

- When new comment emails go out, we check whether the site is a P2 & the user was mentioned in the comment. In that case the user will already receive a mention email, and we don't want to spam their mailbox with 2 mails.
- The new mention email has a check to see whether the user hasn't disabled mention emails. When mention emails are disabled, of course no new mention mails will be sent out.

``` 
if ( ! WP_Note::is_notification_setting_disabled( $user->ID, $context['blog_id'], 'email', 'mentions' ) ) {
   // the mail sending part 
}
```

When you are mentioned in a comment and have mention emails disabled, you thus won't receive any email.

I'll create a fix that adds an extra check here: fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Swbof.cuc%232222%2Q2226-og

**Comment by TimBroddin** [comment]
The user also mentioned not getting a new post email for a post he was mentioned in. I'm currently looking into that issue as, but I assume it might be related.

Happens here: fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sfhofpevcgvba%2Qrznvyf%2Sfhofpevcgvba%2Qrznvyf.cuc%23474%2Q476-og

**Comment by yansern** [comment]
Just want to add that even though with this patch D119077-code added which will send out new comment notification as a fallback if user disabled mentions notifications, there will be a case where the user won't receive this fallback comment notification:

- If the person mentioned is not the post author, they are not a subscriber of the comments of the post, and so, if they are mentioned in those comments, they won't receive a comment notification.
- Even if the person has commented on the post, P2's comment box doesn't have the option to tick "Subscribe to comments of this post", and therefore, will never have a way to receive comment notifications.

**Comment by TimBroddin** [comment]
Closing, since D119077-code is deployed

**Comment by TimBroddin** [comment]
Reopening since @bryanvillarin  noticed a related issue: 

> "I noticed Tim, Yan & Marie worked on this, and Tim deployed something about eight hours ago (then closed out the issue). Thank you!
> 
> About two hours ago, my WPCOM username was mentioned on a P2 where my Notification Settings for Username mentions has Email checked. Sadly, I did not get an email notification (only the notification bell). :bell-ping:"

**Comment by TimBroddin** [comment]
I did some xdebugging and it seems like @bryanvillarin has a legacy setting set that disabled mention notifications globally:

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sabgrf.cuc%231268%2Q1275-og

`echo get_user_attribute( $bryans_user_id, 'disable_mentions_notification' ) ` returns `1`.

@bryanvillarin I think the quickest way to resolve this on your end is calling this from `wpsh`:

`delete_user_attribute( $your_user_id, 'disable_mentions_notification' )`

**Comment by cuemarie** [comment]
Reviewing the thread again: p1692911447742329/1691260635.356439-slack-C025Q5RK2 it looks like this should be working now!

📌 ACTIONS
- Closed as resolved
