### ISSUE TITLE
Assembler: Add a confirmation step

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#80679]
## Description

As proposed in pekYwv-2Fn-p2, we want to introduce a confirmation step after users have completed pattern and style selection. In this step, we can instruct users and set expectations for what's next.

Note that users will only see this step if they have not selected any custom styles. Otherwise, they will see the gated custom styles step described in https://github.com/Automattic/wp-calypso/issues/80682.

See Figma file: Tv3pYqA3EcRfiXC31IxrXE-fi-1660_47934, or the following screenshot for reference:
![Image](https://user-images.githubusercontent.com/797888/260952152-d07301c7-7bff-4168-a46b-e4e2c1fc71b9.png)

## Acceptance Criteria
- [x] Implement this confirmation step for users that have not selected any custom styles.
- [x] Ensure that the new interactive elements have Tracks events.
- [x] Finalize copy with @autumnfjeld and @lucasmendes-design.

**Comment by taipeicoder** [comment]
@lucasmendes-design the current Assembler has this step when the user comes from the LiTS: 
![Screenshot 2023-08-22 at 12 25 01 PM](https://github.com/Automattic/wp-calypso/assets/797888/a9e5d273-7e5d-478a-8409-b50964a14ba1)

Should we merge it to this step?

**Comment by lucasmendes-design** [comment]
> Should we merge it to this step?

We have two different use cases in two different moments in the user journey. 

**Use case 1:** Account creation (or new site) > Design Picker > Patterns > Styles > Confirmation step (Great Job!).  
**Use case 2:** Logged-in Theme Showcase > Patterns > Styles > Confirmation step (Activate theme).

For the use case 2, in terms of importance, I think it's better to clearly present the information about replacing their homepages instead of "Great Job!" or any other information. This user has already committed to using our platform and may know more about the Editor and other concepts. Plus, I would avoid adding more steps to the flow and both pages are a _kind of_ confirmation page. So, I would keep it that way and not merge it into the LiTS, at least not for now.

**Comment by taipeicoder** [comment]
@lucasmendes-design do you mean that for use case 2, we show the existing step of asking users to confirm about replacing their homepage instead of the Great Job screen? That makes sense to me.

How about when users select a custom style? Should the confirmation step come before or after the upsell screen?

Patterns > Styles > Upsell > Confirmation, or
Patterns > Styles > Confirmation > Upsell?

**Comment by arthur791004** [comment]
Currently, we redirect the user back to the Assembler screen after the plan upgrade.

* The Assembler screen includes patterns and styles > Confirmation > Upgrade modal > (upgrade sucessfully) > The Assembler screen

I guess the flow could be

* Pattern > Styles > Upsell > (upgrade sucessfully/decide later) > Confirmation

When we're able to redirect the user to the congratulation screen, we can come back to adjust the flow at that time.

**Comment by miksansegundo** [comment]
After the Upsell modal (or the future https://github.com/Automattic/wp-calypso/issues/80682) we redirect to the Checkout page and then back to the assembler because we must complete the flow from there (calling onSubmit()).

My understanding is that to avoid adding more steps to the flow the final steps are:

1. Activation screen (keep it as it is) - for existing sites
2. Confirmation screen (this issue) - for new sites


When customers choose premium styles they see the Custom styles screen (see https://github.com/Automattic/wp-calypso/issues/80682) and then we will redirect them back to the Activation or Confirmation screen whether the site is new or existing.

The flows will be:

1. Pattern > Styles > Activation > Editor
2. Pattern > Styles > Confirmation > Editor
3. Pattern > Styles > Custom styles screen > Checkout > (Activation |  Confirmation) > Editor


Does it make sense?

**Comment by lucasmendes-design** [comment]
> we show the existing step of asking users to confirm about replacing their homepage instead of the Great Job screen?

Yes, @griffbrad. 

> How about when users select a custom style? Should the confirmation step come before or after the upsell screen?

This flow is related to my recent post I think ( paYJgx-3TE-p2 ). Ideally, after the checkout page. Users will land on the confirmation step. I think this is what you meant @miksansegundo. Video below:

https://github.com/Automattic/wp-calypso/assets/98343583/fbab47b0-5770-4eed-8bee-00a4570bda1a

If it's a new user/new site, there is no need to show the modal since there is no homepage to be replaced. Does it make sense?

**Comment by autumnfjeld** [comment]
@taipeicoder (not the other Griffith 😄 ) ^^  https://github.com/Automattic/wp-calypso/issues/80679#issuecomment-1692133623

**Comment by lucasmendes-design** [comment]
Ops hahaha.

**Comment by taipeicoder** [comment]
@lucasmendes-design is this screen meant to be shown for users that have completed the checkout? Or mean to replace the Activation screen attached in this https://github.com/Automattic/wp-calypso/issues/80679#issuecomment-1687397454? Which means it would be shown to all users that have an existing site.
![Screenshot 2023-08-25 at 1 04 52 PM](https://github.com/Automattic/wp-calypso/assets/797888/f76da9ae-774f-41d8-93c6-31b9c1e60c93)

cc: @Automattic/lego

**Comment by lucasmendes-design** [comment]
> is this screen meant to be shown for users that have completed the checkout?

Yes, only after the checkout page. This is the congratulations page that we're using after users buy a product. 

P2 - p9Jlb4-7Hx-p2#comment-8313
