### ISSUE TITLE
Theme curation: Only show categories with more than 2 *visible* themes

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#80678]
Follow-up to https://github.com/Automattic/dotcom-forge/issues/3324

As of https://github.com/Automattic/wp-calypso/pull/80318 and D118131-code, we no longer display categories with less than 3 themes in the theme showcase and design picker.

However, the logic does not account for themes that are not visible in those lists. For instance, the "Entertainment" category has 6 themes, but only one is visible in the DP. As a result, such category should be hidden in the DP, but it's currently visible:

<img width="1143" alt="Screenshot 2023-08-16 at 10 28 33" src="https://github.com/Automattic/wp-calypso/assets/1233880/4613276c-b7ab-4daa-bac4-5f836ca5161f">

I'm not aware of any other case, but nothing is preventing that from happening for other categories in both the TS and DP.

We should change the logic somewhere to ensure that the minimum number of themes required for a category to be visible consider whether themes are going to be displayed.

**Comment by rcrdortiz** [comment]
The main problem is that we don't know how the different clients are going to filter the themes. A client might show all themes, another client could request curated themes, and another one could should themes based on any given logic. The theme subjects API isn't aware of the filtering the client will do so we can't infer how many items a specific category will have.

The only solution that comes to my mind is merging the themes and filters API in a single API that includes the subjects + results, otherwise, we're going to need to filter the subjects on each client based on the theme results or come up with something else.

**Comment by mmtr** [comment]
> The only solution that comes to my mind is merging the themes and filters API in a single API that includes the subjects + results

Good thinking, that's what we do for the DP. The call to the `starter-designs` endpoint returns both the subjects and results, so we can definitely infer there the themes that are going to be visible. It'd be great if we can do that in the TS too.

**Comment by rcrdortiz** [comment]
> Good thinking, that's what we do for the DP. The call to the starter-designs endpoint returns both the subjects and results, so we can definitely infer there the themes that are going to be visible. It'd be great if we can do that in the TS too.

That's great news! We could then unify the DP and LOTS/LITS to use the same architecture which was one of our mid-term architecture goals.

**Comment by mmtr** [comment]
Fixed in D119551-code
