### ISSUE TITLE
Editing ToolKit and Page Optimize conflict at [Add New Post] page on sites with heavier plugin use

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#80713]
### Quick summary

Relevant links:

- tracking thread: p9F6qB-d1r-p2 
- escalation: p1692205609474649-slack-C02FMH4G8

When users go to My Site > Pages (posts & custom post types, too) > Add New, they see a broken editor due to a static 400 response on a page-optimized concatenated CSS file. 

While it's typical for Page Optimize's CSS concatenation to cause this issue, there is a significant spike of reports (over 50 on the tracking thread above), and reports are suggesting a possible conflict between the WordPress.com Editing Toolkit and Page Optimize plugins (with a combination of various third-party plugins).

Turning off CSS concatenate within Page Optimize's settings only helps in very few cases, and the entire plugin, either Page Optimize or WordPress.com Editing ToolKit, needs to be deactivated to fix the editor (we've **encouraged deactivating Page Optimize as the work around, since the WordPress.com Editing ToolKit plugin comes with a lot of features**.)

### Steps to reproduce

~~We have been unable to reproduce on a test site. However, the issue is still reproducible on sites within the tracking thread when you turn Page Optimize back on.~~ https://github.com/Automattic/wp-calypso/issues/80713#issuecomment-1681425041.

### What you expected to happen

I expect the editor to load.

### What actually happened

The editor loads with broken CSS, and there's a 400 bad request on one of the Page Optimize CSS files e.g ( `/_static/??-eJy9`) 

![image](https://github.com/Automattic/wp-calypso/assets/29527450/95b05164-3043-4aca-8b29-e2a008df9256)

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by upwardmomentum84** [comment]
I was able to reproduce the issue after installing All In One SEO plugin.

![Markup 2023-08-16 at 15 34 55](https://github.com/Automattic/wp-calypso/assets/93800099/dfde8f7b-ad2b-4348-97f7-e9efaa4d5042)

These are the plugins I have active:

Akismet Anti-Spam: Spam Protection
All in One SEO
CoBlocks
Crowdsignal Forms
Crowdsignal Polls & Ratings
Jetpack
Page Optimize
Rank Math SEO
Redirection
Sensei Blocks
Sensei LMS
WooCommerce
WordPress.com Editing Toolkit

Deactivating ANY one of those plugins (yes, even Akismet and JP) resolves the issue.

I also discovered the issue is only happening on my test site when certain themes are active such as Varia, Rockfield, or Barnsbury. The issue was not occurring with Dara, Shoreditch, or Twenty Twenty Three for example.

**Comment by villanovachile** [comment]
Howdy! I was able to test this further with @ash1eygrace and I think we've identified the source of the issue. The first problem is being able to reliably reproduce this.

It seems that the issue is first caused by an accumulation of plugins that are somehow overloading Page Optimize, which ultimately seems to be bearing the weight of the problem and ultimately links to a reference with an HTTP 400 bad request as shown below:

![image](https://github.com/Automattic/wp-calypso/assets/65082164/d5996cd6-5f2d-419f-853e-93b6cde44da9)


Again, this is a symptom, not the source of the issue.

We can reliably reproduce this issue with a minimum number of plugins and combinations of themes & plugins, most of which @upwardmomentum84  had post above. I was able to reproduce with the following plugins & combination:

* akismet
* all-in-one-seo-pack
* coblocks  
* crowdsignal-forms 
* polldaddy  
* elementor  
* jetpack
* mailpoet  
* page-optimize 
* woocommerce 
* woocommerce-services
* full-site-editing

Theme: any Varia child theme

As Brandon had stated, the themes he mentioned seem to come into play as well, although I was able to reproduce this with Twenty Twenty Two as well, if I added additional block related blocks. 

Deactivating any of the above plugins will resolve the issue, however, the source of the issue appears to be WooCommerce version 8.0.0 and above.

I thoroughly tested earlier versions of Jetpack on a WoA Dev site, and the issue persisted indicating that Jetpack was not the cause (this issue just started popping up). Rolling WooCommerce to a version prior to 8.0.0, such as 7.9.0 resolves the issue for me. WooCommerce 8.0.0 was released on 2023-08-08

You can see the full changelog here: https://raw.githubusercontent.com/woocommerce/woocommerce/trunk/changelog.txt

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated following @villanovachile 's specifics above.  

Theme: `varia 1.6.25`

Plugin List:

```
akismet              5.2
all-in-one-seo-pack  4.4.3
coblocks             3.1.2
crowdsignal-forms    1.7.0
polldaddy            3.0.11
elementor            3.15.2
jetpack              12.5-a.7
mailpoet             4.24.0
page-optimize        0.5.3
woocommerce          8.0.2
woocommerce-services 2.3.2
full-site-editing    3.75083
```

Deactivating any plugin combined above, switching the theme, _or rolling back woocommerce to 7.9.0_, resolves the symptom.

📌 ACTIONS
- Scrubbed, awaiting assignment

**Comment by rw-ye** [comment]
Another report: 6678446-zen

Deactivated page optimize plugin

**Comment by inaikem** [comment]
6678754-zd-a8c

**Comment by inaikem** [comment]
6678924-zd-a8c

**Comment by Robertght** [comment]
6652393-zen

**Comment by inaikem** [comment]
Oops! I closed this earlier by accident but it's very much alive! 🙏

**Comment by jamiepalatnik** [comment]
Another report: 6681437-zd-a8c
Turning off CSS concatenation in Page Optimize plugin resolved the issue.

**Comment by jamiepalatnik** [comment]
Another report: 6681661-zd-a8c
Turning off CSS concatenation in Page Optimize plugin resolved the issue.

**Comment by mgozdis** [comment]
6683857-zd-a8c
Deactivated Page Optimize.

**Comment by Robertght** [comment]
6659123-zen turning off Page Optimize helped.

**Comment by jartes** [comment]
- Another one on 6686613-zen 
- Turned off `Concatenate styles` option as a workaround.

**Comment by druesome** [comment]
6686550-zen

**Comment by mgozdis** [comment]
More reports - Deactivated Page Optimize on all
6669631-zd-a8c
6670406-zd-a8c
6670753-zd-a8c
6674898-zd-a8c

**Comment by geekinthegirl** [comment]
Another report here, deactivating Page Optimize and flushing the cache fixed the issue:

6687597-zd-a8c

**Comment by ash1eygrace** [comment]
Instances scraped from the tracking thread p9F6qB-d1r-p2 are here: 

6650824-zen
6651436-zen
6651436-zen
6648944-zen
6650304-zen
6650630-zen
6653453-zen
6653308-zen
6653547-zen
6654753-zen
6655197-zen
6652749-zen
6652154-zen
6661008-zen
6661179-zen
6661398-zen
6661272-zen
6661825-zen
6661877-zen
6662263-zen
6662540-zen
6663071-zen
6658665-zen
6656384-zen
6664495-zen
6664838-zen
6663883-zen
6668171-zen
6671934-zen
6629673-zen
6672635-zen
6672942-zen
6673037-zen
6674055-zen
6674078-zen
6649700-zen
6674669-zen
6649825-zen
6667163-zen
6672898-zen
6675212-zen
6676838-zen
6686533-zen
6686226-zen

**Comment by jamiepalatnik** [comment]
Another report: 6693251-zd-a8c
Turning off CSS concatenation in Page Optimize plugin resolved the issue.

**Comment by cuemarie** [comment]
KitKat has brought this to Woo devs attention p1692234833442139/1692018789.471899-slack-C01DT6U03HC to see if we can determine if the Woo update to 8.0.x is what triggered this overload on Page Optimize.  Thanks for continuing to share reports while we work on tracking down where best to address this!

**Comment by i11za** [comment]
Another report 6694917-zd-a8c
urning off CSS concatenation in Page Optimize plugin resolved the issue.

**Comment by janmckell** [comment]
Another report here - 6696626-zd-a8c
Deactivating WordPress Editing Toolkit resolved it.

**Comment by Robertght** [comment]
6698096-zen

**Comment by Robertght** [comment]
6698259-zen

**Comment by i11za** [comment]
6698364-zd-a8c
Turning off CSS concatenation in Page Optimize plugin resolved the issue.

**Comment by i11za** [comment]
6698520-zd-a8c

**Comment by inaikem** [comment]
6703888-zd-a8c

**Comment by DavidSaladu** [comment]
6704450-zd-a8c

**Comment by brinbliss** [comment]
- [ ] 6705680-zd-a8c

Turning off Editing Toolkit didn't fix the issue, but turning off CSS concatenation in Page Optimize plugin did resolve the issue.

**Comment by i11za** [comment]
6671266-zd-a8c 
Turning off CSS concatenation in Page Optimize plugin resolved the issue.

**Comment by janmckell** [comment]
6707008-zd-a8c
Turning off WordPress Editing Toolkit helped.

**Comment by rakshitwesley** [comment]
6709474-zd-a8c

**Comment by rinazrina** [comment]
6709349-zd-a8c

**Comment by filipanoscampos** [comment]
6710284-zen-a8c

**Comment by mgozdis** [comment]
6711763-zd-a8c

**Comment by galakhyati** [comment]
6716887-zd-a8c

**Comment by Robertght** [comment]
6716873-zen. In this case it impacted creating lessons in Sensei.

**Comment by jamiepalatnik** [comment]
Another report: 6717375-zd-a8c
Turning off CSS concatenation in Page Optimize plugin resolved the issue.

**Comment by mxhassani** [comment]
6717870-zd-a8c
 Turning off CSS concatenation in Page Optimize plugin resolved the issue.

**Comment by villanovachile** [comment]
Another report 6717762-zen

**Comment by galakhyati** [comment]
6721258-zd-a8c
Deactivating Page Optimize plugin fixed the issue.

**Comment by liviopv** [comment]
6722739-zd-a8c deactivating either ETK or Page Optimize worked. I deactivated Page Optimize.

**Comment by mgozdis** [comment]
6728036-zd-a8c

**Comment by villanovachile** [comment]
6727868-zen

**Comment by nerrad** [comment]
Is page optimizer executing concatenation in the editor? And if so, why?

**Comment by inaikem** [comment]
6730046-zd-a8c - I deactivated Page Optimize.

**Comment by liviopv** [comment]
6730592-zd-a8c - deactivated page optimize

**Comment by edwinho89** [comment]
6732735-zd-a8c - Turning CSS concatenation works

**Comment by mriyazuddin** [comment]
6732899-zd-a8c - Turning off "Concatenate styles" worked.

**Comment by mriyazuddin** [comment]
6733361-zd-a8c - Turning off "Concatenate styles" worked.

**Comment by janmckell** [comment]
Ran into this issue: 6736537-zd-a8c

What was done to fix:
WordPress Editing Toolkit reactivated
Autoptimize deactivated
WP-Optimize - Clean, Compress, Cache deactivated

On Page Optimize plugin, CSS concatenization has been disabled.

**Comment by jeyip** [comment]
Hey team -- I started looking into drafting a patch for this. I didn't have a lot of time to work on the issue today, but it sounds like the consensus is that we want to disable the page-optimize plugin when in the editor context, so here's what I imagine a rough sketch would look like:

```php
function maybe_disable_page_optimize_plugin($plugins) {
    if ( !function_exists( 'get_current_screen') ) {
        return $plugins;
    }

    $current_screen = get_current_screen();
    
    if ( $current_screen->base === 'post' || $current_screen->base === 'page' ) {
        $key = array_search( ‘PATH_TO_PAGE_OPTIMIZE/page-optimize.php’ , $plugins );
        if ( false !== $key ) unset( $plugins[$key] );
    }

    return $plugins;
}

add_filter( 'option_active_plugins', 'maybe_disable_page_optimize_plugin' );
```

To get this out as soon as possible, I imagine we'd want to release this in some mu-plugin in the simple wpcom codebase and then in the wpcomsh plugin for atomic sites? Once completed, we could release more broadly through the jetpack plugin or the jetpack mu wpcom plugin PCYsg-Osp-p2 depending on whether or not this issue is also affecting self-hosted sites.

When released, we could then circle back and remove the hotfixes from simple wpcom and wpcomsh

**Comment by Robertght** [comment]
6688587-zen - turning off the "Concatenate styles" bit helped.

**Comment by rcrdortiz** [comment]
I'm working on a solution, It's in review so hopefully, we will have a fix released soon. https://github.com/Automattic/page-optimize/pull/74

Once the PR gets merged we can turn on `Concatenate Styles` again for all our customers.

**Comment by Robertght** [comment]
6739964-zen - turning off the "Concatenate styles" bit helped.

**Comment by brinbliss** [comment]
- [ ] 6740337-zd-a8c

Turned off Concatenate styles within Page Optimized fixed issue.

**Comment by rcrdortiz** [comment]
The changes are now deployed and live. The issue should be solved when the plugin version gets updated.

**Comment by mriyazuddin** [comment]
- [ ] 6679734

Had to turn off Concatenate styles. The Page Optimize plugin doesn't have an update available yet so I guess we would need to wait.
