### ISSUE TITLE
Fullpost Refresh: Mystery mystery man

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8076]
https://wordpress.com/read/blogs/16956016/posts/19503

As reported by @gibrown, this post shows a mystery man avatar when it shouldn't. Any idea why?

**Comment by blowery** [comment]
It's because we think the user has set a gravatar, though apparently they have not. 

http://en.gravatar.com/lostartpress.json is interesting. Apparently there's a "user image" and gravatar is able to use the default icon. Perhaps they way we sync back the user meta flag is busted...

@westi might know more.

**Comment by fraying** [comment]
@blowery So what should we do? Any ideas? Is this a super edge case?

**Comment by bluefuton** [comment]
My read is that this is a Gravatar bug. Is that right? Should we be reporting this elsewhere @blowery?

**Comment by blowery** [comment]
it's a bug in the bridge between grav and wpcom.... unsure where to report it.

**Comment by westi** [comment]
I dug into this a little and as far as I can see this _should_ work.

Someone needs to dig into reproducing the flows within gravatar for adding a removing images from the default identify and see if they can reproduce - if not we should just re-sync the values and move on.

@designsimply what is the best way to encourage someone to take on this testing?

**Comment by fraying** [comment]
Dupe
