### ISSUE TITLE
Auto-save getting stuck and causing content loss

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#80822]
A few folks I've chatted with have run into auto-save issues, where the auto-save seems to fail (stuck as "saving") and content later being lost due to the failure. It's inconsistent at this point and hard to track down. Tagging in folks who have experienced it to see what additional information can be provided. cc @MartinAkram @cyle @maxme @backwardstruck

**Comment by ccwalburn** [comment]
I've had two users report this issue today so I did a quick search and found all of these recent reports with the same issue:

-  6635447-zd-a8c
-  6637022-zd-a8c
-  6641490-zd-a8c
-  6649091-zd-a8c
-  6623380-zd-a8c
-  6638520-zd-a8c

**Comment by annezazu** [comment]
@ccwalburn -- can you describe more about the setup for those sites (simple, atomic, etc)? Thanks so much for bringing in additional reports.

**Comment by ccwalburn** [comment]
Sure! 

- 6635447: Premium plan, Digg 3 Column theme (retired)
- 6637022: Free site, Scratchpad theme
- 6641490: Premium plan, Gateway theme
- 6649091: Business plan (Simple site), Twenty Twelve theme
- 6623380: Premium plan, they have two sites and I'm not sure which one they were working on. They use the Lovecraft and Twenty Fifteen themes
- 6638520: Personal plan, Baskerville 2 theme

**Comment by frosty** [comment]
I have this issue right now on a post I'm editing on the Day One Apple P2. The only thing of note to me is that I've had the editor open for a long time – at least a week, as I was writing a post and then went AFK.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Based on the user reports @ccwalburn shared, this _looks_ like it impacts Simple sites on classic themes. 
- I tested on Twenty Twenty Three, Twenty Fifteen, Twenty Twelve, and Scratchpad across 2 brand new free sites, editing them in 2 windows side by side. 
- After 15 minutes of editing (one in each window, with no other tabs open to WordPress.com), I was still seeing consistent autosaves roughly every 60 seconds.

#### Screenshots/Recordings

Round One - TT3 (left) & T15 (right): _You can observe the Auto-save happening around the :50-:05 on the on-screen stopwatch. Left site autosaves first, followed shortly by the window on the right._

https://github.com/Automattic/wp-calypso/assets/27249804/889e57fa-8d62-443c-b93a-d71535aca70d

Round Two - Scratchpad (left) & T12 (right): _Auto-saves happen at the :20 second mark, on the site that I'm working on at the moment. (If I leave one post editor untouched for several minutes, the editor doesn't keep saving, but it resumes saving as I resume my work. Just a couple highlights:_

2:20 - both sites autosave

![Markup on 2023-08-21 at 16:26:52](https://github.com/Automattic/wp-calypso/assets/27249804/bdf5c9a3-6077-49bf-99f0-51847bd3c648)

| 12:20, Site 1 (Scratchpad)  | 14:20, Site 2 (Twenty Twelve) |
| ------------- | ------------- |
| ![Markup on 2023-08-21 at 16:28:11](https://github.com/Automattic/wp-calypso/assets/27249804/34ba9683-dad2-4c23-9782-7e5882ec19ae) | ![Markup on 2023-08-21 at 16:28:35](https://github.com/Automattic/wp-calypso/assets/27249804/928b2299-641a-4894-89a1-4cfe90346aba) |

📌 ACTIONS
- Leaving open to see if anyone else can repro this.

**Comment by cuemarie** [comment]
📌 NOTE TO HEs
- For future HEs that encounter users reporting that they lost content, please be sure to go through the https://wordpress.com/support/editors/page-post-revisions/#other-tips-to-recover-lost-content tips with your customer before reporting their experience as this bug. 
- There are a few possible causes that can contribute to their content not saving, and eliminating common causes of auto-save issues before reporting here will help keep the reports on this issue as clear as possible, so we can identify any patterns more efficiently. Thank you!

**Comment by jasmussen** [comment]
I experienced this today, and have some logs to share. I'm occasionally on flaky wifi and will briefly lose connection. When that happens, autosave gets stuck, and I get the following message in the logs — edited for anonymity:

```
POST https://public-api.wordpress.com/wp/v2/sites/[siteid]/posts/[postid]/autosaves?_envelope=1&environment-id=stage&_gutenberg_nonce=[nonce]&_locale=user net::ERR_NETWORK_CHANGED
```

When I follow that URL I see the following response:

```
{"body":{"code":"unauthorized","message":"User cannot access this private blog.","data":{"status":403}},"status":403,"headers":[]}
```

**Comment by ccwalburn** [comment]
One of our users wrote back with some additional observations:

> From my limited experience, it is most pronounced on a slower link, but I have had it fail on my Mac Studio on FIOS as well. Less often, but still annoying. Does not seem to be a computer speed/memory issue.

**Comment by flootr** [comment]
Just a quick update as I started looking into this issue: I have yet to reproduce it reliably but I ran into a few occurrences of the bug (especially with long running tabs) but couldn’t narrow it down. One possible route I’m exploring is whether there might be any race conditions under certain (network) conditions.

**Comment by flootr** [comment]
Documenting some observations I did by debugging network requests and actively blocking those to see how the editor behaves in those scenarios:

#### - dotcom (simple)

Blocked network requests to: `public-api.wordpress.com/wp/v2/sites/*/posts/*/autosaves`

You have to wait about 1 minute until the editor attempts an autosave after the editor loads and is ready for editing. Also, the post content hast do be in dirty state (i.e. edited) for an autosave request to happen. Please note that you have to enable network request blocks **after** the editor loaded (otherwise I didn't get any autosave requests at all).

In this case the `Save` button is changing to `Autosaving…` and **not** recovering after the request failed.

<img width="191" alt="Screenshot 2023-09-11 at 13 33 09" src="https://github.com/Automattic/wp-calypso/assets/9202899/54b36c5b-c0f1-46ff-93b7-30dbbc388c34">

#### - dotorg (local dev)

Blocked network requests to: `localhost:8888/index.php?rest_route=%2Fwp%2Fv2%2Fposts%2F6%2Fautosaves`

Autosaves happen about 15 seconds after the editor loaded (post content also has to be in dirty state). It didn't matter whether I enabled request blocking before or after the editor loaded.

In this case the `Save` button changes to `Saving…` and recovers successfully after the request fails (allowing you to save manually). The UI shows a banner which says `Updating failed. You are probably offline.`.

<img width="354" alt="Screenshot 2023-09-11 at 13 44 36" src="https://github.com/Automattic/wp-calypso/assets/9202899/134c7e51-96c1-4ff3-88d7-1afc562b818d">


There's still a glitch here because the `<AutosaveMonitor />` component maintains a class property [`needsAutosave`](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/autosave-monitor/index.js#L28) which is set back to `false` [even if the request failed](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/autosave-monitor/index.js#L82-L83) thus doesn't issue another autosave request. This should be handled better but it's in the editor itself, not dotcom.

Please note that I didn't get any autosave requests if **local** (!) autosave state (there's `<LocalAutosaveMonitor />` which wraps `<AutosaveMonitor />`) is different from what you have in the editor (i.e. shows a warning banner which says "The backup of this post in your browser is different from the version below."). This may be related my local changes but I wanted to mention in case someone else is debugging to and wondering why that might be.

#### next steps

Looking at both examples above it's clear that we have to explore further why the `Save` button is not recovering on dotcom after an autosave attempt failed and not showing any warnings in comparison to dotorg.

**Comment by tyxla** [comment]
Thanks for the update, @flootr! 

I wonder if it might be helpful to introduce some tracking or logging on the WP.com side in an attempt to track how often this occurs. It could also be an opportunity to retrieve some extra data that could help us understand the scenarios where it occurs most often. 

Furthermore, on the Gutenberg side, we might want to explore how to tighten up autosaving when it comes to network errors or intermittent failures.

**Comment by annezazu** [comment]
>Furthermore, on the Gutenberg side, we might want to explore how to tighten up autosaving when it comes to network errors or intermittent failures.

Can you bring any insights into the Gutenberg repo when you have a chance?

**Comment by flootr** [comment]
> Can you bring any insights into the Gutenberg repo when you have a chance?

@annezazu I'm happy to do that though I don't think we have a problem on the .org side when it comes to network failure - that problem seems to be specific to dotcom. What I meant in my previous comment is that we're overly optimistic about the autosave request being successful so that we set the state `needsAutosave` to `false` without looking at the request response. In theory, this could lead to content loss but as the UI (to be more specific, the _Save_ button) doesn't block it's much less likely to happen (also because there's local autosave and you're asked to save your changes before you browse away). – I will look more into this and bring any findings to the Gutenberg repo once I'm done with the dotcom side of things.

**A quick update on the dotcom side of things**: We don't use the default request handler that `apiFetch` provides (due to how the editor is used on .com which seems to be the culprit here. For some reason if a request fails due to network failure/being offline the error isn't passed back and handled in a proper way which leaves the UI blocked. I'm still investigating how to circumvent that.

**Comment by jp-imagines** [comment]
Another user report in 6638520-zd-a8c (initially discussed in https://github.com/Automattic/wp-calypso/issues/81782)

**Comment by inaikem** [comment]
Another user report in 6752817-zd-a8c. @flootr 👋 The affected user came back with a lot more context that may be useful to you here. Please let me know if I can provide any additional context.

**Comment by tyxla** [comment]
Markus has been unable to work on this over the past week, but @jsnajdr has been looking into it and has since isolated the bug, and is now working on a solution.

**Comment by ha-un** [comment]
Another report in: [7098421-zd-a8c](https://a8c.zendesk.com/agent/tickets/7098421)

**Comment by jsnajdr** [comment]
There is a fix in D123683-code ready for review and testing. Hope it will be ready to deploy soon 👍

**Comment by cuemarie** [comment]
Reported here as well: 6804730-zen

**Comment by tyxla** [comment]
Jarda just merged the https://github.com/Automattic/wp-calypso/issues/80822#issuecomment-1740928100 - could you all give it another try and try reproducing it?

**Comment by flootr** [comment]
D123683-code works well for me 👍🏻 I'm not able to reproduce the bug anymore.

**Comment by tyxla** [comment]
Going to close as resolved. Let us know if it reoccurs under any circumstances and we'll take a look again.
