### ISSUE TITLE
Sitemaps does not match the actual page

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#80973]
### Quick summary

The sitemaps are not being generated correctly due to some problems updating the `post_parent` column. The problem that I noticed was:
* The blocks are not properly unlinked after deletion. This leaves the `post_parent` set on the image post, thus leading the sitemap to continue to show the images even after deletion.
* Sometimes adding the images to a page doesn't update the `post_parent` column, which causes the image to not show up on the sitemap.

Ticket: 6589171-zd-a8c

### Steps to reproduce

1. Create a new page
2. Add an image, uploading it through the editor to the page.
3. Save the page
4. Open the sitemap by navigating to `https://your-site/sitemap.xml`
5. If the image appeared on the sitemap, try deleting it in the editor(Jump to step 7 if the image didn't appear).
6. Open the sitemap again. The image should still be there.
7. If the image didn't appear the first time you tried adding it(which is part of the bug), try other ways to upload it, for example, through the media library.
8. Open the sitemap by navigating to `https://your-site/sitemap.xml`
9. If the image appears on the sitemap, jump to step 5.

### What you expected to happen

The sitemap should contain only the images that are present in the sitemaps, and no image should be missing.

### What actually happened

Sometimes, images should appear, and they are not shown in the sitemaps. Sometimes, they shouldn't be shown and continue to be there.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
Hey @valterlorran ! I want to make sure I am walking through the steps to replicate this properly.

So far I've set up 2 new pages with images added in different ways, to see if those appear on my sitemaps.  I started with just 1 image, that appeared right away, then went back and added more. Those didn't appear right away - I had to wait for my sitemaps to refresh, they didn't refresh the moment I made a change. _(AFAIK, [this is expected behavior](https://jetpack.com/support/sitemaps/#sitemap-update-frequency))_.  I left/returned later, and it looks like they updated <10 minutes later. (First update was showing the timestamp `2023-08-24T19:18:--Z`, and now they show `2023-08-24T19:33:36Z`.)

Next, I've removed 1 image from the page alone, and another image from both the page AND the media library, and am now waiting for my sitemaps to update/sync again, so I can check to see which of those images are removed.

Do these testing steps make sense?  LMK if I'm missing anything here - not super familiar with what to expect from the sitemaps. Thanks!

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
In my tests, anything added to the site appeared in the `image-sitemap-1.xml`. Removing the image from the page content alone did not remove the image entirely, but deleting the content from the Media Library did remove the image.

I did need to wait for the site's sitemaps to refresh to see some of the removed images update.

📌 ACTIONS
- @jeherve do you see anything I'm missing in my tests? LMK if you think someone else should look into this, or if you think this is sufficient information to close. Thank you!

**Comment by jeherve** [comment]
> I did need to wait for the site's sitemaps to refresh to see some of the removed images update.

I think that's the key here, that's indeed expected and that may be what @valterlorran experienced.

**Comment by cuemarie** [comment]
Excellent, thanks for confirming!  

📌 ACTIONS
- Closed as by design

**Comment by vparkhere** [comment]
Reopening this since I can replicate the issue on my site where the sitemap won't update despite adding images to a post, specifically via a slideshow block.  I gave the sitemap 12 hours to update on its own, but it still didn't update properly with the images that I added to the post.

Steps to reproduce: 

1. Make sure site is public, then add a slideshow block with images to either a new post or published post. Publish/Update.
2. Check site map at URL/sitemap.xml
3. Wait for a while, at least 10 minutes, and check site map again.  Still will not show images that were added to the post despite `lastmod` date being updated to latest publish/update date.

Here's the test post with the slideshow: https://vpat001.wordpress.com/2017/04/19/first-blog-post/
Test site's sitemap: https://vpat001.wordpress.com/sitemap.xml 

And screenshot of sitemap with no images for the post `https://vpat001.wordpress.com/2017/04/19/first-blog-post/`:
<img width="880" alt="Screenshot 2023-09-13 at 10 35 55 AM" src="https://github.com/Automattic/wp-calypso/assets/11635760/a765a9a8-12a1-45f0-a842-c2c8be4f7144">

**Comment by cuemarie** [comment]
@jeherve do you think this needs a new issue, or should I update the original post?  LMK what you think would work best!

**Comment by jeherve** [comment]
> do you think this needs a new issue

It may be best, since it's specific to images.

**Comment by cuemarie** [comment]
Closing in favor of https://github.com/Automattic/jetpack/issues/33092 for @vparkhere 's report.
