### ISSUE TITLE
Editor: In drafts, date change not reflected in sidebar before publishing

### ISSUE THREAD

**Issue by kevko** [Automattic/wp-calypso#8106]
#### Steps to reproduce
1. Starting a new post at URL: https://wordpress.com/post/site.wordpress.com
2. Change date to a future or past day.
3. Modification not reflected in sidebar, so does not seem "real".
4. Once published, post has date from calendar 

Also affects pages. Tested in staging and production. 
#### What I expected

Date changes made shown in the sidebar, and the calendar view, synchronized. 
#### What happened instead

Date changed in the calendar, but date in the sidebar stays on the current day. Even when draft is saved, date change still not reflected in the sidebar. 

When post published, it uses the date from the calendar but not the sidebar, and change is finally reflected in sidebar. 

The change date behavior does work as expected when modifying published posts. 
#### Browser / OS version

Chrome Version 53.0.2785.89 (64-bit), OS X 10.11.6
#### Screenshot / Video

![date-ooops](https://cloud.githubusercontent.com/assets/578345/18599365/fa998aca-7c0c-11e6-801e-337f2c660687.gif)
#### Context / Source
# a8cgm #kibblingflowclass

**Comment by southp** [comment]
While we no longer show the publish date like that, the new confusion raises for "publishing a post in the past" and "publishing immediately", since they both looks the same.
![image](https://cloud.githubusercontent.com/assets/1842898/19070847/e30f90c8-8a5f-11e6-8ccc-703e8127c722.png)

Comparing to wp-admin, a user can clearly distinguish the two:
![image](https://cloud.githubusercontent.com/assets/1842898/19070859/ea2c7808-8a5f-11e6-8171-eca4fcf7d038.png)

I am not sure how, but we can try to add a caution near the Publish button to notify the user.

**Comment by rachelmcr** [comment]
I tested and can no longer reproduce this issue. Drafts with a past or future date have that date reflected in the sidebar.

Drafts with a future date include a "future" label along with the correct date:

![screen shot 2017-08-07 at 4 40 47 pm](https://user-images.githubusercontent.com/8658164/29034221-7c8474e6-7b8f-11e7-8123-e460e4d6703f.png)

Drafts with a past date have the correct past date displayed:

![screen shot 2017-08-07 at 4 41 07 pm](https://user-images.githubusercontent.com/8658164/29034227-85e6e4a6-7b8f-11e7-98c5-3abab7554f13.png)
