### ISSUE TITLE
안녕하세요. 워드프레스 사이트에 버그가 있는 것 같습니다. 

### ISSUE THREAD

**Issue by infott2t** [Automattic/wp-calypso#81165]
### Quick summary

Let's safely use smartphones, etc. 😁😊; 스마트기기. 안전하게 사용합시다. 좋은 습관을 만들어요. 😁😊

Long sentences. ; 장문이네요. 
...

서비스, 감사드림니다.

워드프레스. 최근에 사용해보고 있네요. 그런데, privacy policy 작성이 영어로 처음에 되어있어서 그대로 사용했거든요. GArvatar라던지. 쿠키 사용이 없었구요. 그래서 사이트 지운다는 광고를 해보구요. Blaze.
그런데, 표시가 잘 안되어있어서... 결제를 하면 바로 될 정도의 금액을 넣고, Blaze광고를 사용했습니다.

지금 현재 지불되면 안되어서... 나중에는 지불을 하구요. 그래서 카드사에 전화를 해봤습니다. 표시가 잘 되어야겠죠. 결제가 안되면, 결제 실패라는 문구가 뜨거나요. 또 버그가 있다면, 전화를 걸어서 통화를 하거나 해야하는데... 안되고. 전화번호를 잘 찾을 수 없더군요.
 그래서, 문의하기를 워드프레스 사이트에서 하는데, '포럼에서 질문하기' 부분이 클릭이 되지 않더군요. 또, 해당 페이지에서 '워드프레스 고객 지원' 링크가 잘 안됨니다. 다시 이 페이지로 가네요. https://wordpress.com/stats/day/adpurchase.wordpress.com.

화면 캡처했습니다.
![화면 캡처 2023-08-29 143031](https://github.com/Automattic/wp-calypso/assets/25080178/d29e313e-2e00-4a73-9fa4-8ba8ac1a825b)

클릭이 되지가 않네요.

 제가 사용하는 해당 카드를 당분간 안써야 되나... 생각을 해봄니다. 힘들죠.

이슈라고 생각해서, 여기에 적어봄니다. 

이해해 주셨으면 고맙겠습니다. 영어를 잘 사용하지 못해서 오해가 생길 수도 있다고 생각해봄니다. 최대한 잘 적어보려고 하네요.

좋은 하루되세요.

또, 교회. 다녀보세요. 기독교. 전화도 해보세요. 사회에서 쉴 곳. 하고 싶은 말 적어보네요.

저의 글, 봐 주셔서 감사합니다.

### Steps to reproduce

클릭이 되지 않네요.
![화면 캡처 2023-08-29 143031](https://github.com/Automattic/wp-calypso/assets/25080178/b920cea2-3fe1-4769-9b2c-afb5c379c951)

### What you expected to happen

문의를 하고 싶은데, 이렇게 밖에 방법을 찾지 못했네요.

### What actually happened

Clicking button but not activate. ; 클릭을 해도 작동하지 않습니다.

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Browser: Google Chrome. 버전 116.0.5845.111(공식 빌드) (64비트)

시스템 정보 확인했습니다.
OS이름: Microsoft Windows 11 Home
버전 : 10.0.22621 빌드 22621

**Comment by cuemarie** [comment]
Hi @infott2t ! 

결제와 관련하여 지원팀에 문의할 때 발생한 문제를 신고해 주셔서 감사합니다. 결제 관련 질문에 대한 구체적인 도움을 받으려면 'help@wordpress.com'으로 지원팀에 직접 이메일을 보내주세요. WordPress.com 계정 이메일 주소를 사용하여 이메일을 보내주시면 저희 팀에서 귀하의 계정을 확인하고 문제를 조사할 수 있습니다. 저희 행복엔지니어가 최대한 빠르게 답변해드리겠습니다.

감사합니다!

---

The reply above was translated from English (below) using Google Translate:


`Thank you for reporting this issue that occurred when you tried to contact support regarding your payments. In order to get specific help with your question regarding your payments, please email our support team directly at help@wordpress.com.  Please send your email using your WordPress.com account email address, that way our team can verify your account and investigate the issue.  Our Happiness Engineers will respond to you as soon as possible. `

`Thank you!`

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Unable to replicate; on a free site, I asked a question via the Help Center, waited for the AI suggestion, then posted to Forums, and it published my question as expected:

https://github.com/Automattic/wp-calypso/assets/27249804/43c68f03-0e24-41fd-9b94-21fa4c23cabb

📌 ACTIONS
- Closed as could not replicate
- Asked reporter to contact WordPress.com Support by email (above)

**Comment by infott2t** [comment]
Let's safely use smartphones, etc. 😁😊; 스마트기기. 안전하게 사용합시다. 😁😊
Long sentences. ; 장문이네요. ...

 서비스, 감사드림니다. Blaze광고. 대금납부는 되었네요. 하지만, 처음에 결제될때 스마트폰에 문자메세지라던가 해서 결제 실패, 결제성공 메세지가 나오면 편할 거라고 생각해보네요. 나중에 표시가 되기 때문에... 실제 대금이 나중에 결제된다라는 메세지가 표시되거나 했다면, 이런 일은 없었겠죠. 

 제가 돈이 있어서, 다행이였지만, 없었다면, 카드사에 전화해서 정지해달라고 다시 이야기했을 것이구요~.
 좋은 하루되세요~. 

 또, 회식. 어떤가요. 해보세요. 잘 쉬고 일도 더 잘 되겠죠. 또, 교회. 다녀보세요. 기독교. 전화도 해보세요. 사회에서 쉴 곳. 하고 싶은 말이네요.

저의 글, 봐 주셔서 감사합니다.
