### ISSUE TITLE
Built by WordPress.com: currencies used for pricing are inconsistent

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#81191]
### Quick summary

When going through the start of the purchase flow for Built by WordPress.com, pricing is shown in different currencies if you're outside the US.

I am a user based in New Zealand, and we usually see prices in AUD$. On the main Built by WordPress.com page, I see the price for Express in AUD, but the non-Express version is priced in USD:

https://wordpress.com/website-design-service/#get-started

<img width="1226" alt="Screenshot 2023-08-30 at 10 28 11 AM" src="https://github.com/Automattic/wp-calypso/assets/17325/2b51fe1e-16c7-4775-bd69-571af41bf142">

As an added complication, if I continue through to buy Express it uses the currency specified in my WordPress.com account, which for me is GBP (because that's where I lived when I created my WordPress.com account):

https://wordpress.com/start/do-it-for-me/new-or-existing-site?ref=do-it-for-me-lp

<img width="1138" alt="Screenshot 2023-08-30 at 10 28 18 AM" src="https://github.com/Automattic/wp-calypso/assets/17325/a08598ed-0b25-49b0-8d4f-936436b3c6c0">

So at this point I've seen 3 different currencies! It would be great if we could be consistent in our display and settle on one.

### Steps to reproduce

1. Browsing from outside the US, visit https://wordpress.com/website-design-service/#get-started. Note that the Express price and non-Express price are in different currencies.
2. Set your user account currency to something different entirely, and click 'Get Started Now'. Note that the currency shown reflects your user account currency, and may be different from the other currencies you've already seen.

### What you expected to happen

I see all prices in one consistent currency.

### What actually happened

I saw 3 different currencies.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested in Sweden, Japan - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Confirmed in a few locations that the Express price updates to the local currency, while the Built By price remains in USD:

**Sweden**
![Screenshot on 2023-08-30 at 08-59-42](https://github.com/Automattic/wp-calypso/assets/27249804/addc5fd9-268d-4f07-a1c7-6505e88e99cf)

**Japan**
![image](https://github.com/Automattic/wp-calypso/assets/27249804/808c43b2-9446-45ab-8922-db635e9ad081)

I imagine this is intentional, but it does look like an error with the prices right next to one another.  Perhaps we could note that the full scale price quote starts in USD somehow - or hide it behind a warning that quotes there will appear in USD as an estimation, so the user has to click that to see the $5k price or something 🤔 

📌 ACTIONS
- Triage complete
- FYI @Automattic/martech

**Comment by dzver** [comment]
I don't think this is a bug, I believe it's done on purpose.

CC @Lochlaer for clarification

**Comment by southp** [comment]
I've called that out once in a p2 and from what I recall it was @peterschimke who clarified that it was intentional for me. 
Since this looks naturally off, I believe ths same ticket will be submitted again sooner or later. How can we better communicate that at least internally so the team won't have to clarify this repetitively?

**Comment by cuemarie** [comment]
Thanks @southp & @dzver - I noted in my triage notes as well that this doesn't look like a bug, and labeled it a Feature Request instead.  

>How can we better communicate that at least internally so the team won't have to clarify this repetitively?

One option is we can keep this issue open as as a tracking thread for feature requests if customers reach out to support confused about the currency. 

Would we ever consider noting the currency in USD as intentional on the landing page itself?  For instance, we could note that the full scale price quote will only show in USD - or even hide it behind a warning that prices there will appear in USD as an estimation, so the user has to click that to see the $5k price?

**Comment by southp** [comment]
> Would we ever consider noting the currency in USD as intentional on the landing page itself? For instance, we could note that the full scale price quote will only show in USD - or even hide it behind a warning that prices there will appear in USD as an estimation, so the user has to click that to see the $5k price?

Intriguing. Maybe for non-US customers we can just add that to the existing copy which explain that all services will be provided in English:
<img width="1070" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1842898/7e0d8ca1-a852-4932-82d8-470eba18b4ab">

**Comment by bluefuton** [comment]
If the $5k is a project minimum/starting price, what's stopping us from showing that in the local currency?

I know roughly what 1 USD:NZD is, but I think it's a mistake to send users off to to do the conversion if we don't have to.

**Comment by peterschimke** [comment]
> If the $5k is a project minimum/starting price, what's stopping us from showing that in the local currency?

We have discussed this previously with the team and decided not to show anything else than USD the Built By, as we won't provide quotes / invoices in anything else than USD. I believe conversions to USD and conversion fluctuations were part of that reason. In any case, I will highlight this to the team again.

**Comment by cuemarie** [comment]
> Maybe for non-US customers we can just add that to the existing copy which explain that all services will be provided in English

I like that!  I definitely think this would help address the unnecessary reports, and sets up the right expectations for customers looking into the service!

**Comment by Lochlaer** [comment]
Sorry, I thought I had replied to this!

Thanks for the ping. If there are a lot of customer complaints about this, then yes, please do add some language letting visitors know that currently Built By WordPress.com custom projects are only available in USD currency. Maybe something like:

> Custom Built By WordPress.com projects are available to customers with content in any language. However, please note that all communications throughout the project are in English only at this time. Payments are only accepted in USD currency. 

cc @peterschimke

**Comment by gikaragia** [comment]
Seems like this one is fixed:
![Screenshot 2024-09-03 at 15 18 27](https://github.com/user-attachments/assets/f077d281-84c8-4ba4-a1d7-412d03530e58)
