### ISSUE TITLE
Domain Forwarding: Allow forwarding to the same domain

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#81323]
We have [previously blocked redirects to the same domain](https://github.com/Automattic/wp-calypso/pull/80665) to avoid infinite loops. Since allowing users to redirect a subdomain to a specific page on their domain is a highly requested feature from HEs, now it's time to support it.

Feature request for more context: pb5gDS-3ig-p2#comment-4068

![Image](https://github.com/Automattic/wp-calypso/assets/1044309/479734a6-209d-4404-a069-7c44d4006d3f)

### Acceptance criteria:

- [ ] We still want to block redirects from the main domain to the same domain
- [x] Allow subdomain redirects to the main domain or a sub-path of it

**Comment by candy02058912** [comment]
> We still want to block redirects from the main domain to the same domain

@paulopmt1 would like to clarify, does this mean we should also block:
`example.com -> example.com/somepath`?

In the case of the subdomain, should we block:
`sub.example.com -> sub.example.com/somepath`

**Comment by paulopmt1** [comment]
> > We still want to block redirects from the main domain to the same domain
> 
> @paulopmt1 would like to clarify, does this mean we should also block: `example.com -> example.com/somepath`?
> 
> In the case of the subdomain, should we block: `sub.example.com -> sub.example.com/somepath`

If those redirects don't create infinite loops, which I believe is not the case, it would be great to allow them.

**Comment by candy02058912** [comment]
Context: p1694099373218399-slack-CKZHG0QCR

Conclusion: We want to be more specific on what we'd like to allow for forwarding.

I'd like to propose that we allow domain forwarding to itself and parent address(es).
~Same level or more would not be allowed.~ UPDATE: Same level is allowed. More is not.

For example:
* ✅ a.b.com -> a.b.com/path (itself, make sure there's a path attached)
* ✅ parent a.b.com -> b.com or b.com/path (forward to parent)
* ~❌ a.b.com -> www.b.com (same level)~ **UPDATE**: ✅ a.b.com -> www.b.com (same level)
* ❌ a.b.com (3 levels) -> c.a.b.com (4 levels)

Another example
* ✅ b.com -> b.com/path (itself, make sure there's a path attached)
* ❌ b.com (2 levels) -> www.b.com (3 levels)
* ❌ b.com (2 levels)-> a.b.com (3 levels)

This can prevent us from bumping into https://github.com/Automattic/dotcom-forge/issues/3493#issuecomment-1681126767 where the infinite loops are caused by b.com -> www.b.com -> (WordPress settings to naked URL) b.com

**Comment by candy02058912** [comment]
Update for the same level, we will allow due to the complexity of the logic, it's really hard to check whether the domains are related, for example:

if `d.e` is a second-level domain e.g. `co.uk`:
`b.co.uk` and `c.co.uk` are NOT related

if `e` is a TLD
`b.d.uk` and `c.d.uk` are related due to `d.uk`

We will leave it up to the users to set the correct forwarding.

**Comment by allilevine** [comment]
Diff to review: D121450-code

**Comment by DustyReagan** [comment]
> Update for the same level, we will allow due to the complexity of the logic, it's really hard to check whether the domains are related, for example:
> 
> if `d.e` is a second-level domain e.g. `co.uk`: `b.co.uk` and `c.co.uk` are NOT related
> 
> if `e` is a TLD `b.d.uk` and `c.d.uk` are related due to `d.uk`
> 
> We will leave it up to the users to set the correct forwarding.

I'm still catching up on the logic, but would it be helpful to remove the TLD from the comparison? We have some functions like `get_subdomain_part`, `get_tld`, and `get_base` in `WPCOM_Domain`.

**Comment by candy02058912** [comment]
Thanks for the extra information @DustyReagan, should have looked more into `WPCOM_Domain`.

That being said though, I think what we have in the diff is good enough for now as it fulfills the goal of the issue (pb5gDS-3ig-p2#comment-4068), as I feel like the cases we're trying to cover more than what's mentioned above seem like edge cases.

If you have any thoughts on this we can still update the code further though (just wondering if I'm spending too much time here).
