### ISSUE TITLE
Editor: "Edit Link" option can be very slow in some cases

### ISSUE THREAD

**Issue by MicBosi** [Automattic/wp-calypso#8132]
- open a website with many articles as in ticket below
- open a post for editing
- select a word
- click on the "edit link" button
- while the list of articles gets populated the website and link editor becomes unresponsive
- doing the same thing in wp-admin on the same website does not cause any problem and the list of articles is populated visibly faster

Problem reported by user here 2835199-t and confirmed on my laptop as well (i7-6700HQ, 16GB, Linux, Chrome).

**Comment by lancewillett** [comment]
This would be a great candidate for profiling in Chrome dev tools to see where the delay is happening.

**Comment by aduth** [comment]
I suspect this should be dramatically improved as of #9725, since we were decoding both titles and post types of all items in the list.

I'm also working on an upgrade to our `react-virtualized` dependency from 7.x to 8.x, which will help performance as noted in https://github.com/bvaughn/react-virtualized/issues/386 .
