### ISSUE TITLE
Cover Block: Unable to accept videos in GB 16.5.1

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#81481]
### Quick summary

It should be possible to add either a video or an image file to the background of the Cover Block.  In my tests while it is possible to set background images without issues, videos are not recognized.  When setting a video in a new block (or editing  an existing cover block to accept a new video) the block shows no change once set.

### Steps to reproduce

1. add cover block to page (Page Editor) or template (Site Editor)
2. Click "Select Media" and choose a video file from the media library or upload one from your computer
3. Click "Select" button to set background

### What you expected to happen

Video to show within the background of the block

### What actually happened

Empty block.  Background appears to be unset.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I noted several errors in the browser console while testing.  I've included a screencast here that shows me trying to set a video on a test site, and the errors shown

https://github.com/Automattic/wp-calypso/assets/1967448/b9acd7b7-d29f-4a2e-be72-bc9898336f1a

**Comment by jerrysarcastic** [comment]
Reported in https://wordpress.com/forums/topic/cover-module-not-accepting-new-videos/

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated** 
- Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described on Simple and AT, as well as Self-Hosted using **Gutenberg 16.5.1**:

### Atomic Site

- Gutenberg: v16.5.1 
- All other non-must-use plugins inactive

https://github.com/Automattic/wp-calypso/assets/27249804/fb30c457-5d4e-4c3b-b783-368ee8942cee

Console errors from AT site:

```
Uncaught (in promise) Error: FastAverageColor: Error loading image "https://videos.files.wordpress.com/1xaQFT8q/pexels-videos-979689.mp4".
    Hr index.esm.js:332
    l index.esm.js:481
```

---

### Simple Site

- Gutenberg: v16.5.1
- Editing Toolkit: 3.77181
- WP AMP: 2.0.5
- CoBlocks: 2.18.1-simple-rev.4

```
Uncaught (in promise) Error: FastAverageColor: Error loading image "https://mcqtestpremiumplan.files.wordpress.com/2023/06/pexels-zlatin-georgiev-5607993-1080p.mp4".
    Hr https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.5.1/build/block-library/index.min.js?m=1693328653i&ver=0e03f723a79477c38e5d:24
    l https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.5.1/build/block-library/index.min.js?m=1693328653i&ver=0e03f723a79477c38e5d:24
```

On Gutenberg 16.6.0 on my Self-hosted site and on AT, the issue is not present:

https://github.com/Automattic/wp-calypso/assets/27249804/4a10e484-e510-4649-b28e-68e3ca4b97b6

---

📌 ACTIONS
- Triage complete

📌 Message to HEs
Looks like this should be resolved as 16.6.0 rolls out to WordPress.com sites in the next few hours!

**Comment by hacchism** [comment]
Another report: 6780347-zen
User wants an update once the issue has been fixed.

**Comment by hacchism** [comment]
Gutenberg 16.6.0 has been rolled out to simple sites, and I can confirm that the issue is no longer present for simple sites. I went ahead and followed up with my user - 6780347-zen

**Comment by csabarakasz** [comment]
Atomic site report 6781072-zd-a8c

**Comment by ccwalburn** [comment]
Atomic site report 6782642-zd-a8c

**Comment by cuemarie** [comment]
Thanks @hacchism ! Atomic sites should be updating to GB 16.6.0 soon, and that'll resolve things for the remaining Atomic Site owners.

**Comment by cuemarie** [comment]
Tested today and confirmed this is working on AT as well - closing out!
