### ISSUE TITLE
Jetpack Backups don't run when an Atomic site's storage is full

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#81490]
### Quick summary

When an Atomic site has maxed out its storage, backups do not run. Apparently, when Jetpack tries to upload the helper script (the thing that fetches data from the site), it is unable to because there is no more space for it, thus the backup cannot run.

Could we perhaps adjust the storage to leave enough storage to upload the helper script? 

Related Slack Conversation - p1693970297136969-slack-C03TY6J1A
Related Documentation Update Request - 84-gh-Automattic/reactor

### Steps to reproduce

1. Max out the storage on an Atomic Site
2. Look at the rewind debugger to see error messages and issues with "Full Backup Attempts"

### What you expected to happen

I would expect that our backups would still run even with storage maxed out. 

### What actually happened

Storage gets maxed out and there is no error message on the user's end indicating that backups are not happening because of a storage issue. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Did not reproduce - this looks to be pretty consistent across user experiences 
- Not sure if this is a bug or working by design; I recall there are a few issues that arise when sites max out their storage. If this behavior is expected, then we can adapt this report to an Enhancement request for this suggestion:

> Could we perhaps adjust the storage to leave enough storage to upload the helper script?

📌 ACTIONS
- @jeherve pinging you in case there's any insight / help Jetpack can offer here.

**Comment by jeherve** [comment]
cc'ing @Automattic/yamato-backup who may know more.

**Comment by pypt** [comment]
It is indeed accurate that we upload a PHP helper script, and later we talk to it over HTTP/SSH to get the backup/restore going.

Let us at @Automattic/yamato-backup know if you have any questions.
