### ISSUE TITLE
Footer Credit: Paragraph Block tied to Footer Credit should be locked

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#81611]
### Quick summary

With FSE theme, you can edit the Paragraph Block tied to Footer Credit. However, the change never gets reflected to a live site. This confuses users.

We should lock the Paragraph Block so it's clear that the block shouldn't be edited. And ideally, we can show a prompt to head to Customize > Site Identity > Footer Credit to change the footer credit option. 

### Steps to reproduce

1. Create a simple site.
2. Switch to any FSE theme (i.e. Livro that I tested with)
3. Go to Appearance → Editor → Patterns → Footer 
4. Find the existing Paragraph Block that is tied to Footer Credit and add any text into it and save the change

![Screen Shot on 2023-09-12 at 09:05:05](https://github.com/Automattic/wp-calypso/assets/32432463/144e6d33-36fa-4fc8-940a-440a3daf0113)

### What you expected to happen

A normal user would expect the change to be reflected on their live site.

### What actually happened

No change. Only the Footer Credit selected in Customize > Site Identity > Footer Credit shows up. 

![Screen Shot on 2023-09-12 at 09:05:58](https://github.com/Automattic/wp-calypso/assets/32432463/1b7791a9-dd17-40e4-aee8-8c546bc5a71a)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
AFAIK, it's by design that the footer credit set in the customizer overrides the block one, but this definitely results in a confusing experience for users who have full ability to edit the footer credit in the Site Editor.

https://github.com/Automattic/wp-calypso/assets/27249804/43566c8e-3305-4fdc-957a-a9962221c5bc

- Related: https://github.com/Automattic/wp-calypso/issues/59363

📌 ACTIONS
- We've never had the Footer credit block locked from edits, since the Customizer overrides it, so I've changed this to a Feature Request type instead.
- Feature Request kept

**Comment by cuemarie** [comment]
Did a little further research into the Footer Credit on Templates - looks like there was work being put into a better solution that was ultimately put on hold, here: https://github.com/Automattic/view-design/issues/244

**Comment by mmtr** [comment]
This shouldn't be needed as of D156044-code (Simple sites) and https://github.com/Automattic/jetpack/pull/38458 (Atomic sites).
