### ISSUE TITLE
Notifications: mobile view header moves

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#8173]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Click Notifications tab
3. Scroll
#### What I expected

The "header" where you can filter notifications should stay at the top
#### What happened instead

The "header" keeps going up and down
#### Browser / OS version

iPhone 5C Safari iOS 9.3.1
#### Screenshot / Video

![slack for ios upload](https://cloud.githubusercontent.com/assets/1158819/18767761/ee6eaff0-80d5-11e6-8eab-19d0e830944b.jpg)

Found by @karenalma

**Comment by lancewillett** [comment]
Would love a 2nd opinion on this — I cannot reproduce on iPhone 6 Plus, iOS 10.

**Comment by ryanboren** [comment]
I can reproduce this on an iPhone 5. I can't get a screenshot because this phone has a broken home button and I can't pin scroll in place while using AssistiveTouch to screenshot. With Calypso on iOS, if you don't see the problem at first, keep going. Tap around. As state piles up, weird things start happening. #tap-bleed, #scroll-bleed, and #cursor-bleed become more frequent, as do things like bar detachment.

Even with fresh state, the filter header jitters while scrolling notifications. This jitter has existed on iOS for the life of Calypso.

#scroll-bleed is pervasive in Calypso and is featured in Notifications.

https://test.wordpress.com/tag/scroll-bleed/
https://test.wordpress.com/tag/cursor-bleed/

**Comment by ryanboren** [comment]
You don't need an iPhone 5. This can be reproduced on any iOS device and has been a fact of life for iOS users for the entire existence of Calypso.

iPhone 7+:

![img_1462](https://cloud.githubusercontent.com/assets/2047747/19702127/e0ad6534-9ac3-11e6-88d8-9f655f491f64.PNG)

**Comment by lancewillett** [comment]
Thanks for the follow-up notes @ryanboren.

**Comment by ryanboren** [comment]
https://test.wordpress.com/2017/03/24/calypso-on-ios-the-big-impact-of-little-interaction-problems/

**Comment by ryanboren** [comment]
See also:

https://github.com/Automattic/wp-calypso/issues/12671
