### ISSUE TITLE
Assembler - Metrics - Analyse why funnels are commonly broken to find ways to prevent that

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#82107]
## What

Analyze why funnels are commonly broken to find ways to prevent that.

## Why

When we change event names the funnels must be updated too. We should prevent breaking funnels and check them regularly.  

## How

For instance: Can we use a prop with the key `assembler-theme` rather than expecting `pub/creatio` or `pub/blank-canvas-3`?

We already did something like this using generic events like `calypso_signup_pattern_assembler_screen_back_click` and `calypso_signup_pattern_assembler_screen_continue_click` with props `screen_from` and `screen_to`.

**Comment by autumnfjeld** [comment]
Is this an issue we can actually work on?   I think the real solution to this is that we have a set of our key funnels and we are checking and reporting on these regularly.  

Otherwise I don't think there is a technical fix for funnels in particular.

I'd close this.

But also noting that I have asked about implementing unit tests for tracks events.   Someday I hope this happens.
