### ISSUE TITLE
Reader: Comment textfield doesn't show up for Discover posts

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8216]
I've noticed this happen:

- On Discover posts only
- In Chrome and FF
- Posts with zero comments

Refreshing the browser doesn't fix it as well.

![screenshot 2016-09-26 17 27 06](https://cloud.githubusercontent.com/assets/4924246/18856294/780c0704-840e-11e6-8e05-2b49e870b60a.png)

Example post: https://wordpress.com/read/feeds/41325786/posts/1167388432

**Comment by fraying** [comment]
Confirmed in Safari, too.

![screen shot 2016-09-26 at 5 32 09 pm](https://cloud.githubusercontent.com/assets/24388/18856399/2c9a2e9e-840f-11e6-9c04-db3bff8be3b3.png)

**Comment by ivantedja** [comment]
See [this line](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/comments/form.jsx#L174)

```
// client/blocks/comments/form.jsx
//...
// Don't display the form if comments are closed
render() {
    // ...
    if ( post && post.discussion && post.discussion.comments_open === false ) {
        // If we already have some comments, show a 'comments closed message'
        if ( post.discussion.comment_count && post.discussion.comment_count > 0 ) {
            return <p className="comments__form-closed">{ translate( 'Comments are closed.' ) }</p>;
        }

        return null;
    }
    // ...
}
//...
```

I believe the `post` information is retrieved by accessing WordPress API and the API return `false` for `post.discussion.comments_open`. It seems that the issue is on the API.

Samples API:
- [comments closed](https://public-api.wordpress.com/rest/v1.1/read/sites/53424024/posts/17848?http_envelope=1)
- [comments open](https://public-api.wordpress.com/rest/v1.1/read/sites/28097921/posts/1993?http_envelope=1)

**Comment by bluefuton** [comment]
Thanks for investigating @ivantedja!

There's some special logic for Discover posts that is applied elsewhere using the `shouldShowComments` helper:

https://github.com/Automattic/wp-calypso/blob/master/client/blocks/comments/helper.jsx#L7

It looks like we need to account for Discover posts here, too.

**Comment by ivantedja** [comment]
@bluefuton thanks for the explanation!
