### ISSUE TITLE
can't view the website on server

### ISSUE THREAD

**Issue by gclsoft** [Automattic/wp-calypso#822]
on centos server: `wp-calypso booted in 1230ms - port: 3000`
but I can't open it on my local network:
http://106.186.125.245:3000/  failed

**Comment by gclsoft** [comment]
ok by run again: `make run`
But why it it empty?

**Comment by Viper007Bond** [comment]
You must view the site from `calypso.localhost:3000`, not `localhost` or the computer's IP address. This is necessary, because when running locally Calypso is using the remote version of the WordPress.com REST API, which allows only certain origins via our current authentication methods.

If you add `106.186.125.245 calypso.localhost` to your `hosts` file, it should work fine.

For details, see https://github.com/Automattic/wp-calypso/blob/master/docs/install.md

**Comment by gclsoft** [comment]
I've added 106.186.125.245 calypso.localhost to  hosts file now. But still emtpy

**Comment by gclsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/1269898/11416207/5af29e48-9446-11e5-9185-ee546a98ce14.png)

**Comment by Viper007Bond** [comment]
The URL in your address bar needs to be http://calypso.localhost:3000/ for it to work.

**Comment by gclsoft** [comment]
But my server doesn't have UI or web browser. I can't visit http://calypso.localhost:3000/.

**Comment by Viper007Bond** [comment]
Edit your local machine's hosts file, not your server's. ;)
