### ISSUE TITLE
Incorrect Link on the Account Recovery Form

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#82274]
### Quick summary

The [account recovery form](https://wordpress.com/wp-login.php?action=recovery) has a link to an incorrect support doc:

<img width="534" alt="Screenshot 2023-09-27 at 6 23 06 pm" src="https://github.com/Automattic/wp-calypso/assets/30727666/17801b17-8fad-4c80-ad47-6c424a6403b4">

### Steps to reproduce

1. Visit the account recovery form: https://wordpress.com/wp-login.php?action=recovery
2. Click "here" in the opening text

### What you expected to happen

To arrive at https://wordpress.com/support/account-recovery/

### What actually happened

I arrived at https://wordpress.com/support/passwords/#account-recovery

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS

- **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO

The issue can be replicated exactly as described above. Clicking on the link redirects to `Change or Reset Your Password` support page instead of [Recover Your Account](https://wordpress.com/support/account-recovery/) page.
 
📌 ACTIONS

- Assigned to @Automattic/nomado 
- Triage complete

**Comment by delputnam** [comment]
I don't mind trying to figure this out at some point, but I'm curious why this was triaged to Nomado. I don't think we've ever worked on this part of the code before. 😅

**Comment by donalirl** [comment]
@delputnam I don't know 🤔 

An incorrect link seems important (and easy) to fix so I've reprioritized this from low to high.

**Comment by lupus2k** [comment]
Diff created: D131880-code

**Comment by lupus2k** [comment]
Merged 🚀

**Comment by donalirl** [comment]
Thank you @lupus2k! Looks perfect.
