### ISSUE TITLE
Can't disconnect Jetpack site if the domain now points to WordPress.com

### ISSUE THREAD

**Issue by koke** [Automattic/wp-calypso#8227]
I had a Jetpack test site (wp.koke.me) on a subdomain of koke.me, which is a domain managed on WordPress.com. I took the site down and removed the DNS entries. WordPress.com automatically sets wildcard entries so now `wp.koke.me` points to WordPress.com.

I tried going to the site settings in calypso to disconnect Jetpack, but I got an error:

![screen shot 2016-09-27 at 15 54 26](https://cloud.githubusercontent.com/assets/8739/18878155/e6dc5e74-84cf-11e6-88f3-101cdc8a9eec.png)

It looks like WordPress.com won't disconnect, since `http://wp.koke.me/xmlrpc.php` still responds (although it's wp.com who's responding).

When I recreated the DNS entries pointing somewhere else, I was able to disconnect the site.

**Comment by lancewillett** [comment]
CC @beaulebens for JPOP (Pit Crew?) to review.

**Comment by beaulebens** [comment]
@rickybanister this is another interesting edge case to be handled in your proposed disconnection flow.

@lezama maybe we could get some sort of "Force Disconnect" link added in to that error message for now, so that people can at least remove a site/kill a connection from our end if there's some sort of problem. It wouldn't do a complete disconnection (e.g. the remote site might still think it's connected?) but would kill it from our end as much as possible.
