### ISSUE TITLE
Gutenberg: pasting text inside table blocks does not work with version 16.6.0

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#82419]
### Quick summary

When Gutenberg 16.6.0 is active, it's not possible to paste text or inline images inside a table.

Text copied from other sources (like a different website) is pasted. It's only the text copied from the same page/post in Gutenberg that can't be pasted inside the table.

### Steps to reproduce

1. Open the page/post editor.
2. Create a table.
3. Type some text.
4. Select and copy the text.
5. Paste the text inside a table cell.

### What you expected to happen

The text should be pasted.

### What actually happened

Nothing is pasted.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Workaround (only for Atomic sites): deactivate the Gutenberg plugin.
- Self-hosted not tested.

**Comment by ariel-maidana** [comment]
Please let the user know once a fix has been released: 7102716-zd-a8c

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated / Could Not Replicate / Uncertain
- Tested on P2 (optional) – Replicated / Could Not Replicate / Uncertain
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described on self-hosted site with GB 16.6.0 and GB16.5.1 as well, however it appears to be resolved in v16.7.0.

Also, another **workaround** is to right-click > `paste without formatting`, as shown below.

**Self-Hosted** - Gutenberg v16.6.0 (replicated issue)

https://github.com/Automattic/wp-calypso/assets/27249804/ec752568-c475-469c-93cf-2df0d6adaab5

**Self-Hosted** - Gutenberg v16.7.0 (error not present)

https://github.com/Automattic/wp-calypso/assets/27249804/75c7e257-3edf-4111-a3dc-5c9ff844dc3d

📌 ACTIONS
- Lowered in priority given the fix is on its way already with 16.7

📌 Message to Author
@ariel-maidana this issue very likely will not receive a batch reply, but if you'd like, you can let the user know that a fix will reach their site with the next upgrade to Gutenberg (to 16.7.0), and in the meantime, they can use the easier workaround of pasting without formatting. Thanks!

**Comment by ariel-maidana** [comment]
Thank you @cuemarie ! I've let the user know.

**Comment by annezazu** [comment]
Closing this out as the issue was resolved quite a while ago in Gutenberg and I can no long replicate.
