### ISSUE TITLE
Signup: Back bar at bottom of page seems off

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#82555]
### Quick summary

https://github.com/Automattic/wp-calypso/assets/1126811/eac800fb-efd7-4b09-9bbf-119ed281ec27

There are several things wrong with this flow:

- The back button loses context and mentions site when I click it on the domains step
- The back button doesn't work when I click it twice on the domains step
- The back button panel doesn't seem centered, which looks really off on the plans grid.

This whole thing just feels out of place.

### Steps to reproduce

1. Start at wordpress.com/start and go through flow

### What you expected to happen

See summary

### What actually happened

See summary

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Started from logged out WordPress.com/start/user. The Back button at the domains step directs to `WordPress.com/sites`, which took multiple tries for me; and then it was confusing from there getting in and out of the site creation flow.

https://github.com/Automattic/wp-calypso/assets/27249804/0ff0d715-49eb-4f52-b3ef-7b84b809d5a3

📌 ACTIONS
- Triaged

**Comment by gmovr** [comment]
![Screenshot 2023-10-04 at 02 16 47](https://github.com/Automattic/wp-calypso/assets/52675688/8164faee-c9b7-4092-85df-52db7d834fa6)

Then clicking it won't do anything useful because the URL is set wrong inside the `StepWrapper` component. When clicking it, the same step loads again, and the URL is now changed, and also the CTA text.

![Screenshot 2023-10-04 at 02 19 10](https://github.com/Automattic/wp-calypso/assets/52675688/0701323b-091c-4b8c-9dcf-0737559ece08)


Some issue with `backUrl` and `allowBackFirstStep`, but I can only replicate it if the previous URL is the user step. https://github.com/Automattic/wp-calypso/blob/0e2ab5355b8b5f51ef6eacda8cbb119b33e6f0e6/client/signup/steps/domains/index.jsx#L861

**Comment by lsl** [comment]
Just passing through while looking at another back button issue.

Positioning fix from @candy02058912 is coming soon in https://github.com/Automattic/wp-calypso/pull/82558

**Comment by lsl** [comment]
This back button is no longer present.
