### ISSUE TITLE
Reader: RP displays image only for a second

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8259]
In this example: http://calypso.dev:3000/read/feeds/24643651/posts/1167317410, the RP image flashes for a second then disappears.

![screenshot 2016-09-27 15 39 07](https://cloud.githubusercontent.com/assets/4924246/18894566/8f9bb68e-84c8-11e6-8ea0-0bfffc35be8d.png)

Video: https://cloudup.com/carcP6qgWVv

**Comment by aaronyan** [comment]
I think this is because the [picture does not meet the size requirements to be shown as a thumbnail/preview](https://github.com/Automattic/wp-calypso/blob/48d0ccba541ba90c3363834e6b6472d36c8ea049/client/lib/post-normalizer/rule-pick-canonical-image.js#L19): width > 350px (the picture is 275 x 275 ).

@blowery, @bluefuton is there a way to prevent the flash? check size requirement then render?

**Comment by fraying** [comment]
> check size requirement then render?

Oh yes please.

**Comment by jancavan** [comment]
Related to image size requirements, a user mentioned his post images flash for a sec then disappear - although it's not in their RP, but in their stream: https://wordpress.com/read/blogs/69641322

Video: https://cloudup.com/chVJMjOzcft

Reported by: @supernovia

**Comment by eduardozulian** [comment]
Another report of the same image flashing issue is shown here: https://wordpress.com/read/feeds/141512

![reader-flash](https://cloud.githubusercontent.com/assets/1136160/19137310/b050a7e4-8b27-11e6-910d-58538c0c89eb.gif)

Reference: 2857025-t

**Comment by samouri** [comment]
I believe the image flashing problem that this issue is talking about has been solved with the normalization changes we've made in the past couple of months. at least I haven't been able to repro this while testing right now

We still have a flashing problem related to galleries https://github.com/Automattic/wp-calypso/issues/9487

**Comment by fraying** [comment]
👍
