### ISSUE TITLE
Varying Page Title Fonts and Sizes

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#82607]
### Quick summary

Clicking through Calypso screens shows a lot of inconsistencies in how the H1 titles are styled:

https://wordpress.com/email/SITE/manage/DOMAIN:
<img width="1127" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/ba7f3d48-7494-43f4-9817-329b6f411e61">

https://wordpress.com/purchases/subscriptions/SITE:
<img width="1123" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/66df8753-fc36-45db-95e4-ad4438371512">

https://wordpress.com/domains/manage/SITE:
<img width="565" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/9f58a88a-8b8c-461f-a433-0ec5721ec1d6">

https://wordpress.com/add-ons/SITE:
<img width="1127" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/def244fe-02f3-42a0-a130-63784a196985">

https://wordpress.com/stats/SITE: (smaller font size)
<img width="566" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/f36895e7-d7b2-41dd-8b24-825d567d41e3">

https://wordpress.com/plugins/SITE: 
<img width="1125" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/130d2a5e-ddc9-4b10-a222-e9aa95cb52ed">

https://wordpress.com/themes/SITE: 
<img width="1129" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/7b143648-096e-4efd-aff3-22256ce8c87b">

https://wordpress.com/subscribers/SITE:
<img width="1127" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/761bfebc-1c37-48ad-8580-6225df99ef89">

https://wordpress.com/advertising/SITE:
<img width="1131" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/36fb6692-a2fc-4459-82ab-f6bd39f3a034">

### Steps to reproduce

Click through Calypso

### What you expected to happen

The titles to look the same	

### What actually happened

The look differently

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by obenland** [comment]
@saygunnyc Should these look all like the top two examples?

**Comment by saygunnyc** [comment]
> @saygunnyc Should these look all like the top two examples?

I am so so ... happy to see this, as we've spent quite some time aligning these with the Dotcom Design team. 
Here is the perfect P2 for this – p9Jlb4-8ec-p2 by @nuriapenya.

**Comment by nuriapenya** [comment]
@obenland, our idea would be to use the newer version of the headers (subscribers, plugins, ad-ons) but with some alignment and tweaks. 

In the P2 that @saygunnyc shared above, there's a handover for the design: eqlepL7MHifK8Bgr1OWqLr-fi-9617_46248. I'd be happy to be the DRI for this project & follow up with engineering. 

Thanks for rising the issue! ✨

**Comment by allilevine** [comment]
> In the P2 that @saygunnyc shared above, there's a handover for the design: [eqlepL7MHifK8Bgr1OWqLr-fi-9617_46248](https://href.li/?https://www.figma.com/file/eqlepL7MHifK8Bgr1OWqLr/?node-id=9617-46248). I'd be happy to be the DRI for this project & follow up with engineering.

@nuriapenya Thanks for sharing this! How would you prefer to work together? Should we start work and check in with you? Or would a sync meeting with Explorers be helpful?

**Comment by allilevine** [comment]
I took a look at each of these headers and most are using one of three components: `FormattedHeader`, `FixedNavigationHeader`, or `NavigationHeader`(we added this one recently for Domains, it's supposed to replace `FixedNavigationHeader`). The exception is Themes, which seems to be using [its own component](https://github.com/Automattic/wp-calypso/blob/67818413a930adeb163255aeb456cc315443ba59/client/my-sites/themes/themes-header.tsx). There may also be custom CSS / props causing variations.

We can consolidate these to one component (or a combination of `FormattedHeader` and `NavigationHeader`). How will we enforce that going forward? 🤔 Through Design?

**Comment by lsl** [comment]
PT: pb5gDS-3rx-p2

**Comment by lsl** [comment]
`NavigationHeader` wraps `FormattedHeader` so those should be semi compatible. Likely a matter of going through each usage and replacing it with `NavigationHeader` and injecting the actions into it cleaning up any css we no longer need. 

`FixedNavigationHeader` - this looks a lot like `NavigationHeader`, guessing that was intentional. The strongest reason to keep this would be "needing" easy access to the search box during an infinite scroll through /plugins. Thinking we should just replace this with NavigationHeader and remove it. (Only plugins and a couple of other screens use it.)

Plugins and themes both have logged out views.

Plugins shows a header inside the content that is re-styled logged out. Logged in they have an extra header on top. We can update the logged in one to whatever we need.

I think we should do something similar for themes, add a new logged in only banner header to replace the existing one. Conditionally only show the existing on while logged out. We get new design but also don't have to over scope into logged out views.

**Comment by lsl** [comment]
Created: 
- https://github.com/Automattic/dotcom-forge/issues/4219
- https://github.com/Automattic/dotcom-forge/issues/4220
- https://github.com/Automattic/dotcom-forge/issues/4221
- https://github.com/Automattic/dotcom-forge/issues/4222

These are not small tasks and will require further breaking down as we go.

**Comment by nuriapenya** [comment]
> How would you prefer to work together? Should we start work and check in with you? Or would a sync meeting with Explorers be helpful?

Sorry @allilevine, I was AFK and just getting into this. I already wrote @lsl over Slack in case needed some design support I can be the DRI. Happy to test or revise any issue when necessary. You can ping me either here in GH or over Slack (or both), as you prefer :)

**Comment by allilevine** [comment]
@lsl Are we ready to close this issue in favor of https://github.com/Automattic/dotcom-forge/issues/4352?

**Comment by lsl** [comment]
There's a few people subbed here already, I was thinking to leave this open until the project is wrapped.

**Comment by lsl** [comment]
I've closed out https://github.com/Automattic/dotcom-forge/issues/4352 since we've shipped the main in scope issues.

Posted PT update and shipped the thread.

There are some remaining low priority issues on the board but I don't think these are worth distracting other priorities over. @allilevine I'll triage / close these out next week.
