### ISSUE TITLE
Settings: Advanced SEO: Can't see cursor after adding title format element from button

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#8290]
#### Steps to reproduce
1. Starting at URL: wordpress.com/settings/seo/$site
2. Choose one of the title format editor's buttons (e.g. "Site Name" or "Tagline" for the Front Page field)
3. Notice the element gets added to the field
4. Look for the cursor (it's actually on the right side of the newly-added element, but it cannot be seen)
#### What I expected

To see a flashing cursor to know it current location within the text field
#### What happened instead

The cursor cannot be seen, it seems to be covered by the style of the element just added
#### Browser / OS version

Chrome 53
#### Screenshot / Video

![wheres-the-cursor](https://cloud.githubusercontent.com/assets/933450/18923709/5d7c4f66-857b-11e6-8ced-a8a729513065.gif)
#### Context / Source
# manual-testing

**Comment by dmsnell** [comment]
strange @alexjgustafson - I tried reproducing on Chrome 53 in macOS and the cursor was blinking. it _was_ lined up on the edge of the token, but I could still see it. are you in Windows or Linux?

**Comment by alexjgustafson** [comment]
I'm on macOS Sierra, Chrome 53.0.2785.116
When cursor is on left of the added element I can see the blink, but not on the right.
Zoomed in:
![cursorgoodonleft-badonright](https://cloud.githubusercontent.com/assets/933450/18977383/da042aa6-8687-11e6-9478-1b8b394ab086.gif)

**Comment by dmsnell** [comment]
got it @alexjgustafson - it seems inconsistent when it does and doesn't show up, which threw me off

**Comment by Copons** [comment]
I've tried adding `border: 1px solid darken( $gray, 20% );` to the token [here](https://github.com/Automattic/wp-calypso/blob/master/client/components/title-format-editor/style.scss#L72).
It forces the cursor to blink white instead of gray and now it's definitely visible (_apparently always_ and on both sides of the token) on Chrome 54 / Windows 10, albeit 1 px off.

![screenshot 2016-11-11 17 29 04](https://cloud.githubusercontent.com/assets/2070010/20222157/815b1742-a834-11e6-97f6-20eeb4e80840.png)

![2453080029](https://cloud.githubusercontent.com/assets/2070010/20222559/110d55c0-a836-11e6-9192-b5bba70695a5.gif)

Looks good enough on Edge and Internet Explorer 11 too, but definitely needs a bit of testing on other browsers and especially on other OS.

As it's a one-liner that can be easily added via dev tools, maybe it would be more convenient testing it before opening a PR?

**Comment by dmsnell** [comment]
This hasn't trickled up in priority so I'm closing. Also, I'd really like to eliminate the draft-js-based editor anyway, as in #20181, if possible, where this issue would be covered by others.
