### ISSUE TITLE
Theme showcase: Make premium badge consistent for premium themes with style variations

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#83153]
### Description

When the current user is on a Free plan, previewing a theme with style variations will show different "badge" depending on whether the style is default or not:

|Default style (badge: "Premium") |Premium style (badge: "Upgrade")|
|-|-|
|<img width="341" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/58df5c76-4cc2-4f1c-a35d-99e23b5e3e6e">|<img width="339" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/fdf22b88-2880-4959-8687-553e4073fde8">|

I think it is confusing as in both scenarios, the user needs to upgrade.

I'd propose to use `Premium` in both contexts.

@Automattic/lego @Automattic/t-rex @lucasmendes-design

**Comment by fushar** [comment]
I just found out that on logged-out theme showcase, we also show that `Upgrade` CTA on non-default styles on premium themes, which does not make sense because the user is not even logged in 😄

**Comment by lucasmendes-design** [comment]
> I'd propose to use Premium in both contexts.

+1. 

> I just found out that on logged-out theme showcase, we also show that Upgrade CTA on non-default styles on premium themes, which does not make sense because the user is not even logged in 😄

Yep haha. Let's follow your suggestion and use Premium everywhere :)

**Comment by retnonindya** [comment]
> I'd propose to use Premium in both contexts.

➕ infinity. "Premium" already set folks reading it to, "oh, I need to upgrade to use that" but still give the feeling (illusion?) of choice. "I can choose to use Premium feature of not." 

"Upgrade" is more like a... ... "Order"? 🤔 I remember our Sales Bootcamp in WPCOM Happiness, hahah. The mentor said, "by default, customers usually say "no"." 

"Upgrade? No." (no-meme.jpg)

Thanks for your hard work, Ashar!

**Comment by Copons** [comment]
I don't have an opinion, just mentioning that we have been doing back and forth on this since the very beginning. 😄 

The last time, we changed Premium to Upgrade in the context of the Limited GS on Personal A/B (where "Premium" did not make sense).


I agree that Premium is the best option, at the same time I have (minor/negligible, at this point) concerns that we'll have to change it again at some point for whatever reason. 😄

**Comment by dsas** [comment]
> concerns that we'll have to change it again at some point for whatever reason. 😄

p1697059060539939/1697058527.504459-slack-C048CUFRGFQ

**Comment by autumnfjeld** [comment]
Change = job security 😆

**Comment by rcrdortiz** [comment]
>I think it is confusing as in both scenarios, the user needs to upgrade.
I'd propose to use Premium in both contexts.

I prefer using `Upgrade` since it indicates the action the user must perform in order to achieve his goal (use the theme or style variation). Besides that, if we go with `Premium` and change what plans have access to that theme or variation we will need to update the copies which leads to increased maintenance costs.

I'll open a PR for this using `Upgrade` instead unless there is a strong opinion against it.

**Comment by rcrdortiz** [comment]
> > I think it is confusing as in both scenarios, the user needs to upgrade.
> > I'd propose to use Premium in both contexts.
> 
> I prefer using `Upgrade` since it indicates the action the user must perform in order to achieve his goal (use the theme or style variation). Besides that, if we go with `Premium` and change what plans have access to that theme or variation we will need to update the copies which leads to increased maintenance costs.
> 
> I'll open a PR for this using `Upgrade` instead unless there is a strong opinion against it.

Thanks, @BogdanUngureanu for the feedback. We're using `Premium` instead of upgrade to avoid adding new logic that removes the upgrade badge once it's included in your plan. If we were to remove it we wouldn't be clearly communicating the value of the `Premium` plan. Once we implement the tiers project we'll need to create new Badges though, but it shouldn't be a problem.

**Comment by rcrdortiz** [comment]
These changes are now live.
