### ISSUE TITLE
Email verification link redirects to reader instead of where you created account

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#83182]
### Quick summary

After creating an account with a new email to comment on a site, you receive a verification link via email. It redirects to the Reader instead of the flow you were in.

The verification link has a `redirect_to` param. Reported here: p1697640711073149/1697634622.150289-slack-C029GN3KD

### Steps to reproduce

1. In incognito visit a page with a form ( atomic site )
2. You will get prompted to login
3. Clicking login, get's you to [WP.com](http://wp.com/) login page where I selected to create an account with email
4. I entered an unused email
5. I got asked to verify my email
6. Clicking the email verification link, landed me in Reader - The problem seems to be the URL of the verification link.

### What you expected to happen

To return to the same flow you were logging into.

### What actually happened

You end up in the Reader.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

To workaround, navigate back to the flow you were in.

**Comment by davemart-in** [comment]
Moving this to the Loop board

**Comment by holdercp** [comment]
I've investigated this issue and I believe it's resolved. After clicking the verification link, you are not taken to Reader but to your WordPress.com account, which makes sense to me given that you are verifying a new WPcom account.

The login screen for where you are trying to comment will also recognize that the account is verified and you are given the option to login, which will take you back to the same flow.

However, it appears the original issue that spawned this one is still occurring. It was only reported in Slack ( p1697634622150289-slack-C029GN3KD ) as far as I can tell, so I created an issue here: Automattic/bugomattic#213

I'm going to mark this as closed since this issue (being navigated to Reader after verification) is no longer happening.
