### ISSUE TITLE
Refreshed Fullpost: Discover Special CSS 

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8330]
Looks like we have a few more special case CSS things to fix for Discover: https://wordpress.com/read/blogs/53424024/posts/17529

Specifically, the full width image and the left side quote.

**Comment by kjellr** [comment]
Screenshot for reference:

![discover-story](https://cloud.githubusercontent.com/assets/1202812/18965205/380bef32-864a-11e6-8900-8962180237f5.png)

---

The issue is evident on scroll:

<img width="1440" alt="screen shot 2016-09-29 at 1 10 29 pm" src="https://cloud.githubusercontent.com/assets/1202812/18965211/3c9b9e26-864a-11e6-9c5a-ebddc576ffee.png">
