### ISSUE TITLE
Assembler Add a Page copy

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#83389]
This issue will capture all new copy for the Add a Page and enforce a copy review by @ianstewart  and @autumnfjeld 

## Copy tasks
- [x] Review of new copy on the Add a Page screen
- [x] Update to the CTA
- [x] Update to copy in the starting blank canvas 
- [x] Update copy per Arthur's comment https://github.com/Automattic/wp-calypso/issues/83389#issuecomment-1791821215
- [x] Update page order per Ola's p1699333907605599/1699321095.326379-slack-CRWCHQGUB
- [ ] Get review from @autumnfjeld or @ianstewart before strings go to translation

@Automattic/lego

**Comment by taipeicoder** [comment]
Change the button from the Styles screen to `Select pages` instead of `Save and continue`, as discussed in p1698810471670369-slack-CRWCHQGUB.

**Comment by taipeicoder** [comment]
We will probably also need to change the copy in the Activation screen, since we will be updating more than their homepage:

![Image](https://user-images.githubusercontent.com/13596067/279595273-90b58544-1fe3-46e9-a07c-bc66a188415a.png)

**Comment by arthur791004** [comment]
## Here are related copy for review:

### The educational copy on the large preview

Add the “Add additional site pages” copy to the bulleted list to let users know they can select other pages later. See https://github.com/Automattic/wp-calypso/issues/83379

| Screenshot | Current | Suggestion |
| - | - | - |
| ![image](https://github.com/Automattic/wp-calypso/assets/13596067/b37c4c18-7326-45a3-8b39-24abef450656) | 1. Select patterns for your homepage<br><br>2. Choose your colors and fonts<br><br>3. Continue to the Editor to customize content | 1. Select patterns for your homepage<br><br>2. Choose your colors and fonts<br><br>(New) **3. Pick additional site pages**<br><br>4. Continue to the Editor to customize content |

### The CTA on the Styles screen

| Screenshot | Current | Change |
| - | - | - |
| ![image](https://github.com/Automattic/wp-calypso/assets/13596067/3da34c26-6dde-40de-86e1-8647ca884183) | Save and continue | Change to "Add more pages" | 

### The description on the Activation screen

We will probably also need to change the copy in the Activation screen, since we will be updating more than their homepage. See https://github.com/Automattic/wp-calypso/issues/83389#issuecomment-1788497851 

| Screenshot | Current | Suggestion |
| - | - | - |
| ![image](https://github.com/Automattic/wp-calypso/assets/13596067/5d8e01fa-58fd-4f7f-8568-6025679104ef) | This will replace your homepage, but your content will remain accessible. Learn more. |  No change. |

### The Pages screen

| Screenshot | Current | Suggestion |
| - | - | - |
| ![image](https://github.com/Automattic/wp-calypso/assets/13596067/6061c205-6769-420c-b08d-a23eaf9ac403) | Heading: Add more pages<br><br>Description: We've included common pages in your website, but feel free to add more or change the current ones.<br><br>CTA: Save and continue | See slack convo with Ola [p1699333907605599/1699321095.326379-slack-CRWCHQGUB](p1699333907605599/1699321095.326379-slack-CRWCHQGUB)|

**Comment by autumnfjeld** [comment]
I'll have a look at this and confirm final copy.

**Comment by autumnfjeld** [comment]
This issue should also include changing the CTA copy, in addition to the other changes discussed above.

This is the copy it should be and it should match what we have in Figma Tv3pYqA3EcRfiXC31IxrXE-fi-2620:43422#610456059

![image](https://github.com/Automattic/wp-calypso/assets/5665959/1d36305d-2930-4d46-8a09-da835bde78e0)

**Comment by autumnfjeld** [comment]
Since this is merged https://github.com/Automattic/wp-calypso/pull/84036
We can close this issue.
