### ISSUE TITLE
Task: Generally enable Customer Home layout with site preview in right nav

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#83465]
### Details

As part of recent discussions, we want to show the site preview as part of the standard Customer Home layout that we show to all users, as opposed to just in cases where we show the Launchpad in Customer Home.

From a structural perspective, we should follow the same approach as for the Launchpad, where we show the site preview next to the primary card, as opposed to the current default layout where the right nav is shown below the primary card.

### Checklist

- [ ] Enable the site preview for internal users - we can either do this for staff users, or for users who are using the Automattic proxy
  * Note that this should take into account and work alongside the existing logic that shows the site preview for launchpads
- [ ] Once we have internal buy-in and testing, roll out the feature to users

**Comment by sixhours** [comment]
We found a fun bug that made implementing this on the back end more difficult. In short, every time I filtered all Simple and Atomic Pre Setup Views to add the site preview card, the wrong view for the site would be returned by the API (ie. a brand new site on the free plan seeing the `VIEW_RENEW_EXPIRED_PLAN` view instead of `VIEW_SITE_SETUP`).

@andres-blanco helped me track it down to what we think is an issue with a `switch` statement that determines whether a specific view is valid for a site. The switch statement was comparing the unfiltered array constant against the filtered view array, causing it to return the wrong view because the arrays did not match exactly.

We think we have a fix in D128072-code, switching on the `view_name` string rather than the whole array. This is a much simpler and more exact comparison on a value that is much less likely to change.

**Comment by sixhours** [comment]
Started a PR that adds the site preview to multiple views aside from Launchpad-enabled ones: D128092-code

This is gated to Automatticians and has logic that checks to see if we already have the card in the `tertiary.manage-site` area before adding it.

It will also need to be rebased when the bug fix in D128072-code ships.

**Comment by sixhours** [comment]
Question: Do we want to add the preview to staging sites, WP for Teams, or Desktop App views? I'm less familiar with these views so figured I'd double-check /cc @daledupreez

**Comment by sixhours** [comment]
Moving this back to Current Sprint for now since we're working with design to get feedback: p9Jlb4-9SL-p2

**Comment by daledupreez** [comment]
We rolled this out to all users in D136265-code on 2024-01-31, so I am going to mark this issue as complete.
