### ISSUE TITLE
The overall storage used is shown as zero in the media section

### ISSUE THREAD

**Issue by tiniacoleyba** [Automattic/wp-calypso#83516]
### Quick summary

The overall storage used for WordPress.com atomic sites media (business and eCommerce plans) is always shown as zero in the WordPress.com dashboard media section, even though the storage used is undoubtedly greater than zero. 
<img width="1261" alt="wpcom-atomic-overall-storage-used-not-correctly-computed-media" src="https://github.com/Automattic/wp-calypso/assets/45241190/bb4ecdbb-8d3a-466d-85f4-ace45e17159b">

Notice in the screenshot how the overall storage computation is shown as zero even though multiple videos are uploaded, and those amount to much more than 1GB. This bug is[ potentially related to this other bug](https://github.com/Automattic/wp-calypso/issues/83512) reported for video file sizes shown as zero on the video details on media.

Besides the incorrect display of the overall storage used, I am more concerned that the checks for the maximum storage allowed are not working correctly, and customers could upload much more than 200GB of storage since the storage displayed is always zero. This hypothesis is worth checking, given that we could be incurring considerable storage costs if the limits for storage are not working properly for Atomic sites.

### Steps to reproduce

1. Go to an Atomic WordPress.com website. (You can use the [www.cursatica.com](http://www.cursatica.com/) atomic site to verify the issue.)
2. Go to the WordPress dashboard and select media. 
3. Upload multiple video and content to the media of considerable size.
4. Check the overall storage used on the media section of the WordPress.com Atomic site section. For me, it was always zero.

It might be preferable to find an Atomic site with this issue rather than trying to reproduce it. I believe there is a delay between the upload and the file size computation of approximately 12 hours. For the site that I mentioned, all the videos were uploaded a long time ago, so I don't think the cause is a synchronization issue.

### What you expected to happen

I expected to see the overall storage used computed correctly and displayed at the top of the media tab instead of zero when there is more than zero storage. For example, look at how the overall storage is correctly displayed on a site we own on the WordPress.com media section.

<img width="1496" alt="a8ctv-media-storage-used-correctly-displayed" src="https://github.com/Automattic/wp-calypso/assets/45241190/856d4d58-0d5d-4bfd-82cf-8b17d4e4b85a">

### What actually happened

The storage displayed was shown as zero, even though I am confident it was greater than zero.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – Reproduced
Tested on Atomic – Reproduced
Replicable outside of Dotcom – not applicable

📌 NOTES

📌 FINDINGS/SCREENSHOTS/VIDEO
![image](https://github.com/Automattic/wp-calypso/assets/6549265/1d600ab0-31c5-4932-98db-ad801b91299e)

![image](https://github.com/Automattic/wp-calypso/assets/6549265/55bc4c87-dfbf-4cff-8acc-fb515e1873ad)

📌 LOGS

📌 ACTIONS
- maintaining High priority - despite it being a string issue, it is quite visible and can leave folks concerned about our ability to maintain a platform.

**Comment by danielbachhuber** [comment]
@worldomonation Did you reproduce with the same video file or a different video file?

**Comment by worldomonation** [comment]
@danielbachhuber I've been pinged by @karenroldan and I'm re-trying the reproduction with more and larger files uploaded.

**Comment by danielbachhuber** [comment]
Worth noting: Atomic recalculates the storage used every 12 hours (citation needed).

On the site @tiniacoleyba showed me, he had uploaded the videos in April. They ended up as zero bytes for some reason (https://github.com/Automattic/wp-calypso/issues/83512) and the usage meter never reflected their size.

**Comment by worldomonation** [comment]
> Worth noting: Atomic recalculates the storage used every 12 hours (citation needed).
> 
> On the site @tiniacoleyba showed me, he had uploaded the videos in April. They ended up as zero bytes for some reason (#83512) and the usage meter never reflected their size.

Gotcha. It looks like there's a bit more intricacy to this than I had expected. Also TIL about the re-calculation on AT.

I've moved it back to Needs Triage for now.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
As for the 0% - I _think_ this is possibly just a limit of the UI – rounding down to 0% for low enough storage use. I pulled up a few actual customers who have reached or are nearing their storage limits on their AT sites and checked how their media storage looks, and they see meters like this:

<img width="250" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/5edbdbf4-08bb-44e6-b653-248650daf0a4">

---

For the sample site above, [cursatica.com](http://www.cursatica.com/), opening up Tools > Site Health > Info > **Directories and Sizes** allows us to see the Disk space used compared to the Disk space quota, which is: 

<img width="550" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/0df248ab-7197-47ee-b823-397902b46c22">

_(As mentioned above, this usage will recalculate every 12 hours)._


74.5MB is approximately `0.0363%` of 200GB, so the media library is rounding that down to 0%.

---

Lastly, I noted this over on https://github.com/Automattic/wp-calypso/issues/83512 as well, but it is expected that [uploaded videos (via VideoPress) on AT sites do not impact the storage usage meter](https://wordpress.com/support/space-upgrade/#reduce-used-storage). VideoPress is a Jetpack module that's on by default for AT sites, so by default, uploaded videos will use VideoPress, and thus not impact storage limits.

📌 ACTIONS
- Closed as by design

📌 Message to Author
- Feel free to reopen if folks feel I've missed anything here, and thank you for reporting in case this was a larger issue!

**Comment by cuemarie** [comment]
I've submitted a feature request to clarify how we show that media usage here: https://github.com/Automattic/wp-calypso/issues/83556 !

**Comment by worldomonation** [comment]
@cuemarie I might need to wait a few more hours (been told the storage usage stats refresh every 12 hours on AT), but on my test AT blog I uploaded a ~1.2GB file, where the storage usage figure is stuck at 0.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/cfdbb7d9-02e2-438a-afc2-e3090f7eeb23)

The file size isn't populating either.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/c3eb38a8-a437-4aa3-9a70-c2798b918039)

**Comment by cuemarie** [comment]
@edwinho89 With the VideoPress feature, that [video will not impact your site's overall storage usage at all](https://wordpress.com/support/space-upgrade/#reduce-used-storage). Can you try with a heavy image file?

> The file size isn't populating either.

I did find in [this test](https://github.com/Automattic/wp-calypso/issues/83512#issuecomment-1781706530) that newly uploaded videos take a bit of time to update before they show their file size field at all.

**Comment by danielbachhuber** [comment]
> With the VideoPress feature, that [video will not impact your site's overall storage usage at all](https://wordpress.com/support/space-upgrade/#reduce-used-storage).

@cuemarie This isn't obvious at all with the storage indicator. Maybe we need to make sure the storage indicator communicates as such?

**Comment by cuemarie** [comment]
> This isn't obvious at all with the storage indicator. Maybe we need to make sure the storage indicator communicates as such?

That's a good idea! Added a feature request for that: https://github.com/Automattic/wp-calypso/issues/83663
