### ISSUE TITLE
Gutenberg 16.9/CoBlocks/ETK conflict: "The page-patterns plugin has encountered an error"

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#83654]
### Quick summary

After Gutenberg 16.9, Atomic sites are experiencing a bug where ETK's pattern selection modal will not display when creating a new page, triggering a `The "page-patterns" plugin has encountered an error and cannot be rendered.` error message.

It only happens when the 3 plugins are active: Gutenberg, CoBlocks, ETK. Disabling either one of the makes the error go away:

![CleanShot 2023-10-30 at 15 22 42@2x](https://github.com/Automattic/wp-calypso/assets/14153300/491481d0-9a78-47d4-9454-220b0d8348fe)

### Steps to reproduce

1. On an Atomic site, activate Gutenberg 16.9, WordPress.com Editing Toolkit, CoBlocks
2. Go to Pages > Add new
3. The pattern selector modal will not load and "The page-patterns plugin has encountered an error" will be shown at the top of the editor canvas.

### What you expected to happen

The pattern selection modal should load correctly when loading new pages if ETK is active, no matter what other plugins are active.

### What actually happened

`The "page-patterns" plugin has encountered an error and cannot be rendered.`

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Chrome 118, Mac Sonoma
Gutenberg 16.9
CoBlocks 3.1.4
ETK 4.2070

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described.  My browser console shows the following error:

```
Source map error: Error: request failed with status 404
Resource URL: https://atbugtesting.work/wp-content/plugins/full-site-editing/starter-page-templates/dist/starter-page-templates.min.js?ver=1698692271
Source Map URL: starter-page-templates.min.js.map
```

📌 ACTIONS
- Triaged

**Comment by Gustavo-Hilario** [comment]
More reports here:

- [ ] 7310862-zen
- [ ] 7297135-zen

**Comment by silvio-meter** [comment]
Reported here: 

- [ ] 7251943-zen

**Comment by pauljacobson** [comment]
Al reported here: 7341396-zen with a follow-up here: 7341532-zen

**Comment by ariel-maidana** [comment]
7360857-zd-a8c
Deactivating Coblocks solved it.

**Comment by janmckell** [comment]
7378575-zd-a8c
Deactivating Coblocks solved it.

**Comment by nazilya06** [comment]
7551741-zd-a8c

User reported the same error. They had CoBlocks and ETK active on their site. I have tried deactivating these plugins; however, it affected the appearance of the site. 

Installing and activating Gutenberg resolved the issue.

**Comment by krutidugade** [comment]
Reported here 8590650-zd-a8c. They didn't have Gutenberg, CoBlocks and ETK active. Installing and activating Gutenberg solved the issue.

**Comment by hanananah** [comment]
8597050-zen

Gutenberg was active on the site, but CoBlocks and ETK were inactive. Activating ETK resolved the issue.

**Comment by donalirl** [comment]
#8827620-zen
Gutenberg plugin active, no Coblocks or ETK.

**Comment by davemart-in** [comment]
@obenland what do we want to do with this one? I don't think we support Coblocks anymore, but it looks like if people have Gutenberg enabled without ETK it creates issues. This seems to be on-going, but doesn't seem to affect a lot of customers.

I bring this up with you because I'm not sure it will be resolved by anyone on groundskeeper rotation.

**Comment by dsas** [comment]
I'll take a look. 

Given that ETK has been completely removed (pbxlJb-6ay-p2#comment-3905), I'll assume that reports where this happens without ETK are to be expected, from some of the reports above it's unclear that coblocks is related.

**Comment by dsas** [comment]
> The "page-patterns" plugin has encountered an error and cannot be rendered.

This is a very generic message that will occur whenever the plugin breaks in some way. This is quite probably several problems dressed up in a trenchcoat.

It looks as though @arthur791004 might have fixed one of these problems in https://github.com/Automattic/jetpack/pull/38823 on 2024-08-12, which was probably a big cause of reports. We've had two further reports since then though.

The plugin is being developed at https://github.com/Automattic/jetpack/tree/trunk/projects/packages/jetpack-mu-wpcom/src/features/starter-page-templates

**Comment by dsas** [comment]
I've tried reproducing this problem using the two tickets reported since Arthur's fix.

> #8827620-zd-a8c 

I can't reproduce on this site, I tried using Chrome.

> 8934305-zd-a8c

I can't reproduce on this site. I tried using Safari as I could see in the screenshot that's what the user used. @desnum also couldn't reproduce while working on the ticket.

----

As I said yesterday, this is a very generic message that just means page-patterns broke in some way. I don't think we should be prioritising this issue solely based upon the interaction count. A whole bunch of those were almost certainly resolved by Arthur's fix in August.

That said, depending upon how widespread these errors are, they might be logged into Sentry. I'll take a look to see if I can find anything.
