### ISSUE TITLE
Private Site subscribers are receiving new post email notifications

### ISSUE THREAD

**Issue by essleeung** [Automattic/wp-calypso#83867]
### Quick summary

Our [docs](https://wordpress.com/support/launch-a-newsletter/#sending-emails) clearly state that if "_If your site is set to private, your subscribers will not receive any email notifications of your posts."_

This doesn't seem to be the case for our user in 7256723-zd-a8c. If you check their subscriber list and reference Logstash, any subscriber that has joined since August 2023 has been sent new post email notifications. 

### Steps to reproduce

Tested this out on my own test site (Business plan, but not yet Atomic): 

1) Set site to Private. 
2) Add an email under Users > [Subscribers](https://wordpress.com/subscribers/). 
3) Create and publish a new post.
4) Check subscriber email for post notification.

### What you expected to happen

There should be no email notifications. In my test, this was correct. 

### What actually happened

On the user's actual site, Logstash shows many email notifications have been sent out.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

User is on a Business plan, but not blocked from going Atomic. 7255560-zd-a8c // 7256723-zd-a8c

**Comment by cuemarie** [comment]
@essleeung Since this isn't replicable outside of the customer's site, we'll need to be able to openly discuss specifics on the site, which isn't possible here in the public Github Repo. Could you please publish this report on 2EDhh-p2 instead?

Additionally, please check out this internal post for context on this customer: pcmoY8-b3-p2

📌 ACTIONS
- Closed in favor of an internal report for now
