### ISSUE TITLE
Stepper signup flow breaks when coming from a plan-specific flow

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#83868]
### Quick summary

When switching between a plan-specific signup and stepper signup, the latter breaks the stepper signup flow.

### Steps to reproduce

1. In the LOHP, in the tailored section flow, click on Video -> Start a blog with video content -> Get started with Premium.
2. You should now be on `/user/user-social` page. Now hit browser back few times till you get back to the LOHP.
3. Now click on Newsletter -> Start my newsletter and then signup for a new account.

### What you expected to happen

I expected to proceed with the newsletter signup flow

### What actually happened

After completing the registration step, I saw this page at the path `/checkout/undefined?signup=1`.

<img width="1232" alt="Screenshot 2023-11-03 at 5 50 14 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/eb74e1eb-66a1-40cb-9419-bdcab360e0f3">

Video recording of switching between plan-specific signup flow and stepper flow:

https://github.com/Automattic/wp-calypso/assets/1269602/fc4299ab-792e-402d-a0d1-11314a5dd481

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by cuemarie** [comment]
Escalation thread: p1699019626481819-slack-C02FMH4G8

**Comment by cuemarie** [comment]
📌 ACTIONS
- Assessed as an edge case in the slack thread above, so dropping priority level to reflect that more accurately

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described. After creating an account, I land on `https://wordpress.com/checkout/undefined?signup=1`

![Markup on 2023-11-06 at 11:06:24](https://github.com/Automattic/wp-calypso/assets/27249804/015e4a39-e2ff-457b-99fb-e02a4bc9dac5)

Clicking on **My Sites** from there leads to a similar page, but with the "Manage domains" buttons at the top right. The URL here is `https://wordpress.com/sites`

![Markup on 2023-11-06 at 11:07:10](https://github.com/Automattic/wp-calypso/assets/27249804/6d6da9d7-17c9-44c3-aab3-b271ff414935)

📌 ACTIONS
- Triaged

**Comment by alshakero** [comment]
Oh man, this was one of the most difficult bugs I investigated in a long time.

When filtering the signup destination, in [these lines](https://github.com/Automattic/wp-calypso/blob/8d5c4b11318a44b6aa0d60dac7b3def449079ab9/client/signup/config/flows.js#L293-L298), we check if the cart has any items, and if it does, we redirect to the checkout instead of the destination that is requested by the current flow.

When you go to a plan-specific flow, eg VideoPress, you add a premium plan to the cart, and when you leave it, the item stays in the cart. This breaks all the following visit to any other flow because the `destination` will always be overwritten by the cart.

I don't think it's specific to Stepper, and it can affect any two flows, where the first flow adds items to the card and the second does not. 

Fix is here: https://github.com/Automattic/wp-calypso/pull/83970

**Comment by alshakero** [comment]
Tested in prod and this is indeed fixed.
