### ISSUE TITLE
Fix the empty slug exception when updating a category

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#83882]
More details: p1698944465310459-slack-C04U5A26MJB

Updating a category with a dot name category throws an exception. It is caused by the fact that the category `slug` is empty. I believe the problem is probably caused by sanitizer that does not accept a `.` as the name of the category.

![Screen Shot 2023-11-02 at 15 51 45](https://github.com/Automattic/wp-calypso/assets/1234758/a308a530-d740-4054-afd3-25b0e7785890)

### Steps to reproduce

* Go to `/settings/taxonomies/category/:siteSlug`
* Add a new category named `.`(dot)
* Click on the option for the newly created category
* Click on Edit, and edit the description
* It should throw an exception

**Comment by bogiii** [comment]
I followed the steps and discovered that the slug field was no longer empty.
Adding and editing the category `.` works fine now.

For the simple site, it throws an exception.

Atomic site:
<img width="772" alt="Screenshot 2024-09-19 at 14 15 55" src="https://github.com/user-attachments/assets/f02ba5f6-ce70-4d2c-a0ef-52f1bb0ab77a">

Simple site:
<img width="298" alt="Screenshot 2024-09-19 at 14 22 43" src="https://github.com/user-attachments/assets/f41ac119-a49b-4e58-b122-4da71f5d1dbe">

I'm closing the ticket since it looks fine.
