### ISSUE TITLE
Question: Wrapping Case Blocks That Include Lexical Declarations In Brackets

### ISSUE THREAD

**Issue by SpenUK** [Automattic/wp-calypso#8399]
I've just been making a change (PR to come soon) and noticed a case block that declares a const without being wrapped in braces.

### Problem

The issue with this is described in the AirBnB style guide.
https://github.com/airbnb/javascript#comparison--switch-blocks

I've also created a gist:
https://gist.github.com/SpenUK/274c81e6b1fdab9367ff511a2d161fbf

### Suggestions

Since redux makes heavy use of switch statements I think this should be discouraged either by including the eslint rule (though I see that an effort is being made to reduce the list of rules...)

...Or add a guideline in the javascript style guide.

As in my previously opened issue, I'm happy to make a PR if this is something you guys agree with :D

**Comment by aduth** [comment]
FWIW, we've configured our ESLint rules to capture these issues, though the [rule is currently configured as a warning](https://github.com/Automattic/wp-calypso/blob/3b3fc118606c9944f56433106c0a44c27d7c2454/.eslintrc.js#L40) (perhaps there's less clear issues elsewhere in the codebase that we've yet to upgrade it to error).

In reducers, we've started moving a bit more toward using our [`createReducer` utility](https://github.com/Automattic/wp-calypso/blob/3b3fc118606c9944f56433106c0a44c27d7c2454/client/state/utils.js#L44-L118) which avoids the issue altogether by having each action type handler be its own separate function.

Otherwise, I've used the approach as in your gist where using [a plain block statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block) can be used for the intent of allowing the same variable name to be declared between cases.

**Comment by SpenUK** [comment]
Hey!
Thanks for taking to time to get back to me on this :)
I missed 'no-redeclare' - that'll do the trick for avoiding any clashing declarations. 
The scoping would still be off in cases where brackets are missed/left off but with the warning I can't imagine there would be much room left for issues.

Also, thanks for pointing me towards the createReducer - it looks quite interesting from a first glance!

**Comment by aduth** [comment]
>but with the warning I can't imagine there would be much room left for issues.

When I have a moment, I'll check to see whether there's a straight-forward upgrade path to changing this to being defined as an error in our configuration, which will help capture them during our continuous integration ([CircleCI](https://circleci.com/)) tests step.
