### ISSUE TITLE
Customizer: Link to “Premium Fonts by Adobe Typekit” Leads to Blank Page

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#8400]
Clicking on the “Premium Fonts by Adobe Typekit” link in the Fonts panel in the Calypso Customizer leads to blank page.

#### Steps to repro:

1. Go to the Calypso Customizer: https://wordpress.com/customize/druesome.com
2. Click Fonts on the left menu
3. Click on “Premium Fonts by Adobe Typekit”

#### Expected

To be taken to the Adobe Typekit site.

#### Actual

Page reloads and a blank page appears.

#### Browser / OS version

Tested on Google Chrome Version 53.0.2785.116 (64-bit) and Firefox 49.0.1 on Mac OS X 10.1

#### Screenshot

![screenshot](https://cldup.com/4cBhMdhuGp.png)

**Comment by lancewillett** [comment]
@mattwiebe Can you take a look, please?

**Comment by sirbrillig** [comment]
Weird! Thank you for the report.

This is the JavaScript error that results from that click:
<img width="544" alt="screen shot 2016-10-03 at 6 20 08 pm" src="https://cloud.githubusercontent.com/assets/2036909/19056258/1c0c0f66-8996-11e6-9595-50b20dc67170.png">

Since that is an external link, it needs to be loaded in the window context and break out of the iframe. Should be fairly easy to do.

**Comment by sirbrillig** [comment]
Should be fixed now.

**Comment by lancewillett** [comment]
Confirmed fixed, link works as expected — opening in same tab/window.
