### ISSUE TITLE
Reader: Subscriptions don't appear in latest when only Private or Coming Soon sites subscribed

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#84045]
### Quick summary

When a user is only subscribed to Private or Coming Soon sites (that they have permission to see), the Latest tab in reader doesn't display the sites and instead shows 
![2023-11-09 at 11 56](https://github.com/Automattic/wp-calypso/assets/47717887/76244617-5bfa-4762-8eb6-18c9ea2edb89)

When a public site is also subscribed to, the sites don't appear correctly in the subscriptions sidebar. Sometimes some sites will show and sometimes nothing
![2023-11-09 at 11 56](https://github.com/Automattic/wp-calypso/assets/47717887/cd116de9-51a2-4e2b-b8af-9a8a69501a73)

user case that brought this to light: 6794439-zd-a8c
p9F6qB-dHO-p2

Workaround is to search for the site in Reader to see it's content

### Steps to reproduce

1. Start with an account with no subscriptions
2. subscribe to a private site that the user has access to
3. check the latest page/subscription sidebar
4. subscribe to a coming soon site the user has access to
5. check the latest page/subscription sidebar
6. subscribe to a public site
7. check the latest page/subscription sidebar

### What you expected to happen

If any sites are subscribed, regardless of privacy setting, they should show in the latest tab

### What actually happened

latest page only loads when public sites subscribed

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my test site

📌 ACTIONS
– Triaged

**Comment by sixhours** [comment]
> When a user is only subscribed to Private or Coming Soon sites, the Latest tab in reader doesn't display the sites

> If any sites are subscribed, _regardless of privacy setting_, they should show in the latest tab

I feel like I'm misunderstanding the core issue here. I would not expect sites that are marked private or coming soon to have their posts show in the Reader unless the viewing user has permissions on the site. I tried the following combinations with my non-a8c test account:

| Capability | Site status | Can see content in reader |
------------|------------|---------------------
| Administrator | Private | true |
| Administrator | Coming Soon | true |
| Editor | Private | true |
| Editor | Coming Soon | true |
| Author | Private | true |
| Author | Coming Soon | true |
| Contributor | Private | true |
| Contributor | Coming Soon | true |
| No explicit permissions | Private | false |
| No explicit permissions | Coming Soon | true |

I'm surprised that a brand new "Coming Soon" site _will_ show up in the Reader if a user subscribes to it, because the implication of "Coming Soon" is that you don't want outside users to see your site/content yet. 😬 

I can't see the ZD ticket to get a better sense of this exact user's issue, but please let me know if I'm missing something!

**Comment by Nic-Sevic** [comment]
@sixhours 

> I feel like I'm misunderstanding the core issue here. I would not expect sites that are marked private or coming soon to have their posts show in the Reader unless the viewing user has permissions on the site.

This is referring to users that have permission, including the site owner. In these cases, the sites should be listed in the sidebar on the right and posts should show in latest. Instead, this only happens once a public site is subscribed to. 

Also, simple sites have viewers and atomic sites have subscribers that should also be able to see this.

Please note, I'm not referring to pulling up the actual reader feed for the site, rather I'm referring to the recent posts page. You can pull up the individual feed page just fine if you know how to get to it. 

You can see the atomic p2 for this case here which has more details: p9F6qB-dHO-p2

**Comment by sixhours** [comment]
> This is referring to users that have permission, including the site owner. 

Aha, that's much clearer, thank you! I've updated the original issue to include that info in the (likely) event I don't solve this today/tomorrow. :D

**Comment by sixhours** [comment]
I'm testing this and I'm beginning to think it's something specific to this user.

On a fresh Atomic site in either Coming Soon or Private mode, as the owner of the site, and only subscribed to that site, I can still see it in the Recent view of the Reader:

<img width="952" alt="Screenshot 2023-12-13 at 12 33 21 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/4d3c0f53-7a61-4762-855d-9b50ac1392a1">

I _did_ have to wait a few minutes for the feed to populate with posts after transferring to Atomic (I actually published a new post and I think that triggered a refresh of the Feedbag cache).

I'm going to check the user's Feedbag cache on the backend to see if there are any clues there.

**Comment by sixhours** [comment]
There's definitely something weird happening with this user's feed. I've traced it back through the API, and the initial query of 4 posts pulls back content but it's all marked as post type `revision`, and therefore considered "not found" according to this:

fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qernq%2Qfvgr%2Qcbfg%2Qraqcbvag.cuc%3Se%3Q4o5279q2%23118-og

I've also found that switching the API back to `v1.1` on the frontend seems to fix it, so there's something in this version of the API that isn't working. I'm going to check the revision history on the API files I went through to see if there were any recent changes that look suspicious.

**Comment by sixhours** [comment]
I think this was caused by the changes we made in D126633-code where we swapped `get_blog_posts` for `get_site_post`. Doing a hard reset to 1 revision before that revision fixes the issue, and resetting to that revision breaks it again.

**Comment by sixhours** [comment]
I dug into it more and confirmed that the above change did not *cause* this bug -- not directly. The reason the feed "works" when we revert that change is because the old `get_blog_post` method did not do much error checking or filter out revisions. It just grabbed the posts by ID and returned them.

The posts being returned in that case are not actually the right posts, because there's a mismatch between the post IDs in Feedbag and the post IDs in the blog tables. 

The feedbag post IDs for the last four posts are:

```
[post_id] => 20195
[post_id] => 20192
[post_id] => 20183
[post_id] => 20180
```

But the site's post IDs for the last four posts are:

```
[post_id] => 24281
[post_id] => 24280
[post_id] => 24279
[post_id] => 24278
```

So when the API fetches each post by its Feedbag post ID here:

fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qernq%2Qfvgr%2Qcbfg%2Qraqcbvag.cuc%3Se%3Q4o5279q2%23101-og

it gets back the wrong posts -- in this case they happen to be the IDs for four post revisions, which get filtered out by the fetch method, so Reader thinks there are no posts at all.

**Comment by sixhours** [comment]
Posted my findings on the P2 since I'm not sure how the Feedbag subscriptions feeds get populated or cache busted, hoping Atomic folks will have some ideas: p9F6qB-dHO-p2#comment-56947

**Comment by Nic-Sevic** [comment]
@sixhours thanks for updating there. 

In terms of private/coming soon blogs not showing, I was able to replicate this on my own sites with my own test sites, so that part is not something specific to the user site.

**Comment by sixhours** [comment]
> In terms of private/coming soon blogs not showing, I was able to replicate this on my own sites with my own test sites, so that part is not something specific to the user site.

Could you send me the blog IDs for your test sites so I can look? Either drop them here or Slack me. That would let me rule out a post ID mismatch issue there and see if there's another issue. Thanks!

**Comment by Nic-Sevic** [comment]
@sixhours Frustratingly when I pull up the user I was testing on now, things are working. Previously I was able to consistently and reliably replicate but now, things show as expected

user I tested with is testnicsev
private site: 194107101
coming soon site: 211258993

**Comment by sixhours** [comment]
I posted a long write-up of the path I followed to get to the above conclusion (should have done that sooner, but holidays, amirite?); including it for posterity here:

p9F6qB-dHO-p2#comment-57155

**Comment by sixhours** [comment]
Dug into this more today and didn't make progress. Posted a query in Loop since they've dealt with fixing weird feed issues somewhat recently, maybe they'll have some ideas! p1704836041096169-slack-C03NLNTPZ2T

**Comment by roo2** [comment]
After a lot of investigation (p9F6qB-dHO-p2#comment-57292), it looks like this was caused by an AT site being reverted, the posts made on the AT site would not show up in subscribers feeds. (but new posts would show up as normal)

I'll close this in favour of https://github.com/Automattic/wp-calypso/issues/86334
