### ISSUE TITLE
Investigate the possibility of installing WooCommerce when selling courses

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#84120]
### Details

In Sensei LMS's onboarding wizard, WooCommerce is installed / activated when "Sell courses and generate income" is selected on the _Purpose_ step:

![Screenshot 2023-11-10 at 6 00 57 PM](https://github.com/Automattic/wp-calypso/assets/1190420/bed9a6ac-cc2f-4c06-b46a-e9dacdae5410)

However, this same behaviour is not present on Atomic sites. From what I've gathered by reviewing P2s and PRs, it seems like we originally [added this functionality](https://github.com/Automattic/wp-calypso/pull/72686), then [subsequently removed it](https://github.com/Automattic/wp-calypso/pull/74004), possibly because of [this issue](https://github.com/Automattic/sensei-pro/issues/2133).

### Checklist

- [x] Review the history of this functionality
- [x] Investigate to determine if the original issue preventing us from installing Woo has been resolved
- [x] If so, create an issue for adding this functionality
- [ ] If not, write a post on Sensei P2 with a summary of the situation

**Comment by renatho** [comment]
Hi @yscik and @gkaragia! 👋
I'd like to ping you here, just in case you remember something important about this or links with references for us to avoid re-creating a bug or something like that.

**Comment by gikaragia** [comment]
Hey @renatho! So I remember that we initially started considering removing WC installation from the flow because we were trying to solve a Jetpack Identity Crisis issue and I believed that it had to do with timing so making our flow faster would stop the issue from happening. 

However, there were also some other issues IIRC. It seems that we had a discussion about it (p1677600664777249-slack-C048ZJB2QNM) but I can't find it unfortunately. So the issues that we were having when we also installed WC as part of the onboarding flow were the following:
- Woo would run their own setup guide once the user was redirected to home which we found a bit cumbersome.
- Woo would add their own tasks in the homepage which we thought it would make it harder for the user to finish with setup.

So for the two reasons above together together with the possibility of solving the JIC we ended up removing Woo. Also, there is an upsell to install Woo already in wp-admin so we thought that users that want to install it, can use this menu anyway. The JIC were not affected at all from WC so you shouldn't worry about introducing this bug if you re-add it. Also, the JIC issues should be solved (or are more unlikely to happen) after a fix that added some delay in the atomic transfer. And the Woo flow might be more streamlined now or easier to configure.

So if you want to implement this, you should install WC as a first step (this should be easy to achieve by adding the plugin slug somewhere in the code IIRC) and test the user experience once the user is redirected to home. Hope that helps!

**Comment by renatho** [comment]
It's definitely helpful! Thank you @gkaragia!

Just adding here a reference to the JIC to connect the points: https://github.com/Automattic/wp-calypso/pull/74004#pullrequestreview-1324045455. I thought it could be related to https://github.com/Automattic/wp-calypso/issues/84350, but it seems something completely different.

**Comment by renatho** [comment]
Issue created for the implementation: https://github.com/Automattic/wp-calypso/issues/85857
