### ISSUE TITLE
Design Picker: Tronar's theme details page is showing main heading with the wrong color

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#84172]
### Quick summary

Tronar's main heading color is different between the demo site and the Design Picker's theme details preview.

cc: @Automattic/lego @iamtakashi 

### Steps to reproduce

1. Go to https://wordpress.com/start.
2. Pick a domain.
3. Pick a plan.
4. In the Design Picker, select the Blog category.
5. Search for Tronar.
6. Click Tronar.

### What you expected to happen

In the details page, the preview should show the main heading's color as white, as per the demo site: https://tronardemo.wordpress.com/

<img width="844" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/99f588a0-bc82-4a31-a835-af86dc8b5354">

### What actually happened

The main heading's color is black:

<img width="1260" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/39e0f9fb-0887-415c-a1e0-18458d6fe54c">

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by arthur791004** [comment]
Proposing D128861-code to resolve this issue 🙂

**Comment by taipeicoder** [comment]
@arthur791004 I'm still seeing the heading color being black, with the patch applied: 😕

<img width="1088" alt="Screenshot 2023-11-15 at 10 35 24 AM" src="https://github.com/Automattic/wp-calypso/assets/797888/a912c25f-724f-48d5-9242-9c1bda41b7a5">

**Comment by arthur791004** [comment]
I misread this one and thought it was the same as https://github.com/Automattic/wp-calypso/issues/84173 😅

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Reproduced in a new site creation flow
![CleanShot 2023-11-18 at 14 59 08@2x](https://github.com/Automattic/wp-calypso/assets/14153300/b83226c4-1429-4be3-9998-d3da8458032f)Attach screenshots or videos.

📌 ACTIONS
- Triaged

📌 Message to Author
I'm going to leave as "High" since you're already working on it, but if you end up moving to other work, I think it might be worth bumping to Normal

**Comment by arthur791004** [comment]
Closing it as it's completed via D129408-code
