### ISSUE TITLE
Sites redirecting to wordpress.com/home/{siteaddress} instead of wp-admin areas

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#84170]
### Quick summary

Some sites are redirecting to WordPress.com/home/{siteaddress} (edit: Or redirected to WordPress.com when Jetpack SSO is deactivated) when clicking nav links to plugins, installed plugins, etc., and opening posts or pages, etc.  

Work around is to navigate to /wp-admin before clicking links in the nav. 

### Steps to reproduce

1.  Go to My Site(s) 
2. Select the site in question
3. Click on Pages > Click on any page to open it  OR click on Plugins > Installed plugins 

### What you expected to happen

I expect the page to open in the editor or the plugins list in wp-admin to open

### What actually happened

Calypso redirects to WordPress.com/home/{siteaddress} in both cases.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement: Work around navigating to /wp-admin before clicking links in the nav fixes the issue. 

### Logs or notes

- p1699986083126169-slack-C02FMH4G8
-  p1699986260637129-slack-CB0B2G43X

**Comment by ash1eygrace** [comment]
7308440-zd-a8c
7299192-zd-a8c
7302929-zd-a8c
7308062-zd-a8c

**Comment by ash1eygrace** [comment]
p9F6qB-dKy-p2

**Comment by jorpdesigns** [comment]
Reported in 7277263-zen. Shared workaround earlier.

**Comment by csabarakasz** [comment]
7305614-zd-a8c

**Comment by mreishus** [comment]
This involves PR 1560 on wpcomsh

**Comment by mgozdis** [comment]
User report on a Simple site when editing Posts/Pages: 7308787-zd-a8c
It briefly shows a "Your blog is almost ready" flow when redirecting. `https://wordpress.com/setup/design-first/launchpad?siteSlug=` where siteSlug is their free *.wordpress.com address. They claim it did not happen until connecting an existing domain.

It also gives them access to the Classic Editor, which only plugin-enabled sites typically have. Switching to Classic View and editing in Classic Editor works, but editing in Site Editor/Calypso redirects. 

Due to the launchpad redirect, I tested launching the site and setting it to Coming Soon. This fixed the redirect and Pages/Posts can be edit in the Site Editor in Default or Classic View now, but they still have access to the Classic Editor.

**Comment by davipontesblog** [comment]
User report at 7311500-zen

**Comment by ash1eygrace** [comment]
Spot-checked the above sites and the redirect to /home and worpress.com is no longer happening and is fixed.
