### ISSUE TITLE
Enable classic admin interface style for Sensei users

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#84467]
### What

Set _Admin interface style_ to _Classic style_ when Sensei is installed as part of the onboarding flow:

![Screenshot 2023-11-23 at 7 57 09 AM](https://github.com/Automattic/wp-calypso/assets/1190420/3a2cc642-fe12-46c0-9594-10dc35a4ad82)

### Why

When viewing the frontend of a Sensei site on Atomic (e.g. a course or a lesson), the admin bar is different than it is for self-hosted sites. In particular, there are no _Edit Course_ or _Edit Lesson_ links and no _Preview as Student_ link.

### How

Additional context about the admin interface style can be found here - pdtkmj-1Vq-p2.

**Comment by Imran92** [comment]
I've added a solution here - https://github.com/Automattic/wp-calypso/pull/84690, so the class WP Admin style is set during the wpcom onboarding bundle flow. This will solve it for the upcoming users.

I was wondering about what we should do about users who are already existing, and who install sensei without going through this flow.

Maybe we can try always the style to Classic when Sensei is active, but I think it can potentially be confusing for users in case they want to use the Default style instead of the classic one, or in case they are not willing to use it but just checking the hosting config and notice the Admin Panel Style. They may wonder why the style isn't moving back to Default even though they are selecting that in the settings.

We can also decide to not handle it for the existing users, maybe we can add this info as part of documentation somewhere to switch to Classic.

Or, maybe we can show a Admin panel notice from Sensei only when Sensei is active and Calypso with Default style is also active, to inform the user that Sensei works best with Classic style. There can be a button in the notice clicking on which will switch the Admin Panel, so they won't have to find it in settings. I like some aspects of it, like the user can choose to have any Admin Panel style they want and we are not changing it without informing them.

I'm imagining something like this - LMKWDYT! :)

![Image](https://github.com/Automattic/wp-calypso/assets/6820724/0570c428-45c2-4fb5-ac71-bd0c1f52fd4a)

**Comment by donnapep** [comment]
> I was wondering about what we should do about users who are already existing, and who install sensei without going through this flow.

@Imran92 No need to change anything for existing users. This is just for new users. And let's not add a notice. All the notices on WP.com are already bothersome enough. Also, we don't have enough subscribers to justify the effort.
