### ISSUE TITLE
Gutenberg Comments: Commenters can't paste links in comments on their own line with newer format

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#84623]
### Quick summary

On sites with Gutenberg comments enabled, commenters cannot paste links, embed videos, etc.

### Steps to reproduce

1. Use a site with Gutenberg Comments enabled, for example: (pduMd4-tC-p2)
2. Try pasting a link on its own line
3. Note nothing happens

### What you expected to happen

Previously, users could paste links on their own line, and according to comments [here](https://wordpress.com/forums/topic/block-editor-in-the-comment-box/), it used to work for embedding tweets and videos.

### What actually happened

If you try to paste a link on its own line, nothing happens

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

This only applies to simple sites currently pdDR7T-U7-p2

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate
📌 FINDINGS/SCREENSHOTS/VIDEO
Simple

https://github.com/Automattic/wp-calypso/assets/14153300/12d85cda-42b6-4271-bb1f-12613f6bba70


Atomic
![CleanShot 2023-12-08 at 09 28 43@2x](https://github.com/Automattic/wp-calypso/assets/14153300/0c5e3996-af81-4136-a384-555a80b6d352)


📌 ACTIONS
- Triaged
- 
📌 Message to Author
@supernovia I imagine @Automattic/vertex has already fixed this because I cannot reproduce anymore, but please reopen if you're still seeing this in the forums and share more information about how we can reproduce.
