### ISSUE TITLE
[Woo Express $1 offer] Plans screen copy updates

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#84681]
### Issue description

Copy does not reflect $1 offer cadence:

Figma: jFG3dxNDOdMkw8AC1aGWBL-fi-458:1884#624584477
![Image](https://github.com/Automattic/wp-calypso/assets/3747241/8f0c20db-72fe-4c57-bd78-b23e5b20b9ef)

### Acceptance criteria

1. Fix copy to `just $1 for your first 3 months.`
2. Make sure the copy in `Free trial` tab is fixed as well.

**Comment by chihsuan** [comment]
Hey @ilyasfoo Copy does not reflect "$1 offer" because the `formatted_price` returned by the wpcom plans API is "US$...". 

<img width="1352" alt="Screenshot 2023-12-25 at 16 34 29" src="https://github.com/Automattic/wp-calypso/assets/4344253/412d3e43-e488-41c8-a144-23cea9bf2371">

We can fix it individually on Calypso side with JS. However, I think it would be better if we could fix it in API side so that we don't need to handle it in different places. But that might affect all other plan pages. I noticed that we show the same formatted price on other pricing pages. I wonder if we should bring this up to relevant teams to ensure we display the same format across all pages? Or we just fix this for WooExpress? What do you think?

<img width="1347" alt="Screenshot 2023-12-25 at 16 39 08" src="https://github.com/Automattic/wp-calypso/assets/4344253/d4cfabd3-156d-4c0a-8c9f-4814e28b096d">

<img width="1141" alt="Screenshot 2023-12-25 at 17 00 25" src="https://github.com/Automattic/wp-calypso/assets/4344253/c8734455-67d2-44f4-a5e1-1f052e8a053a">

cc @adrianduffell

**Comment by chihsuan** [comment]
Note: We're using php [`NumberFormatter::formatCurrency`](https://www.php.net/manual/en/numberformatter.formatcurrency.php) to format the price.

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Sfgber%2Qcevpr.cuc%3Se%3Qnq3pno52%26sv%3Qqvfcynl_cynvagrkg_jvgubhg_mrebf%23199-og

**Comment by ilyasfoo** [comment]
@chihsuan Sorry the issue might've been misleading (I missed the difference between $1 and US$1, but it isn't an issue _yet_ 🤞). I think it's fine either to ignore or fix it just for Woo Express in calypso if it can be simple.

But the crux of the problem is with `US$1 **a month** for your first 3 months` vs `US$1 for your first 3 months`

**Comment by chihsuan** [comment]
> @chihsuan Sorry the issue might've been misleading (I missed the difference between $1 and US$1, but it isn't an issue _yet_ 🤞). I think it's fine either to ignore or fix it just for Woo Express in calypso if it can be simple.
> 
> But the crux of the problem is with `US$1 **a month** for your first 3 months` vs `US$1 for your first 3 months`

Gotcha! Then, I'll ignore it. I prefer to keep a consistent currency format until we want to change it on all systems. 🙂
