### ISSUE TITLE
Like widget: dialog CSS changes

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84752]
Let’s have the avatar image inside the pop-over the same size, 26px. (currently in the code I’m seeing that image is 28px in the pop-over, but [I checked and it’s actually smaller](https://href.li/?https://prnt.sc/ZDyy4Nd9ZJlV), I’m not sure why).

**Comment by JuanLucha** [comment]
I think they are smaller because the white border blends with the white background in the popup.

**Comment by JuanLucha** [comment]
I have done some checks: I have set the background of the popup in black so we can see the real height of the avatar images, and my theory is correct. Seems the white background is messing with the perception of the images, but they are both the same height:


![Image](https://github.com/Automattic/wp-calypso/assets/3832570/479ade6c-959d-43e4-b9c2-47c74602a85e)



![Image](https://github.com/Automattic/wp-calypso/assets/3832570/835c563c-4fbb-4871-93d2-5b4106b3e68e)

Please ignore the height of 56px instead of 28px; it seems to be related to taking screenshots on a retina screen; it's doubling the pixels of the screenshot resolution.

I suggest changing the border of the images in the popup to a different color, maybe a shade of gray, so the border doesn't blend with the background.

**Comment by JuanLucha** [comment]
Set it to blocked until I got input from design on this.

**Comment by TimBroddin** [comment]
@poligilad-auto could you give some input on this please?

**Comment by JuanLucha** [comment]
Following @poligilad-auto feedback, this patch removes the border inside the popup: D130780-code
