### ISSUE TITLE
Remove email verification step when onboarding Woo Express

### ISSUE THREAD

**Issue by adrianduffell** [Automattic/wp-calypso#84976]
## User Story

> As a new Woo Express user, I want to sign-up quickly, so that I can start creating my store.

##  Description

In the Woo Express sign-up flow, new users that create a WordPress.com account are required to verify their email. This screen should be updated with Woo branding.

<img width="1440" alt="Email verification" src="https://github.com/Automattic/wp-calypso/assets/9312929/25b67078-ce78-4c38-9986-3ee23aee325b">

[Figma](https://www.figma.com/file/4ixWMlzrxllx93tSFsCW6k/Customer-first--Experience?mode=dev)

The screen presently looks like:

![image](https://github.com/Automattic/wp-calypso/assets/9312929/84817ef4-d263-48cb-a25b-70cc449a80ca)

**Comment by chihsuan** [comment]
This is a bit tricky to customize the screen because the users are redirected to this page by Jetpack SSO module when visiting the created new site, not Calypso. It's possible that we can set a cookie or local storage to preserve the woo context before the page.

However, I think a better solution is to implement the magic link signup for Woo Express flow.

**Comment by chihsuan** [comment]
Adrian and I discussed this in our 1:1  today. We want to fix "Email verification screen" in January. 

> However, I think a better solution is to implement the magic link signup for Woo Express flow.

Because we are not likely to have a passwordless signup for Woo Express flow in January, Adrian mentioned that we can probably do a quick fix by skipping the verification step for new users when logging Woo Express free trial sites. 

I dug a little deeper today and found that the control logic is actually in WPCOM.
- fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Swrgcnpx%2Qffb.cuc%3Se%3Q45r08p7q%26sv%3Qvf_hfre_pyrnerq_sbe_fvgr%23198-og 

So it seems that **we can simply add a few lines to remove email verification for free trial users.** I would prefer this approach if it's legal to skip email verification because it's just a temporary solution before launching passwordless sign up.

Otherwise, adding a Woo verification screen and redirecting users to it is possible, but that would be a bit more effort. 

What do you think? @adrianduffell cc @Automattic/ghidorah

**Comment by adrianduffell** [comment]
>  if it's legal to skip email verification

Thanks for your work looking into this, @chihsuan! I'll follow-up about this to help us make a decision.

**Comment by adrianduffell** [comment]
> So it seems that we can simply add a few lines to remove email verification for free trial users. I would prefer this approach if it's legal to skip email verification because it's just a temporary solution before launching passwordless sign up.

Confirmed it's legal to skip email verification so let's go ahead with this approach as a temporary solution.

**Comment by chihsuan** [comment]
D133829-code

**Comment by p-jackson** [comment]
@chihsuan I've just deployed a change to Jetpack SSO that I think might supersede this improvement.
Discussed here p1HpG7-qll-p2, it solves the issue of email verification for the general case which and I think it should cover the situation described by OP.

Check out the code change here D133828-code, you might be able to remove the Woo Express-specific work around.

**Comment by chihsuan** [comment]
@p-jackson Nice, thanks for letting me know! 👍  I'll check out the code.
