### ISSUE TITLE
Checkout variant picker items can appear to merge with other line items at mobile width

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#84984]
At desktop width, the discount is on one line:

<img width="583" alt="Screenshot 2023-12-07 at 11 39 22 AM" src="https://github.com/Automattic/wp-calypso/assets/2036909/d7e73dba-2e3e-40f6-9a19-90d810ba0bc2">

But at mobile width, this collapses to two lines:

<img width="390" alt="Screenshot 2023-12-07 at 11 39 17 AM" src="https://github.com/Automattic/wp-calypso/assets/2036909/38fec507-8bd7-43ac-8c79-a1a2cba94b7c">

This makes the variant picker so tall that it overlaps enough of the content below that it can appear to merge with the line item below it (notice how the "One year" of the second item in the cart appears to be part of the dropdown for the first item):

<img width="395" alt="Screenshot 2023-12-07 at 12 06 20 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/5bf7e032-cc5e-4ab9-b448-9e72c593e0b8">

Reported here: p1701945633609839-slack-C0117V2PCAE

**Comment by sirbrillig** [comment]
I wonder if changing the height of each item will really help, because some products have more than three variants. For example, multi-year domains have ten:

<img width="601" alt="Screenshot 2023-12-07 at 11 52 34 AM" src="https://github.com/Automattic/wp-calypso/assets/2036909/2e810554-d022-40a0-9df1-b5f341660fdb">

<img width="389" alt="Screenshot 2023-12-07 at 11 54 01 AM" src="https://github.com/Automattic/wp-calypso/assets/2036909/20f96ae8-2a08-435f-8cbc-7607fce5f3ac">

**Comment by sirbrillig** [comment]
Probably a more robust solution would be further differentiating the dropdown from the page below it when it is active. We could try putting a shadow over the whole page, or part of it, like this:

Before             |  After
:-------------------------:|:-------------------------:
<img width="395" alt="Screenshot 2023-12-07 at 12 06 20 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/a19121ea-764f-4b6c-ad17-f95e152f6f11"> | <img width="408" alt="Screenshot 2023-12-07 at 12 12 05 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/fe4689d1-a5ae-410f-ac65-70a0ba64dcaf">

**Comment by jjchrisdiehl** [comment]
If the overlay is too much, as mentioned in Slack, we could also consider a drop shadow:


![Image](https://github.com/Automattic/wp-calypso/assets/16580129/1adf3581-475b-4021-b2e7-2523919f1eee)


This might also be a separate issue, so I logged it here https://github.com/Automattic/wp-calypso/issues/85004, but I never realized you could open multiple variant pickers at once:

![Image](https://github.com/Automattic/wp-calypso/assets/16580129/bf240fea-870e-4bd5-ae92-af0a7d848bb1)


Which feels a bit messy on mobile 

![Image](https://github.com/Automattic/wp-calypso/assets/16580129/bc9bea0f-9462-441a-93e6-1f99a4abac22)

**Comment by jjchrisdiehl** [comment]
It looks like the layout overflowing onto the next line is intended, as it adjusts from one item in the left column and three in the right, to two in the left, and two and in the right:

| Desktop | Mobile |
| ----- | ----- |
| <img src='https://github.com/Automattic/wp-calypso/assets/16580129/f678f0d7-8c36-4da2-930b-a5da594d02df' width="400px" /> | <img src='https://github.com/Automattic/wp-calypso/assets/16580129/b9fd3164-e14c-47cc-b186-ac3e2d949d05' width="400px" /> |

~Though I am not sure why the list items have that large right padding?~ (Looks like the padding was introduced here https://github.com/Automattic/wp-calypso/pull/61174)  I think its so the prices right align correctly with the main option price on desktop, ~but it doesn't work the same on mobile so the extra padding is not needed.~ This looks like an issue with my local setup, the mobile padding is working now.

The right padding does get a bit intrusive at smaller device widths, so this is more of a design choice that I'll **defer to Jana.**

Here is an example where option three has the right padding removed and the three pricing spans are moved back to the right column (as seen on desktop):



![Image](https://github.com/Automattic/wp-calypso/assets/16580129/126be912-a84a-4f44-b967-d588db1eec14)

And on even smaller devices (under 320px, where arguably it gets difficult to have a good web experience anyway), we could then collapse the right column into a, well, column:



![Image](https://github.com/Automattic/wp-calypso/assets/16580129/ef7d76b6-09fb-4b7f-b83f-62ae69235682)


@JanaMW27 I wonder if the overflow on mobile was intentional to ensure the options are 'tappable' for the average user? Is there a minimum height that is expected for mobile buttons?

**Comment by JanaMW27** [comment]
Minimum height on mobile is 40px.
I don't think we need to align all the prices with the dropdown price.
I would remove the big margin on the right side of the price and try to keep it all in one line with a min height of 40 px.
If then that doesn't git, we can move the Save to a second line but under the price, not under the year label.

**Comment by jjchrisdiehl** [comment]
Fixed with above PR - let me know if there is a better option and we can reopen this.
