### ISSUE TITLE
Themes: when browsing from current theme "Info" into Customizer and back, incorrect return landing page

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8500]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/example.wordpress.com
2. Click "Info" next to current theme
3. Click back (in Calypso)
4. Click "Customize" next to current theme
5. Close Customizer
6. You're back at the info screen (should be back at theme list)
#### What I expected

Land back at the starting point of https://wordpress.com/design/example.wordpress.com — the themes list for the current site.
#### What happened instead

You either land at a specific theme's info screen (seems to be most recent, top of the list) or simply https://wordpress.com/design — which doesn't have the current theme at the top.
#### Context / Source
# dogfooding by @beaulebens

**Comment by seear** [comment]
I'm having some trouble reproducing this—do I have one of the steps wrong? (I don't doubt that there is a problem here somewhere, because the info page 'back' mechanism is somewhat [kludgy](https://github.com/Automattic/wp-calypso/blob/6c246344c91cf65eb21fdaa9f2d626e0f63af277/client/my-sites/theme/controller.jsx#L58).) 

![customizer_close](https://cloud.githubusercontent.com/assets/7767559/19235656/ed8ec340-8eea-11e6-8fe3-533ba76bf04f.gif)

**Comment by lancewillett** [comment]
I had trouble reproducing it exactly, but it seemed to sometimes track a "starting point" and go back to that; other times it would just go to /design as the themes list.
