### ISSUE TITLE
Plans: "My Plan" has layout issues on small screens with icons

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8510]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/plans/my-plan/example.wordpress.com with a site that has a paid plan.
2. View the My Plan page.

<img width="759" alt="screen shot 2016-10-05 at 15 27 39" src="https://cloud.githubusercontent.com/assets/66797/19134042/653b4e24-8b10-11e6-8ed5-8ef387ad3ad6.png">

<img width="988" alt="screen shot 2016-10-05 at 15 27 30" src="https://cloud.githubusercontent.com/assets/66797/19134044/6934c2d0-8b10-11e6-8199-2f4b4f7bc47d.png">
#### Browser / OS version

Chrome on Mac OS X
#### Context / Source

Via a recent #dogfooding session from @beaulebens

**Comment by rachelmcr** [comment]
It looks like this has since been resolved. I tested in Chrome 60 on Mac 10.12.6 and the layout/icons look ok to me at smaller screen widths:

![screen shot 2017-08-22 at 3 35 36 pm](https://user-images.githubusercontent.com/8658164/29570928-cc407c0c-874f-11e7-921e-17c56e9eb507.png)

![screen shot 2017-08-22 at 3 36 00 pm](https://user-images.githubusercontent.com/8658164/29570932-cd9343dc-874f-11e7-9a59-4f1b83362e09.png)

![screen shot 2017-08-22 at 3 38 12 pm](https://user-images.githubusercontent.com/8658164/29570983-f3c0da6a-874f-11e7-933d-9483c99afcf2.png)
