### ISSUE TITLE
Reader: automatically follow newly created Jetpack sites

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8514]
#### What I expected

When you create a WordPress.com site, you automatically follow it yourself in Reader.
#### What happened instead

When you create a Jetpack site, it should auto-follow in Reader as well.

#### Context / Source

Suggested in a recent #dogfooding by @beaulebens

**Comment by fraying** [comment]
Good idea.

**Comment by fraying** [comment]
@blowery Any ideas on how hard this would be to implement?

**Comment by blowery** [comment]
@fraying assuming we have something to hook, _should_ be easy.

**Comment by lancewillett** [comment]
Re-opening this one so we can investigate and fix.

**Comment by donpark** [comment]
I think the ideal place to do this when Jetpack activated occurs either on WPCOM or on the remote site in Jetpack.

Doing this in Calypso is more complicated because target site is unknown, meaning we'll have to either check all the site user owns or check when selected site changes. Neither options are attractive nor problem free.

**Comment by donpark** [comment]
NVM. Just discovered `client/jetpack-connect` and `client/jetpack-onboarding`. `client/jetpack-connect/jetpack-new-site/`, in particularly, looks useful for this issue.

It just never crossed my mind that this sort of one-off stuff would be done in Calypso instead of from Jetpack pages. But then there is the whole signup jungle embedded in Calypso so, doh, I should've expected it.

**Comment by donpark** [comment]
I ran into difficulty verifying, using calypso.localhost, that Calypso-based hacks will work due to server-side hardcoded URLs. I'm now looking at server-side WPCOM code that handles Jetpack site registration (creating cached site tables, etc.).

**Comment by donpark** [comment]
This has been implemented on the WPCOM side. See D26703-code

**Comment by donpark** [comment]
This feature has been deployed to WPCOM this morning. w00t!

D26703-code - impl. patch
D27380-code - integration patch

cc @lancewillett
