### ISSUE TITLE
Image uploads return Invalid parameter(s): post_id when trying to add images to Templates

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#85373]
### Quick summary

When trying to add an image from a 3rd-party service like Pexels or Openverse to a Template in the Site Editor, the image is not added and returns `Invalid parameter(s): post_id`. It appears to only affect Templates as adding to a Page or Post works fine. 
![WJOBnC.png](https://github.com/Automattic/wp-calypso/assets/121042930/9c77cc15-dd68-4990-a431-bdeea1d5b26d)

User report: 7457481-zd-a8c

### Steps to reproduce

1. With an FSE theme, open a template for editing such as the Index template
2. Add an Image block, choose Select Image, and select Pexels or Openverse
3. Select an image from Pexels or Openverse and click Select to try and insert it into the Template - see the error message returned for `Invalid parameter(s): post_id` and no image inserted. 

### What you expected to happen

Images from 3rd-party services should be added to Templates just like Posts and Pages. 

### What actually happened

`Invalid parameter(s): post_id` is returned and no image is added to the Template. 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Reproduced on an AT test site only. Unknown if Simple sites are affected.

**Comment by Aurorum** [comment]
Should be fixed by WordPress/gutenberg#57040 - the API is currently blocking the request because it's sending the theme slug as the Post ID, when it needs to be a number.

<img width="678" alt="Screenshot 2023-12-17 at 14 59 48" src="https://github.com/Automattic/wp-calypso/assets/43215253/5495b38e-d7b4-4fc5-9149-138c82419ab8">

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/14153300/222ebd7e-c787-4d7f-a7be-d7856444b0bb


📌 ACTIONS
- Triaged, switched to High

@glendaviesnz @fullofcaffeine any chance we can push https://github.com/WordPress/gutenberg/pull/57040 sooner than 17.4 to fix this on Dotcom?

**Comment by glendaviesnz** [comment]
> @glendaviesnz @fullofcaffeine any chance we can push https://github.com/WordPress/gutenberg/pull/57040 sooner than 17.4 to fix this on Dotcom?

I will let @fullofcaffeine respond to this as I am not familiar with the dotcom release cycles and what is involved in getting patches pushed.

**Comment by liviopv** [comment]
I tested this further and this is blocking *any* image uploads to templates when using a block theme. Updated the title to match.

**Comment by liviopv** [comment]
With the 17.2.4 patch that includes https://github.com/WordPress/gutenberg/pull/57040, this is the current state of the issue on WordPress.com:

### Simple Sites
✅ Direct uploads
✅ Pexels 
✅ Openverse

### Atomic Sites
🚫 Pexels
🚫 Openverse
✅ Direct uploads

**Comment by ramonjd** [comment]
I'm having trouble reproducing on an Atomic site connected to WP via Jetpack. 

Could folks trace the error to a particular endpoint? Is it the attachments endpoint, and this WP_Error?

https://github.com/WordPress/wordpress-develop/blob/add61a8d7c5c5280155dbfcb1a7e058005e80b7d/src/wp-includes/rest-api/class-wp-rest-request.php#L848

**Comment by ramonjd** [comment]
> Could folks trace the error to a particular endpoint?

Oh sorry, I see that it's coming from a ~WPCOM~ Jetpack endpoint.

I think here: 
https://github.com/Automattic/jetpack/blob/f43a439ea2a1fa3e24311cef6a197f73bbd75c04/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php#L143

Related: p1703590834062169-slack-C02FMH4G8

~~My instinct is that this will require either:~~

1. ~~A change in the backend WPCOM endpoint~~
2. ~~Data handling in Calypso before adding external media, e.g in the [hook](https://github.com/Automattic/wp-calypso/blob/8bed34a2fd824aa396499d30b1be2c5bde91fb92/client/data/media/use-add-external-media.js#L11) or [component](https://github.com/Automattic/wp-calypso/blob/627e76291fbac621945bcaf0ab6d6b0de24cd05e/client/post-editor/media-modal/index.jsx)~~.

_Edit_: updated after realizing the endpoint is in Jetpack. 👍🏻

**Comment by Aurorum** [comment]
Sorry - this is a little late, but looks like you've already found this endpoint. Not sure if this will be helpful (sorry if not!), but when I looked into this, I suspected the problem is that `post_id` still returns the theme string, while it only accepts a number for the post ID: https://github.com/Automattic/jetpack/blob/f43a439ea2a1fa3e24311cef6a197f73bbd75c04/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php#L145

It might be worth adding a check to see if it's a string and forcing that to be `0` if it's not possible to wait for the Core fix.

**Comment by ramonjd** [comment]
> if it's not possible to wait for the Core fix

I'm working on a Gutenberg PR at the moment. The idea is to always send a numerical ID, and where one doesn't exist, then `0`.

**Comment by ramonjd** [comment]
Here we are:

- https://github.com/WordPress/gutenberg/pull/57388

**Comment by ramonjd** [comment]
Hi folks! Me again.

So, https://github.com/WordPress/gutenberg/pull/57388 ensures that we will always send a numerical ID where we can. 

It will make things more consistent, but I don't think it will address this specific issue completely. 

What I've discovered is that simple sites use a different endpoint to Atomic sites. See: https://github.com/Automattic/jetpack/blob/a77f281222d73d7a0db33bf865ee3dde0f98b0cc/projects/plugins/jetpack/extensions/shared/external-media/sources/api.js#L6-L6

The simple site endpoint has a built-in type coercion and fallback, e.g., `(int) $data['post_id'] ?? 0;`

The Atomic endpoint `/wpcom/v2/external-media/copy/` however, expects `post_id` [to be a number.](https://github.com/Automattic/jetpack/blob/f43a439ea2a1fa3e24311cef6a197f73bbd75c04/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php#L145).

I'm having trouble getting a reliable Jetpack env running to test this, but here's what I think is happening: 

the non-number type will snag in [sanitize_params](https://github.com/WordPress/wordpress-develop/blob/add61a8d7c5c5280155dbfcb1a7e058005e80b7d/src/wp-includes/rest-api/class-wp-rest-request.php#L845), due to the [default sanitize_callback](https://github.com/WordPress/wordpress-develop/blob/add61a8d7c5c5280155dbfcb1a7e058005e80b7d/src/wp-includes/rest-api/class-wp-rest-request.php#L825C42-L825C64) of [rest_parse_request_arg](https://github.com/WordPress/wordpress-develop/blob/60c3fe8534da1e06001e8df05da2966dd3313317/src/wp-includes/rest-api.php#L1420), which then calls [rest_validate_request_arg](https://github.com/WordPress/wordpress-develop/blob/60c3fe8534da1e06001e8df05da2966dd3313317/src/wp-includes/rest-api.php#L1377), which then calls [rest_validate_value_from_schema](https://github.com/WordPress/wordpress-develop/blob/60c3fe8534da1e06001e8df05da2966dd3313317/src/wp-includes/rest-api.php#L2153), which returns the type error. 🤣 

So, I think what's left is to ensure Jetpack doesn't send a non-number value to `/wpcom/v2/external-media/copy/`.

If it's being sent a string, which is the case for templates, whose ids are `theme//template-name`, it will fail and cause the problem in question. 

I have a test PR up in Jetpack:

- https://github.com/Automattic/jetpack/pull/34795

**Comment by liviopv** [comment]
Just documenting here what I shared in p1704540926566469/1703590834.062169-slack-C02FMH4G8:

- Image uploads to templates are broken again with Gutenberg 17.3.1 running on Atomic and Simple Sites
- Pexels and Openverse are working on Simple Sites, but not Atomic.

Current status:

### Simple Sites

🚫 Direct uploads
✅ Pexels
✅ Openverse

### Atomic Sites
🚫 Direct uploads
🚫 Pexels
🚫 Openverse

Video of an upload on Atomic:


https://github.com/Automattic/wp-calypso/assets/14153300/d1768370-163f-4cb7-8e96-3815b852169d

**Comment by zdenys** [comment]
- [ ] 7544221-zd-a8c Turning off Gutenberg did the trick. Let's please follow up with them so they can turn it back on after the fix.

**Comment by ghost** [comment]
- [ ] 7541773-zd-a8c
Told them to try to upload to media folder and try that way
Let's please follow up with them as well.

**Comment by upwardmomentum84** [comment]
7545526-zd-a8c Advised to upload images to media library and use the Select Image > from Media library option.

**Comment by nicolynramos** [comment]
7548013-zd-a8c 
7548192-zd-a8c
Unable to use any of the image blocks- even to upload from Media Library.. Deactivated Gutenberg and that fixed it.
<img width="445" alt="Screenshot 2024-01-07 at 8 50 18 AM" src="https://github.com/Automattic/wp-calypso/assets/71851343/c5c1d9d2-a431-4a64-9ac5-50e26a579857">

**Comment by kathrynwp** [comment]
Another report: 7548341-zd-a8c

Advised to upload to Media Library first or deactivate Gutenberg but they said the same issue is also happening when uploading to the Media Library.

**Comment by jp-imagines** [comment]
This issue appears to have been fixed again, per p9o2xV-3Kw-p2.

I can't replicate on Simple or Atomic anymore on my test sites. I'm not sure about the latest report above though.

> Unable to use any of the image blocks- even to upload from Media Library.. Deactivated Gutenberg and that fixed it.

@nicolynramos These look to be for a different issue related to AMP instead: https://github.com/Automattic/wp-calypso/issues/86062

**Comment by rickmgithub** [comment]
2 cases in the last few minutes.
- 7556498-zen
- 7556436-zen
