### ISSUE TITLE
Publicize: display result in notice

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#8547]
Blocked by #8546

Currently, notice is not really displaying result of the action. It is displaying endpoint result, but its not if post went out or not, but mock response.

Also, we should link to the post in notice.

IDEALLY, we should fetch the post and display how it looks like right in the window.
CC @drw158 in the above - would that make a good design?

**Comment by iamtakashi** [comment]
+1 for including the link to the post on social media.

I assume we need a notice for each connected service if you shared more than one services. Because it might fail for one service while it successes for everything else. Something like this?

![image](https://cloud.githubusercontent.com/assets/908665/23276093/ed4ea4d2-fa00-11e6-9737-626484fd5ce3.png)

I'm not sure we need to fetch the social post. Preview before sharing is no-brainer but after sharing link to the post should be enough as I assume a majority of users want to see it on the social media anyways.
