### ISSUE TITLE
Tasklist Block can sometimes crash the Editor

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#85664]
See p1703177396699499-slack-C02FMH4G8 and p58i-gah-p2.

Two different reports:

> I’m writing a post and I want to convert the bullets to a checklist using the Gutenberg tools. Every time I try to do so from either the p2 front end or the dashboard editor the whole post disappears on me and spits out an error.  I converted the bullets to paragraphs by deleting the bullet (not using the transform menu) and then was able to turn the paragraphs into tasks without any trouble.

>  I was unable to take the first list from this post and turn it into a task list block. Clicking on Task in the Transform To popover would cause the Editor to crash.

**Comment by obenland** [comment]
It looks like [this map call](https://github.com/Automattic/p2/blob/603e019e5754abc9bcebc9e04e916cbdc9e9cabb/plugins/p2-blocks/src/p2-changelog/transforms.js#L24) is what's breaking.

**Comment by obenland** [comment]
Turns out `__UNSTABLE_LINE_SEPARATOR` was indeed unstable. It was removed in Gutenberg 16.7 https://github.com/WordPress/gutenberg/pull/54310
There is [one more instance in p2-blocks](https://github.com/search?q=repo%3AAutomattic%2Fp2%20__UNSTABLE_LINE_SEPARATOR&type=code) that will need to be updated.

**Comment by okmttdhr** [comment]
This is fixed by https://github.com/Automattic/p2/pull/6237
