### ISSUE TITLE
Demo product categories getting re-added whenever WooCommerce is updated/re-activated

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#85793]
### Quick summary

Woocommerce theme demo content categories (but not products for some reason) are getting added to site every time WC updates or is reactivated (like after a conflict check)
The headstart action getting triggered appears to be this one: fbhepr%2Skers%2Sjcpbzfu%2Ssrngher%2Qcyhtvaf%2Surnqfgneg%2Qjbbpbzzrepr%2Qgrezf.cuc%3Se%3Q98q9po0o%26zb%3Q2858%26sv%3Q63%23277-og

This should not be happening. If it happens automatically at all it should probably only happen when a WC theme is newly installed.

related to https://github.com/Automattic/themes/issues/7499
[p9F6qB-dRh-p2](https://href.li/?https://wp.me/p9F6qB-dRh)

Discussed here: p1703416853344829-slack-C7U3Y3VMY where the recommendation was to change things to "Maybe woocommerce_newly_installed instead or woocommerce_installed but checking whether the install is new or not."

### Steps to reproduce

1. On a site with woo commerce, activate a WooCommerce theme with demo categories (Amulet, tazza, etc)
2. check categories present on site (if uncategorized or andromeda appears, delete them)
3. deactivate and reactivate WC
4. check categories

### What you expected to happen

demo content should only get added when theme first activated or with approval of user

### What actually happened

demo categories are re-added every time WC is updated or reactivated

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Repro here https://github.com/Automattic/themes/issues/7499#issuecomment-1870137474

📌 ACTIONS
- Triaged

**Comment by liviopv** [comment]
Moving interactions from theme issue:

- [ ] 6689412-zd-a8c
- [ ] 7313467-zd-a8c

**Comment by Nic-Sevic** [comment]
additional discussion here: p9F6qB-dRh-p2#comment-57179

@daledupreez @adrianduffell pinging you for awareness or additional insight you might have since you already started looking at this

**Comment by andres-blanco** [comment]
This is the outline for a possible solution.

Add a new option called `woocommerce_should_run_headstart_for_theme`. This option must be set to the string `yes` when:
 1. A new site is created through `/setup/ecommerce` . This can be hooked into this function fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qarj%2Qfvgr%2Qraqcbvag.cuc%3Se%3Q3rn81p78%2313-og by conditionally filtering by `$site_creation_flow`.
 2. A theme bundled with woocommerce is added to a site. We can add a `woocommerce_should_run_headstart_for_theme` entry to the settings by modifying this list: https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php#L886. When a site is [about to be transferred to AT, before the initiateAtomicTransfer call](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/bundle-transfer/index.tsx#L117), we could make a call to update the settings by doing something similar to what [is being done here](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/store-address/index.tsx#L190).

In order for this approach to work, we should add the `woocommerce_should_run_headstart_for_theme` option to this method: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sjbn.cuc%3Se%3Q89n14732%26sv%3Qjbn_trg_genafsre_bcgvbaf%23jbn_trg_genafsre_bcgvbaf-og, this way it will be copied when the site is transferred.

If we manage to set that option before transfer occurs then we could modify this code on wpcomsh: `feature-plugins/headstart-woocommerce-terms.php#L16` to only run if the `woocommerce_should_run_headstart_for_theme` is present, otherwise return. If the code runs, the last thing it does must be removing the option.

We talked about this with @daledupreez, so please feel free to chime in if you feel something is off.

**Comment by sixhours** [comment]
I added the new site option to the whitelists in `woa.php` as well as `atomic-v2.php` in D136585-code

**Comment by sixhours** [comment]
Added the site option to the `/setup/ecommerce` API endpoint here: D136760-code

**Comment by sixhours** [comment]
Some more discussion of how to go about this in Slack, adding link here for posterity: p1707143138219899-slack-C0Q664T29

**Comment by daledupreez** [comment]
@sixhours, given that we've shipped https://github.com/Automattic/wpcomsh/pull/1665, can this issue be closed?

**Comment by sixhours** [comment]
Yep! Closing this out, thanks for the nudge :)
