### ISSUE TITLE
 Domain Search: confusing error message when looking up a subdomain

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#859]
Originally reported by @supernovia and @SiobhyB.

Steps to reproduce:

- Go to wordpress.com/start or wordpress.com/domains
- Type a subdomain in the site name box
Receive message: "Sorry, but _____ does not appear to be a valid domain name." Regardless of the subdomain used.

**Comment by klimeryk** [comment]
The problem here is that the user has to click the `Map` button to map it (both on the start and domain pages). Then, he'll be presented with a different input box, where he can input a subdomain and successfully map it.
I agree that the wording of the error is confusing - it should be a warning at most that should hint that since this is a subdomain, the user should try mapping it.

**Comment by kriskarkoski** [comment]
I had a user run into this error today and didn't know how to get around it myself until I found this issue.

**Comment by klimeryk** [comment]
Thanks for the info, @kriskarkoski :bow: This is issue is on our radar, but it'd be best to fix it along with a general overhaul of the domain mapping UX (#2443). I'll ping our designers there to see if there's an ETA so we know how to proceed (wait for the designs or hack a fix now).
