### ISSUE TITLE
Editor: have cursor remember position when switching between Visual and HTML

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#8592]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Create a new post and add some content in the visual editor.
3. Position the cursor at a specific point in the post.
4. Switch to the HTML editor
#### What I expected

That the cursor would be at the position it was when I switched editors, so I can easily edit the relevant section's HTML
#### What happened instead

The cursor jumped to the top of the post, meaning I'd have to search again for the section I need to edit.
#### Browser / OS version

Happens across browsers and OS's
#### Screenshot / Video

![html](https://cloud.githubusercontent.com/assets/11873759/19196392/a403cf2c-8cb5-11e6-8b76-c44cf3ca3408.gif)
#### Context / Source

This was reported by a user via Twitter. In very long posts or posts with complex HTML formatting the current behaviour leads to a very cumbersome editing experience. Making the cursor "stick" when switching editors can make a big difference to users who regularly edit content using both views.

**Edited to add:** The highlighting in the video is just for emphasis. The cursor jumps to the top regardless of whether text is highlighted or not.

**Comment by lancewillett** [comment]
> In Visual mode, I would like to place my cursor where I want to edit the html, and when I select the HTML tab, the cursor is at the relevant spot in HTML – and vice-versa

Suggestion in 3083258-t

**Comment by lancewillett** [comment]
[Anecdotal flowsharing](https://test.wordpress.com/2016/11/04/calypso-wp-admin-parity/) from @ryanboren 

> The wp-admin editor keeps the Visual and Text tabs visible on screen when vscrolling. I can switch between the two without losing cursor position in the Visual tab. This is a big deal for me, as I often switch between the two modes to work around editor bugs and add ids to headers.

**Comment by ryanboren** [comment]
I call this #scroll-scan-correlate flow.

- Switch tabs
- Scroll down
- Scan for where you were in the other tab
- Correlate back and forth between the two tabs

I also experience this in media pickers that don't provide images accessible to my presbyopic eyes. Scroll, scan, correlate is physically and mentally tedious and smashes my cognitive stack. I'll forget what I was doing while doing the scan-and-correlate context gymnastics.

https://test.wordpress.com/2016/05/13/full-width-media-views-during-selection/
https://test.wordpress.com/tag/scroll-scan-correlate/

**Comment by designsimply** [comment]
Notes from https://horizonfeedback.wordpress.com/2017/03/03/call-for-testing-calypso-html-toolbar/#comment-343

<blockquote>I am glad I can insert images in HTML mode because that gives me more control over where they actually appear. (Images I insert in Visual mode often must be moved in HTML mode.) On the other hand, I always want to override the default alignment. If I am not sure how to tweak the HTML attributes directly, I can switch to the Visual tab. But I need to find the image again on the Visual tab. I realize that it would be tough to maintain a tight correlation between editing cursor positions on the HTML and Visual tabs, but it would be helpful if the cursor position in one tab could be *approximated* when switching to the other.</blockquote>

**Comment by lancewillett** [comment]
This fix is in-progress! https://github.com/Automattic/wp-calypso/pull/17481#issuecomment-326972568

**Comment by lancewillett** [comment]
Closing with https://github.com/Automattic/wp-calypso/pull/17481
