### ISSUE TITLE
"Read More of this Post" not working on Email Subscribers

### ISSUE THREAD

**Issue by deityjoyaira** [Automattic/wp-calypso#86037]
### Quick Summary

The user reported that several subscribers couldn't click the "Read more of this post" link on their email newsletter.

### Steps to reproduce
(Include the URL it occurs on, the site's plan, and the site's theme)

Theme: Gateway

1. Changed theme to Gateway
2. Created a Test Post
3. Sent a test email

Note: I tried to replicate the issue using the same theme, Gateway - but didn't encounter any error or issue.

### What you expected to happen

"Read more of this post" is not a link hence cannot be clicked

### What actually happened

I tried to replicate the issue using the same theme, Gateway - but didn't encounter any error or issue.

![image](https://github.com/Automattic/wp-calypso/assets/96191442/fd29c976-f502-4fb4-b516-8979bc23b055)

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Browser / OS version
- Google Chrome
- Windows 11

### Context / Source
* Ticket: https://a8c.zendesk.com/agent/tickets/7533266
* Slack: https://a8c.slack.com/archives/CJDUN89L1/p1704375818717799
* Other notes

#bug-report

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate /
- Tested on Atomic –  Could Not Replicate


📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to replicate this on a test site, using Blocks or using the Classic Editor as the user has. I did notice that the user _does not_ have a Read More link anywhere on the post itself; some other setting is causing that break mid post.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by jp-imagines** [comment]
New report: 7502750-zd-a8c (using block editor, Baskerville 2 theme)

This user has a series of posts that never experienced this issue, but their latest few have. They've done some troubleshooting to try to isolate things, but the results are a bit strange:

* Most posts follow the exact same format: columns with previous/next links, four images, two Separator blocks, four more images, and then a few paragraphs (with the same text in each post). The "read more of this post" link in notification emails for _all_ of these posts work without issue.
* Their latest few posts had a slightly altered format: between the two Separator blocks was a single paragraph containing a couple links. Otherwise, the posts are identical to the ones above, but these posts _all_ experience the issue: the "read more of this post" link in the notification email renders as plain text.

Based on the discussion in https://github.com/Automattic/jetpack/issues/34372, it looks like the "Read more of this post" link comes from the `For each new post email, include` setting at _Settings > Reading_ being set to **Excerpt**. (This user has not been using More blocks, and adding a More block to the post creates a duplicate link in the email – "Continue reading [post title]" – confirmed by this user and that other issue discussion.)

Re-opening this issue.

**Comment by jeherve** [comment]
cc @Automattic/apex , who worked on fixing https://github.com/Automattic/jetpack/issues/34372 a few weeks back.

**Comment by ivan-ottinger** [comment]
Thank you for the report!

I was able to reproduce this issue. So far it looks like it could have been unintentionally introduced in D125066-code.

Basically what happens is that the function that trims the content into excerpt breaks it in the middle of a style attribute:

![Markup on 2024-01-12 at 18:16:46](https://github.com/Automattic/wp-calypso/assets/25105483/d5ddcec0-8ce5-43b2-89d1-c202f95946f8)

After that, the whole email content is run through a CSS emogrifier that then gets confused and breaks the HTML markup around the link:

![Markup on 2024-01-12 at 16:57:42](https://github.com/Automattic/wp-calypso/assets/25105483/d18b9f5d-2497-4a0f-ba97-88ddd806b382)

I am also a little suspicious about the following in the post content - maybe it could be in play as well:

![Markup on 2024-01-12 at 18:47:46](https://github.com/Automattic/wp-calypso/assets/25105483/03841153-75a6-45ca-9a97-f39268f5dc68)

We will look into this in our team next week.

@JuanLucha @phcp - maybe you would have more context of the inner workings of the change we introduced in that patch above. We can look at this together next week as well. 🙂

**Comment by TimBroddin** [comment]
I'm working on a solution for this.

**Comment by simison** [comment]
@TimBroddin found anything yet?

**Comment by TimBroddin** [comment]
Thanks for the ping @simison . 

A summary of the problem: in order to make the links in post excerpts trackable a PR was merged that allowed HTML in the excerpts. The word count in this PR was very basic, as it counted attributes etc as words, and just cut the string without considering closing tags.

I have a PR ready ( D134853-code ) that only counts "real" words, but in order to make it robust, it needs to parse the excerpt with `DOMDocument`, and this is not super fast. I actually tried writing my own basic HTML tokenizer but too many edge cases.

I was going to discuss this with the team today, but maybe you're in a better position to make decisions / give guidance here:
1. Is it worth having HTML in the excerpts? Or should we just strip it all tags?
2. Currently, the call to generate an excerpt is made for every email sent. Is there any scenario where the excerpt might be different between mails (I'm thinking paywalled content). Should we optimize this before merging my PR?
3. Should we implement caching for the excerpt trimming, so we only call the HTML parser once ? `wp_cache_get( 'excerpt_trim_' . sha1( $html ) )`

**Comment by simison** [comment]
> Currently, the call to generate an excerpt is made for every email sent. 

Why is that, instead of just when it's actually outputted?

> Is it worth having HTML in the excerpts? Or should we just strip it all tags?

Are you using core's excerpt functionality or something custom? What does the WP core one do?

Stripping all tags might be fine but I'm worried if there are only things like quotes or images in the post, and nothing else.

Have you looked into [`wp_html_processor`](https://developer.wordpress.org/reference/classes/wp_html_processor/)?

> Currently, the call to generate an excerpt is made for every email sent. Is there any scenario where the excerpt might be different between mails (I'm thinking paywalled content). Should we optimize this before merging my PR?

If the entire post is paywalled, we won't send the free version to anyone. If there's a paywall block, we send the post and show content until the paywall. 

The excerpt in that case should also be from the portion that's until the paywall, which could be early in the document, e.g. after first short paragraph block or an image, so no text.

**Comment by TimBroddin** [comment]
> Why is that, instead of just when it's actually outputted?

This has always been this way. The async job calls `Subscription_Mailer->send_post` for every subscription (and thus subscriber). Inside this function the post is rendered (over and over again).

Some filters that run on the content, such as the Emogrifier which inlines the CSS styles, are already cached.

> Is it worth having HTML in the excerpts? Or should we just strip it all tags?
> Are you using core's excerpt functionality or something custom? What does the WP core one do?

Yes, the core's excerpt functionality strips out all tags. 

See also this alignment P2 by @JuanLucha : pdDOJh-2yQ-p2
And this core PR which has been open for 14 years 😀 https://core.trac.wordpress.org/ticket/12084

> Have you looked into [wp_html_processor](https://developer.wordpress.org/reference/classes/wp_html_processor/)?

Yes, I did but I couldn't get it to work for this particular use case. I found keeping track of nesting difficult.
 When searching for other similar use cases in the code I saw that `DOMDocument` is commonly used for this, and the implementation was way easier.

--

Thanks for your questions; it made me investigate the issue deeper and gave me a clearer idea about how to move forward.

I think we either: 
-  Don't allow HTML in excerpts, like it was before. We can then prevent email clients from auto-linking URLs, by adding an extra filter, like we do in the comment subscriptions emails for example ( fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Srznvy%2Qfhofpevcgvbaf%2Sfhofpevcgvba%2Qznvyre.cuc%231792%2Q1792-og )
- Allow all HTML, and cut the excerpt using a modified version of my PR ( D134853-code ). We could cache the result like Emogrifier does, which would make it less expensive to do.

**Comment by TimBroddin** [comment]
@simison any thoughts on this?

I'm most inclined to go with option 1 because I can see option 2 creating lot of side effects (quote blocks being cut after 1 word, multi-column posts missing a whole column, ...). But I'm willing to further explore 2 if you think that's the best way forward.

**Comment by yansern** [comment]
I think I'm convinced Option 1 is the way to go.

**Comment by simison** [comment]
Let's try without tags 👍

**Comment by TimBroddin** [comment]
I'll make the changes necessary!

**Comment by TimBroddin** [comment]
Solved with D135301-code

**Comment by RealCarFax** [comment]
Hm, I'm seeing the same (or similar?) issue on 7588002-zen
In reviewing one example post with this issue reported by the customer, I don't see any quote blocks in the post - only paragraph blocks and an image block. For now I have recommended for the customer to try out the More block as they are not using that currently.
This is an Atomic site using a child theme from the parent theme Blockbase.

**Comment by ivan-ottinger** [comment]
> Hm, I'm seeing the same (or similar?) issue on zd-7588002
In reviewing one example post with this issue reported by the customer, I don't see any quote blocks in the post - only paragraph blocks and an image block. For now I have recommended for the customer to try out the More block as they are not using that currently.
This is an Atomic site using a child theme from the parent theme Blockbase.

Thank you for the report, @RealCarFax.

I have looked at the post the user is referring to (in 7588002-zd-a8c) and sent myself a test email. The _"Read more of this post"_ link worked correctly - even when I tested it without the fix (D135301-code) we introduced last week.

Would it be possible to ask the user to forward the whole email to us so we can take a look at it? Cheers.

**Comment by RealCarFax** [comment]
Thanks @ivan-ottinger for looking into this and the recommendations. I just checked the ticket and I see that the customer has already reported that the issue is resolved. Sounds like a mail client issue or something else on their end, perhaps. Sorry for the additional work created here and again, I appreciate you looking into this!

**Comment by ivan-ottinger** [comment]
No worries, @RealCarFax! My pleasure! 🙂

I am glad that everything is working well for the user.
