### ISSUE TITLE
Editor/Consistency: Different font/alignment in use

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#8604]
In the Editor, under "More Options", we have this:

<img width="283" alt="screen shot 2016-10-07 at 1 39 44 pm" src="https://cloud.githubusercontent.com/assets/108942/19203290/adaeb0e0-8c93-11e6-9346-7f9273624d19.png">

Everywhere else in the sidebar, we are using the sans-serif font (like for the "Search" label for Location), and it's left-aligned. Here we have a center-aligned prompt (Search for Location), and we have a serifed font (Excerpt). Both should be updated to be our standard sans-serif, and left-aligned.

**Comment by rickybanister** [comment]
'Write an excerpt' is using Merriweather because that is the user's content. Anywhere we have 'content' aka the user's voice we use Merriweather.

The search, however, is 'interface'. 

It's weird that it's centered, or indented, that's probably a bug slipping through from the search card component. It should be left-aligned properly.

**Comment by folletto** [comment]
> 'Write an excerpt' is using Merriweather because that is the user's content. Anywhere we have 'content' aka the user's voice we use Merriweather.

+1 

> It's weird that it's centered, or indented, that's probably a bug slipping through from the search card component. It should be left-aligned properly.

It seems there's some added padding to that specific component: `.editor-location__search .search__input`. Odd. I'm not sure why, but just removing padding works.
