### ISSUE TITLE
Subscriptions: No Longer Possible to View Email-Only Subscribers

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#86382]
### Quick summary

It's no longer possible to distinguish between WordPress.com subscribers and Email subscribers under the Users section. 

### Steps to reproduce

1. Head to Stats > Subscribers
2. Select the toggle to view "Email" subscribers
3. This will only display the most recent ones, so click "View all"

<img width="638" alt="Screenshot 2024-01-14 at 10 35 27" src="https://github.com/Automattic/wp-calypso/assets/43215253/7ec1f439-2d0a-4560-bb35-d2a184bef04d">

### What you expected to happen

I should be brought to a screen which allows me to filter out WordPress.com subscribers and only display email ones; this used to happen. 

### What actually happened

I am unable to distinguish between WordPress.com and email subscribers - the Gravatar suggests that they are WordPress.com, but there's no easy way of filtering them out. 

<img width="1132" alt="Screenshot 2024-01-14 at 10 41 02" src="https://github.com/Automattic/wp-calypso/assets/43215253/3e8d82c6-d658-4548-9771-c0968b295b30">

### Impact

Some (< 50%)

cc @pkuliga @simison - any idea on if this was intentional? Do you think a toggle could be included on the Subscribers page for the two?

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO

https://wordpress.com/subscribers/ shows all subscribers, without options to distinguish between email-only and WordPress.com subscribers.

📌 ACTIONS
- Triaged


📌 Message
@simison I feel this change might be intentional - if it is and there's no intention of re-adding the filter, feel free to close the issue. If it comes up in support (I haven't seen anything yet), we'll reopen it as a Feature Request.

**Comment by Aurorum** [comment]
> If it comes up in support (I haven't seen anything yet), we'll reopen it as a Feature Request.

Apologies, forgot to mention - this came up in Support: 7560221-zen

**Comment by Aurorum** [comment]
7598055-zen

> I have attempted to procure a list of "email subscribers" and/or "followers who receive email notifications" by Dashboard on my computer web browser, however, I have not been able to find that.

**Comment by simison** [comment]
Hi!

> any idea on if this was intentional? Do you think a toggle could be included on the Subscribers page for the two?

Yep, this is intentional. The WP.com/email differentiation in the UIs did not make sense, and was indeed giving false idea of what they even are.

Subscribers with WP.com account would get the email as well, and "email" subscribers could set to receive only reader notifications instead of emails. The difference was only if the subscriber had .com account, which isn't important from publisher's perspective. They're all subscribers receiving emails, and some of them turn emails off but still read your content e.g. via the blog or via Reader (web/apps).

You should look for email open/click rates to gauge how popular the emails are. Those stats you can find in the WordPress.com interface.

There might be some UIs around that still show the WP.com/email difference, at least in apps I know they do, but over time that's also going away.

Hope this helps! I'll close this meanwhile but fee free to ask any further questions about this!

**Comment by Aurorum** [comment]
Thanks for the detailed explanation @simison! I've passed it on to those who asked about this.

I wonder if it's still worth keeping an issue open for the "WordPress.com" vs "Email" difference in Stats then? I feel that might be confusing and deserves some UI-love.

**Comment by simison** [comment]
@Aurorum agreed it's confusing, I believe the team working on this has the issue on their tracking backlog already, and are working on it at the moment. I just don't have the link at the moment, could be in Jetpack repo.
