### ISSUE TITLE
Jetpack Connection flow: Do not offer plans to secondary Jetpack users

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#8642]
#### Steps to reproduce
1. Start from a Jetpack site that's already connected to WordPress.com.
2. Under Users > Add New, create a new admin user.
3. Log out of your admin account.
4. Log out of your WordPress.com account.
5. Log in to your Jetpack site with that new admin account you created.
6. Go to the Jetpack menu.
7. You'll be offered the option to link your account to WordPress.com.
8. When you succesfully do so, you'll be offered the option to purchase a plan for that site.
9. Since the site is already connected to WordPress.com, I don't think we should offer that option to this user at this point of the flow.

![screen shot 2016-10-11 at 10 05 41](https://cloud.githubusercontent.com/assets/426388/19263283/ea909be4-8f9b-11e6-9149-14648c98122f.png)

**Comment by johnHackworth** [comment]
As I said in slack: I see your point, but I'm not sure if I agree a 'secondary' admin couldn't be the one with purchasing decision powers. 

What do you think about it, @richardmtl & @rickybanister  ?

**Comment by rickybanister** [comment]
I agree with @johnHackworth here. It would be a different story if that site already had a plan, but there doesn't seem to be any harm in showing the plans existence here. 

The only bit that we might consider a 'bug' is that the call to action for the current plan says 'Select Free' not 'current plan'. We may want to show this step as more of a current status with a skip button if it's been seen by another site admin.

Also you meant to cc @richardmuscat not poor Richard A.

**Comment by jeherve** [comment]
This also happens for editors and other non-admins.

See p8oabR-2x-p2

**Comment by jeherve** [comment]
Also reported here: p9zhOE-yk-p2

**Comment by richardmtl** [comment]
I disconnect and reconnect my test site every once in a while. I did so today, and it was jarring to land on https://wordpress.com/plans/ for the site, especially since it already has a Pro plan. An additional aggravation was that the link back to wp-admin was "below the fold" instead of being somewhere more immediately visible.

**Comment by csonnek** [comment]
Chiming in here with the experience for a non-admin user. 

Have a site with many Editors who use the Calypso dashboard for doing their work. In helping the Admin with a connection issue, all the Editors got disconnected. When reconnecting, they get dumped to this page:

![](https://d.pr/i/Ul44e8+)

As a user, I would think that I did something wrong or that reconnecting didn't work. Perhaps we should have a different flow for people who would not be able to purchase a plan?

**Comment by worldomonation** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. **Report anew**: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. **Reopen**: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
