### ISSUE TITLE
Reader: Preserve rotation when resizing images

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#8671]
As seen at https://wordpress.com/read/feeds/2253/posts/1185089335

<img width="717" alt="fall_in_the_adk_and_hiking_cliff_mountain_ _reader_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/14350/19310922/66633d94-905a-11e6-902b-4bd0669b7459.png">

When we resize images that come from WordPress / Photon, we're currently stripping all of the "extra" parameters past size. We should keep the rotation attributes (and likely the crop ones?) so images look correct in the Reader.

**Comment by tellyworth** [comment]
I think this is a slightly different issue than suggested here.

The two sideways images in that particular post are http://www.jenisgreen.com/wp-content/uploads/2016/10/IMG_4648-e1476275508344-600x800.jpg and http://www.jenisgreen.com/wp-content/uploads/2016/10/IMG_4651-e1476275603302-600x800.jpg.

I think both images have been incorrectly encoded with EXIF orientation values. They both have orientation 6, which means "rotate me 90º clockwise to display". But if you obey that display them in that orientation, they're sideways. I'm guessing this happened during resizing: the resizer (WP itself?) correctly rotated the image from landscape to portrait when it was resized, but incorrectly left the orientation flag in place.

Browsers normally* ignore the EXIF orientation. That means the [original page](http://www.cairnsandcarrots.com/2016/10/12/fall-in-the-adk-and-hiking-cliff-mountain/) dumbly displays the images with no rotation. So they ignore the (incorrect) orientation and show them in portrait orientation. This seems to be the case with or without Photon. You can verify this by viewing the page in Safari on iOS, which, unusually, does honour the EXIF orientation value. Those two images display sideways on iOS, exactly like Reader.

Reader appears to be honouring the (incorrect) orientation value - unlike a regular web page. I'm not sure why or how. Photon returns an image that is [functionally identical](https://i2.wp.com/www.jenisgreen.com/wp-content/uploads/2016/10/IMG_4648-e1476275508344-600x800.jpg) - that is, it has portrait pixels and the incorrect orientation flag. It is possible to strip off the bogus EXIF orientation flag by using `?strip=all` in the Photon url, but I think that's just masking the underlying issue. There are no documented rotation parameters to Photon, except to say that the `strip` parameter will rotate the image and remove its orientation flag (if I'm reading it correctly).

The exact issue seen here is probably pretty rare, since it needs an incorrect orientation flag on the image. But you can wind up in a related situation with stock WordPress, since its built-in resizer seems to ignore and strip the orientation flag on smaller sized images, while leaving the flag intact on the full size version.  Either way, it is pretty likely that we are sometimes "incorrectly" displaying images - in the sense that they appear differently from how they're displayed in the original web page. Whether the fix is in Photon parameters (like the `strip` hack) or elsewhere, I'm not sure; but I think we should probably ignore the orientation flag most of the time, to be consistent with normal browser behaviour.

 * Modern browsers do appear to apply rotation when viewing an image URL directly. This leads to the confusing situation where images are rotated one way in-page, but a different way when you Open Image In New Tab.

**Comment by bluefuton** [comment]
We've not seen any further reports of this, so closing for now.
