### ISSUE TITLE
Checkout: Improve feedback and validation for the postal code field

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#8681]
Steps to reproduce
1. Starting at wordpress.com/checkout
2. Select Netherlands as the country.
3. Input ZIP code 9276DD (one word, no spaces)
4. Note the error message: "Controleer of dit een geldige postcode is." translates to "Make sure this is a valid zip code."

What I expected
- A more helpful error message and/or for the ZIP code to auto-recognize the lack of a space and fix it. This particular ZIP code needs a space between the numbers and the letters to be recognized as valid.
# user-report

**Comment by rwaynick** [comment]
This issue is also present for zip codes in Brasil.

If there isn't a dash before the last three digits the user gets an error. 

<img width="753" alt="1" src="https://cloud.githubusercontent.com/assets/10882502/20835836/c7ea83fa-b883-11e6-9714-81bed0258a99.png">

It's accepted if the dash is added. I would expect that it would work with or without the dash.

<img width="786" alt="2" src="https://cloud.githubusercontent.com/assets/10882502/20835843/ce3c00f8-b883-11e6-94d9-84011cac9914.png">

#user-report
#540598-chat

**Comment by supernovia** [comment]
We had some feedback from a user, too, who was confused about the term zip code, though their country does not offer zip codes. Is this something we could also address or should I file another request?

**Comment by klimeryk** [comment]
@supernovia Thanks for reporting, but actually, the user is mistaken here - Ireland has rolled out post codes a few years ago and _everybody_ in Ireland have post codes (called [Eircode](https://www.eircode.ie)). Actually, every address in Ireland has a unique post code assigned to it (cool stuff, IMHO) - and those post codes are strictly checked on the registry side, so we have to require them from the users too. Though, I can imagine that some people are used to not having a post code or just missed/ignored the news. However, as mentioned, we _have_ to require a valid post code from them.
The user also mentioned that we require post code in "American format" - of course, that's not true, it's a country-specific format, in this case, the mentioned above Eircode.
I agree however that the UX is crappy regardless of the country, which is what this issue is about :)

**Comment by mahangu** [comment]
Just making a note that in 3343594-t, a Cayman's Island user had trouble entering their postal code as:

> KY1 NNNN

I checked the post code format - http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/cymEn.pdf - and sure enough, a dash was missing in between the two blocks.

I tested in Calypso and `KY1-NNNN` worked. Ideally, we should suggest a `-` there.

**Comment by klimeryk** [comment]
Thanks, @mahangu, that's a great suggestion 👍 (probably applicable to other countries that require dashes)

**Comment by hewsut** [comment]
cc @ramonjd @deBhal (let's bump this up? @cecilerainon spotted it too in the issue noted above)

**Comment by cecilerainon** [comment]
Yep, that was me for the screencast. My understanding is that UK postal codes can have from 5 to 7 characters and require a space. I'm guessing a fix could be a tooltip showing the format to the user (eg: Format must be XXX XXX or XX XXX or XXXX XXX). This tooltip could appear according to the country selected in the other field, so let's say for France, the tooltip would: "Format must be XXXXX"

**Comment by klimeryk** [comment]
That's how I've done it before, but it was deemed bad UX :) To be honest, for the message to be helpful for UK postal codes, it had to be _very_ verbose, like something you mentioned "Format must be XXX XXX or XX XXX or XXXX XXX", but even more crazy like "Format must be ANN AAA or AN ANA or ANNA NAN, where A is a letter and N a number", but even _that_ is not accurate, because even if a letter is permitted on a given place, depending on the position of that place and previous symbols in the postal code, the allowed range might differ... (same for numbers, of course) Seriously, WTF, UK.

All that to say, that it'd be better to create an autoformatting field, kinda like we now have for the phone number, that would do that formatting for the user. We've tried the other way and it just created a different type of confusion.

**Comment by sarahmonster** [comment]
Enforcing or specifying a particular format is pretty poor UX and, quite frankly, every time I see this done, I think it's a band-aid for lazy programming. :)

Wouldn't the simplest solution here be to just strip out any spaces (from both the postcode entered and target postcode format) when doing the comparison? Spaces aren't technically required in UK postcodes, and I can't think of anywhere where the presence or lack of a space would make any difference whatsoever, so you don't need them in there at all.

If ANN NAA matches, there's no good reason why ANNNAA shouldn't.

**Comment by klimeryk** [comment]
You'd assume so, but the registries we submit the request to actually register the domains _do_ require a specific format for a lot of these fields, especially phone number and postal codes - it's not just our laziness :)
> Spaces aren't technically required in UK postcodes

Actually, [they are](https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Formatting):
> Each post code is divided into two parts separated by a single space: the outward code and the inward code respectively.

I understand that some might choose to drop that space, but it _is_ required by the standard (which is unnecessary complicated, but what are you going to do) and that's what we are required to provide to the registries.

In case it was not clear - I'm not advocating enforcing a specific format on the user. Like I mentioned, we need a field that will do that _for_ the user. Of course they should not care if they put the space there or not.

**Comment by ramonjd** [comment]
I agree we shouldn't be too demanding in relation to spaces or hyphens, at least on the client side.

Could we have a combination of approaches? If a registry requires special characters or spacing in the post code, perhaps we could offer a very generic example in the `label` or placeholder attribute, and then execute some sort of auto-formatting/normalisation on the field.

<img width="248" alt="screen shot 2017-10-16 at 3 14 32 pm" src="https://user-images.githubusercontent.com/6458278/31595121-255f189c-b285-11e7-8258-50ffc07f2e53.png">

**Disclaimer**: I'm running a risk of over-emphasising the UK as an example as I've not looked at all of the post code formats, and also trivialising the pattern matching required :)

**Comment by klimeryk** [comment]
That looks really nice, thanks, @ramonjd 👍
Actually, UK is the most complicated case here. In basically all others, a simple `AA-NNN` placeholder is enough. See https://github.com/Automattic/delphin/issues/373#issuecomment-237606401 for the previous discussion on the topic and the reasoning that was used to drastically simplify the validation error message.

**Comment by deBhal** [comment]
I've been looking into this a bit, so I wanted to dump my thoughts here brain, so I 'm going to brain dump here in the hope that it helps somebody.

I've been doing some res

Adding front-end validation is great for UX, and I'm totally for that, but you still have to have solid server-side validation, so I’ve been thinking about that.

I'm gravitating towards adding paired `normalize()`/`denormalize()` functions on the backend to make sure that non-sematic formatting doesn't cause validation errors for users or registrars.

All of the non-optional spaces in our postcode validations are a fixed distance from the beginning or end of the string, so we can definitely do spaces. We also upcase everything in Calypso already, so that seems pretty safe too.

The Brazil hyphen is also no problem. I'm not sure about other hyphens, but we could take a look.


UK itself does break down pretty cleanly once you've stared at it for long enough. It always has a space 3 digits from the end, and the part of the string before that is the "outward code", and the second bit is the "inward code".

The existing regex checks whether the first bit looks like an outward code, and then that the second bit looks like an "inward code", so we could easily factor out those two parts, and be able to say '%s is not a valid outward code'. We could go arbitrarily further, and e.g. have a regex to specifically check 'inward codes do not use the letters "CIKMOV"', but that seems like overdoing it.

What we're currently using is based on the "official" regex (see [wiki/Postcodes_in_the_United_Kingdom](https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom)) which takes the rather interesting approach of looking at the [list of postcode areas](https://en.wikipedia.org/wiki/List_of_postcode_areas_in_the_United_Kingdom) and analyzing them letter by letter. This means you can take the first letter from one real postcode area and the second letter from another and you've got yourself a false positive :/

**Comment by ramonjd** [comment]
> Adding front-end validation is great for UX, and I'm totally for that, but you still have to have solid server-side validation, so I’ve been thinking about that.

At the moment, backend validation happens _fairly_ quickly, and I agree with @deBhal that solid server-side validation is important to get right, and I'll go further and say get right _first_. Any 'real time' feedback on the frontend can then try to enhance rather than duplicate the validation rules. A lazy example might be auto-capitalisation for, you guess it, UK/IE. But we already have that :)

Pursuant to the [above comment](https://github.com/Automattic/wp-calypso/issues/8681#issuecomment-336777838), I'm just getting together a list of postcode examples for big-market countries, and the caveat is that we might not have much room for variations, such as [ZIP+4](https://en.wikipedia.org/wiki/ZIP_Code#ZIP.2B4) in the US (`20500` vs `12201-7050`). 

I still think an example of a common postal/zip code may catch many of the cases, particularly where hyphens are involved. Any thoughts?
