### ISSUE TITLE
Stats: Link in Admin Bar Goes to Old Stats Page

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#86959]
### Quick summary

When Classic Style is enabled in Hosting Settings on an Atomic site, the Stats link in the Admin bar links to the older wp-admin stats page.

<img width="400px" src="https://github.com/Automattic/wp-calypso/assets/42279181/f977d183-a6f1-4df7-a8c6-1af97404d227">

![CleanShot 2024-01-29 at 11 39 20@2x](https://github.com/Automattic/wp-calypso/assets/42279181/557a6864-0695-424b-8bdb-3b87230c9b9e)

### Steps to reproduce

1. Enable the Class Style admin interface in Hosting Settings.
2. Open a page on the frontend when logged in.
3. Click on the Stats link.

### What you expected to happen

For the full-featured Calypso stats page to open, or if we have to stay in wp-admin, maybe the Dashboard page (`wp-admin/admin.php?page=jetpack#/dashboard`) that has the stats at the top since it's links out directly to the more fully-featured Calypso page.

### What actually happened

The link opens `/wp-admin/admin.php?page=stats` which doesn't match any of our curent styling and is missing insights, subscribers, and email stats for newsletters.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

Toolbar link and Jetpack > Stats leads to the old stats page at `/wp-admin/admin.php?page=stats` instead of Calypso stats `https://wordpress.com/stats/day/`

https://github.com/Automattic/wp-calypso/assets/14153300/d08caa22-71bd-4718-b333-92ee01e92959


📌 ACTIONS
- Triaged

cc @Automattic/lego @mrfoxtalbot @retnonindya as this might be relevant to the Untangling Calypso project

**Comment by Aurorum** [comment]
PR in Automattic/jetpack#35435 :)
