### ISSUE TITLE
Stats: Day Modal Disappears When Moused Over

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#86957]
### Quick summary

Hovering over a day in the stats bar graph opens a modal that lists details on views and posts published that day. The posts listed are underlined, which made me think they were clickable to get to post-specific details.

I can't get to them to click though, because the modal disappears when I try and mouse over it.

![CleanShot 2024-01-29 at 11 19 14](https://github.com/Automattic/wp-calypso/assets/42279181/0eea7252-3502-4c60-b10e-3b402bfe4425)

### Steps to reproduce

1. Open Jetpack Stats.
2. Hover over a day bar in the bar graph.
3. Attempt to move the cursor over the modal.

### What you expected to happen

For the modal to stay open while the cursor was over it, and to be able to click on a post title in the modal to see post-specific stats.

### What actually happened

The modal hides as soon as the cursor is over it.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I'm in Arc/Chrome, on an Atomic site.

**Comment by grzegorz-cp** [comment]
I investigated the issue and it's an intersection of the bar chat component and the way we started to use it. I think that the tooltips were never intended to have interactive elements, that's why the bar chart only shows them when the bar itself is interacted with (by hovering the mouse).

Updating this would mean adding logic to the shared Calypso bar chart component and might not be that simple. The bars are detecting mouse enter/leave events and toggle the tooltip visibility. To change this, I would have to add a ref property to the tooltip and prevent the bar mouse leave event from closing the tooltip but adding a ref to the tooltip prevents the tooltip from rendering. There might be some conflict so I would have to debug this more. When I'm successful with that I would have to merge the logic handling both refs. I'm not sure if that wouldn't cause further issues when users move the cursor from one bar's tooltip to another bar, as only one tooltip is created at a given time.

Considering the amount of work, the fact that it affects a shared component, and the fact that a project (https://github.com/Automattic/jetpack-roadmap/issues/492) to replace the chart is planned in 1.5 months, I think it's better to stop this issue. 

We can also reevaluate how we surface information about published posts in a selected period because showing it in a tooltip looks like a bad fit.
