### ISSUE TITLE
Reset state of SitePicker on reopening

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#8739]
This is a regression that I created with #5808. Code for this should be in place (`SiteSelector#reset`), but probably got broken during a huge rebase that was done or by some other means.
#### Steps to reproduce
1. ← Switch Site
2. Type search Query
3. Pick any site
4. ← Switch Site
#### What I expected

To have fresh state - without any search query prefilled
#### What happened instead

You can see the last state - with search query present and filtered results
#### Screenshot / Video

![reset](https://cloud.githubusercontent.com/assets/156676/19383312/eaf9a80e-9203-11e6-8c57-19235422d718.gif)

**Comment by alisterscott** [comment]
This still behaves this way but I personally don't mind seeing the previous results as if I accidently selected the wrong site it saves me searching again for the same thing. What do you think @marekhrabe ? Can I close this due to age?

**Comment by marekhrabe** [comment]
I think it has proven to be a decent way to keep it like it is now. I would still like to alter this a bit - to select the contents of search input once it is reopened. I found myself constantly doing CMD+A once I reopen the search to type a new query. I would put this on my todo.

**Comment by kwight** [comment]
@marekhrabe I'm with @alisterscott, I'd keep it like you have it now. Your further auto-select suggestion ends up being helpful only 50% of the time: helpful if we want to start from scratch, hurtful if we need to just type a few more characters to narrow things down more. I'll close just because of the age of the issue, and if you ever want to work on it again, go for it!
