### ISSUE TITLE
Implement WooCommerce NUX passwordless signup screen

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wp-calypso#87627]
### Issue description

Project thread: pdibGW-2FU-p2
Figma: 4ixWMlzrxllx93tSFsCW6k-fi-9483_4315
POC PR:  https://github.com/Automattic/wp-calypso/pull/85462 (This contains the email confirmation step which has been removed)

Implement a passwordless signup flow for Woo Expres. New users will only need to enter their email addresses to create an account. And users will be redirected back to the Woo Express site creation flow when they confirm their email address.

<img width="750px" alt="03  Social Signup" src="https://github.com/Automattic/wp-calypso/assets/4344253/f06bcb3b-b3fe-41f4-b398-f26b6758a63a">

### Acceptance criteria

- When the feature flag is enabled (https://github.com/Automattic/wp-calypso/issues/87635), the new passwordless signup UI should be displayed

```
Given a new user is on the Woo Express account creation step
When user enter their email address
	and clicks on "Continue with email"
Then an account will be created for them
	and they will be logged in automatically
	and they will be redirected back to the Woo Express site creation flow
	and an email will be sent to them to confirm their email address
```

**Comment by rjchow** [comment]
I'm not going to assign this to myself just yet so that I don't block anyone who might get to it first, but here's some groundwork:

- https://github.com/Automattic/wp-calypso/pull/87887 is all it takes to make the passwordless flow show up, and it will take you through the passwordless flow all the way into provisioning. You'll also find the email confirmation in your inbox
- https://github.com/Automattic/wp-calypso/pull/85462/ previous exploration

**Comment by rjchow** [comment]
This should be just CSS and copy changes. I've added the is-woo-passwordless class in https://github.com/Automattic/wp-calypso/pull/87887 to aid with that.
