### ISSUE TITLE
Plans Next: Migrate `lib/url/support.js` to a new package

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#88183]
### What

Part of addressing https://github.com/Automattic/wp-calypso/issues/79004

The `FEATURES_LIST` for plans is importing`DOMAIN_PRICING_AND_AVAILABLE_TLDS` from `lib/url/support.js` for use in one of the descriptions. `FEATURES_LIST` is being ported to `@automattic/calypso-products` and needs to be uncoupled from local dependencies.

### Why

For uncoupling usages that need to be detached from Calypso dependencies.

### How

Per the discussion below, we will be migrating `lib/url/support.js` to a new package - either `@automattic/url-constants` or `@automattic/urls` - and update the references (remove `support.js` altogether). Consider not exporting a `supportUrls` module from it, as some of the URLs are not support-related per se. We can keep the new package as a general holder of `URL`s. 

Props to @tyxla for the input/direction below.

**Comment by tyxla** [comment]
The `@automattic/calypso-url` package is rather a utility package that can be consumed all across the Automattic products and it's currently not related to any particular products or product features. With that in mind, I'm not convinced that the `supportUrls` or any other specific URLs make sense in that particular package. Similarly, if someone is using `supportUrls` it's likely they won't need anything from the `@automattic/calypso-url` package. 

So it could be a good idea to extract those URLs as a separate package - `@automattic/support-urls` or `@automattic/url-constants` or `@automattic/urls`. I'd lean towards the last 2, since some of those URLs seem to be not really support related (`JETPACK_PRICING_PAGE` ), and that way we can be more flexible about the URLs we place in there. 

A side note: IMHO these constants live under `client/lib/url` because of lack of a better place. These constants aren't really part of a library function, so IMHO they don't really belong there in the first place. So I appreciate the chance to move them into a place that makes more sense.

**Comment by chriskmnds** [comment]
Thanks for the feedback @tyxla :-)

> The `@automattic/calypso-url` package is rather a utility package that can be consumed all across the Automattic products and it's currently not related to any particular products or product features. With that in mind, I'm not convinced that the `supportUrls` or any other specific URLs make sense in that particular package. Similarly, if someone is using `supportUrls` it's likely they won't need anything from the `@automattic/calypso-url` package.

👍 

> So it could be a good idea to extract those URLs as a separate package - `@automattic/support-urls` or `@automattic/url-constants` or `@automattic/urls`. I'd lean towards the last 2, since some of those URLs seem to be not really support related (`JETPACK_PRICING_PAGE` ), and that way we can be more flexible about the URLs we place in there.

Gotcha. Makes sense. Happy to go with a new package, I'd flip a coin between `@automattic/url-constants` and `@automattic/urls` as they are equally good. Just an aside - this will be a very slim and specific package, do you think we can generalize out e.g. `@automattic/constants`, if there are more potential constants to extract? or would that make it less visible, and granular packages are preferred?

> A side note: IMHO these constants live under `client/lib/url` because of lack of a better place. These constants aren't really part of a library function, so IMHO they don't really belong there in the first place. So I appreciate the chance to move them into a place that makes more sense.

Time to clean then! :D

**Comment by tyxla** [comment]
> Just an aside - this will be a very slim and specific package, do you think we can generalize out e.g. `@automattic/constants`, if there are more potential constants to extract? or would that make it less visible, and granular packages are preferred?

Good question - IMHO `@automattic/constants` can easily grow into a bigger can of worms since almost anything is a constant, really, and folks can feel like unnecessarily moving thousands of constants there 😉 This will defeat the initial purpose, which is why I recommended a more specific name.

**Comment by chriskmnds** [comment]
> > Just an aside - this will be a very slim and specific package, do you think we can generalize out e.g. `@automattic/constants`, if there are more potential constants to extract? or would that make it less visible, and granular packages are preferred?
> 
> Good question - IMHO `@automattic/constants` can easily grow into a bigger can of worms since almost anything is a constant, really, and folks can feel like unnecessarily moving thousands of constants there 😉 This will defeat the initial purpose, which is why I recommended a more specific name.

Gotcha. Indeed, sounds prone to becoming too broad. 
Thanks for the input/direction. Updated the description and we'll go with either `url-constants` or `urls`.
