### ISSUE TITLE
Stats: Only display the sparkline under certain width

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#88206]
We could only display none the sparkline under a certain width, etc.

![image](https://github.com/Automattic/wp-calypso/assets/1425433/bf30ced9-76b0-4730-8db0-b9892e04fef7)

Related: https://github.com/Automattic/dotcom-forge/issues/5854 https://github.com/Automattic/dotcom-forge/issues/5829

**Comment by annacmc** [comment]
I've been testing this out, and I can't find a use case where the sparkline is shown on smaller displays. I get the same experience on Chrome, FF and Safari where a condensed menu with no sparkline is shown on resize to small.

https://github.com/user-attachments/assets/73dc8e37-d9ef-49e4-a024-524f1bf6fc2f

Perhaps this is a newer change since the original discussion earlier in the year?

There is only a tiny margin of space above this where we could `display:none` it but yet still show it at all. It this worth it? @Automattic/red

**Comment by a8ck3n** [comment]
So it sounds like the issue is shown in this video from Dave:

https://github.com/Automattic/dotcom-forge/issues/5854#issuecomment-1975134497

I'm not able to reproduce the behaviour on my test sites though, so maybe it has already been addressed somewhere. Maybe double check with Dave to see if he can reproduce and if so, share some steps to do so.

**Comment by kangzj** [comment]
Guess we can close it. Thanks for looking into it @annacmc !
