### ISSUE TITLE
Invoking the command palette in the reader can change the post being viewed

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#88226]
### Quick summary

Invoking the command palette using `⌘+k` when looking at a post in the reader also performs the shortcut for `k` - go to previous post in the list.

The reader could check if any modifier keys are also being held before executing its shortcuts.

### Steps to reproduce

1. Go to wordpress.com/reader
2. Click on one of the posts in your stream
3. Press ⌘ + k

Note this isn't reproducible if you go directly to a single post, it has to be a post in a list.

https://github.com/Automattic/wp-calypso/assets/93301/79b40a91-aa2e-46d5-99ea-e6b3977eeb71

### What you expected to happen

The command palette to open, and the post underneath to not change

### What actually happened

 * The command palette opened ✅ 
 * The post I was viewing moved to the next one ❌ 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/14153300/1c4fe0b2-df67-4e68-ab5e-8b43c515ad55



📌 ACTIONS
- Triaged

📌 Message to Author
Keeping it High since it is easy to trigger by accident and very disruptive to the reading flow
