### ISSUE TITLE
Launchpad: Sometimes the Launchpad gets sites stuck in a redirect loop

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#88384]
We get the occasional report of a site that gets into a stuck state where the site editor cannot be accessed because it automatically redirects to the onboarding Launchpad at `/setup/site-setup?siteSlug=...`, which then redirects to `/home`.

It seems to be related to the `site_intent` option not being cleared at the correct time, and/or to the site's launch state, because clearing the `site_intent` usually fixes it.

Reports:
* p1704389206048269-slack-C0Q664T29
* p1687983958852119-slack-C0Q664T29

Related PRs:
* https://github.com/Automattic/wp-calypso/pull/78869
* https://github.com/Automattic/jetpack/pull/31673

**Comment by ash1eygrace** [comment]
Another instance: [8317102-zd-a8c](8317102-zd-a8c)
Open request: p9F6qB-fqh-p2

**Comment by rickmgithub** [comment]
Another instance - 8438115-zd-a8c

**Comment by rickmgithub** [comment]
Also looks like this is another case 8317102-zd-a8c

**Comment by ktyfuller604** [comment]
Another case - 8443021-zd

Launching the site clears the loop. Set the site to "Coming Soon" after launching it does not cause the error to return.

**Comment by jerrysarcastic** [comment]
Also reported in 8642688-zd-a8c

launching the site/setting back to coming soon worked to get this user unstuck

**Comment by annezazu** [comment]
https://github.com/user-attachments/assets/2d292bbc-d946-48f1-99f1-8dfdf2174f05

Not sure if this is the same but it might be? cc @inaikem for a double check. Will open a separate issue if not. This was _rough_ either way and hung for at least 5 minutes (I forgot about it and started working on something else).

**Comment by mmtr** [comment]
I think this issue was fixed by https://github.com/Automattic/wp-calypso/pull/90706. Feel free to re-open if we get new reports.

> Not sure if this is the same but it might be?

@annezazu it looks like a different issue to me. The issue reported here was preventing users from accessing the editor because of a forced redirect:
- User skips launchpad
- Launchpad redirects to My Home
- User opens editor
- Editor mistakenly redirects to launchpad because tasks are not completed
- Launchpad redirects to My Home

It seems that you're facing a `window.AppBoot` error which is something we investigated in the past (see p1699188564421549-slack-C02DQP0FP). It happens when a script needed by Calypso cannot be loaded for some reason.
