### ISSUE TITLE
Checkoutv2: Akismet 'Number of licenses' dropdown does not work.

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/wp-calypso#88455]
### Quick summary

When I select an option, the dropdown remains open, and the price does not change:
![image](https://github.com/Automattic/wp-calypso/assets/1990037/749fd403-ef3f-4704-a7c7-001b17393330)

### Steps to reproduce

1. Go to https://akismet.com/pricing/ and click 'Get Pro'
2. In the checkout, select any option in the dropdown under 'Number of licenses'.

### What you expected to happen

The dropdown should close and the price should update depending on your choice.

### What actually happened

Nothing. The dropdown remained open, and the price did not change.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by DavidRothstein** [comment]
Cross-linking to previous private issue: https://github.com/Automattic/payments-shilling/issues/2436

**Comment by sirbrillig** [comment]
Some quick logging shows that the cart isn't being changed because of [this guard](https://github.com/Automattic/wp-calypso/blob/4120f20fa0edce050a08eadc34c46137295f622c/client/my-sites/checkout/src/components/wp-order-review-line-items.tsx#L162) where `replaceProductInCart` is not available in v2 checkout.

You can see that it's provided for v1 checkout here:

https://github.com/Automattic/wp-calypso/blob/4120f20fa0edce050a08eadc34c46137295f622c/client/my-sites/checkout/src/components/checkout-main-content.tsx#L595-L605

But not for v2 checkout here:

https://github.com/Automattic/wp-calypso/blob/4120f20fa0edce050a08eadc34c46137295f622c/client/my-sites/checkout/src/components/checkout-main-content.tsx#L552-L561

**Comment by sirbrillig** [comment]
https://github.com/Automattic/wp-calypso/pull/88692 should fix this.
