### ISSUE TITLE
Theme Showcase: Retired Themes Showing Up as Options

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#8851]
In the Themes Showcase, two retired themes, Shaan and Retro Fitted, show up as as available themes.

Steps to reproduce
1. Select a site made after 2016-06-10
2. Visit the Themes Showcase:  https://wordpress.com/themes/yoursite.wordpress.com
3. Search for Shaan or Retro Fitted

Expected:

Themes won't show up since they're retired and site was made after the retirement date.

Actual

Themes show up, but couldn't be activated on sites created after their retirement dates (both 2016-06-10)  Sites made before those dates can still activate them (which is by design)

Browser / OS version

Chrome Version 53.0.2785.143 (64-bit) / Mac OS X Yosimite 10.10.15

Screenshots

<img src="https://cldup.com/lkdiV8Q2qQ.png" width="500" />

<img src="https://cldup.com/yL84s7oDnl.png" width="500" />

**Comment by alisterscott** [comment]
This issue also affects the 'Currents' premium theme which is displaying when using the new "Premium Squared" functionality (raised in #8914 which I will close). 

Interestingly this theme shows and activates in wp-admin

**Comment by folletto** [comment]
Periodic check since we changed some pieces. 

Site made 2017-02-08. Both "Retro Fitted" and "Shaan" show up.

![screen shot 2017-02-08 at 17 39 05](https://cloud.githubusercontent.com/assets/4389/22749511/8ff4366c-ee25-11e6-9d67-4a6d2dca5829.png)

Both the themes also show up when logged out:

![screen shot 2017-02-08 at 17 40 45](https://cloud.githubusercontent.com/assets/4389/22749584/c46f3626-ee25-11e6-9b5a-3f76a9af7350.png)


Issue still present.

**Comment by folletto** [comment]
There was a missing step in the retirement for these two themes, now it should properly work.
Thanks to @laurelfulford for the bug hunting!

Thank you!
