### ISSUE TITLE
Checkout: offer more contextual help

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#88555]
The checkout step has a link to the help center, but the help articles shown by default aren't super helpful for checkout:

<img width="1214" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/bebfc386-818c-4d94-84fd-2e1be4047c18">

I think there's some mechanism these days to curate the list of articles showing up here.

cc @Automattic/shilling

**Comment by sirbrillig** [comment]
I don't know a lot about the help center but I've added this to our team's board to discuss it.

**Comment by simison** [comment]
It might be best handled someone on .com teams, but pinged you to get convo going at least, and I trust it'll end up in right hands eventually. :-)

**Comment by michaeldcain** [comment]
> It might be best handled someone on .com teams

Agree - moving this to the Shilling Backlog to keep an eye on it.

**Comment by sirbrillig** [comment]
I vaguely remember that there's a URL somewhere that you can set to go to a specific section? I feel like it used to do that but maybe when it was switched to `usePresalesChat` that changed?

cc @escapemanuele and @jjchrisdiehl 

Related:

- https://github.com/Automattic/wp-calypso/pull/80075
- https://github.com/Automattic/wp-calypso/pull/80495

**Comment by escapemanuele** [comment]
We can add a new line here: https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/route-to-query-mapping.json

What query would you like to show when on the checkout page?

**Comment by simison** [comment]
cc @donalirl from docs guild might have some ideas for the query and pages to show up here.

**Comment by donalirl** [comment]
We need to do more work overall on this contextual help because there's a lot of room for better suggestions. Especially since the introduction of the dev docs to the help center.

For this issue with the checkout screen, let's use the keyword "checkout". I played around with different options and this was the best I could get:

![Screenshot 2024-03-20 at 14 06 54](https://github.com/Automattic/wp-calypso/assets/30727666/34283bc2-2d3f-401c-b96c-85618cc1f9db)

The only undesirable result is the dev firehouse doc (annoyingly, it's showing up all over the place!) but this doc is actually going to be retired soon.

P.S. I'd love to be able to control the results with another method other than keywords to give us more precise control.

**Comment by escapemanuele** [comment]
Thanks @donalirl, we'll add that keyword research there.

What could be this method? Like a list of post ids?

**Comment by donalirl** [comment]
> What could be this method? Like a list of post ids?

That would work! Basically, any way to select the 5 docs we'd want to appear.

**Comment by escapemanuele** [comment]
Opened a PR for the quick fix, and this https://github.com/Automattic/wp-calypso/issues/88707 for the tailored list of ids!

I imagine we'd need to take locale into consideration 👍
