### ISSUE TITLE
Site Migration: Updates to migration instructions

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#88588]
Some updates need to be made to get the implementation closer to the original design: 5yhaC6umexdQLlLpCrCyEe-fi-1994_2844.

- "Follow these steps to get started" should be centered and have the correct style for subtitles, because it's not part of the header and not the content.
- Consider swapping the steps so that we get the user to copy a code closer to the point they will use it. The tradeoff to this approach is that causes the user to have to go back and forth between screens one extra time.
- Review the provided copy to simplify if possible.
- There's an extra slash after the domain on the "Migrate Guru page on the source site" link

When there's an error, and we can't retrieve the key, we do this:

<img width="779" alt="Screenshot 2024-03-15 at 12 52 03" src="https://github.com/Automattic/wp-calypso/assets/4933/215f7909-76ca-44c3-897a-bdd42b5cd45a">

Could we hide the fact that there was an error and display this instead? 

![image](https://github.com/Automattic/wp-calypso/assets/4933/690efc5b-0a1d-4e37-82ab-431d8b57c9b5)

_Originally posted by @javierarce in https://github.com/Automattic/wp-calypso/issues/88506#issuecomment-1999504634_

**Comment by javierarce** [comment]
I'll work on a design for the reveal-and-hide key feature of the step.

**Comment by javierarce** [comment]
I've updated the designs (5yhaC6umexdQLlLpCrCyEe-fi-1994_2844) and improved the migration key field component. It's based on the current password component with some minor adjustments. It also includes a compact copy button:

![image](https://github.com/Automattic/wp-calypso/assets/4933/90ef4a3e-3708-4627-b399-75e8a6494013)

Instead of placing the field inside the text, we could put it directly under the step:

![image](https://github.com/Automattic/wp-calypso/assets/4933/806cd86c-04ab-4e01-b766-4d71d7b3e3aa)

Finally, do we need the "Get migration key" button? I think we could request it automatically before we show the page to the user.
