### ISSUE TITLE
Donation Form Block not working as expected. 

### ISSUE THREAD

**Issue by kkalam7757** [Automattic/wp-calypso#89123]
### Quick summary

I noticed a problem with the Donation Form Block. Nothing appears when you add a Donation form block, I tried it on 
test sites with different themes, but it doesn't work on any.

![image-png-1432×338](https://github.com/Automattic/wp-calypso/assets/66838238/fb60836b-4fd2-4c04-90fc-10aaf3881268)

### Steps to reproduce

Follow general instructions for adding blocks: (https://wordpress.com/support/wordpress-editor/add-content-blocks/).

### What you expected to happen

A donation form with preset amounts ($5.00, $15.00, and $100.00) and editing options should appear. 

### What actually happened

Nothing appears when you add a Donation From Block

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
While it appeared not to load against a white background, against a darker background you can see that the block is loading, and continues to load indefinitely. 



![Image](https://github.com/Automattic/wp-calypso/assets/86028337/ae6b48bc-ad3f-40f2-8a5d-ec772946060f)


📌 ACTIONS
- Triaged

**Comment by mpkelly** [comment]
I just tested this and it still appears broken. I don't know much about this block but I will take a closer look now.

**Comment by mpkelly** [comment]
Quick update. 

The block does work but you must link a Stripe account first. This is obviously something that should be communicated in the Editor instead of an empty block. 

Here is what I see after creating and linking a Stripe account:


![Image](https://github.com/Automattic/wp-calypso/assets/6851384/d0a7c6ab-3deb-4860-b61f-07bf92f6f1cc)


I will start on a Jetpack PR now to address this. I am also going to change the priority to high.
