### ISSUE TITLE
Grid Block - Add Stack on Mobile Option

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#89205]
### What

Add a Stack on Mobile option to the Grid Block to allow the grid columns to be stacked for mobile views.

### Why

The [Grid block](https://wordpress.com/support/wordpress-editor/blocks/grid-block/) allows users to display elements in an aligned array. One use case is to make elements of varying heights appear in-line instead of with a ragged bottom edge. However, the multiple columns might not fit in the mobile view.

**Comment by mmtr** [comment]
> One use case is to make elements of varying heights appear in-line instead of with a ragged bottom edge

I think the Columns block should be used for this purpose, which supports a Stack on Mobile setting.

So I'll close this issue out, but if I missed/misunderstood something, folks are welcome to re-open it.

**Comment by scottsawyer** [comment]
@mmtr I think the challenge with using the Column block is that it is not actually a grid.  Columns do stack on mobile, but they only work on one plane at a time, horizontal on large screens, vertical on small. if you want a 4 x 4 grid on large screens that stacks on small, a columns block won't get there.  

I this setting is also needed on the row block.  From an editor perspective, it's frustrating trying to choose between row, grid, and columns when each presents incongruous compromises.  

Columns:
- Layout in one direction (no wrapping).
- Responsive setting (stack).
- Width settings.

Row:
- Layout in one direction, optional wrapping.
- No responsive setting.
- No control over content width (unless explicit width is somehow set on the child elements).

Grid
- Layout in two directions.
- No responsive setting.
- Width settings 
- - Manual - fixed number of grid items per row, but fills entire space.
- - Auto - min-width of grid items, but requires picking magic number for widths to attempt to control the number of items per row.

I acknowledge Row is a bit challenging due to the nature of flexbox, it would need fine-grained controls. Likewise, Grid with Auto placement has similar challenges.  

But for Grid with Manual placement, a simple toggle that enables a media query like:

```
@media (max-width: 600px) {
 .wp-container-core-group-is-layout-7 {
    grid-template-columns: 1fr;
 }
}
```

This would solve a lot of problems.  BTW, I took this directly from the core/post-template block.
```
(max-width: 600px) {
  .wp-block-post-template-is-layout-grid.wp-block-post-template-is-layout-grid.wp-block-post-template-is-layout-grid.wp-block-post-template-is-layout-grid {
    grid-template-columns: 1fr;
  }
}
```
I do not have permission to re-open this issue.
