### ISSUE TITLE
Site Migration: Investigate possible ways to avoid the verify email screen

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#89401]
It was suggested by Adii that we shouldn't be using the Verify Email screen at all and that we could use something similar to what is currently being done for the Entrepreneur Plan.

We need to understand what's being done currently and implement it in the Site Migration flow if possible.

context: paYKcK-4n3-p2#comment-3256

If this moves forward then #89254 would be obsolete

**Comment by markbiek** [comment]
I'm going to spend some time seeing if it's possible to make the verification email take the user back into the site migration flow.

**Comment by markbiek** [comment]
Had some discussion with @daledupreez and here's how we're going to handle this:

- If an unverified user enters the migration flow, we'll set a site-option on the newly created site flagging it as a migration.
- When the user clicks the verification email, we'll do the following on the backend
  - Check to see if the user only has a single site.
  - If they only have a single site, check to see if it has the migration option.
  - If it _does_ have the option, we'll redirect them back into the migration flow to assign the free trial.
- The Verify Email step will still allow the user to resend the verification email but won't poll to see if verification is complete (because we don't want to call the assign-trial step twice by accident).

**Comment by markbiek** [comment]
Had some discussion with @daledupreez and here's how we're going to handle this:

- If an unverified user enters the migration flow, we'll set a site-option on the newly created site flagging it as a migration.
- When the user clicks the verification email, we'll do the following on the backend
  - Check to see if the user only has a single site.
  - If they only have a single site, check to see if it has the migration option.
  - If it _does_ have the option, we'll redirect them back into the migration flow to assign the free trial.
- The Verify Email step will still allow the user to resend the verification email but won't poll to see if verification is complete (because we don't want to call the assign-trial step twice by accident).

**Comment by markbiek** [comment]
The WPCOM part of this can be found in D146149-code. See above for the Calypso & Jetpack PRs.
