### ISSUE TITLE
Make the command palette shortcut easier to learn about

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#89581]
### Details

The only place that explains the command palette keyboard shortcut is the banner on /sites: 
![image](https://github.com/Automattic/wp-calypso/assets/93301/af64a01c-e446-4e54-b346-8d3c408e5ef4)

Now that the command palette is also available via the magnifying glass icon in some global views we should also explain the keyboard shortcut so that users know how to access it quickly later.

Ideas:
 * When hovering over the magnifying glass icon, also list the shortcut (suggested in usability testing: paYJgx-4Nn-p2)
 * When someone launches the command palette for the first time using the icon, display something somewhere saying "You can also use ⌘+k to repeat this".

This could be _part_ of the solution for #89579

**Comment by javierarce** [comment]
I like both suggestions, here are some proposals:

### Tooltip with shorcut

I think we should replace the current label "Jump to…" and say "Command palette" instead. Otherwise people won't learn the actual name of the feature and won't be able to ask for support or search the docs.


![image](https://github.com/Automattic/wp-calypso/assets/4933/8c129f38-4372-48d4-8ab1-71d50d6ff6ca)

![image](https://github.com/Automattic/wp-calypso/assets/4933/db093ba8-d16b-4d5b-9021-5e902dbbae82)

### Suggestions

We could add a section at the bottom of the palette to display tips. We could display one that teaches how to trigger the palette, as the suggestion above or reserve this place for general tips.

![image](https://github.com/Automattic/wp-calypso/assets/4933/588baccd-c8c1-4b20-a321-e2bfd2806639)

Figma file: 2aegKcEt9nAj7wBQ4yV5n4-fi-2598_39448

**Comment by dsas** [comment]
The last discussion on the command palette ended with Daniel saying we should leave the command palette until we have one based on Core (see: paYJgx-5lQ-p2#comment-5354). [The plan for that is "later"](https://github.com/Automattic/wp-calypso/issues/95475). I'm going to close this as a won't fix, we can reconsider all of this when we eventually relaunch it.
