### ISSUE TITLE
Raise limit to 24 schedules

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#89793]

**Comment by TimBroddin** [comment]
Places where we'll need to update:

- [ ] https://github.com/Automattic/jetpack/blob/5c6be85dbf5b7471bd83f15f573c37b96f5bbb4d/projects/packages/scheduled-updates/src/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-update-schedules.php#L652-L654
- [ ] https://github.com/Automattic/jetpack/blob/5c6be85dbf5b7471bd83f15f573c37b96f5bbb4d/projects/packages/scheduled-updates/tests/php/class-wpcom-rest-api-v2-endpoint-update-schedules-test.php#L343-L368
- [ ] https://github.com/Automattic/wp-calypso/blob/15d56b04a6da4b3791ca29155ebe2985aa5e08ad/client/blocks/plugins-scheduled-updates/config.ts#L1-L2
- [ ] https://github.com/Automattic/wp-calypso/blob/15d56b04a6da4b3791ca29155ebe2985aa5e08ad/client/blocks/plugins-scheduled-updates/schedule-list-empty.tsx#L29-L30

**Comment by obenland** [comment]
Maybe let's start with a P2 post on this to see if there are any concerns we've not considered?
While shaping i1 I had an informal chat with Jennifer where she recommended limiting it to 2 schedules so we could limit the amount of times we send update checks to wp.org. Pressable also has a limit of 2 scheduled, for reference.

So far, we've not added any wp.org pings that weren't there before, which is why I think we should be able to lift the limit.
