### ISSUE TITLE
Signup: Post-signup redirect with external URLs are broken for logged-in users

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#908]
Calls to `page` are unable to redirect to certain external URLs in Calypso:

``` js
page( 'http://google.com' ); // redirects properly

page( 'http://example.wordpress.com' ); // redirects properly

page( 'http://example.wordpress.com/' ); // Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://foobar.wordpress.com/' cannot be created in a document with origin 'http://calypso.localhost:3000'.
```

The reason this triggers an error is unclear: I'm able to use page.js to trigger a redirect to `http://foobar.wordpress.com/` outside of Calypso in 1.6.4, and updating the version in Calypso to 1.6.4 doesn't fix the issue.

You can reproduce this by updating the `destination` of the `test-site` flow to `http://example.wordpress.com/` and trying to signup through `/start/test-site` while logged in.

cc @mattwiebe @kwight @scruffian

**Comment by fabianapsimoes** [comment]
@drewblaisdell can you add steps to reproduce this issue?

**Comment by drewblaisdell** [comment]
@fabianapsimoes I added them above.

**Comment by hoverduck** [comment]
05May16 Bug Scrub

@drewblaisdell - I think this may be fixed, can you confirm?  I may also have the repro steps wrong...

My steps:
1) Edited `client/signup/config/flows.js` to change the _destination_ for _test-site_ to _http://example.wordpress.com_
2) make run
3) Navigate (logged in) to http://calypso.localhost:3000/start/test-site
4) Input a site name (gh908testing) and click "Create My Site"
5) Wait
6) Site is created with no errors, and I'm redirected to https://en.support.wordpress.com/register-domain/, which is where example.wordpress.com takes me

This is all that shows up in the JS console, no errors:

> Navigated to https://en.support.wordpress.com/register-domain/
> JQMIGRATE: Migrate is installed, version 1.4.0

**Comment by drewblaisdell** [comment]
> My steps:
> 1) Edited client/signup/config/flows.js to change the destination for test-site to http://example.wordpress.com

`http://example.wordpress.com` should have always worked - the trailing slash is what was causing a `SecurityError` to be thrown, for some reason unknown to me. :)

**Comment by hoverduck** [comment]
Ah, I didn't read the initial issue closely enough.

But I stepped through the code and it looks like the problem is rooted in [this function](https://github.com/visionmedia/page.js/blob/master/index.js#L198).  When `page.dispatch` is called there, it runs the URL through `client/lib/route/normalize.js` to remove the trailing slash which then calls page.redirect [(here)](https://github.com/Automattic/wp-calypso/blob/master/client/lib/route/normalize.js#L11) .  That's what's throwing the first SecurityError.  Then because that fails it's never gets around to setting the `ctx.handled` variable to false (leaving it undefined), so it's then calling ctx.pushState, throwing the second error [here](https://github.com/visionmedia/page.js/blob/master/index.js#L201).

Changing the normalize function from a `page.redirect` to `page.show` eliminates the problem.  But I'm not smart enough in the inner workings of `page` to say whether that's a good idea or not.

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the steps provided, except with a trailing slash at the end of the destination url, and I see the following console error after clicking the Continue button:

> SecurityError: The operation is insecure.

Video: [22s](https://cloudup.com/cjAtg8Be1DS)

<img width="1280" alt="screen shot 2016-08-30 at tue aug 30 7 16 06 pm" src="https://cloud.githubusercontent.com/assets/1119271/18112644/5f000194-6ee6-11e6-8b47-fd35a64b5c2e.png">
<sup>Seen at http://calypso.localhost:3000/start/test-site/site `e5eda05` with `client/signup/config/flows.js` modified so the `test-site` destination is set to `http://example.wordpress.com/`</sup>

**Comment by lancewillett** [comment]
@mtias Could you comment on <a href="https://github.com/Automattic/wp-calypso/issues/908#issuecomment-217936251">these suggested changes</a>? Would this make a "Good First Change" candidate?

**Comment by mtias** [comment]
I'm not sure I understand the full context of the issue and its needs, but we don't do external redirects with `page`.

**Comment by kwight** [comment]
Closing in light of @mtias ' last comment and seeming lack of importance.
