### ISSUE TITLE
Reader: Consider upping the page size?

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#9132]
Since the cards are so much smaller, we may need to up the number of items in a page.

This will have an impact on the scroll event we track. We'll need to quantify the impact so we can understand how it will move stats.

**Comment by samouri** [comment]
@blowery - I've upped the page for post recommendations from 5 -> 6 in refreshed search page #9106.  We need an even number there so that the posts display correctly (we show two per row and it looks odd when only one has loaded).

Will this have an impact on our stats / do we need to be concerned about it?
