### ISSUE TITLE
Visual bug: Paid Subscriber Stats

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#91632]
### Quick summary

Related to https://github.com/Automattic/wp-calypso/pull/91585

### Steps to reproduce

1. Visit a WordPress.com site > Stats > Subscribers
2. Mouse over the chart to choose a date.
3. The `subscribers-section-duration-control-with-legend` moves horizontally

https://github.com/Automattic/wp-calypso/assets/25607244/66daa247-30d4-436f-83b4-16e8b0cb68d9

### What you expected to happen

The `subscribers-section-duration-control-with-legend` shouldn't move.

### What actually happened

Something is wrong with the `subscribers-section-duration-control-with-legend` alignment or paddings, so it moves when it has data.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO


https://github.com/Automattic/wp-calypso/assets/14153300/bc0bc32c-b3d4-425e-9817-313b062907f0



📌 ACTIONS
- Triaged

**Comment by annacmc** [comment]
As I’m working on this, it seems that the legend should be part of the uPlot component instead of being bundled with the header. I assume it’s currently in the header for alignment purposes, but this is causing unwanted visual shifts.

I made good progress towards resolving the visual shifts using CSS, but I’m now thinking that we should actually move this legend outside of the heading div. 

The current structure places the legend within the `subscribers-section-heading` div, which is part of the header section. This separation of the legend from the chart itself can lead to a disconnect between the visual data representation and its contextual information.

simplified overview of current structure:

```html
<div class="subscribers-section">
  <div class="subscribers-section-heading highlight-cards">
    <div class="subscribers-section-heading__chart-controls">
      <div class="subscribers-section-duration-control-with-legend">
        <div class="subscribers-section-legend">
          <table class="u-legend u-inline u-live">
            <!-- Legend items -->
          </table>
        </div>
      </div>
    </div>
  </div>
  
  <div class="calypso-uplot-chart-container">
    <div class="uplot calypso-uplot-chart u-hz">
      <!-- uPlot chart structure -->
    </div>
  </div>
</div>
```

Moving the legend into the chart container would offer several benefits:

- firstly, I think it would help address this visual shift issue by separating it from the other elements
- improved visual coherence: The legend would be directly associated with the chart it describes, creating a more cohesive visual unit.
- better responsiveness: Having the legend within the chart container allows for easier scaling and repositioning of the entire chart-legend combination as a single entity, and also helps with things like skeleton loaders if we use them. 
- simplified layout management: Keeping related elements together can make it easier to manage the overall page layout and apply consistent styling.

So I am going to abandon the CSS approach (for now) and move forward with relocating the legend and see how that goes. 

cc: @kangzj  and @dognose24

**Comment by annacmc** [comment]
Update: moving it out was **surprisingly**  _(embarrassingly)_ simple and with a single LOC change the improvement is immediate.  PR in https://github.com/Automattic/wp-calypso/pull/95239

**Comment by crisbusquets** [comment]
Thanks for working on this, @annacmc !
