### ISSUE TITLE
"Everything in <prev plan>, includes:" shouldn't rely on the grid position.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#91867]
To shorten the feature list, the plans grid puts "everything in <prev plan>, includes:" copy on top to emphasize that the higher-tier plan includes everything in the lower-tier one. However, it appears to rely on the grid position of a plan card rather than the logical order between these plans. There are three identified issues due to this:

#### 1. The latest report from @niranjan-uma-shankar from pdvytD-EC-p2:

On a Creator site, the Entrepreneur plan shows "everything in Explorer" rather than "everything in Creator":

![Image](https://github.com/Automattic/wp-calypso/assets/1842898/8dd9b3b4-69a1-4034-a32e-0dec62d7aab9)

#### 2. On mobile, the copy is missing
See https://github.com/Automattic/wp-calypso/issues/90196

#### 3. on tablet, the copy is missing for the left-most plan card in the 2nd row:

e.g.
![Image](https://github.com/Automattic/wp-calypso/assets/1842898/a5bd2abf-d47c-4418-8283-468595b00d6b)

![Image](https://github.com/Automattic/wp-calypso/assets/1842898/43f26327-1d70-4e55-bf37-deb3569b2d1e)

**Comment by aneeshd16** [comment]
Hi @southp, I think there are two possible solutions to this:

1. We change the "Everything in.." text so that it will always refer to the previous plan and is not dependent on grid position:<img width="1246" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/adc397ce-fb32-41fb-a5ab-1170f0a22db5">
  This is a low-effort fix and can be done easily. However, if the text for the Entrepreneur plan reads "Everything in Creator, plus", it could be confusing as the features of the Creator plan are not listed on this page. Notably, the spotlight plan card does not have a list of features. This fix will make the grid appear "correct" but will not give the user any more clarity about plan features.


2. We keep the "Everything in.." text as is so that it will always refer to the previous plan according to the grid position. We can make the text clickable so that it either expands into a dropdown or a modal listing the spotlight's plan features. We can also consider any other UI approach. Ultimately, it should give a clearer picture of the features of the previous plan on the grid.

**Comment by southp** [comment]
Great points, @aneeshd16 . I'm thinking if we can actually combine the both, since a clickable "Everything in..." can also solve the particular issue of the 1st approach that the owned plan is not in the plans grid. If that's acceptable, we can first make it right, and then make it better :) 

Is there other reason we should keep it as referring to the previous plan on the grid? Just curious to learn if there is any benefit that I'm overlooking.

**Comment by aneeshd16** [comment]
>  I'm thinking if we can actually combine the both, since a clickable "Everything in..." can also solve the particular issue of the 1st approach that the owned plan is not in the plans grid.

That's true!

> Is there other reason we should keep it as referring to the previous plan on the grid? Just curious to learn if there is any benefit that I'm overlooking.

I was thinking it would make it easier since users can scan the plans from left-right to view plan features, but I realized that it's not true for tablet and mobile.

Meanwhile, the PR is ready for review: #92016

**Comment by southp** [comment]
@aneeshd16 I'm closing this issue since the accompanied PR has been launched. For the idea of the clickable "Everything in ...", should we create a follow-up issue for documenting the idea?

**Comment by aneeshd16** [comment]
Thanks @southp! Created a follow-up here: https://github.com/Automattic/martech/issues/3130
