### ISSUE TITLE
Reader: error "Sorry, we couldn't follow this site" when trying to follow some sites

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#921]
Steps to reproduce:
1. Go to https://wordpress.com/read/blog/id/36117170 or https://wordpress.com/read/blog/id/20465148
2. Click the Follow link in the header 

<strong>Result:</strong> the site cannot be followed and the following error appears above each card:

<blockquote>Sorry, we couldn't follow this site. Please try again in a while.</blockquote>

Notes and screenshots from kriskarkoski

![screen shot 2015-09-03 at 10 57 57 am](https://cloud.githubusercontent.com/assets/1900444/9661852/a97d30c2-522a-11e5-843b-bbf210ed795d.png)

> When I try follow from those links I do see this issue. I also noticed both feeds appear to be inactive, stopping in 2014 and 2011 respectively. If I click the title and visit the sites I can follow them successfully from the action bar. Here's are links from my Edit Following page:
> 
> https://wordpress.com/read/blog/id/77772601/
> https://wordpress.com/read/blog/id/22158974/

**Comment by andreabadgley** [comment]
For context, in case others come across this error, users may get the same message when trying to follow too many sites too quickly, and/or when following above a certain threshold of follows that the Reader supports (>2000 subscriptions). 

In 2544784-t, for example, a user is following more than 78,000 sites, and was showing the "Sorry, we couldn't follow this site. Please try again in a while," error when trying to follow some sites. It is likely the user was given the error due to trying to follow too many sites too quickly. Then when trying to find subscriptions in Follow Sites > Manage, the user gets squirrelly results because of the large number of sites being followed.

(@blowery, if I misrepresented any of that, please feel free to correct me :-) )
