### ISSUE TITLE
Editor: Galleries: Graceful handling of Jetpack site media where Photon disabled and using HTTP

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#9221]
Related: #4601

If a site does not use HTTPS and has Photon disabled, a customer may not be able to see images embedded into a post as galleries from their site if their browser has particularly strict browser settings (i.e. one which blocks [mixed passive content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)).

For these cases, we must decide whether to:

- Force Photon for images even when not "enabled"
- Display an alternative content in place of the unavailable media (i.e. placeholder, raw text)

**Comment by lancewillett** [comment]
Should this be moved to https://github.com/Automattic/jetpack instead? Front end of the site wouldn't be Calypso.

**Comment by alisterscott** [comment]
> Should this be moved to https://github.com/Automattic/jetpack instead? Front end of the site wouldn't be Calypso.

This issue is about media not displaying in the editor for those sites.

I tested this on a Jetpack non-HTTPS site with Photon disabled via Jurassic.ninja: 

Single images are fine:

![single](https://user-images.githubusercontent.com/128826/36133890-f69e6e62-10cc-11e8-90cd-5385baecb872.gif)

Galleries display a blank placeholder:

![Uploading galleries.gif…]()

Interestingly on the media modal the images display fine, is there a reason we couldn't use the same code?

<img width="688" alt="screen shot 2018-02-13 at 2 49 49 pm" src="https://user-images.githubusercontent.com/128826/36133913-297e1878-10cd-11e8-9cf5-228f5674fe03.png">
