### ISSUE TITLE
Reader: add comment functionality for Jetpack sites

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#923]
Raised by @bluefuton

We currently support comment display and posting for wordpress.com blogs within the Reader.

We should ideally support the same functionality for Jetpack blogs.

@designsimply has made a screencast about this: https://cloudup.com/cHbpP3B1cmJ

**Comment by poet-man** [comment]
At present one can´t leave a comment in the reader for a posting from a JetPack-Site. Or as support says "But for now there is no possibility of commenting on a Jetpack site from the reader".
I see it as the main feature of a blogging-software, to make it possible to communicate. How such a feature cannot be on the agenda in the very front, I cannot image at all.
Since having a JetPack-Site, comment numbers have broken down to a minimum, as more and more users have mobile devices, running the reader-app, and do not want to start their browser, in order to leave a comment.
This leaves me with the question, how a product managent would not want to change these circumstances.
All the best for now

**Comment by lancewillett** [comment]
+1 for this — I've wanted to comment in the Reader (and also Posts list) for Jetpack sites and it's jarring when you can't do certain things that are already natural for WordPress.com sites.

**Comment by lancewillett** [comment]
+1 again, ran into this today when trying to comment on a new Jetpack site that I manage via Calypso.

<img width="894" alt="screen shot 2017-02-06 at 13 45 49" src="https://cloud.githubusercontent.com/assets/66797/22665779/44b74738-ec73-11e6-90a7-1e530849dd18.png">

I can Like and Share it, but can't add a comment.

**Comment by poet-man** [comment]
Yes, as a matter of fact, it is not possible to comment on postings, 
published on a selfhosted jetpack-site
In my case I manage it via wordpress-app.
Jetpack-Automatik says, this is due to lack of programm realization. This 
will be done, but there have to be many actions, both in wordpress and in 
the app, and they cannot tell a timeline for this. At least, that´s what 
they tell for a year now.


Am 6. Februar 2017 21:51:21 schrieb Lance Willett <notifications@github.com>:

**Comment by davoraltman** [comment]
Also requested in 3113489-t

**Comment by seejacobscott** [comment]
Also requested here: 3001553-t

**Comment by danjjohnson** [comment]
Also requested here 632912-zen

**Comment by patchcrist** [comment]
The lack of this feature is killing me.  I REALLY don't want to migrate back to wordpress.com

**Comment by poet-man** [comment]
People go mobile ever more, using wp-app. And still, after many many months, program management is not able to give a consequent timeline to a feature, that is most important for blogging. People will leave wp, if this fiasco is not solved. What about all those 'phantastic' new items in wp, when users cannot comment.

**Comment by bluefuton** [comment]
Happy news - Jetpack comments are now enabled in Reader. 🎉
