### ISSUE TITLE
Domains: Delay email verification messaging until email is sent

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#9278]
OpenHRS domain verification emails seem to take longer to go out than we're used to with WWD and we've had a number of users contact us that are concerned they have not received it yet due to our persistent messaging about needing to complete it. If this trend holds and emails do take some time to be delivered we should tone down our confirmation messages or delay showing them at all until we're confident the email will be in their inbox (as one example, one user I spoke to had not received it 1 hour after registration but had by 2 hours). 

Here's one example but there may be other places we warn them as well (post-checkout comes to mind as a possibility):

![screen shot 2016-11-10 at 3 28 44 pm](https://cloud.githubusercontent.com/assets/1900444/20193151/bdf55418-a75a-11e6-85b9-8c7fca522bd6.png)

**Comment by wensco** [comment]
Just a quick update - I spoke with Tucows folks and this slow down was temporary and has been fixed as of Nov 10. The verification emails should be sent within minutes of registration (of course, we can't control how long it takes the recipient to receive them). 

I have not heard of any issues since last week, but maybe folks aren't reporting them to me. @kriskarkoski are you still seeing delays or hearing reports of delays with these emails? If not, we can close this issue and re-open it if needed.

**Comment by kriskarkoski** [comment]
@wensco I had one user today ask about this in chat, but I'm pretty sure they chatted with us immediately after registering the domain and they received the email before I could even reply so that tells be it was pretty quick. That was also the only case I've handled or seen unlike the 3 or 4 I had the other day, so I'm comfortable with closing for now and revisiting if it continues to come up.
