### ISSUE TITLE
Not having the ability to adjust submenu styling means menus look inconsistent.

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#92973]
### What

Once a menu has been create in a navigation block, items that are not submenus can be styled with appearance and weight, etc. However the submenu has not way to adjust it's styling. This leaves an inconsistent look if the individual items are adjusted. 

The recommendation is to add the same type of styling options. However, the submenu has no way to adjust its styling.

### Why

Right now, the only solution is to use Custom CSS which we don't want with FSE.

### How

A case study can be found here - 8524397-zd-a8c

**Comment by retnonindya** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
I'm unsure as I can find stylization tools on my AT site:

<img width="1714" alt="Screenshot 2024-08-11 at 3 10 46 PM" src="https://github.com/user-attachments/assets/53181c6b-7a1c-486d-9924-0f6712e9e533">

Perhaps something has changed/updated since this feature request is updated.

📌 ACTIONS
- Triaged

I'm closing this feature request as it's no longer relevant, but feel free to reopen with additional insights if needed. Thanks!
