### ISSUE TITLE
Themes: On first load in multi-site view, the ThemesSiteSelectorModal points to `null` instead of the selected site

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#9298]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design (from a fresh login session)
2. Choose a theme and click the ... menu
3. Click Try & Customize
4. Select a site in the dropdown
5. Click Try & Customize

#### What I expected
To open the customizer

#### What happened instead
<img width="986" alt="screen shot 2016-11-11 at 7 51 01 am" src="https://cloud.githubusercontent.com/assets/7233112/20215633/9bd6a182-a7e3-11e6-873c-a5d3bd868a87.png">

Note that if you go back and try again the customizer loads fine...it's only on the initial site load that it's a problem.  cc: @ockham #9193 

#### Browser / OS version
OSX Chrome

#### Context / Source
#automated-testing

**Comment by ockham** [comment]
Ugh. Thanks for reporting.

I don't think it actually has to do with a site being private or not, but probably for any non-primary site (?).

This is due to`getThemeCustomizerUrl()` (and a bunch of other theme options, like theme activation) try to read the site's slug from the state tree, which after log-in isn't primed with that kind of information yet.  So we somehow need to teach `ThemeSiteSelectorModal` to query that information if it's not present yet.

**Comment by ockham** [comment]
Reopening, since I had to revert #9431 as it was breaking something. Furthermore, use of `<QuerySites allSites />` is discouraged as long as we are duplicating locally stored data between `sites-list` and our Redux state. This might mean that the fix will be delayed.

**Comment by hoverduck** [comment]
Thanks for the update, @ockham.  I'll add a workaround to our e2e tests in the meantime (which I should've done last week, but I was AFK)

**Comment by ockham** [comment]
@hoverduck Can you try to repro this again? I think this might've been fixed by #13293 -- such that the site selector modal just has you wait while sites are being fetched and doesn't allow you to select one:

![image](https://user-images.githubusercontent.com/96308/27578131-75cc8148-5b23-11e7-8dfe-c42fbd5c2811.png)

(To repro, you don't need to log out and in, just clearing IndexedDB and reloading should do the trick.)

I'll file a PR to fix the UX (by having the collapsed dropdown also show a placeholder).

**Comment by ockham** [comment]
> I'll file a PR to fix the UX (by having the collapsed dropdown also show a placeholder).

Fix is in #9368 now.

**Comment by hoverduck** [comment]
@ockham Thanks for the ping, I'm unable to reproduce the original problem.

**Comment by ockham** [comment]
@hoverduck Cool! I guess you see the above tho while sites are loading?

**Comment by hoverduck** [comment]
> Cool! I guess you see the above tho while sites are loading?

Yeah, I was able to reproduce that on my a11n account (with a ton of sites), but not on a normal-ish user with only a dozen or so sites.
