### ISSUE TITLE
Stepper:  Add `ref` field on step track events within the same flow

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#93060]
## Goal
We need to determine the source of traffic for signups and non-signup events, tracking `ref=`for all subsequent event calls once it is defined. 

**List of events**
- calypso_signup_actions_submit_step
- calypso_signup_step_start

## Out of Scope
- Flow changes will be handled on further iterations. 

## Tech details
We can update the `useFlowNavigation` hook to return a custom `navigate` function that always maintains the `ref` attribute if it is available. 

https://github.com/Automattic/wp-calypso/blob/c5ca5f3b5db08a40acc915faf2f4237fc619350c/client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx#L36

**Comment by daledupreez** [comment]
I am not sure if this is the right way to solve this, @gabrielcaires. I think it's best to have the `ref` tracking when we start a flow, rather than on every step. For me, the main concern is that the `ref` parameter has a clearer meaning when starting a flow -- it means we were referred to this flow from the identified referrer. Once the `ref` is present on every step event within a flow, the meaning is less clear to me, as the referrer for most of the steps will be previous step in the flow, and not the location specified by the `ref` parameter.

**Comment by gabrielcaires** [comment]
I can see your point. It may be redundant info. 
I will close this issue. if we see a better value we can reopen it.

I create another issue to track the ref on non-signup events.

https://github.com/Automattic/wp-calypso/issues/93061

**Comment by escapemanuele** [comment]
Handled in https://github.com/Automattic/wp-calypso/issues/93061
