### ISSUE TITLE
My Themes screen: No error message for missing parent theme

### ISSUE THREAD

**Issue by stronenv** [Automattic/wp-calypso#93132]
### Quick summary

If you upload a child theme through SFTP or GH deployment and the parent theme is missing, there's no indication on the My Themes screen that the parent theme is missing. This error message is available in core WP Admin. See screenshots below:

My Themes screen:
<img width="2143" alt="Screenshot 2024-07-31 at 11 21 44" src="https://github.com/user-attachments/assets/893dade3-307c-42e3-96b8-0fdc31765d9c">

Classic / Core WP Admin:
<img width="2145" alt="Screenshot 2024-07-31 at 11 22 49" src="https://github.com/user-attachments/assets/13611364-f272-4fe3-b73a-8dfdd756d055">

### Steps to reproduce

1. Upload a child theme to the site. Make sure the parent theme is not installed.
2. Visit Appearance -> Themes -> My Themes.

### What you expected to happen

An error message and/or a prompt to install the parent theme, if available. Or a separate section or place to view "broken" themes. 

### What actually happened

No visual feedback that the Parent theme is not available for the site. 

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by Aurorum** [comment]
Starting work on this in Automattic/jetpack#38642

**Comment by Aurorum** [comment]
The endpoint now contains these errors but I don't really understand what's going on here. If I make the API request normally with the `force=wpcom` parameter - as Calypso does - then I get errors for a bunch of random themes:  

<img width="1325" alt="Screenshot 2024-08-11 at 21 31 44" src="https://github.com/user-attachments/assets/6a3f8860-3d2e-4c23-b06b-dffea6334741">

If I remove that parameter - which, as far as I can tell, Calypso never does for anything so far - then it looks normal.

<img width="1120" alt="Screenshot 2024-08-11 at 21 32 26" src="https://github.com/user-attachments/assets/d7331f0d-b4af-4550-bfd8-758ba68989a2">

I can't find any documentation on what that parameter does or whether there's any way to force the API to return the actual error messages, like whether it'd be possible to always assume that `force` is false on the Jetpack side. 

As such, I'm going to leave this for someone else to pick up (unless anyone knows of whom I might be able to ping) - but hopefully that helps.

**Comment by Aurorum** [comment]
@jeherve just pinging you as you reviewed the Jetpack PR and might have an idea of what's going on with the endpoint here - apologies if not! :)

**Comment by dsas** [comment]
`force=wpcom` will check the cache WordPress.com's cache of the site, rather than the site itself.

I guess when that happens, it gets all of the themes that are installed on the WordPress.com multisite and returns the errors for them.

Curator, Decibel and Kerr are all themes that have been removed, I'd bet that their existence here is down to a stale cache somewhere. None of those erroring themes will be available to end-users, so there is no user-facing impact.

I think that:
 * We should fix those theme errors on the WordPress.com multisite
 * Theme errors should not be fetched for WordPress.com multi-site sites
 * When fetching theme errors for atomic/jetpack sites it should that errors come from the site not the WordPress.com multi-site. Perhaps the endpoint needs to do something cleverer, perhaps it shouldn't be called with force=wpcom.

**Comment by Aurorum** [comment]
Thanks @dsas - that's super helpful! 

> Perhaps the endpoint needs to do something cleverer, or perhaps it shouldn't be called with force=wpcom.

Any ideas what an endpoint fix might entail?! As far as I can tell, all `getSite` requests at the moment are made with force=wpcom:

https://github.com/Automattic/wp-calypso/blob/a03cfe03d276349a8b395e1a32aa511741281bb4/packages/data-stores/src/site/resolvers.ts#L19-L33

That can, of course, be rewritten for this particular case - but it might be a bit overkill to need to add a parameter to `getSite` for one use case, so I wonder if an endpoint change would be preferable. Otherwise I suspect that this might be the best route to go with. 

> We should fix those theme errors on the WordPress.com multisite

For what it's worth, I seem to get a different set of errors for each site, so I'm not sure it's just those themes.

**Comment by lsl** [comment]
Endpoint: https://github.com/automattic/jetpack/blob/trunk/projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php#L10

The "temporary" `force=wpcom` hack: fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Spynff.jcpbz%2Qwfba%2Qncv.cuc%3Se%3Q85p66947%232630-og

> Theme errors should not be fetched for WordPress.com multi-site sites

Yes

> When fetching theme errors for atomic/jetpack sites, the errors must come from the site not the WordPress.com multi-site cache. 

Yes

> Perhaps the endpoint needs to do something cleverer, 

No

> or perhaps it shouldn't be called with force=wpcom

Probably the best way to go, though I'd probably just side step the getSite data layer stuff entirely and do a fresh fetch on that calypso page.

**Comment by Aurorum** [comment]
Started a PR for this in #93554 for further discussion 

<img width="1188" alt="Screenshot 2024-08-15 at 12 30 47" src="https://github.com/user-attachments/assets/83508668-6dea-4801-ad50-1d164e8676d9">

**Comment by taipeicoder** [comment]
@Automattic/lego this one should be ready for review. What does the UI look like for multiple occurrence, would it stack?

**Comment by Aurorum** [comment]
Yes, it would stack (happy to change it but I don’t think stacking is too big a deal because the notices are dismissible).

**Comment by taipeicoder** [comment]
Stacking sounds great, my concern was that we would only show the first one 🙂
