### ISSUE TITLE
Reader: Pressing Esc to close a post also cancels currently loading resources

### ISSUE THREAD

**Issue by pento** [Automattic/wp-calypso#9334]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ (while logged in)
2. As soon as a post renders in the stream, click it to open the detailed view.
3. As soon as the detailed view starts rendering, press Esc to exit back to the post stream view.

#### What I expected

Posts in the post stream view would continue to download assets and render.

#### What happened instead

Pressing Esc stopped all currently downloading assets from downloading.

#### Browser / OS version

Chrome 54.0.2840.71, OSX 10.12.1

#### Context / Source

While the steps above are a little contrived to show the effect in as simple a method as possible, I regularly run into this problem during day-to-day usage. Clicking the "x new posts" button, reading through image-heavy post streams, and switching post streams are scenarios where I usually see it.

**Comment by blowery** [comment]
I was aware, but not fully aware, that this is a by-design browser behavior. 

https://bugzilla.mozilla.org/show_bug.cgi?id=614304
https://support.google.com/chrome/answer/157179?hl=en

So, we have two options:
1) preventDefault the esc key when you're on a full post, which _may_ prevent esc from cancelling all pending network requests. I say _may_ because there's no guarentee that we can intercept and prevent that aspect of the keypress. 
2) stop using `esc` as a keyboard shortcut for closing a full post. find something else to use that doesn't conflict with native browser shortcuts.

thoughts @fraying ?

**Comment by fraying** [comment]
Interesting.

I've always thought that the left arrow should be the "back" keyboard shortcut because it matches the left arrow in the "back" link.

But we probably have current users who are used to the "ESC" key, and we don't currently have anyplace that lists they keyboard shortcuts (so how would we tell them it's changed?)

**Comment by fraying** [comment]
Is there any way to measure how many people currently use the ESC keyboard shortcut? Just wondering how much annoyance we'd cause by changing it.

**Comment by pento** [comment]
Esc tends to be the default "back out of this single item" key.

See: Twitter (going from single tweet view to tweet list), Facebook and Google+ (going from photo modal to news feed), Jetpack Gallery (going from photo modal to post), Gmail (closing Compose window).

(Mildly interesting side note: replacing it with arrow keys would need to be RTL aware.) :-)
