### ISSUE TITLE
Calypso notifications panel - "n" key does not always work to toggle panel.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#93530]
related slack discussion - p1723583290390709-slack-C029GN3KD

While in calypso, the "n" key to toggle notifications seems to not work at times. This seems to happen only after visiting the /read/notifications page.

TO REPRO:
* Go to calypso
* Visit */read/notifications
* Visit another calypso page after this.
* Press "n" to open notifications.
* Immediately press "n" again, notice notifications does not close.
* If you interact with the panel more, the "n" key may then work again to close it. (like press "i" twice to toggle the info popover open and closed).

It was also noted that:
> I noticed in one instance that when I used "n" to activate the notification panel, I couldn't use the other keyboard shortcuts until I clicked in the notification panel. But I can't reproduce that now

I can't repro this either, but maybe something to keep an eye out for while testing and developing a fix for this.

EXPECTED
* notifications to always close on "n", other than when a text input is in use.

**Comment by kevin940726** [comment]
I thought this would be a lower-hanging fruit, but it turned out to be a deep rabbit hole 😅.

Sometimes, pressing `n` doesn't work because we have duplicate conflicting `Notifications` stores on the same page. When the user is on the `/read/notifications` page, apart from the global notifications (the masterbar bell icon),

https://github.com/Automattic/wp-calypso/blob/30e98f54d315280e92ccafc661fc403ae01b83fb/client/layout/global-notifications/index.tsx#L73-L78

...we also render the notification module on the reader.

https://github.com/Automattic/wp-calypso/blob/30e98f54d315280e92ccafc661fc403ae01b83fb/client/reader/notifications/controller.jsx#L45-L51

Note that they have different props and behaviors but share the same global store. In each component instance, it creates a different Redux store and overrides the global one. The unexpected side effects are also mentioned in the code comments.

https://github.com/Automattic/wp-calypso/blob/30e98f54d315280e92ccafc661fc403ae01b83fb/apps/notifications/src/panel/Notifications.jsx#L57
https://github.com/Automattic/wp-calypso/blob/30e98f54d315280e92ccafc661fc403ae01b83fb/apps/notifications/src/panel/state/index.js#L24-L33

This broke a handful of things when multiple instances of `<Notifcations>` were rendered on the same page, broken keyboard shortcuts being one. Visiting `https://wordpress.com/read/notifications` directly seems to be broken for the same reason too.

I see a couple of solutions:

1. Allow multiple stores to be registered in total isolation.
2. Keep the one uni-store, but allow the different component instances to react to different `effects`

I think in most cases what we want is the second solution. I'll create a PR soon.
