### ISSUE TITLE
Install Theme: Dropzone might not work the first time

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93582]
## Description

Sometimes the dropzone doesn't work the first time. As a result, I need to drop the file a second time for the upload to begin. See the beginning of the following recording where the site state is after upgrade, but before site transfer:

https://github.com/user-attachments/assets/052e5ebd-36ca-4816-a4b9-3195a031e5a1

## Acceptance Criteria

- [ ] The dropzone should always work when enabled.

**Comment by mpkelly** [comment]
I reproduced this. After clicking continue, the atomic transfer starts and runs in the background. However, there is no indication the transfer is in progress, and the dropzone becomes usable even though it is not. 

I am going to look at a fix now.

**Comment by mpkelly** [comment]
It's broken for plugin installs in a simlar way. After you hit continue you can upload a plugin which will eventually fail because the site is not atomic yet. 
![image](https://github.com/user-attachments/assets/83ab4976-fa8e-46f8-b460-a4c85214294b)

![image](https://github.com/user-attachments/assets/14bc2cce-00f3-4b8e-926f-9cdd4ab397a0)

**Comment by mpkelly** [comment]
I'm on SR this week, so I have unassigned this. I reproduced it and also found the same issue for plugins. I figure this worked ok until recently and has been inadvertently broken somehow but I didn't get time to investigate further.

**Comment by BogdanUngureanu** [comment]
Opened https://github.com/Automattic/wp-calypso/pull/94101 that should fix this issue as well.
