### ISSUE TITLE
Plugins Marketplace: The Upload Plugin screen feels different to the previous screens

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93589]
## Description

The Upload Plugin screen has a very different layout than the previous screens. Also, in the Plugins Marketplace the button says Upload, but in this screen it says Install plugins.

![Image](https://github.com/user-attachments/assets/8965cfe8-9ce2-4d5a-bb0a-e0b73fdb1f11)

And as seen from the screenshot, the hover overlay also feels off.

**Comment by davemart-in** [comment]
No traction on this in 2 weeks...

Summarizing what I'm hearing:

1. It might be nice to align the layout of this page to previous pages
2. It might be nice to change the header text to "Upload plugin" to better align with the "Upload" button you clicked"
3. The hover effect is weird because text is overlaid on top of text

@taipeicoder do you think it makes sense to break this out into 3 separate issues?

**Comment by taipeicoder** [comment]
Sounds good! I'm closing this issue in favor of these three, and placed them on The One Board.

* https://github.com/Automattic/wp-calypso/issues/94092
* https://github.com/Automattic/wp-calypso/issues/94093
* https://github.com/Automattic/wp-calypso/issues/94094
