### ISSUE TITLE
Plugins Marketplace: Plugin installation screen improvements

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93590]
## Description

The header in the plugin installation is odd, and it should be removed and replaced with something else (perhaps the Stepper header). Also, the progress bar has the pink highlight color which doesn't seem to come from the site's admin color scheme.

![Image](https://github.com/user-attachments/assets/fcdc6056-493d-4e13-9939-441f158a4d08)

**Comment by javierarce** [comment]
I don't recall any other loading screens that display a header like that one, and since the user has recent context on how they arrived at this screen, I'd remove it. 

Regarding the color: I think that pink shade was the previous default accent. Now we should probably use `blue-50` (and in the future, the new blueblerry shade). If I'm not mistaken, we tint the spinners with the selected admin color accent, but not the progress bars.

**Comment by javierarce** [comment]
> Also, the progress bar has the pink highlight color which doesn't seem to come from the site's admin color scheme.

I found another loader that uses pink but has a different header, in this case, it's for a theme installation.

![image](https://github.com/user-attachments/assets/c9050ff5-b321-4559-a594-102652745a48)

**Comment by davemart-in** [comment]
I plan to do a full audit of pink and blue colors in the app in a separate issue.

Maybe we just:

1. Remove the purple header
2. Show the WP logo in the top left corner instead.

I'm not sure we want to have other links up there that would disrupt the current process.

Moving this to ready for dev to address these 2 items ^

**Comment by javierarce** [comment]
> Maybe we just:

> Remove the purple header
> Show the WP logo in the top left corner instead.
> I'm not sure we want to have other links up there that would disrupt the current process.

Sounds good to me. And I agree, we probably don't need to display anything clickable.
