### ISSUE TITLE
Theme Showcase: Improve the Install New Theme flow for WoA

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93594]
## Description

The Install New Theme button in WoA sites doesn't take users to the theme upload screen, like on Simple.

![Image](https://github.com/user-attachments/assets/418209e9-46c9-48f8-a3ee-64dcaa75d8f1)

In WoA, the button takes users to /wp-admin/theme-install.php, where they would have to click again on the Upload Theme button in order to see the file upload form.

![Image](https://github.com/user-attachments/assets/fd676cee-f89b-489b-858c-45843d1c2add)

**Comment by davemart-in** [comment]
We should just make WoA sites behave like simple sites and likely remove that other upload UI with a "Choose a file" HTML element.

**Comment by DustyReagan** [comment]
This redirect to `wp-admin` seems deliberate because [Calypso cannot update themes](https://github.com/Automattic/wp-calypso/issues/52710). For example, in Calypso, if you upload `hola.1.1.zip`, then try to upload `hola.1.2.zip`, it will fail with an error message stating the Hola theme already exists. However, wp-admin gracefully handles this scenario, allowing the user to update and even backup their theme.

It looks like we have two options. 

1. Update Calypso to also gracefully handle this scenario. (Existing issue [here](https://github.com/Automattic/dotcom-forge/issues/2540).)
2. Write some code for `wp-admin` to check for a URL parameter to open the Upload section automatically for the user, saving them a click.

Option 2 is straightforward. I'm not sure what option 1 entails. It could be quite an undertaking.

**Comment by mmtr** [comment]
> This redirect to wp-admin seems deliberate because https://github.com/Automattic/wp-calypso/issues/52710.

Oh right, I completely forgot about this! Nice sleuthing.

> Update Calypso to also gracefully handle this scenario. (Existing issue https://github.com/Automattic/dotcom-forge/issues/2540.)

I like this option, because having inconsistency between Simple and Atomic sites is not great. But I recognize this can require more effort than we can allocate to Logical Flows issues.

Maybe we can timebox a solution for Option 1 during a couple of days, and it needs more time we reevaluate?

@davemart-in @ianstewart what are your thoughts?

**Comment by davemart-in** [comment]
What if we start with option 2 because it's straightforward and it solves the immediate issue, then we can consider tackling option 1 as a larger "shaped" refactor?

**Comment by ianstewart** [comment]
Plus one on Dave's idea of splitting into two approaches.

**Comment by DustyReagan** [comment]
I've closed this issue (since "option 1" is merged) and moved the existing issue [Allow users to re-upload (aka update) themes in Calypso](https://github.com/Automattic/dotcom-forge/issues/2540) to the Logical Flows Triage column.
