### ISSUE TITLE
Laughing Squid: image then video

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9372]
A lot of the Laughing Squid posts seem to have an image and then a video. For example: https://wpcalypso.wordpress.com/read/feeds/12098/posts/1223346302

Any way to avoid this?

**Comment by blowery** [comment]
There's always _a_ way, but there's no good generic way. We could special case LS and suppress features in full post.

**Comment by fraying** [comment]
I'm just trying to figure out what changed. I don't remember this being the case with LS articles in the past.

**Comment by blowery** [comment]
Nothing changed. LS has always been like this.

**Comment by blowery** [comment]
Not _all_ of their posts follow the pattern though.

**Comment by blowery** [comment]
It occurred to me overnight what did change. The new Jetpack broke all featured images on Laughing Squid for a while. It must have gotten fixed in a more recent Jetpack release, so now we were getting working featured images again. That's probably why it seemed like it regressed...

It appears that LS is only using featured images to drive publicize / social media cards, so we're just ignoring them for now.

**Comment by fraying** [comment]
@blowery Aha! Thanks for that. I thought I was losing my mind. And I may be! But not about this. :)
