### ISSUE TITLE
Make sure that the source site is not on our platform already

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#93874]
We need to investigate whether this is already implemented in the "Identify your site" step.
If it's not, before checking the credentials we should make sure that the source site is not on our platform already and send an email via Zendesk and coordinate next steps forward.

**Comment by andres-blanco** [comment]
This diff D160989-code adds logs to detect WPCOM sites and prevents running all the other checks if the site is on our platform.

**Comment by Imran92** [comment]
Looks like you are working on this instead - https://github.com/Automattic/wp-calypso/issues/94763.

If you haven't started on [this](https://github.com/Automattic/wp-calypso/issues/93874) one, I think we can close it. Because I've already implemented it slightly differently under issue https://github.com/Automattic/wp-calypso/issues/94915 as a part of Automated Migrations i4(p9Jlb4-ee4-p2)

**Comment by gabrielcaires** [comment]
closed
