### ISSUE TITLE
Post Editor: The placeholder text seems to have unescaped characters

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93903]
## Description
See [context](https://wp.me/p58i-hYA/).

![Image](https://github.com/user-attachments/assets/9500b8b8-a730-4a30-afea-2cc8df0ee647)

**Comment by mmtr** [comment]
Quotes are intentional, but they have been mistranslated. See https://github.com/Automattic/jetpack/blob/499bd93929626c13107dccbe48a2551829177c3c/projects/packages/jetpack-mu-wpcom/src/features/paragraph-block-placeholder/paragraph-block-placeholder.php#L35

I went ahead and fixed the translation myself.
