### ISSUE TITLE
Checkout: Show information about expiration dates (at least when renewing subscriptions that already expire far in the future)

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#93966]
### What

When I go to renew a subscription, even one that expires far in the future, all I see in checkout is this:

![checkout-renewal](https://github.com/user-attachments/assets/6cd8abd6-5639-4c17-8313-23c1f7827b7a)

There isn't anything telling me the current expiration date, or the new expiration date after I renew. And there isn't anything in the fine print (terms of service section) at the bottom of checkout showing me that either.

Maybe we should add something to display that -- at least when the subscription's current expiration date is far enough in the future that we think there's a reasonable chance the user is renewing by accident?

### Why

This might help reduce cases where a customer accidentally renews their subscription more than once, and then needs help to restore it to the intended state.

Internal background discussion: pNPgK-6h2-p2#comment-26428

**Comment by michaeldcain** [comment]
From planning:

This seems like a good improvement to go ahead and action. Let's start by conservatively showing the current and new expiration dates under the following conditions:

- only renewals
- only for renewals, where the current subscription is more than 9 months away from expiration

**Comment by michaeldcain** [comment]
From planning: Moving to the backlog as we re-prioritize the Up Next column. If orphaned subscriptions spike again, then we can re-prioritize.

**Comment by sirbrillig** [comment]
Currently most of the expiry and renewal info for shopping cart items (for example, [the next renewal date](https://github.com/Automattic/wp-calypso/blob/4dcf6657bf6dc2f2b9eced838abd5d7e27043fb6/packages/shopping-cart/src/types.ts#L943)) is, for historical reasons, [inside the terms_of_service](https://github.com/Automattic/wp-calypso/blob/4dcf6657bf6dc2f2b9eced838abd5d7e27043fb6/packages/shopping-cart/src/types.ts#L315) in the cart, rather than listed alongside the cart item. Some day I'd like to move it to the relevant cart item instead but even now it is possible to associate the two. However, the `terms_of_service` property is not set for products which don't have "promotional pricing" data, so this might be a good time to try at least copying some of those dates (and maybe prices) to the cart items instead.

**Comment by sirbrillig** [comment]
Just for a proof-of-concept, here's what I see for a plan renewal if I just disable two guards inside the shopping cart serializer which only allow add `terms_of_service` to introductory offers. I've made no frontend changes.

![Image](https://github.com/user-attachments/assets/fe0a4794-2f60-4d6e-aed6-3cae1869cfc4)

**Comment by sirbrillig** [comment]
I've made a diff to add two dates to every shopping cart item: D165321-code adds `subscription_expiry_date` and `subscription_auto_renew_date`. They're the same dates used by `terms_of_service` but will be present even for products which do not have an introductory offer (though we still hide them for domain transfers and multi-year domains). If that works well we can make a UI in checkout to display one or both of those dates alongside the cart item.
