### ISSUE TITLE
Inconsistency between Campaign Clicks and Stats in Blaze

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#93980]
### Quick summary

I ran a two-day Blaze ad. Stats show that the post I advertised received 3 views. Blaze implies 8 clicks. Where did the 5 go?

### Steps to reproduce

Check the stats and Blaze for veselin.blog
During the campaign period +/- 1 day for the Impenetrable Language post, the stats and the clicks disagree

<img width="636" alt="Screenshot 2024-08-28 at 10 22 19" src="https://github.com/user-attachments/assets/2a1eea67-765e-4b44-b469-a28957158389">
<img width="1048" alt="Screenshot 2024-08-28 at 10 21 07" src="https://github.com/user-attachments/assets/1373362f-3a66-4e26-8d8b-a96092b7c920">

### What you expected to happen

Same amount of clicks or greater in Stats

### What actually happened

The campaign shows 8 clicks while the actual clicks were 3 at most

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by paulopmt1** [comment]
Asked for ads-team-self-serve about it: p1724873271631969-slack-C0351BKR0M6

**Comment by paulopmt1** [comment]
Hey @dzver, thanks for opening this issue!

Summarizing the chat we had in Slack (p1724873271631969-slack-C0351BKR0M6), this isn't an issue with the product. @patrickwarner provided an answer we can send to the customer. The last piece, "We recognize that the level of discrepancy", is optional:

------------------------------

Thank you for reaching out about the differences between the clicks and visits reported. We understand your concerns, especially since the discrepancy seems larger than what is typically expected. Here are a few reasons why this might happen:

1. Clicks vs. Visits: Our system counts every time someone clicks on your ad. However, these clicks might only sometimes result in a visit to your website if, for example, the user closes the page before it loads.
2. Technical Issues: Sometimes, internet problems or browser issues can prevent a page from loading correctly after a click.
3. Ad Blockers: If visitors have enabled ad blockers, they might block the tracking that counts the visit even though they clicked the ad.
4. Accidental Clicks: Sometimes, users might accidentally click an ad and leave before the page loads.


We recognize that the level of discrepancy you’re experiencing is unusual. Our engineering team is currently investigating to ensure our tracking mechanisms function correctly and identify potential issues. We are committed to swiftly resolving this and will update you on our progress.

In the meantime, we recommend using UTM parameters to better track and understand your ads' data. Please let us know if you have any questions or need further help.

Thank you for your patience and for working with us.
