### ISSUE TITLE
Reader Full Post: Follow button location looks off if Comment/Like doesn't exist

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9407]
#### Steps to reproduce
1. Visit any stream on mobile
2. Click on any card to check out the full-post

In full-post, this is what it normally looks like with the Follow, Comment, and Like buttons:

![screenshot 2016-11-15 15 25 53](https://cloud.githubusercontent.com/assets/4924246/20328471/d96d11e0-ab47-11e6-855e-ae6a4f90e65a.png)

But if a post doesn't have Comment/Like buttons, the Follow button's location looks a bit off:

![screenshot 2016-11-15 15 28 03](https://cloud.githubusercontent.com/assets/4924246/20328651/c5c65cb8-ab48-11e6-9ce8-8edddc88e3ae.png)

Especially if you're following it because this results to more white space on its right:

![screenshot 2016-11-15 15 32 47](https://cloud.githubusercontent.com/assets/4924246/20328676/eeb5a0b6-ab48-11e6-990d-43804ff8a2fb.png)

I don't think it's also ideal to just move the Follow button to the right in instances where there aren't any Comment/Like buttons since you don't want to move the location of action items like these around.

I don't have a suggested solution for this yet, but just wanted to note it down after discussing this with @fraying.

**Comment by fraying** [comment]
Right-aligning all the elements (except "back") would be fine. We do the same for the action links in card footers, as well as the action links at the end of articles (right-aligned, with some elements dropping out when they're not active).

In the future, we can consider moving Follow(ing) out of the header/sidebar, since it's not having much of an impact (at least, not as of yet). But, for now, right alignment would solve the problem.
