### ISSUE TITLE
Onboarding: if you draft a post, preview it, and hit "next steps" it asks you to write a post again

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#94086]
### Quick summary

When going through and creating a new site, you are presented with the option to draft a post. If you draft a post and preview it, you'll see at the top the option to click "next steps". If you select that, you are then brought to a screen where you are nudged again to create a new post despite having started a draft. You can basically end up in this endlessly if you never publish a post instead opting to draft it. It's as if these experiences aren't connected and the only way to check that option off is to publish, even though some folks might only want to draft something first. We don't provide any indication that the draft is saved either and it _feels_ like content loss. For example, imagine someone really took time to draft a post, preview it, and then hit next steps only to have to start over, without realizing a draft is saved (I confirmed that a draft is made). 

https://github.com/user-attachments/assets/ee469e65-60c0-4495-9a68-13142c5b93f9

### Steps to reproduce

1. Go to WordPress.com
2. Click getting started and go through flow until you reach three actions to take that include drafting a post as shown below:
![Screenshot 2024-08-30 at 2 23 13 PM](https://github.com/user-attachments/assets/696c5d3c-fd4b-475c-9245-cc07e8320103)
3. Select the option to draft a post.
4. Draft one. 
5. Use the preview panel to preview the post.
6. While previewing select "next steps" in the upper left corner.
7. Notice things bring you to an onboarding flow asking you to write a post.
8. Select the option to write a post and notice it brings you to an empty editor, with no indication of the prior post you were working on. 

### What you expected to happen

I expected to be returned to my draft to finish it. 

### What actually happened

I was brought to a new post. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by renancarvalho** [comment]
Hello 👋  I think it would be nice if we get the latest user draft post and redirect the user there to complete/delete/whatever.


I did a quick investigation to the launchpad implementation, seems we need to add this check in the API level, probably [around here](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L108), we could get the latest user post and check its status, something like:

```php
$posts  = wp_get_recent_posts(
		array(
			'numberposts' => 1,
			'post_status' => 'Draft',
		)
	);
```

If there's a draft, then we return the post ID

On calypso, we need to use this post ID to redirect the user to the correct post URL, in this case to edit the draft. I guess these changes would [happen here.](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/post/index.tsx#L16)

I believe @Automattic/serenity can help us a bit more here.

**I am not very familiar with Launchpad, forgive me If what I am saying is nonsense.**

**Comment by daledupreez** [comment]
@renancarvalho, I think that's a really good idea! And that is also the area of the code that you'd want to touch. All you need to do is add some logic to the block of code below to adjust the link that we send users to.

https://github.com/Automattic/jetpack/blob/9404209f2e965dbf4f9c224787849a718e9f4651/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L107-L117

As a first pass, it could make sense to structure the code block as follows:
```php
	$use_wp_admin_link = wpcom_launchpad_should_use_wp_admin_link();
	$recent_draft_posts = wp_get_recent_posts(
		array(
			'fields'   => 'ids', // we only care about the ID, so no need to fetch all the post data; not sure if this will play nicely with wp_get_recent_posts() due to formatting - we might need to call get_posts() directly
			'numberposts' => 1,
			'post_status' => 'draft',
		)
	);

	if ( is_array( $recent_draft_posts ) ) {
		$draft_post_id = reset( $recent_draft_posts );
		// Maybe validate that we have an integer ID
		if ( $use_wp_admin_link ) {
			return admin_url( 'post.php?action=edit&post=' . rawurlencode( $draft_post_id );
		}
		return '/post/' . $data['site_slug_encoded'] . '/' . rawurlencode( $draft_post_id );
	}

	// Existing logic
```

**Comment by renancarvalho** [comment]
@daledupreez 👋, Great! Thank you for the direction.

I am working on this as part of the `dotcom-groundskeeping`, I am ending my rotation today, and will do my best to handle it over to the next group as smooth as possible.

I have prepared two draft PRs, one with the [API changes](https://github.com/Automattic/jetpack/pull/39259) we've discussed and another with a [calypso change](https://github.com/Automattic/wp-calypso/pull/94259) to handle this API change.

**Needs better understanding:**

— Why in calypso we are not relying on the API path response? The [PR](https://github.com/Automattic/jetpack/pull/39259) I've created changes it, but I wonder if it is a bad idea.

**Notes for further interactions.**

— Both PRs need good testing and regression testing, specially [this one.](https://github.com/Automattic/wp-calypso/pull/94259)
— The API uses `get_posts` instead of `wp_get_recent_posts` since it accepts `'fields'  => 'ids'` as part of the query argument, which will make it run faster.

**Ideas**
— Perhaps we can also change the copy in Launchpad, “Write your first post” or “Continue to write your post” if the user has a draft.

**Comment by p-jackson** [comment]
> — Perhaps we can also change the copy in Launchpad, “Write your first post” or “Continue to write your post” if the user has a draft.

Yep I'm a fan of this. It better primes the user for where the button will take them.

**Comment by p-jackson** [comment]
I've updated the PRs so that it fixes the issue for the `start-writing` and `design-first` flows too.
I've also updated the copy in the launchpad to say "Continue to write your first post"

![image](https://github.com/user-attachments/assets/1ad420dc-83aa-4527-9bde-5e85ad9234fa)

We also have a mini launchpad on My Home, and luckily the fix also fixes the task there too.
![image](https://github.com/user-attachments/assets/9bba5f2d-3da7-4f55-80c2-398d184ee940)


Ready for review https://github.com/Automattic/jetpack/pull/39259 https://github.com/Automattic/wp-calypso/pull/94259

**Comment by renancarvalho** [comment]
@p-jackson great work <3

**Comment by annezazu** [comment]
Thanks for getting this fixed, folks!
