### ISSUE TITLE
Add a textarea input on the MC tool receive our QuickForget JSON

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#94111]
Right now we are storing the created credentials in a escaped JSON object. This is troublesome to copy and paste the URLs and probably will break passwords if they contain a forward slash.

A better alternative would be filtering the URL (https://www.php.net/manual/en/filter.constants.php#constant.filter-validate-url) and  then storing the JSON unescaped.

This was raised here: pdtkmj-2RI-p2#comment-5519

**Comment by valterlorran** [comment]
@andres-blanco and I just synced, and we discussed that we should be careful "unescaping" the JSON because if the user inputs quotes, it may cause the JSON to be unreadable. We decided to add a textarea input on the MC Tool, which will unescape the JSON automatically and auto-fill the information for the HEs.

**Comment by valterlorran** [comment]
I'm addressing this issue here: https://github.a8c.com/Automattic/missioncontrol/pull/157960

**Comment by valterlorran** [comment]
Closing this as 157960-ghe-Automattic/missioncontrol was merged.
