### ISSUE TITLE
Bad error message when uploading unsupported file type

### ISSUE THREAD

**Issue by devicenull** [Automattic/wp-calypso#94189]
### Quick summary

If you try to upload a file with an invalid extension to the media library, you get the poorly worded error "0 file could not be uploaded because the file type is not supported."

### Steps to reproduce

1. Open the media library (https://wordpress.com/media/example.com)
2. Try to upload a SVG file (I used https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg )
3. Note the error message produced

### What you expected to happen

A better error message

### What actually happened

A poorly worded error message appears

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested w/ wpcom free plan

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
Replicated

📌 ACTIONS
- Triaged

I honestly not sure, since we also put a link to Support doc about supported file types. @devicenull -- Do you have suggestions for the wording? I imagine perhaps something like this: "We can't upload the file because the file type is not supported."

Then again, the message: "0 file could not be uploaded because the file type is not supported." is understandable, especially when the user trying to upload multiple files and some of them are supported.

**Comment by devicenull** [comment]
It seemed like an off by one error - even fixing it to "1 file could not be uploaded because the file type is not supported." would make the message read perfectly fine
