### ISSUE TITLE
Stepper: Ensure `calypso_new_user_site_creation` gets recorded as expected

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#94423]
See the audit by @travisw: https://github.com/Automattic/wp-calypso/issues/94394

- [ ] Ensure `calypso_new_user_site_creation` when site is created (as in Classic/Start)

**Comment by renancarvalho** [comment]
Hello 👋 

I did an investigation on this issue and this event is being logged [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/analytics/signup.js#L125), I checked on trunk and production after creating a new user and choosing a free domain and plan that this event is being triggered.
If you already have a user, it is not, but I think it makes sense given the event name `calypso_new_user_site_creation` 

I haven't checked paid plans since I don't have money for my newly created fake user. But I believe it will be the same. I took a brief look at the code and seems that all the flows are using the [same file when completing the sign-up](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/analytics/signup.js)

**Comment by chriskmnds** [comment]
> Hello 👋
> 
> I did an investigation on this issue and this event is being logged [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/analytics/signup.js#L125), I checked on trunk and production after creating a new user and choosing a free domain and plan that this event is being triggered. If you already have a user, it is not, but I think it makes sense given the event name `calypso_new_user_site_creation`
> 
> I haven't checked paid plans since I don't have money for my newly created fake user. But I believe it will be the same. I took a brief look at the code and seems that all the flows are using the [same file when completing the sign-up](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/analytics/signup.js). This happens after checkout.

Thanks @renancarvalho. Let's tag @travisw here as well to confirm if just intermittent / not critical. 
I've had similar explorations with two other issues ([here](https://github.com/Automattic/wp-calypso/issues/94416#issuecomment-2354877674) and [here](https://github.com/Automattic/wp-calypso/issues/94415#issuecomment-2354943774)) 🤞

**Comment by escapemanuele** [comment]
I'd also tag @MicBosi, since he will take @skim1220's place as she is going AFK

**Comment by travisw** [comment]
I just did a quick test and I do indeed see it firing. I think a couple of these issues (this one and [the missing](https://github.com/Automattic/wp-calypso/issues/94414) `calypso_signup_complete`) were a result of getting redirected to /sites. But as long as the flow proceeds normally then this event seems ok as far as I can tell.
