### ISSUE TITLE
Stepper: Offer sticker overlaps domains

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#94426]
### Details

Reported in https://github.com/Automattic/wp-calypso/issues/94394

![image](https://github.com/user-attachments/assets/340cc361-429d-4131-9465-8b794b0d5ea9)

This happens in both /start and Stepper.
To trigger the offer I found that it is helpful to add a paid domain to the cart

**Comment by renancarvalho** [comment]
I conducted an investigation into the issue where the "Oferta" badge overlaps with the domain name.

The main cause of this overlap is a CSS rule that prevents domain titles (in this case, domain names) from breaking into multiple lines. This rule is intended to maintain readability, ensuring the full address appears on a single line, such as [travis.a8c.testing+2024-signup-tester-stepper1@gmail.com](mailto:travis.a8c.testing+2024-signup-tester-stepper1@gmail.com), rather than splitting it into something like this:
```css
rvis.a8c.testing+2024
-signup-tester-stepper1@gmail.com
```
However, this issue is more pronounced on mobile devices or smaller screens. I believe it’s crucial to consult designers on this matter. In my opinion, resolving this is essential.

**Comment by nuriapenya** [comment]
Hey @renancarvalho 👋🏽

If we follow the same logic of the highlighted cards, the badge is stacked on top of a domain name when a domain name is too long. We could try something like this:
![screen 2024-09-13 at 11 02 52](https://github.com/user-attachments/assets/3d24e0ed-edcf-418a-847f-9ec5c1cbe6d2)

Alternatively, we could stack the label on top of the offer message. This is a bit inconsistent with the highlighted domains on top of the list, but to me it connects better the badge + message, all in the same place:

![screen 2024-09-13 at 11 07 44](https://github.com/user-attachments/assets/37bc69d6-0648-4ea4-907b-6fd934e82b0b)

WDYT?

**Comment by renancarvalho** [comment]
Hello @nuriapenya, this is sounds good to me. But the issue still there, specially on Mobile.
The content gets expanded to accommodate the size of the domain name.
In the screenshot below, there's a horizontal scroll.

<img width="424" alt="image" src="https://github.com/user-attachments/assets/3f74f9a6-febb-4a37-b166-118a82114a5e">

**Comment by JanaMW27** [comment]
Hello! Thank you for the input @nuriapenya 
I agree with your proposed solution but/and I think we should have a max width for domain names and turn them into 2 lines if the name is very long. 

![Screenshot 2024-09-13 at 11 41 13](https://github.com/user-attachments/assets/d582e8c7-6464-437d-a028-8b1b6c0ba4f2)

**Comment by JanaMW27** [comment]
Sounds good to me

**Comment by renancarvalho** [comment]
@JanaMW27 and @nuriapenya  , WDYT?

https://github.com/user-attachments/assets/b9420cbe-4ce6-4a5e-bed2-7352ef58a776

**Comment by JanaMW27** [comment]
I think there is too much spacing in the price module. Can we put the price in line with the domain name?

<img width="602" alt="Screenshot 2024-09-13 at 16 49 12" src="https://github.com/user-attachments/assets/2c9d8b7f-b7ce-4e8d-bdfc-070365bf8d7b">
