### ISSUE TITLE
General Settings: Failed to change interface from `Classic` to `Default`

### ISSUE THREAD

**Issue by wongasy** [Automattic/wp-calypso#94558]
### Quick summary

I have a site set to "Classic" admin interface. When I switched it to "Default" style, I got a "Failed to change admin interface style" error notice. If I refresh the page, the UI will be updated to "Default" style as expected. There are two issues here:
* The error notice is a false alarm, `wpcom_admin_interface` was indeed updated.
* The UI doesn't always load up properly unless the user refreshes the page.

<img width="851" alt="Screen Shot 2024-09-13 at 2 38 50 PM" src="https://github.com/user-attachments/assets/737dc882-fd32-4f7a-a69e-e38a82e5dda9">

### Steps to reproduce

1. Set admin interface style to "Classic" on any site (free or paid).
2. Observe that the interface is updated as expected.
3. Go to Hosting > Settings. Change the admin interface style to "Default"

### What you expected to happen

I expect to be taken to the General Settings Page rendered in "Default" admin interface style.

<img width="1391" alt="Screen Shot 2024-09-13 at 2 52 15 PM" src="https://github.com/user-attachments/assets/988fbb7c-c1a3-4fc8-a231-28d09d51de49">

### What actually happened

The request https://wordpress.com/settings/general/:site will trigger a CORS error. And a "Failed to change admin interface style" error notice will be shown.

<img width="1341" alt="Screen Shot 2024-09-13 at 2 57 56 PM" src="https://github.com/user-attachments/assets/a9ef2de2-c6ec-4cbf-84b8-fc0c596d863e">

Sometimes, I remained on the "Settings" page (rather than "General Settings" page), with "Classic" still selected, "Site Profile" box missing, and the sidebar not adjusted to what it's supposed to look like in "Default" view.

https://github.com/user-attachments/assets/a850d41e-3d8c-4727-a13b-2a90426aaa92

Other times, the interface updated as expected. I got the "General Settings" page. However, the "Failed to change admin interface style" error notice remains.

https://github.com/user-attachments/assets/6aa88a8e-c2b7-4958-a0c6-39f5bc237d69

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

After a page refresh, the interface will load up properly in "Default" admin interface style. 

### Logs or notes

The issue applies to both Simple and Atomic. In terms of impact, I selected > 50% arbitrarily. It depends on how may users have enabled "Classic" style.

**Comment by p-jackson** [comment]
I _think_ the CORS error is a red herring because when the POST to update the setting returns it returns a 302, and I think it might be this 302 that causes the CORS error. The thing is POSTing to the API shouldn't be returning a 302 anyway.

The logic for redirect is added in https://github.com/Automattic/jetpack/pull/38107 and it's there to redirect the user from wp-admin to Calypso when the `options.php` for is submitted. The problem is the hook that does the redirect is far too general, it's redirect inside the `update_option_wpcom_admin_interface` hook, which could be run for literally any reason.
https://github.com/Automattic/jetpack/blob/6504c2130388c0fc485244508c7761d5ca91cfab/projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php#L87

We're lucky the admin interface option appears at the bottom of the page. If there was another setting below the admin interface setting, then the early exit logic would prevent that lower setting from ever updating.

The `options.php` page isn't easy to hook so I can see why the hook was installed so widely. I think I've devised another way to get wp-admin to redirect to Calypso when this setting changes.

Core WP redirects once it's finished updating the settings anyway. It just redirects back to the settings page again fbhepr%2Skers%2Sjcpbz%2Sjc%2Qnqzva%2Sbcgvbaf.cuc%3Se%3Q1s889379%23382-og

We should be able to hijack this redirect using the `'wp_redirect'` filter, so that it redirects to Calypso instead of wp-admin. And this will allow us to remove the `'update_option_wpcom_admin_interface'` hook, which will prevent the 302 happening when the setting is changed in Calypso 👍

**Comment by p-jackson** [comment]
@wongasy I've got a fix, the bug was to do with redirecting.
I discovered during my testing that WoA sites don't redirect from wp-admin to Calypso after the user switches their admin style from Classic to Default. I fixed that so WoA and Simple sites behave the same. Presumably it was an oversight? Just pinging here just in case that was an intentional product decision.

**Comment by fushar** [comment]
> WoA sites don't redirect from wp-admin to Calypso after the user switches their admin style from Classic to Default.

This is already tracked here: https://github.com/Automattic/dotcom-forge/issues/8866.
