### ISSUE TITLE
Turning off titan mail auto renew help center issues

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#94698]
https://github.com/user-attachments/assets/d8e6c714-c031-4d02-bc0e-9ae156b2dcbc

- [ ] Contact us link overlays the form buttons
- [ ] Clicking it loads an error about 3rd party cookies (which goes away if you click back in the help center)

https://wordpress.com/email/test135145.blog/manage/test135145.blog

**Comment by heavyweight** [comment]
Opened a PR to fix the text alignment https://github.com/Automattic/wp-calypso/pull/94716
However I'm not able to reproduce the "3rd party cookies" state in the help center.
I tried with disabled 3rd party cookies but still no dice.
Can you try to reproduce it on the PR build link?

**Comment by lsl** [comment]
Nice, looks much better, this might help with the repro:

![Screenshot(46)](https://github.com/user-attachments/assets/4ff063db-ecac-46c9-9b53-392086e99aef)

https://github.com/user-attachments/assets/2af3b00a-5cf9-45a9-99c6-8c98dc8cf7bd

**Comment by lsl** [comment]
Loading it using e.g. the learn more link above doesn't have the same issue, and the < Back button works too.

I don't think there is actually a third party cookie issue, it's probably just the way it's loaded or something. Likely need to fix both the way it loads, and the display of the error

**Comment by heavyweight** [comment]
The help center needs to be opened with mode `CHAT` contact-form?mode=FORUM and to have third-party cookies disabled to see the message in the video.
I updated the styles for it to show better.
However, this code path is old one and I don't see how this can be triggered.
Now all users should see wapuu instead of the chat mode.
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sfhccbeg%2Shfre.cuc%3Se%3Qo391nrs4%26sv%3Qvf_jnchh_nffvfgnag_ranoyrq%23393-og

What does the help center render for the same user if you open it manually and click "Sill need help" ?
Can you provide what's the response for `https://public-api.wordpress.com/wpcom/v2/help/support-status?_envelope=1` for the user?

Thank you

**Comment by heavyweight** [comment]
Will merge the style fixes but will keep the issue open

**Comment by lsl** [comment]
![Screenshot 2024-09-23 at 16-54-49 ](https://github.com/user-attachments/assets/63760faf-0660-4b82-bb32-6a2bf3916632)

It's those specific actions that leads there, help center works normally otherwise:

![Screenshot(49)](https://github.com/user-attachments/assets/728ec8d3-336e-41f4-8c02-861ebb058821)

My test user is `testingtesterson11` if you think it's user related and want to test it out.

**Comment by heavyweight** [comment]
When chat is unsupported due to disabled 3rd party cookies, we now add the same notice on the help center contact page.

We are in the process of redesigning the chat, and part of it will be to make it work with 3rd party cookies disabled. So I will close this issue, since that will be handled there.
