### ISSUE TITLE
Assembler theme not respecting Site Title block alignment

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#94819]
### Quick summary

Site Title block alignment stuck to bottom. Top or Middle alignment is not respected. Other blocks added respect the Middle align, so the header looks out of alignment.

### Steps to reproduce

1. Premium test site.
2. switched theme to Assembler
3. Site Editor, edit header.
4. Site Title block is in a Row block
5. Set Alignment in Row block to Middle.
6. Site Title remains aligned to bottom.

### What you expected to happen

Site title block has space above, so it has room to adjust, it should change alignment when configured.

### What actually happened

Site Title block remains fixed in Bottom Alignment.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by radtechgh** [comment]
8771940-zen

**Comment by renatho** [comment]
I found out that installing the Assembler theme on a standalone site works properly. So searching for the differences, I noticed that one of the global styles is differently rendered in Calypso. If I fix this, it seems the error is fixed.

I didn't find the reason to render it differently yet, but I'm already sharing it here since I'll probably not finish it today.

Calypso site:
![Screenshot 2024-09-25 at 15 11 55](https://github.com/user-attachments/assets/c45d4b63-241b-4f57-80b2-3e5b55b74847)

Standalone site:
<img width="480" alt="Screenshot 2024-09-25 at 15 11 32" src="https://github.com/user-attachments/assets/8bcde4e5-3785-45e1-91d2-e64f8701b961">

**Comment by renatho** [comment]
@Automattic/lego 👋 Would you easily know the reason for [this difference](https://github.com/Automattic/wp-calypso/issues/94819#issuecomment-2374846143) in Calypso? Maybe a filter somewhere?

**Comment by renatho** [comment]
After some debugging I found the reason and noticed that it was an issue [introduced by this Gutenberg PR](https://github.com/WordPress/gutenberg/pull/64911), but already [fixed by this PR](https://github.com/WordPress/gutenberg/pull/65307). So in the next Gutenberg update in WPCOM it will be fixed.

Since it's not related to Calypso repository and the solution was already merged in Gutenberg, I'm closing this PR.
