### ISSUE TITLE
Taxonomy Manager: Changing a category name to an existing category name threw a console error

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#9496]
When changing the name of a term to an existing term name, a console error is thrown.

__Steps to Reproduce__
- Edit an existing term
- Rename it to a term name that exists at another level, client-side validation prevents from renaming to the same name as a peer
- Note the 500 error

This appears to be an API issue in the terms endpoint, so we might need to make the duplicate term name logic stricter to the global scope, not just peers.

**Comment by youknowriad** [comment]
I'm not experiencing the 500 error for some reason, but I'm seeing another bug, the term just disappears from the list.

The API for me is returning the other term with the same name instead of the created/edited term.

**Comment by timmyc** [comment]
> The API for me is returning the other term with the same name instead of the created/edited term.

Yikes, so definitely seems buggy on the API side of things either way.

**Comment by youknowriad** [comment]
When updating/creating a category with the same name as an existing one, we execute the following code:

 ```php 
$data = wp_update_term( $term->term_id, $taxonomy, $update );
$term = get_term_by( 'id', $data['term_id'], $taxonomy );
$returnedTerm = $this->get_taxonomy( $term->slug, $taxonomy, $args['context'] );
```

So say we're creating the category "b" under a category "a".

The `wp_update_term` performs the update and returns the new term id, the term id returned is correct (comparing the one we get if we run a GET `terms`).

But when calling the `get_term_by` we are getting a term with the correct id, but the slug contains only the "leaf" slug ("b" instead of "a-b").

So when we call `get_taxonomy` on the next row, with the 'leaf' slug ("b") we obtain another term and not the one we've just created/updated. We obtain the root "b" term.

So, the thing is, I did not find exactly where this slug construction is performed. If it's something internal to WP Core. than there's probably a bug in `get_term_by` which should return the complete slug and not the leaf part of the slug only.

@timmyc any though on this, I don't have the necessary knowledge yet to handle this.

**Comment by timmyc** [comment]
So a few issues happening here - looks like the call to `wp_update_term` is throwing an error based upon [this validation in core](https://github.com/WordPress/WordPress/blob/master/wp-includes/taxonomy.php#L2653-L2664) which looks to see if there is a slug that already exists with the same name - regardless of `parent`.

This does _feel_ like a core bug to me, because you can call `wp_insert_term` to create a term with a name that already exists under a different parent.

After that, the following call to `get_term_by` is trying to use the `WP_Error` as an array with a `term_id` attribute, which is causing a fatal:

`Uncaught Error: Cannot use object of type WP_Error as array in /home/wpcom/public_html/public.api/rest/json-endpoints/class.wpcom-json-api-update-term-endpoint.php:128`

So as for the proper way to move forward here... I'll get a patch going to return the error from our API when this validation is hit - we should have it in place for non-heirarchical terms.  And perhaps I can look at the core issue a bit further and get some tests and a trac issue going for it.

**Comment by timmyc** [comment]
D3504-code is a patch to return an error instead of fataling, still looking into other possible work-arounds.
