### ISSUE TITLE
Stepper: user redirected to LOHP rather than checkout page after selecting plan

### ISSUE THREAD

**Issue by MicBosi** [Automattic/wp-calypso#95039]
User redirected to LOHP rather than checkout page after they select a plan from the `plans` step.

Steps to reproduce:

Signup starting from https://wordpress.com/setup/onboarding/es/, signup using email, select domain, select plan.

At this point the user is redirected to the logged-out homepage instead of being asked to complete the log-in (verify email and log-in) and proceed to the checkout page for payment.

See Slack conversation: C073776NJ66/p1727704611670019-slack-C073776NJ66

**Comment by skim1220** [comment]
This issue happens to me only when I use automattic email address. 

Steps taken with automattic email address: 
- Turn off Autoproxxy 
- Go to https://wordpress.com/setup/onboarding/es/ in incognito mode 
- At Account Creation step, select email option
- Use automattic email (i.e., seah.kim+test20241001v2@autoamttic.com) 
- Select `.blog` domain
- Select Personal Plan
- Redirected to LOHP (instead of the checkout page)

https://github.com/user-attachments/assets/1dec7ccf-5065-44e0-b4b0-b4c44aebc666

Steps taken with gmail address: 
- Turn off Autoproxxy 
- Go to https://wordpress.com/setup/onboarding/es/ in incognito mode 
- At Account Creation step, select email option
- Use automattic email (i.e., seah1220+test20241001v3@autoamttic.com) 
- Select `.blog` domain
- Select Personal Plan
-  Checkout page

https://github.com/user-attachments/assets/888f6790-dc8a-42a3-9bd2-05317e2cf797
