### ISSUE TITLE
Reduce jumps between Calypso <> wp-admin when editing profile

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#95055]
From @nuriapenya in p9Jlb4-eiq-p2:

> The TL;DR is that updating any User Profile information is currently really confusing. We did a quick walkthrough of navigation last week, and it was apparent that there’s a lot of jumping between interfaces.

For example, when we want to update display name, we would:

1. (in any screen) Click `Howdy` -> `Edit Profile`

   <img width="214" alt="image" src="https://github.com/user-attachments/assets/8e316f8a-a7b9-41af-9f18-ec807e36a8e9">

2. (in wp-admin) See the link to Calypso

   <img width="968" alt="image" src="https://github.com/user-attachments/assets/2f32ba6d-5da6-485b-b113-476b56a74a40">

3. (in Calypso) Finally we can update the display name)

    <img width="817" alt="image" src="https://github.com/user-attachments/assets/f9376d3a-9937-4fe8-8217-800244365d07">

We need a solution that simplifies the above UX.

**Comment by arthur791004** [comment]
Sorry for the late party. IMHO, I agree it's a bit annoying but it seems to be okay as

1. The text of the link to Calypso reminds me that this account is connected to WordPress.com so I cannot modify it. Furthermore, if I click the link to WordPress.com, I may notice the change will apply to all of my sites instead of just one.
2. The admin can see the consistent Edit Profile page when they want to edit the user that isn't connected to WordPress.com

Besides, if you go to `/wp-admin/users.php` (the page seems to be available after adding a new user) > Edit the profile of any user that is connected to WordPress.com, it still shows the `profile.php`.

If we want to align the Core experience, it would be better to keep the `profile.php` page and
* Display all fields there but add the notice link like we did
* We should allow people to change those fields or provide `Disconnect` functionality in the future

**Comment by fushar** [comment]
The strongest argument here is that going to `/me` is far more useful and has the less chance to "jump", because there are more fields that can be edited there.

> The admin can see the consistent Edit Profile page when they want to edit the user that isn't connected to WordPress.com

User links in `wp-admin/users.php` still always point the Core `profile.php` / `user-edit.php`, because we only modified the `Howdy,` menu.

> We should allow people to change those fields or provide Disconnect functionality in the future

Yes, I think this is the key here! We might want to evaluate the decision IF we somehow can successfully untangle all fields in the future.
