### ISSUE TITLE
Jetpack Plugins: flash of content shows the plugin list when manage is turned off

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#955]
There is a flash of content when navigating to `/plugins` for a Jetpack site with manage turned off.

Steps to reproduce:

1. Go to `/wp-admin/admin.php?page=jetpack` for your Jetpack site
1. Click the "Manage" card
1. Click the "Deactivate" button
1. Go to https://wordpress.com/sites and select the Jetpack site from step 1
1. Click the "Plugins" link in the left nav
1. Can you see plugins listed or do you see an warning that says, "Remote management is required to see this page"?

<strong>Result:</strong> I see the plugins listed for a short time before the notice about needing to turn on remote management appears. Can we avoid that flash of content?

Here are the steps that the page goes through before finishing the the feature gate:

![1](https://cloud.githubusercontent.com/assets/11487924/11457469/6528cfb6-9678-11e5-8866-e45a717b6768.png)
![2](https://cloud.githubusercontent.com/assets/11487924/11457471/652c68c4-9678-11e5-88e2-d7e6e8c3db64.png)
![3](https://cloud.githubusercontent.com/assets/11487924/11457472/652d98c0-9678-11e5-888a-08f2c3944692.png)
![4](https://cloud.githubusercontent.com/assets/11487924/11457473/652e5d78-9678-11e5-9adc-8617ab38113a.png)
![5](https://cloud.githubusercontent.com/assets/11487924/11457470/652c5de8-9678-11e5-9758-38f498d21ad1.png)

**Comment by johnHackworth** [comment]
This has been reported before, but currently is not easy to fix:

The problem is that we know about the plugins list of a site way sooner than if the site has manage turned off. So right now, we are taking an optimistic approach: as soon as we can show the list of plugins, we show it. And once we get the info about the site manage module state, if it's off, we show the error screen. 

This results in a faster experience for users with enabled manage, but has as side effect this flash of content for the users that have disabled it. The alternative would be to make everybody wait until we have the confirmation that the site has enabled manage or not.

I'm not sure if we could fix this changing the info we sync... @enejb @lezama

**Comment by enejb** [comment]
I think this has been fixed for sites without manage. Since if a site has manage enabled or not is part of the /me/sites endpoint now and we are able to tell right away if a site has those capabilities. 

Feel free to open this issue if that is not the case for you.
