### ISSUE TITLE
Stats: click on a post link in the Stats page redirects to Insights

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#9550]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/8bitchromedolphin.org?startDate=2016-11-20
2. Click on a post Title under "Posts & Pages"
3. Instead of viewing a post specific stats page, you're redirected to: 
4. https://wordpress.com/stats/insights/8bitchromedolphin.org

#### What I expected
I expected to see a post-specific stats page:

https://wordpress.com/stats/post/0/8bitchromedolphin.org

<img width="757" alt="screen_shot_2016-11-21_at_1 57 06_pm" src="https://cloud.githubusercontent.com/assets/10121835/20496659/b1d79224-afeb-11e6-8402-a33e1b778b44.png">

#### What happened instead

The URL redirects to insights.

![posts_click_on_stats_redirects_to_insights](https://cloud.githubusercontent.com/assets/10121835/20496628/9c269aba-afeb-11e6-9a79-00bd142682d4.gif)

#### Browser / OS version
Chrome 54, Debian Jessie

#### Screenshot / Video
![posts_click_on_stats_redirects_to_insights](https://cloud.githubusercontent.com/assets/10121835/20496679/c46d6418-afeb-11e6-8686-083c304a4a3d.gif)

#### Context / Source

Issue was brought to my attention while chatting with user:

532112-chat

Tish, Kris, and myself all tested and got the same results when trying to get post specific stats info.

 #manual-testing #user-report

**Comment by timmyc** [comment]
This regression appears to have been introduced in #9445, as @mtias at the time even [said](https://github.com/Automattic/wp-calypso/pull/9445#issuecomment-261584853) the PR could cause breakage.

So what is happening with `https://wordpress.com/stats/post/0/8bitchromedolphin.org` is that `getSiteFragment` is returning the post ID from the URL, so `0` as the site ID.  Since `0` is not a site in the user's site list, the request first gets redirected to the all sites path for this route, `https://wordpress.com/stats/post/8bitchromedolphin.org`, which is also an invalid route, so it eventually gets redirected to the Insights page.

If we change the route of the post stats URL to `/stats/post/:site_ID/:post_ID` then all works as expected, but would require updating URLs in a number of places - and not to mention could break URLs in the wild ( bookmarks etc ).

An alternative approach would be to add additional logic to `getSiteFragment` to handle a few stats routes differently, which seems rather 😢 to do.

/cc @ebinnion
