### ISSUE TITLE
Reader: Try nesting image under headline in Default cards

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9557]
This is a test.

There are some concerns about the way the headline start position varies in the Default cards. This is a potential solution.

![test](https://cloud.githubusercontent.com/assets/24388/20506137/b745ffaa-b006-11e6-8078-bbf3376f512b.png)

Changes:
1. In the Default card (wide width), place the image after the headline, next to the excerpt.
2. Increase the excerpt from 3 to 4 lines to allow enough space for the image.

This is an attempt to create consistency in the start point for headlines while still preserving the left-alignment of images.

**Comment by fraying** [comment]
Note also that, if we go with this, we'll need to do the same to Video cards.

**Comment by raoulwegat** [comment]
[https://calypso.live/?branch=try/reader/9557-nest-image-under-headline](https://calypso.live/?branch=try/reader/9557-nest-image-under-headline)

**Wide screen**

![screen shot 2017-02-02 at 5 07 47 pm](https://cloud.githubusercontent.com/assets/2627210/22538913/2bc8a7be-e96a-11e6-8f5b-025f1e185464.png)

**Narrow screen**

![screen shot 2017-02-02 at 5 07 15 pm](https://cloud.githubusercontent.com/assets/2627210/22538917/33b27c52-e96a-11e6-926e-33ecc178000e.png)

Because the title, feature-image and excerpt order are changed, that order carries over to narrow viewports where the elements are stacked. And because feature-image and excerpt are siblings, title can't be moved using flex `order`. Any suggestions on how to work around this without CSS would be appreciated. cc @samouri @blowery @bluefuton
