### ISSUE TITLE
Task: Implement the Goals screen per design

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#95640]
### Details

At the time of writing the Goals screen is still in design p9Jlb4-emx-p2.  

When it is ready, implement new UI.

TBD: This will be behind a feature flag so we can test both the UI and persisting goals to the site option. 

### Checklist

- [x] Implement per Figma design.
   - [x] New goals
   - [x] Mobile/desktop layout
   - [x] Updated checkbox style
- [x] Ensure `intent` works as it should to maintain existing flows: 
   - [x] Write flow (aka `Publish a blog`)
   - [x] Sell flow (aka `Sell services or digital goods` and `Sell physical goods`)
   - [x] DIFM flow
   - [x] Import flow
   - [x] Build flow (aka all the other flows)

**Comment by autumnfjeld** [comment]
FYI:  checking that copy is good to go in this issue: https://github.com/Automattic/wp-calypso/issues/95694

**Comment by p-jackson** [comment]
I have a PR in progress: https://github.com/Automattic/wp-calypso/pull/95707

https://github.com/user-attachments/assets/4f0082f5-8df3-4553-b171-3a66f9656571


**Large Screen**
![CleanShot 2024-10-25 at 20 12 41@2x](https://github.com/user-attachments/assets/5d147ab9-8269-499f-a039-316d35dca1fc)

**Small Screen**
| Above the fold | Below the fold |
| --- | --- |
| ![CleanShot 2024-10-25 at 20 13 32@2x](https://github.com/user-attachments/assets/fb7bb306-2ee1-49b4-968b-cc87bee38754) | ![CleanShot 2024-10-25 at 20 13 49@2x](https://github.com/user-attachments/assets/db5bd762-6ed3-4294-9cdf-e6f7f2d7d388) |

**Comment by p-jackson** [comment]
@nuriapenya I've mostly completed a first pass at the implementation. Could I get some feedback on design?

## Checkbox style
For some reason I thought I remember seeing this big-checkbox-control component somewhere in Core WordPress, but I don't see it in the Gutenberg storybook. I notice the figma uses a different style with tighter margins and grey background. Were you following a Core component we can reuse? Or was this just a refresh on the existing custom component?

## Skip to dashboard button
I haven't labeled it `Go to WordPress Admin` like the mockup because we aren't (yet?) defaulting all new sites to the `wp-admin` experience. That'd be too big a change to cram into this task too. We can update this label when we make that change?
![Image](https://github.com/user-attachments/assets/d2d00f01-708f-4503-b568-becacc530d61)

## The skip button
I haven't added the `Skip` button beside the `Next` button. They'll both behave exactly the same way: advancing the user to the next step in the flow. Do we still want the `Skip` button if the user is already able to immediately skip using `Next`?

**Comment by p-jackson** [comment]
@Automattic/quake the goal screen changes are mostly implemented. I'm on GK rotation next week, so here's some things to consider should you keep working on it:

- Once the discussion at pfYzsZ-xE-p2 has died down we should consider adding the `String Freeze` label to the PR. Untranslated text during signup wouldn't be a great first impression
- Choosing the `DIFM` or `Import` options at the bottom of the screen takes the user to the right flow (and sets the correct site intent), but it leaves the goals array empty. Should we save the goals that just happened to be selected when they clicked the link to the custom flow?
- Unrelated, but context worth considering, this doesn't break the `/setup/newsletter` flow which also relies on goals and intent. The custom flows should continue to work fine as we make all our serious changes to the main flow.
- No other signup flows use this step. That should give us confidence to change it without breaking other things 🤞
- I'm not sure the way I included the dashboard icon is best practice.
	- Please note that I made tweaks to make sure it lined up just so 👨‍🍳😘
- Read the question above about checkbox styles. Is there an existing component that uses standard styles?

**Comment by zaguiini** [comment]
Checkbox PR: https://github.com/Automattic/wp-calypso/pull/95773
