### ISSUE TITLE
Bug: Multiple "Email Confirmed" toasts on login

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#96051]
### Quick summary

Two "Email Confirmed" toasts are shown after logging in for the first time after following a magic login link.

Page: https://wordpress.com/sites?verified=1

### Steps to reproduce

1. Create a new account
2. Follow the "Confirm your email" link in the activation email.
3. Enter your email address for a magic link
4. Follow the "Log in now" link in the email you receive.
5. `/sites?verified=1` and two "Email Confirmed" toasts are shown on the top right of the screen.

### What you expected to happen

Only one toast to be shown.

### What actually happened

![Image](https://github.com/user-attachments/assets/3e6cf0d8-dd9d-47a2-bab6-7e86ed3d3803)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on the platform - Couldn't replicate
 
📌 ACTIONS
- Requested author feedback

📌 Message to Author
@inaikem I couldn't replicate this using an incognito mode and a new account. Did you test this on a particular browser or was were you using a Chrome/browser profile instead of incognito?

**Comment by inaikem** [comment]
It was Chrome incognito!

I started the flow incognito and opened the email links in a new incognito window while the other flow was active in the original window. Hope that helps!
