### ISSUE TITLE
Feature Request: Allow copying sites on Commerce plans

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#96383]
### What

The Copy Site feature should be available to users with Commerce plans. 

### Why

Due to the feature being unavailable on Commerce plans, users must resort to migration plugins or manual migration methods to make a copy of a site on a Commerce plan. Adding this would provide feature parity with the Business plan. 

### How

It can work similar to the existing feature for Business plans, requiring the user to create a new site with a Commerce plan when they start the process.

**Comment by inaikem** [comment]
This has been an ongoing discussion in Fusion/DAMS. Moving straight into `Triaged` for review by Serently.

**Comment by rcrdortiz** [comment]
Heads up, these changes are now live. We can now copy sites under the Commerce plan.

**Comment by Jaykame** [comment]
Following up on this feature request, while Copy Site was implemented for Commerce plans, we've discovered a bug where it creates sites with demo content instead of copying the original site's content. The issue has been reported in Linear: https://linear.app/a8c/issue/DOTCOM-12974/copy-site-feature-on-commerce-plans-creates-demo-content-and-no-email
