### ISSUE TITLE
Reader Full-Post view: github embeds are stripped

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#9660]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/blogs/115552841/posts/560
2. Scrolling down a few paragraphs there is a section with a GitHub embed that does not display properly ('_Our create table statement then looks something like this_'): ![full-post view shot](https://cldup.com/CyItct-Uz8.png)

#### What I expected
For the embed to display as it does on the [actual blog](https://data.blog/2016/11/22/bulk-log-analytics-with-hive/):
![actual blog image](https://cldup.com/VD6pv6Qa7B.png),

**Comment by samouri** [comment]
@blowery  - turns out the way that you embed gists is pretty wacky.  It requires that you add js to your site so that it can `document.write` the table of code....I'm not positive we even want to support that.

Do you think it would be a good idea to add `https://gist.github.com/***` as a whiteslisted source for script tags?  If not then we probaby just need to close this issue as not-likely-to-be-resolved

**Comment by blowery** [comment]
Ugh. `document.write` after the page has already loaded really isn't allowed. Are there docs on how gist embeds work somewhere?

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
