### ISSUE TITLE
StepperTracking:  tracking issue with calypso_new_user_site_creation

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#96724]
### Is there any tracking issue with calypso_new_user_site_creation (New User Site Creations)?

- Although the share of new users and sites is consistent between the control and stepper, the stepper shows a significant (-10%) deviation in this metric, along with a misalignment with related metrics like User Registrations (24H), which shows an opposite trend (+9%). Details are available pbmxuV-3OC-p2.
- It may help to review how is_new_user and is_new_site properties are defined, recorded, and passed during signup in both Stepper and Start. However, I can’t suggest anything more specific at this time.

It's possible that is_new_user may be the thing to check first, especially the 7-days logic with control that may not be respecting it.

## What to do 

We could consider simplifying the logic of this event to something like:

if (isNewUser && isNewSite) then fire calypso_new_user_site_creation

and do away with all the logic related to isNewishUser and isNew7DUserSite from both start and stepper. It'll change slightly the numbers but it will make the implementation more solid and it's interpretation simpler.

**Comment by claudiucelfilip** [comment]
I noticed that the stepper flow emits the `calypso_new_user_site_creation` event through [this callback](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx#L118-L121), but there’s an issue: the higher-order async function is [running a](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/onboarding.ts#L178) `window.location.replace` that might prevent subsequent code, including emitting the event, from executing reliably. 
I couldn’t confirm this behavior, but it raises concerns about the guarantee of execution.

**Comment by escapemanuele** [comment]
cc @chriskmnds on this issue for `calypso_new_user_site_creation`.

It's strange because in our tests we did not encountered this problem, but it might be worth checking 🤔

**Comment by chriskmnds** [comment]
> I noticed that the stepper flow emits the `calypso_new_user_site_creation` event through [this callback](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx#L118-L121), but there’s an issue: the higher-order async function is [running a](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/onboarding.ts#L178) `window.location.replace` that might prevent subsequent code, including emitting the event, from executing reliably. I couldn’t confirm this behavior, but it raises concerns about the guarantee of execution.

I think the `window.location.replace` part happens after the processing step submits, so it should be safe? The pending action would be `createSite` from the previous step, and that looks to be set correctly. The way I'm reading the code:

- "create-site" step calls `setPendingAction`, calls submit
- "onboarding" flow navigates to "processing" step
- "processing" step runs pending action, records completion, calls submit
- "onboarding" flow redirects to checkout via `window.location.replace`

I could be wrong though. Can we double-check?

@escapemanuele / @claudiucelfilip

**Comment by MicBosi** [comment]
Thanks folks for looking into this!

From what I can see `calypso_new_user_site_creation` fires in the same [function](https://github.com/Automattic/wp-calypso/blob/7d705059efeaacbb090b669d7c8a43817097cc5b/client/lib/analytics/signup.js#L96C22-L96C45) as `calypso_signup_complete` although just a bit later. Based on the data we've been looking at during the Stepper experiment we didn't find issues with `calypso_signup_complete` which should probably (not surely since it fires just before) be affected by the redirect roughly as much as `calypso_new_user_site_creation` would be.

@skim1220 @escapemanuele I think we could consider simplifying the logic of this event to something like:

`if (isNewUser && isNewSite) then fire calypso_new_user_site_creation`

and do away with all the logic related to isNewisUser and isNew7DUserSite from both start and stepper. It'll change slightly the numbers but it will make the implementation more solid and it's interpretation simpler.

**Comment by escapemanuele** [comment]
I don't see anything wrong in simplifying the logic in both Start and Stepper. @chriskmnds do you see anything wrong in doing this?
