### ISSUE TITLE
Show emails page tab content for the case when no mailbox is there - upsell page

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#96819]
`Will be unblocked when https://github.com/Automattic/wp-calypso/issues/96673 is done`

When the user does not have any professional email/mailbox or forwarding, we show page with upsell info for professional emails. Now we'll show them in the Emails tab

![Image](https://github.com/user-attachments/assets/9008b629-1615-4705-9d0c-b6da399d25b3)

**Comment by bogiii** [comment]
Hey @Imran92,

I already see the upsell page when I run the Calypso locally with a feature flag turned ON.
There is a difference in design between the upsell component in Calypso and the provided Figma design.

What is the real task here? Match the design? Otherwise, the upsell component is already present (see attachment).

![Image](https://github.com/user-attachments/assets/9348aec7-13d1-4d1a-a439-cceb8507c256)

**Comment by Imran92** [comment]
@bogiii Yap it's showing the email component here because in my layout PR, I've put the Email component there. But it needs to fully match the[ figma design](https://www.figma.com/design/ePfz53j71KKDLWtuSm567A/All-Domains-Domain-Management-Revamp?node-id=4948-18120&node-type=frame&t=ysfbVUNxG6mjXom9-0)
