### ISSUE TITLE
Domain "Contact information" accordion won't stay open

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#97094]
While reviewing this ticket 9129502-zd-a8c we learned that the "Contact information" accordion section does not remain open, and closes when the API call finishes.

To reproduce the issue, go to the Manage Domain page /domains/manage/[domain]/edit/[domain] and try to open the "Contact Information" section.

![Image](https://github.com/user-attachments/assets/9bf4cea7-fc73-4755-877f-bbfe8d421566)

**Comment by DustyReagan** [comment]
I proposed a fix in https://github.com/Automattic/wp-calypso/pull/97093

**Comment by supernovia** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- While I don't have a domain on an atomic site, AFAIK this shouldn't matter

📌 FINDINGS/SCREENSHOTS/VIDEO
- Not including because it shows my personal info, but I can confirm the drop down opens briefly then closes automatically


📌 ACTIONS
- Triaged & assigned; @DustyReagan already as a fix suggested, so I'm marking this as Triaged and pinging the team just in case. :)

**Comment by StevenPartridge** [comment]
Has been tested and deployed by @rafaelgallani, closing
