### ISSUE TITLE
Move the design picker in front of the plans step

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#97208]
### Details

This should be implemented behind the `onboarding/goals-first` feature flag

### Checklist

- [ ]
- [ ]

**Comment by p-jackson** [comment]
WIP https://github.com/Automattic/wp-calypso/pull/97383

**Comment by candy02058912** [comment]
## Where we are currently:
We've merged
* https://github.com/Automattic/wp-calypso/pull/97383
* https://github.com/Automattic/wp-calypso/pull/97540

meaning that the design picker is showing at the right position and won't be duplicated when we redirect to the /site-setup flow.

## What is still not working
* `styleVariation` and `globalStyles` are not persisted on site creation

Currently, we cannot move forward if we select a Paid theme or Premium styles with what has been merged.
To pass the modal during testing, we can use this snippet from @zaguiini https://github.com/Automattic/wp-calypso/pull/97548

## Not part of this Issue
For the modal that needs to be removed, it will be part of https://github.com/Automattic/wp-calypso/issues/97535

**Comment by paulopmt1** [comment]
> we cannot move forward if we select a Paid theme or Premium styles
> For the modal that needs to be removed, it will be part of #97535

This will be addressed [in this task](https://github.com/Automattic/wp-calypso/issues/97535), which I'm working on. If it takes too much time I may [land that diff](https://github.com/Automattic/wp-calypso/pull/97383#issuecomment-2542562566) (implemented [in a draft here](https://github.com/Automattic/wp-calypso/pull/97548)) to allow us test it with premium themes.

> `styleVariation` and `globalStyles` are not persisted on site creation

To help with clear goals for each task, I'm moving this [to a new task](https://github.com/Automattic/wp-calypso/issues/97550) and closing this one, since we already reached its goal.

**Comment by paulopmt1** [comment]
> we cannot move forward if we select a Paid theme or Premium styles

Solution [is ready for review](https://github.com/Automattic/wp-calypso/issues/97535).
