### ISSUE TITLE
Task: Display the correct filtering of plans depending on user's domain or theme choices

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#97299]
### Details

This is a nice to have for the Dec 20 protype deadline. 

If the user chooses a premium theme or a domain, we do not show the free plan in column format. Instead we show this:

![Image](https://github.com/user-attachments/assets/c56e8c65-4487-448d-a8f8-58b03d38662d)

**Comment by taipeicoder** [comment]
@arthur791004 assigning this to you since you're already looking at the Plans page. Note that we already have this kind of logic for the /with-theme flow. e.g.: https://wordpress.com/start/with-theme/plans-theme-preselected?theme=solarone&theme_type=marketplace 

Let's look if we can extract the same logic to /plans, or maybe it already supports it.

**Comment by arthur791004** [comment]
I'll take a look when https://github.com/Automattic/wp-calypso/issues/97208 is completed 🙂

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/97587
