### ISSUE TITLE
Retain selected tab when domain is switched

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#97446]
In our new flyout view, when domain is switched, we open the default tab, that is the domain overview tab. So even if we are currently on the Emails tab, if we switch domains, the Overview will be opened for the new domain. Then we'll need to switch to the Emails tab.

Similar to how wordpress.com/sites work, we want to open the same tab when domains are switched

**Comment by donnapep** [comment]
@Imran92 I've been digging into the details of the Domains dashboard and how info gets passed around in order to try to fix this one. It seems that we'd need to pass some shared data / context (i.e. the selected tab) between the list and the details views in order to make this work. Right now it looks like we're only passing context for the list.

Looking at [how the Sites dashboard does it](https://github.com/Automattic/wp-calypso/blob/07be9b41eb428f2e10f023063a78754edeb26d35/client/sites/components/sites-dashboard.tsx#L345), I think this will be easier to implement and require less rework once DataViews are already in place. Any objection to moving this one to Blocked for the time being?

**Comment by donnapep** [comment]
For kicks, I checked out the [draft DataViews branch](https://github.com/Automattic/wp-calypso/pull/97677) and tried to fix this there, but it looks like the list of domains in the sidebar is still using the old structure (i.e. `<a>` elements with hardcoded `href` attributes instead of `<span>` tags).

**Comment by Imran92** [comment]
Thanks for diggint deeper into it @donnapep! You're totally right, it makes sense to wait until the DataViews conversion is done to avoid rework. I put together a quick POC here: https://github.com/Automattic/wp-calypso/pull/97710 with a very simple version of it. It's just a rough draft and also doesn’t handle subpages yet.

Though, I actually think we shouldn't worry about retaining subpages even in the future either since not all domains have all of them, so it won't be a 1:1 map for each domain, and it could make things unnecessarily complicated. Instead, we could just pick the email tab when we can surely detect, and fall back to the overview tab as the default.

Also, I used `window.location.pathname` in the POC, but we could switch to using the existing `withCurrentRoute` HOC later if we want—it’s probably cleaner. But I don’t think it’s a blocker at all. Totally okay to do it later as an improvement.

Let me know what you think!

**Comment by donnapep** [comment]
Putting this back in Doing as I see a potential solution now.

**Comment by donnapep** [comment]
@Imran92 Turns out I'm not totally right. 😆 There is a relatively simple way to do it as per https://github.com/Automattic/wp-calypso/pull/97719. I'll need to hand this one off to someone else on the team as there are still a few TODOs.
