### ISSUE TITLE
Task: Fix styles in /setup/onboarding/user

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#97570]
### Details

Fixable issues:
- The "Continue" button has the wrong colors

Things that might require a designer involved:
- The textbox has padding settings that differ from the Gutenberg component.
- Weird spacing between the "Continue" button and the "Back" link

![Image](https://github.com/user-attachments/assets/2842a807-1ccf-45c1-870c-91def08da61c)

### Checklist

- [ ] Fixable issue is fixed
- [ ] Designer is queried about the other issues

**Comment by zaguiini** [comment]
cc @nuriapenya

**Comment by nuriapenya** [comment]
@zaguiini thanks for spotting that! Yes, definetely need some fixing.

I created this skeleton reference because I'm seeing a lot of issues around padding misalignment and so on: W9xI27S6Swvw5Ku21EbZvn-fi-9134_65080 - I will be posting this on P2, but for now, you can take as reference for the spacings, and the general styling of the elements.

**Comment by arthur791004** [comment]
It's weird that the styles from `Card` component are bundled into the styles of the user step in stepper so some styles are overridden.

**Comment by arthur791004** [comment]
Proposed https://github.com/Automattic/wp-calypso/pull/97777 to resolve the issue by increasing the CSS priority and update the background color.

**Comment by arthur791004** [comment]
Closing it as the styles of the user step between the signup and stepper are the same now. We can open another issue if we want to make some style changes in the future.
