### ISSUE TITLE
Reader: top post "back" button taking me back to the wrong place

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/wp-calypso#9903]
This one is a bit odd so I wanted to first show you in a gif:

![reader-scroll](https://cloud.githubusercontent.com/assets/3220162/21021381/16246a88-bd2d-11e6-90bc-a7cc8491a2c8.gif)

What's happening is when I view the top post in the Reader, and then hit that "Back" button, I'm then sent back to a different spot (scrolling wise) then where I was.  Often it will be like this:

1. Click on Post # 3
2. Click Back
3. Click on Post # 1 (New post at the top)
4. Click back
5. Instead of going back to the top, I go back to where I had last been, to see Post # 3 which is further down the list and a bit confusing

Happening on the desktop app and in the browser (Chrome 55).

**Comment by fraying** [comment]
This has been happening for me, too. Any ideas, @blowery?

**Comment by blowery** [comment]
The way this works, we cache the last scroll position we saw and restore to that scroll position when you return. I would guess one of a few things is happening:

1. We're not storing the right scroll position. It's on a throttle, so there's a chance we're not grabbing the last setting. But the delay shown makes me think that's not it. Worth checking.
2. We have the "right" position, but that position is wrong when you go back. This could be due to the infinite list picking a different set of things to show, or getting the top and bottom placeholder heights wrong, or do to things in the stream *cough*iframes*cough* that havn't loaded when we set the scroll position, but then load and jank us elsewhere.

**Comment by samouri** [comment]
Would it make more sense to store the last `postKey` as opposed to the last y coordinate? Seems to me like that would convey intent and be more robust

**Comment by blowery** [comment]
> Would it make more sense to store the last postKey as opposed to the last y coordinate? Seems to me like that would convey intent and be more robust

That would only work for the Reader, as we're the only one who use postKeys.

**Comment by designsimply** [comment]
> Reader: Follow a link from post view. Browser back to get back to post view. <- Back to return to reader stream. Vscroll place in reader stream lost. I do this a lot, and it makes me wanna give up. 
— via @ryanboren (internal ref: p1488422599622997-slack-flow)

**Comment by lancewillett** [comment]
This has happened to me often, and in a long Reader session can be quite jarring as you lose the "flow" state you're in, reading and reading. :)

**Comment by blowery** [comment]
Had another thought on the possible cause here. If you expand a photo card, then pop into a post, then hit back, the photo card is likely no longer expanded. That's because we store that state at the component level and we lose it when we render the full post view. Same story for video iframes that you've opened with click to play. 

Instead of storing the absolute position, we should probably store the selected post key and it's offset from the top of the screen, then restore to that. Getting the timing right might be tricky, as things loading in above the post may cause it to jank a bit.
