### ISSUE TITLE
Fade out/fade in animation for dismissing recs

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9908]
When a rec is dismissed, could we make it fade out, and have the new one fade in?

Just want to introduce a delay so the user knows their click had an effect. Right now, it's so fast, it's almost hard to notice.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.


It appears this issue has not had any activity since early 2018. Due to that it is being closed with the label `Closed - Won't Fix`.
If this issue should remain open, please feel free to re-open this bug.
