### ISSUE TITLE
Taxonomy Manager: no option to "Make Default" when editing a category

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#9930]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/taxonomies/category/
2. Click on an existing category to edit it.
3. There is no option to make it the default category.

![screen shot 2016-12-09 at 13 52 39](https://cloud.githubusercontent.com/assets/426388/21049706/c3a55552-be16-11e6-876c-7acdafb30504.png)

4. I know I can make that change from the quick edit dropdown, but I would expect the option to be available in the full edit screen as well.

![screen shot 2016-12-09 at 13 53 27](https://cloud.githubusercontent.com/assets/426388/21049727/e0923e00-be16-11e6-9c3a-e72788767376.png)

**Comment by timmyc** [comment]
We opted to make the term edit form as close to what is seen in wp-admin as possible - and the option to set a category as default is not in the wp-admin edit category either.  I would argue that since the default category is a site option, and not an attribute of the term itself, it seems problematic to try and show it within the form.

I do still believe having the option exposed in the action menu is a big enhancement over the current flow of having to find a category in a long drop down to set a default.

I'm inclined to close this out, but will leave it open for others to comment - and perhaps this could be a future enhancement.

**Comment by jeherve** [comment]
Still an issue, but since I've been the only one to report it I suppose it can be closed now. Closing.
